### ISSUE TITLE
mongoose.CreateQuery not found (but other props fine)

### ISSUE THREAD

**Issue by dylanh724** [Automattic/mongoose#10002]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
See below:
![image](https://user-images.githubusercontent.com/8840024/110242322-81861b80-7f90-11eb-802b-ee6287fd6eaf.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Make an import statement and try to grab mongoose.**CreateQuery**
2. Notice it's not found, while most other imports are fine (successful import)

```json
{
    "compilerOptions": {
        "lib": ["es2020"],
        "module": "commonjs",
        "target": "es2020",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "incremental": true,
        "noImplicitAny": false,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "build",
        "types": ["node", "jest"],
        "baseUrl": "src",
        "paths": {
            "@lib/*": ["lib/*"]
        }
    },
    "include": ["src/**/*.ts"],
    "exclude": ["node_modules"]
}
```

**What is the expected behavior?**
CreateQuery is expected to exist, as everything else seems to exist just fine:
![image](https://user-images.githubusercontent.com/8840024/110242297-687d6a80-7f90-11eb-8aa3-fdd8e53fa3b5.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
package:
![image](https://user-images.githubusercontent.com/8840024/110242281-53a0d700-7f90-11eb-8ab2-5deb6b31fa43.png)

**Comment by dylanh724** [comment]
Wait ... but I can actually use `.create()` just fine. Think it's a ts config issue?
![image](https://user-images.githubusercontent.com/8840024/110242481-5a7c1980-7f91-11eb-97cd-18c61e050a59.png)

**Comment by vkarpov15** [comment]
Mongoose doesn't have a `CreateQuery` export. Not sure what it is you're looking for there.

I suspect the issue is that you're using `@types/mongoose` as well as Mongoose 5.11. If you're on Mongoose >= 5.11, please just remove your `@types/mongoose` dependency.
