### ISSUE TITLE
Population of optional array elements with different types of local and foreign keys is not working

### ISSUE THREAD

**Issue by MikeKoval** [Automattic/mongoose#10003]
**Do you want to request a *feature* or report a **?**

Bug

**What is the current behavior?**

Population of optional array elements with different types of local and foreign keys is not working

**If the current behavior is a bug, please provide the steps to reproduce.**

There are schemas:

```
const distribution = new mongoose.Schema({
id: {
type: String,
get: (v) => new mongoose.Types.ObjectId(v),
}
title: String,
});

distribution.virtual('details', {
  ref: 'Distribution',
  localField: 'id',
  foreignField: '_id',
  justOne: true,
});

const order = new mongoose.Schema({
distributions: [Distribution]
});
```

There is data in db:

```
{ _id: <some ObjectId>, distributions: [{ id: 'String' }, { id: 'String' }] },
{ _id: <some ObjectId> } // means that distributions field might be missing for record
....
```

There is query:

```
const items = await Order.find()
.skip(skip)
.limit(limit)
.populate('distributions.details', 'title')
.exec();
```

In result i get strange behavior when part of items get distributions elements with "detail" field, but others miss "detail" field.
Interesting that it's working just fine if i use findOne :) 
Wondering, is getter respected for population?
Here is not working case where distributions field might be missing https://prnt.sc/10fi8f6
Here is working case when i updated db with empty array where field was missing - https://prnt.sc/10fiagn

**What is the expected behavior?**

Population worked fine.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.11.19
node.js v12.21.0

**Comment by vkarpov15** [comment]
I'm unable to repro this, below script shows that Mongoose applies the `id` getter and that certain `details` are `null` if they point to a non-existent id. Please modify the below script to demonstrate your issue:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const distribution = new mongoose.Schema({
    id: {
      type: String,
      get: (v) => new mongoose.Types.ObjectId(v),
    },
    title: String,
  });

  distribution.virtual('details', {
    ref: 'Distribution',
    localField: 'id',
    foreignField: '_id',
    justOne: true,
  });

  const order = new mongoose.Schema({
    distributions: [distribution]
  });
  const Order = mongoose.model('Order', order);
  const Distribution = mongoose.model('Distribution', mongoose.Schema({ name: String }));

  const d = await Distribution.create({ name: 'test' });
  await Order.create([
    { distributions: [{ id: d._id }, { id: new mongoose.Types.ObjectId() }] },
    { distributions: [{ id: new mongoose.Types.ObjectId() }] }
  ]);

  const items = await Order.find()
    .populate('distributions.details')
    .exec();
  console.log(items.map(d => d.toObject({ virtuals: true }).distributions));
}
```

**Comment by MikeKoval** [comment]
Hi! Thank you for help)

1. By this "Population of optional array elements with different types of local and foreign keys is not working" i mean
not classic
 { distributions: [{ id: new mongoose.Types.ObjectId() }] }
 but
  { distributions: [{ id: new mongoose.Types.ObjectId().toString() }] }
  2. { _id: <some ObjectId> } // means that distributions field might be missing for record
  By this I mean that collection simply might not have field with distributions, Model.prototype.create sets default value (empty array) for fields that are missed that's why you example was not working.
  
Here is what i get

`[
    {
        "_id": "60697d103110093c88a8cba8",
        "total": 2,
        "__v": 0,
        "distributions": [],
        "id": "60697d103110093c88a8cba8"
    },
    {
        "_id": "60697d103110093c88a8cbab",
        "total": 5,
        "distributions": [
            {
                "id": "60697d103110093c88a8cba6"
            },
            {
                "id": "60697d103110093c88a8cba3"
            }
        ],
        "__v": 0,
        "id": "60697d103110093c88a8cbab"
    },
    {
        "_id": "60697d103110093c88a8cba7",
        "total": 1,
        "distributions": [
            {
                "id": "60697d103110093c88a8cba0"
            },
            {
                "id": "60697d103110093c88a8cba3"
            }
        ],
        "__v": 0,
        "id": "60697d103110093c88a8cba7"
    },
    {
        "_id": "60697d103110093c88a8cba9",
        "total": 3,
        "distributions": [
            {
                "id": "60697d103110093c88a8cba2"
            }
        ],
        "__v": 0,
        "id": "60697d103110093c88a8cba9"
    },
    {
        "_id": "60697d103110093c88a8cbaa",
        "total": 4,
        "__v": 0,
        "distributions": [],
        "id": "60697d103110093c88a8cbaa"
    }
]
`

With this script

`'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const distribution = new mongoose.Schema({
    id: {
      type: String,
      get: (v) => new mongoose.Types.ObjectId(v),
    },
    title: String,
  }, { _id : false });

  distribution.virtual('details', {
    ref: 'Distribution',
    localField: 'id',
    foreignField: '_id',
    justOne: true,
  });

  const order = new mongoose.Schema({
    distributions: [distribution],
    total: Number,
  });
  const Order = mongoose.model('Order', order);
  const Distribution = mongoose.model('Distribution', mongoose.Schema({ title: String }));

  const dists = await Distribution.create([
    { title: 'd1' },
    { title: 'd2' },
    { title: 'd3' },
    { title: 'd4' },
    { title: 'd5' },
    { title: 'd6' },
    { title: 'd7' }
  ]);
  const orders = await Order.create([
    { total: 1, distributions: [{ id: dists[0]._id.toString() }, { id: dists[3]._id.toString() }] },
    { total: 2 },
    { total: 3, distributions: [{ id: dists[2]._id.toString() }] },
    { total: 4 },
    { total: 5, distributions: [{ id: dists[6]._id.toString() }, { id: dists[3]._id.toString() }] }
  ]);

  await Order.updateMany({ total: { $in: [2, 4] } }, { $unset: { distributions: true } });

  const items = await Order.find()
    .populate('distributions.details', 'title')
    .exec();

  console.log(JSON.stringify(items.map(d => d.toObject({ virtuals: true })), null, 4));
}
`

**Comment by MikeKoval** [comment]
Thanks)
