### ISSUE TITLE
cannot add an object within an object

### ISSUE THREAD

**Issue by slayt12** [Automattic/mongoose#10012]
mongoose version: 5.11.19

Say I have a mongodb document I'm trying to update. The schema is level1 (object)> level2  (object) > "objects". 
If I want to add another object to the end, what is the method to do that? Do I use findoneandupdate?
I'm trying to append an object to an object
As of right now, it overwrites whatever is in the object
 

    await base.findOneAndUpdate({ baseURL: contentObject.basURL },
                        {
                            "links.subPageURLs": {
                                [contentObject.subPage]: contentObject.links.subPageurls[contentObject.subPage]
                            },
                            "content.subPageContent": {
                                [contentObject.subPage]: contentObject.content.subPageContent[contentObject.subPage]
                            }
                                }
                            }
                        },
                        { upsert: true }, (err, doc) => {
                            console.log(err)
                            db.close()
                        })

**Comment by vkarpov15** [comment]
What do you mean by "add another object to the end"? Hard to tell without seeing what your schemas look like.
