### ISSUE TITLE
Force install mongoose 5.12

### ISSUE THREAD

**Issue by UncleVic** [Automattic/mongoose#10018]
Hi there!

I use mongoose 5.10.18 because I have correct my own index.d.ts
In my werf.yaml in install section exist a string ```nmp audit fix```
Long time deployment worked correct but not today. Today deployment was crashed because ```nmp audit fix``` forcible installed mongoose@5.12.0.
Why did they do it?

**Comment by vkarpov15** [comment]
I'm unfortunately not sure why it would pick 5.12.0 exactly: we didn't change any `package.json` dependencies between 5.11.20 and 5.12.0, https://github.com/Automattic/mongoose/compare/5.11.20...5.12.0, and v5.11.20 isn't deprecated.
