### ISSUE TITLE
$pull with multiple field not working in typescript. 

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [Automattic/mongoose#10024]
![Screenshot 2021-03-13 at 2 13 58 PM](https://user-images.githubusercontent.com/64843262/111024867-f0d39380-8406-11eb-9f31-5498f7c6d98b.png)

npm detail.
 "@types/mongoose": "^5.10.3",

**Comment by kodermax** [comment]
the same

**Comment by vkarpov15** [comment]
Without schema definitions, hard to tell what the issue is. Is `favourite` defined in your schema?
