### ISSUE TITLE
Error: cyclic dependency detected

### ISSUE THREAD

**Issue by pxpcandy** [Automattic/mongoose#10023]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** I'm getting the error "cyclic dependency detected" when I try setting the data of a model

**If the current behavior is a bug, please provide the steps to reproduce.** Find a model, set the data of the model

```js
       Model.find({
           channel: message.mentions.channels.first()
        }, (err, data) => {
            if(err) return console.log(err);

            const _data = new Data({
                guildID: message.guild.id,
                channelID: logchannel.id
            });
        
            const embed = new MessageEmbed()
            .setTitle('Log channel set :white_check_mark:')
            .addField('Your server\'s log channel has been set', _data.channelID, true)
            .setColor('GREEN')
    
            message.channel.send(embed);
        });
```

**What is the expected behavior?** Set the data of the model

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.** v14.15.0

Mongoose version: 5.12.0

**Using Discord.js if that is helpful**

**Comment by vkarpov15** [comment]
Should be fixed with 5.12.1, see #9900
