### ISSUE TITLE
schema type not working with aggregation

### ISSUE THREAD

**Issue by Kraysh** [Automattic/mongoose#10032]
node: v12.19.0
mongoose: v5.12.0
mongo: v4.4.4

schema:
```
const UserSchema = new Schema({
    _id: {
      type: String,
      require: true
    },
    paused: {
      type: Boolean,
      default: false
    },
    name: {
      type: String,
      default: ''
    },
    type: {
      type: String,
      enum: ['private', 'group']
    },
})

const PasswordSchema = new Schema({
    password: {
      type: String,
      require: true
    },
    used: {
      type: Boolean,
      default: false,
    },
    usedBy: UserSchema
})
```
with findOne, works fine
`await Password.findOne({"usedBy._id": 123}) // 123 is converted to string`

but with aggregate, the _id is not converted to string
`await Password.aggregate().match({ "usedBy._id": 123 }) // 123 keeps number, so the query returns null`

this is expected or is a bug?

**Comment by Kamikadze4GAME** [comment]
This is expected and mentioned in the second paragraph of the notes at [Aggregate docs](https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate) 

> Mongoose does not cast pipeline stages. The below will not work unless _id is a string in the database

**Comment by vkarpov15** [comment]
@Kamikadze4GAME is right, Mongoose doesn't cast aggregation pipelines. That's because aggregation pipelines can, and usually do, change the shape of the data in MongoDB. If you need casting, you can use `find()`, or you can use the [`Query#cast()` method](https://mongoosejs.com/docs/api/query.html#query_Query-cast) to cast the filter:

```javascript
await Password.aggregate().match(new Query({ "usedBy._id": 123 }).cast(Password).getFilter())
```
