### ISSUE TITLE
Getting MongoError: Authentication failed when authenticating with url

### ISSUE THREAD

**Issue by templar-git** [Automattic/mongoose#10034]
NodeJS version: 14.16.0
MongoDB server version: 4.2.12
MongoDB Node driver version: 3.6.4
Mongoose version: 5.12.0

Now, when I connect to a MongoDB server without using the user & password url. As seen here:
`await mongoose.connect("mongodb://${remote}/${dbName}", {useNewUrlParser: true, useUnifiedTopology: true})`
Everything works perfectly fine.

But when I include "user:pass@", as seen here:
`await mongoose.connect("mongodb://${user}:${pass}@${remote}/${dbName}", {useNewUrlParser: true, useUnifiedTopology: true})`

I get,
> MongoError: Authentication failed.

All the URL's in the snippets are the ones I use in my code, I've looked at several other stackoverflow threads and I just can't seem to find a solution.

Any help is appreciated :)

**Comment by templar-git** [comment]
Also to note that neither the username nor the password have any non alphanumeric characters

**Comment by Jatin-MYST** [comment]
Try this:
https://stackoverflow.com/questions/45576367/mongoose-connection-authentication-failed

**Comment by templar-git** [comment]
> Try this:
> https://stackoverflow.com/questions/45576367/mongoose-connection-authentication-failed

That worked perfectly, I don’t know how I didn’t stumble upon that. Thank you!
