### ISSUE TITLE
Mongoose continue to query "downed" server.

### ISSUE THREAD

**Issue by daveteu** [Automattic/mongoose#10037]
## Docker Environment
Setting mongo string to the standard mongo://host1:port,host2:port,host3:port/db?retryWrites=true&w=majority&replicaSet=my-replica&authSource=admin&readPreference=primaryPreferred

#### Problem 1
When attempting  to rollrestart the mongo replica servers, mongoose will still attempt to use the restarting server (e.g. primary) even though on('disconnect') was emitted. 

There will be success queries via the other replica, but attempt to query the "restarting" server is called and hence, "stalled" the app.

#### Problem 2

.on('disconnect') event should be emitted only when disconnected from ALL the replicas (as per document), however it's emitting even though my other 2 replicas are alive.

#### Problem 3
When the "restarting" mongodb server is online, moongoose is unable to "auto-recover" and detect the server. I have to manually restart all the node applications.

#### Additional Problem 4

.on('fullsetup') and .on('all')  not called even though it's a replica set

```
Update online error MongooseServerSelectionError: getaddrinfo ENOTFOUND primary
    at Function.Model.$wrapCallback (/code/node_modules/mongoose/lib/model.js:4882:32)
    at /code/node_modules/mongoose/lib/query.js:4373:21
    at /code/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/code/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at model.Query.exec (/code/node_modules/mongoose/lib/query.js:4372:10)
    at model.Query.Query.then (/code/node_modules/mongoose/lib/query.js:4455:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'goreal-replica',
    maxSetVersion: 25,
    maxElectionId: 7fffffff00000000000000b2,
    servers: Map(3) {
      'primary:27017' => [ServerDescription],
      'secondary:27017' => [ServerDescription],
      'tertiary:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: 30,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9
  }
}
```

## Expected Behavior

Mongoose should attempt to connect, but continue to use other replica servers until the "restarting" server is ready.

## Addtional Info

The following is my rs.isMaster() information from my replica.

> 
> 	"topologyVersion" : {
> 		"processId" : ObjectId("605362ed4a011f4b1a2d67f9"),
> 		"counter" : NumberLong(7)
> 	},
> 	"hosts" : [
> 		"primary:27017",
> 		"secondary:27017",
> 		"tertiary:27017"
> 	],
> 	"setName" : "my-replica",
> 	"setVersion" : 25,
> 	"ismaster" : true,
> 	"secondary" : false,
> 	"primary" : "primary:27017",

**Comment by vkarpov15** [comment]
Are you using `useUnifiedTopology: true`?
