### ISSUE TITLE
Export `DocumentQuery` for backwards compatibility

### ISSUE THREAD

**Issue by zeeshanalisyed** [Automattic/mongoose#10036]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Not sure, because of two typing files which is one from this same project and one is ```@types/mongoose``` because of that was having an import error of ```DocumentQuery``` import. Not Sure which typing file should I use, now if I remove index.d.ts file from the ```node_modules/mongoose``` this error is not coming up anymore, because @types/mongoose have  ```DocumentQuery``` export. 

**If the current behavior is a bug, please provide the steps to reproduce.**

#### Code
```typescript
import { 
   Document, 
   DocumentQuery, // this import is giving an error that it is not exported
} from "mongoose";

```
##### tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "esModuleInterop": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "pretty": true,
    "types": [
      "jest",
      "node"
    ],
    "typeRoots" : [
      "node_modules/@types",
      "src/types"
    ],
    "sourceMap": true,
    "target": "es6",
    "baseUrl": "./",
    "lib": [
      "ES2019"
    ]
  },
  "exclude": [
    "node_modules",
  ]
}
```

**What is the expected behavior?**
Not Sure, don't know which typing file is the final one.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
this is not related to any of these but still I will include the versions below.
Node.js: 14.16.0
Mongoose: 5.12.0
MongoDB: 3.4

**Comment by vkarpov15** [comment]
You should use the Mongoose `index.d.ts`, not `@types/mongoose`, unless you have a good reason to.

Why are you using `DocumentQuery` instead of just `Query`?

**Comment by zeeshanalisyed** [comment]
> You should use the Mongoose `index.d.ts`, not `@types/mongoose`, unless you have a good reason to.
> 
> Why are you using `DocumentQuery` instead of just `Query`?

I am not using that myself it is being used in one of the dependencies in my project so maybe I will correct them that also helps, I will create a PR on their project.
Thank you for your help, I am going to close this.

**Comment by vkarpov15** [comment]
We'll add a `DocumentQuery` export for backwards compatibility. Can you please let me know which dependency this is?

**Comment by gustavofusco** [comment]
Thanks @zeeshanalisyed !!!
