### ISSUE TITLE
Property 'lean' does not exist on type 'Aggregate<any[]>'

### ISSUE THREAD

**Issue by DoneDeal0** [Automattic/mongoose#10047]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When adding .lean() in the end of an aggregation query to speed it up, typescript claims that: `Property 'lean' does not exist on type 'Aggregate<any[]>'` . 

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
return User.aggregate([
      {
        $facet: {
          data: [
            { $match: { username: { $ne: username } } },
            { $skip: this.getPagesToSkip(page) },
            { $limit: LIMIT },
            { $sort: { createdAt: 1 } }
            { $project: { _id: 1, username: 1 } },
          ],
          hits: [{ $count: "total" }],
        },
      },
    ]).lean();
```

```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es6"],
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": false,
    "noImplicitAny": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "baseUrl": "./",
    "paths": {
      "@database/*": ["src/database/*"],
      "@mails/*": ["src/mails/*"],
      "@models/*": ["src/models/*"],
      "@routers/*": ["src/routers/*"],
      "@routes/*": ["src/routes/*"],
      "@utils/*": ["src/utils/*"]
    }
  },
  "exclude": ["node_modules"]
}
```

**What is the expected behavior?**
I should be able to use lean() on aggregation to speed up my requests. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^5.12.0",
"@types/mongoose": "^5.10.3",

**Comment by vkarpov15** [comment]
`lean()` is not a method of the Aggregate class, see [code](https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/lib/aggregate.js) and [docs](https://mongoosejs.com/docs/api/aggregate.html). There's no point to using `lean()` with aggregations because Mongoose doesn't hydrate the results of an aggregation, so all aggregations are "lean".
