### ISSUE TITLE
Schema-level collation and text index issue

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#10044]
https://github.com/Automattic/mongoose/commit/6c78829689f8addc26ef0b2ba8fb321e5d86733d#commitcomment-48220571

**Comment by IslandRhythms** [comment]
Confirmed, however this seems to be on Mongodb's end rather than ours.
Script:
```
'use strict';
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const boardSchema = new Schema({
    name: { type: String, required: true },
    ownerId: { type: Schema.ObjectId, required: true, ref: "User" },
  }, {collation: {
      locale: 'en',
      strength: 2
  }});
  boardSchema.index({name: "text"});
  const Board = mongoose.model("Board", boardSchema);
  await Board.init();
  const indexes = await Board.listIndexes();
  console.log(indexes);
};
```

From Mongodb

```
The following indexes only support simple binary comparison and do not support collation:

-    text indexes,
-    2d indexes, and
-    geoHaystack indexes.

```

However it does offer a way to overcome this problem

```
To create a text, a 2d, or a geoHaystack index on a collection that has a non-simple collation, 
you must explicitly specify {collation: {locale: "simple"} } when creating the index.
```

**Comment by jarretmoses** [comment]
@IslandRhythms @vkarpov15 perhaps I am not following this change correctly but since this got merged it I am no longer able to add a index of `2dsphere` either through the schema or with .index with collation of locale 'simple'

**Comment by vkarpov15** [comment]
@jarretmoses can you please provide a code sample that demonstrates what you're trying to do?

**Comment by jarretmoses** [comment]
`
const outputOptions = {
  toJSON: {
    virtuals: true,
    transform: (doc, ret) => {
      delete ret.password;
      delete ret.__v;
      delete ret._id;
    },
  },
  toObject: {
    virtuals: true,
  },
  autoCreate: true,
  timestamps: true,
};

const geoSchema = mongoose.Schema({
  type: String,
  coordinates: [Number],
  lat: Number,
  lng: Number,
}, outputOptions);

const unitSchema = mongoose.Schema({
  geo: {
    type: geoSchema,
    index: '2dsphere',
  },
}, outputOptions);

// Ive tried (and a bunch of combinations of the following)

const unitSchema = mongoose.Schema({
  geo: {
    type: geoSchema,
  },
}, {
  ...outputOptions, 
  collation: {locale: 'simple'}
});

unitSchema.index({geo: '2dsphere'})
`

**Comment by jarretmoses** [comment]
@vkarpov15 things seem to be working for me again after `v5.12.4`. I havent had time to look into what but perhaps it was the mongo driver update. Anyways this is no longer an issue with my setup
