### ISSUE TITLE
strict: false schema not updating with update* queries

### ISSUE THREAD

**Issue by zacharytyhacz** [Automattic/mongoose#10045]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

I am trying to update one field of an object within a model, but the field is not updating but the `updatedAt` field is updating.

I want to update my User model's `profile.name` field FROM `"old name"` to `"Zachary Andrew"`. It is not updating.

Here is an initial basic setup:
```typescript
const mongoose = require('mongoose');

const ProfileSchema = new mongoose.Schema({
    otherField: { type: String, required: false, default: "" },
    anotherField: { type: String, required: false, default: "" },
    // gets added as non-schema, hence strict: false
}, { strict: false });

const userSchema = new mongoose.Schema({
    profile: { type: ProfileSchema, required: true },
}, {
    timestamps: true,
    versionKey: false,
});

const User = mongoose.model('User', userSchema);

// insert initial user that i want to update:
const initialUser = new User({
    profile: {
	otherField : "foo bar",
	anotherField : "something cool",
        name: "old name"
    }
});

// does not throw error; this initial user object gets saved.
await initialUser.save();

const profileField = "name";
const key = `profile.${profileField}`;

const updates = {
    [key] : "Zachary Andrew"
}
console.log(updates);
// { "profile.name" : "Zachary Andrew" }
// i have even tried with $set, still same result; no change.

// no error gets thrown.
const result = await User.findByIdAndUpdate(userId, updates);

// happens with updateOne too
// const result = await User.updateOne({ _id : userId }, updates);

console.log(result);
// { n: 1, nModified: 1, ok: 1 }
```

My model in mongo DOES NOT get updated.
    - BUT THE `updatedAt` field gets updated

```mongo
> db.users.find().pretty();
{
	"_id" : ObjectId("605516673c7fc50e39bd8b8d"),
	"profile" : {
		"otherField" : "foo bar",
		"anotherField" : "something cool",
		"name" : "old name", // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< still says old name
	},
	"createdAt" : ISODate("2021-03-19T21:23:51.169Z"),
	"updatedAt" : ISODate("2021-03-19T21:43:43.518Z") // <<<<<<<<<<<<<<<<< THIS IS NOW, JUST UPDATED
}
```

when i use:
```typescript
mongoose.set('debug', true);
```

The debug log when this executes does not even include my update query, just my filter:
( missing my `{ "profile.name" : "Zachary Andrew" }` )
```bash
Mongoose: users.findOneAndUpdate({ _id: ObjectId("605516673c7fc50e39bd8b8d") }, { '$setOnInsert': { createdAt: new Date("Fri, 19 Mar 2021 21:59:17 GMT") }, '$set': { updatedAt: new Date("Fri, 19 Mar 2021 21:59:17 GMT") }}, { upsert: false, projection: {}, returnOriginal: true })
```

**What is the expected behavior?**
The update query properly updates the `profile.name` to `"Zachary Andrew"`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
$ node -v
v14.9.0
```

```
mongoose version:  5.12.1
```

```
$ mongo --version
MongoDB shell version v4.4.0
Build Info: {
    "version": "4.4.0",
    "gitVersion": "563487e100c4215e2dce98d0af2a6a5a2d67c5cf",
    "modules": [],
    "allocator": "system",
    "environment": {
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```

**Comment by Jatin-MYST** [comment]
```js
const ProfileSchema = new mongoose.Schema({
    otherField: { type: String, required: false, default: "" },
    anotherField: { type: String, required: false, default: "" },
    // gets added as non-schema, hence strict: false
}, { strict: false });
```
you are missing `name` field in the sub-schema.

**Comment by IslandRhythms** [comment]
@zacharytyhacz ^

**Comment by zacharytyhacz** [comment]
@IslandRhythms @Jatin-MYST  My schema has to be `strict: false` because I want to add custom / many different fields that will be inconsistent to this profile object. 

I can try replacing the profile field schema type with just `type: Object` and see how that goes - I will get back to you guys

**Comment by IslandRhythms** [comment]
@zacharytyhacz did you try setting `strict: false` in the `userSchema`?

**Comment by zacharytyhacz** [comment]
@IslandRhythms  i have not, but I did fix it by make the schema like this:

```typescript
const userSchema = new mongoose.Schema({
    // set type to just 'Object', updating works like a charm now; no separate strict: false schema
    profile: { type: Object, required: true, default: {} },
}, {
    timestamps: true,
    versionKey: false,
});
```

**Comment by vkarpov15** [comment]
The way to fix this would be using `strict: false` or fixing your schema to list `name` as a property in `ProfileSchema`.

**Comment by zacharytyhacz** [comment]
I would also like to point out that I found `useNestedStrict` in the documentation: https://mongoosejs.com/docs/guide.html#useNestedStrict 

could be useful

**Comment by zacharytyhacz** [comment]
> The way to fix this would be using `strict: false` or fixing your schema to list `name` as a property in `ProfileSchema`.

I have to disagree with your solution @vkarpov15 

My schema is set to `strict: false` so I can add many custom fields to it. Additionally, with 2 fields that are always required; hence the:
```typescript
const ProfileSchema = new mongoose.Schema({
    alwaysPresentField: { type: String, required: true, default: "" },
    anotherAlwaysPresentField: { type: String, required: true, default: "" },
    // other custom fields may be added as non-schema, therefore i need strict: false
}, { strict: false });
```

technically, my code to update this ProfileSchema SHOULD work

**Comment by vkarpov15** [comment]
@zacharytyhacz I don't understand the issue you're experiencing, can you please open a new issue and follow the issue template?
