### ISSUE TITLE
Types: Property 'project' does not exist on type 'Aggregate<...>'.

### ISSUE THREAD

**Issue by stgogm** [Automattic/mongoose#10043]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

The `project` method is missing from the `Aggregate` interface.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
import { createConnection } from 'mongoose';

const db = createConnection();
const aggregateResults = await db
  .model('SomeModel')
  .aggregate<SomeModelDocument>()
  .project({ // <<-- Not recognized
    someField: true
  });
```

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES2019",
    "rootDir": "./src",
    "outDir": "./lib",
    "declaration": true,
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "lib": ["ES2019"]
  },
  "include": ["src/**/*", "test.ts"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**What is the expected behavior?**

The `project` method does indeed [exists in the aggregate class](https://github.com/Automattic/mongoose/blob/425f35a45ce02297efd4463b022a25510686aaf7/lib/aggregate.js#L217).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

||||
|-|---:|-|
| Node | `v14.16.0` | |
| Mongoose | `v5.12.1` | |
| MongoDB | `v4.0.14` | in-memory test |

**Comment by jerkly** [comment]
https://github.com/Automattic/mongoose/commit/c2f90f2f4873bc0c71e788a90dfabc6afc4bed1a

**Comment by vkarpov15** [comment]
Looks like this got unintentionally removed by https://github.com/Automattic/mongoose/commit/a31efa18311a8f054728d26199756109dfa42f1a#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8. Will be added back in 5.12.2, sorry for the inconvenience! :+1:
