### ISSUE TITLE
Adding a object in existing object

### ISSUE THREAD

**Issue by kamrantekkit** [Automattic/mongoose#10041]
**Do you want to request a *feature* or report a *bug*?**
Requesting for help

Node.js version: 14.7.0
mongoose version: 5.12.0
mongoDB: 3.6.5

**Code**
` 
serverinfo.findOneAndUpdate({ serverID: guildID },  {"serverSettings.reply": true}), (err, data) => {
    if (err) console.log(err);
}
`
Am trying to figure out how to add a new object inside an existing object. 

**Schema Used**

`
const serverSchema = mongoose.Schema({
    name: String,
    serverID: String,
    serverSettings: Object,
    storage: Object,
}, {minimize: false})
`

**Comment by vkarpov15** [comment]
Can you please explain what "add a new object inside an existing object." means?

**Comment by kamrantekkit** [comment]
> Can you please explain what "add a new object inside an existing object." means? Preferably with a code sample.

i was trying to add a new key/attribute to the object but it wasnt working. 
I figured out later i had to mark it for it apply changes.
