### ISSUE TITLE
Populate Virtual schema .find return value of undefined

### ISSUE THREAD

**Issue by rj3087** [Automattic/mongoose#10051]
Question, I'm having issue of return value of undefined if i use the .find({}), but when replace this by .findOne() the return value is correct. But the problem is there's only one return value. I'm trying to populate my postSchema by using virtual schema, so that I can get the avatarPhoto from my userSchema. Both of this schema has username key value.

userScheme

```javascript
const userSchema = mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
    },
    fullname: {
      type: String,
      required: true,
    },
    username: {
      type: String,
      required: true,
      unique: true,
    },
    avatarPhoto: {
      type: String,
    },
);
const userModel = mongoose.model('userModel', userSchema);
export default userModel;
```

postSchema

```javascript
import mongoose from 'mongoose';
import User from '../models/userModel.js';

const postSchema = mongoose.Schema(
  {
    username: {
      type: String,
    },
    description: {
      type: String,
    },
    postImageCollection: {
      type: Array,
    },
  {
    toObject: { virtuals: true },
    toJSON: { virtuals: true },
  }
);

postSchema.virtual('user', {
  ref: 'userModel',
  localField: 'username',
  foreignField: 'username',
  justOne: true,
});

const postModel = mongoose.model('postModel', postSchema);
export default postModel;
```

Controller

```javascript
export const getUserRelatedPost = asyncHandler(async (req, res) => {
  const postData = await postModel.find({}).populate('user');
  console.log(postData.user.avatarPhoto);
});
```

**Comment by vkarpov15** [comment]
When you do `const postData = postModel.find({}).populate('user')`, `postData` will be an array, not an object. So `postData.user.avatarPhoto` will most likely throw an error. Is that your issue?

**Comment by rj3087** [comment]
Yap, I just want to populate the virtual schema so that I can display the avatarPhoto everytime some create a post.

**Comment by vkarpov15** [comment]
I don't understand what you mean by "Yap, I just want to populate the virtual schema so that I can display the avatarPhoto every time user creates a post. Coz, if I used the .findOne I only got one user avatarPhoto." can you please elaborate?
