### ISSUE TITLE
Typescript types do not seem to handle $currentDate correctly

### ISSUE THREAD

**Issue by sean-daley** [Automattic/mongoose#10058]
We recently upgraded to 5.12.2 and all of our update calls which use $currentDate are now failing to "compile" with errors like:
```
src/services/jobRunUtils.ts:120:23 - error TS2322: Type 'true' is not assignable to type 'undefined'.

120       $currentDate: { endDate: true },
```

We upgraded from 5.11.19 to 5.12.2. It looks like this is a change in behavior introduced in 5.11.20.

I don't have an easily self-contained STR but I did modify test/typescript/queries.ts in the mongoose repo and that does reproduce something sort of similar.

Just modify the ITest interface likeso:
```
interface ITest extends Document {
  name?: string;
  age?: number;
  parent?: Types.ObjectId;
  tags?: string[];
  docs?: ISubdoc[];
  endDate?: Date;
}
```

And then add the following new test:
```
Test.findOneAndUpdate({ name: 'test' }, { $currentDate: { endDate: true } });
```

This is showing an error of:
```
(property) endDate?: never
Type 'boolean' is not assignable to type 'never'.ts(2322)
```

Note, I also tried making endDate mandatory instead of optional (our code has an optional one which is why i did that) but it still failed to compile with the same error.

The errors are slightly different (undefined vs never) so I'm not sure if I'm reproducing exactly the same behavior but hopefully there's enough info here to help? Thanks.

**Comment by IslandRhythms** [comment]
```
import { model, Schema, Model, Document, connect, connection } from 'mongoose';


interface IUser extends Document {
  email?: string;
  firstName?: string;
  lastName?: string;
  endDate?: Date;
}

const UserSchema: Schema = new Schema({
  email: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  endDate: {type: Date, required: true}
});

const User: Model<IUser> = model('User', UserSchema);
(async function() {
  await connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false
  });
await connection.dropDatabase();
  const user: IUser = new User({
    email: 'bill@microsoft.com',
    firstName: 'Bill',
    lastName: 'Gates',
    endDate: Date.now()
  });
  await user.save();

  const test: any = await User.findOneAndUpdate({firstName: 'Bill'}, {$currentDate: {endDate: Date.now()}});
  test.save();
  console.log('Done', test);
})();
```

**Comment by sean-daley** [comment]
So it looks like this is due to the following re-declaration in index.d.ts

```
  /** The Mongoose Date [SchemaType](/docs/schematypes.html). */
  export type Date = Schema.Types.Date;
```

At least if I comment that out then date types seem to "compile" correctly now. At least for currentDate. I assume that's not the correct fix as there are some references in there to Date which could require the new type? Maybe? At least it's an explanation as to what seems to be happening.
