### ISSUE TITLE
Typescript - Aggregate typings missing "project"

### ISSUE THREAD

**Issue by devonami** [Automattic/mongoose#10065]
**Do you want to request a *feature* or report a *bug*?**
Bug/missing feature
**What is the current behavior?**
typings - missing 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Hi, 

Thanks for adding Typings to the project! I was working with the aggregates and noticed that the `project` pipeline stage is missing from the typings. I checked for open issues related but didn't see any, hopefully this isn't a duplicate.

Cheers.

**Comment by schmidhannes** [comment]
I think this duplicates [#10043](https://github.com/Automattic/mongoose/issues/10043), which is already resolved.

**Comment by devonami** [comment]
It does, thank you!
