### ISSUE TITLE
Saving multiple documents per seconds on MongoDB returns timeout.

### ISSUE THREAD

**Issue by Zonalds** [Automattic/mongoose#10060]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Request failed:  Error: Timeout of 60000ms exceeded
    at RequestBase._timeoutError .../node_modules/superagent/lib/request-base.js:722:13

(node:13061) UnhandledPromiseRejectionWarning: MongoNetworkTimeoutError: connection timed out

**If the current behavior is a bug, please provide the steps to reproduce.**

  
I am trying to map through an array [of nearly 1200 objects] with the Javascript's .map() method to individually save each object to a Mongodb database (enriched with extra data). The first 270 or so would get saved without problems to Mongodb. But subsequent attempts to save would return timeout error:

**What is the expected behavior?**

Successfully save the entire objects as it maps through them.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node v12.19.1
- Mongoose: "^5.12.2",
- Database: MongoDB Cloud (free tier)

**Comment by IslandRhythms** [comment]
```
'use strict';
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();
const array = [];
  const boardSchema = new Schema({
    name: { type: String, required: true }
  });
  const Board = mongoose.model("Board", boardSchema);
 for (let i = 0; i < 1201; i++) {
    let test = {name: 'Daniel'+i}
    array.push(test);
 }
 console.log('array length', array.length);


 const map = await Promise.all(array.map(async (index) => await Board.create(index)));
 console.log('Done');
};
```

Can't do more without a script
