### ISSUE TITLE
Typescript: $pull doesn't accept strings, only known properties

### ISSUE THREAD

**Issue by ViaxCo** [Automattic/mongoose#10075]
My models: 
```js
import { Document, Schema, model, models, Model } from "mongoose";

// Item interface
export interface ItemDoc extends Document {
  task: string;
  completed: boolean;
}
// List interface
export interface ListDoc extends Document {
  name: string;
  items: ItemDoc[];
}
// User interface
export interface UserDoc extends Document {
  lists: ListDoc[];
}
// Item schema
const itemSchema = new Schema({
  task: String,
  completed: Boolean,
});
// List schema
const listSchema = new Schema({
  name: String,
  items: [itemSchema],
});
// User schema
const userSchema = new Schema({
  lists: [listSchema],
});

export const Item: Model<ItemDoc, {}> = models.Item || model("Item", itemSchema);
export const List: Model<ListDoc, {}> = models.List || model("List", listSchema);
export const User: Model<UserDoc, {}> = models.User || model("User", userSchema);
```
Usage:
```js
await User.findOneAndUpdate(
  { _id: someId, "lists.name": someListName },
  { $pull: { "lists.$.items": { _id: id } } }
);
```
This query works but Typescript is not happy:
```
(property) "lists.$.items": {
    _id: string | string[];
}
Type '{ "lists.$.items": { _id: string | string[]; }; }' is not assignable to type 'PullOperator<_AllowStringsForIds<LeanDocument<UserDoc>>>'.
  Object literal may only specify known properties, and '"lists.$.items"' does not exist in type 'PullOperator<_AllowStringsForIds<LeanDocument<UserDoc>>>'.ts(2322)
```

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noUnusedLocals": true,
  },
  "include": ["**/*.ts"],
  "exclude": ["node_modules"]
}

```

I did something similar (using strings) for `$push`and `$set` and those were fine. Just this one complains.

Node.js - v15.10.0
Mongoose - v5.12.2
Typescript - v4.2.3

**Comment by rubek-joshi** [comment]
Is there any workaround for now or are we supposed to just ignore it?

**Comment by vkarpov15** [comment]
Fix will be in v5.12.4. We'll just allow `any` for `$pull`, because there doesn't seem to really be a good way to do a deep keyof in TypeScript: https://stackoverflow.com/questions/58434389/typescript-deep-keyof-of-a-nested-object

**Comment by andreialecu** [comment]
@vkarpov15 regarding:
> because there doesn't seem to really be a good way to do a deep keyof in TypeScript

I'm not sure if I understood the request right, but this may be relevant:
https://github.com/millsp/ts-toolbelt/issues/154#issuecomment-771850996
https://millsp.github.io/ts-toolbelt/modules/function_autopath.html

Might be possible to create a type using template strings and properly type this.

**Comment by vkarpov15** [comment]
@andreialecu that looks helpful, will look into this more. Not sure whether we can use this because it requires TypeScript 4.1, but we also don't currently have a policy on what TypeScript versions we support, so worth looking into more.
