### ISSUE TITLE
How to reanme the fields of aggregate result?

### ISSUE THREAD

**Issue by keepsilentw** [Automattic/mongoose#10070]
mongoose version:
`"mongoose": "^5.9.16",`

controller code:
```ts
await AuditModel.aggregate([
  {
    $lookup: {
      from: 'puzzle_hook_answer',
      localField: 'search_id',
      foreignField: 'search_id',
      as: 'hooks'
    }
  }
])
````

model code:
```ts
const mongoose = require('mongoose')
const Schema = mongoose.Schema
const AuditSchema = new Schema({
  id: {
    type: Number,
    unique: true,
    required: true
  },
  search_id: String,
  oss_url: String
})
const AuditModel = mongoose.model('Audit', AuditSchema)
module.exports = AuditModel
```

I want to rename the fields of aggregate result, eg 'search_id' to 'searchId', how can I do?

**Comment by Duchynko** [comment]
I think this is rather a MongoDB-related question. You can use `$project` in your aggregation pipeline to change the name of a field.

```typescript
await AuditModel.aggregate([
    { $lookup: { from: 'puzzle_hook_answer', localField: 'search_id', foreignField: 'search_id', as: 'hooks' } },
    { $project: { 
        'searchId': '$search_id', // you're setting the value of search_id to a field named searchId
        'id': '$id', // and include all other fields that you want to return, otherwise, they will be omitted in the response
        'oss_url': '$oss_url',
        'hooks': '$hooks'
    }}
])
```

See the link https://stackoverflow.com/questions/35620274/mongo-aggregate-rename-field-with-project

**Comment by keepsilentw** [comment]
> I think this is rather a MongoDB-related question. You can use `$project` in your aggregation pipeline to change the name of a field.
> 
> ```ts
> await AuditModel.aggregate([
>     { $lookup: { from: 'puzzle_hook_answer', localField: 'search_id', foreignField: 'search_id', as: 'hooks' } },
>     { $project: { 
>         'searchId': '$search_id', // you're setting the value of search_id to a field named searchId
>         'id': '$id', // and include all other fields that you want to return, otherwise, they will be omitted in the response
>         'oss_url': '$oss_url',
>         'hooks': '$hooks'
>     }}
> ])
> ```
> 
> See the link https://stackoverflow.com/questions/35620274/mongo-aggregate-rename-field-with-project

Thanks for replying. I've found this solution, while... I met another problem:
I want to rename the fields of the foreign collection in the lookup result. eg... some fields of the foreign collection: 
```ts
{
  subject_id: 123456,
  subject_type: 'math'
}
```
I want to rename them in camelcase, eg...
```ts
{
  subjectId: 123456,
  subjectType: 'math'
}
```
well, how can I do?

**Comment by Duchynko** [comment]
Also with the `$project. This should work

```typescript
{ $project: {
    searchId: '$search_id',
    hooks: {
        subjectId: '$hooks.subject_id',
        subjectType: '$hooks.subject_type'
    }
}}
```

**Comment by keepsilentw** [comment]
> Also with the `$project`. This should work
> 
> ```ts
> { $project: {
>     searchId: '$search_id',
>     hooks: {
>         subjectId: '$hooks.subject_id',
>         subjectType: '$hooks.subject_type'
>     }
> }}
> ```

Yeah, I used the `$project`, and it worked. then I got a list like this:
```ts
[{
  searchId: '',
  hooks: [{
    subjectId: [123456, 12345],
    subjectType: ['math', 'math']
  }]
}]
```
well, it's not what I want. My expection is below:
```ts
[{
  searchId: '',
  hooks: [{
    subjectId: 123456,
    subjectType: 'math'
  }, {
    subjectId: 12345,
    subjectType: 'math'
  }]
}]
```
so, I think the `$project` syntax may only worked on major collection. but I'm not sure.

**Comment by Duchynko** [comment]
Try `$unwind` and then `$group`. This should do the trick

```javascript
db.collection.aggregate([
  {
    "$unwind": "$hooks"
  },
  {
    $project: {
      searchId: "$search_id",
      hooks: {
        subjectId: "$hooks.subject_id",
        subjectType: "$hooks.subject_type"
      }
    }
  },
  {
    "$group": {
      "_id": "$_id",
      "hooks": {
        "$push": "$hooks"
      }
    }
  }
])
```

**Comment by keepsilentw** [comment]
> Try `$unwind` and then `$group`. This should do the trick
> 
> ```js
> db.collection.aggregate([
>   {
>     "$unwind": "$hooks"
>   },
>   {
>     $project: {
>       searchId: "$search_id",
>       hooks: {
>         subjectId: "$hooks.subject_id",
>         subjectType: "$hooks.subject_type"
>       }
>     }
>   },
>   {
>     "$group": {
>       "_id": "$_id",
>       "hooks": {
>         "$push": "$hooks"
>       }
>     }
>   }
> ])
> ```

unfortunately, `$unwind` and `$group` won't help.

**Comment by vkarpov15** [comment]
@keepsilentw why won't `$unwind` + `$group` help? That's the recommended way to transform arrays with aggregations.
