### ISSUE TITLE
LeanDocument<T> doesn't clear out all props of mongoose.Types.Subdocument

### ISSUE THREAD

**Issue by oopyrj** [Automattic/mongoose#10071]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
"ownerDocument, parent" props are present on type after LeanDocument<T>, **keyof Subdocument** is missing from Exclude  LeanDocument<T>

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
```
  export type LeanDocument<T> = Omit<_LeanDocument<T>, Exclude<keyof Document | keyof Subdocument, '_id' | 'id' | '__v'> | '$isSingleNested'>;
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.12.2

**Comment by vkarpov15** [comment]
I don't think we can support this, because this would prevent subdocuments with a property named `parent` from working correctly with [`lean()`](https://mongoosejs.com/docs/tutorials/lean.html). For example, the below is perfectly valid.

```typescript
class Subdoc extends Document {
  name: string;
  parent: string;
}

interface ITestBase {
  subdoc: Subdoc;
  _id?: number;
  id?: string;
}

interface ITest extends ITestBase, Document<number> {
  subdoc?: Subdoc;
  id?: string;
}
```
