### ISSUE TITLE
Save only when document has changed?

### ISSUE THREAD

**Issue by Arcanorum** [Automattic/mongoose#10076]
**Do you want to request a *feature* or report a *bug*?**
Bug(?)

**What is the current behavior?**
Calling .save on a loaded document without changing anything on the document seems to still cause a DB update.

*"Why are you calling .save without updating anything first?"*
I have an online game with player data being updated in the Mongoose document on player state change and saved on an interval using `.save`. Some of these states change frequently (ammo, exp, etc.) so I didn't want to do a save for every change, but just update the document and save once every so often to commit their progress during that time.

Debug log of this save interval:
> ```
> ...
> Mongoose: accounts.findOne({ _id: ObjectId("6015f830f81adc1f898455a2") }, { session: undefined, projection: { _id: 1 } })
> Mongoose: accounts.findOne({ _id: ObjectId("6015f830f81adc1f898455a2") }, { session: undefined, projection: { _id: 1 } })
> Mongoose: accounts.findOne({ _id: ObjectId("6015f830f81adc1f898455a2") }, { session: undefined, projection: { _id: 1 } })
> ...
> ```

**What is the expected behavior?**
I figured that when Mongoose runs a diff on the document to find what has changed to create an update for, that if nothing has changed then it would skip sending the update to the DB.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 12.19
Mongoose 5.12.2
MongoDB 4.4.4

**Comment by IslandRhythms** [comment]
Why couldn't you just trigger a save when a value like ammo or xp changes?

**Comment by vkarpov15** [comment]
Mongoose doesn't send an update to MongoDB, it sends a `findOne()`.

You can use the [`getChanges()` function](https://mongoosejs.com/docs/api/document.html#document_Document-getChanges) to check if the document changed before calling `save()` to avoid the `findOne()`.
