### ISSUE TITLE
Invalid schema configuration: `True` is not a valid type at path `timestamp.immutable`.

### ISSUE THREAD

**Issue by OverHash** [Automattic/mongoose#10073]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Mongoose gives a run-time error when I am using my schema to define `immutable: true`. Here is a snippet of my schema:
```ts
const crossServerTradesAvailableSchema = new Schema<CrossServerTradesAvailableBaseDocument>(
{
	timestamp: {
		type: Schema.Types.Date,
		default: Date.now,
		immutable: true,
		required: true,
	}
});
```

But when I use this, I get the runtime error:
TypeError: Invalid schema configuration: `True` is not a valid type at path `timestamp.immutable`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.

**What is the expected behavior?**
I would expect mongoose to not have a runtime error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose@5.12.2

**Comment by OverHash** [comment]
This was caused by `type` actually being `types`..

**Comment by vtrphan** [comment]
what do you mean type being types ?

**Comment by OverHash** [comment]
> what do you mean type being types ? i'm having this error too

I typo-ed the `type` field of my schema as `types`.

**Comment by anilraj5** [comment]
also not work in my case
