### ISSUE TITLE
Popular consultation in pre-hooks

### ISSUE THREAD

**Issue by gabriel-peruchi** [Automattic/mongoose#10088]
In the pre-hook, how to check if the consultation is a popular consultation or a normal consultation?

I need to skip a check on the pre-hook if the query is a popular query.

getPopulatedPaths returns the paths to be filled in the current query (normal), but I need to identify the queries that are triggered by the populate, as I need to skip the checks in the same queries.

**Comment by vkarpov15** [comment]
@gabriel-peruchi please provide code samples, this question isn't very actionable.
