### ISSUE TITLE
How to use MongoDB Updates with aggregation pipelines

### ISSUE THREAD

**Issue by awesomelike** [Automattic/mongoose#10095]
MongoDB supports updates with aggregation pipelines (https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/). Here is sample query (https://mongoplayground.net/p/i7A4YoIhyS5). The update function takes an array (the pipeline) as the second argument.

In Mongoose however, it turns out you can pass only an object (by the docs https://mongoosejs.com/docs/api.html#model_Model.updateMany, also I have tried myself and array is not supported). 
Are there any ways to use Updates with aggregation pipelines in Mongoose?

**Comment by vkarpov15** [comment]
We need to update our docs. You can pass an array instead of an object and it will work as expected.
