### ISSUE TITLE
Query's Typescript definition misses an asyncIterator

### ISSUE THREAD

**Issue by borfig** [Automattic/mongoose#10093]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
In Typescript, it is not possible to use a Query instance in a `for await` loop

**If the current behavior is a bug, please provide the steps to reproduce.**
According to [documentation](https://mongoosejs.com/docs/queries.html#streaming), I should be able to do the following:
```
for await (const doc of Person.find()) {
  console.log(doc); // Prints documents one at a time
}
```

My `tsconfig.json`
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2019",
    "lib": [],
    "esModuleInterop": true,
    "strict": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
  },
  "include": [
    "src/**/*.ts*",
  ]
}
```

**What is the expected behavior?**
The code above should compile

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.21.0
Typescript: v4.2.3
Mongoose: v5.12.3
MongoDB: v3.6.5 (DT: 3.6.11)

**Workaround**
Explicitly create a QueryCursor:
```
for await (const doc of Person.find().cursor()) {
  console.log(doc); // Prints documents one at a time
}
```

**Comment by joebowbeer** [comment]
@vkarpov15 Model.aggregate is also in need of this?

https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-Symbol.asyncIterator
