### ISSUE TITLE
URL parsing deprecated, therefore hostname does not have property 'split' 

### ISSUE THREAD

**Issue by tobiO0310** [Automattic/mongoose#10102]
More specific:
Error:
![image](https://user-images.githubusercontent.com/59401633/113471992-62c85700-9460-11eb-8d04-0536f3055cf5.png)

This makes connecting impossible for me.

I am running mongoose version 5.12.3 and mongodb version 3.6.5

**Comment by vkarpov15** [comment]
@tobiO0310 what does your connection string look like? Mongoose doesn't call `parseSrvConnectionString()` directly, so I don't see where this stack trace could be coming from.

**Comment by tobiO0310** [comment]
@vkarpov15, it looks like this:
"mongodb+srv://<username>:<password>@maindatabase.u4ahm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

**Comment by vkarpov15** [comment]
@tobiO0310 you would likely need to remove the empty username and password, just do "mongodb+srv://maindatabase.u4ahm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

**Comment by vkarpov15** [comment]
Also, more recent versions of Mongoose report a more correct error:

```
MongoParseError: Invalid empty username provided
    at parseConnectionString (/mongoose/node_modules/mongodb/lib/core/uri_parser.js:630:23)

```

**Comment by tobiO0310** [comment]
@vkarpov15, actually I just left those out, since I didn’t want to send them-
And I’ve moved from atlas to a privately hosted one, which works better
