### ISSUE TITLE
Mongoose caching

### ISSUE THREAD

**Issue by Uthsho** [Automattic/mongoose#10108]
**Do you want to request a *feature* or report a *bug*?**
Well I need help and not really report a bug

**What is the current behavior?**
When i take data from memory and use new <Model>(cached). It thinks I make it a new document with the same unique id.
I want to just convert it to Document class so I can use the save method to save the document that is on the database and not create a new document.

**What is the expected behavior?**
To convert the cache data to a document using new <Model>(cached) where cached is the plain object I saved into memory.

Nodejs: v14
MongoDB: 4.4.4

Mongoose Version - 5.12.0

**Comment by IslandRhythms** [comment]
Why can't you let it create a new document? the id isn't changing apparently so referencing the document should not have an issue.

**Comment by Kamikadze4GAME** [comment]
@Uthsho try to use `Model.hydrate()` (see [docs](https://mongoosejs.com/docs/api/model.html#model_Model.hydrate))
