### ISSUE TITLE
createCollection method stuck in promise

### ISSUE THREAD

**Issue by arezaie14** [Automattic/mongoose#10104]
There is a problem in Model.createCollection() in version 5.12.3. when trying to use that method it stuck in promise. I checked some hour on this isue, and I found it was working on version 5.11.9 

for example the code blow was working on 5.12.2 but not in 5.12.3:

        const User = mongoose.model('User', userSchema);

        User .createCollection().then((data) => {

            console.log("Collection:  was created.")

        }).catch(err => {

            console.log("Error: " + err + " happend while creating collection")

        });

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');

const run = async () => {
    await mongoose.connect('mongodb://localhost:27017/test', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    await mongoose.connection.dropDatabase();
    const testSchema = new mongoose.Schema({name: String});
    const Test = mongoose.model('Test', testSchema);
    Test.createCollection().then((data) => {
        console.log('Collection: was created');
    }).catch(err => {
        console.log("error: "+err);
    });

}
run().catch(err => console.log(err));
```

**Comment by vkarpov15** [comment]
@arezaie14 please try upgrading to Mongoose 5.12.4. I believe this was fixed in https://github.com/Automattic/mongoose/commit/56bc6a4368cb0b5eb917cda27936d3e79237a673
