### ISSUE TITLE
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by mlamota2020** [Automattic/mongoose#10103]
In creating a login/register system. When I login or I register a new account I use a `findOne()` to search in the db the user. If it doesn't exist, that will create a new user. Currently I have some problems with mongoose. It says: `MongooseError: Operation users.findOne() buffering timed out after 10000ms`. Here is my code:

    const express = require('express');const app = express();

    const path = require('path');
    const mongoose = require('mongoose');
    const passport = require('passport');
    const flash = require('connect-flash');
    const morgan = require('morgan');
    const cookieParser = require('cookie-parser');
    const bodyParser = require('body-parser');
    const session = require('express-session');

    const { url } = require('./config/database.js');

    mongoose.connect(url, {
	    useNewUrlParser: true,
	    useUnifiedTopology: true
    });

    require('./config/passport')(passport);

    // settings
    app.set('port', process.env.PORT || 3000);
    app.set('views', path.join(__dirname, 'views'));
    app.set('view engine', 'ejs');
    
    // middleware
    app.use(morgan('dev'));
    app.use(cookieParser());
    app.use(bodyParser.urlencoded({extended: false}));
    // required for passport
    app.use(session({
	    secret: 'faztwebtutorialexample',
    	    resave: false,
	    saveUninitialized: false
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(flash());
    
    // routes
    require('./app/routes.js')(app, passport);
    
    // static files
    app.use(express.static(path.join(__dirname, 'public')));

    // start the server
    app.listen(app.get('port'), () => {
	    console.log('server on port ', app.get('port'));
    });

    const LocalStrategy = require('passport-local').Strategy;
    const mongo = require("mongodb");
    const User = require('../app/models/user');

    module.exports = function (passport) {
      // required for persistent login sessions
      // passport needs ability to serialize and unserialize users out of session
      passport.serializeUser(function (user, done) {
        done(null, user.id);
      });

      // used to deserialize user
      passport.deserializeUser(function (id, done) {
        User.findById(id, function (err, user) {
          done(err, user);
        });
      });

      // Signup
      passport.use('local-signup', new LocalStrategy({
        // by default, local strategy uses username and password, we will override with email
        usernameField: 'email',
        passwordField: 'password',
        passReqToCallback : true // allows us to pass back the entire request to the callback
      },
      function (req, email, password, done) {
        User.findOne({'local.email': email}, function (err, user) {
          if (err) {
            return done(err);
          }
          if (user) {
            return done(null, false, req.flash('signupMessage', 'the email is already taken'));
          } else {
            var newUser = new User();
            newUser.local.email = email;
            newUser.local.password = newUser.generateHash(password);
            newUser.save(function (err) {
              If (err) { throw err; }
              return done(null, newUser);
            });
          }
        });
      }));

      // login
      // we are using named strategies since we have one for login and one for signup
      // by default, if there was no name, it would just be called 'local
      passport.use('local-login', new LocalStrategy({
        usernameField: 'email',
       passwordField: 'password',
        passReqToCallback: true
      },
      function (req, email, password, done) {
        User.findOne({'local.email': email}, function (err, user) {
          if (err) { return done(err); }
          if (!user) {
            return done(null, false, req.flash('loginMessage', 'No User found'))
          }
          if (!user.validPassword(password)) {
            return done(null, false, req.flash('loginMessage', 'Wrong. password'));
          }
          return done(null, user);
        });
      }));
    }

**Comment by IslandRhythms** [comment]
I usually only see that error when either you need to use async/await for some functions or you don't have a mongodb instance open.

**Comment by vkarpov15** [comment]
How are you defining your `User` model? This error is typically indicative of adding a model to a connection that doesn't connect to MongoDB.

**Comment by teezyfortune** [comment]
I have this same issue when I want to log in, How can I fix this?

**Comment by vkarpov15** [comment]
@teezyfortune please open a new issue and follow the issue template.
