### ISSUE TITLE
not making any error when can't connect to db

### ISSUE THREAD

**Issue by arezaie14** [Automattic/mongoose#10105]
I checked more and more times to connect db with connection string that was false and in version 5.12.3 there was not any error happened, but i checked with version 5.12.2 and it was ok, for example the code below is not work well in new version:

`        mongoose.connect(ars.config.db_connection_string);

        var db = mongoose.connection;

        db.on('error', function () {

            ars.db_manager.connected = false;

            console.error.bind(console, 'connection error:')

        });
        db.once('open', function () {

            ars.db_manager.connected = true;

        });`

**Comment by IslandRhythms** [comment]
```
'use strict';
const { connect } = require('mongodb');
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  mongoose.connection.on('connected', () => {
    console.log(mongoose.connection.readyState);
  });
  mongoose.connection.on('error', () => {
    console.log('error')
  });
  await mongoose.connect('mongodb', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

};
```

**Comment by vkarpov15** [comment]
In more recent versions, the MongoDB Node driver waits for `serverSelectionTimeoutMS` milliseconds before reporting certain types of initial connection errors. That timeout is 30 seconds by default, which often makes it seem like there isn't any error.

For faster feedback, you can reduce `serverSelectionTimeoutMS` as follows:

```javascript
  await mongoose.connect('mongodb', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    serverSelectionTimeoutMS: 5000 // 5 seconds
  });
```
