### ISSUE TITLE
bug in mongodb 3.6.4, 3.6.5

### ISSUE THREAD

**Issue by rlidwka** [Automattic/mongoose#10107]
Mongodb driver recently had a bug I've stumbled upon: https://jira.mongodb.org/browse/NODE-2355

Short description: stream.pipeline in node 14 never finishes when used with GridFS streams.

Introduced in:
https://github.com/mongodb/node-mongodb-native/commit/b5e9d67d5cd9b1912a349789cf2a122e00a46d1b

Fixed in:
https://github.com/mongodb/node-mongodb-native/commit/c976a01bf385941bee07fa7f021adf1d425109a8

Affected versions: 3.6.4 and 3.6.5. 3.6.3 works fine, 3.6.6 not released yet.

Please check if it's worth reverting to mongodb@3.6.3 over this one.

**Comment by vkarpov15** [comment]
Mongoose 5.12.4 uses mongodb@3.6.6, upgrading should fix this issue :+1:
