### ISSUE TITLE
Need an ability to filter nested array when doing find / findById

### ISSUE THREAD

**Issue by tar-aldev** [Automattic/mongoose#10114]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Imagine I have a user model, and user may have multiple addresses.
Something like
```
const userSchema = new Schema({
    firstName: String,
    date: { type: Date, default: Date.now },
    hidden: Boolean,
    addresses: [{
        line1: String,
        ...,
        deletedAt: Date
    }]
  });
const User = mongoose.model('User', userSchema);
```
Then I want to use a soft delete, i.e. addresses array would look like:
```
addresses: [{
        // not deleted, therefore no deletedAt field
        line1: 'Some address 1',
    },
    {
        // soft deleted
        line1: 'Some address 1',
        deletedAt: 2019-09-01T20:59:59.000+00:00
    }
]
```
Then I want to get a user WITHOUT deleted addresses. 
The only way I see now, it do `findOne / findById` and then manually filter addresses field which looks like a pain to do every time.
And things become much worse if I want to just do `find` (not a single user, because I need to map over all found users and filter addresses manually.
I know that I can use aggregation, but I guess mongoose's goal is to make lives easier without need to use aggregations for such simple cases.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Would be really nice to have an ability to filter embedded documents / objects. 
Like
```
// Just a pseudo code, but I hop the idea is clear
User.findfindOne({_id: '606d87095620b37dd5e4f973', $filter: {'addresses': {$exists: {"deletedAt": false } } } } })
```
Or
```
User.findfindOne({_id: '606d87095620b37dd5e4f973'}).select({
  addresses: // way to filter addresses
})
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Unfortunately that isn't something MongoDB can do currently without aggregation framework. There's the [positional operator](https://docs.mongodb.com/manual/reference/operator/projection/positional/) for projections, but that would only return the first non-deleted address.

You can always write a [mongoose getter](https://mongoosejs.com/docs/tutorials/getters-setters.html) for your array that filters out soft-deleted values.
