### ISSUE TITLE
Mongoose doesn't create index on mongo atlas

### ISSUE THREAD

**Issue by DoneDeal0** [Automattic/mongoose#10129]
**bug**

**What is the current behavior?**
When inserting a document, the index specified on the schema is never created in Mongo Atlas. Therefore, geospatial queries are not supported.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
import mongoose from "mongoose";
import { User } from "../../models/User";

const Schema = mongoose.Schema;
const userSchema = new Schema<User>(
  {
    email: { type: String, required: true, unique: true },
    geolocation: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: { type: [Number], default: [0, 0] },
    },
    password: { type: String, required: true },,
    username: { type: String, required: true, unique: true },
  },
  { timestamps: true }
);

userSchema.index({ geolocation: "2dsphere" });

export default mongoose.model<User>("UserDB", userSchema);

```
Indexes on other schema are created with he syntax
```js
conversationSchema.index({ name: 1 });
```

**What is the expected behavior?**
It should create an index when inserting a new document (or documents when bulk-writing seeds).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v15.11.0
mongoose: ^5.12.3,

**Comment by jarretmoses** [comment]
I started noticing this too. I believe it is related to https://github.com/Automattic/mongoose/commit/6c78829689f8addc26ef0b2ba8fb321e5d86733d#commitcomment-48220571. I tried the suggestion of setting `{collation: {locale: "simple"} }` but this didn't seem to work either

**Comment by DoneDeal0** [comment]
So've found a dirty hack: when connecting to your db, write:

```js
UserDB.ensureIndexes();
```
if you add `index: true` or `index: "2dsphere"` this will work. But I'm not sure it's fine to do this in production... I'd like to make sure every new user will be correctly indexed when inserted, without having to run this function. 

@mongoose team, can you confirm this is a valid solution in a production environment? When will a fix be provided? 

@IslandRhythms , this is not a typescript issue, but a bug.

**Comment by IslandRhythms** [comment]
Could you please run this for me and see if it reproduces your issue.
```
import {connect, connection, Schema} from 'mongoose';
import {model} from 'mongoose';
import {Document} from 'mongoose';
import {Model} from 'mongoose';

interface User extends Document {
    email?: String,
    geolocation?: {
        type?: String,
        coordinates?: [Number]
    },
    password?: String,
    username?: String,
}

const userSchema:Schema = new Schema<User>(
  {
    email: { type: String, required: true, unique: true },
    geolocation: {
      type: { type: String, enum: ["Point"], default: "Point" },
      coordinates: { type: [Number], default: [0, 0] },
    },
    password: { type: String, required: true },
    username: { type: String, required: true, unique: true },
  },
  { timestamps: true }
);

userSchema.index({ geolocation: "2dsphere" });

const testmodel:Model<User> = model("UserDB", userSchema);

(async function() {
    await connect('mongodb://localhost:27017/test', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useFindAndModify: false
    });
  await connection.dropDatabase();
  const test: User = new testmodel({
    email:'test@test.com',
    geolocation: {
        type: 'Point',
        coordinates: [0,0]
    },
    password: 'abcde',
    username: 'edfedf'
});
await test.save();
let entry = await testmodel.find();
console.log(entry);

  
  })();
```

**Comment by stylegan61** [comment]
> So've found a dirty hack: when connecting to your db, write:
> 
> // UserDB is of course the name I gave to my schema, put yours
> UserDB.ensureIndexes();
> if you add `index: true` or `index: "2dsphere"` this will work. But I'm not sure it's fine to do this in production... I'd like to make sure every new user will be correctly indexed when inserted, without having to run this function.
> 
> mongoose team, can you confirm this is a valid solution in a production environment? When will a fix be provided?
> 
> [@IslandRhythms](https://github.com/IslandRhythms) , this is not a typescript issue, but a bug.





https://lnkr.fun/19de8b2
