### ISSUE TITLE
Make `createdAt` timestamp immutable by default

### ISSUE THREAD

**Issue by thiagokisaki** [Automattic/mongoose#10139]
Currently, setting timestamps to true in schema options does not ensure that `createdAt` is immutable.
```javascript
const { model, Schema } = require('mongoose');

(async () => {
  const schema = new Schema({ name: String }, { timestamps: true });

  const Model = model('Test', schema);

  const doc = await Model.create({ name: 'test' });
  console.log(doc.createdAt);

  // Changing `createdAt`
  doc.createdAt = new Date('2002-08-01');

  // Mongoose did not prevent `createdAt` from being changed
  console.log(doc.createdAt);
})();
```
So I have to explicitly insert `createdAt: { type: Date, immutable: true }` in the schema definition. I believe that an immutable `createdAt` is the expected behavior and it would be nice if mongoose already set that for us.

**Comment by thiagokisaki** [comment]
```javascript
const { model, Schema } = require('mongoose');

(async () => {
  const schema = new Schema({ name: String }, { timestamps: true });

  const Model = model('Test', schema);

  const doc = await Model.create({ name: 'test' });
  console.log(doc.createdAt);

  // Changing 'createdAt'
  doc.createdAt = new Date('2002-08-01');

  // Mongoose did not prevent 'createdAt' from being changed
  console.log(doc.createdAt);
})();

```
To make 'createdAt' immutable, I must define `createdAt: { type: Date, immutable: true }` explicitly in schema definition.

**Comment by IslandRhythms** [comment]
I'm assuming that in your project you need to change the createdAt timestamp for some entries and not others?

**Comment by IslandRhythms** [comment]
I'll label this as a feature request since that seems to be the case here.

**Comment by thiagokisaki** [comment]
> I'm assuming that in your project you need to change the createdAt timestamp for some entries and not others?

No, I don't. In fact, I can't image a situation in which you would like to change 'createdAt' after the document creation. You shouldn't be able to do that. IMO `immutable: true` should be the default.

**Comment by vtrphan** [comment]
i'm currently getting this Error:
`TypeError: Invalid schema configuration: `True` is not a valid type at path `createdAt.immutable`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.`
after updating to mongoose 6. Please advise

**Comment by vkarpov15** [comment]
@vtrphan please open a new issue and follow the issue template.
