### ISSUE TITLE
empty results when trying to read from secondaty

### ISSUE THREAD

**Issue by aryaKetan** [Automattic/mongoose#10134]
Mongoose version: 5.11.15. 
Mongo server version: 4.4

when trying to read from secondary empty results come. From primary result comes properly.

**Comment by aryaKetan** [comment]
const mongoose = require('mongoose')
 const conn = mongoose.createConnection(connObj.url, connObj.options) //  passing as connection URL:  mongodb+srv://{awskey:secret}/$host/$database?retryWrites=true&w=majority&readPreference=secondaryPreferred&authSource=$external&authMechanism=MONGODB-AWS
 const schema = new logDBConnection.base.Schema({ /// schema object})

const schemaObject = conn.model(mongoTableName, schema) // 

 const results = await schemaObject.find(queryPararms).lean().read('primary') // if we pass .read("primary") results are coming. else empty results come.

Let me know if u need anything else.

**Comment by vkarpov15** [comment]
Not much we can do to debug this without more information. Try `.read('secondaryPreferred')`, if that works then this may be a Mongoose issue. If not, it's an issue with your Atlas setup.
