### ISSUE TITLE
Property casting and validation improvements

### ISSUE THREAD

**Issue by tleach** [Automattic/mongoose#1013]
In my mind the way in which Mongoose handles model property casting is broken. 

As an example, let's say we define a model with this schema:

``` javascript
var Item = new Schema({
  name   : {type : String, required : true},
  price  : {type : Number, required : true},
  description : {type: String, required: true}
});
```

... and we create a new instance, but provide a value for price using the wrong type:

``` javascript
var item = new Item({name:"Blender", description:"Makes frozen daquiris", price:"five hundred dollars");
```

Mongoose will simply silently ignore the incorrectly typed variable and my object will just look like:

``` javascript
{ _id: 50056c29527d176a1d000001, name:"Blender", description:"Makes frozen daquiris"}
```

If we attempt to `create()` a new model directly with these property values a CastError is thrown.

In both cases, I would argue this is the wrong behaviour. 

Assignment of an incorrectly typed value is a mistake which should be caught using _validation_, just like absence of required values, values which are not in the required range, etc. We should be able to assign whatever values we want to the model (correct type or otherwise) and then be prevented from saving them to the DB by validation checks. 

A lot of the time the data that is used to populate models comes from a web form, where the user can enter anything, so if we're using Mongoose validation to validate this data prior to saving it, we need to be able to validate type in a consistent manner to everything else. 

Throwing an out-of-band CastError or ignoring the assignment entirely mean you need to write a bunch of code to detect and handle these special type-cast errors outside of your validation logic. At the very least, if we assign a value to a property, that assignment should not silently fail. 

To draw a parallel with Rails, if I want to validate the numericality of a property on my model I simple declare `validate :price, :numericality => true` in my model and any such failures get bundled into my model's `errors` collection with all other validation failures. 

Is this not more correct? Is there a plan to move in this direction?

Thanks to all of you LearnBoost guys for all you hard work - much appreciated.

**Comment by rafaelcardoso** [comment]
oops, my bad. Thank you @vkarpov15

**Comment by alexkavon** [comment]
@vkarpov15 Are these improvements in any of the 3.8 releases?

**Comment by vkarpov15** [comment]
No, and won't be. 3.8.x releases include only bug fixes and aim to be 100% backwards compatible.
