### ISSUE TITLE
Validations - Can't use model.validate when using internal validators

### ISSUE THREAD

**Issue by tomgrossman** [Automattic/mongoose#10132]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using the `model.validate` function, without casting the doc to a model first, the `this` reference in a shared validations functions, is referring to the function and not to the model.
This can cause issues when trying to validate pure mongo docs, too see if they pass the schema validations, without casting them first.
Script example of the difference between casting to a model first and validating against just validating:

```javascript
const mongoose = require('mongoose');

function isNameRequired() {
    console.log(`requirments: ${this.requirements?.needName}`);

    return true === this.requirements.needName;
}

const TestSchema = new mongoose.Schema({
    requirements: {
        needName: {
            type: Boolean,
            required: true,
        },
    },
    name: {
        type: String,
        required: isNameRequired,
    },
});

const TestModel = new mongoose.model('TestModel', TestSchema);

const testDoc = {
    requirements: {
        needName: true,
    },
    name: 'Tom',
};

async function runTests() {
    // Initializing to a model and validating
    try {
        const testDocModel = new TestModel(testDoc);
        await testDocModel.validate();
        console.log('testDocModel.validate passed');
    } catch (error) {
        console.error(error);
    }

    console.log('///////////');

    // Validating the doc using the model
    try {
        await TestModel.validate(testDoc);
        console.log('TestModel.validate passed');
    } catch (error) {
        console.error(error.errors.name.message);
    }
}

runTests();

```

Output:

> requirments: true
testDocModel.validate passed
requirments: undefined
Cannot read property 'needName' of undefined

**What is the expected behavior?**
It should be possible to validate pure MongoDB docs without casting them first, using the `model.validate` function.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 14
Mongoose - 5.11.18
MongoDB - 4.4, but not relevant.

**Comment by vkarpov15** [comment]
Currently this is by design: the validator context is `null` by default when using `model.validate()`. We can make it default to the doc if the first argument is a document, but you can work around this by passing the [`context` argument to `model.validate()`](https://mongoosejs.com/docs/api/model.html#model_Model.validate):

```javascript
await TestModel.validate(testDoc, null, testDoc);
```
