### ISSUE TITLE
wrongful CastError on findByIdAndRemove and findOneAndRemove using _id

### ISSUE THREAD

**Issue by Azenics** [Automattic/mongoose#10133]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

It logs an error `(node:13592) UnhandledPromiseRejectionWarning: CastError: Cast to ObjectId failed for value "true" at path "_id" for model "uudis"` when using fineByIdAndRemove or findOneAndRemove({ _id: req.params.id }). 
Document gets deleted and `mongoose.Types.ObjectId.isValid(req.params.id)` returns true.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
router.delete(`/${kat.nimi}/:id`, auth, async (req, res) => {

    if (req.user.staatus < 3) {
      return res.status(401).json({ msg: 'Kasutajal puudub volitus.' });
    }
    try {
      const artikkel = await kat.schema.findByIdAndRemove(req.params.id);
      if (!artikkel) {
        return res.status(404).json({ msg: 'Lehte ei leitud.' });
      }
      res.json({ msg: 'Leht kustutatud.' });
    } catch (err) {
      console.error(err.message);
      res.status(500).send('Server error');
    }
}); 
```

**What is the expected behavior?**
No error logged.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v14.16.0
Mongoose 5.12.3
MongoDB 4.4.4 (Atlas)

**Comment by IslandRhythms** [comment]
```
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const boardSchema = new Schema({
    name: { type: String, required: true }
  });
  const Board = mongoose.model("Board", boardSchema);
  const entry = await Board.create({name: 'Test'});
  await entry.save();
  const test = await Board.findOne();
  console.log(test._id);
  const board = await Board.findOneAndRemove({_id:test._id});
  // const board = await Board.findByIdAndRemove({_id:test._id});
};
```

**Comment by Azenics** [comment]
I can't really reproduce either in the scope of the server even - all other findOne, findOneAndUpdate etc schema functions work in the same forEach for all iterations (besides the removes which throw errors for all categories) and when I call the findOneAndRemove/findByIdAndRemove functions inside server.js for the or anywhere else for the very same category schemas - there is no error.

**Comment by Azenics** [comment]
Found out the problem on my end - I wasn't using `{lean: true}` and was getting '$init' as part of an Object.values() that was causing `true` being passed as an id to a later function.

I'm really sorry for wasting your time.

**Comment by IslandRhythms** [comment]
@Azenics no worries, glad you were able to solve your problem.
