### ISSUE TITLE
toObject: excludes virtual when it returns an empty object

### ISSUE THREAD

**Issue by fredericosilva** [Automattic/mongoose#10149]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
toObject: excludes virtual when it returns an empty object

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
'use strict';

const mongoose = require('mongoose');

const personSchema = new mongoose.Schema({
  name: {
    first: String,
    last: String
  }
});

personSchema.virtual('details').get(function() {
  return { };
});

// compile our model
const Person = mongoose.model('Person', personSchema);

// create a document
const axl = new Person({
  name: { first: 'Axl', last: 'Rose' }
});

console.log('details', axl.details);
console.log('person', axl.toObject({ virtuals: true }));
```
output
```
details {}
person {
  _id: 6079ad90c517f4363374a896,
  name: { first: 'Axl', last: 'Rose' },
  id: '6079ad90c517f4363374a896'
}
```
details is missing

**What is the expected behavior?**
Virtual should be returned

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose@5.12.4
node v15.14.0

**Comment by aedeveloper** [comment]
same issue here even with **toJSON**

**Comment by vkarpov15** [comment]
Unfortunately, this is expected behavior. [Mongoose "minimizes" documents by default](https://mongoosejs.com/docs/guide.html#minimize), which removes empty objects from the output. Set the `minimize` option to `false` to opt out.

```javascript
console.log('person', axl.toObject({ virtuals: true, minimize: false }));
```

**Comment by fredericosilva** [comment]
Thank you @vkarpov15 I was not aware of that option.
