### ISSUE TITLE
Website: Missing menu link to Transactions in Mongoose page

### ISSUE THREAD

**Issue by bichotll** [Automattic/mongoose#10143]
**Do you want to request a *feature* or report a *bug*?**

bug: missing link to Transactions in Mongoose page

**What is the current behavior?**

I was only able to find the page thru google. I was reading the docs and didn't see that section/page.

**Comment by vkarpov15** [comment]
The link is here: https://mongoosejs.com/docs/guides.html#integrations but we will add it to the navbar.
