### ISSUE TITLE
string minLength, maxLength validation for string array type

### ISSUE THREAD

**Issue by bwgjoseph** [Automattic/mongoose#10154]
Hi,

Would like to check if there is any way to validate string minLength, maxLength for string array data type?

```js
const schema = new Schema({
    _id: {
      type: String,
    },
    name: {
      // how to ensure all string within the array is conforming to minLength and maxLength check?
      type: [String],
    },
    description: {
      // can do it easily for String field
      type: String,
      minLength: 1,
      maxLength: 10,
    },
})
```

Thanks

**Comment by vkarpov15** [comment]
`name: [{ type: String, minLength: 1, maxLength: 10 }]`

**Comment by bwgjoseph** [comment]
Hey @vkarpov15, I didn't want to re-open this, or create new one but quick question to check if this is valid as well

```js
test: {
    type: [{
        type: String,
        minLength: 5,
        maxLength: 20,
    }],
    default: undefined,
},
```

This is so that I can continue to make use of other declaration like `default` in this case, and any others

**Comment by vkarpov15** [comment]
@bwgjoseph yep, that's the correct way to create a property `test` that is an array of strings of length 5-20, and defaults to `undefined`.

**Comment by bwgjoseph** [comment]
Thank you so much!
