### ISSUE TITLE
Problems mongoose node.js

### ISSUE THREAD

**Issue by JuanSSI** [Automattic/mongoose#10160]
**const mongoose = require('mongoose');

mongoose.connect("mongodb://localhost:27017/fruitsDB", { useNewUrlParser: true });

mongoose.set('useUnifiedTopology', true);**

_When I run my app.js with node I got this error: 

(node:12660) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option 
{ useUnifiedTopology: true } to the MongoClient constructor._

**Comment by theshoperr** [comment]
remove the "mongoose.set" and place the "useUnifiedTopology" inside the "{}" in the "mongoose.connect", along side the "useNewUrlParser: true".

in my code, I use it like this:

mongoose.connect(MYTOKEN, {
  useNewUrlParser: true,
  useUnifiedTopology: true
})

Hope that helped

**Comment by JuanSSI** [comment]
I tried like this, but when I run node on my app.js file nothing happens.

**Comment by JuanSSI** [comment]
Thanks!!
