### ISSUE TITLE
error name is missing

### ISSUE THREAD

**Issue by hasinoorit** [Automattic/mongoose#10166]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Error name is missing for CastError

**If the current behavior is a bug, please provide the steps to reproduce.**

**My Schema code is**
`const contentSchema = Schema({
  text: {
    type: String,
    required: [true, "Text is required"]
  },
  number: {
    type: Number,
    required: [true, "Number is required"]
  },
})
`
**My Parameters are**
`{
    "text": false,
    "number": "fsfsf"
}`

**What is the expected behavior?**
err.errors['number'].name should show 'CastError'

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

1. Node Version: 14.16.0
2. mongooser version: 5.12.4
3. mongodb version: 3.6.8

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({text: {type:String, required: [true, "Text is required"]}, number: {
    type: Number, required: [true, "Number is required"]}, });

    const Test = new mongoose.model('Test', testSchema);

    async function run() {
        await mongoose.connect('mongodb://localhost:27017/test', {
            useNewUrlParser: true,
            useUnifiedTopology: true
          });
        
        await mongoose.connection.dropDatabase();

        const entry = await Test.create({"text": false, "number": "fsfsf"});
        await entry.save();
    }
    run();
```

**Comment by IslandRhythms** [comment]
try `new mongoose.Schema` instead of `Schema`

**Comment by hasinoorit** [comment]
**Code to reproduce**
````javascript
const mongoose = require("mongoose")
const {Schema} = mongoose

const testSchema = new Schema({text: {type:String, required: [true, "Text is required"]}, number: {
  type: Number, required: [true, "Number is required"]}, })

const Test = new mongoose.model("Test", testSchema)

async function run() {
  try {
    await mongoose.connect("mongodb://localhost:27017/test", {
      useNewUrlParser: true,
      useUnifiedTopology: true
    })
        
    await mongoose.connection.dropDatabase()

    const entry = await Test.create({"text": false, "number": "fsfsf"})
    await entry.save()
  } catch (error) {
    console.log(JSON.parse(JSON.stringify(error)))
  }
}
run()

````

**Current output**

````javascript
{
  errors: {
    number: {
      stringValue: '"fsfsf"',
      kind: 'Number',
      value: 'fsfsf',
      path: 'number',
      reason: [Object]
    }
  },
  _message: 'Test validation failed',
  name: 'ValidationError',
  message: 'Test validation failed: number: Cast to Number failed for value "fsfsf" at path "number"'
}
````

**Comment by IslandRhythms** [comment]
Why are you expecting it to show a cast error vs a validation error? Number is expecting a number but you are passing a string.

**Comment by hasinoorit** [comment]
> Why are you expecting it to show a cast error vs a validation error? Number is expecting a number but you are passing a string.

According to documention https://mongoosejs.com/docs/validation.html#cast-errors 
errors['number'] should have "message" & "name" property. But these properties are missing. I need these property for developing a plugin.

**Comment by IslandRhythms** [comment]
So it's possible the documentation could be outdated, I'll need to go confirm that. However, in your output, there is a name and message property, it is just not in the exact place the documentation says so in the meantime you can use that.

**Comment by hasinoorit** [comment]
> So it's possible the documentation could be outdated, I'll need to go confirm that. However, in your output, there is a name and message property, it is just not in the exact place the documentation says so in the meantime you can use that.

That name & message property are not of field level error. Document is not outdated, indeed its updated. My old plugin is also using these property for setting custom CastError message, and unique error message. I am using my old plugin with mongoose 5.9.25. Its definitely a new bug.
