### ISSUE TITLE
Unable to access nested path schemas using Schema#path

### ISSUE THREAD

**Issue by mcat95** [Automattic/mongoose#10164]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When you try to access the properies of a schema path of a deeply nested schema, it returns undefined.

By bisecting the code between our previous good version (5.10.7) and the current one (5.12.5) we found that the bug was introduced by 037eb14f33dc0d15e9e83ea727164e8c8787b41a

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/mcat95/f6dba9774a4c8e02edf169e1f2c12149

**What is the expected behavior?**

It should return the object with the schema node descriptor:
```
SchemaBoolean {
  path: 'field3',
  ...
}
```

Instead, it's returning undefined

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Node.js**: 14.12.0
**Mongoose**: 5.12.5
**Mongodb**: Not relevant, since it's not necessary to connect to a server to reproduce the issue

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');

const schema = mongoose.Schema({
  field1: [mongoose.Schema({
    field2: mongoose.Schema({
      field3: Boolean,
    }),
  })],
});

console.log(schema.path('field1.field2.field3'));
```
