### ISSUE TITLE
When assigning a string to a property that expects a number, the property does not update properly

### ISSUE THREAD

**Issue by chris9740** [Automattic/mongoose#10173]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When passing a string to a field that expects a number, the new value of the newly reassigned property does not update, it remains the same as it was before. In the repro code below, when we're setting the `age` to `"test"`, the property is supposed to be `"test"`, so we can validate it ourselves in the pre-validate middleware. But the middleware sees `18`, which is what the value was before we reassigned it. The built-in validator still sees `"test"`, but our custom one does not.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the code necessary for reproducing the error: https://github.com/chris9740/repro 
Run `npm i`, set the mongoose URL in .env, and `node src/index.js`. You will see that the logged value on line 48 and 52 are the same, the number `18`. The same is true for the pre-validate middleware, on line 22. You will also notice that there is an error from mongoose saying that `"test"` is not a valid string (https://pastebin.com/ZivyXzZE)

**What is the expected behavior?**

We should be able to see the new value `"test"` in the middleware, and when logging the property ourselves in the line after reassigning it

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v15.14.0
Mongoose: 5.12.5
MongoDB: v4.4.4

**Comment by IslandRhythms** [comment]
so when I ran your script, "test" did not show up once even though you say the built-in validator still see it.

**Comment by chris9740** [comment]
> so when I ran your script, "test" did not show up once even though you say the built-in validator still sees it.

There should have been an error from mongoose saying that "test" cannot be cast to a number, is there not?

**Comment by IslandRhythms** [comment]
Yeah that showed up but you had said that > The built-in validator still sees "test", but our custom one does not.
So I got a bit confused for a moment. So this is actually functioning as intended. You would need to create a custom casting or disable casting. I will provide an example later today or tomorrow.

**Comment by IslandRhythms** [comment]
Also so I know, the goal in this issue is that you want to ensure that age is always strictly a number, not a string like '18'

**Comment by chris9740** [comment]
> Also so I know, the goal in this issue is that you want to ensure that age is always strictly a number, not a string like '18'

Exactly, I want a custom hook to throw an error whenever a non-number is passed

**Comment by chris9740** [comment]
> Yeah that showed up but you had said that 
> 
> > The built-in validator still sees "test", but our custom one does not.
> 
> So I got a bit confused for a moment. So this is actually functioning as intended because casting happens first and then it goes to validation. You would need to create a custom casting or disable casting for that path. I will provide an example later today or tomorrow.

Okay, but why do I still see the output 18 in the pre validate hook? If that's the case then I would expect that the casting error should prevent it from reaching that middleware to begin with

**Comment by IslandRhythms** [comment]
You see that because the pre-validation hook runs when you attempt to save.

**Comment by IslandRhythms** [comment]
```
const mongoose = require("mongoose");
const dotenv = require("dotenv");

const { Schema } = mongoose;

const userSchema = new Schema({
    username: {
        type: Schema.Types.String,
        required: true
    },
    email: {
        type: Schema.Types.String,
        required: false
    },
    age: {
        type: Schema.Types.Number,
        required: true,
        cast: function castAge(v) {
            console.log('hello',v);
            if (typeof v === 'number') {
                console.log('hi')
                return v;
            }
            throw new Error('Invalid age!');
        }
    }
});


const User = mongoose.model("User", userSchema);

dotenv.config();



const main = async () => {
   await mongoose.connect('mongodb://localhost:27017/test', {
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: true,
    useNewUrlParser: true,
    connectTimeoutMS: 3000
});
    const user = new User({
        username: "User",
        email: "user@example.com",
        age: 18
    });

    await user.save();

    console.log("before", user.age);

    user.age = "test";

    console.log("after", user.age);

    await user.save();
}

main();
```
So what you will see is that user.age will not change and that is because when the cast throws an error, which it will, it pockets it until you attempt a `save()`. You'll see in the error message the string inserted from the throw.

**Comment by chris9740** [comment]
Thank you for this, that explains why. Instead of throwing a ValidationError, is it possible to throw my own error? My express error handler looks for a custom class `FieldError` (it's a valid error class since it extends Error) to determine the error, and when it receives something else it's programmed to always return a 500 error unknown. I could also code special cases for `ValidationError`s, but if you know a way to get it to throw a custom error class I would greatly appreciate it.

Thanks again!

**Comment by IslandRhythms** [comment]
[This may be the best you can do in this situation](https://thecodebarbarian.com/mongoose-error-handling.html)

**Comment by chris9740** [comment]
All right, much appreciated. Thanks a lot!
