### ISSUE TITLE
Default value in aggregate()

### ISSUE THREAD

**Issue by Loliticos** [Automattic/mongoose#10179]
I'm using aggregate function in order to select some document in my database, however, i'd like to user the match field to check if the property has a value defined as true, however, if the value doesn't exist, it just doesn't return the user. I'd like to "set" a default value into the aggregate function, so that I can check even if the property doesn't exist.

```js
database.users.aggregate([{ $match: { raidable: true } }, { $sample: { 1 } }])
// The following user doesn't have "raidable" as true, what I want is to set "raidable" as true if it doesnt exist.
[ { _id: '664806442406248448', __v: 0, economy: { money: 10 } } ]
```

Node: v14.16.1
Mongoose: 5.12.5
MongoDB: 4.4.5

**Comment by vkarpov15** [comment]
You have a couple of options:

1) Using `$project` + `$ifNull` with the aggregation framework: https://docs.mongodb.com/manual/reference/operator/aggregation/ifNull/
```
database.users.aggregate([{ $sample: { size: 1 } }, { $project: { raidable: { $isNull: ['$raidable', true] } } }])
```

2) Just set `raidable = true` on the result

```javascript
const user = await User.aggregate([{ $sample: { size: 1 } }]).then(res => res[0]);
if (user.raidable == null) {
  user.raidable = true;
}
```
