### ISSUE TITLE
Mongoose Error Buffering Out After 10000 ms

### ISSUE THREAD

**Issue by Pxndah** [Automattic/mongoose#10174]
Hello! A month or so ago, I had just gotten my very own Linux server and I was all ready to transfer all the files into the Linux server using an application called FileZilla. I then installed all the necessary things like pm2 and all my dependencies. I wanted to do a test run so i ran node like so: `node index.js` and it loaded everything in the console. 10 seconds later, this error pops up in the console: 
![mongoose being mongoose](https://user-images.githubusercontent.com/79818750/115976817-76368180-a537-11eb-8864-9de3f78e75b9.PNG). I was all confused so I messaged some of my friends and they said that the error would go away with time and it just fixes itself. So, I left it at that, I came back a month later trying to work this thing again and look, the same error pops up. I did everything, transfered my code to a new project, I rewrote it all, I googled trying to find the solution for hours and hours and I even deleted my mongo cluster, my project, created a new project and cluster, got the link, put it in and... Same error. None of the solutions on google solved my predicament. This error seems to be coming from the fact that its buffering out while trying to find a schema that I created called reaction-roles. This is for a discord bot using discordjs and mongoose. I have no idea how to fix this, (please note, I am not the greatest at coding and am teaching myself still, if this is some easy issue to fix, please bear with me.) 

Please help! One more thing to note, this error only comes up in the linux server, not in my visual studio code terminal or any other IDE. If you need my schema code Respond saying that and I will send it

**Comment by IslandRhythms** [comment]
I usually see that error when an individual calls a function without using async/await or .then() or does not have a monodb instance running. Read through your code again and see if any functions you are calling require that, like `reaction-roles.find()` where the error message is being pointed. If that doesn't work paste the script that contains the function `reaction-roles.find()`. Also errors do not fix themselves nor go away over time. If you ever that it should be concerning because that would mean you have an inconsistent bug which is hard to track down.

**Comment by Pxndah** [comment]
> I usually see that error when an individual calls a function without using async/await or .then() or does not have a monodb instance running. Read through your code again and see if any functions you are calling require that, like `reaction-roles.find()` where the error message is being pointed. If that doesn't work paste the script that contains the function `reaction-roles.find()`. Also errors do not fix themselves nor go away over time. If you ever encounter that it should be concerning because that would mean you have an inconsistent bug which is hard to track down.

So basically, as I said before, I even changed my project and started using another command handler called wokcommands, I am not sure what it is but when it always has to do with my schema/model: 
![for git](https://user-images.githubusercontent.com/79818750/116157881-5a57ea80-a6b3-11eb-9dc5-5ccb989c46ef.PNG)
as you can see this is my model, I never call for a "reaction-roles.find" at all in my code, perhaps thats just mongoose calling for it? Cause in the error message the error is coming from the nodemodules of mongoose. How would i fix this? Please help this has been going on for months and im so confused.

**Comment by IslandRhythms** [comment]
where else do you use that model? Some of the other model functions call find under the hood so that tells me you might be using findOneAndUpdate for example somewhere else.

**Comment by Pxndah** [comment]
> where else do you use that model? Some of the other model functions call find under the hood so that tells me you might be using findOneAndUpdate for example somewhere else.

Well, yes there are multiple instances where i use the find and findoneandupdate methods; "await messageSchema.findOneAndUpdate(
      obj,
      {
        ...obj,
        $addToSet: {
          roles: {
            emoji,
            roleId: role.id,
          },
        },
      },
      {
        upsert: true,
      }
    )" This is one example, another example is here; "  const results = await messageSchema.find()" but I am not super sure why its causing a problem... any ideas?

**Comment by IslandRhythms** [comment]
and you wrapped the function this is being called in async, so `async function whatever()` ?

**Comment by Pxndah** [comment]
> and you wrapped the function this is being called in async, so `async function whatever()` ?

yes exactly an async callback function (i use es6), module.exports = {
name: 'fljsdkaf',
description: 'idk',
category: 'Support',
callback: async ({ message, guild, args }) => {
code for findoneandupdate goes here
}
}

**Comment by IslandRhythms** [comment]
ok so most likely you are not successfully connecting to mongodb. Check to make sure you connection logic is ok and if it is try disabling buffering and it should give a more helpful error message

**Comment by Pxndah** [comment]
Well, I did all that, Inside of my command handler there is  a module.exports.config  object which will specify if I need to load the database first or do it before that,  here is an example with the comments to explain more: 
module.exports.config = {
  // The display name that server owners will see.
  // This can be changed at any time.
  displayName: 'Reaction Roles',
  
  // The name the database will use to set if it is enabled or not.
  // This should NEVER be changed once set, and users cannot see it.
  dbName: 'REACTION ROLES',
  
  // Being true means a database connection must be present before the
  // feature is enabled.
  loadDBFirst: true
}

This is the basic idea but its supposed to wait for  a stable connection from mongo, I also have an event in my index.js
![image](https://user-images.githubusercontent.com/79818750/116452523-6d89c800-a823-11eb-8ece-e855d0cf4a75.png)
which states if it has connnected or not, 
![image](https://user-images.githubusercontent.com/79818750/116452573-7b3f4d80-a823-11eb-92d9-424b3f639020.png)
I will try deleting all the files from the server and transfering them again just in case.

**Comment by IslandRhythms** [comment]
Did you try logging the connection?

**Comment by Pxndah** [comment]
Wait this is interesting, it will say "The connection
![image](https://user-images.githubusercontent.com/79818750/116453138-205a2600-a824-11eb-85d0-fda3ec0558fc.png)
 state is "Connected" But, in the linux server I dont get that, instead i get this error ^^^

**Comment by IslandRhythms** [comment]
is that address the address for your mongodb cluster?

**Comment by Pxndah** [comment]
Pretty sure yes; what do you think is the issue here? Iam sorry im not good at this stuff :/

**Comment by IslandRhythms** [comment]
you enabled remote connections to your db?

**Comment by Pxndah** [comment]
> you enabled remote connections to your db?

Sorry, What does this mean? Can you explain on how exactly I should do this?

**Comment by IslandRhythms** [comment]
https://intercom.help/mongodb-compass/en/articles/1898157-connection-3-to-cluster0-shard-00-00-a1b2c-mongodb-net-27017-closed

**Comment by Pxndah** [comment]
Ok, I have done this and now I guess we wait 10 mins? I hope this works :/ This error has been plaguing me for months

**Comment by Pxndah** [comment]
Thanks for the help

**Comment by Pxndah** [comment]
So uh I followed the article and all the steps but I got the same error

> https://intercom.help/mongodb-compass/en/articles/1898157-connection-3-to-cluster0-shard-00-00-a1b2c-mongodb-net-27017-closed

**Comment by IslandRhythms** [comment]
And you entered the linux server's ip address, not the one in the article?

**Comment by Pxndah** [comment]
OMG WAIT I THINK THAT WAS IT IT SAYS CONNECTED NOW

**Comment by Pxndah** [comment]
HOLD ON LEMME TEST SOME COMMANDS AND ILL CLOSE THIS IF IT WORKS

**Comment by Pxndah** [comment]
TYSM DUDE

**Comment by IslandRhythms** [comment]
no problem

**Comment by Pxndah** [comment]
DUDE UR AMAZING TYSM

**Comment by Pxndah** [comment]
LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO WOOOOOOOOOHOOOOOOOOOOOOOO TYSMMMM

**Comment by Pxndah** [comment]
ACTUAL LEGEND
