### ISSUE TITLE
document.toJSON doesn't toJSON _id

### ISSUE THREAD

**Issue by timoxley** [Automattic/mongoose#1018]
if you toJSON a mongoose model, the _id remains an object. 

this is a problem if you're trying to compare against an actual json representation of the same object.

Simple solution is to

``` js
JSON.parse(JSON.stringify(model))
```

but that's real ugly.

Is there a good reason the id isn't stringified? If not, I'll fix up the toJSON in a PR.

**Comment by booxood** [comment]
`toJSON a mongoose model, the _id remains an object`
It is easy to make mistakes when make test compare...

**Comment by ZacharyRSmith** [comment]
In case this helpful to anyone, I had to create [this perf-thinking lib](https://www.npmjs.com/package/transform-props) to cast ObjectIDs to string.

```javascript
var transformProps = require('transform-props');
 
function castToString(arg) {
    return String(arg);
}
 
var doc = new MongooseModel({ subDoc: { foo: 'bar' }});
var docObj = doc.toObject();
 
transformProps(docObj, castToString, '_id');
 
console.log(typeof docObj._id); // 'string'
console.log(typeof docObj.subDoc._id); // 'string'
```
