### ISSUE TITLE
mongoose ref does not work properly

### ISSUE THREAD

**Issue by nodejsdeveloperskh** [Automattic/mongoose#10199]
**What is the current behavior?**

Example: I have a **user** collection and a **role** collection. `user` fields: name, roleId. when I insert a new document in the `user` collection the roleId value does not exist in the `role` collection. but it does not throw an error.

**If the current behavior is a bug, please provide the steps to reproduce.**

I create a public repo for it: https://github.com/nodejsdeveloperskh/mongoose-ref-does-not-work

**What is the expected behavior?**

Throws an error. Something like constraints foreign key error

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**

Nodejs: 14.16.1
mongoose: 5.12.7
mongodb: 3.6.6

**Comment by IslandRhythms** [comment]
```
(node:21684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of null
    at C:\Users\Daniel Diaz\Desktop\Work\debugging\repos\mongoose-ref-does-not-work-main\index.js:55:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nodejsdeveloperskh** [comment]
> ```
> (node:21684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'title' of null
>     at C:\Users\Daniel Diaz\Desktop\Work\debugging\repos\mongoose-ref-does-not-work-main\index.js:55:29
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:21684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:21684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

This is what is wanna show you. there is no document in the database for the [second user](https://github.com/nodejsdeveloperskh/mongoose-ref-does-not-work/blob/main/index.js#L43), therefore the roleId will be null and if I try to get it by this line of code: [`user.roleId.title`](https://github.com/nodejsdeveloperskh/mongoose-ref-does-not-work/blob/main/index.js#L55), it throws an error.

**What I try to show:**
- when I create the [second user](https://github.com/nodejsdeveloperskh/mongoose-ref-does-not-work/blob/main/index.js#L43) mongoose does not check if there is a document with the given roleId in the database.

**Comment by vkarpov15** [comment]
This is expected behavior, Mongoose does not enforce any constraints on existence of referenced documents. We cannot enforce this sort of constraint in the general case unless the MongoDB server provides this feature. But, if you need this functionality, you can implement it with a [`pre('save')` middleware](https://mongoosejs.com/docs/middleware.html).

**Comment by nodejsdeveloperskh** [comment]
@vkarpov15 yes, you're right. The MongoDB server does not provide this feature. BUT thanks for your guide ([pre(save)](https://mongoosejs.com/docs/middleware.html#pre))
