### ISSUE TITLE
Uncaught TypeError: Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by arpitgupta2405** [Automattic/mongoose#10197]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I'm currently working on migrating mongoose version from v5.6.5 to v5.12.7.
When trying to use toObject() on a mongoose object, I'm getting this error "Uncaught TypeError: Cannot read property 'paths' of undefined"
Please note: this was working fine on v5.6.5
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should convert the mongoose object to a plain javascript object
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJs => v12.15.0
Mongoose => v5.12.7
MongoDb => v4.0.24

**Comment by vkarpov15** [comment]
Without code samples, we're unlikely to be able to repro this issue. Please provide a standalone script that repros this error.

**Comment by arpitgupta2405** [comment]
This issue was occurring due to some other npm module, hence closing this ticket.
Sorry for the inconvenience. 🙇‍♂️
