### ISSUE TITLE
Make CastError: Cast to embedded failed for value XXX at path XXX easier to debug

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#10207]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature request**
Currently, the following error is thrown:

`CastError: Cast to embedded failed for value "{ id: 'xxxxxxx', itemType: 'invoice' }" at path "linked"`

It took me a fair amount of time to spot the error, and find that my `itemType` property was defined as a `Date` instead of a `String`. This is not very obvious.

It would be great if the CastError could actually identify the problem, for example by throwing:

`CastError: Cast to embedded failed for value "{ id: 'xxxxxxx', itemType: 'invoice' }" at path "linked". Value 'invoice' is a String, expected Date.`

**Comment by vkarpov15** [comment]
Given the below script:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    subdoc: new Schema({
      value: Number
    })
  });
  const Test = mongoose.model('Test', schema);

  await Test.create({ subdoc: { value: 'not a number' } });
  console.log('Done');
}

```

The new error message looks like this: 

```
Error: Test validation failed: subdoc.value: Cast to Number failed for value "not a number" (type string) at path "value", subdoc: Validation failed: value: Cast to Number failed for value "not a number" (type string) at path "value"
```

Also, I haven't been able to repro the case where you get "CastError: cast to embedded failed", you shouldn't get that error message unless you have some custom casting logic on your single nested subdoc. Can you please provide more info on how that happened?

**Comment by adamreisnz** [comment]
Thanks for the update, I will see if I can dig up where it happened. From memory, we were passing an invalid value at a path where an embedded subdoc was expected by Mongoose, and hence that error. There was no custom casting logic involved.

**Comment by adamreisnz** [comment]
Maybe try `await Test.create({ subdoc: 'not a subdoc' });`

**Comment by adamreisnz** [comment]
I've run some tests in our latest build with Node 16 and latest mongoose, and I observe that we are now getting more details with these kind of errors. I think this can be closed. I am also unable to reproduce this with our production build. If we run into it again, I will reopen. Thanks!
