### ISSUE TITLE
Static variables declared on advanced schemas are not loaded into the model

### ISSUE THREAD

**Issue by meircarlos** [Automattic/mongoose#10206]
When declaring a static variable on a class loaded with `loadClass` into the schema, the static variable does not get loaded into the model.

In order for it to work, you need to explicitly declare the static variable through the classic function property `schema.statics` approach.

In order to reproduce:
1. Create a model through [advanced schemas](https://mongoosejs.com/docs/4.x/docs/advanced_schemas.html)
2. Add a static variable, example: static TEST = true;
3. Try accessing the static variable from the model (it will not exist)

Mongoose v5.9.2

**Comment by IslandRhythms** [comment]
> static TEST = true;
This isn't standard javascript so we need to know more about your set up if we are going to attempt to repro this issue. Alternatively, you can provide a script with notes about your setup that demonstrates this problem.

**Comment by meircarlos** [comment]
Here is the code to reproduce this issue:
```
const mongoose = require("mongoose");

const schema = new mongoose.Schema({ firstName: String, lastName: String });

class PersonClass {
  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }

  set fullName(v) {
    const firstSpace = v.indexOf(" ");
    this.firstName = v.split(" ")[0];
    this.lastName = firstSpace === -1 ? "" : v.substr(firstSpace + 1);
  }

  getFullName() {
    return `${this.firstName} ${this.lastName}`;
  }

  static findByFullName(name) {
    const firstSpace = name.indexOf(" ");
    const firstName = name.split(" ")[0];
    const lastName = firstSpace === -1 ? "" : name.substr(firstSpace + 1);
    return this.findOne({ firstName, lastName });
  }

  // Does not work
  static TEST = true;
}

schema.loadClass(PersonClass);

// Uncomment this line for it to work
// schema.statics.TEST = true;

var Person = mongoose.model("Person", schema);

console.log(Person.TEST); // undefined
```

**Comment by IslandRhythms** [comment]
> static Test = true

This applies to the person class so

> console.log(Person.TEST);

will return undefined but

`console.log(PersonClass.TEST)` will return true

**Comment by meircarlos** [comment]
Sure, but the static method `findByFullName` also belongs to the PersonClass and it's accessible from the Person model, why would this behavior be avoided for static variables when it works correctly for static methods?

Otherwise the workaround I'm currently doing is duplicating the static variable and adding it to the schema statics, as you can see on the commented lines of code

**Comment by IslandRhythms** [comment]
We'll be implementing this soon
