### ISSUE TITLE
[5.12.7] FindOne projection step not working as expected. 

### ISSUE THREAD

**Issue by guillempuigcom** [Automattic/mongoose#10205]
We are currently using the latest version of mongoose **^5.12.7**
Before the update, we were using version **5.12.3**

**What is the current behaviour?**
Actually, the `findOne` projection is not allowing to create a new field where to store a certain value of the retrieved document.

E.g.
**Queried Document**
```json
{
  "_id": "123124342423",
  "name": "blabla",
  "searchWeight": {
      "value": 1,
  }
}
```
**Query**
```javascript
const getSearchWeightValueField = async (name, model) => model.findOne({ name }, { value: '$searchWeight.value' }).lean();
```

**What is the expected behaviour?**
Before the version update, the query was working just fine, now it assigns `null/undefined` as the value of the projected `value` field.

**Additional**
If we run the `findOne` query directly to a GUI tool like `noSqlbooster` or `robo3t`, the query is working as expected and returning an object with `{_id:123131243, value: 1}`. However, it does not work as we expect through mongoose.

To reproduce the same behaviour as we were getting with the **5.12.3** version we have been forced to change our query and our code logic to:
**query**
```javascript
const getParentWeightValue = async (name, model) => model.findOne({ name }, { 'searchWeight.value': 1 }).lean();
...
const value = getParentWeightValue.searchWeight.value
```

**DOUBT**
Is this behaviour the one expected by mongoose? Or there is some bug?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
**Mongo**: 4.4.4
**Node.js**: v14.16.1
**Mongoose**: "5.12.7"

**Comment by Kamikadze4GAME** [comment]
Related to #10188
