### ISSUE TITLE
BUG: Schema.loadClass typescript definition does not match schema.js definition

### ISSUE THREAD

**Issue by CDaxi** [Automattic/mongoose#10202]
Bug report for mongoose version 5.12.7

**What is the current behavior?**

Mongoose is used within NestJS and the virtuals should be loaded via loadClass from class definition.
The method arguments are defined wrong if you want to use onlyVirtuals argument.

https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/index.d.ts#L1114

```
CalendarSchema.loadClass(Calendar, true);
```

in this case, typescript only works in combination with @ts-ignore

```
// @ts-ignore
CalendarSchema.loadClass(Calendar, true);
```

Source code of Schem.loadClass:
https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/lib/schema.js#L1900

**If the current behavior is a bug, please provide the steps to reproduce.**
see above

TS Config:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "paths": {...}
  }
}
```

**What is the expected behavior?**

index.d.ts has to be changed to include onlyVirtuals argument:

```
loadClass(model: Function, onlyVirtuals: boolean = false): this;
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node version: v16.0.0
Mongoose version 5.12.7
MongoDB Community version 4.4

**Comment by vkarpov15** [comment]
We need to add `onlyVirtuals` to the `loadClass()` definition in `index.d.ts`
