### ISSUE TITLE
Skip validation for certain path(s) in Document.validate() method

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#10216]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Unable to skip or prevalidate or bypass the validation for a path on mongoose

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a model
2. Add required validator on a path
3. Run the doc.$markValid("path")
4. Try `doc.validate(["path"]).catch(e => console.log(Object.keys(e.errors).length))`
5. The length would be == 1

Here I want to bypass the `required` validation for gwId field
![image](https://user-images.githubusercontent.com/28386721/117501570-dbf52580-af9b-11eb-871f-c71a9a71b4e6.png)

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "./dist",
    "strict": true,
    "noImplicitAny": true,
    "typeRoots": ["./ctypings", "./node_modules/@types"],
    "types": ["express", "express-session", "process", "express-request-id"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules", "./node_modules", "./node_modules/*", "./node_modules/@types/node/index.d.ts"],
  "include": ["src/**/*.ts", "ctypings/**/*.ts"]
}
````

**What is the expected behaviour?**

Well, $markValid should bypass all the validators for one or more paths (except unique)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.12.7

Node: v14.16.0

Mongodb: 3.6.6

**Comment by tbhaxor** [comment]
Any updates @mongoose team?

**Comment by IslandRhythms** [comment]
Thats not how $markModified works according to the docs
https://mongoosejs.com/docs/api/document.html#document_Document-markModified

**Comment by tbhaxor** [comment]
@IslandRhythms Please read my issue again

I am talking about $markValid not $markModified. Also $markModified is not any function, it's markModified

**Comment by tbhaxor** [comment]
@IslandRhythms Done, and apologies for that.

Could you now look into this issue?

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    name: {
        type: String, 
        required: true
    },
    nickname: {
        type: String
    }
});
    const Test = new mongoose.model('Test', testSchema);

    async function run() {
        await mongoose.connect('mongodb://localhost:27017/test', {
            useNewUrlParser: true,
            useUnifiedTopology: true
          });
        
        await mongoose.connection.dropDatabase();

        const entry = await Test.create({nickname: 'Test'});
        entry.$markValid('name');
        await entry.validate('name').catch(e=> console.log('Yo', Object.keys(e.errors).length));
    }
    run();

```

**Comment by tbhaxor** [comment]
@IslandRhythms Is there any changelog for each mongoose release?

**Comment by vkarpov15** [comment]
@tbhaxor yes, here's the link: https://github.com/Automattic/mongoose/blob/master/History.md

**Comment by vkarpov15** [comment]
I'm currently working on a series of blog posts about that very subject :) First one is here: http://thecodebarbarian.com/mongoose-internals-schemas-options-models.html .

Re: sanitizing query filters, we're working on that for Mongoose 6.0. Follow #3944 for updates.

**Comment by tbhaxor** [comment]
> I'm currently working on a series of blog posts about that very subject :) First one is here: http://thecodebarbarian.com/mongoose-internals-schemas-options-models.html .
> 
> Re: sanitizing query filters, we're working on that for Mongoose 6.0. Follow #3944 for updates.

Nice blog, @vkarpov15 . I need more posts to be confident about sending quality PR's to the repo. How can I subscribe to the blog?

**Comment by vkarpov15** [comment]
RSS: http://thecodebarbarian.com/feed.xml, or my Twitter: https://twitter.com/code_barbarian . There's only one post so far, so I would recommend tinkering with the code and starting with a small bug or feature if you want to contribute.

One good place to start would be #10230, which is closely related to the problem you're trying to solve with this issue and should be about the right level of complexity for a first contribution.

**Comment by vkarpov15** [comment]
I'm going to close this issue for now, we made a workaround for 5.12.9, and #10230 will give us a better approach for 5.13.
