### ISSUE TITLE
_id should be null in Schema.pre('save') scope for yet to be created documents

### ISSUE THREAD

**Issue by christarnowski** [Automattic/mongoose#1021]
Currently the pre-save hook in Mongoose pre-populates the `_id` field for yet-to-be-created documents. Hence the following piece of code won't work as expected:

``` coffeescript
User.pre 'save', true, (next, done) ->
    next()

    if @_id == null
       # This should execute only on document creation,
       # but _id is never null
        bcrypt.hash @password, 10, (err, hash) =>
            @password = hash
            done()
    else
        done()
```

**Comment by reilg** [comment]
This doesn't seem to be the case anymore. Did it change? I'm getting an `undefined` value.

```
AddressSchema.pre('save', function( next ) {

	console.log( this._id );
});
```

I know this is pretty old but I can't seem to find any information on this anywhere else.

**Comment by vkarpov15** [comment]
@reilg can you open up a new issue with a more complete code sample? If that's happening, that could be a bug.

**Comment by reilg** [comment]
@vkarpov15 It seems to be a bug from the [auto-increment plugin](https://www.npmjs.com/package/mongoose-auto-increment) I'm using and not mongoose. 

Removing the plugin now shows the Id. Thanks.
