### ISSUE TITLE
TS/ESlint: pre hook returning a Promise

### ISSUE THREAD

**Issue by qqilihq** [Automattic/mongoose#10229]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

We just updated to the latest Mongoose version 5.12.8 and got rid of the `@types/mongoose`. We had a couple of `pre` `save` hooks which used an `async` function. This has worked fine so far (i.e. compiled via TypeScript and verified working at runtime).

**If the current behavior is a bug, please provide the steps to reproduce.**

Since using Mongoose’s typings, the following code produces an ESLint error:

```typescript
// PRODUCES ESLINT ERROR:
// Promise returned in function argument where a void return was expected.eslint
// @typescript-eslint/no-misused-promises
mySchema.pre('save', async function () {
   // some async function returning a Promise
});
```

**What is the expected behavior?**

I assume that it’s valid behavior to return a Promise (as stated, Mongoose handled this fine in the past). So the typings should include the case of returning a `Promise<void>` instead of `void`, so that the linting passes.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

* Mongoose 5.12.8
* ESLint with `plugin:promise/recommended`

**Comment by vkarpov15** [comment]
Thanks for reporting, we'll look into this and fix over the next couple of days if we can confirm this is a bug.

**Comment by qqilihq** [comment]
Great, thanks! Let me know if I can help with a reporduction!
