### ISSUE TITLE
http_parser warning

### ISSUE THREAD

**Issue by LOLBRUHNICE** [Automattic/mongoose#10221]
**Do you want to request a *feature* or report a *bug*?**

Type:bug

**What is the current behavior?**
logging the deprecated warning:
(node:23160) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

**If the current behavior is a bug, please provide the steps to reproduce.**

script:
```
mongoose
		.connect(mongoDB_URL, {
			useNewUrlParser: true,
			useUnifiedTopology: true,
			useFindAndModify: false,
			useCreateIndex: true,
		})
```

```
tsconfig.json:
{
	"compilerOptions": {
		"lib": ["ESNext"],
		"module": "commonjs",
		"moduleResolution": "node",
		"target": "ESNext",
		"outDir": "dist",
		"sourceMap": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"allowSyntheticDefaultImports": true,
		"skipLibCheck": true,
		"skipDefaultLibCheck": true,
		"resolveJsonModule": true,
		"incremental": true
	},
	"include": ["src"]
}
```
**What is the expected behavior?**
no deprecated warning

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs:16.1.0
mongoose:5.12.7
mongodb: mongodb+src 4.4

**Comment by vkarpov15** [comment]
Please use `node --trace-deprecation` to find where this deprecation warning is coming from and post the stack trace. Mongoose does not use HTTP, so I would be quite surprised if this deprecation warning came from Mongoose.
