### ISSUE TITLE
Convert mongodb to a peer dependency?

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#10237]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

https://github.com/Automattic/mongoose/blob/master/package.json lists mongodb under `dependencies`. This is not per see incorrect in this scenario, but it has been noticed that mongodb often receives security updates which require us to upgrade mongoose as well. If mongodb was listed as a peer dependency, it would make it possible for us to upgrade mongodb separately from mongoose. Also in npm 7, peer dependencies are automatically installed. So maybe this would be a breaking change.

The downside of this is of course that it is not really a peer dependency in how peer dependencies are supposed to be used, I believe.

**Comment by vkarpov15** [comment]
We've thought about doing this for some time, but the biggest reason why not is that Mongoose is very closely coupled to the MongoDB driver, and it isn't uncommon for there to be differences between patch versions of the MongoDB driver that break Mongoose's tests. So it would be tricky for us to maintain compatibility with a wide range of MongoDB driver versions.

We try our best to upgrade to new versions of the MongoDB driver as they come out.

**Comment by thernstig** [comment]
@vkarpov15 I figured it could be something like that. It sounds like a pragmatic approach to me, as increasing your maintenance burden on supporting this is probably not worth it. Closing but feel free to re-open.
