### ISSUE TITLE
Auto add Timestamps is raising an error $__isSelected is not a function

### ISSUE THREAD

**Issue by soubhikchatterjee** [Automattic/mongoose#10259]
I am trying to save some data to a mongoose (version 5.11.8) collection and want the "createdAt" and "updatedAt" fields to automatically insert. Hence i added the **{ timestamps: true }** as the second parameter in the schema

This is my model schema

    "use strict";
    
    const mongoose = require("mongoose");
    const Schema = mongoose.Schema;
    
    const notificationSchema = new Schema(
      {
        type: String,
        author: String,
        metadata: Object,
        link: String
      },
      { timestamps: true }
    );
    
    module.exports = notificationSchema;

This is how i am inserting the records
 

     try {
        const notification = new Notification({
          type: "user",
          author: "phantom",
          metadata: {
            filename: "internet.png"
          },
          link: "http://yahoo.com"
        });
        const r = await notification.save();
        console.log(`r`, r);
      } catch (error) {
        console.error(error);
      }

But I get this error and the data does not save

> this.$__isSelected is not a function

Stacktrace:

    TypeError: this.$__isSelected is not a function
        at model.<anonymous> (/Users/phantom/projects/personal/backend/service1/node_modules/mongoose/lib/helpers/timestamps/setupTimestamps.js:54:69)
        at callMiddlewareFunction (/Users/phantom/projects/personal/backend/service1/src/submodules/node_modules/kareem/index.js:483:23)
        at model.next (/Users/phantom/projects/personal/backend/service1/src/submodules/node_modules/kareem/index.js:58:7)
        at _next (/Users/phantom/projects/personal/backend/service1/src/submodules/node_modules/kareem/index.js:107:10)
        at /Users/phantom/projects/personal/backend/service1/src/submodules/node_modules/kareem/index.js:508:38
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

When i dug up the **setupTimestamps.js** file at *node_modules/mongoose/lib/helpers/timestamps/setupTimestamps.js*, i saw this piece of code, which did not make any sense to me

    if (!skipCreatedAt && createdAt && !this.get(createdAt) && this.$__isSelected(createdAt)) {
      this.$set(createdAt, auto_id ? this._id.getTimestamp() : defaultTimestamp);
    }

When i make the { timestamps: false } then the record gets inserted without any error. I want mongoose to automatically create createdAt and modifiedAt fields automatically.

Did anyone faced this error before, and how did you fix this?

**Comment by Kamikadze4GAME** [comment]
@soubhikchatterjee how did you init the model (smth like 'mongoose.model('ModelName', mySchema)?

**Comment by IslandRhythms** [comment]
```
'use strict';

const mongoose = require('mongoose');
const {Schema} = mongoose;

const notificationSchema = new Schema(
    {
      type: String,
      author: String,
      metadata: Object,
      link: String
    },
    { timestamps: true }
  );

  const Notification = mongoose.model('Notification', notificationSchema);

async function test() {

    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
    
    await mongoose.connection.dropDatabase();

    try {
        const notification = new Notification({
          type: "user",
          author: "phantom",
          metadata: {
            filename: "internet.png"
          },
          link: "http://yahoo.com"
        });
        const r = await notification.save();
        console.log(`r`, r);
      } catch (error) {
        console.error(error);
      }
}

test();
```

**Comment by LawP09** [comment]
Good morning.
I have exactly the same issue as @soubhikchatterjee with mongoose 5.13.0, NodeJS 14.17.1

Schema creation : 
```import { Schema } from 'mongoose';

export const receiptBatchImportRequestLockSchema: Schema<IReceiptBatchRequestLock> = new Schema(
  {
    _id: String
  },
  { timestamps: true }
);

export interface IReceiptBatchRequestLock {
  _id: string;
  createdAt?: Date;
  updatedAt?: Date;
}
```

Model creation : 
``` 
import * as mongoose from 'mongoose';

private db: mongoose.Connection;
private receiptBatchImportRequestLockModel: mongoose.Model<IReceiptBatchRequestLock>;

this.receiptBatchImportRequestLockModel = this.db.model<IReceiptBatchRequestLock>(
    'receiptBatchImportRequestLock',
    receiptBatchImportRequestLockSchema,
    'receiptBatchImportRequestLock'
);
```

Save in MongoDB (v4.2) : 
```
  public async createReceiptBatchImportRequestLock(lock: IReceiptBatchRequestLock, session: mongoose.ClientSession) {
    logger.info('#createReceiptBatchImportRequestLock ...');
    try {
      this.initialize();
      const result = new this.receiptBatchImportRequestLockModel(lock);
      await result.save({ session });
      return result;
    } catch (error) {
      logger.error({ error }, 'Error when creating a Receipt Batch Import Request Lock.');
      throw error;
    }
  }
``` 

- When I put `{ timestamps: false }` it works correctly and don't save createdAt and updatedAt fields

- When I remove `this.$__isSelected(createdAt)` from the setupTimestamps.js file it works correctly and save createdAt and updatedAt fields into the DB.

What the $__isSelected function is supposed to do. I tried to debug but I found nothing.

Thanks in advance for your investigation.
