### ISSUE TITLE
TypeError: model.collection.addQueue is not a function because property "collection" is overwritten when loading class and "collection" was provided in class

### ISSUE THREAD

**Issue by Eluminati** [Automattic/mongoose#10254]
version 5.12.8 worked fine and since 5.12.9 the following bug occures when building the schemas:

```javascript
TypeError: model.collection.addQueue is not a function
     at D:\Atom_projects\ba\node_modules\mongoose\lib\model.js:1693:30
     at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
I don't know how to reproduce this, but the logging on the tracebacks given position, following will be printed:

Line of code:
```javascript
model.collection.addQueue(create, []);
```
logging: `console.log(model, model.collection, model.collection.addQueue)`

Result:

```javascript
THE MODEL: Model { SystemUser }
THE COLLECTION: users
THE FUNCTION: undefined
```

The model SystemUser is derived from Model user and both have the same collection.
The collection "users" seems to be a String instead of a "NaviveCollection"-Object

Expected behavior is to queue the collection

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.13.0
mongoose: 5.12.9
MongoDB: 4.4.2 Community

**Comment by Eluminati** [comment]
Found the reason. I had a static property called "collection" and I loaded the whole class to the model. So the loading has overwritten the models property "collection". Maybe there should be an error message which protects internal properties from overwrite or add a mapping to an alternative, internal choosen name.

**Comment by vkarpov15** [comment]
Any code in `model.js` that uses `this.collection` should use `this.$__collection` instead, and models should have both a `collection` and a `$__collection` property that point to the underlying collection object. We should use `$__collection` internally to minimize risk of conflicts, but we should leave `collection` for backwards compatibility.

**Comment by Eluminati** [comment]
The same should be done with schema ans all other things which could be overwritten by loading a class into the schema.
