### ISSUE TITLE
Specify _id with uuid

### ISSUE THREAD

**Issue by porsager** [Automattic/mongoose#1026]
Hi. 

We want to use client generated id's in the form of UUID's in our setup, and would like to know if this is supported by Mongoose, or if there is an implementation to make it work??

It should be possible with Mongo to do this as per: http://www.mongodb.org/display/DOCS/Object+IDs#ObjectIDs-UUIDs

It seems the problem is with casting the _id when creating a new document, so maybe a plugin to mongoose to override this function could be made?

**Comment by rsp** [comment]
@jaufgang the `UUID()` function in Mongo is a little bit strange. It doesn't work for valid UUIDs:
```
> UUID('343881b7-852c-46cf-b74c-4a0bca2fae9c')
E QUERY    Error: UUID string must have 32 characters
```
while according to Wikipedia:
> In its canonical textual representation, the sixteen octets of a UUID are represented as 32 lowercase hexadecimal (base 16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for **a total of 36 characters**

See: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

It only works when you manually remove the dashes:
```
> UUID('343881b7852c46cfb74c4a0bca2fae9c')
BinData(3,"NDiBt4UsRs+3TEoLyi+unA==")
```

@porsager For using UUIDs with Mongoose, there are two modules that you can use:

* https://www.npmjs.com/package/mongoose-uuid
* https://www.npmjs.com/package/mongoose-uuid2

See also those issues:

* https://github.com/Automattic/mongoose/issues/2738
* https://github.com/Automattic/mongoose/issues/3208

and this article for some potential problems with binary UUID representations in Mongo:

* http://3t.io/blog/best-practices-uuid-mongodb/
