### ISSUE TITLE
Restart project connection database timeout

### ISSUE THREAD

**Issue by wjl8** [Automattic/mongoose#10268]
```
**error**
connection error: Error: querySrv ESERVFAIL _mongodb._tcp.collext.9hlow.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19) {
  errno: undefined,
  code: 'ESERVFAIL',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.collext.9hlow.mongodb.net'
}
(node:59564) UnhandledPromiseRejectionWarning: Error: querySrv ESERVFAIL _mongodb._tcp.collext.9hlow.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

"express": "~4.16.1"
"mongoose": "^5.12.2"
nodejs：v14.16.1

**Comment by vkarpov15** [comment]
Without a more detailed code sample, no way we'll be able to repro this. Please provide a standalone script that demonstrates this issue.

**Comment by wjl8** [comment]
> 没有更详细的代码示例，我们将无能为力。请提供一个独立的脚本来演示此问题。

const { v4: uuidv4, stringify } = require('uuid');
// 数据库连接
const mongoose = require('mongoose');

mongoose.connect('', { useNewUrlParser: true, useUnifiedTopology: true });// dev

var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function () {
    console.log('we are connected');
});

var tradeInfoSchema = mongoose.Schema({
    
    name:String,
    events:String,      //created,transfer,listing,sales,bids
    image: String,
    price:String,
    quant:String,       

})
var tradeInfo = mongoose.model("tradeInfo",tradeInfoSchema, "tradeInfo");

module.exports = {
    "tradeInfo": tradeInfo,
}

**Comment by vkarpov15** [comment]
How are you restarting the project? pm2, nodemon, something else?

**Comment by wjl8** [comment]
> 你是怎么重启项目的？pm2，nodemon，还有什么？

nodemon

**Comment by vkarpov15** [comment]
We'll try this out and see if we get a similar error restarting a Mongoose app that's connected to Atlas with nodemon.

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');

var tradeInfoSchema = mongoose.Schema({
    
    name:String,
    events:String,      //created,transfer,listing,sales,bids
    image: String,
    price:String,
    quant:String,       

})
var tradeInfo = mongoose.model("tradeInfo",tradeInfoSchema, "tradeInfo");


async function run() {
    mongoose.connect('Your connection string here', { useNewUrlParser: true, useUnifiedTopology: true });// dev

var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function () {
    console.log('we are connected');
});
}

run();
```
