### ISSUE TITLE
Map Type default value not added as JS Map

### ISSUE THREAD

**Issue by AlexRies** [Automattic/mongoose#10277]
Hello,

there seems to be a problem with settings default values for the map type.

#### Steps to reproduce:
I'm using the following schema declaration:
```
const schema = new Schema({
  testMap: {
      type: Map,
      of: String,
      default: new Map(),
    },
});
```

mongoose version: `^5.10.19`

#### Observed:
When new entries are created for the model without specifying `testMap`, the value for `testMap` is `{}` and has no `set` and `get` functions. `newEntry`

#### Desired:
The value for `testMap` should be a JS Map with `set` and `get` functions.

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    testMap: {
        type: Map,
        of: String,
        default: new Map()
    }
});

const Test = mongoose.model('Test', testSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
      
      await mongoose.connection.dropDatabase();

      const entry = await Test.create({});
      console.log(entry)
      entry.testMap.set('github', 'vkarpov');
      console.log(entry)
}

test();
```

**Comment by vkarpov15** [comment]
I would also recommend doing `default: () => new Map()`. If you're trying to set a default to an object, you should use a function instead.
