### ISSUE TITLE
Issue when connecting to a single node replicaset

### ISSUE THREAD

**Issue by kaykhancheckpoint** [Automattic/mongoose#10270]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Mongoose fails to connect to a mongodb replicaset when setting `replicaset=rs0`. Removing this replicaset=rs0 it connects to it fine.

> {"message":{"error":{"message":"getaddrinfo ENOTFOUND mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local","reason":{"type":"ReplicaSetNoPrimary","setName":"rs0","maxSetVersion":2,"maxElectionId":"7fffffff0000000000000003","servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":9}},"error_stack":"MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local\n    at NativeConnection.Connection.openUri (/home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/connection.js:846:32)\n    at /home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/index.js:351:10\n    at /home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (/home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)\n    at Mongoose._promiseOrCallback (/home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/index.js:1149:10)\n    at Mongoose.connect (/home/kay/checkpoint/steam/concurrentusers/node_modules/mongoose/lib/index.js:350:20)\n    at Object.MongoDBService [as default] (/home/kay/checkpoint/steam/concurrentusers/src/services/mongo.service.ts:19:24)\n    at Object.exports.ConcurrentUsers (/home/kay/checkpoint/steam/concurrentusers/src/ConcurrentUsers.ts:13:29)\n    at Object.<anonymous> (/home/kay/checkpoint/steam/concurrentusers/src/ConcurrentUsers.ts:33:1)\n    at Module._compile (internal/modules/cjs/loader.js:1137:30)\n    at Module.m._compile (/home/kay/checkpoint/steam/concurrentusers/node_modules/ts-node/src/index.ts:858:23)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/kay/checkpoint/steam/concurrentusers/node_modules/ts-node/src/index.ts:861:12)\n    at Module.load (internal/modules/cjs/loader.js:985:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:878:14)"},"level":"error","timestamp":"2021-05-19T08:59:11.430Z"}

https://mongoosejs.com/docs/connections.html#replicaset_connections

**If the current behavior is a bug, please provide the steps to reproduce.**

**mongodb**
```
import mongoose from "mongoose";
import Config from "../config";
import { logger } from "../modules/logger.module";

const MongoDBService = async () => {

    const config = Config();

    try {

        connectionString = `${config.mongo.uri}/steam?authSource=admin&replicaSet=rs0&retryWrites=true&w=majority`;
        
        await mongoose.connect(connectionString, config.mongo.options);
        logger.info({log_type: "db", status: "[MONGO CONNECTION]: Successfully Connected"});
    } catch (error) {
        logger.error({error: error, error_stack: error.stack});
        process.exit(1);
    }

    mongoose.connection.on("error", (err) => {
        logger.error({error: err, error_stack: err.stack});
        process.exit(1);
    });
};

export default MongoDBService;
```

```
    options: {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      useFindAndModify: false,
      autoIndex: true,
      poolSize: 10,
      serverSelectionTimeoutMS: 30000,
      socketTimeoutMS: 75000,
      family: 4,
      keepAlive: true,
      keepAliveInitialDelay: 300000
    }
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
nodejs: v12.18.3
mongoose: "^5.12.10"
mongodb: 4.4.5
```

**rs.status()**

```
rs.status()
{
	"set" : "rs0",
	"date" : ISODate("2021-05-19T09:09:02.785Z"),
	"myState" : 1,
	"term" : NumberLong(3),
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 2,
	"writeMajorityCount" : 1,
	"votingMembersCount" : 2,
	"writableVotingMembersCount" : 1,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1621415337, 1),
			"t" : NumberLong(3)
		},
		"lastCommittedWallTime" : ISODate("2021-05-19T09:08:57.738Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1621415337, 1),
			"t" : NumberLong(3)
		},
		"readConcernMajorityWallTime" : ISODate("2021-05-19T09:08:57.738Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1621415337, 1),
			"t" : NumberLong(3)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1621415337, 1),
			"t" : NumberLong(3)
		},
		"lastAppliedWallTime" : ISODate("2021-05-19T09:08:57.738Z"),
		"lastDurableWallTime" : ISODate("2021-05-19T09:08:57.738Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1621415277, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "electionTimeout",
		"lastElectionDate" : ISODate("2021-05-10T09:58:32.571Z"),
		"electionTerm" : NumberLong(3),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(1620640653, 1),
			"t" : NumberLong(2)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1620640653, 1),
			"t" : NumberLong(2)
		},
		"numVotesNeeded" : 2,
		"priorityAtElection" : 5,
		"electionTimeoutMillis" : NumberLong(10000),
		"numCatchUpOps" : NumberLong(0),
		"newTermStartDate" : ISODate("2021-05-10T09:58:32.576Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2021-05-10T09:58:32.676Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 774642,
			"optime" : {
				"ts" : Timestamp(1621415337, 1),
				"t" : NumberLong(3)
			},
			"optimeDate" : ISODate("2021-05-19T09:08:57Z"),
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1620640712, 1),
			"electionDate" : ISODate("2021-05-10T09:58:32Z"),
			"configVersion" : 2,
			"configTerm" : 3,
			"self" : true,
			"lastHeartbeatMessage" : ""
		},
		{
			"_id" : 1,
			"name" : "mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local:27017",
			"health" : 1,
			"state" : 7,
			"stateStr" : "ARBITER",
			"uptime" : 774641,
			"lastHeartbeat" : ISODate("2021-05-19T09:09:02.054Z"),
			"lastHeartbeatRecv" : ISODate("2021-05-19T09:09:02.416Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "",
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"configVersion" : 2,
			"configTerm" : 3
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1621415337, 1),
		"signature" : {
			"hash" : BinData(0,"P450DoJM0f2JmeeqychDmlOobqE="),
			"keyId" : NumberLong("6960597903123415044")
		}
	},
	"operationTime" : Timestamp(1621415337, 1)
}
```

**Comment by vkarpov15** [comment]
This looks like it is due to [replica set host names](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). Does your connection string include `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local` and `mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local`? If your connection string uses a different name for those mongodb servers and your app servers don't know how to resolve these domain names, that would explain this error.

**Comment by kaykhancheckpoint** [comment]
@vkarpov15 This is my connection string `mongo.acme.com/steam?authSource=admin&replicaSet=rs0&retryWrites=true&w=majority`

**Comment by vkarpov15** [comment]
@kaykhancheckpoint yep, the problem is that you're connecting to `mongo.acme.com` but replica set config thinks your MongoDB servers' FQDN is `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local`, etc. and `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local` is not accessible from your app server. Make sure you've configured your VM or docker container's `hostname`: https://mongoosejs.com/docs/connections.html#replicaset-hostnames

**Comment by kaykhancheckpoint** [comment]
@vkarpov15 Sorry for the late response. I have mongodb setup in kubernetes using the following helm chart. https://github.com/bitnami/charts/tree/master/bitnami/mongodb

Do you know which variable i need to set in this chart?

Just to confirm i need to set hostname variable to `mongo.acme.com` ?

**Comment by vkarpov15** [comment]
@kaykhancheckpoint I'm not familiar enough with helm to know. But try that and run `rs.status()` to confirm that the replica set status thinks the members are `mongo.acme.com`, not `*.mongodb.svc.cluster.local`.

**Comment by kaykhancheckpoint** [comment]
@vkarpov15 You can see the original post contains the output for rs.status() and it has no changed. So can i assume this is a setup issue and the `members[0].name` should be `mongo.acme.com` rather than the internal kubernetes address `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017`.

My problem is then this address was setup for me when installing the bitnami/mongodb helm chart into my kubernetes cluster.

**Comment by vkarpov15** [comment]
If you're unable to modify the replica set host names, your only workaround is to make sure that `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local` resolves correctly on your machine. One approach I've used in the past is adding `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local` to my `/etc/hosts` file locally.

**Comment by faisal-coder-313** [comment]
Make sure that you have added replica set nodes in the host machine in etc/hosts file. 
Just like the below example -

    127.0.0.1	mongoset1 mongoset2 mongoset3

Note - 127.0.0.1 is your host machine and mongoset1, mongoset2 and mongoset3 are the nodes (members) of the replicaset.
