### ISSUE TITLE
Error of depcreation

### ISSUE THREAD

**Issue by kakarot-dev** [Automattic/mongoose#10289]
**Do you want to request a *feature* or report a *bug*?** = bug

**What is the current behavior?** !https://cdn.discordapp.com/attachments/347816470589341706/846743623903215677/unknown.png

**If the current behavior is a bug, please provide the steps to reproduce.**
 If you can, provide a standalone script / gist to reproduce your issue.   = https://gist.github.com/kakarot-dev/253956e256d0d7d30ab7c99f915e48f7

If you are using TypeScript, please include your `tsconfig.json`  = https://gist.github.com/kakarot-dev/bbd3007f25425c46550b26624d1fce12

**What is the expected behavior?** = It shouldnt give this error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by kakarot-dev** [comment]
the things u think are undefined are actually defined in other section and there is no need to worry about that
the only probelm is findOneAndUpdate isnt working as excepted

**Comment by kakarot-dev** [comment]
is there any alternative to that

**Comment by IslandRhythms** [comment]
#10285

**Comment by fabraga** [comment]
Does this "Error of Deprecation" mean a deprecation warning that is actually not be taken seriously and so supposed to be ignored (because perhaps it is going to be fixed in a coming update)?

**Comment by kakarot-dev** [comment]
i dont think it is to be ignored

**Comment by fabraga** [comment]
> i dont think it is to be ignored

Then which are the steps to solve this?
