### ISSUE TITLE
Mongoose is reported vulnerable due to lodash.

### ISSUE THREAD

**Issue by arpitgupta2405** [Automattic/mongoose#10281]
**Do you want to request a *feature* or report a *bug*?**
It's a question.

**What is the current behavior?**
Lodash is a dependency of mongoose and recently lodash is reported to be vulnerable, click [here](https://npmjs.com/advisories/1673) to know more.

We are planning a mongoose upgrade so just wanted to know that when will this vulnerability get addressed and merged.
Just wanted a rough timeline, so that we can plan our upgrade accordingly.

Please note that the latest version as of now, i.e. v5.12.10, does not resolve this vulnerability.

**If the current behavior is a bug, please provide the steps to reproduce.**

NPM Audit is reporting mongoose as vulnerable.

**What is the expected behavior?**
The NPM Audit should not report the mongoose npm module as vulnerable.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS => v12.15.0
Mongoose => currently on v5.6.5 and now planning to upgrade.

**Comment by vkarpov15** [comment]
Which version of npm are you using? Mongoose doesn't use lodash, we only have a [couple of lodash submodules as `devDependencies`](https://github.com/Automattic/mongoose/blob/e090c5e3c4178ca8279ac9f4b34c9fb6d0673523/package.json#L54-L55) that we use to test integration with lodash.

**Comment by arpitgupta2405** [comment]
The npm version we use is v6.8.0
And below is the result of the audit log:

| High          │ Command Injection
│ Package       │ lodash
│ Dependency of │ mongoose
│ Path          │ mongoose > async > lodash
│ More info     │ [https://npmjs.com/advisories/1673](https://npmjs.com/advisories/1673)

**Comment by arpitgupta2405** [comment]
@vkarpov15 ,Gentle reminder.

**Comment by vkarpov15** [comment]
async is a devDependency, so this isn't a major concern. We'll get rid of async internally.
