### ISSUE TITLE
Efficient Alternative for .save() on existing Model.Document

### ISSUE THREAD

**Issue by meister03** [Automattic/mongoose#10284]
#### I am searching after a efficient solution for updating a document.

I heard about .updateOne() , but I feel unfamiliar to it, since I have to parseout the field, which should be updated and then parse out the values from the whole cached document.

.save() , saves all my work, but I am searching after a alternative, since the parallelsaveerror occurs, when I have many fast requests to save and I have to cache the document as a "mongoose document" , which uses a lot more ram.

Thx in advance!

**Version:**
  mongoose: ^5.10.2,
  nodejs:  v14.15.5
  mongodb: node driver on mongodb atlas

**Comment by vkarpov15** [comment]
See [updating documents in Mongoose](https://masteringjs.io/tutorials/mongoose/update) for a discussion of tradeoffs.

Can you please describe the use case you're trying to solve that's causing you to get a ParallelSaveError?

**Comment by meister03** [comment]
@vkarpov15 , I have a document with over 100 keys and mostly, I update the document cross over on all keys. Sometimes it is the first key, sometimes the middle one.
The problem on `updateOne` is, that I have to parseout all fields, which I want to update. 
`.save()` has the advantage, that I do not need to, parseout the fields to update, I can just run .save()

I need a caching solution. Since I have a very high traffic over 500 requests per second, in which many `.save` operations take place, so that the Parallel Error occurs.

**Comment by vkarpov15** [comment]
`updateOne()` is the way to go if you need the extra perf, because you don't have to load the document first.

**Comment by meister03** [comment]
But, I how can I know which fields to update?

**Comment by vkarpov15** [comment]
One option is to rely on Mongoose to diff using [`Document#getChanges()`](https://mongoosejs.com/docs/api/document.html#document_Document-getChanges).

```javascript
const doc = await Model.findOne({ _id: docId });
doc.set(updateObj);
const changes = doc.getChanges();
await Model.updateOne({ _id: docId }, changes);
```

**Comment by meister03** [comment]
> One option is to rely on Mongoose to diff using [`Document#getChanges()`](https://mongoosejs.com/docs/api/document.html#document_Document-getChanges).
> 
> ```js
> const doc = await Model.findOne({ _id: docId });
> doc.set(updateObj);
> const changes = doc.getChanges();
> await Model.updateOne({ _id: docId }, changes);
> ```

Thx, when I save the Promise updateOne in a variable, will I get a Mongoose Document back? , where I can do the Operation again?

and can version errors happen, I have some immutable fields...

**Comment by vkarpov15** [comment]
If you want a Mongoose document back, you should use [`findOneAndUpdate()`](https://mongoosejs.com/docs/tutorials/findoneandupdate.html) instead of `updateOne()`.

You won't get any version errors with `updateOne()` or `findOneAndUpdate()` unless you have your own versioning implementation.

**Comment by meister03** [comment]
okay last question ,does `findOneAndUpdate` uses more db ressources/ or other ressources than `updateOne()`?

**Comment by vkarpov15** [comment]
In terms of performance, `updateOne()` should be slightly faster than `findOneAndUpdate()`. But if you need to do a `findOne()` after `updateOne()`, you're likely better off just using `findOneAndUpdate()`.
