### ISSUE TITLE
Mongoose exchanges my documents' fields with null !  Help , Ignore null, undefined or any invalid value.

### ISSUE THREAD

**Issue by brightchip** [Automattic/mongoose#10294]
I could loss my data at any second. Why it automatically updates the existing fields to null ?

Sometime the object I use to update is not cleaned and something like this may happen
`posts.updateOne({ }, {
        $set: {
            views: null,
            pageId: undefined
        }
    })`   

The part of schema has this : `   views: {
        type: Number,
        integer: true,
        default: 0,
    },`

There's already an $unset which was used to delete field why would I still use $set to update field to null ? 

I tried add this in the beginning :
` mongoose.connect(
        process.env.DATABASE_URL, { useNewUrlParser: true, ignoreUndefined: true },`  

It seems ignored undefined but not for null. 
How can I make sure no null or invalid value in the database ?

**Comment by brightchip** [comment]
I have this problem now because I was using Meteor which never sets empty value to the document unless using $unset.
I want an plugin for delete all the invalid fields before update the documents

**Comment by vkarpov15** [comment]
Setting `views` to `null` is valid because `views` is not `required`.
