### ISSUE TITLE
Bug unauthorised to make the request

### ISSUE THREAD

**Issue by Human-bio** [Automattic/mongoose#10299]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I used mongoose and Graphql to send my queries to the database but for some reason it doesn't let me create documents. I have tried creating a new user with full admin privileges it hasn't worked I tried changing the default user password but it didn't work.
I rechecked my mongoose model no errors so what might be the problem.
FYI the problem arose with the `return (author.save())` and the database connects normally

## Author Model
    const mongoose = require('mongoose');
    const Schema = mongoose.Schema;
    
    const authorSchema = new Schema({
        name: String,
        age: Number
    });
    
    module.exports = mongoose.model('Author', authorSchema);

## schema.js

    const graphql = require('graphql');
    const Book = require('../models/book');
    const Author = require('../models/Author');
    const _ = require('lodash');
    
    const {
        GraphQLObjectType,
        GraphQLString,
        GraphQLSchema,
        GraphQLID,
        GraphQLInt,
        GraphQLList
    } = graphql;
    
    const BookType = new GraphQLObjectType({
        name: 'Book',
        fields: ( ) => ({
            id: { type: GraphQLID },
            name: { type: GraphQLString },
            genre: { type: GraphQLString },
            author: {
                type: AuthorType,
                resolve(parent, args){
                    //return _.find(authors, { id: parent.authorId });
                }
            }
        })
    });
    
    const AuthorType = new GraphQLObjectType({
        name: 'Author',
        fields: ( ) => ({
            id: { type: GraphQLID },
            name: { type: GraphQLString },
            age: { type: GraphQLInt },
            books: {
                type: new GraphQLList(BookType),
                resolve(parent, args){
                    //return _.filter(books, { authorId: parent.id });
                }
            }
        })
    });
    
    const RootQuery = new GraphQLObjectType({
        name: 'RootQueryType',
        fields: {
            book: {
                type: BookType,
                args: { id: { type: GraphQLID } },
                resolve(parent, args){
                    //return _.find(books, { id: args.id });
                }
            },
            author: {
                type: AuthorType,
                args: { id: { type: GraphQLID } },
                resolve(parent, args){
                    //return _.find(authors, { id: args.id });
                }
            },
            books: {
                type: new GraphQLList(BookType),
                resolve(parent, args){
                    //return books;
                }
            },
            authors: {
                type: new GraphQLList(AuthorType),
                resolve(parent, args){
                    //return authors;
                }
            }
        }
    });
    
    const Mutation = new GraphQLObjectType({
        name: 'Mutation',
        fields: {
            addAuthor: {
                type: AuthorType,
                args: {
                    name: { type: GraphQLString },
                    age: { type: GraphQLInt }
                },
                resolve(parent, args){
                    let author = new Author({
                        name: args.name,
                        age: args.age
                    });
                    return (author.save())
                }
            }
        }
    });
    
    module.exports = new GraphQLSchema({
        query: RootQuery,
        mutation: Mutation
    });

### error messeage

    (node:31482) MongoError: (Unauthorized) not authorized on admin to execute command { 
    insert: "authors", documents: [[{name gyfdgyiszukjfheusdzyih} {age 88} {_id 
    ObjectID("60af9c682215ea7afad86f4c")} {__v 0}]], ordered: false, writeConcern: { w:
    "majority" }
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongo atlas(latest probably)
mongoose: 5.0.9

**Comment by vkarpov15** [comment]
Do you have permission to write to the database? It also looks like you're connected to the admin db, you might want to try changing `mongodb+srv://my.atlas.url/admin` to `mongodb+srv://my.atlas.url/mydatabase`

**Comment by Human-bio** [comment]
sorry I deleted the project sorry
