### ISSUE TITLE
I get this error when using .findByIdAndUpdate

### ISSUE THREAD

**Issue by byacar** [Automattic/mongoose#10297]
(node:28) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.

**Comment by kakarot-dev** [comment]
#10285 and #10289

**Comment by byacar** [comment]
Even though I follow these procedures, the problem persists.

**Comment by byacar** [comment]
If updateOne is used instead of findByIdAndUpdate, the problem is fixed.
