### ISSUE TITLE
Maximum call stack size exceeded at toObject

### ISSUE THREAD

**Issue by Yash3011** [Automattic/mongoose#10304]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Throwing a error : 

```
RangeError: Maximum call stack size exceeded
    at toObject (/home/ubuntu/proj/node_modules/mongoose/lib/utils.js:421:37)
    at toObject (/home/ubuntu/proj/node_modules/mongoose/lib/utils.js:437:16)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Line that is throwing error :-

```
const users = await userModel.find({email: {$nin: emails}, orderId: orderId, code: null});
```

I am fetching users from find method.
Here, 
Emails is the array of emails.
And, orderId is the reference field in the user schema.
It's not a bug but some error in my code. I just want to know is it because of too many records in my Database or because I am not parsing the emails?

Typescript file :-
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../dist/server",
        "baseUrl": "",
        "module": "commonjs"
    }
}

**What is the expected behavior?**
To fetch to records using the find method but getting a range error from the file utils.js on line 437:16

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.6.3
mongoDB : 4.2
node : 12.0.2

**Comment by Yash3011** [comment]
@IslandRhythms @vkarpov15 @aheckmann Please help me out.

**Comment by Yash3011** [comment]
@IslandRhythms @vkarpov15 @aheckmann Please help me out.

**Comment by vkarpov15** [comment]
This is definitely not because of "too many records in my Database". However, without more information it's unlikely we'll be able to repro this. Can you create a standalone script that reproduces this issue?
