### ISSUE TITLE
testing ttl feature

### ISSUE THREAD

**Issue by bwgjoseph** [Automattic/mongoose#10307]
Hi,

I have the following setup for ttl

```js
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
    await mongoose.connect('mongodb://root:password@localhost:28017/issue_1234?authSource=admin', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
    });

    await mongoose.connection.dropDatabase();

    const schema = new Schema({
        name: String,
        expiresAt: {
        type: Date,
        expires: 0,
        }
    })

    const date = new Date();
    const timeToExpire = 5000; // ms

    const newDoc = {
        name: 'name',
        expiresAt: new Date(+date + timeToExpire)
    }

    const Model = mongoose.model('Test', schema);
    await Model.create(newDoc);

    // this works since I purposely sleep for 60sec
    await new Promise(resolve => setTimeout(resolve, 60000));

    // no data return
    console.log('Done', await Model.findOne(), new Date());
}
```

So I wanted to write some tests to verify this. I'm using `mocha + sinon`

```js
// I have something along this
it('should remove doc after doc expires', async () => {
    const date = new Date();
    const timeToExpire = 5000; // ms
    const clock = sinon.useFakeTimers(date);

    const newDoc = {
        name: 'name',
        expiresAt: new Date(+date + timeToExpire)
    }

    const Model = mongoose.model('Test', schema);
    await Model.create(newDoc);

    clock.tick(60000); // move 60sec ahead

    await Model.findOne(); // still returns data

    clock.restore();
});
```

But it doesn't seem to work. However, if I were to test it manually (eye-balling) the database document, it will disappear roughly after 1 min since MongoDB only runs roughly [every minute](https://docs.mongodb.com/manual/core/index-ttl/#timing-of-the-delete-operation). Not sure how am I supposed to test/verify for this.

I hope this is the correct place to ask this, but if not, let me know.

**Comment by IslandRhythms** [comment]
You could try using the [assertion library](https://nodejs.org/api/assert.html)

**Comment by bwgjoseph** [comment]
How does the assertion library help in this case? (not sure if I'm missing something obvious here)

The issue here is that even when the time ticks (move forward), the data still exist in the database where it should have been removed.

**Comment by IslandRhythms** [comment]
My mistake, I thought you were having trouble testing if it still existed after the tick.

**Comment by IslandRhythms** [comment]
Did you try changing `expiresAt` to [`expires`](https://mongoosejs.com/docs/api.html#schemadateoptions_SchemaDateOptions-expires)?

**Comment by bwgjoseph** [comment]
`expiresAt` is just the field name. If you look at my schema declaration, `expires` is set.

And yes, my issue is that after the tick, the documents still exist in the database where it shouldn't be.

**Comment by IslandRhythms** [comment]
So if I'm reading this correctly, running the first script will work normally but the second script is where the problem is created?

**Comment by bwgjoseph** [comment]
Yes, in the first script, I purposely sleep for 60secs then try to query for the document, and it was removed which is the correct behavior. 

But I couldn't be having my test (2nd script) to sleep for 60sec, so I'm trying to use `sinon` to tick the clock forward, and even though the clock does tick forward, the document still exists. However, If I were to wait in real-time for 60 seconds and look at the database, the document will be removed.

So I'm not sure what happens, hoping to find out.

**Comment by IslandRhythms** [comment]
what is the sinon package?

**Comment by IslandRhythms** [comment]
Also at first glance my guess would be that the clock isn't actually doing anything to the system clock which is why when you actually wait the minute it deletes the entry.

**Comment by sean-daley** [comment]
Just to comment here (reinforce what @IslandRhythms says above). The ttl settings are a feature of mongodb not mongoose. Mongoose just passes the indices to mongodb and it handles processing any ttl deletions. Since mongodb is running outside of your test process it will not be affected by any mocking or sinon library.

I’m not sure there is a good way you can really unit test this because you’d need to mock out mongodb as well and, at that point, you’re not testing the ttl feature. I think, generally, people will just try and verify that the indices are set correctly and that the mongodb folks properly test their ttl feature. I’d definitely be delighted if someone has a better solution though.

**Comment by bwgjoseph** [comment]
@IslandRhythms what does that solve? I tested it and it's not working, and it's the same as how I did in my first post.

> Since mongodb is running outside of your test process it will not be affected by any mocking or sinon library

I think this is exactly why it doesn't care about my clock ticking. I also would like to know if there's any better way to go about it

**Comment by IslandRhythms** [comment]
The script I provided isn't a solution, it's a confirmation of what is causing the problem.

**Comment by bwgjoseph** [comment]
I see. And do you also concur what @sean-daley mentioned `Since mongodb is running outside of your test process it will not be affected by any mocking or sinon library`?

In that case, then there's probably nothing much that can be done/test. I wonder how people test for it though.

**Comment by IslandRhythms** [comment]
I do agree, so you won't be able to test this unfortunately

**Comment by bwgjoseph** [comment]
Alright, thank you both!
