### ISSUE TITLE
Mongoose Connection Spike when using with Mongo DB Atlas 

### ISSUE THREAD

**Issue by Ayushk93** [Automattic/mongoose#10318]
Hi Team,

We are using Mongoose latest version with Mongo DB Atlas and Nest JS. We have tried below connection options for creating connection uri:
```
return {
      uri:
        process.env.MONGO_DB_URL +
        '?retryWrites=false&w=majority&authSource=admin&readPreference=primary',
      useNewUrlParser: true,
      poolSize: 3,
      socketTimeoutMS: 30000,
      autoReconnect: false,
      connectTimeoutMS: 5000,
      maxIdleTimeMS: 5000,
      minPoolSize: 1,
      maxPoolSize: 1,
      keepAlive: false,
      keepAliveInitialDelay: 3000,
    };
```
But our connection count is getting high with every request. Please help us, we have multi tenant architecture.

**Comment by IslandRhythms** [comment]
#10280

**Comment by vkarpov15** [comment]
Without a code sample that demonstrates the issue you're seeing, we won't be able to make any progress on this. Your connection options look fine, but without a repro script we won't be able to provide any advice.
