### ISSUE TITLE
syncIndexes dry-run option

### ISSUE THREAD

**Issue by clhuang** [Automattic/mongoose#10316]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
there is no way to see what syncIndexes will do without running it

**What is the expected behavior?**
would like to have a `dryRun: true` option that will not actually create/delete indexes but just show what changes would be made

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
I think we should implement this as a distinct `diffIndexes()` function that returns an object `{ toDrop, toCreate }` where `toDrop` and `toCreate` are arrays containing the indexes that will be dropped and the indexes that will be created. See: https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes
