### ISSUE TITLE
Issue with lean method when working with promises.

### ISSUE THREAD

**Issue by InnerPulse** [Automattic/mongoose#10327]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug.

**What is the current behavior?**

When findById is called inside a asynchronous function, if there is null and when lean is called
upon null, exeption is thrown. Not tested in synchronous functions but most likley it has nothing 
to do with the type of functions.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a pseudo code to reproduce the error: 

const getById = async (id) => {
  // Option 1
  const target = await collection.findById(id).lean();
  // lean throw exception if there is no result instead of a null as it does without lean method!

  // Option 2
  const target = await collection.findById(id);
  return target ? target.lean() : undefined;
  // Obviously here we will get: TypeError: target.lean is not a function
};

-----------------------------------------------------------------------------------------------------------
Suggestion: When there is null as a result. exprected behaviour would be to still receive null
even if lean method is called upon it.

**Comment by IslandRhythms** [comment]
So the difference between option 1 and option 2 is that in option 1 you save a mongoose document that was turned into a  POJO.
In options 2, you get a mongoose doc and then after call lean to attempt to turn it into a POJO which is not a valid use case.

**Comment by InnerPulse** [comment]
Hi, 

 I totally understand everything you've said but what I didn't mentioned was that if instead findById we use the find method and both have lean attached to them and at the same time the collection have no records, the find method returns empty array and the findById throw exeprion ..

**Comment by InnerPulse** [comment]
Feel free to delete this issue as it wasn't explained well, sorry for the inconvenience.
