### ISSUE TITLE
E11000 duplicate key error collection

### ISSUE THREAD

**Issue by YodaForce157** [Automattic/mongoose#10323]
**Do you want to request a *feature* or report a *bug*?**
I need help
**What is the current behavior?**
If i run +give @myfriendsname 1 it gives this error, it works on me but not him
**If the current behavior is a bug, please provide the steps to reproduce.**

```
module.exports = {
    name: 'give',
    async execute(message, args){
        const profileModel = require('../models/profileSchema')
        if(message.member.roles.cache.find(r => r.id === '679636794060308565')){
            const target = message.mentions.users.first();
            if(!target){
                message.channel.send('Please mention a user to give the points to!')
            } else {
            const pointsAmmount = parseInt(args[1])
            const profileData = await profileModel.findOne({ userID: target.id})
            if(!profileData){
                message.channel.send('Player does not have a profile!')
            } else {
            const currentPoints = profileData.points
            let profile = await profileModel.findOneAndUpdate({
                userID: target.id,
                points: currentPoints + pointsAmmount
              });
              try {profile.save()} 
              catch(err) {console.log(err)}
            }}
            } else {
                message.channel.send('You don\'t have permisson to use this command!')
            }
        }
    }
```

**What is the expected behavior?**
it gives him the amount of points
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
15.9.0, 5.12.12, 4.4.6

**Comment by IslandRhythms** [comment]
[This](https://masteringjs.io/tutorials/mongoose/e11000-duplicate-key) could help.
Duplicate key usually means that you're trying to create an entry with a duplicate id. From the code above, I don't think there is enough to go on cause I can't see where that error would be fired unless somehow there is already a duplicate in the database that somehow got by.

**Comment by YodaForce157** [comment]
i managed to fix it by changing the way it adds points but am now getting the same error with another piece of code similar to it, i have deleted everything in the db and it still gives the error (sorry for being a bit late)

**Comment by IslandRhythms** [comment]
Please include those other pieces of code, otherwise there isn't much we can do.

**Comment by YodaForce157** [comment]
this is the whole piece of code, it doesnt work on anyone
`module.exports = {
    name: 'refresh',
    async execute(message){
        const profileModel = require('../models/profileSchema')
        const user = message.author
        const member = message.member
        const vars = require('../variables')
        if(member.roles.cache.find(r => r.id === vars.SUPREME_ALIEN_COMMANDER)){
            let profile = await profileModel.findOneAndUpdate({
                userID: user,
                rank: 'Supreme Alien Commander'
            });
            profile.save();
            message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.JUNIOR_ALIEN_COMMANDER)){
            let profile = await profileModel.findOneAndUpdate({
                userID: user,
                rank: 'Junior Alien Commander'
            });
                profile.update();
                message.channel.send('Refreshed your profile!')
            } else if(member.roles.cache.find(r => r.id === vars.PROFFESSOR)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Proffessor'
                  });
                profile.update();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.ASSISTANT)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Assistant'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
            } else if(member.roles.cache.find(r => r.id === vars.ELITE_ALIEN)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Elite Alien'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.ALIEN_AGENT)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Alien Agent'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.FIRST_CLASS_AGENT)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'First class agent'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.SECOND_CLASS_AGENT)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Second class agent'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.THIRD_CLASS_AGENT)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Third class agent'
                  });
                profile.save();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.PRIVATE_ALIEN)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Private Alien'
                  });
                profile.update();
                message.channel.send('Refreshed your profile!')
        } else if(member.roles.cache.find(r => r.id === vars.ALIEN)){
                let profile = await profileModel.findOneAndUpdate({
                    userID: user,
                    rank: 'Alien'
                  });
                profile.update();
                message.channel.send('Refreshed your profile!')
        }
    }
}`

**Comment by IslandRhythms** [comment]
Please include the files that you are importing, we need to see the whole picture if we are going to help

**Comment by YodaForce157** [comment]
profileschema: `const mongoose = require('mongoose');

const profileSchema = new mongoose.Schema({
    userID: { type: String, require: true, unique: true},
    points: { type: Number, default: 0},
    rank: { type: String}
})

const model = mongoose.model('ProfileModels', profileSchema);

module.exports = model;`

**Comment by IslandRhythms** [comment]
From what I'm reading you're not actually updating anything.
https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate
You're only specifying the condition that it needs to find the document, so it will find the document and do nothing else.

**Comment by YodaForce157** [comment]
oh, its because it needs to be `const user = message.author.id` i think

**Comment by YodaForce157** [comment]
oh, maybe not

**Comment by YodaForce157** [comment]
hey, could you just give me an example of the code to replace my current piece with? i dont understand the docs very well

**Comment by IslandRhythms** [comment]
> oh, its because it needs to be const user = message.author.id

That might help because I don't remember what `message.author` stores.

so instead of doing
```
let profile = await profileModel.findOneAndUpdate({
                userID: user,
                rank: 'Supreme Alien Commander'
            });
```

Do

```
let profile = await profileModel.findOneAndUpdate({
                userID: user,
            }, {rank: 'Supreme Alien Commander'});
```

**Comment by YodaForce157** [comment]
ah yes, tysvm!!

**Comment by YodaForce157** [comment]
now the hard part, replacing it

**Comment by IslandRhythms** [comment]
GL

**Comment by MO-REDAxCT** [comment]
**Do you want to request a feature or report a bug?**
I want to report a bug 
**What is the current behavior?**
If I create a model using a schema and name it 'model1', and then I change the schema and try to create a new model also named 'model1', Mongoose doesn't throw any error indicating that there's already a model with the same name. Furthermore, if I attempt to add a document to the new collection associated with the second schema, the document will actually be added to the collection created by the first model. Consequently, if I don't adhere to the schema of the first model, Mongoose will throw an error indicating that the schema is not being respected. This can be challenging to debug because when inspecting the schema, it may appear that I am conforming to the new schema, but in reality, the document is being added to the collection associated with the first schema.
**If the current behavior is a bug, please provide the steps to reproduce.**

**Comment by vkarpov15** [comment]
@MO-REDAxCT can you please open a new issue and follow the issue template?
