### ISSUE TITLE
[Backwards compatibility] Dropping support for Node < v8

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10338]
I think v6.0 is a good opportunity to drop support for node versions that are less than v8.

The main reason I'd like to do that is to be able to use async/await in our codebase, I'd happily refactor the current code to use async/await and other modern features.

**Comment by ShadiestGoat** [comment]
Yeah I fully agree. There is basically no reason to keep on support for less than v8. Anything program that hasn't updated to v8 by now is most likely unmaintained

**Comment by vkarpov15** [comment]
I agree about dropping support for Node < 8.0.0. Now that Node.js 10 is EOL, we may even drop support for Node.js < 12.0.0 in 6.0. What do you think?

At the very least, dropping support for < 10 would make it easier to test [async iterators](https://thecodebarbarian.com/getting-started-with-async-iterators-in-node-js).

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 Dropping support for versions < 10 sounds good to me.

I'd avoid dropping support for versions unless we have a feature on mind that we'd like to use, so unless there's a specific version in node 12 that we'd like to use, I would support v10 still.

**Comment by vkarpov15** [comment]
I agree, we can plan on dropping support for < 10 since 10 is already EOL, but the extra friction of supporting Node 10 seems like it should be minimal.

**Comment by vkarpov15** [comment]
It looks like the MongoDB driver v4.0.0 only supports Node 12.x, so we'll drop support for Node 10 as well: https://github.com/mongodb/node-mongodb-native/blob/51ea86d0abfbe18a3ae0a5e41a6b8c5b974f3c3b/package.json#L98-L100. Mongoose can't support Node 10 if the MongoDB driver doesn't support Node 10.
