### ISSUE TITLE
Model.exists function does not accept options

### ISSUE THREAD

**Issue by Aminoiz** [Automattic/mongoose#10334]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
the exists function does not accept an options parameter

**What is the expected behavior?**
the exists function should accept an options parameter and pass is to the findOne function under the hood

**Comment by Aminoiz** [comment]
You can assign it to me, I can handle it

**Comment by IslandRhythms** [comment]
Its a mistake in the docs, it does accept an options parameter

**Comment by Aminoiz** [comment]
@IslandRhythms will it be fixed in the next version?

**Comment by IslandRhythms** [comment]
Go for it.
1. Make a separate Branch off main
2. go to model.js
3. go to Model.exists
4. in the comments above add the options parameter description
5. make a PR and link this to that

**Comment by Uzlopak** [comment]
Can this be closed?

**Comment by Aminoiz** [comment]
Yes
