### ISSUE TITLE
The string "{templateId}" is validated as a valid Object Id by the function isValidObjectId and ObjectId.isValid functions

### ISSUE THREAD

**Issue by nkemcels** [Automattic/mongoose#10330]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`mongoose.Types.ObjectId.isValid` or `mongoose.isValidObjectId` validates the input `"{templateId}"` as a valid Object Id which is very wrong.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Import the `isValidObjectId` or `Types` i.e. 
```js
import { isValidObjectId } from "mongoose"
```

2. Test the input `"{templateId}"` with the imported `isValidObjectId` utility and print the output i.e.
```js
const isValid = isValidObjectId("{templateId}");

console.log(isValid) // -> true
```

**What is the expected behavior?**
Should return **false** as `"{templateId}"` is not a valid object id.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: **12.14.1**
Mongoose: **5.10.4**
Mongodb: **4.6**

**Comment by Kamikadze4GAME** [comment]
Hello @nkemcels
This is not a bug. Please see [this question and answer](https://mongoosejs.com/docs/faq.html#objectid-validation)  from FAQ.
