### ISSUE TITLE
[Question] Is it possible to get real virtuals after calling toObject() or lean()?

### ISSUE THREAD

**Issue by Zombobot1** [Automattic/mongoose#10332]
Hello, I have a model with getters (and maybe some methods) and I would like to use both: the spread operator and virtuals. 

If I use __Model.findOne({}).exec()__ I get a document with getters an so on. However, in this case I cannot use spread operator. On the other hand, if I call __toObject({ virtuals: true })__ the getters in the document will not be functions anymore. I'm interested in getting objects with all properties and virtuals (not their values) which I specify in a schema and being able to use the spread operator. Is it possible?

**Comment by vkarpov15** [comment]
Try [mongoose-lean-virtuals](http://npmjs.com/package/mongoose-lean-virtuals) and [mongoose-lean-getters](https://www.npmjs.com/package/mongoose-lean-getters), that should help you get a lean document with virtuals and getters applied.

Can you please clarify whaty ou mean by "cannot use the spread operator"?

**Comment by Zombobot1** [comment]
I want to make shallow copies of objects using the spread operator. However, if I apply it to a mongoose document I copy a lot of meta information and cannot access my properties anymore. This is a short example:

```ts
await KittenModel.create({ name: 'fluffy', toy: { name: 'ball' } });
const fluffy = await KittenModel.findOne({ name: 'fluffy' }).exec();
if (!fluffy) throw new Error('404');
console.log(fluffy.name); // fluffy
console.log({...fluffy}.name); // undefined
```

I tried mongoose-lean-virtuals but it includes values of virtuals not real functions: 
```ts
await KittenModel.create({ name: 'fluffy', toy: { name: 'ball' } });
const fluffy = await KittenModel.findOne({ name: 'fluffy' }).lean({ virtuals: true });
if (!fluffy) throw new Error('404');
fluffy.toy.name = 'string'
// description is a getter which returns "Nice + toy's name"
console.log(fluffy.toy.description); // prints "Nice ball" instead of "Nice string"
```

**Comment by vkarpov15** [comment]
Hmm in that case why are you making shallow copies of documents using the spread operator? That's not a pattern that is typically useful when working with Mongoose.

**Comment by Zombobot1** [comment]
Now I see that my requirements contradict to each other. Thank you for clarification.
