### ISSUE TITLE
FindById method combined with lean method, throw an exception with no records in given collection.

### ISSUE THREAD

**Issue by InnerPulse** [Automattic/mongoose#10331]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug.

**What is the current behavior?**

When findById is called inside an asynchronous function combined with the lean method, if there are no records in the collection, exeption is thrown, while if it's used the find method combined with lean we don't have the same behaviour but instead we receive and empty array as expected. 

Not tested in synchronous functions but most likely it has nothing 
to do with the type of functions.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a pseudo code to reproduce the error: 

const getById = async (id) => {
  const target = await collection.findById(id).lean();
  // lean throw exception if there is no result instead of a null or any falsy value as it does without lean method!

We don't observe the same behaviour with the find method istead of findById with the exact same circumstances!
};

-----------------------------------------------------------------------------------------------------------
Suggestion:

 When there is null as a result from findById, exprected behaviour would be to still receive null
even if lean method is called upon it so I would suggest to be made to return null or any other falsy value but to don't throw an exception.

**Comment by IslandRhythms** [comment]
```

const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    name: String,
    age: Number,
    weight: Number,
    sex: String,
    height: Number
})
testSchema.index({name: 1, age: 2, weight: 3, sex: 4, height: 5});
const Test = mongoose.model('Test', testSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
    
    await mongoose.connection.dropDatabase();

    await mongoose.connection.db.createCollection("test", {validator: {
        $jsonSchema: {
          bsonType: "object",
          properties: {
            name: {
              bsonType: "string",
              description: "must be a string and is required"
            }
          }
        }
      }});

    console.log('list collection', mongoose.connection.db.listCollections());
    await mongoose.connection.collection('test').find({}).lean();
    console.log('past find')
    await mongoose.connection.collection('test').findById({}).lean();
}

test();
```
it throws an exception for find as well

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    name: String,
    age: Number,
    weight: Number,
    sex: String,
    height: Number
})
testSchema.index({name: 1, age: 2, weight: 3, sex: 4, height: 5});
const Test = mongoose.model('Test', testSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
    
    await mongoose.connection.dropDatabase();

   await Test.create();

    const find = await Test.find().lean();
    console.log('past find', find);
    const byId = await Test.findById().lean();
    console.log('byId', byId);
}

test();
```

**Comment by IslandRhythms** [comment]
If you're using a collection, find and findById are not functions. Running on models, find returned an empty array as it should and findById returned null
