### ISSUE TITLE
Mongoose find query not returning the timestamp fields (createdAt, updatedAt)

### ISSUE THREAD

**Issue by apank** [Automattic/mongoose#10337]
Mongoose version - 5.12.13

Schema
`
const userSchema = mongoose.Schema({
  firstname: {
    type: String,
  },
  lastname: {
    type: String,
  },
}, {
  timestamps: true,
});
`

`const users = await User.find().exec();
`

Expected Output
`{
  "firstName": "John",
  "lastName": "Doe",
  "createdAt": "2021-06-07T01:28:37.039+00:00"
}`

Actual Output
`{
  "firstName": "John",
  "lastName": "Doe",
}`

When I use the native mongodb driver it returns the createdAt field; when I use the mongoose driver it omits the createdAt field no matter what. I also have tried the following - 

`const users = await User.find({}, {"createdAt": -1}).exec();
`
and

`const users = await User.find().select("createdAt").exec();
`

**Comment by indraraj26** [comment]
Hi Apank,

I have tested and getting expected output. 

Could you please use below script to reproduce it.
"mongoose": "^5.12.13",

```
const mongoose = require('mongoose');

const userSchema = mongoose.Schema({ firstname: { type: String, }, lastname: { type: String, }, }, { timestamps: true, });


run().catch((err) => console.log(err));

async function run() {
	await mongoose.connect('mongodb://localhost:27017/test', {
		useNewUrlParser: true,
		useUnifiedTopology: true,
	});
	await mongoose.connection.dropDatabase();

	const UserModel = mongoose.model('user', userSchema);
	const user = new UserModel({firstname: "abc", lastname: "xyz"});
    await user.save();
    const users = await UserModel.find().exec();
    console.log(users)
}

```

output
```
[ { _id: 60c059640c9bb612b4a96d49,
    firstname: 'abc',
    lastname: 'xyz',
    createdAt: 2021-06-09T06:02:12.712Z,
    updatedAt: 2021-06-09T06:02:12.712Z,
    __v: 0 } ]

```

**Comment by vkarpov15** [comment]
@indraraj26 your output shows there is a `createdAt` field, but your bug report says that Mongoose omits the `createdAt` field. Can you please clarify what the actual issue is?

**Comment by indraraj26** [comment]
Hi @vkarpov15 , It is not reported by me. I have added the script for him to reproduce it for us.

**Comment by SaqibSattar** [comment]
Mongoose version - 8.3.2

User Schema
const userSchema = mongoose.Schema({ username: { type: String, }, email: { type: String, }, }, { timestamps: true, });

const users = await User.find(); 

// expected output
{ 
  "username": "admin", 
  "email": "john32@gmail.com", 
  "createdAt": "2024-04-25T12:42:12.12.417+00:00" 
}

// actual output
{ 
  "username": "admin", 
  "email": "john32@gmail.com"
 }

**Comment by vkarpov15** [comment]
@SaqibSattar does the document in the database have a createdAt property?

**Comment by SaqibSattar** [comment]
I don't have custom properties for createdAt and updatedAt. Instead, I'm utilizing { timestamps: true }, which automatically generates these fields

**Comment by vkarpov15** [comment]
That's not what I was asking. I know you have `timestamps` option set in your schema. I'm just asking if the document in MongoDB has timestamps or not? Try executing a query with `lean()` to see if the document in the database has timestamps set.

**Comment by thehexatown-moiz-arif** [comment]
> That's not what I was asking. I know you have `timestamps` option set in your schema. I'm just asking if the document in MongoDB has timestamps or not? Try executing a query with `lean()` to see if the document in the database has timestamps set.

Yes the document in MongoDB has the timestamps but still not coming in result with .find

**Comment by vkarpov15** [comment]
Oh I think I know what the issue is, `2024-04-25T12:42:12.12.417+00:00` isn't a valid date string in JavaScript. Since `timestamps` makes `createdAt` into a Date by default, invalid dates won't show up.

Add `createdAt: String` to your schema definition as follows, and this should be fixed.

```javascript
const userSchema = mongoose.Schema({ username: { type: String, }, email: { type: String, }, createdAt: String }, { timestamps: true, });
```
