### ISSUE TITLE
Sporadic Cannot read property 'call' of undefined in helpers/document/compile.js

### ISSUE THREAD

**Issue by dan-cooke** [Automattic/mongoose#10342]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It is very hard to describe exactly, because I am using quite a complex stack. But in abstract terms - when I perform an `updateById` on a document via my frontend.

I receive the following error:

```
[GraphQLError [Object]: Cannot read property 'call' of undefined] {
  locations: [ { line: 11, column: 9 } ],
  path: [ 'updatePortfolio', 'record', 'details', 'name' ],
  extensions: { code: 'INTERNAL_SERVER_ERROR', exception: { stacktrace: [Array] } }
}

```

The problematic line it is reffering to is in `helpers/document/compile.js` Line 172

```javascript
  Object.defineProperty(prototype, prop, {
      enumerable: true,
      configurable: true,
      get: function() {
        console.log('this',this);
        console.log('getSymbol',getSymbol);
        // This call is failing because this[getSymbol] is undefined
        return this[getSymbol].call(this.$__[scopeSymbol] || this, path);
      },
      set: function(v) {
        this.$set.call(this.$__[scopeSymbol] || this, path, v);
      }
    });
```

I'm fairly convinced the issue is with my frontend, as this error does not happen when I cal my GraphQL API directly from CLI or GraphQL Playground.

Note: I have `console.log` before the failing line. When hitting the problem lines via my API directly the log looks identical to the logs that cause the error via the frontend - which is strange to me.

**If the current behavior is a bug, please provide the steps to reproduce.**
I cannot provide reproduction steps unfortunately, my codebase is quite convoluted and no doubt a reproduction repo would not encounter the issue.

Alternatively it could be something to do with rapid requests through mongoose. Here is what my frontend does when it errors

1. GraphQL request to `getUsersPortfolios`
2. If the user does not have an existing portfolio GraphQL request to `createPortfolio` 
**No Error at this point**

3. Refresh the page
4. GraphQL request to `getUsersPortfolios`
5. Now the user has a portfolio - `updatePortfolio` with any details they edit
**This is when i encounter the error**

**tsconfig.json**
```
{
  "compilerOptions": {
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "esModuleInterop": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "build",
    "target": "es6"
  },
  "exclude": ["node_modules"],
  "include": ["src"]
}

```

**What is the expected behavior?**
No error 😂 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v15.11.0
Mongoose: v5.12.13
MongoDB (with Atlas): 4.4.6

**Comment by IslandRhythms** [comment]
It 's gonna be hard to repro this without a script. Could you please try and provide a repro script?

**Comment by vkarpov15** [comment]
A stack trace would also be helpful

**Comment by dan-cooke** [comment]
Apologies guys. I forgot to include the stack trace.

I agree that this problem will be hard to debug without repro.

I solved my issue. I think it was due to including another ts project via my tsconfig. 

Going to close this one as i don't think it's related to mongoose.
