### ISSUE TITLE
bug: Not inferring Native error

### ISSUE THREAD

**Issue by Himadu2000** [Automattic/mongoose#10340]
**What is the current behavior?**
error TS7006: Parameter 'error' implicitly has an 'any' type.

**steps to reproduce.**
[Repo to recreate](https://github.com/Himadu2000/Recreating-mon-nat-err)
Run `yarn compile`

[Following action](https://github.com/Himadu2000/Recreating-mon-nat-err/runs/2786133255?check_suite_focus=true)

Quick code
`Cat.find({}, (error) => {
  if (error) {
    return error;
  }
});
`
compile with `tsc --strict`

**What is the expected behavior?**
Should infer NativeError in error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v14.17.0
"mongoose": "^5.12.13"

**Comment by Himadu2000** [comment]
I just noticed that mongoose is written .js not in .ts, this is one of major reasons I think I have to file an issue like mine, may I know when this library being written in typescript?

**Comment by IslandRhythms** [comment]
It already has a typescript support
https://mongoosejs.com/docs/typescript.html

**Comment by IslandRhythms** [comment]
```
import * as mongoose from "mongoose";

interface User{
    name: string;
}

const schema = new mongoose.Schema<User>({name: String});

mongoose.connect("mongodb://localhost:27017/test", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const Cat = mongoose.model("Cat", schema);

const kitty = new Cat({ name: "Zildjian" });
kitty.save().then(() => console.log("meow"));

Cat.find({}, (error) => {
  if (error) {
    return error;
  }
});
```

**Comment by vkarpov15** [comment]
@Himadu2000 below code compiles without error, please modify the below script to demonstrate your issue.

```typescript

import * as mongoose from "mongoose";

mongoose.connect("mongodb://localhost:27017/test", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const Cat = mongoose.model("Cat", new mongoose.Schema({ name: String }));

const kitty = new Cat({ name: "Zildjian" });
kitty.save().then(() => console.log("meow"));

Cat.find({}, (error) => {
  if (error) {
    return error;
  }
});

```

**Comment by Himadu2000** [comment]
@vkarpov15 Okay, [here's a example line where problem lies](https://github.com/Automattic/mongoose/blob/f676487d9863c4b0b561ce1bdfe8775603d5b9cf/index.d.ts#L833) , in the line `
callback?: (err: any, 
` the err is type of any, so it needs to be either string or different type which I am not sure what return.

**Comment by Himadu2000** [comment]
So @vkarpov15, what does err returns, I never got err but it needs to known to handle them, I can't take chances for unhandled errors on production app.
