### ISSUE TITLE
RefPath: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by huzaifa-99** [Automattic/mongoose#10347]
Mongodb version = ^4.4.4
Mongoose Version = ^5.11.18

I want to use ref on a field dynamically. For that I am using mongoose [refPath](https://mongoosejs.com/docs/populate.html#dynamic-ref).
Below is a part of my mongoose schema where I am handling this
```
mongoose.Schema({
  paid: {
    type: Boolean,
    required: true,
  },
  payRequest: {
    for: {
      type: String,
      enum: ['Event', 'Subscription'],
      required: true,
    },
    object: {
      type: mongoose.SchemaTypes.ObjectId,
      refPath: 'for', // also tried payRequest.for
      required: true,
    },
  },
});
```
Problem: When I save a new object for this schema I get this Error
```
validation failed: payRequest.object: Schema hasn't been registered for model \"undefined\".\nUse mongoose.model(name, schema)
```
Notes: 
- My schema works perfectly If I don't use refPath 
- If I use `refPath: 'payRequest'` then I get this error `Schema hasn't been registered for model \"{ for: 'Event', object: 60c4fee54cac2d311c1a5506 }` but I cannot access `refPath: 'payRequest.for'`

Hope to get this resolved soon. 🙂

**Comment by IslandRhythms** [comment]
Please include, if you can, the full script where you create your models.

**Comment by Kamikadze4GAME** [comment]
Hi @huzaifa-99 
Try to change

```js
mongoose.SchemaTypes.ObjectId
```

with

```js
mongoose.Schema.Types.ObjectId
```
