### ISSUE TITLE
LeanDocument contain id field

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#10345]
**Do you want to request a *feature* or report a *bug*?**

Issue #10282 continued

**bug**

**What is the current behavior?**

LeanDocument contain `.id` field

**If the current behavior is a bug, please provide the steps to reproduce.**

1. npm init -y
2. npm i mongoose @types/node
3. Create a user model (https://gist.github.com/tbhaxor/1deb83bb4d8a962f7959a3ac41487cd9)
4. Import typings (https://gist.github.com/tbhaxor/367e33692470c26cab5fec5cef749d91)
5. Import user model in another file and lean document `User.findOne().lean()`

![Screenshot_20210612_163817](https://user-images.githubusercontent.com/28386721/121773890-99c39300-cb9c-11eb-93c4-667b6b754e91.png)

**What is the expected behavior?**

Id should not exits

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.12.13

_This problem is with mongoose typescript, mongodb and node version are not required_

**Comment by IslandRhythms** [comment]
From the closed issue:
> 
> 
> I looked into this a bit more and there isn't much we can do about this. The reason is that your document can have a user-defined `id` type, and there's no way for `LeanDocument` to conditionally strip out `id` only if `id` is inherited from `Document` as opposed to user-defined.
> 
> This is one of the reasons why our [TypeScript docs](https://mongoosejs.com/docs/typescript.html) recommend not using `extends Document`:
> 
> ```ts
> // We recommend replacing this:
> interface Store extends Document { ... }
> 
> // With this:
> interface Store { ... }
> ```
> 
> Makes it much easier for Mongoose to infer the correct type when using `lean()`.

**Comment by tbhaxor** [comment]
@IslandRhythms I know typescript for a long time. I am not using a document that is why I reopened this

Please give me the mongoose typescript repo details. I will open a pull request for the fix, in case your team didn't manage to fix this issue earlier

**Comment by tbhaxor** [comment]
@IslandRhythms I am not using Document

**Comment by tbhaxor** [comment]
@IslandRhythms @vkarpov15 Yours typings are not working. Please check this ~3 mins video

https://www.loom.com/share/9b90007366fb4fc49c8f9843e1db4b02

**Comment by vkarpov15** [comment]
01c25ee improves this behavior for `toObject()` and `toJSON()`, we'll see what we can do for `lean()`
