### ISSUE TITLE
Is it possible to attach async methods to a schema within an async plugin?

### ISSUE THREAD

**Issue by lethalbrains** [Automattic/mongoose#10348]
While attaching an async plugin, is it possible to add methods to the schema? 

    const anotherModel = require(__dirname + "/anotherModel.js")
    const mongoose = require("mongoose")
    
    let injectPlugin = async (schema, options) => {
	    const anotherObject = await anotherModel.findOne({name: options['anotherModelName'] }).lean();
	    schema.methods.testfunction = async () => {
		    console.log(anotherObject)
	    }
    }
    
    module.exports = injectPlugin

In the sample snippet shown above, I am trying to initialize and load another model and use the data for subsequent operations within the plugin. 

Since it is an async method, the plugin is loaded before the promise is executed and I get an error 

    TypeError: sampleEntity.testfunction is not a function

So is it possible to attach async methods to the schema within an async plugin? 

I am currently using  **v5.12.13**

**Comment by vkarpov15** [comment]
It is possible, but not recommended for a couple of reasons:

1) Mongoose plugins are assumed to be synchronous functions, so Mongoose doesn't wait for async functions to finish running.

2) In general, we don't support modifying a schema after it has been compiled into a model. So if you've already created a model from `schema`, adding a method to `schema` after the fact may not apply to that model.
