### ISSUE TITLE
Can not use id() method to find subdocuments with TypeScript

### ISSUE THREAD

**Issue by mbacalan** [Automattic/mongoose#10344]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have 2 interfaces and corresponding schemas such as;

```ts
export interface IGiveaway {
  _id: string,
  userId: string,
  userTag: string,
  entries: IUser[]
}

export interface IGuild {
  _id: string,
  config: IConfig,
  giveaways: IGiveaway[],
}
```

So the giveaway schema is used as a subdocument of the guild schema.

```ts
const guildSchema = new Schema<IGuild>({
  _id: {
    type: String,
    required: true,
  },
  config: {
    type: configSchema,
    default: () => ({}),
  },
  giveaways: {
    type: [giveawaySchema],
    required: false,
  },
});

export const Guilds = model<IGuild>("guild", guildSchema);
```

But when I try to find a document inside `guild.giveaways` via the `id()` method, TypeScript gives an error.

```ts
const giveaway = await guild.giveaways.id(_id);
// Property 'id' does not exist on type 'IGiveaway[]'. ts(2339)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "./build",
    "allowJs": true,
    "target": "es5",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "downlevelIteration": true
  },
  "include": ["./src/**/*"]
}
```
**What is the expected behavior?**

I should be able to use the `.id()` method, [as it is shown in docs](https://mongoosejs.com/docs/subdocs.html#finding-a-subdocument).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v14.15.0
Mongoose v5.12.13
MongoDB v4.4.6

**Comment by thiagokisaki** [comment]
Try this:
```typescript
import { Document, Types } from 'mongoose';

export interface IGiveaway {
  _id: string,
  userId: string,
  userTag: string,
  entries: IUser[]
}

export interface IGuild {
  _id: string,
  config: IConfig,
  giveaways: Types.DocumentArray<IGiveaway & Document>,
}
```

**Comment by mbacalan** [comment]
@thiagokisaki thanks, that worked. I looked at the docs and searched online in general but couldn't find anything related to this. Perhaps it would be helpful to have this pointer in the docs about Mongoose and TypeScript
