### ISSUE TITLE
TypeScript: user-specified query options for plugins

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#10356]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

See https://github.com/Automattic/mongoose/issues/7304#issuecomment-859548751 . If a user writes a plugin that requires specifying a query option:

```typescript
Model.findOneAndUpdate({}, { isDeleted: false }, { includeSoftDeleted: false });
```

It would be hard to get this option from middleware:

```typescript
    // Property 'includeSoftDeleted' does not exist on type 'QueryOptions'. How to make it available ?
    const { includeSoftDeleted } = this.getOptions();
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by hasezoey** [comment]
This issue seems to be solved since #11852 (mongoose 6.3.5)

see https://github.com/Automattic/mongoose/blob/b1d99d64df7559c43628c8ad94726c3b3f3616cd/types/query.d.ts#L169
