### ISSUE TITLE
[Feature] Document#validate(...)  `pathsToSkip` option to exclude fields

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10353]
Currently, we can make an inclusive list of fields that we want to validate using `pathsToValidate`.

It would be nice if we could have an option to skip specific fields `pathsToSkip`, and a user can either select fields to skip, or fields to validate, never both.

@vkarpov15 What do you think? I'd happily work on that if accepted.

**Comment by IslandRhythms** [comment]
I believe that has been merged already.
https://github.com/Automattic/mongoose/pull/10276

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez please feel free to work on this and put in a PR against the 5.13 branch :+1:
