### ISSUE TITLE
findOne not working 

### ISSUE THREAD

**Issue by ketanpatel25** [Automattic/mongoose#10374]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by ketanpatel25** [comment]
Hello .....

  i am using in nodejs project in  "mongoose": "^5.12.14",
  
 in side data save are working find but find Object not work 

  const checkEmail =  User.findOne({email: row.email});

**Comment by ketanpatel25** [comment]
```
Query {
  _mongooseOptions: {},
  _transforms: [],
  _hooks: Kareem { _pres: Map {}, _posts: Map {} },
  _executionCount: 0,
  mongooseCollection:
   NativeCollection {
     collection: Collection { s: [Object] },
     Promise: [Function: Promise],
     modelName: 'User',
     _closed: false,
     opts:
      { autoIndex: true,
        autoCreate: undefined,
        schemaUserProvidedOptions: {},
        capped: false,
        Promise: [Function: Promise],
        '$wasForceClosed': undefined },
     name: 'users',
     collectionName: 'users',
     conn:
      NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object],
        _readyState: 1,
        _closeCalled: undefined,
        _hasOpened: true,
        plugins: [],
        id: 0,
        _queue: [],
        _listening: false,
        _connectionString:
         'mongodb://qudos:Xpert2021SIT@18.134.136.178:27011/qudos_dev?authSource=admin',
        _connectionOptions: [Object],
        name: 'qudos_dev',
        host: '18.134.136.178',
        port: 27011,
        user: 'qudos',
        pass: 'Xpert2021SIT',
        client: [MongoClient],
        '$initialConnection': [Promise],
        db: [Db] },
     queue: [],
     buffer: false,
     emitter:
      EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  model: Model { User },
  schema:
   Schema {
     obj:
      { first_name: [Object],
        last_name: [Object],
        email: [Object],
        user_type: [Object],
        password: [Object],
        team_name: [Object],
        company_name: [Object],
        created_admin: [Object],
        created_date: [Object],
        user_image_path: [Object],
        updated_date: [Object],
        user_active_status: [Object] },
     paths:
      { first_name: [SchemaString],
        last_name: [SchemaString],
        email: [SchemaString],
        user_type: [SchemaString],
        password: [SchemaString],
        team_name: [SchemaString],
        company_name: [SchemaString],
        created_admin: [SchemaString],
        created_date: [SchemaDate],
        user_image_path: [SchemaString],
        updated_date: [SchemaDate],
        user_active_status: [SchemaBoolean],
        _id: [ObjectId],
        __v: [SchemaNumber] },
     aliases: {},
     subpaths: {},
     virtuals: { id: [VirtualType] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [],
     _indexes: [],
     methods: {},
     methodOptions: {},
     statics: {},
     tree:
      { first_name: [Object],
        last_name: [Object],
        email: [Object],
        user_type: [Object],
        password: [Object],
        team_name: [Object],
        company_name: [Object],
        created_admin: [Object],
        created_date: [Object],
        user_image_path: [Object],
        updated_date: [Object],
        user_active_status: [Object],
        _id: [Object],
        __v: [Function: Number],
        id: [VirtualType] },
     query: {},
     childSchemas: [],
     plugins:
      [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     '$id': 1,
     mapPaths: [],
     s: { hooks: [Kareem] },
     _userProvidedOptions: {},
     options:
      { typePojoToMixed: true,
        typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        optimisticConcurrency: false,
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strictQuery: false,
        strict: true,
        pluralization: true },
     '$globalPluginsApplied': true },
  op: 'find',
  options: {},
  _conditions: {},
  _fields: undefined,
  _update: undefined,
  _path: undefined,
  _distinct: undefined,
  _collection:
   NodeCollection {
     collection:
      NativeCollection {
        collection: [Collection],
        Promise: [Function: Promise],
        modelName: 'User',
        _closed: false,
        opts: [Object],
        name: 'users',
        collectionName: 'users',
        conn: [NativeConnection],
        queue: [],
        buffer: false,
        emitter: [EventEmitter] },
     collectionName: 'users' },
  _traceFunction: undefined,
  '$useProjection': true }``
```

**Comment by ketanpatel25** [comment]
Query {
  _mongooseOptions: {},
  _transforms: [],
  _hooks: Kareem { _pres: Map {}, _posts: Map {} },
  _executionCount: 0,
  mongooseCollection:
   NativeCollection {
     collection: Collection { s: [Object] },
     Promise: [Function: Promise],
     modelName: 'User',
     _closed: false,
     opts:
      { autoIndex: true,
        autoCreate: undefined,
        schemaUserProvidedOptions: {},
        capped: false,
        Promise: [Function: Promise],
        '$wasForceClosed': undefined },
     name: 'users',
     collectionName: 'users',
     conn:
      NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object],
        _readyState: 1,
        _closeCalled: undefined,
        _hasOpened: true,
        plugins: [],
        id: 0,
        _queue: [],
        _listening: false,
        _connectionString:
        ................
        client: [MongoClient],
        '$initialConnection': [Promise],
        db: [Db] },
     queue: [],
     buffer: false,
     emitter:
      EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  model: Model { User },
  schema:
   Schema {
     obj:
      { first_name: [Object],
        last_name: [Object],
        email: [Object],
        user_type: [Object],
        password: [Object],
        team_name: [Object],
        company_name: [Object],
        created_admin: [Object],
        created_date: [Object],
        user_image_path: [Object],
        updated_date: [Object],
        user_active_status: [Object] },
     paths:
      { first_name: [SchemaString],
        last_name: [SchemaString],
        email: [SchemaString],
        user_type: [SchemaString],
        password: [SchemaString],
        team_name: [SchemaString],
        company_name: [SchemaString],
        created_admin: [SchemaString],
        created_date: [SchemaDate],
        user_image_path: [SchemaString],
        updated_date: [SchemaDate],
        user_active_status: [SchemaBoolean],
        _id: [ObjectId],
        __v: [SchemaNumber] },
     aliases: {},
     subpaths: {},
     virtuals: { id: [VirtualType] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [],
     _indexes: [],
     methods: {},
     methodOptions: {},
     statics: {},
     tree:
      { first_name: [Object],
        last_name: [Object],
        email: [Object],
        user_type: [Object],
        password: [Object],
        team_name: [Object],
        company_name: [Object],
        created_admin: [Object],
        created_date: [Object],
        user_image_path: [Object],
        updated_date: [Object],
        user_active_status: [Object],
        _id: [Object],
        __v: [Function: Number],
        id: [VirtualType] },
     query: {},
     childSchemas: [],
     plugins:
      [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     '$id': 1,
     mapPaths: [],
     s: { hooks: [Kareem] },
     _userProvidedOptions: {},
     options:
      { typePojoToMixed: true,
        typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: true,
        discriminatorKey: '__t',
        optimisticConcurrency: false,
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strictQuery: false,
        strict: true,
        pluralization: true },
     '$globalPluginsApplied': true },
  op: 'find',
  options: {},
  _conditions: {},
  _fields: undefined,
  _update: undefined,
  _path: undefined,
  _distinct: undefined,
  _collection:
   NodeCollection {
     collection:
      NativeCollection {
        collection: [Collection],
        Promise: [Function: Promise],
        modelName: 'User',
        _closed: false,
        opts: [Object],
        name: 'users',
        collectionName: 'users',
        conn: [NativeConnection],
        queue: [],
        buffer: false,
        emitter: [EventEmitter] },
     collectionName: 'users' },
  _traceFunction: undefined,
  '$useProjection': true }``

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @ketanpatel25

Following the issue template is the most efficient way to provide people trying to help with the information they need in order to help you solve your problem, so please follow the issue template the next time.

You need to use `await` in order to get the result you're looking for.
Instead of:
```js
const checkEmail =  User.find();
```
Try
```js
const checkEmail =  await User.find();
```
