### ISSUE TITLE
Is it possible to declare a nested sub-schema but with variable properties (like type Mixed)?

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#10383]
**Do you want to request a *feature* or report a *bug*?**
Question / feature request

We can create a mixed type to create an object property on a schema, but there doesn't seem to be a way to define a mixed sub schema (with it's own toJSON or pre-save handlers for example)

For example, we currently have a `customFields` property defined on our user model as follows:

```
customFields: {
    type: {},
    default: {},
},
```

This exists to capture custom user data which can differ from tenant to tenant. Hence why it is defined as a mixed type, because the keys/properties of the schema will depend on how the custom fields are called. So it's very much a fluid schema.

Now however, I'd like to turn this into a proper Mongoose schema, so that we can apply some pre-save hooks and other handling, e.g. something like:

```
customFields: {
    type: CustomFieldsSchema,
    default: {},
},
```

However, I get stuck at creating the schema, because essentially I have nothing to put in it, as the fields are unknown in advance and will vary for each tenant.

```
const CustomFieldsSchema = new Schema({
 //Unknown
})
```

But if I don't define any properties, the custom field data won't save, because those properties won't exist on the schema.

So the question/feature request is: can we have a schema which allows for mixed properties to be saved on it?

**Comment by IslandRhythms** [comment]
It sounds like you are trying to create a unique schema for every user. Is there no overlap?

**Comment by adamreisnz** [comment]
No, no overlap, because each tenant _creates_ their own custom fields, and decides on their names, which in turn is converted into a property key.

Example:

Tenant 1 defines two custom fields called "Caregiver" and "Emergency contact"
We then store this data on the `customFields` object as `customFields.caregiver` and `customFields.emergencyContact`

These property names are automatically generated.

Tenant 2 may define different custom fields, like "License date", etc.

So no overlap, and purely dynamic property names.

**Comment by vkarpov15** [comment]
Would `const CustomFieldsSchema = new Schema({}, { strict: false })` work for your use case?

Another option might be to use [maps](https://thecodebarbarian.com/whats-new-in-mongoose-5.1-map-support.html). I guess I'm just not quite understanding what "mixed properties to be saved on it" means?

**Comment by adamreisnz** [comment]
Hi @vkarpov15 , interesting solution `new Schema({}, { strict: false })`, I didn't know we can pass the strict parameter to schema creation as well, thought this was only for querying/updating etc.

I think that may work, I will give it a try!

What I meant is that essentially any object under that schema can have different properties, which are not known in advance. So a "free form" / non-strict schema should do the trick.
