### ISSUE TITLE
Support MongoDB realm GraphQL API

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#10382]
**Do you want to request a *feature* or report a *bug*?**

`feature`

**What is the current behavior?**

Currently, graphql behavior is not implemented in the codebase

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Implement MongoDB realm API

https://docs.mongodb.com/realm/graphql/

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**

**Comment by tbhaxor** [comment]
Hey guys any updates on this @vkarpov15 @IslandRhythms

**Comment by vkarpov15** [comment]
Not currently, we haven't used Realm yet so we're not sure what needs to be done. As best I can tell, all Mongoose really needs to do is support syncing Mongoose schemas to [Realm's schemas](https://docs.mongodb.com/realm/schemas/), which use a similar syntax to jsonschema. Similar to the docs described here: https://docs.mongodb.com/realm/schemas/enforce-a-schema/#std-label-enforce-a-schema

@tbhaxor does that sound like what you're thinking, or are you thinking something more sophisticated?
