### ISSUE TITLE
Mongoose does not reset object versioning during transaction abort?

### ISSUE THREAD

**Issue by yunfeng-scale** [Automattic/mongoose#10381]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It does not seem like Mongoose reset object versioning during transaction abort

**If the current behavior is a bug, please provide the steps to reproduce.**

it appears the object version is not reverted after transaction abort in the below snippet. relevant code: https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L483
```
  const newItem = createAndSaveTestItem(); // creates a version 0
  let secondVersion: ITestCollection;

  try {
    await session.withTransaction(async () => {
      newItem.someNumber = 432;
      secondVersion = await newItem.save({ session });
      // secondVersion is now storing the state of a successful v1
      attempt++;
      console.log(`Version after update and before transaction fail: ${newItem!.__v}`);
      throw new Error('Testing a transaction rollback');
    });
  } catch (err) {
    //
  }
  console.log(`Version is now ${secondVersion!.__v}`);
```

this causes problem for us when mongodb driver automatically retries (https://mongodb.github.io/node-mongodb-native/3.2/api/node_modules_mongodb-core_lib_sessions.js.html#line348) the transaction and resulted in version mismatches error like `VersionError: No matching document found for id "..." version 1 modifiedPaths ...`

we were able to fix this by fetching the object again at the start of the transaction so we're more confident on the above hypothesis.

**What is the expected behavior?**
object version is reverted back, either in default versioning or optimistic locking

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
forked version of 5.12.7, don't think we changed the transaction part of code

**Comment by IslandRhythms** [comment]
Could you please include the code for newItem?

**Comment by vkarpov15** [comment]
I'm unable to repro this, the given repro script doesn't mention anything about version keys or do anything to increment the document's version. Below script successfully shows version gets rolled back after transaction failure:

```javascript
'use strict';

const mongoose = require('mongoose');

const Schema = mongoose.Schema;

(async () => {
  // Using custom connection
  const db = await mongoose.createConnection('mongodb://localhost:27017,localhost:27018,localhost:27019/test', {
    useUnifiedTopology: true,
    useNewUrlParser: true,
  });

  const schema = new Schema({ name: String, arr: [String], arr2: [String] }, { optimisticConcurrency: true });

  const Test = db.model('Test', schema);

  await Test.createCollection();
  let doc = await Test.create({ name: 'foo', arr: ['bar'], arr2: ['foo'] });
  doc = await Test.findById(doc);
  console.log(`doc.name ${doc.name}`);
  console.log('Version key', doc.__v);
  await db
    .transaction(async session => {
      await doc.save({ session });
      doc.name = 'baz';
      console.log('going to fail the transaction and expecting doc.name reverted!');
      throw new Error('Oops');
    })
    .catch(err => {
      console.log(err);
    });

  const changes = doc.getChanges();
  console.log(`changes.$set.name ${changes.$set.name}`);
  console.log(`doc.name ${doc.name}`);
  console.log(`Version key after transaction: ${doc.__v}`);
})();
```

Output:

```
doc.name foo
Version key 0
going to fail the transaction and expecting doc.name reverted!
Error: Oops
    at /home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-10381.js:28:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-10381.js:23:3
changes.$set.name baz
doc.name baz
Version key after transaction: 0
```

Furthermore, the code you linked to shows the version key getting reset: https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L489

**Comment by yunfeng-scale** [comment]
my apologies, maybe I should create another ticket / rename the current ticket. i've moved past the versioning revert issue (didn't have time to verify); the focus of the script was on validation the behavior of this claim
```
Mongoose's Connection#transaction() function is a wrapper around withTransaction() that integrates Mongoose change tracking with transactions. For example, the Connection#transaction() function handles resetting a document if you save() that document in a transaction that later fails.
```
in https://mongoosejs.com/docs/transactions.html

as you can see `doc.name` was not revert after transaction failed. this poses a problem for us to solve from application side since we'll have to wrap all transactions with try/catch and revert its in-memory states if transaction failed later (through deep copy and deep set), is it possible for Mongoose to do the revert?

**Comment by yunfeng-scale** [comment]
thanks for the response. there are two difficulties that we face if Mongoose does not reset the doc:
1. we'll have to refetch the all docs involved in a transaction, and that might not be the proper behavior if the doc has in-memory modified states that are not yet saved;
2. if the transaction throws, we'll have to catch and reset all the values involved in the transaction

so i think it's difficult for us to guarantee correctness for all transactions from application side, thus i'm wondering if Mongoose can help add such a feature to (optionally) rollback in-memory states? in my understanding Mongoose does track all the modifications so it should be doable?

**Comment by vkarpov15** [comment]
It's certainly possible, we'll consider this for a future release.

**Comment by vkarpov15** [comment]
In the meantime, I'm curious why you don't just fetch documents within the transaction? I'm sure you have your reasons, I'd just like to get a quick overview of what they are.

**Comment by yunfeng-scale** [comment]
for some documents refetch would revert some already modified in-memory states that happened before the transaction. so we decided to fetch the document while reusing some in-memory states cached outside of transaction. this made it quite messy to maintain
