### ISSUE TITLE
`hasOwnProperty()` always returns true for schema paths on document instances

### ISSUE THREAD

**Issue by dbronin** [Automattic/mongoose#10392]
**Do you want to request a *feature* or report a *bug*?**
Reporting a _bug_ (I hope)

**What is the current behavior?**
hasOwnProperty resolves to false on a mongoose object even if the object has that property

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
'use strict'

const util = require('util')
const mongoose = require('mongoose')

mongoose.set('useFindAndModify', false)

const { Schema } = mongoose

run().catch(err => console.log(err))

async function run() {
   await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
    })

    const Books = mongoose.model('books', new Schema({name: String, author: {_id: Schema.Types.ObjectId, name: String}}))
    const Authors = mongoose.model('authors', new Schema({name: String}))

    const anAuthor = new Authors({name: 'Author1'})
    await anAuthor.save()

    const aBook1 = new Books({name: 'Book1', author: {_id: anAuthor.id}})
    await aBook1.save()

    const populateOptions = [{
            path: 'author',
            model: 'authors',
            select: '_id name'
        }
    ]

    const books = await Books.find()

    console.log('books = ' + util.inspect(books, false, null, true))
    /*books = [{
        _id: aBook1.id,
        name: aBook1.name
        author: {_id: anAuthor.id }
    }]
    */

    if (books[0].hasOwnProperty('name')) {
        console.log('book has name property') //*<-- this IS NOT executed, although books[0] has a name
    }
    //console.log(books[0].name)

    //now, we try to populate the array to get authors
    const populatedBooks = await Books.populate(books, populateOptions)

    if (populatedBooks[0].author.hasOwnProperty('name')) {
        console.log(`author has property name with value: ${populatedBooks[0].author.name}`) //*<-- this IS executed, correctly so, since an author has a name
    }

    await mongoose.connection.dropDatabase()
}
```

**What is the expected behavior?**
hasOwnProperty should be true when the object "has" said property

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 12.18.3
MongoDB: 4.2.13
Mongoose: 5.12.15

Thank you!

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior, because `name` is an inherited property on `books[0]`, not an own property. You can read more about why in this blog post: http://thecodebarbarian.com/mongoose-internals-schemas-options-models.html . But, TLDR, `Books.prototype` has a `name` property that acts as a shorthand for `this.get('name')`. So when you do `books[0].name`, you're accessing an inherited property that does `this.get('name')`.

I'd say the best workaround would be to do `books[0]._doc.hasOwnProperty('name')`, or to check if `books[0].name !== undefined`. Since the MongoDB Node driver converts `undefined` to `null`, there's no way to store a key that is strictly equal to `undefined` in Mongoose, so `books[0].name === undefined` if and only if books[0] does not have a `name` property.

**Comment by dbronin** [comment]
@vkarpov15 Thank you for your response. Can you please elaborate as to why the populated object behaves differently then? Thanks.

**Comment by vkarpov15** [comment]
`author` is a nested path that does not have a `name` property, so `name` is actually an own property on `author` rather than an inherited getter from the model.

I realize this is a bit of a gotcha, sorry for the confusion. Do either of the `_doc` or `!== undefined` workarounds work for you?

**Comment by dbronin** [comment]
@vkarpov15 Got it - that makes sense, thank you. I am sure that the workarounds are fine - our problem is that the code base is hundreds of thousands of lines and going through all of it is a challenge. Would you consider overwriting hasOwnProperty on mongoose objects, maybe with a global flag? Thank you.

**Comment by vkarpov15** [comment]
You can do that on your own with a quick plugin:

```javascript
mongoose.plugin(schema => {
  schema.methods.hasOwnProperty = function hasOwnProperty(path) {
    return this._doc.hasOwnProperty(path);
  };
});
```

**Comment by dbronin** [comment]
@vkarpov15 that's perfect - thank you for the pointer. I will close this issue now then.
