### ISSUE TITLE
[Bug] Mongoose ignores strict mode on findOneAndUpdate

### ISSUE THREAD

**Issue by ziv-codefresh** [Automattic/mongoose#10390]
mongoose 5.12.10

Mongoose ignores strict mode on findOneAndUpdate and let to add a document with missing required fields.
when I'm trying to use save instead, I'm getting an error for those missing fields.
I'm using strict: true in the schema definition.

**Comment by vkarpov15** [comment]
Can you please provide a more detailed code sample?
