### ISSUE TITLE
castNonArrays SchemaType option

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10398]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when `castNonArrays` is set to `false`, it still casts stuff

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
// NodeJS: 16.3.0
// MongoDB: 4.2-bionic (Docker)
import * as mongoose from "mongoose"; // mongoose@5.12.14

const schema1 = new mongoose.Schema({
  someArray: [{
    type: String,
    castNonArrays: false
  }]
});

const model1 = mongoose.model("model1", schema1);

(async () => {
  await mongoose.connect(`mongodb://localhost:44361/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const newdoc = await model1.create({ someArray: "hello" }); // no validation error

  const found = await model1.findById(newdoc);

  console.log(found);

  await mongoose.disconnect();
})();
```

yes typescript is used, but shouldnt matter for this example

Full Reproduction Repository: https://github.com/typegoose/typegoose-testing/tree/mongoosecastNonArrays

**What is the expected behavior?**
to fail with an cast error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

nodejs: 16.4.0
mongoose: 5.12.14
mongodb(server): 4.0.25

---

my guess is that because the following line: 

https://github.com/Automattic/mongoose/blob/012808cd356ed542828bc8f39776b8dca496bf5d/lib/schema/array.js#L397

is `||` instead of `&&` (and no error)

**Comment by vkarpov15** [comment]
The issue isn't with the `||`, it's that `castNonArrays` is a static option on `mongoose.Schema.Types.Array.options`. So `someArray: [{ type: String, castNonArrays: false }]` doesn't work, but `mongoose.Schema.Types.Array.options.castNonArrays = false` does.

Does this work for your use case, or do you need to turn on/off `castNonArrays` on individual schema paths?

**Comment by hasezoey** [comment]
thanks for clarifying that this is an static option, i didnt even know such options existed

> Does this work for your use case, or do you need to turn on/off castNonArrays on individual schema paths?

actually, i dont have a use case myself, it was just that someone (in typegoose) wanted to disable casting `value: "SomeString"` to `value: ["SomeString"]` for one Schema at least

> or do you need to turn on/off castNonArrays on individual schema paths?

personally, i would prefer having all such options either as schema-options, or as property options, instead of static for all things

**Comment by hasezoey** [comment]
i think this issue should be moved from the current milestone to milestone for 6.5.0
