### ISSUE TITLE
this.$__isSelected is not a function error when timestamps set to true in the Mongoose Schema

### ISSUE THREAD

**Issue by LawP09** [Automattic/mongoose#10404]
Good morning.
I have exactly the same issue as @soubhikchatterjee with mongoose 5.13.0, NodeJS 14.17.1

Schema creation : 
```import { Schema } from 'mongoose';

export const receiptBatchImportRequestLockSchema: Schema<IReceiptBatchRequestLock> = new Schema(
  {
    _id: String
  },
  { timestamps: true }
);

export interface IReceiptBatchRequestLock {
  _id: string;
  createdAt?: Date;
  updatedAt?: Date;
}
```

Model creation : 
``` 
import * as mongoose from 'mongoose';

private db: mongoose.Connection;
private receiptBatchImportRequestLockModel: mongoose.Model<IReceiptBatchRequestLock>;

this.receiptBatchImportRequestLockModel = this.db.model<IReceiptBatchRequestLock>(
    'receiptBatchImportRequestLock',
    receiptBatchImportRequestLockSchema,
    'receiptBatchImportRequestLock'
);
```

Save in MongoDB (v4.2) : 
```
  public async createReceiptBatchImportRequestLock(lock: IReceiptBatchRequestLock, session: mongoose.ClientSession) {
    logger.info('#createReceiptBatchImportRequestLock ...');
    try {
      this.initialize();
      const result = new this.receiptBatchImportRequestLockModel(lock);
      await result.save({ session });
      return result;
    } catch (error) {
      logger.error({ error }, 'Error when creating a Receipt Batch Import Request Lock.');
      throw error;
    }
  }
``` 

- When I put `{ timestamps: false }` it works correctly and don't save createdAt and updatedAt fields

- When I remove `this.$__isSelected(createdAt)` from the setupTimestamps.js file it works correctly and save createdAt and updatedAt fields into the DB.

What the $__isSelected function is supposed to do. I tried to debug but I found nothing.

Thanks in advance for your investigation.

_Originally posted by @LawP09 in https://github.com/Automattic/mongoose/issues/10259#issuecomment-870676547_

**Comment by LawP09** [comment]
I downgraded the mongoose version to 5.9.29 and it works well.

**Comment by IslandRhythms** [comment]
it seems like you're dealing with transactions, in which case you cannot test this locally and must use a live db. I created a script based off what you have given and am unable to reproduce. Give a more detailed script and I can try again.

**Comment by LawP09** [comment]
Yes I use a mongoDB transaction to save the ReceiptBatchRequestLock as it's a part of a process. 
Locally I built a MongoDB replicaSet with Docker so transactions works properly.
Even before I implement transactions, the timestamps issue was already there.

But with mongoose v5.9.29, timestamps works with and without transactions.

I'm going to send you a script outside my project to reproduce the issue.

**Comment by vkarpov15** [comment]
The issue you're experiencing is usually due to having multiple versions of Mongoose installed. For example, OP in the issue you referenced, #10259, has a Mongoose version in `/Users/phantom/projects/personal/backend/service1/node_modules/mongoose`, and an incompatible version in `/Users/phantom/projects/personal/backend/service1/src/submodules/node_modules/mongoose`, note the extra `src/submodules`.

Please post the full stack trace, and run `npm list | grep "mongoose"` to make sure you don't have multiple incompatible versions of Mongoose.

The below script executes without error, so please double check that you don't have multiple versions of Mongoose installed.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const receiptBatchImportRequestLockSchema = new Schema(
  {
    _id: String
  },
  { timestamps: true }
  );

  class ModelContainer {
    constructor() {
      this.model = mongoose.model('Test', receiptBatchImportRequestLockSchema);
    }

    async createReceiptBatchImportRequestLock(lock) {
      lock = new this.model(lock);
      await lock.save();
    }
  }

  const container = new ModelContainer();

  await container.createReceiptBatchImportRequestLock({ _id: 'test' });
  console.log('Done');
}
```

**Comment by LawP09** [comment]
Hi @vkarpov15 
Thanks for your analysis.

- **With 5.9.29 mongoose version: (timestamp works)**
```
❯ npm list -a "mongoose"
fin-cashing-deposit-api@3.13.0 /Users/phil/VDM/fin-cashing-deposit/fin-cashing-deposit-api
├─┬ @villemontreal/core-utils-mongo-nodejs-lib@6.2.0
│ └── mongoose@5.9.20
├─┬ casbin-mongoose-adapter@3.0.1
│ └── mongoose@5.13.2
└─┬ mongoose@5.9.29
  └─┬ mongoose-legacy-pluralize@1.0.2
    └── mongoose@5.9.29 deduped
``` 


- **With 5.10.19 mongoose version: (timestamp works)**
```
❯ npm list -a "mongoose"
fin-cashing-deposit-api@3.13.0 /Users/phil/VDM/fin-cashing-deposit/fin-cashing-deposit-api
├─┬ @villemontreal/core-utils-mongo-nodejs-lib@6.2.0
│ └── mongoose@5.9.20
├─┬ casbin-mongoose-adapter@3.0.1
│ └── mongoose@5.13.2
└─┬ mongoose@5.10.19
  └─┬ mongoose-legacy-pluralize@1.0.2
    └── mongoose@5.10.19 deduped
```
setupTimestamps.js: line 54 
```
    if (!skipCreatedAt && createdAt && !this.get(createdAt) && this.isSelected(createdAt)) {
      this.$set(createdAt, auto_id ? this._id.getTimestamp() : defaultTimestamp);
    }
``` 
function isSelected works well and doesn't throw an error.


- **With 5.12.15 mongoose version: (timestamp DOES NOT work / ERROR: this.$__isSelected is not a function)**
```
❯ npm list -a "mongoose"
fin-cashing-deposit-api@3.13.0 /Users/phil/VDM/fin-cashing-deposit/fin-cashing-deposit-api
├─┬ @villemontreal/core-utils-mongo-nodejs-lib@6.2.0
│ └── mongoose@5.9.20
├─┬ casbin-mongoose-adapter@3.0.1
│ └── mongoose@5.13.2
└─┬ mongoose@5.12.15
  └─┬ mongoose-legacy-pluralize@1.0.2
    └── mongoose@5.12.15 deduped
``` 
setupTimestamps.js: line 54 
```
    if (!skipCreatedAt && createdAt && !this.get(createdAt) && this.$__isSelected(createdAt)) {
      this.$set(createdAt, auto_id ? this._id.getTimestamp() : defaultTimestamp);
    }
```
function __isSelected throw an error.


- With 5.13.2 mongoose version: (timestamp DOES NOT work / ERROR: this.$__isSelected is not a function)
```
❯ npm list -a "mongoose"
fin-cashing-deposit-api@3.13.0 /Users/phil/VDM/fin-cashing-deposit/fin-cashing-deposit-api
├─┬ @villemontreal/core-utils-mongo-nodejs-lib@6.2.0
│ └── mongoose@5.9.20
├─┬ casbin-mongoose-adapter@3.0.1
│ └── mongoose@5.13.2 deduped
└─┬ mongoose@5.13.2
  └─┬ mongoose-legacy-pluralize@1.0.2
    └── mongoose@5.13.2 deduped
```

**Comment by LawP09** [comment]
Your script works well no matter the version used. So I assumed it's probably due to multiple versions installed. 
The thing is why it was not a problem with the versions under 5.11.x and started from 5.12.x it doesn't work anymore.
It seems to be a regression.

**Comment by vkarpov15** [comment]
Are you able to bump the Mongoose versions in the other libraries? Or, better yet, list mongoose as a peer dependency in those projects?
