### ISSUE TITLE
Bulk save

### ISSUE THREAD

**Issue by billouboq** [Automattic/mongoose#10401]
Hi, I saw that in mongoose 5.13 we have a new way to create multiple documents in one bulk write.

I would like to now the difference between insertMany and bulkSave ?

**Comment by vkarpov15** [comment]
`bulkSave()` also works for modifying existing documents. So you can do something like

```javascript
const test1 = await User.findOne({ name: 'test1' });
const test2 = await User.findOne({ name: 'test2' });

test1.name = 'test1 updated';
test2.name = 'test2 updated';
await User.bulkSave([test1, test2]);
```

And that will send `{ $set: { name: 'test1 updated' } }` and `{ $set: { name: 'test2 updated' } }` in one `bulkWrite()`.

`insertMany()` is only good for inserting multiple documents in one `bulkWrite()`.

**Comment by billouboq** [comment]
Thank you very much !
