### ISSUE TITLE
"mongoose.Schema.Types.Embedded" should be renamed to "mongoose.Schema.Types.SingleNestedPath"

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10419]
**Do you want to request a *feature* or report a *bug*?**
enhancement

property `mongoose.Schema.Types.Embedded` should be renamed to `mongoose.Schema.Types.SingleNestedPath` to be consistent with the file name and "class" name

https://github.com/Automattic/mongoose/blob/c03cacb5659f640034e67d8a1ee1cae427c12762/lib/schema/index.js#L16

i think this will be something for 6.0 instead of 5.x

Note: i didnt find any issue that already would track this

**Comment by vkarpov15** [comment]
I agree, thanks :+1:
