### ISSUE TITLE
[Types] properties like "caster" are not typed (SingleNestedPath)

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10418]
**Do you want to request a *feature* or report a *bug*?**
types

**What is the current behavior?**
the options are un-typed

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
// NodeJS: 16.4.1
// MongoDB: 4.2-bionic (Docker)
import * as mongoose from "mongoose"; // mongoose@5.13.2

const schema1 = new mongoose.Schema({ nestedPath1: { prop1: String } });
const schema2 = new mongoose.Schema({ nestedSchema: schema1 });
// @ts-ignore
console.log("schema1.nestPath1", schema1.path("nestedPath1"));
// @ts-ignore
console.log("schema2.nestedSchema", schema2.path("nestedSchema").caster);

// tslint-disable no-unused
schema2.eachPath((path, type) => {
  console.log("path,type", path, type);
  if (type instanceof mongoose.Schema.Types.Embedded) {
    // currently an error everywhere from typescript "property does not exist"
    type.caster;
    type.emit;
    type.on;
    type.path;
    type.base;
  }
});
```

**What is the expected behavior?**
the properties to be typed

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.13.2

---

options to do:
- [ ] `mongoose.Schema.Types.Embedded` should extends `EventEmitter`
- [ ] `path` should be typed
- [ ] `base` should be typed
- [ ] when possible `'$isSingleNested'` should also be typed

**Comment by vkarpov15** [comment]
@hasezoey mongoose.Schema.Types.Embedded does not extend `EventEmitter`, it is a SchemaType. And `path`, `base`, and `$isSingleNested` are currently undocumented properties for internal use - why do you need to use them?

**Comment by hasezoey** [comment]
> mongoose.Schema.Types.Embedded does not extend EventEmitter

sorry, i just noticed it has many (if not even all) properties that an `EventEmitter` would have (like `on`, `off`,or `*Listeners` functions)

> why do you need to use them?

- as for `path` it would be nice to just have it in types, because it exists at runtime and from what i know is always the path name
- as for `base` it could be directly used instead of having to supply it some other way (from what i know, it is what is supplied by schema options `existingMongoose`)
- as for `$isSingleNested`, i have no clue for what its for, and just mentioned it, because it also exists and is accessible from the outside

i dont have an use-case for any of them at the moment, i just saw them that they are untyped, but still accessible from the outside and could be useful to others (at least `path` & `base`)

**Comment by vkarpov15** [comment]
You might be mixing up the subdocument schematype and the actual subdocument type. Subdocuments are event emitters, but subdocument schematypes are not.

**Comment by hasezoey** [comment]
that *might* be true, so what is `schema.path()` and `schema.eachPath`(the second parameter from the callback) supposed to be

and just to clarify, with subdocument-schematype you mean `Schema.Types.*` and with actual-subdocuments you mean `Types.*`? when yes, them i am mixing things up maybe, but if not, look at the reproduction code i provided, it clearly logs the output from `schema.eachPath` (both parameters) and it contained those values / functions on the output

**Comment by vkarpov15** [comment]
`schema.path()` returns the subdocument schematype, e.g. `instanceof mongoose.Schema.Types.Embedded`.

And yes, the subdocument schematype does have those properties, but they're not meant to be user-facing. If there's a reason for them to be user facing I'm happy to add them to the TS bindings.
