### ISSUE TITLE
Aggregate.cursor do not return AggregateCursor

### ISSUE THREAD

**Issue by Streeterxs** [Automattic/mongoose#10410]
**Do you want to request a *feature* or report a *bug*?**
report bug

**What is the current behavior?**
`aggregate.cursor` do not return a cursor. We need to execute aggregate.exec to get a AggregateCursor
https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/lib/aggregate.js#L835-L841

EDIT:
Today I use this function to normalize aggregate/query cursors:
```ts
const getCursor = <T extends Document>(
  queryAgg: DocumentQuery<T, T> | Aggregate<T>,
  batchSize = 1000,
) => queryAgg._pipeline
    ? queryAgg.cursor({ batchSize }).exec()
    : queryAgg.cursor({ batchSize });
```

I think this is wrong, shouldn't Aggregate.cursor() do the same thing as Query.cursor() returning similar cursor property? **Why Aggregate.cursor() do not do that?**

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
const aggCursor = Aggregate([]).cursor({batchSize: 1000})
aggCursor.next() // next is not a function
```

**What is the expected behavior?**
```ts
aggCursor: AggregateCursor
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```ts
node: 14.17
mongoose: 5.13
```

**Comment by Streeterxs** [comment]
This isn't a typescript issue

**Comment by vkarpov15** [comment]
This is a good point, we should consider making this change for 6.0 to be more consistent. No reason why `Query#cursor()` and `Aggregate#cursor()` should be so different, especially since the `exec()` syntax for aggregation cursors is pretty messy.
