### ISSUE TITLE
browser.umd.js packaged into NextJS client when running npm run build

### ISSUE THREAD

**Issue by joniaiuser** [Automattic/mongoose#10429]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/64962001/124796272-8f21d100-df83-11eb-9afd-54ad090fa8aa.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

npm run build

I am currently trying to reproduce the issue in an example repo, but have been unable to do so despite using the same code patterns and packages. Not sure what is going on, so hoping to get some ideas here.

I can confirm that I am **not** running any mongoose functions client side, but I do share types with my api, since it's a nextjs repo. However I tried doing the same in other projects and could not reproduce this issue. I wonder if it has something to do with the size of the repo and the number of shared types.. Moreover, even if types are shared, they should be tree shaken at build time? 

```{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "middleware/mongodb.ts",
    "integrations/**/*.ts",
    "integrations/*.ts",
    "services/*.ts",
    "services/**/*.ts",
    "components/**/*.ts",
    "components/**/*.tsx",
    "components/*.ts",
    "components/*.tsx",
  ],
  "exclude": [
    "node_modules",
  ],
  "files": ["react-table-config.d.ts"]
}
```

**What is the expected behavior?**

I expect that Mongoose should not be packaged into client side.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v14
mongoose 5.13.2
MongoDB 4.4.6

**Comment by vkarpov15** [comment]
You would need to come up with a GitHub repo that demonstrates this. My best guess is that you're accidentally importing something that imports Mongoose on the client side. What do you mean by "the number of shared types"?

**Comment by joniaiuser** [comment]
Thanks, I will work towards a repro that I can share.

**Comment by vkarpov15** [comment]
Without a repro there isn't much we'll be able to do unfortunately. Type complexity or number of types shouldn't matter here.

**Comment by joniaiuser** [comment]
I managed to resolve this. Issue was because I colocated some of my enums with my models, which turned out to be problematic as importing them in the frontend caused the mongoose package to be imported as well..
