### ISSUE TITLE
Wrong type for mongoose.connect

### ISSUE THREAD

**Issue by MariaSolOs** [Automattic/mongoose#10422]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** I'm trying to migrate my server to typescript but it seems like the type for `mongoose.connect` is incorrect.
<img width="791" alt="Screen Shot 2021-07-05 at 1 34 53 PM" src="https://user-images.githubusercontent.com/62502207/124504798-29bcbd00-dd96-11eb-9bac-fd4a7b72e02c.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

```
import mongoose from 'mongoose';

mongoose.connect(process.env.MONGODB_URI!, {
    useCreateIndex: true, 
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
})
.then(() => console.log('Mongoose connected.'))
.catch(err => console.error(err));
```

{
  "compilerOptions": {
    "target": "es6",       
    "module": "commonjs",
    "strict": true, 
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": "./",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": [
      "node_modules"
  ]
}

**What is the expected behavior?** Be able to connect to the database without any mongodb driver/typescript warnings 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node.js: 14.17.0
mongoose: 5.13.2
mongodb: 4.4.5

**Comment by IslandRhythms** [comment]
```
import * as mongoose from 'mongoose';

mongoose.connect('mongodb://localhost:27017/test', {
    useCreateIndex: true, 
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
})
.then(() => console.log('Mongoose connected.'))
.catch(err => console.error(err));
```

**Comment by IslandRhythms** [comment]
`process.env.MONGODB_URI!` is that exclamation mark intentional?

**Comment by MariaSolOs** [comment]
Yes, it is a Typescript file.
I ended up solving the issue, I named the file `mongoDB.ts` and this was shadowing the types from `mongodb`. Changing the filename to `mongoDB.config.ts` solved it :)
