### ISSUE TITLE
Typescript: Internal types use `Date` instead of `NativeDate` - bug?

### ISSUE THREAD

**Issue by kfiroo** [Automattic/mongoose#10426]
Hey!

Trying to implement custom `timestamps.currentTime` as described in the [docs](https://mongoosejs.com/docs/guide.html#timestamps)

My simplified implementation looks like this: 
```typescript
const thingSchema = new mongoose.Schema({
  //...
}, {
  timestamps: {
    currentTime: () => new Date()
  } 
});
```

I get the following TS error:
```
TS2322: Type 'Date' is not assignable to type 'number | Date'.
  Type 'Date' is not assignable to type 'number'.
```

After some investigation it looks like there might be some confusion with the [`NativeDate`](https://github.com/Automattic/mongoose/blob/master/index.d.ts#L15) and [`Date`](https://github.com/Automattic/mongoose/blob/master/index.d.ts#L18) types.

For instance, I would expect [`mongoose.now`](https://github.com/Automattic/mongoose/blob/master/index.d.ts#L123) to return `NativeDate` and not `Date`
Same for [`mongoose.SchemaTimestampsConfig.currentTime`](https://github.com/Automattic/mongoose/blob/master/index.d.ts#L1435).

`mongoose` version `5.13.2`

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "skipLibCheck": true,
    "allowJs": true,
    "esModuleInterop": true,
    "noImplicitAny": true,
    "experimentalDecorators":true,
    "emitDecoratorMetadata": true,
    "strictFunctionTypes": true,
    "sourceMap": true,
    "lib": [
      "ESNext"
    ]
  },
  ...
}
```

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/5edb25d63fdff340e79e4f6fcdad403411bf369a, I typo-ed the issue number in the commit message.
