### ISSUE TITLE
Property 'Buffer' does not exist on type 'typeof globalThis' on v5.13.2

### ISSUE THREAD

**Issue by benpoulson** [Automattic/mongoose#10424]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
[7:08:10 PM] Starting compilation in watch mode...

node_modules/mongoose/index.d.ts:1883:33 - error TS2339: Property 'Buffer' does not exist on type 'typeof globalThis'.

1883     class Buffer extends global.Buffer {
                                     ~~~~~~

[7:08:14 PM] Found 1 error. Watching for file changes.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Blank NestJS project, install mongoose as docs describe.

Followed fix on #10415, however no change.

tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**What is the expected behavior?**

No errors on TS build.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS versions - v16.4.0 Linux and v12.16.1 OSX

Mongoose version - Unable to retreive from framework via console.log, but package-lock.json states:
@nestjs/mongoose: `7.2.4`
mongoose: `5.13.2` (depends `@types/node`: 15.14.1)

Attached both package.json and package-lock.json.

[package.json.zip](https://github.com/Automattic/mongoose/files/6771953/package.json.zip)

**Comment by benpoulson** [comment]
Closed; My fault, for some reason @types/node 16.x doesn't work, but 15.x does.

**Comment by jezsung** [comment]
How do we use it with `@types/node@16.0.0`?

**Comment by hantsy** [comment]
Got the same issue here when upgrading to Node 16 API.

**Comment by hantsy** [comment]
OMG, the solution is downgrading `@types/node`, not fixing it.

**Comment by vkarpov15** [comment]
We'll upgrade to @types/node@16 for Mongoose 6. I don't know of any way that Mongoose can support both @types/node@15 and @types/node@16, but PRs are most welcome if you have a suggestion.

**Comment by PCOffline** [comment]
Bumping this - got into the same issue

**Comment by pruthviraj1991** [comment]
bumping this up, got same issue

**Comment by enriqueddm** [comment]
bumping this up, got same issue

**Comment by vkarpov15** [comment]
Upgrade to mongoose@5.13.3 :+1:
