### ISSUE TITLE
Aggregation / $map and $cond

### ISSUE THREAD

**Issue by kamalkech** [Automattic/mongoose#10431]
For speciale case i need to this query bellow using aggragation, 
match is array contain multiple items of type { value: xxx, wegiht: yyy }
but the probelme the condition $cond if... not working every time give secound result => found = 2, mean "$$item.value" not defined correctly

any idea plz to help

```
$map: {
  input: match,
  as: 'item',
  in: {
    $cond: {
      if: {
        $eq: [
          field,
          mongoose.Types.ObjectId( "$$item.value" )
        ],
      },
      then: {
        weight: '$$item.weight',
        found: 1
      },
      else: {
        weight: '$$item.weight',
        found: 0
      },
    },
  },
},
```

**Comment by IslandRhythms** [comment]
Please provide a script that demonstrates the issue.

**Comment by kamalkech** [comment]
@IslandRhythms cannot undestand your comment, my description very clear

**Comment by vkarpov15** [comment]
@kamalkech we'd need to know what the documents in the database look like to be able to repro this issue.

I'd venture a guess that you should replace `mongoose.Types.ObjectId( "$$item.value" )` with `"$$item.value"`. You only need to use `mongoose.Types.ObjectId()` if you're looking to convert an ObjectId string literal to an ObjectId.
