### ISSUE TITLE
Static getters in model classes are causing an error since Mongoose v5.12.9

### ISSUE THREAD

**Issue by yelworc** [Automattic/mongoose#10436]
**Do you want to request a *feature* or report a *bug*?**

A bug (I guess 😄)

**What is the current behavior?**

Static getters defined in a Mongoose model were working fine up to v5.12.8, but as of v5.12.9 are causing an error when the model is loaded/initialized:

    TypeError: Cannot set property <…> of class <…> extends mongoose.Model {
      <…>
    } which has only a getter
        at applyStatics (.../mongoose/lib/helpers/model/applyStatics.js:10:14)
        at Function.compile (.../mongoose/lib/model.js:4958:3)
        at Mongoose.model (.../mongoose/lib/index.js:583:27)

Pretty sure [a3c9acd](https://github.com/Automattic/mongoose/commit/a3c9acd12d00d396c92f8a7bb81fe3cfa3331e57) is the change that caused this.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a simple example:
https://gist.github.com/yelworc/c09d9e58ced1ca31604e9c23d4db7b00

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v16.4.0
Mongoose v5.12.9 and above
MongoDB 4.0.11

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in v5.13.3 :+1:
