### ISSUE TITLE
Allow to modify indexes before 

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#10446]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Hi, I've two problems about indexes, the first one is I use soft delete, so if I've a unique index, I need to add an partialFilterExpression to avoid problems.

Now I've a plugin to spread data to make partitions, so my plugin adds a _zone field, but in this plugin I need to change all the indexes generated in the schemas, I've no problem duplicating the indexes but my problem is the unique indexes, because now the unique index must include the _zone field.
 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I need to be able to modify the indexes generated in the schema, so the plugin can add the field to every index.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v16.4.1
mongodb: 4.4.6
mongoose: 5.13.2

**Comment by vkarpov15** [comment]
You can modify schema indexes in place by looping over [`schema.indexes()`](https://mongoosejs.com/docs/api/schema.html#schema_Schema-indexes) and modifying each index as shown below.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({ email: String, isDeleted: { type: Boolean, default: false } });
  schema.index({ email: 1 }, { unique: true, partialFilterExpression: { isDeleted: false } });

  schema.plugin(schema => {
    schema.add({ _zone: String });
    // Loop over every index in the schema
    for (const index of schema.indexes()) {
      if (index._zone != null) {
        continue;
      }
      // Add `_zone` as the first key in the index
      index[0] = { _zone: 1, ...index[0] };
    }
  });

  console.log(schema.indexes());
}

```

**Comment by chumager** [comment]
Cool!!!

Thanks a lot.

I owe you a beer 
Best Regards.

**Comment by vkarpov15** [comment]
Happy to help :beers:
