### ISSUE TITLE
findOneAndUpdate doesn't upsert new document without .then

### ISSUE THREAD

**Issue by DaliborTrampota** [Automattic/mongoose#10457]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When calling findOneAndUpdate without .then and the document doesn't exist but upsert is set to true, no document is created/added to the collection

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');

const userSchema = mongoose.Schema({
    _id: String,
    cards: { type: Array, default: [] },
    favourite: { type: String, default: "" },
    balance: { type: Number, default: 0 },
    bio: { type: String, default: "" }
});

module.exports = mongoose.model('User', userSchema);

//elsewhere
//require the module above
let card = {
 name: "test card"
 id: 1
}

//this doesnt create new document 
userModel.findOneAndUpdate({_id: "some id that doesnt exist in the collection"}, { $push: { cards: card }, { upsert: true, new: true, setDefaultsOnInsert: true })

//this creates new document 
userModel.findOneAndUpdate({_id: "some id that doesnt exist in the collection"}, { $push: { cards: card }, { upsert: true, new: true, setDefaultsOnInsert: true }).then(db => undefined) //I put undefined there because I dont want to do anything but if I put there console.log it logs the saved document
```

**What is the expected behavior?**
The document should be created

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"dependencies": {
    "canvas": "^2.8.0",
    "discord.js": "^12.5.3",
    "mongoose": "^5.13.2",
    "object-sizeof": "^1.6.1"
 },
 I dont know where I check mongoDB version but I'm using mongo atlas (cloud free version)
nodejs v14.15.4

**Comment by DaliborTrampota** [comment]
*or without awaiting it*

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const userSchema = new Schema({
    _id: String,
    cards: { type: Array, default: [] },
    favourite: { type: String, default: "" },
    balance: { type: Number, default: 0 },
    bio: { type: String, default: "" }
});

const User = mongoose.model('User', userSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
    
      await mongoose.connection.dropDatabase();

      const entry = await User.findOneAndUpdate({ _id: '123456789012'}, {$push: {cards: [{name: "test card", id: 1}]}}, {upsert: true, new: true, setDefaultsOnInsert: true});
      console.log(entry);
      const entry1 = User.findOneAndUpdate({ _id: '123456789012'}, {$push: {cards: [{name: "test card", id: 1}]}}, {upsert: true, new: true, setDefaultsOnInsert: true}).then(db => console.log(db));
      console.log(entry1);

}    
run();
```

**Comment by DaliborTrampota** [comment]
> ```
> const mongoose = require('mongoose');
> const {Schema} = mongoose;
> 
> const userSchema = new Schema({
>     _id: String,
>     cards: { type: Array, default: [] },
>     favourite: { type: String, default: "" },
>     balance: { type: Number, default: 0 },
>     bio: { type: String, default: "" }
> });
> 
> const User = mongoose.model('User', userSchema);
> 
> async function run() {
>     await mongoose.connect('mongodb://localhost:27017/test', {
>         useNewUrlParser: true,
>         useUnifiedTopology: true,
>       });
>     
>       await mongoose.connection.dropDatabase();
> 
>       const entry = await User.findOneAndUpdate({ _id: '123456789012'}, {$push: {cards: [{name: "test card", id: 1}]}}, {upsert: true, new: true, setDefaultsOnInsert: true});
>       console.log(entry);
>       const entry1 = User.findOneAndUpdate({ _id: '123456789012'}, {$push: {cards: [{name: "test card", id: 1}]}}, {upsert: true, new: true, setDefaultsOnInsert: true}).then(db => console.log(db));
>       console.log(entry1);
> 
> }    
> run();
> ```

You are awaiting it thus it won't reproduce... I said without .then or without await

**Comment by DaliborTrampota** [comment]
if you do it without the await and then query the same ID again you will see that the new card is not pushed into it

**Comment by DaliborTrampota** [comment]
can you try it again please @IslandRhythms like i described?

**Comment by DaliborTrampota** [comment]
and I'm using mongo atlas which is cloud database not local one

**Comment by IslandRhythms** [comment]
This isn't a bug. You need to use await for it to persist to the database

**Comment by IslandRhythms** [comment]
```
If you're using findOneAndUpdate() , you need to use await to get those changes to persist to the database.
When you do const q = Model.findOneAndUpdate(filter, update, options);, q is an instance of Mongoose's Query class. Mongoose doesn't execute the query until you call exec() or await on the query
```

**Comment by Kamikadze4GAME** [comment]
Hello @DaliborTrampota. Please stop flooding.

This is expected behaviour. See [Model.findOneAndUpdate](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate) docs:

> Finds a matching document, updates it according to the update arg, passing any options, and returns the found document (if any) to the callback. **_The query executes if callback is passed else a Query object is returned._**


> Examples:
> ```js
> A.findOneAndUpdate(conditions, update, options, callback) // executes
> A.findOneAndUpdate(conditions, update, options)           // returns Query
> A.findOneAndUpdate(conditions, update, callback)          // executes
> A.findOneAndUpdate(conditions, update)                    // returns Query
> A.findOneAndUpdate()                                      // returns Query
> ```

and [Mongoose Promises](https://mongoosejs.com/docs/promises.html) and [`async/await` with Mongoose Queries](https://mongoosejs.com/docs/async-await.html#queries)

--------

So, as a result you have only this options:

1. Use callback: `userModel.findOneAndUpdate(..., cb)` or
2. Use promise `then-catch`: `userModel.findOneAndUpdate(...).then(...).catch(...)` or
3. Use `async/await`: `await userModel.findOneAndUpdate(...)`

--------

> ... but I just went with it but *its annoying and the code isnt "clean"*

PS, if you think that [Asynchronous Concepts](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts) in JavaScript is *annoying*, I could suggest you **FOOTSHOT** --  just add `.exec()` after update:

```js
userModel.findOneAndUpdate(...).exec();
```

**Comment by DaliborTrampota** [comment]
> Hello @DaliborTrampota. Please stop flooding.
> 
> This is expected behaviour. See [Model.findOneAndUpdate](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate) docs:
> 
> > Finds a matching document, updates it according to the update arg, passing any options, and returns the found document (if any) to the callback. **_The query executes if callback is passed else a Query object is returned._**
> 
> 
> > Examples:
> > ```js
> > A.findOneAndUpdate(conditions, update, options, callback) // executes
> > A.findOneAndUpdate(conditions, update, options)           // returns Query
> > A.findOneAndUpdate(conditions, update, callback)          // executes
> > A.findOneAndUpdate(conditions, update)                    // returns Query
> > A.findOneAndUpdate()                                      // returns Query
> > ```
> 
> and [Mongoose Promises](https://mongoosejs.com/docs/promises.html) and [`async/await` with Mongoose Queries](https://mongoosejs.com/docs/async-await.html#queries)
> 
> --------
> 
> So, as a result you have only this options:
> 
> 1. Use callback: `userModel.findOneAndUpdate(..., cb)` or
> 2. Use promise `then-catch`: `userModel.findOneAndUpdate(...).then(...).catch(...)` or
> 3. Use `async/await`: `await userModel.findOneAndUpdate(...)`
> 
> --------
> 
> > ... but I just went with it but *its annoying and the code isnt "clean"*
> 
> PS, if you think that [Asynchronous Concepts](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts) in JavaScript is *annoying*, I could suggest you **FOOTSHOT** --  just add `.exec()` after update:
> 
> ```js
> userModel.findOneAndUpdate(...).exec();
> ```

Thank you.

I was just trying to make it clear what the issue was because @IslandRhythms didn't understand my issue at first so sorry if that was really a flooding it's not like there is big discussion going on here.

Anyway no JavaScript and Asynchronous Concepts aren't annoying. What is annoying putting .then(doc => undefined) after each query but now I see I can just do exec instead which is clearer. And what does FOOTSHOT mean?

It all makes sense now thanks again.
