### ISSUE TITLE
Compatibility with MongoDB 5.0

### ISSUE THREAD

**Issue by matiaslopezd** [Automattic/mongoose#10454]
Is mongoose's latest version `5.13.2` compatible with MongoDB 5.0?

**Comment by andalike** [comment]
+1

**Comment by Kamikadze4GAME** [comment]
Hello @matiaslopezd 

No, mongoose `5.13.2` does not compatible with MongoDB 5.0. 

According to [official MongoDB Node.JS Driver Computability table](https://docs.mongodb.com/drivers/node/current/compatibility/)only `3.7` and `4.0` driver's versions compatible with MongoDB `5.0`. Mongoose has dependency `mongodb` `3.6.10`.

I can only predict that next major mongoose's release (6.0) will be compatible.

**Comment by andalike** [comment]
> Hello @matiaslopezd
> 
> No, mongoose `5.13.2` does not compatible with MongoDB 5.0.
> 
> According to [official MongoDB Node.JS Driver Computability table](https://docs.mongodb.com/drivers/node/current/compatibility/) only `3.7` and `4.0` driver's versions compatible with MongoDB `5.0`. Mongoose has dependency `mongodb` `3.6.10`.
> 
> I can only predict that next major mongoose's release (6.0) will be compatible.

In this comment , it states that the support is provided. https://github.com/mongodb/node-mongodb-native/releases/tag/v4.0.0

**Comment by vkarpov15** [comment]
We're finishing up Mongoose 6.0 and expect to have a release candidate out in the next week or two. Mongoose 5.13.x is unfortunately not fully compatible with MongoDB 5.0.

**Comment by matiaslopezd** [comment]
The release will be very fast, more than I expected! 👏 Thanks, @vkarpov15 !
