### ISSUE TITLE
Mongoose schema default value

### ISSUE THREAD

**Issue by EmirBoyaci** [Automattic/mongoose#10458]
Hello,

I have a user schema that has a email verification code field with a default value. When I create a user with this schema, it has always the same email verification code. After restarting server, the email verification code is changing. In my opinion, when the server runs, it will generates a schema with the fields that we give in the schema and when we want to create a object with this schema, it will always calling the schema that was generated when the server runs. Is there any chance to use default field as a always new value? I found `schema.pre("save")` thing but it shouldn't be that hard. You can see my schema and function below:
![image](https://user-images.githubusercontent.com/59085992/125988066-4d76f1a1-64c9-4fcc-ad07-94dab8b8b546.png)![image](https://user-images.githubusercontent.com/59085992/125988072-91ae19fa-9001-4d51-be96-a91dc10636d9.png)

**Comment by EmirBoyaci** [comment]
In the mongoose docs it says
_ Defaults can be either functions which return the value to use as the default or the literal value itself._

https://mongoosejs.com/docs/api.html#schematype_SchemaType-default

**Comment by Kamikadze4GAME** [comment]
Hello @EmirBoyaci 

You should change 
`default: generateCode(6)`
with
`default: () => generateCode(6)`

Because `typeof generateCode(6) === 'string'`, you function executes only one during initial execution and mongoose reuse result from `generateCode` as default value for every future new user.
