### ISSUE TITLE
I got error in here

### ISSUE THREAD

**Issue by XG-2580** [Automattic/mongoose#10455]
![Screenshot 2021-07-16 162100](https://user-images.githubusercontent.com/70673506/125924960-d90be237-274c-464b-95a0-4d78b117aba8.png)

**Comment by andalike** [comment]
"True" is an Boolean value, so write it as "true" and it should work

**Comment by IslandRhythms** [comment]
^

**Comment by XG-2580** [comment]
> "True" is an Boolean value, so write it as "true" and it should work

Thank @
