### ISSUE TITLE
Error within fetching the database

### ISSUE THREAD

**Issue by DJHARDY2K21** [Automattic/mongoose#10456]
**Before I removed Node_Modules and reinstalled**, It would be fine till now. I rebooted my bot reinstalled all the modules and now it won't return data. But before this. It **Won't access to the database collection**, as it returns as no data created when the data is there.

Any help would be appreciated thanks

**Comment by Kamikadze4GAME** [comment]
Hello @DJHARDY2K21 , please, follow issue template and attach sufficient code to reproduce your issue.

**Comment by IslandRhythms** [comment]
^

**Comment by DJHARDY2K21** [comment]
Okay, my bad
