### ISSUE TITLE
MongoDB Driver 4.x

### ISSUE THREAD

**Issue by guyellis** [Automattic/mongoose#10461]
**Request a *feature***

**What is the current behavior?**

Works with mongodb driver 3.x. TypeScript types are not compatible with mongodb driver 4.x

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

Request: Support the 4.x driver

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node 16.3.0
- Mongoose 5.12.13
- MongoDB 4.0.0

**Comment by Kamikadze4GAME** [comment]
Hello @guyellis 

According to https://github.com/Automattic/mongoose/commit/2400fe821caf9d2852f031bf8ad821942a02c888, the next major release ([6.0](https://github.com/Automattic/mongoose/tree/6.0)) of the mongoose  will use mongodb driver 4.0.0

**Comment by vkarpov15** [comment]
We're finishing up Mongoose 6.0 and expect to have a release candidate out in the next week or two. Mongoose 5.13.x is unfortunately not fully compatible with MongoDB 5.0.

**Comment by faizalshap** [comment]
Hi @vkarpov15, any update on this please? We want to use the new AWS-MONGODB authentication which is only supported in driver >=4.0 and waiting for this. Thanks :)

**Comment by vkarpov15** [comment]
@faizalshap we released mongoose 6.0.0-rc0 last week, you should be able to do `npm install mongoose@next` to get the newest version. Try it out and please report any issues you find on GitHub - we're planning on releasing 6.0.0 in the next week or two once we've had a few people try out the new release.
