### ISSUE TITLE
findOneAndUpdate-hook not fired for nested array schema

### ISSUE THREAD

**Issue by timvol** [Automattic/mongoose#10462]
**Do you want to request a *feature* or report a *bug*?**

I guess it's a bug.

**What is the current behavior?**

I've a "findOneAndUpdate" hook on a nested schema but unfortunately this hook isn't fired. The schema is included by it's parent as an array.

**If the current behavior is a bug, please provide the steps to reproduce.**

When I run the following snippet, the hook is never executed. The entry is created, although I call `process.exit()` in the hook and  "something" is empty.

```js
const mongoose = require('mongoose')

const subSchema = new mongoose.Schema({
  something: {
    type: Date,
    required: false
  },
  name: {
    type: String,
    required: false
  }
})

subSchema.pre('findOneAndUpdate', async function () {
  this.something = Date.now()

  console.log('findOneAndUpdate hook!')
  process.exit()
})

const topSchema = new mongoose.Schema({
  entries: [subSchema]
})

const topModel = mongoose.model('TopSchema', topSchema)

async function test () {
  await mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/dbname?replicaSet=rs', {
    dbName: 'test',
    useCreateIndex: true,
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
  })

  await topModel.findOneAndUpdate({}, {
    entries: [{
      name: Date.now()
    }]
  }, {
    upsert: true
  })
}

test()
```

**What is the expected behavior?**

That the `findOneAndUpdate` hook is called for each entry in the `entries`-array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.13.3
MongoDB: 4.4.6

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/middleware.html#notes

**Comment by timvol** [comment]
Thanks @IslandRhythms but I don't see any reason pre('findOneAndUpdate') works just for the top-level schema and not for the nested one. When I add the `pre('findOneAndUpdate')` hook to the topSchema, it's getting called. But when I add the same hook (see above) to a nested element, it's never called.

**Comment by IslandRhythms** [comment]
They don't work, it says in the first line

**Comment by vkarpov15** [comment]
@timvol that's expected behavior unfortunately. We only fire query middleware on the top-level schema, not nested schemas.
