### ISSUE TITLE
Schema.index produces deprecation warning

### ISSUE THREAD

**Issue by fishcharlie** [Automattic/mongoose#10468]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
(node:90971) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
FeatureSchema.index({
	"geometry": "2dsphere"
});
```

Use the code above on a schema.

**What is the expected behavior?**

No deprecation warning.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v16.4.2
Mongoose: 5.13.2
MongoDB: 4.4.5

**Comment by alhassanv** [comment]
Can reproduce.

**Comment by vkarpov15** [comment]
See the driver deprecation docs: https://mongoosejs.com/docs/deprecations.html
