### ISSUE TITLE
Populate subroutine not fetching latest docuents

### ISSUE THREAD

**Issue by viskie** [Automattic/mongoose#10472]
I have a embedded Schema array based field in a primary Schema.
While populating the sub-documents, there is a Numeric field that stores either 1 or 0. (Numeric for future range provisioning),
these sub documents don't fetch correct values. Its always 1. Other fields like string based ones are correctly fetched along with id. 

But if I dont use populate and fetch these docs manually using find, I get correct vals.

node: v12.18.2
v: ^5.13.3

**Comment by IslandRhythms** [comment]
Please follow the format of reporting an issue and provide a script
