### ISSUE TITLE
TypeScript: Fix for model constructor using "any." new Model(doc?:any) 

### ISSUE THREAD

**Issue by adingeist** [Automattic/mongoose#10475]
### Problem:
When using the model constructor, the doc argument is typed with any. Shown here:
<img width="416" alt="Screen Shot 2021-07-20 at 7 14 44 PM" src="https://user-images.githubusercontent.com/67285419/126406844-a5c958ea-925e-46f8-8d48-65803dab0405.png">

### Source of the issue in **index.d.ts** (line 631):
```
  interface Model<T, TQueryHelpers = {}, TMethods = {}> extends NodeJS.EventEmitter, AcceptsDiscriminator {
    new(doc?: T | any): EnforceDocument<T, TMethods>;
```
Although using the generic T has good intentions at including model properties, the union with any overrides type checking, making the type simply "any."

### My solution
Note that not everything in a model's schema is used by a constructor (which is likely why "any" was union'ed with <T> in the first place.) My solution to this is by creating a DeepPartial<T> type to make all properties and their nested properties optional. [Credit for DeepPartial<T>](https://typeofnan.dev/creating-your-own-deeppartial-type-in-typescript/)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/mongoose/index.d.ts b/node_modules/mongoose/index.d.ts
index be86d72..380fcce 100644
--- a/node_modules/mongoose/index.d.ts
+++ b/node_modules/mongoose/index.d.ts
@@ -625,10 +625,13 @@ declare module 'mongoose' {
   interface AnyObject { [k: string]: any }
   type EnforceDocument<T, TMethods> = T extends Document ? T : T & Document<any, any, T> & TMethods;
 
+  type DeepPartial<T> = Partial<{ [P in keyof T]: DeepPartial<T[P]> }>;
+
   export const Model: Model<any>;
   // eslint-disable-next-line no-undef
   interface Model<T, TQueryHelpers = {}, TMethods = {}> extends NodeJS.EventEmitter, AcceptsDiscriminator {
-    new(doc?: T | any): EnforceDocument<T, TMethods>;
+    new(doc?:  DeepPartial<T>): EnforceDocument<T, TMethods>;
+    
 
     aggregate<R = any>(pipeline?: any[]): Aggregate<Array<R>>;
     // eslint-disable-next-line @typescript-eslint/ban-types
@@ -871,7 +874,7 @@ declare module 'mongoose' {
     replaceOne(filter?: FilterQuery<T>, replacement?: Object, options?: QueryOptions | null, callback?: (err: CallbackError, res: any) => void): QueryWithHelpers<any, EnforceDocument<T, TMethods>, TQueryHelpers, T>;
 
     /**
      * @deprecated use `updateOne` or `updateMany` instead.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

### Look at that beautiful type checking! 🎉
<img width="772" alt="Screen Shot 2021-07-20 at 7 45 13 PM" src="https://user-images.githubusercontent.com/67285419/126408862-ed3a7666-3154-404b-a748-dc03385e12bb.png">
<img width="415" alt="Screen Shot 2021-07-20 at 7 45 29 PM" src="https://user-images.githubusercontent.com/67285419/126408871-e056b1d2-db5d-4e80-9e22-c56efe07453f.png">

A better solution may exist because the time complexity of the DeepPartial<T> isn't great using looping.

**Comment by vkarpov15** [comment]
We will take a look and see if this approach works. any is intentional - you can pass any object to a model constructor. But we may be able to figure out some way to make autocomplete work better without breaking everyone's code.

**Comment by adingeist** [comment]
I've been working with this approach more and unfortunately, it could cause breaking changes. It's common to see test suites use a variable that's reset each time before a test. However, we only have access to the global **Partial** type, not the customized **DeepPartial** type. This will cause issues with 

<img width="493" alt="Screen Shot 2021-07-28 at 8 55 49 AM" src="https://user-images.githubusercontent.com/67285419/127325725-4d818bbc-1464-4499-8f02-cfea6e2f6d0d.png">

**Comment by adingeist** [comment]
Thanks that was an accident and also thanks for looking into it. 

### Update on the usage with my first post. 

What I proposed was unfortunately a breaking approach with the way some people set up tests. 

See the following:
<img width="493" alt="Screen Shot 2021-07-28 at 8 55 49 AM" src="https://user-images.githubusercontent.com/67285419/127388563-f549f256-d51c-4d71-8011-140e66579d18.png">



In this case, Partial<T> and DeepPartial<T> will throw the following typescript error, 

`Argument of type 'Partial<IUser>' is not assignable to parameter of type 'Partial<{ _id: Partial<{ generationTime: number; equals: Partial<{}>; getTimestamp: Partial<{}>; toHexString: Partial<{}>; }>; createdAt: Partial<{ toString: Partial<{}>; ... 42 more ...; [Symbol.toPrimitive]: Partial<...>; }>; ... 71 more ...; validateSync: Partial<...>; }>'.
  Types of property '$locals' are incompatible.
    Type 'Record<string, unknown> | undefined' is not assignable to type 'Partial<{ [x: string]: Partial<{}>; }> | undefined'.
      Type 'Record<string, unknown>' is not assignable to type 'Partial<{ [x: string]: Partial<{}>; }>'`

so everyone would have to go into their code and change document variables to be defined as DeepPartial<T>, which obviously is very bad.

**Comment by vkarpov15** [comment]
I figure we'll just pull top-level keys from `T` - that's better than having `any` since at least the key names will show up, if not necessarily the correct typings.
