### ISSUE TITLE
[refactor] get rid of defineKey `keys` parameter

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#10473]
The function `defineKey` takes a parameters `keys` that is unused, we should get rid of it, and verify that in the function usage we're passing the parameters correctly.

We could even make function use [named parameters](https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/) instead of passing parameters directly, that way we can add parameters or remove them without having to worry about current usage.

**Comment by vkarpov15** [comment]
I'm supportive of removing the unused parameters, but I'd be wary of using named parameters here. Unfortunately defineKey still runs when accessing nested paths, and given that it's already a slow function I don't want to add any more overhead.

**Comment by AbdelrahmanHafez** [comment]
That's interesting, I've never thought about the performance aspect of using named parameters.

The script below outputs a number around 8.5 millions on my machine, converting it to use regular parameters doesn't seem to change the result. Is there any example of where named parameters have worse performance than regular parameters?
```js
'use strict';
let counter = 0;

let numbersSum;
const stopAt = Date.now() + 1000;

while (Date.now() < stopAt) {
  numbersSum = addTwoNumbers({ x: 2, y: 2 });
  numbersSum++;

  counter++;
}

console.log(counter.toLocaleString());

// this should prevent the compiler from doing any tricks that flaw the experiment by not executing `addTwoNumbers` at all.
console.log(numbersSum); 

function addTwoNumbers({ x, y }) {
  return x + y;
}
```

**Comment by AbdelrahmanHafez** [comment]
That's interesting, I've never thought about the performance aspect of using named parameters.

According to the following benchmarks, it seems like regular parameters are 0.3~1% faster for [a function that adds two numbers](https://jsbench.me/kgkrmfcu6x/1), for [a function that does a little bit more than that](https://jsbench.me/kgkrmfcu6x/2), the results are identical, named parameters would randomly be 1% better than regular parameters.

I think even with the potential slight performance degradation, the development experience can allow for better performance optimization over the long run.
