### ISSUE TITLE
Document.id is typed as any rather than string

### ISSUE THREAD

**Issue by Samuel-Beslogic** [Automattic/mongoose#10482]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `mongoose@5.13.3` for the project I'm working on.

When doing `MyDocument.id`, I would expect id to be of type `string`, not `any`.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/mongoose/index.d.ts b/node_modules/mongoose/index.d.ts
index ae90b7a..180c27f 100644
--- a/node_modules/mongoose/index.d.ts
+++ b/node_modules/mongoose/index.d.ts
@@ -488,7 +488,7 @@ declare module 'mongoose' {
     getChanges(): UpdateQuery<this>;
 
     /** The string version of this documents _id. */
-    id?: any;
+    id?: string;
 
     /** Signal that we desire an increment of this documents version. */
     increment(): this;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vkarpov15** [comment]
See comments from https://github.com/Automattic/mongoose/pull/10248. As long as we support `extends Document`, `id` needs to be `any`, otherwise classes that `extends Document` won't be able to have custom `id` properties.
