### ISSUE TITLE
Setting expiry time doesn't delete document

### ISSUE THREAD

**Issue by Priyansh2001here** [Automattic/mongoose#10493]
*bug*

I want to automatically delete a document after 2 minutes.
This is my Schema
```
const tokensSchema = new mongoose.Schema({
    tokenType: {type: String},
    tokenValue: {type: String},
    userID: {type: mongoose.Schema.ObjectId, ref: 'UserSchema'},

}, {timestamps: true});

tokensSchema.index({createdAt: 1},{expireAfterSeconds: 120});

```

but it doesnt delete document.

node version: 16.5.0
mongoose version: 5.13.3

**Comment by perenSHERE** [comment]
This is a place to report issues with the npm not to ask your doughts please go do that on [StackOverflow](https://stackoverflow.com)

**Comment by vkarpov15** [comment]
`expiresAfterSeconds` creates a TTL index in MongoDB, and MongoDB only clears out expired documents every 60 seconds: https://docs.mongodb.com/manual/core/index-ttl/#timing-of-the-delete-operation . So it may be up to 3 minutes before a document that has `expireAfterSeconds = 120` is deleted from the database.
