### ISSUE TITLE
5.13.3 - Warning: Accessing non-existent property of module exports inside circular dependency

### ISSUE THREAD

**Issue by connorjburton** [Automattic/mongoose#10490]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Returns multiple errors such as below:

`Warning: Accessing non-existent property '$isMongooseMap' of module exports inside circular dependency`

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a repo that you can pull down and reproduce the issue. Just run `yarn && node index.js`

https://github.com/connorjburton/mongoose-circular-bug

I can see this has been fixed before here https://github.com/Automattic/mongoose/pull/10038 but it seems to have regressed.

**What is the expected behavior?**

Should not have warnings

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
$ node -v
v16.5.0
```

```
$ yarn why mongoose
yarn why v1.22.5
[1/4] Why do we have the module "mongoose"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "mongoose@5.13.3"
info Has been hoisted to "mongoose"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "3.72MB"
info Disk size with unique dependencies: "9.2MB"
info Disk size with transitive dependencies: "10.54MB"
info Number of shared dependencies: 13
```

```
$ yarn why mongodb
yarn why v1.22.5
[1/4] Why do we have the module "mongodb"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "mongodb@3.6.10"
info Reasons this module exists
   - "mongoose" depends on it
   - Hoisted from "mongoose#mongodb"
info Disk size without dependencies: "1.82MB"
info Disk size with unique dependencies: "2.86MB"
info Disk size with transitive dependencies: "3.17MB"
info Number of shared dependencies: 5
```

**Comment by IslandRhythms** [comment]
Put them in the same file and use schema.add(). See if that works.

**Comment by vkarpov15** [comment]
The issue is that `appointment.js` requires `appointmentRequest.js` and `appointmentRequest.js` requires `appointment.js`. When you have a circular `require()` like that, you'll get this warning.
