### ISSUE TITLE
[6.0 types] `mongoose.createConnection().asPromise` does not exist

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10508]
**Do you want to request a *feature* or report a *bug*?**
types

**What is the current behavior?**
function `.asPromise` (as documented in [`migrating_to_6.md`](https://github.com/Automattic/mongoose/blob/6.0/migrating_to_6.md)) does not exist in types (and `createConnection` still has `Connection & Promise<Connection>`)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

branch 6.0 (head 3b6e6b688704d8b058133eef311419ae9cfa25d6)

**Comment by vkarpov15** [comment]
Fixed, thanks for trying out the 6.0 branch :+1: Feel free to report any other issues you find.
