### ISSUE TITLE
Automatically Pull Document from Arbitrary Documents using an hex String property

### ISSUE THREAD

**Issue by hashweather** [Automattic/mongoose#10503]
I have a Model called Package that has a String property called user. The user string property is meant to hold an hex string equivalent of ObjectId for either of two documents. From Merchants or Customers.

Now I wish to automatically pull the user document along in a query as below, but I keep getting null
Here is my Package Model
```

const mongoose = require("mongoose");


const PackageSchema= new mongoose.Schema(
    {
        _id: mongoose.Schema.Types.ObjectId,
        description:String,
        user: String, //This will hold the hex string equivalent of any objectId from any document
    }
);
```
Here is snippet of How  a Package is created and tied to a merchant

```
const Merchant = require("../models/merchant");
const Customer = require("../models/customer");



let firstMerchant = await Merchant.findOne(..someConditions);

let firstPackage= new Package(
_id:ObjectUtils.generateObjectId(),
description:"Sample Description",
user:firstMerchant ._id.toHexString();
);
await firstPackage.save();
```

Here is snippet of How  a Package is created and tied to a customer
```
const Merchant = require("../models/merchant");
const Customer = require("../models/customer");

let firstCustomer= await Customer.findOne(..someConditions);

let secondPackage= new Package(
_id:ObjectUtils.generateObjectId(),
description:"Sample Description",
user:firstCustomer._id.toHexString();
);
await secondPackage.save();
```

Here is me trying to retrieve a package an also automatically pull the user model tied to that package
```
        let results = await Package.find().populate("user", null, null, ["Merchant", "Customer"]).limit(limit).skip(page == 0 || page == 1 ? 0 : (page * limit)); //So, the user field is expected to be automatically pulled along from either of Merchant or Customer dependending on which document has that user id hex string. 
```

But unfortunately user keeps coming back as null even though the Id is clearly in the Merchants Documents.

Please note that the type of user is not an ObjectId for flexibility sake. The type of user is a string that holds the hex string equivalent of ObjectId.

How can I solve this to make sure user should not return null if the hex string is clearly available in either of the documents?

Thank you.

**Comment by Kamikadze4GAME** [comment]
Hello @hashweather 

Please, provide complete script example with schema and model declarations.

**Comment by hashweather** [comment]
@Kamikadze4GAME I have updated the issue with more clarity. Thank you.

**Comment by vkarpov15** [comment]
The way I'd recommend doing this would be to store the associated model in the package document:

```javascript
const PackageSchema= new mongoose.Schema(
    {
        _id: mongoose.Schema.Types.ObjectId,
        description:String,
        user: {
          type: String,
          refPath: 'userModel' // <-- The `ref` is stored in the document's `userModel` property
        },
        userModel: { // `userModel` is a string that contains the model that the `user` property references
          type: String,
          enum: ['Customer', 'Merchant']
        }
    }
);
```

You should then be able to populate using `await Package.find().populate("user")`, without needing to specify the model. Does that help?

Otherwise, Mongoose doesn't currently support populating using an array of models where you try populating using each model in order. We may consider adding that in the future.

**Comment by vkarpov15** [comment]
Also this is related to #6608
