### ISSUE TITLE
ConnectOptions does not include useNewUrlParser and useUnifiedTopology

### ISSUE THREAD

**Issue by mathletedev** [Automattic/mongoose#10500]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

In TypeScript, the options `useNewUrlParser` and `useUnifiedTopology` cannot be set. When running the program, this produces the warnings

```
(node:818) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:818) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
import "dotenv-safe/config";
import { connect } from "mongoose";

(async () => {
	await connect(process.env.MONGO_URI!, {
		dbName: "example",
		useCreateIndex: true
	});
})();
```

tsconfig.json

```json
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
		"outDir": "dist",
		"strict": true,
		"skipLibCheck": true,
		"removeComments": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"resolveJsonModule": true
	},
	"include": ["src/**/*.ts"],
	"exclude": ["node_modules"]
}
```

**What is the expected behavior?**

`useNewUrlParser` and `useUnifiedTopology` should be options in `mongoose.connect()`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 16.5.0
Mongoose: 5.13.3
MongoDB: 4.0.1

**Comment by IslandRhythms** [comment]
```
import * as mongoose from 'mongoose';

const schema = new mongoose.Schema({
  firstName: String,
  lastName: String,
});



const Robot = mongoose.model('Robot', schema);


(async () => {
  await mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
  const doc = await Robot.create({firstName: 'Bender', lastName: 'Rodriguez'});
  console.log(doc);
  mongoose.disconnect();
})();
```

**Comment by mathletedev** [comment]
Huh. When i try using `useNewUrlParser`, it results in this error:
![image](https://user-images.githubusercontent.com/63214683/127592096-3313ee2c-da98-46e4-b22b-37c18bd289ac.png)

**Comment by mathletedev** [comment]
Here are my dependencies, in case you need them:
```json
	"dependencies": {
		"@typegoose/typegoose": "^7.6.3",
		"apollo-server-express": "^2",
		"class-validator": "^0.13.1",
		"dotenv-safe": "^8.2.0",
		"express": "^4.17.1",
		"graphql": "^15.5.1",
		"mongodb": "^4.0.1",
		"mongoose": "^5.13.3",
		"reflect-metadata": "^0.1.13",
		"type-graphql": "^1.1.1"
	},
	"devDependencies": {
		"@types/express": "^4.17.13",
		"@types/node": "^16.4.3",
		"nodemon": "^2.0.12",
		"typescript": "^4.3.5"
	}
```

**Comment by mathletedev** [comment]
I think it's related to https://github.com/Automattic/mongoose/issues/10506

**Comment by mathletedev** [comment]
I haven't tried it in JavaScript yet, but do you think it's possible to add the options directly into `index.d.ts`?

**Comment by mathletedev** [comment]
In mongodb 4.x, those options were removed https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md

**Comment by PankajSharma3** [comment]
Use this 
await mongoose.connect(`mongodb+srv://username:password@cluster0.3r4pbup.mongodb.net/employee`, { auth: { username: MONGODB_USERNAME, password: MONGODB_PASSWORD } });

Instead of
await mongoose.connect(`mongodb+srv://username:password@cluster0.3r4pbup.mongodb.net/employee`, { useNewUrlParser: true, useUnifiedTopology: true });

The above is only supported below the mongodb 4.0.0 version
