### ISSUE TITLE
doc.save() returns document with empty array in a field referencing another collection IF that collection's model has a unique slug

### ISSUE THREAD

**Issue by jcmpes** [Automattic/mongoose#10517]
5.3.14

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I save a new document (course A) in a collection (collection "courses") passing in for one the fields (field "lessons") an array containing a reference to the id of another document (lesson B) from a different collection (collection "lessons"). And I do this in order to establish a relationship and reference the lesson B inside de document of the course A. The object returned by the save() operation, object A, has an empty array in the field "lessons" where it is supposed to have an array with the ObjectId of document B from collection Y.

Below more details on how a slight change in the model fixes the problem. It's nonsense for me so I thought I might have encountered a bug. 

**If the current behavior is a bug, please provide the steps to reproduce.**
In my current setup. Everything woks as expected without the { unique:true } property on the slug field of the model Lesson. But when adding this property to the model Lesson, then the problems shows up, and the object returned by save() contains an empty array of references.

EVERYTHING WORKS:
slug: { type: String, slug: 'title' },

PROBLEM SHOWS UP:
slug: { type: String, slug: 'title', unique: true },

https://gist.github.com/36ec46fa7b0f24f2b93a3a7111c86578.git

**What is the expected behavior?**
To hace document A saved and including in its fuield "lessons" an array with the ObjectId of document B.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs v14.15.3
Mongoose 5.3.14
MongoDB 4.4.6 Enterprise on MongoDB Atlas

**Comment by IslandRhythms** [comment]
```
'use strict';

const mongoose = require('mongoose');
// Import the slug package
const slug = require('mongoose-slug-updater');
// Initialize
mongoose.plugin(slug);

const courseSchema = mongoose.Schema(
  {
    title: { type: String, unique: true, index: true },
    slug: { type: String, slug: 'title', unique: true },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
    },
    price: { type: Number, required: true },
    video: String,
    description: String,
    content: String,
    image: String,
    lessons: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Lesson',
      },
    ],
  },  
  { timestamps: true },
);

courseSchema.statics.list = async function (filter, skip, limit, sort) {
  const query = Course.find(filter).populate('user').populate('category');
  query.sort(sort);
  query.skip(skip);
  query.limit(limit);

  return await query.exec();
};

const Course = mongoose.model('Course', courseSchema);

const lessonSchema = mongoose.Schema(
    {
      title: { type: String },
      slug: { type: String, slug: 'title' },
      image: String,
      video: String,
      description: String,
      content: String,
    },
    { timestamps: true },
  );
  
  const Lesson = mongoose.model('Lesson', lessonSchema);
  


async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: true
  });

  await mongoose.connection.dropDatabase();
  const entry = await Lesson.create({ title: 'Hello', slug: 'world' });
  console.log(entry);
  const course = new Course({title: 'test', slug: 'world', price: 2});
  course.lessons.push(entry._id);
  course.save();
  console.log(course);
  
}
  
test();
```

**Comment by jcmpes** [comment]
That script from @IslandRhythms was the proof that there is no bug as I had suggested.

As I could not find an explanation to such a strange behavior I thought there could be a bug somewhere in the library and **the bug was actually in my code**. A very basic problem of asynchronous operations.

**Here why:**
When adding the { unique: true } property to the Lesson model, for every lesson it takes a tiny little more time to be saved as all lessons have to be queried in order to generate a slug that is unique. And that extra time, not being managed asynchronously was responsible for not having the saved lessons inside the array of lessons of the course eventually saved at the end. Because I was not doing the save() asynchronously after the lessons were saved in the first place.

It was my bad. I am sorry about the issue. And I am really thankful. Thanks a lot @IslandRhythms, I have learned a lot from the way you created a simple repro script that has really helped me out understanding my bug and how to identify, track and report a bug in case it were necessary.

Best regards from Ibiza 👋

**Comment by vkarpov15** [comment]
No worries. Here's a little bit more info about the `unique` option, why it isn't a validator, and why that matters:

https://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator
https://masteringjs.io/tutorials/mongoose/unique
https://chanwingkeihaha.medium.com/do-you-know-the-unique-option-is-not-a-validator-in-mongoose-85267fb1a085
