### ISSUE TITLE
Bug: `Named export 'Schema' not found.` (TypeScript)

### ISSUE THREAD

**Issue by evolutionleo** [Automattic/mongoose#10513]
**Do you want to request a *feature* or report a *bug*?**
`bug`

**What is the current behavior?**
When importing mongoose using `import { Schema, model } from 'mongoose'`,
TypeScript shows no errors and intellisense works just fine, but
The program errors out with this :
```
import { Schema, model, connect } from 'mongoose';
         ^^^^^^
SyntaxError: Named export 'Schema' not found. The requested module 'mongoose' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mongoose';
const { Schema, model, connect } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```
If I replace the importing line with `import mongoose from 'mongoose'` as suggested in the error message, TypeScript shows `Module "mongoose" has no default export`, while the code runs just fine

And if I replace it with `import * as mongoose from 'mongoose'` instead, it produces a whole new set of errors, basically it is not at all equivalent to `import {...} from 'mongoose'`

so,
**steps to reproduce.**
1) inside package.json: `"type": "module"`
2) tsconfig.json:
```json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "ESNext"
    }
}
```
3) copy the code from the official tutorial at https://mongoosejs.com/docs/typescript.html
4) compile
5) run

**What is the expected behavior?**

Running without errors ("bill@initech.com" printed in the console)
OR
At least throwing errors on the TypeScript side that the imports do not exist

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: v5.13.4
MongoDB: v4.4.6
NodeJS: v16.5.0

**Comment by thiagokisaki** [comment]
Try enabling [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) in `tsconfig.json`:
```json
{
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "ESNext",
        "esModuleInterop": true
    }
}
```

**Comment by evolutionleo** [comment]
Well, the initial syntax from the tutorial still does not work (the error message is the same as before), however now TypeScript doesn't yell at me anymore for `import mongoose from 'mongoose'`

Thank you, @thiagokisaki. This is a lot better, even though the issue is not fully resolved

**Comment by IslandRhythms** [comment]
Do `import * as mongoose from 'mongoose'`

**Comment by evolutionleo** [comment]
> Do `import * as mongoose from 'mongoose'`

I mentioned in the issue that it is not equivalent to `import {...} from 'mongoose'` and creates new problems (namingly, `'Schema' is not a constructor`)

**Comment by IslandRhythms** [comment]
Provide the script that is producing the error

**Comment by evolutionleo** [comment]
@IslandRhythms 
```ts
// import { Schema, model, connect } from 'mongoose';
// import mongoose from 'mongoose';
import * as mongoose from 'mongoose';
const { Schema, model, connect, version } = mongoose;

// 1. Create an interface representing a document in MongoDB.
interface User {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const UserModel = model<User>('User', schema);

run().catch(err => console.log(err));

async function run(): Promise<void> {
  // 4. Connect to MongoDB
  await connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const doc = new UserModel({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await doc.save();

  console.log(doc.email); // 'bill@initech.com'
}
```

**Comment by IslandRhythms** [comment]
works fine for me

**Comment by vkarpov15** [comment]
@evolutionleo which TypeScript version?

**Comment by evolutionleo** [comment]
Not at home rn, but I believeee it's 4.2

**Comment by mathletedev** [comment]
Might this help? https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

**Comment by evolutionleo** [comment]
@vkarpov15 Version 4.3.2

**Comment by evolutionleo** [comment]
> Might this help? https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

@mathletedev it does not unfortunately

**Comment by evolutionleo** [comment]
> works fine for me

@IslandRhythms even if the `import * as mongoose from 'mongoose'` version works (which it doesn't for me), or the version with `import mongoose from 'mongoose'` + `"esModuleInterop": true`, the problem still remains with the code from the tutorial failing

**Comment by IslandRhythms** [comment]
There has to be a problem with your set up then. It's the only explanation at the moment

**Comment by evolutionleo** [comment]
What could be the problem? I'm using the latest versions of everything as far as I'm aware

**Comment by mathletedev** [comment]
Could you try using this tsconfig (temporarily) and see if it works?

```json
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"lib": ["dom", "es6", "es2017", "esnext.asynciterable"],
		"outDir": "dist",
		"strict": true,
		"skipLibCheck": true,
		"removeComments": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"strictPropertyInitialization": false,
		"resolveJsonModule": true
	},
	"include": ["src/**/*.ts"],
	"exclude": ["node_modules"]
}
```

You might need to change the include to your project's directory

**Comment by drdDavi** [comment]
I am facing this exact problem, even the example breaks giving me:

`Untyped function calls may not accept type arguments`

**Comment by vkarpov15** [comment]
@drdDavi please open a new issue and follow the issue template.
