### ISSUE TITLE
limit and perDocumentLimit props 

### ISSUE THREAD

**Issue by mustafaKamal-fe** [Automattic/mongoose#10523]
**What is the current behavior?**
As per docs mentions [HERE](https://mongoosejs.com/docs/populate.html#limit-vs-perDocumentLimit), `limit and perDocumentLimit` have distinct behaviors. However, i tried running both and always receive the same results as if they have the same behavior.

**What is the expected behavior?**
Consider this snippet from the docs: 

```js
const stories = Story.find().populate({
  path: 'fans',
  options: { limit: 2 }
});
```
if `fans.length` was 2, we would not be able to populate any docs.

```js
 const stories = await Story.find().populate({
  path: 'fans',
  // Special option that tells Mongoose to execute a separate query
  // for each `story` to make sure we get 2 fans for each story.
  perDocumentLimit: 2
});
```
Now the snippet above is supposed to solve this problem and execute seperate queries on each doc in order to populate.

**Issue** 
The weired thing is that, using any of these options returns the expected docs number after populating the path, As if the 
two options make no difference. Here is my code: 

```ts
let limit = 2;
let doc1 = await Writer.findById(id)
			.populate({
				path: 'books',
				limit,
			})
			.populate('identity')
			.lean()
			.exec();

let doc 2 = await Writer.findById(id)
			.populate({
				path: 'books',
				perDocumentLimit: limit,
			})
			.populate('identity')
			.lean()
			.exec();
``` 
Indeed i have used the code above in some `expressjs` app and did not include parts that have nothing to do with mongoose iteself and only included this for breivety.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`mongoose` 5.13.2
`node` 12.x
`mongoDb` 4.0.1
`@tsconfig/node12/tsconfig.json`

**Comment by vkarpov15** [comment]
What does your data look like?

**Comment by mustafaKamal-fe** [comment]
:one:  Schemas
```ts
// Writer Schema
const WriterSchema = new mongoose.Schema(
	{
		identity: String,
		books: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Book' }],
	},
	defaultSchemConfig({ withId: true })
);
const model = mongoose.models.person || mongoose.model('Writer', WriterSchema);

// Book Schema
const BookSchema = new mongoose.Schema(
	{
		name: { type: String, required: true },
		pDate: { type: Date, required: true },
		writer: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Person',
			required: true,
		},
		bookshop: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Bookshop',
			required: true,
		},
	},
	defaultSchemConfig({ withId: true })
);
const model = mongoose.models.book || mongoose.model('Book', BookSchema);
```
:two: Hndlers
```ts
// `expressjs` route handler
import { Request, RequestHandler, Response } from 'express';

const withLimitOption: RequestHandler = async (
	req: Request,
	res: Response
) => {
	
	const { id } = req.query;
	const { limit } = req.params;

	// Populated by limit value
	if (limit) {
		let doc = await Writer.findById(id)
			.populate({
				path: 'books',
				limit,
			})
			.populate('identity')
			.lean()
			.exec();

		res.status(200);
		res.json({
			writer: doc
		});
		res.end();
	}
};
```
```ts
// `expressjs` route handler
const withPerDocumentLimitOption: RequestHandler = async (
	req: Request,
	res: Response
) => {
	
	const { id } = req.query;
	const { limit } = req.params;
	if (limit) {
		let doc = await Writer.findById(id)
			.populate({
				path: 'books',
				perDocumentLimit: parseInt(limit),
			})
			.populate('identity')
			.lean()
			.exec();

		res.status(200);
		res.json({
			writer: doc
		});
		res.end();
	}
};
```

**Comment by vkarpov15** [comment]
@mustafaKamal-fe I mean what do the documents in the database look like? Hard to repro this without the actual data in the db.

**Comment by mustafaKamal-fe** [comment]
I hope this is the best way to show you how the data looks like in my db instance: 
> Okay, So  I am trying to query from the writer collection. Clearly i have two paths of type `mongoose.Schema.types.ObjectId`, > However for the sake of tis example, i am only trying to populate the `books` path as it is an array of documents.

![mongodb-example-data](https://user-images.githubusercontent.com/54776055/128646224-38cbfc4c-6deb-4a73-9999-f72ced4ece12.png)

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');

const Person = mongoose.model('Person', mongoose.Schema({
    name: String
  }));
  
  // `ref` tells Mongoose populate what model to query
  const Movie = mongoose.model('Movie', mongoose.Schema({
    title: String,
    director: [{
      type: mongoose.ObjectId,
      ref: 'Person'
    }],
    actors: [{
      type: mongoose.ObjectId,
      ref: 'Person'
    }]
  }));

async function run() {
    await mongoose
    .connect("mongodb://localhost:27017/mongooseDatabase", {
      useNewUrlParser: true,
      useCreateIndex: true,
      useFindAndModify: false,
      useUnifiedTopology: true,
    })
    .then(() => console.log("MongoDB Connected!"))
    .catch((error) => console.log("There was an error: ", error));
    await mongoose.connection.dropDatabase();

    const people = await Person.create([
        { name: 'James Cameron' },
        { name: 'Arnold Schwarzenegger' },
        { name: 'Linda Hamilton' },
        { name: 'Test Testerson' }
      ]);

      await Movie.create({
        title: 'Terminator 2',
        director: [people[0]._id, people[3]._id],
        actors: [people[1]._id, people[2]._id]
      });

      let movie = await Movie.findOne().populate({path: 'director', options: {limit: 2}});
      // let movie = await Movie.findOne().populate({path: 'director', perDocumentLimit: 2 });
      console.log(movie.director.length);
      console.log(movie.director);
}

run();
```

**Comment by mustafaKamal-fe** [comment]
> ```
> 
> const mongoose = require('mongoose');
> 
> 
> 
> const Person = mongoose.model('Person', mongoose.Schema({
> 
>     name: String
> 
>   }));
> 
>   
> 
>   // `ref` tells Mongoose populate what model to query
> 
>   const Movie = mongoose.model('Movie', mongoose.Schema({
> 
>     title: String,
> 
>     director: [{
> 
>       type: mongoose.ObjectId,
> 
>       ref: 'Person'
> 
>     }],
> 
>     actors: [{
> 
>       type: mongoose.ObjectId,
> 
>       ref: 'Person'
> 
>     }]
> 
>   }));
> 
> 
> 
> async function run() {
> 
>     await mongoose
> 
>     .connect("mongodb://localhost:27017/mongooseDatabase", {
> 
>       useNewUrlParser: true,
> 
>       useCreateIndex: true,
> 
>       useFindAndModify: false,
> 
>       useUnifiedTopology: true,
> 
>     })
> 
>     .then(() => console.log("MongoDB Connected!"))
> 
>     .catch((error) => console.log("There was an error: ", error));
> 
>     await mongoose.connection.dropDatabase();
> 
> 
> 
>     const people = await Person.create([
> 
>         { name: 'James Cameron' },
> 
>         { name: 'Arnold Schwarzenegger' },
> 
>         { name: 'Linda Hamilton' },
> 
>         { name: 'Test Testerson' }
> 
>       ]);
> 
> 
> 
>       await Movie.create({
> 
>         title: 'Terminator 2',
> 
>         director: [people[0]._id, people[3]._id],
> 
>         actors: [people[1]._id, people[2]._id]
> 
>       });
> 
> 
> 
>       let movie = await Movie.findOne().populate({path: 'director', options: {limit: 2}});
> 
>       // let movie = await Movie.findOne().populate({path: 'director', perDocumentLimit: 2 });
> 
>       console.log(movie.director.length);
> 
>       console.log(movie.director);
> 
> }
> 
> 
> 
> run();
> 
> ```

@IslandRhythms hi, is this a suggested solution to the issue?

**Comment by IslandRhythms** [comment]
No, this is confirmation of what you are experiencing

**Comment by vkarpov15** [comment]
I took a closer look and this looks like expected behavior. The reason why the output is always the same is because you're using `Writer.findById().populate()`, which always returns at most 1 document. `perDocumentLimit` can only be different if you use `Writer.find().populate()`: `perDocumentLimit` would execute a separate populate query for every document that `await Writer.find()` returns.

Are you experiencing some sort of issue, or is this issue more just a concern that `perDocumentLimit` doesn't seem to do anything different in your case?
