### ISSUE TITLE
SchemaDate types not matching jsdoc types / accepted types

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10529]
**Do you want to request a *feature* or report a *bug*?**
types

**What is the current behavior?**
SchemaDate jsdoc & examples list that accepted types are `Number | String`
https://github.com/Automattic/mongoose/blob/80245edf5aeab304411681035f7f4153dbd2b692/lib/schema/date.js#L118-L157
but types say its `number | Date` (not `number | string`)
https://github.com/Automattic/mongoose/blob/c36bd644ca33bef4bcc49ce59f046ad0f0a0fde4/index.d.ts#L1660-L1661

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.13.5

---

PS: is it correct to not include `SchemaDate` (and others) in the documentation? there i could only find `SchemaDateOptions` under `API` (and `SchemaDateOptions` does not have the examples / accepted types from `SchemaDate`)

**Comment by vkarpov15** [comment]
Re: including `SchemaDate` in documentation, that's worth discussing more. We explicitly exclude them because we don't want to imply that users should be creating `SchemaDate` instances - most users shouldn't have to be aware of `SchemaDate`.
