### ISSUE TITLE
[Typescript Documentation] Document methods without extending Document class

### ISSUE THREAD

**Issue by mjfwebb** [Automattic/mongoose#10520]
**Do you want to request a *feature* or report a *bug*?**

A feature (clarification of documentation)

**What is the current behaviour?**

https://mongoosejs.com/docs/typescript.html describes extending Mongoose's Document class as not recommended. I would like some clarification on how best to use document methods such as `.save()` when passing the document around in code.

For example, imagine I have the following (mostly pseudo-code):

```
// In a schema file
export interface User {
  name: string;
}

const findUserByNameAndDoSomething = async (name: string) => {
  const user = await UserModel.findOne({ name }).exec();
  assert(user, 'Unable to find a user with this name');
  doSomethingToUser(user);
}

const doSomethingToUser = async (user: User) => {
  user.name = 'something-new';
  await user.save();
}
```

The current recommendation is not to extend Document, but not doing so means I will receive the error `Property 'save' does not exist on type 'User'`.

What is the recommended action here? Is it that I must add my own `save` method to the `User` interface? Would I then need to do that for all other document methods like `update` and `toObject`?

Or is it something more fundamental in the way I am using Mongoose and passing around the user incorrectly?

Thanks in advance.

**Comment by hasezoey** [comment]
from what i know, it is (also in the unofficial types) `type YourDocument = mongoose.Document & YourInterface` and for models its `type YourModel = mongoose.Model<YourDocument>` (but also `type YourModel = mongoose.Model<YourInterface>` works)

**Comment by vkarpov15** [comment]
I agree with @hasezoey . We recommend passing the "raw document interface" to `mongoose.model()`, and defining a separate type using `Document &`

```typescript
interface User {
  name: string;
  age: number;
}

interface UserDocument = Document<mongoose.ObjectId> & User;

const UserModel = mongoose.model<User>('User', new Schema<User>({ name: String, age: Number }));
```

**Comment by mjfwebb** [comment]
Thanks for the response @vkarpov15.

Just one last point of clarity. I would then be using `UserDocument` as the function parameter in the example I provided?

```
interface User {
  name: string;
  age: number;
}

interface UserDocument = Document<mongoose.ObjectId> & User;

const UserModel = mongoose.model<User>('User', new Schema<User>({ name: String, age: Number }));

const findUserByNameAndDoSomething = async (name: string) => {
  const user = await UserModel.findOne({ name }).exec();
  assert(user, 'Unable to find a user with this name');
  doSomethingToUser(user);
}

const doSomethingToUser = async (user: UserDocument) => {
  user.name = 'something-new';
  await user.save();
}
```

**Comment by hasezoey** [comment]
@mjfwebb if you mean the function `doSomethingToUser`, then yes, this would be correct if you want the *document* as an argument (not if you want a *POJO* as an argument)

**Comment by mjfwebb** [comment]
@hasezoey Thanks. I have a better understanding now. I appreciate your time.
