### ISSUE TITLE
Put ESLint rules in own file to reduce package size

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10528]
**Do you want to request a *feature* or report a *bug*?**
enhancement / chore

**What is the current behavior?**
i know the size reduction is not much, but still something that does not need to be included in the package.json when shipped (at least from what i know)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.13.5 / 6.0 (head 33bfeb66febab44afad46ed259a9b64dba0684eb)

---

PS: does `History.md` need to also be included in the shipped package?

**Comment by vkarpov15** [comment]
History.md will be removed in future releases, there was a bug in npm 6 that made it impossible to ignore `History.md` when running `npm publish`.

**Comment by Uzlopak** [comment]
@AbdelrahmanHafez 
@vkarpov15 
This can be closed.
