### ISSUE TITLE
[6.0] undocumented change in "validate" function for references

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10522]
**Do you want to request a *feature* or report a *bug*?**
undocumented change / bug

**What is the current behavior?**
in mongoose 5.13.5 the first parameter to a `validate` function for a `ref` property was the document itself
in mongoose 6.0 (head 33bfeb66febab44afad46ed259a9b64dba0684eb) the first parameter to `validate` function for a `ref` property is just the objectid directly

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduction repository: https://github.com/typegoose/typegoose-testing/tree/mongooseRefValidate
Use branch `mongooseRefValidate`

Steps to reproduce (Linux):
- `git clone https://github.com/typegoose/typegoose-testing/tree/mongooseRefValidate`
- `git checkout -b mongooseRefValidate origin/mongooseRefValidate`
- `git reset --hard HEAD~1` (go to the mongoose 5.13.5 commit)
- `yarn install`
- `yarn run run` (have a mongodb instance running locally on port `27017`, or change the connect line)
- look at the result
- `git reset --hard origin/mongooseRefValidate` (go to the 6.0 commit)
- `yarn install`
- `yarn run run:directly` (use ts-node because it ignores the typescript error, because 6.0 does not have the changes for #10504 merged)
- look at the result

<details>
<summary>TL;DR: the output of the steps above</summary>

Output from 5.13.5:

```
yarn run v1.22.10
$ yarn run build && node lib/test.js
$ tsc
arg1 { _id: 610555f50ce8361e51d60838, dummy: 'hello', __v: 0 } object true false
Done in 2.81s.
```

Output from 6.0 (head 33bfeb66febab44afad46ed259a9b64dba0684eb):

```
yarn run v1.22.10
$ ts-node ./src/test.ts
arg1 new ObjectId("610556719380303ef174ba53") object false true
Done in 3.05s.
```

context for output: https://github.com/typegoose/typegoose-testing/blob/7b14da54590f3bdd6f7713405bfd2cf62a100658/src/test.ts#L6-L15

</details>

i at least could not find a reference to this behavior change in [`migrate_to_6.md`](https://github.com/Automattic/mongoose/blob/6.0/migrating_to_6.md)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
based on 5.13.5 behavior
happens in 6.0 (head 33bfeb66febab44afad46ed259a9b64dba0684eb)

**Comment by vkarpov15** [comment]
@hasezoey we'll add this to the docs, but I believe this is an intentional change in #8042.

Do you think we should undo this change? We think passing the depopulated path to validators is a better pattern since it reduces the number of cases a validator needs to handle, but definitely open to discussion.

**Comment by hasezoey** [comment]
> Do you think we should undo this change?

for me personally, there is no need to undo it

> We think passing the depopulated path to validators is a better pattern since it reduces the number of cases a validator needs to handle, but definitely open to discussion.

i actually think this is the better way (reducing the cases it needs to handle), but i just found that the behavior changed without any mention in the `migrate_to_6` file, so i made an full issue about it
