### ISSUE TITLE
[Types] Add proper types for "Schema.index"

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10530]
**Do you want to request a *feature* or report a *bug*?**
types

**What is the current behavior?**
for function `(new Schema()).index` definition everything is `any`, at least `option` should be assigned to `IndexOptions`

and `IndexOptions` should extend / use from `mongodb`'s `IndexOptions`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.13.5

**Comment by Raader** [comment]
#10538
