### ISSUE TITLE
Error thrown when trying to transpile to javascript

### ISSUE THREAD

**Issue by ekow-mensah** [Automattic/mongoose#10539]
When I try to transpile the Typescript code to Javascript using the tsc -p . command, I get these errors. 

src/models/Captain.ts(118,3): error TS2345: Argument of type 'Schema<Document<any, any, any>, Model<any, any, any>, undefined, any>' is not assignable to parameter of type 'Schema<CaptainDoc, CaptainModel, undefined, unknown>'.
  Types of property 'plugin' are incompatible.
    Type '(fn: (schema: Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<...>' is not assignable to type '(fn: (schema: Schema<CaptainDoc, Model<CaptainDoc, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<CaptainDoc, CaptainModel, undefined, unknown>'.
      Types of parameters 'fn' and 'fn' are incompatible.
        Types of parameters 'schema' and 'schema' are incompatible.
          Type 'Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>' is not assignable to type 'Schema<CaptainDoc, Model<CaptainDoc, {}, {}>, undefined, {}>'.
            Types of property 'static' are incompatible.
              Type '{ (name: string, fn: (this: Model<Document<any, any, any>, {}, {}>, ...args: any[]) => any): Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>; (obj: { ...; }): Schema<...>; }' is not assignable to type '{ (name: string, fn: (this: Model<CaptainDoc, {}, {}>, ...args: any[]) => any): Schema<CaptainDoc, Model<CaptainDoc, {}, {}>, undefined, {}>; (obj: { ...; }): Schema<...>; }'.
                Types of parameters 'fn' and 'fn' are incompatible.
                  The 'this' types of each signature are incompatible.
                    Type 'Model<Document<any, any, any>, {}, {}>' is not assignable to type 'Model<CaptainDoc, {}, {}>'.
                      The types returned by 'count(...).$where(...).exec()' are incompatible between these types.
                        Type 'Promise<Document<any, any, any>[]>' is not assignable to type 'Promise<CaptainDoc[]>'.
                          Type 'Document<any, any, any>[]' is not assignable to type 'CaptainDoc[]'.
src/models/Customer.ts(64,3): error TS2345: Argument of type 'Schema<Document<any, any, any>, Model<any, any, any>, undefined, any>' is not assignable to parameter of type 'Schema<CustomerDoc, CustomerModel, undefined, unknown>'.
  Types of property 'plugin' are incompatible.
    Type '(fn: (schema: Schema<Document<any, any, any>, Model<Document<any, any, any>, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<...>' is not assignable to type '(fn: (schema: Schema<CustomerDoc, Model<CustomerDoc, {}, {}>, undefined, {}>, opts?: any) => void, opts?: any) => Schema<CustomerDoc, CustomerModel, undefined, unknown>'.
      Types of parameters 'fn' and 'fn' are incompatible.

I would really appreciate some help on how to solve this. I have updated mongoose to 3.15.3 and set the @types/mongodb to 3.6.10 in the package-lock.json but then still I get these errors.

**Comment by vkarpov15** [comment]
Please provide code samples and follow the issue template, this report doesn't have enough information for us to understand what's going on here
