### ISSUE TITLE
Bug: SchemaDefinitionType Validation not working for Schema.Types.ObjectId[]

### ISSUE THREAD

**Issue by EricLiuCY** [Automattic/mongoose#10533]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/35042747/127824808-7bc34069-4fe5-4241-8db7-ef90e7a5cb9e.png)
![image](https://user-images.githubusercontent.com/35042747/127824736-8c9ebf89-7b07-45f3-9c1f-157c9cf3849e.png)
![image](https://user-images.githubusercontent.com/35042747/127824773-b2cf7d68-c461-49dc-b82e-ea910529d6b0.png)

I am trying to use SchemaDefinitionType ( the third type parameter for Schema) to validate my Schema. It works fine for primitive types, E.G. Numbers String Date. However, when I try to do either an Array of ObjectIds, or an Array of SubDocuments, it gives me type compliance errors.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
{
    "compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "resolveJsonModule": true,
      "target": "es6",
      "noImplicitAny": true,
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "dist",
      "baseUrl": ".",
      "paths": {
        "*": ["node_modules/*"]
      }
    },
    "include": ["./src/**/*", "test"]
  }
  
```
**What is the expected behavior?**

It should validate my schema successfully. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
    "@types/node": "^15.6.1",
    "mongoose": "^5.12.12",

**Comment by IslandRhythms** [comment]
Please include the script causing the error or a simplified version
