### ISSUE TITLE
pre save hook this.collection and this.constructor.modelName are undefined

### ISSUE THREAD

**Issue by rkreienbuehl** [Automattic/mongoose#10548]
**Do you want to request a *feature* or report a *bug*?**

No

**What is the current behavior?**

In pre save hook I need to retrieve the model name and use the collection to get the old Object from the database. To do so I want to use `await this.collection.findOne()` and `this.constructor.modelName`, but both, `this.collection` and `this.constructor.modelName` are `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

``` json
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {},
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ]
  }
}

```

**What is the expected behavior?**

`this.constructor.modelName` should give me the model name and `this.collection` should give the collection of the document of which the pre save hook was triggered for.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v12.19.0
mongoose: 5.13.3
MongoDB: 4.2.14

**Comment by IslandRhythms** [comment]
Please include a script that demonstrates this issue

**Comment by vkarpov15** [comment]
Without a code sample, we won't be able to repro this. My best guess is that you're using an arrow function for the pre save hook, which won't work.

**Comment by rkreienbuehl** [comment]
I don't use arrow functions. My middleware looks like this:
``` ts
export function plugin(schema: mongoose.Schema) {
  schema.pre(
    'save',
    async function (this: mongoose.Document, next: mongoose.HookNextFunction) {
      const context: IGlobalContext = cls.get('request-context');

      const oldRec = await this.collection.findOne({ _id: this._id });
      const modelName = (this.constructor as any).modelName;

      if (modelName === 'History') {
        next();
      } else {
        if (oldRec) {
          await addChangeEntry(context, modelName, oldRec, this.getChanges());
        } else {
          await addInsertEntry(context, this._id, modelName);
        }

        next();
      }
    }
  );
```

**Comment by vkarpov15** [comment]
Are you connected to Mongoose when you're running `save()`?

Also, why are you using `this.collection.findOne()` rather than `this.constructor.findOne()`?

**Comment by rkreienbuehl** [comment]
Yes, mongoose is connected. What is strange is, that the pre hook is called multiple times on the same `save()`. Also what I figured out so far, is that the plugin works fine if I add it as a schema plugin rather than a global plugin, but that would be not an option, since we need it on all schemas.

**Comment by rkreienbuehl** [comment]
Ok, after some more tests I figured out that the `save()` is executed multiple times because I save a document with sub documents that are defined by a separate schema. These schemas don't have a related model, so there is no `modelName` and no `collection`.
As I found this out, I also noticed, that `this.getChanges()` always has the complete sub document in it. Is there a way to get the single changes from the sub documents without always getting the whole sub document in the changes (or do not get have the whole sub document when nothing changed on them)?

**Comment by vkarpov15** [comment]
Re: embedded documents, that makes sense, embedded documents don't have an associated collection, so I'd recommend your pre save middleware skip subdocuments.

Re: "`this.getChanges()` always has the complete subdoc", that isn't correct. For example, the below script outputs "{ '$set': { 'sub.name': 'Ted' } }"

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const subSchema = Schema({ name: String, age: Number });
  const schema = Schema({ sub: subSchema });
  const Test = mongoose.model('Test', schema);

  await Test.create({ sub: { name: 'Bill', age: 30 } });

  const doc = await Test.findOne();
  doc.sub.name = 'Ted';

  console.log(doc.getChanges());
  await process.exit(0);
}
```

However, `getChanges()` will contain the entire subdoc if you're overwriting the entire subdoc, like if you did `doc.sub = { name: 'Ted', age: 30 }` in the above example. If you want to track individual changes on the subdocument, you should assign properties to the subdocument rather than overwrite them, like `Object.assign(doc.sub, { name: 'Ted', age: 30 })`. Does that help?

**Comment by rkreienbuehl** [comment]
Thanks, have to check, but we have used `Object.assign()`, so think this will be the problem.
