### ISSUE TITLE
Problems with Schema.query's type definition

### ISSUE THREAD

**Issue by GCastilho** [Automattic/mongoose#10545]
bug

**What is the current behavior?**

The type definition for the `Schema.query` doesn't seems to be working

**What is the expected behavior?**

If I define a custom query for a schema, the `this` type is resolved to `any`. If I try to provide a custom `this` type I get a "Type 'T' is not assignable to type...":

```typescript
// Type 'T' is not assignable to type 'Query<any, any, {}, any>'.ts(2322)
SomeSchema.query.someQuery = function(
    this: QueryWithHelpers<ResultType, DocType>
): QueryWithHelpers<ResultType, DocType> {
	return ...
}
```

This previously worked (when using @types/mongoose) defining `this` to `DocumentQuery<ResultType, DocType>` although they didn't have a type for the query property

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

5.13.5

**Comment by vkarpov15** [comment]
You're right that `this` is `any` by default in query helpers, we're working on that.

But, in the meantime, the below script seems to compile fine. Can you please provide your tsconfig and check whether the below script compiles on your setup?

```ts
import { Schema, model, Document, Types, Query, Model, QueryWithHelpers } from 'mongoose';

interface QueryHelpers {
  byName(name: string): QueryWithHelpers<Array<ITest>, ITest, QueryHelpers>;
}

const schema: Schema<ITest, Model<ITest, QueryHelpers>> = new Schema({
  name: { type: 'String' },
  tags: [String],
  docs: [{ nested: { id: Number, tags: [String] } }],
  endDate: Date
});

schema.query.byName = function(this: QueryWithHelpers<any, ITest>, name: string): QueryWithHelpers<any, ITest> {
  return this.find({ name });
};
```

**Comment by GCastilho** [comment]
I know it's closed but I do confirm this worked as a workaround
