### ISSUE TITLE
Aggregation with the text search doesn't work

### ISSUE THREAD

**Issue by anotheri** [Automattic/mongoose#10549]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When I use text search with `.aggregate` it throws the error

> $match with $text is only allowed as the first pipeline stage

although, my code looks like this

```
await Person
  .aggregate([
    {
      $match: {
        $text: { $search: 'john' }
      }
    }
  ])
  .exec();
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
try {
  const PersonSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      index: true
    }
  });
  
  PersonSchema.index({ name: 'text' });
  
  const Person = mongoose.model('Person', PersonSchema);

  await Person.create({ name: 'John Do' });
 
  // query works well
  const queryData = await Person
    .find({
      $text: { $search: 'john'}
    })
    .exec();

  console.log('queryData', queryData);

  // and aggregation throws error
  const aggregationData = await Person
    .aggregate([
      {
        $match: {
          $text: { $search: 'john' }
        }
      }
    ])
    .exec();

  console.log('aggregationData', aggregationData);
} catch (err) {
  console.error(err);
}
```

**What is the expected behavior?**

Aggregation should work as the same aggregation executed in mongo shell. It works there.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 12.14.1
mongoose: 5.13.5
mongo: 4.2

**Comment by IslandRhythms** [comment]
Ran the script and it doesn't throw an error. What error message were you getting?

**Comment by vkarpov15** [comment]
Below script works as expected for me, with the addition of `await Person.init()` to ensure that the text index is built before executing. Can't get the "$match with $text is only allowed as the first pipeline stage" error to happen.

Are you perhaps using a discriminator?

```javascript
'use strict';

const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const PersonSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      index: true
    }
  });
  PersonSchema.index({ name: 'text' });
  const Person = mongoose.model('Person', PersonSchema);
  await Person.init(); // <-- Add this to make sure the Person index is built
  await Person.create({ name: 'John Do' });

  // query works well
  const queryData = await Person
    .find({
      $text: { $search: 'john'}
    })
    .exec();
  console.log('queryData', queryData);

  // and aggregation throws error
  const aggregationData = await Person
    .aggregate([
      {
        $match: {
          $text: { $search: 'john' }
        }
      }
    ])
    .exec();
  console.log('aggregationData', aggregationData);
}

```

**Comment by anotheri** [comment]
Hm, yeah that code works, I don't use discriminator, maybe some plugins do.
What if I find that happens b/c o discriminator on the plugin? is there any workaround?
I'll try to find the exact reason and share a failing code example here.

**Comment by anotheri** [comment]
ok, it was easy enough, that happens to my code b/c of method overridden on [mongoose-delete](https://github.com/dsanel/mongoose-delete#method-overridden) plugin.

`.aggregate()` fails with the subject error.
`.aggregateWithDeleted()` works well.

I guess we can close the issue. Thanks for your support!
