### ISSUE TITLE
How do i store a URL

### ISSUE THREAD

**Issue by hapyllama** [Automattic/mongoose#10551]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
How do i store a URL to my db

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
How pleaz tell 😞 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NODE: 14.16.1
mongoose: 5.13.5

**Comment by vkarpov15** [comment]
As a string.
