### ISSUE TITLE
referencing to subdocuments

### ISSUE THREAD

**Issue by massivefermion** [Automattic/mongoose#10559]
I'm working on a yelp-like project. There are businesses and each business belongs to a category. Categories can form a hierarchy. So this is the schema I used for categories:
```javascript
const categorySchema = new Schema({
  name: {
    type: String,
    required: true,
    index: { unique: true },
  },
  icon: String,
  color: String,
})

categorySchema.add({ subCategories: [categorySchema] })
```

And this is the business schema:
```javascript
const businessSchema = new Schema({
  title: {
    type: String,
    trim: true,
    required: true,
    index: true,
  },
  category: {
    type: Schema.Types.ObjectId,
    ref: 'categories',
  }
})
```

Right now, each business can only reference a category. What I don't know how to do, is referencing a sub-category in a way that `populate` works correctly even for sub-categories.
I searched a lot but I couldn't find anything. Is it even possible?
Thanks

**Comment by vkarpov15** [comment]
You shouldn't store `subCategories` as an array. Instead, each category should have a `parentId` that points to its parent category.

```javascript
const categorySchema = new Schema({
  name: {
    type: String,
    required: true,
    index: { unique: true },
  },
  icon: String,
  color: String,
  parentId: { type: Schema.Types.ObjectId, ref: 'categories' }
})
```

And then `businessSchema` should have a `categories` array that contains pointers to all categories, including parent categories, that this business belongs to.

```javascript
const businessSchema = new Schema({
  title: {
    type: String,
    trim: true,
    required: true,
    index: true,
  },
  categories: [{
    type: Schema.Types.ObjectId,
    ref: 'categories',
  }]
})
```

Out of curiosity, what did you search on Google when you were looking for info on this?

**Comment by massivefermion** [comment]
Well, I suppose it's a case of the X Y problem, I got so focused on solving it this way that I only searched for referencing sub documents in the schema and making populate work correctly.
That makes sense. Thanks.
