### ISSUE TITLE
Merging last changes from mongodb driver 4.1.0

### ISSUE THREAD

**Issue by mmkhmmkh** [Automattic/mongoose#10560]
Hi,

Recently, nodejs's mongodb driver library updated to 4.1.0, So it can support MongoDB Atlas Serverless connections. pls upgrade to 4.1.0 ASAP :)

Yet, can I take some actions personally inside my project to force current mongoose to use mongodb 4.1.0?

**Comment by Kamikadze4GAME** [comment]
Duplicate of #10467, #10461, #10454

Read: https://github.com/Automattic/mongoose/issues/10461#issuecomment-894835696

**Comment by andalike** [comment]
Following.

**Comment by mmkhmmkh** [comment]
> We'll upgrade and ship v6.0.0-rc1 later today 👍

When rc1 will be available? :))

**Comment by vkarpov15** [comment]
It's available now, `npm install mongoose@6.0.0-rc1`
