### ISSUE TITLE
AWS Lambda Issue. Constant Reconnections. Need MongoDb Driver 4.1.0

### ISSUE THREAD

**Issue by rmm443** [Automattic/mongoose#10567]
Having a reconnect issue with Lambda and Mongoose. It is causing my connections to skyrocket, reaching the Atlas limitations.

I have been using Atlas and Lambda for at least 2 years, maybe more. Always re-used the same connection on a warm container, making sure connections were proper. Currently the database connection should be re-used on a warm container, however it randomly closes the connection forcing a new connection to be opened. I cannot consistently reproduce this between invocations, however it seems to happen when invocations on a warm container are more than 10s apart.

I believe I have narrowed it down to something with unified topology. Toggling useUnifiedTopology to true and false has mixed results, but the reconnect issue goes away when useUnifiedTopology: false.

**useUnifiedTopology: true**
- Frequent new connections between invocations on the same warm Lambda container.
- No initial connection timeouts.
- Total connections approaching limits on Atlas Cluster.

**useUnifiedTopology: false**
- No new connections between invocations on the same warm Lambda container.
- Initial connection timeouts sporadically occur on cold start without any pattern.
- Total connections much lower without warnings.

After talking to Atlas support, it seems that using Mongo Driver 4.1.0 is the solution, unfortunately the latest stable Mongoose uses 3.6. Is there a way to force Mongoose to my installed Mongo Driver 4.1.0 instead of using its driver dependency? 

I tried Mongoose 6.0rc0 but it immediately caused errors and I had to abandon it as this is a production situation.

MongoDb Atlas 4.4.8
Mongoose 5.13.6
Mongodb Driver 4.1.0

**Comment by vkarpov15** [comment]
There isn't a way to force Mongoose to use MongoDB driver 4.1.0 right now. We'll ship 6.0.0-rc1 later today with MongoDB driver 4.1.0 :+1:
