### ISSUE TITLE
Allow strings for Ids in UpdateQuery for nested documents

### ISSUE THREAD

**Issue by lx-0** [Automattic/mongoose#10573]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Currently when writing a query for a Schema with object ids (refs) in nested documents, the UpdateQuery expects ObjectIds for these nested properties. For all other top-level object id properties, the UpdateQuery either expects ObjectId or string.

**What is the expected behavior?**
Also allow strings for object ids on nested properties. Therefore make type alias `_AllowStringsForIds` in index.d.ts recursive:
```
  type _AllowStringsForIds<T> = {
    [K in keyof T]: [Extract<T[K], mongodb.ObjectId>] extends [never]
      ? T[K] extends object
        ? _AllowStringsForIds<T[K]>
        : T[K]
      : T[K] | string;
    };
```

**Comment by helgetan** [comment]
Stumbled upon this issue a while ago. 
Thumbs up for reporting
+1
