### ISSUE TITLE
Docs about `Document#$where`

### ISSUE THREAD

**Issue by spaiz** [Automattic/mongoose#10583]
Hey. I have some legacy system, where the pattern model.findByID() -> change -> model.save() heavily used.

We have concurrency issues, and we decided to try to implement optimistic concurrency manually. I know the last mongoose version supports out of the box the optimisticConcurrency, but we cannot upgrade. And even if I could, I wouldn't use a single version flag because it will stress our system. We have too many fields on the object. that updated too often, even if they are not really related. As result, it will affect each update we have, including UI, and will make our life worse.

The idea is to introduce some additional field, like fooVersion, and increments it only when some specific fields were changed. I want to secure only a specific set of fields from concurrency issues. Don't care about other stuff for now...

This was my idea (pseudo):

```
ModelSchema.pre('save', function (next) {
	var self = this;

       if (isUpdate) {
             const currentFooFieldVersion = self..... get value loaded from db;
      
              // if some fields modified, I increase the version
	      if (self.isModified('fooField')) {
		      self.fooFieldVersion = new Date().getTime();
	      }
      
              // add the original version value to the internal query object
	      const conditions = self.Query();
	      conditions.set({
	         fooFieldVersion: currentFooFieldVersion.
	      });
	      
	      self._conditions = conditions;
        }
	next();
});
```

I want to force the mongoose to generate under the hood the update with query (I assume it uses updateOne under the hood)

```
.updateOne({ _id: ObjectId("......."), fooFieldVersion: currentFooFieldVersion }
```

Then I wanted to capture results, and if zero docs were updated, throw concurrency error to the business flow, so the client can retry.

Cannot find any way to access the query from the pre('save') hook.

Also thinking how can I safely refactor code to use updateOne() explicitly instead of .save(), without refactoring the whole business logic. Do we have any API to force mongoose model provide me the "diff" it will use on save() so I can take it, and put manually to updateOne()?

Thanks!

p.s.
We use mongoose: v5.6.7

**Comment by spaiz** [comment]
OK. Looks like I found the way to do it. Looks like magic to me, cause self.$where is undefined when I try to debug, but it still works when I explicitly create it like that.

```
		self.$where = {
			'listingAssignVersion': currentListingAssignVersion,
		};
```

Not sure how safe is it :/

**Comment by vkarpov15** [comment]
We don't have good documentation for `this.$where` currently, but you're right that `$where` is our recommended way to implement custom optimistic concurrency plugins, see #4004. The only notes we have are in our changelog: https://github.com/Automattic/mongoose/blob/master/History.md#480--2017-01-28 and #4004. `this.$where` will be undefined by default because it's a property that we've added to allow users to modify the query filter that `save()` uses.

We'll keep this open to make a note about `$where`.
