### ISSUE TITLE
Schema.index text weight types

### ISSUE THREAD

**Issue by AlexZeDim** [Automattic/mongoose#10586]
Versions of `package.json` and `tsconfig.json`:

    - "mongoose": "5.13.7",
    - "typescript": "4.2.4",

Also, I am using Node.js: 16.0.N with Nestjs (8.0) but I guess it doesn't matter since the problem isn't in there.

I'd to ask a question about text indexes and probably report a bug.

I have a problem with build a text index, with the following syntax:

```ts
RealmsSchema.index(
  {
    slug: 'text',
    name: 'text',
    name_locale: 'text',
    slug_locale: 'text',
    ticker: 'text',
    region: 'text',
    locale: 'text',
  },
  {
      weights:
        {
          slug: 10,
          name: 1,
          slug_locale: 1,
          name_locale: 1,
          ticker: 3,
          region: 1,
          locale: 1,
        },
    name: 'SQ',
  },
);
```

Since `5.13.7` version of mongoose gives me the following type error via IDE:
![image](https://user-images.githubusercontent.com/907696/130318058-859e98e2-191b-4068-a1e0-84d48b6c039b.png)

But before updating to mongoose 5.13 I was using 5.12,N and it was actually fine. I have tried various syntaxes according to `*.d.ts` files inside the mongoose itself, with using of `collection object and so on, but it still gives me errors. So the question is, is it a bug? How exactly should I build text indexes with custom weight on the fields right now?

![image](https://user-images.githubusercontent.com/907696/130318171-184ebcef-b35e-4877-81fc-61b6cbbe649d.png)

**Comment by hasezoey** [comment]
could you provide what version of `mongodb` / `@types/mongodb` is installed? because the mongoose Index types extend from the mongodb ones in recent 5.13.x releases

note: if 4.x is installed, try downgrading to `3.6.x` (both `mongodb` and `@types/mongodb`)

**Comment by rlawisch** [comment]
I've just had a similar problem with mongoose `5.13.7`: when sending `{ unique: true }` in `IndexOptions`, an error was raised because there were no `MongoDB.IndexOption` type to be extended. The NPM resolved dependency version for `@types/mongodb` was `3.6.20`.

**Comment by hasezoey** [comment]
@rlawisch could you either open another issue or provide the code where you tried to add this option and the error?

**Comment by rlawisch** [comment]
Sure, I will document it more thoroughly and open an issue properly

**Comment by vkarpov15** [comment]
@rlawisch this looks like a bug on your end, you're specifying `weights` as a sub-option of `collation`, which is incorrect: https://docs.mongodb.com/manual/tutorial/control-results-of-text-search/#control-search-results-with-weights

**Comment by rlawisch** [comment]
@vkarpov15 I think you mean to mention @AlexZeDim

**Comment by AlexZeDim** [comment]
@vkarpov15 guess you missed some description from my issue. In `5.13.7` weight in part of the collection at:

And the original syntax from the beginning was:

![image](https://user-images.githubusercontent.com/907696/130480097-33ae5601-69c0-4a1d-9546-8ad680e3454c.png)

@hasezoey `mongodb` version is 4.2.3 community, and I don't have `@types/mongodb` since mongoose has its own types.

**Comment by hasezoey** [comment]
> @hasezoey mongodb version is 4.2.3 community, and I don't have @types/mongodb since mongoose has its own types.

sorry if this was not clear, i meant what `mongodb` *driver* version was installed and used
and mongoose depends on `@types/mongodb`, so i asked what version was installed "implicitly"

**Comment by AlexZeDim** [comment]
@hasezoey 
![image](https://user-images.githubusercontent.com/907696/130484956-ffa1e831-e8cf-4457-bcfa-85fb0e685bf5.png)
