### ISSUE TITLE
[6.0] validation on references is inconsistent between arrays and non arrays

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10585]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Validation for References is not consistent between Arrays and non-Arrays, in non arrays the parameters to a validate function are unpopulated, in a array (outer) the input is also unpopulated, but in a array (inner) it is *populated*

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduction repository: https://github.com/typegoose/typegoose-testing/tree/mongooseValidateInconsistency
Use branch `mongooseValidateInconsistency`

Steps to reproduce (Linux):
- `git clone https://github.com/typegoose/typegoose-testing/tree/mongooseValidateInconsistency`
- `git checkout -b mongooseValidateInconsistency origin/mongooseValidateInconsistency`
- `git reset --hard HEAD~1` (go to the mongoose 5.13.7 commit)
- `yarn install`
- `yarn run run` (have a mongodb instance running locally on port `27017`, or change the connect line)
- look at the result
- `git reset --hard origin/mongooseValidateInconsistency` (go to the 6.0 commit)
- `yarn install`
- `yarn run run`
- look at the result

<details>
<summary>TL;DR: the output of the steps above</summary>

Output from 5.13.7:

```
yarn run v1.22.11
$ yarn run build && node lib/test.js
$ tsc
validateOuter1 1 2 [{"_id":"611f9876cdb8e5cbede57261","dummyProp":"doc1","__v":0},{"_id":"611f9876cdb8e5cbede57262","dummyProp":"doc2","__v":0}]
validateOuter2 true true
validateInner1 1 { _id: 611f9876cdb8e5cbede57261, dummyProp: 'doc1', __v: 0 }
validateInner2 true
validateInner1 1 { _id: 611f9876cdb8e5cbede57262, dummyProp: 'doc2', __v: 0 }
validateInner2 true
main {
  refarray: [
    { _id: 611f9876cdb8e5cbede57261, dummyProp: 'doc1', __v: 0 },
    { _id: 611f9876cdb8e5cbede57262, dummyProp: 'doc2', __v: 0 }
  ],
  _id: 611f9876cdb8e5cbede57265,
  __v: 0
}
Done in 3.43s.
```

Output from 6.0 (head 14dd60be1f11969bcf7c84fe903ffe0471ff1485):

```
yarn run v1.22.11
$ yarn run build && node lib/test.js
$ tsc
validateOuter1 1 2 [
  new ObjectId("611f98f8ba650a92a093fd2b"),
  new ObjectId("611f98f8ba650a92a093fd2c")
]
validateOuter2 true true
validateInner1 1 {
  dummyProp: 'doc1',
  _id: new ObjectId("611f98f8ba650a92a093fd2b"),
  __v: 0
}
validateInner2 true
validateInner1 1 {
  dummyProp: 'doc2',
  _id: new ObjectId("611f98f8ba650a92a093fd2c"),
  __v: 0
}
validateInner2 true
main {
  refarray: [
    {
      dummyProp: 'doc1',
      _id: new ObjectId("611f98f8ba650a92a093fd2b"),
      __v: 0
    },
    {
      dummyProp: 'doc2',
      _id: new ObjectId("611f98f8ba650a92a093fd2c"),
      __v: 0
    }
  ],
  _id: new ObjectId("611f98f8ba650a92a093fd2f"),
  __v: 0
}
Done in 3.55s.
```

context for output: https://github.com/typegoose/typegoose-testing/blob/29800305aacff6e1d14071d2551fa78b59908f9d/src/test.ts#L5-L20

</details>

**What is the expected behavior?**
expected the parameters for arrays (inner) to also be unpopulated

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 6.0 (head 14dd60be1f11969bcf7c84fe903ffe0471ff1485)

---

in relation to #10522

**Comment by IslandRhythms** [comment]
Am getting the same thing on my machine
