### ISSUE TITLE
Dependency hygiene

### ISSUE THREAD

**Issue by jimmywarting** [Automattic/mongoose#10589]
I where going through the pkg json...

I wish to pruning dependencies that aren't needed in modern JS environments (to reduce dependencies and increase install/compile speed) mquery that you depend on is creating a major release https://github.com/aheckmann/mquery/pull/125

mquery is removing safe-buffer, using more modern syntax like classes, dropped support for node <12, etc
I hope this dose the same

https://npmgraph.js.org/?q=mongoose@5.13.7
https://github.com/Automattic/mongoose/blob/6c362631a2c7680737723dbc0c91262286a7b164/package.json#L21-L72

Some few things:

- [ ] drop support for node < 12.20 possible use esm and prefix builtin node dependencies with `node:`

### Direct deps to remove
* [ ] q - replace with async/await
* [ ] bluebird - replace with async/await
* [ ] co - replace with async/await
* [ ] safe-buffer & buffer - replace with built in buffer, or if possible switch to plain uint8array through out the hole dep-tree
* [ ] try replacing lodash with vanila js solutions
* [ ] rimraf & mkdirp - could technically use fs nodes new mkdir, rm recursive mode.

### Direct deps to update
* [ ] mongodb
* [ ] mquery

### Indirect deps to update
- [ ] update readable-stream to latest version, alternative use `for await (let chunk of chunks)`

**Comment by hasezoey** [comment]
most of this is already done in 6.0, see https://github.com/Automattic/mongoose/tree/6.0

**Comment by vkarpov15** [comment]
@hasezoey is right, we're dropping support for Node < 12 in the 6.0 branch. The mquery 4.0 release is to enable releasing mongoose 6.

q, bluebird, co, lodash.*, rimraf, and mkdirp are dev dependencies, they don't end up in user installs, and they're mostly used to test integration with those libs, so we're unlikely to remove them.

We also disagree with using streams as async iterators. They're fundamentally different structures and shouldn't be mixed up.
