### ISSUE TITLE
Unnecessary validation is triggered

### ISSUE THREAD

**Issue by sinevitch** [Automattic/mongoose#10581]
`phone: {
    type: Array,
    validate(value) {
      validation.checkPhone(value);
    },
  },`

If the type is set to array validation is triggered without required true

node:13.12.0-alpine
"mongoose": "^5.9.13",
Docker Engine v20.10.7

**Comment by vkarpov15** [comment]
What value are you setting the array to?

Keep in mind that arrays have an implicit default value of `[]`, so they always pass `required`.
