### ISSUE TITLE
Compatibility Issue with latest mongoose

### ISSUE THREAD

**Issue by ssomlk** [Automattic/mongoose#10588]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Getting below error
```
No overload matches this call.
  Overload 1 of 3, '(options?: SaveOptions): Promise<LoadingSheetDoc>', gave the following error.
    Type 'import("c:/projects/distribution/backend-services/node_modules/mongodb/mongodb").ClientSession' is not assignable to type 'import("mongoose").ClientSession'.
      The types returned by 'abortTransaction()' are incompatible between these types.
        Type 'Promise<Document>' is not assignable to type 'Promise<void>'.
          Type 'Document' is not assignable to type 'void'.
  Overload 2 of 3, '(options?: SaveOptions, fn?: Callback<LoadingSheetDoc>): void', gave the following error.
    Type 'import("c:/projects/distribution/backend-services/node_modules/mongodb/mongodb").ClientSession' is not assignable to type 'import("mongoose").ClientSession'.
  Overload 3 of 3, '(fn?: Callback<LoadingSheetDoc>): void', gave the following error.
    Argument of type '{ session: ClientSession; }' is not assignable to parameter of type 'Callback<LoadingSheetDoc>'.
      Object literal may only specify known properties, and 'session' does not exist in type 'Callback<LoadingSheetDoc>'.ts(2769)
index.d.ts(1125, 5): The expected type comes from property 'session' which is declared here on type 'SaveOptions'
index.d.ts(1125, 5): The expected type comes from property 'session' which is declared here on type 'SaveOptions'
(property) SaveOptions.session?: mongoose.ClientSession
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const sheet = LoadingSheet.build({
  agency,
  area,
  territory,
  route,
  records,
  createdBy,
  transportClaim: routeFound!.area.transportClaim,
});

const session = await mongoose.startSession();
session.startTransaction({
  // readPreference: 'primary',
  // readConcern: { level: 'local' },
  // writeConcern: { w: 'majority' },
});

sheetAfterSave = await sheet.save({session:session});
```
Getting the above error at sheet.save({session:session})

```
{
  "compilerOptions": {
    "target": "es5" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "outDir": "./build" /* Redirect output structure to the directory. */,
    "rootDir": "./src" /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,
    "downlevelIteration": true /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */,
    /* Strict Type-Checking Options */
    "strict": false /* Enable all strict type-checking options. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**What is the expected behavior?**
Seems correct according to the index.d.ts

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 15.11.0-alpine3.13, mongoose - 5.13.7, mongoDB 4.0.7

**Comment by hasezoey** [comment]
mongodb 4.x is not supported in mongoose 5.13, only in 6.0 (beta) currently, so maybe try downgrading and pinning the `@types/mongodb` version to `3.6.x`

**Comment by ssomlk** [comment]
Hi @hasezoey 

Below is my package.json file

```
{
  "name": "distribution",
  "version": "1.0.0",
  "description": "implementation of distribution api",
  "main": "index.js",
  "scripts": {
    "start": "ts-node-dev --poll src/index.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/cookie-session": "2.0.41",
    "@types/cors": "2.8.7",
    "@types/express": "4.17.6",
    "@types/express-mongo-sanitize": "1.3.2",
    "@types/helmet": "0.0.47",
    "@types/hpp": "0.2.1",
    "@types/jsonwebtoken": "8.5.0",
    "@types/mongoose": "5.7.21",
    "@types/socket.io": "2.1.11",
    "connect-mongodb-session": "2.4.0",
    "cookie-session": "1.4.0",
    "cors": "2.8.5",
    "express": "4.17.1",
    "express-async-errors": "3.1.1",
    "express-mongo-sanitize": "2.0.0",
    "express-rate-limit": "5.1.3",
    "express-validator": "6.6.0",
    "fs-extra": "10.0.0",
    "helmet": "3.23.3",
    "hpp": "0.2.3",
    "jsonwebtoken": "8.5.1",
    "moment": "2.27.0",
    "mongoose": "5.9.21",
    "mongoose-update-if-current": "1.4.0",
    "node-nats-streaming": "0.3.2",
    "ts-node-dev": "1.0.0-pre.49",
    "typescript": "3.9.3"
  },
  "devDependencies": {
    "@types/fs-extra": "9.0.11"
  }
}
```

I do not you @types/mongodb directly. But I can see @types/mongodb in my node_modules (Even after deleting node_modules and package-lock.json). Most probably its from some other dependancy.

I can downgrade mongoose but what do you mean by pinning the @types/mongodb version to 3.6.x. How can i achieve this??

Any advise is highly appreciated

**Comment by hasezoey** [comment]
from what i can tell from the original issue was that you just used mongoose 5.13.x, so the correct mongodb types *should be installed*, but from the package.json i can see now that you have mongoose 5.9.21 (direct, no range) installed and the unofficial types (`@types/mongoose`), which are known to have the `@types/mongodb` version requirement of `*`

so your 2 options are:
- upgrade to mongoose 5.10.19+ (i recommend 5.13.x) to have the official mongoose types and the correct mongodb types versions
- stay at the mongoose version and pin the `@types/mongodb` dependency by directly requiring it (note: use the version that is closest to what the `mongodb` version of mongoose is at `5.9.21`), also note that with some package managers (like yarn), you will probably need to manually update the lock-file to have only one dependency installed (sometimes yarn installs the latest version for `*` (and the older one for the direct dependency, if its older) and uses that for who requires it, and the direct dependency will do nothing)

**Comment by vkarpov15** [comment]
@ssomlk can you please run `npm list | grep "mongo"` and paste the output? It looks like you might be getting `mongodb@4.x` somehow based on the fact that TypeScript is pulling types from `node_modules/mongodb/mongodb`, and that would likely be causing the errors you're seeing.

Also, how are you creating your sessions? Are you using the MongoDB driver directly?

**Comment by hasezoey** [comment]
> Also, how are you creating your sessions? Are you using the MongoDB driver directly?

in the screenshot its `await mongoose.startSession()`?

**Comment by vkarpov15** [comment]
@hasezoey I saw the screenshot, just wanted to make sure there isn't some other way OP is creating sessions in another part of the code.

**Comment by ssomlk** [comment]
Hi @vkarpov15 

See below
```
C:\projects\distribution\backend-services>npm list | findstr "mongo"
| +-- @types/mongoose@5.7.21
| | +-- @types/mongodb@4.0.7
| | | `-- mongodb@4.1.0
| | |   +-- mongodb-connection-string-url@1.1.2
| +-- mongoose@5.9.21
| | +-- mongodb@3.5.9
| | +-- mongoose-legacy-pluralize@1.0.2 deduped
+-- @types/express-mongo-sanitize@1.3.2
+-- connect-mongodb-session@2.4.0
| `-- mongodb@3.6.11
+-- express-mongo-sanitize@2.0.0
+-- mongoose@5.13.7
| +-- @types/mongodb@3.6.20
| +-- mongodb@3.6.11
| +-- mongoose-legacy-pluralize@1.0.2
+-- mongoose-update-if-current@1.4.0
```

I am only using await `mongoose.startSession()` to create the session. Hope these helps

**Comment by hasezoey** [comment]
> | +-- @types/mongoose@5.7.21
> | | +-- @types/mongodb@4.0.7

that seems to be the problem, `@types/mongoose` are still required by some other dependency, which also uses `+-- mongoose@5.9.21` somewhere

**Comment by ssomlk** [comment]
@vkarpov15 @hasezoey Thanks guys for your help so far
I was able to figure out the package with @types/mongoose 5.9.21 and was able to get it sorted. Now the previous errors are gone

But now I am getting another issue shown below.
```

[ERROR] 15:33:08 ⨯ Unable to compile TypeScript:
src/models/LoadingSheet.ts(175,14): error TS2589: Type instantiation is excessively deep and possibly infinite.
```

```
const LoadingSheetSchema = new mongoose.Schema(
  {
    agency: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Agency',
      required: true,
    },
    salesAmountByType: [
      {
        _id: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'ProductType',
          required: false,
        },
        claimAmount: {
          type: Number,
          required: false,
          default: 0,
        },
        salesAmount: {
          type: Number,
          required: false,
          default: 0,
        },
        freeIssueAmount: {
          type: Number,
          required: false,
          default: 0,
        },
        netSalesAmount: {
          type: Number,
          required: false,
          default: 0,
        },
        commissionRate: {
          type: Number,
          required: false,
          default: 0,
        },
        commissionAmount: {
          type: Number,
          required: false,
          default: 0,
        },
      },
    ],
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: false,
    },
    createdAt: {
      type: String,
      required: false,
    },
  },
  {
    toJSON: {
      transform(doc, ret) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
      },
    },
  }
);
```
It's showing the error at salesAmountByType

![image](https://user-images.githubusercontent.com/30547921/130476509-c2e6e96e-c443-4b31-82fc-56ce8a1a83b4.png)

**Comment by hasezoey** [comment]
what typescript version are you using?

**Comment by ssomlk** [comment]
@hasezoey it's as below

"ts-node-dev": "1.0.0-pre.49",
 "typescript": "3.9.3"

**Comment by hasezoey** [comment]
did you already try upgrading to typescript 4.1 (the version mongoose uses for the types) or 4.2?

**Comment by ssomlk** [comment]
Hi @hasezoey,

I updated the typescript to the latest and it works without any issues now. All good
Many thanks for your help (both @vkarpov15 ) and appreciate it heaps.

Cheers

**Comment by ammarlakho** [comment]
Facing a similar issue but my TS version is 4.9.3 
https://github.com/Automattic/mongoose/issues/12877

**Comment by vkarpov15** [comment]
@ammarlakho please open a new issue and follow the issue template
