### ISSUE TITLE
Populating different properties WITH different Models in a Mongoose Map Type Schema

### ISSUE THREAD

**Issue by silvergravel** [Automattic/mongoose#10584]
**Do you want to request a *feature* or report a *bug*?** 
**Feature Request. I guess.**

**What is the current behavior?**
Okay so there seems to be very little about populating Mongoose Map type schema except for the $* selector, but my use case is slightly different:

So I have a schema :
```
Tags  = {

  taggedResources : {
    type: Map,
    of : {
      collectionId: String,
      data: [ { _id : ObjectId } ]
    }
  }

}
```

Now, the data captured via this schema would look something like:

```
taggedResources : {
  collectionid_1 : {
     collectionId : collectionId_1,
     data: [ 
       { _id : id_1 }, 
       { _id : id_2 },
     ]
  },
  collectionid_2 : {
     collectionId : collectionId_2,
     data: [ 
       { _id : id_1 }, 
       { _id : id_2 },
     ]
  }
}
```

Now the problem is:

I need to populate the `id`s in the map property `collectionId_1` with the `collectionId_1` model & I need to populate the `id`s in the map property `collectionId_2` with the `collectionId_2` model

So now, what I tried:

```
tags.populate({
  path: 'taggedResources.$*.data._id,
  model: 'collectionId_1'
})
```

this works, but only populates the `_id`s inside of `collectionId_1`.

I also tried this:
```
for (const key of tag.taggedResources.keys()) {

  tags.populate({
    path: 'taggedResources.$*.data._id,
    match: { 'taggedResources.$*.data.collectionId' : key },
    model: 'collectionId_1'
  })

}
```
doesn't work at all.

I also tried populating by defining a path explicitly: path: `taggedResources.collectionId_1.data._id`

doesn't work.

Can anyone help me with this? Is there even a way? Or will I just have to change my data model back to an array or object.

The reason why I didn't want to use a Object without any clear property definition was because, I wanted to have a more defined 'shape' to the data and stricter type checking. That was the only reason why I thought I should use Map...

Anyway, please help! This issue with Map Schema Type has been bothering me for a while now.

Nodejs version : 12
mongoose version : 5.10.2

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by usernamedoesntexist** [comment]
![image](https://user-images.githubusercontent.com/88772874/130020323-cfcd9f5c-14ba-49f3-926d-d742d1edfdfe.png)
hi i want to remove object that have categorie: null after populating how to do that without filter in exec?

**Comment by IslandRhythms** [comment]
@usernamedoesntexist please open a new issue

**Comment by vkarpov15** [comment]
@silvergravel you'd need to set a `ref` in your schema. The below code populates each entry in the map based on the corresponding `modelId`, but it unfortunately requires Mongoose 6.0.0-rc1. It won't work in Mongoose 5.x because it requires the change from #8469 .

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  await mongoose.connection.dropDatabase();

  const Person = mongoose.model('Person', Schema({ name: String }));
  const Book = mongoose.model('Book', Schema({ title: String }));

  const schema = new Schema({
    myMap: {
      type: Map,
      of: {
        modelId: String,
        data: [{
          _id: {
            type: mongoose.ObjectId,
            ref: doc => doc.parent().modelId // <-- use `modelId` as the name of the model used to populate this subdoc
          }
        }]
      }
    }
  });
  const Test = mongoose.model('Test', schema);

  const people = await Person.create({ name: 'John' });
  const book = await Book.create({ title: 'Intro to CS' });

  await Test.create({
    myMap: {
      key1: { modelId: 'Person', data: [{ _id: people._id }] },
      key2: { modelId: 'Book', data: [{ _id: book._id }] }
    }
  });

  const res = await Test.findOne().populate('myMap.$*.data._id');
  console.log(require('util').inspect(res.myMap.values(), { depth: 10, colors: true }));
}
```

Does this help?

**Comment by silvergravel** [comment]
@vkarpov15 thank you! This should do it for me i guess.
