### ISSUE TITLE
Depopulate not working for populated docs inside array

### ISSUE THREAD

**Issue by LiaanM** [Automattic/mongoose#10592]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A schema containing an array of documents with a nested reference inside of the document in the array does not depopulate correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
The following is a test to reproduce the error.  The `band.members` and `band.lead` is depopulated correctly, but the `band.embeddedMembers` are not. 

    it('depopulate all should depopulate nested array population', async function() {

         const Person = db.model('Person', {
              name: String
          });

          const Band = db.model('Band', {
              name: String,
              members: [{ type: Schema.Types.ObjectId, ref: 'Person' }],
              lead: { type: Schema.Types.ObjectId, ref: 'Person' },
              embeddedMembers: [{
                  active: Boolean,
                  member :{
                      type: Schema.Types.ObjectId, ref: 'Person'
                  }
              }]
          });

          const people = [{ name: 'Axl Rose' }, { name: 'Slash' }];
          try {
              let docs = await Person.create(people);
              let band = {
                  name: 'Guns N\' Roses',
                  members: [docs[0]._id, docs[1]],
                  lead: docs[0]._id,
                  embeddedMembers: [{active:true,member:docs[0]._id},{active:false, member:docs[1]._id}]
              };
              band = await Band.create(band);
              await band.populate('members lead').populate('embeddedMembers.member').execPopulate();
              assert.ok(band.populated('members'));
              assert.ok(band.populated('lead'));
              assert.ok(band.populated('embeddedMembers.member'));
              assert.equal(band.members[0].name, 'Axl Rose');
              assert.equal(band.embeddedMembers[0].member.name, 'Axl Rose');
              band.depopulate();
              assert.ok(!band.populated('members'));
              assert.ok(!band.populated('lead'));
              assert.ok(!band.populated('embeddedMembers.member'));
              assert.ok(!band.embeddedMembers[0].member.name);
              return null
          } catch (err) {
              /* handle error */
              assert.ifError(err);
              return err;
          }
      });

**What is the expected behavior?**
The array with nested population should depopulate.  
I suspect the $set is not taking into account the array indexes here : https://github.com/Automattic/mongoose/blob/a803885a49cb1f0498181263e140e8b688c3e145/lib/document.js#L4206

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js -> v14.17.5
mongoose -> 5.13.8
MongoDB -> 5.0.2

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const {Schema} = mongoose;

const Person = mongoose.model('Person', {
    name: String
});

const Band = mongoose.model('Band', {
    name: String,
    members: [{ type: Schema.Types.ObjectId, ref: 'Person' }],
    lead: { type: Schema.Types.ObjectId, ref: 'Person' },
    embeddedMembers: [{
        active: Boolean,
        member :{
            type: Schema.Types.ObjectId, ref: 'Person'
        }
    }]
});

const people = [{ name: 'Axl Rose' }, { name: 'Slash' }];

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
      await mongoose.connection.dropDatabase();

      
try {
    let docs = await Person.create(people);
    let band = {
        name: 'Guns N\' Roses',
        members: [docs[0]._id, docs[1]],
        lead: docs[0]._id,
        embeddedMembers: [{active:true,member:docs[0]._id},{active:false, member:docs[1]._id}]
    };
    band = await Band.create(band);
    await band.populate('members lead').populate('embeddedMembers.member').execPopulate();
    console.log(band.populated('members')); //true
    console.log(band.populated('lead')); // true
    console.log(band.populated('embeddedMembers.member')); // true
    console.log(band.members[0].name, 'Axl Rose'); // true
    console.log(band.embeddedMembers[0].member.name, 'Axl Rose'); // true
    band.depopulate();
    console.log(!band.populated('members')); // true
    console.log(!band.populated('lead')); // true
    console.log(!band.populated('embeddedMembers.member')); // true
    console.log(!band.embeddedMembers[0].member.name); // false
    return null
} catch (err) {
    /* handle error */
    console.log(err);
    return err;
}
}

test();
```
