### ISSUE TITLE
findByIdAndUpdate not updating

### ISSUE THREAD

**Issue by hallas** [Automattic/mongoose#1060]
User.findByIdAndUpdate(req.body._id, {
    $set: {
      name: req.body.name
    }
  }, { upsert: true },
    function (err, user) {
      return res.json(err == null ? user : err);
    }
  );

This code does not work. It simply returns the document without the updated name field. This means that the _id is correct, but what's not working? I tried alot of different combinations.

**Comment by jotave42** [comment]
i was having the same issue. i fixed with a **await** before User.findByIdAndUpdate
