### ISSUE TITLE
[Question] Is there a way to create MongoDB 5.0 Time Series Collections with Mongoose 6.0?

### ISSUE THREAD

**Issue by antonvalletas** [Automattic/mongoose#10611]
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

* Node v16.7.0
* MongoDB 5.0.2
* Mongoose 6.0

I was wondering if there is a way to mark a Schema in Mongoose as being a [Time Series Collection](https://docs.mongodb.com/manual/core/timeseries-collections/) as described in the MongoDB 5.0 documentation, in order to use this new functionality without having to create these new types of collections manually outside of Mongoose. 

I checked the Mongoose 6.0.0 docs and couldn't any info regarding this matter. Any help is appreciated.

Cheers!

**Comment by acomito** [comment]
@vkarpov15 I tried that but got an error:

```
BSON field 'create.timeseries' is an unknown field
```

**Comment by vkarpov15** [comment]
In v6.1.0, you'll be able to define `timestamps` as a schema option:

```javascript
const schema = new Schema({ name: String, timestamp: Date, metadata: Object }, {
  timeseries: {
    timeField: 'timestamp',
    metaField: 'metadata',
    granularity: 'hours'
  },
  expireAfterSeconds: 86400
});
```

Assuming `autoCreate` is enabled, Mongoose will use the schema `timeseries` option when automatically creating the collection. Or, if you manually call `Model.createCollection()`, Mongoose will use the schema `timeseries` by default.

**Comment by satasuk03** [comment]
I have a problem when I switch database before creating timeseries.  
it will creates a collection instead o f timeseries.  

Here's the code

```typescript
// db.ts
export const useDB = (guidId: string) =>
  mongoose.connection.useDb(guidId, {
    // ensures connections to the same databases are cached
    useCache: true,
    // remove event listeners from the main connection
    noListener: true,
  });

// =====================================

// schema file
import { useDB } from 'db';
import mongoose, { Schema } from 'mongoose';

export interface ActiveUserDoc {
  timestamp: Date;
  messages: Number;
  metadata: { discordId: string };
}

const ActiveUserSchema = new Schema(
  {
    timestamp: Date,
    messages: Number,
    metadata: {
      discordId: String,
    },
  },
  {
    timeseries: {
      timeField: 'timestamp',
      metaField: 'metadata',
      granularity: 'hours',
    },
    expireAfterSeconds: 60 * 24 * 7, // 7 days
  },
);

export const getModel = (guildId: string) =>
  useDB(guildId).model<ActiveUserDoc, mongoose.Model<ActiveUserDoc>>(
    'ActiveUser',
    ActiveUserSchema,
    'active_user',
  );

```

<img width="445" alt="image" src="https://user-images.githubusercontent.com/96050763/172794966-5417c08b-c163-4f2a-a70f-eec8412907c9.png">
