### ISSUE TITLE
Better type definitions for `IndexDirection`

### ISSUE THREAD

**Issue by mahyarmirrashed** [Automattic/mongoose#10629]
**Do you want to request a *feature* or report a *bug*?**
I am requesting a feature.

**What is the current behaviour?**
I am creating a schema with a composite primary key. For this reason, I have to use Model#schema. Where creating this, however, I would like there to be more descriptive options available for the `IndexDirection` field. In my opinion, I think the options of `1` and `-1` are quite hard to understand looking at it the first. Without checking [Mongo's](https://docs.mongodb.com/manual/core/index-compound/) documentation, you would not understand what either meant.

**What is the expected behaviour?**
I believe changing the type definition of `IndexDirection` from
```ts
type IndexDirection = 1 | -1 | '2d' | '2dsphere' | 'geoHaystack' | 'hashed' | 'text';
```
to
```ts
type IndexDirection = 'ascending' | 'descending' | '2d' | '2dsphere' | 'geoHaystack' | 'hashed' | 'text';
```
would solve this problem. However, there is still the issue of making it work in the library itself given those changes.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS version: 16.x
Mongoose version: 6.0.1
Not sure about MongoDB but I know it is one of the more recent ones.

**Comment by vkarpov15** [comment]
Under the hood Mongoose does support both 'ascending'/'descending' and 'asc'/'desc' for sorting, I think we should also add support for both of these for indexes.
