### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by wioniqle-q** [Automattic/mongoose#10624]
![image](https://user-images.githubusercontent.com/69215407/131052706-e2b85e32-ef75-43c0-8191-ad7feda97a3f.png)
![image](https://user-images.githubusercontent.com/69215407/131052727-8b1b5f99-26f5-4066-b312-3c11914d37a5.png)
![image](https://user-images.githubusercontent.com/69215407/131052746-e966029d-583e-4d1a-80c3-ae1d27d5713b.png)

Why this error? no errors in older versions

**Comment by vkarpov15** [comment]
To work around this, set `setDefaultsOnInsert` to `false`:

```javascript
await Test.updateOne({ Id: '12344566', Auth: true}, { $inc: {"Usage.Man": 1 } }, {
  upsert:true,
  setDefaultsOnInsert: false // Tell mongoose to not add `$setOnInsert: { Usage: {} }` to the update
})
```
