### ISSUE TITLE
Mongoose does not automatically create indexes after restoring a database. 

### ISSUE THREAD

**Issue by moisesbites** [Automattic/mongoose#10631]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

"mongoose": "^6.0.2" is not creating indexes automaticly

**If the current behavior is a bug, please provide the steps to reproduce.**

I backed up a database and restored it into a new instance. After that, when testing the system on the new instance, I noticed that no index had been created on the shemas other than the "_id". After I updated mongoose, the options 'useCreateIndex', 'useFindAndModify' and 'useUnifiedTopology' were no more accepted in the connect method. Yhe https://mongoosejs.com/docs/connections.html#options page still seems to be out of date.

![image](https://user-images.githubusercontent.com/8934577/131190861-d1a22ec0-db9c-4b31-9fc7-4b442c99ed3e.png)

For example,

```JS
schema.index({ name: 1 });

schema.index(
  { '$**': 'text' },
  {
    name: 'textIndex',
    default_language: 'portuguese'
  }
);
```
These indexes were not created for any schema. 

**What is the expected behavior?**

The mongoose to create the indexes if they don't exist in the database.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
    mongoose: 6.0.2
    nodejs: v16.3.0
    mongodb: 5.0.2

![image](https://user-images.githubusercontent.com/8934577/131190549-f220efa5-39bc-4860-85e3-e6431cd1d57d.png)

Thank you so much for this great software.

**Comment by HunterKohler** [comment]
The docs indeed are incorrect in a few places, but most of the breaking changes for V6 are [here](https://mongoosejs.com/docs/migrating_to_6.html)

I don't know the answer to this 100%, but I had a similar issue yesterday with a text index, so maybe it can help you.

When you initialize a model the indexes are created automatically unless you set `autoIndex: false` on schemas or the connection. Notice that there is no returned promise when a model is registered, so it's confusing to understand they may not be ready instantly (you can even register models before connection has begun).

Previously, I was using [`Model.init()`](https://mongoosejs.com/docs/migrating_to_6.html) to await index builds on each model. This essentially wraps the little-known `index` event on models and should resolve when the model indexes are finished building (or reject if an error occurs).

Further, the event is triggered by [`Model.ensureIndexes()`](https://mongoosejs.com/docs/api/model.html#model_Model.ensureIndexes)

**However, `Model.init()` stopped working, at least in my case, for an unexplained reason in v6**

The alternative to `Model.ensureIndexes()` is, I believe [`Model.syncIndexes()`](https://mongoosejs.com/docs/api/model.html#model_Model.syncIndexes), which should give similar results if you are re-creating all indexes from scratch on startup (in reality it is not exactly the same, read the docs).

**Comment by IslandRhythms** [comment]
This is intended
https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options

**Comment by vkarpov15** [comment]
We'll need to update the docs you mentioned. Please remove the 'useCreateIndex' option when you upgrade to Mongoose 6, it is no longer necessary.

**Comment by moisesbites** [comment]
Ok. Thank you. But, how I can to force mongoose to create the index?

**Comment by moisesbites** [comment]
> We'll need to update the docs you mentioned. Please remove the 'useCreateIndex' option when you upgrade to Mongoose 6, it is no longer necessary.

in fact mongoose is no longer creating indexes automatically when first loading data into a schema/model

**Comment by vkarpov15** [comment]
@moisesbites Mongoose 6 does automatically create indexes, the `useCreateIndex` option was to internally use `createIndex()` instead of `ensureIndex()`, which is a purely internal change.

Can you please provide a script that demonstrates Mongoose not creating indexes automatically?

**Comment by moisesbites** [comment]
> @moisesbites Mongoose 6 does automatically create indexes, the `useCreateIndex` option was to internally use `createIndex()` instead of `ensureIndex()`, which is a purely internal change.
> 
> Can you please provide a script that demonstrates Mongoose not creating indexes automatically?

I know this is closed, sorry. But here is the example:

![image](https://user-images.githubusercontent.com/8934577/131748786-076ec1f5-f682-408b-a587-3cfb20579125.png)

![image](https://user-images.githubusercontent.com/8934577/131748857-e0159bea-a836-402e-9be7-72ef30ebf9eb.png)

![image](https://user-images.githubusercontent.com/8934577/131748903-b7d36058-3a09-421c-b195-35adbf2f6533.png)

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    name: String,
    age: Number,
    weight: Number,
    height: Number,
    birthday: String
});

testSchema.index({age: 1}, {unique: true});
testSchema.index({ name: 1, weight: 1});
testSchema.index({ name: 1, birthday: 1}, {unique: true});
testSchema.index({ name: 1, height: 1});

testSchema.index({'$**': 'text'}, { name: 'textIndex'});

const Test = mongoose.model('Test', testSchema, 'test');

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      await mongoose.connection.dropDatabase();
      await Test.init();
    console.log(await Test.listIndexes());
}

test();
```

**Comment by truonghongtrieu** [comment]
I had this issue as well, it was because `autoIndex` in the ConnectOptions was set to true. Turning it off and the indexes are created:

```
mongoose.connect(process.env.COSMOSDB_CONNECTION_STRING, {
  dbName: 'my-storage',
  autoCreate: true,
  autoIndex: true
})
```
