### ISSUE TITLE
 `useCreateIndex` is an invalid option.

### ISSUE THREAD

**Issue by aroob5166** [Automattic/mongoose#10637]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Kamikadze4GAME** [comment]
Hello @aroob5166 

Please follow issue template next time. 

Your issue is partially duplicate #10632

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options

**Comment by vkarpov15** [comment]
`useCreateIndex` is no longer necessary in Mongoose 6, please remove it when you upgrade :+1:
