### ISSUE TITLE
Adding of get('parent') feature

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#1063]
At now to get parent document we invoke a this._parent. But we need to have a this.get('parent') feature because of an internal property _parent could be changed in future.

**Comment by skotchio** [comment]
@vkarpov15 will you add this feature or I could close this issue?

**Comment by vkarpov15** [comment]
It's something that I'll put on the roadmap. Thanks for pinging on this issue.

**Comment by vkarpov15** [comment]
Actually, this is already in. Just do `doc.parent()`.
