### ISSUE TITLE
mongoose.set is not working problem at all

### ISSUE THREAD

**Issue by Sourabh-Semalty** [Automattic/mongoose#10636]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Sourabh-Semalty** [comment]
i'll updated my mongoose in 6.0.2 but the urlparser and mongoose.set() is not working

**Comment by Kamikadze4GAME** [comment]
Hello @Sourabh-Semalty 

Please follow issue template

**Comment by vkarpov15** [comment]
Remove `mongoose.set('useNewUrlParser', true)`. It is no longer necessary in Mongoose 6

**Comment by Sourabh-Semalty** [comment]
Okay  i was saying that we pass useNewurlparser and other 4 things but actually right now in 6.0.2 the mongoose say that it is not defined


as I checked that it is deprecated 
So, you are saying we don't need to add these

**Comment by vkarpov15** [comment]
@Sourabh-Semalty yes you no longer need to set `useNewUrlParser`, `useUnifiedTopology`, `useCreateIndex`, or `useFindAndModify`
