### ISSUE TITLE
setDefaultsOnInsert behaviors as default to true, is it expected?

### ISSUE THREAD

**Issue by yz-ark7** [Automattic/mongoose#10643]
Hi,

This will be a simple question, so I didn't follow the template. The background is that we upgrade mongoose recently and discovered that the setDefaultsOnInsert is acting as default to be true. After dig into the code, figured on [this line](https://github.com/Automattic/mongoose/blame/master/lib/helpers/setDefaultsOnInsert.js#L24), i.e.

```
if (!options.upsert || shouldSetDefaultsOnInsert === false) {
    return castedDoc;
}
```

The strict === false check makes the value to be `undefined` and jump out of the if block. Is it expected?

Also, I figured that I can do `mongoose.set('setDefaultsOnInsert', false)` to toggle the default behavior. But reading through https://mongoosejs.com/docs/defaults.html , it makes feel the default behavior is `false`. Caused a bit of confusion.

Thanks!

**Comment by vkarpov15** [comment]
Yep that `if` statement is correct, it means we go through with setting defaults on insert _unless_ `setDefaultsOnInsert: false`.

`mongoose.set('setDefaultsOnInsert', false)` should disable `setDefaultsOnInsert` globally, we're updating the docs you linked to.
