### ISSUE TITLE
Enum object syntax does not work on a number path

### ISSUE THREAD

**Issue by thiagokisaki** [Automattic/mongoose#10648]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
According to [mongoose docs](https://mongoosejs.com/docs/validation.html#custom-error-messages) there are two ways to set a validator message: using array syntax or using object syntax.

Currently, the enum object syntax is not working on a number path.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const { Schema, model } = require('mongoose');

const reviewSchema = new Schema({
  comment: String,
  rating: {
    type: Number,
    enum: {
      values: [1, 2, 3, 4, 5],
      message: 'Rating must be an integer between 1 and 5',
    },
  },
});

const Review = model('Review', reviewSchema);

const review = new Review({ comment: 'Excellent!', rating: 5 });

console.log(review.validateSync());
```

Causes the error:

```Error: Review validation failed: rating: `5` is not a valid enum value for path `rating`.```

**What is the expected behavior?**
To be able to use object syntax to set an enum validator for numbers.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v14.17.3
Mongoose: v6.0.3
MongoDB: irrelevant

**Comment by thiagokisaki** [comment]
So the docs are wrong: https://mongoosejs.com/docs/schematypes.html#number-validators

**Comment by IslandRhythms** [comment]
I'm getting the same error message

```javascript
const mongoose = require('mongoose');
const { Schema, model } = mongoose;

const reviewSchema = new Schema({
  comment: String,
  rating: {
    type: Number,
    enum: {
      values: [1, 2, 3, 4, 5],
      message: 'Rating must be an integer between 1 and 5',
    },
  },
});

const Review = model('Review', reviewSchema);
async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      await mongoose.connection.dropDatabase();

      const review = new Review({ comment: 'Excellent!', rating: 5 });

    console.log(review.validateSync());
}

test();

```
