### ISSUE TITLE
Nested Map validation (Map of Map of String) allows any nested value

### ISSUE THREAD

**Issue by headlessme** [Automattic/mongoose#10644]
**Do you want to request a *feature* or report a *bug*?**
Bug (possibly Feature)

**What is the current behavior?**
When inserting values into a Map of Map of String, any values is accepted at the innermost level. I'm not sure if this should already be supported or if this actually a feature request.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const MySchema = new mongoose.Schema({
  mapOfMapOfString: {
    type: Map,
    of: {
      type: Map,
      of: String
    }
  }
})

const MyModel = mongoose.model('MyModel', MySchema)

const doc = new MyModel()
doc.mapOfMapOfString = { outer: { inner: 123 } }
doc.save()
```

**What is the expected behavior?**
Only string values are accepted as values of the nested Map.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.14.0
Mongoose 6.0.2
MongoDB 4.0.20

**Comment by IslandRhythms** [comment]
the `inner:123` is where an error should be thrown since it is declared to be only strings.

```javascript
const mongoose = require('mongoose');

const MySchema = new mongoose.Schema({
    mapOfMapOfString: {
      type: Map,
      of: {
        type: Map,
        of: String
      }
    }
  })
  
  const MyModel = mongoose.model('MyModel', MySchema)
  async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      await mongoose.connection.dropDatabase();
    const doc = new MyModel()
    console.log(doc);
    doc.mapOfMapOfString = { outer: { inner: 123 } }
    await doc.save()
    let test = await MyModel.find();
    console.log(test);
    console.log('done');
  }

  test();
```

**Comment by vkarpov15** [comment]
The issue here is that Mongoose is interpretting `{ type: Map, of: { type: Map, of: String } }` as `{ type: Map, of: Map }`, so it's losing the nested schema type.

FYI, the correct behavior here is that Mongoose automatically converts number `123` into string `'123'`, which works with d21d2b1
