### ISSUE TITLE
$expr is getting ignored after upgrade to v6

### ISSUE THREAD

**Issue by pnutmath** [Automattic/mongoose#10662]
**Do you want to request a *feature* or report a *bug*?**
This seems a bug

**What is the current behavior?**
$expr is getting ignored after upgrade to v6

**If the current behavior is a bug, please provide the steps to reproduce.**

**Schema**
```javascript

const SampleSchema = new mongoose.Schema(
  {
    date: { type: Date, required: true },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  }
);

SampleSchema.index({ date: -1 });
module.exports = moonracer.model('Sample', SampleSchema);
```

While executing this in code
```javascript
 const SampleModel =  require('./sample)

 SampleModel.find( { $expr: { $eq: [{ $year: '$date' }, 2021] } }, {date: 1}).sort({ date: -1 });
```
**mongoose generating query,log is**

`Mongoose: samples.find({  }, { sort: { date: -1 },  projection: {  date: 1,  _id: -1 }})
`

**What is the expected behavior?**

**mongoose should call following query**

`Mongoose: samples.find({ $expr: { $eq: [{ $year: '$date' }, 2021] } }, { sort: { date: -1 },  projection: {  date: 1,  _id: -1 }})
`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.22.1
MongoDB: 4.2.8
Mongoose: 6.0.4

Issue is starting from v6.x.x

**Comment by IslandRhythms** [comment]
> module.exports = moonrace.model('Sample', SampleSchema);

That's a typo right?

**Comment by IslandRhythms** [comment]
The query does go through in older versions, its in 6.x that this issue pops up

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true)
const testSchema = new mongoose.Schema({ date: {type: Date, required: true }}, {timestamps: {createdAt: 'created_at', updatedAt: 'updated_at'}})

testSchema.index({ date: -1});

const Test = mongoose.model('Test', testSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      });
      await mongoose.connection.dropDatabase();

      await Test.find( { $expr: { $eq: [{ $year: '$date' }, 2021] } }, {date: 1}).sort({ date: -1 });
}

test();
```
