### ISSUE TITLE
Unable to connect using unencoded password in dbUri + discrepancy in 6.0.3 documentation about useNewUrlParser

### ISSUE THREAD

**Issue by jplwood** [Automattic/mongoose#10665]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Using Mongoose 6.0.4, I am unable to use a `dbUri` that contains unencoded characters

**If the current behavior is a bug, please provide the steps to reproduce.**
When using Mongoose 5.12.5 with `useNewUrlParser: true` and my dbUri that contains a password that is not encoded, I can open a connection using `mongoose.createConnection` without issue. 
Example: 
```tsx
    const connection = mongoose.createConnection(dbUri, {
        dbName,
        useNewUrlParser: true,
        useUnifiedTopology: true,
        bufferCommands: false,
        bufferMaxEntries: 0,
        useFindAndModify: false,
        useCreateIndex: true,
    });
```

Using this same version (5.12.5), if I remove `useNewUrlParser: true`. I get this error as expected when trying to connect:
```
Password contains an illegal unescaped character
```

Now, when I upgrade to Mongoose 6.0.4, many of the options that were previously required to suppress deprecation warnings, were removed from `MongooseOptions` and `ConnectOptions` typescript types (see [No More Deprecation Warning Options](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options)). With this in mind, I now make my connections this way:

```tsx
    const connection = mongoose.createConnection(dbUri, {
        dbName,
        bufferCommands: false,
    });
```

However, when using the exact same `dbUri`  in Mongoose 6.0.4, minus the deprecated options I noted above, I get a similar error to the one I got when using Mongoose 5.x.x without `useNewUrlParser: true`. 

```
MongoParseError: Password contains unescaped characters
```

This potentially implies a couple things:
- Mongoose 6.0.4 still requires you to set `useNewUrlParser: true`
- The [migration guide](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options) is incorrect
  - Aside on this: The Mongoose 6.0.4 docs still contain documentation telling you to set these options, which you are unable to do when using typescript (see [Deprecation Warnings](https://mongoosejs.com/docs/deprecations.html)). 
- And the [`ConnectOptions`](https://github.com/Automattic/mongoose/blob/a4329ec3ccd3a42f010b5b9402e8aa00a0df646b/index.d.ts#L253) and [`MongooseOptions`](https://github.com/Automattic/mongoose/blob/a4329ec3ccd3a42f010b5b9402e8aa00a0df646b/index.d.ts#L148) types are wrong

**What is the expected behavior?**
To be able to use a dbUri that contains unencoded password characters

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node.js: v16.2.0
- NPM: 7.14.0
- Mongoose: 5.12.5 -> 6.0.4
- DocumentDB: not sure
- my tsconfig: 
```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "rootDir": "./",
    "outDir": "build",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "baseUrl": "./", 
  },
  "exclude": [
    "node_modules",
    "coverage",
    "cypress",
    "build",
    "**/*.test.js",
    "**/*.test.ts",
    "**/*.spec.js"
  ],
  "include": [
    "src/**/*.ts",
    "./jest-setup.ts"
  ]
}
```

**Comment by vkarpov15** [comment]
We can definitely confirm that `useNewUrlParser` is not required nor supported in Mongoose 6, and I can confirm I can also connect to a MongoDB Atlas cluster with both `pa$$word` and `pass[wor]d` as passwords.

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  console.log('Mongoose version:', mongoose.version);
  await mongoose.connect('mongodb+srv://user:pa$$word@OMITTED.mongodb.net/myFirstDatabase?retryWrites=true&w=majority');

  console.log('Connected');
}
```

This could be a DocumentDB issue: worth noting that Mongoose does not officially support DocumentDB. Either way, is there anything stopping you from calling `encodeURIComponent()` on your password?

**Comment by jplwood** [comment]
> This could be a DocumentDB issue: worth noting that Mongoose does not officially support DocumentDB. Either way, is there anything stopping you from calling encodeURIComponent() on your password?

No, it was just a surprise that it stopped working with the new version where it worked in the old. I think we will just use `encodeURIComponent` when we finish upgrading to the new major version. Interesting though about DocDB, didn't realize there isn't support for it. Thanks for the info.
