### ISSUE TITLE
Mongoose post init hook returning partial document

### ISSUE THREAD

**Issue by sasasavic82** [Automattic/mongoose#10664]
Mongoose middleware post init hook is returning only a partial document.

It returns _id and one other property (called commitments), even though the budget schema has quite a number of properties (20+).

NOTE: there's nothing special about commitments property. Also, the record is fully enriched with data.

`BudgetSchema.post<IBudget>("init", function(doc) { console.log(doc); });`

I should add, my requirement is to modify the fetched document before it is returned.

**Comment by IslandRhythms** [comment]
Please include the code that is demonstrating this problem
