### ISSUE TITLE
Buffer timeout error even after connected to database.

### ISSUE THREAD

**Issue by scientific-dev** [Automattic/mongoose#10667]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
I am using mongoose with next.js with this [template](https://github.com/vercel/next.js/tree/canary/examples/with-mongodb-mongoose). The error i am getting...

![error](https://user-images.githubusercontent.com/69678617/132043687-8608c372-e2bc-423c-9a97-a7a6fede188a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
My site is hosted on vercel serverless with next.js.
Here is the endpoint part:

```js
import { createSimplifiedJSON } from "../../utils";
import { Page } from "../../utils/schemas";

let cached;

export default async (req, res) => {
    if (req.method == "GET" && req.headers.host == process.env.HOST) {
        if (cached && Date.now() - cached.createdAt > 300000) res.status(200).json(cached);
        const pages = (await Page.find()).map(createSimplifiedJSON);
        cached = {
            createdAt: Date.now(),
            recents: pages.sort((a, b) => b.updatedAt - a.updatedAt).slice(0, 10),
            randoms: shuffle(pages).slice(0, 8)
        };

        res.status(200).json(cached);
    } else res.status(403).json({});
};
```

The `connectMongoose` part,

```js
import mongoose from "mongoose";

export default async function connectMongoose() {
    if (!mongoose.connection?.readyState) {
        if (!process.env.MONGO_URI) throw "No mongo url has been provided";
        await mongoose.connect(process.env.MONGO_URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
            useFindAndModify: false,
            useCreateIndex: true,
            bufferCommands: false,
            bufferMaxEntries: 0
        });
    }
}
```

The error is supposed to have if we access the models before the mongoose connects is what the documentation says but it is connected and readyState is 1. I am still getting the same error. Am i doing some mistake or does this issue needs more clear explanation?

**What is the expected behavior?**
To not have the timeout error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
**Node.js:** v14.x
**Mongoose:** v5.11.15

**Comment by IslandRhythms** [comment]
From what I'm reading, the `if(!mongoose.connection?.readyState)` won't execute the connect becaue its negating 1. So instead of `if(1)` its becoming `if(0)` and not executing.

**Comment by scientific-dev** [comment]
> From what I'm reading, the `if(!mongoose.connection?.readyState)` won't execute the connect becaue its negating 1. So instead of `if(1)` its becoming `if(0)` and not executing.

Yeah if it is `0` means it is disconnected and has to be connected isn't it?

**Comment by scientific-dev** [comment]
I found the reason for this error. I was creating 2 clients one in backend and another in frontend and only frontend mongoose client was connected not the backend one.
