### ISSUE TITLE
mongoose.Types.ObjectId.isValid and mongoose.Types.ObjectId.toHexString missing from type definitions

### ISSUE THREAD

**Issue by mstaicu** [Automattic/mongoose#10678]
**What is the current behavior?**

The `mongoose.Types.ObjectId.isValid` and `mongoose.Types.ObjectId.toHexString` types are no longer present in `"mongoose": "^5.12.2"` ( which resolves to `"version": "5.13.8"` )

When trying to access any of those properties I get a: `Property 'isValid' does not exist on type 'ObjectIdConstructor'.ts(2339)`

In `mongoose`s' index.d.ts you got:

`const ObjectId: ObjectIdConstructor;` pointing to:

```
// Expose static methods of `mongodb.ObjectID` and allow calling without `new`
    type ObjectIdConstructor = typeof _ObjectId & {
      (val?: string | number): ObjectId;
    };
```

`_ObjectId` pointing to:

```
class _ObjectId extends mongodb.ObjectID {
      _id?: ObjectId;
    }
```

`mongodb.ObjectID` pointing to:

`export { Binary, DBRef, Decimal128, Double, Int32, Long, MaxKey, MinKey, ObjectID, ObjectId, Timestamp } from "bson";`

`ObjectID` pointing to nothing. `@types/bson` is a folder that has just the `package.json`, LICENSE and README. The content of its `package.json`:

```
{
    "name": "@types/bson",
    "version": "4.2.0",
    "typings": null,
    "description": "Stub TypeScript definitions entry for bson, which provides its own types definitions",
    "main": "",
    "scripts": {},
    "author": "",
    "license": "MIT",
    "dependencies": {
        "bson": "*"
    }
}
```

I have an older repo with the same dependencies, i.e. `"mongoose": "^5.12.2"`, and with that I seem to get a `@types/bson` that has an `index.d.ts` in its package. The content of its `package.json`:

```
{
    "name": "@types/bson",
    "version": "4.0.3",
    "description": "TypeScript definitions for bson",
    "license": "MIT",
    "contributors": [
        {
            "name": "Hiroki Horiuchi",
            "url": "https://github.com/horiuchi",
            "githubUsername": "horiuchi"
        },
        {
            "name": "Federico Caselli",
            "url": "https://github.com/CaselIT",
            "githubUsername": "CaselIT"
        },
        {
            "name": "Justin Grant",
            "url": "https://github.com/justingrant",
            "githubUsername": "justingrant"
        },
        {
            "name": "Mikael Lirbank",
            "url": "https://github.com/lirbank",
            "githubUsername": "lirbank"
        }
    ],
    "main": "",
    "types": "index.d.ts",
    "repository": {
        "type": "git",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
        "directory": "types/bson"
    },
    "scripts": {},
    "dependencies": {
        "@types/node": "*"
    },
    "typesPublisherContentHash": "de339c6ae3194d7c34d771d4580048f1007707bafc646731b539c3a79638ebe9",
    "typeScriptVersion": "3.2"
}
```

Whats the solution here? I tried locking down `mongoose` to a specific version in order to get its dependencies to install, but that didn't work. NPM states that the types for BSON are no longer an independent package. Thoughts?

PS: `bson` does not provide its own types, as per the description of the latest `@types/bson`

Also, `mongoose` requires `"@types/mongodb": "^3.5.27"` but in my working repo that resolves to

```
 "@types/mongodb": {
      "version": "3.6.18",
      "resolved": "https://registry.npmjs.org/@types/mongodb/-/mongodb-3.6.18.tgz",
      "integrity": "sha512-JSVFt9p0rTfZ4EgzXmVHUB3ue00xe3CRbQho8nXfImzEDDM4O7I3po1bwbWl/EIbLENxUreZxqLOc8lvcnLVPA==",
      "requires": {
        "@types/bson": "*",
        "@types/node": "*"
      }
    },
```

And in the repo that this doesn't work, it resolves to 

```
"@types/mongodb": {
      "version": "3.6.20",
      "resolved": "https://registry.npmjs.org/@types/mongodb/-/mongodb-3.6.20.tgz",
      "integrity": "sha512-WcdpPJCakFzcWWD9juKoZbRtQxKIMYF/JIAM4JrNHrMcnJL6/a2NWjXxW7fo9hxboxxkg+icff8d7+WIEvKgYQ==",
      "requires": {
        "@types/bson": "*",
        "@types/node": "*"
      }
    },
```

Could it be that `@types/mongodb` broke the camel's back?

Digging further, it seems that when you go to the landing page on NPM for the `mongodb` types, it says that mongo provides its own types, but when I go in my dependency tree, there is no such type definition file provided by `mongodb`, so what is going on?

**Comment by mstaicu** [comment]
As a temporary solution I decided to go ahead and install as a development dependency the 4.0.3 version of `@types/bson`

**Comment by vkarpov15** [comment]
Confirmed this is an issue with the latest version of `@types/bson`, apparently they removed the entire contents of the package in a minor release :man_shrugging: 

Should be fixed by https://github.com/Automattic/mongoose/commit/fc5fc7e0081bd58774e18c4ca53da59c2ff412b5, please upgrade to v5.13.9 for the fix. We'll be releasing v5.13.9 shortly.

**Comment by mstaicu** [comment]
Thanks @vkarpov15 !

**Comment by firehudson** [comment]
I'm trying to migrate from mongoose v4 to v6 and I came across the same issue.

Not sure if it's still helpful, but mongoose now have moved this method from `ObjectId` to `mongoose` itself.
So simply use `mongoose.isValidObjectId(...)` 😃
