### ISSUE TITLE
Add omitUndefined to 6.0 migration guide

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#10672]
Re: #10649

**Comment by toucham** [comment]
Please add this change into [mongoose doc](https://mongoosejs.com/docs/api.html). The doc seems to be not updated and says that the `omitUndefined` is still one of the option for write operations.

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/a97e6cc2476665e7c07e67bce3843b3184141a4e
