### ISSUE TITLE
How to make where clause after .populate()

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#1068]
I need something like this:

```
Comment.findById('some id')
   .populate('_user')
   .where('_user.scope').equals(0))
   .exec(function (err, doc) {

    });
```

So I need to get some comments which created by an user who has srope: 0.

**Comment by Suraj01071999** [comment]
@aheckmann i am having the same issue as @skotchio , first i have to find data, then populate the child document and then to get the data according to the child. same as @skotchio

**Comment by ansitdevfive** [comment]
@aheckmann i am also facing this issue ,i am doing this as shown Below.

`Notification.populate({
path:"patientId",
match:{provider:currentUser},
select:"firstName lastName"
}).where('patientId').ne(null).skip(pageSize * pageNumber - pageSize)
.limit(pageSize).lean()`

so output should be Those Notification comes where patient's provider equal to  current user if any patient's provider not equal to  current user it should not come,
But it's comming with Null PatientId field.
