### ISSUE TITLE
[Docs] Unable to click on h2 headers to get anchor URL

### ISSUE THREAD

**Issue by mjfwebb** [Automattic/mongoose#10682]
For example in https://mongoosejs.com/docs/migrating_to_6.html, clicking on _**Version Requirements**_ changes the URL to https://mongoosejs.com/docs/migrating_to_6.html#version-requirements but clicking on _**TypeScript changes**_ does not change anything.

**Comment by DavideViolante** [comment]
Works fine to me.

**Comment by vkarpov15** [comment]
Fixed in #10748
