### ISSUE TITLE
Typescript generic schema usage

### ISSUE THREAD

**Issue by GalDayan** [Automattic/mongoose#10684]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Typescript isn't shouting on missing properties, but it does shouting on extra properties or different naming properties.

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/24251369/132179038-dd045d4c-fd0c-4bf0-94b7-a27691650302.png)

**What is the expected behavior?**
Typescript isn't shouting on missing properties, but it does shouting on extra properties or different naming properties.
For example, in the above code, property `b` is missing in the schema, everything seems to work. (typescript compiled without errros)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node LTS (14.17)
- Mongo 4.3
- Mongoose 6.0.4

**Comment by vkarpov15** [comment]
This is by design currently, because you don't necessarily have to define all schema properties in the `new Schema(schemaDefinition)` call. For example, `IContract` may have `createdAt` and `updatedAt` properties, which are added to the schema by `timestamps: true`. Or you may call `ContractSchema.add()` later.

Can you please elaborate on what problems this behavior is causing?

**Comment by GalDayan** [comment]
Thanks for the fast response. 
Yeah, the problem is starting when using `strict: true` option. Thus, when you're adding a new property in the interface `IContract` and forgetting to add it also in mongoose schema, you will find this only in production runtime instead of fail when compiling the typescript file.

@vkarpov15

**Comment by vkarpov15** [comment]
`strict: 'throw'` doesn't mean that `b` isn't added by a plugin or in a later `Schema#add()` call. That's why we don't throw an error there.

**Comment by GalDayan** [comment]
Got ya. Is there any option to make it required and not partial? @vkarpov15

**Comment by vkarpov15** [comment]
@GalDayan you can work around this by using a separate type definition for the schema definition object as shown below.

```ts
import { Schema, SchemaDefinition, Model, model } from 'mongoose';
  
interface IContract {
  a: string;
  b: string;
}

// Below will fail to compile if `a` or `b` are omitted
// error TS2741: Property 'b' is missing in type '{ a: StringConstructor; }' but required in type 'Required<{ a?: SchemaDefinitionProperty<string>; b?: SchemaDefinitionProperty<string>; }>'
const schemaDef: Required<SchemaDefinition<IContract>> = { a: String, b: String };

const schema = new Schema<IContract>(schemaDef);
```
