### ISSUE TITLE
TypeScript: Add support for arbitrary keys in QueryOptions

### ISSUE THREAD

**Issue by adarshmadrecha** [Automattic/mongoose#10688]
**Do you want to request a _feature_ or report a _bug_?**
feature

## Requirement Example
When a record is created in _Sales_ table, a middleware is triggered which updates _Inventory_ table. In this middleware, we need access to _User_ to store which user triggered update in _Inventory_.

## How I solve it currently
When the Shop Query is called, a meta object is passed in the `options`. Then in the middleware, I call `query.getOptions()` to get this meta object.

## Feature Request
Add official support for meta object. Currently, the VS code gives warning that there is NO Meta property which can be passed in the options.

## Sample Code
```js
//  Model & Schema
const salesSchema= new Mongoose.Schema({
   //  schema definition
});
const inventoySchema= new Mongoose.Schema({
   //  schema definition
});
salesSchema.post(['updateOne', 'findOneAndUpdate'], { document: false, query: true }, async function () {
  updateInventory(this)
});

export const Sales = Mongoose.model('sales', salesSchema);
export const Inventory= Mongoose.model('sales', inventoySchema);
```

```js
// Middleware function
export async function (shopQuery) {
  const meta = shopQuery.getOptions()?.meta ?? {}
  // User is now available in this meta object.
  const {user} = meta;
  //  Now when I am updating Inventory, I can update the userId field 
  await Inventory.create({
    /** other fields  */
    userid: user.id
  })
}
```

```js
// Sales Update Function 
const sales = await Sales.findByIdAndUpdate(
    id,
    { ...req.body },
    // NOTE: passing user in options which can then be accessed by middleware
    { new: true, meta: {user:{id:1234}} }
)
```

**Comment by vkarpov15** [comment]
We'll add support for arbitrary keys in `QueryOptions`. AFAIK passing any key you want to QueryOptions should be fine, it's just a TypeScript quirk.
