### ISSUE TITLE
price: CastError: Cast to Number failed for value “۳۵۶۰۰۰” (type string) at path “price"

### ISSUE THREAD

**Issue by Siamakkarimi** [Automattic/mongoose#10685]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Siamakkarimi** [comment]
Hello,
In my react project, I saved my products' Properties such as name, price, and quantity in English by using the following code: 
const { data } = await axios.post('/api/create-product', {
        ...values,
      })
But when I wanted to send the price, for example, in Persian/Arabic(۳۵۶۰۰۰ which is 35600), I got the following error:

 price: CastError: Cast to Number failed for value “۳۵۶۰۰۰” (type string) at path “price

which I think I should encode Persian numbers before sending to the server for saving in MongoDB.
I would be appreciated if you could help me with it. 
Best regards.

**Comment by vkarpov15** [comment]
Mongoose doesn't support this, but this SO thread has a few ideas on how you might convert Persian/Arabic numbers to numbers that Mongoose understands: https://stackoverflow.com/questions/31439604/how-to-convert-persian-and-arabic-digits-of-a-string-to-english-using-javascript
