### ISSUE TITLE
Eslint complains LeanDocument<T> if T type contains Document keys

### ISSUE THREAD

**Issue by tonynguyenit18** [Automattic/mongoose#10690]
**Bug**
I have schema
```ts
export const Test = new Schema({
  id: {
    type: ObjectId,
    required: true
  },
  results: {
    type: [
      {
        model: {
          type: String,
          required: true
        }
      }
    ]
  }
})
```

==> I create interface to represent schema, for fetching Test
```ts
interface IPredictionResult {
    model: string
}
interface ITest {
  results: IPredictionResult[]
}

interface ITestDocument extends ITest, Document  {
}
```

I have a function to get test record
```ts
 async findById(testId: string): Promise<ITest> {
    const test = await testModel.findById(assessmentId).lean()
    return test
 }
```
**What is the current behavior?**
☝️ findById will cause an error message saying 
```bash
Type 'LeanDocument<ITestDocument>' is not assignable to type 'ITest'.
  Types of property 'results' are incompatible.
    Type 'LeanDocument<IPredictionResult>[]' is not assignable to type 'IPredictionResult[]'.
      Property 'model' is missing in type 'LeanDocument<IPredictionResult>' but required in type 'IPredictionResult'.ts(2322)
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "types": ["node", "jest"],
  },
  "exclude": ["node_modules", "dist"]
}


```

**What is the expected behavior?**
Eslint should not raising error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^5.12.12",
Node: 12.x

**Code Problem**
I found we have lean type at https://github.com/Automattic/mongoose/blob/4d48869992897b77490eabf6fd64a032de6103b3/index.d.ts#L2652
```ts
export type LeanDocument<T> = Omit<_LeanDocument<T>, Exclude<keyof Document, '_id' | 'id' | '__v'> | '$isSingleNested'>;
```
This seems recursively apply LeanDocument to attribute of the object because in my result type I have model which is required
AND `Document` has `model` attribute too => `Omit<_LeanDocument<T>, Exclude<keyof Document, '_id' | 'id' | '__v'> | '$isSingleNested'>;` will make `model`

====> error

**Comment by vkarpov15** [comment]
The error you pasted looks like a TypeScript error, not an ESLint error. Either way, I'm unable to repro this, the below script compiles without error.

```ts
import { Schema, Document, model } from 'mongoose';

const Test = new Schema({
  id: {
    type: 'ObjectId',
    required: true
  },
  results: {
    type: [
      {
        model: {
          type: String,
          required: true
        }
      }
    ]
  }
})

interface IPredictionResult {
    model: string
}
interface ITest {
  results: IPredictionResult[]
}

interface ITestDocument extends ITest, Document  {}

const testModel = model<ITestDocument>('Test', Test);

 async function findById(testId: string): Promise<ITest> {
    const test = await testModel.findById('0'.repeat(24)).lean();
    return test
 }
```

Can you please modify the above script to demonstrate your issue?

One potential workaround is to remove `interface ITestDocument extends ITest, Document` and just do `const testModel = model<ITest>('Test', Test);` . That's what our [TypeScript docs](https://mongoosejs.com/docs/typescript.html) recommend.
