### ISSUE TITLE
How to mock/stub variable $$NOW

### ISSUE THREAD

**Issue by macelai** [Automattic/mongoose#10707]
Hey everyone, 

I'm trying to write tests to see if something happens after some time. From my research I should use `sinon` and `useFakeTimers`, it seems to be working when I do `new Date()`, but that doesn't apply to the `$$NOW`, what am I missing here?

**Comment by AbdelrahmanHafez** [comment]
`$$NOW` is evaluated on the MongoDB server, you can't stub that from the node application.

You may need to stub the function that uses `$$NOW`  and not call the databse in the first place.
