### ISSUE TITLE
this.findOne(...).select is not a function

### ISSUE THREAD

**Issue by sayantan300** [Automattic/mongoose#10703]
![Screenshot from 2021-09-10 05-40-36](https://user-images.githubusercontent.com/62213554/132778440-46ca2b28-6d0c-44e8-9a40-a80d8cdf3934.png)
Using nodejs v16.9.0
mongoose v5.13.3

this error didnt happen before, it just started throwing errors this early morning..

(um, i am saving "Infinity" in a number type , it was infinity before too, but when the user earns like +5, inifinity+5=infinity, so the document being asked to save might not have any edits on it actually..

**Comment by IslandRhythms** [comment]
You're providing a screenshot of the mongoose code. We need to see the code you are running that is throwing this error.

**Comment by sayantan300** [comment]
> You're providing a screenshot of the mongoose code. We need to see the code you are running that is throwing this error.

ok, but did you asked for access to my synk account or what?

**Comment by sayantan300** [comment]
so heres the express api router code:
```js
router.get("/earn",(req, res)=>{
 if(publicbot.cooldownearn.has(res.locals?.user?.id)){
  res.json({err: "cooldown"});
}
else {
  Users.findOne({id: res.locals?.user?.id}).then(user=>{
    if(!user) res.json({err:"not_logined"});
    else {
     let act = false;
     if(privatebot.isInMain(res.locals?.user?.id)){
     act = privatebot.guilds.cache.get("602906543356379156").members.cache.get(res.locals?.user?.id).presence.activities.filter(e=>{return (e.type=="CUSTOM" && (e.state.includes("dscrdly.com") || e.state.includes("discord.rovelstars.com")))});
     if(act.length==0) act=false;
     else act=true;
     }
      const c = Math.floor(Math.random()*10)+1;
      user.bal+=c;
      if(act) user.bal+=10;
      user.save();
      res.json({coins: c, bal: user.bal, lis:act, approxbal: rovel.approx(user.bal)});
      publicbot.cooldownearn.add(res.locals?.user?.id);
      setTimeout(()=>{
       publicbot.cooldownearn.delete(res.locals?.user?.id);
      }, 60000);
    }
  })
}
})
```

(my full repo is here if you wanted to checkout https://github.com/rovelstars/discord-list)
so my user.bal for my account in db has `Infinity` instead of a number (infinity is a no=umber ofc)
so infinity + random amount = infinity
therefore the user object would have no changes...

so can I expect a fix for allowing non edited data to be saved without any problems?

**Comment by IslandRhythms** [comment]
> Users.findOne({id: res.locals?.user?.id}).then(user=>{
    if(!user) res.json({err:"not_logined"});
    
    `res` is not defined anywhere

**Comment by IslandRhythms** [comment]
Is that the entire stack trace or only part of it?

**Comment by sayantan300** [comment]
> Is that the entire stack trace or only part of it?

The entire stack trace.

**Comment by sayantan300** [comment]
Also, no idea why it's working now, so I would like to close this.
