### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by WHK102** [Automattic/mongoose#10713]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

after install mongoose show me a error

```
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

in a clean installation run the following commands

```
$ npm init;
$ npm install mongoose;
$ echo "const mongoose = require('mongoose');" > index.js
$ node index.js;
```

**What is the expected behavior?**

show the error

```
/app/node_modules/whatwg-url/dist/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/app/node_modules/whatwg-url/dist/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/whatwg-url/dist/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.

```
$ node -v
v14.17.5

$ npm -v
6.14.14

$ sudo docker exec -it database-mongodb bash;
root@37127c24c366:/# mongo
MongoDB shell version v5.0.2
...

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

$ tail -13 package.json 
    "dependencies": {
        "bcryptjs": "^2.4.3",
        "body-parser": "^1.19.0",
        "cors": "^2.8.5",
        "dotenv": "^10.0.0",
        "express": "^4.17.1",
        "joi": "^17.4.2",
        "jsonwebtoken": "^8.5.1",
        "mongodb": "^4.1.1",
        "mongoose": "^6.0.5",
        "uuid": "^8.3.2"
    }
}
...

Reference: https://github.com/jsdom/whatwg-url/issues/209

**Comment by vkarpov15** [comment]
Take a look at https://github.com/Automattic/mongoose/issues/10638. Are you using Jest? If so, take a look at https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test.

**Comment by WHK102** [comment]
I don't use reactjs.

I saw that issue but I could not answer in the same thread to clarify that it is not solved with an update or changing the framework, that's why I had to make a new thread.

**Comment by WHK102** [comment]
I resolve the problem, i have installed two version of node but one from apt and other from `n` package manager, but in the package.json i declared start scripts as: `"start": "/usr/bin/node index.js"`:

```
$ which nodejs
/usr/bin/nodejs
$ which node
/usr/local/bin/node
$ nodejs -v
v10.19.0
$ node -v
v14.17.5
```

My script call `/usr/bin/node` but it is referenced to `/usr/bin/nodejs`. Works uninstalling nodejs from apt using `apt remove nodejs` and change full path to relative path, like as `"start": "nodejs index.js"`. Now works fine :D
