### ISSUE TITLE
ParamsDictionary should allow any value type

### ISSUE THREAD

**Issue by dillonm197** [Automattic/mongoose#10717]
Since mongoose supports [Sanitation Middlewares](https://express-validator.github.io/docs/filter-api.html), the `ParamsDictionary` interface should allow `any` for value types.

```
export interface RequestHandler<
    P = ParamsDictionary,
    ResBody = any,
    ReqBody = any,
    ReqQuery = ParsedQs,
    Locals extends Record<string, any> = Record<string, any>
>
```

Current:
```
export interface ParamsDictionary {
    [key: string]: string;
}
```

Proposed:
```
export interface ParamsDictionary {
    [key: string]: any;
}
```

**Comment by vkarpov15** [comment]
What is `ParamsDictionary`? That isn't in Mongoose's `index.d.ts` file.

**Comment by dillonm197** [comment]
Wrong library. This was meant to be posted [here](https://github.com/expressjs/express/issues/4701).
