### ISSUE TITLE
Accessing subproperties of `this` results in TypeError: Cannot read property 'call' of undefined 

### ISSUE THREAD

**Issue by venku122** [Automattic/mongoose#10712]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
This bug is an edge case involving an uncommon use case. I am using mongodbMemoryServer as a part of my Jest unit tests.
We are moving from a single default `mongoose.connection` to using multiple `mongoose.createConnection()` calls to support connecting to different databases.

When running the application on a real Mongo connection, everything works fine. When running in the jest tests, with mongo memory server, `this` calls for Mongoose fail with the following error.

```
TypeError: Cannot read property 'call' of undefined

      schemaPropertyA: {
        type: Number,
        default() {
          return this.schemaPropertyX.schemaPropertyY;
        },
      },
```

This error emits during `default()` function calls as well as in model hooks using `this`.

Diving deeper,
The error is actually in this file
https://github.com/Automattic/mongoose/blob/master/lib/helpers/document/compile.js#L171

```
return this[getSymbol].call(this.$__.scope || this, path);
```
`this` does not have `getSymbol` so the `.call()` fails as it is `undefined`.

I've taken the node-inspector through this function and the rest of `compile()` and checked a few things.

`path` during this call has the value `schemaPropertyX.schemaPropertyY` but `this` is a Document object with only `schemaPropertyY` and other properties on that level.

Accessing top-level properties works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

I think this may be a configuration issue specifically with my project. For reference, this issue did not appear when we were using the `mongoose.connection`.

The jest setup looks like this.

```
    this.server = await MongoMemoryServer.create();
    const coreUri = this.server.getUri();
    const mongoOptions = {
      dbName: 'verifyMASTER',
      monitorCommands: true,
      useNewUrlParser: true,
      useUnifiedTopology: true,
    };
    try {
      await Promise.all([
        mongoose.connect(coreUri, mongoOptions),
        this.mockConnections.coreMongoConnection.openUri(coreUri, mongoOptions),
      ]);
    } catch (error) {
      console.error(error);
    }
```

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "es2020",
    "lib": ["es6", "es7", "es2018","DOM", "ES2020", "esnext.asynciterable"],
    "sourceMap": true,
    "allowJs": false,
    "checkJs": false,
    "jsx": "react",
    "noEmitOnError": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "noEmit": true,
    "removeComments": true,
    "downlevelIteration": true,
    "baseUrl": "./",
    "resolveJsonModule": true
  },
  "exclude": ["node_modules"],
}
```

**What is the expected behavior?**
`this` should allow multi-level property access without erroring, including default initialization and hooks.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose - ^5.7.1
MongoDB - 4.2.11
NodeJS - 12.13.0

**Comment by IslandRhythms** [comment]
Are you reporting a bug or asking for help. You state that this is a bug but you also say
> I think this may be a configuration issue specifically with my project. For reference, this issue did not appear when we were using the mongoose.connection.

**Comment by venku122** [comment]
This is most likely a bug but I am asking for help in finding the cause of it.

`compile` shouldn't be attaching the wrong `this` for the getters.

I am looking for anyone with expertise specifically with `compile` that might know why something would cause this undefined behavior.

**Comment by vkarpov15** [comment]
Do you have multiple versions of Mongoose installed? Try running `npm list | grep "mongo"` and paste the output.

Also, when you say "the jest setup looks like this", do you mean you're using `globalSetup()` or `globalTeardown()`? Do **not** use those: https://mongoosejs.com/docs/jest.html#globalsetup-and-globalteardown

In general, I would highly recommend using a different test framework, Jest is an anti-pattern.
