### ISSUE TITLE
MongoParseError: credentials must be an object with 'username' and 'password' properties

### ISSUE THREAD

**Issue by saveman71** [Automattic/mongoose#10726]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

As described in https://mongoosejs.com/docs/connections.html#options:

```js
let connect = mongoose.connect('mongodb://localhost:27018/test', {
	user: 'admin',
    pass: 'password',
});
```

Should forward the auth to the nodejs driver. Looking at the object sent to the driver:

```js
{
  authSource: 'admin',
  auth: { user: 'admin', password: 'password' },
  driverInfo: { name: 'Mongoose', version: '6.0.5' }
}
```

Looking at https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md#authentication, it says the expected format is `username` and not `user`, as the error suggests:

`MongoParseError: credentials must be an object with 'username' and 'password' properties`.

Noting that the following works:

```js
let connect = mongoose.connect('mongodb://localhost:27018/test', {
	auth: {
		username: 'admin',
		password: 'password',
	}
});
```

Either the doc need to be updated to remove the user/pass backwards compat (which appears broken) or it needs to set `username` instead of `user` in the `auth` object.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

MongoDB 3.4
Mongoose 6.0.5
NodeJS v14.17.6

Here is the code responsible for the bug:

https://github.com/Automattic/mongoose/blob/e6820eecbccb66e35d316f84287d3d1484f789dc/lib/connection.js#L742-L750

**Comment by Peculiar-codes** [comment]
Still doesn't seems to work well here,despite putting it as an object
Auth:{username:""}

**Comment by vkarpov15** [comment]
@Peculiar-codes open a new issue and follow the issue template please
