### ISSUE TITLE
[bug] isValidObjectId: shows `true` even if the string is invalid

### ISSUE THREAD

**Issue by SwapnilSoni1999** [Automattic/mongoose#10736]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
currently the method `mongoose.isValidObjectId` or `mongoose.Schema.ObjectId.isValid` shows wrong return value
for the following strings
```
test-again_0 // returns true; behaviour: incorrect
test-again_1 // returns true; behaviour: inocorrect
...
test-again_9 // returns true; behaviour: incorrect

test-again_99 // returns false; behaviour: correct
```
I think the current code is just validating string length and directly returning true if length matches.

**If the current behavior is a bug, please provide the steps to reproduce.**
For the following code it should show `false` in return value but its returning `true`

```js
mongoose.isValidObjectId('test-again_9')
```

**What is the expected behavior?**
Here any single digit from `0-9` shows valid ObjectId but it shouldn't.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
MongoDB: v5.0.2
Mongoose: v6.0.2
Node.js: v16.3.0

**Comment by sean-daley** [comment]
Looks like this is discussed in another issue a couple of months ago. I'll just point to that comment since it has links to the FAQ about this issue as well as the older issue where it was first discussed.

https://github.com/Automattic/mongoose/issues/10330#issuecomment-855225429

**Comment by SwapnilSoni1999** [comment]
> Looks like this is discussed in another issue a couple of months ago. I'll just point to that comment since it has links to the FAQ about this issue as well as the older issue where it was first discussed.
> 
> [#10330 (comment)](https://github.com/Automattic/mongoose/issues/10330#issuecomment-855225429)

Considering the Mongoose FAQ, They say any 12 character string is valid. But MongoDB doc says it consists different segments
![Screenshot_20210916_212136](https://user-images.githubusercontent.com/25403317/133644607-d1a0597d-d738-4e67-8f43-be559faf8ec1.png)
They say it does consist unix timestamp in ObjectId, So shouldn't we validate it?

**Comment by sean-daley** [comment]
So it looks like this (or similar) has been reported to the mongodb folks in the past as a defect as well:
https://github.com/mongodb/js-bson/issues/365

And they've similar responded with working as intended with their reasons.

While I agree that probably nobody in their right mind would use `test-again_0` as an ObjectId, it looks like you can do that:
```
const mongoose = require("mongoose");

const { Schema } = mongoose;

const userSchema = new Schema({
  email: {
    type: Schema.Types.String,
    required: true
  },
  username: {
    type: Schema.Types.String,
//    index: false,
    unique: false,
    required: true
  },
});

const User = mongoose.model("User", userSchema);

const main = async () => {
   const client = await mongoose.connect('mongodb://localhost:27017/test', {
  connectTimeoutMS: 3000
});
  const user = new User({
    _id: mongoose.Types.ObjectId("test-again_0"),
    username: "username",
    email: "user@example.com",
  });

  const dbUser = await user.save();
  console.log(dbUser.toObject());
  client.disconnect();
}

main();
```

This generates:
`{ "_id" : ObjectId("746573742d616761696e5f30"), "email" : "user@example.com", "username" : "username", "__v" : 0 }`
in the DB because "test-again_0" is treated as a binary sequence and converted to that. And that objectId has a timestamp (just a decade in the future):

```
> ObjectId("746573742d616761696e5f30").getTimestamp()
ISODate("2031-11-18T22:02:28Z")
```

You can also bypass mongoose altogether and go directly to the bson package that mongodb maintains:
```
const BSON = require('bson')

const objectId = new BSON.ObjectId('test-again_0')

console.log(objectId)
console.log(objectId.getTimestamp())
```

This evaluates to:
```
$ node bson.js
new ObjectId("746573742d616761696e5f30")
2031-11-18T22:02:28.000Z
```

**Comment by SwapnilSoni1999** [comment]
> So it looks like this (or similar) has been reported to the mongodb folks in the past as a defect as well:
> [mongodb/js-bson#365](https://github.com/mongodb/js-bson/issues/365)
> 
> And they've similar responded with working as intended with their reasons.
> 
> While I agree that probably nobody in their right mind would use `test-again_0` as an ObjectId, it looks like you can do that:
> 
> ```
> const mongoose = require("mongoose");
> 
> const { Schema } = mongoose;
> 
> const userSchema = new Schema({
>   email: {
>     type: Schema.Types.String,
>     required: true
>   },
>   username: {
>     type: Schema.Types.String,
> //    index: false,
>     unique: false,
>     required: true
>   },
> });
> 
> const User = mongoose.model("User", userSchema);
> 
> const main = async () => {
>    const client = await mongoose.connect('mongodb://localhost:27017/test', {
>   connectTimeoutMS: 3000
> });
>   const user = new User({
>     _id: mongoose.Types.ObjectId("test-again_0"),
>     username: "username",
>     email: "user@example.com",
>   });
> 
>   const dbUser = await user.save();
>   console.log(dbUser.toObject());
>   client.disconnect();
> }
> 
> main();
> ```
> 
> This generates:
> `{ "_id" : ObjectId("746573742d616761696e5f30"), "email" : "user@example.com", "username" : "username", "__v" : 0 }`
> in the DB because "test-again_0" is treated as a binary sequence and converted to that. And that objectId has a timestamp (just a decade in the future):
> 
> ```
> > ObjectId("746573742d616761696e5f30").getTimestamp()
> ISODate("2031-11-18T22:02:28Z")
> ```
> 
> You can also bypass mongoose altogether and go directly to the bson package that mongodb maintains:
> 
> ```
> const BSON = require('bson')
> 
> const objectId = new BSON.ObjectId('test-again_0')
> 
> console.log(objectId)
> console.log(objectId.getTimestamp())
> ```
> 
> This evaluates to:
> 
> ```
> $ node bson.js
> new ObjectId("746573742d616761696e5f30")
> 2031-11-18T22:02:28.000Z
> ```

Amazing explanation. Thanks for clearing things out.
