### ISSUE TITLE
[BUG][Vulnerability] Arbitrary Documents deleted when using findOneAndDelete method 

### ISSUE THREAD

**Issue by Yrahate7** [Automattic/mongoose#10747]
Node version 16.9.1
MongoDB version 4.4.8 Enterprise
Mongoose version 6.0.5

Steps to reproduce:- 

Assuming i have a schema as follows
Schema :- Users
fields in schems: - name:string, age:number

In the Filter object passed to the findOneAndDelete method of the schema object of Users, 
if i pass an invalid field , (Excluding name and age, which are not present on the schema)
the method findOneAndDelete deletes an arbitrary document from the Users Collection.

Expected that , 
If no document matches the given filter query then this method return null.

The same query on mongosh works perfectly

[package.txt](https://github.com/Automattic/mongoose/files/7187492/package.txt)
>
[tsconfig.txt](https://github.com/Automattic/mongoose/files/7187493/tsconfig.txt)

**Comment by IslandRhythms** [comment]
This is actually behaving as expected. `findOneAndDelete()` calls `findOne` under the hood.
https://mongoosejs.com/docs/api/model.html#model_Model.findOne
> Note: conditions is optional, and if conditions is null or undefined, mongoose will send an empty findOne command to MongoDB, which will return an arbitrary document. If you're querying by _id, use findById() instead.

**Comment by Yrahate7** [comment]
> This is actually behaving as expected. `findOneAndDelete()` calls `findOne` under the hood.
> https://mongoosejs.com/docs/api/model.html#model_Model.findOne
> 
> > Note: conditions is optional, and if conditions is null or undefined, mongoose will send an empty findOne command to MongoDB, which will return an arbitrary document. If you're querying by _id, use findById() instead.

Okay, but then if we're deleting a document, it should not delete  an arbitrary document. Either an error must be thrown or null should be returned.

**Comment by Yrahate7** [comment]
No Replies?

**Comment by sean-daley** [comment]
You can pass `{ strict: 'throw' }` to your `findOneAndDelete` call to get it to error out.

For example:
```
const mongoose = require("mongoose");

const { Schema } = mongoose;

const userSchema = new Schema({
  email: {
    type: Schema.Types.String,
    required: true
  },
  username: {
    type: Schema.Types.String,
    required: true
  },
});

const User = mongoose.model("User", userSchema);

const main = async () => {
   const client = await mongoose.connect('mongodb://localhost:27017/test', {
  connectTimeoutMS: 3000
});
  const user = new User({
    username: "username",
    email: "user@example.com",
  });

  const beforeCount = await User.countDocuments();
  console.log(`Before count = ${beforeCount}`);
  const dbUser = await user.save();
  const afterCount = await User.countDocuments();
  console.log(`After count = ${afterCount}`);

  await User.findOneAndDelete({ email: 'Does not exist' });
  const afterDelete1Count = await User.countDocuments();
  console.log(`After delete 1 count = ${afterDelete1Count} ... this should be the same as before`)

  // Now delete a random field
  await User.findOneAndDelete({ invalidField: 'blah' }, { strict: 'throw' });
  // We only get here if the above strict: throw is removed
  const afterDelete2Count = await User.countDocuments();
  console.log(`After delete 2 count = ${afterDelete2Count}`)

  client.disconnect();
}

main();
```

If you remove that `{ strict: 'throw' }` on the delete call it will succeed and delete an arbitrary item.
If you leave it in the following happens:
```
After delete 1 count = 5 ... this should be the same as before
(node:78353) UnhandledPromiseRejectionWarning: StrictModeError: Path "invalidField" is not in schema and strict is 'throw'.
    at cast (/Users/sean/node/mongoose-test/node_modules/mongoose/lib/cast.js:270:19)
    at model.Query.Query.cast (/Users/sean/node/mongoose-test/node_modules/mongoose/lib/query.js:4963:12)
    at model.Query.Query._castConditions (/Users/sean/node/mongoose-test/node_modules/mongoose/lib/query.js:2055:10)
    at model.Query.<anonymous> (/Users/sean/node/mongoose-test/node_modules/mongoose/lib/query.js:3445:8)
    at model.Query._wrappedThunk [as _findOneAndDelete] (/Users/sean/node/mongoose-test/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:8)
    at /Users/sean/node/mongoose-test/node_modules/kareem/index.js:370:33
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

I think it's possible to set that value more globally but I can't tell you how to do that off the top of my head.

**Comment by sean-daley** [comment]
Note this is mostly discussed in https://mongoosejs.com/docs/tutorials/query_casting.html
Though those instructions aren't quite correct for 6.0 as strictQuery was replaced by strict ... at least per the mongo 6.0 migration guide. But the general details seem to still be accurate.

**Comment by Yrahate7** [comment]
> Note this is mostly discussed in https://mongoosejs.com/docs/tutorials/query_casting.html
> Though those instructions aren't quite correct for 6.0 as strictQuery was replaced by strict ... at least per the mongo 6.0 migration guide. But the general details seem to still be accurate.

Okay, Thanks.
Closing this now.

**Comment by Vrq** [comment]
A few words: I believe that this is not a Mongoose issue, as the behavior matches the native driver. 
It still feels quite unexpected that the MongoDB implementation of deleteOne does not check how many documents matched the condition and reject the operation in case it's more than 1 (as it should happen in the null example).
