### ISSUE TITLE
[Cached Driver in Serverless Environments Crashes] - Cursor session id (id) is not the same as the operation context's session id (none)

### ISSUE THREAD

**Issue by alqamabinsadiq** [Automattic/mongoose#10751]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cached Driver in Serverless Environments Crashes
```
"name": "MongoServerError",
 "message": "Cursor session id (5351d4a5-e6a3-4a0c-ab71-4ccd08d371e5 - ddqot68vLpBUPnOuqFj2cdClv/dv/vF9ZVSwknYHEsE=) is not the same as the operation context's session id (none)",
 ```

**If the current behavior is a bug, please provide the steps to reproduce.**

Cached Driver in Serverless Environments Crashes randomly after a few mins.

DB connection function:

```
import mongoose from 'mongoose';
import Bluebird from 'bluebird';

mongoose.Promise = Bluebird;

let conn = null;
const uri = process.env.MONGODB_URI;

const connectToDatabase = async () => {
  if (conn == null) {
    console.log('=> using new database connection');
    conn = mongoose
      .connect(uri, {
        serverSelectionTimeoutMS: 5000,
      })
      .then(() => mongoose)
      .catch((err) => {
        console.log(err);
        throw err;
      });
    // `await`ing connection after assigning to the `conn` variable
    // to avoid multiple function calls creating new connections
    await conn;
  } else {
    console.log('=> using existing database connection');
  }

  return conn;
};

export default connectToDatabase;

```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": `"^6.0.6"`,
NodeJS: `14.x`

**Comment by vkarpov15** [comment]
@alqamabinsadiq can you please provide some examples of what your queries look like? Also, is your query using a transaction?

**Comment by mighty6ft5max** [comment]
@alqamabinsadiq was this ever resolved? I am having the same issue, didn't have a catch for the error initially.
`
let cachedConnection = null;

module.exports =
  cachedConnection === null
    ? mongoose
        .connect(process.env.DB_URL)
        .then(con => {
          console.log("Connecting to MongoDB");
          return (cachedConnection = con);
        })
        .catch(err => {
          console.log("Connection error:", err);
        })
    : Promise.resolve(cachedConnection);
`
I'm using mongoose 6.0.14

**Comment by vkarpov15** [comment]
@mighty6ft5max please open a new issue and follow the issue template
