### ISSUE TITLE
TypeScript virtuals docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#10754]
Re: https://github.com/Automattic/mongoose/issues/10689

**Comment by hasezoey** [comment]
it would be great to also have a example of this with typescript classes and their instance methods, static methods, and get / set (mongoose `loadClass`)

**Comment by vkarpov15** [comment]
@hasezoey do you have any examples like this?

**Comment by hasezoey** [comment]
> @hasezoey do you have any examples like this?

not really, expect double/triple-defining the methods (once in the class with implementation and once in a interface that only contains functions definitions(static & instance & maybe getters&setters) and in native mongoose once in a interface that only contains properties)
