### ISSUE TITLE
Code working fine in Mongoose5 but gives error in Mongoose6

### ISSUE THREAD

**Issue by bhavey21** [Automattic/mongoose#10759]
I am getting error "MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms". I have tried same code with Mongoose5, it is working fine.

Is it a bug ? Plz help me 

git link : git clone https://bhavey21@bitbucket.org/bhavey21/mongoose-github-question.git

Repo URL : https://bitbucket.org/bhavey21/mongoose-github-question/src/main/

**Comment by IslandRhythms** [comment]
Are you running it locally or on a server

**Comment by bhavey21** [comment]
> server

I didnt got it running on local, so didnt deploy it to server... I m running it using Serverless Offline plugin

**Comment by IslandRhythms** [comment]
I can't access the code you posted. Copy and paste it here. Before you do that, make sure you have a mongodb instance running and if you are running it on a server make sure to whitelist your ip

**Comment by raymond-redd** [comment]
I am facing a similar issue. One of the projects with mongoose5 is working fine, while the new project with mongoose 6 is having some trouble.

**Comment by bhavey21** [comment]
> I can't access the code you posted. Copy and paste it here. Before you do that, make sure you have a mongodb instance running and if you are running it on a server make sure to whitelist your ip

Above link is working fine for Git Clone... If you are trying to access code directly from browser you should try this link istead : https://bitbucket.org/bhavey21/mongoose-github-question/src/main/

**Comment by bhavey21** [comment]
Above link is working fine for Git Clone... If you are trying to access code directly from browser you should try this link instead : https://bitbucket.org/bhavey21/mongoose-github-question/src/main/
And mongodb istance is running+IP whitelisted because code is working fine with version5 Mongoose

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html
Check your connection string. Also include the error message that mongoose is giving you.

**Comment by bhavey21** [comment]
> https://mongoosejs.com/docs/migrating_to_6.html
> Check your connection string.

Connection string is fine... directly copied from atlast

**Comment by bhavey21** [comment]
> https://mongoosejs.com/docs/migrating_to_6.html
> Check your connection string.

Connection string is fine.

I have doubt on Mongoose buffering, my code is issuing command to mongodb b4 establishing connection, I guess.
https://mongoosejs.com/docs/connections.html#buffering.

And i have tried everything in Documentation, turning buffering Off etc, but was not able to solve the issue.

**Comment by bhavey21** [comment]
> I am facing a similar issue. One of the projects with mongoose5 is working fine, while the new project with mongoose 6 is having some trouble.

So did u got any workaround ? Or u preferred to stay on 5 ?

**Comment by IslandRhythms** [comment]
Try removing your options from the connection string as that isn't necessary anymore.

**Comment by bhavey21** [comment]
> Try removing your options from the connection string as that isn't necessary anymore.

Thanks a lot bro... it solved my problem :)
