### ISSUE TITLE
Is $in / $nin broken for enums in TypeScript?

### ISSUE THREAD

**Issue by cloakedch** [Automattic/mongoose#10757]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
$in and $nin types used to support enums in mongoose 5.x, now with 6.x, there is a type error with the latest NestJS.

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
export enum MyEnum {
  VALUE1,
  VALUE2,
  VALUE3
}

export type MyClassDocument = MyClass & Document;

@Schema()
export class MyClass {
  @Prop({ default: MyEnum.VALUE1 })
  status: MyEnum;
}

const test: FilterQuery<MyClassDocument> = { status: { $in: [MyEnum.VALUE1, MyEnum.VALUE2] } };
```
Now `$in` is marked as having an error, since

```
Type '(MyEnum.VALUE1 | MyEnum.VALUE2)[]' is not assignable to type 'MyEnum.VALUE1[] | MyEnum.VALUE2[] | MyEnum.VALUE3[]'
```

This used to work fine in mongoose 5.x, and I could not find any hints about this change in the changelog.

The last line above works fine (in regards to tsc) when using

```ts
const test: FilterQuery<MyClassDocument> = { status: { $in: [0, 1] } };
```
Obviously, that is not a solution.

**tsconfig.json**

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**What is the expected behavior?**
Supported behaviour, no error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v14.17.6
NestJS 8.1.1
MongoDB 5 (though irrelvant here)
Mongoose 6.0.7

**Comment by IslandRhythms** [comment]
```
import * as mongoose from 'mongoose';

enum MyEnum {
    VALUE1,
    VALUE2,
    VALUE3
}


class MyClass {
    test: ({default: MyEnum.VALUE1})
    status: MyEnum
}

type MyClassDocument = MyClass & mongoose.Document;

const test: mongoose.FilterQuery<MyClassDocument> = {status: { $in: [MyEnum.VALUE1, MyEnum.VALUE2]}}
```
