### ISSUE TITLE
Error: Mongoose does not support calling populate() on nested docs.

### ISSUE THREAD

**Issue by i-zokirov** [Automattic/mongoose#10760]
I have the following Schema on one of my collections. As you can see, I have an array of objects in the "products" and each object holds two items, "cart_item" referencing the products in different collection, and an "item_quantity". I am trying to populate() the cart_items as " **await shopping_cart.products[index].populate('cart_item')** " in async function but I receive the following error: "**Mongoose does not support calling populate() on nested docs. Instead of `doc.arr[0].populate("path")`, use `doc.populate("arr.0.path")`**". How can I find more explanation on the workaround/solution if there is one?

```
const shoppingCartSchema = new Schema({
    products: [{
        cart_item: {
            type: Schema.Types.ObjectId,
            ref: 'Product'
        },
        item_quantity: {
            type: Number,
            required: true
        }
    }],
    cart_owner: {
        type: Schema.Types.ObjectId,
        ref: 'User'
    }
})
```

**Comment by vkarpov15** [comment]
Try `await shopping_cart.populate(`products.${index}.cart_item`)`

**Comment by navanjr** [comment]
> Try
> 
> ```
> await shopping_cart.populate(`products.${index}.cart_item`)
> ```

instead try
> ```
> await shopping_cart.populate('products.0.cart_item')
> ```
