### ISSUE TITLE
Ability to control reconnection attempts and reconnection attempt event

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#10764]
**Question**
Are we able to control reconnecting attempts? There used to be reconnectTries option but now that we are using the new MongoDB connection management engine, that option seems to be gone.

Also, is there an event for when mongoose is attempting to reconnect?
I wasn't able to find any documentation on reconnectTries in the latest driver so I am not sure how many times the driver will try to reconnect. If we know when mongoose is attempting to reconnect, then we can potentially tally the retries and process.exit after x retries. Otherwise it _seems_ that mongoose is stuck reconnecting forever.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.16, Mongoose 6.0.7

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/api/connection.html#connection_Connection-readyState

I think this may be your best bet. You can create an event emitter that fires a callback when it is in the connecting state.

**Comment by vkarpov15** [comment]
@govindrai in Mongoose 6, the notion of "connected" has changed a bit so retries are scoped to an individual operation rather than a connection. Specifically, Mongoose will keep retrying an individual operation for up to `serverSelectionTimeoutMS` milliseconds.
