### ISSUE TITLE
Mongoose 6 populate after save

### ISSUE THREAD

**Issue by euj1n0ng** [Automattic/mongoose#10775]
In Mongoose 6 `execPopulate()` seemed to be removed. Due to this, the below code returns error.

```
const t = new MyModel(value)
return t.save().then(t => t.populate('my-path').execPopulate())
```
I'd like to know how to populate after save in Mongoose 6 or later. FYI, the newly created and unpopulated instance should be used before populating so I don't wanna use `MyModel.populate()`.

**Comment by saveman71** [comment]
https://mongoosejs.com/docs/migrating_to_6.html

populate() returns a promise.

```
const t = new MyModel(value)
return t.save().then(t => t.populate('my-path'))
```

should work

**Comment by euj1n0ng** [comment]
> https://mongoosejs.com/docs/migrating_to_6.html
> 
> populate() returns a promise.
> 
> ```
> const t = new MyModel(value)
> return t.save().then(t => t.populate('my-path'))
> ```
> 
> should work

Yes, it works. I was mistaken for not populating the relevant object, but I found it to work. Thank you.

**Comment by AK47-dadada** [comment]
> https://mongoosejs.com/docs/migrating_to_6.html
> 
> populate() returns a promise.
> 
> ```
> const t = new MyModel(value)
> return t.save().then(t => t.populate('my-path'))
> ```
> 
> should work

It is better to use async and await here
