### ISSUE TITLE
findOne returns random value but collection.findOne does not!

### ISSUE THREAD

**Issue by xoxoxo** [Automattic/mongoose#10778]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
returns random value from findOne. I am pretty sure its not suppose too or maybe I am doing something wrong? In older version it worked as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('./db').mongoose;

function pageViewsSchema() {


  const schema = {
    pageId: {type: mongoose.Schema.Types.ObjectId},
  };

  const collectionName = 'Pageviews';
  const mongoSchema = mongoose.Schema(schema);

  const Pageviews = mongoose.model(collectionName, mongoSchema);

  return Pageviews;
}

module.exports = pageViewsSchema();
```

```
const Pageviews = require('./pageviews');

const awaitPageview = await Pageviews.findOne({'asdasda': 'adadasdsa'});


```

**What is the expected behavior?**
it should return null. When i use Pageviews.collection.findOne returns null as expected.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v15.9.0
mongodb: 5.0.2
mongoose: 6.0.7

**Comment by IslandRhythms** [comment]
behaving as expected
https://mongoosejs.com/docs/api/model.html#model_Model.findOne

**Comment by saveman71** [comment]
This is because `asdasda` isn't in you schema, so it's stripped out, resulting in an empty query `{}`, querying the first document it finds.

**Comment by xoxoxo** [comment]
Ah great makes sense but kinda confusing. So if you make a typo then you will get a random doc thinking its the one you need :/

**Comment by Kamikadze4GAME** [comment]
Duplicate of #10763

**Comment by xoxoxo** [comment]
cheers just posted there will close this one
