### ISSUE TITLE
Mongoose 6.0.7: QueryCursor got error: Collection method find is synchronous 

### ISSUE THREAD

**Issue by xieziyu** [Automattic/mongoose#10785]
Hello, 

I got an exception: `Collection method find is synchronous` when using `model.find().cursor()`.
When I looked into the codes and found the following codes are conflicted.

https://github.com/Automattic/mongoose/blob/51e758541763b6f14569744ced15cc23ab8b50c6/lib/cursor/QueryCursor.js#L62

https://github.com/Automattic/mongoose/blob/a3340bb1302031a39871628a55db47ba092ebebd/lib/drivers/node-mongodb-native/collection.js#L99-L101

It seems the `find` was brought into `syncCollectionMethods` by this commit: https://github.com/Automattic/mongoose/commit/9de60a771e37cc2fcb7af3d805294b49239aed17

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
const {Schema} = mongoose;

const testSchema = new Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();

    await Test.create({name: 'Test'});
    await Test.create({name: 'Test2'});

    await Test.find().cursor();
    console.log('done');

}

run();
```

**Comment by AlexGodard** [comment]
Having the same issue here.

**Comment by cutesquirrel** [comment]
FYI, I had this error as I was forgetting to ... connect to the DB :)

**Comment by andriotisnikos1** [comment]
Having kind of the same issue here
`export const getData = async () => {
  const db = mongoose.createConnection(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  const data = await db
    .collection("test")
    .find({})
    .addCursorFlag("awaitData", true)
    .toArray();
  console.log(data);
  await db.close({ force: true });
  return data;
};`

**Comment by andriotisnikos1** [comment]
Im having kind of the same issue here 
```
export const getData = async () => {
  const db = mongoose.createConnection(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  const data = await db
    .collection("test")
    .find({})
    .addCursorFlag("awaitData", true)
    .toArray();
  console.log(data);
  await db.close({ force: true });
  return data;
};
```
