### ISSUE TITLE
Document.depopulate requires at least one argument in TypeScript

### ISSUE THREAD

**Issue by ujbrody** [Automattic/mongoose#10793]
I don't know if this is a bug or I just don't understand something and set something wrongly, but in the docs, it says that if I don't provide an argument to the `depopulate` method, it returns all populated fields in the document to their original state. However, in TypeScript I am not able to call on the method with no arguments:

`doc.depopulate()`

For this line of code I get the following error:

Expected 1 arguments, but got 0. ts(2554)

**Comment by vkarpov15** [comment]
Looks like an issue with our TS definitions, we'll fix :+1:
