### ISSUE TITLE
TypeError: Cannot read property 'Decimal128' of null

### ISSUE THREAD

**Issue by 4ty711** [Automattic/mongoose#10803]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

I am getting:  TypeError: Cannot read property 'Decimal128' of null

**If the current behavior is a bug, please provide the steps to reproduce.**

Install the latest version of mongoose and use the ObjectID Constructor.

**What is the expected behavior?**

In older versions, the path is correct.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

* Node: v14.17.1
* Mongoose: 6.0.8
* MongoDB: 4.2

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html

Mongoose 6 has several backwards breaking changes. Check if one of them is in your project, if not then provide a reproduction script because this issue does not have enough information to create one.

**Comment by cbratschi** [comment]
I have the same issue on Mongoose 5 after updating to 5.13.12.

**Comment by amatiasq** [comment]
Related to https://github.com/Automattic/mongoose/issues/7866

**Comment by amatiasq** [comment]
This happens to me when using `jest.mock` on multiple modules that end up depending on `mongoose`.
Sorry I don't have time to provide a repo.

**Comment by vkarpov15** [comment]
@amatiasq we strongly recommend using any testing framework other than Jest. Without a repro, there's no way for us to provide any advice other than to:

1. Strongly consider using a different testing framework
2. Read our [jest testing docs](https://mongoosejs.com/docs/jest.html) and make sure you've followed the instructions
