### ISSUE TITLE
`findOneAndUpdate` typing does not include null result

### ISSUE THREAD

**Issue by janeisenmenger** [Automattic/mongoose#10820]
This issue occurred when updating from 6.0.5 to 6.0.8

The behaviour before was that `findOneAndUpdate` would either return the new/old document (depending on the options) or null, when no document was updated.
With [this commit](https://github.com/Automattic/mongoose/commit/919618153ecaea986c8fcc284a11207415a24c5d) the typing of the function was changed to not include null anymore.

However, it is still possible to receive a `null` value, regardless of the typing. Steps to reproduce: 

* call `findOneAndUpdate` on an empty repository (any data or model will do)
* Check the return value -> This is were we receive null, even though it shouldn't be according to the typing.

My proposition would be to add the null value back to the typing or throw a matching error.

Versions used: 
* Node.js: 14.17.5
* MongoDB: 4.2
* Mongoose: 6.0.8

**Comment by IslandRhythms** [comment]
Where does it say on the doc pages that `null` is not a possible value?

**Comment by janeisenmenger** [comment]
Hey @IslandRhythms! 
The documentation doesn't mention `null` on the corresponding `findOneAndUpdate` page, or at least I couldn't find it. 
Regardless of the documentation, I think the typing should reflect the return values the function could have, and currently it does not. 
So: When looking at the typing of `Model.findOneAndUpdate`, one can see that before the update, the signature was as follows:
`Query<T | null, EnforceDocument<T, TMethods>, T>`. Note the explicit `T | null` as part of the Query return type.
Now, after the update, the same function on the Model has the signature `QueryWithHelpers<EnforceDocument<T, TMethods, TVirtuals>, EnforceDocument<T, TMethods, TVirtuals>, TQueryHelpers, T>` - Where `null` is not a possibility anymore, at least according to the types.

Note that the signature of `Query` has not changed in that regard, it still allows `DocType | null` - We simply restrict the type in the Model, which we probably shouldn't.
