### ISSUE TITLE
Missing breaking change in v6 changelog: schema no longer inherits minimize option 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Automattic/mongoose#10827]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In v5, the minimize option seem to be inherited by child schema. This is no longer the case in v6. This should be considered at least a bug in the changelog 

v5 - 

```
> const { Schema, model, version } = require('mongoose');
> console.log(version);
5.9.29
> const child = new Schema({ thing: Schema.Types.Mixed });
> const parent = new Schema({ child }, { minimize: false });
> const Parent = model('Parent', parent);
> const p = new Parent({ child: { thing: {} } });
> console.log(p.toObject());
{
  _id: 615670e7ce0fe77733511fa8,
  child: { _id: 615670e7ce0fe77733511fa9, thing: {} }
}
``` 

v6 - 

``` 
> const { Schema, model, version } = require('mongoose');
> console.log(version);
6.0.6
> const child = new Schema({ thing: Schema.Types.Mixed });
> const parent = new Schema({ child }, { minimize: false });
> const Parent = model('Parent', parent);
> const p = new Parent({ child: { thing: {} } });
> console.log(p.toObject());
{
  child: { _id: new ObjectId("615670bbd7853d32111ae88e") },
  _id: new ObjectId("615670bbd7853d32111ae88d")
}
```

For easier copy-pasting - 

``` js
const { Schema, model, version } = require('mongoose');
console.log(version);
const child = new Schema({ thing: Schema.Types.Mixed });
const parent = new Schema({ child }, { minimize: false });
const Parent = model('Parent', parent);
const p = new Parent({ child: { thing: {} } });
console.log(p.toObject());
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by IslandRhythms** [comment]
So on newer versions of 5 `thing` does not show up.

**Comment by vkarpov15** [comment]
I took a closer look and this is expected behavior as of v5.10.5 with #9405. This is not a change in v6. As a workaround, you can either explicitly set `minimize` by calling `toObject({ minimize: false })`, or, in 6.0, you can define schemas inline (without `new Schema()`) so the schema inherits its parent's `minimize`:

```javascript
const { Schema, model, version } = require('mongoose');
console.log(version);
const parent = new Schema({ child: { thing: Schema.Types.Mixed } }, { minimize: false });
const Parent = model('Parent', parent);
const p = new Parent({ child: { thing: {} } });
console.log(p.toObject()); // Contains `thing` in v6.x
```

**Comment by nomcopter** [comment]
Sure, if it is expected behavior then this is still an undocumented breaking change introduced in a patch version.

**Comment by vkarpov15** [comment]
@nomcopter correct. This change was meant to be a bug fix, but sometimes bug fixes break code :( Do you need any help getting a workaround or do you just think there should be a note in the 6.0 changelog?

**Comment by nomcopter** [comment]
@vkarpov15 a note in the 6.0 changelog should cover it well at this point!
