### ISSUE TITLE
Add `Schema#virtuals` to docs as a public property

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#10829]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
It's easy to loop around all paths with ```schema.eachPath``` but not for vituals, It'll be really helpfull to have somthing like ```schema.eachVirtualPath``` 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
now you have to do:

```js
for(const virtualPath in schema.virtuals){
  const virtualType = schema.virtual(virtualPath);
  //do something
}
```
instead of something like:

```js
schema.eachVirtualPath((path, virtualType)=>{
  //do something
});
```

Obviously you can always do:
```js
mongoose.Schema.prototype.eachVirtualPath = function eachVirtualPath(cb){
  Object.keys(this.virtuals).forEach(path => cb(path, this.virtual(path));
};
``` 
I don't like the first approach as it's a inner prop and you can change it whenever you want, even set it as private or use a ```Symbol```.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 6.0.7
node: 16.10.0
mongodb atlas: 4.4.9

**Comment by vkarpov15** [comment]
Why not just do `Object.entries(schema.virtuals).forEach(([path, virtualType]) => { ... })` ? We can add this feature pretty easily, but I'm not sure it provides much value over just [iterating through the object using `Object.entries()`](https://masteringjs.io/tutorials/fundamentals/iterate-object)

**Comment by chumager** [comment]
Hi, more that how *easy* could it be, ```schema.virtuals``` it's not documented, as such, there is no guarantee to keep it the same, if it were kept in the docs then I can think that it'll not change unless it's informed, that's all.

PS: BTW very good optimization, even I know ```Object.entries``` I never use it... 😄

**Comment by vkarpov15** [comment]
We'll add `Schema.virtuals` to the docs. We're not going to change `.virtuals`, we have tests that rely on it.
