### ISSUE TITLE
Unable to save document if previous save was failed | ParallelValidateError: Can't validate() the same doc multiple times in parallel

### ISSUE THREAD

**Issue by mayank-katare** [Automattic/mongoose#10830]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When we are trying to do multiple saves on a mongoose document, if the previous save somehow failed then the next save is also failing with "ParallelValidateError: Can't validate() the same doc multiple times in parallel" error.

**If the current behavior is a bug, please provide the steps to reproduce.**

------ Script to reproduce ------
```
const BookSchema = mongoose.Schema({
  name: String,
  price: Number,
  quantity: Number
})
Book = mongoose.model('Book', BookSchema, 'bookstore')
Book.findOne({ quantity: 25 }).exec(function (err, book) {
    if (err) return console.log(err)
    book.quantity = 27 // Wrong quantity
    book.save((err, bookDoc) => {
      if (err) console.log(err)
      book.quantity = 26 // Correct quantity
      book.save((err, bookDoc) => {
        if (err) console.log(err)
      })
    })
  })
BookSchema.pre('validate', failForWrongQty)

function failForWrongQty (next) {
  const self = this
  if (self.isNew) return next()

  if (self.quantity === 27) {
    return next(new Error('Wrong Quantity'))
  }
return next()
}
```

**What is the expected behavior?**
It should save successfully for the second save and must not throw ParallelValidateError

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.15.0
mongoose@5.12.5 
mongoDB: 4.0.24

**Comment by IslandRhythms** [comment]
Are the syntax errors intentional?

**Comment by IslandRhythms** [comment]
```javascript


const mongoose = require('mongoose');




const BookSchema = mongoose.Schema({
    name: String,
    price: Number,
    quantity: Number
  })
  const Book = mongoose.model('Book', BookSchema, 'bookstore')


  async function run() {
    await Book.findOne({ quantity: 25 }).exec(function (err, book) {
        if (err) return console.log(err)
        book.quantity = 27 // Wrong quantity
        book.save((err, bookDoc) => {
          if (err) console.log(err)
          book.quantity = 26 // Correct quantity
          book.save((err, bookDoc) => {
            if (err) console.log(err)
          })
        })
      });
  }
  BookSchema.pre('validate', failForWrongQty)
  
  function failForWrongQty (next) {
    const self = this
    if (self.isNew) return next()
  
    if (self.quantity === 27) {
      return next(new Error('Wrong Quantity'))
    }
  return next()
  }

  run();
```

**Comment by mayank-katare** [comment]
@IslandRhythms Please ignore the above code with incomplete syntax and check this below  code, I am still able to reproduce the issue.
`const mongoose = require('mongoose')

// make a connection
mongoose.connect('mongodb://localhost:27017/Dummy_TestDB')

// get reference to database
const db = mongoose.connection

db.on('error', console.error.bind(console, 'connection error:'))
// define Schema
const BookSchema = mongoose.Schema({
  name: String,
  price: Number,
  quantity: Number
})

// compile schema to model
let Book
db.once('open', function () {
  console.log('Connection Successful!')
  Book = mongoose.model('Book', BookSchema, 'bookstore')
  Book.findOne({ quantity: 25 }).exec(function (err, book) {
    if (err) return console.log(err)
    book.quantity = 27
    book.save((err, bookDoc) => { // Expected save to be failing and its failing
      if (err) console.log(err)
      book.quantity = 26
      book.save((error, bookDoc) => { // Expected save to happen but its failing with ParallelValidator error
        console.log('Parallel Validator:', error)
        console.log('Success and bookDoc:  ', bookDoc)
      })
    })
  })
})

BookSchema.pre('validate', disallownumflows)

function disallownumflows (next) {
  const self = this
  if (self.isNew) return next()

  if (self.quantity === 27) {
    return next(new Error('Wrong Quantity'))
  }
}`

**Comment by mayank-katare** [comment]
Getting this error
**### ```
Parallel Validator: ParallelValidateError: Can't validate() the same doc multiple times in parallel. Document: 6156f9df5d1e810eecc15c54
    at model.Document.validate (/Users/mayankkatare/Project/node_modules/mongoose/lib/document.js:2222:24)
```**

**Comment by IslandRhythms** [comment]
```javascript

const mongoose = require('mongoose')

// make a connection
mongoose.connect('mongodb://localhost:27017/Dummy_TestDB')

// get reference to database
const db = mongoose.connection

db.on('error', console.error.bind(console, 'connection error:'))
// define Schema
const BookSchema = mongoose.Schema({
  name: String,
  price: Number,
  quantity: Number
})

// compile schema to model
let Book
db.once('open', async function () {
  console.log('Connection Successful!')
  Book = mongoose.model('Book', BookSchema, 'bookstore')
  await Book.create({name: 'Hello', price: 50, quantity: 25})
  Book.findOne({ quantity: 25 }).exec(function (err, book) {
    if (err) return console.log(err)
    book.quantity = 27
    book.save((err, bookDoc) => { // Expected save to be failing and its failing
      if (err) console.log(err)
      book.quantity = 26
      book.save((error, bookDoc) => { // Expected save to happen but its failing with ParallelValidator error
        console.log('Parallel Validator:', error)
        console.log('Success and bookDoc:  ', bookDoc)
      })
    })
  })
})

BookSchema.pre('validate', disallownumflows)

function disallownumflows (next) {
  const self = this
  if (self.isNew) return next()

  if (self.quantity === 27) {
    return next(new Error('Wrong Quantity'))
  }
}
```
