### ISSUE TITLE
`this` in SchemaType's validator is `null` if the schema is a schema for discriminator

### ISSUE THREAD

**Issue by mark-night** [Automattic/mongoose#10840]
**Do you want to request a *feature* or report a *bug*?**
Not quite sure is this an intended behavior or a bug

**What is the current behavior?**
Following official examples to set `required` for a certain filed based on value of another, something like this:
```
const buildingSchema = new Schema({
  floor: { type: Number, required: true },
  hasElevator: {
    type: Boolean,
    required: function() { return this.level > 5; }
  }
});

const Building = mongoose.model('Building', buildingSchema);
```
**Above works as expected.**
The issue happens when using this `buildingSchema` to create discriminator model off some other model, something like:
```
const Building = SomeOtherModel.discriminator('Building', buildingSchema);
```
Now when creating document, validation fails because `this` in the `required` validator is `null`. It seems `this` gets lost somewhere in the process. 
Or, it is actually an intended result when creating discriminator? If so, how to customize validator based on value of other field in the case?

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure if it is a bug.

**What is the expected behavior?**
`this` should be set/bounded and works the same even when creating discriminator. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose v5.13.3
MongoDB v4.4

**Comment by IslandRhythms** [comment]
> const Building = Schema.model('Building', buildingSchema);

is that a typo? It would be mongoose.model no?

**Comment by mark-night** [comment]
@IslandRhythms Oh, you are right, can't recall how I typed that... I'll fix it in the original question. Thanks.
