### ISSUE TITLE
`minPoolSize` is listed twice with different descriptions

### ISSUE THREAD

**Issue by IslandRhythms** [Automattic/mongoose#10849]
https://mongoosejs.com/docs/connections.html#options

**Comment by IslandRhythms** [comment]
Also need to delete myself from the subscriber model

**Comment by vkarpov15** [comment]
Doesn't look to be the case. Either this was fixed, or @IslandRhythms either misread `maxPoolSize` as `minPoolSize` or thought the 2nd `minPoolSize` was a separate list item.

![image](https://user-images.githubusercontent.com/1620265/141533760-7d46053c-4f4b-4017-9a8d-7f0cdfb6a221.png)

**Comment by IslandRhythms** [comment]
Misread as a separate list item I guess
