### ISSUE TITLE
TypeScript error TS2344: Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.

### ISSUE THREAD

**Issue by APatQ** [Automattic/mongoose#10847]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to compile an application using typescript with mongoose 5.13.10 results in the following error:

    node_modules/mongoose/index.d.ts:2113:103 - error TS2344: Type 'DocType' does not satisfy the constraint 'Document<any, any, any>'.
    2113   type QueryWithHelpers<ResultType, DocType, THelpers = {}, RawDocType = DocType> = Query<ResultType, DocType, THelpers, RawDocType> & THelpers;

Reproduction doesn't require a script, rather it is triggered when using tsc:
`tsc -p tsconfig.build.json`

tsconfig.build.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./dist",
    "noEmit": false
  },
  "exclude": [
    "src/**/__tests__/**"
  ],
  "include": [
    "src/**/*"
  ]
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "es2019",
    "baseUrl": "./src",
    "outDir": "./dist",
    "strict": true,
    "paths": {
      "~/*": [
        "./*"
      ]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./src/@types"
    ],
    "noEmit": true
  },
  "include": [
    "src/**/*",
    "tests/**/*",
    "dev/**/*",
    "*"
  ]
}
```

**What is the expected behavior?**
Compile without errors.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.22.1
Mongoose: v5.13.10
MongoDB: v4.2.9 (should be unrelated)
Typescript: v3.8.3 (verified the issue continues with higher versions)

**Additional Info**
The previously used version was mongoose 5.12.8, which didn't have the issue. This is consistent with the particular piece of code `type QueryWithHelpers<ResultType, DocType, THelpers = {}, RawDocType = DocType> = Query<ResultType, DocType, THelpers, RawDocType> & THelpers;` not being in that package.
Verified via:
- https://unpkg.com/browse/mongoose@5.13.10/index.d.ts
- https://unpkg.com/browse/mongoose@5.12.8/index.d.ts

**Comment by IslandRhythms** [comment]
Following your instructions, I could not reproduce the error.

```
import { Schema, model, connect } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface User {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const UserModel = model<User>('User', schema);

run().catch(err => console.log(err));

async function run(): Promise<void> {
  // 4. Connect to MongoDB
  await connect('mongodb://localhost:27017/test');

  const doc = new UserModel({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await doc.save();

  console.log(doc.email); // 'bill@initech.com'
}
```

please modify this script to reproduce your error

**Comment by nhhockeyplayer** [comment]
this remains a profuse issue
