### ISSUE TITLE
What's the difference between `document` and `savedDocument`

### ISSUE THREAD

**Issue by yahiarefaiea** [Automattic/mongoose#10842]
This is for sure a question to keep my code cleaner and less complicated.

Let's say I want to save a new document to the database...
```
let document = new Model({foo: 'bar'})
document.save(function(err, savedDocument) {
  if(err) {
    // handle the error
  } else {
    // What to send to the client?
    // this original `document`?
    console.log(document)
    // or the new `savedDocument`?
    console.log(savedDocument)
  }
})
  ```
  
What's the difference between `document` and `savedDocument` in the example above?
And which one is recommended to use? I logged both of them and didn't catch the difference.
This is also a question about other methods like: `document.remove()`.

Is it safe to use the `document`? It looks cleaner for me that's all..

**Comment by vkarpov15** [comment]
No difference. `document === savedDocument` in the above example, same reference. You can use whichever you prefer.
