### ISSUE TITLE
How do I correct the timestamp?

### ISSUE THREAD

**Issue by Mattw11486** [Automattic/mongoose#10841]
No matter what Schema I use for timestamp it is still setting the time by 5 hours ahead of my time zone.
I have made sure MongoDB Atlas is set to central time zone in settings but it is still showing incorrect timestamp.

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const moment = require('moment-timezone');
const dateCentral = moment.utc().toDate();

console.log(dateCentral);


const MessageSchema = new Schema({
    heard:{
        type: String,
        required: true
    },
    resolution:{
        type: String,
    },
    createdAt: { 
        type: Date, 
        default: Date.now + '2'
    },
});

const Msg = mongoose.model('slack', MessageSchema);
module.exports = Msg;
```

![image](https://user-images.githubusercontent.com/76888925/135790223-64b1a543-6a3d-4b19-9220-f4dc1af36c37.png)

**Comment by sean-daley** [comment]
Generally you have to do it in your code. Mongo typically stores dates in UTC format. The date you are showing is using UTC (+00:00). Right now UTC is 5 hours ahead of central time zone (assuming you are talking about US central time). So
`2021-10-04T03:48:06.512+00:00` should be `2021-10-03T22:48:06.512-05:00` central time.

The timezone settings in Atlas, assuming you are talking about the settings on the Personalization page (My Time Zone and what not) are for display purposes only when you are logged into the Atlas portal. They have no bearing on any other app other than the Atlas web app you use to manage it.

So the times you get back from Mongo will always be in UTC and then you can convert them to local time if there is some display reason to do so.

So if you did something like:
```
console.log(moment(message.createdAt).local().format('YYYY-MM-DD HH:mm:ss'))
```
That should display what you want. Assuming I'm understanding your issue correctly.

**Comment by Mattw11486** [comment]
Yes, I can get the time to display correctly in console.log. 
```
const dateCentral = moment.utc().toDate();

console.log(dateCentral);
```
Is there a way to add the code to subtract 5 hours from UTC in order for it to display how I want in Mongo?

**Comment by vkarpov15** [comment]
I don't know if there's a way to configure MongoDB Atlas' UI to display times in a different timezone. But keep in mind that the [MongoDB server stores dates as `int64`](https://bsonspec.org/spec.html), so it's up to the application (Atlas UI, your app, etc.) to configure what timezone you want to use when formatting the date as a string.
