### ISSUE TITLE
Export `EnforceDocument<>` from TypeScript types, rename it to something more user-friendly

### ISSUE THREAD

**Issue by Bene-Graham** [Automattic/mongoose#10843]
If we take a slightly modified version of: https://mongoosejs.com/docs/typescript.html

```ts
import { Schema, model, connect } from 'mongoose';

interface User {
    name: string;
    email: string;
    avatar?: string;
}

const schema = new Schema<User>({
    name: { type: String, required: true },
    email: { type: String, required: true },
    avatar: String
});

const UserModel = model<User>('User', schema);

run().catch(err => console.log(err));

function print(entity: /* WHAT GOES HERE??? */) {
    console.log(`${entity._id} -- ${entity.name}`);
}

async function run(): Promise<void> {
    // 4. Connect to MongoDB
    await connect('mongodb://localhost:27017/test');

    const userEntity = await UserModel.findOne().exec();
    if(!userEntity) {
        throw new Error("userEntity is null");
    }
    
    print(userEntity);
}
```

the return type from findOne is 
```ts 
(Document<any, any, User> & User & { _id: Types.ObjectId; }) 
```
 that seems very verbose for putting in the function signature each time I want to reference it.

I also could not find a utility type build into the type definitions. Should we create our own type to wrap this up 
```ts
type DocDef<T> = (Document<any, any, T> & T & { _id: Types.ObjectId; });
``` 
or add _id to the User interface?

I am wondering what is the best practice?

Also curious what DocumentDefinition is supposed to be used for?

**Comment by vkarpov15** [comment]
Add `_id: Types.ObjectId` to `interface User {}`. We should add that to the docs.

```ts
interface User {
    _id: Types.ObjectId;
    name: string;
    email: string;
    avatar?: string;
}
```

**Comment by Duchynko** [comment]
How does adding `_id` to your model interface help here? The returned object would still be of the type `Document<any, any, User> & User & { _id: Types.ObjectId; }`, right? Wouldn't a utility type - as proposed by @Bene-Graham - make more sense here?

Also, if you add `_id: Types.ObjectId` to your model interfaces, then TypeScript will force you to supply `_id` also during document creation. What's the recommended way to go around it? Maybe manually creating ObjectId in the code?

```typescript
User.create({
    _id: , new Types.ObjectId() // this is required
    username: "Dumbledore",
    email: "dumbledore@hogwarts.com,
    avatar: "<url>"
})
```

**Comment by Bene-Graham** [comment]
EnforceDocument does seem to do what I want.

Should the return types for find, findAll(), etc then return a EnforceDocument?

**Comment by Bene-Graham** [comment]
@Duchynko it is defiantly related

**Comment by Duchynko** [comment]
> vkarpov15 changed the title [6.x] Types - What type should be used to pass a document around and have access to _id Export EnforceDocument<> from TypeScript types, rename it to something more user-friendly

I think this will solve https://github.com/Automattic/mongoose/issues/10837 as well 👍🏼
