### ISSUE TITLE
Aggregate cursor exec is not a function

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#10862]
**Do you want to request a *feature* or report a *bug*?**
Bug, or outdated documentation

**What is the current behavior?**
Referring to: https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-cursor
The example states:

```js
const cursor = Model.aggregate(..).cursor({ batchSize: 1000 }).exec();
cursor.eachAsync(function(doc, i) {
  // use doc
});
```

However, our code yields:

```
TypeError: Model.aggregate(...).collation(...).cursor(...).exec is not a function
```

Removing the `exec` part returns a cursor as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
For `exec` to work, or docs to be updated to no longer require this.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 6.0.7

**Comment by vkarpov15** [comment]
@adamreisnz using `exec()` after querying is not required (unless you're using cls-hooked or similar libs), but advisable for cleaner stack traces.

**Comment by ligolas** [comment]
It seems the changes between mongoose 5 and mongoose 6 caused your problem. In mongoose 5 aggregate.cursor return `this`(the aggregate object), not the promise, and you have to` exec()` to get the promise. In mongoose 6 `aggregate.cursor()` return `AggregateCursor` just like `QueryCursor` ( query.cursor() return QueryCursor in mongoose 5 )
@adamreisnz

**Comment by navish-fleetronix** [comment]
> It seems the changes between mongoose 5 and mongoose 6 caused your problem. In mongoose 5 aggregate.cursor return `this`(the aggregate object), not the promise, and you have to` exec()` to get the promise. In mongoose 6 `aggregate.cursor()` return `AggregateCursor` just like `QueryCursor` ( query.cursor() return QueryCursor in mongoose 5 ) [@adamreisnz](https://github.com/adamreisnz)

Then what to do now?

**Comment by vkarpov15** [comment]
@navish-fleetronix what is the issue you're having?
