### ISSUE TITLE
Map type doesn't change into plain object when using toJSON

### ISSUE THREAD

**Issue by RachelleJanssen** [Automattic/mongoose#10872]
Node: 14.15.0
Typescript: 4.1.3
Mongoose: 6.0.10
MongoDB: 4.4.3

I was working on a test file to see if I was able to get mongoose-delete working with mongoose 6, while printing out the result I noticed that a document.toJSON() doesn't tell the compiler that the return type of my Map property has changed into a plain object.

When I want to use the object somewhere down the line and, for example, put something in one of the 'en-US' key-value the compiler will refuse to compile. It will give me a type error because it still thinks it's a Map and it wants me to use the get and set functions. When I console.log it though I can clearly see that it's a plain js object. It would be great if mongoose would show this in the return type as well. A Record type, with the keys from the Map, would would even be better.

The reason that I brought this up is because we've experienced some issues with our title translations in the past. We have yet to decide how we want to go forward with Map types seeing as how mongoose 6 will help clean up our code.

Do I need to adjust anything in my interfaces, or is this something on the mongoose side?

```
import { createConnection, Document, LeanDocument, Model, Schema, Types } from 'mongoose';
import mongooseDelete, { SoftDeleteDocument } from 'mongoose-delete';

interface ITest {
  name: string;
  title: Map<string, string>;
}
interface InstanceMethods {
  iMethod1: (param1: string) => string; // instance method
  iMethod2: (param1: string) => string; // instance method
}
interface TestModel extends Model<(ITest & SoftDeleteDocument), {}, InstanceMethods> {
  sMethod1: (param1: string) => string; // static model method
  sMethod2: (param1: string) => string; // static model method
}
type TestDocument = Document<any, any, (ITest & SoftDeleteDocument)> & (ITest & SoftDeleteDocument) & { _id: Types.ObjectId } & InstanceMethods;
type Test = LeanDocument<TestDocument>;

const ModelSchema = new Schema<(ITest & SoftDeleteDocument), TestModel, InstanceMethods>({
  name: { type: Schema.Types.String },
  title: { type: Schema.Types.Map, of: Schema.Types.String },
});

ModelSchema.plugin(mongooseDelete)

ModelSchema.statics.sMethod1 = function () {
  this.sMethod2('test');
};
ModelSchema.statics.sMethod2 = function () {};

ModelSchema.methods.iMethod1 = function () {
  this.iMethod2('test');
};
ModelSchema.methods.iMethod2 = function () {};

// create lazy connection object to connect later
const connection = createConnection('mongodb://localhost:27017/test');

export const TestModelCompiled = connection.model('testModel', ModelSchema);

const modelInstance = new TestModelCompiled({
  name: 'name 1',
  title: new Map([
    ['en-US', 'this is a title']
  ]),
});

modelInstance.iMethod1('test');

TestModelCompiled.sMethod1('test');

async function saveFunction() {
  const modelInstance = new TestModelCompiled({
    name: 'name 2',
    title: new Map([
      ['en-US', 'this is a title']
    ]),
  });
  modelInstance.save()
}

async function listFunction() {
  const documentsFound = await TestModelCompiled.find().exec()
  const documentsAsJson: Test[] = documentsFound.map(doc => doc.toJSON()) <-- Should change the title
  console.log(documentsAsJson);
}

async function run() {
  await saveFunction()
  await listFunction()
}

run()
```

When using toObject (item.title type = Map, which is what I expect)
![image](https://user-images.githubusercontent.com/14125851/136985880-e61b1fc7-d108-4d01-8fa0-cfb80087fda3.png)

When using toJSON (item.title type = Object but intellisense says it's a Map)
![image](https://user-images.githubusercontent.com/14125851/136985986-e7ace737-9b66-4d15-aef0-692c13134910.png)

**Comment by vkarpov15** [comment]
My comment in https://github.com/Automattic/mongoose/issues/10872#issuecomment-946781920 was slightly incorrect. In #6478 we made it so that `toJSON()` converts maps to POJOs by default. We can't change this behavior until the next backwards breaking change.

In 0648fb0 we made it so that `toJSON()` flattens maps in TS output by default. That should fix your issue.
