### ISSUE TITLE
Is it possible to make the `type` field dynamic?

### ISSUE THREAD

**Issue by yahiarefaiea** [Automattic/mongoose#10879]
Based on this question ([#5119](https://github.com/Automattic/mongoose/issues/5119)), I was wondering if I can do the same, but with the `type` field.

In my case, I'm building a library where I save images to the database based on the configurations. I have to cover 2 ways, one is for `buffer` images which should be type of (`Buffer`) and the other is for `base64` which should be type of ('String').

I tried doing this:
```
new Schema({
  imageType: {type: String, enum: ['getBuffer', 'getBase64']},
  imageData: {
    type: function() {
      if(this.imageType === 'getBuffer') return Buffer
      else return String
    },
    required: true
  }
})
```
but it didn't work and returned an error of:
```
TypeError: Invalid schema configuration: `Type` is not a valid type at path `imageData`.
```

I can create 2 fields, one as bufferData and the other as base64Data. but that will look messy.

So, here's my question, is there a way to make the `type` field dynamic? And if that's not possible, then is there a way you can recommend that can help achieve my goal?

**Comment by chumager** [comment]
Hi... 

Why not just use ```Buffer.from(string, "base64")```? 
[Buffer.from](https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#buffer_static_method_buffer_from_string_encoding)
That way you ain't mix data types and saves one field. 

You can also have a pre save (or validate) hook to change the value.
```js
schema.pre("save", function(){
  if(typeof this.imageData === "string") this.imageData = Buffer.from(this.imageData, "base64");
});
```

BTW, base64 is 4 times bigger than buffer (256/64)
