### ISSUE TITLE
Cursor 'close' event emitted twice 

### ISSUE THREAD

**Issue by iovanom** [Automattic/mongoose#10876]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the cursor is used with pause/resume the event 'close' is emitted twice.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
cursor = TestModel.find({}).cursor();
cursor.on('data', (obj) => {
  cursor.pause();
  // simulate the async actions using obj
  setTimeout(() => cursor.resume(), 50);
});
cursor.on('close', () => console.log('close'));
```

The code below will get two 'close' in the console;

**What is the expected behavior?**

The expected behavior is to receive only one 'close' event.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node - 14.18.0
mongoose - 5.13.11
MongoDB - 4.4.9

**Comment by IslandRhythms** [comment]
close onnly fires once for me

```javascript

const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);



async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const cursor =  await Test.find({}).cursor();

    cursor.on('data', (obj) => {
      cursor.pause();
      // simulate the async actions using obj
      setTimeout(() => cursor.resume(), 50);
    });
    cursor.on('close', () => console.log('close'));
  
}


run();




```

**Comment by iovanom** [comment]
> close only fires once for me
> 
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>     name: String
> });
> 
> const Test = mongoose.model('Test', testSchema);
> 
> 
> 
> async function run() {
>     await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
>     useUnifiedTopology: true,});
>     await mongoose.connection.dropDatabase();
>     const cursor =  await Test.find({}).cursor();
> 
>     cursor.on('data', (obj) => {
>       cursor.pause();
>       // simulate the async actions using obj
>       setTimeout(() => cursor.resume(), 50);
>     });
>     cursor.on('close', () => console.log('close'));
>   
> }
> 
> 
> run();
> ```

you don't have any document in collection. Have a look on my tests that I have added.

**Comment by iovanom** [comment]
@vkarpov15 I've created a PR for version 5.x 
https://github.com/Automattic/mongoose/pull/10897
