### ISSUE TITLE
String comparison using _id & Schema.Types.ObjectId sometimes fail

### ISSUE THREAD

**Issue by EricLiuCY** [Automattic/mongoose#10880]
**Do you want to request a *feature* or report a *bug*?**

Asking for help. I could not find anything in-depth enough & up to date on this topic on google/stackoverflow

**Question?**

I am using TypeScript on a MERN project, and the compiler interprets the _id object as:
_id: (property) Document<string, any, any>._id?: string | undefined

I am using _id as if it was a string throughout my project. However, I've noticed that the outcome of comparing _id with a string literal is not deterministic. 

For example, sometimes the comparison _id === some other id succeeds, and sometimes it fails.

What is proper way to use _id and Schema.Types.ObjectId as if it were a string? Should I be using the id virtual?

Also wondering if there are performance benefits to using .populate(), versus taking the id and performing a .findById(). 

Thanks!

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html#objectid-valueof
This is a new feature of mongoose 6 that may solve your problem

**Comment by EricLiuCY** [comment]
> https://mongoosejs.com/docs/migrating_to_6.html#objectid-valueof This is a new feature of mongoose 6 that may solve your problem

Thanks, I will!
