### ISSUE TITLE
connection event open is not equivalent to connected

### ISSUE THREAD

**Issue by mpodolsk** [Automattic/mongoose#10886]
its either a bug or bad documentation.

mongoose.connection emitted `connected` but never `open`.

as per [docs](https://mongoosejs.com/docs/connections.html#connection-events)

_open: Equivalent to connected_ 

I used in my app `connected` event as a ready signal to make sure my app was ready to receive traffic.

what ended up happening is that the app was receiving traffic it was not able to service.

the `open` event was never emitted and I think that is the one needed for mongoose to operate properly?

Looking at the source code, `open` and `connected` are not exactly identical. It would be nice to note the difference even if they are subtle.
```json
    "mongoose": "^5.13.10",
```

**Comment by IslandRhythms** [comment]
If there is a slight difference, I think we should mention that in the docs.

**Comment by vkarpov15** [comment]
@mpodolsk there's a note [here](https://mongoosejs.com/docs/connections.html#connection-events) about connection events in replica sets:

"In a replica set, Mongoose will emit 'disconnected' if it loses connectivity to the replica set primary, and 'connected' if it manages to reconnect to a the replica set primary."
