### ISSUE TITLE
Are there performance benefits to using populate over findById?

### ISSUE THREAD

**Issue by EricLiuCY** [Automattic/mongoose#10892]
I am wondering if there are performance benefits to using populate over findById? Could not find anything on this on the internet.

So for pseudo code example. Say I have two Models.

```
UserModel = Schema({
    storeId : Schema.Types.ObjectId;
})

StoreModel = Schema({
    name: string;
})
```
Now user wants to know the related store's name.

```
// Option 1
const res = await UserModel.findById(userId).populate(storeId);
const storeName = res.storeId.name;

// Option 2
const user = await UserModel.findById(userId);
const store = await StoreModel.findById(user.storeId);
const storeName = StoreModel.findById(user.storeId).name;
```

Are there any significant performance benefits to using Option 1, populate, over Option 2, findById?

**Comment by AbdelrahmanHafez** [comment]
No, what happens internally is that `UserModel.findById(...).populate(...)` calls `StoreModel.findOne(...)` and then modifies the document, It's more of a convenient way to do that, and allows you to populate multiple fields more conveniently:
```ts
const res = await UserModel.findById(userId).populate([
  { path: 'storeId' },
  { path: 'cityId', select: 'name' },
  { path: 'countryId', select: 'geolocation', lean: true }
]);
const storeName = res.storeId.name;
```

I'll close this issue, let me know if I can assist with anything else. 👍
