### ISSUE TITLE
Collation not set during collection creation (5.x)

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#10896]
Bug:

According to the docs:

> Before Mongoose builds indexes, it calls Model.createCollection() to create the underlying collection in MongoDB if autoCreate is set to true. Calling createCollection() s**ets the collection's default collation based on the collation option** 

So I would expect my collections to have collation information associated if the `collation` option is set for the schema.

**What is the current behavior?**

New collections do not have a collation set. I noticed this with an older 5.x version of mongoose and the latest (5.13.11).

**Repro**

I pretty much took the snippet from the docs (added an index, otherwise my collection wasn't auto-created)

```
export const schema = new mongoose.Schema({
    name: {type: String, index: true },
}, { collation: { locale: 'en_US', strength: 1 } });


export const MediumModel = mongoose.model("foo", schema);
```

On startup, my collection is created, but without any collation information:

```
db.getCollectionInfos({name: 'foo'})

[
    {
        "name" : "foo",
        "type" : "collection",
        "options" : {},
        "info" : {
            "readOnly" : false,
            "uuid" : UUID("9634b30a-7a98-43c6-b6bc-1ebc043f5019")
        },
        "idIndex" : {
            "v" : 2,
            "key" : {
                "_id" : 1
            },
            "name" : "_id_"
        }
    }
]
```

**Comment by vkarpov15** [comment]
I suspect this is because 6.x has the `autoCreate` option set to true by default, so Mongoose automatically creates the collection before building indexes. We'll check and see if this is something we can fix for 5.x.

**Comment by IslandRhythms** [comment]
Can you show me what you see on mongoose 6? I ran the script and shell command on both versions and its identical
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: {type: String, index: true},
}, { collation: { locale: 'en_US', strength: 1}});

const Test = mongoose.model('Foo', testSchema, 'Foo');

async function run() {
    await mongoose.connect('mongodb://localhost:27017/');
    await mongoose.connection.dropDatabase();
    await Test.create({name: 'Daniel'});

}

run();
```

**Comment by vkarpov15** [comment]
I took a closer look and this is expected behavior. In Mongoose 5, you explicitly need to set `autoCreate` to `true` on either your schema or globally:

```
new Schema({ ... }, { autoCreate: true });
```

Or:

```
mongoose.set('autoCreate', true);
```

Otherwise Mongoose won't call `createCollection()` before creating indexes.
