### ISSUE TITLE
TypeError: this.__parentArray.$path is not a function

### ISSUE THREAD

**Issue by RezaErfani67** [Automattic/mongoose#10891]
i used to version 5.13.11

**Do you want to request a *feature* or report a *bug*?**
i want to report a bug

**What is the current behavior?**
when i want to update an array in subdocument,it  shows me an error:

text: "TypeError: this.__parentArray.$path is not a function\n    ...
EmbeddedDocument.ArraySubdocument.$__pathRelativeToParent (D:\\backend-mongo\\node_modules\\mongoose\\lib\\types\\ArraySubdocument.js:145:29)\n   ...
EmbeddedDocument.Subdocument.invalidate (D:\\backend- ongo\\node_modules\\mongoose\\lib\\types\\subdocument.js:202:25)\n    at EmbeddedDocument.$set (D:\\backend-mongo\\node_modules\\mongoose\\lib\\document.js:1453:12)\n    at EmbeddedDocument.set [as _id] (D:\\backend-mongo\\node_modules\\mongoose\\lib\\helpers\\document\\compile.js:174:19)\n    at D:\\backend-mongo\\shared\\Task\\functions.js:2506:55\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
update subdocument properly

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 14.16.1
mongodb: 4.4.6
mongoose version: 6.0.11
windows:10

**Comment by RezaErfani67** [comment]
template was updated

**Comment by RezaErfani67** [comment]
```javascript
                               
   priviouseObj = await Task.find();
     for(let eachRow of priviouseObj) {
                                        if (config.isEqual(eachRow._id,obj._id))
                                        {
                                            let ddd=config._.cloneDeep(eachRow);
                                            for(let key in obj){
                                                    ddd[key]=obj[key];
                                            }
                                            tempFinal=ddd;
                                        }
                                    }

```

**Comment by joebowbeer** [comment]
Related to use of _.cloneDeep?

https://github.com/Automattic/mongoose/issues/4260

**Comment by RezaErfani67** [comment]
it is related to _doc
```
 if(ddd.hasOwnProperty('_doc')){
     //mongoose@6
      ddd._doc[key]=obj[key];
  }
  else{
      //mongoose@5
      ddd[key]=obj[key];
  }
```

**Comment by notRyuk** [comment]
I'm facing the same issue in the version **6.4.3**

Code generating the error:
```js
var userObject = createLowerCaseObject()
var users = []
user.find({}, (err, __users) => {
    if(err) return err
    if(__users) {
        users = __users
        console.log("__users", users)
        __users = __users.map(__user => __user._id)
        // console.log(__users)
        for(var __user of __users) {
            delete __user.__v
            userObject[__user[0]].push(__user)
        }
        // this.users = userObject
        // this.user_col = users
        // console.log(this.users)
        cache.set("users", userObject)
        cache.set("user_col", users)
        console.log("users", userObject)
        console.log("user_col", users)
    }
})
```

Schema:
```js
const UserSchema = new Schema({
    _id: String,
    name: {
        first: {type: String, required: true},
        last: {type: String, required: true, default: ""}
    },
    encryption: {type: String, required: true},
    email: {type: String, required: true},
    blogs: {
        type: [{
            _id: {type: String, required: true},
            name: {type: String, required: true},
            description: {type: String, required: true}
        }], 
        required: false, 
        default: []
    }
})
```

**Comment by vkarpov15** [comment]
@notRyuk the below script executes without error, can you please modify the below script to demonstrate your issue? I think I must be missing something, it isn't clear why you're trying to accumulate all users by the first character of their `_id`.

```javascript
const mongoose = require('mongoose');

run().catch(err => {
  console.error(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const UserSchema = new mongoose.Schema({
    _id: String,
    name: {
        first: {type: String, required: true},
        last: {type: String, required: true, default: ""}
    },
    encryption: {type: String, required: true},
    email: {type: String, required: true},
    blogs: {
        type: [{
            _id: {type: String, required: true},
            name: {type: String, required: true},
            description: {type: String, required: true}
        }],
        required: false,
        default: []
    }
  });
  const User = mongoose.model('Test', UserSchema);

  await User.deleteMany({});
  await User.create({
    _id: 'test', 
    name: { first: 'foo', last: 'bar' },
    encryption: 'foo',
    email: 'bar'
  });
  
  const userObject = { t: [] };
  let __users = await User.find();
  const users = __users;
  __users = await __users.map(u => u._id);
  for (const __user of __users) {
    delete __user.__v;
    userObject[__user[0]].push(__user);
  }
  
  console.log(userObject);
}
```

**Comment by notRyuk** [comment]
Oh I was using the `JSON.stringify` method to store the data in the cache class which I created. And it was causing the same error that is mentioned above. I think it is due to recursiveness of the arrays of `SubDocument`.

And as for the `_id` parameter i'm storing the username as the id since it's easy for me to handle the next part (Even though I have to make 2 calls when the user is trying to change the id).
