### ISSUE TITLE
Model object properties inferred types is always `any`

### ISSUE THREAD

**Issue by iammola** [Automattic/mongoose#10895]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Using TypeScript, from a Model object, the schema property doesn't inherit the Schema from the Model and defaults to any and then the obj property to see the original object passed to the schema constructor also defaults to any

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "downlevelIteration": true,
    "sourceMap": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", ".next", "out"]
}
```

**What is the expected behavior?**
I expected the inferred types to be inherited from the Model.

I can solve this by editing the `index.d.ts`
On [Line 996:](https://github.com/Automattic/mongoose/blob/14a571dcea165613edfcae6d5e0f310e96930be7/index.d.ts#L996)
From
```
schema: Schema;
```
To
```
schema: Schema<T>;
```

And [Line 1297](https://github.com/Automattic/mongoose/blob/14a571dcea165613edfcae6d5e0f310e96930be7/index.d.ts#L1297)
From
```
obj: any;
```
To
```
obj: DocType;
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose Version - `6.0.11`
Node.js Version - `v16.10.0`
MongoDB Version - `4.1.2`

**Comment by vkarpov15** [comment]
I don't see any harm in making the `schema: Schema<T>;` change, but the `obj: DocType` change is incorrect. If anything, it should be `obj: SchemaDefinition<SchemaDefinitionType<DocType>>;`.
