### ISSUE TITLE
Typescript error with type mixed

### ISSUE THREAD

**Issue by israelKusayev** [Automattic/mongoose#10900]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Getting typescript error when using `Mixed` type

```typescript
export interface IPatient {
  birthday?: string | Date;
}

export const patientSchema = new Schema<IPatient>({
  birthday: {
    type: SchemaTypes.Mixed
  }
});

```
`Type '{ type: typeof Schema.Types.Mixed; }' is not assignable to type 'SchemaDefinitionProperty<string | Date>'.
  Types of property 'type' are incompatible.
    Type 'typeof Mixed' is not assignable to type '"string" | StringConstructor | "String" | typeof String | typeof NativeDate | "date" | "Date" | typeof Date'.
      Type 'typeof Mixed' is missing the following properties from type 'StringConstructor': fromCharCode, fromCodePoint, rawts(2322)`

**If the current behavior is a bug, please provide the steps to reproduce.**

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": ["src/**/*"]
}
```

**What is the expected behavior?**

Mixed should behave as any type (sometimes I can't use mongoose types but I still want to use typescript types

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 6.0.11
typescript 4.4.4

**Comment by vkarpov15** [comment]
I wish we had a better solution for this, but we'll fix this by allowing `Mixed` for all schema definition properties. Mongoose currently doesn't have support for union types - "`birthday` is a string or date" is not something Mongoose schemas can represent currently. Also, it doesn't look like there's a way to check if a type is a union in TypeScript, so we'll have to go with this approach for now :+1:

**Comment by rkreienbuehl** [comment]
Hi
I am using mongoose `v6.2.3` and facing the same error when using `Mixed`. Could it be, that this fix is no longer valid? Is there an other way to deal with this error?

My code looks like this:
```ts
export type TMenuStatus = Record<string, 'EXPANDED' | 'COLLAPSED'>[];

export interface IUserProp {
  ...
  menuStatus: TMenuStatus;
  ...
}

const userSchema = new Schema<IUserProp>({
  ...
  menuStatus: { type: Schema.Types.Mixed, default: {} },
  ...
})
```

And the error I get:
```
Type '{ type: typeof mongoose.Schema.Types.Mixed; default: {}; }' is not assignable to type 'SchemaDefinitionProperty<TMenuStatus>'.
  Types of property 'type' are incompatible.
    Type 'typeof Mixed' is not assignable to type 'AnyArray<Schema<any, any, any, any>> | AnyArray<{ [x: string]: SchemaDefinitionProperty<"EXPANDED" | "COLLAPSED">; }> | AnyArray<...>'.
      Type 'typeof Mixed' is missing the following properties from type 'readonly SchemaTypeOptions<Record<string, "EXPANDED" | "COLLAPSED">>[]': concat, join, slice, indexOf, and 15 more.ts(2322)
```

**Comment by vkarpov15** [comment]
@rkreienbuehl sorry for the delay in fixing this. Our previous fix was to support `menuStatus: Schema.Types.Mixed`, in 6.2.11 we'll also support `menuStatus: { type: Schema.Types.Mixed, default: {} }`
