### ISSUE TITLE
Please release official new versions

### ISSUE THREAD

**Issue by lorand-horvath** [Automattic/mongoose#10905]
Github has changed today the way it lists releases, so unless it's an official release, we can't find it here anymore https://github.com/Automattic/mongoose/releases
The latest official release is shown to be 4.0.2 from 7 years ago!
We can still find the latest releases 5.x and 6.x under the tags section https://github.com/Automattic/mongoose/tags but it's awkward for people to see that the latest official release is from 7 years ago :-)

**Comment by lorand-horvath** [comment]
status: wontfix

**Comment by vkarpov15** [comment]
Added a webhook to handle this here: https://github.com/mongoosejs/backend/blob/e5e1ce451b933c22d283f44f86f2994e9cd6f444/webhookGitHubComment/index.js#L79-L82
