### ISSUE TITLE
cursor never finishes

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#10902]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
this PR https://github.com/Automattic/mongoose/pull/10878 breaks our setup, some streams now never finish.

**If the current behavior is a bug, please provide the steps to reproduce.**
It#s hard to tell what's casuing this, because some stream do finish, but some do not. It seems around 60-70% never finish.
![image](https://user-images.githubusercontent.com/5757263/137886016-1afa1c81-10d1-46da-bbd3-934920262d9f.png)

**What is the expected behavior?**
stream should fire finish event like it was before.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 6.0.11: not working
mongoose 6.0.10: works

**Comment by simllll** [comment]
It seems the only event that is fired is a "drain" event, after that..nothing happens anymore.

**Comment by iovanom** [comment]
PR: https://github.com/Automattic/mongoose/pull/10906
