### ISSUE TITLE
cant connect to DB with Node v17

### ISSUE THREAD

**Issue by Taelyn** [Automattic/mongoose#10917]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cant connect to DB on node v17

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
async function startUp() {
    // Connect to mongoose database
    mongoose.connect("mongodb://localhost:27017/xxxxxx", {
        useNewUrlParser: true,
        useUnifiedTopology: true
    }).then(() => {
        // If it connects log the following
        client.log.info("Connected to MongoDB database.");
    }).catch((e) => {
        // If it doesn't connect log the following
        client.log.error("Unable to connect to MongoDB database. Error:" + e.stack);
    });
    client.login(client.credentials.token).catch(e => {
        client.log.error(e.toString());
        process.exit(1);
    });
}
startUp();
```
**What is the expected behavior?**
That it connects like it did before :D

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
MongoDB: 5.0.3
Node: 17.0.1
Mongoose: 6.0.12

If i downgrade node to v16.12.0 then it works fine

**Comment by replete** [comment]
I've had issues around this today, see [mentioned issue](https://github.com/TomDoesTech/Testing-Express-REST-API/issues/2) for details, you should see the same type of problem here and a codebase to check out.

**Comment by Taelyn** [comment]
> Change `localhost` to `127.0.0.1` and it should work. It's because the DB is listening only on `127.0.0.1` and not dualstack. Thus, connecting to `::1` (IPv6-localhost) will obviously fail. Other options: downgrade to NodeJS v16.x, or even better make the DB listen on `::1` instead of localhost/127.0.0.1.
> 
> See here to set `net.ipv6` to `true`: https://docs.mongodb.com/manual/core/security-mongodb-configuration/

Thanks! Solved the issue for me with Node v17.x

**Comment by treysis** [comment]
You maybe wanna try starting MongoDB with net.ipv6 = true and see if that works as well?

**Comment by replete** [comment]
FYI for anyone else, my solution was simply to set ipv6 like so:

*mongo.dev.conf*
```conf
net:
    port: 27777
    ipv6: true
```

Run mongo with `mongod --config mongo.dev.conf`

Alternatively just pass in the command line argument `mongod --ipv6`

**Comment by Taelyn** [comment]
Yes works also perfect. Ill switch to that solution :) 

Thanks!

**Comment by advait-cs** [comment]
simply change localhost to 127.0.0.1

**Comment by treysis** [comment]
@advait-cs Better to use IPv6 and get ready for the future.

**Comment by advait-cs** [comment]
> @advait-cs Better to use IPv6 and get ready for the future.

how to set it to IPv6??

**Comment by stainlezzking** [comment]
changing localhost to 127.0.0.1 didn't work for me, please who can help
