### ISSUE TITLE
Typescript: Populated doc type overrides for nested fields

### ISSUE THREAD

**Issue by ajwootto** [Automattic/mongoose#10912]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
As per the issue here: https://github.com/Automattic/mongoose/issues/10758

It seems that for typing populated queries, we're now supposed to use the generic parameter on the populate function to provide a set of path overrides which contain populated data. From what I can gather this is meant to replace the old "PopulatedDoc" helper (which I don't see mentioned in the docs anymore).

However, using this paths override approach does not seem to handle nested fields that can be populated from the populate() method (such as a ref field inside an array of objects)

**If the current behavior is a bug, please provide the steps to reproduce.**
Adapted from populate docs:

```typescript
import { Schema, model, Types } from 'mongoose';

// `Parent` represents the object as it is stored in MongoDB
interface Parent {
    child?: Types.ObjectId,
    array: {
        nestedChild: Types.ObjectId
    }[]
    name?: string
}
const ParentModel = model<Parent>('Parent', new Schema({
    child: { type: 'ObjectId', ref: 'Child' },
    array: { type: [{
        nestedChild: { type: 'ObjectId', ref: 'NestedChild' }
    }]},
    name: String
}));

interface Child {
    name: string;
}
const childSchema: Schema = new Schema({ name: String });
const ChildModel = model<Child>('Child', childSchema);

interface NestedChild {
    name: string
}
const nestedChildSchema: Schema = new Schema({ name: String });
const NestedChildModel = model<NestedChild>('NestedChild', nestedChildSchema);


// Populate with `Paths` generic `{ child: Child }` to override `child` path
ParentModel.findOne({}).populate<{ child: Child }>('child').orFail().then(doc => {
    // Works
    const t: string = doc.child.name;
});

ParentModel.findOne({}).populate<{ 'array.nestedChild': NestedChild }>('array.nestedChild').orFail().then(doc => {
    // Doesn't work
    const t: string = doc.array[0].nestedChild.name;
});

```

tsconfig:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": [
      "es2017",
      "dom"
    ],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    }
  },
  "exclude": [
    "node_modules",
    "tmp"
  ]
}
```

**What is the expected behavior?**

I would hope that providing overrides using the same nesting syntax as the populate call would allow me to override the type of the returned fields, or that there is a documented alternative approach to handling this case.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.Js: 14.15.0
Mongoose: 6.0.11
MongoDB: 5.0.3

**Comment by IslandRhythms** [comment]
fixed

**Comment by IslandRhythms** [comment]
The name is still printing so I guess there is some sort of disconnect between typescript and mongoose

**Comment by vkarpov15** [comment]
Unfortunately I think this is expected behavior, there's no way for TypeScript to handle dotted paths. You need to override the entire 'array' path as shown below:

```ts
ParentModel.findOne().populate<{ array: { nestedChild: NestedChild }[] }>('array.nestedChild').orFail().then(doc => {
    // Works
    const t: string = doc.array[0].nestedChild.name;
});
```

**Comment by kyvg** [comment]
> there's no way for TypeScript to handle dotted paths.

since TS 4.1 :)

```
type DottedPaths<T> =
  T extends Record<infer G, infer K> ?
    G extends string ?
      K extends object ? G | `${G}.${DottedPaths<K>}` : G
    : never
  : never;

const parent = {
  nested: {
    child: {
      foo: 'hello',
    },
  },
} as const;

type Parent = typeof parent
type DottedParent = DottedPaths<Parent> // "nested" | "nested.child" | "nested.child.foo"
```

**Comment by kyvg** [comment]
> there's no way for TypeScript to handle dotted paths

@vkarpov15 

I modified this code to support array paths
https://stackoverflow.com/questions/66655728/property-path-with-template-literal-types

```
type DotPrefix<T extends string> = T extends '' ? '' : `.${T}`;

type DottedPath<T> =
  T extends any[] ? DottedPath<T[number]> :
  T extends object ? (
    { [K in Exclude<keyof T, symbol>]: K | `${K}${DotPrefix<DottedPath<T[K]>>}`}[Exclude<keyof T, symbol>]
  ) : ''

type ChildArray = {
  foo: number;
}

type Child = {
  bar: string;
}

type Parent = {
  array: ChildArray[],
  single: Child
  foobar: number;
};

type DottedParent = DottedPath<Parent> // "array" | "single" | "foobar" | "array.foo" | "single.bar"
```
