### ISSUE TITLE
mongoose update only not null fields?

### ISSUE THREAD

**Issue by siamahnaf198** [Automattic/mongoose#10924]
If I want to update already created collection, I want only save not null fields.

Example- Suppose I create a collection Here User-

```
name: "Siam Ahnaf"
password: "12345678"
role: "user"
```

This is created collection. Then I want to update it. For updating I get this object from frontend application like this-
```
{name: "",
password: "98765432"
role: "Admin"}
```

Here I can see name is empty that I get from frontend application. When I update it with 
`User.findByIdAndUpdate(req.user._id, {...input})`

It update the collection to with empty name. After updating my collection is like this-

```
name: ""
password: "98765432"
role: "Admin"
```

But I want when name is empty then it will not save this empty valuse. It remain previous value. How can I do that?

**Comment by vkarpov15** [comment]
You can use a [custom setter](https://mongoosejs.com/docs/tutorials/getters-setters.html):

```javascript
new Schema({
  // ...
  name: {
    type: String,
    set: function omitEmptyString(v) {
      if (this instanceof mongoose.Query /* only run on queries */ && v === '') {
        return undefined;
      }
      return v;
    }
  }
});
```
