### ISSUE TITLE
Change .model() requiring 'schema' param for retrieving models

### ISSUE THREAD

**Issue by BuildersRejected** [Automattic/mongoose#10928]
Feature or enhancement

I am dynamically creating Schemas (and Models based on those Schemas) from a module file as POJO. This works great, but when trying to retrieve Models using `.model()`, it requires a `name` and a `schema` (The name is gathered from a REST call). This limits my ability to recall models from a different place in my program. 

POJO: `messageTypes.js`
```js
MessageTypes: {
  Test: {
      title: "Test",
      subUrl: "test",
      messageSchema: {
        text: 'String',
        date: 'Date',
        misc: {
            type: {}
        }
    },
    //more complex MessageTypes.....
}
```
To get around this, I have saved my models in an array to easily loop through them and pull one with a name check. This defeats the purpose of being able to call `.model()` to get connection or mongoose instance Models and requires me to pass around references to them.

Creation: `declareSchemas.js`
```js
for (type in MessageTypes) {
    let sch = new mongoose.Schema(MessageTypes[type].messageSchema);
    let mod = mongoose.model(MessageTypes[type].subUrl, sch)
    watches.push(mod.watch())
    messageModels.push(mod);
}
```

So, I end up doing...

Usage: `repo.js`
```js
const {messageModels} = require('./declareSchemas');
//....
function findModel(subUrl) {
    for (model in messageModels) {
            if (messageModels[model].modelName == subUrl) {
                 return messageModels[model];
            }
    }
}
//....
findModel(name).find().limit(limit).then(messages => messages.slice().reverse())
```
Versus:
`mongoose.model(name).find().limit(limit).then(messages => messages.slice().reverse())`

in order to use the .model() functionality as intended I would have to loop through models and schemas or some other workaround as they are not explicitly defined. I fear as my program gains features this method will become more intensive to implement.

Since you can't pass a different `schema` into the `.model()` function after initial creation without getting an error, I don't personally see the need for the `schema` param if you aren't creating a new Model.

**Comment by vkarpov15** [comment]
`mongoose.model(name)` should retrieve the model by name. Do you get some error when you do that?

**Comment by BuildersRejected** [comment]
I was getting an error saying it couldn't find Schema 'undefined'. But, now that I have re-tested it to produce the error, I realize I must have done something wrong because it works. I'm sorry. Completely my fault
