### ISSUE TITLE
$pull not working for nested array

### ISSUE THREAD

**Issue by akashbijwe** [Automattic/mongoose#10926]
Below I have a document in MongoDB:

 {

    "token": "abc",
    "user_id": "123",
    "client_id": "124",
    "_id": "125",
    "invoice": {
        "status": "inprogress",
        "items_attributes": [
            {
                "description": "Item from postman 3",
                "quantity": "0",
                "cost_on": "fixed_price",
                "cost_per": "120",
                "taxes_attributes": [
                    {
                        "name": "gst",
                        "tax_type": "rupee",
                        "tax_amt": "50",
                        "_id": "24",
                        "_destroy": true
                    },
                    {
                        "name": "gst2",
                        "tax_type": "percentage",
                        "tax_amt": "10",
                        "_id": "25"
                    }
                ],
                "_id": "61767ba912a0af85236288ac"
            },
            {
                "description": "Item from postman 2",
                "quantity": "0",
                "cost_on": "fixed_price",
                "cost_per": "120",
                "taxes_attributes": [
                    {
                        "name": "gst",
                        "tax_type": "rupee",
                        "tax_amt": "50",
                        "_id": "26"
                    },
                    {
                        "name": "gst2",
                        "tax_type": "percentage",
                        "tax_amt": "10",
                        "_id": "27",
                        "_destroy": true
                    }
                ],
                "_id": "39"
            }
        ]
    }
}

I am passing **_destroy: true** in API so that I can delete that particular object which has this property.
I want to delete all the objects in the **taxes_attributes** which has this **_destroy: true** property present.
Below query, I am using to delete that particular object.
```

 const queryObjectsForTax = []
 taxAttributesFromRequestpayload.forEach(element => {
               queryObjectsForTax.push({
                 "_id": element._id
               });
             });
 
 const responseFromUpdate= await invoiceModel.findOneAndUpdate({
               _id: req.body._id,
               client_id: req.body.client_id
             }, {
               $pull: {
                 'invoice.items_attributes': {
                   'taxes_attributes': {
                       $elemMatch : {
                       $or : queryObjectsForTax
                     } 
                   }
                 }
               }
             }, {multi: true, safe: true, new: true})

```

Not sure what's wrong with this query, I am getting a successful response but that object is not getting deleted from the document.

Any help here will be really appreciated, Thanks in advance! :)

**Comment by vkarpov15** [comment]
See https://stackoverflow.com/questions/5228210/how-to-remove-an-element-from-a-doubly-nested-array-in-a-mongodb-document . TLDR; you need to use the all positional operator if you want to `$pull` from a nested array. 

```javascript
$pull: {
  'invoice.items_attributes.$[].taxes_attributes': { $or: queryObjectsForTax }
}
```

**Comment by akashbijwe** [comment]
Hey @vkarpov15 ,
I really appreciate your help, this fixed my issue.
Thank you & Happy coding. 🍻
