### ISSUE TITLE
Find not correctly when field doesn't exist

### ISSUE THREAD

**Issue by buinguyet** [Automattic/mongoose#10932]
+ In database, I just have some fields such as: _id, view, export, create, update
+ Success case correctly:  
    - Find with mongodb: {_id: "[id_value]", view: true} => success
    - Find with mongoose: {_id: "[id_value]", view: true} => success
+ Success case incorrectly:
    - Find with mongodb:  {_id: "[id_value]", listActive: true} => null (true, because listActive doesn't exist)
    - Find with mongoose: {_id: "[id_value]", listActive: true} => success (unexpected, because listActive doesn't exist)
=> Problems: WHY field listActive doesn't exist but still return result?

**Comment by vkarpov15** [comment]
Mongoose 6 filters out fields that aren't in your schema by default. See [migration guide](https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict).

If this behavior causes problems for you, you can disable it globally and get the Mongoose 5behavior (allow passing any fields into the query by default) by disabling `strictQuery` globally:

```javascript
mongoose.set('strictQuery', false);
```
