### ISSUE TITLE
Schema.Types.Mixed improperly casts ObjectId query filter values

### ISSUE THREAD

**Issue by jmikrut** [Automattic/mongoose#10937]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

We use Mongoose extensively within [Payload CMS](https://payloadcms.com). First off, thank you for the work that you do.

In Payload, we support a Relationship field, which stores IDs of related documents. We also support allowing collections to modify their `_id` schema type. The `_id` schema type can be either a `string`, `number`, or `ObjectId`.

Because of the above, our Relationship field uses the `Mixed` schema type to avoid type casting. However, we still need to filter by IDs. We are handling type casting manually.

When we pass a deliberately formatted `ObjectID` to a filter, like this:

```js
const filter = { owner: new mongoose.Types.ObjectId('5ff7744437c1cc4e6b481bf5') };
``` 

We can see through using `debug` that the filter is being casted to an empty object, even in spite of its `Mixed` schema type:

```js
{ owner: {} };
```

If we pass any other value besides an ObjectId, Mongoose rightfully does not cast the value.

**What is the expected behavior?**

Mongoose should not modify query filter values for `mixed` schema types.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 6.0.12
Node: 14.17.0

**Comment by vkarpov15** [comment]
@jmikrut the below script works without error, and shows that Mongoose doesn't minimize out ObjectIds:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({ relationship: Schema.Types.Mixed });
  const Test = mongoose.model('Test', schema);

  const id = new mongoose.Types.ObjectId('5ff7744437c1cc4e6b481bf5');
  await Test.create({ relationship: id });

  const doc = await Test.findOne({ relationship: id });
  console.log(doc);
}
```

Output:

```
Mongoose: tests.insertOne({ relationship: new ObjectId("5ff7744437c1cc4e6b481bf5"), _id: new ObjectId("6192a09e1632cba35331611d"), __v: 0}, { session: null })
Mongoose: tests.findOne({ relationship: new ObjectId("5ff7744437c1cc4e6b481bf5") }, { projection: {} })
{
  _id: new ObjectId("6192a09e1632cba35331611d"),
  relationship: new ObjectId("5ff7744437c1cc4e6b481bf5"),
  __v: 0

```

Try running `npm list | grep "mongo"` and make sure you don't have multiple versions of Mongoose installed. My best guess here is that you're generating ObjectIds from one copy of the Mongoose module and queries from another, that might explain the behavior you're seeing.
