### ISSUE TITLE
Discriminator - reUse

### ISSUE THREAD

**Issue by cacothi** [Automattic/mongoose#10931]
**Do you want to request a *feature* or report a *bug*?**
Bug (?!)

**What is the current behavior?**
When using model.discriminator(name, schema), I get the following error when running by the second time:
`Error('Discriminator with name "' + name + '" already exists');`

The issue is that my code make references of schema and models dynamically, and when I try to refer a model that already contain that discriminator I get this error.

**If the current behavior is a bug, please provide the steps to reproduce.**

My framework is quite complex to share here, but as mentioned, I have all schemas defined, but the models are instantiated dynamically as the collection name changes depending on the request.

no typescript

**What is the expected behavior?**
The expected behavior is to return the discriminator that already exists. My work around was accessing the model.discriminators property to check if that specifc discriminator already exist:

```
		if (discriminatorType && discriminatorSchema) {

			if (model.discriminators && model.discriminators[discriminatorType])
				return model.discriminators[discriminatorType];

			return model.discriminator(discriminatorType, discriminatorSchema);
		}
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
 "mongoose": "^6.0.12",
Node: 16
MongoDB: 5.x

**Comment by vkarpov15** [comment]
@cacothi sure, a flag for this would be useful. If you can put in a PR with this behavior behind a flag, that would be most appreciated :+1:
