### ISSUE TITLE
querySrv ETIMEOUT

### ISSUE THREAD

**Issue by ChilledLiquid** [Automattic/mongoose#10944]
```Error:Error: querySrv ETIMEOUT _mongodb._tcp.midnight.t37c9.mongodb.net```
Getting this error every time I establish a connection to the database.

**Comment by ChilledLiquid** [comment]
Fixed, added DNS records 8.8.8.8 to my IPv4.

**Comment by nxdjib13** [comment]
had the same issue thank you for sharing the way to fix it

**Comment by sofiane31899** [comment]
had the same issue thank you for sharing the way to fix it
