### ISSUE TITLE
<DB>.findOne buffer timed out after 10000ms but not <DB>.find

### ISSUE THREAD

**Issue by LegendNed** [Automattic/mongoose#10940]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running into `MongooseError: Operation 'users.findOne()' buffering timed out after 10000ms` while using **findOne**, however changing to **find** doesn't error anything and instead return the result. Additionally, while **find** doesnt error anything and **findOne** does, **findOne** sometimes returns the result (document) and then give the error. Lastly the applications connects to the database just fine, here is the logs from server/host:
```bash
2021-10-28T21:09:22.397+0200 I  NETWORK  [listener] connection accepted from 111.222.333.444:64281 #173 (<X> connections now open)
2021-10-28T21:09:22.402+0200 I  NETWORK  [conn173] received client metadata from 111.222.333.444:64281 conn173: { driver: { name: "nodejs|Mongoose", version: "4.1.3" }, os: { type: "Windows_NT", name: "win32", architecture: "x64", version: "10.0.19043" }, platform: "Node.js v16.9.0, LE (unified)", version: "4.1.3|6.0.12" }
2021-10-28T21:09:22.546+0200 I  ACCESS   [conn173] Successfully authenticated as principal local on admin from client 111.222.333.444:64281
```
I ensured there are no permission errors or anything with await and async, all code executed is after the database initialisation!

**If the current behavior is a bug, please provide the steps to reproduce.**

Sample connect function, sample schema file and tsconfig used: https://gist.github.com/LegendNed/2f995a88e3894fba8cd549cb7b1da04e

**What is the expected behavior?**
Expected **findOne** to return one document instead of crashing due to buffer error, as **find** doesn't seem to have the same error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
**Node**: v16.9.0
**Mongoose**: 6.0.12
**MongoDB**: 4.1.3

**Comment by IslandRhythms** [comment]
This code works fine, modify to demonstrate your issue.

```typescript
import * as mongoose from 'mongoose';


// 1. Create an interface representing a document in MongoDB.
interface User {
    name: string;
    email: string;
    avatar?: string;
  }
  
  // 2. Create a Schema corresponding to the document interface.
  const schema = new mongoose.Schema<User>({
    name: { type: String, required: true },
    email: { type: String, required: true },
    avatar: String
  });
  
  // 3. Create a Model.
  const UserModel = mongoose.model<User>('User', schema);
  



 async function test () {
     
    mongoose.connection.on('connecting', () => console.info('database connecting'));
    mongoose.connection.on('connected', () => console.info('database connected'));
    mongoose.connection.on('disconnecting', () => console.info('database disconnecting'));
    mongoose.connection.on('disconnected', () => console.info('database disconnected'));
    mongoose.connection.on('error', () => console.error('database error'));
    mongoose.set('bufferCommands', false);
    mongoose.set('debug', true)
    await mongoose.connect('mongodb://localhost:27017')
    const entry = await UserModel.create({
        name: 'Test', 
        email: 'test@localhost.com',
        avatar: 'Aang'
    });
    console.log(await UserModel.findOne());
    console.log(await UserModel.find());


}

test();
```

**Comment by LegendNed** [comment]
> This code works fine, modify to demonstrate your issue.
> 
> ```ts
> import * as mongoose from 'mongoose';
> 
> 
> // 1. Create an interface representing a document in MongoDB.
> interface User {
>     name: string;
>     email: string;
>     avatar?: string;
>   }
>   
>   // 2. Create a Schema corresponding to the document interface.
>   const schema = new mongoose.Schema<User>({
>     name: { type: String, required: true },
>     email: { type: String, required: true },
>     avatar: String
>   });
>   
>   // 3. Create a Model.
>   const UserModel = mongoose.model<User>('User', schema);
>   
> 
> 
> 
>  async function test () {
>      
>     mongoose.connection.on('connecting', () => console.info('database connecting'));
>     mongoose.connection.on('connected', () => console.info('database connected'));
>     mongoose.connection.on('disconnecting', () => console.info('database disconnecting'));
>     mongoose.connection.on('disconnected', () => console.info('database disconnected'));
>     mongoose.connection.on('error', () => console.error('database error'));
>     mongoose.set('bufferCommands', false);
>     mongoose.set('debug', true)
>     await mongoose.connect('mongodb://localhost:27017')
>     const entry = await UserModel.create({
>         name: 'Test', 
>         email: 'test@localhost.com',
>         avatar: 'Aang'
>     });
>     console.log(await UserModel.findOne());
>     console.log(await UserModel.find());
> 
> 
> }
> 
> test();
> ```

Able to reproduce in the current environment, fault on my end, yet to figure out.

**Comment by Deepbigbrainy** [comment]
import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const URI = process.env.DB_LOCAL_URI; // DBURI

const connectToDatabase = async () => {
    try {
        await mongoose.connect(URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        } as mongoose.ConnectOptions);

        console.log("Connection to MongoDB successful");
    } catch (err) {
        console.error("Error connecting to MongoDB:", err);
    }
};

export default connectToDatabase();

users.findone() buffering timed out after 10000ms !

please help me local in working perfect but, AWS  live in to showing un error.

**Comment by Deepbigbrainy** [comment]
`

import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const URI = process.env.DB_LOCAL_URI; // DBURI

const connectToDatabase = async () => {
    try {
        await mongoose.connect(URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true
        } as mongoose.ConnectOptions);
        console.log("Connection to MongoDB successful");
    } catch (err) {
        console.error("Error connecting to MongoDB:", err);
    }
};

export default connectToDatabase();`

users.findone() buffering timed out after 10000ms !

please help me local in working perfect but, AWS  live in to showing un error.

**Comment by vkarpov15** [comment]
@Deepbigbrainy how are you calling `connectToDatabase()`?

**Comment by vkarpov15** [comment]
Ok, and how are you importing this file?

**Comment by Deepbigbrainy** [comment]
`import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const URI = process.env.DBURI;

const connectToDatabase = async () => {
    try {
        await mongoose.connect(URI,
        );

        console.log("Connection to MongoDB successful");
    } catch (err) {
        console.error("Error connecting to MongoDB:", err);
    }
};

export default connectToDatabase();
`


like this

**Comment by Deepbigbrainy** [comment]
![Uploading Screenshot 2024-05-10 at 6.07.57 PM.png…]()

**Comment by vkarpov15** [comment]
That looks fine. How are you defining your `User` model?
