### ISSUE TITLE
mongoose connection error

### ISSUE THREAD

**Issue by ItsLeon15** [Automattic/mongoose#10941]
Hi there,

So I'm trying to use mongoose but when I do 

`module.exports = mongoose.model("playlists", playlistSchema);`

it returns

`Model { playlists }`

This shouldn't be happening so I was wondering what the problem is?

**Comment by vkarpov15** [comment]
Why shouldn't this be happening? Sounds like expected behavior. You're exporting a model, when you print the object out you get a handy message that says the object is in fact a model.

**Comment by ItsLeon15** [comment]
It's working now
