### ISSUE TITLE
Mongoose throws  "MongoError: Pool was force destroyed" after running for a couple of hours.

### ISSUE THREAD

**Issue by DioSerdar** [Automattic/mongoose#10959]
**Do you want to request a *feature* or report a *bug*?**
Bug? (Possibly)
**What is the current behavior?**
Mongoose throws  MongoError: Pool was force destroyed after running for a couple of hours.
**If the current behavior is a bug, please provide the steps to reproduce.**
I have read somewhere it can be related to the oplog size. And it seems that way. Because it usually happens when the MongoDB replica set hits the rs.oplog max size.
**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
Mongo: 4.4
Node:v14.15.0
Mongoose:6.0.12

I have tried increasing the max size of the rs.oplog from 512MB to 1.5 GB but again it throws the same error as soon as it hits the 1.5gbs. Since I'm using MongoDB Atlas I believe there is no option to configure retention time for the oplogs.
Any ideas?

**Comment by vkarpov15** [comment]
What happens when this error is thrown? Does it cause an operation to fail?

**Comment by DioSerdar** [comment]
No, but every mongoose action hangs. The problem seems to be resolved at the moment it might be related to Atlas as well.
