### ISSUE TITLE
`findX` callback types not inferred correctly in TypeScript

### ISSUE THREAD

**Issue by daniellwdb** [Automattic/mongoose#10954]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The callback of `findById` is not inferred correctly when using TypeScript

**If the current behavior is a bug, please provide the steps to reproduce.**
```typescript
import { Schema, model, Document, ObjectId } from 'mongoose';

interface User extends Document {
  name: string;
  email: string;
  avatar?: string;
}

const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

const UserModel = model<User>('User', schema);

declare const id: ObjectId;

UserModel.findById(id, (err, user) => {});
```

**What is the expected behavior?**
Callback types should be inferred correctly

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
6.0.12

**Comment by daniellwdb** [comment]
Same behaviour for `UserModel.findOne({ _id: id }, (err, user) => {});`, haven't tried others yet

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from "mongoose";

interface User extends mongoose.Document {
  name: string;
  email: string;
  avatar?: string;
}

const schema = new mongoose.Schema<User>({
  name: { type: String },
  email: { type: String},
  avatar: String
});

const UserModel = mongoose.model<User>('User', schema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/');
    await mongoose.connection.dropDatabase();
    const entry = await UserModel.create({name: 'Test'});
     UserModel.findById(entry._id, (err, user) => {
         console.log('execute')
     });
     console.log('done')
}

run();
```

**Comment by daniellwdb** [comment]
I believe you misunderstood the issue @IslandRhythms, it’s nog a runtime error but type issue `UserModel.findById(entry._id, (err, user) => {` on this line in your example it seems like `user` cannot be inferred properly when as well when I pasted the example in the playground

**Comment by IslandRhythms** [comment]
so the problem is that user has type `any` as opposed to what?

**Comment by daniellwdb** [comment]
> so the problem is that user has type `any` as opposed to what?

As opposed to the User type? 😅it could be inferred like it does when using .then

**Comment by vkarpov15** [comment]
As far as I can tell, this looks like a bug in TypeScript: https://github.com/microsoft/TypeScript/issues/31146 . [Mongoose is correctly setting the callback parameter types to `(CallbackError, HydratedDocument<...>)`](https://github.com/Automattic/mongoose/blob/429ce495a300e4571f037bec51a8f01924711a14/index.d.ts#L877), but TS isn't picking it up by default.

As a workaround, do:

```ts
UserModel.findById(entry._id, (err: mongoose.CallbackError, user: User) => {
  /* ... */
});
```
