### ISSUE TITLE
Is it guaranteed that two update requests return distinct results?

### ISSUE THREAD

**Issue by HackyDev** [Automattic/mongoose#10965]
Hey! I'm really sorry I'm asking this here. I've been looking for an answer for days without any luck.
I just need to know what's the expected behavior when two machines update a remote database simultaneously.

**Update method**
```
async function update () {
  const filters = { orderNumber: 1, paid: false }
  const updates = { paid: true }
  const { modifiedCount } = await OrderModel.updateOne(filters, updates)
} 
```
Is it guaranteed that `modifiedCount` will always be 0 for one machine and 1 for another?

**Comment by vkarpov15** [comment]
@HackyDev based on my understanding of MongoDB, the answer is yes. `modifiedCount` will be 1 for one of the updates and 0 for future updates, assuming that there's only one document with a given `orderNumber`. `updateOne()` is atomic.
