### ISSUE TITLE
Assignment in nested object not being saved - regression in 6.0.x

### ISSUE THREAD

**Issue by johnpeb** [Automattic/mongoose#10967]
**Do you want to request a *feature* or report a *bug*?**

Bug - regression from 5.11.13 to 6.0.12

**What is the current behavior?**

This code worked in 5.11.13 and prior. The test breaks in 6.0.12.

**If the current behavior is a bug, please provide the steps to reproduce.**

It's hard to provide a standalone reproduction but here is the gist of the issue:

```
const orders = Order.find(...)
[..]
const order = orders[i]
[..]
const match = order.cumulativeConsumption.find(o => [..])
match.unit = 'foo'
match.value = 123
```
Debugging this in 6.0.12:
```
match.modifiedPaths()
(3) ['materialId', 'value', 'unit']
order.modifiedPaths()
(7) ['timing', 'timing.type', 'changeover', 'plannedStart', 'idle', 'plannedEnd', 'demand']
```
Note that `cumulativeConsumption` is not in `order`'s modified paths which I think is the reason that the update value is not saved

**What is the expected behavior?**

When `order` is saved it should reflect the new value.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

In mongoose 5.11.13 (and prior) the new value is saved. In 6.0.12 (and some previous versions of 6) this test fails. 
MongoDB: v4.2.8
Node: v12.22.7

**Comment by johnpeb** [comment]
Workaround: `order.markModified('cumulativeConsumption')`

**Comment by vkarpov15** [comment]
The below script works as intended, shows that modifying a document array element in place works with `save()`. Please modify the below script to demonstrate your issue.

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
  });

  await mongoose.connection.dropDatabase();

  const Order = mongoose.model('Order', Schema({
    cumulativeConsumption: [{ unit: String, value: Number }]
  }));

  await Order.create({
    cumulativeConsumption: [{ unit: 'foo', value: 123 }, { unit: 'bar', value: 42 }]
  });

  const doc = await Order.findOne();
  const match = doc.cumulativeConsumption.find(o => o.unit === 'bar');
  match.unit = 'baz';
  match.value = 43;
  await doc.save();

  const res = await Order.findById(doc._id);
  /**
    {
      unit: 'baz',
      value: 43,
      _id: new ObjectId("61c22142f1cb979997580278")
    }
  */
  console.log(doc.cumulativeConsumption[1]);
}
```

**Comment by johnpeb** [comment]
@vkarpov15, are there any cases in 6.x where `markModified()` should be needed? I re-tested 6.1.3 and there seem to be fewer failures but still some. To get a simpler repro I may remove all `markModified()` to see if it helps narrow it down.

**Comment by vkarpov15** [comment]
@johnpeb the only place you should still need markModified in 6.x is if you're modifying a path underneath a Mixed path.

**Comment by johnpeb** [comment]
I've not yet been able to reproduce but in testing I found https://github.com/Automattic/mongoose/issues/11172. 

Working around the above bug (saving regardless of isModified) saves correctly in my test case but not in my application so there is something different going on for this issue - I will continue to try to reproduce after some feedback on the above bug.
