### ISSUE TITLE
Upgrade mongoose from 5 to 6 Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new'?

### ISSUE THREAD

**Issue by zbarakzai** [Automattic/mongoose#10960]
version 6.0.12 mongoose

Reporting a bug

getting a type error when calling `mongoose.Types.ObjectId()`

 error **Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new'?**

What is the expected behavior?

should be able to call `mongoose.Types.ObjectId()` without adding `new` keyword.

What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.

version 6.0.12 mongoose
version 14.6.0 node
version 4.1.4 mongodb

the fault lies in any file calling the `mongoose.Types.ObjectId()`

I recently upgraded mongodb from `3.5.4` to `4.1.4` and mongoose from `5.12.10 `to `6.0.12` as I am using `typescript` `4.4.4 `and **ts-node** `10.4.0` in my project I get a type error Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new'? when using this line of code mongoose.Types.ObjectId() I uninstalled and removed the `@types/mongoose` from the project as the new version mongoose has its own type and removed globally also but still I get the same error.

Despite the fact that this issue [#9608](https://github.com/Automattic/mongoose/issues/9608) was tagged as a bug and later tagged as resolved, I continue to receive this error.

**Comment by root-io** [comment]
Can you try this:

```javascript
import { Schema } from "mongoose";

foo: { type: Schema.Types.ObjectId }
```

**Comment by zbarakzai** [comment]
I don't need it as a type I need it in cases like this  `_id: variant._id ? variant._id : mongoose.Types.ObjectId(),`

**Comment by IslandRhythms** [comment]
possible that this https://mongoosejs.com/docs/migrating_to_6.html#objectid-valueof caused it but can you not just add the new keyword?

**Comment by zbarakzai** [comment]
@IslandRhythms if I don't add the `new` Keyword `Typescript` complains about the above error I mentioned.
