### ISSUE TITLE
[request]  prototype.merge() for query the document

### ISSUE THREAD

**Issue by mean-cj** [Automattic/mongoose#10966]
Hello dev team.

i recommend add prototype.merge() for query the document is better
when will need to merge multiple object to  document.

**current use**
```
let account = await account.findOne({ _id: "618a44527d72e9e4578ba0d9" });
account.overwrite({ ...account.toObject(), name: "Jean-Luc Picard" });
await account.save()
```

it's easy
```
let account = await account.findOne({ _id: "618a44527d72e9e4578ba0d9" });
account.merge({ name: "Jean-Luc Picard" });
await account.save()
```

thank you.

**Comment by vkarpov15** [comment]
You can do:

```javascript
let account = await account.findOne({ _id: "618a44527d72e9e4578ba0d9" });
account.findOne({ name: "Jean-Luc Picard" });
await account.save()
```

However, we'll add this feature in our next minor release. It is tricky to do this in middleware without changing the query op.

**Comment by vkarpov15** [comment]
I took a closer look at this issue and it isn't what I thought.

As far as I can tell, the existing `Document#set()` function does what you expect. Try out the below code:

```javascript
let account = await account.findOne({ _id: "618a44527d72e9e4578ba0d9" });
account.set({ name: "Jean-Luc Picard" });
await account.save()
```
