### ISSUE TITLE
MongooseError: Cannot populate path `User` because it is not in your schema. Set the `strictPopulate` option to false to override.

### ISSUE THREAD

**Issue by efcjunior** [Automattic/mongoose#10976]
I can't do a simple query after migrate mogoose from 5 to 6. I didn't find any solution how could I fix it.

```javascript  
Schema = mongooseService.getMongoose().Schema;

    userSchema = new this.Schema({
        _id: String,
        email: String,
        password: { type: String, select: false },
        firstName: String,
        lastName: String,
        permissionFlags: Number,
    }, { id: false });

    User = mongooseService.getMongoose().model('Users', this.userSchema);

    
    async getUserById(userId: string) {
        return this.User.findOne({ _id: userId }).populate('User').exec();
    }
```

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/api.html#model_Model.populate

Here are changes from migrating to 5 to 6 dealing with populate. Please ensure you are not experiencing this.

**Comment by vkarpov15** [comment]
@efcjunior what do you expect `populate('User')` to do? `User` isn't a path in your schema, so there's nothing to `populate()`.

**Comment by efcjunior** [comment]
It worked on @5 version. However it stopped working after migration. Sorry,
but I couldn't understand the documentation.

**Comment by mradulgupta** [comment]
remove .populate('User') and simply return
```
return this.User.findOne({ _id: userId }).populate('User').exec();
```

**Comment by Innei** [comment]
Hi, gays. strict populate is enable default, but how to disable it, I set `strictPopulate: false`, but not work.

```ts
model.findOne({}, undefined, { populate: {path: 'fooo', options: {strictPopulate: false}}, option: {strictPopulate: false}, })
```

**Comment by vkarpov15** [comment]
@Innei can you please open a new issue and follow the issue template?
