### ISSUE TITLE
Deeply nested objects do not convert correctly

### ISSUE THREAD

**Issue by lkrubner** [Automattic/mongoose#10973]
"mongoose": "^6.0.12"

node v12.14.1

npm 6.13.4

Expected behavior: either object converts or `{ "strict" : throw }` will throw an error. But I get neither.

Importing a 3rd party XML API and converting it to JSON leaves me with deeply nested objects. The first 3 levels of nesting seem to work correctly, but beyond, things fail. 

Using console log I see this structure: 

	
	console.log(cartons);
	[
	    {
		SSCC18: [ '' ],
		TrackingNumber: [ '802529927200039547' ],
		CartonContentsQty: [ '2' ],
		CartonWeight: [ '0.400' ],
		LineItems: [ [Object] ]
	    }
	]

	console.log(cartons[0].LineItems);
	[ { LineItem: [ [Object], [Object] ] } ]
	

	console.log(cartons[0].LineItems[0].LineItem);
	[
	    {
		LineNumber: [ '1' ],
		ItemNumber: [ '0112_001_SRC' ],
		UPC: [ '196016012318' ],
		QTYOrdered: [ '1' ],
		QTYShipped: [ '1' ],
		QTYUOM: [ 'EA' ],
		Description: [ '' ],
		Style: [ '' ],
		Size: [ '' ],
		Color: [ '' ],
		RetailerItemNumber: [ '' ]
	    },
	    {
		LineNumber: [ '2' ],
		ItemNumber: [ '0111_049_ODF-157744' ],
		UPC: [ '6016004207-157744' ],
		QTYOrdered: [ '1' ],
		QTYShipped: [ '1' ],
		QTYUOM: [ 'EA' ],
		Description: [ '' ],
		Style: [ '' ],
		Size: [ '' ],
		Color: [ '' ],
		RetailerItemNumber: [ '' ]
	    }
	]

When saving to MongoDB, the top layers work correctly, but at the final layer I get `[Object]` : 

    cartons: [
      {
        SSCC18: [ '' ],
        TrackingNumber: [ '802529927200039547' ],
        CartonContentsQty: [ '2' ],
        CartonWeight: [ '0.400' ],
        LineItems: [
          {
            LineItem: [ [Object], [Object] ],
            _id: ObjectId("618ef7ff93f5d720519dcb1a")
          }
        ],
        _id: ObjectId("618ef7ff93f5d720519dcb19")
      }
    ],

This is the line that is the problem:

      LineItem: [ [Object], [Object] ],
       
And yet, I think this schema should be correct: 

    const LineItemSchema = mongoose.Schema({
        LineNumber: [String], 
        ItemNumber: [String], 
        UPC: [String], 
        QTYOrdered: [String], 
        QTYShipped: [String], 
        QTYUOM: [String], 
        Description: [String], 
        Style: [String], 
        Size: [String], 
        Color: [String], 
        RetailerItemNumber: [String],
    }, { strict: "throw" });
    
    const LineItemsSchema = mongoose.Schema({
        LineItem: [LineItemSchema]
    }, { strict: "throw" });
    
    const CartonSchema = mongoose.Schema({
        SSCC18: [String], 
        TrackingNumber: [String], 
        CartonContentsQty: [String], 
        CartonWeight: [String], 
        LineItems: [LineItemsSchema]
    }, { strict: "throw" });
    
    
Also, I was hoping that using this:

    { strict: "throw" }

would at least give me an error message. But no. The objects fail to convert, and no error is thrown. Is there anything I can do to provoke the system to give me more information about what the real problem is? If I remove any field (for instance, if I remove `CartonWeight`) then Mongoose does throw an error, as I expected. But with all the fields in their correct place, no error is thrown, yet the object fails to convert.

**Comment by IslandRhythms** [comment]
Have you tried doing `console.log(cartons[0].LineItems[0].LineItem[0]);` etc. to ensure that the correct data is there?

**Comment by lkrubner** [comment]
You can see the output of `console.log(cartons[0].LineItems[0].LineItem)` up above. 

But yes, I've also gone deeper into the array. 

@IslandRhythms

**Comment by IslandRhythms** [comment]
So the problem is not that there is missing data but rather that it is instead being displayed as Object object? Correct?

**Comment by lkrubner** [comment]
@IslandRhythms That's half the issue. The other issue is that if there is any kind of problem, then clearly `{ "strict" : throw }` should throw, with a clear, verbose message about what the problem is.

But in the short term, I'd be happy if the data simply converted correctly, rather than rendering as Object.

**Comment by IslandRhythms** [comment]
So you believe that it should throw an error message because it is displaying `Object object` instead of  the data as well?

**Comment by lkrubner** [comment]
@IslandRhythms -- What is Mongoose for? It is to convert the data based on a schema, yes? If for some reason that doesn't work correctly, then there should be some error message, yes? That is what I assume is the expected behavior.

**Comment by IslandRhythms** [comment]
All the data is there so I genuinely do not understand what the problem is. 

```javascript
const mongoose = require('mongoose');

const LineItemSchema = mongoose.Schema({
    LineNumber: [String], 
    ItemNumber: [String], 
    UPC: [String], 
    QTYOrdered: [String], 
    QTYShipped: [String], 
    QTYUOM: [String], 
    Description: [String], 
    Style: [String], 
    Size: [String], 
    Color: [String], 
    RetailerItemNumber: [String],
}, { strict: "throw" });

const LineItemsSchema = mongoose.Schema({
    LineItem: [LineItemSchema]
}, { strict: "throw" });

const CartonSchema = mongoose.Schema({
    SSCC18: [String], 
    TrackingNumber: [String], 
    CartonContentsQty: [String], 
    CartonWeight: [String], 
    LineItems: [LineItemsSchema]
}, { strict: "throw" });

const Test = mongoose.model('Test', CartonSchema)

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();

    const entry = await Test.create({
        LineItems: [{LineItem: [{LineNumber: ['1'], ItemNumber: ['2']}]}]
    });
    const item = await Test.find();
    console.log(item);
    console.log(item[0].LineItems[0])
    console.log(item[0].LineItems[0].LineItem[0])
}

run();
```

**Comment by lkrubner** [comment]
@IslandRhythms 

Sorry, I didn't realize you were looking for sample data. I think you are missing one level of nesting? Please try with this:

    {
    shipment_header: {
	ShipmentID: [ '305491237' ],
	OrderChannel: [ '' ],
	CustomerNumber: [ '' ],
	VendorID: [ '' ],
	ShipViaCode: [ 'UPSMI' ],
	AsnDate: [ '2021-10-08' ],
	AsnTime: [ '15:48:20-08:00' ],
	ShipmentDate: [ '2021-09-30' ],
	ShipmentTime: [ '00:00:00-08:00' ],
	MBOL: [ '' ],
	BOL: [ '' ],
	ShippingNumber: [ '802529927300041596' ],
	LoadID: [ '' ],
	ShipmentWeight: [ '0.1' ],
	ShipmentCost: [ '0' ],
	CartonsTotal: [ '1' ],
	CartonPackagingCode: [ 'CTN25' ],
	OrdersTotal: [ '1' ]
    },
    addresses: [
	{
            AddressLocationQualifier: [ 'ST' ],
            LocationNumber: [ '' ],
            Name: [ 'Debbie' ],
            Address1: [ '' ],
            Address2: [ '' ],
            City: [ 'Raleigh' ],
            State: [ 'NC ' ],
            Zip: [ '27614-8149' ],
            Country: [ 'USA' ]
	},
	{
            AddressLocationQualifier: [ 'BT' ],
            LocationNumber: [ '' ],
            Name: [ 'Debbie' ],
            Address1: [ '11820' ],
            Address2: [ '' ],
            City: [ 'Raleigh' ],
            State: [ 'NC ' ],
            Zip: [ '27614-8149' ],
            Country: [ 'USA' ]
	}
    ],
    order_header: {
	PurchaseOrderNumber: [ '4068321263812' ],
	RetailerPurchaseOrderNumber: [ '' ],
	RetailerOrderNumber: [ '157782' ],
	CustomerOrderNumber: [ '157782' ],
	Department: [ '' ],
	Division: [ '' ],
	OrderWeight: [ '0.1' ],
	CartonsTotal: [ '1' ],
	QTYOrdered: [ '2' ],
	QTYShipped: [ '2' ]
    },
    cartons: [
	{
            SSCC18: [ '' ],
            TrackingNumber: [ '802529927300041596' ],
            CartonContentsQty: [ '2' ],
            CartonWeight: [ '0.100' ],
            LineItems: [
		{
		    LineItem: [
			{
			    LineNumber: [ '1' ],
			    ItemNumber: [ '0124_S16_ODC' ],
			    UPC: [ '196016051508' ],
			    QTYOrdered: [ '1' ],
			    QTYShipped: [ '1' ],
			    QTYUOM: [ 'EA' ],
			    Description: [ '' ],
			    Style: [ '' ],
			    Size: [ '' ],
			    Color: [ '' ],
			    RetailerItemNumber: [ '' ]
			},
			{
			    LineNumber: [ '2' ],
			    ItemNumber: [ '0124_TB16_ODC' ],
			    UPC: [ '196016056732' ],
			    QTYOrdered: [ '1' ],
			    QTYShipped: [ '1' ],
			    QTYUOM: [ 'EA' ],
			    Description: [ '' ],
			    Style: [ '' ],
			    Size: [ '' ],
			    Color: [ '' ],
			    RetailerItemNumber: [ '' ]
			}
		    ]
		}
            ]
	}
    ]
    }

**Comment by IslandRhythms** [comment]
No missing data on my end

```javascript
const mongoose = require('mongoose');

const LineItemSchema = mongoose.Schema({
    LineNumber: [String], 
    ItemNumber: [String], 
    UPC: [String], 
    QTYOrdered: [String], 
    QTYShipped: [String], 
    QTYUOM: [String], 
    Description: [String], 
    Style: [String], 
    Size: [String], 
    Color: [String], 
    RetailerItemNumber: [String],
}, { strict: "throw" });

const LineItemsSchema = mongoose.Schema({
    LineItem: [LineItemSchema]
}, { strict: "throw" });

const CartonSchema = mongoose.Schema({
    SSCC18: [String], 
    TrackingNumber: [String], 
    CartonContentsQty: [String], 
    CartonWeight: [String], 
    LineItems: [LineItemsSchema]
}, { strict: "throw" });

const testSchema = new mongoose.Schema({
    cartons: [CartonSchema]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();

    const entry = await Test.create({
        cartons: [{TrackingNumber: ['12345'], LineItems:[{LineItem: [{LineNumber: ['1'], ItemNumber: ['2']}]}]}]
    });
    
    const item = await Test.findOne();
    console.log('top level', item)
    console.log('cartons', item.cartons[0])
    console.log('Line Items', item.cartons[0].LineItems[0])
    console.log('Line Item', item.cartons[0].LineItems[0].LineItem[0]);
}

run();
```

Output:
```
top level {
  _id: new ObjectId("61a50acb933a218a6726b475"),
  cartons: [
    {
      SSCC18: [],
      TrackingNumber: [Array],
      CartonContentsQty: [],
      CartonWeight: [],
      LineItems: [Array],
      _id: new ObjectId("61a50acb933a218a6726b476")
    }
  ],
  __v: 0
}
cartons {
  SSCC18: [],
  TrackingNumber: [ '12345' ],
  CartonContentsQty: [],
  CartonWeight: [],
  LineItems: [
    {
      LineItem: [Array],
      _id: new ObjectId("61a50acb933a218a6726b477")
    }
  ],
  _id: new ObjectId("61a50acb933a218a6726b476")
}
Line Items {
  LineItem: [
    {
      LineNumber: [Array],
      ItemNumber: [Array],
      UPC: [],
      QTYOrdered: [],
      QTYShipped: [],
      QTYUOM: [],
      Description: [],
      Style: [],
      Size: [],
      Color: [],
      RetailerItemNumber: [],
      _id: new ObjectId("61a50acb933a218a6726b478")
    }
  ],
  _id: new ObjectId("61a50acb933a218a6726b477")
}
Line Item {
  LineNumber: [ '1' ],
  ItemNumber: [ '2' ],
  UPC: [],
  QTYOrdered: [],
  QTYShipped: [],
  QTYUOM: [],
  Description: [],
  Style: [],
  Size: [],
  Color: [],
  RetailerItemNumber: [],
  _id: new ObjectId("61a50acb933a218a6726b478")
}
```
