### ISSUE TITLE
Mongoose model methods stop working when converting values to a String in new Model objects.

### ISSUE THREAD

**Issue by mrhotmadm** [Automattic/mongoose#10975]
*Using Express.JS*

**Do you want to request a *feature* or report a *bug*?**
Bug (that I have resolved and would like to report).

**What is the current behavior?**
When using built-in string conversion functions like `String()` and `toString` when creating new documents/models produce mongoose bug, which makes the `Model.deleteOne` method fail to delete **those specific models.**

I am using the latest version of `mongoose` as of 11/15/2021 (v6.0.13). 

**What have you tried?**
I have tried to reinstall mongoose and mongodb with `npm` and even manually.
Heck, I even recreated my database and my NPM files.

**If the current behavior is a bug, please provide the steps to reproduce.**
**BUG Code (does not matter where it is: callback, async/sync function, ES6 func, etc.)**
```js
// please make sure to create a model before doing this.
await User.deleteOne({
        username: {
            roblox: {
                id: toString('test') // can be a number, string, boolean, or variable, both produced same bug regardless.
            } 
        }
});
```

**Model Code**
```js
const mongoose = require('mongoose');

const user = new mongoose.Schema({
    username: {
	type: Object,
	required: true,
        roblox: {
	    type: Object,
            required: true,
            id: String
        },
       discord: {
            type: Object,
            required: false,
            id: String
        }
    }
});

module.exports = mongoose.model('user', user);
```

**What is the expected behavior?**
Code above should work with no errors, just as you would casually create and delete a model.

**The FIXED code**
After a day of debugging, I tried removing the `String()` and `toString()` function when creating new models, this (surprisingly) resolved the issue.

```js
await User.deleteOne({
        username: {
            roblox: {
                id: 'test'
            } 
        }
});
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
**Node.JS** - "v16.7.0"
**Mongoose** - "6.0.13"
**MongoDB** - "4.1.4"

I am completely confused why, and how this happens. I apologize if this bug has been posted, it's in the docs, or any other reason I missed.

**Comment by IslandRhythms** [comment]
I couldn't get it to delete the document with your proposed work around. However, it did not delete the document on the problem version. I think this may be more of a formatting issue than anything. The deleteOne as per the documentation expects a key value pair and it seems like you are giving it a very long key or conversly a very long value.
`{username: { roblox: { id: 'test' } } }`

To elaborate it could be reading it as key username, val roblox ...  for example.

```javascript
const mongoose = require('mongoose');

const user = new mongoose.Schema({
    username: {
	type: Object,
	required: true,
        roblox: {
	    type: Object,
            required: true,
            id: String
        },
       discord: {
            type: Object,
            required: false,
            id: String
        }
    }
});

const User =  mongoose.model('user', user);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const entry = await User.create({
        username: {roblox: {id: 'Hello'}, discord: {id: 'World'}}
    });
    console.log(await User.find());
    await User.deleteOne({"username.roblox.id": 'Hello'});
    console.log(await User.find())
}

run();
```

**Comment by vkarpov15** [comment]
There's a lot of bad bugs in your code. First, your schema definition is very wrong. The below schema defines `username` as an arbitrary object, with no casting for `username.roblox` or anything else.

```javascript
const user = new mongoose.Schema({
    username: {
	type: Object,
	required: true,
        roblox: {
	    type: Object,
            required: true,
            id: String
        },
       discord: {
            type: Object,
            required: false,
            id: String
        }
    }
});
```

Do this instead:

```javascript
const user = new mongoose.Schema({
    username: {
	type: new mongoose.Schema({
          roblox: { type: new mongoose.Schema({ id: String }), required: true },
          discord: { type: new mongoose.Schema({ id: String }), required: false }
        }),
        required: true 
    }
});
```

Second, your delete syntax is wrong. `User.deleteOne({ username: { roblox: { id: 'foo' } } })` will only delete objects whose `username` property is deep equal to `{ roblox: { id: 'foo' } }`, you want `User.deleteOne({ 'username.roblox.id': 'foo' })`
