### ISSUE TITLE
Mongoose `findById` method not properly casting to `id` strings to `ObjectId`

### ISSUE THREAD

**Issue by mnys176** [Automattic/mongoose#10977]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The following code should successfully fetch a user document from the database and store the results in `data`:

```
const fetchById = async id => {
    try {
        const data = await User.findById(id)
        [...]
    } catch (err) {
        // no error is thrown
        throw err
        [...]
    }
}
```

`data` resolves to `null`, when the user does in fact exist. Running `db.users.findOne({ _id: "<id-string>" })` in the mongo shell returns the proper user document.

Using the `findOne({ _id: '<id-string>' })` yields the same `null` result.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above for reproduction. It should also be noted that accessing the native NodeJS driver through mongoose works as it should:

```
const fetchById = async id => {
    try {
        // const data = await Recipe.findById(id)
        const data = await mongoose.connection.db.collection('recipes').findOne({ _id: id })
        [...]
    } catch (err) {
        [...]
    }
}
```

**What is the expected behavior?**

Given the snippet above, `data` should contain the user document.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: 17.0.1
Mongoose: 6.0.13
MongoDB: 5.0.4 (Docker Image ID: 6c5e5224a222)

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema({ name: 'string', size: 'string' });
const Tank = mongoose.model('Tank', schema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const entry = await Tank.create({ name: 'Thomas'});
    console.log(await Tank.findById({_id: entry._id}));
}

run();
```

**Comment by mnys176** [comment]
Predefined IDs were loaded into collection as strings, not as an `ObjectId`. This issue can be closed! :)

Was loaded into collection from JSON file as...

```
[
    {
        "_id": "<id-string>",
        [....]
    },
    [...]
]
```

Changed to...

```
[
    {
        "_id": {
            "$oid": "<id-string>"
        },
        [...]
    },
    [...]
]
```
