### ISSUE TITLE
Upgrade to mongodb 4.2.0 to fix breaking changes for Electron v14+

### ISSUE THREAD

**Issue by has-n** [Automattic/mongoose#10985]
An upstream dependency in the mongodb driver (specifically in [whatwg-url](https://github.com/jsdom/whatwg-url/issues/211)) caused it to break for Electron v14+.

I logged an issue and this has been fixed in the new 4.2.0 driver. 

Mongoose needs to be updated to the new version of the driver to support Electron 14+.

**Comment by vkarpov15** [comment]
We'll upgrade to 4.2.0 with our 6.1.0 release, should be out in the next several days.

**Comment by lorand-horvath** [comment]
The actual PR that updates the driver to 4.2.0 is https://github.com/Automattic/mongoose/pull/10990
