### ISSUE TITLE
custom location of versionKey

### ISSUE THREAD

**Issue by pate313373** [Automattic/mongoose#10980]
**Do you want to request a *feature* or report a *bug*?**
Not sure, I think it's a feature request.

**What is the current behavior?**
Consider the following schema option:
```
const baseSchemaOptionsJson = {
    optimisticConcurrency: true,
    versionKey: 'meta.documentVersion',
    timestamps: {
        createdAt: 'meta.createdAt',
        updatedAt: 'meta.updatedAt',
    },
};
```
The timestamps are moved to the meta property, but the versionKey is not.
So the version key is in {..., 'meta.documentVersion'}.

**What is the expected behavior?**
Expecting to find the version key in {..., meta:{documentVersion:4, ...}, ...}

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 16.18.0
mongoose 6.0.12
mongodb 4.4.10

**Comment by vkarpov15** [comment]
This is a good idea, we will work on this for a future release.

**Comment by vkarpov15** [comment]
We took a closer look at this and it seems to work as expected. The below script shows an example of `discriminatorKey` embedded in a nested property `meta`. Can you please modify the below script to demonstrate the issue you're seeing?

```javascript
'use strict';
  
const assert = require('assert');
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  await mongoose.connection.dropDatabase();

  const mongooseSchema = new mongoose.Schema({
    name: String,
    meta: { 
      test: String
    }
  }, { discriminatorKey: 'meta.discriminatorKey' });
  const Model = mongoose.model('Test', mongooseSchema);

  const D = Model.discriminator('D', Schema({ test: String }), 'D');

  const doc = new D({ name: 'test', test: 'test' });
  assert.equal(doc.meta.discriminatorKey, 'D');
  await doc.save();

  // Prints object with "meta: { discriminatorKey: 'D' }"
  console.log(await Model.findOne());
}
```

**Comment by vkarpov15** [comment]
@pate313373 thanks for pointing that out, and my apologies for my mistake.

**Comment by pate313373** [comment]
Cool, thank you so much! 👍
