### ISSUE TITLE
Mongoose 5 to 6: Virtual populate lean does not return empty array on empty match

### ISSUE THREAD

**Issue by heyyyce** [Automattic/mongoose#10992]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm migrating mongoose from 5 to 6 and upon testing I got this issue:
When I do find() with populate() on a virtual populate and lean()
I get a return undefined from campaignConsumeMonthlyMulti (code below)

**If the current behavior is a bug, please provide the steps to reproduce.**

Here my virtual in schema
```
CampaignSchema.virtual('campaignConsumeMonthlyMulti', {
ref: 'campaigns_consume',
    localField: '_id',
    foreignField: 'campaignsId',
    justOne: false
});
```

Here the query

```
let campaign = await Campaign.findOne({ companyId: companyId })
.populate(
    {
        path: "campaignConsumeMonthlyMulti",
        match: {
            periodCount: { $gt: datePeriod },
            type: campaignConsumeTypeEnum.monthly.value
        }
    })
.lean();

campaign.campaignConsumeMonthlyMulti == undefined
```
If the match matches data it works like a charm.

**What is the expected behavior?**
It should return an empty array like in mongoose 5.12.11

When I remove the lean() call : campaign.campaignConsumeMonthlyMulti getter give me the empty array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJs: 16.11.0
Mongoose: 6.0.13
MongoDB: 4.2.17

**Comment by vkarpov15** [comment]
This is by design. `lean()` should not set virtuals, you can use the [mongoose-lean-virtuals plugin](https://www.npmjs.com/package/mongoose-lean-virtuals) to get this behavior though.

We'll add a note to the changelog about this.

**Comment by heyyyce** [comment]
Hello

> This is by design. `lean()` should not set virtuals, you can use the [mongoose-lean-virtuals plugin](https://www.npmjs.com/package/mongoose-lean-virtuals) to get this behavior though.

lean() don't set virtuals() as getters() and defaults()

But here I'm using some Virtual populate : 
https://mongoosejs.com/docs/populate.html#populate-virtuals

And according to the docs : 
Virtual populate also works with lean.
https://mongoosejs.com/docs/tutorials/lean.html#lean-and-populate

Regards

**Comment by IslandRhythms** [comment]
> Remember that virtuals do not end up in lean() query results. Use the mongoose-lean-virtuals plugin to add virtuals to your lean query results.

https://mongoosejs.com/docs/tutorials/lean.html#plugins

**Comment by heyyyce** [comment]
Hello

> This is by design. `lean()` should not set virtuals, you can use the [mongoose-lean-virtuals plugin](https://www.npmjs.com/package/mongoose-lean-virtuals) to get this behavior though.

lean() don't set virtuals() as getters() and defaults()

But here I'm using some Virtual populate : 
https://mongoosejs.com/docs/populate.html#populate-virtuals

And according to the docs : 
Virtual populate also works with lean.
https://mongoosejs.com/docs/tutorials/lean.html#lean-and-populate

Regards

**Comment by heyyyce** [comment]
Thanks you for the fix!
