### ISSUE TITLE
mogoose transaction is not working with MongoDB

### ISSUE THREAD

**Issue by ats1999** [Automattic/mongoose#10994]
## Code

```js
router.get("/", async (req, res) => {
  const sesion = await mongoose.startSession();

  try {
    sesion.startTransaction();
    const blog = new Blog({ title: "blog title" });
    const byte = new Dsabytes({ topStory: "Not an ObjectId" });
    await blog.save();
    await byte.save(); // throw an error, because topStory should be an ObjectId

    await sesion.commitTransaction();
    sesion.endSession();
    res.send("OK");
  } catch (e) {
    console.log(e);
    await sesion.abortTransaction();
    sesion.endSession();
    res.status(500).send(e.toString());
  }
});
```
In the Dsabytes schema,I have defined `topStory` to be an `ObjectId`. When I run the above code with `topStory:"6167213f5003f3d062dd833f"` then it's working fine. 

But, when `await byte.save()` throws an error then ideally `sesion.abortTransaction()` should remove the update caused by `blog.save()`. 

### Blogs
```js
[]
```

### Dsabytes
```js
[]
```

### Blogs
```js
[
{
  title:"blog title"
}
]
```
### Dsabytes
```js
[]
```

So, when it throws an error then both collections should be empty at the end?

**Comment by vkarpov15** [comment]
You aren't actually using the session. Do:

```javascript
    sesion.startTransaction();
    const blog = new Blog({ title: "blog title" });
    const byte = new Dsabytes({ topStory: "Not an ObjectId" });
    await blog.save({ session: sesion });
    await byte.save({ session: sesion }); // throw an error, because topStory should be an ObjectId

    await sesion.commitTransaction();
    sesion.endSession();
```

**Comment by ats1999** [comment]
Gettig 

MongoServerError: Transaction numbers are only allowed on a replica set member or mongos

**Comment by vkarpov15** [comment]
@ats1999 the MongoDB server doesn't support transactions on standalone mongod instances. You need to run a replica set. Try using Atlas or [run-rs](https://www.npmjs.com/package/run-rs)
