### ISSUE TITLE
Document `DocumentArray.prototype.create()`

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#10998]
**Do you want to request a *feature* or report a *bug*?**
docs

**What is the current behavior?**
Guide https://mongoosejs.com/docs/subdocs.html at https://mongoosejs.com/docs/subdocs.html#finding-a-subdocument has a `create` that is a link, which points to a non-existing header https://mongoosejs.com/docs/api.html#types_documentarray_MongooseDocumentArray.create

**Comment by khairnarsaurabh23** [comment]
@hasezoey  can describe me what's the expected behaviour from this link ?
I want to work on this issue.

**Comment by hasezoey** [comment]
> can describe me what's the expected behaviour from this link ?

the href should link to a valid url and valid id (in this case the id is invalid `#types_documentarray_MongooseDocumentArray.create`)

**Comment by vkarpov15** [comment]
I just removed the link for now. Our API docs don't currently have a description of the document array `create()` method, we'll add that in a future release.
