### ISSUE TITLE
Custom validation error type

### ISSUE THREAD

**Issue by tamis-laan** [Automattic/mongoose#11004]
When mongoose throws an error due to failed validation it's of type MongoError. However I would like add a piece of middleware that converts this MongoError into a HttpException where I filter out any sensitive information like stack traces and use a status code in the 400 range. 

I want to do this on a global level and not for each schema.

How can this be done using mongoose?

**Comment by vkarpov15** [comment]
Global [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware).

Pseudocode:

```javascript
schema.post('save', function(error, doc, next) {
  if (error.name === 'MongoServerError') {
    next(new HttpException('HTTP 500: ' + error.message));
  } else {
    next();
  }
});
```

**Comment by tamis-laan** [comment]
> Global [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware).
> 
> Pseudocode:
> 
> ```js
> schema.post('save', function(error, doc, next) {
>   if (error.name === 'MongoServerError') {
>     next(new HttpException('HTTP 500: ' + error.message));
>   } else {
>     next();
>   }
> });
> ```

But this is not global right, every schema will need this middleware.

**Comment by Kamikadze4GAME** [comment]
Hello @tamis-laan 

You could use [mongoose global plugin](https://mongoosejs.com/docs/plugins.html#global)

**Comment by vkarpov15** [comment]
@tamis-laan @Kamikadze4GAME is right, you can always define a global plugin.

```javascript
mongoose.plugin(schema => {
  schema.post('save', function(error, doc, next) {
    if (error.name === 'MongoServerError') {
      next(new HttpException('HTTP 500: ' + error.message));
    } else {
      next();
    }
  });
});
```
