### ISSUE TITLE
mongoose 6.0.13: .save() not updates nested subdocuments

### ISSUE THREAD

**Issue by liorstezki** [Automattic/mongoose#11002]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
schema:
```
const userSchema = {
    firstName: {
        type: String,
        trim: true,
        default: '',
        required: true
    },
    lastName: {
        type: String,
        trim: true,
        default: '',
        required: true
    },
    email: {
        type: String,
        default: ''
    },
    userId: {
        type: String,
        required: true,
        immutable: true
    },
    apiSettings: {
        userAPI: {
            enabled: {
                type: Boolean
            },
            type: {
                type: String
            },
            group: {
                type: String,
                trim: true
            }
        },
    },
};
```

I'm trying to update an existing document (user), for example:
existing document: 
```
{
    firstName: 'test',
    lastName: 'test',
    email: 'test@test.com',
    userId: '123456789',
    apiSettings: {
        userAPI: {
            enabled: true,
            type: 'user',
            group: 'user'
        },
    },
};
```

updated object:
```
{
    firstName: 'test',
    lastName: 'test',
    email: 'test@test.com',
    userId: '123456789',
    apiSettings: {
        userAPI: {
            enabled: true,
            type: 'user',
            group: 'guest'
        },
    },
};
```

Node function: 
```
async function updateUser(userId, details) {
    let user = await User.findOne({userId});
    user = deepExtend(user, details);
    const retult = user.save();
    return result;
}
```

when "details" is the updated object above.
the returned value ("result") looks as expected but the document is not updated in mongo.

when I added user.markModified('apiSettings') before .save() it updated my user as expected in mongo.
*simple field (firstName, lastName, etc.) write to the database perfectly

**What is the expected behavior?**
.save() should update the subdocument without using markModified.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 16.13.0
mongoose 6.0.13
MongoDB 3.6

**Comment by Kamikadze4GAME** [comment]
Hello @liorstezki

Please show the declaration of the function `deepExtend`

**Comment by liorstezki** [comment]
deepExtend package:
https://www.npmjs.com/package/deep-extend

function declaration:
https://github.com/unclechu/node-deep-extend/blob/master/lib/deep-extend.js

**Comment by Kamikadze4GAME** [comment]
Try to use `.set()` ([docs](https://mongoosejs.com/docs/api/document.html#document_Document-set)):

```js
user.set(details);
// or if you strictly need deepExtend
user.set(deepExtend(user.toJSON(), details));
```

The issue is due to `mongoose` does not keep all properties in `user` (but deeper inside object) to track changes and define getter/setter for each field.

**Comment by vkarpov15** [comment]
You're missing an `await` before `user.save()`, `save()` is async
