### ISSUE TITLE
 TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by pvijeh** [Automattic/mongoose#11012]
can we make a better error message than this please?

**Comment by Kamikadze4GAME** [comment]
@pvijeh

Please follow issue template

**Comment by pvijeh** [comment]
this is a pretty legitimate issue, you would be better off just returning the raw error from mongodb which actually does provide some useful detail. 

I don't think id close this one

**Comment by vkarpov15** [comment]
This isn't a legitimate issue. Without a code sample or stack trace, there isn't anything we can do. Please open a new issue and follow the issue template.
