### ISSUE TITLE
Adding production ready error messages

### ISSUE THREAD

**Issue by aleksadjukic** [Automattic/mongoose#11018]
**Do you want to request a *feature* or report a *bug*?**
I would like to propose a new feature to be added to mongoose, where the mongoose validation error objects coming from mongoose schema validation, would have additional property that will give a formatted, production ready message.

**What is the current behavior?**
Currently, the messages coming from mongoose validation error objects is pretty annoying to format, to be fair. With Express, you have to create a global error handling middleware and extend the JavaScript Error class to format these errors.

**What is the expected behavior?**
Let's say that in our User schema we defined a rule for the user's username like this:
`username: {
      type: String,
      required: [true, 'Username is required.']
}`

Instead of having to format the error message manually, it would be awesome if we could just do something like 
`console.log(err.prodErrorMessage)`

And get the exact message that we passed in the brackets, for each validation rule.

I'm not sure if there is already a way to do that somehow, without making a custom error handler, but if that is the case, I haven't come across a solution yet.

**Comment by vkarpov15** [comment]
That's exactly what the syntax you described already does:

```javascript
'use strict';
  
const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    username: { type: String, required: [true, 'Username is required.'] }
  });

  const User = mongoose.model('User', schema);

  await User.create({});
}
```

Prints:

```
Error: User validation failed: username: Username is required.
```

Are you suggesting some alternative output?

**Comment by aleksadjukic** [comment]
Hi, I'll try to clarify what I meant when I opened this issue.

**Validation Errors**

Currently, this is an example error message in the error object, when there is a bunch of validation errors during the creation of a document.

`{"message": "User validation failed: password: You must provide a password., email: You must provide an email., lastName: You must provide your last name., firstName: You must provide your first name."}`

This message, although good for development, could seem weird to the users of our web app.
That's why we have to manually take the error object with all the fields and construct an array of messages.

It would be great if for example, there would be another property on the error object, besides the "message", called "messagesProd" or something, which would be an array of all the errors that happened during validation.

In the above case, the array would look like this.

`{"messagesProd":["You must provide a password", "You must provide an email", "You must provide your last name","You must provide your first name."}`

This way, on the front end, we could just loop through the array and display all or part of the validation errors defined in mongoose schema.

**Cast Errors**

Here's an example of the error message, when a CastError occurs.

`{"message": "Cast to ObjectId failed for value \"61ae8a38b5889200481b8f356\" (type string) at path \"_id\" for model \"User\""}`

Again, this error is valuable for developers, but for the users has no meaning.
So, we could have a production ready message like, "Invalid _id: 61ae8a38b5889200481b8f356." or something.

This one is easier to implement manually than the ValidationError, but I still feel like the developers, especially beginners to Mongoose, could have a much nicer time if they didn't have to go through all this hustle of formatting messages for production.

This is not a huge issue, but in my opinion it would just make mongoose even nicer to work with.
I hope now, you can understand where I'm going with this.

**Comment by vkarpov15** [comment]
Getting an array of validation errors is pretty easy, a ValidationError has an `errors` object whose keys are paths and values are errors. So `Object.values()` should work:

```javascript
'use strict';
  
const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    username: { type: String, required: [true, 'Username is required.'] }
  });

  const User = mongoose.model('User', schema);

  const err = await User.create({}).then(() => null, err => err);
  // [ 'Username is required.' ]
  console.log(Object.values(err.errors).map(e => e.toString()));
}
```

For prettifying unique errors, we recommend [this plugin](https://github.com/matteodelabre/mongoose-beautiful-unique-validation)
