### ISSUE TITLE
Failed save still loses changed paths

### ISSUE THREAD

**Issue by meloncholy** [Automattic/mongoose#1102]
If a document fails to save (e.g. due to a duplicate key), Mongoose still removes any changed paths from the modified paths list, so a subsequent successful save won't write these data to Mongo. Can obviously be remedied by calling `markModified`, but took me a while (as a beginner) to figure this out... Is this by design?

**Comment by lineus** [comment]
I thought it might be worthwhile to go back and revisit some older open issues. This one being the oldest seems like a good place to start, though, it seems to have been solved somewhere along the way already. The following script shows that the modified paths are retained after a failed save and that a subsequent save successfully persists data that was altered before the failed save attemptl. @vkarpov15 can we close this?

### 1102.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '1102';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = {
  family: 4,
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useCreateIndex: true
};

const schema = new Schema({
  name: {
    type: String,
    unique: true
  },
  age: Number
});

const Test = mongoose.model('test', schema);

let one = new Test({ name: 'test1', age: 1 });
let two = new Test({ name: 'test2', age: 2 });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.init();
  const docs = await Test.create([one, two]);
  ([one, two] = docs);
  two.name = 'test1';
  two.age = 3;
  assert.deepEqual(two.modifiedPaths(), ['name', 'age']);
  await two.save().catch((e) => { assert.ok(e instanceof Error);});
  assert.deepEqual(two.modifiedPaths(), ['name', 'age']);
  two.name = 'testTwo';
  await two.save();
  let saved = await Test.findOne({ _id: two._id });
  assert.strictEqual(saved.name, 'testTwo');
  assert.strictEqual(saved.age, 3);
  console.log('All Assertions Pass.');
  await connection.close();
}

run();

```

### Output:
```
issues: ./1102.js 
All Assertions Pass.
issues: 
```

**Comment by vkarpov15** [comment]
@lineus yes we can. Any issue that doesn't have a label or milestone, from 2017 or earlier, and you find you can't repro it, feel free to close it :+1:
