### ISSUE TITLE
Unable to perform multiple params find query using an array.

### ISSUE THREAD

**Issue by silicon-ninja** [Automattic/mongoose#11025]
# This is just a query.. need help. 

### This is my mongo query when I'm trying to pass multiple values as an array in the find query 

![Screenshot 2021-11-30 at 2 31 52 AM](https://user-images.githubusercontent.com/48326585/143942532-08bc7b47-65e5-45b0-9b2c-c26945f05355.png)

### this is the output where it returns this object 

![Screenshot 2021-11-30 at 2 31 09 AM](https://user-images.githubusercontent.com/48326585/143942446-ce02842b-f5e3-4904-bbae-2a7d7de4c64b.png)

**Comment by IslandRhythms** [comment]
Use `await`

**Comment by silicon-ninja** [comment]
@IslandRhythms it worked thank you. my bad simple line of code couldn't get it XD.
