### ISSUE TITLE
Conflict updating a MongooseMap after upgrading mongoose

### ISSUE THREAD

**Issue by jesusvalle** [Automattic/mongoose#11029]
Bug reporting

Greetings,
In a document (sellerDoc) in my database, I have a mongooseMap field like this:
`    "apiOperations": {
        'catalog_report': {
            'spain': {
                'done' : true
            },
            'france': {
                'done' : false
            }
        },
        'stock_report': {
            'spain': {
                'done' : true
            },
            'france': {
                'done' : false
            }
        },
    }`

If I do an operation like the following to modify the "done" field of one of the countries:
sellerDoc.apiObject.get('catalog_report').set('france', {done:  true});
sellerDoc.save();

I receive the following error: 'Error: MongoServerError: "Updating the path 'apiOperations.$*.france' would create a conflict at 'apiOperations.$*.france'"

I used to use mongoose version 5.12.14 and it allowed me to do this operation, but after upgrading to 6.0.13, it does not.

Mongoose: 6.0.13
Node.js: 14.18.1
MongoDB: 4.2.0

Thank you!

**Comment by vkarpov15** [comment]
The below script completes successfully, no errors. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  await mongoose.connection.dropDatabase();

  const Test = mongoose.model('Test', new Schema({
    apiOperations: {
      type: Map,
      of: new Schema({ done: Boolean })
    }
  }));

  const sellerDoc = await Test.create({
    "apiOperations": { 'catalog_report': { 'spain': { 'done' : true }, 'france': { 'done' : false } }, 'stock_report': { 'spain': { 'done' : true }, 'france': { 'done' : false } } }
  });

  sellerDoc.apiOperations.get('catalog_report').set('france', {done: true});
  await sellerDoc.save();

  console.log('Done');
}
```
