### ISSUE TITLE
Cannot use strictQuery: false with countDocuments query

### ISSUE THREAD

**Issue by OoDeLally** [Automattic/mongoose#11037]
**Do you want to request a *feature* or report a *bug*?**

Kinda both

**What is the current behavior?**

`countDocuments` is missing a `QueryOptions` argument.

I need this `QueryOptions` argument to disable `strictQuery` mode on the filter.

`model.filter(fooFilter)` and `model.countDocuments(fooFilter)` should return the same number of documents.
However in the case `fooFilter` contains fields not in mongoose's schema, they will be stripped off, which is a behavior I do not want.
Therefore I'm using `model.filter(fooFilter, { strictQuery: false })`, but there seem to be no way to do `model.countDocuments(fooFilter, { strictQuery: false })`.

**What is the expected behavior?**

`countDocuments` should accept a `QueryOptions` in order to customize behavior the same way as with `find`.

**Workaround**
A solution is to mark the whole schema as `{ strictQuery: false }`, this does impact the `countDocuments` and makes it behave like `find()`.
This makes me believe `countDocuments` _does_ support `strictQuery`, but the `QueryOptions` argument is just missing from the function.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v16.13.0
mongodb@4.1.4
mongoose@6.0.14

**Comment by IslandRhythms** [comment]
The docs never state that `countDocuments()` accepts query options. Marking as new feature as a result.

**Comment by vkarpov15** [comment]
It looks like this is partially a TypeScript issue: `Model.countDocuments()` isn't in the TypeScript type defs. Also, `Query.prototype.countDocuments()` should accept QueryOptions, but doesn't right now.

**Comment by OoDeLally** [comment]
<3
