### ISSUE TITLE
[SUGGESTION] Make `mongoose.syncIndexes()` and `Connection#syncIndexes()` always successfully fulfilled (error independent)

### ISSUE THREAD

**Issue by Kamikadze4GAME** [Automattic/mongoose#11039]
_Originally posted by @Kamikadze4GAME in https://github.com/Automattic/mongoose/pull/10997#discussion_r755016633_

Maybe is it better to return object, where key is `modelName` and value is result (successful) from `this.model(model).syncIndexes()` or if something went wrong instance of the Error (or MongooseError)?

So the result object will look like (it's just an example):

```js
const syncIndexesResult = await connection.syncIndexes();
// `syncIndexesResult`
{
  model1: ['index-1-1', 'index-1-2'], // this is example of the successful result from `Model.syncIndexes`,
  model2: MongooseError, 
  model3: [...],
}
```

As a result, you could control future actions (ex: show in console list of failed models or manually rerun syncIndexes on failed models).

What do you think?

@vkarpov15 @AbdelrahmanHafez @IslandRhythms 

Ref: #10893, #10997

**Comment by vkarpov15** [comment]
I think this is a pretty reasonable idea. We'll consider this for our next minor release.

**Comment by AbdelrahmanHafez** [comment]
I think errors not being thrown is a counter-intuitive behavior, and I would expect `syncIndexes(...)` to throw if some model failed.

I think having an object available with all the results is convenient, but in case an error happened I'd have that result as a property on the error object `error.result` instead of silently passing.

What do you think?

**Comment by AbdelrahmanHafez** [comment]
I don't think OP's behavior is concerned with parallel vs sequential.

I think the desired behavior is to not throw errors. How about `throwOnErrors: false` to opt in?
@vkarpov15

**Comment by vkarpov15** [comment]
I think I'd prefer `ignoreErrors: true`, and default to `false`. More concise naming.

**Comment by AbdelrahmanHafez** [comment]
I find that `ignore` implies hiding them completely, and find that `throwOnErrors` is more descriptive of the behavior.
I agree on defaulting to throw/not ignore.
