### ISSUE TITLE
Intermittent initial connection failures in Cloud Run

### ISSUE THREAD

**Issue by kk2491** [Automattic/mongoose#11036]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
Cloud run instances fail to make initial connection to mongodb atlas

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
All the cloud run instances should be able to connect to mongoDb atlas. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - v12.22.1  
Mongoose - 6.0.14
MongoDb - 5.0.4 

**Description:**  

The cloud run instances fails to establish initial connection with the MongoDb using mongoose.

**Comment by vkarpov15** [comment]
Can you show some code samples and provide a stack trace?
