### ISSUE TITLE
How to define a schema where object keys/paths have to match a pattern?

### ISSUE THREAD

**Issue by chaeron** [Automattic/mongoose#11042]
Did a bunch of searching in the docs and on the web to answer this with no success.

Does Mongoose have a way to define a schema where you can include keys/paths which have to match a pattern (eg. regex)?

I have a use case were I want to store an an object with any number of keys, but where each key/path matches a regex (in my case only want to allow alpha/numberic and underscore in the key) and the value of each key has to be a string with specific formatting (ISO date string in fact)?

Something like this:

```
const subdoc = new Schema({
   /^[A-Za-z0-9_]+$/:    { type: String, match:  /^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z)$/ }
})
```

where the key/path regex is used to validate allowed key values, and each value has to have a specify type.

I can't find a way to do this using an object, only using an array with entries that match a subdoc schema like:

```
const subdoc = new Schema({
   key:    { type: String, match:  /^[A-Za-z0-9_]+$/ },
   value: { type: String, match:  /^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z)$/ }
})
```

Thanks!

**Comment by vkarpov15** [comment]
[Maps](https://mongoosejs.com/docs/schematypes.html#maps)

```javascript
const subdoc = new Schema({
  map: {
    type: Map,
    of: String,
     validate: v => {
      return [...v.keys()].every(key => /^[A-Za-z0-9_]+$/.test(key));
    }
  }
});
```

An alternative approach would be to use an array of key/value objects:

```javascript
const subdoc = new Schema({
  obj: [{
    key: { type: String, match: /^[A-Za-z0-9_]+$/ },
    value: { type: 'Mixed' }
  }]
});
```

**Comment by chaeron** [comment]
Cool....thanks.  My searching didn't show up the map stuff.

I used the alternative approach for now but may convert to using a Map.
