### ISSUE TITLE
MongooseError: Operation guildschemas.findOneAndDelete() buffering timed out after 10000ms

### ISSUE THREAD

**Issue by ziomek64** [Automattic/mongoose#11045]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When starting my discord bot I get Operation guildschemas.findOneAndDelete() buffering timed out after 10000ms, even though I don't have this operation on startup.

**If the current behavior is a bug, please provide the steps to reproduce.**
Well I would I like to show, but I don't use this operation at all at a startup. I use it sometimes, for example when someone remove the bot from their server. 

My connection:

```
const mongoose = require('mongoose');
const chalk = require('chalk');

module.exports = (client) => {
    console.log(chalk.green("Połączono przy użyciu Discord API."))

  mongoose.connect(process.env.MONGODB_SRV, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
      console.log(chalk.green("Połączono z bazą danych MongoDB."))
  })
  .catch((err) => {
    console.log(err);
  })
};
```

**What is the expected behavior?**
Connecting without errors

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 16.13.1
Mongoose - 6.0.14
MongoDB - 4.4.10

**Comment by IslandRhythms** [comment]
Move your connection code to wherever you login with your bot token

**Comment by vkarpov15** [comment]
Try doing `await mongoose.connect()` **before** allowing your bot to accept incoming requests. This may just be a case where your bot starts accepting requests and trying to talk to MongoDB before `mongoose.connect()` is called. Otherwise, without a more complete repro, there's no way for us to guess what the issue might be.

**Comment by kacper299** [comment]
@vkarpov15 
I am somewhat related to this issue. I don't know if it's significant, but first there are errors and then there is information about the database connection. We added `await` before `mongoose.connect()` and nothing happens.

**Comment by vkarpov15** [comment]
@kacper299 please open a new issue and follow the issue template. Your comment isn't very helpful.

**Comment by ziomek64** [comment]
@vkarpov15 He's working with me on the same project. If you need additional info please tell us

**Comment by vkarpov15** [comment]
Can you provide the code where you're calling `findOneAndDelete()` on `GuildSchema`?

**Comment by kacper299** [comment]
@vkarpov15 
It's just that, we don't have anything else. It should only be called when removing a bot from the server.
```client.on("guildDelete", async guild => {
  const guildSchema = require("./models/guildSchema");
  const prefixSchema = require("./models/prefixSchema");
  const profileSchema = require("./models/profileSchema");
  const warnSchema = require("./models/warnSchema");

  await guildSchema.findOneAndDelete(
    {
      guildID: guild.id
    }
  )
  await prefixSchema.findOneAndDelete(
    {
      guildID: guild.id
    }
  )
  await profileSchema.findOneAndDelete(
    {
      guildID: guild.id
    }
  )
  await warnSchema.findOneAndDelete(
    {
      guildID: guild.id
    }
  )
})```

**Comment by IslandRhythms** [comment]
https://www.google.com/search?q=discord.js+connect+to+mongoose&oq=discord.js+connect+to+mongoose&aqs=chrome..69i57j33i22i29i30l9.6010j0j7&sourceid=chrome&ie=UTF-8#kpvalbx=_08e3YZDwKq6TwbkPy5OVyAE38

You need to put your connection string where you login with your bot.

**Comment by kacper299** [comment]
Great, we'll check it out soon.

**Comment by kacper299** [comment]
@IslandRhythms i did what you asked, the error still occurs.
```
client.on("ready", async () => {
  await mongoose.connect(process.env.MONGODB_SRV, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    //useFindAndModify: false
  })
    .then(() => {
      console.log(chalk.green("Połączono z bazą danych MongoDB."))
    })
    .catch((err) => {
      console.log(err);
    })
});
```

**Comment by IslandRhythms** [comment]
That is not where you login with the bot. That is an event handler that triggers after you have logged in with your bot. Move the connection code outside of the event handler.

**Comment by kacper299** [comment]
@IslandRhythms 
In the same file, my bot is launched.

**Comment by IslandRhythms** [comment]
Take it out of the event handler

**Comment by kacper299** [comment]
@IslandRhythms 
I don't know what you mean. It's in the same file as the bot launches. I only put it in `client.on("ready", async () => {` because it has to be in the async function.

**Comment by IslandRhythms** [comment]
Take it out and use .then() instead of await

**Comment by kacper299** [comment]
@IslandRhythms 
Just mongose.content at the beginning of the code? Do you mean it?

**Comment by IslandRhythms** [comment]
```javascript
mongoose.connect().then(() => {})
client.login()
```

**Comment by kacper299** [comment]
It works, thank you.
