### ISSUE TITLE
countDocuments Queries Broken

### ISSUE THREAD

**Issue by aintHuman** [Automattic/mongoose#11049]
I just upgraded from  version **5.13.13** to **6.0.14**.

One query I need to perform, is to count the number of documents in a collection, between a start and finish date.

Previously I was executing the query like this:

```
const documentCount = await Model.countDocuments({
    releaseAfter : {
        $gt     : start.toDate(),
        $lte    : finish.toDate()
    }
}).exec();
```
`start` and `finish` are dates from the moment library (coerced to `Date` type via `start.toDate()` and `finish.toDate()` method respectively). In the model definition, `releaseAfter` is a field of type `Date`.

Now with the old version (**5.13.13**), the count is returned as expected.

However, with the new version (**6.0.14**), the count that is returned is the **TOTAL COUNT** of the entire collection, and the filter is having no effect. No matter what I change these limits to, the same document count is always returned (the total document count), which is entirely incorrect.

Not sure if this is meaningful, but the old version had database connection options which included using the `useUnifiedTopology=true` and `useFindAndModify = false` flags, and these variables are not-permitted in the new version meaning I had to remove them, not sure if omitting these has caused some effect.

Have had to roll back to the previous version until I can understand what is going on. 

Rolling back was able to yield the expected results.

--

I should also say that the particular model (ie `Model`) is the parent model on a series of discriminator based type models, and `releaseAfter` is a field that is unique to some of the discriminator-models, and NOT present in all, certainly not in the parent, so perhaps the new version only performs the filter correctly if it is applied to the specific discriminator model containing the field. Before rolling back, I tried modifying the filter condition with an `$and: [...]` operator to ensure the field exists, like this:

```
const documentCount = await Model.countDocuments({
    $and : [
        { releaseAfter : {$exists : true} },
        { releaseAfter : { $gt : start.toDate(), $lte : finish.toDate() }}
    ]
}).exec();
```

However, this had no effect on the result, and the problematic total document count was still returned.

**Comment by vkarpov15** [comment]
Try setting `strictQuery: false`, `await Model.countDocuments(...).setOptions({ strictQuery: false })`

**Comment by IslandRhythms** [comment]
Filter is working on my end

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String,
    age: Number
}, {timestamps: true});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const startDate = new Date();
    for(let i = 0; i < 20; i++) {
        await Test.create({name: 'Test'+i, age: i});
    }
    const endDate = new Date();
    // console.log(startDate, endDate, await Test.find())

    setTimeout(async function() {
        for(let i = 21; i < 40; i++) {
            await Test.create({name: 'Test'+i, age: i})
        }
        let filtered = await Test.countDocuments({createdAt: {$gt: startDate, $lte: endDate}})// .setOptions({strictQuery: false});
    console.log('total', await Test.countDocuments());
    console.log('filtered', filtered);
    }, 5000)
    



};

run();
```

**Comment by OBrown92** [comment]
We are running in the same issue. I've figured out that it depends on the model, which you count on.

Take this snippet for example.
```js
const mongoose = require('mongoose');

const parentSchema = new mongoose.Schema({
    firstname: String,
    age: Number
}, { versionKey: false, discriminatorKey: 'type' });

const childSchema = new mongoose.Schema({
    lastname: String,
    isAdult: Boolean
}, { versionKey: false, discriminatorKey: 'type' });

const parent = mongoose.model('Parent', parentSchema);
const child = parent.discriminator('Child', childSchema);


async function run() {
    mongoose.set('strictQuery', false)
    await mongoose.connect('mongodb://localhost:27017/discrim');

    await child.create({ firstname: 'Jane', lastname: 'Doe', age: 26, isAdult: true });
    await child.create({ firstname: 'Janine', lastname: 'Foo', age: 36, isAdult: false  });
    await child.create({ firstname: 'Bar', lastname: 'Lorem', age: 46 });

    const result = await parent.find({ isAdult: true });

    console.log(result);
}

run();
```
with `"mongoose": "5.12.12"` you get:
```js
[
  {
    type: 'Child',
    _id: 61cdd741c9dc03ab7fa4f4e2,
    lastname: 'Doe',
    isAdult: true,
    firstname: 'Jane',
    age: 26
  }
]
```
but with "mongoose": "6.1.4" you get:
```js
[
  {
    _id: new ObjectId("61cdd741c9dc03ab7fa4f4e2"),
    lastname: 'Doe',
    isAdult: true,
    firstname: 'Jane',
    age: 26,
    type: 'Child'
  },
  {
    _id: new ObjectId("61cdd741c9dc03ab7fa4f4e4"),
    lastname: 'Foo',
    isAdult: false,
    firstname: 'Janine',
    age: 36,
    type: 'Child'
  },
  {
    _id: new ObjectId("61cdd741c9dc03ab7fa4f4e6"),
    lastname: 'Lorem',
    firstname: 'Bar',
    age: 46,
    type: 'Child'
  }
]
```

If I change the find command to the child model:
```js
const result = await child.find({ isAdult: true });
```
I get the results like in version 5.

Our first try was to set the `strictQuery` parameter to `false` but this won't work cause it's a `discriminator` model. Unfortunately you get the error with the hint to this only if you try to set the `strictQuery` option in the model itself. The error message btw is:
```bash
Error: Can't customize discriminator option strictQuery (can only modify toJSON, toObject, _id, id)
```

So our only question is: Are we doing this the hole time wrong by searching on the parent model? I think yes and we are going to switch to the child model.

Hope this helps.

**Comment by aintHuman** [comment]
"So our only question is: Are we doing this the hole time wrong by searching on the parent model? I think yes and we are going to switch to the child model."

-- yeah, but sometimes it makes no sense to search on the child. For example let's say that the knowledge of WHICH child to use, can only be determined at runtime based on the query result.

**Comment by IslandRhythms** [comment]
I couldn't get the error message to pop up, but it does behave like you say it does.
```javascript

const mongoose = require('mongoose');

const parentSchema = new mongoose.Schema({
    firstname: String,
    age: Number
}, { versionKey: false, discriminatorKey: 'type' });

const childSchema = new mongoose.Schema({
    lastname: String,
    isAdult: Boolean
}, { versionKey: false, discriminatorKey: 'type' });

const parent = mongoose.model('Parent', parentSchema);
const child = parent.discriminator('Child', childSchema);


async function run() {
    mongoose.set('strictQuery', false)
    await mongoose.connect('mongodb://localhost:27017/discrim');
    await mongoose.connection.dropDatabase();
    await child.create({ firstname: 'Jane', lastname: 'Doe', age: 26, isAdult: true });
    await child.create({ firstname: 'Janine', lastname: 'Foo', age: 36, isAdult: false  });
    await child.create({ firstname: 'Bar', lastname: 'Lorem', age: 46 });

    const result = await parent.find({ isAdult: true });
    // const result = await child.find({ isAdult: true });

    console.log(result);
}

run();
```

**Comment by vkarpov15** [comment]
The correct solution is to set `strictQuery` to `false` globally if this behavior is a problem for you. The issue is that, since `isAdult` isn't a property on the parent model, Mongoose 6 strips it from the query by default. However, the below works:

```javascript
const mongoose = require('mongoose');

mongoose.set('strictQuery', false); // <-- set this

const parentSchema = new mongoose.Schema({
    firstname: String,
    age: Number
}, { versionKey: false, discriminatorKey: 'type' });

const childSchema = new mongoose.Schema({
    lastname: String,
    isAdult: Boolean
}, { versionKey: false, discriminatorKey: 'type' });

const parent = mongoose.model('Parent', parentSchema);
const child = parent.discriminator('Child', childSchema);


async function run() {
    mongoose.set('strictQuery', false)
    await mongoose.connect('mongodb://localhost:27017/discrim');
    await mongoose.connection.dropDatabase();
    await child.create({ firstname: 'Jane', lastname: 'Doe', age: 26, isAdult: true });
    await child.create({ firstname: 'Janine', lastname: 'Foo', age: 36, isAdult: false  });
    await child.create({ firstname: 'Bar', lastname: 'Lorem', age: 46 });

    const result = await parent.find({ isAdult: true });
    // const result = await child.find({ isAdult: true });

    console.log(result);
}

run();
```

If you're getting `Error: Can't customize discriminator option strictQuery (can only modify toJSON, toObject, _id, id)`, that means you're setting `strictQuery` on the schema. Which is also fine, but you need to make sure to set `strictQuery` on both the parent model's schema and the discriminator model's schema:

```javascript
const parentSchema = new mongoose.Schema({
    firstname: String,
    age: Number
}, { versionKey: false, discriminatorKey: 'type', strictQuery: true });

const childSchema = new mongoose.Schema({
    lastname: String,
    isAdult: Boolean
}, { versionKey: false, discriminatorKey: 'type', strictQuery: true });

```
