### ISSUE TITLE
FindOneAndUpdate throws dup key error

### ISSUE THREAD

**Issue by DaliborTrampota** [Automattic/mongoose#11046]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Throws an error when updating document

**If the current behavior is a bug, please provide the steps to reproduce.**
MongoError: E11000 duplicate key error collection: myFirstDatabase.cards index: _id_ dup key: { _id: "ilnamSG_2" }
|     at MessageStream.messageHandler (/root/KPOP/node_modules/mongodb/lib/cmap/connection.js:272:20)
|     at MessageStream.emit (node:events:390:28)
|     at processIncomingData (/root/KPOP/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
|     at MessageStream._write (/root/KPOP/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
|     at writeOrBuffer (node:internal/streams/writable:389:12)
|     at _write (node:internal/streams/writable:330:10)
|     at MessageStream.Writable.write (node:internal/streams/writable:334:10)
|     at TLSSocket.ondata (node:internal/streams/readable:754:22)
|     at TLSSocket.emit (node:events:390:28)
|     at addChunk (node:internal/streams/readable:315:12)
|     at readableAddChunk (node:internal/streams/readable:289:9)
|     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
|     at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23) {
|   operationTime: Timestamp { _bsontype: 'Timestamp', low_: 15, high_: 1638728620 },
|   ok: 0,
|   code: 11000,
|   codeName: 'DuplicateKey',
|   keyPattern: { _id: 1 },
|   keyValue: { _id: 'ilnamSG_2' },
|   '$clusterTime': {
|     clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 18, high_: 1638728620 },
|     signature: { hash: [Binary], keyId: [Long] }
|   }
| }

these are the only calls I have in the code to the cards collection (edit: narrowed it down to the not commented one
```js
await cardsModel.findOneAndUpdate({_id: `${card.fileName}_${card.tier}`, group: card.group.toUpperCase(), tier: card.tier }, {}, { upsert: true, new: true, setDefaultsOnInsert: true })

//await bot.db.cards.findOneAndUpdate({_id: `${c.fileName}_${c.tier}`, group: c.group.toUpperCase(), tier: c.tier}, {$set: { [`issues.${c.issue}`]: null }}, { upsert: true, new: true }).exec()

//await bot.db.cards.findOneAndUpdate({_id: `${c.fileName}_${c.tier}`, group: c.group.toUpperCase(), tier: c.tier}, {$unset: { [`issues.${c.issue}`]: "" }}).exec()
```
as you can see there is the entry but im using findOneAndUpdate so if it exists it edits it if it doesnt it creates.
![image](https://user-images.githubusercontent.com/31895316/144763407-70dd866e-e282-46cb-a2ee-ed06eee0f837.png)

**What is the expected behavior?**
update the document

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v16.13.0
mongoose 5.13.13

I'm trying to fix this issue for several weeks already and im desperate so I'm asking here

**Comment by IslandRhythms** [comment]
Could your provide your schema set up?

**Comment by vkarpov15** [comment]
Are `group` and `tier` equal to `'SOLOIST'` and `2` in your query? The most likely explanation for this is that `group` and `tier` are different values, which would make this `findOneAndUpdate()` try to upsert a new document with the same id as another document.

**Comment by DaliborTrampota** [comment]
> Could your provide your schema set up?

```js
const cardSchema = mongoose.Schema({
    _id: String,
    tier: Number,
    group: String,
    issues: { type: Object, default: {} }
});
```

**Comment by DaliborTrampota** [comment]
> Are `group` and `tier` equal to `'SOLOIST'` and `2` in your query? The most likely explanation for this is that `group` and `tier` are different values, which would make this `findOneAndUpdate()` try to upsert a new document with the same id as another document.

thank, you thats most likely it, didnt know that might be the case. Thanks
