### ISSUE TITLE
`Model.hydrate` does not always cast Object ID values correctly

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#11052]
**Do you want to request a *feature* or report a *bug*?**

Bug (and backward breaking - looks like the regression was initially introduced in `5.12.4`)

**What is the current behavior?**

The behaviour of `Model.hydrate` is inconsistent with how it casts `String` values for fields that should be `ObjectId`s.
- If no `ref` schema path option is specified, the hydration works as expected when an ID string is passed in.
- If the `ref` option is set, the hydration fails.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const assert = require('assert')
const mongoose = require('mongoose')
const { Schema } = mongoose

it('Calling `Model.hydrate` does not always cast Object ID values correctly', async () => {
   const bookSchema = new Schema({
      // Removing the `ref: 'author'` option causes the test to pass successfully
      author: { type: mongoose.Types.ObjectId, required: true, ref: 'author' }
   })

   const Book = mongoose.model('book', bookSchema)

   const book = Book.hydrate({
      author: '513bb18e268bb25016131ca6'
   })

   assert(book.author instanceof mongoose.Types.ObjectId)
})
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node.js: 14.17.6
mongoose: 6.0.14
MongoDB: 4.4.6

**Comment by IslandRhythms** [comment]
I'm confused by your usage of `ref`

https://mongoosejs.com/docs/api.html#schematype_SchemaType-ref

It does not cause a problem for me when I do the following:

```javascript

const assert = require('assert')
const mongoose = require('mongoose')
const { Schema } = mongoose

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const authorSchema = new Schema({
        name: String
    });
   const bookSchema = new Schema({
      // Removing the `ref: 'author'` option causes the test to pass successfully
      author: { type: mongoose.Types.ObjectId, required: true, ref: 'author' }
   })

   const Book = mongoose.model('book', bookSchema);
   const Author = mongoose.model('author',  authorSchema);
  const entry = await Author.create({
       name: 'John'
   })

   const book = Book.hydrate({
      author: entry._id
   })

   assert(book.author instanceof mongoose.Types.ObjectId)
   console.log('done')
};

run();
```

**Comment by asabhaney** [comment]
In your example, if you change

```js
const book = Book.hydrate({ author: entry._id })
``` 

to 

```js
const book = Book.hydrate({ author: entry.id }) // (id instead of _id)
```

then the test will fail, and that is the issue. A string representation of the `_id` is being passed in to `hydrate`, but should be cast to an `ObjectId` instance.

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/guide.html#id

https://mongoosejs.com/docs/api.html#document_Document-id

It is suppose to be a string

**Comment by asabhaney** [comment]
I do understand `id` is supposed to be a string, but the issue I'm trying to communicate is about how `Model.hydrate` is designed to work. Perhaps I'm not being clear, so allow me to explain through an example.

Let's say you create a `Book` document, as you did above in your example. Now, you want to save that book record to a file or cache, or perhaps you need to transmit it over a network. Either way, to do so, you need to create a JSON representation of the data. But JSON doesn't have such a thing as an `ObjectId`, so your `ObjectId`s become stringified when you create a plain JSON object.

Later on, you are receiving or loading this JSON object, but now you want to use it as a mongoose doc (and you want your IDs to be `ObjectId`s again, and not strings, as they are when in plain JSON format). So you use `Model.hydrate`, which I believe is the intended solution for this particular use-case.

Upon using `Model.hydrate`, you expect that each of the fields in your mongoose doc are correctly typed to match the schema path definitions. And up until `5.12.4`, this is how it worked, which is why I believe this is a bug and not the intended behavior.

I hope that provides more context and clarity, but if not, please let me know. Thanks in advance.

**Comment by IslandRhythms** [comment]
```javascript
const assert = require('assert')
const mongoose = require('mongoose')
const { Schema } = mongoose

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const authorSchema = new Schema({
        name: String
    });
   const bookSchema = new Schema({
      // Removing the `ref: 'author'` option causes the test to pass successfully
      author: { type: mongoose.Types.ObjectId, required: true, ref: 'author' }
   })

   const Book = mongoose.model('book', bookSchema);
       const Author = mongoose.model('author',  authorSchema);
        const entry = await Author.create({
        name: 'John'
    })

   const book = Book.hydrate({
      author: entry.id
   })

   assert(book.author instanceof mongoose.Types.ObjectId)
   console.log('done')
};

run();
```

npm install mongoose 5.12.3: passes
npm install mongoose@latest: fails
