### ISSUE TITLE
Typescript Strict schema issue

### ISSUE THREAD

**Issue by GalDayan** [Automattic/mongoose#11063]
Hey,

i've this code ![image](https://user-images.githubusercontent.com/24251369/145392271-28b927cf-43a2-46be-89e2-19e68fe294db.png)

This is the interface
![image](https://user-images.githubusercontent.com/24251369/145392349-27fbbd7b-766f-41d1-9e30-5a7515ba6812.png)

And this is the error
```
Type '{ type: StringConstructor[]; required: false; default: never[]; }' is not assignable to type 'typeof SchemaType | Schema<any, Model<any, any, any>, undefined> | Schema<any, Model<any, any, any>, undefined>[] | Function[] | SchemaTypeOptions<...> | SchemaTypeOptions<...>[] | ("string" | ... 4 more ... | undefined)[] | ("string" | ... 4 more ... | undefined)[][]'.
  Types of property 'type' are incompatible.
    Type 'StringConstructor[]' is not assignable to type 'typeof SchemaType | Schema<Document<any, any>, Model<any, any, any>, undefined> | string[] | undefined'.
      Type 'StringConstructor[]' is not assignable to type 'string[]'.
        Type 'StringConstructor' is not assignable to type 'string'.
```

What could be the problem?

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

interface Internal {
    labels: string[]
}

const schemaDef: Required<mongoose.SchemaDefinition<Internal>> = {
    labels: {type: [String], required: false, default: []}
}
```

**Comment by GalDayan** [comment]
I'm using mongoose version 6.1.1

**Comment by vkarpov15** [comment]
@GalDayan we're unable to repro, can you please modify @IslandRhythms 's script to demonstrate your issue?

**Comment by GalDayan** [comment]
I have this problem with @IslandRhythms 's script
![image](https://user-images.githubusercontent.com/24251369/145705487-be06432a-1759-40b0-9e93-08b1ce7d6464.png)

Using typescript version 4.5.3
mongoose version 6.1.1

**Comment by GalDayan** [comment]
Never mind. I found that a problem since we are using version mongoose@5.12.10.
It cannot be reproduced on version 6.1.1.
