### ISSUE TITLE
Incompatibility with older mongo wire protocol version <= 2 in Cosmos DB's MongoAPI and Issue with populate operation

### ISSUE THREAD

**Issue by vtrphan** [Automattic/mongoose#11072]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After updating mongoose to version > 6.1.0, connection to Azure Cosmos DB's MongoAPI server version 3.2 isn't possible anymore. The following error is reported:
`Server at cosmosdb-dev.documents.azure.com:10255 reports maximum wire version 2, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)`

If i update the Cosmos DB's MongoAPI server version to a higher one (e.g 3.6 or even 4.0), the connection work, but `populate` operation doesn't work anymore. Without populate operation, the fields referencing IDs now return something like `new ObjectId("<object_id>")`. I notice with older server version of Cosmos DB's MongoAPI (prior to 3.6), it returns those fields as `ObjectId("<object_id>")` and populate worked as expected.
I don't know if this is a problem on the side of Microsoft Azure CosmosDB, but since CosmosDB's MongoAPI claims to be an implementation of the Mongo Wire Protocol (see: [https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb/error-codes-solutions](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb/error-codes-solutions)), i guess i can post the issue here, hoping for a possible clarification or solution/work around.

Because of the issue with populate and wire protocol version incompatibility, i had to go back to CosmosDB's MongoAPI version 3.2 AND downgrade mongoose back to 6.0.15

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
No issue or at least backward compatibility with older Mongo wire protocol versions

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.0.0
Mongoose 6.1.1
Cosmos DB's MongoAPI version 3.6

**Comment by vkarpov15** [comment]
We'll investigate and do our best to figure this out, but it is worth noting that Mongoose does **not** officially support CosmosDB. We do not run tests against Cosmos, so there may be inconsistencies.

**Comment by xxzefgh** [comment]
I can confirm it doesn't work for MongoDB 3.2. In my opinion, this should be reverted and introduced as a breaking change

**Comment by vtrphan** [comment]
> 

You mean it doesn't work for server version > 3.2 (i.e 3.6 or 4.0) ?  For me, the last mongoose version that works with `Azure CosmosDB's MongoDB API server version 3.2` is v6.0.15. Starting with mongoose 6.1 it does not work anymore, because it requires higher wire protocol version of MongoDB.
Also, if i upgrade CosmosDB's MongoDB API server version to either 3.6 or 4.0, **the connection works** with Mongoose v6.1 and higher, but **the queries doesn't work** anymore (**populate** does not work in my case, but there might be other incompatibilities and breaking changes in other types of query as well).
CosmosDB's MongoDB API boasts an implementation of MongoDB's wire protocol, so i would expect it to be at least compatible with mongoose...

**Comment by vtrphan** [comment]
> I can confirm it doesn't work for MongoDB 3.2. In my opinion, this commit should be reverted and introduced as a breaking change
> 
> [b579739](https://github.com/Automattic/mongoose/commit/b579739c38321a6130765d09968c72a2ba202cbb)

You mean it doesn't work for server version > 3.2 (i.e 3.6 or 4.0) ? For me, the last mongoose version that works with Azure CosmosDB's MongoDB API server version 3.2 is v6.0.15. Starting with mongoose 6.1 it does not work anymore, because it requires higher wire protocol version of MongoDB.
Also, if i upgrade CosmosDB's MongoDB API server version to either 3.6 or 4.0, the connection works with Mongoose v6.1 and higher, but the queries doesn't work anymore (populate does not work in my case, but there might be other incompatibilities and breaking changes in other types of query as well).
CosmosDB's MongoDB API boasts an implementation of MongoDB's wire protocol, so i would expect it to be at least compatible with mongoose...

**Comment by xxzefgh** [comment]
@vtrphan I didn't do any extensive testing, we have 3.2 server in house, so I can't comment on CosmosDB, or any other variants. It complains about wire protocol v4, as the compatibility table states [here](https://docs.mongodb.com/drivers/node/current/compatibility/), MongoDB versions up to 3.6 are not supported anymore.

**Comment by vkarpov15** [comment]
We discussed this with the MongoDB Node driver team, and their stance is that this change is necessary for continued maintenance and minor because MongoDB 3.2 has been EOL-ed for years. Sorry for the inconvenience, but there's nothing we can do about this in Mongoose - if the MongoDB driver doesn't support it, Mongoose can't.

**Comment by vtrphan** [comment]
The backward compatibility issue with server version 3.2 of CosmosDB's MongoAPI can be fixed by upgrading the server version of CosmosDB's MongoAPI to 3.6 or higher. But then, a few operations stopped working (populate is one of them).
@vkarpov15 is this at least worth an investigation? otherwise I'll be stuck forever with Mongoose 6.0.15 and server version 3.2

**Comment by vkarpov15** [comment]
@vtrphan can you please clarify what you mean by "a few operations stopped working" - concrete examples?
