### ISSUE TITLE
save function doesn't save all the fields

### ISSUE THREAD

**Issue by NedjmeDjedouani** [Automattic/mongoose#11075]
**What is the current behavior?**
some fields are being dropped from document instance
**If the current behavior is a bug, please provide the steps to reproduce.**
strange behavior on mangoose save...idk why 'ingredients' and 'description' got dropped from the model instance and db,no error as you can see, i tried to rename them to something else and it worked ! but no idea why...
any help would be appreciated thanks

![s1](https://user-images.githubusercontent.com/87482619/145670169-42f6dfdf-99a4-4ba4-b07f-68dbf2f370e6.PNG)
![s2](https://user-images.githubusercontent.com/87482619/145670171-c7fcffef-6100-4101-9762-157223c35d02.PNG)
![s3](https://user-images.githubusercontent.com/87482619/145670172-610ae2be-3f37-42c5-b369-d338013feaf5.PNG)

**What is the expected behavior?**
the fields doesn't get  dropped from model instance
**What are the versions of Node.js, Mongoose and MongoDB you are using?**
monggose version : 6.1.1
mongodb version: 5.0
nodejs version : 14.18.0

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    name: String,
    price: Number,
    description: String,
    ingredients: String,
    category: String,
    imgurl: String,
    cloduinaryid: String
});

productSchema.methods.toJSON = function() {
    const product = this.toObject();
    delete product.__v;
    return product;
}

const Product = mongoose.model('Product', productSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
        useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    const entry = new Product({
        ingredients: 'Flour',
        description: 'cake',
        name: 'John',
        price: 200
    });
    await entry.save()
    console.log(await Product.find());
    console.log('done');
}

run();
```

**Comment by NedjmeDjedouani** [comment]
@IslandRhythms thanks for your response sir but even dropping the db didn't work i tried pre save middleware and markModified and that didn't work too 
The only workaround until now was renaming the fields

**Comment by AbdelrahmanHafez** [comment]
@NedjmeDjedouani Sadly without being able to reproduce the issue, we won't be able to help.

Please provide a reproduction script so that we can identify the root cause and fix.
