### ISSUE TITLE
Document is not rolled back if transaction gets aborted 

### ISSUE THREAD

**Issue by vinnytwice** [Automattic/mongoose#11076]
In my server I'm trying to use transactions to create orders. Before saving the order with `Order.create` I check and modify quantities in Product records, check for payment details on buyer and seller, aborting the transaction if anything goes wrong ( I omitted that part in the code sample below), but when passing the object from the request body to `Order.create` as I normally do on document creation it fails not finding requested parameters for the Order schema. 

 I have found here https://github.com/Automattic/mongoose/issues/6761#issuecomment-437493275 and also the doc https://mongoosejs.com/docs/api.html#model_Model.create say that when inside a transaction the object needs to be passed into an array ( like `await SomeModel.create([obj], { session })` ), so I suppose that as we are inside a transaction, if the transaction is aborted then the created record gets rolled back.
 In my app it does create the document but it's not rolled back if I abort the transaction . In fact if I query the db with the document id just created I get the result back. 

Also now my logic inside the `finally` statement is not working anymore. There, if the transaction is not aborted the if statement check on `session.inTransaction` should return `true` so there I commit the transaction and end the session. If instead the transaction is aborted it should return `false` and nothing else happens as  whenever I abort the transaction I also end the session.
When using `await SomeModel.create([obj], { session })` the if statement never returns true so the transaction is never committed and the session is never ended.

Can you see what's wrong with the code here below? 

  

 
```
exports.createOrder = async (req, res) => {

    const { productIdList, productPromotionList, customerId, shopId } = req.body;

    // const order = req.body;
    var notAvailableProducts = [];
    var notAvailablePromotions = [];
    // console.log('createOreder req.body is : ', order);
    var amount = 0.00;
    var stripeAccountId = '';
    var stripeCustomerId = '';
    var receiptEmail = '';
    var defaultSource = '';
    const session = await Order.startSession();
    session.startTransaction();

    try {

... omitted part

        console.log('createOrder req.body is : ', req.body);

        // const order = 
        // await 
        Order.create(
           // req.body, // error 
            [ req.body], // works but doesn't get rolled back if transaction is aborted
            { session: session },
            function (err, result) {
                if (err) {
                    console.log('Mongoose createOrder error:  Order.create', err);
                    res.status(503).send({ error: "Internal error" });
                    session.abortTransaction();
                    session.endSession();
                    return;
                }


                console.log('Mongoose createOrder: ', result);
                res.status(200).send({
                    message: "Order created successfully!",
                    data: result,
                    missingProducts: notAvailableProducts,
                    missingPromotions: notAvailablePromotions
                });

            });


session.abortTransaction();
session.endSession();

    }
    catch (error) {
        console.log('Transaction error is:', error);
        await session.abortTransaction();
        session.endSession();
        res.status(503).send({ error: "Internal error." });
        // throw error; 
    }
    finally {

        if (session.inTransaction == true) {

            console.log('committing session');
            await session.commitTransaction();
            console.log('ending session');
            session.endSession();
        } else {
            console.log('session was aborted');

        }

    }

}
```

**Comment by vinnytwice** [comment]
As it seems that Model.create can't be undone upon aborting a transaction the only way I found to manage it ( not sure it's just a workaround or  the proper business logic) is to wrap it in a `if` statement checking the current state of the session `if (session.inTransaction()) {}` as I do in the `finally` statement to commit the transaction or simply end the session.

```
exports.createOrder = async (req, res) => {

...

            if (session.inTransaction()) {
                const order = {
                    city: city,
                    region: region,
                    country: country,

                    date: Date.now,
                    price: totalOrderAmount,
                    state: 'Waiting',
                    collectedOnDate: null,
                    cancelledOnDate: null,
                    customerFcmToken: customerFcmToken,
                    customerId: customerId,
                    customerName: customerName,
                    shopId: shopId,
                    shopName: shopName,
                    productCategoryList: productCategoryList,
                    productIdList: productIdList,
                    productIsPromotionList: productIsPromotionList,
                    productNameList: productNameList,
                    productPriceList: productPriceList,
                    isBuyNow: isBuyNow,
                    

                    stripePayment: stripePaymentIntent
                };


                await Order.create(
                    [order],
                    { session: session },
                    function (err, result) {
                        if (err) {
                            console.log('Mongoose createOrder error:  Order.create', err);
                            session.abortTransaction();
                            responseCode = 503;
                            responseMessage = 'Internal error';
                            return;
                        }
                        console.log('Mongoose createOrder: ', result);
                        responseCode = 200;
                        responseData = result;
                        message = "Order created successfully!";
                    }).exec();
            }



        }
    }
    catch (error) {
        console.log('Transaction error is:', error);
        await session.abortTransaction();
        session.endSession();
        res.status(503).send({ error: "Transaction error." });
        // throw error; 
    }
    finally {
        if (session.inTransaction()) {
            console.log('transacion wasn\'t aborted');
            console.log('committing session ');
            await session.commitTransaction();

        } else {
            console.log('transacion wasn aborted');
        }

        console.log('ending session ');
        await session.endSession();
        res.status(responseCode).send({
            message: responseMessage,
            data: responseData,
            unavailableProducts: unavailableProducts,
            unavailablePromotions: unavailablePromotions
        });

    }



}
```

**Comment by vkarpov15** [comment]
You should use `await Order.create()`. Because you're mixing callbacks and async/await, you're ending up aborting the transaction before creating the document, which means you're creating a document outside of a transaction. When you say "the if statement never returns true" - duh, you're aborting the transaction in the `try` and in the `catch` so of course `if (session.inTransaction())` will never execute.

Since you're struggling to use `commitTransaction()` and `abortTransaction()`, I'd recommend you just use `session.withTransaction()`, or Mongoose's `Connection.prototype.transaction()`, which handle committing and aborting transactions for you. Read more here: https://thecodebarbarian.com/whats-new-in-mongoose-5-10-improved-transactions.html
