### ISSUE TITLE
[documentation] 404s in internal documentation links

### ISSUE THREAD

**Issue by bjrne** [Automattic/mongoose#11089]
**Bug**

**What is the current behavior?**
When visiting the documentation under https://mongoosejs.com/docs/api.html#mongoose_Mongoose-Document (via first Google hit to api.html and then clicking on the `Mongoose.prototype.Document()` link), a click on the `Document` link there leads to https://mongoosejs.com/api/document.html which returns a 404 when it should probably link to https://mongoosejs.com/docs/api.html#Document .

**If the current behavior is a bug, please provide the steps to reproduce.**
Stated above.

**What is the expected behavior?**
It should probably link to https://mongoosejs.com/docs/api.html#Document .

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
There is no version number in the docs, but the docs are referring to mongoose 6.1.1

**Comment by khairnarsaurabh23** [comment]
can i work on this issue?

**Comment by vkarpov15** [comment]
@khairnarsaurabh23 of course, feel free to put in a PR. There's no need to ask.

**Comment by khairnarsaurabh23** [comment]
I've made respective changes, but before PR how can I test those changes? I tried to find it but couldn't.

**Comment by khairnarsaurabh23** [comment]
@vkarpov15

**Comment by vkarpov15** [comment]
@khairnarsaurabh23 `make gendocs` to compile docs and `node ./static.js` to run static server

**Comment by vkarpov15** [comment]
Should be fixed by #11179
