### ISSUE TITLE
I just updated to mongoose 6.1.1

### ISSUE THREAD

**Issue by enffinity** [Automattic/mongoose#11082]
When i try to use mongoose.hookNextFunction type it says "type mongoose.hookNextFunction = /*unresolved*/ any
Namespace '"mongoose"' has no exported member 'hookNextFunction'.ts(2694)"

**Comment by hansemannn** [comment]
See https://mongoosejs.com/docs/migrating_to_6.html#typescript-changes for details which references `HookNextFunction` as part of deprecated / removed types.

**Comment by vkarpov15** [comment]
We removed `HookNextFunction` in 6.0. It's an unnecessary definition and we're trying to trim down our TypeScript type complexity as much as possible. `HookNextFunction` was just `(err?: Error): any` anyway.
