### ISSUE TITLE
Adding custom instance methods in bulk with TypeScript

### ISSUE THREAD

**Issue by Shassk** [Automattic/mongoose#11086]
I'm not sure if I should mark it as an error or as a feature request, but I've come to this after getting errors trying to use `loadClass(ClassX_extends_Document)` to add to each model instance methods I need.

The idea was next: I needed models to inherit custom base class and have a certain set of instance functions (trying to replicate the same functionality as already exists for MySQL, so this is a requirement). 

Simple class example, no overriding standard methods or anything:

```
export class BaseClass extends Document {
	public someField: number
	public constructor(init?: Partial<AsyncBaseClass>) {
		super()
		Object.assign(this, init)
	}
	public async addNextValue(): Promise<number|undefined> {
		const someValue = await DbDriver.getNextValue(this)
		let failed = false
		if (newId) {
			this.someField = someValue
			await this.save() // mongoose method
			return someValue
		}
		return undefined
	}
}
//-------------------------------------------
export const _NewClass = new Schema({
	someField: Number
})
_NewClass.loadClass(BaseClass)
export const NewClass = model('NewClass', _NewClass, 'NewClass')
```

Trying to create and save new document results in `Can't validate() the same doc multiple times in parallel` error in `save()` method:

```
let newClass = new NewClass({})
await a2.save().catch((e:any) => console.log('e:', e))
```

In the docs I've found out this isn't recommended. And adding methods one by one like this works:

```_NewClass.methods.addNextValue = async function(): Promise<number|undefined> { ... }```

But I didn't find a way to prepare those methods beforehand while keeping the scope of `this` which is required for calling default instance methods of `Model` inside custom instance methods. Not to mention adding methods to schema/model in bulk.

So how can I achieve what I described: clean adding custom instance methods into `Model` which will have access to default instance methods of `Model` with TypeScript?

Node.js 14.17.1
Mongoose 6.0.14
MongoDB 4.2.17 Community (latest available on Win8.1)
tsconfig doesn't want to add as a file, so I'll just copy the contents:
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "outDir": "out",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "alwaysStrict": true
  }
}
```

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/guide.html#statics

Is this what you're looking for?
