### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by R0N1n-dev** [Automattic/mongoose#11097]
Using latest version of mongoose and mongodb 4.4.8 and keep getting validation error when I try posting to the database. So annoying, am following a tutorial and all goes well but when I try it, it gives me a validation error on one of my fields

**Comment by alibehroozi** [comment]
I'm experiencing the same issue.

Every find query that is using $ operators is failing in our product which made us revert the whole server today.
`Cast to Boolean failed for value "{ '$ne': true }" (type Object) at path "path" for model "model"`

We are using aggregations instead but I have no idea why this is happening.
Also some types are not correct in mongoose 6.1.1 (I'm wondering isn't there any testing/linting for pull requests to avoid these major issues)?

**Comment by IslandRhythms** [comment]
@alibehroozi please open a new issue and provided a repro script.
@R0N1n-dev please provide a reproductino script

There is not enough information to do anything right now.

**Comment by R0N1n-dev** [comment]
Had some almost unnoticeable error in the post route of my app. Never showed an error in logs or console
