### ISSUE TITLE
Typescript throws an error when using operators

### ISSUE THREAD

**Issue by magyarb** [Automattic/mongoose#11090]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

The last line in the following script produces a typescript error. I need to find the objects where the `deletedAt` property is `null`, and it works perfectly when using `//@ts-ignore`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
interface teamMemberInterface {
    user: Schema.Types.ObjectId | userInterface;
    deletedAt?: Date
}

const teamMemberSchemaSrc: Record<keyof teamMemberInterface, any> = {
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    deletedAt: Date
}

const teamMemberSchema = new Schema(teamMemberSchemaSrc, { timestamps: true, autoCreate: autoCreate })

const teamMember = model<teamMemberInterface>('teamMember', teamMemberSchema);

await teamMember.find({user:ctx.user, deletedAt: {$eq: null}})

```

tsconfig.json
  ```
{
    "compileOnSave": true,
    "compilerOptions": {
      "allowJs": true,
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "inlineSourceMap": false,
      "inlineSources": false,
      "lib": ["es6", "es2015", "es2016", "es2017"],
      "module": "commonjs",
      "moduleResolution": "node",
      "newLine": "LF",
      "noImplicitAny": false,
      "noUnusedLocals": true,
      "strictNullChecks": true,
      "noUnusedParameters": false,
      "outDir": "build",
      "pretty": true,
      "sourceMap": true,
      "strictFunctionTypes": false,
      "target": "es2017",
      "types": ["node"],
      "typeRoots": [
        "node_modules/koa-bodyparser",
        "node_modules/@types"
      ]
    },
    "include": ["**/*", "typings/**/*"],
    "exclude": ["node_modules", "**/*.spec.ts", "build"]
  }
```
**What is the expected behavior?**

The last line here throws an error, stating that in the `FilterQuery<teamMemberInterface>` the `deletedAt` property should be a `Date` or `undefined`. But an object with a mongo query operator like `$eq` should also work. I think there should be a change in the type `ApplyBasicQueryCasting` to account for these operator objects.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v14.17.0 mongoose v6.1.1 mongodb v4.2.1

**Comment by magyarb** [comment]
Managed to reproduce the same issue in one line:

```
import { UpdateQuery } from 'mongoose';
const qu: UpdateQuery<any> = {isDefault: false};
```

The error:

```
Type '{ isDefault: boolean; }' is not assignable to type 'UpdateQuery<any>'.
  Type '{ isDefault: boolean; }' is not assignable to type 'ReadonlyPartial<_UpdateQueryDef<DeepPartial<any>>>'.
    Property 'isDefault' is incompatible with index signature.
      Type 'boolean' is not assignable to type 'DeepPartial<any> | undefined'.ts(2322)
```

**Comment by magyarb** [comment]
#11101 and this is a separate issue. That, and the DeepPartial error is solved by downgrading to 6.0.14. This main issue (operators) exists in that version too.

**Comment by IslandRhythms** [comment]
Both scripts work fine for me

**Comment by magyarb** [comment]
Here is a reproduction link: [https://www.anyfiddle.com/p/magyarb94/bjhqajww](https://www.anyfiddle.com/p/magyarb94/bjhqajww)

Run `yarn tsc` to see the error.

The issue exists in 6.0.15, but seems to be solved in 6.1.3.

**Comment by IslandRhythms** [comment]
@magyarb Can you not update? If the problem is solved by updating then I suggest you do so unless there is something preventing you from doing so.

**Comment by magyarb** [comment]
I was using the latest version when opening the issue. As this is solved, this issue can be closed.
