### ISSUE TITLE
Duplicate Git Tags for version 6.1.1

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11100]
**Do you want to request a *feature* or report a *bug*?**
docs / dev experience

**What is the current behavior?**
Currently, there are 2 git tags for version 6.1.1:

- [hell](https://github.com/Automattic/mongoose/releases/tag/hell)
- [6.1.1](https://github.com/Automattic/mongoose/releases/tag/6.1.1)

i think the `hell` tag might have been accidentally released

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Affected version: 6.1.1

**Comment by IslandRhythms** [comment]
Currently working on automating the releases, that was an accident but I can't delete the git tag. @vkarpov15 can

**Comment by vkarpov15** [comment]
Fixed :+1:

**Comment by hasezoey** [comment]
@vkarpov15 can it be that tag [`test`](https://github.com/Automattic/mongoose/releases/tag/test) is also a "accidental" release?

**Comment by vkarpov15** [comment]
@hasezoey correct, fixed :+1:
