### ISSUE TITLE
MongooseError: Invalid $unset in pipeline, must be an array of strings

### ISSUE THREAD

**Issue by rpenido** [Automattic/mongoose#11106]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can't use $unset with a string in Model.updateOne(), using AggregationPipeline.

Error:
```
MongooseError: Invalid $unset in pipeline, must be an array of strings
```

**If the current behavior is a bug, please provide the steps to reproduce.**
The code below raises the error:
```
await Model.updateOne({}, [{ $unset: 'myField' }])
```
The code below works:
```
await Model.updateOne({}, [{ $unset: ['myField'] }])
```

**What is the expected behavior?**

According to the docs, both should work without errors
https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/
https://docs.mongodb.com/manual/reference/operator/aggregation/unset/#mongodb-pipeline-pipe.-unset

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 6.1.2

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String,
    age: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();

    await Test.create({ name: 'Test'});

    // error
    console.log(await Test.updateOne({}, [{$unset: 'name'}]))
    // no error
    // console.log(await Test.updateOne({}, [{$unset: ['name']}]))


};

run();
```

**Comment by sean-daley** [comment]
That documentation is for the aggregation pipeline $unset which differs from the update $unset … https://docs.mongodb.com/manual/reference/operator/update/unset/#mongodb-update-up.-unset
