### ISSUE TITLE
Documentation example in Dynamic RefPath breaks the program

### ISSUE THREAD

**Issue by BigOsvaap** [Automattic/mongoose#11113]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
An example provided in the documentation doesn't work and breaks the app.
[docs](https://mongoosejs.com/docs/populate.html#dynamic-ref)

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript

const mongoose = require('mongoose')
const {Schema} = mongoose

const commentSchema = new Schema({
	body: { type: String, required: true },
	on: {
	  type: Schema.Types.ObjectId,
	  required: true,
	  refPath: 'onModel'
	},
	onModel: {
	  type: String,
	  required: true,
	  enum: ['BlogPost', 'Product']
	}
  });
  
const Product = mongoose.model('Product', new Schema({ name: String }));
const BlogPost = mongoose.model('BlogPost', new Schema({ title: String }));
const Comment = mongoose.model('Comment', commentSchema);

async function run() {

    await mongoose.connect('mongodb://localhost:27017/', {
        useNewUrlParser: true, 
        useUnifiedTopology: true
    })
    await mongoose.connection.dropDatabase()

    const book = await Product.create({ name: 'The Count of Monte Cristo' });
    const post = await BlogPost.create({ title: 'Top 10 French Novels' });

    const commentOnBook = await Comment.create({
		body: 'Great read',
		on: book._id,
		onModel: 'Product'
     });

     const commentOnPost = await Comment.create({
		body: 'Very informative',
		on: post._id,
		onModel: 'BlogPost'
     });

     const comments = await Comment.find().populate('on');

     console.log(comments);

}

run()

```

**What is the expected behavior?**

It appears the problem happens because the word on is a reserved pathname

https://github.com/Automattic/mongoose/blob/24d1d6f6e8ed849f8a86d272a5ac76680de89b39/lib/schema.js#L605-L612

https://github.com/Automattic/mongoose/blob/24d1d6f6e8ed849f8a86d272a5ac76680de89b39/lib/schema.js#L672-L679

I think the solution would be to update that part of the documentation

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 17.0.1
Mongoose: 6.1.2

**Comment by vkarpov15** [comment]
Updated the docs :+1:
