### ISSUE TITLE
Promise.all with .transaction

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11115]
@vkarpov15 
Is there any way to run multiple (different) document .save() operations in parallel with a Promise.all in a reliable way?

If I use a Promise.all then I get " Given transaction number 1 does not match any in-progress transactions. The active transaction number is -1"-Error. If I run the save Operations in sequence, it works properly. It seems somehow, that when you run all .save at the same time and one of the .save's gets an Error, it will not be caught properly by the transaction-helper-method and the session gets closed, while it should be imho a retryable Error and the session should have been kept and the underlying operation should have been retried. 

You can see the issue in medici

https://github.com/flash-oss/medici/commit/c5f5902e2fa82f5531bd249eaa9a30672231a9a5#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

(Dont get confused... I thought Promise.allSettled would fix the issue, but actually just covered the issue). 

Now I do the calls in sequence to ensure, that it works properly. But is it the only save way?

**Comment by Uzlopak** [comment]
Ok. I got it. You have to do the first write request not in parallel and then you can do the rest in parallel. 

https://stackoverflow.com/a/68393506/4968833

Maybe should be better documented.

**Comment by vkarpov15** [comment]
@Uzlopak hard to tell without code samples - I don't see any `Promise.all()` usage in the [link you provided](https://github.com/flash-oss/medici/commit/c5f5902e2fa82f5531bd249eaa9a30672231a9a5#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26). It looks like all the transactions are running in series in that link. Also it depends on the nature of the error you mentioned in "one of the .save's gets an Error, it will not be caught properly by the transaction-helper-method" - not all errors are retryable.

Can you please provide a repro script or test case that demonstrates the issue you're seeing?

**Comment by Uzlopak** [comment]
Yes, I will provide you a code snippet next week. I have no computer rn.

But to clarify: this is an issue which also the mongo driver should have. Only way to fix this issue would be to check if an operation is in a session and if so check if the session had already one successful transaction and if not it should await the first one and then the rest should be handled as before.
