### ISSUE TITLE
Unexpected fatal error when saving a document: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by vvandens** [Automattic/mongoose#11110]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

An unexpected error is thrown up to the node machine that gets killed (even not handled in the save() promise)

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const {
  Schema,
  model,
  Types,
  connect,
  connection
} = require("mongoose");

const TEST_SCHEMA = new Schema({
  level_1_array: [new Schema({
    level_1: {
      level_2: new Schema({
        level_3: {
          name_3: String,
          level_4: {
            name_4: String
          }
        }
      })
    }
  })]
});

const Test = model('Test', TEST_SCHEMA);

async function run() {
  await connect('mongodb://localhost:27017/test');
  await connection.dropDatabase();


  const doc = {
    level_1_array: [{
      level_1: {
        level_2: {
          level_3: {
            name_3: 'test',
            level_4: undefined
          },
        },
      },
    }],
  };

  await new Test(doc).save();
}

run()
  .then(() => {
    console.log('Test was successful.');
    process.exit(0);
  })
  .catch((e) => {
    console.log('Test failed: ', e.message);
    process.exit(1);
  });
```

**What is the expected behavior?**

The Test document should be saved (it is on Mongoose 5).
In Mongoose 6.x, Node gets killed with **TypeError: Cannot convert undefined or null to object**.
At least, the error should end up into the global **.catch(...)**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node : **16.13.1**
Mongoose : **6.0.15** and **6.1.2**
MongoDB : **4.2.17**

**Comment by IslandRhythms** [comment]
You omitted the `name_4` field it was expecting

```javascript
const {
    Schema,
    model,
    Types,
    connect,
    connection
  } = require("mongoose");
  
  const TEST_SCHEMA = new Schema({
    level_1_array: [new Schema({
      level_1: {
        level_2: new Schema({
          level_3: {
            name_3: String,
            level_4: {
              name_4: String
            }
          }
        })
      }
    })]
  });
  
  const Test = model('Test', TEST_SCHEMA);
  
  async function run() {
    await connect('mongodb://localhost:27017/test');
    await connection.dropDatabase();
  
  
    const doc = {
      level_1_array: [{
        level_1: {
          level_2: {
            level_3: {
              name_3: 'test',
              level_4:{name_4: undefined}
            },
          },
        },
      }],
    };
  
    await new Test(doc).save();
    console.log('done')
  }
  
  run();
```

**Comment by vvandens** [comment]
Thank you @IslandRhythms for your comment, but this is exactly the point of the bug case... I definitely know how to fix the input so that the test case passes (also omitting level_4:undefined or switching to sub-schemas for level_4 does the trick).

This test case is a minified excerpt of a production problem that we have faced after V6 migration that simply **killed our node servers** from time to time since the error happens very deeply in Mongoose in some async piece of code that is *not awaited*. If it were, it would have gone through the .catch() block of the test case main method (as it would have gone through the top-most global error handler of our production servers).

So I would expect :

1. The validator to cleanly fail if the input document does not conform to the schema. And it does 99.9% of the time. I literally spent hours figuring out the shape of the schema and the form of the input document that was causing the problem.
2. No dangling promise (or equivalent) in the library since they are production killers.
