### ISSUE TITLE
findByIdAndUpdate not update enum field with changed value

### ISSUE THREAD

**Issue by moisesbites** [Automattic/mongoose#11120]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When saving using findByIdAndUpdate, the String field with an enum list is not updated. For new values, okay, findByIdAndUpdate inserts the values. For changed values, it is not updating/changing the value in the database. The validators run ok, too. Just don't save the changed value.

**If the current behavior is a bug, please provide the steps to reproduce.**

I send a new value from frontend to backend using a json object. The api take the object and try do save using findByIdAndUpdate. After that, the object updated don't have de values of enum properties updated. New values are saved correctly.

The command I'm using is below:
```JS
    const doc = await Model.findByIdAndUpdate(req.params.id, req.body, {
      new: true,
      runValidators: true
    });
```

The propertie/field is like this:
```JS
   telephoneType: {
      type: String,
      required: true,
      enum: ['cell', 'commercial', 'contact', '0800', 'whatsapp', 'fax', 'home']
    },
```

**What is the expected behavior?**

If i change the value in a propertie/field, the findAndUpdate updates the value of this propertie/field in the database.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
  System:
    OS: Linux 5.13 Linux Mint 20.2 (Uma)
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 8.06 GB / 23.37 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
    mongoose: 6.1.2
    mongodb: 5.0.5
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.63.2 - /usr/bin/code
  Browsers:
    Chrome: 96.0.4664.110
    Chromium: 96.0.4664.110
    Firefox: 95.0
```

**Comment by BigOsvaap** [comment]
Hello, it appears that there is no bug, I tried to replicate the issue but I wasn't able to do so. I share with you the code that I tried and maybe you can tell me if there's a misunderstood. If there's not misunderstood, maybe the data in the req.body has a typo, something like teleponeType instead of telephoneType.

```javascript
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const phoneSchema = new Schema({
    number: {
        type: String,
        required: true
    },
    type: {
        type: String,
        required: true,
        enum: ['cell', 'commercial', 'contact']
    }
})

const Phone = mongoose.model('Phone', phoneSchema)

async function run() {

    await mongoose.connect('mongodb://localhost:27017/', {
        useNewUrlParser: true, 
        useUnifiedTopology: true
    })
    await mongoose.connection.dropDatabase()

    const phone = await Phone.create({number: '2351212288', type: 'cell'})

    console.log('Record saved', phone)
    
    const result = await Phone.findByIdAndUpdate(phone._id, 
        {number: '2201562200', type: 'commercial'}, 
        {new: true, runValidators: true})
    
    console.log('Record updated', result)

}

run()
```

This is the output that I got for this code. 

`
Record saved {
  number: '2351212288',
  type: 'cell',
  _id: new ObjectId("61bfff3b8480bac782727000"),
  __v: 0
}
Record updated {
  _id: new ObjectId("61bfff3b8480bac782727000"),
  number: '2201562200',
  type: 'commercial',
  __v: 0
}
`

**Comment by moisesbites** [comment]
@BigOsvaap 

Thank you for your help. I tried to test again, and with a fine debug I found the problem. it was a subtle mistake. A virtual field was changing the value, because de App app was sending the data with a filled in virtual field. Sorry about this issue. I'm closing.
