### ISSUE TITLE
Missing properties inside TypeScript SchemaType type

### ISSUE THREAD

**Issue by arnaud-moncel** [Automattic/mongoose#11139]
Hi guys 👋  a little question / type request.

**Do you want to request a *feature* or report a *bug*?**
Not really a bug, but i think some properties are missing inside SchemaType type (eg: path, validators, isRequired).

**What is the current behavior?**
Some properties are missing like `path`, `validators`, `isRequired`.

**What is the expected behavior?**
I don't know if these absences are voluntary, but i think these property are missing.
Let me know if i'm right 🙏 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 14.17.6
Mongoose: 6.1.3
MongoDB: 4.4.6

**Comment by vkarpov15** [comment]
Those properties aren't part of the publicly documented API: https://mongoosejs.com/docs/api/schematype.html so they aren't in the TS definitions either.

Can you please explain why you need access to these properties? We can add them, just want to be consistent about it.

**Comment by arnaud-moncel** [comment]
Hi @vkarpov15 👋 thank you for your answer 🙏 
I perform some schema introspection to change some behaviours of my application.
For exemple, I d'ont know database schema but i craft some from to fill data into.
So i want to put some input required when a field is required.

I don't if it's clear?

**Comment by vkarpov15** [comment]
We'll add this for our next minor release.
