### ISSUE TITLE
MongoParserError: Expected retryWrites to be stringified boolean but got true

### ISSUE THREAD

**Issue by Fasunle** [Automattic/mongoose#11134]
version 6.1.3
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
MongoParserError: Expected retryWrites to return a stringified Boolean but got true
**If the current behavior is a bug, please provide the steps to reproduce.**

[x] try to connect with the database using the connection string:    mongodb+srv://<username>:<password>@sandbox.qnvqb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

![Uploading server-mongo.png…]()

**What is the expected behavior?**
![server-mongo-error](https://user-images.githubusercontent.com/77301273/147254714-e0c4311e-9e08-4e92-9e64-8fc29d4c0ecf.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 14.17.6
mongoose 6.1.3
mongodb 4.4.10

**Comment by Fasunle** [comment]
![server-mongo](https://user-images.githubusercontent.com/77301273/147255478-f544bab6-4b97-400b-a87f-e724efe49f11.png)

I checked online but the responses I saw couldn't solve the problem.

When I remove the retryWrites=true& w=majority, the connection was successful. But I feel like I have turned the functionality of retryWrites off. This is definitely a bug!

**Comment by vkarpov15** [comment]
Make sure you don't have any typos in your connection string. Given that you typo-ed in [this comment](https://github.com/Automattic/mongoose/issues/11134#issuecomment-1000350312), the most likely explanation is that you have an errant space after `true`:

```javascript
  await mongoose.connect('mongodb://localhost:27017/test?retryWrites=true &w=majority'); // Throws "Expected retryWrites to be stringified boolean value, got: true"
```
