### ISSUE TITLE
insertMany changes the _id field of the inseted data

### ISSUE THREAD

**Issue by eng-dibo** [Automattic/mongoose#11136]
I have a set of data, each document has an `_id` field which is a string not ObjectId, when I try to insert all these data to the database using a loose model without any validation, all _id fields are replaced with an `ObjectId` value which is undesired

```
let schema = new mongoose.Schema({}, { strict: false, validateBeforeSave: false })
let model = new mongoose.Model('collection', schema)

model.insertMany(data, { lean: true, rawResult: true })
```

**expected behavior**
inserting the data as it, without any modification

**actual behavior**
the _id field of each document is modifing to a new ObjectId value

note that the type of _id may be a string or ObjectId, so  I cannot force using a string type like that `{_id: 'string'}`

**Comment by IslandRhythms** [comment]
Documents have an `id` property, which is always a string, as well as an `_id`. That could work for you instead of using `_id`

**Comment by vkarpov15** [comment]
@eng-dibo what does the data object look like in your example?

**Comment by eng-dibo** [comment]
> @eng-dibo what does the data object look like in your example?

I use either `shortid.generate` or ObjectId for _id field.

I just want to insert the exact existing value without any casting and without the need to provide a data model (the valudation is turned off)

**Comment by vkarpov15** [comment]
@eng-dibo not helpful. Please provide an example of a `data` object that demonstrates the issue you're seeing, otherwise we'll have to close this issue.
