### ISSUE TITLE
Why Parallel queries on mongoDb collection increase response time sequentially?

### ISSUE THREAD

**Issue by apoorvtomar2222** [Automattic/mongoose#11141]
So I am observing a pattern in mongodb, while trying to load test my NodeJS application i.e. the response time for executing MongoDb find (happening with other queries as well)query is increasing sequentially.

When I am triggering single mongoDb query it is hardly taking few ms, but when I am triggering 100 request in parallel the response time increases from 50 ms to 3000ms for just a simple find request.

Currently I am trying this on mongoDb version 4.2

As per my finding after 4+ version of mongo there is no Read lock which might block the query.

I have created a simple Node JS application, used both mongoose and mongoDb client just to check verify if we face such issue. The behaviour is same with both the client.

Following is the code. Also I have used jmeter to hit parallel request.

```
const express = require('express')
const app = express()
const port = 3000
let mongoClient = require('mongodb').MongoClient;

const mongoose = require('mongoose');
const url = 'mongodb://localhost:27017/db-name'
mongoose.connect(url);

app.post('/', async (req, res) => {
    const resp = mongoose.connection.db.collection('users1')
    const dateBefore = new Date().getTime();
    const data = await resp.find({ name: 'Apoorv' }).toArray();
    // const data = await resp.insertOne({ name: "Apoorv", time: new Date().getTime() });
    const dateAfter = new Date().getTime();
    console.log('API took this much time', dateAfter - dateBefore)
    res.send(data)
})

app.post('/mongo', async (req, res) => {
    return mongoClient.connect(url, { useUnifiedTopology: true }).then(async (db) => {
        // console.info("Connected successfully to server");
        let client = db;
        const dateBefore = new Date().getTime();
        const data = await client.db("db-name").collection('users1').find({ name: 'Apoorv' }).toArray();
        const dateAfter = new Date().getTime();
        console.log('API took this much time', dateAfter - dateBefore)
        res.send(data)
    });

});

app.listen(port, () => {
    console.log(Example app listening at http://localhost:${port})
})
```

<img width="646" alt="one-request (1)" src="https://user-images.githubusercontent.com/20641976/147368420-959d4436-51c7-4049-97d0-720842652110.png">

<img width="899" alt="1000-request" src="https://user-images.githubusercontent.com/20641976/147368422-c2c99bbc-953d-4e65-840b-f296fbd5cfcd.png">

**Comment by yadavpradeep786** [comment]
@vkarpov15 I also faced the same issue in mongo.... Is this a known behaviour of mongodb or I'm missing something?

**Comment by Uzlopak** [comment]
Creating connections is quite expensive. Use a more realistic benchmark, like using only one connection.

**Comment by apoorvtomar2222** [comment]
> Creating connections is quite expensive. Use a more realistic benchmark, like using only one connection.

@Uzlopak Using mongoose, I am creating just a single connection. Just for ruling out the scenario that single connection might be causing such behaviour, so I used mongodb client which is creating new connection on each API call. 

But I have checked single connection doesn't make any difference.

**Comment by apoorvtomar2222** [comment]
@aheckmann @rauchg 

Can you suggest something?

**Comment by vkarpov15** [comment]
See https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs

**Comment by apoorvtomar2222** [comment]
@vkarpov15 This I was already aware of, but let me know why the same was happening while I was creating a new mongo connection on every request.

In that case according to me it should not be sequential.

**Comment by vkarpov15** [comment]
@apoorvtomar2222 that I'm not 100% sure about. I suspect having lots of connections open slows down the MongoDB server as well, but I don't know the particulars. Either way, we don't recommend opening a separate connection for each request, because opening a new connection is an expensive operation.

**Comment by apoorvtomar2222** [comment]
@vkarpov15 I understand that opening multiple connection is definitely an expensive operation. But the ask was bit different, I wanted to cross check that whenever 1000 parallel queries are made at mongodb level does any kind of queuing takes place?

Since that's the behaviour I am experiencing.

**Comment by Uzlopak** [comment]
Maybe because you are opening that many cursors, which have to be processed.

What happens if you do a findOne?

**Comment by apoorvtomar2222** [comment]
@Uzlopak Same behaviour. Even if I close the DB connection or do it with single mongoose connection behaviour is exactly the same.

**Comment by vkarpov15** [comment]
"whenever 1000 parallel queries are made at mongodb level does any kind of queuing takes place?" Mongoose doesn't do any queueing after initial connection is completed. So in the `app.post('/')` case, Mongoose doesn't do any queueing. However, you'll run into the MongoDB server's slow trains issue.
