### ISSUE TITLE
How to switch database

### ISSUE THREAD

**Issue by seasonhuang** [Automattic/mongoose#1114]
In the **mongo shell**, I can do like this:

```
use admin
db.auth('user','pass')
use test
db.find()
```

This means I pass the authurized then I can do everything.

My problem is how can I do the same work in mongoose, how can I switch db in mongonse?

Because I must enter the ADMIN db to authurize, and then chang to other db to my own manipulation

**Comment by zjgnlzq** [comment]
@Naxmeify you save my life too...! thanks!

**Comment by EightSQ** [comment]
@naxmefy You save also my life! Thanks!

**Comment by sudeeprathod** [comment]
how do i change user login portal to admin login portal on same page?
