### ISSUE TITLE
Duplicate Key Error when a Schema has an array of another Schema with a unique index

### ISSUE THREAD

**Issue by thegoldgoat** [Automattic/mongoose#11146]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Assume we have a schema with a unique index on a field.

Then, we have another schema that has an array of the other schema.

I try to save 2 elements of 'other schema' with the same array (e.g. empty arrays) and I get duplicate error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is an example:

```js
const mongoose = require('mongoose')

const childSchema = new mongoose.Schema({
  name: {
    type: String,
    unique: true,
  },
})

const fatherSchema = new mongoose.Schema({
  children: [childSchema],
  name: String,
})

const childModel = mongoose.model('child', childSchema)
const fatherModel = mongoose.model('father', fatherSchema)

async function main() {
  await mongoose.connect('mongodb://localhost:27017/bugtest')

  const child1 = new childModel({
    name: 'name1',
  })

  const child2 = new childModel({
    name: 'name2',
  })

  await child1.save()
  await child2.save()

  const father1 = new fatherModel({
    children: [],
    name: 'father1',
  })

  await father1.save()

  const father2 = new fatherModel({
    children: [],
    name: 'father2',
  })

  // This one fails
  await father2.save()
}

main()

```

This is the error:

```
UnhandledPromiseRejectionWarning: MongoServerError: E11000 duplicate key error collection: bugtest.fathers index: children.name_1 dup key: { children.name: null }
```

I think the problem is that a unique index on `children.name` is created automatically, hence when MongoDB finds 2 identical arrays, it marks them as the same.

**What is the expected behavior?**

No duplicate key error, since the unique field should only be on the 'child` schema and not on the array in the 'father' schema

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 12.21.0 
Mongoose: 6.1.2
MongoDB: 4.4

**Comment by thegoldgoat** [comment]
Maybe there is a 'correct' way to achieve what I was looking for (unique field in `childSchema.name` but not `fatherSchema.children`), please tell me if there is any :)

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/faq.html#unique-doesnt-work

**Comment by thegoldgoat** [comment]
Maybe, I am just guessing, the intended behavior was to propagate unique index for nested object but not for arrays, I will provide an example:

```js
const mongoose = require('mongoose')

const childSchema = new mongoose.Schema({
  name: {
    type: String,
    unique: true,
  },
})

const fatherSchema = new mongoose.Schema({
  onlyChild: childSchema,
  name: String,
})

const childModel = mongoose.model('child', childSchema)
const fatherModel = mongoose.model('father', fatherSchema)

async function main() {
  await mongoose.connect('mongodb://localhost:27017/oktest')

  const child1 = new childModel({
    name: 'name1',
  })

  const child2 = new childModel({
    name: 'name2',
  })

  await child1.save()
  await child2.save()

  const father1 = new fatherModel({
    onlyChild: child1,
    name: 'father1',
  })

  await father1.save()
  const father2 = new fatherModel({
    onlyChild: child1,
    name: 'father2',
  })
  // Fails here
  await father2.save()
}

main()

```

**Comment by thegoldgoat** [comment]
> https://mongoosejs.com/docs/faq.html#unique-doesnt-work

That should not be the problem, here the problem is that a `children.name` unique index is created. I am not sure _why_ this index is created

**Comment by IslandRhythms** [comment]
set `autoIndex` to false in the connection options. With mongoose 6, its default is true.

**Comment by thegoldgoat** [comment]
Thanks for the suggestion!

While I am sure it would work, it doesn't solve the problem that I am trying to address.

What I mean is that the `children.name` unique index should not be created inside `fathers` collection even if `autoIndex` was true.

The only index that should be created is `child.name` in the `children` collection.

Hope it makes sense, please tell me if I am missing anything

**Comment by IslandRhythms** [comment]
So the reason it does that is because you set `unique` on the `childSchema`. `fatherSchema` uses `childSchema` which has `unique` set to `true`.

> Mongoose doesn't handle unique on its own: { name: { type: String, unique: true } } is just a shorthand for creating a MongoDB unique index on name. 

As a result, the father collection will have that index.

**Comment by thegoldgoat** [comment]
Alright, thanks for the explanation, it makes sense now.

To conclude, let me ask just a couple more questions:

1) It looks like this behavior is expected. Should this be the correct behavior? In my opinion, as a mongoose user, it would make sense to disable unique index propagation for nested schemas, at least by default. But maybe I am missing that it could be helpful for other cases.

2) Considering the current behavior, what do you think is the most intelligent way to handle this scenario? The most obvious thing that comes to my mind is:

```js
const childSchema = new mongoose.Schema({
  name: {
    type: String,
    unique: true,
  },
})

const fatherSchema = new mongoose.Schema({
  children: [{
    name: String,
    _id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'children'
    }
  }],
  name: String,
})
```

Or maybe is there an option that prevents unique index propagation in `fatherSchema` ?

**Comment by IslandRhythms** [comment]
If you are using a ref, you don't need to have the name property in the children array. Just make sure when you create father documents you also insert the correct _id that references the child document. When you query for father documents, just populate the document and it will give you the name because it uses the _id to find that correct document. From the documentation, this would seem to be the correct behavior. I will now mark this as a feature request as it seems to be what you are asking for now.

**Comment by thegoldgoat** [comment]
> If you are using a ref, you don't need to have the name property in the children array

Yeah but my goal was to do avoid populate and do embedded instead for performance reasons.

See [here](https://stackoverflow.com/a/24096822)

**Comment by vkarpov15** [comment]
The behavior described in [original post](https://github.com/Automattic/mongoose/issues/11146#issue-1089452249) is expected. Mongoose builds indexes on nested schemas by default, so the below will create an index on `children.name`:

```javascript
const fatherSchema = new mongoose.Schema({
  children: [childSchema],
  name: String,
})
```

However, you can set the `excludeIndexes` option to prevent Mongoose from building indexes on an embedded schema:

```javascript
const fatherSchema = new mongoose.Schema({
  children: [{
    type: childSchema,
    excludeIndexes: true // <-- Avoid all indexes in `childSchema` when building indexes on the father model
  }],
  name: String,
})
```

You can also use `ref`, but you're right that embedding is generally faster.

**Comment by thegoldgoat** [comment]
> However, you can set the excludeIndexes option to prevent Mongoose from building indexes on an embedded schema

I think this is exactly what I was looking for. Thanks a lot!
