### ISSUE TITLE
TypeError: Cannot read property 'Decimal128' of null

### ISSUE THREAD

**Issue by khuongdv** [Automattic/mongoose#11143]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
It shows error when run with Jest, but when start server as normal, It still works
**If the current behavior is a bug, please provide the steps to reproduce.**

In test suit, I write a test that uses a model to create a new document. It says: 
"TypeError: Cannot read property 'Decimal128' of null"

**What is the expected behavior?**
It should insert new documents as normal when start in normal mode.

NOTE:
I use another way to insert data to db:
![image](https://user-images.githubusercontent.com/7438397/147415989-37e36fd1-c70d-4996-bc9c-4ffc56ec1df3.png)
But eventually when I test my API, it fails to use model to get the document and call "populate" function:
(fail here):
![image](https://user-images.githubusercontent.com/7438397/147416014-d0f15ed7-341c-4bee-8251-a11290f919c6.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v14.17.3
Mongoose: "^5.9.13"
MongoDB:  v4.4.3

I searched around but no source about this issue.

**Comment by khuongdv** [comment]
So, there are 2 cases the error message show:
1. Use modal to insert a document
2. Use the old way to insert documents but fail to use model to retrieve the nested data

**Comment by vkarpov15** [comment]
Please provide a standalone example that demonstrates the issue you're seeing.

Also, please make sure you carefully review our [Jest docs](https://mongoosejs.com/docs/jest.html). In general, we strongly recommend using any testing framework other than Jest.

**Comment by khuongdv** [comment]
I already used mocha instead, now it's fine. Thanks.
