### ISSUE TITLE
Does mongoose connect to secondary of replicas?

### ISSUE THREAD

**Issue by daveteu** [Automattic/mongoose#11157]
**Do you want to request a *feature* or report a *bug*?**
Question - I'm on a self hosted replica set and when I connected using mongodb+srv or mongodb://host:port,host2:port,host3:port string, ***does mongoose open connection to all servers of replica***?

When I use `readPreference=secondary` and i use `mongoose.on('connected')` as well as `mongoose.on('open')` events, it's only call once. When I view `mongoose.connection` I only can see my primary server hostname.

`mongoose.connection.replica` also return `false`. Mongoose doesn't seems to be connecting to my replica.

`on('fullsetup')` is also never emitted.

If I were to use MongoDB node driver, and I used mongodb native mongoclient.on('serverOpening'), I get 3 events emitted.

I'm using following code to connect to using mongoose
```
let options = {
  minPoolSize: 5,
  maxPoolSize: 50,
  readPreference: "secondary",
};

mongoose.connect("mongodb+srv://.....");
```
**Expected Behavior**

I'm expecting mongoose to connect to my replica set, write on my Primary, and read from my Secondary (w: majority).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^6.1.4"

**Comment by vkarpov15** [comment]
Mongoose does connect to all servers in a replica set. Not sure why you expect `mongoose.connection.replica` to be set or `'fullsetup'` to be emitted - AFAIK 'fullsetup' is not emitted in Mongoose 6 and no version of Mongoose has ever set the `replica` property.

**Comment by daveteu** [comment]
I was looking at this https://mongoosejs.com/docs/connections.html#connection-events

> fullsetup: Emitted when you're connecting to a replica set and Mongoose has successfully connected to the primary and at least one secondary.

So, since the replica property is available (it's set as false), I was thinking i am missing out on something.
