### ISSUE TITLE
[Suggestion] Small improvement for typed projection

### ISSUE THREAD

**Issue by jansedlon** [Automattic/mongoose#11156]
**Do you want to request a *feature* or report a *bug*?**
Suggest solution for a feature

**What is the current behavior?**
Projection is not typed at all

**What is the expected behavior?**
To be at least somehow typed

Hello. I'd like to propose a small improvement to have typed projection for the simplest cases. Talking about cases where you use `findById(id, { something: 1 })`, basically you just use `1` or `true`.

I would change the type definition of `find` queries to this

```ts
findById<
        Project = undefined,
        ResultDoc = Project extends undefined
          ? T
          : {
              [Key in keyof Project]: Project[K] extends 1
                ? T[Key]
                : Project[Key] extends true
                ? T[Key]
                : any;
            }
      >(
        id: any,
        projection?: Project | null,
        options?: QueryOptions | null,
        callback?: Callback<HydratedDocument<
          ResultDoc,
          TMethods,
          TVirtuals
        > | null>
      ): QueryWithHelpers<
        HydratedDocument<ResultDoc, TMethods, TVirtuals> | null,
        HydratedDocument<ResultDoc, TMethods, TVirtuals>,
        TQueryHelpers,
        ResultDoc
      >;
```

What it does is that if you decide to use the `project` parameter in `find` queries and you want to use simple selects, the result type will only include the properties that you selected. If it's not a simple select (eg `{ something: "$xx" }`), it would just return any.

what do you think?

Note: To use `1` instead of `true` means, that the project object would need to be marked as const.. like this `Model.findById(id, { name: 1 } as const)`

**Comment by vkarpov15** [comment]
I like the idea of allowing overriding the return type of a query, but I think the suggested API is not viable because (1) it is backwards breaking, and (2) doesn't support exclusive projections. Better to just allow `findById<Pick<User, 'name'>>(id, { name: 1 })`.
