### ISSUE TITLE
How to set default value with typescript

### ISSUE THREAD

**Issue by imranbarbhuiya** [Automattic/mongoose#11154]
**Do you want to request a *feature* or report a *bug*?**
It's a question or probably a feature request.

**What is the current behavior?**
Currently, I've a schema where date is default to Date.now. So it'll never be undefined. But when I'm defining its interface if I use,

```ts
date: number;
```

Then when I'm saving a doc it always shows I'm missing date and if I use 

```ts
date?:number
```

then when working with this model it shows date is possibly undefined. Currently, I'm using 

```ts 
// in interface
date?: number;

// when working with model
myModel.date as number
```
as a workaround, but what's the appropriate way to do this?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
There should be a way to work with default values.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v16.13.0
mongoose v6.1.4
mongodb v4.2.2
typescript v4.5.4

**Comment by IslandRhythms** [comment]
Modify the script below to show what you mean.

```typescript
import { Schema, model, connect, connection } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface User {
  name: string;
  email: string;
  avatar?: string;
  date?: number
}

// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String,
  date: {type: Number, default: Date.now()}
});

// 3. Create a Model.
const UserModel = model<User>('User', schema);

run().catch(err => console.log(err));

async function run(): Promise<void> {
  // 4. Connect to MongoDB
  await connect('mongodb://localhost:27017/test');
  await connection.dropDatabase();

  const doc = new UserModel({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await doc.save();

  console.log(doc);
}
```

**Comment by imranbarbhuiya** [comment]
```ts
import { Schema, model, connect, connection } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface User {
  name: string;
  email: string;
  avatar?: string;
  extraData: { address: string; date: number }[]
}

// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String,
  extraData: [{ address: String, date: { type: Number, default: Date.now() }]
});

// 3. Create a Model.
const UserModel = model<User>('User', schema);

run().catch(err => console.log(err));

async function run(): Promise<void> {
  // 4. Connect to MongoDB
  await connect('mongodb://localhost:27017/test');
  await connection.dropDatabase();

  const doc = new UserModel({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png',
    extraData: []
  });

 extraData.push({address: "address"});
// Property 'date' is missing in type '{ address: string; }' but required in type "MyInterface".
  await doc.save();

  console.log(doc);
}
```



If I make `date?:number` then when using this model

```ts

const doc = UserModel.findOne({
       name: "Bill"
});

if(doc){
doc.extrData.forEach((data)=>{
const time = data.date;
// here time will be number | undefined but in reality it'll be a number as it was set to default
})
```

**Comment by vkarpov15** [comment]
We currently recommend using `Types.Array<>` instead of `[]` for arrays in document interfaces:

```ts
import { Types, Schema, model, connect, connection } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface User {
  name: string;
  email: string;
  avatar?: string;
  extraData: Types.Array<{ address: string; date: number }>
}
```

See our docs on [schema arrays in TypeScript](https://mongoosejs.com/docs/typescript/schemas.html#arrays). Does that help?

**Comment by imranbarbhuiya** [comment]
> We currently recommend using `Types.Array<>` instead of `[]` for arrays in document interfaces:
> 
> ```ts
> import { Types, Schema, model, connect, connection } from 'mongoose';
> 
> // 1. Create an interface representing a document in MongoDB.
> interface User {
>   name: string;
>   email: string;
>   avatar?: string;
>   extraData: Types.Array<{ address: string; date: number }>
> }
> ```
> 
> See our docs on [schema arrays in TypeScript](https://mongoosejs.com/docs/typescript/schemas.html#arrays). Does that help?

It's working because there is no more validation. Now when I'm pushing an object in that array, I saw it's  `any` type.
![image](https://user-images.githubusercontent.com/74945038/148323198-9d50add5-d0ff-4774-9869-4c0ef405e95f.png)

So there is no validation, autocomplete. Are there any plan on proper type in future?

**Comment by vkarpov15** [comment]
`push()` should accept a `Partial` with Mongoose document arrays, because it is perfectly valid to `push()` an empty object and then add properties later.

```ts
doc.docArr.push({});

const subdoc = doc.docArr[doc.docArr.length - 1];
subdoc.address = 'test address';
subdoc.date = new Date();
```

**Comment by imranbarbhuiya** [comment]
yeah that makes sense. For pure array 
![image](https://user-images.githubusercontent.com/74945038/148629228-8a0d005d-9537-4bee-87b2-95d85b22cbfa.png)

Btw, Types.Array makes it any type, so ig that needs a fix.

**Comment by vkarpov15** [comment]
I took a closer look and `any[]` is correct for `Types.Array.push()`. Because of Mongoose type casting and change tracking, the below are perfectly valid:

```ts
interface User {
  oids: Types.Array<Types.ObjectId>[];
}

const user = new UserDoc({});

user.oids.push('000000000000000000000000'); // Perfectly fine to push a string, Mongoose casts it to ObjectId if possible
user.oids.push(user); // Perfectly fine to push a Document, Mongoose casts it to ObjectId

user.oids.push('fail'); // Push something invalid
user.oids[user.oids.length - 1] = new Types.ObjectId('000000000000000000000000'); // Overwrite the previous invalid oid, and now you can save

await user.save(); // Succeeds
```
