### ISSUE TITLE
Cannot populate array with discriminator

### ISSUE THREAD

**Issue by conduongtong** [Automattic/mongoose#11159]
I have a schema like this:
![image](https://user-images.githubusercontent.com/43648013/147745192-c6afccb8-2c8e-42d9-8c55-78faac6f73e4.png)

In content_sections, I create a discriminatorKey: 'type'
![image](https://user-images.githubusercontent.com/43648013/147744800-6cf2d656-4b31-457f-9c6c-38dbc758e50f.png)

And this schema for list_browse discriminator:
![image](https://user-images.githubusercontent.com/43648013/147744881-c47609e4-aa39-422f-9b1b-9bf084205288.png)

I try to populate with populate({ path: 'content_sections', populate: { path: 'items' } })
But it only populate items as object, not an array.

This is result:
items: { data: ... }
Expected:
items: [ { data: ...}, { data: ... } ]

Is this a bug or I'm missing something? Thank you

**Comment by IslandRhythms** [comment]
What does your query look like?

**Comment by conduongtong** [comment]
> What does your query look like?

const page = await Page.find({}).populate({ path: 'content_sections', populate: { path: 'items' }})

**Comment by IslandRhythms** [comment]
Please include everything you are using.

What does the `Discipline` model look like, what do all you interfaces look like, etc.
