### ISSUE TITLE
Mongoose 6: Deep-populate with string causing errors (undocumented breaking change?)

### ISSUE THREAD

**Issue by hansemannn** [Automattic/mongoose#11160]
I'm not sure if this may be documented as a breaking change somewhere, but I couldn't find it: When using a string-based populate, it fails with Mongoose 6 while it works with 5.x:
```js
await MyModel.findById(myId).populate({ path: 'subModel', populate: 'subField' });
```
The same works with brackets:
```js
await MyModel.findById(myId).populate({ path: 'subModel', populate: ['subField'] });
```
It's fine to migrate, but devs may not know it's an issue until they run a related query.

**Comment by IslandRhythms** [comment]
I'm reading the docs and I don't see a populate option in the populate function. What does the `populate` option do?

**Comment by mjfwebb** [comment]
I believe the changes are part of this note https://mongoosejs.com/docs/migrating_to_6.html#removed-execpopulate 

The note itself is poorly written. As you say there were more changes made to the way the `populate`  than just `execPopulate` being removed: chaining .populate calls was replaced by an array of populate paths. The same is true for nested populate paths like what you're attempting to do.

**Comment by hansemannn** [comment]
This is possible! If helpful, I can update the docs and draft a PR for it.
