### ISSUE TITLE
TypeError: doc.$__reset is not a function with save option validateBeforeSave: false

### ISSUE THREAD

**Issue by chenhuan001** [Automattic/mongoose#11163]
bug:
![image](https://user-images.githubusercontent.com/20589649/147816373-3eb73c21-96af-4b63-8173-a9d75fb6bcc9.png)

mongoose.version=5.13.12
nodejs version = v14.15.3
mongodb version = v5.0.3

run this simplification script ：
```
const mongoose = require('mongoose');
const connection = mongoose.createConnection("mongodb://127.0.0.1/test");

const schema1 = new mongoose.Schema({age: {type: Number}})
const schema = new mongoose.Schema({
  s1: {type: [schema1], default: []},
  })

UserModel = connection.model('user', schema);

if (true) {
  (async () => {
    let new_user = await UserModel.create({})
    await new_user.save()

    let user = await UserModel.findById(new_user._id, {s1: 1});

    user.s1[user.s1.length] = {age: 3}
    user.markModified('s1.'+(user.s1.length -1));

    await user.save({validateBeforeSave: false})
    console.log(user)

  })().catch((err) => console.error(err));
}
```

you will see this err:
![image](https://user-images.githubusercontent.com/20589649/147816373-3eb73c21-96af-4b63-8173-a9d75fb6bcc9.png)

when save option: validateBeforeSave is true, there is no error.
but validateBeforeSave will cause lots of validate calculate，this is unacceptable。

**Comment by IslandRhythms** [comment]
```javascript

const mongoose = require('mongoose');

const schema1 = new mongoose.Schema({age: {type: Number}})
const schema = new mongoose.Schema({
  s1: {type: [schema1], default: []},
  })

const UserModel = mongoose.model('user', schema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test');
    await mongoose.connection.dropDatabase();
    let new_user = await UserModel.create({})
    await new_user.save()

    let user = await UserModel.findById(new_user._id, {s1: 1});

    user.s1[user.s1.length] = {age: 3}
    user.markModified('s1.'+(user.s1.length -1));

    await user.save({validateBeforeSave: false})
    console.log(user)
    console.log('done');
}

run();
```

**Comment by chenhuan001** [comment]
> 
i run this code  and get the same error.
(same in linux and win10, 
and with my partner:
my partner has the same mongoose version and
nodejs version: v12.18.4
)
are you sure can't reproduce with same version mongoose :(

**Comment by IslandRhythms** [comment]
run `npm list | grep mongoose` and paste the output

**Comment by chenhuan001** [comment]
> run `npm list | grep mongoose` and paste the output

![image](https://user-images.githubusercontent.com/20589649/148024577-ae004cd4-7597-4adf-8797-5bdfa03930aa.png)

**Comment by IslandRhythms** [comment]
all of it

**Comment by chenhuan001** [comment]
> all of it

├─┬ mongoose@5.13.12
│ ├─┬ @types/bson@4.0.5
│ │ └── @types/node@15.12.2 deduped
│ ├─┬ @types/mongodb@3.6.20
│ │ ├── @types/bson@4.0.5 deduped
│ │ └── @types/node@15.12.2 deduped
│ ├── bson@1.1.6
│ ├── kareem@2.3.2
│ ├─┬ mongodb@3.7.2
│ │ ├─┬ bl@2.2.1
│ │ │ ├─┬ readable-stream@2.3.7
│ │ │ │ ├── core-util-is@1.0.3
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ ├── isarray@1.0.0 deduped
│ │ │ │ ├── process-nextick-args@2.0.1
│ │ │ │ ├── safe-buffer@5.1.2 deduped
│ │ │ │ ├── string_decoder@1.1.1 deduped
│ │ │ │ └── util-deprecate@1.0.2 deduped
│ │ │ └── safe-buffer@5.1.2 deduped
│ │ ├── bson@1.1.6 deduped
│ │ ├── denque@1.5.1 deduped
│ │ ├─┬ optional-require@1.1.8
│ │ │ └── require-at@1.0.6
│ │ ├── safe-buffer@5.1.2 deduped
│ │ └── saslprep@1.0.3 deduped
│ ├── mongoose-legacy-pluralize@1.0.2
│ ├── mpath@0.8.4
│ ├─┬ mquery@3.2.5
│ │ ├── bluebird@3.5.1
│ │ ├─┬ debug@3.1.0
│ │ │ └── ms@2.0.0
│ │ ├── regexp-clone@1.0.0 deduped
│ │ ├── safe-buffer@5.1.2 deduped
│ │ └── sliced@1.0.1 deduped
│ ├── ms@2.1.2 deduped
│ ├── optional-require@1.0.3
│ ├── regexp-clone@1.0.0
│ ├── safe-buffer@5.2.1
│ ├── sift@13.5.2
│ └── sliced@1.0.1

**Comment by AbdelrahmanHafez** [comment]
@IslandRhythms @chenhuan001 
Can you modify the test in [this commit](https://github.com/AbdelrahmanHafez/mongoose/commit/a9c8b2d192d11f97516b6c05117471d9b9c4a44c) to make it fail? It's [passing](https://github.com/AbdelrahmanHafez/mongoose/runs/4744768238?check_suite_focus=true) on all supported Node versions.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez that test should succeed in Mongoose 6, the issue is that it fails in Mongoose 5. The issue is that, when setting a document array index directly in Mongoose 5, Mongoose doesn't intercept the set and doesn't cast the subdoc.

```javascript
    user.s1[user.s1.length] = {age: 3} // <-- this is the problem, Mongoose doesn't cast
    user.markModified('s1.'+(user.s1.length -1));

    await user.save({validateBeforeSave: false}) // <-- the last element of `s1` is not a full Mongoose subdocument
```

The correct way to do this in Mongoose 5 is:

```javascript
    let user = await UserModel.findById(new_user._id, {s1: 1});

    user.s1.set(user.s1.length, {age: 3}) // <-- use `set()` to trigger casting and change tracking
    //user.markModified('s1.'+(user.s1.length -1));

    await user.save({validateBeforeSave: false})
    console.log(user)
```

Is there anything preventing you from upgrading to Mongoose 6 @chenhuan001 ?

**Comment by chenhuan001** [comment]
@vkarpov15 thank you for suggest correct way to do this in Mongoose 5，it work in simplification case now。
We will carefully evaluate whether we can upgrade to Mongoose 6。
