### ISSUE TITLE
$sort pipeline with Typescript: Type 'number' is not assignable to type '1 | -1 | { $meta: "textScore"; }'

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#11169]
### Discussed in https://github.com/Automattic/mongoose/discussions/11153

<div type='discussions-op-text'>

<sup>Originally posted by **raj-kumar94** December 29, 2021</sup>
Hi, I'm trying to sort using aggregation pipeline

```
{
    $sort: {
        created_at: -1
    }
},
```

but getting the following error

`Type 'number' is not assignable to type '1 | -1 | { $meta: "textScore"; }'`

Sorry if this is a newbie question. It was working fine earlier. I'm using version `6.1.4`

Thanks in advance.</div>

**Comment by manojsethi** [comment]
Facing the same issue on trying to upgrade from 5 to 6.

**Comment by matvienkont** [comment]
A possible workaround would be:
```
{
    $sort: {
        created_at: -1
    } as const
}
```
**as const** tells Typescript "created_at" will be exact literal value **-1**, not any other number value, i.e. 2, 3, 4...
I don't quite like it, but it works.

**Comment by twhy** [comment]
I don't get this error, but according to TypeScript handbook,
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-inference
code below also works
```typescript
{
    $sort: {
        created_at: -1 as -1
    }
}
```

**Comment by vkarpov15** [comment]
@matvienkont and @twhy are correct, because of literal inference TS doesn't trust that -1 won't change _unless_ you explicitly pass the object literal as a parameter:

```ts
// This causes "Type 'number' is not assignable to type 1 | -1
  const pipeline = [
    { $sort: { name: -1 } }
  ];
  await Test.aggregate(pipeline);
```

```ts
// Works
  await Test.aggregate([
    { $sort: { name: -1 } }
  ]);
```

You can also do `as const` as originally suggested.

We should keep this 1/-1 enforcement though, because MongoDB errors out when you pass something other than 1/-1 to `$sort`: `MongoServerError: $sort key ordering must be 1 (for ascending) or -1 (for descending)`. I'd prefer to allow `number`, but right now I think that 1/-1 is the way to go.
