### ISSUE TITLE
Nested schema issue in v6.1.4

### ISSUE THREAD

**Issue by huangxuewu** [Automattic/mongoose#11167]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**

node_modules\mongoose\lib\schema.js:952 Uncaught TypeError: Schema for array path `children` is from a different copy of the Mongoose module. Please make sure you're using the same version of Mongoose everywhere with `npm list mongoose`.

**If the current behavior is a bug, please provide the steps to reproduce.**

    import { Schema } from "mongoose"
    import conn from "../index"
    
    const childSchema = new Schema({ name: 'string' });
    
    const Chat = new Schema({
    // Array of subdocuments
    children: [childSchema],
    // Single nested subdocuments. Caveat: single nested subdocs only work
    // in mongoose >= 4.2.0
    child: childSchema
    });
    
    export default conn.model('Chat', Chat, 'chat');

`
    {
      "compileOnSave": false,
      "compilerOptions": {
        "resolveJsonModule": true,
        "baseUrl": ".",
        "outDir": "./dist/electron/main",
        "sourceMap": true,
        "declaration": false,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2020",
        "paths": {
          "@config/*": [
            "config/*"
          ],
          "@main/*": [
            "src/main/*"
          ],
          "@/*": [
            "src/renderer/*"
          ],
          "#/*": [
            "src/renderer/components/*"
          ]
        },
        "typeRoots": [
          "node_modules/@types"
        ],
        "lib": [
          "es2018",
          "dom"
        ]
      },
      "include": [
        "src/**/*",
        "types/*"
      ],
      "exclude": [
        "node_modules"
      ]
    }
`

**What is the expected behavior?**
should run without any error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v14.18.1  
mongodb 4.2.1

**Comment by IslandRhythms** [comment]
Works fine for me.
```javascript
const mongoose = require('mongoose');

const childSchema = new mongoose.Schema({
    name: String
});

const Chat = new mongoose.Schema({
    children: [childSchema],
    child: childSchema
});

const Test = mongoose.model('Test', Chat);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test');
    await mongoose.connection.dropDatabase();
    await Test.create({
        children: [{name: 'Array'}],
        child: {name: 'Single'}
    });

    console.log(await Test.find());
    console.log('done');
}

run();
```

**Comment by IslandRhythms** [comment]
> node_modules\mongoose\lib\schema.js:952 Uncaught TypeError: Schema for array path children is from a different copy of the Mongoose module. Please make sure you're using the same version of Mongoose everywhere with npm list mongoose.

From that error message it is telling you that you have different versions of mongoose installed. FInd and remedy the problem.

**Comment by huangxuewu** [comment]
I figured it out, this error was caused when i try to split file

i have file split like follow structure

 database/
      --- conn.ts
      --- model.ts
      --- schema/
               --- user.ts
               --- task.ts

so in the schema file i need to import Schema from mongoose for each file.

this error is not telling me that ia have different version of mongoose, it should actually states i have multiple instance of the Schema imported

**Comment by huangxuewu** [comment]
to fixed this error, just export the Schema in the conn file like

export const db = database;
export const mongoose = Mongoose;
export const Schema = Mongoose.Schema;
