### ISSUE TITLE
doc.isModified() wrong when _id: false and updated this way

### ISSUE THREAD

**Issue by johnpeb** [Automattic/mongoose#11172]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

`doc.isModified()` is incorrectly returning false when a subdocument is modified under an array with `_id` disabled and when the array is completely assigned to a value that is identical, but then later an array member is changed.

See REQUIREMENT 1 and REQUIREMENT 2 below. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the script below: `npx ts-node scripts/mongoose.ts`

Script.ts:
```
import { Schema } from 'mongoose';
import * as mongoose from 'mongoose'

run().catch(err => console.log(err));

async function run(): Promise<void> {
  await mongoose.connect('mongodb://localhost:27017/test', {
  });

  await mongoose.connection.dropDatabase();

  const Order = mongoose.model('Order', new Schema({
    cumulativeConsumption: [{
      _id: false, // REQUIREMENT 1 <<<<<
      unit: String,
      value: Number
    }]
  }));

  await Order.create({
    cumulativeConsumption: [{ unit: 'foo', value: 123 }, { unit: 'bar', value: 42 }]
  });

  const doc = await Order.findOne();
  doc.cumulativeConsumption = doc.toObject().cumulativeConsumption // REQUIREMENT 2 <<<<<
  // console.log(doc.modifiedPaths())
  const match = doc.cumulativeConsumption.find(o => o.unit === 'bar');
  match.value = 43;
  match.unit = 'baz'
  console.log(`Modified: ${doc.isModified()}, expecting true`)

  process.exit()
}
```

**What is the expected behavior?**

1. `modifiedPaths()` should reflect the change after the `  match.value = 43;` line
2. `isModified()` should be true after the  `match.value = 43;` line

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 6.1.4, node v12.22.7, mongo v4.2.8

**Comment by AbdelrahmanHafez** [comment]
Nice, thanks! 👍
