### ISSUE TITLE
`Model.populate()` does not mention the `populate` option

### ISSUE THREAD

**Issue by IslandRhythms** [Automattic/mongoose#11170]
I've seen a few scripts now of people using `populate` as an option in their `populate` functions. From what I can tell its another way to do a nested/chain populate however the docs don't mention it at all.

**Comment by twhy** [comment]
@IslandRhythms  I find this example in docs about the `populate` option at document level.
[Populating across multiple levels](https://mongoosejs.com/docs/populate.html#deep-populate)
https://mongoosejs.com/docs/populate.html#deep-populate
```javascript
User.
  findOne({ name: 'Val' }).
  populate({
    path: 'friends',
    // Get friends of friends - populate the 'friends' array for every friend
    populate: { path: 'friends' }
  });
```
