### ISSUE TITLE
Mongoose 6 - Too many connections

### ISSUE THREAD

**Issue by janantala** [Automattic/mongoose#11175]
Hello there,

I am getting too many connections warning after update to mongoose 6 from mongoose 5 on separate databases, using the latest version 6.1.4

![Screenshot 2022-01-04 at 09 07 12](https://user-images.githubusercontent.com/840789/148028385-8e841dbb-0ce1-45ea-a90e-e75299680b7b.png)
![Screenshot 2022-01-04 at 09 08 08](https://user-images.githubusercontent.com/840789/148028388-74d24e56-2ef2-4617-8112-14454d0dfeb2.png)

The number of connection will drop after app restart.

```
async function connect() {
  await mongoose.connect(config.db, {keepAlive: true});
}

mongoose.connection.on('error', err => {
    console.log('Mongoose default connection error', err);
});

try {
    connect();
} catch (err) {
    console.error('\x1b[31m', 'Could not connect to MongoDB!, err);
}
```

Do you have any idea why it is increasing?

Best regards,
Jan Antala

**Comment by sean-daley** [comment]
Could this be due to the maxPoolSize change that is listed here?
https://mongoosejs.com/docs/migrating_to_6.html#mongodb-driver-40

The mongodb driver changed the default from 10 -> 100. So if you don't set your own pool size maybe that's what you're hitting now (this change from 10 -> 100)?

**Comment by IslandRhythms** [comment]
How many connections do you have open? How many do you want to have open? How are you creating your connections? Do you close your connections after use or do you leave them hanging?
