### ISSUE TITLE
Improved `useDb()` docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#11187]
Right now all we have is API docs: https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb . Should have something more substantial for using `useDb()`, especially for multi tenant

**Comment by khairnarsaurabh23** [comment]
Can I work on this issue? 
Also can you please share some resources so I can contribute in better way.

**Comment by vkarpov15** [comment]
@khairnarsaurabh23 you're welcome to work on this issue. We don't have much in the way of other resources beyond what we already linked to, except for our tests and comments on GitHub issues.
