### ISSUE TITLE
mongoose v6 type definitions don't match up for array of object ids

### ISSUE THREAD

**Issue by lifeiscontent** [Automattic/mongoose#11194]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Type defs don't work as expected

**If the current behavior is a bug, please provide the steps to reproduce.**

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEQgYwK4gKYDsYA0cAymgBbYgCGRAKgJ5jYDORA8gEYBW2aMAkgBM4AXzgAzKBBBwARCAi4A5hAjNssgNwAobcHzYo4qmmwp0cbAA8YeQc3OYc+RNrgTVALjjMYUfUo67hxUUN4MTMwAdJw8fEIA2gC6mnAA9GlwAO7QANYOwOJw5FTK2MIwECTklFRRESwx3LwCgtoiumiKvnAhAF5wALxwuNhZcA3RsS1CABQAlDraXbg94qpDI2PVFNQAPKhoAHyzCG4eEN7EfgEE5yFhiHAwjNjeCaS7dZNNca1JREE2GMGAANjB3klRHcRIttEA

**What is the expected behavior?**

I'd expect using an array of Types.ObjectId for a document type to type check correctly for a schema.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Cartman720** [comment]
if I understood yout problem correctly, you should use `mongoose.Types.DocumentArray<YourDocument>`, default array type i.e. `YourDocument[]` doesn't have a merit for type checks in mongoose.

**Comment by mjfwebb** [comment]
According to [the mongoose SchemaTypes Array docs](https://mongoosejs.com/docs/schematypes.html#arrays) you probably want to define it as `bar: [{ type: [Schema.Types.ObjectId], default: [] }],` instead.

**Comment by lifeiscontent** [comment]
I've also tried using the Types.Array type in the demo I've provided and it still doesn't type check correctly.
