### ISSUE TITLE
mongodb@4.2.2 doesn't compile with latest Typescript node types `@types/node@17.0.6` or higher

### ISSUE THREAD

**Issue by sandersn** [Automattic/mongoose#11207]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Since Jan 1, Typescript projects that install `@types/node@17.0.6` or higher fail to compile because `mongodb@4.2.2`'s `GridFSBucketWriteStream` type has an old override of `Writable.end` from node. `mongodb@4.3` has the correct override, so mongoose should update to `mongodb@4.3`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ npm init
$ npm i mongoose
$ npm i -D @types/node
$ touch index.ts
$ tsc index.ts
```

```ts
// @filename: index.ts
import * as m from 'mongoose'
```

**What is the expected behavior?**
No errors.

** Tail of actual errors **

```
node_modules/mongodb/mongodb.d.ts:3314:5 - error TS2416: Property 'end' in type 'GridFSBucketWriteStream' is not assignable to the same property in base type 'WritableStream'.
  Type '{ (): void; (chunk: Buffer): void; (callback: Callback<void | GridFSFile>): void; (chunk: Buffer, callback: Callback<void | GridFSFile>): void; (chunk: Buffer, encoding: BufferEncoding): void; (chunk: Buffer, encoding: BufferEncoding, callback: Callback<...>): void; }' is not assignable to type '{ (cb?: () => void): this; (data: string | Uint8Array, cb?: () => void): this; (str: string, encoding?: BufferEncoding, cb?: () => void): this; }'.

3314     end(chunk: Buffer, encoding: BufferEncoding | undefined, callback: Callback<GridFSFile | void>): void;
         ~~~


Found 12 errors in 1 file.

Errors  Files
    12  node_modules/mongodb/mongodb.d.ts:3309
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 16.2.0 (but with `@types/node@17.0.8` installed)
mongoose: 6.1.6
mongodb: 4.2.2

**Comment by moritz157** [comment]
I think this is a duplicate of #11178. It has been fixed in PR #11188 which is supposed to be included in the 6.2 release of mongoose

**Comment by sandersn** [comment]
Yes, it's a duplicate. I looked at `main`'s package.json, not `6.2`'s.

**Comment by vkarpov15** [comment]
In the meantime, just enforce the correct `@types/node`. You should **not** be using `@types/node@17` if you're using Node.js 16, you should use `@types/node@16`

**Comment by sandersn** [comment]
Good general advice.

I found this bug via the Definitely Typed test infrastructure, which requires the latest version of everything in order to expose conflicts early. 16.2.0 is just my local version of node that I used for building a repro.
