### ISSUE TITLE
The change of discriminator key doesn't remove the properties not present in the new schema

### ISSUE THREAD

**Issue by Apokalypt** [Automattic/mongoose#11206]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When updating a document and changing the discriminator key, properties not present in the schema corresponding to the new discriminator key are kept if they are in the schema of the old discriminator key...  

**If the current behavior is a bug, please provide the steps to reproduce.**
```
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
    });

    await mongoose.connection.dropDatabase();

    const baseSchema = new Schema({}, { discriminatorKey: 'type' });
    const baseModel = mongoose.model('thing', baseSchema);

    const aSchema = new Schema(
        {
            aThing: { type: Number, required: true },
        },
        { _id: false, id: false },
    );
    const aModel = baseModel.discriminator('A', aSchema);

    const bSchema = new Schema(
        {
            bThing: { type: String, required: true },
        },
        { _id: false, id: false },
    );
    const bModel = baseModel.discriminator('B', bSchema);

    // Model is created as a type A
    const doc = await baseModel.create({ type: 'A', aThing: 1 });
    const doc2 = await baseModel.create({ type: 'B', bThing: 'one' });

    await baseModel.findByIdAndUpdate(
        doc._id,
        { type: 'B', bThing: 'two' },
        { runValidators: true, overwriteDiscriminatorKey: true, new: true },
    );
}
```
With the code above, the new document will be :
```
{ "type": "B", "__v": 0, "aThing": 1, "bThing": "two" }
```
instead of :
```
{ "type": "B", "__v": 0, "bThing": "two" }
```

**What is the expected behavior?**
Properties not present in the schema of the new discriminator key should be removed

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 16.11.0
Mongoose: 6.1.5
MongoDB: 5.0.5

**Comment by IslandRhythms** [comment]
isn't doc's new value suppose to be `bThing: two`? Also, You need to call `create()` on the discriminator model. So for the result you want it would be

```javascript
await bModel.create({...})
await bModel.findByIdAndUpdate({...})
```

**Comment by Apokalypt** [comment]
> isn't doc's new value suppose to be `bThing: two`? Also, You need to call `create()` on the discriminator model. So for the result you want it would be
> 
> ```js
> await bModel.create({...})
> await bModel.findByIdAndUpdate({...})
> ```

Error on my part, indeed it is well "two" and not "one" bad copy of my part...
I don't want to create a new document. I want to create a document respecting the AThing schema and then after some time I want to modify this document and its type so that it is a document of the BThing schema (so I don't want any more the properties corresponding to the AThing schema)

**Comment by IslandRhythms** [comment]
So you only want to return properties that were modified

**Comment by Apokalypt** [comment]
> So you only want to return properties that were modified?

Not really.
In fact, I would like that, when I change the value of the discrimination key, only the values corresponding to the new schema (in this piece of code, the bSchema schema) is kept. So, in this little code, when I call "findByIdAndUpdate" I would like the "aThing" property to be removed from the document because it is not in the bSchema schema.
