### ISSUE TITLE
Model.deleteMany() and Model.deleteOne() does not return acknowledged

### ISSUE THREAD

**Issue by benghaun** [Automattic/mongoose#11211]
**Do you want to request a *feature* or report a *bug*?**
This is a bug - or perhaps just inconsistent documentation, I'm not entirely sure which is it.

**What is the current behavior?**
When calling `Model.deleteMany()` (or `Model.deleteOne()`), the return result is `{ deletedCount: 1 }`, and doesn't have the `acknowledged` property. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply call `Model.deleteMany()` on any model and observe the result. Sample script below:
```
const mongoose = require('mongoose');

mongoose.connect('mongodb://127.0.0.1:27017', {});

const TestModel = mongoose.model('Test', {
  test: { type: String },
});

const main = async () => {
  console.log('running main');
  const result = await TestModel.deleteMany({});
  console.log(result); // logs { deletedCount: 0 }
};

main()
  .then(() => {
    process.exit(0);
  })
  .catch(err => console.log(err));

```

**What is the expected behavior?**
The [v6 migration guide](https://mongoosejs.com/docs/migrating_to_6.html#mongodb-driver-40) states that the result of `deleteMany` should have both the `acknowledged` property and the `deletedCount` property. This is consistent with the TypeScript definitions, which indicate that the result of the deleteMany operation has both `deletedCount` and `acknowledged`. 

However, the [deleteMany API documentation](https://mongoosejs.com/docs/api/model.html#model_Model.deleteMany) states that only `deletedCount` is returned, which is consistent with the implementation.

If the intention is to not include `acknowledged`, then the migration guide and the TypeScript definitions should be updated. If the intention is to include `acknowledged`, then the implementation and the API documentation should be updated.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v14.17.5
Mongoose: v6.1.6
MongoDB: 4.0.22

**Comment by Uzlopak** [comment]
Well I think it is not wrong. 

https://docs.mongodb.com/manual/reference/write-concern/#j-option

So you have to specify the j-option to get the acknowledgement.
