### ISSUE TITLE
Bug: not compiling with tsc due to outdated mongodb dependency

### ISSUE THREAD

**Issue by karlbeecken** [Automattic/mongoose#11215]
Using mongoose 6.1.6, I get the error described [here](https://stackoverflow.com/questions/70607218/error-importing-mongodb-with-typescript). As described in the post, upgrading the dependency to mongodb^4.3.0 fixes the issue, but the current version of mongoose (6.1.6) is pinned to mongodb@4.2.2, which still includes the error. My suggestion would be to bump the dependency to the new mongodb version.

**Comment by hasezoey** [comment]
> Using mongoose 6.1.6, I get the error described here.

current workaround is to pin the version of `@types/node` to a version that does not have the breaking change yet

**Comment by vkarpov15** [comment]
What is your version of `@types/node`? Make sure you pin `@types/node` to a version that's `< 17.0.6`, the DefinitelyTyped team introduced a massive breaking change in 17.0.6 that's been causing some trouble. We'll release Mongoose 6.2.0 with mongodb@4.3 within the next week or so.
