### ISSUE TITLE
Concurrent bulkSave not work properly with  Promise.all

### ISSUE THREAD

**Issue by wunderb1t** [Automattic/mongoose#11217]
**Report a *bug.***

**Current behavior.**
Suppose we have 10k items, to reduce save time, we are trying to split all items into several portions, i.e. 1k and for each create `bulkSave` promise, then execute all this promises via `Promise.all`. So, such way run multiple bulk save queries in parallel, see `bulkSaveTest` method in code snippet. 

But it seems that all queries run sequentially, i.e. all queries execution times are summing.  Looks like "trains problem".   

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

// Create connection.
mongoose.connect(mongoConfig.server, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    authSource: 'my_authSource',
    user: 'my_username',
    pass: 'my_password',
});

let db = mongoose.connection;
db.on('error', (err) => {
    global.logger.error(`Mongoose: ${err}`);
});
db.once('open', async () => {
    global.logger.info("Mongoose: Connected to DB.");
});

// Create model.
class TestModel {
    static _instance;
    _model;

    /**
     * @private
     */
    constructor() {}

    static create() {
        if (this._instance) {return this._instance;}
        this._instance = new this();

        // Schema.
        let testSchema = new mongoose.Schema({
            name: String,
            timestamp: String
        }, { versionKey: false });

        this._instance._model = mongoose.model('test', testSchema);

        return this._instance;
    }

    async insertTests() {
        const docsMaxSize = 10000;
        const docs = [];

        // Delete prev. docs.
        await this._model.deleteMany({});

        for (let i = 0; i < docsMaxSize; i++) {
            docs.push({name: `${i}`, timestamp: Date.now()});
        }

        try {
            await this._model.insertMany(docs);
        }
        catch (err) {
            throw err;
        }
    }

    async getAll() {
        return await this._model.find({});
    }

    async bulkSaveTest(docs) {
        const portionMaxLength = 1000;
        const docsLength = docs.length;

        let portion = [];
        let cnt = 0;
        let promises = [];

        for (let doc of docs) {
            cnt++;
            portion.push(doc);

            if ((portion.length % portionMaxLength === 0) || docsLength === cnt) {
                promises.push(this._model.bulkSave(portion));
                portion = [];
            }
        }

        let start = Date.now();

        // !!! Not running in parallel.
        await Promise.all(promises);

        // !!! High delay.
        console.log(`End ${Date.now() - start} ms`);
    }

}

// Start Test.
const testModel = TestModel.create();

async function test() {
    await testModel.insertTests();
    let docs = await testModel.getAll();
    await testModel.bulkSaveTest(docs);
}

test();
```

**What is the expected behavior?**
`Promise.all(promises)` execution time must be equal approx. to single `bulkSave` promise execution. 
According to documentation, default `maxPoolSize` is `100`, but it seems not working.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS: v13.14.0
Mongoose: ^6.1.6
MongoDB: Docker image: mongo: 4.2

**Comment by vkarpov15** [comment]
As written, your example won't run in parallel because there's nothing to save. Since none of the documents are modified, `this._model.bulkSave(portion)` is a no-op. Since there's nothing sent to MongoDB, you don't really get much benefit from `Promise.all()`.

Try the below `bulkSaveTest()` instead:

```javascript
    async bulkSaveTest(docs) {
        const portionMaxLength = 10000;
        const docsLength = docs.length;

        let portion = [];
        let cnt = 0;
        let promises = [];

        for (let doc of docs) {
            doc.name = 'test' + Math.random();
            cnt++;
            portion.push(doc);

            if ((portion.length % portionMaxLength === 0) || docsLength === cnt) {
                promises.push(this._model.bulkSave(portion));
                portion = [];
            }
        }

        let start = Date.now();

        await Promise.all(promises);

        console.log(`End ${Date.now() - start} ms`); // If portionMaxLength = 10k, prints ~554ms on my machine. If portionMaxLength = 1k, prints ~404ms
    }
```

Keep in mind that you do hit a point of diminishing returns, where more parallelization will make the `bulkSave()` slower, not faster. For example, in the above code, `portionMaxLength = 100` is slightly slower than `portionMaxLength = 1000`, even though both are still significantly faster than `portionMaxLength = 10k`. I'm not 100% sure why, but that isn't terribly surprising given that there's still some sync code running that can't benefit from parallelization and increased thread competition on the MongoDB server.
