### ISSUE TITLE
Random "MongoServerSelectionError", reason : "ReplicaSetNoPrimary"

### ISSUE THREAD

**Issue by ErnestBrandi** [Automattic/mongoose#11228]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
I occasionally get the following error 
```
{
   "errorType":"Runtime.UnhandledPromiseRejection",
   "errorMessage":"MongoServerSelectionError: connection timed out",
   "reason":{
      "errorType":"MongoServerSelectionError",
      "errorMessage":"connection timed out",
      "reason":{
         "type":"ReplicaSetNoPrimary",
         "servers":{
            
         },
         "stale":false,
         "compatible":true,
         "heartbeatFrequencyMS":10000,
         "localThresholdMS":15,
         "setName":"atlas-5kkpk0-shard-0",
         "maxSetVersion":1,
         "maxElectionId":"7fffffff0000000000000016",
         "commonWireVersion":9,
         "logicalSessionTimeoutMinutes":30
      },
      "stack":[
         "MongoServerSelectionError: connection timed out",
         "    at Timeout._onTimeout (/var/task/node_modules/mongodb/lib/sdam/topology.js:330:38)",
         "    at listOnTimeout (internal/timers.js:557:17)",
         "    at processTimers (internal/timers.js:500:7)"
      ]
   }
```
It seems similar to this issue https://github.com/Automattic/mongoose/issues/11200, but I had that problem before switching from v5 to v6.

I use Next.js hosting on Vercel, so I use Lambda functions. I connect with the script `dbConnect` from the official Next.js repo `with-mongodb-mongoose`. 

Also, this happens for different endpoints.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJs : 14.x
Mongoose : 6.1.6
MongoDB : Mongoose dependency

**Comment by vkarpov15** [comment]
Without more code samples, not really possible for us to try to repro this. Same stack trace as #11200, but the stack trace doesn't help much because we get the same stack trace from just about any MongoDB operation that times out.

One potentially useful bit of info: did you omit the contents of the `reason.reason.servers` property, or is it empty in your logs?

**Comment by ErnestBrandi** [comment]
@vkarpov15 nope the `reason.reason.servers` field is always empty in my case.

**Comment by vkarpov15** [comment]
Worth noting: based on your comment, you aren't using Mongoose. `cached.conn.connection.getClient()` returns a MongoDB Node driver `MongoClient` instance, so `req.dbClient` is a `MongoClient`.

We'll take some time to set up an example with Next hosting and see if we can repro this.

**Comment by vkarpov15** [comment]
I set up a Vercel GitHub repo and deployed it: https://github.com/vkarpov15/with-mongodb-mongoose-3 , a quick check shows no errors:

![image](https://user-images.githubusercontent.com/1620265/160261819-355c2ccb-a5be-4d42-b422-8afa479df943.png)

Without more complete code samples, there isn't really much we can do to repro this. I suggest you:

1. Take a look at Mongoose's AWS Lambda docs: https://mongoosejs.com/docs/lambda.html
2. Add some [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware) to drill down what might be causing this error using something like the below code

```javascript
  // Handle errors on save, etc.
  schema.post(/.*/, { document: true, query: false }, function(err, res, next) {
    console.log('Error on document op:', this.$op, this.model.modelName);
    console.log(err);

    next(err);
  });
  // Handle errors on find, findOne, etc.
  schema.post(/.*/, { document: false, query: true }, function(err, res, next) {
    console.log('Error on query:', this.model.modelName, this.op);
    console.log(err);

    next(err);
  });
```

For example, if I shut down my local MongoDB server before a `findOne()` starts, the above middleware will print out:

```
Error on query: Test findOne
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Single',
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9,
    logicalSessionTimeoutMinutes: undefined
  }
}
```

This can at least point you in the direction of where in your code this error is coming from.

**Comment by stevek-pro** [comment]
Maybe a network or security group problem?
