### ISSUE TITLE
Redundant null check on object

### ISSUE THREAD

**Issue by dadwalakshay** [Automattic/mongoose#11223]
BUG

**What is the current behavior?**
There's a redundant null check on variable at [this line](https://github.com/Automattic/mongoose/blob/master/lib/document.js#L76), after checking type of variable as 'object'

**What is the expected behavior?**
It should perform the null check first, and if it passes null check then perform type check.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs: 14.18.2
Mongoose: 6.1.6

**Comment by vkarpov15** [comment]
Why is this check redundant? Remember that `typeof null === 'object'` in JavaScript, so you need to check `!= null` to make sure you can access the value's properties.

**Comment by Uzlopak** [comment]
Should be rejected, as discussed in the PR.
