### ISSUE TITLE
Types.ObjectId.isValid misbehavior

### ISSUE THREAD

**Issue by Josh-Chang** [Automattic/mongoose#11226]
Yes, 

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
import { Types } from 'mongoose';
logger.info('Rheumatology =', Types.ObjectId.isValid('Rheumatology'));
logger.info('ObAIoT =', Types.ObjectId.isValid('ObAIoT'));
logger.info('最新研究新知 =', Types.ObjectId.isValid('最新研究新知'));
=>
![image](https://user-images.githubusercontent.com/40685404/149494111-34de4ff7-97d9-4106-95fa-2c163f2fa361.png)
 
=> the string 'Rheumatology' is a valid ObjectId

**If the current behavior is a bug, please provide the steps to reproduce.**

as above

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/40685404/149494344-100da089-1639-4db2-b25c-35ac62e02d25.png)
=> the string 'Rheumatology' shall not be a valid ObjectId

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
  Node: v16.13.1
  mongoose: 6.0.6

**Comment by Maximusya** [comment]
May I humbly invite you to a party => https://github.com/Automattic/mongoose/discussions/11221

**Comment by vkarpov15** [comment]
Any 12 character string can be converted to a MongoDB ObjectId, because technically any sequence of 12 bytes is a valid ObjectId. If you want to test that a string is 24 hex chars, you should do `/^[0-9A-Fa-f]{24}$/.test(str)`

**Comment by Josh-Chang** [comment]
Instead we use npm package "validator"
It works out well. 

validator.isMongoId(id_string)
