### ISSUE TITLE
Pluralize issue: 'feedback' -> 'feedbacks'

### ISSUE THREAD

**Issue by rubek-joshi** [Automattic/mongoose#11225]
Title itself is pretty explanatory. The word 'feedbacks' doesn't exist in the dictionary.

**Comment by vkarpov15** [comment]
[Depends on the dictionary](https://en.wiktionary.org/wiki/feedbacks#English). Either way, you can overwrite the pluraization as shown below.

```javascript
mongoose.model('Feedback', schema, 'feedback'); // If you don't want "feedbacks"
```

We generally don't modify pluralization between major releases, so we're going to close this for now.
