### ISSUE TITLE
@types/node is now dependency.

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11237]
Seems like a mistake? Should be imho a devDependency

**Comment by vkarpov15** [comment]
No, it is intentional. `@types/node` is an upstream dependency via `mongodb`, we list it as a dependency to avoid versions of `@types/node >= 17.0.6`, which have a backwards breaking change that isn't compatible with Mongoose 6.1.

**Comment by Uzlopak** [comment]
Can you please link the original issue. I would like to have a look at it.

Can you please reopen this issue? I would close it, if I can not come up with a better solution.

**Comment by vkarpov15** [comment]
Didn't have an original issue, our tests just started failing: https://github.com/Automattic/mongoose/runs/4686998575?check_suite_focus=true although there have been a few issue reports, like #11207, #11215, #11178, etc.

The solution is to upgrade to `mongodb@4.3` and then remove the dependency. We already upgraded in 6.2 branch and removed the dep, so this will be fixed when we release 6.2.
