### ISSUE TITLE
How to share the connection pool across multiple databases

### ISSUE THREAD

**Issue by seasonhuang** [Automattic/mongoose#1124]
In node-mongodb-native, I can share the connection pool across multiple databases:

<code>
var mongodb = require("mongodb"),
    mongoserver = new mongodb.Server(host, port, server_options),
    db_connector = new mongodb.Db(name, mongoserver, db_options);

db_connector.open(callback);
</code>

And then I use <code>db_connector.db(name)</code>, this returns a new db instance that shares the connections off the previous instance but will send all commands to the database name . This allows for better control of resource usage in a multiple database scenario.

HOW CAN I DO THIS IN MONGOOSE?

**Comment by memelet** [comment]
@boashan, Have you found any way to use mongoose for your use case. In our case we have hundreds of tenants that all use the same schema. If I understand from the above, the proposed solution is to create thousands of models then cache them myself somehow?

**Comment by manast** [comment]
@memelet Yes, we have been running with this solution for a few months now. we have like max 10 tenants so there has not been any performance issue. Basically what you need to do is this:
```javascript
  var db = mongoose.createConnection(uri);
  db.Schema = mongoose.Schema;
```
So it requires a new mongoose connection, unless mongoose multiplexes the connection it will result in several connections to mongodb, but still, having a few hundreds should be feasible, connections are not that expensive anyways.

**Comment by manojsethi** [comment]
@manast Can you please provide a little detailed example or if you have found any better approach now?
