### ISSUE TITLE
Connection keeps timing out on version 6.1.6

### ISSUE THREAD

**Issue by MuhammedAO** [Automattic/mongoose#11251]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I can't seem to connect to mongDB atlas. mongoose times out abruptly ever since i updated to v6

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const connectDB = async () => {
  try {
    const conn = mongoose.connect(process.env.MONGO_CONNECTION_URI!, {});
    console.log(`database connected: ${(await conn).connection.host}`);
  } catch (error: any) {
    console.log(error.message || error);

    // process.exit(1);
  }
};
```

**What is the expected behavior?**
No timing out

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v16.13.0, mongoose V6.1.6

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.connection.on('connected', () => {
    console.log('connnected');
});

mongoose.connection.on('error', () => {
    console.log('error');
});

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
}

run();
```

**Comment by daveteu** [comment]
You may want to use mongodb://host:port,host:port,host:port instead of mongodb+srv string. it could be a problem of mongodb+srv string not being resolved (happens recently)

**Comment by vkarpov15** [comment]
@MuhammedAO I agree with @daveteu . Try using the non-srv form of the connection string.
