### ISSUE TITLE
Leaking sessions

### ISSUE THREAD

**Issue by morkai** [Automattic/mongoose#11256]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
MongoDB sessions created by using `mongoose.connection.transaction()` aren't cleaned up, resulting in the memory leaking:

![image](https://user-images.githubusercontent.com/301053/150689360-428a4824-014b-48ae-b240-5f7af7639d11.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const mongoose = require('mongoose');

mongoose.model('Test', new mongoose.Schema({}));

async function main()
{
  await mongoose.connect('mongodb://127.0.0.1:27017/test');
  
  setTimeout(leak, 1000);
}

async function leak()
{
  await mongoose.connection.transaction(async session =>
  {
    await mongoose.model('Test').findOne().session(session).exec();
  });
  
  console.log(
    new Date().toISOString(),
    'sessions =',
    mongoose.connection.client.topology.s.sessions.size
  );
  
  setTimeout(leak, 1000);
}

main();
```

```
$ node leak.js
2022-01-23T17:14:16.521Z sessions = 1
2022-01-23T17:14:17.542Z sessions = 2
2022-01-23T17:14:18.555Z sessions = 3
2022-01-23T17:14:19.563Z sessions = 4
2022-01-23T17:14:20.580Z sessions = 5
2022-01-23T17:14:21.603Z sessions = 6
2022-01-23T17:14:22.621Z sessions = 7
2022-01-23T17:14:23.631Z sessions = 8
2022-01-23T17:14:24.645Z sessions = 9
2022-01-23T17:14:25.662Z sessions = 10
...
```

**What is the expected behavior?**
`mongoose.connection.transaction()` should call `session.endSession()` so the session is cleaned up.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v16.13.2
mongoose v6.1.7
mongodb server v5.0.5 driver v4.3.0

**Comment by Uzlopak** [comment]
Created a PR #11259
