### ISSUE TITLE
Emptying and then adding to an array does not work correctly

### ISSUE THREAD

**Issue by taxilian** [Automattic/mongoose#1126]
Given the following file:

```
var mongoose = require("mongoose");
var Schema      = mongoose.Schema,
    ObjectId    = Schema.ObjectId;

var Test = new Schema({
    name: String,
    schools : [ String ]
});

var TestM = mongoose.model("Test", Test);

mongoose.connect("localhost", "testdb");

mongoose.connection.collection("tests").drop(function() {
    var t = new TestM();
    t.name = "Stuff!";
    t.schools = ["asdf", "fdsa"];

    t.save(function(err) {
        if (err) {
            console.log("Error: ", err);
        }
        TestM.find({name: "Stuff!"}).findOne(function (err, t) {
            t.schools = [];
            t.schools.push("zzzb");
            t.save(function() {
                TestM.find({name: "Stuff!"}).findOne(function (err, nt) {
                    console.log(nt);
                    mongoose.disconnect();
                });
            });
        });
    });
});
```

You would expect the final result to contain an array with schools: ["zzzb"] but what you actually get is an array with three values; the two old values and the new value. Instead of replacing the contents of the array it appends the new array to the old one.

This is a really big problem for us because it makes it very difficult to change a list; in order to make it work we have to either save the document with an empty array before making changes or build the new array in its entirety before setting it.  This isn't always practical and involves some pretty weird behavior to reproduce.

This effects 3.2.0 and all earlier tested versions (for sure 3.1.2 but the 2.x versions had the same issue)

**Comment by lineus** [comment]
@jackson-elfers what version of mongoose are you using? 

When I run the OP's original example on @5.2.13 ( **with an updated connection** ) I get the expected results by default:

### 1126.js
```js
#!/usr/bin/env node
'use strict';

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var Test = new Schema({
  name: String,
  schools: [String]
});

var TestM = mongoose.model('Test', Test);

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });

mongoose.connection.collection('tests').drop(function () {
  var t = new TestM();
  t.name = 'Stuff!';
  t.schools = ['asdf', 'fdsa'];

  t.save(function (err) {
    if (err) {
      console.log('Error: ', err);
    }
    TestM.find({ name: 'Stuff!' }).findOne(function (err, t) {
      t.schools = [];
      t.schools.push('zzzb');
      t.save(function () {
        TestM.find({ name: 'Stuff!' }).findOne(function (err, nt) {
          console.log(nt);
          mongoose.disconnect();
        });
      });
    });
  });
});
```
### Output: 
```
issues: ./1126.js
{ schools: [ 'zzzb' ],
  _id: 5b91099e8b23cc0cc7c515ca,
  name: 'Stuff!',
  __v: 1 }
issues:
```

**Comment by jackson-elfers** [comment]
@lineus Just tried your example, looks like it's working fine. I was running at @5.2.7 although I scrapped whatever I was doing there for something entirely different. Could've been something strange I was doing thanks for the feedback.
