### ISSUE TITLE
Modify Issue Template and provide template for a mvce

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11260]
Inspired by #11256 it would make sense to provide a template for providing code examples

Here my proposal:
https://github.com/Uzlopak/mongoose-mvce/

If you want I would write a simple Readme.md and then you could move it to Automattic Organisation. 

Also the Issue template is kind of text-heavy. Look e.g. how we did it in fastify/busboy
https://github.com/fastify/busboy/issues/new/choose

You could e.g. recommend to fork or clone mongoose-mvce and then in the issue form, you would ask for the link to the mvce. 

Then you could just clone the mvce and run local and verify the bug

**Comment by vkarpov15** [comment]
Works for me. We don't have access to the Automattic org unfortunately, so couldn't really move it there, but could transfer to https://github.com/mongoosejs
