### ISSUE TITLE
Cannot populate path `comments` because it is not in your schema. Set the `strictPopulate` option to false to override.

### ISSUE THREAD

**Issue by AdhavanHariharan** [Automattic/mongoose#11277]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AdhavanHariharan** [comment]
const ticketsSchema = new Schema({
    referenceId: {
        type: String
    },
    description : {
        type: String
    },
    title : {
        type: String
    },
    createdAt: {
        type: Number,
    },
    updatedAt: {
        type: Number,
    },
    createdBy: {
        type: Schema.Types.ObjectId,
        ref: 'user'
    },
    status: {
        type: String,
        enum : ['open','pending','closed'],
        default : 'open'
    },
    seen: [{
        by:{
            type: Schema.Types.ObjectId,
            ref: 'user'
        },
        at: {
            type: Number,
        },
        _id: false
    }],
    comments : [{
    message: {
        type: String
    },
    commentedBy: {
        type: Schema.Types.ObjectId,
        ref: 'users'
    },
    commentedAt : {
        type: Number,
    },
    images : [imagesSchema]
},{
    strict: false,
    versionKey: false
}],
    images: [imagesSchema]
}, {
    strict: false,
    versionKey: false
});

This is the schema for the above issue

**Comment by AdhavanHariharan** [comment]
Found out the issue.

**Comment by Capta1nRaj** [comment]
> Found out the issue.

Please tell, facing same issue for last 6 hours.
