### ISSUE TITLE
Replace typescript tests with tsd

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11286]
It is quite annoying that you have to symlink mongoose to run the typescript tests. Also they take very long. Also we had issues with having to add @types/node to maybe get it transpiled. 

To avoid this overhead, I recommend to replace the typescript tests with tests, which only checks the typings, like tsd does.

It would be faster and we could test it more granular.

**Comment by vkarpov15** [comment]
Thanks, I didn't know that tsd existed: https://www.npmjs.com/package/tsd

I agree the tests as written are slow and clunky. The reason why we wrote them the way we did was this was the best way we could come up with to write tests where we could assert that TypeScript compilation fails with a certain error. tsd should make this better.

**Comment by Uzlopak** [comment]
Closing in favor of #11312
