### ISSUE TITLE
Unknown unhandled promise rejections

### ISSUE THREAD

**Issue by CodeWithOz** [Automattic/mongoose#11287]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
I'm seeing my node process terminate unexpectedly when some mongoose operations are ongoing. The error is `Uncaught UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by...`. It's not always consistent where it happens but more frequently it's inside `bulkWrite` operations. This seems to be a faulty promise handler, but I've tried stepping through mongoose internals and I can't find the problem. It also doesn't get caught by vscode's breakpoint for uncaught exceptions, so it's hard to know more about the problem.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sadly reproducing it is a problem because it's not consistently happening.

**What is the expected behavior?**
Mongoose operations, particularly `bulkWrite` operations, proceed without unnecessary/unexpected interruptions.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 16.13.1
mongoose: 6.1.6
mongodb: 4.3.0

**Comment by IslandRhythms** [comment]
Can you provide what you're doing when doing the `bulkWrite()` operation? Schema set up, options, what you're doing before and after the call,  etc.

**Comment by Uzlopak** [comment]
List on the unhandled promise rejection event on process and store somewhere the error stack. Then we can actually see where the error happens.
