### ISSUE TITLE
$addToSet misbehave - missing docs/information about behavior  

### ISSUE THREAD

**Issue by dor-benatia** [Automattic/mongoose#11284]
i've stumbled across a weird problem with mongoose $addToSet in patch function,

i am running this code :

    const y = await model.updateOne(
        { _id: '61e0327e3889426f21dbbe25' },
        {
            $addToSet: { links: ['test1', 'test2', 'test3'] },
        },
    );
when looking at the object in the db i see links: ['a','b',test1', 'test2', 'test3' ] which correspond to $addToSet with $each operator as explained in these docs: https://docs.mongodb.com/manual/reference/operator/update/addToSet/#value-to-add-is-an-array

which should of added this array as single element.

I am seeing in the code the corresponding line that caused that : `lib/types/array/ArrayWrapper.js` line 82.

The thing is that it is written *no-where* in the docs, not even a one liner.

maybe i am missing something ? 

mongoose version: 6.0.13

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: []
});

const Test = mongoose.model('Test', testSchema);

async function run() {
await mongoose.connect('mongodb://localhost:27017');
await mongoose.connection.dropDatabase();

const entry = await Test.create({
    name: [1,2,3,4,5]
});

console.log(entry);

await Test.findOneAndUpdate({_id: entry._id}, {$addToSet: {name: [6,7,8,9,0]}});
console.log(await Test.find());
}

run();
```

**Comment by dor-benatia** [comment]
@IslandRhythms - this is exactly the code the reveal the problem - thank you.

**Comment by twhy** [comment]
What if there's code mistakenly rely on this misbehavior?

**Comment by vkarpov15** [comment]
Right now, the way that Mongoose handles this case is that it adds `$each` _unless_ you're using `$addToSet` on a nested array path. For example, the below code doesn't add `$each` because `name` is a nested array.

```javascript
const mongoose = require('mongoose');

mongoose.set('debug', true);

const testSchema = new mongoose.Schema({
    name: [[]] // <-- Array of arrays of any type
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const entry = await Test.create({
    name: [1,2,3,4,5]
  });

  console.log(entry);

  await Test.findOneAndUpdate({_id: entry._id}, {$addToSet: {name: [6,7,8,9,0]}});
  console.log(await Test.find());
}

run();
```

We'll avoid adding `$each` for mixed arrays for v6.2.1 :+1:

**Comment by dor-benatia** [comment]
@twhy - i think it will appear as a breaking change and if you choose to update to version 6.2.1 you should handle that since it is obviously a bug.

**Comment by twhy** [comment]
@dor-benatia Agree.
