### ISSUE TITLE
strictPopulate won't work in schema options

### ISSUE THREAD

**Issue by UnlimitedX** [Automattic/mongoose#11290]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
An error is triggered by a populate call : 
`MongooseError: Cannot populate path `hello` because it is not in your schema. Set the `strictPopulate` option to false to override.`

Nevertheless the strictPopulate is defined in the schema options.
I've also examined the model.js source code and tests of mongoose and it seems to be available for use:
![image](https://user-images.githubusercontent.com/6625963/151588047-9d781a9a-000d-445f-950c-7fd274946b22.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
require("dotenv").config();

// getting-started.js
const mongoose = require('mongoose');

main().catch(err => console.log(err));

async function main() {
    console.log("mongoose.version " + mongoose.version)
    await mongoose.connect(process.env.vl_api_mongo_db);
    const kittySchema = new mongoose.Schema({
        name: String
    }, {
        strictPopulate: false
    });

    const Kitten = mongoose.model('ResourceTest2', kittySchema);

    var kitty1 = new Kitten({ name: "Henry" })
    await kitty1.save()
    var result = await Kitten.findById(kitty1._id).populate("hello")

    console.dir(result);
}
```

**What is the expected behavior?**
No error should be triggered

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
MongoDB 5.0.5
node v14.18.1
mongoose 6.1.8

**Comment by IslandRhythms** [comment]
```javascript

const mongoose = require('mongoose');

main().catch(err => console.log(err));

async function main() {
    console.log("mongoose.version " + mongoose.version)
    await mongoose.connect('mongodb://localhost:27017');
    const kittySchema = new mongoose.Schema({
        name: String
    }, {
        strictPopulate: false
    });

    const Kitten = mongoose.model('ResourceTest2', kittySchema);

    var kitty1 = new Kitten({ name: "Henry" })
    await kitty1.save()
    var result = await Kitten.findById(kitty1._id).populate("hello")

    console.dir(result);
}
```
