### ISSUE TITLE
MongoServerError: Limit value must be non-negative, but received: -9223372036854775808

### ISSUE THREAD

**Issue by ArbiNMaki** [Automattic/mongoose#11299]
**I'm stuck when I get an error like this, I've been looking everywhere for a solution but haven't gotten any results. Please help me. thank you**

I'm stuck when I get an error like this, I've been looking everywhere for a solution but haven't gotten any results. Please help me. thank you

Product.js "Routes"
`router.get("/products/total/", productsCount)`

Product.js "Controller"
```
exports.productsCount = async (req, res) => {
  let total = await Product.find({}).limit(10).estimatedDocumentCount().exec();
  res.json(total);
}
```

![cok](https://user-images.githubusercontent.com/26770607/151753527-97293fb3-49b9-4334-9169-e3a9915944a8.PNG)

**Comment by IslandRhythms** [comment]
You don't need `exec()` if you're using await.  Try doing
```javascript
let products = await Product.find({}).limit(10);
const total = products.length;
```
and let me know if you still get the same error.

**Comment by vkarpov15** [comment]
Are you sure that's where this error is coming from? Shouldn't be possible if you're hard-coding `limit(10)`
