### ISSUE TITLE
When define const isValidObjectId = mongoose.isValidObjectId, isValidObjectId always returns false

### ISSUE THREAD

**Issue by duyhcmut** [Automattic/mongoose#11304]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When passing an ObjectId to isValidObjectId from mongoose.isValidObjectId, it always returns false, no matter what the passed ObjectId has type of string or is an instance of ObjectId.
**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce, run this code:

const assert = require('assert');
const mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;
const isValidObjectId = mongoose.isValidObjectId;
assert(mongoose.isValidObjectId("5f5f1b2dc802bc22d44a0c2e")); //-> true
assert(isValidObjectId("5f5f1b2dc802bc22d44a0c2e")); //-> false
assert(mongoose.isValidObjectId(new ObjectId("5f5f1b2dc802bc22d44a0c2e"))); // -> true
assert(isValidObjectId(new ObjectId("5f5f1b2dc802bc22d44a0c2e"))); // ->false
**What is the expected behavior?**
It should be true.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 6.1.9
Nodejs 17.3.0

**Comment by pnutmath** [comment]
@duyhcmut This is because latest change in v6.1.9 of mongoose. inside `isValidObjectId`. `this` is getting referred which is undefined if you use like you mentioned.

I have created PR for this here #11305
