### ISSUE TITLE
FindOneAndUpdate doesn't work unless add "await" or ".then()". (The function itself doesn't work)

### ISSUE THREAD

**Issue by CodeYimin** [Automattic/mongoose#11303]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** findOneAndUpdate has no effect unless I add "await" or ".then()"

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const Model = mongoose.model(
  "Test",
  new mongoose.Schema({ title: String, description: String, })
)

mongoose.connect(url).then(async () => {
  await Model.findOneAndUpdate(
    { title: "Bruh" },
    { $set: { description: "bruhbruh" } }
  ).then(() => {});
})
```
If there is no await in front or an empty .then afterwards, the description does not update.

**What is the expected behavior?**
The description updates without putting await or .then

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
16.6.2

https://mongoosejs.com/docs/api.html#mongoose_Mongoose-version --> 6.1.9

**Comment by Uzlopak** [comment]
Add a .exec() to execute the query

**Comment by vkarpov15** [comment]
Expected behavior. Add `exec()` to execute the query.
