### ISSUE TITLE
Mongoose 6: mongoose.Types.ObjectId.isValid returns "true" if whole document is passed

### ISSUE THREAD

**Issue by hansemannn** [Automattic/mongoose#11301]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the behavior?**
When passing a document into `mongoose.Types.ObjectId.isValid`, it returns `false` in Mongoose 5 (correct) and `true` in Mongoose 6 (incorrect). Was this an undocumented change or actually a regression?

**What are the versions of Node.js, Mongoose and MongoDB you are using?
- Mogoose 6.1.5
- Node.js 16.6.1

**Comment by vkarpov15** [comment]
I wouldn't say this is a regression. The general idea of `isValid(v)` is to return `true` if `v` is something that Mongoose can cast to an ObjectId, which does include documents.

What issues is this causing for you? We may be able to suggest a workaround.
