### ISSUE TITLE
distinct return ts type is unclear

### ISSUE THREAD

**Issue by avichai-sealights** [Automattic/mongoose#11306]
**Do you want to request a *feature* or report a *bug*?**
Bug(?)
**What is the current behavior?**
distinct returns an array of Query doc type

```
const schema = new Schema<IModelEntry>({
    field: String
})
const model: Model<IModelEntry> = this.connection.model<IModelEntry>("collection", schema);
const response = await model.distinct('field', {});
```
According to the docs: distinct returns the distinct values of the given field that match filter. So if field is a string, a string[] should return.
However response is of type IModelEntry[]

**What is the expected behavior?**
distinct returns array of string 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
16.11, 5.13.14, 5.0.4

**Comment by kaulshashank** [comment]
@vkarpov15 I was thinking the correct type of `distinct()` should be something like this:

```
distinct<DocKey extends string, Result = DocKey extends keyof TRawDocType ? TRawDocType[DocKey] : unknown>(
        field: DocKey,
        filter?: FilterQuery<TRawDocType>
    ): QueryWithHelpers<
      Array<Result>,
      THydratedDocumentType,
      TQueryHelpers,
      TRawDocType,
      'distinct'
    >;
```

This should behave more like mongodb does, i.e., if you give something that isn't a key on the document, you still get an empty array or something `unknown[]`. With my suggested type, if you do give the correct key from the schema, you'll get a typesafe result.

If you're okay with this type, I'd be happy to raise a PR with tests.

**Comment by vkarpov15** [comment]
@kaulshashank looks good as long as tests pass. Feel free to put in a PR, we'll review it. My only potential concern is that this change will be backwards breaking; but if it is, we can always merge into the 8.0 branch.
