### ISSUE TITLE
Mongoose can't straddle MongoDB 4.4 and 5?

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#11302]
I am using Mongoose 5.13.10 and would like to upgrade MongoDB from 4.4 to 5. However, the [docs](https://mongoosejs.com/docs/compatibility.html) imply that no version of Mongoose is compatible with both versions of MongoDB:

> Below are the semver ranges representing which versions of mongoose are compatible with the listed versions of MongoDB server.
> * MongoDB Server 4.4.x: mongoose ^5.10.0
> * MongoDB Server 5.x: mongoose ^6.0.0

Is this a documentation mistake? If not, how can I safely upgrade MongoDB?

**Comment by IslandRhythms** [comment]
The docs are stating that MongoDB Server 4.4.x is compatible with all versions of mongoose equal to and higher than 5.10.0
and MongoDB Server 5.x is compatible with versions of mongoose equal to or higher than 6.

**Comment by JavaScriptBach** [comment]
> The docs are stating that MongoDB Server 4.4.x is compatible with all versions of mongoose equal to and higher than 5.10.0 and MongoDB Server 5.x is compatible with versions of mongoose equal to or higher than 6. Meaning You can stay on 4.4 and use mongoose v6

In that case I think the docs need to be updated then, because ^ includes minor releases only (https://docs.npmjs.com/about-semantic-versioning), e.g. ^5.10.0 does not include 6 and higher. You can see that major releases are also explicitly called out separately in the other bullet points like this:

> * MongoDB Server 3.0.x: mongoose ^3.8.22, 4.x, or 5.x

**Comment by vkarpov15** [comment]
In order to upgrade to MongoDB server 5.x, you would need to upgrade to Mongoose 6 first.
