### ISSUE TITLE
"cursor.eachAsync is not a function" or "TypeError: aggregate.allowDiskUse(...).cursor(...).exec is not a function" error

### ISSUE THREAD

**Issue by RayKahn** [Automattic/mongoose#11310]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Getting exception when iterating over cursor
`Promise {
  <rejected> TypeError: aggregate.allowDiskUse(...).cursor(...).exec is not a function
`
**If the current behavior is a bug, please provide the steps to reproduce.**

```
const aggregate = Model.aggregate([{ $match: { ownerId: $someId } }]); // type of ownerId is string
const cursor = aggregate.allowDiskUse(true)
	.cursor({batchSize: 100})
	.exec();
await cursor.eachAsync((doc) => {
	console.log({ listingId: doc._id, ...doc });
});
```
Cursor should return 30k records.
Removing `.exec()` results in `Promise { <pending> }` being returned however `cursor.eachAsync` still does not print any records. In fact it does not get executed.

**What is the expected behavior?**
Should be able to iterate through the records
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
$> npm list | grep "mongoose"
├─┬ @types/sinon-mongoose@1.3.11
├─┬ mongoose@6.1.9
npm├─┬ mongoose-type-email@1.0.12
 ERR! peer dep missing: date-fns@~2.0.0, required by date-fns-duration@1.0.4
npm ERR! peer dep missing: eslint@>=7.5.0, required by @babel/eslint-parser@7.12.16
npm ERR! peer dep missing: eslint@>=7.0.0, required by eslint-config-prettier@7.2.0
npm ERR! peer dep missing: sinon@1, required by sinon-as-promised@4.0.3
npm ERR! peer dep missing: sinon@5 - 7, required by sinon-mongoose@2.3.0
npm ERR! peer dep missing: superagent-proxy@^3.0.0, required by rest-facade@1.16.2
├── sinon-mongoose@2.3.0
│ ├─┬ mongoose@5.13.14
│ │ ├── mongoose-legacy-pluralize@1.0.2
```
Node: 16.4.2
mongoose: 6.1.9
mongoDB driver: 4.2.2 
mongoDB: 4.0.18

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html#creating-aggregation-cursors

It was a v 6 change, you don't need exec anymore

**Comment by RayKahn** [comment]
Thank you! Fixed it.
