### ISSUE TITLE
Collections are not created on init

### ISSUE THREAD

**Issue by orgads** [Automattic/mongoose#11319]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Collections (and indexes) are not created on initial connection, until I force them. This happens with mongodb server 5.0.6. This small example doesn't reproduce the issue with 4.4.12, but in my project I can reproduce with a replica set on 4.4.12, and also on MongoDB API for CosmosDB, which is more or less compatible with 4.0.

I've noticed that when `Connection.createCollection` is called for the first time, *sometimes* `db` is undefined, so the operation fails. In some other cases, it is defined, but still the collection is not created, and the most surprising thing is that if I have a breakpoint on the call to `this.db.createCollection` (at least with this small example), it is always defined. With CosmosDB I was able to break there with undefined.

This is clearly a timing issue, but I don't know how to debug this.

I can easily reproduce it, so if you guide me, I can provide more details.

**If the current behavior is a bug, please provide the steps to reproduce.**
Start with an empty database. I used this docker-compose:
```yml
version: '3'
services:
  mongo:
    image: mongo:5.0.6
    ports:
    - 28017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: foo
      MONGO_INITDB_DATABASE: foo
```

```javascript
import mongoose from 'mongoose';
const FooSchema = new mongoose.Schema({
  _id: { type: String },
  foo: { type: String, required: true }
});
FooSchema.index({ foo: 1 });

if (!mongoose.modelNames().includes('Foo'))
  mongoose.model('Foo', FooSchema);

function logCollections() {
  mongoose.connection.db.collections().then((res) => {
    const userCols = res.filter(col => !col.collectionName.startsWith('system.'));
    console.log(`count: ${userCols.length}`);
    for (const col of userCols)
      console.log(col.collectionName);
  })
}

const uri = 'mongodb://root:foo@localhost:28017/admin';
// None of these makes a difference...
const options: mongoose.ConnectOptions = {
  // autoCreate: true,
  // autoIndex: true,
  // bufferCommands: false,
  // directConnection: true,
}
mongoose.connect(uri, options).then(() => {
  console.log('connected');
  logCollections();
  Promise.all(Object.values(mongoose.models).map((model) => model.createCollection())).then(logCollections)
}).catch(console.error);
```

**What is the expected behavior?**
The collection `foos` should be created on startup. The output should list it twice (before and after the explicit call to `createCollection`), but instead - the first call shows an empty array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 17.4.0, mongoose 6.2.0, MongoDB client 4.3.1, MongoDB server 5.0.6

**Comment by IslandRhythms** [comment]
Is that the connection uri you are running when you encounter this error? The default port is 27017 and so it will error if that is not the specified port unless you change it. However, I do not see anywhere in the script where you change the default.

```javascript
const mongoose = require('mongoose');
const FooSchema = new mongoose.Schema({
  _id: { type: String },
  foo: { type: String, required: true }
});
FooSchema.index({ foo: 1 });

if (!mongoose.modelNames().includes('Foo'))
  mongoose.model('Foo', FooSchema);

function logCollections() {
  mongoose.connection.db.collections().then((res) => {
    const userCols = res.filter(col => !col.collectionName.startsWith('system.'));
    console.log(`count: ${userCols.length}`);
    for (const col of userCols)
      console.log(col.collectionName);
  })
}

const uri = 'mongodb://localhost:27017';
// None of these makes a difference...
const options = {
  // autoCreate: true,
  // autoIndex: true,
  // bufferCommands: false,
  // directConnection: true,
}
mongoose.connect(uri, options).then(() => {
  console.log('connected');
  logCollections();
  Promise.all(Object.values(mongoose.models).map((model) => model.createCollection())).then(logCollections)
}).catch(console.error);
```

**Comment by orgads** [comment]
Notice that I used port 28017 also in the docker-compose file.

I have another running instance on the same host on 27017, so I used a different port to isolate this one.

**Comment by orgads** [comment]
@IslandRhythms Are you still unable to reproduce?

**Comment by orgads** [comment]
Yes

**Comment by vkarpov15** [comment]
This is expected behavior. You need to set `autoCreate` to `true` and wait on `Model.init()`. The below works as expected:

```javascript
const uri = 'mongodb://localhost:27017';
// None of these makes a difference...
const options = {
   autoCreate: true,
  // autoIndex: true,
  // bufferCommands: false,
  // directConnection: true,
};

void async function main() {
  await mongoose.connect(uri, options);
  await mongoose.model('Foo').init();
  await logCollections();
}();
```

The reason why `init()` is necessary is that we need `mongoose.model()` to be synchronous, but `mongoose.model()` also kicks off `autoCreate` and `autoIndex` in the background. So `await mongoose.model('Foo').init()` tells your code to wait until Mongoose is done with building collections and indexes.

In prod, you normally don't need to do this because collections are usually already set up.
