### ISSUE TITLE
Deep index removal for MoongooseMap

### ISSUE THREAD

**Issue by tobegreen** [Automattic/mongoose#11328]
Hi,

Just trying to get something like below but the key, continues to be set to null. Is there a setting to make undefined MongooseMap variables be removed. trying to achieve with current indexing feature.

**Schemas**
const ParameterSchema = new mongoose.Schema({
    _id: false,
    label: String,
    description:String,
})

const StandardSchema = new mongoose.Schema({
    name: String,
    description: String,
    parameters: {
        type: Map,
        of:ParameterSchema,
    },
}, {discriminatorKey: 'type', collection: 'templates'});

**Document**
```
{
 name : 'string',
 description : 'string',
 parameters: {
  "1": {
    "label": 'string',
    "description": 'string',,
  },
"2": {
    "label": 'string',
    "description": 'string',,
  },
"3": {
    "label": 'string',
    "description": 'string',,
  },
"4": {
    "label": 'string',
    "description": 'string',,
  },
 }
}
```

**Executed Code:**
document.set('parameters.4', undefined)
**Expected**
```
{
 name : 'string',
 description : 'string',
 parameters: {
  "1": {
    "label": 'string',
    "description": 'string',,
  },
"2": {
    "label": 'string',
    "description": 'string',,
  },
"3": {
    "label": 'string',
    "description": 'string',,
  },
 }
}
```

**Actual**
```
{
 name : 'string',
 description : 'string',
 parameters: {
  "1": {
    "label": 'string',
    "description": 'string',,
  },
"2": {
    "label": 'string',
    "description": 'string',,
  },
"3": {
    "label": 'string',
    "description": 'string',,
  },
"4": null,
 }
}
```

Cheers

**Comment by vkarpov15** [comment]
You would need to do `document.parameters.delete('4')`. Setting the path to `undefined` is different than deleting it.

See MDN docs on `Map.prototype.delete()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete

**Comment by tobegreen** [comment]
Hi,

Ok no worries, there is no way to delete with the deep index?

document.delete('parameters.4')

Thanks

**Comment by vkarpov15** [comment]
@tobegreen unfortunately not. You could do `document.get('parameters').delete('4')`
