### ISSUE TITLE
Prevent duplication when creating mongoose document?

### ISSUE THREAD

**Issue by siamahnaf198** [Automattic/mongoose#11323]
I am trying to creating mongoose data, using array, In frontend I receive array of data like this-

```
mutation addCrypto {
  addCrypto(
    input: {
      code: ["AEDAUD", "AEDCAD", "AEDCHF", "AEDEUR", "AEDGBP", "AEDINR", "AEDJPY", "AEDNOK", "AEDNZD", "AEDPKR", "AEDSAR", "AEDSEK", "AEDZAR", "ANG", "ARSBRL", "ARSEUR", "ARSGBP", "ARSJPY", "ARSUSD", "AUD", "AUDAED", "AUDARS", "AUDBRL", "AUDCAD", "AUDCHF", "AUDCNH", "AUDCNY", "AUDCZK", "AUDDKK", "AUDEUR", "AUDFJD", "AUDGBP", "AUDHKD", "AUDHUF", "AUDIDR", "AUDILS", "AUDINR", "AUDJPY", "AUDKRW", "AUDMXN", "AUDMYR", "AUDNOK", "AUDNZD", "AUDPHP", "AUDPKR", "AUDPLN", "AUDSEK", "AUDSGD", "AUDTHB", "AUDTRY", "AUDTWD", "AUDUSD", "AUDZAR", "BDTGBP", "BDTJPY", "BGNUSD", "BHDEUR", "BHDPKR", "BHDUSD", "BRL", "BRLARS", "BRLAUD", "BRLCHF", "BRLEUR", "BRLHKD", "BRLJPY", "BRLKRW", "BRLMXN", "BRLRUB", "BRLSEK", "BRLSGD", "BRLUSD", "BRLZAR", "BWPEUR", "BWPUSD", "CAD", "CADAED", "CADARS", "CADAUD", "CADBRL", "CADCHF", "CADCNH", "CADCNY", "CADDKK", "CADEUR", "CADGBP", "CADHKD", "CADIDR", "CADILS", "CADINR", "CADISK", "CADJPY", "CADKRW", "CADKWD", "CADMXN", "CADMYR", "CADNOK", "CADNZD", "CADPKR", "CADPLN"],
      category: "61fb7ed1cbb82eee5e5d3074"
    }
  ){
    message
    success
  }
}
```

Now I am creating mongoose documents for every element in array. I write function in this way-

```
Mutation: {
    addCrypto: combineResolvers(isAuthenticated, isAdmin, async (_, {input}) => {
        input.code.forEach(async (code) => {
            const newCrypto = new Crypto({code: code, exchangeCode: "FOREX", category: input.category});
            await newCrypto.save();
        });
        return {
            message: "Crypto Added successfully!"
        }
    })
}
```
It works and give me data like images-
![WhatsApp Image 2022-02-03 at 11 32 05 PM](https://user-images.githubusercontent.com/78312010/152402630-fc68a37b-a043-4110-b528-e6878bcd7d71.jpeg)

Here, in the array of code, it have 100 elements, In the images you can see that it successfully created 100 documents. But Problem is, if I run this mutation again, then it create more 100 documents. This is the duplicates documents.

I need to stop it, If in the code of array has single of element that was created before, then it should not be create again, of course without any duplication error.

More clearly, I need to skip document creation when already created it. Just it. Please help me.

**Comment by IslandRhythms** [comment]
This is a situation where I believe `unique` is what you want.
https://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator

**Comment by siamahnaf198** [comment]
But unique options give an error. I have to skip error.

**Comment by IslandRhythms** [comment]
You need to clear your database, then try again with the unique option.

**Comment by vkarpov15** [comment]
Use [findOneAndUpdate with upserts](https://mongoosejs.com/docs/tutorials/findoneandupdate.html#upsert)
