### ISSUE TITLE
[Docs] explain how timestamps work under the hood

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#11336]
I've come across a case where I needed to use an update with `upsert: true`, but I didn't want to modify the `updatedAt` if the document already exists in the collection, only wanted it to be inserted if I had an insert.

I solved that with:
```js
{
      filter: { email: adminToUpsert.email },
      update: {
        $addToSet: { roles: UserRoles.ADMIN },
        $setOnInsert: {
          password: hashedPassword,
          createdAt: new Date(),
          updatedAt: new Date()
        }
      },
      options: { upsert: true, timestamps: false }
    }
```
That way if we're updating, `updatedAt` should not change, but if we're inserting a new document, we'll have an `updatedAt` field.

It would be nicer if we could provide fine control:
```js
timestamps: { onUpdate: false, onInsert: true }
```

We could change the internal implementation for 
* `timestamps: true` to be the equivalent of `timestamps: { onUpdate: true, onInsert: true }`.
* `timestamps: false` to be the equivalent of `timestamps: { onUpdate: false, onInsert: false }`.

Would need to do that for:
* Model.updateOne
* Model.updateMany
* Model.bulkWrite

Would happily work on that if you think we should include it in mongoose.

What do you think?
@vkarpov15 @Uzlopak @IslandRhythms @ahmedelshenawy25

**Comment by vkarpov15** [comment]
You could do this with a plugin:

```javascript
function skipTimestampsOnUpsert(schema) {
  schema.pre(['updateOne', 'updateMany', 'findOneAndUpdate'], function() {
    if (this.options.upsert) {
      this.setOptions({ timestamps: false });
    }
  });
}
```

Does that work for you?

**Comment by AbdelrahmanHafez** [comment]
That doesn't achieve what I'm trying to do for 2 reasons:
1. I'm trying to set createdAt and updatedAt _only_ on insert, not on update. The mentioned plugin will not add timestamps at all.
2. I don't need to have this behavior every time, so using a plugin will force me to pick a behavior on the schema level, while I'd like to do that on the operation level.


When that feature is implemented, the following tests should pass:
```js
describe('timestamps as an object', () => {
  const userSchema = new Schema(
    { name: { type: String } },
    { timestamps: true }
  );
  const User = mongoose.model('User', userSchema);
  const firstOfJan = new Date('2022-01-01');
  it('when `upsert` inserts a new document, and `timestamps.insert` is true, adds timestamps', async () => {
    // Arrange

    // Act
    await User.updateOne(
      {},
      { name: 'Upserted user 1' },
      { upsert: true, timestamps: { insert: true } }
    );

    // Assert
    const user = await User.findOne({ name: 'Upserted user 1' });
    assert.ok(user.createdAt);
    assert.ok(user.updatedAt);
  });
  it('when `upsert` inserts a new document, and `timestamps.insert` is false, does not add timestamps', async () => {
    // Arrange

    // Act
    await User.updateOne(
      {},
      { name: 'Upserted user 2' },
      { upsert: true, timestamps: { insert: false } }
    );

    // Assert
    const user = await User.findOne({ name: 'Upserted user 2' });
    assert.ok(user.createdAt == null);
    assert.ok(user.updatedAt == null);
  });
  it('when `upsert` updates a document, and `timestamps.update` is true, adds timestamps', async () => {
    // Arrange
    const user = await User.create({ name: 'Existing user 1', createdAt: firstOfJan, updatedAt: firstOfJan });

    // Act
    await User.updateOne(
      { name: 'Existing user 1' },
      { name: 'Upserted user 2' },
      { upsert: true, timestamps: { update: true } }
    );

    // Assert
    const userAfterUpdate = await User.findOne({ _id: user._id });

    assert.ok(userAfterUpdate.updatedAt > firstOfJan);
    assert.ok(userAfterUpdate.createdAt);
  });
  it('when `upsert` updates a document, and `timestamps.update` is false, does not add timestamps', async () => {
    // Arrange
    const user = await User.create({ name: 'Existing user 1', createdAt: firstOfJan, updatedAt: firstOfJan });

    // Act
    await User.updateOne(
      { name: 'Existing user 1' },
      { name: 'Upserted user 2' },
      { upsert: true, timestamps: { update: true } }
    );

    // Assert
    const userAfterUpdate = await User.findOne({ _id: user._id });

    assert.strictEqual(userAfterUpdate.updatedAt, firstOfJan);
    assert.strictEqual(userAfterUpdate.createdAt, firstOfJan);
  });
});
```

The way I'm planning to implement this is by using `$setOnInsert` optionally if `timestamps: true` or `timestamps.insert: true`, otherwise, it will not add timestamps on `$setOnInsert`.

**Comment by vkarpov15** [comment]
I'm not convinced this is a case we should support. It's something you can work around by disabling timestamps and structuring `$setOnInsert` yourself, like in OP. For one thing, `onUpdate` vs `onInsert` only is valid for `updatedAt`, not `createdAt`, so the current API design is potentially confusing. I also don't see this feature saving much code, it saves you from having to add an extra `$setOnInsert` in your update, which maybe saves 2 SLOC.

**Comment by AbdelrahmanHafez** [comment]
Admittedly, this is a case I've needed only once in the past ~5 years of using mongoose.

That being said, `$setOnInsert` lies in my head in the lesser-known features of MongoDB, and I would expect that ~%80 of devs out there do not know of it.
In addition to that, knowing how to solve this issue requires knowledge of the internals of how `timestamps` works, which I'm confident that %95 of devs out there are not familiar with.

I'm 50-50 on whether we should implement this feature or not.
What do you think? @vkarpov15

**Comment by vkarpov15** [comment]
I think it's something that would be better served as a docs entry, encouraging using `$setOnInsert`. Admittedly `$setOnInsert` isn't as well known as it should be. Are you ok with that @AbdelrahmanHafez ?
