### ISSUE TITLE
schema: `validate` with array as value makes typescript mad

### ISSUE THREAD

**Issue by vixalien** [Automattic/mongoose#11335]
**Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug

**What is the current behavior?**
When you create a schema and set `validate` to an array, it causes a typescript error.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create the following schema:

```ts
interface ILeave {
	// ...
	// timing
	start: Date;
	end: Date;
	expected: Date;
       /./..
}

const leavesSchema = new Schema<ILeave>({
    	start: {
		type: Date,
		validate: validators.futureDate(),
		required: true,
	},
	end: {
		type: Date,
		validate: [validators.futureDate(), validators.afterDate("start")],
		required: true,
	},
	expected: {
		type: Date,
		validate: [validators.futureDate(), validators.afterDate("end")],
		required: true,
	},
});
```

tsconfig.json
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"noImplicitAny": true,
		"removeComments": true,
		"preserveConstEnums": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"outDir": "dist",
		"moduleResolution": "node",
		"declaration": true,
	},
	"include": ["src/*", "models/**/*", "plugins/*"],
	"exclude": ["node_modules"]
}

```

**What is the expected behavior?**
I expect the `validate` property on a schema to allow arrays.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 16.13.2
Mongoose: 6.1.8
MongoDB: 4.2.2

**Comment by Uzlopak** [comment]
Yes. 

https://github.com/Automattic/mongoose/blob/d946a95a9cef1f14feaabc1fca6f944ab918c345/types/index.d.ts#L1636

I think it should be

validate?: (RegExp | [RegExp, string] | Function | [Function, string] | ValidateOpts<T>)[]
