### ISSUE TITLE
Inspection Errors when using mongoose.connect

### ISSUE THREAD

**Issue by jamespavett** [Automattic/mongoose#11349]
**What is the current behavior?**

I am getting inspection errors when using Mongoose in a project I am working on.

![image](https://user-images.githubusercontent.com/10764464/152891608-78770411-7350-48e8-9ec5-52a43eb91ff2.png)

![image](https://user-images.githubusercontent.com/10764464/152891677-c3d7521d-ba63-42d0-92b2-79ddbafd2576.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

I have tried using mongoose.connect with a promise and async/await and get similar results when using either:

```
export const connectDb = async (uri, callback) => {
    try {
        await mongoose.connect('mongodb://localhost:27017/test', {
            bufferCommands: true
        })
    } catch (error) {
        console.log(error.message)
    }
}
```

```
mongoose.connect(db.url, { bufferCommands: true }).then(() => {
    console.log('Successfully connected to the database');
}).catch(err => {
    console.log(err);
    console.log('Error connecting to the database');
});
```

**What is the expected behavior?**

I was expect this to work without any inspection errors. If I removed the ConnectOptions parameter, the errors are removed as expected, however they all always present with an options object is passed. I am using WebStorm as my IDE, but I do not get the error with anything else, only this method call when using mongoose.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 17.4.0
Mongoose 6.2.0
MongoDB 5.0.6

**Comment by Uzlopak** [comment]
What tool are you using?

**Comment by Uzlopak** [comment]
It is not reproducable #11351

**Comment by jamespavett** [comment]
As in IDE? Webstorm 2021.3.2

**Comment by Uzlopak** [comment]
I installed now Webstorm to check it.

I checked the typescript definitions and they match typescripts best practice regarding function overloads
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#function-overloads

 It seems that Webstorm is not correctly processing the typescript definition, as it takes the first function definition without checking if the function is the correct match.

**Comment by Uzlopak** [comment]
I also tested reordering the definitions and it seems that I stay corrected: webstorm is applying the definitions wrong :/

**Comment by jamespavett** [comment]
Just to confirm you are able to reproduce the inspection errors on your end as well?

If that's the case I will raise this on their issue tracker.

**Comment by Uzlopak** [comment]
I installed latest webstorm. Then I created a new js-project and installed mongoose. Then I imported mongoose and called connect like in your screenshot.
Got the same type warning like you.

If you go to the type definition (Ctrl+leftclick on connect) you see the function overloads for connect. You can comment out the function overloads which you don't use and see that the warning is gone. 
But as you can see the typescript do's and don't s says that the function overloads have to be in the order like it is now. 
So it should be an issue of webstorm and not of the typings.

**Comment by jamespavett** [comment]
Thanks for your feedback @Uzlopak 

Have raised the issue under [https://youtrack.jetbrains.com/issue/WEB-54729](https://youtrack.jetbrains.com/issue/WEB-54729), just in case anyone comes here and is wondering the same.

**Comment by Uzlopak** [comment]
@jamespavett 
According to the Webstorm issue tracker, the issue was fixed on their side, so we can conclude that the bug was implicitly confirmed on their side. So they should release the fix with their next release. 

Btw. the fixed it fast, respect.

**Comment by 9QS** [comment]
I have this problem too in WebStorm.
