### ISSUE TITLE
Populating nested objects does not work

### ISSUE THREAD

**Issue by JulSeb42** [Automattic/mongoose#11345]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I get only the `_id` and not a populated object

**If the current behavior is a bug, please provide the steps to reproduce.**

Model:

```
invitedPeople: [
    {
        user: {
            type: Schema.Types.ObjectId,
            ref: "User",
        },
        answer: {
            enum: ["yes", "maybe", "no", "pending"],
            type: String,
        },
    },
],
```

Router

```
router.get("/event/:id", (req, res, next) => {
    Event.findById(req.params.id)
        .populate({
            path: "invitedPeople",
            populate: {
                path: "user",
                model: "User",
            },
        })
        .then(postFromDb => res.status(200).json(postFromDb))
        .catch(err => next(err))
})
```

**What is the expected behavior?**

Getting all user information and not only their `_id`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`node 16.13.1`
`mongoose 6.2.0`
`mongodb 5.0.4`

**Comment by IslandRhythms** [comment]
@vkarpov why does the commented out console log return undefined but return a value when saved to a variable? Is it because it hasn't finished?

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    invitePeople: [
        {
            user: {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'User'
            },
            answer: {
                enum: ['yes', 'maybe', 'no', 'pending'],
                type: String
            }
        }
    ]
})

const userSchema = new mongoose.Schema({
    name: String
});

const User = mongoose.model('User', userSchema);

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const entry = await User.create({
        name: 'Test'
    });

    const event = await Test.create({invitePeople: [{user: entry._id, answer: 'pending'}]})
    console.log(await Test.findOne().populate('invitePeople.user'));
    // await Test.findOne().populate('invitePeople.user').invitePeople returns undefined for some reason
    const test = await Test.findOne().populate('invitePeople.user');
    console.log(test.invitePeople)
}

run();
```

**Comment by vkarpov15** [comment]
@IslandRhythms yep. `(await Test.findOne().populate('invitePeople.user')).invitePeople` would work fine, but `await Test.findOne().populate('invitePeople.user').invitePeople` returns undefined because you're awaiting on `Test.findOne().populate('invitePeople.user').invitePeople`, and since `Test.findOne().populate('invitePeople.user')` is a Mongoose Query instance, it doesn't have an `invitePeople` property.
