### ISSUE TITLE
this._executionStack = new Error()

### ISSUE THREAD

**Issue by rodycouto** [Automattic/mongoose#11341]
I've got this error
```js
/home/node/node_modules/mongoose/lib/helpers/query/wrapThunk.js:25
    this._executionStack = new Error();
                           ^
TypeError: Error is not a constructor
    at model.Query._wrappedThunk [as _findOne] (/home/node/node_modules/mongoose/lib/helpers/query/wrapThunk.js:25:28)
    at /home/node/node_modules/kareem/index.js:375:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Node Version ^16
Mongoose Verson: ^16.2.0

*I got this error after 2 days. (My Discord Bot was online for 2 days)

**Comment by Uzlopak** [comment]
What was the solution?

**Comment by rodycouto** [comment]
> What was the solution?

I don't know. I just remake my Database's. Probably the problem was some function on my own code (maybe). The error don't return nothing in code, just mongoose.
