### ISSUE TITLE
ValidationError.errors is wrongly typed

### ISSUE THREAD

**Issue by MitchelKerckhaert** [Automattic/mongoose#11367]
**Do you want to request a *feature* or report a *bug*?**
Report a (typescript) bug

**What is the current behavior?**
The [documentation](https://mongoosejs.com/docs/validation.html) says that the errors property of a ValidationError is an object whose values are ValidatorErrors or CastErrors.
However in practice it can also be another ValidationError object (according to the typing). Because of this I am having issues accessing the kind property on those objects, because the kind property does not exist on a ValidationError object.
```
function handleValidationError(err: mongoose.Error.ValidationError): Array<string> {
  const errorTypes = Object.keys(err.errors).map((field: string) => err.errors[field].kind)
  return errorTypes
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce, create a ValidationError instance and try to access the kind property on one of the items in the errors property like in the example above. Typescript will not compile because kind does not exist on type ValidationProperty.

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./lib",
    "strict": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```

**What is the expected behavior?**
errors on the ValidationError class should only be of type ValidatorError or CastError and not of type ValidationError

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 17.4.0
mongoose: 6.2.0
MongoDB: 5.0

**Comment by Uzlopak** [comment]
Created potential fix in #11369
