### ISSUE TITLE
[TypeScript]  $search operator not correctly typed (highlight path option)

### ISSUE THREAD

**Issue by lmX2015** [Automattic/mongoose#11372]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

$search operator (aggregation) is not correctly typed (for the highlight option). For example

```typescript
import {Model, model, Schema} from "mongoose";

interface IUser {
    name: string;
    firstName: string;
    search(query: string): any;
}

// 2. Create a Schema corresponding to the document interface.
const schema = new Schema<IUser>({
    firstName: { type: String, required: true },
    name: { type: String, required: true },

});

schema.static("search", function(this: Model<IUser>, query: string) {
    return this.aggregate([
        {
            $search: {
                highlight: {
                       path : ["name", "firstname"], // "name" works fine
                },
                index: "searchLucene",
                text: {
                    path: ["name", "firstname"],
                    query,
                },
            },
        },
        {
            $project: {
                firstName: 1,
                highlights: { $meta: "searchHighlights" },
                name: 1,
                score: { $meta: "searchScore" },
        }},

    ]);
});
// 3. Create a Model.
const UserModel = model<IUser>("User", schema);


```

throws a compilation error (path should be a string not string[]).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

From [MongoDB documentation](https://docs.atlas.mongodb.com/atlas-search/highlighting/#std-label-highlight-ref),  "highlight.path" can be a string array.
 So `highlight.path` should be at least `string | string []`
 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

-   mongoose: 6.2.1
-   typescript: 3.3.3
-   node : 16.3.0

**Comment by vkarpov15** [comment]
Fixed in v6.2.2 with #11373
