### ISSUE TITLE
QueryCursor.js is throwing an error on line 144: "TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'"

### ISSUE THREAD

**Issue by balonsom** [Automattic/mongoose#11377]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

QueryCursor.js is throwing an error on line 144:

`QueryCursor.prototype.map = function(fn) {`

Trying to assign to read only property 'map' of object

```
TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
    at Object.<anonymous> (/Users/balonsom/Documents/repos/dungeon-master/node_modules/mongoose/lib/cursor/QueryCursor.js:144:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/balonsom/Documents/repos/dungeon-master/node_modules/mongoose/lib/query.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This bug only arose when I upgrade Node.js to v17.5.0. I don't think I can easily provide a script to replicate.

**What is the expected behavior?**

QueryCursor.js should not throw an error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 6.2.1
Node.js: 17.5.0
MongoDB: 4.4

**Comment by abeledovictor** [comment]
Same happening to
mongoose 5.7.7
MongoDB 4.4.12

**Comment by Uzlopak** [comment]
I can reproduce it on node 17.5. 

@IslandRhythms  You dont need a repoductions script.

Just 
nvm install 17.5 && nvm use 17.5 && npm t

And voila you get that issue.

**Comment by druv5319** [comment]
Having the same issues as well. Any fix?

**Comment by druv5319** [comment]
Thanks it worked. My application automatically updated the Node engine to 17.5 and didn't realize what was causing the issue.

**Comment by ummerirshadk** [comment]
Thanks!! It worked

**Comment by hemantvishwakarma** [comment]
In local working fine but when i deployed on digital ocean Kubernetes server then showing error. please help....

![image](https://user-images.githubusercontent.com/13185478/153586771-6e466e41-1b4c-489a-9ba8-d555d977b4f4.png)

**Comment by ummerirshadk** [comment]
@hemantvishwakarma
Please try updating your package.json to node 14. Please refer to the below sample.

```
"engines": {
    "node": "14.x"
  },

```

**Comment by hemantvishwakarma** [comment]
> @hemantvishwakarma
> 
> Add below under `"main": "index.js",` `"engines": { "node": "14.x" }, `

i did but showing same error 

![image](https://user-images.githubusercontent.com/13185478/153589513-4ea30ad3-f17a-4964-8ccd-ffebcfb07951.png)

![image](https://user-images.githubusercontent.com/13185478/153589588-9909c2ac-d59f-4ece-a71f-b9599f698425.png)

**Comment by ummerirshadk** [comment]
> "engines": { "node": "14.x" },

Try 14.x instead of complete version

**Comment by hemantvishwakarma** [comment]
> > "engines": { "node": "14.x" },
> 
> Try 14.x instead of complete version

same error 

i deployed code on digital ocean Kubernates

**Comment by ummerirshadk** [comment]
Please check on digital ocean to see if there are other options to specify node version of the image they are using for kubernetes.

**Comment by Uzlopak** [comment]
This is not a kubernetes specific issue. Kubernetes is a docker orchestrator. So you have to modify your dockerfile to use a working node base image. 

Also I would recommend to you to not use odd major versions of node, as they are bleeding edge. Best practice is to use LTS-versions for production, to specifically avoid such issues.

If you use node:latest in your dockerfile, than you are using node 17.5, according to dockerhub. 

Best practice for node docker images is to pinpoint exact versions down to patch-version. E.g. use `16.14.0-alpine3.15` instead of `16-alpine`.  Thus also avoiding caching an old node 16 base image in docker and then wondering why you building on a different machine breaks.

**Comment by hemantvishwakarma** [comment]
thank you guys

my old docker file is this -  

![image](https://user-images.githubusercontent.com/13185478/153593511-ad7a6f06-9d02-4318-b510-e9df73764869.png)

When i changed this - 

![image](https://user-images.githubusercontent.com/13185478/153593570-1c90c95a-d543-4a8c-a8d6-d2c00d8fb0ea.png)



NOW WORKING FINE

**Comment by SLXJS** [comment]
oh lol you already had the answer - I didn't realise while I wrote my comment 😅

**Comment by Uzlopak** [comment]
@SLXJS 

Dont worry. How we Germans say: Doppelt hält besser.

@hemantvishwakarma 
You should try to always use latest node LTS version, which is 16.14.0, for security reasons. You should setup a notification on new LTS node versions by using e.g. https://newreleases.io/ and then when you get the information that there is a new LTS-Version, you update your node, run your unit tests, and if they pass, you change your dockerfile to use the newest node LTS-version.

**Comment by Lwdthe1** [comment]
Thanks @abeledovictor 

`"node": ">=14.0.0 <17.5.0" ` worked for me

**Comment by mrVeganProgrammerGuyDude** [comment]
guys, I used to have this:

`	"engines": {
		"node": ">=12.18.2",
		"npm": ">=6.14.5"
	},`

and as per the advice here, changed it to:

`	"engines": {
		"node": "14.x",
		"npm": ">=6.14.5"
	},`

and now it works!!!

**Comment by lolo-io** [comment]
Latest version 17.6.0 of node with the fix (https://github.com/nodejs/node/pull/41931) is out : https://github.com/nodejs/node/releases/tag/v17.6.0
Tested it and the error is gone.

Not available in docker yet as :latest image still points to 1.17.5 but it should be available very soon.
