### ISSUE TITLE
$push is not assignable to type "undefined".

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#11374]
### Discussed in https://github.com/Automattic/mongoose/discussions/11358

<div type='discussions-op-text'>

<sup>Originally posted by **Milo123459** February  8, 2022</sup>
Hello!

I recently started migrating from Mongoose V5 to V6 and had this one weird error coming from one of my `$push` operators. Here is [the code](https://sourceb.in/7juOKo1qHc) and [the error](https://sourceb.in/wmjEVZmSiy).

The error isn't making any sense to me, and was wondering if someone who has more experience with mongoose could take a look/help? This error is very frustrating and I've been trying to solve it for about 30 minutes but I have gotten nowhere. The documentation on the MongoDB docs for $push [here](https://docs.mongodb.com/v4.0/reference/operator/update/push/) have stayed the same from V3.0 to V4.0. I am using TypeScript by the way.</div>

**Comment by Uzlopak** [comment]
It's a typescript issue

**Comment by vkarpov15** [comment]
Looks like this was fixed in v6.0.4 with #10617 and https://github.com/Automattic/mongoose/commit/e1d4aa4e4ecb5fe03c60236d93fb4a574d2b0c1b .
