### ISSUE TITLE
Calling model.create with undefined|null|{} options causes validation errors

### ISSUE THREAD

**Issue by Sammaye** [Automattic/mongoose#11378]
I have a "base" model if you will for proxying my other models, so I have this function:

```
    static create(docs, options, callback) {
        return this.model.create(docs, options, callback);
    }
```

But problem is as soon as I add options or callback params to create it breaks, I have tried:
- Null: Causes validation errors
- undefined: causes validation error
- {}: causes a session property not found error
All of which end in misery.

Anyone else getting this and if so how can I call this function with empty params?

I believe the issue stems form here https://github.com/Automattic/mongoose/blob/master/lib/model.js#L3085

**Comment by Uzlopak** [comment]
What happens if you do instead:

```
  static create(docs, options, callback) {
        return this.model.create.apply(this.model, arguments);
    }
```

**Comment by Sammaye** [comment]
Indeed, thanks that works
