### ISSUE TITLE
Regex for numerical string do not working as expected

### ISSUE THREAD

**Issue by HelkerSuardi** [Automattic/mongoose#11371]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
if i do a query like { field: { $regex: 'asdfasd', $options: 'i' } } and the field has only numerical char, it will be returned. I've copied the same query directly in mongo, and it works. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1- add a string with only numerical char in some register. Ex: { field: '012093102930' }
2- do a query with regex for this field. Ex: { field: {  $regex: 'anything', $options: 'i' } }

**What is the expected behavior?**
Do not bring that do not match with the string

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 16.14.0
Mongoose: 6.2.1
MongoDB: 5.0.6

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({name: '123456789123'});
    await Test.create({name: '0987654321234567899'});

    const result = await Test.find({name: {$regex: 'anything', $options: 'i'}});
    console.log(result);
}

run();
```

**Comment by HelkerSuardi** [comment]
I find out the problem, if you pass 'document' in $or query, it will bring all registers...could you try it @IslandRhythms ?
