### ISSUE TITLE
aggregate $match = have to set a _id to equal ObjectId('idPastIn')

### ISSUE THREAD

**Issue by justcoder1** [Automattic/mongoose#11383]
I have notice when using Mongoose and if you are doing say 'findOne' you can simply do:

_id: idPastIn

But if you are doing an 'aggregate' with a '$match' you have to wrap the idPastIn inside an ObjectId().

Is this an error and to be consident with the rest of Mongoose should the match with with strings and objects for _id?

Thanks

**Comment by MikeKoval** [comment]
aggregate is fully controlled by you, i think it's difficult to populate types there...
