### ISSUE TITLE
What Date format to use with TypeScript?

### ISSUE THREAD

**Issue by Arcanorum** [Automattic/mongoose#11386]
**Do you want to request a *feature* or report a *bug*?**
Bug(?)

**What is the current behavior?**
TypeScript error when trying to use Date type for schema field.

```
Type '{ type: DateConstructor; default: () => number; }' is not assignable to type 'SchemaDefinitionProperty<number> | undefined'.
  Types of property 'type' are incompatible.
    Type 'DateConstructor' is not assignable to type 'NumberSchemaDefinition | undefined'.
      Type 'DateConstructor' is missing the following properties from type 'NumberConstructor': MAX_VALUE, MIN_VALUE, NaN, NEGATIVE_INFINITY, and 10 more.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
import { model, Schema } from 'mongoose';

interface Account {
    username: string;
    password: string;
    lastLogOutTime: number;
    isLoggedIn: boolean;
}

const accountSchema = new Schema<Account>(
    {
        username: {
            type: String, required: true, index: true, unique: true,
        },
        password: { type: String, required: true },
        lastLogOutTime: { type: Date, default: Date.now }, // <-- TS error for type of lastLogOutTime
        isLoggedIn: { type: Boolean, default: false },
    },
);

const AccountModel = model<Account>('Account', accountSchema);

export default AccountModel;
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES6",
    "lib": ["ESNext", "dom"],
    "jsx": "react-jsx",
    "module": "ESNext",               
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true,
    "strict": true,                     
    "skipLibCheck": true,
  },
  "ts-node": {
    "compilerOptions": {
      "module": "CommonJS"
    }
  },
}

```

**What is the expected behavior?**
Unclear what schema field type to use for this situation.
Using a default of `Date.now` returns a number which TypeScript expects for the interface field type `lastLogOutTime: number;`, but then this type doesn't match the `Date` type of the schema field, as TS seems to have no idea that Mongoose converts the value of `Date.now` to a `Date`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: 16.13.0
Mongoose: 6.1.2
MongoDB: 4.4.12
TypeScript: 4.4.4

**Comment by toverux** [comment]
Hi,

Your interface should declare a `Date` rather than a `number`, as that's what you will receive.

Then you could use `() => new Date()` as the default value.
`Date.now` would still pass type checking though, but not because `number` is explicitly supported: `default` is typed as `T | ((this: any, doc: any) => Partial<T>)`, `Date.now` matches the second type in this union, and a `number` is indeed assignable to `Partial<Date>`... so types incidentally (?) cover `() => number` but it looks like a side effect from unsound typing.

**Comment by vkarpov15** [comment]
@toverux is correct, the fix here is to do `lastLogOutTime: { type: Number, default: () => Date.now() }`, or make `lastLogOutTime: Date;` . Can't make a path a number in your document interface but a date in your schema.
