### ISSUE TITLE
Types.Array type does not accept default property

### ISSUE THREAD

**Issue by jansedlon** [Automattic/mongoose#11391]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using `Types.Array<Types.ObjectId>`, I can't pass object configuration for that property with attribute `default` because it's of type `never`. 

**If the current behavior is a bug, please provide the steps to reproduce.**

https://codesandbox.io/s/aged-dawn-biq34?file=/src/index.ts

TSConfig Included in CodeSandbox

**What is the expected behavior?**
To have correct TS typings.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs 16, Mongoose 6.2.1 and MongoDB 4.5

**Comment by Uzlopak** [comment]
You have to use Schema.Types.Array and not Types.Array

**Comment by jansedlon** [comment]
@Uzlopak How exactly do you have in mind? Tried both ways and unfortunately, nothing worked.
<img width="762" alt="image" src="https://user-images.githubusercontent.com/13948180/154796346-f890164e-b29e-42fe-98ae-49f68d42164a.png">
<img width="726" alt="image" src="https://user-images.githubusercontent.com/13948180/154796359-27d84dcf-59c2-4e2d-9960-2ff626be7343.png">

**Comment by Uzlopak** [comment]
Usually you would not type it like you did:

interface User {
   ids: Schema.Types.ObjectId[];
}

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/5a9669236072a82e5c5e51ed092071cd869ce52b, fix will be in v6.2.7
