### ISSUE TITLE
push  #11381 to npm

### ISSUE THREAD

**Issue by Grayson-code** [Automattic/mongoose#11392]
https://github.com/Automattic/mongoose/pull/11381 push this to npm i cant really use my project for past days due to conflicting with mongoose 17.5 error and me needing top level await would like to get this fixed fast

**Comment by meabed** [comment]
@Grayson-code completely - I was thinking release is automated, but it's not, so maybe wait a bit more time.
However - I appreciate the work done by everyone - Thank you ❤️

**Comment by devchilling** [comment]
please, is this fix pushed?? @meabed 
@Grayson-code did you get it to work

**Comment by meabed** [comment]
> please, is this fix pushed to npm already?? @meabed 
> 
> @Grayson-code did you get it to work

It's pushed lasted master but not released, tagged yet.

**Comment by devchilling** [comment]
please what the status of this issue, @meabed

**Comment by meabed** [comment]
It's released! 🎉
