### ISSUE TITLE
SubdocumentPaths.js error on doValidate since release 6.1.4

### ISSUE THREAD

**Issue by ChristopherMedaille** [Automattic/mongoose#11410]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Since the following commit : https://github.com/Automattic/mongoose/commit/89f130219e04a3256fff8d8df85e77238131880a

We have an error on subdocuments when updating with values not defined in schema (Dynamic object parameters)
`TypeError: Cannot read property 'validate' of undefined
    at SubdocumentPath.doValidate (/Users/salvatore/Git/VeryGames/vl-api/node_modules/mongoose/lib/schema/SubdocumentPath.js:247:18)
    at /Users/salvatore/Git/VeryGames/vl-api/node_modules/mongoose/lib/document.js:2745:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)`
    
After checking deeper, seems like the SubdocumentPath.js is missing some checks : 

```
SubdocumentPath.prototype.doValidate = function(value, fn, scope, options) {
  const Constructor = getConstructor(this.caster, value);

  if (value && !(value instanceof Constructor)) {
    value = new Constructor(value, null, scope);
  }

  if (options && options.skipSchemaValidators) {
    return value.validate(fn);
  }

  SchemaType.prototype.doValidate.call(this, value, function(error) {
    if (error) {
      return fn(error);
    }
    if (!value) {
      return fn(null);
    }

    value.validate(fn);
  }, scope, options);
};
```

I don't know if skipSchemaValidators (true) should do the validation. 
Also, shouldn't it check if value is undefined before doing the .validate ?

**If the current behavior is a bug, please provide the steps to reproduce.**
Hard to say since we have a complex stack, but I would say creating a document, trying to update it with a nested document containing parameters that are not defined in schema.

**What is the expected behavior?**
Shouldn't trigger the Cannot read property 'validate' of undefined error since it's should reach this part of code

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node : 14.18.1
Mongoose : 6.2.1
MongoDb : Using atlas so i guess it's 4.3.1

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        name: 'Test'
    });

    await Test.findOneAndUpdate({}, {name: 'Frank', bad: {no: 'not in doc'}});
    console.log('done');
}

run();
```
