### ISSUE TITLE
Set is triggered by find

### ISSUE THREAD

**Issue by HelkerSuardi** [Automattic/mongoose#11425]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I need to make a query using or and regex operator to compare 3 fields, this query is triggering setter of the model, what i hope that is not the right behavior. One of this fields has a setter that remove all chars that is not number, so, if i send in my query something that just has letters, it will set in my query an empty value, that will bring all documents.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose');

const getOnlyNumbers = string => {
    return string.replace(/[^\d]+/g,'')
}

const testSchema = new mongoose.Schema({
    cnpj: {
        type: String,
        required: true,
        set: getOnlyNumbers,
        minlength: 14,
        maxlength: 14
    }
}, { strictQuery: false });

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');

    await Test.create({cnpj: '32270838000191'});
    await Test.create({cnpj: '67181891000109'});

    const result = await Test.find({ $or: [{ cnpj: { $regex: 'nomatter', $options: 'i' } }]});
    console.log(result);
}

run();
```

**What is the expected behavior?**
That the setter do not manipulate the query

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 16.14.0
Mongoose: 6.2.1
MongoDB: 5.0.6

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const getOnlyNumbers = string => {
    console.log(string)
    return string.replace(/[^\d]+/g,'')
}

const testSchema = new mongoose.Schema({
    cnpj: {
        type: String,
        required: true,
        set: getOnlyNumbers,
        minlength: 14,
        maxlength: 14
    }
}, { strictQuery: false });

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await Test.create({cnpj: '32270838000191'});
    await Test.create({cnpj: '67181891000109'});

    const result = await Test.find({ $or: [{ cnpj: { $regex: 'nomatter', $options: 'i' } }]});
    console.log(result);
}

run();
```

**Comment by AbdelrahmanHafez** [comment]
That behavior is [by design](https://mongoosejs.com/docs/api.html#:~:text=Suppose%20you%20are%20implementing,and%20AvEnUe%40Q.CoM.), setters are applied on filters as well as write operations.

Do you have another application writing to the same database that allows characters on that field?

Unless that's the case, your data should be written with the same rules, so applying the setter on the filter makes it only convenient to have the same rules applied when writing the document.

**Comment by HelkerSuardi** [comment]
Semantically speaking, i dont think that makes sense, setters have to be applied only in write operations, but it is my opinion.
This treatment happens in all consumers of my api, its just another security level for the data integrity. Its a data that need to apply masks at client side.

**Comment by AbdelrahmanHafez** [comment]
I agree that the name `set` can be a bit confusing, I've been confused by the name a few times as well.
That being said, this should only be a problem if you have other applications writing to the same database with different rules.

If you have a `set` that converts an `email` field to lowercase, removes dots from the E-mail name while writing, then it only makes sense to have the same rules applied when finding.
If that's not the case for you, can you tell me more about your use case?

I think it might be a good idea to find a better name for `set`, for example, `convert`.
Perhaps we could introduce `convert` as an alternative in v6, and remove `set` in v7 in favor of `convert`.

What do you think?

**Comment by HelkerSuardi** [comment]
I think the biggest problem is....i want to compare multiple props that has the same type (string), but has different behaviors, lets take a look in your example. 
"removes dots from the E-mail name while writing, then it only makes sense to have the same rules applied when finding", in this case, if you are doing a query only for this prop, it will works well, but if you put other props in comparison, some problems can happen, because each prop can has individual behaviors.
Now lets take a look in my real case: I have three props to be compared in an $or sentence: 
1 - tradeName: Has no treatment for the data
2 - companyName: Has no treatment for the data
3 - document: Has treatment to get only numbers
When i do a query with an $or sentence for these props, the treatment shouldnt affects the query, i think that is the point, because when i am querying, the input data shouldnt receive any modification from the model, it is out of model's responsability.
Any handle of the query must be done out of the model, in my opinion.
I dont know if i was clear, my english is poor, but i will try to explain better if you dont understand my case

**Comment by HelkerSuardi** [comment]
If you want to keep a handle of the query, might isolate this behavior in another prop is the best way, so, set only has been triggered when it is a write action, and the new prop when it is a read action

**Comment by AbdelrahmanHafez** [comment]
I'm still not sure we fully understand each other.

What I'm saying is that if we have a
`set: getNumbersOnly`
And all your database insertions are done using mongoose
`new User({ documentName: 'image2020' })` will actually store in the database `documentName: '2020'`.
So when you filter, you would _always_ need to apply the same setter.
`User.findOne({ documentName: 'image2020' })` will never match anything if we don't apply the field setter here, and you'll always need to do that manually.

That's why this is the default behavior.
What do you think? @HelkerSuardi

**Comment by HelkerSuardi** [comment]
$or make it different because you are comparing a same parameter to different props...but its not the point, its the way that you can find this behavior, the point is, the model shouldn't has influence in query values.
My discord if you want to make a call: Helker#5328

**Comment by AbdelrahmanHafez** [comment]
I'm sorry, Discord is not an option I'm willing to go for.

There is a communication issue here, we're stuck in a loop where you say `set` _shouldn't_ affect the filter without explaining _why_.

I'm trying to explain _why_ this is the behavior.

Please try to come up with a script with a failing test that fails due to `set` being applied on filters.

I can not help without understanding why this is a problem for you.

**Comment by HelkerSuardi** [comment]
`const mongoose = require('mongoose');

const getOnlyNumbers = string => {
    console.log(string)
    return string.replace(/[^\d]+/g,'')
}

const testSchema = new mongoose.Schema({
    companyName: String,
    tradeName: String,
    cnpj: {
        type: String,
        required: true,
        set: getOnlyNumbers,
        minlength: 14,
        maxlength: 14
    }
}, { strictQuery: false });

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await Test.create({ companyName: 'My first company LTDA', tradeName: 'My first company', cnpj: '32270838000191'});
    await Test.create({ companyName: 'My second company LTDA', tradeName: 'My second company', cnpj: '67181891000109' });

    const onlyNumbersOrParameter = '322'
    const nonNumericalParameter = 'My first'

    const firstResult = await Test.find({ 
      $or: [
        { companyName: { $regex: onlyNumbersOrParameter, $options: 'i' } },
        { tradeName: { $regex: onlyNumbersOrParameter, $options: 'i' } },
        { cnpj: { $regex: onlyNumbersOrParameter, $options: 'i' } }
      ]
    });

    const secondResult = await Test.find({ 
      $or: [
        { companyName: { $regex: nonNumericalParameter, $options: 'i' } },
        { tradeName: { $regex: nonNumericalParameter, $options: 'i' } },
        { cnpj: { $regex: nonNumericalParameter, $options: 'i' } }
      ]
    });

    console.log('FIRST RESULT', firstResult);
    console.log('********************************************************')
    console.log('SECOND RESULT', secondResult);
}

run();`

**Comment by HelkerSuardi** [comment]
I cant explain better to you than the code bellow
Anyway, i solved the problem moving set to pre save hook

```js
const mongoose = require('mongoose');

const getOnlyNumbers = string => {
    console.log(string)
    return string.replace(/[^\d]+/g,'')
}

const testSchema = new mongoose.Schema({
    companyName: String,
    tradeName: String,
    cnpj: {
        type: String,
        required: true,
        set: getOnlyNumbers,
        minlength: 14,
        maxlength: 14
    }
}, { strictQuery: false });

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await Test.create({ companyName: 'My first company LTDA', tradeName: 'My first company', cnpj: '32270838000191'});
    await Test.create({ companyName: 'My second company LTDA', tradeName: 'My second company', cnpj: '67181891000109' });

    const onlyNumbersOrParameter = '322'
    const nonNumericalParameter = 'My first'

    const firstResult = await Test.find({ 
      $or: [
        { companyName: { $regex: onlyNumbersOrParameter, $options: 'i' } },
        { tradeName: { $regex: onlyNumbersOrParameter, $options: 'i' } },
        { cnpj: { $regex: onlyNumbersOrParameter, $options: 'i' } }
      ]
    });

    const secondResult = await Test.find({ 
      $or: [
        { companyName: { $regex: nonNumericalParameter, $options: 'i' } },
        { tradeName: { $regex: nonNumericalParameter, $options: 'i' } },
        { cnpj: { $regex: nonNumericalParameter, $options: 'i' } }
      ]
    });

    console.log('FIRST RESULT', firstResult);
    console.log('********************************************************')
    console.log('SECOND RESULT', secondResult);
}

run();
```

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 I simplified the repro script a little bit.
Is applying setters on regular expressions intended? I recall seeing an issue back in the day with a use-case that required us to implement this but I couldn't find it.

### 11425.js
```js
import mongoose from 'mongoose';
import assert from 'node:assert';
const { Schema } = mongoose;

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    phoneNumber: { type: String, set: getOnlyNumbers }
  });

  const User = mongoose.model('User', userSchema);

  await User.create([
    { phoneNumber: '32270838000191' },
    { phoneNumber: '67181891000109' }
  ]);

  const usersFromNumberRegex = await User.find({ phoneNumber: { $regex: '322', $options: 'i' } });
  assert.strictEqual(usersFromNumberRegex.length, 1);

  const usersFromStringRegex = await User.find({ phoneNumber: { $regex: 'no numbers', $options: 'i' } });
  assert.strictEqual(usersFromStringRegex.length, 0);
}

function getOnlyNumbers(string) {
  return string.replace(/[^\d]+/g, '');
}
```

### Output
```
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 0

    at run (file:///test.js:26:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 2,
  expected: 0,
  operator: 'strictEqual'
}
```

**Comment by jeremyben** [comment]
Same confusing problem and it's causing a lot of overhead, because I must encrypt (medical) data before it gets written to mongo.
I noticed that when I add the `default` option to a field, the setter always run on this default value with a `find` query (a simple `Model.find({})` for example). This for every document retrieved, which is useless cause I'm encrypting an unused default value a on read query.

**Comment by vkarpov15** [comment]
Fixed this in https://github.com/Automattic/mongoose/commit/caf821d7b29dce1895bf4c3aaf04cf3ca7b58b72 .

I took a closer look and calling setters on `$regex` is a bug. This is similar to #7800, where we made it so that setters aren't called on `$options`. Setters should be called when we're querying by a string, not a regexp.
