### ISSUE TITLE
Unable to update virtual fields using Model.findByIdAndUpdate()

### ISSUE THREAD

**Issue by NumanAnees** [Automattic/mongoose#11427]
# Problem
I have getter, setters and Schema methods for hashing the password but I'm unable to update virtual field/password using Model.findByidAndUpdate().

# Solution
It only works when I use Model.findById().

# Versions
Node: v16.13.1
npm: v8.1.3
mongoose: ^6.2.1

**Comment by vkarpov15** [comment]
Can you please provide some code samples that demonstrate what you're trying to do?
