### ISSUE TITLE
TS error on accessing this.model in middlewares in v6

### ISSUE THREAD

**Issue by piyushk96** [Automattic/mongoose#11435]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
Getting ts error while accessing one model in another schema's prevalidate middleware.

**If the current behavior is a bug, please provide the steps to reproduce.**
I was trying to access model using `this.model(model_name)` but getting typescript error `Property 'model' does not exist on type 'Item2Document'`(code actually works with `ts-ignore`). I have another codebase that uses mongoose v5 and this works perfectly in v5.

```
import mongoose from 'mongoose';
const { Schema } = mongoose;

const Item1Schema = new Schema({ name: String });
const Item2Schema = new Schema({ name: String });

Item2Schema.pre('validate', function preValidate() {
  const item1Model = this.model('Item1');  // Getting ts error here
})

const Item1 = mongoose.model('Item1', Item1Schema);
const Item2 = mongoose.model('Item2', Item2Schema);
```

**What is the expected behavior?**
Code should compile without any errors.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS = v14
MongoDB = v4.4.0
Mongoose = v6.2.2

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

interface Test {
    name: string;
}

const Item1Schema = new mongoose.Schema<Test>({ name: String });
const Item2Schema = new mongoose.Schema<Test>({ name: String });

Item2Schema.pre('validate', function preValidate() {
  const item1Model = this.model('Item1');  // Getting ts error here
  console.log(item1Model);
})

const Item1 = mongoose.model<Test>('Item1', Item1Schema);
const Item2 = mongoose.model<Test>('Item2', Item2Schema);
```

**Comment by Uzlopak** [comment]
It seems like Document is missing the model function in the typings and Schema is not narrowing correctly because TInstanceMethods (third generic typing of Schema) is set to any.

@IslandRhythms Please add typescript tag. :)

**Comment by Uzlopak** [comment]
here the typings test

```typescript
function gh11435() {

  interface Item {
    name: string;
  }
  const ItemSchema = new Schema<Item>({ name: String });

  ItemSchema.pre('validate', function preValidate() {
    expectType<Function>(this.model);
    expectType<Model<any, any, any>>(this.model('Item1'))
  })
}
```
