### ISSUE TITLE
Lambda initiating new mongoose connection for every request

### ISSUE THREAD

**Issue by abhibhaw** [Automattic/mongoose#11433]
I tried following this [docs](https://mongoosejs.com/docs/lambda.html) to connect mongoose through my lambda function but still the connection is not being persist. For every request it's opening a new db connection. Which results in performance issue and also unable to match with mongo connection limits.

Any possible solution to persist the db state in some external state?

**Comment by vkarpov15** [comment]
We did find a small issue in these docs that we fixed in https://github.com/Automattic/mongoose/commit/13a25985c1c5dabd897a3d64a2ffa23cf94130af, but that shouldn't cause issues in reusing the connection.

Can you please provide more detailed code samples and describe how you're testing your lambda?
