### ISSUE TITLE
model.syncIndexes should use model.diffIndexes under the hood

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#11430]
Currently, `Model.diffIndexes` [promises to do a dry-run of Model.syncIndexes()](https://mongoosejs.com/docs/api.html#:~:text=Does%20a%20dry%2Drun%20of%20Model.syncIndexes()%2C%20meaning%20that%20the%20result%20of%20this%20function%20would%20be%20the%20result%20of%20Model.syncIndexes().), we can not give that promise without actually relying on it in `Model.syncIndexes`, since it's really easy for the logic to diverge along the way.

What do you think? @vkarpov15

**Comment by vkarpov15** [comment]
I agree, but don't think that this should block shipping #11424.

**Comment by AbdelrahmanHafez** [comment]
My concern is that the logic for deciding which indexes to drop, and which ones to create _did_ change inside `cleanIndexes` and `ensureIndexes`.

AFAIK `diffIndexes` has, roughly, a copy of the logic deciding which indexes to drop, and which ones to create, they don't rely on the same internals, which means we can't assume the results will be the same.
