### ISSUE TITLE
Populate with match and transform included nulls in result

### ISSUE THREAD

**Issue by SergioArrighi** [Automattic/mongoose#11434]
**Do you want to request a *feature* or report a *bug*?**
I am not sure, sorry

**What is the current behavior?**
I'm using populate function to load objects into an array of my model.
I'm also using match to filter these objects.

Now I want to apply a function to the filtered list, but as soon as I use transform field of populate options I get a null value for each excluded object in output

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a schema
2. Create another schema with an array of string referring to other schema
3. Execute a find with populate on the ref field with a match condition
4. Try to apply transform
5. Verify that non matching objects are added as null

tsconfig.json
`{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}`

**What is the expected behavior?**
**Populate transform is applied only to objects which satisfy the match condition.**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs 17.4.0
MongoDB 5.0.4 Community
Mongoose 6.1.7

**Comment by IslandRhythms** [comment]
Can you provide the line where you make the populate call?
