### ISSUE TITLE
No method available to sort data on the basis of array.length

### ISSUE THREAD

**Issue by NumanAnees** [Automattic/mongoose#11441]
# Problem
I want to sort my result on the basis of Upvotes which is an array of object Id's.

```
   Upvotes: [{ type: ObjectId, ref: "User" }]
```
In mongoose it is not possible to use sort method like ``` .sort({ Upvotes.length: -1 })```
For solving this problem I have to make a new field of upvoteCount and sort using ``` .sort({ upvoteCount: -1 })```

**Comment by AbdelrahmanHafez** [comment]
Hello @NumanAnees 👋
It's not clear what it is that you're trying to achieve.
Please follow the issue template, thanks. 👍
