### ISSUE TITLE
Typescript typings missing for next() function

### ISSUE THREAD

**Issue by rkreienbuehl** [Automattic/mongoose#11449]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
As described in the docs, in pre-hooks the possibility to use `next()` is still there. I am about to update our code to mongoose `6.2.3` and we have a lot of mongoose middleware that uses `next()`.
Now all the imports for `HookNextFunction` don't work anymore because this type definition was removed with mongoose 6.

**If the current behavior is a bug, please provide the steps to reproduce.**

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

**What is the expected behavior?**
To have a type definition for the next function.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: `6.2.3`
node.js: `v16.13.1`

**Comment by Uzlopak** [comment]
If I understood it correctly, you want to type your hook functions but you are lacking the typings of the hook functions. PR #11485 exposes the Middleware Function Types. Would this solve your issue?

**Comment by vkarpov15** [comment]
I think the question is what to do now that `HookNextFunction` is no longer exported. You can still use `next()` callbacks with TypeScript in Mongoose 6, we just removed `HookNextFunction` because `HookNextFunction` is just `(err?: Error) => void`. So if you did this in Mongoose 5:

```ts
schema.pre('save', function(next: HookNextFunction) {
 // ...
});
```

You can just do this in Mongoose 6:

```ts
schema.pre('save', function(next: (err?: Error) => void) {
  // ...
});
```

**Comment by wasit-shafi** [comment]
Just for Additional Info: For those interested(including me) in looking at details of when the support for type **HookNextFunction** was removed refer to official docs: https://mongoosejs.com/docs/migrating_to_6.html#typescript-changes
