### ISSUE TITLE
Sluggish when Requests > minPoolSize [SOLVED]

### ISSUE THREAD

**Issue by emorling** [Automattic/mongoose#11460]
I am connecting Mongoose **6.2.3** with these settings:

``` 
mongoose.connect(process.env.MONGO_CONNECT, {
  useUnifiedTopology: true,
  useNewUrlParser: true,
  minPoolSize: 100, 
  maxPoolSize: 200,
})
```

I am running this code: (if it matters I am running 5 watches on parallel in the project)

```
ApiCallCue.watch().on('change', async (data) => {
     let startTime = performance.now();
     await ApiCallCue.findOneAndUpdate({ _id: data.documentKey._id }, { done: true, success: true }).lean();
     console.log(`Call took ${Math.floor((performance.now() - startTime))} ms`);
    });
```

At the start it runs fast. Updates using findOneAndUpdate take 1-3ms. 

As soon as 100 requests have been made, **which is exact same as minPoolSize**, the it takes 200-700ms instead. 

How to make it as fast as the first 100 requests? 
x

**Comment by Uzlopak** [comment]
This seems odd. Somehow I have the feeling that the semaphore in the mongo native driver has that performance issue. Because I think mongoose does not handle the connection pooling.

**Comment by Uzlopak** [comment]
Can you please provide a minimal reproducible code example please?

I would then be able to determine the potential bottleneck by digging deep.

**Comment by Uzlopak** [comment]
I wrote a mvce myself, but I can not reproduce your performance bottleneck? Maybe you can modify my mcve till you can reproduce it?
https://github.com/Uzlopak/mongoose-mvce/tree/perf-minPoolSize

**Comment by vkarpov15** [comment]
Because the MongoDB driver grows the connection pool once you have more than `minPoolSize` requests, and creating a new TCP socket connection to the MongoDB server is relatively slow. You can increase `minPoolSize`, or make `minPoolSize` exactly equal to `maxPoolSize` to avoid the overhead of creating new sockets, but then you can run into [slow trains](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs).

Also, out of curiosity, isn't the below code an infinite loop? You listen for changes on `ApiCallCue` and modify `ApiCallCue` every time there's a change...

```javascript
ApiCallCue.watch().on('change', async (data) => {
     let startTime = performance.now();
     await ApiCallCue.findOneAndUpdate({ _id: data.documentKey._id }, { done: true, success: true }).lean();
     console.log(`Call took ${Math.floor((performance.now() - startTime))} ms`);
    });
```

**Comment by emorling** [comment]
> You can increase `minPoolSize`, or make `minPoolSize` exactly equal to `maxPoolSize` to avoid the overhead of creating new sockets, but then you can run into [slow trains](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs).

I think this is the problem, but not sure how to fix it. I am trying minPoolSize and maxPoolSize to be 100 now.

> Also, out of curiosity, isn't the below code an infinite loop? You listen for changes on `ApiCallCue` and modify `ApiCallCue` every time there's a change...

I have this to avoid the loop, but removed it from my earlier example:

```
ApiCallCue.watch().on('change', async (data) => {
     **if (data.operationType === 'insert'){**
       let startTime = performance.now();
       await ApiCallCue.findOneAndUpdate({ _id: data.documentKey._id }, { done: true, success: true }).lean();
       console.log(`Call took ${Math.floor((performance.now() - startTime))} ms`);
    });
});
```

**Comment by emorling** [comment]
Ok, I found the issue and fault is entirely my own. I was creating a new watch().on('change') on each function call, and not closing it properly.
