### ISSUE TITLE
Typescript no Type Hint for overriding Query.

### ISSUE THREAD

**Issue by minhthinhls** [Automattic/mongoose#11473]
@see {@link https://github.com/Automattic/mongoose/blob/master/types/index.d.ts#L2277}
On line 2277. The path type `path: string | any` should not contains any here !!!

**Comment by Uzlopak** [comment]
Well the type expanding is an issue but I guess you want also have the ability to use query operators. I guess this is the reason for the any.

**Comment by vkarpov15** [comment]
Fixed in #11475
