### ISSUE TITLE
mongoose.model() vs. db.model()

### ISSUE THREAD

**Issue by pkyeck** [Automattic/mongoose#1147]
these two should be the same (if I'm using only one connection), right!?
taken from the website:

```
var schema = new Schema({ name: 'string', size: 'string' });
var Tank = mongoose.model('Tank', schema);

// or, if you are using separate connections
var db = mongoose.createConnection(..);
var Tank = db.model('Tank', schema);
```

if I'm doing a 

```
Tank.findOne({id:'xxx'}, function () {//...});
```

after using the `mongoose.model()` the callback is never called - whereas if I use `db.model()` I get the expected result.
am I doing something wrong? Is this a bug?

**Comment by ljchengx** [comment]
The problem that troubled a noon, finally solved, thank.
