### ISSUE TITLE
The this type in middleware hook  always resolves to any

### ISSUE THREAD

**Issue by iammola** [Automattic/mongoose#11480]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
I want to use the `this` type in the pre-save middleware I've added to my schema. But the `this` always resolves to `any` with Typescript. I normally read through your index.d.ts file and I know the `this` type is defined, so I don't like importing extra things from mongoose because of the extra space since it's already there. 

The `pre` method's generic argument is set to be this HydratedDocument you pass other type arguments to.
https://github.com/Automattic/mongoose/blob/18cb0bed7256784701d7b75e160707895a0e50db/types/index.d.ts#L1194-L1196
The `TInstanceMethods` type defaults to `any`, and in the `HydratedDocument` absorbs the other types and everything resolves to `any`.

This is the case in many other places and I understand why `any` is used, but I want to ask if you can consider using `unknown` or `{}` for those types you expect to be an object in any case. Like the methods or query helpers. You already do this with the Model definition ⬇️ 
https://github.com/Automattic/mongoose/blob/18cb0bed7256784701d7b75e160707895a0e50db/types/index.d.ts#L594

**If the current behaviour is a bug, please provide the steps to reproduce.**
```js
import { Schema } from "mongoose";

type IUserSchema = {
	name: string;
}

const UserSchema = new Schema<IUserSchema>({ name: { type: String } });

UserSchema.pre("save", function (next) {
	this.name; // Unsafe member access .name on an `any` value
	next();
});
```

***If you are using TypeScript, please include your `tsconfig.json`***
```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.JS"],
  "exclude": ["node_modules", ".next", "out"]
}
```

**What is the expected behaviour?**
The `this` type to be properly types

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
Node.JS - 17.6.0
Mongoose - 6.2.4
MongoDB - 4.3.1
```

**Comment by vkarpov15** [comment]
I confirmed this issue was fixed in v6.2.7 with the fix for #11435. Please upgrade to v6.2.7 for the fix :+1:
