### ISSUE TITLE
Ghost collections auto-created for each subdocument

### ISSUE THREAD

**Issue by sandorvasas** [Automattic/mongoose#11498]
**Do you want to request a *feature* or report a *bug*?** 
BUG

**What is the current behavior?** 
I don't know since when this is happening, I just noticed recently that empty collections were created in our DB. one collection for each subdocument in the schema. For example, if we have a schema like 
```js
export const PawSchema = new mongoose.Schema({
  size: Number,
  temperature: Number
});
export const PawModel = mongoose.model('Paw', PawSchema)

export const DoggoSchema = new mongoose.Schema({
  chonkiness: Number,
  paws: [PawSchema]
}, {
  timestamps: {
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
  },
  collection: 'doggos',
});
export const DoggoModel = mongoose.model('Doggo', DoggoSchema)
```
Results in two automatically created collections: paws and doggos. This had not been happening before. collection above is only defined for doggos, so it should only create doggos, as before.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 6.2.1
Node 16.14
MongoDB 4.4.12

**Comment by sandorvasas** [comment]
Can be disabled with `mongoose.set('autoCreate', false)`

**Comment by sandorvasas** [comment]
Thanks.

**Comment by sandorvasas** [comment]
np

**Comment by Uzlopak** [comment]
Actually when do you use PawModel?

**Comment by Uzlopak** [comment]
I assume you never actually need PawModel, so you can delete PawModel.

**Comment by sandorvasas** [comment]
It actually didn't work. Ghost collections are still created all around. I even tried setting `{ autoCreate: false }` on all the schemas.
I do need PawModel for example when pushing new PawModel({...}) into another model's nested array.

**Comment by vkarpov15** [comment]
@sandorvasas you don't need `PawModel` if all you're doing is pushing onto another model's nested array. In general, if you don't need a collection, you don't need a model.
