### ISSUE TITLE
Updating the path 'batches' would create a conflict at 'batches'

### ISSUE THREAD

**Issue by Ajju2211** [Automattic/mongoose#11500]
Error: ` MongoServerError: Updating the path 'batches' would create a conflict at 'batches'`
I am getting this error when I run updateMany in mongoose 6.1.6
`const presSubLatestBatch  = 2021;`
``await File.updateMany({ subject: subId }, { $addToSet: { batches: (presSubLatestBatch - 1) }, $pull: { batches: presSubLatestBatch }}); ``

this is the part of the schema  of the file.
batches: [{

        type: Number,

        min: 2005,

        required: true
    }],

**Comment by Uzlopak** [comment]
It is a MongoServerError, so it is an issue on the Mongo Server side.

It is basically this issue
https://stackoverflow.com/questions/24300148/pull-and-addtoset-at-the-same-time-with-mongo
