### ISSUE TITLE
NX Next.JS app fails to build on v6.2.5

### ISSUE THREAD

**Issue by anthonyma94** [Automattic/mongoose#11511]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When I try to build my app, it throws this error:
```
../../node_modules/mongoose/types/cursor.ts:1:1
Type error: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} 
from "mod"', 'import d from "mod"', or another module format instead.

> 1 | import stream = require('stream');
    | ^
  2 |
  3 | declare module 'mongoose' {
  4 |   type CursorFlag = 'tailable' | 'oplogReplay' | 'noCursorTimeout' | 'awaitData' | 'partial';
```

Downgrading to v6.2.4 fixes the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "commonjs",
    "lib": ["es2017", "dom", "ES2021.String", "ESNext.String"],
    "typeRoots": ["./@types", "./node_modules/@types"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "strictNullChecks": true,
    "baseUrl": ".",
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsxImportSource": "@emotion/react"
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "next-env.d.ts",
    "../../libs/services/**/*",
    "../../libs/utils/general-utils/**/*",
    "../../libs/utils/react-utils/**/*"
  ],
  "exclude": ["**/*.spec.tsx", "**/*.spec.ts", "**/*.stories.tsx"]
}

**What is the expected behavior?**
App should build without issue.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by sirily11** [comment]
I have the same issue!

**Comment by SimonHausdorf** [comment]
referencing #11512

**Comment by jansedlon** [comment]
Also causing issues in Remix

**Comment by Uzlopak** [comment]
In regard to avoid again such a regression I added in #11516 logic to validate that we only have .d.ts files in types folder.
