### ISSUE TITLE
Populate typings breaking changes with v6.2.5

### ISSUE THREAD

**Issue by patchimou** [Automattic/mongoose#11518]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Typings with populate expect a `string` for the path parameter, before it was typed with `any`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Until version 6.2.5, I used populate with an array when populating multiple fields, like `.populate(['field1', 'field2'])`

Typescript version: 4.5.5

**What is the expected behavior?**
I don't know if this is wanted, but upgrading to v6.2.5 is a breaking change.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS version: 14

**Comment by Uzlopak** [comment]
In #11503 we already improve the typing of populate. I also mentioned a potential fix for this issue.

**Comment by vkarpov15** [comment]
Sorry for the trouble, fix will be in v6.2.6 :+1:

**Comment by Uzlopak** [comment]
Should be fixed now. If the bug still exists after you updated mongoose, then feel free to reopen an issue.
