### ISSUE TITLE
Is there a bug in $pull？

### ISSUE THREAD

**Issue by HandsomeTea** [Automattic/mongoose#11510]
version：
`"mongoose": "^6.2.1"`

my data structure in mongodb like this：

```
{
    _id: ... ,
    ... ,
    services: {
         resume: {
                loginTokens: [{
                     type: "ws",
                     uniqueInfo: {
                          serialNumber: "abcd"
                     }
                }, ...]
         }
    }
}
```

my code:

```javascript
<mongooseModel>.updateOne({ _id: '***' }, {
    $pull: {
        'services.resume.loginTokens': {
            'uniqueInfo.serialNumber': 'abcd'
        }
    }
});
```

It doesn't work! but:

```javascript
<mongooseModel>.updateOne({ _id: '***' }, {
    $pull: {
        'services.resume.loginTokens': {
            type: 'ws'
        }
    }
});
```

worked!

if I put the same condition on the mongodb command line:

```javascript
db.getCollection('***').update({ _id: '***' }, {
    $pull: {
        'services.resume.loginTokens': {
            'uniqueInfo.serialNumber': 'abcd'
        }
    }
});
```

success!

I repeatedly confirmed that all my data and conditions were OK.

I suspect there is a problem with the support of `$pull` conditions for multi-layer objects, I don't know whether mongoose is designed like this or whether it's a problem, but anyway, mongodb supports this syntax.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    array: [{information: {data: String}}]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const entry = await Test.create({
        array: [{information: {data: 'Hello'}}]
    });
    console.log(await Test.findOne());
    await Test.updateOne({_id: entry._id}, {$pull: {array: {information: {data: 'Hello'}}}});
    console.log(await Test.findOne());
}

run();
```

**Comment by IslandRhythms** [comment]
Try updating to the latest version of mongoose and see if that fixes it.

**Comment by Uzlopak** [comment]
Maybe it is related that he uses dot notation in his original script?

**Comment by HandsomeTea** [comment]
Thank you for your attention! Thanks♪(･ω･)ﾉ

we have changed the data structure because of the pressing time of publishing. using the following code test, the result is correct, but the deletion of array item `{ 'uniqueInfo.serialNumber': 'abcd' }` failed at that time, which is very strange
```
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    _id: String,
    services: Object
}, { _id: false, versionKey: false });

const Test = mongoose.model('Test', testSchema, 'Test');
const _id = 'ubiD55QmTjipqhrBo';

async function run() {
    await mongoose.connect('mongodb://localhost:27017/pull_test');

    await Test.create({
        _id,
        services: {
            resume: {
                loginTokens: [{
                    type: "ws",
                    uniqueInfo: {
                        serialNumber: "abcd"
                    }
                }, {
                    type: "ws",
                    uniqueInfo: {
                        serialNumber: "test"
                    }
                }]
            }
        }
    });
    console.log(JSON.stringify(await Test.findOne()));
    await Test.updateOne({ _id }, { $pull: { 'services.resume.loginTokens': { 'uniqueInfo.serialNumber': 'abcd' } } });
    console.log(JSON.stringify(await Test.findOne()));
}

run();
```

**Comment by Uzlopak** [comment]
Please provide a reproducable script, so that we can investigate it.

**Comment by jpedro73** [comment]
### controller

`
if(req.params.type=='checkTransaction'){
    console.log('checkTransaction')
    let session
    try {
      session= await mongoose.startSession()

      session.startTransaction()
      
      const allTransfers_aux=await DEPARTMENTS.find({'code':'Dep04'},{'_id':0, 'cashParams.trfItems':1})
      const allTransfers=cloneDeep(allTransfers_aux)

      let result={'resultSession':'initial', 'trfsInCenter':'initial', 'detailled':null}, trfsInCenter=[]
      
      for(let trfItem of allTransfers[0].cashParams.trfItems){
        if(trfItem.itemToReplace!=undefined){
          trfsInCenter.push(trfItem.itemToReplace)
        }
      }
      
      if(trfsInCenter.length>0){

        let intId=await CASHIER.aggregate([
          {$match:{'cashier':req.params.center, 'intId':/^((?!jp).)*$/}},
          {$group:{_id:null, 'max':{$max:'$intId'}}}
        ])
        
        intId.length==0 ? intId=0 : intId=intId[0].max.slice(6)*1+1
        
        console.log({intId})
        for(let item of trfsInCenter){
          item.intId=req.params.center+'-'+intId
          item.in=item.in*1
          item.out=item.out*1
          item.vat=item.vat*1
          intId++
        }
        const saveItems=await CASHIER.create(trfsInCenter, {session})//! here create the items
        const deleteItems=await DEPARTMENTS.updateOne({'code':'Dep04'}, {$pull:{'cashParams.trfItems':{'itemToReplace.cashier':req.params.center}}}, {session})//! here remove the items
        console.log({trfsInCenter, saveItems, deleteItems})

        if(saveItems.length==0 || saveItems.length!=deleteItems.nModified || deleteItems.nModified==0){   
          console.log('ERROR')       
          throw {'savedItems':saveItems.length, 'confirmedDelted':deleteItems.nModified}
        }else {
          result.resultSession=await session.commitTransaction()
          result.trfsInCenter=trfsInCenter
          result.detailled={'savedItems':saveItems.length, 'confirmedDelted':deleteItems.nModified}
          console.log({result})
        }
        
      }

      res.json({
        'status':'success',
        'statusCode':200,
        'data':result
      })
    
    } catch (error) {
      console.log(error)
      console.log('NO TRANSACTION!')
      await session.abortTransaction()
      res.json({
        'status':'error',
        'statusCode':500,
        'error':error
      })
      
    }finally {
      // ending the session
      console.log('ENDSESSION')
      session.endSession()
    }
    `

**Comment by jpedro73** [comment]
The issue is in:
`const deleteItems=await DEPARTMENTS.updateOne({'code':'Dep04'}, {$pull:{'cashParams.trfItems':{'itemToReplace.cashier':req.params.center}}}, {session})//! here remove the items
console.log({trfsInCenter, saveItems, deleteItems})`

Even if the command does not belong to a transaction, the error occurs in the same.

Before refacted the bd it works fine
the bd before was:

```
{
  "_id": "609979a99fd8114df0a6056e",
  "centers": [...],
  "code": "Dep04",
  "cashParams":{
     "type": [...],
      ....
      "cashiers": [...],
      "remindItems": [...],
      "trfItems":
          [
            { 
                "itemToReplace": {
                   "cashier": "CX093",
                    "category": null,
                     "cc": null,
                     "date": "2022-03-20",
                     "docId": null,
                     "costType",
                     ....
              }
            ]
}
```
and the command was:
`const deleteItems=await DEPARTMENTS.updateOne({'code':'Dep04'}, {$pull:{'cashParams.trfItems':{'cashier':req.params.center}}}, {session})`

**Comment by jpedro73** [comment]
now the result of deleteItems is:

`deleteItems: {
    acknowledged: true,
    modifiedCount: 0,
    upsertedId: null,
    upsertedCount: 0,
    matchedCount: 1
  }`

**Comment by jpedro73** [comment]
now is a bug in the code, it will always trow a error because in the code is nModified instead of modifiedCount, but that was in the previouse 5.2 mongoose version, yesterday i've updated to 6.3.0 and today to 6.3.1

But the issue is in the result of the deleteItem, i don't updated the code for the transaction

**Comment by jpedro73** [comment]
for talk about nModified and modifiedCount, this change will cause many bugs in the apps, like in my case, i was cashing the error in nModified and now you change to modifiedCount, even if the command works well it will always abort the transaction.
Is my opinion :)

**Comment by vkarpov15** [comment]
@jpedro73 looks like the issue is due to Mongoose 6 changing `nModified` to `modifiedCount`. See [migration guide](https://mongoosejs.com/docs/migrating_to_6.html#mongodb-driver-40).

**Comment by brandart** [comment]
it still occurs: https://mongoplayground.net/p/H0QSu7JvFWh
when I run this query with mongoose it does not work
