### ISSUE TITLE
Does not compile with TypeScript

### ISSUE THREAD

**Issue by flyboarder** [Automattic/mongoose#11512]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Unable to compile due to message `Cannot find type definition file for 'mongoose/types/cursor'.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Try compiling with any typescript project.

**What is the expected behavior?**
Compiles without errors.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 6.2.5

Seems the types cursor file is of the wrong file extension. Needs to change from `.ts` to `.d.ts`

https://github.com/Automattic/mongoose/blob/master/types/cursor.ts

**Comment by flyboarder** [comment]
As a follow up to this, it seems Typescript is still passing GitHub checks, those aren't currently working.

**Comment by bke-daniel** [comment]
I can confirm both

**Comment by Uzlopak** [comment]
I will have a look at it.

**Comment by Uzlopak** [comment]
Which version of typescript do you use and what is your tsconfig?

**Comment by Uzlopak** [comment]
I see it. I messed up with the filename. It should have been cursor.d.ts and not cursor.ts.

**Comment by Uzlopak** [comment]
In regard to avoid again such a regression I added in https://github.com/Automattic/mongoose/pull/11516 logic to validate that we only have .d.ts files in types folder.
