### ISSUE TITLE
Subdocument Array of Objects Schema causes "Cast to array failed for value" validation error when you use `...` spread operator versus toObject() for inheritance

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#11522]
Hey @vkarpov15 - hope all is well.

I'm writing as this was a frustrating bug to track down.  I believe this worked in version 5 of Mongoose, but I could be wrong and this totally has never worked since I switched to use `...` spread operator here for inheriting the object.

Here's the diff showing the fix I had to do to avoid the issue:

```diff
  // swap the user group based off ctx.request.body.group
  ctx.state.domain.members = ctx.state.domain.members.map((member) => ({
-    ...member,
+    ...member.toObject(),
    group:
      member.user.toString() === ctx.params.member_id
        ? ctx.request.body.group
        : member.group
  }));

// ...

await ctx.state.domain.save(); // save the domain here causes the validation error
```

<img width="1038" alt="Screen Shot 2022-03-11 at 5 57 34 PM" src="https://user-images.githubusercontent.com/523141/158029816-bf21f849-38e0-4f86-8fc1-516c353b2e5a.png">

The schema is defined here https://github.com/forwardemail/forwardemail.net/blob/master/app/models/domain.js#L131 and here https://github.com/forwardemail/forwardemail.net/blob/master/app/models/domain.js#L45-L58 (pretty simple).

**Comment by niftylettuce** [comment]
Note this only happens when you don't use `lean()` and don't have a Mongoose object.

**Comment by Uzlopak** [comment]
toObject is basically transforming the hydrated Document to a lean Object. Probably when casting we have to check if it is a hydrated Document and lean it.

**Comment by vkarpov15** [comment]
I'll try to repro this. However, in general, I'd recommend using `.toObject()` with spread operator. Because spread operator iterates through the actual object's keys, doing `...member` gives you a [POJO](https://masteringjs.io/tutorials/fundamentals/pojo) with Mongoose document internals like `$__` and `_doc`.

**Comment by vkarpov15** [comment]
Confirmed and fixed. Although I still would strongly recommend doing the below instead:

```javascript
for (const member of ctx.state.domain.members) {
  member.group = member.user.toString() === ctx.params.member_id
        ? ctx.request.body.group
        : member.group;
}
```

You're not writing React here - by shallow cloning the array and all the documents you're incurring an unnecessary performance penalty and making your code more complex.

**Comment by titanism** [comment]
@vkarpov15 this rewrite to use the loop will throw the following error `Cast to ObjectId failed for value "[Circular]" (type string) at path "_id"` on latest version of Mongoose

```js
  for (const member of ctx.state.domain.members) {
    if (member.user.toString() === ctx.params.member_id)
      member.group = ctx.request.body.group;
  }
```

**Comment by titanism** [comment]
@vkarpov15 we've confirmed that the fix is the following:

```js
  // swap the user group based off ctx.request.body.group
  ctx.state.domain.members = ctx.state.domain.members.map((member) => {
    return {
      user: member.user,
      group:
        member.user.toString() === ctx.params.member_id
          ? ctx.request.body.group
          : member.group
    };
  });
```

Can you please look into the Mongoose internals to figure out why this happens?  This 100% a mongoose bug.

**Comment by vkarpov15** [comment]
@titanism I'm trying to figure out why your original example doesn't work. Looking at https://github.com/forwardemail/forwardemail.net/commit/9e3ec850d4461c465293147cdd6fac5743035698#diff-93a5248c3ab689a90e0344028135658b7cf18f44872ed83ecc329f9e912342c9, why is the original code:

```javascript
  for (const member of domain.members) {
    if (member.user.toString() === ctx.params.member_id)
      member.group = ctx.request.body.group;
  }
```

and not the below? Loop should be over `ctx.state.domain.members`

```javascript
for (const member of ctx.state.domain.members) {
    if (member.user.toString() === ctx.params.member_id)
      member.group = ctx.request.body.group;
  }
```
