### ISSUE TITLE
`model.createCollection` fails for capped collection when using `capped: number`

### ISSUE THREAD

**Issue by mhassan1** [Automattic/mongoose#11539]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Calling `model.createCollection` for a model that specifies `capped: number` throws an error: `MongoServerError: the 'size' field is required when 'capped' is true`. Specifying `capped: { size: number }` instead throws no error.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
await mongoose.model('thing', new mongoose.Schema({ name: String }, { capped: 100 })).createCollection()
// -> MongoServerError: the 'size' field is required when 'capped' is true

await mongoose.model('thing', new mongoose.Schema({ name: String }, { capped: { size: 100 } })).createCollection()
// -> no error
```

It seems like the logic at https://github.com/Automattic/mongoose/blob/c5893fa9f6d652d2bed08a52ad58f0f875e34bb4/lib/model.js#L1370 does not properly account for the `capped: number` scenario.

**What is the expected behavior?**

No error is thrown

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

`node`: 16.14.0
`mongoose`: 6.2.4
`mongodb`: 4.4

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const failSchema = new mongoose.Schema({
    name: String
}, {capped: 100});

const passSchema = new mongoose.Schema({
    name: String,
}, {capped: {size: 100}})

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await mongoose.model('thing', failSchema).createCollection();
}

run();
```
