### ISSUE TITLE
Current value does not work 

### ISSUE THREAD

**Issue by lunamcsv** [Automattic/mongoose#11548]
![Screenshot from 2022-03-21 14-59-41](https://user-images.githubusercontent.com/69607389/159223627-b2b29958-77fc-47dd-a004-13c3f26ce4f8.png)
![Screenshot from 2022-03-21 14-57-34](https://user-images.githubusercontent.com/69607389/159223637-62892593-1085-4caf-bd89-199d0d5cea16.png)

It return []
$limit is not working
if I replace $limit with 1. It will work
What problem happened? help me

**Comment by Uzlopak** [comment]
https://www.mongodb.com/docs/manual/reference/operator/query/gte/
$gte expects a value and not a field or expression.

So you have to use $expr.

https://stackoverflow.com/questions/16042315/mongo-field-a-greater-than-field-b
