### ISSUE TITLE
Typescript issue/improvement on virtual(s) definitions

### ISSUE THREAD

**Issue by Jule-** [Automattic/mongoose#11543]
**Do you want to request a *feature* or report a *bug*?**
IMHO, it is more a type bug than a feature but you will judge.

**What is the current behavior?**
When defining `virtual`, function `this` scope is not set.

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
interface Input {
  firstname: string;
  lastname: string;
}

interface InputVirtuals {
  fullname: string;
}

type InputModel = Model<Input, {}, {}, InputVirtuals>;

const inputSchema = new Schema<Input, InputModel, InputVirtuals>({})

inputSchema.virtual("fullname").get(function () {
  return `${this.firstname} ${this.lastname}`;
  // 'this' implicitly has type 'any' because it does not have a type annotation. ts(2683)
});
```

**What is the expected behavior?**
Obviously, we can enforce `this: HydratedDocument<DocType, TInstanceMethods>` when defining the function, but it feels odd since we are not responsible for the calling context.
I expect that type definitions are enforcing it.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`mongoose@6.2.5`

-----

I am not really sure about the right type for `this` but despite this, it could look like:
https://github.com/Automattic/mongoose/blob/75ca68b9d511513efeb369c0f9af0e2815837836/types/index.d.ts#L1203-L1215

Becomes:
```ts
  class VirtualType<HydratedDocType> {
    /** Applies getters to `value`. */
    applyGetters(value: any, doc: HydratedDocType): any;

    /** Applies setters to `value`. */
    applySetters(value: any, doc: HydratedDocType): any;

    /** Adds a custom getter to this virtual. */
    get(fn: (this: HydratedDocType) => any): this;

    /** Adds a custom setter to this virtual. */
    set(fn: (this: HydratedDocType) => void): this;
  }
```
```ts
    /** Creates a virtual type with the given name. */
    virtual<T = HydratedDocument<DocType, TInstanceMethods>>(name: string, options?: VirtualTypeOptions<T>): VirtualType<T>;

    /** Object of currently defined virtuals on this schema */
    virtuals: M extends Model<infer A, infer B, infer C, infer D> ? D : never;

    /** Returns the virtual type with the given `name`. */
    virtualpath<T = HydratedDocument<DocType, TInstanceMethods>>(name: string): VirtualType<T> | null;
```

NB: this proposal needs testing and an insider's eye.

**Comment by Jule-** [comment]
I have just seen https://github.com/Automattic/mongoose/pull/10350, maybe my approach is halfway to an ideal solution, but I feel like it is still better than `any`.

**Comment by Jule-** [comment]
@vkarpov15 thanks for taking care of this one! :slightly_smiling_face:
Can I just ask why letting `any` on `virtuals` while you have the type defined in `M`?

**Comment by vkarpov15** [comment]
@Jule- you can add multiple getters to a virtual, and those getters are called in order. Since a getter returns `any`, the `value` param has to be `any` because Mongoose calls the 2nd getter with the return value of first getter.

```javascript
schema.virtual('myTest').get(() => 'hello').get(() => 42); // `myTest` will always be 42
```

**Comment by Jule-** [comment]
@vkarpov15 thanks for the explanation, I didn't be aware of this pattern. Are you really talking about `virtuals` with an `s` or it is somehow hard linked to your example? You've lost myself a little bit... 😅 Because I thought Schema allows providing virtuals interface in generic parameters and I can't really see how you can use your pattern with `virtuals` (with an `s`).

Even if I am sure there is some usefulness to this pattern, I admit I can't really see the point to chain getters instead of just using one getter which chain methods inside its body... 🤔

**Comment by vkarpov15** [comment]
There's a method called `virtual()` on a `Schema` that you use to define virtuals. Not sure what you're talking about.

Re: chaining getters, admittedly we don't use that feature often. But it's a feature we support, so our types should reflect that.

**Comment by Jule-** [comment]
Sorry I don't want to waste your time, if it's just irrelevant you can ignore. I was talking about this line:
https://github.com/Automattic/mongoose/blob/75ca68b9d511513efeb369c0f9af0e2815837836/types/index.d.ts#L891-L892

**Comment by vkarpov15** [comment]
Oh that's what you're referring to. Thanks for your patience. I'll re-open this and see if we can make that change.

**Comment by vkarpov15** [comment]
Unfortunately we can't do the `infer` approach because it causes serious performance issues with the TypeScript compiler. Before:

```
$ node ./benchmarks/typescript.js 
simple instantiations: 40933
simple memory used: 146771.7
simple check time: 3.571
simple total time: 5.398000000000001
```

After:

```
$ node ./benchmarks/typescript.js 
simple instantiations: 254622
simple memory used: 198186
simple check time: 4.607
simple total time: 6.3549999999999995
```

We'll have to add another generic param to `Schema` that contains `TVirtuals`.

**Comment by Jule-** [comment]
Ok thanks for the try and for doing typescript benchmarks! :wink:
