### ISSUE TITLE
[Feature] Schema#removeIndex(...)

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#11547]
I came across a case where I cloned a schema, and would like to reuse it in another model without the indexes.
The issue is that the cloned schema includes its indexes, and there is no official way to remove indexes, I had to access `schema._indexes` which doesn't work with TS.

```js
const cartSchema = new Schema({ customerId: String, products: [productSchema]  });
cartSchema.index({ customerId: 1 }, { unique: true });

const cartSchemaClone = cartSchema.clone();

cartSchemaClone._indexes = []; // there is no other way to do it.

const checkoutSchema = new Schema({ cart: cartSchemaClone });
```

**Comment by AbdelrahmanHafez** [comment]
Turns out `cartSchemaClone._indexes = [];` doesn't really remove all indexes, it only removes the top-level paths indexes and ignores nested paths indexes.

The workaround that I found for removing all indexes:
```js
const cartSchemaClone = cartSchema.clone();
cartSchemaClone.set('excludeIndexes', true); // ignore _all_ indexes
const checkoutSchema = new Schema({ cart: cartSchemaClone });
```

This fixes my issue, but would become a problem once I need to add some indexes. I think we need to provide:
`Schema#clearIndexes` and `Schema#removeIndex`.

**Comment by vkarpov15** [comment]
We should support both schema.removeIndex('my-index-name') and schema.removeIndex({ status: 1 }) . The latter should remove any index that is deep equal to the given spec.

**Comment by AbdelrahmanHafez** [comment]
I agree that removing an index from schema shouldn't touch MongoDB.

For deep equality check, I think we should check both the index definition and the options. Also, deep equality check should treat objects with the same properties in different order as equal.

For string index names, I am not sure if they're unique or not, one other concern, AFAIK people can set a custom index name, if we wanna match with the index name, does that mean we'll need to fetch indexes from the database? Needing to fetch indexes means we'll have to tie the index removal with database connections.

I think supporting string index names, knowing that users can set custom indexes names, will introduce more issues than the feature requires, deep equality check should do the trick.
