### ISSUE TITLE
Error [ERR_INTERNAL_ASSERTION]: Error [ERR_INTERNAL_ASSERTION]: Error [ERR_INTERNAL_ASSERTION]: TypeError: Cannot read properties of undefined (reading 'paths')

### ISSUE THREAD

**Issue by skaplun** [Automattic/mongoose#11556]
When user logs in, data is loaded from DB using mongoose and this appears to be happening correctly. 
Afterwards, when user refreshes the page, which doesn't involve mongoose, am getting the below error

![image](https://user-images.githubusercontent.com/1812248/159694854-a3969844-ea67-45dd-b3fc-c31e7a650cef.png)

issue happening here:
![image](https://user-images.githubusercontent.com/1812248/159696125-03acee28-a4d2-42c1-b021-0f8ac71b50ef.png)

Why would this function be called with undefined arguments? what's causing this?

help?

**Comment by skaplun** [comment]
adding .lean() solved the issue

**Comment by IslandRhythms** [comment]
@skaplun There is not enough information presented in the report to create a reproduction script. Please elaborate on what the user is doing when they log in or provide a script that demonstrates the process.

**Comment by saver711** [comment]
downgrade to v 7
