### ISSUE TITLE
findOneAndReplace throws validation errors with runValidators: false

### ISSUE THREAD

**Issue by eliw00d** [Automattic/mongoose#11559]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*. But, if it is not a *bug*, then request a *feature*.

**What is the current behavior?**
ValidationErrors are thrown when using the runValidators: false option in findOneAndReplace.

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a model with required fields and try to findOneAndReplace without required fields and with runValidators set to false.

**What is the expected behavior?**
ValidationErrors are not thrown when using the runValidators: false option in findOneAndReplace.

Basically, we want to be able to soft delete a document by replacing it with fewer fields than is normally required without triggering validation.

I searched for findOneAndReplace + runValidators in Issues and found [this](https://github.com/Automattic/mongoose/issues/11206#issuecomment-1035248127mo). Although the issue is about `overwriteDiscriminatorKey` it did include a snippet for findOneAndReplace with runValidators, so unless it was a copy & paste error it would seem it should be supported?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 16.13.0
Mongoose: 6.2.8
MongoDB: 4.4.6-8

**Comment by IslandRhythms** [comment]
Good catch on the typo.

**Comment by eliw00d** [comment]
It's worth pointing out that switching from findOneAndReplace to replaceOne works as expected.
