### ISSUE TITLE
Queries do not return if there was a connection error

### ISSUE THREAD

**Issue by marcelklehr** [Automattic/mongoose#1156]
I don't want my app to exit, if there's an error in the db connection (so, users can be shown some 503 page).
So, I listen on the connection error event, but I just log possible errors to the console.

Now, say db connect has failed, and a request comes in, the app queries the db (e.g. with `<Model>.find`), but the callback isn't even called. So, the request just times out at some point...

**Comment by Billy-** [comment]
I am encountering this issue... Is there a way to at least provide a timeout so that the query will fail / throw an error if the query takes too long?

**Comment by Dewb** [comment]
For posterity's sake, it looks like an option to disable command buffering was indeed added: https://mongoosejs.com/docs/guide.html#bufferCommands
