### ISSUE TITLE
Remove `on` from schema reserved keys

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#11580]
We need to verify that people can use `on` as a path in their schemas.

**Comment by vkarpov15** [comment]
I confirmed that you can use `on` as a schema path. You get a warning that you can suppress using the `supressReservedKeysWarning` option.

As far as Mongoose itself is concerned, we don't need to warn about `on` as a reserved key. Documents support `$on` as an alternative, and Mongoose uses `$on` internally in the [couple of places where we use documents as event emitters internally](https://github.com/Automattic/mongoose/blob/0ecae5cec34064224f57400159c51f994ce32af7/lib/types/subdocument.js#L408-L409). My only concern is plugins that rely on `.on()`.

@AbdelrahmanHafez what do you think about removing `on` from reserved keys in a minor release?

**Comment by AbdelrahmanHafez** [comment]
Nice.
Sounds good, there should be no risk in releasing this in a minor release. I'm anticipating that in a couple of years plugins will break due to those changes, but then again the fix is easy on the plugins' end. 👍
