### ISSUE TITLE
How to delete specify field in Doc of Model ? 

### ISSUE THREAD

**Issue by HypeNeutron** [Automattic/mongoose#11583]
# This is My Code

## In My DB
` {
    _id: ObjectId("623d33658f98242178ffc638"),
    name: 'Peach',
    rating: 8,
    review: 'Noice fruit',
    __v: 0
  }`

## And Command  it not like node driver native ? 
`await Fruit.updateOne({ rating: 8 }, { $unset: { review: "" } })`

**Comment by AbdelrahmanHafez** [comment]
Welcome, @HypeNeutron 👋
The syntax you've provided should work.

If not, please provide more details on your schema and model definition. Are you using any pre-hooks?

**Comment by Uzlopak** [comment]
Isn't it removed if set to null?

**Comment by AbdelrahmanHafez** [comment]
Setting a field to `null` will keep the field in the document with the value `null` to it.
`$unset`ting a field will remove it from the document entirely.
