### ISSUE TITLE
Missing options attribute for aggregation type

### ISSUE THREAD

**Issue by GO-DIE** [Automattic/mongoose#11594]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The type declaration file is incomplete. I can't find [Aggregate.prototype.options](https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-options) in type declaration file.

**Comment by Uzlopak** [comment]
@GO-DIE 

I created a PR #11628 which should fix this issue. Maybe you want to have a look
