### ISSUE TITLE
[Types] `populate('path', 'selection', model)` syntax not supported in types

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11598]
**Do you want to request a *feature* or report a *bug*?**
types

**What is the expected behavior?**
from what i can tell the syntax `doc.populate('path', 'selection', model)` is currently not in the types

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 6.2.9

---

Reference to the syntax i mean: https://github.com/Automattic/mongoose/blob/ec7743882791db221641798096cb6bfe20b89e79/lib/document.js#L4150 (only that from what i can tell a third parameter for a model is also supported)

**Comment by Uzlopak** [comment]
@mohammad0-0ahmad 
Can you have a look at it?

**Comment by mohammad0-0ahmad** [comment]
This issue is confirmed @Uzlopak, 
This is related to these types: 
https://github.com/Automattic/mongoose/blob/337d6ad2f6bbd92e186a2774fbcb8a6fb01e8ed3/types/index.d.ts#L411
