### ISSUE TITLE
Connection leak / increase after upgrade to mongoose@6 / nodejs-mongodb@4 ?

### ISSUE THREAD

**Issue by ronjouch** [Automattic/mongoose#11596]
# Feature request or bug?

Maaaaybe a mongoose@6 bug, or a nodejs-mongodb@4 bug?

But maybe not and maybe my own incorrect usage, made visible by a change in mongoose@6 / mongodb@4.

# Current behavior

After upgrading an app to mongoose@6.2.5 + nodejs-mongodb@4.3.1, connections of the app to MongoDB primary (running MongoDB server 4.4.13, hosted by [Atlas, M30, 3000 max connections](https://www.mongodb.com/docs/atlas/reference/atlas-limits/#connection-limits-and-cluster-tier)) seem to either A. leak, or B. simply increase to a maximum that is higher than it used to be (see "before" screenshot and final question):

![screenshot_connections_2022-03-29-11:12:28](https://user-images.githubusercontent.com/522085/160646582-b6c56b58-b8a9-4c9a-9716-0d52ae15d7c4.png)

The drops in the middle of the graph are deployments of the upgraded app.

We do terminate connections on app teardown (which happens during deployments and infra changes).

**EDIT** graph update for the two days after, March 30 + 31. Graph starts immediately after a deploy of the upgraded app, around 800 connections (what we had with mongoose5, see below), then ramps up and stabilizes around 1.3K:

![screenshot_march30_2022-03-31-09:03:03](https://user-images.githubusercontent.com/522085/161061082-538c7015-22c8-41f3-b4e9-af66a471596c.png)

# Expected behavior

Before the upgrade, running mongoose@5.13.14 + nodejs-mongodb@3.7.3, connections to MongoDB primary were much lower and stable _(sorry I'm unable to provide a screenshot using the same precise 1min granularity, Atlas won’t let me, even if I narrow down to a sub-1day time period)_ :

![screenshot_connections-mongoose4_2022-03-29-11:30:21](https://user-images.githubusercontent.com/522085/160648655-84b755eb-7c27-4c90-a0ca-e1f1ef39531a.png)

# Questions

To summarize numbers:

- Before upgrade of APP, primary hovered around 800 connections (600 other services + 200 of APP)
- After upgrade of APP, primary hovers around 1300 connections and climbing (600 other services + 700 of APP)

Questions:

1. Given the two screenshots, especially the one on a longer period stabilizing at 1.3K, it feels unjust to qualify the new behavior as a leak. So, do we agree that mongoose6/mongodb4 simply somehow causes more connections?
2. Was there any behavior change (in either mongoose, or nodejs-mongodb) that could be causing more/leaked connections? Maybe around connection management, or connection TTLs?
3. Do you have tooling / debugging recommendations to troubleshoot this? I'm usually running the lil' homebrew script below to dig such issues. It proved useful in the past, but sadly not in this case. Do you have anything better to recommend?

<details>
  <summary><code>find-leaks-from-mongodb-connections-log.py</code></summary>

```python
#!/usr/bin/env python3
import json

connections = {}

with open("atlas-connection-log.log", "r") as logs:
  for line in logs:

    c = json.loads(line)
    if c['msg'] == 'Connection accepted':
      connections[c['attr']['connectionId']] = True

    # Assume the mongo monitoring agent is NOT the problem; it's us
    elif c['msg'] == 'client metadata' and c['attr']['doc']['driver']['name'] == 'mongo-go-driver':
      connId = int(c['ctx'].split('conn')[1])
      if connId in connections:
        del connections[connId]

    elif c['msg'] == 'Connection ended':
      if c['attr']['connectionId'] in connections:
        del connections[c['attr']['connectionId']]

leaked_connections = connections.keys()
print(f"{len(leaked_connections)} leaked connections:")
print(leaked_connections)
```
</details>

**Comment by ronjouch** [comment]
Holy spaghetti monster. This is all bad root cause attribution of mine. At the moment I was merging & deploying the mongoose@6 upgrade, another change happened causing instances to quickly die and come back, causing tons of unproperly-closed mongoose connections, dying only after their TTL expires, thus the constant extra connections and noise.

Sorry for the noise. Closing.

**Comment by Julian-Sam** [comment]
Hi @ronjouch I seem to be facing a similar issue on mongoose 6 upgrade. Do you remember what your eventual root cause was?

**Comment by ronjouch** [comment]
@Julian-Sam hola. My root cause was

> another change happened causing instances to quickly die and come back, causing tons of unproperly-closed mongoose connections, dying only after their TTL expires, thus the constant extra connections and noise.

, a.k.a. bad code of mine, not mongoose. If you're in the same boat, try to look at the server-side connections log. If you "tag" your mongoose connections with a "user agent", it's possible by looking at opened/unclosed connectionIds to determine who is misbehaving. Good luck!

**Comment by vatsal-gadhiya-searce** [comment]
@ronjouch I am also facing the same issue. What do you mean by bad code of mine.

We observed changing upgrading from mongoose 4 to 6 and rewriting all callbacks to promise caused the issue here since the production deployment.

Can you help me with what was your root cause in the code? That would be really helpful as I am clueless. Thank you.

**Comment by ronjouch** [comment]
@vatsal-gadhiya-searce (or new passersby asking again on how to solve this): I'll repeat and reformulate what I wrote above:

> _try to look at the server-side connections log. If you "tag" your mongoose connections with a "user agent", it's possible by looking at opened/unclosed connectionIds to determine who is misbehaving._

---

Then, once your connections are tagged, see which (and which user-agents) are leaking, a.k.a. opened but never closed. I use a lil' Python script for this, feel free to reuse it. Unlicensed / Public domain / WTFPL.

```python
#!/usr/bin/env python3
import json
import sys
# This script will help you find the cause of MongoDB connections leaks
# (e.g. apps failing to properly close them). to use it,
# Download lots from your Mongo provider, e.g. Atlas: https://cloud.mongodb.com/v2/YOUR_CLUSTER_HERE#clusters
# and click on "..." -> "Download logs", then pass a not-too-narrow time range
# (not too narrow because you want breathing room to find properly-closed connections)
# then simply call `./find-leaked-mongodb-connections-from-log.py /path/to/logs.log`


connections = {}

with open(sys.argv[1], "r") as logs:
    print(f"Successfully opened {sys.argv[0]}")
    for line in logs:

        # new code handling JSON logs (new mongodb, 4.x maybe?)
        c = json.loads(line)
        if c['msg'] == 'Connection accepted':
            connections[c['attr']['connectionId']] = {'ip': c['attr']['remote']}
        elif c['msg'] == 'client metadata':
            connId = int(c['ctx'].split('conn')[1])
            if c['attr']['doc']['driver']['name'] == 'mongo-go-driver':
                # Assume the mongo monitoring agent is NOT the problem; it's us
                if connId in connections:
                    del connections[connId]
            elif connId in connections:
                connections[connId]['app'] = c['attr']['doc'].get('application', 'unknown')

        elif c['msg'] == 'Connection ended':
            if c['attr']['connectionId'] in connections:
                del connections[c['attr']['connectionId']]

        # old code handling pre-JSON logs (old mongodb, 3.x maybe?)
        # if 'connection accepted from' in line:
        #   c_id = line.split('connection accepted from ')[1].split(' ')[1][1:]
        #   connections[c_id] = True
        # elif 'end connection' in line:
        #   c_id_to_rm = line.split('[conn')[1].split('] ')[0]
        #   if c_id_to_rm in connections:
        #     del connections[c_id_to_rm]

leaked_connections = connections.keys()
print(f"{len(leaked_connections)} maybe leaked connections ('maybe' because an unclosed connection might actually be still used! Exercise judgement when interpreting!")
print(connections)
```

**Comment by vkarpov15** [comment]
@vatsal-gadhiya-searce one potential explanation is that [Mongoose 6 bumps the default number of sockets per connection to 100](https://mongoosejs.com/docs/migrating_to_6.html#mongodb-driver-40), and there's now `maxPoolSize` and `minPoolSize` options, which allows the number of sockets open to fluctuate based on usage. Do you set `maxPoolSize` in your code?
