### ISSUE TITLE
I can't find into an array using regex

### ISSUE THREAD

**Issue by TyrisDavidLopez** [Automattic/mongoose#11609]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
use regex in arrays doesn't work
**If the current behavior is a bug, please provide the steps to reproduce.**
1.- create a collection (ej. 'test')
2.- insert some data, ej:
```
{
 "_id": 1,
 "title": [{
        "value": "El Dave valencià",
        "language": "ca"
    }, {
        "value": "El Dave castellano",
        "language": "es"
    }]
}
{
 "_id": 2,
 "title": [{
        "value": "test",
        "language": "ca"
    }, {
        "value": "test",
        "language": "es"
    }]
}

```
3.- try to find a video using regex in the array "title", ej

`test.find(`{{$or:[{"title.value":/Dave/i},{"name.value":/Dave/i} ]})` -> returns items 1 and 2 (this worked fine on mongoose 5)

**What is the expected behavior?**
return only item 1

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 12.22.8 and 14.19.1
mongoose: 6.2.8 and 6.2.9
MongoDB: 5.0

We use NestJS 8 as framework

**Comment by TyrisDavidLopez** [comment]
3 versions of filter works fine on MongoCompass

**Comment by tyrisivanfernandez** [comment]
Yes, the same for me. Fix needed here!!

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    title: [{
        value: String,
        language: String
    }]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        title: [{
            value: 'El Dave valencia',
            language: 'ca'
        }, {
            value: 'El Dave castellano',
            language: 'es'
        }]
    });

    await Test.create({
        title: [{
            value: 'test',
            language: 'ca'
        }, {
            value: 'test',
            language: 'es'
        }]
    });

    const query = await Test.find({$or: [{"title.value":/Dave/i},{"name.value":/Dave/i} ]});
    console.log('done', query, query[0].title, query[1].title);
    
}

run();
```

**Comment by TyrisDavidLopez** [comment]
I runned your code and the error exists:
`done [
  {
    _id: new ObjectId("624be08d16f59398f93c0272"),
    title: [ [Object], [Object] ],
    __v: 0
  },
  {
    _id: new ObjectId("624be08d16f59398f93c0276"),
    title: [ [Object], [Object] ],
    __v: 0
  }
] [
  {
    value: 'El Dave valencia',
    language: 'ca',
    _id: new ObjectId("624be08d16f59398f93c0273")
  },
  {
    value: 'El Dave castellano',
    language: 'es',
    _id: new ObjectId("624be08d16f59398f93c0274")
  }
] [
  {
    value: 'test',
    language: 'ca',
    _id: new ObjectId("624be08d16f59398f93c0277")
  },
  {
    value: 'test',
    language: 'es',
    _id: new ObjectId("624be08d16f59398f93c0278")
  }
]`

**object "test" has no `Dave` on name.value (name is undefined) or title.value**

The correct results would be: (As mongoCompass results, see picture)
`done [
  {
    _id: new ObjectId("624be08d16f59398f93c0272"),
    title: [ [Object], [Object] ],
    __v: 0
  }
] [
  {
    value: 'El Dave valencia',
    language: 'ca',
    _id: new ObjectId("624be08d16f59398f93c0273")
  },
  {
    value: 'El Dave castellano',
    language: 'es',
    _id: new ObjectId("624be08d16f59398f93c0274")
  }
]`
mongoCompass results:
![image](https://user-images.githubusercontent.com/81306706/161692529-7cf7bd11-6030-479f-8fbb-a97c4942de09.png)

**Comment by vkarpov15** [comment]
This is unfortunately expected behavior in Mongoose 6, because [`strictQuery` is now `true` by default](https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict). So `{"name.value":/Dave/i}` becomes `{}` in your query.

We
