### ISSUE TITLE
MongooseServerSelectionError: connect ECONNREFUSED error

### ISSUE THREAD

**Issue by Liv0130** [Automattic/mongoose#11608]
Hello I am a beginner in coding and I ran into this issue while studying coding.
I wanted to connect my project server to MongoDB and I got this error.

 this is my .env code  
`PORT=4000`
`MONGO_URI=mongodb://localhost:27017/blog`

and 
```
require('dotenv').config();
const Koa = require('koa');
const Router = require('koa-router');
const bodyParser = require('koa-bodyparser');
const mongoose = require('mongoose');

const api = require('./api');

// 비구조화 할당을 통해 process.env 내부 값에 대한 레퍼런스 만들기
const { PORT, MONGO_URI } = process.env;


mongoose.connect(MONGO_URI, {
  useUnifiedTopology: true,
  useNewUrlParser: true
})
.then(() => {
  console.log('Connected to MongoDB');
})
.catch(e => {
  console.error(e);
});


const app = new Koa();
const router = new Router();

// router setting
router.use('/api', api.routes()); // api route


// apply bodyParser before using router
app.use(bodyParser());

// apply router to app instance
app.use(router.routes()).use(router.allowedMethods());

// use 4000 if PORT is not designated
const port = PORT || 4000;
app.listen(4000, () => {
  console.log('Listenig to port %d', port);
})
```

and I got error says:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/96000164/161237331-10359399-7773-4376-956c-98dc9ca7faff.png">

Could you please help me with this?
I have tried other ways while googling but it didn't work for me:( and I have tried 
--ipv6 also.

**Comment by LaGgY-CK** [comment]
@Liv0130 How did you solve this issue ?

**Comment by vkarpov15** [comment]
@LaGgY-CK 2 things to check:

1. Do you have MongoDB running on port 27017?
2. Does your MongoDB server have ipv6 support enabled? It looks like this example has `localhost` mapped to `::1`, which is ipv6 loopback.
