### ISSUE TITLE
mongoose.connect() connectivity issue with  serverApi parameter

### ISSUE THREAD

**Issue by jdial1996** [Automattic/mongoose#11607]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am using the mongoose client within in an EKS cluster to connect to mongo atlas.  The setup uses VPC peering with AWS privatelink.  I am able to succesfully connect to the database using the MongoClient by: 

`MongoClient(process.env.MONGO_CONNECTION_STRING, { useNewUrlParser: true, useUnifiedTopology: true, serverApi: ServerApiVersion.v1 });` 

I tried doing similar with Mongoose by: 

`mongoose.connect(process.env.MONGO_CONNECTION_STRING,{
      useNewUrlParser: true,
      useUnifiedTopology: true,
      serverApi: ServerApiVersion.v1
});`
However this does not work.  It works without the serverApi parameter, so I think this is because the mongoose.connect() function does not support the serverApi parameter as of now.  Could you please provide an alternative way to do this or suggest anything that would be helpful. 

**What is the expected behavior?**
I should be able to connect to a mongodb in mongo atlas from an aws eks cluster using mongoose.connect() as below.  The AWS VPC and Mongo Atlas VPC are peered and use AWS PrivateLink

`mongoose.connect(process.env.MONGO_CONNECTION_STRING,{
      useNewUrlParser: true,
      useUnifiedTopology: true,
      serverApi: ServerApiVersion.v1
});`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 6.2.6
node: 16.13.2
mongodb: 5.0

**Comment by vkarpov15** [comment]
Are you sure you're using Mongoose 6.2? Given that you're setting `useNewUrlParser` and `useUnifiedTopology`, it looks like you're using Mongoose 5. Those options are no longer supported in Mongoose 6.

Also, can you please clarify what you mean by "this does not work"? Is there an error message of some sort?

**Comment by jdial1996** [comment]
I was using mongo release 6.2.4.  

What I have done now is upgraded to the latest release of mongoose (6.3.0).   I have removed the `useNewUrlParser` and `useUnifiedTopology` properties and only the `serverApi` setting such that the mongoose.connect() function looks like this: 

`mongoose.connect(connectionString, {serverApi: 'ServerApiVersion.v1')`

It seems like the serverApi parameter is working now but now I get the below error, which I am not sure how to solve: 

MongoParseError: Invalid server API version=ServerApiVersion.v1; must be in the following enum: ["1"]
    at transform (/usr/src/app/node_modules/mongodb/lib/connection_string.js:528:23)
    at setOption (/usr/src/app/node_modules/mongodb/lib/connection_string.js:432:36)
    at parseOptions (/usr/src/app/node_modules/mongodb/lib/connection_string.js:287:9)
    at new MongoClient (/usr/src/app/node_modules/mongodb/lib/mongo_client.js:62:63)
    at /usr/src/app/node_modules/mongoose/lib/connection.js:784:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:781:19)
    at /usr/src/app/node_modules/mongoose/lib/index.js:342:10
    at /usr/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>) {

**Comment by Uzlopak** [comment]
As we upgraded Mongo native driver with 6.3.0 it will be an issue with the mongo native driver. You would probably also have this issue with using only the native driver.

**Comment by vkarpov15** [comment]
@jdial1996 are you able to connect without specifying the `serverApi` option?
