### ISSUE TITLE
TypeScript: remove support for document interfaces that `extends Document`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#11615]
**Do you want to request a *feature* or report a *bug*?**

Neither

**What is the current behavior?**

We've been recommending people not use `extends Document` for the document interface generic param to `Schema`, `Model`, etc.

```ts
// Do this:
interface User {
  name: string;
  email: string;
  // Use `Types.ObjectId` in document interface...
  organization: Types.ObjectId;
}

const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  // And `Schema.Types.ObjectId` in the schema definition.
  organization: { type: Schema.Types.ObjectId, ref: 'Organization' }
});

// Not this:
interface User extends Document {
  name: string;
  email: string;
  // Use `Types.ObjectId` in document interface...
  organization: Types.ObjectId;
}
```

See: https://mongoosejs.com/docs/typescript.html#using-extends-document

This makes our TypeScript types considerably more complex, and also adds a non-trivial amount of performance overhead because of all the places where we need to `Omit<>` document keys.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by tristanguerin** [comment]
Hi @vkarpov15,

Thanks for the notice !

Sometime we need the document version in our applications.
Do you have any counter-argument of implementing the following `UserDocument` declaration ?

```typescript
// Do this:
interface User {
  name: string;
  email: string;
  // Use `Types.ObjectId` in document interface...
  organization: Types.ObjectId;
}

const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  // And `Schema.Types.ObjectId` in the schema definition.
  organization: { type: Schema.Types.ObjectId, ref: 'Organization' }
});

// Document type to match correct type after using findOne() ... (no lean)
type UserDocument = User & Document;
```

I think it wouldn't impact performances but we've had severe performances issues (and sometime still have), so it'd be great to have confirmation.

**Comment by vkarpov15** [comment]
@tristanguerin that approach works. We recommend doing `Document & User` instead, but those should be equivalent in your case.

What sort of performance issues are you seeing and what version of Mongoose are you using?

**Comment by tristanguerin** [comment]
@vkarpov15
Sometime VSCode is slow to display autocompletion on documents (hardly reproductible, might come from my setup).
We're using version 6.0.14.

Thank you for your answer and your recommendations.
