### ISSUE TITLE
Upgrade MongoDb to 4.5

### ISSUE THREAD

**Issue by rwmia** [Automattic/mongoose#11626]
MongoDb NodeJS driver 4.5.0 was released April 4th. Was wondering if Mongoose can update the mongodb 6.x dependency version to 4.5.0

**Comment by Uzlopak** [comment]
See #11623

**Comment by rwmia** [comment]
Thanks. Should have checked pull requests. Apologies.

**Comment by rwmia** [comment]
Closing.
