### ISSUE TITLE
"this" in middleware behavior - undefined (pre, post)

### ISSUE THREAD

**Issue by Rantoledo** [Automattic/mongoose#11627]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
"this" is undefined

**If the current behavior is a bug, please provide the steps to reproduce.**
```
import mongoose from 'mongoose';
import ms from 'ms';
import getLogger from '../utils/logger';

const logger = getLogger();

const resourceSchema = new mongoose.Schema({
    name: { type: String, required: true },
    resourceType: { type: String, required: true }
}, {
    timestamps: true,
    toJSON: {
        transform: function transform(doc, response) {
            response.id = doc._id;
            delete response._id;

            return response;
        }
    }
});

resourceSchema.pre('find', () => {
    logger.info('>>>> pre find', this, a, b, c);
    this._startTime = Date.now();
    logger.info('>>>> pre find startTime', this._startTime);
});

resourceSchema.post('find', () => {
    logger.info('>>>> post find', this, this._startTime);
    if (this._startTime !== null) {
        logger.info('Find runtime:', ms(Date.now() - this._startTime));
    }
});

resourceSchema.pre('updateMany', () => {
    this._startTime = Date.now();
});

resourceSchema.post('updateMany', () => {
    if (this._startTime !== null) {
        logger.info('updateMany runtime:', ms(Date.now() - this._startTime));
    }
});

const Resource = mongoose.model('Resource', resourceSchema);

export default Resource;
```

I expect "this" to be an empty object like it used to be.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs: 17.6.0
mongoose: 6.2.10
mongodb: 5.0.6

Am I missing something?

**Comment by Uzlopak** [comment]
In typescript or in at runtime?

**Comment by Uzlopak** [comment]
Also arrow functions dont have this.

`Arrow functions don't have their own bindings to this or super, and should not be used as methods.`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

So probably you should classic function () { } so mongoose can bind the this-object.

**Comment by Rantoledo** [comment]
Changing to classic functions actually worked...
That's probably related to the fact that I moved recently to ESM in my project.
thanks!

**Comment by Uzlopak** [comment]
Nice. Closing :)

**Comment by phamvinhdat** [comment]
thanks
```js
shema.pre('find', () => {
  const isQuery = this instanceof mongoose.Query
  console.log(isQuery) // want: true, actual: false
})
```
a night for it, lol
