### ISSUE TITLE
$merge is not allowed to be used within a $facet stage

### ISSUE THREAD

**Issue by olifog** [Automattic/mongoose#11630]
**Do you want to request a *feature* or report a *bug*?**
Bug/inconsistency

**What is the current behavior?**
When performing a $facet aggregation, with a $merge in a subpipeline, mongoose throws a "MongoServerError: $merge is not allowed to be used within a $facet stage"

**If the current behavior is a bug, please provide the steps to reproduce.**
Very easy to reproduce, just do a $merge within a $facet subpipeline

**What is the expected behavior?**
According to the [documentation](https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/):

> Other [aggregation stages](https://www.mongodb.com/docs/manual/reference/operator/aggregation-pipeline/#std-label-aggregation-pipeline-operator-reference) can also be used with $facet with the following exceptions:
> - ...
> - [$merge](https://www.mongodb.com/docs/manual/reference/operator/aggregation/merge/#mongodb-pipeline-pipe.-merge)
> - ...
>
> Each sub-pipeline within $facet is passed the exact same set of input documents. These sub-pipelines are completely independent of one another and the document array output by each is stored in separate fields in the output document. The output of one sub-pipeline can not be used as the input for a different sub-pipeline within the same $facet stage. If further aggregations are required, add additional stages after $facet and specify the field name, <outputField>, of the desired sub-pipeline output.

Unless I'm misunderstanding the documentation, there is no reason for this error to be thrown- it *can* be used just as long as you're careful

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 6.2.9
Node.js v16.14.0

**Comment by olifog** [comment]
My bad, this does not seem to be a mongoose issue, getting the same issue using Compass. Am I just not reading the documentation right?

**Comment by vkarpov15** [comment]
"Other [aggregation stages](https://www.mongodb.com/docs/manual/reference/operator/aggregation-pipeline/#std-label-aggregation-pipeline-operator-reference) can also be used with $facet with the following exceptions" implies that you _can't_ use `$merge` with `$facet`. You can't use the below stages with `$facet`:

[$collStats](https://www.mongodb.com/docs/manual/reference/operator/aggregation/collStats/#mongodb-pipeline-pipe.-collStats)
[$facet](https://www.mongodb.com/docs/manual/reference/operator/aggregation/facet/#mongodb-pipeline-pipe.-facet)
[$geoNear](https://www.mongodb.com/docs/manual/reference/operator/aggregation/geoNear/#mongodb-pipeline-pipe.-geoNear)
[$indexStats](https://www.mongodb.com/docs/manual/reference/operator/aggregation/indexStats/#mongodb-pipeline-pipe.-indexStats)
[$out](https://www.mongodb.com/docs/manual/reference/operator/aggregation/out/#mongodb-pipeline-pipe.-out)
[$merge](https://www.mongodb.com/docs/manual/reference/operator/aggregation/merge/#mongodb-pipeline-pipe.-merge)
[$planCacheStats](https://www.mongodb.com/docs/manual/reference/operator/aggregation/planCacheStats/#mongodb-pipeline-pipe.-planCacheStats)
