### ISSUE TITLE
OR not working properly with find (Using version 6.0.1)

### ISSUE THREAD

**Issue by leopalazzi** [Automattic/mongoose#11635]
I explain my case I have some documents with a key and certains without that key.

I want to retrieve all the document containing one key or the other one.

When I do it with MongoCompare it's working perfectly. I have 3 documents that are returned which is what I am excepting.

But when I used the library with the same condition it's returning me the full collection....

Example of the query : 

{$or:[{supplierCustomerNumber:"HN13ED1"},{groupNumber:"HN1SASAS0"}]}

groupNumber is the key that is not in all documents.

**Note : I also tried to add $exists to check if the field exist in the query it's not working**

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String,
    location: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        name: 'Orange',
        location: 'Florida'
    });

    await Test.create({
        name: 'Weed',
        location: 'California'
    });

    await Test.create({
        name: 'Peach',
        location: 'Georgia'
    });

    console.log(await Test.find({$or: [{name: 'Weed'}, {location: 'Georgia'}]}));
}

run();
```
