### ISSUE TITLE
a small mistake in docs

### ISSUE THREAD

**Issue by asafel** [Automattic/mongoose#11642]
in the docs [here](https://mongoosejs.com/docs/defaults.html#default-functions)
you are creating a schema like this:
`const schema = new Schema({
  title: String,
  date: {
    type: Date,
    default: Date.now
  }
});`

And then, you're using the date attribute, in your example, like this:
`post.date.getTime()`

But this is a mistake.
You should make the default value be `new Date()` instead of `Date.now` and only then you'll be able to call "getTime()" method.

**Comment by Uzlopak** [comment]
The number gets transformed to a Date Object.
