### ISSUE TITLE
callback function as a parameter to .findOne gets called twice

### ISSUE THREAD

**Issue by seyeonCPark** [Automattic/mongoose#11658]
In the code below is about the login function I made. 
In this function, console.log(user); part gets called twice
and the worst part is that **it shows null in the first log** and then user object in form of JSON.

**So even though the user with the requested email exists in DB, it returns null at first and then the right info of the user.**

I have no clue why it would log twice and show null at first.
Also since it's null at first, the code returns response with {success : false, msg : "unregistered email"}, even though it is registered one.

```javascript
const process = {

    login : (req, res) => {

        // 1. check if requested email exists in DB
        User.findOne({email : req.body.email}, (err, user) => {

            console.log(user); // -> logs twice. null and then user object in form of JSON

            if(!user) return res.json({success : false, msg : "unregistered email"});

            // // 2. if so, check if the password is correct
            // .....
            // // 3. generate a token and save
            // .....

            });
        }
};
```
<img width="572" alt="image" src="https://user-images.githubusercontent.com/72260034/163113341-5d0257bd-b740-4127-877a-8b9df047fd48.png">

I couldn't find why it does this...going insane trying to solve this problem...
Any advices or comments will be hugely appreciated.

mongoose version 6.2.10

**Comment by vkarpov15** [comment]
Is it possible that you're sending two HTTP requests? Could be a CORS preflight request or something similar. What is the value of `req.body.email`?

**Comment by seyeonCPark** [comment]
@vkarpov15 Hi, vkarpov15 ! = ) Never heard of CORS preflight... I THINK I'm not sending 2 requests but I'm really new to node js and possibly I made that mistake. Not really sure how to look into that possible problem.
And also, the value of req.body.email is 'asdfez@gmail.com'. The email which user just typed to sign in.

**Comment by Uzlopak** [comment]
Console log please req.method

If fiest req.method is not POST but OPTIONS, then you have CORS-preflight sent by the Browser.

**Comment by seyeonCPark** [comment]
@Uzlopak Hi, there ! I edited the original issue to show more of my other codes, like the part I call fetch API to send POST request. Could you check it out ? Where could I console.log the method tho?

**Comment by Uzlopak** [comment]
Well, you modified your post two days ago. And there I don't see how you fetch a call but where you implement a RequestHandler.

```javascript
login : (req, res) => {
    console.log(req.method);
}
```

**Comment by seyeonCPark** [comment]
@Uzlopak 
<img width="811" alt="2022-04-16" src="https://user-images.githubusercontent.com/72260034/163676707-93386a1a-893a-4e05-aac6-025c53ad93d8.png">
Oh god, it really was sending 2 requests... thank you. Could you tell me what should I do to fix this problem ?

**Comment by vkarpov15** [comment]
Don't send 2 requests. And return an error if `user` is not found.
