### ISSUE TITLE
pluralize option doesn't work correctly, pluralize(null) still can pluralize some collection names

### ISSUE THREAD

**Issue by gg187on** [Automattic/mongoose#11656]
```js
mongoose.pluralize(null);
mongoose
	.connect(process.env.DB, {
		useNewUrlParser: true,
		useUnifiedTopology: true
	})
	.then(init);
```

works fine for most collections, in my case it doesn't pluralize any of them except one...

```js
model('sondy', Sonda_schema);
```

generates `sondies` collection.

I tried to put `mongoose.pluralize(null)` at the beginning of `init` too, didn't help. I actually hate this feature. I needed to explicitly define name of collection with `model('sondy', Sonda_schema, 'sondy');`

**Comment by gg187on** [comment]
actually after some testing it feels like that option doesn't work at all.

**Comment by IslandRhythms** [comment]
Just have it return the name and you should be good
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

mongoose.pluralize(function(name) {
    return name;
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    console.log(await mongoose.connection.collections);
}

run();
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

mongoose.pluralize(null);

const Test = mongoose.model('sondy', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    console.log(await mongoose.connection.collections);
}

run();
```

output:

```
<ref *1> {
  sondy: Collection {
    collection: Collection { s: [Object] },
    Promise: [Function: Promise],
    modelName: 'sondy',
    _closed: false,
    opts: {
      autoIndex: true,
      autoCreate: true,
      schemaUserProvidedOptions: {},
      capped: false,
      Promise: [Function: Promise],
      '$wasForceClosed': undefined
    },
    name: 'sondy',
    collectionName: 'sondy',
    conn: NativeConnection {
      base: [Mongoose],
      collections: [Circular *1],
      models: [Object],
      config: {},
      replica: false,
      options: null,
      otherDbs: [],
      relatedDbs: {},
      states: [Object: null prototype],
      _readyState: 1,
      _closeCalled: undefined,
      _hasOpened: true,
      plugins: [],
      id: 0,
      _queue: [],
      _listening: false,
      _connectionString: 'mongodb://localhost:27017',
      _connectionOptions: [Object],
      client: [MongoClient],
      '$initialConnection': [Promise],
      db: [Db],
      host: 'localhost',
      port: 27017,
      name: 'test'
    },
    queue: [],
    buffer: false,
    emitter: EventEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      [Symbol(kCapture)]: false
    }
  }
}
```

**Comment by Uzlopak** [comment]
We should probably modify mongoose.set to accept pluralization option.

**Comment by gg187on** [comment]
Does that `mongoose.pluralize` need to be writen to every module where I use model? I use SvelteKit, and I put `mongoose.pluralize` inside `hooks.js`, and `model` in my custom JS file, that I imported in endpoint.

**Comment by gg187on** [comment]
give me few minutes, I will send link to repo with reproduction

**Comment by gg187on** [comment]
oh I found out what is problem... I can reproduce it, I'm going to give you repro with "SvelteKit" demo app (but I can reproduce it in NuxtJS too, so I think it's actually reproductable with any project).

https://github.com/gg187on/repro_mongodb_pluralize_kit

**Comment by gg187on** [comment]
no-stale

**Comment by vkarpov15** [comment]
@gg187on the issue is that you're creating your model using `mongoose.model()` **before** calling `mongoose.pluralize()` here: https://github.com/gg187on/repro_mongodb_pluralize_kit/blob/986a5f37206d6a189f4db28a07add32917c280b2/src/hooks.js#L4-L6 . Right now Mongoose gets the collection name when you call `mongoose.model()`, so if you call `pluralize()` after calling `mongoose.model('Test')` then 'Test' won't get your custom `pluralize()`.
