### ISSUE TITLE
Cast to date failed for a $gte filter

### ISSUE THREAD

**Issue by uSkizzik** [Automattic/mongoose#11655]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
I have the following piece of code:
```js
await Connections.find({ connections: { discord: { expires: { $gte: new Date() } } } })
```
with connections having the following model:
```js
usersdb.model(
	"connections",
	new mongoose.Schema({
		userId: { type: String, unique: true },
		connections: {
			type: new mongoose.Schema({
				discord: {
					type: new mongoose.Schema({
						expires: { type: Date },
						token: { type: String },
						refreshToken: { type: String }
					})
				}
			}),
			default: () => ({})
		}
	})
)
```
Running that, gives me the following error:
`CastError: Cast to date failed for value "{ '$gte': 2022-04-10T23:04:34.662Z }" (type Object) at path "expires" for model "connections"`
(Full error available [here](https://gist.github.com/uSkizzik/23e09e9b9c7359af38399ae5e3c7af1f))

**What is the expected behavior?**
The code would run fine with no errors at all and return the documents matching the filter query.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.JS - 16.10.0
Mongoose - 6.2.10
MongoDB - 5.0.6

**Comment by Uzlopak** [comment]
Hmm. makes sense, as it is not possible to transform  { '$gte': 2022-04-10T23:04:34.662Z } to a date. 

We would need your query.

**Comment by uSkizzik** [comment]
> Hmm. makes sense, as it is not possible to transform  { '$gte': 2022-04-10T23:04:34.662Z } to a date. 
> 
> We would need your query.

Isn't the Connections.find the query?

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    expires: Date
});

const Test = mongoose.model('Test', testSchema);
const date = new Date();
async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        expires: new Date()
    });

    console.log(await Test.find({expires: {$gte: date}}))
}

run();
```

**Comment by uSkizzik** [comment]
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>     expires: Date
> });
> 
> const Test = mongoose.model('Test', testSchema);
> const date = new Date();
> async function run() {
>     await mongoose.connect('mongodb://localhost:27017');
>     await mongoose.connection.dropDatabase();
> 
>     await Test.create({
>         expires: new Date()
>     });
> 
>     console.log(await Test.find({expires: {$gte: date}}))
> }
> 
> run();
> ```

After trying this, I reached the conclusion that my issue appears only if the Date field is a part of a sub-schema. 
I'd appreciate if you gave that a shot instead 😃

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    expires: {
        moment: Date
    }
});

const Test = mongoose.model('Test', testSchema);
const date = new Date();
async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        expires: {
            moment: new Date()
        }
    });
    console.log(await Test.findOne());
    const entry = await Test.findOne();
    console.log(typeof entry.expires.moment, typeof date)
    console.log(date)
    console.log(await Test.find({expires:{moment:{$gte: date}}}))
}

run();
```

**Comment by vkarpov15** [comment]
Incorrect query syntax. You should query by `expires.moment` instead as shown below.

```javascript
console.log(await Test.find({'expires.moment':{$gte: date}})
```

The MongoDB server interprets `Test.find({expires:{moment:{$gte: date}}})` as "find all documents where `expires` is exactly equal to the object `{ moment: { $gte: Date('2022-04-11T20:17:45.481Z') } }`". In general, you should use dotted path names instead of nested objects for queries.

**Comment by arthursb2016** [comment]
> Incorrect query syntax. You should query by `expires.moment` instead as shown below.
> 
> ```js
> console.log(await Test.find({'expires.moment':{$gte: date}})
> ```
> 
> The MongoDB server interprets `Test.find({expires:{moment:{$gte: date}}})` as "find all documents where `expires` is exactly equal to the object `{ moment: { $gte: Date('2022-04-11T20:17:45.481Z') } }`". In general, you should use dotted path names instead of nested objects for queries.

This worked for me, thanks :)

**Comment by Vitomir2** [comment]
I have also this issue and my code is as follows:
```js
const AccountSchema = new Schema({
    email: {
        type: String,
        unique: true,
        required: true,
        index: {
            unique: true
        }
    },
    password: {
        type: String,
        required: true
    },
    resetPasswordToken: {
        type: String,
        required: false
    },
    resetPasswordExpires: {
        type: Date,
        required: false
    }
})

AccountSchema.methods.generatePasswordReset = async function () {
    this.resetPasswordToken = crypto.randomBytes(20).toString('hex')
    this.resetPasswordExpires = Date.now() + 1800000 // here I set the value initially
}
```

Then, I query like that:
```js
const account = await AccountModel.findOne({ resetPasswordToken, resetPasswordExpires: { $gte: new Date(Date.now()) } }).setOptions({ sanitizeFilter: true })
```

This throws me the following:
```json
{
    "stringValue": "\"{ '$gte': 2023-02-16T10:58:23.526Z }\"",
    "valueType": "Object",
    "kind": "date",
    "value": {
        "$gte": "2023-02-16T10:58:23.526Z"
    },
    "path": "resetPasswordExpires",
    "reason": {
        "generatedMessage": true,
        "code": "ERR_ASSERTION",
        "actual": false,
        "expected": true,
        "operator": "=="
    },
    "name": "CastError",
    "message": "Cast to date failed for value \"{ '$gte': 2023-02-16T10:58:23.526Z }\" (type Object) at path \"resetPasswordExpires\" for model \"Account\""
}
```

**Comment by vkarpov15** [comment]
@Vitomir2 that's because `sanitizeFilter` prevents using `$gte` and other query selectors. If you still want to use `sanitizeFilter` to prevent query selector injections, you would have to add a `mongoose.trusted()` call as follows.

```javascript
const account = await AccountModel.findOne({
  resetPasswordToken,
  resetPasswordExpires: mongoose.trusted({ $gte: new Date(Date.now()) }) // <-- add mongoose.trusted() here
}).setOptions({ sanitizeFilter: true })
```

Read more here: https://thecodebarbarian.com/whats-new-in-mongoose-6-sanitizefilter.html

**Comment by Vitomir2** [comment]
@vkarpov15 Appreciate for the details, buddy! :)

Best wishes,
Vitomir
