### ISSUE TITLE
[feature] Add 'getSiblingDb' function for 'aggregate $lookup' option

### ISSUE THREAD

**Issue by raulabad98** [Automattic/mongoose#11652]
[MongoDB](https://www.mongodb.com/docs/datalake/reference/pipeline/lookup-stage/) currently offers the 'getSiblingDb' function that allows you to search other databases while aggregation is in progress.

**Comment by vkarpov15** [comment]
We already have `useDb()`, which is similar.

**Comment by bipinstha7** [comment]
@vkarpov15 how do you write this code using mongoose useDb(). I need to aggregate the two db in single pipeline.
`db.getSiblingDb("sourceDB1").orders.aggregate(
  {
    $lookup: {
      from: { db: "sourceDB2", coll: "catalog" },
      localField: "item",
      foreignField: "sku",
      as: "inventory_docs"
    }
  }
)`
