### ISSUE TITLE
Typescript: default import does not work without esModuleInterop

### ISSUE THREAD

**Issue by Loskir** [Automattic/mongoose#11664]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Default import does not work without `esModuleInterop`.
https://github.com/Automattic/mongoose/pull/11343 was planned to fix this, but it seems like it doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**
`package.json`
```json
{
  "name": "mongoose-ts",
  "version": "1.0.0",
  "dependencies": {
    "mongoose": "6.2.11"
  },
  "devDependencies": {
    "typescript": "4.6.3"
  }
}
```
`tsconfig.json`
```json
{
  "compilerOptions": {
	"target": "ES2021",
	"module": "commonjs",
	"outDir": "./dist",
	"noEmitOnError": true,
	"strict": true,
	"skipLibCheck": true,
  }
}
```
`index.ts`
```ts
import mongoose from 'mongoose'

mongoose.model('a')
```

The error:
```
index.ts:1:8 - error TS1192: Module '"mongoose"' has no default export.

1 import mongoose from 'mongoose'
         ~~~~~~~~
```

**What is the expected behavior?**
It should compile

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 6.2.11
Node.js v17.8.0
Typescript 4.6.3

**Comment by IslandRhythms** [comment]
In the meantime you can do `import * as mongoose from 'mongoose'`

**Comment by Uzlopak** [comment]
Hmm, yes I could reproduce it.

**Comment by Uzlopak** [comment]
@Loskir 
I created a PR #11695 . Maybe you want to check if it finally fixes your issue.

**Comment by Loskir** [comment]
@Uzlopak seems to be working 👍
