### ISSUE TITLE
Problem with type Document

### ISSUE THREAD

**Issue by uncle-ara** [Automattic/mongoose#11667]
Hi all. I have a problem with types. Why do I have the Document type in foo?

![image](https://user-images.githubusercontent.com/47677284/163471898-897cb796-c17e-4641-bc96-7b5c2a4d00e9.png)

If I put type Document. Then when I refer to a user I have methods with $ symbol in the list. Is it normal?

![image](https://user-images.githubusercontent.com/47677284/163471548-4c44ab47-bbd9-4bc1-a61f-6b731250dde1.png)

**Comment by vkarpov15** [comment]
This is correct, because `await user.find()` returns an array of hydrated Mongoose documents, which have various helper methods that start with `$`.
