### ISSUE TITLE
unexpected post update middleware firing when document not updated

### ISSUE THREAD

**Issue by fromacetozed** [Automattic/mongoose#11669]
**What is the current behavior?**

To update a document with its id and additional query for optimistic locking 

`Model.updateOne({_id,...additionalQueryForOptimisticLock},updates)`

in case there is a conflicted write made the document no longer match the query for update, no doubt we would get response like below

`{
  acknowledged: true,
  modifiedCount: 0,
  upsertedId: null,
  upsertedCount: 0,
  matchedCount: 0
} `

but the post update middleware is still fired in this case, which is not expected.

**What is the expected behavior?**
no post update middleware firing if document is not updated, thanks.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs v12.19.0
mongoose v6.0.12
MongoDB v4.2

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const {Schema} = mongoose;

const testSchema = new Schema({
    name: String
}, {optimisticConcurrency: true});
testSchema.post('updateOne', function() {
    console.log('hello!')
});


const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const doc = await Test.create({name: 'Test'});
    await Test.updateOne({_id: doc._id}, {name: 'Testerson'});
    console.log(await Test.updateOne({name: 'Test'}, {name: 'Testerson'}));
}

run();
```

**Comment by fromacetozed** [comment]
@IslandRhythms any plan to fix this bug? thanks.

**Comment by vkarpov15** [comment]
This is expected behavior. `post('updateOne')` always fires after the `updateOne()` operation completes. But you can always work around this behavior by adding an extra check to avoid running your middleware if `modifiedCount === 0`:

```javascript
testSchema.post('updateOne', function(res) {
    if (res.modifiedCount === 0) {
      return;
    }
    console.log('hello!')
});
```

**Comment by fromacetozed** [comment]
@vkarpov15 thanks, i kind agree with you that this is an expected behavior, even few of cases we would need a middleware  after 'updateOne' with no documents modified.
