### ISSUE TITLE
Outdated `bson` dependency / Possible double dependency install

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11676]
**Do you want to request a *feature* or report a *bug*?**
enhancement / dev-experience

**What is the current behavior?**
currently (with mongoose 6.3.0), mongoose uses mongodb 4.5 which uses bson 4.6, but mongoose still has dependency on bson 4.2, which may result in some cases in double-installs after upgrades (in my case in yarn)

**If the current behavior is a bug, please provide the steps to reproduce.**
install mongoose (a older version, for example `6.2.x`) with yarn and upgrade to `6.3.x`, observe `node_modules` / `yarn.lock`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 6.3.0

---

i just want to make it clear: this is not a problem for me, but just something i noticed after my upgrade to mongoose 6.3.0 (from 6.2.x), which does not really impact functionality

**Comment by vkarpov15** [comment]
Fix is in https://github.com/Automattic/mongoose/commit/73d202027fcab8e65260991e5939857a32d2abd2, thanks for the heads up. We'll release 6.3.1 with the fix on Monday :+1:
