### ISSUE TITLE
Mongoose not working with IPV6 ReplicaSet

### ISSUE THREAD

**Issue by vBitza** [Automattic/mongoose#11681]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Mongoose is unable to connect to an ipv6 replica set even though the ReplicaSet seems to be working fine. While trying to connect to each ip individually mongoose is able to establish connection. However this only happens with newer Mongoose version, I've found this Stackoverflow issue which mentioned downgrading Mongoose to 4.5.8 and it worked: https://stackoverflow.com/questions/65796174/mongoose-connection-to-replica-set-not-working 

**If the current behavior is a bug, please provide the steps to reproduce.**

Connection string:
mongodb://**user**:**password**@[2001:db8:1::3da]:27017,[2001:db8:1::4ab]:27017,[2001:db8:1::142]:27017/**dbName**?authSource=admin

Mongoose connection error:
[mongose-error.txt](https://github.com/Automattic/mongoose/files/8507060/mongose-error.txt)

Also attached the rs.status() taken from locally connecting to mongodb with mongod:
[rs-status.txt](https://github.com/Automattic/mongoose/files/8507059/rs-status.txt)

**What is the expected behavior?**

Mongoose should be able to connect

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node version: 15
Mongoose: 6.3.0 / 5.12.8

**Comment by vkarpov15** [comment]
Are you able to connect from the MongoDB shell? Also, are you sure your auth credentials are correct?

**Comment by vBitza** [comment]
Hi, 
Yes the Mongo Shell on the MongoVM is properly working and the auth credentials are correct (as they work when connecting to a single Mongo instance).
I think I've forgot to mention this aswell, while using only one of the ReplicaSet Nodes to connect it works, ie:

mongodb://user:password@[2001:db8:1::142]:27017/dbName?authSource=admin -> Works
mongodb://user:password@[2001:db8:1::3da]:27017,[2001:db8:1::4ab]:27017,[2001:db8:1::142]:27017/dbName?authSource=admin -> Doesn't work

**Comment by vBitza** [comment]
Hi, not really, I was just "obfuscating" the rs-name and didn't do it properly. 

It seems the issue still persists:
Adding additional logs:
We can see in the MongoDB logs that the MS is able to reach it (the Node v16.14  client)
[mongodb-logs.txt](https://github.com/Automattic/mongoose/files/9315568/mongodb-logs.txt)

The Moongose Error shows type: "ReplicaSetNoPrimary"
[nodejs-logs.txt](https://github.com/Automattic/mongoose/files/9315570/nodejs-logs.txt)

RS Status Show the First node being the Primary node:
[rs-status.txt](https://github.com/Automattic/mongoose/files/9315571/rs-status.txt)

**Comment by vkarpov15** [comment]
What's your MongoDB server version?

**Comment by vBitza** [comment]
$ mongod --version
db version v4.0.3
git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64

**Comment by vkarpov15** [comment]
@vBitza why are all your replica set members' hostnames different from the ones in your connection string? `rs.status()` shows `[2001:db9:1::1e3]:27017`, `[2001:db9:1::169]:27017`, `[2001:db9:1::10f]:27017`, but none of those are in your connection string. Perhaps this is a [replica set hostnames issue](https://mongoosejs.com/docs/connections.html#replicaset-hostnames)?

**Comment by vBitza** [comment]
@vkarpov15 Hi, the MongoDB VMs are running on two Network Interfaces, one is for external traffic and one for internal traffic. The NodeJS apps connects to the MongoDB on the external one and the nodes are talking between each other on the internal one so that's why we see a different IP in the connection string and the rs.status(). But the App has access to both network interfaces and this setup works fine in IPv4.

**Comment by vkarpov15** [comment]
Is the app able to connect using the IPs specified in `rs.status()`?
