### ISSUE TITLE
How to figure out the number of active connections using mongoose?

### ISSUE THREAD

**Issue by outjoker** [Automattic/mongoose#11680]
let's just say i am running a nodejs application and I am using mongoose to connect to mongodb. In my nodejs app, at any given point of time is there any way to get to know the number of active mongo connections made from the nodejs appl

**Comment by IslandRhythms** [comment]
`mongoose.connection.base.connections`. It is an array that holds all the active connections running. You could do something like this

`const numConnections= mongoose.connection.base.connections.length;`

**Comment by outjoker** [comment]
@IslandRhythms  thank you for responding. 

I have used this to print the number of connections. i was able to print them succesfully. 

This is how i am creating the mongoose connection 

`this.connection = await mongoose.createConnection(mongoUrl, options);`

and once done with the transaction i am closing this connection in the following way 

```
this.connection.close();
mongoose.connection.close()
```

 the count of the active connections is surprisingly increasing while it has to decrement ideally after connection is closed.
can you kindly let me know if the above methods are the legit ways to close the active connection?

**Comment by IslandRhythms** [comment]
You've stored the value of the length of the array in a variable, therefore if you remove connections it won't change on its own. You either have to decrement the variable yourself when you close a connection, or not save the number of connections in a variable. I would recommend doing the latter option. Meaning everytime you want to check the number of connections, use `mongoose.connection.base.connections.length`. You could write a function that returns the current length of the array at any given time like so:

```javascript
function getConnectionsNumber() {
return mongoose.connection.base.connections.length;
}
```

**Comment by outjoker** [comment]
@IslandRhythms thanks for responding back. Actually, i wasn't storing the connections in a variable, I was directly printing the value as a console.log statement like this 

console.log(mongoose.connection.base.connections.length) 

at no point of time, i was assigning the value to a variable.

**Comment by IslandRhythms** [comment]
Can you copy and paste the code that is causing this issue?

**Comment by outjoker** [comment]
@IslandRhythms 

this is my close connection function 

```
close() {
        if (this.connection != null) {
            this.connection.close();
        }
    }
```
and i am printing the active connections in the following way 

```
 logger.info(`LOG`,`No of Active connections are :- ${mongoose.connection.base.connections.length}`)
        logger.info(`LOG`, `No of Active connections from mongoose are :- ${mongoose.connections.length}`)
```

**Comment by Uzlopak** [comment]
Just a reminder: mongodb native driver is not having one connection but having a connectionPool. So if you close the connection, you are closing the whole connectionPool

**Comment by IslandRhythms** [comment]
Ok so the reason why the number isn't decreasing is because a closed connection can be reopened and therefore mongoose does not remove close connections from the connections array. You would have to go in and `splice()` the connection out of the array.
A workaround could be to create a variable that tracks the number of active connections for you. So in the disconnect event handler you could decrement the variable and in the connect event handler you would increment.

**Comment by outjoker** [comment]
@IslandRhythms just fyi, i found this PR https://github.com/Automattic/mongoose/pull/11674 which is trying to address the same thing that you mentioned 
fyi @OmkarHirve

**Comment by outjoker** [comment]
we are currently waiting on [PR](https://github.com/Automattic/mongoose/issues/11680). Once this gets merged, we might need to upgrade to the latest version of mongoose, after which we might start to receive the right number of active connections
