### ISSUE TITLE
createConnection does not return a Promise, as it should

### ISSUE THREAD

**Issue by trycoon** [Automattic/mongoose#11686]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running createConnection() gives the following error "TypeError: mongoose.createConnection(...).then is not a function"

**If the current behavior is a bug, please provide the steps to reproduce.**

import mongoose from 'mongoose';
mongoose.createConnection('mongodb://localhost:27017/db', {}).then((db) => {});

**What is the expected behavior?**
That the function would return a Promise, according to the documentation:
@return {Connection} the created Connection object. Connections are thenable, so you can do `await mongoose.createConnection()`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 6.3.0
The problem is this line: https://github.com/Automattic/mongoose/blob/master/lib/index.js#L286
In Mongoose 5.12.3 its working, and then the code reads:
```
 if (arguments.length > 0) {
    return conn.openUri(uri, options, callback);
  }

  return conn;
```
  
  It **returns** the Promise created by openUri()

**Comment by trycoon** [comment]
Could be related to https://github.com/Automattic/mongoose/issues/8706

**Comment by trycoon** [comment]
Ok, I missed this: https://mongoosejs.com/docs/migrating_to_6.html#the-aspromise-method-for-connections
So then this is the expected behavior... But this line should then be removed: "Connections are thenable, so you can do await mongoose.createConnection()"

**Comment by mryellow** [comment]
`.asPromise()` doesn't exist.

**Comment by vkarpov15** [comment]
@mryellow can you please clarify what you mean? [Here's the `asPromise()` implementation](https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L1630)
