### ISSUE TITLE
Doc: PopulatedDoc is removed from the documentation of the latest version

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#11685]
**Do you want to request a *feature* or report a *bug*?** none

**What is the current behavior?**

* https://mongoosejs.com/docs/typescript/populate.html
* https://mongoosejs.com/docs/5.x/docs/typescript/populate.html

`PopulatedDoc` works fine but doesn't exist on the documentation.

**Comment by vkarpov15** [comment]
`PopulatedDoc` does work fine, but we recommend using the `.populate<TypeOverride>` syntax instead. We'll add a section in the docs about `PopulatedDoc` though.
