### ISSUE TITLE
BuildPipeline, node 12 near to EOL, node 18 does not run on ubuntu 1804 

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11696]
Regarding https://github.com/nodejs/node/issues/42351

So we would need to change the ubuntu version from 1804 to 1810 or skip using node 18 tests for mongo 4.0.2

ubuntu 1804 is not LTS anymore. mongo 4 is not EOL yet. node 12 is near to EOL (9 days left)

So I would propose to use ubuntu 20.04 for mongo4 (if possible) and drop node 12 in 9 days.

**Comment by Uzlopak** [comment]
Disabled node18 test with mongo4

**Comment by vkarpov15** [comment]
I'm ok with skipping Node 18 tests for MongoDB 4.x. However, I'm not ok with dropping Node 12 support. Will put more thoughts in #11749.
