### ISSUE TITLE
Property '...' does not exist on type 'Model<Document<any, any, any>, {}, {}>'.ts(2339)

### ISSUE THREAD

**Issue by learner00000** [Automattic/mongoose#11702]
I have the following models/users.ts` file:

    import mongoose from 'mongoose';
    const Schema = mongoose.Schema;
    import passportLocalMongoose from 'passport-local-mongoose';
    
    const digitalWalletSchema = new Schema({
        currencyName : {
            type : String
        },
        value : {
            type : Number
        }
    });
    const userSchema = new Schema({
        username : {
            type : String,
            sparse : true ,
            unique : true
        },
        firstName : {
            type: String
        },
        lastName : {
            type : String
        },
        email : {
            type : String,
            unique : true
        },
        telNumber : {
            type : Number
        },
        nationalCode : {
            type : Number,
            sparse : true,
            unique : true
        },
        admin : {
            type:Boolean,
            default : false
        },
        image : {
            type : String
        },
        wallet: {
            type : Number,
            default : 0
        },
        rate : {
            type : Number,
            default : 0
        },
        shabaCode : {
            type : Number
        },
        cardNumber : {
            type : Number
        },
        birthDay : {
            type : String
        },
        status : {
            type : String
        },
        address : {
            type : String
        },
        documnetPath : {
            type : String
        },
        description : {
            type: String
        },
        purchased : [String],
        digitalWallet : [digitalWalletSchema]
    }, {timestamps : true});
    
    userSchema.plugin(passportLocalMongoose,{usernameField : 'email'});
    
    export default mongoose.model('User' , userSchema);

And also have this `authentication.ts` file:

    import passport from 'passport';
    import passportLocal from 'passport-local';
    const LocalStrategy = passportLocal.Strategy;
    import passportJWT from 'passport-jwt';
    const passportJWTStrategy = passportJWT.Strategy;
    const ExtractJWT = passportJWT.ExtractJwt;
    import JWT from 'jsonwebtoken';
    import User from './models/users';
    import config from './config';
    
    export const local = passport.use(new LocalStrategy({usernameField : 'email'}, User.authenticate()));
    passport.serializeUser(User.serializeUser());
    passport.deserializeUser(User.deserializeUser());
        
    exports.getToken = (user: any) => {
        return JWT.sign(user, config.secretKey,{ expiresIn : "2 days"});
    };
    
    const opt = {
        secretOrKey : config.secretKey,
        jwtFromRequest : ExtractJWT.fromAuthHeaderAsBearerToken()
    };
    
    
    exports.jwtAuth = passport.use(new passportJWTStrategy(opt , (payload ,done) => {
    
        User.findOne({_id : payload._id},(err: any , user: User) => {
            if(err){
                return done(err,false);
            }
            else if(user){
                return done(null , user);
            }
            else{
                return done(null, false);
            }
        });
    }));
    
    export const verifyUser = passport.authenticate('jwt', {session : false});
    
    export function verifyAdmin(req: Request, res: Response, next: NextFunction) {
        if(req.user.admin){
            return next();
        }
        else{
            let err = new Error('Only Admin can access to this web page or resources!');
            err.status = 403;
            return next(err);
        }
    }

Actually this was a NodeJS code written in JavaScript already, but when I tried to change the language of the application from JavaScript to TypeScript I get the following errors:

    Property 'authenticate' does not exist on type 'Model<Document<any, any, any>, {}, {}>'.ts(2339)
    
    Property 'serializeUser' does not exist on type 'Model<Document<any, any, any>, {}, {}>'.ts(2339)
    
    Property 'deserializeUser' does not exist on type 'Model<Document<any, any, any>, {}, {}>'.ts(2339)
    
    'User' refers to a value, but is being used as a type here. Did you mean 'typeof User'?ts(2749)

To resolve the problem I changed the `models/users.ts` code according to my searches like the following but still get new errors:

    interface digitalWalletDocument extends Document{
        currencyName: string;
        value: number;
    
    }
    
    const digitalWalletSchema = new Schema<digitalWalletDocument>({
        currencyName : {
            type : String
        },
        value : {
            type : Number
        }
    });
    
    
    interface userDocument extends Document{
        username :  String;
        firstName : String;
        lastName : String;
        email : String;
        telNumber : Number;
        nationalCode : Number;
        admin : Boolean;
        image :  String;
        wallet : Number;
        rate : Number;
        shabaCode :Number;
        cardNumber : Number;
        birthDay : String;
        status : String;
        address : String;
        documnetPath : String;
        description : String;
        purchased : String;
        digitalWallet : digitalWalletDocument;
    }
    
    const userSchema = new Schema<userDocument>({
        username : {
            type : String,
            sparse : true ,
            unique : true
        },
        firstName : {
            type: String
        },
        lastName : {
            type : String
        },
        email : {
            type : String,
            unique : true
        },
        telNumber : {
            type : Number
        },
        nationalCode : {
            type : Number,
            sparse : true,
            unique : true
        },
        admin : {
            type:Boolean,
            default : false
        },
        image : {
            type : String
        },
        wallet: {
            type : Number,
            default : 0
        },
        rate : {
            type : Number,
            default : 0
        },
        shabaCode : {
            type : Number
        },
        cardNumber : {
            type : Number
        },
        birthDay : {
            type : String
        },
        status : {
            type : String
        },
        address : {
            type : String
        },
        documnetPath : {
            type : String
        },
        description : {
            type: String
        },
        purchased : [String],
        digitalWallet : [digitalWalletSchema]
    }, {timestamps : true});
    
    userSchema.plugin(passportLocalMongoose,{usernameField : 'email'});
    
    export default mongoose.model('User' , userSchema);

The new error that arises is:

    Argument of type '(schema: Schema<Document<any, any, any>, Model<Document<any, any, any>, any, any>, undefined, {}>, options?: Object | undefined) => void' is not assignable to parameter of type '(schema: Schema<userDocument, Model<userDocument, {}, {}>, undefined, {}>, opts?: any) => void'.
      Types of parameters 'schema' and 'schema' are incompatible.
        Type 'Schema<userDocument, Model<userDocument, {}, {}>, undefined, {}>' is not assignable to type 'Schema<Document<any, any, any>, Model<Document<any, any, any>, any, any>, undefined, {}>'.
          Types of property 'methods' are incompatible.
            Type '{ [name: string]: (this: userDocument & Document<any, any, userDocument>, ...args: any[]) => any; }' is not assignable to type '{ [name: string]: (this: Document<any, any, any>, ...args: any[]) => any; }'.

And it comes from this line of the code:

    userSchema.plugin(passportLocalMongoose,{usernameField : 'email'});

**Comment by IslandRhythms** [comment]
@vkarpov15 seems like the stuff we were dealing with mongoose lean getters and lean virtuals

**Comment by learner00000** [comment]
> @vkarpov15 seems like the stuff we were dealing with mongoose lean getters and lean virtuals

Is this a Mongoose bug or my program's problem?

**Comment by Sandroggy** [comment]
> Is this a Mongoose bug or my program's problem?

I have the same issue since 22/04 and I think is related to the dependencies of my project (going to previous commit didn't change anything)

My project uses docker, typescript and typegoose

**Comment by vkarpov15** [comment]
Without knowing the Mongoose version, hard to tell. There is a known issue with `@types/passport-local-mongoose` not supporting Mongoose 6, so that might explain this issue. See #11599 .

Please upgrade to passport-local-mongoose `>= 7.1.0`, which has [Mongoose 6 compatible type bindings](https://github.com/saintedlama/passport-local-mongoose/blob/main/CHANGELOG.md#710-2022-05-17), and remove your dependency on `@types/passport-local-mongoose`.
