### ISSUE TITLE
src/bson.ts:31:3 Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

### ISSUE THREAD

**Issue by Gerrist** [Automattic/mongoose#11715]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Getting a type error

`npm run build

> webapp-nextjs@0.1.0 build
> next build

Failed to compile.

./node_modules/mongodb/src/bson.ts:31:3
Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

  29 |   DBRef,
  30 |   Decimal128,
> 31 |   Document,
     |   ^
  32 |   Double,
  33 |   Int32,
  34 |   Long,
`
**If the current behavior is a bug, please provide the steps to reproduce.**

`{
  "name": "webapp-nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@craco/craco": "^6.4.3",
    "@types/moment": "^2.13.0",
    "@types/mongoose": "^5.11.97",
    "momentjs": "^2.0.0",
    "mongoose": "^6.3.1",
    "next": "12.1.5",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  },
  "devDependencies": {
    "@types/node": "^17.0.26",
    "@types/react": "18.0.6",
    "@types/react-dom": "18.0.2",
    "autoprefixer": "^10.4.5",
    "eslint": "8.14.0",
    "eslint-config-next": "12.1.5",
    "postcss": "^8.4.12",
    "tailwindcss": "^3.0.24",
    "typescript": "4.6.3"
  }
}
`
**What is the expected behavior?**
Not receiving this error
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v17.2.0
Mongoose: ^6.3.1
Mongo: ^4.5.0
(Got mongo and mongoose version from package.json)

Not able to execute `mongoose.version`  as my script won't even compile

**Comment by Uzlopak** [comment]
First of all: Why are you using @types/mongoose ? Please remove it.

**Comment by IslandRhythms** [comment]
What are you using that is causing this error? What needs to be installed?

**Comment by vkarpov15** [comment]
Without access to a repo that demonstrates this issue, we're unlikely to be able to repro. Hard to guess the exact configs here.

**Comment by vkarpov15** [comment]
@Coledevelopment please open a new issue and follow the issue template
