### ISSUE TITLE
using this in pre/post hooks returns a typeError as this is undefined

### ISSUE THREAD

**Issue by ebosetalee** [Automattic/mongoose#11713]
Mongoose version 5.12.0:

In model schema, I added this pre hook where i use the id to delete fields in other models:

```
schema.pre('deleteMany', async function() {
  console.log(this instanceof mongoose.Query); 
  const id = this.getQuery()._id;
  console.log(id); 
});
```

Instead of the id or true i get this

> false
TypeError: Cannot read properties of undefined (reading 'getQuery')

Even if i do this:
```
schema.pre('deleteMany', { document: true, query: true }, async function() {
  console.log(this instanceof mongoose.Query); 
  const id = this.getQuery()._id;
  console.log(id); 
});
```
I get the same thing.

**Comment by IslandRhythms** [comment]
What is `getQuery()`? That error is popping up because `getQuery()` is returning undefined and therefore throwing an error since you are trying to access a property on something undefined.

**Comment by ebosetalee** [comment]
@IslandRhythms  from the error I'm getting this is undefined
so when i did `console.log(this)`

I get 
> undefined

**Comment by ebosetalee** [comment]
@IslandRhythms  `this.getQuery()` is used in the documentation here 
[https://mongoosejs.com/docs/middleware.html#order](https://mongoosejs.com/docs/middleware.html#order)

```
schema.pre('findOneAndUpdate', async function() {
  const docToUpdate = await this.model.findOne(this.getQuery());
  console.log(docToUpdate); // The document that `findOneAndUpdate()` will modify
});
```
From the documentation:

`getQuery()` is used to access the document that the pre hook query intend to perform an operation on

**Comment by ebosetalee** [comment]
@IslandRhythms I'm closing this issue 

I realised I was using arrow function here:

```
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

testSchema.pre('deleteMany', async () => {
    console.log(this);
    console.log(this.getQuery());
    const id = this.getQuery()._id;
    console.log(id);
});
```
And it works for regular function
