### ISSUE TITLE
Correct typings without extending Document

### ISSUE THREAD

**Issue by boojum** [Automattic/mongoose#11728]
**Do you want to request a *feature* or report a *bug*?**
Neither a feature request nor a bug, rather a shy cry for help.

**What is the current behavior?**
I'm trying to use TypeScript to ensure type-safety for the defined models. To that end I'm following the documentation. And while I got most of it working as expected, few unresolved issues remain - and to those I can't find solutions in the official documentation.

Continuing with a `user` model from the documentation, extended to cover instance methods, query helpers, and virtuals. Take the following snippet:
```js
import { connect, Schema, model } from 'mongoose'
import argon2 from 'argon2'
import { Model, Document, Query } from 'mongoose'

type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>

type User = {
  email: string
  firstName: string
  lastName: string
  password: string
}

type UserVirtuals = {
  fullName: string
}

type UserMethods = {
  verifyPassword: (plaintext: string) => Promise<boolean>
}

type UserQueryHelpers = {
  byEmail(email: string): Query<any, Document<User>> & UserQueryHelpers
}

type UserModel = Model<User, UserQueryHelpers, UserMethods, UserVirtuals>

type UserDocument = User & Document

const userSchema = new Schema<User, UserModel, UserMethods, UserQueryHelpers>(
  {
    email: { type: String, required: true, unique: true },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    password: { type: String, required: true },
  },
  {
    timestamps: true,
    toJSON: {
      versionKey: false,
      transform: function (_, ret: Optional<User, 'password'> & Document) {
        ret.id = ret._id
        delete ret._id
        delete ret.password
      },
    },
    toObject: {
      versionKey: false,
      transform: function (_, ret: Optional<User, 'password'> & Document) {
        ret.id = ret._id
        delete ret._id
        delete ret.password
      },
    },
  },
)

userSchema.pre<UserDocument>('save', async function (next) {
  if (this.isModified('password')) {
    const hashed = await argon2.hash(this.get('password'))
    this.set('password', hashed)
  }
  next()
})

userSchema.virtual<UserDocument>('fullName').get(function () {
  return `${this.firstName} ${this.lastName}`
})

userSchema.methods.verifyPassword = async function (
  plaintext: string,
): Promise<boolean> {
  return await argon2.verify(plaintext, this.password)
}

userSchema.query.byEmail = function (email: string) {
  return this.find({ email })
}

export const user = model<User, UserModel>('users', userSchema)
```
I'm left with seven TypeScript errors, and no idea how to approach them:

![1](https://user-images.githubusercontent.com/1714885/166160570-eae03155-1dbe-48ad-a78e-0ea055967e94.jpeg)
![2](https://user-images.githubusercontent.com/1714885/166160642-89c012e3-60ea-40ac-af85-10147357ca6d.jpeg)
![3](https://user-images.githubusercontent.com/1714885/166160646-11bebe28-df66-4d80-a680-90535eea1656.jpeg)
![4](https://user-images.githubusercontent.com/1714885/166160663-65c6fd76-8112-4c3d-8bb4-8d5ea5f0076b.jpeg)
![5](https://user-images.githubusercontent.com/1714885/166160665-1c566925-6498-4576-ac37-f1247a3608a7.jpeg)
![6](https://user-images.githubusercontent.com/1714885/166160671-efba73ef-a1ef-450f-ad10-5b5484d28d1a.jpeg)
![7](https://user-images.githubusercontent.com/1714885/166160675-4fd4fe42-aa06-4e0f-86f8-1dcfb5409a0e.jpeg)

I was searching through the Github Issues but couldn't find any hints here. Searching through Gitter chat logs didn't help much either. I would appreciate any and all hints as to how I can make those pesky errors to go away.

If this was already approached and answered somewhere else, then my apologies!

Complimentary `tsconfig.json`:
```json
{
  "ts-node": {
    "esm": true
  },
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext"],

    "baseUrl": ".",
    "outDir": "dist",

    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,

    "strict": true,

    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"]
}
```
Also, if relevant, `eslintrc.cjs`:
```js
module.exports = {
  root: true,
  env: {
    es2022: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'prettier',
  ],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: './tsconfig.json',
  },
  ignorePatterns: ['*.cjs', 'dist/*'],
  overrides: [
    {
      files: ['**/*.test.js'],
      env: { jest: true },
      plugins: ['jest'],
      extends: ['plugin:jest/recommended', 'plugin:jest/style'],
    },
  ],
  rules: {
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
  },
}
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```sh
node -v
v18.0.0
npm view mongoose version
6.3.1
mongod --version
db version v5.0.7
```

**Comment by Uzlopak** [comment]
You could define this in typescript by providing this as first parameter with the correct typing. 

function bla(this: User) {
    this._id;
}

We are currently working on getting better typings. For this we the next step is to habe automatically typed models, by @mohammad0-0ahmad 

I would say we should merge the open PR for the auto typings first and then touch the scope of those functions if necessary. @mohammad0-0ahmad this is not an invitation to also cover this in your PR :). Lets get your PR merged first...

**Comment by mohammad0-0ahmad** [comment]
> You could define this in typescript by providing this as first parameter with the correct typing.
> 
> function bla(this: User) { this._id; }
> 
> We are currently working on getting better typings. For this we the next step is to habe automatically typed models, by @mohammad0-0ahmad
> 
> I would say we should merge the open PR for the auto typings first and then touch the scope of those functions if necessary. @mohammad0-0ahmad this is not an invitation to also cover this in your PR :). Lets get your PR merged first...

Thanks for the mention @Uzlopak,
I've planned to cover virtuals and some other TS improvements, but in separate PR's to make them easier to get merged.

**Comment by boojum** [comment]
@Uzlopak @mohammad0-0ahmad 
Just had a look at the PR - looks fantastic! I'll close this for now to not pollute the issue tracker. I'll revisit the issue when #11563 / #9715 will be ready.

Thanks for all your work on this project!
