### ISSUE TITLE
mongoose upgrade issue in schema defintion

### ISSUE THREAD

**Issue by sugandansa** [Automattic/mongoose#11721]
```
Type 'Schema<UserSchemaProps, Model<DocType, any, any, any>, {}, {}>' is not assignable to type 'Schema<IDocUser, Model<IDocUser, any, any, any>, {}, {}>'.
  Types of property 'add' are incompatible.
    Type '(obj: { email?: SchemaDefinitionProperty<StringConstructor> | undefined; firstName?: SchemaDefinitionProperty<StringConstructor> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; } | Schema<...>, prefix?: string | undefined) => Schema<...>' is not assignable to type '(obj: Schema<any, Model<any, any, any, any>, {}, {}> | { _id?: SchemaDefinitionProperty<any> | undefined; __v?: SchemaDefinitionProperty<any> | undefined; id?: SchemaDefinitionProperty<...> | undefined; email?: SchemaDefinitionProperty<...> | undefined; firstName?: SchemaDefinitionProperty<...> | undefined; lastName...'.
      Types of parameters 'obj' and 'obj' are incompatible.
        Type 'Schema<any, Model<any, any, any, any>, {}, {}> | { _id?: SchemaDefinitionProperty<any> | undefined; __v?: SchemaDefinitionProperty<any> | undefined; id?: SchemaDefinitionProperty<...> | undefined; email?: SchemaDefinitionProperty<...> | undefined; firstName?: SchemaDefinitionProperty<...> | undefined; lastName?: Sch...' is not assignable to type '{ email?: SchemaDefinitionProperty<StringConstructor> | undefined; firstName?: SchemaDefinitionProperty<StringConstructor> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; } | Schema<...>'.
          Type '{ _id?: SchemaDefinitionProperty<any> | undefined; __v?: SchemaDefinitionProperty<any> | undefined; id?: SchemaDefinitionProperty<any> | undefined; email?: SchemaDefinitionProperty<...> | undefined; firstName?: SchemaDefinitionProperty<...> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; }' is not assignable to type '{ email?: SchemaDefinitionProperty<StringConstructor> | undefined; firstName?: SchemaDefinitionProperty<StringConstructor> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; } | Schema<...>'.
            Type '{ _id?: SchemaDefinitionProperty<any> | undefined; __v?: SchemaDefinitionProperty<any> | undefined; id?: SchemaDefinitionProperty<any> | undefined; email?: SchemaDefinitionProperty<...> | undefined; firstName?: SchemaDefinitionProperty<...> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; }' is not assignable to type '{ email?: SchemaDefinitionProperty<StringConstructor> | undefined; firstName?: SchemaDefinitionProperty<StringConstructor> | undefined; lastName?: SchemaDefinitionProperty<...> | undefined; }'.
              Types of property 'email' are incompatible.
                Type 'SchemaDefinitionProperty<string> | undefined' is not assignable to type 'SchemaDefinitionProperty<StringConstructor> | undefined'.
                  Type 'SchemaTypeOptions<string>' is not assignable to type 'SchemaDefinitionProperty<StringConstructor> | undefined'.
                    Type 'SchemaTypeOptions<string>' is not assignable to type 'SchemaTypeOptions<StringConstructor>'.
                      Types of property 'type' are incompatible.
                        Type 'StringSchemaDefinition | undefined' is not assignable to type 'Function | StringConstructor | typeof SchemaType | Schema<any, any, any, {}> | AnyArray<Function> | { readonly prototype?: SchemaDefinitionProperty<...> | undefined; fromCharCode?: SchemaDefinitionProperty<...> | undefined; fromCodePoint?: SchemaDefinitionProperty<...> | undefined; raw?: SchemaDefinitionProperty<......'.
                          Type '"string"' is not assignable to type 'Function | StringConstructor | typeof SchemaType | Schema<any, any, any, {}> | AnyArray<Function> | { readonly prototype?: SchemaDefinitionProperty<...> | undefined; fromCharCode?: SchemaDefinitionProperty<...> | undefined; fromCodePoint?: SchemaDefinitionProperty<...> | undefined; raw?: SchemaDefinitionProperty<......'.ts(2322)
```
code:
```typescript
import mongoose, {
  model, Schema, Model, Document, SchemaDefinition,
} from 'mongoose';

const express = require('express');
const bodyParser = require('body-parser');
const methodOverride = require('method-override');

interface IUser extends Document {
  email: string;
  firstName: string;
  lastName: string;
}

interface IDocUser extends mongoose.Document, IUser { }

interface UserSchemaProps {
  email: typeof String;
  firstName: typeof String;
  lastName: typeof String;
}

function createSchema<T>(definition: SchemaDefinition<T>) {
  return new Schema<T>(definition);
}

const UserSchemaDefinition: mongoose.SchemaDefinition = {
  email: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
};

const UserSchema: Schema<IDocUser> = createSchema<UserSchemaProps>(UserSchemaDefinition);

const User: Model<IUser> = model('User', UserSchema);
// eslint-disable-next-line wrap-iife
(async function () {
  mongoose.connect('mongodb://localhost:27017/test');
})
```

**Comment by sugandansa** [comment]
I am trying to update mongoose version from 5.5.34 to 6.x i am facing above issue

**Comment by IslandRhythms** [comment]
What specific version are you upgrading to

**Comment by sugandansa** [comment]
> Why do you use typeof String?

Do i need to remove that


> I am trying to update mongoose version from 5.5.34 to 6.x i am facing above issue



> What specific version are you upgrading to

  "mongoose": "^6.3.1"

**Comment by sugandansa** [comment]
> What specific version are you upgrading to

  "mongoose": "^6.3.1"

**Comment by Uzlopak** [comment]
Usually you dont use TypeConstructor but he the type. So not typeof String but string.

**Comment by sugandansa** [comment]
> TypeConstructor
 I changed still not working
import mongoose, {
  model, Schema, Model, Document, SchemaDefinition,
} from 'mongoose';

const express = require('express');
const bodyParser = require('body-parser');
const methodOverride = require('method-override');

interface IUser extends Document {
  email: string;
  firstName: string;
  lastName: string;
}

interface IDocUser extends mongoose.Document, IUser { }

interface UserSchemaProps {
  email: String;
  firstName: String;
  lastName: String;
}

function createSchema<T extends mongoose.Document>(definition: SchemaDefinition<T>) {
  return new Schema<T>(definition);
}

const UserSchemaDefinition: mongoose.SchemaDefinition = {
  email: { String, required: true },
  firstName: { String, required: true },
  lastName: { String, required: true },
};

const UserSchema: Schema<IDocUser> = createSchema<UserSchemaProps>(UserSchemaDefinition);

const User: Model<IUser> = model('User', UserSchema);
// eslint-disable-next-line wrap-iife
(async function () {
  mongoose.connect('mongodb://localhost:27017/test');

  const user: IUser = await User.create({
    email: 'bill@microsoft.com',
    firstName: 'Bill',
    lastName: 'Gates',
  });

  console.log('Done', user.email);
})();

const app = express();
const router = express.Router();

app.use(bodyParser.json());
app.use(methodOverride());

app.use(router);

app.listen(3000, () => {
  getData();
  console.log();
});

async function getData() {
  const user: IUser | null = await User.findOne({ email: 'bill@microsoft.com' });
  console.log(user);
}

**Comment by sugandansa** [comment]
Argument of type 'SchemaDefinition<T>' is not assignable to parameter of type 'SchemaDefinition<SchemaDefinitionType<T>> | undefined'.
  Type '{ [path: string]: SchemaDefinitionProperty<undefined>; } | { [path in keyof T]?: SchemaDefinitionProperty<T[path]> | undefined; }' is not assignable to type 'SchemaDefinition<SchemaDefinitionType<T>> | undefined'.
    Type '{ [path: string]: SchemaDefinitionProperty<undefined>; }' is not assignable to type 'SchemaDefinition<SchemaDefinitionType<T>>'.
      Type '{ _id?: SchemaDefinitionProperty<any> | undefined; __v?: SchemaDefinitionProperty<any> | undefined; $getAllSubdocs?: SchemaDefinitionProperty<...> | undefined; ... 52 more ...; validateSync?: SchemaDefinitionProperty<...> | undefined; }' is not assignable to type 'SchemaDefinition<SchemaDefinitionType<T>>'

**Comment by sugandansa** [comment]
If i remove generics it is working

import mongoose, {
  model, Schema, Model, Document, SchemaDefinition,
} from 'mongoose';

const express = require('express');
const bodyParser = require('body-parser');
const methodOverride = require('method-override');

interface IUser extends Document {
  email: string;
  firstName: string;
  lastName: string;
}

interface IDocUser extends mongoose.Document, IUser { }

//interface UserSchemaProps {
 // email: typeof String;
 // firstName: typeof String;
  //lastName: typeof String;
//}

function createSchema(definition: SchemaDefinition) {
  return new Schema(definition);
}

const UserSchemaDefinition: mongoose.SchemaDefinition = {
  email: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
};

const UserSchema: Schema<IDocUser> = createSchema(UserSchemaDefinition);

const User: Model<IUser> = model('User', UserSchema);
// eslint-disable-next-line wrap-iife
(async function () {
  mongoose.connect('mongodb://localhost:27017/test');

  const user: IUser = await User.create({
    email: 'bill@microsoft.com',
    firstName: 'Bill',
    lastName: 'Gates',
  });

  console.log('Done', user.email);
})();

const app = express();
const router = express.Router();

app.use(bodyParser.json());
app.use(methodOverride());

app.use(router);

app.listen(3000, () => {
  getData();
  console.log();
});

async function getData() {
  const user: IUser | null = await User.findOne({ email: 'bill@microsoft.com' });
  console.log(user);
}

**Comment by Uzlopak** [comment]
Do you use the typings from definetly typed?

**Comment by vkarpov15** [comment]
You need to use `SchemaDefinition<SchemaDefinitionType<T>>` as the param to `createSchema()`. Below is a working script:

```ts
import mongoose, {
  model, Schema, Model, Document, SchemaDefinition, SchemaDefinitionType
} from 'mongoose';

const express = require('express');
const bodyParser = require('body-parser');
const methodOverride = require('method-override');

interface IUser extends Document {
  email: string;
  firstName: string;
  lastName: string;
}

interface UserSchemaProps {
  email: string;
  firstName: string;
  lastName: string;
}

function createSchema<T>(definition: SchemaDefinition<SchemaDefinitionType<T>>) {
  return new Schema<T>(definition);
}

const UserSchemaDefinition: SchemaDefinition<UserSchemaProps> = {
  email: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
};

const UserSchema: Schema<UserSchemaProps> = createSchema<UserSchemaProps>(UserSchemaDefinition);

const User: Model<IUser> = model<IUser>('User', UserSchema);
// eslint-disable-next-line wrap-iife
(async function () {
  mongoose.connect('mongodb://localhost:27017/test');
})
```
