### ISSUE TITLE
Nested discriminators on Map keys

### ISSUE THREAD

**Issue by zburkhardt-zz** [Automattic/mongoose#11720]
**Do you want to request a *feature* or report a *bug*?**
Clarification on existing functionality

**What is the current behavior?**
I ran across this issue [https://github.com/Automattic/mongoose/issues/8361](url) as I was in need of doing the same thing, essentially being able to set discriminators on Map keys without knowing the keys/paths ahead of time.

After much trial and error I was able to get this to work. Given the original example in the linked issue above I was able to use `.$*` to apply my discriminators to all Map keys like:

```
const shapeSchema = Schema({ name: String }, { discriminatorKey: 'kind' });
const schema = Schema({ shape: {type: Map, of: shapeSchema} });

schema.path('shape.$*').discriminator('Circle', Schema({ radius: String }));
schema.path('shape.$*').discriminator('Square', Schema({ side: Number }));

const MyModel = mongoose.model('ShapeTest', schema);

let doc = new MyModel({ shape: {a: { kind: 'Circle', radius: 5 }, b: { kind: 'Square', side: 10 }} });
doc.shape.a.radius; // 5
doc.shape.b.side; // 10
```

**What is the expected behavior?**
This is behaving exactly how I would hope it would but I am seeking confirmation that this is an appropriate use of `.$*` and that Mongoose is intended to behave in this manner when applying discriminators to Map keys.

 I have not come across any documentation regarding this so I am unsure if there are potential issues with this approach or if it is even meant to work like this.

Any official confirmation/clarification would be much appreciated!

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v16.14.2
Mongoose: 6.3.0
MongoDB: 4.2.9

**Comment by vkarpov15** [comment]
I'm glad to see this works! Admittedly, we have not tested discriminators on maps. But I don't see any reason why the way you implemented it shouldn't work.

We'll make a note to add this to our tests.
