### ISSUE TITLE
Old documentation, delete them?

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11725]
We should think about deleting all the documentation regarding mongoose up to version 4. It makes no sense to keep that old stuff. Also nobody requests currently Support for those versions. And if... Nobody would provide support for them. End of life.

**Comment by Uzlopak** [comment]
After examining the code, removing it from the master could result that the are also removed in the gh-pages branch.

**Comment by Uzlopak** [comment]
But how can remove the old documentation without deleting it in the gh-pages branch? :/

**Comment by hasezoey** [comment]
currently the documentation code does not reference anything before 4.x, but that documentation still exists in `gh-pages` and i dont see a way to remove that without modifying `gh-pages` directly

**Comment by Uzlopak** [comment]
Ah yes. back in the days i moved all old docs into gh-pages.

**Comment by ThePaulin** [comment]
There is no need to remove old documentation since it doesn't cause any issues to people looking for documentation for newer releases

**Comment by Uzlopak** [comment]
I removed like a long time ago old documentation by adding them to gh-pages. So this is done already. :)

**Comment by hasezoey** [comment]
> I removed like a long time ago old documentation by adding them to gh-pages

not really removed, just moved (and is currently harder to access by not being in the version selector, but still accessable)

**Comment by Uzlopak** [comment]
Its accessable yes. But not promoted by the dropdown. If you want you can add them. I actually would remove the 4.x docs from the dropdown to avoid the impression that it is still supported. But anyhow Nobody reported anyway a bug for 4.x so we could actually remove 4.x from the dropdown or add all the old docs. Or leave it as is.
