### ISSUE TITLE
Possible NoSQL injection due to lack of data sanitization in Redis-Todo example	

### ISSUE THREAD

**Issue by ImanSharaf** [Automattic/mongoose#11727]
I believe [this](https://github.com/Automattic/mongoose/blob/master/examples/redis-todo/routers/todoRouter.js#L44) code is vulnerable to NoSQLi. I know it is just an example project, but people might copy and paste your example and build a vulnerable product on top of that.

**Comment by Uzlopak** [comment]
findOneAndUpdate should call the validation functions. So there should be no injection be possible.Also keep in mind there is more a risk to save huge payloads in the database because the text attribute has no maximum length set... 

I dont think that a injection is actually possible.

**Comment by vkarpov15** [comment]
@Uzlopak it is possible. The filter portion, not the update. See https://thecodebarbarian.com/2014/09/04/defending-against-query-selector-injection-attacks.html and https://thecodebarbarian.com/whats-new-in-mongoose-6-sanitizefilter.html
