### ISSUE TITLE
Error testing

### ISSUE THREAD

**Issue by maybesmurf** [Automattic/mongoose#11730]
**Do you want to request a *feature* or report a *bug*?**
I suppose ?

**What is the current behavior?**
I'm getting "The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type." error while testing if error is of mongoose's by `error instanceof mongoose.Error`. By taking a look at the types exported by mongoose, i notice Error is now a namespace which compared to previous versions was a class so perhaps this is why. Also, it seems like the `Error` class had been renamed to `MongooseError` yet i still get a "Right-hand side of 'instanceof' is not an object" error if i test for `error instanceof mongoose.MongooseError`

**Comment by IslandRhythms** [comment]
Please provide the script causing this error

**Comment by Uzlopak** [comment]
MongooseError is a class. So instanceof should work as expected.

**Comment by Uzlopak** [comment]
Are you using jest?

**Comment by vkarpov15** [comment]
@maybesmurf please provide a repro script. This screenshot isn't very helpful.

**Comment by Uzlopak** [comment]
Duplicate of #11838 
Should be fixed.
