### ISSUE TITLE
Typescript: Can't assign full document to ObjectId foreign field

### ISSUE THREAD

**Issue by ajwootto** [Automattic/mongoose#11762]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If a define a model that has a foreign key field pointing to a different model, then normally I can assign the full model document to that field and it will automatically use the _id of the assigned document when saving. With the current type definitions, I can't 
assign the full document to that field.

**If the current behavior is a bug, please provide the steps to reproduce.**

```typescript
import { Schema, model, connect, Types, connection } from 'mongoose'

interface NestedChild {
    name: string
    _id: Types.ObjectId
}
const nestedChildSchema: Schema = new Schema({ name: String })

interface Parent {
    nestedChild: Types.ObjectId
    name?: string
}

const ParentModel = model<Parent>('Parent', new Schema({
    nestedChild: { type: Schema.Types.ObjectId, ref: 'NestedChild' },
    name: String
}))

const NestedChildModel = model<NestedChild>('NestedChild', nestedChildSchema)

export async function run() {
    await connect('mongodb://localhost:27017/')
    const parent = new ParentModel({
        name: 'Parent',
    })

    // doesn't work, should be assigned to object id
    parent.nestedChild = new NestedChildModel({ name: 'test' })

    await parent.save()
}

run()

```

**What is the expected behavior?**
It would be convenient if the typing here allowed for this behaviour, which is valid in regular Mongoose

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 6.3.1

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior in TypeScript. We've been looking for a solution to this, but we don't know of a good way to handle the case where `parent.nestedChild` is expected to be an ObjectId when you read it, but when you set `parent.nestedChild` you can set it to something that isn't an `ObjectId`.

The workaround is to use `parent.set()`, which is equivalent in JavaScript:

```ts
parent.set('nestedChild', new NestedChildModel({ name: 'test' }))
```
