### ISSUE TITLE
Mongoose 6.3.2 - Schema hasn't been registered for model ...

### ISSUE THREAD

**Issue by passosiago** [Automattic/mongoose#11771]
**Do you want to request a *feature* or report a *bug*?**

*BUG*

**What is the current behavior?**

I've a git repository where i store all my schemas and the function responsible for connecting to the database. And i'm installing it as a npm package on my project.

I was using mongoose version 5.10.18, and everything was working fine. But after i upgraded to 6.3.2  i started getting the error that my models are not registered. 

```Schema hasn't been registered for model \"User\"```

Debugging the code locally i saw this particular line ````model = this.base.models[name];```` , that is not present in the new version. That is the exactly point where it bonds the model that that i'm passing to the already registered models.

**If the current behavior is a bug, please provide the steps to reproduce.**

Example of exported schema 

````
// schema_user.js
const mongoose = require('mongoose')

const userSchema = new mongoose.Schema(
 {
   userID: {type:String, required:true, unique:true},
   userName: {type:String, required:true, unique:true}
 }
)

module.exports = mongoose.model("User", userSchema);
````

Example of  connection function on version 5.10.18
````
// connection.js
const connectToDb = async(mongoUri) => {
  let conn_db = mongoose.createConnection(mongoUri, {
    bufferCommands: false,
    bufferMaxEntries: 0,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true,
    poolSize: 1,
    socketTimeoutMS: 2000000,
    keepAlive: true,
  });

 await conn_db;
 return conn_db;
}

module.exports = { connectToDb };

````

Example of  connection function on version 6.3.2 
````
// connection.js
const connectToDb = async(mongoUri) => {
  let conn_db = mongoose.createConnection(mongoUri, {
    bufferCommands: false,
    keepAlive: true,
    keepAliveInitialDelay: 300000,
    autoIndex: false,
    maxPoolSize: 10,
    serverSelectionTimeoutMS: 5000, 
    socketTimeoutMS: 45000, 
    family: 4, 
  });

 await conn_db.asPromise();
 return conn_db;
}

module.exports = { connectToDb };

````

All the schemas and the connection function are exported from a index.js file like this.

````
// index.js 

module.exports = {
 SCHEMA_USER: require('./schema_user.js'),
 DB_CONNECTION: require('./connection.js').connectToDb,
}

````

I'm importing them on my project like the above 

````
// main.js

const { SCHEMA_USER, DB_CONNECTION } = require('my-custom-library')
let connection = await DB_CONNECTION('my-mongo-url');
let result = await connection.model(SCHEMA_USER.modelName).find();
console.log(result);

````

**What is the expected behavior?**

I expect not to receive this error ```Schema hasn't been registered for model \"User\"``` and query runs sucessfully.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 17.2.0
Mongoose 6.3.2

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({name: String});
const Test = mongoose.model('Test', testSchema);
async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await mongoose.connection.model('Test').find();
    console.log('done');
}

run();
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({name: String});
const Test = mongoose.model('Test', testSchema);
async function run() {
    // await mongoose.connect('mongodb://localhost:27017');
    // await mongoose.connection.dropDatabase();
    // await mongoose.connection.model('Test').find();

    const connection = await mongoose.createConnection('mongodb://localhost:27017');
    await connection.model('Test').find();
    console.log('done');
}

run();
```

**Comment by vkarpov15** [comment]
This is expected behavior. In Mongoose 6, we do not pull models from the Mongoose global to connections. You would need to do `conn_db.model()` instead of `mongoose.model()`.

**Comment by passosiago** [comment]
Hi @vkarpov15 ,

I am doing exactly what you said. From the `connection.js` i'm exporting the function that creates the connection and returns it. And on my main.js i'm calling connection.model after creating the connection from the connection library, not calling it directly using mongoose.model.

**Comment by vkarpov15** [comment]
@passosiago you're not doing what I said. You're creating a model in `schema_user.js` here: `module.exports = mongoose.model("User", userSchema);`, and then referencing the model in `main.js` here: `let result = await connection.model(SCHEMA_USER.modelName).find();`

Calling `mongoose.model('User', schema)` means you're defining a model on the default Mongoose connection, **not** the connection you're creating in `connectToDb()`
