### ISSUE TITLE
Date are saved as strings when using Aggregation pipeline update

### ISSUE THREAD

**Issue by thaoula** [Automattic/mongoose#11773]
Hi All,

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When saving a date using findByIdAndUpdate using an aggregation pipeline the date is saved a string. When saved using a regular $set the date is set correctly as a Date type.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Craft an update using findByIdAndUpdate such as the following:

findByIdAndUpdate(123, { $set: { dateField: '2022-05-26T00:00:00.000Z'} }) - The date will be saved as date;
findByIdAndUpdate(123, [{ $set: { dateField: '2022-05-26T00:00:00.000Z' } }] ) - The date will be saved as string;

2. Execute the query and check the date field. Option 1 will result in a date stored as a date. Option 2 will result in a date stored as string.

**What is the expected behavior?**
The expected behaviour is that the value will be stored as a date datatype.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
17.6, 6.32 and 5.01

Regards,
Tarek

**Comment by Uzlopak** [comment]
First of all, I didnt know that you can put aggregation pipelines into findByIdAndUpdate. It is documented, that mongoose not casts in aggregation pipelines.

https://mongoosejs.com/docs/api/aggregate.html#note

**Comment by IslandRhythms** [comment]
We are definetly going to need a script from you

**Comment by Uzlopak** [comment]
@IslandRhythms 

I dont think that a script will be necessary, because this not a bug but a well known behaviour. The reason is, that we can not implement casting in aggegation pipelines, as tihs would mean that we basically have to code a mongodb aggregation pipeline emulator. This is not a simple patch but basically a new massive feature, where we lack the manpower and time.

**Comment by thaoula** [comment]
Hi @IslandRhythmsm, @Uzlopak 

> We are definitely going to need a script from you

Take any collection with a Mongoose schema containing a dateField and execute the following -

```
findByIdAndUpdate(123, { $set: { dateField: '2022-05-26T00:00:00.000Z'} }) - The date will be saved as date;
findByIdAndUpdate(123, [{ $set: { dateField: '2022-05-26T00:00:00.000Z' } }] ) - The date will be saved as string (notice the update is an array);
```

@Uzlopak I did not know it was not supported. I also understand that it is a massive feature but IMHO it should not be discounted as can be extremely powerful way to perform updates.

 The reason I was actually trying to use this MongoDB feature is because of the inability to update subdocuments properties when the subdocument = null.

```
{
  customFields: null
}

findByIdAndUpdate(123, { $set: { 'customFields.dateField': '2022-05-26T00:00:00.000Z'}}) - This will throw an error
findByIdAndUpdate(123, [{ $set: { 'customFields.dateField': '2022-05-26T00:00:00.000Z' }}]) - This will correctly patch the record
```

Is there anyway to call the casting logic Mongoose uses for a standard set? In this case I am issuing the exact same $set in both cases and I just need to types to be cast correctly.

Regards,
Tarek

**Comment by Uzlopak** [comment]
Why dont you just wrap the string in a Date()

**Comment by thaoula** [comment]
Because the update statement is being automatically created by code and it does not have direct knowledge of the field being set. The Mongoose magic was doing this stuff for us in a regular update.

**Comment by thaoula** [comment]
FYI - this is the Mongo db issue I was trying to get around -
https://jira.mongodb.org/browse/SERVER-5143

**Comment by Uzlopak** [comment]
we should atleast get this case to work:

 findByIdAndUpdate(123, { $set: { 'customFields.dateField': '2022-05-26T00:00:00.000Z'}}) - This will throw an error
