### ISSUE TITLE
calling this in immutable doesn't return the document mongoose

### ISSUE THREAD

**Issue by olawalejuwonm** [Automattic/mongoose#11777]
![image](https://user-images.githubusercontent.com/52759812/167211348-fa5ace93-47a8-412a-a370-9a4256eee463.png)

This was returned

**Comment by Uzlopak** [comment]
Looks more like the query

**Comment by olawalejuwonm** [comment]
What's the way forward please

**Comment by vkarpov15** [comment]
@olawalejuwonm if you set `immutable` to a function, `this` may be either a document or a query (for `updateOne()`, `updateMany()`, etc.). You as the developer are responsible for handling both cases.
