### ISSUE TITLE
why transform.options auto convert inline params model to json ? 

### ISSUE THREAD

**Issue by smallst** [Automattic/mongoose#11776]
**Do you want to request a *feature* or report a *bug*?**
i'm not sure it is a bug or feature, but the behaviors change since mongoose 4 -> 5/6. and without any breaking changelogs. 
**What is the current behavior?**
for now, if you define the `transform` function for a schema, the inline params passed into `options` no longer support mongoose model. (but supports in mongoose 4). so you could not call `options.model.get` anymore. 

**If the current behavior is a bug, please provide the steps to reproduce.**

here is a gist to reproduce the behaviors .
https://gist.github.com/smallst/506f493bbe47f5bf1d62d1485b88d12c 
see line 34 and 14-17.

and here is the running results
![image](https://user-images.githubusercontent.com/11417632/167054838-0b675b48-dbac-4faa-8318-a4175d9424ad.png)

**What is the expected behavior?**
i think if we pass in a `model`, it should be still a `model` inside transform function. Or you could tell me (in the Doc) why it is not. 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
version: 
nodejs: v17.9.0
mongoose: 6.3.2
mongodb: 4.0

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose')
const Schema = mongoose.Schema;
const ObjectId = Schema.ObjectId;

const ASchema = new Schema({
  name: String
})
const BSchema = new Schema({
  name: String,
  aName: String
})

ASchema.set('toObject', {
  transform: (doc, ret, options) => {
    console.log('correct:', options.b.aName)         // now this is the correct way
    console.log('error:', options.b.get('aName'))    // in mongoose 4 we use this.
  }
})

const AModel = mongoose.model('AModel', ASchema)
const BModel = mongoose.model('BModel', BSchema)

let main = async () => {
  await mongoose.connect('mongodb://localhost/test_mongoose');
  await mongoose.connection.dropDatabase();
  const a = new AModel()
  a.name = 'a'
  await a.save()

  const b = new BModel()
  b.name = 'b';
  b.aName = 'a';
  await b.save()

  console.log(a.toObject({b}))               // pass in a model, but no longer get a model

}

main().then(() => {console.log('done')})
```

**Comment by smallst** [comment]
i think the bug comes from [here](https://github.com/Automattic/mongoose/blob/7515b810f823f838a8d45ab39c0329ad51b31d7c/lib/helpers/clone.js#L46-L48), you return the `._doc` when clone mongoose model.

**Comment by smallst** [comment]
i don't know if `utils.clone` should work as clone mongoose model to normal object (._doc) , and if `utils.clone` returns mongoose model as model would cause any issue.  but maybe another `utils.cloneModel` function can work here? which clone everything as everything. 
not sure if this suggests helps. 
and i'm still using mongoose 5 (just upgraded from mongoose 4) in my company, that's a huge codebase so maybe not so easy to upgrade to mongoose 6 soon, if you fix this bug on mongoose 6 could you also publish a new version of mongoose 5 with same bugfix? thanks a lot

**Comment by vkarpov15** [comment]
Count this as another use case for #11849. We'll use shallow clone because there's no reason for us to deep clone `options`.

**Comment by smallst** [comment]
thanks!
