### ISSUE TITLE
E11000 duplicate key error collection: Profiles Failed _id or unique key constraint

### ISSUE THREAD

**Issue by Dharam625** [Automattic/mongoose#11789]
Hi,

I have a requirement where i need to add objects to an array (E.g. properties array in below json). I am able to create initial document as per my requirements.

```
{
    "_id" : "DH-AM-123",
    "payload" : {
        "avatars" : {
            "properties" : [ 
                {
                    "propId" : "1234",
                    "type" : "abcs",
                    "color" : "light"
                }
            ]
        }
    },
}
```

However when i try to add another property ({"propId" : "5678", "type" : "fgfgf","color" : "light"}) to properties of above json, i get "E11000 duplicate key error collection: Profiles Failed _id or unique key constraint"

**My Mongo Model:**
```
var propertiesSchema = new Schema({
  _id: false,
  propId: String,
  type: String,
  color: String,
});

module.exports = mongoose.model('Profile', new Schema({
  _id: String,
  payload: {
    avatars: {
           properties: [propertiesSchema]
      ]
    },
  }
}, { collection: 'ProfilesTest' }));
```

**My Query is:**

```
    await Profile.findOneAndUpdate(
        { 
         _id: contactId,
         "payload.avatars.properties": [{
           "propId": propId,
           'type': type,
           'color': color
          }]
        },
        { 
            $set: { 
             "payload.avatars.properties.$.element": {
               propId,
               type,
               color
             }
            }
        },
        {
         upsert: true,
        }
       )
  }
```

**my expected Json structure is :**

```
{
    "_id" : "DH-AM-123",
    "payload" : {
        "avatars" : {
            "properties" : [ 
                {
                    "propId" : "1234",
                    "type" : "abcs",
                    "color" : "light"
                },
                {
                    "propId" : "5678",
                    "type" : "fgfgf",
                    "color" : "light"
                },
            ]
        }
    },
}
```
I tried everything like $set, $addToSet, $push. I am sure i am doing something wrong with the query. I do want the whole document to be unique but i should be able to add more properties inside properties array.

I would really appreciate if you have any experience in this matter.

**Comment by Uzlopak** [comment]
```json
var propertiesSchema = new Schema({
  _id: false,
  propId: String,
  type: String,
  color: String,
});
```

Should be imho actually 
```javascript
var propertiesSchema = new Schema({
  propId: String,
  type: String,
  color: String,
}, {_id: false});

```

**Comment by Dharam625** [comment]
> 

I tried but no luck. I am still getting same [E11000 duplicate key error collection: Profiles Failed _id or unique key constraint](https://github.com/Automattic/mongoose/issues/11789#)

**Comment by Uzlopak** [comment]
Look into the mongodb with mongo compass or studio3t or, or, or... and check if there is a _id: null field in the one element of the properties array or in the other properties-Array.

**Comment by Dharam625** [comment]
This is the only document I have in in my collection @Uzlopak 

`{
    "_id" : "DH-AM-123",
    "payload" : {
        "avatars" : {
            "properties" : [ 
                {
                    "propId" : "1234",
                    "type" : "abcs",
                    "color" : "light"
                }
            ]
        }
    },
} `

**Comment by Dharam625** [comment]
just default one which is _id @Uzlopak
