### ISSUE TITLE
collection already exists

### ISSUE THREAD

**Issue by sugandansa** [Automattic/mongoose#11784]
"before all" hook in "Plugin":
     MongoServerError: a collection 'test-349fff.mapfeatures' already exists

**Comment by IslandRhythms** [comment]
Please provide more details as to what you're doing, as well as a script that can show us what is going on. Without any other details, the most I can say is that when you call `mongoose.model()`, you're reusing a collection name.

**Comment by AbdelrahmanHafez** [comment]
Welcome @sugandansa 

I'll close this issue, please open a new open and follow the issue template, without that it's very difficult to provide any assistance. Thanks for understanding.
