### ISSUE TITLE
Using '$or', if a conditional field does not exist, this query will find all values

### ISSUE THREAD

**Issue by littleboyfury** [Automattic/mongoose#11788]
Use find, add $or query, if this field does not exist in schema, all values will be queried, mongodb does not have this problem.

my db have three documents, `db.users.insertMany([{name: '1', sid: '1', uid: 1},{name: '2',sid: '2',uid: 2}, {name: '3',sid: '3', uid: 3}])`

## mongodb query
```js
const {MongoClient} = require('mongodb')

const url = 'mongodb://127.0.0.1:27017'

const client = new MongoClient(url, {
    directConnection: true,
})

const dbName = 'test1'

async function main() {
    await client.connect()
    console.log('Connected successfully to server');
    const db = client.db(dbName)
    const collection = db.collection('users')
    const files = await collection.find({$or: [
        {
            other_id: {$in: []}
        },
        {
            sid: {$in: ['1']}
        }
    ]}).toArray()
    console.log(files)
    return 'done'
}

main()
.then(console.log)
.catch(console.error)
.finally(() => client.close())
```

## result 
```txt
➜  mongotest node test.js
Connected successfully to server
[
  {
    _id: new ObjectId("6279e8813b08b6dc35a384e9"),
    name: '1',
    sid: '1',
    uid: 1
  }
]
```

## mongoose query 
```js
const mongoose = require('mongoose')
async function main() {
    const uri = 'mongodb://127.0.0.1/test1';
    const db = mongoose.createConnection(uri, {
        directConnection: true
    });
    const Schema = mongoose.Schema;
    const mySchema = Schema({ name: String, sid: String, uid: Number });
    
    /* global db */
    const model = db.model('user', mySchema);
    const files = await model.find({$or: [
        {
            other_id: {$in: []}
        },
        {
            sid: {$in: ['1']}
        }
    ]})
    console.log(files)
}



main()
```

## result
```txt
[
  {
    _id: new ObjectId("6279e8813b08b6dc35a384e9"),
    name: '1',
    sid: '1',
    uid: 1
  },
  {
    _id: new ObjectId("6279e8813b08b6dc35a384ea"),
    name: '2',
    sid: '2',
    uid: 2
  },
  {
    _id: new ObjectId("6279e8813b08b6dc35a384eb"),
    name: '3',
    sid: '3',
    uid: 3
  }
]
```

is this a bug ?

**Comment by littleboyfury** [comment]
![image](https://user-images.githubusercontent.com/73931673/167560913-3d09f2a5-77f2-4b43-8368-f5a5cbcbdbe4.png)

**Comment by IslandRhythms** [comment]
You didn't state what version of mongoose you are on, so i assumend v 6.3.2

```javascript
const mongoose = require('mongoose')


const {MongoClient} = require('mongodb')

const url = 'mongodb://127.0.0.1:27017'

const client = new MongoClient(url, {
    directConnection: true,
})

const dbName = 'test1'

async function run() {
    await client.connect()
    console.log('Connected successfully to server');
    const db = client.db(dbName)
    const collection = db.collection('users')
    const files = await collection.find({$or: [
        {
            other_id: {$in: []}
        },
        {
            sid: {$in: ['1']}
        }
    ]}).toArray()
    console.log(files)
    return 'done'
}

run()
.then(console.log)
.catch(console.error)
.finally(() => client.close())




async function main() {
    const uri = 'mongodb://127.0.0.1/test1';
    const db = mongoose.connect(uri, {
        directConnection: true
    });
    const Schema = mongoose.Schema;
    const mySchema = Schema({ name: String, sid: String, uid: Number });
    
    /* global db */
    const model = mongoose.model('user', mySchema);
    const files = await model.find({$or: [
        {
            other_id: {$in: []}
        },
        {
            sid: {$in: ['1']}
        }
    ]})
    console.log(files)
}



main()
```

output:
```
Connected successfully to server
[]
done
[]
```

**Comment by IslandRhythms** [comment]
A simple example

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String,
    sid: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        name: 'Test',
        sid: '2'
    });

    console.log(await Test.find({undefined}))
    console.log(await Test.find({$or: [{sid: '1'}, {field: undefined}]}));
}

run();
```
So what you see happening is that when 'nothing' is passed to find, it returns all documents in the model. Therefore, when you pass in an empty array, even though it is attached to a field that does not exist, it treats that as nothing and therefore returns all documents because that is one of the or conditions.

From mongodb:
> The [$or](https://www.mongodb.com/docs/manual/reference/operator/query/or/#mongodb-query-op.-or) operator performs a logical OR operation on an array of two or more <expressions> and selects the documents that satisfy at least one of the <expressions>. The $or has the following syntax:

So because one expression is equivalent to passing 'nothing' as an argument, it returns all documents.
Does that make sense?
I believe this issue has been brought up before and the determination was it was expected behavior.

**Comment by littleboyfury** [comment]
> You didn't state what version of mongoose you are on, so i assumend v 6.3.2
> 
> ```js
> const mongoose = require('mongoose')
> 
> 
> const {MongoClient} = require('mongodb')
> 
> const url = 'mongodb://127.0.0.1:27017'
> 
> const client = new MongoClient(url, {
>     directConnection: true,
> })
> 
> const dbName = 'test1'
> 
> async function run() {
>     await client.connect()
>     console.log('Connected successfully to server');
>     const db = client.db(dbName)
>     const collection = db.collection('users')
>     const files = await collection.find({$or: [
>         {
>             other_id: {$in: []}
>         },
>         {
>             sid: {$in: ['1']}
>         }
>     ]}).toArray()
>     console.log(files)
>     return 'done'
> }
> 
> run()
> .then(console.log)
> .catch(console.error)
> .finally(() => client.close())
> 
> 
> 
> 
> async function main() {
>     const uri = 'mongodb://127.0.0.1/test1';
>     const db = mongoose.connect(uri, {
>         directConnection: true
>     });
>     const Schema = mongoose.Schema;
>     const mySchema = Schema({ name: String, sid: String, uid: Number });
>     
>     /* global db */
>     const model = mongoose.model('user', mySchema);
>     const files = await model.find({$or: [
>         {
>             other_id: {$in: []}
>         },
>         {
>             sid: {$in: ['1']}
>         }
>     ]})
>     console.log(files)
> }
> 
> 
> 
> main()
> ```
> 
> output:
> 
> ```
> Connected successfully to server
> []
> done
> []
> ```

mongoose version 6.3.3, mongodb  version 4.1.4 

should insert some data first and then you can get the result `db.users.insertMany([{name: '1', sid: '1', uid: 1},{name: '2',sid: '2',uid: 2}, {name: '3',sid: '3', uid: 3}])`

**Comment by littleboyfury** [comment]
> A simple example
> 
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>     name: String,
>     sid: String
> });
> 
> const Test = mongoose.model('Test', testSchema);
> 
> async function run() {
>     await mongoose.connect('mongodb://localhost:27017');
>     await mongoose.connection.dropDatabase();
> 
>     await Test.create({
>         name: 'Test',
>         sid: '2'
>     });
> 
>     console.log(await Test.find({undefined}))
>     console.log(await Test.find({$or: [{sid: '1'}, {field: undefined}]}));
> }
> 
> run();
> ```
> 
> So what you see happening is that when 'nothing' is passed to find, it returns all documents in the model. Therefore, when you pass in an empty array, even though it is attached to a field that does not exist, it treats that as nothing and therefore returns all documents because that is one of the or conditions.
> 
> From mongodb:
> 
> > The [$or](https://www.mongodb.com/docs/manual/reference/operator/query/or/#mongodb-query-op.-or) operator performs a logical OR operation on an array of two or more  and selects the documents that satisfy at least one of the . The $or has the following syntax:
> 
> So because one expression is equivalent to passing 'nothing' as an argument, it returns all documents. Does that make sense? I believe this issue has been brought up before and the determination was it was expected behavior.

I put the conditions
```js
{$or: [
        {
            other_id: {$in: []}
        },
        {
            sid: {$in: ['1']}
        }
    ]}
```

but mongoose converts the conditions to 
```
{$or: [
        {
        },
        {
            sid: {$in: ['1']}
        }
    ]}
```
So the first condition is always true, and this query processes all the values

**Comment by littleboyfury** [comment]
mongoose version 6.3.3, mongodb version 4.1.4

```js
const {MongoClient} = require('mongodb')
const mongoose = require('mongoose')

const url = 'mongodb://127.0.0.1:27017'

const client = new MongoClient(url, {
  directConnection: true,
})

const dbName = 'test1'

async function main() {
  await client.connect()
  const db = client.db(dbName)
  const collection = db.collection('users')
  await collection.deleteMany({})
  await collection.insertMany([{
    name: '1', sid: '1', uid: 1
  }, {
    name: '2', sid: '2', uid: 2
  }, {
    name: '3', sid: '3', uid: 3
  }])
  const files = await collection
    .find({
      $or: [
        {
          other_id: {$in: []}
        },
        {
          sid: {$in: ['1']}
        }
      ]
    }).toArray()
  console.log('mongodb')
  console.log(files)
  await client.close()
}


async function main1() {
  const uri = 'mongodb://127.0.0.1/test1';
  const db = mongoose.createConnection(uri, {
    directConnection: true
  });
  const Schema = mongoose.Schema;
  const mySchema = Schema({name: String, sid: String, uid: Number}, {
    versionKey: false,
  });

  /* global db */
  const model = db.model('user', mySchema);
  await model.deleteMany({})
  await model.insertMany([{
    name: '1', sid: '1', uid: 1
  }, {
    name: '2', sid: '2', uid: 2
  }, {
    name: '3', sid: '3', uid: 3
  }])
  const files = await model.find({
    $or: [
      {
        other_id: {$in: []}
      },
      {
        sid: {$in: ['1']}
      }
    ]
  })
  console.log('mongoose')
  console.log(files)
  await db.close()
}


main()
  .then(() => {
    main1()
  })
```
print result
```txt
mongodb
[
  {
    _id: new ObjectId("627b933d0a2c9a70389b197b"),
    name: '1',
    sid: '1',
    uid: 1
  }
]
mongoose
[
  {
    _id: new ObjectId("627b933d0a2c9a70389b1980"),
    name: '1',
    sid: '1',
    uid: 1
  },
  {
    _id: new ObjectId("627b933d0a2c9a70389b1981"),
    name: '2',
    sid: '2',
    uid: 2
  },
  {
    _id: new ObjectId("627b933d0a2c9a70389b1982"),
    name: '3',
    sid: '3',
    uid: 3
  }
]
```

**Comment by sean-daley** [comment]
I think both of these:
https://github.com/Automattic/mongoose/issues/10946
https://github.com/Automattic/mongoose/issues/10932

may describe the behavior you are seeing here. They include a work around as well which seems to work with your test provided at https://github.com/Automattic/mongoose/issues/11788#issuecomment-1123562882

The workaround being to add `mongoose.set('strictQuery', false);` to your code. Those linked issues have some discussions around this if you want more info. I tried it with your test though and get a result of:
```
mongodb
[
  {
    _id: new ObjectId("627ba4224e810c5121c997fa"),
    name: '1',
    sid: '1',
    uid: 1
  }
]
mongoose
[
  {
    _id: new ObjectId("627ba4224e810c5121c997ff"),
    name: '1',
    sid: '1',
    uid: 1
  }
]
```

And I think that matches what you're looking for?
