### ISSUE TITLE
Mongoose version error when using ncc to package the code

### ISSUE THREAD

**Issue by sirily11** [Automattic/mongoose#11791]
Hi. I am using ncc to package my node js app. However, I found that `mongoose.version` returns a wrong version in this case. And after doing further investigation,  I found that `mongoose.version` will return whatever version in my `packakge.json`  file. I think it is probably due to the following line of code.

https://github.com/Automattic/mongoose/blob/7515b810f823f838a8d45ab39c0329ad51b31d7c/lib/index.js#L25

and the version is used by reading the `package.json` file defined in the package folder. 
https://github.com/Automattic/mongoose/blob/7515b810f823f838a8d45ab39c0329ad51b31d7c/lib/index.js#L770

Is there any way to fix the incorrect version number?

**Comment by Uzlopak** [comment]
Is this kind of caching issue?

**Comment by vkarpov15** [comment]
Can you provide an example of how you're using ncc to package your app? We've never used ncc before, and https://www.npmjs.com/package/ncc doesn't look like something you use for bundling an app.

**Comment by sirily11** [comment]
> Can you provide an example of how you're using ncc to package your app? We've never used ncc before, and https://www.npmjs.com/package/ncc doesn't look like something you use for bundling an app.

Hi. The ncc I talked about is the one from vercel https://www.npmjs.com/package/@vercel/ncc. I might provide a simple working example later

**Comment by Uzlopak** [comment]
Ok, makes sense. If you bundle mongoose in a new package, then mongoose will load the version from the package.json of the bundled package and not from (the not existing) mongoose folder in node_modules. 

The only thing I can think of would be hardcoding the version into index.js of mongoose

**Comment by sirily11** [comment]
I think hard coded version would be a solution, otherwise, the version number from the library is not reliable.

**Comment by vkarpov15** [comment]
I'm unable to repro. If I compile the below script with ncc:

```
'use strict';

const mongoose = require('mongoose');

console.log(mongoose.version);
```

Here's what I get:

```
$ head -n 15 ./dist/index.js 
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ 2214:
/***/ ((__unused_webpack_module, exports, __nccwpck_require__) => {

"use strict";

Object.defineProperty(exports, "__esModule", ({ value: true }));
exports.Binary = void 0;
var buffer_1 = __nccwpck_require__(4300);
var ensure_buffer_1 = __nccwpck_require__(6669);
var uuid_utils_1 = __nccwpck_require__(3152);
var uuid_1 = __nccwpck_require__(2568);
var error_1 = __nccwpck_require__(240);
$ node ./dist/index.js
6.5.1
$ 
```

Please provide a standalone example that demonstrates the issue you're seeing.
