### ISSUE TITLE
Not throwing errors when schema validation fails

### ISSUE THREAD

**Issue by RemyMachado** [Automattic/mongoose#11799]
When I try to `findById()` against a wrong mongoose `Schema`, the function returns null without emitting any errors.

In my case I was using a `String` instead of `ObjectId`:
```typescript
_id: { type: String, required: true },
``` 
instead of
```typescript
_id: { type: ObjectId, required: true },
```
I kept getting null values.
The function should have raised the following error:
```
TypeError: Invalid schema configuration: `_id` schematype definition is invalid. See https://mongoosejs.com/docs/guide.html#definition for more info on supported schema syntaxes.
```
but instead it just returned `null` every single time.
This was a nightmare to debug.

**Comment by RemyMachado** [comment]
> Validation just makes sure that what you're inserting into the database is what you defined. In the case where you're doing a `findById()` operation, thats just a read operation so nothing is being inserted and therefore no validation is being triggered.

Thanks for the clarification, but why is it returning null if it doesn't check the schema?
As soon as I corrected the schema, I got my results.

**Comment by IslandRhythms** [comment]
I can't say more without seeing what you're doing. Do you have two models or one? How are you creating documents, what is your search query? etc.

**Comment by RemyMachado** [comment]
Thank you for your time @IslandRhythms , here's the code:

```typescript
export interface FooBarType extends Document {
    id: string
    foo: string
    bar: string
}

const fooBarSchema = new Schema<FooBarType>(
    {
        _id: { type: ObjectId, required: true }, // if I use `type: String`, the `findById` will always return null without throwing
        foo: { type: String, required: true },
        bar: { type: String, required: true },
    },
    {
        collection: 'fooBars',
    }
)

export const getFooBarModel = (db: Connection) =>
    db.model<FooBarType>('FooBar', fooBarSchema)
```

Note that the TS interface is using `id` instead of `_id` as I need it for my GraphQL typing.
I ended up removing the `_id` line in the schema.

Also I think I should use typegoose or prisma to handle a better typing. Here I have to define every schema/interface 2-3 times (interface, mongoose-schema, graphql-schema).

**Comment by IslandRhythms** [comment]
Can you write a script reproducing that null you're getting? I'm not quite sure how you're getting that.

**Comment by RemyMachado** [comment]
Yes, but I'm not sure of what you mean by "a script". Do you have a set up recommendation for what would be helpful to send you?

**Comment by IslandRhythms** [comment]
For example, modify this script to reproduce that null you're getting.

```typescript
import * as mongoose from 'mongoose';

export interface FooBarType extends Document {
    _id: string
    foo: string
    bar: string
}

const fooBarSchema = new mongoose.Schema<FooBarType>(
    {
        _id: { type: String, required: true },
        foo: { type: String, required: true },
        bar: { type: String, required: true },
    },
    {
        collection: 'fooBars',
    }
)

const Test = mongoose.model<FooBarType>('FooBar', fooBarSchema)

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const entry = await Test.create({
        _id: '123456789102',
        foo: 'Banana',
        bar: 'split'
    });
    console.log(entry);

    await Test.findById(entry._id);

}

run();
```

**Comment by RemyMachado** [comment]
I did a more accurate use case with the script and I couldn't reproduce the `null` behavior.

```typescript
export interface FooType extends mongoose.Document {
    _id: string
    barId: string
}

export interface BarType extends mongoose.Document {
    _id: string
    name: string
}

const fooSchema = new mongoose.Schema<FooType>(
    {
        _id: { type: String, required: true },
        barId: { type: String, required: true },
    },
    {
        collection: 'foos',
    }
)

const barSchema = new mongoose.Schema<BarType>(
    {
        _id: { type: String, required: true },
        name: { type: String, required: true },
    },
    {
        collection: 'bars',
    }
)

const Foo = mongoose.model<FooType>('Foo', fooSchema)
const Bar = mongoose.model<BarType>('Bar', barSchema)

async function run() {
    await mongoose.connect('mongodb://localhost:27017')
    await mongoose.connection.dropDatabase()

    await Bar.create({
        _id: '123456789103',
        name: 'bar',
    })

    const fooEntry = await Foo.create({
        _id: '123456789102',
        barId: '123456789103',
    })

    const resultFoo = await Foo.findById(fooEntry._id)
    console.log('resultFoo', resultFoo)

    const resultBar = await Bar.findById(resultFoo!.barId)
    console.log('resultBar', resultBar)
}
```

The original problem: with my code base it always succeeded to find the parent, but it always returned `null` for the children with `findById(parent.childrenId)` and as soon as I would change `type: String` into `type: ObjectId` it would succeed to find the children.

Note that in my database, inside the parent, the childrenId appears as a normal string, not an ObjectId.

Does this information makes you think of a theory?

**Comment by IslandRhythms** [comment]
How are you looking at the definitions in the database? Can you double check that it is in fact defined as a string and not an objectId. If you're changing it from string to objectId and it shows up that would imply that it is defined as an objectId in the database.

**Comment by vkarpov15** [comment]
I took a closer look, this is expected behavior, and not much we can really do about it. How should Mongoose infer that your `_id` should really be an ObjectId when you define it to be a string?
