### ISSUE TITLE
Extract Schema??

### ISSUE THREAD

**Issue by vixalien** [Automattic/mongoose#11797]
Is it possible to extract and isolate all `schema` related files (such as schematypes, types etc) to own files (or maybe module) because Mongoose has one of the best validation/schema thingy and it would be nice if it was isolated so as to be used independently of mongoose.

**Comment by vixalien** [comment]
people??

**Comment by vkarpov15** [comment]
Duplicate of #4282. This is something we'd like to do, but just haven't gotten around to yet.
