### ISSUE TITLE
No overload matches this call. Overload 1 of 3, 

### ISSUE THREAD

**Issue by sugandansa** [Automattic/mongoose#11792]
No overload matches this call. Overload 1 of 3, '(callback?: Callback<EnforceDocument<T, {}>[]> | undefined): Query<EnforceDocument<T, {}>[], EnforceDocument<T, {}>, {}, T>', gave the following error.

**Comment by Uzlopak** [comment]
Well a code snippet would help to investigate this further. Without code snippet it is not reproducable.

**Comment by sugandansa** [comment]
Property 'default' does not exist on type 'SchemaDefinitionProperty<boolean>'.
  Property 'default' does not exist on type 'false'

    if (condition) {
    
        this.isAdmin = true;
      
      } else {
        // Subsequent new users use the defaults
        this.isAdmin = model.schema.obj.isAdmin.default;

**Comment by IslandRhythms** [comment]
Please provide a script that demonstrates the issue mentioned in the first comment you made.
