### ISSUE TITLE
Custom update in mongoose

### ISSUE THREAD

**Issue by AryaAnish121** [Automattic/mongoose#11808]
I am trying to figure out how to update with a custom query. Let me explain:

I have a collection named `items`. When someone hits the user it will remove `10` from power of any item which has the `type: offence` and if the power after getting hit is less than `0` it will delete the item. I am currently thinking to use this code:

```js
Item.find({type: 'offence'}, (err, items) => {
    items.forEach(item => {
        if ((item.power - 10) >= 0) {
            Item.deleteOne({id : item .id});
        } else {
            Item.findOne({id: item.id}, (err, item) => {
                item.power -= 10;
                item.save();
            })
        }
    })
})
```

But I believe there is a better was to do it

**Comment by Uzlopak** [comment]
In your code snippet, you basically let node do the whole database operations, which is a violation of the layer separation You are doing database operations in the logic layer and not in the data layer.

There are so many alternatives which are much faster. 

E.g.
1. First use $inc with -10 to decrement the value of power. Then in a second operation delete all documents, where power is lower or equal 0. 
2. Decrement power with $inc -10 and check if power is lower or equal 10 change type to "deleted". Ignore documents with type "deleted" in your other queries., Periodically delete the documents with type deleted or delete them like in variant 1 immediatly after the update.

To implement the first, you could do:

Item.updateMany({type: 'offence'}, { $inc: {power: -10}})
Item.deleteMany({ type: 'offence', {power: {$lte: 0}})

To make it an atomar operation, you could use a mongo session.
