### ISSUE TITLE
JavaScript heap out of memory on version 6.3.4

### ISSUE THREAD

**Issue by the-nance** [Automattic/mongoose#11823]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I keep getting `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` when i use `findOneAndUpdate`

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my settings schema:
```
{
  id: String,
  registered_at: {
    type: Number,
    default: Date.now()
  },
  registered_by: Number,
  action: String,
  min_ag: {
    type: Number,
    default: 259200000
  },
  unv_r: Number,
  log_c: Number,
  men_r: Number,
  ver_r: Number,
  mod_r: Number
}
```
upon executing the following query, it runs out of memory
```
settingsSchema.findOneAndUpdate({
    id: "410488579140354049"
}, data, {
    new: true,
    upsert: true
})
```
**What is the expected behavior?**
Upon executing that, the process should be complete and it should be saved.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: v6.3.4
mongoDB: v4.6.0
node: v16.13.2

**Comment by Nance-the-First** [comment]
I came across a similar issue that occured about a year ago https://github.com/Automattic/mongoose/issues/9864

**Comment by Uzlopak** [comment]
We need a mcve to investigate further.

**Comment by AbdelrahmanHafez** [comment]
For more info on what we mean by that: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by IslandRhythms** [comment]
modify the script to demonstrate your issue
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    id: String,
  registered_at: {
    type: Number,
    default: Date.now()
  },
  registered_by: Number,
  action: String,
  min_ag: {
    type: Number,
    default: 259200000
  },
  unv_r: Number,
  log_c: Number,
  men_r: Number,
  ver_r: Number,
  mod_r: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        id: '410488579140354049',
        registered_by: 12345,
        action: 'Action',
        unv_r: 1,
        log_c: 2,
        men_r: 3,
        ver_r: 4,
        mod_r: 5
    });

    let data = {unv_r: 10, log_c: 11, men_r: 12, ver_r: 13, mod_r: 14}

    await Test.findOneAndUpdate({ id: "410488579140354049"}, data, {new: true, upsert: true} );
    console.log('done');
}

run();
```
