### ISSUE TITLE
Not able to validate a field after it has been saved without validation

### ISSUE THREAD

**Issue by Tom5om** [Automattic/mongoose#11835]
I have a situation where I create a document, and set validateSave to false ( so that a user can create a draft of said document )
This means that unvalidated data can be saved in the database.

I then later on want to force validation on a specific path inside the document to trigger any validation errors.

This currently does not seem possible

I have tried using 

const validationErrors = model.validateSync(propertyName, {validateModifiedOnly: false});

But I can't seem to trigger any kind of validation for this situation

**Comment by Uzlopak** [comment]
I personally think this is a bad way to do it. Once you stored invalid data you can not trust the database anymore. You should imho have always a trustable state of your database.

 I personally would create a Schema of the expected Document and write a method which sets all fields to required false. Or the other way round.
Then create a model for draft-Schema and a model for the final-Schema, targetting the same collection. 

Then you create drafts, which are partial but validated data. Then when finalizing the draft using the other model and have the complete document validated.

**Comment by Tom5om** [comment]
> Then you create drafts, which are partial but validated data
In our case we need to store incomplete drafts that are unvalidated data as we don't want our users to lose their progress.

I am trying to think about the idea of a draft model vs a complete model. Wouldn't this still have the same problem of having data in a field and therefore it not being validated on save?

**Comment by Tom5om** [comment]
I am devising a way to mark the fields as edited now on save so that it will run the validation function correctly on save.

All I really want is to be able to force a validation on either an entire document or a subset

**Comment by vkarpov15** [comment]
I'd advise doing [`Model.validate(doc, ['path'])`](https://mongoosejs.com/docs/api/model.html#model_Model-validate). For example:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => {
  console.error(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const schema = mongoose.Schema({
    name: String,
    age: { type: Number, validate: v => v < 100 }
  });
  const Test = mongoose.model('Test', schema);

  const doc = new Test({ name: 'test', age: 1000 });
  await doc.save({ validateBeforeSave: false });

  console.log('Saved', doc.toObject());

  // Throws "Validation failed: age: Validator failed for path `age` with value `1000`"
  await Test.validate(doc.toObject(), ['age']);

  // Never runs
  console.log('Done');
}
```

I don't believe we'll be able to add support for this in regular old `doc.validate()`. `validate()` is too closely tied to change tracking and there's a few too many options for `validate()` that potentially conflict with this functionality. We will consider adding support to run regular document `validate()` on specified paths rather than modified paths, but it isn't as high of a priority now that we have `Model.validate()`.
