### ISSUE TITLE
Trigger middleware with bulkWrite

### ISSUE THREAD

**Issue by samevision** [Automattic/mongoose#11833]
Hello guys,

I need to update (upsert: true) a lot of documents wherefore I use bulkWrite instead findOneAndUpdate. This accelerates the updating process by a lot. Unfortunately I noticed that bulkWrite doesn't trigger middleware functions.

Is is possible anyhow to use middleware with bulkWrite? This would be really helpful for me.

Best

**Comment by deistermatheus** [comment]
@samevision  Can you post a short code snippet of the query you're trying to perform? What happens with findOneAndUpdate that you'd like to happen on bulkWrite also?

**Comment by Uzlopak** [comment]
Actually why not activating middlewares for all relevant operations?

**Comment by vkarpov15** [comment]
`bulkWrite()` does trigger middleware. You just have to do `pre('bulkWrite')` and `post('bulkWrite')`.
