### ISSUE TITLE
$sort is missing in PipelineStage that includes $facet

### ISSUE THREAD

**Issue by jamesholcomb** [Automattic/mongoose#11840]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

A pipeline stage with $facet that includes a $sort generates a TypeScript error.

Argument of type '({ $match: { x: number; }; $facet?: undefined; } | { $facet: { data: { $sort: { _id: number; x: number; }; }[]; }; $match?: undefined; })[]' is not assignable to parameter of type 'PipelineStage[]'.
  Type '{ $match: { x: number; }; $facet?: undefined; } | { $facet: { data: { $sort: { _id: number; x: number; }; }[]; }; $match?: undefined; }' is not assignable to type 'PipelineStage'.
    Type '{ $facet: { data: { $sort: { _id: number; x: number; }; }[]; }; $match?: undefined; }' is not assignable to type 'PipelineStage'.
      Type '{ $facet: { data: { $sort: { _id: number; x: number; }; }[]; }; $match?: undefined; }' is not assignable to type 'Match'.
        Property '$match' is optional in type '{ $facet: { data: { $sort: { _id: number; x: number; }; }[]; }; $match?: undefined; }' but required in type 'Match'.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
import mongoose from "mongoose"

const schema = new mongoose.Schema({
  x: {
    type: Number
  }
})

const Foo = mongoose.model("Foo", schema)

const pipeline = [
  {
    $match: {
      x: 1
    }
  }, {
    $facet: {
      data: [{
        $sort: {
          _id: 1,
          x: 1
        }}
      ]
    }
  }
]

Foo.aggregate(pipeline)
```

**What is the expected behavior?**
no typescript error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
14.17.3
6.3.4
4.4.10

**Comment by Uzlopak** [comment]
I can not reproduce this.

**Comment by Uzlopak** [comment]
Aha, got it.

**Comment by Uzlopak** [comment]
This happens because typescript can not determine the right typings based on the shape of the pipeline variable. It tries to infer the type of pipeline and thinks, that Objects of your not typed pipeline variable should contain a $facet and or a $match attribute. 

You should type pipeline variable with `const pipeline: PipelineStage[] = ` or directly pass the value directly into .aggregate like

```javascript
Foo.aggregate([
  {
    $match: {
      x: 1
    }
  }, {
    $facet: {
      data: [{
        $sort: {
          _id: 1,
          x: 1
        }}
      ]
    }
  }
]) 
```

We can not fix this as this is an issue of typescript per se.
