### ISSUE TITLE
[Types] Since mongoose 6.3.2 `SchemaTypeOptions` is not useable anymore aside from in types

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11847]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

>6.3.2

### Node.js version

*

### MongoDB server version

*

### Description

Since mongoose 6.3.2 (to be more specific since #11695) `SchemaTypeOptions` was changed from `class` to `interface`, which makes it invalid to be used in something like `instanceof`.

To be more specific i use this functionality for typegoose to match where options have to go, which uses `instanceof` to determine if it has options to map.

Typescript Error:
> error TS2339: Property 'SchemaTypeOptions' does not exist on type 'typeof import("mongoose")'.

### Steps to Reproduce

(have typescript 4.4 or higher and try with mongoose 6.3.1 and 6.3.2 (or higher)
```ts
if (mongoose.Schema.Types.Subdocument.prototype.OptionsConstructor instanceof mongoose.SchemaTypeOptions) {
  console.log("is instance of");
} else {
  console.log("is not instance of");
}
```

### Expected Behavior

No Types error

**Comment by Uzlopak** [comment]
But SchemaTypeOptions is not a class/function-constructor?!

**Comment by hasezoey** [comment]
> But SchemaTypeOptions is not a class/function-constructor?!

are you sure? https://github.com/Automattic/mongoose/blob/eaa445e0ad3f1d9c90bde021b0c04e0315c66a57/lib/options/SchemaTypeOptions.js#L17

**Comment by Uzlopak** [comment]
Ok, i am on it :)

**Comment by hasezoey** [comment]
@Uzlopak it seems like this change was not mentioned in the release notes / changelog.

https://github.com/Automattic/mongoose/blob/6.3.5/CHANGELOG.md#635--2022-05-30
https://github.com/Automattic/mongoose/releases/tag/6.3.5

**Comment by Uzlopak** [comment]
There is also some loss of changes when e g. @vkarpov15 directly commits into master. I thought as far as i create PRs it would keep track of the changges. Idk why it is missing.

**Comment by vkarpov15** [comment]
@Uzlopak can you please add completed issues to milestones? That's how I keep track of what goes in to a given release.

**Comment by Uzlopak** [comment]
@vkarpov15 
Do you manually write the changelog? In my projects i autogenerate them from the pullrequests, and write the releasenotes per github action.

**Comment by vkarpov15** [comment]
@Uzlopak yes I manually write the changelog. 2 reasons: 1) so I can put more noteworthy changes first, 2) so I can patch up commit messages that don't line up with our commit conventions. While #11860 is an option, I prefer to not put the onus on contributors to follow our commit guidelines, because I know I hate it when I'm trying to put in a quick one-line fix to a project and then I get blasted with requests to sign a CLA and change my commit messages and a dozen other things.
