### ISSUE TITLE
Mongoose Typescript Array updates

### ISSUE THREAD

**Issue by apidev234** [Automattic/mongoose#11845]
**Do you want to request a *feature* or report a *bug*?**
- No

**What is the current behavior?**
- Array isn't being updated

**If the current behavior is a bug, please provide the steps to reproduce.**
- I have a model 'Zappers':
```ts
import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
dotenv.config();
import { env } from 'process';
export interface Image {
  url: string;
  durl: string;
  topic: string;
  name: string;
  id: string;
}

interface ZappersInterface {
  images: Image[];
}

const ZappersSchema = new mongoose.Schema<ZappersInterface>();

export const Zappers = mongoose.model<ZappersInterface>(
  'Zappers',
  ZappersSchema,
);

export async function ConnectToDatabase() {
  await mongoose.connect(env.MONGODB_URL as string).then(() => {
    console.log('Connected to DB');
  });
}
```
```ts
async newImage(imgurl: string, durl: string, topic: string, name: string) {
    await Zappers.findByIdAndUpdate('61d056e8f2e37d1d68a49c17', {
      $push: {
        images: {
          url: imgurl,
          durl: durl,
          topic: topic,
          name: name,
          id: uuid.v4(),
        },
      },
    });
    return true;
  }
  ```
  And, I'm trying to push an object to the images array, But it doesn't push the object... The connection is there everything works fine.

**What is the expected behavior?**
- Array should be updated.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 16.13.0
Mongoose - 6.3.4

**Comment by Uzlopak** [comment]
Your schema is basically empty.

**Comment by apidev234** [comment]
Does that really matter?

**Comment by apidev234** [comment]
Alright Then, I'll try fixing it.. Thanks.
