### ISSUE TITLE
why are mongod to nodejs connections bidirectional, doubling the amount of connections in total?

### ISSUE THREAD

**Issue by martianmartian** [Automattic/mongoose#11859]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.2.2

### Node.js version

v17.3.1

### MongoDB version

v4.4.7

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu 18

### Issue

i'm connecting to mongodb through mongoose, from nodejs server, using this line:

        mongoose.createConnection(`${uri}`,{dbName:"user",server: {poolSize : 1}});
        mongoose.createConnection(`${uri}`,{dbName:"db2",server: {poolSize : 1}});

curiously when i inspect TCP connection in linux terminal, using `lsof -i tcp:27017` , i found that for each connection between nodejs and mongodb server, there are TWO(???) TCP connections, which doubles the amount of connections needed.

I have the screenshot here. 

```
    COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
    mongod      779 root    5u  IPv4 1078325      0t0  TCP localhost:27017->localhost:42688 (ESTABLISHED)
    mongod      779 root   11u  IPv4   19794      0t0  TCP localhost:27017 (LISTEN)
    mongod      779 root   46u  IPv4 1078335      0t0  TCP localhost:27017->localhost:42692 (ESTABLISHED)
    mongod      779 root   48u  IPv4 1077657      0t0  TCP localhost:27017->localhost:42698 (ESTABLISHED)
    mongod      779 root   72u  IPv4 1042013      0t0  TCP localhost:27017->localhost:41086 (ESTABLISHED)
    mongod      779 root   74u  IPv4 1042015      0t0  TCP localhost:27017->localhost:41088 (ESTABLISHED)
    mongod      779 root  129u  IPv4  721690      0t0  TCP localhost:27017->localhost:53000 (ESTABLISHED)
    mongod      779 root  133u  IPv4  721692      0t0  TCP localhost:27017->localhost:53002 (ESTABLISHED)
    mongod      779 root  142u  IPv4  758478      0t0  TCP localhost:27017->localhost:55034 (ESTABLISHED)
    mongod      779 root  144u  IPv4  758483      0t0  TCP localhost:27017->localhost:55038 (ESTABLISHED)
    sshd      12453 root    8u  IPv4  722486      0t0  TCP localhost:53000->localhost:27017 (ESTABLISHED)
    sshd      12453 root    9u  IPv4  722488      0t0  TCP localhost:53002->localhost:27017 (ESTABLISHED)
    sshd      12453 root   10u  IPv4 1041239      0t0  TCP localhost:41086->localhost:27017 (ESTABLISHED)
    sshd      12453 root   11u  IPv4 1041240      0t0  TCP localhost:41088->localhost:27017 (ESTABLISHED)
    sshd      12453 root   12u  IPv4  759420      0t0  TCP localhost:55034->localhost:27017 (ESTABLISHED)
    sshd      12453 root   13u  IPv4  759431      0t0  TCP localhost:55038->localhost:27017 (ESTABLISHED)
    node\x20/ 16446 root   20u  IPv4 1077542      0t0  TCP localhost:42692->localhost:27017 (ESTABLISHED)
    node\x20/ 16446 root   21u  IPv4 1077536      0t0  TCP localhost:42688->localhost:27017 (ESTABLISHED)
    node\x20/ 16446 root   23u  IPv4 1078433      0t0  TCP localhost:42698->localhost:27017 (ESTABLISHED)

```
notice that TCP connections are port [42692, 42688, 42698] are counted twice. 

i also have a few connections made through `sshd`, and clearly they are single connections, just for reference purposes. 

i have a limited amount of con-current connections quota, so the question is, what's wrong here? is it possible to get rid of the doubled connections?

**Comment by Uzlopak** [comment]
You create two connections.

**Comment by deistermatheus** [comment]
I think you are effectively listing twice because both processes live on the same. The amount of connections that would be relevant to your server are those owned by mongod, which is the database process.

**Comment by vkarpov15** [comment]
@deistermatheus is right, notice how the "command" column lists "mongod" for one of the 42692 connections and "node" for the other.
