### ISSUE TITLE
How to declare an array of different types in a Mongoose schema?

### ISSUE THREAD

**Issue by javierguzman** [Automattic/mongoose#11864]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^6.3.2

### Node.js version

13.16

### MongoDB version

4

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Issue

Hello all,

I have been searching for quite a while about how to create an array field where every item could have a different type. I have seen possible solutions like creating my custom type or using "Mixed" with a validator function. However, what I am trying to specify is not strange at all and these solutions seem to be convoluted for something it should be simpler. I believe this type can be specified without problem on Open API spec or JSON schema. Is there a way to achieve this on Mongoose?

An example of an object following what I mentioned would be:
```
myArrayObject: [
 { type: 'type1', type1Property: 'blabla', type1Property2: 'blabla'},
 { type: 'type2', type2Property2: 'blablo' }
]
```

Ideally I wish I could do something like in the schema:

```
myArrayField: [ SchemaType1, SchemaType2]
```
So items can follow SchemaType1 OR SchemaType2.

Thank you in advance and regards

**Comment by vkarpov15** [comment]
Discriminators: https://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html

**Comment by javierguzman** [comment]
I tried them without any success. I ended up using Mixed type with a validator

**Comment by xegulon** [comment]
I also had the same problem as you @javierguzman

**Comment by xegulon** [comment]
@wvl is it possible to implement this feature in mongoose
JSON Schema enables this kind of stuff: https://stackoverflow.com/a/15673308/11348232
