### ISSUE TITLE
Make `strictQuery` `false` by default again

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#11861]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.x

### Node.js version

Any

### MongoDB server version

Any

### Description

The `strictQuery` change in Mongoose 6 (https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict) has caused a lot of confusion. Here's a couple:

https://github.com/Automattic/mongoose/issues/11609
https://github.com/Automattic/mongoose/issues/11807
https://github.com/Automattic/mongoose/issues/11514

Etc.

### Steps to Reproduce

From #11609: 

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    title: [{
        value: String,
        language: String
    }]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        title: [{
            value: 'El Dave valencia',
            language: 'ca'
        }, {
            value: 'El Dave castellano',
            language: 'es'
        }]
    });

    await Test.create({
        title: [{
            value: 'test',
            language: 'ca'
        }, {
            value: 'test',
            language: 'es'
        }]
    });

    const query = await Test.find({$or: [{"title.value":/Dave/i},{"name.value":/Dave/i} ]});
    console.log('done', query, query[0].title, query[1].title);
    
}

run();
```

### Expected Behavior

Make `strictQuery` false by default in Mongoose 7

**Comment by hasezoey** [comment]
as mentioned in https://github.com/Automattic/mongoose/issues/12389#issuecomment-1252553337, what about setting it to `throw` (or return some kind of validation errors) instead of reverting to `false` instead of the current "silently remove things" or going back to include "as is"?

**Comment by vkarpov15** [comment]
@hasezoey 'strictQuery: throw' by default would be a bit too strict to be a default for Mongoose. Wouldn't fit in well with the rest of our defaults.

**Comment by vkarpov15** [comment]
We should also decouple `strict` and `strictQuery` again. Setting `strictQuery` to `strict` by default was a workaround, setting `strict: false` in your schema shouldn't disable `strictQuery`.

**Comment by ilovepixelart** [comment]
@vkarpov15 Glad it will be over soon, can't wait for mongoose 7

**Comment by BsLeeha** [comment]
why not merge on v6.x? moving to v7.x takes more problem. @vkarpov15

**Comment by hasezoey** [comment]
this is a breaking change and so could only be done on a major version change, if you want to disable it globally for 6.x you can use `mongoose.set('strictQuery', false)` before using any query (like before / after creating the connection)
