### ISSUE TITLE
Simple query taking more than 10 seconds to complete

### ISSUE THREAD

**Issue by wholelott4** [Automattic/mongoose#11865]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

6.3.4

### Slowed down in version

6.3.4

### Node.js version

v16.14.2

### 🦥 Performance issue

I have a collection with 21.000 documents and Im running a query that is taking more than 10 seconds to return about 1.400 documents.

My schema is very simple:
`const Sale = new mongoose.Schema({
    seller: {
        type: String,
        required: true,
    },
    comment: {
        type: String,
        required: true,
    },
    transaction: {
        type: Object
    },
    createdAt: {
        type: String,
        required: true,
    }
})`

my query is:
`const sales = await OpenSale.find({contract, "createdAt": {$gte: finalUnix}}).lean().exec();`

I don't know what is happening, it can't take so long. The transaction object stored is little information, nothing weight.
My application is probably running simultaneously queries on the same collection (because I have scripts running 24/7 collecting and storing data). I dont know if this could be the issue.

### Steps to Reproduce

I just run the query and it take from 10 to 15 seconds to return 1.400 documents. 

### Expected Behavior

Faster results.

**Comment by Uzlopak** [comment]
What happens if you run the same query in mongo compass/studio 3T/robo 3T?

Did you set good indizes?

**Comment by Uzlopak** [comment]
Changing from performance to help/help wanted as it is not shown, that it is a kind of a performance issue specific to mongoose.

**Comment by wholelott4** [comment]
> Changing from performance to help/help wanted as it is not shown, that it is a kind of a performance issue specific to mongoose.

In mongo compass, the query is taking about 3 seconds. Im going to create an index on the createdAt to see if it solves.

**Comment by wholelott4** [comment]
> I think there could be also the overhead of bson deserialization of those 1400 documents having a perf impact. To reduce this you should consider if you can use an aggregation instead of a query.

How should the aggregation be? I have tried using aggregation with $match and $project, but it was the same.
By the way, I created more indexes and now the result it faster, it now takes about 3 seconds to retrieve. But 3 seconds to retrieve 1k documents in a collection of 21k is much time, is not?

What if my collection has more than 1 million documents?

**Comment by vkarpov15** [comment]
"I don't know what is happening, it can't take so long. The transaction object stored is little information, nothing weight.
My application is probably running simultaneously queries on the same collection (because I have scripts running 24/7 collecting and storing data). I dont know if this could be the issue." - Potential issue here. See: https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs

Also, what indexes did you add? Did you add a compound index on `{ contract, time }` or something else?

**Comment by fzn0x** [comment]
+1 Same with me

```js
  AxieBot.find({
    createdAt: {
      $gte: date,
      $lte: date,
    },
  })
    .lean()
    .then((value) => {
      console.log(value[0].createdAt);
      console.log(value[value.length - 1].createdAt);
    });
```

Takes 1 century to resolve, I even already using compound indexes on my collection.

**Comment by Uzlopak** [comment]
Well, there are so many reasons. You have x-Amount of documents. `find()` results in creating a big Array in memory. Every Document has to be deserialized by the slow bson deserializer. Also every document is loaded completely, as you dont specifiy fields/projection. And that is what is effected by mongoose. There can be stuff happening in Mongo, which is slowing down the connection. Or your connection pool is already processing other operations or you are doing auto population and that also results in clogging the connection.
