### ISSUE TITLE
Add Option `refPath` to `mongoose.SchemaTypeOptions`

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11862]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have just noticed that the type for `mongoose.SchemaTypeOptions` does not include the option `refPath`.

**Comment by Uzlopak** [comment]
The class itself does not have refPath attribute.

**Comment by hasezoey** [comment]
> The class itself does not have refPath attribute.

i didnt look into the class itself before opening this issue, so i will change the title to match the "new state"

**Comment by Uzlopak** [comment]
@vkarpov15 
Is this correct patch? I just want to remind you that SchemaTypeOptions is a class. So we can actually also instantiate it on the fly theoretically. You just patched the typings but not the actual class. Will this work?

**Comment by Uzlopak** [comment]
Reopening to keep track of it.

**Comment by vkarpov15** [comment]
@Uzlopak yes it'll work. The property definitions in `SchemaTypeOptions` are just for documentation and readability, but thanks for the reminder. I'll add `refPath` there too.
