### ISSUE TITLE
insertMany - lean: false returns hydrated documents

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11887]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.4

### Node.js version

16

### MongoDB server version

5.0.3

### Description

While working on the autotyping PR I realized, that lean: true does still return hydrated documents. 

### Steps to Reproduce

```javascript
    it('insertMany should not return hydrated Documents if lean is set to true', async function() {
      const eventSchema = new Schema({
        _id: Number,
        title: String,
      });
      const EventModel = db.model('Test', eventSchema);
      const test = await EventModel.insertMany(
        [{ _id: 3, title: 'Event 2' }],
        { lean: true}
      );

      assert.equal(typeof test[0].isNew, 'undefined')
    });
```

### Expected Behavior

Should return lean documents

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    _id: Number,
    title: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const entries = await Test.insertMany([{_id: 3, title: 'Event 2'}], {lean:true});

    console.log(entries[0].isNew)

}

run();
```

**Comment by Uzlopak** [comment]
@IslandRhythms 

`console.log(entries[0].isNew)` outputs `false` which means, that the field isNew exists on the document. 
You could even do `console.log(Object.keys(entries[0]))`, which results in `[ '$__', '$isNew', '_doc', '$errors' ]`. So it is definitely a hydrated Document.

**Comment by IslandRhythms** [comment]
My mistake, I misunderstood the issue

**Comment by vkarpov15** [comment]
Going to close this per discussion on #11890
