### ISSUE TITLE
Minor spelling errors

### ISSUE THREAD

**Issue by dforsi** [Automattic/mongoose#11895]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

master

### Node.js version

n/a

### MongoDB server version

n/a

### Description

There are some minor spelling errors that can be easily fixed (especially s/DCHP/DHCP/ would be a nice fix).

### Steps to Reproduce

Execute the following command:
```
$ codespell --ignore-words-list=te,tha,tolen ./mongoose.c ./docs/README.md ./src/mip.c
./mongoose.c:2350: DCHP ==> DHCP
./docs/README.md:241: enconding ==> encoding
./docs/README.md:691: suport ==> support
./docs/README.md:2291: sting ==> string
./src/mip.c:38: DCHP ==> DHCP
```

### Expected Behavior

The `codespell` tool should not suggest any correction in those files (it does suggest many corrections in `examples` and in `test/` but many of those are false positives).

**Comment by Uzlopak** [comment]
Hi, 

you are in the wrong project. This is mongoose, a MongoDB ORM written in javascript. I assume you wanted to created the issue in https://github.com/cesanta/mongoose

Closing this issue :).
