### ISSUE TITLE
error: Unable to read from a snapshot due to pending collection catalog changes

### ISSUE THREAD

**Issue by tanvirrb** [Automattic/mongoose#11896]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.12.14

### Node.js version

14.17

### MongoDB version

4.4

### Operating system

Linux

### Issue

I'm getting this error message randomly. I tried but couldn't get any idea why it's popping up from time to time. Does anyone have the same issue?

`error: Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1654362137, 16). Collection minimum is Timestamp(1654362137, 18) {"$clusterTime":{"clusterTime":"7105431274155671571","signature":{"hash":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyId":0}},"code":246,"codeName":"SnapshotUnavailable","name":"MongoError","ok":0,"operationTime":"7105431274155671571","stack":"MongoError: Unable to read from a snapshot due to pending collection catalog changes; please retry the operation. Snapshot timestamp is Timestamp(1654362137, 16). Collection minimum is Timestamp(1654362137, 18)\n    at MessageStream.messageHandler (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:299:20)\n    at MessageStream.emit (events.js:400:28)\n    at MessageStream.emit (domain.js:470:12)\n    at processIncomingData (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n    at MessageStream._write (/usr/src/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:726:22)\n    at Socket.emit (events.js:400:28)\n    at Socket.emit (domain.js:470:12)\n    at addChunk (internal/streams/readable.js:290:12)\n    at readableAddChunk (internal/streams/readable.js:265:9)\n    at Socket.Readable.push (internal/streams/readable.js:204:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"}`

**Comment by Uzlopak** [comment]
Catalog changes are running operations on the collection which modify the collection. E.g. creation of indizes. So while those operations are not done, you can not do aggregations etc.. You have to wait till the operation is done.

**Comment by vkarpov15** [comment]
Hard to tell without taking a look at what your app is doing, but this SO might help: https://stackoverflow.com/questions/60723800/mongodb-transactions-unable-to-read-from-a-snapshot
