### ISSUE TITLE
schema._clone is not a function

### ISSUE THREAD

**Issue by taitasu555** [Automattic/mongoose#11905]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.1.8

### Node.js version

16.12

### MongoDB server version

4.4

### Description

I installed mongoose 6.1.8 and TypeError: schema._clone is not a function shown.
I downgraded mongoose v5 and it worked fine but I want to use v6 .
Please teach me how to solve this bug

### Steps to Reproduce

```
TypeError: schema._clone is not a function
at NativeConnection.Connection.model (/Users/webApp/node_modules/mongoose/lib/connection.js:1093:23)
```

**Comment by IslandRhythms** [comment]
We need the code you are running that is creating this error.
