### ISSUE TITLE
How to populate and use populated fields at root?

### ISSUE THREAD

**Issue by Judahh** [Automattic/mongoose#11901]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.5

### Node.js version

v17.6.0

### MongoDB version

4.6.0

### Issue

```
const companySchema = Schema({
  _id: Schema.Types.ObjectId,
  name: String,
  type: Schema.Types.Number,
});

const companyStandpointSchema = Schema({
  _id: Schema.Types.ObjectId,
  from: { type: Schema.Types.ObjectId, ref: 'Person' },
  to: { type: Schema.Types.ObjectId, ref: 'Company' },
  preference: Schema.Types.Number, 
});

companyStandpointSchema.
  find().
  populate({ path: 'to', model: 'Company' })
```

If I populate like this I will receive something like:
```
[{
  "to": {
	  "_id": "629942f3846f9599f66c2b37",
	  "name": "Pão de Açúcar",
	  "type":2
  },
  "preference": 5,
  "_id": "6299446eee0be364bdb45ef6"
}]
```

But I want something like:
```
[{
  "_id": "629942f3846f9599f66c2b37",
  "name": "Pão de Açúcar",
  "type":2
  "preference": 5,
}]
```
How to accomplish that?

**Comment by AbdelrahmanHafez** [comment]
You can use [Document#depopulate](https://mongoosejs.com/docs/api/document.html#document_Document-depopulate) to achieve that.

```js
const documents = await CompanyStandPoint.find().populate('to');
const name = documents[0].to.name; // Pão de Açúcar
documents.forEach(document => document.depopulate('to'));
documents[0].to // "629942f3846f9599f66c2b37"
```

Does this solve the problem you're facing?

**Comment by deistermatheus** [comment]
I don't know of a way to do that with a populate query, but you can use aggregation operators.


```js
const pipeline = [
  // populate the "to" field with a lookup
  {
    '$lookup': {
      'from': 'companies', 
      'localField': 'to', 
      'foreignField': '_id', 
      'as': 'to' 
    }
  }, {
     // lookup by definition returns an array, unwinding when your relation is one to one should yield the populated doc as a field
    '$unwind': {
      'path': '$to', 
      'preserveNullAndEmptyArrays': true
    }
  }, {
   // replace your document's root with the "populated" field merged to the document root
    '$replaceRoot': {
      'newRoot': {
        '$mergeObjects': [
          '$$ROOT', '$$ROOT.to'
        ]
      }
    }
  }
]
```

```js
  const documents = await CompanyStandPoint.aggregate(pipeline)
 ```

**Comment by Judahh** [comment]
> You can use [Document#depopulate](https://mongoosejs.com/docs/api/document.html#document_Document-depopulate) to achieve that.
> 
> ```js
> const document = await CompanyStandPoint.findOne().populate('to');
> const name = document.to.name; // Pão de Açúcar
> document.depopulate('to');
> document.to // "629942f3846f9599f66c2b37"
> ```
> 
> Does this solve the problem you're facing?

Nope

**Comment by Judahh** [comment]
> I don't know of a way to do that with a populate query, but you can use aggregation operators.
> 
> ```js
> const pipeline = [
>   // populate the "to" field with a lookup
>   {
>     '$lookup': {
>       'from': 'companies', 
>       'localField': 'to', 
>       'foreignField': '_id', 
>       'as': 'to' 
>     }
>   }, {
>      // lookup by definition returns an array, unwinding when your relation is one to one should yield the populated doc as a field
>     '$unwind': {
>       'path': '$to', 
>       'preserveNullAndEmptyArrays': true
>     }
>   }, {
>    // replace your document's root with the "populated" field merged to the document root
>     '$replaceRoot': {
>       'newRoot': {
>         '$mergeObjects': [
>           '$$ROOT', '$$ROOT.to'
>         ]
>       }
>     }
>   }
> ]
> ```
> 
> ```js
>   const documents = await CompanyStandPoint.aggregate(pipeline)
> ```

I think this is the way, thanks!
