### ISSUE TITLE
LeanDocument, the third...

### ISSUE THREAD

**Issue by Uzlopak** [Automattic/mongoose#11910]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@mohammad0-0ahmad 
@taxilian 
@vkarpov15 
@AbdelrahmanHafez 

Tbh, I really dislike the current state of LeanDocument typings. In my opinion, the automatic infer schema PR was the right starting point. 

The shape of the Lean and Hydrated Documents is defined by the Schema. Also the options of a Schema change the shape of the LeanDocument. You store a __v field in the document if you use versioning. And if you use a different fieldname for versioning than this effects also the actual shape of the Document. So omitting fields like this is imho just plain wrong:

https://github.com/Automattic/mongoose/blob/c714d52236fe8ea8531c2ca4b2f10ae11f625080/types/index.d.ts#L552

I think we have to write first all the unit tests for the typings and agree what we actually expect. I think this is something I would start as next.

**Comment by vkarpov15** [comment]
LeanDocument is gone as of 7.x
