### ISSUE TITLE
can I do $inc while using .save?

### ISSUE THREAD

**Issue by TubbyStubby** [Automattic/mongoose#11915]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.6

### Node.js version

14.19.1

### MongoDB version

4.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I have a operation where an object is pushed into an array and a counter is increased.
```javascript
let foo = await Foo.findOne({ <some-filter> });
foo.bars.push({ bar: 2 });
foo.bar_count++;
await foo.save();
```
when I check the query being executed in debug mode, I see it is doing $push on array but $set on the count. In my use case I want to use $inc due to some concurrency issues. I searched and found `.$inc()` but that seems to be deprecated.
Is there any way by which I can tell `save` how to make the query? or maybe change the query which will be executed?

**Comment by vkarpov15** [comment]
Not currently. You would have to run an `updateOne()` manually.

We'll add the ability to do this in a future release.
