### ISSUE TITLE
docs: fix "reconnectTries is not supported" error

### ISSUE THREAD

**Issue by ace-n** [Automattic/mongoose#11928]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.8

### Node.js version

14.19.1

### MongoDB server version

N/A

### Description

[The Mongoose docs](https://mongoosejs.com/docs/connections.html#:~:text=reconnectFailed%3A%20Emitted%20when%20you%27re%20connected%20to%20a%20standalone%20server%20and%20Mongoose%20has%20run%20out%20of%20reconnectTries.%20The%20MongoDB%20driver%20will%20no%20longer%20attempt%20to%20reconnect%20after%20this%20event%20is%20emitted.%20This%20event%20will%20never%20be%20emitted%20if%20you%27re%20connected%20to%20a%20replica%20set.) mention a property called `reconnectTries`.

This used to work fine with the `mongodb` NPM package for `3.x` versions, but fails on the latest versions of `mongodb` (`4.x`) that [Mongoose itself uses](https://github.com/Automattic/mongoose/blob/master/package.json#L24).

### Steps to Reproduce

Run this code:
```
const mongoose = require('mongoose')
const mongoURI = "mongodb://127.0.0.1:8080/"

const connectToMongoDB = async () => {
    await mongoose.connect(mongoURI, {
        useNewUrlParser: true,
        connectTimeoutMS: 2000,
        reconnectTries: 5,
        useUnifiedTopology: true
    })
};

connectToMongoDB();
```

### Actual Behavior
I get an error that looks like this:
```
(node:22113) UnhandledPromiseRejectionWarning: MongoParseError: option reconnecttries is not supported
    at parseOptions (<ROOTDIR>/node_modules/mongodb/lib/connection_string.js:280:15)
    at new MongoClient (<ROOTDIR>/node_modules/mongodb/lib/mongo_client.js:62:63)
    at <ROOTDIR>/node_modules/mongoose/lib/connection.js:784:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (<ROOTDIR>/node_modules/mongoose/lib/connection.js:781:19)
    at <ROOTDIR>/node_modules/mongoose/lib/index.js:344:10
    at <ROOTDIR>/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (<ROOTDIR>/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (<ROOTDIR>/node_modules/mongoose/lib/index.js:1182:10)
```

### Expected Behavior

Either Mongoose should be updated to support the `reconnectTries` property, or references to it should be removed from the docs and  marked as deprecated in public documentation.

**Comment by Uzlopak** [comment]
Created PR #11930 
Please have a look
