### ISSUE TITLE
new mongoose.Types.ObjectId(string) error: Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by sm-hejazi** [Automattic/mongoose#11926]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.6

### Node.js version

16.14.0

### MongoDB server version

4.4

### Description

Hi
I update to latest 6.3.6 and get error on
`new mongoose.Types.ObjectId('6283b2a42d846b51402dbabe')`
error message is: TS2554: Expected 0 arguments, but got 1.

### Steps to Reproduce

await mongoose.connection.collection('collectionName')
                .findOne({ _id: new mongoose.Types.ObjectId('stirngObjectId') });`

**Comment by sm-hejazi** [comment]
this problem with pnpm, i migrate to  yarn and fix it.

**Comment by Uzlopak** [comment]
Closing it as it was solved by yourself :)
