### ISSUE TITLE
Upgrading mongoose to 6.3.5 makes first test fails

### ISSUE THREAD

**Issue by shubhampatwa** [Automattic/mongoose#11931]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.5

### Node.js version

14.18.3

### MongoDB version

3.7.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I had updated my mongoose to 6.3.5, after this code working fine, but when it comes to test case, my first test always fails

I'm using 
`"mongodb-memory-server-global-4.4": "8.6"`
`"@types/mongodb-memory-server": "^1.8.0",`

for running it on local only 

but  it still shows timeout 

`MongooseError: Operation categories.findOne() buffering timed out after 10000ms`
`thrown: "Exceeded timeout of 60000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."`
    
<img width="1462" alt="Screenshot 2022-06-14 at 7 39 58 PM" src="https://user-images.githubusercontent.com/5588651/173600380-78dee18e-4564-4729-9a0f-886f1b4acd0c.png">

**Comment by Uzlopak** [comment]
Do you use the example implementation by mongodb memory server for spawning a mongodb instance and connecting with mongoose?

**Comment by vkarpov15** [comment]
Please provide some code samples that demonstrate this issue, it's hard to guess your setup from a screenshot.

It looks like you're using Jest - please make sure you've followed our [Jest testing guide](https://mongoosejs.com/docs/jest.html). Also, please note that we strongly recommend using any testing framework other than Jest.

**Comment by firehudson** [comment]
Hello @Uzlopak, I'm working in the same team with @shubhampatwa and trying to take care of the issue that @shubhampatwa raise here.

> Do you use the example implementation by mongodb memory server for spawning a mongodb instance and connecting with mongoose?

Yes, we've tried implementing the same setup suggested b the docs.



> Please provide some code samples that demonstrate this issue, it's hard to guess your setup from a screenshot.
> 
> It looks like you're using Jest - please make sure you've followed our [Jest testing guide](https://mongoosejs.com/docs/jest.html). Also, please note that we strongly recommend using any testing framework other than Jest.

Sure, I'll quickly create a sample repo and share it. Thanks

**Comment by ajaypatidar7722** [comment]
Hello @Uzlopak, I'm working in the same team with @shubhampatwa and trying to take care of the issue that @shubhampatwa raise here.

> Do you use the example implementation by mongodb memory server for spawning a mongodb instance and connecting with mongoose?

Yes, we've tried implementing the same setup suggested b the docs.

> Please provide some code samples that demonstrate this issue, it's hard to guess your setup from a screenshot.
> 
> It looks like you're using Jest - please make sure you've followed our [Jest testing guide](https://mongoosejs.com/docs/jest.html). Also, please note that we strongly recommend using any testing framework other than Jest.

Sure @vkarpov15 , I'll quickly create a sample repo and share it. Thanks

**Comment by khivi** [comment]
we having same issue

**Comment by vkarpov15** [comment]
@khivi please open a new issue and follow the issue template
