### ISSUE TITLE
Change streams: return mongoose Document if `fullDocument` is present in the change document

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#11936]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

MongoDB change events may contain the whole document that was modified under the key `fullDocument`. Would it make sense to have mongoose automatically wrap this in an appropriate mongoose Document class?

### Motivation

Given that I already use mongoose Documents most of the time, it might make sense to have them here. This would enable me to use instance methods, getters, setters, virtual fields, etc.

**Comment by Uzlopak** [comment]
It should atleast be activated under an options flag, because hydrating Documents is a performance eater.
