### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite (any model)

### ISSUE THREAD

**Issue by iserdmi** [Automattic/mongoose#11937]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.6

### Node.js version

v16.13.2

### MongoDB server version

4.4.1

### Description

Everything is ok in 6.3.5, but in 6.3.6 and later versions types are broken:
```
const User = model<IUser>('User', userSchema);
```
Will throw error: Type instantiation is excessively deep and possibly infinite.

### Steps to Reproduce

```
import { Schema, model, connect } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const User = model<IUser>('User', userSchema);
```

### Expected Behavior

No error «Type instantiation is excessively deep and possibly infinite», like it works in >=6.3.5

**Comment by Uzlopak** [comment]
https://www.typescriptlang.org/play?ts=4.7.2#code/JYWwDg9gTgLgBAbzgZQMYAsCmICGAaOECAE0wBsDUIA7azVeAXzgDMoIQ4ByI6gcwgQAzpi4BuAFASA9NLgBGAHRwAwlEw4YmODmpxg1LVBY5U29WHUjDBvjrjEIqAK4hMh-XoCyNAQBEAIUUJAyMTMzgASQBVEShECTg4ahw3AC44IRgoW0kk7BxgMgysnP48nQA3TRwoAH4S7NyJRilZOAAmZTUNLXs0LFw4KigrSGpiWzgYCGmsBydXd3hQzGNTTGCqaiy4ZziBgrgAXmTMAHcUDAKAHhi4gD4ACgRE5NTMDKQYAE8wT5QTX4BHUAEdnMB1MQMtlnNpGHg3gUil9pn8AcggXwQZhwZDMNDplA4XAEW8cNUYLUMpiynwWgBKSQyOQAZm66k02hwcB8pDIWxou1iaxOhBI5DuIqgzy40q4BH2a0OuCZQA

Doesnt throw?

**Comment by iserdmi** [comment]
Excuse me please. Removing `.yarn/cache` and `node_modules` fixed this issue

**Comment by Uzlopak** [comment]
No need to excuse ;)
