### ISSUE TITLE
Can't customize discriminator option minimize

### ISSUE THREAD

**Issue by vickyrathee** [Automattic/mongoose#11942]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.8

### Node.js version

16.14.0

### MongoDB server version

5x

### Description

Getting error in `{minimize: false}` options passed in schema using [nest.js with mongoose](https://docs.nestjs.com/techniques/mongodb#discriminators) latest version. This seems to be reported before in #7435 but closed. We are getting this error again in latest version.

![image](https://user-images.githubusercontent.com/6106479/174222384-52e16d35-5de8-48f9-9c0f-da4f3ab6ba80.png)

Schema
```
@Schema({
  minimize: false
})
export class Event {
  @ApiProperty()
  @Prop({ required: true })
  name?: string;

  @ApiProperty({ default: {} })
  data?: Data;
}
export const EventSchema = SchemaFactory.createForClass(Event);
```

### Steps to Reproduce

- Use the discriminators
- Add `{minimize: false}`

**Comment by vkarpov15** [comment]
@vickyrathee this looks like expected behavior as far as I can tell. You can't set `minimize: false` on a discriminator schema unless you also set `minimize: false` on the base schema.

Also, #7435 has nothing to do with this issue.
