### ISSUE TITLE
Upgrading mongoose from 5.3.14 to ^6.0.0 leads to Server selection timed out

### ISSUE THREAD

**Issue by LeoSko** [Automattic/mongoose#11946]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.14

### Node.js version

18.3.0

### MongoDB version

4.4.14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I have a simple code which reproduces subj on my side:
```
import mongoose from "mongoose";
mongoose.Promise = global.Promise;

console.log(`Connecting to ${app.locals.mongoConnectString}`);
mongoose.connect(app.locals.mongoConnectString, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  authSource: app.locals.authSource,
  auth: app.locals.auth,
  dbName: app.locals.dbName,
}, (err) => console.error("Error connecting to MongoDB: " + err));
```
Mongo is a remote running in cluster mode with 1 single primary node.
I also tried variation with specifying all params in connect string with same result.

When using mongoose starting from version 6.0.0 (including latest 6.3.8), I get the following error:
`Error connecting to MongoDB: MongooseServerSelectionError: Server selection timed out after 30000 ms`
This doesn't happen when I'm using mongoose version 5.3.14 and I'm getting all expected results with queries working etc.
My initial reason to upgrade was because of #7367 and I have expected different results but being unable to connect.

**Comment by vkarpov15** [comment]
@LeoSko can you please print out the `error.servers.reason` property and paste the result here? That will help us tell what the MongoDB driver thinks the state of your replica set is.

Also, please take a look at this section of the docs, it explains what is the most common cause of "cannot connect to replica set" is in our experience: https://mongoosejs.com/docs/connections.html#replicaset-hostnames

**Comment by LeoSko** [comment]
@vkarpov15, `err.servers` was undefined for me when error happened.
The link you provided helped - my node was reporting rs.conf() with `127.0.0.1:27017`. I reconfigured it to use hostname instead and mongoose `6.3.8` now successfully connects. Is it intentional change introduced in 6 version?

**Comment by vkarpov15** [comment]
Sorry, I meant `err.reason.servers`. This change was introduced by the [MongoDB node driver](https://npmjs.com/package/mongodb) behind a flag in 3.x and is now the default behavior in 4.x, which is the version that Mongoose 6 uses.
