### ISSUE TITLE
`Model.applyDefaults()` and `Model.castObject()`

### ISSUE THREAD

**Issue by ajwootto** [Automattic/mongoose#11945]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.0.11

### Node.js version

16

### MongoDB version

4.6

### Operating system

macOS

### Issue

I have a use case where I want to be able to apply the Mongoose schema I have defined for a model to some plain data, without constructing the Mongoose document wrapper around it by doing `new Model`. The reason for this is to apply all the schema's defaults, datatype casting etc. without the CPU intensive task of constructing a full document with all the getters / setters and change tracking.

Is there a way to do this in Mongoose? Essentially to provide it some JSON data and get back a lean version of the document I would otherwise get by doing `new Model`?

Edit: I guess this question presumes that a "lean" query actually applies the Mongoose schema to the returned data, which I'm not actually sure is true. A better question then is basically "can I apply the schema defined by Mongoose to a piece of plain data without constructing a full document"?

**Comment by vkarpov15** [comment]
I'm not sure I understand what you're trying to do. If you have some plain data, you already have a lean document - a lean document is a [POJO](https://masteringjs.io/tutorials/fundamentals/pojo).

I'm guessing what you're trying to do is apply defaults and type casting without hydrating a full document?

**Comment by ajwootto** [comment]
Yeah exactly, I basically just want to apply the schema to my POJO and get back a POJO with all the defaults and type casting applied

**Comment by vkarpov15** [comment]
This is a good idea. It would be nice to have helper functions on models that apply defaults to a POJO and apply type casting to a POJO. Good for both internal refactoring as well as providing a way to pick and choose which parts of Mongoose you want to use. Similar to `Model.validate()`.
