### ISSUE TITLE
post query middleware, doc is of type `Query<any, any>` 

### ISSUE THREAD

**Issue by bn-piar** [Automattic/mongoose#11950]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

16.15.0

### MongoDB server version

none?

### Description

In the following code `doc` is of type `Query<any, any, {}, any>, but it should refer (I believe) to the document being deleted. 
```javascript
VendorSchema.post('findOneAndDelete', async function (doc) {
    try {
        const vendor = await this.findOneAndUpdate(
            { defaultVendor: true },
            { $set: { companyName: 'Vendor is not set', defaultVendor: true } },
            { upsert: true, new: true }
        );

        // await ProductModel.updateMany({ mainVendor: doc._id });
    } catch (error) {}
});
```

### Steps to Reproduce

1. Create any schema
2. Add post middleware that listens to `findOneAndDelete` query, as a second argument pass function with a parameter `doc`
3. See `doc` type.

### Expected Behavior

I expect callback function parameter to be the document that is being deleted.

**Comment by vkarpov15** [comment]
You're right that the `Query<any, any>` type is incorrect. We're fixing that.

However, `doc` isn't always the document being deleted. It can be a hydrated document, or `null` if no document is found, or a lean document if `lean` option is set, or a `ModifyResult` with the `value` set to one of the preceeding types if `rawResult` option is set. So you'll still have to handle all of those types.

**Comment by bn-piar** [comment]
@vkarpov15 thank you for your work. Not sure it would help but on mongoose 6.3.6 there's no type error.

**Comment by vkarpov15** [comment]
@bn-piar I took a closer look and I don't think we're going to be able to get this typing entirely right without causing a 10x performance degradation. With 25f98b9, `res` will be of type `any` by default, but you can overwrite it at the `post()` level:

```
schema.post<Query<ITest, ITest>>('findOneAndDelete', function(res, next) {
  res; // ITest
  next();
});
```
