### ISSUE TITLE
[Types] mongoose 6.4.0 (PR 11563) broke explicitly set property types

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#11960]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

any

### MongoDB server version

any

### Description

With mongoose 6.4.0 (i think because of #11563) the explicitly set property types are ignored and so break subdocuments, subdocument arrays and maps (and probably other types that require more than explicit objects or get transformed)

### Steps to Reproduce

1. clone https://github.com/typegoose/typegoose-testing/
2. checkout branch `mongoose6.4.0typebreak`
3. run `yarn install` (or equivalent)
4. inspect the types either via something like vscode or run `yarn run build` (or equivalent)

this branch also contains commits for previous versions:
- [`ef07ac6df32938f30cadbbb955b5f0af0301b536`](https://github.com/typegoose/typegoose-testing/tree/ef07ac6df32938f30cadbbb955b5f0af0301b536) for a typegoose inital example (mongoose 6.3.9) (`HEAD~2`)
- [`23d7787e5101cdee81c267cda0f4745c70b6a46f`](https://github.com/typegoose/typegoose-testing/tree/23d7787e5101cdee81c267cda0f4745c70b6a46f) for a mongosoe native (no typegoose) example at 6.3.9 (`HEAD~1`)
- [`fc31453a5463f03d434fb1459dfb26ce4a770bbb`](https://github.com/typegoose/typegoose-testing/tree/fc31453a5463f03d434fb1459dfb26ce4a770bbb) for a mongoose native (no typegoose) example at 6.4.0 (`HEAD`)

### Expected Behavior

All types to work like in the previous minor version / explicitly set types to overwrite inferred types

**Comment by hasezoey** [comment]
Can confirm that installing 3a4ba27a75622a9fc370683744b8822f3f9dbfdf (current latest master) fixes all mentioned issues in the reproduction repository branch

**Comment by vkarpov15** [comment]
Thanks @hasezoey , and I'm sorry for the inconvenience. We'll ship 6.4.1 on Monday.

**Comment by hasezoey** [comment]
i have just now tried version 6.4.1 and noticed that when using `new Model` everything is fine, but when trying to use `Model.create` the problems appear again for everything (maybe `create` was not updated only `new`?)

see https://github.com/typegoose/typegoose-testing/tree/mongoose6.4.0typebreak (`52e8053db8cc0c52343d1bc9869aa005c4c94672`)

**Comment by vkarpov15** [comment]
Thanks for identifying these issues @hasezoey
