### ISSUE TITLE
Mongoose 6.4.0:  Cannot find name 'BufferConstructor'

### ISSUE THREAD

**Issue by TomMettam** [Automattic/mongoose#11963]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

18.3.0

### MongoDB server version

N/A

### Description

After upgrading to mongoose 6.4.0, Typescript projects fail to build due to missing BufferConstructor in typings

```
node_modules/.pnpm/mongoose@6.4.0/node_modules/mongoose/types/inferschematype.d.ts:145:33 - error TS2552: Cannot find name 'BufferConstructor'. Did you mean 'NumberConstructor'?

145           PathValueType extends BufferConstructor | 'buffer' | 'Buffer' | typeof Schema.Types.Buffer ? Buffer :
                                    ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/mongoose@6.4.0/node_modules/mongoose/types/inferschematype.d.ts:145

```

### Steps to Reproduce

> Upgrade to Mongoose 6.4.0
> Compile typescript project

### Expected Behavior

No error

**Comment by Jule-** [comment]
Same here!

**Comment by xurtasun** [comment]
Same issue here!

**Comment by IslandRhythms** [comment]
```typescript
import { Schema, model, connect } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const User = model<IUser>('User', userSchema);

run().catch(err => console.log(err));

async function run() {
  // 4. Connect to MongoDB
  await connect('mongodb://localhost:27017/test');

  const user = new User({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await user.save();

  console.log(user.email); // 'bill@initech.com'

}
```

**Comment by TomMettam** [comment]
(@IslandRhythms FYI this does make mongoose incompatible with node versions below 16.6)

**Comment by vkarpov15** [comment]
@TomMettam no it doesn't, Mongoose is compatible with Node versions below 16.6. This is a bug in `@types/node`. Further, `@types/node` versions don't line up with node versions beyond major versions. So `@types/node@16.6.0` is a release that attempts to be compatible with Node 16.x, but doesn't include exactly the same changes as Node 16.6.
