### ISSUE TITLE
Compound Index. Argument of type '{ unique: boolean; }' is not assignable to parameter of type 'IndexOptions'.

### ISSUE THREAD

**Issue by dmitryr117** [Automattic/mongoose#11979]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.3

### Node.js version

18.1.0

### MongoDB version

5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Issue

I am trying to create a schema with a compound unique Index:
```
export const ContractorRoleSchema = new Schema<IContractorRoleSchema>({
  role_name: String,
  contractor: { type: Schema.Types.ObjectId, ref: DbModelEnum.Contractor },
  permissions: { type: [ String ], default: [] }, 
  updated_on: Date,
  is_default: Boolean
});
ContractorRoleSchema.index({ role_name: 1, contractor: 1 }, { unique: true });
```
However an error comes up in VSCode saying:
Argument of type '{ unique: boolean; }' is not assignable to parameter of type 'IndexOptions'.
Object literal may only specify known properties, and 'unique' does not exist in type 'IndexOptions'.

All tutorials I find online are older, and seem to use this technique. Thank you.

**Comment by vkarpov15** [comment]
Try upgrading to 5.13.7, this may potentially be related to #10563. Also, 2 followup questions:

1. are you using `@types/mongoose`?
2. Do you get this error when you try to compile your project? Because I can confirm the below script compiles correctly with Mongoose 5.13.3 and TypeScript 4.7.4:

```ts
import { Schema, Types } from 'mongoose';
  
interface IContractorRoleSchema {
  role_name: string;
  contractor: Types.ObjectId;
  permissions: string[];
  updated_on: Date;
  is_default: boolean;
}

const ContractorRoleSchema = new Schema<IContractorRoleSchema>({
  role_name: String,
  contractor: { type: Schema.Types.ObjectId },
  permissions: { type: [ String ], default: [] },
  updated_on: Date,
  is_default: Boolean
});
ContractorRoleSchema.index({ role_name: 1, contractor: 1 }, { unique: true });
```

Also, I strongly recommend you upgrade to Mongoose 6, because [Mongoose 5.x does not fully support MongoDB server 5.x](https://mongoosejs.com/docs/compatibility.html).

**Comment by nayabbeig** [comment]
I know I am answering very late, but just in case someone else visit this link, if you are using @types/mongoose, you can do the work around like below

export const ContractorRoleSchema = new Schema<IContractorRoleSchema>({
  role_name: String,
  contractor: { type: Schema.Types.ObjectId, ref: DbModelEnum.Contractor },
  permissions: { type: [ String ], default: [] }, 
  updated_on: Date,
  is_default: Boolean
});
ContractorRoleSchema.index({ role_name: 1, contractor: 1 }, { unique: true } **as IndexOptions**);
