### ISSUE TITLE
6.4 has compile errors on Typescript 4.8 beta

### ISSUE THREAD

**Issue by sandersn** [Automattic/mongoose#11977]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4

### Node.js version

16.15

### MongoDB server version

4.7

### Description

Mongoose 6.4 uses the new type `MergeType` throughout models.d.ts. This type requires its type arguments to `extend Record<string | number, any>`, but none of them are! It's used 16 times in models.d.ts and all of its arguments are unconstrained type parameters, like `T`, which could possibly allow `null` or `undefined`.

For more background, see: https://github.com/microsoft/TypeScript/issues/49489

### Steps to Reproduce

Clone mongoose
Open types/models.d.ts in an editor running Typescript 4.8.

You can get the same errors when compiling a package that depends on mongoose, like `@types/mongoose-unique-validator`. (I discovered this error by reviewing failures on Definitely Typed.)

### Expected Behavior

No compile errors on Typescript 4.8.

**Comment by rongem** [comment]
I also have compiling errors after upgrading to mongoose 6.4 under typescript 7.4. It seems that mongoose changed the way, complex parameters (i. e. in find method) are interpreted. Return types for many functions are now no longer the type, but Omit<Merge<somthing>>.

**Comment by sandersn** [comment]
I don't know mongoose, but its new `MergeType` is a better reflection of object spread semantics or `Object.assign` semantics than before, since when you spread `{ ...A, ...B}`, B's properties overwrite any of A's that conflict.
