### ISSUE TITLE
Need help related to mongoose and typescript.

### ISSUE THREAD

**Issue by xoldyckk** [Automattic/mongoose#11975]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Here's a list of [all possible ways](https://getridbug.com/node-js/mongoose-the-typescript-way/) in which we can carry out typescript integration with mongoose. Which is the best and recommended way? 

Also I've noticed typescript really doesn't integrate well together with mongoose. The documentation on mongoose website for integration with typescript is also really bad. It only covers simple aspects of it not all the use cases. Can you please provide me some links to good examples of mongoose and typescript integration for mongoose version 5.x.x?

**Comment by vkarpov15** [comment]
For Mongoose 5.x, you can try Typegoose or Method 6 (your `ModelDefinition` helper).

However, we recommend upgrading to Mongoose 6. We added automatic schema type inference in 6.4.0, which addresses the "out of sync fields" issue.

```ts
import { Schema, model } from 'mongoose';

const schema = new Schema({ name: String });
const Test = model('Test', schema);

const doc = new Test({ name: 'foo' });

// Works! `name` is a string
doc.name.includes('foo');

// Property 'foobar' does not exist on type 'Document<unknown, any, { name?: string; }> & { name?: string; } & { _id: ObjectId; }'.
doc.foobar.includes('bar');
```

See: https://mongoosejs.com/docs/typescript/schemas.html
