### ISSUE TITLE
PipelineStage.Match type errors when updating to 6.4.0

### ISSUE THREAD

**Issue by StefanSuciu** [Automattic/mongoose#11993]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

16.0

### MongoDB server version

5.0.9

### Description

`PipelineStage.Match` operator `Expression.In` expects `$in: [Expression, ArrayExpression]`, which is the `{ $in: [field, array] }` notation, however, it should allow for the `{ field: { $in: array } }` notation as well (as it did prior to [this update - #11370 maybe](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md#640--2022-06-17)).

[$in query operator](https://www.mongodb.com/docs/manual/reference/operator/query/in/)
[$in aggregation operator](https://www.mongodb.com/docs/manual/reference/operator/aggregation/in/)

### Steps to Reproduce

This query (the model itself is not relevant):

```
model.aggregate([
    { $match: { fruits: { $in: ['apple', 'orange', 'lemon'] } } },
]);
```

Will trigger this ts error:

```
No overload matches this call.
  Overload 1 of 2, '(pipeline?: PipelineStage[], options?: AggregateOptions, callback?: Callback<any[]>): Aggregate<any[]>', gave the following error.
    Type '[string, string, string]' is not assignable to type '[Expression, ArrayExpression<any>]'.
      Source has 3 element(s) but target allows only 2.
  Overload 2 of 2, '(pipeline: PipelineStage[], callback?: Callback<any[]>): Aggregate<any[]>', gave the following error.
    Type '[string, string, string]' is not assignable to type '[Expression, ArrayExpression<any>]'.
```

Furthermore, the below query is valid (in terms of types):

```
model.aggregate([
    { $match: { $in: ['$fruits', ['apple', 'orange', 'lemon']] } }
]);
```

But it's not a valid mongo query...

### Expected Behavior

The `$in` query operator should be allowed in a `$match` stage of an aggregation pipeline. 
The `$in` aggregation operator should not be allowed as a top level operator in a `$match` stage.

**Comment by jyeros** [comment]
I think this is already fixed at #11969, but it isn't published yet.

**Comment by StefanSuciu** [comment]
Thank you! I'll close this.

**Comment by jyeros** [comment]
6.4.1 fixed the issue for me.
