### ISSUE TITLE
InferSchemaType generates Schema.Types.ObjectId instead of the Types.ObjectId we want

### ISSUE THREAD

**Issue by keysking** [Automattic/mongoose#12002]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.1

### Node.js version

18.*

### MongoDB server version

5.x

### Description

I learned from the documentation that when a Schema has a field whose type is Schema.Types.ObjectId, the corresponding Typescript type should be Types.ObjectId. 
However, when I use InferSchemaType to generate the type, the type it generated for me is Schema.Types.ObjectId.
This prevents me from using the new Types.ObjectId () to pass into my field.

### Steps to Reproduce

```typescript
import { InferSchemaType, model, Schema } from 'mongoose';
const productSchema = new Schema({
  typeId: { type: Schema.Types.ObjectId, ref: 'ProductType' },
});
export type Product = InferSchemaType<typeof productSchema>;
export const Product = model<Product>('Product', productSchema);

const add(product: Product) {}

add({ typeId: new Types.ObjectId()});
```
![image](https://user-images.githubusercontent.com/16982187/176147226-a7728d9f-b8ee-4a27-bbd6-8d12d1e20caa.png)

**Comment by mohammad0-0ahmad** [comment]
@keysking  Thanks for reporting this issue.

**Comment by keysking** [comment]
> @keysking Thanks for reporting this issue.

My pleasure😁.

**Comment by borispinus** [comment]
apparently encountered  with similar problem but in my case the field is array of refs:

```
const schema = new mongoose.Schema({
  goods: [{ type: mongoose.Schema.Types.ObjectId, ref: "Goods" }],
});

type Promo = InferSchemaType<typeof schema>
```

the inferred type is  `goods: {         type?: mongoose.Types.ObjectId | undefined;         ref?: unknown;     }[]` istead of  expected `goods: mongoose.Types.ObjectId[]`

**Comment by jbolter** [comment]
> apparently encountered with similar problem but in my case the field is array of refs:
> 
> ```
> const schema = new mongoose.Schema({
>   goods: [{ type: mongoose.Schema.Types.ObjectId, ref: "Goods" }],
> });
> 
> type Promo = InferSchemaType<typeof schema>
> ```
> 
> the inferred type is `goods: { type?: mongoose.Types.ObjectId | undefined; ref?: unknown; }[]` istead of expected `goods: mongoose.Types.ObjectId[]`

Any fix that you found? I'm running into the same issue.

**Comment by borispinus** [comment]
Nope, I just used type casting to force mongoose.Types.ObjectId[]

**Comment by jbolter** [comment]
I ended up just creating the schema manually instead of using InferSchemaType to avoid the bug.
