### ISSUE TITLE
Schema type disappears when using InferSchemaType with SchemaOptions

### ISSUE THREAD

**Issue by jeetkn** [Automattic/mongoose#12003]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.1

### Node.js version

14.18.3

### MongoDB version

Unsure

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Issue

Created as empty object type when creating schema type using `InferSchemaType` with `SchemaOptions`

```typescript
const baseSchemaOptions: SchemaOptions = {
    versionKey: false,
}

const BaseSchema = new Schema({
    name: String
}, baseSchemaOptions);

type BaseSchemaType = InferSchemaType<typeof BaseSchema>;
// type BaseSchemaType = {}
const BaseModel = mongoose.model<BaseSchemaType>("Test", BaseSchema);
// const BaseModel = mongoose.Model<{}, {}, {}, {}, any>
```

but without `SchemaOptions`

```typescript
const BaseSchema = new Schema({
    name: String
});
BaseSchema.set("versionKey", false);

type BaseSchemaType = InferSchemaType<typeof BaseSchema>;
// type BaseSchemaType = { name: string; }
const BaseModel = mongoose.model<BaseSchemaType>("Test", BaseSchema);
// const BaseModel = mongoose.Model<{ name: string; }, {}, {}, {}, any>
```
Is this type correct?

**Comment by mohammad0-0ahmad** [comment]
@jeetkn  Thanks for reporting this issue.
I will check if we can fix that, but a quick workaround is :
```js
onst BaseSchema = new Schema({
    name: String
}, baseSchemaOptions as any);
```

**Comment by mohammad0-0ahmad** [comment]
I will publish a PR for solving this issue soon, thanks again @jeetkn
