### ISSUE TITLE
boolean field with default true value is returning true though the key and value are not present in the database

### ISSUE THREAD

**Issue by AshutoshSajan** [Automattic/mongoose#12000]
boolean field with default true value is returning true though the key and value are not present in the database. so when I want to add a check for this value to update it, it's always returning true.

**Comment by LucGranato** [comment]
@AshutoshSajan, I understand that this is actually the expected behavior.
Otherwise, having a default value only when the field is already defined does not make sense.

**Comment by AshutoshSajan** [comment]
```js
import { Schema, model } from 'mongoose';

const usersSchema = new Schema(
  {
    name: { type: String, required: true },
    username: {
      type: String, required: true, index: true,
    },
    email: { type: String, required: true },
    isActive: { type: Boolean, default: true } // new field
  {
    timestamps: true,
  },
);

export default model('users', usersSchema);

const user = Users.findOne({ username: "old_user" })
// here user.isActive is true, though in the db there is no isActive key, so we have to add isActive feild in db manually.
```

**Comment by vkarpov15** [comment]
Expected behavior. If `isActive` isn't set, Mongoose will apply the default when loading the document from the database. However, you can set `defaults: false` option on `findOne()` to disable this behavior:

```javascript
const user = await Users.findOne({ username: "old_user" }).setOptions({ defaults: false })
```

**Comment by AshutoshSajan** [comment]
> Expected behavior. If `isActive` isn't set, Mongoose will apply the default when loading the document from the database. However, you can set `defaults: false` option on `findOne()` to disable this behavior:
> 
> ```js
> const user = await Users.findOne({ username: "old_user" }).setOptions({ defaults: false })
> ```

thanks
