### ISSUE TITLE
MongoServerError: The path 'inventory.ores' must exist in the document in order to apply array updates.

### ISSUE THREAD

**Issue by LordLucass** [Automattic/mongoose#12008]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

18.4.1

### MongoDB version

5.0.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.18.7-arch

### Issue

Basically, I have a database where:
```js
inventory: {
  items: [],
  equippedItems: [],
  backpack: { _id: 'Common', limit: 30 },
  _id: '62bb9ecf74911202163ffab3',
  fishies: [],
  ores: [],
  buyableItems: [],
  resources: [ { _id: 'wood', quantity: 20, lastDateAdded: 1656462936489 } ]
}
```
And I have some code, where its function is to remove a resource/item/ore. This code is a function called removeItem, from a class called Inventory.
```js
  async removeItem (material, quantity, type = "resources") {
    const item = (await this.getUser()).inventory[type].find(c => c._id == material);

    if (item?.quantity - quantity <= 0)
      return this._users.update(this.user, { $pull: { [`inventory.${type}`]: { _id: material } } });

    return this._users.update(this.user,
      { $inc: { [`inventory.${type}.$[item].quantity`]: -quantity },
      { arrayFilters: [{ "item._id": material }] }
    );
  }
```
Whenever I try to remove an item, for example `wood`, I get the error that is described in the title, now, the question is: Why does this occur? The ores array exists, and is always created automatically when a user interacts with the application. I have tried using `$exists: true` but it doesn't help, so I am asking for your help.

PS. getUser() is a snippet that return user's database.

Here is the snippet of code, where the removeItem function is used:
```js
   const InventoryManager = new Inventory(author.id, this.client, channel); // instantiating class, ignore

    const name = itemId.split(" ").filter(c => !Number(c)).join(" "); // resource's name

    const removeItem = (_name, type) => InventoryManager.removeItem(_name, quantity, type); // arrow function to turn my work more practical

    let found = false;

    if (await (ToolManager.itemData(name))) (found = true, await ToolManager.breakTool(name)); // another function, but this works

    if (!found) found = UselessUtils.checkSimilarity(name, Resources); // works here too, same concept about ores below

    if (found) await removeItem(found.name[0], "resources"); // works here too, same concept about ores below

    if (!found) found = UselessUtils.checkSimilarity(name, Ores); // the problem is here and below

    if (found) await removeItem(found.name[0], "ores"); // the problem is here too
```

## Please, HELP!

**Comment by vkarpov15** [comment]
Hard to tell without a more complete code sample, but my best guess is that the below code:

```
return this._users.update(this.user,
      { $inc: { [`inventory.${type}.$[item].quantity`]: -quantity },
      { arrayFilters: [{ "item._id": material }] }
    );
```

causes this error when `item` is null. Please double check if that is the case.

If you need more help, please modify the below script to demonstrate the issue you're seeing:

```javascript
'use strict';

const mongoose = require('mongoose');

void async function main() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const Test = mongoose.model('Test', new mongoose.Schema({
    inventory: {
      ores: [{ _id: String }],
      woods: [{ _id: String }]
    }
  }));

  let doc = await Test.create({
    inventory: {
      ores: [{ _id: 'ore1' }, { _id: 'ore2' }],
      woods: [{ _id: 'wood1' }, { _id: 'wood2' }]
    }
  });

  const item = doc.inventory.ores.find(o => o._id === 'ore2');
  await Test.update({ $pull: { 'inventory.ores': { _id: 'ore2' } } });
  console.log('Done');
}();
```

**Comment by LordLucass** [comment]
Hello, I have just analyzed the function, debugged it, and it really is not a problem in the package, not even in its functions, it was a logic error, my mistake. Basically the conditions are running the code 2x, so it looks in the 'resources' and in the 'ores', that's why it didn't locate the material and returned that error. I apologize, and thank you for your help!
