### ISSUE TITLE
Missing types in index.d.ts - bulkSave in Model interface

### ISSUE THREAD

**Issue by pavanyekabote** [Automattic/mongoose#12019]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

version: 5.x

In model.js Model has a method bulkSave, but it is not added in the Model interface of index.d.ts. This creates an issue while using typescript with strict typechecking.

**Comment by vkarpov15** [comment]
This was fixed for 6.x in 6.0.7 with #10745 . Is there anything blocking you from upgrading to 6.0?

**Comment by pavanyekabote** [comment]
If I migrate to 6.x, I may have to test everything for backward compatibility. Since on ugrading to 6.x, I have noticed mongoose.connect method's `ConnectOptions` have changed ( Eg: `useUnifiedTopology` options is not available in 6.x options ).

**Comment by vkarpov15** [comment]
Yep, Mongoose 6 always behaves as if `useUnifiedTopology = true`. So that option was removed.

We'll do what we can to backport this fix to 5.x.
