### ISSUE TITLE
'Cannot read properties of undefined' of mongoose response object

### ISSUE THREAD

**Issue by Dema7** [Automattic/mongoose#12015]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.2.10

### Node.js version

14.17.4

### MongoDB version

5.0.5

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.6

### Issue

Below the mongoose Schema in node.js I am using:
```
mongoose.Schema({
    name: { type: String, required: true },
    userId: { type: String },
    water: { type: Array },
    fertilizer: { type: Array }
})
```
And the following is the query that I made:
```

Plant.aggregate([{
        $facet: {
            waterPipeline: [
                {$match: 
                    {$and: 
                        [{userId: sessionUserId}]
                }}, 
                {$unwind: {path: "$water", preserveNullAndEmptyArrays: true}},
                {$sort: {'water.date': -1}},
                {$group: {_id: '$_id', name:{$first: '$name'}, userId:{$first: '$userId'}, water:{$addToSet: '$water.date'}}},
                {$sort: {name: 1}}
            ],
            fertilizerPipeline: [
                {$match: 
                    {$and: 
                        [{userId: sessionUserId}]
                }}, 
                {$unwind: {path: "$fertilizer", preserveNullAndEmptyArrays: true}},
                {$sort: {'fertilizer.date': -1}},
                {$group: {_id: '$_id', fertilizer:{$addToSet: '$fertilizer.date'}}},
                {$sort: {name: 1}}
            ]
        }
    }])
```
I used facet in order to get two different aggregations and order the collections by two different date fields.

Here the response object that I get (which by the way is exactly what I need):
```

[{…}]
0:
fertilizerPipeline: Array(4)
0: {_id: '62b31bd642e3879a2bc014d6', fertilizer: Array(2)}
1: {_id: '629242c245908061eb0a58d9', fertilizer: Array(2)}
2: {_id: '6297676be803aada1b2fe47e', fertilizer: Array(0)}
3: {_id: '62ac4477a25a1208e29ff8b1', fertilizer: Array(0)}
length: 4
[[Prototype]]: Array(0)
waterPipeline: Array(4)
0: {_id: '6297676be803aada1b2fe47e', name: 'crisantemo', userId: '627154a5e1ba50ffac585716', water: Array(5)}
1: {_id: '62ac4477a25a1208e29ff8b1', name: 'melograno', userId: '627154a5e1ba50ffac585716', water: Array(1)}
2: {_id: '62b31bd642e3879a2bc014d6', name: 'santoreggia', userId: '627154a5e1ba50ffac585716', water: Array(2)}
3: {_id: '629242c245908061eb0a58d9', name: 'timo', userId: '627154a5e1ba50ffac585716', water: Array(5)}
length: 4
[[Prototype]]: Array(0)
[[Prototype]]: Object
length: 1
[[Prototype]]: Array(0)
```
but when I try to access (client side) the waterPipeline or fertilizerPipeline property like this:
```

result[0].fertilizerPipeline
```
I get this error:
```

Cannot read properties of undefined (reading 'fertilizerPipeline')
```
According to similar topics, it seems that the problem resides in the mongoose Schema, since the new pipelines created through facet are not mentioned in it. I tried to adapt the Schema accordingly but still I get the same error. What I tried is:
```

mongoose.Schema({
    name: { type: String, required: true },
    userId: { type: String },
    water: { type: Array },
    fertilizer: { type: Array },
    fertilizerPipeline: [{ type: Object }],
    waterPipeline: [{ type: Object }]
})
```
and others similar, but nothing seems to work.

How to fix this? Am I on the right path or the issue is something else?

Last info: I tried a much simpler query without facet and the response object I get works just fine.

**Comment by vkarpov15** [comment]
Mongoose doesn't cast aggregation pipelines or aggregation output, so that isn't the problem. Based on the error message, my best guess is that `result` is an empty array. Can you check to make sure that `result` actually contains a value on the client side, and, if not, clarify what you're using to pass the object to the client?

**Comment by Dema7** [comment]
Hi @vkarpov15, thanks for the reply.
`result` is not empty. The array contains all the documents shown above (which are what I need).
On client side, I do a `axiom` POST request, through which I get the `result` object.
To clarify, I can display the returned object on the client console but I cannot access the elements inside it.

**Comment by Dema7** [comment]
Last info: I tried a much simpler aggregation and the response object works just fine. Like the following:

```
Plant.aggregate([{$match: 
                        {$and: 
                            [{userId: sessionUserId}]
                        }}, 
                        {$unwind: {path: "$water", preserveNullAndEmptyArrays: true}},
                        {$sort: {'water.date': 1}},
                        {$group: {_id: '$_id', name:{$first: '$name'}, userId:{$first: '$userId'}, water:{$addToSet: '$water.date'}, fertilizer:{$addToSet: '$fertilizer.date'}}}, 
                        {$sort: {name: 1}} // sort documents by name
        ])
        .then(response => res.send(response))
```

**Comment by vkarpov15** [comment]
Realistically we're not going to be able to repro this without a complete code sample. Either way, if you're getting the correct object on the client, that means this isn't a Mongoose issue.

**Comment by Dema7** [comment]
How can I share a code sample? Do I have to upload it on Github?
Mongoose works just fine as long as don't use facet. When I use facet in the aggregation I get that error

**Comment by vkarpov15** [comment]
@Dema7 you can just paste a code snippet in a GitHub comment
