### ISSUE TITLE
Schema Type is inferred as a Partial when assigning schema definition to a variable 

### ISSUE THREAD

**Issue by heilmela** [Automattic/mongoose#12012]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.1

### Node.js version

16.13.0

### MongoDB server version

5.0

### Description

When assigning the schema definition to a variable instead of directly passing it to the schema constructor the resulting type has all properties inferred as optionals.

### Steps to Reproduce

```js
import { Schema, InferSchemaType } from 'mongoose';

const schemaDefintion = {
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String,
};

// Schema
const schema = new mongoose.Schema(schemaDefintion);

type User = InferSchemaType<typeof schema>;
// InferSchemaType will determine the type as follows:
//  type User = {
//     name?: string | undefined;
//     email?: string | undefined;
//     avatar?: string | undefined;
// }
```

### Expected Behavior

```js
type User = InferSchemaType<typeof schema>;
// InferSchemaType will determine the type as follows:
// type User = {
//     name: string;
//     email: string;
//     avatar?: string | undefined;
// }
```

**Comment by imranbarbhuiya** [comment]
The issue isn't related to `assigning schema definition to a variable`. The issue is `required` props are also showing as optional

**Comment by IslandRhythms** [comment]
`Cannot find name InferSchemaType`

**Comment by IslandRhythms** [comment]
Please mention to hover over User in vscode and also include a way to repro if the person testing does not have vscode

**Comment by mohammad0-0ahmad** [comment]
@heilmela test this:
```ts
import { Schema, InferSchemaType } from 'mongoose';

const schemaDefintion = {
  name: { type: String, required: true as const},
  email: { type: String, required: true  as const},
  avatar: String,
};

const schema = new mongoose.Schema(schemaDefintion);

type User = InferSchemaType<typeof schema>;
```

**Comment by vkarpov15** [comment]
@mohammad0-0ahmad is correct, the right way to do this is `as const;`. TS is currently unable to figure out that `schemaDefinition` isn't modified in any way, so `new mongoose.Schema(schemaDefintion);` is not equivalent to `new mongoose.Schema({ name: { type: String, required: true }, ... })` as far as TS is concerned, unless you add the `as const;`.
