### ISSUE TITLE
InferSchemaType does not infer subdocuments/nested paths

### ISSUE THREAD

**Issue by heilmela** [Automattic/mongoose#12011]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.1

### Node.js version

16.13.0

### MongoDB server version

5.0

### Description

Basically, I took the example from the docs and pluralized property `name`. The reslulting schema type is inferred as `{ ..., names?: unknown[] | undefined }`.

The same thing happens when using a nested document, `names: new Schema({})` and when using `names: {type: [{...}]}` the only array type which seems to be inferred correctly are primitive types e.g. `names: [String]` is inferred correctly as string[]

### Steps to Reproduce

```js
const schema = new mongoose.Schema({
  names: [{ type: String, required: true }],
  email: { type: String, required: true },
  avatar: String,
});

type User = InferSchemaType<typeof schema>;
// InferSchemaType will determine the type as follows:
// type User = {
//   email: string;
//   avatar?: string | undefined;
//   names?: unknown[] | undefined;
// };
```

### Expected Behavior

```js
const schema = new mongoose.Schema({
  names: [{ type: String, required: true }],
  email: { type: String, required: true },
  avatar: String,
});

type User = InferSchemaType<typeof schema>;
// InferSchemaType will determine the type as follows:
// type User = {
//   email: string;
//   avatar?: string | undefined;
//   name: string[] | undefined;
// };
```

**Comment by iammola** [comment]
You're probably supposed to wrap the `names` path in another `Schema` constructor. If not you're making it a mixed path. https://mongoosejs.com/docs/subdocs.html#altsyntaxsingle

From
```ts
names: [{ type: String, required: true }],
```

To
```ts
names: [new Schema({ type: String, required: true })],
```

**Comment by iammola** [comment]
I think it's the `type` alone that should be an array not the whole path

From
 
```ts
names: [{ type: String, required: true }],
```

To
```ts
names: { type: [String], required: true },
```

**Comment by heilmela** [comment]
You might be correct, the example was a bit rash. However the problem still remains when using any non primitive array e.g. 
```
const schema = new mongoose.Schema({
  names: {
    type: [
      {
        first: String,
        last: String,
      },
    ],
    required: true,
  },
  email: { type: String, required: true },
  avatar: String,
});
```

**Comment by iammola** [comment]
Yeah, you're right @heilmela ... I'm about to push a commit to fix that in the PR I've linked above. It should allow defining schema paths like this as well.

```ts
names: [{ type: String, required: true }],
```

**Comment by mohammad0-0ahmad** [comment]
@heilmela  Thanks for reporting this issue.
