### ISSUE TITLE
Feat: add `timestamps` option to `bulkSave`

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#12059]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently, we're able to set `timestamps` to `false` on bulkWrite for a specific operation, or for a `Document#save` by passing it as an option, and for `updateOne` as an option, but there is no way to write a `bulkSave` without updatings timestamps.

### Example

```js
const user = new User({ name: 'John Doe' });
await User.bulkSave([user], { timestamps: false });
```

**Comment by lpizzinidev** [comment]
By looking at the function definition at
https://github.com/Automattic/mongoose/blob/3445d240886e508962d7dd6a8481715a3cb373da/lib/model.js#L3625
The `bulkSave` is built on top of `bulkWrite`.
So the option to disable the `timestamps` should already be present.

**Comment by AbdelrahmanHafez** [comment]
That's true, but the way `bulkWrite` accepts timestamps is on each specific operation, not as a global option on all write operations.

So we need to pass `timestamps` as an option to `bulkSave` and then pass it to each individual operation.
It'd be much nicer if we could make set `timestamps` on each document instead of forcing it on all the documents, but I can't think of a good syntax for it.
Technically, we could allow setting some property on each document that specifies whether we want to enable timestamps on saving/bulkSaving or not: `doc.$saveOptions.timestamps = false;` but that goes against how we generally do things in mongoose, where we pass options as an argument to methods, rather than setting options as properties in the documents themselves.

For my purposes, setting it on all documents is good enough, if we can come up with a cleaner way to do that, I'm more than happy to implement it.

What do you think? @lpizzinidev
