### ISSUE TITLE
TypeScript: timestamps not inferred from schema

### ISSUE THREAD

**Issue by janickvwcotiss** [Automattic/mongoose#12069]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

18.2.0

### MongoDB server version

5.0.9

### Description

Hi there, my issue is to do with typescript.

The issue I am having is that when creating a document schema with timestamps enabled the inferred document type doesn't have the corresponding `createdAt` and `updatedAt` fields present.

This means that when querying documents through the schema typescript will throw the property doesn't exist on type issue for the `createdAt` and `updatedAt` fields.

Hope this is pretty simple to understand, I've done my best to proved a good code example to best explain the issue I am having.

I realised mongoose has just recently migrated to typescript and isn't fully feature complete yet so appreciate any help.

P.s. I realise I haven't manually typed the interface for the schema e.g. `new Schema<IDocument>` and `export const Document = model<IDocument>('Document', DocumentSchema);` this is because we are migrating our whole code base to typescript and would ideally like to save some time by using `InferSchemaType`. But obviously open to any ideas even if it'll end up requiring typing the interfaces manually.

Thanks.

### Steps to Reproduce

```typescript
import { Schema, model, Model, InferSchemaType } from 'mongoose';

const DocumentSchema = new Schema(
  {
    url: { type: String, required: true, unique: true },
    fileSize: { type: Number, required: true },
    mimeType: { type: String, required: true },
    fileName: { type: String, required: true },
  },
  {
    timestamps: true,
  }
);

// Document comes out as
// const Document: Model<{
//   url: string;
//   fileSize: number;
//   mimeType: string;
//   fileName: string;
// }, {}, {}, {}, any>
export const Document: Model<InferSchemaType<typeof DocumentSchema>> = model(
  'Document',
  DocumentSchema
);

async function findDocument(id: string) {
  // Document without timestamp in query
  const doc1 = await Document.findById(id);
  if (doc1) {
    console.log(doc1.createdAt); // Error: "Property 'createdAt' does not exist on type 'Document...'"
    console.log(doc1.updatedAt);// Error: "Property 'updatedAt' does not exist on type 'Document...'"
  }

  // With timestamp in query
  const doc2 = await Document.findById(id, undefined, { timestamps: true });
  if (doc2) {
    console.log(doc2.createdAt); // Error: "Property 'createdAt' does not exist on type 'Document...'"
    console.log(doc2.updatedAt); // Error: "Property 'updatedAt' does not exist on type 'Document...'"
  }
}
```

### Expected Behavior

Expect the Document to have the timestamp fields present on the returned type.

**Comment by jamesholcomb** [comment]
I am also converting a project to TS and experiencing this, however, an explicit interface seems to cause the same issue.

```js
import { model, Schema } from "mongoose"

interface IPost {
  title: string
}

const postSchema = new Schema(
  {
    title: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
)

const Post = model<IPost>("Post", postSchema)

Post.create({ title: "foo" }).then((post) => {
  console.log(post._id)
  console.log(post.createdAt) // property 'createdAt' does not exist on type 'Document<unknown, any, IPost> & IPost & { _id: ObjectId; }'.
})
```

Being a bit of TS noob, is there a workaround that does not require @ts-expect-error everywhere?  It is reproducible in every 6.x release I tried.

**Comment by janickvwcotiss** [comment]
> 



> I am also converting a project to TS and experiencing this, however, an explicit interface seems to cause the same issue.
> 
> ```js
> import { model, Schema } from "mongoose"
> 
> interface IPost {
>   title: string
> }
> 
> const postSchema = new Schema(
>   {
>     title: {
>       type: String,
>       required: true,
>     },
>   },
>   {
>     timestamps: true,
>   }
> )
> 
> const Post = model<IPost>("Post", postSchema)
> 
> Post.create({ title: "foo" }).then((post) => {
>   console.log(post._id)
>   console.log(post.createdAt) // property 'createdAt' does not exist on type 'Document<unknown, any, IPost> & IPost & { _id: ObjectId; }'.
> })
> ```
> 
> Being a bit of TS noob, is there a workaround that does not require @ts-expect-error everywhere? It is reproducible in every 6.x release I tried.

I know this isn't ideal but might help with your typescript errors until this is fixed in the next milestone?
```typescript
interface IPost {
  title: string
  createdAt: Date;
  updateAt: Date;
}

const postSchema = new Schema(
  {
    title: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
)

const Post = model<IPost>("Post", postSchema)

Post.create({ title: "foo" }).then((post) => {
  console.log(post._id)
  console.log(post.createdAt) // (property) IPost.createdAt: Date
})
```

**Comment by Uzlopak** [comment]
@mohammad0-0ahmad

**Comment by mohammad0-0ahmad** [comment]
https://github.com/Automattic/mongoose/pull/12122

**Comment by shoeferlin** [comment]
Experiencing the same issue. Looking forward to a fix!

**Comment by neocameback** [comment]
Could you try to access with following
`post['createdAt']` 
instead of 
`post.createdAt `

**Comment by janickvwcotiss** [comment]
> neocameback

Doesn't make a difference

**Comment by janickvwcotiss** [comment]
> Could you try to access with following `post['createdAt']` instead of `post.createdAt `

Doesn't make a difference

**Comment by Adizbek** [comment]
For quick fix, you can try to use `SchemaTimestampsConfig`
![image](https://user-images.githubusercontent.com/10253982/195974525-6b8cde92-634a-491a-8ec6-5d37c5281a8c.png)

**Comment by Roji89** [comment]
it's 2023 and still i have the same problem,
how did you finally resolve it?

**Comment by Michstery** [comment]
Personally I just solved mine by delegating the object type( i.e Object being called from the model) to any instead ObjectId in my code
