### ISSUE TITLE
When the `_id` field is specified in the schema definition, the type of `_id` field cannot be correctly inferred in the HydratedDocument, perhaps due to incorrect implemention of `Require_id`

### ISSUE THREAD

**Issue by Starrah** [Automattic/mongoose#12070]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.3

### Node.js version

16.15.1

### MongoDB server version

This issue have no relevance to MongoDB server.

### Description

When the `_id` field is specified in the schema definition, eg, `new Schema({_id: String})`, the type of `_id` field cannot be correctly inferred in the `HydratedDocument` (the type returned by `new Model` or `await Model.findOne`). 

Please see the "Steps to Reproduce" section for reproducing code. 

I think that the bug is perhaps due to incorrect implemention of `Require_id`: https://github.com/Automattic/mongoose/blob/3445d240886e508962d7dd6a8481715a3cb373da/types/index.d.ts#L111-L115. 

Sorry that I'm not excellent in Typescript, but what does `U extends any` here mean?
As far as I know, everything extends any? so the contiditional clause (T & { _id: Types.ObjectId }) is always used, and the clause T & Required<{ _id: U }> is never used.

Thus, `_id` will be always infered with type ObjectId, even if I have defined another type such as String in the Schema definition.

The issue have been previously discussed at https://github.com/Automattic/mongoose/pull/11563/commits/e0d299ff545caed9dc194c3c5ce5bfdfd1fa1b4a#r915551078 with @mohammad0-0ahmad @Uzlopak, please see the link for details.

### Steps to Reproduce

The following test case demonstrates the bug:
```ts
// index.test-d.ts
import {model, Schema} from "mongoose";
import {expectType} from "tsd";

const schema_with_string_id = new Schema({_id: String, nickname: String})
const theModel = model('test', schema_with_string_id)
const obj = new theModel()

expectType<string>(obj._id)
```
when testing it with `tsd`, gives the following error: 
```
 index.test-d.ts:8:0
  ✖  8:0  Parameter type string is declared too wide for argument type string & ObjectId.
```

**Comment by vkarpov15** [comment]
Thanks for the concise bug report, fix will be in 6.4.5 next week :+1:
