### ISSUE TITLE
mongoose.Types.ObjectId error TS2554: Expected 0 arguments, but got 1. 

### ISSUE THREAD

**Issue by itxtoledo** [Automattic/mongoose#12074]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.3

### Node.js version

16.13.2

### MongoDB server version

4.4

### Description

try to convert string to object id with mongoose.Types.ObjectId

### Steps to Reproduce

```JavaScript

new mongoose.Types.ObjectId("0".padEnd(24, "0"))

```

will throw 

```
error TS2554: Expected 0 arguments, but got 1.

       new mongoose.Types.ObjectId("0".padEnd(24, "0"))
                                      ~~~~~~~~

````

### Expected Behavior

Create ObjectId javascript object

**Comment by divyeshdhokiya** [comment]
@itxtoledo were you able to resolve the issue?
