### ISSUE TITLE
types: $addFields is broken with nested fields

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#12089]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.4

### Node.js version

16.6

### MongoDB server version

5.x

### Description

In MongoDB the following are valid expressions, but throw in our TS types.
```ts
const nestedAddFieldsExpr: PipelineStage.AddFields = {
  $addFields: {
    parent: {
      nestedField: { $add: ['$a', '$b'] }
    }
  }
};
const addFieldsArrayElemAt: PipelineStage.AddFields = {
  $addFields: {
    parent: {
      child: { $arrayElemAt: ['$someArray', 0] }
    }
  }
};
```

The current types only support flat-level fields, and the only way we can achieve that is by changing it in the code to:

```ts
'parentPath.nestedPath': { $add: [1, 2] }
```

### Expected Behavior
It should support nested paths.

**Comment by vkarpov15** [comment]
Looks like this was fixed by same fix as #12096 , fix will be in 6.4.5
