### ISSUE TITLE
`Model.exists` result `_id` is the document's type

### ISSUE THREAD

**Issue by iammola** [Automattic/mongoose#12094]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.3

### Node.js version

18.4.0

### MongoDB server version

5.0

### Description

Using Model.exists to check if a document exists with the specified query is meant to return the Document's `_id` if it exists and null otherwise.

But I get a TS error when accessing the `_id` because it's not the expected value type.

When I read the types to understand the error in these lines, https://github.com/Automattic/mongoose/blob/db1ba6e2a55a8134b99fc9074597ba2d5219e8b9/types/models.d.ts#L308-L313
The first parameter in the `Document` class is expected to be `_id`'s type. But the `T` variable that's passed is the Schema's resolved type.
https://github.com/Automattic/mongoose/blob/db1ba6e2a55a8134b99fc9074597ba2d5219e8b9/types/document.d.ts#L13-L23

---

From the [documatation](https://mongoosejs.com/docs/api/model.html#model_Model-exists),
> Under the hood, `MyModel.exists({ answer: 42 })` is equivalent to `MyModel.findOne({ answer: 42 }).select({ _id: 1 }).lean()`

So the `RequireOnlyTypedId` type could be better to use as the `Model.exists` return type because the `_id` property always exists and the returned document is always a POJO unless it's not found then `null`.
https://github.com/Automattic/mongoose/blob/db1ba6e2a55a8134b99fc9074597ba2d5219e8b9/types/index.d.ts#L117-L119

Then the method definition would be something like,
```ts
exists(filter: FilterQuery<T>, callback: Callback<RequireOnlyTypedId<T> | null>): QueryWithHelpers<RequireOnlyTypedId<T> | null, HydratedDocument<T, TMethodsAndOverrides, TVirtuals>, TQueryHelpers, T>; 
exists(filter: FilterQuery<T>): QueryWithHelpers<RequireOnlyTypedId<T> | null, HydratedDocument<T, TMethodsAndOverrides, TVirtuals>, TQueryHelpers, T>; 
```

### Steps to Reproduce

```ts
const schema = new mongoose.Schema({ name: String });
const Model = mongoose.model('Model', schema);

Model.exists({ name: "Hey!" }).then(doc => {
  if (doc != null) {
    const ID: mongoose.Types.ObjectId = doc._id;
    // Type '{ name?: string | undefined; } | undefined' is not assignable to type 'ObjectId'.
    // Type 'undefined' is not assignable to type 'ObjectId'.ts(2322)
  }
});
```

### Expected Behavior

For the `_id` property to be the Document's `_id` type not the entire document type.

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new mongoose.Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const User = mongoose.model<IUser>('User', userSchema);

run().catch(err => console.log(err));

async function run() {
  // 4. Connect to MongoDB
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const user = new User({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await user.save();

  console.log(user.email); // 'bill@initech.com'
  User.exists({ name: 'Bill' }).then(doc => {
    if(doc != null) {
      const ID : mongoose.Types.ObjectId = doc._id;
    }
  });
}
```
