### ISSUE TITLE
lean transform doesn't work

### ISSUE THREAD

**Issue by Hagriel** [Automattic/mongoose#12093]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.4

### Node.js version

18.5

### MongoDB server version

5.0.9

### Description

lean transform doesn't work

### Steps to Reproduce

```
this.favoriteList
      .find({ })
      .lean({
        transform: (doc) => {
          delete doc._id;
          return doc;
        }
      });
```

**Comment by IslandRhythms** [comment]
Can you please show me what you expect the document to look like?

**Comment by Hagriel** [comment]
@IslandRhythms I expect to see this behavior, but in fact, _id is present

it('allows a transform option for lean on a query gh-10423', async function() {
    const testSchema = new mongoose.Schema({
      name: String
    });
    const Test = db.model('gh10423', testSchema);
    await Test.create({name: 'foo'});
    const result = await Test.findOne().lean({ transform: (doc, ret) => {
      delete ret._id;
      return ret;
    }});
    assert.equal(result._id, undefined);
  });

**Comment by Hagriel** [comment]
this example from https://github.com/Automattic/mongoose/pull/11814/commits/0044913813610767da07d9f9874731eed137d5a4
