### ISSUE TITLE
 Converting all ObjectIds/Dates into string on Mongoose 6.x

### ISSUE THREAD

**Issue by hensansi** [Automattic/mongoose#12098]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.4

### Node.js version

16.x

### MongoDB version

4.7.0

### Operating system

Linux

### Issue

Follow up on [Converting all ObjectIds into string by using Document.toObject() method?](https://github.com/Automattic/mongoose/issues/2790)

I would like to know if it is possible to do this somehow on Mongoose 6.x. I know I can do it on the schema level as such:

```
export const userSchema = new Schema<User, UserModel>(
  {
    name: {
      type: String,
    },
    createdAt: {
      type: Date,
      transform: (value: Date): string => {
        return value ? value.toISOString() : null;
      },
    },
  },
  schemaOptions,
);
```

The problem happens when I do the same for `_id`, I assume I override or miss some of the defaults and get this:

```
"stack":"TypeError: Cannot read properties of undefined (reading 'toString')\n    at model.eval (webpack-internal:///(api)/./xxx/model.ts:23:71)\n    at ObjectId.SchemaType.applyGetters (/xxx/node_modules/mongoose/lib/schematype.js:1212:20)\n 
```

So I would prefer to do something similar to `mongoose.ObjectId.get(v => v.toString())` but at the same time I understand that it might not be possible. Could you give me some hints relative to this?

**Comment by hensansi** [comment]
Ok I found the solution while following t[his guide](https://mongoosejs.com/docs/guide.html#toJSON)

I didn't set the getters as true,

```
const schemaOptions: SchemaOptions = {
  timestamps: true,
  toJSON: { getters: true, virtuals: false },
};
```

After adding that to the schema, adding `Schema.Types.ObjectId.get((v) => v.toString());` works

**Comment by vkarpov15** [comment]
@hensansi can you please provide the code that triggers the error you pasted?

**Comment by hensansi** [comment]
@vkarpov15 sorry I was on vacation so I let this issue drag. I will try to create an auto contained example during this week.

**Comment by hensansi** [comment]
I'll open this error under a different issue as soon as I find some time. I added it to my todos so I don't forget about it.

**Comment by hensansi** [comment]
I was looking into creating an example and I guess that the issue was because the _id wasn't defined and it would just hit a different kind of error because of my codebase,

https://mongoosejs.com/docs/guide.html#_id

Doing something like this solves the issues on the example, I will try to see if it solves the issue on my codebase too.

```
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    get: (value) => {
      return value ? value.toString() : value;
    },
    default: new mongoose.Types.ObjectId(),
  },
  ```
