### ISSUE TITLE
fix(types): aggregate.addFields({score: { $meta: "textScore" } })

### ISSUE THREAD

**Issue by herrerodani** [Automattic/mongoose#12096]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.4

### Node.js version

17.7.1

### MongoDB server version

5.0.9

### Description

Can't compile with Typescript

### Steps to Reproduce

aggregate.addFields({
        score: {
          $meta: "textScore"
        }
      })

gives the following typescript error:

TS2322: Type '{ $meta: string; }' is not assignable to type 'AnyExpression'.
  Object literal may only specify known properties, and '$meta' does not exist in type 'any[] | NativeDate | ArrayElemAt | First | Last | Reduce | ConcatArrays | Filter | Map | ObjectToArray | ... 134 more ... | Switch'.

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new mongoose.Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const User = mongoose.model<IUser>('User', userSchema);

run().catch(err => console.log(err));

async function run() {
  // 4. Connect to MongoDB
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const user = new User({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await user.save();

  User.aggregate().addFields(
    { name: { $meta: "Bill" }}
  );
}
```
