### ISSUE TITLE
Module not found: Error: Can't resolve mongoose module from node_modules using node moduleResolution

### ISSUE THREAD

**Issue by smiley-geek** [Automattic/mongoose#12097]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.4

### Node.js version

16.14.2

### MongoDB version

5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04 

### Issue

When building the app, the build fails as mongoose module cannot be resolved.
It's not a webpack thing as tsc is erroring too...
I'm using node moduleResolution but it cannot find mongoose in the node_modules.
I have reinstalled the modules, installed @types/mongoose, restarted vs-code/ typescript-server  but no changes.

Errors when using webpack

![Screenshot from 2022-07-12 11-29-35](https://user-images.githubusercontent.com/85384821/178449043-7e5d0bee-a3cb-48d0-9c32-4bf9256a165f.png)

Errors when using tsc

![Screenshot from 2022-07-12 11-40-05](https://user-images.githubusercontent.com/85384821/178449132-6c7cbf61-9490-470d-a615-680a96db0813.png)

My tsconfig

![Screenshot from 2022-07-12 11-30-06](https://user-images.githubusercontent.com/85384821/178449088-7d2b342d-301b-458e-ba12-c4b3f2b6bafa.png)

Package.json

![Screenshot from 2022-07-12 11-46-54](https://user-images.githubusercontent.com/85384821/178449889-3958cb77-ae88-4458-a994-ecb9e4fef9b4.png)

One of the schemas having an error

![Screenshot from 2022-07-12 11-30-49](https://user-images.githubusercontent.com/85384821/178449120-46ae316a-7e3d-470c-a01b-6de3da312806.png)

**Comment by vkarpov15** [comment]
@smiley-geek please provide a more complete code sample. In text form, not screenshots.
