### ISSUE TITLE
Typescript aggregation with $match: fails

### ISSUE THREAD

**Issue by SHAGGYER** [Automattic/mongoose#12106]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.2.9

### Node.js version

16.x

### MongoDB server version

5.x

### Description

While aggregating a model, I get an error `Type 'ObjectId' is not assignable to type 'Expression'.` whilst adding the code I wrote in the "Steps to Reproduce" section.

### Steps to Reproduce

```
import mongoose, { Document } from "mongoose";

export interface IForum extends Document {
  name: string;
  description: string;
  position: number;
  createdAt: Date;
  updatedAt: Date;
}

const ForumSchema = new mongoose.Schema<IForum>(
  {
    name: String,
    description: String,
    position: Number,
  },
  {
    timestamps: true,
  }
);

const Forum = mongoose.model<IForum>("Forum", ForumSchema, "forums");
export default Forum;

```

```
    const id = new mongoose.Types.ObjectId(req.params.id)
    const forums = await Forum.aggregate([
      {
        $match: {
          _id: id // here is the error
        },
      },
      {
...
```

### Expected Behavior

No error.

**Comment by vkarpov15** [comment]
It looks like this issue was fixed in 6.4.3 with https://github.com/Automattic/mongoose/commit/9f3f8ebb951a37cdb43934c38e6501782e35fa2f . Please upgrade to 6.4.3 for the fix :+1:
