### ISSUE TITLE
bulkSave should take document.$__.saveOptions.timestamps into account

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#12117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

re #12059 
Now we enabled the possibility to set `timestamps` option on all documents, it'd be nice if we can allow people to set `timestamps` option on each individual document, and send all the write operations at once.

### Motivation

To enable people to have more control over which documents get timestamps and which ones don't.

**Comment by vkarpov15** [comment]
The question is how to enable/disable timestamps on a given document.

I'm thinking that we should add a `$timestamps()` method that is a getter/setter around `this.$__.saveOptions.timestamps`. So

```javascript
// Equivalent to `doc.save({ timestamps: false })`
doc.$timestamps(false);
await doc.save();
```

`$timestamps()` will also affect `bulkSave()` and `insertMany()`, so you can call `bulkSave()` on one document with timestamps enabled and another document with timestamps disabled.

For now, to avoid breaking changes, we'll avoid setting `$timestamps` on any query results. For example, you can do `const doc = await Model.findOneAndUpdate({}, { name: 'foo' }, { timestamps: false })`. In this case, `doc.$timestamps() == null` should be true for now. I'm not 100% convinced that `findOneAndUpdate()` with `timestamps: false` should mean that subsequent `save()` calls run with `timestamps: false`. But this behavior could break someone's code, so we'll leave `doc.$timestamps() == null` for all query results.

What do you think @AbdelrahmanHafez ?

**Comment by AbdelrahmanHafez** [comment]
Sounds good.

I agree that `findOneAndUpdate()` with `timestmaps: false` shouldn't affect the document state, this option should only be set for the query and not mutate the document itself.
