### ISSUE TITLE
mongoose\types\connection.d.ts has incorrect definition for model

### ISSUE THREAD

**Issue by bradleysimard** [Automattic/mongoose#12129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm using mongoose 6.4.5, for reference.

When defining a model directly against the global mongoose reference, the type checking works perfectly fine. Here's an example lifted right out of your documentation:

```
const kittySchema = new mongoose.Schema({
        name: String
    });

const Kitten = mongoose.model('Kitten', kittySchema);
const fluffy = new Kitten({ name: 'fluffy' });
await fluffy.save();
```

If I look at the fluffy instance, I can properly see my schema:
![image](https://user-images.githubusercontent.com/97182063/179983901-41f20dca-a8fb-444f-8247-a6da178dbe13.png)

I can also see the definition of the .save() method:
![image](https://user-images.githubusercontent.com/97182063/179984025-262528b6-9dba-47f1-b815-3d40783e16e0.png)

Now, when I'm trying to define a model against a specific connection (which to me, seems like a more likely situation people would be using this), the type checking does not work properly. Here's an example based on the first example:

```
const connection = await mongoose.createConnection(`mongodb://localhost:27017`).asPromise();
const doggySchema = new mongoose.Schema({
    name: String
});
const Doggy = connection.model('Doggy', doggySchema);
const barky = new Doggy({ name: 'barky' });
await barky.save();
```

If I look at my barky instance, my schema is not visible (type is "any"):
![image](https://user-images.githubusercontent.com/97182063/179985218-93d13b1a-c231-4428-9560-7737fa534c5b.png)

Which also means that the definition of the .save() method is also "any":
![image](https://user-images.githubusercontent.com/97182063/179985351-1032c420-267e-42b7-a4d0-52ffd49b194f.png)

My current workaround is to take the type definition of model from node_modules\mongoose\types\index.d.ts and replace the definition of model in mongoose\types\connection.d.ts. This makes it work, but I'm sure it's not the proper way to do it.

**Comment by hasezoey** [comment]
The reason probably is that the `model` type for `connection` is still the old "plain" type, not the updated type from PR #11563
