### ISSUE TITLE
Typing issues: FilterQuery<T> and UpdateQuery<T> do not give appropriate errors

### ISSUE THREAD

**Issue by jsrozner** [Automattic/mongoose#12127]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.5

### Node.js version

16.14.2

### MongoDB version

5.0.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2

### Issue

```ts
import {Schema, model, Types} from 'mongoose';

// User Object
export interface IUser {
    _id: Types.ObjectId;
    userName: string;
    email: string;
    age: number;
}
const userSchema = new Schema<IUser>({
    userName: {
        type: String,
        required: true,
        unique: true
    },
    email: {
        type: String,
        required: true,
        unique: true,
    },
    age: {type: Number}
});
const User = model<IUser>('User', userSchema);
// end User Object

// Call Object
export interface ICall {
    _id: Types.ObjectId;
    callID: string;
    user: Types.ObjectId;
}
const callSchema = new Schema<ICall>( {
    callID: {
        type: String,
        required: true,
        unique: true
    },
    user : {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: true
    }
});
const Call = model<ICall>('Call', callSchema);
// end call object

// Example issues:
const updateUserOne = async (username: string) => {
    const user = await User.findOne(
        {userName: 'myuser',            // BUG: does not trace userName back to IUser
             wrongField: 'test'});          // BUG: doesn't complain that wrongField is not on IUser
    user.email = 'newemail';           // OK: *does* identify email correctly as a field on IUser
    user.invalidField = 'invalid';      // OK: correctly gives error
    user.age = 'hello';                     // OK: gives error that number and string types do not match
    user.save();
}

const updateUserTwo = async (username: string) => {
    const user = await User.findOneAndUpdate(
        {userName: 'myuser',             // BUG: same as above
            wrongField: 'test'},             // BUG: same as above
        {email: 'newemail',                 // BUG: does not identify that email is part of IUser
                wrongField: 'test',          // BUG: does not complain that wrongField is not on IUser
                age: 'notanage'}            // BUG: does not complain that age is of type string and not type number

    );
}

const getCallInfo = async (callID: string) => {
    const call = await Call.findOne(
        {callID: 'callID_123',                           // BUG: doesn't recognize callID as a field on ICall
            badField: 'wrongdata'})                // BUG: doesn't give error that badField is not on ICall
    const callWithUser = await call.populate<{user: IUser}>('user');
    console.log(callWithUser.user.wrongField); // OK: correctly identifies error that wrongField is not in IUser

    // BUG: doesn't say that invalidField does not exist on ICall
    const callWithWrongField = await call.populate<{invalidField: IUser}>('user');
    // (assumes that callWithWrongField.invalidField is of type IUser)
}
```

As noted in the comments ("BUG"), I cannot get typing to behave as I expect:
- FilterQuery and UpdateQuery do not appropriately trace fields back to the interface definition nor do they produce errors in the above code. This is true both for ts-node compilation of this file and for jetbrains webstorm automatic typing issue identification
- populate does fails to identify attempts to populate invalid fields

This is an issue because
- I don't get type errors for invalid field names
- when I use renaming features of the code editor, the UpdateQuery and FilterQuery params are not matched so after rename, e.g., `find()` calls will silently fail.

Am I doing something wrong? Is there a way to get the typing to work? Or is there another way to deal with this?

One possible workaround is to define the FilterQuery and UpdateQuery as types `Partial<IUser>` but that's a lot of extra code writing?

**Comment by jsrozner** [comment]
For the `find()` and `findAndUpdate()` type queries, if I separate the code into two pieces, e.g., 
```
const filter : FilterQuery<IUser> = {// filters here};
const update : Partial<IUser> = {//field updates here};
await User.findOneAndUpdate(filter, update);
```
Then I get all the correct expected type behaviors. So two more observations:
1) The first issue (with filter) might be with my code editor (webstorm) rather than an issue with typescript. VScode seems to appropriately match the `FilterQuery` argument correctly.

2) Update might not ever actually complain because `UpdateQuery<T>`allows arbitrary fields in the type definition (`[other: string]: any`)

But there must be some better way to handle all of this?

**Comment by vkarpov15** [comment]
The problem is that, for example, the `findOneAndUpdate()` you suggested is almost perfectly valid in Mongoose:

```ts
const user = await User.findOneAndUpdate(
        {userName: 'myuser',             // OK: userName is the expected type
            wrongField: 'test'},             // OK: Mongoose either strips the key out or allows the key through depending on `strictQuery`
        {email: 'newemail',                 // OK: `email` is the expected type
                wrongField: 'test',          // OK: Mongoose either strips the key out or allows the key through depending on `strict`
                age: '42'}                       // OK: Mongoose casts string '42' to number 42

    );
```

Mongoose does a lot of neat type casting and data cleanup at runtime, but it does make it tricky to determine the exactly right set of compile time types that are "valid" for whatever your definition of valid is. For example, technically `age` can be a number, a `Number`, a string that contains a number, or an object with a `valueOf()` function that returns a number, and Mongoose will convert it to a number at runtime.

If you want extra strictness, you unfortunately need to add it yourself.
