### ISSUE TITLE
Incorrect aggregation types for $group since 6.4.0

### ISSUE THREAD

**Issue by Naeoth** [Automattic/mongoose#12149]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.6

### Node.js version

16.15.0

### MongoDB server version

5.0

### Description

The type changed on the 6.4.0: https://github.com/Automattic/mongoose/commit/f57e007c297a9725327a13af749b3eb2407bf121#diff-46be1d2c4ab7acfb5007f7bcccbf3d2e9551597d0bd0d91cc0400a4faffb76cfR116-R118

and gives an error on a valid mongoDB aggregation query.

```
error TS2769: No overload matches this call.
  Overload 1 of 2, '(pipeline?: PipelineStage[], options?: AggregateOptions, callback?: Callback<T[]>): Aggregate<T[]>', gave the following error.
    Type 'string' is not assignable to type 'Record<string | number | symbol, never>'.
  Overload 2 of 2, '(pipeline: PipelineStage[], callback?: Callback<T[]>): Aggregate<T[]>', gave the following error.
    Type 'string' is not assignable to type 'Record<string | number | symbol, never>'.

50         count: { $count: "$value" },
```

For a group the type should be as before:
```javascript
$group: { _id: any } | { [key: string]: { [op in AccumulatorOperator]?: any } }
```

### Steps to Reproduce

```typescript
Model.aggregate([
    {
      $group: {
        _id: "$createdAt",
        count: { "$count": "$value" },
      },
    },
 ])
 ```

**Comment by Naeoth** [comment]
@vkarpov15 

I just test on 6.5.1, but your MR doesn't fix the bug.

The Group interface is declared like that:
```
    export interface Group {
      /** [`$group` reference](https://docs.mongodb.com/manual/reference/operator/aggregation/group) */
      $group: { _id: any } | { [key: string]: AccumulatorOperator }
    }
```

but the mongoDB documention describes:
```
    {
      $group:
        {
          _id: <expression>, // Group key
          <field1>: { <accumulator1> : <expression1> },
          ...
        }
     }
 ```
 
 So mongoose should have something like:
 ```
    export interface Group {
      /** [`$group` reference](https://docs.mongodb.com/manual/reference/operator/aggregation/group) */
      $group: { _id: any } | { [key: string]:  { [op in AccumulatorOperator]?: any } } }
    }
```

**Comment by vkarpov15** [comment]
@Naeoth I took a closer look and the typings as written are correct, and do support the syntax described in the MongoDB documentation. `{ [key: string]: AccumulatorOperator }` is more correct because MongoDB doesn't support multiple accumulator expressions on one field. Multiple accumulators throw "The field 'field-name-here' must specify one accumulator"
