### ISSUE TITLE
add esm support

### ISSUE THREAD

**Issue by imranbarbhuiya** [Automattic/mongoose#12148]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

issue #10513 was closed without fixing it. The issue is we still can't name import `Schema, model`.

To fix this, we can add a new file `index.mjs`. Name export all the structures like `Schema, model`,  default exports `mongoose`, and add export map in package.json.

**Alternative**

Export all the structures in `index.js` file like 
```ts
exports.Schema = Schema
```
and it works for both cjs and esm

**Comment by vkarpov15** [comment]
Can you please provide a repro script that demonstrates the issue you're seeing?

**Comment by imranbarbhuiya** [comment]
```ts
import { Schema, model, connect } from 'mongoose';
         ^^^^^^
SyntaxError: Named export 'Schema' not found. The requested module 'mongoose' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mongoose';
const { Schema, model, connect } = pkg;
```

The issue is we can't name import them. And named imports can be easily supported by either adding an `index.mjs` file and reexporting all the classes. Or reexporting them in current `index.js` file using `exports.className = className` like this.

**Comment by IslandRhythms** [comment]
`import {Schema, model, connect} from 'mongoose';`
Typescript : 4.3.5
mongoose 6.5.1

**Comment by imranbarbhuiya** [comment]
> `import {Schema, model, connect} from 'mongoose';` Typescript : 4.3.5 mongoose 6.5.1

Are u able to run the code? or u saying typescript isn't throwing? because this isn't a ts issue but esm named import issue

**Comment by IslandRhythms** [comment]
I ran the code and got no error. Those are the versions I was using.

**Comment by imranbarbhuiya** [comment]
I've created a repro https://github.com/imranbarbhuiya/mongoose-esm-issue-repro with mongoose `6.5.1` running on node 14, 16, 18. Check the workflow to get the error message.
