### ISSUE TITLE
Make it easy to apply options to all paths in a schema

### ISSUE THREAD

**Issue by btd** [Automattic/mongoose#1215]
Hello, 

why such test in mongoose 3.4.0 failed?

``` javascript
describe('mongoose schama validator', function() {
    it('should failed if field is empty', function() {
        var Schema = mongoose.Schema({
          foo: {
            type: String,
           match: /[a-z]+/
        }});

        Schema.path('foo').doValidate('', function(err) {
            assert.ok(err instanceof ValidatorError); //err there is null
        });
    });
});
```

But `/[a-z]+/.test('') is false:

``` js
den$ node
> /[a-z]+/.test('')
false
> 
```

**Comment by isaachinman** [comment]
Seeing as it's been five years, maybe it's not even worth commenting, but I've just come across this same issue. Empty strings are literally falsey in JavaScript, what is the reasoning here? If a `String` type is required, how is it possibly conceivable that an empty string is what the developer meant by required?

**Comment by vkarpov15** [comment]
@isaachinman the general idea is that mongoose allows `null` and `undefined`, and `required` is how you tell mongoose to not allow `null` or `undefined`. `required` is about nullish values, not falsy values. For example, should we treat `false` as invalid for boolean because it is falsy? Either way, its a one-liner to make empty string invalid: `validate: v => assert.ok(v.length > 0)`

**Comment by isaachinman** [comment]
Sure, some of that makes sense. In my opinion, a "required" string would need a length greater than zero. Maybe that's too opinionated for the maintainers here though!

**Comment by mrfrase3** [comment]
Hey, 

Just found out this ~~bug~~feature after jumping up and down in rage that my patterns were being ignored. It's a tricky conumdrum, and I'd rather not have to put "one-line-fixes" all over my schema definitions. 

In saying this, I can understand that changing this functionality could break older programs, but at the same time, this could introduce security problems with devs that are unaware of this ~~bug~~feature will assume that their pattern is going to catch empty strings.

Maybe some kind of global configuration that allows one to toggle between the two options?

**Comment by isaachinman** [comment]
Agreed that `minLength` is the way to get around this, and is actually preferable as you're defining your data structure more carefully.

Disagree that `defaultMinLength` is a good idea. You could, however, do something like:

    const minLengthSchema = schema => ({ ...schema, minLength: 1 })

    myField: minLengthSchema({
        type: String,
   })

Very quick/dirty example, but you get the idea. I think this belongs in user land.

**Comment by vkarpov15** [comment]
I'm not too fond of a `defaultMinLength` option, but I'm sure there's another approach to solve this. In general, we do need a easy way to apply options to all schema types of a given type. Right now you can generally do

```javascript
schema.eachPath((path, schemaType) => {
  if (schemaType.instance === 'string') {
    schemaType.validate(v => assert.ok(v.length > 0));
  }
});
```

But I think we at least need to add some tests and docs covering this case

**Comment by mrfrase3** [comment]
I'm actually liking defaultMinLength for the reason of the inverse, defaultMaxLength, that you might as well put in there anyway if adding defaultMinLength. For most schemas, the significant majority of strings shouldn't exceed 256-512 characters, it would be much safer to set a global default in the case someone forgets to add the restriction to a field definition. (opt-out over opt-in) Obviously, you wouldn't want this enabled by default and should let the user set the upper limit based on their project.

Conversely, having an event handler of sorts when a schema is registered to add type based validators would be pretty dope.

**Comment by lineus** [comment]
@isaachinman I was looking at this again because of a related issue, and I was wondering if you can provide an example and/or versions to duplicate passing in an empty string to a required String path that doesn't fail validation. 

I realize it's been quite some time since you brought this up, but after looking at the checkRequired function on the String schemaType, the value having a truthy length is a part of the required validation going back to at least 4.9.10.

By "empty string", did you mean a string with a length of 0, or a string only containing whitespace? *I'm assuming you meant length 0, since it's the only one of the two that's falsey in javascript.*

**Comment by isaachinman** [comment]
Hi @lineus. Unfortunately I'm not sure exactly what version I was on at the time of that comment. Most likely it was `4.10.8`.

Can you link to whatever `checkRequired` function you're talking about? We've heard from @vkarpov15 directly that empty strings pass `required` validation.

And by "empty string", I do mean a string with a length of zero, not a string containing whitespace. Handling whitespace is certainly a user land concern.

**Comment by lineus** [comment]
[this is the string checkRequired function I was referring to](https://github.com/Automattic/mongoose/blob/master/lib/schema/string.js#L398)

>We've heard from @vkarpov15 directly that empty strings pass required validation.

I just always assumed this was the case myself. Another issue was opened recently saying that all required strings, including zero length strings should be considered valid, and I verified that they aren't currently, and that actually [this behavior goes back to the 2.x days](https://github.com/Automattic/mongoose/blob/2.x/lib/schema/string.js).

**Comment by isaachinman** [comment]
I just created a [basic example here](https://repl.it/repls/PastDisastrousCopyrightinfringement). @lineus is correct, an empty string is being rejected.

@vkarpov15 Can you explain when this change happened, and why it was made? This seems to be a complete reversal of your previous comments.

Specifically:

> required is about nullish values, not falsy values

**Comment by vkarpov15** [comment]
I'm going to have to investigate more, but that checkRequired function hasn't changed in over 3 years so I was incorrect in my original comment. We will add a workaround.

**Comment by vkarpov15** [comment]
See #7186

**Comment by vkarpov15** [comment]
I'm going  to close this. We added the ability to configure the `checkRequired` function in 5.4.0: http://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html , https://mongoosejs.com/docs/api.html#schematype_SchemaType-checkRequired, and OP's issue can be resolved with [`Schema#eachPath()`](https://mongoosejs.com/docs/api.html#schema_Schema-eachPath)
