### ISSUE TITLE
Document.prototype.$set doesn't work per the documenation when passing path as an object of key/value pairs

### ISSUE THREAD

**Issue by randy5235** [Automattic/mongoose#12157]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.4

### Node.js version

16.x.x

### MongoDB server version

4.2

### Description

The document.set documentation allows for passing either (path: string, value: string, type: string, options: object)
or
(path: object, type: string, option: object)
or 
(path: object, options: object)

with type always optional.

It currently ignores passing path as an object.

### Steps to Reproduce

```
const mongoose = require('mongoose');
const connection = mongoose.connect('connectionString');

const testSchema = new mongoose.Schema({
  email: String,
  name: String,
});

const Test = mongoose.model('Test', testSchema);

// insert a couple of records doesn't really matter what

const myUser = Test.find({_id: <id from generated record>});
// This doesn't work as expect
myUser.set( { path1 : 'Value', path2: 'Value'}, {strict: false});
// setting them like this does
myUser.set('path1', 'Value', {strict: false});
myUser.set('path2', 'Value', {strict: false});



### Expected Behavior

Expected behavior:

Expectation is that the documented behavior is honored.

**Comment by randy5235** [comment]
I opened this PR to resolve this behavior: https://github.com/Automattic/mongoose/pull/12158

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);
const testSchema = new mongoose.Schema({
  email: String,
  name: String,
});

const Test = mongoose.model('Test', testSchema);


async function run() {
    // insert a couple of records doesn't really matter what
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    const user = await Test.create({ name: 'Test Testerson', email: 'test@localhost.com'})
    const myUser = Test.find({ _id: user._id });
    // This doesn't work as expect
    myUser.set( { path1 : 'Value', path2: 'Value'}, {strict: false});
    // setting them like this does
    myUser.set('path1', 'Value', {strict: false});
    await myUser.set('path2', 'Value', {strict: false});
    console.log(await Test.findOne());
}

run();

```

**Comment by IslandRhythms** [comment]
Could also be a duplicate of #12155

**Comment by randy5235** [comment]
I'm closing this. After rereading the code that is in place. I suspect that my interpretation of the signature:
.set({key: value}, {options.values}) is incorrect. I see internally this gets called with `.set({key:value}, undefined, {options.values}` I may submit an update for the documentation to make this more clear, *assuming* that my current understanding is correct.
