### ISSUE TITLE
 Intermittently getting MongooseServerSelectionError: Server selection timed out after 30000 ms  for huge payloads/ lot of requests

### ISSUE THREAD

**Issue by Vinayjinugu-gep** [Automattic/mongoose#12165]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.0

### Node.js version

16.14.0

### MongoDB version

4.5.0

### Issue

I have an api which receives a lot of requests, recently the execution of the operations has become costly due to heavy payloads. Whenever I receive a lot of requests at the same time (CPU usage of the nodejs application increases drastically) the established/ saved mongoose connection gets disconnected and then later I am receiving mongooseServerSelection error. 

When I send a few requests it works perfectly fine without any issues. Whenever I try to test it by sending it lots of requests using jmeter it just gets mongooseServerSelectionError connection timedout after 30000ms in the reponse. 

I tried to find out why the mongoose connection(*SRV*) is getting disconnected in between the requests but I am unable to find anything, it just disconnects if the api receives a lot of requests. 

I have read that the mongoose connenction might get disconnected due to [network inactivity](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html) but I don't understand how to resolve it. If I create a new connection every time the existing connection disconnects, what kind of impact does it have on the ongoing transactions or session?

I tried changing the parameters keep-alive, keepAliveInitialDelay, connectTimeoutMS, socketTimeoutMS to different set of values to see if it would stop the mongoose connection from disconnecting but there is no use.  We need more than one connection open at a time since there is more than one client who tries to access the DB.
````
conn = mongoose.createConnection(dbConnection, {
    keepAlive: true, keepAliveInitialDelay: 1,
    connectTimeoutMS: 0, socketTimeoutMS: 0
});
conn.on('connected', function () {
    console.info('Mongoose connection open');
});

conn.on('disconnected', function () {
    console.info('mongoose connection got disconnected')
    mongoose.connections.forEach(theConn => {
        const models = theConn.modelNames();
        models.forEach(model => {
            theConn.deleteModel(model);
        })
        const collections = Object.keys(theConn.collections)
        collections.forEach(collection => {
            delete theConn.collections[collection];
        })
    })
});

conn.on('error', function (err) {
    console.error('Mongoose ' + err + ' Error');
});
```
`


Any possible solutions to the resolve the problem? Thanks In advance

**Comment by Vinayjinugu-gep** [comment]
@vkarpov15 can you please help me out here.

**Comment by deistermatheus** [comment]
A few things that might help you out:

- Increase your maxPoolSize setting on the connection. Mongo can only execute one operation per socket at a time, so if you have a low pool size, slow operations hanging will essentially block everything else from running until they complete.

- Increase serverSelectionTimeoutMS (how long the driver keeps trying to send some operation to mongo) and decrease maxTimeMS (how long the driver can be busy executing a single query), it may help finding out which operations are slow on the database side.

- Since you're load testing your project and recorded high CPU usage, node.js may be too busy serializing/deserializing those huge payloads and looks unresponsive to asynchronous code, such as connection managers. If nothing works or you find out that MongoDb is not the bottleneck, I'd look into running more than one instance of the API with a load balancer or worker threads.

**Comment by Vinayjinugu-gep** [comment]
> 

Hey @deistermatheus , Thanks for the reply.

- Regarding the first point. The maxPoolSize we are using is 100. Which is the default value given by the mongoose. We are using way less connections than the maxPoolSize for an instance.
- I have tried increasing the serverSelectionTimeoutMS but it didn't have any effect at all. We are already using maxTimeMs for the query we have set it to 5000ms.
- We are already using multiple instances using pm2 but increasing the no of instances didn't have any effect. Although it decreases the load per process.

I have used heartBeatFrequencyMs, minHeartBeatFrequencyMs, maxIdleTimeMs recently. None of them have made any visible difference. If the number of requests are less it works properly. As soon as I increase the no of requests, the established mongoose connection disconnects at some point. By the time the mongoose connection reconnects all the requests that are in the middle of the execution gets the mongooseServerSelectionError. 

something is pushing the mongoose connection to disconnect. I am not able to figure out what.

If you have any more ideas that I could try that would be great. Thanks

**Comment by Vinayjinugu-gep** [comment]
Can the nodejs http server disconnect the existing mongo connection. If the number of tcp/ http connections are high? @deistermatheus

**Comment by Vinayjinugu-gep** [comment]
Whenever the number of tcp connections increase/ open at a point in time (we call external api's(https calls) during the api request). The existing mongoose connections are disconnected at that point in time. How to stop them from disconnecting. Does nodejs has a hard limit to close the no of open connections at a point in time? How can we handle it?

**Comment by vkarpov15** [comment]
Why do you delete all models and collections in your 'disconnected' handler?

```javascript
conn.on('disconnected', function () {
    console.info('mongoose connection got disconnected')
    mongoose.connections.forEach(theConn => {
        const models = theConn.modelNames();
        models.forEach(model => {
            theConn.deleteModel(model);
        })
        const collections = Object.keys(theConn.collections)
        collections.forEach(collection => {
            delete theConn.collections[collection];
        })
    })
});
```

Keep in mind that the disconnected handler is just for monitoring/debugging. You shouldn't have to do any sort of connection management in the disconnected handler in Mongoose `>= 6.0.0`.

Beyond that, it is really hard for us to tell what's going on without a more complete code sample. I can offer some suggestions, but these suggestions are more guesses than anything.

1. Make sure you are **not** setting `waitQueueTimeoutMS`.
2. The http server can't cause a MongoDB connection to disconnect as far as I know, at least unless it crashes the process
3. Register event handlers for `MongoClient`'s 'topologyDescriptionChanged' event: `mongoose.connection.client.on('topologyDescriptionChanged', ev => { /* log `ev` */ })`. What happens to `ev` when your process is disconnected? May provide some insight.

**Comment by Vinayjinugu-gep** [comment]
@vkarpov15 can you let me know how I can debug the issue. With topologyDescriptionChanged, all the difference I could find before the connection disconnects is this.
`{
        "newDescription": {
            "commonWireVersion": 9,
            "compatible": true,
            "heartbeatFrequencyMS": 10000,
            "localThresholdMS": 15,
            "logicalSessionTimeoutMinutes": 30,
            "maxElectionId": "xxxx", //changed this line 
            "maxSetVersion": 36,
            "servers": {},
            "setName": "atlas-xxxx-shard-0", // changed the line
            "stale": false,
            "type": "ReplicaSetNoPrimary"
        },
        "previousDescription": {
            "commonWireVersion": 9,
            "compatible": true,
            "heartbeatFrequencyMS": 10000,
            "localThresholdMS": 15,
            "logicalSessionTimeoutMinutes": 30,
            "maxElectionId": "xxxx", // Changed the line
            "maxSetVersion": 36,
            "servers": {},
            "setName": "atlas-xxxx-shard-0", // changed the line
            "stale": false,
            "type": "ReplicaSetWithPrimary"
        },
        "topologyId": 0
    }`

**Comment by vkarpov15** [comment]
I'd recommend not opening a connection every time you get a disconnected event. The 'disconnected' event is purely for monitoring and debugging, there's no need to open a new connection.

There's far too many potential causes for disconnects for me to venture a guess without more information. The only thing that `topologyDescriptionChanged` really tells me is that the MongoDB driver lost connectivity to the primary for some reason.

Can you please clarify what you mean by "I see a significant change in the no of existing mongo connection disconnections after I limit the number of external api calls made through axios get( [axios](https://github.com/axios/axios) is the npm package I use to call external apis)."?

**Comment by Vinayjinugu-gep** [comment]
I am not opening a connection for disconnected event currently but when a  new request arrives. It checks if the existing connection is in connected| connecting state(using readyState variable). If it's not in connected state then I am opening a new connection. Is there a better way to handle connections? other than opening a new connection if the old connection is in disconnected state?
```
static isConnectionAlreadyOpen(uniqueClientId: string): boolean {
    let existingDbConnection: mongoose.Connection = className.connections[uniqueClientId]; // className.connections is where I store the connections.
    if (existingDbConnection != null) {

        if ((existingDbConnection).readyState == 1 || (existingDbConnection).readyState == 2) {
            return true;
        }
        return false;
    }

    return false;
}

establishConnection(uniqueClientId) {
    if (className.isConnectionAlreadyOpen(uniqueClientId) {
        activeConnection = className.connections[uniqueClientId]
    }
    else {
            activeConnection = mongoose.createConnection(dbUrl);
            className.connections[uniqueClientId] = activeConnection;
    }
}

```
This is how I am opening a connection. Recently I have faced issues where we opened a lot of mongo connections because all the connections we opened went into disconnected state. Since, everytime I opened new connection. 

So I changed the code this way.
```
static isConnectionAlreadyOpen(uniqueClientId: string): boolean {
    let existingDbConnection: mongoose.Connection = className.connections[uniqueClientId]; // className.connections is where I store the connections.
    if (existingDbConnection != null) {

        if ((existingDbConnection).readyState == 1 || (existingDbConnection).readyState == 2) {
            return true;
        }
        existingDbConnection.destroy(function () {
            delete ConnectTo.connections[uniqueClientId];
            console.log(`existing mongoose connection with ${existingDbConnection.id} is destroyed for ${uniqueClientId} and total connections are ${mongoose.connections.length -1}`);
        });
        return false;
    }

    return false;
}
```

**Comment by vkarpov15** [comment]
"If it's not in connected state then I am opening a new connection." <-- don't do that please. In general, you should not do anything if you receive a 'disconnected' event or see that the connection is disconnected. The MongoDB Node driver will handle reconnecting on its own, if possible. Unless you're extremely careful, you can easily end up DoSing your own MongoDB server if you blast the server with new connections every time an operation times out.

**Comment by Vinayjinugu-gep** [comment]
I will update the code according to the advices you have mentioned. 

- Use existing connection opened every time a new request comes regardless of the ready state of the connection.
- Use disconnected state purely for monitoring purpose.
