### ISSUE TITLE
Allow setting compression option (e.g. to zstd) for a collection

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#12170]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

right now it's possible to e.g. set a timeseries option, or capped option,...and more ;-).
When mongoose is creating a new collection, it's considiering all these options. but there is no option for the wired tiger compression flag. actually there is no option to configure the storageEngine at all.

E.g. what I would like to specify is smth like this:
```json
{
   "storageEngine":{
      "wiredTiger":{
         "configString":"block_compressor=zstd"
   }
}
```

`db.createCollection('...', {storageEngine: {wiredTiger: {configString: 'block_compressor=zstd'}}})`

see also https://www.mongodb.com/docs/manual/core/wiredtiger/#compression

### Motivation

This helps to overcome manual steps that are required for deploying new features right now.

### Example

```
const ExampleRequestLogSchema = new Schema(
	{
		source: { type: Number, index: true }
	},
	{ compression: 'zstd' }
);
```

**Comment by vkarpov15** [comment]
Because compression is something you set on the MongoDB server process. Mongoose and other MongoDB drivers aren't allowed to configure storage engine internals as far as I know.
