### ISSUE TITLE
Mongoose doesn't reconnect after receiving specific mongo events

### ISSUE THREAD

**Issue by david-badalov** [Automattic/mongoose#12195]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.0

### Node.js version

14.19.3

### MongoDB server version

4.2.21

### Description

Recently upgraded to Mongoose 6 from 5 and getting the following behavior:

I get the following 2 events from Mongo:
`serverDescriptionChanged` with type of `Unknown`
`topologyDescriptionChanged` with type of `ReplicaSetNoPrimary`

Looking at the code in mongoose, these 2 events fall on both setting the state to `disconnected` and no reconnection is attempted:
https://github.com/Automattic/mongoose/blob/ba323df0b2c56ba76ff81bd67b4dbac5f6f78c01/lib/connection.js#L877-L915

Is there a reason why this case would require to manually initiate a reconnect?

### Steps to Reproduce

1. Start a mongoose connection
2. Receive/trigger `serverDescriptionChanged` with type of `Unknown` and `topologyDescriptionChanged` with type of `ReplicaSetNoPrimary`
3. Mongoose disconnects and no reconnect is attempted

### Expected Behavior

A reconnection would be triggered

**Comment by vkarpov15** [comment]
"Is there a reason why this case would require to manually initiate a reconnect?" No. In Mongoose 6, you never need to manually reconnect. The 'disconnected' event is just for monitoring and debugging.

What makes you think that Mongoose disconnects and no reconnect is attempted?

**Comment by david-badalov** [comment]
> "Is there a reason why this case would require to manually initiate a reconnect?" No. In Mongoose 6, you never need to manually reconnect. The 'disconnected' event is just for monitoring and debugging.
> 
> What makes you think that Mongoose disconnects and no reconnect is attempted?

After upgrading to mongoose 6 I see a recurring heartbeat failure and the aforementioned events (this does not happen with mongoose 5).
Following these events and mongoose setting the disconnected state my queries start failing:

I start getting the following errors if buffering is enabled:
```
"kind":"MongooseError","message":"Operation `-.findOne()` buffering timed out after 10000ms"
```
and a different error if it is not:
```
MongooseError: Cannot call `-.findOne()` before initial connection is complete if `bufferCommands = false`. Make sure you `await mongoose.connect()` if you have `bufferCommands = false`.
```

**Comment by vkarpov15** [comment]
I'm unable to repro this. For example, consider the following script:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => {
  console.log(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', { serverSelectionTimeoutMS: 1000 });

  const Test = mongoose.model('Test', new mongoose.Schema({ name: String }));

  console.log('Before fake disconnect', mongoose.connection.readyState, await Test.findOne());

  mongoose.connection.client.emit('serverDescriptionChanged', {
    newDescription: { type: 'Unknown' } 
  });

  console.log('After fake disconnect', mongoose.connection.readyState, await Test.findOne());
}
```

Output:

```
$ node gh-12195.js 
Before fake disconnect 1 null
After fake disconnect 0 null
^C
```

Even though Mongoose is "disconnected", the 2nd query executes fine. Remember, in Mongoose 6 the 'disconnected' event is just for monitoring and debugging. It doesn't have any impact after initial connection.

**Comment by david-badalov** [comment]
> I'm unable to repro this. For example, consider the following script:
> 
> ```js
> 'use strict';
> 
> const mongoose = require('mongoose');
> 
> run().catch(err => {
>   console.log(err);
>   process.exit(-1);
> });
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017/test', { serverSelectionTimeoutMS: 1000 });
> 
>   const Test = mongoose.model('Test', new mongoose.Schema({ name: String }));
> 
>   console.log('Before fake disconnect', mongoose.connection.readyState, await Test.findOne());
> 
>   mongoose.connection.client.emit('serverDescriptionChanged', {
>     newDescription: { type: 'Unknown' } 
>   });
> 
>   console.log('After fake disconnect', mongoose.connection.readyState, await Test.findOne());
> }
> ```
> 
> Output:
> 
> ```
> $ node gh-12195.js 
> Before fake disconnect 1 null
> After fake disconnect 0 null
> ^C
> ```
> 
> Even though Mongoose is "disconnected", the 2nd query executes fine. Remember, in Mongoose 6 the 'disconnected' event is just for monitoring and debugging. It doesn't have any impact after initial connection.

Have you tried setting both of these events?

> `serverDescriptionChanged` with type of `Unknown`
> `topologyDescriptionChanged` with type of `ReplicaSetNoPrimary`

Right now I have to check `readyState` for if the connection is disconnected and reconnect manually, otherwise my queries are failing

The connection is created with `createConnection` andis being reused - after a heartbeat failure, if the readyState is disconnected, I close the connection and recreate it for the queries to start working. Otherwise they keep failing with the error I mentioned before.
