### ISSUE TITLE
no type checking on "new" or ".create()" Model

### ISSUE THREAD

**Issue by ELI7VH** [Automattic/mongoose#12204]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6

### Node.js version

16

### MongoDB server version

5

### Description

When creating a new record, I expect typescript to notify me when I try to use an object of the incorrect type... this does not happen with `.create` or the new `Model()` or `insertMany([])`

probably others, but I  haven't checked...

### Steps to Reproduce

model definition:
```ts
type IMessage = {
  message: string
  userId: string
  username: string
  metadata?: Record<string, any>
  createdAt: Date
}

const schema = new mongoose.Schema<IMessage>({
  message: String,
  userId: String,
  username: String,
  metadata: Object,
  createdAt: { type: Date, default: Date.now },
})

export const Message = mongoose.model<IMessage>('Message', schema)
```

new instance:
```ts
const message = new Message({
  user_id: req.session.user.id, // key is incorrect 
  user_name: req.session.user.username, // field is incorrect
  message: req.body.message,
})
```
I

### Expected Behavior

I should receive typescript errors when I try and use the wrong data structure!

**Comment by Its-Just-Nans** [comment]
In https://github.com/Automattic/mongoose/blob/a50e6e2086c9440b80a7dcb8abb4e6b078808e6c/types/models.d.ts#L122

If we change like this that's fix the problem (but break some tests)

```diff
+new <DocType = T>(doc?: DocType, fields?: any | null, options?: boolean | AnyObject): HydratedDocument<T, TMethodsAndOverrides,
-new <DocType extends Partial<T> = T>(doc?: DocType, fields?: any | null, options?: boolean | AnyObject): HydratedDocument<T, TMethodsAndOverrides,
```

**Comment by vkarpov15** [comment]
Expected behavior. Mongoose does runtime type coercion, so you can technically pass in a value of any type.
