### ISSUE TITLE
fineOneAndUpdate is not accepting `hint` parameter

### ISSUE THREAD

**Issue by adityapatadia** [Automattic/mongoose#12202]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.0

### Node.js version

16.x

### MongoDB server version

4.7

### Description

When we try to use either `.hint()` or `hint` option with `findOneAndUpdate` command, mongoose throws error saying `hint is not supported with findOneAndUpdate`.

Mongodb supports `hint` option with `findAndModify` command as per their documentation: https://www.mongodb.com/docs/manual/reference/method/db.collection.findAndModify/

### Steps to Reproduce

Fire a query with `findAndModify` along with `hint` and it wiill throw an error.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: {type: String, index: true},
    age: Number
});



const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    // await mongoose.connection.dropDatabase();
    /*
    await Test.create({
        name: 'Test Testerson',
        age: 2
    });*/

    const test = await Test.findOne({}, {}, {}).hint({ name: 1});
    console.log('Test', test);
    const otherTest = await Test.findOneAndUpdate({}, {name: 'Test Testerson'}, {}).hint({name: 1});
    console.log(otherTest);
}

run();
```
Run it once with the commented out statements and then comment out the statements and run it again

**Comment by adityapatadia** [comment]
Keep open.

—
Regards,
Aditya Patadia
