### ISSUE TITLE
Intermediate issue we see from mongoose  driver uses TLS1.0 or TLS1.2 when trying to connect Mongo DB Atlas

### ISSUE THREAD

**Issue by mshetty794** [Automattic/mongoose#12209]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.8.7

### Node.js version

14

### MongoDB server version

5.0

### Description

We are seeing intermediate issue of pod crashing with error stating MongoTimeoutError: Server selection timed out after 30000 ms when it is trying to connect mongoDb Atlas. On replacing the pod it is able to connect successfully. If we again try to replace the running pod we see above error. It is intermediate, could anyone help us here. Mongoose version used is 5.8

We have whitelist of all ip via [0.0.0.0](https://0.0.0.0/) is in place and we use a m30 cluster

Below is the code snippet which we are using to connect mongo atlas

mongoose version: “mongoose”: “5.8.7”
mongo: 5.0

<<<<< code >>>>>

var options = {
useNewUrlParser: true,
useUnifiedTopology: true,
useFindAndModify:false,
connectTimeoutMS: 300000,
socketTimeoutMS:0 ,
keepAlive: 1
};

mongoose.connect(“connection string”, options, function (err) {
if (err) {
logger.critical("Error while connecting to mongoDB … ", err);
} else {
logger.info(“mongodb connected successfully.”)
}
});

let db = mongoose.connection;
db.once('open', function () {
  logger.info('MongoDB event open');
  db.on('connected', function () {
    logger.info('MongoDB event connected');
  });

  db.on('error', function (err) {
    logger.info('MongoDB event error.: ' + err);
  });
});

On further investigations below are the observations

Since this issue is reproducible all over the time, we tried packet capture between working pod and non working pod [both of same deployment version], the observation here is in the non working scenario, after the client makes TCP connection it tries to perform TLS client hello but the pod is not getting reply from the mongodb server resulting in timeout and repeated retries. In all retries the TLS client hello is sent but mongodb server is not replying back.

We further did a deep dive analysis on the packet capture and found that, when the client is making “Client Hello”, for working pods its taking TLSv1.2 protocol and in a non working its using TLSv1 protocol layer…

It is very intermediate, application fails to get connection with TLS1.0 , but with TLS1.2 is able to connect successfully

In mongo db atlas we have set TLS 1.0 and above , still the pod crashes when at run time TLS1.0 gets used.

Could someone help us here , we are clueless how to go ahead

In addition to above issue mentioned we see in logs

mongoose connect(…) failed with err: MongoNetworkError: failed to connect to server [hostname:27017] on first connect [Error: read ETIMEDOUT
at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17) {
name: ‘MongoNetworkError’,
[Symbol(mongoErrorContextSymbol)]: {}
}]
at Pool. (/home/node/app/node_modules/mongodb/lib/core/topologies/server.js:433:11)
at Pool.emit (events.js:400:28)
at /home/node/app/node_modules/mongodb/lib/core/connection/pool.js:577:14
at /home/node/app/node_modules/mongodb/lib/core/connection/pool.js:1021:9

Clearly says its a TLS issue , can some one help us here

### Steps to Reproduce

Since this issue is reproducible all over the time, we tried packet capture between working pod and non working pod [both of same deployment version], the observation here is in the non working scenario, after the client makes TCP connection it tries to perform TLS client hello but the pod is not getting reply from the mongodb server resulting in timeout and repeated retries. In all retries the TLS client hello is sent but mongodb server is not replying back.

We further did a deep dive analysis on the packet capture and found that, when the client is making “Client Hello”, for working pods its taking TLSv1.2 protocol and in a non working its using TLSv1 protocol layer…

**Comment by vkarpov15** [comment]
One potential cause of this issue is that Mongoose 5.x does **not** support MongoDB 5.x, see [compatibility matrix](https://mongoosejs.com/docs/compatibility.html). You need to upgrade to Mongoose 6, or downgrade to MongoDB server 4.4.
