### ISSUE TITLE
InterSchemaType does not properly infer "required" field for Schema.Types.ObjectId type

### ISSUE THREAD

**Issue by darwin403** [Automattic/mongoose#12205]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^6.5.0

### Node.js version

16.13.1

### MongoDB server version

6.x

### Description

A schema field  with `{type: Schema.Types.ObjectId, required: true}` cause faulty inference of Schema type. But,  `{type: Schema.Types.ObjectId, required: false}` ,  `{type: String, required: true}` seem to work

### Steps to Reproduce

The following **works**:

```js
const campaignSchema = new Schema(
  {
    client: {
      type: Schema.Types.ObjectId,
      trim: true,
      ref: "User",
      required: false,
    },
  },
  { timestamps: true }
);

type ICampaign = InterSchemaType<ICampaignSchema>; // {client?: Types.ObjectId | undefined }
```

The following **doesn't work:**

```js
const campaignSchema = new Schema(
  {
    client: {
      type: Schema.Types.ObjectId, // works when the type is changed to "String"
      trim: true,
      ref: "User",
      required: true, // fails to interpret schema
    },
  },
  { timestamps: true }
);

type ICampaign = InterSchemaType<ICampaignSchema>; // DOES NOT return {client:  Types.ObjectId }
```
![Screenshot-from-2022-08-03-09-31-43](https://user-images.githubusercontent.com/65121170/182521560-e3be899e-2d0a-44a4-85d2-d8c653e17443.png)

### Expected Behavior

```js
type ICampaign = InterSchemaType<ICampaignSchema>;  // {client:  Types.ObjectId }
```

**Comment by IslandRhythms** [comment]
What is inferModelType suppose to be?

**Comment by darwin403** [comment]
@IslandRhythms  Sorry it was a typo. I meant `InterSchemaType`, just updated the issue. The `inferModelType` is just my custom type and can be ignored. The problem I'm highlighting only concerns `InterSchemaType`

**Comment by IslandRhythms** [comment]
`Cannot find name 'InterSchemaType'`

**Comment by Uzlopak** [comment]
@mohammad0-0ahmad

**Comment by mohammad0-0ahmad** [comment]
@darwin403 has meant the following:
```TS
const campaignSchema = new Schema(
  {
    client: {
      type: Schema.Types.ObjectId, // works when the type is changed to "String"
      trim: true,
      ref: 'User',
      required: true // fails to interpret schema
    }
  },
  { timestamps: true }
);

type ICampaign = InferSchemaType<typeof campaignSchema>;
```

**Comment by mohammad0-0ahmad** [comment]
Yes, it returns a wrong result.
It related to https://github.com/Automattic/mongoose/pull/12168, I think.
@vkarpov15 would you like to reopen it, so @iammola can fix it, or what do you think ?

**Comment by ryaposov** [comment]
I can see the issue is in progress already, but just to confirm I have a similar issue even without specifying `required`.

```
...
type: {
    type: String,
    enum: ['income', 'expence', 'write-off'],
    required: true
  },
  procurementOrderId: {
    type: Schema.Types.ObjectId,
    ref: 'procurementOrders',
  },
```

Produces the following (notice `type` field resulting in `unknown`):

<img width="411" alt="image" src="https://user-images.githubusercontent.com/5815992/189523985-8393dfbb-00fc-4678-8e3e-7a54d4ae67d9.png">

Removing `procurementOrderId` field from schema makes types work again perfectly.
