### ISSUE TITLE
Extremely high number of connections on MongoDB Atlas with serverless lambda infrastructure

### ISSUE THREAD

**Issue by harishv7** [Automattic/mongoose#12219]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.4

### Node.js version

16.15.0

### MongoDB version

6.0.0

### Operating system

Linux

### Issue

I am following the guide available at https://mongoosejs.com/docs/lambda.html to avoid multiple function calls creating new connections. In particular, I am using the following method to cache my DB connection:

```
const mongoose = require('mongoose');

let conn = null;

const uri = 'YOUR CONNECTION STRING HERE';

exports.connect = async function() {
  if (conn == null) {
    conn = mongoose.connect(uri, {
        connectTimeoutMS: 10000,
        maxPoolSize: 10,
        serverSelectionTimeoutMS: 5000,
        bufferCommands: false, // Disable mongoose buffering
    }).then(() => mongoose);
    
    // `await`ing connection after assigning to the `conn` variable
    // to avoid multiple function calls creating new connections
    await conn;
  }

  return conn;
};
```

However, I am seeing extremely high number of connections on MongoDB Atlas with this setup. A typical alert looks like:

```
The connections to your cluster(s) have exceeded 500, and is nearing the connection limit
```

I have upgraded my MongoDB Atlas instance to something with more capacity (1500 max connections). I did a load test of simulating a few operations through my APIs and the connections were reaching 1000+ for just a small load.

More details

- I am using [Serverless Stack](https://sst.dev/) as the serverless framework

A typical lambda handler looks like this:

```
export const handler = async (event: APIGatewayProxyEventV2WithJWTAuthorizer) => {
  // perform some operations
  return {
    statusCode: 200,
    body: JSON.stringify({
        message: 'Go Serverless v1.0! Your function executed successfully!',
        input: event,
    }),
  }
}
```

Can someone point me in the right direction as to how I can cache the connections? Do I need to modify anything in the handler or the mongoose configs?

**Comment by jeanbmar** [comment]
I've been there :).

Keep in mind that each Lambda will create 10 connections because of the pool size.

You can try to reduce the pool size first, because your scaling will happen through Lambda anyway.

You should then consider:
- Queuing the calls generating a lot of Lambda starts. For instance, if you are building a website, make sure you are not generating more than N pages at a time, N depending from the available resources.
- If the numerous Lambda spawns happen because your Mongo queries take a lot of time to run, you could 1) use a local query cache, declared outside your Lambda handler or 2) use a third-party cache to which your Lambda will connect.

Good luck!

**Comment by harishv7** [comment]
@jeanbmar Thank you for the tips! I will attempt to reduce the `poolSize` first.

> Queuing the calls generating a lot of Lambda starts
So I am already processing the requests asynchronously. This is my current flow: 

Incoming request -> Lambda -> Lambda pushes the request into a SQS queue and returns 200 straight away -> SQS processes the requests asynchronously

However, the first step (incoming request) can be a bit volatile. There may be a sudden burst of 20,000 requests. In this case, I am not able to figure out what's the ideal way to queue them as the API Gateway will receive all 20,000 requests at the same time.

Regarding
> you could 1) use a local query cache, declared outside your Lambda handler or 2) use a third-party cache to which your Lambda will connect.

Could you help me understand more on how to achieve this? Any tutorials or code sample I can refer to?

Thank you in advance!

**Comment by jeanbmar** [comment]
If you receive 20k concurrent requests then caching Mongo results won't help here.

In this situation you could use reserved (reserved, not provisioned) concurrency to limit the maximum number of simultaneous instances of the Lambda connecting to Mongo.
This + limiting the pool size should be good enough.

Reserved concurrency can be configured from the console but there must be a Serverless param too.

**Comment by harishv7** [comment]
@jeanbmar Regarding this:

> to limit the maximum number of simultaneous instances of the Lambda connecting to Mongo

I agree we can limit the simultaneous instances, but this will lead to some of the requests being dropped right? Is there a way we can queue them through API Gateway and process them batch by batch perhaps?

**Comment by jeanbmar** [comment]
API Gateway can't queue the requests, but you can do something in the spirit of what you are already doing:
1. Configure reserved concurrency
2. Receive a request
3. Push it to SQS. If you push to SQS with a Lambda, said Lambda must not connect to Mongo
4. Lambda functions that process your business logic (and connect to Mongo) are coupled with SQS. Messages will stay in SQS durably and won't be dropped while your N Lambda functions consume the queue, N being your reserved concurrency.

See this: https://docs.aws.amazon.com/lambda/latest/operatorguide/reserved-concurrency.html

**Comment by harishv7** [comment]
@jeanbmar That's helpful, thank you!

**Comment by vkarpov15** [comment]
Great suggestions from @jeanbmar . I agree that, if you get 20k concurrent requests, you'll probably run out of connections. Each Lambda instance will create a new connection pool, so even if you reduce `maxPoolSize` to 1 in your example, you'll only be able to handle 750 concurrent requests. You need some sort of queueing infrastructure to make sure you don't go over that.
