### ISSUE TITLE
How to handle Mongoose Cannot populate path is not in your schema error?

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#12210]
### Discussed in https://github.com/Automattic/mongoose/discussions/12182

<div type='discussions-op-text'>

<sup>Originally posted by **samislam** August  1, 2022</sup>
> MongooseError: Cannot populate path `friends` because it is not in your
> schema. Set the `strictPopulate` option to false to override.

I have the following code:
```js
const userSchema = mongoose.Schema({
   age: Number
})
const UserModel = mongoose.model('User', userSchema, 'users')
```

and then in one of the controllers I have the following code:
```js
UserModel.find({ name: 'Isaa' }).populate('friends'); 
```

The above line results in the following error:

> MongooseError: Cannot populate path `friends` because it is not in your
> schema. Set the `strictPopulate` option to false to override.

I want to handle this error in my express error handling middleware, but how?
The error doesn't have any unique field that I can use, such as `error.code` or `error.name`.
So How to handle this error?

```js
app.use((err, req, res, next) => {
    // 👈 here
})
```</div>

**Comment by Its-Just-Nans** [comment]
Hi,

Did you try

```js
try {
    UserModel.find({ name: 'Isaa' }).populate('friends'); 
} catch (e) {
    if (e instanceof MongooseError) {
        // is mongo error
    }
}
```

**Comment by vkarpov15** [comment]
Fixed with https://github.com/Automattic/mongoose/pull/12252
