### ISSUE TITLE
Typescript: Document save method does not return populated type if document was populated

### ISSUE THREAD

**Issue by ajwootto** [Automattic/mongoose#12214]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.1

### Node.js version

16.13

### MongoDB server version

5.x

### Description

When working with a populated document, if you then save it and use the document returned from the "save", the type will no longer accurately reflect that the document is populated:
```typescript
import { Schema, model, connect, Types } from 'mongoose'

interface NestedChild {
    name: string
    _id: Types.ObjectId
}
const nestedChildSchema: Schema = new Schema({ name: String })

interface Parent {
    nestedChild: Types.ObjectId
    name?: string
}

const ParentModel = model<Parent>('Parent', new Schema({
    nestedChild: { type: Schema.Types.ObjectId, ref: 'NestedChild' },
    name: String
}))

const NestedChildModel = model<NestedChild>('NestedChild', nestedChildSchema)

async function run() {
    await connect('mongodb://localhost:27017/')
    await (new ParentModel({
        nestedChild: new NestedChildModel({ name: 'test' }),
        name: 'Parent'
    })).save()

    const foundParent = await ParentModel.findOne({ name: 'Parent' })
        .populate<{nestedChild: NestedChild}>('nestedChild')
        .exec()

    if (!foundParent) {
        return
    }

    // works, populate has set the type correctly
    console.log(foundParent.nestedChild.name)

    const savedPopulatedDocument = await foundParent.save()

    // does not work, save has wiped the info that the document was populated in its return
    // this does not accurately represent the actual contents of `savedPopulatedDocument`
    console.log(savedPopulatedDocument.nestedChild.name)
}

run()
```

The return type of `save()` is actually incorrect in this case, because the `savedPopulatedDocument` instance is still populated after the save.

### Steps to Reproduce

See the code snippet above

### Expected Behavior

I would expect the return type of `save()` to reflect the underlying data type that it's returning, in this case the populated document

**Comment by vkarpov15** [comment]
Unfortunately, based on my reading, I'm not sure we can support this behavior, because TypeScript's `this` is very fundamentally different from JavaScript `this`. We would need to do some complex chaining similar to how we handle queries, and I'd rather avoid that. Especially since there's a workaround that's much more concise:

```ts
await foundParent.save()
```

Remember that `await foundParent.save()` resolves to `findParent`, so there's no need to use the return value. Just save and return `foundParent` instead.
