### ISSUE TITLE
Chaining a Mongoose Query returned by an async function

### ISSUE THREAD

**Issue by jeanbmar** [Automattic/mongoose#12238]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.3

### Node.js version

18.6.0

### MongoDB version

5.0.10

### Operating system

Windows

### Issue

Let's say we have the following method defined on a Schema:
```js
async method() {
  // do async stuff first, then
  return this.constructor.find();
}
```

Chaining on an async method will return an error:
```js
const model = new Model();
await model.method().populate('field').exec();
// throws .populate is not a function
await (await model.method()).populate('field').exec();
// same
```

I understand that the error is thrown because `model.method()` won't return a Mongoose Query, but instantiated documents.

I'm not sure why the query has been executed, but I guess it has to do with Mongoose internally calling exec for pending queries when there is a change in the event loop or something like that.

How can I properly chain the `populate` call here? Is there an option to delay the execution?

`method` needs to be async because async stuff actually happens inside, besides the `find` call.

Thanks!

**Comment by imranbarbhuiya** [comment]
You can do it by returning an object or array. I don't think simply returning the query will work as `await` will call `then` on query and it'll execute the query.

```ts
async method() {
  // do async stuff first, then
  return {find: this.constructor.find()};
}
```

```ts
const model = new Model();
await (await model.method()).find.populate('field').exec();
```

**Comment by jeanbmar** [comment]
Thanks for your answer :).

Now I see, the Query thenable returned by `method` is "resolved" like a regular promise, which triggers query execution.
I wonder if there is a pretty workaround for this.
Wrapping the object like you propose totally works but it kind of break the chaining since the result has to be unwrapped.

**Comment by jeanbmar** [comment]
At best we can `await (await model.method()).populate('field').exec();` if we set the thenable to undefined in the `method` function.
But it comes with side effects and the syntax is still not ideal anyway.
There's no magic to chain from a Promise but this is regular Promise stuff!
