### ISSUE TITLE
Document.prototype.set() on nested objects value erase existing previous values

### ISSUE THREAD

**Issue by erwanriou** [Automattic/mongoose#12235]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.1

### Node.js version

16.13.1

### MongoDB server version

5.0.9

### Description

The issue seems to impact the version 6 of mongoose. I recently discovered this bug since i updated to the last version 6 because of a discovered vulnerability that affect older versions to the 6.4..

 

### Steps to Reproduce

Whenever you use the use `set` with a flattened key/value annotation, it's seems to work correctly.

 ```js
 await document.set({ "path.subpath": "some value" }).save()
 ```
 
 this would work properly assuming that the path potentially contain other subpaths that would not be affected by this change. But if i would write it with a nested object annotation instead then:
 
  ```js
 await document.set({  path: { subpath: "some value" } }).save()
 ```
 
 this would affect the rest of the element potentially contained in path and erase them.  The temporary solution that i found here is to manually inject them with a spread operator.
 
   ```js
 await document.set({  path: { ...document.path, subpath: "some value" } }).save()
 ```
 
 but this is not matching the behavior of the `$set` from MongoDb and in some case it turn out to be very limiting. 
 

### Expected Behavior

  ```js
 await document.set({  path: { subpath: "some value" } }).save()
 ```
 should not erase all the other elements contained within the `path` key.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String,
    fullName: {
        firstName: String,
        lastName: String
    }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({
        name: 'Test',
        fullName: {
            firstName: 'Test',
            lastName: 'Testerson'
        }
    });

    const entry = await Test.findOne();

    await entry.set({"fullName.firstName": "Timmy"});
    await entry.save();
    console.log(entry);
    const failure = await Test.findOne();
    await failure.set({ fullName: { firstName: 'Timothy'}});
    await failure.save();
    console.log(failure);

}

run();
```

**Comment by ramos-ph** [comment]
Can I try and fix this one?

**Comment by IslandRhythms** [comment]
@ramos-ph Sure, knock yourself out.

**Comment by vkarpov15** [comment]
@ramos-ph this is expected behavior. You can set the `merge` option on `set()` to merge instead of overwrite. See below changes to @IslandRhythms 's script:

```javascript
    await entry.set({"fullName.firstName": "Timmy"});
    await entry.save();
    console.log(entry);
    const failure = await Test.findOne();
    failure.set({ fullName: { firstName: 'Timothy'}}, null, { merge: true }); // <-- add merge option here
    await failure.save();
    console.log(failure);
```

**Comment by erwanriou** [comment]
Thank you @vkarpov15, you sorted my issue with this merge option (better than reconvert everything to JSON string paths)
---

so the expected behavior is that:

```js
await entry.set({"fullName.firstName": "Timmy"});
```
is the same than:

```js
await failure.set({ fullName: { firstName: 'Timothy'}}, null, { merge: true });
```

We should consider update the documentation to be more clear about it and also alert about this breaking change between version 5 and version 6.
