### ISSUE TITLE
Error "command createIndexes requires authentication"

### ISSUE THREAD

**Issue by shanematte** [Automattic/mongoose#12232]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, can you tell me what could be the error. I connect via mongoose and the error "command createIndexes requires authentication". But when I connect via compass everything works

```
export const connectMongoURL = `mongodb://${
    config.DB.mongo_ip
}:${ports.portDB()}/${config.DB.db_name}`;

mongoose
    .connect(connectMongoURL, {
        user: config.DB.user,
        pass: config.DB.pwd,
        authSource: config.DB.db_name,
        autoIndex: true,
        useCreateIndex: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
    })
    .then(() => console.log('mongodb connected'))
    .catch((err) => console.log(err));
```

**Comment by vkarpov15** [comment]
Mongoose tries to create any indexes defined in your models when you try to connect. Set `autoIndex: false` and this error should go away.
