### ISSUE TITLE
Missing inferred `enum` property when type is Number

### ISSUE THREAD

**Issue by Catatomik** [Automattic/mongoose#12242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.1

### Node.js version

17.3.0

### MongoDB server version

5.0.5

### Description

When you precise an `enum` property on a Schema, and when type is `Number`, the type doesn't take in account the enum array, but `InferSchemaType` resolves to `number`.

### Steps to Reproduce

```ts
const dbExample = new Schema(
  {
    active: { type: Number, enum: [0, 1], required: true }
  }
);

type Example = InferSchemaType<typeof dbExample>;
```
Here, in type `Example`, `active` will be `number`.

### Expected Behavior

Following the previous example, `active` should be `0 | 1`.

**Comment by hasezoey** [comment]
i dont know if this is even possible with current typescript, without manually doing `[] as const` (where `[]` is the enum array), see [This Typescript Stackoverflow Question](https://stackoverflow.com/questions/73140386/typescript-remap-array-to-object-with-intellisense-on-keys)
