### ISSUE TITLE
Does mongoose fully support mongodb 6.0?

### ISSUE THREAD

**Issue by ZeroCho** [Automattic/mongoose#12257]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I know that mongodb 6.0 is out and it needs mongodb nodejs driver 4.8 or newer.
As I can see in package.json of mongoose, mongoose uses mongodb@4.8, so I guess mongoose can support mongodb 6.0.
I opened this issue to know whether mongoose is tested on mongodb 6.0 and can be used along with mongodb 6.0. Can anybody tell me? Thank you in advance.

**Comment by Uzlopak** [comment]
@vkarpov15 
@hasezoey 
Should we add mongo6 to our test pipeline?

**Comment by Uzlopak** [comment]
There is no official mongo 6 image on docker hub...

**Comment by hasezoey** [comment]
>  Should we add mongo6 to our test pipeline?

we could, at least from a MMS perspective, because 6.0.0 binaries are up at https://dl.mongodb.org/dl/linux, though MMS does not have any 6.0.0 tests yet - but i dont see anything currently preventing its usage

**Comment by Uzlopak** [comment]
@hasezoey 

Well i think vkarpov wanted to use also mongodb memory for the cicd pipeline. Maybe you can provide a PR for using mms in the pipeline?

**Comment by hasezoey** [comment]
> Maybe you can provide a PR for using mms in the pipeline?

is MMS not currently used in the Pipeline? if not, then what is it currently installed for?

**Comment by Uzlopak** [comment]
@hasezoey 
In the cicd pipeline we spawn a mongo server without the use of mms. I added mms into mongoose codebase to easier test the mongoose unit tests locally. When i tried to implement it for the pipeline it was actually not that trivial. But maybe you can implement it?
