### ISSUE TITLE
Depopulate of a populated empty array becomes a "non-mongoose array"

### ISSUE THREAD

**Issue by zxlin** [Automattic/mongoose#12253]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.1

### Node.js version

16.16.0

### MongoDB server version

5.0.9

### Description

If you populate an empty array, then depopulate it, it becomes a non-mongoose tracked array. 

### Steps to Reproduce

Using the same schema in the docs as the example:
```JS
const blogSchema = new Schema({
  title:  String, // String is shorthand for {type: String}
  author: String,
  body:   String,
  comments: [{ body: String, date: Date }],
  date: { type: Date, default: Date.now },
  hidden: Boolean,
  meta: {
    votes: Number,
    favs:  Number
  }
});
mongoose.model('Blog', blogSchema);
```

We can create a new document object
```JS
const blog = new Blog({ comments: [] });
```

At this point in time, if we access `blog.comments`, the type is a `Proxy` type, it's a "mongoose array". repl e.g.:
```JS
> blog.comments
Proxy [ [], { get: [Function: get], set: [Function: set] } ]
> blog.comments.addToSet
[Function: addToSet]
```

But if we run the following two steps:
```JS
await blog.populate('comments');
blog.depopulate('comments');
```

Then we try to access `blog.comments`, then we see that it'll just be a plain old JS array type. repl e.g.:

```JS
> blog.comments
[]
> blog.comments.addToSet
undefined
```

So this means if we try to run `blog.comments.addToSet()` right now, it'll throw a `TypeError: blog.comments.addToSet is not a function`

This specifically happens after the `depopulate` call. If we run the following in repl, we can see that the `populate` call still keeps the array as a "mongoose array":
```JS
> const blog = new Blog({ comments: [] });
> blog.comments
Proxy [ [], { get: [Function: get], set: [Function: set] } ]
> await blog.populate('comments');
> blog.comments
Proxy [ [], { get: [Function: get], set: [Function: set] } ]
```

---

Note: this only happens when the empty array was populated first, never populated before arrays do not experience this problem. 

### Expected Behavior

We should be able to run the following code with the above schema successfully:

```JS
const blog = new Blog({ comments: [] });
await blog.populate('comments');
blog.depopulate('comments');
blog.comments.addToSet({ body: 'test', date: new Date() })
```

This should run without errors (i.e. not throw a `TypeError: blog.comments.addToSet is not a function`)

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
const { Schema } = mongoose;

const blogSchema = new Schema({
  title:  String, // String is shorthand for {type: String}
  author: String,
  body:   String,
  comments: [{ body: String, date: Date }],
  date: { type: Date, default: Date.now },
  hidden: Boolean,
  meta: {
    votes: Number,
    favs:  Number
  }
});

const Blog = mongoose.model('Blog', blogSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const blog = await Blog.create({
    title: 'Test',
    comments: []
  });

  await blog.populate('comments');
  blog.depopulate('comments');
  blog.comments.addToSet({ body: 'test', date: new Date() });
  console.log('done');
  console.log('the blog', blog);

}

run();
```
