### ISSUE TITLE
mongoose.Connection.model() return type for typescript changed between 6.4 to 6.5

### ISSUE THREAD

**Issue by hagar-dolev** [Automattic/mongoose#12276]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5

### Node.js version

18.0.0

### MongoDB server version

5.0.10

### Description

When updating mongoose from 6.4 to 6.5 the following issue arrises:

Having a schema and a matching interface, which work together and have the same fields and types, named "IEmailActivity" and "emailActivitySchema", the following code used to work perfectly:

`const EmailActivity = (conn: mongoose.Connection): mongoose.Model<IEmailActivity> =>`
`conn.model(collectionName, emailActivitySchema);`

And when updating to current Mongoose version, I receive the following warning:

`
Type 'Model<{ [x: string]: any; }, {}, {}, {}, Schema<any, Model<any, any, any, any, any>, {}, {}, {}, {}, "type", { [x: string]: any; }>>' is not assignable to type 
'Model<IUnifiedEmailActivity, {}, {}, {}, any>'. The types returned by 'castObject(...)' are incompatible between these types. Type '{ [x: string]: any; }' is not assignable to type 'IUnifiedEmailActivity'.
`

### Steps to Reproduce

Simply update Mongoose, changed the types needed in my code.

**Comment by hasezoey** [comment]
could `IEmailActivity` and `emailActivitySchema` be provided?
also do your schema & interface work when `mongoose.model` is used instead of `con.model`?
