### ISSUE TITLE
Path is not in your schema error after changing mongoose version from 5 to 6.5.2

### ISSUE THREAD

**Issue by ShubhamP07** [Automattic/mongoose#12292]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.2

### Node.js version

16.13.2

### MongoDB server version

4.2.21

### Description

Here are the schemas-

UserGroup -
```ts
const UserGroupSchema = new Schema({
  sites: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Site',
    },
  ],
})
```

Site-

```ts
const SiteSchema = new Schema({
  gateways: [
    {
      type: Schema.Types.ObjectId,
      ref: 'SiteGateway',
    },
  ],
```

SiteGateway-

```ts
const SiteGatewaySchema = new Schema({
  product_type: {
    type: Schema.Types.ObjectId,
    ref: 'Product',
    required: true,
  },
})
```

Product-

```ts
const ProductSchema = new Schema({
  master_product_id: {
    type: Schema.Types.ObjectId,
    ref: 'MasterProduct',
    required: true,
  },
})
```

Master Product-

```ts
const MasterProductSchema = new Schema({})
```

I needed to get all sites for a particular user group and after get all related information(like gateways linked to it and products and so on...) for analytics and stuff.

I used following query-

```ts
const group = await UserGroup.findOne({
          _id: new Types.ObjectId(group_id),
        })
          .populate({
            path: 'sites',
            select:
              'name tenant_id customer_id status last_updated latitude longitude gateways',
            populate: {
              path: 'customer_id gateways',
              select: '_id name product_type device_id',
              populate: {
                path: 'product_type',
                select: '_id name master_product_id',
                populate: {
                  path: 'master_product_id',
                  select: 'name _id minichart_config',
                },
              },
            },
          })
          .lean()
```

Above query throws following error-

> error MongooseError: Cannot populate path `sites.gateways.product_type` because it is not in your schema. Set the `strictPopulate` option to false to override.
>     at getModelsMapForPopulate (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:47:12)
>     at populate (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\model.js:4574:21)
>     at _populate (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\model.js:4534:5)
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\model.js:4512:5
>     at promiseOrCallback (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\helpers\promiseOrCallback.js:11:14)
>     at Mongoose._promiseOrCallback (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\index.js:1225:10)
>     at Function.Model.populate (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\model.js:4510:23)
>     at cb (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongoose\lib\query.js:2270:26)
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\utils.js:425:9
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\cursor\abstract_cursor.js:257:32
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\cursor\abstract_cursor.js:516:55
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\utils.js:425:9
>     at C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\sessions.js:136:24
>     at maybePromise (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\utils.js:411:5)
>     at ClientSession.endSession (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\sessions.js:133:41)
>     at cleanupCursor (C:\Users\pwrs0\Documents\starlly\spectra\spectra\node_modules\mongodb\lib\cursor\abstract_cursor.js:563:32)

And when I use `Model.aggregate` Api it works fine. Offcourse it returns different format which I need to handle differently.
I use aggregate like-

```ts
const groupData = await UserGroup.aggregate([
            {
              $match: {_id: new Types.ObjectId(group_id)},
            },
            {
              $lookup: {
                from: 'sites',
                localField: 'sites',
                foreignField: '_id',
                as: 'siteObjects',
              },
            },
            {
              $unwind: '$siteObjects',
            },
            {
              $lookup: {
                from: 'customers',
                localField: 'siteObjects.customer_id',
                foreignField: '_id',
                as: 'siteCustomer',
              },
            },
            {
              $unwind: '$siteCustomer',
            },
            {
              $lookup: {
                from: 'sitegateways',
                localField: 'siteObjects.gateways',
                foreignField: '_id',
                as: 'siteGateways',
              },
            },
            {
              $lookup: {
                from: 'products',
                localField: 'siteGateways.product_type',
                foreignField: '_id',
                as: 'siteProduct',
              },
            },
            {
              $unwind: '$siteProduct',
            },
            {
              $lookup: {
                from: 'masterproducts',
                localField: 'siteProduct.master_product_id',
                foreignField: '_id',
                as: 'siteMasterProduct',
              },
            },
            {
              $unwind: '$siteMasterProduct',
            },
            {
              $group: {
                _id: '$_id',
                sites: {
                  $push: {
                    site: '$siteObjects',
                    product: '$siteProduct',
                    masterProduct: '$siteMasterProduct',
                    customer: '$siteCustomer',
                    gateways: '$siteGateways',
                  },
                },
              },
            },
            {
              $project: {
                'sites.site._id': 1,
                'sites.site.name': 1,
                'sites.site.status': 1,
                'sites.site.last_updated': 1,
                'sites.site.tenant_id': 1,
                'sites.site.latitude': 1,
                'sites.site.longitude': 1,
                'sites.gateways.device_id': 1,
                'sites.product._id': 1,
                'sites.product.name': 1,
                'sites.masterProduct._id': 1,
                'sites.masterProduct.name': 1,
                'sites.masterProduct.minichart_config': 1,
                'sites.customer._id': 1,
                'sites.customer.name': 1,
              },
            },
          ])
```

### Steps to Reproduce

Have a schema's like above which are deeply interlinked with each other and when you try to do populate the error occurs.

### Expected Behavior

I need a `group.sites[0]` to look like-

```ts
{
          _id: new ObjectId('61c46aabdabcb406acd77482'),
          last_updated: '13:04:54 2022-06-29',
          name: 'NALLA GOUNDAN KOTTAI_1',
          customer: {
            _id: new ObjectId('61961615e3d284741930f087'),
            name: 'Hatsun Agro',
          },
          gateways: [
            {
              device_id: '200011611293379',
              product: {
                _id: new ObjectId('618e36480b80f656580b66c8'),
                name: 'DoubleCompWithVolume',
                master_product_id: {
                  _id: new ObjectId('618e342d0b80f656580b66c7'),
                  name: 'MILK CHILLER DOUBLE COMP WITH VOLUME',
                },
              },
            },
          ],
        }

```

**Comment by IslandRhythms** [comment]
Could you please provide some dummy data, I'm having a hard time reproing
