### ISSUE TITLE
autoReconnect option on MongoDV version 5

### ISSUE THREAD

**Issue by elizatlawy** [Automattic/mongoose#12304]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.4

### Node.js version

14.18.3

### MongoDB version

5.0.9

### Operating system

macOS

### Issue

How to ensure a `autoReconnect` mechanism with Mongoose? 
When I'm setting the `autoReconnect` flag, I'm getting an error that this option is not supported, is it deprecated? If so what is the alternative?

**Comment by IslandRhythms** [comment]
It has been removed in v6, mongoose will auto reconnect so no need to set the option. Will fix the docs to inform this new behavior.

**Comment by elizatlawy** [comment]
Ok, thank you!
