### ISSUE TITLE
MongooseError: Operation ... buffering timed out after 10000ms

### ISSUE THREAD

**Issue by comicallybad** [Automattic/mongoose#12312]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.2

### Node.js version

17.7.2

### MongoDB server version

5.0.6

### Description

*I was asked to post a new Issue with the updated template.*

To keep this as short and simple as possible, I am getting operation timeout's. These are operations that I do not call on starting up my connection to Mongodb. The operations I use when first connected do not include `deleteOne()` or `deleteMany()`, after the connection has been made.

In my original post, I expressed that the fully cloned db and code did not provide this error on any other machines I had tested. My server was the only PC I could replicate the error on. 

I could be completely wrong, but I am almost certain this issue is network related. The timeouts didn't happen when I first started the server. I cannot pinpoint what I had done last time to fix this. After attempting changing from `localhost` to `127.0.0.1` with `mongoose.connect()`, trying other fixes such as changing my default DNS, I gave up, until randomly one day the error was gone. Seems I have done the opposite now to restart the issue. After moving the server and having to change it's static IP, there were no issues for 3-4 weeks. Just now I am getting these timeout errors again. 

The only thing I had changed within the code was the connection URL, which at the time, didn't seem to fix anything. I have only changed the static IP address. Reason I believe it is network related. This would be 3 times now I changed something with the network to either get this error, or somehow accidentally fix it.
```js
const mongoose = require("mongoose");
const { dbSetup } = require("../../dbFunctions.js");

module.exports = client => {
    var time = new Date();
    console.log(time.toLocaleString('en-US', { month: 'numeric', day: 'numeric', year: 'numeric', hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: true }));

    global.activities = [`${client.guilds.cache.size} servers!`, `${client.channels.cache.size} channels!`, `${client.guilds.cache.reduce((acc, guild) => acc + guild.memberCount, 0)} users!`], i = 0;
    setInterval(() => client.user.setActivity(`${prefix}help | ${activities[i++ % activities.length]}`, { type: "PLAYING" }), 7500)

    mongoose.connect("mongodb://127.0.0.1/ComicallyBOT2", { useUnifiedTopology: true, useNewUrlParser: true }).then(() => {
        console.log("Successfully connected to Mongodb");
        dbSetup(client);
    });

    client.music.init(client.user.id);
}
```
Console error(s):

```MongooseError: Operation `dbs.deleteOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\{username}\Documents\Projects\Comicallybot2.0\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
MongooseError: Operation `xps.deleteMany()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\{username}\Documents\Projects\Comicallybot2.0\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
8/22/2022, 3:27:38 PM
Successfully connected to Mongodb```

### Steps to Reproduce

I would assume change static IP. I can't on purpose reproduce this on my other machines, however, they do not run on static IP's so that is all I have changed.

### Expected Behavior

I expect to simply connect to mongoose with no timeout errors, as I do not call any of these functions during connection or right after connected either. These  operations seem to run without ever being called.

**Comment by IslandRhythms** [comment]
Try 0.0.0.0

**Comment by comicallybad** [comment]
> Try 0.0.0.0

I gave this a try, it successfully connected to Mongodb, same timeout errors however.

**Comment by IslandRhythms** [comment]
Ok so with node 17, localhost changed to `0.0.0.0`. Can you elaborate on how you're getting these timeout errors? You say you are connected to mongodb now, but are still getting the errors. Have you tried moving your connection code to before you login with your bot? Try adding event listeners to see if maybe the connection is being lost along the way.
https://mongoosejs.com/docs/connections.html#connection-events

**Comment by comicallybad** [comment]
Well, after spending hours on this, I have finally found my issue, although left a little confused.

My program works in the following order:

index.js (start discord connection) -> `client.on('ready')` (once discord is connected) -> `mongoose.connect(...)` (connect to mongodb server) -> await discord events that are emitted.

There's only a single location both `dbs.deleteOne()` and `xps.deleteMany()` were called. Inside a `client.on('guildDelete')` event. (In the case my bot is kicked from a server, delete the guild from dbs and all users from xps).  Both operations are called with catch statements to console out any error. -> **Timeout origination**

Although simply removing the `console.log()`'s in both catch statements stopped the timeout errors from being logged, the `guildDelete` event *should* **ONLY** fire *after* discord is connected, in the *specific case* my bot is *kicked* from a guild. I added a console.log to every "guild" discord event and guildDelete was the only event that output on startup. That code should not be triggered, but somehow it is. Might be a discord API issue emitting that event..? Although, it shouldn't receive events until connected.. Oh well. Issue *resolved*.

*Last note:* I did find that the guild argument in the guildDelete event, as expected, was undefined, so instead of an "I'll ignore errors" fix, using `if(guild)` was the better solution.

```guildDelete.js
const db = require("../../schemas/db.js");
const xp = require("../../schemas/xp.js")

module.exports = (client, guild) => {
    console.log("inside guildDelete") //Check if event is ran on start for some reason
    //if(guild){..} Added after last note.
    activities = [`${client.guilds.cache.size} servers!`, `${client.channels.cache.size} channels!`, `${client.guilds.cache.reduce((acc, guild) => acc + guild.memberCount, 0)} users!`], i = 0;
    db.deleteOne({ guildID: guild.id }, {
    }).catch(err => console.log(err)); //Always outputs on startup
    xp.deleteMany({ guildID: guild.id }, {
    }).catch(err => console(err)); //Always outputs on startup
}
```

```
inside guildDelete
MongooseError: Operation `dbs.deleteOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\{user}\Documents\Projects\Comicallybot2.0\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
MongooseError: Operation `xps.deleteMany()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\{user}\Documents\Projects\Comicallybot2.0\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
8/24/2022, 1:34:33 PM
Successfully connected to Mongodb
Successfully connected to Erela
```

**Comment by vkarpov15** [comment]
For future reference, we're working on a discord bot sample app in our sample apps repo: https://github.com/mongoosejs/sample-apps, the PR is here: https://github.com/mongoosejs/sample-apps/pull/6
