### ISSUE TITLE
Find on nested discriminators is broken after upgrade from mongoose 5 to mongoose 6

### ISSUE THREAD

**Issue by fschucht** [Automattic/mongoose#12318]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.2

### Node.js version

16.15.0

### MongoDB server version

4.4

### Description

We are currently migrating from mongoose 5 to mongoose 6, and it seems like nested discriminators are broken with mongoose 6. When we `find` by a nested discriminated field, the query will return all documents instead of matching ones. This has created quite a few bugs for us while testing our code with mongoose 6, where completely unrelated data is being returned from queries. The culprit seems to be the new `strictQuery` option, and setting it to `false` patches the issue. However, having to set this option for nested fields seems like a broken behavior to use.

### Steps to Reproduce

The following script shows the error. The find call should return only the second document. However, both are returned.
```js
import mongoose from 'mongoose';

const BaseDocumentSourceSchema = new mongoose.Schema({
  source: { type: String },
}, {
  discriminatorKey: 'type'
});

const InternalDocumentSchema = new mongoose.Schema({
  source: { type: String },
});

const ExternalDocumentSchema = new mongoose.Schema({
  source: { type: String },
  url: { type: String },
});

const DocumentSchema = new mongoose.Schema({
  source: BaseDocumentSourceSchema,
});
DocumentSchema.path('source').discriminator('internal', InternalDocumentSchema);
DocumentSchema.path('source').discriminator('external', ExternalDocumentSchema);

const DocumentModel = mongoose.model('Document', DocumentSchema);

(async () => {
  await mongoose.connect(`mongodb://localTestUser:HhPQ5rEUvbDgqrkE3c@localhost:27017/frankhr_test`);

  await mongoose.connection.db.dropDatabase();

  const doc1 = await DocumentModel.create({ source: { type: 'internal' } });
  const doc2 = await DocumentModel.create({ source: { type: 'external', url: 'url' } });

  console.log(doc1, doc2);

  // Expected result is document 2. However, it will return both documents.
  const results = await DocumentModel.find({ 'source.url': 'url' });
  console.log(results);

  // Query correctly returns document 2
  const strictResults = await DocumentModel.find({ 'source.url': 'url' }, undefined, { strictQuery: false });
  console.log(strictResults);

  await mongoose.disconnect();
})();

```

### Expected Behavior

Queries using nested discriminated fields should return the correct data.

**Comment by ramos-ph** [comment]
Hey, I've managed to reproduce it and just opened a pull request to try and fix this issue. Let me know if it is from any help.

**Comment by vkarpov15** [comment]
@fschucht  Have you tried setting `mongoose.set('strictQuery', false)`? That would switch back to Mongoose 5.x behavior.

**Comment by fschucht** [comment]
@vkarpov15 We're doing this as a workaround right now. However, the requirement to set the option before registering any models makes it quite hard for us as our codebase is quite interconnected with multiple entry points. This is not the fault of mongoose, but for us setting this on the schema level is definitely more convenient. Especially, since we already set all other options on the schema level. So having the `strictQuery` setting in a different place is not ideal.

**Comment by vkarpov15** [comment]
@fschucht I took a look and you can set `strictQuery` on the schema level. Following script works as expected:

```javascript
'use strict';

const mongoose = require('mongoose');

const BaseDocumentSourceSchema = new mongoose.Schema({
  source: { type: String },
}, {
  discriminatorKey: 'type',
  strictQuery: false
});

const InternalDocumentSchema = new mongoose.Schema({
  source: { type: String },
}, { strictQuery: false });

const ExternalDocumentSchema = new mongoose.Schema({
  source: { type: String },
  url: { type: String },
}, { strictQuery: false });

const DocumentSchema = new mongoose.Schema({
  source: BaseDocumentSourceSchema,
}, { strictQuery: false });
DocumentSchema.path('source').discriminator('internal', InternalDocumentSchema);
DocumentSchema.path('source').discriminator('external', ExternalDocumentSchema);

const DocumentModel = mongoose.model('Document', DocumentSchema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/frankhr_test`);

  await mongoose.connection.db.dropDatabase();

  const doc1 = await DocumentModel.create({ source: { type: 'internal' } });
  const doc2 = await DocumentModel.create({ source: { type: 'external', url: 'url' } });

  console.log(doc1, doc2);

  // Expected result is document 2. However, it will return both documents.
  const results = await DocumentModel.find({ 'source.url': 'url' });
  console.log(results);

  // Query correctly returns document 2
  const strictResults = await DocumentModel.find({ 'source.url': 'url' }, undefined, { strictQuery: false });
  console.log(strictResults);

  await mongoose.disconnect();
})();
```

Can you confirm whether :point_up: works for you @fschucht ?

**Comment by fschucht** [comment]
@vkarpov15 I can confirm that your script works. It seems like I didn't set `strictQuery` for the nested schemas as I assumed the parent options would also apply to the nested child schemas.

Setting `strictQuery` for the child schemas works and solves this issue: https://github.com/Automattic/mongoose/issues/12318#issuecomment-1228138014

However, the original issue still exists. When `strictQuery` is not set or enabled, nested discriminated fields don't work anymore.

**Comment by vkarpov15** [comment]
The original issue is a problem. We're planning on changing `strictQuery`'s default value back to `false` in 7.0: https://github.com/Automattic/mongoose/issues/11861 , which will fix the original issue. I'm sorry for the inconvenience, the `strictQuery` change in 6.0.0 turned out to be a bad design decision in hindsight.
