### ISSUE TITLE
can not save the data

### ISSUE THREAD

**Issue by 5AFRAA3** [Automattic/mongoose#12339]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.14

### Node.js version

16.15.1

### MongoDB version

idk?

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue
```js
const data = await queue.findOne({guildId : interaction.guild.id})
    let queues = data.queue
    let queuename = data.queueName
    let duration = data.duration
    let userId = data.userId
    let index = data.index
    for (let i = data.queue.length - 1; i > 0; i--) {
      let j = 1 + Math.floor(Math.random() * i);
      [queues[i], queues[j]] = [queues[j], queues[i]],
      [queuename[i], queuename[j]] = [queuename[j], queuename[i]],
      [duration[i], duration[j]] = [duration[j], duration[i]],
      [userId[i], userId[j]] = [userId[j], userId[i]],
      [index[i], index[j]] = [index[j], index[i]]
    }
    console.log(queuename)
    data.queueName = queuename
    data.queue = queues
    data.duration = duration
    data.userId = userId
    data.index = index
    await data.save()
```

It's not saving but even when i console queuename its changed but not saved idk why

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @5AFRAA3

Can you elaborate on what you mean by "it's not saving"? Do you get an error?
Try putting `mongoose.set('debug', true);` before `await data.save()`, and share the output you receive in the console.

Also, this for loop is a bit too confusing, I think it can be simplified a lot. Are you trying to shuffle the `queue` array?

**Comment by 5AFRAA3** [comment]
it was simple the for loop thing but I changed it because it wasn't saving
in the data and what I mean by that is when I doo
data.queue = "the array"
and console it it changes but it's still the same in the cluster

**Comment by 5AFRAA3** [comment]
And yes I'm trying to shuffle the array queue in the data

**Comment by AbdelrahmanHafez** [comment]
Perhaps abstract the shuffling process into in a different function.
Can you change your code to the code below and let me know what the output is?
```js
mongoose.set('debug', true);

const data = await queue.findOne({ guildId: interaction.guild.id });
console.log(JSON.stringify(data, null, 2);
data.queue = shuffle(data.queue);

await data.save();

function shuffle(array) {
  let currentIndex = array.length;
  let randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex != 0) {

    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]];
  }

  return array;
}

```

**Comment by 5AFRAA3** [comment]
Tha'ts my code now
mongoose.connect(process.env.database, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
}).then(console.log('Mongoose is connected!'))
  function shuffle(array) {
    let currentIndex = array.length,  randomIndex;
      while (currentIndex != 0) {

      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex--;
        [array[currentIndex], array[randomIndex]] = [
        array[randomIndex], array[currentIndex]];
    }
    return array;
  }
const test = require("./test.js")
async function run() {
  let data = await test.findOne({array: [1, 2, 3, 4 ,5 ,6 ,7 ,8, 9, 10]})
      mongoose.set('debug', true);
      console.log(JSON.stringify(data, null, 2))
      data.array = shuffle(data.array);
      await data.save();
}
run()



/* And that's what im getting in the console Mongoose is connected!
{
  "array": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ],
  "_id": "630b7bc033a062b96543f61a",
  "__v": 0
}
Mongoose: music-queues.findOne({ _id: ObjectId("630b7bc033a062b96543f61a")
}, { session: null, projection: { _id: 1 } })
*/

**Comment by 5AFRAA3** [comment]
the array in the data didn't change yet!

**Comment by AbdelrahmanHafez** [comment]
Please modify the script below to demonstrate the issue you're facing.

### 12339.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('node:assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const queueContainerSchema = new Schema({
    queue: [{ number: Number }]
  });

  const QueueContainer = mongoose.model('QueueContainer', queueContainerSchema);

  const queueContainer = await QueueContainer.create({
    queue: [
      { number: 1 },
      { number: 2 },
      { number: 3 },
      { number: 4 },
      { number: 5 },
      { number: 6 },
      { number: 7 }
    ]
  });

  queueContainer.queue = shuffle(queueContainer.queue);
  await queueContainer.save();
  assert.notStrictEqual(queueContainer.queue[0].number, 1);
  console.log(mongoose.version);
  console.log('All assertions passed.');
}


function shuffle(array) {
  let currentIndex = array.length;
  let randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex != 0) {

    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]];
  }

  return array;
}
```

### Output
```bash
$ node 12339.js
6.5.3
All assertions passed.
```

**Comment by 5AFRAA3** [comment]
Thanks alot

**Comment by AbdelrahmanHafez** [comment]
@5AFRAA3 
Is the issue resolved or is there something else we can help with?

**Comment by IslandRhythms** [comment]
@5AFRAA3 Please indicate if this issue can now be closed.
