### ISSUE TITLE
Issues building with Vite/Rollup: "TypeError: Cannot read property 'Decimal128' of null"

### ISSUE THREAD

**Issue by AlexRMU** [Automattic/mongoose#12335]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.3

### Node.js version

16.15.0

### MongoDB server version

4.4

### Description

I'm trying to create a bundle for the prod.
I use esbuild, vite, rollup, sveltekit.

An error appears during building:
```js
var decimal128$3 = driver$1.get().Decimal128;
                                 ^
TypeError: Cannot read properties of null (reading 'Decimal128')
```

Possibly related to https://github.com/Automattic/mongoose/issues/7866

### Steps to Reproduce

It is difficult

**Comment by IslandRhythms** [comment]
Could you please provide a code sample or perhaps the code leading to that point where the error is thrown?

**Comment by AlexRMU** [comment]
Reproduction: https://stackblitz.com/edit/sveltejs-kit-template-default-jysxco?file=src/hooks.server.js
The error appears here:
```js
...

var mongoose$1 = {
    exports: {}
};

var lib$5 = {
    exports: {}
};

var driver$1 = {};

/*!
 * ignore
 */

let driver = null;

driver$1.get = function () {
    return driver;
};

driver$1.set = function (v) {
    driver = v;
};

...

/**
 * Decimal128 type constructor
 *
 * #### Example:
 *
 *     const id = new mongoose.Types.Decimal128('3.1415');
 *
 * @constructor Decimal128
 */

var decimal128$3 = driver$1.get().Decimal128; //here

var symbols$3 = {};

symbols$3.arrayAtomicsBackupSymbol = Symbol('mongoose#Array#atomicsBackup');
...
```

**Comment by vkarpov15** [comment]
@AlexRMU I don't see any errors? Maybe I just don't understand how to use StackBlitz

![image](https://user-images.githubusercontent.com/1620265/193941975-0fe438d3-9d4e-4c05-b200-a680b47713e6.png)

**Comment by AlexRMU** [comment]
The error appears after the build is runned.
Run 
```
npm i && npm run build && node build/index.js
```

**Comment by vkarpov15** [comment]
This looks like a bug with how Vite handles bundling. Like you mentioned, the general structure of the file Vite outputs looks like this:

```
var driver$1 = {};

/*!
 * ignore
 */

let driver = null;

driver$1.get = function () {
    return driver;
};

driver$1.set = function (v) {
    driver = v;
};

// ...

(function (module, exports) {

  /*!
   * Module dependencies.
   */

  console.log('set driver to', nodeMongodbNative);
  driver$1.set(nodeMongodbNative);
  // ...
})(lib$4);
```

The problem is that the `driver.set()` call runs _after_ `driver.get().Decimal128` in Vite/Rollup, but _before_ in Node. We tried to make a couple of tweaks, but no luck in getting Rollup to produce correct output.

The following doesn't work:

```
/** @type {import('vite').UserConfig} */
const config = {
  plugins: [sveltekit()],
  build: {
    commonjsOptions: {
      strictRequires: false
    }
  }
};
```

Nor does moving the `require('./driver').set(require('./drivers/node-mongodb-native'));` call to a separate file outside of `lib/index.js`. Rollup's output is unfortunately wrong, and we unfortunately don't have the expertise in Rollup internals to make this an easy fix. We'll take a look at this issue later, and open up a related issue that will hopefully help.

**Comment by birkskyum** [comment]
Here is a Reproduction of this issue with a blank SolidStart app:

https://github.com/birkskyum/solid-mongoose-issue

**Comment by birkskyum** [comment]
There is a lot of circular dependencies going on in mongoose, but in my case this error could be avoided by configuring the @rollup/plugin-commonjs with the configuration: { strictRequires: true } (see more [here](https://github.com/rollup/plugins/tree/master/packages/commonjs#strictrequires))

**Comment by vkarpov15** [comment]
I took a look and this is still an issue. New error message is the following:

```
/gh-12335/dist/index.js:134476
	  const Connection = _mongoose.__driver.Connection;
	                                        ^

TypeError: Cannot read properties of null (reading 'Connection')
    at Mongoose.createConnection (/gh-12335/dist/index.js:134476:42)
```

Here's the logic that sets `__driver` when compiled by rollup:

```
driver$2.set(nodeMongodbNative);
```

That logic is _after_ the logic that initializes the Mongoose singleton:

```
const mongoose = module.exports = new Mongoose({
          [defaultMongooseSymbol]: true
        });
```

Not sure why this is happening, I don't see any circular imports related to driver imports in particular. But we'll take a look and see if we can resolve some of the circular imports.

**Comment by AlexRMU** [comment]
Maybe it's a rollup bug
Maybe you need to change the rollup settings
Maybe you need to switch to es modules

**Comment by Coiggahou2002** [comment]
> Yeah all of those are valid explanations, but unfortunately not necessarily viable courses of action at this time. Apparently you can fix this with strictRequires option in Vite/rollup, but I'd love to see if there's a way we can fix this without requiring that option

I've encountered the same problem, setting the options of @rollup/plugin-commonjs to { strictRequires: true } does works.
