### ISSUE TITLE
[Feature/help] schema option to set indexes on top level only

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#12344]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

In my apps, I always have a global plugin that sets `timestamps` option to `true` on schemas, and creates a descending index on `createdAt`, because most of the time I wanna show documents in the GUI in descending chronological order.
```js
mongoose.plugin((schema) => {
  if (!schema.get('timestamps')) {
    schema.set('timestamps', true);
  }
  schema.index({ createdAt: -1 });
});
```

The problem with that is that this also creates indexes on all nested schemas/embedded documents.

Is there a way to have the plugin with what we currently have in mongoose to make it so that I only create `createdAt` indexes on the top-level schema only?

### Motivation

I don't want to have unnecessary indexes on my database.

### Example

```js
describe('plugins can set indexes on top-level only', function() {
    it('works with a plugin that sets indexes on top-level only', function() {
      // Arrange
      const m = new mongoose.Mongoose();
      m.plugin(schema => {
        schema.set('timestamps', true);
        schema.index({ createdAt: -1 }); // perhaps an option here `setOnlyIfTopLevel`
      });

      // Act
      const userSchema = new m.Schema({ name: String, friends: [{ name: String }] });
      m.model('User', userSchema);
      console.log(userSchema.indexes());

      // Assert
      assert.equal(userSchema.indexes().length, 1);
    });
  });
```

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez you should be able to do this by combining the `excludeIndexes` option with global schematype configs:

```javascript
// Set `excludeIndexes` by default on all subdocument paths and
// document array paths. This skips index builds.
mongoose.Schema.Types.Subdocument.set('excludeIndexes', true);
mongoose.Schema.Types.DocumentArray.set('excludeIndexes', true);
```

For example, the following script demonstrates that only 1 index is created with the `set('excludeIndexes', true)` lines, but 3 indexes are created if you comment those lines out.

```javascript
'use strict';

const mongoose = require('mongoose');

const { Schema } = mongoose;

// Set `excludeIndexes` by default on all subdocument paths and
// document array paths. This skips index builds.
mongoose.Schema.Types.Subdocument.set('excludeIndexes', true);
mongoose.Schema.Types.DocumentArray.set('excludeIndexes', true);

mongoose.plugin((schema) => {
  if (!schema.get('timestamps')) {
    schema.set('timestamps', true);
  }
  schema.index({ createdAt: -1 });
});

run().catch(err => {
  console.error(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const schema = new Schema({
    doc: new Schema({ name: String }),
    arr: [new Schema({ name: String })]
  });
  const Test = mongoose.model('Test', schema);

  await Test.init();
  console.log(await Test.collection.listIndexes().toArray());
}
```

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez what about `mongoose.set('applyPluginsToChildSchemas', false)` ? That would prevent plugins from running on all child schemas.

Another approach is that schemas have a `$implicitlyCreated` property if Mongoose creates them automatically. We don't currently set that property on implicitly created subdocument schemas, but we should do that anyway. Take a look at the following script and see what you think.

```javascript
'use strict';

const mongoose = require('mongoose');

const { Schema } = mongoose;

mongoose.plugin((schema) => {
  if (!schema.get('timestamps')) {
    schema.set('timestamps', true);
  }
  if (schema.$implicitlyCreated) {
    return;
  }
  schema.index({ createdAt: -1 });
});

run().catch(err => {
  console.error(err);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const schema = new Schema({
    doc: { type: { name: String } },
    arr: [{ name: String }]
  });
  const Test = mongoose.model('Test', schema);

  await Test.init();
  console.log(await Test.collection.listIndexes().toArray()); // Includes `doc.createdAt` index, 
but ignores `arr.createdAt`
}

```

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 `mongoose.set('applyPluginsToChildSchemas', false)` is a little bit too global for my taste, and would cause problems.

For example, I want to always have `timestamps: true` even for implicit schemas, but want to create an index only on the top-level schemas.

`schema.$implicitlyCreated` slightly improves the problem, because in my applications I don't strictly use the implicit schema creation for deeply nested schemas, sometimes I explicitly create `new Schema(...)`, but since it's not on the top level, I don't want indexes on it by default.
