### ISSUE TITLE
Bad Error Messages 

### ISSUE THREAD

**Issue by pvijeh** [Automattic/mongoose#12346]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

"mongoose": "\5.6.0",

### Node.js version

17.9

### MongoDB server version

none

### Description

mongoose is producing this error, which is not particularly helpful

`[📦] TypeError: Cannot read properties of null (reading '1')
[📦]     at model.mongodbErrorHandler (/home/peter/workspace/blockvent-backend/node_modules/mongoose-mongodb-errors/lib/plugin.js:19:49)
[📦]     at callMiddlewareFunction (/home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:483:23)
[📦]     at next (/home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:164:9)
[📦]     at Kareem.execPost (/home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:218:3)
[📦]     at _handleWrapError (/home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:246:21)
[📦]     at _cb (/home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:305:16)
[📦]     at /home/peter/workspace/blockvent-backend/node_modules/mongoose/lib/model.js:380:9
[📦]     at /home/peter/workspace/blockvent-backend/node_modules/kareem/index.js:136:16
[📦]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
`

### Steps to Reproduce

unsure

### Expected Behavior

the error message should provide more detail about whats going on

**Comment by hasezoey** [comment]
at least to me the error seems to come from some plugin's middleware function

PS: please put such test in code-blocks (not inline), see [Github Markdown: Quoting code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by vkarpov15** [comment]
Yeah this error comes from the "mongoose-mongodb-errors" plugin. Not a Mongoose issue.
