### ISSUE TITLE
Allow arrays in .find method

### ISSUE THREAD

**Issue by ELI7VH** [Automattic/mongoose#12340]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like functionality like: 
```js
User.find({
  username: 'eli7vh',
  roles: [ 'artist', 'admin' ] // roles is a [String] type
})
```

right now all I can do is pass single string into the query like so:
```js
User.find({
  username: 'eli7vh',
  roles: 'artist' // can't query admin at the same time :(
})
```
I know there is a way around this, but I don't want to have to write a "$in" for every crud controller, i should just be able to pass in an array to the 'find' and have it serialize it like so.

### Motivation

trying to make cleaner code, unified types

**Comment by Naeoth** [comment]
You should use the function `.in()` in that case

```
User.find({ username: 'eli7vh' }).in('roles', ['artist', 'admin'])
```

**Comment by ELI7VH** [comment]
That is helpful for my domain controllers for sure. 

That said, I am working on a bit of a prototyping system, and I would like to scope queries from the frontend, which means I am just dumping the json payload into the User.find(req.query)
 
 Any ideas on how I could format my GET params into this?
