### ISSUE TITLE
lean option is not respected

### ISSUE THREAD

**Issue by dor-benatia** [Automattic/mongoose#12358]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.7

### Node.js version

16.2.0

### MongoDB server version

5.0.5

### Description

I am using mongoose for quite some time, lately i have noticed that the `lean` option is not respected in mongoose and queries without `.lean` does NOT return mongoose document.

### Steps to Reproduce

this simple code ( which came from this repo `lean.test.js` file will reproduce the bug:

```
import mongoose from 'mongoose';


(async () => {
	const Schema = mongoose.Schema;
	const MessageSchema = new Schema({
		text: {
			type: String,
			required: true,
		},
	});
	const Model = mongoose.model('Message', MessageSchema);

	// Make Mongoose use the ES6 promise
	mongoose.Promise = global.Promise;

	// Connect to a local database called `feathers`
	mongoose.connect('mongodb://localhost:27017/testing');

	const notLean = await Model.find({ text: '1234' }).lean(false);
	const notLean2 = await Model.find({ text: '1234' });
	const lean = await Model.find({ text: '1234' }).lean(true);
	console.log(lean instanceof mongoose.Document); // false
	console.log(notLean instanceof mongoose.Document); // false
	console.log(notLean2 instanceof mongoose.Document); // false
	console.log(notLean.constructor.name); // 'Array'
	console.log(notLean2.constructor.name); // Array'
	console.log(lean.constructor.name); // Array'
})();
```

### Expected Behavior

to be according to the test and docs. without 'lean()', i will get back a mongoose document object.

**Comment by hasezoey** [comment]
i dont know what `lean.test.js` file you saw, but the [current `lean.test.js`](https://github.com/Automattic/mongoose/blob/24a08fe467c516efa9f19397ccead3cd3b57e6a1/test/docs/lean.test.js) file uses `findOne`, instead of `find` and returns the correct result:

<details>
<summary>Code</summary>

```ts
// NodeJS: 18.7.0
// MongoDB: 5.0 (Docker)
// Typescript 4.8.2
import * as mongoose from 'mongoose'; // mongoose@6.5.3

const MessageSchema = new mongoose.Schema({
  text: {
    type: String,
    required: true,
  },
});
const Model = mongoose.model('Message', MessageSchema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  await Model.create({ text: '1234' });

  const notLean = await Model.findOne({ text: '1234' }).orFail().lean(false);
  const notLean2 = await Model.findOne({ text: '1234' }).orFail();
  const lean = await Model.findOne({ text: '1234' }).orFail().lean(true);
  console.log('lean instanceof Document', lean instanceof mongoose.Document);
  console.log('notLeat instanceof Document', notLean instanceof mongoose.Document);
  console.log('notLean2 instanceof Document', notLean2 instanceof mongoose.Document);
  console.log('lean constructor name', lean.constructor.name);
  console.log('notLean constructor name', notLean.constructor.name);
  console.log('notLean2 constructor name', notLean2.constructor.name);

  await mongoose.disconnect();
})();
```

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseGh12358

</details>

result:
```txt
lean instanceof Document false
notLeat instanceof Document true
notLean2 instanceof Document true
lean constructor name Object
notLean constructor name model
notLean2 constructor name model
```

PS: also when using `find` and then correcting the code to `val[0]` (instead of just `val`) returns the correct results

**Comment by IslandRhythms** [comment]
For whatever reason its the typescript version your are on. I upgraded my typescript to match hasezoey and i went from reproducing your result to theirs.

**Comment by IslandRhythms** [comment]
Use `findOne`
