### ISSUE TITLE
Add `Schema#alias()` function that defines a new alias

### ISSUE THREAD

**Issue by IslandRhythms** [Automattic/mongoose#12368]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

When creating documents from api data, users will sometimes have their schemas be identical to the keys coming in. Therefore, I propose we create a function that does the mapping and returns the resultant object.

### Motivation

It is a bit tedious to have to manually map the result of the api call to your documents when the keys are identical. We could possibly take this one step further and implement an option that converts the keys of the apiResult to match the ones defined in mongoose. So if an api is in snake case but your models are in camel case, the function would convert the keys to camel, then map.

### Example

```javascript
function apiMap(apiResult, schema) {
  const mongooseDoc = {};
  schema.keyName === apiResult.keyName
  mongooseDoc[schema.keyName] = apiResult.keyValue

  return mongooseDoc
}

const guts = apiMap(apiResult, schema)
await Model.create(guts);
```

**Comment by akshay-nm** [comment]
I'd like to see an example of where this could be used just out of curiosity.
