### ISSUE TITLE
🙋 Typescript: type declare issue with Next js

### ISSUE THREAD

**Issue by Charlygraphy23** [Automattic/mongoose#12360]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.x

### Node.js version

12.x

### MongoDB version

5.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I have declare a model using `mongoose.model` and its working fine 😀.

But in next js to i getting error - 😒
`error - OverwriteModelError: Cannot overwrite `projects` model once compiled.`

to resolve this issue i have applied below code but in that code type has changed to any.
So i want a suggestion to override that.😔

![image](https://user-images.githubusercontent.com/46165735/187495788-13133fd6-ad42-4c16-b587-4f194de4d5f1.png)

**Comment by IslandRhythms** [comment]
That error occurs when the model already exists in the db and you're attempting to re-create it, which it prevents.

**Comment by IslandRhythms** [comment]
```typescript
// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

// 3. Create a Model.
const User = model<IUser>('User', userSchema);
```

**Comment by Charlygraphy23** [comment]
> mongoose.model

Yes that will work. But I am working with Next js so it doesn't allow me create new Schema every time a model calls.
that why id find a solution `mongoose.models.MODEL_NAME`
this works fine then the type change
