### ISSUE TITLE
field with Types.ObjectId has typescript error in Schema

### ISSUE THREAD

**Issue by joonseokhu** [Automattic/mongoose#12364]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.4

### Node.js version

16.14.2

### MongoDB version

doesn't matter

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Issue

```typescript
import { Schema, Types } from 'mongoose';

interface Foo {
  _id: Types.ObjectId,
  bar: Types.ObjectId,
}

const FooSchema = new Schema<Foo>({
  _id: { type: Types.ObjectId },
  bar: { type: Types.ObjectId },
});
```

property `_id` and `bar` has typescript error:

```
Type '{ type: typeof Types.ObjectId; }' is not assignable to type 'SchemaDefinitionProperty<ObjectId> | undefined'.
  Types of property 'type' are incompatible.
    Type 'typeof ObjectId' is not assignable to type 'typeof Mixed | ObjectIdSchemaDefinition | undefined'.ts(2322)
```

But I cannot figure out why, and don't know how to solve it.

**Comment by hasezoey** [comment]
the proper type for use in schema would be `mongoose.Schema.Types.ObjectId` and not `mongoose.Types.ObjectId` (also dont use directly from `bson`, if the import should show up)

**Comment by joonseokhu** [comment]
@hasezoey Thanks! didn't know that.
But I have another question your answer. 🥲 Then what is the purpse of the `mongoose.Types.ObjectId` if we have to use `mongoose.Schema.Types.ObjectId` instead of `mongoose.Types.ObjectId`? Looks like we don't need it anymore.

**Comment by hasezoey** [comment]
> mongoose.Schema.Types.*

are used for schema definition (and only there)

> mongoose.Types.*

are used for runtime type creation / how (non primitive) types are represented in a created document, like `new mongoose.Types.ObjectId("hexCode")`

**Comment by joonseokhu** [comment]
Thanks again! @hasezoey :) I have another question again.

Then, how can I get **the exact type of the document**?

```typescript
type IsSameType<A, B> = A extends B ? B extends A ? true : false : false;

interface MyEntitySchema {
  _id: Schema.Types.ObjectId;
}

type MyEntityDoc1 = HydratedDocument<MyEntitySchema>;
type MyEntityDoc2 = LeanDocument<MyEntitySchema>;
type MyEntityDoc3 = LeanDocument<HydratedDocument<MyEntitySchema>>;

const testA: IsSameType<MyEntityDoc1['_id'], Types.ObjectId> = false;
const testB: IsSameType<MyEntityDoc1['_id'], Schema.Types.ObjectId> = true;

const testC: IsSameType<MyEntityDoc2['_id'], Types.ObjectId> = false;
const testD: IsSameType<MyEntityDoc2['_id'], Schema.Types.ObjectId> = true;

const testE: IsSameType<MyEntityDoc3['_id'], Types.ObjectId> = false;
const testF: IsSameType<MyEntityDoc3['_id'], Schema.Types.ObjectId> = true;
```

I tried few things with `HydratedDocument` and `LeanDocument` but they don't change the `Schema.Types.ObjectId` into `Types.ObjectId`. 🥲

**Comment by hasezoey** [comment]
> I tried few things with `HydratedDocument` and `LeanDocument` but they don't change the `Schema.Types.ObjectId` into `Types.ObjectId`. smiling_face_with_tear

the proper type should be `type YourDocument = mongoose.Document<IdType> & YourSchema`, also see [Mongoose Documentation: Typescript](https://mongoosejs.com/docs/typescript.html)

see typegoose's implementation for a full (generic) example:
https://github.com/typegoose/typegoose/blob/06f710df2d47a7501a496dc877dce955e047fe2b/src/types.ts#L14-L18
```ts
// the following is from typegoose, modified without typegoose-specific things
export type DocumentType<T, QueryHelpers = BeAnObject> = (T extends { _id: unknown }
  ? mongoose.Document<T['_id'], QueryHelpers, T>
  : mongoose.Document<any, QueryHelpers, T>) &
  T;
```

**Comment by joonseokhu** [comment]
Thanks! I'm trying as you answered, and got some troubles

```typescript
interface MyEntitySchema {
  _id: Schema.Types.ObjectId;
  items: Schema.Types.ObjectId[]; // ids without ref
}

type MyEntityDoc = Document<any> & MyEntitySchema;
/*                          | [trouble 1]       */

const test1: MyEntityDoc = {
  _id: new Types.ObjectId(),
  items: [new Types.ObjectId()], // [trouble 2]
}
```

1. I had to use `any` as generic in Document, or the type of _id is `Schema.Types.ObjectId & Types.ObjectId` which does not match to the type of `new Types.ObjectId()`
2. other fields in ObjectId types except the `_id` is still `Schema.Types.ObjectId`.

Is there any helper type like this? 🥹
```typescript
type ObjectIdMapper<T> = {
  [Key: keyof T]: T[Key] extends Schema.Types.ObjectId ? Types.ObjectId : T[Key]
}
```

**Comment by hasezoey** [comment]
sorry that i didnt see that before, but yes mongoose currently does not translate `mongoose.Schema.Types.*` to `mongoose.Types.*` in types and you have to use the latter for the types, but the former for the Schema itself (in `new Schema(here)`)

**Comment by kfekairii** [comment]
Take a look at this (from mongoose documentation)

```
import { Schema, Types } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  // Use `Types.ObjectId` in document interface...
  organization: Types.ObjectId;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  // And `Schema.Types.ObjectId` in the schema definition.
  organization: { type: Schema.Types.ObjectId, ref: 'Organization' }
});
```
