### ISSUE TITLE
findOneAndUpdate hangs when using async/await

### ISSUE THREAD

**Issue by dtk9289** [Automattic/mongoose#12362]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.3

### Node.js version

16.x

### MongoDB version

5.x

### Operating system

Linux

### Issue

```javascript
async function fnA(filter, update){
  const updated = await Note.findOneAndUpdate(filter, update)

  if(updated) console.log(updated)
}
```

when i run fnA, if **filter** is correct it's working but if i change **filter** to a value which is not in collection, the function hangs up, it doesn't return or print any error

when i use promise style, this behaviour doesn't happen

**Comment by Naeoth** [comment]
What you want is: https://mongoosejs.com/docs/api.html#query_Query-orFail

So you should add .orFail() if you wish `findOneAndUpdate` to throw an error if there is no find document

**Comment by dtk9289** [comment]
> What you want is: https://mongoosejs.com/docs/api.html#query_Query-orFail
> 
> So you should add .orFail() if you wish `findOneAndUpdate` to throw an error if there is no find document

thanks, i searched through 10 pages of google but cant find a hint about this
