### ISSUE TITLE
Alias models can cause silent errors and data corruption

### ISSUE THREAD

**Issue by MarkVasile** [Automattic/mongoose#12386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.4

### Node.js version

14.x ~ 16.x

### MongoDB server version

6.x

### Description

When using aliases in the query, we can sometimes get silent validation errors which completely drop our filters. The result is that an update such as `repos.updateMany({ origin, 'auth.u': uid }, { $set: { active: false } })` will cause all records to update, not just the ones we filter for.

Example repo that reproduces this error: https://github.com/MarkVasile/test-mongoose

### Steps to Reproduce

Example repo that reproduces this error: https://github.com/MarkVasile/test-mongoose

### Expected Behavior

The findOne query in the sample code should fail.

**Comment by IslandRhythms** [comment]
I'm pretty sure this is expected behavior. When you query with a field that does not exist, it is interpreted as if there is nothing in the args. You need to use `translateAliases` in your query

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  n: {
    type: String,
    alias: 'name'
  }
});

const Test = mongoose.model('Test', testSchema);


async function run() {
  await mongoose.connect('mongodb://localhost:27017')
  await mongoose.connection.dropDatabase();

  await Test.create({
    n: 'Test 1'
  });

  await Test.create({
    n: 'Test 2'
  });

  console.log(await Test.findOne(undefined));
  console.log( await Test.findOne({ age: 2 }));
  console.log(await Test.findOne({ name: 'Test 2'}));
  console.log(await Test.findOne({ n: 'Test 2'}))
  console.log(await Test.findOne(Test.translateAliases({ name: 'Test 2'})))
}

run();
```

**Comment by MarkVasile** [comment]
Also, if i may point out, interpreting our queries like "if field does not exist = let's return all documents" is a very obvious danger, even when well documented. 

It goes contrary to the real MongoDB query mechanism where querying a field that does not exist returns NO document, rather than ALL documents.

**Comment by MarkVasile** [comment]
Ok, I gave it this some more effort to understand, and it seems something has changed between Mongoose 5 and Mongoose 6, where in v5 the aliases were transformed automatically, but in v6 it requires translateAliases, like you pointed out here. I couldn't find anything related to this BREAKING CHANGE in the change log.
