### ISSUE TITLE
Mongoose not saving nested documents

### ISSUE THREAD

**Issue by jamesbruice** [Automattic/mongoose#12398]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.12.14

### Node.js version

v16.13.1

### MongoDB server version

5.0.11

### Description

When modifying a field on a populated document, changes should be saved, when saving the parent.

This is not occ, instead I need to save the document myself (see Steps to Reproduce)

### Steps to Reproduce

Schemas
```
const boardSchema = new Schema({
    name: {
        type: String,
        required: true
    },
    tasks: [
        {
            type: Schema.Types.ObjectId,
            ref: 'Task'
        }
    ]
})
```

```
const taskSchema = new mongoose.Schema({
    name: {
        type: String
    },
    description: String
})
```

route to change name
```
router.patch('/:boardId/:taskId', async (req, res) => {
    const { boardId, taskId } = req.params
    const { value } = req.body
    const board = await Board.findById(boardId).populate('tasks')

    board.tasks.find(x => x._id.toString() === taskId).name = value

    //await board.tasks[0].save() // <--------- Saving changes to task[0] // THIS SHOULD NOT BE REQUIRED
    await board.save() // <-------------------- Not saving changes to nested tasks (e.g. the name)
    res.json(board) // <----------------------- Showing correct change
    res.send('OK')
})
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/111875440/188515139-8538e959-084b-4ca1-a479-8cddeb2dc98b.png)
https://mongoosejs.com/docs/subdocs.html#subdocuments

Saving the tasks individually should not be required. They should be saved when the parent is being saved

**Comment by lpizzinidev** [comment]
Your `Board` model contains a `ref` to the `Task` model, if you want to update the name of a certain `Task` you should update the `Task` directly with `findByIdAndUpdate`:
```
router.patch('/:boardId/:taskId', async (req, res) => {
    try {
        const { boardId, taskId } = req.params;
        const { value } = req.body;

        const task = await Task.findByIdAndUpdate(taskId, { name: value }, { new: true });
        
        res.status(200).json(task);
    } catch (e) {
        res.status(500).json({ message: 'Server error' });
    }
})
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');


const aSchema = new mongoose.Schema({
  name: String
});

const bSchema = new mongoose.Schema({
  persons: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'A'
  }]
});

const A = mongoose.model('A', aSchema);
const B = mongoose.model('B', bSchema);


async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const person1 = await A.create({ name: 'Test Testerson' });
  const person2 = await A.create({ name: 'Test' });
  const id = person2._id;

  await B.create({ persons: [person1._id, person2._id] });

  const test = await B.findOne().populate('persons');
  console.log(test);
  test.persons.find(x => x._id.toString() === id.toString()).name = 'Value Changed';
  await test.save();
  // await test.persons[0].save();
  // await test.persons[1].save();
  const res = await B.findOne().populate('persons');
  console.log(res);
}

run();
```

**Comment by IslandRhythms** [comment]
Populated docs are different from subdocs. If you set a populated value, you need to call save on the doc.

**Comment by jamesbruice** [comment]
Could you explain the difference between a ref and a subdocument? @IslandRhythms

**Comment by IslandRhythms** [comment]
A ref indicates what Model populate should look at when querying the indicated path. A subdocument is described in the image you attached to this issue.

**Comment by vkarpov15** [comment]
@jamesbruice when you populate a `ref`, you get a populated document, which is a distinct top-level document, rather than a subdocument embedded in your document. The difference is that an embedded subdocument is stored in MongoDB as a subdocument, rather than as an ObjectId that refers to another document.
