### ISSUE TITLE
Model.update claims success but document is not updated

### ISSUE THREAD

**Issue by davisford** [Automattic/mongoose#1240]
``` sh
$npm list | grep mongoose
├─┬ mongoose@3.3.1
```

code:

``` javascript
update: function (device) {
      if (!device) {
        return res("cannot update null device");
      }
      console.log(device);
      Device.update({ uuid: device.uuid }, {
        prop1: device.prop1,
        prop2: device.prop2
      }, function (err, numAffected, raw) {
        if (err) { console.log(err); return res(err, null); }
        console.log('# devices updated: %d, mongo-raw: %s', numAffected, JSON.stringify(raw, null, 2));
        return res(null, device);
      });
    }
```

console.log when function is called with valid input;

``` sh
# devices updated: 1, mongo-raw: {
  "updatedExisting": true,
  "n": 1,
  "connectionId": 49,
  "err": null,
  "ok": 1
}
```

prop1 and prop2 are type `Boolean`, I am calling the `update` function toggling the values between true/false, but if I go to the mongodb console, and query `db.devices.find()` the values are never committed.

I tried `show log global` and saw nothing interesting -- the mongod instance is running with default log level.  Where can I look further to figure out why this is not working?  It used to work, and the code has not changed, so I'm a bit stumped what is going wrong now.

I re-wrote as:

``` javascript
Device.findOne({uuid: device.uuid}, function (err, doc) {
        if (err) {
          console.log(err);
          return res('Device update failed', null);
        }
        doc.prop1 = device.prop1;
        doc.prop2 = device.prop2;
        doc.save(function (err, doc) {
          if (err) {
            console.log(err);
            return res('Device update failed', null);
          }
          console.log('save was successful ? => \n', doc);
          return res(null, doc);
        });
      });
```

It still reports success, no `err`, but if I go back to the console and query `db.devices.find()` the values have not changed.

**Comment by bevlison** [comment]
I had the issue : 

> Model.update claims success but document is not updated 

The cause turned out to be the addition of a new field, which was not defined yet in the model. Fields that are defined in the model are not updated either. 

The update/save function seems to have an error that interrupts the save, but it does NOT pass through in the callback.

**Comment by lineus** [comment]
@bevlison paths that **are defined** in the model **should be** updated. Paths that **aren't defined** in the model **should not** be updated. The following example shows that it's working correctly on 5.2.3 (mongoose@latest). If you are experiencing different behavior please open an issue with a code sample that demonstrates the behavior. Make sure to include the version of mongoose you're using. 

### 1240.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'one' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  let cond = { _id: test._id };
  let update = { name: 'two', nope: 'xyz' };
  let res = await Test.update(cond, update);
  assert.strictEqual(res.nModified, 1);
  let found = await Test.findOne(cond);
  assert.strictEqual(found.name, 'two');
  assert.strictEqual(found.nope, undefined);
  console.log('Passed: name updated successfully, nope not set.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./1240.js
Passed: name updated successfully, nope not set.
issues:
```

**Comment by krishnadeveloper** [comment]
I am also having the same issue.
