### ISSUE TITLE
When the field is not defined in the mongoose.model(), the filter condition {field: {$exists: true}} in the collection.find() does not take effect

### ISSUE THREAD

**Issue by maohuYang** [Automattic/mongoose#12402]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.7

### Node.js version

14.17.5

### MongoDB server version

4.4.5

### Description

User model is defined as follows:
const User= _mongoDB.model('user', {
age: Number,
name: String
});

Collection in database: 
{"age" : 19,"name" : "Tom,"six" : "M}
{"age" : 20,"name" : "Li"}

If I use  `Uer.find({six: {$exists: true}}) `  to query, I will get all the data:
{"age" : 19,"name" : "Tom,"six" : "M}
{"age" : 20,"name" : "Li"}

### Steps to Reproduce

User model is defined as follows:
const User= _mongoDB.model('user', {
age: Number,
name: String
});

Collection in database: 
{"age" : 19,"name" : "Tom,"six" : "M}
{"age" : 20,"name" : "Li"}

If I use  `Uer.find({six: {$exists: true}}) `  to query, I will get all the data:
{"age" : 19,"name" : "Tom,"six" : "M}
{"age" : 20,"name" : "Li"}

**Comment by lpizzinidev** [comment]
To reproduce:
```
import mongoose from 'mongoose';

const User = mongoose.model('user', {
  age: Number,
  name: String,
});

const run = async () => {
  try {
    await mongoose.connect('mongodb://localhost:27017/test');
    // Clear database table
    await User.remove({});
    // Insert users
    await User.create({ age: 10, name: 'Test' });
    await User.create({ age: 10, name: 'Example' });
    await User.create({ age: 10 });
    // Retrieve users
    const users = await User.find({ six: { $exists: true } });
    console.log(users);

    process.exit(1);
  } catch (e) {
    console.log(e);
    process.exit(1);
  }
};

run();
```

**Comment by sean-daley** [comment]
Looks like another incident of the `strictQuery` change in mongoose 6.
See https://github.com/Automattic/mongoose/issues/11861 for more info (as well as additional links to other issues which document this).

**Comment by maohuYang** [comment]
https://mongoosejs.com/docs/guide.html#strictQuery
