### ISSUE TITLE
MongoServerError: Invalid $set :: caused by :: Unrecognized expression '$sortArray

### ISSUE THREAD

**Issue by vnugent** [Automattic/mongoose#12415]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.7

### Node.js version

16

### MongoDB server version

6

### Description

Is [$sortArray](https://www.mongodb.com/docs/manual/reference/operator/aggregation/sortArray/) supported?

We're building a document tracking system and need to sort an array of changes (think of them as individual "git" commits).

```
Error:    MongoServerError: Invalid $set :: caused by :: Unrecognized expression '$sortArray'
```

### Steps to Reproduce

```
[
{
    _id: ObjectId('631c63f50ec04fed51a687dc'),
    createdAt: "2022-09-10T10:38:24.791Z"
    changes: [
        {
            fullDocument: {
                _change: {
                    user: UUID("78a7bfaf173b460d84b34cca4aa12c03"),
                    operation: 'addArea',
                    seq: 0,
                },
            },
        },
        {
            fullDocument: {
                _change: {
                    user: UUID("78a7bfaf173b460d84b34cca4aa12c03"),
                    operation: 'updateCountry',
                    seq: 1,
                },
            },
        }
    ],
}
...
]

```
Code
```
      const rs2 = await this.changelogModel
        .aggregate([
          filter,
          {
            $set: {
              changes: {
                $sortArray: {
                  input: '$changes',
                  sortBy: { 'fullDocument._change.seq': -1 }
                }
              }
            }
          },

```

### Expected Behavior

$sortArray is working

Edit:  add createdAt timestamp to example data

**Comment by AbdelrahmanHafez** [comment]
Mongoose does not do any casting logic to aggregation pipelines. The error you're receiving is from the MongoDB server side, not from Mongoose.

I think what you want to do is `.updateOne/.updateMany` instead of `.aggregate`.

**Comment by vnugent** [comment]
Sorry I wasn't clear.  I want to **query** and **sort** the result first by document's timestamp (createdA)t and within each document I want to short `changes` by `seq`.  

A simpler analogy would be having a collection of bands and a nested array their tour dates.   Write a query to sort the collection by `bandName` and sort each band tours by date.
```
[
  {
     bandName: "The Beatles",
     tours: [
     {
        date: "2022-09-10T10:38:24.791Z"
        location: "San Francisco"
     },
     {
        date: "2022-09-15T10:38:24.791Z"
        location: "Seatle"
      }
     ]
  },
...
```

**Comment by AbdelrahmanHafez** [comment]
I built [this mongo playground](https://mongoplayground.net/p/3sCYkQg_RBn) that shows an example of how you'd use `$sortArray` in an aggregation pipeline.

Let me know if that solves the issue you're facing.

**Comment by vnugent** [comment]
Thanks for the playground.  I copied your query verbatim, same error.  I noticed that you use `db.collection.aggregate` whereas I use Mongoose model

**Comment by AbdelrahmanHafez** [comment]
@vnugent 
This is probably an issue with your MongoDB server version, it does not support $sortArray yet, you probably need to update it.
Please try to run the following script and see if it fails for you, and share the output in this issue.

### 12415.js
```js
'use strict';
const mongoose = require('mongoose');
const assert = require('node:assert');
const { Schema } = mongoose;

const changeLogSchema = new Schema({
  bandName: String,
  tours: [{
    date: Date,
    location: String
  }]
});


const ChangeLog = mongoose.model('change_logs', changeLogSchema);

run().catch(console.error);

async function run() {
  // Arrange
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();
  const admin = new mongoose.mongo.Admin(mongoose.connection.db);
  const buildInfo = await admin.buildInfo();
  console.log('MongoDB server version', buildInfo.version);

  await ChangeLog.insertMany([
    {
      bandName: 'B',
      tours: [
        { date: new Date('2022-09-15T10:38:24.791Z'), location: 'San Francisco' },
        { date: new Date('2022-09-10T10:38:24.791Z'), location: 'Seatle' }
      ]
    },
    {
      bandName: 'A',
      tours: [
        { date: new Date('2022-09-15T10:38:24.791Z'), location: 'San Francisco' },
        { date: new Date('2022-09-10T10:38:24.791Z'), location: 'Seatle' }
      ]
    }]);
  // Act
  const docs = await ChangeLog.aggregate([
    {
      $sort: {
        bandName: 1
      }
    },
    {
      $set: {
        tours: {
          $sortArray: {
            input: '$tours',
            sortBy: {
              date: 1
            }
          }
        }
      }
    }
  ]);

  // Assert
  assert.strictEqual(docs[0].bandName, 'A');
  assert.strictEqual(docs[1].bandName, 'B');
  assert.strictEqual(docs[0].tours[0].location, 'Seatle');
  assert.strictEqual(docs[1].tours[0].location, 'Seatle');
  console.log('Assertion passed');
  console.log('Mongoose version', mongoose.version);
}
```

### Output
```
$ node 12415.js
MongoDB server version 6.0.1
Assertion passed
Mongoose version 6.6.0
```

You can test with mongo 6 locally using Docker:
```
docker container run -p 27017:27017 mongo:6
```

**Comment by vnugent** [comment]
You're right.  We're using hosted mongo on DigitalOcean and I thought we're on v6, but it's actually `5.0.8`.  Let me open a support ticket to see if it's possible to upgrade. 

Thanks so much for your time.
