### ISSUE TITLE
Error when trying to connect to db.

### ISSUE THREAD

**Issue by Jacob1Tm** [Automattic/mongoose#12416]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

6.6.0

### Node.js version

18.x

### MongoDB version

5.0.12

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

So when I try to connect to my db I have an error
```
Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.0ltupff.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:dns:303:19) {      
  errno: undefined,
  code: 'ECONNREFUSED',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.cluster0.0ltupff.mongodb.net'
}
```
link that I use to connect is
```
mongodb+srv://<username>:<password>@cluster0.0ltupff.mongodb.net/Cluster0?retryWrites=true&w=majority
```
And yes, I have a correct username and password. My IP is allowed too.

**Comment by Jacob1Tm** [comment]
Im trying to connect my discord bot to database and i have all IP allowed

**Comment by IslandRhythms** [comment]
Make sure you call connect before you login with your bot token

**Comment by Jacob1Tm** [comment]
So i changed that it first tries to connect to the database but that didn't changed anything

**Comment by IslandRhythms** [comment]
Can you please provide the script where you connect, login, and where you call connect.

**Comment by Jacob1Tm** [comment]
https://github.com/Jacob1Tm/Jacob-bot/blob/master/index.js
But just saying my bot is in polish

**Comment by IslandRhythms** [comment]
Where is the error firing from? is it firing from the catch block or?

**Comment by Jacob1Tm** [comment]
In catch just with console.log(e):

**Comment by IslandRhythms** [comment]
Did you verify your .env variables are going through correctly? Try console logging your env variables.

**Comment by IslandRhythms** [comment]
Did you upgrade anything that day?

**Comment by IslandRhythms** [comment]
Did your mongoshell crash? Is your mongo server running?

**Comment by Jacob1Tm** [comment]
Server is running on mongo's cloud so

**Comment by IslandRhythms** [comment]
Can you connect locally though?

**Comment by IslandRhythms** [comment]
`mongodb://localhost:27017/test`

**Comment by Jacob1Tm** [comment]
I never really used it locally, so let me download and test that

~~I should test that before :<~~

**Comment by Jacob1Tm** [comment]
Sorry it takes a while to download 500mb with my awesome internet, but result is that I can't, it returns this
```
MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at Connection.openUri (C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\connection.js:824:32)
    at C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\index.js:381:10
    at C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\index.js:1234:10)
    at Mongoose.connect (C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\node_modules\mongoose\lib\index.js:380:20)
    at Object.<anonymous> (C:\Users\jakub\OneDrive\Pulpit\Repos\Jacob-bot\index.js:20:10)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
```
I just installed it so

**Comment by IslandRhythms** [comment]
localhost for node 17 and up is different than v 16 and below. use `0.0.0.0` for the localhost part

**Comment by Jacob1Tm** [comment]
Oh, I see now it connected to local database

**Comment by Jacob1Tm** [comment]
but still i can't really connect to that from cloud

**Comment by Jacob1Tm** [comment]
And now to be sure I added new user and that didn't change anything

**Comment by Jacob1Tm** [comment]
Funny thing, my friend logged in without trouble...

**Comment by Jacob1Tm** [comment]
I will try to contact with their support, maybe they can help somehow

**Comment by IslandRhythms** [comment]
Did you set your env variables in heroku?
Also I think heroku got rid of their free tier so its possible they stopped your bot and are waiting for you to either upgrade the account or not.

**Comment by Jacob1Tm** [comment]
Yes i have that set up in settings and they will remove free dynos on 28 october i guess

**Comment by Jacob1Tm** [comment]
I just moved my bot to server on digital ocean i stilo can't Access db dron my pc but anyways.
