### ISSUE TITLE
Remove hook not triggered when removing documents

### ISSUE THREAD

**Issue by SirPepe** [Automattic/mongoose#1241]
The pre/post hooks for `remove` are only triggered when using the document instance's `remove()` method, not when the model's methods are used:

``` javascript
var mongoose = require("mongoose");
var db = mongoose.createConnection('mongodb://localhost/experiment');
db.once('open', function(){

  testSchema = new mongoose.Schema({ title: String });
  testSchema.post('remove', function(removed){
    console.log('removed', removed.title);
  });
  var Test = db.model('Test', testSchema);

  // > "removed A"
  new Test({ title: 'A' }).save(function(err, created){
    created.remove();
  });

  // Nothing :(
  Test({ title: 'B' }).save(function(err, created){
    Test.remove({ title: 'B' }).exec();
  });

  // Nothing :(
  Test({ title: 'C' }).save(function(err, created){
    Test.find({ title: 'C' }).remove();
  });

});
```

**Comment by gregthegeek** [comment]
Would it be possible to add support for `Query.remove()` hooks now with the query middleware in 4.0?

**Comment by vkarpov15** [comment]
Not right now - that's very tricky because there's already middleware for `Model.remove()`

**Comment by gregthegeek** [comment]
Would there be any issue other than the name conflict? Couldn't you just call the hook 'remove-query' or something instead of 'remove'?

**Comment by gregthegeek** [comment]
Or how about do what you seem to do with update - call the query hook even when the doc version of the function is used. Of course this would break backwards-compatibility, but it's an idea.

**Comment by vkarpov15** [comment]
Seems like a reasonable idea, but I'm hesitant to break API unless there's a really good reason to. Right now the remove hook operates on a document, so the context in the middleware is the document. For general `Query.remove()`, the document might not even be in memory. I suppose we could name it something else like 'remove-query`, but that's nasty. What do you think about adding an extra options arg to `pre()` and `post()`, something like:

```javascript
schema.pre('remove', { query: true }, function() {
  // This is only attached as query middleware
});

schema.pre('remove', { doc: true }, function() {
  // This will not run on Query.remove(), only doc.remove()
});
```

**Comment by gregthegeek** [comment]
I suppose that could work. It's probably better than just using a different name and it doesn't break the API. So I guess if someone did

    schema.pre('remove', { query: true, doc: true }, function() {
        
    });

The hook would be called on both query and doc requests. I guess a user could do this if they didn't care about the context. If you do this, though, you'd probably want to also change the `update` hook to match this new style, and that could potentially break people's code.

**Comment by vkarpov15** [comment]
Yeah the tricky bit in that context is "what's the default?" In order to preserve API, we'd have to make it so that update is a query middleware by default, but remove is a document middleware by default. That will be very weird. I think we should just open up a separate issue for 5.0 and worry about it later :)

**Comment by gregthegeek** [comment]
How about, just for the next version or some version in the near future, we can just call the hook 'remove-query' or something? It doesn't break the API and AFAIK should be pretty easy to implement. We could really use this feature, as right now you can't capture 100% of remove requests via middleware and we'd much rather do this than enforce certain techniques in our codebase. In 5.0 we can do it the "right way" but I'd love to just see this quick addition before v5.

**Comment by vkarpov15** [comment]
Alternative approach: how about we just make a `preQuery()` and `postQuery()` function?

**Comment by gregthegeek** [comment]
So instead of writing
````javascript
schema.pre('remove', function() {
    // What is this? A doc hook? A query hook? Idk man
});
````
you'd write
````javascript
schema.preQuery('remove', function() {
    // This is definitely a doc hook
});
````

**Comment by vkarpov15** [comment]
Yeah `preQuery()` would be a good way to preserve the API until we can figure out a cleaner API. I would imagine `preQuery()` might be deprecated immediately though, because I'm not quite thrilled with the syntax.

**Comment by Gp2mv3** [comment]
This issue is still open, is it fixed ?
What about preQuery ?

**Comment by vkarpov15** [comment]
The issue of pre remove for documents vs queries is tracked in #3054, not implemented yet, PRs welcome.
