### ISSUE TITLE
TypeError when using Mongoose as a pkg dependency in monorepo

### ISSUE THREAD

**Issue by DLesage25** [Automattic/mongoose#12426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.0

### Node.js version

16.14.2

### MongoDB server version

5.0.10

### Description

I have an API on a turborepo monorepo and am trying to run the bundle via `node dist/main.js`. The API requires one private package available in the monorepo called `shared`. which only contains schema files (user.schema.ts). 

When I try to run the bundle, I get the following message:
```
/Users/d/project/packages/shared/node_modules/mongoose/lib/schematype.js:43
  this[schemaTypeSymbol] = true;
                         ^

TypeError: Cannot set properties of undefined (setting 'Symbol(mongoose#schemaType)')
```

For reference, this is the shared pkg package.json:
```
{
    "name": "shared",
    "version": "0.0.0",
    "private": true,
    "main": "./dist/index.js",
    "module": "./dist/index.mjs",
    "types": "./dist/index.d.ts",
    "sideEffects": false,
    "scripts": {
        "build": "tsc --project tsconfig.json --declaration --esModuleInterop"
    },
    "files": [
        "src/**"
    ],
    "dependencies": {
        "@nestjs/common": "^9.0.11",
        "@nestjs/core": "^9.0.11",
        "@nestjs/mongoose": "^9.2.0",
        "mongoose": "^6.6.0",
        "reflect-metadata": "^0.1.13",
        "rxjs": "^7.5.6"
    },
    "devDependencies": {
        "class-transformer": "^0.5.1",
        "class-validator": "^0.13.2"
    }
}
```
 

### Steps to Reproduce

1. Create a NestJS app.
2. Require a private local package that has the `mongoose` dependency and a schema file.
3. Bundle NestJS app.
4. Attempt to run via `node dist/main.js`

### Expected Behavior

The bundle should work as expected, including the schema files imported from the local private package.

**Comment by DLesage25** [comment]
Fixed. When installing mongoose on the private package, yarn had resolved version `6.6.0`, which apparently causes the bug I mentioned above. Reverting back to `6.5.4` did the trick for me.

**Comment by vkarpov15** [comment]
Realistically, there's no way we're going to be able to repro this without a standalone repo that demonstrates the issue. Too many unknowns for us to guess what OP's setup is like.

**Comment by jsanchez-innomius** [comment]
This happens when you have two different mongoose versions, one in the package ( or library) and other in the application. This happens to me with version 7.1.0 and 7.1.1
It is not supposed that the package should decide which version to use and use the same in both packages?

**Comment by vkarpov15** [comment]
@jsanchez-innomius what do you mean by "It is not supposed that the package should decide which version to use and use the same in both packages?"
