### ISSUE TITLE
User is not allowed to do action [find] on [ecommerce.users]

### ISSUE THREAD

**Issue by ogibinedi** [Automattic/mongoose#12424]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have Controller like this:
### User Controller
```javascript
const Users = require("../models/userModel");

const userController = {
    register: async (req, res) => {
        try {
            const { name, email, password } = req.body;
            const user = await Users.findOne({email}); // the problem came from here
            if(user) return res.status(400).json({msg: "The email already registered"});
            if(password.length < 6) return res.status(400).json({msg: "Please input password at least 6 characters or more"})
        } catch (error) {
            return res.status(500).json({msg: error.message});
        }
    }
};


module.exports = userController;
```
this code produce ``user is not allowed to do action [find] on [ecommerce.users]`` when i hit using postman at localhost
i am using mongoose@^5.13.15

**Comment by IslandRhythms** [comment]
Have you set any permissions in your codebase? That message does not exist in our repository.
