### ISSUE TITLE
`toObject()`: virtuals on subdocuments not available when using default options

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#12425]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.5

### Node.js version

12.22.12

### MongoDB version

4.4.6

### Operating system

Linux

### Issue

This might be a bug, not sure.

With `toObject()` there are a few ways to indicate that virtuals should be included in the output.

1. `mongoose.set("toObject", { virtuals: true })`
2. `schema.set("toObject", { virtuals: true })`
3. `document.toObject({ virtuals: true })`

When using either of the first two approaches (aka. setting `{ virtuals: true }` by default and then calling `document.toObject()`), virtuals are not applied to subdocuments. _They are applied_, however, when using approach # 3! Also note that `getters: true` vs `virtuals: true` makes no difference.

Is this behavior expected?

If it is, it would be nice to understand why : ]

I've found it really difficult to answer this question by inspecting the code for `$toObject`, `clone`, `applyGetters` and `applyVirtuals`. It seems that `applyGetters` works recursively on all document fields, whereas `applyVirtuals` only cares about the defined virtual paths. However, `document.toObject({ virtuals: true })` still produces an object containing virtuals on subdocuments because of how `$toObject` and `clone` works. It is quite confusing. : ]

**Comment by IslandRhythms** [comment]
This is a version issue, updating to 6.6.x will fix it

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.set('toObject', { virtuals: true });
const testSchema = new mongoose.Schema({
  firstName: String,
  lastName: String
}, { virtuals: {
  fullName: {
    get() {
      return this.firstName + ' ' + this.lastName;
    }
  }
}});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({ firstName: 'Test', lastName: 'Testerson' });

  const test = await Test.findOne();
  console.log(test, test.fullName);
  console.log(test.toObject());
  // console.log(test.toObject({ virtuals: true }));

}

run();
```

**Comment by hasezoey** [comment]
Cannot reproduce on latest(`6.6.1`) mongoose OR `6.3.5` (or `6.3.9`)

Code used:
```ts
// NodeJS: 18.7.0
// MongoDB: 5.0 (Docker)
// Typescript 4.8.2
import * as mongoose from 'mongoose'; // mongoose@6.3.5

// Test #1
// mongoose.set('toObject', { virtuals: true });

const schema = new mongoose.Schema(
  {
    prop1: String,
  },
  {
    // Test #2
    // toObject: {
    //   virtuals: true,
    // },
  }
);

// the virtual to test
schema.virtual('test').get(() => 1);

const model = mongoose.model('Test', schema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  const doc = new model({ username: 'user1' });

  // in 6.3.5 this always outputs the correct setting
  console.log(doc.toObject());
  // the following always works and is used a control
  console.log(doc.toObject({ virtuals: true }));

  await mongoose.disconnect();
})();
```

Output:
```txt
// first run - not having anything enabled
{ _id: new ObjectId("632433595b5e97cd51350c6d") }
{
  _id: new ObjectId("632433595b5e97cd51350c6d"),
  test: 1,
  id: '632433595b5e97cd51350c6d'
}

// second run - having the global enabled
{
  _id: new ObjectId("6324337525320dfabe204056"),
  test: 1,
  id: '6324337525320dfabe204056'
}
{
  _id: new ObjectId("6324337525320dfabe204056"),
  test: 1,
  id: '6324337525320dfabe204056'
}

// third run - having the schema-option enabled
{
  _id: new ObjectId("6324338bfa09da9a06d25e9c"),
  test: 1,
  id: '6324338bfa09da9a06d25e9c'
}
{
  _id: new ObjectId("6324338bfa09da9a06d25e9c"),
  test: 1,
  id: '6324338bfa09da9a06d25e9c'
}
```

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseGh12425

**Comment by owenchak** [comment]
I can also reproduce this on mongoose 7.5.3. The reason the two attempts above weren't able to reproduce was because the issue only happens when the schema is a subdocument of another.

Like @juona  said, `document.toObject({ virtuals: true })` works but is weird workaround

**Comment by vkarpov15** [comment]
@owenchak can you please provide a code sample that demonstrates this issue?
