### ISSUE TITLE
High, vulnerability issue when I run npm audit

### ISSUE THREAD

**Issue by karthik2265** [Automattic/mongoose#12433]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

>5.13.15

### Node.js version

14.20.0

### MongoDB server version

3.5.5

### Description

A high vulneraility issue is shown when npm audit is run.

 automattic/mongoose vulnerable to Prototype pollution via Schema.path
 
 

### Steps to Reproduce

 High            automattic/mongoose vulnerable to Prototype pollution via
                  Schema.path

  Package         mongoose

  Patched in      5.13.15

  Dependency of   mongoose

  Path            mongoose

  More info       https://github.com/advisories/GHSA-f825-f98c-gj3g

### Expected Behavior

no vulnerability issue.

**Comment by Uzlopak** [comment]
Duplicate of #12281
