### ISSUE TITLE
unique and index schema properties don't work!?

### ISSUE THREAD

**Issue by tamis-laan** [Automattic/mongoose#12439]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.1

### Node.js version

16 (lts)

### MongoDB server version

5.0.5

### Description

Using the unique and index schema properties don't work.

### Steps to Reproduce

``` javascript
const UserSchema = new client.mongoose.Schema({
	email: {
		type: client.mongoose.SchemaTypes.Email,
		required: true,
		index: true,
		unique: true
	},
})

// Create model
const User = client.mongoose.model("User", UserSchema)

const user1 = new User({foo@test.mail})
console.log('user', user)

const user2 = new User({foo@test.mail})
console.log('user', user)
```

![screenshot](https://user-images.githubusercontent.com/3178666/190850298-953e351e-8869-4ee3-bd4f-1dc4d39dd008.png)
![screenshot](https://user-images.githubusercontent.com/3178666/190850311-438c418b-5816-4323-999f-0e64b47aebc4.png)

### Expected Behavior

I would expect a second index on property `email` and it being unique.

**Comment by hasezoey** [comment]
your code and screenshots do not really align, because the code shows only creation of the documents, not actually saving (`new Model()` is just create a mongoose instead, to actually save it directly use `await Model.create()`, or `await doc.save()` after `new Model()`)

aside from that, did you already try [`await Model.syncIndexes()`](https://mongoosejs.com/docs/api.html#model_Model-syncIndexes)?

**Comment by IslandRhythms** [comment]
Its strange, it doesn't proc every time but if you try it enough times it will proc.
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    index: true,
    unique: true
  }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test'
  });
  const entry2 = await Test.create({
    name: 'Test'
  });

  console.log(entry2);

  console.log('done');
}

run();
```

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    index: true,
    unique: true
  }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.init();

  await Test.create({
    name: 'Test'
  });
  const entry2 = await Test.create({
    name: 'Test'
  });

  console.log('done');
}

run();
```

**Comment by hasezoey** [comment]
i just noticed that `client.mongoose.SchemaTypes.Email` is used, could that be provided for help for the options?

---

@IslandRhythms from what i can tell, the issue is about the unique index *not being created* not *validation* (also a custom schema-type is used)

**Comment by IslandRhythms** [comment]
Add `await Model.init()` to ensure your indexes are built first, and don't create any duplicates.
![image](https://user-images.githubusercontent.com/39510674/192324717-c4507391-38a8-4baf-8ca8-e90db2465178.png)

**Comment by tamis-laan** [comment]
> Add `await Model.init()` to ensure your indexes are built first, and don't create any duplicates. ![image](https://user-images.githubusercontent.com/39510674/192324717-c4507391-38a8-4baf-8ca8-e90db2465178.png)

In case of a rest api should I run this on every startup/restart? Or does this create problems?

**Comment by hasezoey** [comment]
> In case of a rest api should I run this on every startup/restart? Or does this create problems?

`init` is run anyway, the `.init` function just gives your the promise to await for before continuing

so you can do it if you want a full set-up server & database before accepting connections, but from what i know everything done in `init` can also be done in the background / later and does (in most cases) not need to be explicitly awaited

**Comment by tamis-laan** [comment]
> > In case of a rest api should I run this on every startup/restart? Or does this create problems?
> 
> `init` is run anyway, the `.init` function just gives you the promise to await for before continuing
> 
> so you can do it if you want a full set-up server & database before accepting connections, but from what i know everything done in `init` can also be done in the background / later and does (in most cases) not need to be explicitly awaited

Strange because when I do a complete refresh and start all services from the ground up the index is never created.

**Comment by hasezoey** [comment]
just to correct myself, i looked into the implementation of `init` again, it is "not just" a return for the init promise, though the "init promise" already exists when using `autoIndex` (from my understand which is by default `true`)

> Strange because when I do a complete refresh and start all services from the ground up the index is never created.

instantly or after some waiting? also do you set `autoIndex` anywhere? (also from my new understanding, indexes are not created unless the collection already exists with `autoIndex`, and `init` forces the collection to exist)

**Comment by vkarpov15** [comment]
@tamis-laan realistically, without a repro script, there's no way we'll be able to make any informed suggestions. For example, what is `client.mongoose.SchemaTypes.Email` ? Do you still have an issue if you replace `client.mongoose.SchemaTypes.Email` with `String`?

Also, keep in mind that unique indexes will fail to build when there are already duplicates. Try removing any existing documents with duplicate keys.
