### ISSUE TITLE
Creating Transactions with 'readPreference=secondaryPreferred' throws an error

### ISSUE THREAD

**Issue by mx-wndl-zb** [Automattic/mongoose#12436]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.11

### Node.js version

17.2.0

### MongoDB version

5.0.12

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

Hi,

I am trying to use mongoose with a MongoDB-cluster setup where I want to use the setting `readPreference=secondaryPreferred` to shift load away from the primary node.

Now I noticed, if I want to create a transaction that I will get the following error message:
```
MONGODB ERROR Read preference in a transaction must be primary, not: secondaryPreferred
```

This means I am forced to write something like this every time I want to create a transaction:
``` javascript
const session = await Model.withTransaction(async () => {
    // do some db stuff
}, {
    readPreference: 'primary'
}
```

My question would be if there is any possibility/setting to set the `readPreference` for transactions only by default for the whole application?

Since it appears to be forced to `'primary'` anyway, maybe the global default for transactions can even be set to `'primary'`?

**Comment by hasezoey** [comment]
as a note, this is a mongodb (server / driver) limit as per [mongodb documentation](https://www.mongodb.com/docs/manual/core/read-preference/#read-preference-and-transactions):
> [Multi-document transactions](https://www.mongodb.com/docs/manual/core/transactions/) that contain read operations must use read preference [primary](https://www.mongodb.com/docs/manual/core/read-preference/#mongodb-readmode-primary). All operations in a given transaction must route to the same member.

**Comment by vkarpov15** [comment]
@hasezoey is correct, you can't execute transactions against a secondary. This is a limit on the MongoDB server side, there's nothing Mongoose can do about it unfortunately.
