### ISSUE TITLE
find.sort() params no longer accept an array

### ISSUE THREAD

**Issue by penfold45** [Automattic/mongoose#12434]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.1

### Node.js version

16

### MongoDB server version

5.0.12

### Description

Hi 

I am just upgrading from 6.3.1 to 6.6.1 and I noticed that the sort() funciton params have changed
I can not really find any explenaiton why or even any mention of this change being expected i.e its not in the release notes

It appears to have been done in this commit 8d917a98e1a2f491d0e9888625b435b760050d39, feels like a regression but maybe it was intentional?

I used to be able to do

```
        .sort([
            ['year', 1],
            ['quarter', 1],
            ['setNumber', 1],
        ])
``` 

But now it appears it has to be

```
        .sort({
            year: 1,
            quarter: 1,
            setNumber: 1,
        })
```

### Steps to Reproduce

Attempt to pass an array of arrays to sort()

```
        .sort([
            ['year', 1],
            ['quarter', 1],
            ['setNumber', 1],
        ])
```

**Comment by hasezoey** [comment]
yes it seems like 8d917a98e1a2f491d0e9888625b435b760050d39 changed the typing of `sort` from `string | any` to explicit `string | { [key: string]: SortOrder }`

but from what i can tell, arrays were never supported (at least not mentioned in the documentation), see [API Docs: `Query.prototype.sort()`](https://mongoosejs.com/docs/api/query.html#query_Query-sort)

**Comment by penfold45** [comment]
Hi I have noticed that the documentation was not entirly accurate in the past. However this is a particularly popular post of how to sort using mongoose https://stackoverflow.com/questions/4299991/how-to-sort-in-mongoose and as far as I am aware all of this worked until recently. It is also my underatanding that these are also all the ways you can sort directly in Monogodb itself.

**Comment by penfold45** [comment]
Any thoughts on if this we be reverted back to allow what it used too or if you will keep the "new" format? Happy to update my code but dont really want to do it if there is no need as we rely on the previous array format a lot.

Thanks

**Comment by hasezoey** [comment]
the behavior did not change for the runtime, only the types got more strings / more defined, instead of a simple `any` it got lowered, and the array way was seemingly not considered

your options are currently:
- ignore the errors with `@ts-ingore` or `@ts-expect-error`
- downgrade to a version that still has the `any` typing

and then wait for a fix to be released
