### ISSUE TITLE
alternate to connect-option reconnectTries and reconnectInterval

### ISSUE THREAD

**Issue by bhadix3e** [Automattic/mongoose#12448]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am working on migration of mongoose from version 5.12.4 to version 6.5.0 and my code breaks as in connect option reconnectTries and reconnectInterval is used.
As per issue #11930 this is removed in mongoose version 6.3.9. So what is the alternative approach for this and what is default value used by mongoose for  reconnectTries and reconnectInterval option OR how to keep this functionality in version 6.5.0 as well

**Comment by Uzlopak** [comment]
Well afaik it is by default reconnecting.

**Comment by vkarpov15** [comment]
There's no need to use `reconnectTries` or `reconnectInterval` in Mongoose 6. Mongoose will now retry every operation for up to `serverSelectionTimeoutMS`.
