### ISSUE TITLE
How to correctly type custom plugins? Also unable to register previously working plugins since v6.5.2

### ISSUE THREAD

**Issue by rubek-joshi** [Automattic/mongoose#12454]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.1

### Node.js version

16.14.0

### MongoDB version

5.0.5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

My custom plugin used to be typed correctly up to version `6.5.1` where I'm basically following [this guide](https://mongoosejs.com/docs/typescript/statics-and-methods.html#statics). However, starting from v6.5.2 to the current v6.6.1, I get the following:
![image](https://user-images.githubusercontent.com/33681318/191431071-707aa128-ac5a-4233-aadf-c94bea4562b5.png)

I was also unable to register the [mongoose-unique-validator](https://github.com/mongoose-unique-validator/mongoose-unique-validator#readme) plugin and being shown the following error in my IDE:
![image](https://user-images.githubusercontent.com/33681318/191431531-c30e2ae4-9ad4-405c-838f-f53af2d8e636.png)

I can't seem to find any info in the docs regarding how to correctly type my custom plugin nor am I sure if this is a bug or a breaking change.

**Comment by hasezoey** [comment]
Between 6.5.1 and 6.6.1 (the mentioned versions) the types for `schema.plugin` got more explicit than just `any`, but no generic case was added to test which broke existing plugins

current workaround is for the plugins to change their types from `function pluginFunction(schema: Schema)` to `function pluginFunction(schema: Schema<any, any, any, any, any>)`

i already tried to investigate and update the types, but i could not get it to work, the types always broke at `The types returned by discriminator(...) are incompatible between these types` (and i could not really update it, see #12457 and #12455)

see #12458 for reproduction
