### ISSUE TITLE
Unable to run query using mongoose when stopping node js server

### ISSUE THREAD

**Issue by zack1991** [Automattic/mongoose#12468]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.1

### Node.js version

14.17.6

### MongoDB version

4.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I am trying to read some data from database when nodejs server getting stopped. But i did not get the data from database. Below is my code snippet.

```
mongoose.connect(process.env.MONGO_URI,
            {
                socketTimeoutMS: 60000
            }
        ).then(() => {
              console.log('Connected successfully');
       })

async function gracefulShutdown() {
    console.log("Closing Server");
    const count = await MyModel.countDocuments();
    console.log("count => ", count);
    process.exit(0);
}
process.on('exit', gracefulShutdown);
```
Server Log :-
```
Connected successfully
Closing Server
```

count is not getting print getting undefined.

Can you please help me what is reason.

**Comment by vichle** [comment]
I'm pretty sure (tested locally) you can't pass an `async` function to handle the `'exit'` event. In this particular case, it seems odd to run it in the exit handler anyway. I usually do something like this:

```javascript
async function run () {
  await mongoose.connect(process.env.MONGO_URI, {
      socketTimeoutMS: 60000
  })
  console.log('Connected successfully')
  const count = await MyModel.countDocuments();
  console.log("count => ", count);
}

run()
  .then(() => process.exit(0)) // Make sure that we close the process properly after the run() function finishes
  .catch(err => {
    console.log('Unhandled error in run()', err)
    process.exit(1)
  })
```

PS. Based off your snippet above, it looks like you might benefit from reading up on the relationship between callbacks, Promises and async/await.

**Comment by zack1991** [comment]
Hi Vichle,

Thanks for your reply, In your code snippet you are connecting to database then in the next line you are running query on MyModel which will works. Actually my requirement is different, my database is already connected to database when i am running **pm2 start server.js** or **node server.js** then i am stopping the server using **pm2 stop server.js** or by **ctrl + c**. What i want is when stopping my server i want to do some database operations then i want to close the database.

My latest code snippet is :- 
```
mongoose.connect(process.env.MONGO_URI,
            {
                socketTimeoutMS: 60000
            }
        ).then(() => {
              console.log('Connected successfully');
       })

async function gracefulShutdown() {
    console.log("Closing Server");
    const count = await MyModel.countDocuments();
    console.log("count => ", count);
    await mongoose.disconnect();
}
process.on('exit', function () {
    gracefulShutdown().then(() => {
        process.exit(0);
    }).catch((error) => {
        writeLog(`gracefulShutdown.error => ${error.message}, Stack => ${error.stack}`);
        process.exit(1);
    });
});
```
This code is also not working as per my requirement, please help me what i am missing.

**Comment by vichle** [comment]
Looking at the [`pm2` documentation](https://pm2.keymetrics.io/docs/usage/signals-clean-restart/), they will send a `SIGINT` when you run the `stop` command. You can handle the SIGINT, run your query and then exit the application. Something like (not tested):

```javascript
const mongoose = require('mongoose')

async function run () {
    await mongoose.connect(process.env.MONGO_URI, {
        socketTimeoutMS: 60000
    })
    console.log('Connected successfully')
    // Intercept the SIGINT signal, regular SIGINT handling is overridden
    process.on('SIGINT', async function gracefulShutdown() {
        console.log('Received SIGINT, shutting down')
        const count = await MyModel.countDocuments();
        console.log("count => ", count);
        // Call process.exit to close the application
        process.exit(0)
    })
}
  
run()
    .catch(err => {
        console.log('Unhandled error in run()', err)
        process.exit(1)
    })
```

**Comment by zack1991** [comment]
Hi vichle,

Thanks for your reply, the code snippet you have provided is also not working. Can you please share a tested code.
