### ISSUE TITLE
$slice projection unexpected behavior when using negative skip

### ISSUE THREAD

**Issue by phoenixstudiodz** [Automattic/mongoose#12474]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.4

### Node.js version

16.14.2

### MongoDB server version

5.0.9

### Description

The docs in `$slice: [ <number to skip>, <number to return> ]`  state that  If the number of skiped elements is greater than the number of array elements, the query returns an empty array.
I expected a similar behavior when the skiped number is negative but it wasn't the case (when specifying the number of returned elements).
It seems that that when n (number of skip) is negative and greater than the array size it become `0` like `if(n > array.length) return 0` where `0` is the starting referance.

### Steps to Reproduce

Given  {array : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] }
- `myCollection.findOne({}, { $slice: [-1, 5] });` returns: `[ 9, 10]`
- `myCollection.findOne({}, { $slice: [-4, 5] });` returns: `[6, 7, 8, 9, 10]`
- `myCollection.findOne({}, { $slice: [-9, 5] });` returns: `[1, 2, 3, 4, 5]`
- `myCollection.findOne({}, { $slice: [-10, 5] });` returns: `[1, 2, 3, 4, 5]`
- `myCollection.findOne({}, { $slice: [-100, 5] });` returns: `[1, 2, 3, 4, 5]`

### Expected Behavior

I expected that `myCollection.findOne({}, { $slice: [-100, 5] });` to return an empty array same as `myCollection.findOne({}, { $slice: [-10, 5] });` to return: `[1, 2, 3, 4]`, meaning it should work same way netagive or possitive. the expected behavior should be in my opinion the same when :
 * using negative skip with number of return
 * or when using array.reverse() then a skip with a positive number.
Meaning both return empty array if the skip is too big

**Comment by vkarpov15** [comment]
#12776 explains that this is expected behavior. From the following docs: https://www.mongodb.com/docs/manual/reference/operator/projection/slice/

![image](https://user-images.githubusercontent.com/1620265/207999749-75737bc3-9f4d-4b37-b8c4-7da91888f8d5.png)
