### ISSUE TITLE
`findOneAndUpdate` works if invalid query/schema property is specified

### ISSUE THREAD

**Issue by marijus-saulys** [Automattic/mongoose#12477]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.2

### Node.js version

16.15.0

### MongoDB server version

4.0.3

### Description

I'm not sure if that's an expected behavior, but it feels very dangerous. When I execute a query:

```
const res = await models[model].findOneAndUpdate(
    query,
    data,
    { new: true },
).orFail(() => Error('Not found'));
```

with "invalid" `query` parameter like `{ non_existing_field: 'blah' }`, it always updates some "random" record to the specified values and never goes into `onFail`. Basically it corrupts the database, and is really hard to catch in dev phase. Imagine a project where one developer makes a mistype on property name.

Everything works fine with existing properties.

### Steps to Reproduce

```
const res = await models[model].findOneAndUpdate(
   { non_existing_field: 'blah' },
    data,
    { new: true },
).orFail(() => Error('Not found'));
```

### Expected Behavior

It should go into `orFail` block.

**Comment by hasezoey** [comment]
yes this is currently expected behavior, see #4251 and #11861

will close in favor of the existing issues

the workaround is manual for now by setting the schemaOption [`strictQuery`](https://mongoosejs.com/docs/guide.html#strictQuery) to either `false` (default in mongoose 5) or to `throw` to throw on invalid fields
