### ISSUE TITLE
Buffering timeout even though database is connected

### ISSUE THREAD

**Issue by OneCricketeer** [Automattic/mongoose#12487]
### Mongoose version

6.6.2

### Node.js version

16.7.0

### MongoDB version

6.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Issue

I am working on porting some code from JS to TS, and my database connection has not changed, so I have ruled out networking issues. In fact, the logs say the connection is established, and yet, only after I have converted my models to TS, only then am I experiencing buffer timeouts. 

Perhaps I am exporting/importing the `mongoose.model` `const` incorrectly from my external module? It does know what collection to use, so that seems fine. 

For debugging, I am locally using `npm pack` in the "models" module, then `npm install ../models/models*.tgz` in my "main module"

To minimize the example outside my API layer, I created a population TS script (JS script also returns same error, but I thought TS model imports would work better)

## Logs

```
$ npx ts-node scripts/populatedb.ts mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb/${MONGODB_DATABASE}?retryWrites=true
Connected to database
Populating database...
FINAL ERR: MongooseError: Operation `users.insertOne()` buffering timed out after 10000ms
Closing database connection
Disconnected from database
```

## Code snippet

```ts
import {
  MongoUserModel as User,
} from '@external-module/models/dist/mongo';

const userCreate = function (email: string) {
  const user = new User({ email });

  user.save(function (err) {
    if (err) {
      console.log(err);
      return;
    }
    console.log('New User: ' + user);
  });
}

const db = mongoose.connection;
db.on('connected', _ => console.log('Connected to database'));
db.on('disconnecting', _ => console.log('Closing database connection'));
db.on('disconnected', _ => console.log('Disconnected from database'));
db.on('error', console.error.bind(console, 'MongoDB connection error:'));

const userArgs = process.argv.slice(2);
mongoose.connect(userArgs[0])  // have verified this is correct, plus logs say the connection works
  .then(() => {
    console.log("Populating database...")
    userCreate("foo@example.com");
  })
```

External module definition (`tsc` output)

```ts
import { Schema } from "mongoose";
import { IMongoUser } from ".";
export declare const MongoUserModel: import("mongoose").Model<IMongoUser, {}, {}, {}, Schema<IMongoUser, import("mongoose").Model<IMongoUser, any, any, any, any>, {}, {}, {}, {}, "type", IMongoUser>>;
```

\+ interface definition 

```ts
import { Types } from "mongoose";
export interface IMongoUser {
    _id: Types.ObjectId;
   email: string;
}
```

**Comment by hasezoey** [comment]
would it be possible to provide the `User` schema and how it is made into a model? because with the current provided things we can only see the type, but not the runtime behavior

this could have multiple reasons:
- the model is defined on a different connection / mongoose instance than the one that is connected
- the model is define on a different mongoose version than your connection (mismatching mongoose versions)
- the connection somehow gets overloaded (unlikely)

**Comment by OneCricketeer** [comment]
## Files

@hasezoey 

> provide the User schema and how it is made into a model

Sure. Expand each section below. 

<details><summary><code>src/index.ts</code></summary>

```ts
export interface IUser {
    email: string;
}
```

</details>

<details><summary><code>src/mongo/index.ts</code></summary>

```ts
import { Types } from "mongoose";
import { IUser } from "..";
import { MongoUserModel } from "./MongoUserModel";

export interface IMongoUser extends IUser {
    _id: Types.ObjectId;
}

export {
    /* Mongoose models */
    MongoUserModel
}
```
</details>

<details><summary><code>src/mongo/MongoUser.ts</code></summary>

```ts
import { Schema, model } from "mongoose";
import { IMongoUser } from ".";

/** User Details. Use implicit '_id' field for collection lookups. */
const userSchema = new Schema<IMongoUser>({
  /** Emails should be modifiable; this is not a unique ID for a user. */
  email: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },
});

export const MongoUserModel = model("User", userSchema);
```
</details>

<details><summary><code>tsconfig.json</code></summary>

```json
{
    // This is an alias to @tsconfig/node16: https://github.com/tsconfig/bases
    "extends": "ts-node/node16/tsconfig.json",
    "ts-node": {
        "files": true
    },
    "compilerOptions": {
        "outDir": "dist",
        "declaration": true,
        "noImplicitAny": true,
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

</details>

## Responses

> the model is defined on a different connection / mongoose instance

How is that possible when I am running one script, importing mongoose once, and calling `mongoose.connect` one time?

> mismatching mongoose versions

Checked that. Both are the same. 

> somehow gets overloaded

It's a local Mongo database with no other established connections, so yes, unlikely.

**Comment by OneCricketeer** [comment]
> this can be checked by yarn why mongoose or npm ls mongoose, if there are multiple entries and they dont say something along the lines of deduped, then it is likely the problem

Every entry says deduped w/ 6.6.2

> check if the model has been defined before the connecting, with console.log(mongoose.models); or console.log(mongoose.connection.models);(or in your case console.log(db.models) would also work

Those both are showing the same models. 

---

So... I was testing this with `npm pack` in my external module, then `npm install` that local tarball... I just published a dev version to our NPM registry, and installed that published version instead, and now it works. I'm so confused 😆 

Thoughts before I close this?

**Comment by hasezoey** [comment]
> Thoughts before I close this?

not really

**Comment by sarankumar-ns** [comment]
Hi, I'm also facing the same error. When I print `console.log(db.models)` it returns an empty object. But the local machine prints all available 3 models. 🤔

**Comment by hasezoey** [comment]
> Hi, I'm also facing the same error. When I print `console.log(db.models)` it returns an empty object. But the local machine prints all available 3 models. thinking

that likely means that your models are registered on a different connection, or you are printing before any model could be registered, do you use different connections for your local machine and non-local machine?
