### ISSUE TITLE
Get data from a collection and put in another collection [Embed Data] (Best Pratice)

### ISSUE THREAD

**Issue by AmirmohammadBeheshti** [Automattic/mongoose#12481]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

9.2.0

### Node.js version

16.0.0

### MongoDB version

3.6.8

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04 ubuntu

### Issue

I have a collection that I want to store the information in the document of another collection. According to the articles that I read, first colloction.find the values that are needed from the collection and then store that in the other collection as a sub document, but I want to receive and store data from the collection automatically by Mongoose. I use NEST. (** i know that my new document dosn't update when update base document. for example for history colleltion)

**CreateProduct.schema.ts:**
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type CreateProductDocument = Product & Document;

@Schema()
export class Product {
  @Prop()
  name: string;
  @Prop()
  describe: string;
}

export const CreateProductSchema =
  SchemaFactory.createForClass(Product);
```

**ReserveProduct.schema.ts:**
```ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document } from 'mongoose';
import { Product } from 'src/fake-product/schema/product.schema';

export type ReserveDocument = Reserve & Document;

@Schema()
export class Reserve {
  @Prop()
  name: string;
  @Prop({
    type: [{ type: mongoose.Schema.Types.ObjectId, ref: Product.name }],
    name: 'products',
  })
  products: Product;
}

export const ReserveSchema = SchemaFactory.createForClass(Reserve);
```

I want to embed product information in the reserve product schema...

**Expected**

i want to get this request body from user

```js
{
'name' : 'TestName',
'products' : ['63317a213a320785264bb86d' , '63317a743a320785264bb871']
}
```

and get the product details such as name and etc from product collection and embed the value on the reserve collection I read this code but not work exactly

```ts
  async reserved(body: CreateFakeReserve) {
    const createdFakeReserveInstance = new this.fakeReserve({
      ...body,
      name: 'test',
    });
    await createdFakeReserveInstance.populate('products');
    const res = await createdFakeReserveInstance.save();
    return res;
  } 
```

in this code populate the ids with product collection but don't save on the reserve collection , in blogs said first we should get the products from product collection with find method on mongoose but I want to set the ids and mongoose read the data from collection and embed on my product collection automatically

**Comment by hasezoey** [comment]
could you clarify whether you want to store *the populated* data as a new document, or *just the ids* (like original)?

aside from that, depending on when you want to automatically store a copy, you could use hooks (like `schema.pre('save', function)` (or if you want it more re-useable, with plugins)

**Comment by vkarpov15** [comment]
I don't understand what you're trying to do here. What do you mean by "populate the ids with product collection but don't save on the reserve collection" ? What does your data look like in MongoDB?
