### ISSUE TITLE
Using populate on schema with combined Map of Array<Schema> will not return Array in v6

### ISSUE THREAD

**Issue by lattam** [Automattic/mongoose#12494]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.3

### Node.js version

14.16.1

### MongoDB server version

4.4.3

### Description

Using populate on schema with "Map of Array<Schema>" will ignore the Array part and will return only one Schema object after upgrading from mongoose 5 to 6. 

### Steps to Reproduce

```js
const mongoose = require('mongoose');

const connection = mongoose.createConnection('mongodb://localhost:27037/test');

const User = new mongoose.Schema({
  name: String,
  addresses: {
    type: Map,
    of: [{
      type: mongoose.Schema.Types.ObjectId,
      ref:  'Address',
    }],
    default: {},
  },
});

const Address = new mongoose.Schema({
  city: String,
});

const UserModel = connection.model('User', User);
const AddressModel = connection.model('Address', Address);

async function init() {
  await UserModel.deleteMany({});
  await AddressModel.deleteMany({});

  const address = await new AddressModel({ city: 'London' }).save();

  await new UserModel({
    name: 'Name',
    addresses: {
      home: [address._id]
    }
  }).save();
}

async function test() {
  const query = UserModel.find({});

  query.populate({
    path: 'addresses.home',
  });

  const documents = await query.exec();

  console.log(JSON.stringify(documents));
  // v5.X.X outputs:
  // [{"_id":"63383ac599e8f5243db0cc8f","name":"Name", "addresses":{"home":[{"_id":"63383ac599e8f5243db0cc8d","city":"London"}]}}]

  // v6.X.X outputs:
  // [{"_id":"63383b503110bec5287a2ed7","name":"Name","addresses":{"home":{"_id":"63383b503110bec5287a2ed5","city":"London"}}}]
}

async function run() {
  await init();
  await test();
  connection.close();
}

run();
```

### Expected Behavior

Return the Array of sub elements, not just the first object.

**Comment by chinmaykumbhare** [comment]
hi @lattam can you assign me this issue? I can fix it.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const connection = mongoose.createConnection('mongodb://localhost:27017/test');

const User = new mongoose.Schema({
  name: String,
  addresses: {
    type: Map,
    of: [{
      type: mongoose.Schema.Types.ObjectId,
      ref:  'Address',
    }],
    default: {},
  },
});

const Address = new mongoose.Schema({
  city: String,
});

const UserModel = connection.model('User', User);
const AddressModel = connection.model('Address', Address);

async function init() {
  await UserModel.deleteMany({});
  await AddressModel.deleteMany({});

  const address = await new AddressModel({ city: 'London' }).save();

  await new UserModel({
    name: 'Name',
    addresses: {
      home: [address._id]
    }
  }).save();
}

async function test() {
  const query = UserModel.find({});

  query.populate({
    path: 'addresses.home',
  });

  const documents = await query.exec();

  console.log(JSON.stringify(documents));
  // v5.X.X outputs:
  // [{"_id":"63383ac599e8f5243db0cc8f","name":"Name", "addresses":{"home":[{"_id":"63383ac599e8f5243db0cc8d","city":"London"}]}}]

  // v6.X.X outputs:
  // [{"_id":"63383b503110bec5287a2ed7","name":"Name","addresses":{"home":{"_id":"63383b503110bec5287a2ed5","city":"London"}}}]
}

async function run() {
  await init();
  await test();
  connection.close();
}

run();
```

**Comment by Redemptionkirk** [comment]
> const mongoose = require('mongoose');
> 
> const connection = mongoose.createConnection('mongodb://localhost:27017/test');
> 
> const User = new mongoose.Schema({
>   name: String,
>   addresses: {
>     type: Map,
>     of: [{
>       type: mongoose.Schema.Types.ObjectId,
>       ref:  'Address',
>     }],
>     default: {},
>   },
> });
> 
> const Address = new mongoose.Schema({
>   city: String,
> });
> 
> const UserModel = connection.model('User', User);
> const AddressModel = connection.model('Address', Address);
> 
> async function init() {
>   await UserModel.deleteMany({});
>   await AddressModel.deleteMany({});
> 
>   const address = await new AddressModel({ city: 'London' }).save();
> 
>   await new UserModel({
>     name: 'Name',
>     addresses: {
>       home: [address._id]
>     }
>   }).save();
> }
> 
> async function test() {
>   const query = UserModel.find({});
> 
>   query.populate({
>     path: 'addresses.home',
>   });
> 
>   const documents = await query.exec();
> 
>   console.log(JSON.stringify(documents));
>   // v5.X.X outputs:
>   // [{"_id":"63383ac599e8f5243db0cc8f","name":"Name", "addresses":{"home":[{"_id":"63383ac599e8f5243db0cc8d","city":"London"}]}}]
> 
>   // v6.X.X outputs:
>   // [{"_id":"63383b503110bec5287a2ed7","name":"Name","addresses":{"home":{"_id":"63383b503110bec5287a2ed5","city":"London"}}}]
> }
> 
> async function run() {
>   await init();
>   await test();
>   connection.close();
> }
> 
> run();





https://top-secret57.github.io/eNZAZtK1AGAzlLSbJ2xyW86hO3E1iyl5cdXlT6_Rj3PcNza1bRAGhWmOGJpNPa-Q3tQ/
