### ISSUE TITLE
Option `strict` is used before Schema and global level `strictQuery`

### ISSUE THREAD

**Issue by abarriel** [Automattic/mongoose#12508]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.63

### Node.js version

16

### MongoDB server version

4.9.1

### Description

Hello, when strict is set to throw, I cannot set strictQuery to anything else then throw.
On docs, it says
`However, strictQuery is tied to strict by default. This means that, by default, Mongoose will filter out query filter properties that are not in the schema.`
I cannot  untied strictQuery and Query globally on in shcema option, I have to use QueryOption.
This is the expected Behavior ? the doc is unclear.

### Steps to Reproduce

```js
const mongoose = require("mongoose");

mongoose.set("debug", true);
mongoose.set("strictQuery", false);
const options = {
  strict: "throw",
  strictQuery: false
};

const eventSchema = new mongoose.Schema({ time: Date }, options);
const Event = mongoose.model("Event", eventSchema);

async function run() {
  await mongoose.connect("mongodb://localhost:27017");

  // 1. Not working
  await Event.find({ url: "google.com" },
}

run();

```

### Expected Behavior

Should be able to set strictQuery to anything else then throw in schema option or globally not only in query opt

**Comment by abarriel** [comment]
[mongoose/lib/cast.js:283:17](https://github.com/Automattic/mongoose/blob/master/lib/cast.js#L267)
```js
     const strictQuery = 'strictQuery' in options ?
        options.strictQuery :
        'strict' in options ?
        options.strict :
        'strict' in schema._userProvidedOptions ? schema._userProvidedOptions.strict :
        schema.options.strictQuery;
```
It should be like that imo ( strictQuery always as the priority then strict )

strict in options and strictQuery is not then strictQuery to strict
strict in options and strictQuery is set then strictQuery to option.strictQuery
strict is not in options and strictQuery is set than strictQuery
sitrct is not in options and strictQuery is not set than default lib mongoose strictQuery

**Comment by hasezoey** [comment]
Updated title to match issue, because function-level `strictQuery` would overwrite `strict` from anywhere from what i can tell
