### ISSUE TITLE
InferSchemaType says unknown type for everything

### ISSUE THREAD

**Issue by adriandelgg** [Automattic/mongoose#12510]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.3

### Node.js version

16.17.1

### MongoDB server version

4.10.0

### Description

Whenever I use the `InferSchemaType` to get a type for my schema it will say that a lot of the types are `unknown`. What I don't understand is that I wouldn't have this issue before and it randomly started happening.

```typescript
type IUser = InferSchemaType<typeof schema>;

const schema = new Schema({
	address: {
		type: String,
		trim: true,
		minlength: 42,
		maxlength: 42,
		match: /^0x[a-zA-Z0-9]+$/,
		unique: true,
		required: true
	},
	firstName: {
		type: String,
		trim: true,
		set: (v: string) => v[0].toUpperCase() + v.slice(1)
	},
	lastName: {
		type: String,
		trim: true,
		set: (v: string) => v[0].toUpperCase() + v.slice(1)
	},
	email: {
		type: String,
		minlength: 2,
		maxlength: 50,
		trim: true,
		unique: true,
		match: /^.+bp\.com$/
	},
	meetingIds: { type: [Number], required: true },
	lockedUpTokens: {
		type: [String],
		minlength: 42,
		maxlength: 42,
		trim: true,
		match: /^0x[a-zA-Z0-9]+$/
	},
	adminOfOrgs: { type: [Schema.Types.ObjectId], ref: 'Orgs' },
	voterOfOrgs: { type: [Schema.Types.ObjectId], ref: 'Orgs' },
	requestingToJoin: { type: [Schema.Types.ObjectId], ref: 'Orgs' },
	wallets: [
		{
			name: { type: String, unique: true },
			address: {
				type: String,
				minlength: 42,
				maxlength: 42,
				trim: true,
				unique: true,
				match: /^0x[a-zA-Z0-9]+$/
			}
		}
	]
});
```

The type of `IUser` shows as:
```typescript
IUser = {
    meetingIds: unknown[];
    lockedUpTokens: unknown[];
    adminOfOrgs: {
        _id?: ... | undefined;
        equals?: {} | undefined;
        id?: {
            [x: number]: unknown;
            [Symbol.iterator]?: {} | undefined;
            map?: {} | undefined;
            set?: {} | undefined;
            ... 100 more ...;
            valueOf: {};
        } | undefined;
        ... 6 more ...;
        toString: {};
    }[];
    ... 6 more ...;
    email?: unknown;
}
```

Am I doing something wrong here?

### Steps to Reproduce

copy my code and versions.

### Expected Behavior

Should give me correct types when I use `InferSchemaType` rather than give me unknown.

**Comment by hasezoey** [comment]
may be related to #12431 and may be fixed by #12352 (in mongoose 6.7)

**Comment by adriandelgg** [comment]
How do I download Mongoose 6.7 if I'm on Node 16.17.1?

**Comment by hasezoey** [comment]
> How do I download Mongoose 6.7 if I'm on Node 16.17.1?

without using the git repo directory, not at all, mongoose does not have beta builds
but if you want to use git repo dependencies, then replace `"mongoose": "x.x.x"` with `"mongoose": "git+https://github.com/Automattic/mongoose.git#6.7"` (this should work in both yarn and npm)

**Comment by adriandelgg** [comment]
> > How do I download Mongoose 6.7 if I'm on Node 16.17.1?
> 
> without using the git repo directory, not at all, mongoose does not have beta builds but if you want to use git repo dependencies, then replace `"mongoose": "x.x.x"` with `"mongoose": "git+https://github.com/Automattic/mongoose.git#6.7"` (this should work in both yarn and npm)

Thank you. Your suggestion worked and fixed the issue. However, is 6.7 a beta version? When would it get officially released?
