### ISSUE TITLE
OverwriteModelError with mocha 'watch'

### ISSUE THREAD

**Issue by floatingLomas** [Automattic/mongoose#1251]
I just updated from 3.4.0 to 3.5.1, and when 'watching' Mocha tests on a model, every time the file reloads, I get a OverwriteModelError from re-'require'ing - and I guess, redefining - the model.

There must be some value in making an 'overwrite' an error, but I'm going back to 3.4.0 for now because this is too much of a pain.

**Comment by ArnaudRinquin** [comment]
:+1: :bow:

**Comment by joaom182** [comment]
:+1:

**Comment by vkarpov15** [comment]
If you want to create a model in `beforeEach`, create a new connection with `var db = mongoose.createConnection();` and then `db.model(...)` as opposed to `mongoose.model(...);` in `beforeEach`. This behavior is by design rather than a bug.

**Comment by LiamKarlMitchell** [comment]
I have code that can be reloaded at runtime so I want to overwrite an existing model if I make a change to the schema or model functions during development.

Unless there is a good reason not to I don't see why I shouldn't be able to do something like this.

Example
````
delete mongoose.models['somemodel'];
var somemodel = db.mongoose.model('somemodel', someschema);
````

This works for me, I have been doing it that way for about a year.

Or maybe there is a way to change the schema and model functions without wiping an existing model/schema but I have not bothered to investigate further.

**Comment by hellboy81** [comment]
My be [this solution can be helpful](http://stackoverflow.com/a/26142477/444079)

**Comment by zirho** [comment]
:+1:

**Comment by ph3b** [comment]
I know this is old but if anyone stumbles upon this I solved it by making a database test utility file like this:
```javascript
// DatabaseUtils.js
import mongoose from 'mongoose';
const MONGO_URI = 'mongodb://localhost:27017/collectionname'

export function tearDown(){
  mongoose.models = {};
  mongoose.modelSchemas = {};
  clearDB();
  if(mongoose.connection.readyState) mongoose.disconnect();
}

export function setUp(){
  if(!mongoose.connection.readyState) mongoose.connect(MONGO_URI);
}

export function clearDB(){
  if(mongoose.connection.db) mongoose.connection.db.dropDatabase();
}
```
Then from your test file you can use:
```javascript
import * as DbUtils from './DatabaseUtils'

describe('Testing MongoDB models', function(){
  before(setUp)
  after(tearDown)
  afterEach(clearDb)

  it('Some test of a mongoose model', () =>  {
  // Test code here.
  }
})
```

**Comment by gunar** [comment]
[This StackOverflow answer](http://stackoverflow.com/a/38143030) solves it like this:
```js
let users
try { users = mongoose.model('users') }
catch (e) { users = mongoose.model('users', <UsersSchema...>) }
```

**Comment by miqmago** [comment]
Thanks @remicastaing, I've lost 5 minutes until I reached your solution, should be more evident :)

**Comment by developius** [comment]
Thanks @juanpabloaj, that worked for me

**Comment by DanielRamosAcosta** [comment]
@gunar The problem with that is that if your Schema changes changes won't take efect.

**Comment by fega** [comment]
@juanpabloaj  Thanks bro!

**Comment by markotom** [comment]
I simply use, instead of create an ugly try/catch:

```js
let users = mongoose.model('users') || mongoose.model('users', <UsersSchema...>)
```

**Comment by tomyam1** [comment]
This discussion is really shameful
The actual authors of mongoose gave the correct solution ([1](https://github.com/Automattic/mongoose/issues/1251#issuecomment-96323651) and [2](https://github.com/Automattic/mongoose/issues/1251#issuecomment-11466245)) yet all the thumb ups goes to incorrect hacky solutions.
Really shameful

**Comment by fega** [comment]
@tomyam1 , maybe because those hacky solutions is solving our problems without any problems...

**Comment by vkarpov15** [comment]
Sometimes a convenient solution works better than a technically correct one :)

**Comment by garethdown44** [comment]
@tomyam1 There is nothing shameful about collaborating to solve a problem and I am grateful to everyone who has posted up their own take on a solution here. Without going into detail - in my case, one of the 'incorrect hacky' suggestions has worked perfectly, and both of what you are calling 'correct' solutions did not.

Helping one another out is not shameful. Thanks everyone that has made a constructive post.

**Comment by tomyam1** [comment]
Well sirs, then we disagree.
To avoid creating more spam, please use the emojis reactions.

To sum up this thread:

There are only three different solutions in this page:

1. Use cached model if it exists:
```
mongoose.models.users || mongoose.model('users', <UsersSchema...>)
```
or
```
try {
    // Throws an error if "Name" hasn't been registered
    mongoose.model("Name")
} catch (e) {
    mongoose.model("Name", Schema)
}
```
This is not a solution because it won't pick up changes in the models.

2. Clear the model cache
```
 mongoose.models = {};
 mongoose.modelSchemas = {};
```
Tried this solution and it didn't work, and who knows why?
It relies on modifying undocumented internal variables.
It probably did work when it was proposed in 2013, but it's 4 years later.

3. Save the model on the connection.
This is the official solution that was proposed by the authors of mogoose.
And yet it was almost completely overlooked. For me, this is shameful.

```
const Mongoose = require('mongoose');
const DB = Mongoose.createConnection(...);
const Model = mongoose.model("Name");
```

**Comment by garethdown44** [comment]
@tomyam1 - Agree in principle with what you're saying. However to be fair that solution did come two years after the other (hacky) solution!!

In my case I chose the nodemon solution. When I realised what was happening and the way the test code was structured it would have required a big refactoring which I don't have time to do. I'm glad that the nodemon solution was proposed and that people +1'd it. That's all I'm saying.

**Comment by DanielRamosAcosta** [comment]
Sadly, Nodemon restarts the entire test suite, so `mocha --watch` has much faster reload

**Comment by carchrae** [comment]
> Sadly, Nodemon restarts the entire test suite, so mocha --watch has much faster reload

a slow reload and sane developer is tradeoff i'll make over slicing miliseconds of a test run

also, as it hasn't been mentioned here, `npm-watch` is a tool to do this (it wraps nodemon) so you can define a simple npm script `watch`

**Comment by maciekgrzybek** [comment]
@remicastaing  works like a charm, thanks!

**Comment by thiagof** [comment]
On some special instantiations, it may be required to clear the `models` references

```js
after((done) => {
  Object.keys(mongoose.models).forEach((k) => {
    delete mongoose.models[k];
  });
  Object.keys(mongoose.modelSchemas).forEach((k) => {
    delete mongoose.modelSchemas[k];
  });
  mongoose.disconnect();
  mongoose.connection.close();
  done();
});
```

**Comment by Crowbrammer** [comment]
The following, non-hacky solution works for me consistently:

```js
const expect = require("chai").expect;
const mongoose = require("mongoose"),

  // Define your Schemas and models separately, so
  // that you can define your Schema once above
  // your test suites, and your models many times
  // when testing. mocha --watch does not rerequire anything
  // outside of the test suite ("describe").
  UserSchema = require("../data/models/User");

describe("mongoose strangeness", function() {
  var connection = mongoose.createConnection(
    process.env.MONGO_URL || "mongodb://127.0.0.1/test"
  );

  // I tried this first, but this wasn't needed:

  // beforeEach(function(done) {
  //   connection = mongoose.createConnection(
  //     process.env.MONGO_URL || "mongodb://127.0.0.1/test"
  //   );
  //   connection.once("open", function() {
  //     done();
  //   });
  // });

  // afterEach(function(done) {
  //   connection.close(function() {
  //     done();
  //   });
  // });

  it("MongoDB working and testable", function(done) {
    let User = connection.model("User", UserSchema);

    let user = User({
      username: "My user"
    });

    user
      .save()
      .then(doc => {
        console.log(doc); // This outputs the doc.
        expect(doc.username).to.equal("My user");
        done();
      })
      .catch(err => {
        console.error(err);
        expect(err).to.be.null;
        done();
      });
  });
});
```

**Comment by verheyenkoen** [comment]
Just calling `mongoose.deleteModel('...')` prior to creating it again worked for me.

**Comment by vkarpov15** [comment]
@verheyenkoen is right. Here's the link to the deleteModel docs: https://mongoosejs.com/docs/api/connection.html#connection_Connection-deleteModel
