### ISSUE TITLE
Typescript -- MongooseQueryMiddleware not include countDocuments and estimatedDocumentCount but only count 

### ISSUE THREAD

**Issue by LucaIaconelli** [Automattic/mongoose#12516]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.4

### Node.js version

16.17.1

### MongoDB version

4.4.17

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.1 LTS

### Issue

I'm trying to create a pre-hook for my class. But I noticed that in typescript in the definition of `MongooseQueryMiddleware` there are these options: 

`'count' | 'deleteMany' | 'deleteOne' | 'distinct' | 'find' | 'findOne' | 'findOneAndDelete' | 'findOneAndRemove' | 'findOneAndReplace' | 'findOneAndUpdate' | 'remove' | 'replaceOne' | 'update' | 'updateOne' | 'updateMany'`

`countDocuments` and `estimatedDocumentCount` are missing, and if I'm using `count`, the other two not works as expected. 

Could you kindly help to solve this problem?

Thanks

**Comment by LucaIaconelli** [comment]
@hasezoey  Thank you very much. When is 6.6.5 expected to be released?

**Comment by hasezoey** [comment]
> When is 6.6.5 expected to be released?

guessing by the average time patch versions are released, within the next 2 weeks at the longest, but more commonly within ~7 days from the point of the last patch version
