### ISSUE TITLE
pre-query event for mongoose

### ISSUE THREAD

**Issue by Springtime0522** [Automattic/mongoose#1252]
There is a  save and validate functions for the schema.pre but is there a pre-query event like below

var toySchema = new Schema(..);
 *
-     toySchema.pre('query', function (next) {
-      //Append a where clause here for every query
-       next();
-     })

/**
- Defines a pre hook for the document.
  *
- ####Example
  *
-     var toySchema = new Schema(..);
  *
-     toySchema.pre('save', function (next) {
-       if (!this.created) this.created = new Date;
-       next();
-     })
  *
-     toySchema.pre('validate', function (next) {
-       if (this.name != 'Woody') this.name = 'Woody';
-       next();
-     })
  *
- @param {String} method
- @param {Function} callback
- @see hooks.js https://github.com/bnoguchi/hooks-js/tree/31ec571cef0332e21121ee7157e0cf9728572cc3
- @api public
  */

**Comment by rolandnsharp** [comment]
@mailaneel, your workaround is nearly working form me but something is going wrong.


```
model.pre('query', function (something, next, query) {

    query.where({_id: '533137a11994a79fb5c34fac'});
     next();
});
```

**Comment by rolandnsharp** [comment]
@mailaneel, your workaround is nearly working form me but something is going wrong.
Clue one: The pre query hook callback seems to take three arguments.

```
model.pre('query', function (something, next, query) {
    console.log('what is something', something);
    query.where({_id: '533137a11994a79fb5c34fac'});
     next();
});
```

Issue: When useing your code my pre save hooks seem to run over all models not the specific model schema is was called on. This code throws the error only when using your Pre Query code.
```
schema.pre('save', true, function(next, done) {
		var user = this;
		console.log('running pre-save middleware: ', user.constructor.modelName);
		if (user.constructor.modelName !== 'user'){
			throw new Error('User pre-save middleware should not pre-save "' + user.constructor.modelName + 's".');
		}
		next();
	});
};
```

I'm using this for a mongoose extension I'm working on: https://github.com/inlight-media/node-mongoose-soft-delete

Any suggestions on where I should be looking?

**Comment by vkarpov15** [comment]
So the 3.9.x branch contains pre('find'), pre('findOne'), pre('findOneAndUpdate'), and pre('update') hooks, see #2138

**Comment by rolandnsharp** [comment]
@vkarpov15, fantastic! I read your comment about why `count` and `populate` will not contain a pre query hooks but what about `findById`? 

I'm looking through the branches but I can't find 3.9.x... and I looking in the wrong place?

**Comment by vkarpov15** [comment]
`count()` may have one soon, I don't really see any reason why not. `populate()` is a trickier question though.

`findById` is just a very thin wrapper around `findOne`, so `findOne` hooks will get triggered by `findById`

And I'm not sure if its really possible to add a pre('count') functionality in an extension atm. Can't think of a way off the top of my head.

**Comment by rolandnsharp** [comment]
Could it be done by passing the mongoose object into the plugin and modifying it directly? 
```
var softDelete = require('mongoose-soft-delete')(mongoose);
schema.plugin(softDelete);
```

Otherwise, when do you expect to have pre('count') functionality in master?

**Comment by vkarpov15** [comment]
Yeah in theory you could overwrite the count() function yourself. I'll open up an issue (#2621) and put it into 4.0.0-rc0 - pre('count') is not difficult now that we have a notion of query middleware, just pre('find') was much more of a priority :)

**Comment by KATT** [comment]
I'm using a DB which uses soft-delete.

This seems to do it for me, but haven't tested it extensively yet.

```js
function findNotDeletedMiddleware(next) {
    this.$where('this.deleted === false');
    next();
}

MyModel.pre('find', findNotDeletedMiddleware);
MyModel.pre('findOne', findNotDeletedMiddleware);
MyModel.pre('count', findNotDeletedMiddleware);
```

**Comment by vkarpov15** [comment]
Would recommend not using `$where` because that prevents indexes from working. Try `this.find({ deleted: false });` instead.

**Comment by KATT** [comment]
@vkarpov15  Would that work for `findOne` hook? It reads counter-intuitively

**Comment by vkarpov15** [comment]
That won't quite work for `findOne()`. However, you can also do `this.where('deleted').equals(false);` and that will work for `find`, `findOne`, etc.

**Comment by TVMD** [comment]
> That won't quite work for `findOne()`. However, you can also do `this.where('deleted').equals(false);` and that will work for `find`, `findOne`, etc.

does this prevents indexes working ?

**Comment by vkarpov15** [comment]
@TVMD no, `this.where('deleted').equals(false)` is equivalent to `this.find({ deleted: false })`
