### ISSUE TITLE
Achieve optimistic concurrency with bulk updates

### ISSUE THREAD

**Issue by finwayDev** [Automattic/mongoose#12531]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We have `optimisticConcurrency: true` set in our schemas. And it works as expected when using save on individual documents. Given our data model, we sometimes have to use bulk operations though such as updateMany. Is there any way we can achieve OCC with bulk operations as well so that parallel operations that would overwrite each other are not possible?

**Comment by vkarpov15** [comment]
Not currently. We will implement support for this in a future minor release.

**Comment by vkarpov15** [comment]
I took a closer look and this won't be possible. The way that Mongoose implements optimistic concurrency only works when you've loaded the document being updated into memory, it doesn't handle potentially conflicting updates. I'm going to close this issue.
