### ISSUE TITLE
[DOCS] Mongoose website search does not work anymore

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#12539]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently the search at `https://mongoosejs.com/docs/search.html` does not work anymore, with error (that only appears shortly before reloading page):
`An Error occured: NetworkError: when attempting to fetch resource`
and after some waiting:
`An error occurred: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

No errors or warnings related in browser console.

using Firefox 105.0.2 on Linux

**Comment by vkarpov15** [comment]
Search is working again. The issue was that there was some intermittent outages in our MongoDB Atlas cluster yesterday. Looks like that's been fixed.
