### ISSUE TITLE
Set the document's field if it's empty

### ISSUE THREAD

**Issue by tadjik1** [Automattic/mongoose#12543]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.5

### Node.js version

16.17.1

### MongoDB version

MongoDB 6.0.1 Community

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Issue

Hello, I have a question about the possibility of updating the document's field on `findByIdAndUpdate` query. I was trying to research the documentation and similar questions but didn't find the answer.

The task is to find the document by identifier and update its' field if it's empty.
Here is the code example I try to run:

```js
const mongoose = require("mongoose");

mongoose.connect("mongodb://127.0.0.1:27017", { dbName: "test" });

const M = mongoose.model(
  "M",
  new mongoose.Schema({
    some_date: {
      type: mongoose.Schema.Types.Date,
    },
  })
);

(async () => {
  const m = await M.create({ some_date: new Date() });

  await M.findByIdAndUpdate(m.id, {
    some_date: {
      $ifNull: ["$some_date", Date.now()],
    },
  });
})();
```

But I get CaseError when run this. 
```
CastError: Cast to date failed for value "{ '$ifNull': [ '$some_date', 1665321906193 ] }" (type Object) at path "some_date"
```

Of course, I can do this operation in 2 steps and make the check on JS side:

```js
const doc = await M.findById(m.id);
if (!doc.some_date) {
  doc.some_date = new Date();
  doc.save();
}
```

But I'm now wondering, is that possible to do with one request? I have checked the aggregation pipeline in Compass and it seems working nicely:

<img width="1624" alt="Screenshot 2022-10-09 at 15 49 48" src="https://user-images.githubusercontent.com/1452895/194760556-fdc1da1b-f755-4820-b1ee-5cc791fa6486.png">

**Comment by hasezoey** [comment]
from what i can tell the operator [`$ifNull`](https://www.mongodb.com/docs/manual/reference/operator/aggregation/ifNull/) only works in *aggregation* not in a *normal query* (which `findByIdAndUpdate` is), so mongoose has no handling for this operator (from what i can tell) because it is not the proper place to use it and so tries to cast the whole object of `some_date: {}` to a date, which fails

**Comment by tadjik1** [comment]
thanks for taking a look at this case @hasezoey!

after some time I was able to solve this problem, turns out that the second argument should be an Array, in that case it treats as pipeline and you can do such things, so the final code looks like this:

```
await M.findByIdAndUpdate(m.id, [
  { $set: { some_date: { $ifNull: ["$some_date", new Date()] } } },
]);
```
