### ISSUE TITLE
Can't use $add aggregation inside FindOneAndUpdate

### ISSUE THREAD

**Issue by adamcole123** [Automattic/mongoose#12547]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.2.9

### Node.js version

v16.14.2

### MongoDB version

5.0.6 Community

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I am getting this error with my findOneAndUpdate

```
'Cast to Number failed for value "{ '$add': [ '$val', 20 ] }" (type Object) at path "volume"'
```

Here is the object that is passed into the query
```js
let dtoWithTrade: any = {
  ...stockDto, volume: {
    "$add": ["$val", Number(stockDto!.volume)]
  }
}
await this.executeEdit(dtoWithTrade, reject, resolve);
```
stockDto is just a type with some values, nothing that will impact this query.

Here is the find and update:
```js
Stock.findOneAndUpdate(stockDto.id ? { _id: stockDto.id } : { symbol: stockDto.symbol }, stockDto, { new: true })
```
where stockDto has the following form:
```js
{
  id: "6346c2301dc804d795c09fef",
  volume: {
    $add: [
      "$val",
      20,
    ],
  },
}
```

**Comment by samuelastech** [comment]
A similar issue can be found in #12543

**Comment by adamcole123** [comment]
I used `$inc` instead and it worked perfectly
