### ISSUE TITLE
Add lodash docs explaining that you shouldn't deepClone() documents

### ISSUE THREAD

**Issue by piyushk96** [Automattic/mongoose#12559]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.5

### Node.js version

16.15.1

### MongoDB server version

4.4.13

### Description

In continuation to #6507. Lodash `cloneDeep` is now working perfectly when there is single level array subdocuments as mentioned in [this comment](https://github.com/Automattic/mongoose/issues/6507#issuecomment-1111172672) but mongoose is still throwing following error when there is array of array subdocuments

```
myProject/node_modules/mongoose/lib/types/ArraySubdocument.js:149
  return this.__parentArray.$path() + '.' + this.__index + '.' + path;
                            ^
TypeError: this.__parentArray.$path is not a function
    at EmbeddedDocument.ArraySubdocument.$__pathRelativeToParent (/Users/myuser/myProject/node_modules/mongoose/lib/types/ArraySubdocument.js:149:29)
    at EmbeddedDocument.Subdocument.$isValid (/Users/myuser/myProject/node_modules/mongoose/lib/types/subdocument.js:150:25)
    at /Users/piyushkakkar/office/preppapi/node_modules/mongoose/lib/document.js:2802:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### Steps to Reproduce

**Demo Code:**

```
const cloneDeep = require('lodash.cloneDeep');
const mongoose = require('mongoose');

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test5');
  const arr2Schema = new mongoose.Schema({ _id: false, prop1: String });
  const arr1Schema = new mongoose.Schema({ _id: false, arr2: [arr2Schema] });
  const Test = mongoose.model(
    'Test',
    new mongoose.Schema({
      arr1: [arr1Schema],
      field: String,
    }),
  );

  let doc = new Test({ arr1: [{ arr2: [{ prop1: 'test' }] }] });
  await doc.save();

  const doc2 = await Test.findById(doc._id);
  const newDoc = cloneDeep(doc2).set({ field: 'test' });

  await newDoc.save(); // throws error
  console.log(newDoc);
}

run().catch((err) => console.log(err));
```

run this js script

### Expected Behavior

Document should be updated without any error

**Comment by vkarpov15** [comment]
I took a look and unfortunately we can't support `cloneDeep()` on documents with arrays in Mongoose 6. [cloneDeep() has no way of knowing whether an object is a proxy](https://stackoverflow.com/questions/50663784/lodash-clonedeep-remove-proxy-from-object), and [we switched to using proxies for arrays in Mongoose 6](https://thecodebarbarian.com/introducing-mongoose-6.html#arrays-as-proxies).

We're planning on shipping a `$clone()` function in v6.8 that will allow you to do the following. See #11849 and #12549 for more info.

```javascript
  const doc2 = await Test.findById(doc._id);
  const newDoc = doc2.$clone().set({ field: 'test' });

  await newDoc.save(); // works
  console.log(newDoc);
```

In the meantime, since `$clone()` isn't shipped yet, you should do the following:

```javascript
  const doc2 = await Test.findById(doc._id);
  const newDoc = new Test().init(doc2.toObject()).set({ field: 'test' });

  await newDoc.save(); // works
  console.log(newDoc);
```
