### ISSUE TITLE
How to prevent lost updates on standalone instance

### ISSUE THREAD

**Issue by gonmf** [Automattic/mongoose#12566]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

9.0.3

### Node.js version

16.4.1

### MongoDB version

5.0.6 community

### Operating system

macOs

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7

### Issue

I cannot seem to get simple transactions working correctly preventing lost update anomalies. Example:

```js
const session = await this.orderModel.startSession()
let finished = false

while (!finished) {
  await session.withTransaction(async (session) => {
    const order = await this.orderModel.findOne({ id: orderId }).exec()
    if (!order) { return }

    const update = await this.orderModel
      .updateOne(
        {
          id: orderId,
        },
        {
          testField: order.testField + 1,
        },
      )
      .exec()

    if (update.modifiedCount === 1) {
      finished = true
    } else {
      await session.abortTransaction()
    }
  })
}

await session.endSession()
```

I know I could use `findOneAndUpdate` in this example, but the real change is more complex.

How can I ensure that my transaction acquires a read lock at `findOne`, preventing lost updates, and without having to setup a cluster/replica set?

Thank you for reading

**Comment by vkarpov15** [comment]
You need to pass the `session` to every operation in the transaction. So something like the following:

```javascript
    const order = await this.orderModel.findOne({ id: orderId }).session(session).exec()
    if (!order) { return }

    const update = await this.orderModel
      .updateOne(
        {
          id: orderId,
        },
        {
          testField: order.testField + 1,
        },
      )
      .session(session)
      .exec()
```

**Comment by gonmf** [comment]
Hello Valeri, unfortunately I get error

> Transaction numbers are only allowed on a replica set member or mongos

So is it possible without having to have a replica set?

**Comment by sean-daley** [comment]
Per the MongoDB docs at https://www.mongodb.com/docs/manual/core/transactions/ ... replicasets (or sharded clusters) are required for transaction support. Note, this is not a mongoose (this library) limitation, this is a MongoDB server limitation. There are some suggestions out there about running a solo server as a replica set. I haven't tried this but just posting it if it helps you ... https://stackoverflow.com/questions/62343611/enabling-mongodb-transactions-without-replica-sets-or-with-least-possible-config
