### ISSUE TITLE
maxTimeMS in client options

### ISSUE THREAD

**Issue by harishsambasivam** [Automattic/mongoose#12563]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.x.x

### Node.js version

14.x.x

### MongoDB version

4.4

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Issue

Im looking for a way to pass maxTimeMs in client options. In native MongoDB drive this options is available.

https://www.mongodb.com/docs/drivers/node/current/faq/#how-can-i-prevent-long-running-operations-from-slowing-down-the-server-

```
const client = new MongoClient(uri, {
  connectTimeoutMS: <integer value>,
  socketTimeoutMS: <integer value>,
  maxTimeMS: <integer value>,
});
```

Can i achieve the same in mongoose to add maxTimeMs to mongoose globally?

Current Workaround:
I'm using mongoose plugins to setOptions.

```

const collection = "listingsAndReviews";

const schema = new mongoose.Schema({ beds: "string" , bedrooms: "number" });

const maxMillisPlugin = function loadedAtPlugin(schema, options) {
  schema.pre(['find', 'findOne'], function (next) {
    this.setOptions({
      maxTimeMS: 100
    })
    console.log(this.options)
    next()
  });
};

mongoose.plugin(maxMillisPlugin);

mongoose.set('debug', true);
```

Thanks.

**Comment by vkarpov15** [comment]
Yep, you can do `mongoose.set('maxTimeMS`, 100)` to set `maxTimeMS` globally.
