### ISSUE TITLE
Sort with multiple parameters

### ISSUE THREAD

**Issue by Frederic-Ferreira** [Automattic/mongoose#12581]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.15

### Node.js version

16.14.0

### MongoDB version

6.0.2

### Operating system

macOS

### Issue

Hello,
I have an issue with query.sort() ... The problem is that, when passing one value (/parameter) it works, but when passing multiple parameters it doesn't take into account the ones after the first parameter. 

I am using the string syntax for passing multiple parameters : query.sort('field -test'); // from mongoose.js docs

My query looks like this : 127.0.0.1:3000/api/v1/tours?sort=ratingsAverage,price

Here is my code : 

```
exports.getAllTours = async (req, res) => {
    const queryObj = { ...req.query }; 
    let query = Tour.find(queryObj);

    if (req.query.sort) {
      const sortBy = req.query.sort.split(',').join(' ');
      query = query.sort(sortBy);
    } 

const tours = await query;

    res.status(200).json({
      status: 'success',
      requestedAt: req.requestTime,
      results: tours.length,
      data: {
        tours
      }
    });
  } catch (err) {
    res.status(404).json({
      status: 'fail',
      message: err
    });
  }
};

```

**Comment by IslandRhythms** [comment]
add an `await` in front of `Tour.find()`

**Comment by Frederic-Ferreira** [comment]
Adding an await in front of Tour.find() doesn't work ... Plus, my first parameter for sort() is taken into consideration in the response data, but any other parameter after "," doesn't work (so the request is sent successfully and the response also, with no error, it is just the other parameters of sort which are not working)

**Comment by IslandRhythms** [comment]
Double check everything
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  price: Number,
  ratingsAverage: Number,
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    price: 9,
    ratingsAverage: 10,
    name: 'Second'
  });

  await Test.create({
    price: 8,
    ratingsAverage: 10,
    name: 'First'
  });

  await Test.create({
    price: 10,
    ratingsAverage: 10,
    name: 'Third'
  })

  let queryString = 'ratingsAverage,price';
  const newString = queryString.split(',').join(' ');
  console.log(newString);
  const res = await Test.find().sort(newString);
  console.log(res);

  let query = Test.find();
  query = query.sort(newString);

  const response = await query;
  console.log('Response', response);
}

run();
```

**Comment by Frederic-Ferreira** [comment]
Hello, thank you for your response. Since you put the same ratngsAverage for each of your tests document, I took the liberty of changing those into : 
`
  await Test.create({
    price: 9,
    ratingsAverage: 7,
    name: 'Second'
  });

  await Test.create({
    price: 8,
    ratingsAverage: 8,
    name: 'First'
  });

  await Test.create({
    price: 10,
    ratingsAverage: 9,
    name: 'Third'
  });
`

And the response I got was : Response [
  {
    _id: new ObjectId("6356e1ccf46219ce787fc349"),
    price: 9,
    ratingsAverage: 7,
    name: 'Second',
    __v: 0
  },
  {
    _id: new ObjectId("6356e1ccf46219ce787fc34b"),
    price: 8,
    ratingsAverage: 8,
    name: 'First',
    __v: 0
  },
  {
    _id: new ObjectId("6356e1cdf46219ce787fc34d"),
    price: 10,
    ratingsAverage: 9,
    name: 'Third',
    __v: 0
  }
]

**Comment by Frederic-Ferreira** [comment]
Somehow two parameters doesn't seem to work

**Comment by IslandRhythms** [comment]
It is working. Its just not explained well. How sort works is it will sort by ratingsAverage first, then by price. So in your response, ratingsAverage is sorted ascending and then it will sort price while keeping ratingsAverage in order.

**Comment by IslandRhythms** [comment]
We should amend the docs to mention how sorting with multiple fields works.

**Comment by Frederic-Ferreira** [comment]
It gives an order of priority to the first parameter, is that it ?

**Comment by IslandRhythms** [comment]
Yes

**Comment by Frederic-Ferreira** [comment]
Okay thank you very much
