### ISSUE TITLE
Typescript: Error Handling Middleware callback function params are implicitly set to 'any'.

### ISSUE THREAD

**Issue by MindeVieras** [Automattic/mongoose#12583]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.7

### Node.js version

18.11.0

### MongoDB version

6.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Issue

I'm following this documentation [[Error Handling Middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware)](https://mongoosejs.com/docs/middleware.html#error-handling-middleware), and TypeScript does not infer the error middleware function arguments if three parameters are given.

```
userSchema.post('save', function (error, doc, next) { <------ All params implicitly has an 'any' type.
  if (error.name === 'MongoServerError' && error.code === 11000) {
    next(new Error('There was a duplicate key error'))
  } else {
    next()
  }
})
```

I know it is possible to set those types explicitly. However, it will lead to a bunch of boilerplate code, which should be inferred from `ErrorHandlingMiddlewareFunction` type.

My tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "rootDir": "src",
    "outDir": "dist",
    "lib": [
      "es6"
    ],
    "removeComments": false,
    "strict": true,
    "declaration": true,
    "declarationDir": "types",
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "include": [
    "src",
    "test"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  avatar?: string;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new mongoose.Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

userSchema.post('save', function (error, doc, next) {
  console.log('save hook triggered')
  console.log(error.name);
  console.log(doc.name)
});

// 3. Create a Model.
const User = mongoose.model<IUser>('User', userSchema);

run().catch(err => console.log(err));

async function run() {
  // 4. Connect to MongoDB
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();
  const user = new User({
    name: 'Bill',
    email: 'bill@initech.com',
    avatar: 'https://i.imgur.com/dM7Thhn.png'
  });
  await user.save();

  console.log(user.email); // 'bill@initech.com'
}
```

**Comment by MindeVieras** [comment]
@IslandRhythms, thank you for the response, but I'm still getting the same typescript errors.

<img width="814" alt="Screenshot 2022-10-24 at 18 30 48" src="https://user-images.githubusercontent.com/12902970/197589153-7216bede-3513-4e76-a014-eab5b3965a1f.png">

**Comment by vkarpov15** [comment]
@MindeVieras does TypeScript compilation actually fail, or are you just getting red lines in your editor?

**Comment by MindeVieras** [comment]
@vkarpov15 thank you for the response. Yes, it still fails:

<img width="737" alt="Screenshot 2022-11-01 at 20 24 35" src="https://user-images.githubusercontent.com/12902970/199333953-445ace6b-4395-4537-878b-30873b6f24dc.png">

**Comment by vkarpov15** [comment]
It looks like TypeScript struggles to distinguish between `(this: ThisType, res: ResType, next: CallbackWithoutResultAndOptionalError) => void` and `(this: ThisType, err: NativeError, res: ResType, next: CallbackWithoutResultAndOptionalError) => void`, maybe because it doesn't assume that number of arguments can be used to distinguish between 2 function overloads. If I delete the non-error-handling `post()` definitions, this code compiles fine.

We're probably going to have to add a new feature or way to define error handling middleware that TypeScript can distinguish.

**Comment by vkarpov15** [comment]
See #12723, you'll have to do the following in 6.8 to help TypeScript out:

```ts
userSchema.post('save', { errorHandler: true }, function (error, doc, next) {
  if (error.name === 'MongoServerError' && error.code === 11000) {
    next(new Error('There was a duplicate key error'))
  } else {
    next()
  }
})
```
