### ISSUE TITLE
populated subdocument has parent's type, not subdocument's type itself(typescript)

### ISSUE THREAD

**Issue by alanpurple** [Automattic/mongoose#12596]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

populated property should have its subdocument schema, not parent's schema

### Motivation

this feature is about typescript typing

### Example

if 'Book' has subdocument 'Author' with id which is number

populate('Author') works, but typescript compiler sees it as just a number, not a 'Author' type

**Comment by vkarpov15** [comment]
Can you please provide some code samples?

**Comment by alanpurple** [comment]
@vkarpov15 
```
const nextAffi = await AffiModel.findOne({ _id: { $nin: userAffis } }).populate('NbdList');
        /*const affis = await AffiDistModel.find({ id1: nextAffi })
            .sort({ dist: 1 })
            .limit(parseInt(req.params.numEntries));
        res.send({ affis: affis });*/
        if (!nextAffi) {
            res.sendStatus(404);
            return;
        }
        const newlist = nextAffi.NbdList.filter(elem => !userAffis.includes(elem)).map(
            elem => {
                const nbd = elem as unknown as Affi;
                return {
                    _id: nbd._id,
                    url: nbd.url,
                    name: nbd.name
                }
            }
        );
```

here nbdlist is type Affi[] but typescript detect it as an other type( Affi's _id types) so only way to treat those is casting as unknown and cast to actual type

**Comment by vkarpov15** [comment]
@alanpurple hard to tell without a more complete code sample, you're missing schemas, TypeScript version, etc. It does look like you aren't using the generic param to `populate()`, can you take a look at the [Mongoose TypeScript populate docs](https://mongoosejs.com/docs/typescript/populate.html)?

The following script compiles fine:

```ts
import mongoose from 'mongoose';

run().catch(err => console.log(err));

async function run() {
  const Parent = mongoose.model('Parent', new mongoose.Schema({
    name: String,
    children: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Child' }]
  }));
  const Child = mongoose.model('Child', new mongoose.Schema({
    name: String,
    age: Number
  }));

  const parent = await Parent.findOne().orFail().populate<{ children: Child[] }>('children');
  const child: typeof Child | undefined = parent.children[0];
}
```

**Comment by alanpurple** [comment]
@vkarpov15 

I appreciated, I had little information about using populate with typescript

thantks, again
