### ISSUE TITLE
The property justOne in PopulateOptions states an error

### ISSUE THREAD

**Issue by tianguangcn** [Automattic/mongoose#12599]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

16.x

### MongoDB server version

4.9.1

### Typescript version (if applicable)

^4.5.3

### Description

The property justOne in PopulateOptions states an error

```   
    /**
     * If true Mongoose will always set `path` to an array, if false Mongoose will
     * always set `path` to a document. Inferred from schema by default.
     */
     justOne?: boolean;
```
When justOne is set  false, the result is an array， true will retrun  a document.

### Steps to Reproduce

set justOne:false and  justOne:true , 
the result does not match the document description

### Expected Behavior

The property justOne in PopulateOptions states an error ？
Determine if it is a bug, hope to update the documentation and code source code

**Comment by tianguangcn** [comment]
I had a hard time following the official documentation when using PopulateOptions, and the results of my attempts were always inconsistent with the documentation.

**Comment by hasezoey** [comment]
to clarify, you are not asking about a "error" but a incorrect type, correct? if it is actually a error, please provide the error (and a code example would be good too)
