### ISSUE TITLE
.lean and .populate together

### ISSUE THREAD

**Issue by kof** [Automattic/mongoose#1260]
Is there any way or any plans to make them usable together?

Are there any issues which make it difficult to implement?

P.S. I am now using .lean in the most places, because I spent a huge amount of cpu time on wrapping in mongoose documents.

**Comment by mallikarjunece** [comment]
How to use lean and populate together ?

**Comment by vkarpov15** [comment]
@mallikarjunece If you set `lean()` on your query like `Model.find().lean().populate('myPath')`, `lean()` will also apply to the populated docs.
