### ISSUE TITLE
Populating collection doesnt seem to work

### ISSUE THREAD

**Issue by sixpounder** [Automattic/mongoose#12602]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.5

### Node.js version

16.15.0

### MongoDB version

Mongo docker image latest tag

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 36

### Issue

I am assuming I am doing something wrong, so I will just report the issue as I see it: when populating nested documents it all works fine until the populated path resolves to a single document. For example, having the following schemas:

```typescript
export const clientSchema: Schema = new Schema<IClient>({
  displayName: {
    type: String,
    required: true,
  },
  domains: [{
    type: Schema.Types.ObjectId,
    ref: 'Domain'
  }]
})

export const domainSchema: Schema = new Schema<IDomain>({
  identifier: {
    type: String,
    required: true,
    index: true,
    unique: true
  },
  plan: domainPlanSchema,
  description: {
    type: String,
    required: false,
  },
  owner: {
    type: Types.ObjectId,
    ref: 'Client'
  },
})

export const Client = mongoose.model<IClient>('Client', clientSchema, 'clients')
export const Domain = mongoose.model<IDomain>('Domain', domainSchema, 'domains')
```

If I do:

```typescript
await Domain.findById(...).populate('owner')
```

... then owner is correctly populated. But if I try to:

```typescript
await Client.findById(...).populate('domains')
```

...then domains never gets populated. More interesting is the fact that, by enabling mongoose debug logs, I can see that the query on domains is executed, but it's like it happens on some successive digest

```
[1] Mongoose: clients.findOne({ _id: new ObjectId("6350fc71d9f0ef5997253cd6") }, { projection: {} })
<value is returned here>
[1] Mongoose: domains.find({ owner: new ObjectId("6350fc71d9f0ef5997253cd6") }, { projection: {} }) // <- this happens when the function executing clients.findOne has already returned
```

What am I doing wrong here?

**Comment by mrj0** [comment]
I appear to be having the same problem after an upgrade to Mongoose 6.7.0. The same populate call worked with 5 but is now only populating the id field. I see the related document query run with debug on, too.

**Comment by hasezoey** [comment]
i cannot reproduce the mentioned behavior, please modify the following code to match your problem:

Code used:

```ts
// NodeJS: 18.10.0
// MongoDB: 5.0 (Docker)
// Typescript 4.8.4
import * as mongoose from 'mongoose'; // mongoose@6.6.5

const Schema = mongoose.Schema;

const clientSchema = new Schema(
  /* <IClient> */ {
    displayName: {
      type: String,
      required: true,
    },
    domains: [
      {
        type: Schema.Types.ObjectId,
        ref: 'Domain',
      },
    ],
  }
);

const domainSchema = new Schema(
  /* <IDomain> */ {
    // identifier: {
    //   type: String,
    //   required: true,
    //   index: true,
    //   unique: true,
    // },
    // plan: domainPlanSchema,
    description: {
      type: String,
      required: false,
    },
    owner: {
      type: Schema.Types.ObjectId,
      ref: 'Client',
    },
  }
);

const Client = mongoose.model(/* <IClient> */ 'Client', clientSchema, 'clients');
const Domain = mongoose.model(/* <IDomain> */ 'Domain', domainSchema, 'domains');

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  // create initial documents
  const c1 = await Client.create({ displayName: 'test1' });
  const c2 = await Client.create({ displayName: 'test2' });
  const d1 = await Domain.create({ description: 'test1', owner: c1 });
  const d2 = await Domain.create({ description: 'test2', owner: c2 });
  // modify existing documents to have the domains in the array
  await (c1.domains as any).push(d1._id);
  await (c2.domains as any).push(d2._id);
  await c1.save();
  await c2.save();

  // actual find and populate
  const foundDomain = await Domain.findById(d2).populate('owner');
  const foundClient = await Client.findById(c1).populate('domains');

  console.log('foundDomain', foundDomain); // has "owner" populated
  console.log('foundClient', foundClient); // has "domains" populated

  await mongoose.disconnect();
})();
```

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseGh12602

---

as a note, you might want to consider using [virtual populate](https://mongoosejs.com/docs/populate.html#populate-virtuals) for `clientSchema.domains`, as long as `domains` have `owner` properly defined

**Comment by sixpounder** [comment]
> ~I appear to be having the same problem after an upgrade to Mongoose 6.7.0. The same populate call worked with 5 but is now only populating the id field. I see the related document query run with debug on, too.~
> 
> Nvm, a subtle change to the return type tripped me up

Same here, closing
