### ISSUE TITLE
Type error will appear in createConnection

### ISSUE THREAD

**Issue by shibin-cli** [Automattic/mongoose#12618]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

16.16.0

### MongoDB server version

6.0.0

### Typescript version (if applicable)

4.8.0

### Description

If you use the official website sample code to connect to the database, there will be a TS error

### Steps to Reproduce

Use the official website example code
```ts
import { createConnection } from 'mongoose';
const opts = { server: { auto_reconnect: false }, user: 'username', pass: 'mypassword' };
const db = createConnection('localhost', 'database', 27017, opts);
```
Ts error occurs
```
Expected 0-3 arguments, but got 4.
```

**Comment by irham01** [comment]
+1

**Comment by lpizzinidev** [comment]
It's probably just an outdated example remaining from #6766 since the `mongoose.createConnection(host, dbname, port)` syntax is no longer supported.
