### ISSUE TITLE
Schema default functions problem

### ISSUE THREAD

**Issue by mcdoeswhat** [Automattic/mongoose#12617]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

v16.17.0

### MongoDB server version

6.0.2 community

### Description

```
export function genSalt(length=6) {
    return genRandomString(length,"abcdefghijklmnopqrstuvwxyz0123456789");
}
```

Mongoose Schema:

```
salt: {
        type: String,
        trim: true,
        lowercase: true,
        default: genSalt,
    }
```

mongodb data:
[![mongodb](https://i.stack.imgur.com/pTgKm.png)](https://i.stack.imgur.com/pTgKm.png)

But wiredly the problem will gone if I change the default value into an arrow function or anonymous function:

```
 default: ()=>genSalt(),
 default: function(){return genSalt()},
```

mongodb data:
[![mongodb](https://i.stack.imgur.com/hZrZW.png)](https://i.stack.imgur.com/hZrZW.png)

eg: the genSalt function is correctly imported,

### Steps to Reproduce

```
export function genSalt(length=6) {
    return genRandomString(length,"abcdefghijklmnopqrstuvwxyz0123456789");
}


export function genRandomString(length,possible="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789") {
    let text = "";
    for (let i = 0; i < length; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
}

```

imported from a different file

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

function defaultName() {
  return 'Mongoose';
}

const testSchema = new mongoose.Schema({
  name: {
    type: String,
    trim: true,
    lowercase: true,
    default: defaultName
  },
  age: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const entry = await Test.create({age: 2});

  console.log(await Test.findOne());
}

run();
```

**Comment by lpizzinidev** [comment]
This should work:
```
salt: {
        type: String,
        trim: true,
        lowercase: true,
        default: genSalt()
}
```
The problem is that by passing the function as a variable it reaches this line to get its value resolved:
https://github.com/Automattic/mongoose/blob/8b0adf5a5dc519215c22a9db720cf01777fa8180/lib/schematype.js#L1126

So the `genSalt` function default parameter is overridden by the `scope` (an object).
For that reason, it returns an empty string.
