### ISSUE TITLE
cross db populate in both directions

### ISSUE THREAD

**Issue by sambP** [Automattic/mongoose#12612]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.x.x

### Node.js version

16.x

### MongoDB version

5.x

### Issue

1. Question: How is it possible to create a cross-db reference from the conversation back to the event? https://mongoosejs.com/docs/populate.html#cross-db-populate

```js
const db1 = mongoose.createConnection('mongodb://localhost:27000/db1');
const db2 = mongoose.createConnection('mongodb://localhost:27001/db2');

const conversationSchema = new Schema({
  name: String,
  events: {
    type: ObjectId,
    ref: Event // here is the problem because the instance of Event is not defined at this point...
  }
});
const Conversation = db2.model('Conversation', conversationSchema);

const eventSchema = new Schema({
  name: String,
  conversation: {
    type: ObjectId,
    ref: Conversation // `ref` is a **Model class**, not a string
  }
});
const Event = db1.model('Event', eventSchema);
```

2. Question: How to create self-references? I realized them in the past by simply writing the name of the collection as String, but this does not work in that case, because then a population across the database does not work anymore.
It would be also pretty interesting how it is possible to realize a self-reference across DBS. 

```js
const db1 = mongoose.createConnection('mongodb://localhost:27000/db1');
const db2 = mongoose.createConnection('mongodb://localhost:27001/db2');

const conversationSchema = new Schema({
  name: String,
  conversations: {
    type: ObjectId,
    ref: 'Conversation' // this does not work across databases...
  }
});
const Conversation = db2.model('Conversation', conversationSchema);

const eventSchema = new Schema({
  name: String,
  conversation: {
    type: ObjectId,
    ref: Conversation // `ref` is a **Model class**, not a string
  }
});
const Event = db1.model('Event', eventSchema);

const event = await Event.findOne({}).populate('conversation').popluate('conversation.conversations');
```

**Comment by vkarpov15** [comment]
This question is a little strange because "self-reference across DBs" doesn't make sense. Mongoose models are associated with exactly one connection, so you can't have a model point to different databases. Either way, I think this is a problem with your populate syntax, because Mongoose currently doesn't support `populate('conversation.conversations')` as a way to populate a path underneath another populated path. The following script works as expected:

```javascript
'use strict';

const mongoose = require('mongoose');
const { Schema, ObjectId } = mongoose;

run().catch(err => console.log(err));

async function run() {
  const db1 = await mongoose.createConnection('mongodb://127.0.0.1:27017/db1').asPromise();
  const db2 = await mongoose.createConnection('mongodb://127.0.0.1:27017/db2').asPromise();

  await db1.dropDatabase();
  await db2.dropDatabase();

  const conversationSchema = new Schema({
    name: String,
    conversations: {
      type: ObjectId,
      ref: 'Conversation' 
    }
  });
  const Conversation = db2.model('Conversation', conversationSchema);

  const eventSchema = new Schema({
    name: String,
    conversation: {
      type: ObjectId,
      ref: Conversation // `ref` is a **Model class**, not a string
    }
  });
  const Event = db1.model('Event', eventSchema);

    const c1 = await Conversation.create({ name: 'foo' });
  const c2 = await Conversation.create({ name: 'bar', conversations: c1._id });
  const e = await Event.create({ name: 'baz', conversation: c2._id });

  const event = await Event.findOne({}).populate({ path: 'conversation', populate: 'conversations' });
  console.log(event); // Includes { name: 'foo' }
}
```

**Comment by sambP** [comment]
Hi, @vkarpov15  thanks for the answer! But this doesn't solve my problem. I have two schemas, one in each DB and they both refer to one another. Conversations hold Events and Events hold Conversations. This is currently not possible with mongoose because in order to reference a schema from another db, you have to pass the instance of the schema, which at this point does not exist, because it depends on the other schema...

**Comment by vkarpov15** [comment]
`ref` can also be a function. So you can do something like `ref: () => db2.model('Conversation')`. Does that work @sambP ?
