### ISSUE TITLE
deleteMany() with typegoose throws Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by lostrouter** [Automattic/mongoose#12615]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.0

### Node.js version

14.20.1

### MongoDB server version

4.11.0

### Typescript version (if applicable)

4.8.3

### Description

Related to https://github.com/Automattic/mongoose/issues/12277. I think that means this is a mongoose issue and not a typegoose issue, but i could be wrong here. 

### Steps to Reproduce

```ts
export interface MyModel extends Base {}
export class MyModel extends TimeStamps {
  /* model properties */
  @prop()
  public name: string
}
```

I'm generating test data, and using `MyModel.deleteMany({})` to clean up after the tests and it throws `Type instantiation is excessively deep and possibly infinite.`

other impacted methods

`MyModel.create`

### Expected Behavior

calling `MyModel.deleteMany({})` does not `Type instantiation is excessively deep and possibly infinite.`

**Comment by lostrouter** [comment]
> maybe related to [typegoose/typegoose#752](https://github.com/typegoose/typegoose/issues/752) ?

@hasezoey That post is what led me over here. i saw the linked pr in the description above making some typing changes to mongoose.  Should i open the issue on against typegoose as well?

**Comment by vkarpov15** [comment]
As far as I can tell, this is the same issue as #12277, so please read [this comment](https://github.com/Automattic/mongoose/issues/12277#issuecomment-1258473297) if you're seeing this issue. If you're experiencing a similar problem, please open a new issue and follow the issue template.
