### ISSUE TITLE
eachAsync passes more elements than the specified batchSize in doc array to fn, when both parallel and batchSize are used

### ISSUE THREAD

**Issue by SevanEl** [Automattic/mongoose#12652]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.1

### Node.js version

16.18.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

4.8.4

### Description

In a call to `eachAsync`, when both `parallel` and `batchSize` are set to numbers higher than 1, it is expecting to call the `fn` function for each batch of element(s) returned by the cursor, simultaneously, up to `parallel` times, and continue to do so till the exhaustion of the cursor.
As it turns out, the process of reading next elements from the cursor continues to fill the same `doc` array instance, which is already being processed. This can be reproduced by having a time consuming process in the `fn` function and checking the number of elements in `doc` array **before** and **after** such processing.

### Steps to Reproduce

The second and third assertion fail in the fallowing test case:

```js
'use strict';

const mongoose = require('mongoose');
const assert = require('assert');

run().catch(console.error);

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {});

    await mongoose.connection.dropDatabase();

    const User = mongoose.model('user', {});

    const usersCount = 10000;

    const users = Array.from({ length: usersCount }).map(() => ({}));
    await User.create(users);

    const cursorBatchSize = 50;
    const batchSize = 100;

    let counter = 0;

    await User.find({})
        .lean()
        .cursor({ batchSize: cursorBatchSize })
        .eachAsync(async (documents) => {
            assert.equal(documents.length, batchSize);

            counter += documents.length;
            await new Promise((f) => setTimeout(f, 1));

            assert.equal(documents.length, batchSize);
        }, { parallel: 10, batchSize });

    assert.equal(counter, usersCount);

    console.log('All assertions passed.');
}

```

### Expected Behavior

The number of elements in `doc` array, which is passed to `fn`, should be consistent and equal to the `batchSize` passed as `options` to `eachAsync`. Executing other async functions, which might be time consuming, in `fn` function should not effect the number of elements in `doc` array passed to the `fn`.

**Comment by diazoxide** [comment]
@SevanEl I confirm that the bug is actual on my environment too 🤯🤯🤯
