### ISSUE TITLE
Schema.add method not copy indexes

### ISSUE THREAD

**Issue by JorgeSilva7** [Automattic/mongoose#12654]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.5

### Node.js version

14.18.0

### MongoDB server version

4.2.21

### Typescript version (if applicable)

4.8.4

### Description

When i use Schema.prototype.add() method for copy schema to an other schema, the indexes don't  be copied.

### Steps to Reproduce

I have a `test` schema

```ts
const test = new Schema({
   name: String
}):

...someMethods, statics...

test.index({name: 1});
```

And other schema called 'extended' and i want to add `test` schema in `extended` with [add() method](https://mongoosejs.com/docs/api/schema.html#schema_Schema-add) like the documentation say "You can also `add()` another schema and copy over all paths, virtuals, getters, setters, **indexes**, methods, and statics."

```ts
const extended = new Schema({
   property: String
});

extended.add(test);

```

But extended schema haven't the index `name`

### Expected Behavior

When i call `extended.indexes()` the returned array has the index `{name: 1}`

**Comment by hasezoey** [comment]
> And other schema called 'extended' and i want to add test schema in extended with [add() method](https://mongoosejs.com/docs/api/schema.html#schema_Schema-add) like the documentation say "You can also add() another schema and copy over all paths, virtuals, getters, setters, indexes, methods, and statics."

i think the documentation needs to be updated, because in the description it says `Adds key path / schema type pairs to this schema.` while in the code comments it says `You can also 'add()' another schema and copy over all paths, virtuals, getters, setters, indexes, methods, and statics.` [`[Schema.prototype.add()](https://mongoosejs.com/docs/api/schema.html#schema_Schema-add)`](https://mongoosejs.com/docs/api/schema.html#schema_Schema-add)

---

as a workaround, if `test` is a base-schema and you dont need to add other schemas, consider using [`.clone`](https://mongoosejs.com/docs/api/schema.html#schema_Schema-clone)

**Comment by JorgeSilva7** [comment]
But currently the `add()` method copy paths, methods, statics, virtuals, getters, setters. Only the indexes don't be copied.

**Comment by IslandRhythms** [comment]
I did some digging. If you define the index in the schema and then call add, if will be added correctly. If you use the index method it will not be added correctly.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: {type: String}
});

const otherSchema = new mongoose.Schema({
  age: { type: Number}
});

otherSchema.index({ age: 1 })

testSchema.add(otherSchema);

console.log(testSchema);
console.log(testSchema.tree)
console.log(testSchema.tree.age)
```
Marking as a bug because if the docs say it suppose to do something, it should be doing it. Especially if the code is written so.

**Comment by JorgeSilva7** [comment]
Finally i used [.clone()](https://mongoosejs.com/docs/api/schema.html#schema_Schema-clone) method and .add() with .set() methods for add paths and options.

```js
testSchema.index({...someIndex});

const otherSchema = testSchema.clone();
otherSchema.add({...paths})
otherSchema.set(someOptions)
```
Now `otherSchema` has the indexes of `testSchema`
