### ISSUE TITLE
How to select return fields when calling insertMany

### ISSUE THREAD

**Issue by guya-activefence** [Automattic/mongoose#12653]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.11.8

### Node.js version

14.0.7

### MongoDB version

4.2.3

### Issue

Hi all,

I'm using insertMany to insert thousands of big documents, and I want to squeeze the max performance I can.
I've already disabled validation with lean: true.
But I want also to get nothing in return or only the ids, is that possible?

Thanks in advance

**Comment by hasezoey** [comment]
i dont think this is possible, unless option [`noResponse`](https://mongodb.github.io/node-mongodb-native/4.9/interfaces/BulkWriteOptions.html#noResponse) works, though because it has no description and is not mentioned elsewhere i dont know if it does this or something else

**Comment by vkarpov15** [comment]
`insertMany` just returns the values you passed in by default, so returning just the ids wouldn't help performance. Under the hood, the MongoDB server already sends a response with just the inserted ids.
