### ISSUE TITLE
How to organize Mongoose models into a monorepo structure

### ISSUE THREAD

**Issue by noghartt** [Automattic/mongoose#12661]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.1

### Node.js version

18.11.0

### MongoDB version

6.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13 (Ventura)

### Issue

I have a monorepo structure in my project and I would like to split all my models into single packages. But I have a package where my project (and my business logic) is running and I  would like to import these "models package" and use it.

Something like the image below:

<div align="center">
  <img src="https://user-images.githubusercontent.com/47952043/200146619-ca1318e3-8638-492e-b26b-6d1041a8d582.png" width="400px" />
</div>

My issue is that `mongoose` should be a *singleton*, but when I do it, they lose the reference  for some models. Should it happen? How we can fix it?

**Comment by hasezoey** [comment]
> My issue is that mongoose should be a singleton, but when I do it, they lose the reference for some models. Should it happen? How we can fix it?

this sounds like you have multiple mongoose packages installed, this can happen when the package does not get de-duplicated or the packages using the package in question have different requirements
you can try using `npm ls mongoose` or `yarn why mongoose` and see what is installed (or search manually through the lockfile)
