### ISSUE TITLE
Add deprecation warning for default `strictQuery`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#12666]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We're planning on switching `strictQuery` back to `false` in Mongoose 7, see #11861. We should add a deprecation warning to encourage devs to add `mongoose.set('strictQuery', false)` in their projects to prepare for this change.

**Comment by lpizzinidev** [comment]
When should the warning be displayed? 
On database connection?

**Comment by hasezoey** [comment]
>  When should the warning be displayed?

i would guess under the following conditions:
on query or on connection if `strictQuery` is not manually set and maybe only if it would affect the query by having it `true`

**Comment by vkarpov15** [comment]
I think only on database connection. We're changing the default global option, so printing a warning if `strictQuery` isn't set on a query doesn't seem like the way to go.

**Comment by mohit4bug** [comment]
import mongoose from "mongoose";


// ADD THIS IS YOUR CONNECTION FILE
mongoose.set('strictQuery', true);

// CONNECTION
mongoose.connect("mongodb://0.0.0.0:27017/<dbname>", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(console.log("connected to db!"))
    .catch(e => console.log(e))
