### ISSUE TITLE
How to load mongoose Schema from the collection name

### ISSUE THREAD

**Issue by hashweather** [Automattic/mongoose#12667]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

14.19.1

### MongoDB version

4.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

MacOS Monterey, 12.4

### Issue

Ideally, for populate to work during queries in mongoose, both the schemas of that which is been populated and the calling schema needs to be imported in same file under same repo.

Now, I have a scenario where a schema called `AuthorSchema` was created by another internal micro-service in another repo which is pointing to the same database as my own service and I wish to populate it during my queries.

Is there a way to automatically decode the `AuthorSchema` from the `author` collection name after I've connected to the database?

E.g
  

    let posts = await Post.find({})
                .populate("author", 'first_name last_name _id').limit(10)

Where I have created `postSchema` in my own service but `authorSchema` was created by another micro-service in another repo called `author-management-microservice` and as such I have no access to that schema.

What I would want is something like:

    let AuthorSchema = mongoose.connection.decodeSchemaFromCollectionName('author');
    
Such that I can modify my query to something like

    let posts = await Post.find({})
                    .populate({path:"author", model:AuthorSchema, select:'first_name last_name _id'}).limit(10)

The reason I want something like this is because I have been battling with `MissingSchemaError: Schema hasn't been registered for model "Author".` whenever I try to populate `author` and I don't want to copy around duplicate schema files across different micro-services.

**Comment by lorand-horvath** [comment]
@hashweather I'm not sure if this would help, but I usually get the schema from a Model with Model.prototype.schema
