### ISSUE TITLE
Mongoose Schema created using CommonJS not working again after porting to Module

### ISSUE THREAD

**Issue by hashweather** [Automattic/mongoose#12662]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.1

### Node.js version

14.19.1

### MongoDB version

4.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

MacOS Monterey, 12.4

### Issue

I started out my Mongoose Schema declarations using CommonJS as shown below and populate was working perfectly.

For CommonJS I have:

**author.js**

    const mongoose = require('mongoose');
    
    const AuthorSchema = new mongoose.Schema({
        _id: mongoose.Schema.Types.ObjectId,
        first_name: String,
        last_name: String,
        email: String,
    }, {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at'
        }
    });
    
    module.exports = mongoose.model('Author', AuthorSchema);

**comment.js**

    const mongoose = require('mongoose');
    
    const CommentSchema = new mongoose.Schema({
        _id: mongoose.Schema.Types.ObjectId,
        text: String,
        author: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Author'
        }
    }, {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at'
        }
    });
    
    module.exports = mongoose.model('Comment', CommentSchema);

and the below query worked flawlessly when using CommonJS

    let comments = await Comment.find({ author: authorId })
            .populate("author", 'first_name last_name _id').limit(10);

Now, my team wanted us to move away from CommonJS to modules and so I added `type:module` to my `package.json` file and attempted to refactor the schema declarations above to the following:

**new_author.js**

    import mongoose from 'mongoose';
    
    const AuthorSchema = new mongoose.Schema({
        _id: mongoose.Schema.Types.ObjectId,
        first_name: String,
        last_name: String,
        email: String,
    }, {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at'
        }
    });
    
    export default mongoose.model('Author', AuthorSchema);

and 

**new_comment.js**

    import mongoose from 'mongoose';

    const CommentSchema = new mongoose.Schema({
        _id: mongoose.Schema.Types.ObjectId,
        text: String,
        author: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Author'
        }
    }, {
        timestamps: {
            createdAt: 'created_at',
            updatedAt: 'updated_at'
        }
    });
    
    export default mongoose.model('Comment', CommentSchema);

and all of a sudden the following query no longer works

  

    let comments = await Comment.find({ author: authorId })
                .populate("author", 'first_name last_name _id').limit(10);

The error I keep getting back is

    MissingSchemaError: Schema hasn't been registered for model "Author".

This is unbelievable. As you can see above, nothing changed other than using `imports` and `export default` statements.

**Comment by skyme5** [comment]
I think `AuthorSchema` hasn't beed registered when executing `populate`. Maybe you can import AuthorSchema before executing populate? @hashweather

**Comment by hashweather** [comment]
Unfortunately, AuthorSchema was created in a different micro-service  which is responsible for all things author management in a different repo so I can't import it into my own service.

The code works when both services are using CommonJS. It only fails when both services switched to module.

**Comment by hashweather** [comment]
Each service is responsible for a single action so cross importing schemas is not allowed. Each service is responsible for its own models and communication happens only through grpc.

**Comment by skyme5** [comment]
@hashweather how about using the collection names from mongodb in `ref`, for this case setting `ref: authors` might help

**Comment by hashweather** [comment]
I changed ref to `authors` and issue still persists

**Comment by hashweather** [comment]
This is really weird. The funniest part of it is that the authors collection already has over 1k documents in it so how is it possible that its schema has not been created?
