### ISSUE TITLE
Atlas Search is not working when autoEncryption field is added to mongoose.connect

### ISSUE THREAD

**Issue by kart1ka** [Automattic/mongoose#12660]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.1

### Node.js version

16.x

### MongoDB server version

5.x

### Description

Atlas Search was working very well. But it stopped working after I added `autoEncryption` field to `mongoose.connect` options object. It is giving an error (as shown in the screenshot below). It works just fine if I remove `autoEncryption` field.

![err](https://user-images.githubusercontent.com/41051387/200134009-6b74080f-0de3-47c3-bf2e-ed91a1d2d824.png)
The only major change I have made is shown in the screenshot below:

![snap](https://user-images.githubusercontent.com/41051387/200134228-ab32e0ab-3023-4de9-805e-72ac747008df.png)

### Steps to Reproduce

Steps: 
1) Add `autoEncryption` field to `mongoose.connect` options object.
2) Atlas search stops working

Stack Trace:
`
MongoServerError: Unrecognized pipeline stage name: '$search'
    at Connection.onMessage (C:\Users\karti\Desktop\Project-A\project-g\node_modules\mongodb\lib\cmap\connection.js:207:30)
    at MessageStream.<anonymous> (C:\Users\karti\Desktop\Project-A\project-g\node_modules\mongodb\lib\cmap\connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (C:\Users\karti\Desktop\Project-A\project-g\node_modules\mongodb\lib\cmap\message_stream.js:132:20)
    at MessageStream._write (C:\Users\karti\Desktop\Project-A\project-g\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22) {
  ok: new Double(0.0),
  code: new Int32(40324),
  codeName: 'Location40324',
  statusCode: 500,
  [Symbol(errorLabels)]: Set(0) {}
}
`

### Expected Behavior

Atlas Search should work even after implementing client side field level encryption.

**Comment by IslandRhythms** [comment]
https://github.com/Automattic/mongoose/issues/10593
Please provide the whole script. Here is an issue using autoEncryption. See if your script is missing something.

**Comment by kart1ka** [comment]
Below I have attached  before and after (implementing csfle) versions of my script.


Atlas search is working (before implementing csfle)
![server-before](https://user-images.githubusercontent.com/41051387/202642124-1c300f23-2754-435d-a08b-1f4e0de0a0f3.png)

After making the below changes Atlas search stopped working (after implementing csfle)
![server](https://user-images.githubusercontent.com/41051387/202641601-3763fedb-41a1-4ac7-a3b9-ec58580975ea.png)

**Comment by kart1ka** [comment]
Have you found any solution?

**Comment by vkarpov15** [comment]
@kart1ka looks like MongoDB Atlas doesn't currently support querying encrypted data with text search. Here's a screenshot from [MongoDB Atlas Test Search FAQ](https://www.mongodb.com/docs/atlas/atlas-search/faq/#can-i-query-csfle--client-side-field-level-encryption--encrypted-data-):

![image](https://user-images.githubusercontent.com/1620265/205687965-205fc4ae-bb6b-439d-b8fc-7305f09f838b.png)

**Comment by kart1ka** [comment]
Atlas search is working with mongo shell on csfle encrypted data

**Comment by vkarpov15** [comment]
@kart1ka can you please provide a code snippet of how you're querying Atlas search with mongo shell on CSFLE encrypted data? The MongoDB docs seem pretty clear that you can't do that, but if it works in the shell then we may be able to find a way.

**Comment by kart1ka** [comment]
This is the code that i am writing in the mongo shell: 
`db.forms.aggregate([{$search: {index: 'searchForms',text: {query: 'sample ',path: {'wildcard': '*'}}}}])`
It is fetching the document that it is supposed to.
Also, search is working fine on the test search query option that is provided on the atlas website (screenshot is attached below):
![Screenshot 2022-12-20 190919](https://user-images.githubusercontent.com/41051387/208680411-7f9de240-c817-4416-8c89-486b370fb2c2.png)
It is just not working on mongoose.

**Comment by vkarpov15** [comment]
A couple of questions

1) It looks like [the error message you're seeing can be caused by connecting to either a non-Atlas MongoDB cluster, or an Atlas cluster with no text index](https://jira.mongodb.org/browse/SERVER-60474). Can you please confirm that `process.env.DATABASE` lines up with the Atlas cluster you're trying to connect to?

2) I'm unable to repro getting encrypted data results from the MongoDB Cloud search tester. For example, I used the following script to insert a new document:

```javascript
'use strict';

const { ClientEncryption } = require('mongodb-client-encryption');
const base64 = require('uuid-base64');
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  /* Step 1: Connect to MongoDB using autoEncryption */

  // Create a very basic key. You're responsible for making
  // your key secure, don't use this in prod :)
  const arr = [];
  for (let i = 0; i < 96; ++i) {
    arr.push(i);
  }
  const key = Buffer.from(arr);

  const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };
  await mongoose.connect('ATLAS URI HERE', {
    // Configure auto encryption
    autoEncryption: {
      keyVaultNamespace,
      kmsProviders
    }
  });

    /* Step 2: create a key and configure encryption using JSONschema */

  const encryption = new ClientEncryption(mongoose.connection.client, {
      keyVaultNamespace,
      kmsProviders,
    });

  const _key = await encryption.createDataKey('local');

    // CSFLE is defined through JSON schema. Easiest way to set
  // a JSON schema on your collection is via `createCollection()`
  await mongoose.connection.dropCollection('tests').catch(() => {});
  await mongoose.connection.createCollection('tests', {
    validator: {
      $jsonSchema: {
        bsonType: 'object',
        properties: {
          // Automatically encrypt the 'name' property
          name: {
            encrypt: {
              bsonType: 'string',
              keyId: [_key],
              algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic' }
          }
        }
      }
    }
  });

  /* Step 3: Create a Mongoose model that uses the encrypted collection and see encryption in action */

  // 'super secret' will be stored as 'BinData' in the database,
  // if you query using the `mongo` shell.
  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  await Model.create({ name: 'super secret' });

  console.log('Done');
}
```

Searching for "secret" returns no results as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/1620265/212757593-4e33b558-3b04-427d-b6ba-5077da42feb7.png)

Can you please confirm whether you're able to search for the document inserted by the above script?
