### ISSUE TITLE
How to catch MongooseServerSelectionError on express.

### ISSUE THREAD

**Issue by HachikoR** [Automattic/mongoose#12665]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

6.6.3

### Node.js version

16.16.0

### MongoDB version

4.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 21H2

### Issue

I'm writing on express js. Two databases are used: MongoDb and MySQL. MongoDb is connected by mongoose. I need the server to work without database. I mean, if database is available. MySql throw Exception and I catch it. But moongse ignore try{...}catch(e){} and Promise.prototype.catch. I don't know what to do.

My Class:
![1](https://user-images.githubusercontent.com/49492348/200344381-fc6a83c8-f584-468d-b10a-b40087d199c9.png)

Global error handling(express-async-errors):
![2](https://user-images.githubusercontent.com/49492348/200344589-ba4c5b27-cb7f-496c-b184-1917e4b696f5.png)

**Comment by IslandRhythms** [comment]
Add some events to see whats going on
https://mongoosejs.com/docs/connections.html#connection-events

**Comment by HachikoR** [comment]
Thank you!
