### ISSUE TITLE
diffIndexes() with a model with no documents in collection results in TypeError

### ISSUE THREAD

**Issue by rdeavilafloqast** [Automattic/mongoose#12676]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.13.15

### Node.js version

16.18.1

### MongoDB server version

4.4.0

### Use case:
We have a process to create indexes for our schemas instead of relying on `autoIndex`, and occasionally indexes need to be created for newly introduced schemas. As a result, the underlying collections don't actually exist yet. When running `diffIndexes()`( occasionally occurs for dry runs) with a model whose collection does not exist, the following error occurs:

>      Uncaught TypeError: indexes is not iterable
>       at /Users/richarddea/development/projects/mongoose/lib/model.js:1433:27
>       at /Users/richarddea/development/projects/mongoose/lib/model.js:5074:18
>       at processTicksAndRejections (internal/process/task_queues.js:75:11)

This is the result of [this line](https://github.com/Automattic/mongoose/blob/5.x/lib/model.js#L1433), with `indexes` being undefined. The `err` IS defined, and is of the following:

> MongoError: ns does not exist: mongoose_test.my-model
>     at MessageStream.messageHandler (/Users/richarddea/development/projects/mongoose/node_modules/mongodb/lib/cmap/connection.js:299:20)
>     at MessageStream.emit (events.js:315:20)
>     at processIncomingData (/Users/richarddea/development/projects/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
>     at MessageStream._write (/Users/richarddea/development/projects/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
>     at writeOrBuffer (internal/streams/writable.js:358:12)
>     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
>     at Socket.ondata (internal/streams/readable.js:719:22)
>     at Socket.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Socket.Readable.push (internal/streams/readable.js:223:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
>   ok: 0,
>   code: 26,
>   codeName: 'NamespaceNotFound'

### Fix
It'd be best to cleanly return the err, to allow end-users to be able to gracefully handle the it. At the moment, the error is not catchable.

### Steps to Reproduce

Add this integration test to `model.indexes.test.js`
```javascript 
    it('should result in a clean error when calling diffIndexes() against a collection that does not exist', (done) => {
      const MySchema = new Schema({
        name: { type: String, index: true }
      });

      const MyModel = db.model('my-model', MySchema); // This collection should not exist in DB
      MyModel.diffIndexes().then(() => {
        assert.fail('Succeeded when an error should have been thrown');
      }).catch((err) => {
        assert.equal(err.code, 26);
        assert.equal(err.codeName, 'NamespaceNotFound');
        assert.equal(err.name, 'MongoError');
        assert.equal(err.ok, 0);
        done();
      });
    });
```

### Expected Behavior

The error to be catchable, and be the actual `err` instead of a type error because `indexes` is undefined

**Comment by rdeavilafloqast** [comment]
https://github.com/Automattic/mongoose/pull/12677

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: { type: String, index: true }
});



async function run() {
  const db = await mongoose.createConnection('mongodb://localhost:27017');
  const Test = db.model('Test', testSchema);
  Test.diffIndexes().then(() => {
    console.log('executed')
  }).catch((err) => {
    console.log(err)
  })
}

run();
```

**Comment by rdeavilafloqast** [comment]
You probably already have a collection called 'Test' in your DB. Try changing the collection name i.e.

<img width="794" alt="Screen Shot 2022-11-16 at 2 30 27 PM" src="https://user-images.githubusercontent.com/70982763/202315248-6d44a1ba-178f-4ccb-b0f7-9e1bf2509c60.png">

<img width="1192" alt="Screen Shot 2022-11-16 at 2 29 39 PM" src="https://user-images.githubusercontent.com/70982763/202315305-8bd445c1-2470-4567-bf57-02f9793dcfe2.png">

**Comment by IslandRhythms** [comment]
![image](https://user-images.githubusercontent.com/39510674/202505758-aace2c23-084a-4541-a8fa-08dc75ca9701.png)

**Comment by rdeavilafloqast** [comment]
@IslandRhythms 
I opened a PR as a potential fix: https://github.com/Automattic/mongoose/pull/12677/files

If you run the test I added, with `npm test -- -g '(gh-12676)'`, the test will pass.

After commenting out the fix in [model.js](https://github.com/Automattic/mongoose/pull/12677/files#diff-305dbcc98ad8fc959dd0c0be51280893962af34c2d8b18abc871cffc2d80c5f9R1430-R1437), re-running the test fails.

![Screen Shot 2022-11-17 at 11 31 20 AM](https://user-images.githubusercontent.com/70982763/202541648-5e740f5e-7528-4962-96b7-0cddec350fd2.png)

**Comment by rdeavilafloqast** [comment]
Fix merged: https://github.com/Automattic/mongoose/pull/12677
