### ISSUE TITLE
findOne called after findOneAndUpdate on the same id returns the outdated value

### ISSUE THREAD

**Issue by AleCatSS** [Automattic/mongoose#12674]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello everyone,

I need clarification on this: I have a backend providing simple CRUD operations through REST APIs. One of these API is  called 'updateItem' which under the hood uses Mongoose findOneAndUpdate to update n item and return the updated one; the second is a 'getItem' which use Mongoose findOne to return the item.

Now, in the case that an application consuming these API calls in a sequence updateItem then getItem (awaiting both) on the same item (triggering findOneAndUpdate, and findOne) ignoring the updated result from updateItem and instead uses the result from getItem, is it possible that this creates a race condition for which getItem returns the outdated document (the value before the update)?

All calls and methods are awaited.

I know the FE needs to use the return from findOneAndUpdate which will return the updated value and also remove a REST operation optimizing the whole thing but I'm currently investigating an issue and I need to confirm this scenario before taking any action.

I'm asking here because I was not able to find this information reading the docs.

Thank you

**Comment by IslandRhythms** [comment]
```
[options.returnDocument='before'] «String» Has two possible values, 'before' and 'after'. By default, it will return the document before the update was applied.
```
Are you doing `{returnDocument: 'after'}` ?

**Comment by AleCatSS** [comment]
In our case findOneAndUpdate is returning the new document (after update). What I'm trying to understand is if the client calling updateItem (triggering findOneAndUpdate) and then calling getItem (triggering findOne) and using the response from the latter can have an outdated value. I know the client should only call updateItem and use the result from it but I'm investigating the current situation and need to confirm the scenari.

**Comment by IslandRhythms** [comment]
If you're calling updateItem and the changes were saved, when you call getItem it should return the doc with updated values.

**Comment by vkarpov15** [comment]
@AleCatSS "What I'm trying to understand is if the client calling updateItem (triggering findOneAndUpdate) and then calling getItem (triggering findOne) and using the response from the latter can have an outdated value." <-- Unlikely, but possible if you're using a replica set, in which case take a look at [read concerns](https://www.mongodb.com/docs/manual/reference/read-concern/).

Can you provide a more complete repro script that demonstrates what you're seeing?
