### ISSUE TITLE
Getting typings error in $sort stage of pipeline aggregation

### ISSUE THREAD

**Issue by juniorsdj** [Automattic/mongoose#12678]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.3

### Node.js version

v16.17.0

### MongoDB server version

5.0.13

### Typescript version (if applicable)

4.5.4

### Description

```
No overload matches this call.
  Overload 1 of 2, '(pipeline?: PipelineStage[] | undefined, options?: AggregateOptions | undefined, callback?: Callback<ICategoryWithProductsDTO[]> | undefined): Aggregate<...>', gave the following error.
    Argument of type '({ $match: { placeId: ObjectId; isAtivo: boolean; parentId: ObjectId | null; productsCount?: undefined; }; $graphLookup?: undefined; $addFields?: undefined; $lookup?: undefined; $project?: undefined; $sort?: undefined; } | ... 5 more ... | { ...; })[]' is not assignable to parameter of type 'PipelineStage[]'.
      Type '{ $match: { placeId: ObjectId; isAtivo: boolean; parentId: ObjectId | null; productsCount?: undefined; }; $graphLookup?: undefined; $addFields?: undefined; $lookup?: undefined; $project?: undefined; $sort?: undefined; } | ... 5 more ... | { ...; }' is not assignable to type 'PipelineStage'.
        Type '{ $sort: { ordemExibicao: number; }; $match?: undefined; $graphLookup?: undefined; $addFields?: undefined; $lookup?: undefined; $project?: undefined; }' is not assignable to type 'PipelineStage'.
          Type '{ $sort: { ordemExibicao: number; }; $match?: undefined; $graphLookup?: undefined; $addFields?: undefined; $lookup?: undefined; $project?: undefined; }' is not assignable to type 'Sort'.
            Types of property '$sort' are incompatible.
              Type '{ ordemExibicao: number; }' is not assignable to type 'Record<string, 1 | -1 | Meta>'.
                Property 'ordemExibicao' is incompatible with index signature.
                  Type 'number' is not assignable to type '1 | -1 | Meta'.
  Overload 2 of 2, '(pipeline: PipelineStage[], callback?: Callback<ICategoryWithProductsDTO[]> | undefined): Aggregate<ICategoryWithProductsDTO[]>', gave the following error.
    Argument of type '({ $match: { placeId: ObjectId; isAtivo: boolean; parentId: ObjectId | null; productsCount?: undefined; }; $graphLookup?: undefined; $addFields?: undefined; 

```

Type `number` is not assignable to type `1 | -1 | Expression.Meta`.

### Steps to Reproduce

You can try running the script with TS node. It will give you error

```
const pipeline = [
         {
           $match: {},
        },
        {
          $sort: { field: 1},
        },
]
Model.aggregate(pipeline)
```

It's possible fix it if you pass the value as 1 because typescript was expecting the interface `Record<string, 1 | -1 | Expression.Meta>`. However, the typescript was recognized the type as a number.

```
const pipeline = [
         {
           $match: {},
        },
        {
          $sort: { field: 1 as 1},
        },
]
Model.aggregate(pipeline)
```

at this way, mongoose recognized the $sort interface and work as well.

### Expected Behavior

Well it should not throw any error.

### Additional notes

I create [a repository](https://github.com/juniorsdj/mongoose-type-error) with this example of error.

**Comment by almerindo** [comment]
WOW!!

Thanks a lot!

It was happening the same here!
I didn't understand why the typescript was recognizing the type of the sort as a number. 

I solved with as you suggested above. 
```
$sort: { field: 1 as any} 
```

**Comment by lpizzinidev** [comment]
You can prevent the error by specifying the type of the `agg` pipeline:
```
import { PipelineStage } from 'mongoose';

const agg: PipelineStage[] = [
  {
    $sort: {
      count: 1,
    },
  },
];
```

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

const testSchema = new mongoose.Schema({
  field: String
});

const Test = mongoose.model('Test', testSchema);

const pipeline = [
  {
    $match: {},
 },
 {
   $sort: { field: 1},
 },
]
Test.aggregate(pipeline)
```

**Comment by lpizzinidev** [comment]
I think that this issue is related to TypeScript and how it contextually types properties.
You can read more about it in [this](https://stackoverflow.com/questions/56346520/typescript-error-type-number-is-not-assignable-to-type-0-1-2-why-am) StackOverflow QA.
The same problem arises using https://github.com/Automattic/mongoose/blob/a8de1454f8121e1054e0eb88adabee8e972913e5/types/pipelinestage.d.ts#L99 and https://github.com/Automattic/mongoose/blob/a8de1454f8121e1054e0eb88adabee8e972913e5/types/pipelinestage.d.ts#L247
Possible approaches to solve the problem:
1. Cast the `1`:
```
const pipeline = [
  {
    $match: {},
 },
 {
   $sort: { "field": 1 as const },  
 },
];
```
2. Cast the `pipeline` variable to `PipelineStage[]`:
```
const pipeline: mongoose.PipelineStage[] = [
  {
    $match: {},
 },
 {
   $sort: { "field": 1 },  
 },
];
```
3. Pass the pipeline directly to the `aggregate` function:
```
Test.aggregate([
  {
    $match: {},
 },
 {
   $sort: { "field": 1 },  
 },
])
```
Otherwise, we could change the type of the stages and substitute `1 | -1` with `number` and the uncasted approach would work:
```
export interface Sort {
      /** [`$sort` reference](https://docs.mongodb.com/manual/reference/operator/aggregation/sort/) */
      $sort: Record<string, number | Expression.Meta>
    }
```
But In this case, we would lose the value check for all other cases.
What do you think @vkarpov15?

**Comment by vkarpov15** [comment]
This is unfortunately expected behavior. You need to use one of the workarounds in https://github.com/Automattic/mongoose/issues/12678#issuecomment-1354508339 . `1 as const` is probably the easiest workaround.

**Comment by iampato** [comment]
just adding the type fixed it for:
```ts
const pipeline : PipelineStage[] = [
....
];
```

**Comment by guiphc** [comment]
> just adding the type fixed it for:
> 
> ```ts
> const pipeline : PipelineStage[] = [
> ....
> ];
> ```

I could not find the type in mongoose to import, isn't this worked because PipelineStage was not found?

**Comment by iampato** [comment]
> > just adding the type fixed it for:
> > ```ts
> > const pipeline : PipelineStage[] = [
> > ....
> > ];
> > ```
> 
> I could not find the type in mongoose to import, isn't this worked because PipelineStage was not found?

```ts
import { Model, PipelineStage } from 'mongoose';
```

**Comment by vkarpov15** [comment]
@iampato what does your tsconfig look like and what's the error message you're getting? Also what version of Mongoose? I checked and `import { PipelineStage } from 'mongoose'` compiles fine on Mongoose 8.4.0

**Comment by iampato** [comment]
> @iampato what does your tsconfig look like and what's the error message you're getting? Also what version of Mongoose? I checked and `import { PipelineStage } from 'mongoose'` compiles fine on Mongoose 8.4.0

It's @guiphc with the import issue
Mine works perfectly fine
