### ISSUE TITLE
Setting numeric model property to NaN doesn't work properly

### ISSUE THREAD

**Issue by corruptmem** [Automattic/mongoose#1267]
Hi all,

When I set a numeric property to NaN, it appears to not change the property (the getter still returns the old value). However, when I then try to save the changed model, it complains that it can't cast number to NaN.

So for example, if num is a Numeric in the schema and you've loaded a document from the database with it set to 5.

``` javascript
console.log(x.num); //  -> 5
x.num = NaN; 
console.log(x.num); // -> 5
x.save(function(err) { console.log(err); }); // Cast to number failed for value" "NaN" at path 'num'
```

I would expect that saving the NaN back to the database would cause a problem, but I would expect the getter to return a NaN. 

I have added a failing test here demonstrating my problem: https://github.com/corruptmem/mongoose/compare/NaNissue

**Comment by GriffinSauce** [comment]
+1 this just cost me an hour of my life. The behaviour is inconsistent and very opaque.
The value displayed should always match what is actually set.

Does Mongoose cast/validate upon setting? If so setting has failed and the error should occur at that moment.

**Comment by vkarpov15** [comment]
@GriffinSauce which version of mongoose are you using?

**Comment by GriffinSauce** [comment]
@vkarpov15 we're currently using 4.1.0

**Comment by vkarpov15** [comment]
Yeah so mongoose tries to cast when you actually set, but only reports errors that occurred when you try to do `validate()` or `validateSync()`. This is expected behavior - helps make the standard mongoose use case of "set this data to some user-provided data and then try to save it to the db" much simpler and cleaner, all errors get reported when you try to `.save()`.

**Comment by FernandoGOT** [comment]
+1

**Comment by andresgariglio** [comment]
+1 
I'm able to set NaN in MongoDB but I cannot do it in Mongoose:
```
[CastError: Cast to Number failed for value "NaN" at path "some_field"]
```

Is there an ETA for this?

**Comment by vkarpov15** [comment]
No plans to support this currently @andresgariglio .
