### ISSUE TITLE
Inserting default values on update/overwrite

### ISSUE THREAD

**Issue by EtzBetz** [Automattic/mongoose#12687]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.5

### Node.js version

16.17.0

### MongoDB version

5.0.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Issue

Hey there.

I'm currently writing a REST API builder for my application which also uses mongoose.

When implementing PUT, I'm now running into a problem: currently I get the document via `findById()`, then call `overwrite()` and `markModified()` on it and then `save()`. In these steps, really only those values get written into the document, which are given in `overwrite()`, while I would expect default values from the defined schema to be set on attributes, which were not given in the PUT request.

Is this just missing, could we add an option for overwrite, is overwrite thought to be "forceful", do i need the values to be set default mark as changed as well, is there any other option to achieve what I'm currently trying?

Thanks for your help, mongoose really eases a lot of my development.

**Comment by IslandRhythms** [comment]
Provide a Script of what you're doing.

**Comment by EtzBetz** [comment]
This is what I'm doing:
``` javascript
...
  entityToUpdate = await modelToUse.findById(req.params.id)
  await entityToUpdate.overwrite(entityUpdate)
  await markModifiedAttributes(entityToUpdate, req)
  await entityToUpdate.save()
...
```
Now, for example if I have an attribute `disabled`, which has the default attribute `false` in that schema, then if my `entityUpdate` object doesn't include this attribute, the entity will still get overwritten and saved without setting the default value to `disabled`.

**Comment by IslandRhythms** [comment]
Have you tried the applyDefaults function?
https://mongoosejs.com/docs/api.html#model_Model-applyDefaults

**Comment by EtzBetz** [comment]
Oh nice, I thought I searched through all the methods, but seems like I didn't.
From my test now, `applyDefaults` only applies defaults where are a value isn't set, correct?

**Comment by vkarpov15** [comment]
@EtzBetz yes, `applyDefaults()` only applies defaults on properties whose values are either `null` or `undefined`.
