### ISSUE TITLE
Pre 'findOneAndUpdate' hooks not working for array of child schemas

### ISSUE THREAD

**Issue by jcnmsg** [Automattic/mongoose#12694]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

14.16.1

### MongoDB server version

4.11.0

### Description

Having a `childSchema` and using it inside an array on the `mainSchema`  and then calling `findOneAndUpdate` on the model fires the `findOneAndUpdate` pre-hook on the `mainSchema` but not on the `childSchema`.

### Steps to Reproduce

```javascript
const childSchema = new mongoose.Schema({
   name: String
});

const mainSchema = new mongoose.Schema({
   child: [childSchema]
});

mainSchema.pre('findOneAndUpdate', function () {
    console.log('fired.2') // Works
});

childSchema.pre('findOneAndUpdate', function () {
    console.log('fired.1') // Doesn't work
});

const Model = mongoose.model('Model', mainSchema);
const test = new Model();

test.findOneAndUpdate({ _id: id }, {...data}, {}, (err, res) => {})
```

### Expected Behavior

I would expect the console to log `fired.1` and `fired.2` but the pre-hook is only firing on the `mainSchema`. Also tried `save`, `update` and `updateOne` pre-hooks on `childSchema` without luck. Is this intended behavior or a bug?

**Comment by IslandRhythms** [comment]
```javscript
const mongoose = require('mongoose');

const childSchema = new mongoose.Schema({
  name: String
});

const mainSchema = new mongoose.Schema({
  child: [childSchema]
});

mainSchema.pre('findOneAndUpdate', function () {
   console.log('fired.2') // Works
});

childSchema.pre('findOneAndUpdate', function () {
   console.log('fired.1') // Doesn't work
});

const Test = mongoose.model('Test', mainSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const entry = await Test.create({
    child: [{ name: 'Test' }]
  });

  await Test.findOneAndUpdate({_id: entry._id}, {child: [{name: 'Testerson'}, {name: 'Testserson'}]})
}

run();
```

**Comment by vkarpov15** [comment]
This is intentional behavior. We do not fire query middleware on subdocuments. We will add a note about this to the docs.
