### ISSUE TITLE
Proposal to add some tools for documentation consistency

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#12691]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This Issue is a proposal to add the following tools for consistent documentation style (both as raw MD and transformed HTML):
- [`eslint-plugin-markdown`](https://www.npmjs.com/package/eslint-plugin-markdown) to run ESLint against all JS code-blocks inside markdown
- [`markdownlint-cli2`](https://www.npmjs.com/package/markdownlint-cli2) to have consistent markdown files (like eslint but for markdown) using [`markdownlint`](https://www.npmjs.com/package/markdownlint)

Those tools should help to keep the documentation consistent and easy to read.

cc @Uzlopak @vkarpov15

**Comment by vkarpov15** [comment]
I'm supportive of eslint-plugin-markdown. I'm less interested in markdownlint - we'd have to come up with the right set of markdown rules for us, and that seems like it would be a time-consuming endeavor without much upside.

Another tool that I think would be better to have than markdownlint would be a link checker.

**Comment by hasezoey** [comment]
things added so-far:
- `eslint-plugin-markdown` (`lint`): process all code blocks that eslint supports (needs to be manually enabled because of https://github.com/eslint/eslint-plugin-markdown/issues/214)
- `markdownlint-cli2` (`lint-md`): have all markdown files be in consistent style
- `blc` (`docs:check-links`): check documentation for broken links

any other suggestions to maybe add for documentation consistency? otherwise i would close this issue as "completed"
