### ISSUE TITLE
findOneAndUpdate is auto populating unexpectedly

### ISSUE THREAD

**Issue by jamesrollings** [Automattic/mongoose#12701]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

16.17.1

### MongoDB version

4.2

### Operating system

Windows

### Issue

I have a schema property against a collection called CollectionA that looks as follows:

```
PersonnelID: { type: Types.ObjectId, ref: 'Personnel', desc: 'Patient', es_indexed: true, index: true },
```

It references a collection called Personnel.

If I perform a findOneAndUpdate against CollectionA, this PersonnelID is being populated, even though `.populate()` is not being called at any point. This has changed since migrating to v6.

I have compared some of the metadata inside `$__` before upgrading and after, looks like before we have properties such as `wasPopulated: false` and after we have a `populated` object with all of the populated data.

The only options passed to the `findOneAndUpdate` is `{ new : true }`.

As a result, PersonnelID is a `model` rather than an ObjectId, which causes problems further down the line.

Can anyone point to a change in v6 that would result in this being auto populated?

**Comment by vkarpov15** [comment]
Are you using mongoose-autopopulate anywhere?
