### ISSUE TITLE
Unknown/invalid query key returns ALL documents in a collection, instead of 0

### ISSUE THREAD

**Issue by borislemke** [Automattic/mongoose#12708]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.4

### Node.js version

14.19.1

### MongoDB server version

6.0.1 Community

### Typescript version (if applicable)

4.0.5

### Description

Given following model

```
media {
  _id: ObjectID
  folder_id: ObjectId
}
```

When running a query with an invalid query key, ALL documents are matched, e.g:

```
const media = await MediaModel.find({ folder_ud: xxx }); <-- note here that there is a typo "folder_ud" instead of "folder_id"
```

On the above query, the expected result is that mongoose returns 0 results, but instead returns ALL documents of that collection.

We found out about this issue the hard way when we accidentally put a typo in a `deleteMany` query that deleted ALL documents in that collection. This is not the behavior on mongoose versions prior to 6.x, or when using mongosh.

### Steps to Reproduce

```js
const mongoose = require("mongoose");

// Define your model
const mediaSchema = new mongoose.Schema({
  title: mongoose.Schema.Types.String,
});

const MediaModel = mongoose.model("Media", mediaSchema);

(async () => {
  await mongoose.connect("mongodb://localhost:27017/mongoose-test?authSource=admin");

  const mediaTitles = ["media-1", "media-2", "media-3", "media-4", "media-5"];

  for await (const mediaTitle of mediaTitles) {
    await MediaModel.create({ title: mediaTitle });
  }

  const media = await MediaModel.find({ titles: "media-1" }); // note the intentional typo here 'titles' instead of 'title'

  console.log("media", media); // this returns ALL media
  
  // await MediaModel.deleteMany({ titles: "media-1" }); // this will delete ALL documents in the collection
})();
```

### Expected Behavior

- When using mongoose prior to version 6 (e.g v5.13.15), mongoose will return 0 results.
- When using `mongosh` with the equivalent command (e.g `db.media.find({ titles: "media-1" })`) it also returns 0 results

With the above in mind, mongoose 6.x should behave similarly and return 0 results for the query.

**Comment by lpizzinidev** [comment]
In mongoose 6 `strictQuery` is equal to `strict` by default and properties not in the schema are automatically filtered out.

You can change the default behavior either by specifying:
```
mongoose.set('strictQuery', false);
```  
Or adding the option at the query level with 
```
const media = await MediaModel.find({ titles: "media-1" }, null, { strictQuery: false });
```

For more information check the [docs](https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict).

Finally, the option is planned to be brought back to `false` by default in mongoose 7: #11861

**Comment by borislemke** [comment]
@lpizzinidev thanks for getting back to us with the info. Looking at the above thread it seems like this change in v6 has become an issue for many others. Glad that it will be reverted in the next major version.

This has caused loss of data in an entire collection on our Atlas cluster and coincidentally automatic backup was not enabled.

**Comment by vkarpov15** [comment]
@borislemke I'm very sorry for the trouble. As @lpizzinidev mentioned, we're changing this default in Mongoose 7.
