### ISSUE TITLE
Allow setting `debug` on a per-connection basis

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#12700]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Right now you can only enable/disable debugging globally. Would be great to do `conn.set('debug', true)` to just enable debugging for a certain connection.

**Comment by lpizzinidev** [comment]
@vkarpov15 
Hi ✋ I've prepared a working PR addressing this feature request but I saw later that it was already assigned 😅
Can I submit it anyway or should I let @IslandRhythms do the work?

**Comment by IslandRhythms** [comment]
@lpizzinidev if its in a state where its working, go ahead an open a PR. We'll review it and if its up to snuff we'll merge it. If not, I'll work on it.

**Comment by vkarpov15** [comment]
@lpizzinidev feel free to submit your PR :+1:
