### ISSUE TITLE
getting error while accessing mongo URI inside server, working fine in local system

### ISSUE THREAD

**Issue by imkumawat** [Automattic/mongoose#12713]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

18.12.1

### MongoDB version

4.2.0

### Operating system

Linux

### Issue

Mongo is giving error:
MongoParseError: URI Malformed, cannot be parsed.

the same uri is workign when I run my code in my laptop, when I pushed the code into aws server, mongo started giving error.

**Comment by IslandRhythms** [comment]
Can you provide an example script of what you are doing?

**Comment by imkumawat** [comment]
Here is code to fetch Mongo secrets from AWS Secret Manager and pass to Mongo connection and this code is working for other projects well. For my project its working before but when I pushed some changes in server running on AWS ECS, its starts giving error for invalid URI. Working when I hard coded the Mongo connection string, 

```
 let mongodbURL;
  const secretKeys = JSON.parse(
    await secretManager.getSecrets(config.db.secretId)
  );
  mongodbURL =
    "mongodb+srv://" +
    secretKeys["username"] +
    ":" +
    secretKeys["password"] +
    "@" +
    secretKeys["host"] +
    "/" +
    secretKeys["dbname"] +
    "?retryWrites=true&w=majority";

  mongoose
    .connect(mongodbURL, { useUnifiedTopology: true, useNewUrlParser: true })
    .then(async () => {
      logger.info("Connected to MongoDB");
      server = app.listen(config.port, () => {
        logger.info(`Listening to port ${config.port}`);
      });
    });
```
