### ISSUE TITLE
Populate feild then find

### ISSUE THREAD

**Issue by samislam** [Automattic/mongoose#12724]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I have the following tables:

![image](https://user-images.githubusercontent.com/59496975/204075205-5aef532d-8d57-4e58-a75d-0f8529b8a84c.png)

And I want to make a query, and filter inside the subscriptions' collection only for all the users who have the role "client".

So the query should return:
```js
[
  { 
     id: '1',
     name: 'Ahmad',
     role: 'client',
     balance: 0
  }
]
```

How to filter in MongoDB for this?

The only solution, unfortunately, is to use `.aggregate()` with `$lookup`, then `$match`, then `$unwind`, a repetitive pattern that always happen for this scenario.

### Motivation

Here's a similar problem that was solved using aggregate:
https://stackoverflow.com/a/74580085/18387350

it has many drawbacks, and it's not clean and makes the code long.

### Example

Instead of making `Subscription.find().populate()`, let us do the opposite `Subscription.populate().find()`.

```js
Subscription.populate('client').find({
   'client.branch': 'BRANCH_ID'
})
```

* this should mean, populate first, then filter.

**Comment by Uzlopak** [comment]
I am -1 for this proposal. 

In a nosql database you would not normalize data that strict. The high performance of a mongodb is realized by data duplication. So in your case you would either enrich the subscriptions collection with the client role, or create a third collection with the combinations you need.

If you want to normalize the data to the extreme and use the mongodb like a sql-database, then use a sql database instead forcing sql-principles on a nosql-database.

**Comment by Uzlopak** [comment]
Also short reminder what a population on mongoose is. When populating a field mongoose loads the data from the database collection and stores it in memory and replaces the corresponding fields of the parent with the documents. 

So this means with your proposol to do first populate then find, that you have basically load both, the parent collection and the referenced collection, and then filter. This obviously wont work for big collections.

If you want to achive later some kind of pagination, you would be forced to definetly load the whole collections, as sorting would be only possible in nodejs. 

It is one of the principles of working with databases to let the database do the work and not the logic. 

I strongly recommend to read about organizing data in nosql databases.

**Comment by samislam** [comment]
> So this means with your proposol to do first populate then find, that you have basically load both, the parent collection and the referenced collection, and then filter. This obviously wont work for big collections.

`Model.populate().find()`, or any other api, ex: `Model.populateAndFilter()` will execute an aggregation underground which should look similar to this:
```js
[
             {
               $lookup: { // similar to .populate() in mongoose
                from: 'payees', // the other collection name
                localField: 'payee', // the field referencing the other collection in the curent collection
                foreignField: '_id', // the name of the column where the cell in the current collection can be found in the other collection
                as: 'payee' // the field you want to place the db response in. this will overwrite payee id with the actual document in the response (it only writes to the response, not on the database, no worries)
             },
             { // this is where you'll place your filter object you used to place inside .find()
               $match: {
                 isCancelled: false,
                 dueDate: { $gte: sinceDate, $lte: tillDate }
                 'payee.branch': 'YOUR_FILTER', // this is how you access the actual object from the other collection after population, using the dot notation but inside a string.
               }
             },
             { // this is similar to .select()
               $project: {_id: 1, serial: 1, dueDate: 1, value: 1, payee: 1}
             },
             {
               $unwind: '$payee' // this picks the only object in the field payee: [ { payeeDoc } ] --> { payeeDoc }
             }
]
```

**Comment by Uzlopak** [comment]
Well i strongly doubt that this is fast. You will complain in the future that your operation is slow. Than you either want to change to a SQL-Server or you want to keep mongo but need to invest time to restructure the data to improve the performance.

**Comment by samislam** [comment]
@Uzlopak, well, I am now totally convinced that I will have to restructure the data models.
I'm not sure though if we should consider adding this feature (somehow) into mongoose, so I'll wait for the maintainer to post his opinion regarding this.

**Comment by vkarpov15** [comment]
@samislam as you mentioned in the first post, there's no way to do this without aggregation. And Mongoose populate doesn't use aggregation, we use `find()`.

The approach we recommend is to embed the `role` property in the subscription. So instead of `Subscription.find().populate()`, you would just find subscriptions by their `role` property.

**Comment by dara-dessert440** [comment]
I understood the response https://karma-runner9.github.io/YNCc0ttp9h4bBJd4hw/
