### ISSUE TITLE
Subdocument is not saving automatically.

### ISSUE THREAD

**Issue by dayo05** [Automattic/mongoose#12729]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.3

### Node.js version

19.0.0

### MongoDB version

6.0.3

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.0.1

### Issue

I'm new to typescript and mongoose and mongo DB so I can have some mistakes :(

I've created the document with subdocument:
```ts
interface IBadge {
  badgeId: number
}
interface IUser {
  badges: IBadge[]
}

const BadgeModel = model<IBadge>('badge', new Schema<IBadge>({
  badgeId: String
}))
const UserModel = model<IUser>('user', new Schema<IUser>({
  badges: [{ type: Schema.Types.ObjectId, ref: 'badge' }],
}))
```
I want to save IBadge interface with IUser interface.
I accessed the database with this code.
```ts
async function setUserData(data: IUser) {
  await new UserModel(data).save()
}
export async function getDataOfUserId(id: string, existThen: (id: string, data: IUser) => Promise<void>) {
  await existThen(id, <IUser>await UserModel.findOne({'id': id}).exec())
}
export async function updateUserDataId(id: string, data: IUser) {
  await setUserData(data)
}

await getDataOfUserId(user, async (id, data) => {
      data.badges.push(getBadgeModel({
        badgeId: 12
      }))
      await updateUserDataId(id, data)
    })
```
It saves IUser interface(My interface contains other data but I've removed it for explanation) but IBadge interface is not saved.

This is the output when I call `db.users.find()` and `db.badges.find()` in the mongosh. 
```
[
  {
    _id: ObjectId("638359e04decdc54e8b08fbc"),
    badges: [ ObjectId("63835ee68ad0e70279c7c0d9") ],
    __v: 1
  }
]
```
```
```

Thanks for your help! :D

**Comment by IslandRhythms** [comment]
Please include the code for `getBadgeModel()`

**Comment by dayo05** [comment]
I've solve my question, just minor mistake.

I should change
```ts
const UserModel = model<IUser>('user', new Schema<IUser>({
  badges: [{ type: Schema.Types.ObjectId, ref: 'badge' }],
}))
```
to 
```ts
const UserModel = model<IUser>('user', new Schema<IUser>({
  badges: [{ type: BadgeSchema, ref: 'badge' }],
}))
```
Thanks for response!
