### ISSUE TITLE
Mongoose's npm package bundles 6.6.1 package into current version

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#12725]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

>6.6.3

### Node.js version

none

### MongoDB server version

none

### Typescript version (if applicable)

none

### Description

I have noticed that since mongoose 6.6.3, there is a extra `6.6.1` `tgz` bundle included in the shipped package, about doubling the size of the package without being of any (to me visible) use

![screenshot of 6.6.3](https://user-images.githubusercontent.com/10911626/204097307-86ce9264-c79f-4cca-a448-356fa2f9fbdd.png)

### Steps to Reproduce

look at:
- https://unpkg.com/browse/mongoose@6.6.3/
- https://unpkg.com/browse/mongoose@6.7.0/
- https://unpkg.com/browse/mongoose@6.7.3/

### Expected Behavior

no extra bundled package

**Comment by Uzlopak** [comment]
I assume @vkarpov15 packed locally 6.6.1 for testing and forget to delete it.
We should extend .npmignore to cover .tgz files.

**Comment by vkarpov15** [comment]
I'm very sorry about this one. I had a tarball that I was using for testing from `npm pack` that got published. Thanks for the fix.
