### ISSUE TITLE
Check if any error is instanceof one of Mongoose errors

### ISSUE THREAD

**Issue by bacloud23** [Automattic/mongoose#12732]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.3

### Node.js version

14

### MongoDB version

5

### Operating system

Linux

### Issue

Is there a way to know if an error is instance of one of the different mongoose errors ?

I can go one by one like `err instanceof mongoose.Error.CastError` etc, but is there a more generic way ?

Some solutions have this kind of method like in axios. `isAxiosError`

Thanks a lot.

**Comment by Uzlopak** [comment]
All MongooseErrors extend from MongooseError. So you should be able to do `err instanceof mongoose.Error`
