### ISSUE TITLE
Pushing items to an array after emptying the array results in $push instead of $set operator in MongoDB query

### ISSUE THREAD

**Issue by aguecida** [Automattic/mongoose#12747]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.10.9

### Node.js version

16.13.1

### MongoDB server version

5.0.6

### Description

I have an array property that in a certain point in my application, I empty before adding new elements to it. However I started noticing that after saving the document, I was seeing elements in the array that were there before I assigned the empty array. After enabling Mongoose debugging, I was able to determine that a `$push` operator was being used instead of a `$set`. This causes an issue when the array previously had elements in it, resulting in the array containing both the elements that were previously in the array as well as the new elements that were just pushed to it.

Note that I am using the document [save](https://mongoosejs.com/docs/documents.html#updating-using-save) method to update the document in this scenario.

It seems that this can be worked around on my end by replacing my usages of `push` with a `concat` to achieve the same behaviour, but instead by creating a new array each time I add an element to it, but this doesn't seem ideal.

### Steps to Reproduce

I have a "game" schema defined with a top-level property like so:

```js
...
abilityRound: {
    inProgress: { type: Boolean, default: false },
    current: Number,
    previous: Number,
    passed: [Number],
    playedActionCards: [{
        name: String,
        playerId: Schema.Types.ObjectId
    }]
},
...
```

When I first empty the `abilityRound.passed` array

```js
game.abilityRound.passed = [];
```

and shortly after push some elements to it

```js
game.abilityRound.passed(nextPlayer.number);
```

it results in a `$push` operator being used in the MongoDB query rather than a `$set` operator.

Here is a sample debug output taken. Notice how most properties are being `$set` but the `abilityRound.passed` property is using a `$push`.

```
Mongoose: games.updateOne({ _id: ObjectId("62cc8a58a6ef2b0017669b41"), __v: 1191 }, { '$set': { 'abilityRound.current': 6, 'abilityRound.playedActionCards': [], 'abilityRound.previous': 2, abilityRoundQueue: [ { inProgress: true, passed: [], _id: ObjectId("6388e6918ad9e031f88be0ce"), step: 'Second Agenda Revealed', timing: 'after', current: 3, previous: 2, playedActionCards: [ { _id: ObjectId("6388e6918ad9e031f88be0cd"), name: 'Leadership Rider', playerId: ObjectId("62cc8a59a6ef2b0017669c9b") } ] } ], step: 'Action Card Played', timing: 'when', updatedAt: 1669916308 }, '$push': { 'abilityRound.passed': { '$each': [ 3, 4, 5 ] } }, '$inc': { __v: 1 }}, { session: undefined })
```

### Expected Behavior

I would expect that when you assign an empty array to a document property and subsequently push new elements to it, Mongoose would use the `$set` operator rather than the `$push` operator so that any elements that were previously inside the array would get overwritten.

**Comment by vkarpov15** [comment]
The following script works as expected in Mongoose 5.10.9 and 6.7.5:

```javascript
'use strict';
  
const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  const Test = mongoose.model('Test', new mongoose.Schema({
    passed: [Number]
  }));

  const { _id } = await Test.create({ passed: [1, 2, 3] });
  let doc = await Test.findById(_id);

  doc.passed = [];
  doc.passed.push(4);
  await doc.save();

  console.log(await Test.findById(_id));
}
```

Output:

```
$ node gh-12747.js 
Mongoose: tests.insertOne({ passed: [ 1, 2, 3 ], _id: new ObjectId("638d50ce43553a33fb41fc52"), __v: 0}, { session: null })
Mongoose: tests.findOne({ _id: new ObjectId("638d50ce43553a33fb41fc52") }, { projection: {} })
Mongoose: tests.updateOne({ _id: new ObjectId("638d50ce43553a33fb41fc52"), __v: 0 }, { '$set': { passed: [ 4 ] }, '$inc': { __v: 1 } }, { session: null })
Mongoose: tests.findOne({ _id: new ObjectId("638d50ce43553a33fb41fc52") }, { projection: {} })
{
  _id: new ObjectId("638d50ce43553a33fb41fc52"),
  passed: [ 4 ],
  __v: 1
}
```
