### ISSUE TITLE
InferSchemaType: Allow null for optional fields

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#12748]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.5

### Node.js version

16.17.1

### MongoDB server version

4.4

### Description

Currently optional fields in schemas accept either the field type or undefined. Can we change this to also accept `null`? AFAIK `null` should be treated the same as `undefined` in this case, and it makes the types more usable. In our codebase, we generally treat `null` and `undefined` the same in our types, unless we're forced to do otherwise due to explicit behavior difference such as https://mongoosejs.com/docs/migrating_to_6.html#removed-omitundefined.

i.e. we are using

```
type Maybe<T> = T | null | undefined
```

### Steps to Reproduce

If I define the following schema:
```
const ExampleSchema = new Schema({
  example: String
});
type ExampleSchemaFields = InferSchemaType<typeof ExampleSchema>;
```
It infers the following type:
```
// type ExampleSchemaFields = {
//   example?: string | undefined;
// }
```

Can we change this to `example?: string | null | undefined`?

**Comment by JavaScriptBach** [comment]
@vkarpov15 I'm happy to help implement this change if you can give me a pointer of where to edit. I tried looking in https://github.com/Automattic/mongoose/blob/master/types/inferschematype.d.ts but couldn't find how we type optional fields.

**Comment by philiparvidsson** [comment]
Yes, this is causing bugs for us. null is entirely different from undefined (trivially, null can be understood as intentionally set to nothing)
