### ISSUE TITLE
Documentation should include a listing of all strings passable to `.pre` and `.post`

### ISSUE THREAD

**Issue by larasodjati** [Automattic/mongoose#12743]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

There should be a section in the [middleware page](https://github.com/Automattic/mongoose/blob/master/docs/middleware.md) that lists all the possible strings that can be passed to `Schema.pre` or `Schema.post`. 

### Motivation

I was reading the mongoose documentation while I was working on adding pre-save hooks to my application. There are a lot of hook types (strings) that can be provided as the first argument to `Schema.pre` or `Schema.post`. I had a very hard time navigating the documentation because there is no single place where all the possible inputs are listed.

**Comment by hasezoey** [comment]
i dont know if *all* are listed, but many are listed already in the section at [ Types of Middleware ](https://mongoosejs.com/docs/middleware.html#types-of-middleware), but it may not be clear that those lists are what is used for the first parameter in `pre` and `post`

**Comment by larasodjati** [comment]
Thanks for sharing that documentation page, I hadn't seen it before.

Nonetheless, the problem that still exists is it’s hard to find the set of possible inputs to `Schema.prototype.pre` and `Schema.prototype.post`. Another problem is all the possible strings are not located in the same section; they are spread throughout the middleware guide. Finally, the middleware guide appears disorganized if you’re trying to find the list of possible strings. We alternate between `pre-` and `post-` hooks throughout; there should be a place where all `pre-` hooks are together, and a corresponding place for `post-` hooks.

I suggest that we could have the exhaustive list and detailed documentation somewhere in the API section, and then link to that from several places throughout the docs where middleware or hooks are mentioned. Specifically, I suggest there should be a list of possible strings for `Schema.prototype.pre` and `Schema.prototype.post` on this page https://mongoosejs.com/docs/api/schema.html#schema_Schema-post. Although, there might be other good places for this information; I’m open to your suggestions & looking forward to your response!
