### ISSUE TITLE
document.subdocumentarray.id(id_var).remove() returns null when it use to return the document that was removed

### ISSUE THREAD

**Issue by amit777** [Automattic/mongoose#12766]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.5

### Node.js version

16.17.1

### MongoDB server version

5.0

### Description

I'm not sure when this happened as we have had a bunch of infrastructure and code changes, but we noticed that `.remove()` seems to not return an object anymore.  It's not a huge issue for us since we have a workaround, but just wanted to file a ticket in case it's a bug:

### Steps to Reproduce

```js
// subdocuments is an array of other mongoose models.
let id_var = <_id of subdocument we are trying to delete>
let toDelete = domain.subdocuments.id(id_var).remove();

// toDelete use to be an object.. now it's null. 
```

### Expected Behavior

the `.remove()` on the subdocument should return the document that is removed.

**Comment by IslandRhythms** [comment]
From your script, you may be calling remove on the virtual as opposed to the objectid. Try that
```javascript
const mongoose = require('mongoose');

const subSchema = new mongoose.Schema({
  model: {}
});

const testSchema = new mongoose.Schema({
  name: String,
  subdocuments: [{ type: subSchema }]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test',
    subdocuments: [{ model: Test }]
  });
  const entry = await Test.findOne();
  console.log(entry)
  console.log(entry.subdocuments[0]._id)
  console.log(await entry.subdocuments[0].remove());
  const res = await Test.findOne();
  console.log(res.subdocuments);
  console.log(res.subdocuments[0])
}
run();
```
