### ISSUE TITLE
Reuse subschema contains refPath

### ISSUE THREAD

**Issue by conduongtong** [Automattic/mongoose#12773]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.4

### Node.js version

18.12.1

### MongoDB version

6.0.2

### Operating system

Windows

### Issue

I have schemas like this:
```js
const childSchema = new Schema({
    title: String,
    type: { type: String, enum: ['Test'] },
    test: { type: Schema.Types.ObjectId, refPath: 'child.type' },
  });
  const parentSchema = new Schema({ title: String, child: childSchema });
```
It works.
But I want to use childSchema on another schema like this:
```js
  const subAnotherSchema = new Schema({ title: String, child: childSchema });
  const anotherSchema = new Schema({ title: String, subAnother: subAnotherSchema });
```
Because refPath nested another schema so refPath now wrong.
How can I reuse childSchema?

**Comment by vkarpov15** [comment]
Use `ref` function instead of `refPath`. As you saw, `refPath` is relative to the top-level document, which makes it tricky to reuse schemas. If you use `ref: function() { return this.type; }`, that's relative to the subdocument, which is better for schema reuse.
