### ISSUE TITLE
Infer discriminator models

### ISSUE THREAD

**Issue by hornta** [Automattic/mongoose#12786]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm having a hard time understanding how to make TypeScript know that my base model has different models depending on the discriminator key. Is it possible to have them be inferred of the `InferSchemaType` type?

**Comment by vkarpov15** [comment]
Can you please provide some code samples? Hard to tell what you're trying to accomplish.
