### ISSUE TITLE
Creates a find query: gets a list of documents that match filter

### ISSUE THREAD

**Issue by Abbhiishek** [Automattic/mongoose#12783]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.0

### Node.js version

16.16.0

### MongoDB version

4.12.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

```js
 if (method === "GET") {
        // get all the event from eventschemas ?
        const events = await EventSchema.find({});
        res.status(200).json(events);

    }
```

The error :

  Each member of the union type '{ <ResultDoc = any>(filter: FilterQuery<any>, projection?: ProjectionType<any>, options?: QueryOptions<any>, callback?: Callback<ResultDoc[]>): Query<...>; <ResultDoc = any>(filter: FilterQuery<...>, projection?: ProjectionType<...>, callback?: Callback<...>): Query<...>; <ResultDoc = any>(filter: FilterQuery<...>, ...' has signatures, but none of those signatures are compatible with each other.ts(2349)

**Comment by IslandRhythms** [comment]
Is `EventSchema` the name of your model? That's very confusing

**Comment by Abbhiishek** [comment]
The issue is fixed 
Thanks for having a look 👍🏻 

Made some changes in `tsconfig.js` file

**Comment by Boboss74** [comment]
@Abbhiishek what were the changes ?
