### ISSUE TITLE
DeprecationWarning: Mongoose

### ISSUE THREAD

**Issue by vanna-code** [Automattic/mongoose#12795]
### Prerequisites

- [ ] I have written a descriptive issue title

### Mongoose version

6.6.7

### Node.js version

18.x

### MongoDB version

5.0.14

### Issue

DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.

**Comment by IslandRhythms** [comment]
What problem are you experiencing?
