### ISSUE TITLE
findOneAndUpdate() doesn't remove fields set to `undefined`

### ISSUE THREAD

**Issue by calculuschild** [Automattic/mongoose#12794]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.0

### Node.js version

16.11.0

### MongoDB version

4.4.18

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

When using `find()` and then `save()` I am able to set an object field to `undefined` to remove that field from the document (I understand Mongoose performs an `$unset` in this case.

However, we have converted some of our operations to `findOneAndUpdate()`. Unfortunately, this behavior doesn't seem to apply in this case. `undefined` fields are simply unchanged by the update and remain in the document.

The section of code is:

```
article.secondaryID = undefined;
article.oldTitle = undefined;
savedArticle = await articlesModel.findOneAndUpdate({ _id: article._id }, article, {
	returnOriginal : false
}).catch(saveError);
```

All the other fields update correctly; just these two fields are not being unset as expected. `article` is a standard JS object at this point.

Are we doing something wrong, is this a bug, or is this an intended difference between `save()` and `findOneAndUpdate()`?

**Comment by JavaScriptBach** [comment]
This is expected behavior: https://mongoosejs.com/docs/migrating_to_6.html#removed-omitundefined

Although personally I think it's a questionable decision and it significantly increased the cost of migrating my company's codebase to Mongoose 6.

**Comment by calculuschild** [comment]
Huh. It's that very page you linked that tells us `undefined` *should* work:

> In Mongoose 6.x... **Mongoose will always strip out undefined keys.**

And yet... rather than stripping the field from the document, setting a field to `undefined` seems to be totally ignored.

**Comment by JavaScriptBach** [comment]
It is stripping the field from your query before passing it to the MongoDB node driver. So if you want the field cleared in the database, you need to set it to `null`.

**Comment by calculuschild** [comment]
> It is stripping the field **from your query** before passing it to the MongoDB node driver.

Ah. This seems like an issue with the docs then that it is easy to interpret the opposite behavior. I would propose "from the query" be added to the documentation. Especially given `document.save()` doesn't do this.

> So if you want the field cleared in the database, you need to set it to `null`.

Will this actually remove the field as we want, or just set it's value to `null`?

**Comment by Noushad-web** [comment]
Setting null works for me.
