### ISSUE TITLE
Indexed full text search not working or throwing incorrect error using `.find`

### ISSUE THREAD

**Issue by bramvbilsen** [Automattic/mongoose#12793]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.0

### Node.js version

18.12.1

### MongoDB server version

5.0.5

### Typescript version (if applicable)

4.8.4

### Description

Trying to run a full text search query as follows
```js
const res = await Collection.find({
  $text: {
      $search: "math",
  },
});
```
Results in the following output:
```
MongoServerError: Missing expected field "$search"
```
Which I believe is unexpected as the `$text` object does have a `$search` field. Also, the query using the same filter object does get executed correctly using `mongosh`.  

The same query does however work using aggregates as follows:
```js
const res = await Collection.aggregate([
    {
        $match: {
           $text: {
                $search: "math",
            },
        },
    },
]);
```
The same documents that are returned in the `mongosh` environment are queried.

To ensure this is not an index problem, I doubled checked whether a text index is created correctly. The code for this is as follows:
```js
schema.index(
    { title: "text" },
    {
        name: "text_search",
    },
);
```
This index appears to be created successfully as it shows up in MongoDB Atlas and via `mongosh`.

### Steps to Reproduce

1. Create a collection with a text index:
```js
schema.index(
    { field: "text" },
);
```

2. Query this collection using Mongo full text search capabilities:
```js
const res = await Collection.find({
  $text: {
      $search: "math",
  },
});
```

### Expected Behavior

I expect the query to return the same data as was returned in the `mongosh` environment. I.e., the documents that satisfy the full text search query.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

testSchema.index({ name: "text" });

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const res = await mongoose.connection.collection('tests').find({ $text: { $search: "Test Testerson" }}).forEach((item) => console.log(item));
  // console.log(res);
}

run();
```

**Comment by fyyyyy** [comment]
```js
>   const res = await mongoose.connection.collection('tests').find({ $text: { $search: "Test Testerson" }}).forEach((item) 
```
This works because you supply the full string "Test Testerson", but it doesnt work when you supply "Test" which is what we expect from the docs.

**Comment by vkarpov15** [comment]
@fyyyyy I'm unable to repro, following script still prints out the "Test Testerson" document:

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  title: String,
  name: String
});

testSchema.index({title: "text"}, { name: "text_search" });


async function run() {
  await mongoose.connect('mongodb://localhost:27017/mongoose_test');
  await mongoose.connection.dropDatabase();

  const Test = mongoose.model('Test', testSchema);
  await Test.createCollection();

  await Test.create({
    title: 'Test Testerson',
    name: 'Test Testerson'
  });

  const res = await mongoose.connection.collection('tests').find({ $text: { $search: "Test" }}).forEach((item) => console.log(item));
  // console.log(res);
}

run();

```
