### ISSUE TITLE
Unable to add properties to a schema after it has been initialized (trying to use Schema.add method as per docs)

### ISSUE THREAD

**Issue by zubozrout** [Automattic/mongoose#12799]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.0

### Node.js version

18.12.1

### MongoDB server version

6.0.3

### Description

Hi,
(likely) since the latest version I am having hard time merging two Schemas. Basically an example like this no longer works for me:

```
    const testSchema = mongoose.Schema();
    testSchema.add({ test: String });
```

The Schema's obj is undefined if I do this:
```
testSchema Schema {
   obj: undefined,
   ...
```

But it did work for me before and it is still mentioned here in the docs:
https://mongoosejs.com/docs/api.html#schema_Schema-add

Can someone please confirm this is really the case?

I need to edit the original schema which is initialized right upon my app launch and then extend it based on a config file once that gets loaded.

Btw, dirty way doesn't work either - I can in theory do `testSchema.obj = { ...testSchema.obj, test: String }`, but even if I can then see it in the Schema it doesn't seem to work (I can't save anything with that key to the DB, it is just skipped).

Thank you very much.

### Steps to Reproduce

Run this code:
```
    const testSchema = mongoose.Schema();
    testSchema.add({ test: String });
```
and if you print it's `.obj` to the console it will be undefined (= empty).

**Comment by IslandRhythms** [comment]
The `obj` is `undefined` but the `path` is added in the `path` property. Strange.
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema();

testSchema.add({test: String});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({ name: 'Test testerson'});
  console.log(await Test.findOne())
}

run();
```

```output
node ./12799.js
(node:19216) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
{ _id: new ObjectId("639cb9f7c12489154e2b633c"), __v: 0 }
```

**Comment by lpizzinidev** [comment]
@IslandRhythms 

Isn't the problem related to the fact that the `test` attribute is not added to the `.obj` of the `Test` document?
```
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema();

testSchema.add({test: String});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = new Test({ test: 'Test'});
  console.log(doc.obj); // undefined, but should return { test: 'Test'}
}

run();
```

Correct me if I misunderstood something

**Comment by vkarpov15** [comment]
@zubozrout why are you using `.obj` ?

**Comment by zubozrout** [comment]
> @zubozrout why are you using `.obj` ?

I am usually not. This was just what I observed when trying to debug why I can't save anything with a dynamically added property in a schema. That being said I can save anything that's in the schema on load but not anything that's added later on.

However, I did originally say "(likely) since the latest version". I've tried a few versions back and it was the same. Also, it seems that if I restart the app and load it again without clearing cache or anything it will work just fine and I can save these previously initialized "dynamic" properties - could be the reason why I didn't notice earlier and only now when I was testing something. So I wonder if I am perhaps missing something there ... if another trigger is needed to make mongoose aware of it (but I didn't find anything useful when Googling this) or if it is indeed a Mongoose issue.

**Comment by vkarpov15** [comment]
Our [docs on `.obj`](https://mongoosejs.com/docs/api/schema.html#schema_Schema-obj) say that `obj` contains "The original object passed to the schema constructor". So this behavior is correct as far as the docs are concerned. We can consider changing it, but hard to justify changing it without a good reason.

Have you tried using `schema.paths` instead of `schema.obj` ? That's usually more helpful if you're looking at properties that are added later.
