### ISSUE TITLE
Database Pool - Long lived Zombie Connections

### ISSUE THREAD

**Issue by syedahmedhaidershah** [Automattic/mongoose#12800]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.2.1

### Node.js version

14.x

### MongoDB server version

5.x

### Description

Originally we had a codebase deployed to AWS Lambda (a serverless environment).

Since we weren't able to easily integrate a Database proxy easily with MongoDB Atlas, we faced the ye olde' Zombie connections issue in a serverless environment, where we get upto 3x number of users that we have.

**_We resolved it by moving to Autoscaling EC2 (Linux servers)_**.

Effectively we had  10 servers running with a DB pool configured for minimum 5 and maximum 50 connections.

In under 3 hours , we started facing the seeing rapidly increasing connections and for some reason not being reused as Mongoose should. We did not have application layer error logs.

**Infra specs**:
1. T2.2xlarge machines (Ubuntu 22.x, configured for maximum throughput)
2. Scales up on 2% CPU utilization with a 300s startup time

**Runtime specs**:
1. NGINX (Configured for maximum throughput)
2. PM2 hosted Node.JS Application (Clustered environment on an 8-core machine).

Where we expected less than 10,000 active connections our DB connections surged way over 150k.

Is this a behaviour Mongoose experiences at scale?

PS We had about 20k active users, that means about 2 Queries in 1 user interaction - second.

We could map that upto 50k queries at most per second. judged from our UX and patterns.

### Steps to Reproduce

<ul>
<li>
Launch a Node JS Application in an autoscaling group with the configuration:
<ul>
<li>Ubuntu 22.0 image<li>
<li>Execute a load test with throughput with the following metrics / ops per seconds:</li>

![image](https://user-images.githubusercontent.com/43408958/207643981-886a4bac-6d19-471c-b6dc-c2d3c18e5dbb.png)

We had managed to go over 100,K connections
![image](https://user-images.githubusercontent.com/43408958/207644094-a11295cd-b3e7-4b33-ab01-883bd6983d0d.png)

**Comment by vkarpov15** [comment]
This isn't a behavior that Mongoose experiences at scale, or at least not that we know of. But, without code samples, this will be impossible to repro.

Can you please show what the code you're using to connect to MongoDB using Mongoose looks like? Like what options are you passing, are you using `mongoose.connect()` or `createConnection()`?

Also, you mentioned an autoscaling group. Did the number of servers increase when you saw the connection spike?
