### ISSUE TITLE
MongoNetworkTimeoutError: connection 11 to 127.0.0.1:27017 timed out

### ISSUE THREAD

**Issue by roeurbnavy** [Automattic/mongoose#12819]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.0

### Node.js version

14.19.3

### MongoDB version

5.0.5

### Operating system

None

### Issue

Hi, I'm base on `Meteorjs` with `Mongoose`, I tried to query(aggregate) data (500000+ records) at the same time (Users 10+) and  hen got the error: 
![MwrSl](https://user-images.githubusercontent.com/20157836/208801810-97458928-124d-40ea-8434-c12b4b4dbc2f.png)
Here my connection:
```js
import { Meteor } from 'meteor/meteor'
import Mongoose from 'mongoose'

let HOST = '127.0.0.1'
const DB_NAME = 'myDb'
const PORT = 27017

var mongoUrl = `mongodb://${HOST}:${PORT}/${DB_NAME}`

Mongoose.connect(mongoUrl, {
  maxPoolSize: 10,
  socketTimeoutMS: 45000,
  serverSelectionTimeoutMS: 5000,
  autoIndex: false,
  family: 4,
}).catch((err) => console.log('connect error', err.reason))

Mongoose.Promise = global.Promise

var db = Mongoose.connection

db.on('error', (err) => {
  console.log('Mongoose default connect error' + err)
})
db.on('reconnected', () => {
  console.log('Connection Reestablished')
})
db.on('disconnected', () => {
  console.log('Connection Disconnected')
})
```
What should I do?

**Comment by IslandRhythms** [comment]
Are you able to connect locally?

**Comment by roeurbnavy** [comment]
I connected on locally.

**Comment by vkarpov15** [comment]
@roeurbnavy slow trains problem most likely: https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs . Small pool size + lots of slow queries in parallel = this error. I'd recommend speeding up your query (using indexes and/or by replacing aggregations with queries) and increasing `maxPoolSize`.

**Comment by roeurbnavy** [comment]
@vkarpov15 Sorry, How many should we increase `maxPoolSize` ?

**Comment by vkarpov15** [comment]
How many parallel queries do you expect to see? And how many app instances are you running in parallel?

**Comment by roeurbnavy** [comment]
data 500000+ records and requests at the same time (user 10+).

**Comment by Uzlopak** [comment]
5000000+ records? Well that doesnt sound reasonable.

**Comment by roeurbnavy** [comment]
Sorry, I was confused. 500000+ records.
![image](https://user-images.githubusercontent.com/20157836/210294897-4c6a8fa8-88ec-4a2f-b2af-75e18df3daee.png)

**Comment by vkarpov15** [comment]
Ideally, add an index to speed up your query. If that doesn't work or is infeasible for some reason, try increasing `maxPoolSize` to 20. If not, increase to 100, which is the default. Also, increase `minPoolSize` to 10.
