### ISSUE TITLE
Can't get access to data from Model.findOne() outside its body.

### ISSUE THREAD

**Issue by Jacob1Tm** [Automattic/mongoose#12812]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.0

### Node.js version

18.8.0

### MongoDB version

6.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

So im trying to get the data from my db using moongose like that
```js
let value;
Model.findOne({ something: something}, (err, Doc) => {
    if (err) {
        console.error(err);
        return;
    }
    if (Doc) {
        value = Doc.value
    } else {
        value = config.value
    }
});
```
but i need to get it in entire program and i don't really know how to do it. when i try to console log in this i have a correct value, but outside of it i get undefined.

**Comment by Uzlopak** [comment]
Can you use async await logic?

**Comment by Jacob1Tm** [comment]
Now i have this error

```
const err = new MongooseError('Query was already executed: ' + str);
                  ^

MongooseError: Query was already executed: Model.findOne({})
    at model.Query._wrappedThunk [as _findOne] (C:\A\Repo\node_modules\mongoose\lib\helpers\query\wrapThunk.js:23:19)
    at C:\A\Repo\node_modules\kareem\index.js:426:25
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  originalStack: 'Error\n' +
    '    at model.Query._wrappedThunk [as _findOne] (C:\\A\\Repo\\node_modules\\mongoose\\lib\\helpers\\query\\wrapThunk.js:27:28)\n' +
    '    at C:\\A\\Repo\\node_modules\\kareem\\index.js:426:25\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)'
}
```

**Comment by Uzlopak** [comment]
Without callback fn as last parameter, the functions will return promises, which you can await.

**Comment by Jacob1Tm** [comment]
uhh, im not sure what do you mean...

**Comment by Uzlopak** [comment]
await Model.findOne({ something: something})

**Comment by Jacob1Tm** [comment]
im really confused right now what should i do with it...

**Comment by Uzlopak** [comment]
How many years or months experience do you have with Javascript for backend?

**Comment by Jacob1Tm** [comment]
not much...

**Comment by Uzlopak** [comment]
Please first learn about async await and Promises, and how they prevent you from callback hell.

**Comment by Jacob1Tm** [comment]
Finally works!

**Comment by Jacob1Tm** [comment]
~~and now i see what i did wrong thx~~
