### ISSUE TITLE
mongoose updateOne add pre then no return 

### ISSUE THREAD

**Issue by tingfeima** [Automattic/mongoose#12836]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.1

### Node.js version

v14.17.3

### MongoDB version

4.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Issue

1.  schema.pre('updateOne'，async function (doc, next) {
    const updateInfo = {}
    // do stuff...
    this._update.$set = { ...updateInfo }
    return next()
  })
  
2.  const result = await model.updateOne(
    {
     nickname:'mark',
    },
    { $set: {updatedAt:new Date() } }
  )
  console.log(result)  // undefined

why the result is undefined

**Comment by eternalbasic1** [comment]
I guess, As you are using await and async and javascript is a Single-Threaded & Synchronous Language it just execute the code line by line very fast. As you are using async and await which internally deals with Event loop/ TaskQueue/MicroTask. Just waiting for call stack to empty. Why don't you make a the console.log inside a settimeout function and see it, I feel it works when you use a
`settimeout(console.log(result),2000);` 
at the last line

**Comment by vkarpov15** [comment]
The following prints `undefined`. But prints an update result object if you remove the `next()` call. Strange.

```javascript
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

const schema = mongoose.Schema({ name: String });
schema.pre('updateOne', async function(doc, next) {
  this._update = this._update || {};
  this._update.$set = { name: 'foo' };
  //return next();
  next();
});
const Test = mongoose.model('Test', schema);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/mongoose_test');
  const res = await Test.updateOne();
  console.log(res);
  process.exit(0);
}
```

**Comment by vkarpov15** [comment]
The issue is that `next` is the _first_ parameter to pre hooks, not the _second_. Do the following instead and it will work fine:

```javascript
schema.pre('updateOne'，async function (next) { // <-- remove `doc` as first parameter here
  const updateInfo = {}
  // do stuff...
  this._update.$set = { ...updateInfo }
  return next()
})
```

The issue is that Mongoose calls the updateOne hook with `next` as the first argument, and the final callback that it should call once all hooks are done as the 2nd argument. Admittedly this is not a great design choice, and mongoosejs/kareem#36 fixes that. But, in the meantime, please fix your argument order and this will work fine.
