### ISSUE TITLE
Model.find() vs Query.find()

### ISSUE THREAD

**Issue by TemurbekRuziyev** [Automattic/mongoose#12835]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.15

### Node.js version

14.17.1

### MongoDB version

not installed

### Operating system

macOS

### Issue

Currently I am learning NodeJs with MongoDB, and Mongoose as well.
I am confusing some Mongoose implementation:
1. Can **find()** method be used with Model and Query equally?
2. Is there any difference between Model.find() and Query.find()?
3. Is it OK to using chained .finds like: Model.find().find().find()

Thanks in advance!

**Comment by vkarpov15** [comment]
`Model.find()` is equivalent to creating a new `Query` instance and calling `find()` on it. So no significant difference.

`Model.find().find().find()` is fine. We sometimes do stuff like `Model.find({ name: 'test' }).find({ age: { $gte: 30 } })`, which is equivalent to `Model.find({ name: 'test', age: { $gte: 30 } })`
