### ISSUE TITLE
Question: Does mongoose have/need warmup?

### ISSUE THREAD

**Issue by VladimirMikulic** [Automattic/mongoose#12845]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi!

I'm using mongoose to connect to my MongoDB cluster which is hosted on Atlas.
The first few queries (regardless of the collection) upon server startup are slower, almost like it needs to warm up.
(e.g. the same query executed the first few times needs ~2 seconds to complete, but after that it consistently completes in ~700ms)

This doesn't appear to be the case with `mongosh` CLI tool from MongoDB.

I know the question is kind of vague, but I'm just wondering is there a warmup procedure/options used by mongoose that impact initial performance/responsivness?

Thanks!

**Comment by vkarpov15** [comment]
Try setting `minPoolSize` (see connection options docs: https://mongoosejs.com/docs/connections.html#options )

```javascript
await mongoose.connect(uri, { minPoolSize: 10 });
```

The MongoDB node driver maintains a pool of sockets connected to MongoDB, and only one operation can run on a socket at any given time. And the pool size grows/shrinks between ` minPoolSize` and `maxPoolSize` depending on load. It may be that there are just too few sockets open at first, and opening a new socket can be slow.

**Comment by VladimirMikulic** [comment]
Thanks for a fast reply @vkarpov15.
I can confirm that setting `minPoolSize` makes a difference :+1:
