### ISSUE TITLE
Customize unique error message in schema

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#12844]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

See https://github.com/Automattic/mongoose/issues/1225#issuecomment-1359689295 . Should be able to specify an error message for `unique: true` on a given path, and have Mongoose handle that.

**Comment by ahmedkrdzalic** [comment]
Thank you @vkarpov15 . I am happy to see that you took first steps for this request.
If you have some next steps on your mind that I could make, you can give me a suggestion. I am willing to contribute. In that time I will read contributing guidelines for this project.

**Comment by vkarpov15** [comment]
I don't have a good suggestion right now. Big problem is that `unique` isn't a validator, it defines an index. So we'll probably need some [error handling middleware](https://thecodebarbarian.com/mongoose-error-handling.html) in a plugin.
