### ISSUE TITLE
Remove support for custom promise libraries

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#12872]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

MongoDB Node driver is dropping support for `promiseLibrary` option, so we should remove support for `mongoose.Promise`. Worth dropping on our end. You can always switch to bluebird by doing something like `global.Promise = require('bluebird')`

**Comment by Uzlopak** [comment]
I agree.

**Comment by hasezoey** [comment]
> MongoDB Node driver is dropping support for promiseLibrary option

in which version are they planning to remove that option 5.x or some 4.x version?

**Comment by vkarpov15** [comment]
5.x. Dropping support for an option would be backwards breaking.
