### ISSUE TITLE
Model.create() not allowing me to pass SaveOptions as the second argument

### ISSUE THREAD

**Issue by ammarlakho** [Automattic/mongoose#12877]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.18.1

### MongoDB server version

5.0.14

### Typescript version (if applicable)

4.9.3

### Description

Similar to this: https://github.com/Automattic/mongoose/issues/10588 but this person's issue was due to typescript version being 3.x.

While trying  insert a new mongoose model into a collection, I'm receiving the following error:

```
The last overload gave the following error.
    Argument of type 'SaveOptions' is not assignable to parameter of type 'Callback<Customer & Document<any, any, any> & { _id: ObjectId; }>'.
      Type 'SaveOptions' provides no match for the signature '(error: NativeError, result: Customer & Document<any, any, any> & { _id: ObjectId; }): void'.

168       options,
          ~~~~~~~

  node_modules/mongoose/types/models.d.ts:185:5
    185     create<DocContents = AnyKeys<T>>(doc: T | DocContents, callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>): void;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

From what I understand, I'm trying to call the create function with this declaration: `create<DocContents = AnyKeys<T>>(docs: Array<T | DocContents>, options?: SaveOptions): Promise<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>[]>;`
 since i am passing the optional saveOptions function alongside but for some reason mongoose is matching it with the last overload: `create<DocContents = AnyKeys<T>>(doc: T | DocContents, callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>): void;` and the types are not matching for obvious reasons. 

### Steps to Reproduce

Create a schema and a model. Try to use the `create` function to insert a model into the schema. Sample code:

```
import { SaveOptions } from 'mongoose';
const objToInsert = {}
const options: SaveOptions = {}
model.create(objToInsert, options)
```

Output will be something like this (also mentioned above):
```
The last overload gave the following error.
    Argument of type 'SaveOptions' is not assignable to parameter of type 'Callback<Customer & Document<any, any, any> & { _id: ObjectId; }>'.
      Type 'SaveOptions' provides no match for the signature '(error: NativeError, result: Customer & Document<any, any, any> & { _id: ObjectId; }): void'.

168       options,
          ~~~~~~~

  node_modules/mongoose/types/models.d.ts:185:5
    185     create<DocContents = AnyKeys<T>>(doc: T | DocContents, callback: Callback<HydratedDocument<T, TMethodsAndOverrides, TVirtuals>>): void;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```

### Expected Behavior

For mongoose to allow me to pass SaveOptions to the model.create(obj, options) function.

**Comment by hasezoey** [comment]
i think i see the problem, there is no overload for a single document with options, only a array of documents with options

**Comment by vkarpov15** [comment]
This is expected behavior. Do `model.create([obj], options)` instead. From [the create() docs](https://mongoosejs.com/docs/api/model.html#model_Model-create): 

![image](https://user-images.githubusercontent.com/1620265/211056642-31a9a0f5-b278-4db4-b1b6-dec0096ad1c4.png)

**Comment by ammarlakho** [comment]
Thanks @vkarpov15! I should have looked at the function signatures more carefully.
