### ISSUE TITLE
Update `.lean` type to automatically remove methods from type

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#12880]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently the `.lean` type does not remove methods from a given type, so something like the following is passing in typescript, but will fail at runtime:

```ts
// NodeJS: 18.10.0
// MongoDB: 5.0 (Docker)
// Typescript 4.9.4
import * as mongoose from 'mongoose'; // mongoose@6.8.0

interface IUser {
  username: string;
  test(): void;
}

const UserModel = mongoose.model<IUser>('User', new mongoose.Schema({ username: String }, { methods: { test() {} } }));

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  await UserModel.create({ username: 'hello' });

  const doc = await UserModel.findOne({}).orFail().lean();
  doc.test(); // should give a type error

  await mongoose.disconnect();
})();
```

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseLeanMethods

Note: the auto-inferred types are not affected, because they properly split all methods defined via the `methods` option into the proper generic

**Comment by vkarpov15** [comment]
Copying my comment from #12894: We're trying hard to move away from supporting putting methods directly in the document interface, mostly because TypeScript doesn't support stripping out function keys from an object in general. See https://github.com/microsoft/TypeScript/issues/43281 : stripping function keys _does_ work in some cases, but once you add generic interfaces then things break.

Correct way to do this would be:

```javascript
import mongoose from 'mongoose';

interface IUser {
  username: string;
}

interface IUserMethods {
  test(): string;
}

type UserModelType = mongoose.Model<IUser, {}, IUserMethods>;

const UserModel = mongoose.model<IUser, UserModelType>(
  'User',
  new mongoose.Schema<IUser, UserModelType, IUserMethods>({ username: String }, { methods: { test() {} } })
);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  await UserModel.create({ username: 'hello' });

  const doc = await UserModel.findOne({}).orFail();
  doc.test();

  const leanDoc = await UserModel.findOne({}).orFail().lean();
  leanDoc.test(); // should give a type error

  await mongoose.disconnect();
})();
```

**Comment by hasezoey** [comment]
> mostly because TypeScript doesn't support stripping out function keys from an object in general
> Correct way to do this would be:

the problem is when using something like a class (especially in typegoose) where there are properties *and* methods on the same type, it hard to separate them without major performance impacts (or as noted not working correctly as noted in your typescript issue?)

what would you recommend in a case where both things are on the same type?

**Comment by vkarpov15** [comment]
Separate them out beforehand. That's really the only way to go. TypeScript isn't very good about splitting properties out, much more reliable to merge things together later.
