### ISSUE TITLE
mongodb-client-encryption is not working with autoEncryption.bypassAutoEncryption true

### ISSUE THREAD

**Issue by KetanChakraworthy** [Automattic/mongoose#12896]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.13.14

### Node.js version

16.14.2

### MongoDB server version

5.0.7

### Description

I have been trying to make Explicit Encryption and Implicit Decryption with mongodb-client-encryption.
but when i try to connect client with bypassAutoEncryption : true It is throwing error and crashing the server.
<img width="626" alt="Screenshot 2023-01-10 at 1 31 21 PM" src="https://user-images.githubusercontent.com/48315592/211494418-eec85d51-b3ca-41df-8cda-272f6ecb7a10.png">
<img width="729" alt="Screenshot 2023-01-10 at 1 31 55 PM" src="https://user-images.githubusercontent.com/48315592/211494514-c61c7344-0dc9-4fe7-a97c-636d98dc46eb.png">

### Steps to Reproduce

Adding bypassAutoEncryption : true in mongoose mongoose.createConnection options

**Comment by IslandRhythms** [comment]
See if something from this issue thread can help you https://github.com/Automattic/mongoose/issues/10593

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.connection.on('connected', () => {
  console.log('connected')
});

async function run() {

  const arr = [];
  for (let i = 0; i < 96; ++i) {
    arr.push(i);
  }
  const key = Buffer.from(arr);

  const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };
  const db = await mongoose.connect('mongodb://localhost:27017', {
    autoIndex: false,
    maxPoolSize: 1000,
    socketTimeoutMS: 45000,
    dbName: 'Test',
    useNewUrlParser: true,
    useUnifiedTopology: true,
    autoEncryption: {
      keyVaultNamespace,
      kmsProviders,
      bypassAutoEncryption: true
    }
  });
}

run();
```
