### ISSUE TITLE
findAndUpdate doesn't propagate to the document

### ISSUE THREAD

**Issue by Vardner** [Automattic/mongoose#12899]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.5

### Node.js version

16.15.0

### MongoDB server version

6.0.1

### Scenario:
I have 2 connected models, e. g. "Product" and "Review". 
Whenever a review is added, post "save" middleware will be run.
In the middleware, I have an aggregation pipeline to calculate average rating based on the reviews and then I am updating the Product's field (total rating) by issuing the `findByIdAndUpdate ` command.

Since I don't want to check the result of the update I leave it without any callbacks or await statements.

### Outcomes
But, it turns out that if I don't wait for the result, my update doesn't propagate to the document

### Steps to Reproduce

``` javascript
Review.statics.calcAvgRatings = async function (tourId) {
    const stats = (await models.Review.aggregate([
        {
            $match: {tour: tourId}
        },
        {
            $group: {
                _id: '$tour',
                total: {$count: {}},
                avg: {$avg: '$rating'}
            }
        },
        {
            $set: {
                avg: {$round: ['$avg', 1]},
            }
        }
    ]))[0];

    console.log(stats);

    models.Tour.findOneAndUpdate(
        {_id: tourId},
        {ratingsAverage: stats.avg, ratingsQuantity: stats.total},
        undefined,
        // () => 0 // Will not work without this callback or without await statement
    );
};

Review.post('save', function () {
    Review.statics.calcAvgRatings(this.tour);
})
```

### Expected Behavior

Update propagates to the document without waiting for the result

**Comment by MohOraby** [comment]
Without a callback function, `then()` or `await` [a query object is returned](https://mongoosejs.com/docs/api/model.html#model_Model-findOneAndUpdate)

**Comment by Vardner** [comment]
@MohOraby you mean that I should call exec method on returned query so it will be executed, yeah sounds reasonable
https://mongoosejs.com/docs/api/query.html#query_Query-exec
