### ISSUE TITLE
How to use aggregate match with UUID type?

### ISSUE THREAD

**Issue by wfjake** [Automattic/mongoose#12893]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.3

### Node.js version

16.17.1

### MongoDB version

6.0.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 37

### Issue

I understand that mongoose does not automatically cast values in aggregate pipelines, and I've been trying to find how to do this for UUIDs but have been unsuccessful.

My reduced schema:
```
import mongoose from "mongoose";

const mySchema = new mongoose.Schema({
    _id: {type: mongoose.Schema.Types.UUID},
    name: {type: String, required: true}
});

export const My = mongoose.model("My", mySchema);
```

What I'm (failing) to do:
```
let my = await My.aggregate().match({_id: new mongoose.Types.UUID("1e984535-98ad-446b-84cc-bd8f59290eb8")}).exec();
```

The above fails with `TypeError: mongoose.Types.UUID is not a constructor`, but this seems to be the solution for ObjectIds (obviously with UUID replaced to ObjectId). How can I aggregate match with UUIDs in mongoose?

**Comment by wfjake** [comment]
I tried with this as suggested:
```
let my = await My.aggregate().match({_id: new mongoose.Schema.Types.UUID("1e984535-98ad-446b-84cc-bd8f59290eb8")}).exec();
```
It didn't crash, but it returns 0 results despite me running the equivalent on the server with MongoDB's UUID() function and it returning the document as expected.

**Comment by guilhermedalleprane** [comment]
It looks like the native mongodb driver doesn't export the `UUID` class they use internally like they do with `ObjectId`, so I don't know how this would be resolved on the `mongoose` side. But, while no definitive solution is provided, you can generate a `UUID` using the `bson` package as the mongodb native driver does by default:

```typescript
import { UUID } from "bson";
...

let my = await My.aggregate().match({_id: new UUID("1e984535-98ad-446b-84cc-bd8f59290eb8")}).exec();

```

**Comment by wfjake** [comment]
Thanks @guilhermedalleprane, that's solved my issue. I'll leave this up to the maintainers whether to close or not.

**Comment by wfjake** [comment]
Since MongoDB's latest driver (5.x) exports the UUID class now, I made feature request #13103 to add UUIDs as a type in Mongoose. The best way to get the UUID class with Mongoose 7 is now `import {BSON} from "mongodb"` and use `new BSON.UUID("1e984535-98ad-446b-84cc-bd8f59290eb8")`
