### ISSUE TITLE
[Doc] comment and schema definition do not match

### ISSUE THREAD

**Issue by IslandRhythms** [Automattic/mongoose#12895]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

![image](https://user-images.githubusercontent.com/39510674/211387817-a94654ab-0e0b-4ca4-99cf-edcbb6b23588.png)
the comment calls it `onModel` but the schema definition and usage is `docModel`

@vkarpov15 could be a good first issue for the org person

**Comment by kailash360** [comment]
Can I work on this?

**Comment by vkarpov15** [comment]
@kailash360 absolutely :+1:
