### ISSUE TITLE
InferSchemaType fails to infer type for schema with array of subdocs.

### ISSUE THREAD

**Issue by larkvincer** [Automattic/mongoose#12907]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.15.0

### MongoDB server version

5.0

### Typescript version (if applicable)

4.9.3

### Description

Compiling the code with type inference of schema which has array of subdocs takes a long time and gives the following error:
```
RangeError: Value undefined out of range for undefined options property undefined
    at Map.set (<anonymous>)
```

### Steps to Reproduce

```typescript
const subDocSchema = new mongoose.Schema({
  id: String,
});

const docSchema = new mongoose.Schema({
  ids: [subDocSchema],
});

type DocType = InferSchemaType<typeof docSchema>;
```

**Comment by JavaScriptBach** [comment]
Try updating to 6.8.4. I think this should be fixed by #12884.
