### ISSUE TITLE
[Docs] Refactor header naming to lessen conflicts

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#12901]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently in the documentation, a naming of `#type_Type-function` is used, which can cause conflicts between *static* and *instance* methods, for example:
`#model_Model-remove` refers to both *instance* and *static* remove, which is not correct.

Also the `type_Type` is redundant, so it could be removed.
Personally i would like to not have to use band-aids for special cases and just have it correctly separated.

My proposal would be: `#Type(.prototype).function`, real examples:
- `#Model.remove` to refer to the *static* remove
- `#Model.prototype.remove` to refer to the *instance* remove

(basically like it is in JS directly)

i would target this towards 7.0 (because it would be a rather drastic change for the documentation.

as for backwards compatibility (like bookmarks), we could add hidden elements that still have the same old header id and so could still refer to the same place (and maybe some script to translate it to the new id)

cc @vkarpov15 @Uzlopak

**Comment by vkarpov15** [comment]
@hasezoey I like this proposal. Would you be willing to put a PR in against the 7.0 branch? You're right that we can write a script to convert the old format to new format, and 7.0 would be a great place to do that.

**Comment by hasezoey** [comment]
> I like this proposal. Would you be willing to put a PR in against the 7.0 branch? 

sure, i would like to have #12223 merged first to lessen conflicts (or duplicating work on things that are going to be deleted)
