### ISSUE TITLE
Stream watch is not triggered when save is called

### ISSUE THREAD

**Issue by mspapant** [Automattic/mongoose#12927]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.6

### Node.js version

16.17.0

### MongoDB server version

4.1.2

### Typescript version (if applicable)

4.6.2

### Description

I am trying to use the mongodb stream from mongoose, but the watch on model is not working when i call model.`save`. If i call `findOneAndUpdate` instead it works.

For example: 
definition:
```
TransactionModel.watch().on('save', (data) => console.log(data))
```
Then 
```
TransactionModel.findOneAndUpdate -> works
```
but
```
transaction.save() -> it doesn't
```

### Steps to Reproduce

1. Create a schema and a model. For example:
```
const transactionSchema = new Schema({
    name: String
})
const TransactionModel = model('Transaction', transactionSchema)
TransactionModel.watch().on('save', (data) => {
    console.log(data)
  })
```
2. Then load the transaction:
```
const transaction = await TransactionModel.findOne({_id: <>});
```
3. Try to save the transaction
```
transaction.save()
```

The console log is not triggered.

**Comment by MichaelJCole** [comment]
I don't think there is no 'save' event.  The Mongoose docs could be clearer.  From what I can tell, these are the possible events:
https://www.mongodb.com/docs/manual/reference/change-events/#std-label-change-stream-output

**Comment by IslandRhythms** [comment]
Try 'insert' or 'update' and see if that works

**Comment by vkarpov15** [comment]
There is no 'save' event, I think you're looking for the 'change' event? [Here's some more on how to work with change streams](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html).

```javascript
TransactionModel.watch().on('change', (data) => {
    console.log(data)
  })
```
