### ISSUE TITLE
Undefined values end up failing validation on `update`

### ISSUE THREAD

**Issue by 4rgc** [Automattic/mongoose#12930]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.4

### Node.js version

18.4.0

### MongoDB server version

4.4.6

### Description

Validation fails on update (`updateOne`, `findOneAndUpdate`) when update query object only consists of properties with undefined values.
The issue appeared after an upgrade from 5.12.13 to 6.8.4.
[Documentation](https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths) states that:
"When using update validators, `required` validators only fail when you try to explicitly `$unset` the key."
[Also](https://mongoosejs.com/docs/migrating_to_6.html#removed-omitundefined):
"In Mongoose 6.x, the omitUndefined option has been removed, and Mongoose will always strip out undefined keys."

It seems like neither of these 2 statements uphold when a simple `update` call is being made.
Adding `omitUndefined` to the options doesn't seem to change anything either.

### Steps to Reproduce

Also available at https://github.com/4rgc/mongoose-repro

### index.js
```js
import mongoose from 'mongoose';

try {
	await mongoose.connect('mongodb://localhost:27017', { dbName: 'test' });
} catch (err) {
	console.log(err);
}

mongoose.set('runValidators', true);

const userSchema = new mongoose.Schema({
	name: { type: String, required: true },
	email: { type: String, required: true },
});


const User = mongoose.model('User', userSchema);

let res;
try {
	res = await User.updateOne(
		{ _id: '63cb19035f29c5cf071095e3' },
		{ name: undefined, email: undefined }
//              {}  – would not fail
//              { name: "new name", email: undefined}  – would not fail either
	).then(
		(updatedUser) => ({ updatedUser, errUpdateUser: undefined }),
		(errUpdateUser) => ({ errUpdateUser, updatedUser: undefined })
	);
} catch (err) {
	console.log(err);
}

if (!res) {
	console.log('res is undefined');
} else {
	const { updatedUser, errUpdateUser } = res;

	if (!updatedUser) {
		console.log('empty update res');
		if (errUpdateUser) {
			console.log('errUpdateUser: ', errUpdateUser);
		}
	} else if (updatedUser.acknowledged) {
		console.log('acknowledged: ', updatedUser);
	}
}
```
### Test document
```json
// DB name: "test"; collection name: "users"
{
    "_id": {
        "$oid": "63cb19035f29c5cf071095e3"
    },
    "email": "email@email.com",
    "name": "name"
}
```
### package.json
```json
{
  "name": "mongoose-repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^6.8.4"
  }
}
```

### Full output with the error:
```
❯ node .
(node:38701) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
update not ok:  Error: Validation failed: email: Path `email` is required., name: Path `name` is required.
    at ValidationError.inspect (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/error/validation.js:50:26)
    at formatValue (node:internal/util/inspect:787:19)
    at inspect (node:internal/util/inspect:347:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2175:40)
    at formatWithOptions (node:internal/util/inspect:2037:10)
    at console.value (node:internal/console/constructor:339:14)
    at console.log (node:internal/console/constructor:376:61)
    at file:///Users/odmen/Projects/mongoose-repro/index.js:37:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: {
    email: ValidatorError: Path `email` is required.
        at validate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/schematype.js:1346:13)
        at SchemaType.doValidate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/schematype.js:1330:7)
        at /Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/updateValidators.js:151:22
        at module.exports (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/updateValidators.js:202:7)
        at /Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/query.js:4330:9
        at promiseOrCallback (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/promiseOrCallback.js:11:14)
        at model.Query.validate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/query.js:4325:10)
        at /Users/odmen/Projects/mongoose-repro/node_modules/kareem/index.js:497:25
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    name: ValidatorError: Path `name` is required.
        at validate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/schematype.js:1346:13)
        at SchemaType.doValidate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/schematype.js:1330:7)
        at /Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/updateValidators.js:151:22
        at module.exports (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/updateValidators.js:202:7)
        at /Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/query.js:4330:9
        at promiseOrCallback (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/helpers/promiseOrCallback.js:11:14)
        at model.Query.validate (/Users/odmen/Projects/mongoose-repro/node_modules/mongoose/lib/query.js:4325:10)
        at /Users/odmen/Projects/mongoose-repro/node_modules/kareem/index.js:497:25
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'name',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Validation failed'
}
^C

```

### Expected Behavior

Either props with undefined values are ignored, and `{}` is passed to the mongo driver, or the required validation rules don't get triggered when `$unset` is not explicitly in the query (as per documentation).
Operation succeeds without an error. 

`updatedUser`:
```
{
    name: "name",
    email: "email@email.com"
}
```

`errUpdatedUser`: `undefined`

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');
mongoose.set('runValidators', true);

const testSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson',
    email: 'test@localhost.com'
  });

  const res = await Test.updateOne({}, { name: undefined, email: undefined });
  console.log(await Test.findOne());
}

run();
```

**Comment by lpizzinidev** [comment]
Looking at the [docs](https://mongoosejs.com/docs/migrating_to_6.html#removed-omitundefined): 

> Removed omitUndefined: Mongoose now removes undefined keys in updates instead of setting them to null

From my understanding, it is the correct behavior to raise a validation error in this case since you are removing two required fields from the document with `updateOne({}, { name: undefined, email: undefined })`

**Comment by 4rgc** [comment]
@lpizzinidev Actually, it says the exact opposite, if you look at the example provided below the statement you quoted.

> Mongoose 5.x supported an omitUndefined option to strip out undefined keys. In Mongoose 6.x, the omitUndefined option has been removed, and Mongoose will always strip out undefined keys.
> ```
> // In Mongoose 6, equivalent to `findOneAndUpdate({}, {}, { new: true })` because Mongoose will
> // remove `name: undefined`
> const res = await Test.findOneAndUpdate({}, { $set: { name: undefined } }, { new: true });
> ```

Since version 6 it's supposed to by default ignore keys with `undefined` values

**Comment by 4rgc** [comment]
Also how about this? 
> When using update validators, required validators only fail when you try to explicitly $unset the key.

To me it's imperative from the above statement that:
> The required update validators will only fail if you explicitly use the `$unset` operator to unset the key

**Comment by lpizzinidev** [comment]
@4rgc Thank you for following up with further information.

I think that there are two options in this case:
1. Consider the current behavior _(ie. `updateOne({}, { name: undefined })` throws an error if `name` is required)_ a bug, fix it, and uniform the documentation.
2. Consider the current behavior correct, and just uniform the documentation accordingly.

@vkarpov15 What do you think?

**Comment by 4rgc** [comment]
Looking into it further, it seems like this was introduced in `v6.8.1` in this [commit](https://github.com/Automattic/mongoose/commit/ff67167c420ed486cd46c6b0b27d23ae890190b3).
I confirmed that on `v6.8.0` I cannot reproduce this.
Considering this, going with option 2 would mean that you introduced a breaking change in a patch version 6.8.1 which could cause issues for a lot of users.

Personally, if you were to go with option 2, I would very much love to still have an option to omit undefined keys.
It was very nice having that extra logic implemented in one option key, and, frankly, to me it doesn't make sense if you were to delegate that entirely it to the mongoose users.

**Comment by lpizzinidev** [comment]
@4rgc 
You are correct, #12794 didn't consider `required` fields.
I submitted a PR that should solve the bug. Let me know if further changes are needed or if I'm missing something.

**Comment by vkarpov15** [comment]
@lpizzinidev In hindsight, we probably shouldn't have merged #12797, that isn't what "omitting undefined keys" means. That means that `findOneAndUpdate({}, { title: undefined })` would be a no-op, not unsetting `title`. @4rgc is right that #12797 was likely a backwards breaking change. How do you feel about reverting that PR?

**Comment by lpizzinidev** [comment]
@vkarpov15 
Seems reasonable.
Pushed PR to revert introduced changes.
Thanks to @4rgc for the analysis and feedback 👍

**Comment by 4rgc** [comment]
Thanks guys!
