### ISSUE TITLE
sort does not seem to be working when using populate

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#12957]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.8

### Node.js version

16.13.0

### MongoDB version

5.0.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5.2

### Issue

I am trying to sort documents that are part of a query that uses populated documents, for example:

```
ItemOwnership.find()
        .populate({
            path: 'itemId',
            sort: { title: 1 }
        })
        .populate({
            path: 'userId',
        })
        .limit(10)
        .exec();
```

Here, `title` is a field on the Item (`itemId`) document. My goal is to sort all the documents in the `itemOwnership` collection by `itemId.title`. Is this even possible? If not, what alternatives are there?

**Comment by vkarpov15** [comment]
@joetidee that isn't possible. As written, your query will return `ItemOwnership` documents with each ItemOwnership's `itemId` sorted by title.

Alternatives are:

1) add an `itemIdTitle` property to `ItemOwnership` and sort by that
2) use MongoDB aggregation framework with `$lookup`
