### ISSUE TITLE
Any Migration guide from 5 to 6 that works?

### ISSUE THREAD

**Issue by ericrange** [Automattic/mongoose#12958]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

all 6.x

### Node.js version

18

### MongoDB version

5

### Operating system

Linux

### Issue

Is there any guide for migrating from mongoose 5 to 6?

we got a lot auf queries and i cant rewrite them all. if i just migrate and run the app, nearly all queries return different results. even those which are not in the "find" condition?

e.g.
.find({ a:1}) => also returns a:2

if i cant keep my "very simple" queries, i can never go to version 6 :(

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/migrating_to_6.html

**Comment by sean-daley** [comment]
`.find({ a:1}) => also returns a:2`

If a is defined in your schema then this should not return a:2. If it's not defined in your schema then you've probably run into the strictQuery changes that were done in 6.x (and will be undone I believe in 7.x). If you think a is defined in your schema though and it's still returning the wrong stuff, you might want to see if you can give the maintainers here a reproducible test for it.

If related to strictQuery, additional info on this can be found in https://github.com/Automattic/mongoose/issues/10747 and https://github.com/Automattic/mongoose/issues/12389

Those are the delete specific ones. There are other issues which go into more detail around find as well.

https://github.com/Automattic/mongoose/issues/11861 also goes over the plan to try and change this default for Mongoose 7.

**Comment by vkarpov15** [comment]
@ericrange please try running `mongoose.set('strictQuery', false)` when your app first starts, and see if that helps.
