### ISSUE TITLE
Feature: Where should we put this documentation on reconnection and serverSelectionTimeoutMs?

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#12967]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We've done some complex connection management, and wanted to share some patterns we used.

For example, if you have an Express or Koa app, such as `app.js`, you can set it up such as:

For single connection:

```js
const express = require('express');
const mongoose = require('mongoose');
const Graceful = require('graceful');
const pRetry = require('p-retry'); // use v4.x for CJS and v5.x+ for ESM
const getPort = require('get-port'); // use v5.x for CJS and v6.x+ for ESM

try {
  const app = express();
  const port = await getPort();
  const server = await new Promise((resolve, reject) => {
    app.listen(port, function (err) {
      if (err) return reject(err);
      resolve(this);
    });
  });
  const graceful = new Graceful({ servers: [server] });
  graceful.listen();

  console.log('express app started on %d', port);

  //
  // this will attempt to reconnect with exponential backoff up to 10x
  // however if there is not a MongooseServerSelectionError, it will throw
  // (this is useful to keep http server running and retry db connection)
  // (apps such as pm2 are recommended to cause app to reboot if this eventually throws)
  //
  await pRetry(
    () => mongoose.connection.asPromise(),
    {
      // <https://github.com/sindresorhus/p-retry/issues/58>
      // <https://github.com/tim-kos/node-retry/issues/84>
      // forever: true,
      // retries: Infinity,
      onFailedAttempt(err) {
        console.error(err);
        if (!(err instanceof mongoose.Error.MongooseServerSelectionError))
          throw err;
      }
    }
  );
} catch (err) {
  console.error(err);
  process.exit(1);
}
```

For multiple connections:

```js
const express = require('express');
const mongoose = require('mongoose');
const Graceful = require('graceful');
const pRetry = require('p-retry'); // use v4.x for CJS and v5.x+ for ESM
const getPort = require('get-port'); // use v5.x for CJS and v6.x+ for ESM

try {
  const app = express();
  const port = await getPort();
  const server = await new Promise((resolve, reject) => {
    app.listen(port, function (err) {
      if (err) return reject(err);
      resolve(this);
    });
  });
  const graceful = new Graceful({ servers: [server] });
  graceful.listen();

  console.log('express app started on %d', port);

  //
  // this will attempt to reconnect with exponential backoff up to 10x
  // however if there is not a MongooseServerSelectionError, it will throw
  // (this is useful to keep http server running and retry db connection)
  // (apps such as pm2 are recommended to cause app to reboot if this eventually throws)
  //
  await pRetry(
    () => Promise.all(mongoose.connections.map((connection) => connection.asPromise())),
    {
      // <https://github.com/sindresorhus/p-retry/issues/58>
      // <https://github.com/tim-kos/node-retry/issues/84>
      // forever: true,
      // retries: Infinity,
      onFailedAttempt(err) {
        console.error(err);
        if (!(err instanceof mongoose.Error.MongooseServerSelectionError))
          throw err;
      }
    }
  );
} catch (err) {
  console.error(err);
  process.exit(1);
}
```

Did you want to put this in documentation and as an example somewhere for users?  If so let us know where - or feel free to add it wherever you deem best fit!

### Motivation

Lack of real documentation and examples surrounding connection on application boot with `serverSelectionTimeoutMS` and how to properly handle it in real-world Express, Koa, Fastify, etc.

**Comment by vkarpov15** [comment]
You could always just increase `serverSelectionTimeoutMS`, although 30 seconds is typically more than enough time for any intermittent connectivity issues to resolve. But feel free to put a PR in for using `p-retry` to retry initial connection failures, it could be useful for cases where you want to keep `serverSelectionTimeoutMS` low during runtime, but allow retrying initial connection.

**Comment by hasezoey** [comment]
> Did you want to put this in documentation and as an example somewhere for users? If so let us know where - or feel free to add it wherever you deem best fit!

> Lack of real documentation and examples surrounding connection on application boot with serverSelectionTimeoutMS and how to properly handle it in real-world Express, Koa, Fastify, etc.

if you have documentation about something like options, like usage of `serverSelectionTimeoutMS`, then feel free to add a guide in `docs/` and just look at other existing guides for the style to use, if something is wrong or needs improvement it will be noted in the PR

mongoose does not currently list integration examples (aside from typescript) on the documentation website itself, but feel free to add your guide in `docs/further_reading.md`
