### ISSUE TITLE
Bug: Mongoose connection ID is not unique

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#12966]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

All

### Node.js version

All

### MongoDB server version

All

### Description

As discovered in <https://github.com/Automattic/mongoose/issues/12965#issuecomment-1410896781>, `connection.id` is not unique due to `.length` being used to determine its value.  As connections are created and destroyed, `id` properties get re-used.

### Steps to Reproduce

```sh
const mongoose = require('mongoose');
mongoose.createConnection()
mongoose.createConnection()
mongoose.connections[0].destroy()
mongoose.createConnection()
mongoose.createConnection()
mongoose.createConnection()
mongoose.connections.map(c => c.id) // outputs: [ 1, 2, 3, 3, 4 ]
```

**Comment by manjitkumar** [comment]
@titanism @vkarpov15 What impact would this bug have had on the application?

**Comment by vkarpov15** [comment]
@manjitkumar none. Connection `id` property is purely for logging and debugging purposes. Mongoose runtime behavior does not rely on the connection's `id`.
