### ISSUE TITLE
Mongo Whitelisted IP related issues.

### ISSUE THREAD

**Issue by itsjusttriz** [Automattic/mongoose#12969]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.0.12

### Node.js version

14.17.1

### MongoDB version

5.0.14

### Operating system

None

### Issue

For some reason, and only the past 2-3 months... my node.js app has been throwing this error:
> `
Mongoose Disconnected.
(node:2746) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. 
One common reason is that you're trying to access the database from an IP that isn't whitelisted. 
Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
`

Now i currently have my mongo cluster set to an open whitelist, e.g. `0.0.0.0/0` to allow all addresses to access it, so this error provided by mongoose is straight-up false. Im curious if its masking a deeper error, that i cannot figure out?

**Side note**:
I have `debug` set to `true` so that i could keep an eye on db calls, to double check whether a certain model method was causing this, but to no avail. I also have a console.log for the `connected` & `disconnected` events of the package, the latter of which you can see in the above stacktrace. The `connected` event doesnt seem to wanna run anymore, therefore, not running the console.log for it.

**Comment by vkarpov15** [comment]
Without more info, it'll be hard for us to tell what is causing this issue. One thing I can tell you is that whitelist entries isn't necessarily the cause of this issue, the issue is "Could not connect to any servers in your MongoDB Atlas cluster.". Whitelist is one possible explanation, but there are others:

1. Your app wasn't able to connect to MongoDB Atlas due to network issues
2. Your Atlas cluster was down

Probably some other potential explanations. But hard to tell without a code sample that demonstrates this issue.

**Comment by itsjusttriz** [comment]
There's not much more information i can give you. As I had been having this issue for multiple weeks with no sight of an end, i ended up moving to using sqlite3 instead.

Apologies, and thanks for your time.

**Comment by Aviral-Gupta101** [comment]
I am also having the same problem I don't know what happened but suddenly all my NodeJs application which are using Atlas MongoDB instance stop connecting to the database.  
I remembered one of the application worked perfectly fine on 24th of Feb, but when I tried to run the same application again yesterday it showed my error given below 

`MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at Connection.openUri (/Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/connection.js:825:32)
    at /Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/index.js:411:10
    at /Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/index.js:1285:10)
    at Mongoose.connect (/Users/aviralgupta/Development/NodeJs/MongoDB/node_modules/mongoose/lib/index.js:410:20)
    at connectDB (/Users/aviralgupta/Development/NodeJs/MongoDB/config/dbConfig.js:8:24)
    at Object.<anonymous> (/Users/aviralgupta/Development/NodeJs/MongoDB/index.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-a6to6lu-shard-00-00.nfmpr49.mongodb.net:27017' => [ServerDescription],
      'ac-a6to6lu-shard-00-01.nfmpr49.mongodb.net:27017' => [ServerDescription],
      'ac-a6to6lu-shard-00-02.nfmpr49.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-tvdhx4-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
Error in dbConfig.js`

As it mentions that `you're trying to access the database from an IP that isn't whitelisted` I tried to add my current IP address (even though access from anywhere IP: 0.0.0.0/0 was already present ) but still shows the same problem.

Also this project was running perfectly fine a week ago, but now its not working and also one thing to note is that I did not changed my Internet connection when I builded, tested it but now its not working.

**Comment by vkarpov15** [comment]
The issue is that Mongoose "Could not connect to any servers in your MongoDB Atlas cluster". So this is just a connectivity issue. Check to make sure the version of MongoDB you're running is compatible with the version of Mongoose you're using: https://mongoosejs.com/docs/compatibility.html, and check to see if the machine you're running your Node application on is able to connect to the internet. If still an issue, please open a new issue and follow the issue template.
