### ISSUE TITLE
Feature: `createConnection` should allow option to _not_ call `conn.openUri`, e.g. `options.openUri: false`

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#12970]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Right now any invocation of `createConnection(...)` will cause the `openUri()` call in this conditional to get triggered:

https://github.com/Automattic/mongoose/blob/8d9df24c1f4696d56a4c7d240d5bcedf6a008154/lib/index.js#L350-L352

We suggest to add an option to `createConnection` of `options.openUri: true` and if `false` then this is not called.

```diff
-  if (arguments.length > 0) {
+  if (arguments.length > 0 && options.openUri) {
    conn.openUri(uri, options, callback);
  }
```

**Comment by lpizzinidev** [comment]
You should be able to delay `openUri` call by not specifying the `uri` parameter for `createConnection`, taken from the [docs](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-createConnection):
```
// initialize now, connect later
db = mongoose.createConnection();
db.openUri('127.0.0.1', 'database', port, [opts]);
```

**Comment by vkarpov15** [comment]
@lpizzinidev is right, you can just do `const conn = mongoose.createConnection()`, and that gets you a new connection without calling `openUri()`.
