### ISSUE TITLE
Question: how to override the save method of a model

### ISSUE THREAD

**Issue by kojilab** [Automattic/mongoose#1300]
Hi,

How can I override the save method of a model? I'm trying to find an example but I'm not being lucky.

Thanks for your help!!

**Comment by sabrehagen** [comment]
I would like to know how to do this. I want to change the signature of the save object so it can accept the new and the old models to be able to compare model values and perform 'middleware' style functions based on the changes.

**Comment by vkarpov15** [comment]
What do you mean "accept the new and old models"? Mongoose already tracks changes for you, you can check if a path is modified with the `Document.isModified()` function.

**Comment by sabrehagen** [comment]
In addition to checking if it was modified, I would also like to get the original value before modification. Is this possible currently?

Also, i'm trying to keep my code as library agnostic as possible for if we want to switch database at a later stage. By intercepting the calls I can wrap the data access library (in this case mongoose, but potentially any other library).

**Comment by vkarpov15** [comment]
Good point, we don't keep the original values. I'd imagine you'd have to make a copy using `toObject()` first to keep the original values.

As for a wrapper around save, you could pretty easily just use a schema method:

```javascript
mySchema.methods.myCustomSave = function(old, callback) {
  // Do stuff comparing `old` and `this`
  this.save(callback);
}:
```

Then you could access it using `doc.myCustomSave()` for any doc whose model uses `mySchema`

**Comment by sabrehagen** [comment]
This is the current temporary solution i'm using whilst testing, but the clean semantic nature of "save" is something i'd like to try and maintain.

**Comment by vkarpov15** [comment]
Tracking past values of fields in a document sounds like a pretty cool idea, and it would be difficult to implement with the current implementation of mongoose and won't really be a priority for mongoose during the next 6 months. What sort of clean semantic nature are you envisioning?

**Comment by dandv** [comment]
How about a scenario using random-generated short IDs (e.g. `nanoid`), where it's OK to have a rare collision, but would like to override `save` to retry until there's no collision?

**Comment by vkarpov15** [comment]
@dandv I think a custom method is the way to go there. You could also do this with a `post('save')` hook using [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware)

**Comment by hieuluu-lulu** [comment]
hello every one . I have a question. I have a Schema Course like this : 

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const slug = require('mongoose-slug-generator');
const CourseSchema = new Schema(
    {
        courseID: { type: Number },
        name: { type: String, maxLength: 255, require: true },
        author: { type: String, maxLength: 255, require: true },
        description: { type: String, maxLength: 600, require: true },
        image: { type: String, maxLength: 255 },
        videoId: { type: String, required: true },
        category: { type: String, required: true },
        level: { type: String, maxLength: 255, required: true },
        price: { type: Number },
        tag: { type: String, required: true },
        slug: { type: String, slug: 'name', unique: true },
        topic: { type: Array },
        request: { type: Array },
        comments: {type: Array},
        members: { type: Number, default: 0},
    },
    {
        timestamps: true,
    },
);
i have a comment ( array). I want to when user reply on comment then replies array will push into comment.
So i have problem with this code : 

replyHandler(req, res, next) {
        var reply_id = mongoose.Types.ObjectId();

        Course.updateOne(
            {
                _id: req.body.course_id,
                'Course.comments._id': req.body.comment_id,
            },
            {
                $push: {
                    'comments.$.replies': {
                        _id: reply_id,
                        username: req.user.name,
                        reply: req.body.reply,
                        image: req.user.image,
                    },
                },
            },
        )
            .then(() => {
                console.log(req.body.comment_id);
                res.redirect('back');
            })
            .catch(next);
So any body here have solution for my situation

**Comment by vkarpov15** [comment]
@hieuluu-lulu replace `'Course.comments._id': req.body.comment_id,` with `'comments._id': req.body.comment_id,`
