### ISSUE TITLE
tsc: `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by keljohe10** [Automattic/mongoose#13008]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.0

### Node.js version

14.20.1

### MongoDB server version

4.4

### Typescript version (if applicable)

4.6.4

### Description

# Bug Report

Crash when running `tsc` and the mongoose version is higher than v5.10.19

```
running better-npm-run in $PROJECT_ROOT
Executing script: server:build

to be executed: tsc 
/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:95302
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at instantiateTypes (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51421:34)
    at getObjectTypeInstantiation (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51557:80)
    at instantiateTypeWorker (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51757:28)
    at instantiateTypeWithAlias (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51737:26)
    at instantiateType (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51723:37)
    at getConditionalType (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:50792:35)
    at getConditionalTypeInstantiation (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51715:25)
    at instantiateTypeWorker (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51789:24)
    at instantiateTypeWithAlias (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51737:26)
    at instantiateType (/$PROJECT_ROOT/node_modules/typescript/lib/tsc.js:51723:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@0.0.1 server:build: `bnr server:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api@0.0.1 server:build script.
```

### 🔎 Search Terms

RangeError: Maximum call stack size exceeded

### 🕗 Version & Regression Information

Since version, v5.11.0 mongoose introduced its own types and recommends using the latest version of @types/mongodb, but the application is failing to execute the **tsc** command precisely in the versions that mongoose implements its own types. Versions below v5.11.0 are working correctly.

- This is a crash
- This changed between versions 5.11.0 and 6.9.0
- This is the behavior in every version I tried higher than v5.10.19, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### 💻 Code

**package.json**
```json
{
  "name": "api",
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {
    "server:build": "bnr server:build",
  },
  "betterScripts": {
    "server:build": {
      "command": "tsc"
    },
  },
  "dependencies": {
    "@airbnb/node-memwatch": "~2.0.0",
    "@maxmind/geoip2-node": "~3.4.0",
    "@types/config": "0.0.41",
    "aws-sdk": "~2.814.0",
    "better-npm-run": "~0.1.0",
    "btoa": "~1.2.1",
    "chalk": "~2.1.0",
    "chance": "~1.0.10",
    "config": "~1.26.1",
    "exiting": "~2.0.1",
    "fbgraph": "~1.4.1",
    "flat": "~4.0.0",
    "geoip-lite": "~1.4.0",
    "good": "~7.2.0",
    "hapi": "~16.5.2",
    "hapi-auth-basic": "~4.2.0",
    "hapi-auth-bearer-token": "~5.1.0",
    "hapi-auth-jwt2": "~7.3.0",
    "hapi-good-winston": "~1.1.1",
    "hapi-swagger": "~7.7.0",
    "iban": "~0.0.8",
    "inert": "~4.2.1",
    "ip-range-check": "~0.0.2",
    "jsonwebtoken": "~8.3.0",
    "lodash": "~4.17.21",
    "moment": "~2.29.2",
    "mongoose": "~6.9.0",
    "node-mailjet": "~3.2.1",
    "object-hash": "~1.1.8",
    "oidc-provider": "~7.11.3",
    "promptly": "~2.2.0",
    "redis": "~3.1.1",
    "saml20": "~0.1.14",
    "semver": "~5.4.1",
    "stack-trace": "~0.0.10",
    "vision": "~4.1.1",
    "winston": "~2.3.1"
  },
  "devDependencies": {
    "@istanbuljs/nyc-config-typescript": "~1.0.2",
    "@types/mongodb": "~4.0.7",
    "@types/node": "~14.14.31",
    "@typescript-eslint/parser": "~5.31.0",
    "chai": "~4.1.2",
    "chai-as-promised": "~7.1.1",
    "chai-sorted": "~0.1.0",
    "commander": "~2.14.1",
    "eslint": "~4.18.2",
    "eslint-config-prettier": "~2.3.0",
    "eslint-plugin-prettier": "~2.1.2",
    "fast-csv": "~4.3.6",
    "json-size": "~1.0.0",
    "jsonfile": "~4.0.0",
    "jsonwebtoken": "~8.3.0",
    "mocha": "~2.4.5",
    "mocha-jenkins-reporter": "~0.3.1",
    "mongodb": "~4.12.0",
    "nock": "~9.0.22",
    "nodemon": "~1.19.4",
    "nyc": "~15.1.0",
    "prettier": "~1.5.3",
    "sinon": "~4.1.2",
    "sinon-chai": "~2.14.0",
    "supertest": "~3.0.0",
    "supertest-as-promised": "~4.0.2",
    "ts-node": "~10.9.1",
    "typescript": "~4.6.4"
  }
}
```

**Comment by hasezoey** [comment]
>     "mongoose": "~6.9.0",
>     "@types/mongodb": "~4.0.7",
>     "mongodb": "~4.12.0",

mongoose 6.x uses mongodb driver 4.x (which you also have in the package.json), which provides its own types, and `@types/mongodb` is now a stub package and can be removed

>     "typescript": "~4.6.4"

did you already try a newer typescript version?

---

could you provide your tsconfig that is in use?
also, do you know if this happens with some specific files or even in a new project?

**Comment by keljohe10** [comment]
Hey, the error is still happening when I upgraded typescript with the latest version (~4.9.5) and removed @types/mongodb.

this is the `tsconfig.json` file

`{
  "compilerOptions": {
    "target": "es2015", /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "lib": ["es6"], /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "module": "commonjs", /* Specify what module code is generated. */
    "rootDir": "server", /* Specify the root folder within your source files. */
    "resolveJsonModule": true, /* Enable importing .json files */
    "allowJs": true, /* Allow JavaScript files to be a part of your program. Use the `checkJS` option to get errors from these files. */
    "checkJs": false, /* Enable error reporting in type-checked JavaScript files. */
    "outDir": "build/server", /* Specify an output folder for all emitted files. */
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
    "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
    "strict": true, /* Enable all strict type-checking options. */
    "noImplicitAny": true, /* Enable error reporting for expressions and declarations with an implied `any` type.. */
    "skipLibCheck": true, /* Skip type checking all .d.ts files. */
    "removeComments": true
  },
  "include": ["server/**/*"],
  "exclude": ["node_modules", "build/**/*"]
}
`

And the error happens when I just run **tsc**

**Comment by vkarpov15** [comment]
It looks like you have a fairly sophisticated project, so there's no way we'll be able to repro this unfortunately. If you can show us a project that has this issue, we're happy to take a look. Otherwise, unfortunately all we can say is that our TypeScript tests are passing and without further info there isn't much we can do.

**Comment by bozmen** [comment]
We have managed to reproduce the problem in a much smaller project, and we found out these files are the problematic ones:

user.model.js
```
import mongoose from 'mongoose';
import createSchema from './createSchema';

const { String, Number, Boolean, ObjectId, Mixed } = mongoose.Schema.Types;

export const userSchema = {
  someList: [
    createSchema(
      {
        id: { type: Number },
        paths: [
          createSchema(
            { path: { type: String }, type: { type: String } },
            { _id: false, id: false },
          ),
        ],
      },
      { _id: false, id: false },
    ),
  ],
};
```

createSchema.js
```
import mongoose from 'mongoose';

/**
 * @template {mongoose.SchemaDefinition} T
 * @param {T} schemaBody
 * @param {mongoose.SchemaOptions} [options = {}]
 * @returns {import('./schema').Schema<T>}
 */
function schema(schemaBody, options = {}) {
  // @ts-ignore
  return new mongoose.Schema(schemaBody, options);
}

export default schema;
```

and the dependency list being:
```
  "dependencies": {
    "better-npm-run": "~0.1.0",
    "mongoose": "~6.9.0"
  },
  "devDependencies": {
    "typescript": "~4.6.4"
  }
```

**Comment by vkarpov15** [comment]
@bozmen I'm unable to repro, below script compiles fine with `tsc --strict` and TypeScript 4.6

```ts
import mongoose from 'mongoose';


const { String, Number, Boolean, ObjectId, Mixed } = mongoose.Schema.Types;

export const userSchema = {
  someList: [
    createSchema(
      {
        id: { type: Number },
        paths: [
          createSchema(
            { path: { type: String }, type: { type: String } },
            { _id: false, id: false },
          ),
        ],
      },
      { _id: false, id: false },
    ),
  ],
};

function createSchema(schemaBody: Record<string, any>, options = {}) {
  // @ts-ignore
  return new mongoose.Schema(schemaBody, options);
}
```

What does your tsconfig look like?

**Comment by vkarpov15** [comment]
Also, have you opened an issue in the TypeScript repo?

**Comment by bozmen** [comment]
@vkarpov15 Sorry for not providing it before, our tsconfig looks like this: (the same as before, with very little modifications)
```
{
  "compilerOptions": {
    "target": "es2015", /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "lib": ["es6"], /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    "module": "commonjs", /* Specify what module code is generated. */
    "rootDir": "src", /* Specify the root folder within your source files. */
    "resolveJsonModule": true, /* Enable importing .json files */
    "allowJs": true, /* Allow JavaScript files to be a part of your program. Use the `checkJS` option to get errors from these files. */
    "checkJs": false, /* Enable error reporting in type-checked JavaScript files. */
    "outDir": "build/server", /* Specify an output folder for all emitted files. */
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */
    "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
    "strict": true, /* Enable all strict type-checking options. */
    "noImplicitAny": true, /* Enable error reporting for expressions and declarations with an implied `any` type.. */
    "skipLibCheck": true, /* Skip type checking all .d.ts files. */
    "removeComments": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "build/**/*"]
}
```

And no, we have not opened an issue in the TypeScript repo yet.

**Comment by vkarpov15** [comment]
Would be good to open one in the TypeScript repo as well just in case.

**Comment by bozmen** [comment]
Alright, I opened one issue there too.

The tag says it "needs a repro script". Are the files we provided still cant reproduce the bug?

Here we also have our repo that you can reproduce the bug with "npm run test" command: https://github.com/Klab-Berlin/mongoose-test
