### ISSUE TITLE
`lean()` conflicts with `Map` type returned by `InferSchemaType`

### ISSUE THREAD

**Issue by Jokero** [Automattic/mongoose#13010]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

`InferSchemaType` returns `Map` type for a field of type `Map`, which is perfectly fine for full queries like `Model.findOne()`, but does not work for lean queries `Model.findOne().lean()`: 

```typescript
import mongoose, { InferSchemaType, model, Schema } from 'mongoose';

const schema = new Schema({
    name: { required: true, type: Map, of: String },
});

// infers { name: Map<string, string> }
export type CountryRaw = InferSchemaType<typeof schema>;

export const CountryModel = model('Country', schema);

(async () => {
    await mongoose.connect('mongodb://localhost/test');

    await CountryModel.create({
        name: {
            en: 'Croatia',
            ru: 'Хорватия',
        },
    });

    const country: CountryRaw | null = await CountryModel.findOne().lean().exec();
    if (country) {
        // produces "TypeError: country.name.get is not a function",
        // because country.name is a plain object, not a Map
        console.log('country name', country.name.get('en'));
    }
})();
```
Possible solution or quick fix is to allow to pass some flag to `lean()` function that will tell to convert plain object to a `Map` object:
```
// country.name will be a Map
const country: CountryRaw | null = await CountryModel.findOne().lean({ convertToMap: true }).exec();
```
Or maybe even better to use a special plugin for it.

**Comment by Jokero** [comment]
This problem is actually present in plain JS as well, because `Map` type will have different value in case of lean and hydrated queries. Just wanted to clarify

**Comment by vkarpov15** [comment]
@Jokero that's unfortunately expected behavior. Lean means you get back the raw document as it is stored in MongoDB. And MongoDB doesn't have a map type, just objects. We'll have to figure out a workaround for this, but I think the `lean({ inflateMaps: true })` option is a good workaround.
