### ISSUE TITLE
Filter in pre (find) hook Mongoose

### ISSUE THREAD

**Issue by jj-devs** [Automattic/mongoose#13014]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.3

### Node.js version

19.5

### MongoDB version

4.4.18 Community

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro Linux 5.15.91-1

### Issue

I'm trying to perform a query that filters an array from another document, to mention something about the structure, I try to populate the document based on the specified product and store id, so that it doesn't bring the other data from the array but in this case I understand that I can't access the document fields while in the middleware, I'm reading the documentation but I still learning concepts
```

bUnitSchema.pre(/^find/, function (next) {
  this.populate({
    path: "menuItem.product",

    select: {
      "storeId.$": 1,
    },
    match: {
      "storeId.store": "62a811d1af67f5415770f297",
      
    }
  });
  next();
});

```

any guide would be of excellent help

I try something like this
```

bUnitSchema.pre(/^find/, function (next) {
  
  this.populate({
    path: "menuItem.product",

    select: {
      "storeId.$": 1,
    },
    match: {
      
       *//here im trying to do something like this*
      *"storeid.store": bUnitSchema.menuItem.store*
    },
  });

  next();
});
```

but give me
`
store not defined`

**Comment by vkarpov15** [comment]
I think you would need a post hook, not a pre hook. If I'm reading this correctly, I think you're trying to use the result of `find()` in a `populate()`, which isn't going to work in a pre hook because the query hasn't executed yet.

**Comment by jj-devs** [comment]
Yes you are right, that was i need, this is the code:
```
bUnitSchema.post(/^find/, async function (docs) {
  for (let doc of docs) {
    for (let store of doc.menuItem) {
      await doc.populate({
        path: "menuItem.product",
        select: {
          "storeId.$": 1,
        },
        match: {
          "storeId.store": store.store,
        },
      });
    }
  }
});
```

Thanks for the help @vkarpov15 !
