### ISSUE TITLE
Updating the path 'X' would create a conflict at 'X'

### ISSUE THREAD

**Issue by alannaidon** [Automattic/mongoose#13011]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^5.8.7

### Node.js version

14.19

### MongoDB version

4.4.18 and 5.0.11 Community

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04.5 LTS

### Issue

I have the following query being executed in nodeJS
```
const myData = await this.findOneAndUpdate({
  myId,
  color,
}, {
  $setOnInsert: {
    myId,
    color,
    date: now.format('YYYY-MM-DD'),
    counter: myObj.counter - amount,
  },
  $inc: {
    counter: -amount
  },
}, {
  new: true,
  upsert: true,
});
```

I get the error:

> Updating the path 'count' would create a conflict at 'count'  

Now I understand this is happening because I have  color in both **$setOnInsert** and **$inc**.  
I believe that when no document/record is found, both **$setOnInsert** and **$inc** try to create the record and THEN the conflict error happens. Is this right?  
Also: This code works on **MongoDB 3.4.24 Community** but does NOT WORK on **MongoDB 5.0.11 Community and v4.4.18**    

I found [this issue](https://github.com/Automattic/mongoose/issues/7003), but couldn't find the version mongoose was updated to in order to fix it.  

Also tried to use `mongoose v6.9.1` with `MongoDB 5.0.11 and 4.4.18` - the error still happens.  

Changing the query would be the best/only approach?  
This error is happening only because some change made through MongoDB versions?  
I'd like some help to understand the error and find the best way to fix it.

**Comment by vkarpov15** [comment]
Changing the query is the only approach. This error is from the MongoDB server, nothing Mongoose can do about it unfortunately. If it is important for you to set `counter` to a non-zero initial value before incrementing, I would recommend doing a separate `findOneAndUpdate()` with `upsert: true` for the `$setOnInsert`, and then execute a separate `findOneAndUpdate()` with `$inc`.
