### ISSUE TITLE
how to do if using Number refs instead of ObjectId as refs when using populate method

### ISSUE THREAD

**Issue by cityvoice** [Automattic/mongoose#13017]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

My _id is a Number type, this is my schama, if I make wrong, please feel free to correct it  .

```js
@Schema({ versionKey: false })
export class Menu {
  @Prop({ alias: 'id' })
  _id: number;
  ...
  @Prop({ type: Number, default: [], ref: 'Menu' })
  children: Menu[];
}
export const MenuSchema = SchemaFactory.createForClass(Menu);
```

then i populate it, it doesnot work.

`const menu = this.menuModel.findOne({ id: 1 }).populate('children')`

some data in my database:

```js
[
{
  _id: 1,
  name: 'menu1',
  ...,
  children: [ 2 ]
},
{
  _id: 2,
  name: 'menu1-1',
  ...
}
]
```

populate result:

`{"_id":1, "name":"menu1" ,...}`

the filed children is missing.

**Comment by hasezoey** [comment]
i think you are using something like `@nestjs/mongoose`, did you already try without it?

> `  @Prop({ type: Number, default: [], ref: 'Menu' })`

did you make sure the package actually uses the model name `Menu`? (`console.log(this.menuModel.modelName)`)

**Comment by cityvoice** [comment]
Thanks for your replyment. Yes I’m using @nestjs/mongoose, I’m sure I have tried and my menu.schema.ts likes below. There is a question that has always bothered me how does mongoose know the childrens fileld refers to _id instead of other number type field?


import { Prop, Schema, SchemaFactory } from ***@***.***/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export type MenuDocument = HydratedDocument<Menu>;

@Schema({ versionKey: false })
export class Menu {
  @Prop({ alias: 'id' })
  _id: number;

  ...
  @Prop({ type: Number, default: [], ref: 'Menu' })
  childrens: number[];
}
export const MenuSchema = SchemaFactory.createForClass(Menu);

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月12日 18:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Automattic/mongoose] how to do if using Number refs instead of ObjectId as refs when using populate method (Issue #13017)


i think you are using something like @nestjs/mongoose, did you already try without it?

@Prop({ type: Number, default: [], ref: 'Menu' })

did you make sure the package actually uses the model name Menu? (console.log(this.menuModel.modelName))

―

**Comment by hasezoey** [comment]
> There is a question that has always bothered me how does mongoose know the childrens fileld refers to _id instead of other number type field?

because from what i know it is statically set to the property `_id`, if you want it based on another field, you may wanna look at [Virtual Populate](https://mongoosejs.com/docs/populate.html#populate-virtuals) (or in terms of something similar to nestjs, the typegoose docs [Virtual Populate](https://typegoose.github.io/typegoose/docs/api/virtuals#virtual-populate) also explain it)

**Comment by cityvoice** [comment]
Okay, I’ll take a try, very thanks.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月12日 19:49
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Automattic/mongoose] how to do if using Number refs instead of ObjectId as refs when using populate method (Issue #13017)


There is a question that has always bothered me how does mongoose know the childrens fileld refers to _id instead of other number type field?

because from what i know it is statically set to the property _id, if you want it based on another field, you may wanna look at Virtual Populate<https://mongoosejs.com/docs/populate.html#populate-virtuals> (or in terms of something similar to nestjs, the typegoose docs Virtual Populate<https://typegoose.github.io/typegoose/docs/api/virtuals#virtual-populate> also explain it)

―
