### ISSUE TITLE
Passing "Human" as model name creates the collection as "Humen"

### ISSUE THREAD

**Issue by ahmetselimkaraca** [Automattic/mongoose#13037]
### Prerequisites

- [X] I have searched existing issues to ensure the bug has not already been reported

- [X] I have written a descriptive issue title

### Mongoose version

6.9.1

### Node.js version

18.13.0

### MongoDB server version

6.0.4

### Description

When pluralizing the collection name, mongoose sets it to "Humen". Plural for human is not humen, it's not a real word. The correct plural form is "Humans".

### Steps to Reproduce

Simply naming passing "Human" to the model function results in this bug. (`const Human = mongoose.model("Human", humanSchema);`). 

### Expected Behavior

Should be set to "Humans" instead.

**Comment by Uzlopak** [comment]
Political Correct would be people. ;)
Tbh. It was bad to integrate pluralization into mongoose the first place. You can override the collectionname in the model confuguration.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Human = mongoose.model('Human', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const collections = mongoose.connection.collections;
  Object.keys(collections).forEach(entry => {
    console.log(entry);
    console.log(mongoose.connection.collections[entry].name)
  });
}

run();
```

**Comment by Uzlopak** [comment]
We can only fix pluralization issues with major version bump.
