### ISSUE TITLE
Mongoose Model find function taking longer than MongoDB Response time

### ISSUE THREAD

**Issue by jdhubilo** [Automattic/mongoose#13035]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.12.4

### Node.js version

14.x

### MongoDB version

5.0

### Operating system

Linux

### Issue

This is my implementation using Mongoose for `find` method
We are scanning : 2600+ documents

```
import abcModel from '@models/abc.model';

let query = {
    event_id: 123
}

let projection = {
  'field1': 1,
  'field2': 1,
  'field3': 1,
}

console.time('QUERY_TIME')
this.model.find(query, projection, {lean: true});
console.timeEND('QUERY_TIME')
```
**QUERY_TIME : 736.091 ms**

When running the raw query in mongo CLI:
**executionTimeMillis : 11ms**

How can Fetching records time has so much difference when using MongoDB & while using MongoDB ? Is there anything I am missing here ?

**Comment by sohaibMan** [comment]
did you try to create an index on event_id ? if not you should create one to avoid full collection scan

**Comment by vkarpov15** [comment]
@jdhubilo try using [lean](https://mongoosejs.com/docs/tutorials/lean.html), that skips Mongoose hydration, which can make a huge performance difference if you have large documents.
