### ISSUE TITLE
Connecting to local MongoDb from a Docker container fails in any 6.x.x versions

### ISSUE THREAD

**Issue by sonnyk22** [Automattic/mongoose#13048]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.1

### Node.js version

16.13.2

### MongoDB version

4.0.5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10 Pro (OS Build: 19044.1645)

### Issue

Team,

By using `host.docker.internal` as the `host` value within a Docker Container; up to version **5.12.7** it works beautifully to connect to my local MongoDb (outside of Container), however, it fails to connect at any versions above that, including 6.x.x.   

Here is sample code snippet:

    open(mongoose, callback) {        
        const options = {
            // useMongoClient: true,      // <-- no longer necessary
            // useNewUrlParser: true,     // <-- no longer necessary
            // useUnifiedTopology: true,  // <-- no longer necessary
            promiseLibrary: global.Promise  // <-- not sure if its needed in 6.x.x; works fine in 5.12.7
        };

        const env = process.env.MICRO_SVC_ENV,
              dockerLocalHost = 'host.docker.internal',
              connStr = `mongodb://${dockerLocalHost}:27017/someDb`;

        mongoose.connect(connStr, options, (err) => {
            if (err) {
                console.error(`${logPrefix} Open(${env}). Mongoose.Connect() failed:`, err);
                return;
            }

            console.log(`${logPrefix} Open(${env}). CONNECTED to MongoDB.`);
        });
        /// rest of code....

Does anyone know if the new versions of mongoose has disabled this feature, or may be I am missing an extra options setting when connecting?

**Comment by Pr0dt0s** [comment]
The connection is trying to use the server´s configured listening ip (127.0.0.1) unsuccessfully since that points to the loopback interface inside the docker container.

Setting the option ```directConnection: true``` to force the use of the host in the connection string seem to solve this issue.

**Comment by sonnyk22** [comment]
Fantastic!  Your great solution worked out perfectly; thank you.  Closing this ticket.
