### ISSUE TITLE
Getters are not executed automatically with Express' res.json()

### ISSUE THREAD

**Issue by imageck** [Automattic/mongoose#13049]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.0

### Node.js version

18.13.0

### MongoDB server version

5.0.14

### Description

The [documentation](https://mongoosejs.com/docs/tutorials/getters-setters.html) mentions:

> By default, Mongoose executes getters when converting a document to JSON, including [Express' res.json() function](http://expressjs.com/en/4x/api.html#res.json).

However, it doesn't seem to be the case with `find()` (not sure about other methods).

### Steps to Reproduce

 I have some numeric keys in my schema, e.g.:
```javascript
  num1: {
    type: Schema.Types.Decimal128,
    get: n => n.toString()
  },
```
and my controller function:
```javascript
async function getCollectionItems(req, res) {
  let { id } = req.params;
  try {
    let items = await Item.find()
      .where('collectionId').equals(id)
      .exec();
    res.status(200).json(items);
  } catch(err) {
    res.sendStatus(500);
  }
```
On the front-end, a nested object is received:
```javascript
[{... ,"num1":{"$numberDecimal":"123.45"}, ...}]
```

### Expected Behavior

One would expect the getter is executed at the time of conversion to JSON but for some reason it's not, unless the `toJSON.getters` option is explicitly set to `true`:
```javascript
  const Decimal = mongoose.model("Decimal", new mongoose.Schema({
    num1: {
      type: mongoose.Schema.Types.Decimal128,
      get: n => n.toString()
    },  
  }, { toJSON: { getters: true } }));

  const dec1 = await Decimal.create({
    num1: 123.45,
  }); 
  let decimals = await Decimal.find().exec();
  console.log(JSON.stringify(decimals));
// [{"_id":"63f10eb9a1a7e4ed6174dd61","num1":"123.45","__v":0,"id":"63f10eb9a1a7e4ed6174dd61"}]
```

So it's one of the three:

1. I'm doing something wrong;
2. The documentation is misleading;
3. There is a bug;

**Comment by imageck** [comment]
Did another test on the real project and yep, I can confidently say that I'm not doing something wrong. Explicitly setting `getters: true` works. So it's one of the last two :stuck_out_tongue:

**Comment by vkarpov15** [comment]
You're right, this is an issue in our docs. I'm sorry for the trouble, and thanks for pointing this out. You can work around this with `mongoose.set('toJSON', { getters: true })`.

**Comment by imageck** [comment]
Oh, there was no trouble, just slight confusion.

Thank you for looking into this.
