### ISSUE TITLE
How to effectively use the same open mongoose connection across process(created using pm2) and pods?

### ISSUE THREAD

**Issue by Vinayjinugu-gep** [Automattic/mongoose#13041]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.3

### Node.js version

16.14

### MongoDB version

4.8.1

### Operating system

None

### Issue

I have open a mongoose connection in a single process. Since we have multiple clients. We have to open multiple connections for a single process. We are storing the opened connections and reusing them if the request is from the same client.

For suppose I have 10 open connections in a process. If I have X process running and there are Y pods running. 
The total of number of open connections that I store are **10 *( X * Y)**

Is there a way to share the open mongoose connection across process and pods. So I can bring down the connections open to 10?. 
I tried to use redis cache but it can only store strings. I tried stringifying the connection and parsing it but the types/clasess are lost in transition. 
I tried using [flatted,](https://www.npmjs.com/package/flatted) [circular-json](https://www.npmjs.com/package/circular-json) npm packages to stringify and parse the connection but it didn't preserve the values.

Is there any other effective way to bring down the open connections?

**Comment by vkarpov15** [comment]
Your only option to reduce the number of open connections is to reduce the number of connections per process currently. There's no way to share an open connection between processes.
