### ISSUE TITLE
Removing multiple sub documents correct way

### ISSUE THREAD

**Issue by wclr** [Automattic/mongoose#1305]
First I tried the first way:

<pre><code>
item.tasks.forEach(function(task){
            if (task.finished)
                tasks.remove(task)
})

item.save() 
</code></pre>

but after that I have NOT ALL finished task where deleted.

Then I did with async saving item after each sub doc remove:

<pre><code>
        var tasksToRemove= [];
        tasks.forEach(function(task){
            if (task.finished)
                tasksToRemove.push(task)
        })

        async.mapSeries(tasksToRemove, function(task, callback){
            console.log('Removing finished tasks: remove task', task._id )
            tasks.remove(task)
            item.save(function(err){
                callback(err)
            })
        }, function(err){
            
        })
</code></pre>

All tasks where deleted from DB.

What is the issue with first way of removing sub docs?

**Comment by manavrajvanshi** [comment]
Thank you!
