### ISSUE TITLE
Filter query based on a sub-document's field - dot notation doesn't work here

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#13051]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.2

### Node.js version

18.12.1

### MongoDB version

6.0.4

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I use Mongoose with Nest.js here. There are two schemas called `Reward` and `Reservation`. `Reservation` has a reference of `Reward`. I expect to filter the query like `reservationModel.find({'reward.key':'something'});` but it doesn't work. I tried aggregation too. Remember both schemas are actually collections.

#### Reservation
```typescript
export type ReservationDocument = HydratedDocument<Reservation, ReservationMethodsAndOverrides, ReservationVirtuals>;

@Schema({
  versionKey: '_v',
  toObject: { virtuals: true },
})
export class Reservation {
  @Prop({
    type: MongooseSchema.Types.ObjectId,
    ref: Reward.name,
  })
  reward: PopulatedDoc<RewardDocument>;

  constructor(partial: Partial<Reservation>) {
    Object.assign(this, partial);
  }
}

export const ReservationSchema = SchemaFactory.createForClass(Reservation);
```
#### Reward
```typescript
export type RewardDocument = HydratedDocument<Reward, RewardMethodsAndOverrides, RewardVirtuals>;

@Schema({
  versionKey: '_v',
  toObject: { virtuals: true },
})
export class Reward {
  @Prop()
  key: string;

  constructor(partial: Partial<Reward>) {
    Object.assign(this, partial);
  }
}

export const RewardSchema = SchemaFactory.createForClass(Reward);
```

This returns nothing:
```typescript
await this.reservationModel
      .find(
        {
          'reward.key': 'something',
        }
      )
      .populate<{ reward: RewardDocument }>([
        'reward',
      ]).exec();

**Comment by vkarpov15** [comment]
That's not something Mongoose supports. You'll have to use aggregation with `$lookup`: https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-lookup-expr.
