### ISSUE TITLE
post find hook with regEx /^find/,  use model, Object or array in populate and error handling 

### ISSUE THREAD

**Issue by jj-devs** [Automattic/mongoose#13069]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.3.3

### Node.js version

19.5

### MongoDB version

4.4.18 Community

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro Linux 5.15.91-1

### Issue

Hello, I have a query ready that obtains from a document prices and specific data based on the array of `_id`'s from another document. So far it does what it should do. I read in the documentation that `find` returns an array of objects regardless of the number of documents, `findById/Delete/Update` returns model, unlike if you use `lean` in both cases, but for post hook find, in cases of performance or problems with the data types, could you guide me if this is recommended or is it recommended to handle the populate after each `find` or `findById` (not update/delete) and not in hook.

**This is my schema base:**
```JavaScript
const bUnitSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "La unidad de negocio debe tener un nombre"],
      unique: [true, "La unidad de negocio debe ser unico"],
      trim: true,
    },
    menuItem: [
      {
        product: {
          type: mongoose.Schema.ObjectId,
          required: [true, "El producto es requerido"],
          ref: "menuitems",
        },
        store: {
          type: mongoose.Schema.ObjectId,
          ref: "stores",
          _id: false,
        },
       
      },
    ]

..OTHER IRRELEVANT FIELDS
```
This is my mongoose schema for `populate`:
```JavaScript
const menuItemSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, "El producto debe tener un nombre"],
    unique: [true, "El nombre del producto deber ser unico"],
    trim: true,
  },
  storeId: [
    {
      store: {
        type: mongoose.Schema.ObjectId,
        ref: "stores",
        _id: false,
      },
      hasDelivery: {
        type: Boolean,
        default: true,
      },
      hasExistence: {
        type: Boolean,
        default: true,
      },
      price: {
        type: Number,
        default: 0,
        min: [0, "El precio del producto debe ser mayor a 0"],
        max: [10000, "El precio del producto debe ser menor de 10001"],
      },
      microsId: {
        type: Number,
        min: [0, "El ID de micros debe ser mayor a 0"],
      },
    },
  ],
..OTHER IRRELEVANT FIELDS
```
And this is the hook:
 ```JavaScript
bUnitSchema.post(/^find/, async function (docs) {
  // ---------------------- using objects
  if (docs instanceof mongoose.Document) {
    const entries = Object.entries(docs.menuItem);
    for (const [key, { store }] of entries) {
      await docs.populate({
        path: "menuItem.product",
        select: {
          image: 1,
          imagePath: 1,
          plateFor: 1,
          description: 1,
          name: 1,
          _id: 1,
          "storeId.$": 1,
        },
        match: {
          "storeId.store": store,
        },
      });
    }
  } else {
    // --------------------- using arrays
    for (let doc of docs) {
      for (let store of doc.menuItem) {
        // console.log(doc);
        await doc.populate({
          path: "menuItem.product",
          select: {
            image: 1,
            imagePath: 1,
            plateFor: 1,
            description: 1,
            name: 1,
            _id: 1,
            "storeId.$": 1,
          },
          match: {
            "storeId.store": store.store,
          },
        });
      }
    }
  }
});
```

Here I have a problem and I didn't find why yet, when I use the **error handler** with the parameters (**err,docs,next)** 'populate' no longer works and I don't know why it seems to no longer follow the post hook, but when I throw errors it does catch but not the document returned by the query.

1. Could you help me why this happens?
2. Could you guide me if this is recommended or is it recommended to handle the `populate` after each `find` or `findById` (not update/delete).

Thanks!!

**Comment by vkarpov15** [comment]
Can you please clarify what you mean by "use the error handler 'populate' no longer works" - what does your error handler code look like, what is the observed behavior, and what is the behavior you expect?

My best guess as to the issue you're seeing is that error handlers don't get the query results as a parameter, because there's no query results. If there's an error in the query, then the query will throw an error rather than returning results.

On a related note, if you want to automatically populate certain fields, you should consider using [mongoose-autopopulate](http://npmjs.com/package/mongoose-autopopulate) rather than implementing it yourself.

**Comment by jj-devs** [comment]
Thanks, I'll try the plugin and sure, here is what i do:

**Here it catches the errors correctly and shows me the message that i want to send**

```Javascript
bUnitSchema.post(/^find/, async function (err, docs, next) {
  console.log(err);
  console.log(docs);
  if (err) next();
  // ---------------------- using objects
  if (docs instanceof mongoose.Document) {
    const entries = Object.entries(docs.menuItem);
    for (const [key, { store }] of entries) {
      await docs.populate({
        path: "menuItem.product",
        select: {
          image: 1,
          imagePath: 1,
          plateFor: 1,
          description: 1,
          name: 1,
          _id: 1,
          "storeId.$": 1,
        },
        match: {
          "storeId.store": store,
        },
      });
    }
  } else {
    // --------------------- using arrays
    for (let doc of docs) {
      for (let store of doc.menuItem) {
        // console.log(doc);
        await doc.populate({
          path: "menuItem.product",
          select: {
            image: 1,
            imagePath: 1,
            plateFor: 1,
            description: 1,
            name: 1,
            _id: 1,
            "storeId.$": 1,
          },
          match: {
            "storeId.store": store.store,
          },
        });
      }
    }
  }
});
```

**Output:**
```
AppError: La unidad de negocio con el id seleccionado no existe
  status: 'fail',
  isOperational: true
```

**If i have no error in the query this is what i have:**
```Javascript
 "_id": "63f50c7e9d387b9079e35b56",
                "name": "Hotel Resort",
                "menuItem": [
                    {
                        "product": "63c5af7f768ac1fbed1e045d",
                        "store": "62a811d1af67f5415770f297",
                        "price": 425,
                        "_id": "63f50c7e9d387b9079e35b57"
                    }
                ],
```

**But this is what i want, looks like the populate doesn't work or something like im not doing well**
```Javascript
                "_id": "63f50c7e9d387b9079e35b56",
                "name": "Hotel Resort",
                "menuItem": [
                    {
                        "product": {
                            "_id": "63c5af7f768ac1fbed1e045d",
                            "name": "Appetizer Sampler",
                            "storeId": [
                                {
                                    "store": "62a811d1af67f5415770f297",
                                    "hasDelivery": true,
                                    "hasExistence": true,
                                    "price": 425,
                                    "_id": "63c5dbf3768ac1fbed1e07fd"
                                }
                            ],
```

**This only work when i remove the `err`, and `next` parameters in the middleware**

`bUnitSchema.post(/^find/, async function (docs) `

**Comment by vkarpov15** [comment]
That's expected. Error handling middleware _only_ executes when there's an error. If `find()` succeeds, Mongoose will not execute error handling middleware. From the [error handling middleware docs](https://mongoosejs.com/docs/middleware.html#error-handling-middleware).

![image](https://user-images.githubusercontent.com/1620265/220948263-8e1d47ce-0a9c-404a-847a-68280e9c5546.png)

We'll add a little extra to the error handling middleware docs to clarify that error handling middleware does not execute if there's no error.

**Comment by jj-devs** [comment]
Yes, thanks and if I have the expected result when there is an error, but if there is no error then the `find` should do its job with `populate`, but it doesn't do it as I mentioned. Only works the `populate` if i change `(err,docs,next)` for `(docs)` only in the hook.
What I was saying about the error handler is that when I have more parameters in the callback, populate doesn't do its job or doesn't seem to.

**Comment by jj-devs** [comment]
Yes, but i dont have any error, find return the query, but the populate in the hook dont work anymore if i use 3 parameters in callback

**Comment by LilXhan** [comment]
I have an error when I want to connect the user and playlist tables and when I want to show the populate data in the way the user tells me with his playlists, nothing appears. Here I leave my code and what I send by postman: 

> app.js
```javascript
import express from 'express';
import connect from './connect.js';
import { User, Playlist } from './user.js';

connect();

const app = express();

app.use(express.json());

app.get('/api/v1/playlist', async (req, res) => {
	const playlist = await Playlist.find().populate('owner');
	
	res.json(playlist)
})

app.post('/api/v1/playlist', async (req, res) => {
	const data = req.body;
	const ownerId = data.owner;
	const playlist = new Playlist(data);
	playlist.owner = ownerId;
	await playlist.save();
	res.json(playlist)
})

app.get('/api/v1/users', async (req, res) => {
	const users = await User.find().populate('playlistsList');
	res.json(users)
})

app.post('/api/v1/users', async (req, res) => {
	const data = req.body;
	const user = new User(data);
	await user.save();
	res.json(user)
})

app.listen(3000, () => {
	console.log('Server running at http://localhost:3000')
});
```

> models.js

```javascript
import {Schema, model} from 'mongoose';

const userSchema = new Schema({
	name: {type: String, require: false},
	playlistsList: [{type: Schema.Types.ObjectId, ref: 'Playlist'}]
});

const playlistSchema = new Schema({
	name: {type: String, require: false},
	owner: {type: Schema.Types.ObjectId, ref: 'User'}
})
  
export const Playlist = model('Playlist', playlistSchema);

export const User = model('User', userSchema);
```

 > connect.js
```javascript 
import mongoose from "mongoose";

const connect = () => {
	mongoose.Promise = global.Promise;
	mongoose.connect("mongodb://root:root@localhost:27017/crud-silabuz?authSource=admin",
	{
	useNewUrlParser: true,
	useUnifiedTopology: true,
	}
	);
	const db = mongoose.connection;
	db.on("error", (error) => console.error(error));
	db.once("open", () => console.log("Connected to Database"));
};

export default connect;
```

when creating my user and playlist I use this respectively 

```json
{
	"name": "flavio",
	"playlists": []
}
```

```json
{
	"name": "2222",
	"owner": "64092fb3da7bec2a8de44c15"
}
```

I recieve this:

```json
{
	"_id": "64092fb3da7bec2a8de44c15",
	"name": "testt",
	"userPlaylists": [],
	"__v": 0
}
```

when creating my user and playlist I use this respectively

**Comment by vkarpov15** [comment]
As far as I can tell, the issue is due to you populating in error handling middleware, which isn't something that you should do, because Mongoose doesn't call error handling middleware unless there's an error.
