### ISSUE TITLE
validation ignored if the path set as 'select: false'

### ISSUE THREAD

**Issue by ryan1au** [Automattic/mongoose#13062]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Related Issue:
#730
[https://github.com/Automattic/mongoose/issues/730](issue 730)

```
...
const User = mongoose.model('User', Schema({
  name: { type: String, required: true },
  age: { type: Number, required: true, **select:false** }
});
// set user's name and age
// user={name:'Ben',age:16}
...
// then update and save in this way
const user=await User.findOne({name}); // user={name:'Ben'}
// do some work
...
await user.save(); // does not run validation on 'age'
...
```

At most time, before doc.save(), validation will run. But if select option set to false on some path, it does not run validation on that path even there's a required validator until select set to true. This idea may come from #730. That's reasonable enough.

But it's so sad that this rationale **cannot be searched on the documentation**. I only found it in source code, around line 2610:
![image](https://user-images.githubusercontent.com/30694608/220370367-5535761e-bc3a-49bc-b034-b36cf759c002.png)

I just thought full validation will run rather than select option determines. It wasted some time.
So, for making more lives much easier, I think this rule should be added to the documentation directly and explicitly, at least a warning item of rules on validation ;)

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: { type: String, required: true },
  age: { type: Number, required: true, select: false }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson',
    age: 0
  });

  const doc = await Test.findOne();
  doc.age = null;
  doc.name = 'Test';
  await doc.save();
  console.log('done');
}

run();
```

**Comment by ryan1au** [comment]
```
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: { type: String, required: true },
  age: { type: Number, required: true, select: false },
  links: { type: String, required: true, select: false }
});

testSchema.pre('save', function() {
  **this.links = undefined;**
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson',
    age: 0,
    **links: 'some init links'**
  });

  const doc = await Test.findOne(); // error occur: .select('+links');
  
  doc.name = 'Test';
  **await doc.save();**
  console.log('done');
}
run();
```
"links" set to undefined manually in pre save middleware, but finally there is no error. When you turn on select option, then error occur as expected. 

Maybe it's a very weird usage situation above but actually the most interesting thing I see are just:
1) validation happens at a very first time among pre save middlewares.
2) the select option does determine validation paths list, which is difficult for beginners to realize though.

> The following script throws an error as expected. Please modify the below script to demonstrate the issue you're seeing.
> 
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>   name: { type: String, required: true },
>   age: { type: Number, required: true, select: false }
> });
> 
> const Test = mongoose.model('Test', testSchema);
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017');
>   await mongoose.connection.dropDatabase();
> 
>   await Test.create({
>     name: 'Test Testerson',
>     age: 0
>   });
> 
>   const doc = await Test.findOne();
>   doc.age = null;
>   doc.name = 'Test';
>   await doc.save();
>   console.log('done');
> }
> 
> run();
> ```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: { type: String, required: true },
  age: { type: Number, required: true, select: false },
  links: { type: String, required: true, select: false }
});

testSchema.pre('save', function() {
  this.links = undefined;
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson',
    age: 0,
    links: 'some init links'
  });

  const doc = await Test.findOne(); // error occur: .select('+links');
  
  doc.name = 'Test';
  await doc.save();
  console.log('what is doc', doc);
  console.log('done');
}
run();
```
