### ISSUE TITLE
NextJS prerendering error

### ISSUE THREAD

**Issue by wouter-deen** [Automattic/mongoose#13068]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.1

### Node.js version

18.12.1

### MongoDB server version

6.0

### Typescript version (if applicable)

4.9.4

### Description

While building my NextJS code, some pages are using SSR (more specifically, ISR) and while prerendering those pages, I got a one-off `MissingSchemaError` that I haven't encountered before while prerendering. I tried building my project again, and it worked just fine. So I have a feeling that this might be a bug with Mongoose.

Full error:
```
Error occurred prerendering page "/nl/topic/63cbde14a2eaa8a0ccaa17da". Read more: https://nextjs.org/docs/messages/prerender-error
--
21:12:51.121 | MissingSchemaError: Schema hasn't been registered for model "course".
21:12:51.121 | Use mongoose.model(name, schema)
21:12:51.121 | at Connection.model (/vercel/path0/node_modules/mongoose/lib/connection.js:1237:13)
21:12:51.121 | at _getModelFromConn (/vercel/path0/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:580:15)
21:12:51.123 | at addModelNamesToMap (/vercel/path0/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:508:17)
21:12:51.124 | at getModelsMapForPopulate (/vercel/path0/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:198:7)
21:12:51.124 | at populate (/vercel/path0/node_modules/mongoose/lib/model.js:4731:21)
21:12:51.124 | at _populate (/vercel/path0/node_modules/mongoose/lib/model.js:4691:5)
21:12:51.124 | at /vercel/path0/node_modules/mongoose/lib/model.js:4668:5
21:12:51.124 | at promiseOrCallback (/vercel/path0/node_modules/mongoose/lib/helpers/promiseOrCallback.js:11:14)
21:12:51.124 | at Mongoose._promiseOrCallback (/vercel/path0/node_modules/mongoose/lib/index.js:1262:10)
21:12:51.124 | at Model.populate (/vercel/path0/node_modules/mongoose/lib/model.js:4666:23)
```

### Steps to Reproduce

You can reproduce this error by building a NextJS application that utilizes SSR by using `getStaticProps()`. My code:
```tsx
export async function getStaticProps({ params }) {
  await connectToDB();
  const topic: Topic = await TopicModel.findOne({"_id": params.topicId})
    .select("displayName course")
    .populate("course", "displayName")
    .exec();

  return {
    props: {
      basicInfo: {
        displayName: topic.displayName,
        courseDisplayName: topic.course.displayName
      }
    },
    revalidate: 60
  }
}
```

### Expected Behavior

Prerendering without any error.

**Comment by vkarpov15** [comment]
What does `connectToDB()` look like?

**Comment by wouter-deen** [comment]
> What does `connectToDB()` look like? Also, what do your schema definitions for `TopicModel`, `CourseModel`, etc. look like?

### File `connect.ts`
```ts
import mongoose, {connect as mongooseConnect} from "mongoose";

export default async function connectToDB() {
  const username = process.env.MONGODB_USERNAME;
  const password = process.env.MONGODB_PASSWORD;
  const instance = process.env.NEXT_PUBLIC_INSTANCE_NAME;
  const subdomain = process.env.MONGODB_SUBDOMAIN
  const uri = `mongodb+srv://${username}:${password}@${instance}.${subdomain}.mongodb.net/main?retryWrites=true&w=majority`
  mongoose.set('strictQuery', false);
  await mongooseConnect(uri);
}
```

**Comment by wouter-deen** [comment]
While reading through the error more carefully, I have a feeling that it has something to do with the population of the `course` field. The corresponding model for this is the `course` model, and this model is not registered at that point, since it is not directly used. The course model is exported using the following line:
```ts
export default createModel<Course, CourseModel>("course", courseSchema);
```
Would there be any way to make sure that this model gets registered, without actually calling any method on it?

**Comment by vkarpov15** [comment]
How are you importing the file that does `createModel()`? You can always import that file in the same file that you have `getStaticProps` in.

**Comment by wouter-deen** [comment]
I did that and just creating an empty `new CourseModel();` fixed it for me.
