### ISSUE TITLE
Investigate Deno connecting to Atlas

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#13075]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

See https://github.com/denoland/deno/issues/15824#issuecomment-1439802080

**Comment by SkepticMystic** [comment]
I still get this issue..
I'm using `npm:mongoose@^7.4.4`, connecting to an Atlas cluster.
Both with and without `--unstable`, the connection times-out.
Is there something else I can try?

**Comment by vkarpov15** [comment]
@SkepticMystic please open a new issue and follow the issue template
