### ISSUE TITLE
Validation error when using transaction with model#create

### ISSUE THREAD

**Issue by mazenkhalil** [Automattic/mongoose#13073]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.2

### Node.js version

16

### MongoDB server version

5

### Description

Validation error thrown when using transaction with model#create static method.

### Steps to Reproduce

```javascript
const schema = new Schema(
  {
    code: { type: String, required: true, immutable: true, unique: true, minlength: 3, uppercase: true },
    displayName: { type: String, required: true }
  }
);

type User = InferSchemaType<typeof schema>;

const UserModel = mongoose.model('User', schema);

// ----------------------

const user = {code: 'UA', displayName: 'User1'}

UserModel.startSession((session) => {
      
    // User created with validation error thrown 
    return UserModel.create(user, { session: session });
      
    // User created without any issue
    return new UserModel(user, { session: session }).save();
  });. 
```

Validation Error:
```
{
   "errors":    {
      "displayName":       {
         "name": "ValidatorError",
         "message": "Path `displayName` is required.",
         "properties":          {
            "message": "Path `displayName` is required.",
            "type": "required",
            "path": "displayName"
         },
         "kind": "required",
         "path": "displayName"
      },
      "code":       {
         "name": "ValidatorError",
         "message": "Path `code` is required.",
         "properties":          {
            "message": "Path `code` is required.",
            "type": "required",
            "path": "code"
         },
         "kind": "required",
         "path": "code"
      }
   },
   "_message": "User validation failed",
   "name": "ValidationError",
   "message": "User validation failed: displayName: Path `displayName` is required., code: Path `code` is required."
}
```

**Comment by mazenkhalil** [comment]
Either it was caching issue or something else. I will reopen it if I found the exact reproduction steps.

**Comment by yoitsro** [comment]
We've just come across this and it definitely tied to when a session is passed in to the create call. Any ideas @vkarpov15?

**Comment by vkarpov15** [comment]
@yoitsro can you please open a new issue and follow the issue template?

**Comment by yoitsro** [comment]
Hey @vkarpov15. Thanks for your reply.

It turns out this was because of the slightly unintuitive interface of `.create()` where each parameter is expected to be an object to be created, unlike most other model methods.

It would appear that was the way @mazenkhalil was also trying to use it in the example above.
