### ISSUE TITLE
[7.0] Update report

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#13072]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

This is a report on problems updating to mongoose 7.0 in typegoose currently

- `mongoose.Model` does not exist anymore, so `model instanceof mongoose.Model` is not valid anymore (and `mongoose.ModelClass` does not exist at runtime from my knowledge), also see https://github.com/Automattic/mongoose/pull/12935#issuecomment-1439893252
- `Model.countDocuments`'s `filter` parameter is now required - this is a side-effect of the second overload with only the callback being removed and `filter` not made optional in the first overload
- `HydratedDocument<any, any>` now results in type `any` instead of the previous `HydratedDocument<TODO, TODO>`, workaround is to use `HydratedDocument<unknown, unknown>`

Separate issues, that will be the result of mongoose removing "long standing" things:

- plugins that use `base.Promise` now throw a TypeError (example `mongoose-findorcreate`), see [this line](https://github.com/drudge/mongoose-findorcreate/blob/master/index.js#L11)
- existing plugins (like `mongoose-findorcreate`) will now error because they use callbacks (see [this issue](https://github.com/drudge/mongoose-findorcreate/issues/34))

Also as noted in [this comment](https://github.com/Automattic/mongoose/pull/12935#issuecomment-1439890622) the change for `class Model` -> `interface Model` has not been documented in the migration guide yet

[Typegoose Compare](https://github.com/typegoose/typegoose/compare/abf661bc44236cc6155d877eb1592f613545e705..6e92266a98c6fb1aacfb01a930b5f08bbafc766e)

Note: anyone can use this issue to report on how the upgrade to 7.0 went, i would keep this issue open until 7.0 is released

**Comment by vkarpov15** [comment]
Thanks for the feedback. I think we can undo (1) and (2). Any suggestions on what Mongoose can do about (3), `HydratedDocument<any, any>` ?

As for plugins not working, we can either put in PRs to fix plugins, or consider maintaining a fork of certain plugins. For example, I wouldn't be opposed to adding an officially supported replacement for `mongoose-findorcreate` if we aren't able to get a PR in.

**Comment by hasezoey** [comment]
> Any suggestions on what Mongoose can do about (3), HydratedDocument<any, any> ?

i dont really know, but just had it noted as something i encountered so i noted it down

**Comment by hasezoey** [comment]
which commit / PR addressed the Model / ModelClass thing?

**Comment by vkarpov15** [comment]
@hasezoey https://github.com/Automattic/mongoose/commit/5afbe372df66cddd5f082cc10c2635f7c007d1f9
