### ISSUE TITLE
How to use reconnectTries and reconnectInterval options with v6.9.2

### ISSUE THREAD

**Issue by mr-mad-e** [Automattic/mongoose#13071]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.2

### Node.js version

16.x

### MongoDB version

4

### Operating system

Linux

### Issue

Not able to use reconnectTries and reconnectInterval options in latest version.

Is there any alternate way to use it?

Why it is removed? didn't mention in [migration guide](https://mongoosejs.com/docs/migrating_to_6.html)

What is the default value for these options?

**Comment by vkarpov15** [comment]
These options were removed in Mongoose 6. They're no longer necessary: the MongoDB node driver will always attempt to retry any operation for up to `serverSelectionTimeoutMS`, even if MongoDB is down for a long period of time. It will never end up in a state where it ran out of retries and will never try to reconnect to MongoDB.

We'll make a note of this in our docs.

**Comment by mr-mad-e** [comment]
@vkarpov15, thanks for the update
