### ISSUE TITLE
Docs: Official Document shows that Model.findOne() accepts callback but Mongoose throws an error that callback is no longer accepted.

### ISSUE THREAD

**Issue by Arghyahub** [Automattic/mongoose#13095]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The official documentation shows that Model.findOne() accepts callbacks : 
![Official Document](https://user-images.githubusercontent.com/84245432/221880545-0bd8c374-f97a-4796-a354-d9c4f67f1a99.jpg)

But when I try to use it, an error is thrown : 
![FindOne removed](https://user-images.githubusercontent.com/84245432/221880675-7b35e118-c12a-4fef-99df-ad2f048e3d54.jpg)

Mongoose Version 7.0.0
Mongodb  Version v6.0.4

**Comment by Arghyahub** [comment]
If I'm correct about the issue, kindly assign me this issue. I've started working on the project locally.

**Comment by vkarpov15** [comment]
You're correct, this is a bug in our docs. You can put in a PR if you're willing, otherwise we're happy to fix it

**Comment by Arghyahub** [comment]
The PR fixes the issue🙂. This is my first PR and I am happy to contribute to Mongoose.
