### ISSUE TITLE
MongoDb Serverless cluster with mongoose

### ISSUE THREAD

**Issue by Ismola** [Automattic/mongoose#13093]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

12.22.12

### Node.js version

12.22.12

### MongoDB version

6.10.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I\`m trying to change a M2 shared cluster in MongoDB to  a serverless cluster. My node version is 12.22.12 and my mongoose version is mongoose@6.10.0. My connection string is:

```
mongodb+srv://:<password>@<cluster-url>/<database>?retryWrites=true&w=majority&authSource=admin
```

When i make the connection to my databse i get this error:

```` MongoParseError: Text record must only set `authSource` or `replicaSet` ````

My connection function:

```
// Connect to MongoDB
const mongoUrl = MONGODB_URI;
mongoose.Promise = bluebird;
mongoose.set('strictQuery', true);
mongoose.connect(mongoUrl, {
    useNewUrlParser: true,
    useUnifiedTopology: true
}).then(
    () => { /** ready to use. The `mongoose.connect()` promise resolves to undefined. */
    },
).catch(err => {
    console.log("MongoDB connection error. Please make sure MongoDB is running. " + err);
    // process.exit();
});
```

Really, mi node version is 10.19.0 and my mongoose version is (5.9.15) but i changed this version to 12.22.12 to use a mongoose version most recent(6.10.0).

I do this because mongoose version 5.9.15 is not compatible with serverless cluster

Doing this, y have this error

**Comment by vkarpov15** [comment]
Try removing authSource? You typically don't need that when connecting to Atlas

**Comment by AdamK222** [comment]
Hi, I want to switch to serverless version of mongoDB. Is mongoose 6.8.1 fully supporting serverless version ?
