### ISSUE TITLE
Mongoose 7 - LeanDocument replacement

### ISSUE THREAD

**Issue by meabed** [Automattic/mongoose#13101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Since the LeanDocument typing has been removed in V7, what is the replacement for the LeanDocument type in mongoose 7? 

For example:  the result of model.findOne({}).json() or model.findOne({}).lean() ?

is it HyderatedDocument or something else?

Thank you

**Comment by aksdevac** [comment]
See the guide:
https://mongoosejs.com/docs/migrating_to_7.html#typescript-specific-changes

**Comment by vkarpov15** [comment]
The raw doc type as passed in to `mongoose.model<DocType>`, or inferred from the schema.

In 7.0, Mongoose no longer supports passing a DocType that `extends Document` into `mongoose.model<DocType>`. So `Model.findOne().lean()` will just return `Promise<DocType>` and make no effort to strip out document methods. It isn't possible to extract the raw document type (the document type without any document helpers) if your DocType `extends Document` in general, so Mongoose 7 drops support for that.

You can read more on the Mongoose 7 migration guide: https://mongoosejs.com/docs/migrating_to_7.html#typescript-specific-changes and our guide to defining schemas in TypeScript: https://mongoosejs.com/docs/typescript/schemas.html

**Comment by heiba** [comment]
@vkarpov15 Can we have more clarity and examples showing how to replace LeanDocument

[The documentation here](https://mongoosejs.com/docs/migrating_to_7.html#typescript-specific-changes) doesn't show an example of how to replace LeanDocument. Ideally, an example illustrating before and after would be great.

**Comment by aksdevac** [comment]
Not 100% sure, but I think code will be same as only return type of .lean() is changed (breaking change), 
in most cases before & after code will be same as by default typescript will use type inference.

**Comment by vkarpov15** [comment]
@heiba can you provide an example of how you're using LeanDocument?
