### ISSUE TITLE
[bug] mongoose v7 `countDocuments` throws error `Query.prototype.countdocuments() no longer accepts a callback` if you use it with `lean().exec()`

### ISSUE THREAD

**Issue by titanism** [Automattic/mongoose#13104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x.x

### Node.js version

16.x

### MongoDB server version

4.x|5.x|6.x

### Description

Just passing this along - we should probably warn people about this:

You will get a `Query.prototype.countdocuments() no longer accepts a callback` error if you use `.lean()` or `.exec()` with `countDocuments`.

### Steps to Reproduce

```js
const count = await model.countDocuments({}).exec();
// or
const count = await model.countDocuments({}).lean().exec();
```

### Expected Behavior

It shouldn't throw (for maximum backwards compatibility upgrading to v7.x).

**Comment by vkarpov15** [comment]
I'm unable to repro, below script doesn't throw any errors. Can you please modify the below script to demonstrate the issue you're seeing?

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  const Test = mongoose.model('Test', new mongoose.Schema({ name: String }));

  console.log(mongoose.version);

  const count1 = await Test.countDocuments({}).exec();
  const count2 = await Test.countDocuments({}).lean().exec();
  console.log('Done');
}
```

Output:

```
$ node gh-13104.js 
7.0.0
Done 0 0
```
