### ISSUE TITLE
Mongoose find does not return documents in jest test

### ISSUE THREAD

**Issue by chtpl** [Automattic/mongoose#13111]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.10.0

### Node.js version

18.14.1

### MongoDB version

4.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

elementaryOS 7 (22.04)

### Issue

Disclaimer: I already posted this to stackoverflow.com - but I need to solve this right now as it is a major blocker for me currently (that is why I am creating an issue here, too) - so if you want to earn some points there, you might want to answer it there: https://stackoverflow.com/questions/75605343/mongoose-find-does-not-return-documents-in-jest-test 

I want to test that a NestJS application writes a certain amount of documents to the database using an E2E test approach where my jest tests execute some HTTP requests against the application running in docker and then fetch the mongoDB documents and verify the amount of documents.

But my mongoose model always returns an empty array when executing find({})

I checked the collection with mongoDB compass and it does in fact contain the documents.

I have no idea what could be wrong. The schema imported from the application code where it is defined as follows

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type MyDocument = MyData & Document;

@Schema({timestamps: true, autoIndex:false, collection: 'my_documents'})
export class MyData {
    @Prop({ required: true })
    message: string;
}
export const MySchema = SchemaFactory.createForClass(MyData);

This is the test code:

import { MyData, MySchema } from 'apps/api/src/app/schema';
import axios from 'axios';
import { connect, model } from 'mongoose';
import { resetDb, sleep } from '../support/helpers';

describe('Post twice, then get', () => {
  beforeEach(async () => {
    await resetDb();
    // let things settle
    await sleep(10000);
  });

  it('should return two messages', async () => {
    const deleteResult = await axios.delete('/');
    expect(deleteResult.status).toBe(200);
    const post1 = await axios.post('/', { message: 'Hello' });
    expect(post1.status).toBe(201);
    const post2 = await axios.post('/', { message: 'Hello2' });
    expect(post2.status).toBe(201);

    const res = await axios.get('/');

    expect(res.status).toBe(200);
    await connect(process.env.MONGODB_URI);
    const myModel = model<MyData>('MyData', MySchema);
    const documents = await myModel.find({});
    console.log(documents);
    expect(documents.length).toBe(2);
  });
});
I created a minimal reproducible repository that is based on an nx monorepo: https://github.com/CodingSpiderFox/nx-neste2e-mcve

To reproduce the issue that keeps api.spec.ts from succeeding, it should be enough to run the example with the command npx nx e2e api-e2e from the root of the repository. The target will automatically run a script that builds and dockerizes the applications and start the mongodb and application containers via docker compose from the jest global setup defined in apps/api-e2e/src/support/global-setup.ts

**Comment by chtpl** [comment]
The app itself can successfully access the database. After running the test, mongoDB compass shows me a collection called "my_documents" in the "api" database on that server.
The database name is passed to the application here https://github.com/CodingSpiderFox/nx-neste2e-mcve/blob/8c777f7afec9ec3c868f0a31f8092b07047e4bc7/apps/api/src/app/app.module.ts#LL19C29-L19C29

**Comment by chtpl** [comment]
Fixed the problem in https://github.com/CodingSpiderFox/nx-neste2e-mcve/commit/511766b195e850c427114ef1d39310a597143e91 
It seems that the problem was that the connection was not using the logical "api" db.

However, I had already tried to run mongoose.connection.useDb('api') before executing the query which didn't work either.
Then I realized that "useDb" seems to return a new connection. I thought that "useDb" function would change the active database for the entire mongoose Object.


So the actual fix was: 
* Acquire new connection to the correct logical DB with useDb()
* create the model on the **new** connection.
Then it works.

I find this aspect of the mongoose API extremely counter intuitive.

When using MSSQL Server, IIRC, the USE "dbname" command changed the active DB directly on the active connection without creating a new connection.

**Comment by vkarpov15** [comment]
I took a look and yeah, the issue is that you're storing data in the api db, but not correctly setting the database when calling `mongoose.connect()`. Making the following change to your test script works:

```javascript
import { MyData, MySchema } from 'apps/api/src/app/schema';
import axios from 'axios';
import { connect, model } from 'mongoose';
import { resetDb, sleep } from '../support/helpers';

describe('Post twice, then get', () => {
  beforeEach(async () => {
    await resetDb();
    // let things settle
    await sleep(10000);
  });

  it('should return two messages', async () => {
    const deleteResult = await axios.delete('/');
    expect(deleteResult.status).toBe(200);
    const post1 = await axios.post('/', { message: 'Hello' });
    expect(post1.status).toBe(201);
    const post2 = await axios.post('/', { message: 'Hello2' });
    expect(post2.status).toBe(201);

    const res = await axios.get(`/`);

    expect(res.status).toBe(200);
    await connect(process.env.MONGODB_URI, { dbName: 'api' }); // <-- add dbName option here
    const myModel = model<MyData>('MyData', MySchema);
    const documents = await myModel.find({});
    expect(documents.length).toBe(2);
  });
});
```

You shouldn't use `useDb()` for setting the database after connecting. `useDb()` serves a very different purpose.

I would strongly recommend setting the database in your MONGODB_URI environment variable, for example:

```
    environment:
      - MONGODB_URI=mongodb://api:password@db:27017/api
```

instead of setting it after the fact. Keeping the database name in the connection string makes it much harder for mixups like this to happen.

**Comment by chtpl** [comment]
OK, maybe that should be mentioned in the documentation in a place more visibly. 

I find it very counterintuitive as most databases I know change the active logical database for the initial connection when calling "use" commands.
But mongoose / mongodb might have a good reason to handle it differently.
What is the purpose of the useDb() in the mongoose API?

**Comment by vkarpov15** [comment]
Multi-tenant connections that share connection pools. Changing the database on a connection is a bit risky because operations like `populate()` execute multiple queries, so what happens if the database changes in the middle of a `populate()` call?

**Comment by chtpl** [comment]
Ok, thanks for the clarification :)
So how would I safely call the "useDb()" function avoiding unpredictable behaviour?

**Comment by vkarpov15** [comment]
`useDb()` isn't vulnerable to this unpredictable behavior. I was just describing the behavior to explain why `useDb()` doesn't modify the database the current connection object points to.

Although in your code, you really shouldn't be using `useDb()` at all.
