### ISSUE TITLE
How to get update result docs in post or pre hook?

### ISSUE THREAD

**Issue by riskgod** [Automattic/mongoose#13119]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

#### the demo code :

```
const mongoose = require('mongoose');
const _ = require('lodash');


const testSchema = new mongoose.Schema({
  id: Number,
  name: String,
  desc: String,
  hashKey: String
});

testSchema.pre('save', { document: true, query: false }, function (next) {
  console.log('saving ', this);
  next()
});

// testSchema.pre('find', function () {
//   console.log('find ', this.getFilter());
// });

// testSchema.post(/^find/, async function (result, next) {

//   console.log(this)
//   // for (let index = 0; index < result.length; index++) {
//   //   const e = result[index];
//   //   console.log('findhook', e.name)
//   //   next()
//   // }

// });

testSchema.pre('updateOne', { document: true, query: true }, async function (next) {
  const sourceQuery = this.getQuery()
  const res = await this.find(sourceQuery)
  _.set(this.getUpdate(), '$set.hashKey', 'demo update one')
  next()
});

testSchema.post('updateMany', { document: true, query: true }, async function (doc, next) {
  // console.log(this.getUpdate())
  // console.log(this.getQuery())
  console.log(doc)
  // const sourceQuery = this.getQuery()
  // const res = await this.find(sourceQuery)
  // console.log(res)
  // _.set(this.getUpdate(), '$set.hashKey', 'demo update many')
  next()
});


const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  // await mongoose.connection.dropDatabase();

  await Test.updateMany({ id: 3 }, {
    name: "jade",
  });
}

run();
```

**Comment by vkarpov15** [comment]
The MongoDB server doesn't return all the documents that were updated in an `updateOne` or `updateMany()`. Your best bet would be to use `findOneAndUpdate()` instead of `updateOne()`. For `updateMany()`, there's no way to atomically get all the documents that were updated, your best bet would be to either 1) update the documents one-at-a-time using `findOneAndUpdate()`, or 2) `await this.model.find(this.getFilter())` in a `pre('updateMany')` hook.

**Comment by riskgod** [comment]
> The MongoDB server doesn't return all the documents that were updated in an `updateOne` or `updateMany()`. Your best bet would be to use `findOneAndUpdate()` instead of `updateOne()`. For `updateMany()`, there's no way to atomically get all the documents that were updated, your best bet would be to either 1) update the documents one-at-a-time using `findOneAndUpdate()`, or 2) `await this.model.find(this.getFilter())` in a `pre('updateMany')` hook.

got that , thanks bro~
