### ISSUE TITLE
Mongoose 7.0.0 Compatibility

### ISSUE THREAD

**Issue by eljoey** [Automattic/mongoose#13115]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.0

### Node.js version

18.x.x

### MongoDB version

4.4

### Operating system

None

### Issue

Looking to upgrade Mongoose to 7.0 and noticed that the compatibility guide at https://mongoosejs.com/docs/compatibility.html does not include 7.0.  What versions of mongoDB will 7.0 be compatible with?

**Comment by jhartzell** [comment]
@eljoey Did you end up figuring this out? We're also wondering about Atlas MongoDB v7.0

**Comment by eljoey** [comment]
> @eljoey Did you end up figuring this out? We're also wondering about Atlas MongoDB v7.0

They updated the compatibility guide here https://mongoosejs.com/docs/compatibility.html.  Everything later than 3.6.x is compatible
