### ISSUE TITLE
Ignore default properties in a new model using TypeScript

### ISSUE THREAD

**Issue by AaronPorts** [Automattic/mongoose#13128]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.0.

### Node.js version

18.8.0

### MongoDB version

4.4.18

### Operating system

Windows

### Issue

How to create a new model without specifying default properties?
```
const UserSchema = new mongoose.Schema({
    name: { type: String },
    isVerified: { type: Boolean, default: false },
});
type IUser = mongoose.InferSchemaType<typeof UserSchema>;
const User = mongoose.model<IUser>("User", UserSchema)<IUser>;
const user = new User ({ name: "user" });
```
Getting ts(2345) error due to missing isVerified.

**Comment by vkarpov15** [comment]
You shouldn't have to specify default properties. Below script compiles without any issues. Can you please modify the below script to demonstrate your issue?

```ts
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
    name: { type: String },
    isVerified: { type: Boolean, default: false },
});
type IUser = mongoose.InferSchemaType<typeof UserSchema>;
const User = mongoose.model<IUser>("User", UserSchema);
const user = new User ({ name: "user" });
```

**Comment by AaronPorts** [comment]
Do you get any kind of linting error here?
```typescript
import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
  name: { type: String },
  isVerified: { type: Boolean, default: false },
});
type IUser = mongoose.InferSchemaType<typeof UserSchema>;
const User = mongoose.model<IUser>("User", UserSchema);
const user = new User({ wrong: 1 });
```

**Comment by vkarpov15** [comment]
Without knowing what linter and what lint config you're using, I can't meaningfully answer that question.

**Comment by AaronPorts** [comment]
Ok, am I right that mongoose doesn't seem to provide model fields type checking?
```typescript
import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
  name: { type: String },
  isVerified: { type: Boolean, default: false },
});
type IUser = mongoose.InferSchemaType<typeof UserSchema>;
const User = mongoose.model<IUser>("User", UserSchema);
const user = new User({ wrong: 1 }); // <------- no type error despite property is not in schema
```

**Comment by vkarpov15** [comment]
Correct. Because of defaults, Mongoose type casting, dotted path support, strict mode, etc. we can't infer all possible valid object parameters to `new User()` at compile time.

For example, in your case, `await user.save()` will succeed, Mongoose will just strip out `wrong` automatically because that field isn't in your schema.
