### ISSUE TITLE
[Tests] What to do about the ubuntu 18(.04) tests?

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#13134]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Recently, github started to do ["rolling brown-outs" of "ubuntu-18.04"](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) test images, resulting in failed tests (and some tests not running at all, because they depend on previous tests being successful) and also marking the badges of "Build Status" as "failed".

This means that we either do not test that ubuntu version anymore, or we have to use a different runner (again), should we just update the ubuntu versions to test 20.04 and 22.04?

Note: when upgrading to ubuntu 22.04, we will have to change the mongodb version in use, because only since 6.0.4 is ubuntu2204 supported (without workarounds)

@vkarpov15

**Comment by vkarpov15** [comment]
@hasezoey we can just get rid of the ubuntu 18.04 tests if they're causing us trouble. Mongoose doesn't do anything too OS-specific, so I'm not too worried about testing ubuntu 18.04 specifically.
