### ISSUE TITLE
Mongoose Not able to resolve host URL correctly inside a docker container

### ISSUE THREAD

**Issue by deveshaggrawal19** [Automattic/mongoose#13130]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.0

### Node.js version

18.14.2

### MongoDB version

5.1.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Issue

Mongodb Installed on Macbook
Redis installed on Macbook
Memcached installed on Macbook

connection uri : mongodb://userName:password@127.0.0.1:27017/?ssl=false&replicaSet=rs0

The node app is running fine on macbook and mongoose is able to connect to mongodb. 

But when I'm using docker container to run the app, I use **host.docker.internal** to make sure that docker container is able to connect to host servers. Redis and memcached are able to connect. But, mongoose is not able to connect, it is throwin error

backend-backend-1  | MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
backend-backend-1  |     at _handleConnectionErrors (/usr/src/app/node_modules/mongoose/lib/connection.js:755:11)
backend-backend-1  |     at NativeConnection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:730:11)
backend-backend-1  |     at async Object.connectDB (/usr/src/app/app/db/db.js:25:9)
backend-backend-1  |     at async main (/usr/src/app/index.js:55:9) {
backend-backend-1  |   reason: TopologyDescription {
backend-backend-1  |     type: 'ReplicaSetNoPrimary',
backend-backend-1  |     servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
backend-backend-1  |     stale: false,
backend-backend-1  |     compatible: true,
backend-backend-1  |     heartbeatFrequencyMS: 10000,
backend-backend-1  |     localThresholdMS: 15,
backend-backend-1  |     setName: 'rs0',
backend-backend-1  |     maxElectionId: new ObjectId("7fffffff0000000000000023"),
backend-backend-1  |     maxSetVersion: 1,
backend-backend-1  |     commonWireVersion: 0,
backend-backend-1  |     logicalSessionTimeoutMinutes: null
backend-backend-1  |   },
backend-backend-1  |   code: undefined
backend-backend-1  | }

If I pass my ip which I get after connecting wifi, 192.168.29.160, I still get the same error with ECONNREFUSED 127.0.0.1:27017

I cannot understand even when I changed the ip why it is throwing the same error.

How can I connect, please help

**Comment by vkarpov15** [comment]
Looks like you're connecting to a replica set. Make sure that your container's self-reported host name is something Node's DNS can resolve, because the MongoDB node driver will try to use each server in the replica set's self reported `hostname`, **not** what's in your connection string. Please take a look at the [replica set hostnames section of the connections docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames) for more info.
