### ISSUE TITLE
Apply function before saving property to the schema

### ISSUE THREAD

**Issue by felipezarco** [Automattic/mongoose#13139]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Be able to define directly on the schema whatever function we want to run on each property (possibly to modify it) before saving them.

### Motivation

Sometimes we want to make sure data was handled properly before being saved.
This goes beyond the variable type. 
This can be achieved by using the hook pre('save').
But having this on the schema fits perfectly the idea of single property data handling and makes the code more cleaner.

### Example

For instance, we want to save whatever numbers are given inside a string called `givenNumber`. We would use the proposed "apply" function setter.

```javascript
const personFavorites = new Schema({
  person: String,
  givenNumber: { 
       type: String, 
       apply: (str) => String(str.replace(/\D/g, '')) 
     }
   }
)
```

**Comment by vkarpov15** [comment]
This sounds like a [custom setter](https://mongoosejs.com/docs/tutorials/getters-setters.html#setters)

```javascript
const personFavorites = new Schema({
  person: String,
  givenNumber: { 
       type: String, 
       set: (str) => String(str.replace(/\D/g, '')) 
     }
   }
)
```
