### ISSUE TITLE
How enabled hedged reads for primaryPreferred on a single query

### ISSUE THREAD

**Issue by amit777** [Automattic/mongoose#13131]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.10.0

### Node.js version

16.17.1

### MongoDB version

6.0.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04

### Issue

According to the [mongodb docs](https://www.mongodb.com/docs/manual/core/read-preference-hedge-option/), if you use a "nearest" read preference, then hedged reads are automatically enabled. The docs say hedged reads are also available if you use "primaryPreferred". I can't seem to figure out how to enable hedged reads with primaryPreferred.

How would I enable hedged reads on the following example line of code:
```js
let mydoc = await MyMongooseModel.findOne({'foo':'bar'}).read('primaryPreferred').exec();
```

**Comment by LalitAswal** [comment]
i think this will work please check 
`let mydoc = await MyMongooseModel.findOne({'foo':'bar'}).read('nearest', 'primaryPreferred').exec();
`

**Comment by vkarpov15** [comment]
@LalitAswal you'll probably just want to do `await MyMongooseModel.findOne({'foo':'bar'}).read('nearest').exec();` . The 2nd param to `read()` is `tags`, not an extra read preference. But `read('nearest')` should work.
