### ISSUE TITLE
Remove type any from field lean of interface QueryOptions

### ISSUE THREAD

**Issue by FantinRaimbault** [Automattic/mongoose#13142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hello,
I am building my repository using Typescript 4.9.5 and mongoose 7.0.0
I want to deduce the return type of my function from the lean option :
If true, I want to return Leandocument (the type I put in my generic schema) otherwise HydratedDocument.
Because of the boolean | any type this can't be done correctly.
But if you only put the boolean type (and don't restrict with any), it works fine!

I will show you this in the example above.

### Motivation

To infer the return type of a method.

### Example

```js
// BlogRepository

import { FilterQuery, HydratedDocument, Model, ProjectionFields, QueryOptions } from "mongoose";
import { Blog, BlogModel } from "./blog.schema";

class BlogRepository {
    private readonly blogModel: Model<Blog>;

    constructor() {
        this.blogModel = BlogModel;
    }

    findOne<
        Projection extends ProjectionFields<Blog>,
        Options extends QueryOptions<Blog>
    >(
        filter: FilterQuery<Blog>,
        projection: Projection,
        options: Options
    ): Promise<
        Options['lean'] extends true
            ? Pick<Blog, Extract<keyof Projection, keyof Blog>> | null
            : HydratedDocument<Pick<Blog, Extract<keyof Projection, keyof Blog>>> | null
    > {
        return this.blogModel.findOne(filter, projection, options);
    }
}

async function main() {
    const blogRepository = new BlogRepository();
    const blog = await blogRepository.findOne(
        { title: "test" },
        { content: 1 },
        { lean: true } // or { lean: false }
    );
    // blog: Document | null instead of type Blog
    // My blog is therefore polluted by unwanted methods like $where ...
}
```
```js
// node_modules/mongoose/types/query.d.ts

interface QueryOptions<DocType = unknown> extends
    PopulateOption,
    SessionOption {
   ...
   ...
    /**
     * If truthy, mongoose will return the document as a plain JavaScript object rather than a mongoose document.
     */
    lean?: boolean | any;  <--- HERE !!! please remove **| any** 
    
    ...
    ...
    
  }

**Comment by vkarpov15** [comment]
Would `boolean | Record<string, any>` work for you as an alternative?

We have `boolean | any` for plugins like [mongoose-lean-virtuals](https://www.npmjs.com/package/mongoose-lean-virtuals) that require you to do `Model.find().lean({ virtuals: true })`

**Comment by FantinRaimbault** [comment]
yes it would be fine !
