### ISSUE TITLE
mongoose 6.x docs broken links in sidebar menu

### ISSUE THREAD

**Issue by lorand-horvath** [Automattic/mongoose#13144]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.10.2

### Node.js version

16.x

### MongoDB server version

5.x

### Description

I'm trying to access mongoose 6.x documentation and I can only get the top level links in the sidebar menu to load the 6.x version, i.e.
https://mongoosejs.com/docs/6.x/docs/index.html
https://mongoosejs.com/docs/6.x/docs/guide.html
https://mongoosejs.com/docs/6.x/docs/api.html

However, all 2nd level links are pointing to the latest docs 7.x, for example:
https://mongoosejs.com/docs/api/document.html
Trying to manually build the above URL for 6.x returns a 404, for example:
https://mongoosejs.com/docs/6.x/docs/api/document.html

### Steps to Reproduce

As described above in Description section.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, will fix asap :+1:
