### ISSUE TITLE
findById returns "DocumentNotFoundError" instead of "CastError" with invalid ID

### ISSUE THREAD

**Issue by DavidMiles1925** [Automattic/mongoose#13165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.0

### Node.js version

18.13.0

### MongoDB server version

5.0.15

### Description

When using .findById method, an error named "DocumentNotFoundError" is returned when in previous versions an error with name "CastError" would be returned.

### Steps to Reproduce

In the code below, when an invalid ID is passed in req.params.UserId a "DocumentNotFoundError" results. This causes the errorHandler function to return a return a status code of 404, when a status code of 400 would be more appropriate.

```
module.exports.getUserById = (req, res) => {
  User.findById(req.params.UserId)
    .orFail()
    .then((user) => {
      res.status(200).send(user);
    })
    .catch((err) => {
        errorHandler.errorHandler(req, res, err);
    });
};
```
### Expected Behavior

I expected an error name of "Cast Error", but instead received an error with a name "DocumentNotFoundError".

**Comment by IslandRhythms** [comment]
I check versions 5, 6, and 7 and they all returned a document not found error.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const doc = await Test.findById('123456789012').orFail();
}

run();
```

**Comment by vkarpov15** [comment]
@IslandRhythms that's because `123456789012` is a valid string representation of an ObjectId. Why did you use that string exactly?

**Comment by IslandRhythms** [comment]
brain fart.
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const doc = await Test.findById('123456789012adff').orFail();
}

run();
```
