### ISSUE TITLE
Mongoose 6.X docs assets returning 404.

### ISSUE THREAD

**Issue by jjacksonjc** [Automattic/mongoose#13175]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.10.2

### Node.js version

NA

### MongoDB server version

NA

### Typescript version (if applicable)

NA

### Description

Various pieces of CSS, JS, and images are not loading for the 6.X docs.
![Screenshot from 2023-03-15 09-50-00](https://user-images.githubusercontent.com/90723560/225366631-3bae844d-dc6c-4b9e-865a-63714f47a9bd.png)

### Steps to Reproduce

Open browser console. Open browser window to the 6.X documentation. Notice in console all the 404 messages.

### Expected Behavior

Page loads with all content and assets.

**Comment by vkarpov15** [comment]
Thanks for reporting, we're working on a fix.

**Comment by vkarpov15** [comment]
Fixed, see following screenshot. We're sorry for any trouble this issue may have caused.

![image](https://user-images.githubusercontent.com/1620265/225430442-9cc53465-1a47-486b-81fe-77b3faf36b31.png)

**Comment by vkarpov15** [comment]
Fixed :+1: feel free to leave a comment on this thread if you find something else missing
