### ISSUE TITLE
Unordered `bulkWrite()` with validation errors doesn't execute the bulk write

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#13176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.x

### Node.js version

Doesn't matter

### MongoDB server version

Doesn't matter

### Description

General idea is the following code throws a validation error and doesn't execute the one valid bulk write op, even though `ordered: false` is set

```javascript
    const userSchema = new Schema({
      num: Number
    });
    const User = db.model('User', userSchema);


    await User.bulkWrite([{
      updateOne: {
        filter: { },
        update: { num: 'not a number' },
        upsert: true
      },
      {
        updateOne: { filter: {}, update: { num: 42 } }
      }
    }], { ordered: false }).then(() => null, err => err);
```

Reported in Slack: https://mongoosejsteam.slack.com/archives/C2CA1AWQP/p1678894562556919

"Hey I’m trying to use writeBulk with multiple updateOne unordered. When one entity throws error (For example doesn’t pass scheme validation) all the bulk get reverts, and I get a general error of cast fails. I would like to update the entities that able to be updated, and get error that contains the entities failed to update, similar to the the insertMany behavior. Does anyone have an idea?"

### Steps to Reproduce

See above

**Comment by IslandRhythms** [comment]
Remove the `.then()` to see the error. Report is correct, no entries in the db after `bulkWrite` runs.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  num: Number
});

const User = mongoose.model('User', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await User.bulkWrite([{ updateOne: { filter: {}, update: { num: 'not a number'}, upsert: true }},
    {
      updateOne: { filter: {}, update: { num: 42 } }
    }], {ordered: false}).then(() => null, err => err);

    console.log(await User.find())

    console.log('done');
}

run();
```

**Comment by doomhz** [comment]
Unfortunately, this fix broke the `bulkWrite()` function for UNordered ops (`options = { ordered: false }`). The `bulkWrite` function never returns when `ops = []`, since the check for `if (ops.length === 0) { return cb(null, getDefaultBulkwriteResult()); }` was moved inside the new `if (ordered) {` block.

A potential solution would be to move the empty `ops` array check above the new `if` block and return early from the callback function.
