### ISSUE TITLE
Post save middleware: reading from database the saved file

### ISSUE THREAD

**Issue by marcosmartinez7** [Automattic/mongoose#13186]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.2

### Node.js version

16.0.14

### MongoDB version

5.4

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

Hello, 

Im using `post save` middleware and I dont know which is the expected behavior. Didn't found any official docs about this situation: 

Basically my FileSchema is implementing a post save 

```
FileSchema.post<FileDocument>('save', async function (doc, next) {
    try {
      const fileModel = this.$model('File');

     
      console.log('the id ', doc._id);
      const file = await fileModel.findById(doc._id);
      console.log('The file ', file);

    } catch (err) {
      console.log('ERROR', err);
      next(err);
    }
  },
});


```

in that hook im just querying the database for the persisted document. 

I get` null` as a result

If I wrap the entire code into a `setTimeout` to give the hook 1 second or so, the file is returned. 

I was expecting that the post save hook context ensures that the documents are persisted on the database. But it seems that it could happen that there are not present already (the setTimeOut validates that) 

Which is the expected behavior?

Regards

**Comment by IslandRhythms** [comment]
Please update what your mongoose version is, 9.2.0 is not a thing
I'll be testing on latest

**Comment by IslandRhythms** [comment]
No problems for me. See if you can modify this script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

testSchema.post('save', async function (doc, next) {
  console.log('what is doc', doc);
  const model = this.$model('Test');
  const res = await model.findById(doc._id);
  console.log('what is res', res);
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const doc = await Test.findOne();
  doc.name = 'Run Hook';
  await doc.save();
  console.log('done');
}

run();
```

**Comment by marcosmartinez7** [comment]
> No problems for me. See if you can modify this script to demonstrate your issue.
> 
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>   name: String
> });
> 
> testSchema.post('save', async function (doc, next) {
>   console.log('what is doc', doc);
>   const model = this.$model('Test');
>   const res = await model.findById(doc._id);
>   console.log('what is res', res);
> });
> 
> const Test = mongoose.model('Test', testSchema);
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017');
>   await mongoose.connection.dropDatabase();
> 
>   await Test.create({
>     name: 'Test Testerson'
>   });
> 
>   const doc = await Test.findOne();
>   doc.name = 'Run Hook';
>   await doc.save();
>   console.log('done');
> }
> 
> run();
> ```

This works on my local machine but doesn't on MongoAtlas. 

I forgot to mentioned that. 

On mongo atlas it seems that I need to add a timeout to delay the execution.

**Comment by rahulkumawat30** [comment]
Please help me resolve this error code "Model.findById() no longer accepts a callback"

.post(function (req, res) {

        const submittedSecret = req.body.secret;
        const userId = req.user.id;

        User.findById("userId", (err, foundUser) => {
            if (err) {
                console.log(err);
            } else {
                if (foundUser) {
                    foundUser.secret = submittedSecret;
                    foundUser.save(function () {
                        res.redirect("/secrets");
                    });
                }
            }
        });
    });

**Comment by rahulkumawat30** [comment]
> Please help me resolve this error code "Model.findById() no longer accepts a callback"
> 
> app.post("/secrets", function(req, res){ const submittedSecret = req.body.secret; const userId = req.user.id;
> 
> ```
>     User.findById("userId", (err, foundUser) => {
>         if (err) {
>             console.log(err);
>         } else {
>             if (foundUser) {
>                 foundUser.secret = submittedSecret;
>                 foundUser.save(function () {
>                     res.redirect("/secrets");
>                 });
>             }
>         }
>     });
> });
> ```

i solve this problem

**Comment by vkarpov15** [comment]
@rahulkumawat30 your comments are off topic. Please open a new issue and follow the issue template.

**Comment by vkarpov15** [comment]
@marcosmartinez7 the script runs fine for me against Atlas. Can immediately read the update.

Below is what my connection string looks like:

```
mongodb+srv://foo:bar@host.XYZ.mongodb.net/db?retryWrites=true&w=majority
```

Can you please provide what your query string looks like, with credentials and hostname excluded? If you don't have `w=majority` in the connection string and you set a readPreference, this may explain the issue you're seeing.

**Comment by marcosmartinez7** [comment]
Hi @vkarpov15 

"mongodb+srv://XXXX:XXXXX@XXXX.mongodb.net/test"

I do not have the `w=majority` 
 
Can you explain me why it is related with the issue?

**Comment by vkarpov15** [comment]
Are you also setting a read preference anywhere? Can you try and see if you still have this issue with `w=majority` in your connection string?

**Comment by marcosmartinez7** [comment]
> Are you also setting a read preference anywhere? Can you try and see if you still have this issue with `w=majority` in your connection string?

Not really. Just defaults. 

I will try to reproduce it with `w=majority`. Couldn't find any docs that relate that with this issue, what do you have in mind about it? 

Regards

**Comment by vkarpov15** [comment]
The idea behind `w=majority` is you're telling MongoDB to not report any write operations (like `save()`) as complete until the write has replicated to a majority of the replica set. I'm not 100% familiar with how Atlas is configured under the hood, but it is possible that you may need `w=majority` to avoid this issue. I'd imagine this might be a reason why Atlas always includes `w=majority` in sample connection strings.
