### ISSUE TITLE
Mongoose takes a very long time to save large Maps with subdocuments to the database

### ISSUE THREAD

**Issue by TheYuriG** [Automattic/mongoose#13191]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.2

### Node.js version

16.9.0

### MongoDB server version

latest

### Description

Mongoose takes an absurdly long time to save a large Map to the database. This problem doesn't happen if you replace the Maps for Arrays.

This was initially reported at #5925 and requested to be made into a new issue when the reproduction script was created, so here it is.

### Steps to Reproduce

Clone my reproduction repo [here](https://github.com/TheYuriG/mongoose-map-saving-issue), then either edit your mongoKey into the `index.js` file or add a `mongoKey.js` file to `/private` so it can be imported by the `index.js` file.

Once that's done, you can either use `npm start` to start the script in colored mode or `npm run colorless` to use colorless mode.

All major steps are color-coded, if you choose to retain the colors, so you can more easily parse the information.

The script will connect to a database and create 20K documents called Minis that only have a small string and a number, then use those to sort and create a Map and an Array version of those documents, sorted by timestamp value.

I've reused the script a few times and I consistently get ~6-minute timers for saving the Maps using mongoose, while saving the Arrays usually takes around ~5-seconds.

Try out the script and let me know if this is an actual bug with the library double checking If every value actually isn't a duplicate of the other value or if this was a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK).

### Expected Behavior

Expected behavior was to not take over 6 minutes to save the Map to the database.

**Comment by TheYuriG** [comment]
At last, closure! Thanks Valeri!

**Comment by vkarpov15** [comment]
Thanks for your patience, took a lot of debugging but the bottleneck should be gone now :+1:
