### ISSUE TITLE
EOF (end of life) for mongoose 6

### ISSUE THREAD

**Issue by vasyl97kharchenko** [Automattic/mongoose#13193]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6

### Node.js version

16

### MongoDB version

4

### Operating system

macOS

### Issue

Could you please tell me when is the EOL (end of life) for mongoose 6?

**Comment by vkarpov15** [comment]
We don't have a scheduled EOL currently. We intend to continue shipping bug fixes and security fixes to Mongoose 6 for at least the rest of 2023.

Will add a page to our docs for EOL schedule.
