### ISSUE TITLE
Schema 'strict' option not set on query

### ISSUE THREAD

**Issue by jerell-mendoza** [Automattic/mongoose#13198]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.0

### Node.js version

16

### MongoDB server version

5.x

### Description

The `strict` option, when set on the Schema is not persisted all the way down to the query object.

Example: When running `Model.findOneAndUpdate` - it is not receiving the proper `strict` parameter value that is set on the schema.

I went back to 5.x and saw that there was code to set the strict value - checking the `options` passed into the query and then checking the schema for the `strict` value:
https://github.com/Automattic/mongoose/blob/5.x/lib/query.js#L4686

Can we add this back into 7.x?

### Steps to Reproduce

```
const mongooseSchema = new mongoose.Schema(
  { 
    test: { type: String }
  },
  {
    strict: false,
  },
);

const model = mongoose.model('test', mongooseSchema);
await model.findOneAndUpdate({ test: 'yes'}, { $set: { newValueNotInSchema: true } }); 
```

### Expected Behavior

I expect the new field given to be added to the document in the database, given that the original schema is set to `strict: false`

**Comment by jerell-mendoza** [comment]
I have opened a PR here to fix this issue:
https://github.com/Automattic/mongoose/pull/13199

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script shows that Mongoose does send `newValueNotInSchema` to MongoDB in Mongoose 7:

```javascript
'use strict';

const mongoose = require('mongoose');
console.log(mongoose.version);
mongoose.set('debug', true);
mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');

const mongooseSchema = new mongoose.Schema(
  { 
    test: { type: String }
  },
  {
    strict: false,
  },
);

run().catch(err => console.log(err));

async function run() {
  const model = mongoose.model('test', mongooseSchema);
  await model.findOneAndUpdate({ test: 'yes'}, { $set: { newValueNotInSchema: true } }).exec();
  console.log('Done');
}
```

```
$ node gh-13198.js 
7.0.1
Mongoose: tests.findOneAndUpdate({ test: 'yes' }, { '$set': { newValueNotInSchema: true } }, { projection: {} })
Done
```
