### ISSUE TITLE
Operations on a model that filter on aliased fields can result in an unfiltered query being executed

### ISSUE THREAD

**Issue by alexbevi** [Automattic/mongoose#13203]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.4

### Node.js version

14.18 (and 18.15)

### MongoDB server version

6.0.3

### Description

When filtering a find operation targeting a model that defines an [alias](https://mongoosejs.com/docs/guide.html#aliases), if that alias is used as the filter criteria it can be silently ignored, resulting in the resulting operation being unfiltered.

### Steps to Reproduce

```ts
// src/models/repo.model.ts

import mongoose from 'mongoose'

type TAuth = {
  d: Date
  u: mongoose.Schema.Types.ObjectId
}

interface IRepo {
  o: string
  a: Array<TAuth>
}

export interface IRepoDocument extends IRepo, mongoose.Document {
  // statics
}

interface RepoModel extends mongoose.Model<IRepoDocument> {
}

const repoSchema = new mongoose.Schema<IRepo, RepoModel>(
  {
    o: {
      type: String,
      alias: 'origin',
      required: true,
    },
    a: {
      type: [{
        d: Date,
        u: mongoose.Schema.Types.ObjectId,
      }],
      alias: 'auth',
    },
  }, {
    timestamps: true,
  },
)

export default mongoose.model<IRepo, RepoModel>('Repo', repoSchema)
```

```ts
// src/index.ts
import mongoose from 'mongoose'
import Repo from './models/repo.model'

mongoose.set('debug', true)

mongoose.connect(
  'mongodb://127.0.0.1:27017/test-mongoose',
  { useNewUrlParser: true, useUnifiedTopology: true },
).then(async () => {
  console.info('Connected to MongoDB')
  /* create a repo */
  await Repo.deleteMany({})
  await Repo.create({ origin: 'something', auth: [{ u: new mongoose.Types.ObjectId() }] })
  const origin = 'github.com/test-mongoose'
  const uid = '123456'
  console.log('\nFIRST TEST: Mongoose aliases')
  try {
    // Now try to find a repo that does not exist
    const repo = await Repo.findOne({ origin, 'auth.u': uid })
    console.log('REPO found', repo) // BAD: no errors, and we've found a repo that does not correspond to the query; check mongoose debug msg.
    // => Mongoose: repos.findOne({}, { projection: {} })
  } catch (err) {
    console.error(new Error('could not find repo'))
    console.log(err)
  }

  process.exit(0)
})
```

### Expected Behavior

```ts
    const repo = await Repo.findOne({ origin, 'auth.u': uid })
```

The model's find* method would properly replace the aliases within the filter prior to sending the operation to the server.

Note the same behavior can be observed with updates which can result in unexpected data modifications:

```ts
    await Repo.updateOne({ origin: origin }, { $set: { o: 'BOOM !!' } })
    // => Mongoose: repos.updateOne({}, { '$setOnInsert': { createdAt: new Date("Thu, 23 Mar 2023 14:38:46 GMT") }, '$set': { o: 'BOOM !!', updatedAt: new Date("Thu, 23 Mar 2023 14:38:46 GMT") }}, {})
    await Repo.updateOne({ o: origin }, { $set: { o: 'BOOM !!' } })
    // => Mongoose: repos.updateOne({ o: 'github.com/test-mongoose' }, { '$setOnInsert': { createdAt: new Date("Thu, 23 Mar 2023 14:42:30 GMT") }, '$set': { o: 'BOOM !!', updatedAt: new Date("Thu, 23 Mar 2023 14:42:30 GMT") }}, {})
```

_No response_

**Comment by alexbevi** [comment]
Note this **DOES NOT** appear to be an issue with Mongoose 7.x (tested on 7.0.2)

**Comment by vkarpov15** [comment]
@alexbevi we have an outstanding issue for automatically calling `translateAliases()` on queries here: https://github.com/Automattic/mongoose/issues/8678 .

The reason why this is an issue in Mongoose 6, but not Mongoose 7, is because of the [strictQuery change](https://mongoosejs.com/docs/migrating_to_7.html#strictquery). In Mongoose 6, Mongoose doesn't recognize `auth.u` and strips it from the query filter by default. In Mongoose 7, Mongoose doesn't strip out `auth.u` by default, even though it doesn't recognize `auth.u` as a schema path.

**Comment by alexbevi** [comment]
That makes sense @vkarpov15, much appreciated. I'm going to close this issue out as it sounds to just be a duplicate of #8678 at this point.
