### ISSUE TITLE
Nested Discriminators in multi-dimensonal arrays use `name` instead of `value`

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#13201]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.10.1

### Node.js version

19.6.0

### MongoDB server version

5.0

### Typescript version (if applicable)

4.9.5

### Description

I have noticed that nested discriminator multi-dimensonal arrays use the `name` of the discriminator instead of `value`, like in non-array or one-dimensonal arrays

function parameter reference: `path.discriminator(name, schema, value)`

### Steps to Reproduce

Reproduction Repository & branch: https://github.com/typegoose/typegoose-testing/tree/mongooseNestedDiscriminatorNaming

- (have node_modules install and a mongo instance running on default port)
- execute `yarn run run` (or any package manager)
- observe output being without the discriminated properties and assert error

- invert https://github.com/typegoose/typegoose-testing/blob/39da16a7de48d26f9d37b1ead010c0d7f48ce6ec/src/test.ts#L83-L88
- execute `yarn run run` (or any package manager)
- observe discriminated properties being present and no assertion error

also includes commented-out code for a one-dimensonal array

### Expected Behavior

to use `value` like for one-dimensonal arrays and non-arrays

---

also tested mongoose 7.0.2, with same behavior

**Comment by hasezoey** [comment]
i think i found the reason:
`SchemaArray` does not pass-on `options` (also known as `value`) to the lower array, like `DocumentArrayPath`
https://github.com/Automattic/mongoose/blob/0ddb0f6dfd8b8d7ef97cd5a95a26d356f3940810/lib/schema/array.js#L455
https://github.com/Automattic/mongoose/blob/0ddb0f6dfd8b8d7ef97cd5a95a26d356f3940810/lib/schema/documentarray.js#L192

**Comment by vkarpov15** [comment]
@hasezoey I just merged 6.x into main, thanks for pointing this out :+1:
