### ISSUE TITLE
i cant save data from checkbox using js and mongoose

### ISSUE THREAD

**Issue by mohamed9777** [Automattic/mongoose#13205]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.0

### Node.js version

18.15.0 

### MongoDB version

6.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

i have form for new product and using checkbox for chose many size 
when i choose more than 1 size this error happen

 this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Product validation failed: size: Cast to string failed for value "[ 'S', 'M', 'L' ]" (type Array) at path "size"

and this is the schema 

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ProductSchema = new Schema({
    title: String,
    image: String,
    price: Number,
    size: {
        type: String,
        enum: ['S', 'M', 'L', 'xL', '2xL']
    }
});

and this is example of the checkbox

 <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" name="products[size]" id="M" value="M">
                <label class="form-check-label" for="M">
                    Medium
                </label>
              </div> 

module.exports = mongoose.model('Product', ProductSchema);

**Comment by vkarpov15** [comment]
Sounds like you need to update your schema to the following:

```javascript
const ProductSchema = new Schema({
  title: String,
  image: String,
  price: Number,
  size: {
    type: [String], // <-- make size an array of strings rather than just a string
    enum: ['S', 'M', 'L', 'xL', '2xL']
  }
});
```

**Comment by mohamed9777** [comment]
thanks alot <3
