### ISSUE TITLE
Use mongoose in local package for next.js project

### ISSUE THREAD

**Issue by samevision** [Automattic/mongoose#13212]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.3

### Node.js version

18.11.0

### MongoDB version

Atlas

### Operating system

None

### Issue

Hello,

I am using a local NPM package in my Next.js projects which has mongoose as a dependency. In my next.config.js I have specified that my package should be transpiled:

`transpilePackages: ['my-package']`

Somehow I have two problems which I don't have if I use mongoose directly in my next.js project.

**(1) Can't resolve optional depencencies**
Mongoose provides some optional functions that fall back on various dependencies like 'supports-color', 'kerberos', etc. But since I don't use these functions, I don't need these dependencies. However I receive this error:

```
warn  - ../my-package/node_modules/debug/src/node.js
Module not found: Can't resolve 'supports-color' in '/my-package/node_modules/debug/src'

Import trace for requested module:
../my-package/node_modules/debug/src/node.js
../my-package/node_modules/debug/src/index.js
../my-package/node_modules/mquery/lib/mquery.js
../my-package/node_modules/mongoose/lib/index.js
../my-package/node_modules/mongoose/index.js

../my-package/node_modules/mongodb/lib/deps.js
Module not found: Can't resolve 'kerberos' in '/my-package/node_modules/mongodb/lib'

Import trace for requested module:
../my-package/node_modules/mongodb/lib/deps.js
../my-package/node_modules/mongodb/lib/index.js
../my-package/node_modules/mongoose/lib/index.js
../my-package/node_modules/mongoose/index.js
```

(2) Top level await error
I receive this error:

```
../my-package/node_modules/bson/lib/bson.mjs
Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
```

I already tried to enable topLevelAwait but this leads to other errors. And still if I use mongoose directly in my next.js project it works fine.

**Comment by samevision** [comment]
I was able to resolve the second problem by adding adjusting my next.config.js:

`serverComponentsExternalPackages: ["mongoose"]`

The first problem is still appearing.

**Comment by vkarpov15** [comment]
@samevision can you please set up a project that demonstrates how you're sharing models?

**Comment by samevision** [comment]
@vkarpov15 I set up a repository that demonstrates the bug: https://github.com/samevision/mongoose-bug

Please give it a glance and let me know what's the problem here.

Thanks.

**Comment by vkarpov15** [comment]
First of all, I took and confirmed that those "Can't resolve 'kerberos' in '/my-package/node_modules/mongodb/lib'" and "Critical dependency: the request of a dependency is an expression" messages are warnings, not errors. Your code will work fine.

For the "Can't resolve 'X'" warnings, you have 2 workarounds:
1. Install all the necessary packages
2. Use a custom [webpack config with aliases](https://masteringjs.io/tutorials/webpack/alias) as follows

```javascript
module.exports = {
  transpilePackages: ['@package/bug'],
    experimental:{
        appDir: true,
        serverComponentsExternalPackages: ["mongoose"]
    },
    webpack: config => {
      Object.assign(config.resolve.alias, {
        '@mongodb-js/zstd': false,
        '@aws-sdk/credential-providers': false,
        'snappy': false,
        'aws4': false,
        'mongodb-client-encryption': false,
        'kerberos': false,
        'supports-color': false
      });
      return config;
    },
    reactStrictMode: process.env.NODE_ENV === "development" ? false : true
}
```

The "Critical dependency: the request of a dependency is an expression" warning is a bit trickier to work around, you'll need the [webpack-filter-warnings plugin](https://www.npmjs.com/package/webpack-filter-warnings-plugin) as suggested [here](https://typeorm.io/faq#how-to-use-webpack-for-the-backend). Full example with no warnings is as follows:

```
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');

module.exports = {
  transpilePackages: ['@package/bug'],
    experimental:{
        appDir: true,
        serverComponentsExternalPackages: ["mongoose"]
    },
    webpack: config => {
      Object.assign(config.resolve.alias, {
        '@mongodb-js/zstd': false,
        '@aws-sdk/credential-providers': false,
        'snappy': false,
        'aws4': false,
        'mongodb-client-encryption': false,
        'kerberos': false,
        'supports-color': false
      });
      config.plugins.push(new FilterWarningsPlugin({
        exclude: [/the request of a dependency is an expression/]
      }));
      return config;
    },
    reactStrictMode: process.env.NODE_ENV === "development" ? false : true
}
```
