### ISSUE TITLE
countDocument returns the wrong result if match option is set

### ISSUE THREAD

**Issue by cityvoice** [Automattic/mongoose#13217]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.0

### Node.js version

16.2

### MongoDB server version

6.0

### Description

hi guys, I have two records in my collection such as:
[
{_id:1,..., is_delete:0},
{_id:2,..., is_delete:1},
]

when i query with match option `{is_delete:0}`, the aggregate gives me the right result, but the countDocuments returns two.

 ```
async findList(tenant_id: number, queryUserDto: QueryCustomerDto) {
    const {
      name,
      limit,
      skip,
      sort_field,
      sort_type,
      ...rest
    } = queryUserDto;
    const  matchOption = <Record<string, any>>{is_delete:0}; 
    //const matchOption = <Record<string, any>>{ ...rest, tenant_id, is_delete: 0 };
    const queryData = this.model.aggregate();
    queryData.match(matchOption);
    queryData.skip(skip);
    queryData.limit(limit);
    queryData.addFields({ 'id': '$_id' });
    const customers = await queryData;
    const total = await this.model.find(matchOption).countDocuments();
    console.log(total) //returns 2, it should be 1
    return { list: customers, total };
  }
```

I change the code to `this.model.find(matchOption).count()` or `this.model.where(matchOption).countDocuments()` or `this.model.countDocuments(matchOption)` or they all failed.  any ideas ? thanks

### Steps to Reproduce

It's a nestjs project.my @nestjs/mongoose version is 9.2.1

### Expected Behavior

countDocument should match the match option.

**Comment by cityvoice** [comment]
const total = await this.model.collection.countDocuments(matchOption); give me the right result.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String,
  isDeleted: Number
});


const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'test',
    isDeleted: 0
  });
  await Test.create({
    name: 'testerson', 
    isDeleted: 1
  });

  const ag = Test.aggregate();
  ag.match({isDeleted: 0});
  const res = await ag;
  const total = await Test.find({isDeleted: 0}).countDocuments();
  console.log('what is res', res);
  console.log('what is total', total);
  console.log('done');
}

run();
```
