### ISSUE TITLE
Document does not type non-default timestamp property names

### ISSUE THREAD

**Issue by maxmwang** [Automattic/mongoose#13215]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.8.0, 7.0.3

### Node.js version

16.17.0

### MongoDB server version

5.0.14

### Typescript version (if applicable)

4.8.4

### Description

Builds on earlier issue #12069 where `Document` and `InferSchemaType` does not infer timestamp fields into Typescript types. 

Renamed timestamp fields are not extracted using `Document` and `InferSchemaType`. 

### Steps to Reproduce

```ts
import { Schema, InferSchemaType, Document } from 'mongoose';

const MySchema = new Schema({ 
  username: String,
}, {
  timestamps: {
    createdAt: "date_joined",
    updatedAt: false,
  },
});

export type MyType = Document & InferSchemaType<typeof MySchema>;
```

### Expected Behavior

We expect `MyType` to be:

```ts
type MyType = {
  username: String,
  date_joined: Date,
};
```

We get:
```ts
type MyType = {
  username: String,
};
```
<img width="573" alt="Screen Shot 2023-03-26 at 12 58 09 AM" src="https://user-images.githubusercontent.com/46574419/227763035-3e6903ec-0d02-4843-a20b-a07b10de25a8.png">

Note how not even `createdAt` is on the type. Looking at the actual Document, we will see a type that looks like our expected type (with username, date_joined, and no updatedAt field).

**Comment by vkarpov15** [comment]
We'll add support for this in the future. But, in the meantime, I recommend you add `date_joined` to your schema manually as follows.

```ts

const MySchema = new Schema({ 
  username: String,
  date_joined: Date,
}, {
  timestamps: {
    createdAt: "date_joined",
    updatedAt: false,
  },
});
```

**Comment by donoftime2018** [comment]
The way I added my timestamps is as follows:

const MySchema = new Schema({ 
  username: String,
  date_joined: Date,
}, {
  timestamps: true
});
