### ISSUE TITLE
findOneAndUpdate does not cast arrayFilters

### ISSUE THREAD

**Issue by dermasmid** [Automattic/mongoose#13219]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

18

### MongoDB server version

5

### Description

when using findOneAndUpdate and arrayFilters it will not be casted, resulting in _id not being a ObjectId

introduced in https://github.com/Automattic/mongoose/commit/3174e296581ad4f6ed4555990ad55dfa6f7bee8c

### Steps to Reproduce

`Model.findOneAndUpdate(
    { _id: '636bb1a6dece391b2652ae18' },
    {
      $set: {
        'versions.$[v].test': 'test',
      },
    },
    {
      arrayFilters: [
        { 'v._id': '637601b33ce5bbf2cbfe3831' },
      ],
    }
  ).exec()`

### Expected Behavior

_id should be converted to ObjectId

**Comment by Ruslancic** [comment]
I have similar error with this code:
```
Model.findByIdAndUpdate(
            id,
            {
              $inc: { 'item.$[elem].items': -1 },
            },
            { new: true, arrayFilters: [{ 'elem._id': item._id }] },
          );
```
Increment by -1 not working!
