### ISSUE TITLE
Model Bakers for better fixtures in Mongoose

### ISSUE THREAD

**Issue by victorperezc** [Automattic/mongoose#13216]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.x.x

### Node.js version

16.x.x

### MongoDB version

5.x.x

### Operating system

macOS

### Issue

As a Django developer, I am used to work with [model-bakers](https://model-bakery.readthedocs.io/en/latest/), a handy factory library to easily create dummy data for testing fixtures. I have been researching see if I found a similar project for mongoose, but I haven't seen any. Does anyone know any factory library for mongoose? Thanks!

**Comment by vkarpov15** [comment]
Something to look into, but model-bakers looks similar to faker? https://fakerjs.dev/
