### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by kimhandole** [Automattic/mongoose#13225]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.1

### Node.js version

19.5.0

### MongoDB server version

4.9.1

### Description

const { Types } = require('mongoose');

throws me 

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'split')

This was an issue in the past and I guess it still exists?

### Steps to Reproduce

const { Types } = require('mongoose');

### Expected Behavior

TypeError: Cannot read properties of undefined (reading 'split')

**Comment by vkarpov15** [comment]
@kimhandole I'm unable to repro, below is the Node shell output I'm seeing:

```
Welcome to Node.js v19.5.0.
Type ".help" for more information.
> const { Types } = require('mongoose')
undefined
> require('mongoose').version
'6.6.1'
> 
```

Can you please provide the full stack trace? Also, please try executing the above commands on your machine and see if you still get that error.
