### ISSUE TITLE
How to securely add a password for an existing user in the database?

### ISSUE THREAD

**Issue by moaazbhnas228** [Automattic/mongoose#13243]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^6.6.1

### Node.js version

^10.8.1

### MongoDB version

^4.7.0

### Operating system

Windows

### Description
In our database, we have a collection (`customers`) for all ordering customer.  
In this collection, we stored all customer's info, including email.  
**But without password** since we didn't implement authentication yet.  
It looks something like this:

``` js
{
  name: "Moaaz Bhnas",
  email: "moaaz@gmail.com",
  ... // other data about the user
}
```

Then we decided to add a sign up form with email and password fields.

### Problem
When a customer who has a document in our database tries to sign up using the same email.  

### Solution I tried  
If a customer in our database tries to sign up with the same email, I only update the password in his/her document:   

``` ts
const updatedCustomer = await CustomerModel.updateOne({ email }, {password: newPassword});
```
It worked, but there's a security issue with this solution. Anyone could easily hack a customer if he knows his/her email by just signing up using that email.  

### Question
Is there a secure way to add a password to an existing document with only email?

**Comment by ShaunLWM** [comment]
Doesn't feel like a mongoose question though. But I can give some advice.

1. User registers
2. Email exist in database. Generate random code and store it in the user row. Set `isConfirmed` to false.
3. Send email verification link to email
4. User click on link - allow them to set new password.
5. Save password and set `isConfirmed` to true.

**Comment by moaazbhnas228** [comment]
@ShaunLWM Thank you so much. Will do that

**Comment by vkarpov15** [comment]
@ShaunLWM is right, you should implement a check that asks the user to confirm they have access to that email address before letting them set the password.

**Comment by vkarpov15** [comment]
I'd also encourage you to take a look at [this blog post about best practices for storing passwords with Mongoose](http://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis.html)
