### ISSUE TITLE
dataSize issue

### ISSUE THREAD

**Issue by dr-montasir** [Automattic/mongoose#13242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

v19.6.0

### MongoDB server version

v3.6.8

### Description

Can not read dataSize.

`setInterval(() => {
  const conn = mongoose.connection;

  conn.db.stats((err, stats) => {
    if (err) return `Connection Error: ${err}`;
    console.log(stats.dataSize);
  });
}, 1000);`

### Steps to Reproduce

I have no idea

### Expected Behavior

I have no idea

**Comment by IslandRhythms** [comment]
It won't print

```javascript
const mongoose = require('mongoose');

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  const conn = mongoose.connection;

  conn.db.stats((err, stats) => {
    console.log('inside the function')
    console.log('stats are', stats.dataSize);
  });
  console.log('done');
}

run();
```

**Comment by vkarpov15** [comment]
Remember that Mongoose 7 no longer supports callbacks, you need to use async/await or promises. The following script prints out stats as expected.

```javascript
const mongoose = require('mongoose');

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  const conn = mongoose.connection;

  const stats = await conn.db.stats();
  console.log('stats are', stats.dataSize);
  console.log('done');
}

run();

```
