### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by lakshmankashyap** [Automattic/mongoose#13248]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

18.15.

### MongoDB server version

5

### Typescript version (if applicable)

4.9.4

### Description

node_modules/mongodb/lib/operations/add_user.js:16
        this.options = options ?? {};
                                ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### Steps to Reproduce

npm start

### Expected Behavior

node_modules/mongodb/lib/operations/add_user.js:16
        this.options = options ?? {};
                                ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by vkarpov15** [comment]
Please provide a more complete repro script, including your `tsconfig.json`. The code you pasted is valid JavaScript in Node 18.15, so it might be that your tsconfig is producing invalid code.

**Comment by iamEvanYT** [comment]
This is still happening. I think its because this was built for typescript and not javascript, and those typings are not supported by js

**Comment by vkarpov15** [comment]
@iamEvanYT please open a new issue and follow the issue template
