### ISSUE TITLE
The this argument of the pre middleware of the updateOne function not refer to the document

### ISSUE THREAD

**Issue by amanfrinati** [Automattic/mongoose#13244]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13.15

### Node.js version

16.x

### MongoDB version

4.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Issue

As documented here [https://mongoosejs.com/docs/5.x/docs/middleware.html](https://mongoosejs.com/docs/5.x/docs/middleware.html), the `updateOne` middleware (along with `save`, `validate`, etc..) is a Document middleware and `this` should refers to the document, but `this` refers to the query.

```typescript
schema.pre('updateOne', async function () {
  this.getQuery() // Returns the query
})
```

I suggest to remove `updateOne` from the list of "Document middleware supported" in the chapter [Types of Middleware](https://mongoosejs.com/docs/5.x/docs/middleware.html#types-of-middleware)

**Comment by vkarpov15** [comment]
`updateOne()` can be either document middleware or query middleware depending on options. To use `updateOne()` as document middleware, use the following.

```javascript
schema.pre('updateOne', { document: true, query: false }, async function () {
  this.isNew;
})
```
