### ISSUE TITLE
Incorrect result of isValidObjectId

### ISSUE THREAD

**Issue by rishabhsevta** [Automattic/mongoose#13259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

>=6.0.0

### Node.js version

18.14.1

### MongoDB server version

6.0.4

### Description

We tried to run isValidObjectId on the following test case:
'dfdfdfdfdfdf'
This resulted in the output being true despite it failing the Regex requirement for a validObjectId.

### Steps to Reproduce

1. npm install mongoose

2. Run the following script: 
const { isValidObjectId } = require('mongoose');

console.log(isValidObjectId('dfdfdfdfdfdf'));

### Expected Behavior

Correct result: false
Actual Result: true

**Comment by vkarpov15** [comment]
Expected behavior. `isValidObjectId()` returns true for any value that can be converted to an ObjectId, and any string of length 12 can be converted to a valid ObjectId. See #11227, #11856, etc.
