### ISSUE TITLE
Model.findOneAndUpdate -> limitation of the first parameter

### ISSUE THREAD

**Issue by dtboy1995** [Automattic/mongoose#13264]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.4

### Node.js version

v12.18.3

### MongoDB server version

4.2

### Description

When the first parameter is a string, the **Model.findOneAndUpdate** ignores the parameter and randomly updates the data

### Steps to Reproduce

```js
 await mongoose.connect(config.mongodb)
 mongoose.set('debug', true)
 let bill_id = '637cb865b7a6e62bdae6fe55'
 await Bill.findOneAndUpdate(bill_id, { test_insert_data: '___' })
```

**mongoose log**

![image](https://user-images.githubusercontent.com/19227547/231092648-2e456c14-6d63-4db5-b277-a625b5ca0f28.png)

### Expected Behavior

let mongoose throw an error, such as the query parameter must be an `object`

**Comment by IslandRhythms** [comment]
While the query omits the id from the first arg, it still updates the correct document. Not really sure what you want to do here.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);
const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const entry = await Test.create({
    name: 'john'
  });

  await Test.create({
    name: 'henry'
  })
  const id = entry.id;

  await Test.findOneAndUpdate(id, {name: 'Test'});
  console.log('done');
  console.log(await Test.find())
  
}

run();
```

**Comment by gastoncasini** [comment]
In the example above the update is applied to the first inserted document, which is a bit misleading as we are passing an id as a filter.

```
const mongoose = require("mongoose");
mongoose.set("debug", true);
const testSchema = new mongoose.Schema({
	name: String,
});

const Test = mongoose.model("Test", testSchema);

async function run() {
	await mongoose.connect("mongodb://localhost:27017");
	await mongoose.connection.dropDatabase();

	const entry = await Test.create({
		name: "john",
	});

	const anotherEntry = await Test.create({
		name: "henry",
	});

	const id = anotherEntry.id;

	await Test.findOneAndUpdate(id, { name: "Test" });
	console.log("done");
	console.log(await Test.find());
}

run();
```
maybe this example clarifies the problem mentioned in the issue. Because in this case, the updated document is the one with name == "john"
