### ISSUE TITLE
[DOCS] documentation about `Subdocuments versus Nested Paths` may need revision

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#13272]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

i have noticed that `Subdocuments versus Nested Paths` in `/docs/subdocs.md` the section still mentions that `prop: new Schema({ name: String })` and `prop: { name: String }` a subtly different, even though #7181 has been closed and a51fbcc3442204895ae97e68b6d547be8d4b2f5c which should have addressed that to my understanding

(both in master(7.0) and 6.x)

**Comment by vkarpov15** [comment]
I presume this issue is referring to the following text:

```
In Mongoose, nested paths are subtly different from subdocuments.
For example, below are two schemas: one with `child` as a subdocument,
and one with `child` as a nested path.
```

Which is correct. #7181 refers to cases where you explicitly specify `type: { nestedProp: String }`, which is a separate case that had very bad behavior in older versions of Mongoose. There is still a difference between nested paths and subdocuments even in Mongoose 7.

**Comment by hasezoey** [comment]
> There is still a difference between nested paths and subdocuments even in Mongoose 7.

thanks for clearing that up, i thought in 7.0 both ways would be the same as https://github.com/Automattic/mongoose/issues/7181 would indicate

for reference, what are the differences now (aside form the `=== undefined` mentioned in the docs) and do those difference actually matter? (asking if there is a use-case instead of just creating new schemas all the time like typegoose would currently do)

**Comment by vkarpov15** [comment]
Same as listed in those docs: you can set defaults on subdoc paths and subdocs have a `deleteOne()` method
