### ISSUE TITLE
Document $inc method does not store previous data

### ISSUE THREAD

**Issue by oleegarch** [Automattic/mongoose#13274]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

v16.0.0

### MongoDB server version

4.4.5

### Description
$inc method locally saves all data, but sends to mongoose the last one
```
const user = await Users.findOne({ snid: 'vk_205580268' });

user.$inc('coins', 1000); // user.coins = 1000
user.$inc('coins', 2000); // user.coins = 3000

await user.save();

// but output:
// Mongoose: users.updateOne({ _id: new ObjectId("640e547132b7729ceb60d6d6") }, { '$inc': { coins: 2000 } }, { session: null })
```

### Steps to Reproduce

Execute $inc method twice or more times

### Expected Behavior

$inc method store previous value and save all together, output should be:
Mongoose: users.updateOne({ _id: new ObjectId("640e547132b7729ceb60d6d6") }, { '$inc': { coins: 3000 } }, { session: null })

**Comment by floatingmess06** [comment]
does:
user.$inc('coins', 1000); // user.coins = 1000
await user.save();
user.$inc('coins', 2000); // user.coins = 3000
await user.save();
- works or not

**Comment by IslandRhythms** [comment]
I am able to reproduce on 7.0.4, but as floatingmess06 pointed out if you do a save operation beforehand it works fine.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);
const testSchema = new mongoose.Schema({
  coins: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({ coins: 0 });

  const doc = await Test.findOne();
  doc.$inc('coins', 1000);
  console.log('what is doc', doc);
  doc.$inc('coins', 2000);
  console.log('what is doc', doc);

  await doc.save();
  console.log('doc after save', doc);
  console.log(await Test.findOne());
  console.log('done');
}

run();
```
