### ISSUE TITLE
Timeseries should not have _id

### ISSUE THREAD

**Issue by nordicgit70** [Automattic/mongoose#13278]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

By default the time-series collection should not have an `_id`. Conceptually a time-series collection should not have the need for a document identifier apart from the metadata and time field. 

### Motivation

MongoDB delete and update operations have limitations and only work with metadata filters. A Mongoose document with an identifier implicitly suggests that the identifier could be used for update and delete operations.

**Comment by nordicgit70** [comment]
@vkarpov15 thanks!

**Comment by vkarpov15** [comment]
Unfortunately it doesn't look like this will be possible: MongoDB always adds an `_id` for newly inserted documents, even timeseries documents. So if the Mongoose schema doesn't have `_id`, that would mean the schema isn't an accurate representation of what's in MongoDB.

**Comment by nordicgit70** [comment]
Okay, thanks for looking into the proposal.
