### ISSUE TITLE
Schemas in separate project with arrays causes "Schema for array path is from a different copy of the Mongoose module."

### ISSUE THREAD

**Issue by rndfm** [Automattic/mongoose#13275]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

18.13.0

### MongoDB server version

6.0.5

### Description

I have my schemas defined in a separate npm package as they are going to be used be at couple of different services.

When using an array path in the first level i get the following error:
"TypeError: Schema for array path `products` is from a different copy of the Mongoose module. Please make sure you're using the same version of Mongoose everywhere with `npm list mongoose`. If you are still getting this error, please add `new Schema()` around the path: products: new Schema(...)"

I tried adding the new Scheme(..) thing. This makes the error message disappear but when i try to new up the model it fails there instead.

BUT. If i comment out the "if and throw" in schema.js: 1276, it works as expected.

The strange thing is. I have another array that works without any errors. But it's on "level 2". Eg. there's another object path before it.

My schema is quite simple:
```
import { Schema } from "mongoose";
import productSchema from "./Product.js";

const companySchema = new Schema({
	id: String,
	name: String,
	image: String,
	products: [new Schema(productSchema)]
});

export default companySchema;
```

```
import { Schema } from 'mongoose';

const productSchema = new Schema({
	id: String,
	name: String
});

export default productSchema;
```

If i change products to a single(non array) item in the company it works just fine.

My more complex scenario that actually works is a three level deep subDocument.

First level:
```
import { Schema } from "mongoose";
import consumptionDataSchema from "./ConsumptionData.js";

const userSchema = new Schema({
	name: String,
	email: String,
	image: String,
	consumptionData: consumptionDataSchema
});

export default userSchema;
```

Second level:
```
import { Schema } from "mongoose";
import meteringPointSchema from "./MeteringPoint.js";

const consumptionDataSchema = new Schema({
	authorized: Boolean,
	meteringPoints: [meteringPointSchema]
});

export default consumptionDataSchema;
```

Third level:
```
import { Schema } from "mongoose";

const meteringPointSchema = new Schema({
	id: String,
	type: String,
	name: String,
	rawData: Object
});

export default meteringPointSchema;
```

In my shared/common package I am listing mongoose as peerDependency.

All the packages has mongoose version 7.0.3

### Steps to Reproduce

I have created a demo repo that shows the problem:

https://github.com/rndfm/mongoose-schema-error

Try and run the apps with:
node level1app.js
node level2app.js

For the level 1 app I get the following error:
```
PS C:\repos\mongoose-schema-error\app> node app.js
C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:1277
        throw new TypeError('Schema for array path `' + path +
              ^

TypeError: Schema for array path `products` is from a different copy of the Mongoose module. Please make sure you're using the same version of Mongoose everywhere with `npm list mongoose`. If you are still getting this error, please add `new Schema()` around the path: products: new Schema(...)
    at Schema.interpretAsType (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:1277:15)
    at Schema.path (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:1033:27)
    at Schema.add (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:697:12)
    at merge (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\helpers\schema\merge.js:12:6)
    at Schema.add (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:628:5)
    at new Schema (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:134:10)
    at Mongoose.model (C:\repos\mongoose-schema-error\app\node_modules\mongoose\lib\index.js:538:14)    at file:///C:/repos/mongoose-schema-error/app/app.js:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0
```

For the level 2 app it works just fine.

### Expected Behavior

I would expect this to work just the same in any level of the schema tree and not throw any errors.

**Comment by rndfm** [comment]
I just realized that the new Schema(..) thing should be around the array not just the object.

And that actually works. But why is this necessary for the "level 1" version when not for the "level 2"?

I would expect this to behave the same.

**Comment by rndfm** [comment]
I stand corrected. 
Encapsulating the array in new Schema(..) makes the error message disappear. But it doesn't make it work.

Now it's just failing when trying to save data.

**Comment by rndfm** [comment]
If i comment out the "if and throw" in schema.js: 1276 it works as expected.

**Comment by IslandRhythms** [comment]
Since you've updated since you posted the issue, what error are you seeing, what command are you running?

**Comment by IslandRhythms** [comment]
![image](https://user-images.githubusercontent.com/39510674/233669083-2517f048-8e88-47e3-8e5c-238cf6e2e5ab.png)
This is the  error I get

**Comment by rndfm** [comment]
> ![image](https://user-images.githubusercontent.com/39510674/233669083-2517f048-8e88-47e3-8e5c-238cf6e2e5ab.png) This is the error I get

What version of Node i that?
I just tried to clone the repo and run it with node version 18.13.0. And et runs fine. (Apart from the mongoose error)

**Comment by rndfm** [comment]
I tried to change the way i import mongoose types. Maybe this is more compatible?

Pull :)

**Comment by vkarpov15** [comment]
The [repro script you posted](https://github.com/rndfm/mongoose-schema-error) doesn't have a separate package for "shared", "shared" is a separate directory with Mongoose listed as a `peerDependency`. That setup won't work, "shared" isn't installed by npm so nothing will resolve its peer dependencies.

What's the output of `npm list mongoose` in your project?

**Comment by rndfm** [comment]
All I'm trying to do is reuse some schemas across two or more projects. What would be the right way to do this?

**Comment by rndfm** [comment]
And by the way. It works as expected when i comment out the line where the exception is thrown.

mongoose-schema-error\app\node_modules\mongoose\lib\schema.js:1277

**Comment by vkarpov15** [comment]
Depends on how your project is structured. In the setup in this repo: https://github.com/rndfm/mongoose-schema-error where you have multiple sibling directories, each with their own copy of Mongoose, I'd recommend either:

1) Add a top-level `node_modules` directory and put Mongoose as a dependency there. That way both `app` and `shared` use the top-level mongoose package.
2) Make `shared` only export the schema definition, not a Mongoose schema instance. So product.js exports `{ name: String }` rather than `new mongoose.Schema({ name: String })`, `company.js` exports `{ products: [{ type: productSchemaDefinition }] }` rather than `{ products: [productSchema] }`. Export POJO, call `new Schema()` on that POJO.

The problems with multiple copies of the Mongoose modules are 1) incompatibilities between versions, and 2) any `instanceof` checks we use will break. So while your code may look like it works, we don't have tests in place to cover multi-module setups, so we're not as confident that Mongoose will work as designed in that case. That being said, we'll do some work to allow copying using `new Schema()` as the error message recommends.
