### ISSUE TITLE
Getting cast Error While making any request

### ISSUE THREAD

**Issue by shashankduttmr** [Automattic/mongoose#13299]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

v18.16.0

### MongoDB server version

6.0.5

### Description

I'm getting an error cast Error while making any request I haven't pass any kind of parameters like favicon

https://drive.google.com/file/d/1Cep8TFTp9WU5X007f0Ry_NeWbcWR22lG/view?usp=share_link

### Steps to Reproduce

```javascript
const Post = require('../models/Post')
const category = ["vegetable", "dairy", "fruites"]


module.exports.Show = async function(req, res){
    const data = await Post.find({})
    res.render('index', {data})
}

module.exports.New = function(req, res){
    res.render('new', {category})
}

module.exports.Create = async function(req, res){
    const pro = new Post(req.body)
    await pro.save()
    res.redirect('/')
}

module.exports.ShowOne = async function(req, res){
    const {id} = req.params

    const data = await Post.findById(id)

    res.render('show', {data})
}
```

**Comment by vkarpov15** [comment]
Chrome automatically makes request to `/favicon.ico` to for the icon to display next to the page title in the Chrome tab. See https://en.wikipedia.org/wiki/Favicon . Put api request under some endpoint, like `/show/:id`.
