### ISSUE TITLE
Nestjs multiple database connections

### ISSUE THREAD

**Issue by pimane** [Automattic/mongoose#13290]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.3

### Node.js version

16

### MongoDB version

6

### Operating system

macOS

### Issue

Hi,

I've got a database that has accounts (accounts, users, roles, permissions, ...) and flows related to the accounts. We are trying to, if the client wishes, have a different database just for the client data, in this case flows. 

If the account document has a specific mongo uri it should use that for the flows, otherwise it should use the normal connection.

We have a guard to authenticate the users and get his account and would like to connect to the proper database after the guard being called BUT the MongooseService is called before the guard since it's in the app.module.ts:
```
    MongooseModule.forRootAsync({
      connectionName: 'customer',
      useClass: MongooseService,
    }),
```

The MongooseService has:
```
@Injectable({ scope: Scope.REQUEST })
export class MongooseService implements MongooseOptionsFactory {
  constructor(@Inject(REQUEST) private readonly request: IRequest) {}

  createMongooseOptions(): MongooseModuleOptions {
    console.log(
      'MongooseService',
      this.request.date,
      this.request.url,
      this.request.user,
    );
    if (this.request.user.uri) {
      return {
        uri: this.request.user.url,
        useNewUrlParser: true,
        useUnifiedTopology: true,
      };
    } else {
      return { uri: // get uri from .env };
    }
  }
}
```

The flow.module.ts:
```
imports: [
    MongooseModule.forFeature(
      [
        {
          name: Flow.name,
          schema: FlowSchema,
          collection: FLOW_COLLECTION,
        },
      ],
      'customer',
    ),
  ],
```

Our guard has this:
```
...
      // validate token
      const token = this.getToken(request);
      const jwtData = this.jwtService.verify<IJwtData>(token);
...
      let user = await this.teamService.findOne(jwtData.id);
      request.user = user; // here is the database uri or if empty use default
...
```

Is there anyway of using this strategy, using connection names (https://docs.nestjs.com/techniques/mongodb#multiple-databases) or since we need data from the database we need to use a different approach?

Thanks in advance,
Pedro

**Comment by vkarpov15** [comment]
The connection names approach mentioned in the docs you linked (https://docs.nestjs.com/techniques/mongodb#multiple-databases) looks right for cases where you have a separate database for each user.

You should also review [Mongoose's multiple connections docs](https://mongoosejs.com/docs/connections.html#multiple_connections).
