### ISSUE TITLE
After creating a reference between tow collections.throws error when trying to send data using form-data mongoose express 

### ISSUE THREAD

**Issue by JamimahIB** [Automattic/mongoose#13293]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.0

### Node.js version

19.4.0

### MongoDB version

4.11.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

windows 10 HOme

### Issue

using Mongoose express, I have created references between my two collection 'user' and 'prayer' models.My prayer request include image field “image: req.file.filename”. So for creating prayer,I am sending request using form-data,to select image file path, and have provided user’s objectID in “creator” field,  it couldn’t get the objectID of user, I am providing therefore throwing error “could not found UserID” as user ID is being provided in postman request. (screenshot is attached)
But when I am changing field value of image to image:’url’ and sending request using JSON format request proceeds successful. 
Screenshot is attached
I could not understand why this is so. Why it is not processing data when I am using form-data. This is my question. 

![creatorID_Error](https://user-images.githubusercontent.com/130914864/233064133-07a75b83-638b-4445-8245-8ff514ab36ec.png)
![succes_response](https://user-images.githubusercontent.com/130914864/233064200-98ebb902-9656-4fc4-9700-2a9d8c609ee5.png)
![Sucess_req_code](https://user-images.githubusercontent.com/130914864/233064207-f463c475-c18a-45c2-ba4a-41911ba90cbc.png)
![unsuccessResponse](https://user-images.githubusercontent.com/130914864/233064212-f6536888-d03b-474d-92ce-e31d44eeaaed.png)

**Comment by MohOraby** [comment]
Can you try to log the `req.body.creator` and its type, make sure you have something that parses `form-data` and that the `req.body.creator` is not an invalid value that cannot be cast to `ObjectId`

**Comment by JamimahIB** [comment]
Yes issues I am facing indicate that form-data is not parsing id but I have defined the datatypes in Schema model of user as well of prayers. So I think it It should take id of creator. please find attached images. 
![prayers_datatype](https://user-images.githubusercontent.com/130914864/233265581-ecab8740-44f7-48f5-9316-8560c38e6d9b.PNG)
![creator_datatype](https://user-images.githubusercontent.com/130914864/233265584-79fe10f4-906f-4416-b031-f2ca61aa1839.PNG)

**Comment by MohOraby** [comment]
@JamimahIB Are you using any body parser like `multer` to parse form data? the issue is probably your `body.creator` is undefined

**Comment by JamimahIB** [comment]
Yes I am using body parser, I have installed package multer and using it project. yes body.creator is undefined but this should not not when I have define the type of creator and also sending value of objectId while sending request using postman. til then I couldn't get how to resolve this issue, why form-data failed to parse the values provided in post request.

**Comment by MohOraby** [comment]
Your issue is with how you're parsing your body, express' body-parser doesn't parse `form-data`, you're currently try to `findById(undefined)` which returns nothing, please look into how to parse form-data in express

**Comment by JamimahIB** [comment]
ok I check it with.body-parser I am already using .I need to check what else can I use for form-data

**Comment by MohOraby** [comment]
for express you're probably gonna use multer, please check how to parse form-data in express using multer
a simple google search would tell you what you're missing, whether it be wrong headers or wrong use of multer

**Comment by JamimahIB** [comment]
hi I have checked again the with how to parse data using form-data in express. And what I have observed is that I am already using the correct middleware for parsing every request sent to our servers. 
Actually I am facing this problem when I have created reference between user and prayer collections. And after creating references between two collecitons  when I am sending post request to create user it proceed successful but when I am trying to create prayer instead to get user ID  provided in 'creator field' , it is always throwing error "Couldn't find userId" therefore post request is always unsuccessful.
before creating references between two collections everything was working fine.

**Comment by vkarpov15** [comment]
You're calling `User.findById(creator)`, but it doesn't look like `creator` is defined. Can you please try `User.findById(req.body.creator)` ?

**Comment by JamimahIB** [comment]
Thank you all for your help and support. It will help me to understand many things related how to create relationship using mongoose. Well fro time being I have sorted out this issue by creating relationship between prayer and user(one-to-one relationship) .
