### ISSUE TITLE
change schema-type class names to be consistent

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#13309]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Currently schema types may or may not have the prefix `Schema`, this issue tracks to consistenize all types to be named in the same style.

types that do have the prefix:
- `lib/schema/buffer.js` named `SchemaBuffer`
- `lib/schema/string.js` named `SchemaString`
- `lib/schema/date.js` named `SchemaDate`
- `lib/schema/number.js` named `SchemaNumber`
- `lib/schema/uuidjs` named `SchemaUUID`

types that currently dont have the prefix:
- `lib/schema/decimal128.js` named `Decimal128`
- `lib/schema/documentarray.js` named `DocumentArrayPath`
- `lib/schema/map.js` named `Map`
- `lib/schema/mixed.js` named `Mixed`
- `lib/schema/objectid.js` named `ObjectId`

personally i think those that do not have the prefix currently, should get it instead of removing it from those that have it

**Comment by mjfwebb** [comment]
@hasezoey this one too :sweat_smile:
