### ISSUE TITLE
Impossible to change the field not presented in the not strict schema by a direct assignment.

### ISSUE THREAD

**Issue by painkkiller** [Automattic/mongoose#13315]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.3

### Node.js version

16.13.2

### MongoDB version

6.0.5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10 Pro 21H2

### Issue

The whole problem described in this stackoverflow question https://stackoverflow.com/questions/76065281/mongoose-7-0-3-how-to-update-subdocument-with-not-strict-schema
After updating Mongoose from 5.x till 7.0.3 version I've found that I am unable to change fields not included in the schema directly. Maybe I  missed something? But I don't want such behavior.

**Comment by vkarpov15** [comment]
Replace:

```javascript
const CurrentState = {
    NameOfProduct: { type: String },
    ResearcherName: { type: String },
    CollectedDate: { type: String },
    Url: { type: String },
    AuditNumber: { type: Number },
    ImageLinks: {type: mongoose.Schema.Types.Mixed},
    start_date: { type: Date },
    currency_to: { type: String } // originally not in schema
};

const Product = new mongoose.Schema({
    RecordId: { type: Number },
    CurrentState: { type: CurrentState, strict: false },
}, { strict: false, versionKey: false, minimize: false});
```

With:

```javascript
const CurrentState = new Schema({
    NameOfProduct: { type: String },
    ResearcherName: { type: String },
    CollectedDate: { type: String },
    Url: { type: String },
    AuditNumber: { type: Number },
    ImageLinks: {type: mongoose.Schema.Types.Mixed},
    start_date: { type: Date },
    currency_to: { type: String } // originally not in schema
}, { strict: false }); // <-- move strict here

const Product = new mongoose.Schema({
    RecordId: { type: Number },
    CurrentState: { type: CurrentState }, // <-- remove strict here
}, { strict: false, versionKey: false, minimize: false});
```

In Mongoose 5, `CurrentState: { type: CurrentState, strict: false },` was equivalent to `CurrentState: { type: 'Mixed' },` , so no schema validation on `CurrentState`. In Mongoose 7, `CurrentState: { type: CurrentState, strict: false },` makes `CurrentState` a subdocument, but we don't support configuring `strict` on a subdocument schema path like that.
