### ISSUE TITLE
Propagate `toObject` and `toJSON` options to implicitly created schemas

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#13325]
### Discussed in https://github.com/Automattic/mongoose/discussions/13303

<div type='discussions-op-text'>

<sup>Originally posted by **skrishnan22** April 20, 2023</sup>
These are my schemas

user.js
```js
const mongoose = require("mongoose");

const schema = new mongoose.Schema(
  {
    firstName: String,
    companies: {
      type: [
        {
          companyId: {
            type: mongoose.Schema.Types.ObjectId,
          },
          companyName: String,
        },
      ],
      required: true,
    },
  },
  {
    toObject: {
      virtuals: true,
    },
  }
);


schema.virtual("companies.details", {
  ref: "company",
  localField: "companies.companyId",
  foreignField: "_id",
  justOne: true,
});

schema.set("collection", "users");

module.exports = mongoose.model("user", schema);
```

company.js
```js
const mongoose = require("mongoose");

const schema = new mongoose.Schema({
  name: {
    type: String,
  },
  legalName: {
    type: String,
    required: true,
  },
});

schema.set("collection", "companies");

module.exports = mongoose.model("company", schema);
```
On running 

> User.findOne({firstName:'ABC'}).populate('companies.details');

in mongoose 5, **companies.details** is being populated correctly, but in mongoose 6 the populate is not happening

The populate works in mongoose 6, if I change the User schema as below. Note the change to **companies** field
```js
const mongoose = require("mongoose");

const schema = new mongoose.Schema(
  {
    firstName: String,
    email: String,
    companies: {
      type: [{}],
      required: true,
    },
  },
  {
    toObject: {
      virtuals: true,
    },
  }
);

schema.virtual("companies.details", {
  ref: "company",
  localField: "companies.companyId",
  foreignField: "_id",
  justOne: true,
});

schema.set("collection", "users");

module.exports = mongoose.model("user", schema);

```
Is this expected change when migrating from 5 to 6 and if so what is the best way to make it work with versions 6 and above</div>

**Comment by IslandRhythms** [comment]
This bug is also present on mongoose 7. What's interesting is that although it won't print to the console when you view the entire doc, the property is still there when you attempt to access that specific property.

```javascript
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    firstName: String,
    companies: {
      type: [
        {
          companyId: {
            type: mongoose.Schema.Types.ObjectId,
          },
          companyName: String,
        },
      ],
      required: true,
    },
  },
  {
    toObject: {
      virtuals: true,
    },
    toJSON: { virtuals: true }
  }
);

// const userSchema = new mongoose.Schema(
//   {
//     firstName: String,
//     email: String,
//     companies: {
//       type: [{}],
//       required: true,
//     },
//   },
//   {
//     toObject: {
//       virtuals: true,
//     },
//   }
// );


userSchema.virtual("companies.details", {
  ref: "company",
  localField: "companies.companyId",
  foreignField: "_id",
  justOne: true,
});

userSchema.set("collection", "users");

const User = mongoose.model("user", userSchema);


const companySchema = new mongoose.Schema({
  name: {
    type: String,
  },
  legalName: {
    type: String,
    required: true,
  },
});

companySchema.set("collection", "companies");

const Company = mongoose.model("company", companySchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const company = await Company.create({
    name: 'Google',
    legalName: 'Alphabet Inc'
  });
  const user = await User.create({
    firstName: 'Test',
    companies: [{ companyId: company._id, companyName: 'Google' }]
  });

  const test = await User.findOne().populate('companies.details');
  console.log('what is test', test, test.companies[0].details);
}

run();
```

**Comment by vkarpov15** [comment]
@IslandRhythms that's because you're missing a `toObject({ virtuals: true })`. `console.log('what is test', test.toObject({ virtuals: true }), test.companies[0].details);`

**Comment by vkarpov15** [comment]
Good point. `companies` is an array of subdocuments, and subdocuments have their own schema. But we should consider propagating `toObject` and `toJSON` to implicitly created schemas, like we do with `strict`, etc.

**Comment by hasezoey** [comment]
should there also be a way to pass down options for `toObject` / `toJSON` to explicit schemas and not just via the explicit schemas schema-options? (to not require a workaround like for https://github.com/typegoose/typegoose/discussions/835?converting=1#discussioncomment-5918276)

**Comment by vkarpov15** [comment]
@hasezoey 2 ideas come to mind:

1. An `inheritParentSchemaOptions` option for nested schemas
2. A global option to make child schemas inherit the same set of schema options that we pass to implicitly created schemas. This could also be achieved with a plugin.
3. Just a thought: would it be possible for Typegoose to use implicitly created schemas, or is that not easy?

**Comment by hasezoey** [comment]
> Just a thought: would it be possible for Typegoose to use implicitly created schemas, or is that not easy?

i think it would be possible, but was asking about a general option so that when calling `doc.toObject({ virtual: true })` all subdocuments would also have virtuals shown, even if they dont have explicit schema-options set

**Comment by vkarpov15** [comment]
AFAIK that's not a problem, `doc.toObject({ virtuals: true })` would apply virtuals on _all_ subdocuments, because the `toObject()` function's options always overwrite the schema-level `toObject` options.
