### ISSUE TITLE
Cast data at the population process

### ISSUE THREAD

**Issue by Andrey-Yur** [Automattic/mongoose#13331]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.3

### Node.js version

18.16.0

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Issue

I retrieve data by query: 
```
const map = await Map.findOne({_id: mapId }, null, {
      lean: true
    })
      .populate([
        {
          path: 'edgesID',
          model: 'Edges',
          select: '-_id',
          populate: { path: 'dataChunks', model: 'DataChunk', select: '-_id' }
        },
        {
          path: 'businessesID',
          model: 'Business',
          select: '-_id',
          populate: { path: 'dataChunks', model: 'DataChunk', select: '-_id' }
        },
        {
          path: 'residencesID',
          model: 'Residences',
          select: '-_id',
          populate: { path: 'dataChunks', model: 'DataChunk', select: '-_id' }
        },
        {
          path: 'heuristicID',
          model: 'Heuristic',
          select: '-_id',
          populate: { path: 'dataChunks', model: 'DataChunk', select: '-_id' }
        }
      ])
      .orFail(() => responseFailedHelper.getJsonNotFoundResponse('Map'));
```
and get, for examle, some population data in format: 
```
-------
"businessesID": {
    "dataChunks": [
      {
        "data": [
          {
            "x": -446.61792165537224,
            "y": 514.2348027597568,
            "geometry": 28.647921667707458,
            "pid": 888888888,
            "population": 1,
            "location_sigma": 0,
            "begin_hour": 8,
            "end_hour": 5,
            "hour_sigma": 0,
            "type": "communityborder",
            "landmark": null
----------
```
but I need: 
----------
```
"businesses": [
          {
            "x": -446.61792165537224,
            "y": 514.2348027597568,
            "geometry": 28.647921667707458,
            "pid": 888888888,
            "population": 1,
            "location_sigma": 0,
            "begin_hour": 8,
            "end_hour": 5,
            "hour_sigma": 0,
            "type": "communityborder",
            "landmark": null
------------
```
I know how to make that in the aggregation pipline at $project or $set steps, but could not find info regarding casting data at population. Could you help me? Also would be grateful if provided any suggestions, advices to improve speed of receiving data from db. Might be an aggregate function will be faster?

**Comment by vkarpov15** [comment]
Try [virtual populate](https://mongoosejs.com/docs/populate.html#populate-virtuals), make `businesses` a virtual and call `populate('businesses')` instead of populating `businessesID`. Add a getter to the virtual to transform.

Something like:

```javascript
mapSchema.virtual('businesses', {
  ref: 'Edges',
  localField: 'businessesID',
  foreignField: '_id',
  justOne: false
}).get(v => v.dataChunks)
```

**Comment by Andrey-Yur** [comment]
Thanks @vkarpov15! I'll try.

**Comment by Andrey-Yur** [comment]
@vkarpov15  I've tried, but got :
![image](https://user-images.githubusercontent.com/62293778/235029681-b6230b9f-9ff7-40ed-9d5c-6f3aa4ca7487.png)
Might be my fault, I did not explain clearly. Our db has this structure:
![image](https://user-images.githubusercontent.com/62293778/235031709-5007eab3-7441-401f-b463-b93bb6d12db6.png)

**Comment by Andrey-Yur** [comment]
After I put:
![image](https://user-images.githubusercontent.com/62293778/235282648-d10a6744-7929-4e90-9a56-5913ea7f3bd0.png)
I got the populated  'dataChunks', but anyway could not get the transformed data by the `getter` function:
![image](https://user-images.githubusercontent.com/62293778/235282685-2963c149-072e-43db-8807-8cb2695c38ef.png)
