### ISSUE TITLE
Auto Encryption in Mongoose schema

### ISSUE THREAD

**Issue by aseemmohds** [Automattic/mongoose#13333]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7

### Node.js version

14

### MongoDB version

5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

Hi am using mongoose shema model and integrated json schema under createCollection method for automatic encryption purpose, but if I want to add new encrypt fields I need to drop collection and recreate it.
How to add new fields for encryption with out dropping collection or is there any other way to implement automatic encryption using mongoose shema pls suggest

**Comment by Andrey-Yur** [comment]
looks like you should just establish setter for that field

**Comment by vkarpov15** [comment]
Try [collMod](https://www.mongodb.com/docs/manual/reference/command/collMod/)
