### ISSUE TITLE
AggregationCursor from collection is missing method eachASync

### ISSUE THREAD

**Issue by andrewlorenz** [Automattic/mongoose#13334]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.5

### Node.js version

16.14.2

### MongoDB server version

5.0.12

### Description

The observed behaviour of an AggregationCursor from a collection does not align with the documentation at https://mongoosejs.com/docs/api/aggregationcursor.html

### Steps to Reproduce

```
const myDb = await mongoose.createConnection(...)
const myModel = myDb.model('my_collection', Schema)
const myCollection = myDb.collection('my_collection');

const modelA = await myModel.aggregate([ { $match: { name: /test/i } ]);
// modelA contains an array of 1 document as expected

const collFind = await myCollection.find({ name: 'Test' });
// collFind contains 1 document as expected

const collA = await myCollection.aggregate([ { $match: { name: /test/i } ]);
// collA contains an AggregationCursor object

collA.eachAsync(doc => console.log(doc)); - fails is not a function
```
However, the next() and asyncIterator DO work:
```
const doc = await collA.next();   // doc contains 1 document
for await (const doc of collA) {
  console.log('doc', doc);    // each doc of collection is output
}
```

### Expected Behavior

The AggregationCursor object is expected to be in line with the documentation, but the eachASync method is missing.
Per the documentation, addCursorFlag and close methods are also available to call.

**Comment by vkarpov15** [comment]
What indicates to you that `const collA = await myCollection.aggregate([ { $match: { name: /test/i } ]);` means `collA` is an AggregationCursor instance? `await Model.aggregate()` returns the results of the aggregation, **not** a cursor.

Here's how you get an aggregation cursor:

```javascript
    const cursor = MyModel.
      aggregate([{ $match: { name: 'test' } }, { $project: { name: '$name' } }]).
      cursor();

    await cursor.eachAsync(doc => console.log(doc));
```

**Comment by andrewlorenz** [comment]
I specifically said collection in my title and the description.  I have clearly shown in my sample code that accessing via the model works, but NOT when accessing the collection directly. That is what my ticket was about.

**Comment by vkarpov15** [comment]
I'm sorry, I misread.

That's because `collection.aggregate` returns a [MongoDB Node driver AggregationCursor instance](https://mongodb.github.io/node-mongodb-native/Next/classes/AggregationCursor.html), not a Mongoose AggregationCursor instance. Once you use `collection.`, you bypass everything Mongoose specific, including the `eachAsync()` helper for cursors.

**Comment by andrewlorenz** [comment]
Just to finish this off, and in case it helps anyone who hits this thread for info, the page https://mongoosejs.com/docs/api/connection.html#Connection.prototype.collection() documents that this method returns a "Collection" collection instance, and provides no further information, but advises to using a model instead.
There are however valid use cases for accessing collections directly (e.g. in my case, I am running only aggregates against collections and therefore don't want or need to include the models for those in the code), and in these cases you should refer instead to the mongodb node driver https://mongodb.github.io/node-mongodb-native
