### ISSUE TITLE
Getter function does not work on property was specified a virtual with a `ref` property

### ISSUE THREAD

**Issue by Andrey-Yur** [Automattic/mongoose#13342]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.3

### Node.js version

18.16.0

### MongoDB server version

6.0.5

### Typescript version (if applicable)

n/a

### Description

I've tried to implement the @vkarpov15 suggestion for transforming a virtual property from the ticket #13331, but did not get the expected result. Looks like, the getter function does not work. Options `toJSON` and `toObject` were established for virtual to `true` in schemas. 

### Steps to Reproduce

Establish a virtual with a `ref` property and  the getter for formatting by using the virtual method. Try to populate that virtual property.

**Comment by vkarpov15** [comment]
@Andrey-Yur can you please provide a code sample that demonstrates the issue you're seeing? And also please provide what the expected and observed results are?

**Comment by Andrey-Yur** [comment]
`const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const studentSchema = Schema(
  {
    name: String,
    age: Number,
    stories: [{ type: Schema.Types.ObjectId, ref: 'Story' }]
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

const storySchema = Schema(
  {
    title: String
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

studentSchema
  .virtual('bestStories', {
    ref: 'Story',
    localField: 'stories',
    foreignField: '_id',
    justOne: false
  })
  .get((v) => v + '_best');

const Story = mongoose.model('Story', storySchema);

const Student = mongoose.model('Student', studentSchema);

async function run() {
  const student = new Student({
    name: 'Ian',
    age: 50
  });

  const story = new Story({
    title: 'His story'
  });

  student.populate('bestStories');
  console.log(student);
  console.log(student.name);
  console.log(student.bestStories);
}
run();`

**output**

![image](https://user-images.githubusercontent.com/62293778/235728918-250d3262-7309-4abc-9171-f5ba76284235.png)

**Comment by Andrey-Yur** [comment]
Good day @vkarpov15 ! 

`const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const studentSchema = Schema(
  {
    name: String,
    age: Number,
    stories: { type: Schema.Types.ObjectId, ref: 'Story' }
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

const storySchema = Schema(
  {
    title: String
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

studentSchema
  .virtual('bestStories', {
    ref: 'Story',
    localField: 'stories',
    foreignField: '_id',
    justOne: false
  })
  .get((v) => v + '_best');

const Story = mongoose.model('Story', storySchema);

const Student = mongoose.model('Student', studentSchema);

async function run() {
  const student = new Student({
    name: 'Ian',
    age: 50
  });

  const story = new Story({
    title: 'His story'
  });

  console.log('STORY:', story);

  student.populate('bestStories');

  console.log(student);
  console.log(student.name);
  console.log(student.bestStories);
}
run();`

**OUTPUT:**
![image](https://user-images.githubusercontent.com/62293778/235730560-9828e044-d0a9-4df6-840f-0dfe50afea1e.png)

**Comment by vkarpov15** [comment]
@Andrey-Yur there's numerous issues with the script you provided: you're not connecting to MongoDB, you're not saving any documents, you're calling `populate()` without `await`, and `v` will be an array in the virtual getter.

Try the following script and see if it is closer to what you're trying to get at.

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const studentSchema = Schema(
  {
    name: String,
    age: Number,
    stories: { type: Schema.Types.ObjectId, ref: 'Story' }
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

const storySchema = Schema(
  {
    title: String
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

studentSchema
  .virtual('bestStories', {
    ref: 'Story',
    localField: 'stories',
    foreignField: '_id',
    justOne: false
  })
  .get((v) => {
    return v.map(story => ({ ...story.toObject(), title: story.title + '_best' }));
  });

const Story = mongoose.model('Story', storySchema);

const Student = mongoose.model('Student', studentSchema);

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test'); 

  const story = new Story({
    title: 'His story'
  });
  await story.save();
  console.log('STORY:', story);

  const student = new Student({
    name: 'Ian',
    age: 50,
    stories: [story._id]
  });
  await student.save();
  await student.populate('bestStories');

  console.log(student);
  console.log(student.name);
  console.log(student.bestStories);
}
run();
```
