### ISSUE TITLE
Empty array is saved when a property references a schema

### ISSUE THREAD

**Issue by lookfirst** [Automattic/mongoose#1335]
```
var FooSchema = new Schema({});
var Foo = mongoose.model("Foo", FooSchema);
var BarSchema = new Schema({
    foos: [Foo.schema]
});
var Bar = mongoose.model("Bar", BarSchema);

var b = new Bar();
b.save();
```

That will create an empty array of b.foos instead of just leaving the property undefined.

**Comment by viking** [comment]
This is still an issue for me using 4.0.1.

**Comment by viking** [comment]
```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var barSchema = new mongoose.Schema({
  baz: String
});

var fooSchema = new mongoose.Schema({
  bars: [barSchema]
});

var Foo = mongoose.model('Foo', fooSchema);

var foo = new Foo();
console.log(foo); // { _id: 55256e20e3c38434687034fb, bars: [] }

foo.save(function(err, foo2) {
  console.log(foo2); // { __v: 0, _id: 55256e20e3c38434687034fb, bars: [] }

  foo2.bars = undefined;
  foo2.save(function(err, foo3) {
    console.log(foo3); // { __v: 0, _id: 55256e20e3c38434687034fb, bars: undefined }

    Foo.findOne({ _id: foo3._id }, function(err, foo4) {
      console.log(foo4); // { _id: 55256e20e3c38434687034fb, __v: 0, bars: [] }

      mongoose.disconnect();
    });
  });
});
```

**Comment by lookfirst** [comment]
@viking It was never 'fixed'. [A workaround was provided](https://github.com/Automattic/mongoose/issues/1335#issuecomment-13254654). You should test to see if that workaround still works since there is conflicting information about that. =)

**Comment by viking** [comment]
I already have a workaround in place. I'm interested in knowing if this behavior will change or not.

**Comment by lookfirst** [comment]
Sorry, you didn't say you wanted to know if the behavior will change or not.

I'm actually not sure why this issue was re-opened by @vkarpov15 , which does beg the question of whether this behavior will change or not. I think the issue is backwards compatibility. It probably should have been decided before 4.x went out.

**Comment by vkarpov15** [comment]
Yeah this behavior won't change in the near future. I re-opened this issue so I knew to investigate it when I got a chance, because I make sure to understand what's going on with every comment that comes in to the mongoose github and this was one that I didn't have a good answer to off the top of my head. Looking more closely, we can't really change this in the near future because of semver, but something to investigate if it's a pain point for a lot of users.

**Comment by phamtec** [comment]
I have used this workaround with a twist because sometime you WANT to write an empty array and sometimes not.

So My presave looks like this:
```
		var ideaSchema = mongoose.Schema(schema.ideaSchema);
		// turn off the saving of empty children if there are no children in the schema.
		ideaSchema.pre('save', function (next) {
		  	if (this.isNew) {
		  		if (this.children.length == 0) {
					this.children = undefined;       
				}
				else if (this.children.length == 1 && this.children[0] == null) {
					this.children = [];
				}                                                                                                                    
		  	}
		  	next();
		});
```

And then to write empty children I use this:

```
idea.children = [null];
```

Whereas this is stripped:

```
idea.children = [];
```

This might not work for you but you should be able to come up with some other type of scheme.

**Comment by viking** [comment]
This is a pretty big problem when you have arrays inside nested objects.

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var quxSchema = new mongoose.Schema({ qux: String });
var fooSchema = new mongoose.Schema({ foo: { bar: { baz: [ quxSchema ] } } });
var Foo = mongoose.model('Foo', fooSchema);

var foo = new Foo({foo: undefined})
foo.save(function(err, foo) {
  console.log(JSON.stringify(foo)); // {"__v":0,"_id":"557ae56480f047fd4ff4ab26","foo":{"bar":{"baz":[]}}}
  Foo.find({ _id: foo._id }, function(err, foos) {
    console.log(JSON.stringify(foos[0])); // {"_id":"557ae56480f047fd4ff4ab26","__v":0,"foo":{"bar":{"baz":[]}}}
  });
});
```

Here I expect `foo` to be missing, and instead I have this nested object with an empty array.

**Comment by phamtec** [comment]
But can't a pre save help you here? rather than having {foo: undefined} you could use a unique type of foo to signify a null foo, and then strip out the foo in the presave.

**Comment by simllll** [comment]
I just ran into the same issue like @viking did. did you find any useable workaround?

i tried it with the 'pre' save way.. but it still occurs sometimes, I'm not sure how many different usecases I have to cover to get this done. My biggest problem out of this is that the JSON should actually deliver an object, and not an array. this is a fatal exception for my json parser which tries to map these things to java objects.

regards

**Comment by phamtec** [comment]
I think you can make this work, obviously not with the presave that I posted, because that involved children being an array not an object. I haven't tried this, but wouldn't it be possible to actually use a "duck typing" Empty object to signify an ACTUAL empty one?

So your presave might be:

    if (this.isNew) {
        if (typeof(this.filter.empty) != "undefined") {
            this.filter = {};
        }
    }

Then to make an actual empty filter you could use:

    var obj = new modelA();
    obj.filter = { empty: true };
    obj.save();

Note that it doesn't actually matter if the schema doesn't have "empty" in it, it never makes it to mongoose.

**Comment by simllll** [comment]
Somehow I managed a way to overcome the issue .. I actually did something very similar. Just saw your answer though and wanted to say thank you :)

regards
Simon

**Comment by maxko87** [comment]
I was having a lot of problems with this solution when there were nested schemas with optional `Array` fields. I solved this by creating a new type:

    optional_array = 
      type: Mixed
      validate: 
        validator: (v) ->
          return v instanceof Array
        message: '{VALUE} needs to be an array.'

and then setting all my fields to `optional_array` instead of `Array`.

**Comment by viking** [comment]
@simllll I use a `null` placeholder for missing objects and then remove the `null` before using the object.

**Comment by ifeltsweet** [comment]
Sorry, but this is a horrible design. You should not be deciding on my behalf wether I want it to be an empty array or not set at all. At least provide an option to disable this feature.

**Comment by dpaczewski** [comment]
Agree with @ifeltsweet

**Comment by antonioaltamura** [comment]
After months, there is a proper solution without pre hook? I have dozens of array fields, I should handle one by one in a pre hook...

**Comment by vkarpov15** [comment]
@antonioaltamura I forgot about this issue, the below works in mongoose 4.6:

```javascript
const CollectionSchema = new Schema({
 field1: { type: [String], default: void 0 }, // <-- override the array default to be undefined
});

const Collection = mongoose.model('test', CollectionSchema);

Collection.create({}).
  then(doc => { console.log(doc); return doc; }).
  then(() => { process.exit(0); });
```

**Comment by cpup22** [comment]
@vkarpov15 your fix doesn't work for me on mongoose 4.7.0.  Still working okay for you? It doesn't include the value on new object creation but when I do a Model.save it tries to add it in again.

**Comment by vkarpov15** [comment]
@cpup22 can you provide a code sample? [The referenced script](https://github.com/Automattic/mongoose/issues/1335#issuecomment-252129243) works fine for me on 4.7.1.

**Comment by binki** [comment]
I think the workaround from https://github.com/Automattic/mongoose/issues/2363#issuecomment-171988413 is much cleaner. It allows defaulting to `null` even when `default: null` fails:

```javascript
const CollectionSchema = new Schema({
  field1: { type: [String] },
});
CollectionSchema.methods.postconstructed = function () {
  this.field1 = null;
};
CollectionSchema.queue('postconstructed');

const Collection = mongoose.model('test', CollectionSchema);

Collection.create({}).then(doc => { console.log(doc); process.exit(0) });
```

**Comment by binki** [comment]
Never mind, it doesn’t work when passing in a value (e.g., `new Collection({ field1: [] })` gets `field1 === null`. If only there were a construction hook that happened before the passed in data was applied and after the default empty array is created. Or this bug were fixed to allow `default: null` for arrays.

**Comment by binki** [comment]
Oh, looks like this works:

```javascript
const CollectionSchema = new Schema({
  field1: { type: [String], default: () => null },
});
```

The array type thing respects functions more sincerely than values. This has no issue with overwriting a passed-in `null`, `[]`, or non-empty array value via `Collection.create()` or `new Collection()`.

**Comment by vikramkalta** [comment]
@vkarpov15 hello there, so even if i change the key value for type array to null in my mongoose schema before mongo db saves a document, and when the array is empty it saves as key = null.
you have any solutions

**Comment by vkarpov15** [comment]
@vikramkalta please provide code samples, prose to code conversions are error prone.

**Comment by keyboard99** [comment]
Hi, I'm using the mongoose 4.6.5 and still to save a empty array with these solutions.

`services: [{
    type: Schema.Types.ObjectId,
    ref: 'Service',
    default: () => null
  }],`

`services: [{
    type: Schema.Types.ObjectId,
    ref: 'Service',
    default: void 0
  }],`

**Comment by vkarpov15** [comment]
@keyboard99 please follow the instructions in https://github.com/Automattic/mongoose/issues/1335#issuecomment-252129243 . your code sets a default for the individual array elements, not for the array itself

**Comment by vkarpov15** [comment]
@GeneralG any complications other than the obvious one of having to do `doc.array = doc.array || [];` before calling `push()`?

**Comment by sergiomarcano** [comment]
> Somehow I managed a way to overcome the issue .. I actually did something very similar. Just saw your answer though and wanted to say thank you :)
> 
> regards Simon

Hello Simon, could you please post what you did that was "similar"? 

Thanks a lot

**Comment by simllll** [comment]
It's 8 years ago, hard to remember.  But i guess it was something like this
if (this.isNew) {
    if (typeof(this.filter.empty) != "undefined") {
        this.filter = {};
    }
}

Besides this i can say we disabled almost all mongoose helper / magics (e.g timestamp, etc) because there was often some side effect we were not expecting... So maybe there is a flat that disables this behavior too (can't remember right now)

**Comment by sergiomarcano** [comment]
I want to share the solution that worked for me, Just in case someone comes across this post. 

This one is referencing another schema as a subschema. 

    runtimeParams:{
        type:[param],
        required:false,
        default:()=> undefined
    },

This one is a plain string array. 

        stages:{
            type:[String],
            required:false,
            default:()=> undefined
        },

It was mentioned above but with void 0 that did not work for me. 

@simllll  Thanks a lot for answering even though its been so long since it happened.  👍

**Comment by vkarpov15** [comment]
@sergiomarcano you're right, `default: () => undefined` is one way to make Mongoose not create an empty array by default. Glad you figured that out.
