### ISSUE TITLE
Property 'Types' does not exist on type 'typeof Schema'.

### ISSUE THREAD

**Issue by nbdavies** [Automattic/mongoose#13350]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.3.3

### Node.js version

16.18.1

### MongoDB server version

5.0

### Typescript version (if applicable)

4.9.5

### Description

Importing mongoose or pieces thereof causes typescript errors. For example, copy/pasting the example code found in the Mongoose docs: https://mongoosejs.com/docs/typescript.html#objectids-and-other-mongoose-types
...causes an error `Property 'Types' does not exist on type 'typeof Schema'`. It's something funky in the type definitions perhaps, because Schema.Types does seem to exist

### Steps to Reproduce

I plugged the example found [here](https://mongoosejs.com/docs/typescript.html#objectids-and-other-mongoose-types) into a .ts file and ran tsc on it. It produces this error:
```
src/x_mongoose_example.ts:16:32 - error TS2339: Property 'Types' does not exist on type 'typeof Schema'.

16   organization: { type: Schema.Types.ObjectId, ref: 'Organization' }
```

### Expected Behavior

When pieces of Mongoose are imported as recommended in the Mongoose docs:
```
import { Schema, Types } from 'mongoose';
```
Those should not raise typescript errors for lacking things that they do in fact include (right?)

**Comment by IslandRhythms** [comment]
unable to reproduce on mongoose 6.3.3 and mongoose 7.1.0

```typescript
import { Schema, Types } from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface IUser {
  name: string;
  email: string;
  // Use `Types.ObjectId` in document interface...
  organization: Types.ObjectId;
}

// 2. Create a Schema corresponding to the document interface.
const userSchema = new Schema<IUser>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  // And `Schema.Types.ObjectId` in the schema definition.
  organization: { type: Schema.Types.ObjectId, ref: 'Organization' }
});
```
