### ISSUE TITLE
Make `Model.prototype.deleteOne()` return a query, not a promise, to be consistent with `Model.prototype.updateOne()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#13369]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Re: #13367, #13223.

**Comment by suprith-s-reddy** [comment]
Hello I have a similar issue with deleteOne but its a weird one.

When I execute deleteOne it throws 

`MongooseError: Query was already executed: RoleAssignment.findOneAndUpdate({\n  organisationId: new Obje.`

My code runs two operations one after the other.

`  const [allAdminUsers] = await this.roleAssignmentModel
      .aggregate(pipeline.stages)
      .exec();

const removedRoleAssign = await this.roleAssignmentModel
      .deleteOne(filter)
      .exec();
`
I don't use findOneAndUpdate but still get that error when deleteOne executes. I also tried using .clone(), but I keep getting this issue. Is there a fix for this one?

How do I go about this?
