### ISSUE TITLE
Custom debug function missing last method argument

### ISSUE THREAD

**Issue by hieule3004** [Automattic/mongoose#13364]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x.x

### Node.js version

18.x

### MongoDB server version

5

### Typescript version (if applicable)

5

### Issue
https://github.com/Automattic/mongoose/blob/aaacf466bb0ad633c7e9b497458045a6e5c12558/lib/drivers/node-mongodb-native/collection.js#L212
Logging with custom log function missing last argument due to incorrect slicing index.

### Potential fix
Clone array with `args.slice(0, args.length)`

### Risk
- May require existing code to add redact action on large objects such as `session` which happen to be in last argument

### Steps to Reproduce

```
import { connect } from 'mongoose';
import * as util from 'util';

(async () => {
  const MONGO_CONNECTION_STRING = 'mongodb://localhost:27017/db?&directConnection=true';
  const mongoose = await connect(MONGO_CONNECTION_STRING);

  mongoose.set('debug', (collectionName, methodName, ...methodArgs) => {
    console.log(`${collectionName}.${methodName}(${util.inspect(methodArgs).slice(2, -2)})`);
  });

  const collection = mongoose.connection.collection('Test');
  await collection.findOne({ key: 'value' });

  await mongoose.connection.close();
})();
```

### Expected Behavior
Expect: print `Test.findOne({ key: 'value' })`
Actual: print `Test.findOne()`

**Comment by forivall** [comment]
I also see this happening in mongoose 6.8.0 - I'll submit a PR to backport the fix before the August eol date 😄
