### ISSUE TITLE
Issues with sub documents failing validation after upgrading to 7.1.0

### ISSUE THREAD

**Issue by mfinkenzeller** [Automattic/mongoose#13371]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.1.0

### Node.js version

v18.16.0

### MongoDB server version

4.4

### Description

Working on migrating to 7.1.0. Almost all validations fail on sub documents when trying to save data to the DB. The error is 
```
errors: {
    items: TypeError: Proxy is not a constructor
```

Here is the Schema. Super simple...

const LineItem = new Schema({
    productId: String,
    productName: String,
    productLine: String,
    quantity: Number,
    unitPrice: Number
});

const TransactionSchema = new Schema({
    transactionId: String,
    items: [LineItem]
});

It seems if I have an array property in the Schema that is NOT required it fails. And if I send in { 'items': [] } in the JSON for example then it fails with a different error

`items: CastError: Cast to Array failed for value "[]" (type Array) at path "items" because of "TypeError")`

### Steps to Reproduce

// In this case 'order' is the raw JSON

new Transaction(order).save().then(function (aorder) {
  // YA!!
}).catch(function (err) {
  // Puke
  console.log(err);
});

**Comment by mfinkenzeller** [comment]
Non-issue. Was a name collision with Proxy from another library. Resolved

**Comment by vkarpov15** [comment]
Just for our info, what library was causing this name collision?
