### ISSUE TITLE
Make sure MongooseError is exported in TypeScript

### ISSUE THREAD

**Issue by kspshnik** [Automattic/mongoose#13387]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A tool to detect if error is MongooseError.
The most simple approach is to check `if (error instanceof MongooseError)`. But unfortunately this class is not exported, so one need to check if error is instance of all the exported descendants of it.
The idea is to export a very simple member:

```js

const ifMongooseError = (error: Error) : boolean => error instanceof MongooseError;

``` 

This will allow to find out if it's Mongoose's error and do not lead to leaking of private MongooseError class.

### Motivation

Sometimes one need to transform thrown by Mongoose and caught in `.catch()`/`catch` or passed to errors handler(s) by `.catch(next)` (if using Express). It would be very nice to have a tool to detect if it's a Mongoose error, since several sources of error might exist in the same controller, like celebrate does (celebrate.isCelebrateError() method).
At present, I use a helper that check against all 16 types of errors. It would be way more refined and elegant to have a built-in Mongoose method.

### Example

```js

// ...somewhere in errors handler

elseif (mongoose.isMongooseError(error)) {
 /* Process, transform and/or send to client error */
}

```

**Comment by kspshnik** [comment]
> I'm just wondering if `Error` and `MongooseError` are different in any way. If so, pardon me for the lack of knowledge.

Isn't it actually a **Mongo** error in your snippet? They're different. I meant Mongoose errors descrbed in docs here: https://mongoosejs.com/docs/api/error.html#Error()

And its not a TS solution anyway %(

**Comment by ramos-ph** [comment]
I see. I changed my snippet using the example of the docs:

```ts
import mongoose from 'mongoose';

const Model = mongoose.model('model', new mongoose.Schema({ answer: Number }));

async function main() {
  const doc = new Model({ answer: 'not a number' });
  const err = doc.validateSync();

  console.log(err instanceof mongoose.Error); // true
  console.log(err instanceof mongoose.MongooseError); // true
  console.log(err instanceof mongoose.Error.ValidationError); // true
}

main();
```

I'm exporting `MongooseError` the same way, but I didn't noticed any TypeScript changes when I changed `errors.d.ts`. I'll update my PR.

**Comment by kspshnik** [comment]
> I'm exporting `MongooseError` the same way, but I didn't noticed any TypeScript changes when I changed `errors.d.ts`. I'll update my PR.

It seems to me to be more useful to have an exported helper function in the same way they did it in Celebrate. I mean something like `isMoongoseError( error: Error ) : boolean` that performs all the required underneath.

**Comment by ramos-ph** [comment]
> It seems to me to be more useful to have an exported helper function in the same way they did it in Celebrate. I mean something like `isMoongoseError( error: Error ) : boolean` that performs all the required underneath.

It's something that @vkarpov15 suggested on my PR. I originally had implemented a `isMongooseError` util.
Here's the comment for reference: https://github.com/Automattic/mongoose/pull/13403#pullrequestreview-1427560361

**Comment by kspshnik** [comment]
> It's something that @vkarpov15 suggested on my PR. I originally had implemented a `isMongooseError` util.
OK, I see.

Thank you!
