### ISSUE TITLE
$unset does not remove updatedAt

### ISSUE THREAD

**Issue by FeelHippo** [Automattic/mongoose#13394]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.12.14

### Node.js version

14.21.3

### MongoDB server version

4.4.21

### Description

I am trying to remove `createdAt` and `updatedAt` from a collection, as we are going for a different nomecalture.

this works:

`await collection.updateOne(filter, { $unset: { createdAt: "" } });`

this doesn't works:

`await collection.updateOne(filter, { $unset: { updatedAt: "" } });`

### Steps to Reproduce

this, run on any collection:

`await collection.updateOne(filter, { $unset: { updatedAt: "" } });`

### Expected Behavior

field `updatedAt` should be removed from document

**Comment by IslandRhythms** [comment]
confirmed on 5.12.14, 5.13.18, and 7.2.1

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
}, { timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt'} });


const Test = mongoose.model('Test', testSchema, 'Test');

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const collection = mongoose.connection.collection('Test');
  console.log('original doc', await collection.findOne());
  console.log('remove createdAt', await collection.updateOne({}, { $unset: { createdAt: "" } }));
  console.log('remove updatedAt', await collection.findOne({}, { $unset: { updatedAt: "" } }));
  console.log('doc after changes', await collection.findOne({}));
}

run();
```

**Comment by tadjik1** [comment]
Same for me, I've used timestamps before, but now my logic doesn't depend on them and I wanted to remove them using simple migration, but it didn't work. No errors, no queries issued to the server, just silent `{ acknowledged: false }` as a result.
```
Model.updateMany({}, { $unset: { createdAt: 1, updatedAt: 1 } }));
```

**Comment by RealAlphabet** [comment]
Same here

**Comment by vkarpov15** [comment]
The below script demonstrates that Mongoose removes `updatedAt` if you `$unset` it in Mongoose 5.12, 6.x, and 7.x. Please modify the below script to demonstrate your issue:

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
}, { timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt'} });


const Test = mongoose.model('Test', testSchema, 'Test');

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: 'Test Testerson'
  });

  const collection = mongoose.connection.collection('Test');
  console.log('original doc', await collection.findOne());
  console.log('remove createdAt', await collection.updateOne({}, { $unset: { createdAt: "" } }));
  console.log('remove updatedAt', await collection.updateOne({}, { $unset: { updatedAt: "" } }));
  console.log('doc after changes', await collection.findOne({}));
}

run();
```

@IslandRhythms your repro script used `findOne()`, not `updateOne()` here: `console.log('remove updatedAt', await collection.findOne({}, { $unset: { updatedAt: "" } }));`
