### ISSUE TITLE
The best approach for extracting chunked data

### ISSUE THREAD

**Issue by Andrey-Yur** [Automattic/mongoose#13398]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.3

### Node.js version

18.16.0

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Issue

Good day! We have a collection of documents whose fields are stored id collections with chunk data. I tried to get data by population and by make joins in aggregation function, but for several docs those  approaches do not work due amount of size. Could you please  provide for me approach how I should extract data in that situation? Here a pic with example of storing data for a property.
![1](https://github.com/Automattic/mongoose/assets/62293778/93dde73d-ffc5-4a67-a591-c34ebe944ced)
A document in the 'map' collection has several filds like `businessesID`
![image](https://github.com/Automattic/mongoose/assets/62293778/72c947fa-d4b3-4c00-9151-8a9a06f56d74)

**Comment by vkarpov15** [comment]
Can you please elaborate on what "for several docs those approaches do not work due amount of size" means? Are you seeing some sort of error message?

**Comment by Andrey-Yur** [comment]
Error related to exceeding BSON size

**Comment by hasezoey** [comment]
> Error related to exceeding BSON size

what exceeds the bson size, the query or the individual documents, if individual documents, which of the mentioned ones? (if it is the one with `dataChunks`, maybe consider storing the id on the chunks and do a [virtual populate](https://mongoosejs.com/docs/tutorials/virtuals.html#populate) instead of storing all chunks on the target)
