### ISSUE TITLE
a question of catching error

### ISSUE THREAD

**Issue by iron-box-of-an-island** [Automattic/mongoose#13405]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.4.19

### Node.js version

14.18.0

### MongoDB version

5.0.14

### Operating system

Windows

### Issue

<img width="452" alt="1684312323785" src="https://github.com/Automattic/mongoose/assets/131111180/105b7dfb-bbcd-4cce-ab79-c3ac4803e78a">
when the url without databasename, it will report error : MongoError: database name must be a string,and this error can't be caught. how can i catch this error?

**Comment by IslandRhythms** [comment]
![image](https://github.com/Automattic/mongoose/assets/39510674/7500b402-a0e2-4032-8210-0ab739c9a639)
confirmed on 5, not present on 6 or 7

**Comment by vkarpov15** [comment]
@iron-box-of-an-island this looks like a bug in older versions of Mongoose, but looks like it was fixed somewhere between 5.4.19 and 5.13.17. Can you upgrade to 5.13.17?

**Comment by iron-box-of-an-island** [comment]
Well, thank you very much.
