### ISSUE TITLE
`session.withTransaction` is retrying many times on failed transactions. How to limiit the number of retries ?

### ISSUE THREAD

**Issue by bhavya3024** [Automattic/mongoose#13428]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.2

### Node.js version

19.8.1

### MongoDB version

6.0.5 Enterprise

### Operating system

Linux

### Issue

Actaully we have implemented a code which includes the mongoose session.
```
   const session  = mongoose.startSession();
    session.withTransaction(async (t) => {
     // business logic
    }, {retryWrites : false, willRetryWrite : false, maxTimeMS: 1000});
```

We did load testing using k6 including this API which includes this code as well. Since there are many requests coming here. Most of the transactions get retries due to conflict errors. But the problem is it is retyring many times, leading to request timeouts. We have logged errors in an array in different requests as shown in the image below after the retries are exhausted.
![image](https://github.com/Automattic/mongoose/assets/15158756/4c89a866-c9ed-48ef-8424-4c8035d54bce)

We already tried the usecase with ```session.commitTransaction()``` and ```session.abortTransaction()```. but we won't want to use this.

Also we don't want to use retry logic in code manually by taking retryCounts as a variable in code.

Is there an option to apply retries in the mongoose session itself ?

**Comment by alexbevi** [comment]
The associated ticket ([NODE-5307](https://jira.mongodb.org/browse/NODE-5307) has now been closed with additional information as to why [MAX_WITH_TRANSACTION_TIMEOUT](https://github.com/mongodb/node-mongodb-native/blob/91ddcedc100235f5d49b93377df9fdfe313ecfde/src/sessions.ts#L463) is set to `120000`, as well as why this value is not meant to be exposed as user-configurable.

**Comment by vkarpov15** [comment]
I'm going to have to close this issue; not much Mongoose can do if the MongoDB Node driver doesn't allow configuring this setting.
