### ISSUE TITLE
Schema.add() doesn't add fields to original schema

### ISSUE THREAD

**Issue by jzellis** [Automattic/mongoose#13423]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.3

### Node.js version

20.1.0

### MongoDB version

6.0.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6.1

### Issue

I'm trying to build a schema to store [ActivityStreams](https://www.w3.org/TR/activitystreams-vocabulary/), which are often recursive: [Objects](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-object) have sub-Objects, etc.

I realized I couldn't have something like this:

```
const ObjectSchema = new Schema({
actor: ObjectSchema
})
```

so I did this instead: 

```
const ObjectSchema = new Schema(
  {
    id: { type: String, index: true },
    type: { type: String },
    content: String,
    context: String,
    current: String,
    endTime: Date,
    first: String,
    last: String,
    name: String,
    next: String,
    prev: String,
    closed: Date,
    published: Date,
    startTime: Date,
    summary: String,
    accuracy: Number,
    altitude: Number,
    width: Number,
    height: Number,
    latitude: Number,
    longitude: Number,
    radius: Number,
    units: String,
    href: [String],
    startIndex: Number,
    totalItems: Number,
    relationship: String,
    formerType: String,
    deleted: String,
    href: String,
    hreflang: String,
    partOf: String,
    mediaType: { type: String, default: "text/html" },
    duration: String,
    _kowloon: Schema.Types.Mixed,
  },
  {
    strict: false,
    strictPopulate: false,
    timestamps: {
      createdAt: "created",
      updatedAt: "updated",
    },
  }
);

const SubObjectSchema = ObjectSchema.clone();
ObjectSchema.add({
  actor: SubObjectSchema,
  attachment: [SubObjectSchema],
  attributedTo: [SubObjectSchema],
  audience: [SubObjectSchema],
  generator: [SubObjectSchema],
  icon: SubObjectSchema,
  image: SubObjectSchema,
  inReplyTo: [SubObjectSchema],
  instrument: [SubObjectSchema],
  items: [SubObjectSchema],
  location: [SubObjectSchema],
  object: SubObjectSchema,
  oneOf: [SubObjectSchema],
  anyOf: [SubObjectSchema],
  origin: SubObjectSchema,
  preview: [SubObjectSchema],
  replies: [SubObjectSchema],
  result: SubObjectSchema,
  tag: [SubObjectSchema],
  target: SubObjectSchema,
  subject: SubObjectSchema,
  describes: SubObjectSchema,
  url: [SubObjectSchema],
  to: [SubObjectSchema],
  bto: [SubObjectSchema],
  cc: [SubObjectSchema],
  bcc: [SubObjectSchema],
});
```
I don't actually store Objects in a collection; rather, I have **Activities** and **Actors**, which are just collections that use ObjectSchema as their schema.

But here's the problem: when I try to save any documents to my collections, the fields added to ObjectSchema with `.add()` aren't stored. And if I `console.log(ObjectSchema.obj)`, they don't appear in there.

What am I doing wrong, here? Is there any way to actually make this work? I mean, Objects can theoretically be nested infinitely, but in practice that should never happen. What's the smart way to solve this?

**Comment by jzellis** [comment]
I should add that I also tried defining ObjectSchema and then adding fields that were ObjectSchema fields, like so:

`ObjectSchema.add({actor: ObjectSchema})`

... but that just causes everything to freeze up until I exit the process.

**Comment by vkarpov15** [comment]
"But here's the problem: when I try to save any documents to my collections, the fields added to ObjectSchema with .add() aren't stored. And if I console.log(ObjectSchema.obj), they don't appear in there." <-- How are you determining that the fields you added to your schema aren't being stored? Keep in mind that `Schema.prototype.obj` contains the original schema definition passed to the `Schema()` constructor, so any changes you make with `.add()` will not show up in `.obj`.

In general, you're right that `.add()` is how you handle infinitely nested schemas. For example, take a look at the following script:

```javascript
const mongoose = require('mongoose');
const { Schema } = mongoose;

const schema = new Schema({ name: String });
schema.add({ sub: schema });
const Test = mongoose.model('Test', schema);

/*
Example output:
{
  name: 'l1',
  _id: new ObjectId("646d001ab58d1f3008e1adf4"),
  sub: {
    name: 'l2',
    _id: new ObjectId("646d001ab58d1f3008e1adf5"),
    sub: { name: 'l3', _id: new ObjectId("646d001ab58d1f3008e1adf6") }
  }
}
*/
console.log(new Test({
  name: 'l1',
  sub: {
    name: 'l2',
    sub: { name: 'l3' }
  }
}));
```
