### ISSUE TITLE
Arguments' types of the transform function should be improved.

### ISSUE THREAD

**Issue by mrdulin** [Automattic/mongoose#13421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

*"mongoose": "^7.1.1"*

Currently, these arguments' types are all `any`, see:

`mongoose/types/index.d.ts`:
```ts
  export interface ToObjectOptions {  
    /** if set, mongoose will call this function to allow you to transform the returned object */
    transform?: boolean | ((doc: any, ret: any, options: any) => any);
  }
```

 I use `HydratedDocument<Something>` to specify the type for the `doc` argument, but I am not sure it's correct.

```ts
import mongoose, { HydratedDocument } from 'mongoose';

interface Something {
  name: string;
}
const somethingSchema = new mongoose.Schema<Something>({
  name: String
}, {
  collection: 'something',
  toJSON: {
    transform(doc: HydratedDocument<Something>) {

    },
  }
}
``` 

Any suggestion?

**Comment by vkarpov15** [comment]
`HydratedDocument<Something>` is correct in that case. We'll update the types.
