### ISSUE TITLE
Model.findOneAndUpdate() is updating nested fields with 'strict:false'

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#13434]
### Discussed in https://github.com/Automattic/mongoose/discussions/13432

<div type='discussions-op-text'>

<sup>Originally posted by **amitpriyankar** May 24, 2023</sup>
I have observed an unusual behavior when using `Model.findOneAndUpdate` with a collection that has a flexible schema (strict: false). When I attempt to insert a document that includes a key containing a dot (.), the behavior differs based on whether I define the type of the key in the schema. If I specify the type, the key is treated as a regular string. However, if I don't specify the type, nested fields are created in the document.

Please refer the following code:
```javascript
const mongoose = require('mongoose');

const url = '<connection_url>;

main().catch((err) => console.log(err));

async function main() {
    await mongoose.connect(url);

    const personSchema = new mongoose.Schema(
        {
            name: String,
            // info: Object,
        },
        {strict: false}
    );

    personSchema.index({name: 1}, {unique: true});

    const Person = mongoose.model('Person', personSchema);

    const savedDoc = await Person.findOneAndUpdate(
        {},
        {name: 'Tommy1', info: {'second.name': 'Shelby'}},
        {new: true, upsert: true}
    )
        .lean()
        .exec();

    console.log('Saved document: ', savedDoc);
    mongoose.disconnect();
}
```
```
Saved document:  {
  _id: new ObjectId("646dccd30b5d3da01e058fd0"),
  __v: 0,
  info: { second: { name: 'Shelby' } },
  name: 'Tommy1'
}
```

I check the doc but didn't find anything which explains this behavior. Could someone please help?

mongoose: v7.1.1
MongoDB Server: 4.0</div>

**Comment by IslandRhythms** [comment]
![image](https://github.com/Automattic/mongoose/assets/39510674/72133b59-7d89-418e-b8dd-9ae07ddffe33)

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String,
  info: Object
}, { strict: false });

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.findOneAndUpdate({}, { name: 'Test Testerson', info: { 'second.name': 'Quiz' } }, { new: true, upsert: true });
  console.log('doc', doc);
  mongoose.disconnect();
}
run();
```
