### ISSUE TITLE
Cast to ObjectId failed for value \"sell\" (type string) at path \"_id\" for model \"Book\""

### ISSUE THREAD

**Issue by huynhdev24** [Automattic/mongoose#13443]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.3

### Node.js version

16.18.0

### MongoDB version

7

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

I got this error and I don't know how to fix it
![image](https://github.com/Automattic/mongoose/assets/124909303/df221712-16f0-4ec9-9845-39c23363cd8e)
![image](https://github.com/Automattic/mongoose/assets/124909303/978a44fe-8209-4152-9863-7f11a07305b5)
![image](https://github.com/Automattic/mongoose/assets/124909303/9e889925-a7ff-475e-bdb4-72304937d551)

**Comment by vkarpov15** [comment]
What is `req.query`? I imagine you'll see `_id: 'sell'` in `req.query`, which is incorrect, so this is likely a bug in your frontend.
