### ISSUE TITLE
IAM Role Session Token Authentication

### ISSUE THREAD

**Issue by sidpremkumar** [Automattic/mongoose#13454]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.10.19

### Node.js version

18

### MongoDB version

5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

AL2

### Issue

Hello! 

We are using IAM roles to connect to mongo via mongoose. 

To do this we pass a `SESSION_TOKEN` into the connection string such as: 
```js
`${protocol}://${accessKey}:${awsSecretKey}@${host}/${db}?authSource=%24external&authMechanism=MONGODB-AWS&retryWrites=true&w=majority&authMechanismProperties=AWS_SESSION_TOKEN:${awsSessionToken}&ssl=true?${replica}`
```

The problem is after 15 mins the session token is invalidated and we need to re-create it. 

Is there a way to do this in mongoose automatically? Or any tips on how to tackle this problem! Tried calling `disconnect` then `connect` but getting this error while testing: `MongoError: server is closed`

**Comment by vkarpov15** [comment]
Currently there's no good way to do that other than to create a new connection each time your session token changes. The problem with calling `disconnect()` on a timer is that any in-flight operations will fail. So you may want to do something like the following (rough example, no error handling)

```javascript
let currentConnection;

setInterval(() => {
  let oldConnection = currentConnection;
  currentConnection = mongoose.createConnection(`${protocol}://${accessKey}:${awsSecretKey}@${host}/${db}?authSource=%24external&authMechanism=MONGODB-AWS&retryWrites=true&w=majority&authMechanismProperties=AWS_SESSION_TOKEN:${awsSessionToken}&ssl=true?${replica});
  setTimeout(() => {
    oldConnection.destroy();
  }, 10000);
}, 15 * 60 * 1000)
```

**Comment by vkarpov15** [comment]
`destroy()` closes the connection permanently. It doesn't do anything to help with potentially erroring out in-flight requests. Right now we don't have a better way of doing that other than setting a timer - the `setTimeout()` will hopefully give in-flight operations enough time to complete before killing the connection.

We and the MongoDB Node driver team are working on a better solution, but right now creating a new connection and closing the old connection after a certain time period is the simplest and most durable approach.
