### ISSUE TITLE
Why do Mongoose v6 and v7 cause a significant increase in garbage collections and event loop latency compared to v5?

### ISSUE THREAD

**Issue by emilisaksson** [Automattic/mongoose#13456]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

5.12.4

### Slowed down in version

6.11.1

### Node.js version

16.18.0

### 🦥 Performance issue

Background:
We have been trying to migrate from Mongoose v5 to v6 in our SaaS platform for the past year with no luck. The issues described here also occurs when running Mongoose 7.
Our software have a decent amount of web traffic(about 25 requests per second) and is using a single MongoDB Atlas cluster where each SaaS client is using its own database.
The software is hosted on Heroku.

The issue:
When we deploy a version of our software that is using Mongoose 6 or 7 it runs fine for up to an hour, then we start to see an increase in number of garbage collections, time spent in garbage collection, and event loop latency. This continues until the servers event loop is completely hogged and cannot handle any more incoming requests.
The memory usage is unaffected, so it doesn't seem to be a memory leak.

### Steps to Reproduce

The code:

Upon start, we create a database connection with a pool of 300 connections:
```
global.databaseConnection = await mongoose.createConnection(global.config.dbConnectionString, {
	maxPoolSize: 300,
	minPoolSize: 300
});
```

When a request for a specific client is received, a connection to that specific clients database is drawn from the connection pool using the useDb-function:
```
clientDatabaseConnection = global.databaseConnection.useDb(`client-${client.databaseName}`, {
	noListener: true,
	useCache: true
});
```

The client database connection is then used to do various quesries required by the request, for example:
```
let clientUserCollection = connection.model<IClientUserModel>("ClientUser", ClientUserSchema, 'users');
let user = await clientUserCollection.findById(userId).exec();
```

This is basically the structure of the application. What is it that is different in v6 and v7 compared to v5 that could cause these performance implications?

**Comment by hasezoey** [comment]
> This is basically the structure of the application. What is it that is different in v6 and v7 compared to v5 that could cause these performance implications?

one of the biggest changes from v5 to v6 was that mongodb (the underlying driver) was completely re-written in typescript, which could be a likely cause

**Comment by thandaanda** [comment]
We are also experiencing the same issue. We are restarting our servers every 24 hours. Memory seems fine. CPU hovers around 50%., but app becomes completely useless till we restart.

**Comment by samirkatyar** [comment]
I'm also facing this issue.
@vkarpov15 when this will resolved ?

**Comment by billouboq** [comment]
This might be a js-bson issue. Already made a PR to improve performance a bit but PR is not merged yet

**Comment by aykutbulca** [comment]
Are there any updates on the status of this issue? We also faced a similar performance problem after upgrading mongoose from v5.13.20 to v7.6.6.

**Comment by vkarpov15** [comment]
Realistically, without more information there's no way for us to repro this. There's no significant difference in `useDb()` between [5.x](https://github.com/Automattic/mongoose/blob/5.x/lib/drivers/node-mongodb-native/connection.js#L53) and [6.x](https://github.com/Automattic/mongoose/blob/6.x/lib/drivers/node-mongodb-native/connection.js#L53): the only difference is that Mongoose 6 doesn't have a `listen()` function.

Similar with `connection.model()`: [5.x](https://github.com/Automattic/mongoose/blob/5.x/lib/connection.js#1195) vs [6.x](https://github.com/Automattic/mongoose/blob/6.x/lib/connection.js#L1174).

@aykutbulca are you able to create a repro script or project that demonstrates the issue you're seeing? Or at least provide some more substantial code samples?

**Comment by aykutbulca** [comment]
> Realistically, without more information there's no way for us to repro this. There's no significant difference in `useDb()` between [5.x](https://github.com/Automattic/mongoose/blob/5.x/lib/drivers/node-mongodb-native/connection.js#L53) and [6.x](https://github.com/Automattic/mongoose/blob/6.x/lib/drivers/node-mongodb-native/connection.js#L53): the only difference is that Mongoose 6 doesn't have a `listen()` function.
> 
> Similar with `connection.model()`: [5.x](https://github.com/Automattic/mongoose/blob/5.x/lib/connection.js#1195) vs [6.x](https://github.com/Automattic/mongoose/blob/6.x/lib/connection.js#L1174).
> 
> @aykutbulca are you able to create a repro script or project that demonstrates the issue you're seeing? Or at least provide some more substantial code samples?

We have been trying to isolate the issue and identified a significant performance disparity between MongoDB drivers v3 and v6 — the issue does not seem related to mongoose regarding our internal tests. We started discussions with the MongoDB team, but nothing so far.

To replicate the issue, we use the following script. Running this script with MongoDB driver versions 3.7.4 and 6.3.0 clearly demonstrates the performance difference. We consistently observed at least a 30% increase in query time when using 6.3.0. This percentage rises with the volume of data retrieved. For instance, if the inserted documents contain larger fields, such as lengthy strings (`enableUtf8Validation: false` did not help), the performance differential can exceed 50%. 

It's worth noting that the replication script operates without the mongoose library and directly utilizes the MongoDB Node.js driver. However, you get similar results if you run a similar script with mongoose v5 vs. v7.
```
const mongodb = require('mongodb');
const { MongoClient } = mongodb;

const uri = 'mongodb://localhost:27017/test?directConnection=true';
const client = new MongoClient(uri);

async function removeAllDocuments(db) {
    const collection = db.collection('test');
    await collection.deleteMany({});
}
// insert 10k documents to collection 'test'
async function insertDocuments(db) {
    const collection = db.collection('test');
    const docs = [];
    for (let i = 0; i < 10000; i++) {
        docs.push({
            a: i,
            b: i + 1,
            c: i + 2,
            d: i + 3,
            e: i + 4,
            f: i + 5,
            g: i + 6
        });
    }
    await collection.insertMany(docs);
}

async function main() {
    // connect and insert documents
    await client.connect();
    const db = client.db('test');
    await removeAllDocuments(db);
    await insertDocuments(db);
    console.log("insert 10k documents completed");
    // read 10k documents at once, time the operation
    // average 100 fetches and calculate the average time spent

    const numAttempts = 1000;
    const times = [];
    for (let i = 0; i < numAttempts; i++) {
        const start = Date.now();
        const cursor = db.collection('test').find();
        const docs = await cursor.toArray();
        const end = Date.now();
        times.push(end - start);
    }
    const sum = times.reduce((a, b) => a + b, 0);
    const avg = sum / numAttempts;
    console.log(`Average time spent: ${avg} ms`);
}

main().catch(console.error);
```

**Comment by vkarpov15** [comment]
@aykutbulca thanks for the repro script. I see a similar slowdown starting with `mongodb@4.x`, below are the results I got:

```
$ npm install mongodb@3.x --no-save

added 19 packages, and audited 21 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node ./gh-13456.js 
(node:1040636) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
insert 10k documents completed
Average time spent: 30.091 ms
^C
$ npm install mongodb@4.x --no-save

added 99 packages, removed 15 packages, changed 2 packages, and audited 105 packages in 6s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
val@defiant:~/Workspace/MongoDB/troubleshoot-mongoose$ node ./gh-13456.js 
insert 10k documents completed
Average time spent: 35.602 ms
^C
val@defiant:~/Workspace/MongoDB/troubleshoot-mongoose$ npm install mongodb@5.x --no-save

removed 3 packages, changed 2 packages, and audited 102 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node ./gh-13456.js 
insert 10k documents completed
Average time spent: 37.131 ms
^C
$ npm install mongodb@6.x --no-save

removed 2 packages, changed 6 packages, and audited 100 packages in 676ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node ./gh-13456.js 
insert 10k documents completed
Average time spent: 36.066 ms
^C

```

I'll take a look and see what I can find. Below is the flamegraph with `mongodb@6`:

![image](https://github.com/Automattic/mongoose/assets/1620265/a8263e3f-50d7-4f23-ae6e-ccc763a1642f)

**Comment by vkarpov15** [comment]
@aykutbulca I adapted your script to use Mongoose instead of MongoDB driver:

```javascript
const mongoose = require('mongoose');

const Test = mongoose.model('Test', new mongoose.Schema({
  a: Number,
  b: Number,
  c: Number,
  d: Number,
  e: Number,
  f: Number,
  g: Number
}));

// insert 10k documents to collection 'test'
async function insertDocuments() {
    const docs = [];
    for (let i = 0; i < 10000; i++) {
        docs.push({
            a: i,
            b: i + 1,
            c: i + 2,
            d: i + 3,
            e: i + 4,
            f: i + 5,
            g: i + 6
        });
    }
    await Test.insertMany(docs);
}

async function main() {
    // connect and insert documents
    await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
    await Test.deleteMany({});
    await insertDocuments();
    console.log("insert 10k documents completed");
    // read 10k documents at once, time the operation
    // average 100 fetches and calculate the average time spent
    const numAttempts = 100;
    const times = [];
    for (let i = 0; i < numAttempts; i++) {
        const start = Date.now();
        const docs = await Test.find();
        const end = Date.now();
        times.push(end - start);
    }
    const sum = times.reduce((a, b) => a + b, 0);
    const avg = sum / numAttempts;
    console.log(`Average time spent: ${avg} ms`);
    process.exit(0);
}

main().catch(console.error);
```

It looks like Mongoose 6 is actually significantly faster than Mongoose 5. Results are similar with Mongoose 7.

```
$ npm install mongoose@6 --no-save

added 101 packages, removed 26 packages, changed 6 packages, and audited 113 packages in 7s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node gh-13456-mongoose.js 
(node:1140619) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
insert 10k documents completed
Average time spent: 85 ms
$ node gh-13456-mongoose.js 
(node:1140695) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
insert 10k documents completed
Average time spent: 84.03 ms
$ npm install mongoose@5 --no-save

added 23 packages, removed 97 packages, changed 10 packages, and audited 39 packages in 3s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node gh-13456-mongoose.js 
(node:1140853) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:1140853) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
insert 10k documents completed
Average time spent: 125.14 ms
$ 

```

So while the MongoDB driver is a bit slower, Mongoose is actually faster. Have you observed similar behavior or is Mongoose 6 slower than Mongoose 5 for you?

**Comment by aykutbulca** [comment]
Hey @vkarpov15 👋 

I've modified your script with a more complex schema, and the results are similar to our previous findings:

```javascript
const { dependencies } = require('./package.json');
const mongoose = require('mongoose');
const { ObjectId } = mongoose.Schema.Types;

const schema = new mongoose.Schema({
    groupKey: {
        type: String,
        required: true
    },
    groupId: {
        type: ObjectId,
        required: true
    },
    actionName: {
        type: String,
        required: true
    },
    userId: {
        type: ObjectId,
        required: true
    },
    content: String,
    metadata: {
        source: {
            _id: ObjectId,
            email: String,
            username: String,
            bio: String,
            fullName: String,
            emotar: String,
            avatar: String
        },
        project: {
            _id: ObjectId,
            type: {
                type: String,
                enum: [
                    "android",
                    "ios",
                    "web",
                    "osx"
                ]
            },
            name: String
        },
        screen: {
            _id: ObjectId,
            name: String,
            latestVersion: {
                _id: ObjectId,
                snapshotFragment: {
                    url: String,
                    width: {
                        type: Number
                    },
                    height: {
                        type: Number
                    }
                }
            }
        },
        dot: {
            _id: ObjectId,
            name: String,
            status: {
                type: String,
                enum: [
                    "open",
                    "resolved"
                ]
            },
            note: String
        },
        comment: {
            _id: ObjectId,
            name: String,
            note: String
        }
    }
}, {
    toJSON: {
        getters: true,
        virtuals: false
    },
    toObject: {
        getters: true,
        virtuals: false
    },
    timestamps: {
        createdAt: "created",
        updatedAt: "updated"
    }
});

const Test = mongoose.model('Test', schema);

function getBaseData() {
    return {
        actionName: "Action",
        groupId: new mongoose.Types.ObjectId(),
        groupKey: "Group-",
        userId: new mongoose.Types.ObjectId(),
        content: "annotation.text",
        metadata: {
            project: {
                _id: new mongoose.Types.ObjectId(),
                type: "web",
                name: "project.name"
            },
            source: {
                _id: new mongoose.Types.ObjectId(),
                email: "mail@email.com",
                username: "source.username",
                bio: "source.bio",
                fullName: "source.fullName",
                emotar: "source.emotar",
                avatar: "source.avatar"
            },
            dot:  {
                _id: new mongoose.Types.ObjectId(),
                name: "dot.name",
                status: "open",
                note: "comment.note"
            },
            comment: {
                _id: new mongoose.Types.ObjectId()
            },
            screen: {
                _id: new mongoose.Types.ObjectId(),
                name: "screen.name",
                latestVersion: {
                    _id: new mongoose.Types.ObjectId(),
                    snapshotFragment: {
                        url: "latestVersion.snapshotFragment.url",
                        width: 120,
                        height: 240
                    }
                }
            }
        }
    };
}

// insert 10k documents to collection 'test'
async function insertDocuments() {
    const docs = [];
    for (let i = 0; i < 10000; i++) {
        const base = getBaseData();
        const newItem = new Test({...base});
        newItem.groupKey += (i % 20);
        docs.push(newItem);
    }
    await Test.insertMany(docs);
}

async function main() {
    // connect and insert documents
    await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
    await Test.deleteMany({});
    await insertDocuments();
    console.log("insert 10k documents completed");
    // read 10k documents at once, time the operation
    // average 100 fetches and calculate the average time spent
    const numAttempts = 100;
    const times = [];
    for (let i = 0; i < numAttempts; i++) {
        const start = Date.now();
        const docs = await Test.find().lean().exec();
        const end = Date.now();
        console.log(i, end - start);
        times.push(end - start);
    }
    const sum = times.reduce((a, b) => a + b, 0);
    const avg = sum / numAttempts;
    console.log(`Mongo DB Server 5.0.23 + Node 20 + mongoose version ${dependencies.mongoose} - Average time spent: ${avg} ms`);
    process.exit(0);
}

main().catch(console.error);
```

```
Mongo DB Server 5.0.23 + Node 20 + mongoose version 5.13.20 - Average time spent: ~135 ms
Mongo DB Server 5.0.23 + Node 20 + mongoose version 6.12.5 - Average time spent: ~170 ms
Mongo DB Server 5.0.23 + Node 20 + mongoose version 7.6.6 - Average time spent: ~170 ms
```

It looks like Mongoose version 5 is still the fastest in my local environment, and the results are similar to our experiments with the underlying MongoDB driver. So, I still think the root cause of the issue is with the MongoDB NodeJS driver (probably BSON serialization), and Mongoose performs aligned with that.

**Comment by aykutbulca** [comment]
Hey @vkarpov15 👋 

We got the confirmation from the MongoDB team that NodeJS driver version 6 (and 4 + 5) is almost %30 less performance than the driver version 3 due to BSON deserializing. They shared the following projects to improve it, but I don't think this will happen soon:
* https://jira.mongodb.org/browse/NODE-2674
* https://jira.mongodb.org/browse/NODE-5792

We recently upgraded our apps to use Mongoose v7.6 because MongoDB Server 5.0 was not compatible with Mongoose v5.13 (the [compatibility](https://mongoosejs.com/docs/compatibility.html) page is changed btw, it was like the attached screenshot before), and since then, we have seen this performance problem. I doubt there is anything we can do with Mongoose v7.6, but we are open to suggestions.

![image](https://github.com/Automattic/mongoose/assets/18143597/d1b52dbb-c6f5-40fe-90ad-7411040fd96c)

**Comment by kmonagle** [comment]
Great information here...thank you all. We're attempting to upgrade from mongoose 5.13.20 to 7.6.8 and we're running into serious performance issues. 

I get the bson serialization issues, and my own tests clearly show significant performance degredation. What I don't get is this: I'm sending a few thousand update requests to my API. The first load test with Mongoose 7.6.8/Mongod 5.9 runs about 30% slower than Mongoose 5.13/Mongo 3.6.6. The SECOND load test runs slower. The THIRD runs even slower.

Memory looks fine. CPU looks fine. I know this is similar to what some others have reported...but WHY? It behaves like a memory leak but it doesn't appear to be memory related. There's gradually increasing event loop lag for sure, but that's the only metric that clearly reflects the slowdown.  

Any speculation on the cause of the gradual, continuous slowdown? I'd expect slower performance but I'm surprised to see things get slower and slower...

**Comment by billouboq** [comment]
Version 6.4 of the node mongodb driver is available, it has a lot of performance improvements in the js-bson library so it might reduce the slow-down, maybe even increase performance, can we try again with the new version ?

**Comment by kmonagle** [comment]
> Version 6.4 of the node mongodb driver is available, it has a lot of performance improvements in the js-bson library so it might reduce the slow-down, maybe even increase performance, can we try again with the new version ?

thanks @billouboq . In short, I'm not seeing any improvement.

We recently attempted an upgrade from mongodb 3.6.6 to 5.9.2, in conjunction with moving mongoose from 5.13 to 7.4.

Luckily we caught the issue before going to prod, but we're seeing the kind of slowdowns described above. 5.9.2 is about 30% slower from the start, but it unfortunately gets progressively slower as I repeat my fairly modest load tests.

The slowdown seems to happen at the mongodb driver level, I agree generally with the conclusions above that mongoose doesn't seem to be a major factor.

Memory looks good, so I don't get why things steadily degrade...

**Comment by kmonagle** [comment]
I'm suspicious of the lean virtuals plugin. Some more data points: 

1. in my app event loop lag is out of control with mongoose/mongo beyond 5.x. With a moderate load test, mongoose 5 lag is sustained at 1 or 2ms. With mongoose 6 or 7 lag explodes along with degraded performance and is sustained at around 100ms, peaking at 3-400ms.

2. after profiling a heat map identified "attachVirtualsToDoc" from the lean virtuals plugin as the hottest hot spot.

3. when I set virtuals: false in my lean() calls all of the event loop lag and performance issues disappeared.

Any thoughts? Anybody else using lean virtuals and experiencing issues after an upgrade?

**Comment by kmonagle** [comment]
This was the cause of all of our pain:

We had a bit of code that was removing a model from the mongoose connection "models" POJO before creating a new model. Perhaps this was to avoid an exception if the model existed.

delete conn.models['simple'];
model = conn.model('simple', simpleSchema);

This is legacy code, and without getting into a discussion of whether this pattern is advisable, this created a nightmare of an issue when we upgraded from Mongoose 5 to 7.

In short, no ill effects were observed with 5. With 7, every time that code was executed (and it was executed a lot) a new idGetter was added to the getters array of the "id" virtual. So as the app ran that array grew continuously, the event loop lag grew as thousands of redundant idGetter functions were executed synchronously, and idGetter executions grew into the billions with moderate load tests.

So this is not BSON or the mongo driver. The symptoms I observed were identical to those described by other folks when moving past 5.x, where performance gradually slows down while memory looks OK. I'm wondering if there are other scenarios besides mine in which this might happen, and whether there's a bug or two in the code that adds those getters in.

**Comment by vkarpov15** [comment]
@kmonagle we recommend avoiding recreating models, `conn.model('simple', simpleSchema)` is a fairly slow operation and we normally recommend not running that in transactional code.

**Comment by huksley** [comment]
Found this thread because I trying to debug connection timeouts with my app and AWS Lambdas. I upgraded to MongoDB package 5.9.2 and MoongooseJS 7.6.7 and started to get unpredictable sometimes slow connection. It is not related to the load, it just happens sometimes

```
    "mongodb": "^5.9.2",
    "mongoose": "^7.6.7",
```

<img width="1385" alt="image" src="https://github.com/Automattic/mongoose/assets/1594349/cd18162e-f326-4b75-a790-7e41f3f068f3">

Exactly on 2024-02-16, I deployed a new version to the staging, and one week ago into production. The average lambda execution time jumped significantly, and now also, sometimes, it times out exceeding 30 and more...

**Comment by kmonagle** [comment]
@vkarpov15 agreed but it seems like a bug was introduced in 6.x around that. In 5.x it was inefficient. In 6+ it was killing my app.

**Comment by vkarpov15** [comment]
@kmonagle im sorry for the inconvenience. Is there some content you read that indicated it was correct to delete and recreate models on every lambda invocation? If so, can you please provide a link?

**Comment by kmonagle** [comment]
@vkarpov15 this code predates me by several years and we're in agreement that recreating the model every time is not a great practice. We'll be optimizing model creation to work around this as we continue this upgrade process, so thank you for your feedback on that.

That will be a win, but we'll be introducing a new issue. I do have a use case for dynamically deleting and recreating models from time to time. It doesn't need to be on every invocation, but it does happen. I believe that there was a regression in 6+ that will degrade performance every time a model is removed and recreated.

There's a leak in the "id" virtual getter creation. This leak was explicitly prevented in 5x. In 6+ that prevention appears to have gone away. 

In 5.x:
```
Document.prototype.$__setSchema = function(schema) {
  schema.plugin(idGetter, { deduplicate: true });
```
```
Schema.prototype.plugin = function(fn, opts) {
  if (typeof fn !== 'function') {
    throw new Error('First param to `schema.plugin()` must be a function, ' +
      'got "' + (typeof fn) + '"');
  }

  if (opts && opts.deduplicate) {
    for (const plugin of this.plugins) {
      if (plugin.fn === fn) {
        return this;
      }
    }
  }
  this.plugins.push({ fn: fn, opts: opts });

  fn(this, opts);
  return this;
};
```
We use virtuals. So every time I recreate a model in 6+, since the above guardrail appears to have been removed, an additional, duplicate idGetter will be added to the getter array and my application will do more work on subsequent executions. On a busy day, after recreating a model, my app will execute tens or hundreds of thousands more idGetter functions than it did the day before. At best this is an annoyance. At worst, with lots of model recreations, it will start killing my app performance.

I've submitted a bug report:

https://github.com/Automattic/mongoose/issues/14457

I'm including this info here because the negative effects we observed appear to be extremely similar if not identical to what the first few posters observed. It's another angle to explore.

**Comment by vkarpov15** [comment]
I took a look at [this repro](https://github.com/Automattic/mongoose/issues/13456#issuecomment-1891983610) and it looks like Mongoose 8 is now the fastest:

```
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 69.84 ms
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 68.43 ms
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 67.5 ms
```

vs Mongoose 7:

```
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 82.86 ms
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 86.01 ms
$ node gh-13456-mongoose.js 
insert 10k documents completed
Average time spent: 84.54 ms

```

and Mongoose 5:

```
$ node gh-13456-mongoose.js 
(node:71636) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:71636) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
insert 10k documents completed
Average time spent: 117.75 ms
$ node gh-13456-mongoose.js 
(node:71648) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:71648) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
insert 10k documents completed
Average time spent: 123.8 ms
```

The idGetter duplication issue from https://github.com/Automattic/mongoose/issues/13456#issuecomment-1999780097 was fixed in https://github.com/Automattic/mongoose/pull/14492, so I'm going to mark this issue as closed. If you're running into similar issues, please open a new issue with detailed repro instructions.
