### ISSUE TITLE
How to walk through a schema's paths, recursing on subdocuments and arrays?

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#13469]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.4

### Node.js version

18.12.0

### MongoDB version

6

### Operating system

None

### Issue

I want to write a test ensuring that if a schema path is an optional enum, then `null` is included as an allowed value. (That Mongoose doesn't automatically include `null` for optional enums arguably a design flaw, but that's another topic.)

I've written this code which works for scalar fields:
```typescript
const path = schema.paths;
for (const pathName of Object.keys(paths)) {
        const schemaType = paths[pathName];
        if (!schemaType.isRequired) {
          const enums = schemaType.options.enum;
          if (enums) {
            assert.ok(
              enums.some((x: any) => x === null),
              `Schema path '${pathName}' from model '${model.modelName}' is an optional enum, but doesn't allow \`null\`. Either make the path required, or allow null.`
            );
          }
        }
```

But I can't figure out how to recursively handle subdocuments and arrays. I spent an hour trying to figure it out, but there are too many undocumented methods in the API. Any help would be much appreciated. Thanks!

**Comment by vkarpov15** [comment]
@JavaScriptBach try the following:

```javascript
'use strict';

const { Schema } = require('mongoose');

const schema = new Schema({
  name: String,
  nested: new Schema({ foo: String }),
  arr: [{ bar: String }]
});

iteratePaths(schema);

function iteratePaths(schema, prefix = '') {
  if (prefix) {
    prefix = prefix + '.';
  }
  schema.eachPath((path, schematype) => {
    console.log(prefix + path);
    if (schematype.schema) {
      iteratePaths(schematype.schema, prefix + path);
    }
  });
}
```

You are right that `null` not being a valid value for optional enums is strange, this is the 3rd time I've seen #3044 has popped up in the last year or so, I think it is time we re-open that.
