### ISSUE TITLE
Mongoose should export helper query types

### ISSUE THREAD

**Issue by abhijeetviswa** [Automattic/mongoose#13479]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Types such a FilterQuery, Condition etc need to be exported by mongoose so that end-users can make use of them when defining helper functions which eventually are passed to functions like `find`.

**Comment by vkarpov15** [comment]
As far as I can tell, you can import `FilterQuery` and `Condition` just fine. The following compiles with `tsc --strict gh-13479.ts` with Mongoose 7.2.2 and TypeScript 4.9.5. Can you please modify the following script to demonstrate the issue you're seeing?

```ts
import { Query, QueryWithHelpers, FilterQuery, MongooseQueryOptions, Condition } from 'mongoose';

type Foo = Condition<string>;
```
