### ISSUE TITLE
Add localhost vs 127.0.0.1 info in FAQ and connections docs

### ISSUE THREAD

**Issue by nirvikpurkait** [Automattic/mongoose#13483]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.2.2

### Node.js version

18.12.1

### MongoDB version

6.0.4

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I can connect to mongoDB with `127.0.0.1:27017` and `localhost:27017` both, with the help of mongoDB Compass, when I am trying to connect to the same with the help of mongoose, for `localhost:27017` it is showing error message like, `ECONNREFUSED ::1:27017`, but in case if I try to connect with `127.0.0.1:27017`, it connects.

N.B: I have checked my host mapping for my system, everything is mapped correctly.

**Comment by silentjohnny** [comment]
Node 18.x connects to IPv6 address ::1 instead of IPv4 127.0.0.1 when using localhost:27017.
Your MongoDB server needs to listen to IPv6 connections, please consider the following entry in your mongod.conf:

```yaml
net:
  port: 27017
  bindIp: localhost
  ipv6: true
```

**Comment by IslandRhythms** [comment]
@vkarpov15 should we add this to the FAQ?

**Comment by nirvikpurkait** [comment]
> Node 18.x connects to IPv6 address ::1 instead of IPv4 127.0.0.1 when using localhost:27017. Your MongoDB server needs to listen to IPv6 connections, please consider the following entry in your mongod.conf:
> 
> ```yaml
> net:
>   port: 27017
>   bindIp: localhost
>   ipv6: true
> ```

It didn't worked initially, but after making the changes to config file, needed to restart the MongoDB server from services.
