### ISSUE TITLE
Mongoose serializable queries?

### ISSUE THREAD

**Issue by natdm** [Automattic/mongoose#13485]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.13

### Node.js version

14

### MongoDB version

4

### Operating system

None

### Issue

We're working on converting our applications to temporal, and one of the steps we've considered is abstracting away Mongoose calls through Temporal, having them all made within a Temporal activity. This means the queries need to be serialized and sent off, and returned. 

I was wondering if there's any way to be able to convert a query, and then serialize it, and send it off to then get put back in to the Mongoose object for a model, and executed. I don't believe I see a way of being able to do this, but if there is, I'd love to know. Thanks!

**Comment by vkarpov15** [comment]
Mongoose doesn't have a way to serialize an arbitrary query instance, but you can always represent a query in a serializable way. For example, you can have a `find()` activity that takes in a model name and a POJO filter; that activity executes the query and returns the result as a POJO. That's the more idiomatic way to do things in Temporal anyway: anything that references a Mongoose model should be in an activity, not a workflow.

On a side note, I'd love to hear about your experience working with Mongoose and Temporal. I've done a lot of work with Temporal over the years, but never with Mongoose unfortunately.
