### ISSUE TITLE
Specify database name when running query

### ISSUE THREAD

**Issue by sulay-sumaria** [Automattic/mongoose#13489]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.2.2

### Node.js version

18

### MongoDB version

6

### Operating system

None

### Issue

How can I specify the database name that I want to query against? The database on which I want to run the query depends on the data submitted by form on UI. I found the option in the mongodb native driver, there is an option named `dbName` in the FindOptions paramter.

**Comment by sulay-sumaria** [comment]
This throws an error `TypeError: Cannot read properties of undefined (reading 'find')`. Looks like the models are not being loaded on the new database.

**Comment by vkarpov15** [comment]
@hugojerez is right, use `useDb()` and re-register your models on the new connection returned by `useDb()`. Take a look at [Mongoose's multi tenancy docs](https://mongoosejs.com/docs/connections.html#multi-tenant-connections).

I think the MongoDB docs are incorrect here, the [code where `dbName` is defined says this option is only for admin commands](https://github.com/mongodb/node-mongodb-native/blob/v5.6.0/src/operations/command.ts#L56)
