### ISSUE TITLE
Property 'discriminator' does not exist on type... type script

### ISSUE THREAD

**Issue by digiborimusik** [Automattic/mongoose#13488]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.1.1

### Node.js version

16

### MongoDB version

6.0.6

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10)

13.3

### Issue

I want to implement discriminators for subdocument schema [like this](https://idomagor.medium.com/nested-discriminated-documents-in-mongoose-960041146241) but got an error.

<img width="1312" alt="Screenshot 2023-06-07 at 12 09 35" src="https://github.com/Automattic/mongoose/assets/45172795/cc727fe0-58fc-49fc-955e-531898221d62">

**Comment by vkarpov15** [comment]
`OrderDetailsSchema.path<mongoose.Schema.Types.Subdocument>('devicePassword').discriminator(...)`
