### ISSUE TITLE
.save() dont work in 7.2.4, but work in 6.3.6

### ISSUE THREAD

**Issue by ShevRuslan** [Automattic/mongoose#13502]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.2.4

### Node.js version

16.14.0

### MongoDB version

5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

The problem is that .save() doesn't work in 7.2.4 but works in 6.3.6, what could be the problem?
db.js:

```js
const mongoose = require("mongoose");

module.exports = class {
  connect = async () => {
    let connection = await mongoose.connect(
      "mongodb://localhost:27017/db",
      {
        useNewUrlParser: true,
        useUnifiedTopology: true,
      }
    );
    return connection;
  };
  disconnect = async () => {
    let res = await mongoose.disconnect();
    return res;
  };
};
```

server.js:
```js
server.listen(3001, async () => {
  DB.connect();
  console.log("We are live on " + 3001);
});
```

script.js:

```js
 let skin = new Skin({
                        name,

                      });
                      skin
                        .save()
                        .then((savedSkin) => {
                          console.log("Save:", savedSkin);
                        })
                        .catch((error) => {
                          console.error("Error:", error);
                        });
```
skin.js
```js
const mongoose = require("mongoose");
const { Schema, model } = mongoose;
const AutoIncrement = require("mongoose-sequence")(mongoose);
const skin = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    _id: Number,
  },
  { _id: false, versionKey: false, strict: false }
);

skin.plugin(AutoIncrement);

module.exports = model("Skin", skin);

```

**Comment by hasezoey** [comment]
in which way does it not work? does it throw a error, does it never complete or something else?

also note that `mongoose-sequence` [does not support mongoose v7 and may just hang](https://github.com/ramiel/mongoose-sequence/issues/133)

btw `useNewUrlParser` and `useUnifiedTopology` are not used since mongoose 6.x anymore, see [this change](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options)

**Comment by dsclassen** [comment]
I had a similar problem with `doc.save()` hanging with mongoose 7. I removed the dependency on `mongoose-sequence` and everything is working now.

**Comment by vkarpov15** [comment]
Looks like we just need https://github.com/ramiel/mongoose-sequence/pull/136 to get merged.
