### ISSUE TITLE
kill pluralization

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#1350]

**Comment by sslyle** [comment]
My two bits.  Just drop the pluralization and lowercase requirement all together.  Don't option it, that's stupid.  Making a all lower case requirement is not being compliant with mongoDB

Think of this AND your next design choices like this:
  - by removing some unnecessary draconian rules in this world YOU ENABLE ME (US / YOUR USERS & FANS) TO BE THE MORE CREATIVE 
  - AND it costs you LESS OF YOUR EFFORT
  - AND enabling my creativity you're BUILDING A BETTER PRODUCT
  - AND by creating and enforcing additional (and by not removing) arbitrary rules the LESS RELEVANT YOU BECOME TO YOU MARKET YOUR MARKET
Just my two bits.
Need help removing the .toLower() in your code on the collection name?
If the application is structured well this is probably in only one line of code.  So you can fix  this in no more consideration that the next maintenance release.

Thanks.

**Comment by vkarpov15** [comment]
I agree wholeheartedly, we're removing pluralization in the next backwards breaking release :+1: I hear your frustration, when I was first starting with mongoose I once spent 2 hours trying to figure out why no documents were saving (back before I knew about `show collections`) and found out that pluralization was saving to a collection that I didn't expect.

![image](https://cloud.githubusercontent.com/assets/1620265/25767088/dcb7003e-31b3-11e7-8d60-bb7005cf3e99.png)

**Comment by Fonger** [comment]
+1 for killing this. I was confused by this behavior long time ago too.

Should this be tagged as mongoose v6.0 and breaking-change?

**Comment by vkarpov15** [comment]
@Fonger we thought about killing it, but upon further discussion we figured removing pluralization by default would cause more harm than good. All existing tutorials assume pluralization, and I don't think the benefit of removing pluralization by default is worth breaking most existing content and most projects that depend on mongoose.

**Comment by Mlocik97** [comment]
this is really dumb feature, but I understand why it can't be removed,... I just don't understand, why it was added in first place.

**Comment by vkarpov15** [comment]
Not our favorite feature either, but it's too big of a breaking change for too little benefit. Mongoose tries to err on the side of stability, we don't make breaking changes unless we think there's a strong argument for the change. And in this case the change would break a lot of existing production code without enough benefit to offset the cost.

**Comment by Mlocik97** [comment]
Probably it would be nice to mark implicit pluralization as deprecated for some time, and then force to use explicit pluralization setting like `mongoose.pluralize(mysettings)`,... and change in some time default setting to null, and then remove it. In slow process it would be not much problem I think... as first You can just put warning to console, when `mongoose.pluralize()` is missing in code.
