### ISSUE TITLE
`match`ing on current date in a virtual populate

### ISSUE THREAD

**Issue by seankwalker** [Automattic/mongoose#13511]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.4

### Node.js version

16.20

### MongoDB version

4.4

### Operating system

macOS

### Issue

Hello,

I'm trying to use a populate virtual that `match`es on a Date field, filtering for documents which have a value that is in the past. My first instinct was to do something like this:

```ts
// MySchema: { _id }
// OtherSchema: { _id, myRef, activeAt }

MySchema.virtual("myVirtual", {
    ref: "OtherSchema",
    localField: "_id",
    foreignField: "myRef",
    justOne: true,
    match: {
        activeAt: {
            $lte: new Date()
        }
    },
    options: {
        sort: { activeAt: -1 }
    }
});
```

But `new Date()` just evaluates when the app first starts up, and so the match query is always just for the same date.

Is there some way to query for the current timestamp when the populate runs?

**Comment by vkarpov15** [comment]
Try replacing `match: { activeAt: { $lte: new Date() } }` with `match: () =>({ activeAt: { $lte: new Date() } })`. Setting `match` to a function means Mongoose executes the `match` function every time you call `populate()`, so that should solve your problem.

**Comment by seankwalker** [comment]
@vkarpov15 oh that works perfectly, thank you so much! 🤦ing at myself because I totally misunderstood the docs. Since it gives the example of matching based on the doc being populated, I thought that was the only way the function match worked.

Thanks again 🙏
