### ISSUE TITLE
[REG 6->7] Plain fields cannot be assigned in special case (typescript error)

### ISSUE THREAD

**Issue by orgads** [Automattic/mongoose#13529]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.0

### Node.js version

18.16.0

### MongoDB server version

5.x

### Typescript version (if applicable)

5.1.3

### Description

Directly assigning to fields of a document fails with v7 when the document is generic (special case, see example).

### Steps to Reproduce

```typescript
import { Model } from 'mongoose';

interface ResourceDoc {
  foo: string;
}

type ResourceIdT<ResourceIdField extends string> = {
  [key in ResourceIdField]: string;
}
type ResourceDocWithId<ResourceIdField extends string> = ResourceDoc & ResourceIdT<ResourceIdField>;

class TestClass<
  ResourceType extends string,
  DocT extends ResourceDocWithId<`${ResourceType}Id`>>
{
  constructor(dbModel: Model<DocT>) {
    const resourceDoc = new dbModel();
    resourceDoc.foo = 'bar'; // Type 'string' is not assignable to type 'Require_id<DocT>["foo"]'
  }
}
```

If I replace <code>\`${ResourceType}Id\`</code> with `'FooId'` then it works.

### Expected Behavior

It should work.

**Comment by vkarpov15** [comment]
As far as I can tell, the script as written should throw an error. `ResourceType` can be any string, so there's no guarantee that there's a `foo` property on `resourceDoc`.

**Comment by orgads** [comment]
@vkarpov15 Notice that `ResourceDocWithId` is an intersection of `ResourceDoc` (which has `foo`) and `ResourceIdT<ResourceIdField>` (which adds the id field).

This is caused by `Omit`. Not sure what has changed between 6 and 7, but #13573 fixes it.
