### ISSUE TITLE
Driver spec

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#1352]
clean up the driver abstraction and _clearly_ document for others.

**Comment by Kingdutch** [comment]
I was going to write a layer around mongoose that allows you to write isomorphic code for retrieving and storing schemas. Any database accessing code on the client would be routed through socket.io by the layer. However, browsing through the Mongoose code I also see drivers. Would it be possible for you to create a Driver spec? I can use the mongodb-native-driver but I might miss out on some conventions or important details.

The driver would use something like socket.io to route requests to the web server, which in turn might still require a separate module.

**Comment by vkarpov15** [comment]
The driver abstraction isn't really well supported right now. Mongoose does have limited isomorphism in 4.0, but I'm not sure it will help you with what you're trying to achieve. The sort of thing you're trying to do (swap out underlying driver for something that does socket.io to a server and do all mongodb communication that way) isn't really something mongoose is going to support in the near future.

**Comment by Kingdutch** [comment]
That's good to know beforehand, thanks for the prompt reply.

Might want to discuss this in another issue but that raises a question. The browser support for Mongoose models is a nice start towards isomorphism but it still requires the user to write database access twice. Once on the client, once on the server. 

The interface for safe retrieval of objects from Mongo is provided by Mongoose (or a way to write your code this way). By astracting the access code it can be really easy to make this code even more Isomorphic.

**Comment by vkarpov15** [comment]
I agree, it's something that I'd like to make possible for others to build in the future and that's part of the reason for the driver abstraction. I don't think mongoose core will support providing an access mechanism for you like that because that would require me to make assumptions about server framework, but I'd love to see more people building that sort of interface.
