### ISSUE TITLE
socketTimeoutMS default value

### ISSUE THREAD

**Issue by P4yBill** [Automattic/mongoose#13537]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.0

### Node.js version

14.21.1

### MongoDB version

4.4.6

### Operating system

None

### Issue

Hello!

Mongoose states that the `socketTimeoutMS` default value is `30000`([link](https://github.com/Automattic/mongoose/blob/95f1ec9f3c0a15c8834f1ba63912f63cc774324c/lib/index.js#L333)).
I searched the codebase and did not find where this default value is set.

Mongodb native client states that the default `socketTimeoutMS` is `0` which means no timeout([link](https://www.mongodb.com/docs/drivers/node/current/fundamentals/connection/connection-options/) or in [v5.1](https://www.mongodb.com/docs/drivers/node/v5.1/fundamentals/connection/connection-options/) of `mongodb` that `Mongoose v7.0.0` is using).

Can someone enlighten me on this matter? Does mongoose use `30000` or `0` ms?

**Comment by vkarpov15** [comment]
That's an error on our docs. Mongoose does not set `socketTimeoutMS`, so the default is whatever the MongoDB Node driver sets.
