### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Togtokhb** [Automattic/mongoose#13531]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^7.3.0

### Node.js version

16.15.1

### MongoDB server version

6.0.3

### Description

/Users/togtokh/Projects/japan/dac/dummy-server/node_modules/mongoose/lib/model.js:3237
        for (let i = 0; i < error.writeErrors.length; ++i) {
                                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at /Users/togtokh/Projects/japan/dac/dummy-server/node_modules/mongoose/lib/model.js:3237:47

### Steps to Reproduce

I should be insert many records into db

**Comment by MohOraby** [comment]
can you provide a reproduceable script that's making your `insertMany` fail
