### ISSUE TITLE
MongoServerError: ns not found - with mongodb ^5.6.0 & mongoose ^7.3.1

### ISSUE THREAD

**Issue by davewichers** [Automattic/mongoose#13549]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.3.1

### Node.js version

16.20.0

### MongoDB version

5.6.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4.1 (M1, not Intel)

### Issue

I have an app using MongoDB with:
  - connect-mongo          ^5.0.0
  -  mongodb               ^5.6.0
  -  mongoose               ^6.7.2

Which works fine. When I then upgrade mongoose to: ^7.3.1

I get the following error:

/Users/dwichers/TESTSUITES/julietjs/node_modules/mongodb/lib/cmap/connection.js:202
                callback(new error_1.MongoServerError(document));
                         ^

MongoServerError: ns not found
    at Connection.onMessage (/Users/dwichers/TESTSUITES/julietjs/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/Users/dwichers/TESTSUITES/julietjs/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/Users/dwichers/TESTSUITES/julietjs/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/Users/dwichers/TESTSUITES/julietjs/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 26,
  codeName: 'NamespaceNotFound',
  [Symbol(errorLabels)]: Set(0) {}
}

Given this is a callback error, I suspect it's something related to what is discussed here: https://mongoosejs.com/docs/migrating_to_7.html but I couldn't see any specific recommendation on this page that might be relevant. The stack trace above doesn't refer to any custom code I've written so I'm at a loss on how to try to fix this.

Any suggestions/pointers would be much appreciated.

**Comment by vkarpov15** [comment]
I don't know of any particular change in Mongoose 7 that would cause this error, but Googling indicates that this error happens when you try to drop a collection that doesn't exist. For example, the following script triggers that error message:

```
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test', { autoCreate: false, autoIndex: false });
  await mongoose.connection.dropDatabase();

  await mongoose.connection.dropCollection('foo');
  console.log('Done');
} 
```

Are you using `dropCollection()` anywhere?

**Comment by davewichers** [comment]
Yes. That is exactly the problem. Thanks. However, that code was written by another dev on the team who is no longer here. The problematic code is below. What we are trying to do is drop the entire Articles collection and then restore it to a known state. However, I suspect maybe the 1st time the Articles don't exist yet, so we need to first check if they exist and then drop them. Otherwise skip the dropCollection step and just create them the first time.

Any quick suggestions on how to fix this code to do that? Sorry but I'm new to NodeJS and Mongo, so hopefully this is easy for you.

```
const databaseState = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
            serverSelectionTimeoutMS: mongoTimeout
        });
        mongoDB = mongoose.connection;
        mongoDB.db.dropCollection('articles', (err, result) => {. <--- Problem here.
            if (err) {
                mongoDB.createCollection('articles', (err, db) => {
                    if (err) {
                        console.log(
                            `MongoDB:`.blue +
                                `\t[INIT ERROR]\t`.red +
                                `Collection 'Articles' already exists"`
                        );
                    } else {
                        console.log(
                            `MongoDB:`.blue +
                                `\t[SUCCESS]\t`.green +
                                `Collection 'Articles' Creating2`
                        );
                        ... more code ...
```

**Comment by vkarpov15** [comment]
I'd recommend just ignoring the error if `err.codeName === 'NamespaceNotFound'`. That's the easiest way to handle "drop if exists". Does that work?
