### ISSUE TITLE
.toObject() has different behavior from 6.x to 7.x

### ISSUE THREAD

**Issue by puskin94** [Automattic/mongoose#13550]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x

### Node.js version

18.15

### MongoDB server version

6.x

### Typescript version (if applicable)

5.1.3

### Description

The `.toObject()` method called after the creation of a document has a different behavior when you compare mongoose version 6.x and 7.x

It looks like the deeply nested properties , when set to undefined, and passed to a `findByIdAndUpdate` in:

- version 6.x are removed
- version 7.x are set to `null`

removing the `toObject()` method call make the 2 mongoose versions behave the same way, as displayed in the steps to Reproduce

### Steps to Reproduce

```js

const mongoose = require('mongoose');

const mySchema = new mongoose.Schema({
    extended: {
        type:    Object || String,
        default: {keep: true}
    }
});

const myModel = mongoose.model('my', mySchema);

async function main() {
    await mongoose.connect('mongodb://localhost:27017/test-mongoose');

    const myObj = {
        extended: {
            something: {else: true},
            level1:    {level2: {prop: 'something'}}
        }
    };

    let added = (await myModel.create(myObj)).toObject(); // Without the toObject both versions behave the same
    console.log('>>> added:', added.extended); // { something: { else: true }, level1: { level2: { prop: something } } }

    added.extended.level1.level2.prop = undefined;
    console.log('>>> updated', added.extended); // { something: { else: true }, level1: { level2: { prop: undefined } } }

    await myModel.findByIdAndUpdate(added._id, added, {lean: true, new: true, overwrite: true});

    const found = await myModel.findById(added._id);
    console.log('>>> found:', found.extended);
    // 7.x.x { something: { else: true }, level1: { level2: { prop: null } } }
    // 6.x.x { something: { else: true } }
}

main()
    .then(() => process.exit())
    .catch(e => {
        console.error(e);
        process.exit(1);
    });

```

These are the logs for version 6.x with the `toObject()` method call:  
![6x with toObject](https://github.com/Automattic/mongoose/assets/8344987/ac91046b-5fe8-4a73-9707-2fc3b5e2b54d)

These are the logs for version 7.x with the `toObject()` method call:  
![7x with toObject](https://github.com/Automattic/mongoose/assets/8344987/84832f8d-d754-446b-a148-ce8d32284849)

These are the logs for version 7.x without the `toObject()` method call:  
![7x without toObject](https://github.com/Automattic/mongoose/assets/8344987/d19389f6-435e-4718-8fac-e79220cc4446)

**Comment by vkarpov15** [comment]
The fundamental issue here is that, in Mongoose 6, `findOneAndUpdate()` with `overwrite: true` executes a `findOneAndReplace()`. We'll add that behavior back to Mongoose 7, but I would recommend you use `findOneAndReplace()` instead of `findOneAndUpdate()` with `overwrite`. We may deprecate the `overwrite` option in the future.
