### ISSUE TITLE
mongoose filter not return all records

### ISSUE THREAD

**Issue by phhuong256** [Automattic/mongoose#13553]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.2.2

### Node.js version

16.20.0

### MongoDB version

5.6.0

### Operating system

Windows

### Issue

```
filter = { service_id: 2, action_type: '001' }

export async function getStatistic(filter) {
  return Model.aggregate([
    {
      $match: filter,
    },
    {
      $project: {
        month: {
          $month: '$action_date',
        },
        year: {
          $year: '$action_date',
        },
      },
    },
    {
      $group: {
        _id: {
          month: '$month',
          year: '$year',
        },
        count: {
          $sum: 1,
        },
      },
    },
  ]);
}
```

In version 4.13.21, the above code is working properly and the results are back from 2021 or later, however when I upgrade to version 7.2.2 I only get the results in June 2023. Is this a bug?

**Comment by vkarpov15** [comment]
Hard to tell from just the code, nothing looks wrong in your aggregation. A couple of suggestions to help debug this:

1. Try enabling Mongoose debug mode using `mongoose.set('debug'', true)` and see if Mongoose 7 is sending a different aggregation for some reason
2. Create a standalone script that demonstrates this issue
