### ISSUE TITLE
Property 'collection' does not exist on type 'Query<unknown, unknown, {}, unknown, "find">'. Did you mean 'collation'?

### ISSUE THREAD

**Issue by mrdulin** [Automattic/mongoose#13569]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.1

### Node.js version

v14.21.3

### MongoDB server version

6.0.6

### Typescript version (if applicable)

^5.1.6

### Description

I saw the `.collection()` method is there from the [`Query`](https://github.com/Automattic/mongoose/blob/95f1ec9f3c0a15c8834f1ba63912f63cc774324c/lib/query.js#L127C10-L127C20) class.

The code works fine at runtime, but TSC will throw a compiler error:

> Property 'collection' does not exist on type 'Query<unknown, unknown, {}, unknown, "find">'. Did you mean 'collation'?ts(2551)

Currently, I have to use the `// @ts-ignore` for the `query.collection()` method.

### Steps to Reproduce

```ts
import mongoose from 'mongoose';
import { config } from '../../config';

mongoose.set('debug', true);

const schema = new mongoose.Schema({
	name: String,
});
const User = mongoose.model('user', schema);

(async function main() {
	try {
		await mongoose.connect(config.MONGODB_URI);

		// test
		const query = new mongoose.Query();
		const r2 = await query
			.setOptions({ lean: true })
			.collection(User.collection)
			.where({ name: 'Tom Benzamin' })
			.select({ _id: 0, address: 0 })
			.exec();
		console.log('r2: ', r2);
	} catch (error) {
		console.error(error);
	} finally {
		await mongoose.connection.close();
	}
})();
```

### Expected Behavior

Please fix this TS type issue.

**Comment by vkarpov15** [comment]
While there is a `collection()` function on Mongoose queries at runtime, this function is not part of Mongoose's publicly documented API, and it isn't meant to be called by end users. If you want to create a new query, you should use `await User.where({ name: 'Tom Benzamin' })..select({ _id: 0, address: 0 }).exec()`.
