### ISSUE TITLE
TTL index in Mongoose not updating expiration time in MongoDB

### ISSUE THREAD

**Issue by Abdulhameed735** [Automattic/mongoose#13585]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.1

### Node.js version

18.16.1

### MongoDB server version

6.0.6

### Typescript version (if applicable)

5.1.3

### Description

The bug is related to the TTL index in Mongoose not updating the expiration time in MongoDB when the schema is modified.

### Steps to Reproduce

**1. Create a Mongoose schema with a TTL index on a field, for example:**

```
const mySchema = new mongoose.Schema({
  expireAt: { type: Date, default: Date.now, index: { expires: "60s" } },
});

```
_Start the application and ensure the index is created in MongoDB._

**2. Update the expiration time in the schema to a different value, for example:** 

```
const mySchema = new mongoose.Schema({
  expireAt: { type: Date, default: Date.now, index: { expires: "10m" } },
});

```
_Save the changes and restart the application._

**3. Check the indexes in MongoDB using db.myCollection.getIndexes() in the Mongo shell.**

### Expected Behavior

The TTL index for `expireAt` field should be updated in MongoDB with the new expiration time of "10m".

**Actual Result:**
The TTL index remains unchanged in MongoDB, still reflecting the old expiration time of "60s".

This behavior requires manually dropping the existing index and restarting the application for the updated expiration time to take effect.

The TTL index remains unchanged in MongoDB, still reflecting the old expiration time of "60s". To apply the updated expiration time, it is necessary to manually drop the index using the `dropIndex() `command in the MongoDB shell and restart the application.

This issue significantly affects the usability and convenience of working with TTL indexes in Mongoose. It would be beneficial to have the TTL index automatically update in MongoDB when the expiration time is modified in the Mongoose schema, eliminating the need for manual intervention.

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior. Mongoose does not automatically drop indexes that conflict with schema-defined indexes. You are responsible for running [syncIndexes](https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes) yourself to update conflicting indexes.

**Comment by Abdulhameed735** [comment]
Ohh right, thank you so much for clarifying this, I'm fairly new to mongoose and mongodb, but in my opinion why would anyone want to keep an index in the background when they change their schema, shouldn't the syncIndexes() be able to run in the background without explicitly calling it. I feel most people will most likely forget this, it can possibly run in the background and then there can be an option to set the calling in  background to false.

**Comment by vkarpov15** [comment]
We may consider making `syncIndexes()` run by default in the future, but the problem is that index builds can cause performance issues in large applications. It is a little risky for us to turn on `syncIndexes()` by default, because anyone running a mongoose application under high load would have to be very careful about upgrading to make sure that indexes match exactly.

**Comment by Abdulhameed735** [comment]
Okay. Thank you so much for clarifying once again. I understand it better now.
