### ISSUE TITLE
findOneAndUpdate on boolean adding inverted commas ""

### ISSUE THREAD

**Issue by sjxuereb** [Automattic/mongoose#13586]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

Version 7.3.2

### Node.js version

v18.13.0

### MongoDB server version

6.0.6

### Description

I have an issue with updating documents with boolean values. Inverted commas being added.

##Schema##
{"_id":"sysparams","objectId":"string","updatedAt":"date","createdAt":"date","_metadata":{"fields_options":{"expiry":{"required":false,"defaultValue":false},"category":{"required":false,"defaultValue":false},"company":{"required":false},"initial":{"required":false,"defaultValue":true}},"indexes":{"_id_":{"_id":1}}},"expiry":"boolean","category":"boolean","company":"string","initial":"boolean"}
##End Schema

### Initial Document ###
{
"_id":"11vZ2Rf9eF",
"expiry":false,
"category":false,
"initial":false,
,"company":"Company"
}
### Code used to update ###
 const filter = { company: company };
 const update = { expiry: true, category: true, initial: true };
 const doc = await Sysparams.findOneAndUpdate(filter, update, {   new: true    });

#### Result after update #####
{
"_id":"11vZ2Rf9eF",
"expiry":"true",
"category":"true",
"initial":"true",
"company":"Company"
}
#### End Result after update #####

The issue is that mongoose is adding extra inverted commas "" to boolean fields. The fields are later not being interpreted correctly by my existing application.

### Code used to update ###
 const filter = { company: company };
 const update = { expiry: true, category: true, initial: true };
 const doc = await Sysparams.findOneAndUpdate(filter, update, {   new: true    });

### Expected Behavior

{
"_id":"11vZ2Rf9eF",
"expiry":true,
"category":true,
"initial":true,
,"company":"Company"
}

Also noticed the key's are being changed from boolean to string

**Comment by sjxuereb** [comment]
Resolved: The problem was with in the schema 

Resolved: New Code
    const filter = { company: company };

    const update = {
        expiry: expiry,
        category: category,
        initial: initial
    };

    let result = await Sysparams.findOneAndUpdate(filter, update, { new: true });

**Comment by vkarpov15** [comment]
@sjxuereb what was the issue with your schema? Missing `type`?

**Comment by sjxuereb** [comment]
Hi @vkarpov15

Yes the issue was resolved by changing the type. The fields were listed as String. I changed them to Boolean.

### Example part of the schema ##

       "expiry": {
            "type": "Boolean"
        },
        "category": {
            "type": "Boolean"
        },
        "company": {
            "type": "String"
        },
        "initial": {
            "type": "Boolean"
        }

Thanks
