### ISSUE TITLE
How can I automatically append a session object to all operations? 

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13587]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.5.2

### Node.js version

16.19.1

### MongoDB version

5

### Operating system

Linux

### Issue

There is a utility method `withTransaction` which allows one to easily wrap multiple operations into a single transaction. One inconvenience is that the session object has to be explicitly passed into every single DB operation, i.e. `model.find({}, null, session })`.

I have developed an additional utility which invokes `withTransaction` and automatically stores the current session in a [CLS context](https://www.npmjs.com/package/cls-hooked). This allows me to access the current session object arbitrarily deep in the call stack without having to pass it down every single method call.

This is convenient because now I can write code like this and be certain that if there is a session in the CLS, it will be picked up and used:

```typescript
class MyRepository {
  findAll() {
    return this.model.find({}, null, {
      session: cls.get("DB_SESSION")
    });
  }
}
```

With this in place, developers can start sessions and use transactions wherever they want and not worry about passing the session object into every single DB operation they are using.

This is already quite nice, but there is still a problem. Whenever we write some repository code we must not forget to add a session object. Our code currently looks like this:

```typescript
class MyRepository {
    findAll() {
        return this.model.find({}, null, { session: this.cls.dbSession }).exec();
    }

    async create(data) {
        const [equipment] = await this.model.create([data], { session: this.cls.dbSession });
        return equipment;
    }

    findByParam(param: string) {
        return this.model.findOne({ "x.param": param }, null, { session: this.cls.dbSession }).exec();
    }
}
```

See how every single method still has to explicitly pass a session object into the operation? That is something I would like to automate / hide. Are you able to advice on how best to do this?

I have looked into hooks and that might work in many instances but not all. E.g. "distinct" does not invoke any hooks, whereas "insertMany" uses the model for hook context and I have no way to create an options object if it was not supplied by the client in the first place.

I have also considered monkey-patching the Query object or perhaps even some mongodb driver code, but I am not sure what the optimal approach would be.

**Comment by vkarpov15** [comment]
Hooks would likely be the way to go. The trick is that you'd need to make sure every query, document, and model instance has a reference to `cls`, whether via importing `cls` or by setting a `cls` property on all queries, documents, and models. Which is doable. What's the problem with `insertMany` hooks?

Also, what makes you think there's no hooks for distinct? We have tests for distinct hooks...

**Comment by juona** [comment]
Thank you for the prompt reply. I'll try to address the specific questions / statements.

---

> you'd need to make sure every query, document, and model instance has a reference to cls

Yes, I understand and this is not an issue.

---

> What's the problem with insertMany hooks?

The problem is that the context of the `insertMany` hook is the Model as opposed to Query / Document and so I am not able to find a way to set a session anywhere

```typescript
schema.pre("insertMany", function(next, docs) {
    // `this` refers to a `Model` - how do I set a session here?
})
```

---

> what makes you think there's no hooks for distinct?

I was referring to the docs at [https://mongoosejs.com/docs/middleware.html](https://mongoosejs.com/docs/middleware.html), but I can see that you're right - there apparently is a distinct hook. My bad, didn't look well enough : ]

**Comment by vkarpov15** [comment]
Re: `insertMany`, 3rd parameter to `insertMany()` is `options`, if specified:

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const schema = new mongoose.Schema({ name: String });

  schema.pre('insertMany', (next, docs, options) => {
    console.log('Options', options); // Options { testOpt: 'hi' }
    options.foo = 'bar'; // Adds an option to insertMany options
    next();
  });
  
  const Test = mongoose.model('Test', schema);
  
  await Test.insertMany([{ name: 'foo' }], { testOpt: 'hi' });
  console.log('Done');
}
```

The only problem is that, if `options` is not explicitly passed in `insertMany()`, then there's no way to set `options`. But you can always do `if (options == null) throw new Error('Must set options in insertMany()')`

Here's an [example on Mongoose playground](https://playground.mongoosejs.io/#YXdhaXQgbW9uZ29vc2UuY29ubmVjdCgnbW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9tb25nb29zZV90ZXN0Jyk7CmNvbnN0IHNjaGVtYSA9IG5ldyBtb25nb29zZS5TY2hlbWEoeyBuYW1lOiBTdHJpbmcgfSk7CgpzY2hlbWEucHJlKCdpbnNlcnRNYW55JywgKG5leHQsIGRvY3MsIG9wdGlvbnMpID0+IHsKICBjb25zb2xlLmxvZygnT3B0aW9ucycsIG9wdGlvbnMpOyAvLyBPcHRpb25zIHsgdGVzdE9wdDogJ2hpJyB9CiAgb3B0aW9ucy5mb28gPSAnYmFyJzsgLy8gQWRkcyBhbiBvcHRpb24gdG8gaW5zZXJ0TWFueSBvcHRpb25zCiAgbmV4dCgpOwp9KTsKCmNvbnN0IFRlc3QgPSBtb25nb29zZS5tb2RlbCgnVGVzdCcsIHNjaGVtYSk7Cgphd2FpdCBUZXN0Lmluc2VydE1hbnkoW3sgbmFtZTogJ2ZvbycgfV0sIHsgdGVzdE9wdDogJ2hpJyB9KTsKY29uc29sZS5sb2coJ0RvbmUnKTsK)

**Comment by juona** [comment]
Looks like this might work out after all. Thank you!
