### ISSUE TITLE
toJSON options gets passed to implicitly created schemas, including transform

### ISSUE THREAD

**Issue by ksmithut** [Automattic/mongoose#13599]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.2.0+

### Node.js version

20.x

### MongoDB server version

6.x

### Description

A new feature was added (https://github.com/Automattic/mongoose/issues/13325) where `toJSON` and `toObject` options get passed to implicitly created schemas in a schema. I believe this was so that if you set `virtuals: true` and `getters: true` that those options would get passed. Another option gets passed that gives us unexpected results: `transform`. We use this `transform()` function to modify the document before it goes out. Before it was only being run for the top level schema, but now it gets run for every sub document.

### Steps to Reproduce

```js
import mongoose from 'mongoose'

const schema = new mongoose.Schema(
  {
    items: [{ key: String }]
  },
  {
    toJSON: {
      transform (doc, obj) {
        console.log(obj)
        return obj
      }
    }
  }
)
const MyModel = mongoose.model('MyModel', schema)
await mongoose.connect('mongodb://localhost:27017/testing')
const doc = await MyModel.create({
  items: [{ key: 'foobar' }]
})
doc.toJSON()
await mongoose.disconnect()
```

This will produce logs that look something like this:

```
{ key: 'foobar', _id: new ObjectId("[objectid]") }
{
  items: [ { key: 'foobar', _id: new ObjectId("[objectid]") } ],
  _id: new ObjectId("[objectid]"),
  __v: 0
}
```

### Expected Behavior

Expected behavior is that the defined transform function would only apply to the schema on which it is defined.

The workaround is to wrap all of the implicit schemas with `new mongoose.Schema()`.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema(
  {
    items: [{ key: String }]
  },
  {
    toJSON: {
      transform (doc, obj) {
        console.log(obj)
        return obj
      }
    }
  }
)
const MyModel = mongoose.model('MyModel', schema)

async function run() {
  await mongoose.connect('mongodb://localhost:27017/testing')
  await mongoose.connection.dropDatabase();
  const doc = await MyModel.create({
    items: [{ key: 'foobar' }]
  })
  doc.toJSON()
  await mongoose.disconnect()
}

run();
```
