### ISSUE TITLE
Model.bulkWrite weird behaviour

### ISSUE THREAD

**Issue by wisdomabioye** [Automattic/mongoose#13597]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.3.0

### Node.js version

18.15.0

### MongoDB version

6.0.6

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.2

### Issue

Consider this code snippet

```
async function performBulkWrite(operations) {
  // ...
  console.log('before write');
  await Model.bulkWrite(operations);
  console.log('after write'); // this line never logged if operations.length === 0
  // ...
}
```

This code never reach here `console.log('after write');` if operations.length === 0;

Is this the right behaviour?

I have fixed it using `if (operations.length === 0) { ... }` but I'm still curious.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({ 
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const array = [];

  await Test.bulkWrite(array);
  console.log('done');
}

run();
```

**Comment by JavaScriptBach** [comment]
I found a similar issue and provided a repro. See https://github.com/Automattic/mongoose/issues/13664
