### ISSUE TITLE
Documentation on ObjectId

### ISSUE THREAD

**Issue by SimonTweddle1** [Automattic/mongoose#13594]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In your documentation for [SchemaTypes](https://mongoosejs.com/docs/schematypes.html) you write:

1. This example:
    ```javascript
    const schema = new Schema({ name: String });
    ```
2. After you mention:
    >A SchemaType is different from a type. In other words, mongoose.ObjectId !== mongoose.Types.ObjectId
2. After, your cite all possible SchemaTypes where String (the one used in the previous example, or just the plain javascript [type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), because it also works with this) is together with [ObjectId](https://mongoosejs.com/docs/schematypes.html#objectids).
    So normally, one would infer that this is possible:
    ```javascript
    const schema = new Schema({ name: ObjectId });
    ```
4. But, when following the **ObjectId** link, ones read:
    Here's how you declare a schema with a path driver that is an ObjectId:
    ```javascript
    const mongoose = require('mongoose');
    const carSchema = new mongoose.Schema({ driver: mongoose.ObjectId });
   ```

So, which one should we use when constructing a schema?
1. **mongoose.ObjectId** or
2. **mongoose.Types.ObjectId** ?

Is it different? is it the same? for the purpose of creating a schema, what's the difference? Why do we have these 2 objects? You try to explain in the rest of the documentation but you fail to answer those questions.

Also, please mention if [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date),... etc are plain javascript objects or are **mongoose.Types.String**, **mongoose.Types.Date**, etc because it works with both, please mention if this is the case and which one should we use.
Be clear when mentioning **ObjectId** if it's from **mongoose.ObjectId** or from **mongoose.Types.ObjectId**

**Comment by vkarpov15** [comment]
Mongoose errs on the side of being permissive, so both `mongoose.ObjectId` and `mongoose.Types.ObjectId` work. We advise using `mongoose.ObjectId`, because that is the constructor for an ObjectId SchemaType (a configuration object describing a property that stores ObjectIds).

You can read more about why we have a separate ObjectId SchemaType here: https://mongoosejs.com/docs/schematypes.html#what-is-a-schematype.

Similarly, `type: Date` is equivalent to `type: mongoose.Schema.Types.Date`, but we generally use `type: Date` because it is more concise.
