### ISSUE TITLE
7.3.3 not published to NPM

### ISSUE THREAD

**Issue by jakesjews** [Automattic/mongoose#13603]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

7.3.3 doesn't appear to be published on [NPM](https://www.npmjs.com/package/mongoose?activeTab=versions).

**Comment by vkarpov15** [comment]
Just published 7.3.3. So sorry for the trouble.

![image](https://github.com/Automattic/mongoose/assets/1620265/6f196fdc-fdcb-4a8e-89e0-ed2f344d3451)
