### ISSUE TITLE
Type defintion of Types.ObjectId/Avoid necessity of including whole Mongoose package for being able to use Types.ObjectId

### ISSUE THREAD

**Issue by christian-schwaderer** [Automattic/mongoose#13606]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7

### Node.js version

18

### MongoDB version

5

### Operating system

Linux

### Issue

In a complex application spanning over multiple GitHub repos, there is one repo which is used solely for sharing TypeScript types and nothing else. That repo is supposed to be very tiny with as few dependencies as possible.
Now, unfortunately, it happens that an interface needs into this repo which has a property typed `Types.ObjectId` (from Mongoose, in case I need to say that).
However, we do not want to include Mongoose as a dependency. That's the classical gorilla-banana-problem: We do not want to include a heavy package like Mongoose just to be able use one type.

What would you suggest?

My thought was to simply copy&paste the type definition of `Types.ObjectId` because I guess it's unlikely to change. However, being not familiar with the code base, copying a type is not that easy. Is this something you can assist me with?

**Comment by vkarpov15** [comment]
A couple of ideas:

1. Include Mongoose as a peer dependency
2. Import ObjectId from [bson](https://www.npmjs.com/package/bson), which is the package where ObjectId is actually defined. bson is a much lighter package.

Personally, I'd probably do (1), unless you want to share types with some projects that don't use Mongoose at all.

**Comment by vkarpov15** [comment]
Maybe generics? Probably a better approach than `Omit<>` since `Omit<>` is pretty brittle.

```ts
interface Person<IdType = string> {
  _id: IdType;
  name: string;
}

interface PersonDocument extends Person<ObjectId> {
}
```
