### ISSUE TITLE
TS error when specifying schema.pre 'deleteOne' with { document: true }

### ISSUE THREAD

**Issue by upirr** [Automattic/mongoose#13601]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.2

### Node.js version

16.18.1

### MongoDB server version

4.4

### Typescript version (if applicable)

5.1

### Description

So basicallly specifying `schema.pre('deleteOne', { document: true }, function() {});` will throw an error:
```
error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"deleteOne"' is not assignable to parameter of type 'RegExp | "insertMany"'.

168  schema.pre('deleteOne', { document: true }, async function preHandler() {
```

Runtime-wise everything works though.

### Steps to Reproduce

```
schema.pre('deleteOne', { document: true }, function() {});
```

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

const testSchema = new mongoose.Schema({
  name: String
});

testSchema.pre('deleteOne', { document: true }, function() {});
```

**Comment by vkarpov15** [comment]
You can work around this by doing `schema.pre('deleteOne', { document: true, query: false }, function() {});` .
