### ISSUE TITLE
getter not work and run when populated or using lookup in aggregation

### ISSUE THREAD

**Issue by metalliclambda** [Automattic/mongoose#13600]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.12.12

### Node.js version

14

### MongoDB version

4.4

### Operating system

Windows

### Issue

I wrote this problem in stackoverflow, also here and if this problem related to my code, I would appreciate it, if you could help me with that. If it is about the structure of the mongoose, I recommend adding this feature to the mongoose, that "getter" work in populate or aggregation lookup too.

this is the stackoverflow question link :
https://stackoverflow.com/questions/76652529/mongoose-getter-not-work-and-run-when-populated-or-using-lookup-in-aggregation

and here is the text of my problem : 

I searched a lot for this problem, but i couldnt find any working answer.
I have a schema that want to add some prefix string to a field when retrieving data from it when populate from other models or using lookup in aggregation.

I write this code, but not work.

    const uploaderSchema = new schema({
      name: String,
      originalName: String,
      path: String,
      size: Number,
      response: { type: String, default: 'Uploaded' },
    }, { timestamps: true })
    
    uploaderSchema.path('path').get(function(value) {
      console.log('In GETTER : ' ,this.$__);
      return `prefixString${value}`;
    });
    uploaderSchema.set('toObject' , {getters : true})
    uploaderSchema.set('toJSON' , {getters : true})
    
    const Uploader = mongoose.model('docs', uploaderSchema)
    exports.Uploader = Uploader

I log the this.__ to undrestand when it is called.

when I get data directly from the Model, it works fine.

but when it is populated or lookup in aggregation, from another Model, not work and Getter not run.

    const data = await AnotherModel.findById().populate('FieldReferredToDocs').exec();

As I populate this Model, many places, I dont  want to use transform in the populate. or use $set it in aggregation.

I want to change it in the schema if it is possible.

I tried this way too, but not work and not run:

    uploaderSchema.set('toObject' , {
      getters : true,
      transform : function(doc, ret, options) {
        console.log('In ToObject transform');
        ret.path = 'prefixString' + ret.path;
        return ret;
      },
    })
    uploaderSchema.set('toJSON' , {
      getters : true,
      transform : function(doc, ret, options) {
        console.log('In ToJSON transform');
        ret.path = 'prefixString' + ret.path;
        return ret;
      },
    })

I logged some string to find out if the function run and if run which is running. But none of them run in populate or lookup in aggregate.

Also add virtual not suits me, bcs it will add new field with new name, and I only want to use the field in the schema.

Thank you in advance.

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script prints out a document with `path: 'prefixStringfoo',` in Mongoose 5.12.12. Please modify the following script to demonstrate the issue you're seeing.

```javascript
'use strict';

const mongoose = require('mongoose');

const uploaderSchema = new mongoose.Schema({
  name: String,
  originalName: String,
  path: String,
  size: Number,
  response: { type: String, default: 'Uploaded' },
}, { timestamps: true })

uploaderSchema.path('path').get(function(value) {
  console.log('In GETTER : ' ,this.$__);
  return `prefixString${value}`;
});
uploaderSchema.set('toObject' , {getters : true})
uploaderSchema.set('toJSON' , {getters : true})

const Uploader = mongoose.model('docs', uploaderSchema);
const Picture = mongoose.model('Picture', mongoose.Schema({
  uploader: { type: 'ObjectId', ref: 'docs' }
}));

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const u = await Uploader.create({ name: 'test', path: 'foo' });
  const p = await Picture.create({ uploader: u._id });

  const res = await Picture.findById(p._id).populate('uploader');
  console.log(res);
}
```
