### ISSUE TITLE
Nested list of discriminator causes findOneAndUpdate to call findOne, no update is done to the document

### ISSUE THREAD

**Issue by GustavPS** [Automattic/mongoose#13604]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.3

### Node.js version

18.15.0

### MongoDB server version

3.6.4 and 6.0.4

### Typescript version (if applicable)

5.1.6

### Description

When trying to update a field that exists in a nested list of discriminators, nothing is happening. Looking at the mongoose logs "findOne" is executed instead of "findOneAndUpdate".
I first found this issue using **typegoose** and created an issue there which you can find [here](https://github.com/typegoose/typegoose/issues/869).

As you can see in that issue we where able to reproduce it with only **mongoose** without having **typegoose** installed. The code example I've provided below is only using mongoose. In that issue you can see that @hasezoey managed to figure out that this only seems to happens when using a string path instead of an object.

### Steps to Reproduce

The basic structure the schema needs to replicate this behaviour is this:
```json
{
  listWithoutDiscriminator: [
    {
      listWithDiscriminators: []
    }
  ]
}
```

Here is the exact code that can be used to reproduce this bug:

```ts
import * as mongoose from 'mongoose'; // mongoose@7.3.3

// Setting up schemas
enum Types {
  TypeWithPropA = 'typeWithPropA',
  TypeWithPropB = 'typeWithPropB'
};

const baseSchema = new mongoose.Schema(
  {
    commonProp: {
      required: true,
      type: String
    },
    type: {
      required: true,
      type: String,
      enum: Types
    }
  },
  {
    discriminatorKey: 'type'
  }
);

const propASchema = new mongoose.Schema(
  {
    propA: {
      type: String,
      required: true
    }
  }
);

const propBSchema = new mongoose.Schema(
  {
    propB: {
      type: String,
      required: true
    }
  }
)


const containNestedSchema = new mongoose.Schema({
  containNestedCommonProp: {
    required: true,
    type: String
  },
  listWithDiscriminators: {
    required: true,
    type: [baseSchema]
  }
});

// Setting up discriminators
{
  const path = containNestedSchema.path('listWithDiscriminators');
  (path as any).discriminator(Types.TypeWithPropA, propASchema, Types.TypeWithPropA);
  (path as any).discriminator(Types.TypeWithPropB, propBSchema, Types.TypeWithPropB);
}

const parentSchema = new mongoose.Schema({
  aRequiredProp: {
    required: true,
    type: String,
  },
  aList: {
    required: true,
    type: [containNestedSchema],
  },
});

const ParentModel = mongoose.model('parent', parentSchema);

const connectToMongo = async () => {
  mongoose.set('debug', true);

  const uri = 'mongodb://localhost:27017';
  const dbName = 'mongoose-test';
  await mongoose.connect(uri, {
    dbName
  });
  console.log('connected to mongodb');
};

const insertToDb = async () => {
  // Inserting a document with an object of type "TypeWithPropA" in the list with discriminators
  await ParentModel.create({
    aRequiredProp: 'hello',
    aList: [
      {
        containNestedCommonProp: 'something-common',
        listWithDiscriminators: [
          {
            type: Types.TypeWithPropA,
            commonProp: 'this is the common prop',
            propA: 'this is propA'
          }
        ]
      }
    ]
  });
}

const updateValue = async () => {
  const filter = {
    aRequiredProp: 'hello'
  };

  const updateQuery = {
    'aList.0.listWithDiscriminators.0.propA': 'An updated value'
  };
  await ParentModel.findOneAndUpdate(filter, updateQuery).exec();
};


const start = async () => {
  await connectToMongo();
  await insertToDb();
  // This update does nothing, it executed "findOne" instead of "findOneAndUpdate"
  await updateValue();
  await mongoose.disconnect();
}

start();
```

Here are the mongoose debug logs from running the above nodejs script:
```
Mongoose: parents.insertOne({ aRequiredProp: 'hello', aList: [ { containNestedCommonProp: 'something-common', listWithDiscriminators: [ { propA: 'this is propA', commonProp: 'this is the common prop', type: 'typeWithPropA' } ] } ], _id: ObjectId("64ae5c94bfd0195072dde1e2"), __v: 0}, {})
Mongoose: parents.findOne({ aRequiredProp: 'hello' }, {})
```
Notice that it's running **findOne**.

This only happens if the discriminator is set on a list that is inside another list.
It however works if I change the type on `listWithDiscriminators` from `[baseSchema]` to `[propASchema || propBSchema]`. It also works if I set `strict: false` in the `QueryOptions` when doing the `findOneAndUpdate`.

Here are the mongoose debug logs from running the above nodejs script, but adding `strict: false`
```
Mongoose: parents.insertOne({ aRequiredProp: 'hello', aList: [ { containNestedCommonProp: 'something-common', listWithDiscriminators: [ { propA: 'this is propA', commonProp: 'this is the common prop', type: 'typeWithPropA' } ] } ], _id: ObjectId("64ae5cbcf1ba6b72603f11c3"), __v: 0}, {})
Mongoose: parents.findOneAndUpdate({ aRequiredProp: 'hello' }, { '$set': { 'aList.0.listWithDiscriminators.0.propA': 'An updated value' }}, { strict: false })
```

And the logs when changing the type from `[baseSchema]` to `[propASchema || propBSchema]`
```
Mongoose: parents.insertOne({ aRequiredProp: 'hello', aList: [ { containNestedCommonProp: 'something-common', listWithDiscriminators: [ { propA: 'this is propA' } ] } ], _id: ObjectId("64ae5dad576b68995b3b7f0b"), __v: 0}, {})
Mongoose: parents.findOneAndUpdate({ aRequiredProp: 'hello' }, { '$set': { 'aList.0.listWithDiscriminators.0.propA': 'An updated value' }}, {})
```
Notice that after either of these changes, **findOneAndUpdate** is being called.

Changing the `UpdateQuery` from a string to an object also correctly calls **findOneAndUpdate**
```ts
  const updateQuery = {
    aList: {
      0: {
        listWithDiscriminators: {
          0: {
            propA: 'Updated value'
          }
        }
      }
    }
  }
```

### Expected Behavior

When using `findOneAndUpdate` on a document with nested discriminator using a `string` update query, `findOneAndUpdate` should be executed, not `findOne` without having to specify `strict: false`, or changing the `type`

**Comment by vkarpov15** [comment]
This is expected behavior. Mongoose doesn't necessarily know what type `aList.0.listWithDiscriminators.0` is when doing `findOneAndUpdate()`. For example, someone else could have inserted another document with `{ aRequiredProp: 'hello' }` that has a different value for `aList.0.listWithDiscriminators.0.type`.

The workaround is to filter by the discriminator key value as follows:

```javascript
  const filter = {
    aRequiredProp: 'hello',
    'aList.0.listWithDiscriminators.0.type': 'typeWithPropA' // <-- tell Mongoose the type of the embedded discriminator
  };

  const updateQuery = {
    'aList.0.listWithDiscriminators.0.propA': 'An updated value'
  };
  await ParentModel.findOneAndUpdate(filter, updateQuery).exec();
```
