### ISSUE TITLE
Mongoose find method memory leak

### ISSUE THREAD

**Issue by qa805542** [Automattic/mongoose#13610]
### Prerequisites

- [X] I have written a descriptive issue title
- [X]  I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.11.3

### Node.js version

16.x

### MongoDB version

4.1.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

I am using find().lean() to fetch docs from mongodb collection. While monitoring the application's performance we found out that every find() operation consumed ~100MB RAM, though the each doc's size is ~2KB and at a time we're fetching only 10 records.

```
const res = await dbModel.find().limit(10).lean()
```

Besides this we observed that after find query is executed the memory is not released by some cursor object, until another find query is executed.

To test this multiple snapshots were taken after find operation was executed. And we observed that strings related to fetched collection docs were still present in heap memory. The heap snapshots were analyzed using chrome dev tools.

![image](https://github.com/Automattic/mongoose/assets/98910140/5c84ada0-54e0-415b-a77f-91218053dca6)
The expected behavior would be that after docs are fetched from the collection, the records must get garbage collected.

Is there a way to fix it ?

Thanks!

**--------- Update ---------**
As per the mongoDB documentation the find query returns a cursor and must be cleared after use to release the consumed resources.  Is it handled internally by mongoose or the user needs to explicitly call some method to clear acquired memory ?

**Comment by vkarpov15** [comment]
I'm unable to repro. I ran the following script for 18 minutes with `node --max-old-space-size=42 gh-13610.js` to severely restrict available memory:

```javascript
'use strict';

const mongoose = require('mongoose');
const v8 = require('v8');

void async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const TestModel = mongoose.model('Test', mongoose.Schema({ data: String }));

  await TestModel.deleteMany({});
  const docs = [];
  for (let i = 0; i < 1000; ++i) {
    docs.push({ data: '0'.repeat(1024 * 2 * 10) });
  }
  await TestModel.create(docs);
  console.log('Created docs');

  let start = Date.now();
  let count = 0;

  while (++count) {
    const res = await TestModel.find().limit(10).lean();
    if (count % 1000 === 0) {
      console.log(`{ x: ${Date.now() - start}, y: ${v8.getHeapStatistics().used_heap_size} },`);
    }
    await new Promise(resolve => setTimeout(resolve, 10));
  }

}();
```

Here's what the memory usage over time looks like:

![image](https://github.com/Automattic/mongoose/assets/1620265/97b080b8-7606-45cf-a44e-15a891c2ba28)

So no indication of a significant memory leak. Keep in mind that v8's garbage collector is fairly lazy, so you may see memory usage increase over time simply because v8 hasn't bothered to gc yet. You shouldn't explicitly need to close a cursor with Mongoose, cursors are closed automatically.

**Comment by qa805542** [comment]
Thanks @vkarpov15 for the response. Will retest this.
