### ISSUE TITLE
Add support for arbitrary keys in all "middleware-able" operation options

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13629]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I propose to extend the solution implemented to address #10688 and add support for arbitrary option keys in all operations that invoke some middleware. I believe this is mostly an issue with the types, so I'll list those that could be improved IMO:

- InsertManyOptions
- SaveOptions

Perhaps there are some more?

### Motivation

My motivation is the same as the one provided for #10688 - I wish to pass some data to my custom middleware, e.g. a flag to modify its behavior on a case-by-case basis.

### Example

```typescript
schema.pre("save", function (next, options) {
    if (!options.whatever) {
        doSomething(this);
    }
    next()
});

// ...

doc.save({ whatever: true }); // disable the middleware
```

Equivalent code for `insertMany()`:

```typescript
schema.pre("insertMany", function (this: Document, next: CallbackWithoutResultAndOptionalError, _: any, options: any) {
    if (!options.whatever) {
        doSomething(this);
    }
    next();
} as any); // I am forced to cast this middleware function to `any` because it does not recognize the `options` argument, but that's a separate problem

// ...

model.insertMany([{}, {}], { whatever: true });
```

**Comment by vkarpov15** [comment]
The following script compiles fine, the only thing you really need to add is a `: Record<string, any>` param to your `pre('save')`. I suspect the `as any` cast is because you have that unnecessary `_: any` param.

```ts
import mongoose from 'mongoose';

const schema = new mongoose.Schema({ name: String });

schema.pre('save', function(next, opts: Record<string, any>) {
  if (opts == null) {
    return next();
  }
  if (opts.fail) {
    throw new Error('oops!');
  }
  return next();
});

schema.pre('insertMany', function(next, opts) {
  if (opts == null) {
    return next();
  }
  if (opts.fail) {
    throw new Error('oops!');
  }
  return next();
});

const Test = mongoose.model('Test', schema);

const doc = new Test({ name: 'foo' });
doc.save({ fail: true });
```

I'd rather not make this change because we're trying to keep our option types reasonably strict in terms of listing out all available key names. And adding `& AnyObject` would make for worse autocomplete on options.

**Comment by juona** [comment]
Yeah, with https://github.com/Automattic/mongoose/issues/13633 complete I can get my code to look quite nice, this is fine : ]
