### ISSUE TITLE
A query executed within a session does not find documents created outside of any session 

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13627]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

16.19.1

### MongoDB server version

5

### Description

I suspect that this might be working as expected, but it's hard to tell.

Consider this:

```typescript
import m from "mongoose";

const MySchema = m.Schema({});

const MyModel = m.model("MyModel", MySchema);

await m.connect("mongodb://my-replica-set");

await MyModel.createCollection();

const session = await m.startSession();

await session.withTransaction(async () => {
    const d1 = await new MyModel({}).save({ session });
    const d2 = await new MyModel({}).save();

    const res = await MyModel.find({}, null, { session });

    console.log("created", d1, d2); // prints two documents
    console.log("found", res); // prints only one document - d1
});

await MyModel.deleteMany({});

process.exit(0);
```

When executed this program will print:

1. "created" followed by two documents - d1 and d2;
2. "found" followed by an array with one document - d1

However, if I don't create d1...:

```typescript
await session.withTransaction(async () => {
    // const d1 = await new MyModel({}).save({ session });
    const d2 = await new MyModel({}).save();

    const res = await MyModel.find({}, null, { session });

    console.log("created", d2); // prints only d2
    console.log("found", res); // prints d2!
});
```

The program will print:

1. "created" followed by a single document - d2;
2. "found" followed by a single document - d2.

Seems like some inconsistency.

### Steps to Reproduce

Use the code provided in the description.

### Expected Behavior

I guess I would expect the find operation to either:

1. always pick up changes that happen outside of the transaction;
2. never pick up any changes that happen outside of the transaction.

At a glance, reproducing this via the MongoDB shell does not seem to be possible because it requires transaction operations to be executed explicitly via a session handler, i.e.:

```javascript
var session = db.getMongo().startSession();

session.withTransaction(async () => {
    const sessionCollection = session.getDatabase("mydb").getCollection("mymodels");

    sessionCollection.updateOne({ _id: 1 }, { $set: { a: 1 } }, { upsert: true });

    db.mymodels.updateOne({ _id: 2 }, { $set: { a: 2 } }, { upsert: true });

    const x = sessionCollection.find({});

    console.log(x); // of course this will only log one item
});
```

That is why I assume that option 2 is what should be expected in this scenario.

**Comment by juona** [comment]
Okay, so I think that my lack of understanding of MongoDB might be the problem here.

Here's what I believe is happening. The session does not actually really start (whatever that means) until the first database operation with a session reference is executed. If I create a session and invoke the withTransaction helper, that does not really change much - I may still execute any number of database operations outside of that session and the changes made by these operations are going to be seen by the transaction. However, as soon as an actual session operation happens (i.e. an operation bearing a session reference is executed) the MongoDB driver goes into some "session mode" and any data changes that happen outside of the session are no longer picked up by the session.

Am I correct?

I've come to this conclusion because I noticed that in my original code if these two lines switch places, the code starts behaving as expected:

```javascript
const d1 = await new MyModel({}).save({ session });
const d2 = await new MyModel({}).save();
```

I.e.:

```javascript
const session = await m.startSession();

await session.withTransaction(async () => {
    // notice that the save with session is the second operation now
    const d2 = await new MyModel({}).save();
    const d1 = await new MyModel({}).save({ session });

    const res = await MyModel.find({}, null, { session });

    console.log("created", d1, d2); // prints two documents
    console.log("found", res); // prints both documents! - good
});
```

Additionally, I have come across a related issue which could be explained the same way.

```javascript
const test2Bad = async () => {
    const session = await m.startSession();

    // create a document without a session
    await new MyModel({}).save();

    await session.withTransaction(async () => {
        // fetch the document within a session
        const doc = await MyModel.findOne({}, null, { session });
        // unset the session
        doc.$session(null);
        // execute a deleteOne operation - I expect this to happen outside of the session
        await doc.deleteOne();

        console.log(await MyModel.countDocuments({}, { session })); // prints 1 - looks like the document is still in the session
        console.log(await MyModel.countDocuments()); // prints 0 - expected
    });

    await session.endSession();

    await MyModel.deleteMany({});
};

const test2Ok1 = async () => {
    const session = await m.startSession();

    await new MyModel({}).save();

    // fetching the document outside of the session actually fixes the isue
    const doc = await MyModel.findOne();

    await session.withTransaction(async () => {
        // the document does not have any session references at this point
        await doc.deleteOne();

        console.log(await MyModel.countDocuments({}, { session })); // prints 0 - expected
        console.log(await MyModel.countDocuments()); // prints 0
    });

    await session.endSession();

    await MyModel.deleteMany({});
};

const test2Ok2 = async () => {
    const session = await m.startSession();

    await new MyModel({}).save();

    await session.withTransaction(async () => {
        // or deleting directly from the DB without fetching the document first also works
        await MyModel.deleteOne();

        console.log(await MyModel.countDocuments({}, { session })); // prints 0 - expected
        console.log(await MyModel.countDocuments()); // prints 0
    });

    await session.endSession();

    await MyModel.deleteMany({});
};
```

**Comment by juona** [comment]
Confirmed same behavior when using the MongoDB driver directly.

```javascript
import m from "mongodb";

const client = new m.MongoClient("mongodb-replicaset-uri");

await client.connect();

const coll = client.db("foo").collection("foo");

await coll.deleteMany();

const session = client.startSession();

const insertResult = await coll.insertOne({ xyz: 1 });

console.log(`inserted document with id ${insertResult.insertedId}`);

try {
  await session.withTransaction(async () => {
    await coll.findOne({}, { session }); // toggle line

    await coll.deleteOne({
      _id: insertResult.insertedId,
    });

    console.log(await coll.countDocuments({}, { session })); // prints 1 if toggle line is enabled, 0 if commented out!
    console.log(await coll.countDocuments()); // prints 0 always
  });
} finally {
  await session.endSession();
  await client.close();
}
```

Thus not a Mongoose issue.

I am not sure why it works like that. Granted, I'll be able to figure this one out eventually, but if anyone has some insights, please let me know.

**Comment by juona** [comment]
Looks like [this is the explanation](https://www.mongodb.com/docs/manual/core/transactions-production-consideration/#in-progress-transactions-and-stale-reads) that I was looking for:

> Read operations inside a transaction can return stale data. That is, read operations inside a transaction are not guaranteed to see writes performed by other committed transactions or non-transactional writes. For example, consider the following sequence: 1) a transaction is in-progress 2) a write outside the transaction deletes a document 3) a read operation inside the transaction is able to read the now-deleted document since the operation is using a snapshot from before the write.

**Comment by vkarpov15** [comment]
Thanks for finding that in the docs @juona  :+1:
