### ISSUE TITLE
Uncaught MongoServerError: Transaction with { txnNumber: 1 } has been committed.

### ISSUE THREAD

**Issue by heartforit** [Automattic/mongoose#13639]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

v20.4.0

### MongoDB server version

6.0

### Typescript version (if applicable)

Version 5.1.6

### Description

I get the following error:
```
<redacted>\node_modules\mongodb\lib\cmap\connection.js:202
                callback(new error_1.MongoServerError(document));
                         ^

MongoServerError: Transaction with { txnNumber: 1 } has been committed.
    at Connection.onMessage (<redacted>\node_modules\mongodb\lib\cmap\connection.js:202:26)
    at MessageStream.<anonymous> (<redacted>\node_modules\mongodb\lib\cmap\connection.js:61:60)
    at MessageStream.emit (node:events:512:28)
    at processIncomingData (<redacted>\node_modules\mongodb\lib\cmap\message_stream.js:124:16)
    at MessageStream._write (<redacted>\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:399:12)
    at _write (node:internal/streams/writable:340:10)
    at Writable.write (node:internal/streams/writable:344:10)
    at Socket.ondata (node:internal/streams/readable:785:22)
    at Socket.emit (node:events:512:28) {
  ok: 0,
  code: 256,
  codeName: 'TransactionCommitted',
  '$clusterTime': {
    clusterTime: Timestamp { low: 3, high: 1689889708, unsigned: true },
    signature: {
      hash: Binary {
        sub_type: 0,
        buffer: Buffer(20) [Uint8Array] [
           58, 185, 223,  35,   3, 180,
          227, 159, 251, 129,   1,  85,
           15, 123, 145, 254, 237, 158,
          177, 129
        ],
        position: 20
      },
      keyId: Long { low: 4, high: 1682732330, unsigned: false }
    }
  },
  operationTime: Timestamp { low: 1, high: 1689889708, unsigned: true },
  [Symbol(errorLabels)]: Set(0) {}
}
```

The problem is, that  this is not an error at all. Server said all right. Done what you wanted me to do.
From my perspective this is an serious bug, since it is in the latest version and dependes on transactions.
They work, but now I have to work around this bug, which I don´t know how because error gets thrown in different context, when all promises are already done.

### Steps to Reproduce

I did something like this
```
let transactionSession = await connection.startSession();
await transactionSession.startTransaction();

<serious work>

await transactionSession.commitTransaction() <-- this line crashes the flow but server said "Transaction with { txnNumber: 1 } has been committed."

await transactionSession.endSession()
```
Look into the database shows entry was created.

### Expected Behavior

Don`t crash. Just finish.

**Comment by heartforit** [comment]
Bumped version to latest 7.4.0. No change.
Image of debugger with state:
![bug-report-shot-1](https://github.com/Automattic/mongoose/assets/2421850/e7a16c63-9a39-4c1f-819e-3f7918b7efd4)

**Comment by heartforit** [comment]
I think is still an bug, but I know now why it happends. It is a race condition triggered by and forgotten "await .save()" call. Transaction finishes, but data is not written yet. Very missleading. 
I fixed it. Sorry for the confustion!!! Maybe somone else runs over this. But still errmsg should not contain success state in my opinion.

Best

**Comment by Uzlopak** [comment]
I think it is an MongoServerError, so it comes from the MongoDB itself. I agree with you that it is misleading as it should have been: 
"Transaction with { txnNumber: 1 } has already been committed." or similar.

Glad that you fixed your issue. Have a nice day.
