### ISSUE TITLE
Some middleware does not have access to operation options

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13633]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

16.19.1

### MongoDB server version

5

### Typescript version (if applicable)

4.8.3

### Description

It is not possible to access the operation options in the following middleware functions:

- document pre/post updateOne / deleteOne
- document post save
- pre/post insertMany

I know that the pre middlewares of the above operations do in fact get a reference to the options object supplied by the client. Unfortunately, these objects are not included in the type definitions of the middleware functions, so it is not possible to access them without overriding the types.

### Steps to Reproduce

```typescript
schema.pre("updateOne", { document: true, query: false }, function(next) {
    // no way to access operation options here
})

schema.pre("updateOne", { document: true, query: false }, function(next, options) {
    // does not compile
})

schema.post("save", function(res, next) {
    // no way to access operation options here
})

schema.post("save", function(res, next, options) {
    // does not compile
})

schema.pre("insertMany", function(next, docs) {
    // no way to access operation options here
})

schema.pre("insertMany", function(next, docs, options) {
    // does not compile
})
```

Same with post updateOne, pre/post deleteOne, post insertMany

### Expected Behavior

Ideally I'd like to be able to always access operation options like this can be done with query / aggregation middleware:

```typescript
schema.pre("find", function(next) {
    this.getOptions()
})

schema.pre("aggregate", function(next) {
    this.options
})
```

I understand that this might not be possible with Document middleware, in which case it would be nice to receive the options as the last argument to the middleware. Matter of fact, this is already the case, only the types do not reflect that.

**Comment by vkarpov15** [comment]
With #13708, everything except the following will compile.

```javascript
schema.post("save", function(res, next, options) {
    // does not compile
})
```

That's because post save hooks don't get options. As a matter of fact, `function(res, next, options)` will unfortunately end up as [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware), so will execute with `(err, res, next)`.

To access options in post hooks, do the following:

```javascript
schema.pre('save', function(next, options) {
  this.$locals.saveOptions = options;
});

schema.post('save', function() {
  this.$locals.saveOptions; // Get options from initial save
});
```

**Comment by juona** [comment]
Migrating to v7 at the moment, tested this out - looks good. Thank you!
