### ISSUE TITLE
Model.aggregate<T>() does not check type of value returned, with return type.

### ISSUE THREAD

**Issue by nirvikpurkait** [Automattic/mongoose#13647]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

18.16.1

### MongoDB server version

6.0.4

### Typescript version (if applicable)

5.1.6

### Description

Snippet -
```
// user_actions.ts

import User from "./user_schema";

interface UserDetails {
  name: string;
  otherPorp: string;
}

const getUser = async () => {
  const users = await User.aggregate([
    { $match: { name: "Abc" } },
  ]);
};

export { getUser };
```

If I use `User.aggregare()` , without any generic-type the return type is `Aggregate<any[]>` , but if we use the same `User.aggregare()` with a generic-type i.e `User.aggregate<UserDetails>()` , the return type is `Aggregate<UserDetails[]>`. If I resolve both of them I get `any[]` and `UserDetails[]` as type of `users` respectively. Now if I log the value of `users` , for the scenerio-2, the value of the `users` does not match with type of the `users` inferred form resolving aggregation.

___________

NB: I do not have `otherProp` as a field, for better clarification schema and model given below.
```
import mongoose, { Schema } from "mongoose";

interface UserType {
  name: string;
}

const userSchema = new Schema<UserType>({
  name: {
    type: String,
  },
});

const User = mongoose.model<UserType>("User", userSchema);

export default User;
```

### Steps to Reproduce

```
const users = await User.aggregate();
```

![Screenshot 2023-07-24 123253](https://github.com/Automattic/mongoose/assets/93871471/7a8254bc-e713-42d6-b4ac-d0acdb373485)
![Screenshot 2023-07-24 123028](https://github.com/Automattic/mongoose/assets/93871471/6c91bcd0-1c4f-4d7d-992f-77bb66f75347)

```
const users = await User.aggregate<UserDetails>();
```
![Screenshot 2023-07-24 123354](https://github.com/Automattic/mongoose/assets/93871471/1431cacf-3c25-433b-a520-4024291cb1fd)
![Screenshot 2023-07-24 123426](https://github.com/Automattic/mongoose/assets/93871471/84761826-d3a8-43c0-acb1-bf4c5f6a30e5)

When logging `users`, the logging value type does not match with inferred type
![Screenshot 2023-07-24 124638](https://github.com/Automattic/mongoose/assets/93871471/2fa0653c-a980-4fbd-bbf4-511740cc1aee)

### Expected Behavior

When we are implicitly providing the type, `UserDetails` to the `User.aggregate<UserDetails>()` , and as it is returning the type `Aggregate<UserDetails[]>`, the the type of the final value should be type checked, and if the value type mismatch with the type provided, it should give error.

As the `User.aggregate<UserDetails>()` lacks one property `otherPorp`, it should show error like: Property `otherPorp` is missing in type `Aggregate<{ name: string; }[]>` but required in type `Aggregate<UserDetails[]>`.
____

NB: We can consider the `_id:` property checking to be skipped, as they are inbuilt with MongoDB.

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

interface UserType {
  name: string;
}

interface UserDetails {
  name: string;
  otherProp: string;
}

const userSchema = new mongoose.Schema<UserType>({
  name: {
    type: String
  }
});

const User = mongoose.model<UserType>('User', userSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  await User.create({ name: "ABC"})

  const users = await User.aggregate<UserDetails>([{ $match: { name: 'ABC' } }]);
  const user = await User.aggregate([{ $match: { name: 'ABC' } }]);
  console.log('users', users);
  console.log('user', user);
}

run();
```
