### ISSUE TITLE
Typescript; Use methods on populated field

### ISSUE THREAD

**Issue by gearintellix** [Automattic/mongoose#13640]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.3.4

### Node.js version

18.14.0

### MongoDB version

6.0.8

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I struggling how to use methods on populated field

here the example code: ([tsplayground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAIhAxgVxBQDsYAaOAWQgBMUAbCgCURqgEMYUacCjS4AXzgAzKBBBwARCAjEA5hAgBnFFIDcAKE2hIsOAC9R4yVIO0NO8NHiYAyrgAWKEOwqy69IcYnTZCpVVLTRQADz14XDlleAAtAFVVKDgAXkMAOggAIwArFFwYAAp0TQBIYnYiAC4MmKhgBUKASjJNQSatMIiEZDQASUSUZLSDdIaRIYAeJFQIETgEpIA+LQauKBF2XH7BqEoUGEdaDDLlCRR9w9pCw+BlGpY2Tm5eQhIYSYHlppq7GHqFFpBCFwjY4GshpttnAvkNXvx4GEuMQaMo4AA5OTo-D0ejsLL0FCTeHvT67S5HGhLADaAHIAPrAGi0gC6SwosL2B0pGGBUWIMTguwczlcqTgxBQAHc4CKXOwyUkKNRPIqhuyYeTubQloUyiVSuVKigagbDTMTbL-g15K1DaUoCgAI74YCOmg1f74FB20qCO3+-VlUowUAoGKVMD3BBQb2+ohXVGm4OlM5ECnXH5WgHyE72h0HfBQYgIRx3dIVIhae2Bw214EdEHdfmC3bijwMQpSXZSCjCpzyxtNsEtuIAQVwUXwAhGmVy+SKBvwST6WBqowIMQkkzlrnSABVesp0gB5ecFPpU5qtdqdUH6C0widTmcZcZTC1zBbPiDTmArTRRzgH8-13dhxUlGUwM+EDSF1INDWXIZV2Te0LV+Ac90PVBjzPPILxoX0CxEGpuySXtg3rVpGy6EdongWD4DSDt6C7Rje2Aydf1IMCh0KdhlEQYhcDgZpUiWE5NDgaS4AAelkmNEDgABGKSZKArYXyYuB2CldhgAYri-3SEQGhoE9JWadJIDAHFnkmdAkKgFDNSSQRdSkJzVykJp0jCfJmi0GTwXmfijNIJoTmC4LNO4mB0i8rB0jTC5tRoMT5LgXB2FxUs0Cc2k0QTSllDU6TgTKuSFP+JSACZKohDYth2JISQEJESFRDEsRxPECSJNqPk5GkGSZVkNU5DMaF5SqNPCmBlPFXT9MMrSTLMiyUCsmy7K4BzEpqTlBvcrtEp8vzQgCxtguAULYr-ZTIpKaKZPu0hlISlckpSqaMoU7LcsOfKkkKuBitoUrgoq9pmk0IA))
```typescript
import type { Document, Model, HydratedDocument } from "mongoose";

import z from "zod";
import { Schema, model } from "mongoose";

export const ZUser = z.object({
	name: z.string(),
});
export type IUser = z.infer<typeof ZUser>;
interface IUserMethod {
	someMethod(this: HydratedDocument<IUser>): String;
}
export interface IUserDocument extends NonNullable<Document<IUserMethod>['_id']>, IUserMethod {}
const UserSchema = new Schema<IUser, Model<IUser>, IUserMethod>(
	{
		name: {
			type: String,
			required: true,
		},
	},
	{
		timestamps: true,
		methods: {
			someMethod(): String {
				return this.name;
			},
		},
	}
);
export const User = model("User", UserSchema);

export const ZAccount = z.object({
	userID: z.custom<Schema.Types.ObjectId>(),
});
export type IAccount = z.infer<typeof ZAccount>;
const AccountSchema = new Schema<IAccount>(
	{
		userID: {
			type: Schema.Types.ObjectId,
			ref: "User",
		},
	},
);
export const Account = model("Account", AccountSchema);

(async () => {

    // try 1
    const account = await Account.findOne().populate<{userID: IUser}>("userID").exec();
    if (account) {
        account.userID.someMethod() // call the user's methods
    }

    // try 2
    interface IUserDocument extends NonNullable<Document<IUser>['_id']>, IUserMethod {}
    const account1 = await Account.findOne().populate<{userID: IUserDocument}>("userID").exec();
    if (account1) {
        account1.userID.someMethod() // call the user's methods
    }

})()
```
is there any way to access the methods on populated field in typescript?

**Comment by vkarpov15** [comment]
Try the following. 2 big changes: 1) make `IUserDocument` use `HydratedDocument` rather than `extends Document`: that is not supported. 2) pull `methods` out of schema options for now; `methods` in schema options doesn't seem to work very well unless you're using Mongoose's automatic type inference.

```ts
import type { Document, Model, HydratedDocument } from "mongoose";

import * as z from "zod";
import { Schema, model } from "mongoose";

export const ZUser = z.object({
  name: z.string(),
});
export type IUser = z.infer<typeof ZUser>;
interface IUserMethod {
  someMethod(): string;
}
export type IUserDocument = HydratedDocument<IUser, IUserMethod>;
const UserSchema = new Schema<IUser, Model<IUser>, IUserMethod>(
  {
    name: { 
      type: String,
      required: true,
    },
  },
  { 
    timestamps: true,
  }
);
UserSchema.methods.someMethod = function someMethod(): string {
  return this.name;
}
export const User = model("User", UserSchema);

export const ZAccount = z.object({
  userID: z.custom<Schema.Types.ObjectId>(),
});
export type IAccount = z.infer<typeof ZAccount>;
const AccountSchema = new Schema<IAccount>(
  {
    userID: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
  },
);
export const Account = model("Account", AccountSchema);

(async () => {

    // try 1
    /*const account = await Account.findOne().populate<{userID: IUser}>("userID").exec();
    if (account) {
        account.userID.someMethod() // call the user's methods
    }*/

    // try 2
    interface IUserDocument extends NonNullable<Document<IUser>['_id']>, IUserMethod {}
    const account1 = await Account.findOne().populate<{userID: IUserDocument}>("userID").exec();
    if (account1) {
        account1.userID.someMethod() // call the user's methods
    }

})()
```

**Comment by gearintellix** [comment]
I see, it working now
thank you
