### ISSUE TITLE
Use existing mongodb connection in mongoose.connect

### ISSUE THREAD

**Issue by wisdomabioye** [Automattic/mongoose#13646]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.3.0

### Node.js version

18.15.0

### MongoDB version

6.0.6

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04.2

### Issue

I have an existing MongoDB connection established using mongdbClient.connect(URL). Is there a method to pass this existing connection to mongoose so mongoose wouldn't have to establish a separate connection?

**Comment by vkarpov15** [comment]
Use the [`Connection.prototype.setClient()` function](https://mongoosejs.com/docs/api/connection.html#Connection.prototype.setClient()):

```javascript
mongoose.connection.setClient(mongodbClient);
```

Just make sure that the version of the MongoDB Node driver lines up _exactly_ with the version that Mongoose lists in its `package.json`. Mongoose doesn't support multiple MongoDB Node driver versions currently.
