### ISSUE TITLE
Disable All Mongoose Logging

### ISSUE THREAD

**Issue by JemiloII** [Automattic/mongoose#13645]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

latest

### Node.js version

latest

### MongoDB version

latest

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Issue

How on earth do I disable the logging?

mongoose.set('debug', false) still is logging for insertMany. it's driving crazy. I don't want it logging anything.

**Comment by hasezoey** [comment]
please provide which mongoose version you are currently running, it would also be good to have a example of how you use mongoose
