### ISSUE TITLE
Map schema type converts UUID into plain string

### ISSUE THREAD

**Issue by men232** [Automattic/mongoose#13657]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

18

### MongoDB server version

4.4

### Description

Seems Map schema type makes unnecessary conversion via `__schemaType.applyGetters` for updates query. I noted it when developing my custom types that based on MongooseBuffer, i just tried  Map + UUID combination and got the same issue.

### Steps to Reproduce

```js
import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';

const Schema = new mongoose.Schema(
  {
    doc_map: {
      type: mongoose.Schema.Types.Map,
      of: mongoose.Schema.Types.UUID,
    },
  },
  { collection: 'users_test' },
);

const User = mongoose.model('TestUser', Schema);

async function test() {
  const user = new User({
    doc_map: new Map([
      ['role_1', randomUUID()],
      ['role_2', randomUUID()],
    ]),
  });

  await user.save();

  // all good here
  console.log(user.doc_map);

  // trying to update
  user.doc_map.set('role_1', randomUUID());

  await user.save();

  // got string in doc_map -> role_1
}

test().catch(console.error);

```

**Comment by IslandRhythms** [comment]
I couldn't get it to print via a console log but it does show as such in the db

![image](https://github.com/Automattic/mongoose/assets/39510674/6ffe50b1-d689-4059-88c3-76dfb847610c)
