### ISSUE TITLE
Didnt return _id after create new entity

### ISSUE THREAD

**Issue by sur-ser** [Automattic/mongoose#13652]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

18.12.1-alpine

### MongoDB server version

6.0.8

### Description

After i use model.create({..}) document created normal, in database i have see id but mongoose return null for id

### model:
```
const { model, Schema } = require("mongoose");

const userSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
    },
    toObject: {
      virtuals: true,
    }
  }
);

const UserModel = model("User", userSchema);
```

### code:

```
const newUser = await User.create({name: "some name"})
console.log(newUser)
```

**and id will be null**

### Expected Behavior

i expect that i will get in id object id but i have got null

**Comment by BenaliDjamel** [comment]
I tested your code and it seems you have syntax issues, schema can accept many objects not single object that contains your data like you did, `schema({...}); `

I fixed your example, check this link: [example](https://playground.mongoosejs.io/#YXdhaXQgbW9uZ29vc2UuY29ubmVjdCgnbW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9tb25nb29zZV90ZXN0Jyk7CiBjb25zdCB1c2VyU2NoZW1hID0gbmV3IG1vbmdvb3NlLlNjaGVtYSgKICB7CiAgICBuYW1lOiB7CiAgICAgIHR5cGU6IFN0cmluZywKICAgICAgcmVxdWlyZWQ6IHRydWUsCiAgfQogIH0sCiAgeyB0aW1lc3RhbXBzOiB0cnVlfSwKICB7CiAgICB0aW1lc3RhbXBzOiB0cnVlLAogICAgdG9KU09OOiB7CiAgICAgIHZpcnR1YWxzOiB0cnVlLAogICAgfSwKICAgIHRvT2JqZWN0OiB7CiAgICAgIHZpcnR1YWxzOiB0cnVlLAogICAgfQogIH0KKTsKY29uc3QgVGVzdE1vZGVsID0gbW9uZ29vc2UubW9kZWwoIlVzZXIiLCB1c2VyU2NoZW1hKTsKCmNvbnN0IGRvYyA9IGF3YWl0ICBUZXN0TW9kZWwuY3JlYXRlKHtuYW1lOiAic29tZSBuYW1lIn0pCmNvbnN0IGRvY3MgPSBhd2FpdCBUZXN0TW9kZWwuZmluZCgpOwpjb25zb2xlLmxvZygnUmVzdWx0JywgZG9jcy5tYXAoZG9jID0+IGRvYy50b09iamVjdCgpKSk7), it works perfectly.

**Comment by sur-ser** [comment]
i am not understand, this is my full code, and it works fine as expected on mongoose version 7.3.4, when i change version to newer id returns as nulll

const { model, Schema } = require("mongoose");

const userSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
    role: {
      type: String,
      enum: ['admin','user'],
      default: 'user',
    },
    phones: [
      {
        number: Number,
        type: {
          type: String,
          enum: ['mobile','whatsapp','viber','telegram'],
          default: 'mobile',
        },
      }
    ],
    verified: {
      type: Boolean,
      default: false,
    },
    blocked: {
      type: Boolean,
      default: false,
    },
    blockedAt: {
      type: Date,
      required: false,
    }
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
    },
    toObject: {
      virtuals: true,
    }
  }
);

userSchema.virtual("tokens", {
  ref: "Token",
  localField: "_id",
  foreignField: "userId",
  justOne: false,
});

userSchema.virtual("ads", {
  ref: "Ad",
  localField: "_id",
  foreignField: "publisherId",
  justOne: false,
});

userSchema.virtual("passwordRestoreTokens", {
  ref: "PasswordRestoreToken",
  localField: "_id",
  foreignField: "userId",
  justOne: false,
});

const UserModel = model("User", userSchema);

module.exports = UserModel;

**Comment by BenaliDjamel** [comment]
I tested your example and it works fine for me, screenshot attached below:
```
 const user = await UserModel.create({ name: "some name", email: "email@gmail.com" });
 console.log("🚀 ~ file: the data returned from create:", user, `mongoose version ${mongoose.version}`);
```

<img width="358" alt="image" src="https://github.com/Automattic/mongoose/assets/35254265/4ce1603b-c327-46ba-beed-4ff99e47a796">

**Comment by vkarpov15** [comment]
The issue is the following:

```
new UserEntity(newUser._id, newUser.name, newUser.email, newUser.password, newUser.role, newUser.phones, false, false, newUser.createdAt, newUser.updatedAt);
```

That syntax is not supported, you would need to do `new UserEntity({ _id: newUser._id })`. Presuming `UserEntity` is a Mongoose model.

**Comment by sur-ser** [comment]
entity is my class, thanks i will test more times and if i have got same i will told you
