### ISSUE TITLE
mongoose.connection is undefined after 'connect' after library updates

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#13653]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.4

### Node.js version

19.7.0

### MongoDB server version

Atlas

### Typescript version (if applicable)

5.1.6

### Description

I did some experiments on a test branch that involved installing / upgrading several packages. None were related to mongoose, but I noticed that my app's initial connection attempt is failing with this error now:

> TypeError:` Cannot read properties of undefined (reading 'on')

Which basically means that `mongoose.connection` is undefined even though I'm awaiting the `connect` method.

            await mongoose.connect(uri, options);
            // register event listener to track connection losses
            mongoose.connection.on("error", err => {
               ...
            });
            
 
 My connection routine has an automatic retry, and it fails reliably on the initial attempt, and succeeds reliably on the second. It's not a problem for me as it's only a test branch with all the test packages, but I though I'd give you a heads-up.

Further observations:

* We were on mongoose ^6.6.5 and then upgraded to the latest, which didn't change anything
* I can send you guys the yarn.lock files to get a delta if you want (preferrable wouldn't want to paste that here though))
* Feel free to close this at any time. As said, it's more of an FYI than an actual problem for us currently

### Steps to Reproduce

I'm just awaiting `mongoose.connect(...)`

### Expected Behavior

`mongoose.connection` to not be undefined after connecting.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.connection.on('error', err => {
  console.log(err);
});

mongoose.connection.on('connected', () => {
  console.log('connected')
});

async function run() {
  await mongoose.connect('mongodb://localhost:27017')
}

run();
```

**Comment by hardcodet** [comment]
That does confuse me a little, but it seems to do the trick :)

So there is a `connection` object before connection and after connecting, but potentially not right after connecting?
and would that always be the same instance, or may i potentially subscribe to an outdated `connection` instance?

**Comment by vkarpov15** [comment]
@hardcodet AFAIK it isn't possible for `mongoose.connection` to be undefined. If anything, the [connection setter](https://github.com/Automattic/mongoose/blob/255493b51db27e61bd84ef9bfef47a0ac4068183/lib/index.js#L743-L747) explicitly prevents setting `connection` to `null`.

Do you happen to call `mongoose.connection.destroy()` or `setDriver()`?

**Comment by hardcodet** [comment]
I'm importing mongoose like this, just in case:

```
import * as mongoose from "mongoose";
``` 

Fully unrelated side note: Working on a project with an another ORM that bleeds its own `Collection` instance into my codebase, and it makes me appreciate your array implementation *so* much! Really enjoyed mongoose all those years :)

**Comment by hardcodet** [comment]
Will do! Closing this issue now, if that's ok - I guess there's enough pointers here for others, should they stumble over it.
Thanks :)
