### ISSUE TITLE
model.findOne() stopped working after upgrade from v6 to v7

### ISSUE THREAD

**Issue by miguelSoldado1** [Automattic/mongoose#13666]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

18.16.0

### MongoDB server version

6.0.8

### Typescript version (if applicable)

5.1.6

### Description

I upgraded from v6 to v7 and my findOne()'s straight up stopped working.
`const following = await follow.findOne({ folower_id, following_id });`

### Steps to Reproduce

just call findOne in any model

**Comment by IslandRhythms** [comment]
What does "stopped working" mean? Is it hanging indefinitely? Is it returning null?

**Comment by miguelSoldado1** [comment]
It's returning null even tho there's an entry in the collection that matches the conditions and was working in v6.4.6.
Sorry for the lack of detail previously...

**Comment by IslandRhythms** [comment]
If your steps are correct then the issue if you forgot the `.`

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.create({ name: 'Test testerson'});

  console.log(await Test.findOne({ _id: doc._id }))
}

run();
```

**Comment by miguelSoldado1** [comment]
nope, this is the bit of code where following is returning null:
`
    const { following_id } = req.query;
    const data = await getUser(req);
    const folower_id = data.body.id;
    const following = await follow.findOne({ folower_id, following_id });
`

and this is my "follow" schema: 
`const followSchema: Schema = new Schema<Follow>(
  {
    follower_id: { type: String, required: true },
    following_id: { type: String, required: true },
    createdAt: { type: Date, default: new Date() },
  },
  { versionKey: false }
);

export default model<Follow>("Follow", followSchema, "follow");
`
and the findOne() call just started returning null after I updated to v7. Since then I've rolled back to v6 and everything works fine.

**Comment by IslandRhythms** [comment]
Double check that the document you're looking for exists in the db. 

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String,
  age: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.create({ name: 'Test testerson', age: 0});
  const name = "Test testerson";
  const age = 0;

  console.log(await Test.findOne({ name, age }))
}

run();
```

**Comment by miguelSoldado1** [comment]
I did... And like I said it works fine in v6 so the doc definitely exists

**Comment by vkarpov15** [comment]
You have a typo: you use `folower_id` in your query but `follower_id` in your schema. In v6, Mongoose would strip unknown fields from your query filter by default. In v7, Mongoose no longer strips unknown fields from your query filter, so the invalid field `folower_id` is no longer stripped out.

**Comment by miguelSoldado1** [comment]
Oh damn, you're right! I feel dumb, sorry... To prevent typos in the future, is there any way of adding type safety to the mongoose models currently ? Thanks for the help regardless.
