### ISSUE TITLE
Is it safe to reuse Mongoose's MongoDB clients?

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#13665]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.4

### Node.js version

18.16.1

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

## Question
Do Mongoose connections use the same MongoClient object for the lifetime of the connection? Or does the MongoClient get periodically destroyed and recreated?

## Context
I have a node.js webserver using Mongoose. It also uses [connect-mongo](https://www.npmjs.com/package/connect-mongo), an express.js middleware to manage user sessions in MongoDB.

This middleware needs to be initialized with a MongoClient at server startup. So I thought I could reuse mongoose's MongoClient like this:

```javascript
await mongoose.connect(...);
const client = mongoose.connection.getClient();

const app = express();
app.use(expressSession({
  store: MongoStore.create({
    client,
    ...
  })
});
```

However, this code ran into issues where `connect-mongo` sometimes ended up with a MongoClient with a cleared connection pool, leading all web requests to fail. My hypothesis is that Mongoose connections may destroy their underlying MongoClients and thus it's not safe to share MongoClients this way. Is this correct? I tried skimming the code but I wasn't sure. Would appreciate an answer if you have time, and it may be worth mentioning this in the docs if so.

Thanks!

**Comment by vkarpov15** [comment]
Mongoose doesn't destroy the underlying MongoClient unless you explicitly call `close()`, `disconnect()`, or `destroy()`. You should be fine to reuse Mongoose's `MongoClient` instance, the only thing I'd advise you to look out for is [slow trains](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs).

What does the error message you're getting look like?

**Comment by JavaScriptBach** [comment]
```
MongoPoolClearedError: Connection pool for <our_mongodb_url>:27017 was cleared because another operation failed with: "AWS request to http://169.254.170.2/v2/credentials/af29a211-a9f2-43ba-a713-74d75bf91c21 timed out after 10000 ms"
    at ConnectionPool.processWaitQueue (/node_modules/mongodb/src/cmap/connection_pool.ts:715:65)
    at ConnectionPool.clear (/node_modules/mongodb/src/cmap/connection_pool.ts:444:10)
    at updateServers (/node_modules/mongodb/src/sdam/topology.ts:842:23)
    at Topology.serverUpdateHandler (/node_modules/mongodb/src/sdam/topology.ts:687:5)
    at Server.<anonymous> (/node_modules/mongodb/src/sdam/topology.ts:822:66)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at markServerUnknown (/node_modules/mongodb/src/sdam/server.ts:445:10)
    at Server.handleError (/node_modules/mongodb/src/sdam/server.ts:401:9)
    at /node_modules/mongodb/src/sdam/server.ts:356:18
```

**Comment by vkarpov15** [comment]
I haven't seen that error before. It looks like you might be using [AWS IAM authentication with MongoDB](https://www.mongodb.com/docs/atlas/security/passwordless-authentication/), have you been experiencing any trouble with that? The error message looks like there's some auth issue.

Also, can you confirm which version of connect-mongo you're using? It might be possible that you're using a version of connect-mongo that isn't compatible with the version of the MongoDB node driver that Mongoose uses.

**Comment by JavaScriptBach** [comment]
Who is responsible for reconnecting to the database if the connection is lost? Is it the MongoDB node driver, Mongoose, or the customer?

What seems to be happening here is that the MongoDB client that connect-mongo is using loses connection to the database at service startup, and for some reason never reconnects.

To answer your questions, I'm using connect-mongo 4.6.0 and Mongoose v6. They both use MongoDB node driver v4 under the hood.

**Comment by vkarpov15** [comment]
MongoDB Node driver is responsible for reconnecting to the database if connection is lost. Specifically, the MongoDB Node driver has an internal process known as _server selection_, where every time a new operation comes in, the driver will attempt to find a MongoDB server that can handle that operation for up to `serverSelectionTimeoutMS` (30000 by default).

What's the output of `npm list | grep "mongo"` in your project?
