### ISSUE TITLE
Model.bulkWrite() hangs forever when run on an empty list and ordered: false

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#13664]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

18.14.0

### MongoDB server version

6.0.5

### Description

Running `Model.bulkWrite([], {ordered: false})` hangs forever. This is broken on 7.4.1 and 6.11.4. It works correctly on 6.8.4.

Scanning the changelog, I suspect the issue is https://github.com/Automattic/mongoose/pull/13218, but I did not look too closely.

### Steps to Reproduce

https://github.com/JavaScriptBach/test-mongoose-bulkwrite/tree/main

### Expected Behavior

The call completes and returns.

**Comment by JonathanSun** [comment]
The reproduction link doesn't work for me, by the way (gives 404).

**Comment by JavaScriptBach** [comment]
Fixed now. (I accidentally made the repo private)

**Comment by IslandRhythms** [comment]
```javascript

const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.bulkWrite([], {ordered: false});
  console.log('done');
}

run();
```

**Comment by JavaScriptBach** [comment]
@vkarpov15 would you be willing to backport this fix onto Mongoose 6 as well? It would be very much appreciated!

**Comment by JavaScriptBach** [comment]
https://github.com/Automattic/mongoose/pull/13701

**Comment by JavaScriptBach** [comment]
@vkarpov15 thanks. 6.11.6 no longer hangs forever, but it makes `Model.bulkWrite([])` throw an error, whereas before it used to just silently continue. This is arguably a backwards incompatible change depending on what the documented behavior is. Wanted to flag to you so you're aware
