### ISSUE TITLE
Typescript logic to avoid null as a result for model.findOne

### ISSUE THREAD

**Issue by k2helix** [Automattic/mongoose#13673]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.4.1

### Node.js version

18.16.1

### MongoDB version

Latest

### Operating system

None

### Issue

Hi, I have been using Mongoose v5 for a long time and now I've started to migrate to Mongoose 7. I'm following the official guide which recommends to migrate to v6 first and then to 7, but I'm having some issues with Typescript that did not happen on v5.

When I call `model.findOne()` now, it can return null, which makes sense, but this did not happen on Mongoose 5. This is fine for most cases when you are not sure if there'll be any document at all. However, it does not make sense if my program does different checks before calling the method (findOne) that Typescript says it can be null.

For instance, let's say I have two documents that are created at the same time but in different models with different schemas:
```
// Global
interface GlobalUser {
	id: string;
	name: string;
	avatar: string;
}

const SchemaGlobalUser = new mongoose.Schema<GlobalUser>({
	id: String,
	name: String,
	avatar: String
});

const ModelGlobalUser = mongoose.model<GlobalUser>('Global', SchemaGlobalUser);

// Local (copying the interface and schema for a better explanation)
interface LocalUser {
	id: string;
	name: string;
	avatar: string;
}

const SchemaLocalUser = new mongoose.Schema<LocalUser>({
	id: String,
	name: String,
	avatar: String
});

const ModelLocalUser = mongoose.model<LocalUser>('Local', SchemaLocalUser);
```

And I create the documents at the same time (with different data):
```
const newGlobalModel = new ModelGlobalUser({
	id: user.id,
	name: user.username,
	avatar: user.avatar
});

const newLocalModel = new ModelLocalUser({
	id: user.id,
	name: user.localName,
	avatar: user.localAvatar
});

await newGlobalModel.save();
await newLocalModel.save();
```

Then if I call `ModelGlobalUser.findOne({id: user.id})` and it exists, `ModelLocalUser.findOne({id: user.id})` cannot be null. Same thing should happen if I call them in different files or functions (for example, do something -> first findOne (global) -> call another function where the second findOne (local) is done). Nevertheless, Typescript always says it can be null.

As said previously, this did not happen on Mongoose 5, where Typescript never said it could be null. Is there any way to return to that old behaviour by setting an option when creating the model or something? I know it's pretty impossible for Typescript to recognise when it can or cannot be null, but maybe a way to tell Typescript that some models cannot return null documents could solve it (basically a way to ignore that findOne can return no documents).

**Comment by vkarpov15** [comment]
Try `await ModelLocalUser.findOne({id: user.id}).orFail()`, that will make the result non-nullable. Does that help?

**Comment by k2helix** [comment]
> Try `await ModelLocalUser.findOne({id: user.id}).orFail()`, that will make the result non-nullable. Does that help?

Yup, it helps. Do you know if there is a way to use `orFail` for a whole model so I do not have to add it after every `findOne`? Because that way there's no much difference between doing that and adding a `!` after it.

**Comment by vkarpov15** [comment]
Not with TypeScript unfortunately. You could write middleware to add `orFail()` to every query operation, but that wouldn't help TypeScript infer that the result is non-nullable. You're better off just using `orFail()`.

**Comment by vermaslal** [comment]
I had same issue on @nestjs/mongoose . I found adding compiler option as below works

```
{
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitAny": true,
    ...
  }
}
```
