### ISSUE TITLE
SchemaDefinitionProperty `type` not compatible when using SchemaType Getters

### ISSUE THREAD

**Issue by kaulshashank** [Automattic/mongoose#13676]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.x.x

### Node.js version

18.x

### MongoDB version

6.x

### Operating system

Linux

### Issue

I'm trying to make all `ObjectId` fields into strings using `SchemaType.get()` introduced in v5.4. 

My schemas are using the `EnforcedDocType` generic argument for type-safety, so I get the following error when setting `type` to `Schema.Types.ObjectId` in any of my schemas where the `ObjectId` field is changed to `string`.

```
Type '{ type: typeof mongoose.Schema.Types.ObjectId; required: true; }' is not assignable to type 'SchemaDefinitionProperty<string> | undefined'.
  Types of property 'type' are incompatible.
    Type 'typeof ObjectId' is not assignable to type 'typeof Mixed | StringSchemaDefinition | undefined'.
      Type 'typeof ObjectId' is not assignable to type 'typeof Mixed | StringConstructor | typeof String'.
        Type 'typeof ObjectId' is not assignable to type 'typeof Mixed'.
          Types of property 'schemaName' are incompatible.
            Type '"ObjectId"' is not assignable to type '"Mixed"'.
```

Here's sample code:

```
import mongoose from "mongoose";

mongoose.Schema.ObjectId.get((v) => v.toString());

interface Test {
    testId: string;
}

const testSchema = new mongoose.Schema<Test>({
	testId: {
		type: mongoose.Schema.Types.ObjectId,
		required: true,
	},
});
```

I need `Test['testId']` to remain string so that the rest of my app code works as expected and I don't want to maintain two separate types, one for the schema and one for the app.

I'm not completely clear on whether I have to set `type` for `testId` to `String` or `ObjectId`. I presume it's `ObjectId` because it's still that in the database and I need any strings passed to be changed to `ObjectId`s.

Any help is much appreciated!

**Comment by vkarpov15** [comment]
The key point is that Mongoose's types internally store 2 distinct types for models and schemas: the raw document type, which represents what the raw document stored in MongoDB looks like; and the hydrated document type, which is what the result of `await MyModel.findOne()` looks like.

Your code, as written, is setting the raw document type to have `testId: string`, which isn't what you want because the document will have `testId` as an ObjectId in MongoDB. You need to overwrite Mongoose's default hydrated document type as follows. This approach unfortunately requires a huge amount of generics because of how our automatic type inference works, but it gets the job done.

```ts
import mongoose from "mongoose";

mongoose.Schema.ObjectId.get((v) => v.toString());

interface Test {
    testId: mongoose.Types.ObjectId;
}

type TestHydratedType = mongoose.HydratedDocument<{ testId: string }>;

type TestModelType = mongoose.Model<
  Test,
  {},
  {},
  {},
  TestHydratedType
>;

const testSchema = new mongoose.Schema<
  Test,
  TestModelType,
  {},
  {},
  {},
  {},
  mongoose.DefaultSchemaOptions,
  Test,
  TestHydratedType
>({
  testId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
  },
});

const TestModel = mongoose.model<Test, TestModelType>('Test', testSchema);

const doc = new TestModel({ testId: 'foo' });
const str: string = doc.testId;

async function foo() {
  // Keep in mind that, if you use `lean()`, getters don't run by default
  const doc2 = await TestModel.findOne().orFail().lean();
  const oid: mongoose.Types.ObjectId = doc2.testId;
}
```

**Comment by kaulshashank** [comment]
I don't know if this will help anyone but I made a little helper for the comment above:

```
import {
	DefaultSchemaOptions,
	HydratedDocument,
	Model,
	Schema,
	SchemaDefinition,
	SchemaDefinitionType,
	SchemaOptions,
	model,
} from 'mongoose';

export function TypedModel<
	EnforcedSchemaType extends Record<string, any> = any,
	HydratedDocumentType = EnforcedSchemaType,
	HydratedType = HydratedDocument<HydratedDocumentType>,
	ModelType = Model<EnforcedSchemaType, {}, {}, {}, HydratedType>,
>(
	collectionName: string,
	schemaDefinition: SchemaDefinition<
		SchemaDefinitionType<EnforcedSchemaType>,
		EnforcedSchemaType
	>,
	schemaOptions: SchemaOptions<
		EnforcedSchemaType,
		{},
		{},
		{},
		{},
		HydratedType
	>,
) {
	const schema = new Schema<
		EnforcedSchemaType,
		ModelType,
		{},
		{},
		{},
		{},
		DefaultSchemaOptions,
		EnforcedSchemaType,
		HydratedType
	>(schemaDefinition, schemaOptions);
	return model<EnforcedSchemaType, ModelType>(collectionName, schema);
}
```

```
export const Example = z.object({
	_id: ObjectId,
	userId: ObjectId,
});
export type Example = z.infer<typeof Example>;

export const ExampleHydrated = z.object({
	_id: z.string(),
	userId: z.string(),
	createdAt: z.coerce.date(),
});
export type ExampleHydrated = z.infer<typeof ExampleHydrated>;

export const ExampleModel = TypedModel<Example, ExampleHydrated>(
	'examples',
	{
		userId: {
			type: mongoose.Schema.Types.ObjectId,
			required: true,
		},
	},
	{ timestamps: { createdAt: true } },
);
```

Second argument to `TypedModel` is not required, it will default to the first. Which implies default behavior if you are not doing special hydration things.
