### ISSUE TITLE
(node:178) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.  (Use `node --trace-deprecation ...` to show where the warning was created) in mongoose npm version 5.13.20

### ISSUE THREAD

**Issue by Nandhakumar-nk** [Automattic/mongoose#13675]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.13.20

### Node.js version

18.15.0

### MongoDB server version

4.2.8

### Description

During my backend application start, i get this above warning

### Steps to Reproduce

when index.js of my node.js featherjs application start, trying to mongoose.connect()

**Comment by vkarpov15** [comment]
Like the warning says, remove `returnOriginal`, use `returnDocument: 'before'` or `returnDocument: 'after'` instead.

**Comment by Nandhakumar-nk** [comment]
I didn't use findOneAndUpdate method in my application

**Comment by vkarpov15** [comment]
Can you please post the stack trace that is outputted if you run using `node --trace-deprecation`?

**Comment by Nandhakumar-nk** [comment]
api_1          | (node:597) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
api_1          | (Use `node --trace-deprecation ...` to show where the warning was created)

Traced deprecation warning
api_1          | DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
api_1          |     at emitProcessWarning (/project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:547:15)
api_1          |     at /project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:601:9
api_1          |     at Array.forEach (<anonymous>)
api_1          |     at Collection.deprecated [as findOneAndUpdate] (/project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:594:30)
api_1          |     at NativeCollection.<computed> [as findOneAndUpdate] (/project-name/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:244:33)
api_1          |     at module.exports [as _findAndLockNextJob] (/project-name/node_modules/agenda/lib/agenda/find-and-lock-next-job.js:66:43)
api_1          |     at jobQueueFilling (/project-name/node_modules/agenda/lib/utils/process-jobs.js:166:30)
api_1          |     at module.exports (/project-name/node_modules/agenda/lib/utils/process-jobs.js:32:9)
api_1          |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by Nandhakumar-nk** [comment]
When executing node --trace-deprecation src/index.js

api_1          | (node:20) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
api_1          |     at emitProcessWarning (/project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:547:15)
api_1          |     at /project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:601:9
api_1          |     at Array.forEach (<anonymous>)
api_1          |     at Collection.deprecated [as findOneAndUpdate] (/project-name/node_modules/mongoose/node_modules/mongodb/lib/utils.js:594:30)
api_1          |     at NativeCollection.<computed> [as findOneAndUpdate] (/project-name/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:244:33)
api_1          |     at module.exports [as _findAndLockNextJob] (/project-name/node_modules/agenda/lib/agenda/find-and-lock-next-job.js:66:43)
api_1          |     at jobQueueFilling (/project-name/node_modules/agenda/lib/utils/process-jobs.js:166:30)
api_1          |     at module.exports (/project-name/node_modules/agenda/lib/utils/process-jobs.js:32:9)

**Comment by Nandhakumar-nk** [comment]
sorry, i found the issue ocuured inside 'agenda' package, it calls findOneAndUpdate with [returnOriginal]  option inside the agenda package

i updated the 'agenda'  package to latest version, now the deprecationWarning disappeared

Thanks @vkarpov15 for showing interest on this.
