### ISSUE TITLE
Problem sort by date and limit

### ISSUE THREAD

**Issue by dervalp** [Automattic/mongoose#1367]
I have a weird behavior or maybe I completely miss something evident.

I am trying to retrieve the last "2" articles with this query:

```javascript
var PAGESIZING = 2;

post.find({created : {$lt: new Date() }, geo: { $nearSphere: city.geo, $maxDistance: RADIUSCONSTANT }, published: true })
            .sort({created: -1})
            .limit(PAGESIZING)
            .populate("author")
            .exec(function (err, docs) {
              
              console.log(docs.length);
     });
```
It always skips the newest article. If I change the PAGESIZING to 3, I get it.

I really do not know what I am doing wrong, so if someone has an idea, it would be great! :)

EDIT: I also realize if I set the PAGESIZING to 1, it skips the first and second newest articles. If PAGESIZING > 2, everything works perfectly.

**Comment by letsgolesco** [comment]
I recently had this same issue on v3.8.26 actually. Not sure what kind of support you guys are giving 3.x any more, but this could be happening in 4.x as well.

To sum up my situation, I have an `events` collection and an `rsvps` collection. Events can have an `rsvp_limit` attribute. Once that amount of RSVPs have been submitted, new RSVPs are tagged as waitlisted with a boolean called `waitlist`.

The Event schema looks something like this:
```javascript
{
    title: String,
    location: String,
    rsvp_limit: Number,
    created_at: {
        type: Date,
        default: Date.now,
        index: true
    }
}
```

And the RSVP schema looks something like this:
```javascript
{
    event: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Event',
        index: true,
        required: true
    },
    account: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Account',
        index: true,
        required: true
    },
    created_at: {
        type: Date,
        default: Date.now,
        index: true
    },
    waitlist: {
        type: Boolean,
        default: false
    }
}
```

My issue occurs when an event creator wants to change their `rsvp_limit`. I want to find all the RSVPs that need to have their `waitlist` attribute changed, using mongoose like this:

```javascript
var differential = newRsvpLimit - oldRsvpLimit;
var newWaitlistValue = differential < 0;

RSVP
    .find({
        event: event._id,
        waitlist: !newWaitlistValue
    })
    .sort({ created_at: newWaitlistValue ? 'desc' : 'asc' })
    .limit(Math.abs(differential))
    .exec(function (error, rsvps) {
        // for each rsvps, set `rsvp.waitlist` & save
    })
```

When I don't include `.limit`, the sort occurs properly every time. When I do include `.limit` however, the sort seems to go out the window. They might be in their "natural" order, I'm not sure.

**Comment by vkarpov15** [comment]
Hmm @letsgolesco I can't repro, the below simple example gives the correct behavior:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh1367');

var UserSchema = new mongoose.Schema({
  name: String
});

var User = mongoose.model('user', UserSchema);

User.remove({}, function() {
  User.create({ name: 'A' }, { name: 'C' }, { name: 'B' }, function(err) {
    User.find({}).sort({ name: 'asc' }).limit(2).exec(function(error, docs) {
      console.log(util.inspect(docs));
    });
  });
});
```

```
Mongoose: users.remove({}) {}  
Mongoose: users.insert({ name: 'A', _id: ObjectId("5550bfe424736e7918efbda4"), __v: 0 }) {}  
Mongoose: users.insert({ name: 'C', _id: ObjectId("5550bfe424736e7918efbda5"), __v: 0 }) {}  
Mongoose: users.insert({ name: 'B', _id: ObjectId("5550bfe424736e7918efbda6"), __v: 0 }) {}  
Mongoose: users.find({}) { sort: { name: 1 }, limit: 0, fields: undefined }  
[ { __v: 0, name: 'A', _id: 5550bfe424736e7918efbda4 },
  { __v: 0, name: 'B', _id: 5550bfe424736e7918efbda6 },
  { __v: 0, name: 'C', _id: 5550bfe424736e7918efbda5 } ]
```

Can you enable mongoose debug mode `require('mongoose').set('debug', true);` and show me the query that's getting sent?

**Comment by letsgolesco** [comment]
Hey @vkarpov15 thanks for getting back to me. Not sure if it's something you did or something I did, but the next day I upgraded to 3.8.27 and the behavior was fine. Sorry for the false alarm!
