### ISSUE TITLE
get new doc on post.save

### ISSUE THREAD

**Issue by mbenfriha** [Automattic/mongoose#13681]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.4.1

### Node.js version

18.15.0

### MongoDB version

5.7.0

### Operating system

None

### Issue

Hello, I am currently developing a plugin, and during post.save I cannot retrieve the new document, I always have the version before the update was made, how can I do that?

**Comment by Shaky-Sahil** [comment]
Can you provide the code sample where you are updating the post?

If I understand correctly you want mongoose to return the updated post document when updating. This can be done by setting the 'new' option to true when updating.

`PostModel.findByIdAndUpdate(postId,<updated post body>, { new: true });`

[docs for reference](https://mongoosejs.com/docs/tutorials/findoneandupdate.html#:~:text=As%20the%20name%20implies%2C%20findOneAndUpdate,was%20before%20update%20was%20applied.&text=You%20should%20set%20the%20new,document%20after%20update%20was%20applied.)

**Comment by vkarpov15** [comment]
Mongoose's `save()` uses `updateOne()` under the hood, so it doesn't get any changes that where applied between when you loaded the document and when you saved the document. For alternatives, you can use `findOneAndUpdate()`, or you can use `findOne()` in a `post('save')` hook.
