### ISSUE TITLE
In 7.4.2 "$in needs an array" for a simple $in query that worked Previously

### ISSUE THREAD

**Issue by jaredwa** [Automattic/mongoose#13709]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.2

### Node.js version

20.5.0

### MongoDB server version

5x, on Hosted Atlas

### Description

Banging my head for a day - I had some old code that ran a simple $in query that has worked forever. Updated to 7.4.2 and started getting the error:

$in needs an array

Tried a lot of ways to enforce arrays (Array.fromArray, toArray, even stringifying and parsing to force type) - but it WAS an array and of course it had worked before. 

Broadly, the code was : 

{handle: {$in: ["handleA", "handleB"]}}

I then tried to just cheat and use an or query:

{$or: [{handle: "handleA}, {handle: "handleB}]

This also failed, but this time with no error. 

*********

I had made a bunch of updates, Node, Next etc. So after just so many hours I reverted to 6.11.5... and it worked immediately. 

Please take a look... but also please don't give me any advice that doesn't start with "I get that the exact same code works on another version" because no one likes that. 

Thanks!

### Steps to Reproduce

For me, just any $in query 

### Expected Behavior

7.4 should work like 6.11, and more to the point, it should pass through to Mongo and just work.

ALSO NOTE - that error is non-standard. Made searching for solutions harder.

**Comment by vkarpov15** [comment]
The following script executes without error, please modify the following script to demonstrate your issue

```javascript
'use strict';

const mongoose = require('mongoose');

run();

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const schema = new mongoose.Schema({ name: String });
  const Test = mongoose.model('Test', schema);
  await Test.findOne({ name: { $in: ['a', 'b'] } });
  console.log('Done');
  process.exit(0);
}
```
