### ISSUE TITLE
model.create ignores id property

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#13700]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.5

### Node.js version

20.x

### MongoDB server version

5.x

### Typescript version (if applicable)

4.8.4

### Description

Not sure if that's by design, but this doesn't work - mongoose generates an ID of its own, and overrides my custom ID

```
const id = ...;
model.create({id, name: "foo")
```

while this works:

```
const id = ...;
model.create({_id: id, name: "foo")
```

### Steps to Reproduce

See snippet above

### Expected Behavior

I would have expected that the `id` field would be used for inserts as well, if set.

**Comment by MohOraby** [comment]
Can you show your schema? maybe you didn't declare `id` field in your schema so it gets ignored when creating

**Comment by MohOraby** [comment]
Can you show your schema? maybe you didn't declare id field in your schema so it gets ignored when creating

**Comment by hardcodet** [comment]
Hi there!

Ah ok, I indeed haven't declared an `id` field in my schema - so far mongoose has automatically done the mapping from `_id` to `id` automatically. Since this is the first time that I want to create IDs myself, that was never an issue.

Thanks,
Philipp

**Comment by MohOraby** [comment]
What do you mean done the mapping? can you provide an example of when `id` was created by default? `id` is not added by default, meanwhile `_id` is the default primary key

**Comment by vkarpov15** [comment]
@hardcodet I believe we added support for this in 7.4.0 with #13517.

**Comment by hardcodet** [comment]
Awesome, thanks! We'll upgrade soon anyway :)

**Comment by hardcodet** [comment]
Awesome, thanks! We'll upgrade soon anyway :)
