### ISSUE TITLE
Import error when using an inferred data tape

### ISSUE THREAD

**Issue by daniel-ortiz-yepes** [Automattic/mongoose#13710]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.3

### Node.js version

18.16.0

### MongoDB version

6

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10)

Win10

### Issue

Hello Mongoose Team,

I am trying to create a simple model derived from a Schema and an auto inferred type. To this end I am following the example code from the ["schemas in typeScript"](https://mongoosejs.com/docs/6.x/docs/typescript/schemas.html) page. 

I am using a very similar piece of code, but the IDE is complaining about having problems with the import of InferSchemaType
```import { Schema,InferSchemaType  } from 'mongoose';

import getTmtAtlasModel from "apps/tmt/server/adapters/realImplementations/tmsAtlasReal";

const testSchema = new Schema({
    info: String,
});

type TestTmt = InferSchemaType<typeof testSchema>;
```

The compiler says "Cannot resolve symbol 'InferSchemaType'"
![image](https://github.com/Automattic/mongoose/assets/141817982/5fb6902d-18b3-4531-a049-660a2cf8786e)

I see that there is a definition of  InferSchemaType:

``` type InferSchemaType<TSchema> = IfAny<TSchema, any, ObtainSchemaGeneric<TSchema, 'DocType'>>;```

but this definition is not being exported. What can I do in this case?

**Comment by vkarpov15** [comment]
Does TypeScript fail to compile? Or is this an IDE issue?

**Comment by daniel-ortiz-yepes** [comment]
Hi Valeri, it is a TypeScript thing. I tried it with VSCode as well and I get an error

![image](https://github.com/Automattic/mongoose/assets/141817982/e213f770-9edf-4b17-bdd8-676d75abcdb6)

**Comment by daniel-ortiz-yepes** [comment]
Hi Valeri,

good question. I would say this is an IDE issue with Intellij, because I tried the same code with VSCode and I do not see the error. 

But still is there any reason why InferSchemaType is not exported?

**Comment by vkarpov15** [comment]
Opened a PR #13737 to see. I don't have a good reason to not export `InferSchemaType`.
