### ISSUE TITLE
How do I define a nested schema for itself

### ISSUE THREAD

**Issue by f840415070** [Automattic/mongoose#13717]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.2.3

### Node.js version

16.14.0

### MongoDB version

4.4.0

### Operating system

Windows

### Issue

A nested subdocument structure. Like this:
```js
const DirectoryItemSchema = new mongoose.Schema({
  key: String,
  title: String,
  children: [DirectoryItemSchema]
})
```

**Comment by f840415070** [comment]
Resolved!!
```js
const FolderSchema = mongoose.Schema({
    name: { type: String, required: true },
    type: { type: String, enum: ['file', 'directory'],
    children: [ this ]
})
```

**Comment by vkarpov15** [comment]
No, that's incorrect. At the top level of a script, `this` refers to the Node.js global object, so in Mongoose 6 you're getting something equivalent to this:

```javascript
const itemSchema = new mongoose.Schema({
  name: String,
  items: {
    type: ['Mixed'],
    default: undefined
  }
}, { _id: false })
```

You're just making `items` an array of Mixed, AKA any.

Use the following instead:

```javascript
const itemSchema = new mongoose.Schema({
  name: String
}, { _id: false });

itemSchema.add({
  items: {
    type: [itemSchema],
    default: undefined
  }
});
```
