### ISSUE TITLE
Does the Mongoose own `transaction()` method require an explicit call to `session.endSession()`?

### ISSUE THREAD

**Issue by electrotype** [Automattic/mongoose#13719]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.11.3

### Node.js version

16.X

### MongoDB version

5.0.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Manjaro

### Issue

There is something that is not 100% clear for me in the [transactions documentation](https://mongoosejs.com/docs/5.x/docs/transactions.html):

When using the `transaction()` method provided by Mongoose (the wrapper around the native `withTransaction()` method), do we have to call `session.endSession()` somewhere, by ourself? Or is it called for us? I'm pretty sure `transaction()` handles the commit/rollback, but what about  `endSession()`?

**Comment by vkarpov15** [comment]
`transaction()` and `withTransaction()` both handle the full transaction and session lifecycle. So you don't have to commit or abort the transaction yourself, and you do not need to call `endSession()`.
