### ISSUE TITLE
Mongoose intellisense functions not shown when pressing ctrl+space

### ISSUE THREAD

**Issue by Joe-A11-RM** [Automattic/mongoose#13724]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.4.2

### Node.js version

16.16.0

### MongoDB version

6.0.1

### Operating system

Windows

### Issue

Hello 
Am making a basic crud project when I want to make like model.findonbyId by pressing ctrl+space functions of mongoose is not shown and i have to write it manually so can any one help me in this problem
![image](https://github.com/Automattic/mongoose/assets/109547873/94bca2a1-34ad-46ce-9592-c20466dbfc88)

**Comment by vkarpov15** [comment]
How is ProductModel defined?

**Comment by Joe-A11-RM** [comment]
> 

> The first line in the screenshot is the definition of ProductModel

**Comment by Joe-A11-RM** [comment]
> I don't mean the `require()` statement that's loading the model. I mean what are the contents of the `../Models/products.model` file?

![image](https://github.com/Automattic/mongoose/assets/109547873/079b59f4-dd1e-42a8-b744-f7a6120b06c0)
![image](https://github.com/Automattic/mongoose/assets/109547873/33ea814c-7fd4-440b-99f1-8e01f767bf44)

**Comment by vkarpov15** [comment]
What IDE are you using? Also, please stop pasting screenshots of your code. Just copy the code please.
