### ISSUE TITLE
Could not connect to any servers in your MongoDB Atlas cluster, help me pls!

### ISSUE THREAD

**Issue by Salimov-dev** [Automattic/mongoose#13727]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.4.0

### Node.js version

19.7.0

### MongoDB version

5.7.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

Добрый день!

Сегодня перестал подключаться в базе! 
Получаю ошибку: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
[nodemon] app crashed - waiting for file changes before starting...

Пробовал все указанные ранее советы, пробовал Node 2.1.12 устанавливать, пробовал зависимости удалять, ПК перезагружать, роутер и прочее. Помогите, пожалуйста.

**Comment by vkarpov15** [comment]
ты можешь подключитьcя c mongosh или compass? видишь какие-то проблемы в Atlas UI?
