### ISSUE TITLE
Populate virtuals doesn't work unless lean:true in the query

### ISSUE THREAD

**Issue by MuAladdinIbrahim** [Automattic/mongoose#13731]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.1

### Node.js version

16.13.2

### MongoDB server version

4.4.2

### Description

My proplem after upgrading to version 7 that all virtuals that was working fine are not returned in findOneAndUpdate and findOne, findAll queries except that lean is true in the query.

I know the normal is the opposite, I need to install and use a package to make populating virtuals works with the lean. I face the opposite behavior. 

### Steps to Reproduce

```
    const updatedRequest = await request.findOneAndUpdate(
        { request_id: requestid},
        updates,
        { new: true, upsert: false, lean: true, populate: ["x"] }
      )
```
x is returned despite lean: true is here

my proplem if lean:false, x is not returned!

**Comment by SadiqOnGithub** [comment]
are you trying to read `updatedRequest.x` and it returning `undefined`?

**Comment by MuAladdinIbrahim** [comment]
> are you trying to read `updatedRequest.x` and it returning `undefined`?

In my case it returns an empty array if lean is false.

**Comment by SadiqOnGithub** [comment]
can you tell me what `console.log(updatedRequest)` is printing in the console?

**Comment by vkarpov15** [comment]
What do your schemas look like? Without a more complete example, it is unlikely we'll be able to repro this.
