### ISSUE TITLE
post() callback function for deleteOne doesn't give the document object

### ISSUE THREAD

**Issue by amazinglySK** [Automattic/mongoose#13730]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

7.0.4

### Node.js version

18.2

### MongoDB version

6.0

### Operating system

Windows

### Issue

```javascript
ClubSchema.post('deleteOne', {document : true, query : true}, function (doc) {
	console.log('Running');
	console.log(doc);
	let club_id = doc._id;
	console.log(club_id);
});
```

Output (Whenever the `deleteOne()` function is called)  : 
```
Running
{acknowledged: true, deletedCount: 1}
undefined
```

I tried all variations and tweaking with the function - with and without the options parameters, checking out the second parameter that's passed into the callback function, etc. - but to no avail. I even tried the `this` keyword, but again it's `undefined` as well. 

The following was the callback function definition in the package files : 
```javascript
type PostMiddlewareFunction<ThisType = any, ResType = any> = (this: ThisType, res: ResType, next: CallbackWithoutResultAndOptionalError) => void | Promise<void>;
```
And the example in the documentation gives the following example : 
```javascript
schema.post('deleteOne', function(doc) {
  console.log('%s has been deleted', doc._id);
});
```
I tried replicating this same example, but the doc parameter passed into the function seems to be different from the one here. 

Anything that I'm missing here 🤷?

**Comment by vkarpov15** [comment]
Try document: true, query: false? That should prevent this middleware from firing on deleteOne queries, just deleteOne() on document calls
