### ISSUE TITLE
New type to manage large files 

### ISSUE THREAD

**Issue by kidanekalM** [Automattic/mongoose#13743]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I have been searching for a solution that simplifies the crud of large binary data to directory and saving the url to database. and I believe that it would be simpler to add a new type to the schema of mongoose and it will save to a directory or other location specified by the schema and save the url to mongodb as string very similar to sqlServer filestream

### Motivation

It decreases database efficiency and cost to save large files in database. But it is a tedious work to save to a different location and save the url to the database and it is also an error prone method

### Example

lets say the new type is called  ``FIle``
``
const exampleSchema = new mongoose.Schema({
    title: String,
    pic: File,
    desc: String
})
 exampleSchema.addOne({
title:"title",
pic:"Location of the file",
desc"description"
})
``

**Comment by vkarpov15** [comment]
Sounds like [GridFS](https://www.mongodb.com/docs/manual/core/gridfs/)?
