### ISSUE TITLE
Getter firing every time on array property

### ISSUE THREAD

**Issue by dantenol** [Automattic/mongoose#13748]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.3

### Node.js version

18.17

### MongoDB server version

6.0.6

### Typescript version (if applicable)

5.1.6

### Description

While using getters on a schema with type array, the getter function is called every time the value is accessed. The expected behavior should be run the function only once.

Given this getter function on user.hobbies[]
```ts
const removeSufix = (name: string) => {
  return name.slice(0, -6);
};
```

this is the current result of two console.logs in sequence
```ts
  console.log(user.hobbies); // ["swimming", "football"] => correct value
  console.log(user.hobbies); // ["sw", "fo"] => runs getter again
```

### Steps to Reproduce

https://github.com/dantenol/mongoose-array-getters-demo

### Expected Behavior

Run the getter function only once.

**Comment by Uzlopak** [comment]
Well that it gets called everytime makes sense. That it slices everytime not, because strings as all primitives are immutable.

**Comment by dantenol** [comment]
type is always `string`

therefore, changing to the suggested code to force a string had the same results
