### ISSUE TITLE
replaceOne missing BSONType results in Type mismatch error

### ISSUE THREAD

**Issue by allincodes** [Automattic/mongoose#13740]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.4

### Node.js version

16.18.0

### MongoDB server version

5.6.0

### Typescript version (if applicable)

4.8.x

### Description

I'm using mongoose-double to save int as double, and found replaceOne doesn't work, but updateOne is ok. In the source code of [lib/query.js](https://github.com/Automattic/mongoose/blob/7.3/lib/query.js) there are two branch for update and replace, so maybe here is a bug:
<img width="705" alt="image" src="https://github.com/Automattic/mongoose/assets/53214446/5621325c-8eac-48cd-bab1-2463d3408962">

replaceOne goes line 3851
updateOne goes line 3853

### Steps to Reproduce

1. Create a model including a double type
<img width="324" alt="image" src="https://github.com/Automattic/mongoose/assets/53214446/b0f88ab9-33e1-4665-b3a7-913e20a0d573">
</br>...
<img width="184" alt="image" src="https://github.com/Automattic/mongoose/assets/53214446/a4363b89-972b-4490-9af8-b0a432d531a2">

2. Call the model.replaceOne method with data
   {_id: '64d5adde87aeb29496a585e9', updatedTS: 1690356513, ... }

3. Got the error
<img width="325" alt="image" src="https://github.com/Automattic/mongoose/assets/53214446/98703b2d-0306-4dd4-8b47-6348999b02c6">

### Expected Behavior

Replace with new one successfully

**Comment by allincodes** [comment]
I try to modify the code as below the line 3850, and model.replaceOne works well, but i don't know if it is the right way
<img width="719" alt="image" src="https://github.com/Automattic/mongoose/assets/53214446/4bfe043b-f09c-4da5-93f1-c04f3a0873e8">

**Comment by IslandRhythms** [comment]
Modify the below script to demonstrate your issue

```javascript
const mongoose = require('mongoose');
require('mongoose-double')(mongoose);

const testSchema = new mongoose.Schema({
  double: mongoose.Schema.Types.Double
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.create({
    double: 123156486
  });

  await Test.replaceOne({ _id: doc._id}, { double: 1478523698 });

  console.log('done');
}

run();
```
