### ISSUE TITLE
Feature proposal: Populating an array containing Ids or null

### ISSUE THREAD

**Issue by jiayishen21** [Automattic/mongoose#13745]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I am proposing a way to populate an array of ids that aren't required. Currently, if an array that looks something like [id1, id2, null, id3] gets populated, the null gets deleted and has to be restored manually (if you want to restore it).

### Motivation

Restoring the nulls to an array is kind of tedious. From what I know (I may be wrong), you have to convert the populated item into JSON since you can't edit the populated array before this. You then have to compare the unpopulated array with the populated one and updated each element of the array that isn't null. Overall, kind of a tedious process.

You might wonder when someone would even use an array containing ids and nulls. I think there quite a few cases, one of them being something like the array needing to be length n. For example, a roster of 1-4 characters, where each character can be assigned to a specific position. I know you can avoid the need to use nulls by assigning each character a property called position, but I hope you get my point.

(This is my first issue post on GitHub, so please let me know if the motivation is a bit silly)

### Example

Let's say X is the name of a mongoose Model with a roster of Character, which have a name
```
const xSchema = new mongoose.Schema({
  roster: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Character',
    required: false,
  }],
})

const X = mongoose.model('X', xSchema)
```

Let's say a certain X has a roster of [null, id1, null]
```
const x = await X.findById(_id)
  .populateWithoutDelete('roster')

console.log(x)
```
The output of this console.log(x) should be something like: ```[null, { name: 'bob', null }]``` instead of ```[{name: 'bob'}]```, which is what would be generated if the normal ```.populate``` was used.

**Comment by vkarpov15** [comment]
Sounds like the `retainNullValues` option

```javascript
const x = await X.findById(_id)
  .populate({ path: 'roster', options: { retainNullValues: true } })

console.log(x)
```
