### ISSUE TITLE
Support string initialization for map in schema

### ISSUE THREAD

**Issue by dayo05** [Automattic/mongoose#13755]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

My project uses String for setting the type in schema of each keys like this:
```js
username: { type: 'string', required: true }
```

In case of map, I just tried this style of code:
```js
instance: {
  type: Schema.Types.Map,
  of: Schema.Types.Mixed,
  default: new Map<string, any>(),
}
```
This is working code. But if I use 'Map' instead of `Schema.Types.Map`, compiler aborts to compile.
```js
instance: {
  type: 'Map',
  of: 'Mixed',
  default: new Map<string, any>(),
}
```

So, is it able to allow with setting the map type with String?

**Comment by IslandRhythms** [comment]
```typescript
import * as mongoose from 'mongoose';

const testSchema = new mongoose.Schema({
  instance: {
    type: 'Map',
    of: 'Mixed',
    default: new Map<string, any>()
  }
})
```

**Comment by dayo05** [comment]
Sorry for late reply, I was so busy for some reasons...

It looks like my issue seems like typescript problem.

```
TS2322: Type
{     type: string;     of: typeof Schema.Types.ObjectId;     default: Map<string, ObjectId>; }
is not assignable to type
Map<string, ObjectId> | SchemaDefinitionProperty<Map<string, ObjectId>>
```
This is actual error message what I saw.
Because its just type error, it might be able to worked on javascript(not typescript).

I'll just make minimal project ASAP.

Thanks for focusing on this

**Comment by dayo05** [comment]
```ts
class Test {
  instance: Map<string, string>
  constructor() {
    this.instance = new Map<string, string>()
  }
}

const testSchema = new mongoose.Schema<Test>({
  instance: {
    type: 'Map',
    of: 'Mixed',
    default: new Map<string, string>()
  }
})
```

This is minimal reproduction script
