### ISSUE TITLE
Module import: Named export 'models' not found

### ISSUE THREAD

**Issue by RSamaium** [Automattic/mongoose#13752]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.3

### Node.js version

18.15.0

### MongoDB server version

6.0.5

### Typescript version (if applicable)

5.1.6

### Description

The type returns `models`, so Typescript accepts the import of `models`

https://github.com/Automattic/mongoose/blob/master/types/index.d.ts#L52

But after compilation:

```bash
import mongoose, { Schema, models, model } from "mongoose";
                           ^^^^^^
SyntaxError: Named export 'models' not found. The requested module 'mongoose' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mongoose';
const { Schema, models, model } = pkg;
```

### Steps to Reproduce

tsconfig.json
```json
{
"compilerOptions": {
    "target": "es2020",
    "module": "esnext",
  }
}
  ```

### Expected Behavior

Have `models` or other solution

**Comment by A7mooz** [comment]
I can reproduce in ESM

**Comment by vkarpov15** [comment]
@A7mooz can you please provide a project we can use to repro this issue? "I can repro" isn't very helpful when we've already said we're unable to repro.
