### ISSUE TITLE
How to catch error "Uncaught MongoNetworkError MongoNetworkError: failed to connect to server [localhost:27017] on first connect"

### ISSUE THREAD

**Issue by armanhi** [Automattic/mongoose#13754]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.11.15

### Node.js version

20.5.1

### MongoDB version

7

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

BirSur 11.7.4

### Issue

I'd like to know how I could catch the error below:

Uncaught MongoNetworkError MongoNetworkError: failed to connect to server [localhost:27017] on first connect

To be clear, I don't want to fix it, I want to know how to catch it in case it happens. I've tried the below and nothing works:

```
mongoose.connection.on("error", () => {
    console.log("unable to connect to database");
  });

mongoose.connection.on("error", err => {
    console.log("unable to connect to database");
  });

try {
    mongoose.connect(mongoUrl, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true } )
    .then(
        () => { /** ready to use. The `mongoose.connect()` promise resolves to undefined. */ },
    ).catch(err => {
        console.log(`MongoDB connection error. Please make sure MongoDB is running. ${err}`);
        // process.exit();
    });
} catch (err2) {
    const a = err2;
}
```

**Comment by vkarpov15** [comment]
I'm unable to repro. With Mongoose 5.11.15, running the above script gives me the following output:

```
$ node gh-13754.js 
MongoDB connection error. Please make sure MongoDB is running. MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
unable to connect to database
unable to connect to database
```

Can you please provide the stack trace from the error message?
