### ISSUE TITLE
Can only omit discriminator field if `_id` is also selected

### ISSUE THREAD

**Issue by cg-julian-taylor** [Automattic/mongoose#13760]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

18.6.1

### MongoDB server version

4.1.3

### Description

When using the mongoose.select() method I can only select to omit discriminator fields if `_id` is also selected for ommision.

For example:
mongoose.select('-_id -__t') removes the __t field.
mongoose.select('-__t') does not.

This has been attempted using both array and string notation.

this may be related to https://github.com/Automattic/mongoose/issues/13679

### Steps to Reproduce

1. call `mongoose.select(['-__t'])`
2. console.log the result to see that  `__t` is not removed from results.

### Expected Behavior

`__t` discriminator field should be removed via select method.

**Comment by cg-julian-taylor** [comment]
I don't know if this helps as its not a script as such, but here is an example of what type of code I'm trying to run:

`const userSchema = new mongoose.Schema({
  firstName: String
  lastName: String
});

const User = mongoose.model('User', userSchema);

const joeBloggsUser = new User({firstName: 'Joe', lastName: 'Bloggs'});

const users = await User.find().select(['-__t']);

console.log(users[0].__t === undefined);`

**Comment by IslandRhythms** [comment]
Modify the script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  firstName: String,
  lastName: String
});

const User = mongoose.model('User', userSchema);

const accountSchema = User.discriminator('account', new mongoose.Schema({ age: Number }, { discriminatorKey: 'kind' }));

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  const joeBloggsUser = await User.create({firstName: 'Joe', lastName: 'Bloggs'});

  const users = await User.find().select(['-__t']);

  console.log(users[0].__t === undefined, users[0].__t);
  const test = new accountSchema({ age: 2 });
  console.log(test.__t)
  await test.save();
  const res = await accountSchema.find().select(['-__t']);
  console.log(res[0].__t)
}

run();

```

**Comment by cg-julian-taylor** [comment]
Hi there, I've managed to replicate the issue. Please find enclosed a script to replicate the issue:

`const` mongoose = require('mongoose');

async function run(){
  const baseConfig = {
    discriminationKey: '_type',
    collection: 'users'
  };

  const NamesSchema = new mongoose.Schema({
    firstName:   { type: String },
    lastName:  { type: String },
    test: {type: String}
  });

  const User = mongoose.model('User', new mongoose.Schema({}, baseConfig));

  const NamesModel = User.discriminator('names', NamesSchema);

  await mongoose.connect('mongodb://localhost:27017');

  await mongoose.connection.dropDatabase();

  const joeBloggsUser = await NamesModel.create({firstName: 'Joe', lastName: 'Bloggs', test: '123'});

  const userNameResult = await NamesModel.findOne({})
    .select(['-__v', '-__t', '-test'])
    .lean();

  console.log(userNameResult.__t === undefined, userNameResult.__t, userNameResult.__v, userNameResult.test);
}

run();`

**Comment by vkarpov15** [comment]
As a workaround, use the following syntax:

```javascript
  const userNameResult = await NamesModel.findOne({})
    .select({ '__v': 0, '__t': 0, 'test': 0 })
    .lean();
```
