### ISSUE TITLE
_id and id in document are treated the same since 7.4.0

### ISSUE THREAD

**Issue by salos1982** [Automattic/mongoose#13762]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

18.x

### MongoDB server version

7.0

### Typescript version (if applicable)

5.0

### Description

When I try to insert object that contains id field it is transformed to _id field and then is trying to insert.
Deleting id field before insert helps.

### Steps to Reproduce

I have schema without **id** field. But when I try to insert new object with id field it is treated as string version of _id.
E.g. Schema 

```
export class A {
name: string;
}
```
if I try to insert object
```
{
  id: "existing _id of another object"
  name: "A"
}
```
I got E11000 duplicate key error collection
Mongoose 7.3.3 has no such error

### Expected Behavior

New object in inserted without error and id field will be ignored

**Comment by salos1982** [comment]
I would prefer to have option to disable such functionality.  I have a lot of code where I get objects with id field and then insert them to database. And very often there are ids of previous objects and it causes duplicate key errors.

**Comment by zeljkocurcic** [comment]
Please consider releasing a major version when doing something like this in the future and making sure it's marked as a breaking change.

**Comment by vkarpov15** [comment]
@zeljkocurcic we didn't see this as a breaking change when we released it, but in hindsight we definitely should have. We removed this id setter in Mongoose 8.

**Comment by tonynelson19** [comment]
Can the [Migrating from 6.x to 7.x migration guide](https://mongoosejs.com/docs/migrating_to_7.html) be updated to reference this breaking change?

**Comment by mete89** [comment]
Hey @vkarpov15 

The first doc doesn't include [id setter] section. You may want to update it as well. 
https://mongoosejs.com/docs/migrating_to_7.html
https://mongoosejs.com/docs/7.x/docs/migrating_to_7.html

Lastly, what is the suggested migration path from version 6 to avoid being affected by the ID setter change? Is there any option introduced to globally disable it in version 7?

**Comment by vkarpov15** [comment]
@mete89 the idsetter section was added in https://github.com/Automattic/mongoose/commit/da126f4d6c5f3fb5000c000efeb3d4e30b4ba5a6, we just need to merge that to master.

Do you rely on the `.id` property? if not, the easiest way would be to simply disable the `id` property for all documents by default:

```javascript
mongoose.set('id', false);
```

If you rely on the `.id` property, you can disable Mongoose's default `id` property and add your own as follows.

```javascript
mongoose.set('id', false);
mongoose.plugin(schema => {
  schema.virtual('id').get(function() { return this._id?.toString(); });
});
```

**Comment by mete89** [comment]
@vkarpov15 My models have an id field to represent ids in another context so I don't need any virtual here. I set them while creating my objects. So how can I migrate to 7 by disabling this unwanted feature? 

` 
    id: String,
`

**Comment by mete89** [comment]
I upgraded directly to 8.x.x to prevent this issue.

**Comment by vkarpov15** [comment]
@mete89 `schema.virtual('id').get(function() { return this._id.toString(); })`
