### ISSUE TITLE
How to catch MongoServerError thrown by the MongoDB Node.js driver in TypeScript?

### ISSUE THREAD

**Issue by showthesunli** [Automattic/mongoose#13768]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.1

### Node.js version

v18.14.0

### MongoDB version

6.0.6

### Operating system

Linux

### Issue

When I insert a value that violates a unique constraint, the MongoDB Node.js driver will throw a MongoServerError exception. I need to handle this exception in the catch block. However, Mongoose does not export MongoServerError, which makes it difficult for me to determine which class is the error  instance belongs to. 

Since I cannot import MongoServerError, I am unable to determine whether the error is an instance of MongoServerError. This will lead to a type-checking error in TypeScript.

Do I need to install the MongoDB driver in addition to mongoose, in order to import the MongoServerError class?
![image](https://github.com/Automattic/mongoose/assets/3203516/10a6d194-873a-44ae-9022-628110d9a595)
![image](https://github.com/Automattic/mongoose/assets/3203516/4e3ee355-6c18-4a83-8dcd-0d1aa9cbe9cf)

**Comment by maybesmurf** [comment]
![Screenshot 2023-08-22 222826](https://github.com/Automattic/mongoose/assets/68304628/d8049aef-51a8-45a5-ac3b-3cefd1f2463f)

**Comment by vkarpov15** [comment]
Try `mongoose.mongo.ServerSelectionError`? The following code seems to compile fine:

```ts
import mongoose from 'mongoose';

const err: mongoose.mongo.MongoServerError | null = null;
```
