### ISSUE TITLE
Can't make nested populate in new mongoose 3.6rc0

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#1377]
I have the following schemas:

```
var DocumentSchema = new Schema({
  title    : {type: String},
  emails   : [{type: ObjectId, ref: 'Emails'}]
});

var EmailSchema = new Schema({
  title    : {type: String},
  tags     : [{type: ObjectId, ref: 'Tags'}]
});

var TagSchema = new Schema({
  title    : {type: String}    
});
```

I want to find a document with populated 'emails' and tags. When I try this:

```
Document.findById(ObjectId('...'))
  populate('emails.tags')
  .exec(function (err, document) {

  });
```

I get the error: 

```
Caught exception: TypeError: Cannot call method 'path' of undefined
```

**Comment by JaKXz** [comment]
@aheckmann I've got the `callback` function returning the updated model object, which is great. However, in this context:

```js
var User = mongoose.model('User');
var Grade = mongoose.model('Grade');

User.findOne({ ... })
  .populate('array')
  .exec(function (err, user) {
    Grade.populate(user, {
      path: 'array.grades',
      select: 'name -_id'
    }, function (error, updatedUser) {
      //assuming no error,
      user = updatedUser; //how do I persist this?
    });
  });
```
since the callback is asynchronous, how do I get the user object returned from my `findOne` query to get the nested property data? It should look like:

```json
{
  "array" : ["grade one", "grade two"]
}
```

instead of the array of ObjectIds I get back from the basic `populate`? I'm using Mongoose 4.0.x

**Comment by vkarpov15** [comment]
@JaKXz what do you mean by persisting? You should be able to push/pull from the user.grades array.

**Comment by ezequielzacca** [comment]
As the metadata for population is present in the ref property, shouldnt the libary be able to automatically guess the correct model for population?

**Comment by vkarpov15** [comment]
I don't understand your question, please clarify

**Comment by gregballot** [comment]
I think he's asking if the field you are trying to use to populate is correctly defined the Model schema.

**Comment by usernamedoesntexist** [comment]
> @yangsu you are correct. Though there is another way. Either specify the model that should be used for population in the options to `User.populate` or use the `Phone` model directly:
> 
> ```js
> BlogPost.find({ tags: 'fun' }).lean().populate('author').exec(function (err, docs) {
>   assert.ifError(err);
> 
>   User.populate(docs, {
>     path: 'author.phone',
>     select: 'name',
>     model: Phone // <== We are populating phones so we need to use the correct model, not User
>   }, callback);
> 
>   // or use the model directly
> 
>   Phone.populate(docs, {
>     path: 'author.phone',
>     select: 'name',
>   }, callback);
> ```
> 
> This seems clunky. We should be able to do better with this in a future release. If the documents being populated are mongoose documents (opposed to plain objects) we could possibly use it's related schema to determine which Model to use. Won't work for plain objects of course.

thanks you
