### ISSUE TITLE
Model constructor best practices to avoid excessive memory usage

### ISSUE THREAD

**Issue by ilias-t** [Automattic/mongoose#13779]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.8.9

### Node.js version

16.20.0

### MongoDB version

4.4.3

### Operating system

None

### Issue

I'm trying to get a better understanding of best practices in using the `mongoose.model` constructor to avoid excessive memory consumption.

Generally I've seen projects define models up in module scope throughout an app. However based on a strict equality check of the following it looks like there might be more memory allocation than necessary if every module is not referencing the same model in memory.

For example I'm surprised that `mongoose.model('SomeModel') === mongoose.model('SomeModel')` not `true`, implying that we are allocating additional memory for every constructor.

Given mongoose is seemingly not internally maintaining some cache I was curious to understand the recommended patterns to use mongoose to avoid excessive memory consumption.

It appears that using a [connection](https://mongoosejs.com/docs/5.x/docs/api.html#connection_Connection-models) may be the solution? Thanks for the help!

**Comment by vkarpov15** [comment]
I'm surprised that `mongoose.model('SomeModel') === mongoose.model('SomeModel')` is not true. `mongoose.model('SomeModel')` is equivalent to accessing `mongoose.models['SomeModel']`, so you should be getting the same reference every time. Is there any way you can create a script that demonstrates what you're seeing?

**Comment by ilias-t** [comment]
Ah, you're right—I just tried repro'ing in an more minimal application and it work. Turns out that in I was unknowingly using a proxy to access the model, which explains this behavior. Thank and will close!
