### ISSUE TITLE
Regression? Fields named `id` cause problems. 

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13775]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.4

### Node.js version

16.19.1

### MongoDB server version

5

### Typescript version (if applicable)

4.8.3

### Description

# The issue

Put shortly, the following code does not compile with the latest Mongoose while it did with v6:

```typescript
import { InferSchemaType, Schema } from "mongoose";

export const treeSchema = new Schema({
    id: { type: String, required: true },
});

export interface ITree extends InferSchemaType<typeof treeSchema> {}
```

The error occurs at the very last line:

> TS2312: An interface can only extend an object type or intersection of object types with statically known members.

This code compiles fine:

- in Mongoose v6 (and I did not see any related breaking changes in the docs);
- if `ITree` is declared as a type and not an interface;
- if I remove/rename the `id` field.

My guess is that `InferSchemaType` is struggling to unambiguously infer the type of the `id` field.

# Additional observations

This gets weirder when subdocuments are involved. E.g. the following code compiles without any errors:

```typescript
import { InferSchemaType, Schema } from "mongoose";

const nodeSchema = new Schema({
    id: { type: String, required: true }
});

export const treeSchema = new Schema({
    node: { type: nodeSchema, required: true }
});

export interface ITree extends InferSchemaType<typeof treeSchema> {} // ok!
```

However, if I inspect the compilation output in a code editor, suddenly the error is back:

```typescript
import { InferSchemaType, Schema } from "mongoose";
export declare const treeSchema: Schema<any, import("mongoose").Model<any, any, any, any, any, any>, {}, {}, {}, {}, import("mongoose").DefaultSchemaOptions, {
    node: {
        id: string;
    } | (import("mongoose").Document<unknown, {}, {
        id: string;
    }> & {
        id: string;
    });
}, import("mongoose").Document<unknown, {}, {
    node: {
        id: string;
    } | (import("mongoose").Document<unknown, {}, {
        id: string;
    }> & {
        id: string;
    });
}> & {
    node: {
        id: string;
    } | (import("mongoose").Document<unknown, {}, {
        id: string;
    }> & {
        id: string;
    });
} & {
    _id: import("mongoose").Types.ObjectId;
}>;
export interface ITree extends InferSchemaType<typeof treeSchema> { // ERROR HERE!!!
}
```

This is relevant if I wish to distribute my code as a library (which is how I discovered this actually).

Also notice how cumbersome the compilation output looks! In v6 the same code would produce:

```typescript
import { InferSchemaType, Schema } from "mongoose";
export declare const treeSchema: Schema<any, import("mongoose").Model<any, any, any, any, any>, {}, {}, {}, {}, import("mongoose").DefaultSchemaOptions, {
    node: {
        id: string;
    };
}>;
export interface ITree extends InferSchemaType<typeof treeSchema> {
}
```

Whereas with v7, if the `id` field in the subdocument is renamed to `idX`, some different output is produced that is only 15 lines (compared to 27 if the `id` field is present):

```typescript
export declare const treeSchema: Schema<any, import("mongoose").Model<any, any, any, any, any, any>, {}, {}, {}, {}, import("mongoose").DefaultSchemaOptions, {
    node: {
        idX: string;
    };
}, import("mongoose").Document<unknown, {}, {
    node: {
        idX: string;
    };
}> & {
    node: {
        idX: string;
    };
} & {
    _id: import("mongoose").Types.ObjectId;
}>;
```

### Steps to Reproduce

See description.

### Expected Behavior

I guess I expect the code to compile and the compiled code to be compilable again (in the case with subdocuments).

I wonder if the compiled output can be simplified too. It gets _really_ ugly when subdocument arrays are used.

**Comment by vkarpov15** [comment]
One thing I noticed so far: the following code snippet compiles fine in TypeScript 5.x. It's just TypeScript 4.x that has trouble.

**Comment by vkarpov15** [comment]
Also, looks like this regression was introduced in 7.3.3, presumably with #13577. No other TypeScript changes in that release. So that's another workaround: use Mongoose `<= 7.3.2` for now.

FWIW, `InferSchemaType` doesn't do anything special with the `id` field as far as I can tell, at least not explicitly.

**Comment by juona** [comment]
Awesome work, as always! Thank you!
