### ISSUE TITLE
Issue when using _findOneAndUpdate with empty update 

### ISSUE THREAD

**Issue by valeriuflorescu16** [Automattic/mongoose#13783]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.3

### Node.js version

18.17.0

### MongoDB server version

6.0

### Typescript version (if applicable)

5.1.6

### Description

When running a `findOneAndUpdate` query with an empty update, I get a type error that happens in query.js on `delete doc._id`. Here is the error:

'TypeError: Cannot convert undefined or null to object\n' +
    '    at model.Query._findOneAndUpdate (C:\\Users\\username\\projects\\path-replacement\\node_modules\\mongoose\\lib\\query.js:3330:7)\n' +
    '    at model.Query.exec (C:\\Users\\username\\projects\\path-replacement\\node_modules\\mongoose\\lib\\query.js:4425:28)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' 

The reason it happens at 3330:7 is because I added console logs to check `this._update` and `doc` after cloning. They are both undefined. Here is what I am logging:

```
 if (!this._update || Object.keys(this._update).length === 0) {
    if (options.upsert) {
      // still need to do the upsert to empty doc
      console.log("update in query where we get err")
      console.log(this._update);
      const doc = clone(this._update);
      console.log("doc in query where we get err");
      console.log(doc);
      delete doc._id;
      this._update = { $set: doc };
    } else {
      this._executionStack = null;
      const res = await this._findOne();
      return res;
    }
}
```

This is what we notice logged in console:

> update in query where we get err
> undefined
> doc in query where we get err
> undefined

### Steps to Reproduce

Run a `findOneAndUpdate` query with an empty update, as follows:
```
await ExampleModel.findOneAndUpdate({ id: 1}, {}, { upsert: true, returnDocument: 'after', returnOriginal: false });
```

This should then produce the type error I am experiencing.

### Expected Behavior

I would expect to get back the response as normal, with no updates, if an update is not provided (i.e. if update is {}).

**Comment by valeriuflorescu16** [comment]
It looks like when clone takes in `null` or `undefined`, it will return `null` or `undefined`, as can be seen in clone.js, lines 30-32.  That's why we then get the "TypeError: Cannot convert undefined or null to object" when executing `delete doc._id`. 

I guess the question is, why is `this._update` undefined in query.js when an empty update is passed to "findOneAndUpdate" query? Passing `{}` to clone as follows: `const doc = clone(this._update ?? {});` seems to fix the issue.

**Comment by vkarpov15** [comment]
The following script executes without error, please modify the below script to demonstrate your issue:

```javascript
'use strict';
  
const mongoose = require('mongoose');
mongoose.set('debug', true);

void async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  await mongoose.connection.dropDatabase();

  const ExampleModel = mongoose.model('Example', new mongoose.Schema({
    id: Number,
    name: String
  }));
  const res = await ExampleModel.findOneAndUpdate({ id: 1}, {}, { upsert: true, returnDocument: 'after', returnOriginal: false });
  console.log('Done', res);
}();
```

Output:

```
$ node gh-13783.js 
Mongoose: examples.findOneAndUpdate({ id: 1 }, { '$setOnInsert': { __v: 0 } }, { upsert: true, returnDocument: 'after', returnOriginal: false })
Done { _id: new ObjectId("64eb333cf79db182b92aa221"), id: 1, __v: 0 }
^C
```
