### ISSUE TITLE
Sort and fields method returns empty on v7.0 and later

### ISSUE THREAD

**Issue by austingit26** [Automattic/mongoose#13789]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.4.5

### Node.js version

18.16.0

### MongoDB version

7.0

### Operating system

Windows

### Issue

I used the latest version of mongoose (v7.4.5) and I run into a problem when working with sort() method for req.query. I've read somewhere that version 7.0 and later changed sort(). So I downgraded to v6.9 and the code below works. Is there any of you knows how to resolve this in version 7.0 or later. I've read the documentation and searched online but nothing works. I badly need to finish this web API. Thank you for your time....

```
exports.getAllmovies = async (req, res) => {
  try {
    //make it string to use replace() method
    let queryStr = JSON.stringify(req.query);

    //replace gte, gt... with $gte, $gt... using regEx
    queryStr = queryStr.replace(/\b(gte|gt|lte|lt)\b/g, (match) => `$${match}`);

    //bring it back to json (from string)
    const queryObj = JSON.parse(queryStr);

    let query = Movie.find(queryObj);

    //if query consists of SORT
    if (req.query.sort) {
      const sortBy = req.query.sort.split(",").join(" ");
      query = query.sort(sortBy);
    }

    //limiting fields
    if(req.query.fields){
      const fields = req.query.fields.split(",").join(" ");
      query.select(fields)
    }

    const movies = await query;

    res.status(200).json({
      status: true,
      length: movies.length,
      data: {
        movies,
      },
    });
  } catch (error) {
    res.status(404).json({
      status: false,
      message: error.message,
    });
  }
};
```

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  age: Number
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  for (let i = 0; i < 11; i++) {
    await Test.create({
      age: i
    });
  }
  const res = await Test.find().sort({ age: -1 })
  console.log(res);
}

run();
```

**Comment by vkarpov15** [comment]
`query = query.find(queryObj);` is the problem because `queryObj` looks like this: `{ sort: '-age', age: { '$gte': 8 } }`.

Mongoose 6 stripped unknown fields from query filters by default, so it would strip out `sort` by default. Mongoose 7 doesn't, so your query is looking for documents that have a property `sort` equal to the string `'-age'`.

Add a `delete queryObj.sort` before `query = query.find(queryObj);` and it should work fine :+1:
