### ISSUE TITLE
BulkSave existing documents doesn't apply save middleware hook updates

### ISSUE THREAD

**Issue by tatejones** [Automattic/mongoose#13799]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.5

### Node.js version

18.16.0

### MongoDB server version

5.7

### Typescript version (if applicable)

5.1.6

### Description

When the bulkSave creates documents the modifications in the "save" middleware hook at persisted.
Subsequent updates made to the documents in "save" middleware hook are not persisted.  

Confirmed that the hook is being executed during the update.  See console.log below

### Steps to Reproduce

```typescript
describe("bulkSave middleware bug", async () => {
    it.only("it should be able to detect middleware save hook", async () => {
        const schema = new Schema({ name: String, _age: { type: Number, min: 0, default: 0 } })
        schema.pre("save", function () {
            this._age = this._age + 1
            console.log(`Updating person _age to ${this._age}`)
        })
        const connection = connectDatabase(mongodb.uri, "bulkSave")

        const Person = mongoose.model("Person", schema, "Persons", { connection })
        const person = new Person({ name: "Jean-Luc Picard", _age: 59 })

        await Person.bulkSave([person])

        let updatedPerson = await Person.findById(person._id)

        // this succeeds 
        expect(updatedPerson?._age).to.equal(60).

        await Person.bulkSave([updatedPerson!])

        updatedPerson = await Person.findById(person._id)
        
        // this fails - actual value is still 60
        expect(updatedPerson?._age).to.equal(61)
    })
})
```
Output

Updating person _age to 60
Updating person _age to 61
    1) it should be able to detect middleware save hook

  0 passing (113ms)
  1 failing

  1) bulkSave middleware bug
       it should be able to detect middleware save hook:

      AssertionError: expected 60 to equal 61
      + expected - actual

      -60
      +61
      
      at Context.<anonymous> (file:///Users/tate/code/Projects/HealthService/NodeServices/TypeScriptLibrary/src/__tests__/test.utils.ts:110:40)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Expected Behavior

Expect updates made in the save hook middleware to persist during a bulkSave.

**Comment by tatejones** [comment]
I have also attempted without prefix '_'

**Comment by tatejones** [comment]
In the bulkSave it looks like the this.buildBulkWriteOperations needs to be called after the pre-save hooks are called otherwise the embedded document in the writeOperations (a delta for update) won't be updated.  Hence why the create succeeds as it is a full document by reference and not mutated as a delta.

await Promise.all(documents.map(buildPreSavePromise));
const writeOperations = this.buildBulkWriteOperations(documents, { skipValidation: true, timestamps: options.timestamps

**Comment by hyunjinjeong** [comment]
I'm experiencing the same issue. pre-save hooks are executed but their results aren't applied to the final operation when using bulkSave().
