### ISSUE TITLE
BigInt get's returned as undefined but is shown in mongoDB Atlast as Int64

### ISSUE THREAD

**Issue by Schoonmoeder** [Automattic/mongoose#13791]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.5

### Node.js version

16.20.1

### MongoDB server version

7.0.0

### Typescript version (if applicable)

5.2.2

### Description

The value 14055648105137340n returns undefined if you save it in a BigInt
MongoDB Atlas shows it nicely as an Int64.

The signed type, Int64, can hold values from -9223372036854775808 to 9223372036854775807. The unsigned type, Uint64, can hold values from 0 to 18446744073709551615.

9223372036854775807 <- max range
14055648105137340n <- The value we tried to use doesn't work
1305564810513734n <- This value does work

I added a fix (#13787) with patch package to test if this helps but it didn't help

### Steps to Reproduce

```typescript
export interface IBlock {
  n: number; 
  reward: BigInt;
}

export const Block = model<IBlock>(
  'Block',
  new Schema<IBlock>({
     n: Number,
  reward: BigInt
  }),
);

  let a = await Block.create({n: 1, reward: 14055648105137340n});
  let b = await Block.findOne({n: 1});
  console.log(14055648105137340n);
  console.log('create : ', a);
  console.log('findOne : ', b);

  let c = await Block.create({n: 2, reward: 1305564810513734n});
  let d = await Block.findOne({n: 2});
  console.log(1305564810513734n);
  console.log('create : ', c);
  console.log('findOne : ', d);
```
### Expected Behavior

We expected to get the BigInt up to 9223372036854775807n returned

**Comment by Schoonmoeder** [comment]
I tried it also with 7.5.0, but it does not work.
hopefully, the next version will help fix this

**Comment by Schoonmoeder** [comment]
@vkarpov15 I did make a fix for myself. but I don't feel 100% comfortable that is production-ready.

the file lib/cast/bigint.js
I added to the following block just above: assert.ok(false);
`  if(typeof val === 'object'){
    return BigInt(String(val));
  }`

or with more checks for long param
`
  if(typeof val === 'object' && Object.keys(val).length === 3){
    if(val.low !== undefined && val.high !== undefined && val.unsigned !== undefined){
      return BigInt(String(val));
    }
  }`

the main issue is  how check that it is a new Long("123")

**Comment by IslandRhythms** [comment]
```
14055648105137340n
create :  {
  n: 1,
  reward: 14055648105137340n,
  _id: new ObjectId("6504d12486883d7655834fca"),
  __v: 0
}
findOne :  { _id: new ObjectId("6504d12486883d7655834fca"), n: 1, __v: 0 }
1305564810513734n
create :  {
  n: 2,
  reward: 1305564810513734n,
  _id: new ObjectId("6504d12486883d7655834fcd"),
  __v: 0
}
findOne :  {
  _id: new ObjectId("6504d12486883d7655834fcd"),
  n: 2,
  reward: 1305564810513734n,
  __v: 0
}
```
