### ISSUE TITLE
Populate nested refObject in array

### ISSUE THREAD

**Issue by younes200** [Automattic/mongoose#1381]
Hi,
I'm using 3.6.x version and here is my sample schema to reproduce : 

``` javascript
var PersonSchema = new Schema({
  name    : String,
  stories : [{ type: Schema.Types.ObjectId, ref: 'Story' }]
});

var StorySchema = new Schema({
  creator : { type: Schema.Types.ObjectId, ref: 'Person' },
  title    : String,
});
```

I'm trying to populate the creator ref for each stories saved, I tried the both path  :

``` javascript
Person.findById(user1._id).populate("stories stories.creator"}).exec(function(err, doc)
Person.findById(user1._id).populate("stories stories.$.creator"}).exec(function(err, doc)
```

but I got  the: **TypeError: Cannot call method 'path' of undefined**

My tests is running here :https://runnable.com/UT9iTD2wDj1UACXx

Thank you

**Comment by 1izpena** [comment]
For me doesn't work, I tried this:

     `async.forEach(value,function(item,callback) {

                    User.populate(item, {

                            path: 'tasks.createdby tasks.assignedto tasks.contributors',

                            select: 'username mail _id'

                        },

                        function(error,output) {

                            User.populate(output.tasks, {

                                    path: 'comments._user',

                                    select: 'username mail _id'

                                },

                                function(error,output2) {        
            
                                     arrUserstories.push(output2);

                                    callback();

                                });

                        });

                }, function(err) {

                    return promise.done(err, arrUserstories);

                });`

But output2 seems an array with a json stringify, but if I catch the first position to do parse.JSON it me undefined.
Output2:
`
[{"_id":"57518fc9d5b9a7855db1d611","numTask":5,"subject":"Implementar método POST para el módulo userstory en el API REST","createdby":{"_id":"56cb877e73da764818ec5ded","mail":"1izpena@mail.es","username":"1izpena"},"__v":0,"assignedto":{"_id":"56cb879e73da764818ec5def","mail":"asier@mail.es","username":"asier"},"attachments":[],"comments":[{"comment":"what??","_user":{"_id":"56cb877e73da764818ec5ded","mail":"1izpena@mail.es","username":"1izpena"},"_id":"5758902598685b144bd604ae","created":"2016-06-08T21:37:41.358Z"},{"comment":"what??","_user":{"_id":"56cb877e73da764818ec5ded","mail":"1izpena@mail.es","username":"1izpena"},"_id":"575890d1cb7efda84b6cfb39","created":"2016-06-08T21:40:33.398Z"},{"comment":"not working","_user":{"_id":"56cb877e73da764818ec5ded","mail":"1izpena@mail.es","username":"1izpena"},"_id":"5758ad991c645a18577281dc","created":"2016-06-08T23:43:21.517Z"},{"comment":"or yes??",....................."createdby":{"_id":"56cb877e73da764818ec5ded","mail":"1izpena@mail.es","username":"1izpena"},"__v":0,"attachments":[],"comments":[],"requirement":{"blocked":true,"iocaine":false},"status":"Ready for test","contributors":[],"datetime":"2016-06-07T03:20:17.438Z"}]`

**Comment by makrandgupta** [comment]
Mongoose now supports [deep populate](http://mongoosejs.com/docs/populate.html#deep-populate). Relevant code: 

```js
var userSchema = new Schema({
  name: String,
  friends: [{ type: ObjectId, ref: 'User' }]
});

User.
  findOne({ name: 'Val' }).
  populate({
    path: 'friends',
    // Get friends of friends - populate the 'friends' array for every friend
    populate: { path: 'friends' }
  });
```

**Comment by anytitleyoulike** [comment]
@makrandgupta Many thanks! it helped me a lot!
