### ISSUE TITLE
Add possibility to make .lean() in populate itself

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#1382]
It could be good for performance if you add populate lean() to .populate() method itself. So if we use populate at now like the following:

```
Model.find({ type: 'paper' }).lean().populate('batch').exec(fn)
```

We get documents with type 'paper' as just JavaScript objects but 'patch' as fully functional mongoose document. It could be cool if we could make something like the following:

```
Model.find({ type: 'paper' }).lean().populate('batch', {lean: true}).exec(fn)
```

Now all documents are just JavaScript object. What do you think about it?

**Comment by Twois** [comment]
This is still a bug, should be fixed.

**Comment by vkarpov15** [comment]
Please open a new issue with detailed repro instructions, don't comment on long-closed issues.
