### ISSUE TITLE
Anomalous behavior of sort method on array of strings

### ISSUE THREAD

**Issue by shrutipant7** [Automattic/mongoose#13824]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

^7.3.x

### Node.js version

16.x

### MongoDB version

^5.6.x

### Operating system

None

### Issue

I'm trying to apply sort in a collection having one of the field - tags (type array of strings). 
I'm getting response result re-ordered in no particular pattern, the tags are not sorted lexicographically but the order of items is different from what I got without applying sort on any field. 
I read somewhere that result will get sorted based on first item of tags array, but that's not happening.
Please comment if someone knows about the issue or have similar questions.

**Comment by vkarpov15** [comment]
Can you please provide a repro script or at least some code samples? Hard to infer what your code looks like from a prose description.
