### ISSUE TITLE
model.find() unexpected result  when concurrency 

### ISSUE THREAD

**Issue by 826327700** [Automattic/mongoose#13820]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.0.11

### Node.js version

v16.20

### MongoDB version

5.0

### Operating system

Windows

### Issue

```JavaScript
let test=async ()=>{
	let docs=await MailModel.find({isRead:false})
	console.log(docs.length)
	let notReadIds=docs.map(item=>item._id)
	await MailModel.updateMany({_id:{$in:notReadIds}},{$set:{isRead:true}})
}
let q=[]
for (let i = 0; i < 10; i++) {
	q.push(test())
}
await Promise.all(q)
```
I hope that when it executes for the second time, `console.log(docs.length)` should output 0. Unfortunately, it outputs a value greater than 0 every time. Who can tell me how to implement my idea?

**Comment by pshaddel** [comment]
> ### Prerequisites
> * [x]  I have written a descriptive issue title
> 
> ### Mongoose version
> 6.0.11
> 
> ### Node.js version
> v16.20
> 
> ### MongoDB version
> 5.0
> 
> ### Operating system
> Windows
> 
> ### Operating system version (i.e. 20.04, 11.3, 10)
> _No response_
> 
> ### Issue
> ```js
> let test=async ()=>{
> 	let docs=await MailModel.find({isRead:false})
> 	console.log(docs.length)
> 	let notReadIds=docs.map(item=>item._id)
> 	await MailModel.updateMany({_id:{$in:notReadIds}},{$set:{isRead:true}})
> }
> let q=[]
> for (let i = 0; i < 10; i++) {
> 	q.push(test())
> }
> await Promise.all(q)
> ```
> 
> I hope that when it executes for the second time, `console.log(docs.length)` should output 0. Unfortunately, it outputs a value greater than 0 every time. Who can tell me how to implement my idea?

I think your problem is relying on using the async pattern. When you call Promise.all(...) this sends all of these queries almost at the same time, and that is why you are getting length of 0 as result of all of them. One way to do this is to avoid promise.all and call await each time in for loop.

See the difference in the console:
```javascript
const test = async () => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('test:', new Date())
            resolve(new Date());
        }, 1000);
    });
}
// First Version
const main1 = async () => {
    let q = []
    for (let i = 0; i < 10; i++) {
        q.push(test())
    }
    await Promise.all(q)
}

// Second Version
const main2 = async () => {
    for (let i = 0; i < 10; i++) {
        await test()
    }
}

// main()
main2()
```

**Comment by 826327700** [comment]
> > ### 先决条件
> > 
> > * [x]   我写了一个描述性的问题标题
> > 
> > ### 猫鼬版本
> > 6.0.11
> > ### Node.js 版本
> > v16.20
> > ### MongoDB版本
> > 5.0
> > ### 操作系统
> > 视窗
> > ### 操作系统版本（即20.04、11.3、10）
> > _没有反应_
> > ### 问题
> > ```js
> > let test=async ()=>{
> > 	let docs=await MailModel.find({isRead:false})
> > 	console.log(docs.length)
> > 	let notReadIds=docs.map(item=>item._id)
> > 	await MailModel.updateMany({_id:{$in:notReadIds}},{$set:{isRead:true}})
> > }
> > let q=[]
> > for (let i = 0; i < 10; i++) {
> > 	q.push(test())
> > }
> > await Promise.all(q)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我希望当它第二次执行时，`console.log(docs.length)`应该输出0。不幸的是，它每次都输出大于0的值。谁能告诉我如何实现我的想法？
> 
> 我认为你的问题在于使用异步模式。当您调用 Promise.all(...) 时，它几乎同时发送所有这些查询，这就是为什么您得到的长度为 0 作为所有查询的结果。一种方法是避免promise.all并在for循环中每次调用await。
> 
> 在控制台中查看差异：
> 
> ```js
> const test = async () => {
>     return new Promise((resolve, reject) => {
>         setTimeout(() => {
>             console.log('test:', new Date())
>             resolve(new Date());
>         }, 1000);
>     });
> }
> // First Version
> const main1 = async () => {
>     let q = []
>     for (let i = 0; i < 10; i++) {
>         q.push(test())
>     }
>     await Promise.all(q)
> }
> 
> // Second Version
> const main2 = async () => {
>     for (let i = 0; i < 10; i++) {
>         await test()
>     }
> }
> 
> // main()
> main2()
> ```

I'm glad that you replied. However, my problem cannot be solved while avoid Promises. Promises are just used by me to simulate concurrent requests from the client. So, I would like to solve it from the database level.

**Comment by 826327700** [comment]
> ```js
> .session(session);
> ```

![image](https://github.com/Automattic/mongoose/assets/23014381/dbed7148-efa7-4fb1-aa20-f96dfa0693a5)
 I tried your example, why does the second request execute twice?

**Comment by 826327700** [comment]
@pshaddel 
Just now, the code I had was just a simple example. I made changes to the code below to better suit my actual needs,  the problem still hasn't been solved. The part marked in red will be successfully executed again during concurrency, resulting in an unexpected additional record in the database.
![image](https://github.com/Automattic/mongoose/assets/23014381/c4833d90-3b49-41d0-853e-2a52844e5bc3)

**Comment by vkarpov15** [comment]
[Transactions](https://mongoosejs.com/docs/transactions.html) are one approach as suggested in https://github.com/Automattic/mongoose/issues/13820#issuecomment-1705403362. Another approach is [`findOneAndUpdate()`](https://mongoosejs.com/docs/tutorials/findoneandupdate.html):

```javascript
let test=async ()=>{
	let doc = await MailModel.findOneAndUpdate({isRead:false}, { isRead: true });
       while (doc != null) {
         console.log(doc._id);
         doc = await MailModel.findOneAndUpdate({isRead:false}, { isRead: true });
       }
}
```

`findOneAndUpdate()` is atomic, so you can use it for cases where you want to read a document and mark that you read it so nobody else reads it.
