### ISSUE TITLE
Docs missing for ref and refPath as function

### ISSUE THREAD

**Issue by piyushk96** [Automattic/mongoose#13834]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.0

### Node.js version

N/A

### MongoDB version

N/A

### Operating system

None

### Issue

There is no proper documentation available on how to use a ref / refPath as functions in a schema. 

Also, I want to understand what is the intended behaviour of these functions? Whether they are called only once during the schema initialization phase and cache the function return value or these functions are executed for each document. 

The typescript mentions that these functions have access to `this` and `doc` so, is that mean that these functions will have access to document while processing and we can use document's fields to manipulate returned model or modelName
![image](https://github.com/Automattic/mongoose/assets/41179062/0d56208b-b8f8-43a7-b8b7-f2524a094247)

The only mention of ref function is [here](https://mongoosejs.com/docs/api/schematype.html#SchemaType.prototype.ref()) but it doesn't explains the above questions

Use Case:

```javascript
const Entity1 = new Schema({
  f1: { type: Number, required: true},
});
const Entity1Model = mongoose.model('Entity1', Entity1);

const Entity2 = new Schema({
  f2: { type: Number, required: true},
});
const Entity2Model = mongoose.model('Entity2', Entity2);

const E3 = new Schema({
  itemType: { type: String, enum: ['e1', 'e2'], required: true},

  itemId: {
    type: Types.ObjectId,
    ref(doc) {
      return doc.itemType === 'e1' ? Entity1Model : Entity2Model;
      // OR
      // return this.itemType === 'e1' ? Entity1Model : Entity2Model;
    }
  }
})
const E3Model = mongoose.model('E3', E3);
```

**Comment by piyushk96** [comment]
Use Case:

```
const Entity1 = new Schema({
  f1: { type: Number, required: true},
});
const Entity1Model = mongoose.model('Entity1', Entity1);

const Entity2 = new Schema({
  f2: { type: Number, required: true},
});
const Entity2Model = mongoose.model('Entity2', Entity2);

const E3 = new Schema({
  itemType: { type: String, enum: ['e1', 'e2'], required: true},

  itemId: {
    type: Types.ObjectId,
    ref(doc) {
      return doc.itemType === 'e1' ? Entity1Model : Entity2Model;
      // OR
      // return this.itemType === 'e1' ? Entity1Model : Entity2Model;
    }
  }
})
const E3Model = mongoose.model('E3', E3);
```

**Comment by piyushk96** [comment]
@vkarpov15 can you please tell me the expected behavior here until the docs are released on the website

**Comment by vkarpov15** [comment]
`ref` and `refPath` functions are called every time you `populate()`, for every document being populated. Is that helpful @piyushk96 ?

**Comment by piyushk96** [comment]
@vkarpov15 Thanks for the reply. Yes, this helps.
