### ISSUE TITLE
Best approach to use Mongoose with SocketIO per user connection

### ISSUE THREAD

**Issue by El-Tommy** [Automattic/mongoose#13833]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.65

### Node.js version

18.17.1

### MongoDB version

6.0.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Issue

I have an API created with Socket.IO 4.

This API every time it starts it makes a connection to MongoDB using Mongoose. This connection remains open until the script exits.

This use of Mongoose ​​creates the Models and Schemas on every startup.

Every time a user connects to the Socket.IO server, it uses this open connection to MongoDB to save that user's data into MongoDB. When there is a disconnection, this data is deleted, using the connection opened there at the beginning of the script.

Is my approach incorrect or correct?

My fear is that a hundred users connect at the same time and the execution of the script takes time to execute each save/delete one at a time.

Or should I for each request open a connection to MongoDB, do what needs to be done and close the connection (another fear: overloading with MongoDB)?

** I already noticed that even making a connection, there are always 5 connections in MongoDB that were established with the origin in the IP of the Socket.IO server.

**Comment by CCR-bhurtel** [comment]
Think about your application's structure and the average runtime of database operations. Reusing a single connection may be beneficial if most activities are fast and don't block the event loop for too long. Consider per-request connections if you expect lengthy procedures.

The fact that there are consistently 5 connections in MongoDB created with the Socket.IO server's origin IP suggests that this is a result of the way Mongoose handles connection pools by default.

A connection pool to MongoDB with a default pool size of 5 connections is maintained by Mongoose by default. To effectively handle incoming database requests, these connections are made and maintained. In a sensible setting, the connection pool size of 5 balances the need to handle concurrent requests without taxing the MongoDB server.

You can change the connection pool size like this:-
```
mongoose.connect('mongodb://localhost:27017/mydb', {
  poolSize: 10 // Adjust the pool size as needed
});
```

**Comment by vkarpov15** [comment]
"Or should I for each request open a connection to MongoDB, do what needs to be done and close the connection (another fear: overloading with MongoDB)?" <-- there's virtually no case where you should open a new connection for every request. Opening a connection when your application starts and keeping that connection open is the recommended way to use Mongoose for most applications, and nothing in your app's description indicates that pattern won't work for your use case.
