### ISSUE TITLE
In a custom type, how to trigger the castForQuery querying a nested property of the type?

### ISSUE THREAD

**Issue by Davian99** [Automattic/mongoose#13832]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.0

### Node.js version

18.2.0

### MongoDB version

6.0.9

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch

### Issue

Hi!

We are currently writing a custom Mixed type for mongoose and found the next issue with the triggering of the `castForQuery` function of the class.

As a mixed type, it may have nested properties that we should be able to query (and to do that, we first need to cast the query values). 

The problem is the following: if we try to query the collection with a nested property like this the custom `castForQuery` is not triggering. 
`model.find({'customs.a': '123'})`

On the other hand, querying it like this does indeed trigger it.
`model.find({customs: {a: '123'}})`

Is there anything we can do to trigger it in the first case? We can modify how our queries are generated for now, but a solution for the first case would speed up everything.

The following code is a really simple repro for out issue:
```
const mongoose = require('mongoose');

class Customs extends mongoose.SchemaType {
  constructor(key, options) {
    super(key, options, 'Customs');
  }

  cast(val) {
    console.log('Casting');
    return val;
  }

  castForQuery($conditional, value, context) {
    console.log('Casting query');
    return value;
  }
}
mongoose.Schema.Types.Customs = Customs;

const schema = new mongoose.Schema({
  customs: Customs,
});

const model = mongoose.model('schema', schema);

mongoose.connect('mongodb://127.0.0.1:27017', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('Does not trigger');
    await model.find({'customs.a': '123'});
    console.log('Does trigger');
    await model.find({customs: {a: '123'}});
  });
```

Thanks for looking into it!

**Comment by vkarpov15** [comment]
Unfortunately not, the way that Mongoose query casting works is that it first finds the schema type, so `custom.a` resolves to `undefined`, and then casts to match the schematype. There's unfortunately no way to plug into that schema type resolution process to say that subpaths of `custom` should have type `Custom`.

You should be aware that `model.find({'customs.a': '123'});` is a different query than `model.find({customs: {a: '123'}});`. The first finds documents where `customs.a` is equal to '123', regardless of other properties on `customs`. The latter finds documents where `customs` is deep equal to `{ a: '123' }`, so additional properties on `customs` will cause the query to not return any results.
