### ISSUE TITLE
Unable to create field named 'model'

### ISSUE THREAD

**Issue by mpaulucci** [Automattic/mongoose#1383]
I've just updated mongoose from 3.5.x to 3.6.0rc1

I had this schema defined:

```
CounterSchema = mongoose.Schema
    model : String
    next : Number
```

and now I get this error:

```
TypeError: Cannot read property 'scope' of undefined
    at model.Object.defineProperty.get [as model] (foo/node_modules/mongoose/lib/document.js:1184:58)
...
```

Renaming the field 'model' from Counter solves the issue.

**Comment by prescottprue** [comment]
+1 Thank you so much.

**Comment by ineentho** [comment]
Is it possible to improve the error message? It's pretty obvious that you can't create a method with the same name as a field, but a helpful message would be nice.
