### ISSUE TITLE
Conflicting information about migrating from `rawResult` to `includeResultMetadata`

### ISSUE THREAD

**Issue by letsgolesco** [Automattic/mongoose#13844]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.0

### Node.js version

18.17.1

### MongoDB server version

5.8.1

### Description

Related to https://github.com/Automattic/mongoose/issues/13661

The deprecation warning for the `rawResult` option has conflicting information on how to migrate to `includeResultMetadata`.

Screenshot:

<img width="873" alt="Screenshot 2023-09-08 at 12 54 44 PM" src="https://github.com/Automattic/mongoose/assets/3138141/68379eb7-5869-431b-b648-1f373449b447">

The first section says:

```
Replace `rawResult: true` with `includeResultMetadata: false` in `findOneAndUpdate()`, `findOneAndReplace()`, `findOneAndDelete()` calls.
```

But the example below indicates the opposite:

```js
// Replace this:
const doc = await Test.findOneAndUpdate(
  { name: 'Test' },
  { name: 'Test Testerson' },
  { rawResult: true }
);

// With this:
const doc = await Test.findOneAndUpdate(
  { name: 'Test' },
  { name: 'Test Testerson' },
  { includeResultMetadata: true }
);
```

### Steps to Reproduce

View the documentation at https://mongoosejs.com/docs/deprecations.html

### Expected Behavior

The documentation should be consistent, indicating that `rawResult: true` should be replaced with `includeResultMetadata: true`.

**Comment by Jule-** [comment]
Please could you plan to fix also the typings with this issue?

https://github.com/Automattic/mongoose/blob/c6e0665d729c68c0d3854858c296a0822d5cc8fb/types/models.d.ts#L640-L649

This is returning the wrong type.

Many thanks.

**Comment by Jule-** [comment]
@vkarpov15 too bad you didn't see my comment. Same mistake in the typings!

**Comment by Jule-** [comment]
Hum reading the issue again... I may have messed up the right from the wrong form. :sweat_smile:  I guess the typings were right, no? If so sorry for the false lead, you may close this one... :pray:
