### ISSUE TITLE
findOneAndUpdate doesn't update with aggregation pipeline like addFields

### ISSUE THREAD

**Issue by ManimuthurajT** [Automattic/mongoose#13853]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.2.9

### Node.js version

18.10.12

### MongoDB server version

5.0.20

### Typescript version (if applicable)

4.8.1

### Description

when I try to use aggregatoin pipleline in findOneAndUpdate its not working

### Steps to Reproduce

this is my update object
`
const conversationUpdate = [
            {
                $addFields: {
                    accountId,
                    channelId,
                    channelType,
                    latestMessageId: messageId,
                    contactId,
                    "whatsapp.waId": waId,
                    // eslint-disable-next-line no-nested-ternary
                    ...(botId ? { botId } : userId ? { userId } : {}),
                    ...(assigneeId ? { assigneeId } : {}),
                    ...(assigneeType ? { assigneeType } : {}),
                    // ...(botId || userId ? { $unset: { [botId ? "userId" : "botId"]: true } } : {}),
                    "conversationLog.userConversationDetails": {
                        $cond: {
                            if: {
                                $eq: [
                                    {
                                        $ifNull: ["$conversationLog.firstResponseTime", null],
                                    },
                                    null,
                                ],
                            },
                            then: {
                                assigneeId,
                                userAssigneedAt: "$createdAt",
                                userResponsedAt: new Date(),
                            },
                            else: {
                                $cond: {
                                    if: {
                                        $eq: [
                                            "$conversationLog.userConversationDetails.assigneeId",
                                            new mongoose.Types.ObjectId(assigneeId),
                                        ],
                                    },
                                    then: {
                                        assigneeId: "$conversationLog.userConversationDetails.assigneeId",
                                        userAssigneedAt: "$conversationLog.userConversationDetails.userAssigneedAt",
                                        userResponsedAt: {
                                            $cond: {
                                                if: {
                                                    $eq: [
                                                        {
                                                            $ifNull: [
                                                                "$conversationLog.userConversationDetails.userResponsedAt",
                                                                null,
                                                            ],
                                                        },
                                                        null,
                                                    ],
                                                },
                                                then: new Date(),
                                                else: "$conversationLog.userConversationDetails.userResponsedAt",
                                            },
                                        },
                                    },
                                    else: {
                                        assigneeId,
                                        userAssigneedAt: "$createAt",
                                        userResponsedAt: new Date(),
                                    },
                                },
                            },
                        },
                    },
                },
            },
        ];
`

**Comment by MohOraby** [comment]
What are you trying to achieve here? you can't pass pipeline stages to `findOneAndUpdate`
Typescript may not complain because you're passing an object and you may not have your types set correctly
`$addFields` is not a valid `findOneAndUpdate` operator so is `$cond`
You might have to reconsider how you handle this part, either use a valid update query or use an aggregation pipeline then `bulkWrite`/`bulkSave`

**Comment by ManimuthurajT** [comment]
What I am trying here is I want to update the document with $cond, and the reason why I need to use findOneAndUpdate is I want the document in response if I use update which is supporting aggregation pipeline while update(findOneAndUpdate not working) it (update) will not return the document

**Comment by MohOraby** [comment]
Can't you just put your condition in the query?
Example: let's say you want to only update if a person is older than 50 years old
`await findOneAndUpdate({ age: { $gt: 50 } }, updateObject)`

**Comment by ManimuthurajT** [comment]
Yes 

```const conversationUpdate = {
                $addFields: {
                    "conversationLog.userConversationDetails": {
                        $cond: {
                            if: {
                                $eq: [
                                    {
                                        $ifNull: ["$conversationLog.firstResponseTime", null],
                                    },
                                    null,
                                ],
                            },
                            then: {
                                name,
                            },
                            else: {
                                $cond: {
                                    if: {
                                        $eq: [
                                            "$conversationLog.userConversationDetails.assigneeId",
                                            incomingId,
                                        ],
                                    },
                                    then: {
                                        assigneeId: "$conversationLog.userConversationDetails.assigneeId",
                                        userAssigneedAt: "$conversationLog.userConversationDetails.userAssigneedAt",
                                        userResponsedAt: {
                                            $cond: {
                                                if: {
                                                    $eq: [
                                                        {
                                                            $ifNull: [
                                                                "$conversationLog.userConversationDetails.userResponsedAt",
                                                                null,
                                                            ],
                                                        },
                                                        null,
                                                    ],
                                                },
                                                then: new Date(),
                                                else: "$conversationLog.userConversationDetails.userResponsedAt",
                                            },
                                        },
                                    },
                                    else: {
                                        assigneeId: "incomingAssigneeId",
                                        userAssigneedAt: new Date(),
                                        userResponsedAt: new Date(),
                                    },
                                },
                            },
                        },
                    },
                },
            };

 const options = { new: true };

const options = { new: true };
        let conversationDoc = await Conversation.findOneAndUpdate(
            conversationFilter,
            conversationUpdate,
            options
        ).exec();```

**Comment by MohOraby** [comment]
Not what I meant, but from what I can see is you can just create an update object based on your conditions using `if` statements
Example
```typescript
const filterObject = { _id: '000000000000000000000000' }
let updateObject: any = {}

if (personA.age > personB.age) {
  updateObject.oldest = personA._id
  updateObject.youngest = personB._id;
} else {
  updateObject.oldest = personB._id
  updateObject.youngest = personA._id;
}

await PersonGroup.findOneAndUpdate(filterObject, updateObject)
```

**Comment by ManimuthurajT** [comment]
Yeah, you are right but for that, I need to find the document to do the condition because the condition is based on an existing document. I dont want to find the document will cost an extra DB call

**Comment by vkarpov15** [comment]
What does "when I try to use aggregatoin pipleline in findOneAndUpdate its not working" mean? Is there some error message, or some unexpected result? "its not working" isn't a valid bug report.
