### ISSUE TITLE
 Parameter "obj" to Document() must be an object, got "1152387311825330256" (type string)

### ISSUE THREAD

**Issue by EssamanerPL** [Automattic/mongoose#13866]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.2

### Node.js version

bun.sh

### MongoDB version

6.1.0

### Operating system

None

### Issue

[giveaway.command.zip](https://github.com/Automattic/mongoose/files/12629386/giveaway.command.zip)
[giveawaySchema.zip](https://github.com/Automattic/mongoose/files/12629388/giveawaySchema.zip)

This number is messageId

**Comment by IslandRhythms** [comment]
The code you provided does not include the code that is triggering the error. Please provide that.
