### ISSUE TITLE
How to use middleware for $lookup

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [Automattic/mongoose#13860]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.9.1

### Node.js version

16.17.1

### MongoDB version

7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4 (22F66)

### Issue

I am doing:

```
await this.orderModel.aggregate([
    {
        $lookup: {
            from: 'additionalverses',
            localField: '_id',
            foreignField: 'order',
            as: 'additionalVerses',
        }
    }
])
```

I want to write `additionalverses.pre()` middleware to omit {status: draft} additional verses.
Is it possible?

**Comment by vkarpov15** [comment]
Not possible unfortunately. You would need to add an additional `$match` stage to your `aggregate()` to filter out `status: 'draft'` verses
