### ISSUE TITLE
How to get the model name/collection name from a document middleware?

### ISSUE THREAD

**Issue by JavaScriptBach** [Automattic/mongoose#13878]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.12.0

### Node.js version

18

### MongoDB version

6

### Operating system

None

### Issue

I'm trying to write a query/document middleware that logs the model name + collection name in certain circumstances.

I looked at https://mongoosejs.com/docs/6.x/docs/api/document.html, and the first problem I ran into is that model/collection name are not documented in the types.

Then I tried writing:
```typescript
    let modelName = "";
    let collectionName = "";
    if (this instanceof Query) {
      modelName = this.model.modelName;
      collectionName = this.model.collection.name;
    } else if (this instanceof Document) {
      let doc = this;
      // Subdocuments seem to not have model/collection names so keep going up to the parent
      while (isSome(this.$parent()) && doc !== this.$parent()) {
        doc = this.$parent() as Document;
      }
      modelName = (doc.constructor as any).modelName;
      collectionName = doc.collection.name;
    }
```

But this does not work either in the document case, sometimes I get `TypeError: Cannot read properties of undefined (reading 'name')` because `doc.collection` is sometimes undefined. It seems like subdocuments also behave slightly differently than documents in this case.

Surely documents should know which model they came from, so there must be some way to do this. Help would be appreciated; thanks!

**Comment by vkarpov15** [comment]
Can you provide a repro script that demonstrate the case where `doc.collection` is `undefined`? That's unexpected.

Re: types for `doc.constructor`, we'll fix that. 

Also, instead of using a `while` loop to get the root document, you can just use `doc = this.ownerDocument()`.
