### ISSUE TITLE
Mongoose saves defaults despite setDefaultsOnInsert = false

### ISSUE THREAD

**Issue by jaschaio** [Automattic/mongoose#13873]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.4 and 7.5.2

### Node.js version

18.14.2

### MongoDB server version

5.0.19 and 6.0.5

### Description

I have set `mongoose.set( 'setDefaultsOnInsert', false );`

But when calling `document.save()` it still saves default values on subdocuments.

### Steps to Reproduce

Create a new repository, install `mongoose` and `mongodb-memory-server`.

Create a `index.js` file:

```js
// Node modules
import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';

// Create a new instance of the MongoMemoryServer
const mongod = await MongoMemoryServer.create();

// Connect to the in-memory database
await mongoose.connect( mongod.getUri() );

// Tell Mongoose to not save defaults on insert
mongoose.set( 'setDefaultsOnInsert', false );

// Define a schema with a default value
const testSchema = new mongoose.Schema( {
    name: {
        type: String,
        default: 'hello world',
    },
} );

// Create a model from the schema
const Test = mongoose.model( 'Test', testSchema );

// Create a new document
const test = new Test();

// Save the document
await test.save();

// Find all documents
const results = await mongoose.connection.db.collection( 'tests' ).find().toArray();

// Outputs [ { _id: new ObjectId("6507e7d364c8dd8c53584871"), name: 'hello world', __v: 0 } ]
console.log( results );
```

The document will be saved with `name` set to the default `hello world`.

### Expected Behavior

I would expect no defaults to be saved on the document if `setDefaultsOnInsert` is set to `false`

**Comment by IslandRhythms** [comment]
https://mongoosejs.com/docs/defaults.html#the-setdefaultsoninsert-option

That option only applies to `upsert` operations

**Comment by jaschaio** [comment]
Ok so defaults will always be saved when creating new documents? There is no way to prevent that and only have them populate when a value is undefined?

So if I change a default value in the Model I need to run a migration? Seems kind of odd, how would I differentiate between documents who have explicit set something to the same as the default value and those who just were saved automatically by mongoose upon `.save()`?

**Comment by vkarpov15** [comment]
You can disable defaults like this: `const test = new Test({}, null, { defaults: false });`. Does that help?

"how would I differentiate between documents who have explicit set something to the same as the default value and those who just were saved automatically by mongoose upon .save()?" <-- you can't differentiate between those two cases. If you need to differentiate between those two cases, you're better off using a custom getter rather than a default.

```javascript
const schema = new Schema({
  answer: {
    type: Number,
    get: v => v == null ? 42 : v
  }
});
```

The above will mean that `doc.answer = 42` if there's no `answer` property, but Mongoose won't store `answer = 42` in MongoDB.
