### ISSUE TITLE
MongoDB 7.0

### ISSUE THREAD

**Issue by GaborTorma** [Automattic/mongoose#13875]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7

### Node.js version

18

### MongoDB version

7.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian 12

### Issue

MongoDB 7.0 is supported by Mongoose?

**Comment by vkarpov15** [comment]
Yes, Mongoose 7.4 and up support MongoDB 7.

**Comment by vkarpov15** [comment]
Fixed by #13934

**Comment by JavaScriptBach** [comment]
@vkarpov15 Out of curiosity, why are only Mongoose 7.4 and up compatible with MongoDB 7? [MongoDB docs](https://www.mongodb.com/docs/drivers/node/current/compatibility/) claim that any driver 4.0 or later should work, although some new features may not be supported. That implies Mongoose 6 should be compatible, too.

Do you know if it's sound to use Mongoose 6 with MongoDB 7?

**Comment by vkarpov15** [comment]
It is, unless you're using some new MongoDB 7 features. Our rationale is that the docs you linked to say that MongoDB Node driver 5.7 is the minimum version you need to fully support MongoDB 7:

![image](https://github.com/Automattic/mongoose/assets/1620265/cd64425e-0ecc-4136-a215-2dfa059a2364)

And Mongoose 7.4 is the minimum version of Mongoose that uses MongoDB Node driver 5.7:

![image](https://github.com/Automattic/mongoose/assets/1620265/aa7227f0-3982-4525-927e-d1fb297c1287)

However, given that you have partial support for MongoDB 7 from MongoDB Node driver 4.0 and up, you should be fine to use Mongoose 6, which uses MongoDB Node driver 4.x.

**Comment by adnan-abdullah1** [comment]
@vkarpov15
Our database is on Atlas with mongodb version 7
And we are using mongoose 6.5.0

It works well but some time server breaks although we are not using any new feature of mongo 6

**Comment by timewarrior** [comment]
@adnan-abdullah1 - what is the exact issue that you are facing. Do you have details on the server breaks?

**Comment by vkarpov15** [comment]
@adnan-abdullah1 can you please provide any error messages or stack traces you're seeing?
