### ISSUE TITLE
WriteConflict with createCollection in transaction

### ISSUE THREAD

**Issue by JuMastro** [Automattic/mongoose#13886]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.2

### Node.js version

18.7

### MongoDB version

6.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

Hey,

I'd like to create a collection within a transaction but I'm getting a "WriteConflict" err during the commit process. I don't know why this occurs and how to resolve it.

```ts
const mongoose = require("mongoose");

const mongoUri =
  "mongodb://localhost:27027/?replicaSet=rs0&directConnection=true";
const mongoDbName = "mongoose-issue-create-collection-in-tx";

(async () => {
  const schema = new mongoose.Schema({ title: String });
  const Model = mongoose.model("post", schema);

  const client = await mongoose.connect(mongoUri, { dbName: mongoDbName });

  const session = await client.startSession();
  session.startTransaction({
    readPreference: "primary",
    readConcern: { level: "local" },
    writeConcern: { w: "majority" },
  });

  try {
    await Model.createCollection({ session });
    await session.commitTransaction();
    console.log("done");
  } catch (err) {
    console.error(err);
    await session.abortTransaction();
  } finally {
    await session.endSession();
    await client.connection.dropDatabase();
    await client.disconnect();
    process.exit();
  }
})();
```

Error:
```
MongoServerError: WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.
```

It throws a different err when using [Mongo v7](https://hub.docker.com/layers/library/mongo/7.0.0/images/sha256-86be2714cae3fbda498f608c67a15c3fd36e7261c5198c2edd8c963f8c4941b4?context=explore). The message looks like the following:

```
MongoServerError: Caused by :: Collection namespace 'mongoose-issue-create-collection-in-tx.posts' is already in use. :: Please retry your operation or multi-document transaction.
```

Any idea ? 

Thanks

**Comment by vkarpov15** [comment]
Add [`autoCreate: false` option](https://mongoosejs.com/docs/guide.html#autoCreate), otherwise Mongoose will automatically create the model's collection in the background: 

```javascript
const client = await mongoose.connect(mongoUri, { dbName: mongoDbName, autoCreate: false });
```
