### ISSUE TITLE
`andFail()` function

### ISSUE THREAD

**Issue by IslandRhythms** [Automattic/mongoose#13899]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We already have a `orFail()` function that throws an error if a document is not found. This function would simply behave the same but trigger when a document is found.

### Motivation

Sometimes you need to check if a document value is being used in another document before you can safely delete it, for example.

### Example

```javascript
const user = await User.find({ addressId: address._id }).andFail();
await Address.deleteOne({ _id: address._id });
```

**Comment by vkarpov15** [comment]
I'm not sure I understand the use case. In the example you provided (duplicated below), the `await Address.deleteOne()` call wouldn't even execute because `andFail()` would throw an error

```
const user = await User.find({ addressId: address._id }).andFail();
await Address.deleteOne({ _id: address._id });
```

**Comment by IslandRhythms** [comment]
Yes that's the use case. The `deleteOne()` is not called because the `User.find()` returned a document.

**Comment by vkarpov15** [comment]
I'm going to close this one for now, I don't think this use case is sufficiently prevalent to justify adding to Mongoose's API. I can see a few cases, like "don't allow deleting a payment method if there's a subscription that uses that payment method", but I don't think `andFail()` is widely applicable enough.
