### ISSUE TITLE
- error TypeError: (0 , _lib_mongoose__WEBPACK_IMPORTED_MODULE_1__.mongooseConnect) is not a function

### ISSUE THREAD

**Issue by aldofemat** [Automattic/mongoose#13896]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.5.2

### Node.js version

19

### MongoDB version

6.0.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

I have this error trying to connect my mongoose
- error TypeError: (0 , _lib_mongoose__WEBPACK_IMPORTED_MODULE_1__.mongooseConnect) is not a function
my code is the following

app/api/products/route.ts

```
import { Product } from "@/models/Product";
import {mongooseConnect} from "@/lib/mongoose";
import { NextResponse } from "next/server";
import clientPromise from "@/lib/mongodb";
import mongoose from "mongoose";

// Remove the default keyword and use a named export
export  async function POST(req: Request) {
  
    const { method } = req;
    await mongooseConnect();
  if(method === 'POST'){  
  const {title,description,price}= req.body;
  const productDoc = await Product.create({
    title,description,price,
   })

    return NextResponse.json(productDoc);
  }
}
```

lib/mongoose.ts

```
import mongoose from "mongoose";

export function mongooseConnect({children}){
    if(mongoose.connection.readyState===1){
        return mongoose.connection.asPromise();
    } else {
        const uri=process.env.MONGODB_URI;
        return mongoose.connect(uri);
    }
}
```

models/Product.ts

```
import {model,models,Schema} from "mongoose";

const ProductSchema= new Schema({
title:{type:String, require:true},
description: {type:String},
price: {type:Number, require:true},
},{
    timestamps: true,
});

export const Product = models.Product || model('Product', ProductSchema);
```

**Comment by vkarpov15** [comment]
Hard to tell without a more complete code sample, but this isn't a Mongoose issue because Mongoose doesn't export a `mongooseConnect()` function. You should try printing out the value of `mongooseConnect` using `console.log(mongooseConnect)` to see what value you're getting.
