### ISSUE TITLE
`Document.toObject()` doesn't return POJO

### ISSUE THREAD

**Issue by GabrielGorta** [Automattic/mongoose#13895]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.2

### Node.js version

18.6.0

### MongoDB server version

7.0.0

### Typescript version (if applicable)

5.0.0

### Description

Method `Document.toObject()` doesn't return pojo, it includes non serializable `_id` property of type `ObjectId`.

### Steps to Reproduce

```js
import * as devalue from 'devalue';
import { Schema, model } from 'mongoose';
const schema = new Schema({
    something: String
});
const Test = model("test", schema);
const document = Test.findOne({ something: "test" });
const pojo = document.toObject();
//    ^^^^ TYPE: `{ _id: Types.ObjectId, something: string }`
// need to do `pojo._id = String(pojo._id)`
const json = devalue.stringify(pojo);
//           ^^^^^^^^^^^^^^^^^^^^^ ERROR: Cannot stringify arbitary non-POJOs (pojo._id)
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const { Schema } = mongoose;

const testSchema = new Schema({
  something: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    something: 'Test Testerson'
  });

  const doc = await Test.findOne();
  const pojo = doc.toObject();

  const json = JSON.stringify(pojo);
  console.log('done');
}

run();
```

**Comment by vkarpov15** [comment]
Expected behavior, `ObjectId` is serializable by [`JSON.stringify()`](https://thecodebarbarian.com/the-80-20-guide-to-json-stringify-in-javascript). If you want to use devalue as an alternative JSON serializer, you should use [devalue's custom types logic](https://www.npmjs.com/package/devalue#custom-types) to serialize ObjectIds.
