### ISSUE TITLE
7.5.2 fix may be a breaking change for some projects

### ISSUE THREAD

**Issue by MomoRazor** [Automattic/mongoose#13892]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.2

### Node.js version

16.x

### MongoDB server version

7.x

### Typescript version (if applicable)

5.2.x

### Description

One of the changes brought about by the 7.5.2 version is the following:

**fix: ignore id property when calling set() with both id and _id specified to avoid id setter overwriting**
(https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md for reference)

In a specific project I was working one, this proved to be a breaking change, as we were passing {_id: undefined}, along with the creation of an entity, in order to force mongo to create another _id (it was a duplication system, so the entity would have its one _id, that needed removing). However, in this project we are also using a separate id field (just 'id') which meant that this id field was now being removed, due to the {_id: undefined}, which in turn meant that our validators were failing since they where expecting an id field.

Its a bit weird that {_id: undefined} counts as passing an _Id, but I do understand the logic, so I wouldn't call it a bug, more so that it might have warranted a mention as a possible breaking change, rather then just a routine fix.

Hope this saves some time for other people.

### Steps to Reproduce

- pass _id as undefined
- pass id

Notice that id still gets removed

**Comment by Eejit43** [comment]
This was definitely a breaking change, and it has broken a few of my projects as `id` is being stripped-

**Comment by Eejit43** [comment]
> Is there a current workaround so that `id` is not stripped? (I'm fixing our mongoose version to 7.5.1 for now.)

Depending on what you are doing, if you are replacing/updating an entry just don't pass `_id` and it works.

**Comment by stefandesu** [comment]
> Depending on what you are doing, if you are replacing/updating an entry just don't pass `_id` and it works.

The `id` already gets stripped in the return value of `insertMany` for me. Also, in our data, `id` and `_id` have different values as the data model we're working with ([W3C Web Annotation Data Model](https://www.w3.org/TR/annotation-model/)) uses property `id` for the URI of an entity (so `id` contains the full URI while `_id` only contains the UUID).

**Comment by Eejit43** [comment]
> > Depending on what you are doing, if you are replacing/updating an entry just don't pass `_id` and it works.
> 
> The `id` already gets stripped in the return value of `insertMany` for me. Also, in our data, `id` and `_id` have different values as the data model we're working with ([W3C Web Annotation Data Model](https://www.w3.org/TR/annotation-model/)) uses property `id` for the URI of an entity (so `id` contains the full URI while `_id` only contains the UUID).

In that case, I'm not sure. Thankfully it looks like this will be reverted in 7.5.4 (fingers crossed anyway).

**Comment by vkarpov15** [comment]
You're right, this is an unintended breaking change, we reverted in #13933 and will ship 7.5.4 shortly. We're very sorry about this issue.
