### ISSUE TITLE
Can't update a propery in a discriminator array

### ISSUE THREAD

**Issue by AaronPorts** [Automattic/mongoose#13908]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.3

### Node.js version

18.16.0

### MongoDB server version

4.4.18

### Typescript version (if applicable)

5.2.2

### Description

It looks like properties are not updated in a discriminator array unless they are in the "base" schema.

### Steps to Reproduce

```javascript
import { model, Schema } from "mongoose";

const BasicFileSchema = new Schema(
  { size: { type: Number }},
  { discriminatorKey: "type"},
);
const AudioFileSchema = new Schema({
  volume: { type: Number },
});
const ProjectSchema = new Schema({ files: [BasicFileSchema] });
ProjectSchema.path("files").discriminator("audio", AudioFileSchema );
const Model = model("Project", ProjectSchema);

const test = { files: [{ type: "audio", size: 100, volume: 5 }]};
const doc = await Model.create(test);

const {files} = await Model.findByIdAndUpdate(doc._id, {$set: {"files.0.size": 200, "files.0.volume": 10}}, {new: true});
```
In `files` property `size` has changed to 200, but `volume` not changed.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const { Schema } = mongoose;

const BasicFileSchema = new Schema(
  { size: { type: Number }},
  { discriminatorKey: "type"},
);
const AudioFileSchema = new Schema({
  volume: { type: Number },
});
const ProjectSchema = new Schema({ files: [BasicFileSchema] });
ProjectSchema.path("files").discriminator("audio", AudioFileSchema );
const Model = mongoose.model("Project", ProjectSchema);

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017');
  await mongoose.connection.dropDatabase();
  const test = { files: [{ type: "audio", size: 100, volume: 5 }]};
  const doc = await Model.create(test);

  const {files} = await Model.findByIdAndUpdate(doc._id, {$set: {"files.0.size": 200, "files.0.volume": 10}}, {new: true});
  console.log('what is files', files);
}

run();
```

**Comment by vkarpov15** [comment]
@AaronPorts this is expected behavior, Mongoose doesn't know what the type of `files.0` is in your update. Specify the discriminator key in the filter as follows and Mongoose will update the `volume`.

```javascript
  const {files} = await Model.findOneAndUpdate(
    { _id: doc._id, 'files.0.type': 'audio' },
    {$set: {"files.0.size": 200, "files.0.volume": 10}},
    {new: true}
  );

```

**Comment by AaronPorts** [comment]
@vkarpov15 Ok, but is it possible to update several schemes with different discriminator keys using a single method?

**Comment by vkarpov15** [comment]
@AaronPorts can you elaborate a little more on what you mean by updating several schemas with different discriminator keys using a single method?

**Comment by AaronPorts** [comment]
@vkarpov15 Let's say we have an array of elements `files: [{ type: "audio", size: 100, volume: 5 },{ type: "text", size: 100, language: "en" }]` . Can we update all files like this:
```javascript
await Model.findOneAndUpdate(
    { _id: doc._id, 'files.0.type': 'audio' /*<- what type should we use here*/ },
    {$set: {"files.0.size": 200, "files.1.language": "fr"}},
    {new: true}
  );
```

**Comment by vkarpov15** [comment]
`{ _id: doc._id, 'files.0.type': 'audio', 'files.1.type': 'text' }` should work
