### ISSUE TITLE
Memory Leak when using MongoDB Change Streams 

### ISSUE THREAD

**Issue by sanguineti** [Automattic/mongoose#13926]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

7.3.4

### Slowed down in version

7.4.0

### Node.js version

any

### 🦥 Performance issue

Due to changes in  driver, when 

Due to changes in `node-mongodb-native`, when using MongoDB Change Streams, anomalous resource usage has been observed in the monitoring of services that use `mongoose`. The mongodb team identified the problem and resolved it in version 5.9.0 of the driver.

### Steps to Reproduce

See detail in https://jira.mongodb.org/browse/NODE-5502

**Comment by sanguineti** [comment]
@vkarpov15 @IslandRhythms Hello, what are your thoughts on this issue? It has a high impact on resource usage when utilizing change streams. Do you consider it urgent to add the fix in one of the upcoming releases?

**Comment by vkarpov15** [comment]
Fix is out in Mongoose 7.6.0 :+1:
