### ISSUE TITLE
Error connecting to Mongo

### ISSUE THREAD

**Issue by o-paulo** [Automattic/mongoose#13943]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.0

### Node.js version

v18.17.1

### MongoDB version

v4.2.22

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22H2

### Issue

I'm having trouble connecting to the database. When trying to connect, I receive the error below in the console.

`MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at _handleConnectionErrors (C:\Users\PauloPereira\Desktop\party_time\node_modules\mongoose\lib\connection.js:805:11)
    at NativeConnection.openUri (C:\Users\PauloPereira\Desktop\party_time\node_modules\mongoose\lib\connection.js:780:11) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 685401557,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED ::1:27017
            at connectionFailureError (C:\Users\PauloPereira\Desktop\party_time\node_modules\mongodb\lib\cmap\connect.js:367:20)
            at TLSSocket.<anonymous> (C:\Users\PauloPereira\Desktop\party_time\node_modules\mongodb\lib\cmap\connect.js:290:22)
            at Object.onceWrapper (node:events:629:26)
            at TLSSocket.emit (node:events:514:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ECONNREFUSED ::1:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
            errno: -4078,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '::1',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}`

I've tried several ways to try to solve it, and I believe it's not an error in the code, but rather in my computer, but I don't know what's causing this.

Can you help me.

**Comment by IslandRhythms** [comment]
Please include the code that connects to mongo

**Comment by sean-daley** [comment]
Are you trying to connect to localhost:27017?

If so, check out the first item in the FAQ at https://github.com/Automattic/mongoose/blob/master/docs/faq.md about connection refused errors when connecting to that and see if it helps?

**Comment by donoftime2018** [comment]
> 1. Please provide the code where you trying to connect to the localhost.
> 2. Check that can you connect to the localhost in your MongoDB compass.
> 3. Make sure you have installed correct software's in your OS too.
> 4. instead of this:- const url = "mongodb://localhost:27017/DB-NAME", just Replace const url = "mongodb://127.0.0.1:27017/DB-NAME", or const url  = "mongodb://0.0.0.0:27017/DB-NAME".
> 5. Hope this helps 😄.

I mean it worked for me once so

**Comment by donoftime2018** [comment]
Might be different for me but I just did mongodb://127.0.0.1/DB_Name
