### ISSUE TITLE
insertMany return type changed from version 7.3.2 to 7.3.3

### ISSUE THREAD

**Issue by ksyd9821** [Automattic/mongoose#13957]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

>=7.3.3

### Node.js version

18.x

### MongoDB version

6.x

### Operating system

Windows

### Issue

It seems that the return type of the `insertMany` function changed with version 7.3.3. 
The following code runs without any error on v7.3.2 and lower
```
import * as mongoose from "mongoose";

export class RepositoryBase<T> {
    protected model: mongoose.Model<T & mongoose.Document>;

    constructor(schemaModel: mongoose.Model<T & mongoose.Document>) {
        this.model = schemaModel;
    }

    async insertMany(elems: T[]): Promise<T[]> {
        elems = await this.model.insertMany(elems);
        return elems;
    }
}
```
while on versions >=7.3.3 the assignment inside the function generates this error: 
![image](https://github.com/Automattic/mongoose/assets/147424724/09b911fa-6f47-4796-b984-9ce7fb2e7b6c)

The typescript version is 5.2.2.

**Comment by ksyd9821** [comment]
Hi @vkarpov15 ,

I upgraded to version 7.6.2 which should fix this issue, but the error is still present with the code above.

**Comment by vkarpov15** [comment]
@ksyd9821 can you please open a new issue and follow the issue template? We added a test case in #13964 and that test case is passing, so you must have a different setup than OP.
