### ISSUE TITLE
findOneAndUpdate with upsert sets schema defaults on the filter

### ISSUE THREAD

**Issue by Kezzel** [Automattic/mongoose#13962]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.3

### Node.js version

16.14.0

### MongoDB server version

4.0 (documentDB)

### Description

When using findOneAndUpdate with upsert, the defaults of the schema is being applied to the filter.

The below steps to reproduce shows the problem. Inside castUpdate.js (https://github.com/Automattic/mongoose/blob/1f6449576aac47dcb43f9974bb187a4f13d413d3/lib/helpers/query/castUpdate.js#L129) the $setOnInsert is being set to the actual object of filter (not a copy).

Thus when later on applying defaults, the reference to filter makes it update both the $setOnInsert in the update AND the filter.

This caused the filter in findOneAndUpdate to NOT match the expected docs and thus create a new one.

The bug has been detected in 7.5.3, but the code suggests that this is still an issue in 8.0.0 (https://github.com/Automattic/mongoose/blob/e15940051f868f56c0dc9cf935e42b31703bb18b/lib/helpers/query/castUpdate.js#L129C3-L129C37).

A workaround exists with setting the $setOnInsert for ALL the default fields to the defaults your self, to avoid them being set in the filter.

### Steps to Reproduce

```const mongoose = require('mongoose');
const { Schema } = mongoose;

(async function(){
    console.log('connecting');
    var client = await mongoose.connect(`mongodb://localhost:10003/dev?tls=true&directConnection=true&retryWrites=false`,
    {
        user: process.env.DBUSER,
        pass: process.env.DBPASS,
    });
    console.log('connected');

    const schema = new Schema({
        my_field: Number,
        default_field: {type:String, default: 'default'}
    }, {
        collection: `test`,
        //disable versioning alltogether
        versionKey: false
    });
    
    schema.index({my_field:1});

    const Model = mongoose.model(`Test`, schema);
    //Make sure it is clean
    await Model.deleteMany({});

    //create a doc
    await Model.create({my_field:1, default_field:'NOT DEFAULT'});

    //get the doc based on a filter
    const filter = {
        my_field:1
    };
    let docs = await Model.find(filter);
    console.log(`Doc with a non-default`, docs);

    await Model.findOneAndUpdate(filter,{},{
        upsert:true
    });

    docs = await Model.find(filter);
    console.log(`Docs with a duplicate`,docs);

    console.log('done');
    process.exit();
})();
```

### Expected Behavior

That the filter is NOT changed, and thus that the reproduction code would find the existing doc and not create a new one with a default.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose')
const { Schema } = mongoose;

(async function(){
    console.log('connecting');
    var client = await mongoose.connect(`mongodb://localhost:27017/`,
    {
        user: process.env.DBUSER,
        pass: process.env.DBPASS,
    });
    console.log('connected');

    const schema = new Schema({
        my_field: Number,
        default_field: {type:String, default: 'default'}
    }, {
        collection: `test`,
        //disable versioning alltogether
        versionKey: false
    });
    
    schema.index({my_field:1});

    const Model = mongoose.model(`Test`, schema);
    //Make sure it is clean
    await Model.deleteMany({});

    //create a doc
    await Model.create({my_field:1, default_field:'NOT DEFAULT'});

    //get the doc based on a filter
    const filter = {
        my_field:1
    };
    let docs = await Model.find(filter);
    console.log(`Doc with a non-default`, docs);

    await Model.findOneAndUpdate(filter,{},{
        upsert:true
    });

    docs = await Model.find(filter);
    console.log(`Docs with a duplicate`,docs);

    console.log('done');
    process.exit();
})();
```
