### ISSUE TITLE
The POST Request involving Model.create() stucks in between and does not respond with any error in console.

### ISSUE THREAD

**Issue by Abduttayyeb** [Automattic/mongoose#13961]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

16.2.0

### MongoDB server version

4.4.13

### Description

Here's a snippet of my createRequestHandler()

```js   
async createNotesRequestHandler(req, res) {
        console.log("Controller ::createNotesRequestHandler");
        const { user, title, text } = req.body;

        console.log("Creation Initiation");
        const noteObject = { user, title, text };
        
         const note = await Note.create(noteObject);   // <-- Request Hangs here
         
         if (note) {
                  res.status(201).json({ message: "New note created" });
         } else {
                  res.status(400).json({ message: "Invalid note data received" });
         }
    }
}
```

I have wrapped this handler inside asyncHandler() but still it does not catch any error, It works perfectly fine if I downgrade the mongoose version to @^6.5.0

### Steps to Reproduce

Link to Controller Code:- https://github.com/Abduttayyeb/Auth_BUC_Backend/blob/main/controllers/notesController.js

You can clone the above repo, and test it locally, through Postman, 
Or
Curl Request: 
```sh
curl -X POST -H "Content-Type: application/json" -d '{
  "user": "651319283e1b21f013f73054",
  "title": "My third Note",
  "text": "Yippeee!"
}' http://localhost:3500/notes
```

**Comment by IslandRhythms** [comment]
Have you tried adding a `.catch()` and see if that produces anything?

**Comment by Abduttayyeb** [comment]
> Have you tried adding a `.catch()` and see if that produces anything?

Yeaa I tried it, it doesn't catch the errors, and I've actually wrapped the asyncHandler to the controller functions, so try catch isn't required actually.

**Comment by donoftime2018** [comment]
> Please modify the script below to demonstrate your issue.
> 
> ```js
> const mongoose = require('mongoose');
> 
> const testSchema = new mongoose.Schema({
>   name: String
> });
> 
> const Test = mongoose.model('Test', testSchema);
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017');
>   await mongoose.connection.dropDatabase();
> 
>   await Test.create({
>     name: 'Test Testerson'
>   });
> 
>   console.log('done');
> }
> 
> run();
> ```

Maybe try returning 200 an actual existing status code instead of 201?

**Comment by donoftime2018** [comment]
> ### Prerequisites
> * [x]  I have written a descriptive issue title
> * [x]  I have searched existing issues to ensure the bug has not already been reported
> 
> ### Mongoose version
> 7.6.1
> 
> ### Node.js version
> 16.2.0
> 
> ### MongoDB server version
> 4.4.13
> 
> ### Typescript version (if applicable)
> _No response_
> 
> ### Description
> Here's a snippet of my createRequestHandler()
> 
> ```js
> async createNotesRequestHandler(req, res) {
>         console.log("Controller ::createNotesRequestHandler");
>         const { user, title, text } = req.body;
> 
>         console.log("Creation Initiation");
>         const noteObject = { user, title, text };
>         
>          const note = await Note.create(noteObject);   // <-- Request Hangs here
>          
>          if (note) {
>                   res.status(201).json({ message: "New note created" });
>          } else {
>                   res.status(400).json({ message: "Invalid note data received" });
>          }
>     }
> }
> ```
> 
> I have wrapped this handler inside asyncHandler() but still it does not catch any error, It works perfectly fine if I downgrade the mongoose version to @^6.5.0
> 
> ### Steps to Reproduce
> Link to Controller Code:- https://github.com/Abduttayyeb/Auth_BUC_Backend/blob/main/controllers/notesController.js
> 
> You can clone the above repo, and test it locally, through Postman, Or Curl Request:
> 
> ```shell
> curl -X POST -H "Content-Type: application/json" -d '{
>   "user": "651319283e1b21f013f73054",
>   "title": "My third Note",
>   "text": "Yippeee!"
> }' http://localhost:3500/notes
> ```
> 
> ### Expected Behavior
> _No response_

Maybe try returning 200 an actual existing status code instead of 201?

**Comment by donoftime2018** [comment]
I can't see the dotenv file in the fork I made from your repo.

**Comment by vkarpov15** [comment]
Try putting a `try/catch` around `await Note.create()`

**Comment by Abduttayyeb** [comment]
The error still persists for only one of my data model (`Note`), `Model.create` method works just fine for other data models, hence closing this issue for now.
