### ISSUE TITLE
Jest's toEqual on ObjectIds fails since 7.6.0

### ISSUE THREAD

**Issue by qqilihq** [Automattic/mongoose#13966]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.0, 7.6.1

### Node.js version

16.20.0

### MongoDB server version

4.4.24

### Description

The following Jest test would work fine (i.e. pass) until 7.5.4:

```typescript
it('allows comparing ObjectIds via Jest toEqual', async () => {
  const TestModel = model('testModel_ObjectIDIssue', new Schema({}));
  const newTestDocument = await TestModel.create({});
  const loadedTestDocument = await TestModel.findById(newTestDocument._id).orFail();
  expect(newTestDocument._id).toEqual(loadedTestDocument._id);
});
```

Since updating to 7.6.0 and also with 7.6.1, the test fails with:

```
    expect(received).toEqual(expected) // deep equality

    Compared values serialize to the same structure.
    Printing internal object structure without calling `toJSON` instead.

    - Expected  - 0
    + Received  + 2

    @@ -1,6 +1,8 @@
      ObjectId {
    +   "valueOf": [Function objectIdValueOf],
    +   Symbol(mongoose#ObjectId): true,
        Symbol(id): Buffer [
          101,
          38,
          91,
          159,

      12 |     const newTestDocument = await TestModel.create({});
      13 |     const loadedTestDocument = await TestModel.findById(newTestDocument._id).orFail();
    > 14 |     expect(newTestDocument._id).toEqual(loadedTestDocument._id);
         |                                 ^
```

We're using the following Jest and Jest-related versions (latest each):

```
"@shelf/jest-mongodb": "4.1.7",
"@types/jest": "29.5.5",
"jest": "29.7.0",
"jest-environment-node": "^29.7.0",
"jest-extended": "^4.0.2",
"ts-jest": "29.1.1",
```

### Steps to Reproduce

Run test as shown below.

### Expected Behavior

Test should not fail

**Comment by IslandRhythms** [comment]
You can use the virtual `id` or append `.toString()` as a workaround for now.

**Comment by qqilihq** [comment]
@IslandRhythms Thank you, however, this will not work when using `.toEqual()` with nested objects.

Seeing the `7.6.4` milestone, I assume for now that this is something you intend to fix? Thus we'd rather wait with updating to 7.6.x for now to avoid having to change thousands of occurrences in our test suite's codebase.

**Comment by IslandRhythms** [comment]
Please include your setup. I am unable to reproduce. Please modify the script below to demonstrate your issue.

```javascript
'use strict';

const { describe, expect, test, it } = require('@jest/globals');
const mongoose = require('mongoose');

it('allows comparing ObjectIds via Jest toEqual', async () => {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  const TestModel = mongoose.model('testModel_ObjectIDIssue', new mongoose.Schema({}));
  const newTestDocument = await TestModel.create({});
  const loadedTestDocument = await TestModel.findById(newTestDocument._id).orFail();
  await mongoose.connection.close();
  expect(newTestDocument._id).toEqual(loadedTestDocument._id);
});
```

![image](https://github.com/Automattic/mongoose/assets/39510674/c09cc632-743d-4b86-bc6f-118a16d9c825)

**Comment by qqilihq** [comment]
@IslandRhythms Thank you for the reply - interestingly the issue does **not** occur in a new, isolated project.

We will need to figure the culprit - please feel free to close this for now, and if needed I'll comment.

Thank you!

**Comment by qqilihq** [comment]
We do not really know what caused the issue at the end, but jumping straight to mongoose v8 fixed it. Thank you, everybody.
