### ISSUE TITLE
document revision (__v) not updating while calling save on the document

### ISSUE THREAD

**Issue by suthar26** [Automattic/mongoose#13967]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

19.5.0

### MongoDB server version

7.0.2

### Typescript version (if applicable)

5.2.2

### Description

saving a document with `.save()` is not updating the `__v` 
mongoose debug does not have the `__v` fields incrementing on `.updateOne` call after updating all of the properties of the object.
```
Mongoose: configs.updateOne({ _id: ObjectId("6526d81525696106af2cea75") }, { '$set': { name: 'updated-test-config', type: 'updated-test-config-type' }}, {})
```

### Steps to Reproduce

```ts
import mongoose from "mongoose"
const { connect } = mongoose

mongoose.set('debug', true)

class Config {
  _id: mongoose.Types.ObjectId
  name: string
  type: string
}


const configSchema = new mongoose.Schema({
  name: String,
  type: String,
})


const ConfigModel = mongoose.model('Config', configSchema);

async function setup() {
  const config = await new ConfigModel({
    name: 'test-config-name',
    type: 'test-config-1',
  }).save()


  return config
}

// this mimics the update from the featureconfig service
async function update(updateDocument: Partial<Config>) {
  const config = await ConfigModel.findOne({ _id: updateDocument._id })
  if (!config) {
    throw new Error('no config')
  }
  console.log('config found', config)

  config.name = updateDocument.name
  config.type = updateDocument.type
  await config.save()
  return config
}

async function run() {
  console.log('Running test')
  await connect('mongodb://localhost:27017/')

  const savedConfig = await setup()
  const updateDocument = Object.assign(savedConfig.toObject())

  updateDocument.name = 'updated-test-config'
  updateDocument.type = 'updated-test-config-type'

  const updatedConfig = await update(updateDocument)

  console.log('updatedConfig', JSON.stringify(updatedConfig, null, 2))

}
run()
```

### Expected Behavior

expected for the Mongoose debug log to have the `'$inc': { __v: 1 }}` property so the revision of the document gets updated as necessary

**Comment by suthar26** [comment]
realized this is because there is no subdocument in the model along with optimistic concurrency not being activated. I ended up adding a pre save hook to update the version if the document was modified. 

The documentation seemed very confusing and should be updated around the versioning update and versioning key.

**Comment by vkarpov15** [comment]
This is expected behavior, `__v` doesn't increment unless there's changes to arrays by default. You would need to enable optimistic concurrency like here: https://thecodebarbarian.com/whats-new-in-mongoose-5-10-optimistic-concurrency.html
