### ISSUE TITLE
Modified flag does not work correctly during transaction retries

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#13973]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

16.19.1

### MongoDB server version

5

### Typescript version (if applicable)

4.8.3

### Description

Hello there! I have some code that essentially boils down to this (pseudo-code):

```typescript
const document = await getDocument({ status: "in_progress" }); // returns a document where status === "in_progress"

document.status = "canceled";

withTransaction(async () => {
    await document.save();
});
```

Mongoose v7.4.4 fixed some issues with the modified flags and now they are properly reverted to `true` in case of a transaction failure. So if the transaction is retried, the "status" field will still be "modified" and a correct update will be sent to the database when `.save()` is called again.

However, this code would not work anymore:

```typescript
const document = await getDocument({ status: "in_progress" });

withTransaction(async () => {
    document.status = "canceled";
    await document.save();
});
```

Now if the transaction is retried, the "status" field is still modified. However, after the line `document.status = "canceled";` is executed it is no longer "modified".

My first guess was that the setter simply checks if the value changed, and since in this case it didn't, the field's modified flag is set to `false`. I then tried setting the same value to the field twice in a row, and the "modified" flag worked as expected. Kind of expected, since such an obvious thing would probably have been caught a long time ago : ]

### Steps to Reproduce

I am sorry for not providing a working reproduction script this time, my deadline is literally tomorrow and I just took a few minutes to write this down. If you'd like me to provide one, please say so and I will post it next week.

### Expected Behavior

I often use a pattern like this:

```typescript
const document = await getDocument({ status: "in_progress" });

withTransaction(async () => {
    await document.cancel();
});
```

where `.cancel()` sets the status and calls `.save()`. Due to this issue, a lot of code that we've written will occasionally misbehave.

My expectation is that the "modified" flag works consistently with how it does when there are no transaction retries.

**Comment by vkarpov15** [comment]
Confirmed, the following script:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb+srv://XYZ:ABC@cluster0.YYYY.mongodb.net/mongoose_test?retryWrites=true&w=majority');
  console.log('Connected');

  const Test = mongoose.model('Test', new mongoose.Schema({ status: String }));
  await Test.deleteMany({});

  const { _id } = await Test.create({ status: 'test' });
  const doc = await Test.findById(_id);

  let i = 0;
  await mongoose.connection.transaction(async (session) => {
    doc.status = 'test2';
    console.log('Modified', doc.$isModified('status'));
    await doc.save({ session });
    if (++i < 3) {
      throw new mongoose.mongo.MongoServerError({
        errorLabels: ['TransientTransactionError']
      });
    }
  });
  console.log('Done');
}

```

prints the following:

```
$ node gh-13973.js 
Connected
Modified true
Modified false
Modified false
Done

```

So it looks like transaction handling is mixing up change tracking. Will fix.
