### ISSUE TITLE
Default values in subdocuments when they are set using dot notation

### ISSUE THREAD

**Issue by pavlos163** [Automattic/mongoose#13972]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.8.0

### Node.js version

16.10.0

### MongoDB version

5.0.21

### Operating system

None

### Issue

I have the following schema:
```
const mySchema = new mongoose.Schema(
  {
    ...
    someField: {
      _id: false,
      type: {
        subdocumentA: {
          _id: false,
          name: { type: String },
        },
        subdocumentB: {
          _id: false,
          name: { type: String },
          version: {
            type: String,
            default: "default-version"
          }
        }
      }
    },
    ...
  },
  { toJSON: { virtuals: true }, toObject: { virtuals: true } }
);
```

As you can see, subdocumentB has a field with a default value, `"default-version"`.

I have the following code that creates documents.
```
const createNewDocument = async (): Promise<void> => {
  const data = {
    ...,
    "someField.subdocumentB" {
      name: "Name"
    },
    ...
  };

  await new MyDocument(data).save();
};
```

When the document above is created, the default value is not actually added.

On the other hand, if I create the subdocument like this:
```
const createNewDocument2 = async (): Promise<void> => {
  const data = {
    ...,
    someField: {
      subdocumentB: {
        name: "Name"
      }
    },
    ...
  };

  await new MyDocument(data).save();
};
```

Then the default value is actually added!

I have two questions:
1) Is this expected behaviour?
2) If yes, why?
3) In the second method, even though I'm getting my default value, which I want, I am overwriting the whole of `someField`, which I don't want to do, for example, when I want to update the document instead of creating a new one, as `someField.subdocumentA` may have data as well which I don't want to overwrite. What is generally the best approach here?

**Comment by vkarpov15** [comment]
Yes, expected behavior. Because `type: { subdocumentA, subdocumentB }` is a subdocument, but `subdocumentA: { name }` and `subdocumentB: { name, version }` are nested paths. [See docs on nested paths vs subdocuments](https://mongoosejs.com/docs/subdocs.html#subdocuments-versus-nested-paths). 

For question 3, can you please clarify what you're trying to do? I don't quite understand the question.
