### ISSUE TITLE
SyntaxError: Invalid or unexpected token at Module._extensions..js

### ISSUE THREAD

**Issue by wardverduyn** [Automattic/mongoose#13971]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

20.8.0

### MongoDB server version

7.0.2

### Description

I have a problem using Mongoose in my node.js application. Everytime I run `npm run dev`, my application crashed with the error and stack trace below.

```
[nodemon] restarting due to changes...
[nodemon] starting `node -r esm .`
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

D:\HoneypotProject\node_modules\mongoose\node_modules\mongodb\lib\collection.js:74
            pkFactory: db.options?.pkFactory ?? utils_1.DEFAULT_PK_FACTORY,
                                  ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.8.0
[nodemon] app crashed - waiting for file changes before starting...
```

### Steps to Reproduce

This is my code

```
import cors from 'cors';
import express from 'express';
import mongoose from 'mongoose';

// Import constants
import { DB, PORT } from './constants';

// Initialize express app
const app = express();

const main = () => {
    mongoose.connect("mongodb://localhost:27017/my-database?useNewUrlParser=true&useUnifiedTopology=true")
}

main();
```

**Comment by wardverduyn** [comment]
> optional chaining was introduced with node 14. You write you use node 20, but I would first double check if you are not accidently using node 12 or so.

In my stack trace it says Node.js v20.8.0

**Comment by Uzlopak** [comment]
Maybe it is nodemon.

**Comment by wardverduyn** [comment]
> Maybe it is nodemon.

What do you mean?

**Comment by vkarpov15** [comment]
Try running without `-r esm`? You don't really need the esm package in Node 20, Node 20 supports ESM.

**Comment by donoftime2018** [comment]
First of all, try connecting via 127.0.0.1 instead of localhost

**Comment by Nandpatel1** [comment]
I faced the same issue, so I downgraded my mongoose version to 5.12.1 using `npm install mongoose@5.12.1`, and it worked for now.
