### ISSUE TITLE
The combination of the $elemMatch and $or operators causes TypeError for array field

### ISSUE THREAD

**Issue by qprqpr** [Automattic/mongoose#13974]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

16.17.0

### MongoDB server version

6.0.2

### Description

When using the `$elemMatch` operator in combination with the `$or` operator in a Mongoose query to search for documents containing an array of objects, a TypeError error occurs. The error has been reproduced since version **7.6.x**. In version **7.5.x** the query is executed without error.

#### Sample code:

```js
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  arr: [Object],
});

const test = mongoose.model('schema', schema);

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/issue');
  await mongoose.connection.dropDatabase();

  const obj1 = new test({ arr: [{ id: 'one'}, { id: 'two' }] });
  await obj1.save();

  const obj2 = new test({ arr: [{ id: 'two'}, { id: 'three' }] });
  await obj2.save();

  const obj3 = new test({ arr: [{ id: 'three'}, { id: 'four' }] });
  await obj3.save();

  const res = await test.find({
    arr: {
      $elemMatch: {
        $or: [{ id: 'one' }, { id: 'two' }],
      },
    },
  });

  console.log(res);
}

run();
```

#### The query results in a TypeError with the following message:

```
/mongoose-bug/node_modules/mongoose/lib/cast.js:71
        const discriminatorValue = val[k][schema.options.discriminatorKey];
                                                 ^
TypeError: Cannot read properties of undefined (reading 'options')
```

**Comment by tarus622** [comment]
Did you fix that error? I have tested here and this error don't occur.

The response was:

[
  {
    _id: new ObjectId("652d98a853738d908bbc8980"),
    arr: [ [Object], [Object] ],
    __v: 0
  },
  {
    _id: new ObjectId("652d98a853738d908bbc8982"),
    arr: [ [Object], [Object] ],
    __v: 0
  }
]

**Comment by tarus622** [comment]
``Did you fix that error? I have tested here and this error don't occur.

The response was:

`[
  {
    _id: new ObjectId("652d98a853738d908bbc8980"),
    arr: [ [Object], [Object] ],
    __v: 0
  },
  {
    _id: new ObjectId("652d98a853738d908bbc8982"),
    arr: [ [Object], [Object] ],
    __v: 0
  }
]
`

**Comment by tarus622** [comment]
Did you fix that error? I have tested here and this error don't occur.

The response was:

![mongo-test-bug](https://github.com/Automattic/mongoose/assets/94433435/1ed6ea22-ef20-4039-ad1a-e2d5950b2b18)

**Comment by ronjouch** [comment]
Was affected by this bug too as I was migrating a project to Mongoose 7! Thanks OP for the report, and thaaaaaaaaaanks @vkarpov15 for the fix 🙂.
