### ISSUE TITLE
Read preference tags deprecation cause and timeline

### ISSUE THREAD

**Issue by k4y3ff** [Automattic/mongoose#13980]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello! 👋 

I'm responsible for a codebase that uses a `primary` read preference for some queries and `secondaryPreferred` for others. We are adding an analytics node to our MongoDB cluster, however, and thus [need to specify read preference tags when using `secondaryPreferred`](https://www.mongodb.com/docs/atlas/reference/replica-set-tags/#isolate-normal-application-secondary-reads-from-analytics-nodes) to ensure that production application queries are not served by the analytics node.

I've looked in the MongoDB Node.js driver, and read preference tags appear to be supported with no caveats ([GitHub](https://github.com/mongodb/node-mongodb-native/blob/v6.1.0/src/read_preference.ts#L42) / [API documentation](https://mongoosejs.com/docs/6.x/docs/api/aggregate.html#aggregate_Aggregate-read) / [documentation](https://www.mongodb.com/docs/manual/core/read-preference/#mongodb-readmode-secondaryPreferred)). However, reading the Mongoose documentation, it appears that read preference tags are marked as `DEPRECATED` in [version 6+](https://mongoosejs.com/docs/6.x/docs/api/aggregate.html#aggregate_Aggregate-read).

Since it is not a breaking change, only a deprecation, this does not seem to be mentioned in the ["Migrating from 5.x to 6.x" guide](https://mongoosejs.com/docs/6.x/docs/migrating_to_6.html). The PR that added `DEPRECATED` in the documentation (https://github.com/Automattic/mongoose/pull/12140) does not include a detailed description, either. People [seem to be recommending using read preference tags in open issues](https://github.com/Automattic/mongoose/issues/13131#issuecomment-1456503797) as late as this March, too.

Could anyone provide more information on why read preference tags are considered deprecated and what the timeline is for sunsetting them?

Thanks in advance.

**Comment by vkarpov15** [comment]
It looks like this "DEPRECATED" line was unintentionally added, I missed this during code review. @hasezoey what was the reason behind marking `Aggregate.prototype.read` `tags` param as deprecated here: https://github.com/Automattic/mongoose/commit/437b03a81c12fb804a366ff3d50b5084fc504c3e ?

Even without `tags` param, you can always use `.read(new mongoose.mongo.ReadPreference(pref, tags))`.

**Comment by hasezoey** [comment]
i dont know exactly why i added this anymore, but it may have something to do with typescript leading me to mquery when doing a `Go to Definition`, which has the following code:

https://github.com/mongoosejs/mquery/blob/e7a8a3099ef282a2d9af36a2880981871adfe9fd/lib/mquery.js#L1603-L1610
(snippit because github only does snippits for same repository):
```js
Query.prototype.read = Query.prototype.setReadPreference = function(pref) {
  if (arguments.length > 1 && !Query.prototype.read.deprecationWarningIssued) {
    console.error('Deprecation warning: \'tags\' argument is not supported anymore in Query.read() method. Please use mongodb.ReadPreference object instead.');
    Query.prototype.read.deprecationWarningIssued = true;
  }
  this.options.readPreference = utils.readPref(pref);
  return this;
};
```
