### ISSUE TITLE
findOneAndUpdate Setter is not triggering

### ISSUE THREAD

**Issue by MPiland** [Automattic/mongoose#13991]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.2

### Node.js version

18.7.1

### MongoDB version

6.0.11

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10.0.22621

### Issue

I cannot for the life of me understand what I'm doing wrong. I have a model that looks essentially like this

```
export const itemSchema = new Schema(
  {
...
damage: {
      diceCount: Number,
      diceValue: Number,
      diceShort: {
        type: String,
        set: () => {
          let diceShortValue = ''
          console.log('updated this=', this._update)
          if (this._update.damage.diceCount && this._update.damage.diceValue) {
            diceShortValue = `${this._update.damage.diceCount}d${this._update.damage.diceValue}`
          }
          return diceShortValue
        },
      }
...
},
  {
    toJSON: { setters: true, minimize: true, virtuals: true },
    toObject: { setters: true, minimize: true, virtuals: true },
    runSettersOnQuery: true,
  }
)

export default mongoose.model('Item', itemSchema)
```

My API for updating a document looks like

```
export const updateItem = async (req, res) => {
  const { _id } = req.body

  if (!_id) {
    return res.status(400).json({ message: 'Item ID is required' })
  }

  const updatedItem = req.body

  let item
  try {
    item = await Item.findOneAndUpdate({ _id: _id }, updatedItem, {
      upsert: true,
      new: true,
      runValidators: true,
    }).exec()
  } catch (err) {
    console.log(err)
  }

  if (!item) {
    return res.status(400).json({ message: 'Item not found' })
  }

  res.json(`'${item.value}' updated`)
}
```

I have confirmed that the setter is not firing no matter what I change on the document. I can't understand what I'm doing wrong here. Any help would be appreciated. This seems to be a difficult concept for me to grasp. I basically am trying to create the value for the key whenever the user updates/creates the document. If I'm going about this the wrong way, please tell me how I should be approaching this.

I'm using this in a MERN application with RTK Query if that helps. It seems to run if I force a diceValue or diceCount value to change in the findOneAndUpdate call, but otherwise, it doesn't run at all even if the values did change in the payload. There's no error nor a console log.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: {
    firstName: String,
    lastName: String,
    nickName: {
      type: String,
      set: (v) => {
        return v.substring(0, 2)
      }
    }
  }
}, { 
  toJSON: { setters: true, minimize: true, virtuals: true },
  toObject: { setters: true, minimize: true, virtuals: true },
  runSettersOnQuery: true
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: {
      firstName: 'Test',
      lastName: 'Testerson',
      nickName: 'John'
    }
  });

  const res = await Test.findOne();
  console.log('res', res, res.name?.nickName);
  console.log('done');
  await mongoose.connection.close();

}

run();
```

**Comment by IslandRhythms** [comment]
I think what you want in your case is a virtual since that allows you to access the different properties of the doc https://mongoosejs.com/docs/guide.html#virtuals whereas declaring a setter on the property only allows you to access the value for that property.

**Comment by MPiland** [comment]
I thought about that as well, but as I'm using this in a React application, the virtual doesn't actually show up since the payload is saved in a state. Unless I'm misunderstanding how virtuals work, for the virtual to display I would have to access the object itself, right?

Also, why did you remove the tags when what you ran isn't the same as what I have? You're using .create where my issue was specifically with .findOneAndUpdate. Even the setter you're using isn't grabbing the values from other keys. Your whole test doesn't match any of my issue at all. Not trying to be offensive here, but I've been struggling with this for days searching Google and all sorts of forums with no answer.
