### ISSUE TITLE
insertMany return type incompatible with document type

### ISSUE THREAD

**Issue by ksyd9821** [Automattic/mongoose#13999]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.3

### Node.js version

18.x

### MongoDB server version

6.x

### Typescript version (if applicable)

5.2.2

### Description

This is the same issue previously reported in #13957
I have included the code that reproduces it below.
Basically with the code below
```
import * as mongoose from "mongoose";

export class RepositoryBase<T> {
    protected model: mongoose.Model<T & mongoose.Document>;

    constructor(schemaModel: mongoose.Model<T & mongoose.Document>) {
        this.model = schemaModel;
    }

    async insertMany(elems: T[]): Promise<T[]> {
        elems = await this.model.insertMany(elems);
        return elems;
    }
}
```
the assignment inside the `insertMany` function generates the following error
![image](https://github.com/Automattic/mongoose/assets/147424724/72b7d4f3-5d8d-489d-8774-119921a5a0a3)

### Steps to Reproduce

https://github.com/ksyd9821/mongoose-insert-many-issue

```[tasklist]
### Tasks
```

**Comment by donoftime2018** [comment]
> ### Prerequisites
> * [x]  I have written a descriptive issue title
> * [x]  I have searched existing issues to ensure the bug has not already been reported
> 
> ### Mongoose version
> 7.6.3
> 
> ### Node.js version
> 18.x
> 
> ### MongoDB server version
> 6.x
> 
> ### Typescript version (if applicable)
> 5.2.2
> 
> ### Description
> This is the same issue previously reported in #13957 I have included the code that reproduces it below. Basically with the code below
> 
> ```
> import * as mongoose from "mongoose";
> 
> export class RepositoryBase<T> {
>     protected model: mongoose.Model<T & mongoose.Document>;
> 
>     constructor(schemaModel: mongoose.Model<T & mongoose.Document>) {
>         this.model = schemaModel;
>     }
> 
>     async insertMany(elems: T[]): Promise<T[]> {
>         elems = await this.model.insertMany(elems);
>         return elems;
>     }
> }
> ```
> 
> the assignment inside the `insertMany` function generates the following error ![image](https://user-images.githubusercontent.com/147424724/277343780-72b7d4f3-5d8d-489d-8774-119921a5a0a3.png)
> 
> ### Steps to Reproduce
> https://github.com/ksyd9821/mongoose-insert-many-issue
> 
> ### Expected Behavior
> _No response_
> 
> ### Tasks
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> No tasks being tracked yet.
> 1. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2.

Maybe try typecasting elems to type T[]

**Comment by donoftime2018** [comment]
> > ### Prerequisites
> > 
> > * [x]   I have written a descriptive issue title
> > * [x]   I have searched existing issues to ensure the bug has not already been reported
> > 
> > ### Mongoose version
> > 7.6.3
> > ### Node.js version
> > 18.x
> > ### MongoDB server version
> > 6.x
> > ### Typescript version (if applicable)
> > 5.2.2
> > ### Description
> > This is the same issue previously reported in #13957 I have included the code that reproduces it below. Basically with the code below
> > ```
> > import * as mongoose from "mongoose";
> > 
> > export class RepositoryBase<T> {
> >     protected model: mongoose.Model<T & mongoose.Document>;
> > 
> >     constructor(schemaModel: mongoose.Model<T & mongoose.Document>) {
> >         this.model = schemaModel;
> >     }
> > 
> >     async insertMany(elems: T[]): Promise<T[]> {
> >         elems = await this.model.insertMany(elems);
> >         return elems;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the assignment inside the `insertMany` function generates the following error ![image](https://user-images.githubusercontent.com/147424724/277343780-72b7d4f3-5d8d-489d-8774-119921a5a0a3.png)
> > ### Steps to Reproduce
> > https://github.com/ksyd9821/mongoose-insert-many-issue
> > ### Expected Behavior
> > _No response_
> > ### Tasks
> > Beta
> > [Give feedback](https://github.com/community/community/discussions/39106)
> > No tasks being tracked yet.
> > 
> > 1. [ ]
> >    Options
> >    ```
> >      * Convert to issue
> >      * Toggle completion
> >      * Rename
> >      * Remove
> >    ```
> 
> Maybe try typecasting elems to type T[] in the line, elems = await this.model.insertMany(elems);

So according to some research, you could try function overloading with random types like Boolean, int, etc. What I did that did stop the error, was replacing the T[] in the function head with any[]. Not sure if it caused it to work right, but that error isn't being thrown anymore.

  async insertMany(elems: any[]): Promise<any[]>{
        elems = await this.model.insertMany(elems);
        return elems;
    }

**Comment by donoftime2018** [comment]
UPDATE:

My new solution is to typecast elems to type T[] by elems = await this.model.insertMany(elems) as T[] in line 12.

**Comment by donoftime2018** [comment]
` async insertMany(elems: T[]): Promise<T[]> {
        elems = await this.model.insertMany(elems) as T[];
        return elems;
    }
`

Typecasting elems as T[] before returning it worked for me.

**Comment by vkarpov15** [comment]
Just remove the `& Document` and this script compiles fine:

```ts
import * as mongoose from "mongoose";

export class RepositoryBase<T> {
    protected model: mongoose.Model<T>;

    constructor(schemaModel: mongoose.Model<T>) {
        this.model = schemaModel;
    }

    async insertMany(elems: T[]): Promise<T[]> {
        elems = await this.model.insertMany(elems);
        return elems;
    }
}
```

As of Mongoose 7, we no longer support using `extends Document` in the `DocType` generic param to `Model<>`, and we recommend using the raw doc type instead. So don't use `& Document`.

**Comment by hardcodet** [comment]
Hi @vkarpov15 

Just stumbled over this one. Is it possible that there is an overload missing here?
Your snippet works, but not, if I provide an options object. See the inferred types in the screenshot here - `bar` here doesn't properly cast to `T[]`, while `foo` works.

![image](https://github.com/Automattic/mongoose/assets/873009/d5fe5498-d2fd-4fe1-8473-2c32d2133aad)


Let me know if you'd prefer a new issue. (I also don't know if you'll read this, since it's already closed, so I might open a new issue in a few days anyway).
