### ISSUE TITLE
Should not create inherited indexes beyond "disableLowerIndexes: true"

### ISSUE THREAD

**Issue by tatejones** [Automattic/mongoose#14009]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.1

### Node.js version

18.x

### MongoDB server version

6.0

### Typescript version (if applicable)

4.9.5

### Description

Indexes are created on the parent class when the option disableLowerIndexes is true on the child class.
I would expect the child class indexes to be created, but the parent to be ignored.

The use case for this is text indexes as a collection can only have one text index.
A -> B
A -> C

Class A has the text index and B has disableLowerIndexes false and C has disableLowerIndexes true.   Currently the schema is attempting to created two text indexes and therefore syncIndexes will fail with duplicate index details. 

### Steps to Reproduce

```
 it('should not create one level inherited indexes beyond "disableLowerIndexes: true"', () => {
    @index({ dummy1: 1 })
    class IndexInherit5 {
      @prop()
      public dummy1?: string;
    }

    @index({ dummy2: 1 })
    @modelOptions({ options: { disableLowerIndexes: true } })
    class IndexInherit6 extends IndexInherit5 {
      @prop()
      public dummy2?: string;
    }

    const sch = buildSchema(IndexInherit6);
    const indexes = sch.indexes();
    expect(indexes.length).toStrictEqual(2);
    expect(indexes).toStrictEqual([
      [{ dummy2: 1 }, { background: true }],
    ]);
  });
```

### Expected Behavior

```
expect(indexes).toStrictEqual([
    [{ dummy2: 1 }, { background: true }],
]);
```
but received
[
    [{ dummy1: 1 }, { background: true }],
    [{ dummy2: 1 }, { background: true }],
]

**Comment by vkarpov15** [comment]
`disableLowerIndexes` is not a supported option in Mongoose, are you using some other lib?

**Comment by tatejones** [comment]
Sorry, I have accidentally posted this to the wrong project.  It was intended for the typegoose library project.
