### ISSUE TITLE
MongoDB 6 support for Mongoose 4.13

### ISSUE THREAD

**Issue by rubenstolk** [Automattic/mongoose#14005]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

4.13

### Node.js version

18.x

### MongoDB version

6.x

### Operating system

None

### Issue

For an older project we're looking to keep it running while updating to MongoDB 6. It's using Mongoose 4.13 and it's working fine with MongoDB 4.4 and 5.0 but for 6 a few connection changes have happened.

Has anyone looked into upgrading the connection stuff for Mongoose 4.13 by any chance?

**Comment by vkarpov15** [comment]
Unfortunately not. [Mongoose 4 doesn't even support MongoDB 3.6](https://mongoosejs.com/docs/compatibility.html), let alone 6.0. You will need to upgrade to Mongoose 6.5 at least for MongoDB 6.0 support.
