### ISSUE TITLE
<Data>.length not working properly

### ISSUE THREAD

**Issue by CarlosFrog** [Automattic/mongoose#14012]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.3

### Node.js version

18.17.1

### MongoDB server version

6.0.11

### Description

I have this automod code, however I have noticed an issue with it:
- When a user reaches 3 warnings, gets 1 more warning, the bot logs `Count: 5`, meaning it is skipping the 4 and timeouting the user for the wrong amount of time. 

Automod Code: https://pastebin.com/TpBqLWtD
automodMute Function Code: https://pastebin.com/q9mW1r0S

Using the latest version of discord.js and Sapphire Framework.
Here's an image of what is getting logged:

![image](https://github.com/Automattic/mongoose/assets/94943063/88a482ad-81f1-40dc-9e7d-4834776769a0)

### Steps to Reproduce

Reach 3 warnings, the next one will count as 5.

### Expected Behavior

When you reach 3 warnings the next warning number should be 4, not 5.

**Comment by vkarpov15** [comment]
It looks like your code calls both `automod()` and `automodMute()` when count is 3:

```
      if ([3, 4, 5].includes(count)) {
        await automodMute(message.member, message, count);
      }
 
      await automod(message.member, reason, message);
```

I don't see the implementation of `automod` in your pastebin, but based on `automodMute()` I would guess that `automod` also creates a new document, so that would explain why your count jumps from 3 to 5.

**Comment by CarlosFrog** [comment]
> I don't see the implementation of `automod` in your pastebin, but based on `automodMute()` I would guess that `automod` also creates a new document, so that would explain why your count jumps from 3 to 5.

the automod function sends a DM, I have tested this 100+ times and no duplicate DMs have been sent

**Comment by CarlosFrog** [comment]
I could send the code for it if needed

**Comment by vkarpov15** [comment]
Yes please upload the code

**Comment by CarlosFrog** [comment]
> Yes please upload the code

https://pastebin.com/0YFB0TCu
Pastebin Password: r9paDC9Rhz

**Comment by CarlosFrog** [comment]
any updates?

**Comment by vkarpov15** [comment]
Yep confirmed, the issue is the following:

```javascript
      if ([3, 4, 5].includes(count)) {
        await automodMute(message.member, message, count);
      }
 
      await automod(message.member, reason, message);
```

Both `automodMute()` and `automod()` create new documents, so of course `data.length` goes up by 2 each time once `data.length` reaches 3.
