### ISSUE TITLE
Strange Timestamps Type Inference

### ISSUE THREAD

**Issue by kiki-kanri** [Automattic/mongoose#14013]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.3

### Node.js version

20.9

### MongoDB version

7.0.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu22.04

### Issue

It may be related to [this](https://github.com/Automattic/mongoose/pull/12871) PR.

I wrote a model build function to make it easier for me to standardize the addition of plugins when building a model.

Model builder function:
```typescript
import { model, PaginateModel, Schema } from 'mongoose';
import mongoosePaginate from 'mongoose-paginate-v2';
import normalize from 'normalize-mongoose';

export const buildModel = <T extends Schema>(collection: string, name: string, schema: T) => {
	schema.plugin(mongoosePaginate);
	schema.plugin(normalize);
	const tModel = model(name, schema, collection);
	return tModel as typeof tModel & PaginateModel<T, T['query'], T['methods']>;
}
```

Schema:
```typescript
const adminSchema = new Schema({
	// Fields
}, {
	timestamps: true
});
```

Under normal conditions there is an automatic type determination of timestamps.

```typescript
const AdminModel = buildModel('10_admins', 'Admin', adminSchema);
const admin = await AdminModel.findOne();
admin?.createdAt // It works
```
![image](https://github.com/Automattic/mongoose/assets/83924639/37b6838b-9f8b-4c91-9962-d96c378f3323)

But as soon as I set statics or methods, timestamps related types are disabled.

```typescript
const adminSchema = new Schema({
	// Fields
}, {
        statics: {
		// Some statics
	},
	timestamps: true
});

const AdminModel = buildModel('10_admins', 'Admin', adminSchema);
const admin = await AdminModel.findOne();
admin?.createdAt // no createdAt attributes
```

![image](https://github.com/Automattic/mongoose/assets/83924639/d7f78e60-0369-42f6-9b8b-fa4fdb45bd3c)

But when I change the timestamps in DefaultSchemaOptions interface directly, it works again.

Is this by design or is there no definitive solution yet?

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior currently, see [automatic type inference docs](https://mongoosejs.com/docs/typescript/schemas.html#automatic-type-inference)

![image](https://github.com/Automattic/mongoose/assets/1620265/6f1614d0-7458-4451-b815-4b26b4504969)

We have an issue #12807 to track this issue, as a workaround you should define `createdAt` and `updatedAt` yourself in your schemas if you use statics, methods, or virtuals.
