### ISSUE TITLE
Running GeoSpatial queries via populated fields not working (bug or feature?)

### ISSUE THREAD

**Issue by AndreasGalster2** [Automattic/mongoose#14016]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.2

### Node.js version

v18.18.2

### MongoDB version

MongoDB 6.0.11 Atlas

### Operating system

Linux

### Issue

I originally posted this here but figured this might be worth a discussion:
https://www.mongodb.com/community/forums/t/how-to-populate-field-before-running-a-geospatial-query-on-it/251380/1

Hi, I have a schema, for a vendor and a schema for locations

The vendor has the location model as a reference like so:

```
const vendorDetailSchema = new mongoose.Schema(
  {
 // som other fields
    locationDetails: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'LocationDetail',
      required: true,
    },
});
```

The location model is defined like this, with a 2dsphere index included:

```
const locationDetailSchema = new mongoose.Schema({
  locationType: {
    type: String,
    enum: ['USER', 'VENDOR', 'DELIVERY_ADDRESS'],
    required: true,
  },
  gpsInfo: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
    },
    coordinates: {
      type: [Number],
      required: true,
    },
  },
  locationName: String,
  locationAddress: String,
  locationGooglePlacesJSON: String, // This is a JSON String from Google Places API
});

locationDetailSchema.index({ gpsInfo: '2dsphere' });
```

When I try to get the nearest locations directly, I can retrieve them properly…

```
      const vendors = await LocationDetail.find({
        gpsInfo: {
          $nearSphere: {
            $geometry: {
              type: 'Point',
              coordinates: [userLocation[1], userLocation[0]],
            },
            $maxDistance: 500 * 1000, // kilometers multiplier
          },
        },
      })
        .limit(limit)
        .exec();
```

However, if I try to populate the data into the VendorDetail model, it throws an error… 

```
        const vendors = await VendorDetail.find({
          'locationDetails.gpsInfo': {
            $nearSphere: {
              $geometry: {
                type: 'Point',
                coordinates: [userLocation[1], userLocation[0]],
              },
              $maxDistance: 500 * 1000, // kilometers multiplier
            },
          },
        })
          .populate({
            path: 'locationDetails',
          })
          .limit(limit)
          .exec();
```

The error message that I get is:
`error processing query: ns=test.vendordetailsTree: GEONEAR field=locationDetails.gpsInfo maxdist=500000 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error :: caused by :: unable to find index for $geoNear query
`

I am assuming this is related to me populating the data… I suppose this is somewhat by design (at least from the MongoDB driver perspective), after all, the 2dspace index is created on the LocationDetail model/collection, but the nearSpace query is being run on VendorDetail... 

However, I decided to create an issue here because I suppose one could say the populate function is designed/intended for gathering data from other collections. So I don't think it's necessarily a bug, but perhaps this would be food for thought for a feature request.

I solved this particular problem with two separate queries for now... It's not exactly elegant but at least it works for now as a simple hack.

```
      const locations = await LocationDetail.find({
        // approved: true,
        gpsInfo: {
          $nearSphere: {
            $geometry: {
              type: 'Point',
              coordinates: [userLocation[1], userLocation[0]],
            },
            $maxDistance: 900 * 1000, // kilometers multiplier
          },
        },
      })
        .limit(limit)
        .exec();

      const locationIds = locations.map((location) => location.referrer_id);

      const unSortedVendors = await VendorDetail.find({
        _id: { $in: locationIds },
      });

      const vendors = locationIds.map((locationId) => unSortedVendors.find((vendor) => vendor._id.equals(locationId)));
      // sort based on the order retrieved in the sorted LocationDetail result
```

On a sidenote this seems to be the only workable approach aside from denormalization, since aggregating also wouldn't work, because a GeoSpatial query has to be the first result in an aggregate pipeline, making it impossible to aggregate the data from the location collection via lookups

```
         $lookup: {
           from: 'locationdetails',
           localField: 'locationDetails',
           foreignField: '_id',
           as: 'locationDetails',
         },
```

**Comment by vkarpov15** [comment]
This is expected behavior, `populate()` just executes a separate query to load the referenced document. You can't filter or sort based on populated fields in general.
