### ISSUE TITLE
mongodb connection issue

### ISSUE THREAD

**Issue by parasop** [Automattic/mongoose#14015]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.3.1

### Node.js version

18

### MongoDB version

4

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu

### Issue

MongoNetworkError: C0870E1AD47F0000:error:0A00438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80

**Comment by donoftime2018** [comment]
Can I please see the code for how you are connecting?

**Comment by Hassaan-Qaisar** [comment]
maybe you have denied access of your ip address in your mongodb
