### ISSUE TITLE
Undocumented breaking change in v7: calling `diffIndexes` throws error when collection does not exist

### ISSUE THREAD

**Issue by fjeldstad** [Automattic/mongoose#14010]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In Mongoose 6, if you called `await Model.diffIndexes()` on a model where the collection does not yet exist, it would return the index diff and let you proceed with things like `await Model.syncIndexes()`. I suppose it would create the collection first - but I haven't verified this.

In Mongoose 7, it will throw an error instead:

> MongoServerError: ns does not exist [...]

It throws even if you have `autoCreate: true` set on the global `mongoose` instance.

I suppose the fix is to call `await Model.createCollection()` first, but still this was a breaking change that is not listed in the release notes or migration guide as far as I can see.

I created a small demo where you can see the issue here: https://codesandbox.io/p/sandbox/quirky-kapitsa-49vy78?file=%2Findex.js%3A5%2C1

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.set('autoIndex', false);
mongoose.set('autoCreate', true);

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const res = await Test.diffIndexes();
  console.log('res', res);
}

run();
```
