### ISSUE TITLE
There was a problem (Error: read ENOTCONN) in myConsoleReporter and it has been destroyed.

### ISSUE THREAD

**Issue by sumitLKpatel** [Automattic/mongoose#14014]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.3

### Node.js version

18.17.0

### MongoDB server version

6

### Description

when I try to connect to the Mongo database it gives me the below error. this is working fine in node 14.

There was a problem (Error: read ENOTCONN) in myConsoleReporter and it has been destroyed.
Error: read ENOTCONN
    at tryReadStart (node:net:683:20)
    at Socket._read (node:net:694:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at Socket. read (node:net:750:39)
Mongo

### Steps to Reproduce

just try to connect in node 18+

**Comment by vkarpov15** [comment]
I'm going to need a more complete code sample. `myConsoleReporter` isn't defined in Mongoose or any of Mongoose's dependencies AFAIK.
