### ISSUE TITLE
Incorrect inferred return type for `distinct()` on array fields

### ISSUE THREAD

**Issue by richardsimko** [Automattic/mongoose#14026]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.0

### Node.js version

20.0.0

### MongoDB server version

6.0

### Typescript version (if applicable)

latest

### Description

The inferred return type for `distinct()` queries with an array fields is incorrect. It's inferred to be `string[][]` for a `string[]` field when in fact it should be `string[]`

### Steps to Reproduce

```ts
interface Foo {
  bar: string[];
}

const FooModel = model<Foo>('Foo', new Schema<Foo>({ bar: [String] }));

await FooModel.create({ bar: ['a', 'b'] })

const distinctBar = await FooModel.distinct('bar');
console.log(distinctBar); // [ 'a', 'b' ]
```

`distinctBar` is actually a `string[]` but the inferred return type is `string[][]`.

### Expected Behavior

Inferred return type does not add `Array` to a type which is already an `Array`

**Comment by donoftime2018** [comment]
Try to do a (String[]) cast in distinctBar assignment. Maybe check how you are accessing the bar field via distinct method?

**Comment by donoftime2018** [comment]
distinct is actually returning an array of String arrays. bar is a String[] and distinct selects all unique String arrays within an array.

**Comment by richardsimko** [comment]
@donoftime2018 No, `distinct()` returns an array of strings when run on a field with `string[]` type. See the [Mongo docs](https://www.mongodb.com/docs/manual/reference/method/db.collection.distinct/#return-distinct-values-for-an-array-field). I've confirmed this is the case for mongoose as well.

Here's an amended example:

```ts
interface Foo {
  bar: string[];
}

const FooModel = model<Foo>('Foo', new Schema<Foo>({ bar: [String] }));

await FooModel.create({ bar: ['a', 'b'] })

const distinctBar = await FooModel.distinct('bar');
console.log(distinctBar); // [ 'a', 'b' ]
```

I've edited the description as well to explain this

**Comment by donoftime2018** [comment]
Try adding more documents to the collection

**Comment by donoftime2018** [comment]
Or try updating your version of mongoose

**Comment by IslandRhythms** [comment]
For me it ends up being an `any[]`

```typescript
import * as mongoose from 'mongoose';

interface Foo {
  bar: string[];
}

const FooModel = mongoose.model<Foo>('Foo', new mongoose.Schema<Foo>({ bar: [String] }));

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  await FooModel.create({ bar: ['a', 'b'] })
  await FooModel.create({ bar: ['c','d']});
  await FooModel.create({ bar: ['e','f']})

  const distinctBar = await FooModel.distinct('bar');
  console.log(distinctBar); // [ 'a', 'b', 'c', 'd', 'e', 'f' ]
}

run();
```

**Comment by donoftime2018** [comment]
Shall I report this as a bug?

**Comment by richardsimko** [comment]
@donoftime2018 That does sound like a separate bug, yes. I couldn't find anything in neither the mongo nor mongoose docs pointing to the behavior you mentioned being correct. As @IslandRhythms mentioned the type is `string[][]` even when the returned value is `string[]` (Thanks for confirming :) )

**Comment by donoftime2018** [comment]
Np

**Comment by IslandRhythms** [comment]
@donoftime2018 please open a new issue and follow the template if you have a bug to report.

**Comment by donoftime2018** [comment]
How?

**Comment by IslandRhythms** [comment]
From this page on the top left next to this issue title you should see a new issue button.

**Comment by donoftime2018** [comment]
I wanna take a go and fix this issue via code so what should I do?

**Comment by donoftime2018** [comment]
@IslandRhythms @richardsimko 
So, what I did was remove the brackets from string in the interface Foo declaration, so it looks like
interface Foo {
  bar: string;
}
Everything else works the same way, and the type of distinctBar is [].

**Comment by donoftime2018** [comment]
import * as mongoose from 'mongoose';
import { type } from 'os';

interface Foo {
  bar: String;
  bar_num: Number;
}

const FooModel = mongoose.model<Foo>('Foo', new mongoose.Schema({ bar: [String], bar_num: [Number] }));

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  await FooModel.create({ bar: ['a', 'b'], bar_num: [0, 2]})
  await FooModel.create({ bar: ['c','d'], bar_num: [1, 2] });
  await FooModel.create({ bar: ['e','f'], bar_num: [5]})

  const distinctBar = await FooModel.distinct('bar');
  const distinctBars = await FooModel.distinct('bar_num');
  console.log(distinctBar); // [ 'a', 'b', 'c', 'd', 'e', 'f' ]
  console.log(distinctBars); // [0, 1, 2 5]
 //distinctBar is String[] and distinctBars is Number[]
}

run();


The inferred types are String[] and Number[] after removing the array brackets from interface Foo
