### ISSUE TITLE
"this" context has "any" type in Schema methods option

### ISSUE THREAD

**Issue by ruxxzebre** [Automattic/mongoose#14027]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.0 (same case as 7.2.2)

### Node.js version

20.5.0 (same case as 18.0.0)

### MongoDB server version

7.0

### Typescript version (if applicable)

5.2.2 (recently updated, same case with 4.8.4)

### Description

As stated [here](https://github.com/Automattic/mongoose/issues/13800#issuecomment-1789367289), issue with _this_ context was fixed, if we declare methods like this:
```ts
schema.method("fullName", function fullName() {
    return this.firstName + " " + this.lastName;
});
``` 

**But**, if we're trying to specify methods in schema's _method_ option AND provide IUserMethods into a Schema generic, _this_ becomes _any_ once again.

```ts
new Schema<IUser, UserModel, IUserMethods>
```

<img width="451" alt="Screenshot 2023-11-01 at 20 05 27" src="https://github.com/Automattic/mongoose/assets/54982966/4b73c3be-cfce-4c8b-97ab-447d308fed93">

However, If we **do not** provide IUserMethods into a Schema generic, _this_ becomes a Document type, as it should.

```ts
new Schema<IUser, UserModel>
or
new Schema<IUser, UserModel, {}>
```

<img width="442" alt="Screenshot 2023-11-01 at 20 06 26" src="https://github.com/Automattic/mongoose/assets/54982966/4b12aaf6-f13d-473c-8594-c6fb41c58aff">

@pshaddel thanks!

### Steps to Reproduce

Declare types/interfaces for document, methods and model.
```ts
interface IUser {
    firstName: string;
    lastName: string;
}

// Put all user instance methods in this interface:
interface IUserMethods {
    fullName(): string;
}

// Create a new Model type that knows about IUserMethods...
type UserModel = Model<IUser, {}, IUserMethods>;
```

Initialise schema with methods, **but** without third generic type, and observe the result.
```ts
const schema = new Schema<IUser, UserModel>(
    {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
    },
    {
        methods: {
            fullName() {
                return this.firstName + " " + this.lastName;
            },
        },
    }
);
```

Initialise schema with methods **and** third generic type (IUserMethods), and observe the result.
```ts
const schema = new Schema<IUser, UserModel, IUserMethods>(
    {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
    },
    {
        methods: {
            fullName() {
                return this.firstName + " " + this.lastName;
            },
        },
    }
);
```

### Expected Behavior

Methods declared in Schema's options.methods should infer **_this_** with a right type, including provided interface for methods.

**Comment by pshaddel** [comment]
@ruxxzebre Quick workaround:

If you do not pass `IUserMethods` to the Schema the typing is working(you are passing methods to the Model)!
```typescript
const schema = new Schema<IUser, UserModel>(
    {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
    },
    {
        methods: {
            fullName() {
                return this.firstName + " " + this.lastName;
            },
        },
    }
);
```

**Comment by ruxxzebre** [comment]
> @ruxxzebre Quick workaround:
> 
> If you do not pass `IUserMethods` to the Schema the typing is working(you are passing methods to the Model)!
> 
> ```ts
> const schema = new Schema<IUser, UserModel>(
>     {
>         firstName: { type: String, required: true },
>         lastName: { type: String, required: true },
>     },
>     {
>         methods: {
>             fullName() {
>                 return this.firstName + " " + this.lastName;
>             },
>         },
>     }
> );
> ```

Yes It works, as stated in ticket. **However** methods are not appearing in _this_ at all.
<img width="482" alt="Screenshot 2023-11-01 at 21 53 56" src="https://github.com/Automattic/mongoose/assets/54982966/19a789a0-ec93-4daa-aece-44a7e13af00b">

**Comment by ruxxzebre** [comment]
> > @ruxxzebre Quick workaround:
> > If you do not pass `IUserMethods` to the Schema the typing is working(you are passing methods to the Model)!
> > ```ts
> > const schema = new Schema<IUser, UserModel>(
> >     {
> >         firstName: { type: String, required: true },
> >         lastName: { type: String, required: true },
> >     },
> >     {
> >         methods: {
> >             fullName() {
> >                 return this.firstName + " " + this.lastName;
> >             },
> >         },
> >     }
> > );
> > ```
> 
> Yes It works, as stated in ticket. **However** methods are not appearing in _this_ at all. <img alt="Screenshot 2023-11-01 at 21 53 56" width="482" src="https://user-images.githubusercontent.com/54982966/279786200-19a789a0-ec93-4daa-aece-44a7e13af00b.png">
> 
> The thing is that it's currently not possible to have access to typings of methods from other methods (if we're not speaking of schema.method(...))

Made a workaround for my project, looks like this: 
```ts
type AddThisParameter<T, Doc> = {
    [K in keyof T]: T[K] extends (...args: infer A) => infer R
        ? (this: Doc, ...args: A) => R
        : T[K];
};

type HydratedUserDocument = HydratedDocument<
    FlatRecord<IUser>,
    IUserMethods
>;

export const userSchema = new mongoose.Schema<
    IUser,
    UserModel,
    AddThisParameter<IUserMethods, HydratedUserDocument>
>(
```

**Comment by ruxxzebre** [comment]
@pshaddel created a [pull request](https://github.com/Automattic/mongoose/pull/14028) targeted to this specific issue.
Hoping it's appropriate!
