### ISSUE TITLE
timestamp not created from Schema

### ISSUE THREAD

**Issue by popeating** [Automattic/mongoose#14041]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.0

### Node.js version

20.9.0

### MongoDB version

6.0.11

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

when creating a basic schema, i enabled timestamps, but when saving new documents timestamps are not attached:
this is my schema:
```javascript
import { Schema, model, models } from 'mongoose';
const contactSchema = new Schema(
  {
    name: { type: String, required: true },
    email: { type: String, required: true },
  },
  { timestamps: true }
);
const Contact = models.contact || model('Contact', contactSchema);
export default Contact;
``` 
and this is how i save a new document:
```javascript
const contact = new Contact(data);
contact.save();
``` 

what am i missing?

**Comment by donoftime2018** [comment]
Try updating to a later version of MongoDB or Mongoose.

**Comment by donoftime2018** [comment]
my version of mongoose is 8.0.0
my version of mongodb is 6.2.0

**Comment by donoftime2018** [comment]
Or declaring timestamps is different in your version of Mongoose or MongoDb.

**Comment by donoftime2018** [comment]
In my mongoose schema I had to add the collection name in the same brackets at timestamps so maybe try that too.

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String,
  email: String
}, { timestamps: true });

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = new Test({ name: 'Test Testerson', email: 'test@localhost.com' });
  await doc.save();
  console.log('what is doc', doc);
}

run();
```
![image](https://github.com/Automattic/mongoose/assets/39510674/3c8b8e0a-901c-4cda-8079-b6e86543b5b0)

**Comment by donoftime2018** [comment]
Didn't even notice the lack of mongoose before Schema. But try checking the version of mongodb, mongoose, etc

**Comment by donoftime2018** [comment]
I reproduced the bug just now.

**Comment by vkarpov15** [comment]
@popeating how are you determining that timestamps aren't being attached?

**Comment by donoftime2018** [comment]
Try using getTimestamp()

**Comment by donoftime2018** [comment]
Try adding data using Contact.create. Contact isn't returning as a Mongoose model type on my end. You should probably look into how insertion works in Mongoose.
https://mongoosejs.com/docs/timestamps.html
