### ISSUE TITLE
InsertMany() throws dup key error

### ISSUE THREAD

**Issue by 39otrebla** [Automattic/mongoose#14043]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x.x, 8.x.x

### Node.js version

14.x, 16.x, 18.x

### MongoDB server version

5.x, 6.x

### Typescript version (if applicable)

4.x,5.x

### Description

The `insertMany()` method with `ordered: false` throws dup key error when the so-called unordered insert results in no row inserted (i.e. all entries throw dup key error).

### Steps to Reproduce

1. Create a collection with a unique index on the `code` field
2. Use insert many with `ordered: false` option to insert 10 different codes
3. Run the same operation of step 2) a second time, with the same 10 different codes
4. The operation will throw dup key error

### Expected Behavior

The operation should not throw, and just return the correct raw result (i.e. with `insertedCount: 0`), assuming the operation was run with `rawResult: true`.

**Comment by donoftime2018** [comment]
Can you show the code please?

**Comment by IslandRhythms** [comment]
I'm not sure what exactly is the problem. The script below will insert 10 documents the first run and on the second run inform that it could do it as it shows in the `insertedDocs` property to be an empty array, meaning nothing was inserted on that run.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  code: {
    type: String,
    unique: true
  }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  // await mongoose.connection.dropDatabase();

  const docs = [];

  for (let i = 0; i < 10; i++) {
    docs.push({ code: 'test'+i });
  }

  await Test.insertMany(docs, { ordered: false }).catch(err => console.log(err));
  console.log('done');
  console.log(await Test.find())
}

run();
```

**Comment by vkarpov15** [comment]
I took a closer look and this is expected behavior. With `ordered: false`, Mongoose will still throw an error if some writes failed. For example, in the following case, the 2nd `insertMany()` will still throw, even though one insert succeeded:

```javascript
  const docs = [];

  for (let i = 0; i < 2; i++) {
    docs.push({ code: 'test'+i });
  }

  const res = await Test.insertMany(docs, { ordered: false });
  console.log('first', res);
  // Throws MongoBulkWriteError
  const res2 = await Test.insertMany([{ code: 'test1' }, { code: 'test2' }], { ordered: false });
  console.log('second', res2);
```

This is an intentional design decision: when it comes to bulk operations (`bulkWrite()`, `insertMany()`, `syncIndexes()`, etc), Mongoose throws if it can't complete the full bulk operation as specified.
