### ISSUE TITLE
Trouble with TypeScript Type Inference on Mongoose Model Creation

### ISSUE THREAD

**Issue by HamzaLinge** [Automattic/mongoose#14061]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.0

### Node.js version

20.9.0

### MongoDB version

7.0.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

**Description:**
Hello Mongoose team,

I'm encountering an issue with TypeScript where the type inference is not working as expected when creating a Mongoose model with a defined interface. Despite following the TypeScript integration documentation, TypeScript is unable to infer the type from the usage of the model function. The error produced is _"Type argument cannot be inferred from usage"_.

**Environment:**

Node.js version: 20.9.0
Mongoose version: 8.0.0
TypeScript version: 5.2.2

**Code to Reproduce:**

> models/Subscriber.ts

```
import { Document, model, Schema } from "mongoose";

export interface ISubscriber extends Document {
  credentialsProvider: "Local" | "Google" | "Facebook";
  email: string;
  password?: string;

  firstName: string;
  lastName: string;
  phoneNumber: string;
  gender: "Male" | "Female" | "Other";

  birthday?: Date;
  picture?: string;
}

const subscriberSchema = new Schema<ISubscriber>(
  {
    credentialsProvider: {
      type: String,
      enum: ["Local", "Google", "Facebook"],
      required: true,
    },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: false },

    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    phoneNumber: { type: String, required: true },
    gender: { type: String, enum: ["Male", "Female", "Other"], required: true },

    birthday: { type: Date, required: false },
    picture: { type: String, required: false },
  },
  { timestamps: true }
);

const SubscriberModel = model<ISubscriber>("Subscribers", subscriberSchema);

export default SubscriberModel;
```

> tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "Node",
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "strictNullChecks": false
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}
```

When hovering over SubscriberModel, my IDE indicates that the model's type is inferred as ` Model<unknown, unknown, unknown, unknown, Document<unknown, unknown, unknown> & MergeType<unknown extends {_id?: infer U} ? IfAny<U, {_id: Types.ObjectId}, Required<{_id: U}>> : {_id: Types.ObjectId}, unknown>, ISubscriber>`, and when attempting to use `SubscriberModel.create()`, TypeScript does not recognize the type returned by `SubscriberModel`, despite having the `ISubscriber` interface defined and used in `model<ISubscriber>`.

Thank you for your time and assistance.

**Comment by vkarpov15** [comment]
The `Subscriber.ts` file you provided compiles without error. Is there a TypeScript issue you're seeing? Because it looks like "Type argument cannot be inferred from usage" is a webstorm error, and we currently don't debug IDE type preview issues.

**Comment by HamzaLinge** [comment]
Indeed, I'm using WebStorm and `Subscriber.ts` compiles normally. So I conclude that the error displayed and the fact that there is no autocompletion for my SubscriberModel when I import it elsewhere is due to WebStorm.

**Comment by vkarpov15** [comment]
In that case we're going to close this issue. Debugging IDE autocomplete is very tricky and not something we're likely to figure out in a reasonable amount of time.
