### ISSUE TITLE
TypeError: XXX.findByIdAndRemove is not a function

### ISSUE THREAD

**Issue by dannysunyu** [Automattic/mongoose#14060]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.0

### Node.js version

18.15.0

### MongoDB server version

MongoDB Atlas

### Description

Calling `XXX.findByIdAndRemove` throws a TypeError with `TypeError: XXX.findByIdAndRemove is not a function`.
However, calling `XXX.findByIdAndDelete` works.  The error is found only in mongoose v8.0.0, whereas in v7.6.3, there's no such error.

### Steps to Reproduce

Just call findByIdAndRemove on a model.

### Expected Behavior

The invocation succeeds and no error is thrown.

_No response_

**Comment by sean-daley** [comment]
https://github.com/Automattic/mongoose/blob/master/docs/migrating_to_8.md#removed-findoneandremove

While that references `findOneAndRemove` and not `findByIdAndRemove` I'm assuming the same thing is applicable to that call as well. Though the maintainers can answer that more clearly and maybe update the migrating guide accordingly.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  console.log(mongoose.version);
  const doc = await Test.create({ name: 'Test Testerson' });
  console.log(await Test.findOne());
  await Test.findByIdAndRemove(doc._id);
  console.log(await Test.findOne());
  console.log('done');

}

run();
```

**Comment by vkarpov15** [comment]
This is expected, we removed findByIdAndRemove in Mongoose 8.

**Comment by Alucard2169** [comment]
`findByIdAndRemove` is no longer available as stated by @vkarpov15

you can use `findByIdAndDelete` instead.

here is the migration guide: [mongoosejs.com](https://mongoosejs.com/docs/migrating_to_8.html)
