### ISSUE TITLE
Handling same schema in both databases while migrating data

### ISSUE THREAD

**Issue by noghartt** [Automattic/mongoose#14069]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.3

### Node.js version

18.16.0

### MongoDB version

5.8.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.0

### Issue

I'm planning to have a kind of _data migration_ around my database. In case, to avoid downtime, one of the strategies that I think was to have the same collection/schema in both databases while migrating, to ensure the data consistency of both databases in that period.

For this scenario, where I have two databases, where we'll call A and B, I would like to do it:

- For write operations, I would like to write first in A and after it on B. My idea is to have a `pre` hook that handle it for me. Is that the best way to do it? Is there any clever way or a suggestion of how to do it?
- For read operations, I would like to read in both A and B in parallel, the first one that finishes will come back with my result. Does it make sense? Is there a way to do it?

I'm implementing it first using the `useDb` feature accordingly to this documentation [here](https://mongoosejs.com/docs/connections.html#multi-tenant-connections).

Is there any suggestion/resource that I can read about this scenario too?

**Comment by chumager** [comment]
Hi, first of all:
- Do you need to migrate physically?
- Are you using replica set?
- Your DB is on premise or Atlas?

If you need to use 2 DB and accomplish a migration, that's one thing, but to read in parallel looks like you need a replica. 
What do you mean "to avoid downtime"? don't you have to make a deployment of your app to make the changes you want? that has a downtime.

Going to your points, and to avoid data lost, you need to use 2 different connections, and two face commit, mongoose and mongodb connector have native two face commit, so first you need to put all your inserts in a transaction wrapper, and in all schemas add a plugin with a post save hook that extract you model and uses the "other" model (DB B) to save the operation, if the save or update in DB B fails all the operation will fail.

in Atlas, mongodb version 7 allows you to keep 2 DBs replicated, and is exactly for migration purposes.

you can use some pseudocode like this:
```js
import mongoose from "mongoose";
const DBa = await mongoose.createConnection("mongodb://localhost/dba");
const DBb = await mongoose.createConnection("mongodb://localhost/dbb");
//create your schemas with DBa and then use DBa.model(<modelName>, schema) and DBb.model(<modelName>, schema);
//your first plugin
DBa.plugin(schema => {
  schema.pre("save", async function () {
    let session;
    this.$locals.hasSession = true;
    if (!this.$session()) {
      //We have no session so create one.
      this.$locals.hadSession = false;
      session = await DBa.startSession();
      session.startTransaction();
      this.$session(session);
    }
  });
  schema.post("save", async function () {
    try {
      await DBb.model(this.constructor.modelName).create(this);
      if (!this.$locals.hadSession) {
        await this.$session().commitTransaction();
        await this.$session().endSession();
      }
    } catch (e) {
      if (!this.$locals.hadSession) {
        await this.$session().abortTransaction();
        await this.$session().endSession();
      }
      throw e;
    }
  });
});
```
with this approach you can use an external session like ```await db.connection.transaction(session=>{...})``` and then assign the session to your "find" or "docs" to keep them from get written before transaction finishes, but if you ain't use it, the transaction will operate by default.

Don't know why query in parallel if you are migrating, again... that's sound like you need a replica set.

**Comment by noghartt** [comment]
Hey, asking your questions:

> Do you need to migrate physically?

Not for now. In my current scenario, I'm only migrating from a specific database to another in the same server. Just distributing the storages.

> Are you using replica set?

Yes, I'm using a replica set for my current DB.

> Your DB is on premise or Atlas?

It's on premise.

---

I like this approach to be honest. As I said, I was thinking to use the pre hooks to ensure that everything will be accordingly to the write operation. I'll try it, thanks.

> Don't know why query in parallel if you are migrating, again... that's sound like you need a replica set.

I was thinking on a parallel way because, by the fact that is a data migration between databases, I would like to have the `DbA` as a fallback for the rows/queries that can't be found on the `DbB`. I don't know if it's make sense, but I was thinking that could be a way to be more resilient for a scenario where we can't find a specific data.

Maybe only doing the query on the `DbA` while not finishing the migrating and having a kind of feature flag can be another approach on it, like a roll-out migration.

**Comment by chumager** [comment]
Hi, I recommend to have a dynamic configuration (something like in the DBs) to tell the app where to do the query, and it could be an array if you want to do it like ```Promise.race```.
To avoid asking every time (witch will introduce some lag), you can use a watcher, with an initial query to keep the configuration updated. Just beware to recall the watcher in case of lost connection or some errors, obviously with a fallback just in case :D

**Comment by vkarpov15** [comment]
We don't have any documentation about the particular scenario of migrating data from one database to another. But the approach you suggested; using a pre hook to ensure writes to go both databases and reads happen from both; is reasonable.
