### ISSUE TITLE
Insufficient checks when creating a schema

### ISSUE THREAD

**Issue by gardenBanter** [Automattic/mongoose#14063]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.x

### Node.js version

18.13.x

### MongoDB server version

6.0.x

### Typescript version (if applicable)

5.2.x

### Description

I'm running Mongoose with Typescript. I noticed that creating a new schema passes even with incorrect parameters. I had made a typo during development and then out of curiosity tested if the program still works, and it does!

### Steps to Reproduce

I made a typo here, with "rquired" instead of "required":

```
const DataSchema = new Schema<Data>({
  name: { type: String, rquired: true},
  description: { type: String, required: false}
})
```

The program continued working and didn't inform me of this at all, leaving me to think that I correctly marked the field as required. I think that the constructor should throw an exception or let me know in some other way.

**Comment by vkarpov15** [comment]
This is by design. Mongoose plugins often use custom schematype options, so we don't have a good way of saying "these are all the supported schematype options"
