### ISSUE TITLE
Is mongoose version 8.0 compatible with mongoDB server version 4.2?

### ISSUE THREAD

**Issue by aikms-maker** [Automattic/mongoose#14064]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.0

### Node.js version

18

### MongoDB version

4.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18.04.6

### Issue

Is mongoose version 8.0 compatible with mongoDB server version 4.2?

I couldn't find the answer in the documentation, so please let me know.

**Comment by donoftime2018** [comment]
The latest mongodb version is 7.0, so I wouldn't know.

**Comment by vkarpov15** [comment]
Yes. We need to update our compatibility docs: https://mongoosejs.com/docs/compatibility.html

**Comment by aikms-maker** [comment]
Thank you very much, that helped a lot.
