### ISSUE TITLE
Lazy connection handling while registering new models

### ISSUE THREAD

**Issue by noghartt** [Automattic/mongoose#14089]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.3

### Node.js version

18.16.0

### MongoDB version

5.8.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.0

### Issue

I have a monorepo where I handle 2+ connections accordingly to the entrypoints.

In case, I have a specific flow where a model registered via `mongoose.model` runs before the connection to the DB.

```ts
// packages/A/Model.ts
// ...
const model = mongoose.model('Model', ModelSchema);
```

If a try to do something like: `connection.model('Model', ModelSchema)`, it throws an error because `connection` is undefined until connnect.

```ts
// packages/A/Model.ts
// ...
import { getConnection } from '@packages/mongodb';

const connection = getConnection('OtherDatabase'); // get connection accordingly to the `mongoose.connections`

const model = connection.model('Model', ModelSchema);
```

I would like to know if there's a way/strategy to handle this kind of _"model registry"_ in a multi DB architecture allowing this lazy code evaluation.

**Comment by sibelius** [comment]
can we be able to define the collection name and the database name in the SchemaModel ?

Schema.collectionName = 'ok':
Schema.databaseName = 'another-database';

**Comment by sibelius** [comment]
if have something like this

```
export const getConnection = (connectionName: string) => {
  const connection = mongoose.connections.find(
    (c) => c.name === connectionName,
  );

  if (!connection) {
    return mongoose;
  }

  return connection;
};

export const getModelBySchema = (schema: SchemaMultiDB) => {
  const connection = getConnection(schema.databaseName);

  return connection.model(schema.name, schema);
};
```

the usage is

```
const Event = getModelBySchema(EventSchema);
```

We would like to keep using just `EventModel` instead of having a lazy function to get the model from a custom connection

**Comment by vkarpov15** [comment]
@sibelius that patterns works as well. It's not my favorite pattern, but it's the only real option if you have multiple connections and want to be able to import models via `require()` / `import`.
