### ISSUE TITLE
Long not casted BigInt while performing query with lean option

### ISSUE THREAD

**Issue by jerkly** [Automattic/mongoose#14093]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.1

### Node.js version

18.17.1

### MongoDB server version

5.0.19

### Typescript version (if applicable)

5.2.2

### Description

Field with BigInt type not casted from mongodb Long to bigint, when lean option is used in query.

### Steps to Reproduce

```typescript
interface DataDoc {
    testValue: bigint;
}

const dataSchema = new mongoose.Schema<DataDoc>({
    testValue: { type: mongoose.Schema.Types.BigInt },
});

const DataModel = mongoose.model<DataDoc>('Data', dataSchema);
```

```typescript
await DataModel.create({ testValue: 1000n });
 
// Works not correctly.
const doc2 = await DataModel.findOne().lean().exec();
console.log(typeof doc2!.testValue); // print 'number' instead of 'bigint'
```

```typescript
// Works correctly.
const doc1 = await DataModel.findOne().exec();
console.log(typeof doc1!.testValue); // print 'bigint'
console.log(typeof doc1!.toJSON().testValue); // print 'bigint'
```

### Expected Behavior

type of `testValue` expected to be `bigint`

**Comment by vkarpov15** [comment]
This is expected behavior, [lean tells Mongoose to skip all hydrating, casting, etc.](https://mongoosejs.com/docs/tutorials/lean.html); so Mongoose won't explicitly hydrate longs into BigInts.

That being said, you can tell the MongoDB node driver to convert longs into BigInts using the `useBigInt64` option to `connect()` as follows:

```javascript
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test', { useBigInt64: true });

  const schema = new mongoose.Schema({ num: 'BigInt' });
  const Test = mongoose.model('Test', schema);

  await Test.deleteMany({});
  await Test.create({ num: 42n });
  console.log(await Test.findOne().lean()); // `num` will be `42n` because of `useBigInt64`
```
