### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Ronald-Lozano** [Automattic/mongoose#14091]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

1.0.1

### Node.js version

18.16.0

### MongoDB version

6.3.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10.0.22631.2715

### Issue

Buenas noches tengo un error y no he podido encontrar la solucion alguien q me pueda ayudar, este es el error q me aparece:

(node:4268) [MONGODB DRIVER] Warning: useNewUrlParser is a deprecated option: useNewUrlParser has no effect since Node.js Driver version 4.0.0 and will be removed in the next major version
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4268) [MONGODB DRIVER] Warning: useUnifiedTopology is a deprecated option: useUnifiedTopology has no effect since Node.js Driver version 4.0.0 and will be removed in the next major version

**Comment by Uzlopak** [comment]
its a warning not an error

**Comment by Ronald-Lozano** [comment]
> es una advertencia no un error

pero como lo puedo solucionar

**Comment by vkarpov15** [comment]
Busca por `useNewUrlParser` y `useUnifiedTopology` en su proyecto y quitarlo

```javascript
mongoose.connect(uri, {
  useNewUrlParser: true // <-- delete this line
});
```
