### ISSUE TITLE
Handling connection/model exceptions in a better way

### ISSUE THREAD

**Issue by noghartt** [Automattic/mongoose#14106]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.3

### Node.js version

18.16.0

### MongoDB version

5.8.0

### Operating system

None

### Operating system version (i.e. 20.04, 11.3, 10)

14.1.0

### Issue

I have an architecture handling multiple connections with mongoose. In case, assuming `db1` and `db2` as their names.

In some specific flows, if the `db2` break down (by a `ECONNREFUSED` or anything like that), it shouldn't break the entire flow when throwing the exception.

The easier way to handle it is using the `try/catch` solution, but _"in loco"_, every place that handle the second database should have a `try/catch` wrapper handling it.

I would like to know if there's a clever way/strategy to handle it using mongoose? Any suggestion? Idea? Something using the `connection.on` listener or something like that?

**Comment by vkarpov15** [comment]
I'm confused by what you mean by `db2` break down; can you provide some sample code that demonstrates what you're seeing?
