### ISSUE TITLE
Um tanto estranho

### ISSUE THREAD

**Issue by bartomsilva** [Automattic/mongoose#14107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

nesse trecho de código tive que seguir uma sugestão do CHATGPT para contornar algo, tratar como erro uma busca de id inválido, um retorno de null ou [] indicaria que não foi encontrado mas disparar um erro? eu gostaria de tratar se não encontrei seguir com meu código como outras posibilidades e não cair em um catch castrando minha aplicação.

```
router.get("/:id", async (req, res) => {
  try {
    const idPerson = req.params.id;
    
    const people = await Person.findOne({ _id: idPerson });

    if (!people) {
      return res.status(404).json({ error: "Pessoa não encontrada" });
    }

    res.status(200).json(people);
  } catch (error) {
    // Se a conversão para ObjectId falhar, a consulta resultará em um erro
    // Nesse caso, você pode tratar o erro como uma indicação de que o ID não é válido
    if (error.name === 'CastError') {
      return res.status(400).json({ error: "ID inválido" });
    }

    res.status(500).json({ error: error.message });
  }
});
```

**Comment by vkarpov15** [comment]
Try `const person = await Person.findOne({ _id: idPerson }).orFail();`, that will make Mongoose throw an error if no person was found.
