### ISSUE TITLE
Model.bulkWrite function never returns on empty ops param and options.ordered = false

### ISSUE THREAD

**Issue by doomhz** [Automattic/mongoose#14117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

Introduced in **v6.11.3**.
Can be reproduces in all other higher versions up to the latest version to date (**v8.0.1**) .

### Node.js version

18.0

### MongoDB server version

5.0

### Description

The `Model.bulkWrite` function broke after [this fix was merged](https://github.com/Automattic/mongoose/issues/13176).

The `bulkWrite` function never returns when `ops = []` and `options = { ordered: false }`, since the check for `if (ops.length === 0) { return cb(null, getDefaultBulkwriteResult()); }` was moved inside the new `if (ordered) {` block.

A potential solution would be to move the empty `ops` array check above the new `if` block and return early from the callback function.

### Steps to Reproduce

Execute `Model.bulkWrite([], { ordered: false })` for any model. The Node process would get stuck in an endless loop and eventually time out.

### Expected Behavior

Early return `cb(null, getDefaultBulkwriteResult());` from the `Model.bulkWrite` on empty `ops` array param.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');


const testSchema = new mongoose.Schema({
  name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.bulkWrite([], { ordered: false });
  console.log('done');
}

run();
```
