### ISSUE TITLE
Can't prevent subdocument timestamps update with query options

### ISSUE THREAD

**Issue by Bl4sio** [Automattic/mongoose#14111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.5

### Node.js version

16.20.2

### MongoDB server version

4.4.1

### Typescript version (if applicable)

5.3.2

### Description

I have a main schema and a subschema, both has timestamps enabled.
When I update the subschema in a document with the timestamps option set to false, the main's timestamps are not updated, but the subdocument's timestamps are.

### Steps to Reproduce

```
import mongoose from "mongoose";

const SubSchema = new mongoose.Schema(
  {
    subId: {
      type: Number,
    },
    comment: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);

const MainSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    subDoc: {
      type: SubSchema,
    },
  },
  {
    timestamps: true,
  }
);

const Main = mongoose.model("Main", MainSchema);

Main.create({
  name: "first",
  subDoc: {
    subId: 1,
    comment: "a",
  },
});


setTimeout(()=>{
  const updatedDoc = {
    subId: 1,
    comment: "aa",
  };
  
  Main.findOneAndUpdate(
    {
      name: "first",
    },
    {
      $set: {
        subDoc: updatedDoc,
      },
    },
    {
      timestamps: false,
    }
  );

}, 1000)
```

### Expected Behavior

The subdoc updatedAt should not be updated on the findOneAndUpdate call.

**Comment by Bl4sio** [comment]
The findOneAndUpdate returns the original document, if you want to get the updated version, you have to add "new: true"
```  const res = await Main.findOneAndUpdate(
    {
      name: "first",
    },
    {
      $set: {
        subDoc: updatedDoc,
      },
    },
    {
      timestamps: false,
      new: true
    }
  );
```
But in both case the result in the DB will be the same, and the timestamps will be updated under the subdocument.

**Comment by vkarpov15** [comment]
Unfortunately this has to be expected behavior; there is no way to overwrite the entire `subDoc` property but retain just the previous subdoc's timestamps using `findOneAndUpdate()`. You should use `save()` instead:

```javascript
doc.subDoc.set(updatedDoc);
await doc.save();
```
