### ISSUE TITLE
Use Vector in Mongoose schema 

### ISSUE THREAD

**Issue by PeterPilley** [Automattic/mongoose#14121]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.7.3

### Node.js version

16.4

### MongoDB version

5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Issue

I am trying to find appropriate docs on how to use vectorsearch with Mongoose and mongodb atlas.

How do you define the vector field in the schema?

**Comment by vkarpov15** [comment]
`myVector: { type: [Number] }`, can add optional validation to check the array length like `myVector: { type: [Number], validate: v => v.length === 1536 }`.
