### ISSUE TITLE
Support changeStreamPreAndPostImages on Schema

### ISSUE THREAD

**Issue by FiveOFive** [Automattic/mongoose#14127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

MongoDB 6 added support for pre and post images in change stream events. Per the [documentation ](https://www.mongodb.com/docs/v6.0/changeStreams/#change-streams-with-document-pre--and-post-images) _"Enable changeStreamPreAndPostImages for a collection using [db.createCollection()](https://www.mongodb.com/docs/v6.0/reference/method/db.createCollection/#mongodb-method-db.createCollection), [create](https://www.mongodb.com/docs/v6.0/reference/command/create/#mongodb-dbcommand-dbcmd.create), or [collMod](https://www.mongodb.com/docs/v6.0/reference/command/collMod/#mongodb-dbcommand-dbcmd.collMod)"_

I'd like to set the `changeStreamPreAndPostImages` on mongoose Schemas so that the collections are automatically created or updated with the correct pre and post image settings.

**Comment by vkarpov15** [comment]
You should use `new Schema({}, { collectionOptions: { changeStreamPreAndPostImages: { enabled: true } } })`, here's some [docs on `collectionOptions`](https://mongoosejs.com/docs/guide.html#collectionOptions). `collectionOptions` is meant to be a catch all for additional arguments to pass to `createCollection()`, so Mongoose doesn't need to duplicate support for every `createCollection()` option.

**Comment by anantanandgupta** [comment]
i have below schema definition and i am not able to see the effect of that option. I have to run collmod command on the collection manually to make it work. I am not sure what i am doing wrong here.

```JS
const message = new mongoose.Schema({
    text: String,
    status: String,
}, {
  collectionOptions: {
    changeStreamPreAndPostImages: { enabled: true }
  }
});
```

I am not able to see value in `fullDocumentBeforeChange`. it is always returning `null` for that field. Once I run the `collmod` command manually on each collection I am interested in watching, the change stream triggers without tha information.

Regards, 
Anant Anand Gupta

PS. I am using latest version of mongoDB cluser mode setup using docker and latest mongoose npm package.

**Comment by vkarpov15** [comment]
@anantanandgupta `changeStreamPreAndPostImages` needs to be set when the collection is created, or using `collmod`. Setting `changeStreamPreAndPostImages`, and `collectionOptions` in general, won't have any effect if the corresponding MongoDB collection already exists. `collectionOptions` is just what Mongoose uses to determine which options to pass to `createCollection()`.
