### ISSUE TITLE
$gte with $lte not working with Mongoose 8.0.1 or 6.8.2

### ISSUE THREAD

**Issue by HermanBergsholm** [Automattic/mongoose#14122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.1

### Node.js version

20.0.2

### MongoDB server version

5.0.3

### Description

I am unable to use the operaters "$lte" and "$gte" together with Mongoose. I have tried all sort of different approaches to make it work, and the only way I have found to enable retrieving documents between a certain timespan, is to combine the following: 

- Query using collection directly instead of DB-model (e.g. `collection.find()` and not `Users.find()`).
- While also only using format `YYYY-MM-DD` without hours, minutes or seconds - as a string value, not a Date-object.

It should be possible to specify a more specific date-range than by the day at most, and I should also be able to use my model. 

### Steps to Reproduce

Docker-compose: 

```docker
  data-receive-mongodb:
    image: mongo:5.0.3
    container_name: "data-receive-mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
    volumes:
      - data-receive-mongodb:/data/db
      - ./files/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 7201:27017
 ```

MongoDB example doc:
```
{
    _id: ObjectId(<value>),
    projectUUID: 'ffffffff-ffff-ffff-ffff-d1ee4772f595',
    createdAt: '2023-11-06T08:09:07.000Z',
}
```

Relevant part of the "Entity" DB-model
```
    createdAt: {
      type: Date,
      default: null,
      required: true,
      min: "2020-01-01",
      max: "2030-01-01",
    },
 ```

 Node.js - using DB model `Entity.js` (not working): 
 ```js
const query = {
  projectUUID: "ffffffff-ffff-ffff-ffff-d1ee4772f595",
  // Neither of the following works for me:
  createdAt: { $gte: "2023-11-01", $lte: "2023-11-30" },
  // { $gte: new Date("2023-11-01"), $lte: new Date("2023-11-30") },
  // { $gte: new Date("2023-11-01T00:00:00Z"), $lte: new Date("2023-11-30T00:00:00Z") },
  // My DB is using ISOString, but the following doesn not help:
  // { $gte: new Date("2023-11-01").toISOString(), $lte: new Date("2023-11-30").toISOString() },
}

const result = await Entity.countDocuments(query)

console.log(result)
// Output is 0
```

I have found one work-around, but this disables the possibility to specify hours, minutes and seconds - and I also have to create an instance of the collection and query with this directly, instead of using the DB model which is normally used for queries against these documents. Here's an example of what works: 

Node.js - creating instance of MongoDB connection and query collection directly, with date-time format restricted to `YYYY-MM-DD`:
```js
import { mongooseConnection } from "../../../db/connection.js"

const query = {
  projectUUID: "ffffffff-ffff-ffff-ffff-d1ee4772f595",
  // The one below returns correct number of documents:
  createdAt: { $gte: "2023-11-01", $lte: "2023-11-30" },
  // The following examples all return 0 using the collection-method:
  // { $gte: new Date("2023-11-01"), $lte: new Date("2023-11-30") },
  // { $gte: new Date("2023-11-01T00:00:00Z"), $lte: new Date("2023-11-30T00:00:00Z") },
  // { $gte: new Date("2023-11-01").toISOString(), $lte: new Date("2023-11-30").toISOString() },
}

const collection = mongooseConnection.collection("myCollectionName")

const result = await collection.countDocuments(query)
console.log(result)
// Output is correct number of documents which are createdAt between the dates in $gte and $lte
```

I have multiple schemas and models in the same collection. There's about 5 different types of documents in this one collection. I don't know if this matters. Appreciate any help, I've tried everything... 

### Expected Behavior

The expected behavior is that Mongoose should be able to execute a `countDocument()` query with `$gte` and `$lte` , using DB-models rather than querying the entire collection, and return the correct amount of documents matching the filter passed to the `countDocuments()`-function.

**Comment by vkarpov15** [comment]
It looks like createdAt is a string in your database but your schema specifies that createdAt is a date. Which means Mongoose casts all your date strings to dates in your query filter. That means the query Mongoose is executing is looking for docs where createdAt is a date between the two provided dates, which doesn't match any documents where createdAt is a string.

set createdAt to type: String in your query and it should work fine

**Comment by HermanBergsholm** [comment]
Oh, thanks, I did not catch that! The reason is because it is not supposed to be, all my documents up to a certain point used `ISODate(.....)`, and I am still creating the documents using `createdAt: new Date().toISOString(),` so somewhat strange that they are no longer ISODate. Maybe it's due to my version bump of mongoose I did during debugging of this issue.
