### ISSUE TITLE
`findByIdAndRemove` type overload with optional parameter removed in v7.6.6

### ISSUE THREAD

**Issue by FloEdelmann** [Automattic/mongoose#14132]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.6

### Node.js version

18

### MongoDB server version

*irrelevant*

### Typescript version (if applicable)

5.3

### Description

In the update from mongoose 7.6.5 to 7.6.6, the function overload `findByIdAndRemove` with an optional `options` parameter was removed from `models.d.ts`: See https://app.renovatebot.com/package-diff?name=mongoose&from=7.6.5&to=7.6.6

This makes it impossible to call `findByIdAndRemove(id)` because TypeScript complains about a missing second parameter.

In https://github.com/Automattic/mongoose/blob/7.x/types/models.d.ts, the overload is removed, while it is still available in https://github.com/Automattic/mongoose/blob/7.6/types/models.d.ts. Unfortunately, I could not find the commit where this change was made.

### Steps to Reproduce

See above.

**Comment by FloEdelmann** [comment]
It was probably wrongly backported from v8: https://mongoosejs.com/docs/migrating_to_8.html#removed-findoneandremove

**Comment by vkarpov15** [comment]
I'm sorry about this issue, we have a fix in #14136, and we'll ship v7.6.7 with the fix once that PR is approved.
