### ISSUE TITLE
Incorrect return type for doc.findOneAndDelete()

### ISSUE THREAD

**Issue by asvendby** [Automattic/mongoose#14130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.2

### Node.js version

20.10.0

### MongoDB server version

6.2.0

### Typescript version (if applicable)

5.3.2

### Description

The return type for `doc.findOneAndDelete(...)` is of type `ModifyResult` while MongoDB returns the document

### Steps to Reproduce

See return type for MongoDB [here](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOneAndDelete/) and the type definition [here](https://github.com/Automattic/mongoose/blob/12c58921bb683acfa9c78a497a6f8e684ea5c368/types/models.d.ts#L613C24-L613C24)

### Expected Behavior

Expected that the return type is the document, not `ModifyResult`

**Comment by momenthana** [comment]
it was handled temporarily
```diff
- const session = await Session.findOneAndDelete({ sessionToken }) // return ModifyResult<SessionDocument>
+ const session = await Session.findOneAndDelete({ sessionToken }, {}) // return SessionDocument
```
