### ISSUE TITLE
Nested `$inc` is not working properly!

### ISSUE THREAD

**Issue by JawadAhbab** [Automattic/mongoose#14134]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.2

### Node.js version

20.8.0

### MongoDB server version

7.1.1 Atlas

### Description

Though I am using Typegoose, I think this is related to Mongoose actually.

Lets we have a document like this -
```json
{
  "count" : 0,
  "nested" : {
    "inside": {
      "count": 0
    }
  }
}
```

Now we will run this **`5 times simultaneously`** -
```ts
const test = await TestModel.findOne({ ... })
if (!test) throw new Error()

test.$inc('count', 1)
test.$inc('nested.inside.count', 1)
await test.save()
```

Although we are running this 5 times simultaneously with `$inc`. Both fields should be increased by 5. But I wonder, getting this result - 
```json
{
  "count" : 5,
  "nested" : {
    "inside": {
      "count": 1 → What? 🙄
    }
  }
}
```

Don't know why but nested field `'nested.inside.count` has been increased just once. On the other hand `count` is increased by 5 as expected.

Any Clue?

### Steps to Reproduce

...

### Expected Behavior

Should be -
```json
{
  "count" : 5,
  "nested" : {
    "inside": {
      "count": 5 → Expected
    }
  }
}
```

**Comment by IslandRhythms** [comment]
I have two terminals open running the script at the same time and it was incrementing as expected. Please provide how you were running the script simultaneously.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  count: Number,
  nested: {
    inside: {
      count: Number
    }
  }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  // await mongoose.connection.dropDatabase();

  await Test.create({
    count: 0,
    nested: {
      inside: {
        count: 0
      }
    }
  });

  const doc = await Test.findOne();
  doc.$inc('count', 1);
  doc.$inc('nested.inside.count', 1);
  await doc.save();

  console.log(await Test.findOne());
  console.log('done');
}

run();
```
