### ISSUE TITLE
Performance Issue with Mongoose 7.4.0 on Large Document Insertions

### ISSUE THREAD

**Issue by ht-jo** [Automattic/mongoose#14148]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

7.4.0

### Slowed down in version

7.4.0

### Node.js version

20.3.0

### 🦥 Performance issue

Hello,

I am currently using Mongoose version 7.4.0 in a NestJS API server and I've encountered a performance issue that seems to involve the V8 engine's event loop being occupied when inserting large documents. This issue intermittently arises when large documents are inserted using Model.create(). It appears that the event loop gets occupied during these insertions. For instance, other requests are processed simultaneously only after the completion of the document insertion, suggesting that Model.create() might be blocking in the V8 event-loop single-thread environment.

The document causing issues typically looks like this and is a result of OCR recognition. It contains a words array field with more than 500 elements:

```json

{
  "raw": {
    "words": [
      {
        "id": 1,
        "isVertical": false,
        "text": "[",
        "confidence": 0.9968
      },
      // ... more words
    ]
  }
}

```
Benchmarking the performance of Model.create for this operation takes approximately 1.8 seconds.

As a temporary workaround, I am considering separating Model.validate() and the native MongoDB insert operation, which each take about 0.2 seconds and seem to not block the V8 event loop (this modification is yet to be implemented).

Could you provide any insights into what operations within Model.create() might be causing prolonged occupation of the single thread?

Thank you for your assistance.

### Steps to Reproduce

You can roughly check this with the performance measurements below. If you need more explanation regarding reproduction, please leave a comment.

```ts
    // const ocrDate = { } // input data
    perfObserver.observe({ entryTypes: ['measure'], buffered: true })

    const Model = rootModule.get<Model<OCRData>>(getModelToken(OCRData.name))

    performance.mark('create-start')
    try {
      await new Model(ocrData).validate()
    } catch (e) {
      console.log(e)
    }

    // await Model.db.collection('receiptocrdata').insertOne(ocrData)
    // await Model.create(ocrData)
    performance.mark('create-end')

    performance.measure('create', 'create-start', 'create-end')
```

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script doesn't demonstrate anywhere near a 1.8 sec latency:

```javascript
import mongoose from 'mongoose';

console.log(mongoose.version);

await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
const schema = new mongoose.Schema({
  raw: {
    words: [{
      id: Number,
      isVertical: Boolean,
      text: String,
      confidence: Number
    }]
  }
});
const TestModel = mongoose.model('Test', schema);

const start = Date.now();
for (let i = 0; i < 100; ++i) {
  await TestModel.create({
    raw: {
      words: Array(1000).fill(0).map((_, i) => ({
        id: i,
        isVertical: i % 2 === 0,
        text: 'Test ' + i,
        confidence: Math.random()
      }))
    }
  });
}

console.log('Average runtime MS', (Date.now() - start) / 100);
```

Output:

```
$ node gh-14148.mjs 
7.6.7
Average runtime MS 81.38
^C

```

Can you please modify the above script to demonstrate the issue you're seeing?

**Comment by ht-jo** [comment]
@vkarpov15 

Thanks for your check. Actually, I was using `nestjs/mongoose`, but I thought it could be reproduced directly in mongoose. First of all, the code used in nestjs/mongoose is as follows. Many parts were obscured or modified for security reasons.

```ts
@Schema({ _id: false })
class RecognizedWord {
  @Prop()
  id!: number

  @Prop()
  isVertical!: boolean

  @Prop()
  text!: string

  @Prop()
  confidence!: number
}

@Schema({ _id: false })
export class OCRRawResult {

  @Prop({ type: [SchemaFactory.createForClass<RecognizedWord>(RecognizedWord)] })
  words?: RecognizedWord[]

}

export const OCRRawSchema = SchemaFactory.createForClass<OCRRawResult>(OCRRawResult)


@Schema({ collection: 'ocr', shardKey: { _id: 'hashed' } })
export class OCR {
  constructor(init: Partial<OCR>) {
    Object.assign(this, init)
  }

  @Prop({ type: OCRRawSchema })
  raw?: OCRRawResult

}

export const OCRSchema = SchemaFactory.createForClass<OCR>(OCR)

export const OCRModule = MongooseModule.forFeatureAsync(
  [
    {
      name: OCR.name,
      useFactory: () => {
        OCRSchema.index({ _id: 'hashed' }) // for shard
        return OCRSchema
      },
    },
  ]
)
```

This is the result of testing with the array creation code you commented.

```ts
const ocrData = {
  _id: new Types.ObjectId('6566d23a14ed5f3786151495'),
  raw: {
    words: Array(1000)
      .fill(0)
      .map((_, i) => ({ id: i, isVertical: i % 2 === 0, text: 'Test ' + i, confidence: Math.random() }))
  }
}
```

 It's taking over 5 seconds.

```console
    PerformanceMeasure {
      name: 'ocr data create',
      entryType: 'measure',
      startTime: 24868.98991727829,
      duration: 5167.230791091919
    }
```

If you remove the type definition from that part,

```ts
@Schema({ _id: false })
export class OCRRawResult {

  @Prop()
  words?: RecognizedWord[]

}
```

It's taking 450ms. This is acceptable considering the size it fits into. Regardless of whether it is blocking in nodejs single thread environment.

```console
    PerformanceMeasure {
      name: 'ocr data create',
      entryType: 'measure',
      startTime: 24334.886833190918,
      duration: 450.6204171180725
    }
```


I'm sorry that I didn't think it was an issue of `nestjs/mongoose` and immediately wrote an issue about mongoose. I want you to judge for me.

**Comment by vkarpov15** [comment]
I'm still unable to repro: please modify this GitHub project to demonstrate your issue https://github.com/vkarpov15/mongoose-14148. Here's the output on my machine:

```
$ ./node_modules/.bin/ts-node main.ts 
7.4.0
(node:7690) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Average runtime MS 87.12
^C
$ 
```
