### ISSUE TITLE
Monkey patching of ObjectId, but still undefined?

### ISSUE THREAD

**Issue by nicolas-urbantz** [Automattic/mongoose#14154]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.4

### Node.js version

20

### MongoDB server version

5.9.1

### Typescript version (if applicable)

5.1.6

### Description

Hello!

We are upgrading an old codebase from mongoose 5 to 7. I see that mongoose is monkey patching the "native" `ObjectId` by adding a `_id` attribute... But I'm wondering if the type is correct because in the code, I can see:

```
declare module 'bson' {
  interface ObjectId {
    /** Mongoose automatically adds a conveniency "_id" getter on the base ObjectId class */
    _id: this;
  }
}
```

while, in reality, it's undefined (see **steps to reproduce**).

I saw that [issue](https://github.com/Automattic/mongoose/issues/12537), but it doesn't answer my question :/

### Steps to Reproduce

This is my unit test:

```
import { ObjectId as MongoDBObjectId } from 'mongodb';
test('_id is undefined', () => {
	const objectId = new MongoDBObjectId('5b348a71fe5e561dd1c70628');
	expect(objectId._id).toBeUndefined();
});
```

### Expected Behavior

It passes, but shouldn't it fail? Or shouldn't the monkey patch say that `_id` could be undefined?

**Comment by vkarpov15** [comment]
`_id` won't be added as a property on `MongoDBObjectId` unless you import Mongoose. So your unit test failing looks expected, unless there's an `import 'mongoose'` somewhere.

**Comment by nicolas-urbantz** [comment]
Hey, thanks for your quick answer... I tried to run this then, and it passes:
- One test with the "native" ObjectId => Stil no _id
- One test with the ObjectId from mongoose => _id is present

```
import { ObjectId as MongoDBObjectId } from 'mongodb';
import mongoose from 'mongoose';

describe('Native ObjectId', () => {
	test('_id is undefined', () => {
		const objectId = new MongoDBObjectId('5b348a71fe5e561dd1c70628');
		expect(objectId._id).toBeUndefined();
	});
});

describe('mongoose ObjectId', () => {
	test('_id is undefined', () => {
		const objectId = new mongoose.Types.ObjectId(
			'5b348a71fe5e561dd1c70628'
		);
		expect(objectId._id).toBe(objectId);
	});
});

```

**Comment by nicolas-urbantz** [comment]
Up :) I add some clarification, but I don't know if/how I can remove the label @vkarpov15

**Comment by IslandRhythms** [comment]
Please modify the script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');
const { ObjectId } = require('mongodb');
let MongoDBObjectID = ObjectId;

const mongodbId = new MongoDBObjectID('5b348a71fe5e561dd1c70628');
console.log('what is mongodbId', mongodbId);

const mongooseObjectId = new mongoose.Types.ObjectId('5b348a71fe5e561dd1c70628');
console.log('what is mongoose object id', mongooseObjectId);
console.log(mongooseObjectId._id);
```

**Comment by vkarpov15** [comment]
I modified @IslandRhythms ' script slightly, but still not able to repro this issue:

```javascript
const mongoose = require('mongoose');
const { ObjectId } = require('mongodb');
let MongoDBObjectID = ObjectId;

const mongodbId = new MongoDBObjectID('5b348a71fe5e561dd1c70628');
console.log('what is mongodbId', mongodbId._id);

const mongooseObjectId = new mongoose.Types.ObjectId('5b348a71fe5e561dd1c70628');
console.log('what is mongoose ObjectId', mongooseObjectId._id);
```

Output:

```
$ node gh-14154.js 
what is mongodbId new ObjectId('5b348a71fe5e561dd1c70628')
what is mongoose ObjectId new ObjectId('5b348a71fe5e561dd1c70628')

```

@nicolas-urbantz can you please run `npm run list | grep "mongo"` and provide the output? I suspect you have a different version of the MongoDB Node driver than Mongoose.

**Comment by nicolas-urbantz** [comment]
Thanks, I'll have a look tomorrow 🫶

**Comment by nicolas-urbantz** [comment]
@vkarpov15 , you are right I think, we have another version. 

I copy/paste your script and here is my output:
```
what is mongodbId undefined
what is mongoose ObjectId new ObjectId("5b348a71fe5e561dd1c70628")
```

Output of `npm list`:

```
├── mongodb@5.9.1
├── mongoose@7.6.4
```

I see that mongoose is using `5.9.0` in the lock. Do you recommend to not install mongodb "manually", but then use the "mongodb of mongoose", if I want to call mongodb directly (without mongoose)?

**Comment by vkarpov15** [comment]
@nicolas-urbantz yes I'd recommend you use `require('mongoose').mongo`, or match your version of the `mongodb` package to Mongoose's.

**Comment by nicolas-urbantz** [comment]
Make sense!

Thank you for your time 🙏
