### ISSUE TITLE
What does it mean "Mongoose 7 no longer supports passing a document type that extends Document into Model<>"? (typescript)

### ISSUE THREAD

**Issue by vaclav-pruner** [Automattic/mongoose#14163]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.6.7

### Node.js version

18.17.0

### MongoDB version

5.9.1

### Operating system

None

### Issue

I'm migrating from mongoose 6.x to 7.6.7 and migration guide [states](https://mongoosejs.com/docs/7.x/docs/migrating_to_7.html#typescript-specific-changes)
```
Mongoose 7 no longer exports a LeanDocument type, and no longer supports passing a document type that extends Document into Model<>.
```
My code is full of types that do exactly that - they extend Document. But everything seems to work fine, typescript does not force me to change anything. And so I would like to know what it means - is it "only" a recommendation or is it a disaster waiting to happen?

I was trying it with typescript@4.7.4 and typescript@5.2.2 and both were fine.

**Comment by vkarpov15** [comment]
Can you provide an example of what your types look like?

The major difference is that Mongoose no longer tries to infer the lean type, so the most likely issue is that you'll get the fully hydrated document type back if you use `lean()` or `toObject()`.
