### ISSUE TITLE
Mongoose Connection hangs indefinitely after script is done unless `connection.close()` is called

### ISSUE THREAD

**Issue by Altair2169** [Automattic/mongoose#14165]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.3

### Node.js version

20.10.0

### MongoDB version

6.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Issue

I have a nodejs script running where I connect to MongoDB Atlas using Mongoose, read/write some data and then the script exits. The issue I am facing is that if I don't explicitly close the connection via `mongoose.connection.close()`, the script will run indefinitely until I force close it using CTRL + C. 

Is it advisable to explicitly run `connection.close()` to gracefully close the mongoose connection or is there something I am doing wrong?

Here's how my code looks like,

db.ts

```ts

import mongoose, { Schema } from 'mongoose';
import * as dotenv from 'dotenv';

dotenv.config();

export const connectToDB = async () => {
    const uri = process.env.MONGO_URI;
    if (!uri) {
        logger.error(
            'Mongo URL not found in env. Please add the url in the env file. Exiting....'
        );
        process.exit(1);
    }
    try{
        await mongoose.connect(uri, {
            retryWrites:true,
            writeConcern:{
                w:'majority'
            },
            user:process.env.MONGO_USR,
            pass:process.env.MONGO_PWD,
            dbName:process.env.MONGO_DB_NAME
        });
        logger.info('connected to DB')
    }catch(error:any){
        logger.error(error, "Error connecting to MongoDB, shutting down.....")
        process.exit(1)
    }
   
};

```
and my main.ts

```ts

import {connectToDB) from './db'

await connectToDB()

//code execution

console.log('script completed`) // it'll run indefinitely after logging it unless I stop it via CTRL+C

await mongoose.connection.close() //will stop the script as expected
```

**Comment by vkarpov15** [comment]
Yes, you should call `close()` to explicitly disconnect from the database. Mongoose will keep the connection to MongoDB open until you explicitly close it.
