### ISSUE TITLE
missing properties in mongoose.ConnectOptions types for ssl

### ISSUE THREAD

**Issue by rkreienbuehl** [Automattic/mongoose#14166]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

16.13.1

### MongoDB server version

6.0.7

### Typescript version (if applicable)

5.2.2

### Description

The types for `mongoose.ConnectOptions` seem to be missing the properties for `sslValidate`, `sslKey`, `sslCert` and `sslCA`.  After updating from mongoose 7 to mongoose 8 I am getting type errors that these properties do not exist on `mongoose.ConnectOptions`.

### Steps to Reproduce

Defining an object as `mongoose.ConnectOptions` and set properties `sslValidate`, `sslKey`, `sslCert` and `sslCA`.

**Comment by sean-daley** [comment]
My guess is this is due to the Mongo 6 driver update reported in the 8.x migration log? From what I can tell I see the following definition for ConnectOptions:
```
interface ConnectOptions extends mongodb.MongoClientOptions {
```

There is a separate Mongo readme about changes to the v6 driver here:
https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0

One of those changes is:
```
Deprecated SSL options have been removed
The following options have been removed with their supported counterparts listed after the ->

sslCA -> tlsCAFile
sslCRL -> tlsCRLFile
sslCert -> tlsCertificateKeyFile
sslKey -> tlsCertificateKeyFile
sslPass -> tlsCertificateKeyFilePassword
sslValidate -> tlsAllowInvalidCertificates
tlsCertificateFile -> tlsCertificateKeyFile
```

**Comment by rkreienbuehl** [comment]
Oh, I see. Thanks for the Info. Thought they are missing, because the documentation is still with these options.
