### ISSUE TITLE
how to bypass _id validation on insertMany and/or bulkWrite

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#14168]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.4

### Node.js version

20.0.0

### MongoDB server version

7.0.0

### Typescript version (if applicable)

5.2.2

### Description

I'm trying to use insertMany and bulkWrite to insert many items, but the _id has a this format

```jsx
{
    company: '656957a0b86bfdaa7e010e34',
    cohort: '2023-12',
    time: '2023-12'
  }
```

how can I bypass the validation of _id ?

```jsx
const result = await ModelInputed.bulkWrite(toBulk, {
      bypassDocumentValidation: true,
      forceServerObjectId: true,
    });

    const result = await ModelInputed.insertMany(documentListWithCompany, {
      throwOnValidationError: false,
    });
```

I got this error
```jsx
{
  err: Error: UserCube validation failed: _id: Cast to ObjectId failed for value "{
    company: '656957a0b86bfdaa7e010e34',
    cohort: '2023-12',
    time: '2023-12'
  }" (type Object) at path "_id" because of "BSONError"
      at ValidationError.inspect (node_modules/mongoose/lib/error/validation.js:50:26)
      ```

### Steps to Reproduce

```jsx
const items = [
{
 _id: {
     company: '656957a0b86bfdaa7e010e34',
    cohort: '2023-12',
    time: '2023-12'
    }
}
]

const result = await ModelInputed.bulkWrite(toBulk, {
      bypassDocumentValidation: true,
      forceServerObjectId: true,
    });

    const result = await ModelInputed.insertMany(documentListWithCompany, {
      throwOnValidationError: false,
    });
```

### Expected Behavior

it should be able to bypass _id

**Comment by IslandRhythms** [comment]
What does your schema definition look like? This should theoretically be possible. https://mongoosejs.com/docs/guide.html#_id

**Comment by IslandRhythms** [comment]
So if you follow the instructions in the link I sent, you need to define `_id` in your schema so that you can override it.
