### ISSUE TITLE
Product.findOne(...).toObject is not a function

### ISSUE THREAD

**Issue by dghub-founder** [Automattic/mongoose#14187]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

9.6.7

### MongoDB server version

000

### Typescript version (if applicable)

000

### Description

.toObject is not working

### Steps to Reproduce

 await Product.findOne().select([
        "-productType",
        "-casts",
        "-informations",
        "-categories",
        "-subCategories",
        "-horizontalListGroup",
        "-colors",
        "-sizes",
        "-brands",
        "-casts"
        ]).exec().toObject();

**Comment by donoftime2018** [comment]
https://stackoverflow.com/questions/62728153/toobject-is-not-a-function-error-while-converting-mongoose-object

According to this link, one potential fix is to loop through the array of data and run toObject on each element.

**Comment by donoftime2018** [comment]
Try upgrading your version of Node would be my first suggestion.

**Comment by vkarpov15** [comment]
@donoftime2018 is correct, the following returns a query instance, not a document 

```
Product.findOne().select([
"-productType",
"-casts",
"-informations",
"-categories",
"-subCategories",
"-horizontalListGroup",
"-colors",
"-sizes",
"-brands",
"-casts"
]).exec()
```

You would either need to do `(await Product.findOne()).toObject()` or `const doc = await Product.findOne(); doc.toObject()` or `await Product.findOne().then(doc => doc.toObject())`
