### ISSUE TITLE
Uncaught TypeError: ctx.cursor.next is not a function

### ISSUE THREAD

**Issue by gsmeria** [Automattic/mongoose#14188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.7

### Node.js version

16.20.2

### MongoDB version

5.9.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

Sonoma 14.2

### Issue

Hello!

I'm migrating from mongoose 6.11.3 to 7.6.7 and I'm encountering this error while using a cursor.

```
Uncaught TypeError: ctx.cursor.next is not a function
      at _next (/.../node_modules/mongoose/lib/cursor/QueryCursor.js:444:25)
      at QueryCursor._read (/.../node_modules/mongoose/lib/cursor/QueryCursor.js:121:3)
      at QueryCursor.Readable.read (node:internal/streams/readable:487:10)
      at resume_ (node:internal/streams/readable:987:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

As you can see the error comes from `QueryCursor.js` and it says `next` is not a function, when in the docs it clearly states that when using Query.prototype.cursor() it returns a QueryCursor -> [Returns a wrapper around a mongodb driver cursor). A QueryCursor exposes a Streams3 interface, **as well as a .next() function**](https://mongoosejs.com/docs/7.x/docs/api/query.html#Query.prototype.cursor())

Can somebody have a look at it? If there is a need for other technical details, please shout out.
Thanks!

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script works as expected. Please modify the following script to demonstrate the issue you're seeing.

```javascript
const mongoose = require('mongoose');

console.log(mongoose.version);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  await Model.deleteMany({});
  await Model.create([
    { name: 'Axl' },
    { name: 'Slash' }
  ]);

  const cursor = Model.find().sort({ name: 1 }).cursor();

  const expectedNames = ['Axl', 'Slash'];
  
  let cur = 0;
  cursor.on('data', function(doc) {
    console.log('Got', doc);
  });

  await new Promise((resolve, reject) => {
    cursor.on('error', function(error) {
      reject(error);
    });
  
    cursor.on('end', function() {
      resolve();
    });
  });

  console.log('Done');
  process.exit(0);
}
```

Output:

```
$ node gh-14188.js 
7.6.7
Got { _id: new ObjectId("658f4eda3668a824953aa40f"), name: 'Axl', __v: 0 }
Got {
  _id: new ObjectId("658f4eda3668a824953aa410"),
  name: 'Slash',
  __v: 0
}
Done
```
