### ISSUE TITLE
i cant get the stored data from mongoDB database

### ISSUE THREAD

**Issue by mohqaz** [Automattic/mongoose#14181]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.0

### Node.js version

18.18.0

### MongoDB version

6.0.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Issue

I am working on a project in which the user can create posts and can comment on them, and in the backend I created a schema model for the post and another for the comment, and when I comment on the post via the client side, the comment is created successfully and is stored in the database, but I cannot display the comments on the post page, and the error in the console is this
`{error: 'Cast to ObjectId failed for value "{ _id: undefined }" (type Object) at path "_id" for model "Post"'}` 

commentModel.js
```
import mongoose from "mongoose";
const ObjectId = mongoose.Types.ObjectId;

const commentSchema = mongoose.Schema({
    postId: {
    type: ObjectId,
    ref: "Post",
    required: true,
    },
    comment: {
        type: String,
        required: true,
    },
    replies: [{
        reply: {
            type: String,
            required: true,
        },
        username: {
            type: String,
            required: true,
        },
        commentId: {
            type: ObjectId,
            required: true,
        },
    }],
    username: {
        type: String,
        required: true,
    }
}, {
    timestamps: true
})

const Comment = mongoose.model('Comment', commentSchema);

export default Comment;
```

commentController.js

```
const getComments = async (req, res) => {
    const id = req.params;
    try {
        const post = await Post.findById( id )
        if (!post) {
            return res.status(404).json({ error: "Post Not Found!" })
        }

        const comments = await Comment.find({ postId: id }).sort({ createdAt: -1 })
        res.status(200).json(comments);
        
    } catch (error) {
        res.status(500).json({ error: error.message })
    }
}
```

**Comment by sean-daley** [comment]
If I had to take a guess, I'd say your problem is here:

```
const id = req.params;
```

I'm guessing that's undefined? I don't know what you're using for req/res ... express? But, regardless, you might want to make sure that's getting set correctly before getting passed to the mongoose findById call.

**Comment by mohqaz** [comment]
Comments in the frontend are called inside useEffect. Don't forget that the Controller function is intended to fetch comments only. I don't think I need req.

**Comment by sean-daley** [comment]
> Comments in the frontend are called inside useEffect. Don't forget that the Controller function is intended to fetch comments only.
> Comments are called based on the post's ID that is included in the comment once it is created. Note the comment model

Sorry not sure what you’re trying to say there. I can only go by what code you’ve posted.
The error you are reporting is an undefined Id to model Post.

‘And you have this code there
```
 {
    const id = req.params;
    try {
        const post = await Post.findById( id )
```

which is making a model Post call using an Id from your req.params setting.
Which is why I asked what that id is because if it’s undefined you will get the error you are seeing.

if that’s not the call that’s erroring out then you might need to provide some more details.

**Comment by mohqaz** [comment]
> > Comments in the frontend are called inside useEffect. Don't forget that the Controller function is intended to fetch comments only.
> > Comments are called based on the post's ID that is included in the comment once it is created. Note the comment model
> 
> Sorry not sure what you’re trying to say there. I can only go by what code you’ve posted. The error you are reporting is an undefined Id to model Post.
> 
> ‘And you have this code there
> 
> ```
>  {
>     const id = req.params;
>     try {
>         const post = await Post.findById( id )
> ```
> 
> which is making a model Post call using an Id from your req.params setting. Which is why I asked what that id is because if it’s undefined you will get the error you are seeing.
> 
> if that’s not the call that’s erroring out then you might need to provide some more details.

now i get this error 
`"Cast to ObjectId failed for value \"{ postId: '657af1874c383d956cbed7f2' }\" (type Object) at path \"_id\" for model \"Post\""`

note the id of post in the error

**Comment by mohqaz** [comment]
i solve it, i made the comments inside post schema and i gave it it's own id 
thank you @sean-daley
