### ISSUE TITLE
Follow-up to #517 (Asynchronous Setters/Getters)

### ISSUE THREAD

**Issue by Windows81** [Automattic/mongoose#14186]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

In issue #517, the original poster raised an issue with writing a setter that autometically hashes the password field once it's set.  As of bcrypt 2.4.3, there is now a `hashSync` method.  Here's a simplified script I've made to illustrate:

```js
const { MONGOOSE } = require("mongoose");
const bcrypt = require("bcryptjs");

const userInfoSchema = new MONGOOSE.Schema({
	username: {
		type: String,
		unique: true,
	},
	password: {
		type: String,
		set: (password) => bcrypt.hashSync(password, 13),
	},
});
```

**Comment by vkarpov15** [comment]
Is there some issue with the script you wrote? It looks technically correct, although I wouldn't recommend running that schema in production because `hashSync()` blocks the entire event loop and is slow by design

**Comment by Windows81** [comment]
@vkarpov15: my assumption is that `hashSync` runs in the same thread as wherever you're calling the Mongoose query.  Is it viable for async functions which call those queries?

**Comment by vkarpov15** [comment]
Node only has one thread by default, so `hashSync()` will block the whole process while it runs. That's why I would recommend running the asynchronous version of `hash()`.
