### ISSUE TITLE
query.select() should overwrite previous selection

### ISSUE THREAD

**Issue by caub** [Automattic/mongoose#14180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Calling .select(fields) should set the query selection to fields

Currently there's no way to reset a previous one, example

```
query.select({ a: 0 });
query.select({ b: 1, c: 1});
```
then current select is a merge of the 2 (but that'll cause issues of mixed types (0/1))

### Motivation

If a .select() is done from a low-level method, as a default selection, we should be able to overwrite it from elsewhere is in codebase

**Comment by vkarpov15** [comment]
Use [`query.projection()` instead](https://mongoosejs.com/docs/api/query.html#Query.prototype.projection()), `query.projection()` overwrites the existing projection

**Comment by caub** [comment]
Just a related question please, I've been searching for the overwriting equivalent for `.sort()`

Similar to how `.projection()` is the overwriting equivalent for `.select()`

I even tried using `.setOptions(null)` or `.setOptions({})` but without success

```
q=I.find().sort({startDate: -1, _id: -1});

q.options.sort // { startDate: -1, _id: -1 }

q.sort({ _id: -1 }); // doesn't "work" as overwriting

// need a way to reset sort so 
q.options.sort // { _id: -1 }
```
