### ISSUE TITLE
_id: false has no meaning

### ISSUE THREAD

**Issue by 332lfgb6** [Automattic/mongoose#14194]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

20.10.0

### MongoDB server version

4

### Description

I specify `_id: false` because I want to customize the primary key, but I still get an error when model.save(): `MongooseError: document must have an _id before save`, this is not a contradiction, when I specify ` _id: false`, save should not have this error,otherwise, id: false loses its meaning.
![image](https://github.com/Automattic/mongoose/assets/51245335/0bb1a8b9-67bd-4dbd-8530-c4dda189829d)

### Steps to Reproduce

1. _id: false
2. model.create or save

### Expected Behavior
When `id:false` is specified, `presave` does not need to check the `_id`

**Comment by vkarpov15** [comment]
Unfortunately MongoDB doesn't allow you to save a document without an `_id`. MongoDB will create an `_id` property for you when you create a document, even if you don't specify one. We should update our docs to specify that the `_id` option is only useful for subdocuments.
