### ISSUE TITLE
Not getting mongoose method recommendation.

### ISSUE THREAD

**Issue by TheGrayGodfather** [Automattic/mongoose#14193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

18.15.0

### MongoDB server version

7.0.4

### Description

At the time of the instant method and static method, I am not getting the recommendation.
I requested it correctly.

![no1](https://github.com/microsoft/vscode/assets/79376437/88055014-5b30-4b47-beb2-e648cfe3ac10)

Any recommendation to fix 

### Steps to Reproduce

```
expenseController.getAllExpenses = async (req, res) => {
  try {
    const response = await Expense.find().populate('category');
    res.json(response);
  } catch (err) {
    res.status(500).json(err);
  }
};
```

### Expected Behavior

need to get recommendations on static method and instant method. Like in case of save, find, getElementById.

**Comment by vkarpov15** [comment]
How are you importing `Category` and `Expense`? Also you're mentioning "static method and instant method", `findByIdAndDelete()` is a Mongoose method - does this issue only happen with `findByIdAndDelete()`?
