### ISSUE TITLE
Bug: check string if is `ObjectId` or not

### ISSUE THREAD

**Issue by MohamedAli00949** [Automattic/mongoose#14200]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.5.3

### Node.js version

20.10.0

### MongoDB server version

7

### Typescript version (if applicable)

5.2.2

### Description

Hi there,
I am using the `isValid` method to verify if the string is `ObjectId` or not.
For the valid IDs, it returns `true` and in some cases, it returns `false`.

I have noticed that any string with length 12 is `valid`  but, this is not correct.

### Steps to Reproduce

``` ts
import mongoose from "mongoose";

console.log(mongoose.isValidObjectId("this is stri")); // true
console.log(mongoose.Types.ObjectId.isValid('this is stri')); // true
```

### Expected Behavior

As I'm saying in the description, the expected behavior is to show false on console.

**Comment by donoftime2018** [comment]
https://mongoosejs.com/docs/api/mongoose.html#Mongoose.prototype.isValidObjectId()

According to the mongoose docs, isValidObjectId returns true if the passed in variable can be **_casted_** to an object id.

**Comment by donoftime2018** [comment]
Try updating your version of Mongoose, Node, or MongoDB.

**Comment by MohamedAli00949** [comment]
> https://mongoosejs.com/docs/api/mongoose.html#Mongoose.prototype.isValidObjectId()
> 
> According to the mongoose docs, isValidObjectId returns true if the passed in variable can be **_casted_** to an object id.

According to MongoDB docs, the `ObjectId` is 12 bytes of Hexadecimal string so it should be in length 24. 
But the upper string is not in hexadecimal.

My resources:
- https://www.mongodb.com/docs/manual/reference/bson-types/#std-label-objectid
- https://www.mongodb.com/docs/manual/reference/method/ObjectId/

Thanks for your interest in my issue

**Comment by MohamedAli00949** [comment]
> Try updating your version of Mongoose, Node, or MongoDB.

I have tried the latest version and I have found the same issue

**Comment by donoftime2018** [comment]
Did you upgrade versions of all 3?

**Comment by MohamedAli00949** [comment]
> Did you upgrade versions of all 3?

No, I have upgraded mongoose version only.

**Comment by donoftime2018** [comment]
Try updating Mongodb, Node, and even TypeScript and see what happens

**Comment by donoftime2018** [comment]
Did it work?

**Comment by vkarpov15** [comment]
Any string of length 12 is technically valid as an ObjectId. But if you want to verify that a string is 24 hex chars, you can use  [`mongoose.isObjectIdOrHexString()` instead](https://mongoosejs.com/docs/api/mongoose.html#Mongoose.prototype.isObjectIdOrHexString()) as follows:

```javascript
console.log(mongoose.isValidObjectId("this is stri")); // true
console.log(mongoose.Types.ObjectId.isValid('this is stri')); // true

mongoose.isObjectIdOrHexString("this is stri"); // false
```

**Comment by MohamedAli00949** [comment]
> Any string of length 12 is technically valid as an ObjectId. But if you want to verify that a string is 24 hex chars, you can use [`mongoose.isObjectIdOrHexString()` instead](https://mongoosejs.com/docs/api/mongoose.html#Mongoose.prototype.isObjectIdOrHexString()) as follows:
> 
> ```js
> console.log(mongoose.isValidObjectId("this is stri")); // true
> console.log(mongoose.Types.ObjectId.isValid('this is stri')); // true
> 
> mongoose.isObjectIdOrHexString("this is stri"); // false
> ```

This is a good method; I am sorry I didn't show it before.
Thanks
