### ISSUE TITLE
`Document.prototype.set` is not working properly when setting the Nested property to `null` with the `path` of object type

### ISSUE THREAD

**Issue by anthonyminyungi** [Automattic/mongoose#14205]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.13.20

### Node.js version

18.8.0

### MongoDB server version

4.2

### Typescript version (if applicable)

4.9.5

### Description

When I try to set the nested property to null with the object `path` argument,
the `nested` property is not updated to the value `null`.

But, setting the property to `null` with the form of `model.set(path, value)` or assigning directly `null` value to the property worked as I expected.

I think it is a bug, so I searched this repository for similar issues, but I couldn't find it as far as I searched.
So, I am reporting this issue like this.

### Steps to Reproduce

When the Model seems like:
```js
const schema = new Schema({
    nested: {
        key1: String,
        key2: String,
    },
});

const Model = mongoose.model('Model', schema);
```

Behavior different from what I expected:
```js
const func = async (id) => {
    const doc = await Model.findById(id);
    /**
     * doc => {
     *   nested: {
     *     key1: 'value1',
     *     key2: 'value2',
     *   }
     * }
     */
    doc.set({
        nested: null,
    });
    /**
     * doc => {
     *   nested: {
     *     key1: 'value1',
     *     key2: 'value2',
     *   }
     * }
     */
    await doc.save();
};

```

Behavior same as I expected:
```js
const func = async (id) => {
    const doc = await Model.findById(id);
    /**
     * doc => {
     *   nested: {
     *     key1: 'value1',
     *     key2: 'value2',
     *   }
     * }
     */
    doc.set('nested', null);
    // or doc.nested = null
    /**
     * doc => {
     *   nested: null
     * }
     */
    await doc.save();
};
```

### Expected Behavior

```js
const func = async (id) => {
    const doc = await Model.findById(id);
    /**
     * doc => {
     *   nested: {
     *     key1: 'value1',
     *     key2: 'value2',
     *   }
     * }
     */
    doc.set({
        nested: null,
    });
    /**
     * doc => {
     *   nested: null
     * }
     */
    await doc.save();
};
```

**Comment by donoftime2018** [comment]
Can you provide some test data to insert into the db?

**Comment by anthonyminyungi** [comment]
@donoftime2018  

As I explained in https://github.com/Automattic/mongoose/issues/14205#issue-2059366379, you can try to reproduce this with any data that has a property of nested object shape.

For example: 
```js
const schema = new Schema({
    // for 'parent' property
    parent: {
        prop: {
            foo: Number,
            bar: String,
        },
    },
});
```

**Comment by anthonyminyungi** [comment]
@vkarpov15  

I have a little question for it, is there no plan to resolve this issue in the milestone `5.13.22`?  
I found this bug in `5.13.20`, but you set the milestone for this issue to `6.12.5`.  
Could you give me a short explanation of it?

**Comment by vkarpov15** [comment]
We will cherry pick the fix to 5.x.
