### ISSUE TITLE
how to make pre-hook callback function generic so that I can import it every mongoose schema?

### ISSUE THREAD

**Issue by hiijitesh** [Automattic/mongoose#14203]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.4

### Node.js version

14

### MongoDB version

4.4.18

### Operating system

Linux

### Issue

I am trying to make `pre hook` callback function generic so that I can use it in every schema. I was able to do it `post hook` but looks like pre doesn't allow me.

in pre hook i am trying perform `findOne` then pass it to mongoose since i want to store data before performing any operation then i can compare both data in post hook.

**Comment by hiijitesh** [comment]
```js

// this function is suppose to be in other module and passing myModel to this function
const preFunctionHelper = function (myModel) {
	return async function (next) {
		try {
			const { _id } = this.getQuery();
			const myData = await myModel.findOne({ _id: id }).lean();

			next();
		} catch (error) {
			console.error("Error in pre hook:", error);
			next(error);
		}
	};
};

// imorting preFunctionHelper and using it here
schema.pre("updateOne", preFunctionHelper(TestModel));


```

**Comment by vkarpov15** [comment]
What do you mean by "but looks like pre doesn't allow me."? Are you getting some sort of error message?

**Comment by hiijitesh** [comment]
@vkarpov15  Thank your for your response :)
Let me clarify 
`"but looks like pre doesn't allow me."? ` means pre was not getting executed whenever I tried to use it in schema module.

Good thing is that I somehow manage to make it modular and was able to use it.

```js
function preHookHelper() {
	return async function (next) {
		try {
			const query = this.getQuery();
			// main issue was how pass the "Model", which is solved by "this.model"
			const oldData = await this.model.find(query).lean();
		
			this._data = { oldData, query };

			next();
		} catch (error) {
			console.error("Error in pre hook:", error);
			next(error);
		}
	};
}```
