### ISSUE TITLE
Add a new method on `Schema` to create a new model using that instance

### ISSUE THREAD

**Issue by SkyaTura** [Automattic/mongoose#14210]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Self explanatory

### Motivation

Reduce number of unnecessary imports and simplify usability.

### Example

Before:

```typescript
import { Schema, mongoose } from 'mongoose'

const BookSchema = new Schema({ ... }, { ... })

const BookModel = mongoose.model('Book', BookSchema)
```

After:

```typescript
import { Schema } from 'mongoose'

const BookSchema = new Schema({ ... }, { ... })

const BookModel = BookSchema.model('Book')
```

**Comment by vkarpov15** [comment]
Not realistically possible, because one schema can be used by many models (even by models on different connections). A schema can also be a top-level schema in one model and an embedded schema in another.
