### ISSUE TITLE
passing an error handler function in ensureIndexes results in a TypeError

### ISSUE THREAD

**Issue by Altair2169** [Automattic/mongoose#14238]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.3

### Node.js version

20.10.0

### MongoDB server version

6.0

### Description

According to [docs](https://mongoosejs.com/docs/api/model.html#Model.ensureIndexes()) , we can pass in an error handler to `ensureIndexes` in case if it returns an error, but on passing a func, ts returns a type error saying `Type '(err: any) => void' has no properties in common with type 'CreateIndexesOptions'`

### Steps to Reproduce

```ts
const Model = mongoose.Model('model', modelSchema)
await Model.ensureIndexes((err)=>console.log(err))
```

### Expected Behavior

No type error should be there

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);
async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();
    await Test.ensureIndexes(function (err) {
        console.log('error', err);
    });
    await mongoose.connection.close();
    console.log('done');
}

run();
```

Output:
```
MongooseError: Model.ensureIndexes() no longer accepts a callback
```

**Comment by vkarpov15** [comment]
This is just an issue with the docs, `ensureIndexes()` no longer supports passing a callback.
