### ISSUE TITLE
timestamps query option doesn't work in 6.x+

### ISSUE THREAD

**Issue by eric-titan** [Automattic/mongoose#14248]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

&gt;=6

### Node.js version

any

### MongoDB server version

5.x

### Typescript version (if applicable)

N/A

### Description

Setting the `{ timestamps: false }` option doesn't seem to work since 6.x to avoid updating timestamps on schemas with `{ timestamps: true }`. Timestamps still get updated.

```
Using mongoose 5.13.22...
createdAt was updated by findOneAndUpdate

Using mongoose 6.12.5...
createdAt was not updated by findOneAndUpdate

Using mongoose 7.6.8...
createdAt was not updated by findOneAndUpdate

Using mongoose 8.0.4...
createdAt was not updated by findOneAndUpdate
```

### Steps to Reproduce

```
const moment = require('moment');
const mongoose = require('mongoose');
const mongooseVersion = require('mongoose/package').version;

async function run() {
    await mongoose.connect('mongodb://127.0.0.1/my_database');
    const Schema = mongoose.Schema;

    const SchemaWithTimestamps = new Schema({
        name: String,
        age: Number,
        favoriteFoods: [String]
    }, { timestamps: true });

    const Person = mongoose.model('Person', SchemaWithTimestamps);
    const person = new Person({
        name: 'John',
        age: 20,
        favoriteFoods: ['Pizza', 'Hamburger']
    });
    
    await person.save();
    const newCreatedAt = moment().subtract(1, 'year');

    const updatedPerson = await Person.findOneAndUpdate(
        { name: 'John' },
        { $set: { createdAt: newCreatedAt.toDate() } },
        { timestamps: false, new: true }
    );
    
    console.log(`Using mongoose ${mongooseVersion}...`);
    if (moment(updatedPerson.createdAt).isSame(newCreatedAt)) {
        console.log('createdAt was updated by findOneAndUpdate');
    } else {
        console.log('createdAt was not updated by findOneAndUpdate');
    }
    process.exit(0);
}

run();
```

### Expected Behavior

I would expect the `createdAt` timestamp field to get updated by the `findOneAndModify` query as in mongoose < 6.x.

**Comment by eric-titan** [comment]
Everything seems good in the `_setTimestampsOnUpdate` pre middleware, if I `console.log(this.getUpdate())` before the `next()` I see:

```
{ '$set': { createdAt: 2023-01-10T16:45:36.366Z } }
```
However, with debug enabled, I can see Mongoose only runs `Mongoose: people.findOne({ name: 'John' }, { new: true })` - the `createdAt` field is being stripped at some points and Mongoose apparently determines the update to be empty.

Similarly, setting `{timestamps: {createdAt: false}}` yields this in the timestamps middleware:
```
{
    '$set': {
      createdAt: 2023-01-10T16:49:29.791Z,
      updatedAt: 2024-01-10T16:49:29.792Z
    }
  }
```

But Mongoose is again stripping out the `createdAt` field when running the query:

```
Mongoose: people.findOneAndUpdate({ name: 'John' }, { '$set': { updatedAt: new Date("Wed, 10 Jan 2024 16:49:29 GMT") } }, { returnDocument: 'after', returnOriginal: false })
```

**Comment by vkarpov15** [comment]
@eric-titan yes please, put in a PR with where you think would be a good place to put this information in the docs.

**Comment by vkarpov15** [comment]
@eric-titan I took a closer look and our timestamps docs do have an example of how to overwrite `createdAt` using `findOneAndUpdate()` in this section: https://mongoosejs.com/docs/timestamps.html#disabling-timestamps. Below is the code sample:

```
let doc = await User.create({ name: 'test' });

// To update `updatedAt`, do a `findOneAndUpdate()` with `timestamps: false` and
// `updatedAt` set to the value you want
doc = await User.findOneAndUpdate({ _id: doc._id }, { updatedAt: new Date(0) }, {
  new: true,
  timestamps: false
});
console.log(doc.updatedAt); // 1970-01-01T00:00:00.000Z

// To update `createdAt`, you also need to set `strict: false` because `createdAt`
// is immutable
doc = await User.findOneAndUpdate({ _id: doc._id }, { createdAt: new Date(0) }, {
  new: true,
  timestamps: false,
  strict: false
});
console.log(doc.createdAt); // 1970-01-01T00:00:00.000Z
```

Is there somewhere else in the docs you would expect to see this example?
