### ISSUE TITLE
Dynamic Object ID reference for a subdocument inside an array

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#14249]
### Discussed in https://github.com/Automattic/mongoose/discussions/14243

<div type='discussions-op-text'>

<sup>Originally posted by **echo-999** January  8, 2024</sup>
I'm trying to create a dynamic ref for an object ID stored inside a property of a subdocument. The property can reference multiple models (even models registered in a different mongoose database instance) so I use the model instance directly instead of a model name.

```ts
const subSchema = new Schema({
	category: String,
	ref: {
		type: Schema.Types.ObjectId,
		ref: function() {
			return this.category === 'catA' ? CategoryAModel : CategoryBModel // imports model instances
		}
	}
})

const parentSchema = new Schema({
	name: String,
	children: [subSchema]
})

const ParentModel = db.model('Parent', parentSchema)
```

As you can see, the `ref` property is the Object ID of either a document from `CategoryAModel` or `CategoryBModel`. I started creating documents for this model, such as the following:

```ts
const data = {
	name: 'Test Data',
	children: [
		{
			category: 'catA',
			ref: '658e9f1901f3da2c14920401' // <- existing document from CategoryAModel
		},
		{
			category: 'catB',
			ref: '654995e0c89d1c19c84e77b7' // <- existing document from CategoryBModel
		}
	]
}
```

But when i tried to `populate` this, the `ref` for `category: 'catA'` becomes null (despite existing). I logged the `this` context in the `ref`'s ref function and saw that `this` refers to the document being processed (same shape as the data above), and that `this.category` is undefined because it's actually inside the `children` array. Essentially making the `ref` always result in being the `CategoryBModel`

Since it's an array, how would I go and make a dynamic reference? Is there a way to access the index of the `subSchema` being referred to?</div>

**Comment by IslandRhythms** [comment]
Populating both results in only catB being populated

```javascript
const mongoose = require('mongoose');

const { Schema } = mongoose;

const aSchema = new Schema({
  name: String
});

const bSchema = new Schema({
  name: String
});

const CategoryAModel = mongoose.model('CategoryAModel', aSchema);
const CategoryBModel = mongoose.model('CategoryBModel', bSchema);

const testSchema = new Schema({
  category: String,
  ref: {
    type: Schema.Types.ObjectId,
    ref: function() {
      return this.category === 'catA' ? CategoryAModel : CategoryBModel
    }
  }
});

const parentSchema = new Schema({
  name: String,
  children: [testSchema]
});

const Test = mongoose.model('Test', parentSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const A = await CategoryAModel.create({
    name: 'A'
  });
  const B = await CategoryBModel.create({
    name: 'B'
  });

  const doc = await Test.create({
    name: 'Parent',
    children: [{ category: 'catA', ref: A._id }, { category: 'catB', ref: B._id }]
  });

  const res = await Test.findOne().populate('children.ref');
  console.log('what is res', res, res.children);
}

run();
```
