### ISSUE TITLE
Why ObjectId type is such extremly complex?

### ISSUE THREAD

**Issue by samchon** [Automattic/mongoose#14259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

```typescript
import { ObjectId } from "mongoose";
import typia from "typia";

typia.createIs<ObjectId>();
```

Hello, I am the developer of [typia](https://github.com/samchon/typia).

It's a typial TypeScript runtime validator library, not-so-famous. By the way, the biggest characteristic of `typia` is that validation does not require extra schema definition, but fine with only pure TypeScript type. In such reason, I'm often getting such issues with this `mongoose`, especially about the `ObjectId` type.

> ### Some users of `typia`
>
> I think that `ObjectId` type of `mongoose` just seems like a `string` similar one. 
>
> However, if compile the TypeScript code, extremely large amount of code being generated. 
>
> It seems bug of `typia`. Can you fix it?

By the way, it is not a bug of `typia`, and `ObjectId` type of `mongoose` is such extremley complex. Currently, I'm guiding users to separate DTO and ODM types, so that avoid to validating the `ObjectId` type directly. However, it is not a ideal solution, but just a way hiding the problem. I need to answer them the conclusion with exact solution.

  - [Metadata Schema of `ObjectId` type](https://github.com/samchon/typia-mongoose-object-id/blob/master/ObjectId.json)
  - [Validation code of `ObjectId` type](https://github.com/samchon/typia-mongoose-object-id/blob/master/ObjectId.check.js)

Therefore, my question is:

1. Why `ObjectId` type is such complex?
2. Is it spec? or bug?
3. If not bug, what is the purpose of such complex type?
4. No way to simplify it further?

**Comment by vkarpov15** [comment]
What specifically is complex about the ObjectId type? Is the [source code](https://github.com/mongodb/js-bson/blob/main/src/objectid.ts) too long? Too many helpers? Too many possible argument types to the ObjectId constructor?

**Comment by samchon** [comment]
@vkarpov15 No, the complexity comes from the SchemaType of mongoose.

It is the reason why making validation code be such long (read my links of top please).

https://github.com/Automattic/mongoose/blob/1eaa2d6d12281d70343dd580285fceac0f238cfe/types/schematypes.d.ts#L199

**Comment by vkarpov15** [comment]
I don't know how you're generating this code, but one potential issue is that you say typia doesn't require schema definitions, but you're validating that the given value is an instance of the ObjectId SchemaType rather than an ObjectId. If I'm understanding things correctly, `typia.createIs<ObjectId>();` should check if the given value is an instance of `mongoose.Types.ObjectId`, **not** `mongoose.Schema.Types.ObjectId`.

If you're looking for a runtime check that a value is something Mongoose can convert to an ObjectId, then you should just use [`mongoose.isValidObjectId()`](https://mongoosejs.com/docs/api/mongoose.html#Mongoose.prototype.isValidObjectId()).

**Comment by samchon** [comment]
`typia` just analyzes TypeScript types through compiler API, and writes validation code for the target type. That's all. Therefore, it is not possible to adding special validation logic to using the `mongoose.isValidObjectId()` only for the `mongoose.ObjectId` type. Also, it is possible to performing the `instanceof` statement. However, individual member properties' validation is still required, because one of them can be wrong. 

Therefore, to solve the issue of my library `typia`, `mongoose.ObjectId` type (of `mongoose/types/schematypes.d.ts`) must be changed to erasing vulnerable properties. If not, no way for me. In that case, I just have to guide users not to validate the `mongoose` models through `typia`'s functions, introducing such special stories.

```typescript
@Controller("bbs/articles")
export class BbsArticlesController {
  @TypedRoute.Post()
  public async store(
    // the validation must be done in here, and typia does it
    @TypedBody() input: IBbsArticle.IStore
  ): Promise<IBbsArticle> {
      // transformation to the mongoose model class instance must be done after the raw data validation
  }
}
```

From a general perspective on the backend development, DTO types should be separated with ODM types. When the backend server gets some data from a remote client through network communication like Rest API, the instance is not a specific class instance, but a primitive instance. Validation must be done at that step, the raw data level.

Anyway, it would be nice if `mongoose.ObjectId` has a more reasonable type, but this is entirely up to you as the author of `mongoose`. Whatever you decide, I think the fundamental problem comes from some special `typia` users violating the principle, "separating DTO and ODM types". I'm just reporting this issue due to too many people are taking same mistakes repeatedly for a long time. Thanks for reading long issue and comments.

**Comment by vkarpov15** [comment]
Ok, so why is typia analyzing `mongoose.ObjectId` rather than `mongoose.Types.ObjectId`? `mongoose.ObjectId` is the ObjectId SchemaType class, not the ObjectId class. And users typically want to validate that a value is an ObjectId, not an ObjectId SchemaType.

**Comment by samchon** [comment]
Understood, the `mongoose.Types.ObjectId` only one property `_id`.
