### ISSUE TITLE
Inconsistent behaviour for .create/.save vs updateOne/findOneAndUpdate for null values

### ISSUE THREAD

**Issue by wasya243** [Automattic/mongoose#14253]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.4

### Node.js version

18.13.0

### MongoDB server version

6.2.0

### Typescript version (if applicable)

5.3.3

### Description

Here is the code that basically explains everything. But the question is why when I use .save or .create methods I get 'ValidatorError: Path `state` is required' error when trying to set null value, but it does not work the same for update methods -> it simply passes and updates it.

```
import mongoose from 'mongoose';

const AddressSchema = new mongoose.Schema({
  city: {
    type: String,
    required: true
  },
  state: {
    type: String,
    required: true
  }
});

const VendorSchema = new mongoose.Schema({
  name: {
    required: true,
    type: String
  },
  company: {
    required: true,
    type: new mongoose.Schema({
      name: {
        type: String,
        required: true
      },
      address: {
        required: true,
        type: AddressSchema
      },
      billing_address: {
        type: AddressSchema
      }
    })
  }
}, { collection: 'vendors' });


const VendorMongooseModel = mongoose.model('Vendor', VendorSchema);

async function run() {
  try {
    await mongoose.connect(`mongodb://localhost:27017/test-null-values-for-string`);

    // there will error if I pass billing_address.city and billing_address.state as null
    await VendorMongooseModel.create({
      name: 'vendor 3',
      company: {
        name: 'company 3',
        address: {
          city: 'city3',
          state: 'state3'
        },
        billing_address: {
          city: 'city 4',
          state: 'state 4'
        }
      }
    });

    // passes
    await VendorMongooseModel.findOneAndUpdate(
      { name: 'vendor 3' },
      {
        $set: {
          'company.billing_address.city': null,
          'company.billing_address.state': null,
        }
      }
    )

    // passes
    await VendorMongooseModel.updateOne(
      { name: 'vendor 3' },
      {
        $set: {
          'company.billing_address.city': null,
          'company.billing_address.state': null,
        }
      }
    )

    // error
    const qVendor = await VendorMongooseModel.findOne({ name: 'vendor 3' });

    if (qVendor) {
      // @ts-ignore
      qVendor.company.billing_address.city = null;
      // @ts-ignore
      qVendor.company.billing_address.state = null;

      await qVendor.save();
    }

    process.exit(0);
  } catch (err) {
    console.log('err', err);
    process.exit(1);
  }
}

run();
```

### Steps to Reproduce

Just run the following code with mongoose installed and specified versions for typescript, node.js and mongodb.

### Expected Behavior

Error is thrown on .save, .create, .updateOne, .etc

**Comment by paradoxmr24** [comment]
mongoose don't run validators on update by default, if you want to run validators on update operations also then you need to write this:

mongoose.set('runValidators', true);

**Comment by MikeKoval** [comment]
why its disabled by default?
what does "Be careful: update validators are off by default because they have several caveats." really mean according to documentation?

**Comment by vasyl97kharchenko** [comment]
@vkarpov15 is it still ok that because of this behavior I can even delete required fields using $unset operator during update?

**Comment by vkarpov15** [comment]
@vasyl97kharchenko that sounds like a potential bug, `runValidators: true` should prevent explicit `$unset` of `required` fields. Can you please provide a script that demonstrates the issue you're seeing?

**Comment by vasyl97kharchenko** [comment]
@vkarpov15 false alarm, did a double check, if runValidators: true -> it's not possible. Behaviour with $unset is only possible when validators are not running.
