### ISSUE TITLE
$in not working

### ISSUE THREAD

**Issue by dghub-founder** [Automattic/mongoose#14262]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

0

### Node.js version

0

### MongoDB server version

0

### Typescript version (if applicable)

0

### Description

 var search = {
    $or: [
      {
      
        categories: { $all: ["65a3741d84cada94062de106"] },
     
      },
    ],
  };

  var total = await Product.find(search).count();

### Steps to Reproduce

111

**Comment by vkarpov15** [comment]
Please elaborate on the issue you're seeing: what does your data look like, what does your schema look like, are you getting an error message or just an unexpected result?
