### ISSUE TITLE
[REG 8.0.3->8.0.4/8.1.0] updateOne/updateMany can no longer accept runValidators/new

### ISSUE THREAD

**Issue by orgads** [Automattic/mongoose#14275]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.0

### Node.js version

20.10.0

### MongoDB server version

6.2.0

### Typescript version (if applicable)

5.3.3

### Description

Passing `runValidators: true` to `updateOne` (documented [here](https://mongoosejs.com/docs/validation.html#update-validators)) is broken with 8.1.0.

Probably broke with abdac8d7a2e77655ee0fd2ed93b535412ea2f857.

I think that either `updateOne` should be reverted to accept `QueryOptions`, or `MongooseQueryOptions` should include also `runValidators`.

### Steps to Reproduce

```ts
import { Model } from 'mongoose';

export function func(dbModel: Model<unknown>) {
  // Object literal may only specify known properties, and 'runValidators' does not exist in type 'UpdateOptions & Omit<MongooseQueryOptions<unknown>, "lean">'.ts(2353)
  void dbModel.updateOne({ foo: 'bar' }, { foo: 'baz' }, { runValidators: true });
}
```

**Comment by par333k** [comment]
The return option for the updateMany option, new, is also broken and cannot be used.

**Comment by orgads** [comment]
Thanks!

**Comment by vkarpov15** [comment]
@par333k `new` isn't a valid option for `updateMany()`, it is only useful for `findOneAndUpdate()` `findOneAndReplace()` etc.
