### ISSUE TITLE
8.1 middleware pre hook typescript types broken?

### ISSUE THREAD

**Issue by mharj** [Automattic/mongoose#14272]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.0

### Node.js version

18

### MongoDB server version

latest

### Typescript version (if applicable)

5.1.x

### Description

on Mongoose 6.x this is ok (and verified both queries and documents get correctly to function).
```typescript
schema.pre(['deleteOne', 'deleteMany', 'findOneAndDelete', 'findOneAndRemove'], {query: true, document: true}, function (this) {
```

but if try same on Mongoose 8.1 I have type error from keys.
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'RegExp | "insertMany"'.ts(2769)
```
...  also I try to find middleware single "keys" it only gives few options to choose from. (even when only query: true and actual Query type added on generics)

### Steps to Reproduce

just normal pre hook middleware setup on typescript project.

### Expected Behavior

types works like 6.x

**Comment by mharj** [comment]
type issue also visible when adding test to middleware.test.ts
```typescript
schema.pre<Query<ITest, ITest> | Model<ITest>>(['deleteOne', 'deleteMany', 'findOneAndDelete', 'findOneAndRemove'], {query: true, document: true}, function (this) {
  expectType<Model<ITest> | Query<ITest, ITest> | null>(this);
  return Promise.resolve();
});
```

**Comment by vkarpov15** [comment]
It looks like the cause of this issue is the `'findOneAndRemove'`. [`findOneAndRemove()` was removed in Mongoose 8](https://mongoosejs.com/docs/migrating_to_8.html#removed-findoneandremove), and our TypeScript types removed it. It looks like the following compiles fine with Mongoose 8.1.0:

```ts
schema.pre<Query<ITest, ITest> | Model<ITest>>(
  ['deleteOne', 'deleteMany', 'findOneAndDelete'],
  {query: true, document: true},
  function (this, next) {
    expectType<Model<ITest> | Query<ITest, ITest>>(this);
    next();
  }
);
```
