### ISSUE TITLE
Typescript schema doesn't have _id field.

### ISSUE THREAD

**Issue by abarriel** [Automattic/mongoose#14286]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.4

### Node.js version

16

### MongoDB server version

6.0.6

### Typescript version (if applicable)

5.2.2

### Description

Hello,

I think the `SchemaType` of a  schema should have an  `_id` field **by default**

For e.g, we have `createdAt`, and `updatedAt` field in the type when we set the `option { timestamps: true }`.

Which is not the case when we set `options: { _id: true }`

### Steps to Reproduce

```ts
import mongoose, { type InferSchemaType, Schema } from "mongoose";

const eventSchema = new mongoose.Schema({ url: String }, { timestamps: true });
const Event = mongoose.model("Event", eventSchema);

type EventDoc = InferSchemaType<typeof eventSchema>;

async function run() {
  const event = {} as EventDoc;

  // createdAt exists because timestamps: true, which is totally OK
  event.createdAt = new Date();

  //  WRONG: _id does not exist on type EventDoc, this should be set, since options._id is to true by default
  event._id; // ERROR
}

run();

```

**Comment by IslandRhythms** [comment]
```typescript
import mongoose, { type InferSchemaType, Schema } from "mongoose";

const eventSchema = new mongoose.Schema({ url: String }, { timestamps: true });
const Event = mongoose.model("Event", eventSchema);

type EventDoc = InferSchemaType<typeof eventSchema>;

async function run() {
  const event = {} as EventDoc;

  // createdAt exists because timestamps: true, which is totally OK
  event.createdAt = new Date();

  //  WRONG: _id does not exist on type EventDoc, this should be set, since options._id is to true by default
  event._id; // ERROR
}

run();
```

**Comment by vkarpov15** [comment]
I agree this is a bit confusing, however currently the issue is that `InferSchemaType` doesn't return the full hydrated doc type. You still need to pass `InferSchemaType` through `HydratedDocument<>`. The easiest way to infer the full hydrated document type currently is the following:

```ts
type EventDoc = ReturnType<(typeof Event)['hydrate']>; //InferSchemaType<typeof eventSchema>;
```

**Comment by vkarpov15** [comment]
I think we'll have to make some docs changes to account for this, adding `_id` to the return value of `InferSchemaType<>` tends to cause circular dependency errors and other issues. I'll patch up the docs to make this more clear. There's a couple of places, like [here](https://mongoosejs.com/docs/typescript/schemas.html#automatic-type-inference), where we imply that `InferSchemaType` returns a hydrated document type.
