### ISSUE TITLE
Change Discriminator Options value Type

### ISSUE THREAD

**Issue by ToineOu** [Automattic/mongoose#14291]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hye,
Actually, DiscriminatorOptions value only accpet type string.

```
export type DiscriminatorOptions = {
    name: string;
    schema: Schema;
    value?: string;
};
```

I think it's too restrictive and it would be possible for example to add a bollean type

```
export type DiscriminatorOptions = {
    name: string;
    schema: Schema;
    value?: string | boolean;
};
```

**Comment by vkarpov15** [comment]
What version of Mongoose are you using? [In Mongoose 8, `DiscriminatorOptions` accepts string, number, or ObjectId for values](https://github.com/Automattic/mongoose/blob/2c341026768c1cec207ecd4fb2b01b066b04cbf3/types/models.d.ts#L5), which are the only types we officially support for discriminator values.
