### ISSUE TITLE
createConnection creates multiple connections

### ISSUE THREAD

**Issue by jaeecheveste** [Automattic/mongoose#14294]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.3

### Node.js version

20.x

### MongoDB server version

7.0.5

### Typescript version (if applicable)

5.3.3

### Description

I have this following script:

```
import express from 'express';
import mongoose from 'mongoose';
import { ConfigSchema } from '../schemas/config.schema';
const app = express();
const port = 3000;
(async () => {

  const connection = await mongoose.createConnection('mongodb://sdrw-db-service:27017/example').asPromise();

  connection.model('config', ConfigSchema);

  const configModel = await connection.model('config', ConfigSchema);

  const config = await configModel.findOne();
})();

app.get('/', (req, res) => {
  res.send('Hello World!');
});

app.listen(port, () => {
  return console.log(`Express is listening at http://localhost:${port}`);
});
```

When findOne is called, it creates 1 more curr_active connection and it creates 2 curr_inactive connections more.
I don't know if I am doing something wrong.

Running this with mongoose 5.13.22 only creates 1 connection and it stays inactive.

### Steps to Reproduce

Create an express project.
Try to execute the code in the description above. 
Please, observe when findOne is called and running this script to check connections:

```
db.getSiblingDB("admin").aggregate( [
   { $currentOp: { allUsers: true, idleConnections: true, idleSessions: true } }
  ,{$project:{
            "_id":0
           ,client:{$arrayElemAt:[ {$split:["$client",":"]}, 0 ] }
           ,curr_active:{$cond:[{$eq:["$active",true]},1,0]}
           ,curr_inactive:{$cond:[{$eq:["$active",false]},1,0]}
           }
   }
  ,{$match:{client:{$ne: null}}}
  ,{$group:{_id:"$client",curr_active:{$sum:"$curr_active"},curr_inactive:{$sum:"$curr_inactive"},total:{$sum:1}}}
  ,{$sort:{total:-1}}
] )
```

You will observe that connections increases

**Comment by jaeecheveste** [comment]
It seems that when const config = await configModel.findOne(); it creates a new connection in mongoose 6.12.3. If you try in mongoose 5.9.3 , there is not created any new connection

**Comment by DevooKim** [comment]
you might want to check out this migrating guide

https://mongoosejs.com/docs/6.x/docs/migrating_to_6.html#the-aspromise-method-for-connections

**Comment by vkarpov15** [comment]
A Mongoose connection contains a "connection pool", which is a collection of sockets that the MongoDB Node driver can grow or shrink between `minPoolSize` and `maxPoolSize`. So one connection can open multiple sockets to the MongoDB server. Does that make sense?

**Comment by jaeecheveste** [comment]
I've noticed changes in the topology of MongoDB 4.17.2. It seems to be establishing more connections every time a query to the model is executed. However, the issue arises as these connections remain idle, despite configuring the maxIdleTimeMs property.

**Comment by vkarpov15** [comment]
@jaeecheveste have you tried setting the `maxPoolSize` option to a smaller value? That value defaults to 100, smaller values will prevent the MongoDB node driver from opening too many sockets.
