### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by sagardspeed2** [Automattic/mongoose#14298]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hey, I am using FastAPI for my high level abstraction project. and I want to use mongodb for some critical modules. but there is no any great ODM available on market right now.

So I am requesting a feature here to provide the python support.

### Motivation

There are many ODM like prisma, pymongo and some more, but none of them are good as prisma with the rich features that can satisfy the all needed requirements.

**Comment by vkarpov15** [comment]
Unfortunately a Python ODM is outside the scope of Mongoose. We don't have nearly enough Python expertise to build one. Sorry and good luck :+1:
