### ISSUE TITLE
updateMany should be able to return newly updated documents

### ISSUE THREAD

**Issue by bernardarhia** [Automattic/mongoose#14293]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I was wondering if you guys can add the new option props to the current version to return the newly updated documents when updateMany is called.  It was in a previous version but has been removed from v8.1.1

**Comment by vkarpov15** [comment]
`updateMany()` never returned updated documents, newly updated or otherwise, so the `new` option isn't relevant for `updateMany()`. How are you using `updateMany()`?

**Comment by bernardarhia** [comment]
Someway somehow it worked in my company's source code for version 6 but I was tasked to upgrade to v8 and I'm not able to do that again. It is a suggestion though.

**Comment by vkarpov15** [comment]
Without code samples, I can't tell what "it worked" means. Sure TypeScript compiler allowed it, but `new` did nothing with `updateMany()` in 6.x.
