### ISSUE TITLE
Mongoose 8.x returns isValidObjectId false for twelve-character string that works in 7.x

### ISSUE THREAD

**Issue by gunnarsson** [Automattic/mongoose#14308]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.1

### Node.js version

20.5.0

### MongoDB server version

6.x

### Description

I've just tried migrating from Mongoose 7.x to the latest (8.1.1), and ran into an issue with my server not finding the object referred to by a request. As part of the validation I check that the id is a valid ObjectId before using it, and the behavior of this function has changed in 8.x. I send strings of length 12 from the client, e.g. `4c39e9302691`. In Mongoose 7.x, that string is deemed valid by isValidObjectId, but in 8.x the same check comes back negative.

I've read through many past issues regarding isValidObjectId, but they mostly seem to be about making it _more_ strict. In this case the situation is the opposite, and I can't find any references to this change in behavior. Apologies if I've misunderstood anything!

### Steps to Reproduce

```js
const { isValidObjectId } = require('mongoose');

console.log(isValidObjectId('4c39e9302691');
```

### Expected Behavior

I expect a string of length 12 to return true.

**Comment by sean-daley** [comment]
There's a section in the "migrating to mongoose 8" guide about changes to valid object ids and 12 character length strings. Could this be related to that?
https://github.com/Automattic/mongoose/blob/master/docs/migrating_to_8.md#mongodb-node-driver-6

**Comment by gunnarsson** [comment]
> There's a section in the "migrating to mongoose 8" guide about changes to valid object ids and 12 character length strings. Could this be related to that?
> https://github.com/Automattic/mongoose/blob/master/docs/migrating_to_8.md#mongodb-node-driver-6

That sounds very likely! Thank you, I didn't find anything like that on my own. I'll try to figure out how to convert a 12-character string into a valid ObjectId in this new version, since I'll keep getting them from mobile apps out in the wild. I'll close this issue. Thanks again!

**Comment by gunnarsson** [comment]
This seems to be due to a change introduced in verson 6 of the Node MongoDB driver.

**Comment by vkarpov15** [comment]
Yeah this is a change in the MongoDB Node driver. They don't accept length 12 strings in the ObjectId constructor anymore unfortunately:

```
> new mongoose.Types.ObjectId('123457890ab')
Uncaught:
BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
    at new ObjectId (/mongoose/node_modules/bson/lib/bson.cjs:2047:23)
> 

```
