### ISSUE TITLE
Type for new option missing in 8.1.1

### ISSUE THREAD

**Issue by richardsimko** [Automattic/mongoose#14300]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.1

### Node.js version

20.x

### MongoDB server version

6.x

### Typescript version (if applicable)

5.3.x

### Description

The following code

```ts
await FooModel.updateOne(
          { foo: bar },
          { $set: {baz: true} },
          { upsert: true, new: true },
        );
```

Results in the following type error:

`Object literal may only specify known properties, and 'new' does not exist in type 'UpdateOptions & Omit<MongooseQueryOptions<FooModel>, "lean">'`

### Steps to Reproduce

See description

**Comment by richardsimko** [comment]
Has this been removed? In that case it should probably be a version 9.x and the docs need to be updated.

https://mongoosejs.com/docs/tutorials/findoneandupdate.html

https://mongoosejs.com/docs/api/query.html#Query.prototype.findOneAndUpdate()

**Comment by richardsimko** [comment]
Although I suppose `new` doesn't really make sense in the context of `updateOne` since that doesn't actually return a model so it is probably correct for that to be invalid.

**Comment by vkarpov15** [comment]
Yeah specifying `new` with `updateOne` does nothing, so we updated our types for better intellisense: we don't want VSCode to imply that `new` with `updateOne` does something.

**Comment by richardsimko** [comment]
Yep, makes sense! I was getting `findOneAndUpdate` and `updateOne` mixed up. My bad.
