### ISSUE TITLE
Flag to disallow passing undefined in queries globally

### ISSUE THREAD

**Issue by roopakv** [Automattic/mongoose#14313]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Today there is a strictQuery that allows for throwing if a key being searched for isn't defined. However if I end up passing undefined as a value when searching for a field defined in the schema that entire filter is ignored. 

I know there is some of what the mongo driver does here that makes it hard to fix.

However a solution that might work for most cases is allowing a flag or an additional flag on `strictQuery` say `throwIncludingUndefined` that throws if searching for a field including undefined

e.g.
```
// should throw
{
   someKey: undefined
}

// allowed
{
   someKey: null
}
```

### Motivation

We ran into a bug where all documents were returned when we ended up passing undefined in the query for a particular field. pretty nasty bug.

### Example

```
mongoose.set('strictQuery', 'throwIncludingUndefined');
```

**Comment by vkarpov15** [comment]
This is more of a bug report than a feature request. Either way, I'm unable to repro, the following example shows that `find({ name: undefined })` is equivalent to `find({ name: null })`, which doesn't return all documents. This is in Mongoose 8.1.1. Please modify the following script to demonstrate the issue you're seeing.

```
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');

  const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
  await Test.deleteMany({});
  await Test.create({ name: 'foo' }, { name: null });

  // Prints 1 doc with `name: null`
  console.log(await Test.find({ name: undefined }));
  // Prints 2 docs
  console.log(await Test.find({}));
}

```
