### ISSUE TITLE
Find recursive records

### ISSUE THREAD

**Issue by aparzi** [Automattic/mongoose#14311]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.2

### Node.js version

20.11-alpine3.19

### MongoDB version

7.0.0

### Operating system

None

### Issue

I have the following structure: 
```
[
    {
        "_id": "65b90267a24dfc8b86a195b8",
        "name_it": "Sport",
        "name_en": "Sport",
        "visibility": false,
        "typology": "product",
        "uri": "http://localhost:4201/Sport",
        "items": []
    },
    {
        "_id": "65b90276a24dfc8b86a195bd",
        "name_it": "Calendari Olandesi",
        "name_en": "Dutch calendar",
        "visibility": false,
        "typology": "category",
        "uri": "http://localhost:4201/Calendari-Olandesi",
        "items": [
            {
                "name_it": "Calendari classici",
                "name_en": "Classic calendar",
                "visibility": false,
                "typology": "category",
                "uri": "http://localhost:4201/Calendari-Olandesi/Classici",
                "_id": "65b9028ea24dfc8b86a195c8",
                "items": [
                ... recursive objects
                ]
            }
        ]
    }
]
```

I would like to recover the items where the URI property includes a string that comes to me as input, then return the documents (atomically) that include the string.
For example in my case in input I have "Classici" string, my output should be:
```
 {
         "name_it": "Calendari classici",
         "name_en": "Classic calendar"
         "visibility": false,
         "typology": "category",
          "uri": "http://localhost:4201/Calendari-Olandesi/Classici",
          "_id": "65b9028ea24dfc8b86a195c8",
}
```

Thanks for helping

**Comment by vkarpov15** [comment]
Try the following:

```javascript
Model.find({ 'items.name_it': /Classici/ }).select({ 'items.$': 1 })
```

Then for each document in the result set, `items` will contain the first element of `items` whose `name_t` property matches /Classici/. [More info in MongoDB docs](https://www.mongodb.com/docs/manual/reference/operator/projection/positional/#:~:text=Definition,-%24&text=The%20positional%20%24%20operator%20limits%20the,array%20element%20in%20selected%20documents.). Is this helpful?
