### ISSUE TITLE
Add 'promise' return value to model save operation

### ISSUE THREAD

**Issue by wshaver** [Automattic/mongoose#1431]
Add promise return support to save operation, currently returns undefined. There are multiple return paths depending on validation and save state that would need to be updated. This would allow chaining of multiple save operations with .then() instead of nesting.

**Comment by jhullfly** [comment]
Here is what I did for now. Obviously Q is not needed but that is what I use for promises elsewhere. 
```javascript
/*
 * Hack until mongoose 3.10 comes out. See this: https://github.com/LearnBoost/mongoose/issues/1431
 */
mongoose.Document.prototype.savePromise = function () {
    var that = this;
    return Q.Promise(function(resolve, reject) {
        that.save(function (err, item, numberAffected) {
            if (err) {
                reject(err);
            }
            resolve(item, numberAffected);
        });
    });
};

mongoose.Document.prototype.removePromise = function () {
    var that = this;
    return Q.Promise(function(resolve, reject) {
        that.remove(function (err, item) {
            if (err) {
                reject(err);
            }
            resolve(item);
        });
    });
};

**Comment by MattTW** [comment]
+1 on the hack @jhullfly however I think Q's resolve only takes one argument so numberAffected is dropped, need to put them in an array or something to get access to both:

```javascript
mongoose.Document.prototype.savePromise = function () {
    var that = this;
    return Q.Promise(function(resolve, reject) {
        that.save(function (err, item, numberAffected) {
            if (err) {
                reject(err);
            }
            resolve([item, numberAffected]);
        });
    });
};
```

**Comment by zekenie** [comment]
1+ for promise being returned from save!

**Comment by tiaoshi** [comment]
Now `save` returns promise in 4.0.1. Cheers.

**Comment by Ouwen** [comment]
+1

**Comment by hgenru** [comment]
@arathael +1

**Comment by limianwang** [comment]
Are there documentation related to how `save` is used with Promises? 

I tried the following and it didn't seem to work:

```js
var User = mongoose.model('User');
var u = new User();
u.save().then(function() {
// never gets here.
});
// I even tried the following, and neither works.
u.save().then(function() {}).end();
```

**Comment by Ouwen** [comment]
Are you on mongoose 4.0.1 and did you npm install it?

**Comment by limianwang** [comment]
@Ouwen Yes I'm running 4.0.1 and yes i did or else i would've gotten an error if mongoose wasn't installed.

**Comment by Ouwen** [comment]
Hmmm, very strange. I know that I was running 3.8.8 and forgot to npm install to up it to 4.0.1 which is why a promise was not returned from u.save()

What you have written should work.

**Comment by CrabDude** [comment]
@limianwang I'm seeing the same thing right now. Query is being executed, but promise is never resolving or rejecting. Very strange...

Confirmed: mongoose@4.0.1

**Comment by vkarpov15** [comment]
@limianwang are you connecting successfully to a mongodb server? Can you provide me a standalone example that reproduces this?

**Comment by shakiba** [comment]
It seems that promise object returned by .save() is not the same as other promises, it has catch/caught instead of onReject.

**Comment by xrado** [comment]
mongoose 4.1.10 and ...
```javascript
var u = new User();
u.save().then(...)
```
still do not return promise

**Comment by vkarpov15** [comment]
@xrado please provide a more substantial example. We have tests in place to show that should work in mongoose 4.1.10.

**Comment by xrado** [comment]
@vkarpov15 my bad, I have try it again and works ..I don't know what I was doing before ..sorry

**Comment by nickjohngray** [comment]
I have the same issue, Save saves the data to the db right away and does not call the code in the then. The strange thing is that I had another peace of code that did call the then block and the promise worked.

Code ( the  user.save() part saves it, then is not defined but never called )

 user.save().then( function(userX) {
        console.log(2);
     }).end()
      .then(undefined, function(err){
        console.log('err:' + err );
      });

**Comment by vkarpov15** [comment]
@nickjohngray glad you figured it out :) I strongly recommend you read the [promises guide on the docs](http://mongoosejs.com/docs/promises.html) before continuing to use promises with mongoose though - don't worry, its a short read.

**Comment by jhyland87** [comment]
Im having the same issue... Id really hope I dont have to downgrade an entire major release just to get a save to work inside a promise.

**Comment by vkarpov15** [comment]
@jhyland87 please provide code samples so I can see what the issue is.

**Comment by jhyland87** [comment]
@vkarpov15 I did, in the [ticket](https://github.com/Automattic/mongoose/issues/3865)

**Comment by jhyland87** [comment]
This was fixed in the other ticket...

Basically, this code:
```javascript
var User = mongoose.model('User');
var u = new User();
u.save().then(function() {
// never gets here.
});
```
Just needed a `return` added when saving a doc.. so:
```javascript
var User = mongoose.model('User');
var u = new User();
return u.save().then(function() {
// never gets here.
});
```

**Comment by Jeff-Lewis** [comment]
@jhyland87, FYI - another example of [chaining promises with Mongoose](http://stackoverflow.com/a/27946372/589574).

**Comment by SauceCode84** [comment]
Is this still an issue?

I have the following code (using TypeScript)...

```typescript
User.findById(id)
.exec()
.then((user) => {
  user.name = 'new name from wherever!';
  return user.save();
})
.then((user) => {
  // want to do more stuff with the user object once it has been saved successfully...
  // ... but it never makes it here!!!
};
```

However, when I add an empty callback to the `save()` function, then all seems well, as below...
```typescript
User.findById(id)
.exec()
.then((user) => {
  user.name = 'new name from wherever!';
  return user.save(() => {
    // unwanted empty callback... hmmm?
  });
})
.then((user) => {
  // we made it here!!! but now...
  // user === undefined :(
};
```

**Comment by vkarpov15** [comment]
Are you using mpromise? Try switching to `mongoose.Promise = global.Promise;`
