### ISSUE TITLE
Unable to Subscribe to Certain MongoDB Client Events Before Connection

### ISSUE THREAD

**Issue by Klem3n** [Automattic/mongoose#14329]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.1

### Node.js version

20.5.1

### MongoDB server version

6.0

### Description

In the current implementation of Mongoose, it is impossible to listen to specific MongoDB client events such as connectionPoolCreated, connectionCreated, connectionCheckOutStarted, and connectionCheckedIn. These events are crucial for monitoring and debugging purposes, but they are emitted during the initial connection process. Since these events occur when MongoClient connects, it is not possible to subscribe to them at the moment. That is because the MongoClient instance is created and instantly connected with no way of getting the MongoClient instance before it starts connecting [See connection.js#301](https://github.com/Automattic/mongoose/blob/master/lib/drivers/node-mongodb-native/connection.js#L301).

Possible solution:

1. If ```this.readyState = STATES.connecting;``` ([Line](https://github.com/Automattic/mongoose/blob/master/lib/drivers/node-mongodb-native/connection.js#L288)) is set after the client has been initialized, the client can be accessed in "connecting" connection event and the events can be subscribed to there. But that means if client fails to initialize the "disconnected" event will be called without "connecting" event.

2. Add a new event that gets triggered after mongoClient is created so that events can be subscribed to in there.

### Steps to Reproduce

```
import mongoose from "mongoose";

// Replace 'your_connection_string' with your actual MongoDB connection string
const uri = "your_connection_string";

console.log(
  "Client exists before connecting?: ",
  !!mongoose.connection.getClient()
);

mongoose.connection.on("connecting", () => {
  console.log(
    "Client exists during connecting?: ",
    !!mongoose.connection.getClient()
  );
});

await mongoose.connect(uri);

const client = mongoose.connection.getClient();

console.log("Client exists after connecting?", !!client);

if (client) {
  client.on("connectionPoolCreated", () => {
    console.log("This will not get called!");
  });

  client.on("connectionCreated", () => {
    console.log("This will not get called!");
  });
}
```

Workaround I'm using:

```
const originalMongoClientConnect = mongodb.MongoClient.prototype.connect;

// eslint-disable-next-line func-names
mongodb.MongoClient.prototype.connect = async function (...args) {
  // Subscribe to MongoClient events here.

  return originalMongoClientConnect.apply(this, args);
};
```

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

// Replace 'your_connection_string' with your actual MongoDB connection string
const uri = "mongodb://localhost:27017";

console.log(
  "Client exists before connecting?: ",
  !!mongoose.connection.getClient()
);

mongoose.connection.on("connecting", () => {
  console.log(
    "Client exists during connecting?: ",
    !!mongoose.connection.getClient()
  );
});

async function run() {
  await mongoose.connect(uri);

  const client = mongoose.connection.getClient();
  
  console.log("Client exists after connecting?", !!client);
  
  if (client) {
    client.on("connectionPoolCreated", () => {
      console.log("This will not get called!");
    });
  
    client.on("connectionCreated", () => {
      console.log("This will not get called!");
    });
  }

}

run();
```

**Comment by vkarpov15** [comment]
You can get the `connectionPoolCreated` event using the following:

```
async function run() {
  const p = mongoose.connect(uri);

  const client = mongoose.connection.getClient();
  
  console.log("Client exists after connecting?", !!client);
  
  if (client) {
    client.on("connectionPoolCreated", () => {
      console.log("connectionPoolCreated");
    });
  
    client.on("connectionCreated", () => {
      console.log("connectionCreated");
    });
  }
  await p;

}
```

The above code prints:

```
$ node gh-14329.js 
Client exists before connecting?:  false
Client exists during connecting?:  false
Client exists after connecting? true
connectionPoolCreated
^C
$ 
```

Still no "connectionCreated", I'm checking why that isn't emitted.

**Comment by vkarpov15** [comment]
I checked and "connectionCreated" is emitted when the MongoDB Node driver needs to create a new socket to send an operation to MongoDB, so you need to actually execute a `find()` or some other MongoDB operation as follows to print "connectionCreated":

```javascript
async function run() {
  const p = mongoose.connect(uri);

  const client = mongoose.connection.getClient();
    
  console.log("Client exists after connecting?", !!client);
    
  if (client) {
    client.on("connectionPoolCreated", () => {
      console.log("connectionPoolCreated");
    });
  
    client.on("connectionCreated", () => {
      console.log("connectionCreated");
    });
  }
  await p;

  await client.db().collection('test').insertOne({ answer: 42 });
  console.log('Done');
}
```
