### ISSUE TITLE
Add withSession() function

### ISSUE THREAD

**Issue by marosstruk** [Automattic/mongoose#14330]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add withSession() function that would handle session's object lifetime. It should be analogous to the withTransaction() function.

For more details, see MongoDB driver documentation: https://mongodb.github.io/node-mongodb-native/6.3/classes/MongoClient.html#withSession

### Motivation

There are two reasons why I believe withSession() function is required:

1. **Ease of use**
    - Currently, to use a session, it is required to call two functions (startSession, endSessions) and handle any potential exceptions with a catch statement.
    - It would be much more convenient for most use-cases to have this logic abstracted to an out-of-the-box function.
     
2. **Consistency**
    - There already is withTransaction function that handles transaction lifecycle, so it is natural to expect there to be a similar function for the session object.

**Comment by vkarpov15** [comment]
Are you using sessions without transactions? If so, what's your use case?
