### ISSUE TITLE
error :  MongoNetworkError: connection 467 to *IP*:27017 closed

### ISSUE THREAD

**Issue by meibassam** [Automattic/mongoose#14332]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^5.10.15

### Node.js version

14.16

### MongoDB server version

5

### Description

while migrating my data from Postgres to Mongo, divided my data 500k to bulks, and each bulk inserting 1000 rows to Mongodb, after some time it showed this error : 
```
Error in migrateListenTracks: MongoNetworkError: connection 467<different number each time> to *IP*:27017 closed
    at Connection.handleIssue (/node_modules/mongodb/lib/cmap/connection.js:131:15)
    at TLSSocket.<anonymous> (/node_modules/mongodb/lib/cmap/connection.js:64:35)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:529:15)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```
### Steps to Reproduce

    const pgListenTrackQuery = 'SELECT * FROM "SOMETHING" LIMIT 500000';

    const { rows: pgListenTrackResult } = await pgClient.query(pgListenTrackQuery);

    const batchSize = 1000;
    const totalRecords = pgListenTrackResult.length;

    let bulkInsertData = [];
    for (let i = 0; i < totalRecords; i += batchSize) {
      const batch = pgListenTrackResult.slice(i, i + batchSize);

      bulkInsertData = [];
      const listenTracksBatch = await Promise.all(
        batch.map(async (listenData) => {
          const track = await Track.findOne({ _id: listenData.track_id });
          const user = await User.findOne({ _id: listenData.user_id });
            const listen = {
              user: user,
              track: track,
            };

            return listen;
          
        })
      );

      bulkInsertData.push(...listenTracksBatch);
      await ListenTrack.insertMany(bulkInsertData);
    }

### Expected Behavior

should complete all migration successfully without showing any error

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script runs fine for me on Mongoose 5.13.22:

```javascript
'use strict';
  
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const User = mongoose.model('User', mongoose.Schema({ _id: Number, name: String }));
  const Track = mongoose.model('Track', mongoose.Schema({ _id: Number, title: String }));
  const ListenTrack = mongoose.model('ListenTrack', mongoose.Schema({ user: Number, track: Number }));

  const totalRecords = 500000;
  const numUsers = await User.countDocuments({});
  for (let i = numUsers; i < totalRecords; ++i) {
    await User.create({ _id: i, name: `User ${i}` });
  }
  const numTracks = await Track.countDocuments({});
  for (let i = numTracks; i < totalRecords; ++i) {
    await Track.create({ _id: i, name: `Track ${i}` });
  }

  const batchSize = 1000;

  let bulkInsertData = [];
  for (let i = 0; i < totalRecords; i += batchSize) {
    console.log(`${i} / ${totalRecords}`);
    const batch = [];
    for (let j = 0; j < batchSize; ++j) {
      batch.push({ track_id: i + j, user_id: i + j });
    }

    bulkInsertData = [];
    const listenTracksBatch = await Promise.all(
      batch.map(async (listenData) => {
        const track = await Track.findOne({ _id: listenData.track_id });
        const user = await User.findOne({ _id: listenData.user_id });
          const listen = {
            user: user,
            track: track,
          };

          return listen;

      })
    );

    bulkInsertData.push(...listenTracksBatch);
    await ListenTrack.insertMany(bulkInsertData);
  }

  console.log('Done');
  process.exit(0);
};
```

The only potential suggestion I can think of would be reducing `batchSize`, and making sure you're able to maintain a consistent connection to the server you're trying to migrate data to.

**Comment by meibassam** [comment]
Thanks Valeri, I appreciate your help

**Comment by vkarpov15** [comment]
Did you end up fixing the issue?
