### ISSUE TITLE
Upload latest version (8.1.2) to the official npm registry

### ISSUE THREAD

**Issue by IsakTheHacker** [Automattic/mongoose#14345]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

The newest version (8.1.2) does not seem to have been uploaded to npm.

**Comment by vkarpov15** [comment]
Just released. I'm sorry for the trouble.

**Comment by vkarpov15** [comment]
![image](https://github.com/Automattic/mongoose/assets/1620265/5a4c7814-c07d-4451-9748-6b219d1a0025)
