### ISSUE TITLE
Versioning does not work if the `versionKey` option for `toObject` is set to `false` when using `insertMany`

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#14344]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.1.1

### Node.js version

18.18.2

### MongoDB server version

5

### Description

Quite a specific issue here...

Setting the schema option `toObject` to `{ versionKey: false }` interferes with the versioning mechanism when `Model.prototype.insertMany()` is used. This affects `optimisticConcurrency` too.

Debug logs print:

```
Mongoose: mymodels.insertMany([ { name: 'x', _id: new ObjectId('65c6b71554b43144d136c12f') } ], {})
```

Using `Model.prototype.create()` works correctly:

```
Mongoose: mymodels.insertOne({ name: 'x', _id: ObjectId("65c6b745afcd1f760cc117ba"), __v: 0 }, {})
```

Not surprising since the logic for the two methods is deliberately completely separate. Just makes me wonder if there are more edge cases like this one? I.e. what are some other ways of inserting a new document into the database that might not be covered? Perhaps this is something worth looking into.

### Steps to Reproduce

```javascript
import mongoose from "mongoose";
import { MongoMemoryReplSet } from "mongodb-memory-server";

console.log("connecting...");

const mongoDbService = await MongoMemoryReplSet.create();
await mongoose.connect(mongoDbService.getUri());

console.log("connected!");

const schema = new mongoose.Schema(
  { name: String },
  // Could be `optimisticConcurrency` as well
  { versionKey: "__v", toObject: { versionKey: false } }
);

const Model = mongoose.model("MyModel", schema);

// Substituting this for `create()` fixes the problem
await Model.insertMany([{ name: "x" }]);

const doc = await Model.findOne();

console.log(doc.__v); // prints `undefined` when using `insertMany`, and `1` when using `create`

await mongoose.disconnect();

console.log("done!")

process.exit(0);
```

### Expected Behavior

My reasoning is that I set `toObject: { versionKey: false }` because _I_ don't wish to have this field in the output when _I_ invoke `toObject()`. I don't believe it should affect the internal mechanics of the versioning feature though.

**Comment by donoftime2018** [comment]
https://mongoosejs.com/docs/guide.html#versionKey

According to the documentation, you shouldn't be putting versionKey inside toObject. You should put it in the Schema definition like
```
const schema = new mongoose.Schema(
  { name: String },
  // Could be `optimisticConcurrency` as well
  { versionKey: false } //defaults to __v 
);
```

**Comment by donoftime2018** [comment]
@IslandRhythms add process.exit(0) to the end of run() so that the program ends instead of being stuck running run()

**Comment by donoftime2018** [comment]
OK so adding versionKey: false without toObject actually removed __v from 'doc' variable.

**Comment by donoftime2018** [comment]
@juona Does this solve your problem for now? 
```
#!/usr/bin/env node
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema(
  { name: String },
  // Could be `optimisticConcurrency` as well
  { versionKey: '__v' }
);

// testSchema.set('__v', false)

const Test = mongoose.model("Test", testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.insertMany([{ name: 'x' }]);

  const doc = await Test.findOne();

  console.log(doc.__v); # 0

  console.log('done');

  process.exit(0)
}

run();

```

**Comment by juona** [comment]
@donoftime2018 Thanks for the help. This was not a burning issue, I just used `Model.prototype.create()` instead. I will give your method a try in case there is a real _need_ to use `insertMany` (still on v7, you see, so this fix probably does not apply).

@vkarpov15 Thanks, swift as always!
