### ISSUE TITLE
[Question] Do you plan to introduce the bug  fix related to resumeTokenChanged into the 6.0.x version or other 6.x versions 

### ISSUE THREAD

**Issue by 3150** [Automattic/mongoose#14349]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.0.15

### Node.js version

20.10.0

### MongoDB server version

4.4

### Description

Hi! As you have already fixed the bug related to resumeTokenChanged in version 7.x, do you plan to introduce this bug fix into the 6.0.x version or other 6.x versions? Due to version compatibility reasons, I still need to use the 6.0.x version of Mongoose for now.

related issues: https://github.com/Automattic/mongoose/issues/13607

I think the bug can be fixed with this code: https://github.com/3150/mongoose/pull/1/files
This code is pulled from this PR: https://github.com/Automattic/mongoose/pull/13736

### Steps to Reproduce

I think it is the same reason here: https://github.com/Automattic/mongoose/issues/13607

**Comment by vkarpov15** [comment]
Fixed by #14355
