### ISSUE TITLE
Vulnerability issue in nested NPM dependency "IP"

### ISSUE THREAD

**Issue by ArchitaSarda** [Automattic/mongoose#14354]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.11.3

### Node.js version

18.17.0

### MongoDB server version

4.17.1

### Description

High vulnerability issue noticed: NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks  
Package: ip
Dependency of: mongoose@6.11.3
Path:  mongoose > mongodb > socks > ip 
More info: https://github.com/advisories/GHSA-78xj-cgh5-2h22

Please add support to remove this vulnerability threat in mongoose major version 6.
  

### Steps to Reproduce

Use any version in 6.x.x of mongoose.
Run "yarn audit" after installing the dependencies.
You will be able to see this error.

**Comment by tecnologiaskeelo** [comment]
Any updates here? Did you solve the problem @ArchitaSarda ?

**Comment by vkarpov15** [comment]
@tecnologiaskeelo yeah, just reinstall, or bump the version of `ip` in your `package-lock.json`. The upstream dependency is `ip@^2.0.0` and ip released v2.0.1 with the fix, so a clean install or an updated `package-lock.json` should resolve this warning.
