### ISSUE TITLE
Mongoose / mongo omitting part of the document when saved

### ISSUE THREAD

**Issue by pauIbanez** [Automattic/mongoose#14366]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.1

### Node.js version

v16.14.0

### MongoDB server version

5.6.0

### Typescript version (if applicable)

5.1.6

### Description

So I'm getting a document, adding an object to an array and then saving the doc. So far so good, except that part of the created doc is just not saved at all, it's as if the validation swallows part of it, because the document gets saved to the database, but with a missing object.

So far I'm unable to reproduce, that's why I've recorded this to show exactly what happens to me:
https://drive.google.com/file/d/1bwArVYXDlMSni9UAsJVuVXSoCEt3z-Cl/view?usp=sharing

So far I've tried changing names, dropping the collection and re-trying from scratch, requiring or not the object in question, setting a default value for the object which, basically bypasses the required but sill does not add the object.

I'm out of ideas, am I missing something or is this a bug? even if I can't reproduce. Is anyone else able to reproduce?

I can continue my development since I do not require that specific part yet, but it'd be really great to have some more info on this, even it's just a "hey dumbass u missed this!". 

Thank you so much in advance

### Steps to Reproduce

N/A

### Expected Behavior

I'd expect the object to be saved in it's entirety.

**Comment by IslandRhythms** [comment]
Please modify the below script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: [{ firstName: String, lastName: String, alive: Boolean }]
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Test.create({
    name: [{ firstName: 'Test', lastName: 'Testerson', alive: true }]
  });

  const doc = await Test.findOne();
  doc.name.push({ firstName: 'Quiz', lastName: 'Quizerson', alive: true });
  await doc.save();
  const check = await Test.findOne();
  console.log('what is check', check, check.name);
}

run();
```

**Comment by pauIbanez** [comment]
I will try to reproduce the issue again, but as I've said, so far I've not been successful in doing so.

I could share exactly the part of my current codebase that causes the issue if that's something that will help
