### ISSUE TITLE
query.sort(null) should reset the sort options

### ISSUE THREAD

**Issue by caub** [Automattic/mongoose#14365]
### 🚀 Feature Proposal

Calling `.sort(null)` should allow to unset whatever was set as a sort previously (in `query.options.sort`)

### Motivation

Sometimes it's useful to override default behaviors from plugins, later in the query chain

Similar to https://github.com/Automattic/mongoose/issues/14180

### Example

```
q=I.find().sort({ startDate: -1, _id: -1 });

q.options.sort // { startDate: -1, _id: -1 }

q.sort(null); // reset sort (doesn't work currently)
q.sort({ _id: -1 }); // this doesn't overwrite a previous non-null sort

q.options.sort // now is { _id: -1 }, but in current version it still returns { startDate: -1, _id: -1 }
```

I'm proposing `.sort(null)`, but I've tried using `.setOptions(null)` or `.setOptions({})` or `.setOptions({sort: {_id: -1}})` without success. Any way would be fine

**Comment by caub** [comment]
@vkarpov15 sorry for pinging, but maybe I'm missing something here? I'd like to be able to reset a query's sort so I can set something else on the same query instance

**Comment by FaizBShah** [comment]
To change sort options, you can try `q.setOptions({})`, and to check whether it has changed or not, you can check it by doing `console.log(q.getOptions())`

For example:
```
const query = User.find().sort({ age: 1 });
query.setOptions({ sort: { age: -1 } });
console.log(query.getOptions()); // Printing { sort: { age: -1 } }
```

Just FYI, this is for mongoose@8.1.3

**Comment by caub** [comment]
@FaizBShah Doesn't work, for example with a sort with 2 fields, and a reset, the previous fields can't be unset

https://replit.com/@caub/mongoose-sort-up#index.js

```js
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String,
});

const Test = mongoose.model('Test', testSchema);

const q = Test.find().select('name').sort({ name: -1, _id: -1 });

console.log(q.getOptions());

// q.setOptions({});
q.setOptions({sort: {_id: 1}});

console.log(q.getOptions());
```

```
{ sort: { name: -1, _id: -1 } }
{ sort: { name: -1, _id: 1 } }
```

**Comment by probro27** [comment]
@caub @FaizBShah Hey guys, I am trying to work on some open source issues and I came across this one. I understand the use case you guys want to implement, and I think it can be supported by modifying this function [here](https://github.com/Automattic/mongoose/blob/master/lib/query.js#L2869):

In case you agree on how and if you are going to implement it, please reach out to me and I would love to take this up. Thanks :)

**Comment by FaizBShah** [comment]
@caub I think I found the solution. To override the current options object, you just need to pass the 2nd parameter (which stands for override) in `setOptions()` as true.

```
const query = User.find().sort({ grade: 1, age: 1 });
console.log(query.getOptions()); // Prints { sort: { grade: 1, age: 1 } }
query.setOptions({ sort: { age: -1 } }, true);
console.log(query.getOptions()); // Prints { sort: { age: -1 } }
```

I hope this helps you!!

**Comment by FaizBShah** [comment]
@vkarpov15 Currently there is no mention of the `override` parameter for `setOptions()` in the [doc](https://mongoosejs.com/docs/api/query.html#Query.prototype.setOptions()). Also, there is no mention of what the params do when Im typing the function name in the project, as it only displays this [text](https://github.com/Automattic/mongoose/blob/master/types/query.d.ts#L698).

Can I create a PR to add this?

**Comment by caub** [comment]
@FaizBShah Amazing find, thanks very much

We should maybe do `query.setOptions({...query.getOptions(), sort: newSort})` in case there are other fields in options (limit, skip for example)

Maybe we could add a `.setSort(value[, shouldOverride])` method?

**Comment by vkarpov15** [comment]
@caub @FaizBShah I put in PR #14375 with a potential fix, can you please let me know what you think?
