### ISSUE TITLE
not getting validation error even i am using validate method in my schema

### ISSUE THREAD

**Issue by rahulvikramchauhan** [Automattic/mongoose#14368]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

8.1.1

### Slowed down in version

NA

### Node.js version

21.6.1

### 🦥 Performance issue

i am learning mongodb , for that i am using moogoose for query . i created a scheme where i provided type info and validate option in schema. in that i have a name key where i use type as String and also use validate method . And when i am passing wrong data to my name key it is not throughing validation error even i have validate method . i tried everything i can do, but i can't find any solution

### Steps to Reproduce

https://github.com/rahulvikramchauhan/natoursApp,
above is repo location, schema is in database ,
issue comming when i am creating a document , document creation is in tourHandler under createTours

**Comment by vkarpov15** [comment]
Without more info as to what the wrong data is, there's no way for us to make a reasonable guess as to what's going on here. One potential explanation is that Mongoose automatically casts data to the correct type, so if you call `tours.create(tourData)` where `tourData.name` is a number, Mongoose will automatically convert the number to a string for you. Does that help?
