### ISSUE TITLE
MongoNetworkTimeoutError crashes nodejs process

### ISSUE THREAD

**Issue by LvChengbin** [Automattic/mongoose#14377]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.0

### Node.js version

19.4.0

### MongoDB server version

6.2.0

### Typescript version (if applicable)

5.2.2

### Description

`MongoNetworkTimeoutError` crashes my process even though I catch the error with `connection.on( 'error', () => {} )`.
The `error` event is triggered while the server isn't reachable, but the process is crashed.

### Steps to Reproduce

```ts
const connection = mongoose.createConnection( uri, options );
connection.on( 'error', e => { console.log( e ) } );
```

**Comment by IslandRhythms** [comment]
Need more details. What's your connection string look like. What else are you doing?

**Comment by LvChengbin** [comment]
I want to say that when there's a connection error, The error should be catchable instead of crashing the process, without asking why the connection timed out.

**Comment by vkarpov15** [comment]
In general, we would recommend handling errors using `asPromise()`, like `const conn = await mongoose.createConnection(uri).asPromise()` rather than relying on `on('error')`, but we'll fix this issue.
