### ISSUE TITLE
fix: Cannot run `mongoose.createConnection` under `tsx`/ `esbuild`/ `bun` due to the `nextConnectionId`

### ISSUE THREAD

**Issue by mr-kelly** [Automattic/mongoose#14373]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.0

### Node.js version

18.19.0

### MongoDB server version

mongo:latest (docker)

### Typescript version (if applicable)

5.3.3

### Description

I'm experiencing an issue when using `tsx`, `esbuild` and `bun`.

When running under tsx, everything appears to be functioning correctly when . 
However, when executing `mongoose.createConnection`, I encounter a problem. 

The error message shows a different environment, but the error occurs on the same line of code. 

Here are the images illustrating the issue:

1. Under tsx run:

<img width="832" alt="image" src="https://github.com/Automattic/mongoose/assets/520852/6960706f-740d-4d8a-8e49-3f15a022b2cb">

2. After building and running `bun run` server.js:

<img width="809" alt="image" src="https://github.com/Automattic/mongoose/assets/520852/5239ee5c-9d16-4773-880e-604c13ee7ff7">

Different environment but same line code error: 
<img width="526" alt="image" src="https://github.com/Automattic/mongoose/assets/520852/1ddb8901-61c3-42f8-a3e3-eeba070fca55">

Additionally, I want to mention that all other behaviors except for Mongoose are working correctly.

### Steps to Reproduce

| Command | Work | ERROR |
| --- | --- | -- | 
| tsx server.ts |  ❌  | TypeError: Cannot set property nextConnectionId of #<Mongoose> which has only a getter\n    at Mongoose.createConnection |
| esbuild server.ts && node server.js | ❌ |  TypeError: Cannot set property nextConnectionId of # which has only a getter\n at Mongoose.createConnection |
| bun run server.ts | ✅ | SUCCESS | TypeError: Cannot set property nextConnectionId of #<Mongoose> which has only a getter\n    at Mongoose.createConnection |
| bun build server.ts && bun run server.js| ❌ | TypeError: Attempted to assign to readonly property. |
| bun build --compile server.ts && bun run server.js| ❌ | TypeError: Attempted to assign to readonly property. |
| next dev | ✅ | SUCCESS |
| next build | ✅ |  SUCCESS |

### Expected Behavior

Run success all of these runtime and environments.

**Comment by mr-kelly** [comment]
Ok.

If I stop using the `mongoose.createConnection` and use `mongoose.connect` instead,  it solved.

<img width="556" alt="image" src="https://github.com/Automattic/mongoose/assets/520852/db119769-32ba-4a1f-ad86-63d442823560">

**Comment by vkarpov15** [comment]
I'm unable to repro, I tried running the following script:

```ts
import mongoose from 'mongoose';

mongoose.createConnection('mongodb://127.0.0.1:27017/mongoose_test');
console.log('Done');
```

with tsx:

```
$ ./node_modules/.bin/tsx gh-14373.ts 
Done
```

and bun v1.0.29:

```
$ bun build --compile gh-14373.ts && ./gh-14373 
  [89ms]  bundle  593 modules
 [198ms] compile  gh-14373
Done
^C

```

Also, it looks from your stack trace that you're creating a new mongoose connection in your `createMission()` function, which makes it seem like you might be creating a new connection on every request. We generally recommend against doing that.
