### ISSUE TITLE
Missing Typescript detail on Mongoose-specific `options` for updateOne, updateMany, etc. 

### ISSUE THREAD

**Issue by sderrow** [Automattic/mongoose#14378]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.0

### Node.js version

18.18.0

### MongoDB server version

7.0

### Typescript version (if applicable)

4.5.2

### Description

In #14342 , the `MongooseQueryOptions` type was edited to include `& { [other: string]: any }` in order to support arbitrary options. Arbitrary options are fine, but the specific implementation broke Typescript support for all of the official Mongoose option properties, in the sense that there's no more auto-completion or in-line JSDoc displayed when you start typing something like "runValidators".

This is caused by the use of the `Omit` Typescript utility in the type for `options` in `updateOne`, `updateMany`, and a few others. Since now `Omit` is being called on a type that has `[other: string]: any` in it, that particular weak "other" property essentially wipes out all the official properties (I think due to the underlying implementation of `Exclude`).

### Steps to Reproduce

```ts
export const queryOptionTypeTest = async (): Promise<void> => {
  type Test = {
    _id: mongoose.Types.ObjectId;

    testProp: string;

    createdAt: number;
    updatedAt: number;
  };

  const schema = new mongoose.Schema<Test>(
    {
      testProp: { type: String },
      createdAt: { type: Number },
      updatedAt: { type: Number },
    },
    {
      timestamps: { currentTime: () => new Date().valueOf() },
    }
  );

  const M = mongoose.model<Test>("Test", schema);

  // Typescript offers no help for the `timestamps` or `runValidators` options below.
  // It treats them as if they were arbitrary options instead of formal ones with known meanings
  await M.updateMany({}, { testProp: "hello" }, { timestamps: false, runValidators: true }).exec();
};
```
Here's a screenshot of my IDE with the bug and trying to auto-complete the "timestamps" options. You can see it only shows "maxTimeMS" instead. 
![updateOptionsBugWithoutFix](https://github.com/Automattic/mongoose/assets/28607517/12be08c5-2737-496f-8f93-65d14b378f7d)

### Expected Behavior

Here's what I would expect my IDE to show me. You can see it includes auto-complete and helpful documentation for "timestamps" now.
![updateOptionsBugWithFix](https://github.com/Automattic/mongoose/assets/28607517/bc4bce3a-3e62-43c3-9c9e-a14254464db5)

**Comment by FaizBShah** [comment]
Hi @sderrow , I tried to solve this issue in a different manner by not introducing new base types. Basically, replaced `Omit` with a custom util `ExcludeKeys` which fixes the issue caused by Omit. Do review the PR and tell whether it looks ok to you? https://github.com/Automattic/mongoose/pull/14382

**Comment by sderrow** [comment]
@FaizBShah thanks! Your implementation looks good to me. I don't have a strong opinion on implementation. The one additional upside to creating formal types for the base and update query options like I did in #14379 is being able to re-use them instead of having to redeclare the same exclusion of keys across multiple methods. A bit more DRY. But defer to core devs on this one!

**Comment by FaizBShah** [comment]
@sderrow Yes, agree with the re-use factor and DRY advantage of the base formal types. I also side with deferring this to the core devs!!
