### ISSUE TITLE
Convenience Method for Converting Array of Strings to ObjectIDs

### ISSUE THREAD

**Issue by rakibul0310** [Automattic/mongoose#14381]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Introduce a built-in method in Mongoose to facilitate the conversion of an array of string _ids to MongoDB ObjectIDs.

### Motivation

Currently, when developers need to convert an array of string _ids to MongoDB ObjectIDs, they have to manually iterate over the array and perform the conversion, which can be cumbersome and error-prone, especially in scenarios involving large arrays. By providing a built-in method for this common task, Mongoose can simplify the development process and improve code readability and reliability.

### Example

`const mongoose = require('mongoose');`

// Example array of string _ids
const idStrings = ["61cbb7e4b148780364a3f9a7", "61cbb7e4b148780364a3f9a8", "61cbb7e4b148780364a3f9a9"];

// Convert array of string _ids to ObjectIds
const objectIds = mongoose.Types.ObjectIds(idStrings);

console.log(objectIds);

**Comment by FaizBShah** [comment]
The above suggested feature is using a constructor function, which I feel is not the best place to return an array of objects according to good coding designs.

You can create the array of objectIds in the following manner too:
```
const objectIds = idStrings.map((idString) => new mongoose.Types.ObjectId(idString));
```

There can be a new function be implemented on the `Types.ObjectId` to do that, but I feel a single ObjectId class should only be dealing with creating and managing a single ObjectId (that's just my opinion though)

**Comment by rakibul0310** [comment]
Thank you for your feedback and suggestion. I appreciate your perspective on keeping the ObjectId class focused on managing single ObjectId instances.

Given your suggestion, would it be feasible to consider adding a utility function to Types.ObjectId for converting an array of string _ids to ObjectIDs? This approach would provide a cleaner and more concise way to handle this common task without deviating from the core responsibilities of the ObjectId class.

I believe such a utility function could improve developer experience and code readability while aligning with best practices in code organization.

**Comment by zspitz** [comment]
> You can create the array of objectIds in the following manner too:
> 
> ```
> const objectIds = idStrings.map((idString) => new mongoose.Types.ObjectId(idString));
> ```
> 

Why do you think this is not "clean" or "concise"? Why is this problematic?
