### ISSUE TITLE
Filter query `Condition` type might as well be `any`

### ISSUE THREAD

**Issue by sderrow** [Automattic/mongoose#14397]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.0

### Node.js version

18.18.0

### MongoDB server version

7.0

### Typescript version (if applicable)

4.5.2

### Description

The following appears in [query.d.ts](https://github.com/Automattic/mongoose/blob/4b34967e0c2d33fe3440e0742672dd47e01c0a0c/types/query.d.ts#L4-L9):
```ts
export type ApplyBasicQueryCasting<T> = T | T[] | (T extends (infer U)[] ? U : any) | any;
type Condition<T> = ApplyBasicQueryCasting<T> | QuerySelector<ApplyBasicQueryCasting<T>>;

type _FilterQuery<T> = {
  [P in keyof T]?: Condition<T[P]>;
} & RootQuerySelector<T>;
```

The `| any` union in `ApplyBasicQueryCasting<T>`, means that `ApplyBasicQueryCasting` is `any`, which carries through to `Condition<T>` being `any` as well.

I think that defeats the purpose of the `Condition` type in the first place, since now there's no support for prompting the user with valid Mongo operators like `$regex` and `$gte` or displaying type errors if you try to pass an invalid value into such an operator (e.g., `{ $regex: 402 }` or `{ $exists: "hello" }`).

### Steps to Reproduce

```ts
type Test = {
  name: string;
  age: number;
};

// No Typescript error below even though `$regex` cannot be passed a number
// Additionally, there's no auto-complete help for the values of the query object
export const query: FilterQuery<Test> = { name: { $regex: 10 } };
```

### Expected Behavior

Additional Typescript support when it comes to writing filter queries. I understand there's a need for `any`, but is it possible to do it without sacrificing the operator help?

**Comment by FaizBShah** [comment]
@sderrow I think I do have a solution on fixing this, but is there any condition where the `any` type will be necessary? As far as I know about the filters, I cannot personally remember about any condition which might require the use of `any` type. But maybe I might be wrong, so I'll like to know.

**Comment by FaizBShah** [comment]
I have raised a PR to fix this. Do tell any reviews you have about the code - https://github.com/Automattic/mongoose/pull/14398

**Comment by FaizBShah** [comment]
@sderrow I created a PR to fix this. Do comment any thoughts you have about it? - https://github.com/Automattic/mongoose/pull/14398
