### ISSUE TITLE
pre middleware .save conflict with strict mode

### ISSUE THREAD

**Issue by SaadMu7ammad** [Automattic/mongoose#14399]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.1.3

### Node.js version

20.10.0

### MongoDB version

6.0.8

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

22H2 - windows 11

### Issue

when writing a pre middleware to encrypt the password while saving it shows me an error 
![image](https://github.com/Automattic/mongoose/assets/74321306/5a1173e6-78d5-4139-9c7c-a6647d4b09f1)

No overload matches this call.
  The last overload gave the following error.
    Argument of type '"save"' is not assignable to parameter of type 'RegExp | "insertMany"'.ts(2769)
index.d.ts(413, 5): The last overload is declared here.

and i dont know why that middleware called 

important to know that when removing the strict mode it works well with no issues 

steps to reproduce

add "strict": true in the ts.config

then start creating a model for example a user
```ts
const userSchema = new Schema({
  userId: { type: String, required: true, unique: true },
    password: { type: String, required: true },

  
  })
  ```
 setup the interface for user
```ts
 export interface IUser {
  userId: string;
  password: string;
}
export interface IUserDocument extends IUser,Document {}
```
now just try to add the pre middleware for encrypting the password
```ts
userSchema.pre("save",async function (this: IUserDocument, next: NextFunction) {
    try {
      if (!this.isModified('password')) {
        //to not change password every time we edit the user data
        console.log('password not changed');
        return next();
      } else {
        const salt = await bcrypt.genSalt(10);
        this.password = await bcrypt.hash(this.password, salt);
        console.log('password has been changed');
        next();
      }
    } catch (err) {
      const error = new Error(
        'problem while handling the password',
        404
      );
      next(error);
    }
  }
);
```

and that happended i think
to call that 

    pre<T = THydratedDocumentType>(method: 'save', options: SchemaPreOptions, fn: PreSaveMiddlewareFunction<T>): this;
 
  
from the node_moduels 

not

```
pre<T = TModelType>(method: 'insertMany' | RegExp, options: SchemaPreOptions
```

**Comment by FaizBShah** [comment]
I tried to reproduce your code in my system with the same version, and its working fine, even with `strict: true`. Are you still facing this issue?

**Comment by SaadMu7ammad** [comment]
> I tried to reproduce your code in my system with the same version, and its working fine, even with `strict: true`. Are you still facing this issue?

yup , still having an err

**Comment by vkarpov15** [comment]
Does this error occur when you build your project with TypeScript, or just in your IDE? If with TypeScript, please provide which version of TypeScript you're using.

**Comment by SaadMu7ammad** [comment]
> Does this error occur when you build your project with TypeScript, or just in your IDE? If with TypeScript, please provide which version of TypeScript you're using.

with ts compiler i even cant run the code except removing it
![image](https://github.com/Automattic/mongoose/assets/74321306/342ef2dd-d964-49a3-83b6-896d48a44609)

    "typescript": "^5.3.3"

**Comment by vkarpov15** [comment]
Does this issue only appear in your IDE, or when you try to compile? Also, what is `NextFunction`?

The following code (`gh-14399.ts`) compiles fine with TypeScript 5.3.3 and Mongoose 8.1.3:

```ts
import { Schema } from 'mongoose';

const userSchema = new Schema({
  userId: { type: String, required: true, unique: true },
    password: { type: String, required: true },


});

 export interface IUser {
  userId: string;
  password: string;
}
export interface IUserDocument extends IUser,Document {}

userSchema.pre("save",async function (this: IUserDocument, next: Function) {
  }
);
```

Command and output:

```
$ ./node_modules/.bin/tsc --strict gh-14399.ts 
$
```
