### ISSUE TITLE
Why is updateOne invalid if it does not call the then method

### ISSUE THREAD

**Issue by guda-art** [Automattic/mongoose#14417]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.1.1

### Node.js version

16.20.2

### MongoDB version

7.0.5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

windows 11

### Issue

Firstly, it is effective for me to use it this way, as the database data has changed
```js
const userRoleSchema = new mongoose.Schema(
  {
    role_code: {
      type: Number,
      require: true,
      immutable: true,
      unique: true
    },
    role_desc: {
      type: String,
      require: true
    },
    user: {
      type: [mongoose.SchemaTypes.ObjectId],
      ref: Users,
      required: true
    }
  },
  {
    timestamps: {
      // 文档创建时间
      createdAt: 'created_at',
      // 文档更新时间
      updatedAt: 'updated_at'
    }
  }
);
const UserRoles = mongoose.model('user_roles', userRoleSchema);
UserRoles.updateOne(
  {
    role_code: 1
  },
  {
    $push: {
      user: '65d5ce85f5bb733b460cd3cf'
    }
  }
)
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  });
```

But if I don't call the then method, it will fail. The database has not changed, but there will be no errors. Surprisingly, is this the design of mongoose ？
```js
const userRoleSchema = new mongoose.Schema(
  {
    role_code: {
      type: Number,
      require: true,
      immutable: true,
      unique: true
    },
    role_desc: {
      type: String,
      require: true
    },
    user: {
      type: [mongoose.SchemaTypes.ObjectId],
      ref: Users,
      required: true
    }
  },
  {
    timestamps: {
      // 文档创建时间
      createdAt: 'created_at',
      // 文档更新时间
      updatedAt: 'updated_at'
    }
  }
);
const UserRoles = mongoose.model('user_roles', userRoleSchema);
UserRoles.updateOne(
  {
    role_code: 1
  },
  {
    $push: {
      user: '65d5ce85f5bb733b460cd3cf'
    }
  }
);
```

**Comment by donoftime2018** [comment]
First of all, if you aren't using .then, then you should use await/async. Second of all, you have require for the first 2 schemas then required for the last schema. It should be required for all three

**Comment by vkarpov15** [comment]
When you call `UserRoles.updateOne()`, you're creating a [Mongoose Query instance](https://mongoosejs.com/docs/queries.html), which is meant to be an object for building up a query to MongoDB. Queries aren't executed until you call `exec()`. Or unless you call `then()`, which calls `exec()` under the hood; or unless you use `await`, which calls `then()`.

If you want to execute a query without using `then()`, use the following:

```javascript
UserRoles.updateOne(
  {
    role_code: 1
  },
  {
    $push: {
      user: '65d5ce85f5bb733b460cd3cf'
    }
  }
).exec(); // <-- note the `exec()` here
```
