### ISSUE TITLE
populating a new document then saving stores full populated doc instead of _id

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#1442]
see #1436

**Comment by j718** [comment]
Hi, this seems to be the most relevant issue to my question. Not sure if better to reopen this or start a new issue, but here goes.

I can't seem to save documents after populating

```{javascript}
const a = new A({friend: friend._id})
await a.save()
await a.populate(''friend")
await a.save() // throws error saying that object can't be cast to ObjectId
```

**Comment by vkarpov15** [comment]
@j718 please open a new isue and follow the issue template
