### ISSUE TITLE
Issue with 2dsphere indexes in nested schemas vs subdocuments

### ISSUE THREAD

**Issue by andrewplummer** [Automattic/mongoose#14439]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.1

### Node.js version

18.14.0

### MongoDB server version

6.0.2

### Description

This might be my misunderstanding or an issue with the mongodb driver itself, however I am seeing an issue with creating 2dsphere indexes when using nested schemas vs subdocuments. In the case of subdocuments the index may throw "Can't extract geo keys" under certain conditions. I've boiled it down to the following repro. 

It's difficult to know what's going on here as it seems adding the index itself changes what fields are sent to mongodb, which I'm not sure is expected or not.

### Steps to Reproduce

```js
  mongoose.set('debug', true);

  const schema1 = new mongoose.Schema({
    location: {
      geometry: {
        type: {
          type: 'String',
        },
        coordinates: ['Number'],
      },
    },
  });

  const schema2 = new mongoose.Schema({
    location: {
      type: {
        geometry: {
          type: {
            type: 'String',
          },
          coordinates: ['Number'],
        },
      },
    },
  });

  schema1.index({
    'location.geometry': '2dsphere',
  });

  schema2.index({
    'location.geometry': '2dsphere',
  });

  const Test1 = mongoose.model('Test1', schema1);
  const Test2 = mongoose.model('Test2', schema2);

  await Test1.init();
  await Test2.init();

  const test1 = await Test1.create({
    location: {},
  });
  const test2 = await Test2.create({
    location: {},
  });

  console.info('ONE', JSON.stringify(test1, null, 2));
  console.info('TWO', JSON.stringify(test2, null, 2));
```

the above produces the following error, but only for the second schema:

```
Mongoose: test1.createIndex({ 'location.geometry': '2dsphere' }, { background: true })
Mongoose: test2.createIndex({ 'location.geometry': '2dsphere' }, { background: true })
Mongoose: test1.insertOne({ _id: ObjectId("65f3fa51114a3ca7fa124bfc"), __v: 0 }, {})
Mongoose: test2.insertOne({ location: { geometry: { coordinates: [] }, _id: ObjectId("65f3fa51114a3ca7fa124bff") }, _id: ObjectId("65f3fa51114a3ca7fa124bfe"), __v: 0}, {})
/Users/andrew/Bedrock/model/node_modules/mongoose/node_modules/mongodb/lib/operations/insert.js:48
            throw new error_1.MongoServerError(res.writeErrors[0]);
                  ^

MongoServerError: Can't extract geo keys: { _id: ObjectId('65f3fa51114a3ca7fa124bfe'), location: { geometry: { coordinates: [] }, _id: ObjectId('65f3fa51114a3ca7fa124bff') }, __v: 0 }  unknown GeoJSON type: { coordinates: [] }
    at InsertOneOperation.execute (/Users/andrew/Bedrock/model/node_modules/mongoose/node_modules/mongodb/lib/operations/insert.js:48:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeOperationAsync (/Users/andrew/Bedrock/model/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:106:16) {
  index: 0,
  code: 16755,
  [Symbol(errorLabels)]: Set(0) {}
}
```

### Expected Behavior

Regardless of what should happen here (an error thrown or insert succeeded), I would expect that under these conditions nested documents and subdocuments should behave identically.

If there is a reason that they should not, I would still expect that there is some method (whether in the schema definition itself or when creating new documents) by which a subdocument can avoid sending up the empty `coordinates` array which is what seems to be triggering the index error, however as far as I can tell this cannot be avoided, which seemingly makes using a `2dsphere` index together with a subdocument impossible.

**Comment by vkarpov15** [comment]
The issue is that Mongoose arrays have a default value of `[]` by default. You need to disable this default if you want to avoid empty arrays tripping up 2dsphere indexes:

```javascript

  const schema1 = new mongoose.Schema({
    location: {
      geometry: {
        type: {
          type: 'String',
        },
        coordinates: { type: ['Number'], default: undefined }, // <-- Add `default: undefined` here
      },
    },
  });

  const schema2 = new mongoose.Schema({
    location: {
      type: {
        geometry: {
          type: {
            type: 'String',
          },
          coordinates: { type: ['Number'], default: undefined }, // <-- and here
        },
      },
    },
  });
```

You can also add `default: undefined` to all arrays by default with the following code. Just run the following line of code before you define any schemas:

```javascript
mongoose.Schema.Types.Array.set('default', undefined);
```

**Comment by andrewplummer** [comment]
Excellent! Thank you.
