### ISSUE TITLE
Cannot define discriminator options on a Schema

### ISSUE THREAD

**Issue by forivall** [Automattic/mongoose#14448]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.x.x, 8.x.x

### Node.js version

20.x

### MongoDB server version

7.2.2

### Description

While the `options` for a discriminator can be defined on a [`Model`](https://mongoosejs.com/docs/api/model.html#Model.discriminator()), [`SchemaSubdocument`](https://mongoosejs.com/docs/api/schemasubdocument.html#SchemaSubdocument.prototype.discriminator()) or [`SchemaDocumentArray`](https://mongoosejs.com/docs/api/schemadocumentarray.html#SchemaDocumentArray.prototype.discriminator()), they [cannot be defined on a general `Schema`](https://mongoosejs.com/docs/api/schema.html#Schema.prototype.discriminator()). 

### Steps to Reproduce

```js
const clickedEventSchema = new mongoose.Schema({ element: String }, { discriminatorKey: 'kind' });
eventSchema.discriminator('ClickedEvent', clickedEventSchema, { value: 'click' });
//                                                            ^ this will not be used
const Event = mongoose.model('Event', eventSchema);
const doc = await Event.create({ kind: 'clicked', element: '#hero' });
doc.element; // '#hero'
doc instanceof ClickedModel; // this should be `true`, this will currently be `false`
```

### Expected Behavior

Potential fix: https://github.com/Automattic/mongoose/compare/master...forivall:mongoose:schema-discriminator-options

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const eventSchema = new mongoose.Schema({
  name: String
});
const clickedEventSchema = new mongoose.Schema({ element: String }, { discriminatorKey: 'kind' });
eventSchema.discriminator('ClickedEvent', clickedEventSchema, { value: 'click' });
//                                                            ^ this will not be used
const Event = mongoose.model('Event', eventSchema);

const ClickedModel = mongoose.model('Clicked', clickedEventSchema);


async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  const doc = await Event.create({ kind: 'clicked', element: '#hero' });
  doc.element; // '#hero'
  console.log(doc instanceof ClickedModel); // this should be `true`, this will currently be `false`
  console.log('done');
}

run();
```
