### ISSUE TITLE
How to catch MongoNetworkError: connect ECONNREFUSED in Node when using mongoose.createConnection()

### ISSUE THREAD

**Issue by intersides** [Automattic/mongoose#14455]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.0.0

### Node.js version

21

### MongoDB server version

5.0

### Description

on a lost connection there is no clear way to trap **MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017** 
thrown from: node_modules/mongodb/lib/sdam/topology.js:276:34

The connection is created as 
```javascript
try{
  mongooseConnection = mongoose.createConnection(mongoUri, {
      serverSelectionTimeoutMS: 5000
  });
       ....
}
 catch(e){
    console.error(e);
}
```
### Steps to Reproduce

- create a database connection with a mongo instance that can be shut down at will. After connection all the relative callbacks are triggered (connected, open, etc..).
- shut down the mongo db database. 
- callbacks are triggered (disconnect). connection.readystate changes to 0.
- wait into this dosconnected mode for about 10 seconds

The following appears:
MongoNetworkError: connection 1 to 192.168.32.2:27017 closed
at Connection.onClose (/opt/backend/node_modules/mongodb/lib/cmap/connection.js:124:28)
at Socket.<anonymous> (/opt/backend/node_modules/mongodb/lib/cmap/connection.js:66:46)
at Socket.emit (node:events:519:28)
at TCP.<anonymous> (node:net:337:12) {
[Symbol(errorLabels)]: Set(0) {},
[cause]: undefined 

After 2 more seconds the disconnect callback is triggered and the  following appear:

MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
backend       | 13:31:20 0|main  |     at EventTarget.<anonymous> (/opt/backend/node_modules/mongodb/lib/sdam/topology.js:276:34)
backend       | 13:31:20 0|main  |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
backend       | 13:31:20 0|main  |     at EventTarget.dispatchEvent (node:internal/event_target:757:26)
backend       | 13:31:20 0|main  |     at abortSignal (node:internal/abort_controller:374:10)
backend       | 13:31:20 0|main  |     at TimeoutController.abort (node:internal/abort_controller:396:5)
backend       | 13:31:20 0|main  |     at Timeout.<anonymous> (/opt/backend/node_modules/mongodb/lib/utils.js:1011:92)
backend       | 13:31:20 0|main  |     at listOnTimeout (node:internal/timers:573:17)
backend       | 13:31:20 0|main  |     at process.processTimers (node:internal/timers:514:7) {
backend       | 13:31:20 0|main  |   reason: TopologyDescription {
backend       | 13:31:20 0|main  |     type: 'Unknown',
backend       | 13:31:20 0|main  |     servers: Map(1) { 'mongo1:27017' => [ServerDescription] },
backend       | 13:31:20 0|main  |     stale: false,
backend       | 13:31:20 0|main  |     compatible: true,
backend       | 13:31:20 0|main  |     heartbeatFrequencyMS: 10000,
backend       | 13:31:20 0|main  |     localThresholdMS: 15,
backend       | 13:31:20 0|main  |     setName: null,
backend       | 13:31:20 0|main  |     maxElectionId: null,
backend       | 13:31:20 0|main  |     maxSetVersion: null,
backend       | 13:31:20 0|main  |     commonWireVersion: 0,
backend       | 13:31:20 0|main  |     logicalSessionTimeoutMinutes: null
backend       | 13:31:20 0|main  |   },
backend       | 13:31:20 0|main  |   code: undefined,
backend       | 13:31:20 0|main  |   [Symbol(errorLabels)]: Set(0) {},
backend       | 13:31:20 0|main  |   [cause]: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
backend       | 13:31:20 0|main  |       at connectionFailureError (/opt/backend/node_modules/mongodb/lib/cmap/connect.js:379:20)
backend       | 13:31:20 0|main  |       at Socket.<anonymous> (/opt/backend/node_modules/mongodb/lib/cmap/connect.js:285:22)
       at Object.onceWrapper (node:events:634:26)
       at Socket.emit (node:events:519:28)
      at emitErrorNT (node:internal/streams/destroy:169:8)
       at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
     [Symbol(errorLabels)]: Set(1) { 'ResetPool' },
     [cause]: Error: connect ECONNREFUSED 127.0.0.1:27017
         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
       errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
     address: '127.0.0.1',
       port: 27017
     }
}
}

### Expected Behavior

try{
  mongooseConnection = mongoose.createConnection(mongoUri, {
      serverSelectionTimeoutMS: 5000
  });
       ....
}
 catch(e){
    console.error(e);
}

The Error should have been reported in the catch block

**Comment by IslandRhythms** [comment]
Try adding `.catch(e => console.log(e))` to the create connection code instead of wrapping it in a try catch and see if that helps.

**Comment by intersides** [comment]
No, also asPromise() the mongoose.**createConnection** the catch doesn't get called.

`mongoose.createConnection(params.url, {
        serverSelectionTimeoutMS: 5000
      }).asPromise()
     .then(_connection=>{  ...  })
     .catch(e => console.log(e));`

**Comment by vkarpov15** [comment]
Once initial connection is completed, `await mongoose.createConnection().asPromise()` will not throw an error if the connection is later interrupted.

Given that you aren't properly handling errors in your original post (missing `await` and `asPromise()` with `createConnection()`), the issue is most likely that you aren't correctly handling errors in other parts of your code as well. For example, the following code will throw an uncaught error if the MongoDB server stops:

```javascript
try {
  TestModel.findOne();
} catch (err) {
  handleError(err);
}
```

`TestModel.findOne()` is an asynchronous operation and returns a [thenable](https://masteringjs.io/tutorials/fundamentals/thenable), `try/catch` won't catch errors unless you `await` as follows

```javascript
try {
  await TestModel.findOne();
} catch (err) {
  handleError(err);
}
```

**Comment by sadeghhosseini** [comment]
This might help:

```
process.on('unhandledRejection', (error) => {
        if (error instanceof mongoose.mongo.MongoNetworkError) {
            console.log(error);
        } else {
	    console.log('unhandled rejection: ', error);
	    throw new Error(); // so that other types of unhandled exceptions crash the server!
        }
    });
```
