### ISSUE TITLE
Add `Model.listSearchIndexes()`

### ISSUE THREAD

**Issue by hlebegue** [Automattic/mongoose#14450]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.2

### Node.js version

16.20.2

### MongoDB server version

Atlas latest

### Description

When I use model.createSearchIndex() with an index that already exists, my node application is going down with a SIGTERM

### Steps to Reproduce

Use an existing test case to create a search index, but attempt to create it twice with the same name 
```
//just there 
const vectorModelsSupported = [
		{
			name: 'text_embedding_3_small',
			size: 1536,
			enabled: true
		},
		{ 
			name: 'text_embedding_3_small', 
			size: 1536,
			enabled: true
		}
	]

const EmbeddingSchema = new Schema({
	chunkText: { type: String, maxLength: 32764, default: "" },
	embedding_text_embedding_3_small: { type: Array, maxLength: 1536 },
	embedding_text_embedding_3_large: { type: Array, },
	embedding_text_embedding_ada_002: { type: Array, maxLength: 1536 },
	chunkLen: Number,
	chunkIndex: Number,
	upload: {
		type: ObjectId,
		ref: "upload",
	},
	chunkUrl: { type: String, maxLength: 1000, }, /*ex: #page=2 for PDF or #id for HTML*/
	created: { type: Date, default: Date.now },
	usage: { type: Number },
	status: { type: String, default: "inactive" }, // inactive, active | error, selected, deleted
})

const createSearchIndexes = async () => { 
	
	//debug("createSearchIndexes", "This is the list of indexes:", await embedding.listIndexes())
	debug("createSearchIndexes", "This is the list of indexes:", await embedding.searchIndexes)
	if (!modelsSupported) return;
	
	modelsSupported.forEach((model) =>{
		if (model.enabled){
			
			//const field =
			
			const fields = {}
			fields[`embedding_${model.name}`]=  [
				{
					"dimensions": model.size, // 1536,
					"similarity": "euclidean",
					"type": "knnVector"
				}
			]

			try{
				embedding.createSearchIndex({
					name: model.name, // "text_embedding_3_small",
					definition: {
						"mappings": {
							"fields": fields
							}
						}
					}
				)
			}
			catch (err){
				debug("createSearchIndexes", "Failed to create index for model ",model, err)
			}
		
		}

	})
}

embedding.on('index',(event) => {
	debug("Embedding", "===> This is an index event", event)
	
	createSearchIndexes()

})
```
### Expected Behavior

the createSearchIndex should throw an error I can catch, or there should be an API that returns the search index. 

The Model.listIndexes does not return the search indexes.

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const { Schema } = mongoose;

//just there 
const vectorModelsSupported = [
  {
    name: 'text_embedding_3_small',
    size: 1536,
    enabled: true
  },
  { 
    name: 'text_embedding_3_small', 
    size: 1536,
    enabled: true
  }
]

const EmbeddingSchema = new Schema({
chunkText: { type: String, maxLength: 32764, default: "" },
embedding_text_embedding_3_small: { type: Array, maxLength: 1536 },
embedding_text_embedding_3_large: { type: Array, },
embedding_text_embedding_ada_002: { type: Array, maxLength: 1536 },
chunkLen: Number,
chunkIndex: Number,
upload: {
  type: mongoose.Schema.Types.ObjectId,
  ref: "upload",
},
chunkUrl: { type: String, maxLength: 1000, }, /*ex: #page=2 for PDF or #id for HTML*/
created: { type: Date, default: Date.now },
usage: { type: Number },
status: { type: String, default: "inactive" }, // inactive, active | error, selected, deleted
});

const Test = mongoose.model('Test', EmbeddingSchema);


async function run() {
  await mongoose.connect('mongodb://localhost:27017');

  vectorModelsSupported.forEach((model) =>{
		if (model.enabled){
			
			//const field =
			
			const fields = {}
			fields[`embedding_${model.name}`]=  [
				{
					"dimensions": model.size, // 1536,
					"similarity": "euclidean",
					"type": "knnVector"
				}
			]

			try{
				Test.createSearchIndex({
					name: model.name, // "text_embedding_3_small",
					definition: {
						"mappings": {
							"fields": fields
							}
						}
					}
				)
			}
			catch (err){
				debug("createSearchIndexes", "Failed to create index for model ",model, err)
			}
		
		}

	})
}

run();
```

**Comment by hlebegue** [comment]
With the latest Mongoose, I was able to catch error directly treating as a promise 
try{
				embedding.createSearchIndex({
					name: model.name, // "text_embedding_3_small",
					definition: {
						"mappings": {
							"fields": fields
							}
						}
				}).then( (success)=> {
					console.log("Succeeded!", success)
				}).catch((err) => {
					//console.log("EMBEDDINGS => ",err)
				})
			}
			catch (err){
				debug("createSearchIndexes", "Failed to create index for model ",model, err)
			}

But the issue is that I don't get the list of search indexes when I use 
await embedding.listIndexes()
await embedding.searchIndexes

The list returned is always empty.
How can I determine if a searchIndex already exists instead of attempting to create one and catch the error in .catch() ?

Thank you

**Comment by IslandRhythms** [comment]
Please modify my script to demonstrate your issue. Also when using code blocks, use three ` to have it appear as a code block like so:
"```
const name = 'Test'
```"

**Comment by vkarpov15** [comment]
The issue in the original post is that you need to `await` on `embedding.createSearchIndex`. Since `createSearchIndex` is async, you can't handle errors with `try/catch` unless you use `await`.

In terms of listing existing search indexes, we're currently missing an implementation of `listSearchIndexes()`. We will add that.

**Comment by hlebegue** [comment]
Fantastic ! Thank you for adding the Model.listSearchIndex() and respond to this issue. Best wishes
