### ISSUE TITLE
App in docker cannot connect to replica set in localhost

### ISSUE THREAD

**Issue by wielh** [Automattic/mongoose#14475]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.2

### Node.js version

20.11.1

### MongoDB server version

6.0.14

### Typescript version (if applicable)

5.4.2

### Description

> ` mongodb://<user>:<pwd>@<IP1>,<IP2>,<IP3>/<DB>?replicaSet=rs1&readPreference=secondaryPreferred`

Above connection string can be used in local app connect to local mongodb. However, this string cannot be used to connect when app is installed in docker and mongodb in local. The error message is below :

Error connecting to MongoDB with host: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
     at _handleConnectionErrors (/home/app/node_modules/mongoose/lib/connection.js:875:11)
     at NativeConnection.openUri (/home/app/node_modules/mongoose/lib/connection.js:826:11)
     at async URLInit (file:///home/app/common/config.js:130:9)
     at async file:///home/app/common/config.js:157:1 {
    reason: TopologyDescription {
     type: 'ReplicaSetNoPrimary',
     servers: Map(3) {
       '127.0.0.1:27017' => [ServerDescription],
       '127.0.0.1:27018' => [ServerDescription],
       '127.0.0.1:27019' => [ServerDescription]
     },
     stale: false,
     compatible: true,
     heartbeatFrequencyMS: 10000,
     localThresholdMS: 15,
     setName: 'rs1',
    maxElectionId: new ObjectId('7fffffff0000000000000013'),
     maxSetVersion: 13,
     commonWireVersion: 0,
     logicalSessionTimeoutMinutes: null
   },
   code: undefined
 }

### Steps to Reproduce

https://github.com/wielh/bookstore_microService

You can build only-one microService to test, current connection string in project is direct connect, not replica set.

### Expected Behavior

Both app in local and app in docker should be able to connect to replica set

**Comment by vkarpov15** [comment]
Are IP1, IP2, IP3 in your connection string `127.0.0.1` or something else? If something else, this looks like a [replica set hostnames issue](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). For example, if you connect to a replica set `mongodb://mongo1:27017,mongo2:27017/test` but mongo1 is running on a VM whose hostname is `127.0.0.1`, you'll get the same error message.

**Comment by vkarpov15** [comment]
Then it looks like a replica set hostnames issue. Make sure `hostname` on the server that's running your replica set returns `192.168.0.14` or something else that is resolvable from your app servers, **not** `127.0.0.1`.
