### ISSUE TITLE
findOneAndReplace or findOneAndUpdate with overwrite option does not honour any schema getter functions (7.3.2 and newer)

### ISSUE THREAD

**Issue by Ebulus7899** [Automattic/mongoose#14476]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.3.2 and newer

### Node.js version

18.16.1

### MongoDB server version

5.6.0

### Typescript version (if applicable)

4.9.5

### Description

we were currently using mongoose version 6.3 and made an attempt to update to using 7.6.8 however we encountered an issue in that we have a getter function that transforms a field stored as an ObjectId into a string when the document is retrieved. This worked until 7.3.2. We were previously using the overwrite option and in my attempt to update to 7.6.8 I changed our findOneAndUpdate call with the overwrite option set to a findOneAndReplace call.

I found the following patch is where our behaviour changed as the field that we treat as a string throughout our code base is being returned as an ObjectId. This was picked up by test code we had written. 

https://github.com/Automattic/mongoose/pull/13572/commits/0caeb6b2e8428cb56573b75212ddb7c186c2725d

The ObjectIdToString method is our own internal function that will convert the objectId field and convert it to a string.

```ts
export const OurSchema = new Schema<OurType>({
    ourField: {
        type: Schema.Types.ObjectId,
        get: ObjectIdToString,
    },
```

using findOneAndupdate with 7.3.2 this is the least amount of options needed to reproduce the issue

```ts
    const latest = await this.collection
        .findOneAndUpdate(matchQuery, update, {
            upsert: true,
            overwrite: true,
        })
        .lean(opts.lean)
        .exec();
```

using 7.6.8 this is the least amount of options needed for me to reproduce the issue.

```ts
    const latest = await this.collection
        .findOneAndReplace(matchQuery, update, {
             upsert: true,
        })
        .lean(opts.lean)
        .exec();
```

Note that there is a previous issue that was closed as it could not be reproduced which could be related

https://github.com/Automattic/mongoose/issues/14174

### Steps to Reproduce

write a schema that uses a getter function that will transform data. Use a findOneAndReplace or a findOneAndUpdate with the overwrite option set to true and you will find that the field has not been transformed.

### Expected Behavior

The correct transform set in the schema getter is honoured.

**Comment by IslandRhythms** [comment]
I believe this may be expected behavior as using lean removes getters from the doc https://mongoosejs.com/docs/tutorials/lean.html#using-lean

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: { 
    type: String,
    get: v => `TRANSFORM:${v}`
  }
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.create({
    name: 'Test Testerson'
  });

  console.log(doc.name);

  const res = await Test.findOneAndUpdate({}, { name: 'Test' }, { upsert: true, overwrite: true }).lean();
  console.log(res.name);
}

run();

```

**Comment by Ebulus7899** [comment]
I have some more information. We are using the "mongoose-lean-getters" package to get getters working when using lean. I am guessing the bug is then with the mongoose-lean-getters package in that this does not seem to work with findOneAndReplace?

**Comment by IslandRhythms** [comment]
Open a bug report there then if that is the case

**Comment by Ebulus7899** [comment]
yes thank you. I have confirmed that mongoose works fine if I remove the lean from the queries.
