### ISSUE TITLE
TypeError: Invalid schema configuration: `Z` is not a valid type at path - Zod Schema related

### ISSUE THREAD

**Issue by ReturnXDev** [Automattic/mongoose#14491]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.2.3

### Node.js version

v20.11.1

### MongoDB version

6.0.14

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

I use Sentry and I get this TypeError: 

_Invalid schema configuration: `Z` is not a valid type at path `dob`. See https://bit.ly/mongoose-schematypes for a list of valid schema types._

Dob = date of birth, a string comes from the front end, from a datepicker so I coerce using Zod.

Code:

```
dob: z.coerce
      .date()
      .min(daysAgo(365 * 105), "Your date of birth appears to be invalid.")
      .max(daysAgo(365 * 18), "You must be 18 years or older.")
      .nullable(),
```
```
export const daysAgo = (days: number) =>
  new Date(Date.now() - days * ONE_DAY_MS);
```
This ultimately forms part of a ``modifyProfileSchema ``
```
export const modifyProfileSchema = z
  .object({
```
etc

I then: 
``export type ModifyProfile = z.infer<typeof modifyProfileSchema>;``
and
``export type Profile = ModifyProfile & {
  user_id: string;
};``
Before finally:
```
const modelName = "Profiles";
export const Profiles = mongoose.model<Profile & Timestamps>(
  modelName,
  new mongoose.Schema(
    {
...
dob: {
        type: Date,
      },
...

```

So it is sort of a non-issue, the data saves to the database - when I run it on local and interact with the front-end, it saves, pulls from the database but I constantly get this error from Sentry.

From the 'Z' in the error message I assume something relating to Zod is being passed back but no errors get thrown when I monitor it and ultimately the process works.

Let me know if anyone has any tips or insights.

Thank you.

**Comment by vkarpov15** [comment]
I'm unable to repro, can you please modify the following script to demonstrate the issue you're seeing?

```javascript
const z = require('zod');

const Profiles = mongoose.model(
  'Profiles',
  new mongoose.Schema(
    {
      dob: {
        type: Date,
      }
    }
  )
);

void async function main() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');

  const modifyProfileSchema = z
  .object({
    dob: z.coerce
      .date()
      //.min(daysAgo(365 * 105), "Your date of birth appears to be invalid.")
      //.max(daysAgo(365 * 18), "You must be 18 years or older.")
      .nullable()
  });
  
  const { dob } = modifyProfileSchema.parse({ dob: new Date() });
  const { _id } = await Profiles.create({ dob });
  console.log(await Profiles.findById(_id).orFail().then(doc => doc.toObject()));
}();
```

Also, could you please provide the full stack trace of the error? The stack trace may provide something helpful. This error is indicative of trying to set the `dob` path in your schema to something Zod-related. For example, the following code would trigger the issue you're seeing: `new mongoose.Schema({ dob: z.coerce.date() })`

**Comment by Fauzdar1** [comment]
I'm facing the same issue, but only in Google Search Console's crawl bot's console. It is not crawling any page, saying there's a client-side error. And this is the error, it's not even there on the live website or in the dev environment. This is messing everything up.

`Uncaught (in promise) TypeError: Invalid schema configuration: `Z` is not a valid type at path `createdAt`.`

I only use `createdAt` in a single model and as I've checked, I don't see this error anywhere else. Plus the log doesn't help either.

**Comment by vkarpov15** [comment]
@Fauzdar1 could zod or something else be hijacking the global `Date` class?

**Comment by HiccupinGminor** [comment]
> I'm facing the same issue, but only in Google Search Console's crawl bot's console. It is not crawling any page, saying there's a client-side error. And this is the error, it's not even there on the live website or in the dev environment. This is messing everything up.
> 
> `Uncaught (in promise) TypeError: Invalid schema configuration: `Z`is not a valid type at path`createdAt`.`
> 
> I only use `createdAt` in a single model and as I've checked, I don't see this error anywhere else. Plus the log doesn't help either.

We are getting the exact same error, and similarly only when using Google Search Console (loading the same urls in Chrome works without errors). @Fauzdar1 did you manage to find a solution to this?

**Comment by Fauzdar1** [comment]
> > I'm facing the same issue, but only in Google Search Console's crawl bot's console. It is not crawling any page, saying there's a client-side error. And this is the error, it's not even there on the live website or in the dev environment. This is messing everything up.
> > `Uncaught (in promise) TypeError: Invalid schema configuration: `Z`is not a valid type at path`createdAt`.`
> > I only use `createdAt` in a single model and as I've checked, I don't see this error anywhere else. Plus the log doesn't help either.
> 
> We are getting the exact same error, and similarly only when using Google Search Console (loading the same urls in Chrome works without errors). [@Fauzdar1](https://github.com/Fauzdar1) did you manage to find a solution to this?

Yes, by removing Zod from models where date was a field, only a few models though. It was not a logical solution, but the error remained persistent with every fix, nothing like this existed somewhere else, client cancelled the remaining payments, hence removing it was the quickest fix, replacing it with manual data checks and express sanitiser, which was already added, didn't want to add one more package for few models. But you should prepare for this when you decide to rely on 3rd party packages, which happens often.

**Comment by vkarpov15** [comment]
@HiccupinGminor @Fauzdar1 can you please provide an example of what "removing Zod from models where date was a field" looks like code-wise?

**Comment by junaidashrafff** [comment]
@vkarpov15

In our setup, we didn't explicitly define any date fields in the schemas. Instead, we are using Mongoose's timestamps option and renaming the keys to match our preferred naming convention:

```
{
  timestamps: {
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
}
```
We have a total of 22 schemas, all utilizing this timestamp configuration.

However, we are encountering the following error in our case:


```
Uncaught (in promise) TypeError: Invalid schema configuration: `Z` is not a valid type at path `created_at`. See https://bit.ly/mongoose-schematypes for a list of valid schema types.
    at q.interpretAsType
```
Could you provide any insights into what might be causing this issue? We suspect it could be related to the interpretation of the created_at field type. Any guidance would be greatly appreciated!

**Comment by vkarpov15** [comment]
The most likely explanation is that Zod or someone else is replacing JavaScript's built-in `Date` object with a class named `Z`. However, I'm importing Zod and not getting that issue 😕 

```
$ node
Welcome to Node.js v20.18.1.
Type ".help" for more information.
> const zod = require('zod')
undefined
> Date
[Function: Date]
> global.Date
[Function: Date]
> global.Date.constructor.name
'Function'
> global.Date.name
'Date'
> 

```

Can you run `console.log(Date, global.Date)` in your project and paste the output here?

**Comment by junaidashrafff** [comment]
When running the following commands in Node.js:

`$ node
Welcome to Node.js v20.14.0.
Type ".help" for more information.
> c
Uncaught ReferenceError: c is not defined
> console.log(Date, global.Date)
[Function: Date] [Function: Date]
undefined
`

I noticed an issue with how we are defining a default timestamp in one of our schemas. Specifically, we were using the Date.now() function as the default value for the timestamp key:

`timestamp: {
  type: Number,
  default: Date.now(),
},
`

I have updated the schema to use the Date.now function reference instead:

`timestamp: {
  type: Number,
  default: Date.now,
},
`

Could this have been the root cause of the issue? Let me know your thoughts! ?

**Comment by vkarpov15** [comment]
I don't think so, because your error message references a `created_at` property, not a `timestamp` property.

Could you please paste the full stack trace so we can see which lines in Mongoose threw this error?

**Comment by ClapR** [comment]
Hi,
I'm facing the same issue on my app, which is not using Zod. I get this error message on the createdAt and updatedAt fields, even though they're created automatically by mongoose's timestamps.
So I don't think it's related to Zod, I assumed the Z came from the app compiling cause I couldn't find any info on a Z type.
The problem only occurs in Google Search Console when doing a live url test though.
If anyone as insights on how to prevent this I'm interrested !

**Comment by vkarpov15** [comment]
@ClapR please open a new issue and follow the issue template carefully. Mongoose doesn't have a `Z` type.
