### ISSUE TITLE
Using the ms package on expireAt option

### ISSUE THREAD

**Issue by CarlosDev123** [Automattic/mongoose#14498]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.3.0

### Node.js version

v20.10.0

### MongoDB version

7.0.7

### Operating system

None

### Issue

  ```js
  const time = new Date();
  time.setDate(time.getDate() + 30);
  const expiresAt = new Date(time);

  const punishmentData = {
    id: '',
    type: '',
    user: '',
    guild: '',
    moderator: '',
    reason: '',
    date: '',
    expires: '',
    automod: '',
    expireAt: expiresAt
  };
  ```
  
  On the code above, I use "new Date()" to set an expiration date to the data, my question is, instead of that, can I use something like the ms package? And if it's not possible, is there any alternative? Something like this:
  
  ```js
  const punishmentData = {
    id: '',
    type: '',
    user: '',
    guild: '',
    moderator: '',
    reason: '',
    date: '',
    expires: '',
    automod: '',
    expireAt: ms('30d')
  };
  ```

**Comment by vkarpov15** [comment]
You'd need to do `expireAt: new Date(Date.now() + ms('30d'))`. `ms('30d')` just returns the number of milliseconds in 30 days, you need to make sure you add that to the current time.

`expiresAt: ms('30d')` just tells MongoDB that your collection expires 30 days after January 1, 1970, which I'm sure isn't what you're looking for.
