### ISSUE TITLE
Mongoose not reconnecting after disconnection event

### ISSUE THREAD

**Issue by elizatlawy** [Automattic/mongoose#14517]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.10.1

### Node.js version

14.18.3

### MongoDB server version

5.0.9

### Description

My connection looks like this: 

```
const OPTIONS = {
  useNewUrlParser: true,
  useUnifiedTopology: true
};

// Make `sanitizeFilter` true by default
mongoose.set('sanitizeFilter', true);
mongoose.set('strictQuery', true);

if (process.env.LOG_MONGO_QUERIES) {
  mongoose.set('debug', (collectionName, method, query, doc) => {
    logger.debug(`${collectionName}.${method}`, JSON.stringify(query), doc);
  });
}

const initMongooseConnection = () => {
  try {
    connection.on('connected', () => {
      logger.info(`Successfully connected to MongoDB`);
    });
    connection.on('reconnected', () => {
      logger.info(`Successfully reconnected to MongoDB`);
    });
    connection.on('error', error => {
      logger.error(`MongoDB encountered and error: ${error}`);
    });
    connection.on('connecting', () => {
      logger.info('MongoDB connecting...');
    });
    connection.once('open', () => {
      logger.info('MongoDB connection opened');
    });
    connection.on('disconnecting', () => {
      logger.info('MongoDB disconnecting...');
    });
    connection.on('disconnected', () => {
      logger.error('MongoDB disconnected');
    });
    connection.on('close', () => {
      logger.info('MongoDB connection closed');
    });
    mongoose.connect(MONGO_DB_CONNECTION_URI, OPTIONS);
  } catch (err) {
    logger.error(`Error connecting to mongoDB: ${err}`);
  }
};

```

If I restart my Mongodb I get the `disconnected` event but there is no reconnect attempt, I am able to reconnect only after restarting the `Node.js `server. 

### Steps to Reproduce

1. Start the node.js server
2. See that the Mongo connection is open 
3. Restart MongoDB
4. disconnection e ent is fired 
5. No reconnect attempt 

### Expected Behavior

Mongoose should try to reconnect.

**Comment by IslandRhythms** [comment]
![image](https://github.com/Automattic/mongoose/assets/39510674/e1e4b89d-2771-41e6-a5bb-00497694d541)

**Comment by elizatlawy** [comment]
@IslandRhythms - Did you use the same version I mentioned? 

I tried and the issue is still reproduced with your simple test: 
![image](https://github.com/Automattic/mongoose/assets/17687074/bf1cf033-746d-44dd-aa45-57a51fcb5f77)

**Comment by IslandRhythms** [comment]
Does not occur for me on 6.10.1
![image](https://github.com/Automattic/mongoose/assets/39510674/29b76998-74bc-4ce0-a53b-e7233c50d529)

**Comment by vkarpov15** [comment]
I'm similarly unable to repro with a local MongoDB instance. @elizatlawy it looks like you might be connecting to MongoDB Atlas, if so how are you restarting MongoDB?

**Comment by elizatlawy** [comment]
The issue was with our port-forward and not with Mongo, my apologies. I'm closing this one.
