### ISSUE TITLE
There's a merge marker in the changelog

### ISSUE THREAD

**Issue by aredridel** [Automattic/mongoose#14512]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.0

### Node.js version

n/a

### MongoDB server version

n/a

### Description

In the changelog, 
```
<<<<<<< HEAD 8.2.0 / 2024-02-22
``` 

appears

### Steps to Reproduce

It's in the docs

### Expected Behavior

A clearly ordered changelog

**Comment by vkarpov15** [comment]
Fixed, thanks for pointing this out
