### ISSUE TITLE
Using the ms package on the expireAt option

### ISSUE THREAD

**Issue by CarlosDev123** [Automattic/mongoose#14523]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.3.1

### Node.js version

v20.10.0

### MongoDB version

7.0.8

### Operating system

None

### Issue

```js
  const time = new Date();
  time.setDate(time.getDate() + 30);
  const expiresAt = new Date(time);

  const punishmentData = {
    id: '',
    type: '',
    user: '',
    guild: '',
    moderator: '',
    reason: '',
    date: '',
    expires: '',
    automod: '',
    expireAt: expiresAt
  };
  ```
  
 On the code above, I use "new Date()" to set an expiration date to the data, my question is, instead of that, can I use something like the ms package? And if it's not possible, is there any alternative? Something like this:
  
  ```js
  const punishmentData = {
    id: '',
    type: '',
    user: '',
    guild: '',
    moderator: '',
    reason: '',
    date: '',
    expires: '',
    automod: '',
    expireAt: ms('30d')
  };
  ```

**Comment by FaizBShah** [comment]
I don't think this issue is related to mongoose specifically, as its your wish however you want to store the data in the db, and what you want to infer from that. However, it seems what you want to know is if there is any way to convert the value returned by `ms()` to Date. In that case, I'll recommend you to create an issue in the `ms` repo

**Comment by vkarpov15** [comment]
`ms('30d')` just returns the number of milliseconds in 30 days. So `Date.now() + ms('30d')` gives you the [milliseconds since epoch](https://masteringjs.io/tutorials/fundamentals/timestamps) of 30 days from now. You can just convert that to a date using the following:

```
const expiresAt = new Date(Date.now() + ms('30d'));
```
