### ISSUE TITLE
schema.recompileSchema exception when subDocument discriminator is defined before the model is compiled

### ISSUE THREAD

**Issue by ZachLeviPixel** [Automattic/mongoose#14527]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.3.1

### Node.js version

18.16

### MongoDB server version

6.3.0

### Description

The following example throws "discriminator with name 'X' already exists" when the model of the top level schema is compiled after the discriminator definitions have been created on the subdocument schema.

If you create the model first, recompile seems to work as expected.
Important to note that on either case, the schema behaves as expected without recompiling.

### Steps to Reproduce

```javascript
const mongoose = require("mongoose");

const shopItemSchema = new mongoose.Schema({}, { discriminatorKey: "type" });
const shopSchema = new mongoose.Schema({
    items: { type: [shopItemSchema], required: true },
});

const shopItemSubType = new mongoose.Schema({});
// const shopModel = mongoose.model("shop", shopSchema); // If the shop model is created before the schema is discriminated, recompile will work
shopItemSchema.discriminator(2, shopItemSubType);
const shopModel = mongoose.model("shop", shopSchema);

shopModel.recompileSchema(); // Error: Discriminator with name "2" already exists
```

### Expected Behavior

The schema should recompile without error.

**Comment by vkarpov15** [comment]
Fixed by 23869fb10cd3e81c1bb2b51878a206ea30bb935e, I got my issue numbers mixed up
