### ISSUE TITLE
Dumps *gigantic* object into console on error

### ISSUE THREAD

**Issue by ChristopherJTrent** [Automattic/mongoose#14529]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.3.1

### Node.js version

21.6.2

### MongoDB server version

Irrelevant

### Description

Every time I have a problem with mongoose, it decides to dump a gigantic (larger than my terminal scrollback, which is set to 1 billion lines) object into the console.
This makes it completely impossible to diagnose anything.
I have mongoose.set('debug', false),
I don't have any other loggers enabled.

### Steps to Reproduce

Happens in random places in this repo: https://github.com/acheung-94/pet-portal/tree/buildNewPetForm
notably when you send a put request to /api/pets/:id

### Expected Behavior

I expect there to be some way to get mongoose to not dump the entire mongoose object to console

**Comment by vkarpov15** [comment]
Do you have a sample of what the output looks like?

**Comment by ChristopherJTrent** [comment]
[message.txt](https://github.com/Automattic/mongoose/files/15139200/message.txt)
Here's the whole thing.

**Comment by vkarpov15** [comment]
@ChristopherJTrent I deleted your comment because the message you pasted includes your database connection string with username and password. I'd recommend you update your username and password just in case.

**Comment by vkarpov15** [comment]
Also worth noting, your output includes 12 server restarts, most of which have the same error. So the error output isn't quite that large as that. But we'll look into it and see what we can do on our end, or what changes we can recommend to your morgan config to make the logs more readable.

**Comment by ChristopherJTrent** [comment]
> @ChristopherJTrent I deleted your comment because the message you pasted includes your database connection string with username and password. I'd recommend you update your username and password just in case.

Thank you, I didn't realize. My DBA is issuing me new creds. (but not without a stern talking to <_< >_>)

**Comment by vkarpov15** [comment]
I wouldn't say it's entirely your fault, it is surprising that an error originating from casting an update would contain your database connection string. This has to do with how Node.js serializes errors to the console, doesn't affect how errors end up in JSON or anywhere else.
