### ISSUE TITLE
Strict type check based on document interface

### ISSUE THREAD

**Issue by cqiaoben2023** [Automattic/mongoose#14548]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.12.7

### Node.js version

20.12.2

### MongoDB version

7.0.6

### Operating system

None

### Issue

Hello! I am wondering if it is possible to do strict type check based on document interface for the following example:

```
interface IVehicle {
   vehicleName: string 
}

interface ICar {
   vehicleName: string,
   carName: string 
}

const carModel = model<ICar>("Vehicle",  VehicleSchema)
const vehicleModel = model<IVehicle>("Vehicle", VehicleSchema)

vehicleModel.create({vehicleName: "foo"});
vehicleModel.find({vehicleName: "foo"}); // returns vehicle document, great!

// this should return an error because carName is missing!
carModel.find({vehicleName: "foo"}); // returns vehicle document, not great
```

====================

Note: I am not using discriminator for vehicle & car and setting the types up this way mainly because multi-level discriminator is not supported. "https://github.com/Automattic/mongoose/issues/2851" In the complete example, I would have `SUV` & `Convertible` "flattened" under `Car`:

```
SUV = VehicleModel.discriminator("SUV", new Schema({...CarSchema, price: number}))
Convertible = VehicleModel.discriminator("Convertible", new Schema({...CarSchema, roof: enum}))
```

and I would like a way to get `CarModel` with type-safety.

```
SUVModel.create({vehicleName: "suv", carName: "suv", price: 100});
carModel.find({vehicleName: "suv"}); // returns suv document, great!

vehicleModel.create({vehicleName: "foo"});
// this should return an error because carName is missing!
carModel.find({vehicleName: "foo"}); // returns vehicle document, not great
```

**Comment by FaizBShah** [comment]
Can you format your code a little bit more readable way? Could not understand where you are using the interfaces, and from where are you getting the schemas?

**Comment by vkarpov15** [comment]
We allow `vehicleModel.create({vehicleName: "foo"});` because `vehicleName` could be set by defaults, middleware, plugins, etc. But that being said, if you want stricter type checking, the theory is you should be able to do `vehicleModel.create<ICar>({vehicleName: "foo"})` to get the behavior you want. We just need to merge and release #14571 first.
