### ISSUE TITLE
How to retain mongoose connection even on refresh of the app

### ISSUE THREAD

**Issue by chwasifjameel** [Automattic/mongoose#14549]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

5.12.4

### Node.js version

20.0.0

### MongoDB version

6.0.15

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.4.1

### Issue

**Scnacio:**
I have a nodejs application, that can connect to multiple databases at the same time. With every request coming to us, we evaluate and select a database to query. We have allowed all organizations to have their database configured with us.

**How it is implemented:**
I run over all databases uri's and link the models with them. following are the 2 main functions for all these operations

```
async function connectToDatabase(connectionName) {
  if (!connections[connectionName]) {
    if (!databaseConfigs[connectionName]) return null;

    const connection = await mongoose.createConnection(databaseConfigs[connectionName], {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    connection.on('error', (error) => {
      console.error(`Error connecting to database ${databaseUri}`, error);
    });
    connection.on('connected', () => {
      console.log(`Connected to database ${connectionName}`);
    });
    connections[connectionName] = connection;
  }
  return connections[connectionName];
}
```

```
async function setupConnectionsAndModels(databaseConfigs, models) {
  for (const [databaseName, connectionString] of Object.entries(databaseConfigs)) {
    // Check if the connection already exists
    if (!connectionModelMap.has(databaseName)) {
      // Reuse the connectToDatabase function
      const connection = await connectToDatabase(databaseName, connectionString);

      // Store the connection in the map
      if (connection) connectionModelMap.set(databaseName, connection);
    }

    // Get the connection from the map
    const connection = connectionModelMap.get(databaseName);

    // Setup models for the connection
    for (const [modelName, schema] of Object.entries(models)) {
      // Check if the model for the connection already exists
      if (!connectionModelMap.get(databaseName)[modelName]) {
        // Create a new model
        const model = connection.model(modelName, schema);

        // Store the model in the map
        connectionModelMap.get(databaseName)[modelName] = model;
      }
    }
  }
}
```

**Problem**
In the development environment, I'm using [nodemon](https://www.npmjs.com/package/nodemon). Now the problem is every time I save a file it loses all the database connections. I'm looking for something that can cache my database connections so developers don't have to wait 50 seconds every time they save something to a file.

**What I have tried**
I have tried to use global variables to save the connections and return the cached versions if they exist but that is not happening. 

I believe there would be a way to fix this problem. Looking to have the opinion of experts on this.

**Comment by vkarpov15** [comment]
Not possible. Nodemon restarts the entire process, when your Node process shuts down all the sockets shut down too. No  way around that.
