### ISSUE TITLE
Return the deleted document after a deleteOne operation

### ISSUE THREAD

**Issue by Davian99** [Automattic/mongoose#14578]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.3.4

### Node.js version

18.2.0

### MongoDB version

6.5.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux 6.8.7-arch1-

### Issue

We are currently migration our codebase from version 6.5.4 to version 8.3.4.

As recomended, we first migrated to version 7 and dealed with the breaking changes, and then moved to migrate from version 7 to the latest version.

This is where we hit a wall, as our system depends on a pair of middlewares that detects every change done to the documents:
- A post `save` that detects creation and updates of documents that works fine
- A post `deleteOne` (migrated from a `remove` in mongoose 7) that detects deletions of documents.

The new return being a query instead of the deleted document  messed up everything in in our workflow.  Is there any easy alternative or change we can do to restore the behavior of the `deleteOne` method?

Thanks for looking into it.

**Comment by vkarpov15** [comment]
Yeah the issue is that `deleteOne()` is both a query method and a document method. And query `deleteOne()` doesn't have access to the deleted document, you need to use `findOneAndDelete()` for that.
