### ISSUE TITLE
Adding minlength and maxlength to Schema with String as type 

### ISSUE THREAD

**Issue by justin-john** [Automattic/mongoose#1457]
Add a new feature for minimum length and maximum length to Schema with **String** as type. This will  validate minimum and maximum length to corresponding string in schema.

For example,

```
var s = new Schema({ name: { type: String, minlength: 5, maxlength: 15 }});
```

OR 

```
var s = new Schema({ name: { type: String, min: 5, max: 15 }});
```

**Comment by vedi** [comment]
looks like it's on its way to the next release: https://github.com/LearnBoost/mongoose/commit/b96d72440769a4fc038e3934b268b1ec648dd16d

**Comment by vedi** [comment]
@sandesh27, thank you for workaround

**Comment by vkarpov15** [comment]
Its in 4.0.0-rc2 :)

**Comment by jeremyml** [comment]
Here is the documentation for the new `maxlength` validator    http://mongoosejs.com/docs/api.html#schema_string_SchemaString-maxlength

**Comment by tejasmanohar** [comment]
Just stumbled upon this. I personally think the ORM/ODM should include as few validations and whatnot built-in, as these are really application concerns, and there are plenty of libraries for this. Keep it lean :)

**Comment by gayan27** [comment]
hoe to present  date type in schema

**Comment by samshubbu** [comment]
> **jkdkjcs******ldsclscs**sdcscslc**

**Comment by vkarpov15** [comment]
See https://mongoosejs.com/docs/schematypes.html#string-validators
