### ISSUE TITLE
empty objects are being saved as null

### ISSUE THREAD

**Issue by matanDevalore** [Automattic/mongoose#14596]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.2.4

### Node.js version

20.12.0

### MongoDB server version

6.0.2 Community

### Typescript version (if applicable)

5.4.3

### Description

I have a schema which accepts an Object property.
![image](https://github.com/Automattic/mongoose/assets/38420505/a478b020-3789-4e36-a5d5-2ae836fcf113)

On mongoose version 8+, when updating the document in DB, with an empty object ( `{}` ), the value that is actually being saved is `null`.

![image](https://github.com/Automattic/mongoose/assets/38420505/59a846be-9c7e-4a40-af54-4d82ab4b0813)

when querying the DB and fetching the relevant document, `variables: null` is being returned, which makes other validations in the system to throw the following error:
![image](https://github.com/Automattic/mongoose/assets/38420505/24483777-1280-4349-8085-80646529e6b2)

On older versions (tested on 7.6.3), it doesn't happen and it behave as expected (the object is being saved as an empty object):

![image](https://github.com/Automattic/mongoose/assets/38420505/25bb5e0c-510a-4a1c-957d-b76cf2ddec3d)

 I can ofc changing the validators in the system, but it seems like the wrong solution. empty object doesn't equal to null.

### Steps to Reproduce

1. create a mongoose model with an object field. for example:

```
const TestSchema = new Schema({
  data: {
    type: Object,
  },
});

export const TestModel = mongoose.model('Test', TestSchema);
```

2. create a new document in DB (with empty object: `data: {}`). (the object will be saved without `data` property - which is fine)
3. load this document using `findOne`.
4. reset the `data` field again to empty object: `document.data = {}`
5. save this document using `document.save()`

### Expected Behavior

after update, the `data` field should be an empty object `{}`. as can see using mongoDB Compass in old mongoose versions:

![image](https://github.com/Automattic/mongoose/assets/38420505/e6361862-e250-452b-a3e6-f815dde26a44)

another good solution for me, is if you will add a new parameter that will allow me to choose the way it should behave. (`allowNullable: false`)

**Comment by vkarpov15** [comment]
This was fixed in v8.3.1 with #14504, looks like the same issue as #14445. Please upgrade to v8.3.1 for the fix.
