### ISSUE TITLE
Discriminators: Return derived model when issuing Find on base model

### ISSUE THREAD

**Issue by TomMettam** [Automattic/mongoose#14593]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.3.4

### Node.js version

v20.11.1

### MongoDB version

5.0.16-r1::gentoo

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Gentoo

### Issue

I have just finished working on updating an old codebase.

As part of this work, I migrated from the old and largely defunct `mongoose-extend-schema` to Mongoose Discriminators.

However, there's a key change in functionality which is causing a significant loss in performance.

```
const baseModelSchema = new mongoose.Schema({
    ...
});

const derivedModelSchema = new mongoose.Schema({
    ...
});

const baseModel = connection.model('BaseModel', baseModelSchema);
const derivedModel = baseModel.discriminator('DerivedModel', derivedModelSchema);
```

With `mongoose-extend-schema`, if I did:

const result = await baseModel.findOne({ ... });

and the discriminator matched `derivedModel`, it would give me an instance of `derivedModel`.

With discriminators, it always gives me an instance of `baseModel` which means that I have to manually convert it, which costs a bunch of additional CPU cycles...

```
baseModelSchema.post('find', function (docs, next)
    {
        if (docs?.length)
        {
            for (let index = 0; index < docs.length; index++)
            {
                const doc = docs[index];
                const Model = connection.model(doc.__type);
                docs[index] = new Model(doc.toObject());
            }
        }
        next();
    });
```

This is suboptimal and slow, and I'd really like it if mongoose could give me the correct instance for the model. Is there an option to enable this?

**Comment by vkarpov15** [comment]
I'm unable to repro, AFAIK Mongoose does give you the correct discriminator model with `findOne()`. For example, consider the following script. Can you please modify the following repro script to demonstrate the issue you're seeing?

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(error => {
  console.error(error);
  process.exit(-1);
});

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');

  const baseModelSchema = new mongoose.Schema({ baseModelProp: String });

  const derivedModelSchema = new mongoose.Schema({ derivedModelProp: String });

  const baseModel = mongoose.model('BaseModel', baseModelSchema);
  const derivedModel = baseModel.discriminator('DerivedModel', derivedModelSchema);

  await baseModel.deleteMany({});
  const { _id } = await derivedModel.create({ baseModelProp: 'base model test', derivedModelProp: 'derived model test' });

  const doc = await baseModel.findById(_id).orFail();
  console.log(doc.derivedModelProp); // Prints "derived model test"
  console.log(doc instanceof derivedModel); // Prints "true"
}
```
