### ISSUE TITLE
Using mongoose and got error when adding new data: Product validation failed

### ISSUE THREAD

**Issue by alikashanidev** [Automattic/mongoose#14592]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^8.3.4

### Node.js version

21.6.2

### MongoDB server version

...

### Typescript version (if applicable)

5

### Description

Hello.
Hello. When I try to add product data to the MongoDB database, I receive this error:
 "specs.storage": {
            "stringValue": "\"{\n  capacities: [\n    { value: '۲۵۶', unit: 'گیگابایت' },\n    { value: '۵۱۲', unit: 'گیگابایت' },\n    { value: '۱', unit: 'ترابایت' }\n  ],\n  type: 'SSD',\n  upgradable: 'ندارد'\n}\"",
            "valueType": "Object",
            "kind": "string",
            "value": {
                "capacities": [
                    {
                        "value": "۲۵۶",
                        "unit": "گیگابایت"
                    },
                    {
                        "value": "۵۱۲",
                        "unit": "گیگابایت"
                    },
                    {
                        "value": "۱",
                        "unit": "ترابایت"
                    }
                ],
                "type": "SSD",
                "upgradable": "ندارد"
            },
            "path": "specs.storage",
            "reason": null,
            "name": "CastError",
            "message": "Cast to string failed for value \"{\n  capacities: [\n    { value: '۲۵۶', unit: 'گیگابایت' },\n    { value: '۵۱۲', unit: 'گیگابایت' },\n    { value: '۱', unit: 'ترابایت' }\n  ],\n  type: 'SSD',\n  upgradable: 'ندارد'\n}\" (type Object) at path \"specs.storage\""
        }

### Steps to Reproduce

```
export type IProduct = {
    specs: {
        storage?: {
            capacities: {
                value: string;
                unit: string;
            }[];
            type?: string;
            upgradable?: string;
        };
    };
};
const productSchema = new Schema(
    {
        specs: {
            storage: {
                capacities: [
                    {
                        value: String,
                        unit: String,
                    },
                ],
                type: String,
                upgradable: String,
            },
        },
    },
    { timestamps: true }
);
const newData: IProduct = {
    specs: {
        storage: {
            capacities: [
                {
                    value: "۲۵۶",
                    unit: "گیگابایت",
                },
                {
                    value: "۵۱۲",
                    unit: "گیگابایت",
                },
                {
                    value: "۱",
                    unit: "ترابایت",
                },
            ],
            type: "SSD",
            upgradable: "ندارد",
        },
    },
};

```

**Comment by vkarpov15** [comment]
Make the following change to your productSchema:

```javascript
const productSchema = new Schema(
    {
        specs: {
            storage: {
                capacities: [
                    {
                        value: String,
                        unit: String,
                    },
                ],
                type: { type: String }, // <-- Replace `String` with `{ type: String }` here
                upgradable: String,
            },
        },
    },
    { timestamps: true }
);
```

As written your schema tells Mongoose that `specs.storage` is a string rather than a document array because of `type: String`. `type: { type: String }` is a workaround.
