### ISSUE TITLE
Populate to New Field Name

### ISSUE THREAD

**Issue by maxcan** [Automattic/mongoose#1459]
As far as I can tell, if I have a model like:

```
UserSchema =
    name: String

DocSchema = 
    name: String
    ownerId: ObjectId, ref 'User'
```

and I want to populate the owner field, the only way to do this with the populate() function will cause `doc.ownerId` to go from being an `ObjectId` to a User object itself.  However, I'd rather be able to populate a new field `owner` so the type of `ownerId` doesn't change.  This seems safer and more robust but it doesn't seem possible.

**Comment by amragaey** [comment]
Guys! I think we need to consider this option when populating, to get the populated result into another field name. I usually name the references fields with _ at the beginning, so I do need to keep that consistent, and when populating I can get the result into a new field. An example for me would go like this:
__before population from 'Restaurant' model__
_restaurant: ObjectId()
__after population__
restaurant: {}

**Comment by lineus** [comment]
@amragaey Can you just use a virtual for this?

```js
  schema.virtual('restaurant', {
    localField: '_restaurant',
    foreignField: '_id',
    ref: 'otherModelName'
    justOne: true
  });
```
