### ISSUE TITLE
Autoindex is recreating existing indexes

### ISSUE THREAD

**Issue by GustavoOS** [Automattic/mongoose#14597]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.3.4

### Node.js version

20.13.1

### MongoDB server version

3.6

### Description

When connecting with autoIndex option set true (which is the default), mongoose will create the indexes every time the application runs.

### Steps to Reproduce

1. Create a project with mongoose
2. Create a model with an index
3. Connect with autoIndex and 'debug' set
4. Start the application
5. The index creation will be logged (correct)
6. Stop the application
7. Start the application again
8. The index creation will be logged again (unexpected)

### Expected Behavior

Autoindex only create indexes that weren't previously created

**Comment by vkarpov15** [comment]
This is expected and [documented](https://mongoosejs.com/docs/api/model.html#Model.ensureIndexes()) behavior. If this behavior is incorrect for your use case, you can disable `autoIndex` option and use [`Model.syncIndexes()` instead](https://mongoosejs.com/docs/api/model.html#Model.syncIndexes()).

`syncIndexes()` does exactly what you suggest: check MongoDB for which indexes already exist, drop any indexes that are in MongoDB but not in schema, create any indexes that are in schema but not in MongoDB, do nothing with indexes that exist in both schema and MongoDB.

**Comment by GustavoOS** [comment]
> This is expected and [documented](https://mongoosejs.com/docs/api/model.html#Model.ensureIndexes()) behavior. If this behavior is incorrect for your use case, you can disable `autoIndex` option and use [`Model.syncIndexes()` instead](https://mongoosejs.com/docs/api/model.html#Model.syncIndexes()).
> 
> `syncIndexes()` does exactly what you suggest: check MongoDB for which indexes already exist, drop any indexes that are in MongoDB but not in schema, create any indexes that are in schema but not in MongoDB, do nothing with indexes that exist in both schema and MongoDB.

syncIndexes does something different, as this syncs Indexes only by each model, not for all models as autoIndex does

**Comment by vkarpov15** [comment]
There's also a `Connection.prototype.syncIndexes()` which calls `syncIndexes()` on every model in the collection: https://mongoosejs.com/docs/api/connection.html#Connection.prototype.syncIndexes()
