### ISSUE TITLE
Breaking types of `toObject` on SubDocument or ArraySubdocument

### ISSUE THREAD

**Issue by piyushk96** [Automattic/mongoose#14601]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.3.4

### Node.js version

20

### MongoDB server version

6.6

### Typescript version (if applicable)

5.4.5

### Description

Since Mongoose v7, the type of the results obtained by calling `toObject` on SubDocument or ArraySubdocument is `any`. Prior to v7 `toObject` return type was working fine.

### Steps to Reproduce

** Code for version >=v7 **
```
import mongoose, { Types, model } from 'mongoose';
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost:27017/testdb');

interface ISub {
  field1: string;
}
interface IMain {
  f1: string;
  f2: ISub & Types.Subdocument;
  f3: (ISub & Types.ArraySubdocument)[];
}

const subSchema = new Schema({ field1: String }, { _id: false });

const mainSchema = new Schema({
  f1: String,
  f2: { type: subSchema },
  f3: { type: [subSchema] }
})
const MainModel = model<IMain>("Main", mainSchema);

const item = new MainModel({
  f1: "test",
  f2: { field1: "test" },
  f3: [{ field1: "test" }]
})

const obj = item.toObject();

const obj2 = item.f2.toObject()
```

<img width="736" alt="image" src="https://github.com/Automattic/mongoose/assets/41179062/06b1dd1c-b1b2-4eee-b4ab-100b757a49d4">

<img width="669" alt="image" src="https://github.com/Automattic/mongoose/assets/41179062/bb4e7929-b651-4538-b5e6-d2eebc097f27">

** Code for version < v7 **
```
import mongoose, { Types, model, Document } from 'mongoose';
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost:27017/testdb');

interface ISub {
  field1: string;
}
interface IMain {
  f1: string;
  f2: ISub & Types.Subdocument;
  f3: (ISub & Types.ArraySubdocument)[];
}

type IMainDoc = IMain & Document;

const subSchema = new Schema({ field1: String }, { _id: false });

const mainSchema = new Schema({
  f1: String,
  f2: { type: subSchema },
  f3: { type: [subSchema] }
})
const MainModel = model<IMainDoc>("Main", mainSchema);

const item = new MainModel({
  f1: "test",
  f2: { field1: "test" },
  f3: [{ field1: "test" }]
})

const obj = item.toObject();

const obj2 = item.f2.toObject()
const obj3 = item.f3[0].toObject()
```

<img width="733" alt="image" src="https://github.com/Automattic/mongoose/assets/41179062/567891dc-6a24-4bf1-b209-8f5b21a67e3e">

<img width="708" alt="image" src="https://github.com/Automattic/mongoose/assets/41179062/44737969-441b-4a68-b460-7aa5c4e568a3">

### Expected Behavior

Both obj2 and obj3 should have proper types

**Comment by vkarpov15** [comment]
In Mongoose 7, we recommend using `HydratedSingleSubdocument` and `HydratedArraySubdocument` rather than `ISub & Types.Subdocument`. With #14612, the following will no longer return `any`

```
  interface IMain {
    f1: string;
    f2: HydratedSingleSubdocument<ISub>;
    f3: HydratedArraySubdocument<ISub>[];
  }
```
