### ISSUE TITLE
new Types.ObjectId is deprecated how do i convert a string _id to an ObjectID now?

### ISSUE THREAD

**Issue by vorticalbox** [Automattic/mongoose#14608]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.4.0

### Node.js version

20

### MongoDB version

7.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

fedora 40

### Issue

So the apis i have we take the _id from the URL, this is a string and to convert this to an ObjectID I do
```
new Types.ObjectId(id)
```

however this method is now deprecated `@deprecated — Instead, use static createFromTime() to set a numeric value for the new ObjectId.`

however I am not using a  numeric value i have a string of an ObjectID so how should i handle this now?

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script doesn't print any warnings

```
'use strict';

const mongoose = require('mongoose');

console.log(new mongoose.Types.ObjectId('0'.repeat(24)));
console.log(new mongoose.Types.ObjectId(42));
```

Can you please modify the above script to demonstrate the issue you're seeing? Perhaps you're just running into this issue: https://github.com/dotansimha/graphql-code-generator/issues/6830 ?

**Comment by vorticalbox** [comment]
@vkarpov15 if you use typescript you get the following

![image](https://github.com/Automattic/mongoose/assets/10886065/7450b9b5-3e70-4db3-91ad-fab3507e187c)

**Comment by vkarpov15** [comment]
@vorticalbox if you're seeing this deprecation warning, that means your `id` is a number, **not** a string. `new mongoose.Types.ObjectId(strValue)` isn't deprecated, but `new mongoose.Types.ObjectId(numberValue)` apparently is.

Do you see the same function signature `@param inputId - A number` in your IDE?

**Comment by vorticalbox** [comment]
> @vorticalbox if you're seeing this deprecation warning, that means your `id` is a number, **not** a string. `new mongoose.Types.ObjectId(strValue)` isn't deprecated, but `new mongoose.Types.ObjectId(numberValue)` apparently is.
> 
> Do you see the same function signature `@param inputId - A number` in your IDE?

I think it is triggered when the type is unknown.

Thank you for the clarification about the number.

I think this is solved now.

**Comment by techreagan** [comment]
`new mongoose.Types.ObjectId(`${req.user.id}`)` just do this, And you will be fine.

**Comment by VivekJha4105** [comment]
I was also facing this issue. 
The string interpolation worked.
I guess any other method would work as long as make sure the _id passed to it is in string format.
Thank You

**Comment by vkarpov15** [comment]
@pranjul-jangra this method is not deprecated. You just need to make sure the value you're passing in to `new mongoose.Types.ObjectId()` is a string.
