### ISSUE TITLE
command events are not fired after setting monitorCommands: true

### ISSUE THREAD

**Issue by bobeZzz** [Automattic/mongoose#14611]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.0

### Node.js version

18.19.1

### MongoDB server version

6.0.1

### Description

MongoDB dirver supports [Command Monitoring](https://www.mongodb.com/docs/drivers/node/current/fundamentals/monitoring/command-monitoring/)

Problem: unable to subscribe for command monitoring events using mongoose

### Steps to Reproduce

using `mongoose@8.4.0`
After following setup steps from the doc above, events are not emitted / reaching event listeners
```js
const mongoose = require('mongoose');

const initMongoose = async () => {
  await mongoose.connect(
    'mongodb://localhost:27017/mydatabase',
    {
      monitorCommands: true,
    }
  );

  const db = mongoose.connection;
  db.on('commandStarted', event => console.log(event));
  db.on('commandFailed', event => console.log(event));
  db.on('commandSucceeded', event => console.log(event));
}

const User = mongoose.model('User', new mongoose.Schema({
  name: String,
  email: String,
  age: Number,
}));

const main = async () => {
  await initMongoose();
  await User.findOne()
  console.log('done!')
}

main()
```

### Expected Behavior

but when using `mongodb@6.6.2` directly which is installed together with `mongoose@8.4.0`
Events are fired and able to reach event listeners
```js
const { MongoClient } = require("mongodb");

const client = new MongoClient(
  'mongodb://localhost:27017/mydatabase',
  { monitorCommands: true }
);

client.on('commandStarted', event => console.log(event));
client.on('commandFailed', event => console.log(event));
client.on('commandSucceeded', event => console.log(event));

async function main() {
  try {
    await client
      .db("mydatabase")
      .collection('users1')
      .findOne()
  } finally {
    await client.close();
  }
}
main()
```

**Comment by vkarpov15** [comment]
Use the following instead:

```javascript

  const client = mongoose.connection.client;
  client.on('commandStarted', event => console.log(event));
  client.on('commandFailed', event => console.log(event));
  client.on('commandSucceeded', event => console.log(event));

```

[`Connection.prototype.client` contains the Mongoose connection's `MongoClient` instance](https://mongoosejs.com/docs/api/connection.html#Connection.prototype.client), so that is what you should use to integrate with the MongoDB Node driver directly.

That being said, we will keep this issue open for 8.5 because it would by nice for Mongoose to bubble up the `monitorCommands` events onto the Mongoose connection.

**Comment by bobeZzz** [comment]
thanks, works like a charm!
just an FYI `mongoose.connection.client` doesn't seem to be declared on TS side of things, but there is a method availabel to retrieve client instance `mongoose.connection.getClient()` which covers it.

![image](https://github.com/Automattic/mongoose/assets/13787154/3e2229e6-12b6-4bed-9bf0-cf1b216d73f3)

**Comment by vkarpov15** [comment]
Yeah `connection.getClient()` is equivalent to `connection.client`
