### ISSUE TITLE
Not Work  `new mongoose.Types.ObjectId`

### ISSUE THREAD

**Issue by hossein-hypadrive** [Automattic/mongoose#14616]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.4.0

### Node.js version

20.13.1

### MongoDB version

5.x

### Operating system

macOS

### Issue

After updating Mongoose from version 6.9.0 to version 8.4.0, the following command no longer works and I cannot find a replacement for it.

`new mongoose.Types.ObjectId`

**Comment by parthpatel-simbiotik** [comment]
Also populate does not consider the toJSON and id:true fields in 8.4.0

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script executes without error against mongoose 8.4.0. Please modify the following script to demonstrate your issue.

```
'use strict';

const mongoose = require('mongoose');

console.log(new mongoose.Types.ObjectId('0'.repeat(24)));
console.log(new mongoose.Types.ObjectId(42));
```

**Comment by Bamorem** [comment]
it doesn't work for me too it seems like 
- new mongoose.Types.ObjectId(jobId)
get this error => Expected 0 arguments, but got 1


how can we create an ObjectId from a string (existing id)

**Comment by vkarpov15** [comment]
@Bamorem please open a new issue and follow the issue template
