### ISSUE TITLE
Populate does not consider toJSON and id:true

### ISSUE THREAD

**Issue by parthpatel-simbiotik** [Automattic/mongoose#14620]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.0

### Node.js version

21.7.1

### MongoDB server version

7.0.8

### Description

I have 2 schema, and 1 was populating another one. and both has id:true and toJSON implemented to delete ret._id;

but not working after 8.4.0 when I switched back to 8.0.3 it is working fine. it created lot of issues since frontend was expecting id but was returning _id.

### Steps to Reproduce

Try creating 2 schema and populate one from another, implement id:true and toJSON to remove any fields.

It will work on version 8.0.3 but will not work on 8.4.0

`@Schema({
  id: true,
  timestamps: true,
  toJSON: {
    virtuals: true,
    versionKey: false,
    transform(doc, ret) {
      delete ret._id;
    },
  }
})`

`PassingInfoSchema.virtual('entry', {
  ref: 'ParkingEntry',
  localField: 'entryId',
  foreignField: '_id',
  justOne: true,
});`

### Expected Behavior

behavior of populated fields should be same as earlier.

Please look into it.

**Comment by IslandRhythms** [comment]
Please modify the script below to demonstrate your issue:

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
}, { id: true, timestamps: true, toJSON: { virtuals: true, versionKey: false, transform(doc,ret) { delete ret._id ;}}})

const otherSchema = new mongoose.Schema({
  name: String,
  testId: mongoose.Schema.Types.ObjectId
});

otherSchema.virtual('entry', { ref: 'Test', localField: 'testId', foreignField: '_id', justOne: true });

const Test = mongoose.model('Test', testSchema);

const Other = mongoose.model('Other', otherSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Test.create({
    name: 'Test Testerson'
  });

  const other = await Other.create({
    name: 'Other Otherson',
    testId: doc._id
  });
  const res = await Other.findOne().populate('entry');
  console.log('what is res', res, res.entry);
}

run();
```
