### ISSUE TITLE
Is there a way to preserve documents modifications when a doc is modified and then populated?

### ISSUE THREAD

**Issue by ericneubauerbumphealth** [Automattic/mongoose#14627]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.12.8, 7.6.12

### Node.js version

14.21.3, 16.20.2

### MongoDB version

5.0.26

### Operating system

None

### Issue

Hi all,

Wondering if there's a way to preserve changes when doing the following:

```JS
const foo = await Foo.findById('someId').populate('bar')

foo.bar.name = 'hi there'

await foo.populate('bar')
// At this point the foo.bar.name modification is wiped out, saving the document will result in no changes
```

I know that this looks like a contrived example and there should be no reason to do it. The problem I'm trying to solve is this:
I have a function, `funky`, that will populate `bar`, it essentially just does `await foo.populate('bar')`, that multiple code paths go to and `funky` requires that all properties of `bar` be available. These code paths contain a mixture of:
  - Instances of a populated `bar` where only certain paths have been selected, such as ` await Foo.findById('someId').populate({path: 'bar', select: 'name'})`
  - Instances like the example above where `select` is not used and modifications to `bar` are made. This includes cases where modifications happen before and after the second `populate` is performed.

I suppose the answer here is that I should audit all of these code paths and remove any `selects` that are happening, and then I shouldn't need the second populate. Just wanted to ask here if there's a way around this though before I spend the time, and potentially create new bugs. 

Thanks for any advice.

**Comment by vkarpov15** [comment]
Unfortunately the only workarounds would be to

 1. `save()` the document before populating again: `await foo.bar.save(); await foo.populate('bar');`
 2. avoid the extra `populate()` if `bar` is already populated: `if (!foo.populated('bar')) await foo.populate('bar');`
 3. store a reference to the old document before populating: `const oldDoc = foo.bar; await foo.populate('bar');` 
  
 `populate()` creates a new populated document, so any change state on the previous document would get wiped out. Do any of these approaches work for you?

**Comment by ericneubauerbumphealth** [comment]
I decided to go ahead and remove a lot of the `select`s that are currently being used in the app so that if a document is populated it should have all fields available. That combined with suggestion #⁠2 should put us in a good spot. Thank you!
