### ISSUE TITLE
MongooseError: Operation `prefixes.findOne()` buffering timed out after 10000ms and MongooseServerSelectionError: connect ECONNREFUSED 13.200.189.28:27017

### ISSUE THREAD

**Issue by PRANAY6201** [Automattic/mongoose#14624]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

18

### MongoDB version

4.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11.3

### Issue

MongooseError: Operation `prefixes.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\pc\Desktop\Bolt\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Comment by vkarpov15** [comment]
Without more code samples, there's no way for us to attempt to repro this. The only suggestions we can offer are:

1. Make sure you're connecting to MongoDB using `mongoose.connect(uri)` or `const conn = mongoose.createConnection(uri);`
2. Make sure you're successfully connecting, your issue title mentions an `ECONNREFUSED` error, which is indicative of trying to connect to a server that is either unreachable or doesn't have MongoDB running.
