### ISSUE TITLE
getting _id as unknown type

### ISSUE THREAD

**Issue by golu7679** [Automattic/mongoose#14631]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.41.

### Node.js version

20.11.1

### MongoDB server version

6.0.14

### Typescript version (if applicable)

5.4.5

### Description

x

### Steps to Reproduce

![image](https://github.com/Automattic/mongoose/assets/55990159/afbe8eeb-50c6-47d5-ac92-5bee158d3fbb)

just creating an schema object getting passing in in function, as you see in the above image,

It was working, after updating the mongoose with latest version getting this error, any solution?

My previous mongoose version was 6.7.5.

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script compiles correctly with Mongoose 8.4.1 and TypeScript 5.4.5. Please modify the following script to demonstrate the issue you're seeing.

```ts
import mongoose from 'mongoose';

const schema = new mongoose.Schema({ email: String });
const TestModel = mongoose.model('Test', schema);

const doc = new TestModel({ email: 'test' });

const id: string = doc.id;
generateAuthToken(doc.id);

function generateAuthToken(id: string) {
}
```

Output:

```
$ ./node_modules/.bin/tsc --strict gh-14631.ts 
$ head ./node_modules/typescript/package.json 
{
    "name": "typescript",
    "author": "Microsoft Corp.",
    "homepage": "https://www.typescriptlang.org/",
    "version": "5.4.5",
    "license": "Apache-2.0",
    "description": "TypeScript is a language for application scale JavaScript development",
    "keywords": [
        "TypeScript",
        "Microsoft",
$ 
```

**Comment by golu7679** [comment]
`
generateAuthToken(doc._id);
`

can you use `_id` instead of `id` ?

Wait, Does _id and id give the same result?

**Comment by vkarpov15** [comment]
No, `_id` is of type ObjectId by default.

**Comment by golu7679** [comment]
and `id` is string type, right?

**Comment by vkarpov15** [comment]
Correct

**Comment by a8t** [comment]
How did you fix this, @golu7679 ? I am experiencing the same.

**Comment by golu7679** [comment]
@a8t `_id` is of type ObjectId by default. if you want to use `_id` as a string then use `TestModel.id` or `TestModel._id+''`
