### ISSUE TITLE
InferRawDocType returns `unknown` for every property instead of the right type

### ISSUE THREAD

**Issue by watch-janick** [Automattic/mongoose#14658]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.4.x

### Node.js version

20.x

### MongoDB version

7.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.7.x

### Issue

Hello!

Following the documentation regarding `InferRawDocType` I'm facing a weird typing issue: **every property of my schema is defined as `unknown`**.

I'm using NestJS Mongoose Schema, could it be the problem?

My goal is to share the same type definition between my backend and frontend app.
I can't use the decorated class `User` on the frontend so I'm trying to get an inferred type that I can use on both.

Here's the code:
```ts
@Schema({ timestamps: true })
export class User {
  @Prop({ type: String, required: true })
  firstName: string

  @Prop({ required: true })
  lastName: string

  @Prop({ required: true })
  email: string

  @Prop({ enum: UserRoles, required: true })
  role: UserRoles

  @Prop({ type: [String], enum: Permissions, required: true })
  permissions: Permissions[]

  @Prop({ type: Date })
  lastLoginAt?: Date

  @Prop({ type: Boolean, default: true })
  isActive?: boolean
}

export type UserDocument = HydratedDocument<User>
export const UserSchema = SchemaFactory.createForClass(User)
export type UserType = InferRawDocType<User>
```
Here's what `UserType` gives:
<img width="860" alt="Screenshot 2024-06-10 at 15 53 09" src="https://github.com/Automattic/mongoose/assets/11473142/b0fc6933-fa3f-4a98-9cf4-70e0f11e9c63">

Any idea as to why the properties aren't typed correctly?

Thanks!

**Comment by vkarpov15** [comment]
`InferRawDocType` converts a Mongoose schema definition into a TypeScript type, so `{ firstName: { type: String, required: true } }` to `{ firstName: string }`. However, with NestJS, you're starting with the TypeScript type and deriving a schema from that, so I don't think you even need `InferRawDocType`.

We did some work to get InferRawDocType to handle `User` correctly, but it looks like the correct output for `InferRawDocType<User>` is just `User` anyway. Is there a reason why you don't just do `export type UserType = User` or something similar?
