### ISSUE TITLE
how to search objectid with regex?

### ISSUE THREAD

**Issue by kawais** [Automattic/mongoose#14668]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.0.1

### Node.js version

20.8.1

### MongoDB version

4.4.21

### Operating system

None

### Issue

i tried these codes, but all not works...
find({ _id: { '$regex': /^5ee51a3d/ } })    //Error Can't use $regex
find({ _id: /a45640bd1f58$/i })   //CastError Cast to ObjectId failed for value "/a45640bd1f58$/i" (type RegExp) at path "_id"
find({ _id: { regx: 'a45640bd1f58$', options: 'i' } })    //CastError Cast to ObjectId failed for value "{ regx: 'a45640bd1f58$', options: 'i' }" (type Object) at path "_id

**Comment by Capta1nRaj** [comment]
I think you can't use regex for `_id` as it is pre-generated by MongoDB.

Here is how I use regex in my code:

`await schemaName.find({ fullName: { "$regex": fullName, "$options": "i" } })`.

**Comment by kawais** [comment]
> I think you can't use regex for `_id` as it is pre-generated by MongoDB.
> 
> Here is how I use regex in my code:
> 
> `await schemaName.find({ fullName: { "$regex": fullName, "$options": "i" } })`.

thanks, but I need search for records containing specific character endings in _id

**Comment by vkarpov15** [comment]
Unfortunately the MongoDB server only supports $regex on strings, from [docs](https://www.mongodb.com/docs/manual/reference/operator/query/regex/):

![image](https://github.com/Automattic/mongoose/assets/1620265/652516f4-5dfa-4c0c-8d83-6f7c62e92a60)

Example using MongoDB shell:

```
MongoDB Enterprise > db.test.find()
{ "_id" : ObjectId("66706828f6f0d973937d4384") }
MongoDB Enterprise > db.test.find({ _id: /677/ })
MongoDB Enterprise > 
```

You would need to filter in memory, for example `const docs = await MyModel.find(); for (const doc of docs) { if (/667/.test(doc._id.toString()) { /* ... */ } }`
