### ISSUE TITLE
MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster

### ISSUE THREAD

**Issue by juliojordan** [Automattic/mongoose#14693]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.2

### Node.js version

20.12.2

### MongoDB server version

6.0.15

### Typescript version (if applicable)

5.0.2

### Description

From time to time, we get this error from an instance of our Azure App Services web app while the others keep working correctly.

I'm aware that tackling a transient error like this is challenging. I really appreciate any help.

```
MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
    at Model.$wrapCallback (/home/site/wwwroot/node_modules/mongoose/lib/model.js:5380:32)
    at /home/site/wwwroot/node_modules/mongoose/lib/query.js:4938:21
    at /home/site/wwwroot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/site/wwwroot/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at model.Query.exec (/home/site/wwwroot/node_modules/mongoose/lib/query.js:4937:10)
    at Query.then (/home/site/wwwroot/node_modules/mongoose/lib/query.js:5020:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(4) {
      'cluster0-shard-00-00.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-01.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-02.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-03.m***t.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-j1***s-shard-0',
    maxElectionId: new ObjectId("7fffffff0000000000000074"),
    maxSetVersion: 12,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
```

### FYI

We deploy our Next.js version 13 application in standalone mode on Azure App Services.

How often do we get this error? Weekly-ish

I intentionally obfuscated some data with "*" from the error log.

### Workaround

The workaround is to kill the errored instance so Azure can start a new one.

### Steps to Reproduce

As a transient error, I cannot provide a list of steps to reproduce it.
Our code base connects and uses Mongoose, as explained in the [docs](https://mongoosejs.com/docs/6.x/docs/guide.html); nothing is custom or hacky.

### Expected Behavior

Not facing the `MongooseServerSelectionError` error.

**Comment by vkarpov15** [comment]
Does this error happen at startup, or after the process has been running for a while? Also, is your Atlas cluster also running on Azure? What's the ping time from your application server to your Atlas cluster approximately?

This error message means that Mongoose isn't able to connect to any of the servers in your Atlas cluster. One potential explanation is just intermittent network issues.

**Comment by juliojordan** [comment]
@vkarpov15, thx for your help!

> Does this error happen at startup, or after the process has been running for a while?

After the process had been running for a while,

> Also, is your Atlas cluster also running on Azure?

No. It runs on AWS.

> What's the ping time from your application server to your Atlas cluster approximately?

I'm not sure if I understand the question. I would say the one that Mongoose sets by default. By checking the logs, it seems like every millisecond.

```
2024-06-23T23:27:17.570Z	WARN	MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
2024-06-23T23:27:17.571Z	WARN	MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
2024-06-23T23:27:17.572Z	WARN	MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
2024-06-23T23:27:17.572Z	WARN	MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
2024-06-23T23:27:17.573Z	WARN	MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
```

> This error message means that Mongoose isn't able to connect to any of the servers in your Atlas cluster. One potential explanation is just intermittent network issues.

Anything we can do to gather more info to confirm if this is the problem?

**Comment by vkarpov15** [comment]
One more question: what's your `serverSelectionTimeoutMS` set to?

**Comment by juliojordan** [comment]
> One more question: what's your `serverSelectionTimeoutMS` set to?

@vkarpov15, thank you! This is our current value.

```
serverSelectionTimeoutMS: 20000
```

**Comment by vkarpov15** [comment]
What does `reason.servers` property in `MongooseServerSelectionError` look like ? Please omit the actual server URLs. This property contains information on what the MongoDB node driver thinks the state of the connection is, and may have some helpful information.

**Comment by juliojordan** [comment]
> What does `reason.servers` property in `MongooseServerSelectionError` look like ? Please omit the actual server URLs. This property contains information on what the MongoDB node driver thinks the state of the connection is, and may have some helpful information.

@vkarpov15, I appreciate your help. Please let me know if this is what you're asking for. 

```javascript
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(4) {
      'cluster0-shard-00-00.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-01.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-02.m***t.mongodb.net:27017' => [ServerDescription],
      'cluster0-shard-00-03.m***t.mongodb.net:27017' => [ServerDescription]
    },
```

I intentionally obfuscated some data with "*".

**Comment by beneater** [comment]
Following along as I'm having the same issue with Next.js 14 running on Vercel using Mongoose with Atlas. Happy to provide any additional info from my environment if it's helpful.

The most promising lead I've found so far is this discussion about this issue occurring on Vercel with the plain node-mongodb-native client: https://jira.mongodb.org/browse/NODE-6179 That ticket references a number of other issues with additional info.

The solution they arrived at is that rather than the caching MongoClient.connect(), they cache MongoClient. It's not really clear to me why that makes a difference, but judging from the comments it seems to have resolved it. I'm not sure if doing something similar with Mongoose is possible. I've looked at the [docs for running with lambda](https://mongoosejs.com/docs/lambda.html) and am doing the last option, caching mongoose.connect(), since that seems like the only option that didn't create other issues with my models being registered properly.

Anyway, hopefully some of that info is useful. Let me know if there's anything else I can provide. Otherwise I'll be following along.

**Comment by vkarpov15** [comment]
@juliojordan I meant specifically what is the contents of `ServerDescription` object in the `reason.servers` property?

**Comment by juliojordan** [comment]
> @juliojordan I meant specifically what is the contents of `ServerDescription` object in the `reason.servers` property?

@vkarpov15, I got it. I will take a look and try to add the changes needed to log the content of the `ServerDescription`. I'll ping you as soon as possible. Thx!
