### ISSUE TITLE
mongoose.Types.ObjectId(string) - Expected 0 arguments, but got 1

### ISSUE THREAD

**Issue by xiaojiudev** [Automattic/mongoose#14694]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.1

### Node.js version

20.9.0

### MongoDB server version

7.0.2

### Typescript version (if applicable)

5.4.5

### Description

My Deno project worked correctly until today I open my VSCode, it show a typescript error (my code still work correctly).

![Screenshot 2024-06-28 090135](https://github.com/Automattic/mongoose/assets/89904184/85ee04d3-a1e8-4ea3-909e-5fddb410108b)

### Steps to Reproduce

``` 
import mongoose from "npm:mongoose@8.4.1";

export const validObjectId = (id: string): boolean => {
	return mongoose.isValidObjectId(id);
};

export const generateObjectId = (id?: string): ObjectIdType => {
	if(id && validObjectId(id)) {
		return new mongoose.Types.ObjectId(id);
	} else {
		return new mongoose.Types.ObjectId();
	}
}
```

### Expected Behavior

Typescript error should be hide

**Comment by sieusanh** [comment]
Hi @xiaojiudev, i tried running your code with all dependencies you have listed, except for MongoDB Server cause i think it's not necessary connecting to database.

Can you show your tsconfig.json and package.json file which includes mongoose and typescript related dependencies.

**Comment by xiaojiudev** [comment]
@sieusanh Here is my configuration in deno.json file (same as package.json), and I also defined typescript config in that file.

![image](https://github.com/Automattic/mongoose/assets/89904184/cf1ee203-3e54-4d38-af70-421916951b03)

**Comment by vkarpov15** [comment]
As a general rule, we don't debug errors that only show up in your IDE. If you're getting a build error when compiling your project we can look into it, but if it's just a VSCode warning the likelihood of us being able to repro it is negligible. For example, I don't get this warning on my machine:

![image](https://github.com/Automattic/mongoose/assets/1620265/c09c1c80-062d-43f2-84c7-bc754ea65682)

**Comment by Bamorem** [comment]
i'm getting the same error

**Comment by vkarpov15** [comment]
Please open a new issue and follow the issue template if you're experiencing a similar issue.
