### ISSUE TITLE
Unreported breaking change - insertMany with lean option

### ISSUE THREAD

**Issue by nadavhalfon** [Automattic/mongoose#14698]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When this issue was raised: https://github.com/Automattic/mongoose/issues/14372
The fix was to skip hydration in "insertMany" - this causes a bug where insertMany suddenly does't take care for "defaults"
I think it should be mention somewhere, just wanted to point it out 🙏

Thank you very much for your work !

**Comment by vkarpov15** [comment]
That's a good point, we will add this to our docs. As a workaround, you can use [`Model.applyDefaults()`](https://mongoosejs.com/docs/api/model.html#Model.applyDefaults()) to apply the defaults to your lean objects before saving as follows.

```javascript
await MyModel.insertMany(docs.map(doc => MyModel.applyDefaults(doc)), { lean: true })
```

**Comment by 7freaks-otte** [comment]
Note: This seems to have appeared in the 7.x branch as well - presumably with 7.6.10

**Comment by ayoubkhial** [comment]
This behavior is still present in version 8.6.3 :(

**Comment by ayoubkhial** [comment]
This behavior is still present in version 8.7.0

**Comment by nadavhalfon** [comment]
Is there a change that applyDefaults was removed?
