### ISSUE TITLE
`mongoose.connection.db.dropDatabase()` callback is not invoked

### ISSUE THREAD

**Issue by thatmarvin** [Automattic/mongoose#1469]
The following works fine in 3.5.11, but simply hangs forever in 3.5.12.

``` js
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/drop-test');

mongoose.connection.db.dropDatabase(function (err) {
  console.log('db dropped');
  process.exit(0);
});
```

Using the 1.3.0 driver directly works fine though:

``` js
var Db = require('mongodb').Db,
    Server = require('mongodb').Server,
    assert = require('assert');

var db = new Db('drop-test', new Server('localhost', 27017));
db.open(function(err, db) {
  db.dropDatabase(function(err, result) {
    console.log('db dropped');
    process.exit(0);
  });
});

```

**Comment by ivawzh** [comment]
I have got into the same problem. The callback from `db.dropDatabase()` is never triggered. 
My mongoose version: `"mongoose": "^4.2.4"`.

```
import mongoose from 'mongoose'

export default function dropMongoDatabase(callback) {
  const connectionStates = mongoose.Connection.STATES
  const readyState = mongoose.connection.readyState
  const drop = () => {
    // TODO callback is always not triggered
    // callback function: function(err, result){}.
    mongoose.connection.db.dropDatabase(callback)
  }
  if (connectionStates[readyState] === 'connected') {
    drop()
  } else {
    mongoose.connection.once('connected', drop)
  }
}
```

**Comment by vkarpov15** [comment]
Have you tried the suggestion of waiting for the 'open' event in the above comment? Our [tests rely on `.dropDatabase()`](https://github.com/Automattic/mongoose/blob/62a8fee5ea92dc10e1ade16dda44488d3928245b/test/common.js#L131) so `dropDatabase()` should fire as long as you use it correctly...

**Comment by ivawzh** [comment]
I thought 'connection.once('connected', drop)' is equivalent to 'open'. Or would you please give me an example how to do it correctly?

**Comment by ivawzh** [comment]
I still can't fix the problem. My code now looks like this:

```
import mongoose from 'mongoose'
export default function dropMongoDatabase(callback) {
  mongoose.connection.once('open', ()=> {
    mongoose.connection.db.dropDatabase(callback)
  })
}

describe('test', () => {
  beforeEach(done => {
    restoreDatabase((err, result) => {
      console.log('HEREEEEEEEEE')
      expect(err).to.not.exist
      done()
    })
  })
...
```
Error message:
```
 1) test "before each" hook for "should blah":
     Error: timeout of 4000ms exceeded. Ensure the done() callback is being called in this test.
```
And the `console.log('HEREEEEEEEEE')` message never appears. =[

**Comment by vkarpov15** [comment]
Errr what's the restoreDatabase function? I don't see it anywhere

**Comment by ivawzh** [comment]
I found out the problem I had was having duplicated event listener on `once('open')`. I fixed the problem by using `mongoose.connection.removeAllListeners('open')`

**Comment by AanshSavla** [comment]
Mongoose uses promise.
We can use
mongoose.connection.db.dropDatabase().then(function(){
    mongoose.connection.close();
});
