### ISSUE TITLE
TypeScript does not return an error when assigning the result of a `lean` query to a variable of type `InstanceType<Model<MyModel>>`

### ISSUE THREAD

**Issue by nikzanda** [Automattic/mongoose#14697]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.4

### Node.js version

20.10.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

5.4.5

### Description

Reproduction link: https://stackblitz.com/edit/stackblitz-starters-9hjjfm?file=src%2Findex.ts

TypeScript should not allow me to assign the result of `await UserModel.findOne().lean();` to the variable `let user: UserInstance | null = null;` in fact, the user.set or user.save instruction results in an error.

```ts
  let user: UserInstance | null = null;
  if (condition) {
    user = await UserModel.findOne().lean(); // Here it should report an error
    if (user) {
      user.set({
        name: 'John Doe',
      });
      await user.save();
    }
  }
```

The code below
![image](https://github.com/Automattic/mongoose/assets/71180446/48fab565-27d2-4606-9520-64c779c04649)
![image](https://github.com/Automattic/mongoose/assets/71180446/8c3b6cb8-f5d3-420f-b002-a9fd1090a6b1)

results in an error when executed:
<img width="614" alt="Screenshot 2024-06-28 at 18 24 06" src="https://github.com/Automattic/mongoose/assets/71180446/2ca42816-7c44-4733-9de7-172113aa8e89">

### Steps to Reproduce

- Declare a variable of type `InstanceType<Model<MyModel>>`;
- Assign the result of `await MyModel.findOne().lean();`
- Call `.set({ ... })` or `.save()` function of the variabile.

### Expected Behavior

TypeScript should not allow the code to compile

**Comment by IslandRhythms** [comment]
```typescript
import {
    Schema,
    connection,
    connect,
    Model,
    model,
    SchemaOptions,
    SchemaTypes,
  } from 'mongoose';
  
  export interface IUser {
    name: string;
    createdAt: Date;
    updatedAt: Date;
  }
  
  export interface IUserVirtuals {
    id: string;
  }
  
  type UserModelType = Model<IUser, {}, {}, IUserVirtuals>;
  
  export type UserInstance = InstanceType<UserModelType>;
  
  const options: SchemaOptions<IUser> = {
    timestamps: true,
    optimisticConcurrency: true,
  };

  const userSchema = new Schema<IUser, UserModelType>(
    {
      name: {
        type: SchemaTypes.String,
        required: true,
        trim: true,
      },
    },
    options
  );

  const User = model<IUser, UserModelType>('User', userSchema);

  async function run() {
    await connect('mongodb://localhost:27017');
    await connection.dropDatabase();

    await User.create({
        name: 'John',
      });
    
    
      let user: UserInstance | null = null;
      user = await User.findOne().lean();
        if (user) {
          user.set({
            name: 'John Doe',
          });
          await user.save();
        }
    console.log(user);
  }

  run();
```

**Comment by nikzanda** [comment]
> ```ts
> await User.create({
>         name: 'John',
>       });
>     
>     
>       let user: UserInstance | null = null;
>       user = await User.findOne().lean();
>         if (user) {
>           user.name = 'John Doe'
>           await user.save();
>         }
>     console.log(user);
> ```

Sorry, but your code does not work, as the [documentation](https://mongoosejs.com/docs/tutorials/lean.html) states:

_The [lean option](https://mongoosejs.com/docs/api/query.html#query_Query-lean) tells Mongoose to skip [hydrating](https://mongoosejs.com/docs/api/model.html#model_Model-hydrate) the result documents. This makes queries faster and less memory intensive, but the result documents are plain old JavaScript objects (POJOs), not [Mongoose documents](https://mongoosejs.com/docs/documents.html)._

Therefore, the save method cannot be called and TypeScript does not report any errors:

<img width="597" alt="Screenshot 2024-07-02 at 20 47 51" src="https://github.com/Automattic/mongoose/assets/71180446/c28dcde0-6d05-4107-8e91-bbbbc31087f5">

**Comment by IslandRhythms** [comment]
Then why are you reporting this as a bug?

**Comment by vkarpov15** [comment]
As a workaround, you can do `user = await User.findOne().lean<IUser>();`. I'm investigating why this issue is happening.

**Comment by nikzanda** [comment]
Thank you
