### ISSUE TITLE
Clarifications regarding idle socket connections 

### ISSUE THREAD

**Issue by vBitza** [Automattic/mongoose#14716]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.4

### Node.js version

20.9.0

### MongoDB version

6.0.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Issue

Hi,

I have the following setup:
Mongo Replica Set with 3 Nodes 
Connection Options:
- maxPoolSize: 3
- socketTimeoutMS: 30000

While running the following Query:
`
db.currentOp(true).inprog.reduce(
    (accumulator, connection) => {
      appName = connection.appName ? connection.appName : connection.desc;
      accumulator[appName] = (accumulator[appName] || 0) + 1;
      accumulator["TOTAL_CONNECTION_COUNT"]++;
      return accumulator;
    },
    { TOTAL_CONNECTION_COUNT: 0 }
)
`

My app has a total of 14 connections. However, based on the formula provided here: https://www.mongodb.com/community/forums/t/poolsize-connection-count/113029/2 the maximum number of Connections should have been 12 not 14. Does Mongoose open additional connections for internal stuff in some manner?

Another question is related to how does Mongoose handle closing connection. It seems that the sockets are not closed (I do not close them programmatically) as I thought they will eventually be closed by application. However, since keepAlive is no longer a configurable option, does that mean that open sockets will stay active unless they are programmatically closed? Is there an option to control how often should idle sockets be closed?

**Comment by vkarpov15** [comment]
**Does Mongoose open additional connections for internal stuff in some manner?** Yes, the MongoDB node driver maintains a separate connection for monitoring.

**does that mean that open sockets will stay active unless they are programmatically closed?** Not necessarily, the MongoDB node driver may close idle sockets.

**Is there an option to control how often should idle sockets be closed?** There's a `maxIdleTimeMS` option which can configure how long a connection can stay idle. There's also a `minPoolSize` option: if `minPoolSize === maxPoolSize` then the MongoDB node driver shouldn't close any sockets.

**Comment by vBitza** [comment]
By `maxIdleTimeMS` you are refering to `socketTimeoutMS` ?
