### ISSUE TITLE
Improve readyState behavior to more reliably report connection state

### ISSUE THREAD

**Issue by alexbevi** [Automattic/mongoose#14727]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Since `readyState` updates are based on topology status updates, it's less reliable in stateless environments (such as AWS Lamba) as topology update events may be missed while the execution environment is frozen.

This can result in `readyState` tests returning stale state information.

**Comment by vkarpov15** [comment]
Going to move this one back because I've been having trouble reproducing this issue in AWS lambda
