### ISSUE TITLE
Type 'ChangeStreamOptions & { writeConcern?: never; }' is not assignable to type 'ChangeStreamOptions'.

### ISSUE THREAD

**Issue by frank-mendez** [Automattic/mongoose#14731]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.4

### Node.js version

21.6.2

### MongoDB server version

6.0.4

### Typescript version (if applicable)

5.1.3

### Description

![image](https://github.com/Automattic/mongoose/assets/5987618/5379c83b-d622-4964-9097-d4c7b9992b32)

```
async onApplicationBootstrap() {
    this.changeStream = this.eventStore
      .watch()
      .on('change', (change: ChangeStreamInsertDocument<EventDocument>) => {
        if (change.operationType === 'insert') {
          this.handleEventStoreChange(change);
        }
      });
  }
```

### Steps to Reproduce
![image](https://github.com/Automattic/mongoose/assets/5987618/5db46174-50b4-43dc-950d-6f90bb117c0b)

Create a class `EventsBridge` implements `OnApplicationBootstrap` and `OnApplicationShutdown` create a private variable `private changeStream: ChangeStream;` 

```
async onApplicationBootstrap() {
    this.changeStream = this.eventStore
      .watch()
      .on('change', (change: ChangeStreamInsertDocument<EventDocument>) => {
        if (change.operationType === 'insert') {
          this.handleEventStoreChange(change);
        }
      });
  }
```

### Expected Behavior

Should not expect not missing `MongoOptions`  Type MongoOptions is missing the following properties from type MongoOptions: `keepAlive`, `keepAliveInitialDelay`

**Comment by vkarpov15** [comment]
Can you please provide what your `package.json` dependencies look like? This issue looks like it may be due to having multiple incompatible versions of the MongoDB Node driver installed: the error message indicates that you're trying to assign `node_modules/mongoose/node_modules/mongodb`'s version of `ChangeStreamOptions` to a variable that expects `node_modules/mongodb`'s version of `ChangeStreamOptions`. Likely because you have a top-level dependency on "mongoose" and "mongodb", and your version of "mongodb" is different from mongoose's

**Comment by frank-mendez** [comment]
I'm using `mongoose: 10.06` and NestJS Mongoose `@nestjs/mongoose: 10.0.6`
![image](https://github.com/Automattic/mongoose/assets/5987618/591dcb98-f2db-448f-bd2e-cef293e49cf4)
Also for my docker environment I'm using `mongo: 6.0.4`

![image](https://github.com/Automattic/mongoose/assets/5987618/7eb62f04-f165-402a-a021-ecf251f64178)

**Comment by frank-mendez** [comment]
@vkarpov15 Thank you for taking a look. I'll also review the dependencies within the NestJS ecosystem. Currently, my API is functioning properly. For now, I've added some //ts-ignore comments.

**Comment by frank-mendez** [comment]
![image](https://github.com/Automattic/mongoose/assets/5987618/0bc75494-2966-4228-af13-eea7e41dbe81)

**Comment by vkarpov15** [comment]
Can you please run `npm list mongodb` and paste the output in a comment? That should help determine where the duplicate mongodb dep is coming from.

**Comment by frank-mendez** [comment]
![image](https://github.com/user-attachments/assets/af2a6e4d-e6a0-4896-8d0e-e84d37549b67)

**Comment by vkarpov15** [comment]
Ah ok, it looks like you're using a version of typeorm that pulls in a different version of MongoDB. Weirdly enough, [typeorm seems to only support MongoDB driver 5.x](https://github.com/typeorm/typeorm/blob/e7649d2746f907ff36b1efb600402dedd5f5a499/package.json#L156), even though their devDependencies use mongodb driver 6.x for testing :confused: 

You should be able to [override typeorm to use mongodb@6](https://github.com/npm/rfcs/discussions/552), I'll try this out.

**Comment by vkarpov15** [comment]
Yeah I tried this out and you can do the following in `package.json`:

```
{
  "dependencies": {
    "mongoose": "8.4.4",
    "typeorm": "0.3.20"
  },
  "overrides":{
    "mongodb": "6.6.2"
  }
}
```

Just make sure your "mongodb" override lines up with Mongoose's version of mongodb.
