### ISSUE TITLE
Preserve isNew state in post save

### ISSUE THREAD

**Issue by greggreenhaw** [Automattic/mongoose#1474]
It still important to know if the object was new in the post save middleware right now i believe it is set to false it should be set to false after the post save.

**Comment by emanuelecasadio** [comment]
Guys, this tweak should really be added to the current branch.

**Comment by lbstr** [comment]
Any reason why `wasNew` shouldn't be built in? Should we add it to mongoose?

**Comment by vkarpov15** [comment]
Reasonable idea, we'll consider it for later 5.x releases.

**Comment by darkterra** [comment]
Hello everybody !

Any update for this built in feature ?

`wasNew` is not present on mongoose _(5.4.19)_ when I trie to save a new document

**Comment by thakurinbox** [comment]
@darkterra `wasNew` is not there, you need to create it inside `pre` and than can use inside `post` as mentioned in above comment https://github.com/Automattic/mongoose/issues/1474#issuecomment-17669982

**Comment by darkterra** [comment]
@thakurinbox, thank you for your response.

If I understand correctly the question of the original post is to "preserve **isNew** _in the postSave hook_", then @emanuelecasadio, @lbstr and @vkarpov15 seems to say that it would be nice to have built in this data in" postSave " _ (whether it is the property 'isNew' or 'wasNew') _.

I have not 'isNew' or 'wasNew', so I wondered if the 'isNew' property no longer exists and will be replaced by the future by 'wasNew'?

_Little peace of code:_
```javascript
'use strict';

const mongoose = require('mongoose');  // v5.4.19

const connect = mongoose.connect('mongodb://localhost/test_mongoose', { useNewUrlParser: true });
console.log('mongoose connect: ', connect);

connect.then(connectionObject => {
  const Schema = mongoose.Schema;
 
  const BlogPost = new Schema({
    title: String,
    body: String,
    date: Date
  });
  
  BlogPost.pre('save', function(next, doc, err) {
    console.log('pre: this: ', this);
    console.log('pre: doc: ', doc);
    next();
  });
  
  BlogPost.post('save', function(doc, next) {
    console.log('post: this: ', this);
    console.log('post: doc: ', doc);
    next();
  });
  
  const BlogModel = mongoose.model('BlogPost', BlogPost);
  
  
  const newBlogPost = new BlogModel({
    title: 'This is a test',
    body: 'This is the BEST POST ever !!!!!',
    date: new Date()
  });
  
  console.log('newBlogPost: ', newBlogPost);
  
  newBlogPost.save((err, doc) => {
    if (err) {
      console.error(err);
    }
    else
    {
      console.log('callback SAVE: ', doc);
      console.log('Post SAVED :)')
    }
  });
})

```
_And no **isNew** or **wasNew** there:_
```javascript
mongoose connect:  Promise { <pending> }

newBlogPost:  { _id: 5c90aeb34f000a254ed2b6f7,
  title: 'This is a test',
  body: 'This is the BEST POST ever !!!!!',
  date: 2019-03-19T08:56:19.011Z }

pre: this:  { _id: 5c90aeb34f000a254ed2b6f7,
  title: 'This is a test',
  body: 'This is the BEST POST ever !!!!!',
  date: 2019-03-19T08:56:19.011Z }

pre: doc:  SaveOptions {}

post: this:  { _id: 5c90aeb34f000a254ed2b6f7,
  title: 'This is a test',
  body: 'This is the BEST POST ever !!!!!',
  date: 2019-03-19T08:56:19.011Z,
  __v: 0 }

post: doc:  { _id: 5c90aeb34f000a254ed2b6f7,
  title: 'This is a test',
  body: 'This is the BEST POST ever !!!!!',
  date: 2019-03-19T08:56:19.011Z,
  __v: 0 }

callback SAVE:  { _id: 5c90aeb34f000a254ed2b6f7,
  title: 'This is a test',
  body: 'This is the BEST POST ever !!!!!',
  date: 2019-03-19T08:56:19.011Z,
  __v: 0 }

Post SAVED :)
```

**Comment by darkterra** [comment]
Ok, obviously, the console can not seem to show me the other property of the object as well as these methods, but I try to call "this.isNew" and "this.isModified ()" in the preSave and I have something that appears in the console ...

```javascript

  BlogPost.pre('save', function(next, doc, err) {
    console.log('pre: this: ', this);
    console.log('pre: doc: ', doc);
    console.log('pre: this.isNew: ', this.isNew); // true
    console.log('pre: this.isModified(): ', this.isModified()); // true
    
    this.wasNew = this.isNew;

    console.log('pre: this.wasNew: ', this.wasNew); // true
    next();
  });
```

So, I confirm that the trick in this issue works well. On the other hand, in the past, I am sure that the console could display the functions and other properties of the object over defined by Mongoose.

**Comment by vkarpov15** [comment]
No updates on this feature yet, that's why this issue is still open :+1: . Manually setting wasNew in pre save is the way to go for now

**Comment by SailokChinta** [comment]
@vkarpov15 can we expect whether this feature would be added in further new releases? This seems to be a pretty common issue, isn't it?

**Comment by vkarpov15** [comment]
@SailokChinta we don't plan on adding this any time in the near future. Adding support for `wasNew` via a global plugin is a one-liner, so not a priority for now.

**Comment by Konijima** [comment]
> ```js
> schema.pre('save', function (next) {
>   this.wasNew = this.isNew;
>   next();
> })
> 
> schema.post('save', function () {
>   if (this.wasNew) {
>      // ...
>   }
> })
> ```

This would be an ok solution if it didn't trigger an error with Typescript...
It's 2022 and no fix/update for this yet?

**Comment by Uzlopak** [comment]
Would you please create a new issue as it is a different scope bug (typescript) and provide a mcve? 

I would then try to fix the issue.

**Comment by vkarpov15** [comment]
@Konijima you can always just use `this.$locals.wasNew` instead, that should appease TypeScript.
