### ISSUE TITLE
Optional Arguments in SchemaTypes.path().cast required by Typescript

### ISSUE THREAD

**Issue by iamjackchen** [Automattic/mongoose#14748]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.7

### Node.js version

18.20.3

### MongoDB server version

7.0.12

### Typescript version (if applicable)

5.2.2

### Description

It looks like the typescript signature for SchemaTypes.path().cast require some (what appear to be) optional fields.

I wanted to create a subdocument instance without creating a model. With reference to https://github.com/Automattic/mongoose/issues/9076,

I had 
![image](https://github.com/user-attachments/assets/d575482b-4d18-4b7d-a998-b717897e5535)

which works exactly as intended with the //@ts-ignore, but otherwise gives me a type error. Upon further examination,
it appears that 
![image](https://github.com/user-attachments/assets/f0f45d6f-4b70-45ea-9025-c61a04b39f25)
doc and init are required fields in the typescript signature, whereas they seem to be optional in a lot of the documentation I've seen.

This is my top-level schema file:
![image](https://github.com/user-attachments/assets/2f1e7d11-1d9d-4634-b725-2a0b06f8e47d)

Please let me know if I'm mistaken somewhere, many thanks!! 

### Steps to Reproduce

Please see above. 

### Expected Behavior

Optional (?) fields should be required by typescript signature

**Comment by Imanghvs** [comment]
They are required fields according to the the docs here: https://mongoosejs.com/docs/api/schematype.html#SchemaType.prototype.cast()
I'm not sure how it works without typescript. Maybe the code handles `undefined` values somehow.
