### ISSUE TITLE
Mongoose is creating ghost/empty collections for every database under a project where multiple schemas are used

### ISSUE THREAD

**Issue by manny53365** [Automattic/mongoose#14754]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.3

### Node.js version

20.12.1

### MongoDB server version

N/A

### Typescript version (if applicable)

N/A

### Description

I am observing an issue when I create multiple schemas. I have tested the same code using the native MongoDB driver instead of Mongoose and the problem does not exist with the native driver. 

# Problem
When I am making database calls Mongoose creates ghost collections under each database it touches even for schemas not called. For example, say I have 4 schemas `[Sale, SuperUser, Title, Workspace]`; if I call to update current sales 4 collections are created under the current database even though I will only ever use the `Sale` schema in this example. The other schemas belong to entirely different databases in the same project. This happens for every database created and no records are entered into these ghost collections that should not exist. This could increase the costs that people pay for enterprise-level applications. 

Here is a screenshot of the problem:
![Screenshot 2024-07-19 at 3 35 02 PM](https://github.com/user-attachments/assets/3bb3e1d9-d341-4ecd-8ed3-52e1223e9db3)

Here is a working example with the native Mongo driver:
![Screenshot 2024-07-19 at 3 30 18 PM](https://github.com/user-attachments/assets/6e6fe537-d052-4512-8ada-7dd8c90b2bab)

Bear in mind that this is the same database the only difference is the method for writing to MongoDB - the code and logic are the same, Mongoose vs MongoDB driver is the only difference.

### Steps to Reproduce

# Steps to reproduce

1. Create more than 1 schema
2. Ensure both schemas are for the same MongoDB project
3. Each schema should communicate to its database under the project
4. When you make a call to Mongo to create/update etc. Mongoose will create an empty/ghost collection for the unused Schema. 
    -   For example, if I update or create a sale then the title collection is also created under that database. 

**NOTE**: This issue is repeatable on demand if needed. I haven't attached a video due to sensitive data.

### Expected Behavior

# Expected Behavior

A collection should not be created under a database that never calls it. Attached is a working example of how structures should be (not empty)
![Screenshot 2024-07-19 at 3 30 18 PM](https://github.com/user-attachments/assets/0ea41ae6-e9ca-472d-8719-7baf15129b9d)

**Comment by Imanghvs** [comment]
Whenever the `mongoose.model` is called on your schema, a collection is made automatically. It usually happens when you are importing your separated schema files containing this method.

You can prevent this behavior by passing `autoCreate: false` when instantiating the `Schema` class. Like this:

```
const mongoose = require("mongoose");

const User = new mongoose.Schema({
    username: {
        type: String
    }
}, {autoCreate: false})

module.exports = mongoose.model('User', User);
```

**Comment by manny53365** [comment]
Thanks, I will give that a go and let you know if that corrects the issue

**Comment by vkarpov15** [comment]
If you're still running into an issue, please provide code samples for the "Steps to reproduce" section. I think you're mixing up models and schemas in your description, and that makes your description very confusing. For example, the following script won't create any collections in MongoDB.

```javascript
const mongoose = require('mongoose');

const schema1 = new mongoose.Schema();
const schema2 = new mongoose.Schema();
```
