### ISSUE TITLE
Mongoose potentially fails to disconnect from mongod when used with pm2

### ISSUE THREAD

**Issue by GalacticHypernova** [Automattic/mongoose#14750]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.7.0 (according to the lockfile)

### Node.js version

20.15.1

### MongoDB version

v7.0.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu v22.04.3

## NOTE:
I am not certain the issue is within mongoose. I am investigating the possible culprits.

---

Apologies for the messy title, I don't quite know how to correctly categorize it as I'm still investigating it.
I'm running an app with pm2 set to cluster mode and max instances. The app uses mongodb (via mongoose).
When running the app via pm2, the amount of mongod threads climbs consistently, starting from 80 threads and up to >999, causing server unavailability and unresponsiveness.

I have added kill_timeout: 6000 to the pm2 ecosystem.config.js but it doesn't seem to have fixed the issue, as I manually have to restart mongod in order to reduce the amount of threads.
Below is the ecosystem.config.js file:
```js
module.exports = {
	apps: [
		{
			name: 'name',
			port: '3000',
			exec_mode: 'cluster',
			instances: 'max',
			kill_timeout: 6000,
			script: 'path/to/script.mjs'
		}
	]
}
```

I have already made sure that in terms of the app code, the connection through mongoose happens in a server plugin (a piece of code that runs once on server startup) and the disconnection happens in a graceful shutdown hook that listens to SIGINT and SIGTERM. If needed, I can share a reproduction privately as the project is closed source.

**Comment by GalacticHypernova** [comment]
The issue is not mongoose

**Comment by RShah512** [comment]
@GalacticHypernova Did you mange to find out the root cause for this issue?
