### ISSUE TITLE
populate not working without lean()

### ISSUE THREAD

**Issue by Arjun059** [Automattic/mongoose#14757]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.x.x

### Node.js version

18.x

### MongoDB server version

7.x.x

### Description

populate not working without lean().
 let query = Model.find({}, {});
 query.populate({path: "path", select: "select fields" }) // not working
 let data = await query; // not working

 query.populate({path: "path", select: "select fields" }).lean()  // works fine
 let data = await query; // work fine

 

### Steps to Reproduce

populate not working without lean().
 let query = Model.find({}, {});
 query.populate({path: "path", select: "select fields" }) // not working
 let data = await query; // not working

 query.populate({path: "path", select: "select fields" }).lean()  // works fine
 let data = await query; // work fine

### Expected Behavior

populate should work without lean()

**Comment by vkarpov15** [comment]
Please clarify what you mean by "not working" - are you getting some sort of error message?

**Comment by Arjun059** [comment]
> Please clarify what you mean by "not working" - are you getting some sort of error message?

There is no error, but the populated document is not returned when I use Model.populate({ path: "pathField", select: "apple mango"}). However, it works fine with the string Model.populate("pathField").

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script shows same result with and without `lean()`

```javascript
const mongoose = require('mongoose');

const AuthorSchema = new mongoose.Schema({
    name: String,
});
const BookSchema = new mongoose.Schema({
    title: String,
    author: { type: mongoose.Schema.Types.ObjectId, ref: 'Author' }
});
// Create models
const Author = mongoose.model('Author', AuthorSchema);
const Book = mongoose.model('Book', BookSchema);
async function main() {
    // Connect to MongoDB
    await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');

    // Clean up the database
    await Author.deleteMany({});
    await Book.deleteMany({});

    // Create test data
    const author = await Author.create({ name: 'John Doe' });
    await Book.create({ title: 'Mongoose Guide', author: author._id });

    // Test populate without lean()
    let query = Book.find({});
    query.populate({ path: 'author', select: 'name' });
    let data = await query;
    console.log('Without lean():', data);

    // Test populate with lean()
    query = Book.find({});
    query.populate({ path: 'author', select: 'name' }).lean();
    data = await query;
    console.log('With lean():', data);

    // Close the connection
    await mongoose.connection.close();
}

main().catch(err => console.error(err));

```

Output:

```
$ node gh-14757.js 
Without lean(): [
  {
    _id: new ObjectId('66ba5409c961677682494970'),
    title: 'Mongoose Guide',
    author: { _id: new ObjectId('66ba5409c96167768249496e'), name: 'John Doe' },
    __v: 0
  }
]
With lean(): [
  {
    _id: new ObjectId('66ba5409c961677682494970'),
    title: 'Mongoose Guide',
    author: { _id: new ObjectId('66ba5409c96167768249496e'), name: 'John Doe' },
    __v: 0
  }
]
```

Here is [Mongoose playground link](https://playground.mongoosejs.io/#Y29uc3QgQXV0aG9yU2NoZW1hID0gbmV3IG1vbmdvb3NlLlNjaGVtYSh7CiAgICBuYW1lOiBTdHJpbmcsCn0pOwpjb25zdCBCb29rU2NoZW1hID0gbmV3IG1vbmdvb3NlLlNjaGVtYSh7CiAgICB0aXRsZTogU3RyaW5nLAogICAgYXV0aG9yOiB7IHR5cGU6IG1vbmdvb3NlLlNjaGVtYS5UeXBlcy5PYmplY3RJZCwgcmVmOiAnQXV0aG9yJyB9Cn0pOwoKLy8gQ3JlYXRlIG1vZGVscwpjb25zdCBBdXRob3IgPSBtb25nb29zZS5tb2RlbCgnQXV0aG9yJywgQXV0aG9yU2NoZW1hKTsKY29uc3QgQm9vayA9IG1vbmdvb3NlLm1vZGVsKCdCb29rJywgQm9va1NjaGVtYSk7Cgphc3luYyBmdW5jdGlvbiBtYWluKCkgewogICAgLy8gQ29ubmVjdCB0byBNb25nb0RCCiAgICBhd2FpdCBtb25nb29zZS5jb25uZWN0KCdtb25nb2RiOi8vbG9jYWxob3N0OjI3MDE3L21vbmdvb3NlX3Rlc3QnKTsKCiAgICAvLyBDbGVhbiB1cCB0aGUgZGF0YWJhc2UKICAgIGF3YWl0IEF1dGhvci5kZWxldGVNYW55KHt9KTsKICAgIGF3YWl0IEJvb2suZGVsZXRlTWFueSh7fSk7CgogICAgLy8gQ3JlYXRlIHRlc3QgZGF0YQogICAgY29uc3QgYXV0aG9yID0gYXdhaXQgQXV0aG9yLmNyZWF0ZSh7IG5hbWU6ICdKb2huIERvZScgfSk7CiAgICBhd2FpdCBCb29rLmNyZWF0ZSh7IHRpdGxlOiAnTW9uZ29vc2UgR3VpZGUnLCBhdXRob3I6IGF1dGhvci5faWQgfSk7CgogICAgLy8gVGVzdCBwb3B1bGF0ZSB3aXRob3V0IGxlYW4oKQogICAgbGV0IHF1ZXJ5ID0gQm9vay5maW5kKHt9KTsKICAgIHF1ZXJ5LnBvcHVsYXRlKHsgcGF0aDogJ2F1dGhvcicsIHNlbGVjdDogJ25hbWUnIH0pOwogICAgbGV0IGRhdGEgPSBhd2FpdCBxdWVyeTsKICAgIGNvbnNvbGUubG9nKCdXaXRob3V0IGxlYW4oKTonLCBkYXRhKTsKCiAgICAvLyBUZXN0IHBvcHVsYXRlIHdpdGggbGVhbigpCiAgICBxdWVyeSA9IEJvb2suZmluZCh7fSk7CiAgICBxdWVyeS5wb3B1bGF0ZSh7IHBhdGg6ICdhdXRob3InLCBzZWxlY3Q6ICduYW1lJyB9KS5sZWFuKCk7CiAgICBkYXRhID0gYXdhaXQgcXVlcnk7CiAgICBjb25zb2xlLmxvZygnV2l0aCBsZWFuKCk6JywgZGF0YSk7CgogICAgLy8gQ2xvc2UgdGhlIGNvbm5lY3Rpb24KICAgIGF3YWl0IG1vbmdvb3NlLmNvbm5lY3Rpb24uY2xvc2UoKTsKfQoKbWFpbigpOwo=)
