### ISSUE TITLE
Mongoose v6.12.6 installing optional dependencies @aws-sdk packages via mongodb 4.17.2

### ISSUE THREAD

**Issue by h2atecnologia** [Automattic/mongoose#14768]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.6

### Node.js version

14.21.3

### MongoDB server version

5.0

### Description

By install mongoose 6.12.6 with -E, I saw npm installing @aws-sdk packages since mongodb 4.17.2 is a dependency of this version.  these @aws-sdk are declared just as optional in mongodb package.json.  in the package.json, is declared node engine >=12.9.0. but these @aws-sdk are not compatible with node versions below 16.

### Steps to Reproduce

#use node 14.21.3 or another 14.x version
npm install -E mongoose@6.12.6

### Expected Behavior

I will see @aws-sdk not compatible packages been installed and the summary warnings and errors of npm install.

**Comment by h2atecnologia** [comment]
`npm i mongoose@6.12.6 -E
              
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @aws-sdk/credential-providers@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-providers@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-process@3.614.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-process@3.614.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-sso@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-sso@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-ini@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-ini@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/types@3.609.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/types@3.609.0
npm WARN notsup Unsupported engine for @smithy/credential-provider-imds@3.2.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/credential-provider-imds@3.2.0
npm WARN notsup Unsupported engine for @smithy/property-provider@3.1.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/property-provider@3.1.3
npm WARN notsup Unsupported engine for @smithy/types@3.3.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/types@3.3.0
npm WARN notsup Unsupported engine for @aws-sdk/client-sso@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/client-sso@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-web-identity@3.609.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-web-identity@3.609.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-cognito-identity@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-cognito-identity@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-node@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-node@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/client-cognito-identity@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/client-cognito-identity@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-http@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-http@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/client-sts@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/client-sts@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/credential-provider-env@3.609.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/credential-provider-env@3.609.0
npm WARN notsup Unsupported engine for @aws-crypto/sha256-js@5.2.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-crypto/sha256-js@5.2.0
npm WARN notsup Unsupported engine for @aws-sdk/middleware-host-header@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/middleware-host-header@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/middleware-logger@3.609.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/middleware-logger@3.609.0
npm WARN notsup Unsupported engine for @aws-sdk/middleware-recursion-detection@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/middleware-recursion-detection@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/middleware-user-agent@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/middleware-user-agent@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/client-sso-oidc@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/client-sso-oidc@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/util-user-agent-node@3.614.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/util-user-agent-node@3.614.0
npm WARN notsup Unsupported engine for @smithy/core@2.3.1: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/core@2.3.1
npm WARN notsup Unsupported engine for @smithy/hash-node@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/hash-node@3.0.3
npm WARN notsup Unsupported engine for @smithy/middleware-content-length@3.0.5: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/middleware-content-length@3.0.5
npm WARN notsup Unsupported engine for @smithy/middleware-endpoint@3.1.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/middleware-endpoint@3.1.0
npm WARN notsup Unsupported engine for @smithy/middleware-retry@3.0.13: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/middleware-retry@3.0.13
npm WARN notsup Unsupported engine for @smithy/middleware-serde@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/middleware-serde@3.0.3
npm WARN notsup Unsupported engine for @aws-sdk/core@3.620.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/core@3.620.0
npm WARN notsup Unsupported engine for @aws-sdk/region-config-resolver@3.614.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/region-config-resolver@3.614.0
npm WARN notsup Unsupported engine for @aws-sdk/util-endpoints@3.614.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/util-endpoints@3.614.0
npm WARN notsup Unsupported engine for @smithy/middleware-stack@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/middleware-stack@3.0.3
npm WARN notsup Unsupported engine for @smithy/node-config-provider@3.1.4: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/node-config-provider@3.1.4
npm WARN notsup Unsupported engine for @smithy/node-http-handler@3.1.4: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/node-http-handler@3.1.4
npm WARN notsup Unsupported engine for @smithy/protocol-http@4.1.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/protocol-http@4.1.0
npm WARN notsup Unsupported engine for @smithy/smithy-client@3.1.11: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/smithy-client@3.1.11
npm WARN notsup Unsupported engine for @smithy/config-resolver@3.0.5: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/config-resolver@3.0.5
npm WARN notsup Unsupported engine for @smithy/util-base64@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-base64@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-body-length-node@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-body-length-node@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-endpoints@2.0.5: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-endpoints@2.0.5
npm WARN notsup Unsupported engine for @smithy/util-middleware@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-middleware@3.0.3
npm WARN notsup Unsupported engine for @smithy/util-utf8@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-utf8@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-retry@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-retry@3.0.3
npm WARN notsup Unsupported engine for @aws-sdk/util-locate-window@3.568.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/util-locate-window@3.568.0
npm WARN notsup Unsupported engine for @smithy/signature-v4@4.1.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/signature-v4@4.1.0
npm WARN notsup Unsupported engine for @smithy/shared-ini-file-loader@3.1.4: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/shared-ini-file-loader@3.1.4
npm WARN notsup Unsupported engine for @smithy/querystring-parser@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/querystring-parser@3.0.3
npm WARN notsup Unsupported engine for @smithy/service-error-classification@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/service-error-classification@3.0.3
npm WARN notsup Unsupported engine for @smithy/util-stream@3.1.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-stream@3.1.3
npm WARN notsup Unsupported engine for @smithy/util-buffer-from@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-buffer-from@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-hex-encoding@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-hex-encoding@3.0.0
npm WARN notsup Unsupported engine for @smithy/querystring-builder@3.0.3: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/querystring-builder@3.0.3
npm WARN notsup Unsupported engine for @smithy/util-uri-escape@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-uri-escape@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-buffer-from@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-buffer-from@3.0.0
npm WARN notsup Unsupported engine for @smithy/is-array-buffer@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/is-array-buffer@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-buffer-from@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-buffer-from@3.0.0
npm WARN notsup Unsupported engine for @smithy/is-array-buffer@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/is-array-buffer@3.0.0
npm WARN notsup Unsupported engine for @smithy/abort-controller@3.1.1: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/abort-controller@3.1.1
npm WARN notsup Unsupported engine for @smithy/is-array-buffer@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/is-array-buffer@3.0.0
npm WARN notsup Unsupported engine for @smithy/is-array-buffer@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/is-array-buffer@3.0.0
npm WARN notsup Unsupported engine for @aws-sdk/token-providers@3.614.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @aws-sdk/token-providers@3.614.0
npm WARN notsup Unsupported engine for @smithy/util-config-provider@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-config-provider@3.0.0
npm WARN notsup Unsupported engine for @smithy/util-buffer-from@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/util-buffer-from@3.0.0
npm WARN notsup Unsupported engine for @smithy/is-array-buffer@3.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @smithy/is-array-buffer@3.0.0
npm WARN poc_zzz@1.0.0 No description
npm WARN poc_zzz@1.0.0 No repository field.

+ mongoose@6.12.6
added 114 packages from 80 contributors and audited 114 packages in 13.587s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜ ls node_modules/@
@aws-crypto/  @aws-sdk/     @mongodb-js/  @smithy/      @types/  `

**Comment by hunkydoryrepair** [comment]
This must be present so it can connect to dynamodb
What this really means is that mongoose now requires Node 16 or higher

**Comment by erwanriou** [comment]
Ok well i still think that create an non agnostic dependency to a cloud provider (moreover a concurrent of mongodb) a bit strange. It would had been better to have a wrapper for these kind of purposes.

Not sure there is a solution to this and like @hunkydoryrepair said, it's enforce a different node version.

**Comment by vkarpov15** [comment]
Here's a couple of options:

1. `npm install --no-optional` to skip installing optional dependencies
2. Enforce an older version of `@aws-sdk/credential-providers` in your `package.json`, either in `dependencies` or `overrides`:

```
{
  "dependencies": {
    "mongoose": "^6.12.6",
    "@aws-sdk/credential-providers": "3.186.0"
  }
}
```

Unfortunately I don't think the MongoDB driver will accept a patch to remove aws-sdk dependencies, and unfortunately it doesn't look like aws-sdk follows semver because they dropped support for both Node v12 and Node v14 between 3.186.0 and 3.621.0.

**Comment by vkarpov15** [comment]
A little more info here: https://stackoverflow.com/questions/53969343/how-i-can-skip-installing-optional-dependencies-by-npm-ci
