### ISSUE TITLE
incorrect for loop in cast

### ISSUE THREAD

**Issue by 0x0a0d** [Automattic/mongoose#14766]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.x

### Node.js version

x

### MongoDB server version

x

### Description

Please see last comments #14749

### Steps to Reproduce

non

**Comment by vkarpov15** [comment]
@0x0a0d was this fixed with #14749?

**Comment by vkarpov15** [comment]
That comment is pending, so I can't see it on my end. But thanks for the screenshot, that is helpful

**Comment by vkarpov15** [comment]
@0x0a0d you're right, thanks for checking on my changes. I reverted the incorrect changes in https://github.com/Automattic/mongoose/commit/91612bb9657f97e1c981545c2266ebdca57cc751
