### ISSUE TITLE
mongoose.model.ModelName disrupts types

### ISSUE THREAD

**Issue by Arctomachine** [Automattic/mongoose#14767]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.5.1

### Node.js version

20.12.2

### MongoDB version

4.4.5

### Operating system

None

### Issue

Problem: if I include `mongoose.models.User` into export, all types of `User` queries turn into `any`.
If I remove this line and only export model creation, then typescript picks up correct types. But then I get "cannot overwrite once compiled" errors.
I use this because https://stackoverflow.com/questions/19051041/cannot-overwrite-model-once-compiled-mongoose here it is one of suggested solutions, the simplest and it works. But breaks types.
```js
export const User =
	mongoose.models.User || // this line
	mongoose.model(
		'User',
		new mongoose.Schema({
			email: {
				type: String,
				required: true,
				unique: true,
			},
			password: String,
		}),
	)

```

**Comment by windward-hive** [comment]
explicitly type the model `const User: Model<> = ...`

**Comment by Arctomachine** [comment]
Is it `Model<UserType & mongoose.Document>` or just `Model<UserType>`?

**Comment by vkarpov15** [comment]
I'd be curious how you're running into the "cannot overwrite once compiled" error when exporting, can you please provide a script that demonstrates this issue? How are you running your app?

Likely the easiest workaround would be to set the `overwriteModels` option:

```ts
export const User =
	mongoose.model(
		'User',
		new mongoose.Schema({
			email: {
				type: String,
				required: true,
				unique: true,
			},
			password: String,
		}),
                null,
                { overwriteModels: true } // <-- this prevents "cannot overwrite once compiled" errors
	)
```

**Comment by Arctomachine** [comment]
Not sure which of scripts cause it exactly. My project uses nextjs. It happens during reloads after changes. Sometimes everything is fine, sometimes it shows error.

**Comment by vkarpov15** [comment]
Are you able to come up with a script which you can post here that demonstrates the issue you're having?

**Comment by Arctomachine** [comment]
No, sorry. It must be something during sever hot reloads, but cant say anything more precise
