### ISSUE TITLE
Can we include dataloader for .populate method in mongoose, so that this will be efficent while quering

### ISSUE THREAD

**Issue by rdev06** [Automattic/mongoose#14765]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

As of now when we do `.populate()` then if the filter response is having multiple records or any field is having an array then mongoose is quering multiple times to the mongodb database.
This makes huge amount of connection to the database, instead of that if we can use Dataloder to make all queriable items in once and then use `$in` operator.

### Motivation

[https://www.npmjs.com/package/dataloader](loader)

I had used this packages in multiple projects and this increase the performance. May be we can get this option in another method if .`populate` used for backward compability like `.load('friends', 'name, email, age')`...

### Example

Its same like .populate method , just using dataloader for optimisation.
I had also written one such function for my personal project
[https://github.com/rdev06/motu/blob/master/src/MongoLoader.ts](MongoLoader)

**Comment by vkarpov15** [comment]
"filter response is having multiple records or any field is having an array" <-- that sounds incorrect. For example, `Model.find().populate('friends')` will execute one additional query to load `friends` _unless_ you use `perDocumentLimit` or `friends` has an embedded discriminator. "make all queriable items in once and then use $in operator" sounds like exactly what `populate()` already does.
