### ISSUE TITLE
mongoose.connection.db can be undefined, but TypeScript says it can't

### ISSUE THREAD

**Issue by lantw44** [Automattic/mongoose#14789]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.6.13, 8.5.2

### Node.js version

20.12.2

### MongoDB server version

6.0.16

### Typescript version (if applicable)

5.5.4

### Description

```
┌─────────────────────────────────────────────────────────────┐
│(property) Connection.db: mongoose.mongo.Db                  │
│                                                             │
│The mongodb.Db instance, set when the connection is opened   │
└─────────────────────────────────────────────────────────────┘
```
The `db` field is only set after the connection is opened, but TypeScript thinks it can never be undefined.

### Steps to Reproduce

```typescript
import mongoose from 'mongoose';

let db = mongoose.connection.db;
db = undefined;
```
It failed to compile:
```
mongoose-ts.mts:4:1 - error TS2322: Type 'undefined' is not assignable to type 'Db'.

4 db = undefined;
  ~~
```
It also caused code like this to be flagged by TypeScript ESLint @typescript-eslint/no-unnecessary-condition rule:
```typescript
if (mongoose.connection.db == null) {
```

### Expected Behavior

It should compile. `mongoose.connection.db` could be undefined before `mongoose.connect` was called, so TypeScript should not raise a type error here.

**Comment by neilenns** [comment]
This change broke my unit tests :( Probably should have been rolled out in a not dot release since it was a breaking change to the TypeScript definitions.

**Comment by vkarpov15** [comment]
@neilenns what test broke for you?

The line between "bug fix" and "breaking change" can sometimes get a bit blurry. In this case, our TypeScript types did not accurately reflect the runtime behavior, so I think this qualifies as more of a bug fix.

**Comment by neilenns** [comment]
My own unit tests. I had this code:

```typescript
  await mongoose.connect(mongoUri);
  await mongoose.connection.db.dropDatabase();
```

And that started failing. If the goal with mongoose is to follow [semver](https://semver.org/) then IMHO this should have been in a major version since it wasn't backwards compatible with previously written code:

> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes
