### ISSUE TITLE
Connection Error and not getting any data - DEP0170

### ISSUE THREAD

**Issue by hamdiboyaci** [Automattic/mongoose#14792]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.2

### Node.js version

20.16.0

### MongoDB server version

7.0.12

### Description

(node:92732) [DEP0170] DeprecationWarning: The URL mongodb://user:password@bycdigital-shard-00-02.9cgp0.mongodb.net:27017,bycdigital-shard-00-01.9cgp0.mongodb.net:27017,bycdigital-shard-00-00.9cgp0.mongodb.net:27017/?authSource=admin&replicaSet=atlas-9xtpry-shard-0&retryWrites=true&w=majority&appName=BYCDigital&ssl=true is invalid. Future versions of Node.js will throw an error.

### Steps to Reproduce

code (```await mongoose.connect(uri);```) 

### Expected Behavior

How can we solve it?

**Comment by vkarpov15** [comment]
How are you determining that you're running Mongoose 8.5? And, also, are you using any other MongoDB related packages, like connect-mongo or connect-mongodb-session? https://jira.mongodb.org/browse/NODE-5802 indicates this error only occurs on older versions of the MongoDB Node driver (3.x, corresponding to Mongoose 5.x). I also can confirm I get this warning on Mongoose 5.x, but not Mongoose 6.x or higher when running the following script

```javascript
const mongoose = require('mongoose');

mongoose.connect('mongodb://user:password@bycdigital-shard-00-02.9cgp0.mongodb.net:27017,bycdigital-shard-00-01.9cgp0.mongodb.net:27017,bycdigital-shard-00-00.9cgp0.mongodb.net:27017/?authSource=admin&replicaSet=atlas-9xtpry-shard-0&retryWrites=true&w=majority&appName=BYCDigital&ssl=true');
```

Try running `npm list | grep "mongo"` and paste the output here?
