### ISSUE TITLE
Question about .findOne()

### ISSUE THREAD

**Issue by CarlosDev123** [Automattic/mongoose#14805]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.5.3

### Node.js version

20.10.0

### MongoDB version

7.0.12

### Operating system

None

### Issue

With .findOne(), what would happen if many documents meet the filter? Would .findOne() return the newest one? If this is not the case, is there any way of doing it?

**Comment by Ayanabilothman** [comment]
if many documents meet the filter, findOne() will return the first matched document. If you want the newest matched document, use findOne() with sort() method, and sort by createdAt attribute.

for example:
`User.findOne({age:30}).sort({ createdAt: -1 })` 
will return the newest user whose age is 30
