### ISSUE TITLE
Mongoose.prototype.connect() : Discrepancy between changelog and example in document.

### ISSUE THREAD

**Issue by sushil74432** [Automattic/mongoose#14810]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

7.x

### Node.js version

14.x

### MongoDB version

6.x

### Operating system

Linux

### Issue

For Mongoose 7.8.0, the Migration guide says callback support is dropped for "`Mongoose.prototype.connect()`" but the param list and example for this shows callback being used. Please suggest.

MIGRATION GUIDE: 
https://mongoosejs.com/docs/7.x/docs/migrating_to_7.html#dropped-callback-support:~:text=Mongoose.prototype.connect

EXAMPLE: 
https://mongoosejs.com/docs/7.x/docs/api/mongoose.html#Mongoose.prototype.connect()

**Comment by vkarpov15** [comment]
Mongoose dropped callback support for `mongoose.connect()` in Mongoose 7. We will fix our docs to remove the callback-based example in https://mongoosejs.com/docs/7.x/docs/api/mongoose.html#Mongoose.prototype.connect() that you pointed out.
