### ISSUE TITLE
populated sub-documents have same references

### ISSUE THREAD

**Issue by emirhanyagci** [Automattic/mongoose#14816]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.4.3

### Node.js version

20

### MongoDB server version

7.0.12

### Description

I'm facing with issue while using s3 bucket , what is best practice
I was doing chat app this app contain 3 collection Chats,Messages,Users and User
I find messages at group and of possible to same user's message in group in this case when populate like that I'm having trouble getting user avatars signed proccess this is my query.

### Steps to Reproduce

```javascript
 const messages = await Message.find({ chat: chatId })
    .sort({ createdAt: 1 })
    .populate("sender")
    .select("-password")
    .exec();
```
this is what i do . setSignedUrl is my utils its just using getSignedUrl function of `@aws-sdk/s3-request-presigner` packages under the hood . For example we have 2 message from same user then first execute of for both of avatar signed and setted , at second execute this time key broken because we try sign to signed url , and as far as I know, and according to what is written here, it is impossible to tell if the url is signed or not "The pre-signed URL is simply a local calculation and signing of a URL. There is no interaction with the S3 service"

```javascript
  for (let message of messages) {
    message.sender.avatar = await setSignedUrl(message.sender.avatar);
  }
```

after that i did this for temporary solution but this is kind weird not feeling like right solution.
```javascript
 let clonedMessages = JSON.parse(JSON.stringify(messages));

  for (let message of clonedMessages) {
    message.sender.avatar = await setSignedUrl(message.sender.avatar);
  }
```
I think should be some option for this 

### Expected Behavior

checked #3258

**Comment by vkarpov15** [comment]
Yes, there's the `clone` option that was introduced with #3258. For example, the following script demonstrates the issue you're facing, 2 documents end up with `sender.avatar` set to `'avatar1.png?signed=true?signed=true'`

```javascript
const mongoose = require('mongoose');

// MongoDB connection URL
const MONGO_URI = 'mongodb://localhost:27017/mongoose_repro';

// Placeholder function to simulate URL signing
async function signUrl(avatarUrl) {
  // Simulate signing process
  return `${avatarUrl}?signed=true`;
}

const userSchema = new mongoose.Schema({
  username: String,
  avatar: String,
});

const messageSchema = new mongoose.Schema({
  chat: mongoose.Schema.Types.ObjectId,
  sender: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  text: String,
  createdAt: { type: Date, default: Date.now },
});

const User = mongoose.model('User', userSchema);
const Message = mongoose.model('Message', messageSchema);

async function main() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  await User.deleteMany({});
  await Message.deleteMany({});

  // Create sample users and messages
  const user1 = new User({ username: 'user1', avatar: 'avatar1.png' });
  const user2 = new User({ username: 'user2', avatar: 'avatar2.png' });
  await user1.save();
  await user2.save();

  const chatId = new mongoose.Types.ObjectId();
  const messages = [
    new Message({ chat: chatId, sender: user1._id, text: 'Hello from user1' }),
    new Message({ chat: chatId, sender: user1._id, text: 'Another message from user1' }),
    new Message({ chat: chatId, sender: user2._id, text: 'Hello from user2' }),
  ];
  await Message.insertMany(messages);

  // Query and populate
  const populatedMessages = await Message.find({ chat: chatId })
    .sort({ createdAt: 1 })
    .populate('sender')
    .exec();

  // Attempt to sign avatars
  for (let message of populatedMessages) {
    message.sender.avatar = await signUrl(message.sender.avatar);
  }

  console.log('Populated Messages:', populatedMessages);

  // Clean up
  await mongoose.connection.close();
}

main().catch(err => console.error(err));
```

To fix, add the `clone` option to `populate()`:

```javascript
  // Query and populate
  const populatedMessages = await Message.find({ chat: chatId })
    .sort({ createdAt: 1 })
    .populate({ path: 'sender', clone: true }) // <-- add `clone: true` to make Mongoose clone result documents and avoid multiple messages having the same `sender`
    .exec();
```
