### ISSUE TITLE
.populate() clobbers the return type with { [x: string]: NativeDate; }

### ISSUE THREAD

**Issue by smbogan** [Automattic/mongoose#14825]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.3

### Node.js version

22.5.1

### MongoDB server version

5.0

### Typescript version (if applicable)

4.9.5

### Description

The Typescript type for `populate`'s return value:
```Typescript
const result = await SomeModel.findOne().populate<{ otherInfo: string }>("other");
```
includes `MergeType<{ [x: string]: NativeDate; } & ...`.

This causes later code to assume every property is of type `NativeDate`.

This was observed after upgrading from mongoose 6.12.0 to 8.5.3.

### Steps to Reproduce

1. Create any model.
2. Call `findOne`, followed by `populate` with a type parameter.

### Expected Behavior

The types to be properly merged without `{ [x: string]: NativeDate; }` being included.

**Comment by ark23BLR** [comment]
@smbogan Does SomeModel in your example is constructed with `timestamps` schema options?

**Comment by smbogan** [comment]
> @smbogan Does SomeModel in your example is constructed with `timestamps` schema options?

Yes.

```
{
    timestamps: {
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  }
```

**Comment by ark23BLR** [comment]
@smbogan You can try the following?
{
    timestamps: {
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
} as const

**Comment by smbogan** [comment]
Using `as const` did fix the types.

**Comment by ark23CIS** [comment]
@vkarpov15 Created an MR to not confuse users in case if they face the issue
