### ISSUE TITLE
Entire $OR clause dropped in findOne query when any of the keys does not exist in the mongoose schema

### ISSUE THREAD

**Issue by weinis** [Automattic/mongoose#14826]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.13.0

### Node.js version

14.20.1

### MongoDB server version

4.4.18

### Description

Using an $OR clause in a Model.findOne query where one of the keys does not exist in the schema, the mongodb query does not including an $OR clause at all

### Steps to Reproduce

In a schema where the field _processed exists, but the field bob does not exist:

const brokenQuery = await DocModel.findOne({ _id: "001", { $or: [ { _processed: true }, { "bob" : true } ] } }).explain()
console.dir( broken?.queryPlanner?.parsedQuery ?? broken , { depth: 5 } )

{
  _id: { $eq: ObjectId( ... ) }
}

### Expected Behavior

Expect the $or portion of the query to be successfully passed to MongoDB

Expected Example: 
const brokenQuery = await DocModel.findOne({ _id: "001", { $or: [ { _processed: true }, { "bob" : true } ] } }).explain()
console.dir( broken?.queryPlanner?.parsedQuery ?? broken , { depth: 5 } )

{
  '$and' : [
     { _id: [Object] },
     { '$or' : [Array] }
   ]
  
}

**Comment by vkarpov15** [comment]
I'm unable to repro with Mongoose 6.13.0, the following script shows that Mongoose passes the empty `{}` to the MongoDB server in 6.13.0:

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

// Connect to MongoDB
mongoose.connect('mongodb://localhost:27017/mongoose_issue_repro').then(() => {
  console.log('Connected to MongoDB');
}).catch((err) => {
  console.error('Failed to connect to MongoDB:', err);
});

// Define a schema with a single field '_processed'
const docSchema = new mongoose.Schema({
  _processed: Boolean,
});

// Create a model based on the schema
const DocModel = mongoose.model('Doc', docSchema);

(async () => {
  // Demonstrate the issue
  const brokenQuery = await DocModel.findOne({
    $or: [ 
      { _processed: true },
      { "bob": true }  // 'bob' does not exist in the schema
    ] 
  });
  
  // Close the connection to MongoDB
  await mongoose.connection.close();
})();

```

Below is the output:

```
Connected to MongoDB
Mongoose: docs.findOne({ '$or': [ { _processed: true }, {} ] }, {})
```

With https://github.com/Automattic/mongoose/pull/14749, Mongoose actually would strip out the empty `{}`, so the behavior you described will happen in 6.13.1.

What issue is this causing for you?
