### ISSUE TITLE
Mongoose creates duplicate collections when name includes uppercase characters

### ISSUE THREAD

**Issue by jamisonj** [Automattic/mongoose#14823]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.3

### Node.js version

20.16.0

### MongoDB server version

Unsure

### Description

When I attempt to create a collection like so: 

```
const customerLogsSchema = new mongoose.Schema({
    customerId: {
        required: true,
        type: Number
    },
    type: {
        required: true,
        type: String
    },
    text: {
        required: true,
        type: String
    },
    date: {
        required: true,
        type: Date
    }
});
...
const customerLogsModel = mongoose.model('customerLogs', customerLogsSchema);
```

I end up with a `customerLogs` collection (that has my seed data) and a `customerlogs` collection (without seed data) in my database. Using nodemon, every time I refresh my code the bad `customerlogs` one automatically reappears in the database even if I manually deleted it prior.

I saw previously reported issues that claimed that Mongoose is actually _designed_ to create only lowercase collections. If that's really true, I think that's pretty ridiculous (for the record). I spent _two hours_ trying to figure out why my query of the `customerLogs` collection wasn't working and it traced back to this issue.

I've created a new bug for this because the fact that it creates _two_ collections seems to be a different issue than the silly lowercase naming rule.

### Steps to Reproduce

1. Set up a `docker-compose` configuration for mongo.
2. Set up a schema definition like the above.
3. Set up seed data to populate with `docker-entrypoint-initdb.d`.
4. Spin up the container.

### Expected Behavior

One collection is created, with the name `customerLogs`.

**Comment by MohOraby** [comment]
try
```js
const customerLogsModel = mongoose.model('customerLogs', customerLogsSchema, 'customerLogs');
```
first argument is the model name (used for reference and so on)
second argument is the schema
third argument is the collection name

can you confirm 2 collections are being created? and it is not that the camelCase collection already existed. I just tried and only got `customerlogs`

try on a new database with your original code and the snippet above

**Comment by jamisonj** [comment]
@MohOraby That worked! 

```
customer-logging> db.getCollectionNames()
[ 'customerLogs', 'locations', 'customers' ]
```

However, why does it create two different collections (one with and one without camelcase names) when I don't specify the collection name parameter? That seems like buggy behavior.

**Comment by MohOraby** [comment]
@jamisonj 
As I said I tried to reproduce your issue but for me only one collection was created `customerlogs` when I didn't specify a collection name and `customerLogs` when I specified a collection name
if you can share a reproduceable script that would help

**Comment by vkarpov15** [comment]
"However, why does it create two different collections (one with and one without camelcase names) when I don't specify the collection name parameter?" we'll need a repro script to investigate that. Are you using any other packages to help with creating seed data? What does `npm list | grep "mongo"` look like? It could be some other package creating the `customerlogs` collection.
