### ISSUE TITLE
Is there any way to suppress MongoServerError: Collection SOME COLLECTION already exists.

### ISSUE THREAD

**Issue by spaiz** [Automattic/mongoose#14836]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.13.0

### Node.js version

18

### MongoDB version

4.17.2

### Operating system

Linux

### Issue

Hi there. I've been working for a long time with Mongoose, and don't remember these errors in the past to happen in regular mongoose usage.

By regular, I mean, setup connection, setup model, bind model to connection and that's is.

But, I think starting from some update looks like mongoose is ALWAYS trying to create a collection. It knows to handle it, but we catch it in datadog and it creates a lot of noise.

So my question is:

1. Is it by purpose?
2. Is it mongoose behaviour or the MongoDB driver?
3. Is it possible maybe to fix the mongoose so it will check for collection existence instead of trying to create it and handling the exception if it already exists?

Its it so annoying :/

![Screenshot 2024-08-28 at 16 34 27](https://github.com/user-attachments/assets/35494f3e-7d4b-4604-8e62-6010b403df69)

![Screenshot 2024-08-28 at 16 35 49](https://github.com/user-attachments/assets/30b75a4c-585c-45c9-bc09-742310353b0f)

P.S.
People tried to ignore them in datadog but without success.

**Comment by vkarpov15** [comment]
`mongoose.set('autoCreate', false)` should fix this warning. Mongoose does try to automatically create collections by default.
