### ISSUE TITLE
TypeScript returns an error if you run a query on a subclass field of a model

### ISSUE THREAD

**Issue by nikzanda** [Automattic/mongoose#14842]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.0

### Node.js version

20.10.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

5.5.4

### Description

First of all, I find the new feature introduced by the minor release 8.6.0 very useful, which checks if fields exist in the main interface of the model when running queries! It’s a great idea!

However, I encountered a problem with models and subclasses: before 8.6.0, it was possible to run a query on a subclass field from the main model, but now TypeScript reports an error [(solved old issue)](https://github.com/Automattic/mongoose/issues/14664#issue-2348333549).

interfaces:
![image](https://github.com/user-attachments/assets/eaf45b96-f042-49e3-bf86-416464d11c67)
![image](https://github.com/user-attachments/assets/c27bda6d-459a-4b5f-abe0-4c2bce39dd1c)
![image](https://github.com/user-attachments/assets/dad7474b-e2bd-4f04-971f-533fe7ceed74)

query:
<img width="235" alt="Screenshot 2024-08-29 at 11 49 20" src="https://github.com/user-attachments/assets/2fe4870e-b299-461d-9eca-5dab3fe007ba">
<img width="1472" alt="Screenshot 2024-08-29 at 11 49 33" src="https://github.com/user-attachments/assets/6fb8488c-9ba5-4df0-9b15-c00dd1b5b480">

### Steps to Reproduce

Reproduction link: https://stackblitz.com/edit/vitejs-vite-jkwelc?file=src%2Findex.ts

### Expected Behavior

Although the main interface does not include the fields of the subclasses, you should still be able to run a query from the main model, as it worked prior to version 8.6.0.

**Comment by vkarpov15** [comment]
This issue will be fixed by #14874 .

This is another good point for #14874 re: #14764: Mongoose does support automatically inferring discriminator schema if discriminator key is set in the query filter. So if we implement #14764, we would need to come up with a way to support that.

**Comment by vkarpov15** [comment]
Fixed by #14874
