### ISSUE TITLE
Array `addToSet()` and `push()` methods do not work with transaction retries

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#14848]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.0

### Node.js version

20.16.0

### MongoDB server version

5

### Typescript version (if applicable)

N/A

### Description

Hello there,

Scenario:

1. A document has a subdocument array.
2. The array is modified via `push()`.
3. The document is `save()`d inside a transaction.
4. The transaction is retried (the whole transaction as opposed to just the commit).

Result: duplicate entries are saved. Actually, this is exactly the same as in #14340 - the total number of documents added to the array grows exponentially with every retry - it is 2^n, where n is the number of retries.

I chose not to reopen the old issue because I have a hunch that this time the cause might be different.

There is also a closely-related problem when using `addToSet()`. Other array methods (`pop()`, `pull()`, `remove()`, `set()`, `shift()` and even `splice()`) all seem to be working correctly.

### My analysis

Let's take this for example (you'll find the full script below):

```typescript
doc.items.push({ name: "test3" });

await mongoose.connection.transaction(async (session) => {
  console.log(`Attempt: ${attempt}`);
  await doc.save({ session });
});
```

The first attempt to `save()` generates the following `updateOne` query:

```json
{"$push":{"items":{"$each":[{"name":"test3"}]}},"$inc":{"__v":1}}
```

If the transaction is retried, the second attempt to `save()` generates this `updateOne` query:

```json
{"$set":{"__v":1},"$push":{"items":{"$each":[{"name":"test3"},{"name":"test3"}]}}}
```

Attempt 3:

```json
{"$set":{"__v":1},"$push":{"items":{"$each":[{"name":"test3"},{"name":"test3"},{"name":"test3"},{"name":"test3"}]}}}
```

Etc. - as you can see, with each attempt the number of elements in `$push.items.$each` doubles.

A side-effect of this problem is that the update query can grow significantly in size. If it grows too large, it might fail with one of these errors:

```
RangeError: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825793

MongoServerError: BSONObj size: 16928643 (0x1024F83) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "mymodels"
```

As a matter of fact, this was the first problem that I ran into since I noticed that saving after `addToSet()` was _sometimes_ failing. Now I know that _sometimes_ was when a transaction was retried a lot.

### Steps to Reproduce

```typescript
import mongoose from "mongoose";
import { MongoServerError, MongoErrorLabel } from "mongodb";

console.log("connecting...");

// Connecting to a *ReplicaSet* specifically to make sure that transactions work correctly.
// Nevertheless, whether or not an actual ReplicaSet is used has no effect on the issue.
await mongoose.connect(
  "mongodb://mongo-node1:27017,mongo-node2:27018,mongo-node3:27019/xxx?replicaSet=eof"
);

console.log("connected!");

// Define some schemas...
const subItemSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
  },
  { _id: false }
);

const itemSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    subItems: { type: [subItemSchema], required: true },
  },
  { _id: false }
);

const schema = new mongoose.Schema({
  items: { type: [itemSchema], required: true },
});

// ...and a model
const Model = mongoose.model("MyModel", schema);

// Clear the collection...
await Model.deleteMany({});

// ...and create one document
await Model.create({
  items: [
    { name: "test1", subItems: [{ name: "x1" }] },
    { name: "test2", subItems: [{ name: "x2" }] },
  ],
});

const doc = await Model.findOne();

doc.items.addToSet({ name: "test3", subItems: [{ name: "x3" }] });

let attempt = 0;

// Controls the number of retries.
// 17 works, 18 fails
let retries = 18;

await mongoose.connection.transaction(async (session) => {
  console.log(`Attempt: ${attempt}`);

  await doc.save({ session });

  if (attempt < retries) {
    attempt += 1;
    throw new MongoServerError({
      message: "Test transient transaction failures & retries",
      errorLabels: [MongoErrorLabel.TransientTransactionError],
    });
  }
});

await mongoose.disconnect();
```

**Comment by juona** [comment]
A temporary workaround until this is fixed:

```typescript
await mongoose.connection.transaction(async (session) => {
  console.log(`Attempt: ${attempt}`);

  // This! Apparently this resets something inside the Document so that
  // `save()` works correctly for this field. Of course, if there are multiple
  // fields that are being modified in this way, they would all have to be
  / "reset" like this individually.
  doc.items = doc.items;

  await doc.save({ session });

  if (attempt < retries) {
    attempt += 1;
    throw new MongoServerError({
      message: "Test transient transaction failures & retries",
      errorLabels: [MongoErrorLabel.TransientTransactionError],
    });
  }
});

**Comment by juona** [comment]
Correction - it looks like `.pull()` is affected somehow too, albeit in a slightly different way. I need more retries (like 30) and the error is then:

```
MongoServerError: assertion src/mongo/bson/bsonelement.cpp
```

It does not say anything else. Since I am in a bit of hurry, I did not dig in and just used the workaround above.

**Comment by dmint789** [comment]
I'm getting an issue when using .push() and then .save() in general, and it just started happening after a recent update (I'm on version 8.5.5, because versions 8.6.0 and 8.6.1 are giving me bugs when I try to filter by createdAt, which was working just fine before.)

**Comment by dmint789** [comment]
Actually, I just tried it with 8.6.1 and it still doesn't work. When I use `.push(await schema.create())` on a document array of refs, it does create the new document, but it doesn't store it in the array as a ref, but rather as a pure object with all of the fields, including internal fields like `createdAt` and `updatedAt`.

**Comment by juona** [comment]
@dmint789 I believe that's a separate issue. What I am seeing relates specifically to transaction retries.

**Comment by vkarpov15** [comment]
@dmint789 can you please open a new issue and follow the issue template? It's hard to guess what the issue might be without code samples.
