### ISSUE TITLE
syncIndex option to hide instead of drop index

### ISSUE THREAD

**Issue by vvandens** [Automattic/mongoose#14868]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I love the syncIndex() feature that helps to have a single source of truth for our MondoDB schema indexing.

However, dropping an index is never 100% sure, especially on large MongoDB databases with large codebase querying the collections. There can be some rarely used piece of code that need once a time an index and thus will not update the $indexStats frequently enough to identify that this index is actually needed.

One recommandation from the MongoDB team is to **hide** an index before actually dropping it. It will exclude the index from the query planner options and whenever you identify a performance issue due to this exclusion, you can instantly make it visible again. This is way faster and less resource consuming than re-creating the index from scratch. The latter can last for hours on large collections and your system suffers during this re-creation.

It would be nice to pass an option to the syncIndex(**{hide: true}**) to hide the indexes missing in the schema instead of dropping them immediately. Once the system has run for a certain period of time without problem, then we can call the syncIndex({hide:false}) to actually drop them.

### Motivation

Secure the synchronization of the indexes and prevent mis-dropping of rarely used indexes with immediate rollback if necessary.

### Example

```javascript
model.syncIndex({hide: true}); // hide missing schema indexes instead of dropping them
model.syncIndex(); // actually drop missing schema indexes. Same as {hide:false}
```

**Comment by vvandens** [comment]
Just found out that there is no such hideIndex() method on the native MongoDB driver but here is a [SO post](https://stackoverflow.com/a/72016129/4366827) that describes an elegant solution to mimic what mongosh does with hideIndex().

**Comment by vkarpov15** [comment]
We will consider this for a future release, this is a neat feature idea, but would be tricky for us to implement until the MongoDB Node driver supports `hideIndex()`

**Comment by vvandens** [comment]
Thanks @vkarpov15 for considering this evolution.
Whenever you would like to anticipate the `hideIndex()` inclusion in MongoDB node driver, the following code snippet extracted from the SO post linked above works like a charm (with Mongoose `connection` and `model`):

```javascript
connection.db.command({
  'collMod': model.collection.name,
  index: { name: indexName, hidden: true }
})
```
