### ISSUE TITLE
_id no longer seems to be recursively included when bundled with webpack

### ISSUE THREAD

**Issue by gl-aagostino** [Automattic/mongoose#14867]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.0

### Node.js version

20.x

### MongoDB server version

6.8.0

### Typescript version (if applicable)

5.5.4

### Description

We recently updated both mongodb and mongoose packages, from 4x to 6x and 6x to 8x respectively. After ironing out all the breaking changes, our CI started failing in a perplexing way. When we run our application locally with tsnode, all things work as expected. However when we build for production we bundle all packages (except mongodb for reasons) with webpack, we now have a very reproducible and strange, application breaking behaviour. 

As you would know `_id` is recursive in mongoose, eg `_id._id._id`... Sometimes our devs have used this recursive `_id` by accident, for whatever reason, and it has never been a problem. However, now we have test failures/application failures because it seems when we bundle mongoose with webpack we lose that recursive `_id`. 

I painfully verified this by reverting to the old packages listed previously and verified `_id` was always recursive, even when bundled with webpack. However, in these new versions (webpack version unchanged) we definitely have lost the recursiveness of `_id`.

Here is a screenshot for some proof (I'm also seeing generation time is missing - it looks almost like the second ObjectId is not mongoose's version at all)

![image](https://github.com/user-attachments/assets/c01792c8-d432-4f8d-8573-d7e685fb66cc)

So my question is; is this a bug, a breaking change, or some other issue entirely, maybe with webpack? I still see this code in both package versions in both production bundles

```ts
Object.defineProperty(ObjectId.prototype, '_id', {
  enumerable: false,
  configurable: true,
  get: function() {
    return this;
  }
});
```

so its not like that got built-out. 

Any ideas?

---

Update: in our webpack config we have the ability to exclude some packages from the bundle, so I decided to add mongoose and voila, we are back in business. This is definitely some new behaviour with the newer versions of this package and webpack @ 5.92.1

### Steps to Reproduce

Old behaviour
1. Install `mongodb` `4.2.2` and `mongoose` @ `6.1.4`
2. Bundle application with webpack
3. Verify `_id` is recursive when retrieving documents, etc

New behaviour
1. Install `mongodb` `6.8.0` and `mongoose` @ `8.6.0`
2. Bundle application with webpack
3. Verify `_id` is **no **longer** recursive when retrieving documents, etc

### Expected Behavior

`_id` is recursive

**Comment by vkarpov15** [comment]
Can you verify whether your code sets the `objectIdGetter` option, like `mongoose.set('objectIdGetter', false)`? That is the option that's responsible for the recursive `_id` behavior you mentioned. Before we try to repro, it would be great to confirm that you aren't setting that option anywhere.

**Comment by gl-aagostino** [comment]
@vkarpov15 thanks for your response - we do not have that in our codebase, but your idea has led us on some kind of chase. Fingers point towards either a turbo cache or webpack issue, but neither make sense. It doesn't look like we've ever used anything less than mongoose @ 5.x where it seems this was introduced, yet somehow our build in particular for CI has 0 code referencing `objectIdGetter` but our production builds do have it! It's like some strange version of mongoose is being bundled. Still looking in to it, but likely our own problem. Will update again when we truly figure it out.

**Comment by vkarpov15** [comment]
Thanks for checking, let me know what you figure out :+1:
