### ISSUE TITLE
Mongoose aws4 wrong service account

### ISSUE THREAD

**Issue by pedrooct** [Automattic/mongoose#14871]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.2.0

### Node.js version

18.18.0

### MongoDB version

 6.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

alpine3.18

### Issue

HI!

I'm trying to connect to mongoatlas using ?authMechanism=MONGODB-AWS and with a service account isra defined.
However eks default service account is being used resulting is the following error.

MongoServerError: Could not find user "arn:aws:sts::XXXXX for 'db $external'

Any ideas?

Versions:
"aws4": "1.13.2"
"mongoose": "8.2.0",

Thank you

**Comment by vkarpov15** [comment]
Are you able to connect using the mongodb node driver?
