### ISSUE TITLE
CastError Not Thrown When Saving Document with Invalid Value type

### ISSUE THREAD

**Issue by ayoubkhial** [Automattic/mongoose#14896]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.2

### Node.js version

20.16.0

### MongoDB server version

7.0.12

### Typescript version (if applicable)

5.5.4

### Description

I encountered a bug where Mongoose throws a `ValidationError` instead of a `CastError` when saving a document with an invalid value for a specific type. The error instance is a `ValidationError`, even though the error message indicates a casting failure. This behavior prevents us from catching the error as a `CastError` for more precise error handling.

### Steps to Reproduce

**Define the Schema**

```ts
import { Schema, Prop, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema()
export class User extends Document {
  @Prop({ required: true, unique: true })
  username!: string;

  @Prop({ default: false })
  isActive?: boolean;
}

export const UserSchema = SchemaFactory.createForClass(User);
````

**Attempt to Save a Document with an Invalid Boolean Value**
```
try {
  const user = new User({
    username: 'john',
    isActive: 'test', // Invalid Boolean value
  });
  await user.save();
} catch (error) {
  if (error instanceof mongoose.Error.ValidationError) {
    console.log('Validation Error'); // ☜ this get logged
  }
  if (error instanceof mongoose.Error.CastError) {
    console.log('Cast Error');
  }
}
```

**Observe the Error Output**

The error message details a casting failure:
```
Cast to Boolean failed for value "test" (type string) at path "isActive" because of "CastError"
```

### Expected Behavior

**Error Type**: A `CastError` should be thrown directly when a value cannot be cast to the expected data type, in this case, a Boolean.

**Consistency**: The error instance should match the nature of the error message, which indicates a casting issue.

**Comment by vkarpov15** [comment]
This is currently expected behavior. A Mongoose `ValidationError` is an aggregate of one or more errors, it has an `errors` property which contains which errors occurred on a particular path. A `CastError` is scoped to a single path, so it will only say "path `isActive` didn't cast successfully".

A `save()` (`validate()` under the hood) call throws a `ValidationError` because there can be multiple `ValidatorError` and `CastError` errors when trying to validate a particular document.

If you want to do something special if there's at least one CastError, you can do something like `if (Object.keys(error.errors).find(err => err instanceof mongoose.Error.CastError)) { /* ... */ }`

**Comment by ayoubkhial** [comment]
> This is currently expected behavior. A Mongoose `ValidationError` is an aggregate of one or more errors, it has an `errors` property which contains which errors occurred on a particular path. A `CastError` is scoped to a single path, so it will only say "path `isActive` didn't cast successfully".
> 
> A `save()` (`validate()` under the hood) call throws a `ValidationError` because there can be multiple `ValidatorError` and `CastError` errors when trying to validate a particular document.
> 
> If you want to do something special if there's at least one CastError, you can do something like `if (Object.keys(error.errors).find(err => err instanceof mongoose.Error.CastError)) { /* ... */ }`

Thank you @vkarpov15, it's actually `Object.values(error.errors)` instead of `Object.keys(error.errors)`

**Comment by vkarpov15** [comment]
Good point, fixed :+1:
