### ISSUE TITLE
Using spread operator on a SubDocument does not give the original object that mongoose is wrapping

### ISSUE THREAD

**Issue by tonivuc** [Automattic/mongoose#14912]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.6.3

### Node.js version

20.14.0

### MongoDB server version

6.8.0

### Typescript version (if applicable)

5.6.2

### Description

When using the spread operator on a SingleNested Document (a SubDocument) I get:

```
{
 _doc: {
  firstName: 'John',
  lastName: 'Doe'
}
 $__ : ...
 $__parent : ...
 $isNew = false
}
```

But the actual properties of the object Mongoose is wrapping aren't there (unless I look inside _doc)

However, if I do the spread operator on a nested document (Document) I get the original properties of the document.
And by original properties I mean for example this, and none of the Mongoose properties:

```
{ 
 firstName: 'John',
 lastName: 'Doe'
}
```

### Steps to Reproduce

Create two schemas

```
const profileSchemaNestedDoc = {
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
};

const userSchemaNestedDoc = new mongoose.Schema<any>({
    user: {
        profile: profileSchemaNestedDoc,
    },
});

const profileSchemaSubDoc = new mongoose.Schema<any>({
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
});

const userSchemaSubDoc = new mongoose.Schema<any>({
    user: {
        profile: { type: profileSchemaSubDoc },
    },
});
```

Create Document instances of these two, such as userWithSubDoc and userWithNestedDoc with the properties set. Then run 
```
const userWSubDoc = { ...userWithSubDoc };
const userWNestedDoc = { ...userWithSubDoc };
```

Then using a debug tool examine the constants to see what the live objects look like.

You should see that the output of the spread operation is quite different and as described in this issue description.

### Expected Behavior

I would expect the spread operator to work the same way on a Document instance and a SingleNested instance ☺️ And at least give me the properties of the object that Mongoose is wrapping.

**Comment by vkarpov15** [comment]
This is expected behavior, there's unfortunately no good way for spread operator to return a document's properties with the way that Mongoose is currently architected. You should use `{ ...userWithSubDoc.toObject() }`, or just `userWithSubDoc.toObject()`.

This may change in the future if we make documents use proxies, but that is a major change and currently not planned.

**Comment by tonivuc** [comment]
Thanks for the reply @vkarpov15! But it works to use the spread operator for Document...? (nested schema). In the VSCode debug tool it says it is a Document.
It's the inconsistency that I find a bit problematic, and I don't think you addressed it in your comment?

This is our actual runtime objects from the two approaches
SubDocument/SingleNested:
<img width="302" alt="image" src="https://github.com/user-attachments/assets/df945bd1-789e-4b6a-b773-ae31ecce8d72">

Nested schema (Document):
<img width="228" alt="image" src="https://github.com/user-attachments/assets/03f1f3dd-a2e0-4db3-9295-41c8d0f4a525">

**Comment by vkarpov15** [comment]
Nested paths and subdocuments are different, there's several behavior differences between the two. Spread operator handling is one of them. [There's some more info on the difference in our docs](https://mongoosejs.com/docs/subdocs.html#subdocuments-versus-nested-paths).

It is slightly strange that a nested path shows up as a "Document", we'll look into that

**Comment by vkarpov15** [comment]
On further inspection, it is expected that a nested path shows up as a Document. [Here's the code that creates the runtime value of a nested path](https://github.com/Automattic/mongoose/blob/10a3aeda6bfb15f04fc2dd5698826a80005460da/lib/helpers/document/compile.js#L85).

Long story short, subdocuments and nested paths are different as described in the docs: https://mongoosejs.com/docs/subdocs.html#subdocuments-versus-nested-paths. However, neither subdocuments nor nested paths behave as expected with the spread operator. Use `toObject()` instead.
