### ISSUE TITLE
connecting to MongoDB Atlas,

### ISSUE THREAD

**Issue by Joshua-alt** [Automattic/mongoose#14917]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8

### Node.js version

18.14.1

### MongoDB server version

MongoDB Atlas

### Description

I’m encountering a problem connecting to MongoDB Atlas, even though I’ve allowed network access for everyone by adding ‘0.0.0.0/0’ to the IP whitelist using  mongoose v8

### Steps to Reproduce

to get issue that i show in description  can be done by install mongoose 8v  then connect  it with mongodb atlas 
and to fixe required to back on "mongoose": "^7.3.2" version that for me is working fine

### Expected Behavior

I’m encountering a problem connecting to MongoDB Atlas, even though I’ve allowed network access for everyone by adding ‘0.0.0.0/0’ to the IP whitelist. When attempting to connect, I consistently receive the following error message: ‘MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you’re trying to access the database from an IP that isn’t whitelisted. Make sure your current IP address is on your Atlas cluster’s IP whitelist

**Comment by akang** [comment]
I am facing the same issue.

For me:

Breaks on version 8.7.0
Works on 8.5.2

**Comment by vkarpov15** [comment]
What version of the MongoDB server are you running in Atlas?

**Comment by akang** [comment]
@vkarpov15 

7.0.12

**Comment by mtrplx** [comment]
7.0.14

**Comment by kumarchetan-1** [comment]
Yes, "mongoose": "^7.0.12" is working for me.
Thank you @akang!

**Comment by vkarpov15** [comment]
A couple of potential suggestions:

1. Does your database username or password contain special characters that would be encoded by `encodeURIComponent()`? 
2. Are you able to connect using the [mongodb node driver](https://npmjs.com/package/mongodb)?
3. What is the output of `err.reason` where `err` is the `MongooseServerSelectionError`?

**Comment by lukas-becker0** [comment]
We have no issues with mongoose 8.6.4 and mongodb 7.0.12 on mongodb atlas.

**Comment by angelosnm** [comment]
Same behaviour here....mongoose 8.7.0 and mongodb atlas 8.0.0

**Comment by bmortella** [comment]
Same!

**Comment by lukas-becker0** [comment]
Strange we also use Atlas 7.0.14 now and mongoose 8.6.4 without this connection issue.

How do you guys connect to the server ?


`mongodb+srv://DB-USER:PASSWORD@ATLAS-INSTANCE-NAME.dyvqc.mongodb.net/?retryWrites=true&w=majority`

`serverSelectionTimeoutMS` is set to 5000 ms

And the DB name is not included in the URL option, it i passed separately though the mongoose dbName option.

**Comment by lukas-becker0** [comment]
We only use linux and macOS maybe this is a windows issue ?

**Comment by angelosnm** [comment]
> We only use linux and macOS maybe this is a windows issue ?

Nope. I came with this issue on deployment, obviously on linux server.

**Comment by vkarpov15** [comment]
I tried with a separate `dbName` option and no dbname in the connection string, I'm still able to connect successfully to Atlas with Mongoose 8.7. @angelosnm are you able to provide any additional information?

**Comment by angelosnm** [comment]
> I tried with a separate `dbName` option and no dbname in the connection string, I'm still able to connect successfully to Atlas with Mongoose 8.7. [@angelosnm](https://github.com/angelosnm) are you able to provide any additional information?

I still had issues. What fixed it was downgrading package version.

**Comment by chibuzodaniel** [comment]
been battling the same Issue. Downgrading the Mongoose package version fixed it @angelosnm

**Comment by sdbzdg** [comment]
I also allowed access from anywhere (http://0.0.0.0/0 (includes your current IP address))

Atlas version:
8.0.3
Previous Mongoose version:
8.8.1

Downgrading to 8.6.1 or 8.5.2 as suggested did NOT work for me.
**Downgrading to 7.3.2 fixed the issue.**

Did not have any issues for months until today (MongooseServerSelectionError with ReplicaSetNoPrimary error).

**Comment by vkarpov15** [comment]
I'm going to close this issue, recent comments are unhelpful.

If you're experiencing a similar issue, please open a new issue and follow the issue template. Also please include the output of `err.reason.servers.values().next()`.
