### ISSUE TITLE
Why does mongoose not export the `DeleteResult` type

### ISSUE THREAD

**Issue by chtpl** [Automattic/mongoose#14946]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

8.5.2

### Node.js version

22.x

### MongoDB version

6.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Issue

I am implementing a database `deleteMany` query in a NestJS repository class
I prefer declaring the return types explicitly on my methods
However when I defined `Promise<DeleteResult>` as return type for my method, I cannot find an exported member `DeleteResult` to import to my repository class file.
However, type inference shows that `model.deleteMany({}).exec()` returns that type from mongoose.

I wonder why this is the case as I can perfectly import `UpdateWriteOpResult` to check the updated documents count on update queries

**Comment by vkarpov15** [comment]
You should be able to do `import { DeleteResult } from 'mongodb'` as a workaround, but you're right that Mongoose should export DeleteResult.
