### ISSUE TITLE
Type error using findOne with lean function

### ISSUE THREAD

**Issue by nocodehummel** [Automattic/mongoose#14942]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.5.5

### Node.js version

20.18.0

### MongoDB server version

7

### Typescript version (if applicable)

5.6.2

### Description

The lean function does not return the expected object type. The below code is working with Mongoose 8.5.2, but failed with a type error after upgrading to 8..5.5.  

```
aliasSchema.statics.findByAlias = async function (alias: string, ref: ModelNames): Promise<AliasType | null> {
    const regex = new RegExp(alias);
    return await this.findOne({ alias: { $regex: regex, $options: 'i' }, ref }).lean();
};
```

The returned type is `Type '(FlattenMaps<any> & Required<{ _id: unknown; }>)[] | (FlattenMaps<any> & Required<{ _id: unknown; }>) | null'` and does not include the specified type *AliasType*.

### Steps to Reproduce

The type error occurs during compilation.

### Expected Behavior

The lean funcrtion to return the object type as specified in the model.

**Comment by vkarpov15** [comment]
We are investigating the root cause. But as a workaround for now, you can do the following

```ts
aliasSchema.statics.findByAlias = async function (
  alias: string,
  ref: string
): Promise<AliasType | null> {
  const regex = new RegExp(alias, 'i');
  // TypeScript expects the return type to be AliasType | null
  // but the lean() function returns a different type
  return await this.findOne({ alias: { $regex: regex }, ref }).lean<AliasType>(); // <-- add lean type override
};

```

**Comment by vkarpov15** [comment]
I'm not sure what happened, but I am no longer able to repro this issue. The following script compiles without error on Mongoose 8.7.2, can you please try out the following script and see if it fails for you?

```ts
import mongoose, { Document, Model, Schema } from 'mongoose';
  
// Define the AliasType interface
interface AliasType {
  alias: string;
  ref: string;
}

// Define a schema for the Alias model
const aliasSchema = new Schema<AliasType, AliasModel>({
  alias: { type: String, required: true },
  ref: { type: String, required: true }
});

// Define a static method for finding an alias by regex
aliasSchema.statics.findByAlias = async function (
  alias: string,
  ref: string
): Promise<AliasType | null> {
  const regex = new RegExp(alias, 'i');
  // TypeScript expects the return type to be AliasType | null
  // but the lean() function returns a different type
  return await this.findOne({ alias: { $regex: regex }, ref }).lean();
};

interface AliasModel extends Model<AliasType> {
  findByAlias(alias: string, ref: string): Promise<AliasType | null>;
}

// Create the model
const Alias = mongoose.model<AliasType, AliasModel>('Alias', aliasSchema);

// Example usage (for testing)
async function test() {
  const aliasDoc = await Alias.findByAlias('exampleAlias', 'exampleRef');
  console.log(aliasDoc);
}

test().catch(console.error);
```

**Comment by nocodehummel** [comment]
The issue was caused by the interface AliasModel type specification. This was not a Mongoose issue.
