### ISSUE TITLE
mongoose.transaction never resolves

### ISSUE THREAD

**Issue by VladimirMikulic** [Automattic/mongoose#14964]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.7.1

### Node.js version

20

### MongoDB server version

6

### Description

So as the name suggests `await mongoose.transaction` never resolves and callback never gets executed either.
I'm using basically the same logic as from the offical docs (below) but just differently named model. That's all.

![Image](https://github.com/user-attachments/assets/605179ee-9361-44d0-a545-01a545f86346)

### Steps to Reproduce

Copy documentation code above locally and try `await mongoose.transaction`.

**Comment by vkarpov15** [comment]
Try `mongoose.connection.transaction()`. [transaction() is a method on Mongoose connections](https://mongoosejs.com/docs/api/connection.html#Connection.prototype.transaction()), not the Mongoose global.

**Comment by VladimirMikulic** [comment]
Ah, that makes sense. Appreciate fast reply @vkarpov15.
