### ISSUE TITLE
(Document DB) --> MongoServerError: Unsupported mechanism [ -301 ]

### ISSUE THREAD

**Issue by Ditxit** [Automattic/mongoose#15018]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.0

### Node.js version

20

### MongoDB server version

Document DB

### Description

While connecting to `Document DB` using the following code in Node Js

```
const mongoose = require('mongoose');

mongoose.connect('<document-database-url>', {
    tlsCAFile: '<tls-ca-file-path>',
    serverSelectionTimeoutMS: 60000
});
```

My Database URL is like this;
```
mongodb://<username>:<password>@dummy-document-db.cluster-dummy.ap-southeast-2.docdb.amazonaws.com:27017/dummy-db-name?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
```

**ERROR**: I am getting an connection establishment error

```
06:06:50 0|app  | 2024-11-04T06:06:50: info: ::ffff:XX.XXX.X.X - GET / 200 - 0.235 ms
06:06:46 0|app  |     at async connect (/usr/src/app/node_modules/mongodb/lib/cmap/connect.js:24:9)
06:06:46 0|app  |     at async performInitialHandshake (/usr/src/app/node_modules/mongodb/lib/cmap/connect.js:104:13)
06:06:46 0|app  |     at async ScramSHA256.auth (/usr/src/app/node_modules/mongodb/lib/cmap/auth/scram.js:39:16)
06:06:46 0|app  |     at async executeScram (/usr/src/app/node_modules/mongodb/lib/cmap/auth/scram.js:79:22)
06:06:46 0|app  |     at async Connection.command (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:317:26)
06:06:46 0|app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
06:06:46 0|app  |     at Connection.sendCommand (/usr/src/app/node_modules/mongodb/lib/cmap/connection.js:290:27)
06:06:46 0|app  | 2024-11-04T06:06:46: error: MongoServerError: Unsupported mechanism [ -301 ]
```

PS: It works with `mongoos v8.7.0` though.

### Steps to Reproduce

As I mentioned above in the description.

**Comment by darkmavis1980** [comment]
I have the same issue, everything work until version `8.7.3` but now I get a connection error with `8.8.x`, I tried to check what authentication mechanisms are supported for DocumentDB, but it doesn't seem to be much about it.
They mention a `MONGODB-AWS` string in [this article](https://docs.aws.amazon.com/documentdb/latest/developerguide/iam-identity-auth.html) but it's only if you use IAM as authentication, which is not our case I believe.

**Comment by darkmavis1980** [comment]
Actually I found a solution, I changed the `authMechanism` to be `SCRAM-SHA-1`, which is a bit of a downgrade from SHA256 as SHA1 is more vulnerable (hence why MongoDB is pushing for a more secure algorithm I believe), but in my case by setting that value it worked for me with mongoose `8.8.x`.
I hope it helps

**Comment by VaughanHarv** [comment]
> Actually I found a solution, I changed the `authMechanism` to be `SCRAM-SHA-1`, which is a bit of a downgrade from SHA256 as SHA1 is more vulnerable (hence why MongoDB is pushing for a more secure algorithm I believe), but in my case by setting that value it worked for me with mongoose `8.8.x`. I hope it helps

I also faced this issue and used this to resolve it.My guess is that the DEFAULT behaviour changed and it no longer checks each default option before throwing an error. 
I couldn't see anything in the change notes to indicate a difference in priority for the default behaviour, however, i could see in the logs it never attempted any other auth mechanisms other than SHA256.

**Comment by hdodov** [comment]
I'm just going to paste the exact error, so that search engines can pick it up and show this issue to other people:

```
[19:04:40] ERROR: Error: cannot connect to MongoDB. Details: Unsupported mechanism [ -301 ]
    err: {
      "type": "s",
      "message": "Unsupported mechanism [ -301 ]",
      "stack":
          MongoServerError: Unsupported mechanism [ -301 ]
              at S.sendCommand (/app/.next/server/chunks/7319.js:181:64438)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async S.command (/app/.next/server/chunks/7319.js:181:65057)
              at async m (/app/.next/server/chunks/7319.js:181:37048)
              at async k.auth (/app/.next/server/chunks/7319.js:181:36250)
              at async g (/app/.next/server/chunks/7319.js:181:54961)
              at async f (/app/.next/server/chunks/7319.js:181:52995)
      "errorResponse": {
        "ok": 0,
        "code": -301,
        "supportedMechanisms": [
          "SCRAM-SHA-1",
          "MONGODB-AWS"
        ],
        "errmsg": "Unsupported mechanism [ -301 ]",
        "operationTime": {
          "$timestamp": "7442037065258106881"
        }
      },
      "ok": 0,
      "code": -301,
      "supportedMechanisms": [
        "SCRAM-SHA-1",
        "MONGODB-AWS"
      ],
      "operationTime": {
        "$timestamp": "7442037065258106881"
      },
      "connectionGeneration": 0
    }
   ▲ Next.js 15.0.3
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 599ms
```

In my case, the fix was to simply add `&authMechanism=SCRAM-SHA-1` at the end of my connection string.
