### ISSUE TITLE
Mongodb 8 new bulkwrite for multiple collections

### ISSUE THREAD

**Issue by mete89** [Automattic/mongoose#15028]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

8.8.1

### Node.js version

20

### MongoDB version

8

### Operating system

Linux

### Issue

Is there any example on how to use new bulkWrite which works on multiple collections? https://www.mongodb.com/docs/manual/reference/command/bulkWrite/#mongodb-dbcommand-dbcmd.bulkWrite

**Comment by vkarpov15** [comment]
We don't currently have support for that, nor for [db.aggregate](https://www.mongodb.com/docs/manual/reference/method/db.aggregate/). We need to add that.
