### ISSUE TITLE
Schema.clone() not making a deepclone of Schema.obj - intended or bug?

### ISSUE THREAD

**Issue by tomatemeo** [Automattic/mongoose#15037]
### Prerequisites

- [x] I have written a descriptive issue title

### Mongoose version

7.8.2

### Node.js version

20.x

### MongoDB version

6.10

### Operating system

macOS

### Issue

I ran into problems when testing some utility functions, when I noticed the culprit was that .clone() on a Schema does not deep clone the .obj. Hence if:

```
original = new Schema(...), 
a = original.clone() 
b = original.clone()

a.remove(...)
a.add(...)

b.obj will have changed
```

This is also in the current source code (schema.js, line 407 `s.obj = this.obj`), is this intentional for some reason? If so I would be interested why, if not I would report it as a bug, as I think it is not expected behaviour.

Thanks for the great project and best wishes

**Comment by vkarpov15** [comment]
This is expected behavior, because the docs indicate that `obj` is "the original object passed to the Schema constructor" here: https://mongoosejs.com/docs/api/schema.html#Schema.prototype.obj.

The following script shows that `obj` does **not** change if you `add()` or `remove()` from your schema

```javascript
const mongoose = require('mongoose');

// Define a base schema
const baseSchema = new mongoose.Schema({
  name: { type: String, required: true },
});
const clone = baseSchema.clone();

// Log the initial schema structure
console.log('Initial Schema:', baseSchema.obj);

// Dynamically add fields to the schema
baseSchema.add({
  age: { type: Number, required: false },
  address: { type: String, required: false },
});

// Log the updated schema structure
console.log('Schema after adding fields:', baseSchema.obj);
console.log('Cloned schema after adding fields:', clone.obj);

// Dynamically remove a field from the schema
baseSchema.remove('address');

// Log the schema structure after removal
console.log('Schema after removing "address":', baseSchema.obj);
console.log('Cloned schema after removing "address":', clone.obj);

```

We generally recommend using `Schema.prototype.eachPath()` if you want to loop over schema properties, but you can also use `Schema.prototype.tree`.

**Comment by tomatemeo** [comment]
Thanks a lot for your reply @vkarpov15
Yes, you are right, it says in the docs, I just thought after .clone() this would be a copy, not a direct reference to the original object. Your example is also right of course, I should have updated the issue, but guess I didn't want to because that would have changed the topic.
I am still intrigued by the behaviour of the .add(x) though (the second example) as the settings for x get lost (and the original ones used) when adding a schema to an other one.

Never mind, thanks for taking the time!
