### ISSUE TITLE
Cast array filters with embedded discriminators in arrays doesn't work

### ISSUE THREAD

**Issue by jeffersonlipsky** [Automattic/mongoose#15053]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.0

### Node.js version

18.0

### MongoDB server version

8.0

### Typescript version (if applicable)

5.4.3

### Description

When I made an update with arrayFilters in a schema with an embedded discriminators property the method castArrayFilters didn't know the discriminated properties. So Mongoose throws an error "Could not find path "pathDiscriminated" in schema"

### Steps to Reproduce

So, You made an update with arrayFilters like the following:
```
model.updateManyWithDeleted(
        filter,
        { $set: 'items.$[a].ping': 'test'},
        { arrayFilters: ['a.kind': 'one'] },
      );
```

And you have a schema like the following

```
const ItemSchema = new Schema({ message: String }, { discriminatorKey: 'kind', _id: false });

const MainSchema = new Schema({ items: [ItemSchema] });

const path = MainSchema.path<MongooseSchema.Types.Array>('items');

const Onechema = new Schema({ping:String});
const TwoSchema = new Schema({pong:String});

path.discriminator('one', Onechema);
path.discriminator('two, TwoSchema);
```

Partial call stack: 
```
at _castArrayFilters (../node_modules/mongoose/lib/helpers/update/castArrayFilters.js:100:15)
       at castArrayFilters (../node_modules/mongoose/lib/helpers/update/castArrayFilters.js:28:3)
```

Inside method getPath the method schema.path doesn't know the discriminated properties
![Image](https://github.com/user-attachments/assets/2b45cdc9-4981-4973-926f-2e27492183ed)
![Image](https://github.com/user-attachments/assets/b16bc812-19c9-4988-99f0-74788600e9fa)
![Image](https://github.com/user-attachments/assets/2018d008-4980-4a37-89a9-7af04265c27e)

And the path method doesn't check in the discriminators
![Image](https://github.com/user-attachments/assets/2d90c7d1-85e7-4e12-bdda-cdf91c201957)

### Expected Behavior

The castArrayFilters, also check inside discriminators paths

**Comment by vkarpov15** [comment]
I'm unable to repro, the following script correctly sets `items.$[a].ping` to `updated` in Mongoose 7.4.0 and 8.8.3:

```javascript
const mongoose = require('mongoose');

async function main() {
  await mongoose.connect('mongodb://localhost:27017/test');

  // Define the base schema for items
  const ItemSchema = new mongoose.Schema(
    { message: String },
    { discriminatorKey: 'kind', _id: false }
  );

  // Define the main schema that includes an array of items
  const MainSchema = new mongoose.Schema({ items: [ItemSchema] });

  // Add discriminators to the `items` path
  const OneSchema = new mongoose.Schema({ ping: String });
  const TwoSchema = new mongoose.Schema({ pong: String });

  const path = MainSchema.path('items');
  path.discriminator('one', OneSchema);
  path.discriminator('two', TwoSchema);

  // Create the model
  const MainModel = mongoose.model('Main', MainSchema);

  // Clean up previous test data
  await MainModel.deleteMany({});

  // Insert a sample document
  const doc = new MainModel({
    items: [ 
      { kind: 'one', message: 'Hello', ping: 'initial' },
      { kind: 'two', message: 'World', pong: 'data' },
    ],
  });

  await doc.save();

  console.log('Initial document:', await MainModel.findOne().lean());

  // Update with arrayFilters
  await MainModel.updateMany(
    {},
    { $set: { 'items.$[a].ping': 'updated' } },
    { arrayFilters: [{ 'a.kind': 'one' }] }
  );
  console.log('Updated document:', await MainModel.findOne().lean());

  console.log('Done');
  process.exit(0);
}

main().catch((err) => console.error(err));

```

Please modify the above script to demonstrate the issue you're seeing.
