### ISSUE TITLE
Mongoose 8.8.2 returns back level MongoClient

### ISSUE THREAD

**Issue by nigel-daniels** [Automattic/mongoose#15060]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.8.2

### Node.js version

v20.18.0

### MongoDB server version

8.0.3

### Typescript version (if applicable)

5.7.2

### Description

I am using [LangGraph](https://langchain-ai.github.io/langgraphjs/reference/modules/checkpoint_mongodb.html) which has a Mongo DB backed checkpoint memory, to connect it is looking for a `MongoClient`, so I have attempted to get the `MongoClient` object from Mongoose. This is the code I have so far:

```
import { MongoDBSaver } from '@langchain/langgraph-checkpoint-mongodb';
import { type MongoClient } from 'mongodb';
import mongoose from 'mongoose';

const client = /** @type {MongoClient} */ ( mongoose.connection.getClient() );

const mongoDBParams = {
	checkpointCollectionName: 'checkpoints',
	client: client,
    dbName: process.env.MONGO_NAME
}

const memory = new MongoDBSaver(mongoDBParams);
```
Unfortunately this throws the following error:
```
ERROR in /usr/local/quoterion/server/graphs/email_quote.ts
18:32-45
[tsl] ERROR in /usr/local/quoterion/server/graphs/email_quote.ts(18,33)
TS2345: Argument of type '{ checkpointCollectionName: string; client: mongoose.mongo.MongoClient; dbName: string; }' is not assignable to parameter of type 'MongoDBSaverParams'.
Types of property 'client' are incompatible.
Property 'timeoutMS' is missing in type 'import("/usr/local/quoterion/server/node_modules/mongoose/node_modules/mongodb/mongodb").MongoClient' but required in type 'import("/usr/local/quoterion/server/node_modules/mongodb/mongodb").MongoClient'.
```
It seems the 'MongoClient` returned is not compatible as its parameters are missing the `timoutMS`. In the Current MongoDB driver I can see this property but the version of the documentation on the Mongoose reference links to am older version that does not have this property (maybe a v4 version?). AFAIK LangGraph is using a v6.11.0 Mongo Driver. 

Note in the rest of my code the mongoose driver is already up and running ok, hence I just thought I could get the underlying `MongoClient`.

### Steps to Reproduce

Install LangGraph.JS, TypeScript, Mongoose and the MongoDB Types. Create a typescript file with the above and attempt to build.

### Expected Behavior

This should build and run.

**Comment by vkarpov15** [comment]
Because it looks like your langchain and connect-mongo packages use mongodb@6.11, but Mongoose is still using mongodb@6.10. We will ship Mongoose 8.9, which will have support for mongodb@6.11 in the next day or two. But in the meantime, you should add mongodb@6.10 as a top-level dependency, that should help fix this issue.
