### ISSUE TITLE
index setting error occurred at 8.9.1("Schema already has an index")

### ISSUE THREAD

**Issue by 0Ams** [Automattic/mongoose#15109]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

# Error message
```
MongooseError: Schema already has an index on {"uid":1,"gid":1}
    at Schema.index (xxx/node_modules/mongoose/lib/schema.js:2151:13)
    at Object.<anonymous> (xx/schema/member.js:20:8)
```
# Schema 
```
/* eslint-disable */
const mongoose = require('mongoose');

const _schema = {
    uid: {type: mongoose.Schema.Types.ObjectId, required: true},
    gid: {type: mongoose.Schema.Types.ObjectId, required: true},
};
const schema = new mongoose.Schema(
    _schema,
    {'versionKey': false, 'usePushEach': true, 'minimize': false, 'shardKey': {'uid': 1}}
);
schema.index({'gid': 1, 'uid': 1}, {background: false});
schema.index({'uid': 1, 'gid': 1}, {background: false});
```
# mongoDB
```
test> db.test.createIndex({uid: 1, gid:1})
uid_1_gid_1
test> db.test.createIndex({uid: 1, gid:1})
uid_1_gid_1
test> db.test.getIndexes()
[
  { v: 2, key: { gid: 1, uid: 1 }, name: 'gid_1_uid_1' },
  { v: 2, key: { uid: 1, gid: 1 }, name: 'uid_1_gid_1' }
]
```

In my opinion, the two indexes seem to work differently in MongoDB. 
why is this causing an error in mongoose? It works correctly in mongoose@8.8.x, but it behaves abnormally in mongoose@8.9.1.

**Comment by maxuai** [comment]
We had the same error for a slightly different scenario:

we had declared the `unique` keyword twice, once in the schema and second time in a separate index creation:

```
const schema = new Schema({myId: {type String, required: true, unique: true}})
schema.index({myId: 1}, {unique: true})
```
removing the `unique` from the schema declaration fixed it.

**Comment by ronenteva** [comment]
I have the same issue with this use case:
```
schema.index({email: 1, region: 1}, {unique: true});
schema.index({email: 1, region: 1}, {name: 'email_1_region_1-active', partialFilterExpression: {active: true}});

```

**Comment by ecofi** [comment]
When can we expect a new release with a fix? This broke all our DB connections and difficult to port back to older mongoose release. Can this have a priority?

**Comment by winterrdog** [comment]
> We had the same error for a slightly different scenario:
> 
> we had declared the `unique` keyword twice, once in the schema and second time in a separate index creation:
> 
> ```
> const schema = new Schema({myId: {type String, required: true, unique: true}})
> schema.index({myId: 1}, {unique: true})
> ```
> 
> removing the `unique` from the schema declaration fixed it.

ran into the same issue & this seems to have fixed it 🤝

**Comment by orgads** [comment]
I have another regression with nestjs. See https://github.com/nestjs/mongoose/issues/2346.

**Comment by ecofi** [comment]
> > We had the same error for a slightly different scenario:
> > we had declared the `unique` keyword twice, once in the schema and second time in a separate index creation:
> > ```
> > const schema = new Schema({myId: {type String, required: true, unique: true}})
> > schema.index({myId: 1}, {unique: true})
> > ```
> >   
> > removing the `unique` from the schema declaration fixed it.
> 
> ran into the same issue & this seems to have fixed it 🤝

Yes, this also solved it for us. However, there is no information in the mongoose SchemaType section explaining "unique"=true creates an index too. Therefore, it would be highly appreciated to get clarification at least in the documentation, ideally with a warning info.

**Comment by vkarpov15** [comment]
We will change this error into a warning instead to prevent it from blocking anyone from upgrading.

**Comment by shehabadel** [comment]
> We had the same error for a slightly different scenario:
> 
> we had declared the `unique` keyword twice, once in the schema and second time in a separate index creation:
> 
> ```
> const schema = new Schema({myId: {type String, required: true, unique: true}})
> schema.index({myId: 1}, {unique: true})
> ```
> 
> removing the `unique` from the schema declaration fixed it.

This has solved it for us too, thank you :100:

**Comment by pauldraper** [comment]
Why is this a warning?

What is wrong?

**Comment by vkarpov15** [comment]
It is easy to unintentionally end up adding two indexes on the same field. For example, in #15056, the following example actually adds 2 indexes on `key`: one from `unique: true` and one from `schema.index()`

```javascript
const ObjectKeySchema = new mongoose.Schema({
  key: {
    type: String,
    required: true,
    unique: true,
  },
  type: {
    type: String,
    required: false,
  },
}, {
  timestamps: false,
  versionKey: false,
});

ObjectKeySchema.index({ key: 1 });
```

This causes index builds to fail and errors when running `syncIndexes()`.
