### ISSUE TITLE
Missing changelog / release for 7.8.3

### ISSUE THREAD

**Issue by felipeplets** [Automattic/mongoose#15117]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the issue has not already been raised

### Issue

Both the [changelog](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md) and the [releases page](https://github.com/Automattic/mongoose/releases) are missing details for version `7.8.3`

**Comment by vkarpov15** [comment]
Fixed changelog entry, 7.8.3 is now in master: https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md#783--2024-11-26 . Will look into fixing our automated release generation to see if we can apply that to 7.x too.

**Comment by felipeplets** [comment]
Great, thank you @vkarpov15

**Comment by vkarpov15** [comment]
GitHub releases fix should be in https://github.com/mongoosejs/backend/commit/505942cdaf7069899ed944d0ab26af9f3b2367a4, future 6.x and 7.x releases should end up in GitHub releases
