### ISSUE TITLE
The error caused by Binary when using lean queries still exists in `8.9.2`

### ISSUE THREAD

**Issue by nikzanda** [Automattic/mongoose#15122]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

8.9.2

### Node.js version

20.10.0

### MongoDB server version

6.0.2

### Typescript version (if applicable)

5.5.4

### Description

In version 8.9.2 of Mongoose, it seems that the error shown in this [issue](https://github.com/Automattic/mongoose/issues/15102) (and [this one](https://github.com/Automattic/mongoose/issues/15047)) is still not resolved.

In the reproduction link the query does not return IParent fields:
<img width="892" alt="Image" src="https://github.com/user-attachments/assets/24795e5f-20bb-495b-ba04-af267e865fdd" />

Instead, in my project, the last part of the error updates from:
```
Type 'Binary | null | undefined' is not assignable to type 'Buffer | undefined'.
Type 'null' is not assignable to type 'Buffer | undefined'.
```
to
```
Type 'Binary | undefined' is not assignable to type 'Buffer | undefined'.
Type 'Binary' is missing the following properties from type 'Buffer': equals, compare, copy, slice, and 93 more.
```

### Steps to Reproduce

Reproduction link [here](https://stackblitz.com/edit/vitejs-vite-twnhseek?file=src%2Findex.ts).

**Comment by timheerwagen** [comment]
I have updated to ^8.9.3 and the exact same repro from both comments still contains the bug.

Repro with ^8.9.3 https://stackblitz.com/edit/vitejs-vite-42pvczkq?file=src%2Findex.ts
