### ISSUE TITLE
Insconsistent schema.set

### ISSUE THREAD

**Issue by kelonye** [Automattic/mongoose#1512]
Second gist below doesn't set '_id' to false as expected?

```

// a
var schema = new mongoose.Schema({ name: String }, {
  _id: false
});

var Page = mongoose.model('Page', schema);
var p = new Page({ name: 'mongodb.org' });
console.log(p);

// { name: 'mongodb.org' }

// b
var schema = new mongoose.Schema({ name: String });
schema.set('_id', false);

var Page2 = mongoose.model('Page2', schema);
var p = new Page2({ name: 'mongodb.org' });
console.log(p);

// { name: 'mongodb.org', _id: 51a1ca0fae72dd4559000001 }

```

**Comment by antmarot** [comment]
Is this issue supposed to be solved?
I don't see it documented anymore (the *Pass this option during schema construction* bit has been removed) but I've had the same problem.

**Comment by vkarpov15** [comment]
@antmarot can you please open up a separate issue with code samples that demonstrate the issue you're seeing?

**Comment by wangwuyang** [comment]
官方文档跳过来的 然后就发现 最近的消息都已经是2年前的了
