### ISSUE TITLE
Variable Keys

### ISSUE THREAD

**Issue by CodersBrothers** [Automattic/mongoose#1522]
Objects JSON can use variable keys. Will be good that with mongoose we can define variable keys.

Some question with same.
http://stackoverflow.com/questions/11183480/how-to-set-key-by-var-in-mongoose-node-js
https://groups.google.com/forum/?fromgroups#!topic/mongoose-orm/hEabQU6bD6k
http://stackoverflow.com/questions/14195991/mongoose-variable-key-name
http://stackoverflow.com/questions/11133912/how-to-use-a-variable-as-a-field-name-in-mongodb-native-findandmodify

**Comment by vkarpov15** [comment]
Closing this in favor of #681, same issue just older and with more subscribers.

**Comment by vkarpov15** [comment]
This feature is now in Mongoose, see [maps](https://mongoosejs.com/docs/schematypes.html#maps)
