### ISSUE TITLE
Plugin on different connection schemas with same name issue

### ISSUE THREAD

**Issue by eherve** [Automattic/mongoose#1531]
Hello,

I have several plugins loaded on mongoose via mongoose.plugin(...); and I use several connections created via mongoose.createConnection(...). On these connections I load different schemas but with the same name like connection1.model('User', userSchema1) and connection2.model('User, userSchema2);

But mongoose cache the loading of plugins to avoid doing it twice on the same schema. The cache specification (key) is done on the schema name and does not take into account the fact that it is two different schemas (same name different schema different connection). 
#see: lib/index.js line 257~269

Regards,
\--
herve_e

**Comment by vkarpov15** [comment]
Pretty sure this issue is gone in more recent versions and this issue's been stale for years. Re-open if this is still an issue.
