### ISSUE TITLE
Model.distinct().populate() does not populate correctly

### ISSUE THREAD

**Issue by ttezel** [Automattic/mongoose#1549]
I have an `Item` model, which has a `user` property, that is an ObjectID referencing a `User` model. When I query like so:

``` js
Item
.distinct('user', { state: 'foo' })
.populate('user')
.exec(function (err, users) {
    console.log('users', users)
})
```

I get back the distinct user Object IDs, but I expected to get back the populated `User` models instead.

Versions I am using:
mongoose@3.6.11, mongodb@1.3.5

**Comment by afshinm** [comment]
To clarify the problem, `distinct` returns an array of `id`s not array of objects. Therefore, it has no properties and you cannot populate it.

One possible solutions is to pass the array of ids to `find` and fetch posts using `$in`.
