### ISSUE TITLE
Unable to fetch _id object from find method.

### ISSUE THREAD

**Issue by justin-john** [Automattic/mongoose#1567]
I have created a some mongo documents via shell

```
db.users.insert([{ _id: 1, name: "angel" },
    { _id: 2, name: "justin" },
    { name: "rose" }]);
```

I have queried mongoose find to retrieve all users.

``` javascript
model.find(function (err, users) {
    if (err) {
        console.log(err);
    } else {
        console.log(users);
    }
});
```

The console shows as

```
[ { name: 'angel' },
  { name: 'justin' },
  { _id: 51d3c4a113cfcdb762000000, name: 'rose' } ]
```

It is missing `_id` in first two records as I have created `_id` for those records. The third one returns `_id`.

The schema for users 

```
UserSchema = new Schema({
    name: String
}),
```

Why I am unable to fetch `_id` on manually created `_id`?

**Comment by joetidee** [comment]
I am having exactly the same issue in Mongoose v4.7.3 and it is inconvenient to not have the _id field returned if it is a String. Even more so that it is returned sporadically. Can it be returned regardless of type, perhaps in a future release?

**Comment by vkarpov15** [comment]
@joetidee can you please provide a code sample that reproduces your issue?

**Comment by joetidee** [comment]
Basically, if you create the _id yourself (by supplying your own string) and do not set _id: {type: String} in the schema, any results that are returned from a 'find' query will contain some records that include the _id and others that don't.

**Comment by vkarpov15** [comment]
Prose description !== code sample

**Comment by joetidee** [comment]
Same as @justin-john , but it hink it is irrelevant now that i have discovered that if you set the _id: {type: String} in the schema then Mongoose knows what to expect and returns the results accordingly.

**Comment by justin-john** [comment]
@vkarpov15 I believe, what @joetidee ask initially is to return `_id` even if schema is not set for `_id` field. The result should  return "_id" value for each document  regardless of it's type(Number, String or Object). Just like if we insert few documents to collection in mongo shell and query, it will return all data.

```
db.users.insert([
   { _id: 'One', name: '_id as String' },
   { _id: 11, name: '_id as Number' },
   { name: 'Without  _id' }
]);
db.users.find().pretty()
{ "_id" : "One", "name" : "_id as String" }
{ "_id" : 11, "name" : "_id as Number" }
{ "_id" : ObjectId("586e9939577b10ea92a63251"), "name" : "Without  _id" }
```
I think, this can be done in mongoose by setting `Schema.Types.Mixed` schema for `_id`. Is there any future release going to be supported this feature without specifically setting schema for `_id`?

**Comment by vkarpov15** [comment]
Nope not planning on doing that

**Comment by justin-john** [comment]
Thank you Valeri.
