### ISSUE TITLE
Issue with using transform and arrays

### ISSUE THREAD

**Issue by cyberwombat** [Automattic/mongoose#1584]
I want to use the transform option but it seems to iterate through all the subdocuments of the document. How can I tell where I am at or how can I edit the document in one go.  For example let's say I have this schema:

```
var UserSchema = new mongoose.Schema({

  name: {
    type: String
  },
  addresses: [{
    address: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'AddressSchema'
    }
    active: Boolean
  }],
```

If I wanted to add a 'created' field with a date what I end up with is a created field in both the main doc as well as each address sub document and I don't see a way of seeing where I am at. 

On a related note I am also having a problem that I want to remove all the _id fields from the subdocuments (addresses). Is there a way to prevent Mongo from creating an id field for every array entry?  I thought it only used to do that with nested schemas but now it seems that every array is a nested schema.

Thank you for your time.

**Comment by newmanw** [comment]
Also seems that calling:

doc.toObject({ transform: true, anotherOption: option });

To manually transform the document does not transform sub-documents.  Is this expected behavior?

**Comment by vkarpov15** [comment]
@newmanw no that should work. What version of mongoose are you using? I believe 3.8.23 had a bug where `transform: true` wasn't applied to subdocs.

**Comment by newmanw** [comment]
@vkarpov15 just upgraded to npm latest (3.8.24) and from what I can tell the transform is still not called on subdoc.

```javascript
  if ('function' != typeof observation.ownerDocument) {
    console.log('xform called on parent')
  } else {
    console.log('Never called');
  }
```

**Comment by vkarpov15** [comment]
Hmm can you provide me some code that reproduces this? We now have test coverage for this (see #2691) and AFAIK this works in 3.8.24.

**Comment by codeHatcher** [comment]
I am having the same problem as @newmanw 
```javascript
if ('function' == typeof doc.ownerDocument) {
      // never called
      return;
    }
```
Version 3.8.24

**Comment by vkarpov15** [comment]
Can you show me some code that reproduces this?  3 lines of code doesn't really tell me much and doesn't change the fact that i haven't been able to reproduce this

**Comment by codeHatcher** [comment]
The code I have is effectively similar to @newmanw. If you still need some sample code aside from what @newmanw has let me know and I will come up with something.

**Comment by vkarpov15** [comment]
Are you setting `transform: true`?
