### ISSUE TITLE
Inconsistent Error object for CastError

### ISSUE THREAD

**Issue by obibring** [Automattic/mongoose#1587]
Validation errors produce an object with the following structure:
```javascript
{
  errors: {
    field_1: {
      message: '',
      name: '',
      path: '',
      type: '',
      value: ''
     },
    field_2: {
      <etc. etc.>
    }
  }
```

However, when setting a document property to a value that produces a CastError, the structure of the error object is different:

```javascript
{
    // "errors" key omitted here.
    message: '',
    name: '',
    type: '',
    value: '',
    path: ''
}
```

When a property is set to a String where a number is required, the second error is produced. However, as a user, I would consider this a validation error and would like to see an error structure identical to other validation errors.

**Comment by vkarpov15** [comment]
Fixed in 4.x
