### ISSUE TITLE
select: false makes field values not accessible using "this.field_name"

### ISSUE THREAD

**Issue by endymion00** [Automattic/mongoose#1596]
When using a plugin (I'm using mongoose-user) I've noticed that from methods defined in schema.methods inside a plugin (in my example mongoose-user.js) it is not possible to get the value of  fields that have been marked as "select: false" in the model (in my example user.js) 

So if you apply  "select: false" to a field it won't be accesible from a plugin.
By removing this property or setting it to "select: true" the field is accessible again.

**Updated info**: I've also tested moving the plugin logic to user.js and the problem persists. I can't read values using this.field from user.js methods too.

Sample using a plugin: (see line `console.log('mongoose-use hashed_password', this.hashed_password); )`

``` javascript
// model/user.js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var userPlugin = require('mongoose-user');

var UserSchema = new Schema({
  name: { type: String, default: ''  },
  email: { type: String, default: '' },
  hashed_password: { type: String, default: '', select: false },
});

UserSchema.plugin(userPlugin, {});

mongoose.model('User', UserSchema)

```

``` javascript
// mongoose-user.js

module.exports = userPlugin

function userPlugin (schema, options) {
var crypto = require('crypto');

  schema.methods.authenticate = function(plainText) {
    // THIS CONSOLE.LOG CAN'T ACCES TO this.hashed_password value
   // IT ALWAYS RETURN 'undefined'.    
    console.log('mongoose-use hashed_password', this.hashed_password);
    return this.encryptPassword(plainText) === this.hashed_password
  }

schema.methods.encryptPassword = function (password) {
    if (!password) return '';
    return crypto.createHmac('sha1', this.salt).update(password).digest('hex');
   }

}
```

**Comment by jasonshark** [comment]
you can override the select false fields with select for your queries (SO thread [here](http://stackoverflow.com/questions/12096262/how-to-protect-the-password-field-in-mongoose-mongodb-so-it-wont-return-in-a-qu))

```
// add back the password field for this query
var query = User.findOne({
    email: req.body.email
}).select('_id email +password');

query.exec(function(err, user){
    // user with included password field

});

```

My user schema in this case looked like:

```
var userSchema = new Schema({
	email: {type: String, required: true, unique: true },
	password: {type: String, required: true, select: false },
	admin: Boolean
});
```

**Comment by kesarion** [comment]
@vkarpov15 Would it make sense to have access to a `this.select()` function to selectively request the missing fields only when necessary?

For example:

```javascript
ResourceSchema
    .virtual('voted')
    .get(function() {
        if (global.user) {
            this.select( 'voters');
            return _.includes(this.voters, global.user._id);
        }
        return null;
    });
```

Voters would hypothetically contain the ids of users who have voted (some resource). Let's say we don't want to select them by default, but want to check if the logged in user has already voted (set in global in the example).

I suppose it would be less efficient, needing another query to the database, but in some cases where performance isn't critical it might make sense to know that's automatically taken care of.

**Comment by vkarpov15** [comment]
@kesarion would be more efficient and cleaner to apply that logic to filter out the `voters` field after running the query if the user has not voted than to execute a separate query specifically for the `voters` field.

**Comment by r3wt** [comment]
The way i handle this with my models is to add an instance method called `clean()`:

```js
schema.methods.clean = function(){
    const obj = this.toObject();
    const sensitive = ['password','activation_token'];//these are the fields you want to remove
    sensitive.forEach((item)=>{
        delete obj[item];
    });
    return obj;
};
```

**Comment by vkarpov15** [comment]
@r3wt your approach works, but I'd argue against it because you [rarely want to include a user's password in the user document as described in this blog post](https://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis). Keeping the password hash in the user document creates more problems than it solves in my experience.

**Comment by r3wt** [comment]
good general advice, but my way is fine if you are careful not to expose the hash in responses.

On May 10, 2019 4:31 PM, Valeri Karpov <notifications@github.com> wrote:

@r3wt<https://github.com/r3wt> your approach works, but I'd argue against it because you rarely want to include a user's password in the user document as described in this blog post<https://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis>. Keeping the password hash in the user document creates more problems than it solves in my experience.
