### ISSUE TITLE
Does document.remove actually return the removed doc?

### ISSUE THREAD

**Issue by hunterloftis** [Automattic/mongoose#1618]
The documentation suggests that `docInstance.remove()` takes a callback and passes `err, document`, but that doesn't seem to actually work:

https://github.com/LearnBoost/mongoose/blob/049288f7b2f2cc0fb4a4a275c7e801304df93938/lib/model.js#L550

`remove()` calls back with no second argument, even when a document has been removed. It would be nice if the removed document were passed back as in the example, but if not then the documentation should at least be updated with the real behavior.

**Comment by stieg** [comment]
Is the same true for `Model.findOneAndRemove`?  I just tried this and am getting nothing returned as the doc to the function callback even though the docs state
> Finds a matching document, removes it, passing the found document (if any) to the callback.

I am seeing an item removed from my DB.  Mongoose 4.8.3, MongoDB 3.4.  If so please update the docs there as well.  Probably also affects findByIdAndRemove too.  TIA.

**Comment by vkarpov15** [comment]
@stieg `findOneAndRemove()` should return the removed doc, if any. If this isn't working for you please open up a new issue with code samples.

**Comment by stieg** [comment]
> @stieg findOneAndRemove() should return the removed doc, if any. If this isn't working for you please open up a new issue with code samples.

Will do.
