### ISSUE TITLE
Why the getter function is called for 2 times

### ISSUE THREAD

**Issue by blackgun** [Automattic/mongoose#1639]
In my model, there is a getter function:

    tags: {type: [], get: getTags, set: setTags},

getTags:

	var getTags = function (tags) {
	    console.log('getTags:',tags);
	    return tags.join(',')
	}

Every time reading the model, console will display same tags for 2 times,like:

	getTags: [ movie ]
	getTags: [ movie ]

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
