### ISSUE TITLE
Cast error on populate field with null (ver >= 3.6.0 )

### ISSUE THREAD

**Issue by wmig** [Automattic/mongoose#1661]
On version 3.5.16 its work
On version 3.6.2 - 3.6.17 there is "Cast.error"

var Order = new Schema({
 user                      : { type : Schema.ObjectId, ref : 'User', default : null }
})

Order.find().populate('user')

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
