### ISSUE TITLE
work around MongoDB 2dsphere validation

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#1668]
http://stackoverflow.com/questions/16388836/does-applying-a-2dsphere-index-on-a-mongoose-schema-force-the-location-field-to/17328860?noredirect=1

**Comment by keithrz** [comment]
How is an actual geoJSON field handled?  The code commit only seems to test legacy coordinate pairs.

I'm trying this model:
```
var mySchema = new mongoose.Schema({
geolocation: {
    type: {type: String},
    coordinates: []
  }
)};

mySchema.index({geolocation: '2dsphere'});
```

and if I do not specify geolocation in my insert, I get the failure message:
MongoError: insertDocument :: caused by :: 16755 Can't extract geo keys from object, malformed geometry?: { _id: ... , geolocation: { coordinates: [] } ... }

I've also tried this:
```
geolocation: {
    type: {type: String},
    coordinates: {
        type: [],
        required: false
    }
```

**Comment by vkarpov15** [comment]
Mongoose sets coordinates to an empty array by default. To work around this, you can use a pre save hook:

```javascript
var mySchema = new mongoose.Schema({
geolocation: {
    type: {type: String},
    coordinates: { type: [] }
  }
});

mySchema.pre('save', function(next) {
  if (this.geolocation.coordinates.length === 0) {
    this.geolocation.coordinates = undefined;
  }

  next();
});
```

**Comment by keithrz** [comment]
Yes, thank you for the response.  I just tried that exact same workaround, from the stackoverflow article at the beginning of this issue thread.  My code (taking stackoverflow workaround verbatim):
```
mySchema.pre('save', function (next) {
    if (this.isNew && Array.isArray(this.geolocation.coordinates) &&
        this.geolocation.coordinates.length === 0) {
        this.geolocation.coordinates = undefined;
    }
    next();
});
```
but this is still a workaround.  Shouldn't this issue be re-opened?

**Comment by vkarpov15** [comment]
Not exactly, this fix is working as designed. The fix only works if you specify '2dsphere' in the field options:

```javascript
var mySchema = new mongoose.Schema({
geolocation: {
    type: {type: String},
    coordinates: { type: [], index: '2dsphere' }
  }
)};
```

**Comment by keithrz** [comment]
But that puts the index on geolocation.coordinates, doesn't it?  The index should include the entire geolocation field, which includes the type, right?  This provides the added benefit of mongo validating all of your geoJSON.

**Comment by vkarpov15** [comment]
Fair point actually. Opened new issue #3233 to track. Could be easily implemented as a plugin...

**Comment by keithrz** [comment]
Thanks!

**Comment by akreienbring** [comment]
The proposed pre save hook, does not work for me. Even if the hook is applied I get an "MongoError: Can't extract geo keys" ... "Point must be an array or object"... :-(
