### ISSUE TITLE
Must call mongoose.model for child schema to apply global plugins

### ISSUE THREAD

**Issue by fluxxu** [Automattic/mongoose#1674]
According to the document about Sub Docs:
http://mongoosejs.com/docs/subdocs.html
In the example code, there is no mongoose.model call for child schema. 
But if you don't call mongoose.model, global plugins registered by mongoose.plugin are not applied to the schema. 
I think this may confuse people. Please note this in document.

version: 3.6.17

**Comment by gdeward** [comment]
Is this still true?

What is the impact of calling `mongoose.model` for the child schema?  Would it be stored in its own collection because of this?

**Comment by vkarpov15** [comment]
This is no longer true, see discussion in #4271. This behavior was undocumented and changed in 4.5.
