### ISSUE TITLE
addToSet adds duplicates

### ISSUE THREAD

**Issue by lazdmx** [Automattic/mongoose#1677]
Method `MongooseArrays#addToSet` adds duplicates in case of custom type of elements. Seems that problem in `_id` field which automatically assigned to items being added to set.

For code like:

``` coffee

      doc.arrayField.addToSet(
        a: 42
        b: 42
      )

```

mongoose issues update command with modifier:

```
{ '$addToSet': { 'arrayField: { '$each': [ { a: 42, _id: ObjectId("5226b3bcbd3d3ae270000003"), b: 42 } ] } } }
```

**Comment by MuriloEduardo** [comment]
> By design. Subdocuments have an _id field. You could disable the auto _id creation by mongoose on the sub schema level at the cost of being able to use doc.array.id(..) and maybe a few other places. Set your sub schemas `_id` option to false.
> 
> ```
> new Schema({..}, { _id: false})
> ```

it solved 100% for me,
the result of the model was like this:

```
this.model = connection.model(
  'CostData',
  new Schema(
    {
      description: { type: String, required: true },
      value: Number,
      values: [
        {
        _id: false,
        paid: Boolean,
        month: Number,
        value: Number,
        },
      ],
    },
    { collection: 'costs' }
  )
);
```

and to use it, like this:

```
async markAsPaid(_id, value) {
  return await this.costModel.updateOne(
    { _id },
    { $addToSet: { values: { paid: true, ...value } } }
  );
}
```

I hope it helps!
