### ISSUE TITLE
What is the unit of measurement for the radius option on query.within.center?

### ISSUE THREAD

**Issue by JedWatson** [Automattic/mongoose#1684]
When using `query.within.center` on a 2dsphere geo field, how do you convert a kilometre (or mile) to the proper radius value?

The mongo docs suggest to divide by the number of kilometres in a radian (6,371):

http://docs.mongodb.org/manual/tutorial/calculate-distances-using-spherical-geometry-with-2d-geospatial-indexes/

... however when doing so, my query returns no results.

Upping the radius to something larger (say, 0.5) returns around 5-10kms worth of results but I'm having trouble figuring out how it works exactly.

My query condition looks like this:

```
query.where('geo').within.center({ center: [near[0], near[1]], radius: 0.05 });
```

Why is this different to the mongo docs, and what is the unit of measurement?

**Comment by lvarayut** [comment]
@JedWatson, so, do you divide by `111.12` instead of `6371`?

**Comment by Ludrin** [comment]
Not sure how relevant this still is, as it was posted in 2013, but I had a similar issue.
I'm using the following configuration:

- MongoDB: 4.4.5
- mongoose: 5.12.3
- Node.js: 15.9.0

I had to split the kilometer by radians to get the radius. So if I want everything in a one kilometer radius I have to calculate 1/6371.

```
const km = 1;
const radius = km / 6371;
const area = { center: [centerLongitude, centerLatitude], radius: radius, unique: true, spherical: true };
query.where('geo').within().circle(area);
```

Remember that your `geo` has to be a Point Schema (geojson), as specified in [mongoose docs](https://mongoosejs.com/docs/geojson.html).

For example:

```
const pointSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['Point'],
    required: true
  },
  coordinates: {
    type: [Number],
    required: true
  }
});

const citySchema = new mongoose.Schema({
  name: String,
  geo: {
```
    type: pointSchema,
    required: true
  }
});
