### ISSUE TITLE
find + limit faster for some wrappers? (e.g. findById)

### ISSUE THREAD

**Issue by andrewwakeling** [Automattic/mongoose#1692]
There's some sources that say that using "find().limit(1)" is much quicker than using findOne().

I noticed that some of the wrapper functions (e.g. findById) are using findOne().
Just wondering if substituting the find().limit(1) would be beneficial in some of these wrappers without loss of functionality.

If there's some loss of functionality, maybe another findByIdQuick or findByIdLean method could be created?

Thanks!

Sources:
http://dba.stackexchange.com/questions/7573/difference-between-mongodbs-find-and-findone-calls
https://blog.serverdensity.com/checking-if-a-document-exists-mongodb-slow-findone-vs-find/

**Comment by aschmid** [comment]
so is `Model.findOne()` using `Model.find().limit(1)` under the hood?
or is it still better to use `Model.find().limit(1)`?

**Comment by vkarpov15** [comment]
No, `Model.findOne()` is slightly different than `Model.find().limit(1)`. I always just use `findOne()`, never seen a case where I found `findOne()` to be too slow unless I was missing an index, and in that case `.find().limit(1)` wouldn't help.
