### ISSUE TITLE
How to use count() ?

### ISSUE THREAD

**Issue by xdamman** [Automattic/mongoose#17]
I tried many things but I can't make count() work.
Based on the documentation, it is supposed to work this may:
User.find({username: 'john'}).count()

I've got this error:
DEBUG: TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /lib/mongoose/lib/model.js:177:9

I've also tried with 
User.find({username: 'john'}).count(fn(r) { sys.debug(r); })
Or 
User.count(); 
...

Thanks for your support.

**Comment by Jatik** [comment]
I encountered with the same problem, the correct code is:

`User.count({},function(**err**, count) { } )`

**Comment by cesargdm** [comment]
```
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

**Comment by vkarpov15** [comment]
https://mongoosejs.com/docs/deprecations.html#-count-
