### ISSUE TITLE
Driver cursor problem

### ISSUE THREAD

**Issue by eknkc** [Automattic/mongoose#1700]
We have been on mongoose 3.6.15 for a while without any problems. Yesterday, I pushed an update to 3.6.19 to our servers.

Today I looked at the mongodb.log file and it's filled with these:

```
Thu Sep 19 14:27:52.232 [conn822108] ClientCursor::find(): cursor not found in map '8101396862109959409' (ok after a drop)
Thu Sep 19 14:27:52.232 [conn822108] killcursors: found 0 of 1
Thu Sep 19 14:27:52.239 [conn822107] killcursors: found 0 of 1
Thu Sep 19 14:27:52.241 [conn822108] killcursors: found 0 of 1
Thu Sep 19 14:27:52.244 [conn822109] killcursors: found 0 of 1
Thu Sep 19 14:27:52.251 [conn822110] killcursors: found 0 of 1
Thu Sep 19 14:27:52.328 [conn822107] killcursors: found 0 of 1
Thu Sep 19 14:27:52.334 [conn822110] killcursors: found 0 of 1
Thu Sep 19 14:27:52.369 [conn822111] killcursors: found 0 of 1
Thu Sep 19 14:27:52.374 [conn822174] killcursors: found 0 of 1
Thu Sep 19 14:27:52.376 [conn822108] killcursors: found 0 of 1
Thu Sep 19 14:27:52.381 [conn822177] killcursors: found 0 of 1
Thu Sep 19 14:27:52.404 [conn822110] killcursors: found 0 of 1
Thu Sep 19 14:27:52.423 [conn822110] killcursors: found 0 of 1
Thu Sep 19 14:27:52.592 [conn822108] killcursors: found 0 of 1
Thu Sep 19 14:27:52.597 [conn822110] killcursors: found 0 of 1
```

As you can see it is logging this nearly at 50/second rate. Just downgraded back to 3.6.15 and the logging stopped.

Mongodb: 2.4.4 on debian stable
Node: 0.10.16

Replica set with a primary a secondary and an arbeiter. All logs are on the replica primary, secondary is not affected.

Any ideas?

**Comment by davebaol** [comment]
Personally, I'd close this and a lot of other old issues for lack of activity. 
They are just kinda garbage and Mongoose does not deserve 400+ open issues. :wink:

**Comment by vkarpov15** [comment]
@davebaol yeah good call. Will take some time to close out some of these stale issues.

**Comment by davebaol** [comment]
Nice! :+1: 
You might even close just 2 or 3 stale issues a day to achieve a good result in a few weeks
