### ISSUE TITLE
Model.find().exec(function (err, data) { do something  })

### ISSUE THREAD

**Issue by thanhthang20** [Automattic/mongoose#1706]
Take a look at "myObject" and "pers"
Why we can not print out the value of "myObject" when it is out side "exec" function. The value of myObject when it out side is "undefined"

![image](https://f.cloud.github.com/assets/5382700/1187828/30ffb13c-239d-11e3-8584-dc40274b5f4d.png)

Thank so much!

**Comment by YASHVEER321** [comment]
You can user waterfall/async method for solve this problem.
