### ISSUE TITLE
add support for lastErrorObject on findAndModify

### ISSUE THREAD

**Issue by manast** [Automattic/mongoose#1710]
According to [MongoDB documentation](http://docs.mongodb.org/manual/reference/command/findAndModify/), findAndModify returns an object called *lastErrorObject* that includes quite useful information: 

```
lastErrorObject: {
                        updatedExisting: <boolean>,
                        upserted: <boolean>,
                        n: <num>,
                        connectionId: <num>,
                        err: <string>,
                        ok: <num>
   }
```
For instance knowing if the object was upserted or not is quite useful in many situations. The current callback in mongoose has two parameters, *err* and *doc*, wouldn't be good to add a third one *extra* with the contents of the lastErrorObject?

**Comment by vkarpov15** [comment]
See the [`passRawResult` option to `findOneAndUpdate()` and `findOneAndRemove()`](http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate)
