### ISSUE TITLE
Passing reference to a connected mongoose object between modules seems to cause hangs.

### ISSUE THREAD

**Issue by peterbraden** [Automattic/mongoose#1717]
Rather than have several db pools, I've been passing the mongoose object around, ie:

```javascript
// db.js
var mongoose = module.exports = require('mongoose')
mongoose.connect(...)

//foo
var mongoose = require('./db')
...
```

However this has sometimes caused model.save to hang infinitely. I'm assuming theres some underlying connection issue, as mongodb still has the connection pool maintained.

mongoose: 3.6.20
mongodb version v2.4.5

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
