### ISSUE TITLE
How to get collection name list for the current connection?

### ISSUE THREAD

**Issue by Sparo** [Automattic/mongoose#1729]
I have code:

```
var db = mongoose.createConnection('mongodb://localhost:27017/PageViews');
console.log(db.collections)
```

but result is `{}`
_(I have 5 collections in this  db)_
I also tried 

```
    db.db.collectionNames(function (err, names) {
        console.log("in the result st")
        console.log(err);
        console.log(names);
    })
```

but function doesn't even fires, probably because it does not exists...
so, is there some other way?

**Comment by slmnkhn79** [comment]
mongoose.connection.db.collections(function(err, collections){
      if(err)
      reject(err);
      else{
        resolve(collections);
      }
