### ISSUE TITLE
Either Schema.prototype.add or Document.prototype.set is broken

### ISSUE THREAD

**Issue by lbeschastny** [Automattic/mongoose#1730]
I played around `Schema.prototype.add` and `Document.prototype.set` and found a curious bug.

The following code works perfectly fine:

```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var SomeSchema = new Schema({
  data: String
});

SomeSchema.add({
  prefix: {n: Number}
});

var Some = mongoose.model('Some', SomeSchema);

var doc = new Some;

doc.set({prefix: {n: 1}});
console.log(doc);

doc.set({'prefix.n': 2});
console.log(doc);

doc.set('prefix.n', 3);
console.log(doc);

doc.set('prefix', {n: 4});
console.log(doc);

```

It sets `prefix.n` field correctly no matter how I'm calling `Document.prototype.set`:

    { prefix: { n: 1 }, _id: 52553efa8eff9cfb2b000001 }
    { prefix: { n: 2 }, _id: 52553efa8eff9cfb2b000001 }
    { prefix: { n: 3 }, _id: 52553efa8eff9cfb2b000001 }
    { prefix: { n: 4 }, _id: 52553efa8eff9cfb2b000001 }

But when I'm trying to use `prefix` in `Schema.prototype.add`:

```js
SomeSchema.add({n: Number}, 'prefix.');
```

the last `doc.set` breaks:

    { prefix: { n: 1 }, _id: 525541343bedb93e38000001 }
    { prefix: { n: 2 }, _id: 525541343bedb93e38000001 }
    { prefix: { n: 3 }, _id: 525541343bedb93e38000001 }
    { prefix: { n: 3 }, _id: 525541343bedb93e38000001 }

I also tried tho following code:

```js
SomeSchema.add({ 'nested.prefix.n': Number});
```

And it also broke.

I've already got rid of all prefix calls to `Schema.prototype.add` in my code, but it may break someone else's code.

**Comment by lbeschastny** [comment]
@vkarpov15 I've just reproduced this weird bug with the latest `mongoose@4.5.0`.

So it still exists somewhere, though it doesn't look important. I can't event remember how I've stumbled upon it in the first time.

**Comment by vkarpov15** [comment]
Hmm interesting, I'll re-open this. I've been going through and closing out stale issues because I probably will never get to them, but if it's still a problem I'm happy to look into it.
