### ISSUE TITLE
findByIdAndUpdate with req.body.model_name not working

### ISSUE THREAD

**Issue by codegoblin** [Automattic/mongoose#1734]
Hi,

Pardon the coffeescript, but I have some form data being sent into an update action that basically equates to this object:

console.log req.body.reveal #outputs:
{ chef:
   { name: 'a',
     title: '',
     description: '',
     bio: '',
     bio_title: '',
     location: '' },
  recipe: { name: 'j', serves: '' } }

Now,
When I run the following:
Reveal.findByIdAndUpdate req.params.id, req.body.reveal, (err, reveal) ->
it returns me the error:
[TypeError: Cannot read property 'name' of undefined]
however, that field definitely exists on the schema, which looks like this:

RevealSchema = new Schema
  chef:
    name: { type: String }
    title: { type: String }
    description: { type: String }
    bio: { type: String }
    bio_title: { type: String }
    location: { type: String }
    links: [url: { type: String }]
    images: [{ type: Schema.Types.ObjectId, ref: 'Picture' }]
  recipe:
    name: { type: String }
    description: { type: String }
    serves: { type: Number }
    ingredients: [ description: { type: String }]
    steps: [ description: { type: String } ]
    images: [{ type: Schema.Types.ObjectId, ref: 'Picture' }]
  visible: { type: Boolean, default: false }
  created_at: { type: Date, default: Date.now }

if I actually extrapolate the form object and put it directly into the call like ...

Reveal.findByIdAndUpdate req.params.id, {... object literal here ...} , (err, reveal) ->

than it works fine.

Any idea why passing in the req.body.reveal doesn't work when just hardcoding the object literal does? Using mongoose 3.6.20 and Express 3.x

**Comment by vkarpov15** [comment]
Old issue, re-open if this is still an issue
