### ISSUE TITLE
addToSet not working

### ISSUE THREAD

**Issue by sagivo** [Automattic/mongoose#1753]
addToSet as mentioned here (http://mongoosejs.com/docs/api.html#types_array_MongooseArray-addToSet) is not working. 
this will not update the db:

doc.someField.addToSet(someValue)

while this will work:

doc.update({
  $addToSet: {
    someField: someValue
  }
}, function(err, d) {});

**Comment by vkarpov15** [comment]
Stale issue, re-open if this is still an issue.
