### ISSUE TITLE
wish: invalid schema feedback should provide pointer what part of the schema was invalid

### ISSUE THREAD

**Issue by markstos** [Automattic/mongoose#1767]
I just tried to start my Node server after some Mongoose code and got this error message:

```
mongoose/lib/schema/array.js:58
 this.caster = new caster(null, castOptions);
              ^
TypeError: object is not a function
```

I suspect the issue is with my schema, not with the internals of Mongoose. This error message is not very helpful. A helpful error message would report the location in the schema that triggered the exception, rather than the location in Mongoose where the exception was thrown.

**Comment by markstos** [comment]
Was this "wish" closed because it was implemented or because it was rejected?

**Comment by vkarpov15** [comment]
Implemented, http://mongoosejs.com/docs/validation.html

**Comment by markstos** [comment]
Thanks!
