### ISSUE TITLE
Events problem

### ISSUE THREAD

**Issue by Lisio** [Automattic/mongoose#1774]
I'm using latest 3.8.0 and noticed some strange behavior. 

1. If I restart mongodb server, the mongoose triggers "disconnected" event at first and then the consequent "error" events until the mongodb process is restarted. But when it is restarted, mongoose reconnects successfully but silently without any events being triggered ("reconnected", "connected", "connecting", "open"). If I restart the mongodb server for the second time, even "disconnected" event will not be triggered, only "error" events.

2. If I try to connect to the mongodb server which is down initially, then no reconnections will happen at all, even when the mongodb server will be online again.

In both cases the options are set to {server: {auto_reconnect: true}}.

**Comment by johanneslumpe** [comment]
@vkarpov15 Has there been any development on this issue at all? I am currently seeing the following:

1. Starting up a server, mongodb initially down, `disconnected` and `error` events are fired
2. Bringing mongodb up, no events are fired, but in the console I can see that 5 connections have been established.

Is there a way to either completely destroy this connection instance (created with `mongoose.createConnection` or to have it emit the proper events?

I have tried to use `conn.db.close()`, `conn.close()` and `conn.doClose()`. None of those prevented the connection from silently connecting to the database after an error. As the OP, I'm using `auto_reconnect: true` as option for the created connection.

**Comment by vkarpov15** [comment]
@johanneslumpe there have been some related issues that have been resolved. Can you provide some code samples and clarify which version of mongoose you're using?

**Comment by johanneslumpe** [comment]
@vkarpov15 sure! Using mongoose 4.3.7 right now. Here is a snippet which, when executed while mongod is not running, will fail to connect. When then starting up mongod, you will see that connections are being made, but no events whatsoever are emitted.

```js
const mongoose = require('mongoose')
const uri = '...';

// if the database is initially down, the following way of connecting
// will silently connect to the database (can be seen in the log of
// mongod) but will not report any kind of events to the consumer.

const conn = mongoose.createConnection(uri, {
  server: {
    auto_reconnect: true
  }
});

conn.on('error', () => {
  console.log('Error connection to database');
});

conn.on('disconnected', () => {
  console.log('Lost MongoDB connection...');
});

conn.on('connected', () => {
  console.log('Connection established to MongoDB');
});

conn.on('reconnected', () => {
  console.log('Reconnected to MongoDB');
});
```

Without `auto_reconnect` the script will just exit after the initial error. With it enabled it will just sit there and eventually connect if the db comes back online.

It would be important for those events to be properly triggered because I want to wait for a DB connection before bootstrapping the rest of the application. And since reconnecting is already supported it would be great if we were able to just use that instead of having to create our own handlers for that and then disabling the auto-reconnect feature.

**Comment by vkarpov15** [comment]
The above PR will be merged into mongodb-core 1.3, so we're gonna have to postpone this feature to a future release.

**Comment by vkarpov15** [comment]
As a workaround, this old goody should help: https://gist.github.com/asalant/4092454

**Comment by johanneslumpe** [comment]
@vkarpov15 thanks for the update! The proposed workaround will unfortunately require manually handling all connection drops, but I guess there is nothing we can do about it right now :)

**Comment by vkarpov15** [comment]
Actually nvm, latest 4.4 uses mongodb 2.1.16, which uses mongodb-core 1.3.
