### ISSUE TITLE
mongoose-rbac incompatible with mongoose 3.8.x

### ISSUE THREAD

**Issue by daseinindustries** [Automattic/mongoose#1780]
Yesterday I was about to update the Roles and Permissions collections with some new values and encountered a problem where:

Permissions.create(someNewPermissions, function(err) { 
...create 2 new Roles with someNewPermissions
})

In my init script just hung with no error. Just hung.

I back-downgraded to mongoose 3.6.20 and all is good again. 

I also created an issue in the mongoose-rbac github.

**Comment by vkarpov15** [comment]
Stale issue, re-open if this is still a problem
