### ISSUE TITLE
Exclude set on schema does not filter properties when using aggregate

### ISSUE THREAD

**Issue by mbell8903** [Automattic/mongoose#1782]
I'm not sure if this is intended so i figured i report this.  But when i have select: false set on a schema object, then use $project it brings back properties that have the select: false on them.

SCHEMA:
UserSchema = new Schema({
	username: {
		type: String,
		required: true,
		index: {
			unique: true,
			dropDups: true
		}
	},
	password: {
		type: String,
		required: true,
		select: false
	}
}),
AccountSchema = new Schema({
	users: [UserSchema]
});

QUERY:
Account.aggregate(
	{ $match: { _id: mongoose.Types.ObjectId(id) } },
	{ $unwind: '$users'},
	{ $project: { user: '$users' } }
, function (err, user) {
	...
});

This returns entire user objects when i would expect it would only return usernames.

**Comment by vkarpov15** [comment]
For posterity's sake, this is expected behavior. Mongoose does _not_ do any casting on aggregation results.
