### ISSUE TITLE
document get type casting not working with ObjectID

### ISSUE THREAD

**Issue by reneolivo** [Automattic/mongoose#1784]
Hello,

I'm doing the following:

schema.prototype.someMethod = function() {
    console.log(
        typeof this._id,
        typeof this.get('_id'),
        typeof this.get('_id', String),
        typeof this.get('_id', 'String')
    );
}

...
somedoc.someMethod();
...

this returns:
object object object object

Is type casting working? Or, am I doing something wrong?

What I want to accomplish is to compare 2 ObjectIds, but I want to cast them to string instead of using doc._id.equals( ... ) in case they are undefined.

Thank you.

**Comment by vkarpov15** [comment]
_ids are objects, you can compare them using `.toString()` or any `deepEquals()` check I've seen (like lodash or angular)

**Comment by reneolivo** [comment]
@vkarpov, thanks for the update!! (I have no idea about what I was doing here)
