### ISSUE TITLE
db operation blocked after "find" with corrupted mongo data 

### ISSUE THREAD

**Issue by zdwalter** [Automattic/mongoose#1797]
I am using mongoose 3.6.20.

with mongo shell find a corrupted record, it says:
Sat Nov 23 05:26:31 Assertion: 10320:BSONElement: bad type 31
0x5aca73 0x57e8e3 0x4bd676 0x4c8a45 0x573281 0x5ff9aa 0x601377 0x5f1905 0x5f64a1 0x5b706a 0x5b70f2 0x5b716e 0x57a53b 0x4b7ca5 0x4b095e 0x7f941f9b7ea5 0x4b3ca5 
 mongo(_ZN5mongo15printStackTraceERSo+0x23) [0x5aca73]
 mongo(_ZN5mongo11msgassertedEiPKc+0x93) [0x57e8e3]
 mongo(_ZNK5mongo11BSONElement4sizeEv+0x126) [0x4bd676]
 mongo(_ZNK5mongo7BSONObj8getFieldERKNS_10StringDataE+0x75) [0x4c8a45]
 mongo(_ZN5mongo16resolveBSONFieldEP9JSContextP8JSObjectljPS3_+0xc1) [0x573281]
 mongo(js_LookupPropertyWithFlags+0x1aa) [0x5ff9aa]
 mongo(js_GetProperty+0x77) [0x601377]
 mongo(js_Interpret+0x8925) [0x5f1905]
 mongo(js_Execute+0x231) [0x5f64a1]
 mongo(JS_EvaluateUCScriptForPrincipals+0x6a) [0x5b706a]
 mongo(JS_EvaluateUCScript+0x22) [0x5b70f2]
 mongo(JS_EvaluateScript+0x6e) [0x5b716e]
 mongo(_ZN5mongo7SMScope4execERKNS_10StringDataERKSsbbbi+0xfb) [0x57a53b]
 mongo(_Z5_mainiPPc+0x22d5) [0x4b7ca5]
 mongo(main+0x1e) [0x4b095e]
 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f941f9b7ea5]
 mongo() [0x4b3ca5]
Error: BSONElement: bad type 31

when I use mongoose to "find" data with this one retured, Mongoose gives an err object , but nothing in it. JSON.stringify(err) is "{}" .

mongoose.connection.on 'error' , can not catch this exception.

and all further mongoose operation will never return the callback function.

Work around:
when err return, manually drop current connection, and reconnect to mongodb.

**Comment by vkarpov15** [comment]
This is an issue with lodash in 3.x, it wouldn't clone object ids properly. Upgrade to lodash >= 4
