### ISSUE TITLE
String type: enum validation custom error message not working

### ISSUE THREAD

**Issue by petwho** [Automattic/mongoose#1800]
For no particular reason enum custom failed when I use this syntax: 

var enu = {
  values: 'opening open closing closed'.split(' '),
  message: 'enum validator failed for path `{PATH}` with value `{VALUE}`'
}
var s = new Schema({ state: { type: String, enum: enu })
var M = db.model('M', s)
var m = new M({ state: 'invalid' })
m.save(function (err) {
  console.error(String(err)) // ValidationError: enum validator failed for path `state` with value `invalid`
  m.state = 'open'
  m.save(callback) // success
});

Then I had to manual create custom error message object for String Type. But that doesn't sound ideal.

**Comment by dmgreene** [comment]
I can also confirm that this is broken in 3.4.  Can anyone tell me if it's been fixed in newer versions?

**Comment by vkarpov15** [comment]
Works in 4.0.7. Should be fine in 3.8.33 as well.
