### ISSUE TITLE
Mongoose doesn't shut down gracefully

### ISSUE THREAD

**Issue by rsteckler** [Automattic/mongoose#1807]
Mongoose never lets the node event loop clear, even after disconnect is called.  This stops node from exiting gracefully (i.e.  without calling process.exit())
Other server modules allow node to shutdown after it's respective .close() or .shutdown() is called, including Restify, Express, etc.
Mongoose, however, holds the application open.  

This application never exits:

```
//Boilerplate
var mongoose = require('mongoose');
var db = mongoose.connection;
db.on('error', function(err) {
	console.log('Mongoose connection error: ' + err);
});

//connect
mongoose.connect("localhost");

//disconnect
mongoose.disconnect();
```

**Comment by winduptoy** [comment]
+1, same issue. When MongoDB dies, Mongoose will not stop firing error events, blocking the thread.

**Comment by jjn2009** [comment]
This might be useful for narrowing down the problem:
```
var mongoose = require('mongoose');
var os = require('os');
console.log('mongoose ' + mongoose.version);
console.log('node ' + process.version);
console.log('os.type ' + os.type());
console.log('os.platform ' + os.platform());
console.log('os.arch ' + os.arch());
console.log('os.release ' + os.release());

var db = mongoose.connection;

db.on('error', function(err) {
    console.log('Mongoose connection error: ' + err);
    mongoose.disconnect();
});

db.once('open', function () {
    //Kill the MongoDB server here
    setTimeout(function() {
      mongoose.disconnect();
  },3000);
});

db.once('close', function () {
   console.log("Closed mongoose");
});

//Connect to the database
mongoose.connect("localhost");
```
I personally saw this occur on centos, but not osx or ubuntu.

**Comment by vkarpov15** [comment]
Hmmm @jjn2009 the above code shuts down properly for me on 3.6.17 as well. But if it works for you on 3.8.20 I'd recommend upgrading, the 3.6.x branch hasn't been maintained for a while.

**Comment by jbach** [comment]
This is still an issue for me. Mongoose 5.0.4, Node 4.2.1.
After running `disconnect()`, the process keeps running. Is this the same issue as https://github.com/Automattic/mongoose/issues/3358?

**Comment by vkarpov15** [comment]
@jbach are you running against a replica set? Or a standalone?

**Comment by pkantsedalov** [comment]
I have the similar issue.
Using **Node.JS 6.3.0** and **Mongoose 4.5.3** I couldn't catch the case when I stop mongod process - the only result is the exit from a running app. I tried server options (auto_reconnect etc.) and handlers for **disconnected**, **close** etc.

**Comment by vkarpov15** [comment]
Please provide code samples

**Comment by pkantsedalov** [comment]
[vkarpov15](https://github.com/vkarpov15) it's [here](https://github.com/Automattic/mongoose/issues/4368)

**Comment by Smilebags** [comment]
This doesn't seem to be fixed. I am starting up a DB connection in tests and the test process is never ending. I am calling mongoose.disconnect() in my teardown but it doesn't exit. The callback function is never run.

**Comment by vkarpov15** [comment]
@Smilebags can you please open up a separate issue with code samples please?
