### ISSUE TITLE
.select doesn't work with .slice

### ISSUE THREAD

**Issue by phillipb** [Automattic/mongoose#1808]
When performing a slice, the select portions of the query is ignored. Instead of only returning the selected field, it returns the entire document. 

```
this.model.find({_id: req.params['id']})
      .select('comments')
      .where('comments')
      .slice('comments', 2)
      .populate('comments.user')
      .exec(function(err, items) {
        console.log(arguments)
        respond(res, null, items)
      })
```

**Comment by juanmaia** [comment]
+1. thanks @phillipb your solution worked well here!

**Comment by vkarpov15** [comment]
Unfortunately this is a quirk with the mongodb server - it doesn't treat `$slice` as an inclusive projection. Below is the shell's behavior:

```
> db.x.insert({ v: 1, t: [1,2,3] });
WriteResult({ "nInserted" : 1 })
> db.x.find()
{ "_id" : ObjectId("55ce08397e9436b6398c81f7"), "v" : 1, "t" : [ 1, 2, 3 ] }
> db.x.find({}, { t: { $slice: 2 } });
{ "_id" : ObjectId("55ce08397e9436b6398c81f7"), "v" : 1, "t" : [ 1, 2 ] }
```

To work around this, specify an explicit inclusive or exclusive projection as @phillipb suggested.
