### ISSUE TITLE
The populate option limit function doesn't work with find()

### ISSUE THREAD

**Issue by wondersofttech** [Automattic/mongoose#1828]
The populate limit function doesn't work with find
it only works with findOne
This is my code of find function when using populate
<code>
var TestPostSchema = new Schema({
    title: String,
    likes: [{
        _id: {
            type: Schema.ObjectId,
            ref: 'TestUser'
        }
    }],
}, {
    collection: 'testPost'
});
var TestUserSchema = new Schema({
    username: String,
}, {
    collection: 'testUser'
});
mongoose.model('TestPost', TestPostSchema);
mongoose.model('TestUser', TestUserSchema);
</code>
 I insert data into database as follows
<code>
var user1 = new TestUser({
    username: 'user1'
});
user1.save();
var user2 = new TestUser({
    username: 'user2'
});
user2.save();
var user3 = new TestUser({
    username: 'user3'
});
user3.save();
var post1 = new TestPost({
    title: 'title 1'
});
post1.likes.push(user1, user2, user3);
post1.save();
var post2 = new TestPost({
    title: 'title 2'
});
post2.likes.push(user1, user2, user3);
post2.save();
var post3 = new TestPost({
    title: 'title 3'
});
post3.likes.push(user1, user2, user3);
post3.save();
After that, I find database
TestPost.find({})
    .populate('likes._id', 'username', {}, {
        limit: 1
    })
    .lean().exec(function(error, posts) {
        res.jsonp(posts);
    });
</code>
and the result like as follows, notice that i limited populate at 1, I just want to get 1 populate, but it returns 3 ones, please check again fix quickly if it has errors, my current mongoose version is 3.8.1 và mongodb 2.4.5
<code>
[{
    "title": "title 1",
    "_id": "52a53dff649401c01d000004",
    "likes": [{
        "_id": {
            "username": "user1",
            "_id": "52a53dff649401c01d000001"
        }
    }, {
        "_id": {
            "username": "user2",
            "_id": "52a53dff649401c01d000002"
        }
    }, {
        "_id": {
            "username": "user3",
            "_id": "52a53dff649401c01d000003"
        }
    }],
    "__v": 0
}, {
    "title": "title 2",
    "_id": "52a53dff649401c01d000005",
    "likes": [{
        "_id": {
            "username": "user1",
            "_id": "52a53dff649401c01d000001"
        }
    }, {
        "_id": {
            "username": "user2",
            "_id": "52a53dff649401c01d000002"
        }
    }, {
        "_id": {
            "username": "user3",
            "_id": "52a53dff649401c01d000003"
        }
    }],
    "__v": 0
}, {
    "title": "title 3",
    "_id": "52a53dff649401c01d000006",
    "likes": [{
        "_id": {
            "username": "user1",
            "_id": "52a53dff649401c01d000001"
        }
    }, {
        "_id": {
            "username": "user2",
            "_id": "52a53dff649401c01d000002"
        }
    }, {
        "_id": {
            "username": "user3",
            "_id": "52a53dff649401c01d000003"
        }
    }],
    "__v": 0
}]
</code>

**Comment by paglias** [comment]
Same issue here with 4.1.1 and mongodb 2.6.4

Actually for us it stopped working after upgrading to 4.1.1 (same mongodb version)

**Comment by vkarpov15** [comment]
@paglias can you show your code?

**Comment by paglias** [comment]
@vkarpov15 sure,

the basically is this

````js
Group
    .findOne(...)
    .populate({path: 'members', select: 'profile.name', options: {limit: 15} })
    .exec()
```

if you think this might be useful, the exact code can be fund here https://github.com/HabitRPG/habitrpg/blob/paglias/tasks-collection/website/src/controllers/groups.js#L136

**Comment by paglias** [comment]
If you want to replicate, you can fork that branch and run `mocha test/api/groups.coffee`, we add 17 users to a group and should only return the first 15, instead we get all 17

**Comment by vkarpov15** [comment]
@paglias sorry for taking so long to respond to this, it got lost among a few stale issues. I can't quite find the test file you're talking about, but the below script:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh1828');

var User = mongoose.model('User', { name: String });
var Group = mongoose.model('Group', { members: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }] });

var users = [];
for (var i = 0; i < 17; ++i) {
  users.push({ name: 'user' + i });
}

User.create(users, function(error, docs) {
  assert.ifError(error);

  var _ids = [];
  for (var i = 0; i < docs.length; ++i) {
    _ids.push(docs[i]._id);
  }

  var group = new Group({ members: _ids });
  group.save(function(error) {
    assert.ifError(error);
    Group.findOne({ _id: group._id }).populate({ path: 'members', options: { limit: 15 } }).exec(function(error, doc) {
      assert.ifError(error);
      assert.equal(doc.members.length, 15);
      console.log('done');
      process.exit(0);
    });
  });
});
````

executes without error for me in mongoose 4.2.5.

**Comment by paglias** [comment]
@vkarpov15  thanks, Don't worry about this, I only got to replicate this locally, run without problems in production do it's fine :)

**Comment by vkarpov15** [comment]
Alright, I'll close this for now. Re-open if you find this is still causing problems.

**Comment by SevenSinS02** [comment]
This might be of some use to someone but what I've found in newer versions of mongoose(4.4.13)  is that putting limit outside of populate seems to work as expected.

Group
    .findOne(...)
    .populate('members','profile.name').limit(5).lean().
    .exec()
