### ISSUE TITLE
Read preference does not seem to be working

### ISSUE THREAD

**Issue by ryanogle** [Automattic/mongoose#1833]
I was on an older version of mongoose and mongo driver (mongoose@3.6.4 & mongodb@1.2.14), and since upgrading to the newest version (mongoose@3.8.1 & mongodb@1.3.23) my read preference set on the collection level no longer seems to work.  I also tried to set it on the query level, and it doesn't seem to work:

        User.find({
          my_field: {
            $in: my_ids
          }
        }, my_fields, function (err, results) {
          cb(err, results);
        }).read('secondary');

Everything seems to be going to the primary.  Rolling back to the old versions shows the expected behavior - queries going to the secondary.

I also tried to follow exactly the mongoose api docs:

        var query = User.find({
          my_field: {
            $in: my_ids
          }
        }, my_fields ).read('secondary');
        
        query.exec(function (err, result) {
          cb(err, result);
        });

And same result, queries going to primary only.  When I roll back to 3.6.4, reads start going to the secondaries (I'm setting the read preference on the collection).

**Comment by vkarpov15** [comment]
Stale issue, re-open if this is still a problem.
