### ISSUE TITLE
404 Not Found on Mongoose-3.8.3.tgz

### ISSUE THREAD

**Issue by rolandp** [Automattic/mongoose#1840]
When trying to npm install the MEAN stack the installer fails on Mongoose-3.8.3.tgz saying it cannot be found. Did something went wrong with the update 2 hours ago?

**Comment by rkumar552** [comment]
I am getting same error while installing mangoose on windows 8.1 through npm. I tried to setting the mirror but that is also gettting timed out.

>npm install mangoose
npm ERR! Windows_NT 6.3.9600

npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E404

npm ERR! 404 Not Found: mangoose
npm ERR! 404
npm ERR! 404 'mangoose' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yoursel

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rakumar\NodeJS\Node\npm-debug.log

**Comment by rolandp** [comment]
@rkumar552 Try mongoose instead of mangoose

**Comment by rkumar552** [comment]
Thanks Roland. It worked, I am first time user and couldn't catch the typo.  
Date: Sun, 5 Apr 2015 02:57:23 -0700

**Comment by kumarutsav111** [comment]
I am still getting same error:
Kumars-MacBook-Air:demoapi kumarutsav$ npm install mangoose --save
npm ERR! code E404
npm ERR! 404 Not Found: mangoose@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kumarutsav/.npm/_logs/2019-05-01T04_54_25_029Z-debug.log

**Comment by rolandp** [comment]
> I am still getting same error:
> Kumars-MacBook-Air:demoapi kumarutsav$ npm install mangoose --save
> npm ERR! code E404
> npm ERR! 404 Not Found: mangoose@latest
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/kumarutsav/.npm/_logs/2019-05-01T04_54_25_029Z-debug.log

@kumarutsav111 Funny, it's the same mistake you made 4 years ago. Try mongoose instead of mangoose
