### ISSUE TITLE
Unexpected behavior when using model.findOne().remove()

### ISSUE THREAD

**Issue by damphat** [Automattic/mongoose#1851]
```
User.findOne({age: 30}).remove(callback);
```

As I expected, the code above would remove 1 user but it remove all users with age = 30

I know `User.findOneAndRemove()` work fine, but why `User.findOne().remove()` have different result?

**Comment by hasezoey** [comment]
`remove` has been deprecated in both the mongodb driver and mongoose, instead `deleteOne` or `deleteMany` should be used, which should address this issue.

Is this issue still relevant @vkarpov15?

**Comment by vkarpov15** [comment]
@hasezoey nope, I'll close this one
