### ISSUE TITLE
mark has "not modified" on doc

### ISSUE THREAD

**Issue by larafale** [Automattic/mongoose#1854]
I've been through the entire API but still
In a `pre('save')` ,if one of my field is modified `doc.isModified('myField')`

how can we mark that field as not modified in order to remove that field in the update query. I don't want to remove the field in the db with `doc.myField = undefined`, just omit the save on that field.

a good way wood be `doc.markNotModified('field')`

any idea ?
thanks

**Comment by onbjerg** [comment]
Is this still something we want? I could go ahead and implement it @vkarpov15

**Comment by vkarpov15** [comment]
@onbjerg go for it, any help would be much appreciated.

**Comment by vkarpov15** [comment]
Fixed in 4.5.0.

**Comment by adamreisnz** [comment]
Note that for people finding this issue, the method is actually called `unmarkModified()`

**Comment by vkarpov15** [comment]
Thanks @adamreisnz
