### ISSUE TITLE
Discriminator support for Sub-Documents

### ISSUE THREAD

**Issue by ElliotChong** [Automattic/mongoose#1856]
Starting a feature request to allow discriminator use within sub-documents.

Playing around with a possible API:

``` coffeescript
class EmployeeSchema extends Schema
    constructor: ->
        super

        @add
            name: { type: String, required: true }
            salary: { type: Number }

class ManagerSchema extends EmployeeSchema
    constructor: ->
        super

        @add
            subordinates: { type: Number }

        @method
            salaryPerSubordinate: ->
                @salary / @subordinates

# Discriminators can only be set once a Model has been defined; however, sub-documents
# only use Schemas.
# Not sure what the best way to handle this is since defining it at the Model level makes
# sense when not worrying about sub-documents and the distinction between the two
# methods wouldn't be intuitive.
EmployeeSchema.discriminator 'Manager', ManagerSchema

class CompanySchema extends Schema
    @add
        name: { type: String, required: true }
        employees: [ new EmployeeSchema() ]

Company = mongoose.model 'Company', new CompanySchema()
acmeInc = new Company { name: "Acme Inc." }

# Discriminator is inferred through the definition of the dsciriminatorKey '__t'
acmeInc.employees.push { __t: "Manager", name: "Roger Rabbit", salary: 0.01, subordinates: 5 }

# No discriminator is inferred, defaults to Employee
acmeInc.employees.push { name: "Road Runner", salary: 2 }

# Perhaps the 'create' method accepts a discriminator as an optional parameter, or we could
# fall back to requiring the discriminatorKey to be manually defined like in the push example
coyote = acmeInc.employees.create "Manager", { name: "Coyote", salary: 500, subordinates: 3 }
console.log coyote.salaryPerSubordinate()

acmeInc.employees.push coyote

# Sub-documents are cast to their respective discriminated Schema
for employee in acmeInc.employees
    switch employee.__t
        when "Manager"
            console.log employee.name, employee.salary, employee.salaryPerSubordinate()
        else
            console.log employee.name, employee.salary
```

**Comment by UltCombo** [comment]
+1 for this feature!

**Comment by derickbailey** [comment]
@vkarpov15 thanks for putting this on the roadmap! this is something that will make my life significantly easier, as I'm dealing with varying data structures in sub-documents.

**Comment by vbogdanov** [comment]
+1

**Comment by unusualbob** [comment]
+1

**Comment by jonstorer** [comment]
nidge

**Comment by mathieug** [comment]
+1

**Comment by ducdigital** [comment]
+1, this need to be done <3

**Comment by ducdigital** [comment]
By the way any progress for this? Is there any other work around or method that can implement this behavior without touching the mongoose core?

Thanks!

**Comment by gflandre** [comment]
+1 for this feature!

**Comment by ducdigital** [comment]
@vkarpov15: I did take liberty to create a small module to have this feature implement on custom Schema:

Here is the gist: https://gist.github.com/ducdigital/cb0926f1a27127369813 (contains the module and test file)

The sample usage is in the test file.

This works in most of the case except there are some downsides:
- Cannot have `required` validation in children attributes
- Cannot have different type on the same attribute name. 

Let me know what do you think about this module. 
My main concern right now is to able to have custom validation on different schema. I am thinking of generating `.pre('save')` to validate those document. Are there any better way?

**Comment by vkarpov15** [comment]
I think `pre('save');` is the only way to do it. [That's how we do validation for subdocs anyway](https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L200-L277)

**Comment by mitsos1os** [comment]
+1 for this feature

**Comment by Fonger** [comment]
+1

**Comment by davebaol** [comment]
+1 
I'd say that this feature is crucial for any non-trivial data model :)

**Comment by vkarpov15** [comment]
@davebaol hahah you and I have very different ideas about what non-trivial means :)

**Comment by davebaol** [comment]
@vkarpov15 
Well, in this context non-trivial is clearly a [hyperbole](https://en.wikipedia.org/wiki/Hyperbole) :wink: 
And regardless of the context it's a [litotes](https://en.wikipedia.org/wiki/Litotes) too :bowtie:

Anyways, figures of speech aside, I really appreciate your hard work on mongoose. :+1: 
Just wanted to say that this is likely the most important feature among missing ones. :innocent:

**Comment by vkarpov15** [comment]
Thanks for the kind words :beers: it's definitely a priority, just not for the next 2 months.

**Comment by davebaol** [comment]
Great! Sounds like a plan :sunglasses:

**Comment by whitef0x0** [comment]
Is this close to completion?

**Comment by vkarpov15** [comment]
@whitef0x0 no progress thus far, contributions welcome.

**Comment by davebaol** [comment]
@vkarpov15 
Sweet! 
Is there any documentation on this?

**Comment by vkarpov15** [comment]
Working on a blog post about it to consolidate my thoughts and then going to put that into doc form. https://github.com/Automattic/mongoose/pull/4910/files#diff-391b023b3deb2ee3a2fe9a2ffe802070 has a test case that you can extrapolate the general idea from.

**Comment by davebaol** [comment]
@vkarpov15 
Thanks, just found your [blog post about embedded discriminators](http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html)

**Comment by vkarpov15** [comment]
Thanks for posting @davebaol

**Comment by meammeiam** [comment]
I tried this tonight from the blog and was wondering how you add another event once the Batch is created?

I tried pushing an event, but it saves an empty item.

`Batch.create(batch).then(function(doc) {
    
    doc.events.push({ kind: 'Purchased', product: 24 });
    doc.save().then(function(doc) {
        console.log(doc);
    });
    
});`

I also tried create and it returns an empty item.

`console.log(doc.events.create({ kind: 'Purchased', product: 24 }));`

**Comment by vkarpov15** [comment]
@meammeiam that should work, if it doesn't that's a bug. Please open up a separate issue

**Comment by meammeiam** [comment]
Okay, well maybe I need to upgrade mongoDB. I'm at version 3.3.6. I'll have to compile it from source. Mongoose is at  4.8.4. If it's still not working, I'll open a bug. Thank you!

**Comment by vkarpov15** [comment]
Don't use mongodb 3.3.x, that's an unstable dev release. Please use 3.2.x or 3.4.x

**Comment by c1moore** [comment]
Is there a similar feature for normal embedded documents that do not appear in an array?  Using the notation in your blog, I would want something like the below.

```
const EventSchema = new Schema({ message: String });
const SomeSchema = new Schema({ event: EventSchema });

SomeSchema.path('event').discriminator('Clicked', new Schema({
  element: {
    type: String,
    required: true
  }
}));

SomeSchema.path('event').discriminator('Purchased', new Schema({
  product: {
    type: String,
    required: true
  }
}));

const Something = mongoose.model('Something', SomeSchema);
```

Should I open a new issue for that?

**Comment by davebaol** [comment]
> Is there a similar feature for normal embedded documents that do not appear in an array?

No, currently there's no such feature as discriminators in single nested subdocuments.

> Should I open a new issue for that?

No, you should not because there is an open issue already, see https://github.com/Automattic/mongoose/issues/5244
Maybe add your comment or just a '+1' there 😉
