### ISSUE TITLE
Make queries compatible with koa and yield keyword

### ISSUE THREAD

**Issue by capaj** [Automattic/mongoose#1859]
According to this [article](http://tamas.io/replacing-express-with-koa/) it is not possible to use mongoose with yield keyword to get rid of callbacks. Could this be addressed in Mongoose 4.0.0?

**Comment by neverfox** [comment]
Since thunks are on the way out of `co`, you can always promisify `save` with e.g. bluebird:

```
yield Promise.promisify(model.save, model)();
```
