### ISSUE TITLE
CastError when saving populated object

### ISSUE THREAD

**Issue by jonaswindey** [Automattic/mongoose#1865]
I have a PageTemplate model that contains a collection of PageSettings by reference:

```
var PageTemplateSchema = new Schema({
    label: {
        type: String,
        default: '',
        trim: true
    },
    settings: [{
        setting: {
            type: Schema.ObjectId,
            require: true,
            ref: 'PageSetting'
        },
        seq: {
            type: Number,
            default: 1
        }
    }]
});

var PageSettingSchema = new Schema({
    label: {
        type: String,
        default: '',
        trim: true
    },
    type: {
        type: String,
        default: '',
        trim: true
    }
});
```

When I get a PageTemplate and push a new id from PageSetting to the settings array, I can update the model succesfully.

However, when I get the PageTemplate with population of settings.setting, I get a CastError when saving (even without even touching the object), saying mongoose can't cast the [object Object] to ObjectId, because the id's are replaced by their real objects.

What's the best way to prevent this? Is there a way to "unpopulate" referenced objects before saving?

**Comment by vkarpov15** [comment]
@xpepermint what is `db` in your schema example?
