### ISSUE TITLE
schema inheritance?

### ISSUE THREAD

**Issue by tommedema** [Automattic/mongoose#1878]
I've got the following kind of object structure:

    restaurant
    - menu
    -- menucategory
    --- menuitem
    -- menuitem
    -- menuitem
    -- menucategory
    --- menuitem
    --- menucategory
    ---- menuitem
    ---- menuitem

Basically, the restaurant Schema has a field `menu`, which is an array with either `menucategory`s or `menuitem`s. Furthermore, `menucategory`s can have child `menucategory`s or child `menuitem`s.

How can I define this in a schema, such that validation etc. functions as usual?

Ideally I would like to create different schemas:

* restaurant schema
* menu schema
* menucategory schema
* menuitem schema

Where each schema includes the other schemas.

Is something like this possible? I looked at discriminators but they seem to be made for another purpose.

**Comment by lledey** [comment]
I have the exact same problem. Is there any solution for that ?

**Comment by vkarpov15** [comment]
@lledey code sample please?

**Comment by lledey** [comment]
@vkarpov15 It was an issue with another dependency, not mongoose. Sorry for the noise.

**Comment by vkarpov15** [comment]
Glad you fixed it. I'm gonna close this since this issue's state, re-open if this is still an issue.
