### ISSUE TITLE
SSL connection issue with Mongoose 1.8.4

### ISSUE THREAD

**Issue by christkv** [Automattic/mongoose#1882]
Hi

https://jira.mongodb.org/browse/NODE-101

there seems to be a SSL connection issue for replicasets for Mongoose but not with the 1.3.23 driver so something weird is going on. I've added as much detail to the NODE-101 ticket as I have, if you need anything more let me know.

**Comment by koreanilkumar** [comment]
Hi all,
Above stesp for NodeJS to mongoose connection is worked for me too, looking for the same ssl connection in python. How can I do that?

**Comment by vkarpov15** [comment]
@koreanilkumar not the right place to ask that, we don't do python here :) [JIRA](https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-1446?filter=allopenissues) is where you should report bugs with the mongodb python driver
