### ISSUE TITLE
key $in must not start with '$'

### ISSUE THREAD

**Issue by klimashkin** [Automattic/mongoose#1884]
After update from 3.8.3 to 3.8.4 such error message returns on remove with $in
`commentsModel.remove({cid: {$in: [123]}}, this)`
In mongodb console such query work success

**Comment by eladnava** [comment]
In case anyone stumbles upon this issue again, update your Mongoose package. I was using `3.8.8` and when I updated to `4.1.7` the problem was rectified.

**Comment by spandey1296** [comment]
appName":"seneca","err":{"type":"Error","message":"key $ne must not start with '$'","stack":"Error: key $ne must not start with '$'\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:915:19)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:727:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)\n    at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:126:22)\n    at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:118:33)\n    at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:104:25)\n    at serializeCommand (/app/node_modules/mongodb/lib/core/connection/pool.js:780:41)\n    at Pool.write (/app/node_modules/mongodb/lib/core/connection/pool.js:928:3)\n    at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:128:10)\n    at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)\n    at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:47:3)\n    at Object.insert (/app/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)\n    at Server.insert (/app/node_modules/mongodb/lib/core/topologies/server.js:698:23)\n    at Server.insert (/app/node_modules/mongodb/lib/topologies/topology_base.js:301:25)\n    at insertDocuments (/app/node_modules/mongodb/lib/operations/common_functions.js:259:19)\n    at InsertOneOperation.execute (/app/node_modules/mongodb/lib/operations/insert_one.js:26:5)\n    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:77:17)\n    at Collection.insertOne (/app/node_modules/mongodb/lib/collection.js:516:10)\n    at NativeCollection.(anonymous function) [as insertOne] (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:180:28)\n    at model.Model.$__handleSave (/app/node_modules/mongoose/lib/model.js:275:33)\n    at model.Model.$__save (/app/node_modules/mongoose/lib/model.js:340:8)"},"methodName":"insert","fileName":"mongo-dao.js"}
0|www  | {"level":50,"time":1651208637192,"pid":17,"hostname":"node-seneca-76f7d9bbf4-xzt9f","appName":"seneca","err":{"type":"Error","message":"key $ne must not start with '$'","stack":"Error: key $ne must not start with '$'\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:915:19)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:727:17)\n    at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)\n    at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)\n    at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)\n    at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:126:22)\n    at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:118:33)\n    at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:104:25)\n    at serializeCommand (/app/node_modules/mongodb/lib/core/connection/pool.js:780:41)\n    at Pool.write (/app/node_modules/mongodb/lib/core/connection/pool.js:928:3)\n    at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:128:10)\n    at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)\n    at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:47:3)\n    at Object.insert (/app/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)\n    at Server.insert (/app/node_modules/mongodb/lib/core/topologies/server.js:698:23)\n    at Server.insert (/app/node_modules/mongodb/lib/topologies/topology_base.js:301:25)\n    at insertDocuments (/app/node_modules/mongodb/lib/operations/common_functions.js:259:19)\n    at InsertOneOperation.execute (/app/node_modules/mongodb/lib/operations/insert_one.js:26:5)\n    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:77:17)\n    at Collection.insertOne (/app/node_modules/mongodb/lib/collection.js:516:10)\n    at NativeCollection.(anonymous function) [as insertOne] (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:180:28)\n    at model.Model.$__handleSave (/app/node_modules/mongoose/lib/model.js:275:33)\n    at model.Model.$__save (/app/node_modules/mongoose/lib/model.js:340:8)"},"methodName":"consume","fileName":"audit_queue_log_service.js"}
0|www  | Error: key $ne must not start with '$'
0|www  |     at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:915:19)
0|www  |     at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|www  |     at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|www  |     at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|www  |     at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|www  |     at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|www  |     at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:727:17)
0|www  |     at serializeObject (/app/node_modules/bson/lib/bson/parser/serializer.js:347:18)
0|www  |     at serializeInto (/app/node_modules/bson/lib/bson/parser/serializer.js:941:17)
0|www  |     at BSON.serialize (/app/node_modules/bson/lib/bson/bson.js:64:28)
0|www  |     at Msg.serializeBson (/app/node_modules/mongodb/lib/core/connection/msg.js:126:22)
0|www  |     at Msg.makeDocumentSegment (/app/node_modules/mongodb/lib/core/connection/msg.js:118:33)
0|www  |     at Msg.toBin (/app/node_modules/mongodb/lib/core/connection/msg.js:104:25)
0|www  |     at serializeCommand (/app/node_modules/mongodb/lib/core/connection/pool.js:780:41)
0|www  |     at Pool.write (/app/node_modules/mongodb/lib/core/connection/pool.js:928:3)
0|www  |     at _command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:128:10)
0|www  |     at command (/app/node_modules/mongodb/lib/core/wireprotocol/command.js:28:5)
0|www  |     at writeCommand (/app/node_modules/mongodb/lib/core/wireprotocol/write_command.js:47:3)
0|www  |     at Object.insert (/app/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)
0|www  |     at Server.insert (/app/node_modules/mongodb/lib/core/topologies/server.js:698:23)
0|www  |     at Server.insert (/app/node_modules/mongodb/lib/topologies/topology_base.js:301:25)
0|www  |     at insertDocuments (/app/node_modules/mongodb/lib/operations/common_functions.js:259:19)
0|www  |     at InsertOneOperation.execute (/app/node_modules/mongodb/lib/operations/insert_one.js:26:5)
0|www  |     at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:77:17)
0|www  |     at Collection.insertOne (/app/node_modules/mongodb/lib/collection.js:516:10)
0|www  |     at NativeCollection.(anonymous function) [as insertOne] (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:180:28)
0|www  |     at model.Model.$__handleSave (/app/node_modules/mongoose/lib/model.js:275:33)
0|www  |     at model.Model.$__save (/app/node_modules/mongoose/lib/model.js:340:8)

**Comment by Uzlopak** [comment]
Keys in mongo are not allowed in Mongo as they are indicating that they are an mongo operator. So if you try to store a Document with a key $ne it will not work.
