### ISSUE TITLE
Nested fields & default value: cannot create a default on a subobject: must specify default on each final field

### ISSUE THREAD

**Issue by triccardi-systran** [Automattic/mongoose#1885]
It would be great to be able to set a default value for a subobject, like this:

```javascript
var defaultParent = { child1: 1, child2: '2' };
var mySchema = new Schema({
  parent: {
    child1: Number,
    child2: String,
    default: defaultParent
  }
});
```

Currently we must do this:
```javascript
var defaultParent = { child1: 1, child2: '2' };
var mySchema = new Schema({
  parent: {
    child1: { type: Number, default: defaultParent.child1 },
    child2: { type: String, default: defaultParent.child2 }
  }
});
```

The proposed syntax is just and example and is not great: there is a risk of collision with a user subfield named `default`. In fact this risk already exists with `type`, and is somewhat mitigated in `.add()`:
to test if it's a subfield and not a final/leaf field we check if `.type` doesn't exist or if `.type.type` exists (afaik it's not document, it definitely should, see issue #1886).

Maybe we should use a new `type: 'nested'`, alongside the default and the nested definition:
```javascript
var defaultParent = { child1: 1, child2: '2' };
var mySchema = new Schema({
  parent: { 
    type: 'nested',
    default: defaultParent,
    nested: {
      child1: Number,
      child2: String
    }
  }
});
````

**Comment by syuilo** [comment]
+1

**Comment by vkarpov15** [comment]
You should be able to do this with single embedded docs in 4.2.0
