### ISSUE TITLE
Inline transform after a populate seems to pull in the the populated model

### ISSUE THREAD

**Issue by wprater** [Automattic/mongoose#1891]
I have to do a two phase populate to get my nested models loaded.  After they have loaded I need to perform an inline transform so I can protect some data depending on who was requesting the data.

I've put together a quick gist and you can see on the highlighted line which should be the person object is actually the last populated object.  If I don't use a custom transform and just use a default one it's correct.  I do not have any schema level transforms in place on these models.

https://gist.github.com/wprater/8571047#file-person-js-L26

Not certain if this is a bug or intended behavior, but it's very strange.

**Comment by vkarpov15** [comment]
Intended behavior - inline transform will be applied for all subdocs.
