### ISSUE TITLE
mongoose markModified not working on multi level paths

### ISSUE THREAD

**Issue by joeandrews** [Automattic/mongoose#1905]
I have a schema with the a field exceptions, which has the schema type mixed.
The exceptions field is a multi level object of objects. I am marking all the paths that are modified in the object but the result is not saving.

Before the save i loop through the deep level key i know is modified and  do this.

```
_.forOwn(user.exceptions[date][mealTime], function(value, key) {
                    user.markModified('exceptions.' + date + '.' + mealTime + '.' + key);
                });
```

The output of user.modifiedPaths() is as follows.

```
[ 'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.meals',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.email',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.city',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.time',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.address',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.phone',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.zip',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.address2',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.instructions',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.date',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.type',
  'exceptions',
  'exceptions.2014-01-28',
  'exceptions.2014-01-28.dinner',
  'exceptions.2014-01-28.dinner.cancelled' ]
```

I realise I can achieve the above through an update query, but I really want to use the post save hook.

Thanks

Joe

**Comment by priyankinfinnov** [comment]
Any Updates? facing the same !

**Comment by vkarpov15** [comment]
@priyankinfinnov can you please provide more detail on the issue you're facing? I think the answer to OP's post is just `markModified('exceptions')`, no need to mark everything underneath as modified, as long as the child properties are [enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties)

**Comment by priyankinfinnov** [comment]
@vkarpov15 Figured out the Date format of a lower level was wrong. 
Was trying to assign date.ISOString() but then worked when i directly assigned Date object.
