### ISSUE TITLE
Expose underlying cursor object for finds

### ISSUE THREAD

**Issue by yoitsro** [Automattic/mongoose#1908]
It would be great if the underlying cursor could be exposed in the final callback.

Why?
Currently, the way pagination is generally performed is pretty primitive: a count operation, followed by a find with skip and limit parameters. The count is performed so that the client can decide if there are more products to load or not.

For most cases, this is fine. However, for more complex queries, the count takes a long time. For example, when counting with a $nin, indexes become useless. See http://docs.mongodb.org/manual/faq/indexes/#using-ne-and-nin-in-a-query-is-slow-why for more details.

A classic use case of why a $nin query needs to be used is when a user has chosen to hide a certain item in a master collection (i.e. a collection of products). This master collection then needs to be queried with a $nin operator.

Cursors
By exposing the underlying cursor for an operation, we're given access to the hasNext property indicating whether or not there are more items in the queried collection. This property can then be used to inform the client whether or not there are more items available.

**Comment by arasmussen** [comment]
+1 want hasNext

**Comment by jaceechan** [comment]
+1 want hasNext

**Comment by dahannes** [comment]
+1 want hasNext

**Comment by vkarpov15** [comment]
http://thecodebarbarian.com/cursors-in-mongoose-45.html will be available in 4.5.0

**Comment by mleanos** [comment]
I'm very happy to see the introduction of the Cursor API in Mongoose. I can see many great uses for it.

However, in the current context of pagination, I'm having a hard time seeing the usefulness of the `hasNext` property of the underlying cursor. While we can use it to tell the client that we still have more pages to come, how would we indicate how many more items & pages are in the collection without an exact count? Unless we're relying on client-side logic to keep fetching until we've exhausted the collection query results. Thus, sending each item back to the client one at a time. Would this be the suggested approach?

I'm currently struggling with coming up with a scaleable & performant solution to pagination using Mongoose; currently, I'm using a count query (based on a query with a filter), and a `limit()` & `skip()` query. Pretty much as described in this OP.

See this MEANJS pull-request for reference: [feat(articles): Server-side paging for list](https://github.com/meanjs/mean/pull/1263).

Would this type of use case benefit from Streaming? If so, what would that look like?

**Comment by vkarpov15** [comment]
TBH cursors are not terribly useful for pagination, you should just stick
with skip and limit. If you need extra perf and can sacrifice actual
pagination in favor of prev / next buttons and extra work, you can just use
$gt and limit.
