### ISSUE TITLE
Multiple schema in one collection

### ISSUE THREAD

**Issue by gvaish** [Automattic/mongoose#1913]
What's the best way to include multiple schema in one collection and query the union of the documents?

For example:

    var schemaOne = new Schema({ "stype": { type: String, default: "one" }, "myid": String, "f1": String });
    var schemaTwo = new Schema({ "stype": { type: String, default: "two" }, "myid": String, "f2": String });

    var One = mongoose.schema('one', schemaOne, 'coll');
    var Two = mongoose.schema('two', schemaTwo, 'coll');

I can always query:

    One.find({ ... });
    Two.find({ ... });

Is it possible to find using something like:

     mongoose.find( { "in": [ One, Two ] }, { "myid": "myvalue" })

Or

     mongoose.find( { "collection": "coll" }, { "myid": "myvalue" })

**Comment by vkarpov15** [comment]
Discriminators http://mongoosejs.com/docs/discriminators.html
