### ISSUE TITLE
Populate with field defined using type directive

### ISSUE THREAD

**Issue by whitecolor** [Automattic/mongoose#1921]
I property is defined using "type" directive populate path should contain type also.

I have a mongoose schema:

```javascript
  mongoose.Schema({
    state: {
        type: {
           action: 'string' , 
           user: {type: mongoose.Schema.Types.ObjectId, 
           ref: 'User'}, 
           at: 'date'
       },
   default: {}
   },})
```

I tried to populate it:

```javascript
Model.findById(id).populate('state.user').populate('log.user').exec(cb)
```
In query result "user" field of log items is populated correctly and "state.user" is null. So I found out that I either sould use path 'state.type.user' or not use type to define attribute in schema. I think in pupulate properties defined with "type" should be treated like without "type" - in this case 'state.user'.

**Comment by Jeff-Lewis** [comment]
See http://mongoosejs.com/docs/guide.html#typeKey
