### ISSUE TITLE
Create and then populate?

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#1928]
Is it possible to do something like this...?

```js
db.model('User').create({ name: 'John' }).populate('_company').exec(function(err, user) {
    if (err) return next(err)
    console.log(user)
    // outputs user with populate user._company object from Company model
})
```

The only way I see it working now is...

```js
db.model('User').create({ name: 'John' }, function(err, user) {
  if (err) return next(err)
  db.model('User').findById(user._id).populate('_company').exec(function(err, user) {
    if (err) return next(err)
    console.log(user)
    // outputs user with populate user._company object from Company model
  })
})
```

**Comment by TrejGun** [comment]
try this

```
model.findOneAndUpdate({_id:mongoose.Types.ObjectId()}, data, {
new: true,
upsert: true,
runValidators: true,
setDefaultsOnInsert: true,
populate: options
})
```

**Comment by jericopulvera** [comment]
@TrejGun won't this be slow if there's lot of documents? since it'll check the _id 1 by 1 if mongoose.Types.ObjectId() exists right?

**Comment by vkarpov15** [comment]
@jericopulvera  sure, but you can use Model.populate to populate all the created documents, that will use one query: https://mongoosejs.com/docs/api.html#model_Model.populate

`Company.populate(docs, { path: '_company' })`

**Comment by mienaikoe** [comment]
You can also do:
 
    let user = await User.create({ ... })
    user = await user.populate('company').execPopulate()

**Comment by vkarpov15** [comment]
@mienaikoe good suggestion. Here's the relevant docs for posterity:

* [`Document#populate()`](https://mongoosejs.com/docs/api.html#document_Document-populate)
* [`Document#execPopulate()`](https://mongoosejs.com/docs/api.html#document_Document-execPopulate)
