### ISSUE TITLE
Type "Number" may be causing interesting validation ripples.

### ISSUE THREAD

**Issue by crispen-smith** [Automattic/mongoose#1929]
I'm not sure of the best way to document or replicate this issue, though I'm sure I should be able to.

I have the following model:

```
var mongoose = require('mongoose')
, uniqueValidator = require('mongoose-unique-validator')
, Schema = mongoose.Schema
;


var productSchema = new Schema({
name: {type: String, required: true, unique: true },
cost: {type: String, required: true},
summary: {type: String, required: true},
description: {type: String, required: true },
lead_image: {type: String, required: true }
};
productSchema.plugin(uniqueValidator);

module.exports = mongoose.model('product', productSchema);
```

When  I have it configured this way and pass it valid data for price but empty strings for Summary or description, the save gives me expected errors.  However, if I set the type of cost to Number then the subsequent fields don't fail as expected.  I'm more than open to the idea that I'm doing something wrong, but I can't see where that would be.

**Comment by vkarpov15** [comment]
Yeah mongoose explicitly converts empty string '' to `null` for numbers. I'm open to strong counterarguments but that's expected behavior atm so I'm gonna close this for now
