### ISSUE TITLE
__v field causing mongo errors

### ISSUE THREAD

**Issue by dillonkrug** [Automattic/mongoose#1933]
I'm getting this error when saving a document:

``` javascript
{
    name: "MongoError",
    err: "Field name duplication not allowed with modifiers",
    code: 10150,
    n: 0,
    connectionId: 1,
    ok: 1
}
```

the mongo diaglog shows that the query in question did this:

``` javascript
update flags: 0 q: {
    __v: 11,
    _id: ObjectId('527a7c1ca2d740dd0f000004')
}
o: {
    $set: {
        __v: 11,
        aaaa.bbbbb: [{
            _id: ObjectId('52a115780594725664000001'),
            type: "xxxxx",
            name: "xxxxxxxxxxxxxxxx"
        }],
        cccc.ddddd: [{
            _id: ObjectId('527136c893312c254a0000b7'),
            type: "xxxxx",
            name: "xxxxxxx"
        }, {
            _id: ObjectId('52a115780594725664000001'),
            type: "xxxxx",
            name: "xxxxxxxxxxxxxxx"
        }],
        tttttt: new Date(1393008423258)
    },
    $inc: {
        __v: 1
    }
}
```

Not that it's both `{$set: {__v: 11}}` and `{$inc: {__v:1}}`, which mongo does not like.

**Comment by chenop** [comment]
Please check mongoose version compatibility with MongoDB version:
http://mongoosejs.com/docs/compatibility.html

There is a possibility that the MongoDB version you are using require higher Mongoose version.

In my case I use MLab MongoDB version 3.3.6 with Mongoose version 4 - Upgrading to Mongoose 5 solve the issue.
