### ISSUE TITLE
Replace existing document

### ISSUE THREAD

**Issue by scriby** [Automattic/mongoose#1941]
I've been looking for a way to take a model instance and completely overwrite an existing entry in Mongo with it. I'd like validation and other middleware to run on the instance being saved.

The overwrite functionality added in 3.8 looks close to what I want, but it appears that it doesn't run validation and middleware.

**Comment by vvvvalvalval** [comment]
+1 I miss it badly too.

**Comment by vkarpov15** [comment]
4.0 does have middleware and ability to run validators on update(). What exactly are you trying to achieve?

**Comment by kyleshrader** [comment]
Update doesn't validate with options {overwrite: true, runValidators: true}

**Comment by vkarpov15** [comment]
@kyleshrader can you provide some additional context in the form of code samples?

**Comment by kyleshrader** [comment]
For example, I have a Model with the following schema:
```
{
  name: {type: String, required: true},
  someField: {type: String}
}
```

I expect to: 
* be able to add a new field
* be able to remove a not-required field
* not be able to remove a required field

To match these I am using the options:
```
{ overwrite: true,
runValidators: true }

using findOneAndUpdate I am not able to meet these expectations with the options above. In this case, I am able to add a new field, and remove any field (required or not).

**Comment by vkarpov15** [comment]
Update validators currently don't take into account the "overwrite" option. Right now they only validate on the fields specified explicitly in the update, so if you try to `$unset` name it will fail, but if you do `overwrite: true` and send `{ someField: 'test' }` it won't work ATM. I opened up a new issue #3556 to track this.

**Comment by japanjoshi** [comment]
### ### ### ### ### ### _****_
