### ISSUE TITLE
Unexpected bahavior: isNew is true when creating a new model instance with _id provided

### ISSUE THREAD

**Issue by ragulka** [Automattic/mongoose#1943]
Let's say I need to create a model instance by passing in the full hash of model properties, including the _id. Mongoose sets this the document's `isNew` flag to true, even though this model actually exists. 

Maybe this is purposefully designed so, but a bit unexpected nonetheless.

```javascript
var user = new User({ _id: '530f17de2c72a200006d1bea', username: 'app_user' });
console.log(user.isNew); // true
```

**Comment by NickNaso** [comment]
It could be useful if the flas isNew will be set to false when you pass an object with _id in the constructor of mongoose model. Sometimes i did it manually.

**Comment by vkarpov15** [comment]
I don't really like this idea, no way to determine whether the document actually exists in the db, and sometimes you want to generate the id a layer above mongoose
