### ISSUE TITLE
mongoose Error: failed to connect to

### ISSUE THREAD

**Issue by mackjoner** [Automattic/mongoose#1949]
hi,
I was config options
<code>
"mongodb": {
     "url": "mongodb://localhost:27017/demo",
            "options": {
                "db": {
                    "native_parser": false
                },
                "server": {
                    "keepAlive": 1,
                    "poolSize": 10
                }
            }
        }
</code>
node.js code
<code>
mongoose.connect(config.mongodb.url, config.mongodb.options);
</code>

my mongodb is replica set, I startup nodejs app,  it's ok that write data in mongodb by mongoose , Then i shutdown mogodb's SECONDARY node 2, it's not ok that write data. error msg
<code>
Error: failed to connect to .....
</code> 

I search the error in google, There is an article pointed out that this is a bug
https://gist.github.com/asalant/4092454
really？

**Comment by vkarpov15** [comment]
List out all of the servers in your replica set in the url:

`mongodb://localhost:27017,localhost:27018,localhost:27019/demo`

In the above example, mongoose thinks you're connecting to a standalone.

**Comment by mackjoner** [comment]
It's work good..
Thanks
