### ISSUE TITLE
.lean()  - "lean" ObjectIds to strings too?

### ISSUE THREAD

**Issue by mihai-chiorean** [Automattic/mongoose#1955]
how about making .lean() turn objectids as strings?

I often find myself making operations with arrays of ids. Some basic JS array operations don't work if the array contains ObjectIds. Also, I RARELY find myself actually making use of the properties of an ObjectId.

**Comment by vkarpov15** [comment]
Not likely to be in mongoose core anytime soon, because ObjectIds aren't actually strings, they're just conveniently represented as strings. However, easy to make a plugin for this :)

**Comment by mihai-chiorean** [comment]
challenge accepted :)

**Comment by vkarpov15** [comment]
Might want to work with either https://www.npmjs.com/package/mongoose-lean or https://www.npmjs.com/package/mongoose-shortid, these may help

**Comment by brandonros** [comment]
I can't tell you how much headache this has caused me. Please reconsider.

Can you also tell me what else .lean() doesn't do?

**Comment by nasr18** [comment]
if you want to work on mongoose returned object, then dont use lean(). and really this caused me also a great trouble.

**Comment by vkarpov15** [comment]
@brandonros what exactly are you trying to do?

`lean()` bypasses all mongoose-specific stuff so the value returned from the query is the same as it would be if you used the [mongodb driver](http://npmjs.org/package/mongodb) directly without going through mongoose.

**Comment by Fonger** [comment]
You can use this plugin to do exactly what you want
https://github.com/mongoosejs/mongoose-lean-id
