### ISSUE TITLE
Possible Validation Bug

### ISSUE THREAD

**Issue by ix-xerri** [Automattic/mongoose#1966]
I'm setting up a user schema which has subdocuments. Part of the schema is as follows

```
accountIds: { 
	type: [{
		addedAt: {
			type: Date,
			default: Date.now,
			required: true
		}
	}],
	required: true
},
```

If when I create the user I pass `accountIds: ""` then a validation error is not triggered. It does not specify that it has to be an array of objects. Validation Has only worked if I do something like `accountIds: [{}]`

Am I doing something wrong?

**Comment by vkarpov15** [comment]
Mongoose 3 did not support validation within arrays. Mongoose 4 does.
