### ISSUE TITLE
Schema Enum restriction is not enforced upon updating.

### ISSUE THREAD

**Issue by nlhkh** [Automattic/mongoose#1974]
Take this schema:

Schema({
    status          : { type : String, enum : ['active', 'disabled'], default : 'active' }
});

If I attempt to create a document with status field different from active or disabled, then I get an error.
If I attempt to update a document with status field different from active or disabled, then the update will succeed.

**Comment by joeytwiddle** [comment]
These days, you can get validation for `update()` and `updateOne()` and `findOneAndUpdate()`, but you have to pass the `runValidators` option:

```js
    await User.updateOne(
      { _id: userId },
      { status: 'banana' },
      { runValidators: true }
    );
```

Documented here: http://mongoosejs.com/docs/validation.html#update-validators

**Comment by fataltrace** [comment]
I have the same problem.
mongoose: 5.3.2
schema: (
{ status :  { type : String, enum : ['active', 'disabled'], default : 'active' } }, 
{ strict: 'throw', useNestedStrict: true }
)
method: findOneAndUpdate(query, patch, { runValidators: true })

**Comment by vkarpov15** [comment]
@fataltrace please open up a separate issue with detailed code samples. Make sure you read the [update validator docs](http://mongoosejs.com/docs/validation.html#update-validators) carefully first.
