### ISSUE TITLE
Dot notation not working for access to nested object

### ISSUE THREAD

**Issue by neverfox** [Automattic/mongoose#1975]
It was my understanding that dot notation can be used to get from a document object. I have a model that has some simple properties (like a string), some arrays and some nested object properties. I have no problem using dot notation to retrieve the first two types, but if I use it when x is a nested object, then I don't get the expected (to me) behavior. Instead I get back a strange model object that corresponds to the spec for the whole parent model with the object fields thrown in and everything undefined. Something like this (debug console output):

Take the following schema (some things left out for brevity)

``` coffeescript
Schema = mongoose.Schema

priceSchema = new Schema
  date:
    type: Date
    required: true
    unique: true
    dropDups: true

  close:
    type: Number
    required: true

  adj_close:
    type: Number
    required: true

instrumentSchema = new Schema
  symbol:
    type: String
    required: true
    unique: true
    trim: true
    uppercase: true

  quote:
    timestamp:
      type: Date

    price:
      type: Number

    return_3mo:
      type: Number

    source:
      type: String

  prices: [priceSchema]
```

Now, accessing the document as `this` from within a model method, I can all `this.symbol` and get the string back. I can call `this.prices` and get the MongooseEmbeddedArray back. But when I call `this.quote`, I get:

```
model
__v: undefined
_id: undefined
can_allocate: undefined
id: undefined
is_index: undefined
lookbacks: undefined
monthly_prices: undefined
name: undefined
price: undefined  // not part of top level, part of the nested quote object
prices: undefined
quote: undefined
return_3mo: undefined  // not part of top level, part of the nested quote object
source: undefined  // not part of top level, part of the nested quote object
symbol: undefined
timestamp: undefined  // not part of top level, part of the nested quote object
toObject: function () {
weekly_prices: undefined
__proto__: model
```

However, this.get("quote") still works:

```
Object
price: 14.02
source: "Yahoo!"
timestamp: Tue Mar 25 2014 13:14:00 GMT-0700 (PDT)
__proto__: Object
```

This cannot be right, can it?

**Comment by vkarpov15** [comment]
This was fixed in https://github.com/Automattic/mongoose/pull/5546
