### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by nikilster** [Automattic/mongoose#1980]
I've been having really slow mongoose queries and have been trying to figure this out for an entire day.  I've narrowed it down to either being the way mongoose creates objects or the actual latency in the db server requests.  I have barely any data in the database (< 1000 objects in each of the 4 collections) and ran queries (which were similar to the queries in the product) manually and profiled them and they all ran < 2-4 ms.  Two big questions which I have not been able to figure out by searching online / looking at the docs.  
1. How do I get the raw queries that mongoose is running on mongo?
2. How many trips to the db server does a call make - for example if I have a query with a couple populate calls, a sort call, and a nested populate call in the result set how many trips does that make to the server.

Here's some of the latency times I'm seeing:

Login
localhost + localDB = 58ms
localhost + mongoHQ = 127ms
heroku + mongoHQ = 287ms

Get Data
localhost + localDB = 281ms
localhost + mongoHQ = 1657ms
heroku + mongoHQ    = 2190ms

Thanks in advance for the help!

**Comment by pakastin** [comment]
```
db.collection
  .where('_id').in(ids)
```

..is really slow in mongoose (using node-mongodb-native is *much* faster)

**Comment by kang-heewon** [comment]
any update?

**Comment by pakastin** [comment]
Have you tried to add `.lean()` to query? 🤔

**Comment by vkarpov15** [comment]
@kang-heewon please open a new issue and follow the issue template. Original post doesn't have nearly enough info for us to investigate.
