### ISSUE TITLE
How to use $geometry with $near

### ISSUE THREAD

**Issue by khurrumqureshi** [Automattic/mongoose#1983]
I am storing user travelling paths like this

[ { _id: 5336041835cd4c981c000008, __v: 0, loc: { type: 'LineString', coordinates: [ [55.195538, 25.110762], [55.407583, 25.164881] ] } }, { _id: 5336041835cd4c981c000007, __v: 0, loc: { type: 'LineString', coordinates: [ [55.194096, 25.095051], [55.407583, 25.164881] ] } } ]

Now I would like to compare path and get the list of paths that are exactly same to provided path or nearby 100 meter for that I am using this query

db.userPaths.find( { loc : { $near : { $geometry : { type : "LineString" , coordinates : [[ 55.194096 , 25.095051], [55.407583, 25.164881] ] ] } , $maxDistance : 100 } } } )

How to achieve same thing in mongoose means how can I run this query through mongoose?

**Comment by efkan** [comment]
+1

**Comment by efkan** [comment]
Would it be possible you tried the following code?
https://github.com/LearnBoost/mongoose/blob/master/lib/query.js#L2602

    query.where('loc').near({ center: [10, 10], maxDistance: 5, spherical: true });

I've been dealing with this point.
