### ISSUE TITLE
geoNear with GeoJSON should expect maxDistance in metres

### ISSUE THREAD

**Issue by spikeheap** [Automattic/mongoose#1987]
The [documentation for mongo's geoNear](http://docs.mongodb.org/manual/reference/command/geoNear/) defines `maxDistance` as being in radians for legacy coordinate pairs and metres for GeoJSON data. 

Mongoose's `geoNear` strips the coordinates from the GeoJSON object (see [model.js#L1775](https://github.com/LearnBoost/mongoose/blob/8fd25ac6b887bb6c25efdc4ebac04d160b6778fd/lib/model.js#L1775)) so all calls to mongo's `geoNear` use legacy coordinate pairs, which isn't what you expect as a developer.
#### What I expected

Given the following JavaScript:

``` javascript
var location = {
  type : "Point",
  coordinates : [53.123578, -4.102395]
};
var searchOptions = {
  maxDistance : 10,
  spherical : true
}
MyThing.geoNear(location, searchOptions, function (err, results, stats) {
  console.log(results);
})
```

The results should be limited to those within a radius of 10m.
#### What happened

The results were limited to those within a radius of 10radians, or 63,710m.

---

If someone could confirm this as a valid bug I'm happy to have a crack at fixing it.

**Comment by fabiosussetto** [comment]
Please at least mention it in the documentation, I wasted some time because of this. Thanks!
