### ISSUE TITLE
problem saving a no specified field and schema strict:false

### ISSUE THREAD

**Issue by bitliner** [Automattic/mongoose#1994]
My schema has the options strict = false.

But if I try to save an instance the model of this schema, and the istance has a field that is not specified in the schema, that field is not saved.

What I would like to do, it is using strict option = false to specify some fields of the schema, but not all.

To give you an example of this issue, try to run the following code and check your database: that saved model does not have the specified field that it should have.

```
var m=require('mongoose');
this.db || (this.db = m.connect('...'));

var Schema=m.Schema;

var b=new Schema({
        name:String
},{
        string:false
})

var M=m.model('Ola',b);

var a=new M({
        a:{
                b:2
        }
}).save()

```

**Comment by vkarpov15** [comment]
Closing this in favor of #5378, follow that issue for updates
