### ISSUE TITLE
subDocument array update bug

### ISSUE THREAD

**Issue by wwwy3y3** [Automattic/mongoose#2006]
Hi
I have a subdocument array schema like this

```
var TableSchema= new Schema(
    { 
        name: String,
        description: String,
    }, {strict: false})


var collection= {
tables: [ TableSchema ]
}
```

and when I find subdocuments, and try to update, I ran into a bug...

I only specified which subDocument I need in the fields by doing `tables.$`

```
var fields= '_id url _creator tables.$'
collection.findOne({ "tables._id": <myTableId> }, fields)
```

but, when I try to update the collection like this

```
var table= collection.tables.id(<myTableId>);
table.name='newname';
collection.save(done)
```

instead of update the subdocument, which has `_id` myTableId, Mongoose update the first subdocument in the DocumentArray

when I load the whole `tables` to the `collection`, by changing `tables.$` to `tables`, the problem is fixed

Is there anyway I can update subdocument by its `_id`?

**Comment by qmarquez** [comment]
hey there, it seen a bad wrong, the $ operator selects the first element of an array, so, it´s understandable just update that,...
i recomend to read https://docs.mongodb.com/manual/reference/operator/update-array/

**Comment by vkarpov15** [comment]
Gonna close this, this issue is long out of date and the above docs should be sufficient
