### ISSUE TITLE
sub-document nesting, populate then sort

### ISSUE THREAD

**Issue by gmoulin** [Automattic/mongoose#2007]
Hi,

I have a problem with a sort on a sub-document field.

Schemas (simplified) :
```javascript
//saga.js
var mongoose = require('mongoose')
	, validator = require('validator')
	, Schema = mongoose.Schema
	, ObjectIdSchema = Schema.ObjectId
	, ObjectId = mongoose.Types.ObjectId
;

var sagaSchema = new Schema({
	_id: {type: ObjectIdSchema, default: function(){ return new ObjectId(); }},
	title: {type: String, required: true, index: {unique: true, dropDups: true}},
});

module.exports = mongoose.model('Saga', sagaSchema);
```
```javascript
//item.js
var mongoose = require('mongoose')
	, Schema = mongoose.Schema
	, ObjectIdSchema = Schema.ObjectId
	, ObjectId = mongoose.Types.ObjectId
	, Saga = require('./saga.js')
	, itemSchema
;

itemSchema = new Schema({
	_id: {type: ObjectIdSchema, default: function(){ return new ObjectId(); }},
	title: {type: String, required: true},
	saga: {type: ObjectIdSchema, ref: 'Saga'}
});

itemSchema.index({title: 1, category: 1, type: 1}, {unique: true});

module.exports = mongoose.model('Saga', sagaSchema);
```

This is working fine for adding data.

Now with the populate on querying.
```javascript
var Item = require('../models/item.js');

exports.findAll = function( req, res ){
	Item.find()
		//.populate('saga') //not working
                .populate({ path: 'saga', model: 'Saga' })
		.sort({'saga.title': 1}) //not working
		.exec(function( err, items ){
			if( err ){
				res.status( 418 ).send({error: true, msg: 'An error has occurred', desc: err});
			} else {
				res.send( items );
			}
		})
	;
};
```
First I tried with ".populate('saga')" but no data was populated. I then forced the model  with ".populate({ path: 'saga', model: 'Saga' })" and I get populated data.
Is it normal to have to force the model to get populated data ?

Second I tried to sort the items by saga title value but it is not working. 
I tried :
    ".sort('saga.title')",
    putting sort before the "populate" statement,
without success.
Is it even possible ?
Should I use a "manual" sort in the "exec" function ?

P.S. a teapot is hidden somewhere ;).

**Comment by AlfredTheBest** [comment]
I met the same problem , but can not fix it

**Comment by vkarpov15** [comment]
It's unfortunately not possible for mongoose to support this behavior outside of MongoDB 3.2 and $lookup, because you can't sort by foreign fields on the MongoDB server.
