### ISSUE TITLE
schema with variable key?

### ISSUE THREAD

**Issue by dutu** [Automattic/mongoose#2010]
Hi,

Is it possible to define a schema when a key is variable.
Example of 2 objects:
    ` { 123: { firstname: "firstA", lastname: "lastA" } }`
    ` { 124: { firstname: "firstB", lastname: "lastB" } }`

**Comment by vkarpov15** [comment]
Nope not currently possible. Closest alternative is to use `strict: false` or the mixed schema type.

**Comment by Starefossen** [comment]
I solved a similar problem by setting `strict` to `false` as suggested, and then unsetting and setting the object in question like this:

```js
foo.set('bar', {});  
foo.set('bar', barObj);
```

**Comment by Billy-** [comment]
> if you don't know what the key name will be, you probably shouldn't define a strict schema for it
:-1:
My schema _strictly_ enforces an object with a number (id) as a key, and a strict object schema for the value

I realise this issue is old, has there been any change on this?

**Comment by vkarpov15** [comment]
There's several issues open for this already like https://github.com/Automattic/mongoose/issues/1522 . Please follow those for updates.

**Comment by znorman-harris** [comment]
+1

It would really be great if there were something as easy as the way you can define an interface in typescript like this:

```typescript
export interface IImageData {
  _id: string;
  _image: string;
  _project: string;
  data: { [key: string]: IImageDataItem }; // dynamic key-value where key is always a string
}
```

**Comment by vkarpov15** [comment]
@znorman-harris this feature's been in Mongoose for quite a while, see [maps](https://mongoosejs.com/docs/schematypes.html#maps)
