### ISSUE TITLE
wish: Support Bulk() operations in Mongo 2.6

### ISSUE THREAD

**Issue by markstos** [Automattic/mongoose#2016]
Mongo 2.6 has been released now, and adds new bulk operations. 

While the mongoose create() function can insert multiple documents, they are done serially. Mongo has a new option for "unordered inserts" which has the ability to further speed up inserts:

http://docs.mongodb.org/manual/reference/method/Bulk/#Bulk

It would be nice if this was exposed in Mongoose.

Thanks for Mongoose! I'm using it regularly.

**Comment by Levino** [comment]
+1

As far as I can see the inserts are done in parallel but still with individual queries, which is a really bad idea. Should support mongo bulk operation.

**Comment by vkarpov15** [comment]
The old `initializeUnorderedBulkOp()` etc. "fluent bulk" operations are [deprecated](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#q--a). The new API for bulk inserts is the `insertMany()` function. [Mongoose has its own thin wrapper around `insertMany()`](http://mongoosejs.com/docs/api.html#model_Model.insertMany) as of 4.4.0.

**Comment by Levino** [comment]
Good stuff. Thanks for clarifying. What about findAndUpdate?

**Comment by vkarpov15** [comment]
There's an [`ordered` option for `insertMany()`](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#basic) that mongoose needs to properly support, see above issue.

**Comment by Levino** [comment]
I am not talking about insertion but updates.

**Comment by Levino** [comment]
Just to clarify: So per default mongoose will continue on error, right?

**Comment by vkarpov15** [comment]
No, `ordered` is true by default and we don't currently have a mechanism for shutting it off, which is why we need #3893.

**Comment by raitucarp** [comment]
is this issue resolved? I need ordered option
