### ISSUE TITLE
Individual toObject and toJSON options for virtuals

### ISSUE THREAD

**Issue by whitecolor** [Automattic/mongoose#2032]
It would be nice to be able individually set toObject and toJSON for virtuals to instruct whether the virtual property should be included in toObject (toJSON) result or not.

```javascript
personSchema.virtual('name.full').toObject = true
```

```javascript
personSchema.virtual('name.full').toJSON = false
```

**Comment by vkarpov15** [comment]
Stale issue, re-open if this is still a problem. FWIW I'm pretty sure this works already.
