### ISSUE TITLE
toJSON should escape U+2028 and U+2029

### ISSUE THREAD

**Issue by autopulated** [Automattic/mongoose#2033]
These characters are unicode line endings. They aren't valid in javascript literal strings, but they are technically valid in JSON. This means that any JSON object containing these cannot be embedded in a page without causing a syntax error.

It'd be nice if mongoose fixed this ~~insanity~~ ... idiosyncrasy ... by escaping these with their \u escapes in toJSON calls.

In fact, according to [this](http://stackoverflow.com/a/2973494/233201) stackoverflow answer, there are more unicode characters that could cause similar problems.

**Comment by vkarpov15** [comment]
I took a closer look and I don't think this is an issue Mongoose should fix. Couple of reasons: 1) Mongoose data doesn't always end up in a web page, 2) Even then, JSONP is also relatively uncommon.
