### ISSUE TITLE
Is it possible to `find` based on the `populate` field?

### ISSUE THREAD

**Issue by dickeylth** [Automattic/mongoose#2034]
My schemas : 

	
	var UserSchema = new Schema({
    	name: {
        	type: String,
        	unique: true
    	},
    	github: Object
    	group: Array,
    	lastLogin: {
        	type: Date,
        	default: Date.now
    	}
	});

	var BlogSchema = new Schema({
    	name: {                                         
        	type: String,
        	unique: true,
        	index: true
    	},
    	desc: String,
    	category: {
        	type: String,
        	enum: ['tech', 'viewpoint', 'news']
    	},
    	author: {
        	type: Schema.Types.ObjectId,
        	ref: 'User'
    	},
    	date: {
        	type: Date,
        	default: Date.now
    	}
	});
	
	
	mongoose.model("User", UserSchema);
	mongoose.model("Package", PackageSchema);
	
	PackageSchema
        .find({})
        .populate('author', null, { name: currentUser } })
        .skip((page - 1) * pkgNumPerPage)
        .limit(pkgNumPerPage)
        .exec(function (err, data) {

            // did not populate author, result is `author: null`
            ...

        });

**Comment by vkarpov15** [comment]
The above code will return all packages but only populate the user when the corresponding user's name is "currentUser". Unfortunately a limitation based on the fact that mongodb doesn't really support joins.
