### ISSUE TITLE
creating multiple documents at once returns only 1 inserted record

### ISSUE THREAD

**Issue by mgenev** [Automattic/mongoose#2036]
I'm trying to use the multiple record insert from the docs here: http://mongoosejs.com/docs/api.html#model_Model.create

The insertion goes well, but in return I only get 1 record, not 3 records like I need to.

My code looks like this:
```
    User.create({
        name: 'martin genev',
        email: 'mgenev@gmail.com',
        username: 't44ffffff4',
        password: 'pass',
        provider: 'local'
    }).then(function(admin, err) {
        adminInserted = admin;
        // load the first 3 types with mongoose under admin user
        if (err) {
            console.log(err);
        } else {
            var types = Type.create([{
                type: 'blog',
                user: admin
            }, {
                type: 'page',
                user: admin
            }, {
                type: 'newsflash',
                user: admin
            }]);
            return types;
        }
    }).then(function(blog, page, newsflash, err) {
        if (err) {
            console.log('==== error creating types');
            console.log(err);
        } else {

            console.log('==== function arguments', blog, page, newsflash);
        }
    });
```

My console output however looks like this, notice the 2 undefined for 'page' and 'newsflash'
```
==== function arguments { user: 53557794b9e03c0000b8dbc9,
  _id: 53557794b9e03c0000b8dbca,
  type: 'blog',
  created: Mon Apr 21 2014 12:55:00 GMT-0700 (PDT) } undefined undefined
``` 

Either I'm doing something wrong and am failing to understand why from the docs, or the return isn't functioning properly. Thanks for the attention.

**Comment by vkarpov15** [comment]
This was fixed in latest version of mpromise, although I'd recommend you use 4.0.x and pass in an array to `Model.create()`. 4.0.x returns an array of docs if you give `.create()` an array of docs, which provides more sane behavior with promises, because most promises libraries only give you one return value.
