### ISSUE TITLE
Dynamic fields for schemas for stats and preaggregation

### ISSUE THREAD

**Issue by vinz243** [Automattic/mongoose#2039]
Hi,  I'm  to make analytics for number of download per item.  Here is my doc structure

``` js
{ _id: "20101010/site-1/apache_pb.gif", metadata: { date: ISODate("2000-10-10T00:00:00Z"), hourly: { "0": 227850, "1": 210231, ... "23": 20457 }, minute: { "0": { "0": 3612, "1": 3241, ... "59": 2130 }, "1": { "0": ..., }, ... "23": { "59": 2819 } } }
```

As you see I need  to  store the hits very often in a new subdoc .  Every thing is explained here  http://docs.mongodb.org/ecosystem/use-cases/pre-aggregated-reports/ but it applies only for native mongodb. How to do it using mongoose ?

**Comment by vivekgs2007** [comment]
I am also facing same issue with mongoose.

Do i need to use another mongodb middleware?

**Comment by vkarpov15** [comment]
What's the exact issue? Mongoose does support the aggregation framework, see [api docs on aggregate](http://mongoosejs.com/docs/api.html#aggregate-js).
