### ISSUE TITLE
Calling "native" mongodb driver methods right after connecting hangs

### ISSUE THREAD

**Issue by mtkopone** [Automattic/mongoose#2048]
This never completes:

    var mongoose = require('mongoose')
    mongoose.connect('mongodb://localhost/mydb')
    mongoose.connection.db.dropCollection('anyCollection', function() {
      console.log('OK')
      mongoose.disconnect()
    })

A work-around is to call any mongoose operation before the dropCollection.

mongoose 3.8.8
node v0.10.22
mongo v2.6.0

**Comment by vkarpov15** [comment]
By design, mongoose doesn't buffer the underlying driver calls. You need to wait for mongoose to properly connect before using the underlying driver:

```javascript
mongoose.connection.on('connected', function() {
  mongoose.connection.db.dropCollection(); // Works
});
```
