### ISSUE TITLE
Marking field as populated manually?

### ISSUE THREAD

**Issue by inca** [Automattic/mongoose#2075]
Let's say I have `group` and `member` documents, `member` was just created and `group` was fetched earlier.

After `member.group = group` the `member.group` becomes `ObjectId` instead of document. The problem is that I need to use some virtuals, which, in turn, require full document, not just its id. Population works perfectly (awesome stuff, btw, thank you!), but the query is totally redundant as I already have that `group`.

Is it possible to avoid this casting somehow? Or marking the `group` as it was populated?

**Comment by mathieug** [comment]
Is this now possible?

**Comment by vkarpov15** [comment]
Yep in 4.0.1 you can do this for single populated subdocs (but not document arrays). For instance, OP's `members.group = group;` will make the group field into a populated doc, but `group.members[2] = member;` will leave members[2] as an ObjectId.

**Comment by mathieug** [comment]
Thank you. Is there a documentation?

**Comment by vkarpov15** [comment]
Not yet, see #2884 to track.

**Comment by mathieug** [comment]
Thank you!
