### ISSUE TITLE
aggregate with skip can't work

### ISSUE THREAD

**Issue by mani95lisa** [Automattic/mongoose#2078]
Hi, guys, please help me out, thank you very much!

Schema

``` javascript
ReportSchema = new Schema
  user:type:Schema.ObjectId,ref:'User',index:sparse:true
  report:[
    qid:type:Schema.ObjectId,ref:'Question'
    value:Schema.Types.Mixed
    remark:String
  ]
  created_at:Date
```

Aggregate when `skip=0` works fine, but when `skip!=0`, I got nothing. I'm sure there're pages data.

``` javascript
Report.aggregate()
    .unwind('report')
    .match('report.qid':new ObjectId(data.qid))
    .project(
      value:'$report.value'
      remark:'$report.remark'
      user:'$user'
    )
    .sort('created_at':-1)
    .limit(limit)
    .skip(skip)
    .exec (err, result)->
```

**Comment by PARAGJYOTI** [comment]
@mani95lisa  Thanks for the trick . and @vkarpov15  , you are right . Seems like expected behavior in mongodb .

**Comment by tanmynguyen** [comment]
Hi @mani95lisa 
This is how to fix:
`db.collection.aggregate([{$match}, {$sort: {}}, {$skip: _skip}, {$limit: _limit}, {$project: {}}])`
Hope it's useful for you!

**Comment by webexpert4rv** [comment]
@mani95lisa  thanks dear, it's working now
