### ISSUE TITLE
Shouldn't mongoose detect primary in a replica set?

### ISSUE THREAD

**Issue by sommestad** [Automattic/mongoose#2089]
_Using mongoose 3.8.8._

Not sure if this is a "bug" or if I've misunderstood how Mongoose should handle replica sets, but here it goes:

I'm using a replica set with one primary and one secondary (hosted by MongoHQ) and connecting using `mongoose.connect('mongodb://user:pass@hello.com:12345/my_db,mongodb://user:pass@hello.com:54321/my_db')` (with other URI:s and credentials of course). 

The thing is that mongoose can't write to the database unless I specify the primary first in the URI string (it attempts to write to the secondary, which it can't for obvious reasons). I was under the impression that mongoose would try to figure out which one in a replica set that is the primary? 
Otherwise, it would require a new code deployment if we were to change primary?

**Comment by troyfactor4** [comment]
I know this is late but:

Just dealt with this issue for the last day and a half. We changed db.open('...') to db.openSet('...') and all works fine. Using the openSet function is specific to mongoose and sets the internal replica variable to true. Hope this helps someone.

**Comment by vkarpov15** [comment]
@troyfactor4 correct, if you use connection.open() explicitly, that will connect as a standalone. However, `createConnection()` is smart enough to determine if you're using a replica set or not.

**Comment by wtroynelson** [comment]
@vkarpov15 right you are. Was not aware of the many different ways to open the database connection. Thanks for the update!

**Comment by troyfactor4** [comment]
@vkarpov15 right you are. Was not aware of the many different ways to open the database connection. Thanks for the update!

**Comment by mileswilson** [comment]
Also having this problem I think:

I have DNS round robin enabled within my infrastructure - so 'a valid' instance of mongo is availalbe on mongo.marathon.mesos - externally, the replicaset is being dynamically configured with the correct hostnames to contact the individual instances (mongo-1235.mongo.marathon.mesos) 

Can I get mongoose to connect to the instances provided by DNS, then have it re-connect to the addresses listed in that instances replicaset config?

**Comment by vkarpov15** [comment]
I'm not an expert but I'd imagine connecting through DNS round robin would not work terribly well. The node driver doesn't cache server IP addresses, so if it has 3 hosts all at `mongo.marathon.mesos`, it will continue to make requests to `mongo.marathon.mesos` for `isMaster` requests (essentially mongodb's heartbeats) so you'd have to hope that the driver is making requests in exactly the right order. I'd recommend not using DNS round robin with the node driver.
