### ISSUE TITLE
Instance-level events

### ISSUE THREAD

**Issue by Neamar** [Automattic/mongoose#2090]
Mongoose model inherits from Event Emitter, which lets us do stuff like this:

``` js
MyModel.on('init', function() {})
```

Pretty cool.

However, this event is broadcasted to all instances, even when sent from a custom instance. Meaning this code will result in really weird behavior:

``` js
var MyModel = require('mongoose').model('Document');

var myModel = new MyModel();
var myModel2 = new MyModel();

myModel.on('event', function() {
  console.log("Event on myModel");
});

myModel2.emit('event');
```

This code will display "Event on myModel", although it was dispatched on myModel2.
(this is even weirder in mongoosastic plugin, which globally dispatch 'es-indexed' event for each document)

Is there any way to have "instance-level-event-emitter" ? Custom middleware could do the trick too, although i found no information regarding this.

**Comment by Neamar** [comment]
Hey @vkarpov15, you removed the 4.x label but the new implementation does not allow for the quick fix listed above.

Any idea (or plan) on how to implement this using the new method? It looks to be more tricky...

**Comment by vkarpov15** [comment]
I think this should be pretty easily implementable via plugin.

```javascript
function plugin(schema) {
  schema.queue('createEmitter', []);

  schema.methods.createEmitter = function() {
    this.$__emitter = new EventEmitter();
  };

  ['on', 'once', 'emit'].forEach(function(fn) {
    schema.methods[fn] = function() {
      this.$__emitter[fn].apply(this.$__emitter, arguments);
    };
  });
}
```

**Comment by Neamar** [comment]
Indeed, however doing so would also "cut" the instance from "model level" events.

```
Document.on("modelLevel", function(){});

// where document implements the above plugin
var document = new Document();
document.on("instanceLevel", function() {});

// This would not work anymore
document.emit("modelLevel");

**Comment by vkarpov15** [comment]
With the above plugin you can still listen to model-level events with `Document.constructor.on()`.

**Comment by hasezoey** [comment]
i think this can be closed, because events are now properly per-model-instance:

```ts
// NodeJS: 18.7.0
// MongoDB: 5.0 (Docker)
// Typescript 4.7.4
import * as mongoose from 'mongoose'; // mongoose@6.5.2

const MyModel1 = mongoose.model('1', new mongoose.Schema());

const mydoc1 = new MyModel1();
const mydoc2 = new MyModel1();

mydoc1.on('event', function () {
  console.log('Event on mydoc1'); // never logs
});

mydoc2.on('event', function () {
  console.log('Event on mydoc2'); // logs
});

mydoc2.emit('event');
```

i think this issue can be closed @vkarpov15 @Uzlopak @AbdelrahmanHafez
