### ISSUE TITLE
numberOfRetries doesn't work.

### ISSUE THREAD

**Issue by missing1984** [Automattic/mongoose#2110]
var options =  {
        server: {
            auto_reconnect: true,
            socketOptions: {
                keepAlive: 1
            }
        },
        db: {
            retryMiliSeconds: 10000,
            numberOfRetries: 5
        }
    };

the retryMiliSeconds works but numberOfRetries doesn't work. driver keep connecting mongodb ultimately.

**Comment by sprijk** [comment]
It look like it is not being handled in the options parser, see https://github.com/Automattic/mongoose/blob/master/lib/drivers/node-mongodb-native/connection.js#L247

**Comment by vkarpov15** [comment]
try:

```javascript
mongoose.connect('mongodb://localhost:27017/gh2110', {
  server: {
    reconnectTries: 2,
    reconnectInterval: 250
  }
});
```

'numberOfRetries' is actually for [tailable cursors](http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#setCursorOption), not connections. The driver docs need to be updated...

**Comment by vkarpov15** [comment]
See PR clarifying the [node driver docs](http://mongodb.github.io/node-mongodb-native/2.0/api/Db.html)
