### ISSUE TITLE
[TypeError: Cannot use 'in' operator to search for '_id] if field_name is "addresses" but works if field_name is "address"

### ISSUE THREAD

**Issue by dbngshuroy** [Automattic/mongoose#2116]
var patientSchema = new Schema({
	user_id		:	Schema.Types.ObjectId,	
        name         	: 	String,
        date_of_birth   : 	Date,
	addresses	:	[{street:String,city:String}],
	gender		:	String,
	contacts	:	[{data:String,type:String}],
	favourite_doctors   :	[{doctor_id:Schema.Types.ObjectId}],
	favourite_retailers :	[{retailer_id:Schema.Types.ObjectId}]	
});

when creating  a new patient using Postman(Google Chrome) by POST then
[TypeError: Cannot use 'in' operator to search for '_id] comes in the console But if I change the addresses into address in schema then it works. Why this is happening?

**Comment by vkarpov15** [comment]
Can you provide me some more information, like code that reproduces this? Like how you're creating the document and what your schema looks like?

**Comment by keithand** [comment]
Hi Valeri,

I figured it out. My httpie was incorrect. Thanks for reaching out though. :)

Keith

On Jan 2, 2015, at 8:21 AM, Valeri Karpov <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you provide me some more information, like code that reproduces this? Like how you're creating the document and what your schema looks like?

—
Reply to this email directly or view it on GitHub<https://github.com/LearnBoost/mongoose/issues/2116#issuecomment-68538714>.

Keith Anderson
ESL Testing Coordinator
Academy of Art University
79 New Montgomery St.
Room # 340
San Francisco, CA 94105
Phone#:(415)-618-8436

"The purpose of life is to be happy."

-Dalai Lama

**Comment by siddhsuper** [comment]
var parseBody = JSON.parse(req.body);
```
User.create(parseBody, function(err) {
              if (err) {
                callback(null, err);
              }
              callback(null, "");
            });

```
