### ISSUE TITLE
Connection#useDb not working after database has switched once

### ISSUE THREAD

**Issue by Sagarj87** [Automattic/mongoose#2119]
Issue probably due to connection object's path db._state is having the value of "disconnected". But if I do queries on the same connection, we are getting the results. Please help us on the issue.

**Comment by vkarpov15** [comment]
I'm going to close this for now since this issue is very stale. Please re-open with more info if this is still an issue.

**Comment by sevensand** [comment]
I have same issue,
mongoose latest version

Handling Multiple Database connection using useDb  when working with same model, same schemas but different data,

The connection is not switched.


this is my  connection 

`const mongoose=require('mongoose')
const company = mongoose.createConnection(uri)
var connections = {};
function getDatabase(dbName){
  if(connections[dbName]){
    return connections[dbName]
  }else {
    connections[dbName] = company.useDb(dbName)
    return connections[dbName]
  }
}
module.exports = company: getDatabase()
`




this is my Model
`const connection = require('../connection');

const UserSchema = mongoose.Schema({
    Name: {
        type: String,
        required: true
    },
})

module.exports = {
    User: connection.company.model(“user”, UserSchema)
}
`
When I cache the result inside function getDabase the connection appeared and the database name  was change, but it always fall in 1st connection called.

Can you help me to figure out why?
