### ISSUE TITLE
SchemaTypes, Types inheritence on Connection

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#2128]
In order to load additional types into a connection, I need to have inheritance of Types and SchemaTypes from mongoose.  For example:

``` js

// # db

var mongoose = require('mongoose')
var _ = require('underscore')
var mongooseTypes = require('nifty-mongoose-types')

exports = module.exports = function(logger, settings) {

  var connection = mongoose.createConnection(
    settings.mongo.host,
    settings.mongo.dbname,
    settings.mongo.port,
    settings.mongo.opts
  )

  connection.on('error', logger.error)

  connection.on('open', function() {
    logger.info('mongo connection opened')
  })

  connection.Schema = mongoose.Schema
  connection.SchemaTypes = mongoose.SchemaTypes
  connection.Types = mongoose.SchemaTypes
  mongooseTypes.loadTypes(connection)

  return connection

}

exports['@singleton'] = true
exports['@require'] = [ 'logger', 'settings' ]
```

Is this the wrong way to do it?

**Comment by vonpoland** [comment]
I had same error 'error: Undefined type at `paths.email`'

and this solved the problem

var webDb = mongoose.createConnection(options.connectionString)
var user = { name: String }
var UserSchema = new webDb.base.Schema(User);
webDb.model('User', UserSchema);

**Comment by vkarpov15** [comment]
@vonpoland please provide additional context, that's not enough information for me to make an informed hypothesis.
