### ISSUE TITLE
How to get index name on duplicate document 11000 error?

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#2129]
How can I get the index for which the error occurs with?

e.g. if my index is named `email`, how do I get that from the `err` object?

**Comment by paambaati** [comment]
@niftylettuce Can we not get it this way?

`var field = err.message.split('.$')[1].split('_')[0];`

This way, one does not have to know the database name.

**Comment by paambaati** [comment]
@vkarpov15 After Mongoose 4.x, the error format seems to have changed a bit, and no longer contains the offending field name.

The error message, for example, on a field with `unique:true`, `sparse:true` and a `null` value looks like this - 

```
E11000 duplicate key error dup key: { : "<whatever_value_i_tried_to_insert>" }
```

Is there a way to get the field that is causing this error?

**Comment by vkarpov15** [comment]
@paambaati that's not a mongoose issue, that string is generated by the [mongodb server](https://github.com/mongodb/mongo/blob/v3.0/src/mongo/db/storage/wiredtiger/wiredtiger_index.cpp#L110-115) and is specific to the WiredTiger storage engine in mongodb 3.0.0 and 3.0.1. [This bug was reported in the core server jira project, fixed, and the fix is in mongodb 3.0.2](https://jira.mongodb.org/browse/SERVER-17532)

**Comment by alexbooker** [comment]
Thanks to @paambaati I got the functionality I needed. 

```javascript
var user = new User(req.body);
  user.save(function(error) {
    if (error) {
      if (error.code === 11000) {
        // email or username could violate the unique index. we need to find out which field it was.
        var field = error.message.split(".$")[1];
        field = field.split(" dup key")[0];
        field = field.substring(0, field.lastIndexOf("_"));
        req.flash("errors", [{
          msg: "An account with this " + field + " already exists."
        }]);
        res.redirect("/join");
        return;
      }
      throw error;
    }
    req.flash("messages", "Thank you for joining.");
    res.redirect("/");
  });
```

But is there a terser way to get the same result?

**Comment by alexbooker** [comment]
I wrote a [**module**](https://github.com/alexbooker/mongoose-extract-duplicate-field) to extract the duplicate field. I hope someone finds it useful :heart:!

**Comment by vkarpov15** [comment]
There's also another plugin for that, see #2284 and https://www.npmjs.com/package/mongoose-beautiful-unique-validation

**Comment by FuzzySockets** [comment]
@vkarpov15 Dude, thank you!  No more ugly 11000 and 11001 checks!

**Comment by vkarpov15** [comment]
Thank @alexbooker and co, they wrote the plugins :)

**Comment by thomas-lee** [comment]
Not sure if anyone still want to extract the value.

here is my code

```
error.errmsg.match(/dup key: { : "(.+)" }/)[1]
```

**Comment by earthdan** [comment]
And here i wrote mine to get both value and key
*This assumes fixed error msg format*
```
const err.message = 'E11000 duplicate key error index: dev_app.users.$username_1  dup key: { : "debjyoti1" }'
let key_val = err.message.match(/index\:\ [a-z_]+\.[a-z_]+\.\$([a-z_]+)\_[0-9a-z]{1,}\s+dup key[: {]+"(.+)"/).splice(1,3);
// [ 'username', 'debjyoti1' ]
```

**Comment by Fire7** [comment]
Here is my RegExp solution to get index name with any type of error I have found:
```javascript
  var regex = /index\:\ (?:.*\.)?\$?(?:([_a-z0-9]*)(?:_\d*)|([_a-z0-9]*))\s*dup key/i,      
  match =  error.message.match(regex),  
  indexName = match[1] || match[2];  
```


Here what I have tested:
```javascript
('E11000 duplicate key error collection: db.users index: name_1 dup key: { : "Kate" }').match(regex)[1]; // "name"
("E11000 duplicate key error index: myDb.myCollection.$id dup key: { : ObjectId('57226808ec55240c00000272') }").match(regex)[2] // "id"
('E11000 duplicate key error index: test.collection.$a.b_1 dup key: { : null }').match(regex)[1] // "b"
('E11000 duplicate key error collection: upsert_bug.col index: _id_ dup key: { : 3.0 }').match(regex)[1] // "_id"
```

**Comment by aichholzer** [comment]
My two cents:

```
let err = 'E11000 duplicate key error collection: home.users index: name_1 dup key: { : "francis" }';
let [i, field, value] = err.match(/index:\s([a-z]+).*{\s?\:\s?"([a-z]+)"/i);

console.log(field, value);
// name francis
```

MongoDB: `v3.4.2`

**Comment by nicky-lenaers** [comment]
@Fire7 Thanks for your solution. I have, however, a compound unique index for say a `name` and an `owner` field on a `project` model, such that there is never a project created with the same name by one owner.

Using your solution gives me `name_1_owner`. Any idea how to solve this for compound unique indexes?

Thanks!

**Comment by vkarpov15** [comment]
@nicky-lenaers try [this plugin](https://www.npmjs.com/package/mongoose-beautiful-unique-validation)

**Comment by Maxtermax** [comment]
Update 2019, for any one who wanna to use the plugin [mongoose-beautiful-unique-validation](https://www.npmjs.com/package/mongoose-beautiful-unique-validation) be aware of this [issue](mongoose-beautiful-unique-validatio) when use mongodb 3.6 to up

**Comment by itsarnavsingh** [comment]
you guys can just use err.message.indexOf( 'theFieldInQuestion_1' ) === -1
