### ISSUE TITLE
ValidationError string representation shows no relevant details

### ISSUE THREAD

**Issue by bitmage** [Automattic/mongoose#2135]
I'm getting a ValidationError which looks like this:

``` text
ValidationError: Validation failed
  at model.Document.invalidate (.../project/node_modules/mongoose/lib/document.js:990:32)
  at .../project/node_modules/mongoose/lib/document.js:959:16
  at validate (.../project/node_modules/mongoose/lib/schematype.js:561:7)
  at .../project/node_modules/mongoose/lib/schematype.js:577:9
  at Array.forEach (native)
  at ObjectId.SchemaType.doValidate (.../project/node_modules/mongoose/lib/schematype.js:565:19)
  at .../project/node_modules/mongoose/lib/document.js:957:9
  at process._tickCallback (node.js:415:13)
```

The problem is there's no useful information contained in the error.
1.  No lines of code in my application are mentioned.
2.  It doesn't say what model failed.
3.  It doesn't say what field or value failed.

I hunted down the error, and I see it has an 'errors' subobject:

``` text
ValidatorError: Path `account` is required.
  at validate (.../project/node_modules/mongoose/lib/schematype.js:610:16)
  at .../project/node_modules/mongoose/lib/schematype.js:627:9
  at Array.forEach (native)
  at ObjectId.SchemaType.doValidate (.../project/node_modules/mongoose/lib/schematype.js:614:19)
  at .../project/node_modules/mongoose/lib/document.js:956:9
  at process._tickCallback (node.js:415:13)
```
1.  Still no mention of what model failed (account is required on a number of my models).
2.  Still no mention of my application code in the stack trace.

There are a couple of things I think would be helpful:
1.  Add the `model name` and a `listing of fields that errored` to the main error message.  This way it will print out useful information by default, without requiring the consumer to create custom logic to pull out the details.
2.   Is it possible to create a dummy error object when the initial create or save request is made, and then use the stack trace if any errors occur?  Just throwing out ideas here, but anything that could show me the entry point into your library in the trace would be very helpful, as that's the line of code I actually need to change.

**Comment by ksikka** [comment]
Concrete example of where more information would be helpful: I wrote a job that gets data from an API and creates mongoose models out of the data. After running it, I got:

`ValidationError: Client validation failed`

I didn't know why it failed. I looked at the stack trace to see exactly at which line it failed.

`client.lastName = remoteClient.LastName;`

Why would this fail? I looked at the model, `lastName` expects a string. It must be the case that the value assigned to the field was not a string. But then what was it? I had to run my script again with extra logging to determine it was a number.

This could have all been avoided if the error message read:

`ValidationError: Client validation failed: Expected string for lastName, but got number instead.`

As for multiple errors, just append `(N more errors...)` to the message.

**Comment by aneilbaboo** [comment]
Seeing the same problem.  Any word on a fix?

**Comment by whitecolor** [comment]
@vkarpov15 

While trying saving the document get this on 4.11.6 I get nothing meaning validation error
```
 MongooseError:
reader_1                |     at ValidationError (/app/node_modules/mongoose/lib/error/validation.js:27:11)
reader_1                |     at model.Document.invalidate (/app/node_modules/mongoose/lib/document.js:1592:32)
reader_1                |     at _init (/app/node_modules/mongoose/lib/document.js:400:18)
reader_1                |     at init (/app/node_modules/mongoose/lib/document.js:367:7)
reader_1                |     at model.Document.init (/app/node_modules/mongoose/lib/document.js:331:3)
reader_1                |     at completeOne (/app/node_modules/mongoose/lib/query.js:1710:10)
reader_1                |     at Immediate.<anonymous> (/app/node_modules/mongoose/lib/query.js:1311:13)
reader_1                |     at Immediate.<anonymous> (/app/node_modules/mquery/lib/utils.js:137:16)
reader_1                |     at runCallback (timers.js:800:20)
reader_1                |     at tryOnImmediate (timers.js:762:5)
reader_1                |     at processImmediate [as _immediateCallback] (timers.js:733:5)
```

When I use `.validate` I get the correct error like:
```
 { ValidationError: User validation failed: welcomeSent: Cast to date f
ailed for value "true" at path "welcomeSent"
reader_1                |     at ValidationError.inspect (/app/node_modules/mongoose/lib/error/validation.js:57:23)
reader_1                |     at formatValue (util.js:328:36)
reader_1                |     at inspect (util.js:188:10)
reader_1                |     at exports.format (util.js:128:20)
reader_1                |     at Console.log (console.js:106:24)
```


Is it expected behavior? If so, I wonder why.

**Comment by vkarpov15** [comment]
@whitecolor not expected behavior. Can you open up a new issue with some code samples please?
