### ISSUE TITLE
feature request: populate Mongo documents across databases

### ISSUE THREAD

**Issue by mattcasey** [Automattic/mongoose#2137]
I was not able to find anyone else trying to do this, but for scaling, we have some collections saved in separate databases. With this setup, you can't use populate() on a Mongoose document. At least, I could not find a way to do it... For the record, I think I was using mongoose.createConnection() on each database, although now I'm using the same connection with connection.useDB(), maybe that would help? but I didn't try it).

**Comment by olawalejuwonm** [comment]
Is there a way to set the database on the field to use for populating?

**Comment by vkarpov15** [comment]
@olawalejuwonm not currently. You either need to set `ref` to the Model instance (instead of the Model name as a string), or you need to pass in the `connection` as an option when populating. Below is an example from our tests that does cross-db populate with setting `ref` to a model name and passing in a `connection` when populating.

```javascript
      const bookSchema = new Schema({ title: String });
      const movieSchema = new Schema({ title: String });

      const userSchema = new Schema({
        name: String,
        kind: String,
        hobby: {
          type: Schema.Types.ObjectId,
          refPath: 'kind'
        }
      });

      const User = db.model('User', userSchema);
      const Book = db2.model('Book', bookSchema);
      const Movie = db2.model('Movie', movieSchema);

      const book = await Book.create({ title: 'Legacy of the Force: Revelation' });
      const movie = await Movie.create({ title: 'A New Hope' });

      await User.create([
        { name: 'test1', kind: 'Book', hobby: book._id },
        { name: 'test2', kind: 'Movie', hobby: movie._id }
      ]);

      const docs = await User.find().sort({ name: 1 }).populate({
        path: 'hobby',
        connection: db2
      });
      assert.equal(docs[0].hobby.title, 'Legacy of the Force: Revelation');
      assert.equal(docs[1].hobby.title, 'A New Hope');
```
