### ISSUE TITLE
Add a `query` hook

### ISSUE THREAD

**Issue by ghost** [Automattic/mongoose#2138]
## What is the hook?

The `query` hook is a hook that is called before and after a query is executed.
### `pre` Hook

It is run before the final `execute()` in a query chain, or after a query is built from a scalar query chain that provides a callback (eg, `.find({}, function()....)`). The hook will be like any other `pre` hook and would provide a callback that is called once the hook has finished doing what it needs with the query. This lets it run asynchronously and makes sure that the query is modified before it is executed. 
### `post` Hook

The `post` version of the hook would also be similar to other `post` hooks in that it would run asynchronously. The `post` hook would execute once the query had executed and could (possibly) pass in the raw query results.
### Auto-populate certain fields

Say you have a model that has a sub-document that is a reference, and you then want to access that sub-document from a virtual. Currently, to use those virtuals you would need to put a `populate('field')` on the end of every query needing to use those virtuals. With a `pre('query')` hook you could do the following:

``` javascript
var categorySchema = new mongoose.Schema({
    Name: String,
    Tags: Array,
    LatestPost: { type: mongoose.Schema.Types.ObjectId,  ref: 'Post' }
});

var postSchema = new mongoose.Schema({
    Name: String,
    Category: { type: mongoose.Schema.Types.ObjectId,  ref: 'Category' }
});

postSchema.pre('query', function(query, next) {
    query.populate('Category');
    next();
});

postSchema.virtual('CategoryString').get(function() {
    return this.Category.Name + ' / ' + this.Category.Tags.join(',');
})
```

The above example makes sure that the `Category` sub-document is always populated, so that the virtual `CategoryString` would be able to use the `Category` sub-document.

Depending on the internal implementation of the `query` object, you may or may not need to pass the modified query object to the `next` handler, or possibly return it.
### Query logging

So you have your own internal logging system that you would like to log queries to. By using a combination of both `pre` and `post` query hooks you could store the amount of each query executed, the exact queries and parameters executed, and the execution time. Take the following example:

``` javascript
var myQueryLogger = require('logger').Query;

var postSchema = new mongoose.Schema({
    Name: String,
    Views: Number
});

postSchema.pre('query', function(query, next) {
    myQueryLogger.start(query);
    next();
});

postSchema.post('query', function(query) {
    myQueryLogger.end(query);
});
```

The above example logs the query into a 'QueryLogger' and by use of the post hook can also log the execution time by calling `end`. This would allow implementation independent logging of queries as well as storing model data along side it.

<hr>

This is just a few examples of the use cases for the hook, but there is bound to be plenty more! I'll leave it to the people fluent in mongoose to discuss the plausibility of this hook!

_See: #2115_

**Comment by cyberval** [comment]
this is nice, is that going to be ported on the 3.8.X branch or just stick in 4.X?

**Comment by vkarpov15** [comment]
3.8 only has bug fixes, so no plans to backport.

**Comment by ViswanathLekshmanan** [comment]
What about aggregate ?

**Comment by vkarpov15** [comment]
Not supported right now, follow #5251 for updates
