### ISSUE TITLE
Improve docs about connection.

### ISSUE THREAD

**Issue by Volox** [Automattic/mongoose#2157]
Hi,
i just found an issue (petkaantonov/bluebird#241) about the connection instance of Mongoose, or, perhaps, a missing documentation about it. When i create a *custom* connection using the `createConnection()` method i am not able to instantiate a model simply by doing `mongoose.model( 'name', schema )`.

Here is the snippet of the code that reproduces the problem:
```js
var mongoose = require('mongoose');
var connection = mongoose.createConnection();
connection.once( 'error', console.error );
connection.once( 'open', function() {

  var UserSchema = new mongoose.Schema( {
    username: String
  } );

  var User = mongoose.model( 'User', UserSchema );
  //var User = connection.model( 'User', UserSchema ); // This works

  var user = new User( {
    username: 'asd'
  } );

  user.save( function(err, savedUser ) { // Using mogoose.model this callback is never called
    if( err ) console.error( err );
    console.log( 'Saved' );
    console.log( savedUser );
  });
} );


connection.open( 'mongodb://localhost/test' );
```

As i understood `mongoose.model` is bound to the connection created using `mongoose.connection` so the `doc.save()` hangs there waiting for a connection.

**Comment by akoskm** [comment]
I've run into the same issue recently. I can confirm that callback methods on models that are registered directly on the mongoose instance 

```js
require('mongoose').model( 'User', UserSchema )
```

and not on the connection opened by `createConnection`:

```js
var connection = mongoose.createConnection();
connection.model('User', UserSchema);
```
aren't firing.

> As i understood mongoose.model is bound to the connection created using mongoose.connection so the doc.save() hangs there waiting for a connection.

Yes, this seems correct but it's not trivial from the docs that you must have an open, default connection, if you want to register your model like:

```js
require('mongoose').model( 'User', UserSchema )
```
