### ISSUE TITLE
find and findById with ObjectId doesn't work

### ISSUE THREAD

**Issue by zacharynevin** [Automattic/mongoose#2160]
Hello,

My issue is that the `find` and `findById` functions don't work with types `ObjectId`. For example,

````
// id = "53aa4c843bd562c01edd2714"
user.findById(id, { name: 1 }).lean().exec().then(function(user) {
   console.log(user)
})
````

I am not getting any errors. My `user` is just `null`. The issue is that I can clearly see the user object in the test database with the correct `_id`. Also, when I was using plain numbers before, this was working (I made sure to update the Schema to reflect this).

**Comment by vkarpov15** [comment]
Stale issue, re-open if this is still a problem. FWIW I would guess that there's a type mismatch between your schema's `_id` field and the `_id` in the database.
