### ISSUE TITLE
isNew or isModified() for post hooks

### ISSUE THREAD

**Issue by avishaan** [Automattic/mongoose#2162]
For `pre('save')` middleware there is isNew/isModified to figure out if the document is new. I couldn't find something similar for `post('save')`. I am wondering is there something similar for `post('save')`?

**Comment by Philmod** [comment]
I agree with @ericsaboia

**Comment by vkarpov15** [comment]
As far as I understand it, this is trickier than its worth. Post save hooks are run after the save function, so there's no way to clean up internal state like `isNew` after post hooks run, unless we either add an extra "run this post hook after all other post hooks" logic, which is very janky IMO. I'm open to ideas on how this would work, but I don't have a good solution just yet.
