### ISSUE TITLE
Text search on model with discriminators omits all but 3 fields

### ISSUE THREAD

**Issue by Kevin-A** [Automattic/mongoose#2166]
# The situation

I have a situation in which I use text search on model A, which happens to have two discriminators (model AA and AB). The data returned is incomplete while the same query works correctly directly in the Mongo shell. 

## Query using Mongoose

The text search looks something like:

```javascript
A.find(
    { $text: { $search: "something here" } },
    { textScore: { $meta: 'textScore' }}
).
exec(next);
```

According to the documentation this should return all search results including the added `textScore` field, but all it returns is:

```javascript
[
    {
        "_id": "53a954e3ff6c52942a2c1b79",
        "textScore": 0.75,
        "__t": "AA"
    }
    // more
]
```

When I perform the same query on other Models without discriminators it works fine. When I perform this query (the same as above but without the `textScore` field) it returns the same data, fully complete and still in the correct order:
```javascript
A.find(
    { $text: { $search: "something here" } }
).
exec(next);
```

## Same query in Mongoshell

When I launch the same query (with or without the sort() function) directly in the Mongo shell I get the proper output which is all the requested data including the `textScore` field sorted by the `textScore`

```bash
db.A.find(
    { $text: { $search: "something here" }},
    { textScore: { $meta: 'textScore' }}
).
sort({ textScore: { $meta: 'textScore' }})
```

## closing

Am I doing something wrong, if so, what? Or is it Mongoose?

**Comment by douglasf** [comment]
+1
