### ISSUE TITLE
Mongoose autoclose when no other tasks are pending

### ISSUE THREAD

**Issue by iliakan** [Automattic/mongoose#2179]
As of now, the script cannot finish when the mongoose connection is open.
One needs to manually call `mongoose.disconnect()`.

Is that really needed? 

In most DB libraries for languages out there, when the process(say, a script) is "done", it closes filesystem/db connections exits.

And in Node.JS we also have something to help here: the `socket.unref()` call http://nodejs.org/api/net.html#net_server_unref can be applied to show that the connection should not prevent the process from termination.

Maybe we can use it here? So that if there are no pending queries, the sole existence of a connection will not prevent the process from termination.

**Comment by lchenay** [comment]
+1

**Comment by Jokero** [comment]
+1

**Comment by iliakan** [comment]
@vkarpov15 if you ever come across this issue, there's a working implementation of this thing in https://github.com/mranney/node_redis#clientunref

There's a smart notice about the danger of such approach there too.

**Comment by vkarpov15** [comment]
I'm going to close this issue. It is not unreasonable to ask devs to use `mongoose.disconnect()`, most libs that open connections do something similar. We also don't want to mistakenly close Mongoose connections if all the app does is respond to changes that come in on a MongoDB change stream.
