### ISSUE TITLE
Indexes not created

### ISSUE THREAD

**Issue by Neamar** [Automattic/mongoose#2184]
Ive already posted something on https://github.com/LearnBoost/mongoose/issues/2133 however after much investigation i was finally able to reproduce the problem on other machines without NUMA -- totally clearing Mongo and starting it with a different dbpath helped me recreate the problem.

So, here is the simplified model:

```js
var UserSchema = new mongoose.Schema({
  // User email. Will be used for login
  email: { type: String, validate: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i, required: true, unique: true },

  // Hashed and salted password (using bcrypt)
  password: String,
});
```

When running the application, the following command is sent:

```js
Mongoose: users.ensureIndex({ email: 1 }) { safe: undefined, background: true, unique: true }  
```

Looks good. However, running `db.system.indexes.find()` on the db only display the basic index:

```json
{ "v" : 1, "key" : { "_id" : 1 }, "ns" : "test.users", "name" : "_id_" }
```

Adding a `mongoose.connection.on('error')` hook does not display anything. However, using `{ autoIndex: false }` and `model.ensureIndexes(cb);` i get the following error as first argument (stacktrace added for convenience):

```js
{ [MongoError: Connection Closed By Application]
  name: 'MongoError',
  structuredStackTrace: 
   [ { receiver: [Object], fun: [Function], pos: 3084 },
     { receiver: [Object], fun: [Function], pos: 7910 },
     { receiver: [Object], fun: [Function], pos: 16584 },
     { receiver: [Object], fun: [Function], pos: 5685 },
     { receiver: [Object], fun: [Function], pos: 12782 },
     { receiver: [Object], fun: [Function], pos: 13046 },
     { receiver: [Object], fun: [Object], pos: 5807 },
     { receiver: [Object], fun: [Function], pos: 3255 },
     { receiver: [Object], fun: [Function: open], pos: 12206 },
     { receiver: [Object], fun: [Function], pos: 12367 },
     { receiver: [Object], fun: [Function], pos: 11563 },
     { receiver: [Object], fun: [Function], pos: 1279 },
     { receiver: [Object], fun: [Function], pos: 14726 },
     { receiver: [Object],
       fun: [Function: _tickDomainCallback],
       pos: 15554 } ] } 'MongoError: Connection Closed By Application\n    at Object.toError (/home/neamar/Documents/src/REPO_NAME/node_modules/mongodb/lib/mongodb/utils.js:114:11)\n    at Server.close (/home/neamar/Documents/src/REPO_NAME/node_modules/mongodb/lib/mongodb/connection/server.js:188:38)\n    at Db.close (/home/neamar/Documents/src/REPO_NAME/node_modules/mongodb/lib/mongodb/db.js:358:21)\n    at NativeConnection.doClose (/home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:230:11)\n    at NativeConnection.close (/home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/connection.js:483:12)\n    at NativeConnection.<anonymous> (/home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/connection.js:495:14)\n    at NativeConnection.g (events.js:180:16)\n    at NativeConnection.emit (events.js:92:17)\n    at open (/home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/connection.js:453:10)\n    at NativeConnection.onOpen (/home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/connection.js:461:5)\n    at /home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/connection.js:421:10\n    at /home/neamar/Documents/src/REPO_NAME/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:59:5\n    at /home/neamar/Documents/src/REPO_NAME/node_modules/mongodb/lib/mongodb/db.js:294:11\n    at process._tickDomainCallback (node.js:459:13)'
```

(on mongoose 3.8.12)

For information, the mongo log:

```
Wed Jul  9 20:30:10.121 [initandlisten] connection accepted from 127.0.0.1:54615 #193 (11 connections now open)
Wed Jul  9 20:30:10.360 [FileAllocator] allocating new datafile /var/lib/mongodb/test.ns, filling with zeroes...
Wed Jul  9 20:30:10.935 [FileAllocator] done allocating datafile /var/lib/mongodb/test.ns, size: 16MB,  took 0.574 secs
Wed Jul  9 20:30:10.935 [FileAllocator] allocating new datafile /var/lib/mongodb/test.0, filling with zeroes...
Wed Jul  9 20:30:12.489 [FileAllocator] done allocating datafile /var/lib/mongodb/test.0, size: 64MB,  took 1.551 secs
Wed Jul  9 20:30:12.489 [FileAllocator] allocating new datafile /var/lib/mongodb/test.1, filling with zeroes...
Wed Jul  9 20:30:12.491 [conn191] build index test.companies { _id: 1 }
Wed Jul  9 20:30:12.492 [conn191] build index done.  scanned 0 total records. 0 secs
Wed Jul  9 20:30:12.492 [conn191] insert test.companies ninserted:1 keyUpdates:0 locks(micros) w:2132606 2132ms
Wed Jul  9 20:30:13.125 [conn193] build index test.users { _id: 1 }
Wed Jul  9 20:30:13.126 [conn193] build index done.  scanned 0 total records. 0 secs
```

Any ideas on why Mongo would refuse to create the index on a new DB ?

**Comment by memelet** [comment]
I was having a similar problem with ensureIndexes in my tests. Just before ensureIndexes I was dropping the collections, but was not awaiting for the drop to be complete -- hence creating a race between the index creation and collection dropping.

**Comment by efkan** [comment]
@vkarpov15 
Similar problem with mine.

Actually it's not a big problem because already there is an option. But we can see only when we check it :smiley: I've overcome using `{index:true}` option easily.
The documentation specifies '*Indexes are created in the background by default.*' 
https://github.com/LearnBoost/mongoose/blob/master/docs/api.html#L5711
But Mongoose doesn't add any index to any field.

**Comment by nazghull** [comment]
Hiya, 

  I've got a similar problem, I close the connection before the indexes are created. Is there a way to know when ensureIndexes has finished?

Cheers,

  David

**Comment by vkarpov15** [comment]
@nazghull Models emit a (admittedly not very well documented) "index" event when index builds finish.

```javascript
MyModel.on('index', function(err) {
  if (err) {
    // Index build failed!
  } else {
    // Indexes built successfully
  }
});
```

**Comment by Niffy** [comment]
I have a similar problem but I have an idea what could be wrong.
Mongo: v2.4.12
Mongoose: 3.8.23
Collection name: entries
Schema name: Entry

I add an Entry into entries. I expect it to get cleaned up after X amount of time, the result is this does not happen. I wish to use the TTL feature hence the clean up.

You can see below by schema, index event and indexes.

And to me it looks like the ensureIndex call is incorrect.  
If I run the slightly modified ensureIndex code below then the index is created and my

```javascript
entries.ensureIndex({ actioned_on: 1 }, { safe: undefined, background: true, expireAfterSeconds: 32 })
```

So you can see in the original call we do not include the second curly brace statement in the original parentheses. Could this be the problem?

Schema
```javascript
var Entry = new Schema({
  actioned_on: { type: Date, 'default': null, index: {expires: 32} },
});
```

Entry.on('index')
```
Mongoose: entries.ensureIndex({ actioned_on: 1 }) { safe: undefined, background: true, expireAfterSeconds: 32 }  

Mongoose: entries.insert({ __v: 0, actioned_on: new Date("Fri, 13 Feb 2015 01:21:12 GMT"), _id: ObjectId("54dd518874e6f79e040f0f32") }) {} 
```

db.entries.collection
```json
{
    "0" : {
        "v" : 1,
        "name" : "_id_",
        "key" : {
            "_id" : 1
        },
        "ns" : "AkeroAL-prototype.entries"
    }
}
```

recap

THIS WORKS
```javascript
entries.ensureIndex({ actioned_on: 1 }, { safe: undefined, background: true, expireAfterSeconds: 32 })
```

THIS DOES NOT WORK
```javascript
entries.ensureIndex({ actioned_on: 1 }) { safe: undefined, background: true, expireAfterSeconds: 32 }  
```

**Comment by vkarpov15** [comment]
@Niffy that's just debug output, the underlying command should be the same. Are you saying that mongoose drops the index that you created manually? That's scary. Can you provide me a standalone script that reproduces this?

**Comment by Niffy** [comment]
Oh ok my bad, so its just the way the command is outputted in the debug then.
At one point it was dropping the index, but the next day I tried it again and it stopped dropping my index I created. Its pretty strange.
Sorry I can't be of any help.

**Comment by vkarpov15** [comment]
Yeah that seems a little odd - mongoose doesn't have code in place to drop indexes as far as I know. If that were happening that would be a major bug.

**Comment by vkarpov15** [comment]
Stale issue, reopen if this is still a problem

**Comment by morwalz** [comment]
I have existing database and i am trying to create indexes. original schema do not have any indexes. I am trying to create indexes using 
contactSchema.ensureIndex({ gender:1 });

or i tried index:true on field level. 
no indexes being created. Any help will be appreciated.

**Comment by vkarpov15** [comment]
Try listening to

```javascript
ContactModel.on('index', function(error) {
  console.log(error);
});
```

and see if there are any errors happening in the index build.

**Comment by morwalz** [comment]
@vkarpov15 Thank you for response. This worked to me. i was making silly mistake.

**Comment by prithiv2016** [comment]
is there a way to give the index an unique name ?

**Comment by vkarpov15** [comment]
Indexes get a unique index by default, no?

**Comment by the1mills** [comment]
as an aside, what does it mean `users.ensureIndex({ email: 1 })`, is this the same as `users.ensureIndex({ email: true })`?

**Comment by vkarpov15** [comment]
@the1mills yep those should be interchangeable.

**Comment by the1mills** [comment]
ok, thanks, I would just advise to use the boolean instead of the integer in any examples or docs, I don't know whose idea it was to ever use the int over the boolean in mongoose examples online, but unnecessary usage of an int instead of a boolean triggers me; if I see an int, I assume it can take values other than 1 or 0, etc etc.

**Comment by the1mills** [comment]
in other words, saving 3 characters is not enough of a reason to use 1 instead of true, etc.
