### ISSUE TITLE
Poor performance in 3.8.13

### ISSUE THREAD

**Issue by jdzuri** [Automattic/mongoose#2206]
Hi,

I recently upgrade my application dependencies from:

* "express" : "3.2.6",
* "mongoose" : "3.6.11"

to (case 1):

* "express" : "4.6.1",
* "body-parser": "1.5.0",
* "method-override": "2.1.1",
* "mongoose" : "3.6.11"

to (case 2):

* "express" : "4.6.1",
* "body-parser": "1.5.0",
* "method-override": "2.1.1",
* "mongoose" : "3.8.13"

and I notice a poor performance in the mongoose upgrade (last upgrade).

I have performed some benchmarks (publish it as a comment).

**Comment by vkarpov15** [comment]
This issue is stale and may be related to the memory leak that was fixed in 3.8.15. Re-open if this is still a problem.
