### ISSUE TITLE
index not work

### ISSUE THREAD

**Issue by TangMonk** [Automattic/mongoose#2212]
#My project files:

I have a `User` model:

**user.model.js**

    var UserSchema = new Schema({
        username:        { type: String, required: true, unique: true },
        location:        { 'type': {type: String, enum: "Point", default: "Point"}, coordinates: { type: [Number], default: [0,0]} },
    });
    
    UserSchema.index({location: '2dsphere'});

And have an Express route:

**user.route.js**

    function create(req, res) {
        User.create(req.body, function(err, user) {
            if (err) return res.send(err);
    
            return res.send(user);
        })
    }

**user.test.js**

    describe('test_user', function() {
        it('create user', function(done) {
            request('http://localhost/user')
                .post('/')
                .send({
                    username: 'john',
                    password: "123"
                })
                .end(function(err, res) {
                    if (err) cb(err);
                    done()
                });    
        });
    });

I have  a `drop_databse.js` file, it run every time before run test:

**drop_databse.js**

    var MongoClient = require('mongoose/node_modules/mongodb').MongoClient
    
    
    MongoClient.connect('mongodb://localhost/miccity_test', function(err, db) {
        if (err) return console.log(err);
        db.dropDatabase(function(err) {
            if (err) return console.log('drop databse failed!! :\n' + err);
            db.close();
        })
    })

#when I test

when I run test:

    $ node drop_database.js && mocha
    
      test_user
        ✓ create user
    
    
      1 passing (21ms)

But, I notice `user` collection in database has not index of `location` field !

But I create a single file:

**test.js**

    var mongoose = require('mongoose');
    var Schema       = mongoose.Schema;
    
    mongoose.connect('mongodb://localhost/miccity_test');
    var db = mongoose.connection;
    db.on('error', console.error.bind(console, 'mongodb connection error:'));
    
    
    var UserSchema = new Schema({
        username:        { type: String, required: true, unique: true },
       location:        { 'type': {type: String, enum: "Point", default: "Point"}, coordinates: { type: [Number], default: [0,0]} },
    });
    
    
    UserSchema.index({location: '2dsphere'});
    
    var User = mongoose.model('User', UserSchema);
    
    User.create({username: "test"}, function (err) {
        if (err) console.log(err);
    })

And run: `node drop_databse.js && node test.js`, then i check the index of location, it exist!

what is it wrong?

**Comment by vkarpov15** [comment]
No response for a while, re-open if this is still an issue.
