### ISSUE TITLE
Can I create unique index for subdocument?

### ISSUE THREAD

**Issue by raitucarp** [Automattic/mongoose#2226]
Is it possible to create unique index for subdocument? I mean, it may duplicate in other subdocument, but not same parent,

**Comment by stgogm** [comment]
Sorry for the bump but when looking for a solution, I figured this could help in the future:

```js

const schema = new Schema({
  value: String,
  another: Number,
  subdocs: [{
    prop: String, /* Should be unique */
    value: Number
  }]
});

/**
 * Check for duplicated sub document properties.
 */
schema.pre('validate', function validate(next) {
  var unique = [];

  for (var i = 0, l = this.subdocs.length; i < l; i++) {
    let subdoc = this.subdocs[i];

    if (unique.indexOf(subdoc.prop) > -1) {
      return next(new Error('Duplicated sub document!'));
    }

    unique.push(subdoc.prop);
  }

  next();
});
```
#### Explanation:
Let's asume that we have a schema with a `subdocs` property which contains a set of `subdoc` with a property called `prop` that must be unique. The idea is to keep track of the duplicated properties in an array called `unique` and check if the next one is already in the `unique` array.

I know it's not super-efficient but it works.

**Comment by vkarpov15** [comment]
Sure that works most of the time, but keep in mind that when you do a `.push()` to an array and then `.save()`, that becomes a `$push` to mongodb, so you can have 2 documents think they're saving a unique subdoc because they don't know they're `.push()`-ing the same one.

**Comment by stgogm** [comment]
@vkarpov15 The push is made to the `unique` array that only holds the values you want to be unique so you can check if any new values are also unique. It's intended to be used after you've made a `push` or `addToSet` but before saving the document. The `unique` array is temporary and It's not part of the mongo document :)

**Comment by vkarpov15** [comment]
Nah that's beside the point. Suppose you're trying to save 2 documents at roughly the same time from different JS programs - both do a `.find()` for the document, push on a sub-document with `prop = 'test'`, and try to save. Both will think that it's ok to insert `prop = 'test'` because their local copies of the document don't have that subdoc yet, so both will successfully `$push` it into mongodb. The issue is that doing `.push()` on a mongoose array translates to a [`$push` to mongodb](https://docs.mongodb.com/manual/reference/operator/update/push/), so there's no good way for us to enforce uniqueness within an array doc for all array operations...

**Comment by stgogm** [comment]
@vkarpov15 good point, didn't thought it for simultaneous inserts. Well, this seems a lot more complex but I'll try to figure it out :)

**Comment by vkarpov15** [comment]
Well your approach works as long as you call `markModified` on the props array _before_ calling push, then mongoose will always overwrite the whole array when saving to mongodb, so you don't have the same race conditions

**Comment by stgogm** [comment]
I figured out something else that seems to work, even in simultaneous updates.

Let's assume `subdocs.name` is the value we want unique:

```javascript
Model.update({
  _id: '576328595b2880f831413b92',
  'subdocs.name': {
    $ne: 'Unique Name'
  }
}, {
  $push: {
    subdocs: {
      name: 'Unique Name'
    }
  }
}).then((raw) => {
  // check raw.nModified value
}).catch(next);
```

**Comment by vkarpov15** [comment]
Great idea 👍 that should work well

**Comment by stgogm** [comment]
🙌

**Comment by wallawe** [comment]
@stgogm you just ended a 5 hour search, and for that, I'm grateful.

**Comment by ksuhiyp** [comment]
@vkarpov15 can you give me an example of how $addToSet can assure sub-document field uniqueness

Ive tried this 

`await Course.updateOne({ _id: id }, { $addToSet: { 'units.level': { name: body.name, level: body.level} } })
unitSchema.index({ level: 1 })
`    
But unit.level still accepts duplicates

**Comment by vkarpov15** [comment]
@ksuhiyp `unitSchema.index({ level: 1 }, { unique: true })` and make sure you also set `_id` to false in `unitSchema`, like:

```javascript
const unitSchema = new Schema({ name: String, level: Number }, { _id: false })
```

`$addToSet` works with subdocuments, but it looks for exact deep equality between documents, so if a subdoc has an `_id` then `$addToSet` will never catch a duplicate. See:

* https://mongoosejs.com/docs/api.html#schema_Schema-index
* https://mongoosejs.com/docs/guide.html#_id

**Comment by theutkarshsoni** [comment]
Thanks to @vkarpov15 You saved me.
