### ISSUE TITLE
Disconnect event isn't emitted when parseError is emitted

### ISSUE THREAD

**Issue by Quentin01** [Automattic/mongoose#2229]
When using mongoose with big documents, we sometimes get a `Parse Error`. We managed to track it down to the mongo library (it is already documented in numerous places).

Theorically, this should be fine. The connection will be disconnected, the request will be lost but then everything will work again. However, the `disconnect` event is not emitted, although `mongoose.connection.db.serverConfig._serverState` says `disconnected`. No other events are emitted, whether `disconnected` or `error`, on `mongoose` or `db` object.

**Comment by vkarpov15** [comment]
@Quentin01 so the `close` event is only at the server level, not the connection level. A quick fix would be to use

```
mongoose.connection.db.serverConfig.on('close', function() {
  console.log("NEVER CALLED");
});
```

I also opened up a PR against the stable branch of the node driver for this
