### ISSUE TITLE
feature: findByIdAndUpdateOne()

### ISSUE THREAD

**Issue by xpepermint** [Automattic/mongoose#2231]
I found this https://github.com/LearnBoost/mongoose/pull/803 but it's an old issue. I think we need support for `findByIdAndUpdateOne` function. The function should run `pre` and `post` callbacks and `validations`. Right now I have to do this:

```javascript
    let obj = yield MyModel.findById(id).exec();
    let _ = require('underscore');
    _.extend(obj, {name: 'something new'});
    console.log(yield obj.save());
```

The same applies to the destroy version. 

``` javascript
    let obj = yield MyModel.findById(id).exec();
    console.log(yield obj.remove());
```

I don't see this feature in the documentation.

**Comment by vkarpov15** [comment]
`findOneAndUpdate` now has its own pre and post hooks and has validation options, so this issue is no longer relevant.
