### ISSUE TITLE
document.save doesn't work with Schema.Types.Mixed

### ISSUE THREAD

**Issue by duran** [Automattic/mongoose#2249]
When a document is modified inside a `Schema.Types.Mixed` SchemaType the change is ignored in updates with the `document.save` function: 

``` js
var mongoose    = require('mongoose');

mongoose.connect('mongodb://localhost');


var schema1 = new mongoose.Schema({
    "number": Number,
    "mixed": mongoose.Schema.Types.Mixed
}, {
  'strict': true
});

var Model = mongoose.model('mixed', schema1);

var document = new Model({ "number": 1, "mixed": { "number": 1 } })

document.save(function(e, r, n){
    if(e) throw e;

    console.log("Inserted document? " + Boolean(n));

    document.number = 2;

    document.save(function(e, r, n){
        if(e) throw e;

        console.log("Updated number field? " + Boolean(n));

        document.mixed.number = 2;

        document.save(function(e, r, n){
            if(e) throw e;

            console.log("Updated mixed.number field? " + Boolean(n));
        });
    });
});


```

This script will print the following:

```
Inserted document? true
Updated number field? true
Updated mixed.number field? false
```

**Comment by kyleshrader** [comment]
Was this ever re-addressed?

**Comment by vkarpov15** [comment]
@kyleshrader nope. Outside of proxies, it isn't really possible for us to do change tracking for mixed docs.

**Comment by bsdunx** [comment]
+1, this tripped me up for a bit, first few hours of ever using mongoose and I tracked my woes down to this, I just happen to have many Mixed types, to due to polymorphic records
```javascript
const UnitSchema = {
    id: Number,
    type: Number,
    stats: [ Schema.Types.Mixed ],
    storage: [ Schema.Types.Mixed ],
    descriptor: Schema.Types.Mixed
}
```
is there a clean way create arbitrary fields without using Schema.Types.Mixed and adding a bunch of markModified calls?

**Comment by vkarpov15** [comment]
@bsdunx no not currently. You can also use `.set()` manually, like `unit.set('descriptor.foo', 'bar')` as a replacement for `unit.descriptor.foo = 'bar';`, that way you won't have to use `markModified()`
