### ISSUE TITLE
Mongoose docs encourage storing timezone-specific Dates on server, which is harmful

### ISSUE THREAD

**Issue by mikemaccana** [Automattic/mongoose#2258]
Mongoose examples frequently use JS `Date` objects for time. JavaScript `Date`s are in local timezone by default. **Using specific timezones for server-side data is generally considered bad practice**. See **[Daylight saving time and time zone best practices](http://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices)** or **[The 5 laws of API dates and times](http://apiux.com/2013/03/20/5-laws-api-dates-and-times/)**

Mongoose docs should encourage best practice for storing dates, specifically by replacing:

```
     time: { type: Date, default: Date.now },
```

with 

```
  time: { type: Number, default: function(){return new Date().getTime()} }
```

**Comment by deepaksisodiya** [comment]
Is there any way we can save date object in timestamp in mongoDB?

Regards
Deepak Sisodiya

**Comment by vkarpov15** [comment]
AFAIK that's not possible with mongoose atm.

**Comment by ktkaushik** [comment]
This actually clears a lot of doubts regarding dates around mongoose. 👍

**Comment by vkarpov15** [comment]
@ktkaushik yeah dates in JS in general are confusing. Nowadays I just end up using https://www.npmjs.com/package/mongodb-moment and just using moment for everything, makes things a lot more sane.

**Comment by nateislate** [comment]
I'm not sure if this is related but if I save a date from the application (using Mongoose) the date gets "truncated" e.g. `Tue, 15 Nov 2016 01:48:24 GMT` is a date that's saved to the database from the application with `new Date()` but if I used a default date in the (Mongoose) model e.g. `appointment: {type: Date, default: new Date(Date.now() + 60 * 60 * 1000)}`generates a date with the following format: `Tue Nov 15 2016 01:36:26 GMT+0000 (UTC)`, as you can see the default date gets created with the offset and without the comma after the day. When I log `new Date()` from the application it also has the offset (and it's without a comma as well) so I would have to assume that Mongoose is modifying the date and this causes `{ $gte: new Date() }` or `{ $gt: new Date() }` to not find any matches when there are actually documents that match but the date formats are slightly different. `Mongoose version 4.3.3`, is this suppose to have this behaviour?

**Comment by vkarpov15** [comment]
@nateislate are the dates saved as actual dates in the database or as strings? If they're saved as dates, the string format and offset doesn't matter because dates in mongodb are just 64-bit ints.

**Comment by nateislate** [comment]
@vkarpov15 Which is what I thought. The attribute on the model looks like this: `appointment: {type: Date, default: new Date(Date.now() + 60 * 60 * 1000)}` this is with `findOneAndUpdate` & `{new: true, upsert: true}` but a `{$gte: .....}` query doesn't seem to work. I'll have to do some more digging. It works as expected when I save the date from the application but not if I use `default: new Date(Date.now() + 60 * 60 * 1000)`.

**Comment by vkarpov15** [comment]
So defaults don't get applied on `findOneAndUpdate` unless you set the `setDefaultsOnInsert` option to true.

**Comment by th0r** [comment]
@nateislate
`default: new Date(Date.now() + 60 * 60 * 1000)` is calculated once and `Date.now()` there will be the number of milliseconds passed since 1970 till the moment you require your schema module and `60 * 60 * 1000` will add and hour to it.
In other words it doesn't make a lot of sense for me...

**Comment by emirmamashov** [comment]
Iam found solition in mongoose-timezone - mongoose plugin to normalize stored dates timezone
see here https://www.npmjs.com/package/mongoose-timezone

**Comment by azmolmiah** [comment]
This timestamp `2020-05-03T11:00:00.000Z` from mongoose `Sun May 03 2020 12:00:00 GMT+0100 (British Summer Time)`, would it output a different time in any other country? I'm hoping it does, this would mean a lot of ease.

**Comment by vkarpov15** [comment]
@azmolmiah yes it does. JavaScript formats dates according to the local timezone in Node.js or the browser.

Mongoose doesn't store timezones with dates, in MongoDB dates are stored as 64 bit ints.

**Comment by kenkopelson** [comment]
For reference:

https://mongoosejs.com/docs/tutorials/dates.html
