### ISSUE TITLE
Get raw value for "foreign key"

### ISSUE THREAD

**Issue by Neamar** [Automattic/mongoose#2259]
Let's say I have a User which belongs to a Company using 

``` js
  company: { type: ObjectId, ref: 'Company', required: true },
```

Sometimes, we get a Mongoose model from "somewhere" and there's no way for us to get in a single call the company value -- we always have to check "is it populated ?".

In short, to reliably get the company id, we have to write in _every_ place `user.company._id || user.company`. This is error-prone and is often forgotten -- plus it's not easy to test, as two tests are needed for every function.

Could you add a way to get the raw-value? Something like a `populated`, but working even without a populate call : `user.company_raw` or `user.raw('company')`

**Comment by vkarpov15** [comment]
We added `objectIdGetter` option in #6588 that lets you just do `user.company._id`, even if `company` is an ObjectId. Should be fixed in Mongoose >= 5.1.0.
