### ISSUE TITLE
3.9 - Cannot read property find/findOne of undefined

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#2275]
I'm using version 3.9 in a Koa app and getting some strange result when trying to use a query (model creation and saving is ok):

``` js
  yield user = User.findOne({ 
    query here
  }).exec();
```

causes:

```
error: TypeError: Cannot read property 'findOne' of undefined
    at Query.findOne (/home/matteo/Dev/koa-app/node_modules/mongoose/node_modules/mquery/lib/mquery.js:1679:19)
    at Query.findOne (/home/matteo/Dev/koa-app/node_modules/mongoose/lib/query.js:1145:22)
    at Query.exec (/home/matteo/Dev/koa-app/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2230:16)
    at Query.exec (/home/matteo/Dev/koa-app/node_modules/mongoose/lib/query.js:1779:19)
    at Object.authenticateMiddleware (/home/matteo/Dev/koa-app/src/middlewares/auth.js:15:6)
    at GeneratorFunctionPrototype.next (native)
    at Object.<anonymous> (/home/matteo/Dev/koa-app/node_modules/koa-router/node_modules/koa-compose/index.js:29:12)
    at GeneratorFunctionPrototype.next (native)
    at next (/home/matteo/Dev/koa-app/node_modules/co/index.js:74:21)
    at Object.<anonymous> (/home/matteo/Dev/koa-app/node_modules/co/index.js:45:5)
```

But of course User is defined and find/findOne are properties of it

Also:

```User.findOne({}, function(){
    console.log(arguments)
  });

```

without yield ends n the same error, if I don't add the callback instead is ok. Using exec() it always throw the error, yield or not yield
```

**Comment by sudhanshugaur4** [comment]
To get the solution check following things.
1. Check model name which you have defined or the name of the folder where all your models are present must be right because in my case in models folder where i have defined all my models i was using different model name so as there was no model named that, thats'y i was getting the error. 
2. Check Schema name or folder name where it is located.

**Comment by brunodb3** [comment]
Hello guys. 

I have the same error, but changing Mongoose versions didn't work for me. My code is fairly similar, I'm using Mongoose 4.11.5, but I've tried 5.0.15 and 3.8.8 (which gives me an error with indexes).

Before I was using multiple models, creating new ones for each request (which then I found out was a pretty bad practice), but even after changing to creating the models only once didn't work for me, I'm still stuck. I don't know if this is an issue with Mongoose itself, or with my code (I'm using Promises with async/await by the way). Here's the snippet that throws the error:

```
async function findSingle(query, accountName) {
  let foundAutomation;

  try {
    // Creating the model
    const Automation = new AutomationModel(accountName);

    // TODO:
    // check error on this
    console.log('query: ', query);

    foundAutomation = await Automation.findOne(query).exec(); // code stops here
    
    // nothing from here and below is run
    console.log('after: ', foundAutomation);

    // checking if automation was found
    if (foundAutomation) {
      // assigning total_leads value
      foundAutomation.total_leads = foundAutomation.lead_list.length || 0;
    }
  } catch (error) {
    // Returning as a promise reject
    return Promise.reject(error);
  }

  // Returning as a promise resolve
  return Promise.resolve({
    status: 200,
    success: true,
    message: 'Automation found',
    automation: foundAutomation
  });
}
```

**Comment by vkarpov15** [comment]
@brunodb3 what is `AutomationModel` in the above code?

**Comment by brunodb3** [comment]
@vkarpov15 Sorry, forgot about that. It's the model file/class containing the schema for Mongoose, as follows:

```
// Importing modules
const bluebird = require('bluebird');
const mongoose = require('mongoose');
const mongoosePaginate = require('mongoose-paginate');

// Setting the mongoose promise as global (mpromise is deprecated)
mongoose.Promise = bluebird;

// Setting default pagination options
mongoosePaginate.paginate.options = {
  limit: 10,
  lean: true
};

// Creating the schema for mongoose
const automationSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  }); // there's some other properties, but not relevant

// Enabling pagination plugin (see 'github.com/edwardhotchkiss/mongoose-paginate')
automationSchema.plugin(mongoosePaginate);

// Exporting the mongoose model
module.exports = mongoose.model('Automation', automationSchema);
````

**Comment by vkarpov15** [comment]
So then why do you have `const Automation = new AutomationModel(accountName);` ? Why are you creating a new document and then `Automation.findOne()`?

**Comment by jitupardhi7694** [comment]
leave a comment
