### ISSUE TITLE
have all queries return a promise without `.exec()`

### ISSUE THREAD

**Issue by jonathanong** [Automattic/mongoose#2297]
should be able to jsut do `var users = yield User.find()`

**Comment by vkarpov15** [comment]
In 4.0.x, mongoose has this feature courtesy of [mquery](https://github.com/aheckmann/mquery) >= 1.1.0.

**Comment by pnedelko** [comment]
@vkarpov15 Do I understand correctly, that in mongoose 4.0.x it's safe to do `var users = yield User.find()`? Im asking, because documentation says, that `.exec()` should be called.

**Comment by vkarpov15** [comment]
@pnedelko yep it's safe. Where in the docs does it say that? `Users.find().then()` is really just shorthand for `User.find().exec().then()` anyway.

**Comment by pnedelko** [comment]
@vkarpov15 On this page: http://mongoosejs.com/docs/promises.html there is an example:
```js
yield MyModel.findOne({}).exec()
```

**Comment by vkarpov15** [comment]
Yep that example works. This behavior is supported as of 4.0.0
