### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by trisys3** [Automattic/mongoose#2298]
Is there IPv6 support for Mongoose? I couldn't find anything one way or the other on Google or in any of Mongoose's documentation, but from coding myself it doesn't seem like it. For example, when I run `mongod --bind_ip [IPv6-enabled host] --ipv6`, then run my application, `mongoose` can't connect to the host, but when I start the server without `--ipv6` then run my application, `mongoose` connects.

If there isn't support, is there a timeframe on when it will be added? This isn't urgent for my application, I'm just worried about the future as more networks become IPv6-only.

**Comment by vkarpov15** [comment]
So node driver supports ipv6, but mongoose mistakenly occludes this functionality because [muri](http://npmjs.com/package/muri) can't parse ipv6 addresses
