### ISSUE TITLE
sort and limit array

### ISSUE THREAD

**Issue by ChitaGideon** [Automattic/mongoose#2312]
When I use limit and sort option with populate, I always get the wrong length of the populated array

```
MatchSchema = new Schema
    paints:[{type:Schema.ObjectId}]

 Match.find()
    .limit(matchSize)
    .skip((matchPage-1)*matchSize)
    .sort('-created_at')
    .populate {
        path: 'paints'
        select:PAINT_PROPERTY
        options:{
          sort: { vote: -1 ,created_at: -1 }
          limit:paintSize
          skip:(paintPage-1)*paintSize
          match:{
            deleted:0
}
}
}
```

**Comment by svnindia** [comment]
populate with options skip working fine ?

**Comment by vkarpov15** [comment]
@svnindia can you please clarify? I don't understand.

**Comment by svnindia** [comment]
.populate({  path: 'students',  match: { _id: '1'},  select: 'name mobile',
  options: { limit: 5,skip:2 sort: 'name' } }) .exec()

For sub document pagination

**Comment by vkarpov15** [comment]
That seems like it should work. Is it not working?

**Comment by svnindia** [comment]
yes its not working

**Comment by vkarpov15** [comment]
Can you show me what your schemas look like?

**Comment by svnindia** [comment]
I need to perform pagination for subdocument array listing.

sample : https://gist.github.com/svnindia/213c74f6000db3ba4182

Solution : currently using aggregate with $unwind

**Comment by vkarpov15** [comment]
@svnindia You're not actually using `populate()` in the above gist. You're embedding an array of students in your `Schools` schema, so you don't need to use `.populate()`. If your students array is sufficiently big that you need to paginate, I recommend you don't store an array of students in the `Schools` schema, and instead query for students based on the school they're in. For instance `Student.find({ school: schoolId }).sort().limit().skip()`. You may want to review [the population docs](http://mongoosejs.com/docs/populate.html).
