### ISSUE TITLE
"name":"MongoError","ok":0,"errmsg":"can't find ns"

### ISSUE THREAD

**Issue by xiaojunl** [Automattic/mongoose#2313]
Upgrade from version v3.8.8 to v3.8.16,invoke getNear.

**Comment by sumerpatel7** [comment]
{ $geoNear: { near: { type: "Point", coordinates: [parseFloat(user_result.lng), parseFloat(user_result.lat)] }, distanceMultiplier: 0.001, maxDistance: 100000, spherical: true, distanceField: "dist.calculated", query: { lat: { $ne: '' }, lng: { $ne: '' } } } }

This will solve your problem with ns.
