### ISSUE TITLE
virtual path on array

### ISSUE THREAD

**Issue by cncolder** [Automattic/mongoose#2326]
in mongose guild doc there is a cool example. define `.full` virtual on sub documents `name: {first:String, last:String}`. then get virtual value by `name.full`.

but if i define virtual on array like this:

``` js
var schema = new Schema({
  nums: [Number]
});
schema.virtual('nums.odd').get(...).
```

i cannot get it by dot path `nums.odd`. only write like this `model.get('nums.odd')`.

is there a way to fix this?
i'm running mongoose@3.9.3

**Comment by vkarpov15** [comment]
We can't support `schema.virtual('str.upper')` because you can't define getters on primitive values in JavaScript, but `schema.virtual('nums.last')` and `schema.virtual('nums.odd')` are possible. We put in PR #14955 to add that feature.
