### ISSUE TITLE
Mongoose leaks memory with every connection

### ISSUE THREAD

**Issue by azylman** [Automattic/mongoose#2337]
If you run this script, you can watch your machine slowly run out of memory:

``` javascript
var _        = require('underscore');
var async    = require('async');
var mongoose = require('mongoose');

always = function() {return true};

var i = 0;
var makeAndCloseConnection = function(cb) {
  console.log(i++);
  mongoose.createConnection().close();
  setImmediate(cb);
};

async.whilst(always, makeAndCloseConnection, function() {});
```

Presumably this is because every connection gets added to a global list of connections: https://github.com/LearnBoost/mongoose/blob/master/lib/index.js#L162

Is there a reason not to remove it when the connection is closed?

**Comment by sibelius** [comment]
what is the recommended way to fix this?

**Comment by vkarpov15** [comment]
@sibelius the workaround is to remove connections from the `mongoose.connections` list. What's your use case for programatically creating new connections?

**Comment by vkarpov15** [comment]
We can close this now that we have [`Connection.prototype.destroy()`](https://mongoosejs.com/docs/api/connection.html#Connection.prototype.destroy()), which destroys the connection and removes it from Mongoose's `connections` array, letting it get GC-ed.
