### ISSUE TITLE
Support for atomic $inc without special Mongoose Number type

### ISSUE THREAD

**Issue by mstdokumaci** [Automattic/mongoose#2357]
Document already has a method **set** which is used like:

``` js
doc.set(path, val, [type], [options])
```

Similar to set, there might be an **inc** method like:

``` js
doc.inc(path, amount, [options])
```

So I can increment any field easily before saving an open document with other pending updates.
Example:

``` js
model.findById(id, function(err, doc) {
  if (doc.check_field) {
    doc.other_field = 'Other String';
  }
  doc.inc('number_field', 1);
  doc.save(callback);
});
```

**Comment by alobodig** [comment]
This would be great. Is there anything still holding this back?

**Comment by vkarpov15** [comment]
The odd quirks that come when you mix atomic increment with mongoose validators - 2 event handlers could easily `inc()` and then `save()` and both think they're not breaching the maximum. The neat thing about the fact that `save()` only uses `$set` is that validation will always catch errors, whereas we can't really validate `$inc` against `min` and `max` validators without some notion of validation in the mongodb server, which may be coming in a future release but doesn't exist today. As an aside, this is precisely why [update validators](http://mongoosejs.com/docs/validation.html) ignore `$inc`.

If you really want atomic increment then you can always just use `.update()` directly.
