### ISSUE TITLE
The database's name is changed??!!!

### ISSUE THREAD

**Issue by shawninmove** [Automattic/mongoose#2359]
var Person = require("../model").Person;
var mongoose = require("mongoose");

mongoose.connect("mongodb://localhost/person");
var person = mongoose.model("Person", Person);

var p = new person({name: "inmove", age: 23});

p.save(function(err, result) {
    if(err)
        console.log(err);
    else
        console.log(result);
##  });

with this code , i think i should get a collection called <person>.But, i got a collection called people?!!Could you plese tell me how did this happen?

> use person
> switched to db person
> show tables
> people
> system.indexes

**Comment by vitkuz** [comment]
I stumble upon this surprising behavior in 2020. I am confused
