### ISSUE TITLE
Unable to install Mongoose on Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by Bristlecone** [Automattic/mongoose#2362]
When tried `npm install` on Windows Server 2008 R2 SP1, it gives the following messages

C:\Users\someFolder>npm install mongoose-
> kerberos@0.0.3 install C:\Users\SomeFolder\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm WARN optional dep failed, continuing kerberos@0.0.3
npm WARN optional dep failed, continuing kerberos@0.0.3
mongoose@3.8.8 node_modules\mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@0.3.1
├── hooks@0.2.1
├── mpath@0.1.1
├── mpromise@0.4.3
├── ms@0.1.0
├── mquery@0.5.3 (debug@0.7.4)
└── mongodb@1.3.23

> bson@0.2.5 install C:\Users\SomeFolder\node_modules\mongoose\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

When I run the app, I receive the following error

C:\Users\Somefolder>node app.js

module.js:340
    throw err;
    ^
Error: Cannot find module 'bson'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Somefolder\node_mod
ules\agenda\node_modules\mongoskin\node_modules\mongodb\lib\mongodb\collection.j
s:10:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by GIOkafor** [comment]
I have the exact same problem only difference is I'm not doing anything with mongoskin 
(node-gyp rebuild 2> builderror.log) || (exit 0)

When I run 'node server.js' this gets returned:

module.js:340
    throw err;
          ^
Error: Cannot find module 'bson'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\someUser\Desktop\showtra
ckr\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:10:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by GIOkafor** [comment]
I have the exact same problem only difference is I'm not doing anything with mongoskin 
(node-gyp rebuild 2> builderror.log) || (exit 0)

When I run 'node server.js' this gets returned:

module.js:340
throw err;
^
Error: Cannot find module 'bson'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\someUser\Desktop\showtra
ckr\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:10:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)

Any help would be really appreciated thanks.

**Comment by vkarpov15** [comment]
Did your `npm install` succeed? Looks like bson just isn't there.

**Comment by GIOkafor** [comment]
It didn't say, all I get is `(node-gyp rebuild 2> builderror.log) || (exit 0)` and then nothing happens until I hit `Ctrl+C`. However checking the `node_modules` folder, I find the mongo folder there but when I call `node server.js` the error shows up.

**Comment by vkarpov15** [comment]
Try wiping out your `node_modules` folder and then doing a clean `npm install`. That may help.

**Comment by GIOkafor** [comment]
Tried doing that it runs and gets stuck showing this: `(node-gyp rebuild 2> builderror.log) || (exit 0)` tried starting up my server again and it gives me the same error. I even tried deleting just the individual mongo folder and that didn't help either.

**Comment by GIOkafor** [comment]
![debugimg](https://cloud.githubusercontent.com/assets/7291283/5905041/178a82d6-a55b-11e4-91cd-9a34200ec992.jpg)

**Comment by vkarpov15** [comment]
Ok so the kerberos library's what's hanging up. Try doing `npm install mongoose --no-optional`, that will skip the kerberos library. Hopefully that'll help.

**Comment by GIOkafor** [comment]
Got this as a result of running that, once again with verbose
![debu2](https://cloud.githubusercontent.com/assets/7291283/5918279/0055fd1c-a5f5-11e4-91d1-1f61f301d96a.png)

**Comment by vkarpov15** [comment]
Hmmm do you have python and visual studio installed on this machine? `node-gyp` requires those two for some strange reason. Also, if you have those installed, try:

```
npm install --msvs_version=<visual studio version>
```

As suggested [here](https://github.com/joyent/node/issues/4047)

**Comment by GIOkafor** [comment]
I have python installed but not visual studio, installing that right now. Will try after that and let you know how it goes. Thanks.

**Comment by GIOkafor** [comment]
Tried running the command with visual studio installed and I get a message saying the syntax is incorrect.

**Comment by vkarpov15** [comment]
Which version of VS?

**Comment by GIOkafor** [comment]
Visual studio community 2013

**Comment by vkarpov15** [comment]
Can you show me the error message output?

**Comment by GIOkafor** [comment]
Here it is: 

![debu3](https://cloud.githubusercontent.com/assets/7291283/5988986/81a01e9a-a945-11e4-891a-b5f40510f035.png)

**Comment by vkarpov15** [comment]
Hmm looks like you're passing an incorrect visual studio syntax. Try just running `npm install`, followed by `npm install --msvs_version=2013` if the first command doesn't work.

**Comment by GIOkafor** [comment]
Both commands worked fine, but `npm install mongoose --no-optional --verbose` freezes like before and has the same output of the second image I uploaded.

**Comment by goforgold** [comment]
I faced similar issues today. After a lot of Google searches it worked with following way

`npm install -g mongodb --python=python27 --msvs_version=2013`

Issues was:

1. I had latest python installed on my windows machine (3.4) but mongodb required lower version. So I just grabbed that version and installed it and specified which version of python should be used when compiling `moongodb`.
2. It was trying to use Visual Studio 2010 tools to build. I have VS2013 installed so I found out a way to which VS version to use.

And it worked.

But still it is the first node module which I couldn't install with a single command. I had to waste nearly 2 hour in installing it.

I am not happy with it. I still have questions like:

1. Why Python is required to use mongodb with NodeJs ?
2. Why VS is required at all ?

Why can't I simply install it like a just one another npm modules ?

**Comment by vkarpov15** [comment]
First, you can install mongoose without the node-gyp dependencies at all. You just won't get the C++ bson parser, you'll get the JavaScript BSON parser. In theory, if you install mongoose without python or VS, you'll just get a js-bson warning when your application starts.

Re: 1 and 2, the python and VS dependencies come via the [mongodb C++ bson parser](https://www.npmjs.com/package/bson) and [kerberos auth module](https://www.npmjs.com/package/kerberos). These are implemented as nodejs native add-ons, which need to be compiled via https://github.com/tootallnate/node-gyp, which wraps the V8 build tool 'gyp', which requires python and VS on Windows. Trust me, I dislike this dependency as much as you do, but there's a good reason for it. The reason is that the C++ bson parser has marginally less memory overhead and more predictable performance than the JavaScript implementation, and because AFAIK you can't really implement Kerberos auth on windows without being able to call secur32.dll directly. We'd like to figure out a way to close the gap on bson parser performance, but for now you just get a fallback to the JavaScript bson implementation.

**Comment by Johnaka** [comment]
![capture](https://cloud.githubusercontent.com/assets/11838212/9037659/00d17d74-3a07-11e5-85e5-564db50465b4.JPG)

i have similar issue, when i type npm install --save mongoose it gives me that on picture above,
then i waits for about 10 min an then gives me second picture. 
![capture2](https://cloud.githubusercontent.com/assets/11838212/9037882/eb625a60-3a08-11e5-91f1-c15e3ec562af.JPG)

i have python 2.7.10 installed i am running on windows 10, and i don't have visual studio installed,
but i have visual c++ redistributables  installed for vs2013 and vs2015 do i need to install the whole ide ? and which one ? and will it be enough if i custom install only C++, i don't want to install F# C# VB or anything else,  thank you ))

**Comment by Johnaka** [comment]
![capture3](https://cloud.githubusercontent.com/assets/11838212/9038278/974fe722-3a0c-11e5-8172-991e26af792d.JPG)
one more thing is this picture after all of these warnings, thank you.

**Comment by vkarpov15** [comment]
I don't see any real warnings above, looks like a normal npm install. If you upgrade to latest mongoose you shouldn't even see the messages about bson-ext.

**Comment by Johnaka** [comment]
it looks like normal but it is not included in my dependencies after installation and then it gives me an error when i try to interact with mongodb! ?? so frustrating i am trying to fix this since two days now, hey about visual studio can you tell me what to do ? i dont really use that i use visual studio code.
is it enough for node if i have redistributables ? thank you

**Comment by vkarpov15** [comment]
What's the error? And you shouldn't need visual studio at all unless you care about integrating mongodb into your kerberos cluster.

**Comment by Johnaka** [comment]
hey it's freaking worked i just turned my laptop on and it worked ??

**Comment by Johnaka** [comment]
hey can you help me with this one ? 
![capture](https://cloud.githubusercontent.com/assets/11838212/9053347/60bbceac-3a8d-11e5-9c62-6c8fb214930f.JPG)

**Comment by Johnaka** [comment]
here is the error i was getting
![capture2](https://cloud.githubusercontent.com/assets/11838212/9053834/e23823ee-3a93-11e5-9005-1e79f374af9b.JPG)
it gives me an error if i am not connected to the internet, is there any ways i can work offline ? thank yo u

**Comment by Johnaka** [comment]
hey man i figured this out. app.use(multer({dest:'./public/images/uploads/'}).single('photo'));
i was using. app.use(multer({dest: './public/images/uploads'}));
now it works perfectly i love coding, again

**Comment by vkarpov15** [comment]
Glad you figured it out :beers:
