### ISSUE TITLE
Post init event does not fire after document creation

### ISSUE THREAD

**Issue by ioncreature** [Automattic/mongoose#2363]
Here is CardType.js

``` js
var CardType = new Schema({
    name: {type: String, required: true},
    //...
});

CardType.post( 'init', function(){
    this._original = this.toObject();
});
```

I expect that all documents will have `_original` field

``` js
CardType.create( [{name: 'test'}, {name: 'test2'}], function( error ){
    var cardTypes = Array.prototype.splice.call( arguments, 1 );

    cardTypes.forEach( function( doc ){
        console.log( doc._original );
    });
});
```

`doc._original` always return `undefined`

Is it expected behavior or bug?

**Comment by bshamblen** [comment]
Similar to the code in the original issue above I was storing a copy of the existing document in the post `init` hook, then in the pre `save` hook I was comparing the original document with the updated doc (if not new), then in the post `save` hook I had logic to send a notification of the changes. 

As @ioncreature mentioned in his original post, this all used to work. Once I upgraded to 4.0 I received the same error message `Object #<EventEmitter> has no method 'toObject'`. I've been trying to come up with a workable solution, but I can't see a way to persist the original document through to the post `save` event.

**My original code**

	schema.post('init', function() {
		this._original = this.toObject();
		this._changes = []; //array of objects with the path, new and old values. Populated by `observe` function in pre `save` hook
	});

    schema.pre('save', function(next) {
		//other logic here. Cut out for this example..

		this.observe(); //compares the current doc with the original and stores the new and old values in `this._changes` array.
		next();
	});

    schema.post('save', function(doc) {
		if (this._original && this._changes.length > 0) {
			//send web hook notification, with changes
		} else {
			//send web hook notification, with new document
		}

        //reset the values, in case the document is saved again.
		this._original = null;
		this._original = this;
		this._changes = [];
	});

The problem with the new post `init` architecture is that if I now add a parameter to the hook function I can get the `doc` and add a copy to itself, but that copy will no longer be available in the pre or post `save` hooks. 

**Changed to**

    schema.post('init', function(doc) {
		doc._original = doc.toObject();
		doc._changes = [];
	});

But in the pre `save` hook `this._original` is undefined, even for documents that we returned from the database. Any suggestions on how to reliably save a copy of the original document and have is survive the document lifecycle.

**Comment by vkarpov15** [comment]
Please open up a separate issue for that, that is an unrelated issue.

**Comment by azhang** [comment]
I'm still having this issue in 4.2.6. Perhaps it should be removed from the documentation? http://mongoosejs.com/docs/middleware.html

**Comment by ClaytonSmith** [comment]
Is there a workaround for this issue? I need a way to apply some `foo`s and `bar`s to my model's data only when the doc is first created.

**Comment by vkarpov15** [comment]
@ClaytonSmith `var foo = function() { this.bar = 'baz'; }; schema.queue(foo);` foo gets called every time a document with that schema is created.

**Comment by jeremejevs** [comment]
@vkarpov15 Please, update your last comment with a proper example of `schema.queue` usage, like [here](https://github.com/Automattic/mongoose/issues/672#issuecomment-178038854). This was quite misleading, considering that it can't be found in the docs.

Also, I'd like to note that it's synchronous only.

**Comment by vkarpov15** [comment]
@jeremejevs thanks for pointing this out, fixed :+1:

**Comment by vkarpov15** [comment]
I'm going to close this for now, `schema.queue()` is the way to go.

**Comment by vkarpov15** [comment]
See https://mongoosejs.com/docs/api.html#schema_Schema-queue
