### ISSUE TITLE
Saving the same document twice concurrently will override the other

### ISSUE THREAD

**Issue by totty90** [Automattic/mongoose#2367]
Saving the same document twice concurrently will only save one.

I have this flow in my app:

`doc.money = 0`

 - get doc (flow 1)
 - get doc (flow 2)
 - change doc.money += 5 (flow 1)
 - change doc.money += 10 (flow 2)
 - save doc (flow 1)
 - save doc (flow 2)
 
Now my `doc.money` is equal to 10 instead of 5.

How to fix this problem? Not even an error is thrown...

Update with inc: 5 can't be used in my app.

**Comment by vkarpov15** [comment]
No update for a while. Re-open if still an issue.
