### ISSUE TITLE
DISCUSSION: is there any way to have a discriminatorKey of type Int32?

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2369]
In other words, there would be a mapping between the value of the discriminated schema name and the value stored in database for __t. Taking the example in the documentation about various modes of Transportation:
- Car would persist with __t === 0,
- Bus would persist with __t === 1,
- Train would persist with __t === 2,

This would especially make sense (1) for reduced storage/indexing space, and (2) for i18n.

Any way to achieve this with current version (3.8.16 - 3.8.17)?

**Comment by vkarpov15** [comment]
Use https://www.npmjs.com/package/mongoose-int32
