### ISSUE TITLE
Remove field/path from schema

### ISSUE THREAD

**Issue by talha-asad** [Automattic/mongoose#2398]
Is there a way to remove a field/path from a schema object, once it has been added.

I would like to create discriminators that have less fields then the baseSchema. Is this something i hack around as i don't see a function in the API docs?

**Comment by geloescht** [comment]
This has been added in commit 5d459c2d6940bf4259921c7d9234ce2b12a3873e. However, the solution is incomplete, because it does not update Schema.tree. This causes subsequent problems if a virtual of the same name is added.

**Comment by geloescht** [comment]
Hack on top of the hack, seems to work:
```javascript
Schema.prototype.remove = function(path) {
  if (typeof path === 'string') {
    path = [path];
  }
  if (Array.isArray(path)) {
    path.forEach(function(name) {
      if (this.path(name)) {
        delete this.paths[name];
        
        // update the tree
        var subpaths = name.split(/\./),
            last = subpaths.pop(),
            branch = this.tree;

        subpaths.forEach(function(sub, i) {
          branch = branch[sub];
        });
        
        delete branch[last];
      }
    }, this);
  }
};
```

**Comment by vkarpov15** [comment]
Good call, this needs to get fixed

**Comment by natanavra** [comment]
Sorry for re-opening this old issue
It seems to be working only for root/top level fields && simple fields (non Object)
How would you go about removing a subpath?

e.g.
```
const schema = new mongoose.Schema({
  name: String,
  settings: {
    key: Number
    key2: Number
  }
})

schema.remove('name') //works
schema.remove('settings.key2') //does not work
schema.remove('settings') //does not work either
```

**Comment by vkarpov15** [comment]
@natanavra can you provide code samples showing what you mean about "Removing a nested property from a discriminator"?
