### ISSUE TITLE
Field still returned with {myField: 0} or '-myField' when finding docs.

### ISSUE THREAD

**Issue by totty90** [Automattic/mongoose#2407]
User.find(conditions, '-email -password', cb);

Still returns the email and password. Last version of mongoose.

With mongodb debug mode, the output shows that is filtering correctly.

    Mongoose: users.find({ ... }) { fields: { email: 0, password: 0 }, safe: true }  

Update: putting {email: 1} hides some other fields. This is a big bug or what?

    Mongoose: users.find({ ... }) { fields: { email: 1 }, safe: true }  

Is mongodb messed up or what? I'm using 2.6.5v. But from command line works ok.

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
