### ISSUE TITLE
pre( 'validate' ) on parent fires after subdocuments have run validation.

### ISSUE THREAD

**Issue by AshHeskes** [Automattic/mongoose#2430]
The name `pre` is suggestive of runs before any validation. The current behaviour causes validation to run and fail on subdocuments with `required : true` fields, before `pre('validate')` is fired on the parent. However I have found that validators added to subdocuments via `path('foo').validate` are not invoked before `pre('validate')` on the parent.

**Comment by vkarpov15** [comment]
This was fixed. Not sure which version but 4.9.4 runs parent pre validate hooks before child pre validate hooks.
