### ISSUE TITLE
Listing last message of each conversation?

### ISSUE THREAD

**Issue by nasserprofessional** [Automattic/mongoose#2437]
So basically I have a database that looks like this:
{
  "_id": ObjectId("5458009c1ab2354c029d7178"),
  "to": "dan",
  "from": "wood",
  "message": "hi dan how are you?",
  "time": new Date(1415053468590),
  "__v": 0
}
{
  "_id": ObjectId("545800b45eaf364d026c1cba"),
  "to": "wood",
  "from": "dan",
  "message": "hi wood how are you?",
  "time": new Date(1415053492125),
  "__v": 0
}
{
  "_id": ObjectId("5458009c1ab2354c029d7178"),
  "to": "billy",
  "from": "wood",
  "message": "hi billy how are you?",
  "time": new Date(1415053468590),
  "__v": 0
}
{
  "_id": ObjectId("545800b45eaf364d026c1cba"),
  "to": "wood",
  "from": "billy",
  "message": "hi wood how are you?",
  "time": new Date(1415053492125),
  "__v": 0
}
So how can I retrieve the last message from each conversation that the user "wood" may have?

My database schema looks like this:
var messageSchema = new Schema({
to: { type: String, required: true},
from: { type: String, required: true},
message: { type: String, required: true},
time : { type : Date, default: Date.now }
});

I am using node.js mongoose and mongodb.

I have asked other places but cant seem to find any examples or any help.

I am new to mongoose and node.js I come from a php mysql background.
If you need any more information or dont understand something please ask.

Would be great if someone can post what my query should look like. I really appreciate all the help. Thank You

**Comment by samueldelesque** [comment]
For reference, I was having that same issue. Solution is to build a "conversationId" that is a merge of "to" and "from" fields and then group the results by conversationId in your aggregate.

See my answer here: http://stackoverflow.com/a/34403517/1970575
