### ISSUE TITLE
mongoose plugin requires first argument of "next" be type of Error

### ISSUE THREAD

**Issue by mocheng** [Automattic/mongoose#2441]
It cost me hours to figure out bug in below code. 

``` javascript

calendarSchema.pre('save'， function(next) {
    if (this.begin_time > this.end_time) {
       return next('begin time should be earlier than end time');
   }

   next();
});

```

If `next` is invoked with first argument as object not in `Error` type, it just silently fail without trigger callback of `save`.

I believe this should be improved. `next` can transfer first argument into `Error` if it is string or else.

**Comment by vkarpov15** [comment]
This is fixed in 3.9.x
