### ISSUE TITLE
Sparse and Unique Index not working for Schema-level index

### ISSUE THREAD

**Issue by c1moore** [Automattic/mongoose#2457]
I am trying to create an index on two fields of a schema that are to be unique and sparse as follows:

```
var ArraySchema = new Schema ({
	user_id: {type: mongoose.Schema.Types.ObjectId, ref:'User'},
	event_id: {type: mongoose.Schema.Types.ObjectId, ref:'Event'}
}, {_id:false});

ListSchema.index({user_id:1, event_id:1}, {sparse:true, unique:true});
```

Which is then used in an array in the User schema as such:

```
var User = new Schema({
    array : {
        type: [ArraySchema]
    },
    //More specifications for user schema...
});
```

However, when trying to save multiple users without the `array` field, errors are thrown for duplicate fields.  The error in Mocha looks similar to this: `array.event_id_1 dup key {null, null} `.

**Comment by vkarpov15** [comment]
No response for a while and original question unclear. Re-open if still an issue.
