### ISSUE TITLE
TTL indexes are not created

### ISSUE THREAD

**Issue by ItalyPaleAle** [Automattic/mongoose#2459]
With Mongoose 3.8.19 and MongoDB 2.6.5, Mongoose is not creating TTL indexes ("expireAfterSeconds"), in no way.

See this SO question: http://stackoverflow.com/questions/26892660/mongoose-doesnt-create-ttl-indexes

**Comment by dman777** [comment]
Would it be the same thing here with my `index: true`? I can't get `expires` to work:

```javascript
var CpuSchema = new Schema({
	  createdAt: { type: Date, expires: '24h' },
    timestamp : { type : Date, index: true },
```

**Comment by vkarpov15** [comment]
Do `schema.index({ createdAt: 1 }, { expireAfterSeconds: 3600 });`. http://docs.mongodb.org/manual/core/index-ttl/

**Comment by dman777** [comment]
Isn't mongoose supposed to take care of this? I would like to know if my `timestamp : { type : Date, index: true }` is interfering with mongoose creating the ttl index.

**Comment by vkarpov15** [comment]
Try listening to the `Model.on('index', function(error) {});` event to see if there are any issues building indexes.

Also, is mongoose supposed to take care of what exactly?

**Comment by revstage** [comment]
this schema configuration works for me on Mongoose 5.7.0 and MongoDB v4.2.0

```
expireAt: {
  type: Date,
  default: Date.now,
  index: { expires: '1d' },
}
```
