### ISSUE TITLE
Model.create promise returns one object instead of array of objects

### ISSUE THREAD

**Issue by mloncaric** [Automattic/mongoose#2478]
Shouldn't the following condition check the docs and not doc? (or even args..)

``` javascript
  retPromise.then(function (docs) {
    // check if 'doc' created is an array
    if (doc instanceof Array) {
      promise.fulfill.call(promise, docs);
    } else {
      promise.fulfill.apply(promise, docs);
    }
  }, promise.reject.bind(promise));
```

Promises should always resolve with (at most) one argument. I'd always return an array, otherwise it could cause additional issues (one result vs many).

https://github.com/LearnBoost/mongoose/blob/master/lib/model.js#L1573

**Comment by jtmarmon** [comment]
To clarify for other people who stumble upon this issue, passing an array to `Model.create` will continue to spread arguments in 3.8 as it's a breaking chance (see #2582)

Easy workaround for those that want their promises to look a bit more consistent is `var created = Array.prototype.slice.call(arguments)`
