### ISSUE TITLE
Regression in 3.8.20: methods on BaseClass of discriminator leads to TypeError when calling Object.defineProperty

### ISSUE THREAD

**Issue by RBLU** [Automattic/mongoose#2502]
When switching from 3.8.19 to 3.8.20 we experience a TypeError:

```
/Volumes/SourceDev2/yp/backendlib/node_modules/mongoose/lib/model.js:2581
        Object.defineProperty(model.prototype, _i, {
               ^
TypeError: Cannot redefine property: toJsonConfig
```

This is caused by this commit 0bcd28d39b20cc97152da693c6030994c816ffc8 of @alabid. I am not sure whether this commit introduces a bug or we are just using the Discriminator functionality incorrectly.

In difference to the example in #2167  we are using the "methods" functionality on the Base Class, and are not actually adding a method, just a plain data object. 

```
BaseSchema.methods.toJsonConfig = {
        include: ['attr1', 'attr2', 'attr3']
    };
```

This used to work nicely, but now the new method `model.applyMethods` is first called on the BaseModel and then on the SubModel, so the "methods.toJsonConfig" is defined twice, and according to the JS-Spec Object.defineProperty can only called once when configurable is not set explicitly to true for that property.

**Comment by RBLU** [comment]
I am seeing the same error again now, when I am trying to startup my app with mongoose 4.0.2. Is it possible that this fix ist not in the 4.x branches?

**Comment by vkarpov15** [comment]
It's possible that this fix got lost. Can you provide me some code that reproduces this so I can put it in tests?
