### ISSUE TITLE
model hydration 3.8.18

### ISSUE THREAD

**Issue by jmgunn87** [Automattic/mongoose#2505]
using version 3.8.18, I try the following,

````javascript
var  post = new Post({
    title: 'x',
    author: {
        _id: 'x',
        name: 'x'
    }
});

post.author === undefined;
````

Post.author is defined as a referenced schema. When i populate those fields from a query it works as desired but I would like to construct from a JSON object.

**Comment by vkarpov15** [comment]
4.x resolves this issue.
