### ISSUE TITLE
Inverse function -- populate() -- depopulate() ?

### ISSUE THREAD

**Issue by earthquakesan** [Automattic/mongoose#2509]
Hi everyone,

although it's quite easy to implement it as a 'pre' save hook, I'm really wondering why this functionality is not there inside mongoose, because the problem is quite generic. The problem is the following (I will use mine project as an example):
Given the object with one or several relationships to other collection, for example,
```
var ProjectSchema = new Schema({
  created: {type: Date, default: Date.now},
  creator: { type: mongoose.Schema.Types.ObjectId, ref: 'User'},
  title: { type: String, unique: true },
  description: String,
  state: String,
  candidates: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User'}],
  participants: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User'}]
});
```
How to push object back to the DB after running populate() on it? That is, what is the inverse function for populate()?

I do it myself right now like this:
```
newProject.candidates = newProject.candidates.map(function(candidate){ return candidate._id; });
newProject.participants = newProject.participants.map(function(participant){ return participant._id; });
newProject.creator = newProject.creator._id;
```

Is there a built-in functionality, which can identify arrays in the Schema, which contain relationships (i.e. ref) and do it for me automatically, if I define some kind of option?

**Comment by newmanw** [comment]
@vkarpov15 I have the exact same need for depopulate, but for a different reason.

I allow my users via my api to populate children arrays.  However sometimes to do a calc I need to populate a particular child array.  If the api didn't ask for that child array to be populated I need to depopulate it.

I tried:

```javascript
doc.toObject({depopulate: true})
```

However that depopulates all populated children.  Again they may have asked to populate children1, but I populated children2 to do a calc.  In that case I would want something like:

```javascript
  Model.depopulate(docs, 'children2', callback);
```

Any plans to implement this?

Any way I can reach into the depths of mongoose and call a function somewhere that would achieve the same result?

Would also need populated call to work:
```javascript
var children2Populated = doc.populated('children2');
```

**Comment by vkarpov15** [comment]
Hmm I'll mark this as a discussion and put it up on the 4.2 roadmap. If you need to populate without leaking to your users you can just bypass populate and do a query for the docs you need directly :)

**Comment by adamreisnz** [comment]
Was the `{depopulate: true}` option ever added? That seems like a great addition to have.

**Comment by vkarpov15** [comment]
Yep see https://mongoosejs.com/docs/api.html#document_Document-toObject
