### ISSUE TITLE
Date SchemaType min and max validators

### ISSUE THREAD

**Issue by bshamblen** [Automattic/mongoose#2531]
There are built in `min` and `max` validators for the Number SchemaType. Are there any plans to add these options to the Date SchemaType? I checked the most recent version of the source code and it doesn't look like it currently exists. I checked existing bugs and didn't see an open issue for it. I'd be happy to add the feature to the project, if it's not already being worked on for 4.0.

**Comment by jtcmedia** [comment]
Is there a way to set the max date validator to one year from today?
