### ISSUE TITLE
Is it possible to populate without `_id` ?

### ISSUE THREAD

**Issue by mocheng** [Automattic/mongoose#2562]
I checked the API http://mongoosejs.com/docs/populate.html and tried out. It seems that `populate` can only works on foreign `_id`. Even there is a `match` option, it just add more filtering condition on `_id` query condition. There is no way to just populate with fields not involved with `_id`.

In my project, we keep the `_id` as ObjectId and has another field as auto-increment Number. For example, `customers` model has `_id` as Object and `cuid` as incremental number. Other collections just reference to `cuid` not to `_id`. 

Is would be great to be able to customize this?
Is there any design limitation causing this feature missing?

**Comment by vkarpov15** [comment]
It would be great to be able to customize this, but right now we enforce `_id`. I can't think of a good reason off the top of my head why not though. I'll have to investigate further.

**Comment by taxilian** [comment]
The ability to populate not just on a single other field but even on a set of fields is almost required to properly support sharding, which is a huge use case for us.

For example, we have a collection "students" which may have a shard key for "subscription"; when we populate student data from our sections model (which contains an array of students) we have the subscription on the document but it will only look up based on the _id stored in "student" rather than allowing us to specify that it should also map the documents "assignment" field to "assignment" on the student.

Since we'd then be doing a lookup without the shard key when doing populate it renders sharding useless, requiring all shards to be hit to retrieve the data instead of just one.

This is something we would be willing to fund development for or even do ourselves if we could get some guidance of where to do the work.  It is a major need for our company (GradeCam).

**Comment by vkarpov15** [comment]
@taxilian are you setting the `shardKey` schema option? AFAIK that's what that option is for.

**Comment by taxilian** [comment]
I haven't actually moved to start doing it yet because I've been looking for a solution to this issue; does populate take into account shardKey? My understanding was that shardKey only affected updates and inserts

**Comment by LeonLiber** [comment]
It would be great to be able to specify the field which is to be "joined by", for example I'd like to be able to populate not only by userId (i.e. _id) field but also by userType, userGroup etc.
Thanks!

**Comment by podoler** [comment]
+1

**Comment by nadavsinai** [comment]
+1 would be very useful

**Comment by chloetina** [comment]
+1 same here!

**Comment by prakash122** [comment]
+1 love to have this

**Comment by ricolo** [comment]
+1

**Comment by vlapo** [comment]
+1

**Comment by prescottprue** [comment]
+1 

It would be especially nice to be able to select the variable you would like to populate with by adding a parameter such as `key`:

For example if had posts that I wanted to populate the `author` and `comments` parameters of, but the parameters are holding non ObjectId parameters  (username of user and title of comments) before population:
```
{
author: "user1",
comments:["comment5", "comment6"],
title:"Post1"
}
```
It would be nice to be able to add a parameter like "key" to let mongo know which parameter to lookup by:
```
Posts.find().populate([{path:"author", model:"Users", key:"username"}, {path:"comments", model:"Comments", key:"title"}])
```
This would fill the `author` parameter with a User found by username as well as fill the `comments` parameter with comments found by their title (I realize the comments by title is a little unrealistic, but you get the point).

**Comment by apankov** [comment]
+1

**Comment by marklar21** [comment]
+1

**Comment by hallmarkdigital** [comment]
+1

**Comment by J4G-** [comment]
+1

**Comment by asafam** [comment]
+1

**Comment by whyhankee** [comment]
+1

**Comment by ArcoMul** [comment]
+1

**Comment by cannonpalms** [comment]
Big agree. I'd love the ability to define custom population schemes. It'd be great for any schema with one or more fields that are file paths, allowing populate to read from storage.

**Comment by nordisk** [comment]
+1

**Comment by naoxink** [comment]
+1

**Comment by enthusiast94** [comment]
+1

**Comment by Poplava** [comment]
+1

**Comment by lfk** [comment]
+1

**Comment by RithwikAnand** [comment]
+1

**Comment by justvisiting** [comment]
+1

**Comment by kumasento** [comment]
+1

**Comment by Neophy7e** [comment]
+1

**Comment by loris** [comment]
+1

**Comment by tomerb15** [comment]
+1

**Comment by keithl8041** [comment]
+1

**Comment by danielflippance** [comment]
+1

**Comment by prabhupadas** [comment]
+1

**Comment by leonardokl** [comment]
+1

**Comment by robjens** [comment]
+1

**Comment by beinnova** [comment]
+1

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by roygwsidev** [comment]
+1

**Comment by docksteaderluke** [comment]
+1

**Comment by wohugb** [comment]
+1

**Comment by joshbeam** [comment]
+1

**Comment by pavan612** [comment]
+1

**Comment by kennethkoontz** [comment]
+1

**Comment by R0R0N0A** [comment]
+1

**Comment by liraniom** [comment]
+1

**Comment by Pyo25** [comment]
+1

**Comment by danilvalov** [comment]
+1

**Comment by rturk** [comment]
+1

**Comment by rturk** [comment]
Try this code: https://github.com/alexmingoia/mongoose-populate-virtuals.

Actually, any reason for not merging Alex's code into main repo and make this a core feature?

**Comment by vkarpov15** [comment]
@rturk I really really like that plugin, thanks for pointing it out. @alexmingoia what are your thoughts re: merging your module into mongoose core? The idea of using virtuals to handle more generic populate (without having an actual field persisted to the db) is really powerful.

**Comment by alexmingoia** [comment]
That would be ideal. It'd be much better in core because it overloads `Query.prototype.populate` and other core functionality.

The only thing blocking me from creating a pull request is that there's little to no test coverage, and documentation is lacking. I am using it in production in multiple scenarios and it's stable, but I think if someone were to write a test suite it might expose some minor issues or idiosyncrasies that need to be documented.

Is someone willing to tackle the test suite? If not - I can do it but don't expect that to land before next month.

**Comment by vkarpov15** [comment]
I'll take a look. I've been meaning to rewrite populate anyway :)

**Comment by alexmingoia** [comment]
Ping me on IRC `amingoia` or gitter if you have any questions about the code.

**Comment by sibeliusseraphini** [comment]
https://github.com/whitecolor/mongoose-fill also does a great job to populate using data from other models

**Comment by BenSower** [comment]
+1

**Comment by juanpujol** [comment]
+1

**Comment by obengwilliam** [comment]
+1

**Comment by gitawego** [comment]
this is a must :)

**Comment by amit3vr** [comment]
+1

**Comment by teja-paketts** [comment]
+1

**Comment by stewones** [comment]
+1

**Comment by nguyentrongbang** [comment]
+1

**Comment by GuilhermeGoncalves** [comment]
+1

**Comment by markotom** [comment]
+1

**Comment by forksofpower** [comment]
+1

**Comment by ashe540** [comment]
+1

**Comment by BenBestmann** [comment]
+1

**Comment by andela-batolagbe** [comment]
+1

**Comment by rychkog** [comment]
+1

**Comment by atamas101** [comment]
+1

**Comment by mogita** [comment]
+1

**Comment by mogita** [comment]
+1

**Comment by samidarko** [comment]
+1

**Comment by longfeix** [comment]
+1

**Comment by oguzhanaslan** [comment]
+1

**Comment by thatisuday** [comment]
https://github.com/Automattic/mongoose/issues/4348

**Comment by atakangktepe** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by teemuniiranen** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by feit** [comment]
+1

**Comment by fbegue** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by omarps** [comment]
+1
