### ISSUE TITLE
Exceptions in setter methods are not reported

### ISSUE THREAD

**Issue by jtmarmon** [Automattic/mongoose#2570]
I have a setter that takes a phone number and converts it to a standard format.  This external library ([mattbornski/libphonenumber](https://github.com/mattbornski/libphonenumber)) throws an error if the value cannot be converted.  However, my tests for this were just timing out and I wasn't sure why.

After a lot of investigation, it seems that if a setter throws an error, the error handler is not triggered when there is an error, but neither is the success handler, so the function just hangs.

**Comment by vkarpov15** [comment]
Are you sure the setter doesn't throw an exception? If the setter swallows the exception that's a bug, but it may be the case that it's the classic "mocha sometimes times out when an exception is thrown" issue - can you wrap your `set()` call in a try/catch and see if it throws an exception?

**Comment by jtmarmon** [comment]
![image](https://cloud.githubusercontent.com/assets/4528076/5598794/3a8e896e-928a-11e4-8ea0-dcdcc63e5b4d.png)
![image](https://cloud.githubusercontent.com/assets/4528076/5598796/42c66516-928a-11e4-9aa5-6454a9473b63.png)

**Comment by jtmarmon** [comment]
Ah it appears the exception is thrown during `save`.  Shouldn't the set be called when it's actually set, though?

**Comment by vkarpov15** [comment]
Actually this is a design decision - cast errors don't do anything until you try to call `validate()`. This is because you can't do async setters in JS and so there's no good way to report that a setter failed without throwing an exception. It's something that's gotten some discussion on Github issues, but I haven't quite thought of a solution that I like - throwing seems limiting.

**Comment by jtmarmon** [comment]
Hmm...holding errors until validation definitely seems misleading. I'm not sure why it's a bad thing to throw an exception when a setter fails.

**Comment by vkarpov15** [comment]
Because adding a try/catch around every time you try to set user data on a document in addition to `validate()` seems a bit cumbersome IMO. It can be misleading, I agree, but the obvious alternative would make mongoose more clunky.

**Comment by jtmarmon** [comment]
I suppose. I believe there's still an actual bug hanging around on the `create` method not properly handling setter errors. I can try to provide some test code some time this week
