### ISSUE TITLE
Debugging indexes & detailed $explain

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#2572]
I'd like to see if my queries are using the indexes I expect them to use. The current `mongoose.set('debug',true)` only shows the query I put in. Ideally, there'd be a switch we can turn on to get all the `$explain` info:

http://docs.mongodb.org/manual/reference/operator/meta/explain/

**Comment by vkarpov15** [comment]
I really like this idea, thanks. Probably something to add in 4.1.

**Comment by buunguyen** [comment]
+1

**Comment by fridays** [comment]
Is this possible by now?

**Comment by fridays** [comment]
Here is my workaround for now by plugging in  [monk](https://github.com/vccabral/monk) to get the `explain`:
```javascript
	var monk = require('monk')(config.mongo.url);

	mongoose.set('debug', function (collection, method, query, doc) {
		if (method === 'ensureIndex') return;
		
		console.log('');
		console.log('=== Mongoose query ===');
		console.log('');
		console.log(collection,  method, query, doc);

		var explainDoc = Object.create(doc);
		explainDoc.explain = true;

		monk.get(collection)[method](query, explainDoc, function (err, doc) {
			if (err) return console.err(err);

			// Log the explain...
			console.dir(doc, { depth: null, colors: true });
		});
	});
```

**Comment by vkarpov15** [comment]
See https://www.npmjs.com/package/mongoose-explain . It executes the query twice, but ensures that you get the results as well as the explain output, which is AFAIK currently impossible with `.find()`
