### ISSUE TITLE
Provide model name as option/argument to global plugins

### ISSUE THREAD

**Issue by forrert** [Automattic/mongoose#2578]
I am developing a plugin that needs to know the name of the model that is defined from the schema (I have some further config files ready for each model that I'd like to process when the plugin is loaded). Of course, when registering the plugin on each schema this is not a problem. However I would like to register the plugin globally.

Would it be possible to provide that information to the plugin function? Looking at the code, I think it would make most sense to add a 3rd parameter to the plugin function, where the name of the model is provided (to ensure compatibility with all existing plugins).

Thanks for your help!

**Comment by vkarpov15** [comment]
That's not really possible, because a schema purposely doesn't know about what models use it. When a model is created, it makes a copy of the schema, so the name of the model isn't known until it's too late. What specifically are you trying to achieve with your plugin? Perhaps there's another way.

**Comment by forrert** [comment]
Thanks for your response. Turns out there was another way to get it done. I didn't need to know the model name in the plugin itself (just executed that part after all models have been initialised in the application).
