### ISSUE TITLE
mongoosejs.com seem to be offline

### ISSUE THREAD

**Issue by NickNaso** [Automattic/mongoose#2594]
Please check the status of mongoosejs.com it seem to be offilne. I need the documentation. Thanks in advance.

**Comment by Reggino** [comment]
Yep, same here

**Comment by SamHwang1990** [comment]
the same +1~~~

**Comment by TalhaAkkas** [comment]
+1

**Comment by SamHwang1990** [comment]
@NickNaso @Reggino @TalhaAkkas 
i found the docs in github page, aha~~~i'm not sure whether the link can help you~~~
[mongoose api](http://learnboost.github.io/mongoose/docs/guide.html)

**Comment by NickNaso** [comment]
thank you vaery much! @SamHwang1990

**Comment by joe-mojo** [comment]
Please restore mongoosejs.com or update links to the github page.

PS: thanks @SamHwang1990 for the workaround.

**Comment by akaashanky** [comment]
Thanks, @SamHwang1990! :)

**Comment by vkarpov15** [comment]
Thanks for pointing this out, looks like DNS issue, I'm on it. Not that easy to fix since I don't have access to the DNS config though :(
