### ISSUE TITLE
Connection was destroyed by application

### ISSUE THREAD

**Issue by vuesomedev** [Automattic/mongoose#2595]
Im trying to write end2end tests for my express app with supertest.
The app boots after `mongoose.connect` and in the beforeAch part of the test I insert some data with Mongoose models.
When the express route executes it throws an error in GridFS when it tries to insert a file.

**Comment by vkarpov15** [comment]
I'm going to need some more information, like code samples. I don't quite understand what you're trying to do.

**Comment by danielflippance** [comment]
+1

**Comment by danielflippance** [comment]
This test uses nodeunit and superfast to test a NodeJS app and fails with 'Connection was destroyed by application'. As far as I can tell it seems to happen during session save using MongoStore (After the res.render)

```javascript
//Unit test using SuperFast and 
var supertestRequest = require('supertest')
	, express = require('express')
	;

exports.home_Normal_Succeeds = function(test) {
	test.expect(3);

	supertestRequest(app)
		.get('/')
		.expect('Content-Type', "text/html; charset=utf-8")
		.expect(200)
		.end(function(err, res){
			console.log(err ? "**** ERROR - " + err : "**** SUCCESS")
			test.equal(null, err);
			test.notEqual(null, res);
			test.equal(200, res.status);
			test.done();	
	});
}
```

Stack trace:
```
 Stack: Error: Connection was destroyed by application
    at Db._executeInsertCommand (/blah/node_modules/mongodb/lib/mongodb/db.js:1773:55)
    at Collection.update (/blah/node_modules/mongodb/lib/mongodb/collection.js:487:13)
    at /blah/node_modules/connect-mongo/lib/connect-mongo.js:340:18
    at MongoStore.getCollection (/blah/node_modules/connect-mongo/lib/connect-mongo.js:210:11)
    at MongoStore.set (/blah/node_modules/connect-mongo/lib/connect-mongo.js:338:10)
    at Session.save (/blah/node_modules/express-session/session/session.js:71:25)
```

**Comment by blacksonic** [comment]
Do you use mockgoose?

**Comment by vkarpov15** [comment]
Where exactly is this a mongoose issue? Are you passing a mongoose connection to connect-mongo?

Disclaimer: connect-mongo has numerous known bugs and limitations (some of which may have been fixed since it got a new maintainer, I haven't followed connect-mongo dev in 2015) but [connect-mongodb-session](https://github.com/vkarpov15/connect-mongodb-session) is meant to be a more reliable replacement. I would recommend switching over.

**Comment by danielflippance** [comment]
Nope, I'm not using mockgoose - looks interesting, will check it out. Thanks.
Yep I'm passing the mongoose connection to MongoStore:

    var session = require('express-session');
    var MongoStore = require('connect-mongo')(session);
    ...
    app.use(session({...,store: new MongoStore({ mongooseConnection: mongooseConnection }) }) );

I'll try connect-mongodb-session to see if that helps - thanks.
I have no idea if this is a mongoose issue, (seems unlikely) but I saw this post and had the same symptoms so provided the code sample requested.
Thanks.

**Comment by vkarpov15** [comment]
connect-mongo does some strange things with mongoose connections, I don't quite grok the particulars. I think this sounds like a connect-mongo issue.
