### ISSUE TITLE
ensureIndex event should be called even if has no indexes

### ISSUE THREAD

**Issue by totty90** [Automattic/mongoose#2605]
For example I would like to listen on each model to have it's indexes ensured before using the database. Some models have no indexes, except the default _id one.

Another thing would be nice to know whenever a model has it's indexes ensured, like a flag.

**Comment by vkarpov15** [comment]
I agree that the `index` event should be emitted even when a model has no indexes. As a workaround, you can use the `Model.schema.indexes()` function to get an array of all indexes on the model and check if length is > 0.

**Comment by totty90** [comment]
That's exactly what I do. (:

**Comment by vkarpov15** [comment]
In 4.13 you can get a promise back from `Model.init()` or listen to `Model.on('index')`
