### ISSUE TITLE
Custom require error message?

### ISSUE THREAD

**Issue by nijikokun** [Automattic/mongoose#2616]
Currently it's something along the lines of:

```
Path `field` is required.
```

Which is not very user-friendly, how do you customize this *before* output preferably without string manipulation or having to mutate the error object itself.

Is there a way for mongoose to take custom template string for this?

Something like this would be useful

```
required: [ true, "Blah blah" ]
```

**Comment by Nijikokun** [comment]
Actually, this does work:

```
required: [ true, "Blah blah" ]
```

**Comment by Nijikokun** [comment]
This should be better documented. Would have saved me time.

**Comment by magicae** [comment]
This should be documented. It have wasted lots of time.
