### ISSUE TITLE
mongoose runs validators more than once on save of a nested document

### ISSUE THREAD

**Issue by ashaffer** [Automattic/mongoose#2617]
``` javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('localhost');

var SubSchema = new Schema({str: String});
SubSchema.path('str').validate(function(val, next) {
  console.log('path.validate');
  next();
});

SubSchema.pre('validate', function(next) {
  console.log('pre validate');
  next();
});

var DocSchema = new Schema({arr: [SubSchema]});
var Doc = mongoose.model('b', DocSchema);

var p = new Doc();
p.arr.push({str: 'asdf'});
p.save();
```

Run this code.  You would expect each console.log to happen once, but they both happen twice in the latest version of mongoose and at least as far back as 3.8.8, the version i'm using.

**Comment by ashaffer** [comment]
Nvm, this issue seems to be fixed in the unstable version in the repository.  I was only testing against the most recently released version.

**Comment by ashaffer** [comment]
Reopening because I realized that this is not fixed in the latest version of 3.8, and that branch is still being updated with bugfixes.

**Comment by vkarpov15** [comment]
Works fine in 4.9.4

**Comment by troywweber7** [comment]
I'm still seeing this happen in `mongoose@5.3.13`.
