### ISSUE TITLE
not using _id  in subdocument ref

### ISSUE THREAD

**Issue by pabx06** [Automattic/mongoose#2632]
i am having hard time using something not _id  (a string as foreign key)
```
var TrackSchema = new Schema({
    _id:{type:Schema.Types.ObjectId,default: function (){return new mongoose.Types.ObjectId();}},
    album:{type:Schema.Types.ObjectId,ref:'Album'},
});

var AlbumSchema = new Schema({
    _id:{type:Schema.Types.ObjectId,default: function (){return new mongoose.Types.ObjectId();}},
    name: String,
    from_old_mysql_id:{type:String ,index:'unique'},
    album_type:String});
```

i would like to use in AlbumSchema.from_old_mysql_id in the TrackSchema to reference an Album
is this possible ?

**Comment by vkarpov15** [comment]
Right now `populate()` only supports populating by `_id`. This will likely be improved in the future, but you won't be able to populate based on `from_old_mysql_id` now.

**Comment by pabx06** [comment]
Thanks for quick response. 
What about saving?
Or may i replace _id: by a String from old mysql primary key String ?

**Comment by vkarpov15** [comment]
Not sure what you're problem with saving is. There should be nothing to stop you from saving an album with the `from_old_mysql_id` path.
