### ISSUE TITLE
VersionError's Error Object Loses Context

### ISSUE THREAD

**Issue by droppedoncaprica** [Automattic/mongoose#2633]
When you run into a VersionError problem, the resulting error object doesn't show where this error is coming from.  Other errors will normally log what line in your code is causing this error, allowing you to easily debug where it is coming from.  When you run into a VersionError however, it isn't possible to easily locate where the error is originating from.

Take this example (this is in CoffeeScript, but I can write on in JS if you want me to):

    mongoose = require 'mongoose'
    Schema            = mongoose.Schema

    mongoose.connect 'mongodb://localhost/db-test', (e) -> if e then throw e

    ItemSchema = new Schema({
      arr1: [{
        thing1: { type : String },
        thing2: { type : String },
        thing3: { type : String }
      }]
    })

    Item = mongoose.model('Item', ItemSchema)

    # First insert a document

    new Item({
      arr1: [{
        thing1: 'Value',
        thing2: 'Value2',
        thing3: 'Value3'
      }]
    }).save (e, savedItem) ->
      if e then throw e

      console.log('Saved initial item!')
      console.log()

      savedItem.arr1.push {
        thing1: 'value4',
        thing2: 'value5',
        thing3: 'value6'
      }

      savedItem.save (e) ->
        if e then throw e

        console.log('Saved second item!')
        console.log()

      savedItem.arr1.push {
        thing1: 'value7',
        thing2: 'value8',
        thing3: 'value9'
      }

      savedItem.save (e) ->
        if e then throw e

        console.log('Saved third item!')
        console.log()

If you look at the stack trace of the resulting `Error` object, it doesn't have the current context that it was ran in (ie doesn't log where it was called from in the stack trace).  This makes it difficult to locate where these sort of errors are originating from.

**Comment by paglias** [comment]
Agreed, this makes it almost impossible to find out where the error is happening

**Comment by droppedoncaprica** [comment]
Wooo!  Thanks for the update!  :tada:
