### ISSUE TITLE
pre-save in nested documents not executed correctly (???)

### ISSUE THREAD

**Issue by Azuri** [Automattic/mongoose#2645]
I have the following code:
``` js
var ChildSchema = mongoose.Schema({
    name: String
});
ChildSchema.pre('save', function (next) {
    console.log('child pre-save -', this.name);
    next();
});
var Child = mongoose.model('Child', ChildSchema);

var ParentSchema = mongoose.Schema({
    children: [Child.schema]
});
ParentSchema.pre('save', function (next) {
    console.log('parent pre-save');
    this.children = [];
    this.children.push({ name: 'jane' });
    this.children.push({ name: 'john' });
        
    next();
});
var Parent = mongoose.model('Parent', ParentSchema);

var p = new Parent({ children: [{ name: 'mike' }, { name: 'bob' }, { name: 'susan' }] });

p.save(function (err) { console.log(p); });
```

Result
```
parent pre-save
child pre-save - mike
child pre-save - bob
child pre-save - susan
{ __v: 0,
  _id: 54d16604e4f4beb422e39442,
  children:
   [ { name: 'jane', _id: 54d16604e4f4beb422e39446 },
     { name: 'john', _id: 54d16604e4f4beb422e39447 } ] }
```

Is this normal behavior? How can I get around this? I do think that I should get pre-save hooks for `john` and `jane`

**Comment by vkarpov15** [comment]
Yeah this is a limitation in mongoose 3.8.x: the way it handles pre hooks on child docs is a little strange. This issue is fixed in 4.0.0-rc1, I get the following output using that version:

```
parent pre-save
child pre-save - jane
child pre-save - john
{ __v: 0,
  _id: 54d266132187101a14e0b71e,
  children: 
   [ { name: 'jane', _id: 54d266132187101a14e0b722 },
     { name: 'john', _id: 54d266132187101a14e0b723 } ] }
```

I'll investigate fixing this in 3.8.x, but if you want a quick fix try upgrading to 4.0.0-rc1 :)

**Comment by niftylettuce** [comment]
I don't think this is fixed, nested save hooks aren't working when you call `save()` on parent object

**Comment by vkarpov15** [comment]
Actually this is expected behavior, see discussion in https://github.com/Automattic/mongoose/issues/3219 , we assume that child pre save hooks run _before_ parent pre save hooks. However, running child pre save hooks is actually structured as a pre save hook that gets attached to every schema by default, so you can hack it so that your pre save hook runs before the 'child pre save hooks' pre save hook:

```javascript
var ParentSchema = mongoose.Schema({
    children: [Child.schema]
});
ParentSchema.callQueue.unshift(['pre', ['save', function (next) {
    console.log('parent pre-save');
    this.children = [];
    this.children.push({ name: 'jane' });
    this.children.push({ name: 'john' });

    next();
}]]);
```
