### ISSUE TITLE
Calling .findOneAndRemove without callback die silently

### ISSUE THREAD

**Issue by NemoStein** [Automattic/mongoose#2647]
A fire-and-forget call to .findOneAndRemove (and .findByIdAndRemove by extension) won't delete the document and won't warn the user.
A callback function is obligatory, but there is no documentation about it, nor any info is issued at stdout/stderr.

    Model.findByIdAndRemove(id); // Does nothing and return silently
    Model.findByIdAndRemove(id, function(){}); // With a dummy function it works as expected

**Comment by vkarpov15** [comment]
Thanks for pointing this out.

**Comment by bgSosh** [comment]
@NemoStein - This is by design - If you don't provide a callback, then findOneAndRemove will return a query, which you need to execute explicitly.

See [findOneAndRemove documentation](http://mongoosejs.com/docs/api.html#query_Query-findOneAndRemove)

**Comment by vkarpov15** [comment]
Yeah email is correct, if you don't specify a callback it returns a query object which you can then chain methods onto. It won't get executed until you provide a callback or call `.exec()`. See [docs about Query.exec()](http://mongoosejs.com/docs/api.html#query_Query-exec)

**Comment by gkatsanos** [comment]
> Yeah email is correct, if you don't specify a callback it returns a query object which you can then chain methods onto. It won't get executed until you provide a callback or call `.exec()`. See [docs about Query.exec()](http://mongoosejs.com/docs/api.html#query_Query-exec)

What arguments does the callback get? Can you provide an example? How can you check if something was found and change the application flow accordingly?  https://github.com/danielfsousa/express-rest-es2017-boilerplate/issues/125

**Comment by vkarpov15** [comment]
The arguments to the exec callback depend on the operation you're executing. For findOneAndReplace, the callback args are the same as described here: https://mongoosejs.com/docs/api.html#query_Query-findOneAndReplace

In #7343 you mentioned you're using async/await, so it sounds like you're looking for `orFail()`: https://mongoosejs.com/docs/api.html#query_Query-orFail
http://thecodebarbarian.com/whats-new-in-mongoose-53-orfail-and-global-toobject.html
