### ISSUE TITLE
Required array field throws error when set as empty array

### ISSUE THREAD

**Issue by Soviut** [Automattic/mongoose#2662]
I have an array field with the following schema on that field:

``` coffeescript
parents:
    type: 'Array'
    required: true
```

When I try to create a document with the following data:

``` coffeescript
data =
    parents: []

Translation.create data, (err, translations) ->
    console.log err, translations
```

I get the following error:

```
ValidationError: Path `parents` is required.
```

If I put a value inside the array it works, like so:

``` coffeescript
data =
    parents: ['blah']
```

Similarly, if I remove the `required: true` from the schema, it also starts working.

Is an empty array not considered satisfactory for "required" validation? I understand it's false in javascript, but there are plenty of cases where empty arrays and objects are intended in Mongo documents.

**Comment by paton** [comment]
Agreed, we got tripped up on this too.

Assumed behavior of `required: true` would be the presence of an array, rather than an array that requires at least one element.

**Comment by almassapargali** [comment]
Agree that required array fields should accept empty arrays. I've always thought of it this way, till I had an issue with Mongoose yesterday.

**Comment by vkarpov15** [comment]
Gonna close this in favor of #5139. Will change this behavior in 5.0.
