### ISSUE TITLE
feature request: schema definitions in a single object expression

### ISSUE THREAD

**Issue by noisypebble** [Automattic/mongoose#2676]
It would be beneficial to me and perhaps others to be able to define a schema in a single object expression:

``` javascript
var AnimalSchema = new Schema({
  paths: {
    name: { type: 'String' },
    type: { type: 'String' }
  },
  virtuals: {
    title: {
      get: function() {
        return this.name + ': ' + this.type;
      }
    }
  }, 
  methods: {
    findSimilarTypes: function(cb) {
      return this.model('Animal').find({ type: this.type }, cb);
    }
  },
  statics: {
    findByName: function(name, cb) {
      this.find({ name: new RegExp(name, 'i') }, cb);
    }
  },
  indexes: [
    { name: 1, type: -1 }
  ]
});
```

I've created a project that wraps the schema [here](https://github.com/toyatech/mongoose-wrappers) that illustrates how this might work, but I haven't thoroughly tested it.

**Comment by vkarpov15** [comment]
Don't think we're going to implement this any time soon. Supporting both the current syntax and this suggestion will be very tricky. I'm open to suggestions as to how to implement and/or +1's, but right now I don't think this is a high priority.

**Comment by crispen-smith** [comment]
Wouldn't it be possible to add an intermediary object that deconstructs this "megaschema" into it's parts and then builds a new schema on the parts?

I don't know how much value a "megaschema" would offer me personally but that sort of a transformer object if it were given pluggable rules would be very useful for my use-case where I describe an elements collection for user facing forms and a separate model for server facing data definition.

**Comment by vkarpov15** [comment]
I'm not really sure how much value this offers either. There is benefit to being able to specify one giant object versus using chaining, but the implementation details are tricky. I think for now it would be a good idea to keep it as a separate module.

**Comment by crispen-smith** [comment]
Off topic, but I know for my use cases I'm just treating it with a live-with for the moment, but I am hoping to publish a module in the near future that can take transform from schema to an "elements" object or vice-versa.

The difficulty is that I sometimes want to manually force error messages into the element, or apply custom class names as CSS hooks and it feels like a lot of that cruft should be left out of mongoose.  But then I break DRY


For the main topic;  I agree that a transformer should probably be it's own module as well.

**Comment by vkarpov15** [comment]
This was added in 6.4.0 with #11563
