### ISSUE TITLE
single embedded document support

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2689]
See #585

**Comment by netusco** [comment]
+1

**Comment by Reggino** [comment]
+1

**Comment by fcristel** [comment]
+1

**Comment by adambuczynski** [comment]
This was definitely something that tripped me up when I started with Mongoose. Will be good if support for it is added. :+1:

**Comment by ashaffer** [comment]
+1

**Comment by FREEZX** [comment]
+1

**Comment by sdolidze** [comment]
+1

**Comment by Jeff-Lewis** [comment]
@vkarpov15 We are excited this is on the 4.2 milestone! (I've been watching this and #585 for almost 2 years.)  
Can you please share you recent thoughts regarding the features and challenges with this change? There are a lot of +1's and I want to make sure everyone's expectations are in the same place.

**Comment by vkarpov15** [comment]
Getting this to work will require a substantial refactoring of schemas, which is why it hasn't been done yet :) fundamental data structure changes are pretty hard. I'm aware that this is a popular issue but it's unfortunately gonna take a lot of work.

**Comment by seokgyo** [comment]
+1

**Comment by adambuczynski** [comment]
:tada:
