### ISSUE TITLE
How do I profile through put on connections at any given point in time?

### ISSUE THREAD

**Issue by jorgeolivero** [Automattic/mongoose#2694]
I writing some profiling tools for a service which uses the Mongoose ODM. The connection pool ranges between 5 - 20 members.

I would like to, at an interval, monitor the through put on each connection to get information on the number of queries/commands (if any?) that are getting queued up.

I'm looking through the entire mongoose object, but nothing is standing out to me. 

Is there an established way to do this?

**Comment by vkarpov15** [comment]
4.0.0-rc2 has hooks for `find()` and `update()` so you can easily write plugins that track how many requests are outstanding and how long they take. Is this something that would be helpful for your use case?
