### ISSUE TITLE
select: true on nested subdoc field causes other fields to not be selected when querying parent

### ISSUE THREAD

**Issue by sxyuan** [Automattic/mongoose#2702]
``` javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/test');

var SubsubdocASchema = new Schema({
    _id: String,
    val: String
});
var SubsubdocA = mongoose.model('SubsubdocA', SubsubdocASchema);
var SubsubdocBSchema = new Schema({
    _id: String,
    val: { type: String, select: true }
});
var SubsubdocB = mongoose.model('SubsubdocB', SubsubdocBSchema);

var SubdocSchema = new Schema({
    a: [SubsubdocA.schema],
    b: [SubsubdocB.schema]
});
var Subdoc = mongoose.model('Subdoc', SubdocSchema);

var ParentSchema = new Schema({
    vals: [Subdoc.schema]
});
var Parent = mongoose.model('Parent', ParentSchema);

var p = new Parent({
    vals: [{
        a: [{_id: 'A', val: '1'}],
        b: [{_id: 'B', val: '2'}]
    }]
});
p.save(function(err, doc) {
    Parent.find()
    .select('vals')
    .exec(function(err, docs) {
        console.log(docs[0].vals[0]);
        mongoose.connection.collections['parents'].drop(function() {
            mongoose.disconnect();
        });
    });
});
```

Output:

```
Mongoose: parents.insert({ __v: 0, vals: [ { _id: ObjectId("54e6995f332866196b143168"), b: [ { val: '2', _id: 'B' } ], a: [ { val: '1', _id: 'A' } ] } ], _id: ObjectId("54e6995f332866196b143167") }) {}  
false { vals: 1 } [ 'vals.b.val' ]
Mongoose: parents.find({}) { fields: { 'vals.b.val': 1, vals: 1 } }  
{ _id: 54e6995f332866196b143168,
  b: [ { val: '2' } ],
  a: [ { _id: 'A', val: '1' } ] }
Mongoose: parents.drop()   
```

Note that `b._id` is not returned. Based on the description in the docs, I wouldn't have expected this behaviour when using { select: true }. This also doesn't happen when selecting a subdoc with such a field.

**Comment by vkarpov15** [comment]
Thanks for the detailed report. I'll take a look at this asap.

**Comment by vkarpov15** [comment]
Looking into this more carefully, it looks like this is correct behavior. `select: true` does automatically deselect other fields, including `_id` for subdocs. The reason why `_id` for documents needs to be explicitly excluded with `_id: 0` is that the mongodb server enforces that restriction. I don't think mongoose should be enforcing that by default for subdocs. I would like to update the docs to make this more clear though - where did you get this impression from the docs?

**Comment by sxyuan** [comment]
This doesn't have anything to do with special restrictions for _id - it happens for any other field. I don't think it's correct behaviour because it's inconsistent depending on where that { select: true } shows up.

1. If you do T.find() with no select clause and T has a { select: true } field, you'll get all the fields back.

2. If you do T.find().select('a') where T has a subdoc a with schema A that has a { select: true } field, you still get all the fields of A back.

3. If you do T.find().select('a') where T has a subdoc a with schema A and A has a subdoc b with schema B which has a { select: true } field (my original example), suddenly you only get the one field back from B. Again, this has nothing to do with _id, I just used that as an example to reduce the amount of output.

Sorry if this wasn't clear earlier.

The documentation I was referring to is http://mongoosejs.com/docs/api.html#schematype_SchemaType-select. It makes no mention of the side-effect of sometimes causing the other fields to disappear, and I don't think it should - I think case 3 should behave like case 2, and return all the fields of B unless you have a select('a.b.x') clause in your query.

**Comment by sxyuan** [comment]
Hi Valerie, could you please explain why this is not an issue, despite the inconsistency in the semantics of { select: true } right now?

**Comment by vkarpov15** [comment]
That's just how mongodb server handles [projections](http://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/). Mongoose offers a little extra syntactic sugar in that, if you don't specify a projection and use 'select: true', it won't put in a projection at all to prevent hiding other fields. However, once you specify a projection using `.select('vals')`, 'select: true` tells mongoose to add in `vals.b.val` to the projection. Here's how this behavior looks in the mongodb shell:

```
> db.test.insert({ x: { y: { z: 1 }, a: { b: 2 } } });
WriteResult({ "nInserted" : 1 })
> db.test.findOne({}, { x: 1, 'x.y': 1 });
{
	"_id" : ObjectId("54fe1117e08bb4de06cfb421"),
	"x" : {
		"y" : {
			"z" : 1
		}
	}
}
> db.test.findOne({}, { x: 1, 'x.y.z': 1 });
{
	"_id" : ObjectId("54fe1117e08bb4de06cfb421"),
	"x" : {
		"y" : {
			"z" : 1
		}
	}
}
> db.test.findOne({}, { x: 1 });
{
	"_id" : ObjectId("54fe1117e08bb4de06cfb421"),
	"x" : {
		"y" : {
			"z" : 1
		},
		"a" : {
			"b" : 2
		}
	}
}
```

It could be feasible to ignore 'select: true' if the projection includes a parent path, but IMO that occludes a perfectly valid use case.

**Comment by sxyuan** [comment]
I don't see why ignoring 'select: true' if the projection includes a parent path occludes a valid use case. The use case seems to be if you want to exclude all the fields except for those marked { select: true }, *except* when you don't specify a projection. (If you just want to exclude those fields all the time you can just use { select: false }, right?) Seems to be a pretty convoluted use case. On the other hand, my use case is that I want to extend the syntactic sugar you mentioned for not specifying a projection to when you don't specify a projection for a particular subdocument. To me, this seems much more natural. But I'll defer to your judgement.

A side note: I'm surprised to learn that the order in which you construct the projection can change the result in mongodb, which seems bug-like to me. Changing your example slightly:

```
> db.test.insert({ x: { y: { z: 1 }, a: { b: 2 } } });
WriteResult({ "nInserted" : 1 })
> db.test.findOne({}, { x: 1, 'x.y': 1 });
{
        "_id" : ObjectId("54fe17f3dbfe390b21022529"),
        "x" : { 
                "y" : { 
                        "z" : 1
                }
        }
}
> db.test.findOne({}, { 'x.y': 1, x: 1 });
{
        "_id" : ObjectId("54fe17f3dbfe390b21022529"),
        "x" : { 
                "y" : { 
                        "z" : 1
                },
                "a" : { 
                        "b" : 2
                }
        }
}
```

Going back to the original issue, this explains the second case I mentioned, because debugging output shows that the projection is in the "wrong" order.

```
Mongoose: parents.insert({ __v: 0, a: [ { _id: 'A', val: '1', x: 'X' } ], b: [ { _id: 'B', val: '2', x: 'Y' } ], _id: ObjectId("54fe1843ea37ae6721ab8b24") }) {}  
Mongoose: parents.find({}) { fields: { 'b.val': 1, b: 1, a: 1 } }  
{ _id: 54fe1843ea37ae6721ab8b24,
  b: [ { _id: 'B', val: '2', x: 'Y' } ],
  a: [ { _id: 'A', val: '1', x: 'X' } ] }
Mongoose: parents.drop()   
```

I'm using 2.6.1, so I'm not sure if this is still the case in later versions.

**Comment by vkarpov15** [comment]
Ah this may have something to do with my predecessor's decision to loop over keys with `while(i--)` every single time. Causes more trouble than its worth since, as you just noted, there are cases where mongodb relies on the V8 convention that JSON object keys have a well-defined order.

Back to the original point, `select: true` functions as a default whenever you call `select()`. If you don't call `select()`, mongodb will return all keys. If you call `select()` with fields to include, for instance `select('val')`, it will automatically attach any fields you attached `select: true` to in order to ensure those are included. To me, that seems like the natural implementation (except for, of course, the reversal of key order, but that's why I just opened #2749)

Either way, I don't want to make any backwards breaking changes to 4.0 that aren't absolutely necessary since we're now in 4.0.0-rc3, but this could pretty easily be implemented in a [plugin](http://mongoosejs.com/docs/plugins.html) (additional info in [my article on plugins](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins)). Would that be a reasonable solution?
