### ISSUE TITLE
Aggregate() function shouldn't take a spread

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2716]
Open to discussion. Right now `Model.aggregate()` looks through its arguments array and treats each of them as a pipeline. This makes it difficult to do things like pass options. IMO Model.aggregate's signature should change to

``` javascript
Model.aggregate([stages], [options], [callback]);
```

**Comment by loris** [comment]
+1

**Comment by simonxca** [comment]
@vkarpov15 Just fyi, the API docs still say `aggregate()` can take a spread http://mongoosejs.com/docs/api.html#aggregate_aggregate.

**Comment by vkarpov15** [comment]
@simonxca  thanks for reporting, we missed that
