### ISSUE TITLE
Key is missing from returned Query (but appears with lean()!)

### ISSUE THREAD

**Issue by framerate** [Automattic/mongoose#2720]
Hey guys!

So, I have the following schema:

```
{
    'version': {
        'type': Number,
        'default': 1
    },
    'user': {
        'type': mongoose.Schema.Types.ObjectId,
        'ref': 'user'
    },
    'date': {
        'type': 'Date',
        'default': Date.now
    },
    'score': {
        'type': Number,
        'default': 0
    },
    'snapshot': {
        'type': Object,
        'default': {}
    },
    'stats': {
        'type': Object,
        'default': {}
    }
```

And I query it like this:

```
Score.findOne({'user': req.user._id}).sort('-date').exec(function(err, score){
console.log(score.stats); // returns undefined
});
```

HOWEVER, adding lean():

```
Score.findOne({'user': req.user._id}).sort('-date').lean().exec(function(err, score){
console.log(score.stats); // returns the stats object!
});
```

My initial guess was that stats was a reserved term... but I searched both the API docs and Stackoverflow (and the issue tracker here) and didn't find the word 'stats' mentioned in this context.

Please advise?

**Comment by vkarpov15** [comment]
Does the snapshot field also disappear? And is this only happening when you save with the default value?

**Comment by framerate** [comment]
Nope, everything seems to work great except "stats" getting stripped out.

We renamed it "scoreStats" and now the same data works flawlessly (but obviously post launch we don't want to be renaming schemas!)

I just want to get to the bottom of WHY this is happening, and if 'stats' is a reserved mongoose word, make sure it's documented!

@vkarpov15 thanks so much for taking the time to track it down! If you can't reproduce it I can try and make a sample repository this weekend.

**Comment by vkarpov15** [comment]
Can you tell me what version of mongoose and what version of node? As far as I can tell, stats shouldn't conflict with any function names.

**Comment by framerate** [comment]
```
cat package.json| grep mongoose
    "mongoose": "^3.8.24",
```

```
node --version
v0.12.0
```

**Comment by framerate** [comment]
Also, the one thing that worried me from the mongoose codebase was stuff like this:

https://github.com/LearnBoost/mongoose/blob/3780063b75907687be5a3e2baad7922dc0556067/test/model.geosearch.test.js#L50

```
Geo.geoSearch({ type : "place" }, { near : [9,9], maxDistance : 5 }, function (err, results, stats) {
// ...
});
```

**Comment by vkarpov15** [comment]
Hmm I can't seem to reproduce this. The following standalone script seems to work for me, node 0.12, mongoose 3.8.24, mongodb 2.6.6:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var assert = require('assert');
var db = mongoose.createConnection('mongodb://localhost/gh2720');
mongoose.set('debug', true);

var schema = new Schema({ name: String, stats: { type: Object, default: {} } });

var Stats = db.model('gh2720', schema, 'gh2720');
Stats.create({ name: 'Kobe Bryant', stats: { points: 81 } }, function(error, kobe) {
  assert.ifError(error);
  Stats.findOne({ _id: kobe._id }).sort('-name').exec(function(error, doc) {
    assert.ifError(error);
    assert.equal(doc.stats.points, 81);
    db.close(function() {
      console.log('ok');
      process.exit(0);
    });
  });
});
```

What's your mongodb setup like - what version of mongodb server and are you using a sharded cluster?

**Comment by framerate** [comment]
Thanks @vkarpov15. Let me reproduce on my end and get you details. 

(@danacase and @mikejstein were reproducing it locally with me, in case they want to chime in)

**Comment by vkarpov15** [comment]
Issue is stale, re-open if this is still a problem.
