### ISSUE TITLE
Discriminators for child schemas

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2723]

**Comment by ducdigital** [comment]
@vkarpov15: By any chance you've got any process on this?

Thanks!

**Comment by vkarpov15** [comment]
Nope no progress thus far. Hasn't really been a priority unfortunately, which is why we've been kicking the can down the road for now. Contributions and/or +1's welcome.

**Comment by xpepermint** [comment]
+1

**Comment by ryanvanderpol** [comment]
+1

**Comment by kmarecki** [comment]
+1

**Comment by asabhaney** [comment]
+1

**Comment by sebastian-nowak** [comment]
This is really required.

**Comment by galdomar** [comment]
+1

**Comment by tonyharrison** [comment]
+1

**Comment by ivank** [comment]
Um any progress on this guys? Or we're waiting for the next "modified the milestone: 4.7, 4.6" :-D

**Comment by vkarpov15** [comment]
No progress thus far, but PRs are most welcome :)

**Comment by nicotroia** [comment]
+1

**Comment by derekjoos** [comment]
+1

**Comment by ducdigital** [comment]
This is big new! Thanks @vkarpov15

**Comment by vkarpov15** [comment]
http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html
