### ISSUE TITLE
Model.remove() should allow passing options

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2724]

**Comment by hasezoey** [comment]
From what i can tell, the `remove` function accepts options, since ~5.7.4 402db1a8f455306b1e0146d3fa3c776e3ee50da0

https://github.com/Automattic/mongoose/blob/master/lib/model.js#L963-L976

so i think this can be closed
cc @vkarpov15 @Uzlopak @AbdelrahmanHafez

**Comment by AbdelrahmanHafez** [comment]
Thanks @hasezoey

**Comment by hasezoey** [comment]
@AbdelrahmanHafez this should maybe also be added to the proper milestone
