### ISSUE TITLE
Not work c++ lib with iojs 1.5.0

### ISSUE THREAD

**Issue by ZloyDyadka** [Automattic/mongoose#2744]
With node v0.12 worked, but iojs 1.5.0 -
```
[Error: The specified procedure could not be found.
D:\Projects\Server\node_modules\mongoose\node_modules\mongodb\node_mod
ules\bson\build\Release\bson.node]
js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by vkarpov15** [comment]
Have you tried deleting your node_modules and re-installing with the npm version packaged with iojs 1.5? That usually solves this particular problem.

**Comment by ZloyDyadka** [comment]
Yes, clean install npm and iojs. NodeJS work, but iojs not.Re-installing not helpful

**Comment by vkarpov15** [comment]
Which version of Windows?

**Comment by ZloyDyadka** [comment]
8.1

**Comment by rydn** [comment]
Can confirm I am seeing this using io.js v1.5.1 on Fedora 21. Tried a re-install to no avail. Weird because I am able to use the native binding directly without any problems... Is the packaged version of mongodb in mongoose maybe causing this?

**Comment by vkarpov15** [comment]
Can you show me the output of your `node_modules/mongoose/node_modules/mongodb/node_modules/bson/builderror.l
og` file? This may be an issue where your node-gyp is still trying to use nodejs, at least that's the issue that pops up on my windows machine :)

**Comment by ZloyDyadka** [comment]
```
child_process: customFds option is deprecated, use stdio instead.
```

**Comment by vkarpov15** [comment]
Hmm check your version of bson, `cat node_modules/mongoose/node_modules/mongodb/node_modules/bson/package.json | grep "version"`. My colleague Christian just released a [new version of js-bson](https://github.com/mongodb/js-bson/commit/a4b8ff14e3dcc92d144817a806f4c5ba536a7f2e) that should have better support for io.js' latest round of backwards-breaking C++ API changes, so if you're not on 0.2.21, try doing `rm -rf node_modules/mongoose/node_modules/mongodb/node_modules/bson && npm install`

Also, that's the only output in your builderror.log file? Hmm that's really strange. Didn't know that a deprecation warning can cause a build to fail. See if bson 0.2.21 helps.

**Comment by AntouanK** [comment]
I get a similar error on `io.js` ( I use docker containers with `io.js` ).
I get this error when starting my service with `mongoose`
```shell
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

checking the `node_modules` directory in mongoose/.../mongodb/
```shell
➜  main-db git:(develop) ✗ ls node_modules/mongoose/node_modules/mongodb/node_modules
total 0
drwxr-xr-x   4 antouank  staff   136B  8 Apr 16:57 .
drwxr-xr-x  14 antouank  staff   476B  8 Apr 16:57 ..
drwxr-xr-x  13 antouank  staff   442B  8 Apr 16:57 mongodb-core
drwxr-xr-x  13 antouank  staff   442B  8 Apr 16:57 readable-stream
```

so I guess the `bson` module is missing?
( I tried to manually do `npm i bson` in the mongodb directory, but the message still comes up )
