### ISSUE TITLE
Remove retainKeyOrder: always use natural order for object keys

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2749]
Mongoose's tendency to reverse key order causes a lot of issues with indexes, etc. Better to always use natural order and (possibly) take a minor performance hit rather than reverse all keys and mess with user's indexes.

**Comment by paulmelnikow** [comment]
:+1:

**Comment by paulmelnikow** [comment]
By the way, is retainKeyOrder documented somewhere? Should it retain key order within nested documents (e.g. within Mixed properties) or only at the top level?

**Comment by vkarpov15** [comment]
retainKeyOrder is in mongoose's .clone() function. It's not really exposed in the API in any sane way. The only way right now is that if you set `schema.options.toObject.retainKeyOrder` to `true`, `save()` will insert new docs with correct key order as opposed to reverse key order.

**Comment by paulmelnikow** [comment]
That's helpful, thanks.

I'm using `$setOnInsert` which doesn't seem to support that option. I'm manually reversing the items, but agree this enhancement is a good idea.

**Comment by vkarpov15** [comment]
Can you open up a separate issue for that? This issue is for removing mongoose's questionable reversing of keys entirely, which won't be done until at least v5 because its backwards breaking

**Comment by paglias** [comment]
@vkarpov15 I think we encountered this code with code like this:

```
      let oldRepeat = task.toObject().repeat;
      _.assign(task, _.merge(task.toObject(),{}));
      console.log(task.modifiedPaths(), task.toObject().repeat === oldRepeat)
```

In code ^ we're merging an empty object to a document (task) so `task.modifiedPaths()` should be an empty array, instead it's always `["repeat"]` and `task.toObject().repeat === oldRepeat` is always false because the order of the keys in repeat is always different.

`task.repeat` is an object like `{a: true, b: true, c: true, ...}`

**Comment by vkarpov15** [comment]
`task.toObject().repeat === oldRepeat` will always be false, because `toObject()` does a `clone()`. That `_.assign()` is going to mark all paths as modified, because that's what `_.assign` does: assign all fields.

**Comment by paglias** [comment]
@vkarpov15 yeah, `task.toObject().repeat === oldRepeat` will always be false and indeed it's a wrong example. Anyway the fact that `repeat` is always marked as modified is not due to `_.assign` as it only mark modified  the `repeat` field but not for any other one.

**Comment by vkarpov15** [comment]
I don't understand. Can you provide a more substantial code example?

**Comment by paglias** [comment]
@vkarpov15 I'm really sorry for posting issues that I can't replicate myself but this is happening for real:

<img width="988" alt="schermata 2015-12-08 alle 17 53 04" src="https://cloud.githubusercontent.com/assets/589911/11661964/b12f58a4-9dd4-11e5-89a5-b01d6aef5b24.png">

As you can see from the screenshot above I'm merging `task.toObject()` with an empty object and then assigning everything to the task model and logging the modified paths, and as you can see from the terminal output below `repeat` is the only field among listed.

the model has many other fields other than the `repeat` field so I don't understand why it's showing only the it among the modified paths. In this second screenshot I log the output of `task.toObject()` before and after the call to `_.assign`:

<img width="690" alt="schermata 2015-12-08 alle 17 58 59" src="https://cloud.githubusercontent.com/assets/589911/11662152/9787a504-9dd5-11e5-8961-8dd60ee88d40.png">

I honestly don't understand why `repeat` is the only modified path

**Comment by paglias** [comment]
For completeness in this last screenshot you can see how `repeat` wasn't among modified paths before using `_.assign`
<img width="699" alt="schermata 2015-12-08 alle 18 03 13" src="https://cloud.githubusercontent.com/assets/589911/11662279/0fac5b24-9dd6-11e5-8229-4e4401465b23.png">

**Comment by vkarpov15** [comment]
Because `task.repeat` is the only nested object in your schema. When you assign an object, like `task.repeat = { a: 1 };`, `repeat` will always be modified regardless of the object. However, if you do something like `task.priority = 1`, it won't be modified if `task.priority` was already 1.

**Comment by gunnarlium** [comment]
I see from the comment in the code that not retaining key order is faster, but as far as I can tell, the only difference is how the looping is done. How big is the performance hit for either using the `reatainKeyOrder: 1` version, or not doing a reverse loop?

**Comment by vkarpov15** [comment]
To be honest the perf difference is minimal in my experience - it's much worse to accidentally miss an index because of key ordering. I would recommend using `retainKeyOrder` always.
