### ISSUE TITLE
Refactor $__registerHooksFromSchema

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2754]
`$__registerHooksFromSchema` is currently a tangled mess to make promises and hooks play nicely together. Would be great if we could move promise support into kareem and solve this is a more elegant way.

**Comment by vkarpov15** [comment]
Also will be related to #2688

**Comment by puzrin** [comment]
Will this issue cover support of "thenable" pre-hooks (hooks than returns promise instead of calling `next()`)?

I could not find any info about such use of pre-hooks, only some mentions about post hooks.

**Comment by vkarpov15** [comment]
Not necessarily. That's a separate feature, although vkarpov15/kareem#3 would help us do that. I haven't had a chance to take a look at grappling-hook yet though.

**Comment by puzrin** [comment]
Ok, then consider as request please, that it would be cool to tech hooks understand promises instead of callbacks. Should i create a new issue for that?

**Comment by vkarpov15** [comment]
Please do :)

**Comment by vkarpov15** [comment]
Consider this a follow-on to #4821
