### ISSUE TITLE
Code fails when I change model, why?

### ISSUE THREAD

**Issue by GunnarLindholm** [Automattic/mongoose#2763]
This is a very simple code I think, and I have  a lot of code similar to it,

    var id = '54fab5f5f0db68dc7b55f6b5';
    mongoose.model('Account').findOne({'_id':id}, function(err, bosa){ ....
													
And that code failes silently (I have mongoose.debug on)

But just changing the model,

    mongoose.model('Package').findOne({'_id':id}, function(err, bosa){ ...

at least shows me the log line

Mongoose: packages.findOne({ _id: ObjectId("54fab5f5f0db68dc7b55f6b5") }) { fields: undefined }  

Any ideas for debugging this? Any validation that might have failed and killed the process? What should I look for?

**Comment by vkarpov15** [comment]
Can you show me what Account and Package schemas look like?
