### ISSUE TITLE
addToSet object key order is reversed

### ISSUE THREAD

**Issue by dvideby0** [Automattic/mongoose#2771]
I noticed that if you use addToSet on an empty array, the first set of objects inserted are reversed? Any operation after will adhere to the order in which you specify. here is some code that we were using to test and it consistently works. Just wondering why we have to reverse the initial inserts.

Here is sample code that will show the issue.

```javascript
twitterFriends.findOne({screen_name: message.body.screen_name}, function(err, record){
        if(err){
          console.log(err);
          message.nack();
        }

        if(!record) {
          record = twitterFriends(
            {
              screen_name: message.body.screen_name,
              friends: []
            }
          );
          record.save(function(err) {
            if (err) {
              console.log('error: %j', err);
              message.nack();
            }
            console.log('create ' + record);
            data.forEach(function(friend){
              record.friends.addToSet({screen_name: friend.screen_name, name: friend.name, id: friend.id});
              record.save();
            });
            message.ack();
          });
        } else {
          console.log('update ' + record);
          data.forEach(function(friend){
            record.friends.addToSet({id: friend.id, name: friend.name, screen_name: friend.screen_name});
            record.save();
          });
          message.ack();
        }
      });
```

**Comment by dvideby0** [comment]
to hopefully add a little more explanation as to what is happening here. The code above will produce the following array on "create"

```javascript
[{id: 'someId', name: 'sameName', screen_name: 'someScreenName'}]
```

even though the order of keys is

```javascript
{screen_name: friend.screen_name, name: friend.name, id: friend.id}
```
It is ALWAYS the exact reverse of whatever you have set.

However, after that initial write to the document. all of the inserts will keep the order that you set with your code. This is why you see the order flip depending on if its a create or update. Hope this explanation helps.

**Comment by vkarpov15** [comment]
Mongoose likes to loop over keys with `while( --i)`, which is a convention to improve performance held over from previous incarnations. Some functions have a `retainKeyOrder` that lets you use in-order but I don't think there's any way to make addToSet do that, but IMO makes sense to always send keys in-order for addToSet.

An aside, this is a bit of a JavaScript <=> MongoDB grey area, because [BSON (MongoDB's storage format) assumes keys have a well-defined order, but strictly speaking JSON keys are not ordered](http://devblog.me/wtf-mongo). However, v8 does follow the convention that keys have well-defined order, so this is an issue of mongoose following the letter of the law rather than the spirit.

**Comment by vkarpov15** [comment]
Hmm I can't seem to reproduce this. The following script

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh2771');

var child = new mongoose.Schema({ id: Number, v: Number, mult: Number });
var schema = new mongoose.Schema({ nums: [child] });
var m = mongoose.model('gh2771', schema);

var x = new m({ nums: [] });
x.nums.addToSet({ id: 3, v: 1, mult: 5 });
x.save();
```

Saves the keys in the correct order. Can you confirm what version of mongoose you're using and see if  you can provide me a standalone repro?

**Comment by vkarpov15** [comment]
Can't repro and no response after 2 weeks, gonna close for now. Re-open if this is still an issue.
