### ISSUE TITLE
Feature: Helper Method: Model.upsert

### ISSUE THREAD

**Issue by justsml** [Automattic/mongoose#2777]
I think it would make the API more complete if it had a `Model.upsert` helper method ( a simple wrapper for `Model.update(q, obj, {upsert: true}, fn)`

If I'm off-base please let me know, I just thought it was in line with the extended `find()` methods, `findById`, `findByIdAndUpdate`, etc.

**Comment by justsml** [comment]
I've completed a commit for ```Model.upsert``` with additional tests:
https://github.com/justsml/mongoose/tree/feature/upsert
https://github.com/LearnBoost/mongoose/compare/master...justsml:feature/upsert

I think I followed the guide, but this is my first (hopeful) PR for mongoose...
So any feedback === appreciated^2

**Comment by vkarpov15** [comment]
So general feedback - if this is to go in, there should be a function in `lib/query.js` as well so you can chain calls like `model.update().upsert().exec()`. I would also imagine that things like `model.update().upsert(false).exec()` should be valid, so the query function should be able to handle cases where it receives params "[query], [update], [options], [callback]" as well as "[query], [update], [shouldUpsert], [callback]".

Also, if we're going to support chaining with the `upsert()` option, that would also imply that there should be a helper for the `multi()` option as well. The tricky bit with multi is that upsert's meaning is clear, whereas `Model.multi()` or `Query.multi()` can be unclear because the option is 'multi' for update but 'justOne' for remove, and there's no corresponding option for findAndModify...

**Comment by justsml** [comment]
Thanks @vkarpov15 

Just so I know I understand, are you saying it should support modifying the Query chain, switching the upsert flag on or off?

I'll write out the tests and see what I can come up with...

The ```{multi}``` option I've always thought was an awkward design...
If a ```findOne``` method was added, why isn't there a ```updateOne()```

**Comment by justsml** [comment]
Ok, read #803 ... I see... I'll finish the code + tests for upsert

**Comment by justsml** [comment]
I checked in some code, and I'm not sure why I'm having trouble with the ```Query.upsert```

I tried just overriding the ```options.upsert``` after the parameter shifting, and then returning something like ```this.update(criteria, obj, newOpts, callback)```

I also tried returning just ```this``` after calling the update method (with the callback)

I just tried copying the entire Query.update method and just tweaking it -- that got me close, but still returning (null, null) to the callback.

@vkarpov15 I'm sure I'm just mis-reading the functionality or missed a dot somewhere , any insight is really appreciated.

**Comment by vkarpov15** [comment]
Hmm nothing looks obviously wrong. I can look more closely tomorrow.

**Comment by justsml** [comment]
Hey everyone, I looked into this problem again.

I finished the ```Model.upsert``` with much better tests (so far at least): https://github.com/justsml/mongoose/tree/feature/model_upsert_2

The problem with creating a chained ```Query.upsert``` method is it runs into an endless loop when ```mquery.setOptions``` finds a method named upsert on it's this/context.

@vkarpov15  do you have any suggestions, or who should I *nicely* bug?

Thanks in advance!

**Comment by vkarpov15** [comment]
I don't see why it would get stuck in an infinite loop - I don't see where mquery even references `this.upsert`, where do you see that?

**Comment by justsml** [comment]
When Query.update is called, it runs setOptions on it's base.

setOptions checks to see if the ```options``` key names are functions, now, ```upsert``` is both an option and a function name. 

**_I guess I'm trying to figure out/seeking advice on the most minimal implementation, without running into compatibility issues or conflicts in mquery?_**

See this line below: ```this[method].apply(this, args)```

```javascript
Query.prototype.setOptions = function (options) {
  if (!(options && utils.isObject(options)))
    return this;

  // set arbitrary options
  var methods = utils.keys(options)
    , method

  for (var i = 0; i < methods.length; ++i) {
    method = methods[i];

    // use methods if exist (safer option manipulation)
    if ('function' == typeof this[method]) {
      var args = utils.isArray(options[method])
        ? options[method]
        : [options[method]];
      this[method].apply(this, args)
    } else {
      this.options[method] = options[method];
    }
  }

  return this;
}
```

**Comment by joeytwiddle** [comment]
Sorry to see this didn't get completed.

I keep finding myself writing:

```
myModel.update(
  {
    key1: key1,
    key2: key2,
    key3: key3
  },
  {
    key1: key1,
    key2: key2,
    key3: key3,
    data: newData
  },
  { upsert: true }
)
```

at which point I think to myself

"If Mongoose already knows those things are keys, can't it pull them from the `doc` object for me?"

**Comment by vkarpov15** [comment]
Hmm you shouldn't need to do that, the below should be sufficient:

```javascript
myModel.update(
  {
    key1: key1,
    key2: key2,
    key3: key3
  },
  {
    data: newData
  },
  { upsert: true }
)
```

**Comment by joeytwiddle** [comment]
*just some random thoughts which you may skip*

Come to think of it, whenever we do upsert on keys X,Y,Z we also always create a unique index on fields X,Y,Z.

It might be tempting to have mongoose enforce this: to only allow upserts on things which are unique keys, and warn the developer if they are not.

(As you may recall, I am often in favour of strictness, to help developers by catching when they are making mistakes.)

But on the other hand, there are probably people out there already using upsert in strange ways, without having set a unique key index, so this behaviour would break their existing apps. And if we made this behaviour opt-in, then it would not really help the people who need it!

But it might perhaps be something I could add to my mongoose strictness library ... ;)

Thanks for your continue maintenance!

**Comment by vkarpov15** [comment]
That idea feels a bit heavy-handed IMO, thanks for the suggestion though :+1:  :palm_tree:
