### ISSUE TITLE
Improve custom validator docs to have more examples

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2778]

**Comment by justsml** [comment]
Hey @vkarpov15 ... I thought this area deserved some attention. 

Please check out some updates I'm working on https://github.com/justsml/mongoose/commit/2c0d42bda91425b7fb54bdc90e02363808b124d4

I started by updating the tests so they are more readable, and therefore better example material for the docs.
I think it still needs a chained/monadic function text+example....

Let me know if i'm heading in the right direction.

Thanks in advance!
