### ISSUE TITLE
Online documentation: broken link

### ISSUE THREAD

**Issue by rstormsf** [Automattic/mongoose#2779]
http://mongoosejs.com/docs/docs/api.html#model_Model.find
FROM
http://mongoosejs.com/docs/queries.html

>Anywhere a callback is passed to a query in Mongoose, the callback follows the pattern callback(error, >results). What results is depends on the operation: For findOne() it is a potentially-null single document, >find() a [list of documents](http://mongoosejs.com/docs/docs/api.html#model_Model.find), count() the >number of documents, update() the number of documents affected, etc. The API docs for Models >provide more detail on what is passed to the callbacks.

**Comment by vkarpov15** [comment]
Thanks for catching this, on it.
