### ISSUE TITLE
Save document without schema

### ISSUE THREAD

**Issue by devntd** [Automattic/mongoose#2780]
I have object 
game = { 
gameId: "916304e8-c2ee-4d54-8ef1-8a5d75c7ba90", 
gameName: "What Kind Of Person Are You Really?",
score: Number
}

var gameSchema = new Schema({
   game: String,
   gameName: String
}, { strict: false });
var Game = mongoose.model('Game', gameSchema );
var game= new Game(game, { iAmNotInTheSchema: true });
game.save()

But score is not saved to the db!

**Comment by artiifix** [comment]
http://mongoosejs.com/docs/guide.html#strict

**Comment by vkarpov15** [comment]
Where are you actually setting score?
