### ISSUE TITLE
how to use Secondary?

### ISSUE THREAD

**Issue by Ohen** [Automattic/mongoose#2781]
```
Users.aggregate(
    { $group: { _id: null, maxBalance: { $max: '$balance' }}}
  , { $project: { _id: 0, maxBalance: 1 }}
  , function (err, res) {
  if (err) return handleError(err);
  console.log(res); 
});
```

example, this querys didn't work...

I want to send it as a secondary, so I try to read('read'). but didn't work 

I try to example query. 
```
MyModel.aggregate({
    $match: {
        createdAt: {
            $gte: start,
            $lte: end
        }
    }
}, {
    $group: {
        _id: { day: {$dayOfMonth: "$createdAt"}, month: {$month: "$createdAt"}, year: {$year: "$createdAt"} },
        count: {$sum: 1}
    }   
})
.read("secondary")
.exec(callback);
```
but , didn't work...
```
 2015-03-23 15:06:49 TypeError: Cannot read property 'readPreference' of undefined
```
this error display.

how to use secondary mongodb??

**Comment by vkarpov15** [comment]
How are you connecting to this replica set? Also, what version of mongoose are you using?

**Comment by Ohen** [comment]
yes, I connecting to this replica set and use 2.4.6 version,

**Comment by vkarpov15** [comment]
Hmm I can't repro this. Can you provide me the following bits of information?

1) Stack trace for the above error
2) Version of mongoose that you're using

**Comment by vkarpov15** [comment]
Can't repro and no response for a couple weeks - re-open if this is still an issue.
