### ISSUE TITLE
Unstable tag on release 4.0.0

### ISSUE THREAD

**Issue by SamyPesse** [Automattic/mongoose#2792]
@vkarpov15 

```
$ npm view mongoose dist-tags
{ latest: '4.0.0', unstable: '4.0.0' }
```

Which is causing this: https://github.com/Automattic/mongoose/blob/master/lib/index.js#L30

**Comment by SamyPesse** [comment]
You should run: `npm dist-tag rm mongoose unstable` with `npm@2.5.0`

**Comment by vkarpov15** [comment]
Fixed, thanks!

**Comment by akreienbring** [comment]
When I run my server with mongoose 4.0.0 installed it still tells me on the shell that i run an unstable release.

**Comment by vkarpov15** [comment]
@akreienbring #2794
