### ISSUE TITLE
Unstable warning

### ISSUE THREAD

**Issue by edgarmarkosov** [Automattic/mongoose#2794]
Please remove the unstable warning in mongoose v 4.0.0 as it is considered already as stable version.

**Comment by mirkods** [comment]
:+1:

**Comment by tonghae** [comment]
+1

**Comment by Apercu** [comment]
:+1:

**Comment by thody** [comment]
README also refers to 3.8.x as current stable version.

**Comment by solshark** [comment]
+1 Switched in production and it's very hard to me to see this warning. I want to cry time to time and my CI server makes me crazy :)

**Comment by vkarpov15** [comment]
Yep looks like I forgot to switch that over. On it!

**Comment by vkarpov15** [comment]
For now, to hide this warning, use `env MONGOOSE_DISABLE_STABILITY_WARNING=1`

**Comment by devinus** [comment]
Yikes!

**Comment by vkarpov15** [comment]
Yeah sorry about that, something that I missed when I was creating the release checklist. This is my first major mongoose release so there was bound to be a minor snafu :( however, it's a relatively minor issue and easy to work around.

**Comment by edgarmarkosov** [comment]
Thank you.

**Comment by mellema** [comment]
I npm installed mongoose moments ago and I'm still getting the unstable warning

**Comment by vkarpov15** [comment]
Will go away when 4.0.1 is pushed. Don't worry about the warning, 4.0.0 is stable. I'm just waiting to see if I can get a repro for #2798 before bumping 4.0.1.

**Comment by mellema** [comment]
ok thanks
