### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in connection/base.js 

### ISSUE THREAD

**Issue by nabulaer** [Automattic/mongoose#2795]
this bug was resolved on 3.8.22  #2757

now on 3.9.7 it is back.

**Comment by aggied** [comment]
Also having issues with this on 3.9.7

**Comment by vkarpov15** [comment]
Simple solution: don't use 3.9.7. It prints loud warnings when you run it and it's marked as unstable in npm, with good reason, it was an experimental development release. Either use 3.8.x or 4.0.x. Mongoose will use semver going forward, but the 3.x release series did not.
