### ISSUE TITLE
model.update with a json including only a nested attribute does not work and turns out with op: "find" 

### ISSUE THREAD

**Issue by anfield6road** [Automattic/mongoose#2796]
When I use the update method of a model which includes nested objects (mixed) at least once it does only work if I include a not-nested attribute to the "update" parameter.
Otherwhise it does not update my document(s), but return with a list corresponding to the filter.
This worked with e.g. mongoose@3.8.17 or mongoose@3.9.7, not with mongoose@4.0.0.
Every information needed is in the [gist](https://gist.github.com/anfield6road/e55d91c1faf66c881083) attached.

```npm install mocha -g```
```mocha -b```

For any further information needed please inform.

**Comment by anfield6road** [comment]
while testing with mongoose@3.8.17 or mongoose@3.9.7 the ".n" has to be removed in lines 55 and 61 - due do changes in mongoose@4.0.0

**Comment by vkarpov15** [comment]
Yeah this is a bug unfortunately. Or a few different bugs coming together that were masked in older versions

1) update() bugs out when you use promises and there's an error casting the update portion - as you see, it'll execute a find
2) castUpdate() is returning an empty object when it's trying to cast the first update that only includes a nested field.

**Comment by anfield6road** [comment]
yeah right, when I remove promises and change to callbacks, its not any longer _op: "find"_, but still does not update the right elements:
updatedElementsFirstUpdate= { ok: 0, n: 0, nModified: 0 }

**Comment by vkarpov15** [comment]
Yeah that's the castUpdate issue (2) - it thinks that the update is empty. Thanks for pointing this out, I'm investigating a fix.

**Comment by anfield6road** [comment]
can agree.
in /lib/query.js - line 1912
castedDoc turns out to be "0"

**Comment by vkarpov15** [comment]
Put a fix for both issues in a PR, see #2800.

**Comment by anfield6road** [comment]
both working now with branch gh-2796. 
great job!!

**Comment by vkarpov15** [comment]
There's still one issue that I'm not entirely satisfied with though - if you don't specify a callback, mongoose will throw an error if it fails to cast. This means that you'd have to wrap your .update() calls in a try/catch if you're using promises in case there's a cast error. This is expected behavior from 3.x, and I'm hesitant to change that because of semver.

**Comment by anfield6road** [comment]
could be disturbing and is not a good behavior, right. but i prefer wrapping the mongoose functions anyway, while catching the error has only to be done once in wrapped function. 
so for my use fix is quite ok.
thanks again!
