### ISSUE TITLE
isNew value in pre-save hook

### ISSUE THREAD

**Issue by carlosaviles** [Automattic/mongoose#2797]
Hi,
this is more a question than describing an issue.

If I save a document, then remove it and try to save it again using the same model instance: why is the value of isNew true during that second save? Shouldn't it be false since the document was removed and the MongoDB shouldn't know about it anymore?

Thanks,
Carlos.

**Comment by vkarpov15** [comment]
As far as I can tell, isNew shouldn't be true during the second save unless there was an error with the first save. Can you show me some code that reproduces what you're seeing?

**Comment by carlosaviles** [comment]
I have set a simple unit test on a test model:

This is the model:
```
'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var TestSchema = new Schema({
  name: String,
  info: String,
  active: Boolean
});

/**
 * Pre-save hook
 */
TestSchema
  .pre('save', function(next) {

    if (!this.isNew) {
    	console.log('not new!!');
      return next();
    }
     
    next();
  });

module.exports = mongoose.model('Test', TestSchema);
```
And this is the unit test:
```
'use strict';

var should = require('should');
var app = require('../../app');
var request = require('supertest');
var Test = require('./test.model');

var testObject = {
  name: 'somename',
  info: 'someinfo',
  active: true
};

var testModelObject = new Test(testObject);

describe('Model', function() {

  it('should save, remove and save again and leave one object in the DB', function(done) {

    // Add document
    testModelObject.save(function(err) {
      // Remove all documents
      Test.remove({}, function() {
        // Add same document again
        testModelObject.save(function(err) {
          // Fetch all documents
          Test.find({}, function(err, tests) {
            tests.should.have.length(1);
            done();
          });
        });
      });
    });
  });
});
```
The unit tests fails and outputs
```
Model
not new!!
    1) should save, remove and save again and leave one object in the DB
1 failing

  1) Model should save, remove and save again and leave one object in the DB:
Uncaught AssertionError: expected [] to have property 'length' of 1 (got 0)
```
Best,
Carlos.

**Comment by vkarpov15** [comment]
I see what you mean. This is because mongoose doesn't use the upsert option when the document is not new - mongoose doesn't know that the document was removed, and so tries to update an existing document. I think you'll find that the second save actually returns a VersionError.

Not much mongoose can really do in this case with the library and mongodb as they currently stand beyond return an error - even if mongoose tracked which documents were checked out and marked them as new when `Test.remove()` was called, that would not work across multiple processes.

**Comment by carlosaviles** [comment]
OK, I see. The only place I am having problems with this is in my unit tests where I reuse this model objects throughout tests. I'll instantiate new objects for each tests.

Thanks a lot for the prompt feedback!
