### ISSUE TITLE
Using $elemMatch to filter a subdocument based on a mongo ID

### ISSUE THREAD

**Issue by longieirl** [Automattic/mongoose#2799]
Hi All,

We have two schema's, one which stores the ID's to another document as a String and the other stores the reference as an ObjectId. The filter is applied to a findOne as follows where userId is a string:

```
var filterParams = {
            answers: {$elemMatch: {'created_by': userId}}
        };
Something.findOne({status: 'published', filterParams).lean(true)
```

The filter works where the userId being stored is a string. Even casting the userId to an ObjectId does not produce the same behaviour. So I guess the question is whether elemMatch works against ObjectId?

Any advice is appreciated?

StackOverflow:
http://stackoverflow.com/questions/29281577/using-objectid-and-or-string-to-filter-references-to-a-other-documents

J

**Comment by vkarpov15** [comment]
I don't quite understand your question. $elemMatch should work against ObjectId, but it depends on the underlying schema - mongoose will try to cast whatever you give it in elemMatch to the correct type.

**Comment by longieirl** [comment]
Can you please answer one question? What is the best practice when storing reference _id's belonging to another document? To store them as string or ObjectId? Or does it matter?

```
answers: {$elemMatch: userId},
```
Is it possible to use a String i.e. userId even though the type in mongodb is an ObjectId?

I will update this ticket with more detail around the model.

**Comment by vkarpov15** [comment]
As long as the schema says that answers is an array of ObjectIds then yes, you can pass a string.

Best practice depends on if you're generating your own object ids or not. If you're relying on mongodb to create them, I'd recommend you store them as an ObjectId rather than as a string because it takes less space (12 bytes vs 24)

**Comment by longieirl** [comment]
Thanks for your time!
We are generating our own ObjectId's when creating an any document, the _id is created before the save. Would this have any issue on how elemMatch works when trying to query a subdocument based on an ObjectId? As stated earlier, the model explicitly defines the type as ObjectId but we are passing around Strings.

**Comment by vkarpov15** [comment]
Mongoose types have a `castForQuery` function that, as you might guess, takes arbitrary input and attempts to cast it into the correct type. If you're passing around strings for answers but you're running a query where answers is expected to be an ObjectId, mongoose will cast it for you, so long as the string is a valid hex representation of an ObjectId.

For instance, the below script:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');
var assert = require('assert');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2799');

var exampleSchema = new Schema({
   listOfIds: [{ myId: Schema.Types.ObjectId }],
});

var Example = mongoose.model('gh2799', exampleSchema);
Example.findOne({ listOfIds: { $elemMatch: { myId: '000000000000000000000001' } } }, function(err) {
  assert.ifError(err);
  console.log('success');
  process.exit(0);
});
```

Will output:

```
Mongoose: gh2799.findOne({ listOfIds: { '$elemMatch': { myId: ObjectId("000000000000000000000001") } } }) { fields: undefined }  
success
```
