### ISSUE TITLE
Validation error.<field>.type replaced by error.<field>.kind in 4.0.0, undocumented potentially breaking change

### ISSUE THREAD

**Issue by jangelon** [Automattic/mongoose#2801]
It looks like in 4.0.0 the structure of error message responses on validation was changed slightly.

I have this schema:
```
var schema = new Schema({
  title: {
    type: String,
    required: true
  }
});
```

Then create an empty doc with that schema and validate it:
```
doc.validate(function (err) {
  console.log(err);
}
```
In 3.8.25 when validating I get this error:
```
{ message: 'Validation failed',
 name: 'ValidationError',
 errors: 
 { title: 
  { message: 'Path `title` is required.',
    name: 'ValidatorError',
    path: 'title',
    type: 'required',
    value: undefined
  } 
 } 
}
```

in 4.0.0 I get this error:

```
{ message: 'Schema validation failed',
  name: 'ValidationError',
  errors: 
   { title: 
      { properties: [Object],
        message: 'Path `title` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'title',
        value: undefined 
      }
   } 
 }
```

Type has been replaced by kind, so anyone checking the type will now be getting null.

I didn't see this change noted anywhere, but I may have missed it.
Thanks!

**Comment by vkarpov15** [comment]
Hmm not sure when this happened either, I'll investigate and see if I can track down why this changed.

**Comment by vkarpov15** [comment]
So this is unfortunately an intentional change that was introduced into 3.9.0 before I got involved in the project, so I missed it while aggregating release notes. See discussion in #1323 and the [corresponding v8 issue recommending not to set error.type](https://code.google.com/p/v8/issues/detail?id=2397).
