### ISSUE TITLE
Bug with 3.9.7 and clone module

### ISSUE THREAD

**Issue by nfriedly** [Automattic/mongoose#2802]
Hi, not sure if you guys are still interested in this one now that you're on 4.0, but with the 3.9.7 release, calling clone (https://www.npmjs.com/package/clone) on a model got me this error:
```
TypeError: Cannot use 'in' operator to search for '__v' in undefined
  at model.Document.$__shouldModify (/Users/nfriedly/watson-developer-cloud/node_modules/mongoose/lib/document.js:633:42)
  at model.Document.$__set (/Users/nfriedly/watson-developer-cloud/node_modules/mongoose/lib/document.js:654:43)
  at model.Document.set (/Users/nfriedly/watson-developer-cloud/node_modules/mongoose/lib/document.js:596:10)
  at model.Object.defineProperty.set [as __v] (/Users/nfriedly/watson-developer-cloud/node_modules/mongoose/lib/document.js:1331:45)
  at _clone (/Users/nfriedly/watson-developer-cloud/node_modules/clone/clone.js:99:16)
  at clone (/Users/nfriedly/watson-developer-cloud/node_modules/clone/clone.js:105:10)
  at /Users/nfriedly/watson-developer-cloud/admin-app/routes/services.coffee:102:10
  at /Users/nfriedly/watson-developer-cloud/admin-app/routes/services.coffee:20:3
  at /Users/nfriedly/watson-developer-cloud/node_modules/mongoose/lib/query.js:1164:16
  at /Users/nfriedly/watson-developer-cloud/node_modules/mongoose/node_modules/kareem/index.js:101:16
  at process._tickDomainCallback (node.js:486:13)
```
On a related note, I had done the standard `npm install mongoose` which put `"^3.8.15"` in my package.json. When I deployed the code to a server it took the latest 3.x release, 3.9.7, which is apparently an unstable release... this is a bit frustrating to say the least. If you guys instead add a prerelease tag so that the version is something like `3.9.7-unstable`, then NPM won't automatically install it when I ask for the latest 3.x release - see more at https://docs.npmjs.com/misc/semver#prerelease-tags

**Comment by vkarpov15** [comment]
Ah I guess the issue is that now npm is picking up 3.9.7 as a stable release due to the fact that I removed unstable tags entirely re: #2792. Sorry for the packaging snafu - mongoose will support proper semver after 4.0 to avoid these particular issues. 3.9.7 was an unstable release designed as an experimental development release on the way to 4.0, and should not be used. I will mark those releases as unstable to avoid this particular issue.

**Comment by vkarpov15** [comment]
Hmm so looks like neither dist-tags nor `npm deprecate` do the job here. Please use `"mongoose": "~3.8"` as a workaround.

**Comment by nfriedly** [comment]
Yep, that's what I have for the moment. Thanks.

**Comment by vkarpov15** [comment]
Thanks. When you upgrade to 4.0 you'll be able to use "^" as you might expect. Looking forward to seeing Watson in action in NodeJS :)

**Comment by nfriedly** [comment]
Cool, I'll get things upgraded sometime soon. I had held off because the readme still says that 3.8 is the current stable release, is that correct?

**Comment by vkarpov15** [comment]
4.0 is now the current stable release, ~3.8 is now considered the official legacy support for 3.x. There will be maintenance releases to 3.8 until at least September 1, but I'd recommend you consider upgrading. You can find [4.0 release notes on the Github wiki](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes)

**Comment by nfriedly** [comment]
Oh, ok, thanks. It looks like the readme is up to date here, but not on https://www.npmjs.com/package/mongoose

**Comment by vkarpov15** [comment]
Yeah the github readme was updated yesterday because I missed a couple points on my release checklist when releasing 4.0, but I haven't pushed 4.0.1 yet.
