### ISSUE TITLE
Global event for document creation

### ISSUE THREAD

**Issue by felipe-pereira** [Automattic/mongoose#2803]
This is just a question (not a bug or feature request).

Is there an event I can use that gets triggered when a document is saved (regardless of the schema)?

Now I use this (for Users schema):

	UserSchema.pre('save', function(next) {
	  if (this.isNew) {
		//do something here
	  }
	  next();
	});

But I'm looking for something that is called on every document schema, like:

	mongoose.Schema.pre('save', function(next) {
	  if (this.isNew) {
		//do something here
	  }
	  next();
	});

Thanks

**Comment by vkarpov15** [comment]
Nope but this is the sort of thing that a plugin (see [my guide to plugins](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) and the [mongoose plugins docs](http://mongoosejs.com/docs/plugins.html)) can do for you.

```javascript
_.each(schemas, function(schema) {
  schema.plugin(myPreSavePlugin);
});
```

You can also inherit from the mongoose schema class and attach whatever extra behaviors you need in your schema class.

```javascript
function MySchema() {
  Schema.apply(this, arguments);
  this.pre('save', function(next) {});
}

util.inherits(MySchema, Schema);
```

**Comment by felipe-pereira** [comment]
@vkarpov15 thanks for your quick response, I'll take a look at that and make it work.
