### ISSUE TITLE
npm install mongoose fails for any version earlier than current 

### ISSUE THREAD

**Issue by adriatic** [Automattic/mongoose#2805]
This happens on Windows 8.1 with Visual Studio 2013 - I am assuming that the mongoose installation involves the use of some parts of Visual Studio (msbuild and some C++ libs). It seems that all that is related to build bson, so the failed installation results with use of JavaScript version of bson.

If this is of interest to mongoose team, I can provide all supporting evidence.

**Comment by vkarpov15** [comment]
It's not a failure, just a warning. The native js bson implementation is functional, just doesn't quite use memory as efficiently. For development work, js bson should be sufficient.

Make sure you have all the [node-gyp windows dependencies](https://github.com/TooTallNate/node-gyp) installed, including Python.

**Comment by adriatic** [comment]
Thanks for your response - did not expect is so soon, so you gave my confidence on npm in general and mongoose in particular.
A few additional questions:
- Is there a good explanation why am I getting these warnings for any mongoose older than 4.0?
- Why is mongoose 4.0 (which seems to be a release version) issuing a warning "This is an UNSTABLE release of Mongoose."?
- Until not to long ago, i had no issues with any version of mongoose - so something changed without my doing anything. Can you please explain this?
Thanks and regards
Nik

**Comment by adriatic** [comment]
Also, I do have the node-gyp windows dependencies installed, yes. Seeing any "error conditions" / "warnings" (all these are shown in red) flying by when building the app is not a good feeling and I certainly would feel worried delivering such solution to the customer :-)

**Comment by vkarpov15** [comment]
1) Not sure. Are you using io.js? They break their c++ API regularly so keeping our c++ build compatible with all versions of io.js is a struggle.

2) 4.0.1 fixes this issue, see #2794 - I missed removing that warning when I bumped 4.0.0. 4.0.0 is stable.

3) What version of mongoose and node are you running?

And I wouldn't worry too much about the warnings. The mongodb driver and mongoose are designed to work even if you don't have a C++ compiler installed (with the exception of Kerberos auth). We're also currently working on making it easier to get the compiled bson parser, because a lot of windows users struggle with getting it to compile.

**Comment by adriatic** [comment]
1) No, I am not using io.js (never did actually). 
2) This resolves the issue 1) -- for me at least as I am still collecting all pieces for my app and have no need to go back to history. If you find the need to resolve my issue 1), I am willing to help with any amount of time.
3) I was always using the "latest" mongoose until sometime ago, when building it started to give a lot of bson related warning. Then 4.0 came as the latest and it does not have bson problems, but issues the "not stable" warning, something we just resolved. 

When million years ago I started my career in Mountain View CA, all I wrote was z80 code and switch to C was associated with paranoia about "generated code" (read: stability of the compiler). Now, seeing  that "npm install" brings in up to 100 Mbytes of code that I have no idea what it does, and who maintains it, one could understand that I am not always completely at ease despite that I love everything about NodeJS

**Comment by vkarpov15** [comment]
Yeah I understand the feeling - I started my career at a shop that liked to build everything in-house, up to and including writing their own TCP stack. However, I like using trusted npm modules much the same way I like using linux - I might not understand the internals, but there are a lot of people out there using the modules for some very difficult use cases, so when they find issues I reap the rewards in the form of [Linus' Law](http://en.wikipedia.org/wiki/Linus%27s_Law#By_Eric_Raymond). Regardless, if you have mongoose and/or mongodb related issues, don't hesitate to reach out.

**Comment by adriatic** [comment]
Thanks Valeri - I feel as if someone is "having my back". This is quite important as I recently re-planted myself in MEAN stack after spending eons in MS world.

**Comment by MichaelWhite63** [comment]
I am installing Mongoose on Windows Server 2008R2 and would like to confirm that I do need to have visual studio installed.  If so, is there a specific version?  Can I use Visual Studio Community with Update 4?

**Comment by vkarpov15** [comment]
You don't *need* to have visual studio installed for mongoose to work. There is exactly 1 feature that will flat out not work without a native extension, and that's kerberos authentication. If you absolutely need kerberos auth, I will defer to [node-gyp's installation instructions](https://github.com/TooTallNate/node-gyp#installation). According to TooTallNate/node-gyp#380 looks like you need VS2012.

**Comment by adriatic** [comment]
@vkarpov15 Valeri - I am pretty sure that the only component from the Visual Studio that is needed is the C++ run-time, that is used by node-gyp to compile "installer generated native code". Unfortunately the list of dependencies for node-gyp (https://github.com/TooTallNate/node-gyp/blob/master/package.json) is not taking this component in the account so one has to guess what is that you need to do. Most of the time the flags defining the C++ runtime context are incorrect, so that people having VS2013 installed are led to believe that they need to go back to VS2012 instead of fixing the "C++ runtime context" flag (say from v12 to v11 or vice versa).

The real problem is that Windows environment is still a bit of a foster child for npm - so, one of these days I will put on my diving suit and clean this mess once for ever :-)

**Comment by vkarpov15** [comment]
I'd appreciate that very much :)

**Comment by MichaelWhite63** [comment]
I did the following and it worked fine:

- Installed Python
- SET Python=c:\Python27\python.exe
- npm install –g node-gyp
- Installing MS Visual Studio: Visual Studio Community 2013 with Update 4
- npm install -g mongoose

Thank you for the information.

**Comment by vkarpov15** [comment]
I would not recommend installing mongoose with -g, it's almost always the wrong choice. See http://thecodebarbarian.com/2015/02/27/npm-install--g

**Comment by adriatic** [comment]
Yesterday i stated that
> The real problem is that Windows environment is still a bit of a foster child for npm - so, one of these days I will put on my diving suit and clean this mess once for ever :-)

I have to take this back and accept the fact that problem is caused by a huge "support matrix" needed to cover all variants of Windows OS and C++ compiler in existence today. Given the fact that it's year 2015 I am quite unhappy that so many people require support for products like Visual Studio 2010 or 2012, which when installed will make the problem go away
> if you absolutely need kerberos auth, I will defer to node-gyp's installation instructions. According to TooTallNate/node-gyp#380 looks like you need VS2012.

The simplest solution today is to install [Visual Studio Express 2013](https://app.vssps.visualstudio.com/profile/review?download=true&family=VisualStudioExpressDesktop&release=VisualStudio2013Upd4&type=web&slcid=0x409&context=eyJwZSI6MSwicGMiOjEsImljIjoxLCJhbyI6MiwiYW0iOjAsIm9wIjpudWxsLCJhZCI6bnVsbCwiZmEiOjAsImF1IjpudWxsLCJjdiI6MTc2MDU0OTI2OCwiZnMiOjAsInN1IjowLCJlciI6MX01) which is available for free, so anyone can install it.

Folks that care about more details [check this discussion](http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props)

**Comment by adriatic** [comment]
@vkarpov15: by the way I love the reasoning and writing style in http://thecodebarbarian.com/2015/02/27/npm-install--g

**Comment by MichaelWhite63** [comment]
I read the article and he has a valid point.  I prefer not to go through removing it and re-installing but in the future I will think twice before using the -g option on my installs
