### ISSUE TITLE
Migration guide version number

### ISSUE THREAD

**Issue by meng-zhang** [Automattic/mongoose#2807]
Hi, I am looking at the Migration guide for V4, but in this page:
http://mongoosejs.com/docs/migration.html
I see "Migrating from 2.x to 3.x"

I guess it should be "Migrating from 3.x to 4.x"

Please correct me if I am wrong. Thanks.

**Comment by vkarpov15** [comment]
[Release notes for 4.0 are up on the Github wiki](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes). The migration docs above are in fact for migrating from 2.x to 3.x, although those should probably be removed now that 3.x is the legacy version.

**Comment by meng-zhang** [comment]
Thanks a lot

**Comment by djensen47** [comment]
Are the docs on the mongoosejs.com site current for 4.x or legacy for 3.x? 

If mongoosejs.com is all 4.0 documentation, then http://mongoosejs.com/docs/migration.html is still showing the wrong documentation.

**Comment by djensen47** [comment]
Just out of curiosity, when does the documentation that lives on mongoosejs.com get pushed?

**Comment by vkarpov15** [comment]
Whenever a new release is pushed, so 4.0.3 will be next release of mongoosejs.com too. In this case, there was a mistake that prevented jade from compiling the migration docs.
