### ISSUE TITLE
Issues when using $lt or $lte on date object

### ISSUE THREAD

**Issue by christopherdro** [Automattic/mongoose#2811]
I'm currently having some issues with comparing dates using the $lt/$lte operators.

Ive tried standard date object, ISO strings, and moment.js objects as options for the value to compare and all work fine on my local but not when I deploy to heroku.

If I only use $gte everything works in both environments.
 
I am currently using Compose on Heroku for my DB.
Here is a snippet of the code. 
```
var dateRequest = new Date(req.body.dateTime);
var dateRange = new Date(dateRequest);
  
  dateRange.setHours(dateRequest.getHours() + 1);
  // dateRequest = dateRequest.toISOString();
  // dateRange = dateRange.toISOString();
  
  var query = Restaurant.find().populate({ 
    path: 'reservations',
    match: { dateTime: { $gte: dateRequest, $lte: dateRange}, _user: { $exists: false}}, // Important part of query.
    options: { sort: { dateTime: +1 }}
  });
```
Thanks in advance!

**Comment by vkarpov15** [comment]
Lots of moving parts to this question. Can you enable debug mode, `require('mongoose').set('debug', true)` and show me what queries are being sent to mongodb from heroku?

**Comment by christopherdro** [comment]
Here is a comparison of the requests from both my local and Heroku with debug turned on.

Local
```
dateTime: { '$gte': new Date("Tue, 31 Mar 2015 02:30:00 GMT"), '$lte': new Date("Tue, 31 Mar 2015 03:30:00 GMT") }, minParty: { '$lte': 2 }, maxParty: { '$gte': 2 }, _user: { '$exists': false } }) { sort: { dateTime: 1 }, fields: undefined }
```
Heroku
```
dateTime: { '$gte': new Date("Tue, 31 Mar 2015 02:30:28 GMT"), '$lte': new Date("Tue, 31 Mar 2015 03:30:28 GMT") }, minParty: { '$lte': 2 }, maxParty: { '$gte': 2 }, _user: { '$exists': false } }) { sort: { dateTime: 1 }, fields: undefined }
```
I also noticed an error in the heroku log file as follows.
```
2015-03-30T07:34:04.880922+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-03-30T07:34:04.886665+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-03-30T07:34:05.471035+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-03-30T07:34:05.483563+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-03-30T07:34:05.483652+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-03-30T07:34:05.513354+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-03-30T07:34:05.513475+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-03-30T07:34:05.519524+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2015-03-30T07:34:05.471231+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-03-30T07:34:05.519689+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2015-03-30T07:34:05.955924+00:00 app[web.1]: MEAN.JS application started on port 13522
```
I'm currently using iojs 1.6.2 as my engine and after I looked up this issue some people suggested referring back to another stable version of Node. Sure enough, this did make the error go away however, I still ended up with the same outcome.

Not sure if this is related but I'll open an issue with it on io.

Let me know if there is anything else I can test out that might help. Thanks.

**Comment by vkarpov15** [comment]
That's a warning, not an error. Can you try running these same queries on a mongo shell locally and on compose? That'll see if mongoose is the culprit or your database setup

**Comment by christopherdro** [comment]
Here is query I used.
```
db.reservations.find({ dateTime: { '$gte': new Date("Tue, 31 Mar 2015 02:30:00 GMT"), '$lte': new Date("Tue, 31 Mar 2015 03:30:00 GMT") }, minParty: { '$lte': 2 }, maxParty: { '$gte': 2 }, _user: { '$exists': false } })
```

My local populates results however I get nothing on Heroku. Removing the $lte operator from the query populates results as predicted on Heroku.

I guess we can exclude this as a mongoose issue for now. I will continue testing and see if I come across anything different.

**Comment by vkarpov15** [comment]
Strange, but good that we've ruled it out as a mongoose issue. I'd recommend you investigate your heroku data and see if it's correct. Also, be careful with using new Date() like that, JS date formats are inconsistent across environments. Better to explicitly do new Date(2015, 2, 31) instead IMO

**Comment by christopherdro** [comment]
Ya I will continue looking into this.

I was actually using passing an ISO string inside the original query and got the new Date() format you referenced above inside of mongoose debug.

If I'm already using a date object why the need for having the create another new Date for the query?

**Comment by vkarpov15** [comment]
No reason as long as the date object is correct.

**Comment by christopherdro** [comment]
Ok cool. 
I just switched over to MongoLab and am still getting the same issue. Now I'm really stumped.

Closing this issue since it's not one related to mongoose. 

Thanks for your help.

**Comment by christopherdro** [comment]
Looks like I narrowed it down to an issue that happens when I specify a time along with a date. 
If you noticed I was trying to build a query with a date request plus 1 hour from that timestamp.

When I only check for date without specifying the hour or minute the results populate properly.

In my case I do need to somehow compare the times as well. 
A possible workaround could be just to populate 1 whole days reservation then have another function that filters how to display them based on the users request.

Still have no idea why this works on my local.

**Comment by ahmadshahrour951** [comment]
I know this issue has been written long ago, but I think I solved the issue and maybe someone else can reap the benefits.
I managed to fix it by changing my **mongoose schema model**. So for the object you're trying to query, ensure the data type in the model is **Date**. I had it set to **String** for some odd reason, I think what happens is mongoose filters any data that does not meet the requirement of the model, and in this case the **Type**. I thought it was just to ensure data integrity for _created_ or _updated_ documents, but apparently, it also applies to queries.
