### ISSUE TITLE
db.collection.ensureIndex doesn't get invoked on complex type

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#2814]
If I define my `location` field like the following way:

    var Schema = new mongoose.Schema({});
    Schema.add({
       location: {
           name: {type: String},
           loc: {type: [Number], index: '2d'}
        }
    });

I get the following correct message `Mongoose: db.collection.ensureIndex({ 'location.loc': '2d' }) { safe: undefined, background: true } ` in my console log.

But if I define the same field by the following way:

    var Schema = new mongoose.Schema({});
    Schema.add({
       location: {
           type: {
               name: {type: String},
               loc: {type: [Number], index: '2d'}
           }
        }
    });

I don't get the message about ensuring index on `location.loc` field and therefore it does not created if not exist

**Comment by skotchio** [comment]
@vkarpov15 can you reproduce this possible bug?

**Comment by vkarpov15** [comment]
Haven't had a chance to look at it yet. Will take a look later today.

**Comment by vkarpov15** [comment]
The issue is the `type` key. Mongoose interprets the schema as "location has type Mixed" and so misses the type path. Rename 'type' to 'kind' to avoid this issue.

**Comment by skotchio** [comment]
@vkarpov15 unfortunatelly when I tried the following:

    var Schema = new mongoose.Schema({});
    Schema.add({
      location: {
        kind: {
           name: {type: String},
           loc: {type: [Number], index: '2d'}
        }
      }
    });

I get the following error:

```
c:\Users\user\WebstormProjects\project\node_modules\mongoose\node_modules\mongodb\lib\utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: boolean is not a function
    at new SchemaArray (c:\Users\user\WebstormProjects\project\node_modules\mongoose\lib\schema\array.js:58:19)
    at Function.Schema.interpretAsType (c:\Users\user\WebstormProjects\project\node_modules\mongoose\lib\schema.js:427:12)
    at Schema.path (c:\Users\user\WebstormProjects\project\node_modules\mongoose\lib\schema.js:378:29)
    at Schema.add (c:\Users\user\WebstormProjects\project\node_modules\mongoose\lib\schema.js:288:12)
    at Schema.add (c:\Users\user\WebstormProjects\project\node_modules\mongoose\lib\schema.js:283:14)
    at Object.<anonymous> (c:\Users\user\WebstormProjects\project\app\models\AdStoryModel.js:101:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by vkarpov15** [comment]
Can you confirm which version of mongoose you are using?

**Comment by skotchio** [comment]
I'm using the latest 4.0.1

**Comment by alejonext** [comment]
+1

**Comment by vkarpov15** [comment]
Hmm I can't quite reproduce, the following standalone script executes properly for me at 4.0.1:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var assert = require('assert');
mongoose.connect('mongodb://localhost:27017/gh2814');

var Schema = new mongoose.Schema({});
Schema.add({
   location: {
       kind: {
           name: {type: String},
           loc: {type: [Number], index: '2d'}
       }
    }
});

var M = mongoose.model('gh2814', Schema);

M.create({ location: { kind: { name: 'test', loc: [1, 1] } } }, function(error, m) {
  assert.ifError(error);
  M.findOne({ _id: m._id }, function(error, m) {
    assert.ifError(error);
    console.log('done');
  });
});
```

Can you provide me a script that duplicates what you're seeing?

**Comment by vkarpov15** [comment]
Can't repro and no response. Reopen if still an issue.
