### ISSUE TITLE
"No listeners detected, throwing. Consider adding an error listener to your connection" Error

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#2815]
My `author` field defined with `required: true` validator as the following:

    var schema = new mongoose.Schema({});
    schema.add({
       author: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'User',
          required: true
       }
    });

    mongoose.model('Document', schema)

But I can't catch validation error when saving document:

    var model = new Document({});
    model.save(function (err) {
        if (err) {
            console.log(err); // newer invoked
        }
    });

Instead of catching error in callback above I get global exception: 

    No listeners detected, throwing. Consider adding an error listener to your connection.
    ValidationError: Path `author` is required.

**Comment by vkarpov15** [comment]
Hmm that's really strange, shouldn't be happening. I'll try to repro later.

**Comment by skotchio** [comment]
I've got this in mongoose@3.9.7. In mongoose@4.0.1 all works fine

**Comment by vkarpov15** [comment]
mongoose 3.9.7 was an unstable development release (between 3.6 and 4.0 mongoose used linux-style versioning rather than semver. Wasn't the best idea in hindsight.) - 3.9.7 deprecated in npm and gives you loud warnings that this release is unstable when you run it. Use the legacy 3.8.x release series or upgrade to 4.0.1.

**Comment by skotchio** [comment]
> Use the legacy 3.8.x release series
which is legacy 3.8.x release are?

> or upgrade to 4.0.1.
I can't upgrade to this release due https://github.com/Automattic/mongoose/issues/2809

**Comment by vkarpov15** [comment]
3.8.25 is latest, would recommend `"mongoose": "~3.8"` if you don't want to peg exact version

**Comment by skotchio** [comment]
Thanks for the explanation.
