### ISSUE TITLE
Mongoose object in post save is leaking values into later post save call.

### ISSUE THREAD

**Issue by askhogan** [Automattic/mongoose#2817]
I am having a strange issue with mongoose post save and async parallel, where inside one of the parallel calls methods, a value on the post save object leaks from earlier calls.  Simply put, I get the value of a different post save operation, sometimes minutes earlier.

Here is how it happens.  I have a few operations that I handle in an after save.  For code organization, I put each operation in a call static method, then wrap these methods in an async parallel tree, like below

 At some point out of convenience, I set a property on the dbObject.  I know I will not save it, and am using this object as a way to conveniently pass data on.  I end up with one area of the operation where the console.log of the data set is what it should be, and then in a later child call, the value changes to a value from an earlier operation.  This other operation occurred several minutes before.*

*this is in an environment where these post saves are firing 100's per minute.  

Why would the post save db object end up with a value from a completely unrelated post save?  Even if there were reference issues between the two parallel calls, that reference should be isolated to that individual post save.  How could values get leaked into the next post save call?

```
async.parallel([function (cb) {
            self.constructor.someFunctionOne(dbObject, cb);
        }, function (cb) {
            self.constructor.someFunctionTwo(dbObject, cb);
        }], function(err){ if(err) console.error(err) })

CallSchema.static('someFunctionOne', function (dbObject, callback) {

});

CallSchema.static('someFunctionTwo', function (dbObject, callback) {
     //do some work.
      var randomId = require('hat')(); 
      console.log(randomId);
      dbObject.meta.randomId = randomId;
      someLib.someOtherFunctionInAnotherLib(dbObject, callback)
      
});

//in the other lib
exports.someOtherFunctionInAnotherLib(dbObject, function(){
   //do some async work then inside a callback access the object
   console.log(dbObject.meta.randomId); /
/value from earlier call, several minutes before
})
```

**Comment by vkarpov15** [comment]
I'm having trouble understanding your pseudocode. Can you provide me an example that reproduces this? I have a couple ideas, but can't actually test them without something that reproduces the issue you're seeing.
