### ISSUE TITLE
Embedded document and CastError on 4.0.1

### ISSUE THREAD

**Issue by julien-maurel** [Automattic/mongoose#2819]
Hi,
I have 2 issues with Cast Errors on 4.0.1.
Take this simple below code (I use validate to test easier, but same issue with save) : 
```
var mongoose=require('mongoose');
var subSchema = new mongoose.Schema({
    subid:  {
	type:Number,
	required: true
    }
});
var schema = new mongoose.Schema({
    name: {
	type:Number,
	required: true
    },
    subs: [subSchema]
});
var model = mongoose.model('test', schema);
var doc=new model({
    name:'string',
    subs:[
	{
	    subid:'string2'
	},
	{
	    subid:'string3'
	}
    ]
});
doc.validate(function(err){
    console.log(err);
});
```

Output errors are : 
```
{ [ValidationError: test validation failed]
  message: 'test validation failed',
  name: 'ValidationError',
  errors: 
   { 'subs.-1.subid': 
      { [CastError: Cast to Number failed for value "string3" at path "subid"]
        message: 'Cast to Number failed for value "string3" at path "subid"',
        name: 'CastError',
        kind: 'Number',
        value: 'string3',
        path: 'subid' },
     name: 
      { [CastError: Cast to Number failed for value "string" at path "name"]
        message: 'Cast to Number failed for value "string" at path "name"',
        name: 'CastError',
        kind: 'Number',
        value: 'string',
        path: 'name' },
     'subs.0.subid': 
      { [ValidatorError: Path `subid` is required.]
        properties: [Object],
        message: 'Path `subid` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'subid',
        value: undefined },
     'subs.0.name': 
      { [CastError: Cast to Number failed for value "string" at path "name"]
        message: 'Cast to Number failed for value "string" at path "name"',
        name: 'CastError',
        kind: 'Number',
        value: 'string',
        path: 'name' },
     'subs.1.subid': 
      { [ValidatorError: Path `subid` is required.]
        properties: [Object],
        message: 'Path `subid` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'subid',
        value: undefined },
     'subs.1.name': 
      { [CastError: Cast to Number failed for value "string" at path "name"]
        message: 'Cast to Number failed for value "string" at path "name"',
        name: 'CastError',
        kind: 'Number',
        value: 'string',
        path: 'name' } } }
```

As you can see : 
- Cast error about `subid` field on sub docs appear as `subs.-1.subid` instead `subs.0.subid` and `subs.1.subid`
- As a consequence of previous issue, I have required errors on `subs.0.subid` and `subs.1.subid` (instead castError)
- And I don't know why but there is cast error on `subs.0.name` and `subs.1.name`, but these paths don't exist, `name` is a field in main document. I remark that this issue appear only if `subid` field in sub schema is required... strange

This issue is very problematic for me, can you help me?

**Comment by vkarpov15** [comment]
You found a couple bugs in 4.0.1's validation logic. Working on a fix now. Thanks for pointing this out.

**Comment by vkarpov15** [comment]
Put together a PR #2820 that should fix the two issues you pointed out. Works properly with the script you provided on my end, just want to make sure the Travis build checks out.

**Comment by julien-maurel** [comment]
Hi,
Thanks for reactivity.
It works on new documetn, but I have always an issue on update. If I edit an existing document to add a subdocument inside (I have 2 subdoc, I try to add a third), CastError still on `subs.-1.subid` and `subs.2.subid` have required error

**Comment by vkarpov15** [comment]
Thanks for the heads up, I'll reopen this and fix the update code

**Comment by vkarpov15** [comment]
Ok, new PR #2854 should fix that issue, thanks for pointing it out :)

**Comment by julien-maurel** [comment]
Ok, I'll try that tomorrow morning and I let you know if everything is good on my side. Thanks.

**Comment by julien-maurel** [comment]
Hi,
I run tests on my side, it seems good now.
Thanks for your help

**Comment by vkarpov15** [comment]
Thanks for pointing out these issues, I appreciate it. Please open up any other issues you may find.
