### ISSUE TITLE
CastError: Cast to ObjectId failed for value "" at path "_id"

### ISSUE THREAD

**Issue by adriatic** [Automattic/mongoose#2822]
This issue confused many, myself included. Here is my data model
```
[
  {
    "id": "038dfd06-0971-467d-80cb-2000cf3cf989",
    "name": "Cager Classic",
    "homeScreen": "**Welcome coaches, players, and parents!** \n\nThis site contains full schedule information for the tournament.",
    "rulesScreen": ""
  },
  {
    "id": "614b9998-e039-42da-8354-626b7b10a1cf",
    "name": "Holiday Hoops Challenge",
    "homeScreen": "**Welcome coaches, players, and parents!** \n\nThis site contains full schedule information for the tournament.",
    "rulesScreen": ""
  },
  {
    "id": "cabe8500-730c-4f99-b509-62c7a0401049",
    "name": "Thanksgiving Tip Off",
    "homeScreen": "**Welcome coaches, players, and parents!** \n\nThis site contains full schedule information for the tournament.",
    "rulesScreen": ""
  }
]
```
When trying to update the name of the first component of the above array using the following "rule"

    // Patch a league
    app.patch('/leagues/:id', function(req, res) {
        League.findOne({_id:req.params.id},function(err, league) {
            if(err)
                res.send(err);

            for(prop in req.body){
                league[prop]=req.body[prop];
            }

            // save the league
            league.save(function(err) {
                if (err)
                    res.send(err);

                res.json(league);
            });

        });
    });

Mongoose fails with 
```Cast to ObjectId failed for value "038dfd06-0971-467d-80cb-2000cf3cf989" at path "_id"```

This behaviour is likely caused by me using an object (GUID in this case) as the index key and there is clearly more about indexing (http://docs.mongodb.org/manual/core/indexes-introduction/) than I know at the moment, but getting a case error is a bit unfriendly, since it requires some digging (with WebStorm in my case) to understand that something went wrong.

Based on several discussions on stackoverflow, this (not using _id as index) that should be fixed by now. It seems that it is not, so can someone tell me how to bail out of this (a workaround), please?

**Comment by adriatic** [comment]
Please disregard the above issue as I know what my problem is, but do not know how to delete my initial report :-)

**Comment by vkarpov15** [comment]
Consider it disregarded :)

**Comment by Jindu0506** [comment]
Can you please help me here? I am facing the same issue. What is the solution for the issue?

**Comment by adriatic** [comment]
This is more than a three years old post - I have no recollection of ever writing it, much less how I solved it. Sorry!
