### ISSUE TITLE
Inheritance in array of subdocument: Problem with discriminatorKey

### ISSUE THREAD

**Issue by maelfosso** [Automattic/mongoose#2824]
Hi,

I have a problem.
I have a model `Survey` defined by

```
var SurveySchema = new Schema(
    {
        title : {
            type    : String,
            default : 'Title'
        },
        items   :   [ ItemSchema ]
    },
    {
        collection  : 'surveys'
    }
);
```

The `items` property is an array of `ItemSchema` defined by

```
var ItemSchema = new Schema({
        title   : String
    }, { discriminatorKey: '_itype' });
```

which has just been created because of inheritance. The real document which must be into the `items` property will come from `ItemRightSchema` or `ItemLeftSchema` defined by

```
var ItemLeftSchema = ItemSchema.extend(
    {
        description : String,
        items       : [ ItemSchema ]
    }
);
```

```
var ItemRightSchema = ItemSchema.extend(
    {
        help    : String,
        definition  : Schema.Types.Mixed
    },
    {
        discriminatorKey: '_qtype'
    }
);
It will also be the base for  inheritance..
```

The problem is when I create a new document from `ItemRightSchema`, first it just have the `title` property, nothing about `definition` and `help` properties and I don't see the `_itype` as if it doesn't work.

How to solve it please ?

**Comment by vkarpov15** [comment]
What library are you getting the `.extend()` function from?

**Comment by maelvis** [comment]
```.extend()``` come from [mongoose-schema-extend](https://github.com/briankircho/mongoose-schema-extend)

**Comment by kadosh1000** [comment]
@maelfosso I have a similliar issue.
I have as schema with subdocuments that inherits some other schema.
The only fields saved for the subdocuments are the parents fields.

Have you managed to resolve your problem? 
Anyone knows how to fix it?

**Comment by vkarpov15** [comment]
@kadosh1000 code samples please?
