### ISSUE TITLE
Documentation: Model.find arguments naming

### ISSUE THREAD

**Issue by albertorestifo** [Automattic/mongoose#2828]
In the [`Model.find`][1] documentation, the second accepted argument is called `fields`.

While reading it, it generated some confusion about if it is the same an MongoDB [`db.collection.find`][2] `projection` argument.

It is my understanding that the two are the same. If this is true, then the `projection` argument accepts more than what's documented in [`Query.select`][3].

I suggest changing the name of the argument to reflect the MongoDB documentation

[1]: http://mongoosejs.com/docs/api.html#model_Model.find
[2]: http://docs.mongodb.org/manual/reference/method/db.collection.find/#db.collection.find
[3]: http://mongoosejs.com/docs/api.html#query_Query-select

**Comment by vkarpov15** [comment]
I agree. The reason why fields is used is inertia, will change that to be more in line with the mongodb docs
