### ISSUE TITLE
Object has no method 'speak'

### ISSUE THREAD

**Issue by chaosink** [Automattic/mongoose#2829]
I tryed the `Getting Started` on the website however got the following:
```
fluffy.speak() // "Meow name is fluffy"
       ^
TypeError: Object { name: 'fluffy', _id: 551c1cdad21f502557fbbfd9 } has no method 'speak'
```

And I don't know what is meaning of the words:
```
methods must be added to the schema before compiling it with mongoose.model()
```

I am just a beginner of Javascipt...

Thank you!

**Comment by lbeschastny** [comment]
> And I don't know what is meaning of the words

It means that you should define all methods on your schema:

```js
var mongoose = require('mongoose');

var kittySchema = mongoose.Schema({
    name: String
})

kittySchema.methods.speak = function () {
  var greeting = this.name
    ? "Meow name is " + this.name
    : "I don't have a name"
  console.log(greeting);
}
```

before calling `mongoose.model` on it to create an actual model:

```js
var Kitten = mongoose.model('Kitten', kittySchema)
```

Then you'll be able to call this method on any instance of `Kitty` model:

```js
var fluffy = new Kitten({ name: 'fluffy' });
fluffy.speak() // "Meow name is fluffy"
```

**Comment by lbeschastny** [comment]
@chaosink It's best to address question like that to the vast community of `mongoose` users (i.e. people like me), rather than bothering `mongoose` developers with them.

Next time try asking your questions on [StackOverflow QA site](http://stackoverflow.com/questions/tagged/mongoose) or in [Gitter chat](https://gitter.im/Automattic/mongoose). You'll get your answer **much** faster that way.

**Comment by chaosink** [comment]
@lbeschastny Got it and thank you so much ! :sweat_smile:

**Comment by lbeschastny** [comment]
@chaosink If you don't have further questions, close the Issue, please.

Otherwise, `mongoose` guys will have to do it for you.

**Comment by zhishaofei3** [comment]
````javascript
kittySchema.methods.speak = function () {
  var greeting = this.name
    ? "Meow name is " + this.name
    : "I don't have a name"
  console.log(greeting)
}

var Kitten = mongoose.model('Kitten', kittySchema)
var fluffy = new Kitten({name: 'fluffy'})
````
