### ISSUE TITLE
Timeout to update document in mongodb using mongoose

### ISSUE THREAD

**Issue by richzw** [Automattic/mongoose#2830]
As we know, there is [expire data from collections by setting TTL](http://docs.mongodb.org/manual/tutorial/expire-data/) in `mongoDB`.

Now I want to the change one value of the document after a configured timeout. Given one document schema as following

    var Status = new Schema({
      hostId: {type: Number, required: true},
      hostAddress: {type: String},
      status: {type: Boolean, default: false},
      updateTime: {type: Date, default: Date.now}
    });

After receiving one special message, this document will be updated with new `updatetime` and the `status` will be `true`. If this special message can NOT be received after 2 minutes, the `status` should be set to `false`.

- Is there any method in mongoose to update the document after timeout?
- Can I get notification or callback when one document is deleted due to TTL?

**Comment by vkarpov15** [comment]
1) Nope but you can just use JavaScript settimeout or a library like kue if you need more durable scheduling.

2) unfortunately mongodb doesn't support this right now. I hope this feature will be added in a future release but as of today there's no good way to do this without constantly querying or watching the file system, neither of which is a good solution
