### ISSUE TITLE
4.0.1 Modifying documents in pre-save middleware can cause VersionError

### ISSUE THREAD

**Issue by dmfay** [Automattic/mongoose#2835]
We recently updated to 4.0.1 from 3.8. Our model maintains internal statistics, which we've implemented by way of a pre-save middleware that gathers information and updates the relevant fields before the document is saved. This was all well and good in 3.8, but after upgrading we've found that in cases where the document has not actually been modified before the middleware fires, the save() call raises a VersionError with the message 'No matching document found'. Modify a field before the save and everything's fine.

It's further complicated by the fact that we have only been able to reproduce it in some environments: we develop on a Vagrant Ubuntu VM and deploy to CentOS, both of which manifest the problem, but we can't reproduce it at all on OSX Yosemite.

Environment:
* Mongoose 4.0.1
* MongoDB 2.6.8
* nodejs 0.10.33
* Ubuntu 12.0.4 and CentOS 6.6 

Sample mocha test:

	'use strict';

	var mongoose = require('mongoose'),
		assert = require('chai').assert;

	var updater = function(thing, next) {
		thing.pages[0].statistics = {
			stuff: 1
		};
		next();
	};

	var schema = new mongoose.Schema({
		name: String,
		description: String,
		date: Date,
		pages: [{
			statistics: {
				stuff: Number
			}
		}]
	});

	schema.pre('save', function(next) {
		updater(this, next);
	});

	var Thing = mongoose.model('Thing', schema);

	describe('Thing', function() {
		before(function(done) {
			mongoose.connect('mongodb://localhost/unittest', done);
		});

		describe('the pre hook', function() {
			it('shouldnt blow up', function(done) {
				Thing.create({
						name: 'hi',
						pages: [{
							statistics: {
								stuff: 1
							}
						}]
					},
					function(err, thing) {
						if (err) {
							throw err;
						}

						thing.save(function(err) {
							console.log(err);

							assert.equal(err, null);
							
							done();
						});
					});
			});
		});
	});

**Comment by vkarpov15** [comment]
Thanks for the detailed report, I'll investigate tomorrow

**Comment by gregthegeek** [comment]
I'm still having this issue with mongoose 4.0.3. It does not occur using the same code in mongoose 3.8.29. I was logging some variables near the committed fix and found result.result.nModified and result.result.n to both be 0 when the error occurs, but there is a result.result.ok which is set to 0. I don't know what this last property is supposed to mean.

**Comment by vkarpov15** [comment]
@gregthegeek can you show me some code that reproduces your issue?

**Comment by gregthegeek** [comment]
We fixed it by using Model#update instead of Document#save.

**Comment by vkarpov15** [comment]
I'm still quite curious to see the code you used to trigger this issue though. Could you please share? Might be a bug in mongoose.
