### ISSUE TITLE
findOneAndUpdate: mistake in new param

### ISSUE THREAD

**Issue by lucastan** [Automattic/mongoose#2838]
mongoose 4.0 

http://mongoosejs.com/docs/api.html :   

findOneAndUpdate:
```
new: bool - false to return the modified document rather than the original. defaults to false (changed in 4.0)
```

http://docs.mongodb.org/manual/reference/command/findAndModify/ : 

```
new	Optional. When true, returns the modified document rather than the original. The findAndModify method ignores the new option for remove operations. The default is false.
```

**Comment by vkarpov15** [comment]
Thanks for pointing this out. I think the fix for this is already in master but if not I'll fix

**Comment by itsjustcon** [comment]
+1
I have to specify options: `{ new: true }` to get the desired "default" behavior currently.
