### ISSUE TITLE
Getter/setter: property name as argument

### ISSUE THREAD

**Issue by bathos** [Automattic/mongoose#2839]
At present, at least according to the docs, when you assign a getter or setter in a schema property definition, fn receives no arguments; all you have to work with is the document via 'this'. It would be nice to receive as an argument the name of the property, because then we could define generic, reusable get functions that can define behaviors for a repeatable type rather than a specific property that needs to be known beforehand.

Example:

    var momentDate = {
        type: Date,
        get: prop: function(prop) { return moment.utc(this[prop]); }
        set: function(val, prop) { this[prop] = moment.isMoment(val) ? val.toDate : val; },
        validate: function(val) { return moment.utc(val).isValid(); }
    };

    var schema = new moment.Schema({
        start: momentDate,
        end: momentDate
    });

**Comment by Prinzhorn** [comment]
Don't you get the value as parameter?

```js
var momentDate = {
	type: Date,
	get: function(value) {
		return moment.utc(value);
	},
	set: function(value) {
		return moment.isMoment(value) ? value.toDate() : value;
	}
};
```

**Comment by bathos** [comment]
Thanks, @Prinzhorn, you're correct. And in the links there I see that get *does* get a second argument already with the additional info I was seeking. Turns out I was looking at the wrong docs -- for some reason I kept checking the section on virtuals (which also have get/set) and never ended up in the right place till now.

**Comment by Prinzhorn** [comment]
You're welcome @bathos . Close this issue then so the maintainers won't waste their time looking at it as well ;)
