### ISSUE TITLE
ref field is overridden by empty value when used populate() with lean and stream() together

### ISSUE THREAD

**Issue by naoina** [Automattic/mongoose#2841]
Environments:
```
NodeJS: v0.10.26
MongoDB: 3.0.1
Mongoose: 4.0.1
```

In the following code, I expects the output `{_id: ..., sku: ...}`, but `{_id: ...}`.
However, when remove the `options: {lean: true}` from populate() or modify to `{options: {lean: false}}`, it is behavior of the expected.

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
var Sku = mongoose.model('Sku', {});
var Item = mongoose.model('Item', {
  sku: {ref: 'Sku', type: mongoose.Schema.Types.ObjectId}
});

(new Sku()).save(function(err, sku) {
  (new Item({sku: sku})).save(function() {
    var stream = Item.find().populate({
      path: 'sku',
      options: {lean: true}
    }).stream();
    stream.on('data', function(data) {
      console.log(data);
    });
    stream.on('end', function() {
      process.exit(0);
    });
  });
});
```

Is this behavior intended?

**Comment by vkarpov15** [comment]
Nope, thanks for the detailed report, I'll see if I can reproduce this

**Comment by vkarpov15** [comment]
Yeah that's not the preferred way to do what you're trying to do, providing the "lean: true" to populate is a bit of a dark corner. I'd recommend you use `.lean()` instead:

```javascript
    (new Sku()).save(function(err, sku) {
      (new Item({sku: sku})).save(function() {
        var stream = Item.find().lean().populate({
          path: 'sku',
        }).stream();
        stream.on('data', function(data) {
          console.log(data);
        });
        stream.on('end', function() {
          process.exit(0);
        });
      });
    });
```

Are you explicitly trying to only use lean for the populated doc? Or are you looking to enable lean for every query, including the initial find()?

**Comment by naoina** [comment]
The former. I want to use `Item` doc as mongoose.Document, but I want to use populated `Sku` doc as plain object.
It's for performance.

**Comment by vkarpov15** [comment]
Ok, thanks for the info, I think that should be possible to fix but I'm not sure off the top of my head.
