### ISSUE TITLE
Save don't work with pushin element's to array. 

### ISSUE THREAD

**Issue by mgolawski** [Automattic/mongoose#2842]
Hi i have strange issue with mongoose.
Group.findById(req.params.group_id, function(err, group){
		User.findOne(req.body, function(err, user){
			group.users.push(user);
			user.groups.push(group);
			group.save();
			user.save();
			res.json({group: group, user: user});
			return true;	
		});
	});

I try to create double way relation between user and group. User is properly pushed to the group.users array and saved perfectly. The issue appear when i try to save group in user.groups array. There is no action on mongo side until i will try to run this action again. Old element now is saved properly, and new one is still don't saved. On express side everything seems to be fine, and objects that are returned to the front end are also valid.

Here you have visualization of my problem
Group      User           group.users in database                    user.groups in database
group1     user1                [user1]                                                                  []
group2     user2           [user1, user2]                                                       [group1]
group3     user3        [user1, user2, user3]                                        [group1, group2]

I hope you understand where is the key of the issue.

Do you have any advice of how to fix that problem?

**Comment by vkarpov15** [comment]
Can you please clarify? I don't understand what you mean by "no action on mongo side until i will try to run this action again"
