### ISSUE TITLE
model().create validation drop down the entire application

### ISSUE THREAD

**Issue by 3lvcz** [Automattic/mongoose#2843]
for example:

```javascript
var userSchema = mongoose.Schema({
    name: {
        type: String,
        required: true,
        maxlength: 50
    }
    email: String
});
var User = mongoose.model('User', userSchema);

// user to create
var obj = { email: 'some_email' };

mongoose.model('User').create(obj/*, callback */);
```

when mongoose validates 'obj', it's trying to read
'obj.name.length', but 'obj.name' is not defined,
so mongoose throws a not handled error.

it happens only if that field ('name' is this case)
marked as required.

**Comment by vkarpov15** [comment]
Which version of mongoose?

**Comment by 3lvcz** [comment]
4.0.1

**Comment by 3lvcz** [comment]
I was wrong with example, sorry. I missed one thing: to reproduce this bug, it's important, to place 'maxlength' condition BEFORE 'required' in schema definition. It matters. Otherwise, it would be a usual Error-first-argument in callback... so, to meet that issue, the schema should be look like this:
```javascript
var userSchema = mongoose.Schema({
    name: {
        type: String,
        maxlength: 50,
        required: true
    },
    email: String
});
```

**Comment by vkarpov15** [comment]
Thanks for pointing this out, just pushed a solution.
