### ISSUE TITLE
TTL calls remove but not the pre/post hook on model

### ISSUE THREAD

**Issue by TrangNguyen** [Automattic/mongoose#2855]
Hi,

I have 2 Schema, A and B that reference each other, one of them A has TTL expireAt property which can be extended by a user's action. I would like to modify/delete the referenced docs depending on the TTL set on A so I tried to add `pre('remove')` hook onto A which search all referenced B to take further action. It doesn't work. The `pre/post ('remove')` only get called via the custom controller but not when TTL itself internally runs. Any idea, hint would be greatly appreciated.
I'm using `express 4.11.1` and `mongoose 3.8.21`, the database is on heroku with mongolab running `mongodb 2.6.9`, test is done via Postman. I would like to use B as ref instead of subdocs, if possible.
This is how I declared my Schema A
````
var ASchema = new Schema({
  shortId: {
    type: String
  },

  expireAt: {
    type: Date
  },
  children: [{
    type: Schema.Types.ObjectId,
    ref: 'B'
  }]
});
// set TTL on A to expire in 1 minute for testing, works on A. :)
ASchema.pre('save', function(next) {
  this.expireAt = new Date(new Date().valueOf() + 60000);
  next();
});

 // It should remove ref children if A is removed. Only works via controller, not via TTL as intended. :(
ASchema.pre('remove', function(next) {
  console.log("Removing A");
  this.model('B').find({_board: this.shortId}).remove().exec();
  next();
});

// Expire at the time indicated by the expireAt field
ASchema.index({ expireAt: 1 }, { expireAfterSeconds : 0 });

module.exports = mongoose.model('A', ASchema);
```
And for Schema B

```
...
var BSchema   = new Schema({
	...
	_board: {
	  type: String,
	  ref: 'A'
	}
});
...
module.exports = mongoose.model('B', BSchema);
```
The hook `pre('remove') ` is only called on the controller method below, all referenced B docs will also be removed. But when expireAt runs by itself, the remove hook is never executed.
````
app.delete('/api/boards/:boardId', function (req, res) {
    A.findOneAndRemove({boardId: req.params.boardId},  function(err, doc) {
      doc.remove();
```

**Comment by vkarpov15** [comment]
By design - mongoose has no way of knowing when a document expires on the server-side, and the document might not exist in the server's memory at the time it expires.
