### ISSUE TITLE
subdocument has been removed

### ISSUE THREAD

**Issue by maelvis** [Automattic/mongoose#2857]
Hi everybody,

Please how to know whether a subdocument has been removed ?
I use this method ```this.items.id(item._id).remove();```
but the return is always ```undefined```

.

**Comment by vkarpov15** [comment]
What is the `id()` function in your example?

**Comment by maelvis** [comment]
I don't have a ``` id() ``` function. 
See here http://mongoosejs.com/docs/subdocs.html at ```Removing docs``` section

**Comment by vkarpov15** [comment]
If you call `.remove()`, the subdoc will *always* be removed. Same reason why `Array.prototype.splice()` doesn't return a bool. `this.items.id(item._id)` returns null if it can't find a subdoc with id `item._id`.

**Comment by maelvis** [comment]
Thanks....
