### ISSUE TITLE
The package mongoose does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by shikhar-credihealth** [Automattic/mongoose#2858]
I have been getting this error since this morning after I tried to "sudo npm install --save ".

It throws down the following error for me: 

npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer node-restful@0.1.18 wants mongoose@~3

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "mongoose"
npm ERR! cwd /home/shikhar/Untitled Folder/mean example-2/server
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/shikhar/Untitled Folder/mean example-2/server/npm-debug.log
npm ERR! not ok code 0

**Comment by vkarpov15** [comment]
mongoose just released v4, so if you `npm install mongoose --save` you'll get v4. Looks like node-restful wants mongoose 3.x, which is perfectly ok, just make sure you do `npm install mongoose@~3.8 --save`
