### ISSUE TITLE
Debug true shows 'err' for everything?

### ISSUE THREAD

**Issue by btmdave** [Automattic/mongoose#2859]
I have the debug log enabled but it's displaying everything as though it's an error, even for queries I know are not.

Any idea why this would be?   

For example:

`api (err): Mongoose: users.find({}) { fields: undefined, limit: 1 } `

This executed fine however.

**Comment by vkarpov15** [comment]
Hmm that's strange, the following script:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh2859');

var schema = new mongoose.Schema({ test: String });
var m = mongoose.model('gh2859', schema);

m.findOne({
  test: 'abcd'
}, function() {});
```

outputs

```
$ node gh-2859.js 
Mongoose: gh2859.findOne({ test: 'abcd' }) { fields: undefined }  
```

As expected for me. How are you enabling the debug error log?

**Comment by btmdave** [comment]
Hm.  Yeah, actually it works fine locally on mongo v2.6.7 but another server has v2.4.9, maybe that's the culprit.

**Comment by vkarpov15** [comment]
Doubtful, debug is entirely at the NodeJS layer. I'm not an expert on how debug works but perhaps your DEBUG environment variable is set to something weird?

**Comment by btmdave** [comment]
Hm, no DEBUG env set.  Node version is 0.10.35 locally (mac) vs 0.10.23 (ubuntu)... maybe that's it.

**Comment by waelrammo** [comment]
I noticed they all get written to stderr once I started piping the output. Still haven't figured it out
