### ISSUE TITLE
Passing unpopulated document ref to another function by reference breaks object prototype chain

### ISSUE THREAD

**Issue by JasonCust** [Automattic/mongoose#2860]
I'm not sure this is a problem that should be solved but submitting it in case someone else stumbles across this issue. Unlike subdocument refs that each have their own document object, a path that is a reference to another document does not unless it's populated. I guess the question is: should a reference be its own document object similar to populated references or subdocuments?

Using 4.0.1
```
var schema1 = mongoose.Schema({
  title: String,
  refDoc: {type: mongoose.Types.ObjectId, ref: 'Model2'}
});
var schema2 = mongoose.Schema({
  title: String
});

var Model1 = mongoose.Model('Model1', schema1);
var Model2 = mongoose.Model('Model2', schema2);

// assuming populated with references

Model1.findById('some_id', function(err, doc) {
   console.log(doc.refDoc.id, doc.refDoc._id);
   // outputs: '5527eaf8bd2ec6dbbbf2dad4' 5527eaf8bd2ec6dbbbf2dad4
   someFunction(doc.refDoc);
})

function someFunction(doc) {
  console.log(doc.id, doc._id);
  // outputs: 'U\'êæ½.ÆÛ»òÚ¾' undefined
}
```
If the document ref is populated it works as expected:
```
Model1.findById('some_id').populate('refDoc').exec(function(err, doc) {
   console.log(doc.refDoc.id, doc.refDoc._id);
   // outputs: '5527eaf8bd2ec6dbbbf2dad4' 5527eaf8bd2ec6dbbbf2dad4
   someFunction(doc.refDoc);
})

function someFunction(doc) {
  console.log(doc.id, doc._id);
   // outputs: '5527eaf8bd2ec6dbbbf2dad4' 5527eaf8bd2ec6dbbbf2dad4
}
```

**Comment by vkarpov15** [comment]
That's a pretty loud scary title. I don't really see what the issue is though - looks like the `id` virtual is minorly buggy for ref paths that aren't populated, but I don't really see that as a big deal. A ref should definitely not be a separate document unless its populated.

**Comment by JasonCust** [comment]
Agreed but it was the most descriptive title I could think of. :-)

The main use case would be mitigating the need to use populate (which incurs a secondary query of the database) to preserve the functionality that a mongoose document wrapper provides. Maybe there is a way to do this already externally? Psuedo-code: `mongoose.Document(doc.refDoc)`

**Comment by vkarpov15** [comment]
Hmmm so what would you be trying to do? Do you already have the doc that populate() would pull out of the database and want to use it instead?

**Comment by JasonCust** [comment]
For this use case I have an existing function (ex: `needDoc`) that expects a mongoose document as an argument. Among other internal uses, this function uses the document as an argument for another mongoose query (which mongoose automatically accesses the ID via the `id` virtual).

`function needDoc(doc) { ...; Model({someRef: doc, ...}); ...}`

Another function (ex: `getParentDoc`) can only identify the parent document from a query but is used to pass the child ref value to `needDoc`.

`function getParentDoc(query) { mongoose.Find(query, function(err, parent) { ...; needDoc(parent.refDoc, ...); ...}}`

`needDoc` is currently used by other functions but with enough refactoring/type-checks I could work around this issue. However the reason I submitted the issue is because the expected outcome was not met.
 - The unpopulated ref value still looks like a document but as noted it's broken.
 - If you populate a ref value it is a document.
 
While I figured this out quickly I can imagine a user who might be either new to JS or mongoose struggling with this issue. It looks like a duck but doesn't exactly quack like a duck till you make it a duck.

**Comment by vkarpov15** [comment]
Why not just check if `_id` exists or not? I'm not entirely sure why `id` is there, but `refDoc` definitely doesn't look like a document if it's not populated for any reasonable definition of "look."

**Comment by JasonCust** [comment]
I suppose as with most things regarding appearances it's subjective. When I initially was stepping through the code I saw the `refDoc` resolved to a value but also had an `id` method and assumed it was treated as a document. However after a more thorough inspection for debugging I saw the `refDoc` actually doesn't have an `_id` property and is not an instance of mongoose.Document:

    refDoc --> 552be7072358be680e88db71
    refDoc.id --> 'U+ç\u0007#X¾h\u000eÛq'
    refDoc._id --> undefined
    refDoc instanceof mongoose.Document --> false

So I guess my confusion was seeing the `refDoc` would resolve to a value when debugging but internally Mongoose attempts to use the `id` method if a value has one (I haven't tracked down where this happens yet). I can imagine other people tripping over this as well: you run one query and see that a `refDoc` resolves to a valid value and then pass that as an argument/value to another query which unfortunately results in an invalid value due to the `id` issue.

**Comment by vkarpov15** [comment]
Hmm ok I see, so the problem is that `id` is there. I'll investigate and see why this is the case.

**Comment by vkarpov15** [comment]
So I dug into this a little more and it turns out that when you do `doc.refDoc`, since you get back a bson ObjectId, [it has an `id` property that contains the raw 12 byte objectid](https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js). For instance, if you do `doc.refDoc.toHexString()`, you'll get back the hex string (e.g. 552be7072358be680e88db71). This is not something that mongoose is going to change anytime soon - tweaking the mongodb ObjectId type is outside the scope of the project. You can pretty easily check if the field is populated or not using the [`populated()` function on documents](http://mongoosejs.com/docs/api.html#document_Document-populated)
