### ISSUE TITLE
Connection events are not fired properly in 4.0.1

### ISSUE THREAD

**Issue by pickels** [Automattic/mongoose#2865]
I recently updated from 3.8.x to 4.0.1
Everything went well, except that some connection events are fired just one time, or aren't fired at all. I'm using a connection pool of 5, and all the options defaulted (keepAlive, auto_reconnect, etc). I'm using Winston as my logger library, with console and file transport.
This is an actual test code:

```
mongoose.connection.on('connecting', function () {
  logger.info('MongoDB: Trying: ' + dbURI); }); 
mongoose.connection.on('connected', function () {
  logger.info('MongoDB: Successfully connected to: ' + dbURI); }); 
mongoose.connection.on('error',function (err) { 
  logger.error('MongoDB: ERROR connecting to: ' + dbURI + ' - ' + err); }); 
mongoose.connection.on('close',function (err) { 
  logger.error('MongoDB: Connection Closed'); }); 
mongoose.connection.on('reconnected', function () { 
  logger.warn('MongoDB: Database link was reconnected'); });
mongoose.connection.on('disconnected', function () { 
  logger.error('MongoDB: The connection was ended on: ' + dbURI ); });
// Connect to database
mongoose.connect(dbURI, mongoOptions);
```
Upon start, the console shows:
```
info: MongoDB: Trying: mongodb://localhost/Alamo
info: MongoDB: Successfully connected to: mongodb://localhost/Alamo
```
That is "connecting" and "connected".
Now, if I stop the MongoDB service, the console shows:
```
error: MongoDB: The connection was ended on: mongodb://localhost/Alamo
error: MongoDB: Connection Closed
```
That is "disconnected" and "close".
If i start the Mongo service back:
```
info: MongoDB: Successfully connected to: mongodb://localhost/Alamo
warn: MongoDB: Database link was reconnected
```
That is "connected" and "reconnected".
But now, if i stop the Mongo service again, no message appears on the console. If I start the service one more time, I just get the "reconnected" event, and that's all. That is the only event i will see from this point on.

It's clear that the reconnection feature is working, but not having all events fired is cripping the log file, and an analysis of a possible problem will be harder.

vkarpov15 pointed me in the chat that its probably related with:
https://github.com/mongodb/node-mongodb-native/pull/1265

May be it's an issue related with the MongoDB 2.x driver.

**Comment by julien-maurel** [comment]
Hi,
@vkrpov15, I use master branch of mongoose (so mongodb 2.0.27), and I have same type of issue.
I set a log on all event type : 
```
         var events = ['connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close', 'reconnected', 'error'];
         events.forEach(function (event) {
           connection.on(event, function () {
             console.log(event);
           });
         });
```

After, I do (on a non replicaset) :
- run script : connected & open events
- stop mongod : disconnected & close events
- wait first reconnection try : connected & reconnected events
- wait second reconnection try : reconnected event
- restart mongod
- wait third reconnection retry : reconnected event
- stop mongod : nothing
- wait first reconnection : reconnected event
- wait second reconnection : nothing
.... no new events, never (even if I restart, restop... mongod)

As you can see, issues are : 
- no more event when mongod stop/start more than one time
- impossible to know when connection is really back

If I do same on a replicaset (by stopping/starting all servers each time), I receive connected and open events when I run script, I receive reconnected event when I restart servers (after I stopped it during 30s), but nothing else (no close, no error, no disconnected :/).

Thansk for your feedback.

**Comment by vkarpov15** [comment]
You're right, it's an issue with the underlying driver. Pretty much the same issue as mongodb/node-mongodb-native#1265 - the driver's only emitting the close event once. I'm personally not sure what the reasoning for that is but we'll figure it out. Thanks for reporting.

**Comment by softomatix** [comment]
+1
