### ISSUE TITLE
Different $slice behaviour between server and local

### ISSUE THREAD

**Issue by jesusbotella** [Automattic/mongoose#2866]
Hi!

I have been experiencing such a weird issue with mongoose. For the query I was testing, I used the find command combined with $slice and sort in Mongo, like that:

> Item.find({}, { array: { $slice: 1 } }, { sort: {"checked": 1} }, sendToQueue);

When I run the script in my local machine, the array property only shows one item at a time. Meanwhile, when I uploaded the same script and tested in production, the array was showing ALL the items inside itself, so the $slice was doing nothing.

I checked the mongoose versions to know if there was any difference, but they were equal. I'm using mongoose 3.8.24.

Anyone knows what is going on here?

**Comment by vkarpov15** [comment]
Hmm can you enable debug with `require('mongoose').set('debug', true);` and show me the actual query that's getting sent to mongodb?

**Comment by jesusbotella** [comment]
I'm so sorry :( It was my fault, I wasn't testing the same version. There wasn't some important things in the faulty version, so the query was returning all the raw items.
