### ISSUE TITLE
Model.update callback params 

### ISSUE THREAD

**Issue by pnicorelli** [Automattic/mongoose#2872]
Based on docs in http://mongoosejs.com/docs/api.html#model_Model.update
the callback should receive `numberAffected` as integer but I receive an
object like `{ ok: 1, n: 2 }` where n is my aspected numberAffected.

```
- "mongoose": "^4.0.1"
- mongodb.version: 2.4.9
- node -v: v0.10.38
- code:
  User.update(
        { '_id': { $in: req.params.users} },
        { $addToSet: { setsLF: req.params.setLabel }},
        { multi: true },
        function(err, numAffected, rawResponse){
          res.send(200, { "message": numAffected+" user(s) affected", "num": numAffected } );
          return done();
        }
  );
```
test with chai.should:
      `res.body.num.should.equal(2);`
Fail with:
    `Uncaught AssertionError: expected { ok: 1, n: 2 } to equal 2`

with mongoose 3.8.* test run as expected.

**Comment by vkarpov15** [comment]
Docs aren't quite right, that's expected behavior from [the 4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes). Thanks for pointing this out.

**Comment by pnicorelli** [comment]
didn't notice the docs! thanks

**Comment by fiznool** [comment]
Docs updated in https://github.com/Automattic/mongoose/pull/2827
