### ISSUE TITLE
Field is undefined when using + with select

### ISSUE THREAD

**Issue by JonWatkins** [Automattic/mongoose#2876]
I have a model plugin that handles our authentication for users. Inside the plugin I have added some additional fields, the one causing the issue is the password.

```
schema.add({
 password: { type: String, select: false }
});
```

Then in my passport library I call findOne but request that the password is returned. In the callback method for this call I have tried to console log both the document and the password, The document is always there, but password is always undefined. This had been working until a few hours ago

```
User.findOne({ email: emailAddr }, '+password', function (err, doc) {
   console.log(doc.password, doc);
});
```

This has been working for quite some time and just suddenly stopped working after an npm install, I did check and the version installed matches the package.json

Tried deleting the node_modules folder and running npm cache clear and npm update, Still no luck. Has anyone else had the same issue?

Using mongoose 3.8.26 on ubuntu 14, using node version 0.10.25.

**Comment by JonWatkins** [comment]
This does not seem to happen for all documents. The user I was having the issue with getting was over a year old, the code does however seem to function correctly with a newly created document. Not sure if this can cause issues.

I can repeat it with another user created at a similar time to the problematic doc.

**Comment by vkarpov15** [comment]
That's strange. What does the full document look like?

**Comment by JonWatkins** [comment]
Sorry haven't had a chance to get back to you yet, the issue was caused by a silly regexp query that went unnoticed, and an incorrect document was returned, the new ones worked as they were always returned first.
