### ISSUE TITLE
How to call db.eval() via mongoose?

### ISSUE THREAD

**Issue by liangxinhui** [Automattic/mongoose#2877]
I have some functions saved in MongoDB Server.
Is there some methods to call  them, like the native call db.eval().

May be like this (I Tried， not work)：

```javascript
mongoose.connection.db.eval("Foo('Arg1','Arg2')", function(err, retVal) {
	// the eval result
});
```
or this (not work either):
```javascript
mongoose.connection.db.eval("Foo", ['Arg1','Arg2'], function(err, retVal) {
	// the eval result
});
```

**Comment by vkarpov15** [comment]
The first approach looks like it should be correct. Do you get an error, an incorrect result, or how exactly does it "not work"?

**Comment by liangxinhui** [comment]
The `callback` function was never called.
And the return of `mongoose.connection.db.eval` was `undefine`.

**Comment by vkarpov15** [comment]
So `mongoose.connection.db` is the raw mongodb driver db object. The below code executes successfully

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2877');
mongoose.connection.on('connected', function() {
  mongoose.connection.db.eval('return 5;', function(err, result) {
    console.log('err: ' + err);
    process.exit(0);
  });
});
```

The following code hangs because the driver is not connected

```
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2877');

mongoose.connection.db.eval('return 5;', function(err, result) {
  console.log('err: ' + err);
  process.exit(0);
});
```

Because mongoose provides no buffering on top of `mongoose.connection.db`.

**Comment by Premjeet-Singh** [comment]
@liangxinhui :  Your first is correct. This function works correctly. I tried.

mongoose.connection.db.eval("printFunction('hello')", function (e, result) {     // works correctly
            if (e)  res.send(e);
            console.log(result);
            res.send(result);
});
