### ISSUE TITLE
can not find by BinData type id.

### ISSUE THREAD

**Issue by bolerovt** [Automattic/mongoose#2878]
Since the mongoose doesn't support BinData as a Schema type, while I somehow need to set a UUID as the _id for my mongoDB, I am trying to make a workaround by combining mongoose with mongodb native driver.

During my test, the native driver works fine with the BinData typed UUID. But I can not find the right result by using mongoose Model.findOne function.

As long as BinData type of id, instead of String, will improve the efficiency of the database, according to mongodb doc (http://docs.mongodb.org/manual/core/document/#the-id-field), will mongoose in the future support BinData format in its Schema?

```
  , mongoose = require('mongoose')
  , Schema   = mongoose.Schema
  , uuid     = require('node-uuid')

  , mongodb = require('mongodb')
  , Binary  = require('mongodb').Binary
  ;

mongoose.connect('mongodb://127.0.0.1/test');

var TestSchema = new Schema({
  _id: Buffer,
  a: String,
  b: Number
});
var MongoClient = require('mongodb').MongoClient
  , assert = require('assert');
```

Native driver works fine and can get the right result

```
MongoClient.connect('mongodb://127.0.0.1/test', function(err, db) {
  assert.equal(null, err);
  console.log("Connected correctly to server");

  findDocuments(db, function() {
    db.close();
  });
});


var findDocuments = function(db, callback) {
  // Get the documents collection
  var testmodels = db.collection('testmodels');
  // Find some documents

  var UUID = new Binary(new Buffer("17uRpR+9SRO2z9hvggMzHg==", 'base64'), 3);

  testmodels.find({'_id' : UUID}).toArray(function(err, docs) {
    assert.equal(err, null);
    //assert.equal(1, docs.length);
    console.log("Found the following records");
    console.dir(docs);
    callback(docs);
  });
};
```

Got nothing from mongoose API

```
var UUID = new Binary(new Buffer("17uRpR+9SRO2z9hvggMzHg==", 'base64'), 3);
var buffer = new Buffer("17uRpR+9SRO2z9hvggMzHg==", 'base64');

TestModel.findOne({'_id' : UUID}, function(err, item) {
  console.log(item);
});
```

**Comment by juanpin** [comment]
+1

**Comment by vkarpov15** [comment]
With mongoose, you need to use `Buffer` as the type and create an actual NodeJS buffer, **not** a mongodb driver Binary. See [types docs](http://mongoosejs.com/docs/schematypes.html). Mongoose converts buffers to bson type BinData.

**Comment by sibelius** [comment]
is there any example of searching by an uuid v4?
