### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by bhekman** [Automattic/mongoose#2881]
I noticed an illegal line in the api docs.
url: http://mongoosejs.com/docs/api.html
call: SchemaType#unique(bool)
line: var s = new Schema({ name: { type: String, unique: true })

**Comment by vkarpov15** [comment]
What specifically is illegal?

**Comment by rhmeeuwisse** [comment]
The ending curly brace and a semi-colon are missing. See PR https://github.com/Automattic/mongoose/pull/3126

**Comment by dhurlburtusa** [comment]
Can a committer close this? It was fixed in PR #3126.
