### ISSUE TITLE
Disappearing validation errors

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2886]
As I have been migrating code from mongoose 3.8 to 4.0, I have experienced this breaking change:

```js
mySchema.pre('validate', function(next) {

    if(!this.isNew) {
        if (this.isModified('updated')) {
            this.invalidate('updated', '`{PATH}` is invalid: Cannot change the modification date.', that.updated);
        }

        // Assuming updated has been modified, this.errors.updated is a ValidationError at this stage

        this.updated = new Date();

        // And at this stage this.errors.updated is undefined in version 4.0.1 (not in 3.8.26) 
    }

});
```

**Comment by vkarpov15** [comment]
Thanks, something else I need to make note of in the 4.0 release notes. Check the notes on #2775 in the [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) - when you set `updated`, mongoose will check for cast errors, and if there aren't any, mark updated as valid. It will also clear out any calls to `invalidate()`. If you need to do a check like this, I'd recommend adding multiple pre validate hooks and add the hook that checks for modifications last.

**Comment by vkarpov15** [comment]
You could also add a custom setter for `updated` that throws an error, e.g.

```javascript
mySchema.set('updated', function() {
  throw new Error('Not allowed to change modification time!');
});
```

This will ensure that any doc will be invalid after modification time has been modified.
