### ISSUE TITLE
DOCUMENTATION: http://mongoosejs.com/docs/api.html#model_Model.update

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2887]
The documentation at http://mongoosejs.com/docs/api.html#model_Model.update states:
```numberAffected is the count of updated documents Mongo reported```

After upgrading from mongoose 3.8.26 to 4.0.1, my code is broken because ```numberAffected``` is actually an object with 3 numeric properties: ```n```, ```nModified``` and ```ok```.

Which is the number of updated documents? Thx.

**Comment by vkarpov15** [comment]
Fixed by #2827. Recommend using `result.n` instead.
