### ISSUE TITLE
SubDocument arrays are instanceof Array in mongoose 4.0.1

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2888]
I am still reporting breaking changes while upgrading from mongoose 3.8.26 to 4.0.1.

Let's consider the following schema:

```js
var companySchema = new mongoose.Schema({
    ...
    employees: { type: [employeeSchema], default: [], select: false }
});
mongoose.model('Company', companySchema);
```

And the following request:

```js
Company.findOne({ _id: id }, '+employees', function(error, company) {
  ...
});
```

In mongoose 3.8.26, we had:
```
expect(company).to.have.property('employees').that.is.an.instanceof(mongoose.Types.DocumentArray)
```

In mongoose 4.0.1, this is false and the following is true:
```
expect(company).to.have.property('employees').that.is.an.instanceof(Array)
```

Not sure it is intended considering https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes

**Comment by vkarpov15** [comment]
Actually I forgot to make a note of this in the 4.0 release notes. This was an unfortunate necessity to get #2254 (isomorphic schema validation) to work in non-ES5 browsers without a shim. Use the `company.employees.isMongooseDocumentArray` property.
