### ISSUE TITLE
Unable to validate nested fields of mixed type on findOneAndUpdate

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#2889]
I have the following schema with comments field:

    var docSchema = new mongoose.Schema({}, {strict: "throw", collection: "documents"});

    docSchema.add({
      comments: {
        type: [{
          author: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
          },
          comment": {
            type: String,
            trim: true,
            required: [true, 'Comment is required]
          }
        }]
      }
    });

I have `required` options on `comment` field but unfortunately it does't work. When I add new comment like the following:

    Document.findOneAndUpdate({_id: ObjectId()}, {$push:  {comments: {author: ObjectId()}}}, {"new": true, runValidators: true}, function (err) {
      console.log(err); // null    
    });

As you can see I don't provide `comment` field which is required, so I had to have err object.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, I'll investigate.

**Comment by skotchio** [comment]
@vkarpov15 please note I use `$push`. Should this works?

**Comment by vkarpov15** [comment]
Looking at this more carefully, the issue is that you're using `$push`. `runValidators` **only** checks `$set` and `$unset` operations right now. We could support `$push` in theory but that's a bit trickier. Unfortunately I think the only place this is really documented is [in the introductory blog post on the mongodb blog](http://www.mongodb.com/blog/post/introducing-version-40-mongoose-nodejs-odm) so I just need to add some documentation for that.

**Comment by skotchio** [comment]
@vkarpov15 `$set` is the same logic as `$push` and I don't see problem to implement last. We need to just chech that all pushed vales pass validation rules.

**Comment by vkarpov15** [comment]
It should be do-able, I'll put that up for 4.1. Not going to be looking at that for another couple weeks though, so PRs are welcome :)

**Comment by skotchio** [comment]
@vkarpov15 so you don't plan to support `$push` validation at all?

**Comment by vkarpov15** [comment]
Opened up a separate issue #2933 . I used this issue for tracking having some documentation for update validators :) Supporting $push should be fairly easy, but I haven't quite had time to tackle it yet because of the more pressing work of bug fixes for 4.0.x.
