### ISSUE TITLE
Polygon validation error?

### ISSUE THREAD

**Issue by malcommac** [Automattic/mongoose#2890]
I would to store a polygon inside a MongoDB document using mongoose.
This is my schema:

    var alarmSchema = new mongoose.Schema({
    	// ... some other fields ....
    	loc :   {
    		"type": {
    			"type": String,
    			"enum": [
    				"Point",
    				"MultiPoint",
    				"LineString",
    				"MultiLineString",
    				"Polygon",
    				"MultiPolygon"
    			]
    		},
    		"coordinates": [[Number]]
    	}
    });

So I've tried to add a new object of this type using:

    var Alarm = db.model('Alarm', alarmSchema);
    var alarmObj = new Alarm();
    var polygonArray = [[10.371094,42.391009],[14.238281,44.024422],[16.259766,42.130821]];
    alarmObj.loc = {type : "Polygon" , coordinates : polygonArray};
    return alarmObj;

When i try to save this I get this error:

> ValidationError: CastError: Cast to Array failed for value ....(the
> array passed)...

Any idea?

After that I would to find a list of these alarmObj which contains a passed point.
I think this is the right query:

    var geojsonPoint = { type: 'Point', coordinates: [44.95899,8.911711] }
    AlarmModel.find({loc: { $geoIntersects: { $geometry: geojsonPoint}}},function(err,list) {});

Is it okay?

**Comment by vkarpov15** [comment]
Mongoose doesn't currently support multidimensional arrays out of the box (see #1663 et all). You probably want to declare coordinates like this: `"coordinates": Array` and then use a custom validator if you want to validate that coordinates is an array of arrays of numbers.
