### ISSUE TITLE
MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index

### ISSUE THREAD

**Issue by nottinhill** [Automattic/mongoose#2893]
Error:  { [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: 
    dbName.collectionName.$_id_  dup key: { : ObjectId('5530fb9a65c24ee340412369') }]

Above error message I receive when running this code in express.js (coffeescript):
    
    item = { #lotsa data }
    batchSize = 0
          sheet.forEach (item) ->
            if batchSize < 100                                                                       
              item        = parse.map(item)    # do stuff with item, not relevant                                                   
              myModel = new MyModel(                                               
                aktuell: item
                historie: [{
                  changed: item
                  userid: '54340279407267e53192c42a'
                }])
              batchSize += 1
              myArray.push myModel.toObject()
            else
              MyModel.collection.insert myArray, (err, myArray) ->
                if err
                  console.log 'Error: ', err
                  return
                else    
                  console.log '####### BULK-INSERT with BATCHSIZE=' + batchSize
                  batchSize = 0
                  return

Any ideas what I am doing wrong? I am aleady trying 

	_id	   : { type: Number, sparse: true, required: true}

on schema instantiation.

**Comment by vkarpov15** [comment]
MongoDB creates a unique index on _id by default, so your index build is failing. There's no way to tell MongoDB to have a sparse index on _id by default, although having a sparse index on a required field seems pretty contradictory.

Listen to `MyModel.on('index', function(err) {});` and you'll see that mongodb is failing to construct your index.
