### ISSUE TITLE
Error specifying `required` validator to schema's nested object

### ISSUE THREAD

**Issue by th0r** [Automattic/mongoose#2896]
I have made `Location` schema structure to reuse it in my app (validated `GeoJson` `Point`):
```js
var { Schema } = require('mongoose');

var Location = {
    type: {
        type: String,
        enum: ['Point'],
        default: 'Point',
        required: true
    },
    coordinates: {
        type: [Number],
        validate: [
            arr => arr.length === 2,
            '{PATH} should be an array with two numbers (longitude, latitude)'
        ]
    }
};

module.exports = Location;
```
But when I use it like this:
```js
var { Schema } = require('mongoose');

var Location = require('../schemas/Location');
var db = require('../db');

var CinemaSchema = new Schema({
    title: { type: String, required: true },
    loc: { type: Location, required: true }
});

module.exports = db.model('Cinema', CinemaSchema);
```
I get this error:
```
TypeError: Undefined type `undefined` at `loc.required`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (node_modules/mongoose/lib/schema.js:446:11)
    at Schema.path (node_modules/mongoose/lib/schema.js:378:29)
    at Schema.add (node_modules/mongoose/lib/schema.js:288:12)
    at Schema.add (node_modules/mongoose/lib/schema.js:283:14)
    at new Schema (node_modules/mongoose/lib/schema.js:87:10)
```
Am I doing something wrong?

**Comment by vkarpov15** [comment]
`Location` is not a valid mongoose type. If you do `loc: Location` you'll get the desired result.

**Comment by th0r** [comment]
@vkarpov15 But if I want location in some schemas to be required, and in others - optional? How should I write it?

**Comment by th0r** [comment]
@vkarpov15 In other words, how can mark nested object in a schema as required?
For example:
```

**Comment by vkarpov15** [comment]
Marking location as required is redundant - since `location.type` is required, there's no way to save a Cinema without its corresponding location. To make it so that `location.type` is required iff `location` is defined you'd need a custom validator.

**Comment by q42jaap** [comment]
@vkarpov15 I'm coming from a Scala project with mongodb (using ReactiveMongo), we're evaluating if nodejs and mongoose are a better fit for the next project.
What @th0r is asking here is very common to my experience. In Scala you'd model this with the Option class.

You should definately build this in mongoose some day!

In the meantime, do you have an example maybe that shows how to implement this. As I said, I'm new to mongoose, and I have no idea how to implement a custom validator. I don't want to write off mongoose yet, because it seems very nice to me at first...

**Comment by vkarpov15** [comment]
@q42jaap sure, there's the [validation docs](http://mongoosejs.com/docs/validation.html). Admittedly this feature would be great to have in the future, but it's somewhat tricky to get right.
