### ISSUE TITLE
Error with validating subdocs created with .create()

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2902]
https://github.com/Automattic/mongoose/issues/1638#issuecomment-94873970

**Comment by vkarpov15** [comment]
So @irobert91 that particular crash is unintentional, however, your general paradigm isn't quite correct. Mongoose does not support `validate()` on subdocs that have not been added to an array right now.

```javascript
var newChild = parentInstance.children.create({name: "Bob"});
newChild.validate(...);
```

Will not properly return any validation errors. I'd recommend doing

```javascript
parentInstance.children.push({ name: 'Bob' });
parsentInstance.validate(...);
```

**Comment by irobert91** [comment]
Thank you for the response @vkarpov15.
However, my whole point is to make sure that the subdocument is valid before I push it to it's parent.
I suppose that I should create another model, right?

**Comment by vkarpov15** [comment]
Not really possible as written atm, either in 3.8.x or 4.x - the way subdocuments are designed right now is that they don't track their own internal error state, they rely on their parent doc to handle that for them. As you suggested, you can create a new `Child` model, and use `new Child({ name: 'Bob' }).validate(...);`

**Comment by irobert91** [comment]
Ok, thank you!
