### ISSUE TITLE
Broken class names in the docs

### ISSUE THREAD

**Issue by Thibaut** [Automattic/mongoose#2913]
![mongoose api v4 0 2 2015-04-26 13-52-13](https://cloud.githubusercontent.com/assets/17579/7338496/9b9a1c10-ec1b-11e4-9527-163bbbfd8b81.png)

http://mongoosejs.com/docs/api.html#promise_function%20Object()%20%7B%20%5Bnative%20code%5D%20%7D-fulfill
https://github.com/Automattic/mongoose/blob/e1d0293acfd82c107f2f4febd2fbf87d98390c8f/lib/promise.js#L138-L145

\+ most of [`array.js`](https://github.com/Automattic/mongoose/blob/e1d0293acfd82c107f2f4febd2fbf87d98390c8f/lib/types/array.js):
http://mongoosejs.com/docs/api.html#types-array-js

[`buffer.js`](https://github.com/Automattic/mongoose/blob/e1d0293acfd82c107f2f4febd2fbf87d98390c8f/lib/types/buffer.js):
http://mongoosejs.com/docs/api.html#types-buffer-js

and [`documentarray.js`](https://github.com/Automattic/mongoose/blob/e1d0293acfd82c107f2f4febd2fbf87d98390c8f/lib/types/documentarray.js):
http://mongoosejs.com/docs/api.html#types-documentarray-js

(this breaks [devdocs.io](http://devdocs.io)'s scraper)

**Comment by vkarpov15** [comment]
Thanks for pointing this out, on it.
