### ISSUE TITLE
Unable to remove documents within Mocha test

### ISSUE THREAD

**Issue by mikeerickson** [Automattic/mongoose#2914]
I have a mocha test where I am trying to delete documents, but it doesnt seem to work.   The test passes, but the documents are not deleted.   I have tried two different approaches, neither work?

Any suggestions?

```

  it("should delete a collection of documents", function(done) {

    Batter.find({ last_name : "erickson"}, function (err, batter, done) {
      if (err) { winston.error(err); }
        batter.remove(function (err) {
            if(err) { winston.error(err); }
            winston.success('removed');
        });
      });
      done();
    });

  it("should delete a collection of documents again", function() {
    Batter.find({ last_name: "erickson" }).remove().exec();
  });

```

**Comment by vkarpov15** [comment]
Hmm try `.remove({}, function(err) {});` to remove every document. I think the driver requires you to specify a selector for removing docs.

**Comment by mikeerickson** [comment]
I have tried that as well (amongst many other combos) :-(

**Comment by mikeerickson** [comment]
And further, using the standard code in router works just fine, but won't work in mocha test (all other commands work 

Model.remove({last_name: "Erickson", function(err){
  if(err) { handleError(err); }
});

**Comment by vkarpov15** [comment]
Can you show me a more complete example, including your schema and how you're creating your model?

**Comment by mikeerickson** [comment]
@vkarpov15 Here are the requested files

Spec

https://gist.github.com/mikeerickson/735f20213bbd45211665

Schema

https://gist.github.com/mikeerickson/f6dcfa6f6ae8b08b02d7

**Comment by vkarpov15** [comment]
https://gist.github.com/mikeerickson/735f20213bbd45211665#L46 why no callback? Doesn't look like it matches the example you provided.

Also, what version of mongoose are you using?

**Comment by mikeerickson** [comment]
@vkarpov15 Your comment prompted me to look closer, and I posted an older version of the code which performs the delete.   The gist has been updated.

https://gist.github.com/mikeerickson/735f20213bbd45211665

In short, uses the following code (which also does not work)

    Batter.find({ last_name : "erickson"}, function (err, batter, done) {
      if (err) { winston.error(err); }
        batter.remove(function (err) {
            if(err) { winston.error(err); }
            winston.success('document removed, but this is never hit');
        });
      });
      done();
    });

**Comment by mikeerickson** [comment]
@vkarpov15 And an even more slimmed version

  it("should delete specific record, using alternate technique", function() {
    Batter.remove({last_name: /erickson/i}, function(err) {
      if (err) { winston.error(err); }
      winston.success('Batter removed, but this is never hit');
    });
  });

Using Mongoose 3.6.13

**Comment by vkarpov15** [comment]
That might explain it, very old version of mongoose :) Have you considered upgrading to 3.8 or 4.0? Looks like [3.7.1 had some fix related to .remove()](https://github.com/Automattic/mongoose/blob/master/History.md#371-unstable--2013-08-13). There hasn't been a 3.6 release in 1.5 years, so I'm hesitant to dive into that code...

**Comment by mikeerickson** [comment]
I have upgraded to 3.8 and while that didn't solve the issue, I did figure out the problem.

I had failed to add the connection routines (mongoose.connect, etc) After adding this information, all is now working as expected.

BUT, that throws another issue out there.   If I didnt have a valid database connection, why was an error not thrown when calling these methods (.set, .save, .remove)

**Comment by mikeerickson** [comment]
@vkarpov15 If I dont have a valid connection, one would think that an error should be thrown and passed along to the callback (...., function(err).... )   Instead, the test passes for whatever reason and leads one to think all is fine.

**Comment by vkarpov15** [comment]
Mongoose buffers operations by default, so it's waiting for you to make a db connection before actually sending the op.

**Comment by mikeerickson** [comment]
@vkarpov15 Oh really, didn't know that.  surely makes sense now.
