### ISSUE TITLE
remove middleware failing to be called

### ISSUE THREAD

**Issue by DotFreelance** [Automattic/mongoose#2915]
I'm attaching a pre('remove') middleware function to a schema and it's failing to call it. I've confirmed that it's successfully calling save and update middleware in the same script.
Middleware preparation:
```
DataModels.Comment.schema.pre('remove', function(next){
	console.log('remove hook');
	next();
});
```
Call to remove, done by retrieving the document first as middleware isn't called for mongodb direct call methods:
```
DataModel.findOne({ _id: objectID }, function(err, data){
	data.remove(callback);
});
```

This precise pattern works for save and update, just not remove. Post remove middleware also fails to be called.

It's also important to note that I am empirically validating that the object is a valid object, and is successfully being removed.

Version: 4.0.1
MongoDB: 2.6.8
Node: 0.10.0

**Comment by vkarpov15** [comment]
Can you show me a complete code example? There's a few details that might be causing this that aren't shown, so a complete example that reproduces what you're seeing would be very helpful.

**Comment by DotFreelance** [comment]
I actually think I may have solved it. I'm going to leave the issue open for the time being as I test, but if I'm correct I will close the issue. Thank you for your help vkarpov15 :)

**Comment by DotFreelance** [comment]
Yes, I can confirm I've solved the problem. I really appreciate your time.
