### ISSUE TITLE
Provide unhandled rejection detection

### ISSUE THREAD

**Issue by benjamingr** [Automattic/mongoose#2918]
Hi, most promise libraries (Bluebird, When, Q, Native promises in io.js and so on) support unhandled rejection detection which greatly simplifies dealing with errors in promises. Other libraries (RSVP, native promises in node.js) plan to add this feature.

[Here is the proposal](https://gist.github.com/benjamingr/0237932cee84712951a2) as currently implemented in most major libraries.

It could be great if Mongoose promises supported these hooks - I'd love to help with implementation guidance if you'd like it.

**Comment by vkarpov15** [comment]
See #2688. No plans to make mpromise an ES6-compatible promise library, that's just wasted effort given the sheer number of promises libraries out there. mpromise will remain the default in 4.x but in 4.1 you'll be able to specify your own.

**Comment by benjamingr** [comment]
@vkarpov15 I have not asked for anything like making it ES6 compatible, in fact - that's irrelevant as this is not an ES6 promise feature but a serverside JS one.

I'm not asking for any semantics changes, only exporting process hooks the way other libraries do. You can keep whatever semantics you want but this will significantly improve its debuggability. I ask you to reconsider.

**Comment by vkarpov15** [comment]
Then that's a change with mpromise, which I don't have push access to. You already opened up an issue in mpromise, and #2688 will enable you to specify whatever promises library you want, so this issue is redundant.

**Comment by benjamingr** [comment]
You can do this outside of mpromise the same way @petkaantonov did it without access to v8 for io.js, but as you wish - I'll go bark at those people.

**Comment by Doweig** [comment]
require('mongoose/lib/promise').prototype.error = console.error;

Will do the trick.
