### ISSUE TITLE
Allow post hooks with callbacks in the event flow (e.g. for load)

### ISSUE THREAD

**Issue by maurermax** [Automattic/mongoose#2919]
I bet this has been brought up a couple of times, I just can't find anything about it.

post hooks are called fire and forget style. this makes do things prior to releasing a document that has just been loaded into public use. E.g. I was just working on a post-init hook to store initial values of a loaded document to be able to compare them again lateron to see what has changed.

since the post-hooks don't have a callback it is impossible to be sure that the real initial state has been recorded. Is there any other way to solve this? or why has the approach of fire and forget been chosen for post hooks?

Another problem dealing with this issue is for example: 
http://stackoverflow.com/questions/8141039/using-mongoose-middleware-to-add-async-virtuals

**Comment by vkarpov15** [comment]
The SO question is not really possible - async virtuals are impossible in JS without using something like fibers. You can make a virtual return a promise but that's about it.

Also, query hooks actually use a different hooks library in which post hooks have flow control. That library will have the ability to switch between those two modes.

However, `post('init')` hooks are special and have a lot of weird edge cases. For instance, doing async `init` hooks does some very strange things. If you want to do some operation when a document is instantiated, I'd recommend you do something like what I suggested in https://github.com/Automattic/mongoose/pull/2856#issuecomment-92413210

**Comment by maurermax** [comment]
thanks for the intro and explanation. For my own problem I found a solution so far. 

I looked a bit  in the the source code of mongoose but unfortunately I did not completely get how the control flow works for a saving operation with pre and post hook. I seems like you use "Kareem" for doing the post and pre hook stuff, but in general that also supports synchronous post hooks. 
https://www.npmjs.com/package/kareem#it-can-use-synchronous-post-hooks

So to summarize again what I think is missing is the ability to hook into the control flow between the actual reading and creation of an object from the database and the callback that returns the document back to the application for further processing. So in standard mongo collection driver syntax

````
var hook = function(next) {
  return function(err, doc) {
    // do something with doc
    next(err, doc);
  }
}
db.collection('test').findOne({}, hook(function(err, doc) {
 // now we go on with standard processing
});
````

**Comment by vkarpov15** [comment]
That might work, if we used kareem for post init hooks. Unfortunately we don't yet, that's scheduled for 4.1 :(

**Comment by lgomez** [comment]
@maurermax I just posted #3568 before I found your issue here. Are we talking about the same thing and has your solution worked for you? I was wondering if defaults could work but I don't think that solves it.

**Comment by maurermax** [comment]
@lgomez as @vkarpov15 pointed out in your ticket this also looks like a pre save hook to me. pre save hook has a callback so you can postpone saving. If you need the values right after initialization you would need to create some kind of populate-method with a callback in your model and call it right after calling new on your object and setting all props that you need for your population.

**Comment by lgomez** [comment]
Thank you. I'll try that next.

**Comment by vkarpov15** [comment]
See [async post hooks](https://mongoosejs.com/docs/middleware.html#post-async)
