### ISSUE TITLE
Problem deleting element in a document

### ISSUE THREAD

**Issue by ishepard** [Automattic/mongoose#2920]
Hi,
I have a model like that:
```javascript
var example = mongoose.model('example', mongoose.Schema({
    username: String,
    password: String,
    list_example: {}
}));
```
When I populate list_example with data, it will be like:
```
list_example: 
{
'8d685df28407f74305eaeebbf840e5c0f9838445': '66bce37e-29c3-4c42-9786-bd7c865d41c1',
'7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0': null,
'260790090ee0c3de64a64d67974cae13f437fa6e': null 
}
```
There are the "null" there because I deleted that item, using:
```
list_example['7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0'] = undefined;
```
I tried also:

```
delete list_example['7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0'];
```

None of them actually remove the item..they just put it to null! Why? 
I figured out that it's not the delete the problem...but the document.save() that puts to "null" that item..
In order to save I used both document.save() and example.findOneAndUpdate().
Any suggestion?

**Comment by vkarpov15** [comment]
As a workaround just `MyModel.update({}, { $unset: { '7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0': 1 } });`

**Comment by ishepard** [comment]
It doesn't work..because the structure is: 
var MyModel = mongoose.model('MyModel', mongoose.Schema({
    username: String,
    password: String,
    list_example: {
            '8d685df28407f74305eaeebbf840e5c0f9838445': '66bce37e-29c3-4c42-9786-bd7c865d41c1',
            '7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0': null,
            '260790090ee0c3de64a64d67974cae13f437fa6e': null 
    }
}));
So I should do something like MyModel.update({}, { $unset: { 'list_example[7a5f1a5ce552aa4af63c58c4a33f44ea6513ebf0]': 1 } });
And however this number changes, so I can't fix it at the beginning

**Comment by vkarpov15** [comment]
So the following code works for me:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2920');

var Example = mongoose.model('example', mongoose.Schema({
    username: String,
    password: String,
    listExample: {}
}));

Example.create({ listExample: { a: 1, b: 2 } }, function(error, doc) {
  delete doc.listExample['a'];
  doc.markModified('listExample');
  doc.save(function(error, doc) {
    console.log('---> ' + require('util').inspect(doc));
    process.exit(0);
  });
});
```

Output:

```
Mongoose: examples.insert({ listExample: { b: 2, a: 1 }, _id: ObjectId("554a220f711bdd294683ff65"), __v: 0 })   
Mongoose: examples.update({ _id: ObjectId("554a220f711bdd294683ff65") }) { '$set': { listExample: { b: 2 } } }  
---> { __v: 0, listExample: { b: 2 }, _id: 554a220f711bdd294683ff65 }
```

Have you used `markModified()`? Keep in mind that you [need to call markModified when you update a field of type `Mixed`](http://mongoosejs.com/docs/schematypes.html#mixed)

**Comment by vkarpov15** [comment]
No response for a while, re-open if this is still an issue.
