### ISSUE TITLE
embedded lookup by id fails

### ISSUE THREAD

**Issue by panva** [Automattic/mongoose#2923]
Documented [here](http://mongoosejs.com/docs/api.html#types_documentarray_function%20Object()%20%7B%20%5Bnative%20code%5D%20%7D-id) and [here](http://mongoosejs.com/docs/subdocs.html) I should be able to lookup an embedded schema member by it's id.

This however fails right [here](https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L112);

```
$ account.emails.id(primary_id);
TypeError: undefined is not a function
    at Array.MongooseDocumentArray.mixin.id (/node_modules/mongoose/lib/types/documentarray.js:112:19)
```

**Comment by vkarpov15** [comment]
You're going to have to provide me sample code that reproduces this, the below script works fine for me:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2923');

var Example = mongoose.model('example', mongoose.Schema({
  docs: [{ a: Number }]
}));

Example.create({ docs: [{ a: 1 }] }, function(error, doc) {
  console.log(doc.docs.id(doc.docs[0]._id));
  console.log(doc.docs.id('not found'));
  process.exit(0);
});
```

**Comment by panva** [comment]
I am also not able to reproduce using a simple schema setup. Currently i've dropped the mongoose v3 to v4 migration due to mongoose-encryption not working with v4 at all. Should i come across this scenario again i will remember to capture more details.
