### ISSUE TITLE
Race condition in post save middleware in 4.0.2

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2925]
The problem is a race condition in post save middleware in version 4.0.2: post save middleware is actually executed before the saved object reaches mongoDB.

I have activities of various types (comments, ...) defined by discriminators. See structure in https://github.com/Automattic/mongoose/issues/2892.

Activities have post save middleware that counts activities to update users with metrics. 

```js
function postSaveMiddleware(activity) {
    ...
    switch (activity.type/*__t*/) {
        case 'Comment':
            var Comment = Activity.discriminators.Comment;
            Comment.count({ 'actor._userId': activity.actor._userId }, function (error, count) {
                if (!error && count) {
                    User.update({ _id: activity.actor._userId }, { $set: { 'metrics.comments.count': count, updated: new Date() } }, function (err, num) {
                        callback(err);
                    });
                } else {
                    callback(error);
                }
            });
            break;
        case Activity.ACTIVITIES.PUBLICATION:
        ...
    }
};
```

if I put  a breakpoint on:
```
Comment.count({ 'actor._userId': activity.actor._userId }, function (error, count) {
```
activity is not yet in database.

But if I put a breakpoint on the following line:
```
 if (!error && count) {
```
count=0 but now the activity has reached the database so the count should actually be 1.

This issue did not exist in 3.8.26. It is new to version 4.

**Comment by vkarpov15** [comment]
Should be fixed with #2949
