### ISSUE TITLE
createConnection failing for multiple connections 

### ISSUE THREAD

**Issue by footmarksadmin** [Automattic/mongoose#2926]
Moving from mongoose 3 to 4 is causing an Auth MongoError stating the authMechanism must be one of the bla bla bla. I realize that MONGO-CR was the default prior and now it appears this may have changed, but I've not had any luck overriding the options passed into the connection.

As of what I've discovered so far, it appears to be related to the multiple connections we establish using createConnection. We have 7 databases that all live on the same MongoLab server and each has it's own connection established using createConnection. We've had no issues prior to now, but it's extremely important we upgrade to 4.0 to take advantage of the additional middleware and validation offered. We are using a replica set in MongoLab and the options we pass to createConnection contain the replset object with rs_name. 

Any help would be greatly appreciated.

**Comment by vkarpov15** [comment]
How are you passing in options and what do your `createConnection()` calls look like?

**Comment by footmarksadmin** [comment]
Here is a snippet from a connection utility I've wrote:

var connections = {};
var OPTS = {
	server: { poolSize: 10, socketOptions: { keepAlive: 1, connectTimeoutMS: 60000, socketTimeoutMS: 600000 } }, 
	replset: { 
        rs_name: "rs-XXXXXX",
        poolSize: 10, 
        socketOptions: { keepAlive: 1, connectTimeoutMS : 60000, socketTimeoutMS: 600000 }
    }
};

function MyConnect(name, done){
    if (connections[name]) connections[name].close();
    
    var uri = "mongodb://user:password@dsXXXXXX-a1.mongolab.com:XXXXX,dsXXXXXX-a0.mongolab.com:XXXXX/" + name;
    var connection = mongoose.createConnection(uri, OPTS);
    connection.on('connected', function(){
        console.log('[Mongoose] Connected to', name.toUpperCase());
        done();
    });  
   connections[name] = connection;
};

During run-time, I leverage this function and the populate node async lib to open up all of the database connections in parallel like so:

function MyFunction(next){
    var connectionsArr = [];
    connectionsArr.push(async.apply(MyConnect, 'db1'));
    connectionsArr.push(async.apply(MyConnect, 'db2'));
    connectionsArr.push(async.apply(MyConnect, 'db3'));
    connectionsArr.push(async.apply(MyConnect, 'db4'));
    connectionsArr.push(async.apply(MyConnect, 'db5'));
    connectionsArr.push(async.apply(MyConnect, 'db6'));
    connectionsArr.push(async.apply(MyConnect, 'db7'));
    connectionsArr.push(async.apply(MyConnect, 'db8'));       
    async.parallel(connectionsArr, next);   
}

Please let me know if that's enough context. 

Thanks,

Skylar

**Comment by footmarksadmin** [comment]
Were you able to review the connection code by chance?

**Comment by vkarpov15** [comment]
Not yet. As a workaround, you can try setting `connectTimeoutMS` and `socketTimeoutMS` in the URI, something like `mongodb://localhost:27017/dbName?connectTimeoutMS=60000&socketTimeoutMS=60000`. That's what I use to set connectTimeoutMS and socketTimeoutMS in my applications.

**Comment by footmarksadmin** [comment]
This is not a workaround and does not help. Ignore the timeout options. The issue is connecting to multiple databases.

**Comment by mattcasey** [comment]
We also have multiple databases. The way we do it is to use one connection pool for all of them, like this:
```
function getDbs () {
  var connection = mongoose.createConnection();
  return ['db1', 'db2'].map(function (dbName) {
    // .useDb() gives you a database object to attach schemas to later on using database.model()
    return connection.useDb(dbName);
  });
}
```

**Comment by vkarpov15** [comment]
This is an issue in the underlying node driver that we had fixed in the legacy 1.4 release series but the fix didn't get ported to the new 2.0 version of the driver. See PR mongodb/node-mongodb-native#1274 for updates.

**Comment by footmarksadmin** [comment]
Thanks for pushing this. I was able to fix this using the patch you submitted. In order to get something firm referenced via my package.json with the fix, would I need to fork mongoose and include my version for the time being with the fix within the core mongodb driver?

**Comment by vkarpov15** [comment]
Unfortunately you would need to fork both mongoose and underlying mongodb driver, because the fix for this is only in the driver. You can also just fork mongoose and make a clone of `this.options` in this function: https://github.com/Automattic/mongoose/blob/cb975dbad67ce06c08888bc9ea866f7abd0406bc/lib/drivers/node-mongodb-native/connection.js#L47-62 and this function: https://github.com/Automattic/mongoose/blob/cb975dbad67ce06c08888bc9ea866f7abd0406bc/lib/drivers/node-mongodb-native/connection.js#L192-219 and that would probably have the same effect if you want something immediately, but that's not a fix that we would be willing to support long-term.
