### ISSUE TITLE
"not master" error when reading from secondary.

### ISSUE THREAD

**Issue by libook** [Automattic/mongoose#2927]
A nodejs application read a secondary database. I got an "Error" from mongodb-core.
And the error message is "not master".

How to read data from secondary database?

mongodb: v3.0.2
mongoose: v4.0.1

**Comment by vkarpov15** [comment]
Set the read preference

```javascript
db.find().read('secondary').exec()
```

**Comment by diggzhang** [comment]
Set the read preference really worked, but is there any solution to solve this problem with once?
I'm curious about the design pattern that you have applied ever before.

**Comment by vkarpov15** [comment]
Schemas have a read option. Just Google 'mongoose schema readpreference'
