### ISSUE TITLE
Cannot get `raw` query info after `findOneAndUpdate`

### ISSUE THREAD

**Issue by chrisjhoughton** [Automattic/mongoose#2931]
I'd like to get raw query info after my call to `findOneAndUpdate` in order to detect if a document was upserted or not. 

I've read this solution in numerous places.

However, it looks like the `raw` is undefined when I try it - is this a recent change? Are there any workarounds?

Thanks

**Comment by vkarpov15** [comment]
Mogodb findandmodify only returns the doc. To check if there was an upsert specify new: false and check if the doc returned was null

**Comment by chrisjhoughton** [comment]
Thanks!
