### ISSUE TITLE
Support $push + $addToSet validation in update validators

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2933]

**Comment by vkarpov15** [comment]
Gonna have to push this one back, it's very tricky to implement for subdocs and `$each` because update validators right now rely on flattening the update into constituent parts, which really doesn't play nice with how `$push` pushes whole subdocs.

**Comment by GuillaumeLeclerc** [comment]
is it working or not ?

**Comment by vkarpov15** [comment]
Not yet, haven't had a chance to work on it. PRs welcome.

**Comment by toymachiner62** [comment]
👍

**Comment by ThisIsRuddy** [comment]
Appologies for my ignorance but does that commit mean that I can push values in to the 'enum' option in the schema for a model and it be used in the validation when updating/creating a document?

**Comment by vkarpov15** [comment]
@ThisIsRuddy nope that's not what this issue is about. This issue is more about doing `.update()` with `$push` and `runValidators`, has nothing to do with modifying enum values on the fly.

**Comment by daeltondias** [comment]
Has this problem been resolved?

**Comment by vkarpov15** [comment]
@daeltondias yes. Are you seeing a related issue?
