### ISSUE TITLE
findByIdAndUpdate does not return updated array with $push

### ISSUE THREAD

**Issue by root-io** [Automattic/mongoose#2936]
I experienced a weird issue with Mongoose 4.0.2 and MongoDB 3.0.2
When I $push a value to an array, the value has been added to the array in the database but findByIdAndUpdate return the old array (not updated).

    User.findByIdAndUpdate(req.user._id, {
      $push: { friends: friend._id }
    }, cb);

I was forced to tricky hack like:

    User.findByIdAndUpdate(req.user._id, {
      $push: { friends: friend._id }
    }, function (err, user) {
      user.friends.push(friend._id);
      cb(err, user);
    });

Thanks :)

**Comment by vkarpov15** [comment]
See [release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes) section on #2262. The following code will get you the behavior you want.

```javascript
User.findByIdAndUpdate(req.user._id, {
  $push: { friends: friend._id }
}, { 'new': true}, cb);
```

**Comment by root-io** [comment]
@vkarpov15 Thanks :+1:
