### ISSUE TITLE
Unintuitive schema path options

### ISSUE THREAD

**Issue by eloytoro** [Automattic/mongoose#2944]
I'm opening an issue for this since it's not documented and no other issues tackle on this.

Why is it that when I define my schema this way
```javascript
var UserSchema = new UserSchema({
    accounts: [{ type: ObjectId, required: true }]
});
```

The options for the `account` path are empty?

It seems that instead I have to do `schema.path('accounts').caster.options` to get the _actual_ options.
What's this caster and why is this consider to be ok?
Wouldnt It be more intuitive if both `schema.path('acounts').options` and `schema.path('accounts').caster.options` were to reference the same object?
This would be very useful to create my own user-defined set of options.

**Comment by vkarpov15** [comment]
What are you trying to do by accessing the path options?

**Comment by eloytoro** [comment]
I'm trying to write a plugin which enables some new options for your schema paths, so besides the available mongoose options you could use the new ones.

For example if a path were to have `readonly: true` that would mean that you couldnt alter the document's property after creation

**Comment by vkarpov15** [comment]
Just use schema.eachPath(), see vkarpov15/mongoose-autopopulate for an example

**Comment by eloytoro** [comment]
From your code
```javascript
schema.eachPath(function (pathname, schemaType) {
  // if the schemaType is defined using the Array notation, such as
  // path: [{ type: ObjectId, ref: 'someRef', autopopulate: true }]
  // options will be empty
  if (schemaType.options && schemaType.options.autopopulate) {
    var option = schemaType.options.autopopulate;
    pathsToPopulate.push({ path: pathname, autopopulate: option });
  }
});
```

**Comment by vkarpov15** [comment]
Ah ok I see, you're trying to get the options within an array. The caster is the embedded doc, schema.get('accounts') returns the options for the array itself, not the type embedded in the array

**Comment by eloytoro** [comment]
Is _defining options for an array_ something that makes sense?
Is this the desired behavior? What's the correct way to do it?

**Comment by vkarpov15** [comment]
Sure, you can do something like

```javascript
var UserSchema = new UserSchema({
    accounts: { type: [ObjectId], myOption: true }
});
```

**Comment by eloytoro** [comment]
That makes sense, I'll close this issue
Thanks for the help
