### ISSUE TITLE
Mongoose ignores strict mode on findOneAndUpdate and update with non empty objects

### ISSUE THREAD

**Issue by FernandoCastilloCedillo** [Automattic/mongoose#2947]
This is an example of the situation:

----------------------------------------------------------------

```javascript
// define a schema
var personSchema = new Schema({
  name: {
    first: String,
    last: String
  }
}, {strict: true});

// compile the model
var Person = mongoose.model('Person', personSchema);

// create a document
Person. create({
    name: { first: 'Walter', last: 'White' },
    dropthis : {a: 'b', c:'d'} // <-- this is not inserted
});

// 
Person.findOneAndUpdate( // the situation also happens when I use update function
    {name.first: 'Walter'}, 
    { 
          name.first: 'jason',
          thisisdroped: {},      // this is not inserted because is an empty object
          thisisinserted: {a: 'b', c:'d'} // this will be inserted as an empty object
    }, 
    {strict: true}, <-- note that I'm enabling strict explicitly
    function(err){
       // update done!!
});
```

------------------------------------------------------------------

the output document I get is:

```javascript
{
    name: {first: 'jason', last: 'White'},
    thisisinserted: {}
}
```

I don't know if this is really a bug or there is an option that I'am missing to enable.

**Comment by antolovich** [comment]
I am experiencing the exact same issue in Mongoose 4.0.2

**Comment by JLavoieMTL** [comment]
Same for me. Scalar are not saved, but empty object are saved. See http://stackoverflow.com/questions/31348752/mongoose-allow-extra-fields-on-document-update

**Comment by ane1006** [comment]
I am experiencing the exact same issue on update in Mongoose 4.2.3. Can you please let me know if there is some patch that I can install in order to resolve this?

**Comment by JLavoieMTL** [comment]
Hi, I would recommand you to upgrade. We now use Mongoose 4.5.10 and it
works

---
Joël Lavoie
*P *514.616.3768 | *@ *joel.lavoie.mtl@gmail.com |
<http://ca.linkedin.com/pub/joel-lavoie/19/6a1/104>
<http://ca.linkedin.com/pub/joel-lavoie/19/6a1/104> LinkedIn
<http://ca.linkedin.com/pub/joel-lavoie/19/6a1/104>

2016-12-14 10:55 GMT-05:00 ane1006 <notifications@github.com>:

**Comment by ane1006** [comment]
Thank you @JLavoieMTL  . WIth 4.5.10 issue gets resolved.

**Comment by FreifeldRoyi** [comment]
Happens on mongoose 5.9.10 with `findOneAndUpdate` (with upsert)

**Comment by vkarpov15** [comment]
@FreifeldRoyi please open a separate issue and follow the issue template. Posting "me too" on a long-closed comment isn't helpful.
