### ISSUE TITLE
Unable to store array of ObjectId after casting

### ISSUE THREAD

**Issue by azachar** [Automattic/mongoose#2956]
Hello!

I have difficulties to achieve a very simple use case - to store an array of ObjectId

Here is my schema:
```
var ASchema = new Schema({
  products:[Schema.Types.ObjectId],
 
});
```
Saving the following structure doesn't work: ( I have already casted all string ids into ObjectIds) as you can see:

```
{ _id: '5546ba16d799a377d98ecac9',
  products: 
   [ 55428c4a0808c62d2870526d,
     25428c4a0808c62d28705262,
     546a1f1f85a6ccaf13f2bdce ],
...
}
```

Funny thing is when I do this:
```
var RefSchema = new Schema({type:Schema.Types.ObjectId});

var ASchema = new Schema({
  products:[RefSchema],
 
});
```

Then it works. Only thing is that the structure is a bit ugly. 
```
{ _id: '5546ba16d799a377d98ecac9',
  products: 
   [ { _id: '....'},{_id:'...'},,{_id:'...'} ],
...
}
```
What I am doing wrong here? I am using Mongoose 3.8.27.

Thanks for any help. This is such a headache....

Cheers,
Andy

**Comment by vkarpov15** [comment]
When you say

```javascript
var RefSchema = new Schema({type:Schema.Types.ObjectId});

var ASchema = new Schema({
  products:[RefSchema],

});
```

You're telling mongoose that `products` is an array of subdocs. Try doing this instead:

```javascript
var RefSchema = { type: ObjectId, ref: 'MyModel' };

var ASchema = new Schema({
  products:[RefSchema],

});
```

**Comment by azachar** [comment]
This is what I tried in the first place. And it did not work.

**Comment by vkarpov15** [comment]
"does not work" is not a bug report. Please provide code that shows how you're "providing an array of pure strings."

**Comment by azachar** [comment]
Thank you for your quick reply. I found it out, the problem was related with ``markModified``
Here is a problematic code:
```
ASchema.findById(req.params.id, function (err, updated) {
 updated.products = ['a','b'];
 updated.markModified('products');  // without this line it doesn't work
 updated.save(function (err) {
     .....
  });
})
```

After calling method ``markModified`` it works fine.
