### ISSUE TITLE
4.0.2 mongoose.connection.db.collectionNames is undefined

### ISSUE THREAD

**Issue by airyland** [Automattic/mongoose#2960]
After upgrade to v4.0.2, the function does work?

**Comment by vkarpov15** [comment]
I don't understand the question. Code example please.

**Comment by airyland** [comment]
I use the function to get all the collection names in the database:

```
mongoose.connection.db.collectionNames(function(error, collections) {
// something
});

```
But now the collectionNames function does not exist.

And I find it's caused by the upgrade of MongoDB Driver.

http://mongodb.github.io/node-mongodb-native/2.0/meta/changes-from-1.0/

```
db.collectionNames removed as it’s just a specialized version of the new listCollections helper.
```

**Comment by vkarpov15** [comment]
That's correct. Glad you found the issue :)
