### ISSUE TITLE
the change log does not mention that validation error's property type is changed to kind @4.0.2

### ISSUE THREAD

**Issue by airyland** [Automattic/mongoose#2961]
When I found my error handler does not work correctly.
And Why to make change?

**Comment by vkarpov15** [comment]
See #1323 for the "why." The [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) do mention this, but the change log does not. I'll add that.

**Comment by airyland** [comment]
Sorry, I did read the release notes but fail to notice it. I was a little angry at that time.

**Comment by vkarpov15** [comment]
No worries, fixed now. I hope it wasn't the release notes that made you angry :)
