### ISSUE TITLE
VersionError after updating to 4.x

### ISSUE THREAD

**Issue by trueinsider** [Automattic/mongoose#2962]
Mongoose: 4.0.2
Node.js: 0.10.33
MongoDB: 2.4.6

When user login in our game we load his data from mongo, modify it in memory (as long as he is playing) and save at 2 min interval. We have only one place in our code where `.save()` is happening. And it can't happen concurrently. There shouldn't be VersionError in this conditions at all, right? And there wasn't in 3.8.x

I don't know yet how to exactly reproduce issue, it happens not for all users and not at all save attempts. I'll keep looking but I thought I'll report it anyway.

**Comment by vkarpov15** [comment]
Not that I know of, but I may be misunderstanding how your code is written. Can you show me some example code and maybe I can help you figure out how to reproduce?

**Comment by trueinsider** [comment]
There isn't much code to show, I'll try to explain:

Server is a simple REST api. On `/auth` endpoint we fetch user data in memory using `Model.findOne()` and keep it there.

When user access other endpoints we modify his data in memory.

Then, at 2 min intervals we do `Document.save()`

**Comment by trueinsider** [comment]
Ok, investigated a little more.

Here is my saving code:

		logger.info("Saving user " + user.token + "; version = " + user.__v);
		user.save(function (error) {
			if (error) {
				return logger.error(error + ' ' + user.token);
			} else {
				logger.info("Saved user " + user.token + "; version = " + user.__v);
			}
		}

And I added console.log's to model.js of mongoose:

	if ('$push' == op || '$pushAll' == op || '$addToSet' == op) {
		console.log('VERSION_INC because of ' + op + ' at ' + data.path);
		self.$__.version = VERSION_INC;
	}
	else if (/^\$p/.test(op)) {
		// potentially changing array positions
		console.log('VERSION_ALL because of ' + op + ' at ' + data.path);
		self.increment();
	}
	else if (Array.isArray(val)) {
		// $set an array
		console.log('VERSION_ALL because of ' + op + ' at ' + data.path);
		self.increment();
	}
	// now handling $set, $unset
	else if (/\.\d+\.|\.\d+$/.test(data.path)) {
		// subpath of array
		console.log('VERSION_WHERE because of ' + op + ' at ' + data.path);
		self.$__.version = VERSION_WHERE;
	}
-
	// $push $addToSet don't need the where clause set
	if (VERSION_WHERE === (VERSION_WHERE & this.$__.version)) {
		where[key] = this.getValue(key);
		console.log('where version == ' + where[key]);
	}

Now there is logs:

	info: Saving user a886665b5cbcd7405609c39dd84d98cb; version = 3
	VERSION_WHERE because of $set at missionInfo.0.exp
	VERSION_WHERE because of $set at missionInfo.0.gold
	VERSION_WHERE because of $set at missionInfo.0.starsCount
	VERSION_WHERE because of $set at missionInfo.0.stone
	VERSION_WHERE because of $set at missionInfo.0.wood
	VERSION_ALL because of $set at spells
	where version == 3
	info: Saved user a886665b5cbcd7405609c39dd84d98cb; version = 4

And then at next save (without any user actions between them):

	info: Saving user a886665b5cbcd7405609c39dd84d98cb; version = 2
	VERSION_ALL because of $set at spells
	where version == 2
	error: VersionError: No matching document found. a886665b5cbcd7405609c39dd84d98cb

How could version became 2 when it already was 4?

**Comment by vkarpov15** [comment]
That's strange. I don't know, but I'll investigate more when I get a chance.

**Comment by trueinsider** [comment]
> And it can't happen concurrently
That was wrong. Everything ok now.

**Comment by vkarpov15** [comment]
Glad you figured it out.
