### ISSUE TITLE
findByIdAndUpdate does not return the modified document by default?

### ISSUE THREAD

**Issue by airyland** [Automattic/mongoose#2963]
My unit test cases fail a lot because of this. I have to add `new:true` to every query used findByIdAndUpdate to make them pass.
But the doc says:

```
new: bool - true to return the modified document rather than the original. defaults to true
```

**Comment by vkarpov15** [comment]
Where do you see this in the docs? See [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes) and discussion in #2262

**Comment by airyland** [comment]
I check the doc again and it's right  at the moment.

`new: bool - if true, return the modified document rather than the original. defaults to false (changed in 4.0)`

http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate
