### ISSUE TITLE
mongoose populate not populating an array

### ISSUE THREAD

**Issue by raghuiitr** [Automattic/mongoose#2966]
I am facing an issue where mongoose query is not populating an array type. 

Here is institute schema

    'use strict';
    
    var mongoose = require('mongoose');
    var Schema = mongoose.Schema;
    
    var InstituteSchema = new Schema({
        name: String,
        address: String,
        city: String,
        country: String,
        zip: String,
        owner: { type: mongoose.Schema.ObjectId, ref: 'User' },
        teachers: [{type: mongoose.Schema.ObjectId, ref: 'Teacher'}],
        categories: [String],
        created : { type : Date, default : Date.now }
    });
    
    module.exports = mongoose.model('Institute', InstituteSchema);

And here is teacher Schema

    'use strict';
    
    var mongoose = require('mongoose');
    var Schema = mongoose.Schema;
    
    var TeacherSchema = new Schema({
        education: [{degree: String, instituteName: String}],
        dob: Date,
        photoUrl: String,
        phoneNumber: String,
        owner: {type: mongoose.Schema.ObjectId, ref: 'User'},
        institutes: [{type: mongoose.Schema.ObjectId, ref: 'Institute'}],
        subjects: [{type: mongoose.Schema.ObjectId, ref: 'Subject'}],
        created : { type : Date, default : Date.now }
    })
    
    module.exports = mongoose.model('Teacher', TeacherSchema);

Here is a method which queries the institute by owner id

    exports.mine = function (req, res, next) {
        var ObjectId = mongoose.Types.ObjectId;
        var userId = new ObjectId(req.user._id);
        Institute.find({
            owner: userId
        }).populate('teachers').exec(function (err, institute) {
            if (err) return next(err);
            if (!institute) return res.json(401);
            res.json(institute);
        });
    };

I can see from the db that institute has teacher added 

    db.institutes.find();
    { 
        "_id" : ObjectId("554719a9f5be11c6d4369264"), 
        "owner" : ObjectId("5547199bf5be11c6d4369263"), 
        "country" : "USA", 
        "name" : "Raghvendra Singh", 
        "address" : "38589 Royal Ann Cmn", 
        "city" : "Fremont", 
        "zip" : "94536", 
        "created" : ISODate("2015-05-04T07:03:05.569Z"), 
        "categories" : [ "IIT", "Medical" ], 
        "teachers" : [ ObjectId("55471965f5be11c6d436925f") ], 
        "__v" : 3 
    }

But somehow the query method doesn't populate the teachers collection. The weird thing is that i don't even get the collection with object ids and it returns and institute with empty teacher array. 

And when i remove the **.populate('teachers')** from the method call it indeed returns the teacher array with object ids.

I looked at the documentation and i can't see what am i doing wrong.

**Comment by vkarpov15** [comment]
Are you sure that the teacher object exists? That is, does `db.teachers.find({ _id : ObjectId("55471965f5be11c6d436925f") });` return anything?

**Comment by raghuiitr** [comment]
Thanks for your comment. I found the problem. The model was referring to some other entity, fixed that and its working fine. You can close this bug

**Comment by SirPhemmiey** [comment]
Hi guys, please I am facing this same issue. Any solution?

**Comment by vkarpov15** [comment]
@SirPhemmiey please open up a new issue and follow the issue template
