### ISSUE TITLE
subdocument array of doc is empty at post init hook function

### ISSUE THREAD

**Issue by mstdokumaci** [Automattic/mongoose#2967]
altough there are subdocuments in array, post init hook can't reach them.
```js
schema.post('init', function (doc) {
  console.log(doc.sub_documents) // prints []
});
```
This problem started with 4.x.x , 3.8.x versions are printing sub documents properly.

**Comment by vkarpov15** [comment]
This seems to be a duplicate of #2949 etc. Will be fixed in 4.0.3.
