### ISSUE TITLE
aggregation.options = {allowDiskUse: true}; not work  "version": "4.0.2"

### ISSUE THREAD

**Issue by link5209** [Automattic/mongoose#2970]
{
    "error": {
        "name": "MongoError",
        "message": "exception: aggregation result exceeds maximum document size (16MB)",
        "errmsg": "exception: aggregation result exceeds maximum document size (16MB)",
        "code": 16389,
        "ok": 0
    }
}

**Comment by vkarpov15** [comment]
Same issue as #2964, closing

**Comment by Akash0333** [comment]
Got same error can you please help ?

**Comment by varunjayaraman** [comment]
@Akash0333 did you use a cursor or did you just use `allowDiskUse: true`?

**Comment by mehtaakshay2206** [comment]
@varunjayaraman i used allowDiskUse: true as i don't have cursor option in spring mongo repository

**Comment by varunjayaraman** [comment]
@mehtaakshay2206 are you not using mongoose?

**Comment by LeonLiber** [comment]
I'm using latest mongoose `aggregation.allowDiskUse(true).exec()` and still getting this error:

`'Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.'`

Am I missing something?

**Comment by vkarpov15** [comment]
@LeonLiber can you please provide a more detailed code sample and clarify your versions of mongoose and mongodb?

**Comment by LeonLiber** [comment]
@vkarpov15 What turned out eventually is that my hosted mongo provider (mongodb.com) does not allow `allowDiskUse(true)` in any of the shared memory plans. 

Thank you though!

**Comment by vkarpov15** [comment]
Ah that explains it. Can you post a link to the docs where you found this information? I was not aware of this and having a relevant link would be great for future instances of this issue.

**Comment by LeonLiber** [comment]
Of course, here it is:

https://docs.atlas.mongodb.com/unsupported-commands/

Clearly states that allowDiskUse is not supported on free tier and also, as confirmed by the support team, neither on any of the shared memory plans.

**Comment by pspkshah** [comment]
If you are working with m10 or later version of mongo atlas, below is the fix for {allowDiskUse: true}; 
If you are accessing data from application via mongoose then, it should be syntax as function

For. Example 
MongoDb Query: 
db.collection.user.aggrigate([], {allowDiskUse: true})

With Mongoose:
User.aggrigate([]).allowDiskUse(true);

This will resolve error from application :)
