### ISSUE TITLE
Embedded subdocuments are missing using find, findOne, etc. 

### ISSUE THREAD

**Issue by facultymatt** [Automattic/mongoose#2975]
Given the following schema: 
```
var wheelSchema = new Schema({
  name: String,
  price: Number
});

var OrderSchema = new Schema({
  orderId: String,
  wheels: [wheelSchema]
}, {
  collection: 'processedOrders'
});
```

After creating a new database entry:
```
var order = new Order({
  orderId: 1,
  wheels: [{
    name: 'wheel 1',
    price: 99
  }, {
    name: 'wheel 2',
    price: 99
  }]
});

order.save();
```

In the database I can see that an order with 2 nested wheels exists. However when I query the order the wheels array is empty. 
```
Order.findOne({
  orderId: 1
}, function(err, foundOrder) {
  // fails
  // foundOrder.wheels.length == 0;
  expect(foundOrder.wheels.length).toEqual(2); 
});
```

I have also tried using `.populate()` to no avail.

**Comment by chaines** [comment]
Running the following code: 

  var mongoose = require('mongoose')
    , Schema = mongoose.Schema

  mongoose.connect('mongodb://localhost/test2975')

  var wheelSchema = new Schema({
    name: String,
    price: Number
  });

  var OrderSchema = new Schema({
    orderId: String,
    wheels: [wheelSchema]
  }, {
    collection: 'processedOrders'
  });

  var Order = mongoose.model('Order', OrderSchema)

  Order.remove({}, function(err) {
    var order = new Order({
      orderId: 1,
      wheels: [{
        name: 'wheel 1',
        price: 99
      }, {
        name: 'wheel 2',
        price: 99
      }]
    });

    order.save(function(err) {
      Order.findOne({
        orderId: 1
      }, function(err, foundOrder) {
        console.log(foundOrder.wheels.length)
      });
    });
  })

Results in the expected output of '2'

**Comment by facultymatt** [comment]
I updated the code to more closely reflect my model, and isolated the problem. I am defining a model property called `isModified` which conflicts with the [isModified](http://mongoosejs.com/docs/api.html#document_Document-isModified) method on mongoose documents. 

While this is my fault, it would be helpful if an error or waning was provided. Since the database write doesn't outright fail, this is difficult to debug. An error when trying to define a schema with non-allowed properties would be helpful. 

```
var mongoose = require('mongoose'),
  Schema = mongoose.Schema

  mongoose.connect('mongodb://localhost/test2975')

var wheelSchema = new Schema({
  couponsApplied: {
    type: Array,
  },
  name: String,
  price: Number,
  isModified: {
    type: Boolean,
    'default': false
  }
});

var OrderSchema = new Schema({
  orderId: String,
  wheels: [wheelSchema]
}, {
  collection: 'processedOrders'
});

OrderSchema.virtual('totalPrice').get(function() {
  return this.basePrice + this.salesTax + this.shipping;
});

var Order = mongoose.model('Order', OrderSchema);

//clear collection before testing.
Order.remove({}, function(err) {
  var order = new Order({
    "orderId": "123",
    "wheels": [{
      name: 'wheel 1',
      price: 99
    }, {
      name: 'wheel 2',
      price: 99
    }]
  });

  order.save(function(err) {
    Order.findOne({
      orderId: '123'
    }, function(err, foundOrder) {
      console.log(foundOrder.wheels.length)
    });
  });
})
```

Results in the unexpected output of `0`, even though the database has been updated.

**Comment by vkarpov15** [comment]
Good point, we should really make it so that the `isModified` property is something more like `$isModified` or something

**Comment by vkarpov15** [comment]
So I fixed this by adding `isModified` to schema reserved keywords, you'll get an error now if you try to use isModified in a schema. Generally this may be backwards breaking, but unlikely because I don't really see a case where mongoose would work properly with a schema that contains `isModified`, that function is pretty deeply baked into mongoose and is used every time you validate a doc and load a doc from the db. Either way, if this breaks anybody's code, they'll get an error when they start their server and can open up an issue to see if there's a way to work around this.

**Comment by vkarpov15** [comment]
Also, FWIW, it's only top-level `isModified` that isn't allowed. The below is totally valid.

```javascript
var wheelSchema = new Schema({
  couponsApplied: {
    type: Array,
  },
  name: String,
  price: Number,
  data: {
    isModified: {
      type: Boolean,
      'default': false
    }
  }
});
```

And probably the better choice since nesting objects is one of the better ways to achieve field-level access control with mongoose.
