### ISSUE TITLE
getter properties disappear when JSON.stringify() or toObject() or lean() is used

### ISSUE THREAD

**Issue by laggingreflex** [Automattic/mongoose#2977]
I have a schema like this

    var Schema = new mongoose.Schema({
        ...
        lastUpdated :{type:Date, get :function(){ return this.array[0].date }},
    });

Now when I get the document, `doc.lastUpdated` shows and works as expected. 

However either `JSON.stringify`ing it or converting it `toObject()`, or even retrieving it with `lean().exec()` makes the property `doc.lastUpdated` disappear!

**Comment by vkarpov15** [comment]
See the `toJSON` options docs here: http://mongoosejs.com/docs/guide.html#toJSON

`Schema.set('toJSON', { getters: true });` should get you the behavior you want
