### ISSUE TITLE
updating deeply nested subdocuments $ operator

### ISSUE THREAD

**Issue by honitus** [Automattic/mongoose#2980]
Apologies, if this is already addressed

Below works
```javascript
/**
    Person.findOneAndUpdate( {"_id": req.body._id, "name._id": req.body.name},
     {"$set": {"name.$.address": '101 1st Ave' },{new: true},
     function (err, workspace) {      if (err) {return handleError(res, err);}
        //return res.send(200);
      }
    );
**/
```
But below doesn't work

```javascript
Person.findOneAndUpdate( {"_id": req.body._id, "name._id": req.body.name},
      {"$set": {"name.$.address.$.zip": '12345' },{new: true},
      function (err, workspace) {
        if (err) {return handleError(res, err);


        }
        //return res.send(200);
      }
    );
```
If I do        $set": {"name.$.address.0.zip": '12345' }      it works and updates 1st element

However, below doesn't work

```javascript
var index = 0;
$set": {"name.$.address.'index'.zip": '12345' }   
```

My understanding is multiple $ operators are not supported. How do you use a second index? In my case I even know the index for 'address' that I need to update. However, substituting the FindOneAndUpdate arguments with variables is not working.

Thanks!

**Comment by vkarpov15** [comment]
```javascript
Person.findOneAndUpdate( {"_id": req.body._id, "name._id": req.body.name},
      {"$set": {"name.$.address." + index + ".zip": '12345' },{new: true},
      function (err, workspace) {
        if (err) {return handleError(res, err);


        }
        //return res.send(200);
      }
    );
```

You are correct that multiple `$` is not supported. Since you know the index, you can just manipulate the string as shown above.

**Comment by honitus** [comment]
@vkarpov15 
Thanks for updating. The syntax {"$set": {"name.$.address." + index + ".zip": '12345' }   does not work.

The error is that a colon (:) operator is expected after "name.$.address."

It appears to me that $set does not like variables in it.

**Comment by honitus** [comment]
var arg = 

     Person.findOneAndUpdate( {"_id": req.body._id, "name._id": req.body.name},
      {"$set": {"name.$.address." + index + ".zip": '12345' },{new: true},
      function (err, workspace) {
        if (err) {return handleError(res, err);


        }
        //return res.send(200);
      }
    );

**Comment by honitus** [comment]
I am able to make it working using the tip here -> http://stackoverflow.com/questions/21592595/how-to-use-variable-mongoose-query
var temp = 1;
var set = {$set: {}};
set.$set["Item.Possess.Jewel." + temp] = 888;
db.collection.update({"ID":"sample"}, set);

Thanks for the help!
