### ISSUE TITLE
Option to disable validation at the save level

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#2981]
Right now only available at schema level, see #2496

**Comment by JaKXz** [comment]
:+1: perhaps `save` can take an options object?

**Comment by vkarpov15** [comment]
`save()` does [take an options argument in 4.x](http://mongoosejs.com/docs/api.html#model_Model-save), it just doesn't let you overwrite the validation logic :)

**Comment by JaKXz** [comment]
I was just looking at that! you beat me to EDIT2 :)
