### ISSUE TITLE
JSON Strinifying Getters of Objects inside Arrays

### ISSUE THREAD

**Issue by alanjames1987** [Automattic/mongoose#2986]
When sending a Mongoose record with Express using `res.json` the getters inside of objects inside of arrays don't get sent. For example, this schema...

```js
var user = new Schema({
    email:String,
    accounts:[{
        name:String,
        brithday:Date,
        age:{
            type:Number,
            get:function(){
                // bad math but it's just an example
                return (new Date() - this.brithday) / 31557600000; 
            }
        }
    }]
}, {
    toJSON:{
        getters:true
    }
});
```

... might output like this ...

```json
"email": "alanjames1987@gmail.com",
"accounts": [{
    "name": "Alan James",
    "brithday": "Sat Nov 28 1987 00:00:00 GMT-0500 (EST)",
}
```

I realize this is because the scheme's `toJSON` method has an override which incorporates the getters, but the object within the array does not.

I believe can fix this by writing my own `toJSON` method in the object within the array, but I would prefer to not have to.

Does Mongoose include some way to include this getter when the object is converted to a JSON string?

**Comment by vkarpov15** [comment]
You can explicitly use `.toJSON({ getters: true });` or create a separate `accountSchema`:

```javascript
var accountSchema = ({
        name:String,
        brithday:Date,
        age:{
            type:Number,
            get:function(){
                // bad math but it's just an example
                return (new Date() - this.brithday) / 31557600000; 
            }
        }
    }, { toJSON: { getters: true } });
```

and then embed that schema in your UserSchema

**Comment by alanjames1987** [comment]
I had to add the `new Schema` but aside from that it worked really well. 

```
var accountSchema = new Schema({
    name: String,
    brithday: Date,
    age: {
        type: Number,
        get: function() {
            // bad math but it's just an example
            return (new Date() - this.brithday) / 31557600000;
        }
    }
}, {
    toJSON: {
        getters: true
    }
});
```

**Comment by rommguy** [comment]
@vkarpov15 still getting this issue, perhaps because my toJSON has a transform function defined

**Comment by vkarpov15** [comment]
Can you provide some code samples please?

**Comment by rommguy** [comment]
Sorry @vkarpov15 I found another way of defining the schema, and don't remember exactly the case I was trying to solve. If it happens again I will post the code here. I deleted my previous comment. Thank you very much for this fantastic library.
