### ISSUE TITLE
Mongoose and CLS

### ISSUE THREAD

**Issue by iliakan** [Automattic/mongoose#2987]
There is a known problem with continuation-local-storage module and mongoose, in details discussed at https://github.com/othiym23/node-continuation-local-storage/issues/6.

To solve, it there should be a place where all callbacks passed to mongoose queries can be wrapped into something like this:
```js
var cls = require('continuation-local-storage')
var ns = cls.getNamespace('app'); 
callback = ns.bind(callback);
```

Currently, I'm doing it like this:
```js
const shimmer = require('shimmer');
const clsNamespace = require('continuation-local-storage').getNamespace('app');

shimmer.wrap(mongoose.Mongoose.prototype.mquery.prototype, '_wrapCallback', function (original) {
  return function(method, callback, queryInfo) {
    callback = clsNamespace.bind(callback);
    return original.call(this, method, callback, queryInfo);
  };
});
```

Will it handle all situations?

**Comment by vkarpov15** [comment]
In theory that would work, but be careful, that's unsupported behavior. `_wrapCallback` may change at any time.

**Comment by iliakan** [comment]
That's exactly why I asked. There are several variants, in mongodb too.

Do you have an idea about a better place for such hook?

**Comment by iliakan** [comment]
Actually, this place is wrong. Update queries don't go through it.

**Comment by iliakan** [comment]
Making 1 more attempt with:
```js
shimmer.wrap(mongoose.Mongoose.prototype.Promise.prototype, 'on', function (original) {
  return function(event, callback) {
    callback = clsNamespace.bind(callback);
    return original.call(this, event, callback);
  };
});
```

**Comment by vkarpov15** [comment]
Could work. I would imagine that once #2688 is in place you could specify your own promises library that also wraps this CLS module for you.

**Comment by iliakan** [comment]
@vkarpov15 native promises are ok in latest v8/iojs. Unhandled Rejections help to fix the "error swalloging" pattern, and modules like CLS/trace/stackup give long stacktrace.

That looks like to be the future and mongoose should orient towards it.

**Comment by vkarpov15** [comment]
Thanks for the opinion :) honestly I'm not a huge fan of promises and never really cared for long stack traces, but maybe I'll warm up to them.

**Comment by iliakan** [comment]
Yeah, ES7 async/await is geared towars implicit promises, so that seems to be the mainstream.

**Comment by emmansun** [comment]
@iliakan , could you help to make one public cls-mongoose module ?

**Comment by iliakan** [comment]
@emmansun Sure, here you go: https://github.com/iliakan/cls-mongoose (cls-mongoose).

Working so far, deployed to prod, still exploring for possible issues.

**Comment by mkeshavgarg** [comment]
try this, works best for this case:
[cls-domains-promise](npmjs.com/package/cls-domains-promise)

**Comment by iliakan** [comment]
@mkeshavgarg, your module fails on tests by @molexx
please see the issue here https://github.com/iliakan/cls-mongoose/issues/3

**Comment by mkeshavgarg** [comment]
@iliakan i have looked into that, as of now i have not supported callbacks.and it works well with promises. Let me know if I am missing something
