### ISSUE TITLE
Sub document refs cannot be retrieved

### ISSUE THREAD

**Issue by doomdagger** [Automattic/mongoose#2988]
#2951 Now I am sure it's a bug in mongoose 4.0.2.

Here is my code:
```javascript
var blogSchema = new mongoose.Schema({
    name: String,
    title: String,
    pet: {type: String, ref: 'Pet'}
});

var petSchema = new mongoose.Schema({
    name: String
});

var Blog = mongoose.model("Blog", blogSchema);
var Pet = mongoose.model("Pet", petSchema);
```

If I do the following, I will have this issue:
```javascript
var pet = new Pet({name: "huhu"});
var blog = new Blog({name: "haha", title: "gulu", pet: pet});

blog.save().then(function (doc) {
    console.log(doc);
    // { __v: 0, pet: { name: 'huhu', _id: 555424f98b8b32081cf1ab88 }, name: 'haha', title: 'gulu', _id: 555424f98b8b32081cf1ab89 }
    
    Blog.findOne().then(function (found) {
         console.log(found);
         // I cannot get the path `pet`
         // { _id: 555424f98b8b32081cf1ab89 , name: 'haha', title: 'gulu', __v: 0 }
    });
});
```

I found out that even my blogSchema defined that I want use String on path pet, the database uses ObjectId.
![image](https://cloud.githubusercontent.com/assets/6743894/7626160/eed77256-fa35-11e4-821c-6fb6a15bffd7.png)

But if I try this, this issue won't come out, and I can retrieve the pet path:
```javascript
var blog = new Blog({name: "haha", title: "gulu", pet: pet._id});
```
`pet._id` will be cast into String, and then saved into the database. I think it is due to the type mismatch caused the sub-document cannot be retrieved. And this logic can be accepted to some degree. However, when inserting the document with sub document model, mongoose may forget to cast the ObjectId into String according to user's schema definition.

**Comment by doomdagger** [comment]
I want to add some more issues about sub document. 
```javascript
var blogSchema = new Schema({
    name: String,
    title: String,
    // if I use array this time for the path pet
    pet: [{type: String, ref: 'Pet'}]
});

var pet = new Pet({name: "huhu"});
var blog = new Blog({name: "haha", title: "gulu", pet: [pet]});

// then I get this
console.log(blog);
// { name: 'haha', title: 'gulu',  _id: 55542be0c6dfbd9c190e6025, pet: [ '{ name: \'huhu\', _id: 55542be0c6dfbd9c190e6024 }' ] }
// It cast my whole object into json String. 
```
This won't happen if do not use array for path 'pet'. Is it designed to do so, or not?

**Comment by vkarpov15** [comment]
Have you tried this in 4.0.3? One of the other users on #2951 noticed that 4.0.3 fixed this issue.

**Comment by doomdagger** [comment]
Yes, I have tried in 4.0.3. Apparently mongoose still cannot fetch sub documents in type mis-match condition.
