### ISSUE TITLE
toJSON on sub-document is not called

### ISSUE THREAD

**Issue by jsedlacek** [Automattic/mongoose#2990]
There is a regression in mongoose 4.0.3: parent's `toJSON` is called instead of sub-document's one.

Here is a test-case:
```js
var childSchema = new Schema({ name: 'string' });
childSchema.options.toJSON = {
  transform: function(doc) {
    return doc.name;
  }
};
sinon.spy(childSchema.options.toJSON, "transform");

var parentSchema = new Schema({
  children: [childSchema]
});
parentSchema.options.toJSON = {
  transform: function(doc, ret, options) {
    delete ret._id;
  }
};
sinon.spy(parentSchema.options.toJSON, "transform");

var Parent = mongoose.model('Parent', parentSchema);

var parent = new Parent({ children: [{ name: 'Matt' }, { name: 'Sarah' }] })
var json = JSON.stringify({parent: parent});

assert.equal(json, '{"parent":{"children":["Matt","Sarah"]}}');
assert.equal(parentSchema.options.toJSON.transform.callCount, 1, 'Parrent toJSON called count');
assert.equal(childSchema.options.toJSON.transform.callCount, 2, 'Child toJSON called count');
```

This test passes on mongoose 4.0.2, but fails on 4.0.3 with the following result.
```
AssertionError: expected `'{"parent":{"children":[{"name":"Matt"},{"name":"Sarah"}]}}'` to equal `'{"parent":{"children":["Matt","Sarah"]}}'`

AssertionError: Parrent toJSON called count: expected 3 to equal 1

AssertionError: Child toJSON called count: expected 0 to equal 2
```

**Comment by jsedlacek** [comment]
The same regression is present on the latest release of 3.8 branch (3.8.28).

**Comment by jsedlacek** [comment]
I went through the change log and it seems to be related to #2940. /cc @vkarpov15

**Comment by vkarpov15** [comment]
Thanks for pointing this out. As a workaround you can just use `JSON.stringify(doc.toObject({ transform: true }));`

**Comment by jsedlacek** [comment]
@vkarpov15 thanks for the workaround, it seems to works fine :)

**Comment by creynders** [comment]
@vkarpov15 I don't get it, what does `doc` refer to in your workaround? The parent document?  No matter what I do, I can't get the populated fields to have their transformations applied to. This is with 3/8/28 BTW

**Comment by vkarpov15** [comment]
Hmm @creynders can you show me your code? In my example, doc refers to whatever document you're trying to `stringify()`.

**Comment by vkarpov15** [comment]
Fixed for next release. Apparently when you call `JSON.stringify({ parent: doc });` JavaScript calls `toJSON('parent');` because 'parent' is the key name, so mongoose was mistakenly treating 'parent' as an option parameter. Here's [the relevant section of the ES5 spec](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.44).

Adjusted workaround until 3.8.29 is released: `var json = JSON.stringify({ parent: parent.toJSON() });`

**Comment by jsedlacek** [comment]
Thanks for such a quick fix @vkarpov15!!

**Comment by creynders** [comment]
:cake: and :beers: @vkarpov15 Thanks for the extremely quick fix!
