### ISSUE TITLE
findOneAndUpdate overwriting attributes in 2+ level deep object passed as doc

### ISSUE THREAD

**Issue by bmpasini** [Automattic/mongoose#2991]
Let's say I have this schema:

    var UserSchema = new Schema({
        name : {
            firstName : String,
            lastName : String
        }
    });

And I create this user:

    User.create({
		name : {
            firstName : Bob,
            lastName : Marley
        }
	}, function (err, user) {
		if(err) {
			return console.error(err);
		} else {
			return console.log(user);
		}
	});

I noticed that if I do this:

    User.findOneAndUpdate({_id: userId}, { name: { firstName : "Damian" } }, function (err, user) {
		if(err) {
			return console.error(err);
		} else {
			return console.log(user);
		}
	});

My user now is:

    user = {
        name : {
            firstName : "Damian"
        }
    }

However, if I do this:

    User.findOneAndUpdate({_id: userId}, { "name.firstName" : "Damian" }, function (err, user) {
		if(err) {
			return console.error(err);
		} else {
			return console.log(user);
		}
	});

My user is:

    user = {
        name : {
            firstName : "Damian",
            lastName : "Marley"
        }
    }

Is there a way to pass an Object with not all of its attributes filled out to `findOneAndUpdate`, and keep the attributes that were there before, without getting rid of them? (same functionality as `$set` in Mongo). This is really annoying...

**Comment by dozoisch** [comment]
By the way, you can use the `$set` directly in the second parameter.

**Comment by vkarpov15** [comment]
The second way you specified is the only way as far as I know. Explicitly specifying `name.firstName` is the way to go. That's how the mongodb server works right now and really has nothing to do with mongoose.
