### ISSUE TITLE
Query#then conflicts with Promise library

### ISSUE THREAD

**Issue by alancasagrande** [Automattic/mongoose#2995]
Found this when migrating from 3.8.x to 4.0.x. I'm using RSVP for promises, and when I resolve a promise with a Query object, the query is executed and I get the result instead of the object. This is happening because RSVP looks for the .then() method, and not whether the object is a RSVP Promise. I think that's by design, so it can work well with other Promise implementations.

In my case I need to modify the query (pagination, custom filtering) based on async operations.

Just wanted to check if it's working as intended, or if this use case wasn't taken into account.

```javascript
var mongoose = require('mongoose');
var RSVP = require('rsvp');

mongoose.connect('mongodb://localhost/promise');

var userSchema = mongoose.Schema({
  name: String
});

var User = mongoose.model('User', userSchema);

User.create({ name: 'John' }).then(function () {
  return new RSVP.Promise(function (resolve) {
    var query = User.find();
    console.log(query instanceof mongoose.Query); // true
    resolve(query);
  }).then(function (query) {
    console.log(query instanceof mongoose.Query); // false
    process.exit();
  });
});
```

**Comment by vkarpov15** [comment]
That's because newer versions of mquery have a `.then()` function. Unfortunately this is by design precisely so that the 2nd `.then()` above gets the query result rather than the query. There are two workarounds, neither of which is pleasant:

1) Keep query outside of the promise chain and don't return it.
2) `delete query.then;`

**Comment by benjamingr** [comment]
Your code has the explicit construction anti-pattern and is not using idiomatic promises code. 
If you want to resolve a promise with a `then`able (anything with a `then`) but not unwrap it to get the value (which is what you usually want) the easiest thing would be to return a wrapper:

    resolve({query: query})

**Comment by alancasagrande** [comment]
Yes I didn't need to create a promise explicitly. It's just an example to demonstrate that resolving a promise with a query now gives you the result, not the query, which didn't happen before because `Query#then` didn't exist. The wrapper seems to be the best option in this case.

**Comment by vkarpov15** [comment]
I'm going to re-open this so I can add a note to the documentation. Re: my comments on https://github.com/aheckmann/mquery/commit/3cca43758f1e9905f79ce368dd88240f30665311, this change is pretty dangerous and can have some unintentional side effects like doubling every single operation with `Q.ninvoke()`.

**Comment by wavded** [comment]
Just was bitten by this one in 4.0.6, having a `then` on that query object causing some surprisingly hard to catch errors.  In my case I was using ES7 `async/await` and babel.  I ended up wrapping it in an array to get around it.
