### ISSUE TITLE
Export document provider

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#2996]
Could lib/document_provider.js be exported?

I'm building a plugin that should work on the browser too and I need to import the `Document` module but only the server version is exported

**Comment by vkarpov15** [comment]
Will be included for 4.1. Thanks for the suggestion :) Can you tell me a little more about the plugin?

**Comment by paglias** [comment]
Thank you :)

It's the dictionary-like type that is discussed here https://github.com/Automattic/mongoose/issues/2376

I'm trying to adapt Document Array and Embedded doc to work with it, but unless it's needed in the project I'm working on I'm not sure it will support every use case. If it's stable enough probably we're going to release it.

But Mongoose's internals are quite complicate :)

**Comment by vkarpov15** [comment]
Hmm I'm curious, what are you doing to adapt document array and embedded doc? In theory, if you're adding a new type, you shouldn't have to change those.

**Comment by paglias** [comment]
@vkarpov15 sorry, I didn't explain very well. I'm not going to modify directly those types but I'm trying to use a similar approach and I need to use `mongoose.Document` in order to create a sort of EmbeddedDocument that will work with objects instead of arrays

**Comment by paglias** [comment]
@vkarpov15 I know it's not the best place but I'm a bit stuck right now.

When I create a model with my custom type used in a field why isn't `.cast` called? I don't find which method I should use to handle a field when a new model is created, `cast` is called when returning a document from the db but not when creating a new one

**Comment by vkarpov15** [comment]
Are you using an array? The relevant code for calling cast() is here: https://github.com/Automattic/mongoose/blob/1c89eaab434426946046cb8ea5d55a1f4effdbc4/lib/schematype.js#L548-581, but it has a little magic when it comes to setters and arrays.

Could you show me the code you have so far? I'd love to see this plugin work but it's hard to translate prose into code :)

**Comment by paglias** [comment]
@vkarpov15 sure, I'm a bit stuck right now to be honest, this is the code I have so far https://gist.github.com/paglias/ec64777d048f9777a89a

The blockers right now are:

1. When the document is created as in the `test.js` file I don't find a way to intercept it in my schema and cast it to the right value. `cast` is called when fetching documents from the db but not when creating it. The only function called is the one passed to `this.default` https://gist.github.com/paglias/ec64777d048f9777a89a#file-dictionary-js-L38 but I want to intercept the real value passed when the model is created. If I remove those lines (`this.defaults(...`) the field is completely ignored and doesn't appear when passing the document to console.log (https://gist.github.com/paglias/ec64777d048f9777a89a#file-test-js-L30).

2. I just realized that in order to have methods accessible on the field I need to return a new type like `MongooseArray`. Specifically i need to have to methods ($add and $remove) avalaible on the dictionary fields to add new keys to it, compile the fields as a sub document and mark the right path as modified. But at the same time I should still be able to iterate over the normal keys of the dictionary, so i need to distinguish between keys on the dictionary and utility methods. I can easily do a check when converting `toObject` but would like to mantain the ability to iterate over the 'real' keys too

Thanks for your help :)

**Comment by paglias** [comment]
@vkarpov15 another thing, here https://github.com/Automattic/mongoose/blob/master/lib/types/array.js#L36 when creating a document with an array is always `undefined` but then if I push something to the array, `_markModified` uses `this._parent` and it's not undefined anymore. But I can't find where it's setting the value of `_parent`. In `schema.cast` when initializing a document is undefined

**Comment by paglias** [comment]
I got something working: https://github.com/HabitRPG/mongoose-dictionary

it works with a script like this one https://gist.github.com/paglias/bbb062b3b7c6da3e4bfc

But there are a few things that I really can't get to work:

- Saving the document returns a `segmentation faul (core dump)` 
- There's no way to supply a value on creation or to load a value from the db because the default empty dictionary always override whatever value you pass to it (https://github.com/HabitRPG/mongoose-dictionary/blob/master/lib/schemaDictionary.js#L40) but if I remove those lines then `cast` is not called
- When creating the document, there's no way of accessing the parent doc (it's `undefined`) and conseguently I don't know how to set a path as modified on the parent when it's passed during creation. See https://github.com/Automattic/mongoose/issues/2996#issuecomment-103806767

**Comment by vkarpov15** [comment]
Hmm I think you're trying too hard to work against mongoose's internals instead of working with them. I would imagine it would be much more straightforward to just implement a dictionary type that fulfills a similar API to SchemaBoolean: https://github.com/Automattic/mongoose/blob/master/lib/schema/boolean.js . Basically just a constructor, `checkRequired`, `cast`, and `castForQuery`. Would this work for your case?

**Comment by paglias** [comment]
The problem is, I need to have methods to add/remove keys from the dictionary and from the subdocs to mark the parent as modified. How could it be done with a type like SchemaBoolean?

Also, what's the use of `castForQuery`?

**Comment by vkarpov15** [comment]
Hmm not sure. I'll play around with it tomorrow and see what I can come up with.

And `castForQuery` is exactly what it sounds like - this is what mongoose calls when you do a query on a field with dictionary type. For instance

```javascript
var mySchema = new mongoose.Schema({
  title     : String,
  dictionary: {
    type: Dictionary,
    schema: {
      dictionaryString: {
        type: String,
        default: 'Default value'
      }
    }
  }
});

//...

MyModel.find({ dictionary: { key: 'value' } }).exec(callback); // Call Dictionary type's `castForQuery`
```

**Comment by paglias** [comment]
@vkarpov15 thanks once again.

I fixed a few things and now I'm able to retrieve docs correctly from the db. The big problem is saving, both existing documents and new ones. I added all the info and examples I could create here https://github.com/HabitRPG/mongoose-dictionary

**Comment by paglias** [comment]
In the end I went with a plugin https://github.com/HabitRPG/mongoose-dictionary/tree/plugin, still a bit hacky but at least is working and the code has been reduced a lot
