### ISSUE TITLE
Allow return result from middlewares

### ISSUE THREAD

**Issue by joesonw** [Automattic/mongoose#2998]
I'm trying to implement a cache proxy using redis.
So I tried middlewares:
```javascript
schema.pre('find',function(next) {
   
    next(null,result);
    //The missing part is here, It only allows me to resume the procedure instead of interrupting it.
});
```

**Comment by vkarpov15** [comment]
There's no real way to do this right now. Kareem may support passing parameters between middleware in the future, but it will not support passing parameters from middleware to the actual function. Instead I'd recommend you add some data to the query object, which is accessible as `this` in query middleware:

```javascript
schema.pre('find', function(next) {
  this._cache = this._cache || {};
  loadDataFromRedis(function() {
    this._cache.data = /* data from redis */;
    next();
  });
});
```

**Comment by joesonw** [comment]
@vkarpov15 Yeah. but this would still perform the query. I checked out some other mongoose cache projects. They modified the Query project after connection was made, before adding the models. I simply replaced the `Query#exec` method
