### ISSUE TITLE
Clarify mongos option and poolSize options in docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3000]
See http://mongoosejs.com/docs/connections.html and #2968

**Comment by chaines** [comment]
Is it better to clarify the docs, or modify the actual functionality to match that in the docs? I feel like the way the option works in the docs is a lot clearer than the actual implementation, and as far as I can tell it would be a fairly simple fix to make the code match the docs.

**Comment by vkarpov15** [comment]
The problem is that mongoose defers to the underlying driver in regards to processing the `mongos` option, and mongoose already does too much in terms of working against the driver's connection logic. The driver's connection logic is spec-ed out and more heavily tested, whereas mongoose's is the wild west in comparison atm. Also, changing this logic could qualify as a backwards-breaking change depending on the implementation. I'd rather defer down where possible when connections are concerned, unless there's an overwhelming reason to add this behavior.
