### ISSUE TITLE
Mongoose: select method does not return the include field

### ISSUE THREAD

**Issue by richzw** [Automattic/mongoose#3001]
I have one document like that

``` javascript
var ConfigSchema = new Schema({
  basicConfig: {
    levelId: {
      type: Number,
      required: true
    },
    hostId: {
      type: Number,
      required: true
    },
    Name: {
      type: String,
      trim: true
    },
    Settings: {
      Type1: {
         // some types here...
      }
      Type2: {
         // some types here...
      }
    }
  },
  enrolls: {
    name: {type: String},
    list: [String]
  },
  awards: {
    enable: {type: Boolean},
    Primary: {
      amount: {type: Number},
      type: {type: String}
    }
  }
```

Now I want to find `configs` with `hostId` matches `60`, and selecting `basicConfig` field.

``` javascript
Config.findOne({ 'basicConfig.hostId': 60 })
    .select('basicConfig').exec(function(err, configs) {
        if (err) {
            console.error(err);
            return ;
        }

        console.log(configs);   
    });
```

However, all fields of this document will be returned. It seems that the select does NOT work? Why?

Also, those following codes have been test, it does not work.

``` javascript
BonusConfig.findOne({ 'basicConfig.hostId': 60 }, 'basicConfig', function(err, configs) {
        if (err) {
            console.error(err);
            return ;
        }
        console.log(configs);
    });
```

But, without the `basicConfig` field with select with the following codes, it work well.

``` javascript
BonusConfig.findOne({ 'basicConfig.hostId': 60 })
    .select('-basicConfig').exec(function(err, configs) {
        if (err) {
            console.error(err);
            return ;
        }
        console.log(configs);
    });
```

What's wrong with my codes?

Mongoose version: 3.8.24

Mongodb version: 2.6.7

**Comment by vkarpov15** [comment]
Hmm so the first way should work. Can you enable mongoose debug mode and show me the query that's being sent to the server? `require('mongoose').set('debug', true);`

As a workaround, 

```javascript
Config.findOne({ 'basicConfig.hostId': 60 }, { basicConfig: 1 }).exec(function(err, configs) {
        if (err) {
            console.error(err);
            return ;
        }

        console.log(configs);   
    });
```

should work

**Comment by richzw** [comment]
hi @vkarpov15 

Here is the query log under mongoose debug mode.

`Mongoose: configs.findOne({ 'basicConfig.hostId': 60 }) { fields: { basicConfig: 1 } }`

**Comment by richzw** [comment]
The following command used in the mongo client, it can get the `basicConfig` field correctly.

> `db.configs.find({'basicConfig.hostId': 60}, {'basicConfig':1})`

**Comment by richzw** [comment]
**Update**

After further investigation.

The output result of `Config.findOne({ 'basicConfig.hostId': 60 }).select('basicConfig')`:

```javascript
{ _id: 555c4144c0bff1541d0e4059,
  enrolls: {},
  awards: { primary: { PrimarySettings: {}, primaryAck: {} } },
  basicConfig:
   { levelId: 24,
     hostId: 60,
     poolName: 'LC' } }
```

Other fields are `empty value` except `basicConfig`. However, I want the result is

```javascript
{ _id: 555c4144c0bff1541d0e4059,
  basicConfig:
   { levelId: 24,
     hostId: 60,
     poolName: 'LC' } }
```

**Comment by vkarpov15** [comment]
Ah-hah, that makes sense, this is just another manifestation of #2503. This behavior is by design, but admittedly it's not very well-designed. Mongoose is over-eager when it comes to creating sub-docs when loading from the database. Planning on changing that in v5.

**Comment by vkarpov15** [comment]
Upon further investigation, this is not something mongoose can support without introducing some baffling behavior. See https://github.com/Automattic/mongoose/issues/5310#issuecomment-307666824 for more detail. https://github.com/Automattic/mongoose/issues/5369 will be the workaround we go with.
