### ISSUE TITLE
node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build/Release/bson.node: undefined symbol: node_module_register] js-bson: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by gbansal7** [Automattic/mongoose#3002]
Hi, 

I am getting this error. Please help me to resolve this. I am using mongoose with Mean.io.

Thanks
Gaurav

**Comment by vkarpov15** [comment]
Looks like it was fixed in #2718 re: your comment https://github.com/Automattic/mongoose/issues/2718#issuecomment-103860265. Re-open if you're still having this issue
