### ISSUE TITLE
Init middleware supplies a document with no values

### ISSUE THREAD

**Issue by sabrehagen** [Automattic/mongoose#3007]
In mongoose 3.8.27 the schema.post('init') function supplies a fully populated document (keys and values), however in mongoose 4.0.2 and 4.0.3 the schema.post('init') function supplies a document with the correct keys, but empty values.

**Comment by vkarpov15** [comment]
Hmm that's strange, can you show me a code example that reproduces what you're seeing? There were some related issues in 4.0.2 re: #2949, etc. but they should have been fixed for 4.0.3...

**Comment by sabrehagen** [comment]
When attempting to test against 4.0.3 it seems I managed to test against 4.0.2 - sorry for the issue, fixed in the latest version as expected!
