### ISSUE TITLE
model.select brings _id even when it's select:false

### ISSUE THREAD

**Issue by lucasmciruzzi** [Automattic/mongoose#3010]
So, I have an Schema like this:

````javascript
var Schema = mongoose.Schema,
	ObjectId = Schema.ObjectId;

var User = new Schema({
	_id: {
		select: false,
		type: ObjectId,
		default: mongoose.Types.ObjectId
	},
	__v: {
		select: false,
		type: Number	
	},
	username: string
});
````

When I do a find, it gets the correct results (something like `{"username":"lucasmciruzzi"}`), but when I use the select function I get the unselected _id:

**Code:**
````javascript
userModel.find({}).select({username:1});
// or
userModel.find({}).select("username");
````

**Output:**
````json
{
	"username": "lucasmciruzzi",
	"_id": "[theID]"
}
````

If id is set to `select: false` it should stay that way. Am I doing something wrong, or is this a bug of mongoose?

**Comment by vkarpov15** [comment]
Possibly a bug, can you confirm which version of mongoose?

**Comment by lucasmciruzzi** [comment]
Sure thing: 4.0.1

**Comment by lucasmciruzzi** [comment]
Great! Thanks!
