### ISSUE TITLE
Mongoose upsert does not create default schema property

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#3011]
Example document Schema:

    var CompanySchema = Schema({
        created: { type: Date, default: Date.now },
        modified: { type: Date, default: Date.now },
        address: { type: String, required:true },
        name: { type: String, required:true }
    });

I'm using a common request handler for edit and create of "Company" documents:

    exports.upsert = function(req, res, next) {
        var company = {
            name: req.body.name,
            address: req.body.address
        };
        var id = req.body.id || new mongoose.Types.ObjectId();
        var queryOptions = {
            upsert: true
        };
        Company.findByIdAndUpdate(id, company, queryOptions).exec(function(error, result) {
            if (err) return next(error);
            return res.json(result);
        });
    };

But using this method, when a new document is inserted, created, modified properties are not saved with default values of Date.now. Now I can call Company.create depending on the existence of an id but I'm wondering why upsert does not use default values if a property does not exist on a new document?

**Comment by vkarpov15** [comment]
Because findByIdAndUpdate doesn't create a document on the mongoose side. In 4.0.x you can specify the 'setDefaultsOnInsert' option when you specify upsert: true which will attach defaults for you. Just be careful if you're using the this keyword in a default function, that won't work with 'setDefaultsOnInsert'

**Comment by skotchio** [comment]
Thanks for the answer
