### ISSUE TITLE
Multiple update queries in one roundtrip

### ISSUE THREAD

**Issue by shaharlinial** [Automattic/mongoose#3014]
Apologies if this has been addressed,

So the problem as follows:
I had an issue with my schema which led me to ask a question on stackoverflow:
(Below there is a short version of the question)[Question on StackOverflow](http://stackoverflow.com/questions/30442638/conditional-update-mongodb-set-and-addtoset)

This is the schema:

    uid:{type:ObjectId},
    username: {type: String, unique: true, required: true},
    devices: [
        {
            ip:{type:String},
            meta:{type:String},
            type: {type: String, default: 'none', enum: ['android', 'ios', 'web', 'none']},
            cnuid: {type: String},
            uuid:{type:String, unique:true}
        }
    ]

These are the rules:
**UUID** is a unique and one time created per device.

**CNUID** is a unique number also, but consider it as a token, which means it updates from time to time.

*If username does not exist, create a username and attach its device to this array,*
*If it exists try to attach this device to the array, as long as there isn't a uuid like this already,*
*If there is a uuid like this overwrite the cnuid with the cnuid provided.*

Apparently the only solution for this according to the answer, and to the fact that you can't use $set and $addToSet on the same attribute([Feature request on Mongodb Jira](https://jira.mongodb.org/browse/SERVER-6566)), is that you must run 3 Idempotence queries.

which are explained here [StackOverflow Answer for the issue above](http://stackoverflow.com/questions/30292159/update-a-mongodb-subdocument-when-the-parent-document-might-not-exist)

What's left for me is to perform those 3 queries in one update command by db.
I'm kinda trying to avoid using the native driver.

This is the straight db.update command : 
Explained here [MongoDB Update](http://docs.mongodb.org/manual/reference/command/update/#dbcmd.update)
and looks like so:

    {
        update: <collection>,
        updates:
        [
            { q: <query>, u: <update>, upsert: <boolean>, multi: <boolean> },
            { q: <query>, u: <update>, upsert: <boolean>, multi: <boolean> },
            { q: <query>, u: <update>, upsert: <boolean>, multi: <boolean> },
            ...
        ],
        ordered: <boolean>,
        writeConcern: { <write concern> }
    }

Is this already something you are familiar with?

**Comment by vkarpov15** [comment]
Right now the only real way is to use the driver unfortunately, mquery doesn't quite support the new-style MongoDB CRUD API.

**Comment by shaharlinial** [comment]
Is it still possible to access the driver through Mongoose?

**Comment by vkarpov15** [comment]
`MyModel.collection.updateMany();` http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#updateMany

**Comment by shaharlinial** [comment]
This can't be really done with `updateMany();` update many supports in one query to fetch more than one document.

In my case I have to use multiple queries which are different from one another,

**Comment by vkarpov15** [comment]
Given your use case, it may make sense to have a separate collection of devices - enforcing an upsert-like constraint in mongodb arrays is not something you can easily do. If you make a separate `devices` collection you can pretty easily do what you're trying to do with 2 `findOneAndUpdate()` calls

**Comment by shaharlinial** [comment]
Yes, I actually can change it to a collection of `devices` given for example like this:

    {
        username: {type: String, unique: true, required: true},
        ip:{type:String},
        meta:{type:String},
        type: {type: String, default: 'none', enum: ['android', 'ios', 'web', 'none']},
        cnuid: {type: String},
        uuid:{type:String, unique:true}
    }


And it can actually be done in **one** query, while all of the rules above apply:

    device.findOneAndUpdate(
        {
            username:userDevice.username,
            uuid:userDevice.uuid
        },
        {
            $set:{cnuid:userDevice.cnuid},
            $setOnInsert:{username:userDevice.username,uuid:userDevice.uuid}
        },
        {upsert:true}
    )
