### ISSUE TITLE
Sending ObjectId to Model.remove method removes all documents

### ISSUE THREAD

**Issue by bobmoff** [Automattic/mongoose#3015]
Perhaps this should throw an error if its not allowed, seem scary that it will simply remove every document in that collection.

I am using 4.0.3

**Comment by vkarpov15** [comment]
Can you show me a code example? I think I know what you're talking about, but translating prose to code is error-prone.

**Comment by bobmoff** [comment]
I tried creating a small example, but failed. It must be that I acctually didnt send an ObjectID, but probably was feeding the remove method UNDEFINED which will have the same effect as giving it NO parameters. So, sorry for making non-validated issues and good that you questioned it. Thx!

Now I got the error:
MongoError: wrong type for 'q' field, expected object, found q: ObjectId('55675f6063002d0b3895cbf0')
