### ISSUE TITLE
hard to find all the query conditions documented

### ISSUE THREAD

**Issue by mgenev** [Automattic/mongoose#3016]
Several places in the documentation refer to the `conditions` but I don't see  a place where all possible conditions and using them for query building are listed. Are they a complete analog to mongo? If so maybe that's worth mentioning. Maybe this stuff exists, but hard to see? I've been over the docs many times and can't find it...

**Comment by vkarpov15** [comment]
Do you mean `conditions` as in the parameter you pass to `update()`, `find()`, etc.?

**Comment by mgenev** [comment]
Yes. The ones referred to here: http://mongoosejs.com/docs/queries.html
> Queries
> Documents can be retrieved through several static helper methods of models.
> Any model method which involves specifying query conditions can be executed two ways:
