### ISSUE TITLE
undefined is not a function  :: TypeError: undefined is not a function,     at model.emit (events.js:98:17),     at model.save 

### ISSUE THREAD

**Issue by Niteesh** [Automattic/mongoose#3017]
M not able to get subdocument  in the following schema

schema = mongoose.Schema ({
    name: {type: String, required: true},
    description: {type: String, required: true},
    members: [{type: Schema.ObjectId, ref: 'Users'}],
    invitations: [{type: Schema.ObjectId, ref: 'Users'}],
    admin: [{type: Schema.ObjectId, ref: 'Users'}],
    domain: {type: String, required: true},
    teams: [{type: Schema.ObjectId, ref: 'teams'}],
    userPermission : [{
      user :{type: Schema.ObjectId, ref: 'OAuthUsers'},
      center : [{type: Schema.ObjectId, ref: 'centers'}]
    }]
  } );

error: uncaughtException: undefined is not a function date=Wed May 27 2015 12:19:24 GMT+0530 (IST), pid=94102, uid=501, gid=20, cwd=/Users/niteesh/Documents/projects/grooformBuilder, execPath=/usr/local/Cellar/node/0.12.2_1/bin/node, version=v0.12.2, argv=[/usr/local/bin/node, /Users/niteesh/Documents/projects/grooformBuilder/src/index.js], rss=106758144, heapTotal=106091520, heapUsed=51746576, loadavg=[3.48291015625, 3.126953125, 3.06591796875], uptime=471145, trace=[column=17, file=events.js, function=model.emit, line=98, method=emit, native=false, column=10, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js, function=model.save, line=225, method=save, native=false, column=24, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=model._done, line=59, method=_done, native=false, column=28, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=_next, line=52, method=null, native=false, column=8, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=fnWrapper, line=159, method=null, native=false, column=5, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=complete, line=992, method=null, native=false, column=20, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=null, line=983, method=null, native=false, column=24, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js, function=null, line=79, method=null, native=false, column=22, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schematype.js, function=DocumentArray.SchemaType.doValidate, line=603, method=SchemaType.doValidate, native=false, column=35, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js, function=DocumentArray.doValidate, line=73, method=doValidate, native=false, column=9, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=null, line=974, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[TypeError: undefined is not a function,     at model.emit (events.js:98:17),     at model.save (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js:225:10),     at model._done (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:59:24),     at _next (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:52:28),     at fnWrapper (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:159:8),     at complete (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:992:5),     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:983:20,     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js:79:24,     at DocumentArray.SchemaType.doValidate (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schematype.js:603:22),     at DocumentArray.doValidate (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js:73:35),     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:974:9,     at process._tickCallback (node.js:355:11)]
error: uncaughtException: undefined is not a function date=Wed May 27 2015 12:19:24 GMT+0530 (IST), pid=94102, uid=501, gid=20, cwd=/Users/niteesh/Documents/projects/grooformBuilder, execPath=/usr/local/Cellar/node/0.12.2_1/bin/node, version=v0.12.2, argv=[/usr/local/bin/node, /Users/niteesh/Documents/projects/grooformBuilder/src/index.js], rss=107069440, heapTotal=107111424, heapUsed=52397024, loadavg=[3.48291015625, 3.126953125, 3.06591796875], uptime=471145, trace=[column=17, file=events.js, function=model.emit, line=98, method=emit, native=false, column=10, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js, function=handleSave, line=132, method=null, native=false, column=16, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/utils.js, function=null, line=408, method=null, native=false, column=7, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js, function=model.save, line=222, method=save, native=false, column=24, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=model._done, line=59, method=_done, native=false, column=28, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=_next, line=52, method=null, native=false, column=8, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js, function=fnWrapper, line=159, method=null, native=false, column=5, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=complete, line=992, method=null, native=false, column=20, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=null, line=983, method=null, native=false, column=24, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js, function=null, line=79, method=null, native=false, column=22, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schematype.js, function=DocumentArray.SchemaType.doValidate, line=603, method=SchemaType.doValidate, native=false, column=35, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js, function=DocumentArray.doValidate, line=73, method=doValidate, native=false, column=9, file=/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js, function=null, line=974, method=null, native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[TypeError: undefined is not a function,     at model.emit (events.js:98:17),     at handleSave (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js:132:10),     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/utils.js:408:16,     at model.save (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/model.js:222:7),     at model._done (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:59:24),     at _next (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:52:28),     at fnWrapper (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/node_modules/hooks/hooks.js:159:8),     at complete (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:992:5),     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:983:20,     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js:79:24,     at DocumentArray.SchemaType.doValidate (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schematype.js:603:22),     at DocumentArray.doValidate (/Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/schema/documentarray.js:73:35),     at /Users/niteesh/Documents/projects/grooformBuilder/node_modules/mongoose/lib/document.js:974:9,     at process._tickCallback (node.js:355:11)]

**Comment by vkarpov15** [comment]
Hi,

Can you show me the code you're using to trigger this error? It doesn't look like something that happens when you're declaring a new schema.
