### ISSUE TITLE
JSON.stringify leads to error after upgrade to 3.8.28

### ISSUE THREAD

**Issue by mbernath** [Automattic/mongoose#3018]
Moved from #2910 to a seperate issue here.

I upgraded from 3.8.27 to 3.8.28 and when JSON.stringifying a document this leads to an error that reproducibly does not occur with 3.8.27.

The relevant stack trace is:

    TypeError: Object #<Object> has no method 'get'
            at Object.nested.toObject (.../node_modules/mongoose/lib/document.js:1214:27)
            at Object.stringify (native)

The document that was JSON.stringified was populated and the populated document contains a nested object (see following example). When I debugged, it seems to me that the error occurs with the nested document.

    // A "normal" Mongoose document
    {
      ...
      profiles: [{      // <-- These documents were populated
        address: {    // <-- Error occurs with this nested object
          street: "...",
          town: "...",
          zip: "...",
          ...
        }
      }
      ]
    }

I haven't found the time yet to write a simplified piece of code to reproduce this error, but will try within the next days. For now I reverted to 3.8.27.

@vkarpov15 I also haven't had the chance to test if it happens with toObject as well yet.

**Comment by neeharv** [comment]
+1.

**Comment by vkarpov15** [comment]
Hmm so there was an issue in 3.8.28 that will hopefully be fixed when I release 3.8.29 later today, see #2990. I suspect that will fix this.

**Comment by neeharv** [comment]
@vkarpov15 Just tested with 3.8.29, still persists. Doing a JSON.stringify() on a doc with sub documents still causes the following error : 

```TypeError: undefined is not a function 
at Object.defineProperty.get.nested.toObject ```

**Comment by t1bb4r** [comment]
I'm not sure if this is the same issue, but I get the following unexpected behaviour:
model.toJSON does not call model.toObject since I upgraded from .27 to .28. For example in mongoose 3.8.28:
```
var blogSchema = new Schema({
  title:  String,
});

var _toObject = blogSchema.methods.toObject;
blogSchema.methods.toObject = function() {
  console.log('toObject!');
  return {};
}

var Blog = mongoose.model('Blog', blogSchema);

var blog = new Blog();
console.log(blog.toJSON(), blog.toObject())
```
output:
```
toObject!
{ _id: 5582cdb25d6c31001698d429 } {}
```
expected output (3.8.27)
```
toObject!
toObject!
{} {}
```

**Comment by vkarpov15** [comment]
Glad you figured it out @t1bb4r. `toJSON` calling `toObject` was an internal design decision that lead to some really nasty edge cases with `toJSON`, was not really considered supported behavior. In a recent release we switched over to using the internal `$toObject()` helper for both to ensure consistent behavior between the two.

**Comment by vkarpov15** [comment]
I suspect this issue is fixed, re-open if its still an issue.
