### ISSUE TITLE
How to properly handle connection issues?

### ISSUE THREAD

**Issue by cappslock** [Automattic/mongoose#3019]
I'm having a lot of trouble implementing the following using the out-of-box options:

- attempt reconnect `x` times with interval `y` when initial connection fails or is lost
- crash when number of tries has been exhausted

I can do this myself of course, but seeing as dependent libraries seem to offer options for this behavior, I feel like it should be possible somehow.

Is there a good strategy for doing this?

**Comment by vkarpov15** [comment]
Mongoose and the underlying node driver do auto reconnect by default, see http://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/ . You should be able to set the `numberOfRetries` and `retryMiliSeconds` properties on `db` connection options:

```javascript
var db = mongoose.createConnection(uri, { db: { numberOfRetries: x, retryMiliseconds: y } });
```

I think that should work

**Comment by dchekanov** [comment]
`numberOfRetries` doesn't apply to `db`, as mentioned in #2110. 

The cleanest way to handle initial connection issues so far seems to be just letting the app to crash and let process manager (pm2 or other) to try to restart it. Nginx or something like that can be used to display a message to users until mongo is back online and app starts normally.
