### ISSUE TITLE
Sub document refs undefined, depending on how mongodb was installed.

### ISSUE THREAD

**Issue by kmpm** [Automattic/mongoose#3020]
This is an issue that has been discussed before and might be related to #2951 and #2988.
But I found it to be related to how the mongodb dependency was installed...

If mongodb is installed as a sibling dependency (ie mongob was installed first) to mongoose it will fail to get the ObjectId for a schema with __ref__.
If I choose to .populate I will get the sub document but otherwise I will get undefined.
The property is there though, but the value is set to undefined.

The important lines in the output below are
```
doc= { name: 'test', _id: 5565efb54b470078cb0ae60d, __v: 0 }
doc.application= undefined
```
Something about my environment
* on windows x64, node v0.10.36
* on ubuntu 15.04, node v0.10.38
* mongodb 3.0.0 and 2.4.11

This is the test script I'v been using.
```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh2951');

var ApplicationSchema = new mongoose.Schema({
    name: String
});

var UserSchema = new mongoose.Schema({
    application: { type: mongoose.Schema.Types.ObjectId, ref: 'Application', required: true, index: true },
    name: { type: String, required: true, index: true },
  });

var Application = mongoose.model('Application', ApplicationSchema);
var User = mongoose.model('user', UserSchema);

Application.create({name: 'test'})
.then(function (app) {
    return User.create({ application: app, name: 'test' }) ;
})
.then(function (doc) {
    return User.findOne({ _id: doc._id }).exec()  
})  
.then(function (doc) {
    console.log('doc=', doc);
    console.log('doc.application=', doc.application);
    return User.findOne({ _id: doc._id }).populate('application').exec()
})
.then(function (doc) {
    console.log('doc=', doc);
    console.log('doc.application=', doc.application);
    process.exit(0)
})
.end();
```
mongodb as child
----------------------
```json
"dependencies": {
    "mongoose": "4.0.3"
  }
```
Output:
Unpopulated returns the ObjectId and populated returns the document, just as expected.

```
Mongoose: applications.insert({ name: 'test', _id: ObjectId("5565f0d85e8ff1fcb6815dc5"), __v: 0 })
Mongoose: users.ensureIndex({ application: 1 }) { background: true, safe: undefined }
Mongoose: users.insert({ application: ObjectId("5565f0d85e8ff1fcb6815dc5"), name: 'test', _id: ObjectId("5565f0d85e8ff1fcb6815dc6"), __v: 0 })
Mongoose: users.ensureIndex({ name: 1 }) { background: true, safe: undefined }
Mongoose: users.findOne({ _id: ObjectId("5565f0d85e8ff1fcb6815dc6") }) { fields: undefined }
doc= { application: 5565f0d85e8ff1fcb6815dc5,
  name: 'test',
  _id: 5565f0d85e8ff1fcb6815dc6,
  __v: 0 }
doc.application= 5565f0d85e8ff1fcb6815dc5
Mongoose: users.findOne({ _id: ObjectId("5565f0d85e8ff1fcb6815dc6") }) { fields: undefined }
Mongoose: applications.find({ _id: { '$in': [ ObjectId("5565f0d85e8ff1fcb6815dc5") ] } }) { fields: undefined }
doc= { application: { name: 'test', _id: 5565f0d85e8ff1fcb6815dc5, __v: 0 },
  name: 'test',
  _id: 5565f0d85e8ff1fcb6815dc6,
  __v: 0 }
doc.application= { name: 'test', _id: 5565f0d85e8ff1fcb6815dc5, __v: 0 }
```

mongodb as sibling
--------------------------
```json
"dependencies": {
    "mongodb": "2.0.30",
    "mongoose": "4.0.3"
  }
```
Output:
Without .populate it returns undefined where an ObjectId was expected
```
Mongoose: applications.insert({ name: 'test', _id: ObjectId("5565efb54b470078cb0ae60c"), __v: 0 })
Mongoose: users.ensureIndex({ application: 1 }) { background: true, safe: undefined }
Mongoose: users.insert({ application: ObjectId("5565efb54b470078cb0ae60c"), name: 'test', _id: ObjectId("5565efb54b470078cb0ae60d"), __v: 0 })
Mongoose: users.ensureIndex({ name: 1 }) { background: true, safe: undefined }
Mongoose: users.findOne({ _id: ObjectId("5565efb54b470078cb0ae60d") }) { fields: undefined }
doc= { name: 'test', _id: 5565efb54b470078cb0ae60d, __v: 0 }
doc.application= undefined
Mongoose: users.findOne({ _id: ObjectId("5565efb54b470078cb0ae60d") }) { fields: undefined }
Mongoose: applications.find({ _id: { '$in': [ ObjectId("5565efb54b470078cb0ae60c") ] } }) { fields: undefined }
doc= { application: { name: 'test', _id: 5565efb54b470078cb0ae60c, __v: 0 },
  name: 'test',
  _id: 5565efb54b470078cb0ae60d,
  __v: 0 }
doc.application= { name: 'test', _id: 5565efb54b470078cb0ae60c, __v: 0 }
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will investigate this asap

**Comment by kmpm** [comment]
And please note, if I remove the __ref: 'Application'__ I will get the ObjectId but .populate will of course fail.

**Comment by kmpm** [comment]
I have started to trace this if someone would be helped.
It's somewhere in the hydration, as one would guess.
It seems as if The call to __Document.prototype.populated__ returns undefined.
This will cause 
```
var ret = new pop.options.model(value);
```
in __ObjectId.prototype.cast__ to generate a 
    TypeError: Cannot read property 'options' of undefined

And by that the __init__ method in document.js catch that error and invalidate the path

**Comment by kmpm** [comment]
It's something with instance checking that fails...

if mongodb is installed as a child then
(value instanceof oid) = true
but if installed as sibling it will be false.

This test is done at about line 93 in lib/schema/objectid.js

**Comment by kmpm** [comment]
in case of mongodb installed as sibling the _value_ is an instance of 
__require('mongodb').ObjectID__ but I don't know how to fix this properly.
So from here on I'm stuck.

**Comment by kmpm** [comment]
this is probably related to #2908 and whatever is going on with different dependency tricks.

**Comment by kmpm** [comment]
Just a thought, 
couldn't the mongodb dependency be solved with a browserify shim instead of trying to do some other tricks?
That way you could do a require on as few things as possible (as mongodb for example) and have browserify use a shim file instead when that is needed.

**Comment by vkarpov15** [comment]
So the issue is the `require('bson');` call doesn't quite work if mongodb is installed as a sibling - in that case there will be 2 separate installations of bson, one for mongodb and one for mongoose, and that `instanceof` will fail unfortunately. Thanks for catching this problem. I'm actually not familiar with browserify shim, are you talking about this repo? https://github.com/thlorenz/browserify-shim

**Comment by gregthegeek** [comment]
I am also experiencing this issue with Mac OS 10.10.3, Mongoose 4.0.4, MongoDB 2.0.33, and Node 0.12.2.

**Comment by vkarpov15** [comment]
Unfortunately this bug is pretty difficult to test in mongoose itself, but it seems fixed by the above. This was caused by some work to make the browser component avoid loading mongodb, which is fairly tricky to do. Should be fixed for next release.

**Comment by gregthegeek** [comment]
I can confirm, using the latest version of Mongoose directly from github has fixed this issue for me. Thanks man!

**Comment by vkarpov15** [comment]
Thanks for your patience, this issue is a little unfortunate but has finally given us the kick we needed to use the driver abstraction correctly :)

**Comment by kmpm** [comment]
This issue is fixed for me as well..
