### ISSUE TITLE
findOneAndUpdate with $pull not removing

### ISSUE THREAD

**Issue by damionjn** [Automattic/mongoose#3021]
The promise is resolving and I'm able to send the entity back to the client, yet it's unmodified. It doesn't work with a callback either. This was working with v3.8.19, currently using 4.0.3.
```js
Entity.findOneAndUpdate(
  { accountId: _id },
  { $pull: { categories: { _id: categoryId }}}).exec()
  .then(function (entity) {
    res.send(entity)
  }, function (err) {
    res.status(500).end('Couldn\'t save entity: ' + err)
  })
```

I *am* able to modify categories with the following:
```js
Entity.findOneAndUpdate(
  { accountId: _id },
  { categories: null },
  { upsert: true }).exec()
  .then(function (entity) {
    res.send(entity)
  }, function (err) {
    res.status(500).end('Couldn\'t save entity: ' +  err)
  })
```

Example entity (not deeply nested):
```js
{
  _id: 057023749273asdf,
  profiles: [
    { _id: 057023749273asdff, name: 'profile1' },
    { _id: 057023749273asdfff, name: 'profile2' },
  ],
  categories: [
    { _id: 057023749273asdffff, name: 'cat1', subcategories: [Object] },
    { _id: 057023749273asdfffff, name: 'cat2', subcategories: [Object] },
  ]
}
```

**Comment by vkarpov15** [comment]
Looks like you're not setting the `new` flag, see discussion re: #2262 on [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes)

Following code works fine for me:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');
var assert = require('assert');

mongoose.connect('mongodb://localhost:27017/gh3021');

var s = new mongoose.Schema({
  _id: String,
  profiles: [{ _id: String, name: String }],
  categories: [{ _id: String, name: String }]
});

var M = mongoose.model('gh3021', s);

M.remove({}, function(error) {
  assert.ifError(error);
  M.create(
    {
      _id: '057023749273asdf',
      profiles: [
        { _id: '057023749273asdff', name: 'profile1' },
        { _id: '057023749273asdfff', name: 'profile2' },
      ],
      categories: [
        { _id: '057023749273asdffff', name: 'cat1' },
        { _id: '057023749273asdfffff', name: 'cat2' },
      ]
    },
    function(error, m) {
      // !!!! note the { 'new': true } option
      M.findOneAndUpdate({ _id: m._id }, { $pull: { categories: { _id: '057023749273asdffff' }}}, { 'new': true }, function(error, doc) {
        console.log('Error: ' + error);
        console.log(JSON.stringify(doc));
        process.exit(0);
      });
    });
});
```

**Comment by damionjn** [comment]
Thanks @vkarpov15

**Comment by damionjn** [comment]
Just tested this out, still not working as intended. `error` and `doc` are both `null`.

![screen shot 2015-06-18 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/7221494/8243406/09b1f4d4-15d4-11e5-9f05-1993bfed8118.png)

**Comment by vkarpov15** [comment]
Try upgrading to 4.0.5, I suspect this may be related to #3020. What are you using to get `req.user`? Also, try `req.user._id.toString()` as a workaround.

**Comment by damionjn** [comment]
I noticed I was passing in the wrong ID key. I meant to find the `Entity` by the `accountId`. After changing this and upgrading to 4.0.6 it works fine without the `.toString()` workaround. Thanks and sorry if I wasted anyone's time trying to track a bug in $pull!

`req.user` is an object Passport.js sets after token authentication.

**Comment by pre-signed-url7** [comment]
https://angular-date-format-javi.github.io/msodbcsql1774/ I’ve got it now
