### ISSUE TITLE
Mongoose getting stuck during connection closing

### ISSUE THREAD

**Issue by nikolay** [Automattic/mongoose#3023]
We were having connectivity issues to one out of three MongoDB nodes, and Mongoose was getting stuck during application exit as it seemed that the timeout by default is set to infinity, which is not intuitive. There was no clear indication of what was going on, and we've wasted many hours trying to understand where the issue is. I can't recall any other client having infinity as the default setting, which makes the defaults counterintuitive.

**Comment by vkarpov15** [comment]
Because by default, mongoose will try to automatically reconnect forever. You can [turn off the `auto_reconnect` option](http://mongoosejs.com/docs/api.html#index_Mongoose-createConnection), that should help.

**Comment by nikolay** [comment]
@vkarpov15 Yes, we found this the hard way and it was hard, because it's unintuitive! I can't think of any use case where something getting stuck forever is the desired default!

**Comment by zhuangya** [comment]
suffering from this as well ;(
