### ISSUE TITLE
Query middleware should execute after query params are set

### ISSUE THREAD

**Issue by alinode** [Automattic/mongoose#3024]
Hi,

I need to analyze the initial parameters passed to findOneAndUpdate call for audit. Like if we update the field 'fieldA' I need to save extra object in pre hook. How can I get the initial query and update options from within the findOneAndUpdate hook?

```
db.Order.findOneAndUpdate({_id: productId}, {$push: {items: item} }, 
{new: true}, function(err, order) {
....
})
```

And I need smth like this:

```
OrderSchema.pre('findOneAndUpdate', function(next) {
    if (this.???.$push && this.???.$push.items) {
        var historyItem = this.???.$push.items;
        OrderHistory.create({data: historyItem}, next)
    } else {
        next()
    }
})
```

Is it possible to do this?

Also if I use the same post hook is it maybe possible to get modified paths of the document (looks like modified paths are empty in this case).

Thanks.

**Comment by vkarpov15** [comment]
`this.options`, `this._conditions`, and `this._update`.

**Comment by alinode** [comment]
Thanks!

**Comment by alinode** [comment]
@vkarpov15 Btw, faced that _conditions and _update information available only in post('findOneAndUpdate') hook.  In pre hook _condition is {} and _update is undefined. I do not seem to see any other fields in debug containing this info in pre hook. Is it supposed to be by design?

**Comment by alinode** [comment]
Also I wonder why this info (_condition and _update) was done as internal state on which (as you previously mentioned) we should not rely to unless we really need.  I am not sure if it's often use-case but would be good to have this as a documented options which allows to analyze what is changed and how.

**Comment by alinode** [comment]
@vkarpov15 Ok, I investigated this and found that in model.js findOneAndUpdate initially passes empty Query which doesn't have any information about the actual query. Thus in pre hook we cannot get it. Later when we run in Kareem fn.apply(context, args.slice(0, end) which is actual query I guess the data is populated and thus can be extracted from the post hook using the same context. Is it intended behavior or this can be fixed somehow?

**Comment by vkarpov15** [comment]
Yeah unfortunately right now you need to do:

```javascript
db.Order.findOneAndUpdate({_id: productId}, {$push: {items: item} }, 
{new: true}).exec(function(err, order) {
  // this._conditions = { _id: productId };
})
```

Note the `exec()`. One of the unfortunate quirks right now is that if you do `find` or `findOneAndUpdate` with a callback, the hooks execute before the query params are actually set internally.

**Comment by alinode** [comment]
@vkarpov15 Ok, thanks for your help.

**Comment by bdentino** [comment]
Not sure if the problem I'm having is related to this issue, but is it possible to modify the `this._update` object in pre-middleware? I have some middleware set up to transform a certain field if present in the update and i've found that if the field is in the top-level of the update object, the transformed value is stored, but if the value is in a `$set` command, the untransformed value is stored. To illustrate:

```
UserSchema.pre('update', function(next) {
  var update = this._update;
  if (update.$set && update.$set.name) {
    // this does not work...whatever was originally in update.$set.name is saved
    update.$set.name = transform(update.$set.name);
  } else if (update.name) {
    // this works...the transformed name is saved
    update.name = transform(update.name);
  }
  next();
})
```
Is this expected? I've noticed that I can do this to make it work:
```
if (update.$set && update.$set.name) {
  update.name = transform(update.$set.name);
}
```
but it seems that this would limit my ability to make adjustments in middleware for `$push` operations, etc.

**Comment by vkarpov15** [comment]
@bdentino can you open up a separate issue?
