### ISSUE TITLE
Populate of nested models?

### ISSUE THREAD

**Issue by iliakan** [Automattic/mongoose#3029]
Let's say I have a `CourseGroup` model with array of refs:

```js
mongoose.model('CourseGroup', new Schema({
  participants: [{
    type:     Schema.Types.ObjectId,
    ref:      'CourseParticipant'
  }]
});
```

And `CourseParticipant`:
```js
mongoose.model('CourseParticipant', new Schema({
  user: {
    type: Schema.Types.ObjectId,
    ref:  'User',
    index: true,
    required: true
  }
});
```

Should this `populate` work (wrapped in `co`, nothing wrong with yield here)?

```js
var group = yield CourseGroup
  .findById(id)
  .populate('participants participants.user').exec();
```

I'd like to have a group with `participants` array and `user` field populated for each of them.

But as of now, it returns a group with an array of participants, but `participant.user` is an `ObjectId`, not populated.

**Comment by vkarpov15** [comment]
You'd have to do a separate populate once the first populate is done, see #1377 etc. The below should work in theory.

```javascript
var group = yield CourseGroup
  .findById(id)
  .populate('participants').exec();
group = yield group.populate('participants.user').exec;
```

**Comment by iliakan** [comment]
@vkarpov15 

This line exists with error, because `.exec` is `undefined`.
```js
group = yield group.populate('participants.user').exec;
```

`yield` should receive a promise.

**Comment by iliakan** [comment]
This code doesn't work too:
```js
yield CourseGroup.populate(group, 'participants.user');
```

Really strange, maybe I should submit a more complete example with few data items?

**Comment by iliakan** [comment]
This code does the job:
```js
 yield User.populate(group, 'participants.user');
```

**Comment by iliakan** [comment]
Is it the most elegant way to do the job? :)

**Comment by iliakan** [comment]
P.S. #1377 is 2 years ago. Nothing has changed?

**Comment by vkarpov15** [comment]
Yep, hasn't really changed. Thanks for working out my example. Making multi-level population frictionless hasn't really been a very high priority because multi-level populating on a populated field is often indicative of sub-optimal schema design - since populate() isn't exactly an SQL join, it just executes a bunch of extra queries and incurs the RTT twice.

**Comment by iliakan** [comment]
@vkarpov15 thank you very much for answering.
Could you please clear up one more point here: `yield User.populate(group, 'participants.user');` (`participants` is an array) will make a request to db for each participant (hence many) or just a single one for all?

**Comment by iliakan** [comment]
And, if I call same populate twice, will it resend the queries?

**Comment by vkarpov15** [comment]
Should be just one for all the participants. Those two distinct `.populate()` calls will trigger 2 queries, one for all participants, and then one for all the `participants.user` fields
