### ISSUE TITLE
Mongoose doesn't enforce type 'string' in a schema anymore

### ISSUE THREAD

**Issue by seppevs** [Automattic/mongoose#3030]
I upgraded mongoose today. Suddenly, one of my integration tests failed.

In my schema I have:
```javascript
  someAttribute: {
    type: String,
    required: 'someAttribute cannot be blank'
  },
```

The test that fails tests that an error should be raised when someone tries to save an object as the 'someAttribute':

```javascript
someAttribute: {
   thisIs: 'anObject'
}
```

I don't know exactly which version I used before, but Mongoose has always thrown an error when I tried to persist an object where a String is expected. 

In the current version, Mongoose just silently persists the 'object' although an attribute of type 'String' was specified in the Schema.

**Comment by acourtiol** [comment]
I've the same issue since 4.0.4. :+1:

**Comment by vkarpov15** [comment]
An unexpected side-effect of #2943's fix was that now mongoose started casting objects to strings, so mongoose would cast `{ thisIs: 'anObject' }` -> '[object Object]'. This fix will make sure mongoose avoids using the default `toString()` object so you don't ever save '[object Object]'. This should provide a workaround for your issue without occluding the sometimes-useful use case of objects with custom `toString()` getting casted to strings.
