### ISSUE TITLE
Setters on Array items not executed

### ISSUE THREAD

**Issue by dhritzkiv** [Automattic/mongoose#3032]
I may be interacting with arrays incorrectly, but I can't seem to get the setters on array items to fire upon insertion or upon saving, after an initial initialization.

````javascript
var schema = new mongoose.Schema({
    arrayField: [
        {
            type: String,
            lowercase: true
        }
    ]
});

var Model = mongoose.model("foobar", schema);

var doc = new Model({
    arrayField: ["ONE", "TWO"]
});
//doc now has two values, and they were lowercased, as expected.
//{
//    arrayField: ["one", "two"]
//}

doc.arrayField.push("THREE");
//doc now has three values, but the newly inserted one is not lowercased
//{
//    arrayField: ["one", "two", "THREE"]
//}

doc.save(function(err, model) {
   //doc.arrayField still has the third value as uppercase; the setters on the new values haven't been executed.
   //{
   //    arrayField: ["one", "two", "THREE"]
   //}
});
````

I've tried various ways of affecting the array: `doc.markModified("arrayField.2")`, `doc.set("arrayField.2", "THREE")`; but it's still the same result.

Apologies if this is a known issue. I couldn't find it by searching.

Mongoose v4.0.4 on io.js 2.1.0

**Comment by victorkohl** [comment]
@vkarpov15 i'm trying to fix this issue. still need some work for #set, but I would like to know if i'm on the right track here. not so sure about the correct use of #applySetters(). thanks.

**Comment by vkarpov15** [comment]
Seems pretty reasonable so far. As long as tests pass, I probably could merge this :)
