### ISSUE TITLE
model.create and/or model.save are not returning a fully implemented promise

### ISSUE THREAD

**Issue by silverbp** [Automattic/mongoose#3033]
reproduce:

model.create({ name: 'johndoe' }).then(function(user){...})

the above works, however if you try to do done() or catch() on it, the method doesn't exist.

**Comment by silverbp** [comment]
end() exists.. on the other hand if you get the promise back from a query function like model.find() it returns a proper promise.

**Comment by vkarpov15** [comment]
`.save()` currently returns a promises/A+ conformant promise, which does not include `.catch()`. Because of some odd quirks, `.find().exec()` actually returns a bluebird promise if you don't specify any query middleware. A future release will enable you to plug your own promises library, see #2688
