### ISSUE TITLE
Wrong using of this

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#3034]
Are you sure in the following line https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L77 you use `this` correctly? It seems you have to use `self` rather than `this` because `this` in this context is `global`.

**Comment by vkarpov15** [comment]
Good catch, that seems like a bug in mongoose

**Comment by vkarpov15** [comment]
Actually it's by design. In that function's context, [`this` is a reference to the model, not the global object](https://github.com/Automattic/mongoose/blob/1c69036088a1823fd5e131fcb3e56573ec84130f/lib/schematype.js#L537-539). Part of some `.call()` magic - a JavaScript function's context can't be determined with certainty without seeing how it's actually called.

**Comment by skotchio** [comment]
@vkarpov15 ou point me to `getDefault` method https://github.com/Automattic/mongoose/blob/1c69036088a1823fd5e131fcb3e56573ec84130f/lib/schematype.js#L536 but I told you about `default`one https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L75

Also in the following code:

    this.default(function(){
        var arr = fn ? defaultArr() : defaultArr || [];
        return new MongooseArray(arr, self.path, this);
    });

`this` is always `global` because of in JavaScript any function invoked in global context, if not passed  any, executed in `global` context.

Your code should be like the following:

    this.default(function(){
        var arr = fn ? defaultArr() : defaultArr || [];
        return new MongooseArray(arr, self.path, this);
    }.bind(this));

to get is work

**Comment by vkarpov15** [comment]
Yeah the `getDefault()` function uses `.call()` to set the default function's context to the model, see [this](https://github.com/Automattic/mongoose/blob/1c69036088a1823fd5e131fcb3e56573ec84130f/lib/schematype.js#L538). Trust me, I tried, but the usage of `this` there is actually correct. Tests will blow up horribly if you add that `.bind()` :)

**Comment by skotchio** [comment]
@vkarpov15 ok this is your library and maybe I don't understand it structure. But according to this fix https://github.com/Automattic/mongoose/commit/b0379199cbba7afbbc380698b4fa240ac2fac148 you should add same one into https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L37 because I get exception: `TypeError: Cannot call method 'path' of undefined`

because in the following block code:

    if (doc) {
      arr._parent = doc;
      arr._schema = doc.schema.path(path);
      arr._handlers = {
        isNew: arr.notify('isNew'),
        save: arr.notify('save')
    };

    doc.on('save', arr._handlers.save);
    doc.on('isNew', arr._handlers.isNew);

`doc` is `global`

**Comment by skotchio** [comment]
@vkarpov15 also I've found that in `mongoose4.0.3` https://github.com/Automattic/mongoose/blob/4.0.3/lib/schema/documentarray.js#L53

    this.default(function(){
       var arr = fn.call(this);
       if (!Array.isArray(arr)) arr = [arr];
       return new MongooseDocumentArray(arr, path, this);
    });

`this` is document rather `global`

**Comment by skotchio** [comment]
It seems I've found why the document is `global`. Look at the following line https://github.com/Automattic/mongoose/blob/master/lib/services/updateValidators.js#L77

You pass `null` as scope in `getDefault` function which leads to `global` scope

**Comment by vkarpov15** [comment]
You're right. Update validators still have a few quirks that need to get worked out apparently

**Comment by vkarpov15** [comment]
Fix should be analogous to #3035

**Comment by skotchio** [comment]
@vkarpov15 unfortunately this fix does't correspond to the issue

**Comment by skotchio** [comment]
you need to add the same check to `MongooseDocumentArray` class here https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L37
