### ISSUE TITLE
setDefaultsOnInsert throws exception on arrays in schema

### ISSUE THREAD

**Issue by gunters63** [Automattic/mongoose#3035]
Using setDefaultsOnInsert: true in options of findOneAndUpdate (together with upsert) throws an exception if the schema contains any arrays (here it bombs on 'a'), even when the document already exists.

Here a test:

      it.only('should work with setDefaultsOnInsert', function () {
        var testSchema = new mongoose.Schema({
          id: String,
          name: String,
          a: [String],
          _createdAt: {
            type: Number,
            default: Date.now
          },
        });
        var TestModel = mongoose.model('Test', testSchema, 'dbTest');
        return Q(TestModel.create({id: '1'}))
          .then(function () {
            return Q(TestModel.findOneAndUpdate({id: '1'},
              {$set: {name: 'Joe'}}, {
                upsert: true,
                setDefaultsOnInsert: true
              }).exec());
          });
      });

Exception:

    TypeError: Cannot call method 'path' of undefined
        at new MongooseArray (C:\proj\_SVN\Dispatcher\NodeExpressServer\node_modules\mongoose\lib\types\array.js:41:30)

**Comment by gunters63** [comment]
Same error when document is upserted:

      it.only('should work with setDefaultsOnInsert', function () {
        var testSchema = new mongoose.Schema({
          id: String,
          name: String,
          a: [String],
          _createdAt: {
            type: Number,
            default: Date.now
          },
        });
        var TestModel = mongoose.model('Test', testSchema, 'dbTest');
        return Q(TestModel.findOneAndUpdate(
          {id: '1'},
          {$set: {id: '1', name: 'Joe'}},
          {upsert: true, setDefaultsOnInsert: true}).exec());
      });

**Comment by gunters63** [comment]
Seems that updateValidators is the culprit, geDefault gets called with null:

    var def = schemaType.getDefault(null, true);

In schematype:gedefault this means the defaultValue getter is calles with a null scope:

    SchemaType.prototype.getDefault = function (scope, init) {
      var ret = 'function' === typeof this.defaultValue
        ? this.defaultValue.call(scope)
        : this.defaultValue;

For an array default this means (with this=null instead of a doc):

    return new MongooseArray(arr, self.path, this);

And then it crashes in the MongooseArray constructor because the schema property of the third parameter doc is accessed which us null.

**Comment by skotchio** [comment]
+1
I've found this bug also https://github.com/Automattic/mongoose/issues/3034

**Comment by gunters63** [comment]
I don't think so, the scope for the default funcition of Array is normally set to 'scope' by

    this.defaultValue.call(scope)

**Comment by gunters63** [comment]
I also noticed when I tried to work around this error:

When you use setDefaultsOnInsert, all Arrays in the schema automatically default to an empty array.

In updateValidators line 78, $setOnInsert gets populated for every Array even when this array does not have a default set.

**Comment by gunters63** [comment]
The mongoose tests have tests for setDefaultsOnInsert, but they only test a very simple schema:

      var s = new Schema({
        topping: { type: String, default: 'bacon' },
        base: String
      });

The Schema should probably include an Array and a nested object.

**Comment by gunters63** [comment]
After a bit research with MongoDB it seems setDefaultsOnInsert is really a complicated beast.
Mongoose converts this into a $set and $setOnInsert statement.
MongoDB does not like the multiple operations manipulating the same field. It throws an exception, for example: 

    Cannot update 'address.country' and 'address' at the same time"

Which means for example (as it happens to be the case in our application).

This schema with a nested object containing an array:

    Schema({
        a: {
            b: [String],
            c: Number
        }
    })

cannot be used with setDefaultsOnInsert with Mongoose when you just want to set the "a" field to "{c: 0}" . 

Mongoose will create a $setOnInsert with {a.b: Array[0]} and also a $set with a: {c: 0}}. MongoDB will complain and not update the document. Same problem when you use real defaults.

Probably the only solution would to be to remove those fields in $setOnInsert where the defaults would be overwritten by (the same) fields from the $set anyway.
