### ISSUE TITLE
Error: `increment` may not be used as a schema pathname

### ISSUE THREAD

**Issue by bryanlarsen** [Automattic/mongoose#3039]
When upgrading from 3.6 to 4.0, we received this error:

    Error: `increment` may not be used as a schema pathname

Yet #2709 claims this should be a warning, not an error, and it's not in the [list of reserved keys in the documentation](http://mongoosejs.com/docs/api.html#schema_Schema.reserved).

We've been using 'increment' in our schema for over 2 years now; modifying the schema and updating our code base would be very costly.

**Comment by vkarpov15** [comment]
The solution to make it reserved is admittedly a bit heavy-handed. Will tweak this for the next version - as long as you're not using mongoose versioning, you can use "increment" as a key.
