### ISSUE TITLE
Mongoose data range query not working

### ISSUE THREAD

**Issue by raghuiitr** [Automattic/mongoose#3041]
I have a search method which looks like this. (I have a lot of other code too for doing different kind of search but i am omitting that for simplicity)

    var mongoose = require('mongoose');
    
    exports.searchWithParams = function (modal, req, res, next) {
        console.log(JSON.stringify(req.body));
        var body = req.body;
        var orConditions = [];
        var andConditions = [];
        for (var i = 0; i < body.searchParms.length; i++) {
            var param = body.searchParms[i];
    
            switch (modType) {
                case 'and':
                    andConditions.push(param);
                    break;
                case 'or':
                    orConditions.push(param);
                    break;
                default :
                    throw new Error('Invalid mod type: ' + modType)
            }
        }
        var transalatedOrConditions = translateConditions(orConditions);
        var transalatedAndConditions = translateConditions(andConditions);
    
        var finalConditions = {};
        if (transalatedOrConditions.length > 0) {
            finalConditions['$or'] = transalatedOrConditions;
        }
    
        if (transalatedAndConditions.length > 0) {
            finalConditions['$and'] = transalatedAndConditions;
        }
    
        var query = modal.find(finalConditions);
    
        query.exec(function (err, results) {
            if (err) return next(err);
            if (!results) return res.json(401);
            res.json(results);
        });
    }
    
    function translateConditions(conditions) {
        var translatedConditions = [];
        for (var i = 0; i < conditions.length; i++) {
            var condition = conditions[i];
            var fieldName = condition.name;
            var fieldValue = condition.value;
            var searchType = condition.searchType;
            var dataType = condition.dataType;
    
            var translatedCondition = {};
            switch (searchType) {
                case 'range' :
                    switch (dataType) {
                        case 'date':
                            if (!condition.minValue || !condition.maxValue) {
                                throw new Error('missing minValue and maxValue for range query')
                            }
    
                            translatedCondition[fieldName] = {$gt: new Date(condition.minValue), $lt: new Date(condition.maxValue)};
                            translatedConditions.push(translatedCondition);
                            break;
    
                        default :
                            throw new Error('Invalid datatype: ' + dataType)
    
                    }
                    break;
                default :
                    throw new Error('Invalid search type: ' + searchType);
            }
        }
    
        return translatedConditions;
    }

I give a search parameter like this

    {
                    "searchParms": [{
                        "name": "topics.modules.classes.startTime",
                        "minValue": "2014-12-31",
                        "maxValue": "2015-01-31",
                        "searchType": "range",
                        "dataType": "date",
                        "modType": "and"
                    }
                ]
    }

When the query is executed the condition it generates is like this

    {"$and":[{"topics.modules.classes.startTime":{"$gt":"2014-12-31T00:00:00.000Z","$lt":"2015-01-31T00:00:00.000Z"}}]}

If I just execute the same query in the mongo console I get the results

 

        db.subjects.find({"$and":[{"topics.modules.classes.startTime":{"$gt":"2014-12-31T00:00:00.000Z","$lt":"2015-01-31T00:00:00.000Z"}}]});
    { "_id" : ObjectId("55538211864ff2daf3dfc504"), "name" : "math", "topics" : [ { "name" : "math topic", "startTime" : "", "endTime" : "", "fee" : "", "modules" : [ { "name" : "math module", "startTime" : "", "endTime" : "", "fee" : "", "classes" : [ { "name" : "math class", "startTime" : "2015-01-01T20:59:00.000Z", "endTime" : "2015-01-01T20:59:00.000Z", "fee" : 300 } ] } ] } ], "teacher" : ObjectId("5552de1756c7e627ebceb1af") }
    { "_id" : ObjectId("5553832d864ff2daf3dfc505"), "name" : "math1", "topics" : [ { "name" : "math1 topic", "startTime" : "", "endTime" : "", "fee" : "", "modules" : [ { "name" : "math1 module", "startTime" : "", "endTime" : "", "fee" : "", "classes" : [ { "name" : "math1 class", "startTime" : "2015-01-01T20:59:00.000Z", "endTime" : "2015-02-01T20:59:00.000Z", "fee" : 3001 } ] } ] } ], "teacher" : ObjectId("5552de1756c7e627ebceb1af") }

But somehow the method returns me nothing. The range query for other type of data like number (code is omitted) is working fine. How is it that the same condition works in mongo console but not in the server code. Any insight will be greatly helpful.

**Comment by vkarpov15** [comment]
First, your $and is redundant. You only need `$and` if you want to chain together `$or` clauses.

Also, `db.subjects.find({"$and":[{"topics.modules.classes.startTime":{"$gt":"2014-12-31T00:00:00.000Z","$lt":"2015-01-31T00:00:00.000Z"}}]});` implies that the `topics.modules.classes.startTime` field is a string, otherwise you'd have to use `ISODate()` in the shell. I suspect your schema specifies that `topics.modules.classes.startTime` is a date, so mongoose casts the ISO date strings into a BSON date. Is this the case?

**Comment by raghuiitr** [comment]
here is the schema of subject (yes the startTime and endTime are Date)

    var SubjectSchema = new Schema({
    teacher: {type: mongoose.Schema.ObjectId, ref: 'User'},
    name: String,
    topics: [{
        name: String,
        startTime: Date,
        endTime: Date,
        fee: Number,
        modules: [{
            name: String,
            startTime: Date,
            endTime: Date,
            fee: Number,
            classes: [{
                name: String,
                startTime: Date,
                endTime: Date,
                fee: Number
            }]
        }]
    }]
       })

I also tried with new Date in the query i generate but that also didn't help. If what i am doing is not right then i will appreciate if you could tell me the correct way of doing it.

**Comment by vkarpov15** [comment]
If `db.subjects.find({"$and":[{"topics.modules.classes.startTime":{"$gt":"2014-12-31T00:00:00.000Z","$lt":"2015-01-31T00:00:00.000Z"}}]});` succeeds, that means that `topics.modules.classes.startTime` is a string, not a date. I'd recommend migrating your data so that those fields are dates, or, if that's too cumbersome,

```javascript
topics: [{
    name: String,
    startTime: Date,
    endTime: Date,
    fee: Number,
    modules: [{
        name: String,
        startTime: Date,
        endTime: Date,
        fee: Number,
        classes: [{
            name: String,
            startTime: String, // this is a string in your database currently, either change schema or change your data
            endTime: String, // so is this
            fee: Number
        }]
    }]
}]
```

**Comment by raghuiitr** [comment]
as you can see in my comment i had posted the schema type. Those fields are date not string. I am not sure how you are claiming that its a string. Here is the output of db.subjects.find()

{ "_id" : ObjectId("5559919b8f7946b6d3bd0de4"), "name" : "Mathematics", "topics" : [ { "_id" : ObjectId("5565207aed37c5d65773e159"), "name" : "Topic 1", "startTime" : ISODate("2015-05-04T11:00:00Z"), "endTime" : ISODate("2015-05-12T08:00:00Z"), "fee" : 33, "modules" : [ { "_id" : ObjectId("5565207aed37c5d65773e15a"), "name" : "module1 updated", "startTime" : ISODate("2015-05-04T07:00:00Z"), "endTime" : ISODate("2015-05-10T11:00:00Z"), "fee" : null, "classes" : [ { "_id" : ObjectId("5565207aed37c5d65773e15c"), "name" : "class1 has been updated", "startTime" : ISODate("2015-05-06T12:05:00Z"), "endTime" : ISODate("2015-05-03T07:00:00Z"), "fee" : 343434 }, { "_id" : ObjectId("5565207aed37c5d65773e15b"), "name" : "class2", "startTime" : ISODate("2015-05-12T07:00:00Z"), "endTime" : ISODate("2015-05-12T11:00:00Z"), "fee" : 344455 } ] }, { "fee" : null, "endTime" : null, "startTime" : null, "name" : "module 2 added", "_id" : ObjectId("55652130ed37c5d65773e15d"), "classes" : [ ] } ] } ], "teacher" : ObjectId("5554fad036a53e27fe0f3ee0") }

As you can see that class.startTime and class.endTime both are ISODate

**Comment by raghuiitr** [comment]
@vkarpov15 can you please reopen this issue or suggest what is wrong in my implementation?

**Comment by vkarpov15** [comment]
Funny, that's not what was in your initial report:

```
{ "_id" : ObjectId("55538211864ff2daf3dfc504"), "name" : "math", "topics" : [ { "name" : "math topic", "startTime" : "", "endTime" : "", "fee" : "", "modules" : [ { "name" : "math module", "startTime" : "", "endTime" : "", "fee" : "", "classes" : [ { "name" : "math class", "startTime" : "2015-01-01T20:59:00.000Z", "endTime" : "2015-01-01T20:59:00.000Z", "fee" : 300 } ] } ] } ], "teacher" : ObjectId("5552de1756c7e627ebceb1af") }
{ "_id" : ObjectId("5553832d864ff2daf3dfc505"), "name" : "math1", "topics" : [ { "name" : "math1 topic", "startTime" : "", "endTime" : "", "fee" : "", "modules" : [ { "name" : "math1 module", "startTime" : "", "endTime" : "", "fee" : "", "classes" : [ { "name" : "math1 class", "startTime" : "2015-01-01T20:59:00.000Z", "endTime" : "2015-02-01T20:59:00.000Z", "fee" : 3001 } ] } ] } ], "teacher" : ObjectId("5552de1756c7e627ebceb1af") }
```

Note that classes.startTime is a string in the above documents, `"endTime" : "2015-02-01T20:59:00.000Z"`. Which of these is correct? Because if the query you specified,

```
db.subjects.find({"$and":[{"topics.modules.classes.startTime":{"$gt":"2014-12-31T00:00:00.000Z","$lt":"2015-01-31T00:00:00.000Z"}}]});
```

gives you the correct output in the mongodb shell, that means that `topics.modules.classes.startTime` is necessarily a string.

**Comment by raghuiitr** [comment]
Okay you are right, some of the documents in the collection had strings so thats the confusion. I only saw   last few rows which had them as date. I removed those documents and fixed the query and now its all good. Thank you very much for your help.

**Comment by vkarpov15** [comment]
Glad it worked out :)
