### ISSUE TITLE
Mongoose doesnt work for remote MongoDB 2.6.8

### ISSUE THREAD

**Issue by PreethiBabu87** [Automattic/mongoose#3045]
Hi

Am using mongoose to connect to mongodb. Everything works when my connection string is localhost.
But when i mention a remote host where mongo db 2.6.8 is running, the connection gets established but the operations like db.collectionnames or save or any other mongoose operations doesnt work.
The same code works for localhost mongodb. My local box mongodb version is 3.0.3.

regards
Preethi

**Comment by vkarpov15** [comment]
How are you connecting? Can you connect to mongodb using the mongo shell?:

**Comment by PreethiBabu87** [comment]
Yes am able to connect it using mongo shell from my local box.. am writing a nodejs app and using mongoose to connect the remote mongo db 2.6.8

**Comment by PreethiBabu87** [comment]
The below code gets the list of collections for me when am connecting to a locally running mongodb which is of version 3.0.3 but not when connecting to a remote running mongodb which is 2.6.8:

mongoose.connection.db.collectionNames(function (error, names) {
        if (error) {
            throw new Error(error);
        } else {
            names.map(function (cname) {
                console.log(cname.name);
            });
        }
    });

**Comment by PreethiBabu87** [comment]
Hey

I installed the same version of mongodb which is  in remote host(2.6.8) in my local box. The code works. Guess there is something wrong with my connect string to the remote. When I call the db.collectionNames, neither of the callbacks get fire, whether it has error or success.
Below is mu connection string:
var dbName = 'OST';
var connectionString = 'mongodb://vm-1b98-f53f.nam.nsroot.net:32017/OST?ssl=true&sslverifycertificate=false';

mongoose.connect(connectionString);

mongoose.connection.on('connected', function () {
    console.log('Mongoose default connection open to ' + connectionString);
   
    mongoose.connection.db.collectionNames(function (error, names) {
        if (error) {
            throw new Error(error);
        } else {
            names.map(function (cname) {
                console.log(cname.name);
            });
        }
    });
    });

mongoose.connection.on('error', function (err) {
    console.log('Mongoose default connection error: ' + err);
});

**Comment by vkarpov15** [comment]
Are you using SSL locally too? Could easily be a SSL issue. Are you getting anything from your 'connected' and 'error' event handlers?

**Comment by PreethiBabu87** [comment]
No locally am not using ssl.. But am able to see the console.log message inside on connected, so I assumed I got connected to the remote db. It didn't error out anything.. The db.collectionNames is not returning anything though there are collection which I saw through the mongo shell

    mongoose.connection.on('connected', function () {
    console.log('Mongoose default connection open to ' + connectionString);
    mongoose.connection.db.collectionNames(function (error, names) {
    if (error) {
        throw new Error(error);
    } else {
        names.map(function (cname) {
            console.log(cname.name);
        });
     }
    });
    });

**Comment by vkarpov15** [comment]
Can you try an operation that goes through mongoose rather than the underlying driver, like creating a new model and then doing `MyModel.findOne()`? May be an issue with mongoose's driver wrapper.

**Comment by PreethiBabu87** [comment]
Hi Val

I tried using the model operations as you suggested:

mongoose.connection.on('connected', function () {
    console.log('Mongoose default connection open to ' + connectionString);
    var Region = require('./Region.js');
    var r = new Region({ NodeID: 8687, RegionName: 'EMEA' });
   
    r.find({}, function (err, host) {
                if (err) {
                    return res.send(err);
                }
        
                //res.json(host);
                console.log(host);
            });

});

Region:js
------------
var mongoose = require('mongoose');

var Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;

var RegionSchema = new Schema({
    NodeID       : Number,
    //RegionName   : String
    RegionName      : {
        type: String, 
        unique: true,
        index: true
    },
}, 
    {
    collection: 'Regions'
});

RegionSchema.virtual('RegionID').get(function () {
    return this._id;
});

module.exports = mongoose.model('Region', RegionSchema);

But i get the below error:
C:\Projects\EasyNetQPoc\OSTDBCreation\node_modules\mongoose\node_modules\mongodb
\lib\mongodb\db.js:279
          throw err;
                ^
TypeError: undefined is not a function
    at NativeConnection.<anonymous> (C:\Projects\EasyNetQPoc\OSTDBCreation\app.j
s:24:7)
    at NativeConnection.emit (events.js:104:17)
    at NativeConnection.Object.defineProperty.set (C:\Projects\EasyNetQPoc\OSTDB
Creation\node_modules\mongoose\lib\connection.js:104:14)
    at open (C:\Projects\EasyNetQPoc\OSTDBCreation\node_modules\mongoose\lib\con
nection.js:445:21)
    at NativeConnection.Connection.onOpen (C:\Projects\EasyNetQPoc\OSTDBCreation
\node_modules\mongoose\lib\connection.js:461:5)
    at C:\Projects\EasyNetQPoc\OSTDBCreation\node_modules\mongoose\lib\connectio
n.js:421:10
    at C:\Projects\EasyNetQPoc\OSTDBCreation\node_modules\mongoose\lib\drivers\n
ode-mongodb-native\connection.js:59:5
    at C:\Projects\EasyNetQPoc\OSTDBCreation\node_modules\mongoose\node_modules\
mongodb\lib\mongodb\db.js:276:11
    at process._tickCallback (node.js:355:11)

**Comment by PreethiBabu87** [comment]
mongoose.set(debug, 'true') also didnt change anything.. Actually what happens if am setting this? Any log is written to the console?

**Comment by vkarpov15** [comment]
Mongoose will write any operations sent to the server to the console.

Also, which version of mongoose are you using? Looks like you're using an older one.

**Comment by PreethiBabu87** [comment]
Am using mongoose@3.8.3 which was an older version and it didn't write anything to the console as I said earlier even after I set mongoose in debug mode.
Now I tried installing latest version of mongoose which is 4.0.5, but it the installation completed with errors (below):
 kerberos.vcxproj -> C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\Release\\kerberos.node
npm ERR! fetch failed https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz
npm WARN retry will retry, error on last attempt: Error: certificate not trusted
npm ERR! fetch failed https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz
npm WARN retry will retry, error on last attempt: Error: certificate not trusted
npm ERR! fetch failed https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz
npm WARN optional dep failed, continuing bson-ext@0.1.7
mongoose@4.0.5 node_modules\mongoose
+-- regexp-clone@0.0.1
+-- muri@1.0.0
+-- sliced@0.0.5
+-- mpromise@0.5.4
+-- hooks-fixed@1.0.1
+-- kareem@1.0.1
+-- async@0.9.0
+-- mpath@0.1.1
+-- ms@0.1.0
+-- mquery@1.5.1 (debug@0.7.4, bluebird@2.9.9)
+-- mongodb@2.0.33 (readable-stream@1.0.31, mongodb-core@1.1.32)
+-- bson@0.3.2

====npm command completed with exit code 0====

But anyway I started my node application since mongoose latest version got installed. Guess the mongoose debug worked and it throwed the below error:

C:\Projects\EasyNetQPoc\NodeJsWebApplication>node ./bin/start
Express server listening on port 8000
Mongoose default connection open to mongodb://vm-1b98-f53f.nam.nsroot.net:32017/
OST
C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\node_modules\
mongodb\lib\server.js:274
      process.nextTick(function() { throw err; })
                                          ^
TypeError: undefined is not a function
    at NativeConnection.<anonymous> (C:\Projects\EasyNetQPoc\NodeJsWebApplicatio
n\app.js:26:28)
    at NativeConnection.emit (events.js:104:17)
    at NativeConnection.Object.defineProperty.set (C:\Projects\EasyNetQPoc\NodeJ
sWebApplication\node_modules\mongoose\lib\connection.js:105:14)
    at open (C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\
lib\connection.js:477:21)
    at NativeConnection.Connection.onOpen (C:\Projects\EasyNetQPoc\NodeJsWebAppl
ication\node_modules\mongoose\lib\connection.js:494:5)
    at C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\lib\co
nnection.js:453:10
    at C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\lib\dr
ivers\node-mongodb-native\connection.js:59:5
    at C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\node_m
odules\mongodb\lib\db.js:206:5
    at connectHandler (C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules
\mongoose\node_modules\mongodb\lib\server.js:272:7)
    at g (events.js:199:16)
    at emit (events.js:107:17)
    at C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\node_m
odules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:388:23
    at C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules\mongoose\node_m
odules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:795:13
    at Callbacks.emit (C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_modules
\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.j
s:94:3)
    at null.messageHandler (C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_mo
dules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\ser
ver.js:235:23)
    at TLSSocket.<anonymous> (C:\Projects\EasyNetQPoc\NodeJsWebApplication\node_
modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\c
onnection.js:259:22)

**Comment by PreethiBabu87** [comment]
And the code which I executed was : 
      mongoose.connection.on('connected', function (callback) {
        console.log('Mongoose default connection open to ' + connectionString);
   
       mongoose.connection.db.collectionNames(function (error, names) {
            if (error) {
               //throw new Error(error);
                console.log(error);
           } else {
                names.map(function (cname) {
                    console.log(cname.name);
                });
             }
        });
      });

   It says db.collectionNames is  TypeError: undefined is not a function

**Comment by PreethiBabu87** [comment]
Val,

I got it fixed after installing the latest version of mongoose though it was not error free install. I just had to change the function db.collectionName to db.listCollections()

       mongoose.connection.db.listCollections().toArray(function (err, names) {
        if (err) {
            console.log(err);
        }
        else {
            names.forEach(function (e, i, a) {
                console.log("--->>", e.name);
            });
        }

Thaks a lot Val.. But can you tell me why I get error during mongoose installation
    });

**Comment by vkarpov15** [comment]
Yeah I wouldn't recommend using mongoose 3.8.3 for a new project, it's a pretty archaic version at this point. As for the npm messages, that's just a warning for some native extension fallbacks, nothing to worry about :)
