### ISSUE TITLE
Validation errors crash when used with strict mode

### ISSUE THREAD

**Issue by joesonw** [Automattic/mongoose#3046]
when I called `yield model.update({_id:id},data);`

it throws a `TypeError`

`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

**Comment by vkarpov15** [comment]
Which version of node and mongoose is this for?

**Comment by joesonw** [comment]
It appears to be `lib/error.js' line 11. Where it used arguments.callee.

I'm using Mongoose@4.0.2, Node@0.12.4
