### ISSUE TITLE
Discriminators: Middleware added via the model to the base schema

### ISSUE THREAD

**Issue by ikb42** [Automattic/mongoose#3047]
Example, executing this after the model has been created:

    baseModel.schema.post('save', function (doc) {
      ...
    });

would add the hook on the base schema but not to any child schemas.

IMO it would be most intuitive if all base schema hooks fired for all similar child events, ie. the behaviour is always inherited, but could be overloaded/overridden on the child.

Related to #2892

**Comment by vkarpov15** [comment]
Modifying the schema after it's been compiled into a model is not supported behavior - mongoose makes a copy of the schema when you create a new model. Therefore, when you say `model.schema.post()`, you're modifying the model's copy of the schema, not the schema itself. See ["Compiling your first model" in the model docs](http://mongoosejs.com/docs/models.html)

**Comment by ikb42** [comment]
Thanks for the info.
Would be great to have something like this, when I get any good at JS I should make a pull request!  Or are there good reasons not to venture down that route?

**Comment by vkarpov15** [comment]
Potentially weird behavior when the schema underlying a model changes and its more headache than its worth. Suppose that somebody changes one model's schema at runtime halfway through another model's validation logic is running - that's the kind of possibility that the original design was built to avoid.

**Comment by ikb42** [comment]
Good to know the thinking, thanks very much.  So there would need to be some possibly messy sync mechanism that queues such runtime changes when there is a running validation etc.  Hmm.  I do of course see your points completely.  I was thinking about it from a purely naive OO point of view, how the behaviour would be intuitively understood rather than anything else.
Will leave it.
