### ISSUE TITLE
missing _id field for referenced document

### ISSUE THREAD

**Issue by midthun** [Automattic/mongoose#3048]
I'm having issues referencing a document using ObjectId after upgrading to version 4.0.4 from 3.8. I get this error trying to populate: 

    { [CastError: Cast to number failed for value "[object Object]" at path "_id"] 
      message: 'Cast to number failed for value "[object Object]" at path "_id"',
      name: 'CastError',
      kind: 'number',
      value: 
        { _id: 556e186f6b0b77675c3d9075,
          date: Tue Jun 02 2015 22:56:15 GMT+0200 (CEST) },
      path: '_id' }

Query: 

    var populate = [{
      path: 'searches'
    }];
    User.findOne({ _id: 378 }).populate(populate).exec(function(err, doc) { 
      if (err) {
        return next(err);
      }
    }); 

User schema:

    ...
    searches: [{ 
      date: { 
        type: Date, required: false, 'default': Date.now 
      }, 
      _id: {
        type: mongoose.Schema.Types.ObjectId, ref: 'Search' 
      }
    }], 
    projects: [{ 
      date: { 
        type: Date, required: false, 'default': Date.now 
      }, 
      _id: {
        type: Number, ref: 'Project' 
      }
    }],  
    ...   

Search schema:

    var schema = new mongoose.Schema({
      date: { type: Date, required: false, default: Date.now, index: true },
      api: { type: Boolean, required: false, default: false },
      time: { type: Number, required: false, default: 0 }
    }); 

Also, if I do a normal findOne, like this: 

    User.findOne({ _id: 378 }, function(err, user) {
      if (err) {
        return next(err);
      }

      console.log(user);
      // outputs "searches" without the _id field, only date field, "projects" have the _id field present
    });

I do not get the _id field in the output for the "searches", only the "date" field. I use the exact same setup with "projects" in the User schema, just referencing another schema (Projects), not using ObjectId, but number instead (for the _id field on Projects), which works fine.

There is also a problem when I do findOne() then save(), I get cast errors on the referenced documents, since they are empty arrays, they do not contain anything unless i populate them.

### Update
I was able to fix this by changing the "type" on the "searches" to String instead of ObjectId. However, this is against the Mongoose documentation I think, since to be able to populate, both types should be equal? Now, the _id on the User schema is "String" and the _id on the Search schema is of type ObjectId

**Comment by vkarpov15** [comment]
Dup of #3020 #2951 #2988 etc. etc.
