### ISSUE TITLE
Query post middleware should provide access to the result of a query

### ISSUE THREAD

**Issue by gregthegeek** [Automattic/mongoose#3051]
Query post middleware currently looks like this:
```javascript
schema.post('findOneAndUpdate', function() {
    // here i can access the query object (via this) but not the result of the query
});
```
Would it be possible to do something like this:
```javascript
schema.post('findOneAndUpdate', function(result) {
    // here i can access the query object (via this) and the result of the query
});
```
This way, the result of the query could be read in the post hook. For queries like `findOneAndUpdate`, this means you can access the updated document.

#### Use case
When a document is updated, I would like to update related documents based on the ID of the document that was updated. The only reliable way to detect which documents were updated in a query is to use what MongoDB returns. Here I could access the updated document's ID (and other fields) to use in other operations.

**Comment by vkarpov15** [comment]
I know for a fact that

```javascript
schema.post('find', function(result) {
    // 'result' is the result of the query
});
```

works. Does it not work for `findOneAndUpdate`?

**Comment by gregthegeek** [comment]
Wait, really? Is this documented? I haven't seen anything in the documentation. I didn't try it, since I didn't see anything I assumed it wasn't a feature.

**Comment by vkarpov15** [comment]
Not documented in mongoose. It's [not-very-clearly documented in the underlying hooks library](https://github.com/vkarpov15/kareem#it-wraps-wrap-into-a-callable-function), but we can improve that.

**Comment by gregthegeek** [comment]
That's awesome, this should definitely be documented though.
