### ISSUE TITLE
Mongoose v3.8.x filling populated fileds with null

### ISSUE THREAD

**Issue by eloytoro** [Automattic/mongoose#3055]
I really hate `null` for the obvious reasons everyone else does and also because it's bringing inconsistencies to my API

I have a Schema that goes as follows

```javascript
var UserSchema = new Schema({
  client: { type: ObjectId, ref: 'Client' }
});

var ClientSchema = new Schema({
  name: String
})
```

For some reason when I use Model#populate on an array of `users` that may or **may not** have a client it correctly populates the users that have clients, but the ones that don't **get a `null` on the client field**

Repro
```javascript
User.find({}, function (err, users) {
  Client.populate(users, { path: 'client' }, function (err) {
    console.log(users);
    // [{ client: { name: 'John' } }, { client: null }]
  });
});
```

**Comment by vkarpov15** [comment]
That's by design. If it can't find a client whose id matches `user.client`, `user.client` will be null. If you can think of an alternative behavior that would be better, I'd love to hear it :)

**Comment by eloytoro** [comment]
Well whats odd about it is that when _none_ of the documents have the reference set then none of them will have `null` set.

Extending the example previously used
```javascript
[{ client: 'foreign_key', age: 22 }] // populates to [{ client: {/* object */}, age: 22 }]
[{ age: 22 }] // populates to [{ age: 22 }]
```

**Comment by vkarpov15** [comment]
I don't quite understand that last sentence, can you please clarify?

**Comment by eloytoro** [comment]
Basically what i'm getting at is that its no use for me that the populated (but undefined) values are set to null and mongoose doesn't provide any tools to prevent this

**Comment by paton** [comment]
So it looks like the bug is that when the field being populated doesn't exist on the original document, it also shouldn't exist on the populated document.

So 

{ age: 22 }

should never be populated to 

{ age: 22, client: null }

Mongoose adds the null "client" that didn't exist on the original document.

**Comment by vkarpov15** [comment]
Ah ok I see, thanks for the clarification @paton

**Comment by Tyrannogina** [comment]
Hi! I have mongoose version 4.11.11.
I am experiencing the exact same issue @paton is describing about adding null "client".

I created a Schema with a field that is an array filled with two types of objectId's according to a discriminator. I don't know if I am using something wrong, but when I populate the document I get the field that does not belong to the discriminator as null.

Better I put an example, I am not sure how to explain.
When I save the document, the field looks like this (got this from Robo3T):

```
"dataInputs" : [
        {
            "flag" : "potato",
            "datafile" : ObjectId("59ce7046b2ac0713a694210b"),
            "dataInputsKind" : "datafile"
        },
        {
            "flag" : "albahaca",
            "datasubset" : ObjectId("59f083d8d653230f55e0218f"),
            "dataInputsKind" : "datasubset"
        }
    ]
```

Then, when I find the object, I populate it like this (I have tried other ways unsuccessfully): 
```
    .populate({
      path: 'dataInputs.datafile',
      model: 'DataFile'
    })
    .populate({
      path: 'dataInputs.datasubset',
      model: 'DataSubset'
    })
```
The populated object looks like this, with this null values from fields that were not there in the original object:  
```
"dataInputs": [
        {
            "flag": "potato",
            "datafile": {
                "_id": "59ce7046b2ac0713a694210b",
                // Nice info about the object, yay, it populates!
            },
            "datasubset": null,
            "dataInputsKind": "datafile"
        },
        {
            "flag": "albahaca",
            "datasubset": {
                "_id": "59f083d8d653230f55e0218f",
                // Nice info about the object, yay, it populates!
            },
            "dataInputsKind": "datasubset"
        }
    ]
```
