### ISSUE TITLE
Recursive Schema type makes an error

### ISSUE THREAD

**Issue by alanpurple** [Automattic/mongoose#3056]
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ReplySchema = new Schema({
    nickName: { type: String, unique: true, required: true },
    content: String,
    replies: [ReplySchema]
}, { _id: true });

==========================================================

~\node_modules\mongoose\lib\schema.js
:298
      throw new TypeError('Invalid value for schema Array path `'+ prefix + ke
            ^
TypeError: Invalid value for schema Array path `replies`
    at Schema.add (~\node_modules\mon
goose\lib\schema.js:298:13)
    at new Schema (~\node_modules\mon
goose\lib\schema.js:88:10)
    at Object.<anonymous> (~\models\r
eply.js:4:19)

**Comment by alanpurple** [comment]
just add 

============================
var ReplySchema = {};

ReplySchema = new Schema ...
============================

removed that error but it turns out to be [{}]

**Comment by vkarpov15** [comment]
That's just how JavaScript works -

```javascript
var ReplySchema = new Schema({
nickName: { type: String, unique: true, required: true },
content: String,
replies: [ReplySchema]
}, { _id: true });
```

`ReplySchema` is undefined when you say `replies: [ReplySchema]`. Do this instead:

```javascript
var ReplySchema = new Schema({
nickName: { type: String, unique: true, required: true },
content: String
}, { _id: true });

ReplySchema.add({ replies: [ReplySchema] });
```

That will give you the desired behavior.

**Comment by alanpurple** [comment]
@vkarpov15  thank you for this great kindness

**Comment by sedge** [comment]
@vkarpov15 Is this behaviour supported in mongoose 3.8? I'm doing something similar to OP's example, but I keep getting nested schema errors.

**Comment by vkarpov15** [comment]
It should work. Please post on github with a code sample demonstrating your
issue.

**Comment by prema6** [comment]
i created a recursive schema attribute as per above example - ReplySchema.add({ replies: [ReplySchema] });

My question now is, i see "replies" having "_id"'s created.  Can we eliminate the "_id" creation in recursive attributes ? is there a way ?

**Comment by lineus** [comment]
@prema6 When your nested schema is recursive, **the nested path's schema is a reference to the top level schema**.  

**So, any changes you make to the nested path's schema will also apply to the top level schema**  
( *e.g. if you remove the `_id` path from the replies's schema with `ReplySchema.remove('replies._id')`, it will also remove the `_id` property from the top level schema.*).

[This gist](https://gist.github.com/lineus/18e6405cb2c6b758a99c40338c6a31a5) shows the only way I could come up with to:
   1. Only create one schema
   1. Get recursion
   1. remove the _id property only from nested objects but still get a top level _id

@vkarpov15 is there a better way to do this?

**Comment by prema6** [comment]
Thank you for the response.

**Comment by vkarpov15** [comment]
@lineus @prema6 

```javascript
ReplySchema.add({ replies: [ReplySchema.clone().remove('_id')] });
```

See [clone](https://mongoosejs.com/docs/api.html#schema_Schema-clone) and [remove](https://mongoosejs.com/docs/api.html#schema_Schema-remove) in docs.

**Comment by vkarpov15** [comment]
@lineus that's a good point. I'll edit my comment to cross out my response, your response is more correct.
