### ISSUE TITLE
SomeFieldName : SomeType schema configuration doesn't work in mongoose v4 

### ISSUE THREAD

**Issue by Fonger** [Automattic/mongoose#3068]
The following code worked fine on mongoose `v3.8`
```js
var OrderSchema = new Schema({
	orderId: { type: String, required: true },
	createdDate: { type: Date, required: true },
	...
	paymentType: {
		type: String,
		subType: String
	},
	paymentResult: {
		...
	},
	_user: { type: Schema.Types.ObjectId, ref: 'User', required: true}
});
```

However, when I upgrade mongoose to `v4.0.5`
The following code gives a validation error

```js
var newOrder = new DB.Order({
	orderId: orderId,
	createdDate: new Date().getTime(),
	paymentType: {
		type: 'CREDIT',
		subType: 'INSTANT'
	},
	paymentResult: {
		......
	},
	_user: user._id
});
newOrder.save(function(err) { console.log(err); });
```

And the `err` is
```js
{ [ValidationError: Order validation failed]
  message: 'Order validation failed',
  name: 'ValidationError',
  errors: 
   { paymentType: 
      { [CastError: Cast to String failed for value "[object Object]" at path "paymentType"]
        message: 'Cast to String failed for value "[object Object]" at path "paymentType"',
        name: 'CastError',
        kind: 'String',
        value: [Object],
        path: 'paymentType' } } }
```

And if I change subdocument code from
```js
	createdDate: { type: Date, required: true },
	....
	paymentType: {
		type: String,
		subType: String
	},
```
to
```js
	createdDate: { type: Date, required: true },
	....
	paymentType: {
		type: { type: String } ,
		subType: { type: String }
	},
```

Everything works fine again.
Is the `SomeField : SomeType` in subdocument schema deprecated in v4?
We should always use `{ SomeField : { type: SomeType } }` in `subdocument` to avoid this error.

**Comment by vkarpov15** [comment]
Not at all, the reason is that you have a property named 'type', which confuses mongoose because then it  thinks that `paymentType` is of type string:

```javascript
    // Mongoose interprets this as 'paymentType' is a String field, rather than
    // 'paymentType' is a nested doc with properties 'type' and 'subType'
    paymentType: {
        type: String,
        subType: String
    }
```

Not sure why this actually worked in 3.8, perhaps something like #2592 helped. But you already found the correct solution, which is saying `type: { type: String }`.

**Comment by Fonger** [comment]
@vkarpov15  Oops! I didn't find out that `type` happened to be the property name for type configuration.
I'm sorry to ask such stupid question
Thank you for your kind explanation

**Comment by vkarpov15** [comment]
The fact that it works on 3.8 is a potential problem :) worth investigating at least.

**Comment by Fonger** [comment]
Sorry, I use `mongo` to view my database and find that
the whole `paymentType` is missing in the real database and so it doesn't work on mongoose 3.8
(However, in 3.8, it doesn't throw an error, so I thought it worked. It just ignored `paymentType`)

**Comment by vkarpov15** [comment]
Thanks for the clarification, I'll close this. 3.8 has a few quirks like that related to setting nested objects that 4.0 smoothed out.
