### ISSUE TITLE
API docs for Model#save not up to date/wrong

### ISSUE THREAD

**Issue by skleeschulte** [Automattic/mongoose#3073]
The API docs for Model#save are not up to date/wrong. Compare http://mongoosejs.com/docs/api.html#model_Model-save and https://github.com/Automattic/mongoose/blob/4.0.5/lib/model.js. For example, look at the parameters:

**API docs:**

    Model#save([options], product,)
    
    Parameters:
    
        [options] <Object> options set `options.safe` to override [schema's safe option](/docs/guide.html#safe)
        product, <function(err, > Number)} [fn] optional callback

**sourcecode:**

     * @param {Object} [options] options set `options.safe` to override [schema's safe option](/docs/guide.html#safe)
     * @param {function(err, product, Number)} [fn] optional callback

**Comment by vkarpov15** [comment]
Good call, thanks for pointing this out.
