### ISSUE TITLE
Identify fields with default not saved

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#3075]
I have a doc, let's say with only `_id`:

`{_id: 1}`

After the doc is already saved to the db I add a field to my Mongoose schema with a default value: 

```
{
    number: {type: Number, default: 1 }
}
```

Now, when I load `{_id: 1}` with mongoose I get `doc.number === 1` but the value is not saved to the db because defaults seems to be applied only during creation.

Now, in a ``pre('save', function(){...})` I want to set a value for that field, but if I check for: 
```
if(!this.number){
     // this will never be executed
}
```

The if block will never be executed because `this.number === 1` even if it won't be saved to the db.

How can I identify such a field?

**Comment by vkarpov15** [comment]
This was fixed for 4.0, see #2558. As a workaround for 3.8.x, you can check `if ('number' in this.$__.activePaths.states.default)` in pre middleware, but that's not really supported behavior, so use that workaround at your own risk :) I would recommend upgrading to 4.x.

**Comment by paglias** [comment]
thanks!

so in 4.0 default values for fields not existing in a document will be saved the next time  the doc is accessed/saved?

**Comment by vkarpov15** [comment]
yep, should be the case. If it's not the case, open up another issue :)
