### ISSUE TITLE
unique not working if duplicates already exist

### ISSUE THREAD

**Issue by isimmons** [Automattic/mongoose#3085]
```
email: {
        type: String,
        unique: true
    },
```

Using postman client was able to insert same data over and over.

From StackOverflow http://stackoverflow.com/questions/5535610/mongoose-unique-index-not-working it looks like some think the answer is to restart mongodb or even drop the table. In fact dropping the table and starting over is how I got unique to work but I don't think that's right because I wouldn't want to drop a production database.

I also tried 
```
email: {
        type: String,
        index: {
            unique: true,
            dropDups: true
    },
```
Thinking that would automatically drop the existing duplicate entries but that didn't work either.

So is this an issue with mongoose, mongodb, or am I not understanding how this works?

Thinking maybe a bug in mongodb because this issue apparently was resolved by restarting mongodb several times https://github.com/Automattic/mongoose/issues/56

**Comment by isimmons** [comment]
I see now dropDups was deprecated. http://stackoverflow.com/questions/30187688/mongo-3-duplicates-on-unique-index-dropdups  If the answer there is correct then I'll need to learn how to write a batch file to copy collections. 

So this simply won't work without removing the dups in some way first.

Leaving open in case anyone has other solution.

**Comment by vkarpov15** [comment]
Mongoose `unique` keyword does nothing more and nothing less than ensure that there's a [unique index](http://docs.mongodb.org/manual/tutorial/create-a-unique-index/) on the given key on your `mongod` instance. If you're copying data over, I'd recommend creating a unique index in the shell first:

```javascript
db.collection.createIndex( { a: 1 }, { unique: true } );
```

And then run some shell script that loads documents and then inserts them.

```javascript
var cursor = db.coll1.find();
while (cursor.hasNext()) {
  try { db.coll2.insert(cursor.next()); } catch(e) { /* probably duplicate key error */ }
}
```

**Comment by smzm** [comment]
Test it.

```json 
email: {
        type: String,
        unique: true,
        index:true
    },```
