### ISSUE TITLE
issue from downloading mongoose

### ISSUE THREAD

**Issue by KINGJP500** [Automattic/mongoose#3089]
i have receive this message while try to downloading mongoose on my computer.

C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-c
ore\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\n
ode-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\The Family\jstudio\nod
eproject\secondtemplate\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\buil
d\kerberos.vcxproj]
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
|
> bson-ext@0.1.9 install C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\
node_modules\bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if
not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" clean )  else (clean)

C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if
not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\The Family\jstudio\nodeproject\secondtempl
ate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node" --module_name=bson "--module_
path=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ex
t\build\Release" )  else (configure --fallback-to-build "--module=C:\Users\The Family\jstudio\nodeproject\secondtemplate
\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node" --module_name=bson "--module_pat
h=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\b
uild\Release" )

C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if
not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" build --fallback-to-build "--module=C:\Users\The Family\jstudio\nodeproject\secondtemplate\
node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node" --module_name=bson "--module_path
=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\bu
ild\Release" )  else (build --fallback-to-build "--module=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_mo
dules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node" --module_name=bson "--module_path=C:\Use
rs\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Rel
ease" )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\The Family\jstudio\nod
eproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\buil
d.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "
build" "--fallback-to-build" "--module=C:\\Users\\The Family\\jstudio\\nodeproject\\secondtemplate\\node_modules\\mongoo
se\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release\\bson.node" "--module_name=bson" "--module_path=C:\\Users
\\The Family\\jstudio\\nodeproject\\secondtemplate\\node_modules\\mongoose\\node_modules\\bson\\node_modules\\bson-ext\\
build\\Release"
gyp ERR! cwd C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules
\bson-ext
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\The Family\js
tudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node -
-module_name=bson --module_path=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_module
s\bson\node_modules\bson-ext\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\The Family\JStudio\nodeproject\secondtemplate\node_mod
ules\mongoose\node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\Users\\The Family\\JStudio\\nodeproject\\secondtemplate\\node_modules\\mongoose\\n
ode_modules\\bson\\node_modules\\bson-ext\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-bu
ild"
node-pre-gyp ERR! cwd C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\nod
e_modules\bson-ext
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\The Family\jstudio\nodeproject\secondtemplat
e\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path
=C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\bu
ild\Release' (1)

C:\Users\The Family\jstudio\nodeproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if
not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build t
ools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting t
he Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\The Family\jstudio\nod
eproject\secondtemplate\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]

**Comment by vkarpov15** [comment]
Just a warning that you don't have the dependencies for node-gyp set up. That's fine, mongoose should still work normally.

**Comment by KINGJP500** [comment]
how can you fix that please because when i say node server.js i have found some error

**Comment by vkarpov15** [comment]
What's the error message when you start your server?

**Comment by KINGJP500** [comment]
i have this type of error, everything complete  but i can't compile . this is the error i got 

PS C:\Users\The Family\jstudio\nodeproject\secondtemplate> cd..
PS C:\Users\The Family\jstudio\nodeproject> cd firsttemplate
PS C:\Users\The Family\jstudio\nodeproject\firsttemplate> node server.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
C:\Users\The Family\jstudio\nodeproject\firsttemplate\config\passport.js:69
      clientID: configAuth.facabookAuth.clientID,
                                       ^
TypeError: Cannot read property 'clientID' of undefined
    at module.exports (C:\Users\The Family\jstudio\nodeproject\firsttemplate\config\passpor
    at Object.<anonymous> (C:\Users\The Family\jstudio\nodeproject\firsttemplate\server.js:
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
 i have  declare clientid in my project it also say it not defined

**Comment by vkarpov15** [comment]
The error is in your passport code - you have a typo: `clientID: configAuth.facabookAuth.clientID` probably should be `clientID: configAuth.facebookAuth.clientID`, note that 'Facebook' is spelled with an 'e'. Either way, has nothing to do with mongoose.

**Comment by KINGJP500** [comment]
ok thanks for the notice

**Comment by KINGJP500** [comment]
how could you help me to add visual studio 2013 to my computer path environment please.?

**Comment by vkarpov15** [comment]
No idea, I don't really use windows much. Try upgrading to mongoose 4.0.6 and then emptying out your `node_modules` directory and re-installing, that should give you fewer errors.

**Comment by KINGJP500** [comment]
ok thanks
