### ISSUE TITLE
find object ids in document with array

### ISSUE THREAD

**Issue by elgubenis** [Automattic/mongoose#3090]
hi, great job you are doing with mongoose, thank you very much!

we have one problem though: we can't find documents which have a specific ObjectId in a array of these documents, here I will put an example:

2 example documents of users:
---
```bson
{
  "_id": ObjectId("abc"),
  "name": "Miroslav",
  "tenants": [
    ObjectId("123"),
    ObjectId("456")
  ]
}

{
  "_id": ObjectId("abd"),
  "name": "Lothar",
  "tenants": [
    ObjectId("123"),
    ObjectId("694")
  ]
}
```

working mongodb query:
---
```js
db.users.find({ "tenants": new ObjectId("123") });
```

failing mongoose queries (not failing.. but returning an empty array..):
---
```js
Users.find({ "tenants": mongoose.Types.ObjectId("123") });
Users.find({ "tenants": new ObjectId("123") });
```

We also tried aggregates, unwinding the tenants array and using match, elementMatch whatsoever, the same agregates with the native mongodb driver return the documents which have the Item ObjectId("123"), so i thought it should have something to do with mongoose then.

Having debugging enabled i saw surprisingly that in effect mongoose sends the same query which i am executing in robomongo for example, mongoose does not return anything but the mongo-cli or robomongo with the same query do return what i would expect.

```sh
Mongoose: users.find({ tenants: ObjectId("5586c3cba0d822b7341fc0d4") }) { fields: undefined }  
```

the tenants type inside the user schema is [{ type: mongoose.Schema.Types.ObjectId, ref: 'tenant' }]

im using mongoose 4.0.5

what could i do to make it work?

**Comment by elgubenis** [comment]
if i write the following aggregate:
```coffee
MasterUser.aggregate [
      $unwind: '$tenants'
    ,
      $match:
        'tenants': new ObjectId(tenantId)
  ], (err, results) ->
    callback err, results
```

the mongoose debugging does not cast the ObjectId right:
```sh
Mongoose: users.aggregate([ { '$unwind': '$tenants' }, { '$match': { tenants: 5586c579936847d236fbdc03 } } ]) {} 
```

the same thing happend if i use the mongoose ObjectId Type:
```coffee
mongoose.Types.ObjectId(tenantId)
```

**Comment by elgubenis** [comment]
Fun fact i forgot to mention: if i change the arrays item type to string, and search the string, everything works as expected, its only if its of type ObjectId that it doesnt work.

**Comment by elgubenis** [comment]
neither does findOne work
```sh
Mongoose: users.findOne({ tenants: ObjectId("5580b0695b03e2e592bf722e") }) { fields: undefined }  
```

it works though if the document which im searching is having a string with that id and if im searchinf for the string instead of using ObjectId()

**Comment by elgubenis** [comment]
just found out that it works with version 3.8.31 :)

**Comment by vkarpov15** [comment]
This looks related to #3079, but I haven't been able to reproduce this in any case. Can you send me the following:

1. Mongo shell output that contains one user for which this is happening, exactly.
1. Your complete mongoose schema
1. Output of `npm list | grep "mongo"`

so I can try to debug a little more?

**Comment by vkarpov15** [comment]
No response for a while. Re-open if this is still an issue.

**Comment by Davidrl1000** [comment]
I am experiencing this issue, did you find any solution to this?

**Comment by vkarpov15** [comment]
@Davidrl1000 please provide repro instructions / code samples.

**Comment by bdspen** [comment]
I have also experienced this issue.

Say we have a structure like this:
`"{
    "_id": {
        "$oid": "579bd8fd38bb938ebcc61881"
    },
dtc": [
        {
            "dtcId": {
                "$oid": "5751f31ec20539f106fdb9ee"
            },
            "timesSeen": 2
        }
    ]
}`
A query like this:
`{_id: dtcId, 'dtc.dtcId': fooId }`
where dtcId matches the  document's id ("579bd8fd38bb938ebcc61881") and fooId matches the $oid in the array "5751f31ec20539f106fdb9ee",
will return null, though there is in fact an item in the "dtc" array in the object I am looking for.

**Comment by Mayocampo** [comment]
Same issue happening nowadays. Can get documents with an specific objectId() inside an array

/*My model*/
```
const clubSchema = mongoose.Schema({
    _id: {type: mongoose.Schema.Types.ObjectId, required: true},
    Nombre: {type: String, required: true},
    Ciudades: {type: [{type: mongoose.Schema.Types.ObjectId, ref: 'City'}], required: true},
    Responsable: {type: String, required: true},
    Telefono: {type: String, required: true},
    Direccion: {type: String, required: true},
    Ligas_id: {type: mongoose.Schema.Types.ObjectId, required: true, ref: 'League'}
}
```

/*My route*/
```
router.get('/byCity/:id', (req, res, next) => {
    const id = req.params.id;

    League
        .find()
        .where("Ciudades").in([id]) // Tried this way and using find({"Ciudades": id})
        .exec()
        .then(result => {
            console.log(result);
            routingResult.Success(res, result, 200);
        })
        .catch(err => {
            console.error(err);
            routingResult.Error(res, err);
        });
});
```

/*My mongo collection*/
```
_id: 5aea1a00bf7eddae0a37f134
Nombre: "some name"
Ciudades: Array
   0: 5ae7a3d0ce8d5d97a3ce025d
Responsable: "some string"
Teléfono: "some phone"
Dirección: "some address"
Ligas_id: 5ae7be26ce8d5d97a3ce05a1
```

Searching docs by any other of the ObjectId fields, works without problems..

Any solution to this?

**Comment by shubham-rathod1** [comment]
experienced the same issue does anyone have fix for this?

**Comment by shubham-rathod1** [comment]
> experienced the same issue does anyone have fix for this?
I found I had this issue because of my import.
I was importing a JSON file using MongoDB compass.
