### ISSUE TITLE
model.markModified multiple arrays

### ISSUE THREAD

**Issue by naeemshaikh27** [Automattic/mongoose#3093]
I have 10 embedded arrays in my model, where I require to update them using model.save(),
How do update them in one statement. currently I need to do this:

```
       profile.markModified('businessProcessAreas');
       profile.markModified('enterpriseSoftwares');
       profile.markModified('developmentSoftwares');
       profile.markModified('vendorServices');
```
Is there any support for this yet. This would be a great feature!

**Comment by vkarpov15** [comment]
Can't really support this effectively without ES6 proxies or `Object.observe()`, and both suffer from sub-optimal performance atm.

Better solution would be to [use `.set()` explicitly whenever you're modifying an array index](http://mongoosejs.com/docs/faq.html)

**Comment by naeemshaikh27** [comment]
I have the array already set, without using set().

**Comment by vkarpov15** [comment]
Can you clarify that please? I don't understand. Code example would be helpful.

**Comment by naeemshaikh27** [comment]
I get a complete request from browser, so i simply pass req.body to the profile  model, so i wont need to set() any array,

I give you a rough example,
```
profile.someDoc=req.body;

profile.save(function(err, data) {
   
         if (err) {
           return cb(err, null);
         }
         return cb(null, profile);
       });

```

Now as i already have a request which in the form that i can directly use in my model, I dont need to set().

So for this purpose i need to use markModified multiple times, which is quite painful

**Comment by vkarpov15** [comment]
In this case you shouldn't need `markModified()` at all, `markModified` is only really necessary if you're setting array indexes like `doc.myArray[0] = 'hello, world!'`. `doc.myArray = ['hello, world!']` or `doc.mySubDoc = { myArray: ['hello, world'] }` should work without `markModified`.

**Comment by naeemshaikh27** [comment]
doesnt really work, it works after markmodified.

**Comment by vkarpov15** [comment]
Can you provide me a more complete example? Preferably a standalone script that contains your schemas and the data you're using to trigger this?

**Comment by naeemshaikh27** [comment]
File schema:
```
var profileSchema = new Schema({

 arrayFirst: [{
    type: Number,
    ref: 'arrayFirst',
  }, ],
  arraySecond: [{
    type: Number,
    ref: 'v',
  }, ],
  arrayThird: [{
    type: Number,
    ref: 'arrayThird',
  }, ],
  arrayFourth: [{
    type: Number,
    ref: 'arrayFourth',
  }, ],
  
});
module.exports = profileSchema;
```

file controller:
```
perosnalProfile=req.body;
Profile.findOne({email: emID},
     function(err, profile) {
       if (err) {
         return cb(err, null);
       }
       if (!profile) {
         return cb(err, null);
       }
       var updated = _.merge(profile, perosnalProfile);
       profile = updated;
       profile.markModified('arrayFirst');
       profile.markModified('arraySecond');
       profile.markModified('arrayThird');
       profile.markModified('arrayFourth');
       console.log(profile);
       profile.save(function(err, data) {
         console.log('profile updated===');
         console.log(data);
         if (err) {
           return cb(err, null);
         }
         return cb(null, profile);
       });
     });
```


Hope this helps, here i find the document which needs to be updated, then merge it using `lodash.merge`, and then update it, all fields get updated which are not embedded arrays, unless i use `profile.markModified();`

Now I can not use `set()` as everything is already merged, and to persist the data while saving to the db, i need to mark it as modified using `markModified()`.
As you can see i have four arrays here, i will need to mark them all as modified.

Can we have a single method which can handle  multiple parameters like:
```
  profile.markAllModified(['arrayFirst','arraySecond','arrayThird','arrayFourth']);
```

This way we would not require to observe the model using `Object.observe()`, instead we would be just introducing a new method which would let me specify all modified arrays with ease.

**Comment by naeemshaikh27** [comment]
Thanks

**Comment by vkarpov15** [comment]
So the following script works fine for me in 4.0.6:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var _ = require('lodash');
mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3093');

var profileSchema = new Schema({

 arrayFirst: [{
    type: Number,
  }, ],
  arraySecond: [{
    type: Number,
  }, ],
  arrayThird: [{
    type: Number,
  }, ],
  arrayFourth: [{
    type: Number,
  }, ],

});

var User = mongoose.model('User', profileSchema);

var u = new User();

u = _.merge(u, {
  arrayFirst: [1],
  arraySecond: [2],
  arrayThird: [3],
  arrayFourth: [4]
});

u.save(function(error) {
  User.findById(u._id, function(error, user) {
    console.log(JSON.stringify(user));
    assert.ok(user.arrayFirst.length);
    process.exit(0);
  });
});
```

No markModified necessary. Can you check the above script and verify that it works for you?

Also, since you're using lodash, you can easily just do `['arrayFirst','arraySecond','arrayThird','arrayFourth'].each(profile.markModified);`

**Comment by naeemshaikh27** [comment]
Can you try save inside findOne.. I can still reproduce this.

**Comment by vkarpov15** [comment]
The issue is that `_.merge` does a deep copy, which doesn't handle arrays particularly gracefully.

```javascript
u = _.merge(u, {
  arrayFirst: [1],
  arraySecond: [2],
  arrayThird: [3],
  arrayFourth: [4]
});
```

roughly translates to

```javascript
u.arrayFirst[0] = 1;
u.arraySecond[0] = 2;
u.arrayThird[0] = 3;
u.arrayFourth[0] = 4;
```

which is really bad. It's especially bad for mongoose because of [the first question on the mongoose FAQ](http://mongoosejs.com/docs/faq.html). Use `_.extend()` instead:

```javascript
u = _.extend(u, {
  arrayFirst: [1],
  arraySecond: [2],
  arrayThird: [3],
  arrayFourth: [4]
});
```

**Comment by ajbieber** [comment]
Just to confirm what is being said here...

I have 5 documents based on the following model:

```javascript
name: {
  type: String
},
meta: {
  type: mongoose.Schema.Types.Mixed,
  default: {}
}
```

If I want update each of my documents using 
```javascript
Model.updateMany(docs, { meta: { message: 'Hello' }} )
```
then it will replace all of the 'meta' fields in my 5 documents, not add to them.

If I already had data in the meta fields, this will be deleted. Am I correct with this assumption? If not, is there a way I can add to a 'Mixed' field using Model.updateMany() without completely replacing it.

Thanks!

**Comment by vkarpov15** [comment]
@ajbieber you're correct, `Model.updateMany({}, { meta: { message: 'Hello' } } )` will replace the `meta` property in all documents. If you want to add a `meta.message` property instead, do this:

```javascript
Model.updateMany({}, { 'meta.message': 'Hello' })
```

**Comment by IlyaEremin** [comment]
@vkarpov15 `_.merge` works recursively for every field. `_.extend` copy top level fields into destination object which is not desired behaviour in every case. So what can I do when I need to update bunch of fields, some of them are arrays, some of them is nested object with array inside? Is there any alternative to `markModified`?

**Comment by vkarpov15** [comment]
@IlyaEremin I don't understand your question, can you please clarify with some code samples?

**Comment by IlyaEremin** [comment]
I guess my question is not related to this issue, nevermind.
