### ISSUE TITLE
$each $position v up to 3.9

### ISSUE THREAD

**Issue by Renouveaux** [Automattic/mongoose#3095]
Hi, 

I' have some trouble with using $position and $each with Mongoose since the 3.9.* version.
This is my code
```javascript
Patients.findByIdAndUpdate(query.id,
	{
		$push: {
			patientData: {
				$each: [{
					status: 'active',
					room: query.info.room,
					braden: query.info.braden,
					services: query.info.services,
					date: new Date
				}], $position: 0 
			}
		}
	});
```
This part of code work on 3.8.x, and I can't return to this version number.
If you have an idea.

Thanks for your reply.

**Comment by vkarpov15** [comment]
Which version are you using now? 3.9.x is marked as deprecated in npm, it was a development release, and should not be used for any reason.

**Comment by Renouveaux** [comment]
Hi,
I used the last release 4.0.6.

**Comment by vkarpov15** [comment]
Check the [migration guide](http://mongoosejs.com/docs/migration.html). In 4.0, the `new` property to `findOneAndUpdate()` is false by default, so when you call `findOneAndUpdate()` the document you get back is the document as it was **before** the updates were applied.
