### ISSUE TITLE
(suggestion) Schema.Types.Array.maxLength

### ISSUE THREAD

**Issue by alanpurple** [Automattic/mongoose#3096]
{type:[someSchema],maxLength:5}

how about this?

**Comment by vkarpov15** [comment]
Worth discussing as a new feature, but right now you can easily implement it as a plugin.

**Comment by alanpurple** [comment]
yeah I'm using custom plugin currently, thanks

**Comment by vkarpov15** [comment]
Yeah plugin is really the way to go for this one, we can't really support it in general because mongoose never really knows the length of the array it's `.push()`-ing to...
