### ISSUE TITLE
How to get indexes from model instance

### ISSUE THREAD

**Issue by skleeschulte** [Automattic/mongoose#3098]
Given a model instance I need to find the indexes defined on it's schema. A model instance has a `schema` property, which in turn has an `_indexes` property which contains the information I'm looking for. But I guess the leading underscore marks this property as "private" in the sense of "don't use this property, it's not meant to be accessed directly and can change at any time". Am I right? And if so, what is the correct way to get the indexes from a model instance?

**Comment by vkarpov15** [comment]
Do you need to get the indexes defined on the mongoose schema or the actual indexes defined on the mongodb server? For the latter, `Model.collection.indexes(function(error, indexes) {});` [should access the underlying driver's method for getting all indexes defined on the collection](http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#indexes). If you're looking for the indexes defined on a schema, which in theory is a subset of the indexes defined on the mongodb server as long as mongoose's index build succeeded, [`var indexes = Model.schema.indexes();` should work](http://mongoosejs.com/docs/api.html#schema_Schema-indexes)

**Comment by ORESoftware** [comment]
@vkarpov15 yeah I don't follow.. what is Model.collection?

**Comment by ORESoftware** [comment]
Ok this works for me...

```

router.get('/', function (req, res, next) {

  let models = mongoose.models;

  async.mapLimit(models, 6, function (m, cb) {

    m.collection.indexes(function (err, indexes) {

      if (err && err.message === 'no collection') {
        return cb(null, {
          name: 'no collection'
        })
      }
      cb(err, {
        name: indexes
      })
    });

  }, function (err, results) {

    if (err) {
      return next(err);
    }

    res.json({
      success: results
    })
  })

});
```

**Comment by abhishek11210646** [comment]
db.getCollectionNames().forEach(function(collection) {
   indexes = db[collection].getIndexes();
   print("Indexes for " + collection + ":");
   printjson(indexes);
});
