### ISSUE TITLE
add NumberInt SchemaType support!!

### ISSUE THREAD

**Issue by rambo-panda** [Automattic/mongoose#3102]
Hope to increase `MongoDB NumberInt` support

like:
http://stackoverflow.com/questions/8218484/mongodb-inserts-float-when-trying-to-insert-integer
https://raw.githubusercontent.com/paulcsmith/mongoose-currency/master/index.js

**Comment by 285858315** [comment]
+1

**Comment by GlennGeenen** [comment]
+1

**Comment by codeback** [comment]
+1. We need it to use Bitwise query operators:
http://docs.mongodb.org/manual/reference/operator/update/bit/
https://jira.mongodb.org/browse/SERVER-3518

**Comment by vkarpov15** [comment]
I'll put it on the docket for the near future. It's not that big of a deal, because with the way the mongodb driver works, any Number that's an int (that is, equal to Math.floor of itself) gets sent over to mongodb as an int.

**Comment by lvarayut** [comment]
+1 I also need this type.

**Comment by vkarpov15** [comment]
https://www.npmjs.com/package/mongoose-int32
