### ISSUE TITLE
Error handling with Q in pre save hook

### ISSUE THREAD

**Issue by xyleen** [Automattic/mongoose#3104]
Hey!

I've seen you already have a few issues about hooks&promises integration and it seems I've stumbled upon some funky case regarding this combo and error handling:

```javascript
var q = require('q');
var mongoose = require('mongoose');

// setup

var FooSchema = new mongoose.Schema({
    bar: String,
});

FooSchema.pre('save', function (next) {
	q().delay(100).then(function () {
		throw new Error('Error in pre save hook in FooSchema');
	}).catch(function (err) {
		next(err);
	}).done();
});

var Foo = mongoose.model('Foo', FooSchema);


// script

var foo = new Foo({ bar: 'baz' });

q.ninvoke(foo, 'save').then(function () {
	console.log('foo saved!');
}).catch(function (err) {
	console.error(err);
	console.error(err.stack);
}).done();
```
the output:
```
[Error: Error in pre save hook in FooSchema]
Error: Error in pre save hook in FooSchema
    at /test/testcase.js:12:9
    at _fulfilled (/test/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/test/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/test/node_modules/q/q.js:796:13)
    at /test/node_modules/q/q.js:604:44
    at runSingle (/test/node_modules/q/q.js:137:13)
    at flush (/test/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)
```

The code above works as intended - the pre middleware throws an error, catches it in `catch` block and passes it to `next` callback. This results in a promise rejection while invoking `'save'` with `q` - which is handled again in `catch` block. The script above exits with 0 exit code (success).

With a very little change in a hook (notice no function expression in catch block):
```javascript
FooSchema.pre('save', function (next) {
	q().delay(100).then(function () {
		throw new Error('Error in pre save hook in FooSchema');
	}).catch(next).done();
});
```
the output:
```
[Error: Error in pre save hook in FooSchema]
Error: Error in pre save hook in FooSchema
    at /test/testcase.js:12:9
    at _fulfilled (/test/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/test/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/test/node_modules/q/q.js:796:13)
    at /test/node_modules/q/q.js:604:44
    at runSingle (/test/node_modules/q/q.js:137:13)
    at flush (/test/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)

/test/node_modules/q/q.js:155
                throw e;
                      ^
Error: Error in pre save hook in FooSchema
    at /test/testcase.js:12:9
    at _fulfilled (/test/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/test/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/test/node_modules/q/q.js:796:13)
    at /test/node_modules/q/q.js:604:44
    at runSingle (/test/node_modules/q/q.js:137:13)
    at flush (/test/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)
```
the error handling part of the code stops working as described above - apart from normal error handling in `catch` blocks, there is an additional unhandled error which is identical to the thrown/handled one.

Enviroment:
* Node version: v0.10.38
* Mongoose versions affected:
    * 4.0.6
    * 3.9.7
* The above case works as intended in mongoose@3.8.31

The workarounds I've found:
* wrap `next` in function expression
* remove `.done()` in promise chain in the hook

I'm very curious what is causing this issue - I've tried debugging q and mongoose code, but I have to admit defeat. :(   My guess is that there's some shady stuff is going on when promises are being handled by both `q` and `mpromise` - Icould be wrong though.

PS: Great work with the library - thanks!

**Comment by vkarpov15** [comment]
The issue is that, oddly enough, `next()` returns the mpromise wrapper around `save()` in your post hook. That's why the hook's `.done()` throws - it thinks its getting a rejected promise. The above commit should fix that, because `next()` really shouldn't have a return value.

Also, re: `q.ninvoke()`, I'd recommend you be careful with using that with mongoose re: #2864
