### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by abr4xas** [Automattic/mongoose#3105]
Error:

```js
/var/www/html/noodetest/node_modules/mongoose/lib/index.js:329
      throw new mongoose.Error.MissingSchemaError(name);
            ^
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (/var/www/html/noodetest/node_modules/mongoose/lib/index.js:329:13)
    at Object.<anonymous> (/var/www/html/noodetest/app/models/rrss.js:3:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/html/noodetest/server.js:36:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Model user:

```js
var mongoose     = require('mongoose'),
    Schema       = mongoose.Schema,
    Social       = mongoose.model('Social');

var userSchema   = new mongoose.Schema({
    name: { type:  Schema.Types.String, required: true },
    nick: { type:  Schema.Types.String, required: true },
    bio: { type:  Schema.Types.String, required: true },
    avatar: { type:  Schema.Types.String, required: false },
    rrss: [
        {
            type: Schema.Types.ObjectId, ref: 'Social'
        }
    ]
});

module.exports = mongoose.model('User', userSchema);
```

Model social:

```js
var mongoose     = require('mongoose'),
    Schema       = mongoose.Schema,
    User         = mongoose.model('User');

var socialSchema   = new mongoose.Schema({
    twitter: { type:  Schema.Types.String },
    github: { type:  Schema.Types.String },
    web: { type:  Schema.Types.String },
    user_id: [
        {
            type: Schema.Types.String, ref: 'User'
        }
    ]
});

module.exports = mongoose.model('Social', socialSchema);
```

```js
// Load models
var Social = require('./app/models/rrss'),
    User   = require('./app/models/user'),
    Schema = mongoose.Schema;
```

What i miss?

**Comment by vkarpov15** [comment]
You called `require()` on the social schema first, which attempts to compile the 'Social' model that references a 'User' model that isn't defined until later. Since you have circular refs, there's no way for mongoose to successfully compile these models, which is fine since circular refs are often indicative of poor schema design choices.

**Comment by abr4xas** [comment]
Oh, i see... Well, thanks :)

**Comment by SkateFreak** [comment]
@vkarpov15 

Can you please explain a little more?
Did you mean that using ```refs``` is not a good choice?

I have 2 different servers to hold ```User``` and ```Product``` databases.
Each ```User``` has a list of product ids (using mongoose's refs) and I'm getting the same error...
Do i have to rethink my implementation?

**Comment by vkarpov15** [comment]
Using refs is reasonable, usually having two models reference each other is unnecessary though. Either a user should have a list of products or a product has a list of users, but rarely necessary to have both.

**Comment by ajsharp** [comment]
@vkarpov15 I agree that _sometimes_ models that bi-directionally reference each other reflects poor design choices, but other times it's just a necessary evil. Is there a recommended way of handling this? If so, could it be added to the docs? Or better yet, supported by the library.

**Comment by vkarpov15** [comment]
@ajsharp I don't know of any such cases off the top of my head. But, assuming there is such a case, there's nothing stopping you from having an array of refs in two different schemas that point to each other, I don't really see how adding that to the docs would help.

**Comment by zahrajoonjafari** [comment]
i have the same problem, can you explain that more how can i get ride of this error?

**Comment by lineus** [comment]
@zahrajoonjafari it's difficult to help without seeing your code. Please either join us in one of the following communities:

[Slack](https://mongoosejsteam.slack.com/)
[StackOverflow](https://stackoverflow.com/questions/tagged/mongoose)
[Gitter.im](https://gitter.im/Automattic/mongoose)

or open a new issue with a minimally complete code example that reproduces the problem you're having.

**Comment by joetidee** [comment]
It would be good to understand how to get around this problem of having two models that both require each other. I would have thought that the nature of using a document database such as MongoDB should facilitate data de-normalisation. If this is the case, then I would think it quite common to have models that require each other (?)

**Comment by vkarpov15** [comment]
@joetidee there are ways to "have models that require each other", but it depends on specifically what you mean by "require" - do you mean explicit Node.js `require()`? Perhaps you can clarify with a code sample?

**Comment by joetidee** [comment]
An example would be where I have `Item-model.js` which uses the `User` model:
`const User = mongoose.model('User');
`

and where I have `user-model.js` which uses the `Item` model:
`const Item = mongoose.model('Item');
`
I am currently loading these model files when my express server starts:
```
require('./user-model.js');
require('./item-model.js');
```

This causes an error to be thrown.

**Comment by vkarpov15** [comment]
How do you use itemModel in user-model.js ? Sounds like you could benefit from exporting schemas rather than models

**Comment by joetidee** [comment]
```
UserSchema.statics.foo = async function () {
  ...
  const result = await Item.bar();
  ...
};
```

**Comment by vkarpov15** [comment]
Ah, that's right, that has been a pain point in the past for me too. Try `this.db.model('Item').bar()` instead. That's how mongoose generally works around circular require() calls with models.

**Comment by joetidee** [comment]
Thank you. Would e great to post your answer here to help other too:
https://stackoverflow.com/questions/52677446/mongoose-circular-model-reference

**Comment by MaxVinogradov** [comment]
Hi! I have the same problem. Anybody have idea how to solve this?

**Comment by tbhaxor** [comment]
**Error**
```
Schema hasn't been registered for model "PaymentType".
Use mongoose.model(name, schema)
```

**Imports**
```js
const router = require('express').Router({ caseSensitive: true });
const User = require('../models/user');
const Staff = require('../models/staff');
const School = require('../models/school');
const { ObjectId } = require('mongoose').Types;
const config = require('../config.json');
const crypto = require('crypto');
const readChunk = require('read-chunk');
const fileType = require('file-type');
const AWS = require('aws-sdk');
const fs = require('fs');
const multer = require('multer');
const os = require('os');
const sg = require('@sendgrid/mail');
```

**Schema PaymentType**
```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// creating schema
const PaymentTypeSchema = new Schema({
  type: {
    type: String,
    enum: ['Cash', 'Cheque', 'RTGS', 'NEFT', 'Bank Transfers', 'UPI']
  },
  uid: String,
  transferredOn: Date
});

// exporting model
module.exports = mongoose.model('PaymentType', PaymentTypeSchema);
```

**Schema Staff**
```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// creating schema
const StaffSchema = new Schema({
  name: String,
  phoneNo: String,
  gender: {
    type: String,
    enum: ['Male', 'Female', 'Other']
  },
  maritalStatus: {
    type: Boolean,
    default: false
  },
  responsibility: {
    type: Schema.Types.ObjectId,
    ref: 'Subject'
  },
  isPermanent: {
    type: Boolean,
    default: true
  },
  relievingDate: Date,
  indentity: String,
  indentityType: String,
  type: {
    type: String,
    enum: [
      'Lab Incharge',
      'Teacher',
      'Receptionist',
      'Accountant',
      'Principal'
    ],
    default: 'Principal'
  },
  reportingAuthority: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Staff'
    }
  ],
  code: String,
  spouse: String,
  joiningDate: Date,
  classTeacherOf: {
    type: Schema.Types.ObjectId,
    ref: 'Class'
  },
  department: {
    type: Schema.Types.ObjectId,
    ref: 'Department'
  },
  personalEmail: String,
  officialEmail: String,
  bankDetail: {
    type: Schema.Types.ObjectId,
    ref: 'BankDetail'
  },
  payment: [
    {
      type: Schema.Types.ObjectId,
      ref: 'PaymentType'
    }
  ],
  resume: String,
  photo: String,
  section: String,
  confirmationDate: Date,
  classIncharge: { type: Schema.Types.ObjectId, ref: 'Class' },
  social: {
    type: Schema.Types.ObjectId,
    ref: 'Social'
  },
  dob: Date,
  nationality: {
    type: String,
    default: 'Indian'
  },
  bloodGroup: String,
  salary: {
    type: Schema.Types.ObjectId,
    ref: 'SalaryGrade'
  },
  school: {
    type: Schema.Types.ObjectId,
    ref: 'School'
  }
});

// exporting model
module.exports = mongoose.model('Staff', StaffSchema);
```

**Population**
```js
Staff.findById(user.info, { school: false })
          .populate('responsibility')
          .populate('reportingAuthority')
          .populate('classTeacherOf')
          .populate('department')
          .populate('bankDetail')
          .populate('social')
          .populate('payment')
          .populate('classIncharge')
          .populate('salary')
          .exec((err, staff) => {
            if (err) {
              // send 503
              console.log(err);
              res.sendStatus(503);
            } else {
              // send 200
              res.json({ success: true, data: staff });
            }
          });
```

**Comment by lucianrica** [comment]
In case people still encounter this problem, make sure you reference the MODEL as it is in mongoDB database. In my case i had a folder called models with User.js and Item.js, but the schema name on mongoDB is actually users and items. I referenced User and Item instead of schema name.
So, make sure you reference 
```users``` 
from
```const User = mongoose.model('users', UserSchema);```
