### ISSUE TITLE
Ensure index doesn't seem to be working on index change on schema.

### ISSUE THREAD

**Issue by codeHatcher** [Automattic/mongoose#3106]
In my schema I had to add an index. When I checked in my database, that schema was not present. I did not turn ensureIndex to false so I was expecting it to have updated as per the docs.

**Comment by vkarpov15** [comment]
Try listening to the `MyModel.on('index', function(err) {});` event and log any errors that occur. If mongoose fails to build an index, then the index won't be there.

**Comment by codeHatcher** [comment]
Thanks this helped me. It looks like it was unable to build the index because
the remote database was running mongodb 2.4 which doesn't support the GeoJSON
type I was using. I didn't understand what was going on because my local
database was 2.6 and I didn't expect the host I was using to not have such an
old version.
Thanks again.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Fri, Jun 26, 2015 at 6:35 AM, Valeri Karpov <notifications@github.com> wrote:
Try listening to the MyModel.on('index', function(err) {}); event and log any errors that occur. If mongoose fails to build an index, then
the index won't be there.

—
Reply to this email directly or view it on GitHub
[https://github.com/Automattic/mongoose/issues/3106#issuecomment-115690496] .[https://github.com/notifications/beacon/AFHNVlts7z_dlMHHFXf-jmwsUoWpkV_qks5oXUy1gaJpZM4FMiYF.gif]
