### ISSUE TITLE
Doc for SchemaString#maxlength; example is incorrect

### ISSUE THREAD

**Issue by rhmeeuwisse** [Automattic/mongoose#3111]
The 'custom error messages' example for SchemaString#maxlength is incorrect, see: http://mongoosejs.com/docs/api.html#schema_string_SchemaString-maxlength

The example demonstrates a max 10 characters validator but then validates a 10 character string, which would not produce a ValidationError.

**Comment by rhmeeuwisse** [comment]
I've gotten around to producing a PR to fix this and say a few other typos as well. See PR: https://github.com/Automattic/mongoose/pull/3123

**Comment by vkarpov15** [comment]
@rhmeeuwisse you're a champ, thanks.
