### ISSUE TITLE
Double JSON content with .populate and base64 content

### ISSUE THREAD

**Issue by bitflower** [Automattic/mongoose#3112]
I'm getting a malformed JSON output when using the populate function on a column that is an array of refs (ObjectIds). The child documents have image content encoded as base64 in one column. The size of the images is around 50-100k.

These are my models:

```javascript
    var VeranstaltungSchema = new Schema({
        name: {
            type: String,
            required: true
        },
        eventDate: {
            type: Date,
            default: Date.now
        },
        symbole: [{
            type: Schema.Types.ObjectId,
            ref: 'Symbole'
        }],
        isDefault: {
            type: Boolean,
            default: false
        }

    });
    module.exports = mongoose.model('Veranstaltung', VeranstaltungSchema);
```

```javascript
var SymboleSchema = new Schema({
    name: {
        type: String
    },
    dataURL: {
        type: String,
        required: true
    },
    valid: {
        type: Boolean,
        default: true
    },
    scores: {
        type: Number,
        default: 25
    },
    bonus: {
        type: Boolean,
        default: false
    }
});
module.exports = mongoose.model('Symbole', SymboleSchema);
```

This is my controller:

```javascript
    Veranstaltung.find({})
        .sort({
            isDefault: -1,
            name: 1
        })
        .populate('symbole')
        .exec(function(err, veranstaltungen) {
            if (err) {
                return handleError(res, err);
            }
            return res.json(200, veranstaltungen);
        });
```

Mongoose is not generating an error but the consuming client(s) do have problem reading the JSON. For example Angular 1.3.6 is reading it without a problem but Angular 1.4.1 doesn't.

You can see the doubling of the content on line 118:
https://gist.github.com/bitflower/a29a9292181a93c5722a

When I disbable the population the JSON is correct.

Any ideas? What can I do to further inspect? I'm quite new to Mongoose.

Thanks

**Comment by vkarpov15** [comment]
Can you show me what the JSON looks like?

**Comment by bitflower** [comment]
Hey @vkarpov15 it's in the gist i have put in the post. Helps? Thanks!

**Comment by bitflower** [comment]
Hi @vkarpov, I can investigate if you want. 

Any suggestions what I might test?

**Comment by bitflower** [comment]
The array "veranstaltungen" in the exec callback is fine! It has 3 items (.length).

It seems that the convertion to JSON fails in return res.json().

Maybe due to the base64 data ?

**Comment by bitflower** [comment]
Seems not to be related to mongoose but nodejs (see closed reference ticket).

I used the JSON.stringify() call instead which works.
