### ISSUE TITLE
Default mongodb driver timeout?

### ISSUE THREAD

**Issue by paton** [Automattic/mongoose#3114]
I've been getting this error occasionally.

"exception: collection or index disappeared when cursor yielded"

I've had someone suggest it may be due to the query timeout being set too low on the MongoDB driver.

What is the default timeout that Mongoose sets on queries sent to the driver?

**Comment by vkarpov15** [comment]
Neither mongoose nor the driver sets a cursor timeout, so [cursors get killed after 10 minutes by default](http://docs.mongodb.org/manual/core/cursors/). Are you keeping a cursor open for that long?

**Comment by paton** [comment]
What scenario might result in an open cursor? 
Does mongoose return a cursor for any operations?

I was under the impression that the cursor was abstracted away.

Thanks :)

**Comment by vkarpov15** [comment]
Cursor is abstracted away for the most part, you can still access it if you're using cursor for aggregation framework. Can you tell me more about the code that's triggering this issue?

**Comment by paton** [comment]
Here's a query that's causing the issue.

````
Collection.aggregate([
  {
    "$match": {
      "projectId": "553e12fac1dbade76cad942b",
      "type": "apples"
    }
  },
  {
    "$group": {
      "_id": "$state",
      "total": {
        "$sum": 1
      }
    }
  }
], function(err, data) {
   .....
})
````

This code triggers one of these 2 errors in about 1% of queries.

    MongoError: exception: collection or index disappeared when cursor yielded

and 

    MongoError: exception: errmsg: "PlanExecutor killed during plan selection"

**Comment by vkarpov15** [comment]
How long do you expect this aggregation to run for?

**Comment by paton** [comment]
Less than 1000ms in most cases.

**Comment by vkarpov15** [comment]
What version of mongodb is this? Also, can you check how long the queries that are causing these errors are taking?

You can try to [remove the cursor timeout](http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#addCursorFlag):

```javascript
var cursor = Model
    .aggregate([{ $match: { someAttribute: 'abc' } }])
    .cursor({ batchSize: 1000 })
    .exec();

  cursor.addCursorFlag('noCursorTimeout', true);

  var stream = cursor.stream();
  stream.on('data', function(doc) {
    console.log(doc);
  });
  stream.on('end', function() {
    console.log('done!');
    process.exit(0);
  });
```

**Comment by paton** [comment]
Strangely, I was able to fix this problem by removing one of the indexes I had on the collection.
