### ISSUE TITLE
Is there a way to check that a field is modified in pre save method ?

### ISSUE THREAD

**Issue by olasfar** [Automattic/mongoose#3115]
Hey guys,

No idea if such a method exists, it would be very helpful :)

If no, is there any work around ?

Thx,

**Comment by vkarpov15** [comment]
Use [`this.isModified('path')` in your pre save](http://mongoosejs.com/docs/api.html#document_Document-isModified)

**Comment by olasfar** [comment]
Thank you so much @vkarpov15
