### ISSUE TITLE
ENHANCEMENT: Consider http://json-schema.org/ specs

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#3116]
For the roadmap ahead, consider the JSON schema specification, which is:
1. standard,
2. much richer than mongoose schemas.

**Comment by nfroidure** [comment]
3. swagger ready

**Comment by vkarpov15** [comment]
Worth considering. It's a pretty expensive change to make because it'll change the way mongoose schemas are written. Are there other competing JSON schema specs out there?

**Comment by Reggino** [comment]
4. move validation to one of the available libraries, separation of concerns et al
