### ISSUE TITLE
Documents obtained with option _id: false  can't save, or be updated - remove/save methods fail silently 

### ISSUE THREAD

**Issue by sb2702** [Automattic/mongoose#3118]
User.findOne({username: username},  {_id:0},  function(err, user){
       
          user.remove(function(err){
             //Err is null,  
            // Document doesn't get removed
            // Fails silently
           });
  
     });

      User.findOne({username: username},  function(err, user){
       
           user.remove(function(err){
                  //document gets removed like normal
           });
      });

This happens for any update / remove / change to the doc.

I'm not sure if this is intended behavior. If it isn't, would it be possible to make it explicit in the docs or at least throw an error if the document isn't actually getting updated.

**Comment by vkarpov15** [comment]
Which version?

**Comment by sb2702** [comment]
4.0.6
