### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by fearhat** [Automattic/mongoose#3122]
Hello,

I was trying to insert ~10k elements into a collection via model.collection.initializeUnorderedBulkOp()
got following err:
```
c:\br\xml\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-
core\lib\topologies\server.js:796
      catch(err) { process.nextTick(function() { throw err}); }
                                                       ^
TypeError: undefined is not a function
    at c:\br\xml\node_modules\mongoose\node_modules\mongodb\lib\bulk\unord
ered.js:470:5
    at c:\br\xml\node_modules\mongoose\node_modules\mongodb\lib\bulk\unord
ered.js:424:9
    at resultHandler (c:\br\xml\node_modules\mongoose\node_modules\mongodb
\lib\bulk\unordered.js:393:5)
    at c:\br\xml\node_modules\mongoose\node_modules\mongodb\node_modules\m
ongodb-core\lib\topologies\server.js:795:13
    at Callbacks.emit (c:\br\xml\node_modules\mongoose\node_modules\mongod
b\node_modules\mongodb-core\lib\topologies\server.js:94:3)
    at null.messageHandler (c:\br\xml\node_modules\mongoose\node_modules\m
ongodb\node_modules\mongodb-core\lib\topologies\server.js:235:23)
    at Socket.<anonymous> (c:\br\xml\node_modules\mongoose\node_modules\mo
ngodb\node_modules\mongodb-core\lib\connection\connection.js:259:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

I've seen that bulk operations are currently not supported by mongoose (yet), is it going to happen soon?

**Comment by fearhat** [comment]
Issue can be closed, found the mistake and it wasn't even related to mongoose anyways.

**Comment by vkarpov15** [comment]
FWIW you need to wait for mongoose to connect before using `initializeUnorderedBulkOp()`:

```javascript
mongoose.connect(/*...*/);
mongoose.on('connected', function(error) {
  mongoose.collection.initializeUnorderedBulkOp();
});
```

Also, `initializeUnorderedBulkOp()` is [considered deprecated](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#q--a) so I'd have to warn against using it :)

**Comment by fearhat** [comment]
Thanks for the answer.

What would be an appropriate way to do large inserts?

**Comment by vkarpov15** [comment]
`MyModel.collection.insertMany()`, [see mongodb driver docs for details](http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#insertMany). `insertMany()` is the preferred way going forward according to the spec, although the fluent API with `initializeUnorderedBulkOp()` will still work for the foreseeable future.

**Comment by aminnaggar** [comment]
@vkarpov15 I can't find anything about `initializeUnorderedBulkOp` being deprecated (matter fact I can't find anything related to `initializeUnorderedBulkOp` anywhere, not in the docs, not anywhere)

If you could please guide me to page that would be awesome!!

**Comment by fearhat** [comment]
@aminnaggar :
https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#q--a
