### ISSUE TITLE
select virtuals does not work as expected

### ISSUE THREAD

**Issue by loulin** [Automattic/mongoose#3130]
```js
var personSchema = new Schema({
  firstName: : String,
  lastName: String,
  age: Number
}, {toJSON: {virtuals: true}});
personSchema.virtual('fullName').get(function () {
  return this.name.firstName + ' ' + this.name.lastName;
});
```
### Issue 1. If only virtuals are selected, it will throw error.
`Person.find({}, 'fullName')` =>
```
/home/projects/mean/node_modules/mongoose/lib/document.js:1893
        branch[part] = clone(self.get(path), options);
                     ^
TypeError: Cannot set property 'fullName' of undefined
    at applyGetters (/home/projects/mean/node_modules/mongoose/lib/document.js:1893:22)
    at model.Document.$toObject (/home/projects/mean/node_modules/mongoose/lib/document.js:1669:5)
    at model.Document.toJSON (/home/projects/mean/node_modules/mongoose/lib/document.js:1919:15)
    at clone (/home/projects/mean/node_modules/mongoose/lib/utils.js:224:18)
    at cloneArray (/home/projects/mean/node_modules/mongoose/lib/utils.js:305:14)
    at clone (/home/projects/mean/node_modules/mongoose/lib/utils.js:220:12)
    at cloneObject (/home/projects/mean/node_modules/mongoose/lib/utils.js:288:13)
    at clone (/home/projects/mean/node_modules/mongoose/lib/utils.js:233:16)
    at model.Document.$toObject (/home/projects/mean/node_modules/mongoose/lib/document.js:1666:13)
    at model.Document.toJSON (/home/projects/mean/node_modules/mongoose/lib/document.js:1919:15)
    at Object.stringify (native)
```

### Issue 2. If related fields are not included, virtual attributes will return undefined.
`Person.find({}, 'age fullName -_id')` => 
```js
person = {
  "age": 18,
  "fullName": "undefined undefined",
  "id": null
}
```

### Issue 3. Can't only select some of the virtuals.
```js
personSchema.virtual('displayName').get(function () {
  return 'Dear ' + this.name.firstName;
});
```
`Person.find({}, 'firstName displayName -_id')` => 
```js
person = {
  "firstName": "Lin",
  "displayName": "Dear Lin",
  "fullName": "Lin undefined", // still get this field
  "id": null // this is also got as a virtual
}
```

If these are designed features, someone may still be confused that virtuals does not work as expectd.

**Comment by vkarpov15** [comment]
Using a virtual with a projection doesn't make much sense. Since virtuals are not persisted to the database, selecting them in a projection won't work - `.select()` is used to specify which fields you want to query from the database. There's no way to conditionally disable virtuals atm.

The fact that it throws an error in the first case is a potential issue.

**Comment by loulin** [comment]
Thanks for your comments. I have got new secrets about virtuals.

If `virtuals` is set true and `select` is used at the same time, the related fields of virtuals must be specified, otherwise you will get unexpected virtual values.

**Comment by victorkohl** [comment]
Your first example fails because you are trying to retrieve `firstName` and `lastName` from `this.name`, which is `undefined`.

I tried reproducing it like this, and it didn't throw any errors:

```javascript
var personSchema = new Schema({
  firstName: String,
  lastName: String,
  age: Number
}, {toJSON: {virtuals: true}});
personSchema.virtual('fullName').get(function () {
  return this.firstName + ' ' + this.lastName;
});
```

This will return `'undefined undefined'`, but no errors are thrown.

**Comment by loulin** [comment]
Yes, you are experts and know how and why. For beginners, I think I can get the right `fullName` without selecting `firstName` and `lastName`, because the document just gives virtual definition.

For the first example, I can't reproduce it now. But I can get an intended error:
```js
var mongoose = require('mongoose'),
	Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/test');
var personSchema = new Schema({
	firstName: String,
	lastName: String,
	age: Number
}, {
	toJSON: {
		virtuals: true
	}
});
personSchema.virtual('fullName').get(function() {
	return this.firstName + ' ' + this.lastName;
});
var Person = mongoose.model('Person', personSchema);

var person = new Person({
	firstName: 'x',
	lastName: 'y'
});

person.save(function(err, p) {
	Person.findById(person._id, '-_id fullName', function(err, person) {
		console.log(person.toJSON()); // TypeError: Cannot set property 'fullName' of undefined
		//person.remove(); // Error: No _id found on document!
	});
});
```

**Comment by kksrini89** [comment]
@vkarpov15  still the above expected scenario will work?

**Comment by vkarpov15** [comment]
@kksrini89 "work" is a relative term. It won't crash, which is OP's issue, but mongoose doesn't support select() with virtuals.

**Comment by slorenzo** [comment]
@vkarpov15 I see it as a very good enhancement!
