### ISSUE TITLE
Typo in guide

### ISSUE THREAD

**Issue by adamzerner** [Automattic/mongoose#3138]
> .important :markdown In mongoose 4, a Query has a .then() function, and thus can be used as a promise.

On http://mongoosejs.com/docs/queries.html

I wouldn't think the `.important :markdown` is intended.

**Comment by vkarpov15** [comment]
Hmm not sure why the docs build did that, looks like jade may have bugged out. However, this doesn't happen for me locally, so it should be fixed in next release.
