### ISSUE TITLE
Retries are being delayed longer than expected

### ISSUE THREAD

**Issue by ryana** [Automattic/mongoose#3141]
Hey guys,

Any ideas what's going on here? I have a job that failed and got put into the retry queue. New jobs are coming along and things are running find, but this job is still sitting in the queue long after it should have been retried again:

![Odd retry queue behavior]
(https://dl.dropboxusercontent.com/spa/c8k9520tqhih2dg/7nztc0y2.png)

I see this intermittently. Can't reproduce it. When I do see it, there doesn't seem to be any pattern. That is, it's not always the same works, exception type, etc....

**Comment by vkarpov15** [comment]
I have absolutely no idea what's going on here. Where's this UI, what are these workers, what queue are you using?

**Comment by ryana** [comment]
Holy crap. Meant to put this Sidekiq's issue queue. Don't know what the heck I was thinking. Brainfart. Apologies :)

**Comment by vkarpov15** [comment]
No worries, happens :beers: :palm_tree:
