### ISSUE TITLE
when setting _id as a String, unable to fetch it in the result.

### ISSUE THREAD

**Issue by czheo** [Automattic/mongoose#3146]
In mongo console, I did something as below.
~~~ js
> db.tests.insert({name: "test1"})
> db.tests.insert({_id: "test2", name: "test2"})
> db.tests.find()
{ "_id" : ObjectId("559ce0bd1c670eb655265fb9"), "name" : "test1" }
{ "_id" : "test2", "name" : "test2" }
~~~

Using mongoose(coffeescript), when I did `Test.find()`, I can only get `test1` with `_id` returned but `test2` without `_id`
~~~ coffee
mongoose = require('mongoose').connect()
Test = mongoose.Model("Test")
Test.find (err, docs) -> console.log docs
# [ { _id: 559ce0bd1c670eb655265fb9, name: 'test1' }, { name: 'test2' } ]
~~~

How can I make `_id` return for `test2`?

**Comment by czheo** [comment]
Alright. I just figured out the solution - setting the schema with the type of `_id` explicitly to be String.
~~~ coffee
TestSchema = new mongoose.Schema({_id: String})
Test = mongoose.Model("Test", TestSchema)
~~~

Because as default, mongoose will use a schema for `_id` to be `ObjectId`, and if it is stored as `String` in mongodb, the value will be filtered out.

**Comment by czheo** [comment]
But if both `String` and `ObjectId` are used in `_id`, either type will be filtered out.

**Comment by vkarpov15** [comment]
Mongoose casts when you return docs, so it'll have a cast error for the second doc. If you do `docs[1].validate(function(error) {});` you'll see that `_id` is invalid.

**Comment by czheo** [comment]
@vkarpov15 Is it possible to turn the validation off for `_id`?

**Comment by vkarpov15** [comment]
You can just remove `_id` from your schema, that way mongoose won't touch your _id field when you save existing documents. Would that work for you?

**Comment by czheo** [comment]
@vkarpov15 No. I think `_id` will be treated as `ObjectId` as default even if I excluded it from my schema.

**Comment by vkarpov15** [comment]
You can set the [schema `_id` option to false](http://mongoosejs.com/docs/guide.html#_id)
