### ISSUE TITLE
Docs for findById still mention HexId

### ISSUE THREAD

**Issue by rhmeeuwisse** [Automattic/mongoose#3147]
The docs declare the id argument to be of type *ObjectId* or *HexId* / *HexString* in the following functions:

* [Model#findById](https://github.com/Automattic/mongoose/blob/c17162899a722fc3c451721477f195678027d4ae/lib/model.js#L1057)
* [Model#findByIdAndUpdate](https://github.com/Automattic/mongoose/blob/c17162899a722fc3c451721477f195678027d4ae/lib/model.js#L1403)
* [Model#findByIdAndRemove](https://github.com/Automattic/mongoose/blob/c17162899a722fc3c451721477f195678027d4ae/lib/model.js#L1526)

That seems outdated, the current [MongoDB docs](http://docs.mongodb.org/manual/core/document/#field-names) say this about the id field:

> The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type other than an array.

In practice that would mean the type may be a **ObjectId**, **Number** or **String**, although *Object*s or *Boolean*s are not illegal listing every type in javascript but Array is a bit impractical.

Should the docs therefore be updated to something like this?:

    @param {ObjectId|Number|String} id objectid, a value that is unique in the collection

**Comment by rhmeeuwisse** [comment]
Great, `Object|Number|String` is even more clear. 
No need to update the docs for `FindByIdAndUpdate` and `FindByIdAndRemove` as well?
Just say yes and I'll make the PR for you.

**Comment by vkarpov15** [comment]
Yes :)

**Comment by rhmeeuwisse** [comment]
Hehe, I wanted to build a clean diff so did a few do overs. See [PR](https://github.com/Automattic/mongoose/pull/3159) for the proper patch and ignore the other commits.
