### ISSUE TITLE
How do I update/recreate an index?

### ISSUE THREAD

**Issue by paambaati** [Automattic/mongoose#3148]
I have a schema with a particular TTL index that needs to be configurable. Say the TTL value is changed in configuration and the application is restarted, what is the best way to recreate or update the index?

**Comment by kbariotis** [comment]
Mongoose `index` function wont update indexes. Will only create them if not exists. This creates a problem cause you will end up having a lot of indexes around.

What I do, is manually deleting all indexes, before restart my app, so Mongoose will kick in and recreate them. But I am updating them very rarely.

What you could do, to automate it, is keep track of when the Index changed, drop all of the collection's indexes and let Mongoose recreate them.

Not sure though, about how the recreation of indexes will affect performance, so maybe someone else can clear this for us.

**Comment by vkarpov15** [comment]
@kbariotis is right. If you want to manage the TTL, you're going to have to do it manually. Mongoose is really not meant to manage indexes atm, because AFAIK changing the indexes' TTL requires dropping the index and then recreating it.

**Comment by paambaati** [comment]
@kbariotis Thanks, I figured I'd do the same thing, but just wanted to see if someone else had a different solution.

For anyone looking at the same problem, here's how I solved it - I just shoved this in the beginning of my model —

```
modelName.collection.dropIndex('indexName_1', function(err, result) {
    if (err) {
        console.log('Error in dropping index!', err);
    }
});
```

On each start of the application, whenever the model is `require()`ed, this is called and the index is dropped. Mongoose takes care of recreating the index automatically.

**Comment by vkarpov15** [comment]
I'd be very careful with doing that - as your data grows, index builds will get more and more expensive. If you have a lot of data and building indexes takes several hours, dropping indexes every time your server restarts will lead to sketchy performance.

**Comment by Liberateur** [comment]
Thank you for all this information, for my part I needed a script to reindex my databases during big changes, I share on this post because I fell several times over during my research.

### FILE : db.js
```
// Get mongoose
const mongoose = require('mongoose');

// Set debug not prod
mongoose.set('debug', config.prod);

// Connect
mongoose.Promise = global.Promise;
mongoose.connect(CONFIG_DB_HOST, CONFIG_DB_OPTIONS);

// Init
var userSchema = new mongoose.Schema(
{
	name:   { type:String },
	mail:   { type:String },
	adress: { type:String }
});

// Set index
userSchema.index(
{
	'name':    1,
	'mail':    1,
	'adress': -1
}, { name: 'KordaCloud' });

// Export
module.exports.users = mongoose.model('users', userSchema);
```


### FILE : db_reindex.js
```
// Get mongoose
const db = require('./db');

// Loop in all collections 
for(let i in db) if(db[i].schema)
{
	try
	{
		// Drop all indexes in collection
		db[i].collection.dropAllIndexes((err,res)=>
		{
			// Catch error
			if(err) return console.log(err);

			// Create index
			db[i].ensureIndexes((err)=>
			{
				// Catch error
				if(err) return console.log(err);
			});
		});
	}
	catch(e)
	{
		console.log(e)
	}
}
```

### REINDEX

Si vous avez des données dans vos collections, vous devez les réindexer. 

**For replica sets, reIndex will not propagate from the primary to secondaries. reIndex will only affect a single mongod instance.**

```
$ mongo mybase
db.getCollectionNames().forEach(function(collname)
{
  db.getCollection(collname).reIndex();
});
```

**Comment by elena-dev** [comment]
open

**Comment by vkarpov15** [comment]
Use [`Model.syncIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.syncIndexes)
