### ISSUE TITLE
exec() does not reset the conditions in query

### ISSUE THREAD

**Issue by buehler** [Automattic/mongoose#3151]
Hi there.

I was using mongooseJS and was surprised by a very misterious bug (IMO).

I am currently reusing the mongodb connection as intended. When I wan't to use the chaining feature of a query, the conditions are not correctly deleted when creating a new query. As I'm aware of, if you call "toConstructor" on a query, it generates a query which one can use for subqueries with the conditions merged. Now if I just want to search for something, the conditions are stored anyway, resulting in impossible query-conditions and wrong return values.

example:

reuse of the connection:

```javascript
function createConnection(user, pass, host, port, database) {
    return new Promise(function (resolve, reject) {
        if (mongoose.connection._readyState === 1) {
            return resolve(mongoose.connection.models);
        }

        mongoose.connect(buildConnectionstring(user, pass, host, port, database));
        mongoose.connection
            .on('error', function (err) {
                logger.emergency('Could not load / initialize database.', {kind: 'mongodb database', error: err});
                reject(err);
            })
            .once('open', function () {
                logger.info('Successfully connected to the database', {kind: 'mongodb database'});
                var db = require(__baseShared).models;
                resolve(db);
            });
    });
}
```

Now when I perform a search like this:

```javascript
db.User.findOne()
    .where('email').equals('test@test.com')
    .and([{loginToken: '...', {loginTokenDate: '...'}}]
    .exec(...)
```

The conditions of the query are correct for the first search. When you search for the second time (with the same code) the conditions on the query are duplicated. I get the email condition and 4 times the "and". The next time there are 6 conditions.

It seems, the conditions are static on the model, which is correct for a "toConstructor" but not for a normal query.

If I'm searching the normal way:

```javascript
db.User.findOne({ /* all conditions */ }, function(err, user){});
```

The conditions are cleared as expected.

I assume this is either a misbehavior because I reuse the connection or a bug?

Cheers
Chris

**Comment by vkarpov15** [comment]
You definitely should be able to re-use the connection. Are you reusing the query? That is, are you doing something like:

```javascript
var query = db.User.findOne();

function execQuery() {
  query.where('email').equals('test@test.com').exec();
}
```

**Comment by buehler** [comment]
I'm to blame myself.
I found the "bug". I was using a class to load some modules in a nodeJS application. Therefore I overwrote the toString() function of an object.

That object was passed into the query, which was checking
```javascript
mquery.canMerge(conditions)
```

now inside that mquery library, the check is performed as such:
```javascript
conds instanceof Query || utils.isObject(conds)
```

and utils.isObject does it like this:
```javascript
arg.toString() === '[object Object]'
```

now. as I mentioned, I overwrite the toString method, so this check was false for like, forever :smiley: 

I use another function on the prototype now for my toString behavior and the mongoose query works like a charm.

Thank you anyway for your help ;)

(what i don't get, is why mquery does not check typeof(args) === 'object')

Cheers
Chris
