### ISSUE TITLE
Aggregate cursor is undefined

### ISSUE THREAD

**Issue by TimonKK** [Automattic/mongoose#3160]
I am trying this code:
```javascript
var cursor = MyModel
	.aggregate([
		{
			$match: { 
				mark : "some mark" 
			}
		}
	])
	.cursor({ batchSize: 1000 })
	.exec();

cursor.each(function(error, doc) {
  console.log('cursor each', error, doc);
});
```
from [Mongoose API] (http://mongoosejs.com/docs/api.html#aggregate_Aggregate-cursor)
But i have 
```javascript
cursor.each(function(error, doc) {
	  ^
TypeError: Cannot read property 'each' of undefined
```

I am using
```javascript
node v.0.11.14
MongoDB version 2.6.6
mongoose 4.0.5
```

**Comment by vkarpov15** [comment]
One of the unfortunate quirks of the .aggregate() implementation right now is that it doesn't work with buffering, so you need to do

```
connection.on('connected', function() {

});
```

to wait for mongoose to connect to the db before using the aggregation cursor :(

**Comment by TimonKK** [comment]
It no work. 
I place my code in callback "mongoose.connect" - it start work.
But, if i do
```javascript
var cursor = MyModel
  .aggregate([
    {
        $match: { 
          mark : "some mark" 
        }
    }
  ])
  .cursor({ batchSize: 1000 })
  .exec(function() {
    // never cause
  });
					
cursor
  .on('error', function(err) {

  })
  .on('data', function(data) {
		
  })
  .on('end', function() {

  });
```
it is work too.

**Comment by vkarpov15** [comment]
Yeah another way to get it to work is in the `mongoose.connect()` callback. Aggregation cursor unfortunately doesn't work with buffering, so it will only start working once mongoose is connected to the db.

**Comment by timjnh** [comment]
Confirmed TimonKK's issue with on('connected') not working.  This does not work with mongoose 4.0.8 and mongo 3.0.3

    var schema = new mongoose.Schema(
        {
            account:  { id: Number },
            source: { id: Number },
        });
    
    var DocumentView = mongoose.model('DocumentView', schema);
    
    var connection = mongoose.createConnection('mongodb://localhost:27017/reporting');
    connection.on('connected', function() {
        var cursor = DocumentView.aggregate()
            .allowDiskUse(true)
            .group({ _id: { sourceId: '$source.id', accountId: '$account.id' }, count: { $sum: 1 } })
            .cursor({ batchSize: 1000 })
            .exec();
    
        console.log(cursor);
    });

cursor will be undefined.  However, if you use the mongoose.connect callback it does work:

    mongoose.connect('mongodb://localhost:27017/reporting', function() {

        var cursor = DocumentView.aggregate()
            .allowDiskUse(true)
            .group({ _id: { sourceId: '$source.id', accountId: '$account.id' }, count: { $sum: 1 } })
            .cursor({ batchSize: 1000 })
            .exec();

        console.log(cursor);
    });

**Comment by raoulwissink** [comment]
When adding the `async` cursor option I get the following error:

```
MongoError: cursor object can't contain fields other than batchSize
```

I am using:

```
NodeJS 4.2.4
MongoDB version 3.2.5
Mongoose 4.4.13
```

**Comment by vkarpov15** [comment]
@raoulwegat can you open up a separate issue with a code sample please?

**Comment by raoulwissink** [comment]
Yes of course, here you go: #4101.

**Comment by vkarpov15** [comment]
Thanks, much appreciated

**Comment by mhombach** [comment]
I think the label "pending release" is incorrect because this was already released to my understanding?

**Comment by vkarpov15** [comment]
@mhombach yep that's incorrect, I'll fix that.
