### ISSUE TITLE
findAndUpdate doesn't add date when creating new record

### ISSUE THREAD

**Issue by franciszabala** [Automattic/mongoose#3161]
Mongoose version: 4.0.6
MongoDB version: 2.6.6

If a document with that matches the query is not found, the document is saved successfully with the exception of the date record. 

model:
```javascript
var mongoose = require('mongoose');

var StudentSchema = new mongoose.Schema({
      udid: String,
      name: String,
      updated_at: { type: Date, default: Date.now },
},{ strict: true });

module.exports = mongoose.model('Student', StudentSchema);
```

query:
```javascript
    Student.findOneAndUpdate(query, req.body, {upsert:true}, function(err, post){
        if (err) return next(err);
        var response = "1 document saved";
        res.status(201).json({ status: '1', message:response});
    });
```

result:
```javascript
{
    "_id" : ObjectId("55a4c2e98931372777ce864a"),
    "name" : "+639174036937",
    "udid" : "8b691829daeaec12fb64d1aa9c3bbaa0",
    "__v" : 0
}
```

as you can see, the updated_at is missing.

**Comment by vkarpov15** [comment]
What's query and req.body? The fact that it saves a new document is by design - you specified the upsert option, that's what that option does.

**Comment by franciszabala** [comment]
Hi, sorry for the confusion. The record get saved but the updated_at record is not even if in the model has: dated_at: { type: Date, default: Date.now }.

**Comment by vkarpov15** [comment]
Defaults don't get set on `findOneAndUpdate()` unless you use 4.0's new `setDefaultsOnInsert` option:

```javascript
Student.findOneAndUpdate(query, req.body, { upsert:true, setDefaultsOnInsert: true }, callback);
```

**Comment by franciszabala** [comment]
Got it. Thanks!
