### ISSUE TITLE
Is there a plugin that can track data change and sync to client?

### ISSUE THREAD

**Issue by jackiesun8** [Automattic/mongoose#3166]
I use mongoose in a game server development. Mongoose has ability to track data change and sync to database.Now I want to sync data to client at data change.But this sync mechanism can't use mongoose's build-in.Because the sync opportunity is various(database'data is cached in memory and sync to database at player offline)

**Comment by vkarpov15** [comment]
Not that I know of. Node's `Object.observe()` function may be helpful, but I'm not sure how well that'll work with mongoose documents.

**Comment by jackiesun8** [comment]
@vkarpov15 mongoose's mechanism about tracking data change is?

**Comment by vkarpov15** [comment]
Not very extensible I'm afraid. At a high level, mongoose uses [Object.defineProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to define custom getters/setters for every field you define in your schema and uses those to track changes on documents.

**Comment by onbjerg** [comment]
Hmm, if I understand correctly this could prove useful: https://github.com/mWater/minimongo
