### ISSUE TITLE
Update validation using positional operator validates as error, still updates

### ISSUE THREAD

**Issue by valterkraemer** [Automattic/mongoose#3167]
When using a positional operator to update a value in an array of objects. It raises a validation error but still updates the value in the db.

    var MessageSchema = new Schema({
        recipients: [{
            user: {type: Schema.Types.ObjectId, ref: 'User', required : true},
            status: {type: String, enum:['active', 'archived'], required: true}
        }]
    })

    Message.update({
        'recipients.user': user._id
    }, {
        'recipients.$.status': 'hello'
    }, {
        runValidators: true
    }).exec(next);

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/9d9041f79f036b1a83ec00c4bb4f51d98283a819
