### ISSUE TITLE
Under certain circumstances undefined values are recorded in database as null values

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#3169]
To reproduce (with mongoose 3.8.33 and 4.07 + mongodb 3.0.4 and nodejs 0.12.7 on windows 8.1):

```
var mongoose = require('mongoose');

mongoose.connect("mongodb://localhost/TestDB", { server: { auto_reconnect: true, poolSize: 10 } });

var dummySchema = new mongoose.Schema({
    alpha             : { type: String },
    more              : {
        beta              : { type: String },
        gamma             : { type: Number },
        delta             : { type: String }
    }
});
mongoose.model('Dummy', dummySchema);

var dummy = new mongoose.models.Dummy({ alpha: 'blabla', more: { beta: 'blabla' } });
dummy.save(function(error, saved) {
    saved.alpha = 'blabla2';
    saved['more'] = {
        beta              : 'blabla2',
        gamma             : undefined,
        delta             : 'blabla2'
    };
    saved.save(function(error, updated) {
        console.log('done');
    });
});
```

**As you can see below gamma is null instead of being discarded**

![image](https://cloud.githubusercontent.com/assets/2556751/8727932/52d78b1c-2bda-11e5-92c6-0c554c66bcee.png)

**Comment by jlchereau** [comment]
Note: after executing dummy.save (insert), the object is correct (undefined gamma property not recorded) in database but after executing saved.save (update), the value of gamma in database is null.

**Comment by vkarpov15** [comment]
Thanks for the detailed report, will investigate within the next couple days.

**Comment by vkarpov15** [comment]
This is a tricky issue - our bson serializer treats undefined as null, so you will never save something with bson type undefined to mongodb. That's one issue.

The other subtlety is that

```javascript
    saved['more'] = {
        beta              : 'blabla2',
        gamma             : undefined,
        delta             : 'blabla2'
    }
```

is not the same as

```javascript
    saved['more'] = {
        beta              : 'blabla2',
        delta             : 'blabla2'
    }
```

These are two different objects - the first object has 3 keys, the second has 2. In this case, I think mongoose is doing the right thing by trying to save `gamma: undefined` in the database, which is technically valid.

**Comment by jlchereau** [comment]
There is a matter of consistency:

The BSON serializer doe not treat gamma = undefined as gamma = null with:

```
var dummySchema = new mongoose.Schema({
    alpha            : { type: String },
    beta              : { type: String },
    gamma         : { type: Number },
    delta             : { type: String }
});
```

or with

```
var dummySchema = new mongoose.Schema({
    alpha             : { type: String },
    more              : {
        beta              : { type: String },
        gamma             : { type: Number }
        // removed delta
    }
});
```

and in the case reported, it only occurs i updates, not in inserts.

Generally, mongoose does not record undefined in database, and I think it is the right thing to do.

**Comment by lineus** [comment]
@bonesoul it was fixed with a driver update almost 3 years ago in https://github.com/Automattic/mongoose/commit/c6c0b3ced8a1d6efa3e13029865f84135efe49b7. Are you running into this now? If so, can you please create a new issue with a code sample the demonstrates the problem?

If I run the repro script from this issue on mongoose 5.1.7:

### 3169.js
```js
#!/usr/bin/env node
'use strict';

var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/gh-3169');

var dummySchema = new mongoose.Schema({
  alpha: { type: String },
  more: {
    beta: { type: String },
    gamma: { type: Number },
    delta: { type: String }
  }
});
mongoose.model('Dummy', dummySchema);

var dummy = new mongoose.models.Dummy({ alpha: 'blabla', more: { beta: 'blabla' } });

dummy.save(function (error, saved) {
  saved.alpha = 'blabla2';
  saved['more'] = {
    beta: 'blabla2',
    gamma: undefined,
    delta: 'blabla2'
  };
  saved.save(function (error, updated) {
    console.log(updated);
    return mongoose.connection.close();
  });
});
```
I get:
### Output:
```
issues: ./3169.js
{ more: { beta: 'blabla2', delta: 'blabla2' },
  _id: 5b3612d16c128213694f8a4b,
  alpha: 'blabla2',
  __v: 0 }
issues:
```
It works correctly.
