### ISSUE TITLE
findOneAndUpdate doesn't return the result object, only the value that was found

### ISSUE THREAD

**Issue by perrin4869** [Automattic/mongoose#3173]
The callback function to `findOneAndUpdate` is passing an error and the `res.val` object, which contains the result of the `findOne` operation.. however, the rest of the `res` object is discarded. I would like to have access to it however... 

The line in question
https://github.com/Automattic/mongoose/blob/master/lib/query.js#L1746

I think a good solution might be to pass the rest of the `res` object as a third argument, that would not break other people's programs... although ideally, I'd pass either the whole res object, or pass the `res` object as a second argument and `res.val` as a third argument.

**Comment by vkarpov15** [comment]
That's simply not how `findOneAndUpdate()` works. `findOneAndUpdate()` does **not** do a separate 'findOne' and a separate 'update'. The value of `res` looks like this:

```javascript
{ value: 
   { _id: 55a8f94fd65d287438522ec6,
     thin: true,
     name: 'changed',
     docs: [ [Object] ] },
  lastErrorObject: { updatedExisting: true, n: 1 },
  ok: 1 }
```

which has some marginally useful information. What exactly are you looking for?

**Comment by perrin4869** [comment]
Of course I know how `findOneAndUpdate` works.
Yeah, that's how the value of `res` looks in the native mongodb driver, but if you run `Model#findOneAndUpdate`, or if you look at the code from the page above (https://github.com/Automattic/mongoose/blob/master/lib/query.js#L1746), you'll see that callback is called with `res.value`:

```
this._collection.findAndModify(castedQuery, castedDoc, opts, utils.tick(function(error, res) {
      return cb(error, res ? res.value : res);
    }));
```

I was looking for `nModified` or `upserted` for my test suite, but they are not available with `findOneAndUpdate`, only with `update`

**Comment by vkarpov15** [comment]
I see. Right now mongoose does not return that information. `nModified` will always be 1 with `findAndModify`, but the upserted field would definitely be useful.

**Comment by perrin4869** [comment]
What do you think a good solution would be though?

**Comment by vkarpov15** [comment]
Passing it as a third callback parameter would be easiest IMO. Can't really think of another solution without backwards-breaking changes, but that would make it impossible to access that parameter using conventional promise APIs.

**Comment by perrin4869** [comment]
I see! Well, one last thing would be, the other `findOneAnd...` methods should probably all be changed in a similar manner for consistency's sake. Finally, callback function's arguments documentation is not always clear... maybe I can try putting together a pull request to fix that :)

**Comment by vkarpov15** [comment]
Any help would be most welcome :beers:

**Comment by perrin4869** [comment]
hi, thanks for the commit! Unfortunately, I was testing the change, and the solution is not as easy as just passing an extra parameter in this case... I tried to fix it myself and put together a pull request, but it turned out to be harder than I expected since I ended up breaking other methods in the process due to my lack of understanding of the module. You can see my attempt in my fork:

https://github.com/perrin4869/mongoose

**Comment by vkarpov15** [comment]
H

**Comment by bazineta** [comment]
This IMO should be better documented as a potentially breaking change in the migration guide.

Consider that very common usage of mongoose is in concert with async.js, often in a waterfall scenario, which to date has been expecting a callback of (err, doc).  Adding that third value is, for those who fed the next stage of the waterfall from the findOneAndUpdate() callback, now causing what was the callback for the next stage to have been replaced by the new third argument.

**Comment by suprememoocow** [comment]
Just a warning for others in case you're experiencing the same problem as we have been. It's related to what @bazineta [mentioned](https://github.com/Automattic/mongoose/issues/3173#issuecomment-132638849).

We're using mongoose with [mongoose-q](https://github.com/iolo/mongoose-q), which is quite old and something we're looking to drop soon, but anyway, it works pretty well. We're using the `{ spread: true } ` option, which will automatically return an array (suitable for using with `.spread()`) if two values are returned from the callback. If there's only a single argument, it only returns the single value.
 
The problem is that since the callback now has two arguments instead of one, the result of `findOneAndUpdate` is now an array and not a document, so we'll need to update all our `findOneAndUpdate`'s to deal with the spread.

I haven't tested but I'm pretty sure that people using Bluebird's `Promise.promisifyAll` would experience the same problem too.

Lucky we have tests!

**Comment by vkarpov15** [comment]
A fair point. We should probably change it so that the third argument only gets passed if you set an option. Would that work for you?

**Comment by suprememoocow** [comment]
Yeah, that would be fine. It's actually an option that I would find really useful as it's quite useful to be able to access the result, but adding it by default would wreak havoc with promises

**Comment by yannickl** [comment]
@suprememoocow Yes I'm facing with the same problem (with bluebird and the `Promise.promisifyAll` method) and this is very annoying. I searched the bug during few hours before to see it was a method signature problem.
