### ISSUE TITLE
Write index creation errors to console

### ISSUE THREAD

**Issue by Koblaid** [Automattic/mongoose#3174]
Would it be possible for mongoose to write index creation errors to the console?

At the moment errors are only reported if there is a listener added to the model:

```
MyModel.on('index', function(err) {
  if (err) {
    // Index build failed!
  } else {
    // Indexes built successfully
  }
});
```

I just spent a few hours tracking down the problem described here: https://github.com/Automattic/mongoose/issues/2184#issuecomment-73898062. My error was caused by adding `unique: true` to the _id field as described in the shortid example (https://github.com/dylang/shortid/issues/42).

Seeing the index creation error on the console would have helped me a lot.

**Comment by vkarpov15** [comment]
Planned for the future, but yeah the on('index') event really trips a lot of people up...

**Comment by Koblaid** [comment]
Alright, thanks for your answer. I just added a listener to the 'index' event to all our models, so we're safe until it's implemented.

Thanks a lot for your work on mongoose :-)
