### ISSUE TITLE
Errors in toJSON are swallowed and cause Mongoose to hang

### ISSUE THREAD

**Issue by sabrehagen** [Automattic/mongoose#3175]
If any kind of error is thrown in a toJSON transform (for either a document or its subdocument), the error will be swallowed and Mongoose will not return from the toJSON call. The following code demonstrates an offending example.

```
schema.options.toJSON.transform = (doc, ret, options) => {
  var o = { a : 1 };
  o.b.map((e) => e.key);
}
```

**Comment by vkarpov15** [comment]
Hi @sabrehagen sorry for taking a while to get back to you. I haven't been able to repro this in either 3.8.x or 4.1.x. Below script throws an exception for both versions.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh3175');

var Schema = mongoose.Schema;
var TestSchema = new Schema({});

TestSchema.options.toJSON = {
  transform: function(doc, ret, options) {
    var o = { a: 1 };
    o.b.map(function(e) {
      return e.key;
    });
  }
};

var ParentSchema = new Schema({ tests: [TestSchema] });

var Test = mongoose.model('test', ParentSchema);

console.log(new Test({ tests: [{}] }).toJSON());
```

**Comment by sabrehagen** [comment]
Agreed, your code throws fine. I should have supplied you my repro code when I made the issue, sorry. I had it failing in isolation with a code sample but thought it was too simple to bother posting. Tested again in my environment but it throws correctly as well. Will use code samples in future. Thanks.
