### ISSUE TITLE
Default set on sub-property causes its parent to appear in result even when not selected

### ISSUE THREAD

**Issue by alobodig** [Automattic/mongoose#3179]
When a property is defined as an object containing a sub-property with a default, e.g.:

```
{
  property: {
     example: { type: String },
     sub: { type: String, default: 'hello' }
  }
}
```

Returned objects contain that property as an empty object when it is not selected.

```
test.findOne({}, 'example' ...);
// Returns: { _id: ObjectId('...'), sub: { } }
```

However, explicitly deselecting it does remove it from the result.

```
test.findOne({}, '-sub' ...);
// Returns: { _id: ObjectId('...'), __v: 1 }
```

This may be tangentially related to #1022, which was an issue with properties selected in the schema definition. 

Full test case:

```
var schema = new mongoose.Schema({
        embedded: {
           field: { type: Number, default: 1, select: false  }
        }
});

var Test = mongoose.model('Test', schema);
var a = new Test();
a.save(function(err) {
        Test.find({ _id: a._id }, '_id', function(err, b) {
                console.log(b); // b will contain "field" as an empty object
        });
});
```

**Comment by vkarpov15** [comment]
This is a dup of #2503. Unfortunately this is something that's difficult to work around with our current implementation, which is why it's scheduled to change for the next backwards breaking release.

**Comment by alobodig** [comment]
Somehow I missed that while searching. Thank you.

**Comment by vkarpov15** [comment]
No worries, I changed the title today because the title is misleading anyway :)

**Comment by vkarpov15** [comment]
Closing this because #2503 was fixed
