### ISSUE TITLE
Regression Mongoose 4.0.7 -> 4.0.8, $set does not work with sub documents anymore

### ISSUE THREAD

**Issue by gunters63** [Automattic/mongoose#3185]
One of our tests failed after I updated Mongoose from 4.0.6 to 4.0.8.

We are calling some model.update with something like this:

    '$set' : {
    	"jobRequests.$.jobId" : "willBeBooked",
	"jobRequests.$.documents" : {
            // some properties
	},
	"jobRequests.$.bookingDetails" : {
            // some properties
	},
	"jobRequests.$._createdAt" : 1437495452855,
	"jobRequests.$.reasons" : [],
	"jobRequests.$.onBehalf" : ""
    }

I have enabled Mongoose DEBUG so I can see the generated Mongo update. Mongoose 4.0.8. seems to throw away all $set keys which have an object value (=sub-document). This is the resulting Mongo DEBUG output:

	'$set' : {
		'jobRequests.$.onBehalf' : '',
		'jobRequests.$.reasons' : [],
		'jobRequests.$._createdAt' : 1437494543563,
		'jobRequests.$.jobId' : 'willBeBooked'
	}

Array "reasons" is there, the 3 single value properties are there, but the properties with sub-documents are missing.

This worked in Mongoose 4.0.7. This is the DEBUG output from 4.0.7:

    $set' : {
		'jobRequests.$.jobId' : 'willBeBooked',
		'jobRequests.$.documents' : {
			 // some properties
		},
		'jobRequests.$.bookingDetails' : {
			 // some properties
		},
		'jobRequests.$.reasons' : [],
		'jobRequests.$.onBehalf' : ''
	}

**Comment by gunters63** [comment]
After a bit experimentation I found out that when I set the option overwrite it works again.

According to the documentation you have to set this option only when you want to $set the whole document at once. Seems the semantics have changed now for 4.0.8 so you also have to set it when you want to overwrite any sub-document.

**Comment by amit777** [comment]
same bug happens for me too.. i dowgrade to 4.0.7 and the updates work again.

**Comment by jeffwhelpley** [comment]
I ran into this as well. Downgrading to 4.0.7 works.

**Comment by amit777** [comment]
I updated to 4.1.0 and my specific issue seems to be fixed. Is it fixed for you all as well?

**Comment by amit777** [comment]
I ran into this issue again in 4.1.0.  Downgrading to 4.0.7 fixes.  here is an example of the type of query I'm running.  Hopefully it provides some clues:

```
    var newobj = yield parent.constructor.findOneAndUpdate(
      {"_id" : parent._id, "children._id": self._id },
      {
        "$set": {
          "children.$": self
        }
      }
    );
```

**Comment by vkarpov15** [comment]
As a workaround, you can do

```javascript
parent.constructor.findOneAndUpdate(
      {"_id" : parent._id, "children._id": self._id },
      {
        "$set": {
          "children.$": self
        }
      },
      { strict: false } // <-- set strict mode to false for this update
    );
```
