### ISSUE TITLE
document.execPopulate() not returning promise

### ISSUE THREAD

**Issue by JaKXz** [Automattic/mongoose#3187]
My promise chain looks like this:

```js
myDocument.save()
  .then(function (savedDocument) {
    return MyModel.update(/*query, options*/).exec();
  })
  .then(function () { 
    return myDocument
      .populate(/*path, select, model*/)
      .populate(/*path, select, model*/)
      .execPopulate(); // server/controllers/my-document.server.controller:236:10
  })
  .then(function (populatedDoc) {
    //do stuff with populatedDoc
  });
```

However, I'm getting the following stack trace:

```
TypeError: undefined is not a function
    at Object.populate (node_modules/mongoose/lib/document.js:2028:22)
    at Object.Document.execPopulate (node_modules/mongoose/lib/document.js:2070:8)
    at server/controllers/my-document.server.controller.js:236:10
    at newTickHandler (node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
    at wrapped (node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at process._tickDomainCallback (node.js:381:11)
    at process.wrappedFunction (node_modules/newrelic/lib/transaction/tracer/index.js:262:51)
```

~~which, looking at the source code, means that the `Document` object's constructor does not have a populate method?~~ scratch that, I'm quite confused, and didn't find anything on S/O about this... I'll happily move this question there, but this looks to me like a bug since the [documentation says I should be able to do this](http://mongoosejs.com/docs/api.html#document_Document-execPopulate).

For reference I'm using Mongoose v4.0.x

**Comment by vkarpov15** [comment]
Hmm that's strange. Can you show me what `myDocument.constructor.toString()` and `require('util').inspect(myDocument.constructor);` are in that second .then()? This should work in theory.

**Comment by JaKXz** [comment]
```
function Object() { [native code] } // console.log(myDocument.constructor.toString())
[Function: Object] inspect // console.log(require('util').inspect(myDocument.constructor));
```

**Comment by vkarpov15** [comment]
Hmm that doesn't make any sense, `myDocument.constructor` should be the model. How are you getting `myDocument`?

**Comment by JaKXz** [comment]
It's either the result of a `findOne` query or `new Document({key: 'value'})`.

**Comment by burabure** [comment]
I was using 4.0.7, updated to 4.1.0 and this error happened
```
TypeError: RestrictionDay.findOne(...).then(...).catch is not a function
      at getLatest (/root/app/tengo-restriccion/app/models/RestrictionDay.js:39:11)
      at Object.callee$0$0$ (/root/app/tengo-restriccion/app/server/index.jsx:2:18)
      at tryCatch (/root/app/tengo-restriccion/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/root/app/tengo-restriccion/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:323:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/root/app/tengo-restriccion/node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
      at Object.<anonymous> (/root/app/tengo-restriccion/node_modules/koa-route/index.js:34:19)
      at GeneratorFunctionPrototype.next (native)
      at Object.serve (/root/app/tengo-restriccion/node_modules/koa-static/index.js:41:14)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/root/app/tengo-restriccion/node_modules/koa/node_modules/co/index.js:65:19)
      at run (/root/app/tengo-restriccion/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
      at /root/app/tengo-restriccion/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
      at doNTCallback0 (node.js:408:9)
      at process._tickCallback (node.js:337:13)
```

rolling back to 4.0.7 solves it

**Comment by vkarpov15** [comment]
@burabure please provide actual code examples. Stack trace is not particularly helpful.

**Comment by burabure** [comment]
@vkarpov15 nothing too fancy just try to use findOne's returned value as a promise and it blows up.
```
function getLatest() {
  return RestrictionDay.findOne({}, {}, { sort: { _id: -1 } })
    .then( x => x )
    .catch( error => {
      log.error({'RestrictionDay#getLatest': { error }});
      return Promise.reject(error);
    });
}
```

**Comment by JaKXz** [comment]
@burabure `RestrictionDay.findOne()` returns a `Query`, which you must call [`exec()`](http://mongoosejs.com/docs/api.html#query_Query-exec) on to return a `Promise` - see the first link in my promise chain.

**Comment by JaKXz** [comment]
Also, @vkarpov15 and for anyone else interested, I've been using two [`Model#populate`](http://mongoosejs.com/docs/api.html#model_Model.populate)s in series since I posted this, as a workaround [which is obviously not ideal].

**Comment by vkarpov15** [comment]
@JaKXz that's not entirely true, you should be able to do `RestrictionDay.findOne().then()` in 4.x.

@burabure you're running into an issue where in 4.0.x `RestrictionDay.findOne().then()` would mistakenly chain a bluebird promise rather than mpromise. In 4.1.x, if you want to use bluebird, you need to do `require('mongoose').Promise = require('bluebird');`

**Comment by JaKXz** [comment]
@vkarpov15 fair enough - I was just going by what's written in the docs. TBPH though I prefer the consistency of having the `Query` object separated from its execution and returning a promise (or passing a callback, if you're so inclined)... but that's a separate discussion.

**Comment by vkarpov15** [comment]
That's something that was added in to mquery 1.1, so wasn't entirely my choice because 'Query as promise' doesn't entirely make sense with the way ES6 promises work. However some people find it useful, and `Query.then()` basically just calls `.exec()` for you anyway.

**Comment by JaKXz** [comment]
Ah, that's handy - could I ask that it be documented somewhere?

**Comment by vkarpov15** [comment]
https://github.com/aheckmann/mquery#then and http://mongoosejs.com/docs/api.html#query_Query-then

**Comment by burabure** [comment]
@vkarpov15 I dont understand why a bluebird promise works and a mpromise doesn't. could you "explain it like im 5"?

BTW: im using native promises w/Babel.

**Comment by JaKXz** [comment]
Ah, I'm embarrassed. [DevDocs](http://devdocs.io/mongoose) needs to be updated.

**Comment by vkarpov15** [comment]
@burabure mpromise doesn't have `.catch()`, because it aims to be a minimum viable implementation of [the promises/A+ spec](https://promisesaplus.com/).

**Comment by burabure** [comment]
I see, thanks =). Then i'm guessing ``` require('mongoose').Promise = Promise; ``` would work if I wanted to use native promises?

**Comment by vkarpov15** [comment]
Yep :) Part of the reason for 4.1 was to unify all the different promises blobs into one sane interface, so everything returns an mpromise unless you tell mongoose to use some ES6-compatible promises library.

**Comment by vkarpov15** [comment]
As far as I can tell this issue is closed... re-open if there's still an issue.

**Comment by jbdemonte** [comment]
I'm facing the same issue, in this test code:

      var mongoose = require('mongoose');
      mongoose.Promise = require('bluebird');

      var companySchema = new mongoose.Schema({
        name:  String,
        description:  String
      });

      var userSchema = new mongoose.Schema({
        name:  String,
        company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company'}
      });

      var Company = mongoose.model('Company', companySchema);
      var User = mongoose.model('User', userSchema);

      mongoose.connect(
        'mongodb://127.0.0.1/test',
        {},
        function (err) {
          if (err) {
            return console.error(err);
          }

          var company = new Company({name: 'Reynholm Industrie'});
          var user = new User({name: 'Douglas', company: company._id});

          Promise
            .all([
              company.save(),
              user.save()
            ])
            .then(function () {
              return User.findOne({_id: user._id}).exec();
            })
            .then(function (dbUser) {
              return dbUser.populate('company').execPopulate();
            })
            .then(function (dbUser) {
              console.log(dbUser.company);
            });
        }
      );


dbUser.populate('company').execPopulate(); does not return a promise but the model
I only get it working when using the classic:

    dbUser.populate('company', function (err, dbUser2) {
        console.log(dbUser2.company); // populated
    })

**Comment by swordsreversed** [comment]
Hi I'm getting a similar problem with 

```
return Podcast.findOne({ slug: params[0]})
      .populate('categories')
      .execPopulate();
```

returning a stacktrace of 

```
TypeError: _modelsPodcast2.default.findOne(...).populate(...).execPopulate is not a function
```

Also i'm putting in
```
mongoose.Promise = global.Promise;
```

to use ES6 through Babel. Mongoose is 4.4.3. Not really sure how to proceed after reading this thread. Any help would be appreciated.

**Comment by vkarpov15** [comment]
@swordsreversed `execPopulate()` is a function on a document, not a query. So the below requires `execPopulate()`:

```javascript
Podcast.findOne({}, function(error, doc) {
  // Query calls back with a document which has a populate method.
  var promise = doc.populate('categories').execPopulate();
});
```

Your approach attaches populate to the query, so what you need is:

```javascript
var promise = Podcast.findOne({}).populate('categories').execPopulate();
```

Please review the [promises docs](http://mongoosejs.com/docs/promises.html) for more info.

**Comment by swordsreversed** [comment]
Ok thank you!

**Comment by valerybugakov** [comment]
I had a similar problem to `swordsreversed`. Read comments above, tried both approaches:
```js
mongoose.Promise = Promise;

Podcast.findOne({}, function(error, doc) {
  // Query calls back with a document which has a populate method.
  var promise = doc.populate('categories').execPopulate();
});
```
This one worked for me, but here I need to use a callback.  If I use
```js
const result = await Podcast.findOne({}).populate('categories').exec();
```
I'm not getting populated model, only a result of `Podcast.findOne({})`
Mongoose version: 4.5.10
Any suggestions on what is wrong here?

**Comment by vkarpov15** [comment]
@valerybugakov can you please provide a more complete code sample? Your code looks correct but I'd need to see schemas, etc.

**Comment by shivamjjha** [comment]
I have this problem the message is not being populated correctly:

```
exports.createMessage = async function (req, res, next) {
  try {
    const message = await db.Message.create({
      text: req.body.text,
      id: req.params.id
    })

    const foundUser = await db.User.findById(req.params.id);
    foundUser.messages.push(message.id);
    await foundUser.save();

    const foundMessage = await db.Message.findById(message.id).populate('user',
      // Just want the following things instead of user property
      {
        username: true,
        profileImageURL: true
      }).exec();


    return res.status(200).json(foundMessage);
  } catch (error) {
    return next(error);
  }
}
```
It returns:

```
{
    "_id": "5f805fc19845661dccb0c926",
    "text": "Testing please work now please 7",
    "__v": 0
}
```

**Comment by talaikis** [comment]
+1, does not work for me.

```json
{
    status: 'in-progress',
    _id: 5f899dac76455200086429ff,
    authorId: 5f847cba57a40d000828845d,
  .....
    __v: 0
  },
....
```

And code:

```js
const art= await Articles.findById({ _id: '5f899dac76455200086429ff' })
await art.populate('author').execPopulate() // returns above data
arts.populated('author') // undefined, although author exists and can be found with findById
```
