### ISSUE TITLE
Number Unique Index Type Change

### ISSUE THREAD

**Issue by TalhaAkkas** [Automattic/mongoose#3192]
I have unique index on Number type attribute
when i add new object it saved as Int64 type on mongodb
then i add another object it saved as Double type on mongodb

is there a way to specify force numbers to save as Integer or Double
so as result it went around unique index

here is my scheme 
<img width="392" alt="screen shot 2015-07-23 at 17 39 50" src="https://cloud.githubusercontent.com/assets/632596/8853241/68ebb68e-3162-11e5-8f3e-eb0b2d7b2b16.png">

first object
<img width="951" alt="screen shot 2015-07-23 at 17 39 41" src="https://cloud.githubusercontent.com/assets/632596/8853249/70a9e314-3162-11e5-8cfa-12ddcd9fb0f7.png">

second object 
<img width="928" alt="screen shot 2015-07-23 at 17 39 27" src="https://cloud.githubusercontent.com/assets/632596/8853254/770543d4-3162-11e5-80a6-dc2cfaa88fa8.png">
 
 sorry for my bad english

**Comment by vkarpov15** [comment]
Can you show me the code you're using to save?

**Comment by TalhaAkkas** [comment]
it' is  in meta code with no specific model level coding
![screen shot 2015-07-24 at 09 54 20](https://cloud.githubusercontent.com/assets/632596/8869218/fb6e6024-31e9-11e5-9afb-7c1b6e733aed.png)

child.model is a scheme code above equals
->> var obj = new Company(req.body)
->> obj.save();

**Comment by vkarpov15** [comment]
So the way the [bson parser works is that it checks if the number is an integer (`Math.floor(value) === value`) and stores it as an integer, otherwise as a double](https://github.com/mongodb/js-bson/blob/bb9556580e50570c570b95ad75b5ce8e8b295c91/lib/bson/parser/serializer.js#L67) unless its too big, I don't really see how that could happen. If you have a number and you want it to be an integer, just `Math.floor()` it before you store it.

**Comment by TalhaAkkas** [comment]
Ok then problem i got the problem 
I tought since i set the type as numerical it should convert the value. So i didn't do any type casting.
in req all parameters comes as strings and 

function check(value){
	console.log(Math.floor(value) === value );
}  
check(123) gives true;
check("123") gives false; 

and 


function check(value){
	console.log(Math.floor(value) == value );
}  
check(123) gives true;
check("123") gives true;

I'll add casting trigger on save event thanks
