### ISSUE TITLE
Required validation through API not working

### ISSUE THREAD

**Issue by andresmatasuarez** [Automattic/mongoose#3199]
Hi guys!

I have the following schema with its validations (reduced for more clarity):

```
var MySchema = new Schema({
  ...
  evaluations: [{
    choices: [{
      claim: String
      isCorrect: Boolean
    }]
  }]
});

MySchema.path('evaluations').schema.path('choices').schema.path('claim').required(true, errorMessageRequired);

MySchema.path('evaluations').schema.path('choices').schema.path('claim').validate(maxLengthValidator, errorMessageMaxLength);
```

The max length validator works perfectly, but the required validator is not taken into account while creating a new MySchema document without evaluations.choices.claim.

HOWEVER, if I set the `required` options in the schema definition, it IS taken into account and the validation goes smoothly:
```
[{
  claim: { type: String, required: true }
}]
```

What do you think? I can give a look at the code, and maybe fix it in a PR, but I wanted to find out what your opinion was before doing anything.

Anyways, I really don't think this is expected behaviour.

**Comment by vkarpov15** [comment]
Brief aside, why are you doing `MySchema.path('evaluations').schema.path('choices').schema.path('claim').required(true, errorMessageRequired);` instead of `MySchema.path('evaluations.choices.claim').required()`?

Also, please clarify what you mean by 'the required validator is not taken into account'.

**Comment by andresmatasuarez** [comment]
First of all, if I specify schema path with dot notation, I get "TypeError: Cannot call method 'required' of undefined" OR "TypeError: Cannot call method 'validate' of undefined". As I was struggling with this very issue, I came across this article dealing with the same problem, so at least I am not the only one having to access schema paths for embedded arrays that way.

Secondly, by "The required validator is not taken into account" I mean that it is not working. If I create a MySchema document with some "evaluation"s and one of them lacks a "claim", it will not be prevented from saving. However, if a move the .required() call to required: true in schema definition, document creation will fail with the expected ValidationError.

**Comment by andresmatasuarez** [comment]
Great!
