### ISSUE TITLE
incorrect path to win_delay_load_hook.c

### ISSUE THREAD

**Issue by kevinlbatchelor** [Automattic/mongoose#3200]
Installing mongoose on a windows 8.1 box with python 2.3 and windows visual studio express I get the following error:

c1 : fatal error C1083: Cannot open source file: 'c:Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\b
son\node_modules\bson-ext\build\bson.vcxproj]

You can see that there is a slash missing after the C: 

result:

The install creates the bson.vcxproj file with an incorrect path. I rolled back to mongoose 3.8 and I do not get this issue.

**Comment by vkarpov15** [comment]
Which version of mongoose are you getting this with? 4.0.8 and 4.1.0 don't use the C++ BSON extension anymore...

**Comment by kevinlbatchelor** [comment]
I got this installing the latest.

**Comment by kevinlbatchelor** [comment]
$ npm install mongoose
-


> kerberos@0.0.12 install C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  kerberos.cc
  worker.cc
  security_buffer.cc
  security_buffer_descriptor.cc
  security_context.cc
  security_credentials.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib\win32\wrappers\security_buffer_descriptor.cc) [C
:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib\win32\wrappers\security_buffer.cc) [C:\xampp\htd
ocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib\win32\wrappers\security_context.cc) [C:\xampp\ht
docs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc (..\lib\win32\wrappers\security_credentials.cc) [C:\xamp
p\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj]
  base64.c
  kerberos_sspi.c
     Creating library C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\Release\kerberos.lib and object C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_
  modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\Release\kerberos.exp
  Generating code
  Finished generating code
  kerberos.vcxproj -> C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\Release\\kerberos.node
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree

> bson-ext@0.1.10 install C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" clean )  else (node  clean )

C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" configure --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\xampp\htdocs\d3Charts\node_modules\mong
oose\node_modules\bson\node_modules\bson-ext\build\Release )  else (node  configure --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --mod
ule_name=bson --module_path=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release )
Warning: Missing input files:
c:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c

C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" build --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\xampp\htdocs\d3Charts\node_modules\mongoose
\node_modules\bson\node_modules\bson-ext\build\Release )  else (node  build --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name
=bson --module_path=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bson.cc
..\ext\bson.cc(687): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
..\ext\bson.cc(901): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
c:\xampp\htdocs\d3charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'int64_t' to 'double', possible loss of data [C:\xampp\htdocs\d3
Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
          ..\ext\bson.cc(567) : see reference to function template instantiation 'v8::Local<v8::Number> NanNew<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ]
..\ext\bson.cc(342): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
          ..\ext\bson.cc(153) : while compiling class template member function 'void BSONSerializer<DataStream>::SerializeValue(void *,const v8::Handle<v8::Value>)'
          ..\ext\bson.cc(123) : see reference to function template instantiation 'void BSONSerializer<DataStream>::SerializeValue(void *,const v8::Handle<v8::Value>)' being compiled
          ..\ext\bson.cc(103) : while compiling class template member function 'void BSONSerializer<DataStream>::SerializeDocument(const v8::Handle<v8::Value> &)'
          ..\ext\bson.cc(878) : see reference to function template instantiation 'void BSONSerializer<DataStream>::SerializeDocument(const v8::Handle<v8::Value> &)' being compiled
          ..\ext\bson.cc(877) : see reference to class template instantiation 'BSONSerializer<DataStream>' being compiled
  win_delay_load_hook.c
c1 : fatal error C1083: Cannot open source file: 'c:Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\b
son\node_modules\bson-ext\build\bson.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\xampp\\htdocs\\d3Charts\\node_modules\\mongoose\\node_modules\\bson\\nod
e_modules\\bson-ext\\build\\Release\\bson.node" "--module_name=bson" "--module_path=C:\\xampp\\htdocs\\d3Charts\\node_modules\\mongoose\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release"
gyp ERR! cwd C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson -
-module_path=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\xampp\\htdocs\\d3Charts\\node_modules\\mongoose\\node_modules\\bson\\node_modules\\bson-ext\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext
node-pre-gyp ERR! node -v v0.12.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:\xampp\htdocs\d3
Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Release' (1)

C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node  rebuild )
Warning: Missing input files:
c:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bson.cc
..\ext\bson.cc(687): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
..\ext\bson.cc(901): warning C4267: 'argument' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
c:\xampp\htdocs\d3charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\node_modules\nan\nan_new.h(208): warning C4244: 'argument' : conversion from 'int64_t' to 'double', possible loss of data [C:\xampp\htdocs\d3
Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
          ..\ext\bson.cc(567) : see reference to function template instantiation 'v8::Local<v8::Number> NanNew<v8::Number,int64_t>(A0)' being compiled
          with
          [
              A0=int64_t
          ]
..\ext\bson.cc(342): warning C4267: 'initializing' : conversion from 'size_t' to 'uint32_t', possible loss of data [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj]
          ..\ext\bson.cc(153) : while compiling class template member function 'void BSONSerializer<DataStream>::SerializeValue(void *,const v8::Handle<v8::Value>)'
          ..\ext\bson.cc(123) : see reference to function template instantiation 'void BSONSerializer<DataStream>::SerializeValue(void *,const v8::Handle<v8::Value>)' being compiled
          ..\ext\bson.cc(103) : while compiling class template member function 'void BSONSerializer<DataStream>::SerializeDocument(const v8::Handle<v8::Value> &)'
          ..\ext\bson.cc(878) : see reference to function template instantiation 'void BSONSerializer<DataStream>::SerializeDocument(const v8::Handle<v8::Value> &)' being compiled
          ..\ext\bson.cc(877) : see reference to class template instantiation 'BSONSerializer<DataStream>' being compiled
  win_delay_load_hook.c
c1 : fatal error C1083: Cannot open source file: 'c:Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c': No such file or directory [C:\xampp\htdocs\d3Charts\node_modules\mongoose\node_modules\b
son\node_modules\bson-ext\build\bson.vcxproj]
mongoose@4.1.0 node_modules\mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@1.0.0
├── hooks-fixed@1.1.0
├── mpromise@0.5.4
├── mpath@0.1.1
├── kareem@1.0.1
├── async@0.9.0
├── ms@0.1.0
├── mquery@1.6.1 (debug@2.2.0, bluebird@2.9.26)
├── mongodb@2.0.34 (readable-stream@1.0.31, mongodb-core@1.2.0)
└── bson@0.3.2 (bson-ext@0.1.10)

**Comment by vkarpov15** [comment]
Ah this is an issue with Kerberos. Don't worry about it, its just a warning unless you are looking to [integrate mongodb into your kerberos system](http://docs.mongodb.org/manual/tutorial/control-access-to-mongodb-with-kerberos-authentication/).

**Comment by kevinlbatchelor** [comment]
ok, thanks
