### ISSUE TITLE
mongoose/node_modules/mongodb/lib/utils.js:95 undefined is not a function

### ISSUE THREAD

**Issue by OKNoah** [Automattic/mongoose#3201]
Since allowing mongoose to update recently I get this error, which crashes my application.

Maybe related to `.catch()` which seemed to work before?

**Comment by vkarpov15** [comment]
Please provide more information, like code that reproduces this issue.

**Comment by vkarpov15** [comment]
Issue's stale, re-open if this is still an issue.
