### ISSUE TITLE
Q: Unable to find out base model using discriminators

### ISSUE THREAD

**Issue by silkentrance** [Automattic/mongoose#3202]
Having a base model AbstractFoobarModel, for which multiple concrete models like for example BarfooModel or FBModel have been defined using AbstractFoobarModel.discriminator(), I am unable to find out the name for the abstract base model from either BarfooModel or FBModel or any instances thereof.

For instances of both BarfooModel and FBModel I am able to get their actual modelName using instance.constructor.modelName, however, that modelName is equal to their defined discriminator.

I would like to also get their abstract base´s name, namely the AbstractFoobarModel´s name, e.g. Foobar.

Is there any way to this information from mongoose? Having looked at the sources and the runtime instances, it seems as if there is no way to tell from what base model one discriminator based model was derived from, or is there?

**Comment by vkarpov15** [comment]
Admittedly this isn't very easy to do, but `BarfooModel.prototype.__proto__.constructor.modelName;` should serve as a workaround for now

**Comment by silkentrance** [comment]
Great, thanks for the hint. This also works on instances, e.g. `i = new BarFoo(); i.constructor.prototype...`.

**Comment by silkentrance** [comment]
@vkarpov15 thank you!
