### ISSUE TITLE
Can't push to an array in a subdocument using $each. Regression from 4.0.7 to 4.0.8

### ISSUE THREAD

**Issue by paton** [Automattic/mongoose#3203]
The follow update query broke after upgrading from 4.0.7 to 4.0.8 (and the issue also appears on 4.1.0)

````
Order.update({
  _id: '55ae6915a94c112235ce1a87',
  'suborders._id': '55ae6915a94c112235ce1a88'
}, {
  $addToSet: {
    'suborders.$.translatedPhrases': { $each: ['test5'] } 
  }
}, console.log);
````

"test5" doesn't get pushed to the array, and no errors are thrown.

Interestingly, the query works when the $each operator is removed.

Any ideas? Thanks!

**Comment by paton** [comment]
This problem appears in mongoose 4.0.8.

Downgrading to 4.0.7 fixed this issue.

**Comment by amit777** [comment]
I wonder if it's also related to this: https://github.com/Automattic/mongoose/issues/3185

though my issue was solved with 4.1.0.  Your test case is a little different with the $each operator.

**Comment by vkarpov15** [comment]
That's odd... I'll investigate.

**Comment by hugoduraes** [comment]
The same is happening with me. $each array values are not being pushed to the array.

**Comment by fmmartins** [comment]
Happening with me too.

**Comment by amit777** [comment]
it seems like 4.1.1 fixes it for me.

**Comment by paton** [comment]
Yep, 4.1.1 fixes this problem.

Thanks!!
