### ISSUE TITLE
NPM FIX Release  ASAP

### ISSUE THREAD

**Issue by Ozonid** [Automattic/mongoose#3204]
Hey,

could you do an NPM release asap? I would need this fix: https://github.com/Automattic/mongoose/commit/c2180c2004b47b322bdf382fba15f770270e57e9#diff-9356081774d360ebc77cf6fe0a8cfc9f

Thanks a lot!

**Comment by gifff** [comment]
+1

**Comment by jrthib** [comment]
+1
