### ISSUE TITLE
Make UUID a formal Schema.Type

### ISSUE THREAD

**Issue by niahmiah** [Automattic/mongoose#3208]
Hi,

I was wondering.. why is UUID not supported as a formal Schema Type? Mongo has support for storing it as BinData(), which seems to require about 50% of the space as compared to storing them as Strings.

The mongo shell has a built in function UUID() for the conversion... It seems like this would be a nice addition to mongoose.

**Comment by vkarpov15** [comment]
As far as I know, the mongoose 'buffer' type is what you want for storing the BinData BSON type. http://mongoosejs.com/docs/schematypes.html

**Comment by niahmiah** [comment]
Created a PR https://github.com/Automattic/mongoose/pull/3242

**Comment by iamkhalidbashir** [comment]
should not be closed

**Comment by L14MJ4M3S0N** [comment]
@vkarpov15  Any comment as to why the PR with a fix was closed?

 #https://github.com/Automattic/mongoose/pull/3242

I would love to se this feature released soon!

**Comment by vkarpov15** [comment]
@L14MJ4M3S0N I'm not sure why the PR was closed, the PR author closed it without any feedback.

**Comment by felipefrancisco** [comment]
+1

**Comment by L14MJ4M3S0N** [comment]
For those that are looking for a workaround and do not want to use published NPM packages, here is what I have been using. 

**Interface**
```
export interface Person extends Document {
  uuid: Buffer;
...
};
```

**Schema:**
```
   uuid: {
      type: Schema.Types.Buffer,
      index: true,
      background: true,
      unique: true,
      default: () => new UUID(UUID.generate()).toBinary(),
    },
```

**FindOne Example**
```
const person = await People.findOne()
      .where({uuid: new UUID(event.pathParameters.assessmentId).toBinary()})
      .exec();
```

**Returning a uuid as a string**
```
      return new UUID(person.uuid).toString(),
```

**Comment by adarshmadrecha** [comment]
Now that https://github.com/Automattic/mongoose/pull/12268 is merged and released, this issue can be closed.

**Comment by hasezoey** [comment]
i kinda expected this to auto-close because of the keyword in #12268, but it didnt
