### ISSUE TITLE
Several async DELETE request - "VersionError: No matching document found."

### ISSUE THREAD

**Issue by voronianski** [Automattic/mongoose#3211]
In our application we have request `DELETE http://someapi.com/items/:itemId/subitems/:subItemId` which deletes sub-item from array inside item object.

Recently we noticed such error when making several DELETEs one by one:

```bash
VersionError: No matching document found.
    at p1.then.then.self.isNew (/Users/dmitri/api/node_modules/mongoose/lib/model.js:242:38)
    at newTickHandler (/Users/dmitri/api/node_modules/mongoose/node_modules/mpromise/lib/promise.js:229:18)
    at process._tickDomainCallback (node.js:381:11)
```

It just throws this error on every second DELETE request (success, fail, success, fail etc.)! Skip versioning disable error throwing but actual sub-items are not deleted.

This is how code looks like:

```javascript
let item = Item.findById(req.params.itemId);
item.content = item.content.filter(subItem => {
     return subItem.id !== req.params.subItemId;
});
item = await item.save();
```

We've found several related questions:

- http://stackoverflow.com/questions/22053685/mongoose-no-matching-document-found-using-id-method-error-caused-by-asynchron
- https://github.com/Automattic/mongoose/issues/1844

And read the article on how versioning works - http://aaronheckmann.tumblr.com/post/48943525537/mongoose-v3-part-1-versioning

##### Interesting point is.. 
..that when we make several `POST /items/:itemId/subitems/:subItemId` and updating item like below it works fine:

```javascript
item.content.push(req.subItem);
item = await item.save();
```

##### Is there any workaround? Locking document is the only solution?! Thanks!

**Comment by vkarpov15** [comment]
Are you re-using the same `item` document between requests? Also, FWIW, I'd recommend you use [mongoose's `.pull()` function](http://mongoosejs.com/docs/api.html#types_array_MongooseArray.pull) rather than the built-in filter function.

```javascript
item.content.pull({ id: req.params.subItemId });
```

Built-in functions typically don't play nice with mongoose's change tracking.

**Comment by voronianski** [comment]
@vkarpov15 thanks! For every request we get new item document from db by `findById()`. 

Regarding your suggest does `pull` work only with ids? I have array of subdocuments where unique field is `fileName`. And `item.content.pull({fileName: req.params.fileName});`  removes all subdocuments from it.. Also it still returns error on every second DELETE request.

**Comment by anton-syrovatka** [comment]
I have a feeling that if those requests are processed in parallel then you might need to use ```findOneAndUpdate``` function. You will avoid situation when you have several versions of one document retrieved from db and therefore they won't override each over on executing ```save```.

**Comment by vkarpov15** [comment]
Yeah pull only works with id. Also @anton-syrovatka is right about that.

At a high level, I recommend not having a `DELETE` request for an array item, and instead exposing a `PUT` with the whole array and relying on the client to modify the array into their desired state. `DELETE` on an array item typically has race conditions like the one you're running into.

**Comment by elgubenis** [comment]
is there no way to add something like a wait? (im not talking about promises to send multiple delete requests) like a queue of requests, so the second pull gets executed when the first is done, but like internally?

**Comment by vkarpov15** [comment]
You can call `.pull()` before calling `.save()`

**Comment by vkarpov15** [comment]
Issue's been stale for a while, closing.
