### ISSUE TITLE
Wildcard index?

### ISSUE THREAD

**Issue by dougmoscrop** [Automattic/mongoose#3213]
I'm trying to add a [wildcard text index](http://docs.mongodb.org/manual/core/index-text/#text-index-wildcard), e.g.

`schema.index({ '$**': 'text' })`

but I get:

`Error: key foo.$** must not contain '.'`

where 'foo' is the key of some field that is a subdocument. I've been poking around schema.js and it seems like the logic always tries to map indices on to paths, meaning that the wildcard index concept doesn't really fit with how mongoose is tracking indices against a schema. is this a fair assessment?

**Comment by vkarpov15** [comment]
Yeah mongoose's index function will only let you set indexes on paths that exist. I'd recommend you just use `mongoose.connection.db.ensureIndex()` directly instead for this use case. We'll put in a fix for this for a future release.

**Comment by dougmoscrop** [comment]
Are you interested in pull requests to support it?

**Comment by vkarpov15** [comment]
Absolutely :) shouldn't be too difficult.

**Comment by vkarpov15** [comment]
Hmm actually, so the below script seems to work fine now.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh3213');

var s = new Schema({
  test: String
});

s.index({ '$**': 'text' });

var Test = mongoose.model('test', s);

Test.on('index', function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

I didn't quite expect this to work, but looks like it already does. I'm gonna close this, re-open if it's still an issue.

**Comment by CraftyFella** [comment]
The original question was talking about an index with a `.` in it.. you're example doesn't have a `.`
