### ISSUE TITLE
$sort array update modifier not retaining order of sort

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#3215]
For example, suppose I have documents:

```
{
  arr: {type: [
    date: Date,
    value: value
  ]}
}
```

Then, I attempt to update an existing doc and sort its inner array using $sort:

```
collection.update({_id: id}, {$push: {
    arr: {
        $each: [{date: new Date(), value: 1}],
        $sort: {value: -1, date: -1}
    }
}}
```

One would expect this to sort `arr` as follows:
- Sort by Descending `value`
- Where value is equal, sort by Descending `date`

However, this doesn't happen and in fact it seems like its sorting just by `date`.

I checked that this feature works correctly using the native mongodb driver but it does not work as expected in mongoose.

**Comment by vkarpov15** [comment]
Looks like this might be another case of mongoose reversing things unnecessarily. Which version are you using?

**Comment by wlingke** [comment]
4.0.6



—
