### ISSUE TITLE
property default ignore null value(4.1.0)

### ISSUE THREAD

**Issue by alanpurple** [Automattic/mongoose#3218]
required:true check null value
default value applies to only undefined, not to null valud

It's not consistent, I think

**Comment by vkarpov15** [comment]
null is not the same thing as undefined. In particular, [null means *intentional* absence of an object value according to the language spec](http://www.ecma-international.org/ecma-262/6.0/#sec-null-value), so I'd argue that defaults shouldn't apply to null.

**Comment by alanpurple** [comment]
I see, thanks
