### ISSUE TITLE
Pre-save hooks in 4.x fire on parent before the subdocuments

### ISSUE THREAD

**Issue by burtonjc** [Automattic/mongoose#3219]
In mongoose 3.x, pre-save hooks fired on subdocuments prior to firing on parent documents. In 4.x it changed so now pre-save fires on the parent document prior to its subdocuments. I tracked it back to [these two commits](https://github.com/Automattic/mongoose/compare/03389a3ebc1ae78a510a10a4b26bd988fb46d35c...b3836e85322d923513339169f8accac8d7702cf3); however, most of the code changes in those commits have been moved around or changed again.

We have a use case where both the child and parent have pre-save hooks and the pre-save hook on the parent assumes the children have executed their pre-save's already. Here is a test illustrating the behavior.

```javascript
it('pre-save hooks fire on subducs before their parent doc', function(done) {
  var childSchema = Schema({ count: Number });

  childSchema.pre('save', function(next) {
    ++this.count;
    next();
    // On subdocuments, you have to return `this`
    return this;
  });

  var parentSchema = Schema({
    cumulativeCount: Number,
    children: [childSchema]
  });

  parentSchema.pre('save', function(next) {
    this.cumulativeCount = this.children.reduce(function (seed, child) {
      return seed += child.count;
    }, 0)
    next();
  });

  var db = start(),
      Child = db.model('Child', childSchema);
      Parent = db.model('ParentWithChildren', parentSchema);

  doc = new Parent({ children: [{ count: 0 }, { count: 1 }] });
  doc.save(function(err, doc){
    db.close();

    try {
      assert.strictEqual(doc.children[0].count, 1);
      assert.strictEqual(doc.children[1].count, 2);
      assert.strictEqual(doc.cumulativeCount, 3);
    } catch (e) {
      return done(e);
    }

    done();
  });
});
```
This test passes in 3.x but fails in 4.x becuase `doc.cumulativeCount` is `1` (it was calculated prior to the pre-save hook on the children incremented their count).

Was this an intended behavior change?

**Comment by vkarpov15** [comment]
I think this is an unintentional side effect of some work done to support promises a long time ago. Good job finding this issue, it's pretty subtle. As a matter of fact, AFAIK the relationship between pre save hooks on docs and pre save hooks on subdocs is not documented and we never supported one way or the other officially. Is there a way to make mongoose-encryption independent of this ordering?

**Comment by burtonjc** [comment]
I don't think so, at least not in a performant way. The ordering of middleware is a fundamental assumption for mongoose-encryption. As far as I know, the order never was documented anywhere; however, it is how it worked for a long time and (I *think*) it actually makes since for subdocument middleware to fire prior to the parent doc's.

If I am understanding how middleware works in mongoose v4, it isn't a small amount of work to get that order back. Though, if we all agree it should be that way, I am happy to spend some time figuring out a good path forward.

**Comment by vkarpov15** [comment]
Unfortunately this is often the downside of plugins - lots of reaching around into unsupported behavior.

I don't think it would be that difficult to fire child doc pre save hooks before pre save hooks, its just a matter of putting 'run .save() on all embedded docs' as the first pre save hook. Would that be enough to fix mongoose-encryption?

**Comment by burtonjc** [comment]
Ha, I actually spent some time yesterday doing exactly that. It makes the above test pass, but breaks another 2 tests. I am looking into them. If it works out I'll open a PR.

**Comment by vkarpov15** [comment]
Sounds good. I suspect the broken tests are tests that rely on the ordering of the pre save hooks - those have switched around a fair bit since 3.9.0...

**Comment by burtonjc** [comment]
I just opened https://github.com/Automattic/mongoose/pull/3220. Let me know what you think. I'm happy to iterate on it some if you see anything that could be improved.
