### ISSUE TITLE
Model.where({}).update().exec() not updating

### ISSUE THREAD

**Issue by joesonw** [Automattic/mongoose#3221]
Tried

```
yield Model
        .where('myId'),equals(id)
        .update({a:'1'})
        .exec()
```

and 

```
yield Model
        .where({'myId':id})
        .update({a:'1'})  
        .exec()
```

both returns 

```
 {ok:0,n:0,nModified:0}
```

However, the following works

```
yield Model.update(query,update,options).exec()
```

**Comment by vkarpov15** [comment]
Try

```javascript
yield Model
        .find()
        .where('myId'),equals(id)
        .update({a:'1'})
        .exec()
```

Off the top of my head I don't think Model even has a `where()` function, that's on the query builder..

**Comment by chazmo03** [comment]
I am also encountering this bug. The query's `update()` method doesn't seem to do a good job of parsing the parameters when you call it promise-style without a callback. One workaround is to pass in an empty set of conditions, e.g., `.update({}, {a:'1'}) `.

**Comment by vkarpov15** [comment]
@chazmo03 code example?

**Comment by testtube-** [comment]
I'm facing the same bug. Neither of these two work:

```
Model
    .where({ "_id": id })
    .update({ $inc: { views: 1 } })
    .exec(function (err, c) { ... });

Model
    .find()
    .where({ "_id": id })
    .update({ $inc: { views: 1 } })
    .exec(function (err, c) { ... });
```

Both return

     {ok:0,n:0,nModified:0}

Setting 'debug' to 'true' for mongoose shows that nothing is actually executed at all.

**Comment by vkarpov15** [comment]
@testtube- try just doing `Model.update({ _id: id }, { $inc: { views: 1 } });`. If that doesn't work, try executing the same query in the mongo shell.

**Comment by testtube-** [comment]
That did the trick. Is the chained version supported at all? At least the documentation shows it as an example: http://mongoosejs.com/docs/api.html#query_Query-update

**Comment by vkarpov15** [comment]
Yep the chained version should work in theory. I'll investigate.
