### ISSUE TITLE
mongoose 4.1.0 interferes with exception handling

### ISSUE THREAD

**Issue by dkashkin** [Automattic/mongoose#3222]
I just spent several hours and verified plenty of times that upgrading mongoose from 4.0.7 to 4.1.0 messes up exception handling in my node app. In other words, if I run "throw new Error('test')" after a few interactions with mongoose,  this exception never reaches my process.on('uncaughtException') handler. The same happens if I handle exceptions via node.js Domains. Everything works before I start hitting Mongoose, and even after the first few database queries. But then after running a several queries through mongoose 4.1.0 node stops calling my uncaughtException. I verified that process._events.uncaughtException still points at my function but node does not call it. I wish I could localize it better, but running out of time and decided to share because somebody might be struggling with the same thing... I am rolling back to 4.0.7 for now...
P.S. One more detail - my app never swallows exceptions. The uncaughtException handler always calls process.exit. I know that swallowing exceptions cause a lot of weird issues for V8, but we're not talking about this situation here.

**Comment by sitegui** [comment]
@dkashkin 

I got the same problem here and I can reproduce this with:
```js
'use strict'

var mongoose = require('mongoose')
mongoose.connect('mongodb://localhost:27017/mongoose')
var User = mongoose.model('user', new mongoose.Schema({}))

User.create({}, function () {
	console.log('Throwing exception, see it crashing...')
	setTimeout(function () {
		console.log('Ops! The exception went somewhere else')
		process.exit()
	}, 100)
	throw new Error('This should crash the process')
})
```

In `mongoose@4.0.8` the exception crashes the process as expected.
In `mongoose@4.1.0` the exception vanishes

This does not seem to affect `find` and `update`.

**Comment by sitegui** [comment]
Using `git bisect` here, it seems this was introduced by 9de7aa3c86

**Comment by gergoerdosi** [comment]
I'm having an issue with this too, see https://github.com/hapijs/lab/issues/422 for details.

**Comment by ksullivan** [comment]
I'm having the same issue. It has the potential to cause a debugging nightmare.

This code works as expected:

    var mongoose = require('mongoose');

    mongoose.connect('mongodb://localhost/mongoose_bug', function (err) {
        var Test = mongoose.model('Test', {field: String});

        Test.find(function (err, tests) {
            // This error is written to stdout and terminates the process.
            throw new Error('test error');
        });
    });

This code does not work as expected:

    var mongoose = require('mongoose');

    mongoose.connect('mongodb://localhost/mongoose_bug', function (err) {
        var Test = mongoose.model('Test', {field: String});

        Test.create({field: 'bug!'}, function (err, test) {
            // This error is not written to stdout and does not terminate the process.
            // It is silently eaten somewhere in mongoose.
            throw new Error('test error');
        });
    });

**Comment by thanpolas** [comment]
Everything worked ok until 4.1.1, from then on all my error handling tests broke.

**Comment by siboulet** [comment]
Also having the issue here. Simply rethrowing model.save exception.

model.save(function(err) {
  if (err) throw err;
  ...
});

Exception is swallowed my Mongoose.

**Comment by terebentina** [comment]
This fails using the promise interface too - then() is never called:
```
doc.save().then(function() {...})
```

**Comment by vkarpov15** [comment]
@terebentina which version? Can you show me a more thorough code sample?

**Comment by terebentina** [comment]
@vkarpov15 ignore me, it was a problem with my code. The promise interface (mpromise) doesn't have `.catch()`, but the error saying that `catch() is not a function` was swallowed.

**Comment by niftylettuce** [comment]
@vkarpov15 Hey I just wanted to follow up here that unless we explicitly pass `.catch` on a `.save` (when it uses a callback, e.g. `req.user.save(callback).catch(doSomething)`), then an unhandled promise rejection gets thrown.  This isn't documented anywhere either, so people upgrading will have a broken app.

**Comment by vkarpov15** [comment]
Umm @niftylettuce can you provide an example and open up a separate issue? We've got tests covering that use case and they're passing

**Comment by niftylettuce** [comment]
I think you resolved this already @vkarpov15 with that fix you did I paypal'd you 40 for, right?

**Comment by vkarpov15** [comment]
Should be :+1:
