### ISSUE TITLE
$set is empty error when $set is not empty

### ISSUE THREAD

**Issue by zoellner** [Automattic/mongoose#3226]
I am getting a $set is empty error when running a Model.update call

    { [MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}]
      name: 'MongoError',
      message: '\'$set\' is empty. You must specify a field like so: {$set: {<field>: ...}}',
      index: 0,
      code: 9,
      errmsg: '\'$set\' is empty. You must specify a field like so: {$set: {<field>: ...}}' }

But my update call has a $set that is not empty (below an example of the stringified version of the update operation)

    { '$set':
       { 'history.values.$':
          { user: 54f814bd4c2c9b96e46dc5ae,
            isProcessed: true,
            date: 1438658340507,
            messages: 0 } },
      '$inc': { totalMessages: 0 } }

I confirmed by turning on mongoose debug that the command sent to the database is actually an empty $set. When I use Model.collection.update instead of Model.update with no other changes, the $set is not empty and passed through to the database correctly.

I'm not 100% sure yet what other conditions are required to reproduce.

**Comment by vkarpov15** [comment]
Try upgrading to 4.1.1, there were some related issues like #3203 with 4.0.8 and 4.1.0 where mongoose was casting out positional operators. Mongoose casts your queries, so mongoose mistakenly thought that 'history.values.$' was not in your schema with older versions.

**Comment by zoellner** [comment]
Thank you, it was indeed related to the other issue you referenced (I was focused on the MongoError 'is empty' and therefore didn't find that one). 4.1.1 works fine.
