### ISSUE TITLE
Post Save Hook returning Promise

### ISSUE THREAD

**Issue by thebergamo** [Automattic/mongoose#3228]
Hi!

I trying to return a Bluebird promise in Post save() Hook, but when I resolve the saveAsync() method, my post hook is not resolved yet. In my case I create a new document in other collection. After I save this document and my promise are resolved I trying to get the created doc on post hook, but the doc is not created yet.

Have a way to force the promise in post hook is fulfilled before the save promise?

Thanks in advance!

**Comment by vkarpov15** [comment]
First, [document post hooks don't get flow control](http://mongoosejs.com/docs/middleware.html#post), so post hooks don't necessarily execute before the code in `.save().then()` executes. Also, post save hooks don't know about promises, so long story short this isn't going to work.

**Comment by thebergamo** [comment]
Well, I think maybe mongoose need to have an event 'on('save')' and not using the post hook, because in many times we need to use a function after saving and the control flow need be respected.

Pre hook -> save -> Post hook -> resolve promise or callback.

And in the other hand have the really event listener!

What you think?

**Comment by vkarpov15** [comment]
Actually this is something that I've been planning for 5.0 but haven't created an issue for yet (now have, see #3232). Right now query post hooks get flow control, but document post hooks don't for compatibility. This limits the usefulness of post-save hooks for processing results. The new hooks library [kareem](https://www.npmjs.com/package/kareem) gives post save hooks flow control by default.

**Comment by anotheri** [comment]
@vkarpov15 
> First, document post hooks don't get flow control, so post hooks don't necessarily execute before the code in .save().then() executes.

And what's about error handling middleware? it doesn't work for me at all at least in that way as described in [docs](http://mongoosejs.com/docs/middleware.html#error-handling) (btw docs has 2 html elements with `error-handling` id, that link is for 2nd one).

I'm on Mongoose v.4.5.8, Bluebird plugged in.

**Comment by vkarpov15** [comment]
Error handling middleware is an exception, it does get flow control. Can you please provide a code sample which demonstrates your issue?

**Comment by vkarpov15** [comment]
Fixed in 5.0, see http://thecodebarbarian.com/introducing-mongoose-5.html#promises-and-async-await-with-middleware
