### ISSUE TITLE
Model.create(<array>, callback) is not returning an array of created documents.

### ISSUE THREAD

**Issue by jrthib** [Automattic/mongoose#3229]
````javascript
var TestModel = mongoose.model('TestModel');

TestModel.create([ {doc: 1}, {doc: 2}, {doc: 3} ], function(err, docs) {
    // This log only prints a single document rather than the array of created documents.
    console.log(docs);
});
````

Reference Model.create (http://mongoosejs.com/docs/api.html#model_Model.create]

**Comment by vkarpov15** [comment]
Which version of mongoose are you using? Mongoose 3.x returned documents as arguments rather than as an array [when you passed an array to `.create().`](http://mongoosejs.com/docs/3.8.x/docs/api.html#model_Model.create)

**Comment by jrthib** [comment]
Sorry, I should have mentioned the version. I'm on Mongoose 4.1.1. I was trying the array example shown here http://mongoosejs.com/docs/api.html#model_Model.create

**Comment by jrthib** [comment]
This is working. Turns out my module wasn't being updated when I checked the version in the `node_modules` folder.
