### ISSUE TITLE
Ability to de-select discriminator key

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3230]
Re: #3133.

**Comment by Catatomik** [comment]
Any update or lead on this ?
I'd like to remove the `__t` field, note that I'm using the `lean` option.

And this is all about memory consumption ; `__t` field for a lot of documents represents a lot of memory.

**Comment by vkarpov15** [comment]
@Catatomik can you provide some code samples that show what you're trying to achieve?

**Comment by Catatomik** [comment]
> @Catatomik can you provide some code samples that show what you're trying to achieve?

Of course, here's a short code sample :
```ts
const dbScheduledRoutes = await TBMScheduledRoutesModel.find<DocumentType<ScheduledRoute>>({}, dbScheduledRoutesProjection)
      .sort({ _id: 1 })
      .populate("trips.schedules", { hor_app: 1, hor_estime: 1, _id: 0 })
      .lean()
      .exec()
```

My types are made with **typegoose**.
`trips.schedules` is `Ref<dbTBM_Schedules_rt>[]`.

The important part is about `schedules`, which is a discriminator.
Short schemas : 
```ts
@modelOptions({ options: { customName: TBMEndpoints.Schedules } })
export class dbTBM_Schedules extends TimeStamps {
  @prop({ required: true })
  public hor_theo!: Date;
}

@modelOptions({ options: { customName: TBMEndpoints.Schedules_rt } })
export class dbTBM_Schedules_rt extends dbTBM_Schedules {
  @prop({ required: true })
  public hor_app!: Date;

  @prop({ required: true })
  public hor_estime!: Date;
}
```

So when populating through `.populate("trips.schedules", { hor_app: 1, hor_estime: 1, _id: 0 })`, I'd like to keep **only** `hor_app` and `hor_estime`. I got to remove `_id` (well documented, this filed is the only exception where you can make an exclusion with an inclusion projection), but nothing about the `__t` field).

A possible solution would be making an exclusion projection only, and put `__t` in. Don't know if it would work, but I strongly prefer to keep an inclusion projection.

**Comment by vkarpov15** [comment]
@Catatomik you can also deselect `__t` in an inclusive projection. Mongoose will automatically strip out `__t` from the projection before sending it to MongoDB, and then strip out `__t` from the result. See the following script for a Mongoose example:

```javascript
'use strict';
  
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
  const D = Test.discriminator('D', mongoose.Schema({ prop: String }));

  await Test.deleteMany({});
  await D.create({ name: 'foo', prop: 'bar' });

  console.log(await D.findOne().select({ name: 1, prop: 1, _id: 0, __t: 0 })); // { name: 'foo', prop: 'bar' }, no __t
}

```

**Comment by Catatomik** [comment]
> @Catatomik you can also deselect `__t` in an inclusive projection. Mongoose will automatically strip out `__t` from the projection before sending it to MongoDB, and then strip out `__t` from the result. See the following script for a Mongoose example:
> 
> ```js
> 'use strict';
>   
> const mongoose = require('mongoose');
> 
> run().catch(err => console.log(err));
> 
> async function run() {
>   await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
>   const Test = mongoose.model('Test', mongoose.Schema({ name: String }));
>   const D = Test.discriminator('D', mongoose.Schema({ prop: String }));
> 
>   await Test.deleteMany({});
>   await D.create({ name: 'foo', prop: 'bar' });
> 
>   console.log(await D.findOne().select({ name: 1, prop: 1, _id: 0, __t: 0 })); // { name: 'foo', prop: 'bar' }, no __t
> }
> ```

Well I tried that : 
When I append `__t: 0` to the inclusion projection (here `.populate("trips.schedules", { hor_app: 1, hor_estime: 1, _id: 0 })`), I get the following error : `MongoServerError: Cannot do inclusion on field hor_estime in exclusion projection`.
Note that without this `__t: 0`, code works well.
I use mongoose@7.6.3.

It might be due to the population ? Or my Schema ?

**Comment by vkarpov15** [comment]
What is your discriminator key? Perhaps it is set to a different value than `__t`.

**Comment by Catatomik** [comment]
> What is your discriminator key? Perhaps it is set to a different value than `__t`.

I don't think so...
```ts
{
  hor_app: "+275760-09-13T00:00:00.000Z",
  hor_estime: "+275760-09-13T00:00:00.000Z",
  __t: "TBM_Schedules_rt",
}
```

**Comment by vkarpov15** [comment]
Might be due to populate, we will check

**Comment by vkarpov15** [comment]
Looks like it is due to populate(), the following throws `Cannot do inclusion on field prop in exclusion projection`

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test');
  const Test = mongoose.model(
    'Test',
    mongoose.Schema({ name: String, arr: [{ testRef: { type: 'ObjectId', ref: 'Test2' } }] })
  );

  const schema = mongoose.Schema({ name: String });
  const Test2 = mongoose.model('Test2', schema);
  const D = Test2.discriminator('D', mongoose.Schema({ prop: String }));


  await Test.deleteMany({});
  await Test2.deleteMany({});
  const { _id } = await D.create({ name: 'foo', prop: 'bar' });
  let test = await Test.create({ name: 'test', arr: [{ testRef: _id }] });

  console.log(await Test.findById(test._id).populate('arr.testRef', { name: 1, prop: 1, _id: 0, __t: 0 }));
}

```

**Comment by vkarpov15** [comment]
As a workaround, use `.populate("trips.schedules", { hor_app: 1, hor_estime: 1, _id: 0, '-__t': 0 })`
