### ISSUE TITLE
ObjectId equality not working

### ISSUE THREAD

**Issue by joshperry** [Automattic/mongoose#3237]
The ObjectID equality doesn't seem to be working properly which makes it really difficult to work with arrays of ObjectIds.

![image](https://cloud.githubusercontent.com/assets/298053/9102553/01c7e41a-3bb1-11e5-99a5-916921782c38.png)

**Comment by vkarpov15** [comment]
Object ids are objects in NodeJS (otherwise the node driver wouldn't know whether they were ObjectIds), so `===` is never going to work for ObjectIds. `oid == oid2.toString()` works, as does deep equality check (so lodash's `.where()` and `findWhere` functions works fine).

**Comment by joshperry** [comment]
@vkarpov15 So it's worse than I expected, I suppose. Do most people just deal exclusively with ObjectIds as strings to mitigate confusion when surrogate ID comparison is necessary?

**Comment by vkarpov15** [comment]
By definition, ObjectIds are 12 arbitrary bytes. The string form is convenient because you can represent 12 arbitrary bytes as 24 hex chars, and thus easily transfer ObjectIds using text-encoded protocols like JSON. However, in NodeJS, the actual ObjectId type is an object with a 12 byte buffer - we don't use a plain-old buffer because then there's no good way to say "I really mean for this buffer to be an ObjectId". You can also compare the ObjectId's `.id` field, which is the buffer.

```
$ node
> var mongodb = require('mongodb');
undefined
> var o1 = mongodb.ObjectId()
undefined
> o1
55c4caa4ece723b21cad5ffc
> var o2 = new mongodb.ObjectId("55c4caa4ece723b21cad5ffc");
undefined
> o2
55c4caa4ece723b21cad5ffc
> o2 === o1
false
> o1.id === o2.id
true
> o1.id
'UÄÊ¤ìç#²\u001c­_ü'
```

**Comment by fafamnzm** [comment]
transferring both ids to string using .toString() however, seems to work fine, so oid1.toString() === oid2.toString() work fine

**Comment by vkarpov15** [comment]
We introduced a workaround for this in Mongoose 5.4: https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters .

```javascript
const schema = new mongoose.Schema({
  test: {
    type: mongoose.ObjectId,
    get: v => v.toString() // Convert `test` to a string when you do `doc.test`
  }
}, { _id: false });
```

You can tell Mongoose to automatically convert ObjectIds to strings every time they're accessed as shown below:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');

mongoose.ObjectId.get(v => v.toString());

const schema = new mongoose.Schema({
  test: mongoose.ObjectId
}, { _id: false });

const Model = mongoose.model('Test', schema);

const doc = new Model({ test: '5c2e35400844102978e69f8c' });

// `doc.test` will always be a string
assert.ok(typeof doc.test === 'string');
assert.ok(doc.test === '5c2e35400844102978e69f8c');

const doc2 = new Model({ test: doc.test.toString() });

// So you can compare ObjectIds using `===`
assert.ok(doc.test === doc2.test);

const doc3 = new Model({ test: 'bad' });
assert.ok(doc3.validateSync() instanceof Error); // Mongoose still casts
```
