### ISSUE TITLE
Retrieving fields on queries with .where .findOne() (.get("field") != .field)

### ISSUE THREAD

**Issue by lrabiet** [Automattic/mongoose#3239]
While doing query using `.where` or `.$where`, I cannot use `doc.get("field")` on the retrieved docs ("undefined" error).
It works with a query using `.findOne` `.find.` 
If I use `doc.field` it returns the correct value.

 mongod -version
> db version v3.0.4
> git version: nogitversion
> OpenSSL version: OpenSSL 1.0.2c 12 Jun 2015

 node -v
> v0.12.5

grep mongoose package.json
>     "mongoose": "^4.0.6"

**Comment by vkarpov15** [comment]
Can you show me a more complete code example please?
