### ISSUE TITLE
Reference subdocument is not getting populated with subdocument which is also in same collection

### ISSUE THREAD

**Issue by sham332** [Automattic/mongoose#3244]
Below is the schema  design code

```javascript
var mongoose = require('mongoose'),
	Schema = mongoose.Schema;
var ObjectId = mongoose.Schema.Types.ObjectId;

mongoose.set('debug', true);

var chapter = new Schema({
  title:String,
  startPage:Number,
  endPage:Number
});
mongoose.model('chapter', chapter);

var keyPoint = new Schema({
  text:String,
  mentionInChapter:[{type: Schema.ObjectId, ref: 'chapter'}]
});
mongoose.model('keyPoint', keyPoint);

var Book = new Schema({
   title:String,
   author:String,
   chapters:[chapter],
   keyPoints:[keyPoint]
});

mongoose.model('Book', Book);
```

And when I try to retrieve Book populated with all values, I get blank array. Below is express module containing the query 

```javascript
	exports.getCompleteBook = function(req,res){
		var bookId = '55c65c8749286ac0e25d1f58';
		Book.findById(bookId)
		.lean() 
		.populate({ path: 'keyPoints' }) 
		.exec(function (err, docs) {
			if (err) throw err;
			console.log(docs);
			Book.populate(docs, {path: 'keyPoints.mentionInChapter', model : 'chapter', select:'title'}, function (err, book) {
			  if (err) throw err;
			  res.json(book);
			});
		});
	};
```

This link to jist has further on data etc, https://gist.github.com/sham332/20ad1c7b1b460c478700

I should have recieved the 'mentionInChapter' subdocument populated with values, but it is coming blank.

**Comment by vkarpov15** [comment]
What you're gonna want is:

```javascript
var Book = new Schema({
   title:String,
   author:String,
   chapters:[{type: Schema.ObjectId, ref: 'chapter'}],
   keyPoints:[{type: Schema.ObjectId, ref: 'keyPoint'}]
});
```

If you're [embedding subdocs](http://mongoosejs.com/docs/subdocs.html), you're not going to be able to run `populate()` on the array, because the subdocs are stored in the doc itself rather than in a separate collection.

**Comment by ogheneovo12** [comment]
what if the subdoc contains a reference to an item in another collection,
take for a example a cart with a subdoc of CartItem that references Product in another Collection.

**Comment by vkarpov15** [comment]
That's fine, as long as `Product` is a Mongoose model. We have a [sample app with a very similar setup to what you're describing](https://github.com/mongoosejs/sample-apps/blob/d7c4e780c21d046fa069c971ea27497df721de0c/netlify-functions-ecommerce/models.js#L79), a cart with an array of subdocuments with a `productId` property that points to a `Product` model.
