### ISSUE TITLE
Failing to automatically re-connect to New PRIMARY after a replica set failover , from Mongoose (MongoDB, NodeJS Driver)

### ISSUE THREAD

**Issue by tayal8** [Automattic/mongoose#3247]
Hi,

I have seen this issue being reported by many users. The issue i am getting is i have 3 node mongo replica set. I pass the 3 servers ip in mongoose connect uri. It gets connected to primary correctly.
My mongo primary goes down, and new gets elected, the switchover gets done in code correctly. Now if i step down primary or my primary goes down second time, the application is stuck on queries and not able to make connection, till is restart the application.

**Comment by vkarpov15** [comment]
Set the `replSet.connectWithNoPrimary` option: http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html . By default, the mongodb node driver will refuse to say it successfully connected until the replica set has a primary, so you won't be able to re-connect if 2 members of a 3 node replica set are down.

**Comment by triccardi-systran** [comment]
This is possibly related to https://github.com/Automattic/mongoose/issues/3299, which is fixed since mongoose v4.1.5.
