### ISSUE TITLE
Populate from reference document

### ISSUE THREAD

**Issue by senyorails** [Automattic/mongoose#3248]
May be something i may be doing wrong, but how do i populate specific fields from my reference doc?
 Schema definitions:

```javascript
var ProductSchema = new Schema({
  name: {type: String, required: true, index: {unique: true, dropDups: true}, trim: true, es_indexed: true},
  description: {type: String, required: true, trim: true, es_indexed: true},
  price: {type: Number, required: true, validate: validators.isFloat()},
  quantity: {type: Number, rquired: true},
  categories: {type: [String], enum:['vegetables', 'fruits', 'dairy', 'grains', 'proteins'], required: true, trim: true, es_indexed: true},
  processed: {type: Boolean, default: false},
  images:[{type: String, required: true, trim: true, validate: validators.isURL()}],
  location: [{type: Schema.Types.ObjectId, required: true, validate:[noEmpty, 'Location can not be empty'], ref: 'Location'}]
});

var LocationSchema = new Schema({
  city:{type:String, required: true, unique: true},
  geometry: {
    type: {type:String, default:'Point'},
    coordinates: [Number],//format [long, lat]
  }
});
LocationSchema.index({geometry:'2dsphere'});
```

I want to be able to populate the right coordinates in my product during save when the user enters a city.

This is what i am doing:

```javascript
  product.save(function(err){
        if(!err)
        {
          Product.find({})
            .populate('location', 'geometry.coordinates')
            .exec(err, product)
            {
              if(err)
              res.status(500).send(err);
              else
              return res.status(200).send(product);
            }
```

**Comment by vkarpov15** [comment]
Can you please clarify? I don't understand what you're trying to do.

**Comment by senyorails** [comment]
Thanks for the prompt response.
I am trying to populate location coordinates into each product document by referencing the document. Note these documents are separate schema files. 
Eg.:
  {
    "_id": "55c371be295d0145078c5daf",
    "city": "Plano",
    "__v": 0,
    "geometry": {
      "coordinates": [
        -96.698883,
        33.019844
      ],
      "type": "Point"
    }
Is a location document
And this is a product document:
{
    "_id": "55c78c500e5f3f9db06e2045",
    "name": "Ghost Pepper",
    "description": "extremely hot pepper cultivated in Indian",
    "price": 1,
    "quantity": 100,
    "__v": 0,
    "location": [],
    "images": [
      "http://somcdn.gallery.com"
    ],
    "processed": false,
    "categories": [
      "vegetables, fruits"
    ]
  }
If you notice, the location is an empty array even though i referenced the location document. Is this helpful? What i want to be able to do is populate where city is for example Plano, i want to populate the coordinates in products

**Comment by vkarpov15** [comment]
What does the product document look like if you don't call `populate()` on 'location'? It might be that the document just has the wrong id.

Also, try enabling mongoose debug mode, `require('mongoose').set('debug', true);`, and show me the queries that happen.

**Comment by senyorails** [comment]
This is the debug for adding a new document to product:
Mongoose: products.insert({ name: 'Red Chili Pepper', description: 'Hot peppers also known as chili', price: 0.5, quantity: 50, _id: ObjectId("55ca052004d2568db628bfee"), location: [], images: [ 'http://somecdn.gallery.com' ], processed: false, categories: [ 'fruits' ], __v: 0 })

**Comment by senyorails** [comment]
And also this: Mongoose: products.find({}) { fields: undefined }

**Comment by vkarpov15** [comment]
Are you emptying the database? Since you're doing `find()` with no criteria, you might just be getting an old document.

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
