### ISSUE TITLE
How to catch db error when mongo is disconnected

### ISSUE THREAD

**Issue by syter** [Automattic/mongoose#3252]
I have used nodeJS+express+mongoose for a server project.

There is an issue I found that is I can't catch error when mongo is disconnected.

Here is code:

	var App = require('../../../service/apps/models').App;
	console.log("==============================appKeyFilter=====33333333");
	App.findOne({key: key}).exec(function (err, app) {
		console.log("==============================appKeyFilter=====55555555");
		if (err) {
			console.log("=============================err:" + require('util').inspect(err));
			return;
		}
                console.log("==============================appKeyFilter=====66666666");
		if (app) {
			callback(app._id);
		} else {
		  	callback();
		}
	});

And my step is :
 1. start mongo

 2. start server

 3. stop mongo. 
    After this step, the server console will notice Mongoose error: Error: failed to connect to [localhost:27017] every sec. Because I have set auto_reconnect : true.

 4. use curl command call an API
    the server console just notice 
==============================appKeyFilter=====33333333
[2015-08-11 12:48:08.885] [ERROR] mrm - Mongoose error: Error: failed to connect to [localhost:27017]
==============================appKeyFilter=====33333333
[2015-08-11 12:48:09.895] [ERROR] mrm - Mongoose error: Error: failed to connect to [localhost:27017]

    At the same time, curl command is handle, no response.

 5. start mongo
    curl command received response 200
    server console notice 
"==============================appKeyFilter=====55555555"
"==============================appKeyFilter=====66666666"

It seems when mongo is disconnected, execute collection.find() will keep waiting until mongo is reconected.
So if I can't execute step 5, lots of http request will handle.

Is there any way to catch this error?
Thanks.

**Comment by vkarpov15** [comment]
[Set the `bufferCommands` schema option to false](http://mongoosejs.com/docs/guide.html#bufferCommands)

**Comment by syter** [comment]
Hi @vkarpov15 ,
 I found bufferCommands only works when set auto_reconnect : false.
 How can I get error when auto_reconnect is true?
 Thanks.

**Comment by vkarpov15** [comment]
[Set the `db.bufferMaxEntries` option to 0](http://mongodb.github.io/node-mongodb-native/2.0/api/Db.html) on your [mongoose connection](http://mongoosejs.com/docs/api.html#connection-js)
