### ISSUE TITLE
Migrating from 3.x to 4.x, create() has different behavior

### ISSUE THREAD

**Issue by wcp1231** [Automattic/mongoose#3254]
example:
```
var UserSchema = new Schema({
  name: { type: String, required: true },
  password: { type: String, required: true }
});

var PostSchema = new Schema({
  author: { type: Schema.Types.ObjectId, ref: 'User' },
  content: { type: String, required: true }
});

var User = mongoose.model('User', UserSchema);
var Post = mongoose.model('Post', PostSchema);

function main() {
  User.findOne({ _id: u._id }).exec().then(function(u) {
    return Post.create({
      author: u,
      content: 'something'
    });
  }).then(function(post) {
    console.log(post);
  });
}

main();
```

In `3.8.x` will output like this:
```
{ __v: 0,
  author: 55c9a08c502b1dad0420bcaa,
  content: 'something',
  _id: 55c9a08c502b1dad0420bcab }
```

But in `4.x` will output:
```
{ __v: 0,
  author:
   { _id: 55c9a1c7e0e1ca600764b83e,
     name: 'exampleUser',
     password: '123456',
     __v: 0 },
  content: 'something',
  _id: 55c9a1c7e0e1ca600764b83f }
```

But in [4.0-Release-Notes][1] I can't find something relate to it...

Am I missing someting ?

[1]: https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes

**Comment by vkarpov15** [comment]
Looks like #1530 wasn't in the [4.0 release notes](https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes). Now it is. General idea is that when you set `post.author` to a 'User' doc, mongoose will treat it as if you had done a `.populate()` on `post.author`. That's why this feature is sometimes called 'manual population' like in #2370. The document saved to the database should still be:

```
{ __v: 0,
  author: 55c9a08c502b1dad0420bcaa,
  content: 'something',
  _id: 55c9a08c502b1dad0420bcab }
```

Just the document you see in node is the one with 'author' populated. Is it saving the populated doc into the database? If so, that would be a bug.

**Comment by wcp1231** [comment]
It have no populated doc in database, it is alright.

So, It mean when I create a `post` which `author` field set to a `user` doc, then `create()` will auto `populate()` on `post.author` ?

And it is a breaking change from 3.8.x to 4.x, right ?

**Comment by vkarpov15** [comment]
Yep. `.create()` is just a thin wrapper for `new Post().save();` anyway. And yeah this is a backwards breaking change. 3.8.x does not have this behavior.

**Comment by attritionorg** [comment]
I know this is an old ticket, but curious about the changelog entry referencing it vs the content above, which don't immediately seem to be related?

4.2.4 / 2015-11-02
fixed; upgraded  ms  package for security vulnerability #3254 fhemberger

**Comment by vkarpov15** [comment]
Woops that's a typo, meant to be #3524
