### ISSUE TITLE
bson dependency fixed at ~0.3

### ISSUE THREAD

**Issue by olingerc** [Automattic/mongoose#3259]
Any reason why bson is fixed at 0.3.x?
The bson-ext developer [suggested](https://github.com/christkv/bson-ext/issues/24) to change this in order to resolve an issue I had during mongoose installation. Bascially the bson dependency installed an optionalDependency: bson-ext. The installation of the latter caused my system to give errors which are not really related to mongoose itself.

**Comment by vkarpov15** [comment]
Nope that was mongoose being slightly out of date. Mongoose includes bson directly for the sake of being compatible with browserify, and hadn't upgraded to the newest version of bson. Thanks for pointing this out.
