### ISSUE TITLE
Expose formatting for logging

### ISSUE THREAD

**Issue by newmanw** [Automattic/mongoose#3261]
I am using winston as my logger and want to log using that instead of letting mongoose log.

I know that I can do this:

``` javascript
var logger = //create winston logger
mongoose.set('debug', function(collection, method, query, doc, options) {
   logger.trace(//log some mongoose stuff...
}
```

However I get raw objects.  Which is for sure the right thing as I agree at this point it is my job to do with those as I please.

However there is a decent amount of code here to format debug logs:
https://github.com/Automattic/mongoose/blob/d563355be9e24a907b31e94877836d201b5c9406/lib/drivers/node-mongodb-native/collection.js

It would be nice if those formatters where exposed such that I can use them.  At least at that point if mongoose decides to change the format of the objects the formatters will probably be updated as well.

Don't really want to copy/paste and maintain the same formatting code.

**Comment by vkarpov15** [comment]
This is a great suggestion. Will work on it in the future; PRs welcome.

**Comment by object88** [comment]
I am unfamiliar with github... is it appropriate to share enthusiasm for a feature request here?  Because I while coding up some logging last night, I was hoping for _exactly_ this.  Thanks!

**Comment by vkarpov15** [comment]
You're welcome to share enthusiasm :) I like this feature request as well.

**Comment by newmanw** [comment]
Awesome thanks!  Possible to add some docs here on how to get access to those exposed methods using custom logger?

I.E.

```javascript
mongoose.set('debug', function(collection, method, query, doc, options) {
   // use mongoose $format here
}
```

**Comment by vkarpov15** [comment]
Yep will do re: #3557

**Comment by newmanw** [comment]
Once again can't thank you enough.  Such a great lib and tremendous support!

**Comment by newmanw** [comment]
Sorry to nag, just checking in again.  It does indeed look the the $print and $format functions are exposed from https://github.com/Automattic/mongoose/blob/d4744a985f6e804319dc54900ccd04a4b8189197/lib/drivers/node-mongodb-native/collection.js#L147-L168

However accessing that inside my custom logger function seems to be a bit of a hack as those functions are attached to the collection (which is not passed in):

```javascript
mongoose.set('debug', function(collection, method, query, doc, options) {
  // Grab the format function from one of my models, any model
  var format = mongoose.model('SomeModel').collection.$format;
  // now use format
  ...
});

```

Wondering if the NativeCollections scope could just be passed to the debug function?

https://github.com/Automattic/mongoose/blob/d4744a985f6e804319dc54900ccd04a4b8189197/lib/drivers/node-mongodb-native/collection.js#L129-L130

```javascript
debug.apply(self
   , [self.name, i].concat(utils.args(args, 0, args.length - 1)));
```
