### ISSUE TITLE
When using autoIndex does it create the indexes in the background

### ISSUE THREAD

**Issue by nodesocket** [Automattic/mongoose#3262]
When using `autoIndex` does it ensure index, with `background: true`? The documentation does not specify. If not background, can you specify it?

**Comment by vkarpov15** [comment]
Mongoose does use background indexes by default. If you want to shut this off, just set `background: false` in [the `schema.index()` function's options arg](http://mongoosejs.com/docs/api.html#schema_Schema-index)
