### ISSUE TITLE
How to set auto_reconnect options?

### ISSUE THREAD

**Issue by syter** [Automattic/mongoose#3266]
Hello,
  I found if set auto_reconnect: true, when mongo is down, mongoose will auto_reconnect __only 1 mins for 1time/sec.__

 How can I set the auto_reconnect time and frequency？

**Comment by vkarpov15** [comment]
`server.reconnectTries` and `server.reconnectInterval` in options passed to `mongoose.connect()` or `mongoose.createConnection()` http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html
