### ISSUE TITLE
elemMatch doesn't work as expected

### ISSUE THREAD

**Issue by Zane-XY** [Automattic/mongoose#3272]
I have the following native mongo query, it is working as expected, but I failed to convert this into the equivalent mongoose query:

<img width="611" alt="screen shot 2015-08-15 at 12 28 15 pm" src="https://cloud.githubusercontent.com/assets/2939476/9287477/28a46e42-4349-11e5-8db3-45989e7ba534.png">

Use elemMatch, but the match doesn't work,
```javascript
findById(empId)
.elemMatch("leavesHistory", {_id: historyId})
.select("leavesHistory.days leavesHistory.leaveType")
.exec();
```
gives:
```javascript
{ _id: 55cb020a9cabdf13503db51e,
  leavesHistory: 
   [ { days: 1, leaveType: 'AL' },
     { days: 1, leaveType: 'AL' },
     { days: 1, leaveType: 'AL' },
     { days: 2, leaveType: 'SL' },
...
}
```
or this one, it matched but doesn't select the correct projection:
```javascript
findOne({_id: empId}, {
	 "leavesHistory": {$elemMatch: {"_id": historyId}},
	 'leavesHistory.days': 1,
	 'leavesHistory.leaveType': 1
	 }).exec()
```
Want to know is it a bug or I did it wrong?

**Comment by vkarpov15** [comment]
Please enable mongoose debug mode, `require('mongoose').set('debug', true);`, and show me the output.

**Comment by vkarpov15** [comment]
Bug in mquery, fixed here: https://github.com/aheckmann/mquery/commit/92b6261aef1e45d9a095b62e747a0879fbe765aa
