### ISSUE TITLE
Uncaught TypeError: `mongoose.model is not a function`

### ISSUE THREAD

**Issue by georgiana-gligor** [Automattic/mongoose#3277]
I am trying to setup a React isomorphic application.
My `server.js` contains the following
![server-js-model-works](https://cloud.githubusercontent.com/assets/1164711/9301203/7b12d316-44d5-11e5-8cbf-6b4d5f68e758.jpg)

and when I look in the console, it is showing up properly, the model is parsed, the schema is there.
![printed-from-server-js-line-32](https://cloud.githubusercontent.com/assets/1164711/9301217/8eb0047a-44d5-11e5-8401-02bcb8746575.jpg)

In the `SessionStore.js` file, I am also including mongoose and trying to use it,
![sessionstore](https://cloud.githubusercontent.com/assets/1164711/9301453/3cd36d3e-44d7-11e5-9934-46e9efff0715.jpg)

If I do print `mongoose.model` it is indeed a function:
![printed-function-from-line-19](https://cloud.githubusercontent.com/assets/1164711/9301467/57a51dba-44d7-11e5-8bcf-b5f8287c9d98.jpg)

but in the browser I am getting this error:
![error](https://cloud.githubusercontent.com/assets/1164711/9301455/47d10714-44d7-11e5-8a14-18b311f4b1b7.jpg)

**Comment by georgiana-gligor** [comment]
Up.

**Comment by vkarpov15** [comment]
Unfortunately mongoose's browser component is **extremely** limited. [It doesn't actually have models - the general idea is that mongoose schema declarations are isomorphic, but not much else](http://mongoosejs.com/docs/browser.html). The correct way to use it is to make the schema declaration isomorphic and then have [separate browser code that creates a new `Document`](http://mongoosejs.com/docs/browser.html).

**Comment by georgiana-gligor** [comment]
Thank you very much for pointing me to the right direction, with just the `Schema` being isomorphic.
It is very helpful.
