### ISSUE TITLE
Unable to push objects to an array in an object

### ISSUE THREAD

**Issue by prssn** [Automattic/mongoose#3278]
The code will explain it better. It works fine with 4.0.7, but not with newer versions.

```javascript
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var User = mongoose.model('User', {
    username: String,
    attributes: {}
});

User.create({ username: 'Foo' }).then(function (user) {

    // This works fine
    User.update({ _id: user._id }, { '$push': { 'attributes.friends': 'Bar' } })
.then(console.log, console.error);

    // This one neither gets resolved or rejected
    User.update({ _id: user._id }, { '$push': { 'attributes.scores': { a: 1 } } })
.then(console.log, console.error);
});
```
MongoDB version: 2.6.5
Mongoose version: 4.0.8 and above
Node version: 0.10.39

**Comment by vkarpov15** [comment]
Looks like this was fixed by  https://github.com/aheckmann/mquery/commit/0843863d166a5b6320ae240f046c9cca4b671621 and https://github.com/Automattic/mongoose/commit/0b4def218a155e3d314f374d7ac9f0344443aefb

**Comment by prssn** [comment]
Well it resolves in 4.1.4 & 4.1.5. But the issue now is that the document doesn't get updated.

```javascript
{
    "username": "Foo",
    "attributes": {
        "friends": [
            "Bar"
        ]
    }
}
```

**Comment by vlapo** [comment]
Hi @prssn. Please check https://github.com/Automattic/mongoose/issues/3337. I think it is your issue, too.

**Comment by vkarpov15** [comment]
Yeah @vlapo is right, same issue. Let's track that particular issue there.
