### ISSUE TITLE
query.exec() behaviour

### ISSUE THREAD

**Issue by Zane-XY** [Automattic/mongoose#3282]
I don't know if I understand this correctly, in mongoose, query.exec() always returns Promise and returns immediately, until I read this from documentation:

> q.update({ $set: { name: 'bob' }}).exec(); // executed as unsafe
> The operation is only executed when a callback is passed. To force execution without a callback > (which would be an unsafe write), we must first call update() and then execute it by using the exec() method.

What does ".exec() executed as unsafe" mean? Is there any way I can return a Promise, while keep it safe?

**Comment by vkarpov15** [comment]
Not sure what that's about, but there's no reason why .exec() should be unsafe.

**Comment by psabharwal3** [comment]
still hasn't been updated in http://mongoosejs.com/docs/api.html#query_Query-update
