### ISSUE TITLE
Query.count() method doesn't ignore skip/limit per Mongo's count implementation

### ISSUE THREAD

**Issue by JasonCust** [Automattic/mongoose#3283]
The current implementation of [`Query.count`](http://mongoosejs.com/docs/api.html#query_Query-count) includes the effects of `Query.skip` and `Query.limit`. MongoDB's implementation of [`cursor.count`](http://docs.mongodb.org/manual/reference/method/cursor.count/#cursor.count) states:
> By default, the `count()` method ignores the effects of the `cursor.skip()` and `cursor.limit()`.

After looking into the [codebase](https://github.com/Automattic/mongoose/blob/cd75baa58112847c92dca95ffcd3dc22c9a048f9/lib/query.js#L1250-L1256) it doesn't appear this is the intended implementation:

     /**
     * Thunk around count()
     *
     * @param {Function} [callback]
     * @see count http://docs.mongodb.org/manual/reference/method/db.collection.count/
     * @api private
     */

For example: Assuming a collection of 24 documents

    // Mongo
    db.collection.find().skip(5).limit(3); // an array of 3 docs
    db.collection.find().skip(5).limit(3).count(); // 24
    // Mongoose
    var query = Model.find().skip(5).limit(3);
    query.exec().then(function (docs) {
      // docs is an array of 3 docs
    });
    query.count().exec().then(function (count) {
      // count === 3
      // expected count value is 24
    });

Tested on Mongoose 4.1.1, Mongo 3.0.5, Node 0.12.6

**Comment by vkarpov15** [comment]
Unfortunately those docs are specific to the mongodb shell, not to the drivers. The mongodb crud spec says that skip and limit are valid options for count, and there's no applyskiplimit option. This is just a case of the shell being out of date with our spec.

**Comment by JasonCust** [comment]
Out of curiosity and also for clarification, the shell/mongodb docs are out of date but the crud spec is accurate? If so, does that mean the shell will eventually be updated to mirror the crud spec and not vice versa?

**Comment by vkarpov15** [comment]
@JasonCust yep that's the general idea, at least for the 3.2 shell. See https://github.com/mongodb/mongo/pull/1004.

**Comment by krobing** [comment]
For simulate the behavior of mongodb's applySkipLimit parameter in mongoose, I used this code (used it the unserscore.js library method clone) :
`var notificationsUser = {};
                       var notifyCount = 0;
						var notifyQuery = Notification.find({
							$or: [{"receivedBy": user}, {isGlobal:true}],
							readBy: { $nin: [user] }
						});

					// Get notifications quantity
					_.clone(notifyQuery).count(function (err, count) {
						if(err) return err;

						notifyCount = count;

						// Get notifications
						notifyQuery.sort({created:-1}).limit(1).exec(function (err, nots) {
							if(err) return new Error(err.message);

							notificationsUser = nots;

						}).then(function (nots) {

							// Send notifications for user
							socket.emit('getNotifications', notificationsUser, notifyCount);
						});
					});`

**Comment by huy-lv** [comment]
Why this issue is 'wont fix', this is a necessary function for pagination feature :(

**Comment by robertsLando** [comment]
@vkarpov15  This is used on pagination because when you need to load data in a table with multiple pages you use `skip` and `limit` to load a specific page but you need total items `count` to know how many pages to show (so the user can switch to a specific page)

**Comment by vkarpov15** [comment]
@robertsLando in that case you need 2 separate queries, a find() and a countDocuments()

**Comment by robertsLando** [comment]
@vkarpiv15 the mongoose-paginate package that I have mentioned in my previous comment is what I was looking for

**Comment by baryon** [comment]
we have to use native connection.

```
const query = StudentModel.collection.find(
    {
       age: 13
    }, 
    {
       projection:{ _id:0 }
    }
    ).sort({ time: -1 })
const count = await query.count()
const records = await query.skip(20)
          .limit(10).toArray()

```
