### ISSUE TITLE
[Bug] too many connections being opened for pool

### ISSUE THREAD

**Issue by robpolak** [Automattic/mongoose#3289]
I am current running 4.1.3 with a replicaset, I am running a pool size of **50**.  On startup my application went from 219 connections to 766 = **~467** connections from my IP address.  

I cannot think this is expected behavior, this led from a problem in our production environment where way too many connections were being established.

**Mongodlogs:**

2015-08-20T15:46:26.235+0000 [initandlisten] connection accepted from x.x.x.x:25438 #3628 (**219** connections now open)
   .....
2015-08-20T15:46:29.333+0000 [initandlisten] connection accepted from  x.x.x.x:25985 #4175 (**766** connections now open)

**setting:**

 "replset": {
          "poolSize": 50,
          "socketOptions": {
            "keepAlive": 1,
            "connectTimeoutMS": 20000
          }
        },

**Comment by vkarpov15** [comment]
Can you show me your full connection code?

**Comment by robpolak** [comment]
I actually think I just figured this out, not at bug at all, there was a race condition in my code that would cause mongoose.createConnection() to be called multiple times, thus, would caused the extra pools to be opened.

It might be a nice to throw a console warning for this scenario.. anyways this can be closed.
