### ISSUE TITLE
MongoDB 3.0 Auth Failed with SCRAM-SHA-1

### ISSUE THREAD

**Issue by Grievoushead** [Automattic/mongoose#3296]
I am using MongoDB 3.0 and I have created user via mongo shell, granted roles to db, but I can't connect  my app with mongoose. I am passing credentials in connection string, but it show ```MongoError: AuthFailed ```

I am able to connect with credentials using MongoChef.

I did research and seems like the problem with new SCRAM-SHA-1 auth schema, b/c everyone suggest to downgrade it to MONGODB-CR and recreate users.

**Comment by vkarpov15** [comment]
1. Which version of mongoose?
2. Are you sure you're authenticating against the database that the user is defined on?

**Comment by Grievoushead** [comment]
1. Mongoose v3.9.7
2. Yes, since I was able to connect with ChefMongo tool

**Comment by vkarpov15** [comment]
Please don't use mongoose 3.9.x. It's been deprecated in npm and should yell at you when you start the server. Either use 3.8.x or 4.x.

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this is still an issue.
