### ISSUE TITLE
If findOne query returns nothing throw an error

### ISSUE THREAD

**Issue by kevinsimper** [Automattic/mongoose#3298]
There should be a way to define that a query like `.findOne` should throw and error if there were not documents matching the query.

When using promises (bluebird) and mongoose, it would be nice to just expect that it is fufilled succesfully instead of having to make another check. It is a little bit against the way you would expect working with promises, when a query returns nothing, but does not throw and error.

Now:

``` js
User.findOne({_id: id}).then(function(user) {
  if(!user) {
    throw new Error('no user with that id')
  }
  // do something with user
  res.send(user
}).catch(function(err) {
  res.send({error: err})
})
```

Suggestion:

``` js
User.findOne({_id: id}, {explicit: true}).then(function(user) {
  // do something with user
  res.send(user
}).catch(function(err) {
  res.send({error: err})
})
```

This way you can always assume that is is defined.

**Comment by vkarpov15** [comment]
This would be trivial to implement as a plugin. I'm not inclined to add this to the core unless there's a lot of demand for it.

General idea for how the plugin would work (beware of bugs, haven't tested this at all)

```javascript
function plugin(schema) {
  schema.post('findOne', function(res, next) {
    if (!res) {
      return next(new Error('not found!'));
    }
    return next();
  });
}
```

**Comment by kevinsimper** [comment]
Okay, that is pretty cool!

I was creating it because I wanted to hear other people wanted it as well, but I will just create a plugin first :)

**Comment by vkarpov15** [comment]
Post the plugin when you write it, I'd love to see it. I'd probably use it, because on ES6 projects with co I often find myself writing `findByIdOrThrow` functions a lot :)

**Comment by web-mi** [comment]
I have a short question how i could handle a findMinOne without overriding the whole findOne.
Currently i'm using it like this which is working with the callback but its not working with the promise:
`schema.static('findMinOne', function (conditions, callback) {
      return this.find(conditions, function (err, data) {
         if (!data || data.length <= 0) {
            err = new Error('No docs found in schema "' + schema + '"!')
         }
         callback(err, data)
      })
   })`

It would be nice if we could do something like that:

`schema.static('findMinOne', function (conditions, callback) {
      return this.find(conditions, callback)
   })

   schema.post('findMinOne', function (data, next) {
      if (!data) {
         return next(new Error('No docs found in schema "' + schema + '"!'))
      }
      next()
   })`

Could you tell me how i could handle this?

**Comment by vkarpov15** [comment]
With promises:

```javascript
const assert = require('assert');

schema.static('findMinOne', function(conditions) {
  return this.find(conditions).then(res => assert.ok(res.length >= 1, 'No documents found'));
});
```

**Comment by web-mi** [comment]
Thanks for your reply!
But **then** will execute the query and will not return the promise so its not working like i wan't it.
I would use it like this:
```javascript
user
.findMinOne({
   'email': 'test@test.de' 
})
.populate('groups')
.exec(function (err, user) {
   // Here, where all other errors will came up, i will get the err if no user is found
}
´´´
Or did i missunderstood something?

**Comment by vkarpov15** [comment]
That's a very good point. We really need to add support for middleware for statics and methods, and the ability to set internal options on queries. Until we have support for either of these, please use the below. It's a little clunky but it gets the job done.

```javascript
async function run() {
  await mongoose.connect(connectionString);

  const schema = new Schema({ name: String });

  schema.static('findMinOne', function (conditions, callback) {
    var q = this.find();
    q.findMinOne = true;
    return q.find(conditions, callback);
  });

  schema.post('find', function(docs, next) {
    if (this.findMinOne === true && docs.length < 1) {
      return next(new Error('No docs found!'));
    }
    return next();
  });

  const M = mongoose.model('3298', schema);

  await M.find();

  // Will throw an error as expected
  await M.findMinOne();
}
```

**Comment by web-mi** [comment]
Thanks for your reply! 
This should do it for now as you post it. I will use this until the middleware issue is done.

**Comment by tgerk** [comment]
I wish I'd seen ```orFail``` much sooner:
```js
myModel.findById(theId).orFail( () => new Error('your document not found') )
    .catch( new myModel() )
    .then( lifeGoesOnFunction )
```

**Comment by vkarpov15** [comment]
@tgerk thanks for your comment. For posterity, here's the [docs for `orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail) in case someone else stumbles across this issue.
