### ISSUE TITLE
MongooseJS document Wierdness

### ISSUE THREAD

**Issue by iceNuts** [Automattic/mongoose#3300]
Hi there,

I am trying to do something like:

Item.photo = JSON.parse(Item.photo)

But it doesn't work, please help me out. Thanks.

**Comment by vkarpov15** [comment]
What does your schema look like?

**Comment by iceNuts** [comment]
something like:
`
var Schema = new Schema({
  // region
  region: { type: String }, // cn,us
  photo: {typse: String},
  errorMessage: { type: String },
  createdAt: { type : Date, default : Date.now }
});
`
And I want to update photo, I guess strict is on by default.

**Comment by vkarpov15** [comment]
Perhaps the fact that you misspelled "type" in `photo: {typse: String}`?

Also, for future reference, "it doesn't work" is not a valid bug report. Please be as explicit as possible, including code samples, stack traces, etc. where appropriate.
