### ISSUE TITLE
useDb() connection caching

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3302]
Make it so that calling `conn.useDb('abc');` twice will give you back the same connection rather than creating a new connection each time.

**Comment by xpepermint** [comment]
+10 :), this means I can clean up my code (deleting my own caching function)

**Comment by kheide** [comment]
Whats the status on this? I am fiddling with my own multi-tenant implementation and I am not doing any caching and my node instance seems to go fubar after 10-15 requests suddenly stopping to respond to requests until I restart node. I am thinking it might be a connection issue.

**Comment by kheide** [comment]
Btw @xpepermint would it be possible for your to share your caching function ?

**Comment by xpepermint** [comment]
@kheide after spending 2 days just reading about mongodb benchmarks, I decided not to use multiple databases (I have 10k users, each user has projects ...). The majority of speed tests suggest carefully setting indexes and splitting processing among multiple servers. But yeah... I had a working uncommited code which looked something like this:
```js
class Mongo {
  constructor() {
    this.conn = mongoose.createConnection(...);
    this.dbs = {};
  }

  use(name) {
    if (this.dbs[name]) {
      let db = this.conn.useDb(name);
      db.model('User', userSchema);
      ... register other models
      this.dbs[name] = db;
    }
    return this.dbs[name];
  }
  
  unuse(name) {
    if (this.dbs[name]) {
       this.dbs[name].close();
       delete this.dbs[name];
    }
  }
}
```

**Comment by rocketspacer** [comment]
@vkarpov15 How about I make the otherDbs a POJO and just share them between all connections?
https://github.com/Automattic/mongoose/blob/70b74f95d4439a5a14c757d36cdef660f65f257d/lib/drivers/node-mongodb-native/connection.js#L88-L89


Something like this:
```
this.otherDbs[newConn.name] = newConn;
newConn.otherDbs = this.otherDbs;
```

**Comment by rocketspacer** [comment]
Could add an option to maintain the default behaviour for backward compatibility

**Comment by vkarpov15** [comment]
@rocketspacer sounds reasonable, just add the option to maintain backwards compat

**Comment by vkarpov15** [comment]
There's now an option for this, see [`Connection#useDb()` and the `useCache` option](https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb)

**Comment by tomerzcod7** [comment]
Hey guys, a question on this subject (I might have a misunderstanding):

When I use useDb to create a new connection to a DB for the first time, I need to link all my models to that new connection right?

If I got my connection from the cache (already used this DB before), do I need to link my models to it again? and if not, how do I know if the connection was returned from cache or just created for the first time?

**Comment by vkarpov15** [comment]
@tomerzcod7 you would need to link your models to the new connection that `useDb()` returns. If the connection was cached, you don't need to link models again.

To check if the models were linked, you can check whether the returned connection actually has models.

```javascript
const db = connection.useDb('otherdb', { useCache: true });
if (Object.keys(db.models).length === 0) {
  // `db` has no models, so you need to decorate the db with models
}
```

**Comment by tomerzcod7** [comment]
@vkarpov15 Thanks
