### ISSUE TITLE
Unable to create new array field by $pushing object

### ISSUE THREAD

**Issue by lfk** [Automattic/mongoose#3305]
I'm attempting to create a new array field on my non-strict schema by `$push`ing an object to a non-existent field. As the sample below demonstrates, it works fine if the value being pushed is *not* an object, but in my case it fails silently, i.e. no error and with `nModified: 0`. If the array is already defined in the schema, the object push works fine.

```js
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var Schema = mongoose.Schema({}, { strict: false });
var Model  = mongoose.model('Model', Schema);

// This successfully creates the array `myArr` with someArr[0] = 'Value'
Model.create({}).then(function(m) {
    Model.update({ _id: m._id }, { '$push': { 'myArr': 'Value' } })
    .then(console.log, console.log);
});

// This, however, fails to create the array
Model.create({}).then(function(m) {
    Model.update({ _id: m._id }, { '$push': { 'myArr': { 'key': 'Value' } } })
    .then(console.log, console.log);
});


// With this, $pushing an object to `myArr` works fine, of course
//var Schema = mongoose.Schema({ 'myArr': [] });
```

FWIW, executing an equivalent "raw" query does yield the expected result.
`db.models.update({ _id: ObjectId("MYOBJID") }, { '$push': { 'myArr': { 'foo': 'Bar' } } })`

**Comment by vkarpov15** [comment]
I suspect this is related to #3265. Will double-check though.

**Comment by lfk** [comment]
Hello, and many thanks for the quick response time!

I pulled the master branch, checked that it contained the commit solving the referenced issue (b6ffdd7c499c8ab07de02d85d8220b4ab4b179b3), and re-ran my sample code. Interestingly the output is vaguely distinct -- I now get `{ ok: 0, n: 0, nModified: 0 }` from pushing the object, whereas before it was completely "silent". However, the result is still not the expected one.

**Comment by lfk** [comment]
Thank you @vkarpov15! Works great now.

**Comment by mphuc** [comment]
addasd
