### ISSUE TITLE
find with $gte return nothing

### ISSUE THREAD

**Issue by zwb-ict** [Automattic/mongoose#3306]
In mongo, I use ```db.pm2logs.find({"time": {$gte: new Date("2015-08-23T08:00:00")}})``` get return:

```
{ "_id" : ObjectId("55d97f76c3a4cffcd13dd883"), "level" : "err", "process" : { "pm_id" : 0, "name" : "test", "rev" : null }, "time" : [ 1440317300538, ISODate("2015-08-23T08:08:20.538Z") ], "body" : "xxx\n" }
{ "_id" : ObjectId("55d97f76c3a4cffcd13dd884"), "level" : "PM2", "process" : { "pm_id" : "PM2", "name" : "PM2", "rev" : null }, "time" : [ 1440317300541, ISODate("2015-08-23T08:08:20.541Z") ], "body" : "App name:test id:0 exited with code 255\n" }
{ "_id" : ObjectId("55d97f76c3a4cffcd13dd885"), "level" : "PM2", "process" : { "pm_id" : "PM2", "name" : "PM2", "rev" : null }, "time" : [ 1440317300543, ISODate("2015-08-23T08:08:20.543Z") ], "body" : "Starting execution sequence in -fork mode- for app name:test id:0\n" }
{ "_id" : ObjectId("55d97f76c3a4cffcd13dd886"), "level" : "PM2", "process" : { "pm_id" : "PM2", "name" : "PM2", "rev" : null }, "time" : [ 1440317300546, ISODate("2015-08-23T08:08:20.546Z") ], "body" : "App name:test id:0 online\n" }
```

but in js: 
```
this.body = yield  PM2Log.find({ "time": { $gte: new Date(startTime), $lte: new Date(endTime)}}).exec();
```
and test with:
```
curl http://localhost:3002/api/log\?startTime\="2015-07-23T07:00:00"\&endTime\="2015-08-23T08:00:00"
```
It return nothing.

I try
```
 this.body = yield  PM2Log.find().exec();
```
It can return all.

**Comment by zwb-ict** [comment]
This is mongd output:

2015-08-25T22:16:04.887+0800 I QUERY [conn583] query pm2-monitor.pm2logs query: { time: { $gte: "Thu Jul 23 2015 15:00:00 GMT+0800 (CST)", $lte: "Tue Aug 25 2015 22:16:04 GMT+0800 (CST)" } } planSummary: COLLSCAN ntoreturn:1000 ntoskip:0 nscanned:0 nscannedObjects:556860 keyUpdates:0 writeConflicts:0 numYields:4350 nreturned:0 reslen:20 locks:{ Global: { acquireCount: { r: 8702 } }, MMAPV1Journal: { acquireCount: { r: 4351 } }, Database: { acquireCount: { r: 4351 } }, Collection: { acquireCount: { R: 4351 } } } 404ms

**Comment by vkarpov15** [comment]
Can you enable mongoose debug mode, `require('mongoose').set('debug', true);`, and show me the console output? This will log all outgoing queries and writes to stdout.

**Comment by zwb-ict** [comment]
@vkarpov15, thank you for your help, I did as you told me, and this is the output: 

curl http://localhost:3002/api/log\?startTime\="2015-07-23T07:00:00"

Mongoose: pm2logs.find({ time: { '$gte': 'Thu Jul 23 2015 15:00:00 GMT+0800 (CST)', '$lte': 'Wed Aug 26 2015 22:32:35 GMT+0800 (CST)' } }) { fields: undefined }

**Comment by vkarpov15** [comment]
Hmm and what's your schema like? It looks like your times are sometimes numbers and sometimes dates in the database, but mongoose is casting the date to a string...

**Comment by zwb-ict** [comment]
@vkarpov15, this is my scheme:
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var pm2LogSchema = new Schema({
  level:  String,
  process: {
    pm_id: String,
    name: String,
    rev: String
  },
  time: { type: [String], index: true},
  body: String
}, { autoIndex: false });

var pm2log = mongoose.model('PM2log', pm2LogSchema);

exports = module.exports = pm2log;
```

Thank you.

**Comment by vkarpov15** [comment]
So in your database, your `time` array is either a date or a number, but since your schema says time is an array of strings, mongoose casts your query so that `time.$gte` is a string. Naturally, since your `time` values are numbers or dates, none of these will match. Fix your schema so that time's type is `[Date]`

**Comment by zwb-ict** [comment]
@vkarpov15, thank you for your help, I did as you told, it's OK now.
