### ISSUE TITLE
`populate` should respect `select`

### ISSUE THREAD

**Issue by Kuzmin** [Automattic/mongoose#3309]
Sometimes when I populate subdocuments, I want to remove certain fields for them. I do not think it's unreasonable to change the API so that it supports stuff like:

```
dogSchema = new Schema({
    name: String,
    toys: [String]
});

userSchema = new Schema({
    name: String,
    dog: ObjectId,
});

// somewhere else
user.find().populate('dog').select('-dog.toys');
```

To only retrieve the dogs names when populating subdocuments.

Do you think this is a reasonable feature to have? Would it be easy to implement in the current code? Currently taking a bit of a performance hit because of big nested subdocuments and it would be nice to not have to write my own wrapper to emulate `populate` with selected fields.

Thank you!

**Comment by Kuzmin** [comment]
I saw now that `populate` supports this as a second argument. I still think it would be neat to have `select` understand nested fields like described above, but this solution will work!

Feel free to close this

**Comment by vkarpov15** [comment]
This would be very difficult to support with dynamic refs unfortunately. I'll keep this open for now, if there's a lot of demand it's worth considering.
