### ISSUE TITLE
findOneAndUpdate doesn't return updated model

### ISSUE THREAD

**Issue by lifeisfoo** [Automattic/mongoose#3310]
`findOneAndUpdate` doesn't return updated model after a successful update (I've checked the db directly).

Example code:
```
Contact.findOneAndUpdate({_id: c_id}, contactData, function (err, contact) {
    if(err){
       res.status(400).send('Contact Error");
    } else{
      res.json(contact);
    }
  });
```

Usign mongoose 4.1.3, mongodb 2.4.8, express 4.13.3 and node 0.10.22.

**Comment by edwardysun** [comment]
You should specify the `{new: true}` option.

i.e.
```
Contact.findOneAndUpdate({_id: c_id}, contactData, {new: true}, function (err, contact) {
    if(err){
       res.status(400).send('Contact Error");
    } else{
      res.json(contact);
    }
  });
```

**Comment by lifeisfoo** [comment]
I've searched the docs and I've seen that was a 4.0 change.
Thank you for your help.
