### ISSUE TITLE
Reference nested schema for population

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3312]
Assume the following (simplified) schemas:

```javascript
var AddressSchema = new Schema({
  address: {
    type: String
  },
});

var PersonSchema = new Schema({
  name: {
    type: String
  },
  addresses: [AddressSchema]
});
```

This represents an person which can have multiple addresses, but the addresses are saved within the person document, not in a separate collection, yet each get their own _id.

Now consider an event schema linked to a specific host and with a specific location:

```javascript
var EventSchema = new Schema({
  host: {
    type: Schema.Types.ObjectId,
    ref: 'Person'
  },
  location: {
    type: Schema.Types.ObjectId,
    ref: '' //How to refer to Person.addresses?
  },
  title: {
    type: String
  }
});
```

How can I query the events and automatically populate the correct location?
In other words event.location should match an address from event.host.addresses.

Is this possible at all with Mongoose population, or do I have to populate the event.location field manually?

**Comment by vkarpov15** [comment]
Not really possible - since `AddressSchema` is embedded, it doesn't have its own model.

However, there is an alternative. [`.populate()` lets you do mongodb field selection](http://mongoosejs.com/docs/populate.html) so you can use the [`$elemMatch` operator](http://docs.mongodb.org/manual/reference/operator/projection/elemMatch/). Would look something like this.

```javascript
Event.findOne().populate('host', { addresses: { $elemMatch: { _id: '<insert _id here>' } } });
```

So `event.host.addresses` would contain only 1 element, the address with _id as provided.

**Comment by adambuczynski** [comment]
I don't like that workaround, because it breaks the desired document structure. I've tried to go with manual population instead, but there I also run into problems, see the issue I referenced above.

**Comment by vkarpov15** [comment]
You can always make `event.location` of type mixed to bypass all type checking altogether. And there's no way to bypass that check, it's pretty strictly enforced.

Strict enforcement of schemas works well in some cases but not so well in others. If you're committed to this document structure, just used `location: {}`

**Comment by adambuczynski** [comment]
Right, that works. Another way I found of bypassing this, is when I find the address, I simply convert it to a model of the right type (Address) before I attempt to set it to `event.location`.

E.g.:

```javascript
var event; //assume this is an instance of the Event model, where "host" has been populated.
var location = event.host.addresses.find(function(address) {
  if (event.location.equals(address._id)) {
    return true;
  }
});
location = new Address(location);
event.location = location; //this now works, if ref is "Address" in the event schema

**Comment by vkarpov15** [comment]
That works too, good idea.
