### ISSUE TITLE
Is it possible to reference another schema that may not be part of the code base?

### ISSUE THREAD

**Issue by Icehunter** [Automattic/mongoose#3314]
As an example I have X-Service which is specific to a certain schema. I will be running it on it's own box. I have another box with Y-Service and it also has it's own schema.

To alleviate issues if one API itself is overwhelmed, I need to keep them on different boxes but in Y it references the ID of X; and in X there is a reference to Z.

Is this even possible? If not is there a better solution to being able to pull in a document?

I was thinking of just making basic schema (strict: false) that only have ID in them so at least the collection names could be used. I couldn't find any documents on this though.

Thanks for all the great work!

**Comment by vkarpov15** [comment]
Population should be able to populate across dbs as long as you have separate models AFAIK...

**Comment by Icehunter** [comment]
@vkarpov15 What is those models live in separate projects and are separately hosted on different boxes? Technically I store the ID anyway; was just wondering the bare minimum I'd have to do to populate and get the data out without keep all models in all projects. If that's even possible.

**Comment by vkarpov15** [comment]
In theory, so long as you have a mongoose model pointing to the separate box. You don't even need to have the same schema if you're storing the schemas in different projects.

Here's the basic pseudo-code.

```javascript
var db = mongoose.createConnection('mongodb://my other box');
var model = db.model('ModelName', {} /* no schema */, 'collection name here');
MyOtherModel.populate('path', { model: model });
```

**Comment by Icehunter** [comment]
Ah! Thanks. I'll try playing around with schema-less schemas around that for reading. As long as I don't need to deep populate and it's just that first node; then I think that will suffice.

Very much appreciated!
