### ISSUE TITLE
After validation error, the callback seems to be catching errors somewhere.

### ISSUE THREAD

**Issue by aletorrado** [Automattic/mongoose#3316]
I'm writing a simple http web service, catching errors with NodeJS domains. It seems that Mongoose have a try-catch somewhere when calling the callback after saving with a validation error. A possible solution is to always call process.nextTick before calling the callback.

```
// THIS ALLOWS THE DOMAIN TO CATCH IT
db.MyModel.create({
	// BAD DATA
}, function(err){
	process.nextTick(function(){
		throw new Error()
	})
});

// THIS DOESN'T
db.MyModel.create({
	// BAD DATA
}, function(err){
	throw new Error()
});
```

Any idea?

**Comment by vkarpov15** [comment]
Dup of #3222 etc. Should be fixed with 4.1.4, re-open if this is still an issue :)
