### ISSUE TITLE
Sub document schema plugins don't execute anymore.

### ISSUE THREAD

**Issue by jrthib** [Automattic/mongoose#3318]
We're experiencing an issue where we have a plugin defined on one of our sub document schemas. Prior to upgrading to Mongoose 4.0, the plugin would successfully execute and define values onto the sub document before it was saved with the parent document. After upgrading, it seems as though the plugins defined on sub documents don't execute anymore.

This might be a bug in Mongoose 4.x

Thanks in advance for any help!

**Comment by vkarpov15** [comment]
Can you show me some code samples? Also, this may be related to #3284 and #3291, can you double check if your issue was fixed in 4.1.4?

**Comment by jrthib** [comment]
The code sample in #3284 is exactly what's happening, however we do the pre-save hook within a mongoose plugin on the `childSchema`. Does #3284 fix that if it is hooked within plugins?

**Comment by jrthib** [comment]
I just upgraded to 4.1.4, and confirmed the plugin method still doesn't seem to execute. Code example to follow:

**Comment by vkarpov15** [comment]
The below script executes without error for me on 4.1.5.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh3318');
mongoose.set('debug', true);

var L2calls = 0;
var L2Schema = new Schema({
  name: String
});

presavePlugin(L2Schema);

L1Schema = new Schema({
  items: [L2Schema]
});

var L = mongoose.model('test', L1Schema);
L.create({ items: [{ name: 'abc' }, { name: '123' }] }, function(error) {
  assert.ifError(error);
  assert.equal(L2calls, 2);
  process.exit(0);
});

function presavePlugin(schema) {
  L2Schema.pre('save', function(next) {
    ++L2calls;
    next();
  });
}
```

Make sure that you're calling the plugin **before** you nest the schema in another schema, modifying the schema after it's nested isn't really supported atm.

**Comment by vkarpov15** [comment]
Issue's gone stale and I can't repro. Re-open if this is still an issue.

**Comment by jrthib** [comment]
Ah, I forgot to follow up. After some deep digging, it turned out to be an issue with a particular plugin I was using. Thanks for looking into it!
