### ISSUE TITLE
Unique Index not working on Subdocuments

### ISSUE THREAD

**Issue by ivishwas-s** [Automattic/mongoose#3322]
Hi,

I'm trying to define unique (and sparse) index on subdocuments. Here's my schema:

```javascript
var model = {
    name: {type: String, required: true, unique: true},
    acronym: {type: String, required: true},
    accounting: {type: {
    pan: {type: String, required: false, unique: true, sparse: true},
    tin: {type: String, required: false, unique: true, sparse: true},
    tan: {type: String, required: false, unique: true, sparse: true},
    serviceTax: {type: String, required: false, unique: true, sparse: true},
    cst: {type: String, required: false, unique: true, sparse: true},
    iec: {type: String, required: false, unique: true, sparse: true},
    cin: {type: String, required: false, unique: true, sparse: true},
    vat: {type: String, required: false, unique: true, sparse: true},
    excises: {type: [excise], required: false}
}, required: false},
    bankAccounts: {type: [{
    name: {type: String, required: true},
    branch: {type: String, required: false},
    accountType: {type: String, required: false, default: 'Current'},
    accountNumber: {type: String, required: true, unique: true, sparse: true},
    swiftCode: {type: String, required: false},
    ifscCode: {type: String, required: false}
}], required: false}
};
```

Let me divide this into different scenarios I tried creating an index on a subdocument

**Case 1**: (Accounting is just a subdocument, BankAccounts is an array of subdocuments)

Unique index is being created on "bankAccounts.accountNumber" (bankAccounts being an array) field but not on "accounting.pan" (or any other fields under accounting). Duplicate inserts are allowed on the accounting subdocument

**Case 2**: (Accounting is an array of subdocuments, BankAccounts is an array of subdocuments)

Unique index is being created on all the fields of "accounting" subdocument and of course the "bankAccounts.accountNumber" field. (But for obvious reasons, I can't have an array of the accounting subdocument). Duplicate inserts are not allowed on the accounting subdocument

**Case 3**: (Create index manually in mongo)

If I create an index manually in mongo for "accounting" subdocument fields, everything works as expected, i.e. no duplicates are allowed!!

I'm not sure if this is a bug in mongoose (version being used is 4.1.3) or the expected behaviour.

Please help!!

Regards,
Vishwas

**Comment by vkarpov15** [comment]
The issue is the `accounting.type` path. Mongoose doesn't currently support single-embedded schemas (see #2689 to track) so your schema below:

```javascript
var model = {
  name: {type: String, required: true, unique: true},
  acronym: {type: String, required: true},
  accounting: {
    type: {
      pan: {type: String, required: false, unique: true, sparse: true},
      tin: {type: String, required: false, unique: true, sparse: true},
      tan: {type: String, required: false, unique: true, sparse: true},
      serviceTax: {type: String, required: false, unique: true, sparse: true},
      cst: {type: String, required: false, unique: true, sparse: true},
      iec: {type: String, required: false, unique: true, sparse: true},
      cin: {type: String, required: false, unique: true, sparse: true},
      vat: {type: String, required: false, unique: true, sparse: true},
      excises: {type: [excise], required: false}
    },
    required: false
  },
  bankAccounts: {
    type: [{
      name: {type: String, required: true},
      branch: {type: String, required: false},
      accountType: {type: String, required: false, default: 'Current'},
      accountNumber: {type: String, required: true, unique: true, sparse: true},
      swiftCode: {type: String, required: false},
      ifscCode: {type: String, required: false}
    }],
    required: false
  }
};
```

is actually equivalent to:

```javascript
var model = {
  name: {type: String, required: true, unique: true},
  acronym: {type: String, required: true},
  accounting: {
    type: mongoose.Schema.Types.Mixed,
    required: false
  },
  bankAccounts: {
    type: [{
      name: {type: String, required: true},
      branch: {type: String, required: false},
      accountType: {type: String, required: false, default: 'Current'},
      accountNumber: {type: String, required: true, unique: true, sparse: true},
      swiftCode: {type: String, required: false},
      ifscCode: {type: String, required: false}
    }],
    required: false
  }
};
```

because when `type` is a POJO, mongoose ignores all sub-fields and just assumes you mean [mixed type](http://mongoosejs.com/docs/schematypes.html#mixed). Get rid of `type` or use `kind` instead, and everything should work :)

**Comment by kevinresol** [comment]
Sometimes the "type" field is no avoidable such as in [GeoJson](http://geojson.org/) which is required for a 2d index. Are there any fixes for this?

**Comment by vkarpov15** [comment]
Mongoose `~4.2.2` supports [configuring the 'type' key for a given schema](http://mongoosejs.com/docs/guide.html#typeKey) for precisely this reason. The below should work.

```javascript
new Schema({
    origin: {
        type: {
            coordinates: {
                $type: [Number]
            },
            type: {
                $type: String
            }
        }
    }
}, { typeKey: '$type' });
```

**Comment by kevinresol** [comment]
Thanks! But should the type right after origin has the dollar sign too?

**Comment by vkarpov15** [comment]
No, the above schema says "origin is an object with a single key called "type". "type" is ab object with two keys, an array called "coordinates" and a string called "type".

**Comment by kevinresol** [comment]
```js
new Schema({  
   origin:{  
      $type:{  
         coordinates:{  
            $type:[Number]
         },
         type:{  
            $type:String
         }
      },
      index:"2dsphere"
   }
}, { typeKey: '$type' });
```

If I am going to have an `origin` object with 2 keys (`coordinates` and `type`) plus one index. Is the above syntax correct?

**Comment by maickBarreto** [comment]
a simple resolution:

`
var model = {
    name: {type: String, required: true, unique: true},
    acronym: {type: String, required: true},
    accounting: {
      type: new mongoose.Schema({
         pan: {
            type: String, 
            required: false, 
            sparse: true,
            index:{
               unique: true
            }
         }
       }, {_id: false})
   }
`
