### ISSUE TITLE
Add support for cursor.min() and cursor.max()

### ISSUE THREAD

**Issue by ovaris** [Automattic/mongoose#3329]
It would be great to have Mongoose Query (or cursor) to support for `cursor.min()` `cursor.max()` for limiting results of .find() function.

See http://docs.mongodb.org/manual/reference/method/cursor.min/#cursor.min
http://docs.mongodb.org/manual/reference/method/cursor.max/#cursor.max

**Comment by jamesjieye** [comment]
+1

**Comment by vkarpov15** [comment]
Actually this should be already supported, `MyModel.find({}, null, { min: 5, max: 10 });` looks like it works for me...

**Comment by vkarpov15** [comment]
Issue's stale, re-open if this is still an issue.

**Comment by Bleoo** [comment]
Your codes not work for me, the min document is not included in the result set.

MongoDB Example:
Using the ordering of the { item: 1, type: 1 } index, min() limits the query to the documents that are at or above the index key bound of item equal to apple and type equal to jonagold, as in the following:

db.products.find().min( { item: 'apple', type: 'jonagold' } ).hint( { item: 1, type: 1 } )
The query returns the following documents:

{ "_id" : 3, "item" : "apple", "type" : "jonagold", "price" : 1.29 } this included in the result set
{ "_id" : 4, "item" : "apple", "type" : "jonathan", "price" : 1.29 }
{ "_id" : 5, "item" : "apple", "type" : "mcintosh", "price" : 1.29 }

See [https://docs.mongodb.com/v3.6/reference/method/cursor.min/#example](https://docs.mongodb.com/v3.6/reference/method/cursor.min/#example)
