### ISSUE TITLE
turn off auto-creating index paths from embedded documents

### ISSUE THREAD

**Issue by pyramation** [Automattic/mongoose#3334]
Seems like mongoose is auto generating indexes for embedded documents.

Is there an option to turn off the auto-magical indexes that are created? For example the code [https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L940] seems to `collectIndexes` from any subdocuments.

Am I missing something or is there a way to disable this and be explicit about which subdocuments need indexing? We require this, because we are hitting the limit of **64** total indexes per collection limit, which is enforced by MongoDB.

**Comment by vkarpov15** [comment]
Do you want to shut off just those specific indexes or shut off mongoose index creation? `require('mongoose').connect('myUri', { config: { autoIndex: false } });` will shut off automatic index creation for all models that you create with `mongoose.model()`.

**Comment by pyramation** [comment]
I actually want to shut off those specific indexes, creation is fine. My workaround right now:

```
        schema.indexes = function () {
            return schema._indexes;
        };
```

**Comment by vkarpov15** [comment]
I think it's just creating indexes for the `_id` field, no? You can shut off the `_id` field in document arrays by setting [the `_id` schema option to `false`](http://mongoosejs.com/docs/guide.html#_id)

**Comment by pyramation** [comment]
If you create indexes on model `Child` and embed in `Parent`, all the indexes created on `Child` will be added to `Parent` based on the path names for the embeds. You can see in the `collectIndexes` method inside of the `indexes` method: https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L946-L987

**Comment by vkarpov15** [comment]
Yep that's by design, I don't think there's any way to shut that off atm other than not putting indexes on `Child` in the first place.
