### ISSUE TITLE
Cross DB Relationships?

### ISSUE THREAD

**Issue by resistdesign** [Automattic/mongoose#3339]
If I...
1. Use `Mongoose.createConnection()` and open 2 DBs
2. Make model `A` from DB 1 (i.e. `db1.model('A', new Schema({...}))`)
3. Make model `B` from DB 2 with a Schema that has a relational ref for model `A` (i.e. `db2.model('B', new Schema({name: String, sub: {type: ObjectId, ref: 'A'}}))`)
4. Save a new object of type `B` with a sub-object of type `A`

What happens?

**Comment by vkarpov15** [comment]
Won't work as written, because there's no model in `db2` with name 'A'. However, if you do `B.find().populate({ path: 'sub', model: A });` it should work. Note that you're using the model `A` explicitly, not referencing it by name.

**Comment by resistdesign** [comment]
Ok, very cool, thank you :)
