### ISSUE TITLE
findOneAndUpdate not returning new entry (returns all docs)

### ISSUE THREAD

**Issue by fredp613** [Automattic/mongoose#3343]
Mongo's findAndModify allows for getting the newly created document provided the "upsert" option is set to "true".  For some reason (maybe i'm wrong), but the doc return by Mongoose's findOneAndUpdate() method returns all docs queries (which is fine in some cases) but there is no way to get the "inserted" doc if the query returns no value.

**Comment by vkarpov15** [comment]
What do you mean by "returns all docs queries"?

**Comment by fredp613** [comment]
Returns all docs from the query so if I'm passing the user model for example with a token parameter to filter the users, if I have say 4 results and an unfound result, using the upsert bool option will create the unfound result but there is no way for me to access just the newly created doc inside the callback function. Instead it will return the 5 docs including the inserted one

**Comment by fredp613** [comment]
It would be great if for example, i could add an arg to the callback function like newDoc so that I could access it within the callback function for further processing

**Comment by vkarpov15** [comment]
That's odd, I'm pretty sure there's no way for findOneAndUpdate to return multiple docs. Can you show some code samples? I don't quite understand what your issue is

**Comment by fredp613** [comment]
Yes sorry I meant it returns the found doc or the newly created doc. So one doc. However in the call back when accessing doc it will return the doc wether it was newly created or simply found therefore, unless I'm wrong, there is currently No way to distinguish the newly created doc which can be done with findandmodify using mongo. Currently I resorted to using findOne because if not found I can save the object but I find that's a bit more unnecessary overhead. I would prefer to use atomic operations.

**Comment by fredp613** [comment]
Here is an illustration of the issue:
var update = {$set: message.toObject()}
var options = { upsert: true, 'new': true  }

Message.findOneAndUpdate(query,update,options,function(err, doc) {
   if (!doc) {
      /**Send push notification - this won't work in this case because if I do find a doc that matches my query criteria, the doc is returned and there is no way inside this block (aside from performing another query) to know that the doc is newly inserted)**/
   }
});

It would be nice if I could do:
"" = optional arg
Message.findOneAndUpdate(query,update,options,function(err, doc, "upsertDoc") {
   if (upsert) {
      //send push notification
   }
});

**Comment by vkarpov15** [comment]
You have 2 options.

1. set `options.new` to `false`, then `doc` will always be null if there was an upsert.
2. set `options.passRawResult` to true, then your cb signature will look like:

```
function(error, doc, res) {
  // If `passRawResult` is true, `res.lastErrorObject.updateExisting` will be false iff there was an upsert
}
```
