### ISSUE TITLE
findById promise has different behaviour if there is a callback function

### ISSUE THREAD

**Issue by landru29** [Automattic/mongoose#3344]
If I invoke findById like this, I get an object in the resolution of the promise
```
User.findById(
    '55eae90a337edf5319b25861'
).then(function(user){
	  console.log(user); // user is an object
    }
);
```
But if I invoke findById with a callback function, I get an array in the resolution of the promise
```
User.findById(
    '55eae90a337edf5319b25861', 
    function(){}
).then(function(user){
        console.log(user); // user is an array
    }
);
```

The promise should always resolve an object.

**Comment by vkarpov15** [comment]
This is indicative of a minor issue which was fixed in 55d2384.

The bigger problem, though, is that you absolutely should not specify both a callback and call `.then()` on a query. This will execute the query twice by design.
