### ISSUE TITLE
Feature Request: Allow Unique in Array Schema Definition

### ISSUE THREAD

**Issue by ccravens** [Automattic/mongoose#3347]
The following page states currently supported Schema types: http://mongoosejs.com/docs/schematypes.html

One feature that would be nice is for Mongoose to enforce uniqueness in Arrays, which could guarantee unique values in an array in Mongoose, like the $addToSet functionality in the Mongo database query language.
## Current Issue

I can only define an array to hold a list of values, which allows multiple instances of the same value. The following code example demonstrates the issue.

var schema = mongoose.Schema({
  friends : [{type : mongoose.Schema.Types.ObjectId, ref : 'User' }]
})

model = new mongoose.model('User')

model['friends'].push(ObjectId('12345'))
model['friends'].push(ObjectId('12345'))

model.save()

Mongo document now looks like:
{friends:[ObjectId('12345'),ObjectId('12345')]}
## Suggested Fix

Enhance the schema model to allow unique attribute for an array, which internally uses the Set() object in Mongoose. Then once save() is called, mongoose will convert the set to an array and use the "$addToSet" mongodb operator that will ensure values are unique in the array. Something like the following code snippet would be desired:

var schema = mongoose.Schema({
  friends : [{type : mongoose.Schema.Types.ObjectId, ref : 'User', unique: true }]
})
model = new mongoose.model('User')

model['friends'].push(ObjectId('12345'))
model['friends'].push(ObjectId('12345'))

model.save()

Mongo document now looks like:
{friends:[ObjectId('12345')]}
## Current Method

Currently it is being suggested to create a seperate update() function with the "$addToSet" parameter, which seems to be more work and burden on the developer than it should be. Please refer to the following:

https://groups.google.com/forum/#!topic/mongoose-orm/QSpr_7rtEYY
http://stackoverflow.com/questions/15921700/mongoose-unique-values-in-nested-array-of-objects

**Comment by filfat** [comment]
+1

**Comment by BlueAccords** [comment]
+1  
Also, just wondering but how difficult would it be to implement this?

**Comment by vkarpov15** [comment]
Pretty difficult actually, mongoose would have to do a lot to make this work, because `$addToSet` doesn't work well with document arrays. For example, there is no good way to, say, `$addToSet` a user object to an array called `users` while enforcing that the `username` property should be unique. This would make the API a bit unwieldy, because `unique` would only work as expected for regular arrays, but not work right for document arrays.

**Comment by yonib05** [comment]
+1 
I can imagine it would be a bit complex and inefficient on the querying side but it still would be nice to have.

**Comment by vlaad360** [comment]
+1
It would be very nice to do it

**Comment by forl** [comment]
+1
Nice feature to have!

**Comment by ianmin2** [comment]
### +1

 That'd be really awesome.
 Somebody please add it.

**Comment by amit3vr** [comment]
+1

**Comment by faizalpribadi** [comment]
+1

**Comment by maximilianschmid** [comment]
+1

**Comment by nubitech** [comment]
+1

**Comment by klaaz0r** [comment]
+1

**Comment by fauria** [comment]
+1

**Comment by scombat** [comment]
+1

**Comment by toymachiner62** [comment]
👍

**Comment by strafe89** [comment]
+1

**Comment by 0xc00010ff** [comment]
bump! ✊

**Comment by antonsamarsky** [comment]
+1

**Comment by geekiam** [comment]
+1

**Comment by nitindhar7** [comment]
+1

**Comment by raphaklaus** [comment]
+1

**Comment by bshikhar13** [comment]
+1

**Comment by djekoff** [comment]
+1

**Comment by Sonivaibhav26** [comment]
+1

**Comment by jpetitte** [comment]
+1

**Comment by raghav130593** [comment]
+1

**Comment by robertleeplummerjr** [comment]
+1

**Comment by Trenrod** [comment]
+1

**Comment by pashoo2** [comment]
+1

**Comment by januszhou** [comment]
+1

**Comment by andrewstec** [comment]
+1

**Comment by vkarpov15** [comment]
Use the [mongoose-unique-array plugin](https://github.com/Automattic/mongoose/blob/master/History.md#4100--2017-05-18) and mongoose 4.10 for this behavior

**Comment by vkarpov15** [comment]
Check out http://thecodebarbarian.com/whats-new-in-mongoose-4.10-unique-in-arrays.html if you're eager to get started :+1:

**Comment by Pei116** [comment]
Does that plugin work with `Document.findByIdAndUpdate()`?

**Comment by vkarpov15** [comment]
@Pei116 no unfortunately it only works for `save()` right now
