### ISSUE TITLE
How to set reasonable poolsize?

### ISSUE THREAD

**Issue by zwb-ict** [Automattic/mongoose#3350]
I enable keepalive with mongo, now I have doubts about how to set poolsize reasonablly, I searched google, but not found a good answer, would you please give me a hand? Thank you.

**Comment by vkarpov15** [comment]
Recommend setting it in your connection string:

```javascript
var db = require('mongoose').createConnection('mongodb://localhost:27017/test?poolSize=25');
```

**Comment by zwb-ict** [comment]
@vkarpov15  Thank you very much!
