### ISSUE TITLE
Silently failing queries when schema does not correspond to database document

### ISSUE THREAD

**Issue by albertorestifo** [Automattic/mongoose#3352]
I'm making the following query in mongoose:

```js
Schedule.find({
    'operative.from': { $lte: '2015-09-07T00:00:25+00:00' },
    'operative.to': { $gte: '2015-09-07T23:59:25+00:00' },
    'operative.weekdays': { $in: [ 1 ] } })
    .exec()
    .then(function () { … })
```

It returns no results. What confuses me is that if I run the exact same query on the Mongo Shell, it returns ~200 results as expected.

I've tried removing the conditions until it returned some results, and what's confusing mongoose are the two dates queries.

The relevant schema for those fields is the following:

```js
operative: {
   from: Date,
   to: Date,

   // weekdayds the flight is operated, Sunday = 0
   weekdays: []
 }
```

I've also ensured that the queries without date conditions return the expected results, and they do. The only possible thing I did differently is that I've inserted the data I'm querying using a bulk operation via the native driver.

Any ideas what might cause this?

**Comment by albertorestifo** [comment]
Ok I found the issue:

This what how I specified a path in the schema:

```js
aircraft: {
  type: String,
  owner: String
}
```

Obviously, the reserved word `type` was causing a validation error on the document. I fixed it by correcting it to `type: { type: String }`. All clear there.

I however want to keep the issue open: I inserted the documents skipping Mongoose validation for performance limitations.

I believe a schema validation error should not silently fail your queries. Some kind of error should be propagated, something along the lines:

> Schema not corresponding to documents in the collection for path …

**Comment by vkarpov15** [comment]
That's what `strict: 'throw'` is for: http://mongoosejs.com/docs/guide.html#strict. Otherwise mongoose silently filters out fields that don't match the query by design.

**Comment by albertorestifo** [comment]
Totally missed that option, thank you very much for the info

**Comment by albertorestifo** [comment]
@vkarpov15 Although, it's strange that this error in the schema was causing the date queries to return no result, even when the definition of those paths was correct, but other queries (excluding those to the miss-declared path) returned the appropriate results.

**Comment by vkarpov15** [comment]
That's odd. Where the date fields nested under another path that was mistakenly using `type`? Can you show me more of the schema?

**Comment by albertorestifo** [comment]
I think that was the only issue with the schema.

Here it is how it was before the fix:

```js
new mongoose.Schema({

  // Two letter iata of the operator (LX, WK)
  operatorIATA: { type: String, uppercase: true },

  // Flight number (8061)
  number: Number,

  callsign: String,

  departure: {
    airport: String,
    time: String, // `HH:mm` format
  },

  destination: {
    airport: String,
    time: String, // HH:mm
  },

  operative: {
    from: Date,
    to: Date,

    // weekdayds the flight is operated, Sunday = 0
    weekdays: []
  },

  aircraft: {
    // ICAO of the aircraft type used
    type: String,

    // Ailine owner of the plane, IATA code
    owner: String
  },

  // name of the cycle used to compute this entry, example: W030
  cycle: String,

  // When archived, mark as true
  archive: { type: Boolean, default: false }

}, {
  collection: 'schedule'
})
```

This is what I did in details:

- Call the native driver to make a bulk operation to populate the database
- Query for both a dare range and week number - 0 results
- Query for only a week number - Correct number of results
- Drop the database, repopulated it using the Mongoose `create` method
- Found out about the schema error
- Repopulated the database
- Works

**Comment by vkarpov15** [comment]
Yeah the only query that should fail there would be for `aircraft.owner`. The thing is, Mongoose's `create()` function refuses to create a document that has a cast error, so if you were creating documents with `{ aircraft: { type: 'abc', owner: '123' } }`, `.create()` would return an error in the callback and no docs would get created, so that might explain why you were getting no results.
