### ISSUE TITLE
node won't exit after disconnect on replset

### ISSUE THREAD

**Issue by bobzoller** [Automattic/mongoose#3358]
Node (tried 0.10.33, 0.10.36, 0.10.40, 0.12.7), mongoose (tried 4.0.2, 4.1.5), mongodb (tried 3.6.4, 3.6.11)

With `MONGO_URL=mongodb://u:p@h1:p1,h2:p2/db?replicaSet=rs`, after calling disconnect in the code below, the callback is called, but the process _almost never_ exits.

If I only specify one seed host (doesn't matter which), the process _exits cleanly every time_.

Does this ring bells or make any sense to anyone?

```
var mongoose = require('mongoose');

mongoose.connect(process.env.MONGO_URL, function(err) {
  if (err) throw err;
  console.log('connected');
  mongoose.disconnect(function(err) {
    if (err) throw err;
    console.log('disconnected');
  });
});
```

**Comment by vkarpov15** [comment]
Even with auto_reconnect off? #866

**Comment by bobzoller** [comment]
I tried setting auto_reconnect off, did not fix.
I also tried directly calling the driver's connection.close method with the `forceClose` option as suggested in #866, did not fix.

```
var mongoose = require('mongoose');

mongoose.connect(process.env.MONGO_URL, {autoReconnect: false}, function(err) {
  if (err) throw err;
  console.log('connected');
  setTimeout(function() {
    mongoose.disconnect(function(err) {
      if (err) throw err;
      console.log('disconnected');
    });
  }, 1000);
});
```

```
var mongoose = require('mongoose');

mongoose.connect(process.env.MONGO_URL, {autoReconnect: false}, function(err) {
  if (err) throw err;
  console.log('connected');
  setTimeout(function() {
    mongoose.connection.db.close(true, function(err) {
      if (err) throw err;
      mongoose.connection.onClose();
      console.log('disconnected');
    });
  }, 1000);
});
```

**Comment by vkarpov15** [comment]
Which version of mongoose are you using? On 4.1.7 the second script exits about 5 seconds after the 'disconnected' message happens, at least a 3-node replica set running 2.6.10 on my laptop.

**Comment by vkarpov15** [comment]
Issue's stale. Re-open if this is still an issue.

**Comment by yelworc** [comment]
I'm currently seeing this issue with a MongoDB 2.6.9 replica set on Mongolab, with mongoose v4.1.8 in production. Testing with v4.2.5 locally shows the same behavior. The code snippets by @bobzoller above don't exit for me, either.
Let me know if there is anything I can do to help debug; I have not tried reproducing it with a MongoDB 2.6.9 replica set locally yet.

(FWIW: Node v4 on Debian Jessie (locally) and Heroku)

**Comment by vkarpov15** [comment]
That's odd, I still can't repro. Running below script with node v4 and mongoose 4.2.5 against mongodb 2.6.10 on xubuntu:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://conan:27000,conan:27001,conan:27002/gh3358', {autoReconnect: false}, function(err) {
  if (err) throw err;
  console.log('connected');
  setTimeout(function() {
    mongoose.connection.db.close(true, function(err) {
      if (err) throw err;
      mongoose.connection.onClose();
      console.log('disconnected');
    });
  }, 1000);
});
```

gives me:

```
$ node -v
v4.0.0
$ time node gh-3358.js 
connected
disconnected

real	0m10.396s
user	0m0.430s
sys	0m0.017s
```

Here's my `rs.status()`:

```
mongoose26:PRIMARY> rs.status()
{
	"set" : "mongoose26",
	"date" : ISODate("2015-11-12T19:56:21Z"),
	"myState" : 1,
	"members" : [
		{
			"_id" : 0,
			"name" : "HOSTNAME:27000",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 64,
			"optime" : Timestamp(1447358134, 1),
			"optimeDate" : ISODate("2015-11-12T19:55:34Z"),
			"electionTime" : Timestamp(1447358118, 1),
			"electionDate" : ISODate("2015-11-12T19:55:18Z"),
			"self" : true
		},
		{
			"_id" : 1,
			"name" : "HOSTNAME:27001",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 50,
			"optime" : Timestamp(1447358134, 1),
			"optimeDate" : ISODate("2015-11-12T19:55:34Z"),
			"lastHeartbeat" : ISODate("2015-11-12T19:56:21Z"),
			"lastHeartbeatRecv" : ISODate("2015-11-12T19:56:19Z"),
			"pingMs" : 0,
			"syncingTo" : "HOSTNAME:27000"
		},
		{
			"_id" : 2,
			"name" : "HOSTNAME:27002",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 47,
			"optime" : Timestamp(1447358134, 1),
			"optimeDate" : ISODate("2015-11-12T19:55:34Z"),
			"lastHeartbeat" : ISODate("2015-11-12T19:56:20Z"),
			"lastHeartbeatRecv" : ISODate("2015-11-12T19:56:20Z"),
			"pingMs" : 0,
			"syncingTo" : "HOSTNAME:27000"
		}
	],
	"ok" : 1
}
```

Might be helpful if you could see if you can reproduce this issue on an AWS machine @yelworc , so I can spawn up the same instance and debug... In the meantime, you can always just explicitly `process.exit(0);`

**Comment by yelworc** [comment]
Thanks for the feedback! So the differences I can spot are:
* MongoDB v2.6.9 vs 2.6.10
* locally installed vs remote MongoDB
* my connect string includes access credentials and a `?replicaSet=...` parameter (like the one given by @bobzoller in the first post)

Neither of those seems likely to be the cause, though.
`process.exit` would work, but I've learnt the hard way to avoid that like the plague, so for now I chose to just connect to a single server of the replica set instead, temporarily.

I have to admit I don't have any experience working with AWS machines directly, only through intermediaries such as Heroku or Mongolab. I'll try if I get a chance, but any pointers to resources, tutorials etc. on getting this running on an AWS machine quickly would be much appreciated.

**Comment by vkarpov15** [comment]
I really don't see anything in the [2.6.10 release notes](https://jira.mongodb.org/browse/SERVER-18364?jql=fixVersion%20%3D%20%222.6.10%22%20AND%20project%20%3D%20SERVER) that would cause this difference.

The auth difference might be important though. Can you show me the general form of your connection string with hostnames and usernames/passwords X-ed out?

AWS machines are pretty much indistinguishable from real servers (performance aside), you just SSH in, download whatever you want, and run whatever you want.

**Comment by yelworc** [comment]
Sure. Seeing the issue with this connect string:
```
mongodb://<user>:<password>@ds012345-a0.mongolab.com:<port>,ds012345-a1.mongolab.com:<port>/<dbname>?replicaSet=rs-ds012345
```
But not with this one:
```
mongodb://<user>:<password>@ds012345-a0.mongolab.com:<port>/<dbname>
```

**Comment by bobzoller** [comment]
Same format connection strings for me -- I also have `&ssl=true `.
Hopefully a red herring, but I'm also using MongoLab.

**Comment by thstarshine** [comment]
+1

Using Node 0.12.7, mongo 2.6.11.
My program cannot terminate successfully with mongoose 4.1.3+.
(OK with 4.1.3)

**Comment by vkarpov15** [comment]
@yelworc don't use the second form, that will actually open up a standalone connection...

**Comment by vkarpov15** [comment]
Still no dice, even with auth and SSL enabled against a local mongod. I also tried setting up a mongolab account and it exits just fine as well, although mongolab shouldn't make any difference. @bobzoller @thstarshine what OS?

Also, once again, I'd recommend just using `process.exit(0);` if you really need to shut down the process.

**Comment by yelworc** [comment]
Thanks for looking into it! I'll see if I can find some time to try to reproduce it in an AWS instance.

What exactly do you mean by "standalone connection"? I am aware that I'm losing the automatic failover feature when connecting to a single server – is there something else that is passing me by?

**Comment by vkarpov15** [comment]
Connecting to a single mongodb instance is different than connecting to a replica set. Unless you specify multiple hostnames or the "?replicaSet=<rsname>" option, mongoose will think it's connecting to a single mongodb instance, and won't connect to the other members of the replica set.

**Comment by thstarshine** [comment]
@vkarpov15 I'm working under Ubuntu 14.04.

**Comment by vinnie-pepi** [comment]
I'm seeing the same problem with the node mongodb driver. Just stumbled onto this thread looking for an explanation as to why the process won't exit.

**Comment by vkarpov15** [comment]
@thstarshine probably isn't OS-specific then, I'm running xubuntu 14.04, and the different windowing system shouldn't affect mongoose. Are you running in AWS? Also, are you using mongolab?

**Comment by vkarpov15** [comment]
I'm gonna remove this from the milestone because I haven't been able to reproduce this. If anybody can provide any insight on how to repro this on AWS that would be very helpful. Until then, this is a relatively minor issue that can always be ameliorated with `process.exit()`.

**Comment by alexsk** [comment]
@vkarpov15 the issue is reproducible for me when something is wrong with the mongo itself (e.g. it's not running from the start, or dies somewhere).

Here is a small example trying to connect to irrelevant port:

**Mongo driver example**:
```
var MongoClient = require('mongodb').MongoClient;

MongoClient.connect('mongodb://localhost:12345/test', function(err, db) {
    if (err) {
        console.log(err);
    } else {
        console.log(err || "Connected correctly to server");
        db.close();
    }
});
```
Works perfectly:
```
$ node mongo-test.js 
{ [MongoError: connect ECONNREFUSED 127.0.0.1:12345]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:12345' }
$
```
Error is logged and the process exists.

**And mongoose example**:
```
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:12345/test', {autoReconnect: false}, function(err) {
    console.log(err || 'connected');
    setTimeout(function() {
        mongoose.connection.db.close(true, function(err) {
            if (err) throw err;
            mongoose.connection.onClose();
            console.log('disconnected');
        });
    }, 1000);
});
```
The process can't exit even after all close calls:
```
$ node mongoose-test.js 
{ [MongoError: connect ECONNREFUSED 127.0.0.1:12345]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:12345' }
disconnected
^C
$
```

**Comment by vkarpov15** [comment]
@alexsk you need to specify `autoReconnect` as a server option:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:12345/test', {server:{autoReconnect: false}}, function(err) {
    console.log(err || 'connected');
    mongoose.connection.close(function(err) {
      console.log('err', err);
    });
});
```
