### ISSUE TITLE
validate function triggers 'Cast to ObjectID failed for '''

### ISSUE THREAD

**Issue by awdogsgo2heaven** [Automattic/mongoose#3359]
If you call the validate function on a model directly, and you have an ObjectID field, set to required false, then it will attempt to cast an empty string (that seemingly comes from no where) and fail. I even tried inserting nulls, and it still tried to cast an empty string to ObjectID, this is from the lastest release from NPM.

notes:

Adding 'ref' makes this issue go away (but this isn't suitable in my case, as the ID is pointing to a non model type, an ID in an embedded array). Also, my Object id field, is embedded if that counts for something.

**Comment by vkarpov15** [comment]
Can you show me a code sample? Translating prose to code is error-prone.
