### ISSUE TITLE
Segmentation fault with node v4

### ISSUE THREAD

**Issue by jkresner** [Automattic/mongoose#3361]
I'm not 100% sure, will update again shortly, but I'm seeing Seg faults when I require mongoose.

**Comment by jkresner** [comment]
MMmmm... it is crashing when I hit mongoose in my main app, but in a separate one I just created with a single file, seems ok.

**Comment by jkresner** [comment]
Ok - blowing away my node_modules folder and doing a fresh npm install (after upgrading node and npm) seemed to do the trick!

**Comment by jkresner** [comment]
Note, I had already updated mongoose to 4.1.6 and it wasn't working, so there must have been some dependency somewhere.

**Comment by vkarpov15** [comment]
Yeah when you upgrade node versions, make sure you clear out your node_modules and re-run `npm install` unless you're 100% sure there's no native add-ons that need to get re-compiled. In mongoose's case, there's a native extension via the mongodb driver. If there's still a segfault, that's probably a bug.
