### ISSUE TITLE
Not work ObjectId.isValid function

### ISSUE THREAD

**Issue by inthedark122** [Automattic/mongoose#3363]
When I check valid ObjectId
```
> console.log(mongoose.Types.ObjectId.isValid('test@mail.ru'));
true
```
I get result true. But if I execute this query then I have error.
Why is this happening?

**Comment by inthedark122** [comment]
Automattic/mongoose#1959

**Comment by vkarpov15** [comment]
https://github.com/mongodb/js-bson/issues/112 as well. Any 12 character string is technically a valid mongodb objectid under the hood, however, mongoose casting doesn't handle that case. I'll open up a separate issue, #3365, to track this.
