### ISSUE TITLE
Custom isValid for ObjectId

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3365]
Re https://github.com/mongodb/js-bson/issues/112, #3363, #1959.

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/issues/1959#issuecomment-170195451

**Comment by iliakan** [comment]
Just my two cents.

It's pretty strange to see `mongoose.Types.ObjectId.isValid('blablablabla')` returning `true` and see `CastError` on further operations with such `id`, because it's actually invalid.

That really looks like API inconsistency.

**Comment by vkarpov15** [comment]
Yeah you're right that is a little weird. Can you show me an example of what operations give a CastError with such an id?

**Comment by iliakan** [comment]
`findById("blablablabla")`
