### ISSUE TITLE
Update Guide: built in validators

### ISSUE THREAD

**Issue by adamzerner** [Automattic/mongoose#3368]
http://mongoosejs.com/docs/validation.html

[maxlength](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-maxlength) and [minlength](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-minlength) should be added to the `Built in validators` section.

**Comment by adamzerner** [comment]
Looks like it failed the build.

**Comment by vkarpov15** [comment]
Don't worry about it, Travis is pretty flakey when you try to do mongodb operations. I'm considering switching us over to Semaphore, because they're much more reliable.
