### ISSUE TITLE
Possible Issue with Mongoose hitting Mongo RS with v2 & v3 members?

### ISSUE THREAD

**Issue by ninjada** [Automattic/mongoose#3372]
Hi, have been running mongoose 3.8.35 against a mongo v2.68 RS for sometime. Recently undertook process to upgrade our stack starting with our qa & staging environments from v2.68 to latest v3.06 along with all associated drivers etc. We tested mongoose 4.x and our app experienced a drop in performance and so remained at 3.8x. these upgraded environments had not encountered any issues for past 1-2months. 

Fast forward to upgrading our production servers, as we're unable to get past the addition of servers. unlike qa & staging where we took the mongo RS offline and ugpraded, being production we're performing a rolling upgrade bringing in new v3 secondaries to the RS before swapping the v2's out. unfortunately, as soon as we add new v3 members and they are synced and begin transacting our app begins throwing connection errors, mongo begins throwing REPLSET errors and things descend from there. 

We've reached a bit of a deadend with support and are trying to rule out all possibilities, which as far as I can tell would seem to be 3 possible causes. 1) an unknown issue with our app's mongo queries under mongod v3, that only causes serious issue at production scale, 2) an unknown mongo v3 RS bug or 3) an unknown issue with some of the drivers/tools in use such as mongoose, in particular hitting mixed version replica sets, as things seems fine with singular v2 or v3 repl sets.

The last one might be reaching, but just seeking advice really. I've combed the other issue posts without finding much specific in that area. I'm wondering if there any reports regarding issues with mongoose 3.8x or any reason you could imagine such a scenario with mongo when there are mixed version within a replica set?

**Comment by vkarpov15** [comment]
Can you show me how you're using mongoose to connect? Mongoose doesn't do any replica set management itself, so it's most likely an issue with the mongodb driver or with the way you're connecting with mongoose. I haven't seen any similar issues unfortunately - I just tried running the below script

```javascript
'use strict';

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27000/gh3356');

var DriverSchema = new Schema({
  averageResponseTimeInSeconds: Number,
  percentageOnTime: {
    type: Number,
    default: 100
  }
});

var Driver = mongoose.model('gh3356', DriverSchema);

Driver.create({ percentageOnTime: 25 }, function(error, doc) {
  console.log(doc.percentageOnTime);
  Driver.findById(doc._id, function(error, doc) {
    console.log(doc.percentageOnTime);
    process.exit(0);
  });
});
```

in a mixed-version replica set with 2.6.10 primary and 1/2 3.0.5 secondaries, either way works fine.

**Comment by ninjada** [comment]
let me try and condense it:

{code}
var configFile = require('yaml-config');
var globalConfig = configFile.readConfig('config/config.yaml'); 
// mongodb:
    mydb1: "mongodb://mongodb-rs0-1:27017/mydb1,mongodb-rs0-2:27017/mydb1,mongodb-rs0-9:27017/mydb1/mydb1?replicaSet=rs0"
    mydb2: "mongodb://mongodb-rs0-1:27017/mydb2,mongodb-rs0-2:27017/mydb2,mongodb-rs0-9:27017/mydb2?replicaSet=rs0"
//
var mongoose = require('mongoose')
var mongoClusters = {};

var db1 = mongoose.createConnection(globalConfig.mongodb.mydb1).on('open', function () {
    console.log("Connected to MongoDB: " + globalConfig.mongodb.mydb1);
}).on('error', function (err) {
    console.log("Failed to connect to MongoDB: " + globalConfig.mongodb.mydb1)
    console.log(err);
})

var db2 = mongoose.createConnection(globalConfig.mongodb.mydb2).on('open', function () {
    console.log("Connected to MongoDB: " + globalConfig.mongodb.mydb2);
}).on('error', function (err) {
    console.log("Failed to connect to MongoDB: " + globalConfig.mongodb.mydb2)
    console.log(err);
})

mongoClusters['mydb1'] = db1;
mongoClusters['mydb2'] = db2;

module.exports.mongoClusters = mongoClusters;

var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var MongoStackCollection = require('../mongo-stack-collection');

var ScheduleQueueSchema = new Schema({
    stack_id: Number,
    created_at: Number,
    scheduled_action: String,
    publish_at: {type: Number, default: 0},
    publish_id: String
}, {collection: 'Schedule_Queue', read: 'secondaryPreferred'});
{code}

**Comment by vkarpov15** [comment]
I don't see anything in the above example that would cause this. What does the timeout error that you're seeing look like?

**Comment by ninjada** [comment]
They're just connections timeouts with no real detail unfortunately:

```node
READY internal-app-data-ElB-xxxxxxxx.us-east-1.elb.amazonaws.com/data/5150.json?visible_on=plugin&page=1
{ [MongoError: connection to [mongodb-rs0-10:27017] timed out]
  name: 'MongoError',
  err: 'connection to [mongodb-rs0-10:27017] timed out' }
```

rs0-10 being a new v3.0x node added in. I would presume this is solely Mongo's fault but it is equally vague in its errors even at the highest log levels, but yeah just checking all possibilities.

will test latest v4.x too, thanks for your help! :)

**Comment by vkarpov15** [comment]
Do you have a stack trace? That may help. I'd imagine this may be an issue with the driver.

**Comment by vkarpov15** [comment]
@ninjada actually, taking a closer look, I think your [connection strings](http://docs.mongodb.org/manual/reference/connection-string/) are improperly formatted. It's a subtle issue that's difficult to spot, but it may be contributing to your problems. Essentially

```
mongodb://mongodb-rs0-1:27017/mydb1,mongodb-rs0-2:27017/mydb1,mongodb-rs0-3:27017/mydb1?replicaSet=rs0
```

should be

```
mongodb://mongodb-rs0-1:27017,mongodb-rs0-2:27017,mongodb-rs0-3:27017/mydb1?replicaSet=rs0
```

Note the removal of the `/mydb1` after each host. Mongoose may be parsing the connection improperly. There was an issue a while back about mongoose docs improperly specifying the connection string in the format you specified, which has since been fixed. http://mongoosejs.com/docs/connections.html
