### ISSUE TITLE
findOne does not return the _id

### ISSUE THREAD

**Issue by prtome** [Automattic/mongoose#3378]
(mongoose v 4.1.7, mongo 3.0.3)
Hello
when calling : Account.findOne({'username': myname}, function(err,user) {console.log(user)};
I correctly get the  info, but never the _id of the object. A direct call to mongo returns the _id, so I know it is there.
I understood from what I read that the _id is returned.  Is this correct ?
Thanks

**Comment by vkarpov15** [comment]
It should be. What does your schema look like?

**Comment by prtome** [comment]
Here is my schema.
    var Account = new Schema({
      dbname: { type: String, required: true },
      schema: { type: String, required: true },
      username: { type: String, required: true },  // combines dbschema and username
      nomuser: { type: String, required: true },  // the username as the user sees it
      role: { type: String, required: true },
      mylang: { type: String, required: true },
      lastlogin: { type: Date, default: Date.now } ,
      password:  String 
    });

**Comment by vkarpov15** [comment]
The issue probably has something to do with the fact that you have a path named `schema`. Mongoose 4 throws an error when this happens, so I'm not sure how you managed to get the provided schema to work. Once you remove the offending path name, the below script works for me without error:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3378');

var accountSchema = new Schema({
  dbname: { type: String, required: true },
  username: { type: String, required: true }, // combines dbschema and username
  nomuser: { type: String, required: true }, // the username as the user sees it
  role: { type: String, required: true },
  mylang: { type: String, required: true },
  lastlogin: { type: Date, default: Date.now } ,
  password: String
});

var Account = mongoose.model('account', accountSchema);

Account.remove({}, function(error) {
  Account.create({ dbname: 'a', username: 'b', nomuser: 'c', role: 'd', mylang: 'e' }, function(error, doc) {
    assert.ifError(error);
    Account.findOne({ username: 'b' }, function(error, doc) {
      assert.ifError(error);
      assert.ok(doc._id);
      console.log('done');
      process.exit(0);
    });
  });
});
```

```
$ node gh-3378.js 
Mongoose: accounts.remove({}) {}  
Mongoose: accounts.insert({ dbname: 'a', username: 'b', nomuser: 'c', role: 'd', mylang: 'e', _id: ObjectId("55f9bef94f997dc026e89f3a"), lastlogin: new Date("Wed, 16 Sep 2015 19:11:53 GMT"), __v: 0 })   
Mongoose: accounts.findOne({ username: 'b' }) { fields: undefined }  
done
```

**Comment by prtome** [comment]
I will check, but I realise now that I took a letter away when adding spaces for the code to show well. the name is nurschema and not schema
I will modify it anyway to make sure it is not that the problem. I check now

**Comment by prtome** [comment]
Thanks, I can reproduce your script and results - and it works for me to, even when adding nurschema.
So there is something else in my code/setup, because it still does not work inside my code.
I will modify your example to look like my code and see if I can find what is going on.
Thanks for your help, I might come back with more questions

**Comment by prtome** [comment]
Thanks for your help
I must have something weird then in my code, since I can run your script without problem. 
It is going to be difficult to find I am afraid
Thanks again

**Comment by prtome** [comment]
Thank you again. I don't know what I did exactly - but I corrected all "schema" path in my models, even the ones not called by the function. Maybe it was that or a control char in my Account model (I retyped the name there also) - now it works!
