### ISSUE TITLE
extract pluralize from utils.js

### ISSUE THREAD

**Issue by ChristianMurphy** [Automattic/mongoose#3382]
`lib/utils.js` that there is a section for pluralizing words.
and a deprecation notice that refers back to #1350.

Is this something that could now be completely deprecated and removed?
Or if the functionality needs to stay, could a library like https://github.com/blakeembrey/pluralize be used rather than maintaining an internal implementation?

Thoughts? :thought_balloon:

**Comment by vkarpov15** [comment]
There's a deprecation warning there, however, we decided to not remove it for v4 because it would break too many people's code. We could use pluralize instead, would make life easier to not have to maintain a separate implementation.
