### ISSUE TITLE
 Npm install with node4 on windows fails.

### ISSUE THREAD

**Issue by bgSosh** [Automattic/mongoose#3384]
I'm no longer able to npm install mongoose on my windows7 dev box after upgrade to node 4.

I get about 3 pages of compilation errors, culminating in:
`
gyp ERR! build error
gyp ERR! stack Error: `xxxx\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (xxxxx\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
`

**Comment by vkarpov15** [comment]
The node-gyp errors are just warnings, you should be able to use mongoose normally on node v4 if node-gyp fails unless you have your mongod instance hooked up to a kerberos cluster and you're using the kerberos authentication mechanism.
