### ISSUE TITLE
Using mongoose schemas and models with another data access tool

### ISSUE THREAD

**Issue by matheo** [Automattic/mongoose#3385]
Hi all
I just want to ask a n00b question about the possibility to "reuse" some mongoose features with another database like postgress, using https://github.com/robconery/massive-js

I would like to know if there's so much coupling to mongodb to try to get mongoose schemas and models working with a different lib. Reading the docs, the practical stuff is what I would like to have but with Postgres.

May I start from scratch learning from your approach?
or it's possible to build a driver to support some stuff and excluding some unsupported features?

Thanks you very much

**Comment by matheo** [comment]
Checking mongoose ooooolder versions, when the codebase was more basic, I think it could be possible for me to get some inspiration to build a basic abstraction layer for my nodejs models. Any suggestion for which version I should check? 1.2.0? :P 2.0? Thanks!

**Comment by vkarpov15** [comment]
I would imagine it would be very difficult to get mongoose to work with postgres, but I've never tried. I'm not sure which early versions of mongoose would be good examples since I wasn't around then, but you could try taking a look at [monogram](https://github.com/vkarpov15/monogram)

**Comment by matheo** [comment]
WOOOOW!
I think I wont get to know your repo if I don't ask here!
Thank you VERY MUCH! I will check it and please, may I ask for your help adapting it to use [Massive.js](https://github.com/robconery/massive-js#full-jsonb-document-support)?
Best regards!

**Comment by vkarpov15** [comment]
Open up an issue on monogram. One of the longer-term goals for the project is to make it more generic so it can pull data from multiple sources into a single document - make it pluggable while hopefully avoiding turning into this:

![image](https://cloud.githubusercontent.com/assets/1620265/9994734/afda4d94-604c-11e5-99b9-fc4af5459123.png)
