### ISSUE TITLE
Using bluebird by way of PromiseProvider printing all exceptions as Unhandled

### ISSUE THREAD

**Issue by awdogsgo2heaven** [Automattic/mongoose#3391]
I've setup mongoose (4.17) to use bluebird for promises by way of PromiseProvider. It works, but , all errors from Mongoose get printed as unhandled, even if I handle them by way of 'catch'.
Example code:

var promise = Barcode.create({ barcode: barcode, standard: standard }); promise.catch(function(e){ console.log(e); res.sendStatus(500); }); 

This should throw a validation error as an invalid barcode, then be caught print to the screen and be done.

Reality: it prints the exception (verifying its 'caught') but still prints as Unhandled anyways. It does this for ALL mongoose exceptions handled anywhere in my code (thus making my tests very ugly, and confusing to track down REAL issues)

I've posted this as an issue in bluebird, but on reflection I think I may have posted it here first to see if it was a known issue. I see there are tests for using bluebird as a promise provider in code but I don't think there is one for exceptions, but I find it hard to believe this may have been overlooked. Is there something I'm missing here?
 
Print out below:

<b>from console ------>>>>></b> { [ValidationError: Barcode validation failed]
message: 'Barcode validation failed',
name: 'ValidationError',
errors: 
{ barcode: 
{ [ValidatorError: Invalid barcode]
properties: [Object],
stack: 'Error\n at MongooseError.ValidatorError (/home/xxx/test/test-apps/node_modules/mongoose/lib/error/validator.js:25:16)\n at validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:652:13)\n at /home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:681:9\n at Array.forEach (native)\n at SchemaString.SchemaType.doValidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:658:19)\n at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1102:11\n at process._tickCallback (node.js:355:11)',
message: 'Invalid barcode',
name: 'ValidatorError',
kind: 'user defined',
path: 'barcode',
value: '668988' } } }
<b>----Now saying unhandled after it was just caught---->>></b> Unhandled rejection ValidationError: Invalid barcode
at MongooseError.ValidationError (/home/xxx/test/test-apps/node_modules/mongoose/lib/error/validation.js:22:16)
at model.Document.invalidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1230:32)
at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1104:18
at validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:653:7)
at /home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:681:9
at Array.forEach (native)
at SchemaString.SchemaType.doValidate (/home/xxx/test/test-apps/node_modules/mongoose/lib/schematype.js:658:19)
at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1102:11
From previous event:
at model.Document.validate (/home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1071:10)
at model.Object.defineProperty.value.fn (/home/xxx/test/test-apps/node_modules/mongoose/lib/schema.js:190:14)
at model._next (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
at model.proto.(anonymous function) as $__original_save
at /home/xxx/test/test-apps/node_modules/mongoose/lib/document.js:1666:23
From previous event:
at model.wrappedPointCut as save
at /home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1634:37
at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:570:21
at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:249:17
at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:125:13
at Array.forEach (native)
at _each (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:46:24)
at async.each (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:124:9)
at _asyncMap (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:248:13)
at Object.map (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:219:23)
at _parallel (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:568:20)
at Object.async.parallel (/home/xxx/test/test-apps/node_modules/mongoose/node_modules/async/lib/async.js:598:9)
at /home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1640:11
From previous event:
at Function.create (/home/xxx/test/test-apps/node_modules/mongoose/lib/model.js:1622:17)
at exports.barcode (/home/xxx/test/test-apps/test-resource/api/discovery/discovery.controller.js:130:27)
at Layer.handle as handle_request
at next (/home/xxx/test/test-apps/test-resource/node_modules/express/lib/router/route.js:131:13)
at next (/home/xxx/test/test-apps/node_modules/composable-middleware/lib/composable-middleware.js:40:9)
at Query. (/home/xxx/test/test-apps/lib/auth/auth.service.js:36:9)
at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/kareem/index.js:177:19
at /home/xxx/test/test-apps/node_modules/mongoose/node_modules/kareem/index.js:109:16
at process._tickCallback (node.js:355:11)

**Comment by vkarpov15** [comment]
Is this just using `.create()`?

**Comment by awdogsgo2heaven** [comment]
Yes. just a create on a model.

**Comment by awdogsgo2heaven** [comment]
I have a custom validation on it, but this issue is happen literally anywhere there is a mongoose any error. Validation, Write ect. I'm using PromiseProvider set function to set it bluebird in my index..

**Comment by awdogsgo2heaven** [comment]
OK, I did some digging, I tracked the root cause of all this to: $__registerHooksFromSchema
This is called from the Document constructor, which is called when creating a Document. It appears to be coming from this part specifically:

self[pointCut] = function wrappedPointCut () {
      var args = [].slice.call(arguments);
      var lastArg = args.pop();
      var fn;

      return new Promise.ES6(function(resolve, reject) {
        if (lastArg && typeof lastArg !== 'function') {
          args.push(lastArg);
        } else {
          fn = lastArg;
        }
        args.push(function(error, result) {
          if (error) {
            console.log('bbbbbb')
            console.log(error);
            self.$__handleReject(error);
            fn && fn(error);
            reject(error);
            return;
          }

          fn && fn.apply(null, [null].concat(Array.prototype.slice.call(arguments, 1)));
          resolve(result);
        });

        self[newName].apply(self, args);
      });
    };

(console was added for me tracking this)

<b>If I commented out the reject there, all the warnings went away</b> and I was still able to catch the errors using Bluebird's catch. However, I'm not exactly sure what the ramifications could be of removing this! So I hope a contributor out there can comment more about this issue. If I had to speculate, this promise that's created by document is never actually chained with the promise returned by create, as such, catching from that promise does nothing to resolve the reject coming from within the document itself. end speculation.

**Comment by vkarpov15** [comment]
Thanks for digging. `$__registerHooksFromSchema` is a never-ending source of annoyance. However, the fact that bluebird is nagging is strange - we have tests in place for bluebird: https://github.com/Automattic/mongoose/blob/cbc59d94f9bd197c6e0d3b879a4c370f28e310a6/test/promise_provider.test.js#L178 and none of these give any warnings... I'll look in to the 2nd edit, that looks like it would be helpful.

`.catch(function(error) {})` is the same thing as `.then(null, function(error) {});` in every marginally civilized promise library I've seen ([Q](https://github.com/kriskowal/q/blob/79e5b717d7d54f21fe27d1b53f1b8b70eaab0219/q.js#L1711-L1713), [bluebird](https://github.com/petkaantonov/bluebird/blob/287990c4242b36a639ed0813c60ae35088749cb8/src/promise.js#L105)) so adding it shouldn't be a problem.

**Comment by awdogsgo2heaven** [comment]
Thanks for checking. Warnings appeared as soon as I installed bluebird. I traced it in bluebird down to a function that handles possible uncaught errors. I can turn it off but then I lose it for everything else which isn't helpful. I see you added a new test, did any warnings appear that time?

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/commit/c87b5426f6b5e9f367d2ea79720a54b5a81e2825 causes a warning to appear, and https://github.com/Automattic/mongoose/commit/49ca1b431454a1976983f7fb6450464cadece197 causes it to no longer appear. This appears to be a simple issue of bluebird detecting that the `save()` promise in create doesn't have a rejection handler.

**Comment by awdogsgo2heaven** [comment]
Thanks again vkarpov. I guess I can expect to see this commit in 4.1.9?

**Comment by vkarpov15** [comment]
Yep ETA is next Monday (September 28) unless you really need this immediately.

**Comment by awdogsgo2heaven** [comment]
I can wait. Thanks!

**Comment by syzer** [comment]
+1

**Comment by vkarpov15** [comment]
Please provide repro instructions
