### ISSUE TITLE
$all no longer casts string Ids as expected

### ISSUE THREAD

**Issue by inkub8** [Automattic/mongoose#3394]
I've just updated from 4.0.x to 4.1.7
My previous query fails.

```
MyModel.find({participants: {$all: ["56004de515fd637b14278187"]} }).exec(function(err, models) {
   //models.length === 0
});
```

In order to make it work I need to wrap the id in a ```mongoose.Types.ObjectId``` first, i.e.
```
MyModel.find({participants: {$all: [mongoose.Types.ObjectId("56004de515fd637b14278187")]} }).exec(function(err, models) {
   //models.length === 0
});
```

I wonder if the fix for #3163 has caused this?

**Comment by vkarpov15** [comment]
Might have caused this, will check this out later.
