### ISSUE TITLE
npm install mongoose failed on x-linux RedHat 7 due to kerberos

### ISSUE THREAD

**Issue by smartmouse** [Automattic/mongoose#3396]
node version 4.0 --

[node@04 test]$ npm install mongoose
/
> kerberos@0.0.14 install /svt/node/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/svt/node/test/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1

**Comment by vkarpov15** [comment]
Not failure, just warning. kerberos is an optional dependency a few levels up. Mongoose should still work fine unless you're really concerned about kerberos auth (in which case just follow up on your comment in https://github.com/christkv/kerberos/issues/28), and the fact that kerberos blows up on node v4 is something that we're working on. Unfortunately it's far from a trivial fix.
