### ISSUE TITLE
Model#save hangs forever and does not save

### ISSUE THREAD

**Issue by sitegui** [Automattic/mongoose#3399]
Hi all,

After v4.1.5 (and up to, at least, v4.1.8), the `Model#save` does not execute the callback.
Looking closer, it doesn't even send the `update` command to MongoDB.

I can repro this with the following code:
```js
'use strict'

var mongoose = require('mongoose'),
	assert = require('assert')
mongoose.set('debug', true)
mongoose.connect('mongodb://localhost:27017/test')

// Define schema
var Order = mongoose.model('Order', new mongoose.Schema({
	status: {
		// This is the important bit:
		// the embedded field `status.code`
		code: Number
	}
}), 'Order')

// Clean all data in the collection
Order.remove({}, function (err) {
	assert.ifError(err)
	
	// Insert a document using the driver
	Order.collection.insertOne({
		// Note here the field is not `status.code`
		status: 7
	}, function (err) {
		assert.ifError(err)
	
		// With findOne() we'll get the inserted doc above
		Order.findOne(function (err, order) {
			assert.ifError(err)
			console.log(order) // { _id: 56020ad372cc1fd419cb8f30, status: 7 }
			
			// And now we try to save the doc, but this fails somewhere
			// internally (even when the document is actually changed)
			// No update command is sent to MongoDB
			order.save(function (err) {
				// We never get called back...
				assert.ifError(err)
				console.log('Saved!!')
				mongoose.connection.close()
			})
			
			// Exit after a while
			setTimeout(function () {
				console.log('Failed ;(')
				process.exit(1)
			}, 3e3).unref()
		})
	})
})
```

This seems to be caused by the fact the schema is `{status: {code: Number}}` and the document from the DB is `{status: 7}`. Probably mongoose can't handle this internally, but why doesn't it throw some exception or something? Maybe it is, but the exception is sent somewhere else?

FWIW: I'm using node v0.12.7 and mongo v3.0.6, but this does not seem related

Can someone confirm this?

**Comment by zladuric** [comment]
Confirming, I have the same issue with mongoose 4.1.18, with MongoDB 2.6.11 and Node 0.12.7 or 0.10.40.

FWIW I'm compiling my code with babel, from ES6. Additionally, when installing mongoose, I get compile errors on the kerberos stuff:
`../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory`

Since npm continued, I assumed it's something optional. There even isn't a npm-debug.log. Was I wrong?

**Comment by porsager** [comment]
This seems to be broken since Promises where implemented for Model.save().

**Comment by vkarpov15** [comment]
Don't worry about the kerberos stuff, it's an optional dependency. Re: the original issue, I'll investigate shortly.

**Comment by sitegui** [comment]
Thanks for the quick fix :)

I didn't tested it here yet, but wouldn't it be the case we add a test case for this?

**Comment by vkarpov15** [comment]
So I can only repro if I actually change the doc:

```javascript
'use strict'

var mongoose = require('mongoose'),
    assert = require('assert')
mongoose.set('debug', true)
mongoose.connect('mongodb://localhost:27017/test')

// Define schema
var Order = mongoose.model('Order', new mongoose.Schema({
    status: {
        // This is the important bit:
        // the embedded field `status.code`
        code: Number
    }
}), 'Order')

// Clean all data in the collection
Order.remove({}, function (err) {
    assert.ifError(err)

    // Insert a document using the driver
    Order.collection.insertOne({
        // Note here the field is not `status.code`
        status: 7
    }, function (err) {
        assert.ifError(err)

        // With findOne() we'll get the inserted doc above
        Order.findOne(function (err, order) {
            assert.ifError(err)
            console.log(order) // { _id: 56020ad372cc1fd419cb8f30, status: 7 }

order.status = 8;
            // And now we try to save the doc, but this fails somewhere
            // internally (even when the document is actually changed)
            // No update command is sent to MongoDB
            order.save(function (err) {
                // We never get called back...
console.log(err);
                assert.ifError(err)
                console.log('Saved!!')
                mongoose.connection.close()
            })

            // Exit after a while
            setTimeout(function () {
                console.log('Failed ;(')
                process.exit(1)
            }, 3e3).unref()
        })
    })
})
```

It's due to `assert.ifError()` triggering and save() swallowing the exception because of [this line in `mpromise'](https://github.com/aheckmann/mpromise/blob/c199b753fc5a7d270f5618c05cb41aad7fd87ea3/lib/promise.js#L227-L232). Long story short, mpromise has gotta go re: #3402.

And testing this is really hard, unless you're willing to go the `process.on('unchaughtException');` route. I'm open to alternative suggestions though :)
