### ISSUE TITLE
Want to Update Array of Array Object Value in Mongo

### ISSUE THREAD

**Issue by Ashesh007** [Automattic/mongoose#3400]
{
    "_id": ObjectId(),
    "sku": "V4696-DR-V33",
    "options": [
        {
            "sku": "8903689984338",
            "stores": [
                {
                    "code": "AND1",
                    "zipcode": "110070",
                    "inventory": -1000
                },
                {
                    "code": "AND2",
                    "zipcode": "201010",
                    "inventory": -1000
                },
                {
                    "code": "AND3",
                    "zipcode": "411001",
                    "inventory": -1000
                },
                {
                    "code": "AND4",
                    "zipcode": " 700020",
                    "inventory": -1000
                },
                {
                    "code": "",
                    "zipcode": "110015",
                    "inventory": -1000
                }
            ],
            "price": 2199,
            "_id": ObjectId(),
            "size": "14"
        },
        {
            "sku": "1742564789",
            "stores": [
                {
                    "code": "AND5",
                    "zipcode": "110070",
                    "inventory": -1000
                },
                {
                    "code": "AND6",
                    "zipcode": "201010",
                    "inventory": -1000
                },
                {
                    "code": "AND7",
                    "zipcode": "411001",
                    "inventory": -1000
                },
                {
                    "code": "AND8",
                    "zipcode": " 700020",
                    "inventory": -1000
                },
                {
                    "code": "",
                    "zipcode": "110015",
                    "inventory": -1000
                }
            ],
            "price": 2199,
            "_id": ObjectId(),
            "size": "14"
        },

    ]
    }

I want to update each inventory value. I want query in mongo query or any python script to update whole document with nested value. Can I use $unwind method for resolve this issue ??? I want Mongo query related to this issue? Kindly Reply this issue ?? I am very Stuck with This Issue

**Comment by vkarpov15** [comment]
There's no way to do this with a single update that I'm aware of, update doesn't go into arrays. $unwind works well, but the aggregation will be somewhat complex and cumbersome. Easiest way would be to just load the documents, modify them, and then save them back.

**Comment by Ashesh007** [comment]
But i have 1 billion documents in one collections then it's not possible to reload all the document. want some simple way to resolve this issue????

**Comment by vkarpov15** [comment]
The simplest way IMO would be to just do a script that loads the documents in batches and then updates them. Doing it with the aggregation framework would be confusing and cumbersome, as well as error prone because you'd have to do a very messy `$project`.
