### ISSUE TITLE
Breaking change from 3.8.35 to 4.1.8 due to _skipDepopulateTopLevel

### ISSUE THREAD

**Issue by Jolg42** [Automattic/mongoose#3408]
Hi,

I'm using `model.toObject({depopulate: true, getters: false, virtuals: false, minimize: true})` to take snapshots of my data.

The problem is happening only if i'm trying to do the `.toObject` after an update, I looked in the source code and I found the origin, the `.toObject` was returning the object correctly on the first time before the update and only the id after, due to the `return clone(this._id, options);`

```javascript
 Document.prototype.$toObject = function(options, json) {
  var defaultOptions = { transform: true, json: json };

  if (options && options.depopulate && !options._skipDepopulateTopLevel && this.$__.wasPopulated) {
    // populated paths that we set to a document
    return clone(this._id, options);
  }

```
See https://github.com/Automattic/mongoose/compare/3.8.35...4.1.8#diff-fc7fc7567205f95715daa4204b8ea0b0R1710

What do you think about this ?

**Comment by vkarpov15** [comment]
Hmm can you show me the code that's causing this issue?

**Comment by Jolg42** [comment]
@vkarpov15 
The route
```js
  .put('/:id', dao.get, version.snapshot, controller.update, version.snapshot, renderer.update)
```
Here it's `version.snapshot`
```js
req.versions.push(req.model.toObject({depopulate: true, getters: false, virtuals: false, minimize: true}));
```

**Comment by vkarpov15** [comment]
Ok. But you mentioned something about doing an update in the first post? What's that about?
