### ISSUE TITLE
sub-doc is not saved when parent object saved

### ISSUE THREAD

**Issue by swrocket** [Automattic/mongoose#3416]
I have a hierarchy that I'm trying to save. The top level object gets saved but the sub object does not get updated.

    var UserSchema = mongoose.Schema({
        email:String,
        password:String,
        googleId:String,
        facebookId: String,
        twitterId:String,
        displayName:String,
        active:{type:Boolean, default:false},
        infoComplete:{type:Boolean, default:false},
        phone: String,
        move: { type: Schema.Types.ObjectId, ref: 'Move'}
    });
    var moveSchema = mongoose.Schema({
        oldHome: {
            address: { type: String,  default:''},
            suite: { type: String,  default:''},
            city: { type: String, default:''},
            state: { type: String,  default:''},
            zip: { type: String, default:''},
            geo: {
                lat: {type:Number,default:0},
                lon: {type:Number,default:0}
            },
            rentown:  { type: String, enum: ['own', 'rent'], default:'own'}
        },
        newHome: {
            address: { type: String,  default:''},
            suite: { type: String,  default:''},
            city: { type: String,  default:''},
            state: { type: String,  default:''},
            zip: { type: String,  default:''},
            geo: {
                lat: {type:Number,default:0},
                lon: {type:Number,default:0}
            },
            rentown:  { type: String, enum: ['own', 'rent'], default:'own' }
        },
        moveoutDate: {type:Date, default:new moment().add(60, 'days').toDate()},
        moveinDate: {type:Date, default:new moment().add(60, 'days').toDate()},
        createdDate: {type: Date, default:Date.now()},
        activities: [moveActivitySchema]
    });

     //middleware
    router.use("/:userId", function(req, res, next){
        User.findById(req.params.userId).populate('move').exec(function(err, user){
            if(err){
                res.status(500).send(err);
            }
            else if(user){
                req.user = user;
                next();
            }
            else
                res.status(404).send("No time frame found");
        });
    });

    router.route('/:userId')
        .get(function(req, res){
            res.json(req.user); //this uses the middleware above
        })
        .put(function(req, res){
            //update the user.
            //req.user is set in the middleware

            req.user.displayName = req.body.displayName;
            req.user.email = req.body.email;
            req.user.phone = req.body.phone;
            req.user.infoComplete = req.body.infoComplete;
            req.user.move = req.body.move;

            console.log(req.user.move ); //this show the right data

            req.user.save(function(err){
                if (err)
                    res.status(500).send(err);
                else
                    res.json(req.user);
            });
        })
        .patch(function(req, res){
            if (req.body._id){
                delete req.body._id;
            }
            for (var p in req.body){
                req.user[p] = req.body[p];
            }
            req.user.save(function(err){
                if (err)
                    res.status(500).send(err);
                else
                    res.json(req.user);
            });
        })
        .delete(function(req, res){
            req.user.remove(function(err){
                if (err)
                    res.status(500).send(err);
                else
                    res.status(204).send("Deleted");
            });
        });

This is the debug
Mongoose: users.update({ _id: ObjectId("56097036db0a99dc2bb42e41") }) { '$set': { move: ObjectId("56097036db0a99dc2bb42e40") } }

If this is a stupid question please forgive me and refer me to the place in the docs where it's addressed. I come for an Entity Framework world and this is new to me.

TIA,

Andrew

**Comment by vkarpov15** [comment]
When you call `.save()`, mongoose explicitly avoids saving documents that you've populated. Is that what you're trying to do?

**Comment by swrocket** [comment]
Yes, that's what I'm trying to do. I expected, perhaps in error, that I could populate an entire hierarchy and save it all at once.

**Comment by Jeff-Lewis** [comment]
@vkarpov15 I assume there's some history behind this behavior but I'm curious why Mongoose doesn't support this type of saving. We've spent a considerable amount of time trying to create a recursive save Mongoose plugin that saves a model's populated docs that have changed.

Without it, IMHO, you loose some to the simplicity of using JSON and embedded documents in the application layer of the app built on top of Mongoose.

For one, I assume you would need to have collection object instead of arrays to keep track of array properties. 

Anyway, coming from working with ORMS, it was something they did and it's what made working with the DB easier.

**Comment by vkarpov15** [comment]
@Jeff-Lewis there was a fair amount of discussion about this here: https://github.com/Automattic/mongoose/issues/2418#issuecomment-61795795 . General idea is to avoid implicit writes in mongoose core, because 1) it's harder and more confusing to shut off implicit writes than to write a plugin to explicitly enable them, 2) saving populated docs is often indicative of sub-optimal MongoDB schema design. ORMs have to do implicit writes, that's just how RDBMS works, but mongodb has different constraints and so that behavior isn't as core to mongoose IMO.

A plugin to save recursively populated documents should be doable - if you're stuck, I'd be happy to provide guidance.

**Comment by jhenriquez** [comment]
@Jeff-Lewis I'm using outdated mongoose version (3.8.1) but I recall having a similar issue. Even though, I agree with you that it was surprising (coming from ORMs as well). In our case the relations are not deep, and actually only needed it for one schema, so ended up using a pre-save hook to check and save the sub-doc.

As for this approach @vkarpov15, does it seem reasonable? Would there be a better way around these scenarios?

**Comment by vkarpov15** [comment]
@jhenriquez sure, that sounds reasonable. If you really wanted to implement a generic plugin you'd use a pre save hook that got all the populated docs.

**Comment by Jeff-Lewis** [comment]
@swrocket May I suggest a rename of this issue to "**Populated** ~~sub-doc~~ doc is not saved when parent object saved" ?

This might be helpful for others who are trying to save Populated docs versus [Sub-Docs](http://mongoosejs.com/docs/subdocs.html) which behave differently. Sub-docs are saved when parent doc is saved.

**Comment by vkarpov15** [comment]
Good suggestion @Jeff-Lewis
