### ISSUE TITLE
Is Model.where() should works equal than Model.find()?

### ISSUE THREAD

**Issue by danilodeveloper** [Automattic/mongoose#3417]
Hello guys!
I have this model:
```javascript
var likeSchema = {
   idItemLiked : String,
};

var UserSchema = Schema({
   likes: [likeSchema]
   ...
});
```
So when I execute ```User.find({'likes.idItemLiked' : myID}).exec(...)``` it's returning the users but when I execute:
```javascript
User.where({'likes.idItemLiked' : myID})
   .setOptions({multi : true})
   .update({active : false},  function(error,raw) {
        ...
    });
```
Nothing happens. 
I expected that ```where``` function return the user array, then I'll update all of the users.
Am I right?

Mongoose version - 4.1.9

Tks!

**Comment by vkarpov15** [comment]
What do you mean by 'nothing happens' - does it hang?

**Comment by danilodeveloper** [comment]
No, the result is empty.

Em ter, 29 de set de 2015 10:44, Valeri Karpov <notifications@github.com>
escreveu:

**Comment by danilodeveloper** [comment]
Hi @vkarpov15, I found my fail, I should have used the positional operator ($) like that:

```javascript
User.where({'likes.idItemLiked' : myID})
   .setOptions({multi : true})
   .update({'likes.$.active' : false},  function(error,raw) {
        ...
    });
```
Now it's working!
Sorry, my fail.

Thanks for help!
