### ISSUE TITLE
patch-style update() function on docs

### ISSUE THREAD

**Issue by tejasmanohar** [Automattic/mongoose#3418]
I've implemented a patch-style update() function for docs [here](https://github.com/autolotto/mongoose-model-update). Was wondering if this is something Mongoose would be interested in introducing (before I clean it up some more, look through the core, and submit PR).

And, I guess, even if it's not fit for the core, if whoever sees this has any thoughts on the module, definitely interested in hearing :smiley:

**Comment by vkarpov15** [comment]
I like the idea of this plugin, good job :) I'm not really sure we want to add it into core, since the core is already pretty heavy and this fits very nicely as a plugin.

**Comment by tejasmanohar** [comment]
Yeah, I think that's fair. It is super light-weight so I guess the argument could go either way... that said, there may be more situations / conditions to consider if this was added to the core, of course.

Lmk if anything changes :)
