### ISSUE TITLE
API docs for Model#save not up to date/wrong

### ISSUE THREAD

**Issue by skleeschulte** [Automattic/mongoose#3420]
Link: http://mongoosejs.com/docs/api.html#model_Model-save

* The callback function parameter is missing (`Model#save([options], document,)`) respectively messed up (`document, <function(err, > Number)} [fn] optional callback`)
* The `numberAffected` explanation is misleading: `[...], and numberAffected which will be 1 when the document was found and updated in the database, otherwise 0.` - `numberAffected` will also be 1 when the document was newly created (also see here: http://stackoverflow.com/questions/24113211/error-in-mongoose-documentation-model-save-numberaffected-1-for-update-rather). Looking at the code reveals `numberAffected` will never be 0 - this will result in an error instead: `if (numAffected <= 0) {  // the update failed. pass an error back  [...]`
* `The fn callback is optional. If no fn is passed and validation fails, the validation error will be emitted on the connection used to create this model.` - Not 100% sure about this one - but I don't see it in the code...?
* The Promise-Example has 2 failures:
  * `product.save().then(function (product, numberAffected) {` - here numberAffected will always be undefined (although in the code there is `resolve(_this, numAffected);`) - the current default promise implementation doesn't seem to support multiple parameters for `resolve`.
  * `}).onRejected(function (err) {` - this must be `onReject`

**Comment by Jeff-Lewis** [comment]
Nice @skleeschulte. We need more attention to detail like this in Mongoose.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, will fix :)
