### ISSUE TITLE
I con't findOne and  save existing record 

### ISSUE THREAD

**Issue by gowthaman-i2i** [Automattic/mongoose#3421]
Hi all,

  i try to find one record  and update but  it's not work  and I didn't get any  erro message also
  
My mongoose version  **mongoose@4.1.9**
```     
  Record.findOne({
        "_id": new ObjectId(id)
      }, function(error, doc) {
         doc.values = _.extend(doc.values, {"name" : "gowtham"}) 
        doc.save(function(err, result) {
          console.log(".....result", result);
        });
      });
 ```

**Comment by vkarpov15** [comment]
What do your schemas look like, etc?

**Comment by mcpDESIGNS** [comment]
Does it help if you do findById at all?
`Record.findById( id )`

Also you aren't logging anything for the errors, does anything come up when you do `console.log(error)` at the update level, and `console.log(err)` at the save level?
