### ISSUE TITLE
Schema migration plugin

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3424]
Should be possible for mongoose to have an equivalent to https://github.com/vkarpov15/monogram-schema-migration - just add a bunch of post hooks.

**Comment by hasezoey** [comment]
is this issue still relevant with https://github.com/mongoosejs/migrations existing and being maintained?

**Comment by vkarpov15** [comment]
We'll close this for now. However, monogram-schema-migration is very different from mongoosejs/migrations. The former is more about individual document versions and upgrading schema versions on individual documents. mongoosejs/migrations is more of a generic tool for managing scripts that modify data.
