### ISSUE TITLE
Mongoose opening multiple unwanted TCP sockets on reconnect

### ISSUE THREAD

**Issue by BillyFS2** [Automattic/mongoose#3426]
Wanting to test a mongoDB server up/down procedure connected to Node/Mongoose, we found out that Mongoose can sometimes open hundreds of TCP sockets (which is not necessary and potentially blocking for the user who is limited to a certain amount of sockets). This occurs in the following case and environment :

Node supervised with PM2 and MongoDB surevised with daemontools

At normal and clean startup :

**$ netstat -alpet | grep mongo
tcp 0 0 *:27017  *:* LISTEN  mongo  65910844 22930/mongod
tcp 0 0 localhost.localdomain:27017 localhost.localdomain:54595 ESTABLISHED mongo 6591110422930/mongod**

The last "ESTABLISHED" line repeated 5 times since the option (poolSize: 5) is specified in Mongoose ("mongo" is the user running mongod under daemontools)

When we have the Node procedure :
```javascript
mongoose.connection.on('disconnected', function () {  
var options = {server: { auto_reconnect:true, poolSize: 5 }};
console.log('Mongoose default connection disconnected ' + mongoose.connection.readyState);
mongoose.connect( dbURI, options );
});
```

and we bring down the MongoDB by daemontools (mongodbdaemon is a simple $mongod command) :

**svc -d /service/mongodbdaemon**

there is of course no mongod running in the system (tested by the netstat command ) and the web server pages called which are using mongoose announce what is normal :

**{"name":"MongoError","message":"topology was destroyed"}**

The problem occurrs at this stage. Since the time we bring down MongoDB, Mongoose accumulates all the connect() calls in the 'disconnected' event handler. This means that the longer we wait before bringing up MongoDB, the more TCP connections will be opened.

So bringing up MongoDB by

**svc -u /service/mongodbdaemon**

gives the following :

**$ netstat -alpet | grep mongo | wc -l**

**850 'ESTABLISHED' TCP connections to mongod !**

If we bring down again mongod, the hundreds of connections remain in the TIME_WAIT state until Linux cleans the socket pool.

Is there a way to avoid this ressource consuming problem ?

Problem reproductible on a CentOS 6.7 / mongoDB 3.0.6 / mongoose 4.1.8 / node 4.0.0

Thanks !

**Comment by vkarpov15** [comment]
The purpose of the `auto_reconnect` option is that mongoose automatically reconnects on its own (technically, the underlying mongodb driver automatically reconnects on its own), so you don't need to try to re-open the connection yourself. If you're going to try to open up a new connection pool every time you get a disconnected event, you're going to open up a new connection every time the connection that you tried to open before fails to connect.
