### ISSUE TITLE
Get count of elements in QueryStream upfront

### ISSUE THREAD

**Issue by skleeschulte** [Automattic/mongoose#3429]
I use QueryStreams to return large result sets. Now I would like to send the total count of objects which will be returned in a HTTP header before I start to stream the results. I think this information might be accessible with the cursor which is used internally by QueryStream and stored in _cursor as soon as _init has finished. But I don't know how/when it is save to access the cursor. Any idea?

**Comment by vkarpov15** [comment]
AFAIK this information isn't available when you create a cursor, because MongoDB would have to iterate through the cursor to find that information :) Best way to do that would be doing a `.count()` to get the number of results before creating the stream.
