### ISSUE TITLE
API docs for Query#select mention prefixing with '+'

### ISSUE THREAD

**Issue by skleeschulte** [Automattic/mongoose#3431]
From the docs: "When using string syntax, prefixing a path with - will flag that path as excluded. When a path does not have the - prefix, it is included. Lastly, if a path is prefixed with +, it forces inclusion of the path, which is useful for paths excluded at the schema level."

And the example:

    // force inclusion of field excluded at schema level
    query.select('+path')

As far as I can see exclusion of paths at schema level and inclusion of excluded paths by prefixing with '+' are no longer supported.

**Comment by vkarpov15** [comment]
Hmm what makes you think that? We have [test coverage](https://github.com/Automattic/mongoose/blob/347e6714c5aa2e9b7987016470009851f396db4e/test/schema.select.test.js#L139-L151) for that exact case.

**Comment by skleeschulte** [comment]
Alright, now I see `select: false` in the schema does indeed work, sorry for that one! I was mislead by "...it forces inclusion of the path..." - I thought that implied that a previously excluded path would not be selected even with `select('path')`. Now I see `select('path')` also selects a previously deselected path and limits the fields to `path` (as expected), whereas `select('+path')` adds the previously deselected path to the field selection...
