### ISSUE TITLE
update is not working when creation and tries to update an array's item.

### ISSUE THREAD

**Issue by carlitux** [Automattic/mongoose#3438]
I have some code like this code:

```js
data1 = {volume: 40}; 
document.save(function (error, doc) {
      var item = doc.items[doc.items.length - 1];
      Document.find({_id: doc._id}).update({'items._id': item._id}, {
        '$set': {
          'items.$.volume': data1.volume
        }
      }, function (error) {
        .....
      });
});
```
Also tried
```js
data1 = {volume: 40}; 
Document.create(data, unction (error, doc) {
      var item = doc.items[doc.items.length - 1];
      Document.find({_id: doc._id}).update({'items._id': item._id}, {
        '$set': {
          'items.$.volume': data1.volume
        }
      }, function (error) {
        .....
      });
});
```

If document is already in mongo it is updating as espected but if not and save is creating it... the code is not updating the data.
This code is to simplify... already the update query is executed in a callback after doing a external processing but this one does the actual flow.

**Comment by vkarpov15** [comment]
Hmm as far as I can tell, the below script executes the correct query...

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh3438');

var schema = new mongoose.Schema({
  items: [{ _id: mongoose.Schema.Types.ObjectId, volume: Number }]
});

var M = mongoose.model('test', schema);

var x = new M();
var _id = new mongoose.Types.ObjectId();
_id = _id.toString();

M.find({ _id: _id }).update({ 'items._id': _id }, { $set: { 'items.$.volume': 40 } }).exec(function(error) {
  process.exit(0);
});
```

The query I get is

```
$ node gh-3438.js 
Mongoose: tests.update({ _id: ObjectId("561ae3b0160bb83b704011ef"), 'items._id': ObjectId("561ae3b0160bb83b704011ef") }) { '$set': { 'items.$.volume': 40 } } {} 
```

Can you double check that this query works for you in the mongodb shell?

**Comment by carlitux** [comment]
@vkarpov15 I mean create and on callback update the same document... please look at my code.

**Comment by vkarpov15** [comment]
I see, but whether the document exists or not doesn't affect whether the query is correct or not. As far as I can tell, the query I put above should actually work, which is why I asked you to make sure the above query works on your data as expected.

**Comment by carlitux** [comment]
@vkarpov15 as I commented if only update the document this really really works (add item and then update)... but when I wrap it with create(Document with the embedded item)... the update query fires as it should also the response is that one document was updated but I look at mongo and it didn't update the item.

**Comment by vkarpov15** [comment]
What does the `data` variable look like in your example?

**Comment by vkarpov15** [comment]
Issue is stale, closing. Re-open if this is still an issue.

**Comment by carlitux** [comment]
@vkarpov15 where you able to reproduce?

**Comment by vkarpov15** [comment]
Nope that's why this issue is closed. I need additional information re: what the data variable looks like, etc. because the script provided doesn't fail. It's typically easier if you just modify the script provided in https://github.com/Automattic/mongoose/issues/3438#issuecomment-147251821 to reproduce your issue - it's really hard to describe code and state accurately in prose.

**Comment by carlitux** [comment]
@vkarpov15 thanks, I just did some basic tests and it is working... maybe on sending string instead ObjectID is causing this...

**Comment by vkarpov15** [comment]
It shouldn't as long as your schema is correct, mongoose should be able to cast a string to an objectid.
