### ISSUE TITLE
Indexes should not be built using the `safe` option

### ISSUE THREAD

**Issue by objectiveSee** [Automattic/mongoose#3439]
Mongoose has multiple ways of creating indexes on your behalf such as the `{autoIndex:true}` option on Schemas, and APIs like `Schema.ensureIndex()` and `Schema.index()`. Indexes created in this manner will look something like this:

```js
app-prod:PRIMARY> db.games.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "app.games"
	},
	{
		"v" : 1,
		"key" : {
			"blitz_mode" : 1
		},
		"name" : "blitz_mode_1",
		"ns" : "app.games",
		"safe" : null
	}
]
```

Notice how the second index includes the option `"safe" : null`. What does this option do? It is unclear, but from digging around the repo and documentation online it appears that `safe` is intended as an option for write connections to the MongoDB server and has nothing to do with indexes. 

`safe` appears to be a superfluous option on the index. The problem with extra options on an index is a) extra is not needed and b) re-creating the identical index via Mongo shell or another Mongo driver, you will need to pass `{safe:null}` as an option. I believe that this option should not be sent when creating indexes, however I do not understand the usage of `safe` outside of indexes enough to make the change. Would love to hear thoughts on this matter! 

Side Note: A similar issue appears to be in the Meteor Mongo driver as well. See https://github.com/meteor/meteor/pull/4340 and https://forums.meteor.com/t/why-does-collection--ensureindex-add-safe-true/3968/5

**Comment by objectiveSee** [comment]
It appears that the mongodb module will exclude certain fields when creating an index, however `safe` is not among them as `safe` is a Mongoose convention. See https://github.com/mongodb/node-mongodb-native/blob/55fa4004addcb8329d061e7be92ad520b77fd772/lib/db.js#L1568

**Comment by vkarpov15** [comment]
Fixed in 781f2b5

**Comment by aaronryden** [comment]
Any tips on how can I remove 
```
safe: null
``` 
from all of my indexes on all of my collections programmatically?

**Comment by vkarpov15** [comment]
@aaronryden unfortunately you would have to [drop your indexes and then rebuild them](https://docs.mongodb.com/v3.0/tutorial/modify-an-index/#drop-the-index) without the `safe` option.
