### ISSUE TITLE
model.remove().then().catch() is undefined

### ISSUE THREAD

**Issue by loulin** [Automattic/mongoose#3442]
Promise provider is set by `mongoose.Promise = require('bluebird');`, but `model.remove()` still uses [mpromise](https://github.com/Automattic/mongoose/blob/master/lib/model.js#L653) so it does not have a catch() method, while `Model.remove()` works fine.

**Comment by vkarpov15** [comment]
Oops, sorry, thanks for catching that.

**Comment by vkarpov15** [comment]
781f2b5 mistakenly references this issue, should have been #3439. a14c576 is the actual fix.
