### ISSUE TITLE
2 possible parent type

### ISSUE THREAD

**Issue by cauburtin** [Automattic/mongoose#3446]
I have

	var PageSchema = new mongoose.Schema({
		//...
		items: [{type: mongoose.Schema.ObjectId, ref:"Element"}],
	})

then

	var ElementSchema = new mongoose.Schema({
		parent: {type: mongoose.Schema.ObjectId, ref: 'Element'}, // or 'Page' how can I do that?
		items: [{type: mongoose.Schema.ObjectId, ref:"Element"}],
		//...
	})

Elements can themselves have elements children items, thus their parent can either be an Element or a Page (at the first level)

How can I specify this?

Is there something better than: 

	var ElementSchema = new mongoose.Schema({
		parentElement: {type: mongoose.Schema.ObjectId, ref: 'Element'},// null or not
		parentPage: {type: mongoose.Schema.ObjectId, ref: 'Page'},// null or not
		items: [{type: mongoose.Schema.ObjectId, ref:"Element"}],
		//...
	})

**Comment by vkarpov15** [comment]
You can use the `refPath` field. Unfortunately we really lack any docs for this right now, but there's some examples in #3108.

**Comment by cauburtin** [comment]
Thanks, what is actually wrong in doing that?

var PageSchema = new mongoose.Schema({
        title: String,
        items: [{type: mongoose.Schema.ObjectId, ref:"Element"}],
    })

    var ElementSchema = new mongoose.Schema({
        parent: {type: mongoose.Schema.ObjectId, ref: 'Element'}, // or 'Page' how can I do that?
        items: [{type: mongoose.Schema.ObjectId, ref:"Element"}],
        html: String
    })

    var Page = mongoose.model("Page", PageSchema);
    var Element = mongoose.model("Element", ElementSchema);

    var p = new Page({title: 'cool'})
    var e = new Element({parent: p._id, html:'ok'})
    p.items.push(e)

    p.save(function(err, doc){
      console.log('p saved',doc)
      e.save(function(err, doc){
        console.log('e saved',doc)
        Element.find({}, function(e, docs){
          console.log('found elts',docs)
          Page.find({})
            .populate('items')
            .exec(function(e, docs){
              console.log('found pages',docs)
              Page.remove({}, function(){})
              Element.remove({}, function(){})
            })
        })
      })
    })

the parent of Element reference an Element, but it's 'working' with a Page, what are the cases when I will have problems doing that?

**Comment by vkarpov15** [comment]
If you try to call `.populate()` on the parent and the Element's parent is the `_id` of a page, you'll get back null.

**Comment by cauburtin** [comment]
Oh right, but I won't have to populate in this upward way, thanks
