### ISSUE TITLE
`.toObject` and `new` constructors not working on a collection's array of schema

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#3452]
Related to my earlier bug with #3451.

Code stops execution and blocks for no apparent reason when I try to do `new Item({ someObj })` or `Item.pre('save'` or `item.toObject()`.  No log output, nothing.

**Comment by niftylettuce** [comment]
Okay I figured out what the issue was.  If you set a key of an array that has type of Schema to be equal to a different Schema's key, then it doesn't change the value.

```
var CartItem = new Schema({ amount: Number });
var Cart = new Schema({ items: [ CartItem ]});

var OrderItem = new Schema({ amount: Number });
var Order = new Schema({ items: [ OrderItem ]});

// now if we have an instance of a cart and an instance of an order
var someCartItem = new CartItem({ amount: 10 });
var cart = new Cart({ items: [ someCartItem ] });

var order = new Order({ items: cart.items });
order.save(next); // <---- here's where the error happens, see below comment
```

Note that when we call `.save` or even instantiate the new order, it does not set the `items` array properly, it does not call pre('save') hooks that we might have created for `OrderItem.pre('save')` for example.  I think this is because `order.items` is now an instance of `cart.items`, which is a Mongoose schema/document of its own.

@aheckmann

**Comment by vkarpov15** [comment]
I don't understand what you're trying to do. A schema is an object, not a constructor, the above code would not work at all. I also don't understand what you mean by "Mongoose schema/document", those are two completely separate concepts. Please provide a real code example to clarify your issue.

**Comment by niftylettuce** [comment]
Nvm
