### ISSUE TITLE
Can't use model methods in promises

### ISSUE THREAD

**Issue by bmcorser** [Automattic/mongoose#3460]
I don't seem to be able to add model methods such as `findById` to the callback chain of a promise by passing them to the `then` method.

For example, the following fails:
``` javascript
new m.Group({name: name})
  .save()
  .then(m.Group.findById)
  .catch(function (err) {
    console.log(err.stack);
  })
;
```
With the following error:
```
TypeError: undefined is not a function
```

I can work around it by defining a closure, but that seems a bit hacky:
``` javascript
var findById = function (Model) {
  return function (object) {
    return Model['findById'](object);
  };
};

new m.Group({name: name})
  .save()
  .then(findById(m.Group))
  .then(console.log)
;
```
Output is as expected:
```
{ _id: 561ca5cad78f5ec166c40041,
  name: 'Humans',
  __v: 0,
  members: [] }
```

Mongoose: 4.1.10
Node: v0.12.6
MongoDB: v3.0.6

**Comment by vkarpov15** [comment]
Classic case of [lost function context](http://stackoverflow.com/questions/16382165/why-do-i-lose-the-context-of-this-in-javascript). Mongoose functions very much depend on context (the value of `this`) so when you execute them in function style, everything goes horribly wrong as you noticed above. Here's a few workarounds.

```javascript
new m.Group({name: name})
  .save()
  .then(m.Group.findById.bind(m))
  .then(console.log)
```

```javascript
new m.Group({name: name})
  .save()
  .then((v) => m.Group.findById(v))
  .then(console.log)
```

```javascript
new m.Group({name: name})
  .save()
  .then(safeCall(m.Group, 'findById'))
  .then(console.log)

function safeCall(obj, name) {
  return function() {
    return obj[name].apply(obj, arguments);
  };
}
```

**Comment by bmcorser** [comment]
Thanks @vkarpov15 ... the wonderful world of JavaScript `;)`
