### ISSUE TITLE
geoNear not working as expected after upgrade

### ISSUE THREAD

**Issue by bardu** [Automattic/mongoose#3462]
Upon upgrading MongoDB from 2.6 to 3.0.6 and Mongoose from 3.8.x to 4.1.11 the following query did always worked:
```javascript
function findData(req, res) {
    var point       = { type : "Point", coordinates : [+req.body.lng, +req.body.lat] },
        maxKm       = 480,
        earthRadius = 6371,
        maxDistance = maxKm / earthRadius;
    // get all campgrounds within 300mi/480km from the users position 
    Campgrounds.geoNear(point, { maxDistance: maxDistance, spherical: true }, function(err, results, stats) {
        if ( err ) {
            console.log(err);
            res.send([]);
        }
        if ( results.length === 0 ) {
            console.log('No campgrounds within 480 km');
            res.send([]);
        }
        else {
            res.send(results);
        }
        
    });
}
```
Now results.length is 0.

I could not find any hints to API changes, are there any?

**Comment by vkarpov15** [comment]
See http://docs.mongodb.org/manual/reference/command/geoNear/, it looks like the MongoDB server uses meters to compute distance if you pass a geoJSON point and radians if you use legacy coordinate pairs. I'm not 100% sure if this was changed in MongoDB 3.0.x but that would explain the behavior you're seeing - try removing the earthRadius division.

**Comment by bardu** [comment]
Yep, that's it, thanks!
