### ISSUE TITLE
Cannot set noTimeout option to the underlying cursor

### ISSUE THREAD

**Issue by mike1808** [Automattic/mongoose#3464]
I've created an administrative script which uses stream in order to get documents one by one process them. It look like this.

```js
model.find().stream().on('data', process);
```

The process function can took more then 10 minutes to finish. However, after 10 minutes the underlying cursor is closed [docs](http://docs.mongodb.org/manual/core/cursors/#closure-of-inactive-cursors). 

I didn't find any solution to get the cursor object and set the noTimeout property to false via [addCursorFlag](https://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#addCursorFlag) method of the cursor of  the native mongodb driver.

Can you expose the underlying cursor object? Something like this
```js
let cursor = model.find().getCursor();
```

**Comment by saranyakEmd** [comment]
their is a option for setting notime out 
var myCursor = db.inventory.find().addOption(DBQuery.Option.noTimeout);
refer
http://docs.mongodb.org/manual/core/cursors/

**Comment by vkarpov15** [comment]
Does https://github.com/Automattic/mongoose/issues/3354#issuecomment-138655847 not work?

```javascript
// 'timeout: true' gets translated by the mongodb driver into a `noCursorTimeout` http://mongodb.github.io/node-mongodb-native/2.0/api/Cursor.html#addCursorFlag
Order.find({}, {}, { timeout: true }).stream();
```

**Comment by mike1808** [comment]
@vkarpov15 thank you. It worked. The issue can be closed now.

**Comment by danielmeng07** [comment]
tried setting timeout to true, still doesn't work. 

```
    model_video
      .find({ 
        "vid_ref.date_updated" : { "$exists" : false } 
      }, {}, { timeout: true })
      .snapshot(true)
      .cursor()
      .on('data', function(d) {
        d.vid_ref.date_updated = d.vid_ref.date || d.date_tagged;
        d.save()
        return;
      })
```

**Comment by danielmeng07** [comment]
Solved by setting batchSize to 10,000
