### ISSUE TITLE
Query Populate: limit options doesn't work in Mongoose 4

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#3469]
We have a schema like this:

```
var Group = new Schema({
    //...
    members: [{type: String, ref: 'User'}]
    //..
});
```

And we're populating a findOne query like this:

```
var q = Group.findOne({$or:[
        {_id: gid, privacy:'public'},
        {_id: gid, privacy:'private', members: {$in:[ user._id]}} // if the group is private, only return if they have access
      ]});

q.populate({path: 'members', select: nameFields, options: {limit: 15} });
```

in order to limit the number of members populated to 15 at most, and it works perfectly in 3.8.x with Mongo 2.6.4

Upgrading to 4.1.1 with same Mongo version break this, and all the members are populated, ignoring the `limit` option

**Comment by vkarpov15** [comment]
So below is my attempt to reproduce this, but the script executes without error in 4.1.1. Can you see if you can tweak it to reproduce your issue?

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh3469');

var groupSchema = new Schema({
  members: [{type: String, ref: 'User'}]
});

var userSchema = new Schema({ _id: String, name: String });

var User = mongoose.model('User', userSchema);
var Group = mongoose.model('Group', groupSchema);

var users = [];
for (var i = 0; i < 10; ++i) {
  users.push({ _id: i, name: 'user' + i });
}

User.remove({}, function(error) {
  assert.ifError(error);
  User.create(users, function(error, docs) {
    assert.ifError(error);
    var group = new Group({ members: [] });
    for (var i = 0; i < docs.length; ++i) {
      group.members.push(docs[i]._id);
    }

    group.save(function(error) {
      assert.ifError(error);
      next(group._id);
    });
  });
});

function next(id) {
  Group.findOne({ _id: id, members: { $in: ['1'] } }).populate({ path: 'members', options: { limit: 5 } }).exec(function(error, group) {
    assert.ifError(error);
    assert.equal(group.members.length, 5);
    console.log('done');
    process.exit(0);
  });
}
```

**Comment by paglias** [comment]
@vkarpov15 thanks for looking into this, I have a test suite where this can be replicated

<img width="1440" alt="schermata 2015-10-23 alle 17 32 54" src="https://cloud.githubusercontent.com/assets/589911/10697482/69778226-79ac-11e5-80cb-f248f6295022.png">

In the case above all the 17 members in the group document are populated, the code is in this branch https://github.com/HabitRPG/habitrpg/tree/paglias/tasks-collection and can be run with `mocha test/api/groups.coffee` from the main directory in the repo

These are the 2 tests that are failing https://github.com/HabitRPG/habitrpg/blob/paglias/tasks-collection/test/api/groups.coffee#L480-L500, their code is and they simply call this API controller method https://github.com/HabitRPG/habitrpg/blob/paglias/tasks-collection/website/src/controllers/groups.js#L132-L177 

and the population options are defined in the same file here https://github.com/HabitRPG/habitrpg/blob/paglias/tasks-collection/website/src/controllers/groups.js#L33

We're using mongodb 2.6.4 if it can help and mongoose ~4.1.8 (i'll make sure to upgrade to 4.2.1 in the next days)

**Comment by vkarpov15** [comment]
Upgrade to 4.2.2 rather than 4.2.1 please :) I'll dig into your code next week. In the meantime, can you do me a favor and run the failing test with `require('mongoose').set('debug', true);`? Would be very interesting to see the queries.

**Comment by paglias** [comment]
@vkarpov15 actually I just noticed that while the tests are failing on my notebook they are fine on TravisCI. So before spending much time digging into this, let me check a bit more. I'll be back with more info in the next 2 weeks, I can't really work on this right now

**Comment by vkarpov15** [comment]
No worries. Might be worthwhile to double check your version of mongoose, just check `node_modules/mongoose/package.json`.

**Comment by vkarpov15** [comment]
This has been stale for a while. Re-open if this is still an issue.
