### ISSUE TITLE
Questions about read preference for query population

### ISSUE THREAD

**Issue by buunguyen** [Automattic/mongoose#3470]
I have a query that explicitly specifies a read option:

```js
const users = await this.Users
        .find(...)
        .read('secondaryPreferred')
        .populate('stuff')
```

Will the population query reuse the read preference of the main query? If not, what is the right way to specify the read preference for the population query? 

As far as the second question goes, I know I can specify populate options with `.populate{path: 'stuff', options: {...}}`, but the documentation doesn't specify how to declare read option.

Any help is much appreciated.

**Comment by buunguyen** [comment]
The code comment of [Query.prototype.setOptions](https://github.com/Automattic/mongoose/blob/master/lib%2Fquery.js#L855) mentions about the `slaveOk` option. But AFAIK, this was deprecated long ago. So I suppose that comment is out of date.

**Comment by vkarpov15** [comment]
Should be `.populate({ path: 'stuff', options: { options: { readPreference: 'secondaryPreferred' } } });`

**Comment by buunguyen** [comment]
Awesome, thanks for the quick response!
