### ISSUE TITLE
Possibility to pass Promise in Query conditions

### ISSUE THREAD

**Issue by googoid** [Automattic/mongoose#3472]
Hey folks,

I have a habit of returning Query in my model methods. It gives me ability to chain my model methods and what's the best thing for me is using `select()` in my routes.

Unfortunately I can't do the following thing:

*schema.coffee*

```coffee
mongoose = require 'mongoose'

module.exports = SomeSchema = new goose.Schema
	someString: String
	someOtherString: String
	someNumber: Number
```
*model.coffee*

```coffee
_ = require 'lodash'
mongoose = require 'mongoose'
SomeSchema = require './schema.coffee'

_.extend SomeSchema.statics,
	findSomeRecordsBySomeNumber: (someNumber) ->
		mongoose.model 'SomeModel'
		.find
			someNumber: someNumber
			someString: @_somePrivatePromisedThingy()

	findTotallyDifferentThing: (someNumber) ->
		@findSomeRecordsBySomeNumber someNumber
		.where 'someOtherString'
		.equals 'some value'

	_somePrivatePromisedThingy: (reallyWantIt = false) ->
		new Promise (resolve, reject) ->
			if not reallyWantIt
				return reject new Error 'but you have to'

			doSomeAsyncStuff (err, result) ->
				if err
					return reject err
				resolve result


mongoose.model 'SomeModel', Schema
```

*main.coffee*

```coffee
mongoose = require './mongoose'

mongoose.model 'SomeModel'
.create
	someString: 'hello'
	someOtherString: 'other string'
	someNumber: 9
.then ->
	promise = mongoose.model 'SomeModel'
	.findSomeRecordsBySomeNumber 9
	.select 'someOtherString'
.then (model) ->
	console.log model.toObject() # contains only '_id' and 'someOtherString'
```

The problem here is that if I resolve promise before calling `find()` I won't be able to return `Query` object.

Any thoughts if currently there is a way of doing this?

Thanks in advance.

**Comment by googoid** [comment]
IMHO async `pre 'find'` hook may help.

So I could run through over all criterias, find promises, resolve them and then call `next()`.

Is it doable somehow?

**Comment by vkarpov15** [comment]
You can just return `return Promise.resolve(query);` if I'm interpretting your problem correctly...

**Comment by googoid** [comment]
Well, `Promise.resolve(query)` will return `Promise` object which is not acceptable in query condition or is it?

**Comment by vkarpov15** [comment]
It'll return the query object, which will let you further modify the query object. I guess I'm not understanding the issue you're having, can you please clarify?

**Comment by googoid** [comment]
**somefile.dat**

```text
somevalue
```

**someotherfile.dat**

```text
someothervalue
```

**test.coffee**

```coffee
promise1 = new Promise (resolve, reject) ->
	fs.readFile './somefile.dat', (err, data) ->
		if err then reject err
		else resolve data

promise2 = new Promise (resolve, reject) ->
	fs.readFile './someotherfile.dat', (err, data) ->
		if err then reject err
		else resolve data

mongoose.model('SomeSchema').find
	somefield: $or: [promise1, promise2]
.then ->
	console.log arguments
```

Excuse me if I failed again explaining the situation.

**Comment by vkarpov15** [comment]
Ah I see. No, mongoose doesn't really have a way of doing that. Your best bet would be to use [co](http://npmjs.org/package/co) and `yield` - `mongoose.model('SomeSchema').find({ somefield: { $or: [yield promise1, yield promise2] } });`

**Comment by googoid** [comment]
Wow cool, didn't thought about that, though my project heavily depends on `co` :)

Thanks a lot and sorry for bothering so much :+1:
