### ISSUE TITLE
Why can't I install a stable version of Mongoose

### ISSUE THREAD

**Issue by computersarecool** [Automattic/mongoose#3476]
Hi,
I have reinstalled and tried various ways of getting a stable installation of Mongoose onto my server but it seems impossible.

Right now I have ``4.1.11`` in my package.json (and installed) and I am still getting the 

```
###################
#
#  !!! MONGOOSE WARNING !!!
# This is an UNSTABLE release of Mongoose......etc

```

I went back to 3.8, same warning. I completely uninstalled mongoose, specified a `"*"` in my package.json file and reinstalled again. Both times I got the same warning. I tried `4.0` and got the same warning.

I though it might be possible that I was running some kind of cached version so I ran `npm --cache-clear` same issue.

Does anybody know a way to get a stable version?  

Also, upon starting up, is there a way to see what version of the software you are running?  I can see no way to tell, which might make asking my questions easier.  Thanks for any input!

**Comment by vkarpov15** [comment]
That warning shouldn't be happening, probably you're installing 3.9.x for some reason. Open up `node_modules/mongoose/package.json` and check the version there - is it actually running version 4.x?

**Comment by computersarecool** [comment]
In my `node_modules/mongoose/package.json` I do have `"version": 4.1.11"`

This is strange right?

**Comment by vkarpov15** [comment]
Yep, considering that the code to print that warning isn't even in 4.1.11 that's pretty strange. Try `rm -rf node_modules && npm clear && npm install`?

**Comment by computersarecool** [comment]
I don't think `npm clear` is a valid command (I am using `npm 2.14.2`) however I did what you said and ran `npm--cache clean` and got the same warning...

**Comment by vkarpov15** [comment]
Err I meant `npm cache clean`. What does your `package.json` look like? Getting that message is simply not possible (barring npm bugout) because mongoose >= 4.0.1 doesn't even have the code to print that message. It might be that you have a separate module that's relying on an old version of mongoose.

**Comment by computersarecool** [comment]
I thought your approach would definitely help - that is what is so wierd. I looked into my `package.json` thinking the same thing.  Here is the output (thanks for your help by the way):
```
{
  "name": "server",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "NODE_ENV=production nodemon ./bin/www",
    "test": "NODE_ENV=development nodemon ./bin/www"
  },
  "dependencies": {
    "async": "^1.4.2",
    "bcrypt": "^0.8.5",
    "body-parser": "^1.14.1",
    "cli-color": "^1.1.0",
    "debug": "^2.2.0",
    "express": "^4.13.3",
    "express-jwt": "^3.1.0",
    "jsonwebtoken": "^5.4.0",
    "moment": "^2.10.6",
    "mongoose": "^4.1.11",
    "morgan": "^1.6.1",
    "nodemon": "^1.7.1",
    "passport": "^0.3.0",
    "passport-local": "^1.0.0",
    "serve-favicon": "^2.3.0",
    "stripe": "^4.0.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-contrib-stylus": "^0.22.0"
  }
}
```

**Comment by vkarpov15** [comment]
Yeah nothing there depends on mongoose AFAIK. Try running `npm list`, maybe you've installed something that depends on mongoose that isn't in your `package.json`.

**Comment by computersarecool** [comment]
The issue was that I was requiring mongoose from the wrong directory.  The mongoose index.js file was in a different directory than the rest of my app, somehow there was an older version of mongoose installed there.
