### ISSUE TITLE
Documentation Links to some methods are incorrect

### ISSUE THREAD

**Issue by michalvankodev** [Automattic/mongoose#3477]
For ex. Navigate to guide -> subdocs (http://mongoosejs.com/docs/subdocs.html)

Under section _Adding subdocs_ there are links to methods `MongooseArray.push` , `MongooseArray.unshift` and so.

There is just a small mistake instead of pointing to url `#types_array_MongooseArray.push` they are pointing to `#types_array_MongooseArray-push`

_See the `-` and `.`_

I haven't tested whole site for mistakes like these but the fix is very easy. I'll create a PR if you want just want to know how to proceed. I can see that docs are generated with some tools. I'm just not sure if the links are defined in the `.jade` files or somewhere else.

**Comment by vkarpov15** [comment]
The links are in the Jade files. PRs would be much appreciated :)
