### ISSUE TITLE
TypeError: Undefined type `FnWrapper` at `path`Did you try nesting Schemas? You can only nest using refs or arrays.

### ISSUE THREAD

**Issue by carlitux** [Automattic/mongoose#3479]
Getting this after upgrade to 4.1.11 I need this for mongodb 3.x

**Comment by vkarpov15** [comment]
Can you show a code example please?

**Comment by carlitux** [comment]
Mongoose file is causing the issues

**Comment by vkarpov15** [comment]
Show an actual code example, otherwise I can't provide any useful information.

**Comment by carlitux** [comment]
@vkarpov15 that is the virtual field.

https://github.com/panta/mongoose-file/blob/master/src/index.coffee#L90

**Comment by vkarpov15** [comment]
Ok, that's a little better, but can you actually show me the code that's using mongoose-file that causes this issue?

Also, there's a good reason why 3.9.x gives you loud unstable warnings when you try to run it. Please don't use 3.9.x, either 3.8.x or 4.x.

**Comment by carlitux** [comment]
@vkarpov15 really I didn't see warnings, the code it simple line:

```js
project.design.file = req.files.design;
```

**Comment by vkarpov15** [comment]
That line doesn't really help. Show schemas please?

**Comment by carlitux** [comment]
Here is my code in es6 using mongoose-file, where add a virtual field in this line:

https://github.com/panta/mongoose-file/blob/master/src/index.coffee#L90

```js
import mongoose from 'mongoose';
import filePlugin from 'mongoose-file';

let ObjectSchema = new Schema({
...
});

ObjectSchema.plugin(filePlugin.filePlugin, {
  name: 'design',
  upload_to: filePlugin.make_upload_to_model(nconf.get('media:upload:to'),
                                             'files'),
  relative_to: nconf.get('media:upload:to'),
  change_cb: function () {
    this._callbackUpload();
  }
});
```

And on controller I just do:

```js
project.design.file = req.files.design;
```

**Comment by vkarpov15** [comment]
The reason is that mongoose-file relies on `pre('set');` hooks, which are historically a bit of a grey area in mongoose. In theory they work, but they have never been documented nor officially supported. 4.2.4 should fix the crash when its released.

**Comment by carlitux** [comment]
Ok, thanks!
