### ISSUE TITLE
Unique indexes not working.

### ISSUE THREAD

**Issue by supasympa** [Automattic/mongoose#348]
I've got a problem with creating unique indexes using Mongoose / MongoDb and can't get it work, I'm able to add two documents with the same attribute values when I have set a unique index.

I've tried everything I can think of - restarting (everything) changing the syntax etc.
### code

```
    var Something = new Schema({
    objectId          : ObjectId,
    name              : { type : String, index: { unique: true }}, 
    url               : { type : String, index: { unique: true }},
    ...etc
    mongoose.model('Something', Something);
```

...

This is the method that I'm using to save an entity:

```
create  : function(entity, definition, successFn, errorFn){ 

var model = mongoose.model(entity);
newModel = new model(definition);

newModel.save(function(error) {
  if(error){
    if(!errorFn){
      throw error;
    }
    errorFn(newModel);
    return;
  }

  successFn(newModel);
});
```

  }...
### Mongo output

```
 [conn1] insert xxxxx.agencies 1526ms
 [conn1] building new index on { name: 1 } for xxxxx.agencies
 [conn1] insert xxxxx.system.indexes exception 11000 E11000 duplicate key error    index: xxxxx.agencies.$name_1  dup key: { : "something" } 4ms
 [conn1] building new index on { url: 1 } for xxxxx.agencies
 [conn1] insert xxxxx.system.indexes exception 11000 E11000 duplicate key error index: xxxxx.agencies.$url_1  dup key: { : "http://www.something.com" } 1ms
```

When I checked in MongoHub the indexes don't appear, so they don't look like they have been created.

**Comment by markstos** [comment]
Perhaps what happened is that the index were first created non-unique and later the unique attribute was added, but Mongoose didn't create the index as unique indexes because it saw the indexes already existed.

**Comment by vkarpov15** [comment]
Yep. Listen for the `Model.on('index');` event to see if any errors occurred in the index build.

**Comment by snanilim** [comment]
markstos, solution work for me. Drop your existing collection and reconnect it again
