### ISSUE TITLE
isModified flag for attribute with default value

### ISSUE THREAD

**Issue by geronime** [Automattic/mongoose#3480]
Hello,

I already described the issue in [stackowerflow](http://stackoverflow.com/questions/33039635/mongoose-js-ismodified-flag-for-attribute-with-default-value).

It seems that mongoose does not mark an attribute that was assigned a default value as modified.

*Example:*
In schema I have defined `created_at` timestamp and `token` attributes; `token` with some generated default value function.
I have an existing document that contains just `_id` and `created_at`. When I find this document with mongoose, the `token` is automatically generated but if I do `document.isModified('token')` I get `false`. This seems to me as a logical issue because the original document doesn't have `token` attribute and the loaded one does; hence modified.

Example code on [stackowerflow](http://stackoverflow.com/questions/33039635/mongoose-js-ismodified-flag-for-attribute-with-default-value).

**Comment by vkarpov15** [comment]
This is a conscious design choice - mongoose treats a value that was automatically set to its default slightly differently than a value that was modified by the user. You can check if a path is in the default state using `doc.$isDefault(path);`, similar to `doc.isModified()`.

**Comment by geronime** [comment]
Tested and this works as expected, thanks!
