### ISSUE TITLE
custom id is not used for models inherited by using discriminators

### ISSUE THREAD

**Issue by thewilli** [Automattic/mongoose#3482]
I'm using mongoose 4.1.12. Consider the official [discriminator example](http://mongoosejs.com/docs/discriminators.html), slightly modified so the main schema has a custom `_id` type (`String` instead of `ObjectId`). Whenever I try to save an in inherited model, I get a validation error because the id type does not match `ObjectId`:

```
var options = { discriminatorKey: 'kind' };

var eventSchema = new mongoose.Schema({ time: Date, _id: String }, options);
var Event = mongoose.model('Event', eventSchema);

var ClickedLinkEvent = Event.discriminator('ClickedLink',
                                           new mongoose.Schema({ url: String }, options));

var genericEvent = new Event({_id: "e1", time: Date.now()});

var clickedEvent =
    new ClickedLinkEvent({ _id: "e2", time: Date.now(), url: 'google.com' });

genericEvent.save(console.log);
/* ok */
clickedEvent.save(console.log);
/*
message: 'ClickedLink validation failed',
  name: 'ValidationError',
  errors:
   { _id:
      { [CastError: Cast to ObjectID failed for value "e2" at path "_id"], ...
*/
``

**Comment by thewilli** [comment]
(re-)defining the `_id` field in the inherited scheme works as a workaround, but this behavior does not seem to be intended, right?

**Comment by vkarpov15** [comment]
Actually it is intended - schemas get an `_id` field by default, so when you create the `ClickedLinkEvent` schema, it automatically has an `_id` field, unless you explicitly [set the `_id` schema option to false](http://mongoosejs.com/docs/guide.html#_id). Admittedly this is a bit of a rough edge in the API, but it'll be a little tricky to fix.

In the meantime, If you want discriminators with a custom `_id`, you're going to need to set the schema `_id` option to false.

**Comment by thewilli** [comment]
thank you for your fast response, imho this should be really clarified in the docs
