### ISSUE TITLE
Have "pre" => "update" hooks been removed?

### ISSUE THREAD

**Issue by edwardhotchkiss** [Automattic/mongoose#3485]
Basic sample code that has always worked. I need it for a much more complex scenario but here is an oldie but goodie that has always worked. I see it triggered but no update saved?

```javascript
SomeSchema.pre('save', function(next) {
  this.modified_on = Date.now();
  next();
});
```

Thanks!

**Comment by vkarpov15** [comment]
Hmm that's something that should definitely work, we have test coverage for that. Can you show me a standalone script that reproduces this issue?

**Comment by edwardhotchkiss** [comment]
I had thought that the Mongoose middleware was async.

**Comment by edwardhotchkiss** [comment]
Thanks @vkarpov15

**Comment by vkarpov15** [comment]
What do you mean? It can be async...
