### ISSUE TITLE
Use Standard Promise By Default

### ISSUE THREAD

**Issue by bluenaux** [Automattic/mongoose#3487]
hi
Will use stardard Promise by default in next version?

**Comment by Jokero** [comment]
https://github.com/Automattic/mongoose/issues/2917

**Comment by vkarpov15** [comment]
Yep, general plan for 5.0 is to use "native if available, otherwise no promises" by default. You'll still be able to set your own promise library using `mongoose.Promise`, so if you're really set on bluebird you can make mongoose use that.
