### ISSUE TITLE
Sort overflow returns partial records instead of error

### ISSUE THREAD

**Issue by mkw** [Automattic/mongoose#3493]
Today, I added a seemingly innocent sort to a query, and suddenly, almost 90% of the records were no longer returned.  Digging in, I tried the same query, with the same sort, from the mongo shell and got an error like "Overflow sort stage buffered data usage of X bytes exceeds internal limit of Y bytes.

But, no error is reported by Mongoose.  I tried both callback and promise versions of the query and both return the same, partial results without the error.

I'm running against MongoDB 3.0.6 in a local, un-sharded, environment on OS X.

I tested both Mongoose 4.0.6 and 4.2.1; neither returned an error.

**Comment by vkarpov15** [comment]
Very vague issue report. What does the query look like, what does the underlying data look like?

**Comment by mkw** [comment]
I'm working on a test case that I can release, including a test collection, but I cannot release the collection to which it happened today because my company owns the data, and it's proprietary.

To answer your questions, the nature of the query does not seem to matter.  In my initial test case, it was a simple find that was supposed to return all objects in the collection; I added a sort, and spent the rest of the afternoon digging weird effects until I realized that slightly less than 1,000 of more than 7,000 objects were being returned.  The change was literally from:
```
MyModel.find({}).select('field1 field2 field3').lean()
```
To:
```
MyModel.find({}).select('field1 field2 field3').sort('field3 _id').lean()
```
I knew that adding the _id as a second sort would probably prevent it from using an index, but didn't care if it was slow for this particular query, and I was doing something that required consistent ordering after a group-by, so adding both sorts would make the group by efficient and the order of the objects in each group consistent.

Until recently, the collection was very small, but the size of the documents got larger, and I forgot about the 32MB memory limit.  I expected that I'd get an error if the sort failed, not that the results would be truncated.

Honestly, given the nature of the error, it's more than likely that this is in the Node driver, or even in MongoDB itself, but I reported it here because after searching this repository's issues and the Node driver's issues, I didn't find anything.

I'm still hoping that someone can prove I'm crazy because we have lots and lots of sorts on growing collections in our application, and it will take a while to track down every single one to make sure we're not getting truncated results.

**Comment by vkarpov15** [comment]
Hmm yeah this does seem like a memory limit issue. I'll see if I can repro.

**Comment by mkw** [comment]
So, I might still be crazy, but adding the following to the model.querying.test.js file will reproduce it:
```
    it('handles sort memory limit errors', function(done) {
      // This is slow because building the collection takes a bit
      this.timeout(60 * 1000);

      if (!mongo26_or_greater) {
        return done();
      }

      var db = start()
        , Overflow = db.model('Overflow', new Schema({f: Buffer}), 'overflow_' + random());

      var totalCount = 1024
        , count = totalCount;
      for (var i = 0; i < totalCount; i++) {
        Overflow.create({f: crypto.pseudoRandomBytes(32 * 1024)}, cb);
      }

      function cb(error) {
        assert.ifError(error);
        if (--count > 0) { return; }
        Overflow.find({}).sort({f: 1, _id: 1}).lean().exec(function(err, results) {
          if (!err) {
            if (results) {
              assert.equal(results.length, totalCount, 'Invalid number of documents returned instead of error.');
            }
            assert.fail('Sort overflow did not throw error.');
          }
          db.close();
          done();
        });
      }
    });
```

I didn't make this a pull request for two reasons:
1. I'm still not convinced it's a Mongoose error, and not a problem in the Node driver or even Mongo itself.
2. I haven't found a way to execute the test quickly.  It's slow to build a large collection.

BTW, I tried using fewer, larger, documents, but the error does not seem to happen with fewer than about 1,000 documents, which makes me even more convinced that the problem is in the driver or Mongo.

**Comment by mkw** [comment]
So, I realized that I could make the insert faster using a bulk insert, though my 10 minutes of effort could only make it work with a crude hack to make sure that the db connection is initialized:
```
    it('handles sort memory limit errors', function(done) {
      // This is slow because building the collection takes a bit
      this.timeout(5 * 1000);

      if (!mongo26_or_greater) {
        return done();
      }

      var db = start()
        , Overflow = db.model('Overflow', new Schema({f: Buffer}), 'overflow_' + random());

      (function sortMemoryLimitError() {
        // Crude check to see if the DB connection is fully initialized: probably wrong, but works.
        if (Overflow.collection.buffer) {
          var self = this;
          db.on('open', function() { sortMemoryLimitError.call(self); });
          return;
        }

        var totalCount = 1024;
        var bulk = Overflow.collection.initializeUnorderedBulkOp();
        for (var i = 0; i < totalCount; i++) {
          bulk.insert({f: crypto.pseudoRandomBytes(32 * 1024)});
        }
        bulk.execute(function(err, result) {
          assert.ifError(err);
          assert.equal(result.nInserted, totalCount, 'Unexpected number of documents inserted.');
          Overflow.find({}).sort({f: 1, _id: 1}).lean().exec(function(err, results) {
            if (!err) {
              if (results) {
                assert.equal(results.length, totalCount, 'Invalid number of documents returned instead of error.');
              }
              assert.fail('Sort overflow did not throw error.');
            }
            db.close();
            done();
          });
        });
      })();
    });
```

I still don't think that it's a pull request.  But, if you want it, feel free to use it.

**Comment by vkarpov15** [comment]
Thanks, I'll take a look at that this week.

**Comment by vkarpov15** [comment]
Thanks for the repro instructions, they're very helpful. This looks like a bug in the underlying driver, I'll put in a PR in a bit and tag this issue.
