### ISSUE TITLE
MongoError: Authentication failed (for empty user/pass)

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3500]
This used to work a couple versions back but now I keep getting a `MongoError: Authentication failed.` error when trying to connect to my localhost database. Can't we connect without credentials anymore?

This is in version 4.2.2, but 4.1.12 is also affected, but working fine when I downgrade to 4.1.6. A little bit worrisome, as there aren't supposed to be any breaking changes for patch releases. 

DB config is:

```javascript
db: {
  uri: 'mongodb://localhost/meanie',
  debug: true,
  options: {
    user: '',
    pass: ''
  }
},
```

**Comment by vkarpov15** [comment]
Should be fixed with #3498 when 4.2.3 gets shipped tomorrow.

**Comment by adambuczynski** [comment]
Thanks!

**Comment by adambuczynski** [comment]
Just to double check, is this fix in 4.2.3 or 4.2.4?
If the latter, when is 4.2.4 due to come out?

**Comment by vkarpov15** [comment]
It's in 4.2.3, which is already released. Re-open if you're still having this issue after upgrading.

**Comment by adambuczynski** [comment]
Ok will retest, just that you modified the milestone from 4.2.3 to 4.2.4 had me a bit confused.

**Comment by zhangjx** [comment]
From 4.2.3 to 4.2.5, this bug also exists. When I used 4.1.11 this bug not exists. Why?

**Comment by vkarpov15** [comment]
@zhangjx can you show a code example? OP for #3498 said that this issue was fixed...

**Comment by adambuczynski** [comment]
I'm on mongoose 4.2.4 now and I can confirm that this issue has been fixed. I am no longer getting an error for empty credentials.
