### ISSUE TITLE
Single nested schemas revert nested population

### ISSUE THREAD

**Issue by aliatsis** [Automattic/mongoose#3501]
Given the schema setup below, the `populateMeArray` within the single nested schema is populated through most of the Document init flow after a find query until this line:

```javascript
doc[i] = schema.cast(obj[i], self, true);
```
After this, the value is depopulated to the corresponding ObjectId.
I really would love to use single nested schemas, but this is definitely a blocker for now.

```javascript
var PopulateMeSchema = new Schema({

});

mongoose.model('PopulateMe', PopulateMeSchema);

var SingleNestedSchema = new Schema({
  populateMeArray: [{
    type: Schema.Types.ObjectId,
    ref: 'PopulateMe'
  }]
});

var ParentSchema = new Schema({
  singleNested: SingleNestedSchema
});
```

**Comment by vkarpov15** [comment]
Thanks for pointing this out, will fix next week.
