### ISSUE TITLE
findOne({email: email, pass: encryptPass}) often works rarely doesn't work !!!

### ISSUE THREAD

**Issue by TroubadourFabiolas** [Automattic/mongoose#3504]
Hello,

I use Mongoose 4.1.11

It's very very hard to perform this bug : 

```javascript
console.log("step1"); // that's display every time in my console => ok

models.users.findOne({email: mail, password: encryptPwd}, function (err, myUser) {
	console.log("step2"); // That's very very weird, that's work but RARELY that's doesn't work
	...
```

Sometimes, my API server doesn't work because of this problem,
Any help to check what's happened ? 

Thank you

**Comment by TroubadourFabiolas** [comment]
For your information, I tried

```javascript
console.log("step1"); // that's display every time in my console => ok

models.users.findOne({email: mail}, function (err, myUser) {
	console.log("step2"); // That's very very weird, that's work but RARELY that's doesn't work
	...
```

But I've got the same problem :confused:

**Comment by vkarpov15** [comment]
Please clarify what "doesn't work" means and provide additional context, code samples, schemas, etc.

**Comment by TroubadourFabiolas** [comment]
"doesn't work" means "step2" doesn't display on my console (terminal).

Of course I use the same email at every test

<img width="1778" alt="capture d ecran 2015-10-27 a 09 40 21" src="https://cloud.githubusercontent.com/assets/8639345/10753125/2742ab66-7c8f-11e5-8d51-736711976e98.png">

<img width="774" alt="capture d ecran 2015-10-27 a 09 44 32" src="https://cloud.githubusercontent.com/assets/8639345/10753170/62b23022-7c8f-11e5-95f9-d10cdb625b91.png">

**Comment by TroubadourFabiolas** [comment]
I think, I've got the same problem when I use a 'MongoLab' resquest

From the back developement : 
my code

```javascript
console.log("step1"); // that's display every time in my console => ok

models.webSiteApiPoi.findOneAndUpdate({_id: req.params.wsPoiId},options).then(function () {
	console.log("step2"); // That's very very weird, that's work but RARELY that's doesn't work
	...
```

From my browser
<img width="612" alt="capture d ecran 2015-10-27 a 16 02 53" src="https://cloud.githubusercontent.com/assets/8639345/10762114/ee44903c-7cc4-11e5-97eb-acffdc22f69e.png">

Server availability problem ?

**Comment by TroubadourFabiolas** [comment]
I just tested with my localhost server and I've got no problem,

so, the problem comes probably from the 'simple hosting server Gandi'

I let you know ...

**Comment by vkarpov15** [comment]
Hmm are you getting the 'DB connection opened' message? I don't see that in your logs...

**Comment by TroubadourFabiolas** [comment]
Yes, I've got it, every time, when I reboot my server ;-)

**Comment by TroubadourFabiolas** [comment]
Hi everybody, I just finished to test with another server service.

I tested with Heroku server and its works very well ;-)

So, very sorry to post this issue because the problem don't come Mongoose

Thank for all ++
