### ISSUE TITLE
Document.array.id.remove() is not working

### ISSUE THREAD

**Issue by sebay00** [Automattic/mongoose#3505]
Hi fellas,

I succeed to create a subdocument, with `document.array.push(new Schema)`.
but I can't remove subdocument with `document.array.id(:id).remove()`

Is there any known issue about it ?

Here's the snippet of my model (Message) :
```
  replies: {
    type: [Reply.Schema]
  }
```
I tried to do something like : 
`message.replies[0].remove();` just for testing it, and it's doesn't work neither. 
`undefined is not a function`

The weirdest is that there's no error. It seems to work, and actually not working.
Also, message.replies.id(:id) is an undefined function. I dont know why, it's written in the doc :(  
And, Obviously it's working well with `Ref`relation. 

I hope you could help me plzzzz. :(

**Comment by vkarpov15** [comment]
Try `message.replies.pull(id)` http://mongoosejs.com/docs/api.html#types_array_MongooseArray.pull

**Comment by sebay00** [comment]
I tried message.replies.pull(:id) followed by a save, and that's not working either !

Here's my creation snippet : 
```
message.replies.push(new Reply(obj));
```

**Comment by vkarpov15** [comment]
Hmm it looks like it's executing the right query, `$pullAll` is what it should do. Can you clarify what you mean by "doesn't work"? Is it not updating the data in the db correctly?
