### ISSUE TITLE
Populate() for deeper paths might ignore schema ref

### ISSUE THREAD

**Issue by dluces** [Automattic/mongoose#3507]
I'm copying a small part of my schema below for reference. This is an issue when populating deep paths (first "tasks" and then "tasks.handler" in this case). The ref property of the deeper path ("tasks.handler") is ignored by populate().

This applies for mongoose 4.1.3.

```javascript
// handler schema
var handlerSchema = new Schema({
  name: { type: String, trim: true },
  moduleName: { type: String, trim: true }
});

// task schema
var taskSchema = new Schema({
  name: { type: String, trim: true },
  handler: { type: Schema.Types.ObjectId, ref: 'Handler' }
});

// application schema
var applicationSchema = new Schema({
  name: { type: String, trim: true },
  tasks: [{ type: Schema.Types.ObjectId, ref: 'Task' }]
});

var Handler = mongoose.model('Handler', handlerSchema);
var Task = mongoose.model('Task', taskSchema);
var Application = mongoose.model('Application', applicationSchema);
```

Here are examples that will and will not work.

```javascript
// this will null the values in application.tasks[x].handler
Application.findOne(search)
  .populate([
    { path: 'tasks'},
    // seems like this path does not refer back to the ref in the handler property for the taskSchema
    { path: 'tasks.handler' }
  ])
  .execAsync()
  .then(function(application) {
    // application.tasks[x].handler is null
    console.log(application.tasks[0].handler);
  })

// this will populate the handlers correctly
Application.findOne(search)
  .populate({ path: 'tasks'})
  .execAsync()
  .then(function(application) {
    // load handlers
    return application.populate({
      path: 'tasks.handler',
      // manually specifying the model fixes the issue
      model: 'Handler'
    }).execPopulate();
  })

// specifying the model for tasks.handler in the original populate() call does not work either
Application.findOne(search)
  .populate([
    { path: 'tasks'},
    {
      path: 'tasks.handler',
      // specifying the model here won't fix the issue either
      model: 'Handler'
    }
  ])
  .execAsync()
  .then(function(application) {
    // application.tasks[x].handler is null
    console.log(application.tasks[0].handler);
  })
```

My guess that the ref config is being ignored for the deeper path is based on the messages written by the mongoose debugger. First, it queries the "tasks" collection with the application's tasks' ObjectIds. But then it queries the "tasks" collection again (and not the "handlers" collection) with the tasks' handler's ObjectIds.

Am I doing something wrong in my schemas? Or is this a problem with the populate method?

**Comment by vkarpov15** [comment]
Hmm that's strange, I don't think this is a known issue, thanks for pointing it out. Will take a closer look later this week.

**Comment by vkarpov15** [comment]
The below should work for you - @timbur did some work in #3103 to add the ability to populate multiple levels down in a single query. The syntax isn't quite as clean as a join, but multi-level populates aren't quite what mongodb is good for :)

```javascript
  Application.findById(id)
    .populate([
      { path: 'tasks', populate: { path: 'handler', model: 'Handler' } }
    ])
    .exec()
    .then(function(application) {
      // application.tasks[x].handler is null
      console.log(application);
      console.log(application.tasks[0].handler);
    });
```

**Comment by dluces** [comment]
Thanks, @vkarpov15! I agree that the fix should be enough for now. My real worry was that the model specified in the schema via ref was being ignored and it was using the parent collection instead to try to populate, which led me to believe that deep population had a bug. Cheers!

**Comment by vkarpov15** [comment]
That's a good point, I'll re-open this and see if that's something we can fix.

**Comment by dluces** [comment]
That's great, @vkarpov15! Thank you
