### ISSUE TITLE
Subdocument validation fails when doing .remove() after change

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3511]
See https://github.com/Automattic/mongoose/issues/1638#issuecomment-151491447

**Comment by vkarpov15** [comment]
In hindsight, this is a much more fundamental issue than I thought re: #1638. This is gonna have to be backwards breaking.

**Comment by niftylettuce** [comment]
I just wanted to chime in and state that I reproduced this bug too.  In my case I called `.remove()` on the last remaining subdocument in an array, and it gives validation errors on the subdocument that was removed still when I do `.save()`.

```js
{ [ValidationError: Document validation failed]
  message: 'Document validation failed',
  name: 'ValidationError',
  errors:
   { 'items.0.quantity':
      { [ValidatorError: Path `quantity` is required.]
        properties: [Object],
        message: 'Path `quantity` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'quantity',
        value: undefined } } }
```

Whereas I called `.remove()` on the item at position `items.0`.

**Comment by Edgesyntax-Kwame** [comment]
Hi i'm using mongoose version `^4.5.0` and experiencing the same issue. Is there a work around for this issue.

I'm getting the same error when using both `lot.locations.remove(lot.locations[index]);`  and `lot.locations.splice(index, 1);` after `.save()`

**Comment by vkarpov15** [comment]
Use mongodb's [$pull](https://docs.mongodb.com/manual/reference/operator/update/pull/) and `Model.update()` for now

**Comment by niftylettuce** [comment]
Bump

**Comment by apboon** [comment]
Bump (impressive.. :) this bug is from 2013 https://github.com/Automattic/mongoose/issues/1638)

**Comment by niftylettuce** [comment]
Bump

**Comment by vkarpov15** [comment]
Seeing as how this one keeps coming up, I think it's about time we investigate this issue with a set of fresh eyes and see if all the refactoring we've done over the last 2 years has made this more feasible. Promoted to the next patch release to take a closer look.

**Comment by apboon** [comment]
**excited** :D

**Comment by dragos99** [comment]
This is back
