### ISSUE TITLE
Promise not rejected on CastError

### ISSUE THREAD

**Issue by gvelo** [Automattic/mongoose#3512]
There is a inconsistent behavior in the API related to error handling on callback vs promise flow.

In the following code, `onRejected`  is never called and a MongooseError ( CastError ) is thrown

``` javascript
doc.update(  { _id: 'foo' }, {  $push:{ bar: value} } ).then( onFulfilled , onRejected )
```

But in the  callback variant the callback function is called properly with the error.

``` javascript
doc.update(  { _id: 'foo' }, {  $push:{ bar: value} },  callback )
```

**Comment by vkarpov15** [comment]
Thanks for pointing this out, will fix.

**Comment by vkarpov15** [comment]
So this would qualify as a backwards breaking change, because I would imagine some people still do

```javascript
try {
  query = Model.update({ _id: 'foo' });
} catch(err) {}

query.exec();
```

because that's part of mongoose's API. That will change in the next release, however, till then,

```javascript
doc.update(  { _id: 'foo' }, {  $push:{ bar: value} }, { dontThrowCastError: true } ).then( onFulfilled , onRejected )
```

is the best we can do unfortunately.
