### ISSUE TITLE
Unable to use comma delimited connection string

### ISSUE THREAD

**Issue by unusualbob** [Automattic/mongoose#3514]
So this is a strange issue that I've run into today. We are running a 2 member replica set and if I include both servers in the connection string I receive an error when connecting.

Replica Set:
Name: my_replica
Primary: replica_2.domain.net
Secondary: replica_1.domain.net

Preferred connection string: `mongodb://replica_1.domain.net,replica_2.domain.net/myDB?replicaSet=my_replica`
This fails with `Error: No valid replicaset instance servers found`

However if I connect directly to the primary, like so: `mongodb://replica_2.domain.net/myDB?replicaSet=my_replica`
This connects fine with no issues

If I connect with the secondary it fails (as expected): `mongodb://replica_1.domain.net/myDB?replicaSet=my_replica`
`TypeError: Object Error: Cannot write to a secondary has no method 'isCompatible'`

Can anyone explain this? I would like both servers to be in the connection string because if for any reason the servers are swapped primary <-> secondary then the application will no longer be able to connect.

Mongoose @ 3.8.20
Node @ 0.10.28

**Comment by vkarpov15** [comment]
Unless you manually configure it, a [2 node replica set won't work with MongoDB](http://stackoverflow.com/questions/25502410/two-nodes-mongodb-replica-set-without-arbiter). By default, the [MongoDB node driver refuses to say its connected to a replica set unless it can find a primary](http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html), so if you have a 2 node replica set and it can't elect a primary, the node driver won't be able to complete its initial connection.

**Comment by unusualbob** [comment]
Ok so just to test your theory @vkarpov15 this time I'm using the latest Mongoose. I've added an arbiter node to the replicaset and still get the same result.

```
> db.version()
2.6.7

> rs.status()
{
	"set" : "my_replica",
	"date" : ISODate("2015-10-28T19:52:57Z"),
	"myState" : 1,
	"members" : [
		{
			"_id" : 1,
			"name" : "replica_1.test.net:27017",
			"health" : 1,
			"state" : 2,
			"stateStr" : "SECONDARY",
			"uptime" : 87846,
			"optime" : Timestamp(1446061975, 1),
			"optimeDate" : ISODate("2015-10-28T19:52:55Z"),
			"lastHeartbeat" : ISODate("2015-10-28T19:52:55Z"),
			"lastHeartbeatRecv" : ISODate("2015-10-28T19:52:55Z"),
			"pingMs" : 2,
			"syncingTo" : "replica_2.test.net:27017"
		},
		{
			"_id" : 3,
			"name" : "replica_2.test.net:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 87846,
			"optime" : Timestamp(1446061976, 1),
			"optimeDate" : ISODate("2015-10-28T19:52:56Z"),
			"electionTime" : Timestamp(1445974137, 1),
			"electionDate" : ISODate("2015-10-27T19:28:57Z"),
			"self" : true
		},
		{
			"_id" : 4,
			"name" : "arbiter.test.net:27020",
			"health" : 1,
			"state" : 7,
			"stateStr" : "ARBITER",
			"uptime" : 343,
			"lastHeartbeat" : ISODate("2015-10-28T19:52:56Z"),
			"lastHeartbeatRecv" : ISODate("2015-10-28T19:52:56Z"),
			"pingMs" : 0
		}
	],
	"ok" : 1
}
```

This is the script I am running to test this:

```js
  var Mongoose = require('mongoose');
  
  var mongodbConnectionString = 'mongodb://replica_1.test.net:27017,replica_2.test.net:27017,arbiter.net:27020/myDatabase';
  
  Mongoose.connect(mongodbConnectionString, {
    server: {
      ssl: true,
      sslValidate: false
    }
  }, function(err) {
    if (err) {
      console.log(err);
      process.exit();
    }
    else {
      console.log("Everything is ok :D");
    }
  });
```

Outputs: 
```
{ [MongoError: no valid seed servers in list] name: 'MongoError', message: 'no valid seed servers in list' }
```

**Comment by unusualbob** [comment]
Aha, just tried swapping the 'server' in options with 'replset' and suddenly it works.

```
Mongoose.connect(mongodbConnectionString, {
    replset: {
      ssl: true,
      sslValidate: false,
      connectWithNoPrimary: true
    }
  }, function(err) {
    if (err) {
      console.log(err);
      process.exit();
    }
    else {
      console.log("Everything is ok :D");
    }
  });
```

Outputs: 
```
Everything is ok :D
```

**Comment by vkarpov15** [comment]
Glad that worked :) Switching between replset and server options is often confusing, this is why I usually just specify those options in the connection string - 'mongodb://replica_1.test.net:27017,replica_2.test.net:27017,arbiter.net:27020/myDatabase?ssl=true'. Unfortunately the node driver doesn't support sslValidate as a query parameter yet though...
