### ISSUE TITLE
doc.constructor.modelName is undefined on doc returned by findOneAndUpdate

### ISSUE THREAD

**Issue by agarzola** [Automattic/mongoose#3515]
Hi! We’re saving some text documents in our application. These documents have a slug for pretty URLs.

We want to redirect users who might have an old URL, so we’ve created a slugs collection that stores document ID and slug string. Say we have document with ID 1234, which previously had `'slug-1'` for its slug, but now has `'slug-2'`, we’d like for a user visiting the first to get redirected to the second.

We have multiple slug collections because we have multiple document models, but the document models themselves share a common schema. So we need to be able to determine which model this document belongs to in order to save the new slug to the right slug collection.

To achieve this, we’ve come up with the following on our schema:

```javascript
editorial.post('findOneAndUpdate', function (doc) {
  if (doc.slug) {
    saveSlug(doc)
  }
})

var saveSlug = function (doc) {
  var modelName = doc.constructor.modelName
  var Slug = require('./index')[modelName]
  Slug.update({ slug: doc.slug }, { document: doc._id }, { upsert: true }, function (err) {
    if (err) { console.log(err) }
  })
}
```

Unfortunately, this results in `modelName` being undefined. We consoled the `doc.constructor` and found that it only returns `[Function: Object]`. If we use `doc.save()`, the constructor has a bunch of data, including the `modelName`.

Are we doing something wrong, or should we not be expecting the `constructor` to work at all with the resulting document from a `findOneAndUpdate()`?

**Comment by vkarpov15** [comment]
Possible bug, will double-check later this week.

**Comment by agarzola** [comment]
Never mind. I had a stray `.lean()` in the original query.

I appreciate the prompt response!
