### ISSUE TITLE
[Question] Key Spacing

### ISSUE THREAD

**Issue by ChristianMurphy** [Automattic/mongoose#3518]
Throughout the Mongoose code base there appear to be 3 styles for object key spacing.
Which one is the preferred code style?
@vkarpov15 

### Style 1
No space before and 1 space after `:`

``` js
{
  a: String,
  aReallyReallyLongKey: String
}
```

### Style 2
1 space before and after `:`

``` js
{
  a : String,
  aReallyReallyLongKey : String
}
```

### Style 3
`:` are aligned to the same column

``` js
 {
   a                    : String,
   aReallyReallyLongKey : String
 }
```

**Comment by vkarpov15** [comment]
Style 1 is my preferred choice :)

**Comment by ChristianMurphy** [comment]
Thanks! :beers:
