### ISSUE TITLE
Model query calls not returning real promises, leading to confusion

### ISSUE THREAD

**Issue by frank-weindel** [Automattic/mongoose#3520]
I'm sure this is well known but I can't find anyone talking about it or any documentation about it but there is a big difference in the THENable that gets returned from a model query call and the real promise that can be then chained from that point forward.

For this example I'm using 'when' for as the promise library setup within mongoose. When supports the `done()` promise terminator call.
```js
var mongoose = require('mongoose');
var when = require('when');
mongoose.Promise = when.Promise;
```

When I do an update for example, I can chain `then()` on the call
```js
  User.update(
    /* Condition */
  ).then(
    function() {
      // Good to go
    }
  );
```

But I cannot chain `done()` (or `catch()` etc) on it
```js
  User.update(
    /* Condition */
  ).done(
    /* Handlers here */
  );
  /* done() does not exist! */
```

However if I first do a then() and then a done(). Its works fine
```js
  User.update(
    /* Condition */
  ).then(
    /* then handlers here */
  ).done(
    /* Done handlers here */
  );
  /* Works fine, but sometimes we don't need the then() */
```

Often times I just want a done() without a then(). Intuitively I should just be able to tack on a `done()`.

I found out that if you call `exec()` first this actually returns a real promise that can be done'd, caught, etc.

```js
  User.update(
    /* Condition */
  ).exec().done(
    /* Done handlers here */
  );
  /* Works well. An acceptable solution */
```

While calling `exec()` first to get a real promise is an acceptable solution I think it is needlessly misleading/confusing to expose a `then()` on the resulting query call object without it being a real promise where you could also call `done()`, `catch()`.

**Comment by vkarpov15** [comment]
The `.then()` is there as syntactic sugar for `yield`, so you can do `yield User.update();` instead of explicitly doing `.exec()`. There will be additional clarification about this with #3441 in the next release.
