### ISSUE TITLE
use find question

### ISSUE THREAD

**Issue by kolonse** [Automattic/mongoose#3522]
my database 's data is over 650,000 , i use the find but my program is block and cpu is full!!!!!

**Comment by kolonse** [comment]
my database 's data is over 650,000 , i use the find but my program is block and cpu is full!!!!!

**Comment by adrian-ludwig** [comment]
Use indexes.

**Comment by vkarpov15** [comment]
You're going to have to clarify some more. 650k what - documents, MB? CPU full on which machine, the one with node or the one with mongodb? Also, what does your find look like code-wise?

**Comment by kolonse** [comment]
@vkarpov15 
650k means count of record, and all of record is same. CPU full is one with node! 

This is my code:
store.prototype.find = function(){
    var self = this ;
    var arg = arguments ;
    var event = arg[0];
    return new Promise(function(fulfill,reject){
        var model = self.model[event] ;
        if( !model ){ //如果该模式不存在 那么重新创建
            self.logger.info("%s 不存在 创建模式",event);
            model = self.mongoose.model(event,self.schema);
            self.model[event] = model ;
        }
        var cb = function(err,result){
            if(err){
                reject(err);
            }else{
                fulfill(result);
            }
        }
        arg = objectPush(arg,cb);
        console.log(arg);
        model.find.apply(model, arg );
    });
}

**Comment by kolonse** [comment]
@adrian-ludwig 
My all records is same, can it  work to use indexes?

**Comment by vkarpov15** [comment]
Looks like you're trying to get all 650k docs into memory at once - depending on how big those docs are, that might be a problem.

**Comment by kolonse** [comment]
@vkarpov15 
every one is small, such as {"event":"test","data":{timestamp:"xxx"}}

**Comment by vkarpov15** [comment]
well that bson doc is gonna be maybe 30 bytes, which is already maybe 19 MB of data that mongoose needs to saturate at once. You can try using `.lean()` to help, see [docs on lean](http://mongoosejs.com/docs/api.html#query_Query-lean), that should reduce CPU usage and memory overhead considerably, but you won't get a full mongoose object.

**Comment by kolonse** [comment]
Very Thanks! it's work really! 
but I do not know the reason,maybe I need to read the source code and resolve it!

**Comment by vkarpov15** [comment]
Reason is that mongoose does a lot of work to make it so you can do things like `doc.num = 5; doc.save();`. If you do `.lean()` that won't work, but if you don't need all the getter/setter syntactic sugar then `.lean()` can give you better performance :)
