### ISSUE TITLE
Feature Idea: Using Joi for validation and schema definition

### ISSUE THREAD

**Issue by mwawrusch** [Automattic/mongoose#3526]
We use hapi and the joi validation library (https://github.com/hapijs/joi) extensively, it is well done and battle tested. Have you considered using that library for schema definition and validation in a future version?

**Comment by vkarpov15** [comment]
Haven't really investigated but I don't really see that being a realistic possibility unless there's a lot of demand. There's plenty of plugins out there for this though, [joigoose](https://github.com/yoitsro/joigoose) is one
