### ISSUE TITLE
Really slow populate?

### ISSUE THREAD

**Issue by Krisa** [Automattic/mongoose#3530]
I'm having a schema similar to this one, at least here the simplified version:

``` javascript
var Schema1 = new Schema({
    name: {type: String },
    schema2: [{type: Schema.Types.ObjectId, ref: 'Obj2'}]
});

var Schema2 = new Schema({
    name: {type: String }
});

var obj1 = mongoose.model('Obj1', Schema1);
var obj2 = mongoose.model('Obj2', Schema2);
```

In Obj1, I'm having currently roughly 100K records. In Obj2, I have just created 1 single record, linked to one document of Obj1.

If I query the whole Obj1, the query takes usually around 4 to 6 seconds on my machine. If I query the whole Obj1 and I add the option to populate `schema2`, then the query takes suddenly 15 to 20s. Again, the key `schema2`of Obj1 is empty for all records, but one. Not so sure, what cause this difference?

**Comment by vkarpov15** [comment]
Hmm not sure. In theory, mongoose should only be executing one extra query for Obj2. Can you enable mongoose debug mode with `require('mongoose').set('debug', true);` and show me the queries that get sent? That might help.

**Comment by Krisa** [comment]
Interesting option ...

This is what I get:
```
Mongoose: metadatas.find({ project: ObjectId("56320690092761878bac2115") }) { batchSize: 10000, fields: { storymetadata: 1, updated_at: 1, status: 1, fullPath: 1, _id: 1 } }  
```
This is the main query, which retrieves approximately the 100K records.

I see then this query:
```
Mongoose: storymetadatas.find({ _id: { '$in': [ ObjectId("5637a99aa54b755528267c1f") ] } }) { fields: undefined } 
```

That's all what's logged.

**Comment by Krisa** [comment]
Maybe worth mentioning, the request is a stream (even so, it doesn't appear in the log above).

**Comment by vkarpov15** [comment]
Ah ok so if you're doing `.find().populate().stream()`, mongoose needs to do a separate request for every single document that comes out of the stream in order to do `.populate()`, which would explain why you're seeing a lot of performance overhead. No way around that unfortunately unless you know in advance what ids you need to query to properly populate the documents.

**Comment by Krisa** [comment]
I see, thank you.

**Comment by pocesar** [comment]
is there anything that could be done to improve the performance @vkarpov15? I'm using stream on the query, and the population for 1kish rows is noticeable slow, and I can't use lean()

**Comment by vkarpov15** [comment]
If you're using mongodb 3.2, you can use $lookup and build an aggregation pipeline. That will give you much better performance but bypass mongoose.

**Comment by pocesar** [comment]
thanks for pointing me to $lookup, but I'm using mongodb 3.0.9 =/

**Comment by vkarpov15** [comment]
Unfortunately there's no good way for mongoose to help you in that case, because to populate on a stream we need to make a separate query for every doc that comes in through the stream.

**Comment by pocesar** [comment]
I see, I'll try to really limit the size of the resulting query before hand then

**Comment by vkarpov15** [comment]
Another approach might be to query in batches rather than using `stream()`. If you query 100 docs at a time then `populate()` can resolve the refs for those docs with 1 query rather than 100.

**Comment by vkarpov15** [comment]
Gonna close this, no way to help with a stream and we're not going to be using `$lookup` for populate.
