### ISSUE TITLE
$lookup 

### ISSUE THREAD

**Issue by StealthyDev** [Automattic/mongoose#3531]
Missing JOIN feature is partially coming to MongoDB. How does it work with Mongoose?

References:
https://jira.mongodb.org/browse/SERVER-19095
http://slamdata.com/blog/2015/10/21/mongodb-missing-join.html

Cheers

**Comment by vkarpov15** [comment]
Should work the same as [any other aggregation stage in mongoose](http://mongoosejs.com/docs/api.html#aggregate-js). We'll add a helper re: #3532, but not much else planned atm.

**Comment by jaider2523** [comment]
Error:

{ [MongoError: exception: Unrecognized pipeline stage name: '$lookup']
  name: 'MongoError',
  message: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
  errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
  code: 16436,
  ok: 0 }

**Comment by vkarpov15** [comment]
@jaider2523 which version of mongodb are you using? That error isn't generated by mongoose, it makes me suspect you're not using mongodb 3.2.

**Comment by jaider2523** [comment]
Hi,

Thanks, i have an old version.....i'm going to upgrade my MongoDB.

**Comment by jaider2523** [comment]
Hi,

@vkarpov15, I need your help with this: Complex Query Populate and More Options #3818 

Is possible?
