### ISSUE TITLE
.lookup aggregation helper

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3532]

**Comment by capaj** [comment]
@vkarpov15 does this mean .populate() will utilize new $lookup operator or am I misunderstanding this issue?

**Comment by vkarpov15** [comment]
Nope. `$lookup` is only for the aggregation framework, which `populate()` doesn't use. It could in the future, but that's too big a change to how mongoose works fundamentally IMO.

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/1ef43b3f5d26933719c98544ca714e6255a45b02
