### ISSUE TITLE
Script for build indexes

### ISSUE THREAD

**Issue by objectiveSee** [Automattic/mongoose#3536]
We have turned off the `autoIndex` property in production, as you should have too. This means that indexes need to be build in some other way. In our company, we have written a script that knows about each Schema from our project and will call `ensureIndexes()` on that Schema. It handles showing a progress indicator of how long you have been building indexes for and some other nice features for building large indexes. 

I am curious if this sort of script would be useful to other people.  I am also curious whether you have a different approach to building indexes in production.

**Comment by vkarpov15** [comment]
That would be extremely useful actually, it's technically possible: https://docs.mongodb.org/manual/tutorial/manage-in-progress-indexing-operations/ . Should be possible to write a plugin to do this...

**Comment by pdesterlich** [comment]
I'm interested in such a script. Can you provide it via a gist?

**Comment by vkarpov15** [comment]
See [`Model.syncIndexes()`](https://mongoosejs.com/docs/api/model.html#model_Model.syncIndexes) and [`syncIndexes()` blog post](https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes)
