### ISSUE TITLE
ReadPreference not working with Mongoose - 4.0.3

### ISSUE THREAD

**Issue by Chatosh** [Automattic/mongoose#3537]
I need to set readPreference at queryLevel. But the below code doesnot work.
modelObj.find({}).read("secondary");
Am I missing out something ?

**Comment by vkarpov15** [comment]
That should work. Can you clarify what you mean by "doesn't work"? What's the structure of your replica set?

**Comment by Chatosh** [comment]
I have a sharded cluster with 2 shards and each shard have 1 primary , 1 secondary and 1 arbiter. Am using MongoDB - 3.0.5 and Mongoose 4.0.3 version. When secondary instances are down and when i query from Mongo Shell with readPreference as secondary , am getting error message as      'no good nodes on rs1'. The same error gets displayed through MongoDB Native Driver. But from Mongoose am getting success result. Hence I doubt if readPreference works or not with Mongoose

**Comment by vkarpov15** [comment]
The only way I can reproduce this is if mongoose thinks it's not connecting to a replica set. In mongoose 4, the below code will open a connection to a single mongod rather than a replica set:

```javascript
mongoose.connect('mongodb://myhost:27000/gh3537');
```

In order to get mongoose to connect to a replica set, you either need to list multiple hosts:

```javascript
mongoose.connect('mongodb://myhost:27000,myhost:27001/gh3537');
```

Or, specify the replica set name in the uri's query string:

```javascript
mongoose.connect('mongodb://myhost:27000/gh3537?replicaSet=mongoosetest');
```

That should help and would explain why you're having a read pref issue - read preferences have no effect if you're connected to a single mongodb instance.

**Comment by Chatosh** [comment]
Am connecting to MongoS instance from my application.Am giving only MongoS IP and Port information to connect to DB from application.Am trying to give readPreference at query level.With MongoDB Nativer driver when i give readPreference as secondary, it works. But am trying the same thing from Mongoose.But it's not working.
```javascript
    var mongoose = require('mongoose').set('debug',true)    

    var conn = mongoose.createConnection('mongodb://MongoSIP:MongoSport/testDB',
    {
        auth: {authdb: "admin"},
        user:"admin",
        pass:"admin",
        db:{
            read_preference:"secondary"
        }
    }

   );

conn.on('error', function () {
    console.log("error", "Error in connecting to Database");
});

var Schema = mongoose.Schema;
var MySchema = new Schema(
    {
       
    },
    {
        "autoIndex": false,
        "safe": true,
        "strict": "throw"
    }
);

var data = conn.model('', MySchema, 'test');
var query = data.find({id: "veh14"}).read("secondary");
query.exec(function (err, data) {
    if (err) {
        console.log('Error ' + err);
    }
    else {
        console.log('Success')
        console.log(data);
    }
});
```

**Comment by vkarpov15** [comment]
Looks like there was no way to tell mongodb that you're connected to a standalone mongos with mongoose :( Now you should be able to do `mongoose.createConnection('mongodb://MongoSIP:MongoSport/testDB', { mongos: true, /* ... */ });` once 4.2.5 is released.
