### ISSUE TITLE
Override .save method to make it Reactive

### ISSUE THREAD

**Issue by vekexasia** [Automattic/mongoose#3538]
Hello is it possible to override the save method so that it returns an observable? 

I tried creating a simple plugin but apparently it does not kick in early enough during object creation

``` javascript
module.exports = exports = function mongoRxPlugin(schema) {

  schema.post('init', function () {
    var _origsave = this.save;
    this.save = Rx.Observable.fromPromise(_origsave);

  });
};

```

**Comment by vkarpov15** [comment]
I don't think it's possible with a post init hook, but you could just create a custom schema method:

```javascript
schema.methods.saveObservable = function() {
  return Rx.Observable.fromPromise(this.save.apply(this, arguments));
}
```

**Comment by vekexasia** [comment]
Hello @vkarpov15 what i'd like is to override the save method... :(

**Comment by vkarpov15** [comment]
It's pretty difficult to do that in a general plugin, because mongoose does a lot of magic under the hood to wrap hooks in promises, and in general we don't support this sort of monkey-patching...
