### ISSUE TITLE
Why the SIGINT signal is blocked when mongoose auto reconnect

### ISSUE THREAD

**Issue by richzw** [Automattic/mongoose#3540]
I have built up the MongoDB auto reconnection feature via Mongoose, here are the code snippets

```javascript
var mongoose = require('mongoose');

var connect = function() {
  var options = {
    server: {
        auto_reconnect: true
    }
  };
  mongoose.connect('mongodb://localhost/' + + 'test_dev', options);
};
connect();

mongoose.connection.on('error', function() {
    console.log('Could not connect to MongoDB');
});

mongoose.connection.on('open', function() {
    console.log('Connection opened to MongoDB');
});

mongoose.connection.on('disconnected', function(){
    console.log('Lost MongoDB connection...');
    connect();
});
mongoose.connection.on('connected', function() {
    console.log('Connection established to MongoDB');
});

mongoose.connection.on('reconnected', function() {
    console.log('Reconnected to MongoDB');
});

// Close the Mongoose connection, when receiving SIGINT
process.on('SIGINT', function() {
    mongoose.connection.close(function () {
        console.log('Force to close the MongoDB conection');
        process.exit(0);
    });
});
```

It can connect to the `MongoDB` successfully after starting. However, when I stop `MongoDB` first, then try to stop the node application through `Ctrl+C` under window. The node application failed to stop, and output the `Lost MongoDB connection...` continually. Until I restart `MongoDB`, the node application can stop, and logs are as below

```
Lost MongoDB connection...
Lost MongoDB connection...
Lost MongoDB connection...
Connection established to MongoDB
Connection opened to MongoDB
Lost MongoDB connection...
Force to close the MongoDB conection 
```

It seems the `SIGINT` is blocked by disconnected event of mongoose.

**Am I right? Could someone help figure out what's wrong with my codes?**

Node version: v0.12.7

Mongoose version: 3.8.24

**Comment by vkarpov15** [comment]
First of all, `mongoose.connection.close()` waits for you to be successfully connected before closing the connection. Slightly weird, but not too bad. Your real problem is that the `connect()` call in the `on('disconnected')` handler is triggering an infinite loop, `connect()` fails and so `on('disconnected');` is fired again. Why are you calling `connect();` there when you have `auto_reconnect` on?

**Comment by richzw** [comment]
If my apps starts with `mongoDB` stopped, it will exit directly rather than trying to reconnect to `mongoDB` continuously. So the `connect()` is invoked in the `disconnected` event. 

I am not sure whether it is the correct way to implement it or am I missing something?

**Comment by vkarpov15** [comment]
The behavior that "if you fail to initially connect, it'll throw an error" is pretty deeply baked into the mongodb driver, mongoose doesn't really do anything about that. You could try only calling `connect()` function in your 'disconnected' handler if you haven't seen a 'connected' event yet.

**Comment by richzw** [comment]
@vkarpov15 thanks for your advice, it can solve my issue. However, as the `connect()` function is invoked in the `disconnected` handler, it can cause the infinite loop as you mentioned before. 

I am still confused that why the `SIGINT` signal could be blocked by the infinite loop in the `disconnected` handler? 

Based my understanding, there is one event queue in the `Node.js`, all events could be put into this queue, and then be processed one by one. Due to the infinite loop here, the `disconnected` event will be added into this queue continuously. The `SIGINT` event will be blocked by it?

Could you please give more information about it?

**Comment by vkarpov15** [comment]
Can't handle events if the event loop is blocked, and that's what's happening when you're calling `connect()` in the 'disconnected' handler.

**Comment by kenyramses** [comment]
you can add a timeOut in order to stop manually the  node server like this:
setTimeout(function () {
            connect();
        }, 5000);

**Comment by Composur** [comment]
`
const db= mongoose.connection
const isConnectedBefore=false

db.on('open',function(){
    log('connection established to mongodb')
    isConnectedBefore=true
})

db.on('disconnect',function(){
    log('lost mongodb connect...')
    if(!isConnectedBefore){
        mongoConnect()
    }
})`
I'm not sure if that's right.
