### ISSUE TITLE
mongoose.Types.ObjectId() successfully returns a valid ObjectId from an invalid input string 

### ISSUE THREAD

**Issue by Qrysto** [Automattic/mongoose#3541]
I'm using ObjectId() to check if a provided string is a valid ObjectId in my project. Most of the time it works as expected, but surprisingly in a case it gives an unexpected result (not sure if there're other similar cases).

With Mongoose@4.2.4, given a test 

```
var mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;

function toObjectId(idStr) {
   var id = null;
   try {
       id = ObjectId(idStr);
   } catch(err) {}

   return id;
}
```

`toObjectId('cay-sua-cafe')` returns a valid ObjectId `6361792d7375612d63616665`. With most of other random strings it returns null (ObjectId() throws an error). Is this a bug or a feature? :laughing:

**Comment by vkarpov15** [comment]
It's a feature, see https://github.com/mongodb/js-bson/issues/112. An ObjectId is a 12-byte structure which we usually express as a 24 character hex string, so if you give it a string of length 12 that's a perfectly valid 12 bytes. If you want to make sure it's a 24 char hex string, just use a regexp like `/[a-f0-9]{24}/i`
