### ISSUE TITLE
Pre update hook not updating field correctly

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3549]
See https://github.com/Automattic/mongoose/issues/964#issuecomment-154743584

**Comment by vkarpov15** [comment]
Hey @willemmulder, only issue I can find with your code in #964 is that `hashSync()` takes 2 arguments re [bcrypt docs](https://www.npmjs.com/package/bcrypt#sync). Other than that, the below code works for me.

```javascript
var assert = require('assert');
var bcrypt = require('bcrypt');
var mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3549');

var Schema = mongoose.Schema;

var schema = new Schema({ password: String });

schema.pre('update', function(next) {
  this.update({}, { password: bcrypt.hashSync(this.getUpdate().$set.password, 8) } );
  console.log(this.getUpdate());
  next();
});

var Model = mongoose.model('test', schema);

Model.update({}, { password: 'a1b2c3' }, function(error) {
  assert.ifError(error);
  console.log('done');
  process.exit(0);
});
```

Output:

```
$ node gh-3549.js 
{ '$set': { password: '$2a$08$cFFggOw/sGO6pHWhbpWaDetFvV9OlAxH/d6OYCtj0N0sI1upr2VN.' } }
Mongoose: tests.update({}) { '$set': { password: '$2a$08$cFFggOw/sGO6pHWhbpWaDetFvV9OlAxH/d6OYCtj0N0sI1upr2VN.' } } {} 
done
```

Can you see if you can modify the given script and see if you can reproduce your issue?

**Comment by willemmulder** [comment]
Hi @vkarpov15, so I get the same results as you get. 

BUT if I change the latter part to 

```
Model.update({}, { password: 'a1b2c3' }).exec(function(error) {
	assert.ifError(error);
	console.log('done');
	process.exit(0);
});
```

So changing it into using the `.exec` method, then I get the same error as I got before. Could you try that as well?

**Comment by willemmulder** [comment]
Whew that was fast; thanks! :-)

**Comment by ztrange** [comment]
Hi, @vkarpov15 I think I found a small problem:

I was trying to run code very similar to that of the OP:

```
  schema.pre('findOneAndUpdate', function(next) {
    debug('pre findOneAndUpdate')
    debug(this.getUpdate())
    this.update({}, {email: 'test@test.com'})
    debug(this.getUpdate())
    next()
  })
```

But it wasn't working with any of these ways:
`this.update({}, {email: 'test@test.com'})`
`this.update({}, {$set: {email: 'test@test.com'}})`

So I finally found the problem:

The original object that I passed to my update was:

```
Customer.findOneAndUpdate(
      {_id: customer.id},
      {
        'name.first': 'John',
        'name.last': 'Doe',
        email: 'john@test.com',
        array: [ 1, 2, 3 ]
      },
      {runValidators: true, new: true},
      (err, c) => {
        if (err) {
          console.log(err)
        }

        console.log(c)
        t.end()
      }
    )

```

So when the pre update middleware ran, What happened was:

```
  schema.pre('findOneAndUpdate', function(next) {
    debug('pre findOneAndUpdate')
    debug(this.getUpdate())
    // { 'name.first': 'Jonh', 'name.last': 'Doe', email: 'john@test.com', array: [ 1, 2, 3 ] }
    this.update({}, {email: 'test@test.com'})
    debug(this.getUpdate())
    // { 'name.first': 'John', 'name.last': 'Doe', email: 'john@test.com', array: [ 1, 2, 3 ], '$set': { email: 'test@test.com' } }
    next()
  })

```

And the result was email containing 'john@test.com' instead of being overwritten as: 'test@test.com' after the update to the document

So, I finally found a workaround by doing the original update as:

```
Customer.findOneAndUpdate(
      {_id: customer.id},
      {$set: {
        'name.first': 'John',
        'name.last': 'Doe',
        email: 'john@test.com',
        array: [ 1, 2, 3 ]
      }},
      {runValidators: true, new: true},
      (err, c) => {
        if (err) {
          console.log(err)
        }

        console.log(c)
        t.end()
      }
    )

```

And with that, it doesn't matter if I do the this.update() call on the hook in either form, both work fine:

`this.update({}, {email: 'test@test.com'})`
`this.update({}, {$set: {email: 'test@test.com'}})`

Hope this helps someone

**Comment by vkarpov15** [comment]
You should use `this.findOneAndUpdate()`. If you use `this.update()`, I'm pretty sure you'll change the `findOneAndUpdate()` to an `update()`

**Comment by ztrange** [comment]
You are uterly, totally and completely right... :) Thanks

**Comment by zilions** [comment]
I'm trying to set a property to have the `length` of an array.

```
schema.post('findOneAndUpdate', function(result) {
	console.log(result.comments.length);
	this.findOneAndUpdate({}, { totalNumberOfComments: result.comments.length });
});
```

The correct length is logged, although the query never sets `totalNumberOfComments`, and the field stays at `0` (since the schema references `default: 0`).

Is there something I'm doing wrong, or is this a bug?
