### ISSUE TITLE
$pull will remove all sub-documents if the _id is undefined

### ISSUE THREAD

**Issue by Herobs** [Automattic/mongoose#3550]
document(test):

    {
      "_id" : 1,
      "results" : [
          { "_id" : "1", "content" : "foo" },
          { "_id" : "2", "content" : "bar" }
       ]
    }

operation:

    test.findOneAndUpdate({
        _id: 1
    }, {
        $pull: {
            results: {
                _id: undefined
            }
        }
    });

results will be an empty array if the _id is undefined.

**Comment by vkarpov15** [comment]
Which version of mongoose is this? Think this should've been fixed in a recent release.

**Comment by Herobs** [comment]
version `4.0.8`

**Comment by vkarpov15** [comment]
Yeah this is related to #3260, etc. by way of https://github.com/mongodb/js-bson/commit/c19734d907bcd8e4f32f906b414ea09f55df341c. Try upgrading to 4.2.4, this issue should go away.

**Comment by Herobs** [comment]
This problem resolved when I upgrade to version 4.2.4, thx.
