### ISSUE TITLE
Mongoose does not reconnect if DB is down for more than 30 sec

### ISSUE THREAD

**Issue by yangit** [Automattic/mongoose#3552]
Given this simple code:
````
var mongoose = require('mongoose');

var options = {
  server: {socketOptions: {keepAlive: 1, connectTimeoutMS: 30000}}
};
mongoose.connect('mongodb://127.0.0.1/test', options);
var db = mongoose.connection;

['close', 'disconnected', 'disconnecting', 'connected', 'connecting', 'reconnected', 'open', 'error'].forEach(function (event) {
  db.on(event, function () {console.log(event);});
});

var Cat = mongoose.model('Cat', {name: String});

var counter = 0;

var saveKitty = function () {
  var n = counter++;
  var kitty = new Cat({name: n});
  kitty.save(function (err) {
    if (err) {
      console.log('Error saving:', n, err);
    } else {
      console.log('Saved:', n);
    }
  });
};


setInterval(saveKitty, 5000);
saveKitty();
````

If I run above code it will save Kitty into DB every 5 sec.
If I shutdown local mongo instance I will get `close` and `disconnected` event fired and errors with start to pop up `MongoError: topology was destroyed` and that is fine.
If I restart mongodb server within 30 sec mongoose will reconnect and any subsequent saves will be fine.
However if I fail to restart mongoDB server within 30 sec I will get second `close` event fired (`disconnect` is not fired again) and from that point mongoose will never reconnect again regardless of mongoDB server status.

Is that expected behavior? How to check if mongoose is going to reconnect or not, and force it to?

**Comment by yangit** [comment]
This is mongoose v 4.2.4

**Comment by vkarpov15** [comment]
@yangit by default, on disconnect, the mongodb driver will try to reconnect every second up to 30 times, and then give up. You can set the [`server.reconnectTries` and `server.reconnectInterval` options to configure this behavior](http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html). For instance,

```javascript
// Attempt to reconnect every second for up to 24 hours
mongoose.connect('mongodb://localhost:27017/test', { server: { reconnectTries: 60 * 60 * 24, reconnectInterval: 1000 } });
```
