### ISSUE TITLE
Enable custom functions for logging

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#3557]
debug support

```javascript
mongoose.set('debug', true, function (coll, method, query, doc) {
    log.debug('query executed:', coll, method, query, doc);
});
```

works for this query

```javascript
    Model.update(conditions, data, opts, function (err, result) {

    });
```

but not for this:

```javascript
    Model.update(conditions, data).lean(true).limit(30).exec(err, result) {

    });
```

I assume that in general debugging support is not currently available for exec() style queries, is there a good reason for this? Would be nice to have support for it

**Comment by vkarpov15** [comment]
The below script

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh3557');

var Model = mongoose.model('gh3557', { name: String });

Model.update({}, { name: 'Val' }).lean().limit(30).exec(function(error, result) {
  console.log('done', error);
  process.exit(0);
});
```

gives me the expected output, query is logged just fine. We do have debugging support for `.exec()`.

```
$ node gh-3557.js 
Mongoose: gh3557.update({}) { '$set': { name: 'Val' } } { limit: 30 } 
done null
```

although you might want to know that `.lean()` and `.limit()` have no effect with `.update()`. Also, I don't know why you're passing a third argument to `mongoose.set()`, [that behavior is unsupported and passing a third argument to `mongoose.set()` has no effect](http://mongoosejs.com/docs/api.html#index_Mongoose-set).

**Comment by ORESoftware** [comment]
yes, you may be right, although for some reason my experience dictated otherwise

nevertheless, creating this functionality

```
mongoose.set('debug', true, function (coll, method, query, doc) {
    log.debug('query executed:', coll, method, query, doc);
});
```

would allow the consumer of your lib to redirect the logging out put through the logging library of their choice. at the moment, without that 3rd arg (the callback), the consumer of your lib has no control regarding how the logging output is formatted or where it's piped to, etc.

**Comment by vkarpov15** [comment]
That's a good feature request. There are some ways to do this - in theory, `mongoose.set('debug', function() {});` works, but that's not tested or documented anywhere. I'll track that in this ticket.

**Comment by ORESoftware** [comment]
alright thanks

**Comment by ORESoftware** [comment]
@vkarpov15 sorry to bug you, can you confirm this works? the exact feature I was looking for was so that if you passed the callback function, it wouldn't log at all, except for the logic/logging you put in your own defined callback

**Comment by vkarpov15** [comment]
Try

```javascript
mongoose.set('debug', function (coll, method, query, doc) {
        log.debug('query executed:', coll, method, query, doc); //note: this callback doesn't execute yet, but it's in their issue inbox on Github
    });
```

The 2nd param should be the function. If the 2nd param is true, mongoose will just use its default 'log to console' behavior. [See docs](http://mongoosejs.com/docs/api.html#index_Mongoose-set)

**Comment by ORESoftware** [comment]
ok thanks! yeah

**Comment by ORESoftware** [comment]
so much better, this is great
