### ISSUE TITLE
findById require ObjectId

### ISSUE THREAD

**Issue by michelem09** [Automattic/mongoose#3563]
Hello,
I have just upgraded from 3.8 to latest 4.x and I found any query like `findById` now requires the `id` to be an `ObjectId` while before it worked with string ids.
Can you confirm this behaviour in the newest version? I can't find any reference to this and I would be sure before change a lot of code in my app.
Thanks

**Comment by vkarpov15** [comment]
Nope, this behavior has definitely not changed in 4.x, it's a very core part of how mongoose works. Can you show me a code sample that reproduces the issue you're seeing?

**Comment by michelem09** [comment]
With 3.8.34 I did:

    Catalog.findById(id, function(err, product) {
       if (err) return next(err);
       if (!product) return next(new Error('Failed to load product ' + id));	
    });

With `id` as string and it worked.

Now (4.2.4) I have to do this:

    Catalog.findById(mongoose.mongo.ObjectID(id), function(err, product) {
       if (err) return next(err);
       if (!product) return next(new Error('Failed to load product ' + id));	
    });

**Comment by vkarpov15** [comment]
What does your catalog schema look like? Does it have a custom _id field?

**Comment by michelem09** [comment]
Here is my problem, I wrote this in the schema, to exclude the _id from mongoosastic:

    _id: { es_indexed: false }

But this is wrong because it should be:

    _id: { type: Schema.ObjectId, es_indexed: false }

Thanks for your time
