### ISSUE TITLE
Missing dependancy for Cloud9 Installation

### ISSUE THREAD

**Issue by marktyers** [Automattic/mongoose#3566]
Installation fails unless `libkrb5-dev` is installed. Should this be flagged as a dependency?

http://stackoverflow.com/questions/33539407/installation-of-mongoose-on-cloud-9-fails/33646233#33646233

**Comment by vkarpov15** [comment]
Installation does **not** fail. Notice that the npm exit status is 0 and npm still outputs the dependency tree. `kerberos` is an optional dependency.
