### ISSUE TITLE
What is the recommended way to populate some of a model's attributes automatically based on provided attributes?

### ISSUE THREAD

**Issue by lgomez** [Automattic/mongoose#3568]
Hi all,

I'm writing some models that contain attributes for which values come from external services. These values are fetched from those services using some attributes provided by the instantiator of the model. I'll give you an example:

A Location model. The user will provide an address string and, optionally, a zipcode. If we don't get a zipcode, we use a service to get it from the address. Once we do have the zipcode, we use a different service to get the country and state codes. To illustrate:

```javascript
var location = new Location({
    "address": "123 main st",
    "zipcode": "90210"
});
```
Now, BEFORE saving, I need to trigger a an HTTP call that fetches the state and country codes so I can do:
```javascript
console.log(location.state); // to check the state code
console.log(location.country); // to check the country code
```
I suspect the answer is in a post init hook but an example would be awesome because I haven't been able to get it to work. Any ideas?

Keep in mind that I may or may not need to check those values so it is possible that I would be calling `save()` immediately after instantiating... Which tells me there may be a race condition there where `save()` may be called before the country and state codes are received from the external services.

Thank you in advance.

**Comment by lgomez** [comment]
I've been reading a bit more of the docs and perhaps a schema type default function is more appropriate for what I'm looking for? But then I'm not entirely sure what happens if this function takes longer than expected...

**Comment by vkarpov15** [comment]
Try a [pre save hook](http://mongoosejs.com/docs/middleware.html). Functions passed to schema defaults need to be synchronous, so that won't quite work.
