### ISSUE TITLE
Bluebird 3.0.5 Promises : warning about handler not returning a promise

### ISSUE THREAD

**Issue by BenjaminBini** [Automattic/mongoose#3570]
Hi,

I use bluebird promises with Mongoose (by setting `mongoose.Promise = require('bluebird')`) and since the last version of bluebird (3.0.5) [a new warning](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it) is triggered when a Promise is created in a handler but nothing is returned from it : 

``` bash
Warning: a promise was created in a  handler but was not returned from it
    at Query.exec (C:\benjamin\dil\node_modules\mongoose\lib\query.js:2125:10)
    at Query.then (C:\benjamin\dil\node_modules\mongoose\lib\query.js:2155:15)
    at model._hasBeenAnswered (C:\benjamin\dil\server\models\question.model.js:47:6)
```

The corresponding lines :

```javascript
Query.prototype.exec = function exec(op, callback) {
  var Promise = PromiseProvider.get();
  var _this = this;

  if ('function' == typeof op) {
    callback = op;
    op = null;
  } else if ('string' == typeof op) {
    this.op = op;
  }

  return new Promise.ES6(function(resolve, reject) { // 2125
    if (!_this.op) {
      callback && callback(null, undefined);
      resolve();
      return;
    }

    _this[_this.op].call(_this, function(error, res) {
      if (error) {
        callback && callback(error);
        reject(error);
        return;
      }
      callback && callback.apply(null, arguments);
      resolve(res);
    });
  });
};

/**
 * Executes the query returning a `Promise` which will be
 * resolved with either the doc(s) or rejected with the error.
 *
 * @param {Function} [resolve]
 * @param {Function} [reject]
 * @return {Promise}
 * @api public
 */

Query.prototype.then = function(resolve, reject) {
  return this.exec().then(resolve, reject); // 2155
}
```

The line from my code is this one : 

```javascript
return User.find({username: username})
    .then(....
```

**Comment by vkarpov15** [comment]
The below script works fine for me with bluebird 3.0.5 and mongoose 4.2.5:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.Promise = require('bluebird');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh3570');

var User = mongoose.model('User', { name: String });

User.find().then(function(error) {
  console.log('error', error);
  process.exit(0);
});
```

No warnings logged. Which version of mongoose are you using?

**Comment by BenjaminBini** [comment]
My bad, I had an issue in my own code causing this issue. 

I still do not really understand why the stacktrace was refering to mongoose code but whatever.

Thanks!

**Comment by fkenji** [comment]
Not sure if this might shed more light to the issue, but in my case I had the same warning and apparently it was because I was returning the `next()` function (which comes from express.js) within the promise. 

I.e:
```
app.use(function (req, res, next) {
  User
    .find({_id: id})
    .then(function (user) {
      return next();
    });
});
```

Changing it to
```
app.use(function (req, res, next) {
  User
    .find({_id: id})
    .then(function (user) {
      next();
      return null;
    });
});
```

fixed it. So maybe returning `next()`  put off Bluebird's detection of no values being returned from a promise, since it was actually looking at a express middleware / route which I think  doesn't return any values.

That said, the reason that the stacktrace was pointing to Mongoose might be because it was the first call I have made in the http request.
