### ISSUE TITLE
pre save middleware have no document and example do not match document.

### ISSUE THREAD

**Issue by imane-jym** [Automattic/mongoose#3573]
document:
http://mongoosejs.com/docs/middleware.html
```javascript
var schema = new Schema(..);
schema.pre('save', function(next) {
  // do stuff
  next();
});
```

example:
https://github.com/Automattic/mongoose/blob/master/examples/schema/schema.js

```javascript
BlogPost.pre('save', function(next, done) {
  /* global emailAuthor */
  emailAuthor(done); // some async function
  next();
});
```

about callback para done is not equal in two examples.
I can not find document about this callback parameters.

**Comment by vkarpov15** [comment]
http://mongoosejs.com/docs/middleware.html has some details about it, just look for 'parallel'

**Comment by imane-jym** [comment]
Parallel

Parallel middleware offer more fine-grained flow control.

var schema = new Schema(..);
schema.pre('save', true, function(next, done) {
  // calling next kicks off the next middleware in parallel
  next();
  setTimeout(done, 100);
}

There are three parameters and second parameters is true. but there are just two parameters and I can not found true parameter in the example.
