### ISSUE TITLE
select: false, but returns that field on save()

### ISSUE THREAD

**Issue by sincerekamal** [Automattic/mongoose#3574]
Hi,

I have schema below,
````
var userSchema = new Schema({

	"_id": String,
	"username": String,
	"password": {type: String, required: false, "default": "", select: false}
});

````

When I perform ````find()````, ````findOne()```` operation, it works as expected. i.e it's not returning the password field. But when I create a new user using ````save()````, in the success callback I get the user details including that <b>password</b> field.

**Comment by vkarpov15** [comment]
Because `save()` doesn't actually execute a query against mongodb, it just gives you back the same document you called `.save()` on, so `doc.save(function(error, _doc) { assert.ok(doc === _doc); }` is true. Execute a separate `find()` to get back a doc with the password field hidden.
