### ISSUE TITLE
Using isomorphic mongoose with webpack

### ISSUE THREAD

**Issue by patterncoder** [Automattic/mongoose#3578]
I am getting the following warning and then a bunch of "Module not found errors" when packing my project:
```
WARNING in ./~/mongoose/lib/drivers/index.js
Critical dependencies:
9:11-74 the request of a dependency is an expression
 @ ./~/mongoose/lib/drivers/index.js 9:11-74

WARNING in ./~/mongoose/lib/drivers/SPEC.md
Module parse failed: C:\development\banquetninja\node_modules\mongoose\lib\drivers\SPEC.md Line 2: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| 
| # Driver Spec
| 
| TODO
 @ ./~/mongoose/lib/drivers ^\.\/.*$
```
Webpack seems to failing on the following code in ./~/mongoose/lib/drivers/index.js:

```
var driver;

if (typeof window === 'undefined') {
  console.log('global: ' + global.MONGOOSE_DRIVER_PATH);
  driver = require(global.MONGOOSE_DRIVER_PATH || './node-mongodb-native');
} else {
  driver = require('./browser');
}
```

If I force driver = require('./browser') and skip the window conditional everything works but this is a horrible hack.  I believe the answer lies in webpack.config but have been unable to find a solution.

Thanks for any help you can provide.

**Comment by vkarpov15** [comment]
I'm not terribly familiar with webpack, but other people have managed to get it working re: #2900. Why is webpack trying to load markdown files?

**Comment by utkuturunc** [comment]
I am having the same issue. @patterncoder did you ever solve this?

**Comment by patterncoder** [comment]
No I sure didn't.  Since I wanted to get mongoose working in the browser and not abandon webpack, nor keep banging my head against the wall I kept a local copy of mongoose and modified the code...a horrible hack!

driver = require('./browser') 

The more I thought about this it is really a webpack issue, but never got it resolved.  If you get any further let me know.

**Comment by utkuturunc** [comment]
Adding node-loader to webpack with

```
      { test: /\.node$/, loader: 'node' },
```

and

```
    extensions: [ '', '.js', '.json', '.jsx', '.es6', '.babel', '.node' ],
```

solves some of the errors. Also adding 
```
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

solves module not found errors. Then I am left with the very same warnings you have. They don't break anything so I guess I will keep on working and ignore warnings.

**Comment by myknbani** [comment]
https://github.com/Automattic/mongoose/blob/master/lib/schema.js

looks like schema pulls in some unwanted files

**Comment by id0Sch** [comment]
Hi,
i've been trying to get mongoose to work with webpack for hours now.
the build works but when i run the code it fails with `Cannot find module './node-mongodb-native'.`
any ideas on how to solve it ?
none of the above solutions fixed it.
here is my webpack.config.js

``` javascript
var webpack = require('webpack');
var path = require('path');

module.exports = {
    entry: './index.js',
    target: 'node',
    output: {
        path: './lib',
        filename: 'index.js',
        libraryTarget: 'commonjs2'
    },
    externals: {'aws-sdk': 'aws-sdk'},
    plugins: [
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("development")
            }
        }),
    ],
    resolve: {
        extensions: ["", ".json", ".node", ".js"],
        modulesDirectories: ['node_modules', 'app']
    },
    module: {
        noParse: [/node_modules\/json-schema\/lib\/validate\.js/, /node_modules\\json-schema\\lib\\validate\.js/],
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: [/node_modules/]
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            },
            {
                test: /\.node$/,
                loader: "node-loader"
            }
        ]
    }
};
```
