### ISSUE TITLE
Validation doesn't work on subschemas

### ISSUE THREAD

**Issue by tvoloshyn** [Automattic/mongoose#3580]
Hi everyone,

I think I've found a possible issue with validation when it comes to sub-schemas. Below is a scenario in which validation doesn't seems to work for me.

I have the following schemas in my project:
```javascript
	var valueSchema = new Schema(
	{
		_id: false,
		"value" 		: {type: Number, required: true},
		"updatedAt"  	: {type: Date}
	});

	var schema = new Schema(
	{
		"field"		:  	{ type: Schema.Types.ObjectId, ref: "Field", required: true},
		"operator"	:  	{ type: Schema.Types.ObjectId, ref: "User", required: true},
		"measure" 	: 	{ type: String, required: true},
		"in" 		: 	{
							_id: false,
							"value" 		: {type: Number, required: true},
							"updatedAt"  	: {type: Date}
						},
		"out" 		: 	{ type: valueSchema, required: false},
		"note" 		:  	{ type: String, trim: true}
	});
```

For demonstration/testing purposes I've made `in` field a sub-**document** and `out` sub-**schema**.

I use `findOneAndUpdate` to perform an update with following `options`:
```javascript
{ "runValidators": true, "new" : true }
```

And here is what I pass in for `update`:
```javascript
{
	field: '5640a8e9910d6b1c22900ba7',
	operator: '563cae72d210b6d40aaea242',
	measure: 'kg',
	in: { value: 600 },
	out:{ value: 'Not A Number' },
	note: 'This is just an update note'
}
```

Output (`updatedAt` are added "automatically"):

```javascript
{
    "_id": "564b46f7a271258c1d1e9156",
    "field": "5640a8e9910d6b1c22900ba7",
    "measure": "kg",
    "note": "This is just an update note",
    "operator": "563cae72d210b6d40aaea242",
    "__v": 0,
    "out": {
      "updatedAt": "2015-11-17T15:40:19.887Z"
    },
    "in": {
      "value": 600,
      "updatedAt": "2015-11-17T15:40:19.887Z"
    }
  }
```
I was expecting a validation error to be thrown for `out.value`.

Changing `in.value` to a `String` does throw a validation error, which makes me think that validation isn't working for sub-schema(s). At least in the above scenario.

Here is what I use:
* **Mongoose** : 4.2.6
* **Node.JS** : 4.2.0
* **MongoDB**: 3.0.7

**Comment by vkarpov15** [comment]
So the fact that this doesn't throw a cast error is a bug, fixed in 1e6047b. However, there's also a related issue, #3587, that's been outstanding for a while with update validators that you may want to watch out for.
