### ISSUE TITLE
Reconnection issue

### ISSUE THREAD

**Issue by boysmovie** [Automattic/mongoose#3583]
I have mongodb setup as standalone server. I also have replicaset enabled as standalone for enabling the oplog (my app tracks realtime updates).

When mongod service is stopped and restarted mongoose auto-reconnects but throws an error when performing write operation. (I understand mongodb cannot write to secondary but I just have one node which is PRIMARY but mongoose thinks its secondary?

--
d:\project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:18
67
  if(!connection.isCompatible()) {
                 ^
TypeError: Object Error: Cannot write to a secondary has no method 'isCompatible

**Comment by vkarpov15** [comment]
When the mongod restarts, it can take a few seconds for it to realize that it's a primary. Is this error a temporary condition or does it persist?

**Comment by aanuprab** [comment]
@vkarpov15  - From what I am noticing, after mongod restarts, if the next write request happens after 4 to 5 seconds, I do NOT see this crash. But if the next write request happens very soon within a second or so - crash!

My webapp has heavy load which mean the next write op can happen within a second.

To further this question:

1. I have mongoose on-error event. Why doesn't mongoose call this rather it crashes the app?

	// If the connection throws an error
	mongoose.connection.on('error',function (err) {
		console.log('MongoDB error!');
	});


2. When mongoose re-connects, can't it connect only to a node that mongod has made it the PRIMARY?

**Comment by vkarpov15** [comment]
I remember there being some related issues fixed in subsequent 3.8 releases. Could you upgrade to 3.8.37 and see if the issue still happens?
