### ISSUE TITLE
runValidators should handle objects and $set more intelligently

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3587]
Right now with a schema like:

``` javascript
new Schema({
  nested: { a: { type: String, required: true }, b: String }
});
```

`.update({}, { nested: { b: 'test' } });` will succeed because updateValidators flatten aggressively until they find a primitive.

**Comment by kotarou3** [comment]
Does the following code hit the same bug as this?

```js
"use strict";

const mongoose = require("mongoose");
mongoose.connect("localhost/test");

const schema = new mongoose.Schema({
    a: {
        type: {
            a: {
                type: String,
                required: true
            },
            b: {
                type: String,
                required: true
            }
        },
        required: true
    }
});

const Test = mongoose.model("Test", schema);
Test.create({a: {c: "test"}}).then(function (record) {
    console.log(record.validateSync()); // undefined
    console.log(record); // Seems to have properly saved (note: not meant to)
}).catch(e => console.log(e));
```

**Comment by vkarpov15** [comment]
No, you aren't using update validators. The issue is that your schema is wrong: the `a` field is of mixed type (unintentionally). See the [`typeKey` option on schemas](http://mongoosejs.com/docs/guide.html#typeKey) for how to fix this.

**Comment by kotarou3** [comment]
I changed the `type` properties to `$type` and added `typeKey: "$type"` but now I'm getting:
```
TypeError: Undefined type `undefined` at `a.$type.a.required`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/tmp/node_modules/mongoose/lib/schema.js:598:11)
```

Does this mean that mongoose doesn't support the "easy" way of nesting objects and having them validated? Or am I still doing something wrong?

Note that the intention is that `record.a` is a required object, and that `record.a.a` is a required string.

**Comment by vkarpov15** [comment]
Yeah mongoose doesn't really support `required` on nested objects. If you need that functionality, use [single embedded subdocs](http://mongoosejs.com/docs/subdocs.html#single-embedded) instead.

**Comment by kotarou3** [comment]
Should I add that as a feature request then?

**Comment by vkarpov15** [comment]
Sure. In the meantime, single embedded subdocs work well for this case.
