### ISSUE TITLE
Disconnect event not firing

### ISSUE THREAD

**Issue by boysmovie** [Automattic/mongoose#3590]
I upgraded to mongoose 4.2.6 and when mongodb shutsdown, I expected the disconnect event to fire but it does not. Only the reconnect fires.

It looks like the same issue https://github.com/Automattic/mongoose/issues/3183

Was this fix moved to 4.2.6?

**Comment by vkarpov15** [comment]
Listen for the `close` event instead.

```javascript
var mongoose = require('mongoose');

var Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh3590');

mongoose.connection.on('close', function() {
  console.log('closed');
});

mongoose.connection.on('reconnected', function() {
  console.log('reconn');
});
```

**Comment by aanuprab** [comment]
@vkarpov15  close does not fire either!

**Comment by vkarpov15** [comment]
Works fine for me:

```
$ node gh-3590.js 
closed
reconn
closed
reconn
```

Can you clarify your version of mongodb, whether you're using a standalone mongod or replica set or sharded cluster, and try the above script to see if it work for you?

**Comment by aanuprab** [comment]
@vkarpov15 i am on mongoose 4.2.6, mongodb 2.6.5 and I have mongodb setup as standalone server. I also have replicaset enabled as standalone for enabling the oplog (my app tracks realtime updates).

If mongodb is standalone the close event is firing. But if its replicaset close event does not fire.

**Comment by vkarpov15** [comment]
Replica sets handle closed events a little differently right now, they don't actually emit 'closed' events when a server dies. They probably should if they're not connected to a single server though, will investigate.

**Comment by vkarpov15** [comment]
Looks like this already works as far as I can tell, re-open if still an issue.

**Comment by khocef** [comment]
Hello,

```
// Connect Mongo database
mongoose.connect(config.mongo.uri, config.mongo.options);

var events = ['connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close', 'reconnected', 'error'];
events.forEach(function (event) {
  mongoose.connection.on(event, function () {
    console.log(event);
  });
});
```


The problem is that mongoose doesn't fire any event when i kill mongodb terminal. 

I'm using a standalone mongod
Node v4.4.5
db version v2.2.7, pdfile version 4.5

Any idea ?

Thanks.

**Comment by vkarpov15** [comment]
Which version of mongoose? Also, you're using mongodb 2.2?

**Comment by khocef** [comment]
i'm using mongoose 4.5.9 and mongodb version 2.2.7 and also mongodb v 3.2.9.

**Comment by vkarpov15** [comment]
Funny, I'm getting the below output running your code:

```
$ node gh-3590.js 
connected
open
disconnected
close
connected
reconnected
disconnected
close
```

when killing off a mongodb 3.2.10 instance in the background. By "kill mongodb terminal" do you mean kill the terminal window in which the mongod instance is running, kill the mongodb shell, or something else entirely?
