### ISSUE TITLE
All indexes missing for single subdocument

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3594]
With mongoose 4.2.6, all indexes are missing for a single subdocument, e.g.:
```javascript
var jobSchema = new mongoose.Schema({
  title: {type: String, unique: true}
});

var personSchema = new mongoose.Schema({
  name: {type: String, required: true},
  job: jobSchema,
});

var Person = mongoose.model('Person', personSchema);
```
Verifying with mongo shell:
```javascript
> db.people.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "test.people"
	}
]
```
I expect a `job.title` index in the output. Due to the missing index, uniqueness cannot be enforced (which leads to serious problems in our application).

**Comment by vkarpov15** [comment]
Confirmed issue, fix will be in 4.2.7 this afternoon.
