### ISSUE TITLE
Problem with queries being routed to Primary Only

### ISSUE THREAD

**Issue by adrian-ludwig** [Automattic/mongoose#3600]
Hi!

We have problem with readPreference. 90% of the work (queries, aggregations) are done on Primary, but readPreference is set to secondaryPreferred. Only queries that are manualy set to read from secondaries do so. Other queries should read readPreference from global config but they do not.

I'm using mongoose 4.2.6
Node 0.12.7 / 5.0.0

My configuration is:

connection string: 
```
mongodb://mongo01.domain:27017,mongo02.domain:27017,mongo03.domain:27017/dbName
```

options:
```
{ server: 
	{ socketOptions: { keepAlive: 1, connectTimeoutMS: 30000, socketTimeoutMS: 0 },
	  auto_reconnect: true },
	replset: 
	{ readPreference: 'secondaryPreferred',
	  rs_name: 'repl0',
	  poolSize: 10,
	  socketOptions: { keepAlive: 1, connectTimeoutMS: 30000, socketTimeoutMS: 0 } } } }
```
Replica Set is build on top of 3 servers and in MongoDB Cloud Manager 

![image](https://cloud.githubusercontent.com/assets/1642500/11302033/2aa39a9e-8f9b-11e5-8638-43c1770e5a0b.png)
First column is Primary server

I have tried many different configurations but non of them give proper result.
In mongoose 3.8.x it was working fine.

**Comment by adrian-ludwig** [comment]
After some more digging I have changed connection stirng to:
```
mongodb://mongo01.domain:27017,mongo02.domain:27017,mongo03.domain:27017/eguard_master?replicaSet=repl0&slaveOk=true&readPreference=secondaryPreferred
```

But still only Primary Server is executing queries, not secondaries.

**Comment by vkarpov15** [comment]
Try explicitly specifying the readPreference in the connection string: `mongodb://mongo01.domain:27017,mongo02.domain:27017,mongo03.domain:27017/dbName?readPreference=secondaryPreferred`. I think `readPreference` is a db option, not a replset option. This distinction is very confusing, which is why I typically prefer to specify options in the connection string where possible.

**Comment by adrian-ludwig** [comment]
```
mongodb://mongo01.domain:27017,mongo02.domain:27017,mongo03.domain:27017/eguard_master?replicaSet=repl0&slaveOk=true&readPreference=secondaryPreferred
```

Do not work properly (readPreference is in uri)

**Comment by vkarpov15** [comment]
I see, you're going to need

```javascript
{ server: 
    { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000, socketTimeoutMS: 0 },
      auto_reconnect: true },
    replset: 
    { readPreference: 'secondaryPreferred',
      rs_name: 'repl0',
      poolSize: 10,
      socketOptions: { keepAlive: 1, connectTimeoutMS: 30000, socketTimeoutMS: 0 } } },
    db:
    { readPreference: 'secondaryPreferred' } }
```

mongoose is mistakenly using the legacy `read_preference` option when you specify `readPreference` in the query string. Will fix.

**Comment by adrian-ludwig** [comment]
It looks like it works!
Awesome! 
Thank you!

But still, it a bug of 4.x i think ;) Do you want help with bug fix ? I can make pull request.

**Comment by vkarpov15** [comment]
Yeah I made mongoose support `readPreference` properly in the connection string. Turns out the node driver also has this issue: https://github.com/mongodb/node-mongodb-native/pull/1311 . Thanks for pointing this out.
