### ISSUE TITLE
soft delete plugin

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3603]
General idea:

1) Add `isDeleted` to schema field, boolean, false by default.
2) Add pre hooks to query operations (`find`, `findOne`, `count`, `findOneAndUpdate`, `update`) that attach `isDeleted: false` unless an option is set.
3) Add a `.softDelete()` function that soft deletes this doc.

**Comment by aredo** [comment]
@vkarpov15 +1 for this. When plan to release this feature?

**Comment by vkarpov15** [comment]
No plan ATM, its not on the roadmap. It should be easy to implement, I just haven't had the cycles. You're more than welcome to take a stab at it though, [here's a blog post on how to write mongoose plugins](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) :)

**Comment by RobertWHurst** [comment]
Try my plugin => https://www.npmjs.com/package/mongoose-soft-remove
It works seamlessly with mongoose's API. Also provides filtering so soft removed items do not show up unless explicitly requested. It's fully tested and we use it at E-xact in production.

**Comment by GO-DIE** [comment]
Welcome to use soft delete plugin => [https://www.npmjs.com/package/soft-delete-mongoose-plugin](https://www.npmjs.com/package/soft-delete-mongoose-plugin)

A simple and friendly soft delete plugin for mongoose，implementation using TS.
Methods were added and overridden on mongoose model to realize soft deletion logic.
