### ISSUE TITLE
Multi-Tenancy Populate with UseDB

### ISSUE THREAD

**Issue by kheide** [Automattic/mongoose#3607]
Hi, 

So I have a default db connection that I run useDb() on per request based on a jwt token that is passed along from the user. When I intercept this token I run a function called initMultiTenancy() which switches the DB and loads all the Models. I do this by walking the models/schema directory and doing mongoose.model() on all of them and storing this on req.models (express). 

So far so good. I am able to do normal requests on all my endpoints. The problem arises when I try to populate. This is where I get the following error: 

```
MissingSchemaError: Schema hasn't been registered for model "Roles".
Use mongoose.model(name, schema)
```

This is even though its loaded on req.models just like the asking model that I am populating from. 

Does populate not care about which connection we are using so its trying to populate from the main mongoose.connection ? Or have I done something completely wack?

**Comment by kheide** [comment]
Seems like its solveable by doing this: 

```
req.models.users.find().populate('roles', 'name', req.models.roles).exec() 
```

Even though this seems abit complex to me. Why can't populate use the 'parent' connection when populating without having it specified?

**Comment by vkarpov15** [comment]
Having some trouble reproducing:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3607');
mongoose.set('debug', true);

var testSchema = new mongoose.Schema({ name: String });
var parentSchema = new mongoose.Schema({ test: { type: mongoose.Schema.Types.ObjectId, ref: 'Test' } });

var db2 = mongoose.connection.useDb('gh3607_0');

var Test = db2.model('Test', testSchema);
var Parent = db2.model('Parent', parentSchema);

Test.create({ name: 'test' }, function(error, test) {
  assert.ifError(error);
  Parent.create({ test: test._id }, function(error, p) {
    runTest(p._id);
  });
});

function runTest(id) {
  Parent.findOne({ _id: id }).populate('test').exec(function(error, doc) {
    assert.ifError(error);
    assert.equal(doc.test.name, 'test');
    process.exit(0);
  });
}
```

this works fine for me without error in 4.2.7

```
$ node gh-3607.js 
Mongoose: tests.insert({ name: 'test', _id: ObjectId("56537bef452a0d4657655cf0"), __v: 0 })   
Mongoose: parents.insert({ test: ObjectId("56537bef452a0d4657655cf0"), _id: ObjectId("56537bef452a0d4657655cf1"), __v: 0 })   
Mongoose: parents.findOne({ _id: ObjectId("56537bef452a0d4657655cf1") }) { fields: undefined }  
Mongoose: tests.find({ _id: { '$in': [ ObjectId("56537bef452a0d4657655cf0") ] } }) { fields: undefined } 
```

Can you try modifying this script and see if you can reproduce your issue?

**Comment by vkarpov15** [comment]
Issue's gone stale, re-open if this is still an issue.
