### ISSUE TITLE
_id:false vs. _id:true

### ISSUE THREAD

**Issue by the1mills** [Automattic/mongoose#3608]
_id:false is used on a schema to signify no ObjectId to be created by the mongo driver:

 ```_id: false```

as in  

```
 following: [{ // this user follows these users and topics
        _id: false,
        kind: {type: String},
    }],
```

but if I do this to be explicit

```
 following: [{ // this user follows these users and topics
        _id: true,
        kind: {type: String},
    }],
```

it gives me an error: 

```"undefined type 'undefined' at '_id'"```

which is just not good

to be consistent, would it be better to just allow the ```_id: true``` call?

I know it's not useful, but I like to be explicit sometimes, especially when toggling between whether or not to use an _id on property

thanks

**Comment by vkarpov15** [comment]
Don't know where you got that you disable mongoose's automatic `_id` creation by setting the `_id` schema path to false. [You need to set the `_id` option to false, not the schema path](http://mongoosejs.com/docs/guide.html#_id). The fact that `_id: false` works is really just an accidental side effect of laziness (might even qualify as a bug, but IMO not a big deal), it's not supported behavior.

**Comment by the1mills** [comment]
sorry I don't follow, would you mind showing a quick example?

**Comment by vkarpov15** [comment]
```javascript
following: [new Schema({ // this user follows these users and topics
  kind: {type: String},
}, { _id: false })]
```
