### ISSUE TITLE
Use ISO8601 representation for dates in toJSON() instead of Date object

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3609]
It would be nice if `toJSON()` would return ISO8601 strings for `Date` type fields (via the `toISOString()` method). Currently, `toJSON()` returns the raw Date object:

```js
var personSchema = new mongoose.Schema({
  name: String,
  birthday: Date
});
var Person = mongoose.model('Person', personSchema);
var dude = new Person({
  name: 'Jeffrey Lebowski',
  birthday: new Date('1942-12-04T00:00:00.000Z')
});
console.log(dude.toJSON());
console.log(dude.toJSON().birthday.toISOString());
```
Result:
```js
{ name: 'Jeffrey Lebowski',
  birthday: Fri Dec 04 1942 01:00:00 GMT+0100 (CET),
  _id: 5652114dadee5572571077c5 }
1942-12-04T00:00:00.000Z
```
Background: I use `toJSON()` in unit tests to check if a mongoose document contains a (JSON-parsed) object. Comparing objects with JSON-types is easy but my tests fail because a `Date` from the mongoose document is automatically converted via `toString()` and is compared against ISO8601. Note: `JSON.stringify` also uses ISO8601 via `toISOString()`.

I'm aware that the conversion can be achieved with transforms but I'd have to walk through all `Date` fields manually. It'd be nice if mongoose would support this out-of-the-box. What do you think?

PS: the name `toJSON` is misleading since the result is not JSON but an object.

**Comment by vkarpov15** [comment]
`toJSON` is meant to convert a mongoose doc into a POJO, I don't think it's the place to make decisions about what date format string to use. If `JSON.stringify()` is a use case you case about, you can just do `JSON.stringify(doc);`, which is equivalent to `JSON.stringify(doc.toJSON());` anyway.

I don't really like `toJSON` as a name either, but [that name is decided by the JS interpreter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior), not mongoose. If you don't like the name, `toObject();` works pretty similarly.

**Comment by andrenarchy** [comment]
@vkarpov15  Thanks for the clarification!

I ended up using `JSON.parse(JSON.stringify(doc))` for getting a representation with JSON types. If anyone knows a shortcut for this: please let me know! :)

**Comment by Spown** [comment]
> toJSON is meant to convert a mongoose doc into a POJO
> I don't really like toJSON as a name either, but that name is decided by the JS interpreter
> toJSON() behavior: If an object being stringified has a property named toJSON whose value is a function, then the toJSON() method customizes JSON stringification behavior: instead of the object being serialized, the value returned by the toJSON() method when called will be serialized. For example:

So, just to be clear: you've named the method after an expected by Interpreter method, that should return a serialized value (i.e. string, number, null or array/object containing the first 3 on the end nodes) but it returns some esoteric data format instead?

Brilliant, slow clapping.

P.S. I've just wasted 4 hours trying to find a bug in my module code that cuses data "to fall through" JSON conversion. Turns out its not a bug - it's a "feature".
