### ISSUE TITLE
Couldn't install optional dependency kerberos@~0.0

### ISSUE THREAD

**Issue by leaves4j** [Automattic/mongoose#3611]
mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
then I try to install kerberos

make: Entering directory '/home/xx/server/xx/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-22-generic
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3

**Comment by vkarpov15** [comment]
Not error, warning. Unless your mongodb server is configured to use kerberos authentication, ignore it.

**Comment by eremzeit** [comment]
I ran into this while building on Ubuntu.  I needed to install the headers for kerberos via...

`sudo apt-get install libkrb5-dev`

**Comment by mgnmpk** [comment]
I'm also getting same error. But I'm running my NodeJS application in container in CentOS.

**logErroressage: message:undefined stackTrace: MongoMissingDependencyError: Optional module `kerberos` not found. Please install it to enable kerberos authentication**

**Comment by vkarpov15** [comment]
@mgnmpk which version of mongoose are you using?

**Comment by mgnmpk** [comment]
@vkarpov15 I'm using mongoose": "^6.13.0

**Comment by vkarpov15** [comment]
And what version of Node.js and npm? Also, is this an error or a warning? AFAIK you shouldn't get an error unless you're trying to use Kerberos auth

**Comment by mgnmpk** [comment]
@vkarpov15 I'm getting error not warning because I'm usin kerberos authentication on mongoDB.
Using node ^20
npm^10

**Comment by vkarpov15** [comment]
Have you tried installing the [kerberos auth package](https://www.npmjs.com/package/kerberos)? Try `npm list kerberos` to check.
