### ISSUE TITLE
Version conflict with pre-existing version

### ISSUE THREAD

**Issue by crispen-smith** [Automattic/mongoose#3613]
Have been attempting to connect my app to a MongoLab sandbox account.

I've been able to log in via terminal but am unable to log in via the app.  MongoLab suppor tells me this is due to a legacy version of Mongoose within my app, however I've done `npm uninstall mongoose --save`, confirmed the uninstall and then done `npm install mongoose@4.2.7 --save`.   MongoLabs logs continue to suggest it's a version mismatch.

I've also confirmed that there is no global instance installed on this machine.

Is there any chance that it's holding on to earlier versions or conflicting with older versions buried in another app?

**Comment by vkarpov15** [comment]
Not terribly likely. Can you show me the output of `npm list | grep "mongoose"` and `npm list | grep "mongodb"`?

Also worth trying explicitly wiping out your `node_modules` directory and re-installing: `rm -rf node_modules && npm install`

**Comment by crispen-smith** [comment]
I'm going to close this as your suggestions were helpful; my app had been holding on to an older version due to a plugin that I was using on top of Mongoose proper, but that doesn't seem to have resolved the connection issue.
