### ISSUE TITLE
Switch collection at runtime

### ISSUE THREAD

**Issue by devvit** [Automattic/mongoose#3614]
Hi, guys, I wanna implement dynamic collection, consider schemas like these:
```coffeescript
mongoose = require 'mongoose'
mongoose.connect 'mongodb://localhost/test_dev'
db = mongoose.connection

userSchema = new mongoose.Schema {
  name: String
  location: String # tokyo, osaka ...
}

postSchema = new mongoose.Schema {
  title: String
  user: { type: String, ref: 'User' }
}

postSchema.pre 'save', (next) ->
  # switch collection here
  # just for instance level, not class level
  this.collection = db.collection 'posts_' + this.user.location
  next()

User = mongoose.model 'User', userSchema
Post = mongoose.model 'Post', postSchema

for k, v of db.collections
  console.log '---', k

tom = new User { name: 'tom' }
tom.location = 'osaka'
tom.save()

post1 = new Post { title: 'hello' }
post1.user = tom
post1.save (err, doc) ->
  if err
    console.log err
  else
    console.log doc
    console.log '===', Post.collection.name
    for k, v of db.collections
      console.log '+++', k
    process.exit()
```
It's working fine, but I could not determine whether it is **safe enough**, anybody tell me that ? Thanks

PS: I write ruby, just a javascript newbie

**Comment by vkarpov15** [comment]
This isn't really supported behavior, and, as is, this'll only work for `.save()`, but start giving you incorrect results if you do `Post.find()`, or if you try to `.populate()` a post. You can work around these limitations with query hooks, but I'd imagine this would be very tricky and you should test thoroughly if you're going to do this.

**Comment by xpepermint** [comment]
I'm also searching for a model with a `dynamic collection` support.
