### ISSUE TITLE
Unable to $pull from single sub-document which containes array of objects

### ISSUE THREAD

**Issue by sparshy** [Automattic/mongoose#3616]
$pull from a single subdocument fails

    var ParentSchema = new Schema({
      child: childSchema
    })

    var ChildSchema = new Schema({
    items:[itemsSchema]
    })

the below query fails to pull from items array

    Parent.findOneAndUpdate(query, {$pull:{'child.tems':{_id: itemID}}})

whereas the following works on mongodb

    db.parent.update(query, {$pull:{'child.tems':{_id: itemID}}})

**Comment by vkarpov15** [comment]
Are you sure the issue isn't due to the fact that you typoed on 'items' in your findOneAndUpdate call?

**Comment by sparshy** [comment]
Yes definitely not due to the typo here. Now i am using embedded document instead of defining a subdocument that works fine.

**Comment by sparshy** [comment]
@vkarpov15 can you tell if there is any difference between using subdocument and embedded document, apart from using `subdocument` assigns a _id field where as embedded document doesnt. 

Any advantage of one over the other?

**Comment by vkarpov15** [comment]
In theory they should have the same semantics. Can you show me some code that reproduces the `_id` issue you mentioned? That shouldn't happen either.
