### ISSUE TITLE
$inc a default non 0 value with findOneAndUpdate  and upsert true

### ISSUE THREAD

**Issue by dciccale** [Automattic/mongoose#3617]
hi, i am having trouble starting a counter `n` at a specified number and then increasing by 1 using `findOneAndUpdate` and `upsert: true`.

```js
var RefSchema = new Schema({
  _id: {type: String, default: 'refs'},
  n: {type: Number, default: 776}
});

...

var query = {_id: 'refs'};
var update = {$inc: {n: 1}};
var options = {upsert: true, 'new': true};
// this will create the doc if it doesn't exist the first time, 
// it should use the default value from the schema instead of the value passed to $inc
RefSchema.findOneAndUpdate(query, update, options, function (err, doc) {
  console.log(doc.n); // is 1 but i expect to see 776
});
```

what i expect is the creation of a document with the `n` property starting at `776` and then increasing from that value.

**Comment by vkarpov15** [comment]
Use the `setDefaultsOnInsert` option. Or just manually use `{$inc: {n:1}, $setOnInsert: {n:776} }`.

**Comment by dciccale** [comment]
using `$setOnInsert` doesn't seem to work, I get `undefined` instead of a document

```
  var RefSchema = new Schema({
    _id: {type: String, default: 'refs'},
    n: {type: Number, default: 776}
  });

  ...

  var query = {_id: 'refs'};
  var update = {$inc: {n: 1}, $setOnInsert: {n: 766}};
  var options = {upsert: true, 'new': true};
  RefSchema.findOneAndUpdate(query, update, options, function (err, doc) {
    console.log(doc); // is undefined
  });
```

if I use `setDefaultsOnInsert` option

```
var options = {upsert: true, 'new': true, setDefaultsOnInsert: true};
```

**Comment by dciccale** [comment]
Oops, I'm using mongo 3.0.0 probably is a bit old :( will update and try again!, sorry & thx

**Comment by dciccale** [comment]
mongoose 4.1.5, mongodb version shouldn't be an issue right?

**Comment by vkarpov15** [comment]
No setDefaultsOnInsert should work fine against mongodb 3.0. I'll double check

**Comment by dciccale** [comment]
I think that is not allowed to use `$inc` with `$setOnInsert` because the record doesn't exist. if I use `$setOnInsert` alone it works, or `$inc` alone also.
But I wanted a query that every time is called, is either incrementing the value or if the first time the record wasn't there, create it with a default value.

Basically what I want to do is something like this (working example):

```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var RefSchema = new Schema({
  _id: {type: String, default: 'refs'},
  ref: {type: Number, default: 776}
});

RefSchema.statics.increment = function (callback) {
  var query = {_id: 'refs'};
  var update = {$inc: {ref: 1}};
  var options = {upsert: true, 'new': true, setDefaultsOnInsert: true};

  this.findOneAndUpdate(query, update, options, callback);
};


var RefModel = mongoose.model('Ref', RefSchema);

var OrderSchema = new Schema({
  total: Number,
  ref: Number
});

OrderSchema.pre('save', function (next) {
  if (!this.isNew) {
    return next();
  }

  var self = this;
  RefModel.increment(function (err, doc) {
    self.ref = doc.ref;
    next(err);
  });
});

var OrderModel = mongoose.model('Order', OrderSchema);

var orders = [];

for (var i = 0; i < 100; i++) {
  orders.push({total: (i + 1) * 3.4});
}

OrderModel.create(orders, function (err, orders) {
  console.log('orders', orders);
});
```

So this is working but it is starting the `ref` count in 1. instead of 766. I just can't get it to start on other number other than 1.

Again, what it suspect is that with upsert, it will create the document with the value of the `$inc` instead of the specified in the `default`.

I am trying to find where is this happening.. will update asap if if i find something.

anything from your side?

**Comment by dciccale** [comment]
I found this conversation https://groups.google.com/forum/#!topic/mongodb-user/A93n4zEXClk that relates to this ticket in mongodb https://jira.mongodb.org/browse/SERVER-6566

so far what i understand is that this could be achieved with an array of updates as it is proposed in the jira ticket.

**Comment by vkarpov15** [comment]
So if you specify `$inc` on a field, `setDefaultsOnInsert` will explicitly ignore it, because mongodb treats `$inc` and `$setOnInsert` on the same field as an error:

```javascript
> db.test.updateOne({}, { $inc: { test: 1 }, $setOnInsert: { test: 50 } }, { upsert: true });
2016-02-02T16:24:59.148-0500 E QUERY    [thread1] uncaught exception: WriteError({
	"index" : 0,
	"code" : 16836,
	"errmsg" : "Cannot update 'test' and 'test' at the same time",
	"op" : {
		"q" : {
			
		},
		"u" : {
			"$inc" : {
				"test" : 1
			},
			"$setOnInsert" : {
				"test" : 50
			}
		},
		"multi" : false,
		"upsert" : true
	}
}) :
undefined
```

As such, there's no good way for mongoose to have sane handling for `setDefaultsOnInsert` if the defaults field is anywhere in the update operation until the mongodb server can handle this case better.

Also, I opened up a separate issue #3835 that's somewhat related to this one.

**Comment by ashfaqnisar** [comment]
@dciccale, I know this has been too long. But, were you able to find a solution for this thing ?
