### ISSUE TITLE
toObject not adding virtual fields with getters: true

### ISSUE THREAD

**Issue by pschuegr** [Automattic/mongoose#3618]
I'm seeing some behaviour that doesn't make sense to me with the options passed to toObject; similar behaviour with setting the corresponding options on the schema.

````
let userSchema = new Schema({
    profile: {
        type: Object,
        default: {}
    }
});

userSchema.virtual('profile.hasAvatar')
    .get(...)
````

````
user.toObject({ getters: false, virtuals: true }).profile.hasAvatar; //true
user.toObject({ getters: true, virtuals: true }).profile.hasAvatar;  //undefined
user.toObject({ getters: true }).profile.hasAvatar; //undefined
````

My expectation is that all these would return the same value.  Is there something I'm missing or am I looking at a bug?

(v4.2.8, node 0.10.16, mongo 2.6)

**Comment by vkarpov15** [comment]
Be careful with dots in virtual field names. Could very well be a bug, but virtuals with dots in the name don't really work the way you expect. You'd have to access `user['profile.hasAvatar']` rather than `user.profile.hasAvatar`.
