### ISSUE TITLE
Middleware with ES6 arrow functions

### ISSUE THREAD

**Issue by davidkalosi** [Automattic/mongoose#3619]
I stumbled on this issue while playing with babel and new ES6 features - when using the => notation this is undefined and does not point to the document. 

I am bootstrapping the app with ```babel-polyfill``` and ```babel-core/register```

Classic notation
```javascript
// all OK 
documentSchema.pre('save', function (next) {
  //  whateverFunctionUsingThis(this._id);
  return next();
});
```

Arrow function notation
```javascript
// this is undefined
documentSchema.pre('save', (next) => {
  //  whateverFunctionUsingThis(this._id);
  return next();
});
```

**Comment by ChristianMurphy** [comment]
`function` dynamically scopes the `this` keyword, and can be rebound at run time using `.bind()`.
fat arrow is lexically scoped and prevents `.bind()`.

Meaning babel is rewriting the above arrow example into something like this,

``` javascript
var self = this;
documentSchema.pre('save', function (next) {
  whateverFunctionUsingThis(self._id);
  return next();
});
```

references [function and this](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch2.md#chapter-2-this-all-makes-sense-now), [fat arrow and this](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/apC.md#appendix-c-lexical-this)

**Comment by vkarpov15** [comment]
Not an issue, that's how arrow functions work. Don't use arrow functions when you're dependant on dynamic function context.

**Comment by nathanhleung** [comment]
I stumbled upon this problem as well - is there a way to pass the doc that's being updated to the callback?

**Comment by vkarpov15** [comment]
Nope not at the moment. That's a core feature of arrow functions
