### ISSUE TITLE
Mongoose not connecting with SCRAM-SHA-1

### ISSUE THREAD

**Issue by crispen-smith** [Automattic/mongoose#3621]
Given the following setup:

    Crispens-MacBook-Pro:site crispensmith$ npm list | grep mongodb
    │ ├─┬ mongodb@2.0.49
    │ │ ├── mongodb-core@1.2.24
     npm ERR! peer dep missing: kerberos@~0.0, required by mongodb-core@1.2.24

    Crispens-MacBook-Pro:site crispensmith$ npm list | grep mongoose
    ├── locomotive-mongoose@0.1.0
    ├─┬ mongoose@4.2.8
    ├── mongoose-types@1.0.3
    npm ERR! peer dep missing: kerberos@~0.0, required by mongodb-core@1.2.24
 
on osX Yosemite (10.10.5), with connection being executed in  the following code block:

    module.exports = function () {
        this.mongoose = require('mongoose');
	this.mongooseTypes = require("mongoose-types");
	this.mongooseTypes.loadTypes(this.mongoose);
	this.mongoose.connect(mongoURL);
    };

This works: 

    var mongoURL = "mongodb://localhost/ofDreamsAndShadows";

but this does not: 

    var mongoURL = "mongodb://ods_db_login:0ds123@ds055594.mongolab.com:55594/of_dreams_and_shadows_dev?authMechanism=SCRAM-SHA-1"`

However cli login to the mongolabs instance is working as expected.

This suggests that this is an issue with Authentication (the unmet kerberos dep?) . 

However, I've also  tried on a cloud instance .

I'm including the output of npm start on my local machine as cloud instance logs are much more verbose but the critical line is the same in both instances.

    Crispens-MacBook-Pro:site crispensmith$ npm start

    > Of_Dreams_and_Shadows_1_pager@0.0.1 start /Users/crispensmith/Documents/goal/Site
    > node node_modules/locomotive/bin/lcm.js server

    CLI ENV: development
    Locomotive 0.4.2 application starting in development on http://0.0.0.0:3000
    HTTP server listening on 0.0.0.0:3000

    /Users/crispensmith/Documents/goal/Site/node_modules/mongodb/lib/utils.js:98
     process.nextTick(function() { throw err; });
                                   ^
    MongoError: Authentication failed.
        at Function.MongoError.create (/Users/crispensmith/Documents/goal/Site/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/crispensmith/Documents/goal/Site/node_modules/mongodb-core/lib/topologies/server.js:776:66
    at Callbacks.emit (/Users/crispensmith/Documents/goal/Site/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/crispensmith/Documents/goal/Site/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/crispensmith/Documents/goal/Site/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by vkarpov15** [comment]
Are you sure your mongolabs instance is configured to use SCRAM-SHA-1? What version of the shell are you using and how are you authenticating in the shell?

**Comment by HexORSist** [comment]
I'm seeing this same problem.  Using a C9 implementation on heroku with a add-on for mongolabs.

**Comment by crispen-smith** [comment]
I've had several conversations with the support team at MongoLabs around this, where they have confirmed this is the auth model they are using.

I'm using Shell 3.0.7 and authenticating with  this pattern:

mongo ds055594.mongolab.com:55594/of_dreams_and_shadows_dev -u <dbuser> -p <dbpassword>

**Comment by HexORSist** [comment]
When I use the mongo shell it authenticates using 2.6.11.  How do I get it to use 3.0.7?  I removed the mongoose dependency from my package.json but when i install using `npm install mongoose --save` it still doesn't use 3.0.7.

**Comment by HexORSist** [comment]
I figured out how to upgrade to 3.0.7 on C9 and authentication with mongo shell is good.  mongoose on the other hand isn't authenticating as @crispen-smith has described.

http://stackoverflow.com/questions/33204739/how-to-delete-an-old-version-of-mongodb-and-install-the-new-one-in-cloud9-ide

**Comment by vkarpov15** [comment]
@crispen-smith which database is your user defined on? You may need to set the [`authSource` query parameter](https://docs.mongodb.org/manual/reference/connection-string/#uri.authSource) as well.

**Comment by crispen-smith** [comment]
I've reached out to MongoLabs to confirm where users are created as this happens behind the scenes.  I'll come back with updates as soon as I can.

**Comment by HexORSist** [comment]
@crispen-smith I was able to resolve my issue.  In my server.js file i was referencing "MONGO_URI" as the key. When mongolabs automatically generates the key it is generated as "MONGOLAB_URI".  Its easy to miss this because they look so similar.

**Comment by crispen-smith** [comment]
@HexORSist I don't believe that will resolve my issue as I'm using a hardcoded string for the uri and not constructing it in the environment. But I'm glad to hear that your piece has been resolved.

**Comment by crispen-smith** [comment]
I've heard from MongoLabs Support with the following message:

Jackson (MongoLab Support)
Nov 30, 12:13

I can confirm that the authSource for your user is "of_dreams_and_shadows_dev". When not specified, authSource defaults to the database in the connection string.

Have you tried setting the authMechanism parameter?

Sincerely,
Jackson


The connection string is currently: 
var mongoURL =  "mongodb://ods_db_login:0ds123@ds055594.mongolab.com:55594/of_dreams_and_shadows_dev?authMechanism=SCRAM-SHA-1&authSource=of_dreams_and_shadows_dev"

At this time I'm still not able to make a connection.

**Comment by vkarpov15** [comment]
Try removing the `authMechanism` and `authSource`, and also try `authMechanism=MONGODB-CR`. Might be that for some reason mongolabs is using the legacy auth mechanism.

**Comment by crispen-smith** [comment]
I've tried the following variations:
-> No URI params
-> authMechanism=SCRAM-SHA-1&authSource=of_dreams_and_shadows_dev
-> authMechanism=SCRAM-SHA-1
-> authSource=of_dreams_and_shadows_dev
-> authSource=of_dreams_and_shadows_dev&authMechanism=MONGODB-CR
->authMechanism=MONGODB-CR

So far, no luck.

**Comment by vkarpov15** [comment]
Does your username or password contain any special characters like `:`, `@`, etc. or are they alphanumeric?

**Comment by crispen-smith** [comment]
Well, that's interesting.   The original username was snake-cased and that was failing within Mongoose.  As soon as I dropped everything but letters the issue resolved itself.

**Comment by vkarpov15** [comment]
That sounds like a bug. Snake-cased as in `crispen_smith`? Or `crispen-smith`?

**Comment by crispen-smith** [comment]
The former.  I had been thinking it was buggy and that I should be looking into it.  if you can let me know where the auth module sits I can look at submitting a PR against this.

**Comment by vkarpov15** [comment]
@crispen-smith you may want to take a look at this: https://github.com/aheckmann/muri/blob/master/lib/index.js#L174-L197 although I see no reason why an `_` in the username should cause the parsing to fail. Did you have any other special characters in your username?

**Comment by crispen-smith** [comment]
Sorry for the slow responses to this;  got buried under the holidays and some additional operational stuff.

Looking at the code, I agree that on the surface there's no reason why this error should have occured and I've been able to prove that connections without the character are working okay.

**Comment by vkarpov15** [comment]
Weird. Glad you got it working, happy new year.

**Comment by sbrnag** [comment]
Thanks a lot @vkarpov15...helped me to resolve connection issue with mlab. i was using password with special characters. After removing that able to connect.
