### ISSUE TITLE
Discriminators: Model.create({kind: 'discriminator'}) should return proper class

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#3624]
Given a parent class `Model` and a discriminator `SubModel`, doing `Model.create({kind: "SubModel"})` or `new Model({kind: 'SubModel'})` should return a doc that is instance of `SubModel`

**Comment by vkarpov15** [comment]
IMO that wouldn't be the right behavior, polymorphic constructors are really confusing. Open to counter arguments though.

**Comment by paglias** [comment]
I see your point but it's equally confusing that once you do `Model.create({kind: "SubModel"})` when that document is returned using a query like `Model.findOne({_id: docId})` the returned model will be an instance of `SubModel` too with its schema fields applied. So the behavior is just deferred to the next query

**Comment by vkarpov15** [comment]
That's a fair point. That's a bit of a rough edge in the API.
