### ISSUE TITLE
PoolSize related questions

### ISSUE THREAD

**Issue by karmakoder** [Automattic/mongoose#3627]
Does default poolSize of 5 mean app will only have 5 connections at any given point of time? Seems kind of weird that app driver wont scale connections when load rises. Also poolSize is indeed the maximum number why not call it maxPoolSize?

**Comment by vkarpov15** [comment]
5 connections that are used to send commands to the server. The driver will open other connections for internal use.

The driver could scale connections when load rises, but it's tricky to get that right for all use cases. Better to let users determine what's correct for their use case.

Also, the number of connections open at any given time should always be `poolSize` unless a connection fails, so 'poolSize' is more specific and more correct.

**Comment by karmakoder** [comment]
Thanks for the response. Wanted to confirm if driver scales connections or not. Have definitely seen more than default size under load tests so was confused.
