### ISSUE TITLE
I have one Question please can you help me

### ISSUE THREAD

**Issue by manjeettahkur** [Automattic/mongoose#3630]
I am using aggregate method . and it provide me the document  match the query but  i need on projection fields so can i use projection on some fields in aggregate method
```javascript
db.places.aggregate([
   {
     $geoNear: {
        near: { type: "Point", coordinates: [ -73.99279 , 40.719296 ] },
        distanceField: "dist.calculated",
        maxDistance: 2,
        query: { type: "public" },
        includeLocs: "dist.location",
        num: 5,
        spherical: true
     }
   }
])
```

**Comment by vkarpov15** [comment]
Can you please clarify? I don't understand the question.

**Comment by yordis** [comment]
@vkarpov15 https://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/#projection

Short description: Select the fields that you want in the query result.

**Comment by yordis** [comment]
@manjeettahkur I found this so I think actually is supported it. [Aggregate.prototype.project](https://github.com/Automattic/mongoose/blob/master/lib/aggregate.js#L129)

**Comment by vkarpov15** [comment]
Yeah `.project()` is how you would do the equivalent of `.select()` in the aggregation framework.

**Comment by manjeettahkur** [comment]
Thank you for helping me @yordis and @vkarpov15
