### ISSUE TITLE
Newest *npm* appears to be upgrading a dep in this projects release flow

### ISSUE THREAD

**Issue by Martii** [Automattic/mongoose#3631]
Newest *npm* appears to be massively messing with the dependency tree automatically with *npm*@3.5.0

I've reported this at npm/npm#10612 

Will this damage some functionality of this project? It seems to me that upping your dependency tree all by itself without your testing could cause some headaches. Other projects may have this affect them as well. Another one has one downgraded which doesn't appear to make much sense to me... but that's over there at less/less.js#2739

Sites, such as ours and our thousands of users, depend on a stable dependency tree and I'd much rather not see the packaged eco-system polluted with versions that aren't yet supported or could have some serious bugs/security risks... all of this seems to be without this projects consent.

Thanks for your patience on this.

---

*(Clipped requote specific to this package)*
``` sh-session
npm WARN In mongoose@4.2.8 replacing bundled version of async with async@0.9.0
```

... I understand this project is working on 4.2.9 in development but **not** in release yet at the time of this writing. *(__EDIT__: I understand the usage of caret, tilde, [etc.](https://docs.npmjs.com/misc/semver) in [package.json](https://docs.npmjs.com/files/package.json) but what is to prevent them from downgrading one of your dependencies like the other mentioned project and causing some real DB damage?)*

**Comment by Martii** [comment]
Bringing up [this mistake](/Automattic/mongoose/issues/3326) if *npm* were to do say that update automatically *(assuming it wasn't deleted from their registry repository and one didn't know about it)* ... upping a dependency might be a very large headache if caught at the right moment between deploys and unexpected consequences.

**Comment by vkarpov15** [comment]
I really don't understand this question, can you please clarify what your issue is?

**Comment by Martii** [comment]
Did you visit npm/npm#10612 to see the dependencies that were "changed"? ... [in 4.2.8 this projects *async* is at 0.9.0](/Automattic/mongoose/blob/79c17e00794dd29f4f7c74f1a2469abcbd753496/package.json#L22) already but it appears that *npm* is able to change package.json up **and** down regardless of caret, tilde and lack of with semver... the down part being especially destructive in the other projects. It's fully documented on what is happening... We've downgraded to a less volatile *npm* that doesn't appear to change dependencies.

I am curious if other projects are getting lower version dependencies of your project without consent or knowledge? e.g. rhetorical as they could be due to this discovery. *npm* hasn't responded yet and if one of the dependencies that this project relies on gets downgraded it could easily cause additional DB corruption... so for this project this issue is more of a FYI. :)

**Comment by vkarpov15** [comment]
Considering that we don't really use `^` or `~` for production dependencies (excluding bson) it shouldn't affect us. Either way, the way I read that warning message is that "mongoose is getting a different version of async than you are, so be careful if you expect mongoose's async to be the same as yours", which shouldn't matter since mongoose only uses async internally. Does that clarify your concern?

**Comment by Martii** [comment]
Yes... I hope that the FYI wasn't too over presumptuous *(which I figured out later)* as it does seem to affect everyone in the eco-system of *node*... now I get to, as the Active Maintainer, check every dependency we utilize and make sure that something in their dependencies isn't downgraded from the latest *npm*... seems to be a maintenance nightmare and dependency "hell" is probably inevitable. :( ... but I'll try to keep an upside note with maybe they'll respond and fix it.

I appreciate all your teams efforts and especially yours for your patience and professionalism. Kudos! :) ... closing.
