### ISSUE TITLE
Empty subdocument not returned

### ISSUE THREAD

**Issue by email2vimalraj** [Automattic/mongoose#3632]
I have a document like this:

	{
	    "_id" : ObjectId("565c16d3951a55934acaca75"),
	    "userEmail" : "abc@example.com",
	    "subscription" : {
	        "project1" : {
	            "subproject1" : [ 
	                "comp1"
	            ]
	        },
	        "project2" : {}
	    }
	}

Using mongoose, if I try this:

	MyModel.findOne({userEmail: "abc@example.com"})

I'm getting output as:

	{
	    "_id" : ObjectId("565c16d3951a55934acaca75"),
	    "userEmail" : "abc@example.com",
	    "subscription" : {
	        "project1" : {
	            "subproject1" : [ 
	                "comp1"
	            ]
	        }
	    }
	}

The `project2` is removed since it has empty document. If I try in mongo console, I'm not facing this issue.

**Comment by email2vimalraj** [comment]
I believe it may be because of `BodyParser` that I use. Let me check and update this issue accordingly.

**Comment by vkarpov15** [comment]
It's probably because of the [mongoose `minimize` option](http://mongoosejs.com/docs/guide.html#minimize). Try setting that to false.

**Comment by email2vimalraj** [comment]
Awesome it worked. Thanks a lot.
