### ISSUE TITLE
find().each() loop with cursor

### ISSUE THREAD

**Issue by xpepermint** [Automattic/mongoose#3637]
I have a million documents in my database and I need to scan through all of them. I search for an easy `find().each(...)` solution like [THIS](https://rethinkdb.com/api/javascript/each_async/) to loop through each document using a `cursor`. So far I found the built-in streaming solution but it does not return a promise when the the process finishes.

So... is there a function that would do something like this:
```js
  return new Promise((resolve, reject) => {
    Identity.find().stream().on('data', doc => {
      console.log('doc', doc)
    }).on('error', res => {
      reject(err);
    }).on('end', res => {
      resolve();
    });
  })
```
And would return a promise:
```js
Model.find().each(doc => {
  console.log(doc) // loop using curosr
}).then(res => {
  console.log('Results count:', res.count);
})
```
If not, can we add one?

**Comment by xpepermint** [comment]
A quick code/plugin example:
```js
const eachInStreamPlugin = function(schema, options) {
   schema.method('eachInStream', (stream, handler) => {
     return new Promise((resolve, reject) => {
       stream.on('data', doc => {
         stream.pause();
         handler(doc).then(res => stream.resume()).catch(reject);
       }).on('error', reject).on('end', resolve);
     });
   });
};
```
Example:
```js
var schema = new mongoose.Schema({...});
schema.plugin(eachInStreamPlugin);

schema.method('printAll', function() {
  let query = Model.find().batchSize(10).stream();

  return this.eachInStream(query, doc => {
    console.log('Doc:', doc._id);
    return Promise.resolve();
  }).then(res => {
    console.log('done')
  }).catch(err => {
    console.log(err);
  });
});
```

**Comment by vkarpov15** [comment]
Would giving the resulting stream from `.stream()` a `.then()` function be sufficient for your use case?

**Comment by xpepermint** [comment]
Hum, I'm not sure I understand. Do you mean `stream().then`? Note that the `handler` for `stream.on('data', handler)` returns a promise thus the documents can be processed sequentially. I use `pause/resume` to achieve the expected result.

So the final result would look something like this:
```js
Model.find().eachInStream(doc => {
  return Promise.resolve();
}).then(...).then().catch(...);
```

**Comment by vkarpov15** [comment]
The general idea would be something like this:

```javascript
Model.find().stream().on('data', function() {}).on('error', function() {}).then(function() {
  /* Resolved with `null` value when the stream is exhausted, rejected when there was an error */
});
```

**Comment by xpepermint** [comment]
I must admit that I don't know exactly how the `on("data", handler)` works. Will `on("data", handler)` wait until the handler complete an **async** task (until a promise inside is resolved)?
```js
Model.find().stream().on('data', function() { 
   // async operation here, this must return a promise
   return Promise.resolve(); // if you don't return a promise you don't know when to process next
}).then(res => {
   console.log('finished');
   Model.db.close();
});
```
I'd prefer having `eachSomething` method that returns a promise so you know exactly what you can expect.

**Comment by vkarpov15** [comment]
Ah ok I was mistaking your use case. I was imagining something like below.

```javascript
var stream = Model.find().stream();

stream.on('data', handler);
stream.on('error', errorHandler);

stream.then(function() {});
```

Where `stream.then()` would just be a shorthand for `stream.on('end');`. You're looking to pause the stream in between async operations. I'm hesitant to put this in the mongoose core unless there's more demand, but if you can implement it easily as a plugin then might as well just do that.

**Comment by xpepermint** [comment]
Well... I think that having a method that can process all the records in a database is a core method. Elasticsearch provides a `scan` and `scrollToEnd` methods, Rethinkdb has `each` and `eachAsync`, and Mongodb has `forEach` but no promises. I would need a query cursor which I could safely (in batches to save memory) use to process all the documents in a database. Can this functionality be achieved in a different way? Do you have an alternative to that?

**Comment by vkarpov15** [comment]
I'd imagine this is something that would have to go into the mongodb driver. We could implement it outside of the driver but would involve a lot of stream pausing and restarting, which is extra unnecessary work. We'll discuss this with the mongodb node team and see if this is something worth adding :)

**Comment by sibelius** [comment]
this could be helpful
```jsx
await Model.find().cursor().eachAsync(async (model) => {
   console.log('do work with model: ', model);
});
```

**Comment by vkarpov15** [comment]
That's of minor use, if you're using asyc / await you can just use a for loop to get the same functionality as eachasync anyway
