### ISSUE TITLE
Populate across different databases not working.

### ISSUE THREAD

**Issue by DigitalLeaves** [Automattic/mongoose#3639]
I'm trying to populate across different databases, but it's not working. Here is my setup. 

Database 1: users (in globalDatabase.js)

```
var connection;
exports.connectToDatabase = function () {
    var db = mongoose.createConnection('...'); // database db1
    connection = db;
    defineGlobalDatabaseSchemas();
}
exports.currentConnection = function() { return connection; }

function defineGlobalDatabaseSchemas() {
   var userSchema = mongoose.Schema({
       "name": String,
       "email": String,
       ...
   });
   var User = connection.model('users', userSchema);
   exports.User = User;
   exports.UserSchema = userSchema;
}
```

Database 2: customers, and other things... (in team.js).

```

// Same methods for connectToDatabase, and define the schemas:
// creates a connection to db2 using createConnection()
var customerSchema = mongoose.Schema({
    "name" : { type: String, unique: true},
    "email" : [ String ],
     ...
    "created_by" : { type: mongoose.Schema.Types.ObjectId, ref: 'users' },
});
var Customer = connection.model('customers', customerSchema);
exports.Customer = Customer;
exports.CustomerSchema = customerSchema;
```

As of https://github.com/Automattic/mongoose/blob/91347cf80271fc968ab385f179858132e177eec3/test/model.populate.test.js#L129-160 and https://github.com/Automattic/mongoose/issues/2137 I am doing the following to populate:

```
var db = require('./globalDatabase');
db.connectToDatabase();

var db2 = require('./team.js');
db2.connectToDatabase();

var query = db2.Customer.find({});
    query.limit(...);
    query.skip(...);
    query.populate('created_by', 'name, email', db.User); <==== db.User is valid and console.log shows it
    query.exec(function (err, customers) {
        if (err) { // handle error }
        else { send response; }
    });
```

However, I always get created_by as null. If I don't include the populate clause, created_by is valid, and I can see the valid Reference ObjID, but I really need to populate it. As I understand, starting from version 3.9, it should be possible, so what am I doing wrong?

**Comment by DigitalLeaves** [comment]
I have tried with whitespace-separated fields 'name email', just one field 'name' or nothing at all ('created_by, db.User) but nothing seems to work :(

**Comment by vkarpov15** [comment]
That's odd, the below script works fine for me.

```javascript
var mongoose = require('mongoose');
var assert = require('assert');

mongoose.set('debug', true);

var db1 = mongoose.createConnection('mongodb://localhost:27017/gh3639');
var db2 = mongoose.createConnection('mongodb://localhost:27017/gh3639_2');

var userSchema = mongoose.Schema({
  "name": String,
  "email": String
});

var customerSchema = mongoose.Schema({
  "name" : { type: String },
  "email" : [ String ],
  "created_by" : { type: mongoose.Schema.Types.ObjectId, ref: 'users' },
});

var User = db1.model('users', userSchema);
var Customer = db2.model('customers', customerSchema);

User.create({ name: 'Val' }, function(error, user) {
  assert.ifError(error);
  Customer.create({ name: 'Bacon', created_by: user._id }, function(error, customer) {
    assert.ifError(error);
    test(customer._id);
  });
});

function test(id) {
  Customer.findOne({ _id: id }).populate('created_by', 'name email', User).exec(function(error, customer) {
    assert.ifError(error);
    assert.equal(customer.created_by.name, 'Val');
    process.exit(0);
  });
}
```

Can you see if you can modify the given script to reproduce your issue? We have tests in place for cross-db population so this should work in theory, but there may be a case we've missed. 

Also, can you clarify which version of mongoose you're using? The above script works for me with 4.2.9.

**Comment by DigitalLeaves** [comment]
Hi Valeri,
Thanks for your prompt response. Having a look at your code I realized I was terribly confused about the fields in the populate function. Now it's clearer and working. 

Thank you so very much for your quick support. May I suggest to put a clearer (=simpler) example somewhere in the mongoose documentation about this issue? as it was by no means clear to me and I actually ended up doing it terribly wrong.

Again, thanks a lot.

**Comment by vkarpov15** [comment]
What specifically is unclear? [The api docs](http://mongoosejs.com/docs/api.html#query_Query-populate) give you a pretty good list (with one minor issue I'll fix now) of parameters to supply to `query.populate()`, what can we do better?

**Comment by DigitalLeaves** [comment]
The api docs are nice, but I think this issue is not covered in depth, not at least, IMHO. I spent hours looking for a solution, and actually asked here in github because honestly I didn't know where else to ask for help. Maybe it's just me. Other topics are covered nicely in the intro, user guide and such, but this specific topic was a obscure one to me. Just my opinion, though.

**Comment by figalex** [comment]
@DigitalLeaves What changes did you make in order to make it work? I'm trying to do it just as @vkarpov15 put it on the example but still I get null on the field I want to populate

**Comment by figalex** [comment]
I'm also getting MongooseError: Schema hasn't been registered for model when the populate function runs and I pass a Model connected to my 2nd db

**Comment by DigitalLeaves** [comment]
@figalex probably that might be the problem. Are you sure you have declared the schema and the model before calling populate(...) ?

**Comment by DigitalLeaves** [comment]
Anyway, as I stated, the documentation on this is fairly confusing and missing a serious example.

**Comment by vkarpov15** [comment]
@DigitalLeaves are you referring to [these docs](http://mongoosejs.com/docs/populate.html#cross-db-populate) ? Would a github gist that you can run standalone help?

**Comment by DigitalLeaves** [comment]
Yes, precisely those docs. I had to write a backend for an application where there was a global database, and specific databases for every customer. The global and customer databases had different schemas with different models.

It was a nightmare to populate it properly across databases. I ended up doing it, but the documentation was not helpful in my experience. I say this in a constructive way, I know you probably spent quite a lot of time in the documentation and all, but for me, in that case, wasn't helpful at all.

**Comment by vkarpov15** [comment]
Thanks for the feedback, we'll review those docs and see how to improve them

**Comment by elm2013** [comment]
> 
I have the same issue. Could you find any solution?

**Comment by vkarpov15** [comment]
@elm2013 can you please open a new issue and follow the issue template?
