### ISSUE TITLE
Strange behavior when inserting elements to an array in a tight loop

### ISSUE THREAD

**Issue by napalm272** [Automattic/mongoose#3641]
Using mongoose 4.1.5

``` javascript
//model declaration
var mongoose = require('mongoose');
var Q = require('q');

var SampleModelSchema = new mongoose.Schema({
    values: [Number]
});

SampleModelSchema.methods.addValue = function(value){
    this.values.push(value);
    return this.save();
};

var SampleModel = mongoose.model('SampleModel', SampleModelSchema);

//test code
mongoose.connect('mongodb://@localhost:27017');

SampleModel.remove({})
    .then(function(){
        return SampleModel.create({values: []})
    })
    .then(function(model){
        var promises = [];
        for(var k=0;k<10;k++){
            promises.push(model.addValue(k));
        }
        return Q.all(promises);
    })
    .then(function(){
        return SampleModel.findOne({});
    })
    .then(function(model){
        console.log(model.values.length);
    });
```

I have a model called `SampleModel`, I created a method called `addValue` that adds a value to the `values` array and then save the model itself.  In my test code, I'm trying to add 10 values, however, if you run the code, you can see that it will actually have 100 values.  The number of values is always the square of the intended value.  I think it has something to do with how `save` works in mongoose.  Can you advise me on how to do this correctly?

P.S. the reason why I want to have `save()` in the method is so that when other people use `addValue()` they don't have to remember to save it.

**Comment by vkarpov15** [comment]
When you do `.push()`, mongoose translates this into a [`$push` operation to the mongodb server](https://docs.mongodb.org/manual/reference/operator/update/push/). So what you're doing above when you call `.save()` 10 times in parallel is saying "`$push` 1 array element", then "`$push` 2 array elements", all the way up to `$push 10 array elements`. There is absolutely no reason to ever save the same document multiple times in parallel - it's terrible for performance and can have unintended consequences like you saw above.

```javascript
        var promises = [];
        for(var k=0;k<10;k++){
            promises.push(model.addValue(k));
        }
        return model.save();
```

should work.

**Comment by napalm272** [comment]
Does this mean that we should never put `save()` in methods, and always have the method callers call save?

**Comment by vkarpov15** [comment]
No you can put `save()` in methods, just make sure you aren't doing `Promise.all()` on multiple save operations for the same document or calling `.save()` for the same document multiple times in the same iteration of the event loop, that's just silly.

**Comment by napalm272** [comment]
I understand that, but if there's a method called `addValue()`, and if I need to add multiple values, then the natural thing to do imho is to call `addValue()` repeatedly.  But as you said that doesn't work.  So it seems that the consistent thing to do is to never call `save()` in methods in schema, and make `save()` a responsibility of the caller.

**Comment by vkarpov15** [comment]
Yeah that makes sense, unless you explicitly want to call `.save()` in a method. But if you intend to call it repeatedly, doesn't make sense.
