### ISSUE TITLE
Embedded Schema duplicate index problem

### ISSUE THREAD

**Issue by alanpurple** [Automattic/mongoose#3643]
should embedded document array have _id?

if I put {_id:false} option, mongoose make first property as index, so even though the array is null, mongoerror "duplicate index" occur

Shouldn't I use {_id:false} option for embedded schema for embedded array?

The reason I put that option is the array means only for the host document, and because of this, I can't use "unique:true" for the property since this force that property unique for all embedded document  for all host(which is unrelated)

For example, Person A's each task name should be unique for within Person A's task, not for all person's tasks, but I have to check manually every time I update task lists for each person, is that correct?

And all these came recently, I don't know when this first occured

MongoDB version is 3.2.0-rc5 & rc6

**Comment by vkarpov15** [comment]
Ideally the documents you store in a document array should have `_id` fields unless you have a really good reason to disable it. Mongoose uses the document array element's `_id` field for array methods like `pull()`, `remove()`, and `addToSet()` (but falls back to deep equality if _id is not present), so I wouldn't recommend it. You also shouldn't have to use `unique: true` for this field, and the likelihood of ObjectId collisions in the same document is negligible.

**Comment by alanpurple** [comment]
I understand, thanks
