### ISSUE TITLE
doClose callback is not called asynchronously

### ISSUE THREAD

**Issue by jbach** [Automattic/mongoose#3645]
The callback for closing connections is [not passed to the native drivers `close()`](https://github.com/Automattic/mongoose/blob/master/lib/drivers/node-mongodb-native/connection.js#L217)

This means the callback [here](https://github.com/Automattic/mongoose/blob/6789d5b823449599915297256a25b61e8a5ac401/lib/connection.js#L522) is not called AFTER closing the connection.

Looking at [mongodb-native’s doc](http://mongodb.github.io/node-mongodb-native/2.0/api/Db.html#close), wouldn’t it be better to do:

```JavaScript
NativeConnection.prototype.doClose = function(fn) {
  this.db.close(fn);
  return this;
};
````
?

**Comment by vkarpov15** [comment]
It's better, but mostly a pedantic point because [the mongodb driver just calls the callback in a `nextTick()`, it doesn't do any async operations](https://github.com/mongodb/node-mongodb-native/blob/ac29513a42cf18394f4e35317a664b55782a87e9/lib/db.js#L352-L357)
