### ISSUE TITLE
Mongoose reports successful save when stored with an undefined shardKey

### ISSUE THREAD

**Issue by mikepc** [Automattic/mongoose#3650]
When a model has a shardKey defined, and the model instance's key is undefined, mongoose reports a successful save (err is not passed in the callback) and calls the callback, but the record is not updated.

I had changed keys recently and some of the data hadn't been migrated, and none of the records  that lacked the shard key would update data from save().

I assigned them the appropriate shardKey and the saves continued normally and everything worked.

It would be really helpful of this state could be detected and at least error (the preferred behavior would be to at least populate the shardKey with the default value  and continue with the save.

**Comment by vkarpov15** [comment]
@mikepc can you show me a code sample? I think I understand what you're trying to do but translating prose to code is error-prone.
