### ISSUE TITLE
Populate with field select still includes virtual fields

### ISSUE THREAD

**Issue by jonathanasquier** [Automattic/mongoose#3655]
```
Order.findOne({_id : orderId})
    .populate('customer', Customer.publicFields.join(' '))
    .exec(function(error, order){
      //virtual fields included in order.customer, even if not in Customer.publicFields array
    });
```
Virtual fields are included in the populated model even if not in they are not in the select fields string.

**Comment by vkarpov15** [comment]
There's no way to de-select virtual fields, because virtual fields are not loaded from the database.

**Comment by jonathanasquier** [comment]
That may be a technical explanation to the issue, but still a design problem :)

Thanks!

**Comment by vkarpov15** [comment]
Not necessarily a problem, there definitely are use cases where you want a virtual field to have a value even if the related underlying fields are not selected, etc.
