### ISSUE TITLE
Support 3.2

### ISSUE THREAD

**Issue by paton** [Automattic/mongoose#3656]
When upgrading to Mongo 3.2 we get "MongoError: topology was destroyed"

The 3.2 release notes says "A driver upgrade is necessary to support find and getMore." -- is this a driver issue?

**Comment by vkarpov15** [comment]
Yep we're going to make a 4.3 release within the next 24 hours that's going to upgrade the driver version.

**Comment by paton** [comment]
Great! :)

Thanks for the awesome work you've done on Mongoose.

**Comment by vkarpov15** [comment]
Fixed with https://github.com/Automattic/mongoose/commit/cc522d2e152f83c3431d7ff919101dd92818b781

**Comment by thstarshine** [comment]
It would be nice to address 3.2 support on this page: http://mongoosejs.com/docs/compatibility.html
