### ISSUE TITLE
Object <object> has no method 'validateSync'

### ISSUE THREAD

**Issue by dvoras** [Automattic/mongoose#3668]
I installed mongoose@3.8.24 and uses 'validateSync' method (it works well).
However, when I install mongoose on other server (mongoose 3.8.24), It says the error: 
Object <object> has no method 'validateSync', 
and in mongoose/lib/document.js this method doesn't exist.
What could be the problem?

Thanks
Dvora

**Comment by vkarpov15** [comment]
`validateSync()` was added in 4.0.0, so you're not using 3.8.24 locally. Double check by running `head node_modules/mongoose/package.json`.
