### ISSUE TITLE
Don't require callback of type Error for hooks

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3672]
Would require tweaking https://github.com/Automattic/mongoose/blob/98445926a994f9fff8372a47d9702bc4fd2477b2/test/document.hooks.test.js#L220-L230

**Comment by robludwig** [comment]
I wasn't aware of that middleware behavior as it's not mentioned in the [middleware docs](http://mongoosejs.com/docs/middleware.html), but I see that it's testing behavior inherited from bnoguchi/hooks [mutating middlware](https://github.com/bnoguchi/hooks-js#mutating-arguments-via-middleware). If that's intended or if there's a stable API for middleware hooks, I can update the above docs to match.

**Comment by vkarpov15** [comment]
@robludwig clarified in docs above. Sorry for the confusion - this issue should have been fixed but apparently not, and can't quite fix it now without backwards-breaking changes.

**Comment by robludwig** [comment]
Great, thanks for the (very speedy) clarification!

**Comment by vkarpov15** [comment]
Yeah sorry about the delay re: the original issue. Kicked the can down the road for a while because there were more pressing issues and we don't really have a good solution without removing the mutating middleware. I think we might introduce an option to change this behavior in 4.5 or 4.6, but it won't be the default until 5.0.

**Comment by hasezoey** [comment]
i think this issue should be added to a milestone (like `7.0` or `Parking Lot`)

also, what exactly is this issue trying to track?

**Comment by vkarpov15** [comment]
If I remember correctly, the issue is that if you call `next()` with something that isn't an instance of `Error`, Mongoose treated it as an additional arg to subsequent middleware. We need to check if there is still an issue here, and, if so, what we want to do about it.

**Comment by vkarpov15** [comment]
Re: https://github.com/Automattic/mongoose/issues/3672#issuecomment-1235696372, I can confirm this was fixed a long time ago. At least Mongoose 5.0.
