### ISSUE TITLE
Model.update() accepts an array as a query

### ISSUE THREAD

**Issue by r-tanner-f** [Automattic/mongoose#3677]
Calling `Model.update(['foo'], {borked: true}, {multi:true})` will set borked to true on every document. The MongoDB CLI and native driver both complain that the query is not an object, where Mongoose happily charges through the entire collection and sets the property. Any reason for this behavior, aside from helping me test my backups? :)

**Comment by vkarpov15** [comment]
Nope that's not good, will fix :)

**Comment by vkarpov15** [comment]
This is actually pretty deeply embedded behavior, all query functions (`find()`, `findOneAndUpdate()`, `update()`, etc.) explicitly ignore conditions that aren't objects. This may be backwards breaking so we'll put better behavior behind a flag in 4.4. Sorry about the difficulties :)

**Comment by vkarpov15** [comment]
Fixed by bef5646
