### ISSUE TITLE
Schema method returns 'undefined'

### ISSUE THREAD

**Issue by OKNoah** [Automattic/mongoose#3678]
Here is the method:

    User.methods.verifyPassword = function verifyPassword ( password ) {
      return bcrypt.compare( password, this.password )
    }

Here it is used in the controller.

    export function* login () {
      let self = this

      const user = yield User.findOne({ email: this.request.body.email }).exec()

      if ( user.verifyPassword(this.request.body.password) ) {
        this.status = 200
        this.body = {
          token: user.token
        }
      } else {
        this.status = 500
        this.body = "Problem signing in."
      }
    }

**Comment by jiripospisil** [comment]
I'm not sure what bcrypt library you're using but doesn't the compare method take a callback as the third parameter (although I'm surprised it doesn't scream at you for not providing it)? There might be a synchronous version (compareSync) but ideally you should thunkify the async variant and yield in the controller.

**Comment by vkarpov15** [comment]
@jiripospisil is right, [`bcrypt.compare()` is async](https://www.npmjs.com/package/bcrypt#async-recommended).
