### ISSUE TITLE
Unrecognized pipeline stage name: '$lookup'

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#3682]
Doesn't seem to have $lookup support if you do `.aggregate([ { $match: {} }, { $lookup: {} ...`

**Comment by niftylettuce** [comment]
Ref: https://github.com/christkv/mongodb-core/issues/67

**Comment by vkarpov15** [comment]
Are you sure you're using mongodb server 3.2? I only get the above error with the below script when running against mongodb 3.0.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3682');
mongoose.set('debug', true);

var Schema = mongoose.Schema;

var testSchema = new Schema({
  name: String
});

var Test = mongoose.model('Test', testSchema);

Test.aggregate([{ $lookup: { from: 'test2', localField: 'name', foreignField: 'name', as: 'test' } }], function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

**Comment by jaider2523** [comment]
Hi,

I have the same issue, my version of mongoose is 4.3.7.

Request.aggregate([ // Request is a model
      {
         $lookup : {
           from: "Equipo",        // Equipo is a model. 
           localField: "equipo",// Reference to Equipo in Request model
           foreignField: "_id",  // Id of the equipo
           as: "request_eqp"  // Name result
         }
       }
      ], function (err, result) {

        console.log('Agrupamiento');
        console.log(err);
        console.log(result);
      });

**Comment by jaider2523** [comment]
Error:

{ [MongoError: exception: Unrecognized pipeline stage name: '$lookup']
name: 'MongoError',
message: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
code: 16436,
ok: 0 }

**Comment by niftylettuce** [comment]
Upgrade to MongoDB v3.2+

On Wed, Jan 27, 2016 at 12:12 PM, Jaider <notifications@github.com> wrote:

> Error:
>
> { [MongoError: exception: Unrecognized pipeline stage name: '$lookup']
> name: 'MongoError',
> message: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
> errmsg: 'exception: Unrecognized pipeline stage name: \'$lookup\'',
> code: 16436,
> ok: 0 }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3682#issuecomment-175750706>
> .
>



-- 
--
@niftylettuce

**Comment by jaider2523** [comment]
Hi,

Thanks, i have an old version.....i'm going to upgrade my MongoDB.

**Comment by zeuyanik** [comment]
I have "MongoDB shell version: 3.2.8" but the problem is still occurs. What should I do?

**Comment by vkarpov15** [comment]
@zeuyanik just because your shell is version 3.2.8 doesn't mean that the mongodb server you're talking to is using 3.2.8, the shell is just a client for the mongodb server. Try running `db.version()` in the shell, that'll tell you what version the mongodb server it's talking to is running.

**Comment by hyogman** [comment]
Hello I have:
MongoDB shell version v3.4.2
MongoDB server version: 3.2.10

still getting 

> exception: Unrecognized pipeline stage name: '$lookup'   MongoError: exception: Unrecognized pipeline stage name: '$lookup'
