### ISSUE TITLE
how save() works, when I push an item into an array?

### ISSUE THREAD

**Issue by tiant167** [Automattic/mongoose#3684]
Hello, I have some trouble with the `save()` function.

I retrieved an object with `findOne()`, and an array is in this object.
When I call some code like `obj.arr.push({a: 1}); `, and then call `obj.save()` function.

Its all right when request is come in one by one. But when a dozen of requests come in at the same time. The `findOne()` function may return the same origin result to every request. Then every request will call `obj.arr.push({a: 1}); obj.save();`.

At first, I think `save()` will perform like `$set`, but the result is that `arr` in `obj` will be pushed in many `{a:1}`, like `$push`.

This is my test code,

1. The origin result in mongodb is like this
```
> db.userschedules.findOne({_id: ObjectId('565527f363a8b9af7028d197')})
{
	"_id" : ObjectId("565527f363a8b9af7028d197"),
	"joinDate" : ISODate("2015-11-25T03:16:03.381Z"),
	"modified" : ISODate("2015-11-25T03:16:03.385Z"),
	"completedWorkouts" : [ ],
	"__v" : 0
}
```

2. My test code is below,

```javascript
'use strict';

var UserSchedule = require('base/db/mongo').UserSchedule;

for( var i = 0; i< 3; i++){
  UserSchedule.findOne({_id: '565527f363a8b9af7028d197'}).exec().then(function(u) {
    u.completedWorkouts.push({
      day: 22,
      workout: '55ebd890d07a9ed33c293660',
      traininglogs: []
    });
    console.log(u);
    u.save();
  });
}
```

3. Run it, the console log result is:
```
{ _id: 565527f363a8b9af7028d197,
  joinDate: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  __v: 0,
  modified: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  completedWorkouts:
   [ { day: 22,
       workout: 55ebd890d07a9ed33c293660,
       _id: 56722dd1cbf3500e571ebcac,
       traininglogs: [] } ] }
{ _id: 565527f363a8b9af7028d197,
  joinDate: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  __v: 0,
  modified: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  completedWorkouts:
   [ { day: 22,
       workout: 55ebd890d07a9ed33c293660,
       _id: 56722dd1cbf3500e571ebcad,
       traininglogs: [] } ] }
{ _id: 565527f363a8b9af7028d197,
  joinDate: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  __v: 0,
  modified: Wed Nov 25 2015 11:16:03 GMT+0800 (CST),
  completedWorkouts:
   [ { day: 22,
       workout: 55ebd890d07a9ed33c293660,
       _id: 56722dd1cbf3500e571ebcae,
       traininglogs: [] } ] }
```

4. Then the result in mongodb is:
```
{
	"_id" : ObjectId("565527f363a8b9af7028d197"),
	"joinDate" : ISODate("2015-11-25T03:16:03.381Z"),
	"completedWorkouts" : [
		{
			"day" : 22,
			"workout" : ObjectId("55ebd890d07a9ed33c293660"),
			"_id" : ObjectId("56722dd1cbf3500e571ebcac"),
			"traininglogs" : [ ]
		},
		{
			"day" : 22,
			"workout" : ObjectId("55ebd890d07a9ed33c293660"),
			"_id" : ObjectId("56722dd1cbf3500e571ebcad"),
			"traininglogs" : [ ]
		},
		{
			"day" : 22,
			"workout" : ObjectId("55ebd890d07a9ed33c293660"),
			"_id" : ObjectId("56722dd1cbf3500e571ebcae"),
			"traininglogs" : [ ]
		}
	],
	"__v" : 3
}
```

Ok, with this result, I think `save()` is not the simple `$set` update right? It will record the `push` function, and call `$push` in the last execute step?

Thank you >.<

**Comment by vkarpov15** [comment]
Yep, if you `.push()` and don't do anything else, `.save()` will do `$push` for you. In your case `u.save()` just does a `$push` to `completedWorkouts`.

You can turn on mongoose debug mode with `require('mongoose').set('debug', true);` to have mongoose log the operations its sending to mongodb in the console, when you save you should see a `update()` with a `$push` operator.

**Comment by tiant167** [comment]
Thank you!
