### ISSUE TITLE
Support 'replSet' as well as 'replset' for connect options

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3685]

**Comment by taxilian** [comment]
Unfortunately, this is not completely fixed.  I've fixed, tested, and opened #3688 to completely address the issue

**Comment by taxilian** [comment]
I don't suppose there would be any chance of a hotfix pushed in the next 16 hours or so? I can monkey patch my code, but it would be nice to just have a fixed mongoose version when I deploy to production tomorrow... =]

Thanks for looking at this.
