### ISSUE TITLE
0 in query converted into '\u001b[33m0\u001b[39m'

### ISSUE THREAD

**Issue by spamguy** [Automattic/mongoose#3689]
I scripted a query in my Express app, `games.find({ status: { '$in': [ 0, 2 ] } })`. That is, find all games whose status is either 0 or 2.

When Mongoose executed this query, the result set was as expected. The debug output converted the 0 to misencoded garbage, though:
```
Mongoose: games.find({ status: { '$in': [ '\u001b[33m0\u001b[39m', 2 ] } }) { fields: undefined } 
```
I had been running 4.0.8, but this encouraged me to upgrade to 4.2.10. No change.

**Comment by vkarpov15** [comment]
What does your schema look like?

**Comment by spamguy** [comment]
See https://github.com/spamguy/diplomacy/blob/master/server/models/game.js .
