### ISSUE TITLE
No support of cross-modules Schema definitions?

### ISSUE THREAD

**Issue by mgcrea** [Automattic/mongoose#3690]
I found out today that mongoose does not seem to support Schema definitions accross modules:

Using latest mongoose `4.3.3` on node `4.2.1`.

If I have a user schema like:

```js
import {Schema} from 'mongoose';

const schema = new Schema({
  email: {type: String, required: false},
  password: {type: String, required: true},
  firstName: {type: String, required: false},
  lastName: {type: String, required: false}
});

export default schema;
```

That I import from another module:

```js
import userSchema from 'my-user-schema';
mongoose.model('User', userSchema);
```

I do encounter the following error:

```
TypeError: Undefined type `undefined` at `paths.email`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/schema.js:587:11)
    at Schema.path (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/schema.js:498:29)
    at Schema.add (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/schema.js:390:12)
    at Schema.add (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/schema.js:385:14)
    at new Schema (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/schema.js:93:10)
    at Mongoose.model (/Users/olivier/Projects/foobar/node_modules/mongoose/lib/index.js:311:14)
    at Object.<anonymous> (/source/col-core/src/index.js:22:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/olivier/Projects/foobar/lib/index.js:9:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

However the same file, inside the current module:

```js
import userSchema from './schemas/my-user-schema';
mongoose.model('User', userSchema);
```

Does work.

It looks like schema definition are bound to their own mongoose instance.

Any idea on how I can workaround this?

**Comment by vkarpov15** [comment]
I don't quite understand, can you provide a more thorough example? Also, which version of node + which transpiler are you using, if any?

**Comment by mgcrea** [comment]
I'm using `babel@6.3.17` and `node@4.2.1`, it does not look like this comes from babel transpiling, but I could be wrong. Basically, I require an external module that does exposes a `new mongoose.Schema` object/instance, however if I use `mongoose.model` it will throw errors as it looks like it only support schema that has been defined on its "own" `mongoose` global instance (which is not the same in the other module).

**Comment by mgcrea** [comment]
Some additional information:

Somehow things get messed up in [Schema.interpretAsType](https://github.com/Automattic/mongoose/blob/4.3.3/lib/schema.js#L529), I end up with a type that looks like:

```
SchemaString {
    enumValues: [],
    regExp: null,
    path: 'email',
    instance: 'String',
    validators: [],
    setters: [],
    getters: [],
    options: 
     { type: [Function: String],
       required: false,
       index: { unique: false } },
    _index: { unique: false },
    isRequired: false }
```

That just does not match any following rules in this function, ending up with an undefined `name`.

**Comment by mgcrea** [comment]
Found the culprit! It is `schema instanceof Schema` from [index.js](https://github.com/Automattic/mongoose/blob/4.3.3/lib/index.js#L310) returning false because the `Schema` object from the other module comes from another instance.

**Comment by gilles-yvetot** [comment]
I am still facing the same issue. It is always true when I am doing `yarn link` to bind my main project to the "schema" project

**Comment by vkarpov15** [comment]
@gilles-yvetot please provide code samples

**Comment by gilles-yvetot** [comment]
@vkarpov15 

So here are my 2 files:

`User.js` (located in a private node module `data-models`):
```javascript
const { Schema, model } = require('mongoose')

const { Mixed } = Schema.Types // different than mongoose.Types

const EmailSchema = {
  type: String,
  trim: true,
  lowercase: true,
  match: [
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    'Email not valid',
  ],
  minlength: [6, 'Email address too short to be true'],
  maxlength: [100, 'Email address too long to be true'],
}

const UserSchema = new Schema(
  {
    email: EmailSchema,
    name: String,
    passwordHash: String,
    passwordSalt: String,
    magiclinkToken: String,
    resetPasswordToken: String,
    connectors: Mixed,

    recordSettings: {
      pickActions: {
        type: Boolean,
        default: false,
      },
      quickLabel: {
        type: Boolean,
        default: false,
      },
      smartPaste: {
        type: Boolean,
        default: false,
      },
    },
  },
  { timestamps: true, strict: true },
)

const User = model('User', UserSchema)

module.exports = {
  User,
  UserSchema,
  EmailSchema,
}
```

`test.js` (located in another project requiring data-models)
```javascript
const mongoose = require('mongoose')
const { User } = require('data-models')

mongoose
  .connect(`iUsuallyPutMyConnectionStringHere`)
  .then(() => console.log(`connected`))
  .then(() => User.findOne({ email: `gilles@omniinc.com` }))
  .then(usr => {
    console.log(usr)
  })
  .finally(() => process.exit())
```

**Comment by gilles-yvetot** [comment]
I have noticed that if I only import the schema and create the model within the requiring project it works. By working I mean it prints "connected" and then print the fetched user.

Also
` "mongoose": "^5.5.1"` 
node v10.15.3
yarn 1.15.2

**Comment by gilles-yvetot** [comment]
My current fix is to export a Database object with 2 methods `connect` and `disconnect` that are just returning the mongoose methods.
I then require this Database methods in the project that needs the models and this is working. 
So my understanding is there are 2 instances of mongoose, one has a connected connection and the other one is not connected.

**Comment by vkarpov15** [comment]
I'm guessing that `data-models` includes mongoose as a dependency in package.json rather than a `peerDependency`? This should work if mongoose is a peer dep rather than a fully fledged dep.

**Comment by gilles-yvetot** [comment]
`mongoose` in a dependency in the `package.json` of `data-models` yep. 

It looks like it is now working since I upgrade 2 mongoose to the same version on both project. Could it be it ?

**Comment by vkarpov15** [comment]
I'd strongly recommend listing mongoose as a peer dependency in the data-models project rather than having two separate versions.

If both projects have the same version, npm will end up doing the same thing as if data-models listed mongoose as a peer dependency
