### ISSUE TITLE
Native validation support

### ISSUE THREAD

**Issue by Lughino** [Automattic/mongoose#3691]
It would be very useful to use the [native validation](https://docs.mongodb.org/manual/core/document-validation/) included in mongodb 3.2.  
You have already provided this implementation?

Thank you

**Comment by vkarpov15** [comment]
Nope, and no real plans to do so at the moment. Document validation is of limited use atm and it's tricky to figure out how to get it to play nice with mongoose, but I'm open to suggestions.
