### ISSUE TITLE
ES6 anonymous function and schema methods 

### ISSUE THREAD

**Issue by jlouazel** [Automattic/mongoose#3695]
I have setted a schema method called `makeSalt`. When I trying to call my method from a virtual, using ES6 anonymous function style, it doesn't work. 
```javascript
UserSchema.virtual('password')
.set((password) => {
  this.makeSalt();
});
// TypeError: this.makeSalt is not a function
```

But, when I'm using the traditional style, it works like a charm.
```javascript
UserSchema.virtual('password')
.set(function(password) {
  this.makeSalt();
});
// OK, work as usual
```

I'm guessing that the context is not handled in the same way in my two examples. I just want to know what is the difference in mongoose between these two codes because honestly, I don't see why it isn't working.

Thanks

**Comment by vkarpov15** [comment]
[Retaining context is one of the key features of ES2015 arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this), this behavior has nothing to do with mongoose.

**Comment by johannds** [comment]
I'm seeing this happen now even with the traditional style.

**Comment by varunjayaraman** [comment]
@johannds can you post a full repro example?

**Comment by Hasan9797** [comment]
menda bu ishlamadi yibanlaar to'gri javob yo'q hechqaysingda
