### ISSUE TITLE
mongoDb .update doesn't work

### ISSUE THREAD

**Issue by pevargasg** [Automattic/mongoose#3696]
Hi!, I really need some help with my code I'm trying to push more elements to the array. I'm new in MongoDB and I have been experimenting with different methods to update and push the new elements into the new array an none seem to be working. I have attached pictures, since I do not know how to do the formatting for the code on this post.

Thanks!

http://stackoverflow.com/questions/17288439/mongodb-how-to-insert-additional-object-into-object-collection
![codigo1](https://cloud.githubusercontent.com/assets/11162114/11915835/529cbfa6-a686-11e5-87b1-37990358ba13.PNG)
![codigo2](https://cloud.githubusercontent.com/assets/11162114/11915837/52a1161e-a686-11e5-9709-cdbfe1c7aaad.PNG)
![codigo3](https://cloud.githubusercontent.com/assets/11162114/11915836/529f93fc-a686-11e5-85a2-6f94825d0d0b.PNG)

**Comment by vkarpov15** [comment]
See answers on SO.
