### ISSUE TITLE
Support question on events generated

### ISSUE THREAD

**Issue by Martii** [Automattic/mongoose#3699]
So it's been a curious thing to **guess** what events are emitted from which package.

The biggest ones are the past tense ones like `connected` whereas MongoDB has [this](http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html#event:connect) stated as `connect`.

How is one to know when a past tense is needed or not?

I'm looking to attempt to trap http://mongodb.github.io/node-mongodb-native/2.0/api/ReplSet.html#event:timeout but I'm not entirely sure if the MongoDB chain, including *mongoose*, will encapsulate this event. **EDIT**: and if it's `timedout` which follows the same naming logic pattern. I did figure out how to enumerate the connections array but I am unclear if all the events are propagated upwards toward *mongoose*.

Thanks for the support.

**Comment by vkarpov15** [comment]
Mongoose has its own wrapper around mongodb driver connections - it emits events when [it changes state](https://github.com/Automattic/mongoose/blob/master/lib/connectionstate.js) and emits the state name. You can access the `ReplSet` instance using `mongoose.connection.db.topology`. Does that help?

**Comment by Martii** [comment]
> Mongoose has its own wrapper around mongodb driver connections

So I presume this is how some of the events propagate [from *mongodb-core*](https://github.com/christkv/mongodb-core/blob/ea9c6e6b86a32af79a714e5a3d8d3cd0ac5441ca/lib/connection/pool.js#L10-L13) *([also here](https://github.com/Automattic/mongoose/blob/4d7de47f4961c44373713e07f265304d8af09db8/lib/drivers/node-mongodb-native/connection.js#L142) and a bunch of other places)*... right? I'm trying to validate our usage of `error` event and find the `join`, etc. [from that project mentioning](https://github.com/christkv/mongodb-core/issues/66#issuecomment-165052045).  It's a little difficult to find in a `$ grep` since there hundreds of results... I even kept *npm*@2.x so I could search easier since it's not "flat" dependencies like *npm*@3.x is.

> it emits events when [it changes state](https://github.com/Automattic/mongoose/blob/master/lib/connectionstate.js)

So basically I'm asking whose events are [we trapping here](https://github.com/OpenUserJs/OpenUserJS.org/blob/674ca106f3a1ed4ab71aaf261f6357d5f98bcd17/app.js#L89-L111)? ... are these *mongoose* only generated or everything under the object itself, which includes *mongoose*, including the mongo core drivers? As you linked above that doesn't contain `timeout`, `join` and `left`... nor does it contain `error`, `open`, etc. So that's what I'm looking for is the total summary of all events supported and on which object unless it "bubbles upwards" to the parent object of `db`... e.g. can we trap it at the "top-level" `db` identifier or do we need to dive into the connection? Randoming guessing and testing is taking it's toll.

> You can access the ReplSet instance using `mongoose.connection.db.topology`

Ahh that's a little different than what I found digging through the web but I will give that a whirl with some tests.

Thanks for your responses... and if I don't hear back before the holiday that is kosher too. :)

**Comment by vkarpov15** [comment]
The events you're listening to in https://github.com/OpenUserJs/OpenUserJS.org/blob/674ca106f3a1ed4ab71aaf261f6357d5f98bcd17/app.js#L89-L111 are mongoose generated.
