### ISSUE TITLE
Where is documentation of .disconnect() ?

### ISSUE THREAD

**Issue by alex75ita** [Automattic/mongoose#3704]
Hi, 
I red a suggestion to use .disconnect() for my specific case.
OK, where is documentation of this method? Is it private? 
From here (http://mongoosejs.com/docs/guide.html) you can't make a search.
In _connections_ there is nothing about *disconnect()*.

Somebody else suggests to use _mongoose.connection.close_.
But I can't find documentation of this too.

It is frustrating to not know where to search.
I don't want plenty of example from stack-overflow or other sites, I want the documentation.

Have I search in the API? I'm using the npm mongoose module, not the API.

Thanks,
Alessandro

**Comment by vkarpov15** [comment]
That's a good question. `.disconnect()` is admittedly a bit of a gray area, since most mongoose applications start a connection at server start and have no need to manually disconnect. Will look into it in early 2016.

**Comment by vkarpov15** [comment]
`disconnect();` is on the top level mongoose object, that is, `require('mongoose').disconnect();`, see [disconnect docs](http://mongoosejs.com/docs/api.html#index_Mongoose-disconnect). Connections have a [`close()` method documented here](http://mongoosejs.com/docs/api.html#connection_Connection-close). At a high level, `mongoose.disconnect();` calls `.close();` on all connections.
