### ISSUE TITLE
Why callback is undocumented on .connect() method?

### ISSUE THREAD

**Issue by alex75ita** [Automattic/mongoose#3705]
Hi,

I'm using mongoose ^4.3.0.
My code (probably inspired from some examples) is:
<pre>var mongoose = require("mongoose");
mongoose.connect(mongoDBConnection, function() {
    // do something... but in case of wrong URL ???
}
</pre>

So, I looked at documentation for .connect(...) in Connections... there is not mention for a callback?!?
The quick start uses another approach: the .on() with "error" or "open". It is the only "official" way?

Then there is the API documentation where the version _mongoose.connect()_ is used.

Quick start: [http://mongoosejs.com/docs/index.html]
Connections: [http://mongoosejs.com/docs/connections.html] (I call this "classic" docs)
API for connect: [http://mongoosejs.com/docs/api.html#index_Mongoose-connect]

I don't understand...
1. I'm not calling any API, the documentation with Mongoose#connect is like the one with mongoose.connect()? Am I using the API?
2. Have I to see the API docs or the "classic" docs? What is the differences?
3. Where is the explanation for the "callback" of mongoose.connect(uri, option, callback) ?
Is it called only for successful connections or either in case of error?

I have got a lot of confusion... but looking at the docs it grows instead of clarifying things.
I can found myself how it works experimenting... but I'm frustrated for this situation.

Thanks in advance,
Alessandro

**Comment by vkarpov15** [comment]
1. You usually don't need to use the callback to `mongoose.connect()`, 99% of the time it isn't useful. [Mongoose enables you to just call `mongoose.connect()` and then start using your models immediately](http://mongoosejs.com/docs/guide.html#bufferCommands), without waiting for mongoose to connect.

2. What are the "classic" docs? The docs you link to are all part of the core mongoose docs, and the API docs should be consistent with the guides that you linked to for "Quick start" and "Connections"

3. I don't think we have an explanation at the moment. The general idea is that it gets called with an error if there was a connection error, and with no error if you successfully connected. However, I have not seen a case where passing a callback to `mongoose.connect()` is useful.

**Comment by alex75ita** [comment]
Thanks vkapov15 for the answers.
Basically my problem is how to use the docs.
From main mongoose page the "read the docs" link get out on http://mongoosejs.com/docs/guide.html

But when I'm there, *where have I to searh for .connect() method*?
In the [connections] (http://mongoosejs.com/docs/connections.html) page (that I called "classic" ;) )
or in the API index page on [connect] (http://mongoosejs.com/docs/api.html#index_Mongoose-connect) paragraph (the "API docs")?
More in general I don't understand *why there is the guide and the API docs*???

You say "API docs should be consistent with the guides":
- Quick start:<br>
mongoose.connect('mongodb://localhost/test');<br>
db.on('error', console.error.bind(console, 'connection error:'));  <br>
// how can I "catch" the error (I mean in a try/catch)?<br>
db.once('open', function() {<br>
  // we're connected!<br>
});<br>
.on("")... where is the docs about this (read *how can I find the usage of "on" FAST*)?<br>
- Guide:<br>
mongoose.connect(uri) and mongoose.connect(uri, options);<br>
*Nothing about managing error*<br>
- API docs:<br>
Mongoose#connect(uri(s), [options], [callback])<br>
*_callback_ description is missing.*<br>

I'm still writing tests (with grunt, mocha, unit.js) and I had a lot of problems about:
a. disconnect before each test: now solved using always ".disconnect()" before every .connect() .
b. test a wrong URI or other kinds of problems: now I think I've to use _emitter_ (I still don't know how) but my first try was to use the callback in some way (might it have an "error" as argument?).

So, the point is that it is difficult to achieve this simply tasks just looking the docs.
(And now I'm afraid to search for Schema options about how to map entity in entity!)

Thank you

**Comment by vkarpov15** [comment]
The [connections guide](http://mongoosejs.com/docs/connections.html) is an overview of how connections work in mongoose, ideally you should read that once or twice to learn about connections and then refer to the API docs for more technical details. Unfortunately, we don't quite have a good guide about the different events that connections can emit right now, but you're more than welcome to contribute one :)
