### ISSUE TITLE
Less somewhat magic, more straighforward Schema declarations would be nice

### ISSUE THREAD

**Issue by robertleeplummerjr** [Automattic/mongoose#3707]
Currently we do:

``` javascript
schema.virtual('myVirtual').get(function() {
  return true;
});
```

And while the shorthand is rather nice, it would be nice to have a less seemingly magic means, like:

``` javascript
schema.myVirtual = (new mongoose.VirtualType).get(function() {
  return true;
});
```

or

``` javascript
schema = new mongoose.Schema({
  myVirtual: (new mongoose.VirtualType).get(function() {
    return true;
  })
});
```

or

``` javascript
schema.prototype = {
  myVirtual: (new mongoose.VirtualType).get(function() {
    return true;
  })
};
```

That way an IDE's can easily understand the project we are building, and easily allow for extra features, aiding the human counterpart.

**Comment by robertleeplummerjr** [comment]
Note, this is just an "it would be nice", not a bug.

**Comment by Jeff-Lewis** [comment]
It would be great if we could get IDE's such as WebStorm to provide auto-complete of Schema/Model properties, paths, and virtuals when developing. This is one thing I miss using Node+Mongoose vs .NET generated entity/NHibernate classes.

Could this be done using a mongoose plugin that generates the JSDocs for each schema?

**Comment by robertleeplummerjr** [comment]
I suppose a simple ide plugin would be fine.  But if we just had a trail that any IDE could follow, using a strongerly typed schema, it'd be 1 stone and multi birds.

**Comment by Jeff-Lewis** [comment]
Here's an example of a JSDoc'ed schema with methods that a JSDoc supporting IDE should be able to understand.
https://github.com/nagyv/estisia-wall/blob/master/lib/models.js

**Comment by vkarpov15** [comment]
I suppose a JSdoc-generating plugin could work, but dealing with the quirks of an IDE is outside the scope of mongoose core IMO. As a side note, I'd love to make it possible to declare virtuals in the `new mongoose.Schema()` call.

**Comment by hasezoey** [comment]
for anyone finding this issue, since the creation of this issue a `virtuals` schema options has been added, which means virtuals can now be defined "more closely to the schema", like:

([from the Schema#virtuals documentation](https://mongoosejs.com/docs/guide.html#virtuals))
```ts
const personSchema = new Schema({
  name: {
    first: String,
    last: String
  }
},{
  virtuals:{
    fullName:{
      get() {
        return this.name.first + ' ' + this.name.last;
      }
    }
  }
});
```

**Comment by robertleeplummerjr** [comment]
That'll do.
