### ISSUE TITLE
params in model

### ISSUE THREAD

**Issue by wormen** [Automattic/mongoose#3710]
I have a model like me it can pass parameters to them in the future on the basis of I could change the name of the collection
for example, there is such a call
```
Models.MenuSite(data).save(function(err, result){
});
```
or
```
Models.MenuSite.find({}, {}, function(err, result){
 });
```
how in this case, I can dynamically change collection name?

**Comment by vkarpov15** [comment]
Mongoose doesn't support changing the collection name of models at the moment unfortunately. What's your use case?

**Comment by wormen** [comment]
@vkarpov15 I need to dynamically change the name of the collection, using validation of the model

**Comment by wormen** [comment]
how change name of the collection, I figured out, but, changes  not apply

**Comment by vkarpov15** [comment]
You can just create a new model with the same schema. Mongoose doesn't support changing the underlying collection because you can get some unexpected behavior if you have concurrent requests.
