### ISSUE TITLE
findOneOrFail Query (ES6)

### ISSUE THREAD

**Issue by eloytoro** [Automattic/mongoose#3714]
It has been my experience that when the findOne and findById queries cant find a single match for the given criteria I would handle the `null` result as an error and pass it on to the next middleware.

``` javascript
User.findOne({}, function (err, user) {
  // user = null, err = null
  if (err) return next(err)
  if (user == null) return next(new Error('UserNotFound'))
})
```

This happens almost everytime, it would be so much better to have a method that sends an error when no document is found in order to avoid the extra error handling, but also looking forward to the async/await pattern coming up because middlewares throw errors making them much easier to handle, but less intuitive to manually propagate.

``` javascript
var {email} = yield User.findOne({}); // runtime error, cant read property email of null
```

Instead

``` javascript
var {email} = yield User.findOneOrFail({}); // throws before assignment
```

**Comment by eloytoro** [comment]
Also fixes #3457

**Comment by vkarpov15** [comment]
Also related to #3577. This would be very easy to implement as a plugin, but I'm hesitant to put it in mongoose core unless there's a lot of demand.

**Comment by eloytoro** [comment]
Going through the latest issues I see that Promise integration into mongoose is becoming somewhat of a trending topic.
Given that this would pretty much be a wrapper for

```javascript
Model.findOne({}).then(result => result || throw new Error('NotFound'))
```
And that many queries should be able to support this (such as `findById` or the 'update' variants), maybe a query modifier function would fit best, something like

```javascript
Model.findOne({}).notNull()
```

**Comment by vkarpov15** [comment]
We unfortunately don't have a good way to add custom query methods right now. There have been related issues opened previously but I can't quite find them, so I added a new one #3470. I've used the below plugin before with great success for this application:

```javascript
module.exports = function(schema, options) {
  options = options || { name: 'Object' };

  schema.statics.findByIdOrThrow = function(id) {
    var query = this.findOne({ _id: id });
    return query.then(function(doc) {
      if (!doc) {
        throw new StandardError(options.name + ' ' + id + ' not found', {
          status: status.NOT_FOUND
        });
      }

      return doc;
    });
  };
};
```

**Comment by gberger** [comment]
I think my definition of 'named scopes', as defined by [my plugin](https://github.com/gberger/mongoose-named-scopes), allows for custom query helpers?

**Comment by vkarpov15** [comment]
Yep that should help. Sweet plugin, nice use of proxies :+1: 4.5 has support for a similar feature

**Comment by gberger** [comment]
what feature @vkarpov15 ?

**Comment by vkarpov15** [comment]
#3740. See fbbba27ec5eb05afa5091cfd942003921d9e51ff for not-yet-released docs on the subject

**Comment by world** [comment]
yah gberger's plugin is super sugary yummy schtuff. :)
