### ISSUE TITLE
Virtual getter fails inside selectively populated model

### ISSUE THREAD

**Issue by blahoink** [Automattic/mongoose#3715]
Hey all, relatively new to mongoose and I just ran into an error where the virtual field of a populated model relies on the other non-virtual fields being populated too. Here's a brief example:

```javascript
PostSchema = new Schema({
  ...
  author: {
    type: String,
    ref: 'User'
  }
});
var Post = mongoose.model('Post', PostSchema);

UserSchema = new Schema({
  ...
  username: {
    type: String
  }
});
UserSchema.virtual('displayName').get(function() {
  return this.username;
});
var User = mongoose.model('User', UserSchema);

Post.find({}, function(err, post) {
  return post; // does not work - displayName of user is undefined
})
.populate({
  path: 'author',
  select: 'displayName'
});

Post.find({}, function(err, post) {
  return post; // works - displayName of user = username
})
.populate({
  path: 'author',
  select: 'username displayName'
});
```

I can kind of guess what's happening here - the db object is fetched with only those fields and then its virtual function is called. Fixing this would probably require rearranging the order of things and make this process slower and costlier. My question is that is there a way to get a virtual without getting all the other fields it relies on? Should I be using a virtual setter?

Thanks for your time.

**Comment by vkarpov15** [comment]
You can't really "get" a virtual, since a virtual is not stored in the database, it's computed from other fields in the document. Just do

```javascript
populate({
  path: 'author',
  select: 'username'
})
```

should work fine.
