### ISSUE TITLE
Query with projection that contains both includes and excludes causes weird behavior

### ISSUE THREAD

**Issue by talbronfer** [Automattic/mongoose#3717]
I have a project containing a method that returns all `Account`s in the database:

`Account.find({}, projection).lean().exec(function(err, results) {
// internal code
})`

Recently I refactored the projection so that it filters out the `_id` property;

```{
    "_id": 0,
    "name": 1,
    "address": 1
}```

Other than the Account object, our project also has several other basic objects quite similar to each other, all having a defined Schema that looks something like this:

```mongoose.Schema({
    id: Number,
    name: String,
    values: [
        {
            id: Number,
            value: String,
            sort: {
                type: Number,
                null: true
            },
            metadata: mongoose.Schema.Types.Mixed,
            createdAt: String,
            updatedAt: String,
            deletedAt: {
                type: String,
                null: true
            }
        }
    ]})

```

Recently I noticed that in certain cases, these Models return from Mongoose with the  `Values` property set to null, even though in the database `Values` is populated. In other cases, they would return just fine.

After some debugging I noticed that this only happens after I invoke the getAccounts method described above. This behavior was persistent until I physically restarted the Node service.

However, once I changed the projection to the older include-only format, all Models started to persistently return as per their schema and database representation.

**Comment by vkarpov15** [comment]
Is the `projection` variable in your `getAccounts()` function global?
