### ISSUE TITLE
Is mongoose streaming partial documents?

### ISSUE THREAD

**Issue by berlincityboy** [Automattic/mongoose#3720]
Hey,

I want to know if mongoose is streaming partial documents when I use it like this

`Collection.find().lean().stream().pipe(writeableStream)`

or only full documents. The problem is that I have nested objects (may be very deep) and my question is whether I have to change my data structure so that all my nested objects are stored as separate mongo documents or not?

Thanks for your help! :)

**Comment by vkarpov15** [comment]
Only full documents, mongoose has no mechanism for streaming partial documents.
