### ISSUE TITLE
updating date does not trigger modified internal

### ISSUE THREAD

**Issue by brandon-collins** [Automattic/mongoose#3722]
If we have a model:

    var Time = mongoose.model('Time', schema)

If we have a mongoose schema that looks like this:

    var schema = mongoose.Schema({ ts: Date })

and we have a mongoose document that exists in the db collection that looks like this:

    { _id: 'blah', ts: 'Tue Dec 29 2015 20:55:44 GMT-0800 (PST)' }

if we do this:

    Time.findOne({_id: 'blah'}).exec(function(err, doc) {
        doc.ts.setDate(31)
        doc.save(function(err2, updatedDoc) {
            console.log(updatedDoc.ts)
        })
    })

the console output will show 'Thu Dec 31 2015 20:59:33 GMT-0800 (PST)'
however, the actual data in the collection will not have been updated and the ts will still be 'Tue Dec 29 2015 20:55:44 GMT-0800 (PST)'

NOTE - the expected behavior is achieved if we do this (which tells me the document setter flags the document for update):

    doc.ts = new Date(doc.ts).setDate(31)
    doc.save()

I imagine this is because I am operating on the date object directly so the mongoose setters aren't aware that the document was actually modified and thus no actual mongodb 'update' call is made. I would consider this behavior a bug and I could find no mention of it in the docs. I looked in the mongoose source but couldn't identify if this was intended behavior. Would you mind, either documenting this behavior better or, even better, fix this behavior so that the internal 'modified' flags are set properly in this case and the db document is actually updated when we'd expect it to update. Thanks! I appreciate the lib, it's wonderful.

**Comment by vkarpov15** [comment]
Yeah mongoose isn't aware of in-place updates to date objects - there's no good way for us to support that without monkey-patching `Date.prototype`, which isn't great. I'll add this to the FAQ and date type docs.

**Comment by brandon-collins** [comment]
ok, thanks Valeri
