### ISSUE TITLE
TLSSocket & TLSWrap problem

### ISSUE THREAD

**Issue by eshujiushiwo** [Automattic/mongoose#3725]
Hey guys ,we met a problem.
There are a lot of TLSSocket & TLSWrap that use a lot of memory.
And we found out that the TLSSocket & TLSWrap contains each other.
Like:
```
TLSWrap @855
owner TLSSocket @372251
```
```
 TLSSocket @372251
 _handle, ssl TLSWrap @855
```
They hold each other,and each of them cost a lot of memory.
It`s looks like that if one of them do not release the memory,the others who hold or contains them will not release.

And the pool size of Mongoose is 5,but there r 49 "TLSSocket" at the same time.

**Comment by vkarpov15** [comment]
Are you connected to a standalone mongod or to a repl set?
