### ISSUE TITLE
fix the Docs

### ISSUE THREAD

**Issue by Spown** [Automattic/mongoose#3727]
Basically all of your links to the Api from the other parts of Docs are broken.

For example http://mongoosejs.com/docs/faq.html (first link on the page):
> The work-around is to use [MongooseArray#set](http://mongoosejs.com/docs/api.html#types_array_MongooseArray-set) available in Mongoose >= 3.2.0.

it points to the top of Api page because there is no ``#types_array_MongooseArray-set`` anchor on it.

**Comment by vkarpov15** [comment]
This is an issue with links to arrays, because the way mongoose wraps arrays changed a lot between 3.8 and 4.0. Thanks for pointing it out.

**Comment by Spown** [comment]
its not only about arrays - I've been stumbling upon dead anchors all the time.

* http://mongoosejs.com/docs/middleware.html : [init](http://mongoosejs.com/docs/api.html#document_Document-init)
* http://mongoosejs.com/docs/schematypes.html : [Buffer](http://mongoosejs.com/docs/api.html#schema-buffer-js)

Actually just recently I found [devdocs.io/mongoose](http://devdocs.io/mongoose-mongoose/) and been hapily using it since. I don't want to offend anyone, but it is much clearer and better structured than the official... Just a suggestion - use something that asserts docs consistency and generates a compact navigation automatically, like [JSDuck](https://github.com/senchalabs/jsduck) or something...

**Comment by vkarpov15** [comment]
Thanks for the suggestion. The docs could definitely use some work and that's a high priority for the next few months. Feel free to report any dead anchors you find as bugs and we'll fix them, much appreciated :)
