### ISSUE TITLE
Performance Degradation: Fix for #3461 causes severe latency

### ISSUE THREAD

**Issue by parisholley** [Automattic/mongoose#3728]
See below...

**Comment by parisholley** [comment]
I take that back, i need to investigate more as that didn't help...*sigh*

**Comment by parisholley** [comment]
appears the driver change was just a temporary false positive. i've isolated a single server in prod and have been testing jumps between different mongoose versions. at this point it appears that some commit introduced between 4.1.11 and 4.1.12 cause some serious performance degradation (for me). i'll try stepping up per version next...

**Comment by parisholley** [comment]
Here is a breakdown of the performance degradation I am seeing. The performance impact is based upon my application response time increases as I moved from commit to commit. I was previously on the 4.0.x release before upgrading to get new features.

Commit | Performance Impact
-----------|----------------------------
1f6aa7a91e36a8e6f7b8c1a45f2c87ba3eb71963 (4.1.11 Tag) | None
335513cae34fafbfe43e29f520965af28d60e255 (#3461 fix) | 33% Slower
c8b3e273e8da3369ab4aa6e700f45f7c4839a3cb (#3461 refactor) | 100% Slower
d7c10cbac3dc5208661a12289b33d626321a502e (4.3.4 Tag) w/ #3461 removed | None

perhaps @vkarpov15 / @boblauer can shed some light on why that "fix" could cause such an issue? it could be something deep within how I am using the resulting mongo objects (ie: passing arrays to modules like underscore or Lazy.js)s...

**Comment by vkarpov15** [comment]
Hmm could you share your benchmarks? I don't see why you'd have such a big performance impact from that change.

**Comment by parisholley** [comment]
@vkarpov15 The benchmarks were from watching new relic from deploy to deploy. I had this code take my cluster of 6 severs down twice when pushed live :) I unfortunately do not have much time to dig into a profiler, so I will just be running off a fork for now.

**Comment by vkarpov15** [comment]
I'll mark this as help wanted. There's not really much I can do without being able to repro your performance degradation, and without more info I'll just be taking shots in the dark.
