### ISSUE TITLE
Question about validation

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3731]
This is a question, not really an issue, but I was really surprised to read the following in the docs:

> In Mongoose 4.x, update validators are off by default .
> One final detail worth noting: update validators only run on $set and $unset operations.

What was the reason update validators were turned off by default?

It means we now either have to explicitly turn it on for *all* update operations, since we relied on Mongoose to do the basic validation like required fields, min/max values, etc., or build our own validation service to validate for both create/update.

Can this setting be turned on globally by default somewhere via configuration?

**Comment by vkarpov15** [comment]
They're turned off by default to minimize backwards breaking changes in 4.0. Update validators have a significant caveat - in an update validator, `this` is null, whereas `this` is the document in a regular old `.validate()`, and that's sufficient enough to make update validators an opt-in behavior until at least 5.0.

The best way to turn them on by default is using query middleware:

```javascript
schema.pre('update', function() {
  this.update.runValidators = true;
});
```

You can pretty easily write a [plugin](http://mongoosejs.com/docs/plugins.html) to do this for you.

**Comment by adambuczynski** [comment]
Thanks for the explanation
