### ISSUE TITLE
Ability to register plugins for all schemas

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3732]
In our application, we have the following code in every single model file:

```js
/**
 * Transformation to JSON
 */
SomeSchema.options.toJSON = {
  transform: function(doc, ret) {
    ret.id = ret._id.toString();
    delete ret._id;
    delete ret.__v;
  }
};
```

Is there a preferred/safe way to extend Mongoose's default toJSON() behaviour to apply this transformation to every model?

**Comment by vkarpov15** [comment]
Unfortunately we don't have a way to make this global to all schemas. You can DRY this up and make it a one-liner using [plugins](http://mongoosejs.com/docs/plugins.html). We'll add a way to register a plugin for all schemas in a future release.

**Comment by adambuczynski** [comment]
That's be a great feature, good to hear it's in the cards.

**Comment by vkarpov15** [comment]
This feature already exists actually, I had just missed it.

```javascript
var mongoose = require('mongoose');
mongoose.plugin(myPlugin);
// Every schema will now get `myPlugin`
```

**Comment by adambuczynski** [comment]
Cheers thank you, I will try it out tonight.

**Comment by adambuczynski** [comment]
A note regarding this, if registering a plugin on a schema, beware that the plugin will be called *after* the schema has been defined, so if you set properties on the schema via a global plugin like this, be careful that you don't overwrite any properties you may have set for specific schema's.

For example:

```js
UserSchema.options.toJSON = {
  transform(doc, ret) {
    //custom transform logic here
  }
};
```

```js
module.exports = function toJsonPlugin(schema) {
  //At this stage, schema.options.toJSON has already been set for the UserSchema
  //Therefore, the following would overwrite this. Ensure you call the schema specific
  //transform function after applying the global logic below.
  schema.options.toJSON = {
    transform(doc, ret) {
      //global transform logic
    }
  };
};
```

Maybe worth mentioning in the docs somewhere.

**Comment by Jeff-Lewis** [comment]
@adambuczynski Agreed, this one bit me this week...
