### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by jadencarver** [Automattic/mongoose#3736]
I noticed code that implements Google Analytics for the account UA-1122274-9 - Why is this here?  This is very suspicious.  Who owns the account?  Who is tracking people?

**Comment by jadencarver** [comment]
The offending file: https://github.com/enyo/postman/blob/master/node_modules/mongoose/docs/includes/googleanalytics.jade

**Comment by eloytoro** [comment]
Google analytics only runs on browsers, and in the case of mongoose, only in it's documentation, which is compiled to http://mongoosejs.com/docs/, which you could run locally if you wanted by running the [website.js](https://github.com/Automattic/mongoose/blob/master/website.js) script
To learn more about google analytics [visit their site](https://www.google.co.ve/analytics/)

**Comment by jadencarver** [comment]
That's not the problem, I know what Google Analytics is. My issue is - why are people being tracked when they read documentation, both online and offline.  That's an invasion of privacy, and since this is an open source project - I want to know who has access to that information.

**Comment by vkarpov15** [comment]
Honestly I have never looked at that information (not even sure if I have access to it), it was introduced by previous maintainers. However, I can see how the information would be valuable: its good to see which pages are getting more traffic so we know where to focus our efforts documentation-wise. I also don't really see how using Google Analytics can be considered an invasion of privacy in mongoose's case; we don't ask for your email address or any personally-identifiable information, as far as we're concerned you're just one of X number of people that have hit a page. Also, using Google Analytics on open-source docs is not unprecedented, Express, Hapi, Bower, and Gulp all use GA as well.
