### ISSUE TITLE
Support change detection for in-place updates to date objects?

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3738]
For instance `doc.createdAt.setDate(2011, 5, 1);` should get saved to the db without needing to call `.markModified()`, re #3722. Discussions and +1's welcome.

**Comment by TrejGun** [comment]
are you going to call setter too?

**Comment by vkarpov15** [comment]
That would be ideal. Not planning on supporting this behavior unless there's a lot of demand though, you don't really see people using in-place updates on dates that often in my experience.

**Comment by stableShip** [comment]
+1

**Comment by vkarpov15** [comment]
Going to close this unless there's very strong objections. Too many caveats, not much value, especially since we have this in the FAQ.
