### ISSUE TITLE
set time zone in the schema

### ISSUE THREAD

**Issue by thavaamm** [Automattic/mongoose#3739]
Hi Sir,

I need to set time zone for created_date in the schema, for eg. my timeZone is 'Asia/Calcutta'. Could you guide me?

sample code:
-----------------
var userSchema = new mongoose.Schema({
    user_name: String,
    created_date: {type:Date, default:Date.now},
}

**Comment by vkarpov15** [comment]
[Dates in MongoDB are just 64-bit ints](https://docs.mongodb.org/manual/reference/bson-types/#date). The way I usually attach a timezone is with a string:

```javascript
var userSchema = new mongoose.Schema({
  user_name: String,
  created_date: {type:Date, default:Date.now},
  tz: String // e.g. 'Asia/Calcutta' or 'America/New_York'
}
```

**Comment by thavaamm** [comment]
Thanks VKarpov for your immediate response, But i think you understood my question wrongly, let me correct it, I need to set default timezone along with Date.now in the field of created_date. Is there any possibilities like below?

var userSchema = new mongoose.Schema({
  user_name: String,
  created_date: {type:Date, default:Date.now, timezone: 'Asia/Calcutta'}
}

**Comment by vkarpov15** [comment]
A date gets stored in the database as an int, so there's no meaningful way to associate a timezone with it. You're going to need a separate field to store the timezone.

**Comment by TahaKhanAbdalli** [comment]
Try mongoose-timezone

**Comment by Shazil1** [comment]
How can i add TZ to mongoose timestamps?
