### ISSUE TITLE
Custom query methods

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3740]
Like in https://github.com/Automattic/mongoose/issues/3714#issuecomment-169216844

**Comment by onbjerg** [comment]
Possibly also related to #2372?

**Comment by vkarpov15** [comment]
Good catch @onbjerg :)

**Comment by gberger** [comment]
I think my definition of 'named scopes', as defined by [my plugin](https://github.com/gberger/mongoose-named-scopes), allows for custom query helpers?
