### ISSUE TITLE
Question from docs- populate and `stories : [{ type: Schema.Types.ObjectId, ref: 'Story' }] `

### ISSUE THREAD

**Issue by dman777** [Automattic/mongoose#3745]
I've been reading [Mongoose documentation on populate](http://mongoosejs.com/docs/populate.html)  and wanted to know, please:

In personSchema, is `stories : [{ type: Schema.Types.ObjectId, ref: 'Story' }]` only used for `.populate('stories')`? Could it be left out if I do not use the second pointer to populate `aaron` with stories he owns?

**Comment by vkarpov15** [comment]
Sure, `stories` is a list of stories the user owns, so if you don't need that information you don't have to store it.
