### ISSUE TITLE
Add support for NeDB

### ISSUE THREAD

**Issue by JamesMGreene** [Automattic/mongoose#3746]
I would love to see [NeDB](https://github.com/louischatriot/nedb) (basically the SQLite equivalent of MongoDB) be a supported backend for Mongoose.  Any chance that is something that can already be achieve today unbeknownst to me?  :pray:

**Comment by vkarpov15** [comment]
Not supported atm, and FWIW not likely to be supported anytime soon. It's already sufficiently tricky to get mongoose to work as expected against multiple versions of MongoDB, supporting a separate database will require a lot of overhead. You can always fork and write your own though :)

**Comment by JamesMGreene** [comment]
😢

**Comment by vkarpov15** [comment]
Yeah it's sad and I'd love to help, but we already barely have the capacity to keep up with mongodb, not enough resources to keep up with a completely separate DB. Sorry about that :palm_tree:
