### ISSUE TITLE
Split schema creation and usage between node modules fail if "npm linked"

### ISSUE THREAD

**Issue by gcoupelant** [Automattic/mongoose#3749]
Let's say i have two npm modules, A & B, each one has it own node_modules/mongoose (no npm link), but A depends on B using npm link.

If I create a `schema` in A, call `mongoose.createConnection(...).model(...)` in B and return its result to A. All model method will fail since no schema were created using B's mongoose.

The error is: 
```
TypeError: Expecting a function in instanceof check, but got undefined"
at Object.toObject (.../node_modules/mongoose/lib/utils.js:389:22)"
```

This won't be a problem in production, since A & B will have the same mongoose, but in my dev environment, I have to call `mongoose/lib/utils#isMongooseObject` to somehow "init" mongoose.

**Comment by vkarpov15** [comment]
This isn't really behavior that we can support effectively - its really tricky to test what happens when you have two separate versions of mongoose floating around. I'll leave this open for +1's, but I don't see this being a priority.

**Comment by gcoupelant** [comment]
I agree, the "workaround" is quite simple, and I hope this will help :)

**Comment by jsumners** [comment]
I'm having this issue. I have a parent module that passes a mongoose instance into a plugin module. The plugin defines a schema and exports a method that the parent can use to issue a query. When the parent issues the query it fails:

```
TypeError: Expecting a function in instanceof check, but got undefined
    at Object.toObject (/path/to/parent/node_modules/mongoose/lib/utils.js:419:22)
```

Both modules depend upon the same version of mongoose: 4.4.6.

**Comment by vkarpov15** [comment]
@jsumners can you show me a code sample and tell me which plugin you're trying to use?

**Comment by jsumners** [comment]
@vkarpov15 sadly, I can't. The project isn't OSS; at least not yet. However, I "solved" the problem by using the passed in mongoose instance to define schemas. But that's a lot of handing the, what I see as, database connection around to parts of code that don't really need it. Why wouldn't a schema be a static object that can be created by any `require`d instance of mongoose and used by any instance that is actually connected?

**Comment by vkarpov15** [comment]
That would require multiple versions of mongoose to be compatible with each other, which isn't always going to be the case. I would be surprised if you passed a mongoose 3.8.x schema to a mongoose 4.x model and nothing went horribly wrong. Either way, it's really hard for us to be able to test "do mongoose 3.8 schemas work with mongoose 4.5?", and IMO it's really not worth the effort

**Comment by jsumners** [comment]
I don't why it would require any such thing. In fact, I said I am using the exact same version.

**Comment by vkarpov15** [comment]
That's strange, how are you getting a separate instance of mongoose then? npm should be smart enough to consolidate...

**Comment by jsumners** [comment]
Okay, I'm not sure why I was getting the error. I just recreated the scenario in a simple project -- https://github.com/jsumners/mongoose-test . The case that should be failing in that project isn't. So, I have no clue why the error was occurring before.

**Comment by vkarpov15** [comment]
Glad it works. I'll close this issue for now.

**Comment by nswbmw** [comment]
I'm having this issue.

My situation: 

- myproject(require `myproject-database-schemas` and `myproject-services`): main project, inject some plugins & statics.
- myproject-database-schemas: only mongoose schemas.
- myproject-services(require `myproject-database-schemas`): services files, no plugins or statics.

When install with npm@3, `myproject-database-schemas` will installed in `myproject/node_modules`, `myproject` and `myproject-services` will require the same module. So, `myproject-services` will throw errors.

My solution:

`cd myproject-services && npm i`, installed `myproject-database-schemas` in `myproject-services/node_modules`...
