### ISSUE TITLE
document.execPopulate() not returning promise

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#3755]
I wanted to reopen the #3187 with:

I'm facing the same issue with the latest version mongoose@4.3.5, in this test code:

      var mongoose = require('mongoose');
      mongoose.Promise = require('bluebird');

      var companySchema = new mongoose.Schema({
        name:  String,
        description:  String
      });

      var userSchema = new mongoose.Schema({
        name:  String,
        company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company'}
      });

      var Company = mongoose.model('Company', companySchema);
      var User = mongoose.model('User', userSchema);

      mongoose.connect(
        'mongodb://127.0.0.1/test',
        {},
        function (err) {
          if (err) {
            return console.error(err);
          }

          var company = new Company({name: 'Reynholm Industrie'});
          var user = new User({name: 'Douglas', company: company._id});

          Promise
            .all([
              company.save(),
              user.save()
            ])
            .then(function () {
              return User.findOne({_id: user._id}).exec();
            })
            .then(function (dbUser) {
              return dbUser.populate('company').execPopulate();
            })
            .then(function (dbUser) {
              console.log(dbUser.company);
            });
        }
      );

dbUser.populate('company').execPopulate(); does not return a promise but the model
I only get it working when using the classic:

    dbUser.populate('company', function (err, dbUser2) {
        console.log(dbUser2.company); // populated
    })

**Comment by jbdemonte** [comment]
In the interval, another issue has been added before this one (I was too long to isolate it :) )
#3753

**Comment by vkarpov15** [comment]
Will fix, sorry about the snafu :palm_tree:
