### ISSUE TITLE
this.listeners is not a fucnction

### ISSUE THREAD

**Issue by badars** [Automattic/mongoose#3758]
Its silly but i am thinking its better to be discussed here.
I am using the key named 'listeners' in schema , something like
```
var User = new Schema({
         email: String,
         listeners : [{
                type: Schema.Types.ObjectId,
                ref: 'User'
        }],
})

```

I am getting error from document.js:1774:12 , because listeners keyword is already reserved.  Is there any possibility to avoid this kind of issue by adding some pre keyword ? Thanks.
```
version : 4.3.4
````

**Comment by vkarpov15** [comment]
No way to work around that, because one of the fundamental parts of a document is that it fulfills the event emitter API, which includes a `listeners()` function. Removing it would be a major backwards breaking change. Either rename the listeners field or move it away from the top level:

```javascript
var User = new Schema({
         email: String,
         subdoc: {
             listeners : [{
                  type: Schema.Types.ObjectId,
                  ref: 'User'
              }]
        },
})
```
