### ISSUE TITLE
Question- How to reference embedded document array element for populate() 

### ISSUE THREAD

**Issue by dman777** [Automattic/mongoose#3762]
If I may ask, please...

I have `users.js` schema with a embeded document array `pets`. For each user, a user can have multiple pets(usually no more than 3 I would think). 

For each pet, there would be a daily chart. So it would be many daily charts for a pet.  I have read with embedded documents that each array element is indexed. In `daily.js`, how can I reference the pet it would belong to for the `populate()` function? 

```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var userSchema = new Schema({
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    username: { type: String, required: true, unique: true },
    location: String,
    pets: [{ name: 'string', animalType: 'string'}], //could have more than one pet
    created_at: Date,
    updated_at: Date
});
```
```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var dailySchema = new Schema({
  tite: String,
  _pet: { type: Number, ref: 'User.pet' }, // not sure how to reference name in user.pets[#] array
  created_at: Date,
  updated_at: Date
});
```

**Comment by dman777** [comment]
Found this to be a anti-pattern. Closing.

**Comment by vkarpov15** [comment]
You'd have to get the whole user, not just the pet. You could reference the user and the index of the pet in the `pets` array in `dailySchema`.
