### ISSUE TITLE
limit and skip doesn't work on mongodb 3.2

### ISSUE THREAD

**Issue by pongib** [Automattic/mongoose#3763]
It seem like mongodb 3.2, limit and skip field must be numeric number. Can you embed cast string to int into your mongoose.

**Comment by vkarpov15** [comment]
`limit()` and `skip()` explicitly expect a number in the [mongoose docs](http://mongoosejs.com/docs/api.html#query_Query-limit) and we don't currently support any casting. Do you want `.limit('10');` to work like `.limit(10)` ?

**Comment by pongib** [comment]
Thank you for your reply. I use limit and skip as options parameter like this 
`Product.find({}, '-__v -updatedAt', { lean: true, skip: skip, limit: limit, sort: sort }, function (err, results) { do stuff })`, everything work fine in mongo 3.0 but when I change to 3.2, error occur and display something like skip and limit must be numeric. But when I cast to numeric everything work well. It ok if I just cast to number, But I curious why it work on mongo 3.0 but doesn't work on mongo 3.2. I use mongoose 4.3.5. Thank you.

**Comment by vkarpov15** [comment]
Same thing happens in the shell:

```
$ ~/Workspace/10gen/mongodb-test-makefile/3.0.5/bin/mongo
MongoDB shell version: 3.0.5
connecting to: test
Server has startup warnings: 
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] 
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] 
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-01-18T09:22:16.328-0500 I CONTROL  [initandlisten] 
> db.test.find().limit('10');
> ^C
bye
$ ~/Workspace/10gen/mongodb-test-makefile/3.2.0/bin/mongo
MongoDB shell version: 3.2.0
connecting to: test
Server has startup warnings: 
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] 
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] 
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-01-18T09:22:54.881-0500 I CONTROL  [initandlisten] 
> db.test.find().limit('10');
Error: error: {
	"waitedMS" : NumberLong(0),
	"ok" : 0,
	"errmsg" : "Failed to parse: { find: \"test\", filter: {}, limit: \"10\", singleBatch: false }. 'limit' field must be numeric.",
	"code" : 9
}
```

I opened up https://jira.mongodb.org/browse/DOCS-6995 because this should be documented on the mongodb server.

**Comment by rgalindo33** [comment]
was this issue solved? im having the same problems and would like to know the status of it

**Comment by vkarpov15** [comment]
It's a won't fix @rgalindo33

**Comment by StefanBalea** [comment]
/*create user query*/
            let userQuery = UserModel
                .find({})
                .limit(Number(limit));
Casting to Number fixed the problem.

**Comment by zahid492** [comment]
This code work for me mongo 3.28  
Delivery.find({}, '-__v').limit(parseInt(req.params.limit)).skip(parseInt(req.params.skip)* parseInt(req.params.limit)).sort({
        _id: -1
      }).exec(function(err, data) {
        if (err) return res.json({
          'error': err
        })
        return res.json(data)
      });

**Comment by markstos** [comment]
I also ran into this change when upgrading from Mongoose 3.8 to Mongoose 4.13 when running MongoDB 3.2. Mongoose 3.8 would accept strings for `limit()` and `skip()`, while the same code breaks with Mongoose 4.13 with a parse error.  Both Mongoose 3.8 and Mongoose 4.13 document that `skip()` and limit()` accept a number as input, so it's not a backwards-incompatible change according to the doc, but the difference could still break some apps that depended on the looser behavior of Mongoose 3.8. For this reason, I think it's worth a mention in the 4.0 release notes under Backwards-Breaking Changes (which is my guess at when the behavior change was introduced):

> #3763: limit() and skip() now require their input to be numbers. Mongoose 3.8 was already documented to require numbers here, but previously strings were accepted and cast to numbers. Passing numbers as strings will now throw a parse error. 

If that's acceptable I can make the addition to the wiki page.

**Comment by vkarpov15** [comment]
@markstos please do, I appreciate your help :+1:

**Comment by markstos** [comment]
Ah, sorry, looks like I don't have edit rights on the wiki:
https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes Perhaps it's
restricted to collaborators only.

At least it should be a quick copy/paste to add the text I wrote.

**Comment by vkarpov15** [comment]
@markstos done https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes :+1:

**Comment by lukegorman** [comment]
parseInt works... 
.
Publication.find({}).skip(parseInt(query.skip))
      .toArray(function(err, result){
.
.
