### ISSUE TITLE
timestamps option does not work with non-ObjectId _ids

### ISSUE THREAD

**Issue by ccollie** [Automattic/mongoose#3767]
I recently changed from mongoose-concrete-timestamps to the internal implementation and immediately go an error on insert

TypeError: this._id.getTimestamp is not a function

Most of my models use a self-written plugin to generate auto-incrementing numeric ids (using hi-lo for performance on bulk inserts). The internal implementation of timestamps seems to assume that the _id field is always an ObjectId, hence the blowup.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix

**Comment by vkarpov15** [comment]
@ccollie that's strange, the below script executes without error for me in 4.3.6. Looks like the internal timestamps implementation knows to avoid _id unless you're using the default _id schema path.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3767');

var Schema = mongoose.Schema;

var testSchema = new Schema({
  _id: Number
}, {  
  timestamps: true
});   

var Test = mongoose.model('gh3767', testSchema);

Test.create({ _id: 5 }, function(error, doc) {
  assert.ifError(error);
  assert.ok(doc.createdAt);
  process.exit(0);
});
```

Can you try modifying the above script to reproduce your issue?

**Comment by vkarpov15** [comment]
Issue's gone stale, re-open if you still have this issue.
