### ISSUE TITLE
Access to passed values from default function

### ISSUE THREAD

**Issue by lgomez** [Automattic/mongoose#3781]
Hi all,

Is there a way to access the parameters being passed to a new instance of a model from a schema type's default function? Specifically:

``` javascript
var crypto   = require('crypto');
var db       = require('../db').db; // <- ref to mongoose
var Schema   = db.Schema;

var schema = Schema({
  email          : { type: String, index: true, required: true, unique: true },
  precomputedhash: { type: String }
});

schema.path('precomputedhash').default(function(doc) {
  console.log(doc); // -> undefined
  var hmac = crypto.createHmac('sha256', 'fake secret');
  var sig = hmac.update(doc.email /* <- what I'd like */).digest('hex');
  return sig;
});
```

I need to create a precomputed hash as soon as I instantiate. I know I can generate that hash as a default at the appropriate time but I need it to use the doc.email (ideal) or the objectid (not ideal but ok). Yes, a hook would do the trick but I do need this to be accessible after instantiation and before saving.

Further details: you may be asking yourself why... In this particular case, I need to generate a hash for a specific third-party service with which we are integrating. I need a predictable way to generate the hash because it is the way I can access user's data on that service. In this case, the hash is generated using a recipe the provider defined.

If I can't fund a solution, worse case scenario, I'll have to document that a record must be saved before being able to get that precomputedhash but I'd like to avoid that.

Thank you!

**Comment by vkarpov15** [comment]
```javascript
schema.path('precomputedhash').default(function(doc) {
  var hmac = crypto.createHmac('sha256', 'fake secret');
  // In `.default()`, `this` refers to the document
  var sig = hmac.update(this.email).digest('hex');
  return sig;
});
```

There's some relevant docs in the [defaults guide](http://mongoosejs.com/docs/defaults.html). Just be wary of using `this` in `.default()` if you're going to be using `setDefaultsOnInsert` - the defaults guide has more info on that.

**Comment by siboulet** [comment]
@vkarpov15 what version of Mongoose where you using here? I can't seem to get `this` to refer to the document in `default()`. https://github.com/Automattic/mongoose/issues/1581

**Comment by vkarpov15** [comment]
@siboulet  the first param to the function is the doc. We will add it as the context for the default function as well

**Comment by siboulet** [comment]
@vkarpov15 I must be doing something wrong because taking my example in #1581 default() doesn't seems to receive any parameter at all.

```
schema.path('arnold').default(function(post) {
  return post.title && post.title.match(/arnold/i);
});
```

Yields:

```
TypeError: Cannot read property 'title' of undefined
```

Confirmed `post` is undefined.

Node v6.11.0
Mongoose 4.13.9

**Comment by vkarpov15** [comment]
Actually yes you're right, the first param is **not** the document, I was mistaken, the correct way to access the document in a `default` function is using `this`. Unfortunately, right now the `default` function gets called before the actual document is built, so if you access `this` you won't see any of the object's properties:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  await mongoose.connection.dropDatabase();

  const schema = new Schema({ title: String, arnold: String });
  schema.path('arnold').default(function() {
    // Will be an empty object
    console.log(this);
  });

  const Model = mongoose.model('Test', schema);

  new Model({ title: 'Test' });
}
```

Will fix this :+1:

**Comment by vkarpov15** [comment]
See #6119 for fix, will take some time to re-review because this is a sizable change.
