### ISSUE TITLE
modelName undefined in instance methods

### ISSUE THREAD

**Issue by hstonge** [Automattic/mongoose#3782]
Consider the following test, which is based on an example in the [official doc](http://mongoosejs.com/docs/guide.html#methods):

```javascript
var mongoose = require('mongoose');
    mongoose.connect('mongodb://localhost/modelName_test');

var animalSchema = new mongoose.Schema({ name: String, type: String });
    animalSchema.methods.findSimilarTypes = function (cb) {
      var mName = this.modelName;
      console.log('findSimilarTypes mName=' + mName);
      return this.model(mName).find({ type: this.type }, cb);
    };

var Animal = mongoose.model('Animal', animalSchema);

var dog = new Animal({ type: 'dog' });
    dog.findSimilarTypes(function(err, result) {
      if (err) {
        console.error(err);
      } else {
        console.log(result);
      }

      mongoose.disconnect();
    });
```

Why is the `model()` method accessible in the `findSimilarTypes` instance method, but not the `modelName` property ?

Thanks for your help.

**Comment by hstonge** [comment]
Well, a quick look at the source code for [document.js](https://github.com/Automattic/mongoose/blob/master/lib/document.js) hints that **modelName** could actually be accessible in instance methods via `this.constructor.modelName`. 

I find this a bit hack-ish; am I missing something ?

**Comment by vkarpov15** [comment]
Not hackish, `doc.constructor` is the canonical way to access the model used to create the document. I'd recommend you just do

```javascript
var model = this.constructor;
return model.find({ type: this.type }, cb);
```

**Comment by hstonge** [comment]
Oh, alrighty then! Thanks @vkarpov15 !
