### ISSUE TITLE
upsert option doesn't work with  FindOneAndUpdate 

### ISSUE THREAD

**Issue by Deliamalvarez** [Automattic/mongoose#3784]
When using FindOneAndUpdate method with {'upsert': true or false }  and a Post request for a restful api it inserts the new element if it doesn't find it no matter if upsert it's specified. However when using FindByIdAndUpdate method with upsert option specified it works fine.

**Comment by vkarpov15** [comment]
Code sample please? We have tests in place for upsert, and `findByIdAndUpdate()` just calls `findOneAndUpdate()` anyway.

**Comment by vkarpov15** [comment]
Issue's gone stale, closing.
