### ISSUE TITLE
Apply `toJSON` to children nodes

### ISSUE THREAD

**Issue by Beingbook** [Automattic/mongoose#3789]
Hello.
I use `toJSON` to filter or transform nodes' content.
toJSON is called only root node in object. Children nodes are not.
It matters when it's populating.
Can it be solved?

**Comment by vkarpov15** [comment]
Can you clarify your question please? I don't understand.

**Comment by Beingbook** [comment]
@vkarpov15 , sorry and let me repeat with example.
There are two models `User` and `Post`. The schema is:
```js
const userSchema = {
...,
passports: [{ ref: 'Passport', type: ... }], // passports has passwords or third-party authentication token.
...,
};
const postSchema = {
...,
author: { ref: 'User', type: ... },
...,
};
// To hide passports of user documents, I use `toJSON transform` like:
userSchema.options.toJSON.transform = (doc, ret) => { delete ret.passports };
// API endpoints
app.get('/users/:userId', await (req, res) => {
....
return res.send(user); // toJSON does work! user has no passports.
});
app.get('/posts/:postId', await (req, res) => {
...
return res.send(post); // populated user does not execute toJSON.
});
```
To solve above problem, I should write code like this:
```js
return res.send({
...post,
user: user.toJSON(),
});
```
It's something dirty because I have to re-transform every models that reference `User` model.

Thank you!

**Comment by vkarpov15** [comment]
Looks like you're using express, why don't you just [use `res.json()`](http://expressjs.com/en/4x/api.html#res.json)? That will call `.toJSON()` for you.
