### ISSUE TITLE
Efficient deep update

### ISSUE THREAD

**Issue by tomerb15** [Automattic/mongoose#3794]
I was wondering if there is a better way to update subDocument than this:
```
updateCounter: function(listOfIds, restId){
        db.model('rests').findById(restid, function (e, data) {
            data.markModified("menu");
            for(var i=0 ; i< listOfIds.length ; i++){
                data.menu[courseList[i]].counter+=1;
            }
            data.save();
        });
    }
```
the relevant scheme is:
```
var restsSchema = new Schema({
    name: String,
    menu: mongoose.Schema.Types.Mixed
});
```
Document can look like:
```
{
    name: "My yummi rest"
    phoneNumber: "1206454545"
    menu:{
             "1":{
                  name: "Pizza",
                  soldCounter: 0
               },
             "2":{
                  name: "Pasta",
                  soldCounter: 0
                },
            "3":{
                  name: "Steak",
                  soldCounter: 0
                }
         }
}
```
I also fear from data integrity in case few requests will come at once.
Is there an elegant way of doing so with `$inc` and `update()`?

**Comment by vkarpov15** [comment]
Sure, just build up an update op.

```javascript
var update = { $inc: {} };
for (var i = 0; i < ids.length; ++i) {
  update.$inc[`menu.${ids[i]}.soldCounter`] = 1;
}
Rests.update({ _id: restid }, update, function(error) {
  // ...
});
```

**Comment by tomerb15** [comment]
It seems to be very not efficient to make a loop.
Lets say i have changed my Scheme and document to look like:
 
```
var restsSchema = new Schema({
    name: String
    menu: [mongoose.Schema.Types.Mixed]
});
```
My document can look like:
```
{
     name: "Sandwiches & More",
     menu: [
                {id:1,name:"Tona Sandwich",price: 10, soldCounter:0},
                {id:2,name:"Salami Sandwich",price: 10, soldCounter:0},
                {id:3,name:"Cheese Sandwich",price: 10, soldCounter:0}
     ]
}
```
The collection rests is indexed with:

`db.rests.createIndex( { "menu.id": 1} , { unique: true })`
Lets say i have this array of ids `[1,3]` and based on that i need to increment the soldCounter by 1 of menu items with ids=1 or 3.

What will be the must efficient way of doing so?

**Comment by vkarpov15** [comment]
The loop is really the most efficient way to do that. Unless you expect to pass a huge number of ids, the performance cost of the update will be dominated by the network round-trip to the database.
