### ISSUE TITLE
special chars break $regex query

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#3796]
I tried this query:
```
mymodel.find({
        content:{'$regex': 'ello [pos'}
    })
```
It doesn't match this document
```
{ 
    "_id" : ObjectId("56a6192d8903f7dc101d782d"), 
    "content" : "hello [post]", 
    "__v" : NumberInt(0)
}
```

the special char "[" break the query, there is a better method to accomplish a query "LIKE" (sql speaking)?

**Comment by vkarpov15** [comment]
Just use [the `escape-regexp` module or something similar](https://www.npmjs.com/package/escape-regexp) to escape the user input before putting it into a query.

**Comment by alfredopacino** [comment]
I found this on stackoverflow
```
query.replace(/[-[\]{}()*+?.,\\/^$|#\s]/g, "\\$&");
```

maybe there is no need of a module, or the module is more safe somehow?

**Comment by vkarpov15** [comment]
The module is pretty much the same thing: https://github.com/component/escape-regexp/blob/master/index.js .

**Comment by alfredopacino** [comment]
Sorry I reopen, I've just noticed this code doesn't work if I have special char in the user name ( "Micke[y] mouse").
```
app.get('/api/community/users', function(req,res) {
    var q= (req.query.q) ?
            escape(req.query.q):
            '.*';
    com_user.find({name:{$regex: q}}, function(err,data){
        res.json(data);
        
    });
});
```

**Comment by vkarpov15** [comment]
@alfredopacino the below script executes without error for me. What does your regexp look like?

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var escapere = require('escape-regexp');

mongoose.connect('mongodb://localhost:27017/gh3796');

var PostSchema = mongoose.Schema({
  content: String
});

var Child = mongoose.model('Child', PostSchema);

Child.create({ content: 'Micke[y] mouse' }, function(error, doc) {
  Child.findOne({ content: new RegExp(escapere('Micke[y')) }, function(error, doc) {
    assert.ok(doc);
    process.exit(0);
  });
});
```

**Comment by vkarpov15** [comment]
Issue's been stale for a while, closing.

**Comment by alfredopacino** [comment]
sorry I can't reproduce myself neither.
Maybe the mistake was somewhere else :+1: .

**Comment by askri2pac** [comment]
hi @vkarpov15, sory for reopen the issue but i have a question, for example,

i want to search the name "B&B Hôtel" that contains special caraters like & and ô by just typing "BB Hotel"

how can i do that ?

**Comment by vkarpov15** [comment]
@askri2pac read up on [mongodb collations](https://docs.mongodb.com/manual/reference/collation/)

**Comment by arjupba** [comment]
This saved my day: 
$regex: new RegExp('^' + name.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&') + '$', 'i')
This work with mongoose aggregate $match also. Check this out.

**Comment by OmarKhattab** [comment]
> I found this on stackoverflow
> 
> ```
> query.replace(/[-[\]{}()*+?.,\\/^$|#\s]/g, "\\$&");
> ```
> 
> maybe there is no need of a module, or the module is more safe somehow?

this solved it for me
