### ISSUE TITLE
How to create a limit on "ref" ?

### ISSUE THREAD

**Issue by ParanormalCoder** [Automattic/mongoose#3797]
consider the following models:

var mongoose = require('mongoose');
var Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;
var Human = new Schema({
  pet:{
    type: ObjectId,
    ref: "pet"
  },
  type:{
        enum: ["teen",
            "old"
        ],
        type: Schema.Types.String,
        required: true
  }
});

----- and ------

var mongoose = require('mongoose');
var Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;
var Pet = new Schema({
...
});

How can I strictly limit the number of references for each document in Human model?
For example having at maximum 3 pets for each person.

The next question is that: Is there any ways to strictly control the ref limit by the human.type field value? (e.g. "adult" can have 5 pets and "teen" can have 10 pets)

**Comment by TrejGun** [comment]
you can validate on set like this

```js
pet: {
	type: ObjectId,
	ref: "pet"
	set(pets) {
		if (this.type === "adult" && pets.length >= 5) {
			this.invalidate("pets", "maximum 5 pets!", pets);
		} else if (pets.length >= 5) {
			this.invalidate("pets", "maximum 3 pets!", pets);
		}
		return pets;
	}
}
```

or on save
```js
pet: {
	type: ObjectId,
	ref: "pet"
	validate: [{
		validator: function () {
			if (this.type === "adult" ) {
				return this.pets.length >= 5;
			} else if (pets.length >= 5) {
				return this.pets.length >= 3;
			}
		},
		msg: "maximum pets exceeded!"
	}],
}
```
