### ISSUE TITLE
Calling `toObject` on a casted document with `depopulate` will depopulate itself

### ISSUE THREAD

**Issue by slamuu** [Automattic/mongoose#3798]
Not sure what the expected behavior is or the desired approach if this requires a fix

From quick checking, `Document#set` is setting `value.$__.wasPopulated` [(source)](https://github.com/Automattic/mongoose/blob/ede06fc6231ca5062c0bcd4e03021dc997604705/lib/schema/objectid.js#L91) during casting of reference documents.

However, `Document#$toObject` will cast to its `_id` if `$__.wasPopulated` is set and `_skipDepopulateTopLevel` option is not specified.

Workaround is to set `_skipDepopulateTopLevel` but it seems to be an internal option and not documented

```
const ReferenceSchema = new mongoose.Schema();
const BaseSchema = new mongoose.Schema({
  'reference': {
    'type': mongoose.Schema.ObjectId,
    'ref': 'Reference',
  },
});

const Reference = mongoose.model('Reference', ReferenceSchema);
const Base = mongoose.model('Base', BaseSchema);

const reference = new Reference();
const base = new Base();

expect(reference.toObject({ depopulate: true })).to.have.property('_id'); // Passes

base.reference = reference;

expect(reference.toObject({ depopulate: true, _skipDepopulateTopLevel: true })).to.have.property('_id'); // Passes
expect(reference.toObject({ depopulate: true })).to.have.property('_id'); // Fails
```

Could be related to #3057, #3408

**Comment by vkarpov15** [comment]
IMO this is reasonable behavior: if you do `toObject()` with `depopulate` option set on a populated subdoc, you should get just an `_id`. Is this unreasonable?

**Comment by slamuu** [comment]
Ah I see, although it does seem a little misleading coming from a functional perspective for `toObject`. If the first call to `reference.toObject({ depopulate: true })` returns `{ "_id": "123" }`, I would not expect that assigning it as a subdocument would change the internal state so that subsequent calls to `reference.toObject({ depopulate: true })` returns `"123"`. But nonetheless, `_skipDepopulateTopLevel` works for me! Thanks Valeri!

**Comment by vkarpov15** [comment]
I wouldn't really recommend using `_skipDepopulateTopLevel` - it's an internal option and not formally supported. The reasoning for this behavior is that when you set `base.reference = reference;`, mongoose converts `reference` to a populated doc underneath the `base` root doc.

Another alternative to get the behavior you want would be to set `base.reference` to a clone of `reference`: `base.reference = reference.toObject();` . This will leave the original `reference` doc as a standalone and create a new subdoc for `base.reference`.
