### ISSUE TITLE
Populate return null on nested path

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#3802]
I'm facing a null on some nested path when while the schema does not change

In the code below, I just rearrange the same result to add a level in the object, and suddenly, a "null" value appear.

Am I wrong somewhere?

      var mongoose = require('mongoose');
      mongoose.Promise = require('bluebird');

      var companySchema = new mongoose.Schema({
        name:  String,
        description:  String
      });

      var userSchema = new mongoose.Schema({
        name:  String,
        company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company'}
      });

      var Company = mongoose.model('Company', companySchema);
      var User = mongoose.model('User', userSchema);

      mongoose.connect(
        'mongodb://127.0.0.1/test',
        {},
        function (err) {
          if (err) {
            return console.error(err);
          }

          var company = new Company({name: 'Reynholm Industrie'});
          var user1 = new User({name: 'Douglas', company: company._id});
          var user2 = new User({name: 'Lambda'});

          Promise
            .all([
              company.save(),
              user1.save(),
              user2.save()
            ])
            .then(function () {
              return User.find({}).exec();
            })
            .then(function (results) {
              return Company.populate(results, {path: 'company', options: {lean: true}})
            })
            .then(function (results) {
              console.log(results);
              /*
              [ { __v: 0,
                company:
                { _id: 56a7757940023eb1156ca8b1,
                  name: 'Reynholm Industrie',
                  __v: 0 },
                name: 'Douglas',
                _id: 56a7757940023eb1156ca8b2 },
                { __v: 0, name: 'Lambda', _id: 56a7757940023eb1156ca8b3 } ]
              */

            })
            .then(function () {
              return User.find({}).exec();
            })
            .then(function (results) {
              return Company.populate({items: results}, {path: 'items.company', options: {lean: true}})
            })
            .then(function (results) {
              console.log(results);
              /*
               { items:
               [ { __v: 0,
               company:
               { _id: 56a775d3e0736ab5155017ed,
               name: 'Reynholm Industrie',
               __v: 0 },
               name: 'Douglas',
               _id: 56a775d3e0736ab5155017ee },
               { __v: 0,
               name: 'Lambda',
               _id: 56a775d3e0736ab5155017ef,
               company: null } ] }                  <= null object

               */

            })
        }
      );

**Comment by vkarpov15** [comment]
Unfortunately this behavior is not supported. The [`Model.populate()` function](http://mongoosejs.com/docs/api.html#model_Model.populate) only accepts a mongoose document or an array of mongoose documents as a parameter, and supporting this in the more general case is more trouble than its worth with mongoose's current internals. You can pretty easily do something like this:

```javascript
.then(function () {
          return User.find({}).exec();
        })
        .then(function (results) {
          return Company.populate(results, {path: 'company', options: {lean: true}})
        })
        .then(function (results) {
          console.log({ items: results });
        })
```

**Comment by jbdemonte** [comment]
Oh...
Sorry, I didn't noticed
