### ISSUE TITLE
Unique index on single subdocument fails if subdocument is omitted

### ISSUE THREAD

**Issue by andrenarchy** [Automattic/mongoose#3803]
A nice feature of single subdocuments is that the corresponding key can be omitted. However, a unique index in a single subdocument prevents multiple documents where the subdocument is omitted, see below. Can mongoose transparently use a partial index that only sends documents to the index where the subdocument is present?

## Example:

```javascript
var userSchema = new mongoose.Schema({
  username: {type: String, unique: true, required: true},
});

var personSchema = new mongoose.Schema({
  fullName: String,
  user: userSchema,
});

var Person = mongoose.model('Person', personSchema);

// make sure the index exists before inserting
Person.ensureIndexes(function() {
  Person.create(
    {fullName: 'Darth', user: {username: 'darth'}},
    {fullName: 'Kylo'},
    function (err) {
      if (err) return;
      console.log('successfully inserted Darth and Kylo');
      Person.create({fullName: 'Rey'}, function(err) {
        console.log(err);
      });
    }
  );
});
```
This results in
```
successfully inserted Darth and Kylo
{ [MongoError: E11000 duplicate key error collection: darth.people index: user.username_1 dup key: { : null }]
[...]
```

**Comment by vkarpov15** [comment]
That's MongoDB's unique index behavior by default. Use sparse indexes https://docs.mongodb.org/manual/core/index-sparse/ , add `sparse: true`

**Comment by andrenarchy** [comment]
I'm aware of this fix. But it seems strange that an index on a single subdoc has to be defined in a different way (i.e., with `sparse: true`) than on the root doc.

**Comment by vkarpov15** [comment]
AFAIK you would need to do the same thing with a root doc - mongodb will always complain about duplicates if the key is null/undefined unless you specify a sparse unique index. Do you have an example where this is not the case?

**Comment by andrenarchy** [comment]
You're right: it will complain about duplicates in the root doc. But with a root doc you don't have the possibility to omit it completely (like with single subdouments). 

Your approach means that we have to include knowledge about where we use a schema inside the schema. From a software architecture and encapsulation point of view this seems a bit odd but maybe there's no better way...

**Comment by vkarpov15** [comment]
There's no reason why you can try to save a root doc without a key that's defined as `unique: true` on the schema. I don't really see how this case is any different...
