### ISSUE TITLE
multiple collections refs

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#3806]
Hi, I can't see docs about a field who can store ObjectId referring one of collections of mine.
I searching something like that:
```
var doc= new Schema({
name:String,
others: [{type:mongoose.Types.ObjectId refs: "collection1,collection2,collection3"}]
})
```
Obiouvsly it's wrong, but the aim is clear: The field "others" should store an array of ObjectId of documents coming from collection1 OR collection2 OR collection3.

**Comment by vkarpov15** [comment]
We don't quite cover this feature in the docs yet, but mongoose 4.x supports using `refPath` instead of `ref`:

```javascript
var schema = new Schema({
  name:String,
  others: [{ value: {type:mongoose.Types.ObjectId, refPath: 'others.kind' } }, kind: String }]
})
```

You can find some examples in #3108 . I opened up #3809 to track status of documentation for this feature.

**Comment by alfredopacino** [comment]
Maybe it could be useful for someone.
If you need a ref to multiple collection it means those collections semantically have something in common.
A solution could be good old inheritance approach.
https://github.com/briankircho/mongoose-schema-extend
