### ISSUE TITLE
nested populate on multiple path only populate first one

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#3808]
When using space separated path with "populate" property of populate function, only the first one is populated.

In the code below, if I change the path from "author target" to "target author" then, the company is populated to the "target" user instead of the user

      var mongoose = require('mongoose');
      mongoose.Promise = require('bluebird');

      var companySchema = new mongoose.Schema({
        name:  String,
        description:  String
      });

      var userSchema = new mongoose.Schema({
        name:  String,
        company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company', select: false}
      });

      var messageSchema = new mongoose.Schema({
        message:  String,
        author: {type: mongoose.Schema.Types.ObjectId, ref: 'User'},
        target: {type: mongoose.Schema.Types.ObjectId, ref: 'User'}
      });

      var Company = mongoose.model('Company', companySchema);
      var User = mongoose.model('User', userSchema);
      var Message = mongoose.model('Message', messageSchema);

      mongoose.connect(
        'mongodb://127.0.0.1/test',
        {},
        function (err) {
          if (err) {
            return console.error(err);
          }

          var company = new Company({name: 'Reynholm Industrie'});
          var user1 = new User({name: 'Douglas', company: company._id});
          var user2 = new User({name: 'Moss', company: company._id});
          var message = new Message({message: 'Hello', author: user1._id, target: user2._id});

          Promise.all([
            company.save(),
            user1.save(),
            user2.save(),
            message.save()
          ])
          .then(function () {
            return Message.findOne({_id: message._id}).exec();
          })
          .then(function (mess) {
            mess.populate(
              {
                path: 'author target',
                select: '_id name company',
                populate: {
                  path: 'company',
                  model: 'Company'
                }
              },
              function () {
                console.log(mess);
                /*
                 {
                   __v: 0,
                   target:
                      { company: 56a856a8adacc85b22816205,       <=  not populated: because is in 2nd position in the path: 'author target'
                        name: 'Moss',
                        _id: 56a856a8adacc85b22816207
                      },
                   author:
                      { company:                                 <= populated: because is in 1st position in the path: 'author target'
                        { __v: 0,
                          name: 'Reynholm Industrie',
                          _id: 56a856a8adacc85b22816205
                        },
                        name: 'Douglas',
                        _id: 56a856a8adacc85b22816206
                      },
                   message: 'Hello',
                   _id: 56a856a8adacc85b22816208
                 }
                 */
              }
            )
          })
        }
      );

**Comment by vadermemo** [comment]
Someone have resolve this issue? I am in same situation even at November, 2019

**Comment by vkarpov15** [comment]
@vadermemo please open up a new issue and follow the issue template.
