### ISSUE TITLE
Why when create a new doc is $__registerHooksFromSchema called at the end?

### ISSUE THREAD

**Issue by marchah** [Automattic/mongoose#3817]
Hi,

I would like to know why in the [document constructor](https://github.com/Automattic/mongoose/blob/master/lib/document.js#L39) `$__registerHooksFromSchema` is called at the end? Is there any reason?

I'm asking that because for a plugin I would need to detect the event `set` but it's not emitted when you create a new document.

Example:
````javascript
const model = new Model({
 'field_1': 'value_1',
 'field_2': 'value_2',
 ...
});
````

BTW: is there any way to get the list of all the event associate to the model?

Thank you

**Comment by vkarpov15** [comment]
Not entirely sure why, that particular bit of logic predates my involvement in the project. If you want some code to execute when you create a new document, [`schema.queue()` is helpful](http://mongoosejs.com/docs/api.html#schema_Schema-queue).

Re events, see [model constructor docs](http://mongoosejs.com/docs/api.html#model_Model)
