### ISSUE TITLE
bad problem with ObjectId.isValid()

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#3823]
I am having a helluva a time trying to determining if a value is a valid ObjectId, there seems to be a big problem with this -

I tried

``` js
var ObjectId = mongoose.Types.ObjectId;
var ObjectId = mongoose.Schema.Types.ObjectId;

using ObjectId.isValid() and new ObjectId(val);
```

take a look here:

you can see that the value "95" or 95 slips through:

filter
![screenshot 2016-01-29 20 04 30](https://cloud.githubusercontent.com/assets/11139560/12693630/31dc304a-c6c4-11e5-91ce-a3b07332e791.png)

map
![screenshot 2016-01-29 20 04 48](https://cloud.githubusercontent.com/assets/11139560/12693631/35653b6c-c6c4-11e5-90a0-cb7b8b1b09db.png)

what the heck is going on?
please help, thanks!

**Comment by ORESoftware** [comment]
oh shit, wtf


```
/**
* Checks if a value is a valid bson ObjectId
*
* @method
* @return {boolean} return true if the value is a valid bson ObjectId, return false otherwise.
*/
ObjectID.isValid = function isValid(id) {
  if(id == null) return false;

  if(typeof id == 'number')
    return true;
  if(typeof id == 'string') {
    return id.length == 12 || (id.length == 24 && checkForHexRegExp.test(id));
  }
  return false;
};
```

what is it ok if it's a number?

**Comment by TrejGun** [comment]
`js-bson` looks outdated :(

it also throws error
```Buffer.set is deprecated. Use array indexes instead.```

can someone update it?

**Comment by TrejGun** [comment]
oh thats nice mongodb/js-bson#160

**Comment by vkarpov15** [comment]
`new ObjectId(95);` is completely valid because a valid ObjectId is any 12 bytes, so the number `95` works just fine. If you want to check for the usual hex string, just use `/[a-fA-F0-9]{24}/.test(val);`

**Comment by fires3as0n** [comment]
It works with strings, but if I try to check if `id` is valid by using `ObjectId.isValid(6)`, passing 6 as a number, and it says that it is fine.
Then I pass it to `.findById(6)` and get an exception.
`UnhandledPromiseRejectionWarning: CastError: Cast to ObjectId failed for value "6" at path "_id" for model "SomeModel"
at new CastError (node_modules\mongoose\lib\cast.js:315:32)`

So seems like `ObjectId.isValid()` is really quite a useless stuff unless you implicitly cast data passed to it to a string.
