### ISSUE TITLE
reason for reconnect

### ISSUE THREAD

**Issue by refaelos** [Automattic/mongoose#3825]
Hey Guys,

I need help investigate a reason for *some* of my machines to reconnect over and over again to mongo.
Using mongoose and v4.2.6 node v4.

I suppose the reason lies with the machines and not with mongo or mongoose b/c some of the machines don't reconnect over and over.

I tried looking at mongo's logs and only seeing the disconnection and reconnection but nothing more.

Ideas are welcome. Please help!

Thanks!

**Comment by vkarpov15** [comment]
I suspect its just due to a socketTimeout, can you show how you're connecting to mongodb? There's some helpful tips on issues like #3588

**Comment by refaelos** [comment]
This is my configuration:

```
mongo   : {
    uri    : 'xxx',
    options: {
      user   :'xxx',
      pass   : 'xxx',
      server : {
        socketOptions: {
          keepAlive       : 1,
          socketTimeoutMS : 300000,
          connectTimeoutMS: 300000
        }
      },
      replset: {
        rs_name      : 'xxx',
        socketOptions: {
          keepAlive       : 1,
          socketTimeoutMS : 300000,
          connectTimeoutMS: 300000
        },
        readPreference: 'secondaryPreferred',
        poolSize: 200
      }
    }

  }
```

**Comment by vkarpov15** [comment]
Might want to take a look at https://github.com/christkv/mongodb-core/issues/66#issuecomment-165052045 . Also, [some users have commented that upgrading to mongoose 4.3.4 fixed similar issues](https://github.com/Automattic/mongoose/issues/3588#issuecomment-167618587) so you may want to try that.

**Comment by refaelos** [comment]
Nothing helped.

I still see multiple reconnects on the clients and on the server I see connection count rising up. Connections are just not closing.

Ideas?

**Comment by refaelos** [comment]
Closing this in favor of: https://github.com/Automattic/mongoose/issues/3863
