### ISSUE TITLE
How to deal with circular dependencies

### ISSUE THREAD

**Issue by ajsharp** [Automattic/mongoose#3826]
I have two models:

```js
// app/models/message.js
var User = require('./user');

var MessageSchema = new Schema ({
  sender: {type: Schema.Types.ObjectId, ref: 'User', required: true},
});

MessageSchema.methods.toJSON = function() {
  return {
    sender: User.publicJSON(this.sender)
  };
}

// app/models/user.js

var Message = require('./message')
var UserSchema = new Schema ({
});

UserSchema.methods.recentMessages = function() {
  return Message.where({sender: this.id});
};

UserSchema.statics.publicJSON = function(user) {
  return {
    id: this.id,
    recent_messages: user.recentMessages()
  }
};
```

Requiring one from the other causes problems and causes a copy of the model to be returned before it's fully formed. Specifically, before the User model has it's `publicJSON` static attached to it. Do you know of a way to deal with this issue?

**Comment by vkarpov15** [comment]
Hard solution: use a dependency injector. Easy solution: if you create a model using `mongoose.model('Message', MessageSchema);` you can then access the model with `mongoose.model('Message');`, so all you need to do is `require('mongoose');` in the file to access your models.

**Comment by developius** [comment]
@vkarpov15 that 'easy' solution breaks down when you've got models being loaded one after the other which depend on each other - you get the error `MongooseError: Schema hasn't been registered for model`. Is there a way around this? I guess the best way would be a separation of concerns approach and use a controller or helper method to handle it.

**Comment by vkarpov15** [comment]
Can you clarify what you mean by models "which depend on each other"? If you have schemas that depend on each other, then I'd recommend you keep them in the same file, but that's a [quirk of node](http://blog.cloudmineinc.com/managing-cyclic-dependencies-in-node.js?hsFormKey=7431de7ae0d26bfb35db489dae544ad5) rather than a mongoose issue

**Comment by ianpogi5** [comment]
> Hard solution: use a dependency injector. Easy solution: if you create a model using `mongoose.model('Message', MessageSchema);` you can then access the model with `mongoose.model('Message');`, so all you need to do is `require('mongoose');` in the file to access your models.

Would be great if you have a code sample demonstrating this. I tried it and got MongooseError: Schema hasn't been registered for model.

**Comment by vkarpov15** [comment]
@ianpogi5 most likely you're calling `mongoose.model('message')` before defining your model

**Comment by ianpogi5** [comment]
> @ianpogi5 most likely you're calling `mongoose.model('message')` before defining your model

My code was the same as @ajsharp. I solved it by avoiding the situation using a third file to use the two models.

But still I don't get what you mean. Doing your suggestion yields the error @developius encountered. A code example modifying @ajsharp code would be great.

**Comment by pykeras** [comment]
may help others, 
If you get the `MissingSchemaError: Schema hasn't been registered for model "<ModelName>".`
then add in model code file you should have these :

```
module.exports = mongoose.model("ModelName", schema)
exports.ModelNameSpecial = mongoose.model("ModelName")
```
I'm adding this to and existing code, so don't want to mess with module.exports

**Comment by pykeras** [comment]
this solves my problem, for any one may need it:

In all dependent models, require(import) your models after export current source model.  

**Model_A.js**
```
module.exports = mongoose.model("ModelA", schema);
const ModelB = require("./Model_B.js");
```

and for **Model_B.js**
```
module.exports = mongoose.model("ModelB", schema);
const ModelA = require("./Model_A.js");
```
