### ISSUE TITLE
Populated paths toJSON options

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#3833]
I have a model that gets populated from another model's document, the populated model has the option `minimize: false` set. I'd like to disable it when serializing the populated document:

```
// Challenge and User has minimize: true
var chal = await Challenge.find(...).populate('user', 'some fields').exec();
chal.toJSON();
```
I need `chal.user` to be serialized with `minimize: true` while having `chal` serialized with the default minimize option, in this case `minimize: false`

**Comment by vkarpov15** [comment]
Right now we don't support that, either all subdocs use their schema-specified `minimize` option or the one passed to `toJSON()`. You can work around it by doing something weird like `chal.user.schema.options.minimize = true;` but I don't have any really good ideas about how to support this behavior in general.

**Comment by paglias** [comment]
> chal.user.schema.options.minimize = true;

is a good idea, I actually figured out that populations are simple find calls so I decided to wrote the logic manually but it easily got very verbose

**Comment by vkarpov15** [comment]
Yeah this is a bit of an odd edge case. We don't have any way of defining options at a level between "define at function call" and "define on schema". Perhaps we could make `minimize` take a function, so you could do something like `minimize: function(doc) { if (doc.ownerDocument) { return false; } return true; }` so you can say "minimize by default unless this is a child doc". Would that work for your use case?

**Comment by paglias** [comment]
@vkarpov15 in the end I had to stay with my custom logic because if I did something like this:

```
    User.schema.options.minimize = true;
    let challenges = await Challenge.find(...)
      .populate('user', nameFields)
      .exec();
    User.schema.options.minimize = false;
```
being Challenge.find async a different request could have called user.toJSON() in the meantime with the wrong minimize option.

But it's really an edge case so don't worry if you don't want to implement it (I probably wouldn't since it's so easy to recreate the populate method manually)
