### ISSUE TITLE
Document.populate should return a promise if no callback is passed

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#3834]

**Comment by vkarpov15** [comment]
Use [`doc.execPopulate()`](http://mongoosejs.com/docs/api.html#document_Document-execPopulate) to get a promise back. Part of the `doc.populate()` API is that it returns the original document, so unless we want a document to inherit from a promise (not a good idea) we can't really do that. Perhaps for 5.0 we can make `doc.populate()` return a chainable promise, but for now just use `execPopulate()`

**Comment by paglias** [comment]
@vkarpov15 thanks, that's exacty what I needed. I can see how it would be a big change to return a promise and execPopulate is exactly what I needed, I created the issue just because it wasn't mentioned in the API docs of doc.populate, a link to it might be useful

**Comment by vkarpov15** [comment]
Opened #3836

**Comment by adambuczynski** [comment]
+1 for making `doc.populate()` return a promise. I'm using it in a promise chain and was wondering why it didn't work:

```js
Event.create(data)
      .then(event => {
        return event.populate({
          path: 'organisers',
          select: 'id firstName lastName avatar color'
        });
      })
      .then(event => event.toJSON())
      .then(event => res.status(201).json(event))
      .catch(next);
```

Can I simply replace `.populate` with `.execPopulate` to fix it for now?

**Comment by vkarpov15** [comment]
Use `event.populate().execPopulate()` - the reason why `populate()` doesn't return a promise is for chaining `populate()` calls

**Comment by adambuczynski** [comment]
I don't think I've ever found the need to do that. You can specify as many fields as you like in `.populate()` right?

**Comment by vkarpov15** [comment]
I haven't really used it myself, but it's useful if you want to populate multiple fields with different options, say populate "friends" and only select their "names" field and in addition populate "job" and only select "title".

**Comment by adambuczynski** [comment]
Ok. Yes, I understand it's a tricky balance to find between making Mongoose promise architecture friendly and functional with chainable methods in their own right.

I can live with having to use `execPopulate()` for now, but it would be nice to revisit this for a future major release maybe and see if the API can be made more consistent somehow. Right now, if you see that `doc.save()` is returning a promise, you kind of expect `doc.populate()` to do the same.

Probably the easiest way to deal with this for `.populate()` would be to modify the method signature so it can accept an array of population requests, removing the need for multiple `.populate()` calls.

**Comment by vkarpov15** [comment]
Chaining is a pivotal part of any JS API and I'd like to avoid dropping it. Right now I'm thinking that in 5.0 `.populate()` should instead return a special promise type that also has a `.populate()` helper that lets you chain `populate()` calls, so you get the best of both worlds.

**Comment by adambuczynski** [comment]
Yes, I thought about suggesting that but wasn't sure if you'd like that
approach. I guess it would leverage the flexibility of Javascript.

Also, I have found that I am I'm fact using chaining of populate in my own
project, so it would be good to leave it in :)

**Comment by vkarpov15** [comment]
Not planning on dropping support for it, don't worry :)

**Comment by AbdelrahmanHafez** [comment]
>I haven't really used it myself, but it's useful if you want to populate multiple fields with different options, say populate "friends" and only select their "names" field and in addition populate "job" and only select "title".

Now that we support an array of options to populate, this shouldn't be a problem anymore.

**Comment by vkarpov15** [comment]
I took a closer look at this and I think @AbdelrahmanHafez is right - keeping the chaining API would likely do more harm than good here. If we support chaining, we'd still have to think about what happens if someone chains on a `populate()` after `populate()` is already in progress.

We'll remove support for doing things like `doc.populate({ path: 'friends', select: { names } }).populate({ path: 'job', select: { title } })`, in favor of `doc.populate({ path: 'friends', select: { names } }, { path: 'job', select: { title } })`. We support passing arrays and spreads to `Document#populate()`.

@adamreisnz any thoughts?

**Comment by adamreisnz** [comment]
I agree, passing an array or multiple arguments into populate seems to be the sensible approach in favour of chaining populate calls. If this removes the need for an `execPopulate` that'd be a good change in my opinion.

This probably won't affect the outcome of https://github.com/Automattic/mongoose/issues/8747 will it? Still recommended to use `exec`?

**Comment by vkarpov15** [comment]
@adamreisnz no this is unrelated to #8747. In this case, using `doc.populate()` would return a promise rather than a custom thenable, so we wouldn't run into the same issue affecting custom thenable stack traces.

**Comment by adamreisnz** [comment]
Ok so I guess it would just replace `execPopulate` with `exec` (if you want to better stack traces) 👍

**Comment by AbdelrahmanHafez** [comment]
@adamreisnz 
I believe that won't be necessary nor possible, since `.populate(...)` will return a real promise, not a custom thenable. You'll just need to remove `execPopulate(...)` altogether.

**Comment by adamreisnz** [comment]
Ok gotcha, thanks

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
In [this change](https://github.com/Automattic/mongoose/blob/3d7b2a801c9495bca7e06a89214d1136b0de6c0c/migrating_to_6.md#L5) we're recommending that people use:
`await document.populate('path1'); await document.populate('path2');`

For some reason I've always had an assumption that populating multiple paths happens as a `Promise.all(...)` under the hood, if my assumption is correct, then I think we should recommend `await document.populate(['path1', 'path2']);` which would have the same old behavior.

If it's not correct, I think we should take a look at it, perhaps let is be up to the user to decide how they wanna execute their `populate(...)`

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez `await document.populate(['path1', 'path2']);` populates `path1` followed by `path2` in series. You'd need to use `Promise.all([document.populate('path1'), document.populate('path2')])` to execute them in parallel.

**Comment by AbdelrahmanHafez** [comment]
I opened #10480 to discuss this further, let's continue there
