### ISSUE TITLE
setDefaultsOnInsert doesn't work if update is empty

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3835]
```javascript
var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3617');

mongoose.set('debug', true);

var schema = new mongoose.Schema({
  test: { type: Number, default: 8472 },
  name: String
});

var MyModel = mongoose.model('MyModel', schema);

MyModel.update({}, { }, { setDefaultsOnInsert: true, upsert: true }, function(error) {
  assert.ifError(error);
  MyModel.findOne({}, function(error, doc) {
    assert.ifError(error);
    console.log(doc);
  });
});
```

**Comment by yinbucheng** [comment]
How to write mongodb grammar? I still make the same mistake

**Comment by yinbucheng** [comment]
db.dataReference.update({ "dataId": "test" }, 
{ "$inc": { "referCnt": 1 }, 
    "$set": { "updatedTimestamp": "1652257641341"  }, 
    "$setOnInsert": { "createdTimestamp": "1652257641341" ,"referCnt":100 }}
)

=============
WriteResult({
	"nMatched" : 0,
	"nUpserted" : 0,
	"nModified" : 0,
	"writeError" : {
		"code" : 40,
		"errmsg" : "Updating the path 'referCnt' would create a conflict at 'referCnt'"
	}
})
4.4.6

**Comment by vkarpov15** [comment]
@yinbucheng I'd recommend doing a separate update with `$setOnInsert`. So `await db.dataReference.updateOne({ dataId: 'test' }, { $setOnInsert: { referCnt: 100 } }, { upsert: true })` followed by `DataReference.update({}, { $inc: { referCnt: 1 } })` without the `$setOnInsert` or upsert.
