### ISSUE TITLE
v4.4.0 topology destroyed error

### ISSUE THREAD

**Issue by perrin4869** [Automattic/mongoose#3837]
Hi, I just updated to v4.4.0, and now I see an error during my tests, although I really don't know what the cause could be:

```
Unhandled rejection MongoError: topology was destroyed
```

Any clues what could be causing this? I tested v4.3.7 and the error wasn't there.

**Comment by vkarpov15** [comment]
I suspect this is related to #3790, because now the `.connect()` and `close()` methods now return ES2015 promises. I think the solution will be to just make it so that these functions don't return promises if you specify a callback to minimize impact.

**Comment by vkarpov15** [comment]
Also, can you provide a code sample or show how you're connecting?

**Comment by perrin4869** [comment]
Actually, it's a bit convoluted, starting and closing connections before each unit test, I'll try to isolate the problem though!

**Comment by perrin4869** [comment]
Made a repository with the problem almost isolated: https://github.com/perrin4869/mongoose_topology_error

**Comment by vkarpov15** [comment]
Thanks for the detailed repro instructions, turns out this warning was due to the fact that we had an unhandled rejection internally when model init calls `ensureIndexes()`, which returns a promise as of #3795. Nothing to really worry about.

**Comment by perrin4869** [comment]
Awesome, looking forward to 4.4.2 then, thanks!!!
