### ISSUE TITLE
schematypes.html page is screwed

### ISSUE THREAD

**Issue by codemorpher** [Automattic/mongoose#3843]
http://mongoosejs.com/docs/schematypes.html is rendered  broken.
Screenshot:
http://pasteboard.co/1hlwoDLj.jpg

My OS: Linux Mint 17
Browsers: Last Chrome and FF

**Comment by mynameiscoffey** [comment]
It looks like schematypes is the only page in the docs that uses both a .jade file and acquit

**Comment by mynameiscoffey** [comment]
Sorry I don't know how to remove the bad PR (a3cccd7).  Not sure if this is the direction you would like to take this issue or not as well as if I am supposed to include the built pages since they are checked into the repo.
