### ISSUE TITLE
Model defaults over undefined values

### ISSUE THREAD

**Issue by dciccale** [Automattic/mongoose#3844]
hi I would like my model to set `undefined` values to default model values.

example:

``` js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var OrderSchema = new Schema({
  billing: {
    name: {type: String, default: ''},
    company: {type: String, default: ''}
  }
});

var OrderModel = mongoose.model('Order', OrderSchema);

var orders = [
  // first order specifies undefined values
  {
    billing: {
      name: undefined,
      company: undefined
    }
  },
  // second order has empty values
  {
    billing: {}
  }
];

OrderModel.create(orders, function (err, docs) {
  var order1 = docs[0];
  var order2 = docs[0];

  // order1.billing.name === undefined
  // order2.billing.name === ''

  // Actually now the value is not even a String as specified in the model
  // typeof order1.billing.name === undefined
});
```

Where can I specify to mongoose to treat `undefined` values in a way such that they are replaced with the default instead?

Is there any option in the model to specify "non existing values" which mongoose will ignore them and use defaults?

Could this be a feature if it is not there?

Any other way to achieve this that I am missing?

**Edit:** And actually the value of `order1.billing.name` is `undefined`. not even a `String` as specified in the model

thanks in advance!

**Comment by dciccale** [comment]
I found a way to do it:

```js
function omitUndefined(value) {
  return value === undefined ? '' : value;
}

var OrderSchema = new Schema({
  billing: {
    name: {type: String, default: '', set: omitUndefined},
    company: {type: String, default: '', set: omitUndefined}
  }
});
```

However, isn there a way inside the `omitUndefined` function to get the `default` property from the model. In that case would be really powerful so I can do something like this:

```js
function omitUndefined(value) {
  return value === undefined ? this.default : value;
}
```

**Comment by varunjayaraman** [comment]
@dciccale sorry for the very late reply, but it seems that you could just close over the same value and use both in the `set` hook and in the `default` value. I'm going to close this since this doesn't really need to be a mongoose feature
