### ISSUE TITLE
Backwards breaking change with `.connect()` return value

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3847]
Re: https://github.com/Automattic/mongoose/pull/3790#issuecomment-179335380

**Comment by nschloe** [comment]
Interestingly, when upgrading to 4.4.1 (from 4.3.x), I noticed that `return`ing the `mongoose` object doesn't work anymore,
```js
import mongoose from 'mongoose';

export const init = co.wrap(function* _init() {
  yield mongoose.connect(
    config.mongodbUri,
    {
      server: {
        socketOptions: {
          keepAlive: 1,
        },
      },
      replset: {
        socketOptions: {
          keepAlive: 1,
        },
      },
    }
  );

  mongoose.connection.on('error', (err) => {
    process.exit(1);
  });

  return mongoose;
});
```
always returns `undefined`. Within this function, it's all fine; `mongoose` is the fat object it used to be. I'm puzzled as to why this may happen, but perhaps it's related to the attempted fix.

**Comment by vkarpov15** [comment]
@nschloe can you please open up a separate issue for this? I'm not 100% sure this is related but I'd like to find out if it is...
