### ISSUE TITLE
Set the background option as global setting

### ISSUE THREAD

**Issue by diego1686** [Automattic/mongoose#3849]
It would be great if the background option for index creation could be set in the connection settings as a global option. 

For example, if I'm testing against a test database, I need to re-generate all the indexes before the tests start running. In that case, I need to create all the indexes with the background:false option, because I need them ready before the tests start doing read/write operations on the database. But I want this only in the test environment, for all the other environments the background:true as default is ok.

To do that, now I need to use the Schema#index function to create each index in my app, setting the background option dynamically depending the environment the app is running on. This approach makes the code more complex and dirty! 

What do you think about it?

**Comment by vkarpov15** [comment]
Plugins (see [plugins docs](http://mongoosejs.com/docs/plugins.html) and [my blog post on plugins](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) ) are the best way to do this right now. You can DRY your code up by just writing a plugin and attaching `schema.plugin(myIndexPlugin);` to every schema that you need indexes for. In the future we will have a mechanism to register a plugin for all schemas, but its not a burning priority right now - follow #3732 for updates on that.

**Comment by diego1686** [comment]
@vkarpov15 Great, thanks!
