### ISSUE TITLE
Style documentation http://mongoosejs.com/docs/schematypes.html

### ISSUE THREAD

**Issue by borovik96** [Automattic/mongoose#3850]
![image](https://cloud.githubusercontent.com/assets/9018702/12796395/93fd7a72-cacf-11e5-8bbc-1ece4cb2b8dd.png)

**Comment by mynameiscoffey** [comment]
Duplicate of #3843

**Comment by tech-boy** [comment]
Hey, 
Why is the webpage bug not resolved yet?

**Comment by vkarpov15** [comment]
Haven't deployed changes yet, should be fixed with 4.4.2 release today.
