### ISSUE TITLE
Broken markup on /docs/schematypes.html

### ISSUE THREAD

**Issue by wzup** [Automattic/mongoose#3853]
Please, repair markup on the page http://mongoosejs.com/docs/schematypes.html. This is what it looks now in Chrome and FF:

![mongoose custom schema types v4 4 1 - google chrome 2016-02-05 00 00 24](https://cloud.githubusercontent.com/assets/3880497/12820835/c3a44bd0-cb9b-11e5-9dab-42143699769b.png)

**Comment by vkarpov15** [comment]
See #3843

**Comment by wzup** [comment]
Thanks for closing the issue without solving it.

Could you at least tell us where/how could we read the docs in any readable format? Ok, it is broken there, but tell us where we can find a spare readable source?

**Comment by wzup** [comment]
For those who like myself need to read docs. Open contents of this file https://github.com/Automattic/mongoose/blob/master/docs/schematypes.html in a browser (by copy/paste and save in a separate file or even right to browser dev tools Elements tab). It is possible to read it all right.

**Comment by vkarpov15** [comment]
Its closed because it's resolved in master but hasn't been pushed to prod yet. Sorry about that, will push the fix today.
