### ISSUE TITLE
Aggregate cursor default batchSize

### ISSUE THREAD

**Issue by siboulet** [Automattic/mongoose#3855]
For some reason I can't use cursor without specifying cursor batchSize:

```js
var cursor = Model.aggregate(...).cursor().exec();
```
I'm getting TypeError: cursor.each is not a function.

This however seems to work:

```js
var cursor = Model.aggregate(...).cursor({batchSize:1000}).exec();
```

Is this expected?

Mongoose 4.4.1

**Comment by vkarpov15** [comment]
Mistake on my part, fixed in master and will be deployed with 4.4.2.
