### ISSUE TITLE
Document.toObject minimize option doesn't seem to function

### ISSUE THREAD

**Issue by unusualbob** [Automattic/mongoose#3857]
Mongoose 4.4.1

When interacting with an empty object, it seems `{minimize: false}` doesn't actually stop fields from being culled.

Schema
```js
{
  testField: String,
  testData: {
    a: String,
    b: String,
    c: Boolean
    d: [new Schema({
        f: String
        g: String
    }, {_id: false})]
}
```

Example:

```js
Object.keys(myDocument.testData);  // returns [  '$__',  'isNew',  'errors',  '_doc', '$__original_save',  'save',  '_pres',  '_posts',  '$__original_init',  'init',  'toObject',  'toJSON',  '$__isNested',  'a',  'b', 'c',  'd']
Object.keys(myDocument.testData.toObject({minimize: false})); //returns ['d'] instead of ['a','b','c','d']
```

Am I misunderstanding this method option? If so how do I remove the mongoose keys from an object without removing the empty field stubs? On 3.8.x the only mongoose field returned by Object.keys(document.subObject) was toObject so it was simple enough to filter it specifically. I can do that again for all of these fields, but I wanted to make sure this was expected behavior and that there wasn't a more 'correct' way of doing it. Thanks :)

**Comment by vkarpov15** [comment]
@unusualbob what does the actual data of the object that you're running `.toObject()` on look like?

**Comment by unusualbob** [comment]
The raw object is mostly empty:
```js
{
  testField: "some data",
  testData: {
    d: []
  }
}
```

I know that running Object.keys on this object.testData would return only `'d'`, but when wrapped as a mongoose document and minimize: false I expected the other fields to be initialized with empty values.

**Comment by vkarpov15** [comment]
Why don't you use defaults? Mongoose won't create default values in the `toObject()` output for you.

**Comment by unusualbob** [comment]
In this case I don't care about the values at all, just the keys on the object. Is there a different way to access the available keys on an instance without getting all the mongoose items?

**Comment by vkarpov15** [comment]
Yeah there's no other way to do this that I know of beyond just `Object.keys()` on the nested object. Usually you don't need to do that though. Can you tell me more about what you're trying to achieve by getting all available keys?

**Comment by unusualbob** [comment]
I've got a CSV export function with a stream of documents and I'm using the key names to generate the header fields and want to include all keys even if they are empty. In upgrading to 4.x I found there are far more special mongoose fields that are returned when doing Object.keys so I figured there must be a better way than manually filtering all the additional fields via a blacklist.

I have been planning to take a look at how toObject actually works later this week to see if there's a way to identify and filter mongoose properties programmatically as opposed to just naming them in a blacklist. I had assumed that toObject would basically do that with `{minimize: false}` flag set, but it seems it has some other usage. (what is `minimize: false` used for if not this by the way?).

**Comment by vkarpov15** [comment]
[Minimize toggles whether mongoose removes empty objects](http://mongoosejs.com/docs/guide.html#minimize), doesn't affect primitives.

A better alternative IMO would be to just iterate through the schema, rather than the objects. A mongoose schema has [a nice `eachPath()` function](http://mongoosejs.com/docs/api.html#schema_Schema-eachPath) that's useful for this case.

**Comment by unusualbob** [comment]
Thanks @vkarpov15 that pointer to eachPath really helped things along. I managed to get this working, just in case anyone else comes up against this here you go:

```js
var validTestDataPaths = [];

Storage.model('MyModel').schema.eachPath(function(path) {
  //Narrow down results to only our subdocument
  if (path.indexOf('testData') === 0) {
    //Strip leading 'testData.' from path name and insert it into our whitelist
    validTestDataPaths.push(path.substr(9));
  }
});

function buildCsvHeaders() {
  var csvKeys = [];

  //Inside some mongo find op
  function processDocumentKeys(myDocument) {
    var testData = myDocument.testData;

    Object.keys(testData).forEach(function (key) {
      //Filters out keys which we already know about, keys we dont want, and then only allows keys we identified were on the schema
      if (csvKeys.indexOf(key) === -1 && key !== 'd' && validTestDataPaths.indexOf(key) !== -1) {
        csvKeys.push(key);
      }
    });
  }
}
```
