### ISSUE TITLE
Lookup returns empty array

### ISSUE THREAD

**Issue by zavernutiy** [Automattic/mongoose#3858]
Hello, I receive empty array with lookup. Here is my code:
`user.js`
```
var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

var UserSchema   = new Schema({
    fbId: Number,
    firstName: String,
    lastName: String,
    name: String,
    email: String,
    picture: String,
    favorites: Array
});

module.exports = mongoose.model('User', UserSchema);
```

`comment.js`
```
var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

var CommentSchema   = new Schema({
    userId: String,
    tvShowId: String,
    episodeId: String,
    type: String,
    content: String,
    date: Date
});

module.exports = mongoose.model('Comment', CommentSchema);
```

`server.js`
```
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/tvapi');

var User = require('./app/models/user');
var Comment = require('./app/models/comment');
...
        Comment.aggregate([
            {
                $match: {
                    type: type,
                    tvShowId: tvShowId,
                    episodeId: episodeId
                }
            },
            {
                $lookup: {
                    from: 'users',
                    localField: 'userId',
                    foreignField: '_id',
                    'as': 'user'
                }
            }
        ], function(err, comments) {
            if (err) {
                res.json({Error: err});
            }

            res.json({comments: comments});
        });
```

I've checked that there is a comment that has `userId`, and the user with corresponding `_id`, so it should be a user in the array. I think my problem is in the lookup `from` or `foreignField`, could you help me please?

**Comment by vkarpov15** [comment]
In CommentSchema, `userId` is a string, but in UserSchema `_id` is an ObjectId. As such, comments will always have string userIds, and users will always have an ObjectId, so `$lookup` will never actually match these two

**Comment by mustafaekim** [comment]
I have the same issue. I have to match string and objectIds within $lookup. How can I ?

**Comment by vkarpov15** [comment]
There's no general way to convert types in the aggregation framework. http://stackoverflow.com/questions/14989058/mongo-new-date-in-aggregate-project suggests a way you might be able to hack a way around it, but the right answer would be to convert the string to an objectid
