### ISSUE TITLE
Populate return null on nested path

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#3859]
In the code below, I rewrote the test to handle a document, unlike in the #3802
Is it the correct behaviour expected?

_I wasn't sure if I would comment or create a new issue because of the "won't fix" status of the previous one, sorry if I would't have create a new one_

    var mongoose = require('mongoose');
    mongoose.Promise = require('bluebird');
    
    var companySchema = new mongoose.Schema({
      name:  String,
      description:  String
    });
 
    var userSchema = new mongoose.Schema({
      name:  String,
      company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company'}
    });
    
    var sampleSchema = new mongoose.Schema({
      items:  [userSchema]
    });
    
    var Company = mongoose.model('Company', companySchema);
    var User = mongoose.model('User', userSchema);
    var Sample = mongoose.model('Sample', sampleSchema);
    
    mongoose.connect(
      'mongodb://127.0.0.1/test',
      {},
      function (err) {
        if (err) {
          return console.error(err);
        }
    
        var company = new Company({name: 'Reynholm Industrie'});
        var user1 = new User({name: 'Douglas', company: company._id});
        var user2 = new User({name: 'Lambda'});
        var sample = new Sample({
          items: [user1, user2]
        });
    
        Promise
          .all([
            company.save(),
            user1.save(),
            user2.save(),
            sample.save()
          ])
          .then(function () {
            return Sample.findOne({}).exec();
          })
          .then(function (sample) {
            return Company.populate(sample, {path: 'items.company', options: {lean: true}});
          })
          .then(function (sample) {
            console.log(sample);
              /*
             { items: [
              {
                name: 'Douglas',
                company: [Object],
                _id: 56b4d572b4737d774f9dd7ee
              },
    
               {
                 name: 'Lambda',
                 _id: 56b4d572b4737d774f9dd7ef,
                 company: null                          //  <== null object
               }
             ],
             __v: 0,
             _id: 56b4d572b4737d774f9dd7f0 }
             */
    
          });
      }
    );

**Comment by vkarpov15** [comment]
This is correct behavior: the "Lambda" user doesn't have an associated company, so populate will give you a null object.

**Comment by jbdemonte** [comment]
Really?
If you do the same, one level up, from the users, you don't get the same result

    var mongoose = require('mongoose');
    mongoose.Promise = require('bluebird');
    
    var companySchema = new mongoose.Schema({
      name:  String,
      description:  String
    });
    
    var userSchema = new mongoose.Schema({
      name:  String,
      company: {type: mongoose.Schema.Types.ObjectId, ref: 'Company'}
    });
    
    var sampleSchema = new mongoose.Schema({
      items:  [userSchema]
    });
    
    var Company = mongoose.model('Company', companySchema);
    var User = mongoose.model('User', userSchema);
    var Sample = mongoose.model('Sample', sampleSchema);
    
    mongoose.connect(
      'mongodb://127.0.0.1/test',
      {},
      function (err) {
        if (err) {
          return console.error(err);
        }
    
        var company = new Company({name: 'Reynholm Industrie'});
        var user1 = new User({name: 'Douglas', company: company._id});
        var user2 = new User({name: 'Lambda'});
        var sample = new Sample({
          items: [user1, user2]
        });
    
        Promise
          .all([
            company.save(),
            user1.save(),
            user2.save(),
            sample.save()
          ])
          .then(function () {
            return User.find({}).exec();
          })
          .then(function (users) {
            return Company.populate(users, {path: 'company', options: {lean: true}});
          })
          .then(function (sample) {
            console.log(sample);
            /*
             [ 
              {
                __v: 0,
                company: { _id: 56bd8aeb72ac44b74b9d3ca8, name: 'Reynholm Industrie', __v: 0 },
                name: 'Douglas',
                _id: 56bd8aeb72ac44b74b9d3ca9 
              },
              
              { __v: 0, name: 'Lambda', _id: 56bd8aeb72ac44b74b9d3caa }  <= no null object here
             
             ]
    
             */
    
          });
      }
    );

**Comment by vkarpov15** [comment]
Hmm that's strange. Perhaps this has something to do with #3873. I'll revisit this.

**Comment by Jeff-Lewis** [comment]
This issue or a very similar issue occurs still if the referencing _id' actual document does not exist in the database. In other words, when populating a sub-doc's properties, if the referenced doc does not exist, the id will be replace with null.

I have a full repro here https://ide.c9.io/jefflewis/mongoose-populate-missing-ref. It's similar to the [repro #3859](https://github.com/Automattic/mongoose/commit/b5df43eda4b5525a3f483c099560dcc4dd99b911) but the difference would be not saving user2 doc in the db, only it's id in Sample items.

**Comment by vkarpov15** [comment]
Thanks for the repro instructions @Jeff-Lewis . I'll check this out later, currently backed up on other issues - check on #3937 for updates

**Comment by Jeff-Lewis** [comment]
I see it. Thanks!
