### ISSUE TITLE
Message related to kerberos is out to console in 4.4.2

### ISSUE THREAD

**Issue by cartuchogl** [Automattic/mongoose#3860]
````shell
$ node -e "require('mongoose')"
[TypeError: Cannot read property 'Kerberos' of undefined]
$
````

on nodejs 0.12.9

**Comment by pqvst** [comment]
Just installed mongoose 4.4.2 with node 5.5.0 and I am also receiving the above error as soon as I require mongoose. Why?

**Comment by cartuchogl** [comment]
In my case, debian jessie with node 0.12.9, this is not an error, but corrupts the output of my scripts. It's fine with 4.4.1. I think that it is related with a recent change on mongodb or mongodb-core deps.

**Comment by perrin4869** [comment]
same here, Slackware64-current, node 5.5.0

**Comment by alanpurple** [comment]
+1

**Comment by NerdPad** [comment]
+1

**Comment by think2011** [comment]
+1

**Comment by CanadianOranges** [comment]
+1

**Comment by deadlybutter** [comment]
Temp fix for those experiencing this...

```
rm -rf node_modules/mongoose/node_modules/mogodb
npm install --prefix ./node_modules/mongoose/ mongodb@2.1.6 --save
```

**Comment by peterbsmith2** [comment]
I got this issue with mongoose 4.4.2, node version 4.2.3, mongodb version 2.1.5.

I changed my mongoose version from 4.4.2 to 4.4.1 and that removed the error.

Apparently mongoose 4.4.1 depends on mongodb 2.1.4 which depends on kerberos 0.0.18.

mongoose 4.4.2 depends on mongodb 2.1.5 which removes kerberos as a dependency. So it seems mongoose is looking for a kerberos dependency to exist in mongodb which it no longer does.

**Comment by alfredopacino** [comment]
+1

**Comment by davegri** [comment]
+1

**Comment by fpayer** [comment]
+1

**Comment by zxlin** [comment]
+1

Can confirm running `npm install kerberos` fixes the issue temporarily. Would prefer an upstream fix.

**Comment by Nexeuz** [comment]
Hello, I'm newbie using mongodb, I tell them my folder mongodb install npm install mongoose installed --save me normal, but does not recognize me "mongo" command down what happens when I start the server is displayed

![image](https://cloud.githubusercontent.com/assets/17104494/12870518/a1a38ccc-cd16-11e5-9b23-f247534cd1ee.png)


sorry for mi english

**Comment by staff0rd** [comment]
+1

**Comment by Risto-Stevcev** [comment]
+1

**Comment by NateFuller** [comment]
+1

**Comment by KuroGuo** [comment]
+1

**Comment by VirtualOverride** [comment]
i tried what @zxlin said. it fix the issue. not sure if this is permanent fixed.

**Comment by madhudskumar** [comment]
+1

**Comment by SamuelMarks** [comment]
+1

**Comment by madhudskumar** [comment]
@zxlin did fix the issue if installed at local

**Comment by DSTParis** [comment]
Hello I have the same problem too :( 
[TypeError: Cannot read property 'Kerberos' of undefined]  &
Database error: MongoError: getaddrinfo ENOTFOUND localhost localhost:27017

**Comment by cbratschi** [comment]
+1

**Comment by sallespro** [comment]
@ deadlybutter did the trick. thanks !

**Comment by mukul-raina** [comment]
like @zxlin said `npm install kerberos` works

**Comment by alfredopacino** [comment]
trying to install kerberos I get the error (sorry for the italian messagge the error code is MSB4019)
```
\node_modules\kerberos\build\k
erberos.vcxproj(20,3): error **MSB4019**: progett
o importato "C:\Microsoft.Cpp.Default.props" 
non trovato. Verificare che il percorso nella
 dichiarazione <Import> sia corretto e che il
 file sia presente sul disco.

```

**Comment by psantos10** [comment]
`npm install kerberos` solved my problem too

**Comment by franzwcom** [comment]
deleted my mongoose "mongoose": "^4.4.2", and  installed again with the last version "mongoose": "^4.4.6", the issue is gone
