### ISSUE TITLE
Model.save called multiple times

### ISSUE THREAD

**Issue by gergelyke** [Automattic/mongoose#3862]
Hey,

I have a very simple model:

```
const FooSchema = new Schema({
  name: String
});

const Model = mongoose.model('Foo', FooSchema);
```

Then I do this:

```
const foo = new Foo({ name: 'bar' });
foo.save().then(function () {

})
```

In this case sometimes the callback for the `then` gets called multiple times - any idea why it can happen?

**Comment by vkarpov15** [comment]
Not that I know of. I'll try to repro this this week.

**Comment by gergelyke** [comment]
Thanks!

**Comment by gergelyke** [comment]
One thing that may help: if I turn off the `versionKey` in the options it doesn't happen.

**Comment by gergelyke** [comment]
Is there any way I can help you with?

**Comment by vkarpov15** [comment]
@gergelyke a more detailed code sample would help. Working on reproing now.

**Comment by vkarpov15** [comment]
@gergelyke here's my attempt at reproing. Executes the above code 50000 times, not a single instance of the behavior you're seeing. Can you see if the below script bugs out in your environment? If not, gonna need a more detailed code sample.

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3862');

const FooSchema = new mongoose.Schema({
  name: String
});

const Foo = mongoose.model('Foo', FooSchema);

let calls = 50000;
next();

function next() {
  if (--calls <= 0) {
    process.exit(0);
  }
  console.log(calls);
  const foo = new Foo({ name: 'bar' });
  let called = false;
  foo.save().then(function() {
    assert.ok(!called);
    called = true;
    next();
  });
}
```

**Comment by vkarpov15** [comment]
Issue's been stale, closing. Re-open if this is still an issue.
