### ISSUE TITLE
Mongoose not closing connections

### ISSUE THREAD

**Issue by refaelos** [Automattic/mongoose#3863]
I'm using mongoose to connect to my MongoDB server on production.

```
  mongo   : {
    uri    : process.env.MONGO_URL,
    options: {
      user   : process.env.MONGO_USER,
      pass   : process.env.MONGO_PASS,
      server : {
        socketOptions: {
          keepAlive       : 1,
          socketTimeoutMS : 300000,
          connectTimeoutMS: 300000
        }
      },
      replset: {
        rs_name      : process.env.MONGO_RS_NAME || "set-name",
        socketOptions: {
          keepAlive       : 1,
          socketTimeoutMS : 300000,
          connectTimeoutMS: 300000
        },
        readPreference: 'secondaryPreferred',
        poolSize: 50
      }
    }

  }
```

I've set tcp_keepalive_time to 120:

```
echo 120 | sudo tee /proc/sys/net/ipv4/tcp_keepalive_time
```

The problem is the connections keep opening to the server but never closing.

1. Why are connections keep opening to the server?
2. Why are connections not being closed?

Btw, connections are only opening to Primary. On Secondary I don't see too many open connections.

**Comment by vkarpov15** [comment]
Are you able to connect using the mongo shell? Does the connection stay open?

**Comment by refaelos** [comment]
@vkarpov15 yes. It works perfectly from mongo shell.

I'm starting to suspect linux configurations... in case you can say for sure it's not with mongoose or mongodb driver?

**Comment by refaelos** [comment]
@vkarpov15 weird thing... when I lower the pool size from 50 to 10 the sockets don't keep opening. Can you explain why?

**Comment by refaelos** [comment]
Anyone can help here?

Another finding we had is that connections are less likely to rise when we remove the socketTimeout and connectionTimeout and keepAlive settings. Not sure why...

**Comment by vkarpov15** [comment]
Which version of mongoose? Also try reading through the thread on #3634 and https://jira.mongodb.org/browse/NODE-622, this looks like a similar issue

**Comment by refaelos** [comment]
We use the latest v4.4.2

Right now we removed all mongoose settings except `poolSize`. We just put the replica set in the connection string and don't put any values for socketTimeout and connectionTimeout. Things seems to work better although we're still monitoring it to see what happens over time. 

I don't know if this is recommended to do things like that but we didn't find any other option.

**Comment by vkarpov15** [comment]
There's a lot of tips in the issues I referenced in https://github.com/Automattic/mongoose/issues/3863#issuecomment-181962533 . Typically these issues are because of the network, and often the solution is "tune socketTimeoutMS to the right value". You may also want to watch the 'joined' and 'left' events referenced in https://jira.mongodb.org/browse/NODE-622 and turn on debug mode for repl sets as described here: https://github.com/Automattic/mongoose/issues/3634#issuecomment-163728573 to get more insight into what's going on.

**Comment by refaelos** [comment]
@vkarpov15 we tried tuning the socketTimeout. We set larger and shorter values... nothing helped. When we removed it, things started behaving good. I wonder if you have an explanation to that.

**Comment by vkarpov15** [comment]
AFAIK socketTimeoutMS=0 means use the OS' socket timeout, so if that works for you go for it. I personally don't bother setting socketTImeoutMS ever. Some more info: http://mongodb.github.io/node-mongodb-native/2.0/tutorials/connection_failures/ .

**Comment by refaelos** [comment]
@vkarpov15 perfect thanks!
