### ISSUE TITLE
JetBrains Integration doesn't work

### ISSUE THREAD

**Issue by robertleeplummerjr** [Automattic/mongoose#3870]
This isn't a bug for Mongoose, but needs attention from those who use WebStorm, PhpStorm, or any other JetBrains IDE with Mongoose. Here is the issue: https://youtrack.jetbrains.com/issue/WEB-17099
We need to upvote it to get it fixed there to have better integration here.  Please up-vote and help make Mongoose Integration rock solid, as it is a fine product.

**Comment by Jeff-Lewis** [comment]
Awesome @robertleeplummerjr. Thanks for reporting to JetBrains and here. I voted.

**Comment by robertleeplummerjr** [comment]
Spread the word!  Let's get as many people from our networks that use Mongoose and JetBrains products to upvote this.

**Comment by TrejGun** [comment]
:+1:

**Comment by vkarpov15** [comment]
Happy to support, but I have zero experience with JetBrains, WebStorm, etc. PRs welcome.

**Comment by robertleeplummerjr** [comment]
Start by voting it up, and spreading the word.

On Thu, Feb 11, 2016 at 10:30 AM, Valeri Karpov <notifications@github.com>
wrote:

> Happy to support, but I have zero experience with JetBrains, WebStorm,
> etc. PRs welcome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3870#issuecomment-182917161>
> .
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Also, @vkarpov15, honored that you'd support this.  Keep up the hard work!  Ok guys, lets keep on voting it up!

**Comment by cyberjoac** [comment]
+1

**Comment by sibelius** [comment]
I think we can close this, not a problem with mongoose

**Comment by robertleeplummerjr** [comment]
Ty everyone who gave this attention.
