### ISSUE TITLE
basic schema with multiple extensions

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#3876]
Hi, I have 4 type of documents.
Some fields are common, some not.
What's you think is the better way to structure those db?
There is a better way than 4 indipendent schemas (and collections)?

The problem is I have to expose at least a resource that lists all the documents and query on those.

**Comment by vkarpov15** [comment]
[Discriminators](http://mongoosejs.com/docs/discriminators.html) should help. [My blog post about discriminators](http://thecodebarbarian.com/2015/07/24/guide-to-mongoose-discriminators) is also a useful resource.
