### ISSUE TITLE
Invalid value for schema path for nested documents

### ISSUE THREAD

**Issue by rutvik18** [Automattic/mongoose#3881]
Source:

`var ProfileSchema = new mongoose.Schema({

 	profile_id : {type: Number, required : true},
 	user_id : {type: String, required : true},
 	profile_type : {type: String, enum : ['talent', 'class', 'vendor', 'organsiation', 'bomb' ], required : true},
 	display_name : {type: String, required : true},
 	name : {
 		first_name : {type : 'String'},
 		last_name : {type : 'String'},
 		middle_name : {type : 'String'}
 	},
 	display_picture : {
 		cover_pic_media : {type : String},
 		profile_pic_media : {type : String},
 	},
 	tagline : {type : String},
 	about : {type : String},
 	gender : {type: String, enum : ['male', 'female' ]},
 	birthdate : {type : Date},
 	address : [{type: mongoose.Schema.Types.Object, ref: 'AddressSchema' }],
 	contact : {
 		emails : [{type: mongoose.Schema.Types.Object, ref: 'EmailSchema' }],
 		phones : [{type: mongoose.Schema.Types.Object, ref: 'PhoneSchema' }],
 	},
 	urls : {
 		type : String,
 		url : String,
 		is_active : Number
 	},
 	current_step : String,
 	referral_id : {
 		referral_type : { 
 			type : String , enum : ["agency", "fos", "invite"]
 		},
 		ref_id : String,
 	},
 	is_agency : Number,
 	agency_meta : {
 		pan : String,
	 	tan : String,
	 	st : String,
	 	agency_code : String
 	},
 	aggrements : {
 		loi : Number,
		tos : Number,
 		accepted_date : Date
 	},
 	languages : [{type: mongoose.Schema.Types.Object, ref: 'LanguageSchema' }],
 	work_exp : [{type: mongoose.Schema.Types.Object, ref: 'WorkExpSchema' }],
 	dreams : [{type: mongoose.Schema.Types.Object, ref: 'DreamsSchema' }],
 	idols : [{type: mongoose.Schema.Types.Object, ref: 'IdolsSchema' }],
 	interests : [{type: mongoose.Schema.Types.Object, ref: 'InterestsSchmea' }],
 	events : [{type: mongoose.Schema.Types.Object, ref: 'EventSchema' }],
 	created_at : { type : Date, default: Date.now, required : true },
 	updated_at : { type : Date, default: Date.now, required : true },
 	is_active : { type : Number, default: 1},
 	last_modified_date : Date

 },{ collection: 'profiles' }
);`

I am getting this error while running app:

Invalid value for schema path `url`

Any clue?

**Comment by vkarpov15** [comment]
```javascript
urls : {
    type : String,
    url : String,
    is_active : Number
},
```

The above tells mongoose that `urls` is a String field, rather than `urls` is an object field with 3 properties. Rename the `type` field to `kind` or [use a custom `typeKey` as shown here](http://mongoosejs.com/docs/guide.html#typeKey)

**Comment by phavor** [comment]
@vkarpov15 could you show an example with the `kind` field? am currently having similar error in my terminal

**Comment by vkarpov15** [comment]
@phavor : 

```javascript
urls : {
    kind: String,
    url: String,
    is_active: Number
},
```
