### ISSUE TITLE
Create Price range from Filter Data ..

### ISSUE THREAD

**Issue by Ashesh007** [Automattic/mongoose#3885]
Wan't create Price range Using mongodb aggregation pipeline.. while using elastic search or solr we can directly get price filter range value... How can i create price range according to my products price, if there is no product in that range then don't create that range...
`{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 1200
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 200
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 2000
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 2020
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 100
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 3500
},
{ 
    "_id" : ObjectId("5657412ddb70397479575d1d"),"price" : 3900
}`

From above i have to create price range filter value as par product price using Mongo aggregation...
and out put is like

`[
        {
            range : '100-200',
            count : 2
        },
        {
            range : '1200-2020',
            count : 3
        },
        {
            range : '3500-3900',
            count : 2
        }
]`

**Comment by adrian-ludwig** [comment]
Use map-reduce for mongodb

**Comment by Ashesh007** [comment]
how to use not understand.. can u give me some expectation using my problems..??

**Comment by adrian-ludwig** [comment]
The best way of doing it would be to use map-reduce:
https://docs.mongodb.org/manual/core/map-reduce/

You propobly could do this by using Aggregation Framework, but it would be much trickier than using map-reduce.

Also I think you problem is not mongoose related :)

**Comment by vkarpov15** [comment]
http://stackoverflow.com/questions/29972393/create-a-price-range-facet-in-mongodb-aggregation-pipeline

General idea would be to use a `$project` stage that sets a boolean for each price range. Admittedly this is extremely awkward to do with the aggregation framework, you might be better off using map-reduce as @adrian-ludwig suggested. Below is the general idea of how you'd do this with aggregation.

```javascript
Product.aggregate([
  {
    $project: {
      '0-100': { $cond: { $if: { $gte: 0, $lte: 100 }, $then: true, $else: false } },
      '100-200': { $cond: { $if: { $gte: ['price', 100, $lte: 200 }, $then: true, $else: false } }
    }
  },
  {
    $group: { _id: { '0-100': '$0-100', '100-200': '$100-200' }, count: { $sum: 1 } }
  }
]);
```
