### ISSUE TITLE
Performance Regression with Mongoose 4.x on Mongoose document creation

### ISSUE THREAD

**Issue by Farfad** [Automattic/mongoose#3886]
Hi,
A regression has been observed by passing from Mongoose 3.x to the latest version (4.4.3).
Indeed the conversion of JSON to Mongoose document is around 5 times longer when the schema is a little bit complex with emebbed documents.

To highlight this regression I just created a lite Nodejs application which does one query (this query returns 2 documents with embedded documents) to the following schema:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var EmbeddedA = new Schema({
    key1: String,
    key2: String
}, {_id: false});

var EmbeddedB = new Schema({
    key1: String,
    key2: String,
    key3: String,
    key4: String, 
    key5: {
        key51: String,
        key52: String,
        key53: [EmbeddedA],
        key54: Boolean,
        key55: Boolean   
    }}, {_id: false});

var EmbeddedC = new Schema({
    key1: String,
    key2: [String],
    key3: {
        key31: [EmbeddedA],
        key32: Boolean,
        key33: [],
        key34: [],
        key35: String
    }}, {_id: false});

var EmbeddedD = new Schema({
    key1: String,
    key2: String
}, {_id: false});

var EmbeddedE = new Schema({
    key1: String,
    key2: String, 
    key3: [EmbeddedD]
}, {_id: false});

var EmbeddedF = new Schema({
    key1: String,
    key2: String,
    key3: String, 
    key4: String,
    key5: Number,
    key6: [EmbeddedB],
    key7: [EmbeddedB],
    key8: [EmbeddedB],
    key9: [EmbeddedC],
    key10: [EmbeddedE]
}, {_id: false});

var FinalSchema = new Schema({
    key1: String,
    key2: {type: String, default: 'DEFAULT_STRING'},
    key3: String, 
    key4: String,
    key5: String,
    key6: [EmbeddedF]
});
```
The below table summarizes the response time for this query (getting the two documents):

Mongoose 3.x | Mongoose 4.x | lean() ?
------------ | ------------- | -------------
113 ms | 500 ms| No
14 ms | 17 ms| Yes

When the conversion from JSON to mongoose document is required (first line of the table), the latest version of mongoose spends around 5 more times to construct this Mongoose document (with embedded documents). In order to substantiate this claim,the second line shows that time is spent in conversion since without this conversion only 17 ms is needed to get the JSON. 
Moreover, the profiling shows that for Mongoose 4.x 90% of time is spent into DocumentArray and Array constructors (lib/types/documentarray.js or lib/types/array.js)

**Comment by vkarpov15** [comment]
Thanks for the detailed report, will take a look later this week.

**Comment by Farfad** [comment]
@vkarpov15, any news for this topic?
Thanks.
Regards.

**Comment by vkarpov15** [comment]
Not yet, haven't had a chance to take a look at it. Been backed up on other issues.

**Comment by vkarpov15** [comment]
This looks like a dup of #3728 re: #3461. @boblauer I think I'm gonna have to revert the changes from #3461, the perf overhead for docs with lots of arrays is just too huge (in below example, removing `defineProperties()` and using plain assignment instead cuts runtime in half including network I/O) to justify saving a `.toObject()` call in a test framework.

Long story short, the reason for the degradation is that 4.0 can't use the `__proto__` trick to extend arrays because IE9 and IE10 don't support it, and we need that for isomorphic schemas. This leads to us relying on assigning a bunch of functions to an array, which is marginally slower. However, once you try to use `defineProperty()` to make those properties non-enumerable, performance drops like a rock.

Overall plan is to push this change to 4.5 as a general courtesy, because IMO this change is a bit too big for a point release.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test');
var Schema = mongoose.Schema;
var EmbeddedA = new Schema({
    key1: String,
    key2: String
}, {_id: false});

var EmbeddedB = new Schema({
    key1: String,
    key2: String,
    key3: String,
    key4: String,
    key5: {
        key51: String,
        key52: String,
        key53: [EmbeddedA],
        key54: Boolean,
        key55: Boolean
    }}, {_id: false});

var EmbeddedC = new Schema({
    key1: String,
    key2: [String],
    key3: {
        key31: [EmbeddedA],
        key32: Boolean,
        key33: [],
        key34: [],
        key35: String
    }}, {_id: false});

var EmbeddedD = new Schema({
    key1: String,
    key2: String
}, {_id: false});

var EmbeddedE = new Schema({
    key1: String,
    key2: String,
    key3: [EmbeddedD]
}, {_id: false});

var EmbeddedF = new Schema({
    key1: String,
    key2: String,
    key3: String,
    key4: String,
    key5: Number,
    key6: [EmbeddedB],
    key7: [EmbeddedB],
    key8: [EmbeddedB],
    key9: [EmbeddedC],
    key10: [EmbeddedE]
}, {_id: false});

var FinalSchema = new Schema({
    key1: String,
    key2: {type: String, default: 'DEFAULT_STRING'},
    key3: String,
    key4: String,
    key5: String,
    key6: [EmbeddedF]
});

var Final = mongoose.model('Final', FinalSchema);
var f = new Final({
  key1: 'test',
  key3: 'test',
  key4: 'test',
  key5: 'test',
  key6: [{
    key1: 'test',
    key3: 'test',
    key4: 'test',
    key6: [{
      key5: {
        key53: [{ key1: 'test' }]
      }
    }],
    key7: [{
      key5: {
        key53: [{ key1: 'test' }]
      }
    }],
    key8: [{
      key5: {
        key53: [{ key1: 'test' }]
      }
    }],
    key9: [{
      key3: {
        key31: [{ key1: 'test' }]
      }
    }],
    key10: [{
      key1: 'test',
      key3: [{ key1: 'test' }]
    }]
  }]
});

var totalTime = 0;
f.save(function(error) {
  console.log(error && error.errors);
  assert.ifError(error);
  bench(f._id);
});

function bench(id) {
  step(id, 0);
}

function step(id, count) {
  if (count >= 100) {
    console.log(totalTime, ' over 100 runs, ', totalTime / 100, 'average');
    process.exit(0);
  }
  var start = Date.now();
  Final.findById(id, function(error) {
    assert.ifError(error);
    totalTime += (Date.now() - start);
    step(id, count + 1);
  });
}
```

**Comment by boblauer** [comment]
Sounds good.  Sorry to introduce such a bottleneck, I didn't realize `defineProperty` was so slow.

**Comment by vkarpov15** [comment]
No worries, my fault for not paying closer attention to perf :palm_tree: good article on the subject: https://www.nczonline.net/blog/2015/11/performance-implication-object-defineproperty/ . With mongoose, the performance implications of defineProperty() get compounded because we use it for every single array.

**Comment by Farfad** [comment]
@vkarpov15, thanks a lot for your investigation.
What's the ETA for the 4.5?

**Comment by vkarpov15** [comment]
The eta right now is may 1 - check github milestones for roadmap. I'm going to investigate a couple alternatives but I think we'll push that up if our other alternatives don't work out

**Comment by stephanvermeire** [comment]
@vkarpov15: First I want to thank you for your excellent work on mongoose so far.

Currently I am working om my first mongoose project and I'm encountering serious performance problems when retrieving objects with many subdocuments. I really appreciatie your efforts to fix this issue.

**Comment by simoneb** [comment]
I believe this change broke node's `assert.deepEqual` between a standard array and a `MongooseArray`. Very painful to track down when all you get is an assertion error which does not show the differences. Wouldn't a more conceptually correct approach be to add such properties to the prototype of the `MongooseArray` *class*?

**Comment by Sebmaster** [comment]
@simoneb Sadly extending `Array`s is not easy while maintaining IE 9 + 10 compat (which mongoose tries to do). Normal prototypal inheritance doesn't really apply there.

Although I have to admit, this patch also breaks a lot of tests in our code and is an additional major change compared to 3.8.

**Comment by simoneb** [comment]
@Sebmaster agreed. It's quite a major change compared to 4.4 in fact.

**Comment by vkarpov15** [comment]
Yeah this is why we postponed this to 4.5 - it can be considered a breaking change because of `assert.deepEqual()`, but as @Sebmaster said there's really no way to get this functionality right without massive performance overhead in ES5. ES6 makes it better of course, but mongoose 4 still needs to support ES5 environments. As a workaround, you can just do `arr.toObject()` and your deep equality checks should work...

**Comment by simoneb** [comment]
Thanks for the explanation, that's exactly what I ended up doing. The only
thing is that I would probably like to see such a change more visible in
the change log.

**Comment by vkarpov15** [comment]
@simoneb added. https://github.com/Automattic/mongoose/blob/master/History.md#450--2016-06-13

**Comment by simoneb** [comment]
Awesome, great job guys!

**Comment by vkarpov15** [comment]
Thanks for the suggestion, and sorry about the trouble.

**Comment by puzrin** [comment]
What about use feature detection to select the best inheritance approach?

- ES6-capable things could use honest Array subclassing
- Ancient garbage like IE could continue use of `defineProperty`, because nobody cares about performance there.

That could solve performance problem without breaking deepEqual and so on.

**Comment by vkarpov15** [comment]
@puzrin that would be a pretty good approach. PRs would be welcome, or suggestions as to how to check if a JS environment supports Array subclassing :)

**Comment by Sebmaster** [comment]
Can we just check `Object.setPrototypeOf`? It's also the official replacement for `__proto__`.

However, that leads to an inconsistency between IE9/10 and IE11 in the library, is that acceptable?

**Comment by puzrin** [comment]
@vkarpov15

I guess, something like this:

```js
function canClass() {
  try {
    eval 'class C {}; return typeof C === "function";'
  } catch (__) {}
  return false;
}
```

See https://kangax.github.io/compat-table/es6/ "array subclassing", probably more strict check required. But principle is the same - eval string with required equation.

**Comment by vkarpov15** [comment]
Thanks for suggestions, follow this issue in #4265
