### ISSUE TITLE
I'm desperate for a question...

### ISSUE THREAD

**Issue by igordeoliveirasa** [Automattic/mongoose#3887]
Is there any way to disable cast verification of ObjectId ? It's because I have to use mongoose to access an already created and in production mongodb and they use id's like: "oH25foZvnM" instead of mongoose ObjectId pattern.

Thank you so much.

**Comment by vkarpov15** [comment]
[Set the `_id` option to false for your schema](http://mongoosejs.com/docs/guide.html#_id)
