### ISSUE TITLE
Plugin Application error

### ISSUE THREAD

**Issue by djoq** [Automattic/mongoose#3888]
http://plugins.mongoosejs.com/ is down.

**Comment by vkarpov15** [comment]
The plugins site does some aggressive caching and so requires too much memory to run properly on our current heroku setup - too many mongoose plugins :) Use http://plugins.mongoosejs.io/ instead. If you're interested in helping modernize the plugins site, here's the github repo: https://github.com/aheckmann/mongooseplugins

**Comment by djoq** [comment]
Okay, I updated the link, is it possible to merge?

https://github.com/djoq/mongoose-1

On Thu, Feb 18, 2016 at 2:05 PM, Valeri Karpov <notifications@github.com>
wrote:

> The plugins site does some aggressive caching and so requires too much
> memory to run properly on our current heroku setup - too many mongoose
> plugins :) Use http://plugins.mongoosejs.io/ instead. If you're
> interested in helping modernize the plugins site, here's the github repo:
> https://github.com/aheckmann/mongooseplugins
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3888#issuecomment-185864342>
> .
>



-- 
Daniel O'Quinn
BS Mechanical Engineering
University of Massachusetts Amherst
daniel@cambridge-blockchain.com
danieljoquinn@gmail.com
617-571-7257 (cell)

**Comment by vkarpov15** [comment]
Already made those changes in master in https://github.com/Automattic/mongoose/commit/ad298cb0e58105271a794043fa5ac6d8da812f93

**Comment by djoq** [comment]
Is there a way to make the publicly accessed server point to this new
revision?

**Comment by vkarpov15** [comment]
Yes that'll happen when 4.4.5 is released, which will be over the weekend or early next week.
