### ISSUE TITLE
Object.keys applied on a query callback has extra keys

### ISSUE THREAD

**Issue by SkateFreak** [Automattic/mongoose#3891]
Object.keys(user).forEach(function (key, i) {
        console.log(key);
    });

this is what my console looks like: 

    $__
    isNew
    errors
    _doc
    $__original_save
    save
    _pres
    _posts
    toObject
    toJSON
    $__isNested
    userName
    userEmail

how can iterate on my result keys if it has 11 more keys?

thanks!

**Comment by vkarpov15** [comment]
`Object.keys(user.toObject());`
