### ISSUE TITLE
Support `ordered` option for `insertMany()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3893]
Re: https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#basic #2016

**Comment by raitucarp** [comment]
When 4.6 released?

**Comment by vkarpov15** [comment]
No ETA yet.

**Comment by yasharma** [comment]
I am receiving lot of data from webhooks and it also contains some duplicate data, now i am using mongoose `insertMany` option, however i cannot use `{ 'ordered': false }` to skip duplicate data. please help me if any alternative of this. @vkarpov15

**Comment by vkarpov15** [comment]
You can always just use `MyModel.collection.insertMany(data, { ordered: false });` to bypass mongoose. Mongoose's `insertMany()` has syntactic sugar (validators, etc.) but if you're willing to live without that you can just use the driver.

**Comment by kartojal** [comment]
Any news about this issue? Do you know another way of inserting (probably duplicated) documents in bulk without bypassing mongoose validation?

Thanks

**Comment by vkarpov15** [comment]
Not at the moment. For now I'd recommend doing `doc.validate()` before `MyModel.collection.insertMany()` if you need that.

**Comment by jaburcodes** [comment]
`UserModel.insertMany(rows, { ordered: false });`

is working here
