### ISSUE TITLE
mongoose 4.4.4 : Model.update can't really update data in mongodb

### ISSUE THREAD

**Issue by ausir0726** [Automattic/mongoose#3895]
When I update mongoose from 4.0.1 to 4.4.4
I use Model.update function , it's return ok : 1 , and modified : 1 , but when I check my data in mongodb , It's the old data .

now I downgrade to 4.0.8 , It's look like ok , I don't change any code .

mongod version: 2.6.9
mongoose version : 4.4.4
node version : 5.6

=== code ===
Sites.update({
_id : req.params.id 
}, { $set : { "data":"test" } } , function(err,sites){
console.log(sites);
});
=== return ===
{ ok: 1,
nModified: 1,
n: 1,
lastOp: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1455948558 },
electionId: 5622c579b576d605371043d3 }

**Comment by vkarpov15** [comment]
Hmm that's strange. Can you show your schema? Also, try enabling mongoose debug mode, `require('mongoose').set('debug', true);` to show the queries that mongoose is sending to mongodb. That will give us a better idea of whats going on.

**Comment by ausir0726** [comment]
thanks ,

when I open debug mode 

`
Mongoose: sites.update({ '$and': [ { 'permission.admin': { '$in': [ ObjectId("551b5fd43b91fb94ebe575bf") ] } } ], _id: ObjectId("551ca35b64a5979e7f5bc761") }) { '$set': { updatedAt: 1456191817322 } } {}
Mongoose: tokens.findAndModify({ _id: ObjectId("56cbb920d053b799709be5ae") }) [] { '$set': { lft: '1456191817' } } { new: false, upsert: false }
null { ok: 1,
  nModified: 1,
  n: 1,
  lastOp: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1456191817 },
  electionId: 5622c579b576d605371043d3 }
`

that's my model defined
`
'use strict';

var mongoose = require('mongoose'),
Schema = mongoose.Schema,
ObjectId = Schema.ObjectId ;

var attributes = {
  finpoadmin : { type : String },
  name : { type : String , required : true } ,
  keyword : { type : String } ,
  title : { type : String } ,
  desc : { type : String } ,
  customSidebar : { type : String } ,
  contactmail : { type : String },
  recaptcha_sitekey : { type : String } ,
  recaptcha_secretkey : { type : String } ,

  status : { type : String , required : true , default : "啟用" } ,
  permission : {
    admin : [{ type : Schema.Types.ObjectId , ref : 'Users' }] ,
    media : [{ type : Schema.Types.ObjectId , ref : 'Users' }] ,
    content : [{ type : Schema.Types.ObjectId , ref : 'Users' }] ,
    editor : [{ type : Schema.Types.ObjectId , ref : 'Users' }] ,
    visitor : [{ type : Schema.Types.ObjectId , ref : 'Users' }]
  } ,
  setting : {} ,
  creator : { type : Schema.Types.ObjectId , required : true , ref : 'Users' } ,
  category : { type : Schema.Types.ObjectId , ref : 'Categories' } ,


  createdAt : { type: Date , default: Date.now } ,
  updatedAt : { type: Date , default: Date.now }
};

var sitesSchema = new Schema(attributes , { strict: false } );

sitesSchema.pre('update', function(next){
  this._update = { '$set': { updatedAt : Date.now() } }
  next();
});

module.exports = mongoose.model('Sites', sitesSchema);
`

I'm sure I have correct data input and model.find condition

when I use 4.0.8 
`
Mongoose: sites.update({ _id: ObjectId("551ca35b64a5979e7f5bc761"), '$and': [ { 'permission.admin': { '$in': [ ObjectId("551b5fd43b91fb94ebe575bf") ] } } ] }) { '$set': { updatedAt: 1456192240500, title: '1111' } } {}
Mongoose: tokens.findAndModify({ _id: ObjectId("56cbb920d053b799709be5ae") }) [] { '$set': { lft: '1456192240' } } { new: false, upsert: false }
null { ok: 1,
  nModified: 1,
  n: 1,
  lastOp: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1456192240 },
  electionId: 5622c579b576d605371043d3 }
`

it's looks like I lost input data in mongoose .. 

thanks.

**Comment by vkarpov15** [comment]
```javascript
sitesSchema.pre('update', function(next){
  this._update = { '$set': { updatedAt : Date.now() } }
  next();
});
```

Is the offending code. Use `this.update({ updatedAt: Date.now() });` instead and it should work.
