### ISSUE TITLE
OSX: js-bson: Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by michalkrupa** [Automattic/mongoose#3898]
I believe I have found a common cause of the

``` console
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

error that occurs on OSX. The version of MongoDB (1.4.28) required by Mongoose (3.8.23) has BSON ~0.2.0 listed as its dependency. However, this version of BSON happens to reference NAN  ("nan": "~1.8"), an outdated release of the NAN library that does not support various casting, or otherwise references unavailable functions from the v8 header file included with the nodeJS installation and used by node-gyp during the build process of the BSON binary. 

Unfortunately, the dependencies are a bit complicated, as the bson module is now up to date and references the proper build libraries, however, it requires a new dependency called bson-ext, which based on the bson package.json, is optional. The bson/ext folder with the makefile that node-gyp takes to generate build configuration is no longer present in the bson module, since it is now part of bson-ext.

BSON changelog
``` console
0.3.0 2015-03-26
----------------
- Pulled out all C++ code into bson-ext and made it an optional dependency.

0.2.21 2015-03-21
-----------------
- Updated Nan to 1.7.0 to support io.js and node 0.12.0
```

Therefore, the build process for OSX has to be updated, so that the bson-ext package is included either as a dependency of the mongoose module, or as a dependency of the mongodb dependency included with the mongoose module. Then, build settings from the bson/binding.gyp file need to reference the bson-ext/bson.cc file from the new dependency location, rather than the location that was referenced for bson ~0.2. This also requires an update to the mongodb/node_modules/bson/ext/index.js file, so that the build/Release/bson directory points to the separate bson-ext module (or configure bson-ext module to output the release binary to the bson module Release folder. I believe the kerberos package also needs to reference an updated version of NAN, otherwise it too fails to build.

This issue occurs after node v0.12.X on OSX.

**Comment by vkarpov15** [comment]
Try upgrading to a more recent version of 3.8.x. Either way, this message is just a warning, should have no effect on your dev environment.
