### ISSUE TITLE
embedded array issue

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#3901]
Hi, this is the schema
```

var caseNoteSchema = mongoose.Schema({
    name:{type:String,required:true},
    type:{type:String},
    eu:[{euid:{type: ObjectId, ref: 'euLaw' },comment:String}],
});

```
this is the json data I want to save (this data are printed serverside)
```
{ name: 'test',
  type: '',
  'eu[0][euid]': '56c23745f724c288054f3d42',
  'eu[0][comment]': '342'}
```

but 'eu' is always empty in db. What am I doing wrong?

**Comment by alfredopacino** [comment]
I serialize my form using this https://github.com/macek/jquery-serialize-object

If I print clientside (before submit) the object I see
![ser](https://cloud.githubusercontent.com/assets/6325475/13205398/7bd65132-d8e7-11e5-8c90-440704672510.jpg)

I simply print in my post route the same object and I see "**eu[0][euid]**"

**Comment by vkarpov15** [comment]
I don't really understand what you're trying to do. Can you provide a more substantial code sample?

**Comment by alfredopacino** [comment]
I solved realizing it's not mongoose related. Thanks  :)
