### ISSUE TITLE
How to specify `--authenticationDatabase` in mongoose?

### ISSUE THREAD

**Issue by SamuelMarks** [Automattic/mongoose#3905]
Works in the shell:
```
$ mongo -u monguser -p mongpass 192.168.2.2/ps --authenticationDatabase=admin
MongoDB shell version: 3.2.3
connecting to: 192.168.2.2/ps
Server has startup warnings: 
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] 
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] 
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-02-23T01:59:10.522+0000 I CONTROL  [initandlisten] 
> db.foo.insert({can:'haz'})
WriteResult({ "nInserted" : 1 })
```

Fails in mongoose:
```
'use strict';

const mongoose = require('mongoose');

const uri = 'mongodb://monguser:mongpass@192.168.2.2:27017/ps'

console.log('mongoose.connect =', mongoose.connect(uri, (err) => {
    err && console.log('err =', err);
}));
```

```
// For `mongoose.connect` output, see: https://gist.github.com/SamuelMarks/dedd863742f90cf2f333
err = { [MongoError: Authentication failed.]
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  code: 18,
  errmsg: 'Authentication failed.' }
```

So it's save to assume that `authenticationDatabase` needs to be set somehow, maybe in the config parameter. *What's the syntax?*

**Comment by vkarpov15** [comment]
Easiest way is to specify `authSource` in the uri

`const uri = 'mongodb://monguser:mongpass@192.168.2.2:27017/ps?authSource=admin';`

**Comment by vkarpov15** [comment]
See [mongodb connection string docs](https://docs.mongodb.org/manual/reference/connection-string/#uri.authSource)

**Comment by SamuelMarks** [comment]
Thanks

**Comment by daveai** [comment]
My connection string like this

mongodb://root:pass@127.0.0.1:27017/ai?authSource=admin

Everything working good but getting a wired message at the shell.

Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

For what is this ?

**Comment by mhassanist** [comment]
@vkarpov15 you saved my day. Thanks a lot.

**Comment by ORESoftware** [comment]
Anybody know how to specifiy authsource when using mongodump command? :]

**Comment by vkarpov15** [comment]
@ORESoftware mongodump calls it `authenticationDatabase`: https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-authenticationdatabase

**Comment by leonprou** [comment]
```
Easiest way is to specify authSource in the uri

const uri = 'mongodb://monguser:mongpass@192.168.2.2:27017/ps?authSource=admin';
```
@vkarpov15 this is working, but before I tried to pass the authSource from `options` object. using:

```
    options: {
      ...
      authSource: 'admin'
    }
```

looking at the api of mongodb - http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html, and the source of mongoose that should work

**Comment by liudonghua123** [comment]
If `/defaultauthdb` and `?authSource=admin` both specified, then `/defaultauthdb` will be the database you tried to connect?

For `const uri = 'mongodb://monguser:mongpass@192.168.2.2:27017/ps?authSource=admin';`, the database connected is `ps`.

https://www.mongodb.com/docs/manual/reference/connection-string/#components
