### ISSUE TITLE
timestamps don't work with schema.set(option, value)

### ISSUE THREAD

**Issue by btknorr** [Automattic/mongoose#3907]
If you create a schema
``` var schema = new Schema({...});```
And then use set to turn on timestamps
```schema.set('timestamps', true);```
The fields createdAt and updatedAt are never saved with the model.

I looked at the code and it seems timestamps can only be enabled in the constructor of Schema.  Why is this?

Thanks,

Brian

**Comment by fiws** [comment]
+1

**Comment by vkarpov15** [comment]
Closed in #3952
