### ISSUE TITLE
very strange bug when trying to save new model

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#3911]
I have this simple model, with a string property on the model that is causing disproportionate trouble

```js

         var post = new Post({
                posterId: user._id,
                picture: {},
                content: [],
                url: 'foo',  // <<<< if I omit this it works
                string: body.string
            });

            post.save(function(err){
              /// callback doesn't even fire when url is defined in the post constructor
            });
```

my schema looks like:

```js
    url: {
        type: String,
        required: false
    },
```

this is consistent behavior and has been happening over a few days

what could possibly be going on?

thanks

**Comment by ORESoftware** [comment]
there might be some index in the database that prevents the insert, but *still* why wouldn't the callback fire the error? the callback never fires

**Comment by ORESoftware** [comment]
but there is no index on that property ('url')

as you can see

https://www.dropbox.com/s/lk1yuzmgh55efq7/Screenshot%202016-02-23%2021.19.43.png?dl=0

**Comment by ORESoftware** [comment]
ok I tried Model.create

```js
 Post.create({
                posterId: user._id,
                picture: {},
                content: [],
                url: body.url,
                string: body.string
            }, function (err, models) {
                if (err) {
                    log.error(err);
                }
                else if (models.length > 0) {
                    log.debug('new post model:', models[0]);
                }

                cb(null);
            });
```

and I got the same exact problem, callback never fires

hope that's a clue, sure seems like a bug (for the callback to never fire, at the very least)

thanks

**Comment by vkarpov15** [comment]
Hmm are you setting a custom promise library?

**Comment by ORESoftware** [comment]
I don't think so, I think we are only using native promises in our code,
but I would be have to check to see if our dependencies might use some
other promise library - is there something in particular to look out for?
problem still exists for us

**Comment by ORESoftware** [comment]
btw I checked the content of db.system.js and it is empty so I dont think
its related to functions in the db

**Comment by vkarpov15** [comment]
Sorry, my original question wasn't sufficiently clear. [Are you setting `require('mongoose').Promise` as specified in the docs](http://mongoosejs.com/docs/promises.html)?

**Comment by ORESoftware** [comment]
Thanks, no we aren't making that call

**Comment by ORESoftware** [comment]
So I guess your hypothesis might be that it thinks we are using promises and that's why the callback never fires?

**Comment by ORESoftware** [comment]
I tried promises, same exact problem

```js

   post = new Post({
                posterId: user._id,
                picture: {},
                summary: summary,
                url: postUrl,  // << this is causing the problem
                string: body.string
            });

            post.save().then(function(result) {
                cb(null);
            }, function rejected(err) {
                log.error(err);
                cb({ msg: 'Error saving post', error: err.stack });

            }).catch(function(err) {
                log.error(err);
            });

```

are there any database schema validation structures that we can delete drop to eliminate variables?

again, the problem is that the callbacks (in CPS or promises) never fire

**Comment by ORESoftware** [comment]
OK we figured it out, definitely some sort of bug I think

the property "url" on a mongoose model schema seems to be reserved somehow

we did everything - dropped the database and reinstalled mongo and the problem remained

...then we changed the property "url" to "postUrl" and "link" and both worked

there seems to be a problem with mongodb/mongoose with a property called "url", can you verify this?

thanks

**Comment by ORESoftware** [comment]
just to be clear, it was clear to me that this was a bug because the callback never fired!

**Comment by vkarpov15** [comment]
@ORESoftware the below script works for me without error:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gh3911');
mongoose.set('debug', true);

var Schema = mongoose.Schema;

var postSchema = new Schema({ url: { type: String, required: true } });

var Post = mongoose.model('Post', postSchema);

var post = new Post({
                url: 'foo'  // <<<< if I omit this it works
            });

            post.save(function(err){
              /// callback doesn't even fire when url is defined in the post constructor
              assert.ifError(err);
              process.exit(0);
            });
```

You mentioned that you're using CPS - can you modify the above sample to more closely match your architecture?

**Comment by vkarpov15** [comment]
Issue's been stale for a while, closing. Re-open if this is still an issue.

**Comment by ORESoftware** [comment]
Yeah we simply fixed the problem by changing our model property from url to postUrl or whatever. Like I said we dropped the db and started clean and the problem still remained. Very strange, would love to know what it was about, definitely let me know if you figure it out anytime thanks.
