### ISSUE TITLE
string to ObjectId

### ISSUE THREAD

**Issue by nikkwong** [Automattic/mongoose#3912]
I have a string that references an ObjectId, that I would like to store in the DB as an actual ObjectId (not just a string). Can this be achieved? There is nothing obvious in the docs. 

Thanks.

**Comment by btknorr** [comment]
Would you mind clarifying your issue with a small example?  Maybe include an example Schema.

**Comment by nikkwong** [comment]
Closing as it's better to probably just reference the ObjectId's string representation when storing objects into the datastore:

For example:

This

````
{_id: ObjectId("4edd40c86762e0fb12000003"), 
 type: 'comment',
 belongsTo: "36t4ec86762e0fb53285390", 
 ...
As opposed to this: 
````
{_id: ObjectId("4edd40c86762e0fb12000003"), 
 type: 'comment',
 belongsTo: ObjectId("36t4ec86762e0fb53285390"), 
 ...

**Comment by vkarpov15** [comment]
You can always declare `belongsTo` in your schema as having type ObjectId, and mongoose will cast it for you.
