### ISSUE TITLE
Required Single Embedded Subdoc

### ISSUE THREAD

**Issue by domharrington** [Automattic/mongoose#3913]
As of 4.2.0 you can provide a single embedded subdoc: http://mongoosejs.com/docs/subdocs.html#single-embedded

From docs:
```js
var childSchema = new Schema({ name: 'string' });

var parentSchema = new Schema({
  child: childSchema
});
```

Is there any way to make `childSchema` (and the properties within) required when validating the parent?
```js
var mongoose = require('mongoose');

var childSchema = mongoose.Schema({ name: { type: String, required: true } })
var parentSchema = mongoose.Schema({
  child: childSchema
})

var Parent = mongoose.model('Parent', parentSchema)
var instance = new Parent();

instance.validate(err => {
  console.log(err); // No errors
})

instance.child = {}

instance.validate(err => {
  console.log(err.errors); // 'Path `name` is required.'
})
```

The child schema errors are only displayed when the property on the parent is not undefined. Is this intentional? Is there a recommended way around this?

Thanks in advance.

**Comment by btknorr** [comment]
In our app if we want to include validation on a child schema we just create the parent with a reference to the child as {}.

```new Parent({child:{}})```

We actually like that it works this way...allows us to create reusable schemas that the application can wire up as optional child schemas on a parent schema.

**Comment by domharrington** [comment]
I've resorted to doing something very similar, but I was wondering if there is a way to do it natively.

**Comment by btknorr** [comment]
Gotcha...then I believe you can just do this:

```
var ParentSchema = new Schema({
    child: {
        type: childSchema,
        required: true
    }
});
```

**Comment by domharrington** [comment]
Ahhh yes that works. Thank you very much! Full example for anyone viewing this in future:

```js
var mongoose = require('mongoose');

var childSchema = mongoose.Schema({ name: { type: String, required: true } })
var parentSchema = mongoose.Schema({
  child: { required: true, type: childSchema }
})

var Parent = mongoose.model('Parent', parentSchema)
var instance = new Parent();

instance.validate(err => {
  console.log(err);
})
```

Thanks again.

**Comment by domharrington** [comment]
This does not work in v4.2.4. I've upgraded to the latest version (v4.4.5 at time of writing) and it seems to be working as expected.

**Comment by vkarpov15** [comment]
Glad you figured it out. Admittedly this is a little strange with how the rest of mongoose currently works - `required: true` means the top-level document validation will always fail, unless that `required: true` is in a child schema. I added an issue to clarify this in documentation.

**Comment by domharrington** [comment]
Thank you! Very much appreciated.
