### ISSUE TITLE
Applying sort to a count query fails

### ISSUE THREAD

**Issue by sabrehagen** [Automattic/mongoose#3914]
To generate my queries I chain on options, for example:

```
const query = model.find(criteria);
if (data.select) {
    query.select(data.select);
}
if (data.sort) {
    query.sort(data.sort);
}
return query;
```

Now I want to add an option for `count` in my query builder, for example:

```
const query = data.count ? model.count(criteria) : model.find(criteria);
if (data.select) {
    query.select(data.select);
}
if (data.sort) {
    query.sort(data.sort);
}
return query;
```

However, when applying a `.sort()` to a `.count()` query, no result is returned. Given that sorting has no influence on the number of matching documents, it should be ignored at the very least, certainly it shouldn't cause the query to return `undefined` as it currently does.

Furthermore, as an aside to this issue, mongoose baulks if you supply a `.select()` to a `.count()` with the error `Unhandled rejection Error: select cannot be used with count`. Given that select doesn't influence count either, I propose it should silently fail. Thoughts?

Here's code to demonstrate the issue:

```
const mongoose = require('mongoose');
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/sort-count');

const s = mongoose.Schema({
  v: { type: String, default: 'mongoose' }
});

const model = mongoose.model('s', s);

model.create({}, () => {
    model.create({}, () => {
        model.create({}, () => {
            model.count({}).exec((err, n) => console.log(err, n));          // works
            model.count({}).sort().exec((err, n) => console.log(err, n));   // fails
        });
    });
});
```

**Comment by vkarpov15** [comment]
Thanks for reporting. What version of mongoose are you using? Please tell me you upgraded from 3.8.x :)

**Comment by sabrehagen** [comment]
Yes, this is with 4.3.6.

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/cee754580d1bac45292b9e0c967ecb7d9809a705

**Comment by sabrehagen** [comment]
Cool, thanks. That deals with the sort issue, what's the decision on the select issue?

**Comment by vkarpov15** [comment]
No the above commits allow you to do both, see 139a90b

**Comment by sabrehagen** [comment]
Great, thank you.
