### ISSUE TITLE
mongoose continuing connect to statup slaves cause high cpuload

### ISSUE THREAD

**Issue by rrfeng** [Automattic/mongoose#3916]
I have a mongodb repl cluster with 1 primary and 3 secondary. And when I rs.add() one more mongodb secondary member, the new mongod start to rsync from primary. 
The mongoose application will couse high cpuload at that time.

The mongod's log shows that many clients connect and reconnect to this new mongod, I think this is the reason.

Because the initial sync member will stay in STARTUP2 status, and this may remain in a long time. should the mongoose always reconnecting to the member which is in STARTUP2 status?

**Comment by vkarpov15** [comment]
As far as mongoose is concerned, that's expected behavior - the [mongodb driver](https://github.com/mongodb/node-mongodb-native) handles all the repl set state logic. Does the increased cpu load cause problems for your application?

**Comment by rrfeng** [comment]
@vkarpov15 I run some consumers for a RabbitMQ on a 16core VM, and one process per consumer using cfork. There was  about 50 processes connected the mongodb repl set. And average cpu usage was lower than 5%. When that happend, the cpu usage came up to 60%-100% at the beginning  5min, and then stable at 30%. 
I think the `reconnect` method can be more intelligent.

thanks.

**Comment by vkarpov15** [comment]
You can report an issue on the [mongodb node jira](https://jira.mongodb.org/browse/NODE) - that's the place to report this sort of issue. Sorry to kick the can down the road but repl set state management is way outside the scope of mongoose.
