### ISSUE TITLE
validation in setter

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#3918]
here is a test case

```js
var start = require('./common'),
    assert = require('power-assert'),
    mongoose = start.mongoose,
    Schema = mongoose.Schema;

describe('should validate an array', function() {
  it('if an embedded doc', function(done) {
    var db = start();

    var TestSchema = new Schema({
      date: {
        type: Date,
        set: function(date) {
          this.invalidate('date', 'invalid date', date);
          return date;
        },
        get: function(date) {
          return date;
        }
      }
    }, {versionKey: false});

    var Test = db.model('Test', TestSchema);

    var test = new Test();
    test.date = new Date();

    test.save(function(err, test) {
      console.log(err, test);
      assert.ok(err);
      done();
    });
  });
});
```

in `set` function `this` refers to `mongoose.Document` and `invalidate` is present but doesn't mark `date` field as invalid

looks like a bug to me

**Comment by TrejGun** [comment]
ok i have found a reason for this
https://github.com/Automattic/mongoose/blob/4.4/lib/document.js#L640
related bug #2766

not sure how to deal with this

**Comment by TrejGun** [comment]
@vkarpov15  can you please point me where to start?

**Comment by vkarpov15** [comment]
@TrejGun expected behavior. If `set()` succeeds, mongoose will [mark the path as valid](https://github.com/Automattic/mongoose/blob/cee754580d1bac45292b9e0c967ecb7d9809a705/lib/document.js#L671). I can't really think of any way to work around this while still supporting the behavior that if you set a field that has a validation error to something valid the error goes away. You can `invalidate()` other fields in a setter, but the correct way to make a setter fail is to `throw`:

```javascript
describe('should validate an array', function() {
  it('if an embedded doc (gh-3918)', function(done) {
    var db = start();

    var TestSchema = new Schema({
      date: {
        type: Date,
        set: function(date) {
          throw 'invalid date';
        },
        get: function(date) {
          return date;
        }
      }
    }, {versionKey: false});

    var Test = db.model('Test', TestSchema);

    var test = new Test();
    test.date = new Date();

    test.save(function(err, test) {
      console.log(err, test);
      assert.ok(err);
      done();
    });
  });
});
```

**Comment by TrejGun** [comment]
thanks! this works
i tried this before but was confused about error message
it appears to be in `reason` rather than in `message` property

**Comment by vkarpov15** [comment]
Yeah the general idea is that reason contains the reason for the casterror, which may be a user generated error or not
