### ISSUE TITLE
Connection pooling changed?

### ISSUE THREAD

**Issue by synthmeat** [Automattic/mongoose#3920]
Up until recently, I've always had mongoose create poolSize connections (default 5) to mongod, but ever since the recent infrastructure update I had, mongod logs a single connection created, no matter what poolSize I set (or if I set it at all).

For connection code:

```javascript
mongoose.connect(
	process.env.MONGO_HOST + ':' +
	process.env.MONGO_PORT + '/' +
	process.env.MONGO_DATABASE,
	{
		server: { poolSize: 3 },
		socketOptions: { keepAlive: 120, connectTimeoutMS: 30000 }
	};
);
```

I get logged only:

```2016-02-27T12:00:56.130+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60797 #1 (1 connection now open)```

Same thing for just:
```javascript
mongoose.connect(
	process.env.MONGO_HOST + ':' +
	process.env.MONGO_PORT + '/' +
	process.env.MONGO_DATABASE
);
```

Is this change related to mongoose?

**Comment by synthmeat** [comment]
For posterity, apparently, it's just behaving differently than before. Now it's creating connections as needed later on, not on start.

**Comment by vkarpov15** [comment]
For posterity, the change is in the [mongodb driver](https://github.com/mongodb/node-mongodb-native), mongoose doesn't do any connection pool management on its own.
