### ISSUE TITLE
Is it correct to validate fields in the following way?

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#3924]
I need to check required fields but with some cases. I'm trying the following:

    var PostSchema = mongoose.Schema({});

    PostSchema.pre('validate', function (next) {
        var error = new ValidationError(this);

        if (this.type === 'question' && !Array.isArray(this.tags)) {
            error.errors.tags = new ValidatorError({message: 'Tags field is required', type: 'required', path: 'tags'});
        }

        if (!Object.keys(error.errors).length) {
           return next();
        } else {
           return next(error);   
        }
    });

Is it correct to make validation the approach above and don't it break mongoose in a future?

**Comment by vkarpov15** [comment]
Seems reasonably correct - just be very very careful with [schema fields named 'type'](http://mongoosejs.com/docs/guide.html#typeKey). However, the above approach unfortunately won't work if you want to use `validateSync()`. Might be easier to use the function form of `required`:

```javascript
var postSchema = new Schema({
  kind: String,
  tags: {
    type: Array,
    required: function() { return this.kind === 'question' }
  }
});
```

**Comment by skotchio** [comment]
@vkarpov15 what's wrong with `type`? Should I use `kind` instead `type` for post type?

**Comment by vkarpov15** [comment]
Because the type key is what mongoose uses to determine the type of the field, so generally having fields named type is a bad idea
