### ISSUE TITLE
Mongoose failed to failed to build cert chain 

### ISSUE THREAD

**Issue by PradeepVishnu** [Automattic/mongoose#3929]
Hi,

I had a setup mongo db with SSL decorated with domain certs (domain cert->sub ca cert -> ca cert). But it seems failed to verify using node modules. Please let me know is there any thing missing ? 

```javascript
   var sslDomainCert = fs.readFileSync(config.db.sslServer.sslDomainCert);
    var options = {
        server: {
            sslValidate:true,
            sslCert: sslDomainCert
        },
        user: config.db.sslServer.user,
        pass: config.db.sslServer.pass
    };
    mongoose.connect(config.db.sslServer.mongodb, options);
```

But its failed with validating peer certificate with error below - 

```
/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
                                      ^
Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1003:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:570:8)
```

On otherside , we have connected successfully connected mongo with below command using same cert :+1: 
mongo -u user -pPass  MongoDbHost/admin --ssl -sslCAFile  sslDomainCert

Also above command failed once we broke the chain to single cert with below error (which is great and was expected )
SSL peer certificate validation failed: unable to verify the first certificate 

SSLDomainCert - Pem encoded file with all certs on the chain (domain,subCA,CA)

I appreciate any reply.

Thanks

**Comment by vkarpov15** [comment]
Does it work if you set `sslValidate` to false? Also, can you clarify which mongoose version you're using , what version of mongodb, and if you're connecting to a standalone mongodb server or replica set or mongos?

**Comment by PradeepVishnu** [comment]
Valeri,

It works when sslvalidate:false . We have specified 4.4.5 ( "mongoose":
">=4.4.5" )

I believe the mongodb is ssl enabled standalone version.

Thanks
Pradeep

**Comment by PradeepVishnu** [comment]
Valeri,

Db version is returned 3.0.8

Thanks
Pradeep

**Comment by vkarpov15** [comment]
Sslvalidate enables stricter validation of the ssl cert, I don't remember the details off the top of my head. Can you double check to make sure your certificate is not expired?

**Comment by alph486** [comment]
I am also experiencing this using Mongoose.js version 4.4.6 and server version 3.2.1. I am not using the `options` object though. I'm using a connect string thusly:

```
mongodb://user:pass@server:port/mydb?ssl=true&authMechanism=SCRAM-SHA-1&sslValidate=false
```

Error I get is:
```
error:  Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1057:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:596:8)
```
