### ISSUE TITLE
Index ignored after update fields

### ISSUE THREAD

**Issue by thebergamo** [Automattic/mongoose#3930]
I create a compound index in my model. 

```javascript
companyCitySchema.index({ company: 1, city: 1, state: 1, country: 1 }, { unique: true });
```

When I update the model city property and I try create a new document with the same city, state, country and company the information equal the updated one, the index are not respected. 

I need to using another settings?

`"mongoose": "^4.1.0"`

**Comment by vkarpov15** [comment]
Turn on the [emitIndex errors option](http://mongoosejs.com/docs/guide.html#emitIndexErrors) on your schema and see if you get any errors. I suspect your index build is failing for some reason.

**Comment by thebergamo** [comment]
@vkarpov15 well, I'm not sure, but just restart my mongod the problem solved O.o
