### ISSUE TITLE
Don't return promise if callback specified

### ISSUE THREAD

**Issue by artzstudio** [Automattic/mongoose#3931]
Hello, I'm the author of [meanify](https://github.com/artzstudio/meanify), a library that uses Mongoose to cleverly generate API routes.  

One of my users is bumping into an issue where he is seeing console.error output because I use callbacks to deal with Mongoose errors.  

Bluebird appears to expect an explicit catch statement, forcing one to prefer one style to another i.e. promises vs callbacks upon installation.

Consider the following code:

``` javascript
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');

var User = mongoose.model('User', new mongoose.Schema({
    name: { type: String, required: true },
}));

var user = new User();
user.save(function (err, doc) {
  if (err) {
    // error handled in the callback
    console.error('Error:', err.message);
  } else {
    console.log('Success:', doc);
  }
});
```

Results in this console output:

``` bash
Error: User validation failed
Unhandled rejection ValidationError: User validation failed
    at MongooseError.ValidationError (/Users/artz/Sites/meanify/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/Users/artz/Sites/meanify/node_modules/mongoose/lib/document.js:1298:32)
    at /Users/artz/Sites/meanify/node_modules/mongoose/lib/document.js:1173:16
    at validate (/Users/artz/Sites/meanify/node_modules/mongoose/lib/schematype.js:662:7)
    at /Users/artz/Sites/meanify/node_modules/mongoose/lib/schematype.js:693:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Users/artz/Sites/meanify/node_modules/mongoose/lib/schematype.js:667:19)
    at /Users/artz/Sites/meanify/node_modules/mongoose/lib/document.js:1171:9
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3
```

My only solution to avoid this error for my users using Bluebird appears to be refactoring `meanify` to use promises so there's no error output.  Any advice would be much appreciated.  

Thanks!

**Comment by vkarpov15** [comment]
Right now mongoose always returns a promise, even if you specify a callback. I'd love to change this for a future release. However, not happening anytime soon because we've got more pressing issues. Here's a couple alternatives:

1) Don't use bluebird. IMO it's a bloated mess that's more trouble than it's worth
2) Use `.catch()` with an empty function

```javascript
user.save(function (err, doc) {
  if (err) {
    // error handled in the callback
    console.error('Error:', err.message);
  } else {
    console.log('Success:', doc);
  }
}).catch(function() {});
```

**Comment by artz** [comment]
Thanks for the workaround, that'll do for now.

**Comment by niftylettuce** [comment]
Related #4364

**Comment by zbjornson** [comment]
@vkarpov15 I'm confused about the current state of this issue. In 15e271a I think you fixed unhandled rejections when using cbs and bluebird for queries. In e27430f, the same for `save()`. #4269 and this issue seem similar and are open...

To the point: we have this issue with `model.insertMany` using `global.Promise` (not bluebird) with a `process.on("unhandledRejection")` listener. Is this something I should open a new issue for? Thanks in advance.

**Comment by vkarpov15** [comment]
Yes please open a new issue with some code samples @zbjornson . The commits you referenced aren't quite related to this issue and #4269 because those commits fixed bluebird warnings that are internal to mongoose (internal functions returning promises while we use callbacks internally), whereas this issue is about making a user-facing API change.

**Comment by vkarpov15** [comment]
Closing this in favor of #3670, follow that issue for updates. Still planning on changing this for 5.0.
