### ISSUE TITLE
Required fields dose not validate

### ISSUE THREAD

**Issue by rrNuvoPoint** [Automattic/mongoose#3932]
I am using this schema

```
var OAuthUsersSchema = new mongoose.Schema({
    username: { type: String, required: true },
    password: { type: String, required: true },
    email: { type: String, unique: true, required: true }
});

OAuthUsersSchema.pre('update', function() {
  this.options.runValidators = true;
});

mongoose.model('OAuthUsers', OAuthUsersSchema);

OAuthUsersModel = mongoose.model('OAuthUsers');
```

I basically want to make sure that all fields are filled out. But No validation is happening when i do:

```
OAuthUsersModel.update(
                {_id: new mongoose.Types.ObjectId() }, 
                {$set: {username: 'eoop'}},
                 {upsert: true}, 
                 function(err,doc){
                res.send({err: err, doc: doc});
            });

```
A new document is successfully upserted the first time. The second time it fails of course because of index problems. I am using version 4.3.7.

**Comment by vkarpov15** [comment]
Update validators are somewhat limited in that if you don't specify the field in the update, mongoose won't validate that field. In the above example, mongoose won't run validation on the password field, because mongoose doesn't know if the document being updated has a password field or not.
