### ISSUE TITLE
updateOne(filter, update, { timestamps: { createdAt: false, updatedAt: true } })

### ISSUE THREAD

**Issue by antony** [Automattic/mongoose#3934]
Rather than raise two feature requests I'll just add this one with a minor but important extension to the timestamps functionality.
1. I'd love to be able to say {timestamps: false} in a create, update, etc. statement.

The reasoning for this is that when writing tests, I have to drop to the native driver to override auto-time-stamping, which just makes things messy. I want to create a variety of documents in a variety of created/updated periods.
1. I'd like to be able to turn 'createdAt' off, and just have 'updatedAt'

Reasoning for this is that we're growing our developers team fast. I wrote the system using ObjectID's created functionality, but I really need updatedAt functionality too. Having two ways to get the created time is going to cause problems, as using createdAt is the obvious one, but using native ObjectID (in my opinion) is the correct one.

**Comment by seriousManual** [comment]
> The reasoning for this is that when writing tests, I have to drop to the native driver to override auto-time-stamping, which just makes things messy. I want to create a variety of documents in a variety of created/updated periods.
When I understand you correctly you have the issue that it is not possible to specify which date is set via the autotimestamping mechanism?
I like to use [sinon fake timers](http://sinonjs.org/docs/#clock) for exactly this:

````javascript
    var clock = sinon.useFakeTimers() //resets the clock to 1979/01/01

    var testSchema = new mongoose.Schema({ foo: String });
    var TestModel = mongoose.model('test', testSchema);

    var firstTestInstance = new TestModel({foo: 'bar'})
    clock.tick(3600000) //moves the clock forward by 1h
    var secondTestInstance = new TestModel({foo: 'bax'})

    async.parallel([
        cb => firstTestInstance.save(cb),
        cb => secondTestInstance.save(cb)
    ], _ => {
        TestModel.find({}, (error, result) => console.log(result))
    })
````

Result would be:
````
[ { __v: 0, foo: 'bar', _id: 0000000035960fa409c1f17c },
  { __v: 0, foo: 'bax', _id: 00000e1035960fa409c1f17d } ]
````
Notice how the ObjectID differ albeit having been constructed at nearly the same point in time?

**Comment by vkarpov15** [comment]
We already have support for most of these suggestions as of Mongoose 5.6. For example, you can skip timestamps on an individual update using `Model.updateOne(filter, update, { timestamps: false })`. See [`updateOne()` docs](https://mongoosejs.com/docs/api/model.html#model_Model.updateOne). We also support turning off `updatedAt` at the schema level as shown in the [schema timestamps docs](https://mongoosejs.com/docs/guide.html#timestamps). However, we don't quite support shutting off just `updatedAt` or just `createdAt` on an individual update, which we should.
