### ISSUE TITLE
Make `_id: false` disable `id` virtual as well

### ISSUE THREAD

**Issue by nschloe** [Automattic/mongoose#3936]
To disable the generation of an `_id` for a schema, I'm using

``` js
_id: false,
firstName: String,
lastName: String,
```

When inspecting a document of this schema, one gets

``` js
> console.log(doc);
  Object { firstName: 'karl', lastName: 'hungus' }
```

But

``` js
> console.log(doc._id);
  null
```

and

``` js
> console.log(doc.toJSON({virtuals: true}));
  Object { id: null, firstName: 'karl', lastName: 'hungus' }
```

Apparently, `_id` has somehow been transformed into a virtual field.

This makes it impossible to an actual virtual field (e.g., `fullName`), have it transformed to JSON and _not_ include `id`.

**Comment by vkarpov15** [comment]
Set the id option on your schema to false, not just _id. By default, mongoose gives each doc an id virtual that gets the _id as a string

**Comment by nschloe** [comment]
Thanks, that does the trick!

**Comment by adamreisnz** [comment]
Sorry for resurrecting this @vkarpov15 , but I think this is somewhat confusing behaviour.
If we disable `_id` for a schema, then `id` will always be null anyway. So why is it not disabled by default when `_id` is disabled?

Now we have to (quite redundantly) specify both `_id: false` and `id: false` to avoid these ID's from showing up when generating JSON which isn't minimized.

**Comment by vkarpov15** [comment]
@adamreisnz that's a fair point, we'll change that for our next backwards breaking change

**Comment by vkarpov15** [comment]
Fixed but in hindsight I want to undo the refactor I did to move `idGetter` from being a plugin to being a helper. It's better off as a plugin because you may do something like `const schema = new Schema({}, { _id: false }); schema.add({ _id: Number });`. If `idGetter` isn't a plugin, it won't get added in the latter case.
