### ISSUE TITLE
Populate return null on nested path, take 2

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#3937]
Re: https://github.com/Automattic/mongoose/issues/3859#issuecomment-190541373

**Comment by vkarpov15** [comment]
@Jeff-Lewis this is expected behavior, we've got tests in place for this: https://github.com/Automattic/mongoose/blob/157b0f0f0a71d6f98a6a3033a13c9cf68b012ba3/test/model.populate.test.js#L1463 . Any change in this behavior would be backwards breaking. Also, taking a closer look at it, I think the current behavior makes more sense: if you `populate()` on a field that's undefined in the doc, you get back undefined. If you `populate()` on a field that exists but get back no results, you get back null. What do you think?

**Comment by Jeff-Lewis** [comment]
Yeah, I saw later that it's working as designed. It just wasn't intuitive to me that the id would change to null, even when the id is in the saved doc.

I don't know what the original use case was of preferring the id to be set to null so I can't weigh in on what's better. 

For my use case, we are importing a lot of related data and sometimes the ref gets saved before the child doc. Is there an alternate way to check a document for the pre-populated id on a populated property? I assume the Document object keeps the pre-populated id somewhere?

It would be great to have a config option to control this behavior but would that be overkill on the number config options? 

As a side note, I think we should explore alternate strategies in v5 or v6 of Mongoose on how Mongoose replaces the ObjectID properties with Documents when populated. Something along the lines of [mongoose-fill](https://github.com/whitecolor/mongoose-fill) and [mongoose-populate-virtuals](https://github.com/alexmingoia/mongoose-populate-virtuals).

**Comment by vkarpov15** [comment]
Re: mongoose-fill and mongoose-populate-virtuals, I agree that's the right way going forward. The fact that populate modifies the actual document is a big source of confusion. We plan on supporting something along the lines of those plugins in core in 4.5 or 4.6, and possibly deprecating the current notion of populate.

Can you clarify what you mean by "Is there an alternate way to check a document for the pre-populated id on a populated property?".

Re: prepopulated id, use [doc.populated(path)](http://mongoosejs.com/docs/api.html#document_Document-populated)

**Comment by Jeff-Lewis** [comment]
@vkarpov15 Is it possible to do the opposite? Can we get the original Document Object that was casted to an ObjectID when setting a path/property ref? 

Rough example...
``` javascript
var carMakerSchema = new Schema({
  name: {type: String}
});
var carSchema = new Schema({
   year: {type: Number},
   maker: {type: ObjectID, ref: 'CarMaker' }
});
var CarMaker = mongoose.model('CarMaker', carMakerSchema);
var Car = mongoose.model('Car', carSchema);

var carMaker = new CarMaker({ name: 'Ford' });
var someCar = new Car({ year: 2016 });
someCar.maker = carMaker;
```
Now `someCar.maker` is an ObjectID. How can we get the original **new** instance of the `carMaker` Document from the `someCar` model?  `someCar.casted('maker')`?

I guess the difference in what we're trying to do is attach `carMaker` to `car` before the `carMaker` model is saved. This is critical in doing any type of n-depth pojo hydration and recursive saving that we're working on as a plugin, which I would love your feedback on when it's worth looking at.

**Comment by vkarpov15** [comment]
No way to do that at the moment unless you attach carMaker to the doc in a field that's not in the schema, like doc.originalCarMaker = carMaker.
