### ISSUE TITLE
[Proposal] Separate ValidationError and ValidatorError from core

### ISSUE THREAD

**Issue by perrin4869** [Automattic/mongoose#3939]
Inside my current project I'm using both redis and mongodb, and have models built against these two backends. The thing is, that when it comes to custom redis-based models, the validation errors are thrown with my own custom error objects, while mongoose based models throw mongoose's own instances of `ValidationError` and `ValidatorError`. I was thinking that it would be great if the validation error objects were factored out of the core mongoose repository and made into its own separate project, so that third party libraries or other custom code can use the objects independently of mongoose. For your consideration!

**Comment by vkarpov15** [comment]
IMO this isn't a high priority since mongoose already exports these classes as 'mongoose.Error.ValidationError' and these classes are not sufficiently useful to be used independent of mongoose

**Comment by perrin4869** [comment]
Hi, I agree it's noto a high priority, but I still think that, even though they are rather simple classes with no complex functionality, they are very well built semantically, and therefore they can be very useful to set a standard. Also, this wouldn't represent a breaking change as far as I can see. Maybe a consideration for a next major release?

**Comment by vkarpov15** [comment]
Fair point. Let's do it :)
