### ISSUE TITLE
Mongoose.Schema.Types is undefined in v4.4.5 and up

### ISSUE THREAD

**Issue by creynders** [Automattic/mongoose#3940]
Hi, I think the wrapping of the mongoose singleton with a thenable on https://github.com/Automattic/mongoose/blob/master/lib/index.js#L295 causes Mongoose.Schema.Types to be `undefined`. Since `Schema` is a function it gets wrapped within a function here https://github.com/Automattic/mongoose/blob/master/lib/index.js#L60 which means none of it's static properties are directly accessible anymore.

**Comment by vkarpov15** [comment]
Sorry about that, will fix early next week

**Comment by creynders** [comment]
:ok_hand:
