### ISSUE TITLE
mongoose readPreference in options object?

### ISSUE THREAD

**Issue by aschmid** [Automattic/mongoose#3941]
hi,

right now i am connecting to mongodb like this:

```
uri = 'mongodb://mongodomain1.com:1234,mongodomain2.com:1234/mydb?replicaSet=replicasetname&readPreference=secondaryPreferred';

opts = {
  user: 'myuser',
  pass: 'mypass',
  server: {
    auto_reconnect: true,
    socketOptions: {
      keepAlive: 120
    }
  },
  replset: {
    socketOptions: {
      keepAlive: 120
    }
  }
};

mongoose.connect(uri, opts);
```

now i would like to bring the `readPreference` url parameter into the options object to be consitent and have all connection variables in the options.
i am struggling to find documentation on how to define the readPreference in the object.
same thing the `replicaSet` parameter in the url. is that equivalent to the `rs_name`

is there anything else i could/should improve in the way i am connecting to mongodb?

**Comment by vkarpov15** [comment]
@aschmid 

```javascript
opts = {
  user: 'myuser',
  pass: 'mypass',
  db: {
    readPreference: 'secondaryPreferred'
  },
  server: {
    auto_reconnect: true,
    socketOptions: {
      keepAlive: 120
    }
  },
  replset: {
    socketOptions: {
      keepAlive: 120
    }
  }
};
```

Docs about that will be more clear once we release 4.4.8. Correct place to check these options is in the [mongodb driver docs](http://mongodb.github.io/node-mongodb-native/2.1/api/Db.html). Mongoose helps you out if you use the connection string form, but if you want to use the options form, you should dig into the mongodb driver docs and check whether you need to set the option on `db`, `server`, `replset`, or `mongos`.
