### ISSUE TITLE
Model.aggregate.then is not a function

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#3946]
It seems the `aggregate` method on models is not thenable, is this intentional or an accidental omission?

**Comment by vkarpov15** [comment]
Intentional. Use the .exec() function. We'll add a .then() that does this for you in a future release

**Comment by adambuczynski** [comment]
Ok that'd be great. I use the promises interface for all other Mongoose operations, so would be good if it can be consistent with aggregate as well. Thanks!

**Comment by TrejGun** [comment]
+1
