### ISSUE TITLE
Empty subdocs does not override current value

### ISSUE THREAD

**Issue by yamifr07** [Automattic/mongoose#3948]
I have, for example, the following object:

```
{
    a: 1,
    b: {
       c:  2,
       d:  {
           e: 3,
           f: 4,
        }
    }
}
```

And I set e and f to undefined:

```
{
    a: 1,
    b: {
       c:  2,
       d:  {
           e: undefined,
           f: undefined,
        }
    }
}
```

When I save the document, values e and f, do not override the current values so d is not getting updated. I want d to be undefined or all their elements to be undefined, but old values persist in the DB.

**Comment by vkarpov15** [comment]
@yamifr07 what's your mongoose version and what does your schema look like?

**Comment by vkarpov15** [comment]
Issue's been stale for a while, re-open if this still a problem.
