### ISSUE TITLE
Compound Unique indexes 

### ISSUE THREAD

**Issue by yonib05** [Automattic/mongoose#3955]
**Feature Request:**

A cool to have compound unique indexes in a schema for instance.

```nodejs
var Schema = new Schema({
    created: {
        type: Date,
        default: Date.now
    },
    product_slug : {
        type: String,
        index: true
    },
    store_slug: {
        type: String
        index: true
    }
});


Schema.unique({store_slug : {product_slug : 1}});
```

So product_slug must be unique among all objects with the same store_slug.

This definitely could be achieved with a mongoose plugin however I think this could give mongoose a lot of power right out of the box and could be included.

**Comment by vkarpov15** [comment]
`Schema.index({ store_slug: 1, product_slug: 1 }, { unique: true });` https://docs.mongodb.org/manual/tutorial/create-a-unique-index/#unique-compound-index

**Comment by florianwalther-private** [comment]
@vkarpov15 Where do I put this? In the same file as the schema definition? Is it okay if this gets executed multiple times?

**Comment by vkarpov15** [comment]
@florianwalther-private yep same file as schema definition. Not a huge problem if it gets executed multiple times, although I'm not sure why you would want it to.

**Comment by florianwalther-private** [comment]
@vkarpov15 It gets executed whenever I restart my server, right?

Also, I don't really understand if I need to disable `autoIndex` in production. I've read the docs, but I don't really understand the implications. The slowdown it is said to cause only happens directly after restarting the server, not while it is running, is that correct?

And if I disable `autoIndex` in production, it will still use the (compound) indexes that were created in development mode?

**Comment by vkarpov15** [comment]
@florianwalther-private it does get executed whenever you restart your server.

You don't necessarily need to disable `autoIndex` in production. If you aren't running a large scale production app where you want to manage index builds yourself, you're fine to leave `autoIndex` on.

**Comment by florianwalther-private** [comment]
@vkarpov15 Thank you for the clarifiation!
