### ISSUE TITLE
Stress test problem

### ISSUE THREAD

**Issue by leopoldfreeman** [Automattic/mongoose#3956]
I find a problem when I test the proformance of our game server. Our schema:

```javascript
var playerSchema = new Schema({
    uid: {
        type: String,
        required: true
    },
    data: {
        //...
    },
    dataRev: {
        type: Number,
        required: true
        default: 0
    }
}, {
    //...
});
```

To prevent overwriting the data field, we use dataRev to protect it:
```javascript
function testWrite(player, cb) {
    PlayerModel.findOneAndUpdate(
        {uid: player.uid, dataRev: player.dataRev}, 
        {$inc: {dataRev: 1}, $set: {data: player.data}}, 
        {upsert: false, select: {dataRev: 1}}, 
        function(err, doc) {
            if (doc) {
                player.dataRev = doc.dataRev;
            }
            //...
        }
    );
}
```

The test routine will try to use the up function to update the data field which size is about 1KB.

The stress test program will create 4 threads and each thread will create 500 clients. Then each client will call the API of the server side to init the doc in database. After that, it will call the test routine every 10 seconds for 5 times.

The result shows the findOneAndUpdate could not find a few docs at the 2nd time (about 5%, I checked the player.dataRev, it is currect.). The 1st, 3rd, 4th and 5th were all passed. If I remove the dataRev from the query condition, there will be no failure. So, it cannot find the dataRev! In other words, there must be something wrong with $inc.

I ran the stress test program for several times. Everytime the failure happened at the 2nd time. <del>Please note that there are about 10 seconds between the two requests from the same client. </del>

There will be no failure if I create 4 threads and each thread only create 100 clients.

MongoDB: v3.2.3
Mongoose: v4.4.6
CentOS 7.2 amd64

**Comment by vkarpov15** [comment]
What does your stress test program look like? For one thing, there are no threads in node...

**Comment by leopoldfreeman** [comment]
It's a c sharp program. Each client will create a tcp connection to our game server. And it will use that connection to call the APIs of our game service which is a NodeJS application.

**Comment by leopoldfreeman** [comment]
I made a mistake, the second request was sent after the first request was completed (the callback of findOneAndUpdate has been fired). There is no interval between the two requests. The interval exists between later requests. That's the reason why requests always failed at the second time. If the interval exists between the 1st and 2nd requests, there's no failure.

**Comment by vkarpov15** [comment]
Do you have just one node process running or are there multiple?

**Comment by leopoldfreeman** [comment]
Multiple node processes. But each client only create one tcp connection to one node process during the test.

**Comment by vkarpov15** [comment]
And how exactly is your node process calling the `testWrite()` function?

**Comment by leopoldfreeman** [comment]
It's a general way for server to handle the request from clients. We use customed protocol which is build on TCP layer.
1. Create a listen socket.
2. Accept a client socket from the listen socket.
3. Read the packet data and check whether the packet is fully accepted (by checking the packet's header).
4. If it's a full packet, emit it.
5. Call the function to handle the packet.
 
So, the testWrite is called when the game service accepted a request from client and the request is 'testWrite'.

**Comment by leopoldfreeman** [comment]
I'll set up a HTTP service to test it on Monday and post the result here when done.

**Comment by vkarpov15** [comment]
The key question is can multiple findoneandupdates() be in flight at the same time? If so, would explain the behavior you're seeing

**Comment by leopoldfreeman** [comment]
No, it cannot. I sent the response in the callback of findOneAndUpdate. The client must receive the response before send the next request.

**Comment by vkarpov15** [comment]
Hmm and can the multiple threads try to update the same doc in parallel?

Might be helpful for you to enable mongoose debug mode, `require('mongoose').set('debug', true)`. This will show all the queries being sent to mongodb - that output would be really helpful in figuring out what's going wrong here

**Comment by leopoldfreeman** [comment]
Also, it cannot. The client's uid is unique (threadId + Date.now() + RobotIdx), I already said that. To verify that, I added a flag 'dbUpdating' in the object:
```javascript
var Player = function () {
    this.dbUpdating = false;
    ...
}

// In test function:
function testWrite(id, cb) {
    var player = playerMap.getPlayer(id);
    if (player.isUpdating) {
        logger.error('id %s is updating db.',id);
        cb(new Error());
        return;
    }

    player.isUpdating = true;
    playerDB.testWrite(err, function () {
        player.isUpdating = false;
        ....
    });
}
```

The error log never shows up.

**Comment by vkarpov15** [comment]
Hmm looks like the log file is gone. Did you take it down?

**Comment by leopoldfreeman** [comment]
Yes. You didn't grab it? I'll upload it again.

**Comment by leopoldfreeman** [comment]
The log has been uploaded again.

**Comment by vkarpov15** [comment]
Got it, thanks. Sorry, sometimes takes me a while to get to issues when a lot of them back up.

**Comment by vkarpov15** [comment]
@leopoldfreeman which op in the logs is the one that fails? Not sure what you mean by "at the 2nd time"

**Comment by leopoldfreeman** [comment]
Hi, I've reimplemented some parts of the stress test program recently. After I run tests with the new program and the server doesn't complain any more. So it should be a bug in previous version of stress test program. I'll compare the codes. Sorry.

**Comment by vkarpov15** [comment]
No worries, glad you found the issue :beers:
