### ISSUE TITLE
Enum validation doesn't get executed with {runValidators: true, upsert: true}

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#3963]
In the following schema:

    var PostModel = mongoose.Schema({
        kind: {
            type: Number,
            enum: [2, 3 ]
        }
    }, {strict: "throw"});

I have `kind` field with allowed `2` and `3` values only. But when I make following `update`:

    PostModel.update(
        {_id: "1"},
        {$set: {kind: 1}},
        {upsert: true, runValidators: true}
    ).exec(function (err, numAffected) {
         if (err) throw err;
    });

The new document get inserted with `{kind: 1}` if document `{_id: 1}` was not found. So `enum` restriction doesn't work in this case :(

**Comment by vkarpov15** [comment]
Expected behavior - numbers don't have a built-in enum validator. The below script works:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh3963');

var PostSchema = mongoose.Schema({
    kind: {
        type: Number,
        enum: [2, 3 ]
    }
}, {strict: "throw"});

var Post = mongoose.model('Post', PostSchema);

Post.create({ kind: 1 }, function(error) {
  assert.ifError(error);
  process.exit(0);
});
```

**Comment by skotchio** [comment]
I'm a little bit confused your answer. Your code works but it's not my case. I also create a new document but via `upsert` option. The validatiors behavior should be the same as in your example.

**Comment by vkarpov15** [comment]
The validator behavior is the same whether you're using conventional validation or update validators, because we don't have the `enum` validator for numbers. If you use `min` and `max` you'll get validator errors, but mongoose doesn't define any validators for the below schema:

```javascript
var PostSchema = mongoose.Schema({
    kind: {
        type: Number,
        enum: [2, 3 ]
    }
}, {strict: "throw"});
```
