### ISSUE TITLE
Document#invalidate would return this.$__.validationError

### ISSUE THREAD

**Issue by MarcelGeo** [Automattic/mongoose#3964]
Hello.

The function Document#invalidate can return new created validationError object. It would be usefull to use it in middleware for strictly mongoose error handling (new Error is not good reason).

Abstract example with bcrypt. It can be usefull to use validationError variable as error:

```javascript
schema.pre('save', function(next){
			// only hash the password if it has been modified (or is new)
			var that = this;
   			if (!that.isModified('password')){
				return next();
			}
			bcrypt.hash(that.password, 10, function(err, hash){
				if(err){
					var validationError = that.invalidate('password', 'Hashing failed', that.password);
					return next(validationError);			
				}else{
					that.password = hash;
				}	
				next();
			});
		});
```

**Comment by vkarpov15** [comment]
Good suggestion, thanks

**Comment by MarcelGeo** [comment]
You are welcome. invalidate is very usefull, need tunning :+1:
