### ISSUE TITLE
Document#invalidate can accept kind of ValidatorError

### ISSUE THREAD

**Issue by MarcelGeo** [Automattic/mongoose#3965]
It would be possible for invalidate method: create not only ValidatorError with kind 'user defined', but also with custom name of kind, passed as argument.

**Comment by vkarpov15** [comment]
Can you please clarify with a code sample? I don't quite understand.

**Comment by MarcelGeo** [comment]
I upgrade code from API docs.

`doc.invalidate('size','must be less than 20', 'CUSTOMKIND', 14); `

`doc.validate(function (err) {`
  `console.log(err)`
  `// prints`
 ` { message: 'Validation failed',`
   ` name: 'ValidationError',`
    `errors:`
    ` { size:`
        `{ message: 'must be less than 20',`
          `name: 'ValidatorError',`
         ` path: 'size',`
          `type: 'CUSTOMKIND',`
         `value: 14 } } }`
`})`

**Comment by vkarpov15** [comment]
What exactly are you trying to do? What does "custom name of kind, passed as argument" mean?

**Comment by MarcelGeo** [comment]
For now: kind of ValidatorError is no editable with function invalidate, but It will be usefull to do. If you have to mutch custom errors generated with invalidate, its not enough to have only 'user defined' kind.

**Comment by vkarpov15** [comment]
`ValidatorError` and `ValidationError` are hardcoded by mongoose, but you can still set the type using `CUSTOMKIND` like you did in the above example no?

**Comment by MarcelGeo** [comment]
I can not edit validator error. In source code, config in constructor for ValidatorError accepts arguments from invalidate: path, err, val. I want to add new argument: kind, which will be accdepted from invalidate arguments. Source code for invalidate function:

`if(!err || typeof err === 'string') {
    err = new ValidatorError({
      path: path,
      message: err,
      type: 'user defined',
      value: val
    });
  }`

constructor accepts path, err, val. I want to add new argument to invalidate: kind.

`if(!err || typeof err === 'string') {
    err = new ValidatorError({
      path: path,
      message: err,
      type: kind, // this is argument in invalidate function
      value: val
    });
  }`
