### ISSUE TITLE
Sparse and Unique Index not working for Schema-level index

### ISSUE THREAD

**Issue by 360disrupt** [Automattic/mongoose#3967]
I want to reopen this issue:
https://github.com/Automattic/mongoose/issues/2457

I have the same problem, see a full description here:
http://stackoverflow.com/questions/35920733/mongoose-compound-index-unique-sparse

## Code
```
implantSchema.index({ serialNr: 1, art: 1 , manufacturer: 1, deleted: 1}, { unique: true, partialFilterExpression: { serialNr: {$exists:true} }})
``` 
or
```
implantSchema.index({ serialNr: 1, art: 1 , manufacturer: 1, deleted: 1}, { unique: true, sparse: true})
```

Return both a `dup` error if the field does not exist.

**Comment by 360disrupt** [comment]
The solution was to update `mongodb` itself. Maybe it should throw a warning if the setting is applied when there is an old mongodb version used. `2.4` was preinstalled, I updated to `3.2.4`

**Comment by vkarpov15** [comment]
Hmm that's strange, as far as I know sparse indexes are supported in mongodb 2.4 (although partial indexes are not). Can you turn on the [`emitIndexErrors` option](http://mongoosejs.com/docs/guide.html#emitIndexErrors) to see if your index build failed, and, if so, why?

**Comment by 360disrupt** [comment]
I already deleted `2.4` but I guess it built the index. Because querying the index with `db.items.getIndexes()` showed the index correctly:

```
/* 0 */
{
    "0" : {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "LOC_db.items"
    },
    "1" : {
        "v" : 1,
        "unique" : true,
        "key" : {
            "serialNr" : 1,
            "art" : 1,
            "manufacturer" : 1,
            "deleted" : 1
        },
        "name" : "serialNr_1_art_1_manufacturer_1_deleted_1",
        "ns" : "LOC_db.items",
        "partialFilterExpression" : {
            "serialNr" : {
                "$exists" : true
            }
        },
        "background" : true
    }
}
```

**Comment by 360disrupt** [comment]
EDIT: I mistyped the version. I had `2.6.6.`

**Comment by vkarpov15** [comment]
Either way, I'd strongly recommend running with the `emitIndexErrors` option on, it'll give you more insight into failing index builds. The only reason why it's off by default is for backwards compat, it'll be [on by default in the next backwards breaking release](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings)
