### ISSUE TITLE
mongoose auto reconnect doesn't work if mongod downtime is around 10 seconds

### ISSUE THREAD

**Issue by tokunal80** [Automattic/mongoose#3969]
[mongoose_reconnect_issue.txt](https://github.com/Automattic/mongoose/files/170065/mongoose_reconnect_issue.txt)

Hi, 
I was using this auto reconnect feature and I observed if the mongod restart is within five seconds then this auto reconnect works but anything more than that and it fails to reconnect, even if you do request query on the connections it still just hangs there.  And I also couldn't figure out a clean way to restart mongoose connection when mongod is down when the app is started for the first time,  if you keep doing mongoose.connect in retry then when mongod comes up you can see those many connections opened with mongod as many times as you retried connection from your app. I even tried doing close/disconnect before doing a new connect but it doesn't help. I have been going through mongoose driver code but till now have not been able to reach the right code where it's giving up reconnection action.

Another issue I observed is that if I sent multiple queries when mongoose driver is trying to reconnect then reconnect never happens even if the mongod is up and running in less than three seconds.

Mongoose version: 4.4.6
Nodejs version: 0.12.10

**Comment by vkarpov15** [comment]
The underlying mongodb driver will only try reconnecting a certain number of times before giving up. Set the `server.reconnectTries` and `server.reconnectInterval` options: http://mongodb.github.io/node-mongodb-native/2.1/api/Server.html

We should really clarify this in the docs.

**Comment by tokunal80** [comment]
I was aware of these two configurations but is there are good way to know that driver has given up on reconnect and the application should try opening a fresh new connection and keep retrying till it succeeds?

**Comment by vkarpov15** [comment]
Not at the moment. Can you open up an issue for that?
