### ISSUE TITLE
Connection returned from mongoose.connect has undefined connection.db property in 4.4.7

### ISSUE THREAD

**Issue by mleanos** [Automattic/mongoose#3972]
We're connecting to our MongoDB instance with `mongoose.connect`. Up till the release of Mongoose `4.4.7`, the returned Connection's `connection.db` property gave us a `dropDatabase` method.

After upgrading to `4.4.7`, the `connection.db` property is undefined.

We connect this way:
```javascript
var db = mongoose.connect(config.db.uri, config.db.options, function (err) {
    // Log Error
    if (err) {
      console.error(chalk.red('Could not connect to MongoDB!'));
      console.log(err);
    } else {

      // Enabling mongoose debug mode if required
      mongoose.set('debug', config.db.debug);

      // Call callback FN
      if (cb) cb(db);
    }
  });
```
And we have a Grunt task to drop the database:
```javascript
grunt.task.registerTask('dropdb', 'drop the database', function () {
    // async mode
    var done = this.async();

    // Use mongoose configuration
    var mongoose = require('./config/lib/mongoose.js');

    mongoose.connect(function (db) {
      db.connection.db.dropDatabase(function (err) {
        if (err) {
          console.log(err);
        } else {
          console.log('Successfully dropped db: ', db.connection.db.databaseName);
        }
        db.connection.db.close(done);
      });
    });
  });
```

I reverted back to Mongoose `4.4.6` and this issue went away.

**Comment by mleanos** [comment]
Upon further investigation, it appears the connection isn't being made. When I change the above example that connects to the database, to use `createConnection` instead of `connect`, I get the following error thrown.

![gh-1264-mongoose-createconnection-error](https://cloud.githubusercontent.com/assets/5613734/13730475/8af2e30c-e90d-11e5-8a5e-c89c77d66198.PNG)

Perhaps, I'm complicating the matter by changing the connection method to use `createConnection` (for the purposes of debugging) but I find it interesting that no error is thrown when attempting the connection by using `connect`; but it's not making the connection.

Any ideas?

**Comment by simonkontschak** [comment]
Same situation, same problem...

**Comment by DrDanRyan** [comment]
I am having connection issues as well in 4.4.7

**Comment by mleanos** [comment]
@vkarpov15 My issue went away after upgrading to 4.4.8. Thanks for the prompt fix!
