### ISSUE TITLE
Sort method should also accept a function param

### ISSUE THREAD

**Issue by guilhermedelai** [Automattic/mongoose#3978]
Ex:

```
Users.find().sort(function(userA, userB){return userA.name - userB.name}).exec(function(err, data){
   console.log(err)
   console.log(data)
})
```

It would be an awesome feature.

**Comment by vkarpov15** [comment]
Not really possible, because mongoose relies on the mongodb server to handle sorting, and mongodb doesn't allow you to sort by arbitrary functions.
