### ISSUE TITLE
Subdocument schema model and intance

### ISSUE THREAD

**Issue by wertlex** [Automattic/mongoose#3979]
Not found where to ask, so fired this issue. 

I'm trying to separate domain 'classes' in my app with embedded subdocuments and submodels with static methods.  What I'm trying to achieve is simple subdocument encapsulation not to pull all related logic in one fat model. But I face very strange problem. As submodels not instantiated with `db.model()` they are not `Models` and statics/instance methods are unavailable here. Looks like submodels are only convenient shortcat for json structure, not logic. Am I mistaken?

Here is an example:

`HashedPasswordSchema` easy to construct, easy to compare. 
```
// HashedPasswordSchema.json
const HashedPasswordSchema = new Schema({
    salt: { type: String },
    hash: { type: String }
});

HashedPasswordSchema.statics.newPassword = function(purePass, optSalt, optIterations){
  // salting, hashing, cooking, promising
  return Promise.resolve(new this({ salt: 'salted', hash: 'hashed'})); // effectively we got this
};

HashedPasswordSchema.methods.isSame = function(purePass){
  return Promise.resolve(true); // one size fits all 
};
```

UserSchema:

```
const HashedPassword = require('./HashedPasswordSchema');
const UserSchema = new Schema({
    email: { type: String},
    password: { type: HashedPassword },
    name: { type: String }
});

/** Constructs new unverified user with given userData */
UserSchema.statics.newUnverified = function(userData) {
    if(userData.password) {
        userData.password = HashedPassword.newPassword(userData.password); // ERROR: newPassword is not a function
    }
    const user = new this(userData);
    // TODO: add sms and email service call for real tokens
    return user;
};
```

So, submodels and subdocuments are only can be used to bring part of schema or there is a way to use them almost like normal documents/schemas/models?

**Comment by vkarpov15** [comment]
It's tricky to use statics with nested schemas, because a `HashedPassword` above is just a schema, not a full fledged model. You can do something like this:

```javascript
// HashedPasswordSchema.json
const HashedPasswordSchema = new Schema({
    salt: { type: String },
    hash: { type: String }
});

HashedPasswordSchema.statics.newPassword = function(purePass, optSalt, optIterations){
  // salting, hashing, cooking, promising
  return Promise.resolve(new this({ salt: 'salted', hash: 'hashed'})); // effectively we got this
};

HashedPasswordSchema.methods.isSame = function(purePass){
  return Promise.resolve(true); // one size fits all 
};

module.exports = mongoose.model('HashedPassword', HashedPasswordSchema);
```

```javascript
const HashedPassword = require('./HashedPasswordSchema');
const UserSchema = new Schema({
    email: { type: String},
    password: { type: HashedPassword.schema },
    name: { type: String }
});
```

And then you should in theory be able to use it. However, IMO the better solution would be to just use a pure helper function to generate the password:

```javascript
HashedPasswordSchema.newPassword = function(purePass, optSalt, optIterations){
  // salting, hashing, cooking, promising
  return Promise.resolve({ salt: 'salted', hash: 'hashed'}); // effectively we got this
};
```

If you return a POJO, mongoose will cast that POJO into a subdoc for you when you set `userData.password`, so no need to create a full doc. As a matter of fact, creating a full doc is bad for performance, because mongoose will just convert it back to a plain object before casting it into a subdoc.

**Comment by wertlex** [comment]
@vkarpov15 thanks for feedback. I'm already bring user's password back to user's schema. 
It is definetly not a feature request and quick run through sources show that `Model`s only exists backed with collections, but I believe such kind of feature eventually can be very usefull as in Mongo nesting is the only way to atomicity :)
