### ISSUE TITLE
Difference in Promise behavior between the v. 4.3.* and 4.4*

### ISSUE THREAD

**Issue by Fred2MTL** [Automattic/mongoose#3983]
Hi All
I encounter a strange issue since the upgrade to v4.4.*. The following code runs correctly in v 4.3.* and  stucks in v 4.4.* at the remove invocation, without any timeout. I don't understand/know the effective issue.

Thanks in advance

Fred

```javascript
var mongoose = require('mongoose'),
	dbUrl = 'mongodb://@' + oConfigDataDb.host + ':' + oConfigDataDb.port + '/' + oConfigDataDb.name;
var dbConnectionOptions = {
	db		: { native_parser: true },
	safe	: true,
	server	: { poolSize: oConfigDataDb.poolSize },
};
mongoose.Promise = global.Promise;
mongoose.connect(dbUrl, dbConnectionOptions);

function toConfigure(aModel,aConfigData,aTypeName){
	return new global.Promise(function(resolve, reject) {
		aModel.remove().then(function(){
			aModel.create(aConfigData).then(function(aResult){
				oLogger.info(aTypeName + ' Loading : ' + aConfigData.length + ' - ' + aResult.length);
				resolve(aResult.length);
			},function(aError){
	    		oLogger.warn(aTypeName + ' Loading : Error : ' + aError);
	    		reject(aError);
			});
		}).catch(function(aError){
			oLogger.error(aTypeName + ' Loading : Error : ' + aError);
			reject(aError);
		});
	} ); 
}
```

**Comment by vkarpov15** [comment]
Can you elaborate on your issue? I don't see where `toConfigure()` is getting called?

**Comment by Fred2MTL** [comment]
Hi Viktor
As required. I load some configuration files (list of JSON structures) according to the corresponding models and with help of Promises.
Thanks
Fred

var oPromises = [];
oConfigData = _.find(oDiverseConfig.structures,{ 'identifier': 'agreement' }).data;
oPromises.push(toConfigure(models.Agreement,oConfigData,'Agreements'));
Promise.all(oPromises).then(function (aData) {
	...
	process.exit();
},function(aError){
	...
	process.exit(-1);
});

in 4.3.*:
[2016-03-16 21:59:12.543] [INFO] Database - Start of configuration
[2016-03-16 21:59:12.715] [INFO] Database - Insurance Companies Loading : 3 - 3
... then loading of 24 configuration files
[2016-03-16 21:59:12.735] [INFO] Database - End of configuration

in 4.4.*
[2016-03-17 21:40:01.159] [INFO] Database - Start of configuration
... then, anything else ;-)

**Comment by vkarpov15** [comment]
Can't quite reproduce. Try enabling mongoose debug mode `mongoose.set('debug', true);`. The below script works without error for me, see if you can modify to repro your issue.

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var util = require('util');

mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/gh3983');
mongoose.set('debug', true);

var TestModel = mongoose.model('Test', { name: String });

new Promise(function(resolve, reject) {
  TestModel.remove().then(
    function() {
      resolve();
    },
    function() {
      reject();
    });
}).then(() => { console.log('done'); process.exit(0); });
```

**Comment by Fred2MTL** [comment]
Your test hangs also in my environment for V 4.4.x, not for 4.3.x. The issue seems to come from my environment characteristics and to be related to promise management.
In order to clearly define the issue, I will build a clean new project, validate the correctness of V 4.4.x, then introduce the libraries (as specified in my current file 'package.json') one per one and test. 
Do you agree ? Ideas are welcome.
[package.json.txt](https://github.com/Automattic/mongoose/files/207426/package.json.txt)

**Comment by vkarpov15** [comment]
Hmm @Fred2MTL the test above hangs? Do you actually have a mongod server running on `localhost:27017`? That's the only reason that I can think of why the above script would hang...

**Comment by Fred2MTL** [comment]
Hi @vkarpov15. 
The mongodb server was 'up and running' during the two tests. I just update my environment through the modification of package.json (entry : mongoose) and the usage of npm. No other action.
So, i expect to complete the tests with help of the 'clean' projet (ie. not my currently one, under development) during the next weekend.
I think there is an inconsistency into the dependencies during theirs updates (exclusively with help of npm). Then, i don't think there is a 'physical' issue. 
Refer to my previous comment in order to see the dependencies if you want. I don't use exotic libraries ;-)

**Comment by vkarpov15** [comment]
Are you running the test script provided above as-is? Or are you running it in a separate file? The script doesn't really have an 'environment' or much in the way of dependencies other than having a mongodb running on localhost:27017 and mongoose installed. Can you clarify the above comment?

**Comment by Fred2MTL** [comment]
Hi @vkarpov15 
I found the issue. In development mode, i don't use any authentication, but the synbol @ remains in the URL. It wasn't an issue with the version 4.3, but it is with the version 4.4. Certainly due to a new version of mongo driver. In fact, your proposal didn't run because i used my connectivity code, not yours.I flix it and it runs correctly. 
I don't know if the issue remains. This part of code isn't protected against connection default ans i will enforce that.  But, the connection steps ran correctly with the symbol in the URL and the operation 'remove' return a promise object, unfunctional. I let you do decide.
Thanks for your help and your time.

**Comment by vkarpov15** [comment]
@Fred2MTL what does your connection string look like? The below script works fine for me too:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var util = require('util');

mongoose.Promise = global.Promise;
mongoose.connect('mongodb://@localhost:27017/gh3983');
mongoose.set('debug', true);

var TestModel = mongoose.model('Test', { name: String });

new Promise(function(resolve, reject) {
  TestModel.remove().then(
    function() {
      resolve();
    },
    function() {
      reject();
    });
}).then(() => { console.log('done'); process.exit(0); });
```
