### ISSUE TITLE
Timestamp functionality triggers unnecessary update

### ISSUE THREAD

**Issue by tommarien** [Automattic/mongoose#3991]
When using the timestamp functionality whenever you do a document.Save() on an existing document it triggers an unnecessary update to the db when the document is not modified

**Comment by seriousManual** [comment]
do have an example to reproduce this behaviour?

**Comment by tommarien** [comment]
@seriousManual Did even better created pr for it ;), no clue why what seems to be unrelated fails

**Comment by vkarpov15** [comment]
Thanks for the pr. Don't worry about the unrelated fails, Travis just has really unreliable infrastructure
