### ISSUE TITLE
Setting a relation with a full object (ref column) triggers a change although the object ids are the same

### ISSUE THREAD

**Issue by tommarien** [Automattic/mongoose#3992]
For instance 

Person: {
}

Job: {
  person : {type:objectid, ref:Person}
}

const p = PersonModel.FindOne()

aJob.person = p;
aJob.Save();

The job should not been seen as modified if the job previously had the same id as the person model assigned

**Comment by tommarien** [comment]
@vkarpov15 it think this fix will break subdocuments, it should only not mark is as modified when the object is a ref, imho :S

**Comment by vkarpov15** [comment]
What do you mean? The populated check will fail for subdocs...

**Comment by tommarien** [comment]
You're right missed it sorry fir the confusion :s
