### ISSUE TITLE
Virtual fields gets selected despite not listing them in projections

### ISSUE THREAD

**Issue by darkbasic** [Automattic/mongoose#4001]
var taskSchema = mongoose.Schema({
    name: {
        type: String,
        required: true,
        validate: nameValidator
    },
    completed: {type: Boolean, default: false}
}, {
    toObject: {virtuals: true},
    toJSON: {virtuals: true}
});

taskSchema.virtual('title')
    .get(function () {
        return this.name
    })
    .set(function (title) {
        this.name = title
    });

models.Task.find({completed: false}, '_id name', {sort: {_id: -1}}, function (err, docs) {
  // docs has the 'title' virtual field
})

Mongoose 4.4.6

**Comment by vkarpov15** [comment]
There's no way to deselect virtuals, because they're not stored in the database.

**Comment by darkbasic** [comment]
I know they're not stored in the db (that's the whole point of virtuals), I simply want to craft my response and I expect my ODM does it for me instead of having to do it manually. Is it a wrong pattern or what?

**Comment by vkarpov15** [comment]
Yeah, it's just that virtuals are an abstraction on top of documents rather than being truly part of the document. IMO the key use case for virtuals is as functions whose output appears in toJSON, and I don't think putting that as part of field selection really fits with that use case

**Comment by darkbasic** [comment]
Either I don't understand virtuals use cases or the whole community got it wrong. In "Practical Node.js" (http://www.apress.com/9781430265955) the author says:
- "Virtual fields are awesome for creating aggregate fields." OK, fine.
- "Another use case is to make the database backward compatible. For example, we might have thousands of user items in a MongoDB collection and we want to start collecting their locations. We have two options: run a migration script to add the default location (“none”) to the thousands of old user documents or use a virtual field and apply defaults at runtime!" See below.

Here is the problem with the second suggested scenario (backward compatibility):

req.models.Todo.findOne({"name" : "task 1"}, function (err, doc) {
    console.log(doc.title) // task 1
    console.log(JSON.stringify(doc.title)) // "task 1"
    console.log(doc) // it does not show any title attribute
    console.log(JSON.stringify(doc)) // it does show a title attribute with value "task 1"
})

then after doing a "db.todos.update({"name" : "task 1"}, {"$set" : {"title" : "task 9999"}})" in the shell:

req.models.Todo.findOne({"name" : "task 1"}, function (err, doc) {
    console.log(doc.title) // task 1
    console.log(JSON.stringify(doc.title)) // "task 1"
    console.log(doc) // it does show a title attribute with value "task 9999"
    console.log(JSON.stringify(doc)) // it does show a title attribute with value "task 1"
})

This is a nightmare to work with.

**Comment by vkarpov15** [comment]
Hmm that's an unusual use case. I'll reopen this and take a look next week

**Comment by vkarpov15** [comment]
So the reason why you're seeing "task999" when you `console.log(doc)` is that mongoose isn't currently taking the `{ virtuals: true }` option when doing `require('util').inspect()`, which is how node converts objects to strings for `console.log()`. Not a big deal, you would still get the correct output when you do `res.json()` with express.
