### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by Risto-Stevcev** [Automattic/mongoose#4002]
For **Query#find(**[`criteria`], [`callback`]**)**, 

```js
query.find({ name: 'Los Pollos Hermanos' }).find(callback)
```

should be:
```js
query.find({ name: 'Los Pollos Hermanos' }, callback)
```

http://mongoosejs.com/docs/api.html#query_Query-find

**Comment by vkarpov15** [comment]
Either should work just fine.
