### ISSUE TITLE
Bump mongodb version to 2.1.10

### ISSUE THREAD

**Issue by chrisckchang** [Automattic/mongoose#4010]
We're seeing a lot of user issues when using mongodb version 2.1.8. Can we update the version to 2.1.10? 

Thanks,

Chris@mLab

**Comment by samparas** [comment]
We are also having issues with mongodb version 2.1.8, which were seen when we upgraded to 4.4.8 this weekend. You can see the tickets here: https://jira.mongodb.org/browse/NODE-679?jql=project%20%3D%20NODE%20AND%20created%3E%3D-1w%20ORDER%20BY%20created%20DESC

Downgrading down to 4.4.7 seems to have fixed our problem

**Comment by toddbluhm** [comment]
I was just going to suggest this. I forked mongoose yesterday and internally bumped to 2.1.10 and we have been running without issue so far today. It seems like it should be a safe bump.
