### ISSUE TITLE
id method for sub document array when _id is instance of ObjectId

### ISSUE THREAD

**Issue by dongliu** [Automattic/mongoose#4011]
The line https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L148 results in comparing the parameter id and _id with utils.deepEqual (https://github.com/Automattic/mongoose/blob/master/lib/utils.js#L140) if !(_id instanceof ObjectId). 

I assume the right logic should be to use utils.deepEqual when both id and _id are instances of ObjectId. Otherwise, the strings should be compared.

**Comment by vkarpov15** [comment]
@dongliu does this cause an end-user facing issue?

**Comment by dongliu** [comment]
I think it does. 
When the user defines the _id in sub document array as String type. Then the id(par) function should try to convert par to String and then compare with _id, other than convert par to ObjectId and then compare with _id with utils.deepEqual(). 

There is nothing wrong with utils.deepEqual(), but what to do before calling it. Hope this clarify it.

**Comment by vkarpov15** [comment]
Can you provide a code sample? Translating prose to code is error prone

**Comment by dongliu** [comment]
A schema like this
```javascript
var sub = new Schema({
    _id: String,
   other: String
})

var main = new Schema({
    subs: [sub]
})
```
Suppose we have a document like
````json
doc =  {
    "subs" : [
        {
              "_id" : "a_string",
              "other" : "something"
        }
    ]
}
````

Try to find a sub document by `doc.subs.id(ObjectId('a_string'))`
will not succeed. In order to make it work, the logic at https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L148 can be like
```javascript
      if (_id === null || typeof _id === 'undefined') {
        continue;
      } else if (_id instanceof Document) {
        sid || (sid = String(id));
        if (sid == _id._id) {
          return this[i];
        }
      } else if (!(casted) && !(_id instanceof ObjectId)) {
        if (utils.deepEqual(id, _id)) {
          return this[i];
        }
      } else if (casted == _id) {
        return this[i];
      }
```
