### ISSUE TITLE
Cast to ObjectId failed for value "[object Object]" at path "_id"

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#4018]
Hi, I have several embedded docs with refs in it, I want to avoid the useless creation of embedded docs _id.
`schema = mongoose.Schema(
{
name:String,
chapters:[{item:{type: ObjectId, ref: 'chap'},comment:String,_id: false}],
}
`
Since I added this _id:false, my get query throws the error in title when I try to populate a null ref. There is a way to fix it? I search for other discussion, but I didn't find any proper solution..

**Comment by johndorn** [comment]
Are you getting this error when you try to insert? If so, it's likely your insert statement that is the culprit. When you say "try to populate a null ref" what does that mean? Are you trying to set `doc.chapters[0]._id` to null? If so, you should just leave it unset.

**Comment by alfredopacino** [comment]
The error is in a .find() query.
By 'try to populate a null ref' I mean those refs could exists or not.
I don't touch that chapter[x]._id.

**Comment by alfredopacino** [comment]
This is the real schema end the real query
```
var schema = mongoose.Schema( { name:String,
    euLaw:[{item:{type: ObjectId, ref: 'euLaw' },comment:String,_id:false}],
});
```

the query, I guess the error is that population of item nested field
```
 caseNoteA
        .findOne({_id:id})
        .populate([
            {
                path: 'euLaw',
                populate: {
                    path: 'item',
                    model: 'euLaw'
                }
            }])
        .exec(function (err, data) {
            if(err || !data) {
                res.status(404)
                next(err)
            } else
                res.json(data);
        });
```

**NOTE** if I remove that `_id:false` in schema all works fine

**Comment by vkarpov15** [comment]
Why are you doing a deep populate? The euLaw.item field is only one step away, not 2. You only need to populate the item field

**Comment by alfredopacino** [comment]
Well I guess you're right, I can't remember why I made it, could you kindly provide a proper example of deep population?
 (I don't need in this case, but I will...my syntax is right?)

**Comment by vkarpov15** [comment]
@alfredopacino http://mongoosejs.com/docs/populate.html#deep-populate . `.populate('euLaw.item')` will work just fine.
