### ISSUE TITLE
Throw error when accessing un-selected field

### ISSUE THREAD

**Issue by mspensieri** [Automattic/mongoose#4020]
Our application uses projections to optimize memory usage, but it's hard to keep track of which fields have/have not been selected. Is there a way to configure Mongoose to throw an error when attempting to access a field that has not been selected through query projection? 

For example:

```
var Person = mongoose.model('Person', new Schema({
  firstname: String,
  lastname: String
}));

Person.findOne({}, {
  lastname: 0
})
.then(function(person){
  console.log(person.isSelected('lastname')); // => false
  console.log(person.lastname); // => undefined
});
```

Instead of returning `undefined` when accessing `person.lastname`, it would be great if this could throw a `NotSelectedError` or something to let the programmer know that they need to modify the query in order to access this field.

**Comment by vkarpov15** [comment]
I like this idea. Would be very easy to implement as a plugin using custom getters and setters.

**Comment by dannytranlx** [comment]
I often run into this issue and would like to have this in Mongoose as well. Any progress on this task?

**Comment by vkarpov15** [comment]
No progress, hasn't been a priority. Will re-investigate for a future minor release

**Comment by vkarpov15** [comment]
Use https://www.npmjs.com/package/mongoose-throw-unselected
