### ISSUE TITLE
Model.update Validators: No access to "this", specifically in subschemas

### ISSUE THREAD

**Issue by ross-nordstrom** [Automattic/mongoose#4028]
Using `this` in my validators works for document validation, but breaks (throws errors) on query validation.

Is there an option I'm not aware of that would help me achieve this?

My root issue is that I want to mutually validate 2 fields against each other, and had been using `this` as a way to access each of them.

```js
var schema = new Schema({
  smaller: {type: Number, validate: validateRelative},
  larger: {type: Number, validate: validateRelative}
}, {_id: false});

function validateRelative(val, done) {
  // Works for document validation, 
  // but throws (this not defined) on query (update) validation
  if(this.smaller > this.larger) {
    return done(false, "`larger` must be greater than `smaller`");
  }

  return done;
}
```

Another alternative I could think of, but couldn't figure out how to implement would be defining "root" validation on my schema, e.g.:

```js
// Is there a way to do this??
schema.path(/* root */).validate(validateRelative);

function validateRelative(subDoc, done) {
  if(subDoc.smaller > subDoc.larger) {
    return done(false, "Path `larger` must be greater than path `smaller`");
  }

  return done;
}
```

**Comment by vkarpov15** [comment]
Check the validation docs, we explicitly set this to null for update validators, because when running update validators mongoose doesn't necessarily have access to the document being modified, the document may be just in mongodb

**Comment by vkarpov15** [comment]
Woops that's a bug with our docs, let me fix really quick.

**Comment by vkarpov15** [comment]
Fixed, see http://mongoosejs.com/docs/validation.html#update-validators-and-this . Looks like our docs build was broken.

**Comment by ross-nordstrom** [comment]
> However, you can set the `context` option to 'query' to make this refer to the underlying query.

I don't see any examples of the `context` option. Could you help give some insight? Is that an `update` option like `runValidators`?

**Comment by vkarpov15** [comment]
Thanks for pointing that out, fixed.
