### ISSUE TITLE
Mongoose 4.4.10, mongodb-core 1.3.9 and MongoDB 3.2 - Cursor not found

### ISSUE THREAD

**Issue by xyleads** [Automattic/mongoose#4030]
This is referencing a closed issue: #3927 

For others who are experiencing this issue, using mongoose 4.4.10 with MongoDB 3.2, it was just fixed in mongodb-core version 1.3.13.

christkv/mongodb-core@caa169d

The MongoDB driver would intermittently throw errors of the form:

Cursor not found (namespace: 'some.collection', id: 73106491510903863)."

This would mainly happen on find calls returning more than some random threshold of data.

I've used npm-shrinkwrap to bump Mongoose's dependency of mongodb-core up to version 1.3.13 from 1.3.9. Hopefully, this version bump will come from the Mongoose team soon.

**Comment by vkarpov15** [comment]
Should already be done, upgraded to mongodb driver 2.1.14 yesterday, which should be mongodb-core 1.1.13

**Comment by xyleads** [comment]
Awesome. Thank you very much.

**Comment by harshjv** [comment]
I am still facing this issue with mongoose@4.4.19

**Comment by vkarpov15** [comment]
Please open a new issue with detailed repro instructions
