### ISSUE TITLE
feature request: support for specifying mongos=true in connection query string

### ISSUE THREAD

**Issue by burtonjc** [Automattic/mongoose#4035]
We have a number of different environments that have different database configurations. For example, in our test environment we simply run a `mongod` instance that is not ssl enabled. In production, we have a `mongos` cluster that forces ssl. Currently, we have to specify `{mongos: true}` if we are in production, but then have to be smart enough to not do that in tests. We also have several more environments dealing with the same complications. I have tried to infer if it is a `mongos` cluster from the connection string format, but as far as I can tell, there is no fail-proof way to determine a `mongos` cluster from a replica set. The ssl piece is conveniently handled completely by the connection string via the `ssl` query param. It would be awesome if our code didn't care at all about `mongos` vs `mongod` vs a replica set either and for the connect string to have all the information needed for how to connect to mongo.

So currently, to connect to `mongos` you have to do:
```javascript
mongoose.connect('mongodb://host.name:1234/dbname', {mongos: true});
```
What we would like to have is:
```javascript
mongoose.connect('mongodb://host.name:1234/dbname?mongos=true');
```

I am happy to open a PR for this, but wanted to throw the idea out there before taking the time to implement it in case there were objections.

**Comment by vkarpov15** [comment]
Sounds like a great idea 👍

**Comment by burtonjc** [comment]
Great, it might be a couple weeks before I get to this. I am taking a trip and will be in and out of internet service. But I will get to it asap!
