### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by klimashkin** [Automattic/mongoose#4037]
Hello!
If in model schema we define field as array of strings (`{ type: [String] }`), previously (before 4.4) it was possible to avoid creating empty array in database record on document saving , if assign `undefined` to corresponding document field.
But after update to 4.4 I can't avoid creating empty array.

**Comment by klimashkin** [comment]
@vkarpov15 If it doesn't work, maybe in next mongoose version do not create empty arrays in database by default if value is not provided? And substitute with empty array when document with empty field is selected (without `lean` option)?

**Comment by vkarpov15** [comment]
So mongoose does **not** create an array in the database if you set the array to `undefined`, but when you load the document back you get the default value for an array, which is an empty array `[]`, and that's very much an integral part of how mongoose works. I'd recommend you just set the array to `null`.

```javascript
      var Foo = db.model('gh4037', {
        strs: [String]
      });

      var f = new Foo({ strs: null });
      f.save(function(error) {
        assert.ifError(error);
        assert.strictEqual(f.strs, null);
        Foo.findById(f._id).exec(function(error, doc) {
          assert.strictEqual(doc.strs, null);
        });
      });
```

Since null represents intentional absence of a value according to the ES2015 spec, we bypass defaults for null, but not for undefined.

**Comment by klimashkin** [comment]
I don't know why, but for me it **creates** empty array in the database if I set the array to undefined.
I see it through mongo console.
Before mongoose 4.4 it was not created

**Comment by klimashkin** [comment]
@vkarpov15 I got it!
I create object, assign undefined to one of its array property and then create model object from it. Like this:
```
new MyModel({..., arr: unedfined, ...}).save()
```
And in this case `arr` is being saved as empty array (yes, empty array in database). 

If I assign undefined to already created model instance, then empty array is not being saved in db, as you said.
```
const model = new MyModel({...}).save();
model.arr = undefined;
model.save();
```

But before 4.4 results of both approach were the same!

**Comment by vkarpov15** [comment]
I think this has to do with a recent change that prevented setting something to undefined from overwriting defaults, since mongoose automatically sets the default for arrays to an empty array. Is this a problem for you or do you plan on using null instead?

**Comment by klimashkin** [comment]
Yeah, we have millions of records and only several percents of them have a few array properties, that contain data.
So it's a pretty overheady to store empty arrays for all millions records, and with `undefined` I was sure that I store only meaningful data, not empty objects

**Comment by vkarpov15** [comment]
Can you just use null instead? That's probably more correct anyway with how mongodb works.

**Comment by klimashkin** [comment]
But why? To remove all other fields i can use undefined, except arrays?

On Monday, April 18, 2016, Valeri Karpov <notifications@github.com> wrote:

> Can you just use null instead? That's probably more correct anyway with
> how mongodb works.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/4037#issuecomment-211434551>
>


-- 
*Sincerely yours, Paul Klimashkin.*

**Comment by vkarpov15** [comment]
You can't use `undefined` to remove fields that have defaults, and every array has an implicit default of `[]`.

Furthermore, the mongodb driver [converts `undefined` to `null` internally](https://github.com/mongodb/js-bson/blob/f7efecc04240525931402116f881b5984af800c4/lib/bson/parser/serializer.js#L120-L122) because the bson type `undefined` has been deprecated for many years, so you actually can't store a field with value undefined in mongodb from node.

**Comment by klimashkin** [comment]
What if we split concept 'default' to 'default write' and 'default read'. It would be much flexible.
For instance if I have some `type` field with index: true and default: 13, I want to write it to database by default also.
But If I have some additional fields, like array of document modify dates, avatar path or something like that - I don't need to write them by default to database, it's redundant, but good to have default values for them when I read them from db to mongoose document.

And discrepancy in behavior is still retained: If I assign undefined to array field to _mongoose document instance_ I will delete it completely, as I expect

**Comment by vkarpov15** [comment]
IMO splitting the concept of 'default' just adds more concepts and more confusion, and there's a good reason for using `[]` as a default value for an array - so you can do push immediately. If you want to have a default value that doesn't get saved to the db, a custom getter would handle that quite nicely.

**Comment by r3wt** [comment]
this causes so many bugs. boo for this shitty behavior.

**Comment by vkarpov15** [comment]
@r3wt what bugs has this caused for you?

**Comment by r3wt** [comment]
Many bugs. Such wow

On Feb 6, 2018 5:13 PM, Valeri Karpov <notifications@github.com> wrote:

@r3wt<https://github.com/r3wt> what bugs has this caused for you?

**Comment by vkarpov15** [comment]
Can you provide some examples?

**Comment by r3wt** [comment]
No

On Feb 12, 2018 2:59 PM, Valeri Karpov <notifications@github.com> wrote:

Can you provide some examples?

**Comment by r3wt** [comment]
You know what bugs it causes. Don't be dishonest and play stupid. It causes bugs if you expected the property to not be set,but instead its an empty array.

On Feb 12, 2018 2:59 PM, Valeri Karpov <notifications@github.com> wrote:

Can you provide some examples?

**Comment by vkarpov15** [comment]
Not trying to be dishonest or stupid, just constructive. I can see it causing bugs, but it also has been a part of mongoose since the beginning, it enables you to use arrays immediately without having to check for existence, and if you don't like it there's an easy one-line workaround.

**Comment by isaachinman** [comment]
@r3wt Why do you consistently behave like this? OSS is not created and maintained for your own personal benefit. It's really a shame when I come across your borderline abusive comments, which is semi-frequently.

**Comment by r3wt** [comment]
> Not trying to be dishonest or stupid, just constructive. I can see it causing bugs, but it also has been a part of mongoose since the beginning, it enables you to use arrays immediately without having to check for existence, and if you don't like it there's an easy one-line workaround.

How about a compromise: Add a disclaimer and common pitfalls sections to the docs/readme.

**Comment by vkarpov15** [comment]
@isaachinman your concern is appreciated, but unnecessary in this thread. I love a good spirited debate.

@r3wt this behavior is already in the [schematypes docs](http://mongoosejs.com/docs/schematypes.html#arrays) and [the FAQ](http://mongoosejs.com/docs/faq.html#array-defaults). I moved these questions up in priority based on your feedback. Do you have any other suggestions for where to put this? Maybe worth creating a table of contents for the FAQ because it's grown a little heavy?
