### ISSUE TITLE
Mongoose Mongo 2dsphere geoWithin

### ISSUE THREAD

**Issue by westandy** [Automattic/mongoose#4044]
Please see http://stackoverflow.com/questions/36415162/mongoose-mongo-2dsphere-geowithin for the full description.  

The short of it: despite $geoWithin working fine in Mongo, Mongoose keeps telling me **[Error: Can't use $geoWithin]**

**Comment by vkarpov15** [comment]
Next time please put the code samples here, don't just link to SO. Will review this when I get a chance.

**Comment by westandy** [comment]
OK.  Thanks for the heads up, Valeri.

Andy W.

**Comment by vkarpov15** [comment]
Good catch @westandy. Mongoose query casting was filtering out your `$geoWithin` query, will push a release for this issue early next week.

**Comment by westandy** [comment]
Thanks @vkarpov15 for fixing this.  

Side question: did you test the other geoSpatials as well ($geoIntersects, $near, $nearSphere)?  Would they require a separate issue ticket if they were a problem?

**Comment by vkarpov15** [comment]
Yeah open up a separate issue if you have trouble with those
