### ISSUE TITLE
Params used in construct model isn't validated

### ISSUE THREAD

**Issue by EJGamer04** [Automattic/mongoose#4047]
When you use the construct model to fill a object, isn't validating the data.

```
mongoose.model('Contact', {
    name: {
        type: String,
        maxlength: 3
    },
    address: String
});
var Contact = mongoose.model('Contact');
var newContact = new Contact({
    name: 'My name',
    address: 'My Address'
});
newContact.save();
```

Is saved although viole the validations

**Comment by vkarpov15** [comment]
We have tests in place for this use case. Which version of mongoose are you using?

**Comment by EJGamer04** [comment]
I'm using mongoose 4.1.2

**Comment by vkarpov15** [comment]
Try upgrading, I suspect the maxlength validator was added recently but don't remember off the top of my head

**Comment by EJGamer04** [comment]
I updated to version 4.4.2 and the problem was solved. Looks like was an issue but was fixed. Thanks.
