### ISSUE TITLE
timestamps schema option doesn't work on embedded subdocuments (tested in array)

### ISSUE THREAD

**Issue by jeremyml** [Automattic/mongoose#4049]
The mongoose timestamps schema option feature does not create a createdAt or updatedAt field for subdocuments.  I tested for subdocuments in an array only.  This is the schema feature I am referring to: http://mongoosejs.com/docs/guide.html#timestamps

**Comment by hymloth** [comment]
Yes I can verify that too

**Comment by vkarpov15** [comment]
Will take a look. I'm pretty sure we didn't think of this use case when we implemented timestamps :)

**Comment by vkarpov15** [comment]
@jeremyml @hymloth can you guys provide a code sample that reproduces the issue you're seeing? I added some test cases above to cover this case, because we didn't have coverage for it, and everything seems to work as expected...

**Comment by hymloth** [comment]
```
var childSchema = new mongoose.Schema({
  senderId: {type: String}
},{
    timestamps:true,
  toObject: {
    virtuals: true
  },
  toJSON: {
    virtuals: true
  }
});

var parentSchema = new mongoose.Schema({
  children: [childSchema],
},{
  timestamps:true,
  toObject: {
    virtuals: true
  },
  toJSON: {
    virtuals: true
  }
});

var Parent = mongoose.model('Parent', parentSchema);
var Child = mongoose.model('Child', childSchema);

Parent.find({}).remove()
Child.find({}).remove()

var b1 = new Parent({children:[{senderId:"1"}]})
b1.save(function(err, d){
  Parent.findOne({_id:d._id}).then(function(res){
    console.log(1, res) // contains timestamps
  })
})

var b2 = new Parent()
b2.save(function(err, d){
  Parent.findOneAndUpdate({_id:d._id}, {$push:{children: {senderId:"234"}}}, {new:true, fields:{children: {$slice: -1}}}).exec().then(function(res){
    console.log(2, res) // doesn't contain timestamps (shouldn't?)
  })
})
```

**Comment by vkarpov15** [comment]
Ah ok its an issue with findOneAndUpdate and timestamps, got it.

**Comment by Jeff-Lewis** [comment]
Is this relevant? [drudge/mongoose-timestamp Adding support for mongoose 4.0.1 findOneAndUpdate hooks.](https://github.com/drudge/mongoose-timestamp/commit/aad9a7fe65962a2f11f162083c5a666fdd9ad899)

**Comment by jeremyml** [comment]
@vkarpov15 by the way, thanks for all the work you do on Mongoose.  It's really great.

**Comment by vkarpov15** [comment]
@Jeff-Lewis somewhat relevant - great find but I don't think that will help with embedded subdocuments because query middleware only gets fired on the top-level document...

@jeremyml thanks for your kind words, I appreciate it :beers:

**Comment by joaoreynolds** [comment]
For what it's worth, I had the same issue not only when trying `findOneAndUpdate` but also just `update` when using `$push` (just like in the example above), so I have to fallback to using Mongoose's `.push()` method.

Thanks!

**Comment by vkarpov15** [comment]
There will be a rudimentary fix for this in 4.5.9, however, it will only work if the path is _explicitly_ specified in the update.

```javascript
var childSchema = new Schema({ name: String }, { timestamps: true });
var parentSchema = new Schema({ child: childSchema });
var Parent = mongoose.model('Parent', parentSchema);

// In 4.5.9, these 2 are equivalent
Parent.update({}, { $set: { child: { name: 'Luke' } });
Parent.update({}, { $set: { child: { name: 'Luke', createdAt: new Date(), updatedAt: new Date() } });

// Should set `child.updatedAt` as well but will *not* do so in 4.5.9
// Supporting this is pretty tricky, so comment on https://github.com/Automattic/mongoose/issues/4412 if you want this feature
Parent.update({}, { $set: { 'child.name': 'Luke' } });
```

**Comment by msupetran** [comment]
Can't seem to figure out how to do it using $push.

**Comment by vkarpov15** [comment]
@msupetran code sample please?

**Comment by msupetran** [comment]
@vkarpov15, I was trying to add to an nested collection/array using $push but the time stamps weren't added (before the fix). Now I switched to using .push() method. I have in my code something similar to this:

`function giveBirth(parentId, child) {
    Parent.findById(parentId, function(err, parent) {
        parent.children.push(child);
        parent.save();
    })
}`

But I believe it is two (2) separate database calls right (select and update)? I need to do it using the .update method if I want a single call to the database. In your 'rudimentary fix' you're just setting the value of an object (not adding to a collection). Is this the right way of doing it using $push:

`function giveBirth(parentId, child) {
    Parent.update({ _id: parentId }, { $push: {  children: child } });
}`

I'm fairly new to Mongoose and MongoDB in general. Great work btw!

**Comment by vkarpov15** [comment]
Yep that looks like the right way, and yep find then save is 2 separate database calls, so it's faster to just do update if you can

**Comment by nelsonlarocca** [comment]
any update about pushing and timestamps ?

**Comment by vkarpov15** [comment]
@nelsonlarocca yes, we added it years ago

**Comment by AlbertHambardzumyan** [comment]
I'm experiencing a similar issue with child of child

```
const JournalSchema = new mongoose.Schema({
  message: {type: String},
}, {timestamps:true})

const ProductSchema = new mongoose.Schema({
  name: {type: String},
  journal: [JournalSchema]
}, {timestamps:true})

var LoTSchema = new mongoose.Schema({
  products: [ProductSchema],
}, {timestamps:true})

const LotsModel = mongoose.model('LoTs', LoTSchema)

const payload = {
  name: 'mock-name',
  journal: [{message: 'mock-message}]
}

  function addProductIntLot (id, payload) {
    const conditions = { _id: id }
    const update = { $push: { products: payload } }
    const options = { new: true, runValidators: true, fields: { products: { $slice: -1 } } }

    return LotsModel.model.findOneAndUpdate(conditions, update, options)
  }


journal entry never gets createdAt & updatedAt fields.

**Comment by vkarpov15** [comment]
@AlbertHambardzumyan please open a new issue with detailed code samples. Posting "me too" on a long closed issue isn't helpful.
