### ISSUE TITLE
saving an object cointaining an array of arrays throws errors

### ISSUE THREAD

**Issue by dpaczewski** [Automattic/mongoose#4059]
Hi guys.

I'm new to Mongoose so maybe I'm doing something wrong. What I would like to achieve is sth like this: I have a schema which contains an array object which should contain arrays with nested objects. The business logic is that the "big array" contains options to complete a taks (subarrays) and these options contain conditions which you need to fullfill to complete given option.

It looks more or less like this:

`var mongoose = require('mongoose').set('debug', true);

var conditionDetailsSchema = mongoose.Schema({
	type : String,
	confirmation: String,
	message : String,
	attributes : {
		attribute : String,
		value : String
	}
});

// **Notice:** this is Schema([{ }]), not Schema ({ })
var challengeOptionSchema = mongoose.Schema([{
	id : Number,
	type : String,
	name : String,
	desc : String,
	details : [conditionDetailsSchema]
}]);

var challengeSchema = mongoose.Schema({
	options: [challengeOptionSchema]
});
`

**In NodeJS:**

module.exports = mongoose.model('Challenge', challengeSchema);

**Then I get the JSON object through REST API, let's say it's something like this:**

`var options = req.body.options;`

**When I print the value of _options_ using JSON.stringify I get something like this:**

> [[{"id":1,"name":"option_name_1","desc":"option_description_1","details":[],"$$hashKey":"object:14"}],[{"id":1,"name":"option_name_2","desc":"option_description_2","details":[],"$$hashKey":"object:20"}]]

**Then I try to assgn the value of options to the mongoose model:**

var challenge = new Challenge({
		if(options && options.length>0) {
			var i = 0;
			for (i; i < options.length; i++) {
				challenge.options.push(options[i]);
			}
		};
});

And finally I do challenge.save.

**When I do it with this approach I get a message saying:**

{ [ValidationError: Challenge validation failed]
  message: 'Challenge validation failed',
  name: 'ValidationError',
  errors: 
   { 'options.0._id': 
      { [CastError: Cast to ObjectID failed for value "[object Object]" at path "_id"]
        message: 'Cast to ObjectID failed for value "[object Object]" at path "_id"',
        name: 'CastError',
        kind: 'ObjectID',
        value: [Object],
        path: '_id',
        reason: undefined },
     'options.1._id': 
      { [CastError: Cast to ObjectID failed for value "[object Object]" at path "_id"]
        message: 'Cast to ObjectID failed for value "[object Object]" at path "_id"',
        name: 'CastError',
        kind: 'ObjectID',
        value: [Object],
        path: '_id',
        reason: undefined } } }

It is kind of strage since there should not be an __id_ field in the options array (they are not models/separate documents with their own structure in the database).

I tried a more simple approach instead of loop (so direct assignment of the "options" object to the "options" in the model). 

The challenge object before challenge.save looks like this:
{
options: 
   [ { _id: 570a8d31d548b9000f6efcc7 },
     { _id: 570a8d31d548b9000f6efcc6 } ],
  _id: 570a8d31d548b9000f6efcc5
}

Is there a problem with the schema definition or is there something wrong with the driver?

Thank you in advance,
best regards,
D. Paczewski.

PS: using mongoose 4.4.11

**Comment by vkarpov15** [comment]
So mongoose subdocs get _ids by default, unless you set the _id option to false for the schema. Try that and see if that helps

**Comment by vkarpov15** [comment]
No response for a while, I'm gonna assume the above comment fixed your issue :)
