### ISSUE TITLE
If findOne({_id}) doesn't match any result, does it throw an Error instead of null?

### ISSUE THREAD

**Issue by Kaijun** [Automattic/mongoose#4060]
I found a weird behaviour of findOne,

if i'm querying with field `_id`:  `findOne({_id})`, and if no results match the _id,  it will throw an `CastError` instead of `null`?

But if i try querying other fields,  e.g. `findOne({title})`, the result will be `null` indeed. 

Why does it have two different behaviours?

**Comment by vkarpov15** [comment]
The CastError case happens when the _id in the query is something that doesn't look like a mongodb objectid. Mongoose casts your queries to match your schema, so you can use a string instead of an objectid for instance. If there's a CastError, mongoose won't execute the query.
