### ISSUE TITLE
not expresive information if instead an inline declaration you use a variable

### ISSUE THREAD

**Issue by mtavano** [Automattic/mongoose#4061]
Today i found a really weird problem using mongoose (on my personal opinion)

i have 4 collections with the same base pattern but anyone represent different things.
I declared the same base in a file called base.js and then I imported the file into another one as the snippets can show

```js
// base.js
export const base = {
  id: { type: Number, required: true },
  sent_at: { type: Date, required: true, default: Date.now()},
  received_at: { type: Date, required: false },
  user_email: { type: String, required: true },
}

export default base
```

```js
// budget.js
import mongoose from 'mongoose'

import base from './budget'

const schema = new mongoose.Schema()
const budgetModel = mongoose.model('budget', schema)

class Budget {
  constructor (data) {
    this._data = data
    this._budget = new budgetModel(this._data)
  }
...
```
after that when i was testing I figured out that model was not the expected. after a few hours i change the schema declaration by this way and everything works well

```js
import mongoose from 'mongoose'

import base from './budget'

const schema = new mongoose.Schema({
  id: { type: Number, required: true },
  sent_at: { type: Date, required: true, default: Date.now()},
  received_at: { type: Date, required: false },
  user_email: { type: String, required: true },
})
const budgetModel = mongoose.model('budget', schema)

class Budget {
  constructor (data) {
    this._data = data
    this._budget = new budgetModel(this._data)
  }
...
```

schema declaration should work with both cases or at leat throw an error

**Comment by vkarpov15** [comment]
In the first case you're just declaring a blank schema and not using `base` at all. Using a variable in schema constructor is perfectly valid.
