### ISSUE TITLE
how to get multiple counts on multiple fields in mongoose query

### ISSUE THREAD

**Issue by aniinprni** [Automattic/mongoose#4062]
Hi,

I am using ``mongoose`` in my node js application. There is hotel schema with fields ``starRating``, ``hotel groups`` etc.. For example starRating is having rating values from ``1-5`` stars.

I need to retrieve the counts of each starRating hotels. i am able to achieve it by using ``aggregation`` by below query.

```
hotelData.aggregate(
					 [
					  	
					     { $group : { _id : "$hotel.basicInfo.starRating", starCount: { $sum: 1 }  }}
					  	
					 ]
					
					).exec(function(err,data){
						starRatingCount = data;
						console.log("this is data aggregate:",data);
						
						callback();
					});  
				  },
```
 Now i need to retrieve each hotel group counts along with each starRating counts. How can i achieve this in one single query? Please help me out

Thanks in advance

**Comment by aniinprni** [comment]
Hi,

Is there any update on this?

**Comment by vkarpov15** [comment]
What do you mean by one single query, do you mean without the aggregation framework?

**Comment by Daimonos** [comment]
Could you do a complex key in your grouping?
```
hotelData.aggregate(
                     [

                         { $group : { _id : {starRating:"$hotel.basicInfo.starRating", hotelGroup:"$hotel.basicInfo.hotelGroup"},  starCount: { $sum: 1 }  }}

                     ]

                    ).exec(function(err,data){
                        starRatingCount = data;
                        console.log("this is data aggregate:",data);

                        callback();
                    });
```
