### ISSUE TITLE
chaining "count" after "distinct" does not apply the distinct filter

### ISSUE THREAD

**Issue by itlodge** [Automattic/mongoose#4063]
Hi,
    the result of 
```javascript
myModel.distinct('myfield', query).exec(function (err, docs) {
  console.log(docs.length);
}
```
and
```javascript
myModel.distinct('myfield', query).count().exec(function (err, count) {
  console.log(count);
}
```
are not the same.

It seems that chaining "count" after "distinct" does not apply the distinct filter. And there is a disccusion in [stackoverflow](http://stackoverflow.com/a/12452200/1667722)

**Comment by vkarpov15** [comment]
Count and distinct are separate query operations, there's no way for mongoose to tell mongodb to return the count of the result of distinct. Just use `.length` on the result of distinct.

**Comment by muhammadfaizan** [comment]
@vkarpov15 but that doesn't solve the problem in case of `skip` and `limit`

**Comment by vkarpov15** [comment]
@muhammadfaizan can you please clarify? Skip and limit don't make sense in the context of `count` and `distinct`

**Comment by muhammadfaizan** [comment]
@vkarpov15 i was saying, that if i take `.lenght` of returned result then it would create a false `length` that could be its limit

**Comment by vkarpov15** [comment]
@muhammadfaizan I don't understand, can you please clarify with some code samples?

**Comment by muhammadfaizan** [comment]
apologize, i thought this was possible to do something like this

```
myModel.distinct(someFlter, property).limit(lim).skip(sk)
```

However this code throws error that `limit` can't be applied to distinct

**Comment by vkarpov15** [comment]
Yeah I'd argue that's a reasonable thing to do, because limit and skip don't make sense for distinct as far as I know.
