### ISSUE TITLE
Add maxTime option to all queries

### ISSUE THREAD

**Issue by tomgrossman** [Automattic/mongoose#4066]
I would like to add the option for maxTime(ms) for **all** models queries (find, update, findOneAndUpdate, etc..).

for example:

`A.findOneAndUpdate(id, updateObject, {maxTime: 1000}}, callback)`

**Comment by vkarpov15** [comment]
Write a plugin, use query middleware

**Comment by tomgrossman** [comment]
Hi @vkarpov15 ,
After further investigation about this issue, it seems that this option exists, but not in the API.
I added `maxTime: x` to the options object in `findOneAndUpdate` function, and I saw that it is being converted to `maxTimeMS` option in the `mquery.js` file in this function:
`Query.prototype.maxTime = function (v)` (line 1359).

So it looks like this option is working, am I wrong?
it doesn't appear in the API in the available options.

**Comment by vkarpov15** [comment]
@tomgrossman yep should be working, just added it to the docs.

**Comment by tomgrossman** [comment]
So there is no need for a plugin, right? Should be closed.

**Comment by vkarpov15** [comment]
I think the original issue was "ability to set maxTimeMS for all queries" which is a task for a plugin. Adding the option to the docs is separate.

**Comment by tomgrossman** [comment]
@vkarpov15 sorry I don't understand. I said before that this option already exists but was only missing in the docs. So there is no need for a plugin. Am I wrong?

**Comment by vkarpov15** [comment]
The plugin is for setting max time ms for all queries at once, like `mongoose.use(maxTimeMSPlugin(5000))` will make it so that all queries have maxTimeMS of 5000 by default. I thought that was the original use case, no?

**Comment by tomgrossman** [comment]
@vkarpov15 no, the original case was the option to add this timeout for every query. as an option.
but this is already available.

**Comment by vkarpov15** [comment]
Ok then we can close this issue :)

**Comment by santimendoza** [comment]
Hey just to know, `find`, `findOne` does not have the maxTime option? I can't see it in the documentation, neither seems to work.

**Comment by vkarpov15** [comment]
@santimendoza the option is maxTimeMS http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#findOne we will add it to the mongoose docs

**Comment by freewil** [comment]
> The plugin is for setting max time ms for all queries at once, like mongoose.use(maxTimeMSPlugin(5000)) will make it so that all queries have maxTimeMS of 5000 by default. I thought that was the original use case, no?

@vkarpov15 I was just looking to do this - would the plugin approach still be the best way to achieve global query timeouts in latest mongoose v5?

**Comment by freewil** [comment]
bump

@vkarpov15 I was just looking to do this - would the plugin approach still be the best way to achieve global query timeouts in latest mongoose v5?

**Comment by vkarpov15** [comment]
@freewil yes it would. I'm going to be writing a blog post on maxTimeMS next week that you should keep an eye out for. MaxTimeMS has some caveats

**Comment by natanavra** [comment]
@vkarpov15 Hi!
Seems docs are not updated, as `Query.prototype.maxTimeMS` errors with `is not a function`
`Query.prototype.maxTime` works as expected.

**Comment by vkarpov15** [comment]
@natanavra can you write a script that demonstrates this issue and clarify which version of Mongoose you're using? [Here's the `maxTimeMS()` function in our code](https://github.com/Automattic/mongoose/blob/62afee6273d6ada21cbb797749d38fb94709c2b8/lib/query.js#L1408-L1410)

**Comment by natanavra** [comment]
@vkarpov15 using Mongoose 5.0.16

Here's an example:
```
return await model
  .find(query, null)
  .sort(sort)
  .maxTime(constants.maxQueryMS)
  .hint(model.getHint())
  .limit(constants.maxEvents)
  .cache(10)
  .catch(err => {
     logger.warn({err}, 'events.find failed');
  });
```

**Comment by Fonger** [comment]
@natanavra You can't use that in mongoose 5.0.16. It was added in mongoose 5.2.6

I added maxTimeMS alias to maxTime in [mquery](https://github.com/aheckmann/mquery) v3.1.1, an underlying library of mongoose. This was introduced since mongoose@5.2.6, which used this version of mquery.

https://github.com/aheckmann/mquery/pull/105
https://github.com/aheckmann/mquery/commit/42499d33ecca1917e754b785a2381928638b566d

**Comment by natanavra** [comment]
@Fonger Ahh thanks for letting me know
There is not mention of it in the docs https://mongoosejs.com/docs/api.html#query_Query-maxTimeMS
And I never really accessed previous 5.x.x docs since it's usually the latest.

**Comment by GeniusBrother** [comment]
I can't find maxTimeMSPlugin, so is this just an example? @vkarpov15

**Comment by vkarpov15** [comment]
@GeniusBrother we added a global and connection level `maxTimeMS` option in 5.6.0.

```javascript
mongoose.set('maxTimeMS', 3000);
```

Or:

```javascript
const db = mongoose.createConnection(uri);

db.set('maxTimeMS', 3000);
```

**Comment by vkarpov15** [comment]
See [`Connection#set()`](https://mongoosejs.com/docs/api/connection.html#connection_Connection-set) and [`Mongoose#set()`](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set)
