### ISSUE TITLE
`findOne` query can trigger "MongoError: Projection cannot have a mix of inclusion and exclusion."

### ISSUE THREAD

**Issue by letsgolesco** [Automattic/mongoose#4067]
My 'Account' schema has the `select: false` option for certain fields (e.g. `password`). It looks like the behavior for this option is to add the projection `{ field: 0 }` when no projection is specified in the query.

Using `findOne` with a projection selecting one field (e.g. `{ status: 1 }`) I got the MongoError "Projection cannot have a mix of inclusion and exclusion". Debugging, I noticed that mongoose applies a projection that looks like this: `{ password: 0, status: 1 }`.

Calling `find` with the same options yields the desired projection: `{ status: 1 }`.

[Using version 4.4.12]

**Comment by letsgolesco** [comment]
I went a little further and it looks like this can be triggered with either `find` or `findOne`.

The defining factor seems to be that I'm calling `this.find(query).select('status').lean().exec()` from inside a post 'findOneAndUpdate' hook (the issue doesn't occur when I make the same call from within a post 'update' hook).

**Comment by letsgolesco** [comment]
Managed to work around this by calling `this.model.find()...` rather than `this.find()`.

Is there a recommended course of action for calling query/update methods from within middleware hooks?

**Comment by vkarpov15** [comment]
Yeah you're right, you need to call `this.model.find()`. That's because, in query middleware, `this` refers to the actual query, so when you do something like:

```javascript
schema.post('findOneAndUpdate', function(next) {
  this.find({}).select('status').lean().exec(function(error, res) {
    console.log(error, res);
    process.exit(0);
  });
});
```

You re-execute the query with all the state the previous query built up. You should use `this.model.find()` to create a new query instead.
