### ISSUE TITLE
is it possible to return ALL ids + populated fields when populating with limit?

### ISSUE THREAD

**Issue by smirea** [Automattic/mongoose#4068]
If I have a model with:

```js
mongoose.model('Person', new mongoose.Schema({
    name: String,
    siblings: {type: 'ref', ref: 'Person'}
})
```

And say I have an entry `Joe` with 20 siblings, if I do 

```js
Person.find({
    name: 'Joe'
})
.populate({
    path: 'siblings',
    options: {limit: 5},
})
```

I will get 5 siblings documents back and the remaining 15 IDs are lost
Is it possible to request the unpopulated IDs as well? I was hoping there is an option for that but the docs don't specify

**Comment by vkarpov15** [comment]
Unfortunately not with the current implementation of populate - if you ask to populate and limit to 5, mongoose won't return the remaining ids. No good way to really do that with the current implementation of populate either, because either a path is fully populated or not populated.
