### ISSUE TITLE
not run validator on findByIdAndUpdate

### ISSUE THREAD

**Issue by hubsn** [Automattic/mongoose#4070]
I use mongoose 4.4.11. Let me explain.

breifed schema follows :
```javascript

let inspectHistorySchema = new Schema({
  order: { type: Number, min: 0, max: 50 }

let mapSchema = new Schema({
    inspectHistory : [ inspectHistorySchema ]
})

let map = mongoose.model('Map', mapSchema)
```

and I write code which follows :
```javascript
let r = await Map.findByIdAndUpdate(
    req.params.mapId,
    { $push: { inspectHistory: req.body } },
    { new: true, runValidators: true }
  )
```

I wished the order can not be passed by min and max validator, but passed. 

Would you check this for moment? I will appreciate that check this issue. thanks.

**Comment by vkarpov15** [comment]
[Update validators only run on `$set` and `$unset`, not `$push`](http://mongoosejs.com/docs/validation.html#update-validators-only-run-on-specified-paths). We plan on implementing support for that soon, but hasn't happened yet. See issue #2933.

**Comment by hubsn** [comment]
@vkarpov15 Thanks for check. I wish to support that.

**Comment by AdamElHassan** [comment]
Is this fixed? because my validators are still not running after a $push

**Comment by vkarpov15** [comment]
@AdamElHassan did you [turn on the `runValidators` option](https://mongoosejs.com/docs/validation.html#update-validators)?

**Comment by AdamElHassan** [comment]
Yes i did. I workedaround it now with a $set, but using $push would be the better way to do it ofcourse
