### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by SimoneTaliercio** [Automattic/mongoose#4071]
Hi all : )

My project contains a multi-level Schema structure (A <-B <-C). We achieved that level of inheritance thanks to a third party module called mongoose-schema-extend.

Everything was fine with mongoose 3.x but we are migrating now to 4.x . Unfortunately we get the following exception:

`TypeError: Cannot read property 'apply' of undefined at q.reduce.post (/Users/simone/Enviroments/nodejs/target-manager-server/node_modules/mongoose/lib/document.js:1764:21)
      at Array.reduce (native)
      at model.Document.$__registerHooksFromSchema (/Users/simone/Enviroments/nodejs/target-manager-server/node_modules/mongoose/lib/document.js:1762:18)
      at model.Document (/Users/simone/Enviroments/nodejs/target-manager-server/node_modules/mongoose/lib/document.js:79:8)
      at model.Model (/Users/simone/Enviroments/nodejs/target-manager-server/node_modules/mongoose/lib/model.js:42:12)
      at new model (/Users/simone/Enviroments/nodejs/target-manager-server/node_modules/mongoose/lib/model.js:3096:11)
      at Object.createIm`

I had a look at mongoose/lib/document.js line 1762 and I found out that commenting the IF block in the following code then would fix the issue.

`// we are only interested in 'pre' hooks, and group by point-cut
  var toWrap = q.reduce(function(seed, pair) {
    if (pair[0] !== 'pre' && pair[0] !== 'post' && pair[0] !== 'on') {
      _this[pair[0]].apply(_this, pair[1]);
      return seed;
    }`

What does that code ? Any workaround I can use from my application in order to be compliant with that check ?

Thanks a lot for your support! :_)

**Comment by SimoneTaliercio** [comment]
I have an updated on this. It seems that moongose-extend-schema is working properly till a 3rd level of extension, but at the 4th it breaks. E.g. A <- B <- C is ok, but A <- B <- C <- D is not working.

The module is using the framework concept (pre-save hook): I don't understand why it breaks at third level of the chain :-/

**Comment by vkarpov15** [comment]
Honestly mongoose-schema-extend is a broken module and it's a minor miracle that it works at all. Schema inheritance is much easier if you just use ES2015 class syntax:

```javascript
class PersonSchema extends mongoose.Schema {
  constructor(obj, options) {
    super(obj, options);
    this.add({ name: String });
  }
}

class EmployeeSchema extends PersonSchema {
  constructor(obj, options) {
    super(obj, options);
    this.add({ department: String });
  }
}

const employeeSchema = new EmployeeSchema();
const Employee = mongoose.model('Employee', employeeSchema);

console.log(new Employee({ name: 'Val', department: 'test' }));
```

**Comment by SimoneTaliercio** [comment]
Thanks for your support, vkarpov. I share your opinion. Actually I'm in doubt when going for the ES6 class inheritance approach or simply collapse my structure in max. two level so that i can use the model.discriminator approach. Any thought on that ? :)

**Comment by vkarpov15** [comment]
Really depends - discriminators are great if you want to store different types of documents in one collection. My usual check is "do I want to query across all types of documents as well as one specific type?". For instance, you might want to query all `People` as well as just by `Employee`, so in that case discriminators are great. However, if you don't need that it's typically better to not use discriminators, because smaller collections are usually better for performance.
