### ISSUE TITLE
full-text search on inherited schemas

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#4072]
Hi, I would bring the attention on this stackoverflow question:
http://stackoverflow.com/questions/36056594/mongodb-error-failed-to-use-text-index-to-satisfy-text-query

I know it's a huge post, basically I'm trying to make a full-text search on 4 subschemas together.
The compound text index is defined `myRootSchema.index({ "_type": 1, "$**": "text" })`
_type is the discriminatorKey.

This query should work since _type is indeed a discriminatorkey, so mongoose should 'autofill' that, but it doesn't.
```
Model
    .find(
        { $text : { $search :req.query.q } }

    )
    .exec(function(err, data) {
        if(err)res.json(err)
        res.json(data)
    });
```
trying this query I get the error `failed to use text index to satisfy $text query`.
A temporary solution could be explicitly fill `_type` and use parallel from async module and query each subschema like this
```
 async.parallel([
            function(callback){
                caseNote
                    .find({_type:'FIRST_TYPE',$text : { $search :req.query.q } })
                    .exec(function(err, data) {
                        if(err) {
                            callback(err);
                        }
                        else {
                            callback(null, data);
                        }

                    });
            },
.....#query on each other type..#
]);
```
but I don't think there is a proper way to paginate those results..so I'm stuck here.

**Comment by vkarpov15** [comment]
In your example, is `Model` the base model? If so, the discriminator won't get 'autofilled' like you said, because when you query by the base model the `_type` field won't get set.

Try doing:

```javascript
Model
    .find(
        { _type: { $in: ARRAY_OF_ALL_TYPES } },
        { $text : { $search :req.query.q } }
    )
```

**Comment by alfredopacino** [comment]
Yes is the base model.
I tried your query, it fails with the error: `failed to use text index to satisfy $text query (if text index is compound, are equality predicates given for all prefix fields?)`

I have a doubt: as I said I have 4 subschema, with the text-index like I defined (a compound text-index with the discriminator on base model), can you ensure me the peculiar string fields of each subschema are indexed and 'contributes' to a full-text search correctly?

**Comment by alfredopacino** [comment]
MORE DETAILS: 
this is my current (very badly paginable..basically I can paginate the resulting array after the queries) async solution

```
var async = require('async');
router.get('/',function(req,res,next){
        async.parallel([
                function(callback){
                    model
                        .find({_type:'DOC_A',$text : { $search :req.query.q } })
                        .exec(function(err, data) {
                            if(err) {
                                callback(err);
                            }
                            else {
                                callback(null, data);
                            }

                        });
                },
                function(callback){
                    model
                        .find({_type:'DOC_B',$text : { $search :req.query.q } })
                        .exec(function(err, data) {
                            if(err)
                                callback(err);
                            else
                                callback(null, data);
                        });
                },
                function(callback){
                    model
                        .find({_type:'DOC_C',$text : { $search :req.query.q } })
                        .exec(function(err, data) {
                            if(err)
                                callback(err);
                            else
                                callback(null, data);
                        });
                },
                function(callback){
                    model
                        .find({_type:'DOC_D',$text : { $search :req.query.q } })
                        .exec(function(err, data) {
                            if(err)
                                callback(err);
                            else
                                callback(null, data);
                        });
                }
            ],
            function(err, results){
//I should paginate here
                res.json([].concat(results[0],results[1],results[2],results[3]));
            });
});
```

**Comment by vkarpov15** [comment]
Try setting mongoose debug mode to true, `require('mongoose').set('debug', true)` and see what query is actually being sent.

Also, I suspect this may be another case of mongoose reversing object keys. Try:

```javascript
Model
    .find({
        { $text : { $search :req.query.q } }
        { _type: { $in: ARRAY_OF_ALL_TYPES } }
    })
```

**Comment by alfredopacino** [comment]
Well I guess the $text and _type objects are indeed reversed:

this is what the debug prints with **$text first**
```
Mongoose: caseNotes.find({ _type: { '$in': [ 'caseNoteA', 'caseNoteB', 'caseNoteC', 'caseNoteD' ] }, '$text': { '$search': 'def' } }) { fields: undefined }  

```
this is what it prints with _type first
```
Mongoose: caseNotes.find({ '$text': { '$search': 'def' }, _type: { '$in': [ 'caseNoteA', 'caseNoteB', 'caseNoteC', 'caseNoteD' ] } }) { fields: undefined }  

```

it both ways the query fails :(

**Comment by alfredopacino** [comment]
maybe it could help a minimal project to reproduce the error?

**Comment by vkarpov15** [comment]
Do you get this error when you execute the query in the mongodb shell?

**Comment by alfredopacino** [comment]
I created this app for this fulltext issue and this issue too https://github.com/Automattic/mongoose/issues/4085

**Comment by vkarpov15** [comment]
Hmm so looks like we can rule this out as a mongoose issue - mongoose is sending the correct query, it's just that mongodb [does not support `$in` for using compound indexes with `$text`](https://jira.mongodb.org/browse/SERVER-13801). That's an unfortunate edge case that I wasn't aware of :(

In other words, the below is valid:

```javascript
Model
    .find({
        { _type: 'Employee' },
        { $text : { $search :req.query.q } }
    })
```

but the below is not:

```javascript
Model
    .find({
        { _type: { $in: ['Employee'] } },
        { $text : { $search :req.query.q } }
    })
```

because the `_type` query uses `$in` rather than "equality matching".

One way to work around this would be to not use an index on `_type` - then this should work just fine.

**Comment by alfredopacino** [comment]
without `_type` as index the inherited model fields won't compete in a full-text search, am I right?

**Comment by vkarpov15** [comment]
I don't think so, mongodb should still be smart enough to use the text index

**Comment by alfredopacino** [comment]
well, I defined a compound index because indeed I want to index all the string fields fro base and child model.

Can you explain so what's the difference in this case between 
`myRootSchema.index({ "_type": 1, "$**": "text" })`

and `myRootSchema.index({ "$**": "text" })`

**Comment by vkarpov15** [comment]
The queries won't be quite as fast because you don't have the compound index, but because compound text indexes don't support $in you'll be able to use $in with _type again. Which is better depends on your query pattern, if you need to use $in with _type a lot then you're probably better off without the compound index.

**Comment by alfredopacino** [comment]
Please re-read my first post.
I need to perform a fulltext search on the 4 subschemas togheter.
I do NOT need $in with _type in my queries, I don't care which _type the document is. I just need to query all types.

**Comment by vkarpov15** [comment]
There's two ways to do that, either 4 queries in parallel like you mentioned, or one query with `$in`. My guess would be that the `$in` query would be slightly faster, and I also wouldn't want to use compound text indexes because their API is pretty brittle as we discovered in this thread :)

**Comment by alfredopacino** [comment]
I'm sorry maybe I still don't get something here.
I made first a compound index on the root model because on stackoverflow someone said it was the right way to index all the inherited field.
Now you said (https://github.com/Automattic/mongoose/issues/4072#issuecomment-215589613), and I'm pretty sure it's true (still testing) an index like
`myRootSchema.index({ "$**": "text" })`

index correctly the inherited model fields too!
WHY do I need to perform a fulltext search including the _type field? just for performance?

**Comment by vkarpov15** [comment]
It'll definitely index all the inherited fields, `$**` has nothing to do with mongoose, it's all at the mongodb level, so it doesn't even know about discriminators.

Yeah, building a compound index and querying by the `_type` field would be all about performance - if you don't need that extra performance, I wouldn't recommend bothering to figure it out.
