### ISSUE TITLE
mongoose-text-search is not working

### ISSUE THREAD

**Issue by jatinseth2007** [Automattic/mongoose#4074]
I have a already built old project on nodejs where I am using MongoDb to store data. Mongodb version is 2.4

The problem is I am running a text-search on a collection but it's never return anything which means console.log(arguments); never get print anything

It's to inform you guys that I am able to run db.socialposts.runCommand( "text", { search: "accessories",limit: 1 } ) on mongo terminal and getting results very fast

```javascript
var options, search;

options = {
limit: 1
};

search = 'accessories';

console.log(search);

SocialPost.textSearch(search, options, function(err, out) {
console.log(arguments);
return true;
});
```

It's Schema is

```javascript
var schema;
schema = new mongoose.Schema({
entity_id: {
type: mongoose.Schema.Types.ObjectId,
required: true
},
social_id: {
type: String,
required: true
},
type: {
type: String,
required: true
},
app: {
type: String,
required: true
},
date: {
type: Date,
required: true
},
url: {
type: String,
required: true
},
post: {
type: String
},
title: {
type: String
},
image: {
type: String
},
video: {
type: String
},
hashtags: [String]
}, {
strict: 'throw'
});
```

And Index is

```javascript
schema.index({
type: 1,
social_id: 1
});

schema.index({
type: 1,
entity_id: 1,
date: 1
});

schema.index({
title: 'text',
post: 'text'
});
```

**Comment by jatinseth2007** [comment]
I have put this issue on stackoverflow also

http://stackoverflow.com/questions/36617113/mongoose-text-search-is-not-working

**Comment by vkarpov15** [comment]
@jatinseth2007 which version of mongoose are you using?

**Comment by jatinseth2007** [comment]
Following are the entries in my package.json

 "mongoose": "3.8.x",
 "mongoose-text-search": "0.0.x"

**Comment by vkarpov15** [comment]
Looks like this was fixed on SO
