### ISSUE TITLE
updateAt not updated when saving

### ISSUE THREAD

**Issue by mebibou** [Automattic/mongoose#4079]
Using version `4.3.7`, with a model set up with `timestamps: true`, I would just do a `save()` on a model and `updateAt` will be automatically updated. When I updated my packages, it fetched latest version `4.4.6` and some tests failed because the `updateAt` attribute would not be updated automatically

**Comment by vkarpov15** [comment]
Code samples please. We have test cases for timestamps that are passing, so it's not that timestamps are completely fried across the board.

**Comment by frasator** [comment]
I have the same issue, for me it started at version 4.3.11.
Tested it with mongo 2.6.x and 3.2.x.
In my case, some times it updates the timestamp but some times does not, I have to test more but maybe is some related to call the save method on a model instance without modifications.

**Comment by mebibou** [comment]
Oh my bad, thanks to @frasator comment I actually found out that sometimes the field is not modified and therefore the date is not updated, I missed your fix on not changing timestamp if nothing changes.
