### ISSUE TITLE
Why does Types.ObjectId.isValid(123) return true?

### ISSUE THREAD

**Issue by rubenstolk** [Automattic/mongoose#4083]
Perhaps isValid should always use `String(parameter)`?

**Comment by vkarpov15** [comment]
The definition of an object id is "12 arbitrary bytes", so technically any JavaScript number works, as does any string of length 12. See [the actual implementation](https://github.com/mongodb/js-bson/blob/f7efecc04240525931402116f881b5984af800c4/lib/bson/objectid.js#L247). If you want to enforce a length 24 hex string, which is the common string representation of a mongodb object id, just check for that using a regexp `/^[0-9a-fA-F]{24}$/`
