### ISSUE TITLE
query a base model on an inherited fields

### ISSUE THREAD

**Issue by alfredopacino** [Automattic/mongoose#4085]
I noticed a strange behaviour when I query a base model _for a inherited field_.

```
var rootSchema = mongoose.Schema({
    name:{type:String,required:true},
}, { timestamps: { createdAt: 'createdAt',updatedAt:'updatedAt' }, collection : 'caseNotes', discriminatorKey : '_type' });


var collectionASchema = rootModel.discriminator('collectionA', new Schema({
    referring:{type: ObjectId, ref: 'referring',autopopulate:true },
    plain_field:{type:String}
},{discriminatorKey : '_type'}) );

var referringSchema = new Schema({
    name:{type:String,required:true},
}, { collection: 'referrings' });
var referring = mongoose.model('referring',referringSchema);
```

This query doesn't work.
It works if I query on "plain_field" (type String) but it doesn't it I query "referring" (an ObjectId).
```
rootModel.find({referring:'56f1e6821e0c304418f2ed2f'})
        .exec(function(err, data) {
            if (err) {
                return res.status(400).send({
                    message: err
                });
            } else {
                res.json(data);
            }
});
```

**Comment by Daimonos** [comment]
Would you not need to create an ObjectId for the referring id?

```
var mongoose = require('mongoose');
...
rootModel.find({referring:mongoose.Types.ObjectId('56f1e6821e0c304418f2ed2f')})
        .exec(function(err, data) {
            if (err) {
                return res.status(400).send({
                    message: err
                });
            } else {
                res.json(data);
            }
});
```

**Comment by alfredopacino** [comment]
So are you implying a query on a base model for a inherited field should work, right?
I already tried the ObjectId creation, it doesn't work neither.
A query on a ref belongs to the base model works without the ObjectId creation.

**Comment by Daimonos** [comment]
I assumed from your question that querying for an inherited field should work as you said:

> It works if I query on "plain_field" (type String)

Which means that you should be able to query on referring

Try debugging with `console.log(rootModel.schema.paths)` and see if referring is in the list. If so, make note of it's instance. As per the statement though, I would expect it to be there

**Comment by alfredopacino** [comment]
> I assumed from your question that querying for an inherited field should work as you said:

yes, I was starting to think it's not supposed to work like I want, or it isn't a best pratice.

> Try debugging with console.log(rootModel.schema.paths) 
referring isn't in the list, why should be there? as I said referring belongs to a child schema.

**Comment by Daimonos** [comment]
I'm saying that I don't think it should have worked.
Is there a way you can provide an excerpt of the entire code with the working query and the non-working query?

**Comment by vkarpov15** [comment]
Try setting mongoose debug mode to true with `require('mongoose').set('debug', true);`. FWIW I think this is expected behavior - since `referring` is not a path on the model you're querying, the query will filter it out. You'd need to query by the `collectionA` model.

**Comment by alfredopacino** [comment]
I created this app for further investigation
https://github.com/alfredopacino/mongoose_project/blob/master/app.js

To reproduce the error:
- just refresh /init/ few times
- visit /posts and copy a "coauthor" id
- add it in the query in /search_ref
- just verify /search_ref doesn't work, but /search_string does.

**Comment by vkarpov15** [comment]
As a workaround you should manually cast to an objectid: `Post.find({coauthor:new mongoose.Types.ObjectId('571a97c72617c1a41d4b1bef')})`

**Comment by vkarpov15** [comment]
Yeah I dug into this, looks like its expected behavior. Mongoose doesn't remove nor cast fields that aren't in the schema for queries, and neither `coauthor` nor `coauthor_comment` are in the Post schema.
