### ISSUE TITLE
findOneAndUpdate does not update virtual attribute

### ISSUE THREAD

**Issue by hymloth** [Automattic/mongoose#4087]
```
var ASchema = new mongoose.Schema({
  photoId: {type: String}
},{
  toObject: {
    virtuals: true
  },
  toJSON: {
    virtuals: true
  }
});

ASchema.virtual('photo').get(function () {
  if (this.photoId)
    return "/uploads/" + this.photoId;
  return null
}).set(function (p) {
  this.photoId = p;
});


var A = mongoose.model('A', ASchema);
A.find({}).remove()


var a = new A()
a.save(function(err, d){
  A.findOneAndUpdate({_id:d._id}, {$set:{photo: "test1.jpg"}}, {new:true}).exec().then(function(res){
    console.log(2, res) // doesn't update photoId
  })
})
```

**Comment by Jeff-Lewis** [comment]
Virtual properties are designed to be virtual properties of the Model in memory and do not save to MongoDB, while findOneAndUpdate operates below the Model interface and works more directly with MongoDB as a CRUD operation.

[See Mongoose Guide](http://mongoosejs.com/docs/guide.html)

Do this instead:

``` javascript

var a = new A();
a.photo = 'test1.jpg';
a.save()
  .then(function(res){
      console.log(2, res);
  })
  .catch(function(err){
     console.err(err);
  });


```

**Comment by vkarpov15** [comment]
@Jeff-Lewis is right - findOneAndUpdate [currently bypasses setters and virtuals](http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate) and we don't have any plans to support this behavior atm. You should update `photoId` directly.

**Comment by vanchonlee** [comment]
- [ ] 

- 1.
