### ISSUE TITLE
getting duplicate while looping and saving.

### ISSUE THREAD

**Issue by nasr18** [Automattic/mongoose#4089]
Duplicate records are being inserted to the collection while looping through the collections. I'm using unique id to restrict duplicate record. But anyway its not working. Inserting duplicate records. Anyway to stop this duplicate record being inserted?? Actually i'm getting this duplicate record while doing `Cron Job`.

**Comment by vkarpov15** [comment]
Please provide a code sample, describing your code with prose doesn't really give me a good idea of what you're trying to do.

**Comment by nasr18** [comment]
```
var url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?';
request(url, function(error, response, body) {
    if (!error && response.statusCode == 200) {
        var mapapiresp = JSON.parse(body);
                async.each(mapapiresp.results, function(place, callback) {
                    placedetail.find({
                        $and:[{
                            'placedetails.place_id': place.place_id
                        }, {
                            $and:[{
                              'placedetails.geometry.location.lat': place.geometry.location.lat
                            },{
                              'placedetails.geometry.location.lng': place.geometry.location.lng
                            }]
                        }]
                    }, function(err, dupdata) {
                         if (dupdata.length == 0) {
                             // here i will insert new data into my mongodb.
                            // but my problem is that duplicate record is also inserting.
                         }
                    }, function(err) {
                         if (err) {
                            console.log('async err:', err);
                         }
                         console.log('addMasjidsCronCount:', addMasjidsCronCount);
                    });
               }
}
```
I'm filtering records using "place_id" and "locations lat & lng", but no use. Duplicates are getting inserted.

**Comment by vkarpov15** [comment]
Couple questions:

What is the unique id you're using?
What does the code you're using to insert look like?
Is the code you provided executed in a loop / executed multiple times?

**Comment by nasr18** [comment]
Answer for 1st question is: unique id's are `place_id` & `lat lng`.
2nd question's answer: using model.save() inside an async loop.

**Comment by vkarpov15** [comment]
Please provide example code, I still don't quite understand what your code is doing.

**Comment by nasr18** [comment]
pls check my above code. i have updated my code. 

My task is to get places from google map api and have to insert that into my db. Google will give max 60 places on hitting their api. I have to insert that places into my db if not already inserted. Unique id's are `place_id` and `lat, lng`. But anyway I'm getting duplicate records in my db. 

Hope you got it.

**Comment by nasr18** [comment]
@vkarpov15  please give solution for my problem. How do i get rid of duplicate records???

**Comment by nasr18** [comment]
> Because we rely on async operations to verify whether a document exists in the database, it's possible for two queries to execute at the same time, both get 0 back, and then both insert into MongoDB.

I think this is the problem. Asynchronous execution. How do i fix this??? @vkarpov15

**Comment by nasr18** [comment]
Still looking for answer.....

**Comment by nasr18** [comment]
@vkarpov15  have you fixed this??

**Comment by vkarpov15** [comment]
@nasr18 [`async.each()` runs your lookups in parallel, not in series](https://www.npmjs.com/package/async#eachcoll-iteratee-callback). This means that your code has a race condition - two locations can be running at roughly the same time, send the same query, get zero back, and both think it's safe to save. Use [`async.series()` instead](https://www.npmjs.com/package/async#seriestasks-callback)

**Comment by nasr18** [comment]
ok will try and let you know. @vkarpov15

**Comment by nasr18** [comment]
how do i loop through using `async.series()`? @vkarpov15

**Comment by vkarpov15** [comment]
See the async docs: https://www.npmjs.com/package/async#quick-examples
