### ISSUE TITLE
Using id() on Array of populated documents

### ISSUE THREAD

**Issue by siboulet** [Automattic/mongoose#4091]
We recently moved embedded subdocuments to their own collections and use query population. This works great, the only issue we are running into now is that MongooseArray are missing the id() method that MongooseDocumentArray have.

We worked around this by extending the MongooseArray mixins to add the id() method like so:

```js
mongoose.Types.Array.mixin.id = function(id) {
  return this.find(function(obj) {
    return obj._id && obj._id.equals(id);
  });
};
```

Suppose you maintain groups in a separate collection. You're app gets passed the User model that has its groups Array already populated, and you want to check if user is member of a specific group ID. Adding the id() method to Array allow for using this:

```js
var ADMIN_GROUP_ID = '571127a00698ba9200ca571b';
var adminGroup = user.groups.id(ADMIN_GROUP_ID);
```

Without id() mixin on MongooseArray you have to implement your own lookup using Array.find().

Is there a particular reason why MongooseArray don't have id()? Would you consider adding MongooseArray id() mixin?

**Comment by vkarpov15** [comment]
I think the reasoning is because Arrays can be of arbitrary type, whereas DocumentArrays are necessarily documents, but it just so happens that when you populate an array you still have an Array rather than a DocumentArray.

**Comment by siboulet** [comment]
This has been working for us for quite some time now

```js
mongoose.Types.Array.mixin.id = function(id) {
  return this.find(function(obj) {
    return obj._id && obj._id.equals(id);
  });
};

```

**Comment by vkarpov15** [comment]
Ok if it works then I'll close :+1:
