### ISSUE TITLE
Why does Document#update() return query object, not promise?

### ISSUE THREAD

**Issue by Jokero** [Automattic/mongoose#4095]
```js
Chart.findOne().then(chart => {
    const result = chart.update({ $set: { type: 'pie' } });
    console.log(result instanceof Promise); // false
    console.log(result instanceof mongoose.Query); // true
});
```

Expected behaviour for me: `chart.update()` should return promise, because we already know which object we want to update. It's very illogical to add additional search criteria in this situation. If you want to do it you can use `Model.update()`. What do you think?

**Comment by vkarpov15** [comment]
IMO this is the correct behavior - `chart.update()` is meant to be very thin syntactic sugar around `Model.update()`, don't want to add too much magic. Plus, the query builder can help you build updates as well as queries:

```javascript
chart.update({ type: 'pie' }).update({}, { flavor: 'cherry' }).update({}, { cost: 9.99 }, { upsert: true });
```

You can get a promise if you use `.exec()`, so I'm hesitant to make a backwards breaking change like this to save 7 characters unless there's a very good reason. Open to counter-arguments :)
