### ISSUE TITLE
Blank Connection and after use db.auth()

### ISSUE THREAD

**Issue by jorgecuesta** [Automattic/mongoose#4096]
Hi, first of all, this is not an issue, is a Question and of course sorry about my english skill.

I'm looking for a way to can create a blank connection to mongo and after make operation using db.auth() switch. The main goal of it is use wiredtiger engine with multi-tenant using multi-schema approach.

For this reason I want add a user credential per tenant and after for each operations using db.auth() for each tenant giving me control over RBCA.

The main intention of it's don't open a new connection for each one. I see this approach used by [Cisco](http://es.slideshare.net/mongodb/securing-mongodb-to-serve-an-awsbased-multitenant-securityfanatic-saas-application) and here the way to do this on [MongoDB](https://docs.mongodb.org/manual/reference/method/db.auth/)

Can you say me if this can be do it using moongose like in [Spring Framework](http://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/MongoTemplate.html)

Regards...

**Comment by vkarpov15** [comment]
With mongoose you can only authenticate on a per-connection basis - if you want to use multi-tenant, I'd recommend a separate connection for each tenant.

**Comment by jorgecuesta** [comment]
@vkarpov15 this is a bad idea or I miss something maybe. If I have more than 1000 tenants doing request, should open this amount of connections?
Have a way to make an auto-close connections after some time without transaction make under a connection?

Thanks!

**Comment by vkarpov15** [comment]
Yeah I admit that thousands of connections can bog down mongodb, especially if you're using the wiredtiger storage engine. The tricky bit about working with multi tenant mongoose is that mongoose operations can consist of multiple mongodb operations, so if you're not careful with concurrency you can switch the connection underlying a model and a populate for one tenant gets data from another tenant. This is why we don't really support switching databases or changing auth on the fly

**Comment by jorgecuesta** [comment]
@vkarpov15 Thanks again to answer me again. So using mongoose I doesn't have a current working solution. I ask you, If I createConnection for tenants with a limited time life and control each one, thoose can work, but can you give me an idea of how with mongoose create a connection like auto-close when in an X time don't be used to any transaction?

Thanks Again!.

FYD: To work on multi-tenant I'm planning use [mongoose-multitenant](https://github.com/jraede/mongoose-multitenant)

**Comment by vkarpov15** [comment]
You can use settimeout and connection.close() to close a connection so it can never be used again. Just be careful, models are tied to one connection, so you need to recreate models every time.

Fwiw I have no experience with mongoose-multitenant, so probably worthwhile to ask about best practices there as well as in this repo
