### ISSUE TITLE
update fails to $rename

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4100]
This is quite a minor bug but i have spent 2 hours trying to understand why this doesn't work

```
Model.update({}, {$rename:{existingFieldName:"newFieldName"}}, {multi:true, /*strict:true is by default*/})
```

so update fails to $rename existing field to something which is not existing in a schema
but its actually pretty weird to rename field to something which already exists >_<

i believe this query should print some message to console.

**Comment by vkarpov15** [comment]
Hmm how does it not work? Is there some error or just no updates? What does the debug output look like? Also, which mongoose version? There have been some relevant fixes recently...

**Comment by TrejGun** [comment]
`{strict: true}` works, however updates 0 rows
and there is no debug output 

but `{strict: false}` prints
```
Mongoose: collectionName.ensureIndex({ myId: 1 }) { unique: true, background: true }  
Mongoose: collectionName.update({}) { '$rename': { a: 'b' } } { strict: false, multi: true } 
```

**Comment by vkarpov15** [comment]
Is existingField in your schema? Mongoose will filter out update paths that aren't in the schema unless you specify strict: false

**Comment by TrejGun** [comment]
thats what i'm talking about)
```but its actually pretty weird to rename field to something which already exists >_<```

so it should print some message to console

**Comment by vkarpov15** [comment]
The fact that mongoose filters out updates to paths that aren't in the schema unless you do `strict: false` is a pretty fundamental feature, hard to justify breaking that. Plus, I find it hard to think of a case where doing `$rename` in mongoose is useful, usually if you're gonna rename a field you should do it from the mongodb shell or some other ops tool
