### ISSUE TITLE
relationship aggregation not working

### ISSUE THREAD

**Issue by tumdav** [Automattic/mongoose#4103]
I have two models.
For example post and comments.
Comment related  with post.

**In post model**
```
comments: [{type: Schema.ObjectId, ref: 'Comment'}]
```

I need get weekly comments if comment  status is 1.

```
 Post.aggregate(
     [ 
       {
	$unwind: '$comments'
       }, 
      {
	$project: {
		commentStatus: "$comments.status"
	 }
      },
     {
	$match: {
		commentStatus: 1
	}
      },
      {
	$group: {
		_id: 'some field'
	}
     } 
    ]);
```

**Comment by nasr18** [comment]
instead of using aggregate, try `count`.

**Comment by vkarpov15** [comment]
Use the $lookup stage. Since comments is a separate collection you need to explicitly pull them in to your posts aggregation.
