### ISSUE TITLE
Exclude elements that can't be populated

### ISSUE THREAD

**Issue by santimacia** [Automattic/mongoose#4105]
Sometimes and objectId can't be populated cause it's missing in the other collection. It's possible to avoid these kind of elements, for example in a find query.

**Comment by vkarpov15** [comment]
Please clarify the issue, I don't understand

**Comment by santimacia** [comment]
Sorry for the delay,
Image the two schemas Person, Story from docs.

```
var aaron = new Person({ _id: 0, name: 'Aaron', age: 100 });
var patrick = new Person({ _id: 1, name: 'Patrick', age: 100 });
//and we save

var story0 = new Story({
    title: "Once upon a time0.",
    _creator: 0    // correct id 
  });
var story1 = new Story({
    title: "Once upon a time2.",
    _creator: -1    // missing id
  });
//we save too

//simple search with population of creator
Story.find()
        .populate('_creator')
        .exec(function (err, story) {});

//check the difference of the field _creator between the two objects
[{
title: "Once upon a time0.",
_creator: { _id: 0, name: 'Aaron', age: 100 }
},{
title: "Once upon a time2.",
_creator: -1 //can't be populated,
}]
 ```

The question is, what is a good way to manage the "can't be populated" fields. Should always check:
```
if (array[i]._creator.name) ??exist
```

**Comment by vkarpov15** [comment]
If populate can't find a person with `_id=-1`, then `_creator` will be `null`.

**Comment by Jeff-Lewis** [comment]
@santimacia I struggle with this "set null if not found" when populating as well. See https://github.com/Automattic/mongoose/issues/3937

You can get the original ID from `Story.populated('_created')' after it's been populated. The nasty part of this is that you have to add null checks with an additional checks for doc.populated(path) value all over your code.
