### ISSUE TITLE
Plugins are applied to schemas more than once.

### ISSUE THREAD

**Issue by RobertWHurst** [Automattic/mongoose#4106]
I noticed that plugins were running applied to my schema tens of times within some tests I wrote for a server my team has created. I noticed the issue was caused by the way we have our server structured. We create our schema instances and export them. Then have a modules containing a server constructor that requires them. When the server constructor is executed it constructs a new instance of Mongoose then registers global plugins with it. Lastly it registers the schemas with the mongoose instance. All is fine up to this point.

The problem arises when a new instance of the server constructor is created. The plugins are registered with the new mongoose instance, but then when the schemas are registered, which remember, are the same schema instances passed the the previous mongoose instance, the plugins are applied the the schemas yet again. Now the schemas have had all of the global plugins applied to them twice.

I'm aware that this can be fixed by exporting a factory function instead of the schemas directly, but I would like to suggest that mongoose should check to see if a plugin has already been registered with a schema before adding it. I'll make a PR to demonstrate this. Thoughts?

**Comment by vkarpov15** [comment]
Useful in some cases, but the tricky part is how do you check if a plugin has already been registered? Plugins are just functions - you can do an exact equality check, but that will miss cases where plugins use the "function that returns a function" pattern

**Comment by RobertWHurst** [comment]
Going to close this as my fix was merged. Thanks to @vkarpov15 for merging it. For anyone who's curious, my fix keeps a reference to the passed function. If the function was encountered prior, then the plugin function simply returns this, instead of executing the plugin.

**Comment by jorgecuesta** [comment]
Hey guys,

The functionality described here by @RobertWHurst  we implemented it in a npm package
[mongoose-plugins-recurrency](https://github.com/jorgecuesta/mongoose-plugins-recurrency).

Since we (@jeffreysoriano5) basically copied the functionality we would like to put you as a contributor to the package.

We are open to suggestions, ideas and unit-test enhancements.

**Regards...**

**Comment by vkarpov15** [comment]
Thanks! :beers:
