### ISSUE TITLE
Add two collections with the same unique property

### ISSUE THREAD

**Issue by hckhanh** [Automattic/mongoose#4108]
When I set the unique flag for a property in my document's model. I figure out something is not stable.

Procedure:
1. Start MongoDB server
2. Open the Node.js server
3. Make a request to add a document to a collection by using Model.create()
4. Drop the collection (**without** turn of Node.js server and MongoDB server)
5. Make a request to add a document to the collection again
6. Make a request to add a document to the collection again (2)

**I can add two collections with the same unique property**

**Comment by vkarpov15** [comment]
Code samples please? Converting prose to code is hard
