### ISSUE TITLE
#3981 breaks the ability to use sparse indexes at least in some cases

### ISSUE THREAD

**Issue by taxilian** [Automattic/mongoose#4109]
Since mongoose The fix in #3981 went in, we can no longer omit a field from the document.  When using a sparse index, marking a field as "null" is not sufficient; it must be entirely omitted from the doucment in order to avoid being included in the sparse index.

I've tried setting the default to "void 0", but as I would tend to expect it doesn't help =]

We'll set it to mixed for now, but this is a very real use case which is not possible anymore with mongoose :-(  Ties in and could be possibly considered a sorta dupe of #1335

**Comment by vkarpov15** [comment]
Whoa yeah that's a big problem that we need a workaround for. Perhaps an explicit unset function would be helpful?

**Comment by taxilian** [comment]
I considered that as well; it does seem like it'd fit the most use cases; another idea I considered was a special flag or tweak for $set that would let you specify "force" and it would put whatever you give it, be it object, value, undefined, or whatever.  I finally decided to just open a ticket, though, as I don't feel I understand this code well enough to make a decision on my own

**Comment by vkarpov15** [comment]
Yeah IMO unset is probably the way to go, because setting a field to undefined doesn't really work correctly with mongoose anyway. The use case for #3981 was basically that if you happened to have an object with a key that was set to undefined that would overwrite defaults, which was not great behavior either.

**Comment by vkarpov15** [comment]
@taxilian actually better solution IMO is to just overwrite the default value for an array:

```javascript
var schema = new Schema({
  names: {
    type: [String],
    default: void 0
  }
});
```

The issue is that by default, arrays get `[]` as a default. With the above commit you should now be able to say that "this array should be undefined by default"

**Comment by paulwalker** [comment]
This is obviously an issue when using a unique sparse index for an array. MongoDB has a different semantic than a typical RDBMS in which a key can be absent, present with null or present with a value. It's important that mongoose recognize this semantic as it's inherent to fundamental functionality of the product itself.

I would suggest an explicit option for types, something like `includeWhenNull`. Perhaps for arrays, a shorter term 'fix' would be to recognize an explicit `required: false` option and not include an empty array as a default.

**Comment by vkarpov15** [comment]
@paulwalker I'm not sure I understand your suggestion - you want the `required` property to affect the behavior of the `default` property?
