### ISSUE TITLE
instanceof check for Connection

### ISSUE THREAD

**Issue by gonsfx** [Automattic/mongoose#4112]
I'm writing a plugin that needs to retrieve a `connection` object in its options.

In tests, i do not only want to check if the `connection` property is set on options, but i would also love to perform an instanceof check to check if it's really a valid mongoose connection instance. Unfortunately, this doesn't work:

```javascript
import { isPlainObject } from 'lodash'
import { Connection } from 'mongoose'

export default function (schema, options) {
  if (!isPlainObject(options)) {
    throw new Error('options must be an object')
  }
  if (!(options.connection instanceof Connection)) {
    throw new Error('connection option must be a valid mongoose connection')
  }
}
```

Am i missing something? Is there any other way to validate a connection?

**Comment by vkarpov15** [comment]
What is `options.connection`? I added a test case above and it looks like the result of `createConnection()` is definitely an instance of `mongoose.Connection`...

**Comment by gonsfx** [comment]
Seems you're right. Sorry, my bad. After executing `mongoose.connect`, i used the `mongoose` object instead of `mongoose.connection` as `options.connection`.

From reading the docs i was under the impression that those are basically the same?

**Comment by vkarpov15** [comment]
No definitely not, the top level mongoose object is not the same thing as a connection. There's some syntactic sugar there to help with using the default connection, but they're separate types
