### ISSUE TITLE
How to surface custom CastError messages?

### ISSUE THREAD

**Issue by joshkopecek** [Automattic/mongoose#4113]
We're working on [mongoose-geojson-schema](https://github.com/joshkopecek/mongoose-geojson-schema), which adds validation for GeoJSON objects to Mongoose schemas. Following the guidance on creating a [Custom Schema Type in the mongoose docs](http://mongoosejs.com/docs/customschematypes.html) we're using 
``` javascript
throw new mongoose.SchemaType.CastError('Crs must be an object or null');
```
[referenced here](https://github.com/joshkopecek/mongoose-geojson-schema/blob/master/GeoJSON.js)
Yet when we test the code and review the exceptions thrown, they are generic messages:
```
Cast to Point failed for value "[object Object]" at path "point"
```
How can the user find out the detailed error message? Is there something else that we need to in the plugin, or something else the user does on the calling side?

Thanks in advance for any help here.

**Comment by markstos** [comment]
This is similar to, if not the same issue as #3162.

**Comment by vkarpov15** [comment]
Right now a CastError has a `reason` property that contains the original error. Unfortunately the custom schema type examples currently prevent that property from getting populated though. To work around this, just throw any error type that isn't mongoose's `CastError` and you'll get the `reason` property.

**Comment by joshkopecek** [comment]
@vkarpov15 thanks for looking at this. I've changed to using `Error` instead, which is definitely more meaningful than the generic `CastError`. We'll wait on the milestone release for switching back to `CastError`. @markstos

**Comment by vkarpov15** [comment]
You can also just use your own error type, a casterror gets surfaced in the end anyway

**Comment by markstos** [comment]
Thanks for the tip!
