### ISSUE TITLE
"npm test" on master branch fails with Node.js v0.10.40 and v4.4.1

### ISSUE THREAD

**Issue by markstos** [Automattic/mongoose#4121]
After a fresh "npm install && npm test", I get the same result for both Node.js versions.

Yes, I see that the warning that "I'm not testing shards!", but I don't care about shards, and the message does claim that it's an error /not to/. I presume it's a stern recommendation to test shards. 

```
$ npm test

> mongoose@4.4.15-pre test /home/mark/Documents/ride_amigos/github-forks/mongoose
> mocha test/*.test.js test/**/*.test.js

Not testing multi-mongos support
 
 You're not testing shards! 
 Please set the MONGOOSE_SHARD_TEST_URI env variable. 
 e.g: `mongodb://localhost:27017/database 
 Sharding must already be enabled on your database 


  ․․

  0 passing (2m)
  2 failing

  1)  "before all" hook:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  

  2)  "after all" hook:
     Error: timeout of 120000ms exceeded. Ensure the done() callback is being called in this test.
  
npm ERR! Test failed.  See above for more details.
```

I eventually realized my MongoDB was unexpectedly not running. A reality-check for this case up front would be welcome with a more useful error message than what happened above.

**Comment by vkarpov15** [comment]
Fair point, will add
