### ISSUE TITLE
Refactor: Fix argument order for some `assert.equal()` calls

### ISSUE THREAD

**Issue by markstos** [Automattic/mongoose#4122]
The order of calls to `assert.equal()` should be `(actual,expected)` according to the [official docs](https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message).

This matters for the diagnostic messages which helpfully label which value was `expected` and which value was `actual`. 

The Mongoose test suite sometimes has the values reversed, with the fixed value as the argument and the value being tested as the second. 

All the cases to cover can be found by by searching in the `/test/` directory for `assert.equals()`.

Without this refactor, there's more possibility about confusion when a test fails. This is particularly important for cases where both args are variables, like this one:

    ` assert.equal(errorMessage, error.toString());`

**Comment by vkarpov15** [comment]
Yeah you're right, good call

**Comment by vkarpov15** [comment]
Here's the script I used to get most of this done for posterity's sake

```javascript
var fs = require('fs');

const contents = fs.readFileSync(process.env.FILE).toString('utf8');

const lines = contents.split('\n');

for (const line of lines) {
  if (/assert.equal/.test(line)) {
    console.log(line.replace(/assert.equal\((\d+|true|false|undefined|null|'.*)?, (.*)?\)/, 'assert.equal($2, $1)'));
    //console.log(line.replace(/assert.equal\((.*)?, (.*)?\)/, 'assert.equal($2, $1)'));
  } else {
    console.log(line);
  }
}
```

**Comment by markstos** [comment]
Thanks! Nice use of automation for this fix.
