### ISSUE TITLE
Mongoose hang up without throwing any error

### ISSUE THREAD

**Issue by bitliner** [Automattic/mongoose#4125]
In my node.js process there is a module the saves html pages.

Other modules save other objects.

Apparently the saving some html page makes mongoose hangup. If I remove it mongoose does not hang up anymore.

Specifically I saw a custom function of the model that runs a save, and then (maybe because it hanged up before) it runs the callback, the log after running the callback is displayed on the console, but the callback  is not really executed.

Something like

```
// custom method
Model.methods.mycustomFn=function(cb){
  this.save(function(err,doc){
    cb();
    console.log('call back was executed')
  })
}

// cb 
cb = function(){
  console.log('this code is never executed...');
}
```

Does mongoose have an internal debugging logging that I can activate in order to better understand what is going on?
I will have a look at the html page to see why it is problematic.

Do you have any other recommendation/tool to troubleshoot the problem?

**Comment by vkarpov15** [comment]
`require('mongoose').set('debug', true)`. How big is your html page?

**Comment by bitliner** [comment]
@vkarpov15 Did you ask because you are afraid that the page is bigger than 16MB ?
In that case, should't mongoose throw an exception?

**Comment by vkarpov15** [comment]
Mongoose should throw an exception, yes. Just trying to get all the information I can :)

**Comment by vkarpov15** [comment]
Issue's gone stale, closing.
