### ISSUE TITLE
mongoose silently ignores a problem if it cannot create the text index

### ISSUE THREAD

**Issue by dportabella** [Automattic/mongoose#4127]
let's say I create a database as follows:

```
var ProductSchema = new mongoose.Schema({title: String, price: Number}).index({title: "text"});
var Product = mongoose.model('Product', ProductSchema);
Product.create({title: 'book1', price: 100});
```
and populate it with data.
later, I realize that I want to add a description, and text index it also, so I change my program and run on the already populated database:

```
var ProductSchema = new mongoose.Schema({title: String, price: Number, description: String}).index({title: "text", description: "text"});
var Product = mongoose.model('Product', ProductSchema);
Product.create({title: 'book2', price: 200, description: 'better'});
```

so, I have book1 and book2, and I would expect that I have the new text index set-up.
But that's not the case; Mongoose didn't create the text index (with title and description) because it already existed a text index (with only title). (mongodb only allows one text index shared across the requested fields).

`mongoose.model` silently ignored the problem, and this is not an acceptable behavior. Instead, it should either:
- delete the previous text index and create the new one.
- or throw an error

The developer can detect this problem by calling `Product.ensureIndexes`. But i still think that `mongoose.model` should either execute what is asked or fail, instead of silently ignoring the problem.

**Comment by vkarpov15** [comment]
[Turn on the `emitIndexErrors` option](http://mongoosejs.com/docs/guide.html#emitIndexErrors). This behavior is off by default for backwards compatibility, but it [will be changed in the next major release](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings)
