### ISSUE TITLE
querying population

### ISSUE THREAD

**Issue by GichanLee** [Automattic/mongoose#4134]
hello, I'm beginner of mongoose. I'm so sorry about asking question at this board. but I really don't know what to do. I was finding my problem about 2 days but I couldn't have any answer. please, help me.

after creating dummy, I have this collection 'employees'

```
{ "_id" : ObjectId("5731454d965c2473120caa8b"), "id" : "1000003", "address" : { "city" : "New York", "state" : "NY", "zip" : 10118, "lines" : [ "11 Wall Street" ] }, "image" : "images/employees/1000003.png", "name" : { "first" : "Colin", "last" : "Ihrig" }, "__v" : 0, "team" : ObjectId("5731454d965c2473120caa91") }
{ "_id" : ObjectId("5731454d965c2473120caa8c"), "id" : "1000021", "address" : { "city" : "Pittsburgh", "state" : "PA", "zip" : 15222, "lines" : [ "46 18th St", "St. 210" ] }, "image" : "images/user.png", "name" : { "first" : "Adam", "last" : "Bretz" }, "__v" : 0, "team" : ObjectId("5731454d965c2473120caa91") }
{ "_id" : ObjectId("5731454d965c2473120caa8d"), "id" : "1000022", "address" : { "city" : "Pittsburgh", "state" : "PA", "zip" : 15222, "lines" : [ "2 S Market Square", "(Market Square)" ] }, "image" : "images/user.png", "name" : { "first" : "Matt", "last" : "Liegey" }, "__v" : 0, "team" : ObjectId("5731454d965c2473120caa91") }
```

and 'teams'

```
{ "_id" : ObjectId("5731454d965c2473120caa91"), "name" : "Software and Services Group", "members" : [ ], "__v" : 0 }
{ "_id" : ObjectId("5731454d965c2473120caa92"), "name" : "Project Development", "members" : [ ], "__v" : 0 }
```

and I execute simple function on routes.

```
function getEmployee (employeeId, callback) {
  Employee.findOne({id: employeeId}).populate('team').exec(callback);
}

[...]
else if(_url = /^\/employees\/(\d+)$/i.exec(req.url)){
    employeeService.getEmployee(_url[1], function(err, data){
      if(err){
        return responder.send500(err, res);
      }
      if(!data){
        return responder.send404(res);
      }
      return responder.sendJson(data, res);
    });
  }
```

Employee.findOne({id: employeeId})**.populate('team')**.exec(callback);
If I don't have '.populate', It works simply printing JSON about employee.
but If I have it, It's pending and the callback isn't executed.
I think that I just follow the documentation, but it doesn't work.
again, I'm so sorry about asking this question. 
 
+debug log here

```
Mongoose: employees.findOne({ id: '1000022' }) { fields: undefined }  
Mongoose: teams.find({ _id: { '$in': [ ObjectId("5731454d965c2473120caa91") ] } }) { fields: undefined }  
Mongoose: employees.find({ team: ObjectId("5731454d965c2473120caa91") }) { fields: undefined }  
```

+ my full code
https://github.com/GichanLee/codingPractices/tree/master/HRapp_with_MEAN/sources
models/employee.js
models/team.js
/index.js
/lib/employees.js

Thank you.

**Comment by nasr18** [comment]
@GichanLee i think you have to pass two parameter in `exec(err, cb)`. but I'm not sure. Your code looks correct.

**Comment by GichanLee** [comment]
@nasr18 Thank you. but if I delete .populate, the function correctly works. also I added err but didn't change. is there any hint..?

**Comment by nasr18** [comment]
@GichanLee  sorrry no idea.

**Comment by vkarpov15** [comment]
Does the error still occur if you remove the postFind plugin? I suspect there's something wrong with how you're using async.each, and that plugin is unnecessary since mongoose 4.x has post find and post findOne hooks

**Comment by GichanLee** [comment]
@vkarpov15 Thanks, I will try that and comment about it.

**Comment by GichanLee** [comment]
@vkarpov15 Thank you!! It works! mongoose-post-find module may be crashed because of old dependency with its node-modules.
