### ISSUE TITLE
Feature Request: Warn when querying on a field not in the schema

### ISSUE THREAD

**Issue by joeytwiddle** [Automattic/mongoose#4136]
It would be awesome if there would be an option that would cause Mongoose to throw an error if we try to perform a query on a field which was not specified in the schema.

This would assist development by letting me know when I have spelled a field/property incorrectly (typo) or perhaps some other silly mistake like querying the wrong collection.
- Most (but maybe not all) developers who use mongoose will put **all** their properties/fields in the schema.
- The schema is there to help prevent us from making mistakes in this schema-less environment.
- An SQL server will clearly complain if we try to select on a non-existent field. Currently mongoose just returns us `[]`. But if it could give us a helpful warning like SQL, then why not?

**Comment by vkarpov15** [comment]
Check out the schema option 'strict'. `strict: 'throw'` does exactly what you're suggesting

**Comment by joeytwiddle** [comment]
Throw seems to only complain when saving documents.

My suggestions was about **_querying_** collections.  E.g. when doing `find()` or `findOne()` operations.

**Comment by vkarpov15** [comment]
Hmm that's strange. Will check
