### ISSUE TITLE
restrict specific fields 

### ISSUE THREAD

**Issue by antonioaltamura** [Automattic/mongoose#4141]
Hi, what do you think it's the best way to accompish a restriction (with authentication) to a field?
I mean something like this data model:
```
var users = new Schema({
    name:{type:String},
    private:{type:String}
});
```
In a find() query the "private" field should be visible just to authenticated users.
Obiouvsly I have a serverside function to check the authentication.

**Comment by pdspicer** [comment]
```
var query = {...}, // some query
    projection = isAuthenticated ? null : '-private'; // projection removing private field if not authenticated
users.find(query, fields)
```
reference: [Model.find](http://mongoosejs.com/docs/api.html#model_Model.find)

**Comment by antonioaltamura** [comment]
thanks, it works great.

**Comment by antonioaltamura** [comment]
just to be sure I didn't miss something "projection" and "fields" are the same thing, right :) ?

**Comment by vkarpov15** [comment]
@pdspicer 's suggestion is probably the easiest way. You can also try [mongoose-hidden](https://www.npmjs.com/package/mongoose-hidden).

And yeah "projection" and "fields" refer to the same concept, "fields" is somewhat archaic and MongoDB is trying to get people to use "projection" more consistently.
