### ISSUE TITLE
Pass doc as parameter to virtual getters/setters

### ISSUE THREAD

**Issue by refextu** [Automattic/mongoose#4143]
As descriped in #3695, it would be handy to use arrow functions. 

How to handle the following Code in ES6 syntax?

```
TransactionSchema.virtual('happy').get(() => {
  return this.face === 'smiling' ? true : false;
});
```

or better

`TransactionSchema.virtual('happy').get(() =>  this.face === 'smiling' ? true : false);`

This works pretty fine:

```
TransactionSchema.virtual('happy').get(function() {
  return this.face === 'smiling' ? true : false;
});
```

How do I access the virtual Object?

**Comment by dbellavista** [comment]
This is not a mongoose problem. Arrow functions are not a shortcut for `function()`, by definition they get `this` and `arguments` from the current context so you can't call the virtual getter with a different `this`.

**Comment by Rolilink** [comment]
why not simply pass the doc/this reference through the parameters?

**Comment by vkarpov15** [comment]
@Rolilink we'll add that for a future release

**Comment by vkarpov15** [comment]
Turns out we already pass `doc` as the 2nd parameter to getters and setters: 

```javascript
TransactionSchema.virtual('happy').get((v, doc) => {
  return doc.face === 'smiling' ? true : false;
});
```

Just need to make the [`VirtualType#get()`](https://mongoosejs.com/docs/api.html#virtualtype_VirtualType-get) and [`VirtualType#set()`](https://mongoosejs.com/docs/api.html#virtualtype_VirtualType-set) docs describe this.
