### ISSUE TITLE
Context in `Document.prototype.$__validate`

### ISSUE THREAD

**Issue by varunjayaraman** [Automattic/mongoose#4144]
I was having trouble validating subdocuments in an array in `4.4.16` where I noticed the function was executed in node's global scope and not the context of my subdocument. I think I located the error here:

https://github.com/Automattic/mongoose/blob/master/lib/document.js#L1147

Since the filter function loses the context of the subdocument, it should be `_this`, as defined at the top of the `$__validate` function, and not `this`, right? When I changed `this` to `_this`, the validator functions assumed the proper context.

**Comment by varunjayaraman** [comment]
Oops, look like a PR was opened to address this as I was writing this issue: https://github.com/Automattic/mongoose/pull/4142

**Comment by vkarpov15** [comment]
Yeah Jed got it. Thanks for reporting :)
