### ISSUE TITLE
Issue when a discriminator is registered with the same name as another model

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#4148]
Firstly, great work on this library.

There seems to be an issue when registering a discriminator (inherited schema) that also has the same name as separate, non-discriminator model. For example:

````
var Product = mongoose.model( 'product', require('./product/index') );
var SubscriptionProduct = Product.discriminator( 'subscription', require('./product/subscription') );

var Subscription = mongoose.model( 'subscription', require('./subscription') );
````

Yields the following error: 

````
/Users/ajay/Sites/xx/node_modules/mongoose/lib/index.js:360
      throw new mongoose.Error.OverwriteModelError(name);
      ^
OverwriteModelError: Cannot overwrite `subscription` model once compiled.
    at Mongoose.model (/Users/ajay/Sites/xx/node_modules/mongoose/lib/index.js:360:13)
````

However, switching the order in which the schemas are registered as models seems to fix the problem:

````
var Subscription = mongoose.model( 'subscription', require('./subscription') );

var Product = mongoose.model( 'product', require('./product/index') );
var SubscriptionProduct = Product.discriminator( 'subscription', require('./product/subscription') );
````

I assume this is a bug and not intended behaviour, as discriminators are not actually their own models in themselves, correct?

Using mongoose 4.4.17, node 4.2.2.

Thanks!

**Comment by vkarpov15** [comment]
Unfortunately the "throw error" behavior is correct, discriminators are actually fully-fledged models, so they need to have unique names.

**Comment by alexahdp** [comment]
Why did you do it in minor release? You broke back compatibility for us with this feature.

**Comment by alexahdp** [comment]
It must be in major release

**Comment by vkarpov15** [comment]
Because this behavior wouldn't work as advertised, the discriminator would overwrite the original model in the connection's model map. I admit this is one of those issues that blurs the line between bug and feature but as long as the model map exists we need to make sure it works in a consistent way.

**Comment by vkarpov15** [comment]
My sincerest apologies for any trouble this caused @alexahdp .
