### ISSUE TITLE
Unable to validate when array of documents is sent to create function

### ISSUE THREAD

**Issue by akanshgulati** [Automattic/mongoose#4150]
```JS
//Schema:
var userSchema = new Schema({
'id':{type: Number, unique: true, index: true, required:true, dropDups: true}
});

//Method
userSchema.statics.createUser= function(user,cb){
return this.create(user,cb);
}
//Model
var User = mongoose.moderl('User', userSchema);

User.createUser(sampleUserDocument,function(err,resp){
 if(err) throw err;
console.log(resp);
}
```
On passing a single redundant document in createUser method, shows validation error but if array of documents is passed to the same function, all documents are inserted without any validation. By this, createUser function even takes redundant data.

**Comment by vkarpov15** [comment]
What does the array of documents you're inserting look like? Create definitely does validation, but I suspect there may be some issue with mongoose's default `id` virtual and your id path
