### ISSUE TITLE
Mongoose not shutting down gracefully (on initial connection when ECONNREFUSED)

### ISSUE THREAD

**Issue by tilleps** [Automattic/mongoose#4151]
I have come into the issue of where scripts/tests won't finish/exit when the database is unavailable prior to running the script/test.  Possibly related issue: https://www.bountysource.com/issues/1384221-mongoose-doesn-t-shut-down-gracefully

**Basic Example:**
```javascript
var connection = mongoose.createConnection('mongodb://localhost:27017/');

connection.on('error', function (err) {
  console.log(err);
});

setTimeout(function () {
  connection.close();
}, 2000);
```

If the above is run when there is a running MongoDB server, the script will exit after 2000 milliseconds, as intended.

If the above is run when there is no running MongoDB server, the script will hang for about 30 seconds (I'm assuming this is some timeout?) then the script will end.

I have tried `mongoose.disconnect()` and removing all the listeners on `connection` and `connection.db`, but they do not appear to have any effect.

**How to prevent mongoose delaying the graceful termination of the script?**

I should also note that the native MongoDB driver does not appear to have this issue:

```javascript
var MongoClient = require('mongodb').MongoClient
  , assert = require('assert');

// Connection URL
var url = 'mongodb://localhost:27017/';
// Use connect method to connect to the Server
MongoClient.connect(url, function(err, db) {
  assert.equal(null, err);
  console.log("Connected correctly to server");

  db.close();
});
```

**Comment by vkarpov15** [comment]
Which version of mongoose? The below script executes as expected for me when no mongodb running, exits immediately:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var connection = mongoose.createConnection('mongodb://localhost:27017/');

connection.on('error', function (err) {
  console.log(err);
});

setTimeout(function () {
  connection.close();
}, 2000);
```

```
$ node gh-4151.js 
{ Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }
```

If the script hangs for about 30 seconds, I suspect you're hitting the `server.reconnectTries` and `server.reconnectInterval` limit, in which case you can try shutting off the `autoReconnect` option: http://mongoosejs.com/docs/connections.html
