### ISSUE TITLE
insertMany do not update createdAt ? 

### ISSUE THREAD

**Issue by windmaomao** [Automattic/mongoose#4155]
Just curious if insertMany actually appreciate createdAt and updatedAt if model has { timestamps: true }

i believe if i do just insert, it'll work, but not with insertMany.

**Comment by ramiel** [comment]
I was wondering if insertMany calls the `save` hook. Then I read this issue and I discover the `insertMany` hooks is present but is not documented (or at least I could not find it). So two questions:

1) Why a specific hook and not the save one?
2) Is documentation missing?

**Comment by vkarpov15** [comment]
Because `create` calls `save()` but `insertMany()` does not. `insertMany()`
is a specific wrapper around the mongodb bulk API to make inserting docs
more performant (in theory). Documentation is missing, see
https://github.com/Automattic/mongoose/issues/4451

**Comment by exentrich** [comment]
No chance to get timestamps for insertMany? 
Probably it’s easy to implement because requires only to add ‘createdBy’ field into documents before actual insertMany.

Sure we can implement this behavior by ourself, but I think this should be in library itself?

**Comment by vkarpov15** [comment]
@exentrich `insertMany()` does set timestamps as far as I know, if it doesn't that's a bug. Can you please open up a new issue with repro instructions if `insertMany()` doesn't set `createdAt` for you?

**Comment by hugomallet** [comment]
On my case using insertMany it seems that the document timestamps are set but not sub documents ones.

**Comment by vkarpov15** [comment]
@hugomallet please open up a new issue and follow the issue template.
