### ISSUE TITLE
Can't populate from fs.files

### ISSUE THREAD

**Issue by codepunkt** [Automattic/mongoose#4157]
I'd like to populate my article documents with tenant information and file information from gridfs `fs.files` collection. To do so, i have a `FileSchema`, a `TenantSchema` and an `ArticleSchema` referencing both.

``` javascript
import mongoose, { Schema } from 'mongoose'

const FileSchema = new Schema({}, { strict: false }, 'fs.files')
const TenantSchema = new Schema({})
const ArticleSchema = new Schema({
  image: { type: Schema.Types.ObjectId, ref: 'File' },
  title: { type: String, required: true },
  tenant: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true }
})

const FileModel = mongoose.model('File', FileSchema)
const TenantModel = mongoose.model('Tenant', TenantSchema)
const ArticleModel = mongoose.model('Article', ArticleSchema)
```

When i query the article collection and try to populate both `image` and `tenant`, only `tenant` is populated:

``` javascript
ArticleModel.findOne().populate([ 'image', 'tenant' ]).exec().then((article) => {
  console.log(article)
  // { image: null,
  //  __v: 0,
  //  tenant: { __v: 0, _id: 5728c00b7f6adc9dc1c6eafe },
  //  title: 'Kiste Delirium',
  //  _id: 573aea7ed9d16f80326c6a5d }
})
```

mongoose.log logs these queries:

```
mongoose articles.findOne({})
mongoose files.find({"_id":{"$in":["573aeb4617ed0d36330536be"]}})
mongoose tenants.find({"_id":{"$in":["5728c00b7f6adc9dc1c6eafe"]}})
```

When i try these queries manually in my code, these are the results:

``` javascript
Tenant.find({ _id: { '$in': ['5728c00b7f6adc9dc1c6eafe'] } }).then((tenant) => {
  console.log(tenant) // [ { __v: 0, _id: 5728c00b7f6adc9dc1c6eafe } ]
})

File.find({ _id: { '$in': ['573aeb4617ed0d36330536be'] } }).then((file) => {
  console.log(file) // []
})
```

I'm not sure whats wrong here, but it seems i can't query `fs.files` with an `{ _id: { $in } }` query.
Why?

**Comment by vkarpov15** [comment]
The below script works fine for me:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4157');
mongoose.set('debug', true);

const FileSchema = new Schema({}, { strict: false }, 'fs.files');
var File = mongoose.model('File', FileSchema);

File.create({}, function(error, doc) {
  assert.ifError(error);
  File.find({ _id: { $in: [doc._id.toString()] } }, function(error, docs) {
    assert.ifError(error);
    assert.equal(docs.length, 1);
    console.log('done');
    process.exit(0);
  });
});
```

```
$ node gh-4157.js 
Mongoose: files.insert({ _id: ObjectId("5740bea816ca73fe3813751c"), __v: 0 })   
Mongoose: files.find({ _id: { '$in': [ ObjectId("5740bea816ca73fe3813751c") ] } }) { fields: undefined }  
done
```

Can you clarify your version of mongoose, and see if you can modify the above script to reproduce your issue?

**Comment by gonsfx** [comment]
Your example runs without errors for me, i'm using mongoose `4.4.12`. The problem with your example is that it is not running on the gridfs collection `fs.files`. What it does instead is creating a collection named `files`, which works fine.

This test case, on the other hand, reproduces my problem. It sets up on a regular `fs.files` collection
```javascript
'use strict';

var assert = require('assert');
var MongoClient = require('mongodb').MongoClient;
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var url = 'mongodb://localhost/gh4157';

MongoClient.connect(url, function(error, db) {
  assert.ifError(error);

  mongoose.connect(url);
  mongoose.set('debug', true);

  var filesCollection = db.collection('fs.files');
  filesCollection.insert({}, function(error, obj) {
    assert.ifError(error);
    var doc = obj.ops[0];

    var FileSchema = new Schema({}, { strict: false }, 'fs.files');
    var File = mongoose.model('File', FileSchema);

    File.find({ _id: { $in: [doc._id.toString()] } }, function(error, docs) {
      assert.ifError(error);
      assert.equal(docs.length, 1);
      console.log('done');
      process.exit(0);
    })
  })
})
```
Unlike the `files` collection from your test, the `fs.file` collection from this one has the assorted `fs.chunks` collection which does not matter for the purposes of this test but clearly shows that this indeed __is__ a gridfs collection while the one from your test is __not__.

**Comment by vkarpov15** [comment]
@gonsfx you're setting up your collection name incorrectly. The below two alternatives work correctly:

```javascript
var FileSchema = new Schema({}, { strict: false, collection: 'fs.files' });
var File = mongoose.model('File', FileSchema);
```

```javascript
var FileSchema = new Schema({}, { strict: false });
var File = mongoose.model('File', FileSchema, 'fs.files');
```

**Comment by ilaipi** [comment]
@vkarpov15 hello,after:
```javascript
var FileSchema = new Schema({}, { strict: false });
var File = mongoose.model('File', FileSchema, 'fs.files');
```
how can I use the `File` to save my files into mongodb?  
Can u give me an example?

**Comment by vkarpov15** [comment]
@ilaipi it's pretty tricky to implement the gridfs spec yourself and mongoose doesn't really support it. I'd recommend you use the mongodb drivers gridfsbucket interface, http://mongodb.github.io/node-mongodb-native/2.2/api/GridFSBucket.html , it'll made it easy for you to use node fs streams with mongodb gridfs

**Comment by ilaipi** [comment]
Thanks for your response! I will try it.  
So, the mongoose api  
```javascript
var FileSchema = new Schema({}, { strict: false });
var File = mongoose.model('File', FileSchema, 'fs.files');
```
is just use for `Read` && `Delete` operations for files.   
And sth not involve streams for `Create` && `Update`  
Is this right? @vkarpov15

**Comment by vkarpov15** [comment]
I wouldn't recommend using mongoose for read or delete operations either, because gridfs actually uses two collections, `fs.files` for file metadata (size, name, etc.) and a separate `fs.chunks` collection that contains the actual file content. If you want to truly delete a file you'd need to delete both the metadata document and any chunks documents. The GridFSBucket interface handles this for you, but mongoose doesn't really have any equivalent. If you're interested in using mongoose for this you can check out the [mongodb gridfs spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) but it's probably a little heavy unless you have a very good reason to use mongoose for gridfs.

**Comment by sadeeqaji** [comment]
i'm uploading files with multer gridfs, then i created a new Schema which named Movie with a property of fileID which i referenced with file id of file i uploaded how do populate the MovieID since the file is splited into 2 collection fs.files and fs.chunk?

**Comment by vkarpov15** [comment]
@sadeeqaji please provide code samples

**Comment by sadeeqaji** [comment]
The Movie Schema 
![screenshot from 2018-12-15 17-50-05](https://user-images.githubusercontent.com/16036023/50045413-9665f400-0092-11e9-9a30-176d50a4e92d.png)

Here i called the populate method 
![screenshot from 2018-12-15 17-53-17](https://user-images.githubusercontent.com/16036023/50045419-a4b41000-0092-11e9-85cc-fa835e943c4e.png)

**Comment by vkarpov15** [comment]
@sadeeqaji you would need to create Mongoose models for the `fs.files` and `fs.chunks` collections, and use [deep populate](https://mongoosejs.com/docs/populate.html#deep-populate) as show below.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh4157`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const MovieSchema = new Schema({
    fileId: { type: mongoose.ObjectId, ref: 'File' }
  });
  const Movie = mongoose.model('Movie', MovieSchema);

  const FileSchema = new Schema({ name: String });
  FileSchema.virtual('chunks', {
    ref: 'Chunk',
    localField: '_id',
    foreignField: 'files_id'
  });

  const File = mongoose.model('File', FileSchema, 'fs.files');

  const ChunkSchema = new Schema({ files_id: mongoose.ObjectId, data: Buffer });
  const Chunk = mongoose.model('Chunk', ChunkSchema, 'fs.chunks');

  const m = await Movie.findOne().populate({
    path: 'fileId',
    populate: {
      path: 'chunks'
    }
  });

  console.log(m.fileId.chunks);

  /* Can use below to insert sample data
  const mongodb = require('mongodb');
  const client = await mongodb.MongoClient.connect(connectionString);
  const bucket = new mongodb.GridFSBucket(client.db());
  require('fs').createReadStream('./qr.html').pipe(bucket.openUploadStream('qr.html'));*/
}
```

See https://thecodebarbarian.com/mongodb-gridfs-stream for more info on how to create test data for this script.
