### ISSUE TITLE
mongoose findByIdAndUpdate not modifying model and not returning error

### ISSUE THREAD

**Issue by claytonshaver** [Automattic/mongoose#4162]
I have a mongoose model called Message, when that model is created I want to save the Message Id to an array in another model called User. However when the findByIdAndUpdate method is called its not modifying the user model nor is it returning an error message. I've checked that I'm using the correct User id and the Message id is also valid. I'm sure its just me doing something wrong, but any thoughts as to why it behaving this way?

```
MessageSchema.post('save', function addMessageToUser(doc) {
      User.findByIdAndUpdate(doc.userID, {
        $push: {
          messages: {
            $each: [doc._id],
            $sort: { createdAt: 1 },
            $slice: -1000,
          },
        },
      }, {
        new: true,
      }, (response, error) => {
        console.log(response);
        console.log(error);
      })
});
```

**Comment by vkarpov15** [comment]
Are you calling .post() on a model or a schema? You should define hooks on a schema, not a model

**Comment by claytonshaver** [comment]
Sorry for the confusion, I am calling the .post() on a schema and not a model

**Comment by claytonshaver** [comment]
I found the issue: doc.userID wasn't being cast to an ObjectId, here is the refactored code using mongoose.Types.ObjectId() to cast the string to an ObjectId. It would be helpful if mongoose would throw and error when an update requries an ObjectId, but gets another type like a String.
``
MessageSchema.post('save', function addMessageToUser(doc) {
      User.update({
    "_id": mongoose.Types.ObjectId(doc.userID),
  }, {
    $push: {
      metrics: {
        $each: [metricID],
        $sort: { createdAt: 1 },
        $slice: -1000,
      },
    },
  })
});``

**Comment by vkarpov15** [comment]
That's strange, what does your schema look like? Mongoose does cast by default unless you disable it.
