### ISSUE TITLE
Is it possible to use the positional operator '$' in Model.update $set? 

### ISSUE THREAD

**Issue by zky829** [Automattic/mongoose#4165]
For example:

```
Model.update({
		_id : somedoc._id
	},
	{ $set: {
		'somearray.$.somefield': 'foo'
	}}
);
```

I can't find any mention of it in the docs and it's not working for me. I'm using 4.3.7. Thanks!

**Comment by vkarpov15** [comment]
Yep no reason why not. Just make sure youre using the positional operator properly. You need to query by the array field before using that array field with the positional update operator
