### ISSUE TITLE
insert bunch of data at a time without looping

### ISSUE THREAD

**Issue by nasr18** [Automattic/mongoose#4168]
I have a scenario to save employee logs from csv file which will have lot of entries. I need to save this entries without looping through. is that possible to do??? @vkarpov15

**Comment by vkarpov15** [comment]
Perhaps `insertMany` ? Why can't you loop?

**Comment by nasr18** [comment]
ok will check it out.

**Comment by nasr18** [comment]
`inserMany` is just awesome. but is there any possible to check for duplicates before inserting????

**Comment by vkarpov15** [comment]
Unique indexes: https://docs.mongodb.com/manual/core/index-unique/, http://mongoosejs.com/docs/2.7.x/docs/indexes.html
