### ISSUE TITLE
Populate referenced sub documents

### ISSUE THREAD

**Issue by aquadestructor** [Automattic/mongoose#4172]
I have read around similar issues but I haven't got my head around the work around for this. I have a nested array of sub documents in a registered schema and I want to populate the sub document that I have referenced in another Schema. What would be the workaround/solution to overcome this scenario other than to move the sub docs to a new schema?
**Team Schema**

```javascript
var mongoose = require('mongoose'),
  Schema = mongoose.Schema;
var TeamSchema = new Schema({
  subTeams: [{ _Referenced Sub doc in Player Schema_
    title: {
      type: String,
      default: ''
    },
    players :[{
	    type: Schema.ObjectId,
	    ref: 'Player'
    }],
  }],
});
mongoose.model('Team', TeamSchema);
```

**Player Schema**

```javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;
var PlayerSchema = new Schema({
   playerHistory: [{
        previousTeam: {
            type: Schema.ObjectId,
            ref: 'Team' _**I have referenced team here but in a use case I am handling I have to add subTeam id here and populate the subteam**_
        },
        joinDate: {
            type: Date
        }
    }],

});
mongoose.model('Player', PlayerSchema);
```

@vkarpov15 Any sort of help/direction would be highly appreciated. Thank you

**Comment by crimsonronin** [comment]
@aquadestructor, just a tip for future reference, you can use triple backticks (```) to block format your code. 

You can also nominate the language: (```javascript).

eg
```javascript
var mongoose = require('mongoose'),
Schema = mongoose.Schema;
var TeamSchema = new Schema({
    subTeams: [{ //Referenced Sub doc in Player Schema
        title: {
        type: String,
            default: ''
        },
        players :[{
            type: Schema.ObjectId,
            ref: 'Player'
        }],
    }],
});
mongoose.model('Team', TeamSchema);
```

Single backticks work only for inline code formatting eg. `somecode`.

https://help.github.com/articles/creating-and-highlighting-code-blocks/

It helps people decipher your problems.

**Comment by aquadestructor** [comment]
@crimsonronin Thank you for the suggestion. I'll surely use that in the future

**Comment by vkarpov15** [comment]
Mongoose won't do this sort of population for you - populate requires that you have a separate document, not an embedded doc. You would just have to do a separate query for the `Team`:

```javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;
var PlayerSchema = new Schema({
   playerHistory: [{
        previousTeam: {
            team: {
              type: Schema.ObjectId,
              ref: 'Team'
            },
            subTeamTitle: String
        },
        joinDate: {
            type: Date
        }
    }],

});
mongoose.model('Player', PlayerSchema);
```

You can then `find()` the team based on `previousTeam.team` and then look through the `subTeams` array to find the one with the right title.

However, IMO if you're going to be referencing subteam subdocs from the player doc, it may be easier to just store subteams in a separate collection from teams.
