### ISSUE TITLE
two collection but same field

### ISSUE THREAD

**Issue by nasr18** [Automattic/mongoose#4174]
I have scenario that, i have two collection `empProfile` and `empLogs`. In `empProfile` i'm having just two fields, `EnNo` and `Name`. In `empLogs` i have 5 fields including `EnNo` and `Name`. And i will insert `empLogs` data from csv file which contains only `EnNo` and no `Name`. My question is, is that possible to get `Name` from `empProfile` based on `EnNo` and pass it to `empLogs`? without using loop.

**Comment by vkarpov15** [comment]
Use [aggregation + $lookup](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/) with [$out](https://docs.mongodb.com/manual/reference/operator/aggregation/out/). General idea is here: http://thecodebarbarian.com/2014/04/25/a-nodejs-perspective-on-whats-new-in-mongodb-2-6-part-ii-aggregation-out
