### ISSUE TITLE
mongoose.findById does not return anything and request keep hanging

### ISSUE THREAD

**Issue by xkeshav** [Automattic/mongoose#4175]
system specifications  

- node v 6.1.0
- npm v 3.8.6
- "mongodb": "^2.1.18"
- "mongoose": "^4.4.16"
- ubuntu 16.04

created schema and added one entry by terminal using `db.locations.save({...});`
get the id of that entry and tried to use in my api  but does not return anything when hitting _api/locations/:locationid_  in browser 

### app_api//models/db.js
```
var mongoose  = require( 'mongoose' );    
var mongoURI = 'mongodb://localhost/loc8r';    
var mongoDB = mongoose.createConnection(mongoURI);

mongoDB.on('connected', function (){
    console.log('mongoose connected to ' + mongoURI);
});

require('./locations');
```
### app_api/models/locations.js

```
var mongoose  = require( 'mongoose' );
var Schema =  mongoose.Schema;
var locationSchema = new Schema({
	name: {type: String, required: true},
	address: String,
	rating: {type: Number, "default": 0, min: 0, max: 5},
	facilities: [String]
});

mongoose.model('Location', locationSchema);
```
### /app_api/router/index.js

```
var express = require('express');
var router = express.Router();
var ctrlLocations = require('../controllers/locations');

/* Locations pages */
router.get('/locations/:locationid', ctrlLocations.locationsReadOne);
```
### app_api/controllers/locations.js
```
var mongoose  = require( 'mongoose' );
var location = mongoose.model('Location');

module.exports.locationsReadOne =  function (req, res) {
    if(req.params && req.params.locationid) {
        var _id = mongoose.Types.ObjectId(req.params.locationid);
        console.log(mongoose.Types.ObjectId.isValid(req.params.locationid)); // return true
        location
            .findById(req.params.locationid)
            .exec(function(err, location) {
                if (err) return res.status(500).send(err);
                if (location) return res.status(200).json(location);
                return res.status(404).json({"message":"locationid not found"});
            });
    } else {
         return res.status(200).json({"message": "no location id in request"});
    }
}
```
 also tried with 
`findById(mongoose.Types.ObjectId(req.params.id)` `find()` and `findOne({"_id":_id)` but no results

Is there any bug in latest mongoose?

**Comment by nasr18** [comment]
your codes are very much complicated. why dont you make it short and simple? Your are using MEAN right???

**Comment by xkeshav** [comment]
I am using mongo node and express simultaneously. Sorry but I have pasted all the require code . Please see the complete problem here : http://stackoverflow.com/questions/37383917/mongoose-doesnt-return-the-output-with-findbyid

**Comment by nasr18** [comment]
mongoose working fine for me.

**Comment by xkeshav** [comment]
But here is not working :( that's the problem . I don't know how to see/debug the error and why the request is hanging ? As nodejs is non-blocking

**Comment by vkarpov15** [comment]
@xkeshav are you requiring in `db.js` anywhere? Don't see that in your code...

**Comment by xkeshav** [comment]
yes. in root folder **app.js**

require('./app_api/models/db');

**Comment by xkeshav** [comment]
got the solution.. problem was with **createConnection** method

make  changes the connection string in **db.js**

 `var mongoDB = mongoose.createConnection(mongoURI);`  

to 

`mongoose.connect(mongoURI);`
