### ISSUE TITLE
Error: No _id found on document! with an _id of zero

### ISSUE THREAD

**Issue by claytongulick** [Automattic/mongoose#4176]
Comes from model.js line 651:

 ```
if (!this._doc._id) {
    return new Error('No _id found on document!');
 }
```

An id of 0 is a valid ID, but breaks with this check.

**Comment by Attrash-Islam** [comment]
Did you building the _id by using
var myObjectId = mongoose.Types.ObjectId('0') ?

I guess that would be the creation of an ObjectId for a document.

**Comment by vkarpov15** [comment]
You're using an out-of-date version of mongoose, this is a dup of #3776, upgrade to [>= 4.3.7](https://github.com/Automattic/mongoose/blob/master/History.md#437--2016-01-23)
