### ISSUE TITLE
Unhandled rejection "duplicate key" with sub document using bluebird.

### ISSUE THREAD

**Issue by martinj** [Automattic/mongoose#4177]
**Mongoose** version: **4.4.19**
**Bluebird** version: **3.4.0**

**Example code**

```javascript
'use strict';

const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost/validation-error-test');

const Schema = mongoose.Schema;

const subSchema = new Schema({
	name: {type: String, required: true}
});

const mainSchema = new Schema({
	name: String,
	type: String,
	children: [subSchema]
});

mainSchema.index({name: 1, account: 1}, {unique: true});

const Model = mongoose.model('Model', mainSchema);
const data = {
	name: 'foo',
	type: 'bar',
	children: [{name: 'child'}]
};

new Model(data)
	.save()
	.then(() => new Model(data).save())
	.catch((err) => {
		console.log('Should not print more stuff');
	});

```

**Output**

```
Should not print more stuff
Unhandled rejection MongoError: E11000 duplicate key error index: validation-error-test.models.$name_1_account_1 dup key: { : "foo", : null }
    at Function.MongoError.create (node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
...
```

This problem came after mongoose version 4.3.7

**Comment by vkarpov15** [comment]
Hmm that's strange, this script looks like it should fail at first glance, you would think that it would crash because of the duplicate name + account...

**Comment by martinj** [comment]
The second `new Model(data).save()` is supposed to fail with `duplicate key error` which it does and it gets caught in the `catch()`. 
However it still get `Unhandled rejection` even though it was caught.

The problems is of the same nature as https://github.com/Automattic/mongoose/issues/3391 but in this case its related to sub documents.

If i change the data
```
const data = {
    name: 'foo',
    type: 'bar',
    children: [{name: 'child'}]
};
```
to 
```
const data = {
    name: 'foo',
    type: 'bar'
};

```
No `Unhandled rejection MongoError` would be printed.

**Comment by vkarpov15** [comment]
Ah ok I see, good call, I missed that :+1: 🌴
