### ISSUE TITLE
.near() minDistance not working

### ISSUE THREAD

**Issue by sylvainlap** [Automattic/mongoose#4179]
Hi,

I'm trying to make a $near query, with $minDistance, that is supported by mongoDB (https://docs.mongodb.com/manual/reference/operator/query/near/#op._S_near).

According to http://mongoosejs.com/docs/api.html#query_Query-near, my query looks like this:

````
User.find()
.near('location', {
  center,
  minDistance: lastDistance,
  spherical: true,
})
.limit(10)
.exec()
.then(usersFound => {
  ...
```

However, minDistance is not taken into account. Is this feature implemented in mongoose ?

**Comment by vkarpov15** [comment]
@sylvainlap can you show me what your data looks like, what your mongodb version is, and what your lastDistance is? I suspect the issue is what units mongodb is using for minDistance, your syntax looks correct.

**Comment by sylvainlap** [comment]
I cannot find minDistance in the repository (and I find maxDistance).
I think minDistance is not implemented in mongoose.

**Comment by maxs15** [comment]
@vkarpov15 any news on this ? is minDistance implemented ?
Thanks

**Comment by maxs15** [comment]
Awesome :) Thanks @vkarpov15

**Comment by vkarpov15** [comment]
Thanks for pointing out the issue :beers:
