### ISSUE TITLE
Connection is blocked in Electron main process

### ISSUE THREAD

**Issue by gsavin** [Automattic/mongoose#4180]
Hi,

I am developping an Electron app where there is a connection to a mongo database through mongoose. I got a strange behavior doing this.
An ipc event is triggering the connection action, so I have something like (it is a simplified view of course) :

``` javascript
...
ipc.on('some channel', uri => {
   mongoose.connect(uri, defaultOptions);
   mongoose.connection.once('connected', () => { ... });
   mongoose.connection.on('error', err => { ... });
});
...
```

The thing is : the first call to this channel execute the code, but nothing happens from mongoose. I means no error, no completed action. In the example I used `mongoose.connect()` but I also tried using `mongoose.createConnection()`.
On the second call, the connection is done and I received the 'connected' event. Strange isn't it ?

But the strangest thing is that if I put an empty timeout just before the end of the ipc callback everything works fine on the first shot.

``` javascript
...
ipc.on('some channel', uri => {
   mongoose.connect(uri, defaultOptions);
   mongoose.connection.once('connected', () => { ... });
   mongoose.connection.on('error', err => { ... });
   setTimeout(() => {}, 100);
});
...
```

Any idea about why I got this behavior ? Or is this an electron-related issue ?

**Comment by vkarpov15** [comment]
Very strange, nothing comes to mind, I'll try this out later and see if I can repro the issue. Do you need to create a mongoose connection asynchronously? Might save yourself some headache if you just create a connection once and reuse it.

**Comment by gsavin** [comment]
Yes strange... It actually works fine with the `setTimeout()`. I post this issue just because it does not seem to be a correct behavior.
In my case, connection is triggered from the renderer process and done in the main process, so I do not want to block the renderer.
If there are more informations I can provide, just tell me.

**Comment by vkarpov15** [comment]
Not in particular. My experience with electron is minimal so I'd definitely need some rampup time on this one. What version of electron?

**Comment by gsavin** [comment]
The last one `1.0.2`.
Code is available [here](https://github.com/gsavin/fenix/blob/master/app/lib/modules/db.js).

**Comment by vkarpov15** [comment]
I haven't been able to get your app running because you don't have React in your package.json, but I added the following to electron-quick-start `main.js`:

```javascript
// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

const ipcMain = require('electron').ipcMain;

ipcMain.on('ping', event => {
  console.log('Got ping');
  event.sender.send('pong');
});
```

and the following to `renderer.js`:

```javascript
const ipcRenderer = require('electron').ipcRenderer;
const mongoose = require('mongoose');

console.log('In renderer');

ipcRenderer.send('ping', 'foo');

ipcRenderer.on('pong', () => {
  console.log('Connecting...');
  mongoose.connect('mongodb://localhost:27017');
  mongoose.connection.once('connected', () => { console.log('connected') });
  mongoose.connection.on('error', err => { console.log('error', err) });
});
```

It seems to connect just fine with Electron 4.0.4 and Mongoose 5.4.14. I'm going to close this issue for now since it's long out of date...
