### ISSUE TITLE
HA reconnection is incomplete

### ISSUE THREAD

**Issue by dlong5** [Automattic/mongoose#4183]
If all connected servers in a mongos ha cluster are disconnected, mongoose queries hang forever even after the HA process reconnects.

To reproduce. Make a mongoS connection to a set of db's. Take down all the db's after the initial connection. Start up the db's and try a query. It never comes back even though the HA process reconnects to the db.
Related issue and code example can be found here. http://stackoverflow.com/questions/35951957/mongoose-stops-responding-after-unspecified-period-of-time

Mongoose version 3.8.40.

At the point the 'disconnected' event is triggered, the HA reconnect process is still trying to reconnect.
My primary question at this point is, am I expected to reconnect or should the HA reconnect process work after the disconnected event has been fired?
Currently I have to reconnect myself, but I also need to stop the ha reconnect process so I don't collect additional unused db connections from the rogue HA reconnect process that didn't shut down. Either the HA reconnect process should stop trying when the mongoose connection is in a disconnected state, or it should automatically connect again for me.

Here is the code I am using to shut down the HA process.
connection.on('disconnected', function() {
  ...
  mongoose.connection.db.serverConfig.close(function() {});
  ... // begin manual reconnect
});

**Comment by vkarpov15** [comment]
Hmm 3.8.x is pretty out of date at this point, have you tried upgrading to 4.x? TBH I'm really rusty with how the old mongodb 1.x driver handled repl set failover...

**Comment by dlong5** [comment]
Haven't tried 4.x. I will look at it if I get a chance this week.
