### ISSUE TITLE
Feature Request: Add LocalStorage support

### ISSUE THREAD

**Issue by tfmontague** [Automattic/mongoose#4187]
Would like to manage my browser's LocalStorage with client-side Mongoose. Can someone suggest code examples - that would allow me to achieve this functionality?

http://mongoosejs.com/docs/browser.html
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

```
<script type="text/javascript" src="//d1l4stvdmqmdzl.cloudfront.net/3.9.6/mongoose.js">
</script>

mongoose.connect('webstorage');

var Cat = mongoose.model('Cat', { name: String });
var kitty = new Cat({ name: 'Zildjian' });
kitty.save(function (err) {
  if (err) // ...
  console.log('meow');
});
```

Thank you,
Tim

**Comment by styopdev** [comment]
Hi @tfmontague, quote from mongoose docs

> The primary goal of mongoose's browser component is to validate documents against a given schema. Because the mongoose browser component doesn't currently support any sort of querying

Only thing you can do is validate documents I don't think it can be useful in this case.

**Comment by tfmontague** [comment]
@styopdev - Client-side and server-side Mongoose should share the same goal. LocalStorage and MongoDB can both store documents. Don't want to use another client-side ORM like
https://github.com/mWater/minimongo, when there's already a stable and well-designed ORM like Mongoose.

If anyone has code examples to use Mongoose with LocalStorage please share. Considering forking and building out a fully functional client-side Mongoose, when my time is less impacted.

**Comment by vkarpov15** [comment]
@tfmontague that would be pretty excellent :) We haven't quite had time to flesh out the client-side of mongoose, plenty of work to stay busy on the server side, so any help would be welcome. However, I'm not sure using localStorage as a drop-in replacement for mongodb as a mongoose backend is a good idea - that will require an extraordinary amount of work.

**Comment by tfmontague** [comment]
@vkarpov15 - Yes, but if you want Mongoose to thrive during the encroaching JWT and RESTful revolution, it needs to come to the browser. These technologies devalue server-side state and database queries, and instead place their dependance on LocalStorage.

**Comment by vkarpov15** [comment]
Errr there's really no encroaching revolution, we've been using REST+JWT for years...
