### ISSUE TITLE
Wrong promise behavior with validation after .catch().

### ISSUE THREAD

**Issue by RayzRazko** [Automattic/mongoose#4189]
Hi guys.

I noticed that promise chain works in a wrong way. I want to catch validation error, handle it and return other kind of errors. Like this:
```
Promise.reject("First").catch(function(err){
    console.log(err);
    return Promise.reject("Second");
}).catch(function(err){
    console.log(err);
});
```

This code example will print:
```
First
Second
```

But if I try to do the same with validation promise it prints first error twice. Let's assume we have some required fields in schema declaration which is used for 'SomeModel' model. Next code will print mongoose validation error twice:

```
new SomeModel({}).validate().catch(function(err){
    console.log(err);
    return Promise.reject("Something other");
}).catch(function(err){
    console.log(err);
});
```

**Comment by vkarpov15** [comment]
Try using an alternative promise library: http://mongoosejs.com/docs/promises.html . I'll look into this but I'd imagine it's an issue with [mpromise](https://www.npmjs.com/package/mpromise), mongoose's default promises library, being hopelessly obsolete. Thankfully it's a one-liner to swap it out :muscle:
