### ISSUE TITLE
Modifying an array's contents does not mark field as modified

### ISSUE THREAD

**Issue by dhritzkiv** [Automattic/mongoose#4190]
mongoose v4.4.19; node v6.2.0

---

Changing an array's contents doesn't mark it as complete. This was not an issue until the last version or two.

Simple test case code [(also runnable in TonicDev [with small `save` workaround])](https://tonicdev.com/dhritzkiv/574caaf198265b1300bc1593)

```js
"use strict";

const mongoose = require("mongoose");

const fooSchema = new mongoose.Schema({
    tags: [{
        type: String
    }]
});

const Foo = mongoose.model('Foo', fooSchema);

const foo = new Foo({
    tags: ["Bar"]
});

console.log(`modified paths before:`, foo.modifiedPaths());

foo.save((err, foo) => {
    console.log(`tags before:`, foo.tags); //["Bar"]

    foo.tags[0] = "Baz";

    console.log(`tags after:`, foo.tags); //["Baz"]
    console.log(`modified paths after:`, foo.modifiedPaths()); //reports as []; should be ["tags"]
});

```

**Comment by vkarpov15** [comment]
Look at question 1 on the FAQ: http://mongoosejs.com/docs/faq.html . This is a really old limitation of mongoose and one that we have no good way to work around in ES5. Use `foo.tags.set(0, 'Baz');` instead.

**Comment by dhritzkiv** [comment]
Sorry about that! I should've known better.
