### ISSUE TITLE
Merging POJOS into mongoose documents

### ISSUE THREAD

**Issue by varunjayaraman** [Automattic/mongoose#4191]
`Mongoose version: 4.3.2`

Not sure if this is an issue or if I'm just using mongoose arrays incorrectly, but I have a custom merger function that merges a POJO into a mongoose document, but it is causing issues with document validation for a schema nested within an array, nested within a schema. Here's the context:

```
var AddOn = new mongoose.Schema({
  priceType: String,
  priceCents: {
    type: Number,
    validate: {
      validator: function(v) {
        console.log('this', this) // logs out the space document AND the individual addons after running the custom merger func, when it should only log out the addons
        return this.priceType === 'FREE' ?
          !v :
          v;
      }
    }
  }
})

var Space = new mongoose.Schema({
  data: {
    addOns: [AddOn]
  }
})

var Venue = new mongoose.Schema({
  data: {
    spaces: [Space]
  }
})
```

This is all fine and dandy up until I attempt to merge a POJO into a mongoose document using a custom merger function. This is the file from which I export the merger function (it gets instantiated as a dependency to be injected, so it's exported as a function that executes and returns the actual function applyChanges)

```
'use strict';

var _ = require('lodash');

module.exports = function() {
  function getChanges (obj) {
    var updates = [];

    getPathAndValues(obj);
    return updates;

    function getPathAndValues(obj, path) {
      for( let p in obj) {
        if (_.includes(['[object Object]'], Object.prototype.toString.call(obj[p]))) {
          getPathAndValues(obj[p], (path ? path + p : p) + '.' );
        } else {
          updates.push({path: (path ? path + p : p), value: obj[p]});
        }
      }
    }
  };

  return function applyChanges(obj, update, allowedPaths) {

    var updates = getChanges(update);
    _.each(updates, function(update, updateKey) {
      var checkRegexp = function(re) {
        return re.test(update.path);
      };

      if (allowedPaths && _.some(allowedPaths, checkRegexp)) {
        _.set(obj, update.path, update.value)
      }
    });

    return obj;
  };

};
```

The object being updated is a venue, which is a mongoose document, and the update passed into `applyChanges` is a POJO.

I should note that BEFORE this updater function runs, the `console.log` in the `AddOn` schema validator logs out only addons as `this`. Afterwards, it also logs out the space document (and in my actual db, venues have addons too as `venue.data.addOns`, and the venue gets logged out as well in that case, but i've omitted that for simplicity here). 

The validation obviously fails because a `Space` does not have a property `priceType`, and so the validator will only return true if `priceCents` is truthy, which it isn't in the case of a `Space`. This is the error I get when there is 1 addon in a space:

```
{ [ValidationError: venues validation failed]
  message: 'venues validation failed',
  name: 'ValidationError',
  errors: 
   { 'data.spaces.0.data.addOns.0.priceCents': 
      { [ValidatorError: Add-on price is required if the price type is not free]
        properties: [Object],
        message: 'Add-on price is required if the price type is not free',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'priceCents',
        value: 0 }
     
```

Any idea why this is happening? I suspect it must have something to do with the fact that a mongoose document's array, within which a schema is nested, is getting replaced by a POJO array, but I could be wrong. 

And if I am doing this incorrectly, is there a better alternative to merging POJOS into mongoose docs? I thought of invoking `.toObject()` on the mongoose document, using a lodash `merge`, and then reconverting to a mongoose document with `new mongoose.Document(obj, Venue)`, but that throws an error that mongoose can't `read 'options' of undefined`.

**Comment by Jeff-Lewis** [comment]
With just looking at the code, here are my thoughts:
- Check `getPathAndValues` in the order that is creates the list of fields in `updates`. It appears `applyChanges` runs through the changes sequentially although the objects and their paths are nested. Is it setting a parent path after child path?
- try using mongoose's `.set` function to set the values

**Comment by varunjayaraman** [comment]
@Jeff-Lewis Regarding your first bullet point, I don't think so because when `getPathAndValues` encounters an array, it just replaces the original array with the new array rather than looping through the array and individually taking each item at each index.

i.e the update path for the first addon is not `data.spaces.addOns.0` but `data.spaces`, and then the entire spaces array just gets replaced.

mongoose `.set` didn't do anything :/

I'll work on getting a mini repo to help repro the issue now

**Comment by varunjayaraman** [comment]
Fixed - definitely not an issue with mongoose, problem was on our end

**Comment by vkarpov15** [comment]
Good catch @varunjayaraman, hope things are going well over in SixPlus land 👍
