### ISSUE TITLE
findById error - Cast to ObjectId failed for value at path

### ISSUE THREAD

**Issue by WiHHi-Z3-PuX** [Automattic/mongoose#4192]
I can see some similar issues, but in this case the _id is an ObjectId and it does exist, so it's probably a different bug/case. if not, feel free to merge it.

I have a very simple schema (one of them anyway), which is causing me problems:

```
var wordSchema = new Schema({
    word: {
        type: String,
        minlength: 2,
        maxlength: 20,
        required: true,
        unique: true
    }
});
```

when I try findById in the router, I get "Cast to ObjectId failed for value" ... "at path word".

in fact I don't really need findById, but I realized that's what is causing the issue after some googling. what I really need is to send a random document from this model/schema (in response to a GET request). I have tried 3 mongoose random modules, all fail. in a different router where I am using a different schema/model it works perfectly and I can get random documents.

here's what a document looks like, I checked manually with db.getCollection('words').find({}):

```
{
    "_id" : ObjectId("574dc4d7568193d42dc1d1d1"),
    "word" : "blurple",
    "__v" : 0
}
```

any ideas why the findById is not working? mongoose version: 4.4.19.

edit: just in case, here's the first step of what I'm trying to do in the router:

```
wordRouter.route('/random')
    .get(function (req, res, next) {
        models.Words.findOneRandom(function (err, wordObj) {
            if (err) next(err);
        
            res.json(wordObj);
        });
    });
```

findOneRandom is from mongoose-simple-random

**Comment by WiHHi-Z3-PuX** [comment]
omg, I have tried everything by now:

changing the schema to make it simpler
renaming the schema and the model
adding extra "columns" in the schema
adding the words with a separate route where nothing else is done

and it never ever works.

meanwhile in another schema which is basically identical to the one I'm having trouble with it works after the first attempt.

```
var tagSchema = new Schema({
    tag: {
        type: String,
        minlength: 2,
        maxlength: 20,
        required: true,
        unique: true
    },
    nused: {
        type: Number,
        default: 1
    }
});

tagRouter.route('/random')
    .get(function (req, res, next) {
        models.Tags.findOneRandom({}, null, {}, function (err, tag) {
            if (err) next(err);
            if (err) console.log(err);

            console.log(tag);

            res.json(tag);
        });
    });
```

**Comment by WiHHi-Z3-PuX** [comment]
I rewrote the wordRouter with only 2 routes: create and random. and it worked.

so my best guess is that comments cause the "Cast to ObjectId failed for value at path ..." error. I had lots of older routes commented out.

**Comment by vkarpov15** [comment]
Re: random doc, [use `$sample`](https://docs.mongodb.com/manual/reference/operator/aggregation/sample/):

```javascript
models.Tags.aggregate([{ $sample: 1 }]).exec(function(error, docs) {
  // docs[0] contains a random doc
});
```

Also see my article on the subject: http://thecodebarbarian.com/node-perspective-on-mongodb-3.2-$lookup-$sample

Also, how are you using `findById`? I don't see any code samples that involve `findById` in your issue report...

**Comment by WiHHi-Z3-PuX** [comment]
it looked like this.
```
models.Words.findById("574ee6b3a63db66c2f40ccd6", function (err, word) {
    if (err) throw err;
        
    res.json(word);
});
```

 I also tried 
`models.Words.find({"_id": "574ee6b3a63db66c2f40ccd6"} ...`
and always had the Cast to ObjectId error.

but after rewriting the whole router I have no issues, it was either the comments getting in the way or a typo.

**Comment by vkarpov15** [comment]
Possibly, that's a perfectly valid objectid and works fine for me. I'm gonna close this, re-open if the issue pops up again :+1:
