### ISSUE TITLE
Unable to update a model from a cronJob

### ISSUE THREAD

**Issue by FrakyFrog** [Automattic/mongoose#4193]
The code below does not work. It used to work with mongoose v4.3.4, and it goes through all the way (it prints current, set and saved doc) but does not make the changes to the document.

I noticed this issue on a heroku system, all I did was rollback to v4.3.4 on mongoose and it worked again.

````Javascript
new CronJob('* * * * * *', function() {
  var todayTimestamp = Moment(new Date()).format('x');
  Normering.find({
    archivedStart: { $exists: false }
  }).then(function(normering){
    normering.forEach(function(norm){
      var normeringStart = Moment(norm.start).format('x');
      if(todayTimestamp >= normeringStart){
        var data = norm.data;
        var query = {
          _id: data._id
        };

        Model.findOne(query)
            .then(function(doc) {
              console.log('current document:', doc);
              doc.set(data);
              console.log('set document:', doc);

              doc.save().then(function(doc) {
                console.log('saved document:', doc);
              });
            }).then(function() {
          norm.archiveStart();
        });
      }
    });
  });
});
````

**Comment by vkarpov15** [comment]
@FrakyFrog sorry for taking so long to get to this. What do your schemas look like and what does the data look like? Don't see any reason why this shouldn't work in any version of mongoose

**Comment by FrakyFrog** [comment]
The data is a replica of the "current doc" with some modifications made. For example there is one schema /model named employee who has firstname, lastname etc along with hourly rate. the data in this case has a different value on the hourly rate and tries to update the document but fails. It although prints all down to "saved doc .." but does not update the document itself.

**Comment by vkarpov15** [comment]
What does 'The data is a replica of the "current doc" with some modifications made' mean? Code samples please?
