### ISSUE TITLE
How to access the created/updated sub-document?

### ISSUE THREAD

**Issue by mtvs** [Automattic/mongoose#4194]
I noticed when you save a parent document, the `save` middleware of its sub-document`s schema is called for all of the sub-documents.

Is there a way that you can access the created/updated sub-document?

    subDocSchema.post('save'. function (doc) {
        console.log(doc);
    }

then

    parent.subDocs.push({note: 'new doc'});
    parent.save();

results

    // {note: 'new doc'}
    // {note: 'old doc'}
    // ...

**Comment by vkarpov15** [comment]
I'm sorry, I don't understand the question, can you please clarify? In my mind it looks like you've got the answer to your question in your code samples.

**Comment by mtvs** [comment]
@vkarpov15 Normally when a document is saved the pre/post save middleware of its schema are called with the newly created/updated doc but when a sub-doc is created/updated by changing the document-array inside its parent document and then saving the parent document the pre/post save middleware of the sub-document schema are called for all the sub-docs not just the newly created/updated one.

So how are you supposed to detect the new one to for example emit an event with that?

**Comment by vkarpov15** [comment]
Documents, including subdocs, [have an `isNew` property](http://mongoosejs.com/docs/api.html#document_Document-isNew) that tells you whether the doc has been saved to the db or not.

```javascript
subDocSchema.post('save'. function (doc) {
  if (doc.isNew) {
    console.log('new doc', doc);
  }
});
```

**Comment by mtvs** [comment]
@vkarpov15 Inside post save middleware of the sub document schema, `isNew` is false for all the sub documents.

I think this behavior (execution of save middleware for all sub docs) is something against the expectation and also a development obstacle.

**Comment by vkarpov15** [comment]
Yeah because after you save, `isNew` will always be false. Take a look at #1474 for a workaround.

And IMO it's the correct behavior - save middleware happens for parent docs regardless of whether or not there's anything to save, so makes sense that the child docs get the same behavior too.

**Comment by mtvs** [comment]
@vkarpov15 Ok, thanks for your help.
