### ISSUE TITLE
Documentation regarding accessing native mongodb driver inaccurate

### ISSUE THREAD

**Issue by basickarl** [Automattic/mongoose#4195]
[Native driver find from Mongoose model not returning Cursor](https://stackoverflow.com/questions/10588808/native-driver-find-from-mongoose-model-not-returning-cursor)
[Mongoose and native mongodb driver api 2.1 issue](https://stackoverflow.com/questions/37574032/mongoose-and-native-mongodb-driver-api-2-1-issue)

[Node.js MongoDB Driver API 2.1](https://mongodb.github.io/node-mongodb-native/2.1/api/Collection.html#find)

Now onto what the mongoose documentation states:

http://mongoosejs.com/docs/guide.html can't find it there, not clear enough.

However on the github page: https://github.com/Automattic/mongoose#driver-access

> Driver Access
> 
> Mongoose is built on top of the official MongoDB Node.js driver. Each mongoose model keeps a reference to a native MongoDB driver collection. The collection object can be accessed using YourModel.collection. However, using the collection object directly bypasses all mongoose features, including hooks, validation, etc.

This is inaccurate. The native driver does not work as it should. Why? Look at the stackoverflow answer linked:

> The native driver methods are all proxied to run on the nextTick so return values from the driver are not returned.

An update of the documentation is required to give users this information to help stop wasting of hours trying to debug.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, I got bit by this once or twice in the past. Will fix 🌴

**Comment by basickarl** [comment]
:+1: :+1: :+1:
