### ISSUE TITLE
update 3 arrays in a model at a time using "$addToSet"

### ISSUE THREAD

**Issue by nasr18** [Automattic/mongoose#4201]
Is it possible to update 3 arrays within a model at a time using `$addToSet`??

**Comment by nasr18** [comment]
@vkarpov15

**Comment by vkarpov15** [comment]
Sure, I don't see why not.

**Comment by nasr18** [comment]
but it is not working for me. if not exists means, it should insert. if already present it should omit that.

**Comment by vkarpov15** [comment]
I don't understand, please provide code samples

**Comment by nasr18** [comment]
i'm using `multiple select` and select multiple `tags`, `categorys` and `locations` and have to save into the particular `schema`.

```
Article.findByIdAndUpdate(article._id, {
            title: article.title,
            summary: article.summary,
            date: Date.parse(article.date),
            imgUrl: article.imgUrl,
            $addToSet:{category:{$each:categoryIds}},
            $addToSet:{tags:{$each:tagIds}},
            $addToSet:{location:{$each:locationIds}}
            description: article.description,
            author: article.author,
            link: article.link,
            guid: article.guid,
            updatedBy: req.user._id,
            updatedOn: new Date()
        }, {new:true}).exec(function(err, article) {
            if(err) console.log('bulkupdate findByIdAndUpdate err:', err);
            cb();
        });
```

if `tags` already exists means it should omit that tags and have to insert new `tags`, likewise for `categorys` and `locations`. but what i'm getting something different, really i cant understand whats happening and looking the result. @vkarpov15

**Comment by vkarpov15** [comment]
Try this:

```javascript

**Comment by nasr18** [comment]
ok will check it and let you know.
