### ISSUE TITLE
$addToSet doesn't work in nested object

### ISSUE THREAD

**Issue by mauvew** [Automattic/mongoose#4203]
Mongoose fails to update $addToSet for nested object. Let's say we have the following document:

```
{
  id: '001',
  assignments:{
    one:[
      {oneId: 'aaa'},
      {oneId: 'bbb'}
    ] 
  }
}
```
```
Schema.update({
  id: '001'
},{
  $addToSet: {
    'assignments.one': {oneId: 'ccc'}
  }
},{
  new: true
})
```
This doesn't work and will not modify the document.

However, using the same way in MongoDB command works well and do modify the document. Any thoughts of why this happens?

**Comment by mauvew** [comment]
mongoose version: 4.0.3
mongoDb version: 3.2.4

To reproduce:
```
'use strict';


var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var Cat = mongoose.model('cat', {
  _id: String,
  assignments: Object
});

          
Cat.update(
{_id: '01'},{
$addToSet: {
          'assignments.course': {
          	'OneId': 'ccc'
          }
}
}, function(err){
});
```

**Comment by vkarpov15** [comment]
That's strange, looks like it's executing the correct query in both 4.4.20 and 4.0.3:

```javascript
'use strict';

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

mongoose.set('debug', true);

var Cat = mongoose.model('cat', {
  _id: String,
  assignments: Object
});


Cat.update(
{_id: '01'},{
$addToSet: {
          'assignments.course': {
            'OneId': 'ccc'
          }
}
}, function(err){
});
```

Prints out:

```
$ node gh-4203.js 
Mongoose: cats.update({ _id: '01' }) { '$addToSet': { 'assignments.course': { OneId: 'ccc' } } } {} 
^C
```

How are you determining that the doc is not modified?

**Comment by mauvew** [comment]
thanks for the reply. 

For me, after executing, there is no error, but the document just not updated in the database. My laptop just broken and is being repaired. I will give it a go once I got my laptop and provide evidence.

**Comment by vkarpov15** [comment]
Issue's gone stale, closing
