### ISSUE TITLE
find().where().within() callback call

### ISSUE THREAD

**Issue by earthiverse** [Automattic/mongoose#4204]
I am using the following versions of things:
Mongoose 4.4.19
Node 6.2.0

I am using the following code:

	var tableSchema = new mongoose.Schema({
	  type: String,
	  properties: {
	    comment: String,
	    updated: Number
	  },
	  geometry: {
	    type: String,
	    coordinates: [Number]
	  }
	}, {collection: 'tables'});

	tableSchema.statics.within = function(bounds, callback) {
	  console.log(bounds);
	  this.find({}, null, null, callback).where("geometry").within(bounds);
	}

Example Document:

	{
	        "_id" : ObjectId("574f59e0f90c710858289338"),
	        "properties" : {
	                "dataset_name" : "Public Picnic Table Locations",
	                "source" : "https://data.edmonton.ca/Facilities-and-Structures/Public-Picnic-Table-Locations/vk3s-q842",>
	                "source_name" : "Edmonton Open Data Portal",
	                "comment" : "A square picnic table made from metal and composite materials.",
	                "license" : "http://www.edmonton.ca/city_government/documents/Web-version2.1-OpenDataAgreement.pdf"
	        },
	        "type" : "Feature",
	        "geometry" : {
	                "coordinates" : [
	                        -113.451420457284,
	                        53.5310049552461
	                ],
	                "type" : "Point"
	        }
	}

When I set bounds to `{}` it fails with the following error:

> {}
>TypeError: Invalid argument
>    at Query.within (/home/ubuntu/picknic/node_modules/mquery/lib/mquery.js:754:9)
>    at Function.tableSchema.statics.within (/home/ubuntu/picknic/app/table/model.js:19:67)
>    at /home/ubuntu/picknic/app/table/routes.js:13:23
>    at Layer.handle [as handle_request] (/home/ubuntu/picknic/node_modules/express/lib/router/layer.js:95:5)
>    at next (/home/ubuntu/picknic/node_modules/express/lib/router/route.js:131:13)
>    at Route.dispatch (/home/ubuntu/picknic/node_modules/express/lib/router/route.js:112:3)
>    at Layer.handle [as handle_request] (/home/ubuntu/picknic/node_modules/express/lib/router/layer.js:95:5)
>    at /home/ubuntu/picknic/node_modules/express/lib/router/index.js:277:22
>    at Function.process_params (/home/ubuntu/picknic/node_modules/express/lib/router/index.js:330:12)
>    at next (/home/ubuntu/picknic/node_modules/express/lib/router/index.js:271:10)
>    at /home/ubuntu/picknic/node_modules/body-parser/lib/read.js:129:5
>    at invokeCallback (/home/ubuntu/picknic/node_modules/raw-body/index.js:262:16)
>    at done (/home/ubuntu/picknic/node_modules/raw-body/index.js:251:7)
>    at IncomingMessage.onEnd (/home/ubuntu/picknic/node_modules/raw-body/index.js:308:7)
>    at emitNone (events.js:86:13)
>    at IncomingMessage.emit (events.js:185:7)

but still executes the callback with no error (set to null) and all documents in the collection.

It works as expected when passed this valid GeoJSON object (returns all points in the area):
`{"type": "Polygon", "coordinates": [[[-113.49083,53.54337],[-113.49099,53.54446],[-113.48913,53.54457],[-113.48892,53.54347],[-113.49083,53.54337]]]}`

-----

I tried the following instead, which doesn't execute the callback when passed the empty JSON object, but it doesn't work with the same GeoJSON object that worked before.

	tableSchema.statics.within = function(bounds, callback) {
	  console.log(bounds);
	  this.find().where("geometry").within(bounds).exec(callback);
	}

I get this error instead:
>Error: Can't use $geoWithin with String.
>    at SchemaString.castForQuery (/home/ubuntu/picknic/node_modules/mongoose/lib/schema/string.js:491:13)
>    at cast (/home/ubuntu/picknic/node_modules/mongoose/lib/cast.js:169:39)
>    at Query.cast (/home/ubuntu/picknic/node_modules/mongoose/lib/query.js:2580:10)
>    at Query.find (/home/ubuntu/picknic/node_modules/mongoose/lib/query.js:1088:10)
>    at /home/ubuntu/picknic/node_modules/mongoose/lib/query.js:2174:21
>    at new Promise.ES6 (/home/ubuntu/picknic/node_modules/mongoose/lib/promise.js:45:3)
>    at Query.exec (/home/ubuntu/picknic/node_modules/mongoose/lib/query.js:2167:10)
>    at Function.tableSchema.statics.within (/home/ubuntu/picknic/app/table/model.js:20:58)
>    at /home/ubuntu/picknic/app/table/routes.js:13:23
>    at Layer.handle [as handle_request] (/home/ubuntu/picknic/node_modules/express/lib/router/layer.js:95:5)
>    at next (/home/ubuntu/picknic/node_modules/express/lib/router/route.js:131:13)
>    at Route.dispatch (/home/ubuntu/picknic/node_modules/express/lib/router/route.js:112:3)
>    at Layer.handle [as handle_request] (/home/ubuntu/picknic/node_modules/express/lib/router/layer.js:95:5)
>    at /home/ubuntu/picknic/node_modules/express/lib/router/index.js:277:22
>    at Function.process_params (/home/ubuntu/picknic/node_modules/express/lib/router/index.js:330:12)
>    at next (/home/ubuntu/picknic/node_modules/express/lib/router/index.js:271:10)

-----

I can change the code to the following (`"geometry"` -> `"geometry.coordinates"`), but then it will only work with points, whereas I also need polygons inside polygons. The first one works for finding polygons within polygons.

	tableSchema.statics.within = function(bounds, callback) {
	  console.log(bounds);
	  this.find().where("geometry.coordinates").within(bounds).exec(callback);
	}

Any suggestions or help would be much appreciated. I've found issues that are kind of related ( #4014 and #4044 ).

**Comment by vkarpov15** [comment]
There's a couple mistakes in your code.

First, don't do this:

```javascript
tableSchema.statics.within = function(bounds, callback) {
  console.log(bounds);
  this.find({}, null, null, callback).where("geometry").within(bounds);
}
```

Modifying a query after you passed in the callback will not work as you expect. Do this instead:

```javascript
tableSchema.statics.within = function(bounds, callback) {
  console.log(bounds);
  this.find().where("geometry").within(bounds).exec(callback);
}
```

Also, there's a bug in your schema. Look closely, you'll see that you're actually defining `geometry` as a field of type 'string'.

```javascript
var tableSchema = new mongoose.Schema({
  type: String,
  properties: {
    comment: String,
    updated: Number
  },
  geometry: {
    type: String, // <-- This means 'geometry' is **not** a nested object, but a string
    coordinates: [Number]
  }
}, {collection: 'tables'});
```

Do this instead:

```javascript
var tableSchema = new mongoose.Schema({
  type: String,
  properties: {
    comment: String,
    updated: Number
  },
  geometry: {
    type: { type: String },
    coordinates: [Number]
  }
}, {collection: 'tables'});
```

If you want to avoid this mistake in the future, you can either define a geojson point schema and use it:

```javascript
var pointSchema = new mongoose.Schema({
  type: { type: String },
  coordinates: [Number]
});

var tableSchema = new mongoose.Schema({
  type: String,
  properties: {
    comment: String,
    updated: Number
  },
  geometry: pointSchema
}, {collection: 'tables'});
```

Or use the [`typeKey` option](http://mongoosejs.com/docs/guide.html#typeKey):

```javascript
var tableSchema = new mongoose.Schema({
  type: String,
  properties: {
    comment: String,
    updated: { $type: Number } // <-- typeKey: `$type` means mongoose will look for `$type`
  },
  geometry: {
    type: String,
    coordinates: [Number]
  }
}, {collection: 'tables', typeKey: '$type'});
```

**Comment by Siegoboy** [comment]
@vkarpov15 Thanks for all the support and help with all the issues. You are doing a great job, tahnks man.

**Comment by vkarpov15** [comment]
@Siegoboy thanks! I appreciate the kind words.
