### ISSUE TITLE
something about the mongoose.Error.messages

### ISSUE THREAD

**Issue by aweiu** [Automattic/mongoose#4207]
### Q1:why i can't change the Object by this way?
```
mongoose.Error.messages={
    general: {
        default: 'some tips',
        required: 'some tips'
    }
    ....
}
```
but it can work by this:
```
mongoose.Error.messages.general.default='some tips'
mongoose.Error.messages.general.required='some tips'
```

### Q2:how can i hook the ValidationError?
for example:
```
new Schema({
    key:{
        type:String,
        required:true,
        remark:'remarkName'
    }
})
```
when it has a wrong validation,i will get the ValidationError that likes 'Path **key** is required.' ,but i want it is 'Path **remarkName** is required.'(the remarkName is in Schema)

- i try to use the 'pre save' hook,but it won't be called when it has a wrong validation.
- i try to use the 'pre validate' hook,you konw,it will be called before valide,so i can't change the ValidationError too
- i try to change the mongoose.Error.messages,but it just has these templatings:
**PATH**,**VALUE**,**TYPE**,**MIN**,**MAX**!But no "**remark**" that i need!And no way to add a new templatings

so, i'm very very need your help,please!Thank you very much!

**Comment by aweiu** [comment]
now,i complete the Q2 by handling these errors at the Model level.

**Comment by vkarpov15** [comment]
For q2, there will be a mechanism to do this in 4.5, see #2284. Re: q1, not sure, I need to check

**Comment by aweiu** [comment]
@vkarpov15 thank you for your reply
i do it in this way:
all models in my project is created by this fuction: 
```
function myModel(collectionName,schema){
    var mySchema = new db.Schema(schema)
    mySchema.pre('save', function (next) {
        //in this callback,you can run your coustom validation after defult validation
        //the '**validator**' fuction has the argument:**schema**,it means that you can also style your validation rules in **schema** !
        var errMsg=validator(schema,this._doc)
        if(errMsg)throw Error(errMsg)
    })
    var myModel = db.model(collectionName, mySchema)
    myModel.on('error', function (error) {
        //in this call back,you can change the defult errorMessage,even expand errorMessage templatings(just like {REMARK},{ENUM},etc)
        if (error.name == 'ValidationError') {
            for (let path in error.errors) {
                var tree = this.schema.tree[path],
                    remark = tree.remark || path
                throw Error(error.errors[path].message
                  .replace(/\{REMARK\}/g, remark)
                  .replace(/\{ENUM\}/g, tree.enum)
                );
            }
    } else {
        throw error
    }
    return myModel
}
```
now,i'm thinking that how can i hook all the db event,not only save,but also find,findById,update,etc...
i'm still waiting your help,Thank you

**Comment by vkarpov15** [comment]
I don't understand your comment, can you please clarify?
