### ISSUE TITLE
Improve VersionError

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#4211]
We have a document with several arrays and we constantly get VersionErrors across our code. From my understanding the `__v` key doesn't distinguish different array. So for example updating doc.array1 and doc.array2 can trigger the error even though 2 different arrays were updated.

Could `__v` be changed to do versioning separately for each array?

```
__v: {
   array1: 1,
   array2: 2,
}
```

**Comment by vkarpov15** [comment]
Yeah that's definitely something we need to improve. As a workaround you can turn off versioning or just overwrite the whole array every time

**Comment by sibelius** [comment]
we only have versionError for arrays

is there anything we can do to fix this?

**Comment by sibelius** [comment]
what is the proper way to debug VersionError errors?

**Comment by vkarpov15** [comment]
@sibelius it's hard for me to provide any advice without more info. You can take a look at [the blog post that introduced versioning](http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html). But generally speaking, VersionError occurs when you have two copies of a document, you modify an element in a document array in one, you remove an element from the same document array in another, and you try to `save()`. Here's an example:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh4211`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  const schema = Schema({ arr: [{ name: String }] });
  const Model = mongoose.model('Test', schema);

  await Model.create({ arr: [{ name: 'test' }] });

  const doc1 = await Model.findOne();
  const doc2 = await Model.findOne();

  doc1.arr.pop();
  await doc1.save();

  doc2.arr[0].name = 'test2';
  await doc2.save(); // VersionError
}
```

**Comment by sibelius** [comment]
I think this only happens when we are using a replica set

**Comment by vkarpov15** [comment]
@sibelius can you provide any code samples or any more info?

**Comment by sibelius** [comment]
This happens if user call REST endpoint or GraphQL mutation very fast

so each instance will have different versions (lock problems)

is there a way to solve this?

we moved our array operations to use `findOneAndUpdate` and `$addToSet`/`$pull`

so we won't have any version conflict

**Comment by vkarpov15** [comment]
Looks like you found a solution. Without any other code samples I can't really venture a guess as to how you can solve this other than one of the below solutions:

1) Disable versioning
2) Overwrite the whole array every time instead of using `$addToSet` and `$pull`.
