### ISSUE TITLE
Handle deeply nested populate not working for me

### ISSUE THREAD

**Issue by 1izpena** [Automattic/mongoose#4214]
I have mongoose version 4.
I have nested schemas: comment, task and userstory.
Userstory has tasks, and tasks have comments.
Comments have an external ref. of other model: User.
Well, once the first populate (userstory with task), I want get comments.
I have the following method to doing nested populate, where value is userstory populated with task:

         async.forEach(value,function(item,callback) {

                User.populate(item, {
                        path: 'tasks.createdby tasks.assignedto tasks.contributors',
                        select: 'username mail _id'
                    },
                    function(error,output) {

                        User.populate(output, {
                                path: 'comments._user',
                                select: 'username mail _id'
                            },
                            function(error,output2) {

                                 parseuserstory = output2.parse();
                                 arrUserstories.push(parseuserstory);

                                callback();

                            });

                    });

            }, function(err) {

                return promise.done(err, arrUserstories);

            });

This doesn't work, but I don't know why.
Any idea?
Thank you very much.

**Comment by vkarpov15** [comment]
Can you show me your schemas? It looks like you're trying to do 2 unrelated populates one after the other.
