### ISSUE TITLE
Validation fails when removing a single embedded sub document

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4216]
I might be doing something wrong, but I can't figure out what.

I have an `event` schema with a `recurrence` sub schema, defined as follows (simplified):

```js
let RecurrenceSchema = new Schema({
  frequency: Number,
  interval: {
    type: String,
    enum: ['days', 'weeks', 'months', 'years']
  },
  //...
}, {
  _id: false
});

let EventSchema = new Schema({
  name: {
    type: String,
    trim: true
  },
  recurrence: RecurrenceSchema,
  //...
});
```

When I create a new event with no recurrence, e.g. `event.recurrence = null`, this gets saved in the database as `null` and works fine.

However, when I try to edit an event and *remove* the recurrence from it, the validation keeps tripping up.

I have tried the following methods:

```js
//Throws validation error `null` is not a valid enum value for path `interval`
event.recurrence = null;
event.save();
```

```js
//Throws validation error `null` is not a valid enum value for path `interval`
event.recurrence.remove();
event.save();
```

```js
//Doesn't remove the recurrence from the DB
delete event.recurrence;
event.save();
```

How can I remove the recurrence sub document without tripping up the validation? 

It seems Mongoose is trying to populate all the fields of the sub document with `null` rather than just setting it to `null`, which then breaks validation for fields that are enum or required.

**Comment by vkarpov15** [comment]
Hmm looks like a bug. Will fix early next week, thanks for reporting.

**Comment by adambuczynski** [comment]
@vkarpov15 based on your commit, should I deduce that the proper way of removing a subdocument is with the `doc.subdoc.remove()` call?

Or should it also work by setting `doc.subdoc = null`?

**Comment by vkarpov15** [comment]
Nah I'd argue that setting to null is probably the most correct way

**Comment by adambuczynski** [comment]
Yep, it seems to work in `master`, thanks!
