### ISSUE TITLE
Emptying a subschema doesn't mark the field as modified

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#4218]
```
{
    object: {
       nested: {
           field1: {type: Number, default: 1},
       }
   },
}
```

`doc.object.nested = {}`
`doc.modifiedPaths().indexOf('object.nested') === -1` -> is this expected?

Saving the doc won't save the new `object.nested` because it's not marked as modified

**Comment by vkarpov15** [comment]
Yeah that's a bug if that's the case. Will take a look early this week.
