### ISSUE TITLE
Mongoose does not connect when passed url string with replica set

### ISSUE THREAD

**Issue by ganarajpr** [Automattic/mongoose#4220]
I had a strange issue when attempting to connect to a mongo ( with replica sets in url )

In config the url looks like this :

`mongodb://user:pass@dev-mongodb-1.project-dev.local:27017,dev-mongodb-2.project-dev.local:27017/db`

```javascript
    var mongoose = require('mongoose');
    mongoose.connect(config.mongoUrl, function(err){
        if(err) {
            console.log('Mongo Connection error', err);
            return;
        }
        console.log('connected to mongo');
    });

```

This code works fine with `mongoose@4.2.6`.

Code hangs with `mongoose@4.4.19` and `mongoose@4.4.20`

**Comment by vkarpov15** [comment]
Hmm that's strange. Any particular reason why you can't use 4.2.6? I'd rather avoid diving into year old releases if possible :)

**Comment by ganarajpr** [comment]
I can :) I just flagged it here because it seems like the problem that has surfaced in the later releases.

**Comment by vkarpov15** [comment]
Does the problem appear in 4.4.x?

**Comment by ganarajpr** [comment]
Sorry let me correct that. I got the numbers messed up when typing. 

 It works fine in `4.2.6` but does not work fine in `4.4.19` and `4.4.20`.

**Comment by ganarajpr** [comment]
So I did some further testing on this: Trying to go older and older in the 4.x series with the same url.

It looks like the replica set url was ( almost ) never working on the `4.x` series. I was wrong again about reporting `4.2.6` working. In `4.2.6` I never got a message back on the terminal stating that the connection was established. It used to just exit to the terminal back after the connection , while on 4.4.x it would just stay there without any message. 

The one version which seemed to work fine is `3.8.40` ( I dint try older versions of `3.x` ). I do get back a message stating that it connected to mongo ( JS connection though, not bson). 

On `4.1.x` and such the code just throws errors and exits to the terminal.

**Comment by vkarpov15** [comment]
What version of mongodb does your repl set use?
