### ISSUE TITLE
Model.findOneAndUpdate overwrites `fields` option

### ISSUE THREAD

**Issue by letsgolesco** [Automattic/mongoose#4221]
When a `fields` property is included in the options for `Model.findOneAndUpdate`, it is overwritten in the function.

I noticed this because I have a static object in my code that indicates which document fields should be selected in my `findOneAndUpdate` call, like so:
```javascript
var options = {
    fields: '+password',
    new: true,
    runValidators: true
};
```

It works fine the first time, but on subsequent calls I see that `options.fields` is set to `undefined`. This happens on line 1463 of lib/model.js as of commit 048b776 (see here: https://github.com/Automattic/mongoose/blob/master/lib/model.js#L1463).

I'm not sure why this behaviour was implemented (it's been this way since f3d5015 in 2012) but it seems like bad practice in general to mutate variables passed into functions (ideally you'd clone them if you need to do any mutation).

**Comment by vkarpov15** [comment]
Yeah TBH I'm not sure why that code is there. I'll get rid of it.
