### ISSUE TITLE
inque indexing is not working

### ISSUE THREAD

**Issue by zahiruldu** [Automattic/mongoose#4225]
I am using mongodb 3.2X and mongoose 4.4X. My Schema is 
 

   email: { type: String, unique: true, index: true, lowercase:true },
    api_key: { type: String, index:true, unique:true},

Here unique indexing by mongoose is not working. I can insert same value again and again.

But if I make the unique indexing manually from mongo shell it works perfectly. Would you let me know how I can fix this problem from mongoose?

**Comment by vkarpov15** [comment]
Your index build is probably failing for some reason. Set the [`emitIndexErrors` option to true on your schema](http://mongoosejs.com/docs/guide.html#emitIndexErrors) and mongoose will show you what the error is. Or you can just listen to mongoose model's 'index' event, which reports when the index build succeeded or failed `Model.on('index', function(error) {});`
