### ISSUE TITLE
Docs for error handling middleware

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#4229]

**Comment by JustinLivi** [comment]
Is this feature available in the latest mongoose release? I'm trying to write a plugin to handle all my errors and convert them to a format digestible by the rest of my application. I don't necessarily need full documentation, just a pointer in the right direction if it's possible.

Thanks!

**Comment by vkarpov15** [comment]
Yep it's available. The only docs are the tests unfortunately, will add these docs early next week

**Comment by JustinLivi** [comment]
Thanks! Found what I was looking for here: https://github.com/Automattic/mongoose/issues/2284
and here: https://github.com/Automattic/mongoose/blob/master/test/query.middleware.test.js
