### ISSUE TITLE
4.5 can't populate several virtuals at the same time

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4234]
populate virtuals is very good feature to have, thank you :)

and here is a first bug report
none of these signatures works

```js
populate("xxx yyy")
```
```js
populate("xxx").populate("yyy")
```
```js
populate({path: "xxx"}).populate({path: "yyy"})
```

`xxx` is always `null` after second call

**Comment by agnjunio** [comment]
Are you using `exec()` after?
I'm doing it like this and it works. (assuming xxx and yyy are referencing another model)
```javascript
Tournament.findById(id).populate("participants.team participants.player rounds.games").exec()
	.then(tournament => {  // tournament.participants.team._id exists
});
```
