### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by elena09** [Automattic/mongoose#4236]
I have this code, but I have a bug of "Maximum call stack size exceeded", 

'var Mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');
Mongoose.connect('mongodb://locahost/categorias');
var Schema = Mongoose.Schema;
var ObjectId = Schema.ObjectId;

var esquema = {
    id: ObjectId,
    nombre: {type: String, required: true, unique: true},
    descripcion: String,
    icono: String,
    fechaRegistro: {type: Date, default: new Date},
    activo: {type: Boolean, default: true},
    tipo: {type: ObjectId}
}
esquema.subcategorias = [esquema];

var categoriaSchema = new Schema(esquema);

categoriaSchema.plugin(uniqueValidator);
var CategoriaEsquema = Mongoose.model(categoriaSchema);
module.exports = CategoriaEsquema;'

**Comment by agnjunio** [comment]
Coloque ``` antes e depois do seu código para que os devs entendam.

ex:
```javascript
module.exports = CategoriaEsquema;
```

Wrote in portuguese because her code is also in portuguese, sry if breaks the rules.

**Comment by vkarpov15** [comment]
This looks like a bug with mongoose-unique-validator, seems like it doesn't handle recursive schemas well. In general, be careful with recursive schemas
