### ISSUE TITLE
Docs: update references of hooks.js

### ISSUE THREAD

**Issue by michaelkrone** [Automattic/mongoose#4238]
In the current documentation, the hooks.js framework is referenced (e.g. here: http://mongoosejs.com/docs/api.html#schema_Schema-post).

When inspecting a schema the s.hooks property shows a Kareem object. The dependencies are referencing hooks-fixed and kareem, but not hooks.

Questions:
Which lib is effectively used for settings up hooks?
Should the links in the docs be updated?

**Comment by vkarpov15** [comment]
We use both right now. Hooks is for backwards compat because kareem does things slightly differently. I don't really think the docs should be referencing hooks tbh, because end user shouldn't really care about that internal implementation detail
