### ISSUE TITLE
aggregate noTimeout option available ?

### ISSUE THREAD

**Issue by Ykid** [Automattic/mongoose#4241]
I am experiencing cursor timeout(error: cursor id didn't exist on server)when running mongoose aggregation on collections with 2 million records. according to https://jira.mongodb.org/browse/SERVER-6036 I can set noTimeout options to enable this, but I couldn't find it in mongoose documentation site. May I know if it is available ? Thanks

**Comment by vkarpov15** [comment]
As far as I can tell it isn't supported atm, will fix ASAP

**Comment by Ykid** [comment]
thank you!
