### ISSUE TITLE
Can't attach methods to subdocument after creation of document schema

### ISSUE THREAD

**Issue by kotarou3** [Automattic/mongoose#4242]
I'm currently using a converter that converts a different format into a mongoose schema, so I don't have direct access to the subdocument schema before it is used in other schemas. (It's used for something where it wouldn't make sense to attach document methods to it, so I don't want to modify it just to pass subdocument methods in)

So is there a way to attach methods to a subdocument after it's already used in other schemas (The model is not yet created, if that helps)? If not, I'm willing to pull request a "fix" if I could get some pointers to whereabouts I should be modifying.

See the code below to see what my current problem is:

```javascript
"use strict";

const mongoose = require("mongoose");
mongoose.Promise = Promise;
mongoose.connect("localhost/test");

const childSchema = new mongoose.Schema({
    name: String
});
const rootSchema = new mongoose.Schema({
    children: [childSchema]
});

rootSchema.path('children').schema.method({
    sayName: function () {
        console.log(this.name);
    }
});

const Root = mongoose.model("Root", rootSchema);

const root = new Root();
root.children.push({name: "a"});
root.children[0].sayName(); // TypeError: root.children[0].sayName is not a function

/* Also throws the same error:

const root = new Root();
root.children.push({name: "a"});
root.save().then(function () {
    return Root.findOne().exec();
}).then(function (root2) {
    root2.children[0].sayName();
}).catch(e => console.error(e.stack));

*/
```

(Using mongoose v4.5.0)

**Comment by vkarpov15** [comment]
Unfortunately this is really not supported, you need to fully define your schema before embedding it in another schema.

**Comment by kotarou3** [comment]
For posterity, I ended up working around this by "re-adding" the subdocument to the schema by:
```js
rootSchema.add({children: [rootSchema.path('children').schema]});
```
after defining the methods
