### ISSUE TITLE
Add a pool size to QueryCursor#eachAsync

### ISSUE THREAD

**Issue by YouriT** [Automattic/mongoose#4244]
I wrote a little wrapper that pretty much acts like `QueryCursor#eachAsync(fn, [callback])` but with a small difference which basically allows it to have a pool of items available, enabling to exec faster and to make stuff in parallel.
### Use case:

Each `fn` given to `eachAsync` is a promise that makes some IO and takes 5s to run. `eachAsync` would wait it to be finished before executing a new one but it doesn't mean you cannot execute multiple at once and to always have a pool of X `fn` executing at the same time, which would enable a higher throughput.

Hence, if `eachAsync` could buffer the next Y items to not have to wait for a new IO between mongo and the Node app it would enable a higher throughput too.
### API suggestion:

`QueryCursor#eachAsync(fn, [options], [callback])`
where `options` is something like:

``` js
{
    poolSize: >=1, // How many [fn] will be executed in parallel
    bufferSize: >=0 // How many items shall be retrieved in advance
}
```

If it has any interest I could think about making a PR for it.

Thanks for the good job guys!

**Comment by vkarpov15** [comment]
Thanks! PR would be great, but one big problem: please don't name it "poolSize", that term is [already used to mean the number of sockets the mongodb driver opens up](http://mongodb.github.io/node-mongodb-native/2.1/api/Server.html) and overriding the term will lead to a lot of headache.

**Comment by YouriT** [comment]
What about:
```js
{
    simultaneous: >=1, // How many [fn] will be executed in parallel
    bufferSize: >=0 // How many items shall be retrieved in advance
}
```

You like both enhancements?

**Comment by vkarpov15** [comment]
Sounds good to me, looking forward to seeing the pr 👍

**Comment by devourment77** [comment]
parallel would also be a good name, looking forward to this feature, currently trying to jury rig async queue to get parallel functionality with eachAsync.

**Comment by YouriT** [comment]
I'm lacking of time those days/weeks to get myself into it unfortunately. Hope to get some soon. Will come back on it. About the name, `parallel` seems nice to me :)

**Comment by vkarpov15** [comment]
Sure. In the meantime id recommend you just use co to implement this in your app, it should be a while loop with maybe 10 lines of code
