### ISSUE TITLE
Mongoose Boolean validation not working if a String is provided

### ISSUE THREAD

**Issue by andresgariglio** [Automattic/mongoose#4245]
Given the following schema with a Boolean field:

```
var UserSchema = new Schema({
  _id: {
    type: Number
  },
  enabled: {
    type: Boolean,
    default: false
  }
});
```

When trying to save a document, if I supply a random string instead of a Boolean value or "Boolean string" (e.g. "false" or "true" instead of just false/true) for enabled field, the document is still being saved properly, with the Boolean field set to true. 

Expected behavior: save operation should throw a ValidationError.

**Comment by vkarpov15** [comment]
Yeah unfortunately this is backwards breaking, mongoose will cast anything into a boolean and this is expected behavior. Will make this change for the next major release.
