### ISSUE TITLE
Nested methods aren't working on populated functions

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#4247]
Inside of a `pre` save hook, if I call `document.populate('something')`, the `document.something` database reference is populated, however methods such as `save` for example do not work, e.g. `document.something.save()` after modifying it such as `document.something.foo = 'bar';`.

**Comment by niftylettuce** [comment]
v4.5.x

**Comment by vkarpov15** [comment]
Is this a regression in 4.5?

**Comment by niftylettuce** [comment]
Yes I believe so.  There are a few other issues in 4.5.x, maybe you can investigate and file @vkarpov15, for example `.save` methods do not execute callback function if it is passed, nor do `.then` promises work.  v4.5.0 to be exact.

**Comment by vkarpov15** [comment]
Can you provide a more substantial code sample for the 2 issues you specified in your latest post?

**Comment by niftylettuce** [comment]
For the two issues mentioned, they are directly discussed here https://github.com/Automattic/mongoose/issues/4064.

**Comment by vkarpov15** [comment]
Looks like this is a dup of #4064. Re-open if I'm wrong.
