### ISSUE TITLE
lean() no longer works when moving from stream() to cursor()

### ISSUE THREAD

**Issue by pyramation** [Automattic/mongoose#4253]
As of the DeprecationWarning added [here](https://github.com/Automattic/mongoose/pull/4117/commits/94557653dba2cd9046f1b2ffab427cef4632a7c3), it seems to say that `cursor()` is a drop-in replacement for `stream()`, however, there is some functionality that seems to have been left behind.

For example, this deprecated code will have "lean" documents that are *not* instances of `mongoose.Document`:

```javascript
Cat
    .find({ }).lean()
    .stream()
    .on('data', function (data) {
        var value = data instanceof mongoose.Document;
        console.log('lean().stream() data instanceof mongoose.Document', value);
    })
    .on('end', function () { });
```

and this code will have mongoose Documents, even when `lean()` is used:

```javascript
Cat
    .find({ }).lean()
    .cursor()
    .on('data', function (data) {
        var value = data instanceof mongoose.Document;
        console.log('lean().cursor() data instanceof mongoose.Document', value);
    })
    .on('end', function () {});
```

Is there a proper way to achieve this with `cursor()` or did I find a bug? Thanks in advance ;)

**Comment by pyramation** [comment]
after research looks like `lean()` was not added into the `cursor()` flow, so I've added a test and code to make sure it is here: https://github.com/Automattic/mongoose/pull/4255

**Comment by vkarpov15** [comment]
Great job fixing this on your own, thanks for the help :beers:
