### ISSUE TITLE
How do I stop or close the cursor.

### ISSUE THREAD

**Issue by itnarayanan** [Automattic/mongoose#4258]
For an example 
fetching rows using cursor.next then I have stop or close the cursor while reach my limit. 
How do I stop or close the cursor ?

**Comment by vkarpov15** [comment]
No way to do so yet

**Comment by dewwwald** [comment]
I can't seem to figure out if this has now been made possible from the commits. I don't see a command to close the cursor.

**Comment by Marcvander** [comment]
@dewwwald @itnarayanan you can close the cursor by calling cursor.close():

`const cursor = User.find(filter).sort(sort).cursor();
  for (let user = await cursor.next(); user != null; user = await cursor.next()) {
      if (shouldBreakLoop) {
          cursor.close();
          break;
      }   
    }`
    
MongoDB doc: https://docs.mongodb.com/manual/reference/method/cursor.close/ that works for Mongoose
