### ISSUE TITLE
populated virtuals are always an array

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#4263]
virtual population is using `find` method to do its population stuff, so result is always an array
however relation can be one-to-one in many cases and this causes some redundant calculation
- `find` searches over all collection, while `findOne` stops on first result
- code have additional complexity in `x.y[0].value` this `[0]` is redundant
it would be nice to have ability to specify a relation type in any acceptable way
```js
XSchema.virtual("y", {
	ref: "Y",
	localField: "_id",
	foreignField: "x",
	singular: true // <-- here
});
```

**Comment by vkarpov15** [comment]
Yeah that's not something that we have support for yet, will add. Thanks for pointing this out :+1:

**Comment by TrejGun** [comment]
Thanks for making our issues `priorities`, we very appreciate

**Comment by vkarpov15** [comment]
Thanks for taking the time to look at this new feature and point out issues :+1:

**Comment by AleksMeshkov** [comment]
Hi! Do we have this feature described in the docs?

**Comment by vkarpov15** [comment]
@AleksMeshkov added a quick note about it in the populate docs :+1:
