### ISSUE TITLE
Sub schema references weird stuff happening

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4270]
I have the following (simplified) schema's:

```js
//Club model
let ClubSchema = new Schema({
  //...
  games: [GameSchema],
  //...
});

//Club games sub schema
let GameSchema = new Schema({
  id: String,
  modes: [{
    id: {
      type: String,
      ref: 'Mode'
    },
    //...
  }],
  //...
}, {
  _id: false
});

//Mode model
let ModeSchema = new Schema({
  _id: String,
  numMembers: Number
});
```

Note that I have a reference to the `Mode` model in the `Game` sub-schema of `Club`. However, I use string `_id`'s for the modes when populating them in the database, e.g.:

```js
[
  {
    _id: 'member',
    //..
  },
  {
    _id: 'visitor',
    //..
  },
  {
    _id: 'practice',
    //..
  }
];
```

And club games data looks like:

```js
games: [
      {
        id: 'some-game',
        modes: [
          {
            id: 'member',
            //...
          },
        ]
      }
]
```

So the idea is that in the club games, the modes will refer to the `Mode` models in the database via the `id` string property which is a simple string (not object ID).

First strange thing is that after I enter the data into the database with the above structure, the modes in the club games get an `_id` property added with some Object ID that I have no idea what it's referring to:

![image](https://cloud.githubusercontent.com/assets/490562/16360309/a788edd2-3baf-11e6-8dc4-58d128f6d229.png)

Modes are populated without these ID's:

![image](https://cloud.githubusercontent.com/assets/490562/16360307/917f2074-3baf-11e6-972a-f6335b229a34.png)

The second weird thing then happens when I execute this query:

```js
Club.findOne({subdomain})
    .populate('games.modes')
    .then(club => {
      //...
    });
```

I see the following in the logs:

```
Mongoose: clubs.find({ subdomain: 'upperhutt' }) { limit: 1, fields: undefined }  
Mongoose: clubs.find({ _id: { '$in': [ ObjectId("576f407b99ea90faf79cfadc"), ObjectId("576f407b99ea90faf79cfadb"), ObjectId("576f407b99ea90faf79cfada"), ObjectId("576f407b99ea90faf79cfad9"), ObjectId("576f407b99ea90faf79cfad8"), ObjectId("576f407b99ea90faf79cfad7") ] } }) { fields: undefined }
```

I have no idea why Mongoose would be executing the find on the `clubs`. It should be querying the modes, but it isn't according to the logs. However, in my response data, I see that population of modes did in fact occur correctly:

![image](https://cloud.githubusercontent.com/assets/490562/16360316/f182ad2e-3baf-11e6-9bd7-99ce839013b8.png)

But as you can see, the weird `_id` is included as well.

Question 1: why the `_id`'s which don't refer to anything?
Question 2: what's happening with the log output?

Please let me know if anything is unclear or if you need more information.

**Comment by adambuczynski** [comment]
PS: I have since refactored the code to get rid of the separate modes model altogether, but this was still a weird issue that I wanted to let you know about.

**Comment by vkarpov15** [comment]
Question 1: By default, every element in a mongoose document array gets an _id. To disable:

```javascript
  modes: [new Schema({
    id: {
      type: String,
      ref: 'Mode'
    },
    //...
  }, { _id: false })]
```

Question 2: When you say `Club.findOne({subdomain}).populate('games.modes')` you're telling mongoose to populate `games.modes` by the `_id` property in `games.modes`. Since that property doesn't have a ref, mongoose will use the current model by default.

In general, I'd recommend you structure GameSchema like this:

```javascript
let GameSchema = new Schema({
  id: String,
  modes: [{ type: String, ref: 'Mode' }],
  //...
}, {
  _id: false
});
```

This way, `populate('games.mode')` should work as expected

**Comment by adambuczynski** [comment]
@vkarpov15 

Q1: Right, so the _id is created because I didn't make a schema for the game mode in the club games array.

Q2: I see, thanks for clarifying. Now that I see what was happening with the `_id`s it makes more sense.
