### ISSUE TITLE
TypeError while using strict mode

### ISSUE THREAD

**Issue by kryogenic** [Automattic/mongoose#4272]
Hi, I get this stacktrace sometimes (not sure why):
`TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`
Full stacktrace: http://hastebin.com/fuxulemeze.rb

I found a similar issue here that has been fixed: https://github.com/Automattic/mongoose/issues/3046

The fix seems to be to apply this same logic from this commit:
https://github.com/Automattic/mongoose/commit/cdda75b998315f571523a9b947230044dfa11139
To the version.js file
https://github.com/Automattic/mongoose/blob/master/lib/error/version.js

**Comment by vkarpov15** [comment]
Looks like you're using a really old version of mongoose, the fix has already been out for over a year :)

**Comment by kryogenic** [comment]
As far as I can tell I'm using v4.4.3, and the version.js file I linked is from the master branch

**Comment by vkarpov15** [comment]
Woops looks like I didn't read properly, good catch

**Comment by theqabalist** [comment]
This is still an issue; node 8.2.1, mongoose 4.11.1.  lib/error/overwriteModel.js#16. Or in master
https://github.com/Automattic/mongoose/blob/master/lib/error/overwriteModel.js#L17

**Comment by vkarpov15** [comment]
@theqabalist opened a new issue :point_up: to track
