### ISSUE TITLE
required properties fail when being set on pre save

### ISSUE THREAD

**Issue by mitchellporter** [Automattic/mongoose#4273]
I have a pre save setup for all of my models that creates properties called `created_at` and `updated_at`. If you set these to required, you will get validation failures when trying to create a new object. It might be nice if you could require properties that won't actually be set until a pre save.

**Comment by TrejGun** [comment]
set it on pre validate)

**Comment by vkarpov15** [comment]
`validate()` currently runs _before_ any save hooks. You can set them in pre validate as @TrejGun suggested, you can also add default values.

**Comment by mitchellporter** [comment]
@TrejGun @vkarpov15 thanks!
