### ISSUE TITLE
Issue sorting a cursor 

### ISSUE THREAD

**Issue by pipaman** [Automattic/mongoose#4277]
I have a working code with version 4.4.1:
var cursor = EthTransaction.find(query).sort({ blockNumber: -1, transactionIndex: -1 }).cursor();

if I call this line on v4.4.1 works as specified, it returns the documents in the inverse order but if I do the same with latest version 4.5.2 it doesn't apply the sort command. In v4.4.1 cursor.options has the sort field but in 4.5.2 it's undefined.

**Comment by vkarpov15** [comment]
This is a dup of #4266, will be fixed once 4.5.3 is released. Sorry for the trouble :palm_tree:
