### ISSUE TITLE
Mongoose does not see disconnection with mLab after the loss of Internet connection

### ISSUE THREAD

**Issue by rn4hgs** [Automattic/mongoose#4289]
When my ISP interrupts the connection, the 'disconnection' event doesn't work with the mLab service. This code works fine with local or remote (non-mLab) databases.

var conn = mongoose.connection;
conn.on('error', console.error.bind(console, 'connection error:'));
conn.on('disconnected', function () {
    console.log(console, 'disconnected from database server');
    mongoose.connect(config.mongoUrl);
});
conn.on('open', function () {
    console.log('Connected to database server');
});

I use Node 6.2.2, Mongoose 4.5.1 and Mongo 3.0.12 on mLab side.

**Comment by vkarpov15** [comment]
You'll want to listen for the close event too:

```javascript
conn.on('close', function() {
  console.log('connection closed');
});
```

That event will fire after the socket times out if you lose internet
