### ISSUE TITLE
Browser require with system.js (CommonJS)?

### ISSUE THREAD

**Issue by mkastner** [Automattic/mongoose#4296]
Can browser.js only be used with browserify?

I'd like to get it running with system.js but that attempt fails.

Currently mainly because system.js requires extensions to be explicitly set:

```
Error loading http://host.name/:3001/js/lib/mongoose/lib/virtualtype as "./virtualtype"
```

If I set

```
SystemJS.defaultJSExtensions = true
```

Then the error occurs here:

```
Error loading http://host.name:3001/js/lib/mongoose/lib/types.js as "./types" from http://local.fmh.de:3001
```

So, is it possible at all to get browser.js running with system.js?

**Comment by vkarpov15** [comment]
TBH I've never tried, too many special snowflake build systems these days and too little time :) will give it a shot once we catch up on other issues

**Comment by vkarpov15** [comment]
Yeah gonna have to push this back for later when there's more demand, getting mongoose to work with systemjs will be a pretty significant undertaking because we'd have to change literally every single `require()` call in the entire codebase.

**Comment by hasezoey** [comment]
i this still planned to be done, or will it closed in favor of the official ECMAScript Modules (which are part of the js spec now)?

**Comment by vkarpov15** [comment]
Yeah we can close this. I don't think there's enough interest in SystemJS to justify the work.
