### ISSUE TITLE
object projection returns error

### ISSUE THREAD

**Issue by gogliko** [Automattic/mongoose#4299]
Hello, when I try to return object from projection, it gets errored or returns wrong value (which I don't want to get).

For example my query object is
```
 object = {
  name: {
            "1" : 1 ,
            "2": 2
   };
};
```

I want to return from this object 

```
 object = {
  name: 1
};
```

What I've tried so far is - 
```
model.find(query,{'name.1': 1},function ...
```

**Comment by vkarpov15** [comment]
What's the result you get? And what error?
