### ISSUE TITLE
eachAsync not a function for aggregation cursor

### ISSUE THREAD

**Issue by mbellezi** [Automattic/mongoose#4300]
I have an aggregation like this:

```
var cursor = self.model('BwLog').aggregate([ ... ]).cursor({ batchSize: 50 }).exec();
cursor.eachAsync(function(doc) {
    do something...
})
```

I'm using Mongoose 4.5.3 and I'm getting an error: 

`cursor.eachAsync is not a function
`

The cursor from the aggregations is different from the query cursors? Do you plan to support this async method?

Regards,

**Comment by vkarpov15** [comment]
Yeah right now aggregation cursors are completely separate. This would be a great feature to have though, thanks for the suggestion

**Comment by azarus** [comment]
So is this available in any versions yet?
