### ISSUE TITLE
ModelScheme skip Number type field 

### ISSUE THREAD

**Issue by timeswind** [Automattic/mongoose#4301]
I have many modelscheme file contains settings like this
`var mySchema = mongoose.Schema({
    Name: String,
    statistic: {
        a: Number,
        b: Number,
        c: Number
    }
});`
After created a document specify the Name field
it looks like this 
`{_id: xxxxxx, Name: '123'}`,
the remaining fields are missing

**Comment by timeswind** [comment]
I solve the issue by assign the field a default value
`{ type: Number, default: 0 }`

**Comment by vkarpov15** [comment]
Expected behavior, mongoose won't set defaults unless you ask it to
