### ISSUE TITLE
setting mongoose.Promise show warning messages about unhandled promises

### ISSUE THREAD

**Issue by rahpuser** [Automattic/mongoose#4303]
Hello, I have the following middleware

```javascript
exports.middleName = function(data, next) {
  return Model.aggregate([
    {
      $match: {
        'reference._id': mongoose.Types.ObjectId(data.elementId),
        'reference.Id': mongoose.Types.ObjectId(data.id)
      }
    }, {
      $group: {
        _id: mongoose.Types.ObjectId(data.elementId),
        average: {
          $avg: '$sentiment.score'
        }
      }
    }
  ]).exec(); // line 138 of my code
};
```

So, as I was getting the deprecated message, I decided to plug in bluebird.. like this:

```javascript
mongoose.Promise = require('bluebird');
var db = mongoose.connect(config.db);
```

But exactly after this, running the code results in:

_Warning: a promise was created in a handler but was not returned from it
        at Aggregate.exec (privatePath/node_modules/mongoose/lib/aggregate.js:526:10)
        at Object.exports.middleName (privatePath/app/sockets/middleware/middleware.socket.js:138:6)_

Is this an error in my code? or is in mongoose ?

Thanks

**Comment by vkarpov15** [comment]
Hmm which version of mongoose are you using? Also, are you using mongoose aggregation cursors or are you just getting an array as the result of the aggregation?

**Comment by rahpuser** [comment]
Mongoose: 4.5.3
Node: 4.4.4

Im getting an array as the result of the aggregation.

Thanks,

**Comment by rahpuser** [comment]
Hi @vkarpov15 thanks for your attention over this, I did try with other scenarios in order to confirm the problem, this is not a issue with mongoose. Thanks for your help, sorry the troubles.
