### ISSUE TITLE
Combination of index and unique on schema creates index in error

### ISSUE THREAD

**Issue by CoreMetabolicsAdmin** [Automattic/mongoose#4304]
An index is created in error when unique and index are present together on a property definition. 

```
class TestModel extends Model {
    constructor() {
        super();
        this._schema = new mongoose.Schema({
                _id: {type: String, unique: true, index: true, required: true},
                prop1Indexed: {type: String, unique: true, index: true, required: true},
                prop2NotIndexed: {type: String, required: false, unique: false, index: false},
                prop3NotIndexed: {type: String, required: false, index: false}
            },
            {timestamps: true});

        mongoose.set('debug', true);
        this._model = mongoose.model('Test', this._schema);
    }
}
```

See log. Index is created on prop2NotIndexed

info: Started Winston logger
info: Fetched app configs for platform: default
info: Mongo disconnected null
info: App initialized
Mongoose: tests.ensureIndex({ _id: 1 }) { unique: true, background: true }  
info: Booted Mongo at DSN: mongodb://localhost/arpeggio-auth-test with config: {"autoIndex":false}
Mongoose: tests.drop()   
Mongoose: tests.ensureIndex({ _id: 1 }) { unique: true, background: true }  
info: Dropped collections: tests
Mongoose: tests.ensureIndex({ prop1Indexed: 1 }) { unique: true, background: true }  
Mongoose: tests.ensureIndex({ prop1Indexed: 1 }) { unique: true, background: true }  
Mongoose: tests.ensureIndex({ prop2NotIndexed: 1 }) { unique: false, background: true }  
Mongoose: tests.ensureIndex({ prop2NotIndexed: 1 }) { unique: false, background: true }  
Mongoose: tests.insert({ updatedAt: new Date("Wed, 06 Jul 2016 18:18:00 GMT"), createdAt: new Date("Wed, 06 Jul 2016 18:18:00 GMT"), prop1Indexed: 'prop1Val', _id: '20bf5f83-77dc-4d0d-bbf6-174636b693b1', __v: 0 })   
Mongoose: tests.findOne({ _id: '20bf5f83-77dc-4d0d-bbf6-174636b693b1' }) { fields: undefined }  
Mongoose: tests.insert({ updatedAt: new Date("Wed, 06 Jul 2016 18:18:00 GMT"), createdAt: new Date("Wed, 06 Jul 2016 18:18:00 GMT"), prop1Indexed: 'prop1Val', _id: '6a66f90f-bcdd-4c03-b179-2887f0bb2e98', __v: 0 })   
info: ApiError ... /n/tname: Database error/n/tcode: 101/n/tmessage: A database operation failed. See extended message.

**Comment by vkarpov15** [comment]
`unique` creates a [unique index](https://docs.mongodb.com/manual/core/index-unique/) in mongodb, so you don't need to do both `index` and `unique`. Also, you should **never** specify a unique index on `_id` in mongoose, because mongodb collections always have a special index on `_id` by default, this will always cause an error.

Related, I'd recommend you set the [`emitIndexErrors` option to true](http://mongoosejs.com/docs/guide.html#emitIndexErrors) on your schema. It's off by default for backwards compatibility but I'd strongly recommend keeping that option on.

**Comment by CoreMetabolicsAdmin** [comment]
The point is that for prop2NotIndexed property in the example, index and unique are set to false. I would not expect this to create an index in any circumstance.

**Comment by vkarpov15** [comment]
Ah ok that makes sense
