### ISSUE TITLE
Pre update hook, before doc casting

### ISSUE THREAD

**Issue by ramiel** [Automattic/mongoose#4306]
```js
this.Person.update({'n': 'John'}, {surname: 'Stark'}, () =>{});
```
During an update the second parameter is `casted` which means basically all the properties which are not defined in the schema are dropped. Then the `pre update` hook is called. Is there any hook which runs before this casting?

**Comment by vkarpov15** [comment]
No, there's no such hook. I'd imagine the easiest way to do this would be to overwrite Person query's update function (or `_castUpdate()`, which is the function that actually casts update operations):

```javascript
var originalQuery = Person.Query.prototype.update;

Person.Query.prototype.update = function(query, update, cb) {
  /* Handle update */
  return originalQuery.apply(this, arguments);
};
```

**Comment by ramiel** [comment]
Ok, thank you.
Overwrite the method is not a suitable option for me, I'll look for something else.

**Comment by Nepoxx** [comment]
Are there any technical (or non-technical) constraints against having such a hook?

**Comment by vkarpov15** [comment]
Just how the API is structured right now is not really conducive to modifying before casting. Casting the update happens before hooks are executed because we always assume that the current state of the Query is already casted.
