### ISSUE TITLE
How to get keys against a Collection

### ISSUE THREAD

**Issue by UmerIftikhar** [Automattic/mongoose#4307]
I retrieved all the collection names from the MongoDB, and I used the following code:

```javascript
mongoose.connection.on('open', function () {

    mongoose.connection.db.collectionNames(function (err, names) {

        for(var i=0;i<names.length;i++){

            console.log(names[i].name);

            var currentCollection = mongoose.connection.db.collection(names[i].name);

            console.log(currentCollection);
        }
   });
 });
```

Now on the client side I will display these collection names in drop down menu, and when the user will select a specific Collection I want to display all the keys(in json format) against that collection.

How can I implement this? In short I want to retrieve the whole schema only by using the MongoDB.

Example:

User selects the collection named **Comments**
And I want to display the corresponding schema for that as follow.
_{
    title     : String
  , body      : String
  , date      : Date
}_

**Comment by vkarpov15** [comment]
`mongoose.connection.models` is a map from model name to model. To get the mongoose schema for a collection name:

```javascript
function getSchemaForCollectionName(collectionName) {
  for (var model in mongoose.connection.models) {
    if (model.collection.collectionName === collectionName) {
      return model.schema;
    }
  }
}
```

**Comment by UmerIftikhar** [comment]
Unfortunately it gives me nothing.
When i print `mongoose.connection.models` on console it gives an empty JSON.
console.log(mongoose.connection.models)
output: {}

**Comment by vkarpov15** [comment]
How are you declaring your models?

**Comment by UmerIftikhar** [comment]
`var mongoose = require('mongoose');
var requestTrackingSchema = new mongoose.Schema({
localrecord			:{
		  email: { type: String }
		, sampledata1: String
		, sampledata2: String
		, commands: String
}

});

module.exports = mongoose.model('Record', requestTrackingSchema);`

**Comment by UmerIftikhar** [comment]
// app/models/user.js
// load the things we need
var mongoose = require('mongoose');
var bcrypt   = require('bcrypt-nodejs');

// define the schema for our user model
var userSchema = mongoose.Schema({

    local            : {
        email        : String,
        password     : String,
    },
    facebook         : {
        id           : String,
        token        : String,
        email        : String,
        name         : String
    },
    twitter          : {
        id           : String,
        token        : String,
        displayName  : String,
        username     : String
    },
    google           : {
        id           : String,
        token        : String,
        email        : String,
        name         : String
    }

});

// methods ======================
// generating a hash
userSchema.methods.generateHash = function(password) {
    return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null);
};

// checking if password is valid
userSchema.methods.validPassword = function(password) {
    return bcrypt.compareSync(password, this.local.password);
};

// create the model for users and expose it to our app
module.exports = mongoose.model('User', userSchema);

**Comment by vkarpov15** [comment]
That's strange. Are you printing out `mongoose.connection.models` before calling `require()` on that file? Also, try printing `Object.keys(mongoose.connection.models)`. Which version of mongoose are you using?

**Comment by UmerIftikhar** [comment]
Actually what I am doing is that I have created two servers, In one I am creating those schemas (as mentioned in the code above), Now in the other server I am connecting to the same MongooDB and from this server i want to display all the schemas. (Therefore, my objective is just to provide configuration of the respective mongooDB and retrieve its schemas from any where).

**Comment by vkarpov15** [comment]
MongoDB doesn't have any notion of schemas, those schemas only exist on your node.js server. If you want to display all the schemas you'll have to `require()` them in
