### ISSUE TITLE
Cannot change type

### ISSUE THREAD

**Issue by leopoldfreeman** [Automattic/mongoose#4310]
If the object is a normal javascript object:
```JavaScript
var foo = {
    a: 'abc'
};
foo.a = 5;
console.log(typeof foo.a);  // Print number.
```

But the doc from callback of Mongoose API has the very strange behavior:
```JavaScript
var barSchema = {
    name: {
         type: String,
         required: true
    }
}

var BarModel = db.model('BarModel', barSchema);

BarModel.findOne({name: 'xxx'}, function (err, doc) {
     var copy = JSON.parse(doc.toJSON()); // toObject()/Object.assign() are the same.
     copy.name = 5;
     console.log(typeof copy.name) // STILL print string
});
```

I copied from the doc, why I cannot change the type? And how can I change the type?

**Comment by leopoldfreeman** [comment]
I find ['lean()'](http://mongoosejs.com/docs/api.html#query_Query-lean) that can fix this problem.

**Comment by vkarpov15** [comment]
One problem might be that `toJSON()` returns an object, not a string, so you shouldn't be doing `JSON.parse()` there. But glad you found the problem.
