### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by thatisuday** [Automattic/mongoose#4313]
In v4.5.3 documenation on page http://mongoosejs.com/docs/guide.html,
under the title **Query Helpers**

```
animalSchema.query.byName = function(name) {
  return this.find({ name: new RegExp(name, 'i') });
};

var Animal = mongoose.model('Animal', animalSchema);
Animal.find().byName('fido').exec(function(err, animals) {
  console.log(animals);
});
```

`Animal.find().byName('fido')` is wrong. It should be `Animal.byName('fido')` because **byName** function already returning query builder object from find inside it. If this is how it supposed to be, then it's not working out for me.

**Comment by vkarpov15** [comment]
Hmm it looks correct, `Animal.byName('fido');` shouldn't work because `byName` is only defined on the Query object, not the Model itself, in the above example Can you show me the code that's not working for you?
