### ISSUE TITLE
mongoose 4.5.4 keeps on reconnecting ...

### ISSUE THREAD

**Issue by oliverhuang** [Automattic/mongoose#4323]
I use mongoose 4.5.4 to connect to a mongodb cluster (version 3.0.3). It keeps on reporting reconnect event. When I downgrade to mongoose 4.5.3, everything goes well.

Is there anything wrong ?

**Comment by mattdawson** [comment]
+1 This took out my server overnight.  Every database access seems reconnect.

**Comment by shauntrennery** [comment]
I've seen a dramatic increase in median response times since upgrading to 4.5.4. I suspect it could be related to this reconnect issue. Response times back down to expected levels when redeploying 4.5.3.

**Comment by vkarpov15** [comment]
I think this is a dup of #4334, we upgraded the driver in 4.5.4 to fix #4202 and looks like driver 2.2.21 has some issues. Sorry about that. Will release 4.5.5 to fix this over the weekend.
