### ISSUE TITLE
How to find by array of objects?

### ISSUE THREAD

**Issue by semanser** [Automattic/mongoose#4325]
I have Mongoose.Schema like this:

```
const pixelSchema = mongoose.Schema({
  x: String,
  y: String,
  color: String,
});
```

Also I have array of objects like this:
```
let pixels = [
  {x: 0, 1: 0, color: 'blue'},
  {x: 0, y: 1, color: 'blue'},
  {x: 0, y: 2, color: 'blue'},
]
```

**How can I check is one of this elements is already exist in database?** My solution now looks like this, but I think it's very inefficient.

```
pixels.map(pixel => {
  Pixel.find(pixel, (err, pixels) => {
    if (pixels) {
      console.log('Find!');
    }
  });
});
```

**Comment by semanser** [comment]
Solution find: just use `$or`

```
let pixels = [
  {x: 0, y: 0, color: 'blue'},
  {x: 0, y: 1, color: 'blue'},
  {x: 0, y: 2, color: 'blue'},
];

let query = { "$or": pixels };

Pixel.find(query, (err, pixels) => {
    if (pixels) {
        console.log('Find!');
    }
});
```

**Comment by vkarpov15** [comment]
`$or` is the way to go in this case, good catch.

You can use `$in` too, but that will only match docs that match the query exactly, that is, docs where `pixels` is either a doc with 3 keys 'x', 'y', and 'color' that match the given doc, or `pixels` is an array which contains a doc that matches exactly.
