### ISSUE TITLE
Not authorized to execute command after upgrade to 4.5.4

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#4328]
I've seen that there are other reports of issues about 4.5.4 but since this same error isn't reported in any issue I've decided to open another one, feel free to close it if it's not relevant.

Since upgrading to 4.5.4 we've started to see a lot of errors about not being authorized to execute commands on our replica set:

> error: MongoError: not authorized on ***** to execute command

For all types of queries: reads, updates, ... We're now in the process of reverting to the previous mongoose version and will be able to confirm if it's still happening in a few hours.

I couldn't find any similar error in our server logs before the new mongoose version was deployed

Thanks for your help!

**Comment by Jeff-Lewis** [comment]
Just got the same thing on our CI server...

**Comment by vkarpov15** [comment]
Yeah this is fixed with #4334. MongoDB's driver had some issues with their 2.1.21 release, which had a fix for the issue in #4202 but introduced several other issues. Sorry about that, will push 4.5.5 with a downgraded mongodb driver version.
