### ISSUE TITLE
Stochastic behavior when setting defaults on sub-schema

### ISSUE THREAD

**Issue by leobudima** [Automattic/mongoose#4330]
I was wondering if anyone has any insight into weird behavior that's been bugging me for a while now in production.

The problem is that, when I don't send any values for a subschema when creating a document, default values for the subschema are created stochastically.

My model:

```
const SubSchema = new Schema({
    subValue: {
        type: Boolean,
		default: false
	}
})'

const MainSchema = new Schema({
    flags: {
        type: SubSchema,
        default: {}
    },
    mainValue: {
       type: Number
    }
})
```

I create a document by sending:

```
{ mainValue: 1 }
```

Most of the time, `subValue` is set to `false`, and I get:

```
{
    mainValue: 1,
    flags: {
        subValue: false
    }
}
```
but probably 10% of the time, it is explicitly set to `true`:

```
{
    mainValue: 1,
    flags: {
        subValue: true
    }
}
```

A lot of stuff is happening asynchronously on the server at the same time, but on the other hand, I am absolutely certain that there is no place in my code that can set it to `true` - yet it happens.

Thanks for any feedback!

**Comment by vkarpov15** [comment]
Weird, thanks for reporting, I'll try to repo when I get a chance

**Comment by vkarpov15** [comment]
So yeah below script works fine for me:

```javascript
'use strict';

Error.stackTraceLimit = Infinity;

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4330');
mongoose.set('debug', true);

const co = require('co');

const SubSchema = new Schema({
    subValue: {
        type: Boolean,
        default: false
    }
});

const MainSchema = new Schema({
    flags: {
        type: SubSchema,
        default: {}
    },
    mainValue: {
       type: Number
    }
});

const MainSchema = new Schema({
    flags: {
        type: SubSchema,
        default: {}
    },
    mainValue: {
       type: Number
    }
});

const Main = mongoose.model('Test', MainSchema);

co(function*() {
  let doc;
  for (let i = 0; i < 100000; ++i) {
    doc = yield Main.create({ mainValue: 1 });
    assert.strictEqual(doc.flags.subValue, false);
  }
  console.log('done');
  process.exit(0);
}).catch(error => {
  console.error('error', error.message);
  process.exit(0);
});
```

Create a new doc 100k times, 0 instances of `subValue` true. Can you provide more details about what's going on around this call?

**Comment by leobudima** [comment]
Hi @vkarpov15 - thanks a lot for checking this, I appreciate it greatly. The environment around what happens with default values is rather complex, Hapi framework, async calls, pre/post hooks etc. I've tried to dig into it as much as possible, but was unable to find any obvious cause and later surrendered and resorted to sending a default for subvalue from the client. Knowing that it's not something exclusively due to mongoose helps, and I'll get back to trying to devise a simplest example which can reproduce it... 

Thanks again and I'll report if I find anything useful to you/others.
