### ISSUE TITLE
sub-document validation doesn't run with runValidators

### ISSUE THREAD

**Issue by valterkraemer** [Automattic/mongoose#4332]
//area.schema.js

    var Schema = require('mongoose').Schema;

    module.exports = new Schema({
      a: String
    });

    //company.schema.js

    var mongoose = require('mongoose');
    var Schema = mongoose.Schema;
    var AreaSchema = require('./area.schema');

    var CompanySchema = new Schema({
      area: {
        type: AreaSchema,
        validate: {
          validator: function(value) {
            return false;
          },
          message: 'Not valid Area'
        }
      }
    });

    module.exports = mongoose.model('Company', CompanySchema);

Create runs area's validator, update with `runValidators` doesn't.

    Company.update({
      _id: user.company._id
    }, {
      area: {
        a: 'Helo'
      }
    }, {
      runValidators: true
    });

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/4926e1b259d4d28e92f1845bc9130c1d2abdea9a
