### ISSUE TITLE
DocumentArray still uses defineProperties

### ISSUE THREAD

**Issue by Sebmaster** [Automattic/mongoose#4333]
3ebf10440fb74345dfe66beb7cfc2b0850ac42f9 fixed the performance regression for MongooseArrays, however [DocumentArrays still do the defineProperty call](https://github.com/Automattic/mongoose/blob/25810a378989b478c13d2356322aa98c36a31fd3/lib/types/documentarray.js#L53), which still causes a serious perf regression for us.

**Comment by vkarpov15** [comment]
Good catch, will fix for next release
