### ISSUE TITLE
Updating to mongoose 4.5.4 have issue with authentication

### ISSUE THREAD

**Issue by rupamkhaitan** [Automattic/mongoose#4335]
We have updated to mongoose 4.5.4 and we dint change any logic in the way we make connection to mlab

But we see it keep throwing error with Mongo query not authorized, when we switch back to mongoose 4.5.3 it works fine.

The only difference we see that mongodb driver is updated to 2.1.21 in latest mongoose

Is there something we are missing ?

**Comment by vkarpov15** [comment]
#4334.

**Comment by rupamkhaitan** [comment]
Thanks
