### ISSUE TITLE
some questions about sub-doc

### ISSUE THREAD

**Issue by aweiu** [Automattic/mongoose#4336]
## Q1:
```
parent.find(
  {
    _id: id
  },
  {
    children: {
      $elemMatch: {
        age: 18
      }
    }
  },
  (e, doc) => {
    //  why the doc.children.length ===1?i need all the children where age is 18 and i can set the array length i need,how to do?
  // could the doc just be the children doc ,not the parent doc?
  }
)
```
## Q2:
document:
```
{
  children: [
    {index: 'first'},
    {index: 'last'}
  ]
}
```
how to get the last one in children?i don't want the parent run find first,then do filter,just like that:
parent.children.findLast()
=>{index: 'last'} 
## Q3:
is it possible to do that:
```
parent.find({
   children.name: 'Jack'
},
// children fields
'children.name',
(e, doc) => {
  // the doc.children is [{name: 'Jack'},{name: 'Tom'}] 
}
)
```
## Q4:
how to page the sub-doc?some one suggest me to do that:
```
  parent.find(...(doc)=>{
    // do something for paging doc.children
  })
```
but i think the way is not good,if the children array is too big,it will consume more memery

**Comment by vkarpov15** [comment]
1) https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/#proj._S_elemMatch

2) Not sure I understand this question, can you clarify?

3) That should work

4) I don't understand this question, please clarify

**Comment by aweiu** [comment]
sorry,i try to clarify it by my bad English.thank you for your help!
## Q2:
suppose the parent document is 
```
{
  children: [
    {index: 'first'},
    {index: 'last'}
  ]
}
```
how to excute some query to get it?:
`{index:first}`
some one do it by this way:
```
parent.findOne({_id:id})
  .then((doc) => {
    return doc.children[doc.children.length-1]
  })
```
but,i think,if the size of sub-doc is too large,will this action consume more memery?
now,i do it by **aggregate()**,is there more sample way?

Q4:
how to get any number sub-doc?if i do this:
```
parent.findOne({_id:id})
  .then((doc) => {
    // the doc.chidren will be all of the sub-doc,not some number of it,and it may also consume more memery
   // just like 'limit','skip','gt',etc...
  })
```

**Comment by TrejGun** [comment]
2 and 4 you possibly need to use aggregation framework 
https://docs.mongodb.com/manual/reference/operator/aggregation/unwind/

5 `parent.findOne({_id:id}, {$push:{field:value}})`

**Comment by vkarpov15** [comment]
@TrejGun is right.

In general, you don't want to have really big arrays in subdocs because they can get pretty unwieldy and you [don't want to run into the 16MB document size limit](https://docs.mongodb.com/manual/reference/limits/)
