### ISSUE TITLE
discriminator and option typeKey combination

### ISSUE THREAD

**Issue by CallMeLaNN** [Automattic/mongoose#4339]
Create a model with discriminator and make use of the `typeKey` option e.g. `"$type"` because I want to store GeoJSON document. Then follow the first discriminator example in the mongoose documentation.

    var options = {typeKey: '$type', discriminatorKey: '_t'};

I receive this error in the `model.discriminator()` line:

> Undefined type "_discriminator name_" at "_typeKey_.default"  Did you try nesting Schemas? You can only nest using refs or arrays.

But obviously I'm not trying to nest any schema.

**Comment by vkarpov15** [comment]
Yeah I think this is a bug with mongoose and the interaction between the typeKey option and discriminators. Thanks for pointing it out :+1:
