### ISSUE TITLE
Deep populating doesn't return id's in document.populated

### ISSUE THREAD

**Issue by andrewsomahony** [Automattic/mongoose#4343]
Hello,

I'm doing a deep population of an embedded schema within a model.  I'm simply using populate("comments._creator"), but when I call "populated" on the document with "_creator" as a parameter, it returns undefined, instead of the id used to populate the value.  Is this known?

**Comment by vkarpov15** [comment]
I'm not sure I understand your issue, can you clarify with a code sample?
