### ISSUE TITLE
Populate Virtuals : not working 😞

### ISSUE THREAD

**Issue by thatisuday** [Automattic/mongoose#4348]
Hi, I am using mongoose 4.5.3.
As mentioned in the docs, `http://mongoosejs.com/docs/populate.html` in `Populate Virtuals`, I can't produce desired results as mentioned.

There isn't any `members`  field present inside return `bands` doc. Are you sure this worked with you?
Can you please add a travis-ci tests for this?

My code:
```
var mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1/test');
var db = mongoose.connection;

/**************************************/

var personSchema = new mongoose.Schema({
  name: String,
  band: String
});

var bandSchema = new mongoose.Schema({
  name: String
});


bandSchema.virtual('members', {
  ref: 'Person', // The model to use
  localField: 'name', // Find people where `localField`
  foreignField: 'band' // is equal to `foreignField`
});

var Person = mongoose.model('Person', personSchema);
var Band = mongoose.model('Band', bandSchema);

var person = new Person({
    name : 'Uday',
    band : 'gnr'
});
person.save(function(){
  var band = new Band({
      name : 'gnr'
  });

  band.save(function(){
    Band.find({}).populate('members').exec(function(error, bands) {
      console.log(bands);
    });
  });
});
```

**Comment by thatisuday** [comment]
Here is **runnable** code
[http://code.runnable.com/V48qGaK7YcYcxd58/output](http://code.runnable.com/V48qGaK7YcYcxd58/output)

**Comment by thatisuday** [comment]
[Runnable](http://code.runnable.com/V48p8ZpxiFQcqK8x/mongoose-populate-virtual-for-node-js-and-hello-world)

**Comment by thatisuday** [comment]
Sorry for the mess...

**Comment by vkarpov15** [comment]
@thatisuday is this still an issue?

**Comment by thatisuday** [comment]
@vkarpov15 Yes. Please take a look at https://github.com/Automattic/mongoose/issues/4354 issue where I have mentioned some extra operations I needed to do to get going.
