### ISSUE TITLE
 Can't use $elemMatch with String - how to list() using subdocuments field?

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#4350]
So I'm implementing a paginated table that list some records that have subdocuments and i need to add filtering capabilities so that I can filter the list() results using the subdocument field values.

```
let HardwareSchema = new mongoose.Schema({
	name: { type: String, required: true }, // the exact name of the hardware.
	slug: { type: String, unique: true }, // the hardware's slug.
	category: { type: String, ref: 'HardwareCategory', required: true },
}

let HardwareCategorySchema = new mongoose.Schema({
	name: { type: String, unique: true, required: true }, // the name of the category.
	slug: { type: String, unique: true }, // the slug of the category.
	description: { type: String, unique: true, required: true }, // the name of the category.
	createdBy: { type: String, ref: 'User', required: true } // the original submitter of the document.
});
```

So basically i want to to filter our Hardwares using category selected category.

Here is my the actual code;

```
	const options = {
		perPage: 10,
		page: (req.query.page > 0 ? req.query.page : 1) - 1,
		sortBy: {'rank': -1 },
		criteria: {
			status: 'approved',
			category: {
				 $elemMatch: { 'slug': category }
			}
		}
	};

Hardware.list(options)
.then(results => {});
```

I'm getting the error;  Can't use $elemMatch with String.

So basically i need to;

- be able to filter results based on subdocuments field value.
- be able to paginate results
- be able to sort results.

How can I manage this?

**Comment by vkarpov15** [comment]
You're going to have to use the [`$lookup` operator and the aggregation framework](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/), mongoose won't let you filter hardware by hardware category doc properties.
