### ISSUE TITLE
Make debug output copy-pastable into MongoDB console

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4352]
With mongoose debug option enabled, I get output like the following for my queries:

```
Mongoose: productsortorders.update({ sortOrder: { '$gte': 1, '$lte': 1 }, categoryId: ObjectId("111bee3e4527879d33c7b31b") }) { '$inc': { sortOrder: 1 } } { multi: true } 
Mongoose: productsortorders.update({ productId: ObjectId("222bee3e4527879d33c7b31b") }) { '$set': { sortOrder: 1 } } {} 
```

Can we move the location of the closing bracket `)` such that it encompasses the fields as well as any options, and also add a comma between the fields and options objects?

This way we can copy paste this debug information straight in our MongoDB consoles to execute the same command, e.g.:

```
Mongoose: productsortorders.update({ sortOrder: { '$gte': 1, '$lte': 1 }, categoryId: ObjectId("111bee3e4527879d33c7b31b") }, { '$inc': { sortOrder: 1 } }, { multi: true })
Mongoose: productsortorders.update({ productId: ObjectId("222bee3e4527879d33c7b31b") }, { '$set': { sortOrder: 1 } }, {})
```

Seems like a fairly minor change. I can look into making a PR if you are interested.

**Comment by vkarpov15** [comment]
Yes please, that would be a wonderful feature. If you can put in a PR that would be awesome :+1:

**Comment by adambuczynski** [comment]
Alright I'll have a look into it.

Another observation I made is that an array of items doesn't get string quotes in the log output in some cases. Will try to fix this as well while I'm at it.

Example:

```
courts: [ 444bee3e4527879d33c7b31c ], organisers: [ '333bee3e4527879d33c7b31a' ],
```

For courts, the quotes are missing.

**Comment by adambuczynski** [comment]
Great stuff! I've had a quick look, but couldn't really work out how it was being logged.
Was planning to tackle it later, but guess you beat me to it :)
