### ISSUE TITLE
Populate Virtuals : not working 😞

### ISSUE THREAD

**Issue by thatisuday** [Automattic/mongoose#4354]
Hi, I am using mongoose 4.5.3.
As mentioned in the docs, `http://mongoosejs.com/docs/populate.html` in `Populate Virtuals`, I can't produce desired results as mentioned.

There isn't any `members`  field present inside return `bands` doc. Are you sure this worked with you?
Can you please add a travis-ci tests for this?

My code:
```
var mongoose = require('mongoose');
mongoose.connect('mongodb://127.0.0.1/test');
var db = mongoose.connection;

/**************************************/

var personSchema = new mongoose.Schema({
  name: String,
  band: String
});

var bandSchema = new mongoose.Schema({
  name: String
});


bandSchema.virtual('members', {
  ref: 'Person', // The model to use
  localField: 'name', // Find people where `localField`
  foreignField: 'band' // is equal to `foreignField`
});

var Person = mongoose.model('Person', personSchema);
var Band = mongoose.model('Band', bandSchema);

var person = new Person({
    name : 'Uday',
    band : 'gnr'
});
person.save(function(){
  var band = new Band({
      name : 'gnr'
  });

  band.save(function(){
    Band.find({}).populate('members').exec(function(error, bands) {
      console.log(bands);
    });
  });
});
```

[Runnable](http://code.runnable.com/V48p8ZpxiFQcqK8x/mongoose-populate-virtual-for-node-js-and-hello-world)

**Comment by thatisuday** [comment]
Seems like population is working fine. You can access `members` using `band.members` but it won't show up in the `band`. It's like a hidden field or something. What can we do here?

**Comment by thatisuday** [comment]
Ok. Got it. You must need to set `toObject : {virtuals:true},` option in your schema. I guess, you should mention that in the doc. That would be helpful.

**Comment by thatisuday** [comment]
Everything is working fine now except when I am sending data over HTTP, virtuals are not excluded in the data.


This is the final document with `owner` is the populated field.

![image](https://cloud.githubusercontent.com/assets/5711821/17012421/2a17d4d2-4f35-11e6-9f96-8127259991ce.png)

![image](https://cloud.githubusercontent.com/assets/5711821/17012389/ecdc742e-4f34-11e6-92eb-0eb5e400c346.png)

This is the same document with no `owner` field sent to the user.
![image](https://cloud.githubusercontent.com/assets/5711821/17012415/1618b7f8-4f35-11e6-99b4-191f8841dd3c.png)

**Comment by thatisuday** [comment]
Got it, you also need to add option `toJSON : {virtuals : true}`.

**Comment by thatisuday** [comment]
Also, is there any option to populate suing singular reference instead of array. `singular' key is not working as per mentioned in [mongoose-populate-virtuals](https://github.com/alexmingoia/mongoose-populate-virtuals).

**Comment by vkarpov15** [comment]
@thatisuday use the `justOne` property:

```javascript
projectSchema.virtual('owner', {
  ref: 'People',
  localField: '_id',
  foreignField: 'owns',
  justOne: true // Only return one owner
});
``

**Comment by thatisuday** [comment]
@vkarpov15 wow, thanks.
