### ISSUE TITLE
Sharing connection pool with multiple instances.

### ISSUE THREAD

**Issue by ericrini** [Automattic/mongoose#4357]
Let's say I had a web server, and I wanted to log every Mongoose query in a way that could be tied back to the request that initiated it.

I might try doing something like this.

```
var Mongoose = require('mongoose').Mongoose;

var request1 = new Mongoose();
request1.connect('foo');
request1.set('debug', function () { console.log('request 1 made a query') });

var request2 = new Mongoose();
request2.connect('foo');
request2.set('debug', function () { console.log('request 2 made a query') });
```

So each request can have it's own Mongoose instance. Cool? Not quite.

Each instance is creating it's own connection pool which is going to end up leaking all over when requests end. Even if this could be solved by disconnecting each instance at the end of each request, it's still not particularly efficient to make even a single connection per request.

So I might try to fix it by doing something like this.

```
mongoose.connect('foobar');  // Connect the "default" instance.
request1.connection = mongoose.connection; // Share the "default" instance pool with request 1.
request2.connection = mongoose.connection; // Share the "default" instance pool with request 2.
```

Superficially, this appears to work, but then I try to do something like this...

```
var Model = request1.Model('Yaddah', Schema);
Model.findAll();  
```

What I find is that instead of logging through the log handler on the Mongoose instance that created the Model (request1), instead it goes through the log handler on the Mongoose instance that created the connection (default mongoose).

So. I'm feeling a little lost, and starting to wonder if this is possible. Anyone have any ideas?

**Comment by vkarpov15** [comment]
Creating a separate connection pool for every request is a really bad idea for performance and general sanity, would strongly advise you don't do that.

I'll check this out, but I'm curious, why do you need a new mongoose instance for every request? That seems like overkill
