### ISSUE TITLE
Document updating but not saving

### ISSUE THREAD

**Issue by shekit** [Automattic/mongoose#4358]
Hi, 

I've been pulling my hair out trying to figure this. My document shows that it is updating but it does not save to the database. 

**My Schema**
`
    var moduleSchema = new Schema({
	title: {
		type: String,
		unique: true
	},
	description: String,
	tier: [{
		type: Schema.Types.ObjectId,
		ref: 'Tier'
	}],
    })
`

**My Custom Method**

`    
       moduleSchema.methods.saveInTier = function(tierTitles, cb){

	// expects an array of tier names

	var self = this;

	var updateTier = function(i){ 
		Tier.findOneAndUpdate({title: tierTitles[i]},
		{$addToSet: {modules: self._id}},
		function(err, tier){
			if(err) throw err;

			//self.tier.set(i, tier._id)
			self.tier.addToSet(tier._id)

			console.log("module saved in tier: ", tier.title)
			
			// self.markModified('tier')
			// self.save()
				console.log("i am EXITING")
				console.log("assigning to SELF")

			return self.tier
			
		})
	}

	

	for(var j=0;j<tierTitles.length;j++){
		updateTier(j)
	}
    }
`

**Creating the Document**
`
        var module = new Module({
	    title: "Chat"
        })

    module.saveInTier(['default','gold'])

    module.save(function(err){
	if(err){
	if(err.code == '11000'){
		console.log("module already exists")
		} else {
		throw err
		}
	}
	console.log("Correctly logs out new updated document here")
    })
`

**Accessing the DB**
`
    Module.find({}, function(err, docs){
	console.log(docs)
	// does not show any the doc updated in the database
    })
`

Also sorry about the markdown, not sure whats up with it

**Comment by vkarpov15** [comment]
Are you calling `.find()` in the save callback? Looks like you're struggling to grok the async nature of javascript:

```javascript
var module = new Module({
title: "Chat"
})

module.saveInTier(['default','gold'])

module.save(function(err){
if(err){
if(err.code == '11000'){
    console.log("module already exists")
    } else {
    throw err
    }
}
console.log("Correctly logs out new updated document here")
Module.find({}, function(error, docs) { /* _will_ show the saved doc */ });
})

Module.find({}, function(error, docs) { /* won't show the saved doc */ });
```
