### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by livertonli12** [Automattic/mongoose#4361]
Hi, 

I tried looking for all issues related to auth failed and also tried all suggestions but unfortunatley i couldn't connect to my database.

I have one database named "integrador".

I registered an administrator with the following:

```
db.createUser({ user: "linkapiAdmin", pwd: "password", roles : [ { role: "clusterAdmin", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readAnyDatabase", db: "admin" }, { role: "userAdminAnyDatabase", db : "admin" }, { role: "dbAdminAnyDatabase", db : "admin" } ] });
```

Then tried to connect with the following URI's 

```javascript
var connectionString = 'mongodb://linkapiAdmin:mypassword@myiphost:33003/integrador';
var connectionString = 'mongodb://linkapiAdmin:mypassword@myiphost:33003/integrador?authSource=admin';
```

and always receive the following error:

![image](https://cloud.githubusercontent.com/assets/1885894/17076126/765a48b0-5080-11e6-9797-b06bf350791f.png)

What I am doing wrong ? =/

I am using mongoose 4.5.1

**Comment by emaxedon** [comment]
I'm getting the same issue with Mongoose v4.9.2. Probably related to `authSource` not working properly.

Were you able to solve this?

**Comment by varunjayaraman** [comment]
Does this not fail for you in your `mongodb shell`: `db.auth('linkapiAdmin', 'password')` because it does for me

**Comment by vkarpov15** [comment]
Keep in mind that the database the user is associated with is very important. Users are scoped to a database, and then you can give them permissions on other databases. Because you're not sure which database the user is on and you're trying two different ones, I suspect you don't quite grok the difference. For example, here's how you repro this issue:

```
$ mongo
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.1
> db.createUser({ user: "linkapiAdmin", pwd: "password", roles : [ { role: "clusterAdmin", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readAnyDatabase", db: "admin" }, { role: "userAdminAnyDatabase", db : "admin" }, { role: "dbAdminAnyDatabase", db : "admin" } ] });
Successfully added user: {
	"user" : "linkapiAdmin",
	"roles" : [
		{
			"role" : "clusterAdmin",
			"db" : "admin"
		},
		{
			"role" : "readWrite",
			"db" : "admin"
		},
		{
			"role" : "readWrite",
			"db" : "admin"
		},
		{
			"role" : "readAnyDatabase",
			"db" : "admin"
		},
		{
			"role" : "userAdminAnyDatabase",
			"db" : "admin"
		},
		{
			"role" : "dbAdminAnyDatabase",
			"db" : "admin"
		}
	]
}
> 
```

Auth will then fail both with and without `authSource=admin`. The reason is that the above script created a new user on the `test` database, so auth will _only_ succeed if you specity `authSource=test`. Doesn't matter that the user's permissions are all on the admin db, it will still be associated with the `test` database.  What you want is this:

```
$ mongo
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.1
> use admin
switched to db admin
> db.createUser({ user: "linkapiAdmin", pwd: "password", roles : [ { role: "clusterAdmin", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readWrite", db: "admin" }, { role: "readAnyDatabase", db: "admin" }, { role: "userAdminAnyDatabase", db : "admin" }, { role: "dbAdminAnyDatabase", db : "admin" } ] });
Successfully added user: {
	"user" : "linkapiAdmin",
	"roles" : [
		{
			"role" : "clusterAdmin",
			"db" : "admin"
		},
		{
			"role" : "readWrite",
			"db" : "admin"
		},
		{
			"role" : "readWrite",
			"db" : "admin"
		},
		{
			"role" : "readAnyDatabase",
			"db" : "admin"
		},
		{
			"role" : "userAdminAnyDatabase",
			"db" : "admin"
		},
		{
			"role" : "dbAdminAnyDatabase",
			"db" : "admin"
		}
	]
}
> 
```
