### ISSUE TITLE
Array sub-documents that reuse parent field names behave strangely

### ISSUE THREAD

**Issue by dylanscott** [Automattic/mongoose#4365]
I'm running into an issue with a schema having an array of sub-documents, where the parent and child schemas have a field with the same name. I've written a [pretty minimal](https://github.com/dylanscott/mongoose-repro) repro and I've encountered the issue on mongoose `4.5.7` as well as on `3.8.34`.

The test-case defines two models:
```javascript
const UserSchema = new mongoose.Schema({
  name: {
    type: String,
    default: '',
  }
})
const UserModel = mongoose.model('User', UserSchema)


const GroupSchema = new mongoose.Schema({
  name: String,
  members: [String],
})

const OrganizationSchema = new mongoose.Schema({
  members: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }],
  groups: [GroupSchema],
})
const OrganizationModel = mongoose.model('Organization', OrganizationSchema)
```

The important thing here is that the organization model and child group model both have a field named `members`. The weirdness occurs when we try to push to a group sub-document's `members` field after having loaded the organization with a populated `members` field (to be clear, the parent's `members` field is populated, not the child one we're pushing to). You can check out the [test case](https://github.com/dylanscott/mongoose-repro/blob/master/repro.js#L71) but the long story short is:

```javascript
return OrganizationModel.findOne({}) // we created one org previously
.populate('members', 'name')
.exec()
.then((org) => {
  org.groups.push({ name: 'Rocket' })
  return org.save()
})
.then((org) => {
  const teamRocket = org.groups.find((team) => team.name === 'Rocket')

  console.log('team.members before', teamRocket.members)
  // prints: `team.members before []`

  teamRocket.members.push('Jessie')

  console.log('team.members after', teamRocket.members)
  // prints: `team.members after ["{ name: '' }"]`
})
```

Digging into the code, it looks like when you push to the array, there is a check whether that array was populated in which case the element being pushed needs to be cast to the populated model. The problematic check seems to be [here](https://github.com/Automattic/mongoose/blob/d2e1091f31ee0bacb5ee3f8b8b0e0e5eca2a2be7/lib/types/array.js#L98) where we end up checking if the parent `members` field is populated, conclude that it is, and end casting to its model (in this case the `UserModel`).

**Comment by vkarpov15** [comment]
Thanks for the repro, will check this out next week
