### ISSUE TITLE
How to handle mongod service stop

### ISSUE THREAD

**Issue by pkantsedalov** [Automattic/mongoose#4368]
Hi everybody.

I am using **Node.JS 6.3.0** and **Mongoose 4.5.3** and I couldn't catch the case when I stop mongod process using `sudo service mongod stop`. After I do that the only result is the exit from a running app. I tried server options (auto_reconnect etc.) and handlers for **disconnected**, **close** etc. - no result.

Here is an example of my code:
``` javascript

// method of MongoConnection class
connect(options = {}) {
        return new Promise((resolve, reject) => {

            /**
                 options = {
                      "MyConnection": {
		         "options": {
			       "readPreference": "ReadPreference.PRIMARY_PREFERRED",
			       "connectTimeoutMS": 300000,
			       "socketTimeoutMS": 300000
                           },
                          "user": "",
                          "password": "",
                          "host": "localhost:27017",
                          "db": "MyDatabase" 
                        }
                 }
            */
            this._connection = mongoose.createConnection(this.makeUrl(options));

            this._connection.on('open', () => {
                LogHelper.info(`MongoDB connection has been opened`);
                resolve();
            });

            // works fine, but not fired when I kill **mongod** process
            this._connection.on('error', error => {
                LogHelper.info(`${this} interrupt with an error`, error);
                reject(error);
            });
        });
    }

```

Please help.

**Comment by pkantsedalov** [comment]
UPD: I've caught that with process.on('exit', callback), but now I have another problem: the exit code is 0 and I couldn't find the place where this exit was made.

**Comment by vkarpov15** [comment]
Are you connecting to a replica set? Below script works fine for me with single mongod using mongodb 3.0:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.set('debug', true);

var _connection = mongoose.createConnection('mongodb://localhost:27017/gh4368');

_connection.on('open', () => {
    console.log(`MongoDB connection has been opened`);
});         

// works fine, but not fired when I kill **mongod** process
_connection.on('error', error => {
    console.log(`${this} interrupt with an error`, error);
});         

_connection.on('close', error => {
    console.log('closed');
});
```

Output looks like this:

```
$ node gh-4368.js 
MongoDB connection has been opened
closed
```

where close happens after I kill mongodb. Can you see if the above script works for you?

**Comment by pkantsedalov** [comment]
Thanks a lot for the answer, I've fixed it in [this way](http://stackoverflow.com/questions/38609323/handle-mongod-stop-with-nodejs-and-mongoose). It was not an mongoose issue but the lack of my experience.

**Comment by sibelius** [comment]
@pkantsedalov your link is broken, could you post your solution here?

**Comment by pkantsedalov** [comment]
@sibelius Here it is (btw, I haven't found the link broken).

> I've found the solution of that. It happened because we don't have any waiting I/O operations, so node.js decided to stop the app as it does usually. We had a recursive function and when we were in it and connection became lost we weren't able to catch it - the app stopped immediately before any "error", "disconnected" or other event handler, but the mongoose after all tried to reconnect. So be careful with it. We decided to open/close a connection inside the function we recursively call - now it works OK.
