### ISSUE TITLE
Documentation of instance methods

### ISSUE THREAD

**Issue by wasadigi** [Automattic/mongoose#4373]
In the documentation, there is a paragraph about *instance methods* that can be defined for schemas:

```
// define a schema
var animalSchema = new Schema({ name: String, type: String });

// assign a function to the "methods" object of our animalSchema
animalSchema.methods.findSimilarTypes = function(cb) {
  return this.model('Animal').find({ type: this.type }, cb);
};
```
I was surprised by this example and I wonder if I a missing something:

- for one schema, one can define several models. In the example below, one could think of a model of pets, another model of wild animals, etc. If I define method for the schema, then I expect it to be available on all the models built from the schema.

- in the code below, we reference one specific model in a function attached to the schema methods. To come back to my example, I should either pick 'pet' animals or 'zoo' animals, and I would not get expected results half of the time.

- I found in a couple of posts/issues that you can retrieve the model used to create a document and rewrite the previous code like this:

```
// define a schema
var animalSchema = new Schema({ name: String, type: String });

// assign a function to the "methods" object of our animalSchema
animalSchema.methods.findSimilarTypes = function(cb) {
  return this.constructor.find({ type: this.type }, cb);
};
```

Is this correct? Is there any reason for which the code in the documentation is better? Am I missing anything?

**Comment by clanofnoobs** [comment]
Hmm, I'm actually not sure about this. But I've come across another issue. The animalSchema.methods.findSimilarTypes worked for me before but now for some reason `this` is just an empty object inside of `.findSimilarTypes`.

**Comment by vkarpov15** [comment]
I'm very confused by your second bullet point in the original post, can you clarify?

Re: third bullet, yep, that code should work well because in `findSimilarTypes`, `this` should refer to the document, and `doc.constructor` refers to the model that was used to create the document.

Re: https://github.com/Automattic/mongoose/issues/4373#issuecomment-235823866, code sample please?

**Comment by timscott** [comment]
@clanofnoobs - I also had the problem of ```this``` being undefined. The problem was I used fat arrow syntax instead of function. So changing from this ```() => {}``` to this ```function() {}``` fixed it for me.
