### ISSUE TITLE
Breaking change in version 4.5.0: changing a discriminator key is ignored

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#4374]
There has been a breaking change between version 4.4.20 and 4.5.0.

I have a schema with a discriminator the key of which is 'Test'. The key  field has been renamed from __t to type. The reason for this change is a RESTful API framework which automatically maps JSON to mongoDB documents and __t is not very nice or meaningful in such an API. The following mocha test changes the type (therefore the key) from 'Test' to 'Dummy', which does not exist.

The presave middleware ensures to invalidate the document if such a change occurs and the API returns a bad request. This worked fine until version 4.5.0 because now teh change is discarded before calling the presave middleware, so there is no way to return an error to the user of the RESTful API to let him/her know that here change has not been accepted.

```
Test.findOne({ language: data.language, _summaryId: data._summaryId, _id: data._id }, function (error, version) {
    expect(error).to.be.null;
    expect(version).to.be.an.instanceof(Test);
    if (!error && version instanceof Test) {
        version.type = 'Dummy';
        version.save(function (err, saved) {
            if (mongoose.version < '4.5') {
                expect(err).to.be.an.instanceof(mongoose.Error.ValidationError).with.property('errors');
                expect(err.errors).to.have.property('type').that.is.an.instanceof(mongoose.Error.ValidatorError).with.property(mongoose.version < '4' ? 'type' : 'kind', 'user defined');
                expect(Object.keys(err.errors)).to.be.an.instanceof(Array).with.property('length', 1);
                expect(saved).to.be.undefined;
            } else {
                // Note: recent versions of mongoose discard the change
                expect(error).to.be.null;
                expect(version).to.be.an.instanceof(Test).with.property('type', 'Test');
            }
            callback();
        });
    } else {
        callback(error);
    }
});
```

I suggest you revert back to the old way, because discarding a user change without any warning is not right.

**Comment by vkarpov15** [comment]
Good call, will fix early next week. Thanks for the clear repro instructions :+1:

**Comment by vkarpov15** [comment]
So this change is related to #2041, making it so that you don't need a pre save middleware to catch changes to the discriminator key. However, you're right that silently swallowing changes to the discriminator key is not the best behavior. In the above changes I made it so that changing the discriminator key causes an error
