### ISSUE TITLE
Problem with understanding of new mongoose stream deprecation

### ISSUE THREAD

**Issue by NikitaLiashenko** [Automattic/mongoose#4376]
It's simple question not an issue, but I can't understand how I can replace query stream with cursor. I want to pipe my query result directly to standard express response. Could anybody explain me how I can do this using mongoose 4.5.7? There are no examples at all.

**Comment by vkarpov15** [comment]
Are you doing this currently with `.stream()` ? General idea can be found here: http://stackoverflow.com/questions/13503844/streaming-piping-json-stringify-output-in-node-js-express

**Comment by NikitaLiashenko** [comment]
Actually it's not the same thing. 
Using mongoose 4.3.6 I can write something like this:
`Model
  .find()
  .stream()
  .pipe(JSONStream.stringify)
  .pipe(response)`
But now I can't do this, cause I get error 
"... Query.stream() is now deprecated. Use Query.cursor()..."
I have tried to use it, but it's not the same thing. As I understood, I should have an event listener on 'data' event, then get objects one by one and do something with them.
I have tried to write something like `Model.find().cursor.stream().pipe()...`,  and `Model.find().cursor.pipe()...` and so on, but nothing works.
Could you please help me with this?How can I pipe query result directly to Express response?

**Comment by vkarpov15** [comment]
Umm have you tried `Model.find().cursor().pipe()`? That should work fine with JSONStream, can you show me a more detailed code example?

**Comment by NikitaLiashenko** [comment]
Oh, I am so sorry. This really works exactly as expected.
Thank you so much for your help.
