### ISSUE TITLE
Pass parameters to middleware or call schema methods for bulk operations?

### ISSUE THREAD

**Issue by techpool** [Automattic/mongoose#4380]
I am doing a bulk insertion operation like the following:
`bulk.find({ _id: new ObjectId(valuemaps[i]._id) }).upsert().updateOne(updatedObj);`

and then doing an execute operation like

`bulk.execute(function(err, result) {
        if (err) {
            logger.log('error', 'Error upserting', err);
            return res.status(500).send(err)
        }
        return res.status(201).send(result);
    });`

What I want to do is pass all these objects through a middleware in order to set the createdBy or updatedBy parameter in them. Is there any way to do this? I could not find any docs where it is mentioned about how to pass values to middleware for bulk operations.

**Comment by vkarpov15** [comment]
Can you show me a more detailed code sample and clarify which version of mongoose you're using? Mongoose doesn't even support this deprecated style of bulk ops to the best of my knowledge
