### ISSUE TITLE
use populate in pre find is not work

### ISSUE THREAD

**Issue by kelvv** [Automattic/mongoose#4386]
modelSchema.pre('find',function(next){
		this.where({
			isvalid : true
		}).populate('-background');
        next();
    })

it not work,background is null, who can help?

**Comment by vkarpov15** [comment]
Why is the - there?

**Comment by kelvv** [comment]
if i remove the - 

the same result :background is null i god

**Comment by vkarpov15** [comment]
Can you show me your schema? Also, does it work if you use populate outside of the pre find hook?
