### ISSUE TITLE
Validation/Cast Error when 'setting' the discriminator key: breaking change?

### ISSUE THREAD

**Issue by tusbar** [Automattic/mongoose#4387]
The change introduced in https://github.com/Automattic/mongoose/commit/f16a447746de0154807bf4452c812a78b60c5c85 prevents from _cloning_ documents/models using the `Model` constructor (i.e. `const clone = new original.constructor(original);`) if that model has a discriminator key.

The same behavior can now be achieved by doing something like

```js
new original.constructor(original.toObject({
    transform: (doc, res) => {
        delete res[doc.schema.options.discriminatorKey];
    }
}));
```

**Comment by mmoulton** [comment]
I'm using a library for node called [Baucis](https://github.com/wprl/baucis) that is also being affected by the change in `f16a447`. With Mongoose 4.5.8 I'm getting errors such as `Cast to String failed for "SomeDiscriminator" value at path "__t"`. Everything works great with 4.5.7.

While I haven't traced the exact offending code in Baucis yet, it seems to be related to the example in this issue.

**Comment by Blackbaud-SteveBrush** [comment]
Need a fix for this as well (or appropriate documentation for best practices)
+1

**Comment by ReedD** [comment]
Same, I'm now getting this error while saving: `CastError: Cast to String failed for value "SOMEVALUE" at path "kind"`

**Comment by vkarpov15** [comment]
So 4.5.10 will not error if the discriminator key is unchanged, so you should be able to clone as specified in OP. Generally speaking, you should _not_ change the discriminator key, but as long as you use the same model for this clone operation you should be fine.
