### ISSUE TITLE
fetch value from one schema and update in other using middlewares 

### ISSUE THREAD

**Issue by shubsaini09** [Automattic/mongoose#4389]
While updating Movie documents, get value from User collection and save it with the documents getting updated in Movie.

Movie.pre('update', function (next) {
   var id = this._update.$set.userid;
   var some = this;
   User.findOne({userid: id}, function(err, post) {
       // **how should we add the firstname to current movie document and let update query update it all. Something like this**...
       some.firstname = post.firstname;
       next();
   });
});

// update query
Movie.statics.saveMovieDetails = function(requestData, callback) {
this.update({userid:requestData.userid},
    { $set:{
            userid   : requestData.userid,
            name     : requestData.name,
            location : requestData.location,
            language : requestData.language,
            date     : requestData.date
        }
    },{upsert:true}, callback);
};

**Comment by shubsaini09** [comment]
solution - 
Movie.pre('update', function (next) {
	var id = this._update.$set.userid;
	var some = this;
	User.findOne({userid: id}, function(err, post) {
		some.update({userid: id},{ $set: { bookie: post.firstname }});
		next();
	});
});

**Comment by shubsaini09** [comment]
This is how i did it. Correct me if i am wrong or if there is any better way to solve this problem.

Movie.pre('update', function (next) {
  var id = this._update.$set.userid;
  var some = this;
  User.findOne({userid: id}, function(err, post) {
      some._update.$set.firstname = post.firstname;
      next();
  });
});

**Comment by vkarpov15** [comment]
Id recommend using some.update like recommended in #3303 . does that not work for you?

**Comment by shubsaini09** [comment]
I tried but it did not work. Results in two update queries for same document.
