### ISSUE TITLE
Assign Promise Implementation to Browser mongoose

### ISSUE THREAD

**Issue by mkastner** [Automattic/mongoose#4395]
I might be missing something, but I wasn't able to figure out how to assign the preferred promise implementation to the mongoose Instance in the **browser**.

I've tried
```
     mongoose.Promise = Promise // which is bluebird in that case
```

but I still get the deprecation warning:

_util.js:61 Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html_

The examples on that page don't seem to apply to the browser version.

**Comment by vkarpov15** [comment]
Hmm I don't think I've ever tried that, wouldn't bee surprised if there was a bug there. Will fix

**Comment by richardpj** [comment]
Yup.  This is broken.  The browser implementation does not respect the promise replacement.
`mongoose.Promise = Promise //this does nothing`
Worse still the browserified bundle deprecation notice falls into infinite recursion.  I've had to monkeypatch it by "undeprecating" `mpromise.then` (by removing lib/promise.js:73-76) in my browser bundle.
