### ISSUE TITLE
Mongoose Error

### ISSUE THREAD

**Issue by koushikmln** [Automattic/mongoose#4397]
Error [TypeError: Object #<Object> has no method 'apply']
Caught exception: TypeError: Object #<Object> has no method 'apply'
    at /home/ubuntu/appBackend/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at process._tickCallback (node.js:415:13)

Works if i change the version of mongoose. installed the current npm version.

**Comment by koushikmln** [comment]
mongo version 2.4.9

**Comment by vkarpov15** [comment]
Code sample please?

**Comment by koushikmln** [comment]
```
                var notification = new notifications({
			channelId:vendor.channelId.slice(),
			vendorId:vendor._id,
			vendorName:vendor.name,
			text:text,
		});
		notification.save(function(err, notification) {
			if(!err){
				res.json({success:true,message:"Notification Successfully Posted"});
			}else{
				res.json({success:false,error:'Database Error'});
			}
		});
```

**Comment by vkarpov15** [comment]
Gonna need some more info, like what the schemas look like and what the vendor object looks like
