### ISSUE TITLE
Make CastError message clearer

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4398]
I am facing this kind of CastError:

```
CastError: Cast to ObjectId failed for value "[object Object]" at path "_id"
```

Unfortunately for me, all of my schema's have an `_id` field, and the `[object Object]` is not giving me much details either, so it's kind of impossible for me to deduce where this error is thrown from or why.

Could we make the error message a bit clearer to indicate perhaps the schema involved? And perhaps if an object is given, we can provide at least a one level deep representation of it?

This would make debugging this error much easier.

**Comment by vkarpov15** [comment]
yeah we should probably use util.inspect instead of toString
