### ISSUE TITLE
Sub schema's discarding `_id` if set via virtual setter

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4399]
Consider the following code:

```js
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const ObjectId = mongoose.Types.ObjectId;

const SubSchema = new Schema({
  _id: Schema.Types.ObjectId,
  name: String,
});
SubSchema.virtual('id').set(id => {
  this._id = new ObjectId(id);
  console.log('Virtual ID set, _id =', this._id);
});

const TestSchema = new Schema({
  name: String,
  sub: [SubSchema],
});

const Test = mongoose.model('Test', TestSchema);

let id = new ObjectId().toString();
console.log('ID =', id);

let test = new Test({
  name: 'Main',
  sub: {
    id,
    name: 'Sub'
  }
});

console.log(test.toObject());
```

Actual output is:

```
ID = 57a7a8baa1ad468716c15907
Virtual ID set, _id = 57a7a8baa1ad468716c15907
{ name: 'Main',
  _id: 57a7a8baa1ad468716c15908,
  sub: [ { name: 'Sub' } ] }
```

Expected output is:

```
ID = 57a7a8baa1ad468716c15907
Virtual ID set, _id = 57a7a8baa1ad468716c15907
{ name: 'Main',
  _id: 57a7a8baa1ad468716c15908,
  sub: [ { 
    _id: 57a7a8baa1ad468716c15907,
    name: 'Sub' 
   } ] }
```

Why is Mongoose discarding my `_id` on the sub document that I've set with the virtual setter?

This is part of my ongoing struggle with `id` vs `_id` as I lamented about in the other issue ;)
I'm trying to automatically convert the `id` as received from JSON to `_id` for the sub document, but haven't had any luck so far.

I have tried pre-save hooks, post-init hooks, virtual setters... nothing works :(

I will have to resort to manually pre-parsing my JSON data until this issue is resolved or clarified.

**Comment by vkarpov15** [comment]
Yeah upon more careful inspection this (pun intended) is a subtle bug in your code. Look closely at:

```javascript
SubSchema.virtual('id').set(id => {
  // `this` is the global object here, so you're setting _id on something that is *not* the mongoose doc
  this._id = new ObjectId(id);
  console.log('Virtual ID set, _id =', this._id);
});
```

Change to:

```javascript
SubSchema.virtual('id').set(function(id) {
  this._id = new ObjectId(id);
  console.log('Virtual ID set, _id =', this._id);
});
```

and everything works fine. In haiku,

Fat arrows are great
But they lose function context
Refrigerator

**Comment by adambuczynski** [comment]
Haha, you're right... get so used to using fat arrows, forget sometimes it breaks the context of `this`. Thanks for picking this up.
