### ISSUE TITLE
Pagination & Cursor API

### ISSUE THREAD

**Issue by mleanos** [Automattic/mongoose#4401]
I'm very happy to see the introduction of the Cursor API in Mongoose. I can see many great uses for it.

I'm currently struggling with coming up with a scaleable & performant solution to pagination using Mongoose; currently, I'm using a count query (based on a query with a filter), and a `limit()` & `skip()` query. Pretty much as described in [this issue](https://github.com/Automattic/mongoose/issues/1908#issue-26610833).

However, in the context of pagination, I'm having a hard time seeing the usefulness of the `hasNext` property of the underlying cursor. While we can use it to tell the client that we still have more pages to come, how would we indicate how many more items & pages are in the collection without an exact count? Unless we're relying on client-side logic to keep fetching until we've exhausted the collection query results. Thus, sending each item back to the client one at a time. Would this be the suggested approach?

See this MEANJS pull-request for reference: [feat(articles): Server-side paging for list](https://github.com/meanjs/mean/pull/1263).

Would this type of use case benefit from Streaming? If so, what would that look like?

**Comment by vkarpov15** [comment]
See my comment https://github.com/Automattic/mongoose/issues/1908#issuecomment-239315629 . long story short cursor api is not really helpful for pagination. Most of the time skip + limit with good indexes is good enough

**Comment by mleanos** [comment]
My response is a bit late, but thank you for confirming my hunch. I've found that indexes were essential for my use case.

**Comment by davidlondono** [comment]
you can use my module [mongoose-paginate-cursor](https://github.com/davidlondono/mongoose-paginate-cursor)
