### ISSUE TITLE
Error message body lost when using native ES6 promises

### ISSUE THREAD

**Issue by ericgrosse** [Automattic/mongoose#4407]
If I send a custom error through a pre-validation hook, it doesn't get properly caught by my promise's `catch` block. Here is a code example:

***

Validate function

```
userSchema.pre('validate', function(next) {
  if (this.isModified('email')) {
    Model.User.find({email: this.email}, function(err, matches) {
      if (matches.length > 0) {
        next(new Error('This email is already in use'));
      }
      next();
    });
  }
  else {
    next();
  }
});
```

According to the Mongoose docs, `next(new Error('This email is already in use'));` should propagate to the callback of `<userDocument>.save()`

***

Function that invokes save

```
function putOne(reqBody, res, Model, queryObj, options) {
  // Prevent PUT requests from updating locked fields
  if (options && options.lockedFields && intersection(Object.keys(reqBody), options.lockedFields).length > 0 ) {
    return res.status(500).json({
      error: 'Cannot update a locked field',
      lockedFields: options.lockedFields
    });
  }

  return Model.findOne(queryObj).exec()
  .then(function(match) {
    if (match) {
      modifyReq(match, reqBody);
      return match.save();
    }
    else {
      return res.status(500).json({error: 'no match found'});
    }
  })
  .catch(function(err) {
    return res.status(500).json({error: err});
  });
}
```

Here I'd expect the error propagated to

`return match.save();`

to be caught here:

```
.catch(function(err) {
  return res.status(500).json({error: err});
});
```

And sure enough it does catch an error, except that it reports absolutely nothing. The response is

```
{
  "error": {}
}
```

Contrast this to the usual way of catching the error:

```
match.save(function(err, doc) {
  if (err) {
    return res.status(500).json(err);
  }
});
```

This actually captures the custom error message `'This email is already in use'`.

For clarity, I am using `mongoose.Promise = global.Promise;`

**Comment by vkarpov15** [comment]
Be careful with passing Error objects to `res.json()`, since [error objects don't have a `toJSON()` function](http://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify). TLDR; `res.json()` calls `res.send(JSON.stringify())` which in turn looks for `toJSON()` functions to convert the object into JSON, so error objects don't get properly converted to JSON by default:

```
$ node
> JSON.stringify(new Error('test'))
'{}'
> JSON.stringify({ err: new Error('test') })
'{"err":{}}'
> 
> 
> 
> Error.prototype.toJSON
undefined
> Error.prototype.toJSON = function() { return this.message; }
[Function]
> JSON.stringify({ err: new Error('test') })
'{"err":"test"}'
> 
```

The right way to do this is `return res.status(500).json({error: err.message});`, has nothing to do with mongoose.
