### ISSUE TITLE
Mongoosejs.io logo linking to mongoose.com

### ISSUE THREAD

**Issue by mithralaya** [Automattic/mongoose#4409]
Hello,

In discover plugin page, the logo is linking to mongoose.com. I hope its not intentional :)

http://plugins.mongoosejs.io

Karthik

**Comment by vkarpov15** [comment]
Was fixed in https://github.com/vkarpov15/mongooseplugins/commit/a4528410448a202a2d066e8ccc69d6d60bf5d426 but unfortunately I haven't redeployed yet :(
