### ISSUE TITLE
Increment `updatedAt` for nested schemas when setting a nested path in update

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#4412]
``` javascript
var childSchema = new Schema({ name: String }, { timestamps: true });
var parentSchema = new Schema({ child: childSchema });
var Parent = mongoose.model('Parent', parentSchema);

// Should set `child.updatedAt` as well. Currently does not do so
Parent.update({}, { $set: { 'child.name': 'Luke' } });
```

Re: #4049

**Comment by joaoreynolds** [comment]
+1 for this! In the meantime I can set it explicitly with my update, but it does seem like something mongoose should handle.

Thanks for your hard work, I wish I could help!

**Comment by vkarpov15** [comment]
Thanks for reporting the $push issue, will fix as well.

**Comment by akashdeepsinghal** [comment]
Hi! Any updates on this?

**Comment by vkarpov15** [comment]
@akashdeepsinghal nope, not yet. We'll add this to our next minor release :+1:

**Comment by MBayoumi** [comment]
AssignmentSchema = new mongoose.Schema({
  agentId: {type: String},
}, { strict: false, timestamps: true });


this.conversationModel.findByIdAndUpdate(conversationID, { $push: { assignments: assignment } }, {
      new: true,
      upsert: true,
    });

when i use $set timestamps fields were created and works fine but when i'm using $push timestamps fields don't

**Comment by vkarpov15** [comment]
@MBayoumi please open up a separate issue with detailed code samples and what version of Mongoose you're using.
