### ISSUE TITLE
Please update docs for createConnection

### ISSUE THREAD

**Issue by cortopy** [Automattic/mongoose#4413]
Mongoose was hanging on every single request to my database. After too many hours of frustration, it turns out that the [answer at Stackoverflow](http://stackoverflow.com/questions/22786374/queries-hang-when-using-mongoose-createconnection-vs-mongoose-connect#answer-22838614) clarifies what the docs don't.

I was using `createConnection` when I should have used `connect`.

There are many more questions around with exactly the same problem. I only wish that: 

- the docs were clear about this
- there was some sort of error when connect/createConnection are not used appropriately. Mongoose doesn't throw error, doesn't say anything. It just HANGS! I've tried with promises, callbacks and everything else I know with the frustration of knowing there was something with Mongoose I couldn't debug

**Comment by Jeff-Lewis** [comment]
In refactoring our connection setup, I struggled with this as well. I was surprised the promise nor the callback return the instance of the connection when successful. Can we have the promise and callback return the instance of the connection so that event handlers could be setup on that connection?

Also, when only createConnection is used, the default mongoose.connection.name is null as the default connection is not used. This was a little confusing as well.

@cortopy do you have a config setup that hangs mongoose to reproduce?

**Comment by vkarpov15** [comment]
Yeah I've gotten bit by this a few times myself, it's a subtle distinction that was mostly put in as a way to avoid extra callbacks. Nowadays with co it's not quite as important.

Simple idea: throw an error if you try to run an operation on a connection that you haven't explicitly opened. So `mongoose.connect()` followed by whatever else in the same tick will work, but if you haven't called `mongoose.connect()` it'll bug out.

@Jeff-Lewis the general idea with `createConnection()` is that you just start using the connection immediately without waiting for a callback.

**Comment by cortopy** [comment]
@Jeff-Lewis My config is pretty basic.

To connect now:
```javascript
mongoose.connect(connectionString)
  .then(() => logger.info("Successfully connected to MongoDB. Starting web server..."))
  .catch(err => logger.error("Unable to connect to MongoDB: ", err))
  .then(() => server.start())
  .then(() => logger.info("Successfully started web server. Waiting for incoming connections..."))
  .catch((err) => logger.error(err));
```

And the model
```
mongoose.Promise = require("bluebird");
```

**Comment by joscarcab** [comment]
I have this code and catch isn't working.

`const restify = require('restify');
const config = require('config');
const logger = require('modules/logger');
const router = require('router');
const Promise = require('bluebird');
const mongoose = require('mongoose');

mongoose.Promise = require('bluebird');

mongoose.connect(Config.get('mongodb.uri'))
.then((err) => console.log('then', err))
.catch((err) => {
    console.log('catch',err);
    process.exit(1);
  }
);`

**Comment by vkarpov15** [comment]
Please clarify what you mean by "not working"
