### ISSUE TITLE
Nested population fails when combined with select

### ISSUE THREAD

**Issue by NikxDa** [Automattic/mongoose#4414]
Hi there,

I currently have a database structure where there is a nested object B in object A. Object B has multiple fields which are select: false, therefore I have to actively select them to be usable. Those fields themselves reference more objects. My turn on this was the following:

```
objectA
.findOne (data)
.populate ({
path: "fieldOne",
select: "+nestedFieldOne +nestedFieldTwo",
populate: "nestedFileOne"
})
.exec ()
```

The expected result would be objectA with a populated fieldOne, which itself has two fields nestedFieldOne and nestedFieldTwo, where nestedFieldOne is again populated. 

The actual result is, that nestedFieldOne is null.

What am I missing here?

**Comment by vkarpov15** [comment]
Can you show me your schemas please?
