### ISSUE TITLE
Cannot Query By _id

### ISSUE THREAD

**Issue by aconfee** [Automattic/mongoose#4416]
Hello, 

I'm trying to find a document by an _id that very clearly exists, but am getting null back. Do you have any idea or helpful insights into what might be happening here?

Shell:

> db.examples.find().pretty()
{
	"_id" : ObjectId("57b116e340df84ac7d70895f"),
	"name" : "First Example",
	"data" : [
		{
			"name" : "First Example Child Data",
			"data" : 7
		}
	]
}
> db.examples.findOne({ _id: "57b116e340df84ac7d70895f" }).pretty()
2016-08-15T01:25:45.923-0500 E QUERY    [thread1] TypeError: db.examples.findOne(...) is null :
@(shell):1:1

I've tried all permutations of "_id": "...", _id: "...", _"_id": ..., etc. I've also tried using findById with mongoose in my code. 

In the shell, if I surround the id with 'ObjectId(...)' it will work, but I haven't had to do this with any previous projects. In fact, all of my previous projects have never had trouble with this, and I can't figure out for my life what's different here. 

Any help very greatly appreciated. Thanks,
Adam

**Comment by aconfee** [comment]
As a note, this is occurring in my local and dev environments.

**Comment by ypanyukov** [comment]
Hi @aconfee. Firstly, findOne already returns pretty output.

Regarding your case. Check please db.examples.findOne({ _id: ObjectId('57b116e340df84ac7d70895f') })

**Comment by aconfee** [comment]
Hey @ypanyukov, thanks for your quick response. Using the syntax provided, I'm able to retrieve the correct information. 

It turns out that I was encountering two issues that were closely related and misleading. Please let me know if you're interested in knowing what the problem was, but it was completely irrelevant and far removed form the original problem. 

Thanks,
Adam

**Comment by ypanyukov** [comment]
@aconfee you are welcome!
