### ISSUE TITLE
bulk.find().upsert().replaceOne() - get the IDs of replaced documents

### ISSUE THREAD

**Issue by dpaczewski** [Automattic/mongoose#4417]
Hi. I'm running bulk query with upsert combined with replaceOne - the idea is to insert the document to the database or update it if it exists. The thing is that I would like to run some additional checks on the documents that have been replaced - **is there a way to get their IDs**? As for now I can get the IDs of the documents that have been upserted. Let's say that:

- I have 25 documents in the collection
- I run bulk.upsert.replaceOne with the list of 30 documents WITH 25 already present in the database
- I get the information about new 5 documents (their IDs) but I don't get the information about the IDs of the replaced documents

I think this could be very helpful to other developers as well.

> getRawResponse:  { ok: 1,
  writeErrors: [],
  writeConcernErrors: [],
  insertedIds: [],
  nInserted: 0,
  nUpserted: 5,
  nMatched: 25,
  nModified: 25,
  nRemoved: 0,
  upserted: 
   [ { index: 0, _id: [Object] },
     { index: 10, _id: [Object] },
     { index: 13, _id: [Object] },
     { index: 18, _id: [Object] },
     { index: 23, _id: [Object] } ] }

**Comment by vkarpov15** [comment]
Can you show me a code sample? I'm not 100% certain I understand what you're trying to do and don't want to make a mistake in translating prose to code.

**Comment by dpaczewski** [comment]
@vkarpov15:

`		    bulk = this.model('FeedItem').collection.initializeUnorderedBulkOp();

	    for(var i=0; i<feedItems.length ; ++i) {

		    dbFeedItems.push({
		    	_id : {
				    source : "somewhere.com",
				    activityId : feedItems[i]['id']
			    },
			    processed : false,
			    userId : feedItems[i].userId,
			    data : feedItems[i]
		    });

		    bulk.find({_id : dbFeedItems[dbFeedItems.length-1]['_id']}).upsert().replaceOne(dbFeedItems[dbFeedItems.length-1]);
	    }

	    bulk.execute(function(error, done) {
		    if(error) {
			    console.log("Error: ", error);
			    reject(error);
		    } else if (done) {
			    resolve(done);
		    }
	    });`

**Comment by vkarpov15** [comment]
There's a [getUpsertedIds() function that the mongodb driver docs mention](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#initializeOrderedBulkOp), perhaps that's what you're looking for? I'm not terribly familiar with the `initializeOrderedBulkOp` API, it's considered deprecated...

**Comment by dpaczewski** [comment]
Hm, I don't think that's it (I was looking for the ID's of the 25 documents that were replaced rather than upserted) but if that' deprecated then it doesn't make sense to continue this. I will close it. Thaks @vkarpov15.
