### ISSUE TITLE
Error in findOneAndUpdate

### ISSUE THREAD

**Issue by ypanyukov** [Automattic/mongoose#4418]
TypeError: Cannot read property $isSingleNested of undefined

at applyTimestampsToChildren (/Users/yurypanyukov/Projects/easyhire_repo/node_modules/mongoose/lib/schema.js:865

It was changed here https://github.com/Automattic/mongoose/commit/5edeb344d687592af2b49ca1e1bf5705bd4cfc7b#diff-f412f4722a52cf22ed3d0a9a694b837d

**Comment by sidonaldson** [comment]
Yup, found this too. What version is safe?

**Comment by ypanyukov** [comment]
npm install mongoose --save - 4.5.9 the same with --save-dev

**Comment by py09mb** [comment]
Update also throwing this error on a nested schema with timestamps applied. 

```
TypeError: Cannot read property 'createdAt' of undefined
   at applyTimestampsToChildren (D:\Program Files\app\node_modules\mongoose\lib\schema.js:859:33)
```
```
  const schema = new Schema({
    thing: [{
      thing2: { type: String }
    }],
    thing3: { type: ObjectId, required: true },
  }, { timestamps: true });
```

**Comment by almostagile** [comment]
My application is failing where it is using the positional update operator `$`. For example in the following function when a user changes their name:

```js
exports.updateParticipantName = function (user) {
    return Conversation.update(
        {'participants.user': user._id},
        {$set: {
            'participants.$.name': user.name,
        }},
        {multi: true})
        .exec();
};
```

The function `applyTimestampsToChildren` is calling `schema.path(key)` where `key` is `'participants.$.name'` which returns `undefined` as it does not support the positional operator '$'.

**Comment by webjay** [comment]
I get the error `Cannot read property '$isSingleNested' of undefined` when using `.update`

This started happening in version `4.5.9` so I downgraded to `4.5.8` where the error doesn't happen.

    Trace: TypeError: Cannot read property '$isSingleNested' of undefined
        at applyTimestampsToChildren (node_modules/mongoose/lib/schema.js:865:56)
        at Query.<anonymous> (node_modules/mongoose/lib/schema.js:816:7)
        at next (node_modules/kareem/index.js:82:14)
        at Kareem.execPre (node_modules/kareem/index.js:99:3)
        at Kareem.wrap (node_modules/kareem/index.js:231:8)
        at Query._execUpdate (node_modules/kareem/index.js:271:11)
        at Query.update (node_modules/mongoose/lib/query.js:2189:17)
        at node_modules/mongoose/lib/query.js:2230:21
        at Query.exec (node_modules/mongoose/lib/query.js:2223:10)

**Comment by webjay** [comment]
@sidonaldson 4.5.8 is safe.

**Comment by webjay** [comment]
My error happens in similar code as @almostagile

**Comment by webkrak** [comment]
the same error:
`TypeError: Cannot read property '$isSingleNested' of undefined`

I have got during using `update` function:
`{ $set: { 'prints.$.material': 'paper' }`

**Comment by Andargor** [comment]
Same

`[TypeError:  Cannot read property '$isSingleNested' of undefined]`

**Comment by kilianc** [comment]
+1
