### ISSUE TITLE
Incorrect $geoWithin check

### ISSUE THREAD

**Issue by kroleg** [Automattic/mongoose#4419]
After update from 4.5.8 to 4.5.9 mongoose started to throw error: "$geoWithin must specify $geometry" from mongoose/lib/cast.js:151 on this code:
```javascript
model.photo.find({ location: { $geoWithin: { $centerSphere: [[55, 55], 0.0007] } } }).exec();
```

After small investigation i've found that commit https://github.com/Automattic/mongoose/commit/978732b12187976606cd590e60b653aa0cbd7a7d added a check for `$geometry` property, so it is required now. But it's not the only possible option for `$geoWithin`, according to [mongodb docs](https://docs.mongodb.com/manual/reference/operator/query-geospatial/) `$geoWithin` can also have `$box`, `$center`, `$centerSphere` or `$polygon` property.

**Comment by Kenblair1226** [comment]
Observed the same issue. 

Before 4.5.9 I can do this: (with coord as an open loop and mongoose will close it for me)
`model.water.where('loc').within({polygon: coord})`
Now I have to do this: (with coord as a closed loop)
`model.water.where('loc').within().geometry({ type: 'Polygon', coordinates: coord})`

The original code is probably over-simplified but 4.5.9 is too restricted.
