### ISSUE TITLE
applyTimestampsToChildren Bug

### ISSUE THREAD

**Issue by yuzeng** [Automattic/mongoose#4421]
mongoose/lib/schema.js line 855
` _if (Array.isArray(update.$set[key]) &&
            schema.path(key).$isMongooseDocumentArray) {`
Should add a condition:
`&& schema.path(key).schema.options.timestamps_`

Otherwise it is easy to go wrong:
line 858
`  _timestamps = schema.path(key).schema.options.timestamps;
          createdAt = timestamps.createdAt || 'createdAt';_`
error:Cannot read property 'createdAt ' of undefined

Thinks!

**Comment by bbatliner** [comment]
Also noticed this today. Current fix is to explicitly use version 4.5.2, since some patch in between 4.5.2 and 4.5.9 caused the bug to appear.

**Comment by vkarpov15** [comment]
Dup of #4418, fixed in master and will be released tomorrow

**Comment by antoinegomez** [comment]
Hi, also getting this bug with an update an on key that's no in the schema:

```
Cannot read property '$isMongooseDocumentArray' of undefined
    at applyTimestampsToChildren (xaxa/node_modules/mongoose/lib/schema.js:844:29)
```

Tested with 4.5.10 and 4.6.0.
