### ISSUE TITLE
Unhandled promise rejection if `findById` is passed an empty string

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#4423]
If I'm using callbacks and pass empty strings to `findById` for example, it will return an unhandled promise rejection cc @vkarpov15

**Comment by vkarpov15** [comment]
Looks like this was fixed in 4.6.0, the below code works fine for me in 4.6.1 with `mongoose.Promise = require('bluebird');`

```javascript
MyModel.findById('', function(error) {
        assert.ok(error);
        done();
      });
```
