### ISSUE TITLE
is it possibale to ref a sub-doc?

### ISSUE THREAD

**Issue by aweiu** [Automattic/mongoose#4427]
addressCollection:
```
province:{
    name:'xxProvince:',
    _id:'xxxx',
    city:{
      name:'xxCity'
      _id:'xxx'
    }
}

```
userCollection:
```
user:{
 address:{
   ref:"address.city"
 }
}
```
how to link to address.city by 'ref'?
is it possibale to ref a sub-doc

**Comment by Hongbo-Miao** [comment]
Please consider using http://stackoverflow.com/questions/tagged/mongoose first for questions. And you can get quicker response there.

**Comment by vkarpov15** [comment]
No mongoose currently does not support that behavior.
