### ISSUE TITLE
Cancel remove gracefully inside pre hook?

### ISSUE THREAD

**Issue by mgcrea** [Automattic/mongoose#4428]
I was looking into a `softDeletePlugin` that would catch remove call and only perform a small update instead, something like:

``` js
export default function softDeletePlugin(schema, {softDeleteField = 'isDeleted'}) {
  schema.add({
    [softDeleteField]: {type: Boolean, required: true, default: false, select: false}
  });
  schema.pre('remove', function preRemove(next) {
    this.update({[softDeleteField]: true})
      .then(() => {
        next(new Error('error'));
      })

  });
}
```

It kinda works, but I have an error that is thrown. Is there any way to gracefully cancel the remove?

**Comment by vkarpov15** [comment]
Not supported right now unfortunately. What would such an api look like?

**Comment by Jeff-Lewis** [comment]
FYI - Here is a [simplified gist](https://gist.github.com/Jeff-Lewis/6e319ea40a366b8439bb5b4e8bce2561) of a shim over the `mongoose.Model.remove` method that we use. We use it to prevent removing all models in non-testing databases and ensure shard keys are present in conditions.

**Comment by vkarpov15** [comment]
Yeah shimmer or a custom function is probably the right way to do it. You could always just do it so that a document has a `softDelete()` function and the `remove()` function has a pre hook that errors out.
