### ISSUE TITLE
Convert to ObjectId of undefined 

### ISSUE THREAD

**Issue by NgaNguyenDuy** [Automattic/mongoose#4429]
I don't know why when i try to use require('mongoose').Types.ObjectId(undefined) is return random ObjectId?

The version i'm using is 4.5.8

**Comment by vkarpov15** [comment]
That's treated as `new ObjectId()`, that is, the same as passing no parameter, it'll just give you a new id. What are you trying to do?

**Comment by NgaNguyenDuy** [comment]
Hi @vkarpov15 , 

I just want to detect when my users forget that parameter (in this case is ObjectId). What should i do?

**Comment by vkarpov15** [comment]
```javascript
var schema = new mongoose.Schema({
  myId: { type: mongoose.Schema.Types.ObjectId, required: true}
});
```

Does that not work for you?
