### ISSUE TITLE
Mongoose 4.4.20 aggregation cursor NOT WORKING!

### ISSUE THREAD

**Issue by maksRadko** [Automattic/mongoose#4430]
```javascript
      let places = Model.aggregate([]).cursor({ batchSize: 100 }).exec();
      console.log(places); // undefined
```
some body can explain me why this not working?

or this
```javascript
    let cursor = Model.aggregate([], { cursor: { batchSize: 100 } }, () => {
        console.log(arguments)
    }); // Error: Arguments must be aggregate pipeline operators
```

or maybe this
```javascript
    let cursor = Place.aggregate([]).cursor({ batchSize: 100 }).exec(() => {
        console.log(arguments) // never be executed
    });
```

**Comment by maksRadko** [comment]
I solve this problem using native mongodb driver only!

**Comment by Hongbo-Miao** [comment]
this can be closed

**Comment by vkarpov15** [comment]
Is the underlying db connection open when you call `Model.aggregate([]).cursor({ batchSize: 100 }).exec();` ? That code is correct but won't work unless the model is successfully connected to mongodb. Otherwise, you'll want to use

```javascript
MyModel.aggregate([]).cursor({ batchSize: 2500, async: true }).exec(function(error, cursor) {
  // use cursor
});
```

**Comment by devinus** [comment]
@vkarpov15 This behavior changed without a semver major increase if Mongoose happens to semver at all. I'm curious what version did this change? I know that it changed sometime between `4.2.7` and `4.5.10`.

**Comment by maksRadko** [comment]
I think Yes

2016-08-29 23:33 GMT+03:00 Devin Torres <notifications@github.com>:

**Comment by vkarpov15** [comment]
Mongoose does semver, and I'm fairly certain this behavior did _not_ change between 4.2 and 4.5. The only relevant work I can see reviewing the change log is [4.2.0 adding support for the `async` option I mentioned](https://github.com/Automattic/mongoose/blob/master/History.md#420--2015-10-22). Can you provide a more thorough code sample that shows the code that was working in 4.2.7 but broke in 4.5.10?
