### ISSUE TITLE
match and find

### ISSUE THREAD

**Issue by aweiu** [Automattic/mongoose#4431]
Collection:
```
{
  state: true
}
```
Find:
`model.find({state: 1})`
return: [{state: true}]
Match:
`model.aggregate().match({state: 1})`
return:[]
how to make match translate Number to Boolean just like find?

**Comment by Hongbo-Miao** [comment]
Please consider using http://stackoverflow.com/questions/tagged/mongoose first for questions.

**Comment by vkarpov15** [comment]
Mongoose does _not_ do any type casting for aggregation. You'd have to handle that on your own.
