### ISSUE TITLE
push() and save() leaks it's query on the next save() as well

### ISSUE THREAD

**Issue by nicholaswmin** [Automattic/mongoose#4432]
## Overview

When `saving()` an operation, queries from a previous operation that was already saved appear in the next `save()` query as well

### What I do

I call the below method (in rapid succession) with `msg.action` flags that fall:

- The `"newBoard"` case, which simply `push`-es an item into an array
 - I then `save()`

- The `switchBoard` case, which simply toggles a value, that lies outside of the array
 - I then `save()`
 
I'm expecting to see mongoose sending 2 *distinct* queries:

- A `push` query to push the item into the `this.boardBucket.items` Array
- A `set` query to set the value `boardBucket.currentBoardId`

### The problem

Mongoose sends 2 queries but *both* contain the `pushAll` command

> Why does this happen?
> How can I ameliorate this?

### The code

This is the method that get's called which does the operations:

    roomSchema.methods.applyOperation = function(msg, options) {
      options = options || {};
    
      // Adding the below `console.log` to confirm in the logs that this function
      // is indeed called only *twice*
      console.log("Operation " + msg.action);

      switch (msg.action) {
        case "setBoardBucket":
          this.set("boardBucket", msg.msg.boardBucket);
          break;
        case "newBoard":
          this.boardBucket.items.push(msg.msg.board);
          break;
        case "switchBoard":
          this.set("boardBucket.currentBoardId", msg.msg.boardId);
          break;
      }
    
      this.save((err, result) => {
        if (err) console.log(err);
      })
    }

### The Mongoose logs:

As you can see there are 2 distinct queries with *both* containing a `$pushAll` command

    Operation newBoard
    Mongoose: rooms.update({ _id: ObjectId("57b5c537e88db17f17012578") }, { '$pushAll': { 'boardBucket.items': [ { boardId: '147705812266', viewPosition: '{x: 0, y: 0}', _id: ObjectId("57b5c7c28d08643f18640332"), undoedItems: [], boardItems: [] } ] } })
    Operation switchBoard
    Mongoose: rooms.update({ _id: ObjectId("57b5c537e88db17f17012578") }, { '$set': { 'boardBucket.currentBoardId': '147705812266' }, '$pushAll': { 'boardBucket.items': [ { boardId: '147705812266', viewPosition: '{x: 0, y: 0}', _id: ObjectId("57b5c7c28d08643f18640332"), undoedItems: [], boardItems: [] } ] } })

**Comment by vkarpov15** [comment]
what does the code calling `applyOperation()` look like? It looks like there's no way for the caller to know when applyOperation is done saving, so it looks like you have a race condition there

**Comment by nicholaswmin** [comment]
Well, it's being called by a websocket event-listener and you are right - I don't wait until `save()` is done before calling it again.

I assumed that mongoose internally tracks the changes issued to it so there won't be any dupe ops when `save()` is called.

Should I always wait for the `save()` callback before processing the next message?

**Comment by vkarpov15** [comment]
Yes you should. Mongoose does track changes, but it keeps the changes until the document has been successfully saved (in other words, if an error occurs in save, mongoose still retains all the changes so you can retry), so you should wait until one save has finished before calling another on that same document.

**Comment by nicholaswmin** [comment]
Allright got it, thanks a lot 👍 

In case someone stumbles upon this I've asked a S.O question about implementing a *serially processed message queue whereas each message is processed asynchronously*

So if anyone has the same use case as me, this message queue can be implemented which waits for each `save()` to finish before moving on to the next op.

Here it is: http://stackoverflow.com/questions/39044183/serially-processing-a-queue-of-messages-whose-processing-is-async

There's a practical answer on implementing the above as well

**Comment by vkarpov15** [comment]
Just track the last promise and chain `then()` calls

```javascript
roomSchema.methods.applyOperation = function(msg, options) {
  options = options || {};

  // Adding the below `console.log` to confirm in the logs that this function
  // is indeed called only *twice*
  console.log("Operation " + msg.action);

  switch (msg.action) {
    case "setBoardBucket":
      this.set("boardBucket", msg.msg.boardBucket);
      break;
    case "newBoard":
      this.boardBucket.items.push(msg.msg.board);
      break;
    case "switchBoard":
      this.set("boardBucket.currentBoardId", msg.msg.boardId);
      break;
  }

  return this.save()
}

// later
const doc;
let lastPromise = Promise.resolve();
stream.on('data', function(msg) {
  lastPromise = lastPromise.then(doc.applyOperation(msg));
});
stream.on('end', () => lastPromise.then(() => console.log('done!')))
```

Should work fine unless your stream is spitting data too fast and you run out of memory.

**Comment by vkarpov15** [comment]
Mongoose's `eachAsync` function might be useful too http://thecodebarbarian.com/cursors-in-mongoose-45.html

**Comment by nicholaswmin** [comment]
Guess that's another way to hit it - thanks again
