### ISSUE TITLE
Will Mongoose check the  type of find() queryObject?

### ISSUE THREAD

**Issue by SoaringTiger** [Automattic/mongoose#4433]
model.find(queryObj) 
When queryObj is a string type,query will return all documents.
Example:
`
var queryObj = 'abc';
myModel.find(queryObj).exec();
`
In mongo shell , find() function will throw error with wrong queryObject type.
Will Mongoose check the  type of find() queryObject?

**Comment by vkarpov15** [comment]
Mongoose will check the object but it will silently ignore if you pass a string to `find()`
