### ISSUE TITLE
Validators not run on embedded schema during updates

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#4441]
The following test fails in master -- the validator is never invoked:

```js
it.only('runs validation on Mixed properties of embedded arrays during updates (gh-4441)', function(done) {
  var db = start();

  var A = new Schema({str: Mixed});
  var validateCalls = 0;
  A.path('str').validate(function(val, next) {
    ++validateCalls;
    next();
  });

  var B = new Schema({a: [A]});

  B = db.model('b', B);

  B.findOneAndUpdate(
    {foo: 'bar'},
    {$set: {a: [{str: {somekey: 'someval'}}]}},
    {runValidators: true},
    function(err) {
      assert.ifError(err);
      assert.equal(validateCalls, 1); // AssertionError: 0 == 1
      db.close(done);
    }
  );
});
```

I *think* the docs titled ["Required Validators on Nested Objects"](http://mongoosejs.com/docs/validation.html#required-validators-on-nested-objects) are actually describing this problem: `str` is a prefix to whatever's inside of its object, so it cannot function as a validation path. (If that's the case, it would be nice to fix the docs to say that **all** validators, and not just `required` validators, will not be run -- happy to submit a PR for this if correct.) This seems to leave no way to validate a Mixed type however, aside from putting the validator on `B.a` and having the validation function validate the array instead of its members (currently bugged, #4440). If this won't/can't be fixed, it would also be good to state this limitation in the docs. It seems like it should be possible to make this work, however.

**Comment by vkarpov15** [comment]
Should be possible, will take a look for the next release after tomorrow's release, thanks for the detailed test case.
