### ISSUE TITLE
Can i set the global runvalidators

### ISSUE THREAD

**Issue by KID-WuMeng** [Automattic/mongoose#4442]
My all updates need to validate by schema, what the way to set global runvalidators = true ?

**Comment by vkarpov15** [comment]
Define a global plugin that creates a pre 'update' hook. You would also need to define a hook for `findOneAndUpdate()` if you use that.

```javascript
mongoose.plugin(function(schema) {
  schema.pre('update', function(next) {
    this.update({}, {}, { runValidators: true });
  });
});
```

**Comment by KID-WuMeng** [comment]
Thank you !
