### ISSUE TITLE
Typo in Getting Started section

### ISSUE THREAD

**Issue by rokit** [Automattic/mongoose#4448]
http://mongoosejs.com/docs/index.html

The last line of example code is this:

`Kitten.find({ name: /^Fluff/ }, callback);`

But the F in `Fluff` should be lowercase or you get an empty array.

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/30c78cbace87d569e953a1604edda837640e1c5b
