### ISSUE TITLE
[docs] schemaTypes options documentation

### ISSUE THREAD

**Issue by xiaofan2406** [Automattic/mongoose#4452]
The old documentation: http://mongoosejs.com/docs/2.7.x/docs/schematypes.html has documented many more options for schemaTypes definition, such as, `unique`, `sparse`.

(I went through a lot of trouble defining my  custom validator only later to find out `unique` solves it.)

Can these be transferred to the latest docs as well?

**Comment by vkarpov15** [comment]
Yeah for sure, thanks for the suggestion
