### ISSUE TITLE
4.5.10 Embedded array with dates BREAKING CHANGE

### ISSUE THREAD

**Issue by tommarien** [Automattic/mongoose#4453]
When upgrading from 4.5.9 to 4.5.10 we now get a 

Stack:  ValidationError: [OBJECTNAME] validation failed
        at MongooseError.ValidationError

When a subdocument has an undefined date

**Comment by vkarpov15** [comment]
@tommarien can you provide a code sample including schemas please?

**Comment by tommarien** [comment]
@vkarpov15 I tried reproducing the issue we had but i guess i have different data now. The issue that we got ended up in a 1970 date before 4.5.10. But with 4.5.10 it ended in a validation issue. You can close this issue if you want i'll reopen one when i got a reproduction case ready ;)

**Comment by vkarpov15** [comment]
Please do, let me know if you manage to repro :+1:
