### ISSUE TITLE
Can not register query-events after mongoose.model(schema)

### ISSUE THREAD

**Issue by Root-Core** [Automattic/mongoose#4454]
Hello,

I have a model of a schema, which gets exported as a module.
As I want to watch actions on the schema, I register some events.

If I register post('save'), the event gets triggered.
If I register post('findOneAndRemove'), the event does not get triggered.

Example-Model ('cat.model'):
```
var mongoose = require('mongoose');

var catSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

module.exports = mongoose.model('Cat', catSchema);
```

Example-Script:
```
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var catModel = require('./cat.model');

//###################################

catModel.schema.post('save', (doc) => {
  console.log('SAVE: ' + doc.name);
});

catModel.schema.post('findOneAndUpdate', (doc) => {
  console.log('UPDATE: ' + doc.name);
});

catModel.schema.post('findOneAndRemove', (doc) => {
  console.log('REMOVE: ' + doc.name);
});

//###################################

catModel.create({ name: 'Zildjian' }, function (err, cat) {
  if (err) {
    console.log(err);
  } else {
    console.log(cat.name + ': meow');

    catModel.findByIdAndUpdate(cat._id, { name: 'Zohan' },
    function(err, sec) {
      console.log(sec);
    });

    catModel.findByIdAndRemove(cat._id).exec();
  }
});
```

Console-Output:
```
SAVE: Zildjian
Zildjian: meow
{ _id: 57bdb8a82ed3d91d0e769002, name: 'Zildjian', __v: 0 }
```

It was expected to trigger the registered events, but it doesn't.
If I put everything in one file and register the events before I call mongoose.model(schema), it works like a charm.

Sorry, that this issue is kind of 'long', but I hope the provided code helps.

Regards, Root-Core

**Comment by Root-Core** [comment]
As I want to push this issue, but not to spam, I decided to provide an working version of this script.

Example-Script:
```
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

var catSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

//###################################

catSchema.post('save', (doc) => {
  console.log('CREATE: ' + doc.name);
});

catSchema.post('findOneAndUpdate', (doc) => {
  console.log('UPDATE: ' + doc.name);
});

catSchema.post('findOneAndRemove', (doc) => {
  console.log('REMOVE: ' + doc.name);
});

var catModel = mongoose.model('Cat', catSchema);

//###################################

catModel.create({ name: 'Zildjian' }, function (err, cat) {
  if (err) {
    console.log(err);
  } else {
    console.log(cat.name + ': meow');

    catModel.findByIdAndUpdate(cat._id, { name: 'zohan' },
    function(err, sec) {
      if (err) {
        console.log(err);
      } else {
        console.log(sec);
      }
    });

    catModel.findByIdAndRemove(cat._id, () => {});
  }
});
```
Console-Output:
```
SAVE: Zildjian
Zildjian: meow
UPDATE: Zildjian
{ _id: 57da8f59d8078ec3371c2492, name: 'Zildjian', __v: 0 }
REMOVE: zohan
```

**Comment by vkarpov15** [comment]
Modifying a models schema after compiling the model (like by calling `mongoose.model`) is not supported. I recommend you export the schema, not the model

**Comment by Root-Core** [comment]
@vkarpov15 I just wondered, why it would work with non query events like "save", but not for query ones like "findOneAndUpdate". Shouldn't model.schema point to the original schema object?
To me, it just seems to be an unwanted behavior.

So I do have to compile the model on every use?
If I don't, it would not work either as there might be timing problems..

For example:

1. File2 is initialized
2. File1 is initialized
3. File1 registers events
4. File2 accesses the database

File1 and File2 both access the exported schema, but the event does not get triggered.
If I compile the model before modifying data in File2, it works. I just wonder, if this has a noticeable performance impact?

Thanks for your answer!
Regards, Root-Core.

**Comment by vkarpov15** [comment]
Re: first paragraph, if it works then it's by accident.

What do you mean by "compile the model on every use"?

**Comment by Root-Core** [comment]
@vkarpov15, for example: If I want to write data to the MongoDB under usage of an model, I have to compile the exported schema every time, to ensure that the events get fired, as I can not store the compiled model objects in my classes.
If I would do that, the stored model objects would not fire events, that were registered later (after compiling) to the same schema.

I hope this is understandable, as I find it hard to explain time based problems.. sorry!

**Comment by vkarpov15** [comment]
I don't quite see why you have to compile the schema every time. Ideally you just register hooks and then compile the model. Is there a reason why you can't do this?

**Comment by Root-Core** [comment]
I am using Typescript and there I have implemented multiple classes, which import the same schema / model to access the database with it. They will register events if necessary.
I want to catch events in all classes, not only the one that registered the events. I actually can't know, if all classes have registered their events to compile it only once and can't export the schema, as every class would compile an 'older' version than the next class, that uses the schema and might register some events.
