### ISSUE TITLE
Default on array of SubDocuments throws error

### ISSUE THREAD

**Issue by bharley** [Automattic/mongoose#4456]
I have a document that's defined roughly like

``` js
const AddressSchema = new mongoose.Schema({
  _id: false,
  id: false,
  address1: String,
  address2: String,
  city: String,
  state: String,
  postal: String,
  country: String,
  latitude: Number,
  longitude: Number
});

const SocialMediaSchema = new mongoose.Schema({
  _id: false,
  id: false,
  provider: String,
  link: String,
  enabled: Boolean
});

const schema = new mongoose.Schema({
  name: String,
  identifier: {type: String, index: true, unique: true},
  address: AddressSchema,
  socialMedia: {
    type: [SocialMediaSchema],
    default: [
      {
        provider: 'Facebook',
        enabled: true,
        link: 'https://www.facebook.com'
      },
      {
        provider: 'Google+',
        enabled: true,
        link: 'https://www.google.com'
      },
      {
        provider: 'Twitter',
        enabled: true,
        link: 'https://www.twitter.com'
      },
    ]
  },
  headerLogo: String,
  hostnames: [String]
});

const Site = mongoose.model('Site', schema);
```

When I try to `update` with the `upsert` and `setDefaultsOnInsert` options enabled, I get the following error:

```
TypeError: Cannot read property '$__' of null
    at DocumentArray.cast (/project/node_modules/mongoose/lib/schema/documentarray.js:232:53)
    at DocumentArray.SchemaType.getDefault (/project/node_modules/mongoose/lib/schematype.js:587:23)
    at /project/node_modules/mongoose/lib/services/setDefaultsOnInsert.js:99:32
    at Schema.eachPath (/project/node_modules/mongoose/lib/schema.js:651:5)
    at module.exports (/project/node_modules/mongoose/lib/services/setDefaultsOnInsert.js:76:14)
    at Query.update (/project/node_modules/mongoose/lib/query.js:2173:15)
    at Function.update (/project/node_modules/mongoose/lib/model.js:2059:13)
    at _callee$ (index.js:38:38)
```

However, if I add the new model through `Site.create(...)`, I get no errors and the defaults I expected.

**Comment by vkarpov15** [comment]
Which version of mongoose are you using? There was a similar issue we fixed in 4.5.10

**Comment by bharley** [comment]
I probably should have noted the first thing I tried doing was upgrading to 4.5.10 (I'm currently on 4.5.9), but I get a `RangeError: Maximum call stack size exceeded` detailed in this issue: #4466. So I can't confirm if 4.5.10 fixes the issue.

**Comment by vkarpov15** [comment]
Ah so that answers my question about which version you're using, is this the same code sample that triggers the issue you described in #4466?

**Comment by vkarpov15** [comment]
Code seems to work in 4.6.2, gonna close this, possibly related to #4540. Re-open if still an issue.

**Comment by bbuckley123** [comment]
I ran into this issue today, and I believe I have the code path that shows where `null` is being passed in. Referencing the 4.6.2 tag, Start here:
https://github.com/Automattic/mongoose/blob/4.6.2/lib/services/setDefaultsOnInsert.js#L99
`schemaType.getDefault` is being passed `(null, true)`

It is then casted here:
https://github.com/Automattic/mongoose/blob/master/lib/schematype.js#L587
Note `this.cast` is being passed `(myDefaultValue, null, true)`.

My particular schema type is documentArray. It's cast definition starts here:
https://github.com/Automattic/mongoose/blob/4.6.2/lib/schema/documentarray.js#L195

The signature of the function is `(value, doc, init, prev, options)`. Unfortunately, the arguments passed in would be `(myDefaultValue, null, true)`. Important to note here that the second argument should be a `doc`, but it was assigned `null`.

Go down a few lines to here:
https://github.com/Automattic/mongoose/blob/4.6.2/lib/schema/documentarray.js#L236

And boom. Death by Null™. 

I hope this helps!

**Comment by vkarpov15** [comment]
Thanks, will take a closer look when I get a chance
