### ISSUE TITLE
single embedded subdoc instanciation after main object one

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#4458]
Hi,

What is the best way to instanciate a single embedded subdoc when the default value is set to null

    var mongoose = require('mongoose');
    
    var childSchema = new mongoose.Schema({ name: 'string' });
    
    var parentSchema = new mongoose.Schema({
      child: {type: childSchema, default: null}
    });
    
    var Parent = mongoose.model('Parent', parentSchema);
    var parent = new Parent();
    
    // how to instanciate the child here?
    
    parent.child.name = 'Leia'; 
    
    console.log(parent)

**Comment by vkarpov15** [comment]
`parent.child = { name: 'Leia' }`

**Comment by jbdemonte** [comment]
Easy... 
Thanks a lot :)
