### ISSUE TITLE
Public Dashboard for Mocha Test Result

### ISSUE THREAD

**Issue by Nishchit14** [Automattic/mongoose#4462]
I am the creator of vigoreport.io, and fan of mongoose. (I have used it in vigoreport :D)

Here I have created a public dashboard of mongoose test output
https://vigoreport.io/p/MUO9eVz 
[![vigoreport](https://vigoreport.io/p/badge/MUO9eVz)](https://vigoreport.io/p/MUO9eVz)

@vkarpov15 please review this, If you find that it will be helpful then ping me, i will transfer ownership. 

Suggestions and feedback are welcome :smiley:

**Comment by vkarpov15** [comment]
Thanks! Is this just a status badge to put on the github repo? If so, sure, I'd be happy to put it up.

**Comment by Nishchit14** [comment]
Yes, but you need a small setup in mocha.opts. 
So on every Travis-CI build badge will changed according to tests result.
I will create a PR, You can merge by checking it. May i ?

**Comment by vkarpov15** [comment]
Sure please do :)
