### ISSUE TITLE
Query 'lean' option doesn't produce POJOs

### ISSUE THREAD

**Issue by sabrehagen** [Automattic/mongoose#4463]
The [Query docs](http://mongoosejs.com/docs/api.html#query_Query-lean) state that when using `lean` "documents returned from queries with the lean option enabled are plain javascript objects, not MongooseDocuments.". However, the fact that the `_id` key of the document is an `object`, not a `string` contradicts this indicated POJO nature. Surely the `_id` key should be a string when converting to a plain javascript object.

Currently, checking equality requires a `toString` call on any `_id`s, for example when an `_id` has been supplied by http request and needs to be compared to an `_id` of a `lean` query result.

Is there a way to ensure `_id` is a `string`, not an `object`?

```
const Promise = require('bluebird');
const mongoose = require('mongoose')

mongoose.Promise = Promise;
mongoose.connect('mongodb://localhost/test');

const personSchema = mongoose.Schema({ name : String });

const Person = mongoose.model('Person', personSchema);

const p = new Person({ name : 'Turing' });

return p.save().then(() => {
  Person.findOne({ name : 'Turing' }).then((doc) => {
    console.log('non-lean _id type', typeof doc._id, doc._id)
  });

  Person.findOne({ name : 'Turing' }).lean(true).then((doc) => {
    console.log('    lean _id type', typeof doc._id, doc._id)
  });
});
```
Produces output:
```
non-lean _id type object 57c38e4a01456bbc213b7ff2
    lean _id type object 57c38e4a01456bbc213b7ff2
```

**Comment by vkarpov15** [comment]
There's been some discussion about this before, can't quite remember the issue. The point is that `ObjectId` is not a mongoose construct, but a fundamental mongodb construct. The point of `lean()` is to bypass all of mongoose's heavy change tracking and get the same result that you would get from running the query using the mongodb driver directly. Converting ObjectIds to their hex string representation would break that, so I guess this would require documentation changes more than anything else.

What's your use case for wanting `_id` as a string? `JSON.stringify()` should convert it to a string for you just fine.

**Comment by sabrehagen** [comment]
My use case is comparing objectIds. Having to compare `user1._id.toString() === user2._id.toString()` is not ideal at all. I don't want to use the `_id.equals` function as I don't want my codebase outside my mongoose wrapper being aware of mongoose.

**Comment by vkarpov15** [comment]
Hmm perhaps #3366 would be a way to fix this for you? General idea is to add a `withVirtuals` option to `.lean()`, so your lean docs would include an `id` field that contains the object id as a hex string, so you could do `user1.id === user2.id`.

**Comment by sabrehagen** [comment]
Thanks, but the full codebase references _id. Will close this as there doesn't seem to be a non-hacky solution. Thanks for your time and though Val.

**Comment by vkarpov15** [comment]
Yeah. In my code I always just use `toHexString()`, this checks the ids for equality and ensures that both are probably mongodb objectids unless you happen to get another object with such a function.
