### ISSUE TITLE
How to reach ValidationError class

### ISSUE THREAD

**Issue by AttilaSATAN** [Automattic/mongoose#4464]
I've created a centeralized error handling class which handles the ValidationError instances  and translates those to a human friendly error string and response code (400, 401, 409 exc...) . 

I want to use ValidationError class in `pre('validate')` and use its instances as done callback argument but I couldn't find the class in API docs nor could not see in the public API when I use inspect on mongoose object. 

Before deep dive to the source code I just wanted to ask that did I miss something or is this class fully private or renamed before publicated to API?

**Comment by vkarpov15** [comment]
`require('mongoose').Error.ValidationError` should work
