### ISSUE TITLE
Using arrays as Set objects

### ISSUE THREAD

**Issue by dorshemer** [Automattic/mongoose#4467]
I have the following schema:

`var library = new mongoose.Schema({
    books: {type: [String]}
})`

I want to test if a book is in the library, and I want to do it the most efficient way possible. Iterating over the books isn't a good idea, and I would normally use Set.has(), but I can't convert library.books to Set because it's not an array of strings.

I also don't want to use getters and setters:
`var library = new mongoose.Schema({
    books: { type: [String], get: books => new Set(books), set: Array.from }
})`

because this way each call to library.books creates a new set, which beats the purpose.

Is there a mongoose solution to this?

Thanks

**Comment by vkarpov15** [comment]
The most efficient way would be to query mongodb for that `Library.findOne({ _id: library._id, books: bookToFind })` if you have an index on `books`. If your `books` array is huge, you'd probably be better off having a separate mongodb collection for books and have each `book` point to its parent library.
