### ISSUE TITLE
Custom ObjectIds - How to?

### ISSUE THREAD

**Issue by stphnthiel** [Automattic/mongoose#447]
Hi all,
this is more a question than an issue (mongoose newbie) but could someone point me to an example of how to use custom ObectIds with mongoose?
whenever I properly define, i.e. _id: mongoose.Schema.ObjectId in a schema and then try to create the ObjectId with a custom key, i.e. myModel._id = new ObjectId('unique'), I get an invalid ObjectId error. 

Using Strings as _id and automatic ObjectIds generated by mongoose works well, but I really need custom (and unique) keys for the ObjectIds within my models and want to use the DBRef plugin to make proper references in mongodb between collections.

Any hints?
Thanks in advance for your help!

**Comment by aliabdzad** [comment]
i want to have a custom _id and i define it in schema . but when i use "findOneAndUpdate" and set "upsert" and "setDefaultsOnInsert" true for it ,in creating my document my custom _id is skipped and default ObjectId set for it

**Comment by amrdraz** [comment]
@aliabdzad what did you do about that issue
did setting something like
`new Schema({ _id: { type: String, default: _ => uuid() } })`
work
