### ISSUE TITLE
Error on findOneAndUpdate if new value has type Array of Arrays

### ISSUE THREAD

**Issue by fedotov** [Automattic/mongoose#4470]
I have scema with 'Array of Arrays' field type like

```
let schema = new mongoose.Schema({
    name: String,
    fieldArray: [[Number]]
}, { strict: true, versionKey: false });
```

Creating new document works fine for this

```
let doc = { name: "asdf", fieldArray: [[12, 654, 8], [-54, -45]]};
new model(doc).save()
```

But findOneAndUpdate throws error

> TypeError: Cannot read property 'castForQuery' of undefined at SchemaArray.castForQuery
> (\node_modules\mongoose\lib\schema\array.js:208:37)
>     at Query._castUpdateVal (\node_modules\mongoose\lib\query.js:2575:17)
>     at Query._walkUpdatePath (\node_modules\mongoose\lib\query.js:2519:25)
>     at Query._castUpdate (\node_modules\mongoose\lib\query.js:2391:23)
>     at castDoc (\node_modules\mongoose\lib\query.js:2598:18)
>     at Query._findAndModify (\node_modules\mongoose\lib\query.js:1825:17)
>     at Query._findOneAndUpdate (\node_modules\mongoose\lib\query.js:1692:8)
>     at \node_modules\kareem\index.js:239:8
>     at \node_modules\kareem\index.js:18:7
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

Full code to reproduce error
```
'use strict';
var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');

let schema = new mongoose.Schema({
    name: String,
    fieldArray: [[Number]]
}, { strict: true, versionKey: false });

let model = mongoose.model('TestArray', schema);

mongoose.connect('mongodb://localhost/TestArray');

let doc = { name: 'asdf', fieldArray: [[12, 654, 8], [-54, -45]]};
let newDoc = { fieldArray: [[34], [-54], [0, 12]]};

new model(doc).save()
    .then(() => model.findOneAndUpdate({name: doc.name}, newDoc, {new: true}))
    .then(doc => console.log(doc.toObject()))
    .catch(err => console.warn(err))
    .finally(() => mongoose.connection.close());
```

I've looked to [ node_modules\mongoose\lib\schema\array.js:208](https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L208) and found

```
SchemaArray.prototype.castForQuery = function($conditional, value) {
  var handler,
      val;

  if (arguments.length === 2) {
    handler = this.$conditionalHandlers[$conditional];

    if (!handler) {
      throw new Error('Can\'t use ' + $conditional + ' with Array.');
    }

    val = handler.call(this, value);
  } else {
    val = $conditional;
    var proto = this.casterConstructor.prototype;
    var method = proto.castForQuery || proto.cast;   // here is the error. Because of proto equals to undefined

    if (Array.isArray(val)) {
      val = val.map(function(v) {
        if (utils.isObject(v) && v.$elemMatch) {
          return v;
        }
        if (method) {
          v = method.call(caster, v);
        }
        return isMongooseObject(v) ?
            v.toObject({virtuals: false}) :
            v;
      });
    } else if (method) {
      val = method.call(caster, val);
    }
  }

  return val && isMongooseObject(val) ?
      val.toObject({virtuals: false}) :
      val;
};
```
As I can see if line 208 change to
`var method = proto && (proto.castForQuery || proto.cast);`
the logic will not be broken. After the fix findOneAndUpdate works fine for above example.

May be the fix should be included to mongoose repo?

**Comment by vkarpov15** [comment]
If you have a fix, please put in a PR and I'll be happy to merge as long as it doesn't break any existing tests :+1:

**Comment by fedotov** [comment]
[PR is here](https://github.com/Automattic/mongoose/pull/4484)

**Comment by vkarpov15** [comment]
Thanks :beers:

**Comment by lopezjo** [comment]
+1

I ran into this issue as well and confirmed the fix locally. Thank you! Looking forward to next release.

**Comment by egiray** [comment]
Is this still bugged?

**Comment by vkarpov15** [comment]
@egiray I don't believe so. Please provide code samples if you're experiencing a similar issue

**Comment by egiray** [comment]
I saw this same error yesterday. But then I found out the schema I wrote was incorrect. But it's still a little bit weird that I got this error type on that occasion.
