### ISSUE TITLE
Setting vs Pushing to an array

### ISSUE THREAD

**Issue by varunjayaraman** [Automattic/mongoose#4472]
I've been experiencing some trouble with a function that mutates a mongoose doc (you may remember it @vkarpov15 as `applyDelta`) and the root of the issue seems to be that mongoose treats lodash's `_.set` for an array differently from `.push` or its own `document#set`. If you have an array of objects in mongoose, mongoose inserts them as documents with `.push`, but if you `_.set` an element through an index, it inserts it as a POJO. This was causing issues for me when I tried to run `document#save` because it would claim that `doc.toObject` was not a function on line 181 in `mongoose/lib/types/documentarray.js` in `mongoose 4.5.2` (it's within 1 or 2 lines in `mongoose 4.5.10`). This error wouldn't occur if I ran `Model#findByIdAndUpdate`.

Here's a repo for you to reproduce the error: `https://github.com/varunjayaraman/mongoose-set-bug`

 I'm not sure if this is intended functionality or a bug. It also just might be something you have no control over since it's specifically an issue relating to lodash. If it's intended, is the recommended alternative to use `document#set`? I'd like to be able to use this function on both POJOS and mongoose documents, so my current workaround is to see if the object has a `document#set` function and use that, otherwise use `_.set`.

**Comment by varunjayaraman** [comment]
I noticed another bug with `document#set`. If you try to set at an array index, it will set it as an array (so now you'll have a nested array).

I've updated the repro so that the first npm command outlined in the README illustrates my previous bug and the second npm command illustrates this bug in this followup.

https://github.com/varunjayaraman/mongoose-set-bug/tree/master

**Comment by vkarpov15** [comment]
Oh boy questionable design decisions coming back to bite me :) TBH if it were up to me I'd scrap that entire applyDelta function and redesign the whole schema. I'll check this today/tomorrow but you'd probably be better off using `document.set()`, can't remember why we started using `_.set()` instead but hopefully the tests would catch any issues that arise.

**Comment by vkarpov15** [comment]
Yeah the `docarray-bug` issue is not something we can fix until we start using proxies, it's the same thing that happens if you do `essay.attachments.notes[0] = { subject: 'Subject 2', description: 'Description 2'};`, because we don't explicitly watch for setting array indexes. This is something that needs to happen for 5.0 but not happening for the immediate future.

The 2nd issue, the `set-array-bug`, should be fixed in the next release.

**Comment by varunjayaraman** [comment]
Cool, thanks for taking a look val
