### ISSUE TITLE
v4.5.8 - Incorrect return value for `document.save` method when using callbacks (Array instead of Object)

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#4473]
For instance, I have a document called `user`, which is a Mongoose object.

I run on it `user.save(fn);` where `fn` is a callback function.  The returned value to `fn` if successful looks like `[ { User Object}, 1]` (an Array).  However if I run `user.save(function(err, user) { fn(err, user); });` it works fine and the returned value to `fn` is `{ User Object}` (an Object).

Version 4.5.8

cc @vkarpov15

**Comment by vkarpov15** [comment]
I'm really confused, can you provide some sample code please?
