### ISSUE TITLE
differemces of validation error object format for castError while update 

### ISSUE THREAD

**Issue by kyungeunni** [Automattic/mongoose#4478]
I'm using mongoose validator and find out it throw me different format ot error object in the case of 'castError' while update, not save/create function. 
The common format I get is:

```
 { [ValidationError:  validation failed]
  message: 'adminaccounts validation failed',
  name: 'ValidationError',
  errors: 
   { level: 
      { [CastError: Cast to Number failed for value "one" at path "level"]
        message: 'Cast to Number failed for value "one" at path "level"',
        name: 'CastError',
        kind: 'Number',
        value: 'one',
        path: 'level',
        reason: [Object] } } }
```

but the one I got when I did update with the same situation is : 

```
{ [CastError: Cast to Number failed for value "one" at path "level"]
  message: 'Cast to Number failed for value "one" at path "level"',
  name: 'CastError',
  kind: 'Number',
  value: 'one',
  path: 'level',
  reason: 
   { [CastError: Cast to number failed for value "one" at path "level"]
     message: 'Cast to number failed for value "one" at path "level"',
     name: 'CastError',
     kind: 'number',
     value: 'one',
     path: 'level',
     reason: undefined } }
```

I thought maybe it was different error format between document validator and update validator, but  it wasn't after testing many cases. the other validation error throwed me the general format of error object while I updated. 

it's not a big deal to handle this differences but I wanted to check that it is the way you meant or mistake.

many thanks.

**Comment by vkarpov15** [comment]
It's an unfortunate limitation of how `update()` works right now. `save()` will look through the entire document and find all the cast and validator errors (see the `errors` property in your first code example) but `update()` will look through the document until it finds a cast error and then throw that. Something we'll improve in a future release but not going to happen in the immediate future.

**Comment by kyungeunni** [comment]
Now it's totally clear for me why it happened like that. thanks a lot!
