### ISSUE TITLE
Unhandled Reject Write Error on compound unique index duplicate.

### ISSUE THREAD

**Issue by r3wt** [Automattic/mongoose#4482]
**Expected behavior:**

exception is caught and provided to callback as `err` parameter.

**Actual behavior:**

exception is not caught, result in stack unwind and app explodes needlessly.

**model:**
```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var Types = Schema.Types;

var CheckinsSchema = new Schema({
	user: {
		type: Types.ObjectId, ref: 'User', index: true //invited user
	},
	event: {
		type: Types.ObjectId, ref: 'Event', index: true
	},
	tenant: { 
		type: Types.ObjectId, ref: 'Tenant', index: true 
	},
	checkInTime: { 
		type: Types.Date, default: null 
	}
});

CheckinsSchema.index({ user: 1, event: 1, tenant: 1}, { unique: true });

module.exports = Checkins = mongoose.model('Checkins', CheckinsSchema);
```
**request handler:**
```js
function checkIn(req,res){
	var id = req.params.id;
	
	var m = new model.Checkins({
		event: id,
		user: req.user.id,
		tenant: req.tenant,
		checkInTime: new Date(Date.now()) 
	});
	
	m.save(function(err,insert){
		
		if(err) return res.error('already checked in');
		res.apiResponse('ok');
		
	});	
}
```

**Comment by vkarpov15** [comment]
What version of mongoose? Also, what is the error you get?

**Comment by r3wt** [comment]
Sneaking to close issue, such dishonor.

**Comment by vkarpov15** [comment]
No response for a while and original post included no useful information, too many other more pressing and more well defined issues to play guessing games

**Comment by r3wt** [comment]
@vkarpov15 Ok:

1. mongod version:
```
db version v3.2.8
git version: ed70e33130c977bda0024c125b56d159573dbaf0
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1404
    distarch: x86_64
    target_arch: x86_64
```
2. mongoose version
```
npm list mongoose
└── mongoose@4.5.5
```
3. additional info
- using bluebird for promises.
4. mongoose setup as so:
```
var mongoose = require('mongoose');

mongoose.Promise = require('bluebird');

mongoose.connect(config.mongo_url,config.mongo_options);

mongoose.connection.on('connected', function (ref) {
	log.info('mongoose: connected');
	
	//require mongoose types.
	var mongooseTypes = require("mongoose-types");
	mongooseTypes.loadTypes(mongoose);

	//import models
	global.model = model = require('./models');
	
	//should move to backend process later
	require('./backend')(model);	

});
```

**Comment by vkarpov15** [comment]
Yeah I still don't get what the actual issue is here, below script gives me the expected output:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4482');
mongoose.set('debug', true);
var Types = mongoose.Schema.Types;
var CheckinsSchema = new Schema({
    user: {
        type: Types.ObjectId, ref: 'User', index: true //invited user
    },
    event: {
        type: Types.ObjectId, ref: 'Event', index: true
    },
    tenant: { 
        type: Types.ObjectId, ref: 'Tenant', index: true 
    },
    checkInTime: { 
        type: Types.Date, default: null 
    }
});

CheckinsSchema.index({ user: 1, event: 1, tenant: 1}, { unique: true });
var M = mongoose.model('CheckIn', CheckinsSchema);
M.on('index', function(error) {
  console.log('error', error);
  var m = M({
        event: '000000000000000000000000',
        user: '000000000000000000000000',
        tenant: '000000000000000000000000',
        checkInTime: new Date(Date.now()) 
    });

    m.save(function(err,insert){
      console.log('done', err);
      process.exit(0);
    });
});
```

Output:

```
$ node gh-4482.js 
Mongoose: checkins.ensureIndex({ user: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ event: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ tenant: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ user: 1, event: 1, tenant: 1 }, { unique: true, background: true })
error undefined
(node:32725) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: checkins.insert({ event: ObjectId("000000000000000000000000"), user: ObjectId("000000000000000000000000"), tenant: ObjectId("000000000000000000000000"), _id: ObjectId("57edddc53ad3f67fd52987d9"), checkInTime: new Date("Fri, 30 Sep 2016 03:36:37 GMT"), __v: 0 })
done null
```

Potential issue is that by using `index: true` and then using `.index()` at the end you're actually creating 4 separate indexes, 3 that aren't unique indexes. If you're expecting the last `.index()` call to mean that each of `user`, `event`, and `tenant` are unique you'll be disappointed, the last one means that the combination of `user`, `event`, and `tenant` is unique.

**Comment by r3wt** [comment]
It happens on a duplicate

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 29, 2016 at 10:40 PM -0500, "Valeri Karpov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah I still don't get what the actual issue is here, below script gives me the expected output:

'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4482');
mongoose.set('debug', true);
var Types = mongoose.Schema.Types;
var CheckinsSchema = new Schema({
    user: {
        type: Types.ObjectId, ref: 'User', index: true //invited user
    },
    event: {
        type: Types.ObjectId, ref: 'Event', index: true
    },
    tenant: {
        type: Types.ObjectId, ref: 'Tenant', index: true
    },
    checkInTime: {
        type: Types.Date, default: null
    }
});

CheckinsSchema.index({ user: 1, event: 1, tenant: 1}, { unique: true });
var M = mongoose.model('CheckIn', CheckinsSchema);
M.on('index', function(error) {
  console.log('error', error);
  var m = M({
        event: '000000000000000000000000',
        user: '000000000000000000000000',
        tenant: '000000000000000000000000',
        checkInTime: new Date(Date.now())
    });

    m.save(function(err,insert){
      console.log('done', err);
      process.exit(0);
    });
});

Output:

$ node gh-4482.js
Mongoose: checkins.ensureIndex({ user: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ event: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ tenant: 1 }, { background: true })
Mongoose: checkins.ensureIndex({ user: 1, event: 1, tenant: 1 }, { unique: true, background: true })
error undefined
(node:32725) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: checkins.insert({ event: ObjectId("000000000000000000000000"), user: ObjectId("000000000000000000000000"), tenant: ObjectId("000000000000000000000000"), _id: ObjectId("57edddc53ad3f67fd52987d9"), checkInTime: new Date("Fri, 30 Sep 2016 03:36:37 GMT"), __v: 0 })
done null


Potential issue is that by using index: true and then using .index() at the end you're actually creating 4 separate indexes, 3 that aren't unique indexes. If you're expecting the last .index() call to mean that each of user, event, and tenant are unique you'll be disappointed, the last one means that the combination of user, event, and tenant is unique.

-

**Comment by r3wt** [comment]
And yes, the combination unique index is important. Other indexes are for lookups.

**Comment by vkarpov15** [comment]
Umm can you clarify what you mean by duplicate and show me the code that actually writes to mongodb?
