### ISSUE TITLE
Mongos: true doesn't trigger "error"-function if databases are down.

### ISSUE THREAD

**Issue by yvanavermaet** [Automattic/mongoose#4483]
Hi

When you specify 2 mongo databases and pass along "mongos: true", then the error-function won't be called if both databases are down.

Mongoose: 4.5.10
MongoDB: 3.2

	var mongoose = require('mongoose');

	module.exports = (function() {
		var servers = ['localhost:27017', '127.0.0.1:27017'],
			connectionStr = 'mongodb://' + servers.join(',') + '/apm?authSource=admin',
			options;

		options = {
			'mongos': servers.length > 1,
			'server': {
				'auto_reconnect': true
			}
		};

		mongoose.connect(connectionStr, options);

		mongoose.connection.on('error', function() {
			console.log('Could not connect to mongodb. Stopping the server.');
		});

		mongoose.connection.on('open', function() {
			console.info('Connected to ' + connectionStr);

			mongoose.connection.on('disconnected', function() {
				console.log('Lost connection to mongodb.');
			});

			mongoose.connection.on('reconnected', function() {
				console.log('Reconnected to mongodb.');
			});
		});

		return mongoose;
	}());

If the databases are down, the error-function won't be called. If you remove the mongos-option, then the error-function will be called as expected.

Is this a bug with Mongoose or is there something wrong with my implementation?

Thanks in advance.

Kind regards,
Yannick

**Comment by vkarpov15** [comment]
If you don't specify mongos, mongoose will treat it as a replica set connection, which is not what you want. Do you get any errors if both mongos are disconnected?

**Comment by yvanavermaet** [comment]
Instead of typing this entire issue, I should have just waited and looked at my console... It seems that it takes a certain time for the error-function to be called.

Sorry to have bothered you and thanks for your reply!
