### ISSUE TITLE
Reliable way to access original object passed to mongoose schema

### ISSUE THREAD

**Issue by amirmohsen** [Automattic/mongoose#4486]
I'm working on a react library that accepts mongoose schemas. I'm wondering whether there's an api for accessing the original object that gets passed to the Schema class in mongoose. I managed to find the ```tree``` property on the schema object. While it does have the properties from the original object, it also has two extra properties: ```id``` and ```_id```. I'm not sure if the ```tree``` property is meant only for internal purposes or not.

So is there a reliable way to get the original object from a mongoose schema? This would be very useful for external libraries like mine.

**Comment by vkarpov15** [comment]
Unfortunately not at the moment, the tree and paths properties are the closest thing. Will add it for next release though, I've often wanted this feature myself

**Comment by amirmohsen** [comment]
Thank you. Good to know that it's on your radar.
