### ISSUE TITLE
TypeError: virtual.get is not a function

### ISSUE THREAD

**Issue by xuhong** [Automattic/mongoose#4488]
I've searched a lot, but still can't found the problem, code is dead simple below:

```
postSchema.virtual('author', {
  ref: 'User',
  localField: 'name',
  foreignField: 'author',
  justOne: true
})
```

and error message is 

> TypeError: virtual.get is not a function
>     at Schema.virtual

mongoose version is 4.6.0.

much thanks!

**Comment by zbjornson** [comment]
I'm not too familiar with the undocumented(?) options object for `virtual`, but did you define the getter anywhere?

`postSchema.virtual('author').get(function () {...})`

**Comment by xuhong** [comment]
@zbjornson Thanks for your reply! I've tried this way and get the error below

> TypeError: postSchema.virtual(...).get is not a function

 and i wrote code like this issue https://github.com/Automattic/mongoose/issues/4354 did but still doesn't work... and In fact there is documented [here](https://github.com/Automattic/mongoose/pull/4219/commits/86d9c5058d8ef3c605d6b2cde5f6f2b6134c028a)

**Comment by zbjornson** [comment]
Aha, sorry. Have you tried/are you already calling `populate('author')` first?

**Comment by vkarpov15** [comment]
Hmm @xuhong what does your `postSchema` look like?

**Comment by xuhong** [comment]
hi, @vkarpov15 , my `postSchema` is below:
```
const postSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true
  },
  author: {
    type: String,
    required: true
  },
  content: {
    type: String,
    required: true
  },
  create_at: {
    type: Date,
    default: Date.now
  },
  update_at: {
    type: Date,
    default: Date.now
  },
  meta: {
    views: {
      type: Number,
      default: 0
    },
    comments: {
      type: Number,
      default: 0
    },
    votes: {
      type: Number,
      default: 0
    }
  }
})
```

**Comment by xuhong** [comment]
I had found the problem, i had `author` property in my schema which cause the error...
