### ISSUE TITLE
Not creating `versionKey` when upserting docs

### ISSUE THREAD

**Issue by zatziky** [Automattic/mongoose#4491]
Originally, I created [a question on StackOverflow](http://stackoverflow.com/questions/39342568/versions-v-not-appearing-in-documents/39342925#39342925). Then  I realized that it maybe a bug as I hadn't found any proper options forcing `versionKey` to appear in upsert options in the [docs](http://mongoosejs.com/docs/api.html#model_Model.update). 

`versionKey` is not inserted with the document.  When doing `Model.update({},{},{upsert:true})`.

**Comment by vkarpov15** [comment]
Right now we don't support that, but will add for a future release

**Comment by vkarpov15** [comment]
Duplicate of #2122, fixed in 3.8.13
