### ISSUE TITLE
ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by paton** [Automattic/mongoose#4494]
We're getting this error after upgrading from 4.5.10 of mongoose (mongodb v2.1.18) to 4.6.0 mongoose (mongodb v2.2.9).  Running on Node 6.2.2.

Any ideas what might cause this? We've tried increasing disk space with no luck. Thanks!

`ENOSPC: no space left on device, write`
![image](https://cloud.githubusercontent.com/assets/609881/18293416/6908c12e-7447-11e6-878f-06b6d2c5d158.png)

**Comment by paton** [comment]
One thing I noticed:

v4.5.10 outputs no logs, while v4.6.0 outputs a ton of logs via console.log, so my guess is our log file ballooned and the server ran out of space.

Not too sure what would cause the extra console.log's in v4.6.0.

**Comment by paton** [comment]
The logging seems to be fixed by changing "loggerLevel" from error to debug.

Strange that older versions of mongoose / mongodb driver didn't produce any logs until upgrading to 4.6.0. If this isn't a bug, feel free to close the issue 👍 

![image](https://cloud.githubusercontent.com/assets/609881/18449766/5c2df94a-78e5-11e6-9353-9e4e3da44db3.png)

**Comment by vkarpov15** [comment]
Yeah this is internal to the mongodb driver, feel free to report an issue on the [driver's JIRA](https://jira.mongodb.org/browse/NODE/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). Most projects I've seen spit out a lot of data if you turn on debug mode, so not surprising.
