### ISSUE TITLE
Conditions are not parsed inside $not expression

### ISSUE THREAD

**Issue by jason-igaw** [Automattic/mongoose#4495]
Hi,

I'm using Mongoose.js now. While I'm developing my back-end application, I found a bug about $not expression.

If I query using a condition below, it is parsed well.
ex1) 

```
let condition = {"createdAt":{"$gte":"2016/09/02 00:00:00", "$lte":"2016/09/02 23:59:59"}};
```

mongoose log:
```
=> Mongoose: collection.find({ createdAt: { '$gte': new Date("Thu, 01 Sep 2016 15:00:00 GMT"), '$lte': new Date("Fri, 02 Sep 2016 14:59:59 GMT") } }, { fields: undefined })
```

But if I use $not expression inside this condition, date string isn't parsed.
ex2)

```
let condition = {"createdAt":{$not:{"$gte":"2016/09/02 00:00:00", "$lte":"2016/09/02 23:59:59}}}
```

mongoose log:
```
=> Mongoose: collection.find({ createdAt: { '$not': { '$gte': '2016/09/02 00:00:00', '$lte': '2016/09/02 23:59:59' } } }, { fields: undefined })
```

What should I do to fix this?

Sincerely,
Jeongsang Baek

**Comment by pjotrsavitski** [comment]
Not sure if I am correct or not, but if you pass in the Date objects, then it should work. This means that you would need to convert date string into an object yourself.

That is not a fix for that issue, still, it should start working after that. It should not be a big deal and would also work well enough once the issue is identified and fixed.

**Comment by jason-igaw** [comment]
You're right. As you mentioned, it works if I pass Date objects myself. Thing is, these two conditions should do the same thing. This issue makes ambiguity.

**Comment by pjotrsavitski** [comment]
Understood and agree.

Although, if you need to get running right before this might be addressed (unless you could fork, fix and submit a pull request to make it ship faster).
Then a meaningful solution could be to always use Date objects. This might also be safer and allow more control over what is going on, giving you full control.

I am not saying it should not be addressed.
