### ISSUE TITLE
Field '__v' gets initialized with non-numeric type NULL

### ISSUE THREAD

**Issue by BenBestmann** [Automattic/mongoose#4499]
When trying to perform a `.()save` on a document of my contact model I get the following error:

    Cannot apply $inc to a value of non-numeric type. {_id: ObjectId('57d0063348b748000369a7bd')} has the field '__v' of non-numeric type NULL

The schema looks like this:

    name: { type: String, minlength: 1, maxlength: 50, required: true },
    emails: [{
        _id: false,
        label: { type: String, minlength: 2, maxlength: 20, default: 'primary', required: true },
        email: { type: String, validate: Validators.emailValidator, required: true }
    }],
    phones: [{
        _id: false,
        label: { type: String, minlength: 2, maxlength: 20, default: 'primary', required: true },
        number: { type: String, validate: Validators.phoneValidator, required: true }
    }],
    addresses: [{
        _id: false,
        label: { type: String, minlength: 2, maxlength: 20, default: 'primary', required: true },
        address: {
            addressLine1: { type: String },
            addressLine2: { type: String },
            city: { type: String },
            region: { type: String },
            country: { type: String },
            zipCode: { type: String }
        }
    }],
    websites: [{
        _id: false,
        label: { type: String, minlength: 2, maxlength: 20, default: 'primary', required: true },
        url: { type: String, validate: Validators.urlValidator, required: true }
    }],
    socialProfiles: [{
        _id: false,
        label: { type: String, minlength: 2, maxlength: 20, required: true },
        url: { type: String, required: true }
    }],
    description: { type: String }

When I looked at the documents in the collection I noticed that all new documents get created with the `__v` property set to `null` instead of `0`. Obviously this causes the error when mongoose tries to apply $inc to increase the version. So far I get it.

**However I can't see  why mongoose does initialize the field with `null`!** Has this something to do with the way my subdocument arrays are defined? Or could it be that this model also uses the discrimination feature?

**Update:** It seems to have something to do with the mongo version. When running the save call on a 3.0.7 the problem does not occur. On newer versions, 3.2.x however it gets initialized with null as described above.

I am using mongoose version 4.6.0 by the way.

**Comment by BenBestmann** [comment]
I temporarily managed to work around the error by explicitly defining the `__v` field in the schema and set the `default: 0`. However I am wondering if this will have any unwanted side effects?

**Comment by vkarpov15** [comment]
Hmm that's strange, not sure how you're getting `__v` as null, that shouldn't happen. Below simple script works fine:

```javascript
'use strict';

Error.stackTraceLimit = Infinity;

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4493');
mongoose.set('debug', true);

const TestSchema = new Schema ({
  test: String
});

var T = mongoose.model('Test', TestSchema);
var T2 = T.discriminator('Test2', new Schema({ test2: String }));

T2.create({ test: 'test' }, function(error, x) {
  assert.ifError(error);
  console.log(x, x.__v);
  process.exit(0);
});
```

Can you provide a code sample that shows how you're creating models with that schema?
