### ISSUE TITLE
OverwriteModelError using typescript and node 6.5

### ISSUE THREAD

**Issue by ricardogomes** [Automattic/mongoose#4501]
I'm getting a strange behavior after updating to node 6.5.0.

I have a project done using typescript (not sure if it matters) that exposes a schema like this:

```
export const UserSchema = new mongoose.Schema({...});

export interface IUserModel extends IUser, mongoose.Document {...}

export const User = mongoose.model<IUserModel>('User', UserSchema);
```

And I import it like this:

`import { User } from '../users/user'`

Now on node 6.3.0 no issues, on 6.5.0 on the second time that a particular file uses that import I get this error:

`OverwriteModelError: Cannot overwrite `User` model once compiled.`

Was there anything on node 6.5.0 that could explain this, or am I doing something wrong?

mongod --version v3.2.9
mongoose 4.6.0

**Comment by vkarpov15** [comment]
Hmm I'm really not familiar with the internals of typescript. Try getting the JS output and seeing what it actually does. Your code definitely assumes that `User` is a singleton, does TS not do that?

**Comment by legarland** [comment]
@ricardogomes Did you find a solution for this?
