### ISSUE TITLE
Query methods change find vs. findOne

### ISSUE THREAD

**Issue by davidkaneda** [Automattic/mongoose#4502]
I'm a big fan of the new query methods, but have been bitten a few times on them changing a find to findOne or vice versa. I understand they simply modify the query, but in practice, it's feels very odd to have something like:

```
resourceSchema.query.inAccount = function(accountId) {
  return this.find({account: accountId});
};
```

and later, have `Resource.findOne().inAccount(accountId)` return an array—Is there a method that I should be using in these query methods that would adjust the query without the nature of find vs. findOne? Has anyone else run into this? Currently we're doing things like `Resource.findOne().inAccount(accountId).findOne()` which is obviously not ideal...

**Comment by vkarpov15** [comment]
Try using `where()`.

```javascript
resourceSchema.query.inAccount = function(accountId) {
  return this.where({account: accountId});
};
```

Then `Resource.findOne().inAccount(accountId)` should work.
