### ISSUE TITLE
Validation error when a using 'type' as a field name

### ISSUE THREAD

**Issue by turtleDev** [Automattic/mongoose#4504]
like the title says, using the key `type` in a subfield that is an array raises a `ValidationError`.
mongoose version 4.6.0
OS: Ubuntu 14.04.

here's the code that reproduces the issue

```js
'use strict';

var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test');

var db = mongoose.connection;

var peopleSchema = new mongoose.Schema({
    links: [{
        name: String,
        type: String,
        url: String
    }]
});

db.on('error', console.error.bind(console, 'connection error:'));

db.once('open', function() {
    var people = mongoose.model('people', peopleSchema)
    var data = {
        links: [{
            name: 'blah', 
            type: 'blah', 
            url:'blah://superblah'
        }]
    };
    people.create(data, function(err, doc) {
        if ( err ) {
            console.error(err)
            throw err;
        }
        console.log(success);
        db.close();
    });
});
```

I'm guessing this issue has something to do with how mongoose handles schema's and how it uses ''type' to denote the type of a top level field.

**Comment by TrejGun** [comment]
```
links: [{
        name: String,
        type: {type:String},
        url: String
    }]
```

**Comment by turtleDev** [comment]
ahh thanks. That fixes things. Is this documented somewhere?
@TrejGun

**Comment by varunjayaraman** [comment]
@turtleDev, take a look here:

http://mongoosejs.com/docs/guide.html#typeKey

Ran into this problem once upon a time :P

**Comment by vkarpov15** [comment]
Yeah this is a common source of confusion, mongoose interprets your schema as "`schema.links` is an array of strings". Common source of confusion, which is why we added the typeKey option
