### ISSUE TITLE
Mongoose doesn't save __v on upsert in update

### ISSUE THREAD

**Issue by michAtEl** [Automattic/mongoose#4505]
I'd like to insert a new document if there is no document where aField has the value aValue:

```
Model.update(
  { aField: aValue},
  {$setOnInsert: {aField: aValue, otherField: otherValue} },
  { upsert: true},
  function(err, result) { ... }
);
```
If a document is inserted, it doesn't have the field __v.
This seems to be similar to #2122

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix
