### ISSUE TITLE
At the same time to send two requests，can't set headers after they are sent

### ISSUE THREAD

**Issue by hclscut** [Automattic/mongoose#4509]
when I send two requests, express give the error can't set headers after they are sent.

Excluded other reasons，In an mongoose findOne asynchronous callback，the error exist。

when I remove the mongoose findOne asynchronous callback, the error disappear。

**Comment by vkarpov15** [comment]
Code samples please

**Comment by varunjayaraman** [comment]
@hclscut closing this as stale, please reopen if you have a code sample
