### ISSUE TITLE
How to drop collection

### ISSUE THREAD

**Issue by zatziky** [Automattic/mongoose#4511]
For testing purposes I would like to empty a capped collection. It's not possible to do so using [remove()](https://docs.mongodb.com/manual/reference/method/db.collection.remove/). 

I was trying to issue this using `MyModel.collection.<methods-from-mongodb>` or `mongoose.connection.<again-some-variations>`.

What is the correct way and is it possible in the currecnt version `4.4.20`?

**Comment by vkarpov15** [comment]
`MyModel.collection.drop()`
