### ISSUE TITLE
Data spillage in object attribute when values are set to null, but may only occur in very specific scenario

### ISSUE THREAD

**Issue by njcaruso** [Automattic/mongoose#4516]
I'm seeing data spillage when querying a document, and getting results for an object attribute in another document.  This "data spillage" is based on data in memory from a previous insert, and gets cleaned up on a restart of node.

I'm on Mongoose 4.6, and MongoDB 3.0.7, running NodeJS 6.3.0, running an ExpressJS/Restify API service.  I have verified this issue as well on other Node versions if it matters.

I have a model with a schema like this:
`
name: String,
settings: {
 type: Object,
 default: {
   color: null,
   size: null
  }
}
`

So I have a `settings` Object with default attributes set to null.  

Let's say I have two documents:

Document 1
name: Bob

note that Bob has no settings values stored in DB.  But on a query, I would get the default null returns in the settings object, which is what I want.

Later on, I do a bulk insert using collection.insert().  Let's say I insert:

Document 2
name: Steve

Then, after my insert, in the same thread after the insert, I requery the same model to retrieve the documents.  I then run some operations, which then individually .save() the records.  So
1.) Bulk insert
2.) Requery within same thread
3.) Run individual operations and perform .save()

If I run a query against Bob (the old document), expecting null results for settings, I will get instead Steve's settings.  The results are not from Mongo, but from memory.  If I restart Node, everything is fine.

I haven't yet narrowed this down, and my code has a ton of node modules, my insert is wrapped in an async waterfall, etc. so perhaps it's my code, perhaps it's a dependency, but I wanted to let you know.  I don't know if it's the sequence of bulk insert, find, then .save(), or some subset of that.

But querying after the insert constantly returns the data spilled value for any document that has null attributes in the `settings`.  But if I query Mongo directly (outside of NodeJS), there's nothing in`settings` as expected.

A quick solution is to not default to null values in an object (like settings), and just create my schema like:

`
name: String,
settings: {
 type: Object,
}
`

Then it works as expected.

If you're aware of this issue - then great.  If you're not aware, I can try and create a very simple node application to try and simulate.

**Comment by vkarpov15** [comment]
Was not aware of this issue. If you can create a repro script that would be very helpful :+1:

**Comment by njcaruso** [comment]
Good to hear - hopefully it's just something local to my environment.  I'll repro with a script and get back to you.  May take a few weeks to schedule this, but I'll definitely report back.

**Comment by vkarpov15** [comment]
Issue's gone stale, re-open if this is still an issue
