### ISSUE TITLE
Embedded fields set as null

### ISSUE THREAD

**Issue by efueyo** [Automattic/mongoose#4520]
Hello!

I just found a, what looks to me, strange behaviour when setting embedded fields in a mongoose document.
By default it gets its default structure as it is set in the Schema declaration. => **OK**
If I set the embedded field as an empty Object `{}` it sets the document as and empty Object `{}`. => **OK**
If I set the embedded field as and object with the right structure everything works as expected and subfields are properly set. => **OK**
If I set the embedded field as and object with the right structure plus some other extra fields everything works as expected: subfields are properly set and extra fields are ignored. => **OK**

If I set the embedded field as and object with **only** other keys `{ random: 'key'}` the subdocument is set to `null`, **which seems kindof unexpected to me. Why is it set to `null` instead of `{}`?** 

I created this snippet to reproduce the issue:
`npm ls mongoose => mongoose@4.6.0`
```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const CarSchema = new Schema({
  color: String,
  extra: {
    field1: {
      subField1: String,
    },
  },
});
const Car = mongoose.model('Car', CarSchema);

const car = new Car();
console.log(car.extra); // => { field1: {} }
car.extra = {};
console.log(car.extra); // => {}
car.extra = { field1: {} }; 
console.log(car.extra); // => { field1: {} }
car.extra = { non_field1: {} }; 
console.log(car.extra); // => null. boom!
car.extra = { field1: { subField1: 'hey!' } };
console.log(car.extra); // => { field1: { subField1: 'hey!' } }
car.extra = { field1: { non_subField1: 'non_hey!' } };
console.log(car.extra); // => null. boom!
car.extra = { field1: {  subField1: 'hey!', non_subField1: 'non_hey!' } };
console.log(car.extra); // => { field1: { subField1: 'hey!' } }
```

Am I missing something?

Thanks!

**Comment by vkarpov15** [comment]
Try setting the minimize schema option to false, that should fix it. If it doesn't, that's a bug
