### ISSUE TITLE
Find batch of results using cursor

### ISSUE THREAD

**Issue by maxs15** [Automattic/mongoose#4522]
Hey @vkarpov15,

I'm trying to use the cursors in order to process a batch of 1000 elements at a time.

It seems like the way to process a cursor is by using the eachAsync method (or manually using next):
````
this.model('Action')
.find({user: userId})
.cursor({batchSize: 1000})
.eachAsync((doc) => {

});
```
But the issue is that I have to process every document individually instead of having an array of 1000 elements each time.
So I was wondering if:
1/ that's a feature already implemented
2/ that's a missing feature that could be implemented
3/ that's something currently not possible using cursors (If that's the case what's the proper way to do it, a custom implementation using limit/skip ?)

Thanks for your help !

**Comment by vkarpov15** [comment]
So batchSize is for performance optimization, it tells the mongodb driver how many docs to load from the mongodb server at a time. Useful if you want to ensure the driver doesn't use too much memory. However currently cursors only support getting one document at a time. If you want to process multiple docs at a time id recommend you write a helper function that calls next on a cursor n times and gathers the results into an array for you

**Comment by maxs15** [comment]
This is what I thought, this helper isn't already implemented in mongoose.
Thanks @vkarpov15 ! 👍

**Comment by ashokduraik** [comment]
1+

**Comment by ChrisLahaye** [comment]
Came across this issue and wanted to share my solution:
```ts
export const getBatchedIterable = async function*<T>(
  cursor: { next(): Promise<T> },
  batchSize: number,
) {
  let batch: T[] = [];
  let hasNext = false;
  do {
    const item = await cursor.next();

    hasNext = !!item;
    if (hasNext) batch.push(item);

    if (batch.length === batchSize) {
      yield batch;
      batch = [];
    }
  } while (hasNext);

  if (batch.length) yield batch;
};
```

You can use it as follows:
```ts
const batchSize = 1000;
const cursor = MyModel.find({}).cursor({ batchSize });
for await (const items of getBatchedIterable<ItemType>(cursor, batchSize)) {
  // use items
}
```
