### ISSUE TITLE
Missing Multiple Field Validation Hook (Schema Validation)

### ISSUE THREAD

**Issue by pedrovagner** [Automattic/mongoose#4523]
Hi everybody. I have previous experience using other validation libraries and in all of them I have a hook to put my code where I want validate multiple fields. This hook is executed after successful validation of all individual fields. I know that is possible achieve the same using `mongoose`, but I end up executing the same field validation for each field dependency. E.g. `field2` validation depends on `field1` and `field3` depends on `field1`. Did you see? `field1` validation executed two times.

After search a lot, my only solution to avoid this was override `schema.methods.validate`, inside it call `validate` and then put my multiple field validation code. To improve this, I plan do a monkey patch on `mongoose.Document.prototype.validate`.

There is another solution for this? Please tell me.

**Comment by vkarpov15** [comment]
Any reason why you can't use pre or post validate hooks?

**Comment by pedrovagner** [comment]
First, I want validate all individual fields, then validate multiple fields. I can't put my multiple field validation code on <code>pre</code> hook, because individual fields already not validate. But I can put multiple validation code on <code>post</code> hook, because this code is called after individual fields validation. But not always I want save on database; sometimes I want just validate code. How can I ONLY validate my data in this manner? If I call <code>schema.validate()</code> only individual fields validate. Did you understand me?

**Comment by vkarpov15** [comment]
Yeah you're right, right now `post('validate')` doesn't get flow control, which prevents you from doing any real validation work in post validate. No other solution currently.

**Comment by pedrovagner** [comment]
Just close my issue? I think this is a missing feature. Alright, maybe I'm wrong. I just have a month in Node development. I need to be strong, keeping using Node and find out the "Node Way" to validate. Thanks anyway.

**Comment by vkarpov15** [comment]
Sorry, didn't mention that there's already an issue open to track this, #3232. Follow that for updates, but for now `post('validate')` doesn't exactly work. The way I've worked around this in the past is just stuffing multi-field validation into individual field validators.

**Comment by pedrovagner** [comment]
Nice, I just subscribed to this issue. Exactly what I say, when I put multi-field validation into individual field validator, I end up calling the same validation code twice (or more).

I don't understand exactly what is planned to do in issue #3232. Let's see if I understand. `schema.validate()` callback gets called after `post('validate')`? If that was the case, it's strange, because is expected that `post('validate')` gets called after all validation code. Please, correct me if I wrong.

**Comment by vkarpov15** [comment]
So currently mongoose does not guarantee whether a post validate hook gets called before the validate callback or not. This prevents you from effectively doing additional validation logic in post validate, which is why we have #3232.

Can you clarify what you mean by calling the same validation code twice?

**Comment by pedrovagner** [comment]
This is a common situation where this happens:

```javascript
const userSchema = new mongoose.Schema({
  email: {type: String},
  ip: {type: String}
});

userSchema.path('email').validate(email => {
  if (!isEmail(email)) return false;
  // I need use 'ip' field here, but first I need ensure it is valid (again)
  if (!isIp(ip)) return false;
  return isAllowedEmail(ip, email);
});
userSchema.path('ip').validate(ip => {
  if (!isIp(ip)) return false;
  // I need use 'email' field here, but first I need ensure it is valid (again)
  if (!isEmail(email)) return false;
  return isAllowedIp(ip, email);
});
```
It's possible arrange this piece of code to avoid twice validation?

**Comment by pedrovagner** [comment]
I just found a way to workaround this issue: Create a method `schema.validateTogether` and put there multi-field validation code, then create another method `schema.validateAll` that call `schema.validate` and `schema.validateTogether`. Then `schema.pre('save')` call `schema.validateTogether`. If I want validate data, instead `schema.validate` I do `schema.validateAll`. Yeah, that's it.

**Comment by vkarpov15** [comment]
That's a good workaround :+1:
