### ISSUE TITLE
invalid Schema type passed, but mongoose not throwing error

### ISSUE THREAD

**Issue by xiaofan2406** [Automattic/mongoose#4524]
For example:
```
const post = new Schema({ title: String, vote: Number });
```
If I am creating with 
```
{ title: 12230, vote: '12' }
```

I am expecting error to be thrown here, but mongoose instead automatically cast the types. How do I stop mongoose from doing this?

Edit: i think it is the same case for 'true' to Boolean as well

**Comment by vkarpov15** [comment]
That's a feature, no way to turn it off, just a very fundamental part of how mongoose works. You can write custom types but that's about it

**Comment by KID-WuMeng** [comment]
+1.

I think there should has a switch to close the automatically cast for schema.

It's is a useful feature for more stricter validate.
