### ISSUE TITLE
I tried to index all collections but its getting me the error message 

### ISSUE THREAD

**Issue by riginoommen** [Automattic/mongoose#4527]
Code: 
var db = mongoose.connection;

db.once('open', function(error, names) {
    console.log('Connected to mongo server.');
    mongoose.connection.db.collectionNames(function (err, names) {
        for(var index in names) {
            var collectionName = names[index].name;
            console.log(collectionName);
            db.collection(collectionName).createIndex({'$**':'text'},null,function(err, results) {
                console.log(results);
                callback();
            });
        }
    });
});

Result: 
vlans
$**_text
$**_text
$**_text
$**_text
$**_text
$**_text
$**_text

/home/roommen/Work/Ops/operations-portal-server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;  
              ^
ReferenceError: callback is not defined

How to resolve it

**Comment by vkarpov15** [comment]
Is this error in your code? There's a `callback()` call in your code, perhaps that's the issue?

**Comment by varunjayaraman** [comment]
@riginoommen this is definitely a reference error since `callback` isn't defined in your code, and not an issue with mongoose
