### ISSUE TITLE
Random authentication errors: SCRAM-SHA-1 authentication failed

### ISSUE THREAD

**Issue by aartiles** [Automattic/mongoose#4530]
After enabling authentication it see the following errors in our logs
```
2016-09-16T13:54:52.932+0000 I ACCESS   [conn84452] SCRAM-SHA-1 authentication failed for USERNAME on admin from client xx.xx.xx.xx ; BadValue: Unmatched SCRAM-SHA-1 nonce received from client in second step, expected HASH1 but received HASH2
```

Then I randomly get this error when trying to query: `MongoError: not authorized on DATABASE to execute command...`
It seems that some of the connections in the pool are not being authenticated correctly.
Unfortunately I haven't been able to reproduce it as it only happen randomly in production after restarting the processes.

mongoose version: 4.4.11 (I've tested with 4.6.0 and the same happens)
mongodb version: 3.2.9

This is the way I create the connections:
```
    var uri = 'mongodb://USENAME:PASSWORD@host1:port1,host2:port2/database?authSource=admin';

    var options = {};
    options.server = {
      auto_reconnect: true,
      poolSize: 5,
      socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 },
      reconnectTries: 3000
    };

    options.replset = {
      auto_reconnect: true,
      poolSize: 5,
      socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 },
      reconnectTries: 3000
    };

    var db = mongoose.createConnection(uri, options);

    mongoose.connection.on('error', function(err) {
      console.log('MONGODB ERROR MONGOOSE LEVEL ' + server, err);
    });

    db.on('connecting', function() {
      console.info('MONGODB ' + server + ' connecting.');
    });

    db.on('error', function(err) {
      console.log('MONGODB ERROR ' + server, err);
    });

    db.on('close', function(err) {
      console.log('MONGODB CLOSE ' + server, err);
    });

    db.on('connected', function() {
      console.info('MONGODB ' + server + ' connected successfully.');
    });

    db.once('open', function callback() {
      console.info('MONGODB ' + server + ' opened successfully.');
    });

    db.on('reconnected', function() {
      console.info('MONGODB ' + server + ' reconnected.');
    });

    db.on('timeout', function() {
      console.info('MONGODB ' + server + ' timeout.');
    });

    db.on('disconnected', function() {
      console.info('MONGODB ' + server + ' disconnected');
    });
```

This could be related to #4257 but I'm not sure about how he solved it.

**Comment by vkarpov15** [comment]
Try upgrading to 4.6.0 and doing `rm -rf node_modules && npm install`. This was an issue with 2.1.21 of the mongodb node driver, 4.6 uses 2.2. Also is mongoose the only npm module you're using to connect to mongodb?

**Comment by aartiles** [comment]
We do `npm install` in a fresh machine on every deploy. Any way I have removed a legacy dependency that used a previous version of mongodb just in case. 
The problem is that when I upgrade to 4.6.0 then I get a new error `MongoError: no primary found in replicaset` which seems to be related to #4517 (hopefully you release 4.6.1 soon). 

So we are in a bucle here:
4.6.0: -> `MongoError: no primary found in replicaset`
4.5.10 -> `MongoError: not authorized on...`

**Comment by vkarpov15** [comment]
So 4.6.1 is out, has that helped?

**Comment by aartiles** [comment]
It's stable after 24 hours so it seems both the authentication problem and #4517 are fixed.
Thanks!
