### ISSUE TITLE
object relationship is depopulated after adding an item via push

### ISSUE THREAD

**Issue by sescobb27** [Automattic/mongoose#4532]
hi, when i try to add an object to a has many relationship mongoose depopulates it right after adding it, is there something i'm missing or how can it ensure it doesn't get depopulated?. see the example above:
```js
// models/customer.js
var customerSchema = new Schema({
  customerType: {
    type: String,
    required: 'Customer type is required',
  },
  fullName: {
    type: String,
    required: 'Full name is required'
  },
  orders: [{
    type: Schema.Types.ObjectId,
    ref: 'Order'
  }]
});
module.exports = mongoose.model('Customer', customerSchema);

// models/order.js
var orderSchema = new Schema({
  customer: {
    type: Schema.Types.ObjectId,
    ref: 'Customer',
  }
});
module.exports = mongoose.model('Order', orderSchema);

// console
var customer = new Customer({fullName:'yeah', customerType: 'subscriber'});
var order = new Order({})
customer.orders.push(order);
customer.orders // => ["57dc57dd9c4feb0a27f6fc5f"] but I'm expecting customer.orders to equal [order object]

```
<img width="495" alt="screen shot 2016-09-16 at 3 36 52 pm" src="https://cloud.githubusercontent.com/assets/1157892/18600694/a8746432-7c24-11e6-9a11-0704f8a2b51a.png">

**Comment by vkarpov15** [comment]
Mongoose will depopulate it for you because an array can only be entirely populated or entirely not populated, so unless you ran `populate()` on that field or you marked it as populated on your own, mongoose will just put the `_id` in the array. You can manually mark `orders` as populated like so:

```
customer.populated('orders', [], { model: Order }); // <-- mark `orders` as populated with the model Order
customer.orders.push(order);
console.log(customer.orders); // [{"_id":"57de11a434f2f80a7dbf2d3c"}]
```
