### ISSUE TITLE
mongoose connection doesn't seem to work with a new mongodb driver ('no mongos proxies found in seed list")

### ISSUE THREAD

**Issue by ycheapopo** [Automattic/mongoose#4535]
configuration:
windows server 2012 R2 VM (running in azure),
mongoose 4.6.0
mongodb 2.2.9
mongodb-core 2.0.11

Before upgrade to new mongodb, I had 1 machine (with no replica set). After upgrading, it seems I need to define even for just one machine a replicate set (which I have done).

connection string:
mongodb://[machinename]:[port]/[db]?replicaSet=[replicatesetname]
issue happen also when i configure the options parameter
options:
replSet: {
	replicaSet: 'replicatesetname', ssl: false, sslValidate: false
},

When creating a small mongodb (not mongoose) connection test, I could connect;

I get an error from mongodb: 'no mongos proxies found in seed list'
See also 
https://github.com/christkv/mongodb-core/issues/118

**Comment by vkarpov15** [comment]
Yeah that's a bug in mongoose, right now we were looking for `replset` with a lower-case 'S' to determine whether you were looking for a replica set or not.
