### ISSUE TITLE
Is not a function ERROR - this.isModified is not a function

### ISSUE THREAD

**Issue by oltmannsdaniel** [Automattic/mongoose#4537]
When I use following code:
```Javascript
userSchema.pre('save', (done) => {
  if(this.isModified('password')) {
    bcrypt.hash(this.password, null, null, (err, hash) => {
      if(err) return next(err);

      this.password = hash;
      this.updated_at = new Date().toISOString();
      done();
    });
  } else {
    return done();
  }
});
```
I receive following Error:
```
TypeError: this.isModified is not a function
    at model.userSchema.pre (C:\code\project\core\models\user.js:26:11)
    at _next (C:\code\project\node_modules\hooks-fixed\hooks.js:62:30)
    at fnWrapper (C:\code\project\node_modules\hooks-fixed\hooks.js:186:8)
    at model.Object.defineProperty.value.fn (C:\code\project\node_modules\mongoose\lib\schema.js:221:11)
    at _next (C:\code\project\node_modules\hooks-fixed\hooks.js:62:30)
    at fnWrapper (C:\code\project\node_modules\hooks-fixed\hooks.js:186:8)
    at C:\code\project\node_modules\mongoose\lib\schema.js:196:17
    at C:\code\project\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Problem:
- `this` is not a Document, Query or Schema. It's value is `{}`

How can I solve that?

**Comment by VictorGerritsenQLVR** [comment]
You are using an arrow operator for the callback, which changes the scope of `this`. If you define a regular callback you should be fine, e.g.:

```
userSchema.pre('save',  function(done)  {
});
```

**Comment by oltmannsdaniel** [comment]
Ok. Thanks. It works.

**Comment by R4meau** [comment]
Is there a way to do it with arrow functions? I'm using ES6 and my eslintrc is complaining about regular callbacks.

**Comment by leodsgn** [comment]
I had this issue, as well. Thanks for help @VictorGerritsenQLVR!

**Comment by domarp-j** [comment]
Is there a way to change the code to accommodate the arrow operator, rather than using `function(next)`?

**Comment by R4meau** [comment]
@domarp-j Good question. I thought about it and tried to figure it out but I couldn't come up with anything easier than just switching to a regular callback function. Maybe someone else has done it tho. I'll keep an eye on this issue.

**Comment by vkarpov15** [comment]
No way to do it, fat arrows use lexical scope for context, no way around it.

**Comment by ZeeAzmat-punch** [comment]
had same issue, thanks for the help

**Comment by gdenn** [comment]
Hi, was stuck on the same problem with the es6 arrow function. Thank you very much!

**Comment by cheri3a** [comment]
great thank u

**Comment by m00zi** [comment]
**Thanks**, works for me too.
