### ISSUE TITLE
server instance pool was destroyed

### ISSUE THREAD

**Issue by shellHong** [Automattic/mongoose#4538]
I Wrote a log service, nodejs + mongo (mongoose), then run for a period of time (7, 8 hours), there will be "server instance pool was destroyed" error, poolsize set to 2000.

**Comment by vkarpov15** [comment]
Code samples please?

**Comment by gauravbansal74** [comment]
+1 we are facing this issue also. :(

**Comment by vkarpov15** [comment]
@gauravbansal74 please provide code samples in a separate issue
