### ISSUE TITLE
Populating across multiple levels issue

### ISSUE THREAD

**Issue by programmer4web** [Automattic/mongoose#4539]
with this structure:

```javascript
 Row = new Schema({
    product			: { type: Schema.Types.ObjectId, ref: 'Product'}
});
OrderSchema.add({
	rows		: [Row]
});
```

This code used to work with older versions:

```javascript
Orders.find().populate([
     {path: 'rows', populate: { path: 'product', model: "Product" } }
]).exec().then(function(orders){ ...  });
```

But now orders.rows.product is just in id

**Comment by vkarpov15** [comment]
TBH I have trouble believing that the code as written ever worked. The correct way is `Orders.find().populate({ path: 'rows.product', model: 'Product' }).exec().then()`, you do not need to populate `rows` because it is not in a separate collection
