### ISSUE TITLE
why the _id duplicate?

### ISSUE THREAD

**Issue by linixc** [Automattic/mongoose#4546]
{
    "_id" : ObjectId("579c51d107621eb62ef1f1f2"),
    "roleId" : "56823",
    "runePages" : [ 
        {
            "_id" : ObjectId("57d2cdab383c044802428950"),
            "usePassiveSkills" : [],
            "inlayRunes" : [],
            "name" : "符石页1",
            "pageId" : 1
        }, 
        {
            "_id" : ObjectId("57d2cdab383c044802428951"),
            "usePassiveSkills" : [],
            "inlayRunes" : [],
            "name" : "符石页2",
            "pageId" : 2
        }, 
        {
            "_id" : ObjectId("57d2cdab383c044802428950"),
            "usePassiveSkills" : [],
            "inlayRunes" : [],
            "name" : "符石页1",
            "pageId" : 1
        }, 
        {
            "_id" : ObjectId("57d2cdab383c044802428951"),
            "usePassiveSkills" : [],
            "inlayRunes" : [],
            "name" : "符石页2",
            "pageId" : 2
        }
    ]
}

**Comment by linixc** [comment]
what's the id generation rules?

**Comment by enrichz** [comment]
From the MongoDB documentation:
 ObjectId(<hexadecimal>)
    Returns a new ObjectId value. The 12-byte ObjectId value consists of:
    -   a 4-byte value representing the seconds since the Unix epoch,
    -   a 3-byte machine identifier,
    -   a 2-byte process id, and
    -   a 3-byte counter, starting with a random value.

What's the code that you use to insert the documents?

**Comment by vkarpov15** [comment]
How are you generating the ids?
