### ISSUE TITLE
updatedAt timestamp doesn't change in embedded document when updated with findByIdAndUpdate

### ISSUE THREAD

**Issue by jfdominguezp** [Automattic/mongoose#4550]
Hello, 

I appreciate your help with this. When pushing a new embedded document to an array, `createdAt` and `updatedAt` fields are created. But, when I perform an update operation on the subdocument,  its `updatedAt` field doesn't change; instead, its parent's gets updated. I'm using mongoose 4.5.10.

I have the following model:

```javascript
var ProfileSchema = new Schema ({
  ...
  products:[ProductSchema],
  ...
},
{ timestamps: true });

var ProductSchema = new Schema ({

  name:String,
  type: String,
  description:String,

},
{ timestamps: true });
```

When I push a new Product to the products array, `createdAt` and `updatedAt` timestamps are added to the document. I'm pushing new embedded documents like this:

```javascript
Profile.findByIdAndUpdate(
  {_id: id},
  { $push: { products: { /*fields*/ } } },
  { new: true, upsert: false },
  function(error, profile) {
    if(error) //do something;
    //Send response
  }
);
```

I'm updating an embedded documents like this:

```javascript
var update = dotNotate(fields);

Profile.findByIdAndUpdate(
  { "_id": profileId, "products._id": productId },
  { $set: update }, 
  { new : true },
  function(error, profile){
    if(error) //do something
    //Send response
  }
);
```
Product values are updated correctly, but `updatedAt` timestamp isn't. It always has the same value as `createdAt`. Instead, profile's timestamp gets updated.

**Comment by vkarpov15** [comment]
Expected behavior atm, timestamps will only update a nested docs updatedAt if you update the whole doc. Follow #4412 for updates on this issue
