### ISSUE TITLE
Can't define toString method on model since 4.6.1

### ISSUE THREAD

**Issue by leseulsteve** [Automattic/mongoose#4551]
Since we have updated from 4.6.0 to 4.6.1 we have this error on models that have a toString method:

    // Model definition.

    Model.methods.toString = function () {};

    // Error stack in logs

    Error: You have a method and a property in your schema both named "toString"
    at applyMethods (...\node_modules\mongoose\lib\model.js:3255:13)
    at Function.compile ...\node_modules\mongoose\lib\model.js:3200:3)
    at Mongoose.model (...\node_modules\mongoose\lib\index.js:392:17)
    at Object.<anonymous> (X:\..\app\module\models\model.js:21:27)
    ...

**Comment by vkarpov15** [comment]
Do you also have a field in your schema called toString?

**Comment by vkarpov15** [comment]
Fixed in master, will be fixed in next release. Thanks for reporting :+1:

**Comment by leseulsteve** [comment]
I didn't have a field called toString on my schema. Thanks for the quick response!

**Comment by vkarpov15** [comment]
Yeah the issue was not using hasOwnProperty. 4.6.2 is out and should fix this :+1:
