### ISSUE TITLE
Did Model.remove() callback ever contain an array of removed items?

### ISSUE THREAD

**Issue by mitchellporter** [Automattic/mongoose#4553]
I have a test project I've been working on and I recently updated to `mongoose version 4.6.0`. I have a few files in this project that have code like the following:

```
Model.remove({}, function(err, removed) {
logger.log('Removed this many models: ' + removed.length);
});
```

If my memory serves correctly, calling remove on a model used to have the above callback, but after looking at the current documentation and testing, it seems the callback only includes one parameter which is an error.

I also found an answer on StackOverflow that implies the callback used to contain a second parameter that was the count of the removed items as well: http://stackoverflow.com/a/24881557/3344977

My memory could be wrong, but I thought I remembered that `Model.remove()'s` callback had a second parameter that was an array of the removed items. I also understand that this is currently the correct behavior on `modelInstance.remove()`.

Unfortunately this test project didn't have tests so if this is new behavior I didn't have any tests to catch it after upgrading to `mongoose version 4.6.0`

**Comment by vkarpov15** [comment]
Hmm I think the second param to the callback should be the raw result from the mongodb driver, which used to be a number in mongodb driver 1.x but is now an object with driver 2.x, which is what mongoose 4.x uses. Can you show me the code that isn't working for you?

**Comment by mitchellporter** [comment]
@vkarpov15 I don't think there is any issue here. I think what I'm remembering is wrong. Apologies and thanks for the help.

**Comment by michAtEl** [comment]
@vkarpov15 Thanks for clarification. I thinks this information about the raw result should be added to the documentation of Model.remove:
http://mongoosejs.com/docs/api.html#model_Model.remove
Furthermore, it would be nice to have the raw result in the typescript definition.
Or is the raw result of mongodb something that you don't want to be part of the public api of mongoose?

**Comment by vkarpov15** [comment]
It is definitely a part of the public API, the docs will mention it in the next release. I don't maintain any typescript definitions however, so ask your friendly neighborhood typescript definition maintainer for help on that front :)
