### ISSUE TITLE
Mongoose create multiple index not work

### ISSUE THREAD

**Issue by idock** [Automattic/mongoose#4554]
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ship = new Schema({
  user: {type:Schema.Types.ObjectId, ref:'User', required: true},
  other: {type: Schema.Types.ObjectId, ref:'User', required: true},
  created:{type: Date, default: Date.now}
});
ship.index({user:1, other:1}, {unique:true});
module.exports = mongoose.model('UserShip', ship);
```

It is not work!

**Comment by idock** [comment]
"mongoose": "~4.5.8"
MongoDB shell version: 3.2.8

**Comment by vkarpov15** [comment]
What happens? Do you get an error?

**Comment by Pompeu** [comment]
same problem in mongoose 4.6.2, can't create index, but in shell working normaly

**Comment by vkarpov15** [comment]
Please provide code samples

**Comment by rizkiheryandi** [comment]
Still not work here...

mongoose : 4.11
mongodb : 3.4

**Comment by rizkiheryandi** [comment]
Hmm in mongodb, multiple index with text imposibble...

Maybe this article can help.. https://code.tutsplus.com/tutorials/full-text-search-in-mongodb--cms-24835
