### ISSUE TITLE
Connection URI containing a replica set name with a leading number crashes mongoose

### ISSUE THREAD

**Issue by kevinadi** [Automattic/mongoose#4556]
Using a connection string URI having a replica set name with a leading number crashes mongoose.

For example:

```
mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=123-myreplset')
```

crashes mongoose with an error:

```
[ERROR-ReplSet:10156] 1474608343698 [1] server in replset 123-myreplset is not part of the specified setName 123
```

Apparently the name `123-myreplset` was parsed into `123`, ignoring the rest of the string.

I traced the issue to muri, and have submitted a PR that fixes this: https://github.com/aheckmann/muri/pull/8

**Comment by vkarpov15** [comment]
Updated muri, thanks for finding this :+1:
