### ISSUE TITLE
Duplicate key error collection with unique field.

### ISSUE THREAD

**Issue by axenovV** [Automattic/mongoose#4562]
How to make a field unique and optional at the same time?

[This is my question in stack](http://stackoverflow.com/questions/39698482/duplicate-key-error-collection-with-unique-field/39698640?noredirect=1#39698640l)

**Comment by vkarpov15** [comment]
Use a sparse index as suggested on SO. TBH I haven't used partial indexes yet, but sparse indexes have worked well for me in the past.
