### ISSUE TITLE
Removal of document modifies document data

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4566]
Is this the expected behaviour of Mongoose (simplified example)?

```js
console.log(booking);
booking.remove().then(() => console.log(booking));
```

```
{ _id: 57ea07fb1ef1d82dd4a056c1,
  court: { name: 'Court 2', _id: 444bee3e4527879d33c7b31b },
  date: 2016-09-26T11:00:00.000Z,
  __v: 0,
}
Mongoose: bookings.remove({ _id: ObjectId("57ea07fb1ef1d82dd4a056c1") }, {})
{ _id: 57ea07fb1ef1d82dd4a056c1,
  court: null,
  date: 2016-09-26T11:00:00.000Z,
  __v: 0,
}
```

The court subdocument is set to `null` for some reason, meaning that I can't use that data to for example send out a confirmation email, because part of the data is missing.

If this is expected behaviour, what is the rationale behind it? Why would Mongoose modify the document if it's going to be deleted?

**Comment by vkarpov15** [comment]
Hmm that's not expected behavior as far as I know, will take a look

**Comment by vkarpov15** [comment]
Fixed, thanks for reporting :+1:

**Comment by adambuczynski** [comment]
Cheers thanks!
