### ISSUE TITLE
How to print subdocument value in html 

### ISSUE THREAD

**Issue by Gajendrasinh** [Automattic/mongoose#4567]
When i call this router i got below data

app.get('/contacts/list', function(req, res){
  db.collection('contacts').find().toArray((err, result) => {
    if (err) return console.log(err)
      //console.log(JSON.stringify(result) );
      res.render('ListContact.html', {page_title:"All Contacts", contact: result})
      db.close();
   // console.log(result);
  })
});

Collection DATA

{
        "_id" : ObjectId("57ea35b6d085c304201490a7"),
        "name" : "k",
        "mobile" : "k",
        "email" : "k@gmail.com",
        "company" : "k",
        "designation" : "k",
        "information" : [
                {
                        "owner" : "k",
                        "website" : "k",
                        "phone" : "k",
                        "otherPhone" : "k",
                        "skype" : "k",
                        "LinkedIn" : null,
                        "facebook" : "k",
                        "Twitter" : "k",
                        "google" : "k",
                        "currency" : "k"
                }
        ],
        "BillingAddress" : [
                {
                        "addressline1" : "k",
                        "addressline2" : "k",
                        "city" : "k",
                        "zipcode" : "k",
                        "state" : "k",
                        "country" : "k"
                }
        ],
        "Details" : [
                {
                        "description" : "k",
                        "tags" : "k"
                }
        ]
}

i want to display this value in html

```
  <table class="table">
    <thead>
       <tr>
        <th width="50px">No</th>
        <th>Name</th>
        <th>Designation</th>
        <th>Company</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Owner</th>
        <th>Tags</th>
      </tr>
    </thead>
    </thead>
    <tbody>
         <% if(contact.length){ 

         for(var i = 0;i < contact.length;i++) { %>

         <tr>
          <td><%=(i+1)%></td>
          <td><%=contact[i].name%></td>
          <td><%=contact[i].designation%></td>
          <td><%=contact[i].company%></td>
          <td><%=contact[i].email%></td>
          <td><%=contact[i].mobile%></td>
          <td><%=contact[i].owner%></td>
          <td><%=contact[i].tags%></td>
        </tr>
        <% }

      }else{ %>
      <tr>
        <td colspan="3">No Contact in list</td>
      </tr>
      <% } %>

      </tbody>
  </table>
```

when run not display owner value

**Comment by varunjayaraman** [comment]
Your `owner` value lives on an object within the `information` array, it doesn't live directly on `contact`

**Comment by Gajendrasinh** [comment]
How can i print that?

-
Best Regards,
Gajendrasinh Zala

**Comment by vkarpov15** [comment]
Doesn't look like there's an owner property in your data

**Comment by varunjayaraman** [comment]
Closing this since this just an issue of improperly accessing properties on the objects that live in the `information` array.
