### ISSUE TITLE
aggregate.exec() and agregate.then() both throw error

### ISSUE THREAD

**Issue by zeg-io** [Automattic/mongoose#4568]
https://github.com/Automattic/mongoose/issues/3212 was an older issue in which it was stated that .exec was fixed, in fact, I found another issue which supposedly fixed the .then as well, but in the latest version of Mongoose (4.6.1) it doesn't work.

**Comment by vkarpov15** [comment]
Please provide code samples

**Comment by zeg-io** [comment]
Well, as stated in #3212:

> when using method Model.aggregate (...).exec(), system will throw
> 
> `undefined is not a function`

So to validate simply set up a model, run an aggregate on it and attempt to .exec() it afterwards.

Aggregate seems to not return a promise.

**Comment by vkarpov15** [comment]
We have tests in place for `aggregate().exec()` and `aggregate().then()` in place and they're succeeding, so the issue isn't that obvious. Please provide a code sample and clarify which versions of mongoose and mongodb you're using.
