### ISSUE TITLE
Non-issue regarding lowercase attribute in schema declaration and queries 

### ISSUE THREAD

**Issue by daretodave** [Automattic/mongoose#4569]
When a property is specified to be lower cased in the schema -

```
...   = new Schema({
  username: {type: String, lowercase: true}
})

```

Shouldn't the select statements that filter on this property lower-case the input?

```
                User.findOne({
                    username: "DAVID"
                },
```

VS. doing this before hand?

```
                User.findOne({
                    username: username.toLowerCase()
                }
```

The former **find** seems more practical when the schema denotes the property is lower-cased. 

Additionally **insert** has this behavior of automatically lower-casing the property.

**Comment by vkarpov15** [comment]
That's a good suggestion, currently mongoose does not support that but I'd love to add it for a future release

**Comment by vkarpov15** [comment]
4.10.0 has an option called `runSettersOnQuery`, for example:

```javascript
var testSchema = new Schema({
  name: { type: String, lowercase: true },
  num: { type: Number, set: function(v) { return Math.floor(v); } }
}, { runSettersOnQuery: true });
```

That will run setters when you're querying
