### ISSUE TITLE
Cannot override .toString() and other Object.prototype properties as schema methods

### ISSUE THREAD

**Issue by pdspicer** [Automattic/mongoose#4572]
Started getting the follow error when using `mySchema.methods = { toString () {...}}` in mongoose 4.6.1:
```
Error: You have a method and a property in your schema both named "toString"
    at applyMethods (/Users/prevalent/projects/vtm/server/node_modules/mongoose/lib/model.js:3255:13)
    at Function.compile (/Users/prevalent/projects/vtm/server/node_modules/mongoose/lib/model.js:3200:3)
    at Mongoose.model (/Users/prevalent/projects/vtm/server/node_modules/mongoose/lib/index.js:392:17)
```
Error occurs when calling `mongoose.model(name, mySchema)`. My schema does not have a toString property defined, and this worked with the same code in 4.6.0 and prior versions. If I had to guess I'd say #4475 has something to do with this. I've tested with other properties that are in Object.prototype, they exhibit the same behavior. Might be the same for other primitive prototype properties as well, although this I did not check.

Below is a runnable code sample demonstrating this issue. It works in 4.6.0 but not 4.6.1:

```javascript
var mongoose = require('mongoose');

var mySchema = new mongoose.Schema({});
mySchema.methods = { hasOwnProperty: () => false, toString: () => '', valueOf: () => '' };

mongoose.model('mySchema', mySchema);
```

**Comment by pdspicer** [comment]
Sorry for the dup, swear I looked for it elsewhere...

**Comment by vkarpov15** [comment]
No worries about the dup, would rather have duplicate issues than nobody reporting an issue. Upgrade to 4.6.2 and this issue should go away
