### ISSUE TITLE
Include ObjectIds of docs inserted through insertMany()

### ISSUE THREAD

**Issue by rahulyagi** [Automattic/mongoose#4573]
mongodb does returns insertedIds Array when inserted through insertMany, so why not include this in the promise callback

**Comment by vkarpov15** [comment]
If I recall correctly, the insertMany promise resolves with the inserted docs, which includes their _id's. Is there a reason why this is not sufficient?

**Comment by rahulyagi** [comment]
I am using mongoose v4.5.3 and on using insertMany, the promise doesn't return any _ids with the docs. The _id comes as undefined with each doc.

**Comment by vkarpov15** [comment]
Can you provide a code sample with your schemas please?

**Comment by arvi** [comment]
I can confirm that insertMany doesn't return ids. It returns everything BUT inserted ids. Here is the log of what it returns.

```
[ { updatedAt: 2018-02-22T05:08:06.962Z,
    createdAt: 2018-02-22T05:08:06.962Z,
    __v: 0,
    companyId: 5a8be99b26034558cfee43c9,
    name: 'HR', },
  { updatedAt: 2018-02-22T05:08:06.962Z,
    createdAt: 2018-02-22T05:08:06.962Z,
    __v: 0,
    companyId: 5a8be99b26034558cfee43c9,
    name: 'IT',
     } ]
```
