### ISSUE TITLE
`findByIdAndUpdate` Calls `toObject` (`transform`) Before Pushing

### ISSUE THREAD

**Issue by mahsa-motherco** [Automattic/mongoose#4574]
Hi,
We have a schema with an array field which is a subschema. We are using the `_id` of each element in the array for retrieving data. Also, we have a transform function for converting `_id` to `id` with String type using `toObject` on our subschema (array field).

We called `findByIdAndUpdate()` to find a document, and we wanted to add a new element into the aforementioned array field. However, we noticed an issue with the newly added element. The element had `id` with String or Number type in the database instead of `_id` with the `ObjectId` type. And, it caused issues by the time we called `toObject` or wanted to read the resulting document value in anyway. We got the following error on `transform` function: `TypeError: Cannot read property 'toString' of undefined` on line `ret.id = ret._id.toString()`, which led us to find out that there was no `_id` field on the element in our collection.

We believe the problem is caused by `findByIdAndUpdate` that applied `transform` before pushing the new element and uses the transformed values to make a new document.

```
const SubdocSchema = new Schema({ ... }, {
  toObject: {
    transform(doc, ret) {
      ret.id = ret._id.toString()
      delete ret._id
    }
})

const CollectionSchema = new Schema({
 field1: { type: ... }
 field2 : {
   arrayField: [SubdocSchema],
   innerField2: { ... }
 },
 ...
})
```
```
CollectionSchema.findByIdAndUpdate(idValue, {
  $push: { 'field2.arrayField': newValue }
}, { new: true })
```

There was a similar issue [here](https://github.com/Automattic/mongoose/issues/2355) which might help to solve this issue.

Thank you for your attention.

**Comment by vkarpov15** [comment]
Thanks for the detailed issue report, will investigate asap
