### ISSUE TITLE
Disabling specific validations instead of disabling all of them?

### ISSUE THREAD

**Issue by mitchellporter** [Automattic/mongoose#4577]
I already know that there is a way to disable validation when saving by passing in the `validateBeforeSave: false` option, but is there a way to disable a specific validation for a field? An example would be something like `I want to validate the username, but not the password`.

Is there a way to do this, or is `validateBeforeSave` the only option?

**Comment by vkarpov15** [comment]
The `validateSync()` function supports passing a list of fields to validate, but that's more a hack than anything. No way to do that in general with `save()` but you can pretty easily write custom validators that skip validation given certain criteria

**Comment by mitchellporter** [comment]
Awesome thanks for the help!
