### ISSUE TITLE
Setting at a path inside a nested schema does not instantiate nested field as a mongoose document

### ISSUE THREAD

**Issue by varunjayaraman** [Automattic/mongoose#4578]
It seems that using `document.set()` on a path that leads to a path inside a nested schema does not then instantiate the schema in which the path lies. For instance, if you have 2 schemas, a `Parent` and a `Child`, and you do `new Parent().set('family.child.age', 15)`, it will create the a document at `parent.family.child` but as a POJO and not a mongoose document. 

Here's a repo to reproduce: https://github.com/varunjayaraman/set-schema-bug/tree/master

**Comment by varunjayaraman** [comment]
Seems like this is related to https://github.com/Automattic/mongoose/issues/4528 actually, your call as to whether or not to close this as a duplicate @vkarpov15

**Comment by vkarpov15** [comment]
Thanks for the repro @varunjayaraman , was having trouble figuring out what #4528 was talking about

**Comment by vkarpov15** [comment]
Actually #4528 is closely related but not quite the same, will fix it as well
