### ISSUE TITLE
Mongoose 4.6.0 findOneAndUpdate insert by element returns null and does not update document

### ISSUE THREAD

**Issue by stevenelson74708** [Automattic/mongoose#4582]
The following call to findOneAndUpdate updates the document properly in mongoose versions 4.5.10 and earlier, but in versions 4.6.0 and 4.6.1 the call returns model as null and does not update the document. Should this call to findOneAndUpdate still work properly after version 4.5.10?

                  `// Array is at max size, find oldest element and replace
                    wlogger.debug("UserId: " + userId + " locations array is full - size = "
                        + users[0].locations.length
                        + " -- replace oldest location in array");

                    var oldestIndex = 0;
                    var oldestDate = users[0].locations[0].accessDate;

                    for (var i = 0; i < (constants.maxLocationsArraySize - 1); i++)
                    {
                        if (oldestDate >
                            users[0].locations[i + 1].accessDate)
                        {
                            oldestDate = users[0].locations[i + 1].accessDate;
                            oldestIndex = i + 1;
                        }
                    }

                    // Bracket notation is required to set the value for a key of an object from a variable
                    var oldestLocationsIndex = "locations." + oldestIndex;
                    wlogger.debug("ipLocationsIndex = " + oldestLocationsIndex);
                    var element = {};
                    element[oldestLocationsIndex] = locationInfo;

                    //noinspection JSUnresolvedFunction
                    user.findOneAndUpdate(
                        {"_id": userId},
                        {$set: element},
                        function (err1, model)
                        {
                            if (model == null)
                            {
                                wlogger.warn("model == null -- "
                                    + "unable to update location info for "
                                    + "UserId: " + userId);
                                callback({"response": false});
                            }
                            else if (err1 == null)
                            {
                                wlogger.debug("Updated location info for UserId: "
                                    + userId + " in array");
                                callback({"response": true});
                            }
                            else if (model.length != 0)
                            {
                                wlogger.error(err1 + " - Unable to update location info for "
                                    + "UserId: " + userId + " -- model = "
                                    + model);
                                callback({"response": false});
                            }
                            else
                            {
                                wlogger.error(err1 + " unable to update location info"
                                    + " for UserId: " + userId);
                                callback({"response": false});
                            }
                        });`

**Comment by vkarpov15** [comment]
It should work, can you show me what your schema looks like?

**Comment by stevenelson74708** [comment]
The schema is shown below.

var mongoose = require('mongoose');
require('mongoose-long')(mongoose);

var Schema = mongoose.Schema;

var phoneNumbersSchema = new Schema( {_id: false, type: String, number: String, primary: Boolean} );
var categoriesSchema = new Schema( {_id: false, categoryId: Schema.Types.ObjectId} );
var customerSchema = new Schema( {_id: false, firstName: String, lastName: String, phoneNumbers: [phoneNumbersSchema] , userId: Schema.Types.ObjectId} );
var providerSchema = new Schema( {_id: false, providerName: String, providerId: Schema.Types.ObjectId} );
var ipAddrSchema = new Schema( {_id: false, ipType: String, useCount: Number, upper64: Schema.Types.Long, lower64: Schema.Types.Long, lastUsedDate: Date} );
var locationSchema = new Schema( {_id: false, location: { type: { type: String, default: 'Point' }, coordinates: [Number] }, accessDate: Date, accessType: String} );
var inMessageSchema = new Schema( {_id:false, date: Date, fromUserId: Schema.Types.ObjectId, fromEmail: String,
 read: { type: Boolean, default: false }, deleted: { type: Boolean, default: false }, subject: String, message: String} );
var outMessageSchema = new Schema( {_id:false, date: Date, toUserId: Schema.Types.ObjectId, toEmail: String,
 deleted: { type: Boolean, default: false }, subject: String, message: String} );
var recentUploadSchema = new Schema( {_id: false, uploadDate: Date, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
var recentViewsSchema = new Schema( {_id: false, viewDate: Date, viewCount: Number, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
var recentAddsSchema = new Schema( {_id: false, addDate: Date, addCount: Number, categoryId: Schema.Types.ObjectId, itemId: Schema.Types.ObjectId, itemName: String });

var userSchema = mongoose.Schema({ 
 token : String,
 email: String,
 userName: String,
 deviceId: String,
 devicePhoneNumber: String, 
 hashed_password: String, 
 hashed_admin_code: String,
 maxStorageByteLimit: { type: Number, default: 1073741824 },
 accessLevel: { type: Number, default: 2 },
 lastAccessType: Number,
 storageBytesUsed: { type: Number, default: 0 },
 totalStorageBytesUsed: { type: Number, default: 0 },
 deletedStorageBytesUsed: { type: Number, default: 0 },
 salt : String,
 salt1 : String,
 temp_str: String,
 active: { type: Boolean, default: false },
 disabled: { type: Boolean, default: false },
 emailReg: { type: Boolean, default: false },
 regPending: { type: Boolean, default: false },
 emailChangePending: { type: Boolean, default: false },
 regCodeSendCount: { type: Number, default: 0 },
 trialStartDate: Date,
 signUpDate: Date,
 passwordResetDate: Date,
 lastLoginDate: Date,
 lastModifiedDate: Date,
 curLoginDate: Date,
 curIpAddr: { ipType: String, 
 upper64: Schema.Types.Long,
 lower64: Schema.Types.Long },
 firstName: String,
 lastName: String,
 address: { streetAddress: String,
 city: String,
 state: String, postalCode: String },
 phoneNumbers: [ phoneNumbersSchema ],
 categories: [ categoriesSchema ],
 providerCustomers: [ customerSchema ],
 serviceProviders: [ providerSchema ],
 ipAddrs: [ ipAddrSchema ],
 recentUploads: [ recentUploadSchema ],
 recentUploadsGizmo: [ recentUploadSchema ],
 recentUploadsLife: [ recentUploadSchema ],
 recentUploadsVehicle: [ recentUploadSchema ],
 recentUploadsMisc: [ recentUploadSchema ],
 recentViews: [ recentViewsSchema ],
 recentAdds: [ recentAddsSchema ],
 locations: [ locationSchema ],
 inMessages: [ inMessageSchema],
 outMessages: [ outMessageSchema ]
});
 
module.exports = mongoose.model('users', userSchema); 

---- On Sat, 01 Oct 2016 15:09:56 -0700 Valeri Karpov &lt;notifications@github.com&gt; wrote ---- 

It should work, can you show me what your schema looks like?

**Comment by stevenelson74708** [comment]
The schema used is below:    

    `var mongoose = require('mongoose');
     require('mongoose-long')(mongoose);

     var Schema = mongoose.Schema;

     var phoneNumbersSchema = new Schema( {_id: false, type: String, number: String, primary: Boolean} );
     var categoriesSchema = new Schema( {_id: false, categoryId: Schema.Types.ObjectId} );
     var customerSchema = new Schema( {_id: false, firstName: String, lastName: String, phoneNumbers: [phoneNumbersSchema] , userId: Schema.Types.ObjectId} );
     var providerSchema = new Schema( {_id: false, providerName: String, providerId: Schema.Types.ObjectId} );
     var ipAddrSchema = new Schema( {_id: false, ipType: String, useCount: Number, upper64: Schema.Types.Long, lower64: Schema.Types.Long, lastUsedDate: Date} );
     var locationSchema = new Schema( {_id: false, location: { type: { type: String, default: 'Point' }, coordinates: [Number] }, accessDate: Date,  accessType: String} );
     var inMessageSchema = new Schema( {_id:false, date: Date, fromUserId: Schema.Types.ObjectId, fromEmail: String, read: { type: Boolean, default: false }, deleted: { type: Boolean, default: false }, subject: String, message: String} );
     var outMessageSchema = new Schema( {_id:false, date: Date, toUserId: Schema.Types.ObjectId, toEmail: String, deleted: { type: Boolean, default: false }, subject: String, message: String} );
     var recentUploadSchema = new Schema( {_id: false, uploadDate: Date, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
     var recentViewsSchema = new Schema( {_id: false, viewDate: Date, viewCount: Number, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
     var recentAddsSchema = new Schema( {_id: false, addDate: Date, addCount: Number, categoryId: Schema.Types.ObjectId, itemId: Schema.Types.ObjectId, itemName: String });

     var userSchema = mongoose.Schema({ 
	     token : String,
	     email: String,
         userName: String,
	     deviceId: String,
	     devicePhoneNumber: String, 
	     hashed_password: String, 
	     hashed_admin_code: String,
         maxStorageByteLimit: { type: Number, default: 1073741824 },
         accessLevel: { type: Number, default: 2 },
         lastAccessType: Number,
         storageBytesUsed: { type: Number, default: 0 },
         totalStorageBytesUsed: { type: Number, default: 0 },
         deletedStorageBytesUsed: { type: Number, default: 0 },
	     salt : String,
	     salt1 : String,
	     temp_str: String,
         active: { type: Boolean, default: false },
         disabled: { type: Boolean, default: false },
         emailReg: { type: Boolean, default: false },
         regPending: { type: Boolean, default: false },
         emailChangePending: { type: Boolean, default: false },
         regCodeSendCount: { type: Number, default: 0 },
         trialStartDate: Date,
	     signUpDate: Date,
	     passwordResetDate: Date,
	     lastLoginDate: Date,
         lastModifiedDate: Date,
	     curLoginDate: Date,
	     curIpAddr: { ipType: String, 
             upper64: Schema.Types.Long,
             lower64: Schema.Types.Long },
         firstName: String,
         lastName: String,
         address: { streetAddress: String,
             city: String,
             state: String, postalCode: String },
         phoneNumbers: [ phoneNumbersSchema ],
         categories: [ categoriesSchema ],
         providerCustomers: [ customerSchema ],
         serviceProviders: [ providerSchema ],
         ipAddrs: [ ipAddrSchema ],
         recentUploads: [ recentUploadSchema ],
         recentUploadsGizmo: [ recentUploadSchema ],
         recentUploadsLife: [ recentUploadSchema ],
         recentUploadsVehicle: [ recentUploadSchema ],
         recentUploadsMisc: [ recentUploadSchema ],
         recentViews: [ recentViewsSchema ],
         recentAdds: [ recentAddsSchema ],
         locations: [ locationSchema ],
         inMessages: [ inMessageSchema],
         outMessages: [ outMessageSchema ]
     });
     module.exports = mongoose.model('users', userSchema);  `

**Comment by stevenelson74708** [comment]
The code that simply pushes an element into the array when the array is not at max size, shown below, continues to work properly using versions 4.6.0 and 4.6.1 as it always has in earlier versions. It's only the code that attempts to replace an element, when the array is at max size, that fails using versions 4.6.0 and 4.6.1 while working properly with earlier versions. 
               
               `if (users[0].locations.length < constants.maxLocationsArraySize)
                {
                    // Array is not at max size, push locationInfo element to array
                    //noinspection JSUnresolvedFunction
                    user.findOneAndUpdate(
                        {"_id": userId},
                        {$push: {"locations": locationInfo}},
                        function (err1, model)
                        {
                            if (model == null)
                            {
                                wlogger.warn("model = null -- unable to store "
                                    + "location Info for UserId: "
                                    + userId);
                                callback({"response": false});
                            }
                            else if (err1 == null)
                            {
                                wlogger.debug("Location Info added for UserId: "
                                    + userId);
                                callback({"response": true});
                            }
                            else if (model.length != 0)
                            {
                                wlogger.warn("Unable to store location info for "
                                    + "UserId: " + userId + " -- model = "
                                    + model);
                                callback({"response": false});
                            }
                            else
                            {
                                wlogger.error(err1
                                    + " unable to store location info"
                                    + " for UserId: " + userId);
                                callback({"response": false});
                            }
                        });
                }
                else
                {
                     // Array is at max size, find oldest element and replace
                     <the code shown in the initial post resides here>
                }`

**Comment by vkarpov15** [comment]
Yeah the below script fails for me in 4.6.1, but works in 4.6.2. Try upgrading to 4.6.2 and it should work.

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4582');
mongoose.set('debug', true);

var locationSchema = new Schema({
  _id: false,
  location: { type: { type: String, default: 'Point' }, coordinates: [Number] },
  accessDate: Date,
  accessType: String
});

var testSchema = new Schema({
  locations: [locationSchema]
});

var T = mongoose.model('Test', testSchema);

var t = new T({
  locations: [{
    location: { type: 'Point', coordinates: [-122, 44] },
    accessDate: Date.now()
  }]
});

t.save().
  then(t => T.findByIdAndUpdate(t._id, { $set: { 'locations.0': { location: { type: 'Point', coordinates: [-123, 45] } } } }, { new: true })).
  then(res => {
    console.log('done', res.locations[0]);
    process.exit(0);
  }).
  catch(error => {
    console.error('error', error);
    process.exit(-1);
  });
```
