### ISSUE TITLE
Virtual Populate localField array

### ISSUE THREAD

**Issue by thatisuday** [Automattic/mongoose#4585]
I am using mongoose v4.5.3
I am not sure if there is any functionality to take localField as array of ids to map against foreignField.

Let's say I have  localField as `tags` which is array of tag ids in `tags` collection identified by tagId.

```
_id : xxx,
tags : ['tagId1', 'tagId2', 'tagId3'],
...
``

So my virtual populate declaration in schema will be

```

mySchema.virtual('tagsDocuments', {
 ref : 'Tag', // model
 localField : 'tags',
 foreignField : 'tagId'
})

```

Can we add feature for this?
```

**Comment by vkarpov15** [comment]
Not sure I understand your question, can you please clarify?

**Comment by thatisuday** [comment]
@vkarpov15 

Ok. Let's say I have two collections. `blog_posts` and `tags`. Tags are hashtags that can be added to a blog post.

Schema for a `tag` document is 
```
var tagSchema = new mongoose.Schema({
  name : String,
  tagId : {type:String, unique:true}
});
```

Schema for a `blog post` document is
```
var blogPostSchema = new mongoose.Schema({
  name : String,
  body: String,
  tags : [String]
});
```

Now let's populate tags with few mock documents
```
{
  name : 'angular.js`,
  tagId : 'angular`
},
{
  name : 'node.js',
  tagId : 'node'
},
{
  name : 'javascript',
  tagId : 'javascript'
}
```

Now let's add a blog post
```
{
  title : 'This is first blog post on angular js',
  tags : ['angular', 'javascript']
}
``

As you can see, `tags` in `post` document are array of `tagId`. Now when I will use virtual populate to populate tags document, I can not use `tags` as `localField` to match against `tagId` which is `foreignField` because mongoose map `string:string` not `array:string`.

What I was asking is, if `localField` is type of string array, map each value against `foreignField`

Did you get it?

**Comment by vkarpov15** [comment]
Yeah I see what you mean. To work around this, you can just use

```javascript

**Comment by himanshu1691** [comment]
I cant get this to work.
Can someone please check: http://stackoverflow.com/questions/43882577/mongoosejs-virtual-populate

**Comment by vkarpov15** [comment]
:point_up: is already answered on SO

**Comment by edgesinghkataria** [comment]
Hey,
I'm trying to achieve some what same result.
`
const UserChatSchema = new Schema(
  {
    cID: { type: ObjectId, required: true },
    bucket: { type : Number, required: true },
    count: { type : Number, required: true },
  }
);

const ChatListSchema = new Schema(
  {
    _id: { type: ObjectId,  required: true }, 
    type: { type: String, required: true, },
  }
);

const UserSchema = new Schema(
  {
    playerID: { type: String, required: true, trim: true },
    chats: [ChatListSchema],
  }
);

UserSchema.virtual('tests', {
  ref: 'userchats',
  localField: 'chats._id',
  foreignField: 'cID'
});

const UserModel = mongoose.model('users', UserSchema);
const UserChatModel = mongoose.model('userchats', UserChatSchema);
`
In UserSchema chats is an array of objects that has an _id field which needs to be mapped to the the 'cID' field in UserChatSchema.
I have tried the above approach but it didn't work
Any idea how can we get this to work
Thanks in advance

**Comment by vkarpov15** [comment]
@edgesinghkataria the below script shows `tests` getting populated successfully. Please modify the below script to demonstrate your issue.

```javascript
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

run().catch(err => console.log(err));

async function run() {
  const UserChatSchema = new Schema(
  {
    cID: { type: mongoose.ObjectId, required: true },
    bucket: { type : Number, required: true },
    count: { type : Number, required: true },
  }
);

const ChatListSchema = new Schema(
  {
    _id: { type: mongoose.ObjectId,  required: true },
    type: { type: String, required: true, },
  }
);

const UserSchema = new Schema(
  {
    playerID: { type: String, required: true, trim: true },
    chats: [ChatListSchema],
  }
);

UserSchema.virtual('tests', {
  ref: 'userchats',
  localField: 'chats._id',
  foreignField: 'cID'
});

const UserModel = mongoose.model('users', UserSchema);
const UserChatModel = mongoose.model('userchats', UserChatSchema);

  const id = new mongoose.Types.ObjectId();

  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();
  await UserChatModel.create({ cID: id, bucket: 1, count: 1 });
  await UserModel.create({ playerID: 'test', chats: [{ _id: id, type: 'foo' }] });

  const doc = await UserModel.findOne().populate('tests');
  console.log(doc.tests);
}
```

**Comment by Namchee** [comment]
All of the cases here refers to `array of IDs` in virtualized-schema to `ID` in reference schema. But, what if I have the opposite case?

Example:

Announcement Schema
```
const announcementSchema = new Schema({
  title: {
    type: String,
    trim: true,
    unique: true,
    required: true,
    maxlength: 25,
  },

  content: {
    type: String,
    trim: true,
    required: true,
    maxlength: 500,
  },

  validUntil: {
    type: Date,
    required: true,
  },

  important: {
    type: Boolean,
    default: false,
  },

  categories: {
    type: [Schema.Types.ObjectId],
    ref: 'Category',
    default: [],
  },
});
```

Category Schema
```
const categorySchema = new Schema({
  name: {
    type: String,
    trim: true,
    required: true,
    index: true,
    maxlength: 50,
  },

  desc: {
    type: String,
    trim: true,
    required: true,
    maxlength: 250,
  },
});

categorySchema.virtual('announcementCount', {
  ref: 'Announcement',
  localField: 'id',
  foreignField: 'categories',
  count: true,
});
```

I've tried the above solution, but I keep getting `undefined` when I tried to access `announcementCount` after populating it.

**Comment by vkarpov15** [comment]
@Namchee your `announcementCount` virtual should work fine. Please open up a new issue and follow the issue template :+1:
