### ISSUE TITLE
MongoError: Authentication failed

### ISSUE THREAD

**Issue by yankouskia** [Automattic/mongoose#4587]
I have mongodb in mongolab.
If I connect to it by command 
```js
mongo uri/$db -u user -p pass
```
it is ok.
If I use mongoose and connect by 
```js
mongoose.connect('mongodb://${user}:${pass}@${uri}/${db}')
```
I have error
```js
MongoError: Authentication failed
```

I use mongoose `4.6.1`

**Comment by yankouskia** [comment]
Also, I have checked - bug is not reproduced in `4.4.20` version.

**Comment by vkarpov15** [comment]
Do your username and password include any non alphanumeric characters? Similar issues have surfaced in the past with handling characters like : in passwords

**Comment by vkarpov15** [comment]
Also, what version of mongoose and mongodb?

**Comment by yankouskia** [comment]
Mongodb 'v3'
No, there is no non-alphanumeric symbols.

**Comment by vkarpov15** [comment]
Hmm also what database is the user defined on? MongoDB users are scoped to dbs, even if they have cross-db privileges, so if the user you have isn't defined on `db` you'll need to put something like `mongoose.connect('mongodb://${user}:${pass}@${uri}/${db}?authSource=admin')` if the user is defined on the 'admin' db.

Also, if you're on mongodb 3.x, you might be using SCRAM-SHA-1 auth or not. Try both of the below:

* `mongoose.connect('mongodb://${user}:${pass}@${uri}/${db}?authMechanism=SCRAM-SHA-1')`
* `mongoose.connect('mongodb://${user}:${pass}@${uri}/${db}?authMechanism=MONGODB-CR')`

**Comment by yankouskia** [comment]
Yes, it helped! Thank you very much!

**Comment by AlexeyRomanchenko** [comment]
I have made connection to cloud.mongodb.com with node.js but I don't understand why and how I made 2 successful connections but other times connections were unsuccessfull .
![image](https://user-images.githubusercontent.com/12534662/31762751-df663fc2-b4c4-11e7-916f-641118160b2b.png)

**Comment by xiaoxiekeke** [comment]
i tryed it , but not work,

mongoose v4.5.3
mongodb v3.4.7

errMsg：
`MongoError: Authentication failed.
14|gougouS |     at Function.MongoError.create (/www/website/gougouServer/source/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)`

**Comment by alikarimii** [comment]
just add `?authSource=yourDB&w=1` to end of db url

 `mongoose.connect('mongodb://user:password@host/yourDB?authSource=yourDB&w=1')`
this work for me . `&w=1` is important

**Comment by phamthephuc** [comment]
> just add `?authSource=yourDB&w=1` to end of db url
> 
> `mongoose.connect('mongodb://user:password@host/yourDB?authSource=yourDB&w=1')`
> this work for me . `&w=1` is important

Thank you sir. :3 good answer
