### ISSUE TITLE
Model.find is not returning any document

### ISSUE THREAD

**Issue by bitf12a046** [Automattic/mongoose#4594]
Here is Model
`var mongoose=require('mongoose');
module.exports=mongoose.model('Photo',{ 
         "_created_at": Date
   
});`

One of document in collection Photo is 

`{
    "_id": "1Bv4UUV3E8",
    "_updated_at": {
        "$date": "2016-02-05T20:41:48.230Z"
    },
    "Image": "tfss-d064dd20-90a3-432a-8966-65d70649db31-photo.jpg",
    "_created_at": {
        "$date": "2016-02-05T20:41:47.658Z"
    }
}`
Here is my query to find all documents.
```
Photo.find({},function(err,result){
if(err)
console.log("Error in allPhoto");
res.json(result);
});
```

**Comment by ogaryu** [comment]
Me too, I'm using Model.find() to get all documents in a collection but returns time out error.
If I use Model.findOne(...) returns a correct document.

**Comment by swrocket** [comment]
I'm experiencing the same issue, but only against MongoDB 3.2.
Works fine against 3.0...

**Comment by swrocket** [comment]
Update.
Thanks to the patient help of one of the mLab guys, the issue is resolved.
It turns out that you have to have MongoDB driver version 2.10.x or higher.
I ran npm install mongodb --save followed by npm install mongoose --save and the driver was upgraded to 2.2.x
Now everything works
