### ISSUE TITLE
suggestion to detect array changes

### ISSUE THREAD

**Issue by jampy** [Automattic/mongoose#4597]
As described in the FAQ, direct changes to array elements are not detected by Mongoose:

> **Mongoose doesn't create getters/setters for array indexes**; without them mongoose never gets notified of the change and so doesn't know to persist the new value. The work-around is to use MongooseArray#set 

I wonder if this is due to performance concerns, because *technically* this should be possible to do.

You can create a *setter* for each numeric array index, like:

```javascript
function decorateIndex(arr, i) {
  var value = arr[i];
  Object.defineProperty(arr, i, {
    enumerable: true,
    configurable: true,
    get: function() {
      return value;
    },
    set: function(v) {
      console.log("** CHANGE DETECTED ** set index", i, "to", v);
      value = v;
    }
  });
}

function decorate(arr) {
  var n = arr.length;
  for (var i=0; i<n; i++) {
    decorateIndex(arr, i);
  }
}

var someArr = ["one", "two", "three"];
decorate(someArr);

someArr[1] = "a new value";
```

Of course this detects only changes of existing items and won't, for example, detect a `someArr.push(x)` operation.

However, I *guess* that Mongoose will *probably* update the *whole* array (to MongoDB) anyway when the array length changes (no matter if items added or removed), so that should make that restriction irrelevant. If not (Mongoose is able to detect appended items, for example), then I'd like to know the mechanism behind.

I have no clue if you guys have already thought of such a solution - just wanted to share an idea...

**Comment by vkarpov15** [comment]
So the reason why we don't do `Object.defineProperty()` on every existing array index is 2-fold. First, it's ungodly slow for large arrays. Second, it's perfectly valid to assign to array index 3 in an array of length 1 in JS, so we'd miss cases like that.

Long story short, if we support this it'll have to be through proxies.

**Comment by jampy** [comment]
> Second, it's perfectly valid to assign to array index 3 in an array of length 1 in JS, so we'd miss cases like that.

As said, in that situation you could detect indirectly that since the `.length` property changed.

But okay, the performance concerns are obviously valid.

**Comment by vkarpov15** [comment]
Yeah but unfortunately diffing 2 objects is antithetical to how mongoose does change tracking. Fundamentally mongoose assumes that it can intercept all changes to an object to avoid the really messy alternative of diffing objects.
