### ISSUE TITLE
square brackets in prehook

### ISSUE THREAD

**Issue by antonioaltamura** [Automattic/mongoose#4598]
Hi, I want to avoid mongoose empty array creation.

`
mySchema.pre('save', function (next) {
[   "item1",
        "item2",
        "item3",
        "item4"
        ].forEach(function (field) {
        if (this[field] && isEmpty (this[field]))
            this[field] = undefined;
    });
    next();
})
`

I cannot access to the fields using square brackets, how can I generalize this behaviour for multiple items?

**Comment by zbjornson** [comment]
I think your `this` reference is simply wrong...

Your code:
```js
mySchema.pre('save', function (next) {
  ["item1", "item2", "item3", "item4"].forEach(function (field) {
    // 'this' is undefined -> becomes global
    if (this[field] && isEmpty(this[field])) this[field] = undefined;
  });
  next();
}) 
```

Solution A:
```js
mySchema.pre('save', function (next) {
  ["item1", "item2", "item3", "item4"].forEach(function (field) {
    if (this[field] && isEmpty(this[field])) this[field] = undefined;
  }, this); // provide a context
  next();
}) 
```

Solution B
```js
mySchema.pre('save', function (next) {
  var _this = this; // reference this
  ["item1", "item2", "item3", "item4"].forEach(function (field) {
    if (_this[field] && isEmpty(_this[field])) _this[field] = undefined;
  });
  next();
}) 
```

Does that work?

**Comment by antonioaltamura** [comment]
both solution look like don't works
if I print
`console.log(this[field]);`
inside the forEach I get an empty array
`[]`

**Comment by zbjornson** [comment]
(Based on your indentation and what I understand of your goal, it looks like you're missing `{` `}` for your `if` block.)

Looking at [the source around that trace](https://github.com/Automattic/mongoose/blob/master/lib/types/documentarray.js#L233), it looks like the replaced value needs to be [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) in order for mongoose to not attempt to emit an event. Does it still fail with `undefined`?

**Comment by antonioaltamura** [comment]
Sorry for the `if` distraction :D
Anyway you're right about the value, with `undefined` it doesn't throw the error. But when I get the saved doc I still get the empty arrays on the fields item1,item2,item3..

```
    [   "item1",
        "item2",
        "item3"
        ].forEach(function (field) {
        if (this[field] && isEmpty (this[field])) {
            this[field] = undefined;
        }
    },this);
```

**Comment by vkarpov15** [comment]
You can just do `new Schema({ arr: { type: [String], default: void 0 } });` to avoid the default empty array creation for `arr`.
