### ISSUE TITLE
Mongoose makes node cluster unresponsive

### ISSUE THREAD

**Issue by itopenup** [Automattic/mongoose#4600]
Using 4.6.2 version of mongoose + actionhero in a cluster mode (it uses node.cluster).

Wrote a bash script which can make requests to my API many times in a loop.

Inside my API I just make find().populate() request. I can make 1, 10, 45 requests with minimal delay. But after 45-50 requests node cluster become unresponsive at all.

Tried remove population - everything works, can make 100, 10000, 100000 requests without population.

But if I run actionhero without cluster mode I can make requests with population as many as I want.

**Comment by vkarpov15** [comment]
Code samples please
