### ISSUE TITLE
Breaking change in 4.6.2: values passed to validator fns have a different prototype chain

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#4603]
Bisected to e42e5a0a2d22420f21d41a299cfd49aca4ef2e2e

Restoring these three lines fixes the problem:
https://github.com/Automattic/mongoose/commit/e42e5a0a2d22420f21d41a299cfd49aca4ef2e2e#diff-8ffefdea352a143d6aba70d2c1f4ce00L219
but I'm not comfortable submitting a PR to revert it because I don't know the overall goal of that change.

```js
it('does not add properties to the chain', function (done) {
  var db = start();

  function myValidator(val, cb) {
    assert(!('name' in zero)); // assertion failure
    console.log(Object.getOwnPropertyNames(val[0])); // see below
    console.log(Object.getOwnPropertyNames(Object.getPrototypeOf(val[0]))); // see below
    console.log('in', 'name' in val[0]); // since e42e5a0: true, before: false
    console.log('own', val[0].hasOwnProperty('name')); // false
    cb(true);
  }
  var A = new Schema({
    name: String,
    scale: {}
  });
  var B = new Schema({
    a: {
      type: [A], validate: {validator: myValidator}
    }
  });

  B = db.model('b', B);

  B.findOneAndUpdate(
    {foo: 'bar'},
    {$set: {a: [{scale: {z: 1}}]}}, // notice no 'name' in the update
    {new: true, runValidators: true},
    function (err, doc) {
      assert.ifError(err);
      db.close(done);
    });
});
```

Output from the `console.log`s in my example above:

| version | ownProperties | proto's ownProperties |
| --- | --- | --- |
| ad3dc70 (old) | `[ 'scale', '_id' ]` | `[ 'constructor', 'toString', 'toLocaleString', 'valueOf', 'hasOwnProperty', 'isPrototypeOf', 'propertyIsEnumerable', '__defineGetter__', '__lookupGetter__', '__defineSetter__', '__lookupSetter__', '__proto__' ]` |
| e42e5a0 (new) | `[ 'constructor', 'toString', 'toLocaleString', 'valueOf', 'hasOwnProperty', 'isPrototypeOf', 'propertyIsEnumerable', '__defineGetter__', '__lookupGetter__', '__defineSetter__', '__lookupSetter__', '__proto__' ]` | `[ 'id', '_id', 'scale', 'name', 'schema' ]` |

In particular, note that `'name'` (a property of the schema and not in the update) is now present in the chain, whereas it wasn't previously.

I know it's generally bad to use `in` instead of `hasOwnProperty` to test if a property is present on an object that I didn't create, so I understand if this is accepted as the correct behavior. Nonetheless, perhaps someone will find this issue useful if they hit the same problem.

**Comment by zbjornson** [comment]
Actually, re: my last paragraph, the new behavior breaks the use of `Object.hasOwnProperty` because there are now 12 (rather obscure) fields that cannot be used in mongoose schemas.

**Comment by vkarpov15** [comment]
Thanks for the detailed report, will take a look early next week

**Comment by vkarpov15** [comment]
The goal of this change was to address #4519, which requires us to cast objects in updates into full-fledged mongoose documents, which don't work too well with `hasOwnProperty()`. Unfortunately this behavior was not well defined before 4.6.2, but this new behavior is correct as far as mongoose is concerned. If you want the old behavior back, just use `.toObject()`:

```javascript
function myValidator(val, cb) {
    val = val.toObject();
    cb(true);
  }
```
