### ISSUE TITLE
Mongoose Document Object "name" attribute shouldn't be reserved?

### ISSUE THREAD

**Issue by jaredreich** [Automattic/mongoose#4605]
Reproduced like this:
```js
Cat.findById(id).exec((err, cat) => {
  console.log(cat) // { feels: 'fluffy', name: 'George', color: 'orange' }
  console.log(cat.feels) // fluffy
  console.log(cat.name) // undefined
  console.log(cat.get('name')) // George
  console.log(cat.color) // orange
})
```
Why do I have to use this specific syntax only for the attribute "name"?

**Comment by jaredreich** [comment]
Apparently this occurs only on subdocuments...

Like this:
```js
Human.findById(id).exec((err, human) => {
  const cat = human.cat
  console.log(cat) // { feels: 'fluffy', name: 'George', color: 'orange' }
  console.log(cat.feels) // fluffy
  console.log(cat.name) // undefined
  console.log(cat.get('name')) // George
  console.log(cat.color) // orange
})
```

**Comment by vkarpov15** [comment]
What does your data look like in mongodb and what does your schema look like?

**Comment by adambuczynski** [comment]
@jaredreich I have used the `name` property extensively, both on main schema's and also sub document schema's, and have not encountered this problem.

**Comment by jaredreich** [comment]
@adambuczynski fair enough. Not sure the root of why I'm experiencing this. Will investigate and re-open if I find anything. Thanks all.
