### ISSUE TITLE
Can't read property onOpen/onClose of null

### ISSUE THREAD

**Issue by vishalgakhare** [Automattic/mongoose#4606]
Mongoose version: 4.3.6
Usage: mongoose is used by nodejs rest API to connect to database. I also have a health check URL that creates separate mongoose connection to test DB connection. The health check runs every 5 minutes. The API and/or health check breaks intermittently with the below error. When health check breaks, the cloud environment kills the docker container and restarts it. 

Error message: cannot read property onOpen of null. (In local machine, when API is stopped with Control+C, it's onClose)

**Comment by vishalgakhare** [comment]
![img_2107](https://cloud.githubusercontent.com/assets/10359853/19179617/77676560-8c2d-11e6-8bb5-2e82b08f90b6.PNG)

**Comment by vkarpov15** [comment]
Please provide a code sample

**Comment by vishalgakhare** [comment]
**Configuration:**
`"database": {
    "Connection": {
      "uri": "mongodb://host1:port,host2:port/dbname",
      "options": {
        "db": {
          "native_parser": true
        },
        "server": {
          "poolSize": 10,
          "reconnectTries": 30,
          "reconnectInterval": 1000,
          "socketOptions": {
            "autoReconnect": true,
            "noDelay": true,
            "keepAlive": 120,
            "connectTimeoutMS": 0,
            "socketTimeoutMS": 0
          }
        },
          "auth": {
          "authdb": "admin"
          },
          "replset": {
             "rs_name": "replica"
          },
            "user": "user",
           "pass": "password"
          }
        }
     }`

**The NodeJS Api uses the dbConnection.js to connect to DB:**
`dbConnection.prototype.connect = function() {
    if ( db == null) {
      let dbPath = config.get('database.Connection.uri');
      let dbOptions = config.get('database.Connection.options');
      mongoose.connect(dbPath, dbOptions);
      db = mongoose.connection;
      db.on('connected',dbConnection.prototype.OnConnected);
      db.on('error',dbConnection.prototype.OnError);
      db.on('close', dbConnection.prototype.close);
      logger.log.info({time:util.getCurrentTimeStamp()},"DB instance is created");
    }
    return db;
};`

**The healthcheck creates separate DB connection in health/get route:**

`let healthCheck = function(req,res,next)
{
  req.log.info({"time": util.getCurrentTimeStamp()},"Started BizEventsApi Health Check...");
  return handlePromiseOperations(dbConnection.prototype.execution(eventMetaData.getCountForHealthCheck(req), req), res, next);
};`


`let handlePromiseOperations = function (promise, res, next) {
  return promise
    .then(function (result) {
      let response=[];
      response.push("Status: Alive");
      dbConnection.prototype.close();
      res.send(response);
      next(null);
    })
    .catch(function (error) {
      let response=[];
      let errDetails = JSON.stringify(error);
      response.push("Status: Inactive",  "error:" + errDetails");
      dbConnection.prototype.close();
      res.send(response);
      throw error;
    });
};`

**The model schema is shared between Api and health check. Mongoose allows only unique schema:**
`let getCountForHealthCheck= function getEventCount(req){
   return new Promise(function (resolve, reject) {
      eventMetaData.find().count(function(err,count){
      if(count)
      {
            return resolve(count);
      }
      return reject(err);
      });
  });
};`

Package Versions:
mongoose: 4.3.6

**Comment by vishalgakhare** [comment]
When trying to stop the app (CTRL+C):

`/Users/jsh371/Repos/BizEvents/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'onClose' of null
    at NativeConnection.Connection.onClose (/node_modules/mongoose/lib/connection.js:561:24)
    at /node_modules/mongoose/lib/connection.js:526:16
    at handleCallback (/node_modules/mongodb/lib/utils.js:96:12)
    at /node_modules/mongodb/lib/db.js:373:5
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
[ripe at 12:28] INFO Stopping node server for: undefined ℹ
`

**Comment by vkarpov15** [comment]
Are you closing in the same tick as opening? That could be one cause for this issue, I don't see where you're calling `connect()` or how you're interacting with the mongoose connection in your code.

**Comment by vishalgakhare** [comment]
Since I had backed out the health check code, I pulled it from the history. This is the entire JS file.
`
const eventMetaData = require('../../models/eventMetaData.js');
const mongoose = require("mongoose");
const config = require("config");

let db;

let dbConnection = function () {
  db = null;
};

dbConnection.prototype.close = function() {
  if (db) {
    db.close();
  }
};

dbConnection.prototype.connection= function(req){
  let dbPath = config.get('database.Connection.uri');
  let dbOptions = config.get('database.Connection.options');
  let dbConnection = JSON.parse(JSON.stringify(dbOptions));
  }
  return new Promise(function(resolve,reject){
    mongoose.connect(dbPath, dbConnection,function(err,result)
    {
      if(err)
      {
        req.log.info({"Health Check DB Connection failed:" + err);
        return reject(err);
      }
        req.log.info({"Health Check DB Connection successful:");
        return resolve(result);
    });
  });
};

dbConnection.prototype.execution = function(healthCheckFunction, req) {
  let self = this;
  let connection = self.connection(req);
  return connection.then(function(){
    healthCheckFunction.then(function(result)
    {
      return result;
    });
  }).catch(function(err){
    throw err;
  });
};

let handlePromiseOperations = function (promise, res, next) {
  return promise
    .then(function () {
      let response=[];
      response.push("Status: Alive","Database: Active);
      dbConnection.prototype.close();
      res.send(response);
      next(null);
    })
    .catch(function (error) {
      let response=[];
      let errDetails = JSON.stringify(error);
      response.push("Status: Alive", "Database: Failed" , "error:" + errDetails");
      dbConnection.prototype.close();
      res.send(response);
      throw error;
    });
};

let healthCheck = function(req,res,next)
{
  req.log.info({"Started Health Check...");
  return handlePromiseOperations(dbConnection.prototype.execution(eventMetaData.getCountForHealthCheck(req), req), res, next);
};
`
And the model:

let getCountForHealthCheck= function getEventCount(req){
   return new Promise(function (resolve, reject) {
      eventMetaData.find().count(function(err,count){
      if(count)
      {
        req.log.info("Success: Health Check call for getCountForHealthCheck: " + count);
        return resolve(count);

      }
        req.log.info("Failure: Health Check call for getCountForHealthCheck: " + err);
        return reject("error in Db connection");
      });
  });
};

**Comment by vkarpov15** [comment]
```
mongoose.connect(dbPath, dbConnection,function(err,result)
    {
      if(err)
      {
        req.log.info({"Health Check DB Connection failed:" + err);
        return reject(err);
      }
        req.log.info({"Health Check DB Connection successful:");
        return resolve(result);
    });
```

Why the 2nd parameter `dbConnection` there? Try removing that
