### ISSUE TITLE
Unsetting fields which don't exist on the schema

### ISSUE THREAD

**Issue by adambuczynski** [Automattic/mongoose#4612]
I ran into an issue where I was needing to run a data migration and had to unset some old fields that were not present on the model anymore. I used the approach:

```js
User.update({}, {$unset: {someField: 1}}, {multi: true})
```

However, it seems that because the field wasn't present in the model schema anymore, Mongoose refused to carry out this query and never processed any documents. 

When I processed them one by one and manually set the field to undefined:

```js
user.someField = undefined;
user.save();
```

That did get rid of them, but for the multi update I had to resort to accessing the underlying collection directly, e.g.:

```js
User.collection.update({}, {$unset: {someField: 1}}, {multi: true})
```

That eventually did the trick.

Is it expected behaviour that Mongoose will not carry out `$unset` operations on fields it doesn't "know" of in the schema? I tested it a bit more and it seems to also affect `$set` operations for fields that aren't on the schema.

**Comment by vkarpov15** [comment]
Yep that's expected. Try turning off strict mode in your update and it should work though:

```javascript
User.update({}, {$unset: {someField: 1}}, {multi: true, strict: false});
```

**Comment by adambuczynski** [comment]
Ok thanks

**Comment by goldylucks** [comment]
The proposed solution didn't work for me, so I ended up using this:

```
const fields = ["admin"];
const unset = fields.reduce(
  (acc, field) => ({
    ...acc,
    [field]: 1,
  }),
  {}
);

YourModel.collection.updateMany(query, { $unset: unset });
```
