### ISSUE TITLE
Array field default value 0 returns empty array

### ISSUE THREAD

**Issue by EricMcRay** [Automattic/mongoose#4620]
When you set 0, false or empty string to array field's default, it returns empty array.

Examples:

```
new Schema({
arrayX: { type: Array, default: 0},
arrayFalse: { type: Array, default: false},
arrayString: { type: Array, default: ""}
})
```

I tried to fix but tests for gh-2562 failed. But you can hack that bug with default function

```
new Schema({
arrayX: { type: Array, default: function(){ return 0 }}
})
```

Line: https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L87

**Comment by MOM** [comment]
+1, thanks for the hack

**Comment by vkarpov15** [comment]
What would the expected behavior be in this case? An array with a single element which is the number 0? Really strange edge case

**Comment by EricMcRay** [comment]
@vkarpov15 yes, it is. I wanted to tag users with numbers and 0 was the default global tag. I did it like shown in documentation and It didnt work. I was losing my mind then I decided to debug mongoose code and find that line.

I know this can hard to fix cuz can affect lot of thing. Even if you don't want to fix this, maybe you can add this as a note to documentation. 👍
