### ISSUE TITLE
Schema attribute lowercase: false does the same as lowercase: true

### ISSUE THREAD

**Issue by vtni** [Automattic/mongoose#4622]
I expect that the option `lowercase: true` in a field of type String will convert it into lowercase. On the other hand I expect that `lowercase: false` doesnt't convert it.
But actually it doesn't matter what value you hand in. If the `lowercase` value is set, it is always casted to lowercase.
I wrote a fix for this, but it would be nice, if you can change it, too (in `mongoose/lib/schema/string.js`)

```
SchemaString.prototype.lowercase = function() {
  return this.set(function(v, self) {
    if (typeof v !== 'string') {
      v = self.cast(v);
    }
    if (self.options.lowercase && v) {
      return v.toLowerCase();
    }
    return v;
  });
};
```

The same problem has `uppercase`.

**Comment by nomankt** [comment]
1+
