### ISSUE TITLE
Schema field's default function not being called properly when imported from module

### ISSUE THREAD

**Issue by newhouse** [Automattic/mongoose#4623]
Seemingly out of the blue (I think it was working as-expected before), I'm having an issue when using a function from another module as the default for a field on a schema. I've played around with it for a while now and it's exhibiting some really odd behavior, which is why I'm posting.
- Note 1: I'm using `mongoose-fill` in some places, though I can't pinpoint whether that has anything to do with it and it's too late to rip it out to test. I'm going to assume it has nothing to do with this.
- Note 2: I do have some `pre('save'...` stuff going on, but as you'll see below it doesn't seem to be the issue.

Here's the relevant code:

helper.js:

```
...
exports.now = function() {
  console.log("in NOW");
  return new Date();
}
...
```

user.js

```
const mongoose = require('mongoose-fill');
const helpers = require('../helpers/helpers');

var UserSchema = new mongoose.Schema({
  created: {
    type: Date,
    default: helpers.now,
    required: true
  }
});

module.exports = mongoose.model('User', UserSchema);
```

elsewhere:

```
let user = new User();
user.save(function(err, user) {
...
});
```

Here's the thing: when I run this code as I have it above, I get an error that validation failed on `created`. However, if I change the default on `created` to `default: function() { return helpers.now(); },` it works fine. If a create a local function `var myNow = function() { return helpers.now(); }` in `user.js` and use it on `created` like so `default: myNow,`, it also works fine. It just doesn't seem to want to call `helpers.now` directly as a function.

**Comment by vkarpov15** [comment]
Thats strange. Which version of node and are you using plain old require() or something fancier?

**Comment by vkarpov15** [comment]
Also, what does the validation error look like?

**Comment by newhouse** [comment]
Hi Valeri and sorry for the late reply. I was using node 6.6.0 and plain old `require`. I'm sorry, but I can't provide any more information as we've switched from Mongo/Mongoose to PostgreSQL/ObjectionJS for this project so that code's long gone.  Mongoose was really useful, but the heart of the project did not require Mongo - I think I'll be back for other parts of the application so thank you and keep up the good work on Mongoose!

**Comment by vkarpov15** [comment]
Thanks, best of luck :+1:
