### ISSUE TITLE
RFC: Updating existing indexes

### ISSUE THREAD

**Issue by davidkaneda** [Automattic/mongoose#4644]
I know mongoose calls `ensureIndexes` as a background op, but it seems like this only creates indexes that don't exist, it never actually "updates" existing resources. So any variation of: Adding a new field to a text index, taking an existing index and adding (or removing) "unique," or removing an index, requires dropping all indexes and calling ensureIndexes from that state.

It seems like this would inherently mean downtime as we'd be unable to serve the app while this was happening (and we'd also have to stagger it so we drop the indexes, then launch the app so ensureIndexes is called).

I'm sure there must a better way... What are best practices here? Also: Very sorry if this is the wrong place to post, happy to move if someone has a better recommendation-

**Comment by vkarpov15** [comment]
There isn't really a better way because mongodb doesn't support modifying existing indexes as far as I know. You can drop just one index and then rebuild it as necessary, but I wouldn't rely on mongoose to manage your production indexes
