### ISSUE TITLE
findOneAndUpdate does not include newly saved virtuals in populated result

### ISSUE THREAD

**Issue by linusbrolin** [Automattic/mongoose#4646]
I have a parent schema that has a virtual array of a child schema.
The virtual docs are saved separately into the children collection, and then I have a post middleware that sets the parent id to each child when the parent is saved.
However, even though the post middleware completes before findOneAndUpdate does, it still doesn't include newly added children into the resulting parent document.
So I have to do another findOne on the parent after findOneAndUpdate has finished, in order to get all the virtual children.

Below is some example code that demonstrates the issue:

    var mongoose = require('mongoose');

    const ChildSchema = new mongoose.Schema({
      _id: Number,
      childtest: String,
      parent: { type: Number, ref: 'Parent' }
    });

    var ChildModel = mongoose.model('Child', ChildSchema);

    const ParentSchema = new mongoose.Schema({
      _id: Number,
      test: String
    }, {
      toObject: { virtuals: true },
      toJSON: { virtuals: true }
    });

    ParentSchema.virtual('children', {
      ref: 'Child',
      localField: '_id',
      foreignField: 'parent'
    });

    ParentSchema.post('findOneAndUpdate', function(doc, next) {
      if (this._update && this._update['children']) {
        ChildModel
          .update(
            { _id: { $in: this._update['children'] } },
            { parent: doc._id },
            { multi: true }
          )
          .exec((err, res) => {
            console.log('childs parent ref updated');
            return next();
          });
      }
      else {
        next();
      }
    });

    var ParentModel = mongoose.model('Parent', ParentSchema);

    var c = {
      _id: 1,
      childtest: 'child test1',
      parent: 1
    };

    ChildModel
      .findByIdAndUpdate(c._id, c, { upsert: true, setDefaultsOnInsert: true, new: true })
      .lean()
      .exec((err, cres) => {
        if (err) {
          console.log('child1 err: ' + err);
          return;
        }
        console.log('child1 saved:');
        console.dir(cres);

        var p = {
          _id: 1,
          test: 'parent test1'
        };

        ParentModel
          .findByIdAndUpdate(p._id, p, { upsert: true, setDefaultsOnInsert: true, new: true })
          .populate('children')
          .lean()
          .exec((err, pres) => {
            if (err) {
              console.log('parent err: ' + err);
              return;
            }
            console.log('parent saved:');
            console.dir(pres);

            var c2 = {
              _id: 2,
              childtest: 'child test2'
              // note: no parent ref yet
            };

            ChildModel
              .findByIdAndUpdate(c2._id, c2, { upsert: true, setDefaultsOnInsert: true, new: true })
              .lean()
              .exec((err, cres2) => {
                if (err) {
                  console.log('child2 err: ' + err);
                  return;
                }
                console.log('child2 saved:');
                console.dir(cres2);

                var p2 = pres;
                p2.test = 'parent test2';

                if (!p2.children) {
                  p2.children = [];
                }

                p2.children.push(cres2);

                ParentModel
                  .findByIdAndUpdate(p2._id, p2, { upsert: true, setDefaultsOnInsert: true, new: true })
                  .populate('children')
                  .lean()
                  .exec((err, pres2) => {
                    if (err) {
                      console.log('parent err: ' + err);
                      return;
                    }
                    console.log('parent re-saved:');
                    console.dir(pres2); // child2 not included, even though its parent ref was updated before we got here

                    ParentModel
                      .findById(pres2._id)
                      .populate('children')
                      .lean()
                      .exec((err, pres3) => {
                        if (err) {
                          console.log('parent err: ' + err);
                          return;
                        }
                        console.log('parent re-loaded:');
                        console.dir(pres3); // both children included, like they should
                      });
                  });
              });
          });
      });

**Comment by vkarpov15** [comment]
So the issue is that your `post('findOneAndUpdate')` middleware happens _after_ mongoose populates, because when you do `.findByIdAndUpdate().populate()` then populate is a part of the `findOneAndUpdate` operation, and there's no way to say "do this operation after findOneAndUpdate but before populate".

Since you're using lean(), you'll want to manually do populate after the `findOneAndUpdate` is done:

```javascript
ParentModel
              .findByIdAndUpdate(p2._id, p2, { upsert: true, setDefaultsOnInsert: true, new: true })
              .populate('children')
              .lean()
              .exec((err, pres2) => {
                if (err) {
                  console.log('parent err: ' + err);
                  return;
                }
                console.log('parent re-saved:');
                console.dir(pres2); // child2 not included, even though its parent ref was updated before we got here

                ParentModel
                  .populate(pres2, [{ path: 'children', options: { lean: true } }], (err, pres3) => {
                    if (err) {
                      console.log('parent err: ' + err);
                      return;
                    }
                    console.log('parent re-loaded:');
                    console.dir(pres3); // both children included, like they should
                  });
              });
```

**Comment by linusbrolin** [comment]
@vkarpov15 thanks for the quick response!
Too bad that it can't be fixed, but I guess I can live with the manual population.
But in my project I need to populate more than one field and some of them may be nested aswell, where the populateoptions are retrieved from each models service, so having to put `options: { lean: true }` on every path is not really an option for me.
So unless I can do a `lean()` after the `.populate(options)` I guess I'll have to stick with doing the `.findById(id).populate(opts).lean()` method..

**Comment by vkarpov15** [comment]
Another way would be to manually update `ChildModel` after `findOneAndUpdate()`. Or you could skip using `lean()` and populate the doc afterwards.

**Comment by linusbrolin** [comment]
@vkarpov15 Would it be possible to make this work?

    ParentModel
      .populate(obj)
      .lean()
      .exec();

I need `lean()`, because I need the entire populated object (every path) to be a regular json object, without having to do `options: { lean: true }` manually on every path.

**Comment by vkarpov15** [comment]
If you're not using `lean()` for performance reasons I'd recommend just doing

```javascript
ParentModel
  .populate(obj)
  .exec(function(error, doc) {
    doc.toObject({ depopulate: false }); // <-- make sure to unset depopulate option
  });
```

I don't know off the top of my head whether lean propagates down to all populates or not but generally if you're doing a lot of populates you're not really starving for extra performance and so you don't really need `lean()`

**Comment by linusbrolin** [comment]
That seems to work. Thanks!
