### ISSUE TITLE
Is it possible to access static methods of sub/nested documents?

### ISSUE THREAD

**Issue by kdmon** [Automattic/mongoose#4648]
I'm trying to access a static method belonging to a sub-document (``getAuthenticated()``, part of the User schema). 

Company is the root schema and pulls in the User schema. I have an authentication middleware where I want to do something like: Company.users.getAuthenticated(...), but users (and getAuthenticated) are undefined. Any pointers are highly appreciated!

models/user.js:
```
[---]
var UserSchema = new mongoose.Schema({
  created:       { type: Date, default: Date.now },
  username:      { type: String, required: true, unique: true},
  email:         { type: String, required: true, unique: true, lowercase: true, trim: true},
  password:      { type: String, required: true}
});

[---] 

UserSchema.statics.getAuthenticated = function(username, password, cb) {
  this.findOne({ username: username }, function(err, user) {
    if (err) return cb(err);

    // make sure the user exists
    if (!user) {console.log ("not found");}
   }
}
[---] 

module.exports = UserSchema;

```

models/company.js:

```
[---]
var UserSchema     = require('./user');
var CompanySchema = new mongoose.Schema({
  name: {type: String, required: true},
  users: [UserSchema]
});

module.exports = mongoose.model('Company', CompanySchema);

```

middleware/authentication.js:

```
[---]
var Company       = require('../models/company');

passport.use('userAuthentication', new LocalStrategy(
  function(username, password, cb) {
    Company.users.getAuthenticated(username, password, function (err, user) {
      console.log (err);
      if (err) { return cb(err); }
      if (!user) { return cb(null, false); }
      return cb(null, user);
    });
  })
);
[---]
```

**Comment by vkarpov15** [comment]
No it isn't really possible, and what you're trying to do doesn't quite make sense because, since `users` is an embedded property of a `company`, you can't really do `findOne()` on a user. If you want to do this, I recommend you store `users` in a separate collection and use `populate()`

**Comment by kdmon** [comment]
Thank you very much for clarifying and explaining the issue. It makes sense. Separate collections and ``populate()`` is what I'll revert to.
