### ISSUE TITLE
`.distinct(field, query).stream()` is converted to `.find()` ?

### ISSUE THREAD

**Issue by mreinstein** [Automattic/mongoose#4649]
given this mongoose model query:

```javascript
const query = { userId: 'def68b7da77c883538f5dbfb', template: { $ne: 1 } }
const projectIdStream = MyModel.distinct('projectId', query).stream()
```

when I enable `mongoose.set('debug', true)`, in the logs I see that this query is turned into this:

```bash
Mongoose: ProjectHosts.find({ template: { '$ne': 1 }, userId: ObjectId("def68b7da77c883538f5dbfb") }) { fields: undefined
12:27:17 PM web.1       |  >  39m }  

```

can anyone explain why this is happening ? I don't see anything in the mongoose  docs about this

**Comment by vkarpov15** [comment]
`.stream()` forces you to use `.find()`, because you can't `stream()` a `distinct`, `findOne`, `count`, etc. currently.

**Comment by onur2677** [comment]
But why ?

**Comment by vkarpov15** [comment]
@onur2677 because the MongoDB server doesn't support it.
