### ISSUE TITLE
manually 'populating' a virtual field with .set on a new model does not set the field value in '_doc'

### ISSUE THREAD

**Issue by linusbrolin** [Automattic/mongoose#4657]
I need a way to reliably have access to populated virtual fields in post update middleware.
So far, I'm checking `this._update` in the post middleware, and that works fine as long as the object sent to mongodb had the virtual fields populated.
But if I want to create a new object by calling `new Model(obj)`, then all the populated virtual fields are removed from the new object.
And so far, I have only managed to repopulate them by using the internal `setValue` api.

Below is code for demonstrating the problem.
In the examples below, only `parent1` and `parent4` will have the `children` field populated, and thus only those two will be able to set the `parent` field in the post `findOneAndUpdate` middleware.

`parent1` is a regular javascript object. This works, but I cannot make a new mongoose doc with an autogenerated id this way.

`parent2` is created with `new ParentModel(obj)`. This does not work.

`parent3` is created with `new ParentModel(obj)` and uses the public `set` api to repopulate the virtual fields, but the values are not available in `_update` or `_doc`. This does not work.

`parent4` is created with `new ParentModel(obj)` and uses the internal `setValue` api to repopulate the virtual fields. This works.

    var mongoose = require('mongoose');

    const ChildSchema = new mongoose.Schema({
      _id: Number,
      label: String,
      parent: { type: Number, ref: 'Parent' }
    });

    var ChildModel = mongoose.model('Child', ChildSchema);

    const ParentSchema = new mongoose.Schema({
      _id: Number,
      label: String
    }, {
      toObject: { virtuals: true },
      toJSON: { virtuals: true }
    });

    ParentSchema.virtual('children', {
      ref: 'Child',
      localField: '_id',
      foreignField: 'parent'
    });

    ParentSchema.post('findOneAndUpdate', function(doc, next) {
      if (!this._update) {
        return next();
      }
      console.log('post findOneAndUpdate: this._update for: ' + this._update['label'] + ', has children field: ' + this._update.hasOwnProperty('children'));

      if (this._update['children']) {
        ChildModel
          .update(
            { _id: { $in: this._update['children'] } },
            { parent: doc._id },
            { multi: true }
          )
          .exec((err, res) => {
            console.log('childs parent ref updated');
            return next();
          });
      }
      else {
        next();
      }
    });

    var ParentModel = mongoose.model('Parent', ParentSchema);

    // parent1 test

    var c = {
      _id: 1,
      label: 'child1'
    };

    ChildModel
      .findByIdAndUpdate(c._id, c, { upsert: true, setDefaultsOnInsert: true, new: true })
      .lean()
      .exec((err, cres) => {
        if (err) {
          console.log('child1 err: ' + err);
          return;
        }
        console.log('child1 saved:');
        console.dir(cres);

        var children = [];
        children.push(cres);

        var p = {
          _id: 1,
          label: 'parent1',
          children: children
        };

        ParentModel
          .findByIdAndUpdate(p._id, p, { upsert: true, setDefaultsOnInsert: true, new: true })
          .lean()
          .exec((err, pres) => {
            if (err) {
              console.log('parent1 err: ' + err);
              return;
            }
            console.log('parent1 saved:');
            console.dir(pres);

            ParentModel
              .populate(pres, 'children', { options: { lean: true } })
              .then(ppop => {
                console.log('parent1 populated:');
                console.dir(ppop);
              })
              .catch(err => {
                console.log('parent1 err: ' + err);
                return;
              });
          });
      });

    // parent2 test

    var c2 = {
      _id: 2,
      label: 'child2'
    };

    ChildModel
      .findByIdAndUpdate(c2._id, c2, { upsert: true, setDefaultsOnInsert: true, new: true })
      .lean()
      .exec((err, cres2) => {
        if (err) {
          console.log('child2 err: ' + err);
          return;
        }
        console.log('child2 saved:');
        console.dir(cres2);

        var children = [];
        children.push(cres2);

        var p2 = new ParentModel({
          _id: 2,
          label: 'parent2',
          children: children
        });

        ParentModel
          .findByIdAndUpdate(p2._id, p2, { upsert: true, setDefaultsOnInsert: true, new: true })
          .lean()
          .exec((err, pres2) => {
            if (err) {
              console.log('parent2 err: ' + err);
              return;
            }
            console.log('parent2 saved:');
            console.dir(pres2);

            ParentModel
              .populate(pres2, 'children', { options: { lean: true } })
              .then(ppop2 => {
                console.log('parent2 populated:');
                console.dir(ppop2);
              })
              .catch(err => {
                console.log('parent2 err: ' + err);
                return;
              });
          });
      });

    // parent3 test

    var c3 = {
      _id: 3,
      label: 'child3'
    };

    ChildModel
      .findByIdAndUpdate(c3._id, c3, { upsert: true, setDefaultsOnInsert: true, new: true })
      .lean()
      .exec((err, cres3) => {
        if (err) {
          console.log('child3 err: ' + err);
          return;
        }
        console.log('child3 saved:');
        console.dir(cres3);

        var children = [];
        children.push(cres3);

        var p3 = new ParentModel({
          _id: 3,
          label: 'parent3'
        });

        p3.set('children', children);

        ParentModel
          .findByIdAndUpdate(p3._id, p3, { upsert: true, setDefaultsOnInsert: true, new: true })
          .lean()
          .exec((err, pres3) => {
            if (err) {
              console.log('parent3 err: ' + err);
              return;
            }
            console.log('parent3 saved:');
            console.dir(pres3);

            ParentModel
              .populate(pres3, 'children', { options: { lean: true } })
              .then(ppop3 => {
                console.log('parent3 populated:');
                console.dir(ppop3);
              })
              .catch(err => {
                console.log('parent3 err: ' + err);
                return;
              });
          });
      });

    // parent4 test

    var c4 = {
      _id: 4,
      label: 'child4'
    };

    ChildModel
      .findByIdAndUpdate(c4._id, c4, { upsert: true, setDefaultsOnInsert: true, new: true })
      .lean()
      .exec((err, cres4) => {
        if (err) {
          console.log('child4 err: ' + err);
          return;
        }
        console.log('child4 saved:');
        console.dir(cres4);

        var children = [];
        children.push(cres4);

        var p4 = new ParentModel({
          _id: 4,
          label: 'parent4'
        });

        p4.setValue('children', children);

        ParentModel
          .findByIdAndUpdate(p4._id, p4, { upsert: true, setDefaultsOnInsert: true, new: true })
          .lean()
          .exec((err, pres4) => {
            if (err) {
              console.log('parent4 err: ' + err);
              return;
            }
            console.log('parent4 saved:');
            console.dir(pres4);

            ParentModel
              .populate(pres4, 'children', { options: { lean: true } })
              .then(ppop4 => {
                console.log('parent4 populated:');
                console.dir(ppop4);
              })
              .catch(err => {
                console.log('parent4 err: ' + err);
                return;
              });
          });
      });

**Comment by vkarpov15** [comment]
p2 is not supported. To get p3 to work, use `.toObject()`:

```javascript
ParentModel
      .findByIdAndUpdate(p3._id, p3.toObject(), { upsert: true, setDefaultsOnInsert: true, new: true })
```

**Comment by linusbrolin** [comment]
Thanks!
