### ISSUE TITLE
runValidators doesn't work with findOneAndUpdate

### ISSUE THREAD

**Issue by damienleroux** [Automattic/mongoose#4661]
I tried mongoose today and write:

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/my_database');

var Model = new Schema({
  name: { type: String, required: true},
  content: { type: String, required: true}
});

var myModel = mongoose.model('Model', Model);

myModel.findOneAndUpdate(
  { 
    name: 'test'
  },{
    name: 'test',
    content: true
  }, {
    new: true,
    upsert: true,
    runValidators: true
  }, function (err, traductions) {
    console.log("traductions:", JSON.stringify(traductions));
    console.error("updateTraduction err:", err);
  }
);
```

This code should return an error because I try to insert a boolean in `content` from schema `Model` instead of a `string`. 

I enable `runValidators` and `upsert` and doesn't understand why this doesn't work. my console returns:

```
traductions: {"_id":"581129cc201f204c686dda1c","name":"test","__v":0,"content":"true"}
updateTraduction err: null
```

Why the validator doesn't take into account a schema?

**Comment by damienleroux** [comment]
this problem seems to be referenced [here](http://stackoverflow.com/questions/31101984/mongoose-findoneandupdate-and-runvalidators-not-working) but doesn't explain why this doesn't work

**Comment by vkarpov15** [comment]
It does take into account the schema, you'll notice that 'content' is saved as a string. Mongoose does type coercion. In the case of setting a string property to a boolean value, mongoose will convert the boolean value to a string, true -> 'true', false -> 'false'.
