### ISSUE TITLE
setDefaultsOnInsert causes high CPU utilization unnecessarily

### ISSUE THREAD

**Issue by CamHenlin** [Automattic/mongoose#4671]
There is unnecessary code in setDefaultsOnInserts (most of lines 25 - 49, in fact!) that can be extremely expensive in terms of node process utilization when updating documents with large numbers of properties. That code should be cut down to only the essentials and moved inside of the conditional currently located on line 51 for big performance gains. I have a PR fixing this issue here: https://github.com/Automattic/mongoose/pull/4672

**Comment by vkarpov15** [comment]
Merged the PR, thanks for catching this :+1:
