### ISSUE TITLE
Insert if not exists atomically

### ISSUE THREAD

**Issue by rocketspacer** [Automattic/mongoose#4678]
I'm trying to create a new account with unique email, one of the options is trying to find out if there is an account with that email already exists, if there is none, create the new account.
The problem is that I am unclear about whether this is atomically-safe or not. What if 2 users trying to create new account with same email at the same time. Will that ruin the consistency of my database ?
```
Account
    .find({email: req.body.email})
    .exec((err, accounts) => {
        //Try to find an account that have the same email
        if (!accounts.length) {
            //If none is found create a new account with this email
            var account = new Account({.....});
            account.save();
        }
});
```
I know about the unique option in SchemaType. I just need someone to clarify if the above code is considered bad practice

**Comment by vkarpov15** [comment]
I'd argue it's bad practice, it is most definitely _not_ atomic. Use the `unique` option in schema type or `findOneAndUpdate()` with the upsert option instead, both of those are atomic.
