### ISSUE TITLE
Documentation on Handling Error

### ISSUE THREAD

**Issue by rocketspacer** [Automattic/mongoose#4679]
I really need some documentation on how to handle mongoose errors (Validation, Not Unique, etc)

Some information about how many types of error there are, what are they, and how they are structured would be great

**Comment by vkarpov15** [comment]
Do you mean errors from save, connection errors, etc.? There's a lot of them...

**Comment by rocketspacer** [comment]
Yeah, put them somewhere in the documentation.
If they have the same format, then for each error, highlight their signature.
If they have  a unique format (like the Unique-Constraint validation error) note them out.

**Comment by vkarpov15** [comment]
Not gonna happen for the foreseeable future. There's a lot of different error conditions that can come out of the mongodb driver and it'll be a Sisyphean task to try to enumerate them all in a clean way.
