### ISSUE TITLE
Optionally disable timestamps?

### ISSUE THREAD

**Issue by SabeehY** [Automattic/mongoose#4687]
Hi,

I have a case where I want to update the document, but don't want to touch the timestamps. Just want to know if it's possible, and if there's any other way to disable the timestamp feature for the current update/save. Any help would be highly appreciated.

Thanks.

**Comment by vkarpov15** [comment]
Not supported right now. Only workaround would be to bypass mongoose and do `MyModel.connection.update()`.

**Comment by fiws** [comment]
I also have the same problem. Is there the possibility that this will be implemented someday?

**Comment by vkarpov15** [comment]
@fiws you can always just write a pre save hook that does `unmarkModified('updatedAt')`. Or a pre update hook that deletes `updatedAt`. Should be pretty doable.

**Comment by evilive3000** [comment]
+1 would be useful.
