### ISSUE TITLE
Aggregate cursor exec sometimes returns undefined?

### ISSUE THREAD

**Issue by brandonros** [Automattic/mongoose#4694]
```
mongo.aggregate = function (collection, parameters) {
	return new Promise(function (resolve, reject) {
		var model = models[collection];

		var docs = [];

		var cursor = model.aggregate(parameters).cursor({ batchSize: 1000 }).exec();

		cursor.each(function (err, doc) {
			if (err) {
				return reject(err);
			}

			if (!doc) {
				return resolve(docs);
			}

			docs.push(doc);
		});
	});
};
```

Sometimes, this works without issue.
Sometimes, cursor is undefined.

Could this be a timeout issue? It seems to happen immediately though.

**Comment by vkarpov15** [comment]
It's unfortunately a bug with the first way we implemented aggregation cursors - cursor will be undefined if the model's underlying connection has not successfully connected. That's what the async option for agg cursors is for:

```javascript
model.aggregate(parameters).cursor({ batchSize: 1000, async: true }).exec(function(error, cursor) {
  // Can now use cursor
});
```

The reason why it needs to be async is that mongoose may need to wait for the connection to mongodb to be established before it can actually return the cursor.
