### ISSUE TITLE
populate array of ObjectId without ref, not work

### ISSUE THREAD

**Issue by raugaral** [Automattic/mongoose#4695]
I have the next mongoose Schema

```
var userSchema = new Schema({
  nombre: String,
  apellidos: String,
  email: String,
  pass: String,
  fecha_registro : { type: Date, default: Date.now },
  rol_list: [Schema.Types.ObjectId], // Generic array of ObjectId
  deleted: {type: Boolean, default: false}
});

module.exports = mongoose.model('User', userSchema);
```
When I search a user and try to populate the "rol_list" array, is always empty. I have looked in mongo the users are well filled, but mongoose return it empty.

```
passport.deserializeUser(function(id, done) {
  User.findById(id)
    .populate('rol_list')
    .exec(function(err, user) {
      console.log(user);
      done(err, user);
    });
});
```
The console.log(user) show always the array rol_list empty.

If I assign a reference to the ObjectId in the schema like:
`rol_list: [{ type: Schema.Types.ObjectId, ref: 'Rol1' }]`
than is correct filled, logically only with the element "Rol1".

Any idea?
Is userSchema  bad defined?

**Comment by vkarpov15** [comment]
Populate won't work unless you provide a ref, because if you just have a list of object ids how is mongoose supposed to know what collection to populate from? If you don't want to define a ref, you can also specify the model in populate:

```javascript
  User.findById(id)
    .populate({ path: 'rol_list', model: Rol1 })
    .exec(function(err, user) {
      console.log(user);
      done(err, user);
    });
```

**Comment by raugaral** [comment]
Doesn't work ... 😢

**Comment by vkarpov15** [comment]
Please clarify?

**Comment by yy0608** [comment]
Did u resolve the problem? I got the same problem.
