### ISSUE TITLE
Referencing virtuals I get MissingSchemaError: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by tosbaha** [Automattic/mongoose#4696]
I have following models,

user.js
```javascript
var mongoose = require('mongoose');

var UserSchema = mongoose.Schema({
    email: {type: String, index: {unique: true, sparse: true}},
    password: String,
    createdOn: {type: Date, default:Date.now }
});

UserSchema.virtual('documents',{
    ref: 'Document',
    localField:'_id',
    foreignField:'owner'
});


var User = mongoose.model("User", UserSchema);
module.exports = User;
```

document.js
```javascript
var mongoose = require('mongoose');

var DocumentSchema = mongoose.Schema({
    owner : { type:mongoose.Schema.Types.ObjectId, ref: 'User' },
    name: String,
    details:[{
        _id:false,
        message: String,
        location: String,
        date: Date
    }]
});

var Document = mongoose.model("Document", DocumentSchema);
module.exports = Document;

```
In my app.js since I don't use Document, if I just import User
```javascript
const User = require('./lib/model/user');
```
I get 

`MissingSchemaError: Schema hasn't been registered for model "Document".`

However if I do,
```javascript
const User = require('./lib/model/user');
const Document = require('./lib/model/document');
```
It works as expected. Even though I don't use Document, it still needs it.

**Comment by tarun1793** [comment]
This is expected Behaviour. Mongoose needs to know if the Schema exists for the referenced model. 
You can view this as `User` model being dependent on the `Document` model, you should call or `require` the `Document` model inside the `User.js` file.

**Comment by tosbaha** [comment]
Thanks for the response. I wonder if I `require` the `Document` inside `user.js`, and the `User` inside `document.js`, will it create circular reference?

**Comment by vkarpov15** [comment]
So the below script works just fine, no errors thrown:

```javascript

**Comment by tosbaha** [comment]
I guess I found the error. In my code I `populate` documents field and and `match` some properties. That is why mongoose needs the schema I guess. Sorry for the confusion.

**Comment by rsinghal26** [comment]
so, why it was given this error when you populate documents field and match some properties. Can you explain it because I have the same problem.

**Comment by vkarpov15** [comment]
@rsinghal26 code samples please?
