### ISSUE TITLE
DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead

### ISSUE THREAD

**Issue by wzup** [Automattic/mongoose#4699]
```
const mongoose = require('mongoose');

let conn = mongoose.connect(uri);
conn.then((res) => {
    console.log('res:', res);
})
```

> (node:7428) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

> res:
 undefined

= Docs http://mongoosejs.com/docs/api.html#index_Mongoose-connect
![mongoose api v4 6 7 - google chrome 2016-11-11 10 11 37](https://cloud.githubusercontent.com/assets/3880497/20202041/553fac14-a7f7-11e6-990b-b97eb158b6ab.png)

**Comment by vkarpov15** [comment]
Expected behavior. If you're going to use `.then()`, plug in your own promise lib [as described here](http://mongoosejs.com/docs/promises.html)

**Comment by ajbraus** [comment]
Link hangs indefinitely: http://mongoosejs.com/docs/promises.html

**Comment by vkarpov15** [comment]
That's strange, works fine for me. Does mongoosejs.com work for you?
