### ISSUE TITLE
What is cached and what is not cached in mongoose?

### ISSUE THREAD

**Issue by wzup** [Automattic/mongoose#4701]
1) What is cached and what is not cached?
2) What do I need to cache?

All your examples imply that everything happens in one file - connection, schemas, models, callbacks, everything. It is not the case with real life app. In real life app developers tend to have models, schemas, connections in separate files (modules).

So here are my questions. 

1. I want to have a separate file for every schema. It means that in every schema file I have to `require('mongoose')`. Is 'mongoose' once required cached or not? Will I get one and the same `mongoose` instance in every schema file or every `require('mongoose')` will create new instance? What should I do to have only one `mongoose` instance in every schema file? Your best practices?

2.  May I cache models as well? Or do I have to create a new model every time I need to save a new document into collection?

**Comment by paton** [comment]
1. require('mongoose') returns the same instance.

2.  Yes Schemas are cached too as long as you register the schema with `mongoose.model`: http://mongoosejs.com/docs/api.html#index_Mongoose-model

**Comment by vkarpov15** [comment]
1) Same instance. That's just how `require()` works

2) You should only create your models once, when your process starts. Each time you save a new user you should use the same User model
