### ISSUE TITLE
.populate with separated ref not working

### ISSUE THREAD

**Issue by hpfs74** [Automattic/mongoose#4704]
It seems that the latest version of mongoose does not honor the
 
` query.populate('table1 table2 table3') 
`
it doesn't work like it was a 3.6 version, while doing

`query.populate('table1').populate('table2').populate('table3')`

works fine

**Comment by paton** [comment]
This is working for me on mongoose 4.6.6.

```
ModelName.findOne().populate('field1 field2').exec(console.log);
```

Can you provide a more complete code example to help reproduce?

**Comment by hpfs74** [comment]
It's broken on 4.6.7

**Comment by vkarpov15** [comment]
Please provide a real code sample, preferably with schemas.

**Comment by jiri-smolik** [comment]
I am having another maybe relate problem with populate particularly with 4.6.7 and empty populate string

```
var x = mongoose.Schema({
}, {collection: 'users'});
mongoose.model('x', x);
mongoose.model('x').findOne({}).populate('').exec((err, res) => {
    console.log(err, res);
});
```

My app crashes (err callback not called) with 

> Error: If you are populating a virtual, you must set the localField and foreignField options

Key thing is the collection which has to exist and has to be non-empty, no matter the stored data.

**Comment by vkarpov15** [comment]
I don't understand, can you please clarify?

**Comment by jiri-smolik** [comment]
Yes. The code specified above triggers an uncaught exception, which I thought should not happen. Entire reproducible code snippet:

```
const mongoose = require('mongoose');

const connString = '...';
mongoose.connect(connString);

var x = mongoose.Schema({}, {collection: 'users'});
mongoose.model('x', x);
mongoose.model('x').findOne({}).populate('').exec((err, res) => {
    console.log(err, res);
});

console.log('Hello');

// If i do not supply this handler, node application crashes
process.on('uncaughtException', (err) => {
  console.warn('uncaughtException', err.message); // uncaughtException If you are populating a virtual, you must set the localField and foreignField options
});
```

Mongoose debug says: `Mongoose: users.findOne({}, { fields: undefined })`

mongo db version 3.2.10
nodejs version 5.5.0

As I said, the code produces uncaught exception only in the case, the specified collection - users in my case - exists and contains at least one record

**Comment by vkarpov15** [comment]
Try upgrading to 4.7.0: https://github.com/Automattic/mongoose/blob/master/History.md#470--2016-11-23

**Comment by jiri-smolik** [comment]
I can confirm that 4.7.0 fixes this. Thanks
