### ISSUE TITLE
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by AraanBranco** [Automattic/mongoose#4708]
I have an application running, and I had some problems when I make a find in a string (even though it is an ObjectId), I already tried to convert the String to ObjectId with `mongoose.Types.ObjectId(' 53cb6b9b4f4ddef1ad47f943 ')` (example) and Even then I can not get the return and it returns me the following error:

`Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`

Also returns me:

`this.id.charCodeAt is not a function`

Has anyone had this problem yet?

**Comment by cblanc** [comment]
Try trimming the spaces in your string

```
mongoose.Types.ObjectId ('53cb6b9b4f4ddef1ad47f943')
```

**Comment by AraanBranco** [comment]
Sorry, it was typing error ... neat =)

**Comment by Bikashm977** [comment]
hi i m bikash
