### ISSUE TITLE
There is no opportunity to enable required validation for Update 

### ISSUE THREAD

**Issue by hrachyam** [Automattic/mongoose#4711]
Hello,

I am able to enable Schema validation while updating document  using this attribute:
    {runValidators: true} 
But the validation "required" is still disabled.

Note: 
it is OK for PATCH request but it is not OK for PUT request while implementing Restful API as all required fields must be specified in case of adding new document instead of updating one.

In the PUT I have used  { upsert: true }

```javascript
app.put('/employees/:id', function(req, res) {
    var msg = 'Update or Create employee by Id: ' + req.params.id;
    console.log(msg);
    Employee.findOneAndUpdate({'emp_no' : req.params.id}, req.body,
        { upsert: true, new: true, runValidators: true },
        function (err, employee) {
            if (err){
                return res.send(err);
            }
            res.send(msg + '\n');
        });
});
```

```
app.patch('/employees/:id', function(req, res) {
    var msg = 'Update employee by Id: ' + req.params.id;
    console.log(msg);
    Employee.findOneAndUpdate({'emp_no' : req.params.id}, req.body,
        { new: true, runValidators: true },
        function (err, employee) {
            if (err){
                return res.send(err);
            }
            res.send(msg + '\n');
        });
});
```

Everything is OK for PATCH but for PUT it will be used like for POST.

**Comment by vkarpov15** [comment]
`runValidators` will only run validation on fields that are [explicitly set (or unset) in the update operation](http://mongoosejs.com/docs/validation.html#update-validator-paths). If you want to validate an upsert in the way you specified, do:

```javascript
var employee = new Employee(req.body);
employee._id = req.params.id;
employee.isNew = false;
employee.save(callback);
```

**Comment by hrachyam** [comment]
Hello,

Thanks for the explanation.

app.put('/employees/:id', function(req, res) {
    Employee.findOne({'emp_no' : req.params.id}, function(err, employee) {
        if (employee == null) {
            var newEmployee = new Employee(req.body);
            newEmployee.save(function (err) {
                if (err){
                    return res.send(err);
                }
                var msg = 'Created employee by Id: ' + req.params.id;
                console.log(msg);
                res.send(msg + '\n');
            });
        } else {
            employee.first_name = req.body.first_name;
            employee.last_name = req.body.last_name;
            employee.birth_date = req.body.birth_date;
            employee.gender = req.body.gender;
            employee.hire_date = req.body.hire_date;
            employee.save(function (err) {
                if (err){
                    return res.send(err);
                }
                var msg = 'Updated employee by Id: ' + req.params.id;
                console.log(msg);
                res.send(msg + '\n');
            });
        }
    });
});

app.patch('/employees/:id', function(req, res) {
    Employee.findOneAndUpdate({'emp_no' : req.params.id}, req.body,
        { new: true, runValidators: true }, 
        function (err, obj) {
            if (err){
                return res.send(err);
            }
            if (obj === null) {
                var msg = 'Employee by Id: ' + req.params.id + ' is not found';
                console.log(msg);
                res.send(msg + '\n');
            } else {
                var msg = 'Updated employee by Id: ' + req.params.id;
                console.log(msg);
                res.send(msg + '\n');
            }
        }
    );
});


Is it correct way  to use mongoose?

NOTE: I would like to use findOneAndUpfate with upsert: true in  post request also and not check employee existence and then call save methods to create or update employee.

Could you please provide your opinion about the above mentioned?

Thanks,
Hrach

**Comment by vkarpov15** [comment]
The other alternative is to use mongoose's `validate()` before doing `findOneAndUpdate()`:

```javascript
var employee = new Employee(req.body);
employee.validate(function(error) {
  if (error) {
    return res.send(err);
  }
  var toSave = employee.toObject({ virtuals: false });
  delete toSave._id;
  Employee.findOneAndUpdate({ _id: req.params.id }, { $set: toSave }, { upsert: true }, function(err) {
    // ...
  });
});
```

Based on your code samples I think that would probably be the way to go for you

**Comment by hrachyam** [comment]
Thank you very much for your help and effort.

It is that I have expected to have.
