### ISSUE TITLE
Date format validation is missing

### ISSUE THREAD

**Issue by hrachyam** [Automattic/mongoose#4712]
How to validate format of type: Date in schema (format: YYYY-MM-DD) ?

I have tried to use String type and then add custom validation but in this case the specified value is stored in DB as String type instead of Date type.

How to solve this problem and store Date format data in DB ?

**Comment by vkarpov15** [comment]
So mongodb dates are always stored as a date with time, but you can do a custom setter as well:

```javascript
var schema = new Schema({
  date: {
    type: Date,
    set: function(v) {
      return new Date(v.getFullYear(), v.getMonth(), v.getDate());
    }
  }
});
```

That way, whenever you set the date, you'll get just the year+month+date component, no time component. Just be wary of [question 2 on the FAQ](http://mongoosejs.com/docs/faq.html).

However, if you want to store just dates, I'd recommend you just store them as YYYYMMDD strings. No reason why not, both take 8 bytes of space in bson and YYYYMMDD takes less space in JSON, and YYYYMMDD strings are sortable and filterable in mongodb just like dates.
