### ISSUE TITLE
not authorized on [database_name] to execute command { insert: "[collection_name]", documents: [count], ordered: true, writeConcern: { w: 1 } }

### ISSUE THREAD

**Issue by zeg-io** [Automattic/mongoose#4717]
In my testing on this issue I've wiped out and reinstalled mongoose and any mongo folder as well. So  I am currently using

mongodb@2.2.11 
│   └── mongodb-core@2.0.13 
└── mongoose@4.6.8 

I am authorizing with an account which has `dbOwner` permissions.

I am doing a bulk insert of around 600 records by using

```js
ModelName.insertMany( documentArray, function (err, results) {...}
```
I get the following error:
```json
{
  "name": "MongoError",
  "message": "not authorized on appdb to execute command { insert: \"devices\", documents: 609, ordered: true, writeConcern: { w: 1 } }",
  "ok": 0,
  "errmsg": "not authorized on appdb to execute command { insert: \"devices\", documents: 609, ordered: true, writeConcern: { w: 1 } }",
  "code": 13
}
```
**However** I have logged in both from my client and locally on the server and can perform `db.devices.insertMany` operations just fine!

I've been looking for a solution for hours and can find none.

**Comment by zeg-io** [comment]
Umm... correction...

The version of mongo locally installed on my macOS machine is 3.2.7  Permissions are configured, and that one works fine.

I installed the Bitnami version of MongoDB and configured it with the same Permissions.  It is version 3.2.10.

The Bitnami install is the one failing.  So I am no longer sure it is a driver issue

**Comment by vkarpov15** [comment]
How are you configuring permissions? Also, are you able to auth against the bitnami version using the mongodb shell?

**Comment by zeg-io** [comment]
Ok, so more details:

I spun up an additional ubuntu machine, installed Mongo and tested the code.  It worked fine.

(I documented the entire process below) everything worked until after I secured the server, then *no* account can create records with .insertMany() through the node code.  However, I can authenticate through Robomongo and perform manual insertMany() commands.  There is definitely a permissions issue going on.

I am attempting to bulk insert documents into a `devices` collection, and that is failing using the `dataload` account which is dbOwner, and I would assume that would have permissions. 

Mongoose configuration code:
-------
```js
var config = {
  URI: 'mongodb://mongodb-ip/magic',
  OPTIONS: {
    user: 'tarcher',
    pass: 'SUPERSECRETPASSWORD',
    auth: {
      authdb: 'magic'
    }
  }
}
```

Configuration on server:
--------

After installing mongo, I mounted an encrypted drive at `/data` then created folders: /data/mongo/db/ and /data/mongo/log/
put mongod.conf in /data/mongo/

```sh
mkdir /data/mongo
mkdir /data/mongo/db
mkdir /data/mongo/log
cp /etc/mongodb.conf /data/mongo
cp -r /var/lib/mongodb /data/mongo/db
cp /var/log/mongodb/mongod.log /data/mongo/log/mongod.log
```

Edit the bindings for mongodb.conf:
```sh
# Where and how to store data.
storage:
  dbPath: /data/mongo/db
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /data/mongo/log/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1,999.999.999.999 # the 999 address is just obfuscation around an actual one
```

Fix permissions
`sudo chown -R mongodb:mongodb /data`

Create the service
`sudo nano /lib/systemd/system/mongod.service`

```
[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target
Documentation=https://docs.mongodb.org/manual

[Service]
User=mongodb
Group=mongodb
ExecStart=/usr/bin/mongod --quiet --config /data/mongo/mongod.conf

[Install]
WantedBy=multi-user.target
```
```sh
sudo service mongod start
netstat -plntu
# Check for port :27017
```
Lock it down!
`$ mongo`
# ------
```js
use admin
// Create root user
db.createUser({ user:"root", pwd:"SUPERSECUREPASSWORD", roles: [{ role:"root", db:"admin" }] })
```

Edit the service to run secured and save
`sudo nano /lib/systemd/system/mongod.service`
modify the following line
`ExecStart=/usr/bin/mongod --quiet --auth --config /data/mongo/mongod.conf`

Restart the service
`sudo service mongod restart`

Access the server with credentials
`mongo -u root -p "SUPERSECUREPASSWORD" --authenticationDatabase admin`

Add user-account(s)
```js
db.createUser({ user:"dataload", pwd:"SUPERSECUREPASSWORD", roles: [ { role:"dbOwner", db:"magic" } ] })
```

Add roles and service-account(s)
Add Service:
```js
use magic
db.createRole({
  role: "ore-service",
  privileges: [
     { resource: { db: "magic", collection: "" }, actions: [ "find" ] },
     { resource: { db: "magic", collection: "accessHistory" }, actions: [ "find", "insert", "update" ] },
     { resource: { db: "magic", collection: "selfservice" }, actions: [ "find", "insert", "update" ] },
     { resource: { db: "magic", collection: "serviceHistory" }, actions: [ "find", "insert", "update" ] },
     { resource: { db: "magic", collection: "users" }, actions: [ "find", "insert", "update" ] }
  ],
  roles: []
})
```

```js
use magic
db.createUser(
  {
    user: "ore-ws",
    pwd: "xxxxxxx",
    roles: [ { role: "ore-service", db: "magic" } ]
  }
)
```

**Comment by vkarpov15** [comment]
So you're not creating a "tarcher" user, which would explain why the auth credentials in your mongoose connection options aren't working...
