### ISSUE TITLE
Error with Object Id

### ISSUE THREAD

**Issue by jaider2523** [Automattic/mongoose#4718]
Hi,

I need your help with this error:

Error: The 2nd parameter to `mongoose.model()` should be a schema or a POJO
    at Mongoose.model...

My model is:

```
'use strict';


/**
 * Module Dependencies
 */

var mongoose      = require('mongoose');
var shortid       = require('shortid');
var Schema        = mongoose.Schema;
var userSchema    = require('../models/User');
var User          = mongoose.model('User', userSchema);

/**
 * Define Unit Schema
 */

var unitShema = new mongoose.Schema ({
  idShema: { type: String, unique: true, default: shortid.generate },
  name: { type: String, unique: true, index: true },
  description: { type: String },
  updated: { type: Date },
  created: { type: Date, default: Date.now },
  user: { type: mongoose.Schema.ObjectId, ref: 'User' },

});

module.exports = mongoose.model('Unit', unitShema);
```

I don´t understand ....this work ....a few weeks ago.

Thanks..

**Comment by vkarpov15** [comment]
Is your stack trace saying the error is from the `var User = mongoose.model` call or the `module.exports = mongoose.model` call? I suspect it's the former, because I'd imagine `models/User` exports a *model*, not a *schema*. Either way, `User` is unused in this file so it's not clear why it's there in the first place.

**Comment by jaider2523** [comment]
Hi @vkarpov15, i found my mistake, i just only remove :

 var userSchema    = require('../models/User');
var User                  = mongoose.model('User', userSchema);

Mongoose recognize automatically my model User......Thanks
