### ISSUE TITLE
openSet data base parameter is ignored

### ISSUE THREAD

**Issue by mjflan** [Automattic/mongoose#4721]
When calling `openSet` in mongoose  4.4.6, the `database` parameter has no function. Instead, the database to connect __must__ be given in the `uris` parameter. If no DB name follows the host list, the database name 'test' is used instead.  Under no circumstances is the name given in the `database` parameter used.

Since most of us don't use 'test' as the only DB name, it ends up being empty, which provides for lots of successful results that return nothing. 

Oh, and while you are there, update the header docs on `openSet` and correct the `uris` description. 'mongodb://'  does not belong in front of each host name, or all the hosts after the first one will be ignored. That probably works...sometimes.

**Comment by vkarpov15** [comment]
Fixed in master :+1:
