### ISSUE TITLE
Cannot read property 'username' of null

### ISSUE THREAD

**Issue by nathan130200** [Automattic/mongoose#4722]
# I i try to authenticate username with database, it returns:
`               
        if (user.username && opts.password)
                        ^

        TypeError: Cannot read property 'username' of null
            at Query.<anonymous> (C:\WarFace Servers files\warface-xmpp-tls\warface-xmpp-tls\lib\server.js:92:25)
            at C:\WarFace Servers files\warface-xmpp-tls\warface-xmpp-tls\node_modules\mongoose\node_modules\kareem\index.js:177:19
            at C:\WarFace Servers files\warface-xmpp-tls\warface-xmpp-tls\node_modules\mongoose\node_modules\kareem\index.js:109:16
            at _combinedTickCallback (internal/process/next_tick.js:67:7)
            at process._tickCallback (internal/process/next_tick.js:98:9)

# My script:

        server.on("connect", function(client) {

        // Allows the developer to authenticate users against anything they want.
        client.on("authenticate", function(opts, cb) {
            User.findOne({username: opts.jid.local}, function(err, user) {
                if (user.username && opts.password)
                    cb(null, opts);
                else
                    cb(new Error("Authentication failure"));
            });
        });

        // On Disconnect event. When a client disconnects
        client.on("disconnect", function(client) {
            console.log('saiu do jogo!', Math.random())
        });

    });

**Comment by timeswind** [comment]
if (user && user.username && opts && opts.password)

**Comment by vkarpov15** [comment]
Can you please clarify your question? I don't understand.

**Comment by nathan130200** [comment]
I'm using this api to create gaming private server that it uses mongoose. But i don't understand how to use this. I tryed to run, but still returning in "kareem module" null. https://github.com/highattack30/warface-emulator

**Comment by vkarpov15** [comment]
`user` might be null because a user was not found. Are you sure that user is in the database? That's the simplest explanation for this issue.
