### ISSUE TITLE
Mongoose 4.6.6 findOneAndUpdate insert by element inserts null for element instead of the given data

### ISSUE THREAD

**Issue by stevenelson74708** [Automattic/mongoose#4724]
The following call to findOneAndUpdate updates the document properly with mongoose versions 4.6.5 and earlier, but with versions 4.6.6 and later the call inserts null into the specified element of the document instead of inserting the given data. 

Calls that simply push an element into the array, continue to work properly using versions 4.6.6 and later as they have in earlier versions. It's only the calls that attempt to replace the data for a specific element that insert null using versions 4.6.6 and later, which work properly with versions prior to 4.6.6. 

This is similar to the problem cited in issue #4582 where the same findOneAndUpdate call did not update the document at all.

               `// Array is at max size, find oldest element and replace
                wlogger.debug("UserId: " + userId + " locations array is full - size = "
                    + users[0].locations.length
                    + " -- replace oldest location in array");

                var oldestIndex = 0;
                var oldestDate = users[0].locations[0].accessDate;

                for (var i = 0; i < (constants.maxLocationsArraySize - 1); i++)
                {
                    if (oldestDate >
                        users[0].locations[i + 1].accessDate)
                    {
                        oldestDate = users[0].locations[i + 1].accessDate;
                        oldestIndex = i + 1;
                    }
                }

                // Bracket notation is required to set the value for a key of an object from a variable
                var oldestLocationsIndex = "locations." + oldestIndex;
                wlogger.debug("ipLocationsIndex = " + oldestLocationsIndex);
                var element = {};
                element[oldestLocationsIndex] = locationInfo;

                //noinspection JSUnresolvedFunction
                user.findOneAndUpdate(
                    {"_id": userId},
                    {$set: element},
                    function (err1, model)
                    {
                        if (model == null)
                        {
                            wlogger.warn("model == null -- "
                                + "unable to update location info for "
                                + "UserId: " + userId);
                            callback({"response": false});
                        }
                        else if (err1 == null)
                        {
                            wlogger.debug("Updated location info for UserId: "
                                + userId + " in array");
                            callback({"response": true});
                        }
                        else if (model.length != 0)
                        {
                            wlogger.error(err1 + " - Unable to update location info for "
                                + "UserId: " + userId + " -- model = "
                                + model);
                            callback({"response": false});
                        }
                        else
                        {
                            wlogger.error(err1 + " unable to update location info"
                                + " for UserId: " + userId);
                            callback({"response": false});
                        }
                    });`

The schema used is below: 

      `var mongoose = require('mongoose');
       require('mongoose-long')(mongoose);

       var Schema = mongoose.Schema;

       var phoneNumbersSchema = new Schema( {_id: false, type: String, number: String, primary: Boolean} );
       var categoriesSchema = new Schema( {_id: false, categoryId: Schema.Types.ObjectId} );
       var customerSchema = new Schema( {_id: false, firstName: String, lastName: String, phoneNumbers: [phoneNumbersSchema] , userId: Schema.Types.ObjectId} );
       var providerSchema = new Schema( {_id: false, providerName: String, providerId: Schema.Types.ObjectId} );
       var ipAddrSchema = new Schema( {_id: false, ipType: String, useCount: Number, upper64: Schema.Types.Long, lower64: Schema.Types.Long, lastUsedDate: Date} );
       var locationSchema = new Schema( {_id: false, location: { type: { type: String, default: 'Point' }, coordinates: [Number] }, accessDate: Date,  accessType: String} );
       var inMessageSchema = new Schema( {_id:false, date: Date, fromUserId: Schema.Types.ObjectId, fromEmail: String, read: { type: Boolean, default: false }, deleted: { type: Boolean, default: false }, subject: String, message: String} );
       var outMessageSchema = new Schema( {_id:false, date: Date, toUserId: Schema.Types.ObjectId, toEmail: String, deleted: { type: Boolean, default: false }, subject: String, message: String} );
       var recentUploadSchema = new Schema( {_id: false, uploadDate: Date, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
       var recentViewsSchema = new Schema( {_id: false, viewDate: Date, viewCount: Number, itemDocId: Schema.Types.ObjectId, itemDocGroupId: String, thumbnailId: Schema.Types.ObjectId, thumbnailUuid: String });
       var recentAddsSchema = new Schema( {_id: false, addDate: Date, addCount: Number, categoryId: Schema.Types.ObjectId, itemId: Schema.Types.ObjectId, itemName: String });

       var userSchema = mongoose.Schema({ 
           token : String,
           email: String,
           userName: String,
           deviceId: String,
           devicePhoneNumber: String, 
           hashed_password: String, 
           hashed_admin_code: String,
           maxStorageByteLimit: { type: Number, default: 1073741824 },
           accessLevel: { type: Number, default: 2 },
           lastAccessType: Number,
           storageBytesUsed: { type: Number, default: 0 },
           totalStorageBytesUsed: { type: Number, default: 0 },
           deletedStorageBytesUsed: { type: Number, default: 0 },
           salt : String,
           salt1 : String,
           temp_str: String,
           active: { type: Boolean, default: false },
           disabled: { type: Boolean, default: false },
           emailReg: { type: Boolean, default: false },
           regPending: { type: Boolean, default: false },
           emailChangePending: { type: Boolean, default: false },
           regCodeSendCount: { type: Number, default: 0 },
           trialStartDate: Date,
           signUpDate: Date,
           passwordResetDate: Date,
           lastLoginDate: Date,
           lastModifiedDate: Date,
           curLoginDate: Date,
           curIpAddr: { ipType: String, 
               upper64: Schema.Types.Long,
               lower64: Schema.Types.Long },
           firstName: String,
           lastName: String,
           address: { streetAddress: String,
               city: String,
               state: String, postalCode: String },
           phoneNumbers: [ phoneNumbersSchema ],
           categories: [ categoriesSchema ],
           providerCustomers: [ customerSchema ],
           serviceProviders: [ providerSchema ],
           ipAddrs: [ ipAddrSchema ],
           recentUploads: [ recentUploadSchema ],
           recentUploadsGizmo: [ recentUploadSchema ],
           recentUploadsLife: [ recentUploadSchema ],
           recentUploadsVehicle: [ recentUploadSchema ],
           recentUploadsMisc: [ recentUploadSchema ],
           recentViews: [ recentViewsSchema ],
           recentAdds: [ recentAddsSchema ],
           locations: [ locationSchema ],
           inMessages: [ inMessageSchema],
           outMessages: [ outMessageSchema ]
       });
       module.exports = mongoose.model('users', userSchema);`

**Comment by gil0mendes** [comment]
That is also happening with me! This is a really critical bug, that breaks a lot of my code. 😞

**Comment by gil0mendes** [comment]
This bug also happen when we use Promises.

```javascript
api.models.get('repair')
  .findByIdAndUpdate(action.params.id, {
      state: 'waiting_repair',
      technician: action.params.technician
  })
  .catch(error => { next(error) })
  .then(repair => {
      // NOTE: The repair correspond to the old version 
      // and not the updated one
  })
```

**Comment by gil0mendes** [comment]
I think this is related with this [commit](https://github.com/Automattic/mongoose/commit/d337db63bb93bc6c5b195bce5c7fb8658618cca7).

**Comment by vkarpov15** [comment]
Thanks for reporting, fixed in master and will be fixed with next release

**Comment by vkarpov15** [comment]
Fix by https://github.com/Automattic/mongoose/commit/90e26d3ff142c7b622f787e2e7e0b9a54a1446ec
