### ISSUE TITLE
Fatal bug with promise on cast error

### ISSUE THREAD

**Issue by mrlove** [Automattic/mongoose#4731]
Hi guys,

i do struggle with the following lines of code:
```
return Fruits.update(
                {_id: "somebadid"},
                {
                    $set: {
                        name: "Apple"
                    }
                }
            )
            .then((data) => {
               console.log(data)
            })
            .catch((err) => {
                console.log(err)
            })
```

It never jumps into the catch block, when I've got an cast exception...

Can someone help me out?

Best,
mrlove

**Comment by mrlove** [comment]
Update:
While debugging, I figuerd out, that the error is thrown instead of handed over to the promise. This is an bug because you have to write something like this:
```
Q.promise((resolve, reject) => {
try {
Fruits.update(
                {_id: "somebadid"},
                {
                    $set: {
                        name: "Apple"
                    }
                }
            )
            .then((data) => {
               console.log(data)
            })
            .catch((err) => {
                console.log(err)
            })
} catch(e) {
 reject(e)
}
})
```

**Comment by vkarpov15** [comment]
Yeah this behavior is [deprecated for 5.0](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings) but unhappily maintained in 4.x for backwards compatibility. There's a undocumented `dontThrowCastError` option (see #3512) that's there as a hacky solution for now. Follow #3512 for updates.
