### ISSUE TITLE
Timeout on long-running queries in 4.6.2, while 4.4.20 works fine

### ISSUE THREAD

**Issue by jkrenge** [Automattic/mongoose#4737]
We recently upgraded the dependency and then ran into problems with long-running queries (5 minutes and more).

Our old version with following connect parameters works fine, 4.6.2 works fine (will check 4.7.0 as well):

```javascript
{
  path: 'mongodb://user:pass@server-1,server-2/database?replicaSet=RS&readPreference=secondary',
  options: {
    db: {
      native_parser: true,
    },
    server: {
      poolSize: 5,
      socketOptions: {
        keepAlive: true,
      },
    },
    replset: {
      rs_name: 'RS',
    },
  },
}
```

**Comment by vkarpov15** [comment]
What sort of "problems"? Might be related to #4660

**Comment by jkrenge** [comment]
Ah sorry, forgot to clarify in the text, it's only in the subject:

I am encountering timeouts after a rather short time (1 minute or so).

**Comment by vkarpov15** [comment]
Is there an error message with a stack trace or something like that?

**Comment by varunjayaraman** [comment]
@jkrenge I'm going to close this for now since it's been stale for over a month. If you have further details or a stack trace or something, feel free to comment and I'll consider reopening.
