### ISSUE TITLE
Error: "The 2nd parameter to `mongoose.model()` should be a schema or a POJO" after upgrading mongoose (discriminator related)

### ISSUE THREAD

**Issue by antonioaltamura** [Automattic/mongoose#4738]
I'm not sure what's the problem, after upgrading mongoose I get  the error in title at the row
`var doc = mongoose.model('doc',docSchema);
`

The entire code
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var caseNote = mongoose.model('caseNote');
var ObjectId=mongoose.Schema.Types.ObjectId;
var models = require('./');
var autopopulate = require('mongoose-autopopulate');

var docSchema_raw = new Schema({
    decidingBody:{type:String},
},{discriminatorKey : '_type'});

var docSchema = caseNote.discriminator('doc',  docSchema_raw);

var doc = mongoose.model('doc',docSchema);

exports.docSchema = docSchema;
module.exports = doc;
```

**Comment by adeelhussain** [comment]
@antonioaltamura why you are registering your **doc** model again?
try this.

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var caseNote = mongoose.model('caseNote');
var ObjectId=mongoose.Schema.Types.ObjectId;
var models = require('./');
var autopopulate = require('mongoose-autopopulate');

var docSchema_raw = new Schema({
    decidingBody:{type:String},
},{discriminatorKey : '_type'});

var docSchema = caseNote.discriminator('doc',  docSchema_raw);

var doc = mongoose.model('doc');

exports.docSchema = docSchema;
module.exports = doc;
```

**Comment by antonioaltamura** [comment]
I'm sorry, I don't get what exactly means 
`var doc = mongoose.model('doc');`

which schema am I defining 'linked' the model `doc`?

**Comment by adeelhussain** [comment]
Did you try to run my block of code?

**Comment by vkarpov15** [comment]
Why are you passing a model as the second parameter to `mongoose.model()`? That's not right. I'd imagine you just want to export `docSchema`, which is misleadingly named because it isn't a schema, it's actually a model.

**Comment by antonioaltamura** [comment]
So the right way to register `doc` as inherited model of the model "caseNote" is simply
 `var docSchema = caseNote.discriminator('doc',  docSchema_raw);
var doc = mongoose.model('doc'); `

just to be sure :)

**Comment by adeelhussain** [comment]
Exactly :)

**Comment by vkarpov15** [comment]
I think you're conflating documents and models. `mongoose.model()` returns a model, and then `new MyModel()` gives you a document.

**Comment by antonioaltamura** [comment]
There is no new Model here :)
I'm in doubt how the `doc` model is defined by the `docSchema` using @adeelhussain (working) code :)

**Comment by Partho-FRz** [comment]
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var caseNote = mongoose.model('caseNote');
var ObjectId=mongoose.Schema.Types.ObjectId;
var models = require('./');
var autopopulate = require('mongoose-autopopulate');

var docSchema = new mongoose.Schema({
    decidingBody:{type:String},
},{discriminatorKey : '_type'});

var doc = mongoose.model('doc',docSchema);

exports.docSchema = docSchema;
module.exports = doc;


//this should for You :)

**Comment by bvedad** [comment]
Error occurs because `discriminator` method returns model object but `mongoose.model` method expects schema. This should be solved with:
`var docSchema = caseNote.discriminator('doc',  docSchema_raw);
var doc = mongoose.model('doc',docSchema.scheme);`
