### ISSUE TITLE
>= 4.6.7 broke select for some nested paths with defaults

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#4739]
This is linked to https://github.com/Automattic/mongoose/commit/db30110ed5835c4afe36beccff188e11f65ef5b8 that was partially reversed with https://github.com/Automattic/mongoose/commit/1b7e48384eb06d0416f53883b40be1f027b9bf13 to fix https://github.com/Automattic/mongoose/issues/4707.

This time I've had a really hard time creating a reproducible script test but my build is failing again with 4.7.0 and since the project is open source it can be used to see where the problem lies.

I've setup a branch where the only test running is the one impacted by this bug https://github.com/HabitRPG/habitica/tree/paglias/mongoose-reproduce-select-bug

If you download the branch, run `npm install` and then `npm run test:api-v3:integration` you'll see that a test is failing because the returned results do not include the `preferences.sleep` field although it's listed in the fields to select. The field has a default value of `false`. I've also enabled mongoose debugging and added some extra logging to show where the problem lies.

The main point is that installing mongoose 4.6.6 or simply editing `node_modules/mongoose/document.js` manually to revert the remaining piece of https://github.com/Automattic/mongoose/commit/db30110ed5835c4afe36beccff188e11f65ef5b8 is enough to fix the problem and make sure the field is correctly returned when selected.

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, I'll check this out ASAP

**Comment by vkarpov15** [comment]
@paglias that's strange, looks like I can't successfully `npm install` unless I run this on a mac? Last time I cloned your repo it worked fine...

```
npm ERR! Linux 3.16.0-43-generic
npm ERR! argv "/home/val/Workspace/node-v6.9.0-linux-x64/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/val/Workspace/10gen/habitica/npm-debug.log
```

If so, gonna have to postpone this because my macbook is a few thousand miles away at the moment.

**Comment by paglias** [comment]
@vkarpov15 there's a bug in npm 3.10.8 (fixed in 3.10.10 or 4) but the easiest way is to just remove the npm-shrinkwrap.json file and run npm install without it

**Comment by vkarpov15** [comment]
Ok got the test working (rather failing), thanks for clarifying :+1: I'll upgrade npm next time.

Also, random question, how'd you get it to send desktop push notifications when your test fails?

**Comment by paglias** [comment]
Does it? I never get notifications on my Mac :) It may be a linux or windows thing

**Comment by vkarpov15** [comment]
Fixed, thanks for the repro. In https://github.com/Automattic/mongoose/commit/db30110ed5835c4afe36beccff188e11f65ef5b8 I didn't quite flesh out the `hasIncludedChildren` idea I was trying to get at and it caused some issues. Appreciate it, but man y'all's tests are slow :p  

Also, here's the push notification I get. Never seen this on any project before so I'm curious how you guys got it.

![image](https://cloud.githubusercontent.com/assets/1620265/20644543/771e1752-b3ec-11e6-98f8-63a09f8fc135.png)

**Comment by paglias** [comment]
Thanks for the fix! I've asked my coworkers but it looks like they don't get the notifications either. I think it could be a Mocha's thing https://github.com/mochajs/mocha/wiki/Growl-Notifications
