### ISSUE TITLE
Unhandled promise rejection when mongoose.createConnection failed.

### ISSUE THREAD

**Issue by micromaomao** [Automattic/mongoose#4742]
The following code:

    const mongoose = require('mongoose')
    mongoose.Promise = global.Promise // Error gone without this.
    
    let db = mongoose.createConnection('mongodb://127.255.255.255') // Will fail
    db.on('error', err => {
      console.error(err)
      // Wait for promise
      setTimeout(() => process.exit(0), 1000)
    })
    db.on('open', () => {
      console.log('Database open!')
      process.exit(1)
    })

Gives out

    (node:10700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [127.255.255.255:27017] on first connect
    (node:10700) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----

Looks like [`Connection::open` returns a rejected Promise when any error happens](https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L292), but [`createConnection`](https://github.com/Automattic/mongoose/blob/master/lib/index.js#L177) which calls `Connection::open` [is not handling the rejection](https://github.com/Automattic/mongoose/blob/master/lib/index.js#L189), nor returning the promise back.

Without `mongoose.Promise = global.Promise`, everything seems to work fine. Maybe the default Promise engine which mongoose use hides unhandled rejection?

**Comment by vkarpov15** [comment]
The default promise lib for mongoose 4 actually doesn't do any tracking of unhandled rejections :)

**Comment by shaunpersad** [comment]
It seems like this same issue is back in 4.9.1.  I haven't found exactly where the unhandled promise is, but the same scenario that was initially described is happening.

**Comment by vkarpov15** [comment]
@shaunpersad please open up a new issue with a code sample that demonstrates your issue. `process.on('unhandledRejection', err => console.log(err.stack))` would be helpful for you finding the unhandled rejection
