### ISSUE TITLE
Mongoose bower

### ISSUE THREAD

**Issue by patrikx3** [Automattic/mongoose#4750]
How can i use mongoose with bower?
I want to use the schemas / models shared for validations.

**Comment by vkarpov15** [comment]
Not supported atm. You'd have to use browserify or webpack or something similar. Didn't know people still used bower :)

**Comment by patrikx3** [comment]
What do you mean? Bower is the biggest.
Bower 26m, Webpack 2m, browserify 579k

![image](https://cloud.githubusercontent.com/assets/4770180/20858193/805fe25c-b93f-11e6-9274-404eb0da81bc.png)
![image](https://cloud.githubusercontent.com/assets/4770180/20858197/8564d06e-b93f-11e6-94a8-6d08c88c87a8.png)

![image](https://cloud.githubusercontent.com/assets/4770180/20858198/8abcdb88-b93f-11e6-8874-dec524fa698d.png)
