### ISSUE TITLE
Getting weird exception while setting value to virtual fields using Mongoose model

### ISSUE THREAD

**Issue by suman-gulapalemmu** [Automattic/mongoose#4751]
I have posted question in StackOverFlow and here is the [link](http://stackoverflow.com/questions/40839816). 

Please need help from someone. 

Thanks in advance.

**Comment by vkarpov15** [comment]
```javascript
StatusSchema.virtual('count')
    .get(function () {
        return this.count;
    })
    .set(function (count) {
        this.count = count;
    });
```

This will trigger an infinite recursion whenever you set count, because setting `count` triggers the `.set()` handler, which in turn triggers the `.set()` handler again because it sets count.
