### ISSUE TITLE
Search By ID gives "Can't use $where with Number." error in Mongoose

### ISSUE THREAD

**Issue by vaijal** [Automattic/mongoose#4752]
I want to search by ID.  Below query works fine with MongoDB but not with mongoose.

db.getCollection('country').find({ $where: "/^51.*/.test(this._id)" });

I get below error with mongoose

"err":{"message":"Can't use $where with Number.","name":"Error","stack":"Error: Can't use $where with Number.\n  at SchemaNumber.castForQuery (/home/pcuser/Projects/country/node_modules/mongoose/lib/schema/number.js:278:13)\n

**Comment by vkarpov15** [comment]
Show the query you're executing. We have tests in place for `$where`, and that error makes it look like you're doing something like `MyModel.find({ num: { $where: fn } });`, and `$where` needs to be a top-level operator
