### ISSUE TITLE
Is the docs about discriminator still relevant?

### ISSUE THREAD

**Issue by agusputra** [Automattic/mongoose#4754]
I read this: [http//mongoosejs.com/docs/discriminators.html](http//mongoosejs.com/docs/discriminators.html)
And in the sample it sets discriminatorKey. But I have an error when try to set it.
So, Is it allowed to set discriminatorKey? If not, I think the docs must be edited.

**Comment by vkarpov15** [comment]
Where in the sample does it set the discriminator key? What's the error you receive? Do you mean setting the `discriminatorKey` option on a schema or the discriminator key on a doc? Please clarify.
