### ISSUE TITLE
npm warning: deprecated mongodb dependency

### ISSUE THREAD

**Issue by alanrsoares** [Automattic/mongoose#4758]
NPM warning when installing:
```
npm WARN deprecated mongodb@2.2.11: please upgrade to 2.2.12 or higher
```

**Comment by kyrylkov** [comment]
The same issue after upgrade to Mongoose 4.7.2   Please upgrade MongoDB driver 2.2.12

**Comment by alanrsoares** [comment]
So, I've forked mongoose, tried upgrading the MongoDB to 2.2.12 and it broke a lot of tests. Guess the problem is a bit deeper than it looks

**Comment by sandfox** [comment]
PR with failing tests here: https://github.com/Automattic/mongoose/pull/4753

**Comment by RafaelRViana** [comment]
Anybody knows when 4.7.2 will be released?

**Comment by vkarpov15** [comment]
ETA is today (December 6, 2016)

**Comment by mgcrea** [comment]
2.2.12 has been deprecated as well:

```
warning mongoose > mongodb@2.2.12: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return value
```

**Comment by vkarpov15** [comment]
4.7.3 is out and uses 2.2.16
