### ISSUE TITLE
What about decimal ?

### ISSUE THREAD

**Issue by YouriT** [Automattic/mongoose#4759]
Decimal BSON type has been introduced in Mongo 3.4 therefore, it would be convenient that this type would be also available within mongoose.

For more informations => https://docs.mongodb.com/manual/tutorial/model-monetary-data/#numeric-decimal

I'm quickly checking how long it would take me and checking if I can put that on my roadmap

**Comment by YouriT** [comment]
Some basic doc can be found here: http://mongodb.github.io/node-mongodb-native/2.2/tutorials/crud/

**Comment by hungchai** [comment]
Decimal Bson type is one of important feature in Mongo 3.4. Hope that available within mongoose as soon as possible. Thanks

**Comment by YouriT** [comment]
Yup, let's see what the people here say :)

**Comment by vkarpov15** [comment]
Yep definitely a major priority, will release soon :+1:

**Comment by YouriT** [comment]
@vkarpov15 wasn't expecting less from your side, always reactive! ⚡️

**Comment by marcelh-gh** [comment]
In the 5.0.8 docs I still just find Number as numeric type.

Does the fixed label assigned to this issue not mean that a decimal type was implemented?

**Comment by YouriT** [comment]
@marcelh-gh yup it has been. You can check the above commit reference: 61d665c

Documentation doesn't seem up to date, I suggest you open a new issue about it.

Strangely it was in the [previous docs](http://mongoosejs.com/docs/4.x/docs/api.html#schema-decimal128-js).

**Comment by marcelh-gh** [comment]
@YouriT thanks a lot for the quick answer. Awesome!

**Comment by marcelh-gh** [comment]
@YouriT so, there is a Decimal128 type. What about integer/ long? I didn't find anything in the old docs...
