### ISSUE TITLE
Create a text index with with a specific language

### ISSUE THREAD

**Issue by rossimo** [Automattic/mongoose#4764]
Is there a way in Mongoose schema to define a text index with a specific default language?

I.E., something analogous to:
```
db.blog.createIndex( { summary: "text" }, { default_language: "none" } );
```

**Comment by vkarpov15** [comment]
`blogSchema.index({ summary: 'text' }, { default_language: 'none' });`

Or

`Blog.collection.createIndex({ summary: 'text' }, { default_language: 'none' });` should work
