### ISSUE TITLE
aggregate stream not calling function on close event

### ISSUE THREAD

**Issue by lager1** [Automattic/mongoose#4767]
I have this code:

```
var stream = req.db.succ_logins.aggregate(aggregate_query).cursor({ batchSize: 1000 }).exec().stream();
var data = [];

 stream.on('error', function (err) {
   console.error(err);
 }); 

 stream.on('data', function(item) {
   console.log(item);
   data.push(item);
 });

 stream.on('close', function(items) {
   console.log("close");
   respond(data, res);
 });
```

All data are logged to the console but the close function does not get called. Can you explain, where is there problem? Am I using the api incorrectly somehow?

I am using mongoose 4.6.8 and node 6.5.0.

**Comment by vkarpov15** [comment]
You should probably use the [`end` event instead](https://nodejs.org/api/stream.html#stream_event_end) of close. The close event has slightly different semantics and 'end' is usually the right choice for readable streams.

**Comment by lager1** [comment]
thanks for clarification, works fine.
