### ISSUE TITLE
allow to populate linked model under specified field

### ISSUE THREAD

**Issue by stalniy** [Automattic/mongoose#4773]
For example, I have a relation: Task belongs to Group. And I want to have both `group` and `groupId` as separate field in my resulting task object.

Currently it's impossible because populated group replaces id field.
```js
const mongoose = require('mongoose')
const schemas = {}

schemas.Task = mongoose.Schema({
  name: String,
  attachments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'File' }],
  groupId: {
    ref: 'Group',
    type: mongoose.Schema.Types.ObjectId,
    populateAs: 'group' // <----- feature request!
  }
})

schemas.Group = mongoose.Schema({
  name: String,
  tasks: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Task' }]
})

Object.keys(schemas).forEach(name => {
  mongoose.model(name, schemas[name])
})

mongoose.connect('localhost/api')

const getTask = () => mongoose.model('Task').findOne(null, { name: 1, groupId: 1 })
  .populate('groupId')

getTask().then(task => {
  console.log(task.groupId) // outputs object
})
```

My suggestion is to add `populateAs` option which is just a name of the property where the resulting object will be populated. 

So that, in other parts of application shouldn't worry whether my task model is populated ( this will allow to always use `task.groupId` if I need an id instead of checking the type of `task.group` and use `task.group` if it's a string and `task.group._id` if it's an object)

**Comment by vkarpov15** [comment]
Take a look at [the virtual populate functionality](http://thecodebarbarian.com/mongoose-virtual-populate.html), this is one of the many use cases where virtual populate is better than conventional populate.

```javascript
schemas.Task = mongoose.Schema({
  name: String,
  attachments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'File' }],
  groupId: {
    ref: 'Group',
    type: mongoose.Schema.Types.ObjectId
  }
})

schemas.Task.virtual('group', {
  ref: 'Group',
  localField: 'groupId',
  foreignField: '_id',
  justOne: true
});

schemas.Group = mongoose.Schema({
  name: String,
  tasks: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Task' }]
})
```

You can then do `mongoose.model('Task').findOne().populate('group')`

**Comment by stalniy** [comment]
@vkarpov15
There are some downsides of virtual populate:
- virtual fields are not included by default in json
- if I have a virtual field which I don't want to have in json + virtual population. The result redundant/private info in resulting json
- it's not possible to reassign associated record by using virtual population

I looked through source code of population and I believe it shouldn't be hard. 

Maybe you can explain me why it was not done before or which pitfalls are there. 
So that, I'll be able to create PR

**Comment by vkarpov15** [comment]
1 and 2 are very good points. I'd much rather improve virtuals to make it possible to specify which virtuals to include in JSON output than add yet another option to an already bloated conventional populate API. 

Number 3 is very much by design - modifying populated fields is a common source of confusion and we'd rather that not be possible.
