### ISSUE TITLE
Webpack with Mongoose - mongoose.model is not a function

### ISSUE THREAD

**Issue by rrtigga** [Automattic/mongoose#4779]
I'm using Webpack to use require modules in the browser; however, I'm getting the following error:
 

    Uncaught TypeError: mongoose.model is not a function
        at Object.<anonymous> (bundle.js:44338)
        at __webpack_require__ (bundle.js:20)
        at Object.<anonymous> (bundle.js:48)
        at Object.<anonymous> (bundle.js:68)
        at __webpack_require__ (bundle.js:20)
        at bundle.js:40
        at bundle.js:43

I know mongoose has some limitations in the browser according to http://mongoosejs.com/docs/browser.html and **I even included the script tag suggested and still receiving the error**.

I have also exported my module using mongoose correctly:

    var mongoose  = require('mongoose');
    var Schema  = mongoose.Schema;
    
    var ProductSchema = new Schema({
        imageURL: String,
        productName: String,
        productType: String,
        price: String
    }, {collection: 'products'});
    
    module.exports = mongoose.model('products', ProductSchema);

My webpack.config.js is configured correctly as well

    var webpack = require('webpack');
    var path = require('path');
    var fs = require('fs');
    var request = require('request');
    var CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
    
    module.exports = {
        entry: "./main.js",
        output: {
            path: __dirname,
            filename: "bundle.js"
        },
        module: {
        loaders: [
          { test: /\.json$/, loader: 'json-loader' }
            ]
        },
        resolve: {
            extensions: ['', '.webpack.js', '.web.js', '.js', '.json']
        },
        node: {
            console: 'empty',
            fs: 'empty',
            net: 'empty',
            tls: 'empty'
        }
    }

**Why is this occurring? And how can this be resolved?**

**Comment by vkarpov15** [comment]
Models are not supported in the browser, see docs http://mongoosejs.com/docs/browser.html . The browser build is meant to be a minimal way to get schemas to work in the browser, there's no full models because you can't really query from the browser
