### ISSUE TITLE
new:true not returning modified document from model.findByIdAndUpdate

### ISSUE THREAD

**Issue by paul42** [Automattic/mongoose#4780]
I've tried out both findByIdAndUpdate and findOneAndUpdate with an {_id:this.params.id} query selector, but having trouble getting it to return the new, modified document. after querying a second time I get the updated document. 

current version is 4.7.1

example code:
````
var models = require('../../modelSetup');
var resource = models.user;
var mongoResponse = yield resource.findByIdAndUpdate(this.params.id, this.request.fields, {new:true, runValidators:true}).exec();
_.set(this, 'body.user', mongoResponse);
````

am I reading the documentation wrong and making my options object incorrectly?

Thanks for any help, love the library!

**Comment by vkarpov15** [comment]
That should be correct. Can you provide a more complete code sample? We have plenty of tests surrounding `new: true` and they're all passing.

**Comment by paul42** [comment]
I think it's something wrong on my end, I have another model that does not appear to be exhibiting this behavior - it's a bit of a tangle in here, do you have any suggestions for likely areas to look or how to compare two models to find a difference?

Sorry if it's vague, I appreciate your time though!

**Comment by vkarpov15** [comment]
Sure, `require('mongoose').set('debug', true)` will print messages to the console about what mongoose is actually sending to mongodb.
