### ISSUE TITLE
'select as' for select queries?

### ISSUE THREAD

**Issue by donnyjeremiah** [Automattic/mongoose#4782]
Is there any way to select 'as' and use a temporary name, like we do in mysql? I've got documents like this:
```
[{
  stats: {
    monday:{goals:10,tackles:20},
    tuesday:{goals:10,tackles:20}
  }
}]
```

I need to get stats.monday or stats.whatever 'as' just stats. So I can use stats.goals or stats.tackles. I can assign stats.monday to stats, but for hundreds of records, this seems a bit to much.

**Comment by vkarpov15** [comment]
Not supported with queries, you'd have to use the [mongodb aggregation framework](https://docs.mongodb.com/v3.2/reference/aggregation/) or just do it manually.
