### ISSUE TITLE
auto created time stamp format

### ISSUE THREAD

**Issue by iiitmahesh** [Automattic/mongoose#4783]
The following snippet is my code
```
var ItemSchema = new Schema({
    name: { type: String, required: true, trim: true }
},
{
    timestamps: true
});
```

I got this "2016-12-07T11:46:46.066Z" in database. Could somebody please explain time stamp format, and how change time zone?? is it take mongoDB server time zone??

**Comment by vkarpov15** [comment]
MongoDB server stores timestamps as [plain-old 64-bit ints](http://bsonspec.org/spec.html), no timezone. The MongoDB shell displays dates in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format in [UTC](https://www.timeanddate.com/time/aboututc.html). In node.js, you'll see dates as native JavaScript date objects, which implicitly use the current server time zone. Would recommend you use [moment](https://www.npmjs.com/package/moment-timezone) if you need sophisticated timezone functionality.

**Comment by khantopa** [comment]
you can use this date in ui just give " {{ item.date | date: 'medium'}}   "
