### ISSUE TITLE
Mongoose Replica Connection String Not working when trying to connect

### ISSUE THREAD

**Issue by shreejibawa** [Automattic/mongoose#4784]
Mongoose v4.3.4.

I am trying to connect to AWS MongoDB instances and its not even attempting to connect:

This is the connection URI format I am using:

`mongodb://<usr>:<pwd>@host:port,host2:port2/db`

And this is the code I am using to connect.

```javascript
var mongoose = require('mongoose');
var dbOptions = { server: { socketOptions: { keepAlive: 300000, connectTimeoutMS: 30000 } }, 
            replset: { socketOptions: { keepAlive: 300000, connectTimeoutMS : 30000 } } };

mongoose.connect(uri, dbOptions);

```

I am not getting anything in error callback either. I also added logs for possible events.. none of the events are firing. If I remove host2:port2 it works. So issue seems to be with the connection string. But connection string looks totally fine.. but still its not working.

Am I missing anything?

**Comment by vkarpov15** [comment]
Not that I can see. What events are you logging?

**Comment by mathewjeorge** [comment]
@vkarpov15 connecting, open, error.

**Comment by shreejibawa** [comment]
@vkarpov15 connecting, open, error.

**Comment by vkarpov15** [comment]
Weird. Can you connect using the node.js driver or the mongodb shell?

**Comment by varunjayaraman** [comment]
@shreejibawa any update on using the driver or mongodb shell?
