### ISSUE TITLE
Mongoose model import broken in latest releases

### ISSUE THREAD

**Issue by bionetmarco** [Automattic/mongoose#4786]
Just an FYI, I had to quickly revert back to **4.4.13** (I had been using the import with a caret **^4.4.13**, which is equivalent to **4.x**) due the recent releases breaking how I import my models.

```
Error: The 2nd parameter to `mongoose.model()` should be a schema or a POJO
```

My model file:
```
var mongoose = require('mongoose');
var db = require('../api/db.js');

var userSchema = new mongoose.Schema({
    createdAt: {type:Date},
    email: {type: String, unique: true, lowercase: true },
    displayName: {
        firstName: {type : String},
        lastName: {type : String}
    }
});

var User = db.model('User', userSchema);
module.exports = User;
```

My import:

```
var User = mongoose.model('User', require('../models/user.js'));
```

**Comment by vkarpov15** [comment]
The way you're importing your model is quite wrong. You really should just export a schema if you want to create multiple models with the same schema, passing a model to `mongoose.model()` was never supported.
