### ISSUE TITLE
MongoDB schema with nested validation and strict mode

### ISSUE THREAD

**Issue by linvi** [Automattic/mongoose#4788]
Hello,

I have been able to have a correct schema validation with the following rules :

* Only the expected field should be saved (hence the strict mode)
* The `User.Account` should be nullable. If null, the required fields are not preventing the schema from being saved.
* If `User.Account` is not null, The validation rules to be respected (`.password` and `.email` required).
* I do NOT want to create an `AccountSchema` because it pollutes the account with an `_id` field.

I have been able to do this with 2 schemas (`UserSchema` and `AccountSchema`). But as mentioned, the problem is that it creates a `_id` field in the `User.Account` field.

``` js
const AccountSchema: Mongoose.Schema = mongoose.Schema({
    password: { type: String, required: true },
    email: { type: String, required: true }
}, {
        strict: 'throw',
        useNestedStrict: true
    });

const UserSchema: Mongoose.Schema = mongoose.Schema({
    name: { type: String, required: true },
    account: AccountSchema
}, {
        strict: 'throw',
        useNestedStrict: true
    });
```

Here is a solution with only a `UserSchema` but the field strict mode and validation are not working as expected.

``` js
const UserSchema: Mongoose.Schema = mongoose.Schema({
    name: { type: String, required: true },
    account: {
        type: {
            password: { type: String, required: true },
            email: { type: String, required: true }
        },
        required: false
    }
}, {
        strict: 'throw',
        useNestedStrict: true
    });
```

Could anyone let me know what I am missing here?

By the way, I tried custom validation which does work, but it does not guarantee the object schema safety that strict mode should ensure.

Thanks

**Comment by vkarpov15** [comment]
```javascript
const AccountSchema: Mongoose.Schema = mongoose.Schema({
    password: { type: String, required: true },
    email: { type: String, required: true }
}, {
        _id: false, // <---
        strict: 'throw',
        useNestedStrict: true
    });
```

Add `_id: false` to make it so that mongoose doesn't add an _id by default

**Comment by apurv195** [comment]
> ```js
> const AccountSchema: Mongoose.Schema = mongoose.Schema({
>     password: { type: String, required: true },
>     email: { type: String, required: true }
> }, {
>         _id: false, // <---
>         strict: 'throw',
>         useNestedStrict: true
>     });
> ```
> 
> Add `_id: false` to make it so that mongoose doesn't add an _id by default

not working, getting error if set _id to false
`document must have an _id before saving`

**Comment by vkarpov15** [comment]
@apurv195 the MongoDB server always adds an `_id` property by default, no way to disable it. So if you try to save a document without an `_id`, MongoDB server will add one for you.
