### ISSUE TITLE
Why does discriminator key need to be set on child models?

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#4790]
In docs:
```
    var options = {discriminatorKey: 'kind'};

    var eventSchema = new mongoose.Schema({time: Date}, options);
    var Event = mongoose.model('Event', eventSchema);

   // THIS FAILS, gets error can't customize discriminator option discriminatorKey
    var ClickedLinkEvent = Event.discriminator('ClickedLink',
      new mongoose.Schema({url: String}, {}));

  // This is required to work
        var ClickedLinkEvent = Event.discriminator('ClickedLink',
      new mongoose.Schema({url: String}, options));
```

It's a small thing but intuitively I would've just though child models inherit the discriminator key.

**Comment by hooke** [comment]
Hey, now the [documentation](http://mongoosejs.com/docs/discriminators.html), which claimed to be of Version 4.7.3, should be changed appropriately:

```
var options = {discriminatorKey: 'kind'};

    var eventSchema = new mongoose.Schema({time: Date}, options);
    var Event = mongoose.model('Event', eventSchema);

    // ClickedLinkEvent is a special type of Event that has
    // a URL.
    var ClickedLinkEvent = Event.discriminator('ClickedLink',
      new mongoose.Schema({url: String}));
```

 (otherwise I got an error with this example in Mongoose v.4.7.3)

**Comment by vkarpov15** [comment]
What error exactly? Below script works for me:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4790');
mongoose.set('debug', true);

var options = {discriminatorKey: 'kind'};

    var eventSchema = new mongoose.Schema({time: Date}, options);
    var Event = mongoose.model('Event', eventSchema);

    // ClickedLinkEvent is a special type of Event that has
    // a URL.
    var ClickedLinkEvent = Event.discriminator('ClickedLink',
      new mongoose.Schema({url: String}));
```

**Comment by vkarpov15** [comment]
@KrishnanSriram I think you're getting confused because `Person.discriminator()` returns a **model** not a **schema**. Specifically, the below code is problematic:

```javascript
var ContactSchema = Person.discriminator('Contact',
    new mongoose.Schema({phone: String}));

module.exports = mongoose.model('Contact', ContactSchema);
```

Should be:

```javascript
module.exports = Person.discriminator('Contact',
    new mongoose.Schema({phone: String}));
```

The below script works fine for me:

```javascript
const mongoose = require('mongoose');

const GITHUB_ISSUE = `gh-6116`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
mongoose.Promise = global.Promise;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const options = {discriminatorKey: 'kind'};

  const PersonSchema = new mongoose.Schema({name: String}, options);
  const Person = mongoose.model('Person', PersonSchema);

  const Contact = Person.discriminator('Contact',
    new mongoose.Schema({phone: String}));

  console.log('done');
}
```

**Comment by RobertWSaunders** [comment]
Why was this issue closed @vkarpov15? The [docs](https://mongoosejs.com/docs/discriminators.html) are still incorrect, `ClickedLinkEvent` should not be passing `options` to its schema constructor.

**Comment by vkarpov15** [comment]
@RobertWSaunders this issue was closed because as far as we can tell there was no issue. Couldn't reproduce and no response => closed.

Can you point out specifically what in those docs is incorrect?

**Comment by RobertWSaunders** [comment]
I think @hooke mentioned the incorrect docs. The `ClickedLinkEvent` should be passing `options` to its schema constructor in the example. See below: 

```
var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({time: Date}, options);
var Event = mongoose.model('Event', eventSchema);

var ClickedLinkEvent = Event.discriminator('ClickedLink', new mongoose.Schema({url: String}, options));
```

Instead it should be this:

```
var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({time: Date}, options);
var Event = mongoose.model('Event', eventSchema);

var ClickedLinkEvent = Event.discriminator('ClickedLink', new mongoose.Schema({url: String}));
```

**Comment by vkarpov15** [comment]
As far as I know, you need to pass the same options to the discriminator schema. What makes you think that you don't have to? Does the former code cause an error for you?

**Comment by RobertWSaunders** [comment]
Both the `eventSchema` and the schema for `ClickedLinkEvent` don't need `options`. Only `eventSchema` needs the discriminator key.

**Comment by vkarpov15** [comment]
I see what you mean. You don't need `options` in this particular case, but in general you do, because otherwise you might get "Can't customize discriminator option" errors. Since it is a little tricky to know when you need `options` and when you don't, the docs just always pass the `options` param.

**Comment by RobertWSaunders** [comment]
Sounds good to me, thanks for clarifying and providing a reason!
