### ISSUE TITLE
Mongoose timestamps updatedAt set value

### ISSUE THREAD

**Issue by fucazu** [Automattic/mongoose#4797]
I need to change the value that is stored in updatedAt, is there a way?
My case I've a mobile that manipulate information and then send to server, when I tried to set the date that is older then actual on updatedAt, it store the `Date.now()`.

**Comment by vkarpov15** [comment]
Not possible with `save()`, you need to do update. `Model.update({ _id: doc._id }, { updatedAt: myDate });`

**Comment by gualopezb** [comment]
@vkarpov15 the `updatedAt` isn't updated automatically when the Schema has the `timestamps` set, or should I have to change it manually?

**Comment by vkarpov15** [comment]
@gualopezb it should be getting set, is mongoose not setting `updatedAt()` correctly? If so, can you please show your code?

**Comment by gualopezb** [comment]
@vkarpov15 I realized that `updatedAt` is setting correctly when using `update` and `findOneAndUpdate` methods, but not for `updateOne`. Is that intentional?

**Comment by vkarpov15** [comment]
Nope that's a bug, will fix ASAP :+1:

**Comment by gualopezb** [comment]
@vkarpov15 #6282 fixes the bug. I added the corresponding test as well.

**Comment by vkarpov15** [comment]
Fixed by #6282
