### ISSUE TITLE
 throw StrictModeError if upsert with nonexisting field in condition #4757

### ISSUE THREAD

**Issue by talaviss** [Automattic/mongoose#4801]
In Mongoose 4.7.2 there was this fix  #4757 which is a true **breaking change**.

For my IMHO there should be a way to disable this behavior "to throw of error StrictModeError".

fix(query): throw StrictModeError if upsert with non existing field in condition #4757

lets say I have a schema that contains and id field,  
I'm working in strict mode = true.
I'm issuing a query to findAndUpdate({id:1,schema,data}, {upsert:true, now:true}}
the data object  doesn't **have** an id field, the schema object  does **have** an id field and  the query I do have id field
This causes the error to be thrown because of #4757 and causes backward compatibility issue.

**Comment by franciscocpg** [comment]
@talaviss 
Same problem here.
Why did you close the issue?
What was your solution?

**Comment by franciscocpg** [comment]
For anyone else having the same problem, the solution for me was to set [strict](http://mongoosejs.com/docs/guide.html#strict) to `false` in the schema

**Comment by vkarpov15** [comment]
The easiest solution is to turn `strict` off but I wouldn't recommend doing that unless you really know what you're doing, because you might accidentally upsert in a field that doesn't exist in your schema.
