### ISSUE TITLE
Using mongoose @ 4.5 and above causes process.domain to be undefined

### ISSUE THREAD

**Issue by brian-learningpool** [Automattic/mongoose#4803]
I've been looking to upgrade a project to Mongoose 4.6.2 but in my testing I noticed that something in versions 4.5 and above seems to cause `process.domain` to always be undefined.  I know `domain` is deprecated in Node.js, but it hasn't been removed yet. 

Does anyone have an idea what might have changed in version 4.5 and above which would cause this to break?

Thanks.

**Comment by vkarpov15** [comment]
Domains have always been a hopelessly broken piece of trash with zero redeeming qualities. I'd really rather avoid digging into that can of worms unless you have a really good reason to use use domains.

**Comment by andrew-borzenko** [comment]
See:
https://github.com/christkv/mongodb-core/issues/124
Domain support is turned off in version 2.0, which mongoose 4.6+ started using. To turn domains on pass: domainsEnabled = true.
`mongoose.connect(uri, {
					server: {
						domainsEnabled: true
					},...`

**Comment by vkarpov15** [comment]
Thanks @andrew-borzenko

**Comment by brian-learningpool** [comment]
Thank you, @andrew-borzenko!

**Comment by smartmasks** [comment]
Thanks Lot. :)
