### ISSUE TITLE
Question: .splice() on an array of embedded documents

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#4807]
We're trying to track down a bug we have with some embedded docs, I won't enter into the details but I've noticed that we're using `parentDoc.array.splice(subDocIndex, 1)` to remove embedded docs from the array.

Is this the right way to remove a subdoc? Or should I use `.remove()` on the subdoc? I'm concerned about the fact that `.splice()` won't correctly unregister the hooks registered on the subdocs.  In particular it's possible that a `pre('save')` hook attached to a subdoc removed with `.splice()` will still be executed when the parent is saved?

**Comment by vkarpov15** [comment]
If save hooks for a subdoc you spliced out still run, that's a bug, so if you could provide a repro script that would be excellent. `splice()` and `remove()` are mostly interchangeable, the big difference is that `splice()` translates to mongoose sending a `$set` on the whole array, whereas `remove()` translates to using `$pull` to remove the document by its `_id`. If you use `_id: false`, `remove()` will throw an error.

**Comment by paglias** [comment]
@vkarpov15 I'll try to create a reproduction but I'm not sure this is a bug in mongoose, I'm trying to debug a bug in our system where we have an embedded doc with this schema called `UserNotification`:

```
export let schema = new Schema({
  id: {
    type: String,
    default: uuid,
    validate: [validator.isUUID, 'Invalid uuid.'],
  },
  type: {type: String, required: true, enum: NOTIFICATION_TYPES},
  data: {type: Schema.Types.Mixed, default: () => {
    return {};
  }},
}, {
  strict: true,
  minimize: false, // So empty objects are returned
  _id: false, // use id instead of _id
});
```

plus a plugin that adds two fields (`updatedAt` and `createdAt`) and creates a `pre('save')` hook that sets `updatedAt` to `new Date()`. 

What we've been finding in the database are instances of this subdoc saved as `{ updatedAt: { $date: ... } }` without any other field and since we don't use update commands to edit that subdoc anywhere it shouldn't be impossible to save a subdoc without `type` that is a required field. 

Since I didn't have any better idea I thought that it could be due to .splice not removing the hooks correctly and thus causing the code to update `updatedAt` to run on a removed instance of `UserNotification` when the parent doc is saved.

I'll try to create a reproduction

**Comment by paglias** [comment]
I've been unable to create a repro script, if it matters we also have a 

```
    schema.pre('update', function preUpdateModel () {
      this.update({}, { $set: { updatedAt: new Date() } });
    });
```

attached to the subschema (comes with an internal plugin we use for most models) but I figured out it shouldn't run at all for subschemas so it cannot be the cause of our problems.

I'll leave the bug open for now, in case you may have an idea of what could cause this behavior but feel free to close it since it's likely not related to Mongoose

**Comment by vkarpov15** [comment]
I'll close this for now, re-open if you manage to figure out if this is a bug with mongoose
