### ISSUE TITLE
Offputting docs wording

### ISSUE THREAD

**Issue by cassfantastic** [Automattic/mongoose#4808]
Reading the docs on this page:
http://mongoosejs.com/docs/guide.html
You're using "Walter White is insane" as an example. 
![example](https://cloud.githubusercontent.com/assets/22797596/21211744/3be6ad0a-c2da-11e6-83dd-ee2e385abea5.PNG)
This is a bit offputting, insane isn't a pleasant word to use, especially when earlier the docs use dogs and cats and animals for the examples.

**Comment by vkarpov15** [comment]
Yeah I admit that isn't my favorite example either, doesn't fit at all with the rest of the docs. Thanks for the reminder.
