### ISSUE TITLE
schema with setters doesn't work

### ISSUE THREAD

**Issue by unutoiul** [Automattic/mongoose#4809]
I using exactly this example:

```javascript
function capitalize (val) {
  if (typeof val !== 'string') val = '';
  return val.charAt(0).toUpperCase() + val.substring(1);
}

// defining within the schema
var s = new Schema({ name: { type: String, set: capitalize }})

// or by retreiving its SchemaType
var s = new Schema({ name: String })
s.path('name').set(capitalize)
```

and the function capitalize never get triggered on findOnceAndUpdate() request.

What other option I need to enable or what i'm doing wrong?

PS. the getter is getting triggered..

Thanks,
Lucas

**Comment by vkarpov15** [comment]
`findOneAndUpdate()` does *not* trigger setters. Setters only get triggered when you modify the document, like `doc.name = 'test'`. See [docs](http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate) for more detail
