### ISSUE TITLE
How to track fields changes at update?

### ISSUE THREAD

**Issue by guzgarcia** [Automattic/mongoose#4811]
I have a `User` schema with a path `email`. I want track changes over this field, so, when the user changes his email, a job is executed. Which is the way to do it with mongoose, since the update hooks pass a Query instead a Document (can't use isModified(path))?

**Comment by guzgarcia** [comment]
Actually, instead of use Model.update, I follow this pattern:

- Fetch the model to update via ID
- Assign manually the new values (`user.email = data.email || user.email`)
- Use `save` method.

So, with this way I'm able to get the document inside the `pre` save hook and I can check if the path was changed via `doc.isModified('email')`.

Would be great if the newly updated doc is availabe on update and remove hooks too. It is possible?

**Comment by vkarpov15** [comment]
You can access `getUpdate()` in a pre update hook to check whether email is getting updated or not:

```javascript
mySchema.pre('update', function() {
  if (this.getUpdate().email) {
    // Run job
  }
});
```

You can't use `isModified()`, but `email` won't change unless `email` is in the update

**Comment by Peter-web-frontend** [comment]
Inspect this https://impersonation-frequent.github.io/boris/ comment
