### ISSUE TITLE
Mongoose.CreateConnection(...).Then Is Not A Function

### ISSUE THREAD

**Issue by edgeadjei** [Automattic/mongoose#4812]
I'm receiving an error when trying to initialize Mongoose.CreateConnection as a promise.
Since there's no indication that this is a supported feature in the documentation, My implementation is based on the fact that `mongoose.connect` has a promise wrapper (#4135).

```js
mongoose.createConnection(`${databaseConnectionUri}/${databaseName}`)
      .then((appDatabase) => {
        // {appDatabase} - database connection object
        return [appDatabase, clientModel().findOne({authDomain: databaseName, isActive: true}).lean().exec()];
      })
      .spread((appDatabase, client) => {
        ... 
      })
      .catch((err) => {
        ...
      });
```

Oddly enough i get the expected behavior when returning `mongoose.createConnection` inside a promise chain as shown below

```js
validateClient(clientDatabaseName)
      .then((databaseName) => {
        return mongoose.createConnection(`${databaseConnectionUri}/${databaseName}`);
      })
      .then((clientDb) => {
       ...
      })
      .catch((err) => {
        ...
      });
```

**Comment by vkarpov15** [comment]
`createConnection()` returns a connection rather than a promise, mostly for backwards compatibility reasons. However, because of buffering, you do not need to wait for `createConnection()` to execute to start using it.

**Comment by edgeadjei** [comment]
thank you
