### ISSUE TITLE
internal mixed field not updated even with markModified

### ISSUE THREAD

**Issue by fithwith** [Automattic/mongoose#4815]
I'm trying to update an internal field in a mixed object and even I'm using markModified its not reflecting in the database.
in the save callback I'm getting a successful reply, without error and with the modified object. but when checking the DB nothing changes.
here what I'm trying to do:

```
x.y.z++
x.markModified('y')
x.save(function(err,r){
console.log(r);
})
```

**Comment by vkarpov15** [comment]
Show schemas please?

**Comment by fithwith** [comment]
var tsch=new mongoose.Schema({
    y: mongoose.Schema.Types.Mixed,
    },{versionKey: false });

**Comment by fithwith** [comment]
sorry guys it was a problem coming from me, I was using as _id the type objectid then I changed it to a string without updating the data already there, after updating the data it works normally.
but from another side I got not warning or error, the field was coming from the DB as objectid and in the schema it was string.

**Comment by vkarpov15** [comment]
There's no error to be shown, it's perfectly expected behavior. With that schema you'll modify a document whose `_id` field is a string, not the doc whose `_id` field is an ObjectId.
