### ISSUE TITLE
findOneAndUpdate doesn't provide updated values when Collection is queried

### ISSUE THREAD

**Issue by Mastermaulik** [Automattic/mongoose#4822]
I am trying to update the sub document by giving sub document ID.

I have the following model:
```

{
    "_id" : ObjectId("5858b9d788e3438bed93c97a"),
    "modelType" : "Course",
    "name" : "course 1",
    "sections" : [
        {
            "id" : ObjectId("5858b9e188e3438bed93c97b"),
            "name" : "section 1",
            "position" : 1
        },
        {
            "id" : ObjectId("5858b9ec88e3438bed93c97c"),
            "name" : "section 2",
            "position" : 2
        }
    ]
}
```
Now, when i try to find and update using section's objectId as follows:

```
let value = await courseCollection.findOneAndUpdate(
        {"sections.id" : require('mongodb').ObjectId(sectionId)},
        { $set: {"sections.$.name":name}},
        { new : true}
      );
```
The value returned is not the updated value, even if the option new is provided as true. I am not doing any other thing apart from this, so I think there may be an issue with returning the updated document.

I think the problem here is not to query with subdocument id, if we are trying to query using Collection, we don't get the updated values. Also, other options that are passed like: fields are not taken into perspective as well.

**Comment by vkarpov15** [comment]
Is it updating the document in the database? Also, try using `sectionId` instead of `require('mongodb').ObjectId(sectionId)`, mongoose will cast to an objectid for you.
