### ISSUE TITLE
Accessing subdocument fields returns empty result

### ISSUE THREAD

**Issue by sudheerj** [Automattic/mongoose#4827]
When I try to retrieve records based on subdocument fields filters I'am always getting the empty result.Can you please confirm whether below query is proper or not.

```
  User.find({"hobbies.title":"sleeping"}).populate('hobbies friends').exec((err, res) => {
      err ? reject(err) : resolve(res);

```
Thanks in advance for the help.

**Comment by TrejGun** [comment]
probably you have to dig this way
```js
User.find({}).populate({path:'hobbies', match:{title:"sleeping"}).populate('friends')
```
then filter User with empty hobbies
but its better to distinct `hobbies` 
```js
Hobbies.distinct("_id", {title: "sleeping"})
.then(ids => 
User.find({hobbies:{$in: ids}}).populate(...)
)
```

**Comment by vkarpov15** [comment]
Mongoose doesn't let you query by ref fields, you can only query by properties that are within the document.
