### ISSUE TITLE
Document.markModified does not save path when object leaf is {}

### ISSUE THREAD

**Issue by AugustBrenner** [Automattic/mongoose#4829]
Given:

    const TestSchema =  new Schema({
        mixed: {}
    })

    const TestModel = mongoose.model('TestModel', TestSchema)

    const test = new TestModel()

Ignores mixed path when saving:

    test.mixed = { 'foo': { 'bar': {} } }
    test.markModified('mixed')

Successfully includes mixed path when saving:

    test.mixed = { 'foo': { 'bar': true } }
    test.markModified('mixed')

When:

    test.save()

**Comment by vkarpov15** [comment]
Use `minimize: false` in your schema. Mongoose will collapse empty objects by default.

```javascript
const TestSchema =  new Schema({
    mixed: {}
}, { minimize: false }) // <--

const TestModel = mongoose.model('TestModel', TestSchema)

const test = new TestModel()

test.mixed = { 'foo': { 'bar': {} } }
test.markModified('mixed')

test.save()
```
