### ISSUE TITLE
New MongoDB 3.4 Collation support in queries

### ISSUE THREAD

**Issue by emidelgo** [Automattic/mongoose#4839]
Hi,
the new MongoDB 3.4 introduced collation support to run case insensitive queries.
https://docs.mongodb.com/manual/reference/method/cursor.collation/#cursor.collation

To run a query supporting collation is needed set collation on cursor.

It would be important add complete support in mongoose for this feature.

**Comment by vkarpov15** [comment]
So currently you can just do `MyModel.find({}, null, { collation: collation });` (or `MyModel.find({}, null, { collation: collation }).cursor();` In 4.8 queries will have a nice helper function for this.

**Comment by frieck** [comment]
Hi @vkarpov15 
How can I set the collation while using the aggregation function?

**Comment by vkarpov15** [comment]
Currently somewhat tricky:

```javascript
var agg = MyModel.aggregate([ { $match: { /* ... */ } ]);
agg.options = { collation: { locale: 'en_US', strength: 1 } };
var promise = agg.exec();
```

Will add a helper for this too
