### ISSUE TITLE
When node.js server is inactive for some time, it shows connection timeout

### ISSUE THREAD

**Issue by immohitrathi** [Automattic/mongoose#4840]
**Bug**

**Error**

mongoose.connect(config.connectionString, function(err, database) {
  if (err) return console.log(err)
  psDb = database;
});

**What is the expected behavior?**
Connection should not timeout

**Please mention your node.js, mongoose and MongoDB version.**
"mongodb": "^2.1.4",
 "mongoose": "^4.7.4",
node: 6.9.2

**Comment by vkarpov15** [comment]
Can you define "inactive for some time" and "connection timeout"? I don't understand.

**Comment by varunjayaraman** [comment]
@immohitrathi I'm going to close this issue from lack of clarification. If you have more details, I'm open to reopening the issue.
