### ISSUE TITLE
Mongoose 4.7.5 / Populate Error

### ISSUE THREAD

**Issue by juanimarchese** [Automattic/mongoose#4843]
Hi! 

We update to latest version, and sudenly, the populate method stopped working.

We returned to 4.7.4 and it seams to work again.

Thanks!

**Comment by roomnoise** [comment]
Looks like it needs the model name at all times now:

  Article.populate(feed, {
    path: 'articles',
    select: '_id title',
    **model: 'Article'**
  }, function(err, coll) {})

due to #4817 

Whereas in the past it would pull it from the modelName.

**Comment by jiri-smolik** [comment]
Happened to me too, is it not supposed to be in a major version update, as it breaks the backwards compatibility? (as stated in https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers)

**Comment by vkarpov15** [comment]
What do your schemas look like @roomnoise @juanimarchese ?

**Comment by roomnoise** [comment]
@vkarpov15 here's a simplified version:

```
var FeedSchema = new Schema({
  ...
  articles: [{type: mongoose.Schema.Types.Mixed}],
  created_at: {type: Date, default: Date.now}
});
```

then when I try to populate articles below I have to explicitly add the model param, whereas in 4.7.4 I didn't.

```
Article.populate(feed_obj, {
  path: 'articles',
  select: '_id title',
  model: 'Article'
}, function(err, coll) {});
```

**Comment by swapkids** [comment]
I'm having the same issue upgrading from 4.7.0 -> 4.7.5 (stopping my API from working )-:)

**Comment by vkarpov15** [comment]
@swapkids sorry for the trouble. Please upgrade to 4.7.6 and the issue should go away. This is one of those rare cases where the behavior was documented but not tested and so a bug slipped through the cracks.
