### ISSUE TITLE
What kind of issues can happen when setting the bufferCommands to false?

### ISSUE THREAD

**Issue by talaviss** [Automattic/mongoose#4849]
**Do you want to request a *feature* or report a *bug*?**
More information.  can it lead to data loss? other issues?
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
If bufferCommands is false you'll just get an `error` in your callback (or a rejected promise) if mongoose is not connected to mongodb. By default mongoose will wait until you're connected connected to actually send your queries and write operations.
