### ISSUE TITLE
Cannot read property '$__' of undefined when using createConnection

### ISSUE THREAD

**Issue by steebchen** [Automattic/mongoose#4853]
I recently switched from using .connect to .createConnection and with the exact same schema, this error arises:

```
node_modules/mongoose/lib/types/embedded.js:234
    return !this.__parent.$__.validationError ||
                         ^
TypeError: Cannot read property '$__' of undefined
    at EmbeddedDocument.$isValid (/home/luca/websites/a/node_modules/@steebchen/helpers/node_modules/mongoose/lib/types/embedded.js:234:26)
    at /home/luca/websites/a/node_modules/@steebchen/helpers/node_modules/mongoose/lib/document.js:1278:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

My schema looks like this:

```
const schema = new global.mongoose.Schema({
  _id: String,
  size: Number,
  tags: [{
    _id: String,
    name: {
      type: String,
      ref: 'pr_tag',
      required: true
    }
  }]
})

module.exports = global.db.model('pr_item', schema)
```

Where global.db is the connection where I called .createConnection. When using mongoose.connect and mongoose.model, there is no error and all works fine.

node v6.6.0
mongoose@4.7.5

**Comment by steebchen** [comment]
No idea how I got it to work, but it seems the issue arise because I had another connection with mongoose.connect open and I didn't realize that.

**Comment by vkarpov15** [comment]
How are you calling createConnection?

**Comment by steebchen** [comment]
Exactly like in the example, that's why I left it out.
```
global.mongoose = require('mongoose')
mongoose.Promise = Promise
const connection = mongoose.createConnection('mongodb://localhost:27017/main')
connection.once('connected', () => {
  console.log('connected')
})
```

I will close this since it seems that like it's not reproducible, since I cannot post my whole project which is quite big. I avoided the problem by not using `mongoose.createConnection`, I solved my problem another way with still using `mongoose.connect`.

**Comment by appacea** [comment]
I have the same problem, I´m using mongoose.createConnection and I want to keep using it. Anyone solve this issue?

**Comment by appacea** [comment]
Ok for me this was happening because my project was using two different mongoose versions in different modules. So the problem was that the connection was probably being created with one version and the operations with another version. Clearing out all dependencies and reinstalling mongoose fixed the problem.
