### ISSUE TITLE
package.json file issue in installing mongoose via npm.

### ISSUE THREAD

**Issue by Danish22** [Automattic/mongoose#4855]
Hi, 
Just tried to install mongoose with **npm install mongoose --save**
Using on a cloud9 workspace having hosted on ubuntu , npm, node and mongodb already installed.

Attaching the npm-debug.log in txt format.

[log.txt](https://github.com/Automattic/mongoose/files/680502/log.txt)

Thanks

**Comment by Danish22** [comment]
**UPDATE**
It works while using **npm install -g mongoose@version --save**
without **-g ** its not working.

**Comment by Danish22** [comment]
@vkarpov15  well maybe, Am new to MEAN stack and mongoose.
Is there anyway I can test my package.json for formatting as for me it was perfectly fine and properly formatted .

Thanks

**Comment by vkarpov15** [comment]
Plenty of json syntax checkers on Google just a quick search away, like http://jsonlint.com
