### ISSUE TITLE
Promises are not returned from model instance methods

### ISSUE THREAD

**Issue by godzsa** [Automattic/mongoose#4856]
**bug**
Promises not returned from model instance methods

**What is the current behavior?**
When I return a promise from an instance method, it "gets lost". I mean I cannot attach a then to it.

**If the current behavior is a bug, please provide the steps to reproduce.**
for example.:
I have an authentication query in my nodejs express app:
```
    User.findOne({'username': req.body.username})
        .then(
            user=> user.validate(req.body.password)
        )
        .then(
            // never called
            success=> console.log(success)
        )
        .catch(
             // never called
            err=> console.log(err)
        );
```
And a bcrypt compare in my user.js :
```
UserSchema.methods.validate = function (password) {
    return bcrypt.compare(password, this.local.password);
};
```

**What is the expected behavior?**
I should be able to return promises like this and attach .then() to them like in my example. I guess the problem is that these methods get wrapped or proxied, so my original promise disappears somewhere

**Please mention your node.js, mongoose and MongoDB version.**
-nodejs: v6.9.2
-mongoose: v4.7.4
-mongoDB: v3.4.1

**Comment by coyotte508** [comment]
Did you add this in your code after requiring mongoose?

```js
mongoose.Promise = global.Promise; //native promises
```

Also, you probably want `bcrypt.compareSync` instead of `bcrypt.compare`.

**Comment by godzsa** [comment]
Yes I did

**Comment by coyotte508** [comment]
This is weird. I use promises with no problems. 

What about this code:

```js
    User.findOne({'username': req.body.username})
        .then(
            user=> user.validate(req.body.password).then( (val) => {
                 console.log("This is really a bug", val);
                 return val;
            });
        )
        .then(
            // never called
            success=> console.log(success)
        )
        .catch(
             // never called
            err=> console.log(err)
        );
```

Another reason might be if you use `bcrypt-nodejs` instead of `bcrypt`.

**Comment by vkarpov15** [comment]
You're overwriting mongoose's built-in `validate` function. Don't do that. Bad things will happen.
