### ISSUE TITLE
Mongoose function findByIdAndUpdate is returning a null document

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4859]
Please see this question:

http://stackoverflow.com/questions/41420379/mongoose-function-findbyidandupdate-is-returning-a-null-document

**Comment by vkarpov15** [comment]
Show schema and document from the mongo shell please. Couple possibilities:

1) How did you verify that the `_id` field is a string in the db?
2) Are you connected to the right database?
3) Is mongoose executing the query on the right collection? Run `require('mongoose').set('debug', true)` to see what collection mongoose is updating.

**Comment by joetidee** [comment]
1. Using MonChef I viewed the property of the field and it said 'String'.
2. Yes, I ran a find() command just before my update block and it was from the correct database.
3. Yes, it is updaing the right collection.

I edited this S.O. question yesterday to relfect what I discovered, which was that I needed to use `JSON.parse(templateId)` on the incoming variable. Strange though that when running `typeof templateId` that the templateId variable was a `string` , but that I still had to use the `JSON.parse` function on it - any idea why?

**Comment by varunjayaraman** [comment]
What version of node are you using? The doc shows up in my console log with these specs: 
Node v6.9.2
Mongoose v4.7.6

I modified your script, but it's essentially the same, and it's working for me:

`index.js`

```
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;

// Constants
const GITHUB_ISSUE = `gh-4859`;
const STRING_ID = 'random-string-id';

// Define Schema

const TemplateSchema = new mongoose.Schema({
  _id: { type: String },
  discon: Boolean,
  discon_date: Date,
  discon_user_id: String
});


TemplateSchema.statics.archive = function(templateId, userId) {
  const self = this;
  return co(function*() {
    let now = new Date();

    const doc = yield self.findByIdAndUpdate(templateId, {
      discon: true,
      discon_date: now,
      discon_user_id: userId
    }, { new: true });

    console.log(`TemplateDoc: ${ doc }`);
  });
};

const Template = mongoose.model('Template', TemplateSchema);

exec()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
    process.exit(2);
  });

function exec() {
  return co(function*() {
    connect();
    const doc = yield seed();

    yield Template.archive(STRING_ID, 'user-id');
  });
}

function connect() {
  mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
}

function seed() {
  return co(function*() {
    const doc = yield Template.create({
      _id: STRING_ID
    });

    return doc;
  });
}
```

Do you still get a

**Comment by joetidee** [comment]
The templateId is being sent via Xhr request from the client-side. I think that sending information using Xhr (or any Ajax-type request) converts everything to 'string' - maybe it alters it in some way that means, even though the typeof is a string, it is treated differently by the findByIdAndUpdate function (?) - could be something as simple as the incoming templateId being surrounded by double-quotes and the findByIdAndUpdate function wraps it in single quotes as well (?)

**Comment by varunjayaraman** [comment]
Can you console log it? If you aren't handling the string properly from the AJAX request, that's probably more a problem with your server-side logic than mongoose itself. Ideally you would be parsing your JSON request bodies properly, but if the string itself has `"` in it, you need to handle that on your end
