### ISSUE TITLE
[Bug - Mongoose >=4.7.3] Fail to create new record with string _id

### ISSUE THREAD

**Issue by kyofight** [Automattic/mongoose#4867]
When I try to create a new record with the "create" Model method by supplying the _id as a String,
```
Model.create({
      _id: "5788683c1fa46a472a051543"
     name: "abc"
});
```
 it fails with the following error:
`{"errors":{"_id":{"message":"Cast to ObjectID failed for value \"5788683c1fa46a472a051543\" at path \"_id\"","name":"CastError","stringValue":"\"5788683c1fa46a472a051543\"","kind":"ObjectID","value":"5788683c1fa46a472a051543","path":"_id","reason":{"message":"Cast to ObjectId failed for value \"5788683c1fa46a472a051543\" at path \"_id\"","name":"CastError","stringValue":"\"5788683c1fa46a472a051543\"","kind":"ObjectId","value":"5788683c1fa46a472a051543","path":"_id"}}},"message":"Model validation failed","name":"ValidationError"}`

I suppose for Mongoose >= 4.7.3, it does not automatically convert string _id value to ObjectId _id value when we try to insert new records

**Comment by joetidee** [comment]
What is your _id defined as in your schema?

**Comment by thedewpoint** [comment]
Also having this issue when retrieving records with a string ID using findById. 

(err): CastError: Cast to ObjectId failed for value "586c6806a6918640e144622a" at path "_id" for model "User"

**Comment by JvrBaena** [comment]
I think this is related to the upgrade of the bson package. See here https://github.com/Automattic/mongoose/issues/4860

...Although I have tried installing all dependencies so we get the latest version of bson and the bug persist... :(

**Comment by raugaral** [comment]
> (err): CastError: Cast to ObjectId failed for value "586c6806a6918640e144622a" at path "_id" for model "User

I have the same problem, at the moment I have "solve" it using the version 4.7.2. All posterior version have this bug. To install the version 4.7.2 you can use this command: 

`npm install mongoose@4.7.2`

**Comment by ifyour** [comment]
@raugaral  Thanks，it's work now！

**Comment by joetidee** [comment]
Make sure that if using a string for the _id, that you also have the following defined in your schema:

`_id: {type: String}`

**Comment by JCBird1012** [comment]
Seconding @thedewpoint above. The default for an unspecified ```_id``` in your schema is an ObjectId. Before 4.7.3, strings were automatically cast into ObjectIds across all Mongoose functions (```findByID``` and others). 

+1 for this issue.

**Comment by JvrBaena** [comment]
Everything goes back to this issue in the bson package, I'm afraid: https://github.com/mongodb/js-bson/issues/204

**Comment by foriam** [comment]
It seems if you can update to [node 7.4.0](https://github.com/nodejs/node/releases/tag/v7.4.0) the issue is gone, as the Buffer.from function is working as expected by bson, which is used in mongoose.

Test (working in 7.4.0, probably not working in your node version):
```javascript
console.log(
    require('buffer').Buffer.from('AAAAAAAAAAAAAAAAAAAAAAAA', 'hex')
);
```

**Comment by Kikobeats** [comment]
NodeJS API for Buffer is inconsistent between node versions.

A better approach is use [buffer](https://www.npmjs.com/package/buffer) (thanks @feross!) package that do exactly the same (or better) and move the dependency out of the native API. 

It was designed precisely for this kind of problems as premise.

**Comment by varunjayaraman** [comment]
I can't seem to reproduce this issue:

node v6.9.2
mongodb v3.2

Tried with mongoose 4.7.3, 4.7.4, 4.7.6

This is the script I used to attempt to reproduce:

```
// NPM Deps
const mongoose = require('mongoose');
const co = require('co');
const chalk = require('chalk');

// Constants
const GITHUB_ISSUE = `gh-4867`;
const STRING_AS_ID = '5788683c1fa46a472a051543';

// Set mongoose promise
mongoose.Promise = global.Promise;

try {
  exec();
} catch (error) {
  console.log(chalk.red(`Error: ${error}\n${error.stack}`));
}


function exec() {
  return co(function* () {
    mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
    
    const ThingSchema = new mongoose.Schema({
      name: String
    });

    const Thing = mongoose.model('Thing', ThingSchema);

    const thing = yield Thing.create({
      _id: '5788683c1fa46a472a051543',
      name: 'Bob'
    });
    console.log(chalk.green(`thing exists with id ${ thing._id.toString() }: ${ !!thing }`));

    const foundThing = yield Thing.findById(thing._id.toString());
    console.log(chalk.green(`thing exists after finding by string id ${ foundThing._id.toString() }: ${ !!foundThing }`));
  }).catch(function(error) {
    console.error(chalk.red(`Error ${error}\n${error.stack}`));
  });
}
```

Does this script produce the same cast to ObjectId error?

**Comment by thedewpoint** [comment]
I'm using node 4.4.x , maybe that's the difference

**Comment by JvrBaena** [comment]
It definitely depends on the node version, as explained here https://github.com/mongodb/js-bson/issues/204 ... I'm not sure there's anything that can be done from this side (mongoose)... as AFAIK the issue comes from the bson package, which in turn is a dependency of mongodb-core (listed in the package.json with ^ which would explain why doing `npm install` broke stuff for versions that worked before)

Im my case, it's node 4.4.4

**Comment by varunjayaraman** [comment]
@JvrBaena thanks, seems like it fails up to but not including node v6.0 on mongoose >= 4.7.3.

I also agree that this isn't a mongoose issue, but a problem with js-bson (through mongodb-core). This issue will hopefully be resolved soon: https://github.com/mongodb/js-bson/pull/205

**Comment by varunjayaraman** [comment]
For now the solution is to use mongoose < 4.7.2 or upgrade node >= 6.0. If anyone else has any other ideas, feel free to comment, but i think this and waiting for js-bson to merge in PR 205 are the best solutions.

**Comment by kapilgarg1996** [comment]
Using node >=6.0 worked for me

**Comment by Airboy** [comment]
I have this issue with node 6.9.3 and mongoose 4.7.6. But it works with mongoose 4.7.3.

**Comment by ronteq** [comment]
Using node >=6.0 worked for me too (6.9.1)

**Comment by SumiSastri** [comment]
> > (err): CastError: Cast to ObjectId failed for value "586c6806a6918640e144622a" at path "_id" for model "User
> 
> I have the same problem, at the moment I have "solve" it using the version 4.7.2. All posterior version have this bug. To install the version 4.7.2 you can use this command:
> 
> `npm install mongoose@4.7.2`

I have done this but get a mongoDb connection error ```check mongo-db connection Error: Invalid mongodb uri. Must begin with "mongodb://"``` I can't use the dot env file  like so ```DB_CONNECTION=mongodb+srv://<username>:<password>@cluster0.iqhpj.mongodb.net/test```

**Comment by vkarpov15** [comment]
@SumiSastri you need to use Mongoose >= 5 to connect to MongoDB Atlas. Atlas only supports MongoDB >= 3.6, which requires Mongoose 5: https://mongoosejs.com/docs/compatibility.html
