### ISSUE TITLE
Please update mongodb-core dependency

### ISSUE THREAD

**Issue by sradu** [Automattic/mongoose#4870]
mongodb-core 2.2.18 fixes https://github.com/christkv/mongodb-core/issues/153, which is causing a number of connection timeouts.

**Comment by varunjayaraman** [comment]
The next release of mongoose uses mongodb-core 2.2.19, so this should be fixed then.

**Comment by desygn** [comment]
I noticed this was closed. Will mongodb-core 2.2.19 be included in the next version?

**Comment by varunjayaraman** [comment]
yup

**Comment by loris** [comment]
When will it be released? maybe you guys should release another version meanwhile which uses an older/non-buggy version of `mongodb-core`?
