### ISSUE TITLE
Getting Uncaught RangeError when validating client-side document.

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4878]
I am trying to use Mongoose for client-side model validation. I have the following code (this is a React component):

```
import templateSchema from '../../../shared/schemas/templateSchema.js';
var mongoose = require('mongoose');
var TemplateDocSchema = new mongoose.Schema(templateSchema);

class TemplateEditInfo extends Component {
    ...
    saveStage(e) {
        var doc = new mongoose.Document({}, TemplateDocSchema);
        doc.validate(function(error) {

        });
    }
    ...
}
```

The `doc.validate` function is throwing the following error in the browser (latest Chrome):

> Uncaught RangeError: Maximum call stack size exceeded
>     at Object.exports.deprecate (eval at <anonymous> (app.js:866), <anonymous>:65:29)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:22)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)
>     at Promise.eval (eval at <anonymous> (app.js:866), <anonymous>:69:41)

The schema is as follows:

```
const templateSchema = {
    ref: {type: Number}
};
export default templateSchema;
```

**Comment by varunjayaraman** [comment]
At first I thought this might have been an issue with webpack, but I've confirmed the bug exists with both bundlers. 

I've created a repro example below (without React):

*index.js*
```
const mongoose = require('mongoose');

const templateSchema = {
  ref: { type: Number }
};

const schema = new mongoose.Schema(templateSchema);

const doc = new mongoose.Document({}, schema);

doc.validate(function(error) {
  if (error) {
    console.error(`Error: ${ error }\n${ error.stack }`);
  } else {
    console.log(`Doc validated successfully`, doc);
  }
});
```

*index.html*
```
<!DOCTYPE html>
<head>
  <title>Bundler Testing</title>

  <body>
    <p>sup</p>
    <script src="bundle.js" type="text/javascript"></script>
  </body>
</head>
```

Make sure to `$(npm bin)/browserify index.js -o bundle.js` before opening index.html in your browser.

**Comment by joetidee** [comment]
Adding the bluebird package fixed this - many thanks.
