### ISSUE TITLE
Ability to override validation fields

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4880]
This is a feature request. It would be good to be able to explicitly state which fields can be validated, perhaps by supplying an array of field names as a parameter to the validate function:

`doc.validate(['name','age',...], function(error){ ... }`

Example 1: lets say that a web form has two stages - address information is entered into the first stage and saved, then the user moves onto the second stage, which asks for their personal interests, and saves that. Both address and personal interest information is `required: true` in the User schema, but when Mongoose validates stage 1 against this schema it cannot simply validate the personal information only as is will throw a validation error.

Example 2: I have a schema whereby the `created_date` field is set to `required: true`, however, this field will only be set server-side just before the document is saved. So, if I want to use the same schema to validate  client-side, I this case when I try and validate client-side, it will throw a validation error.

I think that this would be a good first step to making schema usage isomorphic. I have used the jagi-astronomy package (used in Meteor applications), which I think look it's inspiration from Mongoose package. The Astronomy package allow for partial field validation as described above.

**Comment by varunjayaraman** [comment]
This feature exists in `document#validateSync`. i.e. you can do:

```
const errors = theDoc.validateSync(['data.name', 'admin.readableId']);
```

**Comment by vkarpov15** [comment]
Would be nice to add this for regular validate at some point

**Comment by captaincaius** [comment]
I've been thinking about this recently too... @vkarpov15 what do you think about putting the path array into a property of options so it's not breaking?

**Comment by captaincaius** [comment]
otherwise, if you think it's too awkward to have validateSync and validate this different... where would you want the field list in the argument list?

I might want to help with this one if it's welcome :)

**Comment by vkarpov15** [comment]
@captaincaius go for it. It should be right up your alley given your work on #7483 . Will merge it into 5.5

**Comment by vkarpov15** [comment]
This has been fixed, we added `pathsToValidate` as first param to [`validate()` function](https://mongoosejs.com/docs/api/document.html#document_Document-validate).
