### ISSUE TITLE
Unrecognized pipeline stage name: '$sortByCount' in mongo db 3.4

### ISSUE THREAD

**Issue by vijay122** [Automattic/mongoose#4882]
error code : Unrecognised pipeline stage name: '$sortByCount'

mongodb version : 3.4
mongoose version : 4.7.6 
 
I upgraded the mongo db from 3.2 to 3.4 for the new sortByCount feature, also i updated to the latest mongoose 4.7.6 version.

Error scenario in mongoose with node.js: 
Package.aggregate( [ { $unwind: "$category" },  { $sortByCount: "$category" } ],function(err,data)
{
				if (err) throw err;
}
error returned by mongoose : Unrecognised pipeline stage name: '$sortByCount'

Actual on mongo 3.4 :
running the below command on mongo console, gives me,
db.packages.aggregate( [ { $unwind: "$category" },  { $sortByCount: "$category" } ] )

expected results:
{ "_id" : "honeymoon", "count" : 2 }
{ "_id" : "sightseeing", "count" : 2 }
{ "_id" : "party", "count" : 1 }
{ "_id" : "grouptrips", "count" : 1 }

please let me know if this case was already covered or help me to progress. Thanks.

**Comment by vkarpov15** [comment]
Below script works fine for me:

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4882');
mongoose.set('debug', true);

var MyModel = mongoose.model('gh4882', new Schema({ name: String }));

MyModel.aggregate([ { $unwind: "$category" }, { $sortByCount: "$category" } ],function(err,data) {
  console.log('error', err);
  process.exit(0);
});
```

```
$ node gh-4882.js 
Mongoose: gh4882.aggregate([ { '$unwind': '$category' }, { '$sortByCount': '$category' } ]) {}  
error null
$ 
```

To me this error sounds like mongoose is connected to a mongodb server that isn't running 3.4. Can you please double check that?

**Comment by vijay122** [comment]
it worked fine. mongo db version was still 3.2, i updated to 3.4 and it worked fine. thanks @vkarpov15 :-)
