### ISSUE TITLE
Post validate error handler does not fire

### ISSUE THREAD

**Issue by sshymko** [Automattic/mongoose#4885]
**Environment:**
- Node.js 6.7.0
- MongoDB 3.2.10
- Mongoose 4.7.2

**Steps to reproduce:**

1. Execute the following test script:
```js
let PaymentSchema = new db.Schema({
  currency: {type: String, required: true, enum: ['USD'], default: 'USD'},
  amount: {type: Number, required: true},
});

PaymentSchema.post('validate', function(error, doc, next) {
  next(new Error('Invalid payment information'));
});

let PaymentModel = db.model('Payment', PaymentSchema);

let payment = new PaymentModel({
  currency: 'EUR',
  amount: 10,
});

payment.validate()
  .catch((error) => {
    console.log(error.message);
  });

let error = payment.validateSync();
if (error) {
  console.log(error.message);
}
```

**Expected result:**
- Post-validate error handler catches & converts all validation errors
- Model validation methods `validate` and `validateSync` return converted error

**Actual result:**
- Post-validate error handler does NOT get called upon validation failure
- Model validation methods return original error

**Comment by varunjayaraman** [comment]
Thanks for the repro script.

Looks like it also doesn't run when you actually make a db operation:

```
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-4885`;

mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
let PaymentSchema = new mongoose.Schema({
  currency: { type: String, required: true, enum: ['USD'], default: 'USD' },
  amount: { type: Number, required: true },
});

PaymentSchema.post('validate', function(error, doc, next) {
  console.log(`Error in post validate hook ${error}`)
  next(new Error('Invalid payment information'));
});

let PaymentModel = mongoose.model('Payment', PaymentSchema);

try {
  let payment = new PaymentModel({
    currency: 'EUR',
    amount: 10,
  });

  console.log('saving...');
  payment.save()
    .then(doc => {
      console.log('saved', doc);
      process.exit(0);
    })
    .catch(error => {
      console.error(`Error in catch handler ${error}\n${error.stack}`);
      process.exit(2);
    })

} catch (error) {
  console.error(error);
  process.exit(2);
}

```

**Comment by sshymko** [comment]
Looks like post save error handler does not fire either. Do error handlers ever fire at all?

**Comment by sshymko** [comment]
@varunjayaraman 
You did confirm the issue, didn't you? Why has the label changed "confirmed-bug" -> "bug?" than?

**Comment by varunjayaraman** [comment]
yep, sorry about that, not sure what happened

**Comment by sshymko** [comment]
@vkarpov15 
Thanks for the fix, I'm yet to verify it.
Does it also cover the post save error hander not intercepting errors?
The issue does seem to extend beyond the post validate to error handler in general.

**Comment by vkarpov15** [comment]
What do you mean by "post save error handler not intercepting errors"? I'm not aware of such an issue.

**Comment by sshymko** [comment]
@vkarpov15 
Thanks for getting back to me.
The test case is the same, but `schema.post('save', errorHandler)` instead of `schema.post('validate', errorHandler)`. Error handler won't fire upon save failure. In my case save failure was due to the `VersionError`, but perhaps DB error of any nature will reproduce too.

**Comment by vkarpov15** [comment]
@sshymko works just fine:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-4885`;

mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
let PaymentSchema = new mongoose.Schema({
  currency: { type: String, required: true, enum: ['USD'], default: 'USD' },
  amount: { type: Number, required: true },
});

PaymentSchema.post('save', function(error, doc, next) {
  console.log(`Error in post validate hook ${error}`)
  next(new Error('Invalid payment information'));
});

let PaymentModel = mongoose.model('Payment', PaymentSchema);

try {
  let payment = new PaymentModel({
    currency: 'EUR',
    amount: 10,
  });

  console.log('saving...');
  payment.save()
    .then(doc => {
      console.log('saved', doc);
      process.exit(0);
    })
    .catch(error => {
      console.error(`Error in catch handler ${error}\n${error.stack}`);
      process.exit(2);
    })

} catch (error) {
  console.error(error);
  process.exit(2);
}
```

Output

```
$ node gh-4885.js 
saving...
Error in post validate hook ValidationError: `EUR` is not a valid enum value for path `currency`.
Error in catch handler Error: Invalid payment information
Error: Invalid payment information
    at model.<anonymous> (/home/val/Workspace/10gen/troubleshoot-mongoose/gh-4885.js:14:8)
    at next (/home/val/Workspace/10gen/mongoose/node_modules/kareem/index.js:141:14)
    at Kareem.execPost (/home/val/Workspace/10gen/mongoose/node_modules/kareem/index.js:189:3)
    at /home/val/Workspace/10gen/mongoose/lib/schema.js:199:43
    at handleError (/home/val/Workspace/10gen/mongoose/node_modules/hooks-fixed/hooks.js:40:22)
    at next_ (/home/val/Workspace/10gen/mongoose/node_modules/hooks-fixed/hooks.js:75:26)
    at fnWrapper (/home/val/Workspace/10gen/mongoose/node_modules/hooks-fixed/hooks.js:186:8)
    at /home/val/Workspace/10gen/mongoose/lib/document.js:1370:9
    at /home/val/Workspace/10gen/mongoose/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
$ 
```

Which version of mongoose are you using?

**Comment by sshymko** [comment]
@vkarpov15 
I'll test `schema.post('save', errorHandler)` once again and file a separate issue, if it reproduces.

**Comment by sshymko** [comment]
@vkarpov15 
Confirmed the error transformation by the handler `schema.post('validate', handler)` does affect `doc.validate()` as of Mongoose 4.7.8.
However, `doc.validateSync()` still returns the original error object unaffected by the `handler`.
Cannot tell whether it's because of not invoking the handler or ignoring its result.
Tested on the latest Mongoose 4.8.3.

**Comment by vkarpov15** [comment]
@sshymko can you please clarify with a code sample?

**Comment by jayadrathamondal** [comment]
This error is still there in mongoose v5.9.5.
Post validate hook doesn't get executed if I call doc.validateSync function but it get executed if I call doc.validate().

`
const mongoose = require('mongoose');

const PaymentSchema = new mongoose.Schema({
  currency: { type: String, required: true, enum: ['USD'], default: 'USD' },
  amount: { type: Number, required: true },
});

PaymentSchema.post('validate', (error, doc, next) => {
  next(new Error('POST VALIDATE FUNCTION EXECUTED'));
});

const PaymentModel = mongoose.model('Payment', PaymentSchema);

const payment = new PaymentModel({
  currency: 'EUR',
  amount: 10,
});

payment.validate((error) => {
  console.log(`validate: ${error.message}`);
});

const error = payment.validateSync();
if (error) {
  console.log(`validateSync: ${error.message}`);
}
`
Check the outputs of both console.log. They are different. 
In post validate hook I'm changing the error message but its only reflecting in payment.validate() function not in payment.validateSync().

**Comment by jayadrathamondal** [comment]
This error is still there in mongoose v5.9.5.
Post validate hook doesn't get executed if I call doc.validateSync function but it get executed if I call doc.validate().

```
const mongoose = require('mongoose');

const PaymentSchema = new mongoose.Schema({
  currency: { type: String, required: true, enum: ['USD'], default: 'USD' },
  amount: { type: Number, required: true },
});

PaymentSchema.post('validate', (error, doc, next) => {
  next(new Error('POST VALIDATE FUNCTION EXECUTED'));
});

const PaymentModel = mongoose.model('Payment', PaymentSchema);

const payment = new PaymentModel({
  currency: 'EUR',
  amount: 10,
});

payment.validate((error) => {
  console.log(`validate: ${error.message}`);
});

const error = payment.validateSync();
if (error) {
  console.log(`validateSync: ${error.message}`);
}

```
Check the outputs of both console.log. They are different. 
In post validate hook I'm changing the error message but its only reflecting in payment.validate() function not in payment.validateSync().

**Comment by vkarpov15** [comment]
@jayadrathamondal we unfortunately don't have a way to run error handling middleware on `validateSync()` because error handling middleware always takes 3 arguments. Please follow #8703 for updates.
