### ISSUE TITLE
CastError: Cast to ObjectId failed for value "56d79e4a52637adc45e874b4" at path "_id" for model "User"

### ISSUE THREAD

**Issue by KavenWork** [Automattic/mongoose#4887]
findById

mongoose@4.3.6 is right

4.7.6 has this problem

**Comment by dongyingtao** [comment]
Same problem. I was using 4.6.8. It worked fine. Today, when I deployed a new server with npm install. It installs 4.7.6 with mongodb@2.2.19 which has the regression.
This is pretty big regression. Everyone seems to be complaining.

**Comment by varunjayaraman** [comment]
Guessing this is a duplicate of https://github.com/Automattic/mongoose/issues/4867 but can you please post a code snippet or follow the issue template please so we can at least see what's causing the bug?

**Comment by varunjayaraman** [comment]
@KavenWork any update on this? Otherwise I'm going to close this issue as stale.

**Comment by MadeoIT** [comment]
fuking tard what are you closing
