### ISSUE TITLE
mongoose connection with authentication

### ISSUE THREAD

**Issue by nasr18** [Automattic/mongoose#4891]
How do i execute query with authentication enabled? 

Yesterday our app's mongodb data was deleted by some scripts. So that we enabled `auth` in our mongodb. But now i can't able to query the data. How do i enable `auth` using mongoose?

**Comment by varunjayaraman** [comment]
I normally do it 1 of 2 ways:

1) Connection string: 

`mongoose.connect('mongodb://username:password@host:port(usually 27017)/db')`

Where username and password are the respective username and password for that specific db, host would be the host where your db is hosted (so localhost or some domain/IP), port is the port mongo listens on, and db is the name of the db you want to connect to

2) Using options. From the docs:

```
var options = {
  db: { native_parser: true },
  server: { poolSize: 5 },
  replset: { rs_name: 'myReplicaSetName' },
  user: 'myUserName',
  pass: 'myPassword'
}
mongoose.connect(uri, options);
```
