### ISSUE TITLE
required validator not running on findOnAndUpdate(). Document keeps its old value for the specific field.

### ISSUE THREAD

**Issue by mtsap** [Automattic/mongoose#4896]
I have the following Schema

```javascript
const mongoose = require('mongoose');

const ProjectSchema = new mongoose.Schema({
  _owner: {
    type: mongoose.Schema.ObjectId,
    ref: 'User',
  },
  name: {
    type: String,
    required: true,
    unique: true
  },
});

ProjectSchema.pre('findOneAndUpdate', function (next) {
  // the findOneAndUpdate is called with the context:'query' option
  console.log(this._update.name);
  next();
});

const Project = mongoose.model('Project', ProjectSchema);

module.exports = Project;
```

When creating a new project both the required and the unique validators are working as expected.

When  updating a project the unique validator works as expected but the required validator does not kick in. Setting the project name to blank ( its value is now undefined) results to the project being updated and keeping its old name.  

I know that the required validator is the only one that runs on undefined values when creating a new document. Isn't it supposed to run when updating?

Here is the express controller just in case there is something wrong here

```javascript
  let promise = {};
    if (res.locals.user.role === 'admin' || 'contractor'){
      promise = Project.findOneAndUpdate({
          _id: req.params.projectId,
        }, req.body, {
          new: true,
          context:'query'
        })
        .exec()
    }
    else {
      res.boom.notFound();
    }

      promise
      .then((project) => {
        res.status(200).json(project);
      })
      .catch((error) => {
        res.boom.notFound();
      });
```

mongoose v 4.4.11
node version 6.9.4 LTS
mongoDB 3.2.11

**Comment by varunjayaraman** [comment]
You have to pass `{ runValidators: true }` to the `findOneAndUpdate` options.

**Comment by mtsap** [comment]
Tried it, and got the exact same behaviour.
Unique works as intended, required save the project with its old name.

**Comment by varunjayaraman** [comment]
Can you put in some console logs to make sure the `findOneAndUpdate` path in that controller is actually running? And can I see what `req.body` looks like? 

As a side note, there's a bug in your controller, in this check:

```
if (res.locals.user.role === 'admin' || 'contractor')
```

The string 'contractor' will always be truthy so you will never go down the `else` check where you call `res.boom.notFound()`. I'm guessing you meant to do:

```javascript
if (['admin', 'contractor'].indexOf(res.locals.user.role) > -1) ...
```

or

```javascript
if (res.locals.user.role === 'admin' || res.locals.user.role === 'contractor') ...
```

**Comment by mtsap** [comment]
Thanks for catching the bug! :+1: !

So here is the request code

```javascript
router.put('/:projectId', /*middlewares.validateProject,*/  middlewares.loadme, (req, res) => {
  // router.put('/:id', (req, res) => {
  console.log("Logging request body");
  console.log(req.body.name);
  const errors = req.validationErrors();
  //logger.debug(errors);
  if (errors) {
    res.boom.badRequest('Validations errors exist', errors);
  } else {
    let promise = {};
    if (res.locals.user.role === 'admin' || 'contractor'){
      promise = Project.findOneAndUpdate({
          _id: req.params.projectId,
        }, req.body, {
          new: true,
          runValidators: true,
          context: 'query'
        })
        .exec()
    }
    else {
      res.boom.notFound();
    }

      promise
      .then((project) => {
        console.log('Logging the name after the update');
        console.log(project.name);
        res.status(200).json(project);
      })
      .catch((error) => {
        logger.debug(error)
        res.boom.notFound();
      });
  }
});
```

Here is the model
```javascript
const mongoose = require('mongoose');

const ProjectSchema = new mongoose.Schema({
  _owner: {
    type: mongoose.Schema.ObjectId,
    ref: 'User',
  },
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  }
//A hell lot more fields
});



ProjectSchema.pre('findOneAndUpdate', function (next) {
  console.log("findOneAndUpdate validations running");
  console.log('Logging the name in the findOneAndUpdate validations');
  console.log(this._update.name);
  next();
});

const Project = mongoose.model('Project', ProjectSchema);

module.exports = Project;

```

Here's the logs after updating with a correct value:
![image](https://cloud.githubusercontent.com/assets/17740611/21998508/f15666ae-dc3d-11e6-8541-f0aeab264036.png)

Updating with a non-unique value (works):
![image](https://cloud.githubusercontent.com/assets/17740611/21998549/254f3e7c-dc3e-11e6-8199-8ebebd02aefc.png)

And updating with an empty name which should give an error but doesn't:
![image](https://cloud.githubusercontent.com/assets/17740611/21998572/54a14cce-dc3e-11e6-8328-53d87ae9dab0.png)

**Comment by varunjayaraman** [comment]
I think I know what the problem is. Instead of logging `req.body.name`, can you log the entire request body. 

`findByIdAndUpdate` will only update the properties that you pass to the object. It won't overwrite `name` unless you specifically tell it to, i.e. if you specify in request body `{ name: undefined }`

**Comment by mtsap** [comment]
Ok you got it!! That's it. The name property when undefined gets removed from the req.body (probably because of express body-parser?  still looking into it..). So the update query has no name property thus the validation not running! Thanks for your time!
