### ISSUE TITLE
Monggose exec function is not working since Yesterday 

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [Automattic/mongoose#4897]
--- I got exec is working last day -- since today exec function is not working -- the callback is returning always undefined -- not sure what i'm doing wrong with this. 

     mongoose.model('myModal').findOne({})
        .exec(function(err, data) {
          // got both error and data as undefined
        });

Please advise me on this

**Comment by bazineta** [comment]
That means that there is no data in the collection.

**Comment by GeorgeAnanthSoosai** [comment]
There is a data in the collection sir -- it was working great last day.. today stopped working

**Comment by varunjayaraman** [comment]
@GeorgeAnanthSoosai can I see how you define your mongoose model? 

Also what happens if you type the following into your mongodb shell:

`db.myModals.find({})`

**Comment by GeorgeAnanthSoosai** [comment]
It was looks to be a strange issue.. It gotta working back.. thanks for your help..

**Comment by varunjayaraman** [comment]
OK, no problem
