### ISSUE TITLE
Virtual.populate is undefined.

### ISSUE THREAD

**Issue by sundavu** [Automattic/mongoose#4899]
I am following this basic example from [http://mongoosejs.com/docs/populate.html](url)
 below is my schema with virtual field.

```
var mongoose = require("mongoose");
var answerSchema = new mongoose.Schema ({
    questionId:String,
    username:String,
    answered:Boolean
});

answerSchema.virtual('quest', {
ref: 'Question',
localField: 'questionId',
foreignField: '_id'
},{ toObject : {virtuals:true} }, { toJSON: { virtuals:true } });

module.exports = mongoose.model("Answer", answerSchema);
```
**Question schema is below, I am trying to "join" to it's auto generated "_id"**

```
var questionSchema = new mongoose.Schema({
    question: {type:String, required:true},
)}
module.exports = mongoose.model("Question", questionSchema);
```

here is the query that I am using to try and populate from "Question" model based on id. But I get back only values from the "Answer" collection, even though there is data based on the ID in the foreign collection. What am I doing wrong ?

```

Answer.findOne({questionId:"58497379b0094008fe202b62"}).populate('quest').exec
(function(error, vals) {console.log(vals) }); 
```
// vals does not have the foreign collection related fields.
vals does have values from Answer schema but vals.quest is undefined. I also tried it with upgrading to 4.7.6 and that did not help.

Mongoose 4.6.7
Mongo 2.6.12
Node 4.5.0

**Comment by vkarpov15** [comment]
```javascript
answerSchema.virtual('quest', {
ref: 'Question',
localField: 'questionId',
foreignField: '_id'
},{ toObject : {virtuals:true} }, { toJSON: { virtuals:true } });
```

:point_up: why is `toObject` and `toJSON` in the virtual definition and not passed as options to the schema? That might explain why your `console.log()` is not showing it

**Comment by sundavu** [comment]
Thanks, that fixed it.
