### ISSUE TITLE
Mongoose.Promise is declared through Object.defineProperty() therefore is immutable

### ISSUE THREAD

**Issue by rpadovani** [Automattic/mongoose#4903]
In the [documentation](http://mongoosejs.com/docs/promises.html) there is written that to change the library mongoose uses for promises we need to do something like:

```
mongoose.Promise = global.Promise;
```

but `mongoose.Promise` is [declared](https://github.com/Automattic/mongoose/blob/master/lib/index.js#L665) through [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty):

```
Object.defineProperty(Mongoose.prototype, 'Promise', {
  get: function() {
    return PromiseProvider.get();
  },
  set: function(lib) {
    PromiseProvider.set(lib);
  }
});
```

therefore you cannot simply assign the library you want.
If you use TypeScript, you will have an error during the compilation:

```
TS2540:Cannot assign to 'Promise' because it is a constant or a read-only property.
```

There is any way to get around this?

**Comment by varunjayaraman** [comment]
This isn't really a mongoose issue but an issue with the typings which is a separately managed project. That being said, the typings file itself lists the fix for this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mongoose/index.d.ts#L2226-L2251

**Comment by pavlosadovyi** [comment]
I'm here with the same problem, but the link is broken, could you point me how to figure out with this issue?

**Comment by mastertinner** [comment]
I'm still having this problem and the link above leads to a 404... What's the best way of setting

```typescript
mongoose.Promise = global.Promise;
```

in TypeScript without any warnings?

**Comment by mchapman** [comment]
@mastertinner check out https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L2291

**Comment by mastertinner** [comment]
Thanks, @mchapman!

**Comment by vgw-rhysc** [comment]
Broken links?

**Comment by mchapman** [comment]
@vgw-rhysc try https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4e278d0f6d5be5a57db4475e30dc9b358afc803f/types/mongoose/index.d.ts#L2291
