### ISSUE TITLE
Doc: Bracket missing in example & included examples out of date.

### ISSUE THREAD

**Issue by Gormador** [Automattic/mongoose#4907]
Hi,

Just noticed a missing bracket in [this section's example](http://mongoosejs.com/docs/api.html#promise_Promise-then).

The code is currently:

    return People.find({ meetups: { $in: ids }).exec();
When it should be:

    return People.find({ meetups: { $in: ids }}).exec();

Also, the examples included in the module seem out of date, at least the one regarding promises (use of deprecated functionalities).

Anyway, I hope this helps. And thank you for your work on this project :-)

**Comment by varunjayaraman** [comment]
Thanks, we'll fix the docs in the next release
