### ISSUE TITLE
UNMET PEER DEPENDENCY mongoose@4.7.7

### ISSUE THREAD

**Issue by parichit13** [Automattic/mongoose#4908]
I was using mongoose now for a while in my API and recently I updated my mongoose version to 4.7.7 and I started getting these errors.

UNMET PEER DEPENDENCY mongoose@4.7.7

I saw several posts about this common issue of unmet peer dependency like
1. Deleting node_modules and using `npm install`
2. Updating the node and npm version.

but nothing seems to work. I have deployed my api on Heroku and it automatically uses the latest npm and node version. Please can anyone help.

**Comment by vkarpov15** [comment]
What version of mongoose did you upgrade from and what other packages are you using? This sounds like another lib you're using depends on a different version of mongoose from the one you currently have installed.

**Comment by matheo** [comment]
Indeed, I'm having the same error message after update from 4.6.* and after that error I get:
```
UNMET PEER DEPENDENCY mongoose@4.7.8
npm WARN mongoose-type-email@1.0.2 requires a peer of mongoose@ but none was installed.
npm ERR! code 1
```

**Comment by vkarpov15** [comment]
What does your package.json look like @matheo ?

**Comment by varunjayaraman** [comment]
@matheo any update on this? Otherwise I'm going to close this as stale

**Comment by matheo** [comment]
This is the `package.json` in question:
https://github.com/wfpc92/cleansuit-backend/blob/primer_release/package.json

The problem may be reproducable in that branch.
I just performed a `npm update --save` and got this output:
```
npm WARN gentlyRm not removing /media/zikula/git/cleansuit/cleansuit-backend/node_modules/espree/node_modules/.bin/acorn as it wasn't installed by /media/zikula/git/cleansuit/cleansuit-backend/node_modules/espree/node_modules/acorn
- base64-url@1.3.3 node_modules/base64-url
- is-expression@2.1.0 node_modules/constantinople/node_modules/is-expression
- debug@2.6.0 node_modules/eslint/node_modules/debug
- assert-plus@0.2.0 node_modules/http-signature/node_modules/assert-plus
- acorn@4.0.4 node_modules/is-expression/node_modules/acorn
- ms@0.7.1 node_modules/send/node_modules/ms
- send@0.14.2 node_modules/serve-static/node_modules/send
- mime@1.2.11 node_modules/url-loader/node_modules/mime
cleansuit-backend@0.1.0 /media/zikula/git/cleansuit/cleansuit-backend
├── async@2.1.5 
├── body-parser@1.17.1 
├── eslint@3.17.1 
├── express@4.15.2 
├── express-session@1.15.1 
├── file-loader@0.10.1 
├── html-pdf@2.1.0
├── moment@2.17.1 
├── UNMET PEER DEPENDENCY mongoose@4.9.0
├── morgan@1.8.1 
├── multer@1.3.0 
├── node-restful@0.2.6  (git+https://github.com/matheo/node-restful.git#9cb001185521020a3e0e6021a0d50e1cf7d3b744)
├── pug@2.0.0-beta9 
├── request@2.81.0 
├── shortid@2.2.8 
├── url-loader@0.5.8 
└── validator@6.3.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mongoose-type-email@1.0.3 requires a peer of mongoose@ but none was installed.
```

**Comment by vkarpov15** [comment]
Yeah this looks like a bug with mongoose-type-email. Either way, not a bug with mongoose.

**Comment by mukeshthe93** [comment]
Hi I am also getting same error. calling "npm install" then geting below error:

+-- UNMET DEPENDENCY mongoose@~4.9.4
+-- node-restful@0.2.6
| `-- underscore@1.8.3
`-- nodeman@1.1.2
  `-- colors@1.1.2

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\mukesh\Desktop\NodaApp\routeApp\node_modules\.staging\cor
e-util-is-1357e953
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mukesh\Desktop\
NodaApp\routeApp\node_modules\.staging\core-util-is-1357e953' -> 'C:\Users\mukes
h\Desktop\NodaApp\routeApp\node_modules\core-util-is'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mukesh\Desktop\
NodaApp\routeApp\node_modules\.staging\core-util-is-1357e953' -> 'C:\Users\mukes
h\Desktop\NodaApp\routeApp\node_modules\core-util-is'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\mukesh\Deskt
op\NodaApp\routeApp\node_modules\.staging\core-util-is-1357e953' -> 'C:\Users\mu
kesh\Desktop\NodaApp\routeApp\node_modules\core-util-is'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\instal
l\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mukesh\Desktop\
NodaApp\routeApp\node_modules\.staging\core-util-is-1357e953' -> 'C:\Users\mukes
h\Desktop\NodaApp\routeApp\node_modules\core-util-is'
npm ERR!     at Error (native) parent: 'express-router-experiments' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mukesh\Desktop\NodaApp\routeApp\npm-debug.log

**Comment by matheo** [comment]
@mukeshthe93 Seems that your issue is about user permissions, are you working with your `mukesh` user right? well, windows and its questions: `Please try running this command again as root/Administrator.`
