### ISSUE TITLE
Strange behaviour when saving string

### ISSUE THREAD

**Issue by amihajlovski** [Automattic/mongoose#4909]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When saving specific string if mongoose detects it as a valid objectID, which is not, automatically converts it into objectID and saves database instead of the real string. For example, I was using title **Test MK Call** аnd it was detected as ObjectID and saved in the collection with that ID. This is happening on multiple collections and is very annoying. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To be saved the real string.

**Please mention your node.js, mongoose and MongoDB version.**
nodejs: 6.9.1
mongoose: 4.7.6
mongoDB: 3.2.10

**Comment by varunjayaraman** [comment]
Can you post a repro script and your schema?

**Comment by amihajlovski** [comment]
This is the schema

`var CallSchema = new Schema({
  name: String,
  website: String,
  contactPerson: {
    name: String,
    telephoneNumber: String,
    email: String
  });`

So, when I save string with 12 characters, mongoose thinks that it is ObjectID and saves it as ObjectID instead of real string... How can this happen?

**Comment by vkarpov15** [comment]
Which string are you saving? Also, can you please post your actual schema? The given one has a glaring syntax error.

**Comment by amihajlovski** [comment]
Here is the whole schema file: http://pastebin.com/vzjZp5q2

The string that I like to save is: **Test MK Call**
Detected as objectID because it has 12 characters.

**Comment by vkarpov15** [comment]
No I mean which schema path are you setting to that string?

**Comment by amihajlovski** [comment]
http://pastebin.com/p4jsjS7c
Here is the whole service where I use **call.save()** method for saving new call in the database.

**Comment by amihajlovski** [comment]
Any progress on this?

**Comment by vkarpov15** [comment]
Still not clear what the bug is. No schemas in the pastebin, no idea what the path you're setting to that string is and what type mongoose expects it to be. Please provide a standalone script that reproduces your issue.

**Comment by varunjayaraman** [comment]
@amihajlovski definitely not something mongoose is doing. Joi or something on your end. Could you please post a much smaller repro script that allows us to locate exactly how you're storing the string? It's hard for us to go through ~500 LOC to help debug your problem.

And I also can't reproduce your problem with a much smaller repro script:

```javascript
const mongoose = require('Mongoose');
const co = require('co');
const assert = require('assert');

mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-4909`;

exec()
  .then(() => {
    console.log('Successfully executed program');
    process.exit(0);
  })
  .catch(error => {
    console.error(error);
    process.exit(2);
  })
function exec() {
  return co(function*() {
    mongoose.connect(`mongodb://localhost/${ GITHUB_ISSUE }`);
    const Model = mongoose.model('Model', new mongoose.Schema({
      name: String
    }));

    const doc = yield Model.create({ name: 'Test MK Call' });
    console.log(doc.name);
    assert.ok(typeof doc.name === 'string');
    assert.ok(!(doc.name instanceof mongoose.Types.ObjectId));
  });
}
```

**Comment by amihajlovski** [comment]
And how can I avoid this behaviour and not store unneeded ObjectIds instead of real strings?

**Comment by varunjayaraman** [comment]
@amihajlovski any update on this?

**Comment by amihajlovski** [comment]
Cannot reproduce it, but however, this became a serious problem because it appears on different "tables" 

Here as a last name: http://prntscr.com/e5dtss --- http://prntscr.com/e5dt3g

Here as telephone number: http://prntscr.com/e5dtbp

Here as first name: http://prntscr.com/e5du3q
