### ISSUE TITLE
pre findOneAndUpdate middleware doesn't skip its end when next() is called

### ISSUE THREAD

**Issue by Gormador** [Automattic/mongoose#4913]
**Do you want to request a *feature* or report a *bug*?**
Encountered a **bug** with a `pre findOneAndUpdate` middleware.

**What is the current behavior?**
A `pre findOneAndUpdate` middleware, when `next()` is called executes the next middleware but also the rest of the current one. Leading to, in my case, errors being thrown that shouldn't be.

A few lines of code will expose the situation, see comments:
```javascript
GeolocSchema.pre('findOneAndUpdate', function(next) {
  // Yes, this works, findOneAndUpdate is called with
  // 'runValidators: true' and 'context: 'query''
  doc = this.getUpdate();

  coord = doc.location.coordinates;

  // This condition is met with my test data
  if (doc.location.type && coord) {
    // As well as this one
    if (Array.isArray(coord) && coord.length === 2) {
      lat = coord[1];
      lon = coord[0];
      if ((-90 <= lat && lat <= 90) && (-180 <= lat && lat <= 180)) {
        // And the next middleware is corectly called.
        next();
      }
    }
  }
  // But this error is still thrown!
  var err = new Error("Long error message irrelevant here.");
  err.status = 400;
  next(err);
});
```
Here is my Express route:
```javascript
router.post('/', function(req, res, next) {
  Geoloc.findOneAndUpdate({
    id: req.body.id
  }, req.body, {
    runValidators: true,
    upsert: true,
    context: 'query'
  }, function(err, post) {
    // if (err) return next(err);
    if (err) console.log(err);
    res.status(201).json(post);
  });
});
```

And here is the data sent:
```JSON
{
  "location": {
    "type": "Point",
    "coordinates": [
      3.0586,
      50.633
    ]
  },
  "count": 1
}
```

**What is the expected behavior?**
Shouldn't it behave like other middlewares and entirely skip to the next one when `next()` is called?

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose v 4.7.7; Node v 6.9.2; MongoDB v 3.4.1-rc0

Please ask away for any other information you may need.

**Comment by santanu-biswas** [comment]
It's not a bug. Its normal behaviour. The code execution is not supposed to stop on calling next(). It just calls the next middleware. To abandon the remaining code execution you can do `return` after the `next()` call (or you can do `return next()`).

**Comment by Gormador** [comment]
Then how do you explain that the code in my [SO question](http://stackoverflow.com/questions/41717602/create-or-update-field-after-pre-validation-middlewares/) does indeed work as expected, i.e. the execution stops?  
Third code block, same coordinates validation code as described here but in a `pre validate` middleware.

**Comment by santanu-biswas** [comment]
If it worked there, then I would suspect - that is a bug.

**Comment by Gormador** [comment]
Hum, after thinking about it you may well be right. For another programming language I would have agreed with you from the start, however JavaScript being... well, JavaScript (and me being a beginner with the language), I thought this could be a feature related to the asynchronous paradigms of Node.JS.

So, dear mongoose collaborators, this issue might be in reverse.

**Comment by vkarpov15** [comment]
Which other middlewares stop execution when you call `next()`? That shouldn't be possible in JavaScript, function execution continues until there's an exception or an explicit `return`.

**Comment by Gormador** [comment]
At this point I'm assuming that there is no bug whatsoever and that this is only the result of me being a derp, but just in case...
(This code is from my linked SO question above.)

These two middlewares are called before a `Post` request's body validation. What made me assume that the 'bug' from this issue was real was that in the code below, the first middleware doesn't generate an error (as described in the comments) despite the lack of a `return` at this line:
```javascript
if ((-90 <= lat && lat <= 90) && (-180 <= lat && lat <= 180)) next();
```
which, by JS standards should generate an error and whatever debug prompts that I put there. But none of that happen, when it in fact does in the code at the origin of the issue.

My guess on the matter is that the next middleware is called and executed faster, interrupting whatever middleware execution still hanging. But this seems very sketchy.
```javascript
// Before validation, check given coordinates for errors.
GeolocSchema.pre('validate', function(next) {
  coord = this.location.coordinates
  if (this.location.type && coord) {
    if (Array.isArray(coord) && coord.length === 2) {
      lat = coord[1];
      lon = coord[0];
      // No 'return next()' here.
      if ((-90 <= lat && lat <= 90) && (-180 <= lat && lat <= 180)) next();
    }
  }
  // Debug prompts at this level don't show up...
  var err = new Error('...'); // Long error text, irrelevant here
  err.status = 400;
  // No error bubbling up to the '.create()' callback either.
  next(err);
});

// Then, if no 'id' is given, create it.
GeolocSchema.pre('validate', function(next) {
  if (!this.id) {
    strLat = this.location.coordinates[1].toFixed(3).replace('.', '_');
    strLon = this.location.coordinates[0].toFixed(3).replace('.', '_');
    this.id = strLat + '-' + strLon;
  }
  next();
});
```

**Comment by vkarpov15** [comment]
Yeah `next()` does not check if `next()` has already been called, so if you call next twice in the same middleware bad things will happen. We'll make that throw an error

**Comment by vkarpov15** [comment]
I took a closer look at this. In 5.0.0 we made it so that double-calling `next()` is a no-op. Throwing an error seems excessive given that right now double-calling `next()` is harmless.
