### ISSUE TITLE
nested array doesn't seem to work

### ISSUE THREAD

**Issue by serganus** [Automattic/mongoose#4914]
**Do you want to request a *feature* or report a *bug*?**
-Bug

**What is the current behavior?**
- I have a schema as follows, please focus on `someauth.registrationRequest.registerRequests` which is `Schema.Type as Array`. Whenever I try to push using `findOneAndUpdate` it saves it as a string. Screenshot for reference for the outcome in MongoDB.

```
'use strict';
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var AuthModelConfiguration = new Schema({
	someauth: {
		registrationRequest: { //startRegistration
			appId: String,
			type: String,
			registerRequests: [{version: String,challenge: String}],
			registeredKeys: [{version: String,challenge: String}]
		}
	}
}, {
	versionKey: false
});

var db = require('../configuration/database').XSHDatabase;
module.exports = db.model('auth', AuthModelConfiguration);
```

![screen shot 2017-01-19 at 7 30 21 pm](https://cloud.githubusercontent.com/assets/12946435/22105164/c3a74bf0-de7d-11e6-87b3-a95cf2038f8d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

- The controller that explains `findOneAndUpdate` is as follows:

```
            var data2push = {
                $set: {
                    'someauth.registrationRequest.appId' : registrationRequest.appId,
                    'someauth.registrationRequest.type' : registrationRequest.type,
                    'someauth.registrationRequest.registerRequests' : registrationRequest.registerRequests,//Is an array not a string by value
                    'someauth.registrationRequest.registeredKeys' : registrationRequest.registeredKeys,
                }
            };

            var condition = {
                email: req.session.email
            };

            AuthModel.findOneAndUpdate(condition, data2push, {
                upsert: true
            }).lean().exec(function(err, doc) {
                if (err) {
                    return next(err);
                }
                res.json('Works!');
            });
```

**What is the expected behavior?**

- The schema type of registerRequests should be `array` not `string`. But this doesn't seem to be the case.

![screen shot 2017-01-19 at 7 33 22 pm](https://cloud.githubusercontent.com/assets/12946435/22105297/4746dc6e-de7e-11e6-8057-822b972d9132.png)

**Please mention your node.js, mongoose and MongoDB version.**

- Node.js : v6.9.2
- mongoose : 4.7.7
- MongoDB : 3.4.0

**Comment by TrejGun** [comment]
you have `registrationRequest` of type `String`
try
```
var AuthModelConfiguration = new Schema({
	someauth: {
		registrationRequest: { //startRegistration
			// _id: false, // probably you want to use this too
			appId: String,
			type: {
				type: String
			},
			registerRequests: [{version: String,challenge: String}],
			registeredKeys: [{version: String,challenge: String}]
		}
	}
}, {
	versionKey: false
});
```

**Comment by serganus** [comment]
@TrejGun Oops! Thanks, maybe i need some sleep :-D
