### ISSUE TITLE
Error: Cannot find module './win32/ia32/bson' from '<mypath>\node_modules\bson-ext\ext'

### ISSUE THREAD

**Issue by mirik123** [Automattic/mongoose#4920]
**Cannot run mongoose client.**

> os: windows
> node: 6.9.1,
> mongoose: 4.7.7
> python: 2.7

I checked all existing conversations regarding this problem and no one actually helps.
Cleaning cache and reinstalling npm packages doesn't help:

> npm cache clean
> remove node_modules
> npm install

I've installed bson-ext separately to avoid another error and has folder "build\Release" after running "node-gyp rebuild". If bson-ext is not installed manually the error is:

> Error: Cannot find module 'bson-ext' from '<mypath>\node_modules\mongodb-core'

And after installing bson-ext I have this error:

> Error: Cannot find module './win32/x64/bson' from '<mypath>\node_modules\mongodb-core\node_modules\bson-ext\ext'

So, how do I fix this issue?

**Comment by varunjayaraman** [comment]
I don't develop on windows so I'm not too familiar with these types of errors, but this looks like a `mongodb-core` problem and not a `mongoose` problem. You're better off opening an issue on that project instead of mongoose.

**Comment by vkarpov15** [comment]
Are you getting this error when you `npm install` or when you're running a node script?

**Comment by mirik123** [comment]
1) I agree that this is more mongodb error than mongoose.
2) The error jumps when I run the script. The installation passes successfully and the Release folder is also created by node-gyp.

**Comment by vkarpov15** [comment]
Can you show me the stack trace?

**Comment by mirik123** [comment]
Hi all,
The problem is solved (or workaround found). It happened when I built application with gulp browserify:
`    var dev = browserify('./server/app.ts', {
            debug: true,
            **browserField: false,**
            builtins: false,
            commondir: false
        });
`

When I removed parameter browserField everything started working. No bson or bson-ext installation is now required.
