### ISSUE TITLE
Can't delete the _id property

### ISSUE THREAD

**Issue by yuwanlin** [Automattic/mongoose#4922]
when I use mongoose query a collection, get a doucment(doc). Then I `delete doc._id`, but I console the `doc._id`, It still exists.

part code:
```
collection.findOne({
      "name": reprint_from.name,
      "time.day": reprint_from.day,
      "title": reprint_from.title
    }, function(err, doc) {
      if(err){
        return callback(err);
      }
      delete doc._id;
      console.log(doc._id) // It still exists.
})
```
when I attempt to `console.log(Object.getOwnPropertyDescriptor(doc,'_id'))`, It's `undefined`
It is a bug? 
```
"mongodb": "^2.2.20",
"mongoose": "^4.7.7",
```
```
node -v  -> v4.4.7
npm -v   -> v2.15.8
```

**Comment by varunjayaraman** [comment]
can you try `doc.set('_id', undefined)`?

using `delete` on mongoose objects is kinda weird because they aren't POJOs, they are mongoose documents with a bunch of getters and setters.

**Comment by yuwanlin** [comment]
It works. when I  set `doc.set('_id', undefined)`, and `console.log(doc._id)`, It returns undefined.  I set `doc._id = undefined` will receive the same.
even so, I get an error like:
```
C:\Users\real\Desktop\study\node2\nodejs_blog\node_modules\.4.7.7@mongoose\lib\model.js:463
  if (where._id.toObject) {
               ^

TypeError: Cannot read property 'toObject' of undefined
// etc.
```

**Comment by vkarpov15** [comment]
So that error should only occur if you try to save the doc...

Mongoose actually tries very hard to prevent you from modifying the document's id if you load the doc from the server. Can you tell me what you're trying to do that requires you to remove the doc's `_id`? There's probably an alternative approach.

**Comment by yuwanlin** [comment]
yeah, I am practicing a blog system.  when I want to reprint other's article,  first remove the original `_id`, I modify It's `reprint_to` property, then save it (Error?). 

 why I remove the original `_id`,  because the new article is based on the original articel( like `var newArticle = new articleModel(doc)`).  If I don't remove it, the new article's `_id` will overlay the original's.

**Comment by yuwanlin** [comment]
I modify something...
I use `newDoc` instead of `doc`, copy doc's some property with out `_id` , don't remove the original `_id`. update `reprint_to`, save it. OK!
then `var newArticle = new articleModel(newDoc)`, Save it, OK!

Appreciate!

**Comment by varunjayaraman** [comment]
Thanks, can I close out this issue @yuwanlin or are you still confused about why you can't do `delete doc._id`?

**Comment by yuwanlin** [comment]
@varunjayaraman  thank you,  I have solved it by above-mentioned details.
