### ISSUE TITLE
post-findOneAndUpdate middleware hangs with passRawResult = true

### ISSUE THREAD

**Issue by bdentino** [Automattic/mongoose#4925]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Post-findOneAndUpdate middleware function defined with two arguments hangs when passRawResult=true. Apparently, it is passing a 3rd `next()` argument that it is expecting to be called. However, when I define the middleware function with 3 arguments, the middleware is skipped altogether (I'm guessing because it assumes this is 'error middleware'). I'm very confused about what is supposed to happen here, or how such middleware should be written for a plugin that is capable of handling both passRawResult=true and passRawResult=false scenarios...

**If the current behavior is a bug, please provide the steps to reproduce.**
Running 
`Model.findOneAndUpdate({ prop: 'xyz' }, { prop: 'abc' }, { upsert: true, passRawResult: true })`
produces the following behavior for each of the different middleware setups:

```
  // This is called, and is passed 2 arguments (the doc, and the raw result)
  schema.post('findOneAndUpdate', function (doc) {
    console.log(arguments)
  })

  // output:
  //
  // { '0': null,
  //  '1': 
  //   { lastErrorObject: 
  //      { updatedExisting: false,
  //        n: 1,
  //     upserted: 5883edc039241549e8322aa0 },
  //     value: null,
  //     ok: 1,
  //     _kareemIgnore: true } }
```

```
  // This hangs, logging arguments shows that a 3rd hidden parameter (function) is passed
  schema.post('findOneAndUpdate', function (doc, result) {
    console.log(arguments)
  })

  // output:
  //
  // { '0': null,
  //  '1': 
  //   { lastErrorObject: 
  //      { updatedExisting: false,
  //        n: 1,
  //     upserted: 5883edc039241549e8322aa0 },
  //     value: null,
  //     ok: 1,
  //     _kareemIgnore: true },
  //  '2': [Function]  }
```

```
  // This is never called, presumably because it's assumed to be an error handler?
  schema.post('findOneAndUpdate', function (doc, result, next) {
    console.log(arguments)
  })
```

```
  // This is actually called, but next and _ are undefined
  schema.post('findOneAndUpdate', function (doc, result, next, _) {
    console.log(arguments)
  })

  // output:
  //
  // { '0': null,
  //  '1': 
  //   { lastErrorObject: 
  //      { updatedExisting: false,
  //        n: 1,
  //     upserted: 5883edc039241549e8322aa0 },
  //     value: null,
  //     ok: 1,
  //     _kareemIgnore: true } }
```

**What is the expected behavior?**
I'd like to be able to access the raw result in my post middleware without causing it to hang. I'd also like to know what the appropriate signature is for a post middleware that might not know if the update operation set passRawResult to true or false

**Please mention your node.js, mongoose and MongoDB version.**
Node 7.2.1, mongoose 4.7.7, mongodb 3.2

**Comment by varunjayaraman** [comment]
Thanks for opening the issue, looks like this is a confirmed bug. I'm able to reproduce it with this:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const chalk = require('chalk');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-4925`;
mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
let Model;

exec()
  .then(() => seedData())
  .then((doc) => runFindOneAndUpdate(doc))
  .then(() => {
    console.log(chalk.green(`Successfully ran func`));
    process.exit(0);
  })
  .catch(error => {
    handleError(error);
  });

function runFindOneAndUpdate(doc) {
  return co(function*() {
    console.log('running find one and update');
    return Model
      .findOneAndUpdate(
        { name: 'Random Name' }, 
        { name: 'abc' }, 
        { upsert: true, passRawResult: true })
      .exec();
  });
}

function seedData() {
  return co(function*() {
    console.log('seding data')
    const name = yield Model.create({
      name: `Random Name`
    });
    console.log('name', name);
    return name;
  });
}

function exec() {
  return co(function* () {
    console.log('execing')
    const schema = new mongoose.Schema({
      name: String
    });

    schema.post('findOneAndUpdate', function(doc, result, next) {
      console.log('arguments', arguments)
    });
    Model = mongoose.model('Name', schema);
  });
}

function handleError(error) {
  console.log(chalk.red(`Error: ${ error }\n${ error.stack }`));
  process.exit(2);
}
```

**Comment by vkarpov15** [comment]
So in 4.8.0 there will be an option for this:

```javascript
var userSchema = new mongoose.Schema({
  name: String,
  email:{
    type:String,
    index:true,
    unique:true,
    required:true
  }
}, { saveErrorIfNotFound: true })
```

Going to release 4.8.0 within the next week so look forward to that :+1:

**Comment by bdentino** [comment]
It seems that after upgrading to 4.8.2, it is now impossible to access the raw result in post-middleware regardless of the function signature. @vkarpov15 is this intentional or am I missing something?

**Comment by vkarpov15** [comment]
@bdentino unfortunately this was intentional, since there's no consistent way to handle `passRawResult: true` and `passRawResult: false` with error handler middleware. This was an API design mistake on our part and I'm sorry about the inconvenience. Can you switch to using `rawResult: true` instead?

**Comment by bdentino** [comment]
Yep, having the mongoose doc available in `result.value` when `rawResult: true` should cover my use case. Thanks!
