### ISSUE TITLE
Virtual populate does not work in subdocuments with separate schema

### ISSUE THREAD

**Issue by ztrange** [Automattic/mongoose#4928]
Related to #4923, using the same test script but now I separated the elements of document.activity onto a new schema ActivitySchema:

If I use a separate ActivitySchema but define the virtual on the DocSchema, it works fine. Is that the way it should be done? I cannot add a virtual population on a non-model schema? I ask because the non-populate virtual fields on a non-model Schema have worked for me on other projects.

```js
const mongoose = require('mongoose')

mongoose.Promise = Promise
mongoose.connect('mongodb://localhost/test')

const {Schema} = mongoose
const {ObjectId} = Schema

const ClusterSchema = new Schema({
  name: String,
})
/*const Cluster = */mongoose.model('Cluster', ClusterSchema)


const ZoneSchema = new Schema({
  name: String,
  clusters: {
    type: [ObjectId],
    ref: 'Cluster',
  },
})
/*const Zone = */mongoose.model('Zone', ZoneSchema)

const ActivitySchema = new Schema({
  cluster: {
    type: ObjectId,
    ref: 'Cluster',
  },
  intensity: Number,
})
ActivitySchema.virtual('zones', {
  ref: 'Zone',
  localField: 'cluster',
  foreignField: 'clusters',
})


const DocSchema = new Schema({
  activity: [ActivitySchema],
})

DocSchema.set('toObject', {virtuals: true})
DocSchema.set('toJSON', {virtuals: true})
const Doc = mongoose.model('Doc', DocSchema)

Doc
  .findOne({})
  .populate('activity.cluster')
  .populate('activity.zones')
  .exec()
  .then(data => {
    console.log(JSON.stringify(data, null, 2))
    mongoose.connection.close()
  })
  .catch(err => console.err(err))

```

**Comment by cliffeby** [comment]
I'm have similar problems populating an array of subdocuments.  Details are posted on stackoverfow at

[http://stackoverflow.com/questions/41787345/populate-mongoose-array-subdocuments]

**Comment by vkarpov15** [comment]
That's a bug, fixed in https://github.com/Automattic/mongoose/commit/f19b88f16e97b0ccc90f0462a130ab129bd9d0a8
