### ISSUE TITLE
Unexpected Disconnects with Replica Set

### ISSUE THREAD

**Issue by Icydillic** [Automattic/mongoose#4931]
**Do you want to request a *feature* or report a *bug*?**
I'd like to report a Bug.

**What is the current behavior?**
When connected to a replica set the connection unexpectedly disconnects. We tested several versions before and all disconnected after a few hours or sometimes after a week. Even in the night where the database is not used and the process is idle it disconnects.
After the disconnect it now reconnects, what it did not with version 4.6.8 (there it stays disconnected).

This only happens when connecting to a replica set. When connecting to a single instance the connection stays open as long as the server is running. Only exceptions end an open connection.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is how we connect to our replicaset

    mongoose = require('mongoose');
    mongoose.Promise = require('q').Promise;
    config = require('config');

    dbOptions = {
        server : {
            reconnectTries: Number.MAX_VALUE,
            socketOptions : {
                keepAlive : 120
            }
        },
        auth: { authdb: 'admin' },
        user: config.dbUser,
        pass: config.dbPassword,
        replset: {
            strategy: 'ping',
            rs_name: config.dbReplSetName,
            socketOptions : {
                keepAlive : 120
            }
        }
    };

    const dbConn = mongoose.createConnection(config.mongo.uri, config.mongo.dbOptions);

    dbConn.on('connected', function () {
        console.log('Mongoose default connection open to '+ config.dbUri);
    });
    dbConn.on('disconnected', function () {
        console.log('Mongoose connection to '+ config.dbUri +' disconnected');
    });

**What is the expected behavior?**
It would be nice if the connection keeps open.
Perhaps it is normal that it disconnects after a while, but it is definitively no timeout behaviour.

**Please mention your node.js, mongoose and MongoDB version.**
We are using mongoose 4.7.6. When using 4.7.8 the requests are hanging.

Any advice is appreciated. :o)
Thank you very much and best regards,
Stefan

**Comment by JacksonTian** [comment]
It seems mongodb v2.2.22 fixed it. please upgrade dependence, and release a new version.

**Comment by Icydillic** [comment]
We let the server run a few days and it seems with version 4.7.8 the disconnects disappeard.
The hanging requests occured because of different hostnames on mongoDB replicaset configuration and the connection string.
We used <hostname.xyz.com> only on mongoDB replicaset config side and <hostname> only on connection string side. Correcting both to use the FQDN solved the issue.

Thank you very much and best regards,
Stefan
