### ISSUE TITLE
Missing subdocument while trying to fetch a document, using the schema below

### ISSUE THREAD

**Issue by naveenwashere** [Automattic/mongoose#4932]
**Mongoose** Version tried with: **4.7.7** and **4.7.8** (tried both)
**MongoDB** Version tried with: **3.2** and **3.4** (tried both)
**Node** Version: **7.4.0**

**Issue:**
I am creating an accounts table with the schema as shown below. I have just one account document for a user in a mongo server that's running in my localhost. After defining the schema and adding a single account document, I wrote an endpoint to query and fetch that document (`Model.find(id: '12345'`)) using the `id` key. The resulting JSON document has all the data except the subdocument named `accRef` as show in the Schema below. When I try the same `find` query using the Mongo Shell, I get the results perfectly. I've been trying to find what's causing this for almost an entire day now, without making much headway. Any help would be highly appreciated.

I started with an empty schema and added each field one by one, starting with the `id` attribute and fire the `find` query. Every single time, I get all the 75+ elements and subdocuments, but the moment I add the `accRef` subdoc to my schema, this piece of info disappears from the result.

Is there a limitation to the number of subdocuments that can be defined in mongoose's schema?

Also, I cannot seem to insert/save any new account object using the same schema as shown below. However, I can perform this insert/save operation using the very same JSON object, using a client like MongoChef.

Here's my JS module where I've defined my schema:

```
import mongoose from 'mongoose';
mongoose.connect('mongodb://localhost:27017/accounts');

const Schema = mongoose.Schema;

const accountsSchema = new Schema({
  _id: Schema.ObjectId,
  id: String,
  uuid: String,
  firstName: String,
  lastName: String,
  contactNumber: Number,
  dob: Date,
  email: String,
  originalEmail: {type: String, index: true},
  password: String,
  socialMedia: {
    facebook: {
      id: String,
      email: String,
      token: String
    }
  },
  domainInfo: {
    country: String,
    currency: String,
    lang: String,
    domain: String
  },
  profile: {
    type: Number,
    id: Number,
    points: Number,
    accumulated: Number
  },
  perks: {
    id: Number,
    type: Number
  },
  address: {
    address: String,
    postalCode: String
  },
  paymentInfo: {
    cardNumber: String,
    isValidCard: Number,
    paypal: {
      email: String
    },
    bank: {
      bankName: String,
      bankNumber: String,
      accontId: Number,
      accountHolderName: String,
      bankBranchCode: String,
      paymentTypeId: Number
    },
    dateCreated: {type: Date, default: Date.now},
    dateModified: {type: Date, default: Date.now},
    createdAt: {type: Date, default: Date.now},
    updatedAt: {type: Date, default: Date.now}
  },
  metadata: {
    timezone: String,
    ipAddress: String,
    signupMeta: String,
    clientUserAgent: String,
    signupUrl: String
  },
  accRef: {
    type: String,
    code: String,
    url: String
  },
  key: String,
  parentId: String,
  type: String,
  utm: String,
  bounced: Number,
  status: Number,
  isPoints: Number,
  isAdmin: String,
  dateTutorialCompleted: {type: Date, default: Date.now},
  dateCreated: {type: Date, default: Date.now},
  dateModified: {type: Date, default: Date.now},
  dateAccessed: {type: Date, default: Date.now},
  dateVerified: {type: Date, default: Date.now},
  datePurchased: Date,
  createdAt: {type: Date, default: Date.now},
  updatedAt: {type: Date, default: Date.now}
});

const Account = mongoose.model('Account', accountsSchema);

export default Account;
```

The function in the service class that fires the mongo query:

```
import Account from '../../models/mongo';

const getAccountById = (accountId) => {
  return Account.find({id: accountId})
    .then(response => {
      if(response.length === 0) {
        throw new Error("Account Not Found");
      }
      console.log(response);
      return response;
    })
    .catch(error => {
      throw new Error(error.message);
    });
};
```

Thanks in advance!
Naveen

**Comment by varunjayaraman** [comment]
Without seeing how you are creating your document, my guess is that you're running into a `typeKey` error so your subdoc isn't getting added properly: http://mongoosejs.com/docs/guide.html#typeKey

Mongoose treats the `type` property differently, so if you want to name your property on the subdoc `type`, you need to specify the `$typeKey` in the schema definition.

Alternatively, you could change the field name to something else (which is what I generally prefer).

If that doesn't solve it, we'll need to see exactly how you're creating your documents.

**Comment by vkarpov15** [comment]
@varunjayaraman is right. 

```javascript
accRef: {
    type: String, // <-- means accRef is of type 'string', rather than an object with a property 'type'
    code: String,
    url: String
  }
```

Try this

```javascript
accRef: {
    type: { type: String },
    code: String,
    url: String
  }
```

To be more defensive about this issue in the future, consider using the typeKey option: http://mongoosejs.com/docs/guide.html#typeKey
