### ISSUE TITLE
Is possible to access children fields in query helper functions?

### ISSUE THREAD

**Issue by guzgarcia** [Automattic/mongoose#4939]
Good day. The title describe my question. I have two collections: `Person` and `User`. Person is referenced in User collection. The Person collection has the username, email, and password fields. In order to login an user I wrote this query:

```javascript
User.findOne({
  $and: [
    {
      $or: [
        { 'person.username': username },
        { 'person.email': username }
      ],
      'person.password': password
    }
  ]
});
```
But it didn't work. Am I doing the query wrong or this feature isn't implemented?

**PS:** I'm using MongoDB 3.4.0 and Mongoose 4.7.8

**Comment by varunjayaraman** [comment]
Can you post both schemas? If `person` is just a Mongo id, you cant search that way.

If your user schema looked like this, it would work:

```
const userSchema = new mongoose.Schema({
  person: { username: String, email: String },
  password: { String } // by the way, I hope you aren't actually storing your passwords in plain text!!
});
```

**Comment by guzgarcia** [comment]
> by the way, I hope you aren't actually storing your passwords in plain text!!

Lol, no! It's just a fast test.

> Can you post both schemas

Sure, the Person is a independent collection, it's not an embedded doc.

**User**

```javascript
const UserSchema = new Schema({
  role: {
    type: Schema.Types.String,
    required: true,
    default: 'USER'
  },
  website: {
    type: Schema.Types.String,
    required: true,
    default: 'http://blablabla.com'
  },
  state: {
    type: Schema.Types.String,
    required: true,
    default: 'waiting'
  },
  person: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'Person'
  }
});
```

**Person**
```javascript
const PersonSchema = new Schema({
  username: {
    type: Schema.Types.String,
    required: true,
    unique: true
  },
  email: {
    type: Schema.Types.String,
    required: true,
    unique: true
  },
  password: {
    type: Schema.Types.String,
    required: true
  },
  avatar: {
    type: Schema.Types.String,
    default: 'https://thesocietypages.org/socimages/files/2009/05/vimeo.jpg',
    required: true
  }
});
```

**Comment by varunjayaraman** [comment]
Just making sure re: the passwords 👍 

As for your schema, that's not gonna work then. Seems like a User is pretty useless without the Person information, so you may as well make it an embedded doc. 

You can also use a discriminator if you want to compose a subclass from the `UserSchema` can create a `Person` collection that would inherit all of the `User` schema properties

**Comment by guzgarcia** [comment]
You're right. I will use the personal data as a embedded document. That's has more sense. Thanks for your assistance.
