### ISSUE TITLE
Incorred pluralization for collections ending in "ed"

### ISSUE THREAD

**Issue by OmgImAlexis** [Automattic/mongoose#4940]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Collections ending in "ed" end up with a "s" added after them.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a collection called "episodes_watched" it creates "episodes_watched**s**"

**What is the expected behavior?**
For it to parse the "ed" correctly.

**Please mention your node.js, mongoose and MongoDB version.**
N/A

**Comment by varunjayaraman** [comment]
Your collection name doesn't really follow mongoose convention, i'd probably name it `WatchedEpisode` which will translate to a collection name of `watchedepisodes`.

If you aren't going to follow the convention, you can also pass a collection name as the 3rd parameter to the `mongoose.model` function:

```
const Model = mongoose.model('episodes_watched', schema, 'episodes_watched');
```
