### ISSUE TITLE
Can't get mapReduce stats when using global.Promise

### ISSUE THREAD

**Issue by steve-p-com** [Automattic/mongoose#4945]
I am looking at an issue with Mongoose 4.7.8 and Node.js 6.9.4 where `model.mapReduce` works as expected when using a callback, but does not work as documented when using the global promise:

```
mongoose.Promise = global.Promise
```

As per the documentation. when using `mapReduce` with a callback function with a signature like this

```
MyModel.mapReduce(o, function (err, model, stats) {
  // all good
})
```

it works as expected. But if I try to use a promise instead, `model` is fine, but `stats` is always undefined.

I see that inside `lib/model.js` the relevant code is

```
callback && callback(null, model, stats);
return resolve(model, stats);
```

However, my understanding of `resolve` is that there can only be a single parameter:

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

So, copying some lines directly from the mongoose documentation, this can't work:

```
promise.then(function (model, stats) {
  console.log('map reduce took %d ms', stats.processtime)
```

`stats` will always be undefined.

Am I misunderstanding how promises work, or is this a compatibility legacy of when mongoose used mpromise? I know it's a breaking change, but will you need to change the resolve value to an object like this:

```
return resolve{
  model: model,
  stats: stats
})
```

I would really like to use promises so that I can chain them together, but I also need the stats.

**Comment by vkarpov15** [comment]
Sorry we missed this issue for so long, not sure how it slipped through the cracks. You're right, this is a compatibility issue with mpromise vs ES6 promises, mpromise allowed `resolve()` with multiple values but ES6 promises resolve to exactly 1 value. Use the `resolveToObject` option for `mapReduce()` to turn on the object mode behavior.

```javascript
    var o = {
      map: function() {
      },
      reduce: function() {
        return 'test';
      },
      resolveToObject: true
    };
    MyModel.mapReduce(o).then(res => { const model = res.model; const stats = res.stats });
```

**Comment by steve-p-com** [comment]
Great, thank you!
