### ISSUE TITLE
TypeError: Class constructor MongoTenantModel cannot be invoked without 'new'

### ISSUE THREAD

**Issue by benhjames** [Automattic/mongoose#4947]
This error occurs in Mongoose v4.8.1 but not in v4.7.7.

```
TypeError: Class constructor MongoTenantModel cannot be invoked without 'new'
    at /Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/mongoose/lib/model.js:1818:51
    at /Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/async/internal/parallel.js:27:9
    at eachOfArrayLike (/Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/async/eachOf.js:57:9)
    at exports.default (/Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/async/eachOf.js:9:5)
    at _parallel (/Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/async/internal/parallel.js:26:5)
    at parallelLimit (/Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/async/parallel.js:85:26)
    at /Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/mongoose/lib/model.js:1836:5
    at Function.create (/Users/benjames/Documents/Development/ToPlayFor/TP4Web/toplayfor-server/node_modules/mongoose/lib/model.js:1803:17)
```

Here is the line of code that causes the issue, where `Reply` is a mongoose model:

```
await Reply.create({ reply });
```

I would expect that this creates a reply, as it does in v4.8.1! I had a quick look in `lib/model.js` for the offending line 1818, and hopefully it's just as simple as adding `new` to that line.

Using Node v6.9.1. If you need anything else let me know - cheers! 😃

**Comment by varunjayaraman** [comment]
@benhjames you're probably right, but can wee see your schema and how the Model is created just to be sure?

**Comment by benhjames** [comment]
Sure, here's some links to the source of the Model creation:

https://github.com/superscriptjs/superscript/blob/master/src/bot/db/models/reply.js

**Comment by varunjayaraman** [comment]
Cool, thanks

**Comment by alrik** [comment]
I think the issue was introduced in a66a8cadb27941a4010134c73f07c2a0e615a996.
The problem may also be related to the https://github.com/craftup/node-mongo-tenant plugin.
@varunjayaraman What do you think is this a regression bug of mongoose or should the plugin be aware of the new create logic?

**Comment by varunjayaraman** [comment]
The plugin should probably be aware of the new create logic. I've never used `mongo-tenant`, but if it's plugin-specifiy, you're probably better off opening up a PR there

**Comment by vkarpov15** [comment]
Yeah @varunjayaraman this was a bug with the create changes, I accidentally dropped the `new`. The discriminator changes shouldn't break this behavior.

**Comment by Rajeshsinghcse** [comment]
var MongoStore = require('connect-mongo')(session);
                                         ^

TypeError: Class constructor MongoStore cannot be invoked without 'new'
