### ISSUE TITLE
Documentation doesn't specify params for `callback`

### ISSUE THREAD

**Issue by nhooey** [Automattic/mongoose#4949]
I'm talking about the documentation specifically here:
http://mongoosejs.com/docs/api.html#query_Query-findOne

The documentation for `callback` in this case doesn't specify what parameters this callback function should take. It demonstrates those parameters in the example, but it's not included in the definition.

Other pieces of documentation including `callback` didn't have examples as lucky as this one that show the parameters.

Instead of just saying:
```
Parameters
...
[callback] <Function>
```
The documentation should say something like this:
```
Parameters
...
[callback(error, record)] <Function> - A callback function executed after the query
    has been run that takes an error and a record as parameters.
```

**Comment by varunjayaraman** [comment]
@nhooey the docs def need some love.

Do you have a list of any others where the callback params are unclear / not listed?

**Comment by nhooey** [comment]
It would be nice if I had a list, but I just found this one and reported.
