### ISSUE TITLE
Getting "DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated"  after adding `mongoose.Promise = global.Promise;`

### ISSUE THREAD

**Issue by sahibjotsaggu** [Automattic/mongoose#4950]
I'm still getting the promise deprecation warning after adding the `mongoose.Promise = global.Promise;` line before connecting to the database.

This is the full terminal output:
```
→ nodemon server.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
Magic happens on port 8080
a user has came to the app.
(node:8020) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
(node:8020) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: data and salt arguments required
```

You can see the last commit before this error started occuring here: https://github.com/sahibjotsaggu/MEAN/commit/abdf6f8e112a010c85466e58691d7f5117b71b19#diff-78c12f5adc1848d13b1c6f07055d996e

To reproduce the issue, clone the repository (https://github.com/sahibjotsaggu/MEAN)
```
npm install
nodemon server.js
```

Then use Postman or a similar software to create a POST request to `localhost:8080/api/users` with `x-www-form-urlencoded` data and with the name, username, and password fields filled out.

The expected behaviour is a response of `User created!`

node.js version: `v6.9.5`
mongoose version: `latest`
mongodb version: `MongoDB shell version: 3.0.5`

**Comment by varunjayaraman** [comment]
The problem is you are requiring in your `User` model in `server.js` before setting the mongoose Promise constructor. SO the model has already been instantiated with `mpromise, not `global.Promise`. Always set `mongoose.Promise = global.Promise` at the top most level of your app if you want to avoid bugs like this.

Heres an example:

```javascript
var mongoose = require('mongoose');
var port = process.env.PORT || 8080;
mongoose.Promise = global.Promise;
var User = require('./user');


const GITHUB_ISSUE = `gh-4950`;

try {
exec();

} catch (error) {
  console.error(error);
}

function exec() {
  var db_url = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
  mongoose.connect(db_url);
  var user = new User();
  user.name = 'bob';
  user.username = 'jones';
  user.password = 'password';

  user.save(function(err) {
    console.log('err', err);

  });
}
```

**Comment by sahibjotsaggu** [comment]
After following your example, I am getting another error: 

```
(node:8291) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: data and salt arguments required
```

This is what my `server.js` looks like:
```javascript
var express = require('express');
var bodyParser = require('body-parser');
var morgan = require('morgan');
var mongoose = require('mongoose');
var port = process.env.PORT || 8080;
mongoose.Promise = global.Promise;
var User = require('./app/models/user');

try {
	exec();
} catch (error) {
	console.error(error);
}

function exec() {
	var db_url = 'mongodb://localhost:27017/MEAN';
	mongoose.connect(db_url);
}

var app = express();
...
```

**Comment by varunjayaraman** [comment]
that has nothing to do with mongoose. That's because you're using `bcrypt.compare` improperly here https://github.com/sahibjotsaggu/MEAN/blob/master/app/models/user.js#L28-L36: the `hash` function requires the 2nd (hash) and 3rd (the salt) parameters to be defined.

See: https://github.com/sahibjotsaggu/MEAN/blob/master/app/models/user.js#L28-L36
