### ISSUE TITLE
Validation for elements in array not happening on update

### ISSUE THREAD

**Issue by erickcsh** [Automattic/mongoose#4953]
I have a similar schema like:

```
var childSchema = new Schema({
  info: {
    name: {
       type: String,
       required: true
    },
    lastName: {
       type: String,
       required: true
    }
  }
})

var parentSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  children: [childSchema]
})

model = mongoose.model('Parent', parentSchema) 
```

But when I am trying to update an existing one like
```
Parent.findByIdAndUpdate('id', {
 $addToSet: { children: { info: {  name: 'Test' } }
}, { new: true })
```

The children is being added, and the required validation for the lastName property is not happening. I can actually see the object in the database now being
```
{ _id: 'id',
  name: 'SomeName',
  children: [{ name: 'Test' }]
```

I am using mongoose 4.8.1
node 5.4.1
MongoDB shell version: 3.2.1

**Comment by varunjayaraman** [comment]
So 2 things:

1) `required` validators only run in update operations for unset operations: http://mongoosejs.com/docs/validation.html#update-validators

2) If you are trying to do other types of validation, make sure you remember to set `runValidators: true` in your update options

**Comment by Saravanan90** [comment]
@vkarpov15 I'm using `v4.11.3`, the issue still persists as reported https://stackoverflow.com/questions/43467316/addtoset-in-mongoose-does-not-run-custom-update-validation

May I know why the issue is closed?
