### ISSUE TITLE
ancestors function?

### ISSUE THREAD

**Issue by virgiltu** [Automattic/mongoose#4956]
Is this function anywhere in mongoose? I cant find anything about it in the documentation.

**Comment by varunjayaraman** [comment]
@virgiltu can you clarify what you mean?

**Comment by virgiltu** [comment]
I was just curious y there is no documentation of the ancestors function that mongodb has.

**Comment by vkarpov15** [comment]
MongoDB doesn't have any ancestors function that I'm aware of
