### ISSUE TITLE
Post hooks not firing on Ubuntu, but working properly on MacOS

### ISSUE THREAD

**Issue by nacq** [Automattic/mongoose#4957]
My dev environment is MacOS, node v6.9.4, mongoose latest, express 4.13.1, and the Linux box an Ubuntu 16.04 with the same node, mongoose, express versions than the Mac, with the hooks definition being on a separated file are not being called after a Model.save() or Model.remove(), but if I define the hooks on the same file where the mongoose schema is, the hooks work correctly, any idea why? Is there any error in my code?

**User.js**

```
const mongoose = require('bluebird').promisifyAll(require('mongoose'))  

const UserSchema = new mongoose.Schema({  
  name: {  
    type: String,
    required: true,
    trim: true
  },
  username: {
    type: String,
    required: true,
    trim: true,
    unique: true,
    lowercase: true
  },
  password: {
    type: String,
    required: true
  },
  role: {
    type: String,
    required: true,
    trim: true
  },
  status: {
    type: Boolean,
    required: true,
    default: false
  }
})

module.exports = mongoose.model('User', UserSchema)
```

**user.events.js**

```
const Model = require('./User')
const EventEmitter = require('events')
const EE = new EventEmitter()

EE.setMaxListeners(0)

Model.schema.post('save', function (doc) {
  EE.emit(`save:${doc._id}`, doc)
  EE.emit('save', doc)
})

Model.schema.post('remove', function (doc) {
  EE.emit(`remove:${doc._id}`, doc)
  EE.emit('remove', doc)
})
```

**Comment by varunjayaraman** [comment]
@nacq can I go ahead and close this or did the fix of defining your hooks before calling `mongoose.model()` not work?

**Comment by nacq** [comment]
My concern is why is working on one machine and not on the other

**Comment by nacq** [comment]
You can close it
