### ISSUE TITLE
Since upgraded mongoose from 4.7.7 to 4.8.0 my mocha tests outputting promise deprecation warning

### ISSUE THREAD

**Issue by cebor** [Automattic/mongoose#4961]
Since the upgrade from 4.7.7 to 4.8.0 i get the following warning in my mocha Tests:

With 4.8.0
```
  /auth
    /register - POST
(node:2896) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
      ✓ it should register user (284ms)
    /login - POST
      ✓ it should login user
    /test - GET
      ✓ it should auth user (53ms)
      ✓ it should reject user with invalid token
      ✓ it should reject user with invalid token type
      ✓ it should reject user with no token
```
Test: https://travis-ci.org/whomeetswho/wmw-api/jobs/196528596#L183

With 4.7.7
```
  /auth
    /register - POST
      ✓ it should register user
    /login - POST
      ✓ it should login user
    /test - GET
      ✓ it should auth user (38ms)
      ✓ it should reject user with invalid token
      ✓ it should reject user with invalid token type
      ✓ it should reject user with no token
```
Test: https://travis-ci.org/whomeetswho/wmw-api/jobs/193202626#L185

-----

As described in the moongose docs i set the promise correctly, see https://github.com/whomeetswho/wmw-api/blob/master/app/server.js#L15.

Project Source: https://github.com/whomeetswho/wmw-api

Node: 7.5.0
mongoose: 4.8.1
macOS: 10.12

**Comment by varunjayaraman** [comment]
You're using a promise in your tests before setting `mongoose.Promise`. Remember that `require()` is a singleton, so you have to set `mongoose.Promise = yourPromiseConstructor` before ever using a promise for the warning to go away.

The warning is coming from your `app/auth/router.spec.js` file: You've defined your mongoose models and constructed them using `mongoose.model()` before ever setting the `Promise` constructor (which happens in `app/server.js`): https://github.com/whomeetswho/wmw-api.git

Note how you only require `server.js` after that. If you move `require('../server')` above where you `require('./user.model')`, the error will go away:

```javascript
process.env.NODE_ENV = 'test';

const server = require('../server');
const User = require('./user.model');
const Token = require('./user.model');

const chai = require('chai');
const chaiHttp = require('chai-http');
const should = chai.should();
```

**Comment by rodrigogs** [comment]
I'm having the same problem. The thing is... I just updated mongoose from 4.7.6 to 4.8.1, and it seems that the promise library is being ignored now.
I didn't change a line of code, just updated mongoose lib.

**Comment by cebor** [comment]
@rodrigogs yes, had the same behavior but changing the order of the require statements fixed for me.

btw big thanks @varunjayaraman for the detailed answer.
