### ISSUE TITLE
Post hook unable to consume error

### ISSUE THREAD

**Issue by a-koka** [Automattic/mongoose#4968]
**Versions**
Node: 6.8.1
Mongoose: 4.8.1
MongoDB: 3.4.0

**Bug**
Consume an error in the `post` hook.

**Description**
I need to ignore a duplicate key error from MongoDB (error code 11000) and still return a 204 HTTP response from my `Express.js` app.

**Code Below**

    const createMyModel = (req, res, next) => {
      MyModel.create({...data})
      .then(createRes => res.status(204).send())
      .catch(next)
    }

    MySchema.post('save', (err, res, next) => {
      if (!err || (err.name === 'MongoError' && err.code === 11000)) {
        // The duplicate key error is caught here but somehow
        // the catch on my service layer gets triggered 
        next();
      }else{
        next(err)
      }
    });

**Expected behavior**
The `save` fails with a `11000` error but still return a `204` from the `then` callback.

**Comment by clement-escolano** [comment]
@a-koka This is normal as the error triggers the catch part of the promise. I am not a promise expert but you should either duplicate the expected answer :
```js
const createMyModel = (req, res, next) => {
  MyModel.create({...data})
  .then(createRes => res.status(204).send())
  .catch(createRes => res.status(204).send())
}
```

or you can use finally (not sure about this one)
```js
const createMyModel = (req, res, next) => {
  MyModel.create({...data})
  .finally(createRes => res.status(204).send())
}
```

**Comment by a-koka** [comment]
That wouldn't work reliably as now we'd be ignoring all errors that get thrown by `create`. The fact that the `post` hook takes in `next` as a parameter makes me believe that this is a bug and it is intended to work the way I'm expecting it to.

**Comment by varunjayaraman** [comment]
@a-koka is this used all over your app or is it only in one place? I would probably recommend wrapping the `create` or `save` operation in a `try-catch` block so you can catch the error thrown and then handle it how you want. I think @clement-escolano is right here: since this is error-handling middleware, this is operating within the `rejected` domain of a Promise. If you want to catch the rejection and handle it, that's up to you. I'll loop @vkarpov15 in though since I think this could be a discussion.

**Comment by a-koka** [comment]
No, it isn't and I'm addressing my specific use case explicitly now. I investigated further and looks like `next` internally keeps track of `firstError` which triggers the `catch` even if I call `next(null)` in my hook.
