### ISSUE TITLE
mongoose 4.8.1 model.schema.post not working

### ISSUE THREAD

**Issue by patrikx3** [Automattic/mongoose#4971]
FinancialDocument.schema.post('save', function (doc) {
    onSave(socket, doc);
  });

In 4.7.8 I can emit socketio, the pre save works

In 4.8.1 the post save is not executed.

I updated and that is that is chanagd. When I rever 4.7.8 works. Update 4.8.1, not working with modelschem.post('save') not executing.

**Comment by varunjayaraman** [comment]
@patrikx3 are you editing the schema after you've called `mongoose.model()`. That behavior was never **really** supported before 4.8.1 but it won't work at all in 4.8.1 and after. Always finish editing your schemas before calling `mongoose.model()`

**Comment by mfonolleda** [comment]
I also installed 4.8.1/2 and the post-save hooks (probably others as well) stopped working, both on my dev and prod environment. I installed back 4.7.6 and the hooks worked as expected.

Could just be a problem on my side, but I thought I would mention just in case...

**Comment by patrikx3** [comment]
This is the exact code. Old code.
4.7.6 works, latest stopped working. 

Model:
```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const Partner = require('../partner/partner.model');
const Currency = require('../currency/currency.model');

const ngivrStrings = require('../../../client/shared/ngivrStrings');

const FinancialDocumentSchema = new Schema({
  accountingDate: Date, //könyvelés dátuma
  registryDate: Date, //iktatás dátuma

  bruttoValue: Number, //bruttó érték
  currency: [Currency.schema], //deviza
  documentNumber: String, //bizonylatszám
  documentType: { //bizonylat típusa
    type: String,
    enum: Object.keys(ngivrStrings.financialDocument.documentType).map((key) => key)
  },
  partner: [Partner.schema], //partner
  relatedInvoices: [ //kapcsolódó számlák
    {invoiceId: Schema.Types.ObjectId}, //számla ID
    {bruttoValue: Number} //számla bruttó értéke
  ],
  lockedFor : {
    type: Schema.Types.ObjectId,
    default: null
  },
  visible: {
    type: Boolean, //láthatóság
    default: true
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('FinancialDocument', FinancialDocumentSchema);
```

Socket:
```
/**
 * Broadcast updates to client when the model changes
 */

'use strict';

var FinancialDocument = require('./financialDocument.model');

exports.register = function(socket) {
  FinancialDocument.schema.post('save', function (doc) {
    onSave(socket, doc);
  });
  FinancialDocument.schema.post('remove', function (doc) {
    onRemove(socket, doc);
  });
}

function onSave(socket, doc, cb) {
  socket.emit('financialDocument:save', doc);
}

function onRemove(socket, doc, cb) {
  socket.emit('financialDocument:remove', doc);
}
```

Save:
```
  /**
   * Saves a document model and send the data to the response.
   * @param response
   * @param document
   */
  static save(response, document) {

    document.save().then((document) => {

      response.status(200).json({
        doc: document
      });
      return document;

    }).catch((error) => {

      this.sendErrorResponse(response, error);
      return error;

    });
  }

```

**Comment by varunjayaraman** [comment]
@patrikx3 so your problem is exactly what it said it was. You are registering your hooks on your schema after calling `mongoose.model()` because `mongoose.model()` gets called in `financialDocument.model.js`.

While this was never really supported before 4.8.1, it sort of worked sometimes, but it is **not supported anymore whatsoever**. Don't modify your schema after calling `mongoose.model()`.

```javascript
FinancialDocument.schema.post('save', function (doc) { // Don't do this!
    onSave(socket, doc);
  });
  FinancialDocument.schema.post('remove', function (doc) { // or this!
    onRemove(socket, doc);
  });
```

**Comment by patrikx3** [comment]
hold on, this is wrong, the socket is before the model!

**Comment by varunjayaraman** [comment]
@patrikx3 it requires in the model that's already instantiated. You call `mongoose.model()` at the bottom of the file. Once you do that, you can't mutate the schema any more by registering hooks.

**Comment by patrikx3** [comment]
i understand, but i am registering before the model! that's what you said. i should do it before the model. that is what i exactly do. i register the hooks before the 
`module.exports = mongoose.model('FinancialDocument', FinancialDocumentSchema);`

**Comment by patrikx3** [comment]
the model is executing way later the socketio registering.

**Comment by varunjayaraman** [comment]
@patrikx3 are you doing that elsewhere? In the code you posted, you are not registering the hooks before `mongoose.model()` gets called

**Comment by patrikx3** [comment]
ahh you are right, sometimes it is after!! you are right! thanks!

**Comment by varunjayaraman** [comment]
no worries, glad the issue's resolved :P

**Comment by patrikx3** [comment]
hold on, so how do i do the hooks now?  if there is no model before??

**Comment by patrikx3** [comment]
`module.exports = mongoose.model('FinancialCostBearer', FinancialCostBearerSchema);`

http://mongoosejs.com/docs/middleware.html

It says i have to have a schema. how can i do it?

**Comment by varunjayaraman** [comment]
you basically need to register the hooks before calling `mongoose.model()`. Maybe you can flip the order of things and import the socket stuff into your schema (since you seem to need access to the the socket instance in the hook).

**Comment by patrikx3** [comment]
but i need the schmea before, can you show an example? weird.

**Comment by patrikx3** [comment]
i understand i have to register before, but how can i register into a schema if is not existing?

**Comment by patrikx3** [comment]
i got the code, but i need the schema before, if it is not existing how can i hook?:

```
var ZipCode = require('./zipCode.model');

exports.register = function(socket) {
  ZipCode.schema.post('save', function (doc) {
    onSave(socket, doc);
  });
  ZipCode.schema.post('remove', function (doc) {
    onRemove(socket, doc);
  });
}

function onSave(socket, doc, cb) {
  socket.emit('zipCode:save', doc);
}

function onRemove(socket, doc, cb) {
  socket.emit('zipCode:remove', doc);
}

```

**Comment by varunjayaraman** [comment]
I'm not sure i understand what you mean. The schema exists as the variable `FinancialDocumentSchema` in `financialdocument.model.js`. That's the schema, and inside `financialdocument.model.js`, you add the hooks to `FinancialDocumentSchema` before calling `mongoose.model()`. With mongoose, we call the object returned from `mongoose.model()` the **model** and the second parameter passed to `mongoose.model()` the **schema**, so you would mutate the schema before creating the model.

**Comment by patrikx3** [comment]
i never use mongoose.model(), where is it?

**Comment by patrikx3** [comment]
ah got it. but where do i put it?

**Comment by patrikx3** [comment]
got it! before the model!!! got it thanks!

**Comment by varunjayaraman** [comment]
model:

```javascript
'use strict';

var mongoose = require('mongoose'),
  Schema = mongoose.Schema;

var ZipCodeSchema = new Schema({
  zipCode: String,
  settlement: String
},{
  timestamps: true
});

ZipCodeSchema.pre('save', function() { ... // register hook 1});
// do that for future hooks

module.exports = mongoose.model('ZipCode', ZipCodeSchema); // you use mongoose.model here

```

**Comment by ateixeiramunoz** [comment]
Working on 4.7.9 as expected.
