### ISSUE TITLE
running virtual method from schema

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#4974]
mongoose 4.8.1

i have a virtual method in my model;

```
  schema.virtual('isModeratable').get(function () {
    return options.moderated; // returns if content type is moderatable (ie, can have awaiting_moderation status).
  });
```

i want to call from schema definition instead of instance;

`    console.dir(model.schema.virtual('isModeratable'))`

this shows it's existince but how can i call it?

**Comment by varunjayaraman** [comment]
@bonesoul why can't you just use a static method instead? Virtuals are essentially instance getters, so kind of confused about your use case here.

**Comment by bonesoul** [comment]
the reason is that it's attached by a plugin;

```
function moderation (schema, options) {
  options = options || { autoApproved: false, selfDeletable: false };

  // add fields.
  schema.add({
...
  });

  // virtuals
  schema.virtual('isModeratable').get(function () {
    return true;
  });

  schema.virtual('isAutoApproved').get(function () {
    return options.autoApproved; // returns if content type is auto-approved.
  });

  schema.virtual('isSelfDeletable').get(function () {
    return options.selfDeletable; // returns if content type is self-deletable.
  });
```

so basically with this virtuals i can check what model is capable of - but i'll give static methods a try.

**Comment by bonesoul** [comment]
@varunjayaraman @vkarpov15 is 'options' a reserved word by mongoose?

**Comment by bonesoul** [comment]
by the way i've a hacked a way to call it;

```
let isModeratableFunc = _.head(model.schema.virtual('isModeratable').getters);

then;

isModeratableFunc()
```

**Comment by varunjayaraman** [comment]
@bonesoul so basically a virtual is the same thing as a static method that takes in the instance as its first parameter. The two are pretty much the same except for the fact that the virtual is a getter so you don't have to invoke it, while the static is a function that has to be invoked. I'm a bit confused in your example where you need to call the virtual from within the plugin though?

**Comment by bonesoul** [comment]
I don't call it from the plugin. The virtuals are defined in my plugin and then called from my actual application. like;

 ```
 let models = ['Deal', 'Business', 'UrlInfo', 'Comment', 'User'];

  return Promise.map(models, modelName => {
    let model = mongoose.model(modelName); // load context's model.

    // get model meta.
    let isModeratableFunc = _.head(model.schema.virtual('isModeratable').getters);
    let isAutoApprovedFunc = _.head(model.schema.virtual('isAutoApproved').getters);
    let isSelfDeletableFunc = _.head(model.schema.virtual('isSelfDeletable').getters);

    let meta = {
      isModeratable: isModeratableFunc ? isModeratableFunc() : false
    };
```

**Comment by varunjayaraman** [comment]
Ok i see now. I don't think what you're trying to do is possible (unless you use a hack like you did).

The better way to do it though is just write a function that's shared by your plugin and your app.

**Comment by bonesoul** [comment]
@varunjayaraman okay i still like the static method idea as i dont need an instance within my fuctions, i can just return the response.
