### ISSUE TITLE
Model.insertMany duplicate error

### ISSUE THREAD

**Issue by Yura13** [Automattic/mongoose#4978]
I am using Model.insertMany(docs, callback). In my application insertMany runs few times. This array may contains some docs which are already saved in the database. When insertMany will the second time running and more, i see duplicate error. Also I tried to use options from http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#insertMany but it couldn't help. How can skip the duplicate index error and continue inserting docs? How can insert docs which don't contained in collection of database?
```
Code:
FilmSession.insertMany(sessions, (err, docs) => {
       if (err) {
          console.log('Insert Error', err);
        } else {
          console.log('Successful Insert', docs);
        }
      });`
```
```
Error:
Unhandled rejection MongoError: E11000 duplicate key error collection: dbData.filmsessions index: cinema_1_isoDate_1_film_id_1 dup key: { : "title", : new Date(1486886400000), : ObjectId('58a064db68cdb614ecc0c118') }
    at Function.MongoError.create (C:\Projects\mean-app\node_modules\mongodb-core\lib\error.js:31:11)
    at toError (C:\Projects\mean-app\node_modules\mongodb\lib\utils.js:114:22)
    at C:\Projects\mean-app\node_modules\mongodb\lib\collection.js:658:23
    at handleCallback (C:\Projects\mean-app\node_modules\mongodb\lib\utils.js:95:56)
    at resultHandler (C:\Projects\mean-app\node_modules\mongodb\lib\bulk\ordered.js:421:14)
    at C:\Projects\mean-app\node_modules\mongodb-core\lib\connection\pool.js:455:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Node.js 6.9.5
MongoDB 3.4.1
Mongoose 4.8.1

**Comment by varunjayaraman** [comment]
@Yura13 are you trying to insert docs that already exist (the `_id` already exists on a document in the collection)?

**Comment by Yura13** [comment]
@varunjayaraman docs array is dynamically created, so it contains some indentical docs with collection, but _id is different

**Comment by varunjayaraman** [comment]
do you have any other unique indexes? The error seems to suggest you do...

**Comment by Yura13** [comment]
Also collection has additional index
```
db.filmsessions.createIndex({ cinema: 1,  isoDate: 1, film_id: 1 }, { unique: true })
```

1. Schema
```
const FilmSessionSchema = new Schema({
  cinema: {type: String},
  date: {
    _id: false,
    day: {type: Number},
    month: {type: Number},
    year: {type: Number}
  },
  time: {
    _id: false,
    hour: {type: Number},
    minute: {type: Number}
  },
  prices: {type: String},
  is3D: {type: Boolean},
  isoDate: {type: Date},
  film_id: {type: ObjectId, ref: 'Film'},
  timestamp: {type: Date, default: Date.now}
}, {
  versionKey: false
});
```

2. 
```
function sessionsByFilm(html, filmId) {
  let sessions = [],
    $ = cheerio.load(html),
    tmpDateSession = '';

  $('#weekSchedule tr').each((i, tr) => {
      if(i > 0) {
        let tmpSession = new FilmSession();

        tmpSession.film_id = mongoose.Types.ObjectId(filmId);
        tmpSession.cinema = 'Cinema';

        tmpDateSession = $(tr).children().eq(0).text();
        const now = new Date();
        tmpSession.date = {
          day:  parseInt(tmpDateSession.slice(tmpDateSession.indexOf('(') + 1, tmpDateSession.indexOf('.')), 10),
          month: parseInt(tmpDateSession.slice(tmpDateSession.indexOf('.') + 1, tmpDateSession.indexOf(')')), 10),
          year: month - 1 < now.getMonth() ? now.getFullYear() + 1 : now.getFullYear()
        };
        const sessionTime = $(tr).children().eq(1).text();
        tmpSession.time = {
          hour: parseInt(sessionTime.slice(0, sessionTime.indexOf(':')), 10),
          minute: parseInt(sessionTime.slice(sessionTime.indexOf(':') + 1, sessionTime.length), 10)
        };

        tmpSession.is3D = $(tr).children().eq(2).text() === '3D';
        tmpSession.prices = $(tr).children().eq(4).text();
        tmpSession.isoDate = moment({
          y: tmpSession.date.year,
          M: tmpSession.date.month - 1,
          d: tmpSession.date.day,
          h: tmpSession.time.hour,
          m: tmpSession.time.minute
        }).format();
        sessions.push(tmpSession);
      }
  });
  return sessions;
}
```

**Comment by varunjayaraman** [comment]
So you understand why you're getting a duplicate key error here right? Is the question why you're getting the duplicate key or how to ignore it?

**Comment by Yura13** [comment]
Do you mean this additional index in DB?
```
db.filmsessions.createIndex({ cinema: 1,  isoDate: 1, film_id: 1 }, { unique: true })
```

**Comment by varunjayaraman** [comment]
Yeah. If you're creating multiple unique indices and then trying to save duplicate entries to the db where the only difference is the `_id`, it's going to fail

**Comment by Yura13** [comment]
So, how i should save entities that aren't duplicate in db without this index?

**Comment by varunjayaraman** [comment]
I'm not sure I understand what you mean. If you specify a unique index, you shouldn't be saving documents that are nonunique for those fields.

**Comment by varunjayaraman** [comment]
I'm going to close this as stale soon. Do you still have an issue with this?

**Comment by Yura13** [comment]
I rewrote saving flow to DB and resolve this issue. Thanks!

**Comment by zackharley** [comment]
I believe that I've been having the same issue. The problem in my case is that my Schema has a secondary index field which is causing a duplicate key error. If I understand correctly, the issue here is that @Yura13 wanted to ignore any conflicting documents to ensure that only the new documents were inserted. 

After referencing http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#insertMany, I tried setting `{ ordered: false }` in an attempt to ignore the duplicate key errors, but to no avail. 

Based on the discussion in https://github.com/mongodb/mongo-php-library/issues/165, it looks like MongoDB will still generate an error for unique index conflicts, but if `{ ordered: false }` is supplied as an option, then documents will continue to be inserted. 

I was wondering if there is any way to stop these error messages from being thrown as I currently either have to deal with successful (but not complete) `insertMany` calls in a `Promise.prototype.catch` block or create my own set of promises for inserting these documents.

**Comment by vkarpov15** [comment]
@zackharley can you please open up a new issue with some code samples? I think I understand your issue but converting prose to code is error prone and I don't want to misunderstand your issue.
