### ISSUE TITLE
[buggy silence] Mongoose should throw Error if model created on dumb (without config opts) connection

### ISSUE THREAD

**Issue by nodkz** [Automattic/mongoose#4979]
In my app I'm switched from default connection to "manual" connections:
```js
// main db file which creates several connections
const db1 = mongoose.createConnection(uri, opts);

// in model file
const User = db1.model('User', UserSchema);
User.find(...);
```

But in one file I forgot to change default mongoose connection on "manual" connection:
```js
// main db file
// does not setup default connection any more 
// mongoose.connect(uri, opts);

// in model file
const Article = mongoose.model('Article', ArticleSchema);
```
And when try to make some request on Article, my app hang express requests (freeze them in pending status). How I understood it waiting when default connection will be initialized for proceeding operation. But connection will never be initialized.

**@vkarpov15 it will be cool if you somehow add checking if a connection is not initialized and user performs some query operation on model with such dumb connection. I suppose operation (find, count, update ...) should throw an error (cb(err) or reject if promise).**

PS. This case very hard to diagnose if using bunch of logic wrappers on top of mongoose. In my case `express` - `react-relay-network-layer:batchExpressMiddleware` - `graphql-express` - `graphql-compose` - `graphql-compose-mongoose` - `mongoose`.

PSS. For me, it's no error anymore, but further users may be blocked by this buggy silence.

**Comment by vkarpov15** [comment]
Yeah this is something we're planning on changing in 5.0. Buffering was really meant to minimize the number of callbacks necessary but that's much less of a problem now than it was in 2012. Not something we can really change right now without being backwards breaking though.

**Comment by vkarpov15** [comment]
I think we can close this one now that we have bufferTimeoutMS, which means that you'll at least get some error message after 10 seconds by default if you're using a model that is tied to a connection that you never called `connect()` on.
