### ISSUE TITLE
custom query function chained in before exec?

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#4980]
Hi there,

I've found information about custom query functions here: http://thecodebarbarian.com/mongoose-custom-query-methods.html

So is this possible then?

```
CommentSchema.query.loadContext = function () {
  console.log(this.contextId);
};
```

```
  list: function (options) {
    let criteria = options.criteria || {};
    let sortBy = options.sortBy || {};
    return this.find(criteria)
      .limit(options.perPage)
      .skip(options.perPage * options.page)
      .sort(sortBy)
      .populate('createdBy')
      .populate('deletedBy')
      .loadContext()
      .exec();
  }
```

but I can't get it working.

mongoose 4.8.2

**Comment by varunjayaraman** [comment]
@bonesoul you need to return `this`

**Comment by bonesoul** [comment]
@varunjayaraman okay i'll return it but as right now

` console.log(this.contextId);`

already exceptions as it doesnt hold current instance in this.

any ideas?

**Comment by vkarpov15** [comment]
@bonesoul can you please clarify what you mean, preferably with some code samples?
