### ISSUE TITLE
inherited models with distinct collections?

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#4981]
Basically i've read http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html and have a question.

Let's say that I've a commentableSchema defined as;

```
const commentableSchema = new Schema({ message: String },
  { discriminatorKey: 'kind' });

const Commentable = mongoose.model('Commentable', commentableSchema);
```

So let's say that I've two different models that both extend 'Commentable' like Product and BlogPost.

```
const BlogPost = Commentable .discriminator('BlogPost', new Schema({
  post: {
    title: String,
    required: true
  }
}));

const Product = Commentable .discriminator('Product', new Schema({
  product: {
    type: String,
    required: true
  }
}));
```

So it says in the page that ' are mongoose models that share the 'events' collection'.

So what I basically require is a way to store my products in 'products' collection and blogpost in 'blogposts' collection but still extending them from commentableSchema.

Is this even possible?

Sorry for lately asking a lot of questions as I've started digging deep within mongoose but hopefully I'll start paying back once I'm used to it's internals so I can start throwing back some bug-fixes and contributions :)

**Comment by vkarpov15** [comment]
Do *not* use discriminators for this purpose, by design discriminators use the same collection as the original model. There are numerous ways to achieve what you're trying to achieve with mongoose, [plugins](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) are probably the right approach for you
