### ISSUE TITLE
findOne() Method Returning All Records if passed value is empty

### ISSUE THREAD

**Issue by chaiwa-berian** [Automattic/mongoose#4984]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
Hello here, this piece of code returns all records if id is empty string! I am using mongoose:
```
Student.findOne({'_id':id}, function (err, result) {
      if (!result) {
        res.sendStatus(404);
      }

      return res.json(result);

    });
```
Isn't `findOne() ` supposed to return one item or default? I expect it to return `null` if `empty` string is passed ! Am I right?

**Comment by varunjayaraman** [comment]
It should throw an error if you pass in an empty string as the value for `_id`:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const chalk = require('chalk');
const assert = require('assert');

// Constants
const GITHUB_ISSUE = `gh-4984`;

exec()
  .then(() => {
    console.log(chalk.green(`Program ran successfully`));
    process.exit(1);
  })
  .catch(error => {
    console.log(chalk.red(`Error: ${ error }\n${ error.stack }`));
    process.exit(2);
  });

function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

    const schema = new mongoose.Schema({ name: String });
    const Model = db.model('Model', schema);
    const docs = yield createManyDocs(Model);

    const doc = yield Model.findOne({ _id: '' }); // this throws for me
    assert.ok(!Array.isArray(doc);
  });
}

function createManyDocs(Model) {
  return co(function*() {
    const docs = [];
    for(let i = 0; i < 10; i++) {
      docs.push(Model.create({ name: `doc-${ i }`}));
    }

    const createdDocs = yield docs;
    return createdDocs;
  });
}
```

**Comment by varunjayaraman** [comment]
Even if I use callbacks and I comment out my error handler, it logs `result` as undefined for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const chalk = require('chalk');
const assert = require('assert');

// Constants
const GITHUB_ISSUE = `gh-4984`;

exec()
  // .then(() => {
  //   console.log(chalk.green(`Program ran successfully`));
  //   process.exit(1);
  // })
  // .catch(error => {
  //   console.log(chalk.red(`Error: ${ error }\n${ error.stack }`));
  //   process.exit(2);
  // });

function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

    const schema = new mongoose.Schema({ name: String });
    const Model = db.model('Model', schema);
    const docs = yield createManyDocs(Model);

    Model.findOne({ _id: '' }, function(error, result) {
      // if (error) {
      //   console.log(chalk.red(`Error in callback ${ error }\n${ error.stack }`));
      // }

      console.log(result); // undefined
      process.exit(0);
    });
  }).catch(error => {
    console.log(chalk.red(error));
    process.exit(2);
  })
}

function createManyDocs(Model) {
  return co(function*() {
    const docs = [];
    for(let i = 0; i < 10; i++) {
      docs.push(Model.create({ name: `doc-${ i }`}));
    }

    const createdDocs = yield docs;
    return createdDocs;
  });
}
```

**Comment by chaiwa-berian** [comment]
@varunjayaraman Thanks, but can't it just return null if id is `''`? By the way, I figured out that I was hitting a wrong endpoint when `id` is empty hence returning all records. So it had nothing to do with `findOne()`, my bad!! But would you please clarify why it doesn't just return `null` if not found since its name suggests so?
Thanks!

**Comment by varunjayaraman** [comment]
@chaiwa-berian because mongoose casts a string `_id` to an ObjectId since `_id` has a special meaning in Mongo which allows for an O(log n) (binary) search. If the cast to an ObjectId fails, it'll throw an error. Making it return null would be a huge backwards breaking change and probably not ideal since you would want to know if the value being passed in is not being cast properly.

If you want, you can specify that `_id` will be a string or something and handle the property that way, or just make sure that you never pass in ' ' as the value for _id in a query.

**Comment by vkarpov15** [comment]
Not worth exploring IMO. Failing if the query fails to cast is much more consistent with the rest of the mongoose API (for example, how should we handle `findOneAndUpdate()` with `{ _id: '' }` and `{ upsert: true }`?), and I'd rather not make a one-off exception.

**Comment by chaiwa-berian** [comment]
@varunjayaraman and @vkarpov15 Very helpful notes, appreciated!
