### ISSUE TITLE
query.update() replacing current query._update contents

### ISSUE THREAD

**Issue by davidsapiro** [Automattic/mongoose#4994]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
update method on a query is **_replacing_** query _update - not adding (at least in pre-hooks - not checked elsewhere)
**If the current behavior is a bug, please provide the steps to reproduce.**

E.g. in pre-save hook

ProjectSchema.pre('update', function (next) {
    this.update( {$currentDate: {lastUpdated: true}});
    next();
});

results in this._update only containing   {$currentDate: {lastUpdated: true}}
**What is the expected behavior?**
Updates are added to the _update of the query - as in 4.8.2 and previously

**Please mention your node.js, mongoose and MongoDB version.**
Node: 4.9.5, mongoose 4.8.3, MongoDb: 3.2.11 (MMAPv1)

**Comment by stgogm** [comment]
Having the same issue here. v4.8.2 works correctly but 4.8.3 breaks updates.

**Comment by simllll** [comment]
same happening to me... critical bug!

**Comment by varunjayaraman** [comment]
yeah this should be fixed in the next release

**Comment by vkarpov15** [comment]
Fixed, please upgrade to 4.8.4. Sorry for the trouble!
