### ISSUE TITLE
could  you help to use mongoose in a small setup for the browser?

### ISSUE THREAD

**Issue by patrikx3** [Automattic/mongoose#4995]
just want to use validation for a schema, where to go?
is borwserify enough without webpack? we are using old system and grunt/bower, i am thinking i could add browserify to grunt?

do we need the whole lib? how can i just use the schema/validation?

**Comment by varunjayaraman** [comment]
browserify is indeed enough without webpack. But you can also use webpack or gulp/grunt. Bower is simply a package manager, so you won't be able to `require()` or `import()` mongoose unless you use the cdn script tag, which i think the most recent version is only v3.2, so you're probably going to need a bundler.

When you require mongoose in the browser, it detects if it's being required in that context and imports special parts of the library that are necessary for mongoose to work in the browser (like `browserDocument.

And you can import specific parts of the library in the browser, but most module bundlers just require in the whole lib and then export the specific exports from the mongoose library that you requested. If you're using a tree-shaking utility like webpack 2+ or rollup, I'm not too sure how that would play out with mongoose in the browser.

What I do is I define my schemas in a file and require them in the browser, and then you can create mongoose documents with them as `new mongoose.Document({}, theSchema)`. You can then do `doc.validateSync()` in the browser and see any errors, use any virtuals and methods, etc.
