### ISSUE TITLE
webpack fails 

### ISSUE THREAD

**Issue by foreggs** [Automattic/mongoose#4996]
**bug**

**What is the current behavior?**
When using webpack, mongoose fails. The error code: 

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js
```
const path = require("path");
const webpack = require("webpack");

module.exports = {
    context: path.resolve(__dirname, "./src"),
    target: "node",
    entry: {
        app: "./app.js"
    },
    resolve: {
        extensions: [".js"],
    },
    output: {
        path: path.resolve(__dirname, "./dist"),
        filename: "[name].bundle.js"
    }
}
```
src/app.js
```
import mongoose from "mongoose";
```
package.json
```
{
  "name": "server.1",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongodb": "^2.2.24",
    "mongoose": "^4.8.3",
    "webpack": "^2.2.1"
  }
}
```
Now, run `npm install`, `webpack` and then `node dist/app.bundle.js`.
The error i get: "Error: cannot find module ".""

**What is the expected behavior?**
NOT FAIL...

**Please mention your node.js, mongoose and MongoDB version.**
Node.js 7.5.0

**Comment by varunjayaraman** [comment]
Are you bundling your code for the browser or server-side code (i see you've specified `target: node` and you've included `.node` extensions: are you sure you mean to do that?).

**Comment by foreggs** [comment]
I didn't mean to include .node extensions. I tried different fixes and It seems like i forgot to remote that one. Code is executed with node, just like I said in the instructions (`node dist/app.bunde.js')

**Comment by varunjayaraman** [comment]
@foreggs my question was more are you trying to bundle this for the server or the browser?

**Comment by foreggs** [comment]
Node as I said. I wouldn't be stupid enough to try to run this in browser.

**Comment by varunjayaraman** [comment]
I guess my question is why are you trying to bundle server-side code with webpack? 

Also I don't get your error message. I only get:
```
WARNING in ../~/mongoose/lib/drivers/index.js
8:11-74 Critical dependency: the request of a dependency is an expression
```

Mongoose has some weird quirks where it attempts to use some native dependencies on the server, and avoids using them in the browser. There's a [mini hack](http://mongoosejs.com/docs/browser.html) to get it to work in the browser. But doing that on the server might have some weird results.

**Comment by varunjayaraman** [comment]
@foreggs any update on this? Can you try using the solution from the docs that I posted?

**Comment by varunjayaraman** [comment]
@foreggs I'm gonna close this as a stale issue unless you're still having issues. Feel free to comment if you're still having trouble.

**Comment by hugoduraes** [comment]
I'm having this issue too! I'm using mocha-webpack to run my unit tests and I get the same error as @foreggs! I can't reproduce the issue while running the app built with webpack, only when running the unit tests with mocha-webpack.
