### ISSUE TITLE
cursor lost last document

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#4998]
Hi,

I was using `.stream()` in some libraries and, in order to fix the :
`DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead`
I'm basically trying to replace `stream()` by `cursor()` and I'm facing a strange bug (which does not if I rollback to `stream()`), the last document in the database is just not receive.

    var mongoose = require('mongoose');
    global.Promise = mongoose.Promise = require('bluebird');

    var userSchema = new mongoose.Schema({
      name:  String
    });

    var User = mongoose.model('User', userSchema);

    mongoose.connect(
      'mongodb://127.0.0.1/test',
      {},
      function (err) {
        if (err) {
          return console.error(err);
        }

        User
          .remove({}) // clean db test
          .exec()
          .then(function () {
            var users = [];
            for (var i = 0; i < 100; i++) {
              users.push({
                _id: mongoose.Types.ObjectId(),
                name: 'Bob' + (i < 10 ? '0' : '') + i
              });
            }

            console.log('User count: ' + users.length);  // => 100
            return User.insertMany(users);
            /*
            // classic save do the same
            return Promise.all(users.map(function (user) {
              return new User(user).save();
            }));
            */
          })
          .then(function () {
            return new Promise(function (resolve) {

              var stream = User.find({}).cursor();
              var docs = [];

              stream.on('data', function (doc) {
                docs.push(doc);
              });

              stream.on('close', function () {
                var names = docs.map(function (doc) {
                  return doc.name;
                });
                names.sort();
                console.log(names);

                console.log('Doc count: ' + docs.length); // => return 99 instead of 100
                resolve();
              });

            });
          })
          .then(function () {
            mongoose.disconnect();
          });
      }
    );

In my case, the missing document is the "BOB37" which is in the database the last go by `db.users.find()`+ `it` * 4

Strangely, the bug seems to depends on the document count in database, there are some count which does not bugs: 2000, 2001 while 2002 bugs...

Tested on mongoose 4.5 and 4.8.3 with mongo db version v3.0.7

**Comment by varunjayaraman** [comment]
Hm, I thought this was fixed in mongoose 4.4.8 but i guess not. 

Also, @jbdemonte you said you're missing `Bob37`, are you sure you didn't mean `Bob99`, since that's the last document (and the one missing for me when I try your repro script)

**Comment by jbdemonte** [comment]
@varunjayaraman It depends on how mongo store the data, but in my case, the Bob37 is the last in DB order (when I use the CLI commands to see them), and it's the missing one so. (no idea why it's the last :D )
