### ISSUE TITLE
dynamic ref and find

### ISSUE THREAD

**Issue by dupenf** [Automattic/mongoose#5000]
node.jsV6.9,    mongooseV4.8.2
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug 
**What is the current behavior?**

I want to find dynamically using refPath.

**If the current behavior is a bug, please provide the steps to reproduce.**

modify the code of model.js in line 2764, as follow:
 function next(options, assignmentOpts, err, valsFromDb) {
    if (err) return callback(err);   
 vals = vals.concat(valsFromDb);
   ------ _assign(null, vals, options, assignmentOpts);
    if (--_remaining === 0) {
   ++++ _assign(null, vals, options, assignmentOpts);
      callback();
    }
  }

**What is the expected behavior?**
1. if your model with this schema:
         let a = new Schema({ items:[{t:String, e:[{type:ObjectId, refPath: 'items.t'}]}]});
   when query with find, you cannot get correct results.
2. raise efficiency.

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
I don't understand this bug report, please clarify

**Comment by varunjayaraman** [comment]
@dupenf i'm going to close this as stale unless you can clarify this bug report
