### ISSUE TITLE
Embedded discriminators: pushing a subdocument does not work

### ISSUE THREAD

**Issue by davebaol** [Automattic/mongoose#5001]
As @meammeiam reported in [issue 1856](https://github.com/Automattic/mongoose/issues/1856#issuecomment-280896808), if you try to push a new event it saves an empty item.

To reproduce this issue just add the code below to the code from the [blog post about embedded discriminators](http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators.html):
````javascript
Batch.create(batch).then(function(doc) {
    doc.events.push({ kind: 'Purchased', product: 24 });
    doc.save().then(function(doc) {
        console.log(doc);
    });
});
`````

Software versions:
* node.js 6.1.0
* mongodb 3.4.1
* mongoose 4.8.4

**Comment by davebaol** [comment]
@vkarpov15 
Thanks, your fix works like a charm. Great work! :bowtie:

**Comment by meammeiam** [comment]
@vkarpov15
Yes, It works great now! Thank you very much for your hard work! Mongoose is awesome!

@davebaol Thanks for filing the bug!
