### ISSUE TITLE
geoNear breaking change between 3.8 and 4.0?

### ISSUE THREAD

**Issue by bradleylandis** [Automattic/mongoose#5003]
geoNear is returning very different results when I upgrade from mongoose 3.8 to mongoose 4.0.  I don't see anything in the release notes about a breaking change in that area.

Node: v6.9.2
MongoDB: 3.4

**Comment by varunjayaraman** [comment]
Can you give an example of what you got with mongoose 3.8 and mongoose 4.0, and a repro script?

**Comment by bradleylandis** [comment]
I'm pretty sure it is related to https://github.com/Automattic/mongoose/issues/1987.  But I didn't see any mention of it in the release notes.  as for recreating it.  I used the code from https://github.com/simonholmes/getting-MEAN/tree/chapter-11.  I added the following script to a scripts folder in the project to illustrate the change:

"use strict";

let db = require('./../app_api/models/db');
let mongoose = require('mongoose');
let Loc = mongoose.model('Location');

Loc.remove({}, function (err, data) {
    if (err) {
        console.log(err);
    }
    else {
        console.log('deleted');

        Loc.create({name: "Test Location", coords:[-0.1276251, 51.5033640]}, function(err, location){
            if(err){
                console.log(err);
            }
            else{
                console.log('created');
                let point = {
                    type: "Point",
                    coordinates: [-0.1276251, 51.5033641]
                };
                let geoOptions = {
                    spherical: true,
                    num: 10
                };
                Loc.geoNear(point, geoOptions, function(err, results, stats) {
                    console.log('distance: ' + results[0].dis);
                });
            }
        });
    }
});

Result with mongoose 3.8.0:
deleted
created
distance: 1.7453292699914073e-9

Result with mongoose 4.8.5:
deleted
created
distance: 0.011131884616932194

**Comment by vkarpov15** [comment]
Yep #1987 is exactly the change. TLDR; in mongoose 4.x, if you send a geoJSON point to `geoNear()` then mongodb uses meters, and if you use legacy coordinate pairs `[lng, lat]` mongodb uses radians. In mongoose 3.x we converted geoJSON points to legacy coordinate pairs, hence the difference. Check the [mongodb geoNear docs](https://docs.mongodb.com/manual/reference/command/geoNear/) for more detail.
