### ISSUE TITLE
Mongoose not creating indexes on replica set

### ISSUE THREAD

**Issue by gordysc** [Automattic/mongoose#5004]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If we point at a single instance of MongoDB, the indexes for our schema are created when starting up our NodeJS server.  If we point at a replica set they appear to not be created.  Is there a special configuration option/known issue for this?

**If the current behavior is a bug, please provide the steps to reproduce.**
Just point at a replica set vs a single instance of Mongo

**What is the expected behavior?**
The indexes are created.

**Please mention your node.js, mongoose and MongoDB version.**
Node 6.9.5
Mongoose 4.8.4
MongoDB 3.4.2

**Comment by gordysc** [comment]
So, apparently when Mongo fails to create an index, it doesn't show the error by default.  We have to explicitly listen on the model for an event "index" to see if it succeeded.  I'm curious, what was the thought behind this approach? I imagine we can't be the only ones who were curious why our indexes were failing to be created.

As for the actual issue, we were overriding _id and setting "index:true".  However, this causes Mongo to pass { background: true } when creating the _id index, which is invalid for this particular case.  This caused the index creation to fail.  I'd like to propose a check to see if the user is doing this edge case and provide a warning to help correct the issue.  I'd be up for submitting a PR for this if the maintainers of this repository agree.  Thoughts?

**Comment by vkarpov15** [comment]
@gordysc set the [emitIndexErrors option](http://mongoosejs.com/docs/guide.html#emitIndexErrors) to change this behavior. The behavior you're referencing in this bug is [deprecated](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings), in the next release mongoose will always throw an error if an index build fails and there are no listeners.
