### ISSUE TITLE
missing promise on connection with invalid mongo uri

### ISSUE THREAD

**Issue by noerw** [Automattic/mongoose#5006]
when an error is thrown by `muri()` AND a callback is provided, no promise will be returned ([connection.js#225](https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L225)).

see this test case:
```js
mongoose.connect('asdf://asdf', err => {
  console.log('err', err);
}).then(asdf => {
  console.log('then', asdf);
}).catch(err => {
  console.log('catch', err);
});
```

**Comment by varunjayaraman** [comment]
Not really sure how to handle this one. A lot of node libs assume that if you pass a callback, you don't want to use promises

**Comment by noerw** [comment]
if I understand the code correctly, for all other error cases an error is thrown as well as a rejected promise returned..

**Comment by varunjayaraman** [comment]
@noerw so in this case, `Model.create()` will throw an error because the name field is required but undefined in the doc that is being created. The error handler in the `catch` handler will never run:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5006`;

const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

const schema = new mongoose.Schema({
  name: { type: String, required: true },
  age: Number
});

const Model = db.model('Model', schema);

Model
  .create({ age: 5 }, (error, doc) => {
    if (error) {
      console.error(`Error: ${ error }\n${ error.stack }`);
      return error;
    }
  })
  .then(doc => {
    console.log('doc', doc);
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error in catch handler: ${ error }\n${ error.stack }`);
    process.exit(2);
  })
```

**Comment by noerw** [comment]
I agree that this is unusual usage, but we do it to retry a connection attempt if it fails via a recursive callback, and continue with the promise on success: [sensebox/opensensemap-api:lib/utils.js](https://github.com/sensebox/openSenseMap-API/blob/master/lib/utils.js#L57-L69).

The reason I opened this issue is just, that this behaviour is inconsistent with the other error handling in `connection.js`, as all other cases return on both the callback and the promise.

Feel free to close this, if the use case is too specific. Maybe mention in the docs, that callback / promise usage is mutually exclusive

**Comment by varunjayaraman** [comment]
Sure I can open it up to discussion as a new feature, although I'd say you could also recursively handle the retry attempts through promises

**Comment by vkarpov15** [comment]
Right now mongoose returns a promise regardless of whether you provide a callback or not, so it should do so in all cases.
