### ISSUE TITLE
toObject does not create immutable objects?

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#5008]
I'm migrating our codebase from lodash 3 to 4 and since (_.clone) doesn't seem to work anymore for Mongoose objects and was anyway discouraged I started to use `mongooseObject.toObject()` in place of it.

My impression was that `.toObject()` would create new objects based on the current document data  and no link to the original object like a clone, but instead it seems like changes to original mongoose objects get propagated to the ones created by `toObject()`.

Not sure if my assumption that toObject would clone is wrong or if it's a bug but anyway I thought it would be useful to report it.

<img width="533" alt="schermata 2017-02-22 alle 18 53 35" src="https://cloud.githubusercontent.com/assets/589911/23224878/3eab9a14-f930-11e6-8ab7-4c13f78b68ee.png">
<img width="841" alt="schermata 2017-02-22 alle 18 53 24" src="https://cloud.githubusercontent.com/assets/589911/23224877/3ea999da-f930-11e6-8d55-21321e5555ec.png">

notice how the change to progress.down is applied to the cloned object too

**Comment by varunjayaraman** [comment]
@paglias yeah definitely do not use `_.clone` on mongoose objects. Remember that mongoose docs have a bunch of getters and setters, so your results could be wonky.

can you post a more full repro script and I can take a look? For me, it doesn't mutate the doc (which it shouldn't):

```javascript
const mongoose = require('mongoose');
const assert = require('assert');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5008`;

try {
  exec()
  process.exit(0);
} catch (error) {
  console.error(`Error: ${error}\n${error.stack}`);
  process.exit(2);
}


function exec() {
  const db = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
  const schema = new mongoose.Schema({
    name: String,
    age: Number
  });

  const Model = db.model('Model', schema);

  const doc = new Model({
    name: 'Bob',
    age: 32
  });

  assert.equal(doc.age, 32);

  const leanDoc = doc.toObject();
  assert.equal(leanDoc.age, 32);

  doc.age = 55;
  assert.equal(doc.age, 55);
  assert.equal(leanDoc.age, 32);

}

```

**Comment by paglias** [comment]
@varunjayaraman sorry I didn't include a reproduction initially, i've been able to reproduce it with

```
const mongoose = require('mongoose');
const assert = require('assert');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5008`;

try {
  exec()
  process.exit(0);
} catch (error) {
  console.error(`Error: ${error}\n${error.stack}`);
  process.exit(2);
}


function exec() {
  const db = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
  const schema = new mongoose.Schema({
    name: String,
    age: Number,
    sub: {
      heigth: Number,
    },
  });

  const Model = db.model('Model', schema);

  const doc = new Model({
    name: 'Bob',
    age: 32,
    sub: {
      heigth: 3,
    },
  });

  assert.equal(doc.sub.heigth, 3);

  const leanDoc = doc.sub.toObject();
  assert.equal(leanDoc.heigth, 3);

  doc.sub.heigth = 55;
  assert.equal(doc.sub.heigth, 55);
  assert.equal(leanDoc.heigth, 3);
}
```

It seems to happen when toObject is called on a sub document only.

**Comment by varunjayaraman** [comment]
@paglias whoa, nice catch. Thanks for this, looks like a bug.
