### ISSUE TITLE
$lookup not working help me when this add in mongoos?

### ISSUE THREAD

**Issue by kysemon** [Automattic/mongoose#5016]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by varunjayaraman** [comment]
@kysemon this is pretty impossible to debug unless you answer the questions in the issue template...or at least provide something besides a title.
