### ISSUE TITLE
transform in toObject being executed when called with options

### ISSUE THREAD

**Issue by exprodrigues** [Automattic/mongoose#5023]
According to the documentation: 

> Note: if you call toObject and pass any options, the transform declared in your schema options will not be applied. To force its application pass `transform: true`
http://mongoosejs.com/docs/api.html#document_Document-toObject

Steps to reproduce the problem
https://gist.github.com/exprodrigues/ee73ca2feb9099a3953626b561b5fb84

`doc.toObject({ hide: '_id old' });` has a different result than expected

**Expected**
```
doc.toObject(); // { name: 'John Doe', email: 'john@doe.com', old: 31 }
doc.toObject({ hide: '_id old' }); // { _id: 'john', name: 'John Doe', email: 'john@doe.com', old: 31 }
doc.toObject({ hide: '_id old', transform: true }); // { name: 'John Doe', email: 'john@doe.com' }
```

**Result**
```
doc.toObject(); // { name: 'John Doe', email: 'john@doe.com', old: 31 }
doc.toObject({ hide: '_id old' }); // { name: 'John Doe', email: 'john@doe.com' }
doc.toObject({ hide: '_id old', transform: true }); // { name: 'John Doe', email: 'john@doe.com' }
```

Nodejs: v6.9.4
MongoDB: v3.4.1
mongoose: 4.8.5

**Comment by varunjayaraman** [comment]
Yeah, looks like it's applying the changes in the 2nd case when you don't pass `transform: true`

**Comment by vkarpov15** [comment]
Unfortunately this is a bug in the docs. We've had tests in place for this behavior for years, see #2245 for the discussion.
