### ISSUE TITLE
Is there any efficient way to implement remove an item in an array that is in an array?

### ISSUE THREAD

**Issue by Sean-Wang** [Automattic/mongoose#5025]
**Do you want to request a *feature* or report a *bug*?**

Document is:

![image](https://cloud.githubusercontent.com/assets/1193073/23355381/628f9aaa-fd10-11e6-8b55-89b7c4d50b1e.png)

I want to remove `"57da54b205905d019a8c80ac"` from `"byTarget"` array that is in `"sharer"` array.

**What is the current behavior?**

My current code is:

```javascript
Model.findOne ({
    producer: "57d83d9fea8f50797d3b916e"
}).exec (function (err, result) {
    var idx = 0;
    underscore.each (result.sharer, function (item, index) {
        underscore.each (item.byTarget, function (deepItem) {
            if (deepItem.toString() === "57da54b205905d019a8c80ac") {
                idx = index;
            }
        });
    });

    var object = {};
    var b = 'sharer.' + idx + '.byTarget';
    object[b] = "57da54b205905d019a8c80ac";

    Model.findOneAndUpdate ({
        producer: "57d83d9fea8f50797d3b916e"
    }, {
        $pull: object
    }, function (err) {
        if (err) {
            callback (err);
        } else {
            callback (undefined, returnMsg.SuccessStatus);
        }
    });
});
```

It works.

but, is there any efficient way to implement it?

**Please mention your node.js, mongoose and MongoDB version.**

node.js: 6.9.4
mongoose: 4.8.5
MongoDB: 3.4.2

**Comment by vkarpov15** [comment]
No real way to make it more efficient in the sense of using indexes, either you have to loop over the nested arrays or mongodb has to loop over the nested arrays. In general nested arrays are pretty tough to work with in mongodb, I'd try to structure my data to avoid that if possible.

**Comment by Sean-Wang** [comment]
Thanks.
