### ISSUE TITLE
populate() returns the document, but depopulate() doesn't

### ISSUE THREAD

**Issue by javorosas** [Automattic/mongoose#5027]
This is an observation on consistency. Noted by use and confirmed by [documentarion](http://mongoosejs.com/docs/api.html#document_Document-depopulate)

#### Current behavior

The `populate()` method of a document evaluates to the `this` of the same document, returning the document in question; while it's counterpart `depopulate()` does not have any return value.

#### Expected

It would be more consistent to make `depopulate()` also return the `this` reference.

#### Why?

I wanted to achieve the following

```javascript
function createBook(title, owner) {
  return Book.create({ title: 'LOTR', owner: owner  })  // Book is created, but returned with 'owner' populated
    .then(book => book.depopulate('owner'))             // I want to be able to return just the created document
    .then(book => console.log(typeof book))             // undefined
}
```

**Comment by vkarpov15** [comment]
Good idea, will do.
