### ISSUE TITLE
Mongoose blows up when $push-ing undefined 

### ISSUE THREAD

**Issue by idibidiart** [Automattic/mongoose#5029]
To repro:

npm install feathers feathers-errors feathers-rest body-parser mongoose feathers-mongoose

Then create and app.js like the one provided here:

https://github.com/feathersjs/feathers-mongoose/issues/167

run: node app.js

result:
Mongoose blows up when trying to $push 'undefined'

**Comment by vkarpov15** [comment]
A more minimal repro would be much appreciated. Can you also tell me what error you get?

**Comment by varunjayaraman** [comment]
@idibidiart do you have more info or a better repro script? I'm going to mark this as stale and will close soon if not
