### ISSUE TITLE
BUG: mongoose.connect, poolSize is defaulting to 1 and will not go above

### ISSUE THREAD

**Issue by kdr1** [Automattic/mongoose#5031]
NodeJs v6.9.4
Mongoose v4.8.5
MongoDB v3.2.9

The following code only opens 1 connection.

    const express = require('express');
    const mongoose = require('mongoose');

    const app = express();

    let database_uri = 'mongodb://localhost:27017/some_database';

    let options = {
        server: {
            poolSize: 5
        }
    }

    mongoose.connect(database_uri, options, function(err) {
	    if (err) console.log(err);
	    app.listen(8080);
    });

I would expect this to produce 5 connections. It produces 1. The default is listed as 5. Changing server.poolSize has no affect on the number of connections opened when I run this script.

**Comment by kdr1** [comment]
Did a little more testing. The options object inside the driver is getting updated with the supplied value. The thing that is confusing me is that the open connections in the shell is being reported as 2. One for the shell, one of the app. With the shell and the app with a connection pool of 5, shouldn't there be 6 open connections?

**Comment by vkarpov15** [comment]
More recent versions of the [mongodb driver grow/shrink the connection pool based on usage](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#220-2016-07-05) so the provided `poolSize` is now treated as the maximum number of connections rather than the actual number of connections.
