### ISSUE TITLE
Ran out of retries trying to reconnect

### ISSUE THREAD

**Issue by kaasdude** [Automattic/mongoose#5034]
**Before creating an issue please make sure you are using the latest version of mongoose**

Mongoose version: `4.8.5`

**Do you want to request a *feature* or report a *bug*?**

I need to file a bug

**What is the current behavior?**

Running a Docker container: `docker run -p 27017:27017 mongo:3.2.11`

Connecting successfully to a mongo instance with the following options:

```
server: {
            // auto_reconnect: true, // Default true
            reconnectTries: Number.MAX_VALUE,
            reconnectInterval: 1000, // reconnect after 1 second(s)
        }
```

Then I stop the mongo server for like a minute, and noticed the following `Unhandled error event`:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
DisconnectedError: Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
.....
```

**If the current behavior is a bug, please provide the steps to reproduce.**
*If you can, provide a stadalone script / gist to reproduce your issue*

```
const mongoose = require('mongoose');

const options =  {
                server: {
                    reconnectTries: Number.MAX_VALUE,
                    reconnectInterval: 1000, // reconnect after 1 second(s)
                }
            };
            mongoose.Promise = global.Promise;
            mongoose.connect('mongodb://localhost:27017/thedb', options, (err) => {
                if (err) {
                    return callback(err);
                }
                callback();
            });
```

**What is the expected behavior?**

What I would expect is, when mongo db is stopped, for example manually `CTRL+C`, mongoose(mongo) should retry connecting for almost indefinitely (`Number.MAX_VALUE`) without trowing an  error.

*Use Case:*
* E.g: Deployed a node REST api to Heroku + MongoDB addon
* App bootstraps, connects to db first, continues bootstrapping, and is up and running
* MongoDB decides to crap out, or the network connection dips for a minute (allthethings).
* Node process crashes and eventually doesn't start anymore (API is not able to respond with generated REST error)

**Please mention your node.js, mongoose and MongoDB version.**

* Node: 6.9.5
* MongoDB: 3.2.11
* Mongoose: 4.8.5

**Comment by varunjayaraman** [comment]
So this only happens when you try to perform db operations after mongodb shuts down right?

**Comment by kaasdude** [comment]
Seems the event.js (nodejs) throws this error:
[Screenshot](https://drive.google.com/open?id=0BxA-4OkwHbvGRUp4V055NERVVkk)

When I got a moment I will try to create a example.

**Comment by varunjayaraman** [comment]
@kaasdude any luck on creating a repro example?

**Comment by varunjayaraman** [comment]
@kaasdude im going to close this as stale soon unless you have more info / a repro example?

**Comment by kaasdude** [comment]
Hi @varunjayaraman ,

I made a small test, and I need to apologise for this "non-issue".
See: https://github.com/kaasdude/mongoose-disconnect-test

I made a small isolated test, to see what mongoose is doing when I quit docker.
It starts a dummy http server, initializes a mongoose connection, and starts to dump data in.

You are most welcome to close this one.
( We surely need to investigate our own issue, interfering event listeners or something :-S )

Regards,
I.

**Comment by sebbarg** [comment]
Hey guys,

I can provoke the same scenario with the below express-route. 

Killing the mongo server before hitting the foo-route will crash the node server and not execute the catch-block. Top of the call-stack is node_modules/mongoose/lib/error/disconnected.js:21:11

Even if it is an unlikely scenario, I guess we should be able to handle the error gracefully?

```javascript
router.get('/foo', async function (req, res) {
  let user = new User();
  try {
    await user.save();
    res.redirect('/bar'); 
  } catch (err) {
    console.log('Oh dear...');
  }
});

```
Best,
Sebastian

**Comment by varunjayaraman** [comment]
@sebbarg sorry for the late response, just saw this. I will try to reproduce with your script soon and get back to you

**Comment by rafaelgrilli92** [comment]
Any news about this? I'm facing the same "problem". I'm trying to handle all kind of errors that could happen, but this one isn't possible to handle properly.

**Comment by asadighi** [comment]
I have the same issue but in my case I just simply want to have a callback to handle the error gently. This is currently crashing my app.
