### ISSUE TITLE
Trying to use $inc in mongoose with update

### ISSUE THREAD

**Issue by webdev48** [Automattic/mongoose#5035]
Mongoose: 4.8.1
Mongo: 3.4
Node: 4.4.7

Is this a **bug**

I have tried almost everything and searched on internet for 4 hours. Couldn't get $inc to work with `update()`

```
var updateCommand = {};
        updateCommand['$inc'] = {};
        updateCommand['$inc']['story.hide'] = 1;
        console.log('hideStory : story service : ',updateCommand);

        Story.update(query,updateCommand,callback);
```

i also tried
```
        Story.update(query,{$inc:{'story.hide':1}},callback);
```

above were for nested/embedded field, but even for simple field `test` it doesn't work
```
        Story.update(query,{$inc:{'test':1}},callback);
```

Am i doing anything wrong or this doesn't work in mongoose?

**Comment by varunjayaraman** [comment]
I'm guessing you're logging the doc as the 2nd parameter in the `callback` to `Model.update()`? If so, remember that the 2nd parameter to the callback for `Model.update()` is the raw response from mongodb, NOT the document: http://mongoosejs.com/docs/api.html#model_Model.update

Anyway, this works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');

const GITHUB_ISSUE = `gh-5035`;

exec()
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
    process.exit(2);
  });

function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

    const schema = new mongoose.Schema({
      age: Number
    });

    const Model = db.model('Model', schema);

    const doc = yield Model.create({ age: 5 });

    Model.update({ _id: doc._id }, { $inc: { age: 1 } }, function(error, rawResponse) {
      if (error) {
        console.error(error);
        process.exit(2);
      }

     Model.findOne({ _id: doc._id }, function(error, doc) {
       if (error) {
         console.error(error);
         process.exit(2);
       }
       console.log(doc.age)
     })
    });

  });
}
```

**Comment by varunjayaraman** [comment]
@webdev48 I'm going to close this as stale. If you still have issues with my script above, feel free to comment and I'll reopen

**Comment by aliasgherbadshah** [comment]
it does not work...........................................................
LOL
