### ISSUE TITLE
Pls generify Query.prototype.populate

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5036]
Feature request/bug - the populate method (Query.prototype.populate) cannot handle an empty arguments list.

Here's my code, I believe I am using `populate()` correctly:

```js
router.get('/', function (req, res, next) {

  const q = req.parsedQueryParams;
  const populate = req.parsedPopulateParams;

 // this is what req.parsedPopulateParams looks like:
  // const populate = ['userId','promptId'];  

 // *but* sometimes it could be empty => populate = []; !!!!

  Assignment.find(q)
    .populate(...populate)   
    .lean()
    .exec()
    .then(function (assignments) {
      res.jsonp({
        success: assignments
      });
    }, next);

});
```

the populate() method, calls this routine in Mongoose:

```js
Query.prototype.populate = function() {

  console.log('Query.populate => ', arguments);

  var res = utils.populate.apply(null, arguments);
  var opts = this._mongooseOptions;

  if (!utils.isObject(opts.populate)) {
    opts.populate = {};
  }

  var pop = opts.populate;

  for (var i = 0; i < res.length; ++i) {
    var path = res[i].path;
    if (pop[path] && pop[path].populate && res[i].populate) {
      res[i].populate = pop[path].populate.concat(res[i].populate);
    }
    pop[res[i].path] = res[i];
  }

  return this;
};

```

When I run my code, passing an empty arguments list to populate() I get this:

```
 TypeError: utils.populate: invalid path. Expected string. Got typeof `undefined`
    at populate (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/utils.js:626:11)
    at Query.populate (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/mongoose/lib/query.js:2949:28)
```

utils.populate looks like this:

```js
exports.populate = function populate(path, select, model, match, options, subPopulate) {
  // The order of select/conditions args is opposite Model.find but
  // necessary to keep backward compatibility (select could be
  // an array, string, or object literal).

  // might have passed an object specifying all arguments
  if (arguments.length === 1) {
    if (path instanceof PopulateOptions) {
      return [path];
    }

    if (Array.isArray(path)) {
      return path.map(function(o) {
        return exports.populate(o)[0];
      });
    }

    if (exports.isObject(path)) {
      match = path.match;
      options = path.options;
      select = path.select;
      model = path.model;
      subPopulate = path.populate;
      path = path.path;
    }
  } else if (typeof model !== 'string' && typeof model !== 'function') {
    options = match;
    match = model;
    model = undefined;
  }

  if (typeof path !== 'string') {
    throw new TypeError('utils.populate: invalid path. Expected string. Got typeof `' + typeof path + '`');
  }

  if (typeof subPopulate === 'object') {
    subPopulate = exports.populate(subPopulate);
  }

  var ret = [];
  var paths = path.split(' ');
  options = exports.clone(options, { retainKeyOrder: true });
  for (var i = 0; i < paths.length; ++i) {
    ret.push(new PopulateOptions(paths[i], select, match, options, model, subPopulate));
  }

  return ret;
};

```

Can you please update these functions/methods to handle empty arguments?

If no arguments are passed, then it should be a no-op.

thanks!

**Comment by ORESoftware** [comment]
In other words, to get around this, I can do this:

```js
router.get('/', function (req, res, next) {

  const query = req.parsedQueryParams;
  const populate = req.parsedPopulateParams;

  // const populate = ['userId','promptId'];

  let q = Assignment.find(query);

  if (populate.length) {
    q = q.populate(...populate);
  }
  
  q.lean()
    .exec()
    .then(function (assignments) {
      res.jsonp({
        success: assignments
      });
    }, next);

});
```

but I think you would agree it would be a lot nicer to not have to check.

Also - I don't think Mongoose is doing a good job of validating that the list items in the populate arguments actually match fields in models...? I can pass anything to populate() as long as they are strings, and I don't see Mongoose throwing any errors, is there a good reason for that?

**Comment by ORESoftware** [comment]
bumpity bump bump bumperoo

**Comment by varunjayaraman** [comment]
Open to discussion. @vkarpov15 what do you think?

**Comment by ORESoftware** [comment]
thanks for being open to this, don't forget:

> Also - I don't think Mongoose is doing a good job of validating that the list items in the populate arguments actually match fields in models...? I can pass anything to populate() as long as they are strings, and I don't see Mongoose throwing any errors, is there a good reason for that?

**Comment by vkarpov15** [comment]
Good suggestion, will add this for the next patch release, thanks @ORESoftware

**Comment by ORESoftware** [comment]
thank you, like I said it would also be nice to validate that the items in the populate array match fields that are actually on the schema (although schemas do change over time, so maybe that's not a good idea - you would know more about that).

**Comment by vkarpov15** [comment]
@ORESoftware can you clarify what you mean by that? I'm not sure I understand

**Comment by ORESoftware** [comment]
np, if a schema for a model called X which looks like this:


```js
{

foo: Schema.Types.ObjectId,
bar: Schema.Types.ObjectId,
baz: Schema.Types.ObjectId

}
```


I could call

```js
X.find({}, {populate:['zzzzz','xxx']).exec().then()
```

The problem I was alluding to is that the arguments to populate are not validated - I can passing anything in the populate and Mongoose does not seem to even log a warning.

Basically 'zzzzz' and 'xxx' don't need to match any of foo, bar, or baz.

**Comment by vkarpov15** [comment]
@ORESoftware opened up an issue :point_up:  to track
