### ISSUE TITLE
[Feature]Is it the time to remove co?

### ISSUE THREAD

**Issue by libook** [Automattic/mongoose#5043]
Async\await feature is released now in the latest version of node.js.
So, is it the time to remove co from dependencies?
I'm just curious about it.

**Comment by varunjayaraman** [comment]
I'd say probably not. Async/await is a feature from node 7 but mongoose needs to be compatible for previous versions of node. Without a transpiler to run the tests, I would argue that it's more trouble than its worth to have separate node 7 tests using async/await.

**Comment by firrae** [comment]
Co offers a great backwards compatibility to Node versions previous to 7. Once we can say 7 (or 8) is where the community is mainly then I'd say it's time to go to native async/await, but I know there are still a ton of people and project using Node 4 and even Node 0.10.X and changing away from Co might break their projects or, at least, block them from new features until they upgraded which isn't always an easy option.

**Comment by libook** [comment]
OK. Thank you all.

**Comment by vkarpov15** [comment]
Co is a dev dependency for us, we really only use it for testing
