### ISSUE TITLE
save not working inside callback from "request"

### ISSUE THREAD

**Issue by gustavomanolo** [Automattic/mongoose#5044]
I'm currently using the "request" module to get data from an external page:
if i use the following code, it doesn't work:

`request(SITE_URL, function (error, response, body) {
    var user = new gasStation({ id: 12345, name: 'Gustavo' });
    user.save();
});`

But if i make the call outside the request function it works as expected:

`var user = new gasStation({ id: 12345, name: 'Gustavo' });
    user.save();
request(SITE_URL, function (error, response, body) {
});
`

Why is this happening?

**Comment by varunjayaraman** [comment]
@gustavomanolo how do you know it doesn't work. What happens if you pass in a callback to the save operation and log the document that was created?

**Comment by gustavomanolo** [comment]
Was mas my mistake, there was something wrong with the code.
Thanks a lot.
