### ISSUE TITLE
MongoError: Cannot update 'createdAt' and 'createdAt' at the same time

### ISSUE THREAD

**Issue by wprl** [Automattic/mongoose#5045]
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**

Doing an upsert on a model using `setDefaultsOnInsert`, when the model uses `{ timestamps: true }`, and when the update document has `createdAt` set, the query results in this error: 

MongoError: Cannot update 'createdAt' and 'createdAt' at the same time
4|app | at Function.MongoError.create (/home/ubuntu/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
4|app | at /home/ubuntu/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:483:72
4|app | at authenticateStragglers (/home/ubuntu/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:429:16)
4|app | at Connection.messageHandler (/home/ubuntu/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:463:5)
4|app | at Socket.<anonymous> (/home/ubuntu/myproject/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:319:22)

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const schema = new mongoose.Schema({ username: String }, { timestamps: true });
const User = mongoose.model('User', schema);

User.findOneAndUpdate({
  username: 'xyz', 
  isDeleted: false
}, { createdAt: '2017-03-06T14:08:59+00:00' }, {
  new: true,
  setDefaultsOnInsert: true,
  upsert: true
}, (error) => { if (error) throw error });
```

**What is the expected behavior?**

I would expect it to use the `createdAt` value I pass in rather than causing an error.

**Please mention your node.js, mongoose and MongoDB version.**

Node v6.9.5
Mongoose 4.6.6
MongoDB 3.4.2

**Comment by varunjayaraman** [comment]
Yeah i guess this shouldn't happen. On the other hand, why manually update the createdAt property? The timestamps will still get set on a `findOneAndUpdate` op.

**Comment by wprl** [comment]
My use case is that sometimes a "user" is created by our system, in which case `timestamps` works as expected. However sometimes the "user" is created by copying data, including `createdAt`, from a call to an external API. I say "user" but really the model is not a user.

**Comment by MidnightP** [comment]
"MongoError: Cannot update 'createdAt' and 'createdAt' at the same time"

Node v7.6.0
Mongoose 4.9.0
Mongo 3.4

I'm using Mongoose 4.9.0 !

I need this for a migration of documents using `findOneAndUpdate` with data retrieved from documents that can already have `createdAt`. 

**What is the expected behavior?**

wprl: "I would expect it to use the createdAt value I pass in rather than causing an error."

**Comment by wprl** [comment]
Thank you @vkarpov15 !

**Comment by johnculviner** [comment]
ditto thank you very much. This isn't frequent that I "googled the error message" and find it was fixed for my exact situation 1 day ago. <3 opensource

**Comment by dylanjha** [comment]
@johnculviner what was the fix that worked for you?

**Comment by johnculviner** [comment]
@dylanjha for my situation I actually found it wasn't working as intended. I wanted to explicitly set createdAt and updatedAt in certain situations and was encountering this message. I ended up breaking them out into the schema explicitly since I needed to 'manage it myself' in certain situations
