### ISSUE TITLE
Mongoose Typescript not recognizing anything attached to 'this'

### ISSUE THREAD

**Issue by digital216** [Automattic/mongoose#5046]
I think this is a bug, but I may be doing something stupid too...

This is my schema:

    import express = require('express');
    import mongoose = require('mongoose');
    import security = require('crypto');

    export interface IUser extends mongoose.Document {
	    username: string;
	    password: string;

	    characters: mongoose.Types.ObjectId[];

	    authenticate: Function;
    }

    const Schema = new mongoose.Schema({
	    username: { required: true, trim: true,  type: String },
	    password: { required: true, trim: true, type: String },
	    salt: String,
	    characters: [{ type: mongoose.Schema.Types.ObjectId }]
    });

    Schema.methods.hashPassword = (password: string) => {
	    return security.pbkdf2Sync(password, this.salt, 10000, 64, 'SHA512').toString('base64');
    };

    Schema.methods.authenticate = (password: string) => {
	    return this.password === this.hashPassword(password);
    };

    Schema.pre('save', (next: express.NextFunction) => {
	     if (this.password) {
		    this.salt = new Buffer(security.randomBytes(16).toString('base64'), 'base64');
		    this.password = this.hashPassword(this.password);
	    }

	    next();
    });

    export let User = mongoose.model<IUser>('User', Schema);

And I am using it in this controller:

    export let register = (request: express.Request, response: express.Response, next: express.NextFunction) => {
	    const newUser = new User(request.body);

	    newUser.save()
		    .then(() => { response.sendStatus(200); })
		    .catch((error: MongoError) => { return next(error) });
    };

When I hit the controller with data, anything inside the schema methods doesn't see any properties of the schema.  As in, in the `pre('save')`, `this.password` is always undefined, even if I can see it's present in the `newUser` in the controller.  Have I been away from this basic part of the process long enough to have forgot what I'm doing, or is something wonky?

I would expect that inside any Schema method, I would have access to the schema properties.

- Node v7.7.1
- NPM v4.4.1
- Mongoose v4.8.6
- Mongoose @Types v4.7.7
- MongoDB v3.4.2

**Comment by varunjayaraman** [comment]
So this has nothing to do with Typescript. The problem is that you are using `fat arrow` syntax to define mongoose methods and hooks. **Don't do that**. If you use a fat arrow function to define a method, it has no lexical scope and cannot be bound to a given context.

This example will work:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5046`;

const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

const schema = new mongoose.Schema({
  username: { required: true, trim: true, type: String },
});

schema.pre('save', function(next) {
  console.log(`Using this: ${ this.username }`);
  next();
});

const Model = mongoose.model('Model', schema);

let doc = new Model({ username: 'Testing' });

Model.create(doc)
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(2);
  });
```

**Comment by buffcode** [comment]
When using the correct way to import mongoose by `import mongoose from "mongoose";` your code won't run for the same reason in the pre callback:
`Error: TS2339: Property 'username' does not exist on type 'Document'.`

**Comment by diki** [comment]
I had the same error and could not fix it too @buffcode your solution seems fixing the error at first (vscode does not show the error anymore) but it show up again on compile 😱I just started using TS I might be doing something really stupid :)

If you could not find any solution yet you can modify as `(this as any).password`

**Comment by t1bb4r** [comment]
```
export interface IUser extends mongoose.Document {
  usernname: string,
  password: string
}

const usersSchema = new mongoose.Schema({
  username: String,
  password: String,
});

usersSchema.pre<IUser>("save", function(next) {
  const user = this;
  // user.password and user.username exists here.
  next();
});

const User = mongoose.model<IUser>("Users", usersSchema);
```
This is how I use mongoose with Typescript, see https://www.typescriptlang.org/docs/handbook/interfaces.html for more information on extending interfaces.

**Comment by leeya018** [comment]
I had the same issue:
so this what works for me :
**Model code :**

`
schema.methods.authenticate = async function(password: string) {
  return await bcrypt.compareSync(password, this.password);
};
`

**Router code :**
`
if (await (user as any).authenticate(password)) {
          res.json({ message: "SUCCESS LOGIN" });
 } 
`

**Comment by coolsam726** [comment]
> ```
> export interface IUser extends mongoose.Document {
>   usernname: string,
>   password: string
> }
> 
> const usersSchema = new mongoose.Schema({
>   username: String,
>   password: String,
> });
> 
> usersSchema.pre<IUser>("save", function(next) {
>   const user = this;
>   // user.password and user.username exists here.
>   next();
> });
> 
> const User = mongoose.model<IUser>("Users", usersSchema);
> ```
> 
> This is how I use mongoose with Typescript, see https://www.typescriptlang.org/docs/handbook/interfaces.html for more information on extending interfaces.

Sure this works, but if you don't want to use interfaces just to achieve that, here is how I solved it in my case, by avoiding to reference the variables directly and instead using `get` and `set` methods:

```typescript
export const UserSchema = new mongoose.Schema({
    name: {
        type: String,
        required: 'Name is required',
    },
    username: {
        type: String,
        required: 'username is required'
    },
    email: {
        type: String,
        required: 'email is required'
    },
    password: {
        type: String,
    },
    created_by: {
        type: Number,
    },
},{
    timestamps: true,
    autoIndex: true,
});
```
```typescript
UserSchema.pre("save", function(next: NextFunction) {
    console.log(this.get('password'));
    if(!this.isModified("password")) {
        return next();
    }
    let plaintext = this.get('password');
    this.set('password',bcrypt.hashSync(plaintext, 10));
    next();
 });
```
