### ISSUE TITLE
Unique is not working

### ISSUE THREAD

**Issue by nischay30** [Automattic/mongoose#5050]
HI below is my Schema in which unique is not working

const user = new Schema({
  userName: { type: **String**, required: true, unique: true },
  quiz:[]
}); 

but i have one more Schema in which unique is working and the schema is 

const user = new Schema({
  userName: { type: **'String**', required: true, unique: true },
  quiz:[]
});

and the main difference between them is highlighted.
So anyone can tell me what is the issue?
Why i am facing this?

MongoDB Version: v3.4.2
Nodejs Version: v7.4.0
Mongoose Version: v4.8.5

**Comment by varunjayaraman** [comment]
Are you setting the type to the string value `'String'`?

**Comment by nischay30** [comment]
yes

**Comment by Pinesy** [comment]
Try setting the type to 

`Schema.Types.String` ? I.e.

```js
const user = new Schema({
  userName: { type: Schema.Types.String, unique: true},
});
```

**Comment by varunjayaraman** [comment]
@nischay30 why? You should be setting it to `String`

**Comment by vkarpov15** [comment]
Not a bug, you have to understand that `unique` is an [index configuration option in your schema](http://mongoosejs.com/docs/guide.html#indexes). If your 'users' collection doesn't have a unique index on `userName`, you need to wait for the index to build **before** you start relying on it.

```javascript
function exec() {
  const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

  const user = new mongoose.Schema({
    userName: { type: 'String', unique: true },
    quiz: []
  });

  const User = db.model('User', user);

  const doc = new User({
    userName: 'Bob'
  });

  return new Promise((resolve, reject) => {
      // Wait for all indexes on the 'users' collection to finish building
      User.on('index', error => error ? reject(error) : resolve());
    })
    .then(() => User.create(doc))
    .then(() => User.create({ userName: 'Bob' }));
}
```

While the index is building, MongoDB will still allow duplicates.

**Comment by lednhatkhanh** [comment]
This is a bug, it used to work in the older mongoose version but not now.

**Comment by lednhatkhanh** [comment]
Can confirm that this error has been fixed in `4.11.3`

**Comment by n3pixowe** [comment]
@vkarpov15 Thanks, you are right :)

**Comment by benag** [comment]
Same problem here mongoose: 4.6.1

**Comment by giorgiofellipe** [comment]
Same here on version 4.13.12

**Comment by vkarpov15** [comment]
Use `Model.init()`. If that doesn't work for you, please open up a new issue with detailed code samples. 

```javascript
function exec() {
  const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

  const user = new mongoose.Schema({
    userName: { type: 'String', unique: true },
    quiz: []
  });

  const User = db.model('User', user);

  const doc = new User({
    userName: 'Bob'
  });

  return User.init() // `User.init()` returns a promise that is fulfilled when all indexes are done
    .then(() => User.create(doc))
    .then(() => User.create({ userName: 'Bob' }));
}
```

Read more about why this is on the [validation docs](http://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator).

I'm locking this issue for now due to unhelpful comments that obfuscate the solution.
