### ISSUE TITLE
Skipping subdocument model validation

### ISSUE THREAD

**Issue by cloud-tribal** [Automattic/mongoose#5052]
I am trying to save a subdocument which represents a Model that has a pre save hook that prevents it from saving if there are more than 3 instances of it assigned to a ref.

When I try to save the parent document, it runs the validations for the subdocument.

I would like to skip the validations if the Model is being saved as a subdocument.

Is this possible?

**Comment by varunjayaraman** [comment]
yeah you can see if a document has `this.parent && this.parent()`
