### ISSUE TITLE
Control mongoose connections

### ISSUE THREAD

**Issue by anzileiro** [Automattic/mongoose#5053]
Mongoose v4.8.6 (report)

I'm having some problems with mongodb connections like that:

<img width="1079" alt="screen shot 2017-03-08 at 5 19 11 pm" src="https://cloud.githubusercontent.com/assets/3415671/23722496/5d20cd62-0424-11e7-8f13-d21ce83af925.png">

After a lot of new connections opened, I got that:

<img width="1070" alt="screen shot 2017-03-08 at 5 32 56 pm" src="https://cloud.githubusercontent.com/assets/3415671/23722771/69daf63a-0425-11e7-971a-7ed5f9d813de.png">

Connections never get closed, always are opened a new connection on MongoDB. How can I implement correct mongoose connections to solve it?

Thanks!

**Comment by varunjayaraman** [comment]
How many connections are you opening up? Are you closing your connections when you're done with them? Is something else closing the connection potentially?

It's a bit difficult to debug these kinds of problems in a vacuum :/

**Comment by varunjayaraman** [comment]
I'm going to close this issue as stale unless you do, but feel free to comment here again if you have more context
