### ISSUE TITLE
Populate with refPath searches all ids in all collections

### ISSUE THREAD

**Issue by hytromo** [Automattic/mongoose#5054]
I think this is a bug, but looking at the relevant code it seemed like it was designed that way in purpose.

Currently, when you have something like this:

```
var customersSchema = new Schema({
	name: String,
	rentals: [{
		kind: String,
		item: { type: ObjectId, refPath: 'rentals.kind' }
	}]
});

var customer = new Customer({
	name: 'Tiimmy Turner',
	rentals: [
	{ kind: 'Rentals1', item: objIds[0] },
	{ kind: 'Rentals1', item: objIds[1] },
	{ kind: 'Rentals2', item: objIds[2] },
	],
});
```
and then you run
```
Customer.
findOne({ _id: doc._id }).
populate('rentals.item');
```
mongoose's debug will report
```
Mongoose: rentals2.find({ _id: { '$in': [ ObjectId("ID1_HERE"), ObjectId("ID2_HERE"), ObjectId("ID3_HERE") ] } }, { fields: {} })
Mongoose: rentals1.find({ _id: { '$in': [  ObjectId("ID1_HERE"), ObjectId("ID2_HERE"), ObjectId("ID3_HERE") ] } }, { fields: {} })
```

Which means that it will search all the collections for all the ids. I would expect that mongoose would search each collection only for each own ids, as reported by `rentals.kind`, for each specific `item` (id).

Here's the code that creates example collections and reproduces the problem:
https://gist.github.com/hytromo/ea7983d530cd78181ef6e921827e0957

This has 2 main concerns, I think:

- Reduced speed. If N the number of ids and M the number of the collections they span to, it seems to perform N*M id searches, while they could be reduced to N (the number of the mongodb calls to `find` would remain the same in both cases).

- Could return data from the wrong collection. It is very difficult to have the same ObjectId in different collections, but the `_id` field can also be set by the user and then it could easily clash.

Why doesn't it perform the searches with the corresponding ids for each collection only?

node 4.8.0, mongoose 4.6.6, mongodb 3.2.12

**Comment by vkarpov15** [comment]
That looks like a bug in mongoose. Probably wasn't a huge concern when the dynref code was first written, because it was very challenging to write, but definitely something we need to improve.
