### ISSUE TITLE
Issue with aggregate query

### ISSUE THREAD

**Issue by som-soni** [Automattic/mongoose#5056]
Hi,

I am getting following error while executing aggregate query. ( mongoose version - 4.8.6 )

TypeError: callback.apply is not a function
    at /node_modules/mongoose/lib/model.js:3433:16)

Query --

    EventModel
        .aggregate(
            [
                {"$match": filter},
                {"$unwind": "$assignto"},
                {"$unwind": "$services"},
                {
                    "$lookup": {
                        from: 'servicerequests',
                        localField: 'services.servicerequest_id',
                        foreignField: '_id',
                        as: 'workplan'
                    }
                },
                {
                    "$project": {
                        "date": {
                            "$dateToString": {
                                "format": "%Y-%m-%d",
                                "date": {"$add": ["$fromdatetime", 330 * 60 * 1000]}
                            }
                        },
                        "status": 1,
                        "user_id": "$assignto",
                        "workOrderNumber": {
                            "$let": {
                                "vars": {
                                    "workplan": {
                                        "$arrayElemAt": ["$workplan", 0]
                                    }
                                },
                                "in": "$$workplan.workOrderNumber"
                            }
                        },
                        "patientname": {
                            "$let": {
                                "vars": {
                                    "workplan": {
                                        "$arrayElemAt": ["$workplan", 0]
                                    }
                                },
                                "in": "$$workplan.patientname"
                            }
                        }
                    }
                }
            ])
        .exec(function (err, events) {
            if (err) {
             return callback(err);
            }
            return callback(null, events);
        });

This works fine on mongoose version 4.0.3. Any pointers will be really helpful.

Thanks.

**Comment by vkarpov15** [comment]
Below script doesn't error for me on 4.8.6. Can you please modify the below script so it reproduces your issue?

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test');

var EventModel = mongoose.model('Test', new mongoose.Schema({}));

EventModel
    .aggregate(
        [
            {"$match": {}},
            {"$unwind": "$assignto"},
            {"$unwind": "$services"},
            {
                "$lookup": {
                    from: 'servicerequests',
                    localField: 'services.servicerequest_id',
                    foreignField: '_id',
                    as: 'workplan'
                }
            },
            {
                "$project": {
                    "date": {
                        "$dateToString": {
                            "format": "%Y-%m-%d",
                            "date": {"$add": ["$fromdatetime", 330 * 60 * 1000]}
                        }
                    },
                    "status": 1,
                    "user_id": "$assignto",
                    "workOrderNumber": {
                        "$let": {
                            "vars": {
                                "workplan": {
                                    "$arrayElemAt": ["$workplan", 0]
                                }
                            },
                            "in": "$$workplan.workOrderNumber"
                        }
                    },
                    "patientname": {
                        "$let": {
                            "vars": {
                                "workplan": {
                                    "$arrayElemAt": ["$workplan", 0]
                                }
                            },
                            "in": "$$workplan.patientname"
                        }
                    }
                }
            }
        ])
    .exec(function (err, events) {
      console.log(err, events);
    });
```

**Comment by varunjayaraman** [comment]
@som-soni have you tried @vkarpov15's repro script? Please let us know, otherwise I'm going to close this as stale soon
