### ISSUE TITLE
updateValidators for required array when using setDefaultsOnInsert 

### ISSUE THREAD

**Issue by yishaic** [Automattic/mongoose#5059]
**Do you want to request a *feature* or report a *bug*?**

a bug

**What is the current behavior?**

If I set an array(e.g. users) in my schema as `required: true`, and use `findOneAndUpdate` with `setDefaultsOnInsert: true, runValidators: true`, and then call it in order to update another path in my schema, the validation fails with `ValidationError: Path `users` is required`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const MeetingSchema = new Schema({
...
  timeSlots: {
    type: [
      {
        startDateTime: Date,
        endDateTime: Date,
      }
    ],
    required: true
  },
  attendees: {
    type: [
      {
        _id: false,
        userId: String,
        isRequired: Boolean,
        attendeeType: String
      },
    ],
    required: true
  }
});
```
I insert\update values with findOneAndUpdate:
```
function upsertMeeting(query, doc) {
  return MeetingModel.findOneAndUpdate(
    query,
    doc,
    { new: true, upsert: true, setDefaultsOnInsert: true, runValidators: true }
  );
}
```
If I first insert a valid meeting, and then I call for a partial update
```
let partialUpdate = {
        timeSlots: [{
            startDateTime: '2017-02-26T15:00:00.000Z',
            endDateTime: '2017-02-26T15:30:00.000Z',
          },
        ],
      };
upsertMeeting({ _id: oldMeeting._id }, { '$set': partialUpdate })
```
I get the following error:
```
 ValidationError: Path `attendees` is required.
      at MongooseError.ValidationError (/home/yishai/Workspace/temp/web-app/node_modules/mongoose/lib/error/validation.js:23:11)
      at /home/yishai/Workspace/temp/web-app/node_modules/mongoose/lib/services/updateValidators.js:147:19
```

**What is the expected behavior?**

To not throw this validation error, as the array is not one of the paths specified in the update.

**Please mention your node.js, mongoose and MongoDB version.**

node.js 6.9.1
mongoose 4.8.5
mongo 3.4.1

**My own investigation**

In lib/services/setDefaultsOnInsert.js line 84 there is:
```
  var def = schemaType.getDefault(null, true);
          if (!isModified(modified, path) && typeof def !== 'undefined') {
            castedDoc = castedDoc || {};
            castedDoc.$setOnInsert = castedDoc.$setOnInsert || {};
            castedDoc.$setOnInsert[path] = def;
            updatedValues[path] = def;
          }
```
I use `setDefaultsOnInsert: true`, and for the `attendees` array, `isModified` is false and the default is [], so its added to the `$setOnInsert`.
Then in lib/services/updateValidators.js  line 55 there is:
```
  if (keys[i] === '$set' || keys[i] === '$setOnInsert') {
          updatedValues[updatedPath] = flat[paths[j]];
  }
```
which causes `attendees` to be considered as updated, and run the validation on it - which fails.

**Comment by varunjayaraman** [comment]
yeah i think this is a bug.

Here's a full repro:

```javascript
const mongoose = require('mongoose');
const co = require('co');

mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5059`;

exec()
  .then(() => {
    console.log('Successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
    process.exit(2);
  });

function exec() {
  return co(function* () {
    const db = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

    const schema = new mongoose.Schema({
      timeSlots: {
        type: [
          {
            startDateTime: Date,
            endDateTime: Date,
          }
        ],
        required: true
      },
      attendees: {
        type: [
          {
            _id: false,
            userId: String,
            isRequired: Boolean,
            attendeeType: String
          },
        ],
        required: true
      }
    });
    const MeetingModel = mongoose.model('Meeting', schema);

    const doc = yield MeetingModel.create({
      timeSlots: [
        {
          startDateTime: Date.now(),
          endDateTime: Date.now()
        }
      ],
      attendees: [
        {
          userId: 'asdf',
          isRequired: false,
          attendeeType: 'RandomType'
        }
      ]
    });

    let partialUpdate = {
      timeSlots: [{
        startDateTime: '2017-02-26T15:00:00.000Z',
        endDateTime: '2017-02-26T15:30:00.000Z',
      },
      ],
    };

    return upsertMeeting({ _id: doc._id }, { '$set': partialUpdate });

    function upsertMeeting(query, doc) {
      return MeetingModel.findOneAndUpdate(
        query,
        doc,
        { new: true, upsert: true, setDefaultsOnInsert: true, runValidators: true }
      );
    }
  });
}

```

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior rather than a bug. Arrays have an implicit `default` value of `[]` (empty array), so when you use `setDefaultsOnInsert` mongoose will try to send the below update to mongodb:

```
{ '$setOnInsert': { __v: 0, attendees: [] },
  '$set': { timeSlots: [ [Object] ] } }
```

But validation fails because `required` for an array means the array must have at least one element.

You have a couple workarounds:

1) Set the array's default to `void 0` (or `undefined`, same thing). This will prevent mongoose from setting the default array value

```javascript
    const schema = new mongoose.Schema({
      timeSlots: {
        type: [
          {
            startDateTime: Date,
            endDateTime: Date,
          }
        ],
        required: true
      },
      attendees: {
        type: [
          {
            _id: false,
            userId: String,
            isRequired: Boolean,
            attendeeType: String
          },
        ],
        required: true,
        default: void 0 // <-- explicitly remove the default default for arrays
      }
    });
```

2) Instead of using `required` for the array, use a custom validator that allows empty arrays:

```javascript
    const schema = new mongoose.Schema({
      timeSlots: {
        type: [
          {
            startDateTime: Date,
            endDateTime: Date,
          }
        ],
        validate: v => v != null
      },
      attendees: {
        type: [
          {
            _id: false,
            userId: String,
            isRequired: Boolean,
            attendeeType: String
          },
        ],
        validate: v => v != null // <-- v can only be null, undefined, or an array, so this validator will only pass if v is an array, but, unlike `required`, this allows arrays of length 0
      }
    });
```

Does one of these solutions work for you?

@varunjayaraman any thoughts on removing the default value for arrays? It's convenient but also has numerous weird side effects...

**Comment by yishaic** [comment]
@vkarpov15 thank you for you response. Both solutions are working, although not 100% solutions. Solution No.2 I won't use anyway because I don't want to allow empty arrays because it doesn't make sense in this model. Solution No.1 is just lacking the convenience of the empty array default value.

As for the issue itself, I still think its a bug - the  `attendees` array isn't empty in the db, and I don't try to update it in the current update, so the `updateValidators` shouldn't even check it for validation, because now its an update. The only reason it happens is because its applied with `setDefaultsOnInsert` - but here its not an insert.

**Comment by varunjayaraman** [comment]
i do agree that the default value for an array is convenient. @yishaic i think the problem here is that you want to use `setDefaultsOnInsert`.

What I'm wondering is: should `required` for an array require 1 element (which means that if it were to not, it wouldn't really make sense to put a `required` validator on an array type field)?

**Comment by yishaic** [comment]
@varunjayaraman I think that `required` for an array that require 1 element contradicts the default default value for an array `[]`. So maybe it should be considered to change one of them. Anyway `required` for an array can have many meanings, for example in `graphql`, `[String!]` isn't equivalent to `[String]!`.

As being someone quite new to mongoose, I think that the real issue here is that the update validators validate the `$setOnInsert` values although its not an `insert`. The validators should run only after knowing whether its an insert/update and apply the appropriate validators. But I understand that this might be too difficult to implement.
Also I think this should be noted in the docs, so it will be more clear.

**Comment by vkarpov15** [comment]
Since you specified `upsert: true`, there's no way for update validators to tell whether there will be an insert or not, so it errs on the side of validating `$setOnInsert`.
