### ISSUE TITLE
Support / feature request Model.create().exec()

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5060]
I have this code:

```js
function create(data, cb){
  return (Model).create(data).exec(cb);
}
```

I like this pattern because then we can easily use both promises and callbacks

The problem is that `(Model).create().exec() `is not a valid method. I am wondering why that is.
I get this error:

`'Model.create(...).exec is not a function`

On the other hand, exec() does exist here:

```js
  let q = (Model).findById(id);

  if (populate && populate.length > 0) {
    q = q.populate(populate);
  }

  return q.lean().exec(cb)
```

So my question is - is there a Model.create() style method that does use the exec() pattern? Like I said, this is useful if we need to move between promises and callbacks in the codebase.

Perhaps this will suffice:

```js
function create(data, cb){
  // if callback == null, then will return a promise (?)
  return Prompt.create(data, cb);
}

```

just hoping for some consistency, as I like the exec() pattern for the reasons aforementioned.

**Comment by varunjayaraman** [comment]
Why are you trying to move between promises and callbacks? That makes error handling more difficult in my opinion. I don't have anything against callbacks, but I think using both leads to more confusion than its worth.

**Comment by ORESoftware** [comment]
thanks, I stand by what I originally said. what would be nice out of Mongo is consistency.

If no callback is passed to Model.create(), then it should return a Promise, and I believe it does.

However **the problem** occurs when this happens:

`Model.create(data, undefined)
`
or

`Model.create(data,null)`

In the above cases, it's not returning a promise, something else is happening, it's a bug.
you have a bug somewhere I think.

Perhaps you are checking the length of the arguments, but you need to check the actual value of the arguments! I will check your source code.

**Comment by varunjayaraman** [comment]
@ORESoftware why would you pass null or undefined as a second parameter? This is pretty common amongst node libs to ensure backwards compatibility for callbacks while also allowing promises: you check arguments.length and if it's 2 you treat it as a callback-async operation. I agree it's a bit weird but the alternative seems unnecessary: just don't pass the 2nd parameter to `Model.create()`

**Comment by ORESoftware** [comment]
I am checking your source code to see what the problem is, so far I do not think you are looking at arguments.length, here is the source I am looking at:

```js
Model.create = function create(doc, callback) {
  var args;
  var cb;
  var discriminatorKey = this.schema.options.discriminatorKey;

  if (Array.isArray(doc)) {
    args = doc;
    cb = callback;
  } else {
    var last = arguments[arguments.length - 1];
    if (typeof last === 'function') {
      cb = last;
      args = utils.args(arguments, 0, arguments.length - 1);
    } else {
      args = utils.args(arguments);
    }
  }

  var Promise = PromiseProvider.get();
  var _this = this;
  if (cb) {
    cb = this.$wrapCallback(cb);
  }

  var promise = new Promise.ES6(function(resolve, reject) {
    if (args.length === 0) {
      setImmediate(function() {
        cb && cb(null);
        resolve(null);
      });
      return;
    }

    var toExecute = [];
    args.forEach(function(doc) {
      toExecute.push(function(callback) {
        var Model = _this.discriminators && doc[discriminatorKey] ?
          _this.discriminators[doc[discriminatorKey]] :
          _this;
        var toSave = doc instanceof Model ? doc : new Model(doc);
        var callbackWrapper = function(error, doc) {
          if (error) {
            return callback(error);
          }
          callback(null, doc);
        };

        // Hack to avoid getting a promise because of
        // $__registerHooksFromSchema
        if (toSave.$__original_save) {
          toSave.$__original_save({ __noPromise: true }, callbackWrapper);
        } else {
          toSave.save({ __noPromise: true }, callbackWrapper);
        }
      });
    });

    parallel(toExecute, function(error, savedDocs) {
      if (error) {
        if (cb) {
          cb(error);
        } else {
          reject(error);
        }
        return;
      }

      if (doc instanceof Array) {
        resolve(savedDocs);
        cb && cb.call(_this, null, savedDocs);
      } else {
        resolve.apply(promise, savedDocs);
        if (cb) {
          savedDocs.unshift(null);
          cb.apply(_this, savedDocs);
        }
      }
    });
  });

  return promise;
};
```

**Comment by varunjayaraman** [comment]
@ORESoftware see:

```javascript
if (Array.isArray(doc)) {
    args = doc;
    cb = callback;
  } else {
    var last = arguments[arguments.length - 1];
    if (typeof last === 'function') {
      cb = last;
      args = utils.args(arguments, 0, arguments.length - 1);
    } else {
      args = utils.args(arguments);
    }
  }
```

**Comment by varunjayaraman** [comment]
I'm not saying don't use callbacks. The problem is you will lose the error to the callback abyss if you use both promises and callbacks unless you specifically wrap your callbacks with a Promise constructor and reject the error from within the callbacks. But at that point, it seems pointless to use callbacks if you are going to be chaining promises off of it.

**Comment by ORESoftware** [comment]
There was some of code of mine yesterday where I saw a problem I am trying to figure out where it was, please keep this issue open for a few days I will try to replicate the problem.

I have been working with Node.js for a number of years and have written several libraries that needed to support both promises and vanilla callbacks I am aware of the difficulties.

**Comment by ORESoftware** [comment]
Let me give you one more reason why we mix callbacks and promises: because we use Express. Maybe we could use Koa, but for now, because Express is callback oriented, we have to be a little bit callback oriented at least.

<img width="518" alt="screenshot 2017-03-10 10 14 47" src="https://cloud.githubusercontent.com/assets/11139560/23807447/9132c022-057a-11e7-86e0-1cd8a82d539a.png">

**Comment by varunjayaraman** [comment]
@ORESoftware what's the problem with that?

**Comment by ORESoftware** [comment]
I think the crux of the problem here was resolved on another issue thread so I will close this one, thanks!
