### ISSUE TITLE
Document.isSelected() returns misleading results for partially selected subdocs

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#5063]
`document.isSelected('subdoc')` returns true if only a part of `subdoc` was selected like `model.findOne({}).select('subdoc.subfield').exec()`. 

IMHO `document.isSelected('subdoc')` should not return true since only `field.sub` is selected and not any other field inside `subdoc`.

----
Repro (cannot get the process to error but anyway it should output ` Unhandled promise rejection (rejection id: 1): AssertionError: true == false` 

```js
const mongoose = require('mongoose');
const assert = require('assert');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-50xx`;

try {
  exec()
    .then(() => process.exit(0))
    .catch(err => {
      throw err;
    });
} catch (error) {
  console.error(`Error: ${error}\n${error.stack}`);
  process.exit(2);
}


function exec() {
  const db = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
  const schema = new mongoose.Schema({
    name: String,
    age: Number,
    sub: {
      heigth: Number,
      eyes: String,
    },
  });

  const Model = db.model('Model', schema);

  const doc = new Model({
    name: 'Bob',
    age: 32,
    sub: {
      heigth: 3,
      eyes: 'green',
    },
  });

  return doc.save().then(() => {
    return Model.findOne({}).select('sub.heigth').exec();
  }).then(returnedDoc => {
    assert.equal(returnedDoc.isSelected('sub.heigth'), true);
    assert.equal(returnedDoc.isSelected('sub.eyes'), false);
    assert.equal(returnedDoc.isSelected('sub'), false);
  });
}
```

**Comment by vkarpov15** [comment]
Changing `isSelected()` that way is hard because we use `isSelected()` internally for checking which paths we need to validate. Would a function like `isDirectSelected()` which spits out true if and only if the field was in the original selection help?

**Comment by paglias** [comment]
`isDirectSelected() ` would work well for my use case. I need to check if a path is fully available before running some code in a pre-save hook
