### ISSUE TITLE
Document array not accessible via pre-insertMany hooks

### ISSUE THREAD

**Issue by bdentino** [Automattic/mongoose#5064]
**Do you want to request a *feature* or report a *bug*?**
Not sure if bug or by design

**What is the current behavior?**
Cannot figure out how to access documents that are being inserted within pre-insertMany middleware. The only argument passed to middleware is `next`, and the `this` context of the function is the `model` instance. Is there a way to access the document array that is to be inserted? If not, should there be?

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure if bug or by design

**What is the expected behavior?**
It would be very useful to have access to those docs to be able to manipulate/transform within pre-middleware.

**Please mention your node.js, mongoose and MongoDB version.**
4.8.1

**Comment by vkarpov15** [comment]
Currently by design, not supported yet. There should be a mechanism to handle this but we don't have one yet, sorry.
