### ISSUE TITLE
Update can not set  The second parameter

### ISSUE THREAD

**Issue by mugworts** [Automattic/mongoose#5067]
node v6.6.0 
"mongoose": "^4.7.5",
MongoDB shell version v3.4.0

## update Parameter is null

---

app.js 

```
var mongoose = require('mongoose').set('debug', true);;
```

router.js

```
router.get('/test', function(req, res, next){

var conditions = {"Prodects.id": "2"},
          update =  {'$inc': {"Prodects.$.price": 1}},
          options =  {upsert:true};
          
      CartModel.update(conditions, update, options, function(err) {
      });
});
```

#### The terminal execution results
 
```
hotnode  node process restarted

{ '$inc': { 'Prodects.$.price': 1 } }
Mongoose: carts.update({ 'Prodects.id': '2' }, { '$inc': {}, '$setOnInsert': { __v: 0 } }, { upsert: true })
```

#### The second parameter ---- **'$inc': {}** , but the 'update' is ' update =  {'$inc': {"Prodects.$.price": 1}},'  

Unable to update the data

**Comment by varunjayaraman** [comment]
Hmm, this logs it out correctly for me:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.set('debug', true);

const co = require('co');

const GITHUB_ISSUE = `gh-5067`;

exec()
  .then(() => {
    process.exit(0);
  })
  .catch(error => {
    console.error(error);
    process.exit(2);
  });

function exec() {
  return co(function* () {
    const db = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

    const cartSchema = new mongoose.Schema({
      products: [{
        id: String,
        price: Number
      }]
    });

    const Cart = db.model('Cart', cartSchema);

    const doc = yield Cart.create({
      products: [
        { id: '2', price: 5 }
      ]
    });

    yield Cart.update({ 'products.id': '2' }, { $inc: { 'products.$.price': 1 } });
  });
}
```

The mongoose debug output is:
```
Mongoose: carts.insert({ _id: ObjectId("58c6396cf0cae73b26349b14"), products: [ { id: '2', price: 5, _id: ObjectId("5
8c6396cf0cae73b26349b15") } ], __v: 0 })
Mongoose: carts.update({ 'products.id': '2' }, { '$inc': { 'products.$.price': 1 } }, {})
```

Is that the exact code you're using to update or did you simplify it for the repro example?

Also, as a side note, it's not advise to use the positional operator `$` with `{ upsert: true }`: https://docs.mongodb.com/manual/reference/operator/update/positional/

**Comment by mugworts** [comment]
https://github.com/varunjayaraman 

thank you very much. 

Just now, I insert data, I use **Model.collections.insert **, so I try **Model.collections.update **
**The terminal execution results is RIGHT !**

```
 CartModel.collection.update(conditions, update, options, function(err) {
      });
```
The terminal execution results

```
carts.update({ 'Products.name': 'test' }, { '$inc': { 'Prodects.$.price': 1 } }, { upsert: true })
```


Now, I would change` $`  `{ upsert: true }`
Thank you very much

**Comment by varunjayaraman** [comment]
Hm I'm confused. Are you using the underlying mongodb driver or are you using the mongoose Model?

**Comment by mugworts** [comment]
[https://github.com/varunjayaraman](@varunjayaraman)

In the terminal operation mongo, try using the mongoose, but found that don't use.

#### model.js
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var modelSchema = new Schema({
});
module.exports = mongoose.model('Model', modelSchema);
```
#### router.js

```
var Model = require('../models/model');

router.get('/test', function(req, res, next){
   var conditions = {"Products.name": "mongodb"},
        update =  {'$inc': {"Products.$.time": 100}};

      Model.collection.update(conditions, update, function(err, result){
          res.send(result)
        });
});
```

Don't know whether reasonable, can update the data in the database now

thank you

**Comment by varunjayaraman** [comment]
@mugworts sorry i'm not sure I understand, can you please clarify?

**Comment by varunjayaraman** [comment]
@mugworts can you please provide me with more explanation? I'm marking this as stale and I'm going to close this issue soon otherwise
