### ISSUE TITLE
Array discriminators + $push + $each = no-go

### ISSUE THREAD

**Issue by davebaol** [Automattic/mongoose#5070]
See https://github.com/Automattic/mongoose/commit/7c114acb8fe8497fcb5557bb4a68e8f831b5040f#commitcomment-21305892 to reproduce this issue.

This is related to issue #5009 which is only partially fixed.

Software versions:
- node 6.1.0
- mongoose 4.8.7
- MongoDB 3.4.2

**Comment by vkarpov15** [comment]
@davebaol I added a test case for this :point_up: and it seems to pass. Can you provide a repro script to reproduce this issue in 4.9.0?

**Comment by davebaol** [comment]
@vkarpov15 
This is weird. Your test fails for me using 4.9.0.
I think I'll have to investigate further.

**Comment by davebaol** [comment]
@vkarpov15 
BTW, I'm on Window 7. Cannot test on Ubuntu till monday.

**Comment by davebaol** [comment]
@vkarpov15 
Ok, the test fails for me using 4.9.0 but the veeeery good news is that it works great with version 4.9.1 released just 1 hours ago. :+1: 
I guess you've run the test with a snapshot in between 4.9.0 and 4.9.1.
Closing this... thanks for your great work on mongoose.
