### ISSUE TITLE
ObjectId.isValid('${messageId}') is True?

### ISSUE THREAD

**Issue by FlyingSailor** [Automattic/mongoose#5071]
const { ObjectId } = require('mongoose').Types;
console.log('${messageId}');
console.log(ObjectId.isValid('${messageId}'));

it out:
    ${messageId}
    true

'${messageId}' is a string,  but ObjectId.isValid('${messageId}') is true, why?
thanks for first!

**Comment by varunjayaraman** [comment]
because that's a 12 byte string:

https://mongodb.github.io/node-mongodb-native/api-bson-generated/objectid.html
