### ISSUE TITLE
How can I change _id's type from Objectid to String?

### ISSUE THREAD

**Issue by JoeLeeWu** [Automattic/mongoose#5075]
How can I change _id's type from Objectid to String?
I am using Mongoose in my MEAN app
version:"mongoose": "^4.8.6",
Any ideas?
Thanks a lot!

**Comment by varunjayaraman** [comment]
you can just set the type of the field to String in the schema

**Comment by cAstraea** [comment]
doesn't seem to work ? It's still saving as objectid ignoring my schema definition ?

**Comment by vkarpov15** [comment]
@cAstraea please provide code samples

**Comment by shubhansh** [comment]
your need to provide some default value.
