### ISSUE TITLE
besides 'validate', is it possible to have a 'sanitizer'? 

### ISSUE THREAD

**Issue by beeplin** [Automattic/mongoose#5077]
**Do you want to request a *feature* or report a *bug*?**
requesting a feature

**What is the current behavior?**
Maybe I am wrong, but it seems that in a item of a schema we can only define a `validate` to validate if the value is valid:
```js
new Schema {
  key: type: String, trim: true, validate: someValidationFunc
  ...
}
```
but we cannot define a `santize` to collect the value. The only tools provided currently is `trim`, `lowercase` etc. for strings.

**What is the expected behavior?**
It's nice to have something like this:
```js
import validator from 'validator'
someSanitizationFunc = value => {
  return validator.escape(value);
}
new Schema {
  key: type: String, trim: true, sanitize: someSanitizationFunc // this func returns the sanitized value
  ...
}
```
**Please mention your node.js, mongoose and MongoDB version.**
node: v7.7.2
mongoose: v4.9.0
mongodb: v3.2.10

**Comment by varunjayaraman** [comment]
You can define a setter on a value:

```javascript
new Schema({
  name: {
    type: String,
    set: function(val) {
      return val.replace(' ', '');
    }
  }
})
```

**Comment by beeplin** [comment]
thanks！
