### ISSUE TITLE
Merge Model.create() & Model.insertMany() in one method

### ISSUE THREAD

**Issue by Frosty-Z** [Automattic/mongoose#5081]
[Feature]

Current behavior : as per docs, `Model.create(doc(s), [callback])` does a `MyModel(doc).save()` when an array of documents is provided, whereas `Model.insertMany()` does the same thing but faster (_one operation to the server_).

So maybe stupid question, but why not merge those two methods so that `create()` behaves the same as `insertMany()` (thus performs better) when dealing with several docs + maybe deprecate `insertMany()` ?

Applies to latest version of Mongoose (4.9.0 at date of writing)

**Comment by varunjayaraman** [comment]
@Frosty-Z `insertMany()` doesn't trigger `save` middleware so they're slightly different.

**Comment by vkarpov15** [comment]
@varunjayaraman is right, their implementations are sufficiently different to warrant being separate functions, plus we need `insertMany()` to fulfill the mongodb CRUD specification.

**Comment by Frosty-Z** [comment]
IMHO from a developer using Mongoose's perspective, a single, well documented `create()` endpoint would be simpler & less misleading.

This would still allow to keep different implementations & underlying MongoDB specs, for example by introducing an "options" parameter.

I would suggest for example
```
Model.create(doc); // same as current
Model.create(arrayOfDocs); // same as current
Model.create(arrayOfDocs, {"oneOperation": true}); // would call MongoDB's insertMany() + Mongoose documentation would tell clearly that one operation is sent to server without using save() hook.
```

Only my personal opinion / 2 cents, ultimately it's your decision 🙂

**Comment by vkarpov15** [comment]
Thanks for the suggestion. For now we need to stick with the current approach, because removing `create()` is backwards breaking and removing `insertMany` would break compatibility with the mongodb crud spec. May change in the future but unlikely, I'd rather avoid breaking existing code unless absolutely necessary :)

**Comment by Frosty-Z** [comment]
No problem ; thanks for your reply anyway ;-) I understand that breaking BC is a major concern ; on that point I agree with you 100%.

**Comment by ajithtunerlabs** [comment]
if you put insertMany you cannot get createdAt and updatedAt time

**Comment by lintdeveloper** [comment]
@vkarpov15  based on @mpacary comment. Here are some code samples to work with

 ```
const data = [{
    name: 'Johnson',
    text: 'First test todo'
}, {
    name: 'Abdullahi',
    text: 'Second test todo'
}];
// operation is saved to the server without the save() hook.
Model.create(data, {"oneOperation": true}).then((docs)=>{
   console.log(docs);
}); ```

**Comment by ajithtunerlabs** [comment]
@vkarpov15 Here are some code samples
```
const data = [{
   name: 'Johnson',
   text: 'First test todo'
}, {
   name: 'Abdullahi',
   text: 'Second test todo'
}];
// operation is saved to the server without the save() hook.
Model.insertMany(data).then((docs)=>{
  console.log(docs);
});
```

If you do this you cannot get updateAt and createdAt field. Create will give you those fields but I don't want to use create functionality. Thanks

**Comment by vkarpov15** [comment]
@ajithtunerlabs  which version of mongoose are you using? We have test coverage for timestamps with insertMany unless I'm much mistaken.

**Comment by ajithtunerlabs** [comment]
@vkarpov15 I am using 

> "mongoose": "^5.0.17"

If you try to create multiple documents using insertMany you won't get the timestamp(createdAt, updatedAt) in those created fields.

**Comment by vkarpov15** [comment]
@ajithtunerlabs `^5.0.17` is not a version. Depending on if you have `package-lock.json`, that can mean any version from 5.0.17 to 5.4.16. The below script works fine in 5.4.16 and shows that `insertMany()` does add timestamps to the documents. Please modify the below script to demonstrate your issue.

```javascript
