### ISSUE TITLE
How to create an ObjectId?

### ISSUE THREAD

**Issue by allanchau** [Automattic/mongoose#5082]
**Do you want to request a *feature* or report a *bug*?**
Question/bug in the docs.

**What is the current behavior?**
```javascript
const ObjectId = mongoose.Types.ObjectId;
const SomeModel = new Model({ _id: new ObjectId(...) }); // breaks
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should work according to http://mongoosejs.com/docs/schematypes.html?
If not, how should we use:
- mongoose.mongo.Types.ObjectId
- mongoose.Types.ObjectId
- mongoose.Schema.Types.ObjectId (In Schemas only I assume?)

**Please mention your node.js, mongoose and MongoDB version.**
- node: 6.x (LTS)
- mongoose: 4.8.1
- mongo: 3.0.1

**Comment by varunjayaraman** [comment]
this works for me with latest mongoose and 4.8.1:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5082`;

const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

const schema = new mongoose.Schema({
  name: String
});

const Model = db.model('Model', schema);

try {
  const doc = new Model({
    _id: new mongoose.Types.ObjectId()
  });

  console.log('doc', doc);
 
} catch (error) {
  console.error(error);
}
```

Console log output:
```
doc { _id: 58cd7cfcf9f1150515ee9fb0 }
```

**Comment by allanchau** [comment]
@varunjayaraman Thanks, it seems I accidentally use `mongoose.mongo.Types.ObjectId` when it should be `mongoose.mongo.ObjectId`. `mongoose.Types.ObjectId` seems to work now too.

**Comment by aymather** [comment]
Note, the object id needs to follow mongoose conventions, otherwise you will get this error:

`Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`

In otherwords, you can't do something like this:

`var mongo_id = mongoose.Types.ObjectId('blah')`
