### ISSUE TITLE
Pre and Post middleware not firing at all

### ISSUE THREAD

**Issue by a-koka** [Automattic/mongoose#5087]
**What is the current behavior?**
The code below should trigger the `pre` and `post` hooks.
```
Asset.findById(assetId).then(asset => asset.remove())
```

**AssetSchema.js**

```
const AssetSchema = mongoose.Schema({
  name: { type: String, required: true, trim: true }
});

const Asset = mongoose.model('Asset', AssetSchema);

AssetSchema.pre('remove', function(next) {
  console.log('pre', this._id)
})

AssetSchema.post('remove', function(next) {
  console.log('post', this._id)
})
```
MongoDB: 3.4.0
Mongoose: 4.9.1
NodeJS: 6.8.1

**Comment by varunjayaraman** [comment]
You have to define your hooks before calling `mongoose.model()`

**Comment by danielrvt** [comment]
Why isn't this on the docs?

**Comment by ItzzS1d** [comment]
> You have to define your hooks before calling `mongoose.model()`

You thanks man i was stuck for long time

**Comment by vkarpov15** [comment]
There's a [dedicated section in the middleware docs about having to define middleware before calling `mongoose.model()`](https://mongoosejs.com/docs/middleware.html#defining)
