### ISSUE TITLE
findOneAndUpdate regression? "$setOnInsert is empty"

### ISSUE THREAD

**Issue by maenthoven** [Automattic/mongoose#5088]
Hey everyone,

I just updated mongoose from 4.4.20 to 4.9 and seem to have a bad bug with findOneAndUpdate.

I now get this message: "$setOnInsert is empty. You must specify a field like so:"

```db.findOneAndUpdate({_id: doc._id}, doc, {new: true})```

Any idea why this would start with the version upgrade?

Simple reproduction below... obviously this isn't how you'd actually use findOneAndUpdate, but it is an easy trigger:

    connect().then(() => {
	var mongoose = require("mongoose"),
		RequestSchema;

	mongoose.Promise = require("bluebird");
	RequestSchema = mongoose.Schema({
		submitter: {
			name: String,
			email: String
		},
		identifier: String,
		type: {
			type: String,
			uppercase: true,
			index: true,
			required: true,
			enum: ["GAME", "REVIEW", "AUTHOR"]
		},
		status: {
			type: String,
			uppercase: true,
			index: true,
			default: "NEW",
			enum: ["NEW", "APPROVED", "DENIED"]
		},
		data: String
	}, { timestamps: true });

	var db = mongoose.model("Request", RequestSchema, "Request");

	return db.findOne({}).then(thing => {
		thing.status = "APPROVED";
		return db.findOneAndUpdate({_id: thing._id}, thing, {new: true});
	});
      }).then(() => console.log("Did it!"));
      .catch((err) => console.logg(err));`

**Comment by varunjayaraman** [comment]
yeah looks like this is an actual bug, here's a repro script that works:

```javascript
var mongoose = require("mongoose"),
  RequestSchema;
const GITHUB_ISSUE = `gh-5088`;

mongoose.Promise = global.Promise;

const connection = mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

RequestSchema = new mongoose.Schema({
  submitter: {
    name: String,
    email: String
  },
  identifier: String,
  type: {
    type: String,
    uppercase: true,
    index: true,
    required: true,
    enum: ["GAME", "REVIEW", "AUTHOR"]
  },
  status: {
    type: String,
    uppercase: true,
    index: true,
    default: "NEW",
    enum: ["NEW", "APPROVED", "DENIED"]
  },
  data: String
}, { timestamps: true });

var db = mongoose.model("Request", RequestSchema, "Request");

db.create({ type: 'GAME' })
  .then(doc => db.findOne({ _id: doc._id }))
  .then(thing => {
    thing.status = "APPROVED";
    return db.findOneAndUpdate({ _id: thing._id }, thing, { new: true });
  })
  .then(() => console.log("Did it!"))
  .catch((err) => console.log(err));
```
