### ISSUE TITLE
Altering an object into a hook

### ISSUE THREAD

**Issue by Fred2MTL** [Automattic/mongoose#5092]
Hi,
At this time, it's just a question, perhaps a feature request.
I have an account schema, embedding the (encrypted) password and use for the connection through passport.js. I also use this schema in order to store specific information regarding the client action. 
So, i don't want these informations (password, etc) to be extracted from the database. Then, i just want to remove them with help of a post hook on 'init'. But, the hook only allows to update a value of the given object (as parameter of the function), not to alter the object by adding or removing an entry.
So, how can i do that ?

Node : 7.7.3, Mongoose : 4.9.1, MongoDb : 3.4.2

**Comment by varunjayaraman** [comment]
@Fred2MTL sorry I'm not sure what you mean. Why can't you remove the field from the object in the hook?

**Comment by Fred2MTL** [comment]
I think some information, like password, NAS, etc., must remain into the database. You can compare it in case of search (for example, as parameter for a find). But, you can't extract it from the database (for example, as field of object returned by a query). 
Actually, i manage this case by filtering at the applicative level (aka express). But, it requires coding and isn't systematic. So, a hole could potentially exist.
I expected to use hook in order to filter the document returned by mongo. Not for adding a field outside of the schema, but for removing this kind of field. Moveover, i don't want to nullify it, because the next 'save operation' will overwrite the real value (i.e. the real password).

**Comment by varunjayaraman** [comment]
@Fred2MTL sorry I'm still slightly confused what you're asking for.

Does `select: false` not solve your problem?

**Comment by Fred2MTL** [comment]
@varunjayaraman 
You're right. I did not pay attention to this possibility on the schema types. Sorry and thanks for your support.
This case is closed.
