### ISSUE TITLE
Mongoose Fails to reconnect if database get disconnected (Replica set Mlab Db)

### ISSUE THREAD

**Issue by manoj97738** [Automattic/mongoose#5094]
Node version : 6.9.5
Mongoose : 4.6.1 
MongoDB (mlab) : 3.0.12 Replica set

The reconnect event are never fired.
Even after 1 or 2 tried the mongoose will never reconnect

We even tried tweaking the below setting but mongoose fails to reconnect to MLab 

var opts = {
    server: {
        auto_reconnect: true,
        socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 }, 
        connectWithNoPrimary: false  
    },
    db: {
        numberOfRetries: 10,
        retryMiliSeconds: 1000
    },
    replset: { 
        socketOptions: { keepAlive: 1, connectTimeoutMS : 30000 }, 
        connectWithNoPrimary: false
    }
};

Steps to produce is  create a node.js app with MLAB replica set try shutting down the DB the mongoose would never reconnect or reconnect event are  just once. Event the disconnected events are fires just once

**Comment by CN-Sean** [comment]
me too.
{mongos: true}
sharding cluster

**Comment by nooks** [comment]
+1

**Comment by leonardoampuero** [comment]
My nodejs app looses connection using mongoose, and I see many "reconnected/disconnected" events, but I end restarting the app to make it back to normal.

+1
