### ISSUE TITLE
Query middleware not executed when using cursor

### ISSUE THREAD

**Issue by zoellner** [Automattic/mongoose#5096]
Not sure if it is a bug or by design, but query middleware is ignored for `.cursor()` calls. If it's by design it should be mentioned in the docs.

Expected behavior would be the same query for either call. 
Current behavior is (with test script below): 
find(): `Mongoose: tests.find({ b: true }, { fields: {} })`
find().cursor(): `Mongoose: tests.find({ isB: true }, { retainKeyOrder: false, fields: {} })`

```
'use strict';

const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/github-mongoose-query-middleware-cursor', {});
mongoose.set('debug', true);

const TestSchema = new mongoose.Schema({a: {type: String}, b: {type: Boolean}});

const queryMiddleware = function() {
  if (this._conditions.hasOwnProperty('isB')) {
    this._conditions.b = this._conditions.isB;
    delete this._conditions.isB;
  }
};

TestSchema.pre('find', queryMiddleware);
TestSchema.pre('findOne', queryMiddleware);
TestSchema.pre('count', queryMiddleware);

const Test = mongoose.model('Test', TestSchema);

const query = { user: { $type: 'string' } };

Test.insertMany([{a: 'b true', b: true}, {a: 'b false', b: false}], function (err) {
  if (err) {console.error(err);}
  Test.find({isB: true}).exec(function(err, t) {
    if (err) {console.error(err);}
    console.log(t);

    let cursor = Test.find({isB: true}).cursor();
    process.exit();
  });
});
```

using
node.js v6.9.5
mongoose v4.9.1
mongodb v3.4.1

**Comment by varunjayaraman** [comment]
@zoellner thanks for the clear repro script, this looks like a bug

**Comment by joniba** [comment]
is there a workaround for those of us that cannot upgrade right now to a version with the fix?

**Comment by vkarpov15** [comment]
@joniba not currently. What version are you on and what prevents you from upgrading to 4.9.2?
