### ISSUE TITLE
cursor.eachAsync document values are wrapped

### ISSUE THREAD

**Issue by JoeTheFkingFrypan** [Automattic/mongoose#5097]
### Summary ###

- `Model.find().cursor().eachAsync()` does not return the **document values** as expected.
- Instead they are **wrapped inside an object** containing the following **keys**: `$__`, `isNew`, `errors`, `_doc`. 

- Unless I am misunderstanding what **eachAsync** is supposed to be doing, I am assuming I should normally be able to do a simple `.eachAsync(handler)` because the document shouldn't be wrapped the way it is.

### Technical information ###

- Node `v6.10.0`
- Mongoose `v4.9.1`

### Details ###

```javascript
return User.find(params.query, params.select, params.options)
  .cursor()
  .eachAsync(user => {
    // HERE > user values will be wrapped in "user._doc"
    // Cannot do "handler(user)", have to fallback on handler(user._doc)
    return handler(user._doc).then(completeUser => users.push(completeUser));
  })
  .then(() => {
    return Promise.resolve(users);
  });
```

**Comment by varunjayaraman** [comment]
@JoeTheFkingFrypan that's probably just the mongoose document, but when you console log it should have the proper values on it like virtuals and the fields on the schema:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const _ = require('lodash');

const co = require('co');

const GITHUB_ISSUE = `gh-5097`;

exec()
  .then(() => {
    console.log(`Program ran successfully`);
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
    process.exit(2);
  });

function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
    const schema = new mongoose.Schema({
      name: String
    });

    schema.virtual('age').get(function() {
      return 24;
    });

    const User = db.model('User', schema);
    yield User.remove({});

    for (let i = 0; i < 10; i++) {
      yield User.create({ name: `Doc-${ i }` });

    }
    return User.find()
      .cursor()
      .eachAsync(function(user) {
        console.log('user', user.name + ' ' + user.age);
      })
      .then(() => Promise.resolve())
  });
}
```

Does this not log out:
```
user Doc-0 24
user Doc-1 24
user Doc-2 24
user Doc-3 24
user Doc-4 24
user Doc-5 24
user Doc-6 24
user Doc-7 24
user Doc-8 24
user Doc-9 24
```

for you?

**Comment by JoeTheFkingFrypan** [comment]
Might be a relevant information : I'm using `Bluebird v3.5.0` as promise engine.

The problem comes from the fact I needed to iterate over the result keys, which ended up iterating over `$__`, `isNew`, `errors`, `_doc` instead of the actual user object keys.

**Comment by vkarpov15** [comment]
`eachAsync()` gives you a full fledged mongoose document. If you want the POJO version, you can either use `.toObject()` or `.lean()`

```javascript
return User.find()
  .cursor()
  .eachAsync(user => { user = user.toObject(); /* ... */ });
```

Or

```javascript
return User.find()
  .lean()
  .cursor()
  .eachAsync(user => { /** user is now a POJO */ });
```

**Comment by JoeTheFkingFrypan** [comment]
Thanks for the tip!
