### ISSUE TITLE
"MongoError $setOnInsert' is empty" when trying to save properties that are not in schema (using strict false)

### ISSUE THREAD

**Issue by MidnightP** [Automattic/mongoose#5099]
I want to achieve updates (preferably `findOneAndUpdate` or `findByIdAndUpdate`) with fields that are not specified in the mongoose model.

My code is as follows:

```
Model = mongoose.model('Model', new Schema({
    ip:               { type: String  },
    operator:               { type: String  }
    }, {
        strict: false,
        versionKey: false,
        timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' }
})

const options = {
    runValidators: true,
    upsert: false,
    setDefaultsOnInsert: false
}

Model
    .findOneAndUpdate({_id}, { $set: newEntry }, options)
    .lean()
    .exec((err, result) => {
   // doing stuff
   })
```

When I attempt to update document's fields that are included in the schema everything goes well.
```
const newEntry = {
  "operator": "Foo",
  "ip": "10.112"
}
```

But when i attempt to update fields that are NOT in the schema like so: 
```
  const newEntry = {
  "operator": "Foo",
  "ip": "10.112",
  "field_not_in_schema": "new stuffs"
}
```

I receive a Mongo error!

`MongoError: '$setOnInsert' is empty. You must specify a field like so: {$setOnInsert: {<field>: ...}}`

I love Mongoose but this is very frustrating and confusing.

Does `strict: false` in schema apply to `findOneAndUpdate` ? 

I have also tried updating like this:

```
Model
    .where({_id})
    .setOptions({ strict: false, runValidators: false })
    .update({ $set: newEntry })
```

But to no avail. What is going on?

**Comment by heikomat** [comment]
@MidnightP Are you using 4.9.1? If so, this is probably a douplicate of https://github.com/Automattic/mongoose/issues/5088

Try 4.9.0 and see if this works for you

**Comment by MidnightP** [comment]
Yes I am. Is it the same bug #5088 ?

Using v4.9.1 and disabled timestamps: all seems to go well this way...
Using v4.9.0 and enabled timestamps: success!

Also, it seems like the bug relates to #5045 ?

**Comment by varunjayaraman** [comment]
yeah @MidnightP this is probably a duplicate. 4.9.2 should be released in a few days, can you post again then if you still have the issue?

**Comment by MidnightP** [comment]
Will do my best

**Comment by MidnightP** [comment]
seems like this is fixed now. Thanks!
