### ISSUE TITLE
Mongoose select,populate and save behaving differently on Mac and Windows

### ISSUE THREAD

**Issue by deveshjadon98** [Automattic/mongoose#5100]
I have a funciton in which i am selecting only 3 fields to go ahead with i.e billing,current_referral_program and referral. And populating user using the reference stored in billing.user

`static populateReferralLinks(){

    return Promise.coroutine(function*(){
        let companies = yield Company.find({},'billing referral current_referral_program')
        .populate('billing.user','emails name');
        for(let i = 0 ; i < length ; i++){  
            companies[i].referral.is_created = true;
            companies[i].referral.referral_email = companies[i].billing.user.emails[0].email;
            companies[i] = yield companies[i].save();
       }
       return companies;
    })
    .apply(this)
    .catch((err) => {
            throw err;
    });
} `

Now when i call this function then on line

`companies[i].save();`

The following command is shown in the terminal in windows

`Mongoose: companies.update(
{ _id: ObjectId("58d12e1a588a96311075c45c") }, 
{ '$set': 
   { billing: 
      { configured: false, 
        user: ObjectId("58d12e16588a96311075c45a") }, 
     referral: 
     { is_created: true,  
       referral_email: 'jadon.devesh98@gmail.com', 
     }, 
     updatedAt: new Date("Wed, 22 Mar 2017 12:02:55 GMT") 
   } 
}
)`

But in Mac's terminal it shows this command

`Mongoose: companies.update({ _id: ObjectId("58d12e1a588a96311075c45c") }) { '$set': { billing: { configured: false, user: ObjectId("58d12e16588a96311075c45a") }, current_limit: {}, current_usage: {},referral: { is_created: true, referral_email: 'jadon.devesh98@gmail.com'}}, '$unset': { updatedAt: 1 } }`

Now, I haven't mentioned **current_limit** and **current_usage** to be empty. it's executing fine on windows but on Mac it's setting **current_limit** and **current_usage** empty thus updating my document with empty objects on Mac but not on windows.

It should behave same way on both OS but it is not.

My Company Schema is like this

`const companySchema = new mongoose.Schema(
    {
       name: {
            type: String,
            trim: true,
            required: true,
            minlength: 3,
            lowercase: true,
        },
        current_limit: {
            leads: {
                type: Number,
                default: null
            },
            traffic: {
                type: Number,
                default: null
            }
        },
        current_usage: {
            leads: {
                type: Number,
                default: 0
            },
            traffic: {
                type: Number,
                default: 0
            }
        }
        billing: {
            user: {
                type: mongoose.Schema.ObjectId,
                ref: 'User'
            },
            configured: {
                type: Boolean,
                default: false
            },
        },
        current_referral_program: {
            type: String,
            uppercase: true,
            enum: ['FIRST', 'SECOND'],
            default: 'FIRST'
        },
        referral: {
            is_created:{
                type: Boolean,
                default: false
            }
            referral_email:{
                type: String,
                default:null
            }
        }
    },
    {
        timestamps: true,
        autoIndex: true
    }
);`

and User Schema is like this

`const userSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            trim: true,
            default: ''
        },
        username: {
            type: String,
            trim: true,
            required: true,
            minlength: 4,
            lowercase: true,
            unique: true
        },
        emails: [emailSchema],
        password: {
            type: String,
            required: true,
            minlength: 8
        },
    },
    {
        timestamps: true,
        autoIndex: true
    }
);`

Note : this happens only for fields like **current_limit** which store an object but not for fields like **name** which store single value but not whole object.

MongoDb version is 3.4.0 on both systems
Mongoose version is 4.5.8

**Comment by varunjayaraman** [comment]
@deveshjadon98 can you try with mongoose 4.9.1. This is definitely a weird one... what version of node are you using?

**Comment by deveshjadon98** [comment]
@varunjayaraman it worked fine after upgrading to mongoose 4.9.1 , now it's making the same query in both environments, which was earlier made in windows. i am using ubuntu instance on aws, On 4.5.8 it resulted in data loss because of different queries. All good now, Thanks.
