### ISSUE TITLE
Really slow populate

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#5103]
Node v6.10.0 - Mongo 3.4.3 - Mongoose 4.9.0

I have a collection of 500k users, some of them have a company (less than 200).

    model.find({}, '+profile +geo +worker +company').lean().limit(5000).batchSize(batch).stream();

It tooks me 0.7 seconds to get the 5000 profiles, when adding this populate:

    model.find({}, '+profile +geo +worker +company', {
          populate: {
            path: 'company',
            model: 'Company',
            select: '_id name',
            options: {
              lean: true
            }
          }
        }).lean().limit(5000).batchSize(batch).stream();

It takes around 11 seconds (while in my test set, there are only 4 companies)

When activating the logs thanks to `require('mongoose').set('debug', true);`
I get:

    Mongoose: users.find({}, { limit: 5000, batchSize: 1000, fields: { 'campaign.campaigns': 0, birth: 0, city: 0, address: 0, zip: 0, nationality: 0, admin: 0, peopledoc: 0, password: 0, email: 0, dt: 0, phone: 0, bu: 0, endorsements: 0, 'profile.norm': 0 } })
    Mongoose: companies.find({ _id: { '$in': [ ObjectId("58cbb8cee558ff1b16da60a1") ] } }, { fields: { _id: 1, name: 1 } })
    Mongoose: companies.find({ _id: { '$in': [ ObjectId("58cbf209e723453ece746901") ] } }, { fields: { _id: 1, name: 1 } })
    Mongoose: companies.find({ _id: { '$in': [ ObjectId("58cbf7c51cb26f3ec86d289d") ] } }, { fields: { _id: 1, name: 1 } })
    Mongoose: companies.find({ _id: { '$in': [ ObjectId("58cbf8bbb910a33e97dd273e") ] } }, { fields: { _id: 1, name: 1 } })

It seems that 99% of the time is passed in `getModelsMapForPopulate` in the `model.js` on line 2927

**Comment by vidding** [comment]
I also found it is slow to use populate.
Without populate, first i get a collection of some users, then get the collection of company id from users, make the company id in collection is unique, last get company by  the collection of company id.
It takes less than 1 seconds.

**Comment by jbdemonte** [comment]
Yep, I also write a custom "populate" for another project which collect all ids to retrieve, make a unique select and set these object manually (using hashmap of id => object), and it's really fast

**Comment by jbdemonte** [comment]
The time is lost in the `var originalOptions = utils.clone(options);` in the `getModelsMapForPopulate` function on line 3235

Here is the kind of content of the `options`object cloned:

```
{ path: 'company',
  match: undefined,
  select: '_id name',
  options: { lean: true },
  _docs: 
   { '58ca9557841f51435bcb1ab9': undefined,
     '58cab51e5671084365f7e54f': undefined,
     '58cab583db9bd7435521f6ec': undefined,
     '58cbb8cee558ff1b16da60a0': 58cbb8cee558ff1b16da60a1,
     '58cbe5576f89a93f6534073e': undefined,
     '58cbf209e723453ece746900': 58cbf209e723453ece746901,
     '58cbf28f1cb26f3ec86d2579': undefined,
     '58cbf7c51cb26f3ec86d289e': 58cbf7c51cb26f3ec86d289d,
     '58cbf8bbb910a33e97dd273d': 58cbf8bbb910a33e97dd273e,
     '58cc03961e6d244df3e91759': undefined,
     '58cfa4f8fcd1ee7aa01174ea': undefined,
     '58d1504df9a02b5105378880': undefined,
     '58d23182579e2450d4c1151f': undefined,
     // ... lot of _id => undefined
     '58d251a84d4a890520808925': undefined },
  isVirtual: false }

```

**Comment by jbdemonte** [comment]
I didn't see any reason why _docs should be cloned.
I try this __*really ugly*__ fix and everything seems to be ok:
```
  var tmpDoc = options._docs;
  delete options._docs;
  var originalOptions = utils.clone(options);
  options._docs = tmpDoc;
```
A nicer fix should be to add an option to utils.clone to ignore some keys

**Comment by varunjayaraman** [comment]
@jbdemonte i'll label this an enhancement request
