### ISSUE TITLE
Can't query on subclassed models

### ISSUE THREAD

**Issue by alexis-y** [Automattic/mongoose#5104]
This is a follow-up on #5019. It took me a while to get on it, version 4.8+ required some additional changes in my project that I hadn't got time to solve until recently. On with this issue...

I declare a model and a discriminator (subclass) of it, using ES6 classes. I save some documents. The data in the collections look ok. But querying on the discriminator produces no results.

### Repro
```JavaScript
const { Mongoose, Model, Schema } = require('mongoose');

describe('mongoose discriminated classes', () => {
  it('should query correctly', done => {
    class Shape extends Model { };
    class Circle extends Shape { };
    mongoose.model(Shape, new Schema({ color: String }));
    Shape.discriminator(Circle, new Schema({ radius: Number }));

    mongoose.connect(/* your connection string here */, () => {
      let circle = new Circle({ color: 'blue', radius: 3 });
      circle.save(() => {

        // Done preparing, now do your thing
        Circle.find({}, (err, circles) => {
          assert.equal(err, null);

          assert.notEqual(circles.length, 0); // Fails here

          done();
        });
      });
    });
  });
});
```

If I trace the query being made with ```mongoose.set('debug', true)```, I can see why there's no results...
```
Mongoose: shapes.find({ __t: 'class Circle extends Shape { }' }, { fields: {} })
```

The value of the discriminator is wrong! Sure enough, if I query with ```Shape.find({})``` instead of ```Circle.find()```, I get the expected result. Finally, I added
```JavaScript
Circle.schema.discriminatorMapping.value = Circle.name;
```
and it worked beautifully.

So, I guess there's somehing missing in ```Model.discriminator()``` re: ES6 classes.

**Comment by varunjayaraman** [comment]
@alexis-y haha yeah thats definitely not the discriminator key you want. I'll mark this is a bug

**Comment by alexis-y** [comment]
This means that, unlike ```mongoose.model(SomeClass, ...)```, this function doesn't operate and return back the same Class that was passed as argument.

ie.:
```JavaScript
class Vehicle { }
var V = mongoose.model(Vehicle, vehicleSchema);
// V === Vehicle
class Car extends Vehicle { }
var C = Vehicle.discriminator(Car, carSchema);
// C !== Car
```

As a consequence, the discriminator doesn't have statics or methods. Also, it's a breaking change compared to the previous version (4.9.1?)
