### ISSUE TITLE
How to ensure separation of reading and writing in replica sets ?

### ISSUE THREAD

**Issue by RifeWang** [Automattic/mongoose#5107]
```
// replica sets
var uri = 'mongodb://user:pass@localhost:port,anotherhost:port,yetanother:port/mydatabase';
mongoose.connect(uri);
```
I can connect to replica sets through the way above, but the pramary and the secondary will change, so how to ensure separation of reading from secondary and writing in pramary ?

**Comment by vkarpov15** [comment]
Read up on [read preferences](https://docs.mongodb.com/manual/core/read-preference/)
