### ISSUE TITLE
Request options strict: false on findByIdAndUpdate & findOneAndUpdate

### ISSUE THREAD

**Issue by MidnightP** [Automattic/mongoose#5108]
It seems consistent to include the option `strict`, i.e. `strict: false` or `strict: 'throw'`, on `findByIdAndUpdate` & `findOneAndUpdate` and all update functions in general. 

I've been trying and trying and searching for a solution in the source code until I find out I presupposed wrongly that `strict` was an option  `findByIdAndUpdate` & `findOneAndUpdate`.  Why is the option not there?

**Comment by MidnightP** [comment]
+ same for useNestedStrict

**Comment by varunjayaraman** [comment]
@MidnightP I'm not sure myself, I'll loop @vkarpov15 in who can chime in on whether or not this is an enhancement worth pursuing.

**Comment by vkarpov15** [comment]
Hmm that's strange, I thought they had a strict option. Guess not. Will add for next minor release.

**Comment by MidnightP** [comment]
Would be super deluxe!
