### ISSUE TITLE
'refPath' not evaluated when using discriminator

### ISSUE THREAD

**Issue by thecastor** [Automattic/mongoose#5109]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Scenario: a `Post` has a `date` and a `text`, a `MediaPost` extends `Post` via discriminator, and references `media`, which can be either an `Image` or a `Video`.

    var options = { discriminatorKey: 'kind' };
    var Post = model('Post', new Schema({ time: Date, text: String }, options));
    var MediaPost = Post.discriminator('MediaPost', new Schema({ 
        media: { type: Schema.Types.ObjectId, refPath: 'mediaType'  },
        mediaType: String // either 'Image' or 'Video'
    }, options));
    var Image = model('Image', new Schema({ url: String }));
    var Video = model('Video', new Schema({ url: String, duration: Number }));

The following finds all `MediaPost`s and populates the referenced `media`, as expected:

    MediaPost.find({}).populate('media');

Querying *all* Posts (there might be further types, e.g., `ActivityPost`), *will not populate media*:

    Post.find({}).populate('media');

While strictly speaking this behaviour is not a bug (`Post` doesn't know about `media` after all), the only way to populate all different kinds of `Post`s (I know of) is to 

    Post.find({}).populate('populate fields of all types of posts')
And this actually works well, even if a child Schema uses `ref`. However, it doesn't work with `refPath`, the respective reference is not populated.

The reason is, that  in `model.js`, lines  3242 ff.,

    function getModelsMapForPopulate(model, docs, options) {
        // ...
        schema = model._getSchema(options.path); // line 3252
        // ...
        refPath = schema && schema.options && schema.options.refPath; // line 3272
    
        for (i = 0; i < len; i++) {
            doc = docs[i];

            if (refPath) { // line 3276
                modelNames = utils.getValue(refPath, doc);
                if (Array.isArray(modelNames)) {
                    modelNames = modelNames.filter(function(v) {
                        return v != null;
                    });
                }
            } else {
                // ...
                var schemaForCurrentDoc;
                
                if (!schema && discriminatorKey) { // line 3288
                    modelForFindSchema = utils.getValue(discriminatorKey, doc);
                    // sets schemaForCurrentDoc for extended schemas/models
                }
                // ...
                if (schemaForCurrentDoc && schemaForCurrentDoc.options && schemaForCurrentDoc.options.ref) { // line 3304
                    modelNames = [schemaForCurrentDoc.options.ref];
                } else if (virtual && virtual.options && virtual.options.ref) {
                    modelNames = [virtual && virtual.options && virtual.options.ref];
                    isVirtual = true;
                } else {
                    // We may have a discriminator, in which case we don't want to
                    // populate using the base model by default
                    modelNames = discriminatorKey ? null : [model.modelName];
                }

Lines 3252 and 3272 try to determine a `schema` (and `refPath`, if it exists) *for the Model used to perform the query (not any derived models)*.
Thus `schema` is undefined for any fields (`options.path`) which are not part of that Model, and consequently, `refPath` is undefined for any such fields and not regarded on line 3276. 
This is what happens to the `Post` Model when trying to populate `media`, which is not a property of `Post`.

So the `refPath` for child Models needs to be resolved later on, when the `discriminatorKey` and the actual child Schema/Model are taken into account (lines 3288 ff.). Here, the actual Schema is determined (`MediaPost`) and now its `ref`s can be populated (lines 3304 ff.).
However, there is no clause for `refPath`.

I suggest that either
- there should be a way to define populate options based on the resolved `refPath` (resolved meaning `Image` or `Video` in the example above). This way, `media` would only be considered for population of `Post`s that acutally *are* `MediaPost`s.
- `refPath` should be evaluated in child Models, just as `ref`is. The following code does exactly that:

```
if (schemaForCurrentDoc && schemaForCurrentDoc.options && schemaForCurrentDoc.options.ref) { // line 3304
    modelNames = [schemaForCurrentDoc.options.ref];
}
// handles refPath in child schemas 
else if (schemaForCurrentDoc && schemaForCurrentDoc.options && schemaForCurrentDoc.options.refPath) {
    modelNames = utils.getValue(schemaForCurrentDoc.options.refPath, doc);
    if (Array.isArray(modelNames)) {
        modelNames = modelNames.filter(function(v) {
            return v != null;
        });
    }
} else if (virtual && virtual.options && virtual.options.ref) {
// ...
```
**What is the expected behavior?**
`refPath` should be evaluated for child Models, even when the query was made using the parent Model.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: 6.9.5
mongoose: 4.9.1
MongoDB: 3.4.0

**Comment by varunjayaraman** [comment]
@thecastor thanks for the detailed issue / suggestion. I'm going to label this a feature request

**Comment by Crackz** [comment]
**Waiting for this feature to be implemented !**
