### ISSUE TITLE
Is it safe to use Moment.js objects with mongoose?

### ISSUE THREAD

**Issue by serge-nikitin** [Automattic/mongoose#5110]
I would like to use [moment.js](https://momentjs.com/) library instead of built-in Date object.

```
const moment = require('moment')

const schema = new mongoose.Schema({
  createdAt: Date
})

const Data = mongoose.model('Data', schema)

async function main() {
  const d = new Data({ createdAt: moment().subtract(1, 'hours') })
  await d.save()
  console.log(await Data.find({createdAt: {$gt: moment().subtract(1, 'months')}}).exec())
}
```

It looks like everything works fine. But maybe there are some pitfalls with it?

I haven't found anything about moment.js in documentation.

**Comment by varunjayaraman** [comment]
Is there a particular reason you're doing this vs storing it as a JS Date or a unix timestamp and converting it to a moment on retrieval? I think this works because Mongoose will type coerce it to a Date object and `Moment`s will turn into JS Date objects when you call the Date constructor on them.

That being said, I think it's far better to store this as a Date or Integer (unix timestamp) and then convert it in a getter or a pre('init') hook or something

**Comment by vkarpov15** [comment]
I'd really recommend using `moment().toDate()` or use this lib: https://www.npmjs.com/package/mongodb-moment

**Comment by adamreisnz** [comment]
And here I've been writing parsers to convert all moments in my models with `toDate()` prior to saving, until I realised I didn't always do it and things still worked as expected... ;)

**Comment by vkarpov15** [comment]
Lol yeah this is one of my favorite gotchas :) There's also this if you want to be very defensive: https://www.npmjs.com/package/mongodb-moment

**Comment by adamreisnz** [comment]
@vkarpov15 does Mongoose actually also handle moment objects in queries properly (e.g. `.find({date: {$gte: moment()}})`? Because I've been converting those to plain `Date`'s too, I seem to recall it didn't work if I didn't.

**Comment by vkarpov15** [comment]
Yes it should. When casting to date, mongoose will look for `valueOf()` and use that.

**Comment by adamreisnz** [comment]
Unfortunately, it doesn't seem to work in `aggregate` pipelines though -- still need to convert to Date objects there manually.

**Comment by vkarpov15** [comment]
Yeah mongoose doesn't do any casting on aggregation pipelines. For that case, you need to use mongodb-moment or attach your own toBSON() function. I don't see a way for mongoose to help with that.

**Comment by adamreisnz** [comment]
Yep I copied the toBSON method from MongoDB moment and that seems to work
well 👍🏻

**Comment by adamreisnz** [comment]
@vkarpov15 is there any way to "retain" a moment on a document without having it be cast to a `Date` object all the time, and only cast it when saving?

E.g.:

```js
const FooSchema = new Schema({
  date: Date,
});
const Foo = mongoose.model('Foo', FooSchema);
const date = moment();
console.log(moment.isMoment(date)); //true
const foo = new Foo({date});
console.log(moment.isMoment(foo.date)); //false
```

Can the moment instance be retained and have conversion to a Date take place only when the data is saved into the database?

**Comment by vkarpov15** [comment]
You would need a custom type for that: https://mongoosejs.com/docs/customschematypes.html . That will be a useful plugin :)
