### ISSUE TITLE
Have not a database but log connect

### ISSUE THREAD

**Issue by RifeWang** [Automattic/mongoose#5117]
OS:  macOS 10.12.3

```
var db = mongoose.createConnection('mongodb://localhost:27017/cardb');
      db.on('error',console.error.bind(console,'connection error:'));
      db.once('open', function () {
          console.log('mongodb connected');
      });
```
I have not a database named cardb, but it log 'mongodb connected!'. Is that a bug?

**Comment by vkarpov15** [comment]
There's no need to explicitly create databases in mongodb, mongodb will create the db for you when you first write to it.
