### ISSUE TITLE
Ionic Factory Not Working

### ISSUE THREAD

**Issue by seothuang** [Automattic/mongoose#5118]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by seothuang** [comment]
I have an existing Ionic app that uses a factory to retrieve data from Mongoose and display on my html pages and it is working well. 
Now I created some new data in the database and I just wanted to display the new information on my app  but the factory I created does not seem to work. I received error saying that my aliments[0] is undefined.

The following are is my code. My app is able to retrieve and display information on promotions successfully. However, the new code for aliments data is not working. The healthymenuFactory gives error undefined for aliments[0].

I don't understand why my code for promotions is working but the new code for aliments is not working.
Appreciate any form of help in this please.

** The following is part of app.js **
_____________________________________________________________________________________
.config(function($stateProvider, $urlRouterProvider) {
  $stateProvider

  .state('app', {
    url: '/app',
    abstract: true,
    templateUrl: 'templates/sidebar.html',
    controller: 'AppCtrl'
  })

  .state('app.home', {
    url: '/home',
    views: {
      'mainContent': {
        templateUrl: 'templates/home.html',
        controller: 'IndexController'
      }
    }
  })
_________________________________________________________________________________________________
** The following is part of Controller.js **
_________________________________________________________________________________________________
.controller('IndexController', ['$scope', 'menuFactory', 'promotionFactory', 'corporateFactory', 'healthymenuFactory', 'baseURL', function ($scope, menuFactory, promotionFactory, corporateFactory, healthymenuFactory, baseURL) {
    
    $scope.baseURL = baseURL;
    corporateFactory.query({
            featured: "true"
        },
            function (response) {
                var leaders = response;
                $scope.leader = leaders[0];
                $scope.showLeader = true;
            },
            function (response) {
                $scope.message = "Error: " + response.status + " " + response.statusText;
            }
        );
	healthymenuFactory.query({
            featured: "true"
        },
            function (response) {
                var aliments = response;
                $scope.aliment = aliments[0];
                $scope.showAliment = true;
            },
            function (response) {
                $scope.message = "Error: " + response.status + " " + response.statusText;
            }
        );
    menuFactory.query({
            featured: "false"
        },
            function (response) {
                var dishes = response;
                $scope.dish = dishes[0];
                $scope.showDish = true;
            },
            function (response) {
                $scope.message = "Error: " + response.status + " " + response.statusText;
            }
        );
    promotionFactory.query({
        featured: "true"
    },
            function (response) {
                var promotions = response;
                $scope.promotion = promotions[0];
                $scope.showPromotion = true;
            },
            function (response) {
                $scope.message = "Error: " + response.status + " " + response.statusText;
            }
        );
}])
______________________________________________
** The following is part of services.js **
_____________________________________________
.factory('healthymenuFactory', ['$resource', 'baseURL', function ($resource, baseURL) {

            return $resource(baseURL + "aliments/:id", null, {
                'update': {
                    method: 'PUT'
                }
            });

}])

.factory('commentFactory', ['$resource', 'baseURL', function ($resource, baseURL) {

        return $resource(baseURL + "dishes/:id/comments/:commentId", {id:"@Id", commentId: "@CommentId"}, {
            'update': {
                method: 'PUT'
            }
        });

}])

.factory('promotionFactory', ['$resource', 'baseURL', function ($resource, baseURL) {
    
        return $resource(baseURL + "promotions/:id", null,  {
                'update': {
                    method: 'PUT'
                }
            });

}])
___________________________________________________________________________
** The following is part of home.html **
___________________________________________________________________________
  <ion-content>
    <div class="card">
        <div class="item item-divider">
            Cirrhosis Menu
            <span class="badge badge-assertive">{{aliment.category}}</span>
        </div>
        <div class="item item-thumbnail-left item-text-wrap">
            <img ng-src="{{baseURL+aliment.image}}" alt="Green Apple Juice">
            <h2>{{aliment.name}}</h2>
            <p>{{aliment.ingredients}}</p>
        </div>
    </div>
      <div class="card">
          <div class="item item-divider">
            This Month's Promotions
            <span class="badge badge-assertive">{{promotion.label}}</span>
          </div>
          <div class="item item-thumbnail-left item-text-wrap">
               <img ng-src="{{baseURL+promotion.image}}" alt="Uthappizza">
                <h2>{{promotion.name}} 
                <span class="badge">{{promotion.price/100 | currency}}</span></h2>
                <p>{{promotion.description}}</p>
          </div>
      </div>
______________________________________________________________________________
** The following code are from my rest server **
** The following is the schema file aliments.js **
______________________________________________________________________________
// grab the things we need
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

//add the Currency type to the Mongoose Schema types
require('mongoose-currency').loadType(mongoose);
var Currency = mongoose.Types.Currency;

// create a schema
var alimentSchema = new Schema({
    category: {
		type: String,
		required: true,
		default:'',
	},
	name: {
        type: String,
        required: true,
		default:'',
    },
    image: {
        type: String,
        required: true,
    },
    ingredients: {
        type: String,
        default: '',
    },
    steps: {
        type: String,
        default:'',
    },
    featured: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true
});

var Aliments = mongoose.model('Aliment', alimentSchema);

// make this available to our Node applications
module.exports = Aliments;
____________________________________________________________________
** The following is the code for alimentRouter.js **
____________________________________________________________________
var express = require('express');
var bodyParser = require('body-parser');
var mongoose = require('mongoose');

var Aliments = require('../models/aliments');
var Verify = require('./verify');

var alimentRouter = express.Router();
alimentRouter.use(bodyParser.json());

alimentRouter.route('/')

.get(function(req,res,next){
	
    Aliments.find(req.query, function (err, aliment) {
        if (err) next(err);
        res.json(aliment);
    });
})

.post(Verify.verifyOrdinaryUser, Verify.verifyAdmin, function(req, res, next){
	
    Aliments.create(req.body, function (err, aliment) {
        if (err) next(err);
        console.log('Aliment created!');
        var id = aliment._id;

        res.writeHead(200, {
            'Content-Type': 'text/plain'
        });
        res.end('Added the aliment with id: ' + id);
    });  
})

.delete(Verify.verifyOrdinaryUser, Verify.verifyAdmin, function(req, res, next){
	
    Aliments.remove({}, function (err, resp) {
        if (err) next(err);
        res.json(resp);
    });
});

alimentRouter.route('/:alimentId')

.get(Verify.verifyOrdinaryUser, function(req,res,next){
	
    Aliments.findById(req.params.alimentId, function (err, aliment) {
        if (err) next(err);
        res.json(aliment);
    });
	
})

.put(Verify.verifyOrdinaryUser, Verify.verifyAdmin, function(req, res, next){
	
    Aliments.findByIdAndUpdate(req.params.alimentId, {
        $set: req.body
    }, {
        new: true
    }, function (err, aliment) {
        if (err) next(err);
        res.json(aliment);
    });
	
})

.delete(Verify.verifyOrdinaryUser, Verify.verifyAdmin, function(req, res, next){
    Aliments.findByIdAndRemove(req.params.alimentId, function (err, resp) {        if (err) next(err);
        res.json(resp);
    });
}); 

module.exports = alimentRouter;
________________________________________________________________________
** The following is part of my app.js file in my rest server **
________________________________________________________________________
var index = require('./routes/index');
var users = require('./routes/users');
var dishRouter = require('./routes/dishRouter');
var promoRouter = require('./routes/promoRouter');
var leaderRouter = require('./routes/leaderRouter');
var favoriteRouter = require('./routes/favoriteRouter');
var alimentRouter = require('./routes/alimentRouter');

var app = express();

//CORS
app.use(function(req, res, next){
	res.header("Access-Control-Allow-Origin", "*");
	res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
	next();
});

app.options('*', cors()); // for preflight

// Secure traffic only
app.all('*', function(req, res, next){
    console.log('req start: ',req.secure, req.hostname, req.url, app.get('port'));
  if (req.secure) {
    return next();
  };

 res.redirect('https://'+req.hostname+':'+app.get('secPort')+req.url);
});

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());

// passport config
app.use(passport.initialize());

app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);
app.use('/users', users);
app.use('/dishes',dishRouter);
app.use('/promotions',promoRouter);
app.use('/leadership',leaderRouter);
app.use('/favorites',favoriteRouter);
app.use('/aliments',alimentRouter);

____________________________________________________________________
Node version : 6.9.2
Mongo version: 3.2.11

**Comment by varunjayaraman** [comment]
it looks like your PUT route:

```javascript
Aliments.findByIdAndUpdate(req.params.alimentId, {
    $set: req.body
}, {
    new: true
}, function (err, aliment) {
    if (err) next(err);
    res.json(aliment);
});
```
is returning a single object, not an array (since `findByIdAndUpdate` doesn't return an array but an object). So you don't want to access it as `aliments[0]`

**Comment by seothuang** [comment]
Thanks Varun for your reply.
I removed the array and the code now read:
var aliments = response;
$scope.aliment = aliments;

But it still get the undefined error.

**Comment by seothuang** [comment]
Does a change of Ionic version cause such problem?
My working code was created using Ionic 1 but the new code that is not working was created in Ionic 2.
