### ISSUE TITLE
How to add required validation when an other field has an specific value?

### ISSUE THREAD

**Issue by saeidalidadi** [Automattic/mongoose#5119]
I have a model that should have a field when there is an specific value for an other field (one-way dependency for two fields).

How this should be implemented in schema level validation?

**Comment by vkarpov15** [comment]
```javascript
new Schema({
  a: String,
  b: {
    type: String,
    required: function() { return this.a === 'test'; } // Only required if a equals 'test'
  }
});
```

**Comment by saeidalidadi** [comment]
This could be fine if added to documentation.
And also this solution could be useful:

```javascript
new Schema({
   a: String,
   b: String
})

Schema.path('b').required(function() {
  return this.a === 'test'
})

**Comment by vkarpov15** [comment]
It's in the docs: http://mongoosejs.com/docs/api.html#schematype_SchemaType-required . But will add to guide as well

**Comment by Pradeep298** [comment]
> ```js
> new Schema({
>   a: String,
>   b: {
>     type: String,
>     required: function() { return this.a === 'test'; } // Only required if a equals 'test'
>   }
> });
> ```

How can I set error "message" here? If this.a is equal to 'test' but value for b is not provided,  I want to set an error message to be thrown.

**Comment by Pradeep298** [comment]
@vkarpov15  Thanks!. Below is the simple one.

`const s = new Schema({ 
             a: String, 
             b: { type: String } });`

> @Pradeep298 see [docs](https://mongoosejs.com/docs/api.html#schematype_SchemaType-required)
> 
> ```js
> const s = new Schema({
>   a: String,
>   b: {
>     type: String
>   }
> });
> 
> s.path('b').required(function() { return this.a === 'test'; }, 'your custom message here');
> ```

@vkarpov15  Thanks!. Below is the simple one.

> const s = new Schema({
>   a: String,
>   b: {
>     type: String,
>     required: function() { return this.a === 'test'; }
>   }
> });

> > ```js
> > new Schema({
> >   a: String,
> >   b: {
> >     type: String,
> >     required: function() { return this.a === 'test'; } // Only required if a equals 'test'
> >   }
> > });
> > ```
> 
> @vkarpov15 How can I set error "message" here? If this.a is equal to 'test' but value for b is not provided, I want to set an error message to be thrown.

I got this simpler way to do this..

`required: function() [{ return this.a === 'test'; }, 'YOUR CUSTOME MSG HERE']`

**Comment by Pradeep298** [comment]
@vkarpov15  Thanks! I got this simpler way to do this.  Need to add second parameter in required validation.

`required: function() [{ return this.a === 'test'; }, 'YOUR CUSTOME MSG HERE']`
