### ISSUE TITLE
[Feature Request]New mode for "reference" and "populate". For semantic clear.

### ISSUE THREAD

**Issue by libook** [Automattic/mongoose#5120]
This is how we use reference and populate:
```javascript
const orderSchema = Schema({
  user      : { type: ObjectId, ref: 'User' },
  amount    : Number});
```

When we only need user's ID:
```javascript
Order.find();
```
Returns:
```json
{
  "user" : ObjectId("58d8e53f08f3bfb38f1c0f7d"),
  "amount" : 100
}
```

When we need user's information:
```javascript
Order.find().populate('user');
```
Returns:
```json
{
  "user" : {
    "_id" : ObjectId("58d8e53f08f3bfb38f1c0f7d"),
    "name" : "Steve",
    "role" : "miner"
  },
  "amount" : 100
}
```

Now, problem comes.
The name "user" has 2 meanings. One is "user's ID", another is "user object".

It's just ok, but not clear enough.
All I know is that I'll get an order object. But I always forget what does the "user" mean.
And these codes will get wrong:
```javascript
// Without populate.
response.body = oneOrder.user._id;
```
---

I have got an idea.
Defining schema like this:
```javascript
const orderSchema = Schema({
  user      : { type: ObjectId, ref: 'User' },
  amount    : Number}, {"strictStruct": true});
```

When we only need user's ID:
```javascript
Order.find();
```
Returns:
```json
{
  "user" : {
    "_id" : ObjectId("58d8e53f08f3bfb38f1c0f7d")
  },
  "amount" : 100
}
```

When we need user's information:
```javascript
Order.find().populate('user');
```
Returns:
```json
{
  "user" : {
    "_id" : ObjectId("58d8e53f08f3bfb38f1c0f7d"),
    "name" : "Steve",
    "role" : "miner"
  },
  "amount" : 100
}
```

How about this?

I apologize;
if there is already a way to make this;
or I made mistakes in my description.

**Comment by vkarpov15** [comment]
Thanks for the suggestion but we have an alternative way to do this using populate virtuals. 

```javascript
const orderSchema = Schema({
  userId      : { type: ObjectId },
  amount    : Number});

orderSchema.virtual('user', {
  ref: 'User',
  localField: 'userId',
  foreignField: '_id',
  justOne: true
});
```

This way `userId` will always be an object id, and 'user', if it exists, will be a doc
