### ISSUE TITLE
model.js: from version 4.x，cant do saving repeatedly in same eventtick 

### ISSUE THREAD

**Issue by linatiantamade** [Automattic/mongoose#5122]
in version 3.8.x, can do saving many times.

after the vesion, when i pushed datas to an array, there's  counts of datas as many as the times i doing saving in same tick. (my eng is so so, sorry.)

i wander why do this change?

i move the $__reset() before the collection update, and solve it.

versions: nodejs 0.10.33 mongoose 4.9.2 mongodb 3.2.7

**Comment by varunjayaraman** [comment]
@linatiantamade sorry can you show me an example? Not quite sure what you mean?

**Comment by linatiantamade** [comment]
main code:
var blogSchema = new mongoose.Schema({
  title:  String,
  oo:[{
	n:String,
	p:Number	
  }]
}, {collection:'blog'});
Blog.create([{title:'aaa1', oo:[{n:'1',p:1}]}], function(err,docs) {
	var data = docs[0];
	var oo = data.oo;
	setTimeout(function(){
		console.log("save");
		oo.push({n:'2',p:1});
		data.save();
        data.save();
        data.save();
	}, 5000);
});

there i do saving 3 times, in version 4.9.1, the result:
{title:'aaa1', oo:[{n:'1',p:1}, {n:'2',p:1}, {n:'2',p:1}, {n:'2',p:1}]}
in version 3.8.x, the result will :
{title:'aaa1', oo:[{n:'1',p:1}, {n:'2',p:1}]}

i want to know the purpose of it.

**Comment by varunjayaraman** [comment]
this looks like a bug then since it should only be adding that object to `oo` once but it looks like mongoose sees it as modified even after the first call to `.save()`

**Comment by linatiantamade** [comment]
version:
`nodejs 0.10.33
mongoose 4.9.1
mongodb 3.2.7`
The output of the last console log:

`
save
data:{"__v":0,"title":"aaa1","_id":"58dcafac13c5a515e0ee97e1","oo":[{"n":"1","p":1,"_id":"58dcafac13c5a515e0ee97e2"},{"n":"2","p":1,"_id":"58dcafb113c5a515e0ee97e3"}]}
{ '0': null, '1': [object Object], '2': 1 }
{ '0': null, '1': [object Object], '2': 1 }
{ '0': null, '1': [object Object], '2': 1 }`

**Comment by linatiantamade** [comment]
E:\workspace\n1\main>node.exe -v
v6.9.2
i run with the version v6.9.2, the output is same.

**Comment by linatiantamade** [comment]
i know then reason of diff:
data.save();
      data.save();
      data.save();

      console.log('data', data);
db.save is async operate, shold wait for save callback.

**Comment by varunjayaraman** [comment]
wow i can't believe i did that, it must have been late at night :P

Anyway, even if i do it correctly:

```javascript
const mongoose = require('mongoose');

const GITHUB_ISSUE = `gh-5122`;

const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

var blogSchema = new mongoose.Schema({
  title: String,
  oo: [{
    n: String,
    p: Number
  }]
});

const Blog = db.model('Blog', blogSchema);

Blog.remove({}, () => {
  Blog.create([{ title: 'aaa1', oo: [{ n: '1', p: 1 }] }], function(err, docs) {
    var data = docs[0];
    var oo = data.oo;
    setTimeout(function() {
      console.log("save");
      oo.push({ n: '2', p: 1 });
      data.save()
        .then(() => data.save())
        .then(() => data.save())
        .then(() => Blog.findById(data._id))
        .then(doc => console.log('doc', doc));
    }, 5000);
  });
});
```

I still get:

```
doc { _id: 58e4594717f6db75514b2ea2,
  title: 'aaa1',
  __v: 1,
  oo: 
   [ { n: '1', p: 1, _id: 58e4594717f6db75514b2ea3 },
     { n: '2', p: 1, _id: 58e4594c17f6db75514b2ea4 } ] }
```

**Comment by linatiantamade** [comment]
^_^,not coding after zero o'clock is my motto.
i'll try to find out the reason of it.
thank you for prompt reply.

**Comment by varunjayaraman** [comment]
@linatiantamade any luck?
