### ISSUE TITLE
Is there a way to use conditinal required validator with custom message?

### ISSUE THREAD

**Issue by poohitan** [Automattic/mongoose#5123]
Can I use a custom validation message while using a function for `required` attribute?

Let's pretend only John should be allowed to have no status: 
```javascript
{
    name: String
},
{
    status: String,
    required() {
        return this.name !== 'John';
    }
}
```

If I try to create a Peter without a status, I get this message: `Path status is required.`. Can I customize this message?

**Comment by vkarpov15** [comment]
Actually this is currently possible, I added docs :point_up: . Do this:

```javascript
var s = new Schema({
  userId: ObjectId,
  username: {
    type: String,
    required: [
      function() { return this.userId != null; },
      'username is required if id is specified'
    ]
  }
})
```

**Comment by poohitan** [comment]
@vkarpov15 wonderful, thanks!
