### ISSUE TITLE
`$setOnInsert` does not work correctly with custom schema type

### ISSUE THREAD

**Issue by josephktcheung** [Automattic/mongoose#5126]
I created a custom schema type to store `Point` geojson format. I used `findOneAndUpdate` and `$setOnInsert` on this custom schema type but failed, if I change from `$setOnInsert` to `$set` it works but that's not what I want as I only want to set the field when it is inserted.

```javascript
var mongoose = require('mongoose');

function Point(key, options) {
  mongoose.SchemaType.call(this, key, options, 'Point');
}

Point.prototype = Object.create(mongoose.SchemaType.prototype);

Point.prototype.cast = function(point) {
  if (!point.type) {
    throw new mongoose.Error('Point', point.type, 'point.type'); // will throw error here because `point` here is a string not an object
  }
  // type must be Point
  if (point.type !== 'Point') {
    throw new mongoose.Error(point.type + ' is not a valid GeoJSON type');
  }

  return point;
};

mongoose.connect('mongodb://localhost/test');
mongoose.Schema.Types.Point = Point;

var testSchema = new mongoose.Schema({ name: String, test: Point });
var Test = mongoose.model('Test', testSchema);

Test.findOneAndUpdate({
  name: 'a',
}, {
  $setOnInsert: {
    name: 'a',
  },
  test: {
    type: 'Point',
  },
}, {
  new: true, upsert: true,
})
  .then(function (test) {
    console.log('test', test);
  }, function (error) {
    console.log('error', error);
  });
```
This will return an `mongoose.Error` that `point` doesn't have property `type` because the parameter being casted is a string. However, if I change from `$setOnInsert` to `$set` it can be run properly. 

```javascript
Test.findOneAndUpdate({
  name: 'a',
}, {
  $setOnInsert: {
    name: 'a',
  },
  $set: {
    test: {
      type: 'Point',
    },
  }
}, {
  new: true, upsert: true,
})
```

So by tracing the error, `$set` is matched in [castUpdate.js L147](https://github.com/Automattic/mongoose/blob/0a8808547f9b04d38604337ed0b23b8779022aba/lib/services/query/castUpdate.js#L147) and therefore `castUpdateVal` is run correctly with correct parameters `castUpdateVal(Point, { type: 'Point' }, '$set')` but `$setOnInsert` does not and continue to call `walkUpdatePath` with `location.type`. Therefore, `castUpdateVal` is called with wrong parameters this time `castUpdateVal(Point, 'Point', '$setOnInsert', 'type')`.

**What is the expected behavior?**
Expected `$setOnInsert` to work correctly with this custom schema type field same as `$set`.
**Please mention your node.js, mongoose and MongoDB version.**
node.js - 7.2.0
mongoose - 4.9.2
MongoDB - 3.4.0

**Comment by varunjayaraman** [comment]
@josephktcheung this doesn't return a mongoose error for me and logs:

```
test { _id: 58dc7a4be5c29a342bf881ba,
  name: 'a',
  __v: 0,
  test: { type: 'Point' } }
```

**Comment by josephktcheung** [comment]
Oh I make a mistake in the script, the following is the correct one:

```javascript
var mongoose = require('mongoose');

function Point(key, options) {
  mongoose.SchemaType.call(this, key, options, 'Point');
}

Point.prototype = Object.create(mongoose.SchemaType.prototype);

Point.prototype.cast = function(point) {
  console.log('point?', point, typeof point);
  if (!point.type) {
    throw new mongoose.Error('Point', point.type, 'point.type');
  }
  // type must be Point
  if (point.type !== 'Point') {
    throw new mongoose.Error(point.type + ' is not a valid GeoJSON type');
  }

  return point;
};

mongoose.connect('mongodb://localhost/test');
mongoose.Schema.Types.Point = Point;

var testSchema = new mongoose.Schema({ name: String, test: Point });
var Test = mongoose.model('Test', testSchema);

Test.findOneAndUpdate({
  name: 'a',
}, {
  $setOnInsert: {
    name: 'a',
    test: {
      type: 'Point',
    },
  },
}, {
  new: true, upsert: true,
})
  .then(function (test) {
    console.log('test', test);
  }, function (error) {
    console.log('error', error);
  });
```

**Comment by josephktcheung** [comment]
I put ` test: { type: 'Point' }` outside of `$setOnInsert`, it should be inside the `$setOnInsert` instead

**Comment by josephktcheung** [comment]
If you try the second script it should return error, sorry for the mistake.

**Comment by varunjayaraman** [comment]
Cool, thanks, looks like a bug
