### ISSUE TITLE
Virtual nested query question

### ISSUE THREAD

**Issue by zhaozhiming** [Automattic/mongoose#5127]
HI,
I have some Schema like this:
```js
const user = Schema({
  uid: String,
  group: ObjectId,
}, { toJSON: { virtuals: true } });

const group = Schema({
  name: String,
}, { toJSON: { virtuals: true } });

const customer = Schema({
  owner: String,
}, { toJSON: { virtuals: true } });

mongoose.model('User', user);
mongoose.model('Group', group);
mongoose.model('Customer', customer);

customer.virtual('ownerDetail', {
  ref: 'User',
  localField: 'owner',
  foreignField: 'uid',
  justOne: true,
});
// I try this way to find ownerGroup but failed
customer.virtual('ownerGroup', {
  ref: 'Group',
  localField: 'ownerDetail.group',
  foreignField: '_id',
  justOne: true,
});
```
I want to find customer with owner detail and owner group, it will join 2 foreign collection to find the info.
Is there a way to find all info I need in one query? Thanks.

Mongoose version: 4.8.1
Mongodb version: 3.4.2
node version: 6.9.2

**Comment by varunjayaraman** [comment]
@zhaozhiming sorry for the late reply. You can include a virtual populate as a populate option in your query. Just treat it like a normal populate when you specify the fields to populate
