### ISSUE TITLE
circular populate involving virtual ref is not working

### ISSUE THREAD

**Issue by mecp** [Automattic/mongoose#5128]
**Do you want to request a *feature* or report a *bug*?**
It seems to be a bug

**What is the current behavior?**
Circular populate for virtual is not working.

**If the current behavior is a bug, please provide the steps to reproduce.**
Circular virtual ref Population is not working for me.

```js
var ASchema = new Schema({
    title: { type: String, required: true, trim : true },
}, {
    toObject: { virtuals: true },
    toJSON: { virtuals: true }
});

ASchema.virtual('brefs', {
  ref: 'BSchema',
  localField: '_id',
  foreignField: 'arefs'
});

var BSchema = new Schema({
    arefs: [{ type: ObjectId, required: true, ref : 'A' }],
});

var a = db.model('A', ASchema);
var b = db.model('B', BSchema);

var res = await a.find({}).populate([{ 
  path: 'brefs', // this gets populated
  model: 'B', 
  populate: [{
    path: 'arefs', // <---- this is returned as [ObjectId], not populated
    model: 'A',
    populate: []
  }]
}]).exec();
```

It returns array of IDs but not populated documents.

**What is the expected behavior?**
`a.brefs.arefs` should fetch populated 'a' documents for 'arefs'.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 6.9.1
Mongodb: 3.4.6
Mongoose: 4.9.1

Seems related to [#4631](https://github.com/Automattic/mongoose/issues/4631)

**Comment by varunjayaraman** [comment]
Hm this must be a bug with virtual nested populate

**Comment by mecp** [comment]
Thanks Valeri (@vkarpov15) for the fix. But I noticed that in the populated `a.brefs.arefs` documents `brefs` are returned as `null` not as array of `ObjectId`.

**Comment by mecp** [comment]
@vkarpov15 We could add this assertion to the test.

```js
assert(doc.brefs[0].arefs[0].brefs.indexOf(doc.brefs[0]._id) > -1);
```
