### ISSUE TITLE
Model init event? 

### ISSUE THREAD

**Issue by wertlex** [Automattic/mongoose#5135]
Hey!

Do Model need `init`/`ready` event? Once Model instantiated it is not always ready for use. For ex. if one need index-based uniqueness Model cannot be used up to the time when index will be really built (and there is `index` event for that).

Will it by handy to add one more event named `ready` which is emitted when it is safe to use Model? (In case with user provided index - when `index` emitted, if no index used - right after model instantiation)

**Comment by varunjayaraman** [comment]
mongoose models do actually emit an `init` event so you can listen for it. Here's the code for `Model.init()`:

```javascript
Model.init = function init() {
  if ((this.schema.options.autoIndex) ||
      (this.schema.options.autoIndex === null && this.db.config.autoIndex)) {
    this.ensureIndexes({ __noPromise: true, _automatic: true });
  }

  this.schema.emit('init', this);
};
```
