### ISSUE TITLE
$replaceRoot returns array instead of document

### ISSUE THREAD

**Issue by thomasdingemanse** [Automattic/mongoose#5136]
I'm using the latest version of Mongoose, which seems to handle $replaceRoot operations in aggregation queries differently than the native MongoDB driver. This is a feature request.

I ran the following query on my database using the MongoDB driver (through the mongo shell):

`db.merchants.aggregate({$unwind: '$shops'}, {$replaceRoot: {newRoot: "$shops"}}, {$match: {nameSlug: "example-shop-nameslug"}})`

This returns a single document with that particular shop's properties, which is the expected result.

In mongoose on the other hand, I tried to run the following (equivalent) query:

`Merchant.aggregate({$unwind: '$shops'}, {$replaceRoot: {newRoot: "$shops"}}, {$match: {nameSlug: "example-shop-nameslug"}}, function(err, doc) { console.log(doc); });`

This returns an array with the shop as the first (and only) element. I have to use shop[0] to access its properties.

It's not a big problem of course (this is probably one of the issues with the smallest impact and the easiest workaround), but this feature would make the usage of the aggregation framework in Mongoose more intuitive and clear.

I'm using Node.js 5.9.0, MongoDB 3.4.3 and Mongoose 4.9.2.

**Comment by vkarpov15** [comment]
So mongodb shell !== [native mongodb driver](http://npmjs.org/package/mongodb). This isn't limited to `$replaceRoot`, `aggregate()` will always give you an array. Thanks for the suggestion but unless there's a lot of demand I don't think this is a very valuable feature to add.
