### ISSUE TITLE
How to validate values before running queries?

### ISSUE THREAD

**Issue by saeidalidadi** [Automattic/mongoose#5137]
Is there any way to validate query values ?
 I have a static method as `findByServiceNumber`
```javascript
// Controller function
function create(req, res, next) {
  UserModel.findByServiceNumber({ service_no: req.service_no }).then(...)
  ...
}
```
So what is the right way to encapsulate the validation inside the static method by using the validation of `service_no` which I have been provided in schema of `User` model?

**Comment by varunjayaraman** [comment]
are you saying you want to validate the params you pass to a query, as in to check whether  you are querying for a path on the schema that actually exists? Or do you mean something else?

**Comment by saeidalidadi** [comment]
Yeah, existence and type of the params, like all validations.

**Comment by varunjayaraman** [comment]
at the moment no, but I believe something similar is in the pipeline for 5.0. @vkarpov15 would have more info

**Comment by vkarpov15** [comment]
Here's a potential idea: how about a `Model.validatePath()` function, so you could do something like:

```javascript
UserModel.validatePaths('service_no', req.service_no).
  then(service_no => UserModel.findByServiceNumber(service_no));
```

**Comment by vkarpov15** [comment]
I did some work to implement `validatePaths()` but it unfortunately adds yet another context that custom validator functions need to run in. This'll add a lot of headache for plugin maintainers. Need to think more about how we can support this using the existing update validators paradigm so I'm pushing this back.

**Comment by vkarpov15** [comment]
See [`Model.validate()`](https://mongoosejs.com/docs/api/model.html#model_Model.validate)
