### ISSUE TITLE
mongodb returns empty array when queried with params in mongoose

### ISSUE THREAD

**Issue by myquery** [Automattic/mongoose#5140]
this is my package.json file

`{
  "name": "gradify",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "dependencies": {
    "body-parser": "^1.17.1",
    "cors": "^2.8.1",
    "express": "^4.15.2",
    "express-jwt": "^5.1.0",
    "http": "0.0.0",
    "jsonwebtoken": "^7.3.0",
    "mongoose": "^4.9.2",
    "path": "^0.12.7"
  },
  "devDependencies": {
    "nodemon": "^1.11.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "nodemon server.js"
  },
  "keywords": [
    "laundry",
    "drycleaners"
  ],
  "author": "Ibe Arua",
  "license": "ISC"
}
`

then my schema:
`var mongoose = require('mongoose');
//Define a schema
var Schema = mongoose.Schema;

var CitySchema = new Schema({
    
    state: String,
    alias: String,
    lga: String,
    area : String,
    area_alias: String,
    zipcode: [{type: String}],
    street: [{type: String}]
      
});

var CityItem = mongoose.model('city_areas', CitySchema )
module.exports = CityItem;`

//api to mongodb:
`router.get('/getstateareas/:areas', (req, res) =>{
    let areas = req.params.areas
    CityItem.find({area: areas})
            .exec((err, data) => {
                if(err){
                    res.status(500).send(err)
                }else{
                    res.json(data)
                    console.log(data)
                }
                }) 
})
`
the data at mongolab
{
    "_id": {
        "$oid": "58de6b1f734d1d01a2392d12"
    },
    "state": "Federal Capital Territory",
    "alias": "abuja",
    "lga": "Abuja Municipal",
    "area": "Central Business District",
    "area_alias": "central_business_district",
    "zipcode": "900211",
    "street": [
        "2nd Avenue",
        "3 Avenue",
        "4th Avenue",
        "Abuja Dr",
        "Ahmadu Bello Way",
        "Constitution Road",
        "Hospital Avenue",
        "Independence Avenue",
        "Inner Express (N) Way",
        "Mohammed Buhari Way",
        "North Transit Way",
        "Northern Express Way",
        "Olusegun Obasanjo Way",
        "Shehu Shagari Way",
        "South Transit Way",
        "Tafawa Balewa Way"
    ]
}

I just  need to return the area of the collection, what am I doing wrong?
any help please!

**Comment by varunjayaraman** [comment]
are you saying that it's not finding any documents based on those params? What happens when you `console.log` `req.params.areas`?

**Comment by myquery** [comment]
@varunjayaraman, i consoled req.params.areas but it just showed 'areas'. my thought on this is that mongoose can't possibly figure out how to query for a property in a mongodb collection because the parameter: req.params.areas supplied to the find function does not tell mongodb to filter out  the areas from the collection unlike in sql where a similar statement might read select * collection where area =req.params.areas( this is just for demonstration purpose), in this case req.params.areas is ambiguous that is why mongodb returned empty array. unlike req.query where supplied params is actually a value that mongodb can relate to. my workaround to this issue was to find all documents and did a forloop to get the area per document. please somebody should quote me wrong.

**Comment by varunjayaraman** [comment]
@myquery `req.params.areas` is a param string. Are you trying to treat it as an array so you can do a mongodb `$in` operation?

**Comment by myquery** [comment]
@varunjayaraman nope not trying to treat it as an array, it is a property in the mongodb db object. my assumption is that such operation cannot be performed at the db level rather at the application level because there is nothing relating `req.params.areas` to either mongodb object or mongoose schema such as telling mongodb i want all  the area in the collection. if i can recall i have actually queried mongodb before by declaring a parameter on the route but i can't figure out how i did it and no backup as my laptop got lost. there must a way to perform such operation at the db level

**Comment by varunjayaraman** [comment]
i see what you're asking for now: in mongoose you can use `.select()`:

```javascript
CityItem.find({ area: areas }).select('area')
```
