### ISSUE TITLE
Always pass next() to pre hook regardless of function arity

### ISSUE THREAD

**Issue by Earthstar** [Automattic/mongoose#5148]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you use _.partial to partially apply arguments to a function, then use that function as a pre hook, you get the error `"Your pre must have a next argument -- e.g., function (next, ...)"`. See: https://github.com/vkarpov15/hooks-fixed/blob/master/hooks.js#L58. 

This is because _.partial does not set function.length, which is behavior that the lodash maintainers do not intend to change. See: https://github.com/lodash/lodash/issues/2248. 

I am given to believe that function.length is an unreliable value now that default parameters exist. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length

**If the current behavior is a bug, please provide the steps to reproduce.**

```
function hookWrapper(hookFunction, next) {
	// do some stuff

	hookFunction.call(this, next);
}

function hookFunction(next) {
	// do some stuff
	next();
}

ModelSchema.pre('save', _.partial(hookWrapper, hookFunction));
```

**What is the expected behavior?**
Arbitrarily-bound functions can be used as pre hooks.

**Please mention your node.js, mongoose and MongoDB version.**
Node 4.3.1
mongoose 4.3.7 (relevant code is the same on latest tag 4.9.3)
MongoDB version n/a

**Comment by varunjayaraman** [comment]
I'm labelling this a discussion, I don't think it's really a bug.

I've created a full repro script:

```javascript
const mongoose = require('mongoose');
const _ = require('lodash');
const co = require('co');

mongoose.Promise = global.Promise;

exec()
  .then(() => {
    console.log('ran successfully');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
    process.exit(2);
  });

function exec() {
  return co(function* () {
    const schema = new mongoose.Schema({
      name: String
    });

    function hookWrapper(hookFunction, next) {
      // do some stuff

      hookFunction.call(this, next);
    }

    function hookFunction(next) {
      // do some stuff
      next();
    }

    schema.pre('save', _.partial(hookWrapper, hookFunction));

    const db = mongoose.createConnection(`mongodb://localhost:27017/gh-5148`);

    const Model = db.model('Model', schema);
    yield Model.remove
    yield Model.create({ name: 'Test' });
  });

}

```

**Comment by vkarpov15** [comment]
Yeah positional args are very error prone. Although the default arguments point is moot in the case of mongoose, this is a valuable suggestion. I opened up a separate issue :point_up: to track

**Comment by vkarpov15** [comment]
On second thought I just changed the title of this one so I can better remember what this issue is about.

**Comment by Earthstar** [comment]
In case someone else runs into the same issue, I was able to get around the function arity check by "manually" partially applying the function, as so:

```
function hookWrapper(callback) {
    return function(next) {
        // do stuff
        return callback.call(this, next);
    };
}

function hookFunction(next) {
    // do some stuff
    next();
}

schema.pre('save', hookWrapper(hookFunction));
```

**Comment by vkarpov15** [comment]
This was fixed in Mongoose 5, below script works without error:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh5148`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String });
  schema.pre('save', function() {
    console.log('foo');
  });
  const Model = mongoose.model('Test', schema);

  await Model.create({ name: 'foo' });
}
```
