### ISSUE TITLE
Automatic pluralizing of collection names incorrect for "human"

### ISSUE THREAD

**Issue by dargue3** [Automattic/mongoose#5149]
**What is the current behavior?**
When creating a new model called "Human", the collection name inside mongoDB gets pluralized to "humen".

**Steps to reproduce**
```javascript
var HumanSchema = new Schema({
  name: String,
  age: Number
})

var HumanModel = mongoose.model('Human', HumanSchema)
```

**Expected Behavior**
A collection with the name of "humans"

**Relevant package versions**
Using mongoose `v 4.9.3`, node `v 6.9.2` and MongoDB `v 3.4.3`.

I recognize this is probably an issue with a _different_ open-source repo that handles pluralization of words. If someone can point me towards where that is, I could take the issue up with them.

**Comment by varunjayaraman** [comment]
So this is a problem with the `exports.pluralization` array of `regexes` in `mongoose/lib/utils.js`:

```javascript
exports.pluralization = [
  [/(m)an$/gi, '$1en'],
  [/(pe)rson$/gi, '$1ople'],
  [/(child)$/gi, '$1ren'],
  [/^(ox)$/gi, '$1en'],
  [/(ax|test)is$/gi, '$1es'],
  [/(octop|vir)us$/gi, '$1i'],
  [/(alias|status)$/gi, '$1es'],
  [/(bu)s$/gi, '$1ses'],
  [/(buffal|tomat|potat)o$/gi, '$1oes'],
  [/([ti])um$/gi, '$1a'],
  [/sis$/gi, 'ses'],
  [/(?:([^f])fe|([lr])f)$/gi, '$1$2ves'],
  [/(hive)$/gi, '$1s'],
  [/([^aeiouy]|qu)y$/gi, '$1ies'],
  [/(x|ch|ss|sh)$/gi, '$1es'],
  [/(matr|vert|ind)ix|ex$/gi, '$1ices'],
  [/([m|l])ouse$/gi, '$1ice'],
  [/(kn|w|l)ife$/gi, '$1ives'],
  [/(quiz)$/gi, '$1zes'],
  [/s$/gi, 's'],
  [/([^a-z])$/, '$1'],
  [/$/gi, 's']
];
```
The plan is to deprecate this though and to use a 3rd party library dedicated to pluralization. So for now, you can pass the collection name as the 3rd parameter to `mongoose.model()`:

```javascript
var HumanModel  = mongoose.model('Human', HumanSchema, 'humans');
```
