### ISSUE TITLE
findOne returns empty doc, but data in doc._doc

### ISSUE THREAD

**Issue by murvinlai** [Automattic/mongoose#516]
Here is what my script look like:

UserModel.findOne(
                {userId:'xx123456'},
                function(err, doc) {
                    if (err) {
                        next(err);
                    } else if (! doc) {
                        next( 'findOne: User not found.  Input: ' + JSON.stringify(data)));
                    } else {
                        next(null, {status:true, 
                            message:'User is found' ,
                            data:doc
                        });
                    }
                }
        );

When I run unit test in command line, doc is the mongo Document. e.g. {userId:'xx123456', name:"My Name' }

However, when I make a web app calling this function passing exactly the same userId, doc.userId is empty.  However, I can find the data in doc._doc   why is that?

I have another site that return the full document from "doc" normally.   Why there is inconsistency...

**Comment by a-m-dev** [comment]
`toObject()` or `toJSON()` both works, and it returns the final result of any operation on model, thank you!
