### ISSUE TITLE
bug: SubDocument Array issue while deleting

### ISSUE THREAD

**Issue by harshaldhake** [Automattic/mongoose#5167]
model 

user: {
name : String,
address: String,
comments: [comments]
}

comments:[
    {
      comment: String,
      rating: String
    }
]

I am trying to remove a document from subdocument array. I am using below mongoose code which just say document match but do not update.
Mongoose ( below code is called from hapi Route)
============
  Mongoose.model('User')
        .update({ "_id": Mongoose.Types.ObjectId(request.query.id) }, { $pull: { "comments": { "_id": Mongoose.Types.ObjectId(request.query.commentId) } } }, { new: true })
        .then(user => reply(user))
        .catch(err => reply(Boom.badImplementation('Unable remove comment', err)));

swagger o/p 👍 
{
  "ok": 1,
  "nModified": 0,
  "n": 0
}

but when I fire query directly on mongoose shell , subdocument is removed.

Mongo Shell Output/
=================
> db.users.update({ "_id": ObjectId("58ab3378b13697fb451890d1")}, { $pull : { "comments" :  {"_id": ObjectId("58f1c7983b59f11dc7ab8724") }} },{new:true} )
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

**Do you want to request a *feature* or report a *bug*?**
--Bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

as given above

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB shell version: 3.0.6
node: v7.8.0
"mongoose": "^4.8.1",

**Comment by varunjayaraman** [comment]
This works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `issue`


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

    const commentSchema = new mongoose.Schema({
      comment: String,
      rating: String
    });

    const schema = new mongoose.Schema({
      name: String,
      address: String,
      comments: [commentSchema]
    });

    const Model = db.model('Model', schema);

    yield Model.remove({});
    const doc = yield Model.create({
      comments: [
        { comment: 'test', rating: 'test' }
      ]
    });

    const update = yield Model.update(
      { _id: doc._id }, 
      { $pull: { comments: { _id: doc.comments[0]._id } } });
    console.log(update);
  });
}


This gives me the following output:

```
{ n: 1, nModified: 1, ok: 1 }
```

As a sidenote, dont call the mongo id constructor on `request.query.id`. I'm not sure what that string looks like, but I'm guessing its causing an issue with your query. Also you can't pass `{ new: true }` to `Model.update()`, only to `Model.findOneAndUpdate()` or `Model.findByIdAndUpdate()`
