### ISSUE TITLE
Model.bulkWrite Documentation Errata

### ISSUE THREAD

**Issue by p-hebert** [Automattic/mongoose#5168]
The [Model.bulkWrite documentation](http://mongoosejs.com/docs/api.html#model_Model.bulkWrite) has two errors in the description:

a. Model.bulkWrite _is not a function_. In effect calling Model.bulkWrite results in a `TypeError: is not a function`. I suggest the following correction:
    `Model.bulkWrite` => `Model.collection.bulkWrite`

b. As per the [MongoDB API](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#bulkwrite-write-operations-deleteonemany), the `deleteOne`, `deleteMany`, `updateOne`, `updateMany`, `replaceOne`, and `replaceMany` operation requires to have a property `filter` which acts as the filter for the query. I suggest the following correction:
```
Character.bulkWrite([
  ...
  {
    deleteOne: {
      { name: 'Eddard Stark' }
    }
  }
]).then(handleResult);
```
to
```
Character.bulkWrite([
  ...
  {
    deleteOne: {
      { filter: { name: 'Eddard Stark' } }
    }
  }
]).then(handleResult);
```

This was found while developing my website, and documented on this [StackOverflow issue](http://stackoverflow.com/questions/43426782/mongo-bulkwrite-from-json-file/43437898#43437898).

Thank you for your good work!
Cheers,
p-hebert

**Comment by varunjayaraman** [comment]
Thanks for the issue! 

For the first part, `Model.bulkWrite()` is a function in mongoose:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5168`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String
    });


    const Model = db.model('Model', schema);
    yield Model.remove({});
    yield Model.bulkWrite([
      { insertOne: { document: { name: 'Test 1' } } },
      { insertOne: { document: { name: 'Test 2' } } }
    ]);
  });
}
```

That shouldn't throw an error for you. If it does, i'd like to see how you're doing it.

As for the second issue, I agree that the `deleteOne` docs are off. We'll add that for the next milestone

**Comment by p-hebert** [comment]
Thanks for the test script, really time saving!
When running your exact script using `node mongo.js`, I get the following:
```
Error: TypeError: Model.bulkWrite is not a function
TypeError: Model.bulkWrite is not a function
    at /home/p-hebert/app_dev/www/futureboy/website/server/mongo.js:27:17
    at next (native)
    at onFulfilled (/home/p-hebert/app_dev/www/futureboy/website/server/node_modules/co/index.js:65:19)
```
My specs are the following:
```
"node": "v6.10.0",
"npm": "3.10.10",
"mongoose": "4.6.5",
"mongod": "v3.4.1",
```
My mongodb image runs from docker's [mongo:latest](https://github.com/docker-library/mongo/blob/9914fd4e7967c32ad79710b08e4a21f4f68239f9/3.4/Dockerfile), while node runs in my current environment, Ubuntu Xenial Xerus 16.04.

Let me know if you have any question

**Comment by varunjayaraman** [comment]
Ah its your mongoose version, try latest

**Comment by p-hebert** [comment]
Updated to latest (@4.9.5) - Issue is effectively solved!

Thanks for the help!

Cheers,
p-hebert

**Comment by vkarpov15** [comment]
Thanks for reporting this issue. `bulkWrite()` is [new in 4.9.0](https://github.com/Automattic/mongoose/blob/master/History.md#490--2017-03-13) so make sure you use at least that version if you want to use it. The example is fixed and the fix will be deployed with the next release :+1:

**Comment by somnathpanja** [comment]
Mongoose : 4.10.8 & Mongodb: v3.4.9 is also have the same issue. I can see it in our production.

Test case: If mongoose connection is lost suddenly and autoReconnect option is set to false then model.bulkWrite() is undefined. 
Expectation: bulkWrite() should be always defined. If connection is lost bulkWrite() should throw an error over callback.

**Comment by vkarpov15** [comment]
@somnathpanja can you please provide code samples?

Also, I would strongly recommend not disabling `autoReconnect`. That option has a lot of impact on driver internals and should only be used if you're confident managing the connection pool yourself.
