### ISSUE TITLE
Asynchronous Setters/Getters

### ISSUE THREAD

**Issue by NuckChorris** [Automattic/mongoose#517]
This is important for anyone using bcrypt, including [mongoose-auth](https://github.com/bnoguchi/mongoose-auth), which currently relies on synchronous bcrypt functions, which block the entire server while they work.

``` javascript
schema.virtual('password').get( function () {
    return this._password;
}).set( function (password) {
    this._password = password;
    var salt = this.salt = bcrypt.gen_salt_sync(10);
    this.hash = bcrypt.encrypt_sync(password, salt);
});
```

versus the asynchronous form

``` javascript
schema.virtual('password').get( function () {
    return this._password;
}).set( function (password, done) {
    var _this = this;
    bcrypt.gen_salt(10, function(err, salt) {
        bcrypt.encrypt(password, salt, function(err, hash) {
            _this._password = password;
            _this.salt = salt;
            done();
        });
    });
});
```

_(speaking of which, that is an awful authentication module, at least in the password-auth department &mdash; I know I wouldn't trust it.)_

**Comment by kilianc** [comment]
I am currently using validators as setters to get desidered behavior, but those just run before save, not when you "set" a property. If you think about it you're asking to make `doc.foo = 'bar'` async which makes no sense. If I am not wrong setters are also run on `new Foo` so even more impossible to make it async.

On the other end `Foo.create()` it's async already and there it comes the frustration :)

**Comment by kilianc** [comment]
@neverfox I usually add a `.methods.compute()` which returns a promise and does async settings stuff. Then I call validators. You can also use validators as I said above but doing so you lose the ability to have the set value in memory before saving. Having `var doc = new Foo(data)` and `yield doc.compute()` does it. I even use to wrap those into a `.statics.safeCreate()` method where I cleanup protected fields and do async stuff.

**Comment by hfournier** [comment]
@NuckChorris I know this is an old thread, but did you ever figure out a working solution for this? I'm writing my API in TypeScript in NestJS and I've run into the same thing, were I thought I would hide the salting and hashing code in the schema and simply assign the password to the property, but I can't get async/await to work and bcrypt calls end up executing after data as saved to the DB. Thanks.

**Comment by vkarpov15** [comment]
@hfournier without code samples we can't really help.

Although [this article on passwords in REST APIs might help](https://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis). TLDR; separate `AuthenticationMethod` model is usually the way to go, instead of storing a password hash directly on the user.
