### ISSUE TITLE
mongoose 4.8.3 broke $pullAll for _id-less subdocs

### ISSUE THREAD

**Issue by Sebmaster** [Automattic/mongoose#5170]
Continued from #5164, sorry for not realizing this earlier...

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

$pullAll does not remove the requested document.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
var mongoose = require('.');
var Promise = require('bluebird');

mongoose.connect('mongodb://localhost/test', {debug: true});
mongoose.set('debug', true)

var Cat = mongoose.model('Cat', {
  name: String, props: [{
    name: String
  }]
});

(async function () {
  var kitty = new Cat({ name: 'Zildjian', props: [{ name: 'invalid' }, { name: 'abc' }] });
  await kitty.save();

  await Promise.fromNode((next) => Cat.update({ _id: kitty._id }, { $unset: { 'props.0._id': true } }, next))

  kitty = await Cat.findById(kitty._id);
  console.log(kitty.props)

  await Promise.fromNode((next) => Cat.update({ _id: kitty._id }, { $pullAll: { props: [{ name: 'invalid' }] } }, next))

  kitty = await Cat.findById(kitty._id);
  console.log(kitty.props)
}());
```

**What is the expected behavior?**

Second console.log should just output 1 element.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose 4.9.5
node 7.7.1
mongodb 3.2

**Comment by varunjayaraman** [comment]
This actually isn't a bug, you're using `$pullAll` incorrectly. `$pullAll` matches values in an array, but no 2 objects are equal in `javascript`, so it won't consider the object equal.

You have to use `$pull` if you want to match on an embedded doc:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5170`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const catSchema = new mongoose.Schema({
      name: String, props: [{
        name: String
      }]
    });


    const Cat = db.model('Cat', catSchema);

    yield Cat.remove({});
    const kitty = yield Cat.create({ name: 'Zildjian', props: [{ name: 'invalid' }, { name: 'abc' }] });

    yield Cat.findByIdAndUpdate(kitty._id, { $pull: { props: { name: 'invalid' } } });

    const updatedKitty = yield Cat.findById(kitty._id);
    console.log(updatedKitty.props);
  });
}
```

**Comment by Sebmaster** [comment]
Two things:

1. This works fine in mongoose 4.8.2. I think what's happening is that because of the cast introduced in 4.8.3, mongoose adds a (new) subdoc-_id to the $pullAll, making the objects not match.
2. Doing the same query with Cat.collection.update() (that is, via the native mongodb-driver, bypassing mongoose) also works fine.

So this is definitely a thing mongoose has changed and it worked fine before.

**Comment by vkarpov15** [comment]
This is definitely worth investigating a little more, I'll look into it

**Comment by vkarpov15** [comment]
I looked into it a little more and looks like this is a result of #4960. I think the original behavior was a bug because mongoose was not casting the subdoc in the pull op: `Cat.update({ _id: kitty._id }, { $pullAll: { props: [{ name: 'invalid' }] } })` . Just because you unset the `_id` in the doc doesn't tell mongoose that you don't want an `_id` for each document in the `props` array. The below code works as expected:

```javascript
var mongoose = require('mongoose');
var Promise = require('bluebird');

mongoose.connect('mongodb://localhost/test', {debug: true});
mongoose.set('debug', true)

var Cat = mongoose.model('Cat', {
  name: String, props: [new mongoose.Schema({
    name: String
  }, { _id: false })] // <-- make it so that mongoose knows `props` subdocs don't have an `_id`
});

(async function () {
  var kitty = new Cat({ name: 'Zildjian', props: [{ name: 'invalid' }, { name: 'abc' }] });
  await kitty.save();

  // Below is no longer necessary, no _id
  //await Cat.update({ _id: kitty._id }, { $unset: { 'props.0._id': true } })

  kitty = await Cat.findById(kitty._id);
  console.log(kitty.props)

  await Cat.update({ _id: kitty._id }, { $pullAll: { props: [{ name: 'invalid' }] } })

  kitty = await Cat.findById(kitty._id);
  console.log(kitty.props)
}());
```
