### ISSUE TITLE
Schema alias option

### ISSUE THREAD

**Issue by rocketspacer** [Automattic/mongoose#5177]
Are you guys accepting pull requests? I want to add schema alias option feature
```
var FooSchema = mongoose.schema({
  bar: { type: String, alias: 'baz' }
});
```

Basically, the only thing I do is read this option out and create virtual properties. There was some guy at where I work who wrote a fork that does this. But the fork is really obsolete now, merging it is quite troublesome, too many conflicts.

The fork is creating troubles for us as things upgrade. So we plan to reuse his logic and merge it to official mongoose, so we can both cooperate with our current code while using the latest mongoose.

Do you have any suggestion to where I should start? Which file should I put the changes in?

**Comment by vkarpov15** [comment]
#5184
