### ISSUE TITLE
Can't figure out how to use strict

### ISSUE THREAD

**Issue by randyhill** [Automattic/mongoose#5179]
I'm trying to create a Schema where the email field is always unique.

```
var contactSchema = mongoose.Schema({
    firstName: {
        type: String,
        required: true
    },
    lastName: {
        type: String,
        required: true
    },
    email: {
        type: String,
        unique: true,
        required: true
    },
    phone: {
        mobile: String,
        work: String
    },
    auditTrail: {created: Date, modified: Date, deleted: Date}
});
```

I then create and save a contact this way.

```
const uri = "mongodb://localhost/test";
var db = mongoose.createConnection(uri, {server: {poolsize: 2000}});   
var ContactModel = db('Contact', contactSchema);
    var newContact = new ContactModel(req.body);
    newContact.save(function (err) {
        if (err) {
```

Save works fine, but if I try to save a contact with a duplicate email field I get no error, and the contact is never saved to the database. In order to test whether the problem was Mongoose returning before Mongo raised a duplicate error, I switched to using the safe option when I create the Schema.

`var newContact = new Contacts(req.body, {safe: true});`

With the safe option saving the contact always produces an error, "document must have an _id before saving", and never writes to the database. When I look at the created newContact it doesn't have an _id, though it has one if created without the safe option. I actually tried to use "strict" instead, but I get same error.

This was with mongoose version 4.9.5, and Mongo 3.4.3.

**Comment by varunjayaraman** [comment]
safe is on by default for all mongoose schemas.

Can you post a repro example for how you're using strict?

**Comment by randyhill** [comment]
Same way.

var newContact = new Contacts(req.body, {strict: true});

So it appears I'm just mis-using the API here?

**Comment by varunjayaraman** [comment]
Ah it seems you are onto something. So `strict` is on by default in mongoose, but it seems like if you pass an option object as `{ strict: true }`, it wont automatically put the `_id` on the document and so it'll throw an error when you try to save to the db.

Here's a repro script with the options param:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5179`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String
    });


    const Model = db.model('Model', schema);

    yield Model.remove({});

    const doc = new Model({ name: 'Test' }, { strict: true });
    console.log(doc._id); // should not be undefined
    yield doc.save();
  });
}
```

But this seems to work:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5179`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String
    });


    const Model = db.model('Model', schema);

    yield Model.remove({});

    const doc = new Model({ name: 'Test' }, true);
    console.log(doc._id); // this is defined: 58fe936a6386a037ece0d4a3
    yield doc.save();
  });
}
```

**Comment by vkarpov15** [comment]
@varunjayaraman the issue is that the 2nd param to the `Model()` constructor in your example is *not* `options`, but the selected fields. `new Model({ name: 'Test' }, { strict: true })` means create a new doc with only the `strict` field selected. `strict` is an option for _schemas_ and _queries_, not _models_.

As for OP's problem, `unique` creates a unique index, so you need to wait for the index to be created. `Contact.on('index', err => { /* index done building or error occurred */ })` . The better approach for production environments is to just create the unique index in the mongo shell though, mongoose is really not meant to be an index management solution.

Need to add more docs about this

**Comment by randyhill** [comment]
Thanks @vkarpov15!
