### ISSUE TITLE
mongoose 3.8.1 not creating indexes with mongo 3.4.3 node version is 0.10.33

### ISSUE THREAD

**Issue by morwalz** [Automattic/mongoose#5180]
I tried to log the error.  Following is the error

>  MongoError: The field 'safe' is not valid for an index specification.
>  Specification: { ns: "iseeit.deals", key: { name.displayValue: 1 }, 
>  name: "name.displayValue_1", background: true, safe: null, unique: false

**Comment by varunjayaraman** [comment]
can you post a full repro script please? This isn't very helpful without seeing your schema and how you define the index

**Comment by morwalz** [comment]
Here is my schema. It is very normal. I debugged the code of moongoose. moogose put safe: null without setting it. is there any way to remove this ?
`var dealSchema = mongoose.Schema({
    displayId: {type: String},
    createdOn: {type: Number, default: 0},
    attributes: [
        {
            linkedAttributeId: {type: String},
            explanatoryText: {type: String},
            selectedValues: [Schema.Types.ObjectId],
            textValue: {type: String},
            numberValue: {type: Number}
        }
    ],
    convertedOn: {type: Number, default: 0},
    leadCreatedOn: {type: Number, default: 0},
    lead: {type: Schema.Types.ObjectId, ref: 'Lead'},
    lastUpdated: {type: Number, default: 0},
    name: {
        displayValue: {type: String, default: '', index: true},
        lowerCaseValue: {type: String, default: '', index: true}
    },
    isProbable: {type: Boolean, default: false, index: true},
    isNewLogo: {type: Boolean, default: false},
    isNewProduct: {type: Boolean, default: false},
    owner: {type: Schema.Types.ObjectId, ref: 'Member', index: true},
    organization: {type: Schema.Types.ObjectId, ref: 'Organization', index: true},
    contact: {type: Schema.Types.ObjectId, ref: 'Contact', index: true},
    company: {type: Schema.Types.ObjectId, ref: 'Company', index: true},
    channelPartner: {type: Schema.Types.ObjectId, ref: 'Company'},
    amount: {type: Number, default: 0},
    currency: {type: String, default: ''},
    closeDate: {type: Number, default: 0},
    lastInteractionTimestamp: {type: Number, default: 0},
    closeDateFormat: {type: String},
    products: [{
        name: {type: String, default: ''},
        amount: {type: Number, default: 0},
        type: {type: String, default: 'Fixed'},
        units: {type: Number, default: 0},
        price: {type: Number, default: 0},
        revenueList: [{
            price: {type: Number, default: 0},
            units: {type: Number, default: 0},
            durations: {type: Number, default: 0},
            type: {type: String, default: 'Monthly'},
            amount: {type: Number, default: 0},
            startDate: {type: Number, default: 0},
            startDateFormat: {type: String}
        }],
        subProducts: [{
            name: {type: String, default: ''},
            price: {type: Number, default: 0},
            type: {type: String, default: 'Fixed'},
            units: {type: Number, default: 0},
            amount: {type: Number, default: 0},
            revenueList: [{
                price: {type: Number, default: 0},
                units: {type: Number, default: 0},
                durations: {type: Number, default: 0},
                type: {type: String, default: 'Monthly'},
                amount: {type: Number, default: 0},
                startDate: {type: Number, default: 0},
                startDateFormat: {type: String}
            }]
        }]
    }],
    // we will group all fixed revenues
    fixedRevenue: {
        items: [{
            name: {type: String, default: ''},
            parentName: {type: String, default: ''},
            price: {type: Number, default: 0},
            units: {type: Number, default: 0},
            amount: {type: Number, default: 0}
        }]
    },
    // we will group all recurring revenues
    recurringRevenue: {
        startDate: {type: Number, default: 0},
        startDateFormat: {type: String},
        endDateFormat: {type: String},
        endDate: {type: Number, default: 0},
        items: [{
            name: {type: String, default: ''},
            parentName: {type: String, default: ''},
            price: {type: Number, default: 0},
            units: {type: Number, default: 0},
            durations: {type: Number, default: 0},
            type: {type: String, default: 'Monthly'},
            amount: {type: Number, default: 0},
            startDate: {type: Number, default: 0},
            startDateFormat: {type: String},
            endDate: {type: Number, default: 0},
            endDateFormat: {type: String},
        }]
    },
    associatedContacts: [{type: Schema.Types.ObjectId, ref: 'Contact'}],
    sharedWith: [{type: Schema.Types.ObjectId, ref: 'Member'}],
    status: {
        name: {type: String, default: 'Pipeline'},
        orderPriority: {type: Number, default: 3}
    },
    dealStatus: {type: String, default: 'Pipeline'},
    closeState: {
        won: {
            reason: {type: String, default: ''},
            qualifiedForInternalReference: {type: Boolean, default: true}
        },
        lost: {
            reason: {type: String, default: ''},
            competitorName: {type: String, default: ''}
        },
        stalled: {
            reason: {type: String, default: ''}
        },
        duplicated: {},
        // one of the above values: won, lost, stalled, duplicated
        selected: {type: String, default: ''},
        closed: {type: Boolean, default: false},
        closeDate: {type: Number, default: 0}
    },
    stages: {
        current: {type: Number, default: 0},
        lastStateChange: {type: Number, default: 0},
        list: [{
            name: {type: 'String', default: ''},
            qualifiers: [{
                content: [{
                    date: Number,
                    text: {type: String, default: ''},
                    title: {type: String, default: ''},
                    author: {type: String, default: ''},
                    meetingMinute: {type: Schema.Types.ObjectId, ref: 'Meeting_Minute'}
                }],
                empty: {type: Boolean, default: true},
                longName: {type: 'String', default: ''},
                shortName: {type: 'String', default: ''},
                explanatoryText: {type: 'String', default: ''},
                deadline: {type: Number, default: 0},
                status: {
                    selected: {type: Number, default: -1},
                    list: {type: [String], default: []}
                },
                checklist: [{
                    text: {type: String, default: ''},
                    description: {type: String, default: ''},
                    selected: {type: Boolean, default: false}
                }],
                tasks: [{type: Schema.Types.ObjectId, ref: 'Task'}],
                isFromLead: {type: Boolean, default: false}
            }],
            milestones: [{
                content: [{
                    date: Number,
                    text: {type: String, default: ''},
                    title: {type: String, default: ''},
                    author: {type: String, default: ''},
                    meetingMinute: {type: Schema.Types.ObjectId, ref: 'Meeting_Minute'}
                }],
                deadline: {type: Number, default: 0},
                empty: {type: Boolean, default: true},
                longName: {type: 'String', default: ''},
                shortName: {type: 'String', default: ''},
                explanatoryText: {type: 'String', default: ''},
                status: {
                    selected: {type: Number, default: -1},
                    list: {type: [String], default: []}
                },
                checklist: [{
                    text: {type: String, default: ''},
                    selected: {type: Boolean, default: false},
                    description: {type: String, default: ''}
                }],
                tasks: [{type: Schema.Types.ObjectId, ref: 'Task'}]
            }]
        }]
    },
    source: {
        name: {type: String, default: '', index: true},
        metadata: {
            resourceId: String,
            resourceURL: String
        }
    },
    dealSource: {type: String, default: '', index: true},
    notes: [{
        timestamp: {type: Number, default: 0},
        title: {type: String, default: ''},
        text: {type: String, default: ''},
        linked: {
            name: {type: String, default: 'DEAL'},
            child: {type: String, default: ''}
        },
        author: {type: String, default: ''}
    }],
    lastForecasts: [{
        memberId: {type: Schema.Types.ObjectId, ref: 'Member'},
        value: {type: Number, default: 0},
        status: {type: String, default: ''},
        comment: {type: String, default: ''},
        valueOverwritten: {type: Boolean, default: false},
        statusOverwritten: {type: Boolean, default: false}
    }],
    nextSteps: [{
        timestamp: {type: Number, default: 0},
        text: {type: String, default: ''},
        author: {type: String, default: ''},
        fromMerge: {type: Boolean, default: false}
    }],
    territory: {type: Schema.Types.ObjectId, ref: 'Territory'},
    includedInForecast: [{
        included: {type: Boolean, default: false},
        member: {type: Schema.Types.ObjectId, ref: 'Member'}
    }],
    isSandbox: {type: Boolean, default: false},
    externalId: {type: String, default: ''}
});`

**Comment by varunjayaraman** [comment]
can you please format this with 3 backticks, it's really difficult to read and you inserted it as an image so i can't reformat it for you

**Comment by vkarpov15** [comment]
Yeah the problem is that you're using a long-obsolete version of mongoose. Upgrade to at least [4.1.11](https://github.com/Automattic/mongoose/blob/master/History.md#4111--2015-10-12) to fix this.
