### ISSUE TITLE
Macos sierra, model.save is undefined

### ISSUE THREAD

**Issue by andreasi** [Automattic/mongoose#5183]
Hi everyone.
A couple of days ago I bought a new macbook pro with MacOs Sierra on it.  I installed Nodejs 6.10.2 and cloned by repo from github to start working. Previously I had a PC. 
Here is some code. 

`
//model.js
var mongoose = require('mongoose'),
     Schema = mongoose.Schema;

  var RecordSchema = new Schema({
  field1: String,
  field2: String
  });

module.exports = mongoose.model('Record', RecordSchema )

//controller.js
import RecordModel from './RecordModel'
var newRecord = new RecordModel({
  field1: "value1",
  field2: "value2"
});

console.log(Object.getOwnPropertyNames(newRecord));
//on my pc it prints out [ ‘$__’, ‘isNew’, ‘errors’, ‘_doc’, 'save', 'validate' ] //and all the methods
//on my mac it just prints out [ ‘$__’, ‘isNew’, ‘errors’, ‘_doc’ ] //and newRecord.save is undefined 
newRecord.save(function(err, record){
  if(err){
    console.error(err);
  } else {
    console.log(record);
  }
})
`

Does anyone know why this is happening only my mac and not on windows. 
Thanks.

**Comment by varunjayaraman** [comment]
are you sure this is an OS level issue?

Does `newRecord.save()` throw an error or does it just not show up on in the list of `getOwnPropertyNames`? mongoose documents are weird and you shouldnt call methods like `hasOwnProperty` or `getOwnPropertyNames` on them.

**Comment by andreasi** [comment]
Hey, thanks for the reply.
The getOwnPropertyNames method was called just for debugging purposes. I don't call this method in my production code. The newRecord.save() is never called because "save" is undefined. That is my issue. I don't know if it has to do with the Node version. On my pc I have v6.9.2 where on my mac I have v6.10.2.

**Comment by varunjayaraman** [comment]
I'm asking does it throw an error when you try to  call `newRecord.save()` or are you not even trying because you can't see the method in the console log?

**Comment by vkarpov15** [comment]
Which version of mongoose do you have installed on each machine? It's much more likely you have different versions of mongoose than an OS-level issue.

**Comment by varunjayaraman** [comment]
@andreasi can you please clarify if you're using the same version of mongoose on both machines? Otherwise I'm going to close this soon as stale.
