### ISSUE TITLE
small question, if you got an answer quickly

### ISSUE THREAD

**Issue by patrikx3** [Automattic/mongoose#5186]
Ciao! 

How are you?

Is there a default Schema options setting?

So that all my timestamp enabled by default?
I always have to add in a timestamp as an option. Can I set a default option?

Thanks if you know, if not, I will figure out something. Thanks so much!

**Comment by varunjayaraman** [comment]
Not that I can remember but you could easily create a plugin and attach it globally to mongoose or write a helper function that takes in an object and creates a schema and attaches the `timestamps` option to it

**Comment by patrikx3** [comment]
thanks so much, i just decorate the defaultOptions function, thanks so much ciao!!
