### ISSUE TITLE
Declare methods on sub-documents array

### ISSUE THREAD

**Issue by maxs15** [Automattic/mongoose#5187]
I didn't find anything to declare a custom method on my array of sub-documents, is there a way to do that currently ? Would be super helpful :)

Just an example to clarify my issue:
```js
var PictureSchema = new mongoose.Schema({
	created_date: Date,
	url: String
});

var UserSchema = new mongoose.Schema({
	pictures: [PictureSchema],
});

User.findById("123")
.then((user) => {
	/* Would like to create a custom method user.pictures.upload(...)
	 * The same way it is possible with documents using schema.methods
	 */
});
```

I could declare the method in the User model, but it would be much cleaner because my user model is getting really big..hope you'll see my point.

I appreciate the help, thanks

**Comment by varunjayaraman** [comment]
Not really, but why you can't just define a method on your schema, like so:

```javascript
const schema = new mongoose.Schema({
      testArr: [{ name: String }]
    });

    schema.methods.lowercaseNames = function() {
      return this.testArr.map(val => val.name.toLowerCase());
    }
```
Your argument that your User model is getting big seems strange to me since this array still lives on the User model so you would have to define the method on it anyway

**Comment by maxs15** [comment]
Actually that's the comprise I just implemented, the only flaw is that I have to declare a useless object..but well it isn't too bad.
Just wanted to know if there is some way I didn't know yet, thanks for your confirmation @varunjayaraman.
