### ISSUE TITLE
unset a value for a path

### ISSUE THREAD

**Issue by gitfy** [Automattic/mongoose#519]
Hi,
Is there way to unset a value for an attribute using the path like :

instance.set('embedObj.attribute1' , null) 

or instance.unset('embedObj.attribute1')

which will eventually mark the attribute to modified and add the right atomics during the save.

Thanks.

**Comment by MidnightP** [comment]
Is there a solution for this yet ?

**Comment by vkarpov15** [comment]
@MidnightP nope not yet. Please open up a new issue if you want a feature, this issue is closed.
