### ISSUE TITLE
Bug: insertMany fails on Decimal Types

### ISSUE THREAD

**Issue by alaa-ismail** [Automattic/mongoose#5190]
When using insertMany on a model whose schema contains a Decimal type, the operation fails with the error:
`Error: key $numberDecimal must not start with '$'`

**Steps to reproduce:**
The following code reproduces the issue: 
```javascript
const mongoose  = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect('mongodb://localhost:27017/test');

var schema = new mongoose.Schema({
    amount : mongoose.Schema.Types.Decimal
});
var Money = mongoose.model('Money', schema);

Money.create({amount : '123.45'});  // Works fine

// This does not work
Money.insertMany([{amount : '123.45'},{amount : '321.54'}]).then((docs) => { 
    console.log(docs.length);
}).catch((err) => {
    console.log(err);
});
```
**Current Behavior:**
The insert operation fails with the error: 
`Error: key $numberDecimal must not start with '$'`

**Expectation:**
I expect the documents passed to insertMany to be inserted into MongoDB.

**Versions:**
Mongoose **v4.9.5**
MongoDB **v3.4.3**
Node **v6.9.1**

**Comment by varunjayaraman** [comment]
thanks for the full repro script, this looks like a bug

**Comment by varunjayaraman** [comment]
it looks like the mongoose `insertMany()` debug output might shed some light on this:

```
Mongoose: money.insertMany([ { __v: 0, amount: { '$numberDecimal': '132.45' }, _id: 58fea3fe3e
4166463e444c43 }, { __v: 0, amount: { '$numberDecimal': '321.54' }, _id: 58fea3fe3e4166463e444
c44 } ])
```

i believe in mongo it should be setting it as Decimal128 or `NumberDecimal` and the `create()` function seems to do just that:

```
Mongoose: money.insert({ amount: Decimal128 { _bsontype: 'Decimal128', bytes: <Buffer 39 30 00
 00 00 00 00 00 00 00 00 00 00 00 3c 30> }, _id: ObjectId("58fea4ef8a63684695772839"), __v: 0
})
```

**Comment by nicroto** [comment]
I am getting this same error, when I install my node dependencies with `npm install --production`.
In development, the same create query works properly. Here is (a simplified ver of) the document I try to insert:

```javascript
    MyModel.create({
      ...
      "price": {
        "$numberDecimal": "9.99"
      }
      ...
    });
```

And this is the model descriptor:

```json
{
  ...
  "attributes": {
    ...
    "price": {
      "type": "decimal"
    },
    ...
  }
}
```
(strapi creates this schema for me, so I don't know if it is directly compatible with mongoose description of a model, or it's a layer of abstraction on top of it)

mongoose seems to be latest (v5.4.6). (it's myProj -> dep -> dep -> mongoose, so at least that's fortunate in this situation)

**Comment by vkarpov15** [comment]
@nicroto can you provide code samples for how you're using strapi to generate this?

Also, you're not experiencing the exact same issue, [`Model.insertMany()`](https://mongoosejs.com/docs/api.html#model_Model.insertMany) is different from [`Model.create()`](https://mongoosejs.com/docs/api.html#model_Model.create)

**Comment by nicroto** [comment]
Thanks for the reply @vkarpov15.

It was strapi's fault. They were setting the type to float instead of decimal and the create wasn't able to parse the value.
