### ISSUE TITLE
findByIdAndUpdate allows a document inserted with an _id of value null

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#5193]
Should `findByIdAndUpdate` allow a document to be inserted (upserted) where an `_id` of value `null` is supplied?

**Comment by varunjayaraman** [comment]
not sure, probably not but open to discussion

**Comment by vkarpov15** [comment]
You can explicitly set `_id` to be required and then use `updateValidators` if you want `findByIdAndUpdate` to error if `_id` is null.
