### ISSUE TITLE
Mongoose 3.8.40 stopped working on windows 7

### ISSUE THREAD

**Issue by VilleMiekkoja** [Automattic/mongoose#5195]
Hello,

I can't get the basic example working in the front page:
http://mongoosejs.com/docs/3.8.x/

Node version: 7.3.0
MongoDB version: 3.2.0

The code runs without problems, but nothing is stored to the database. I set debug true, but it didn't print anything to console. The quick start guide didn't work either. This has been working before, no idea what has happened. I can connect to the database, and search it through mongo.exe.

**Comment by varunjayaraman** [comment]
please provide a repro script or a code sample, even if it is a copy of the front page code, i'd like to see how you've done it
