### ISSUE TITLE
[BUG] Sub Schema in Sub Schema create wrong index

### ISSUE THREAD

**Issue by ittayo** [Automattic/mongoose#5199]
**Bug**:

When a mongoose schema is used as a type of field within a mongoose schema, and then THIS schema is used in a third schema, and there is an index on the inner most schema, it is created in the external schema as if it is created for the middle schema.

e.g:
SchemaA { f: String }
SchemaA.index({ f: 1 })
SchemaB { a: SchemaA }
SchameC { b : SchemaB }
mongoose.model('TopSchema', SchameC )
*Result:*
topschemas.ensureIndex({ 'a.f': 1 }, {})

**The expected result is:**
topschemas.ensureIndex({ 'b.a.f': 1 }, {})

*******************************
**nodejs code to reproduce:**

```javascript
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird'); //this is only to remove the warning
mongoose.set('debug', true);

const SubSubSchema = mongoose.Schema({
    flavour: { type: String }
});

SubSubSchema.index({ flavour: 1 });

const SubSchema = mongoose.Schema({
    status: { type: String },
    containedInContained: { type: SubSubSchema }
});

SubSchema.index({ status: 1 });

const ContainerSchema = mongoose.Schema({
    name: { type: String },
    contained: { type: SubSchema }
});

ContainerSchema.index({ name: 1 });

const Container = mongoose.model('Container', ContainerSchema);

mongoose.connect('mongodb://localhost/test');

var db = mongoose.connection;


db.once('open', function () {
    console.log('(waiting for all the indexes to be created)')
    setTimeout(function () {
        process.exit()
    }, 1000)
});
```
**Console output:**
```
Mongoose: containers.ensureIndex({ 'containedInContained.flavour': 1 }, {})
(waiting for all the indexes to be created)
Mongoose: containers.ensureIndex({ 'contained.status': 1 }, {})
Mongoose: containers.ensureIndex({ name: 1 }, { background: true })
```
*`containedInContained.flavour`* should have been: *contained.containedInContained.flavour*

*******************************
mongoose npm version: 4.9.6 
nodejs v6.9.1
MongoDB: v3.2.9

**Comment by varunjayaraman** [comment]
cool, thanks for the repro script, this looks like a bug
