### ISSUE TITLE
Bug: array validation not working properly

### ISSUE THREAD

**Issue by asafch-talenya** [Automattic/mongoose#5200]
I'm using this schema to validate a set of updates to a document:

`reps: {type: [{type: String, match: /[0-9a-f]{24}/}]}`

meaning, I expect the new value for this property to be an array of strings, each string being exactly 24 hexa chars long. I've turned on validation when updating a document with `{runValidators: true}` as an option sent to the `findOneAndUpdate` function. I compile the schema with `mongoose.Schema`.

However, I am able to set this property to both a single string (not enclosed in an array) or an empty array, both of which aren't permitted by the schema.

Node v7.7.3
Mongoose v4.6.8
MongoDB v3.2.11

**Comment by varunjayaraman** [comment]
have you tried with the latest mongoose? You're allowed to have an empty array in mongoose for your second case and for your first case of it being a single string, it fails on latest mongoose:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5200`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const schema = new mongoose.Schema({
      name: String,
      reps: { type: [{ type: String, match: /[0-9a-f]{24}/ }] }
    });


    const Model = db.model('Model', schema);

    yield Model.remove({});

    // case 1: empty array - this is allowed in mongoose
    yield Model.create({
      name: 'test',
      reps: []
    });

    // case 2: string - fails as it should
    yield Model.create({
      name: 'test',
      reps: 'test'
    });
  });
}
```
