### ISSUE TITLE
Use GUIDs with Mongoose ID using custom plugin?

### ISSUE THREAD

**Issue by gdeward** [Automattic/mongoose#5201]
Would this plugin be adequate for ensuring the `_id` field of a Mongoose schema is a GUID?  It looks correct but is not working.

    var uuid = require('uuid');
    var validator = require('validator');

    module.exports = function (schema, options) {

        options = options || {};

        var pk = schema.paths['_id'];
        pk.options.default = (typeof options.default === 'function') ? options.default : uuid.v4
        pk.options.lowercase = true;
        pk.options.trim = true;
        pk.options.type = String;
        pk.options.uppercase = false;

        pk.validate(function(v){

            console.log('validating: ' + JSON.stringify(v));

            return validator.isUUID(v);
        }, 'ID is not a valid GUID: {VALUE}');
    };

The goal is to use it as follows:

    var mongoose = require('mongoose');
    
    var schema = mongoose.Schema({
        name: String,
        born: Date
    });
    schema.plugins(require('./guidIdPlugin'));
    
    module.exports = mongoose.model('Person', schema);

The console is showing the `_id` field is *not* a uuid but, instead, is still being generated as an ObjectId:

    validating: "590ce11a58d9114d1cbae06a"

What am I missing?

**Comment by vkarpov15** [comment]
```javascript
schema.plugins('guidIdPlugin');
```

convert to

```javascript
// Make sure to call `.plugin()`, not `.plugins()`
schema.plugin(require('./guidIdPlugin')); // Insert path to the plugin's js file here
```

Mongoose doesn't have a notion of a plugin name, you need to pass a function to `schema.plugin()`

**Comment by gdeward** [comment]
@vkarpov15 : that part was a typo.  i've corrected it.  the problem is that the plugin has no impact.  the plugin does not change the type, the default function, etc.  the `_id` still remains as an ObjectId and an ObjectId is generated.  HOWEVER, the validate function above FAILS because the `_id` value is not a UUID.

**Comment by vkarpov15** [comment]
I wouldn't recommend modifying the internal schema state after the schema's been created, use `.add()` to overwrite the `_id` field correctly. The below script works:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test');
mongoose.set('debug', true);

var uuid = require('uuid');
var validator = require('validator');

function guidPlugin (schema, options) {
    options = options || {};

    var pk = schema.add({
      _id: {
        type: 'string',
        default: () => uuid.v4(),
        trim: true,
        lowercase: true
      }
    });

    schema.path('_id').validate(function(v){
        return validator.isUUID(v);
    }, 'ID is not a valid GUID: {VALUE}');
};

var mongoose = require('mongoose');

var schema = mongoose.Schema({
    name: String,
    born: Date
});
schema.plugin(guidPlugin);

var M = mongoose.model('Person', schema);

M.create({ name: 'Test' }, function(error) {
  console.log(error);
});
```

Output:

```
$ node gh-5201.js 
Mongoose: people.insert({ name: 'Test', _id: 'f52b4080-24c8-4475-b3a5-17b3ac9099bf', __v: 0 })
null
^C
$ 
```
