### ISSUE TITLE
array.push will push repetitively while array.addToSet is correct. Is it a Bug ?

### ISSUE THREAD

**Issue by WingMrL** [Automattic/mongoose#5202]
### IconSchema
```javascript
let IconSchema = new Schema({
  fileName: String,
  iconUrl: String,
  width: Number,
  height: Number,
  labels: [{
    type: ObjectId,
    ref: 'Label',
  }],
  group: {
    type: ObjectId,
    ref: 'Group'
  },
  meta: {
    createAt: {
      type: Date,
      default: Date.now()
    },
    updateAt: {
      type: Date,
      default: Date.now()
    }
  }
})
```
### LabelSchema
```javascript
let LabelSchema = new Schema({
  labelName: String,
  icons: [{
    type: ObjectId,
    ref: 'Icon',
  }],
  meta: {
    createAt: {
      type: Date,
      default: Date.now()
    },
    updateAt: {
      type: Date,
      default: Date.now()
    }
  }
})
```

```javascript
exports.addIcon = function(req, res) {
    let fileName = req.body.trueName;
    let groupId = req.body.groupId;
    let labels = req.body.labels.split(',');
    let iconObj = {
        fileName: fileName,
        iconUrl: path.join(groupId, fileName),
        width: req.body.width,
        height: req.body.height,
        group: groupId,
    };

    let _icon = new Icon(iconObj);


    let saveCount = labels.length;
    // 1. save icon
    _icon.save(function(err, icon) {
        if(err) {
            console.log(err);
        }
        // labels ['good', 'nice']
        if(labels.length > 0) {
            labels.forEach(function(value) {
                Label.findByLabelName(value, function(err, label) {
                    if(label == null) {
                        // new 
                        let _label = new Label({
                            labelName: value,
                            icons: [icon._id] 
                        });
                        _label.save(function(err, label) {
                            if(err) {
                                console.log(err);
                            }
                            // 2. push   label._id   into    icon.labels
                            icon.labels.push(label._id);
                            icon.save(function(err, icon) {
                                if(err) {
                                    console.log(err);
                                }
                                saveCount --;
                                if(saveCount == 0) {
                                    res.json({
                                        code: 0,
                                        status: 'ok',
                                        icon: icon
                                    });
                                }
                            });
                        });
                    } else {
                        label.icons.push(icon._id);
                        label.save(function(err, label) {
                            if(err) {
                                console.log(err);
                            }
                            // 3. push   label._id   into    icon.labels
                            icon.labels.push(label._id);
                            icon.save(function(err, icon) {
                                if(err) {
                                    console.log(err);
                                }
                                saveCount --;
                                if(saveCount == 0) {
                                    res.json({
                                        code: 0,
                                        status: 'ok',
                                        icon: icon
                                    });
                                }
                            });
                        });
                        
                    }
                });
            });
        }
    });
};
```
### Sorry for the poor issue title, but I really didn't know how to describe.

* As you can see in the `2` and `3` comments, I push `label._id` into `icon.labels`. However, when the array `labels` is somthing like that, `['good', 'nice']`.  Finally, I found 3 elements in `icon.labels`. As the following photo shows:

![image](https://cloud.githubusercontent.com/assets/13505958/25396130/fba4b59a-2a15-11e7-91c6-5973a5e83bf8.png)

* When the array `labels` is somthing like that, `['good', 'nice', 'Woo']`, Finally, I found 6 elements in `icon.labels`. As the following photo shows:

![image](https://cloud.githubusercontent.com/assets/13505958/25396217/5da81e9e-2a16-11e7-9a26-92f16d72cb15.png)

* So, am I missing some mistakes ? I googled it many times, but could not solve it. Thank you for your time !

### Clarification
* I'm going to add an `icon` to `IconSchema`, and the `icon` has some labels which should be add to `LabelSchema` when the label is a new one (case comment 2) or find those existing labels in `LabelSchema` and push icons's id(s) to Label.icons. (case comment 3)
* So, when the `labels` array is something like `['good', 'nice']`, the `icon.labels` should be something like `[ObjectId("id111"), ObjectId("id222")]` instead of `[ObjectId("id111"), ObjectId("id111"), ObjectId("id222")]`. 
* when the `labels` array is something like `['good', 'nice', 'Woo']`, the `icon.labels` should be something like `[ObjectId("id111"), ObjectId("id222"), ObjectId("id333"), ]` instead of `[ObjectId("id111"), ObjectId("id111"), ObjectId("id111"), ObjectId("id222"), ObjectId("id222"), ObjectId("id333")]`. 
* It seems to push 'label' repetitively into `icon.labels`. Only when the `labels` array's length equals 1, the operation is right.

**Comment by varunjayaraman** [comment]
oh man, this is some hard to reason through code. Do you have a more condensed example? I'm guessing this has something to do with how you're asynchronously saving documents in a `forEach` loop.

Also, are you saying case 2 is correct but the result for case 3 is unexpected?

**Comment by WingMrL** [comment]
I updated the comment above and thank you for your time ! @varunjayaraman 

I added the `IconSchema` and `LabelSchema` structure and made a clarification. I have thought about the asynchronously saving documents in a `forEach`, but each of them are no conflicts. Case 2 and case 3 are both wrong.

**Comment by TrejGun** [comment]
@WingMrL 
hey man! try to replace 
```
icon.labels.push(label._id);
```
with
```
icon.labels.addToSet(label._id);
```

**Comment by WingMrL** [comment]
@TrejGun That's amazing ! It works. Thank you so much! But I still have no idea about the `push` problem.

**Comment by TrejGun** [comment]
i see no problem here)

**Comment by TrejGun** [comment]
from the second screenshot it looks like

1 you have [_id1]
2 then you push existing _id1 and new _id2 so you have [_id1, _id1, _id2]
3 then you push existing _id1, _id2 and new _id3 so you have [_id1, _id1, _id2,  _id1, _id2, _id3]

I don't really want to dig your spaghetti :) so split your code into small functions, rename variables so not all of them has name `label` and you will find a bug in your logic. cheers.
