### ISSUE TITLE
Bug: connection.schema.pre('xxx') does not work after upgraded to newer mongoose versions

### ISSUE THREAD

**Issue by thanhlq** [Automattic/mongoose#5203]
Hello Everybody,

I have a use case like this: I am using multiple data sources so I used the schema from the connection object for trigger of hooks as pre('save').. 

But after upgraded from version 4.7.9 to newer versions.. no any hooks are executed... it works fine for me in the version 4.7.9.

- Worked mongoose version: 4.7.9
- Failed mongoose version: > 4.7.9 (as 4.8.0, 4.8.x, 4.9.0, 4.9.x)

This is quite urgent for me so thanks so much for any help.

Kind regards,
Thanh Le
EMSA TECHNOLOGY.

Example model:
```javascript
module.exports = function(cnn, modelConfig) {
  const Schema = cnn.mongoose.Schema;
  const modelSchema = Schema({
    name: {
      type: String,
      unique: true,
      required: true,
      index : true,
    },
    displayName: {
      type: String,
      unique: true,
      required: true,
      index : true,
    },
    enabled: {
      type: Boolean,
      default: true,
    },
    metadata: Schema.Types.Mixed,
    createdTime: {
      type: Date,
    },
    updatedTime: {
      type: Date,
    }
  }, modelConfig.schemaOptions || {});

  const model = cnn.modelCreator.model(modelConfig.tableName, modelSchema);


  return model;
};
```
and in another place:

```javascript
const schema = model.schema;
schema.pre('save', function(next) {
    console.log('[schema.pre.save] this gets printed ........................' );
    next()
  });
```

**Comment by varunjayaraman** [comment]
Your problem is that you've registered your hooks after calling `mongoose.model()`. You have to register your books before that. Never mutate your schema after calling `mongoose.model()`, the returned object is constructrs from the underlying schema

**Comment by thanhlq** [comment]
Ah I tried this and it works.... so I have to rework all defined models :(.

Thank you very much for your tip!
