### ISSUE TITLE
Mongoose failing to pass correct update query to mongodb

### ISSUE THREAD

**Issue by kyle-mccarthy** [Automattic/mongoose#5207]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On the object there is an array of another object.  When an object in the array is modified, not all of the objects attributes are updated.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the object that contains the array of other objects, I have omitted some code that isn't relevant to this specific issue.

```
export interface IMatrix {
  ...
  otherMarkups: IMarkupModel[];
  otherMarkupCount: number;
}

export interface IMatrixModel extends IMatrix, Document {
  ...

  addOtherMarkup(markup: IMarkupModel): void;
  setOtherMarkups(markups: IMarkupModel[]): void;
  getOtherMarkups(): IMarkupModel[];
}

export let MatrixSchema: Schema = new Schema({
  ...
  otherMarkups: [MarkupSchema],
  otherMarkupCount: { type: SchemaTypes.Number, default: 0 }
});

....

MatrixSchema.methods.addOtherMarkup = function (markup: IMarkupModel): void {
  markup.setId(this.otherMarkupCount);
  this.otherMarkups.push(markup);
  this.otherMarkupCount++;
};

MatrixSchema.methods.setOtherMarkups = function (markups: IMarkupModel[]): void {
  this.otherMarkups = markups;
};

MatrixSchema.methods.getOtherMarkups = function (): IMarkupModel[] {
  return this.otherMarkups;
};

export const Matrix: Model<IMatrixModel> = model<IMatrixModel>("Matrix", MatrixSchema);  
```

This is the markup module, I've also omitted irrelevant code....

```
import { SchemaTypes, Schema, Model, Document, model } from "mongoose";

export interface IMarkup {
  id: number;
  name: string;
  value: number;
  fixed: boolean;
  display: string;
  type: string;
}

export interface IMarkupModel extends IMarkup, Document {
  ...
  setAttributes(attrs: any): void;
}

export let MarkupSchema = new Schema({
  id: SchemaTypes.Number,
  name: SchemaTypes.String,
  value: SchemaTypes.Number,
  fixed: SchemaTypes.Boolean,
  display: SchemaTypes.String,
  type: SchemaTypes.String
});

...
generic getters and setters
....

MarkupSchema.methods.setAttributes = function (attrs: any): void {
  Object.keys(attrs).forEach(key => {
    if (key !== "id" && key !== "_id") {
      this[key] = attrs[key];
    }
  });
};

export const Markup: Model<IMarkupModel> = model<IMarkupModel>("Markup", MarkupSchema);
```

Where the update is actually happening.

```
 Matrix.where("id").equals(request.params.id).limit(1).find((err: any, res: IMatrixModel[]) => {
      let matrix = res[0];
      let markups = matrix.getOtherMarkups();
      let idx = markups.findIndex((m: IMarkupModel) => m.getId() === body.id);
      let markup = markups[idx];
      markup.setAttributes(body);
      markup.setId(body.id);
      markups[idx] = markup;
      matrix.save();
    });
```

This is happening inside of a method handling a Express.js request.  The body contains all of the of the attributes of the markup model.  I am defining an incrementing id on the markup because I come from a background of SQL so it is easier for me to understand, it doesn't serve any function other than me pulling out the correct element.  The correct markup is pulled out of the array, the setAttributes function correctly modifies expected attributes, I can console.log the object after setAttributes and all of the data is correct.  I've seen the issue #1204, where it suggest to call the set method but the IMatrixModel[] doesn't have a set method for me to call, because TypeScript arrays don't have a set method.

Furthermore, if the markup isn't inside of an array everything is updated correctly and there isn't a problem.  Additionally, all of the fields are updated (even in the array) _except_ the display field.

The display field will update if I pass it something that is clearly a string such as "2%", but will not update if it is passed an integer as a string i.e. "1500".  I have checked to make sure that the value being assigned to the display value is in fact a string, so I know that "1500" is oftype string and not a number.

I've turned on debug mode and discovered that mongoose is not passing the correct update query to mongo.  The query omits the 'display' value unless it has non numeric characters inside the string.

Wrong: 

```
Mongoose: matrixes.update({ _id: ObjectId("58f103c93afd7d4f24108fc3"), __v: 121 }, { '$set': { ... 'otherMarkups.0.fixed': true, 'otherMarkups.0.id': 7, 'otherMarkups.0.name': 'Testing', 'otherMarkups.0.value': 1500, ... } })
```

Correct:

```
Mongoose: matrixes.update({ _id: ObjectId("58f103c93afd7d4f24108fc3"), __v: 121 }, { '$set': { ...  'otherMarkups.0.display': '5%', 'otherMarkups.0.fixed': false, 'otherMarkups.0.id': 7, 'otherMarkups.0.name': 'Testing', 'otherMarkups.0.value': 5, ... } })
```

```
Mongoose: matrixes.update({ _id: ObjectId("58f103c93afd7d4f24108fc3"), __v: 121 }, { '$set': { ... 'otherMarkups.0.display': '$1500', 'otherMarkups.0.fixed': true, 'otherMarkups.0.id': 7, 'otherMarkups.0.name': 'Testing', 'otherMarkups.0.value': 1500, ... } })
```

**What is the expected behavior?**

Mongoose should be updating the display property which is a string.  See above for an explanation.

**Please mention your node.js, mongoose and MongoDB version.**

```
node.js: v6.9.5
mongoose: v4.6.9
mongoDb: v3.4.2
typescript: v2.2
```

**Comment by varunjayaraman** [comment]
it works for me on latest mongoose, can you try with that?:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5207`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

    const childSchema = new mongoose.Schema({
      display: String
    });

    childSchema.methods.setAttributes = function(attrs) {
      Object.keys(attrs).forEach(key => {
        if (key !== "id" && key !== "_id") {
          this[key] = attrs[key];
        }
      });
    }
    const schema = new mongoose.Schema({
      name: String,
      children: [childSchema]
    });

    const Model = db.model('Model', schema);
    yield Model.remove({});

    const doc = yield Model.create({
      name: 'Test',
      children: [
        { display: 'child 1' },
        { display: 'child 2' }
      ]
    });

    const result = yield Model.findById(doc._id);
    
    const children = result.children;
    const child = children[0];
    child.setAttributes({
      display: '1500'
    });

    children[0] = child;
    yield result.save(); // debug output: Mongoose: models.update({ _id: ObjectId("5905066d2e737b900ac47a9d"), __v: 0 }, { '$set': { 'children.0.display': '1500' } })
    
    const update = yield Model.findById(result._id);
    const updatedChild = update.children[0];
    console.log(updatedChild.display); // shows 1500
  }); 
}
```

as a sidenote, you can use `.set()` by passing in the array index number inside `.set()`:

```javascript
matrix.set('marksup.0.display', '1500');
```

**Comment by kyle-mccarthy** [comment]
@varunjayaraman So that worked correctly.  I've noticed that in my DB for my application that the __v will not increment correctly even if a child inside of the children array changes.  I assume that this could be part of the problem?

**Comment by kyle-mccarthy** [comment]
Actually, I am starting to thing that this is a race condition with how things are updating... The two update requests fire at nearly the exact same time +/- a couple of ms.  On the front end the display value is set, then a change event is fired, this will send the first request for updating the display value.  While this happens the front end script calculates the value, so if it is a % it will do a total * % and sets the value, otherwise it will just set the value to the integer value of the display.

So the first request will be 

```
{
    value: 100,
    display: '10%',
    id: 1
}
```

Then the second will have the calculated value
```
{
    value: 100000
    display: '10%'
    id: 1
}
```

Even though the server gets the requests in the right order and handles them correctly, I think that mongoose is asynchronously handling them in the wrong order which is causing the problem.  I should just be able to modify the front end script to not send it when the display value is updated and wait for the value to be calculated.

**Comment by varunjayaraman** [comment]
without more context on how the two async calls are happening, not sure i can debug. Try refactoring so that your code is deterministic and the race condition doesn't occur and if the issue persists, let me know

**Comment by varunjayaraman** [comment]
going to close this. If you find that this issue persists and you have more context, feel free to open another issue and link to this one for additional context
