### ISSUE TITLE
KILL PLURALIZATION  (#1350)

### ISSUE THREAD

**Issue by sslyle** [Automattic/mongoose#5209]
My two bits.  Just drop the pluralization and lowercase requirement all together.  Don't option it, that's stupid.  And making a all lower case requirement is not being compliant with mongoDB.  

Think of this AND your next design choices like this:
  - by removing some unnecessary draconian rules in this world YOU ENABLE ME (US / YOUR USERS & FANS) TO BE THE MORE CREATIVE 
  - AND it costs you LESS OF YOUR EFFORT
  - AND enabling my creativity you're BUILDING A BETTER PRODUCT
  - AND by creating and enforcing additional (and by not removing) arbitrary rules the LESS RELEVANT YOU BECOME TO YOU MARKET YOUR MARKET
Just my two bits.
Need help removing the .toLower() in your code on the collection name?
If the application is structured well this is probably in only one line of code.  So you can fix  this in no more consideration that the next maintenance release.

On 1350 I saw the remark "most collections are plural"  ... Really?!!  That simply is NOT true.  Where you see this is in the work of those sheep who learned, then never challenged finding, a better way.  most specifically Microsoft Entity Frameworks.  You don't want mongoose to be associated in the minds of users is Microsoft EF do you?  Just let me name it what I want to name it and you earn favor and grow deployments.  Make people struggle over stupid design choices and people will walk straight into the arms of your competitors who are not so pointlessly sadistic.

Thanks.

**Comment by varunjayaraman** [comment]
convention is to use plural and lowercase for collection names because case sensitive bugs are annoying to deal with. If you disagree with the convention you  can pass in a collection name, it's not that difficult. 

I'll open this up to discussion but I think it's fine as is (although the goal is to deprecate the way we currently pluralize collections and just use a third-party lib that is unit tested for that end)

**Comment by sslyle** [comment]
Varun.  I appreciate the response and openness to new thought regarding this policy.

My first thought is being 'conventional' is not at all what I would suggest wanting to achieve, especially given the nature of an endeavor as this.  Instead, be brilliant. Distinguish Mongoose above all else.  Give Mongoose the antithesis of conventional.  A convention is a way of doing things.  Choose to use it if you want to, choose to not use it if you don't.  This is NOT what Mongoose is supporting.  Mongoose is enforcing a rule, enforcing a regulations, enforcing itself upon developers who want to use Mongoose.  And doing so while NOT being compliant with mongoDB.

***Second, be compatible with MongoDB.  Mongo support these three names existing simultaneously; countryCode, Countrycode, Countrycodes, CountryCode. ***
But any collection created by Mongoose will be lowercase justified ~ even if you "pass in a collection name".  I still can't find anything of the lowercase documentation, AND if you fail to connect to a collection because of case problems Mongoose doesn't throw any type of warning/response... While technically this is accurate it actually SUPPORTS making case sensitive bug DIFFICULT to find.

I would like to think anyone who codes their collection name in Mongoose "countryCode" would get a collection named "countryCode" in mongodb.  Thereby avoiding any case sensitive bugs.  But also someone wanting to connect Mongoose to a collection named "camelCaSe" would type "camelCaSe" into their Mongoose code.  It is a Javascript world.  If they don't get it by now then they need to have the trouble of figuring it out so they can learn.

Not all collections developers are attaching to using Mongoose are created by Mongoose.
My case for example, that Mongoose _helped_ me lose 8-hours having to figure this out, I'm attaching to collections created by a third-party, who I found out isn't using Mongoose specifically BECAUSE or this case-pluralism policy.

Third, you are actually doing MORE work in Mongoose to validate & modify case 
![u](https://cloud.githubusercontent.com/assets/5661146/25666655/2593459a-2fef-11e7-9a95-a678413705ab.png)


That's my two-bits. Thanks for listening.  You ARE doing a lot of things I like in Mongoose.  But this one, one NOT compliant with mongoDB ~ or javascript for that matter ~ specifically makes Mongoose entirely unusable on this project.

**Comment by vkarpov15** [comment]
I had a similar problem mongoose when I was first learning back in 2012, I didn't realize the pluralization was happening and so spent 2 hours trying to figure out why docs weren't getting saved. I agree 100%, that's why we're planning on killing it in the next backwards breaking release.

**Comment by sslyle** [comment]
I want to be screamingly clear. Plurality is NOT the issue I brought to
this conversation.  My was the atypical enforcement of all lowercase.  That
is all lowercase which is contrary to MongoDB & Javascript itself.
