### ISSUE TITLE
SchemaType Boolean tries to convert input

### ISSUE THREAD

**Issue by c0d0g3n** [Automattic/mongoose#5211]
I encountered a bug with schemaType Boolean where its cast method converts the input to `true` (or `false`?) as a last resort. I think it should throw or spit a validation error if the input is not a boolean, a string representation of a boolean or 0 or 1. Right now it returns `!!value` (https://github.com/Automattic/mongoose/blob/master/lib/schema/boolean.js#L70), which seems  unexpected to me and may introduce subtle bugs. In addition to that, writing a custom validator (to override this behavior) is pointless, because the passed value is `true` or `false` anyway.

I suspect that mongoose itself is tricked by current behavior: https://github.com/Automattic/mongoose/blob/master/lib/schema/boolean.js#L47

[Here is a gist](https://gist.github.com/c0d0g3n/40b4b62041969abfafe4199c4101c047) showing the current behavior, as well as providing a temporary workaround.

I'm using mongoose 4.9.6.

**Comment by c0d0g3n** [comment]
As this issue is labeled as discussion, let me give a clearer example of what I mean:

Say you want to store in the database whether a visitor likes pancakes or not, represented by a boolean. You receive the info in JSON, like this:

    {
        "likePancakes": true
    }

You apply the new value like this:

    user.likePancakes = input.likePancakes
    user.save()

So far, so good. Note that input validation is left to Mongoose as validating here would be redundant and inconsistent relating error messages etc. (The issue could be due to my reasoning right here.)

Now, assume the visitor passes this:

    {
        likePancakes: "nope"
    }

Currently, Mongoose parses this as `true`, even though this is clearly not the visitor's intent, which creates confusion. Better would be to just let the validation fail.

Hope this makes my point more clear :)

P.s. I've never made a pull request before, but if we can agree on the wanted behavior of this schemaType, I am willing to try.

**Comment by c0d0g3n** [comment]
@varunjayaraman I've made an [alternative implementation](https://github.com/c0d0g3n/mongoose/commit/d57351e57077047b2deafaa5e786f7ae6e033728) as a matter of practice. What do you think about it and where would be the best place to document this new option? Without enabling the `strict` option, behavior will remain intact, so this is fully backwards-compatible.

**Comment by varunjayaraman** [comment]
this looks good to me. looping in @vkarpov15 to sign off on it. And if you want to write a test, that would be A+, otherwise i can knock 1 or 2 out pretty easily

**Comment by c0d0g3n** [comment]
@varunjayaraman I've written a test: https://github.com/c0d0g3n/mongoose/commit/ede9c64d0d06e22312656bdd34d612ba823a400a. (Don't mind the comments at the end of the file, I removed them in the repo.) Also eslint thinks the es6 `Promise` object is an undefined variable, hence we had an argument :).

**Comment by varunjayaraman** [comment]
you could probably clean up those multiple `||` blocks with an array and `indexOf` (although I have some not so nice opinions of the `indexOf` hack), but its not the biggest deal in the world if not

**Comment by vkarpov15** [comment]
Already planning on changing this for 5.0 re: #4245 but PRs are most welcome. At first glance the code you wrote looks good, I'll give it a more thorough inspection once the PR is in

**Comment by c0d0g3n** [comment]
@vkarpov15 Finally created a pull request, but was not able to build documentation. (Also, my git management is probably garbage.)

Below's relevant part of the make output. Am I messing up the build process or is there a bug in the repo? (Should probably go into a separate issue.)

    node website.js
    undefined:31
    ]\n### lib/aggregate.js
     ^

    SyntaxError: Unexpected token \ in JSON at position 1731
        at Object.parse (native)
        at /home/roos/Projects/issues/test/mongoose/docs/source/api.js:34:21
        at Array.forEach (native)
        at parse (/home/roos/Projects/issues/test/mongoose/docs/source/api.js:23:25)
        at Object.<anonymous> (/home/roos/Projects/issues/test/mongoose/docs/source/api.js:19:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
    Makefile:17: recept voor doel 'docs/source/_docs' is mislukt
    make: *** [docs/source/_docs] Fout 1

**Comment by vkarpov15** [comment]
I think you're mixing something up. If you want to compile the docs I'd do `make gendocs`, although that currently appears broken, but for a separate reason from what you specified... Will fix that

**Comment by c0d0g3n** [comment]
@vkarpov15 Any clue what the cause of my problem is? It still appears and I have no idea what is causing it. (maybe something with charsets?) :thinking:

**Comment by vkarpov15** [comment]
@c0d0g3n what's your node version?

**Comment by c0d0g3n** [comment]
@vkarpov15 Node version: 6.10.3 (npm: 3.10.10)

**Comment by vkarpov15** [comment]
Weird, works fine for me with node 6.10.3. I think you need to do `make docclean` before running `make gendocs`...
