### ISSUE TITLE
Mongod start not trigger with Mongoose

### ISSUE THREAD

**Issue by akudahewa** [Automattic/mongoose#5213]
when start the node with connected database, triggers below events,

```
mongoose.connection.once('open', console.log.bind(console,'connection open !!!!!'));
mongoose.connection.on('connected', console.log.bind(console,'connection connected !!!!!'));
```

when stop the database,triggers below events,

```
mongoose.connection.on('disconnected', console.log.bind(console,'connection disconnected !!!!!'));
mongoose.connection.on('close',console.log.bind(console,'connection close !!!!!'));
```

Then again I start the mongodb database

But application get hang when trying at access the database even through `reconnectTries` set 1 in the server option

```
var options = { server: {reconnectTries: 1,socketOptions: { keepAlive: 300000,connectTimeoutMS: 10000 } } } ; 
mongoose.connect(uri,options)
```
below is my code block

```
app.get('/res', function(req, res, next) {
	var result;
	console.log('Trying to access the database')
	rootRes.find({}, function (err, result) {
  	if (err) {
  		console.log('Error occur !!!!!!!!!!!!!!!!!!')
  	};
 	res.json(result);
 	})
});
```

I'm having experiencing that when we start the mongodb after stop, 'connected' event not triggerd.
`mongoose.connection.on('connected', console.log.bind(console,'connection connected !!!!!'));`

Any idea about this. Can you please provide some ideas which I don't know.

I'm using
"mongoose": "4.6.4"
"mongod" :"3.2.9"

Thank you

**Comment by houssem-yahiaoui** [comment]
What about your connection string can you show us the full mongoose configuration ?

**Comment by varunjayaraman** [comment]
oops sorry we missed this. Are you still experiencing this issue @akudahewa ?
