### ISSUE TITLE
[BUG] (node:8232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: the limit must be positive

### ISSUE THREAD

**Issue by vatex** [Automattic/mongoose#5214]
Hi,

I have big application on AWS. unexpectedly it crashed and thrown this error: 

"(node:8232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: the limit must be positive"

Can you tell me when this error occurs? This will help me or not, to write console logs in error callback to catch where is this error?

P.S. I don't know what happened... I seen this error in 24 hour, after occured.

Environment:
> AWS - Elastic Beanstalk
> 64bit Amazon Linux 2016.09 
> Node.js v6.10.0
> Mongoose v4.7.5
> MongoDB v3.4

**Comment by vatex** [comment]
Here is more clear error message:
{ MongoError: the limit must be positive
    at Function.MongoError.create (/var/app/current/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/app/current/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/var/app/current/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/var/app/current/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/var/app/current/node_modules/mongodb-core/lib/connection/connection.js:317:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  message: 'the limit must be positive',
  ok: 0,
  errmsg: 'the limit must be positive',
  code: 15958,
  codeName: 'Location15958' }

**Comment by varunjayaraman** [comment]
this is hard to debug without more context. I've seen this error before when `$slice` was used (mongodb aggregation). Do you have more instructive error logs?

**Comment by vatex** [comment]
@varunjayaraman Unfortunatelly, only this error logged :/ I have tons of operations in database and I don't where and when happening...

**Comment by varunjayaraman** [comment]
I'll keep this open for a little bit longer in case anyone else wants to chime in, but I'll have to close it soon without more context since there's nothing much I can do without a code sample / some context

**Comment by ShiChenCong** [comment]
i have the same problem

**Comment by vkarpov15** [comment]
Please provide code sample
