### ISSUE TITLE
Errors thrown in pre validation middleware of sub doc result in Unhandled Rejection

### ISSUE THREAD

**Issue by c0d0g3n** [Automattic/mongoose#5215]
Errors that are thrown or passed to `next()` in the pre validation middleware of a sub doc are not propagated correctly to the error handler, but instead get lost somewhere (Unhandled Rejection) (forgive my terminology).

I assume this is a bug as pre save errors get caught correctly, as well as pre save and pre validate errors on regular (no sub doc) docs.

[Here is a gist](https://gist.github.com/c0d0g3n/ba2df311ea76963a066874b5183d1624) to reproduce the bug.

I'm using Mongoose 4.9.6.

**Comment by varunjayaraman** [comment]
thanks for the repro script, this looks like a bug.

**Comment by vkarpov15** [comment]
Issue's been fixed, fix will be released with 4.9.9
