### ISSUE TITLE
VersionError after call save on existing document, if it's model has array field.

### ISSUE THREAD

**Issue by basileos** [Automattic/mongoose#5218]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
VersionError: No matching document found for id ...
**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/basileos/ac5db70ac6a709b6c276862512e0b422.js
https://gist.github.com/basileos/ac5db70ac6a709b6c276862512e0b422.js
**What is the expected behavior?**
Document should be saved
**Please mention your node.js, mongoose and MongoDB version.**
Node.js: v6.10.0
mongoose: 4.9.7
mongoDB: v3.4.3

**Comment by varunjayaraman** [comment]
@basileos can i close this out?

**Comment by basileos** [comment]
@varunjayaraman sure, it fixed with #5221
