### ISSUE TITLE
mongoose out of sync with mongo driver: auto_reconnect => autoReconnect

### ISSUE THREAD

**Issue by japrescott** [Automattic/mongoose#5220]
I have noticed that the mongoose documentation, the information in this github repo and the code-examples are out of sync with the underlying [mongodb native driver 2.2](http://mongodb.github.io/node-mongodb-native/2.2/api/Server.html)
Within the mongoose code, i see many "auto_reconnect" variables that no longer seem to fulfil their intention as it is newly called "autoReconnect".

I started investigating after I noticed getting many timeouts and uncaught errors similar to those being mentioned in  [Bug4789](https://github.com/Automattic/mongoose/issues/4789).

mongodb: 3.4.4
mongoose: 4.9.7

**Comment by varunjayaraman** [comment]
thanks, but I'm not sure that's the issue. If you see here, the change to `autoReconnect` isn't backwards breaking:

https://github.com/mongodb/node-mongodb-native/blob/1e9ce89e62b3d9d2c74a73f83c45c892b0ca11e5/lib/server.js#L122-L123
