### ISSUE TITLE
MongoError: Cannot update 'updatedAt' and 'updatedAt' at the same time (followup to #5045)

### ISSUE THREAD

**Issue by johanneslumpe** [Automattic/mongoose#5222]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Using the `$currentDate` operator in `Model.update()` fails, because mongoose tries to update the timestamps internally

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const mongoose = require('mongoose');

const schema = new mongoose.Schema({ someProp: String }, { timestamps: true });
const TestModel = mongoose.model('TestModel', schema);

TestModel.create({ someProp: 'test' })
  .then(model =>
    TestModel.update(
      {
        _id: model._id,
      },
      {
        $currentDate: {
          updatedAt: true,
        },
        someProp: 'dummy',
      }
    ).exec()
  )
  .then(() => console.log('done'))
  .catch(console.log);
```

**What is the expected behavior?**
Mongoose should be checking for `$currentDate` and see if one of the updated properties is a timestamp and if so not update the property by itself. This behavior was working fine in earlier version of mongoose (last checked with 4.1.x). I assume that earlier version did **not** update `updatedAt` on a `Model.update()` call. But if that is the case, then this is a breaking change and should have been a major version increment. @vkarpov15 can you shed some light on this?

**Please mention your node.js, mongoose and MongoDB version.**
Node v4.4.3 and v6.9.1
Mongoose 4.9.7
MongoDB 3.2.10

**Comment by varunjayaraman** [comment]
thanks, this is probably a bug, although you shouldn't need to update the date in the `update()` call.

Here's a full repro script:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.set('debug', true);
const GITHUB_ISSUE = `gh-5222`;
const db = mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

const schema = new mongoose.Schema({ someProp: String }, { timestamps: true });
const TestModel = db.model('TestModel', schema);

TestModel.create({ someProp: 'test' })
  .then(model =>
    TestModel.update(
      {
        _id: model._id,
      },
      {
        $currentDate: {
          updatedAt: true,
        },
        someProp: 'dummy',
      }
    ).exec()
  )
  .then(() => console.log('done'))
  .catch(console.log.bind(console));
```

**Comment by johanneslumpe** [comment]
@varunjayaraman that's exactly my point: In 4.1.x we had to specify `updatedAt` in the `update()` call because it wouldn't properly update in the first place. Hence my thought about this being a breaking change.

**Comment by varunjayaraman** [comment]
@johanneslumpe i'm assuming the `updatedAt` property was previously updated and a bug cause `update()` to stop updating it, but @vkarpov15 would know better.

**Comment by vkarpov15** [comment]
This was intended as a bug fix for [4.1.11](https://github.com/Automattic/mongoose/blob/master/History.md#4111--2015-10-12), automatically setting timestamps for `update()` and `findOneAndUpdate()` seems like it's very much in-scope for mongoose's timestamps, and this fix removed a gaping hole in the functionality. Unfortunately, sometimes fixing a bug breaks workarounds for that bug, so thanks for reporting this :+1: The `$currentDate` pattern will succeed as of 4.9.9, although as of 4.1.11 you don't need it.

**Comment by johanneslumpe** [comment]
Awesome, thanks!

**Comment by BruceCham** [comment]
Awesome, thanks!
