### ISSUE TITLE
[Proposal] Reconsidering validator contexts and calling behavior

### ISSUE THREAD

**Issue by c0d0g3n** [Automattic/mongoose#5224]
When updating a property of a sub doc, like so:

    doc.sub.property = "value"
    doc.save()

Its validators are called twice, once in the context of the main doc and once in the context of the sub doc. This is probably intended behavior, however I would really consider thinking about this.

I encountered this "feature" because I needed to access a property's siblings in its validator function (f.i. to check whether a date is before another stored in the database). The current behavior makes the validator never pass, because depending on what context (`this`) you rely on, the following is thrown for the other context: `Cannot read property x of undefined`.

Now, I know I can easily work around this by normalizing what I receive, something along the lines of:

    let sub = this.sub || this

But this is just a hack, I think we face a more fundamental problem because Mongoose passes varying contexts to validators (and possibly more functions that operate on properties, like `required`, `set`...).

I think we should always start from the smallest document instance, because, while providing the parent (more possibly useful data) seems tempting, using the sub doc as a standalone would create varying contexts once again. (However I'm not sure whether that should be allowed anyway, but that's topic for another discussion :p.) We could enhance the context if we have more data to provide.

What if validators (and other functions) would receive something like below as value for `this`?

    {
		document: {
			// properties of sub doc
			sample: "test"
			// ...
		},
		parent: {
			// properties of parent
			subdoc: {
				sample: "test"
			}
			// ...
		}
	}

Note I chose for an extra layer to prevent naming conflicts with document properties, and allow for extensibility. (Monoose could hook extra properties and methods to `this`, that validators could use...) When used as a standalone, parent will not be present obviously. `document` should still be present though, to ensure we always provide the same context upon which we can rely then.

This would go behind an option (f.i. `richContext`) of course, to ensure backwards compatibility.

However, validators are still being called twice in some scenarios, which is redundant and inefficient. I think we should address that too. The validation should only be called on the sub doc level, in line with the reasoning above.

Let me know what you think :)

I'm using Mongoose 4.9.7 as of writing.

**Comment by varunjayaraman** [comment]
yeah i think this is an issue too, and it certainly feels like a hack to do something like:

```javascript
let sub = this.sub || this;
```

i think this is a repro script that captures the problem:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5224`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);
    const subSchema = new mongoose.Schema({
      name: String
    });

    // this only runs once
    subSchema.path('name').validate(function(name) {
      console.log('this', this.name); // undefined in context of parent schema
      // console.log('parent', this.parent()); // this would error
      return true;
    });

    const schema = new mongoose.Schema({
      subDoc: subSchema,
      age: Number
    });

    const Model = db.model('Model', schema);

    yield Model.remove({});
    
    const doc = new Model({ subDoc: { name: 'Test' }, age: 24 });

    yield doc.save();

    doc.subDoc.name = 'Another name';

    yield doc.save();
  });
}
```

I wonder if running the validators only once would be considered a breaking backwards change though so only fit for a major release?

**Comment by c0d0g3n** [comment]
@varunjayaraman This indeed shows the issue. (Sorry, I was a bit lazy not adding an example myself.) It is probably safer to change this in a major release, as backwards compatibility depends on how you work around this issue and what context is passed. Consider below validator:

    if (typeof this.sub !== "undefined") {
        // validate...
    }

In this case, validation will cease to work if we decide to only call the validator in the context of its sub doc.
Besides, changing what is passed to `this` will be breaking anyway, so we could ship the changes together? (Well I did mention we could put that under an option, I don't know...)

Anyway, thank you for your responses so far!

**Comment by vkarpov15** [comment]
Yeah this one is worth discussing more and definitely better saved for a major release. This behavior is not intentional, just a side effect of how single nested subdocs were originally implemented.

I think the solution is to run the validator with the subdoc as the context, because it's easy to get the parent doc from the child doc (`this.parent()`, or `this.ownerDocument()` to get the top level doc) but hard to go the other way. @c0d0g3n thoughts?

**Comment by c0d0g3n** [comment]
@vkarpov15 I didn't know about that method but that should do. We also need to make sure that the sub doc validators only run once.

When I get some time again to program, I'll investigate if this issue also happens with other functions (f.i. `required`).

**Comment by vkarpov15** [comment]
Thanks, I really appreciate your taking the time to look into this, very helpful :+1: :beers:

**Comment by hasezoey** [comment]
for anyone finding this and searching for a solution:
the `this` context in a `validate` function is the document of the schema the path is defined on, so if you want a separate context you would have to separate out the path into its own schema

```ts
// from
const schema = new mongoose.Schema({
  topLevel: {
    type: String,
    validate: function () {
      // the "this" context here is the full document of "schema"
      // code
    },
  },
  prop: {
    nested: {
      type: String,
      validate: function () {
        // the "this" context here is the document of "schema"
        // code
      },
    },
  },
});

// to
const propSchema = new mongoose.Schema({
  nested: {
    type: String,
    validate: function () {
      // the "this" context here is the document of "propSchema" (only the nested path)
      // code
    },
  },
});

const schema = new mongoose.Schema({
  topLevel: {
    type: String,
    validate: function () {
      // the "this" context here is the full document of "schema"
      // code
    },
  },
  prop: propSchema,
});
```

or like in the original issue description use the workaround of `const self = this.path || this`
