### ISSUE TITLE
Add option for destination field for Query#populate()

### ISSUE THREAD

**Issue by bitstrider** [Automattic/mongoose#5228]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
```javascript
var storySchema = Schema({
  _creator : { type: Number, ref: 'Person' },
  title    : String,
  fans     : [{ type: Number, ref: 'Person' }]
});

var Story  = mongoose.model('Story', storySchema);

Story
.findOne({ title: 'Once upon a timex.' })
.populate('_creator')
```

Pulled from the docs, this will replace/populate the `_creator` field containing the id with the associated `Person` doc

This seems semantically undesirable since, at least personally, the underscore `_` prefix is an indicator that a field is of an id type. Preferably in this instance, I'd like to populate the `creator` field with the `Person` doc, while leaving the `_creator` field intact.

So, I'd like to propose the addition of `dest` to the options param for `Query#populate()` to support this and other similar use cases without breaking its current default behavior.

```javascript
Story
.findOne({ title: 'Once upon a timex.' })
.populate({ path: '_creator', dest: 'theCreatorPerson' })
.exec(function (err, story) {
      if (err) return handleError(err);
      
      console.log('The creator is %s', story.theCreatorPerson.name)
      // prints "The creator is Guillermo"
})
```

**Comment by vkarpov15** [comment]
http://mongoosejs.com/docs/populate.html#populate-virtuals

**Comment by bitstrider** [comment]
@vkarpov15 thanks for that!
