### ISSUE TITLE
How to clone model and lock some filed?

### ISSUE THREAD

**Issue by JianChuanting** [Automattic/mongoose#5231]
In my case, I provide a basic service, and I want space docs for different consumers, for example a field _namespace.
I want to clone a new model with _namespace field locked to consumer's token from basic model to handle consumer's request.
My implementation:

```javascript
function genLocked(Model, lock = {}) {
  function Spaced(...args) {
    Model.call(this, ...args);
  }
  Spaced.prototype = Model.prototype;
  Object.assign(Spaced, Model);
  Spaced.__proto__ = Model;

  function lockedQuery(condition, ...args) {
    Object.assign(condition, lock);
    Model.Query.call(this, condition, ...args);
  }
  lockedQuery.prototype = Model.Query.prototype;
  Object.assign(lockedQuery, Model.Query);
  lockedQuery.__proto__ = Model.Query;


  Spaced.Query = lockedQuery;
  const clone = Model.schema.clone();
  Object.keys(lock).filter(path => typeof lock[path] !== 'undefined').forEach((path) => {
    const v = lock[path];
    const t = v.constructor || {};
    clone.path(path, {
      type: t,
      default: () => v,
    });
  });
  Spaced.schema = clone;
  return Spaced;
}
```

it works in v4.9.1, but in v4.9.2 not works.

**Comment by varunjayaraman** [comment]
Do you have a simpler version of what you're trying to do. I'm not too sure about what your actual problem is, and what exactly about it "doesn't work"?

**Comment by JianChuanting** [comment]
For example, User model
`
{
sys: String,
name: String
}
`
How to generate SysFooUser from User model, sys field locked to 'foo'.
`
SysFooUser.createOne({ name: 'a'}); // create {name: 'a', sys: 'foo'}

SysFooUser.findOne(); // query { sys: 'foo' }

`

**Comment by varunjayaraman** [comment]
are you saying you want the `SysFooUser` model to always include `{sys: 'foo'}` in its queries?

**Comment by varunjayaraman** [comment]
Why dont you just write a helper static method:

```javascript
SysFooUser.statics.findFoo = function(query) {
  return this.find(Object.assign({ sys: 'foo' }, query));
};
```

**Comment by JianChuanting** [comment]
sys is a dynamic field like id, can't define all of them...
`
SysFooUser.statics.findSys = function(sys, query, ...args) {
  return this.find(Object.assign(query, { sys }), ...args);
};
`
this way is effective. but need to wrap all of method used...if want use all features..
is there a lazy way to easily wrap all methods..such as  Model.insert Model.find ..... doc.save  and so on ?
all criterion and doc's sys field will be overwrite to a special dynamic value.

**Comment by JianChuanting** [comment]
I provide a basic service. every calling will has a sys paramters, its dynamic value.
I want to generate a isolated Model from common Model for every calling, other sys's doc cant be found and cant save any doc into other sys.
isolate by sys value.

**Comment by varunjayaraman** [comment]
Yeah that doesn't exist atm, although @vkarpov15 can correct me if I'm wrong. If I understand correctly, youre looking for a way to wrap all model methods with a default conditions object that contains a dynamic field.

This is a pretty niche use case, and I'm not sure if it's worth building out as a new feature. For now you could wrap the methods necessary, and I'l mark this as a feature request

**Comment by vkarpov15** [comment]
Sounds like [discriminators](http://mongoosejs.com/docs/discriminators.html) to me, no?

**Comment by varunjayaraman** [comment]
You mean using a discriminator to wrap all the model methods and then having every model inherit from that base class? I think that works, does that work for your use case @JianChuanting ?

**Comment by JianChuanting** [comment]
it seems ok. THX! @vkarpov15 @varunjayaraman

**Comment by varunjayaraman** [comment]
no problem
