### ISSUE TITLE
Authentication Failed 

### ISSUE THREAD

**Issue by Hanzofm** [Automattic/mongoose#5235]
I'm trying to enable auth into my mongo server. 

I've already done:
-Configured security into mongo.conf

-Created the users **(if use it with mongo -u -p..... from console the users works fine)**

In the node server js my config is this

`mongoose.connect(mongodb://user:pass@localhost:27017/dbName);`

Also I've already tried with

`mongoose.connect(mongodb://user:pass@localhost:27017/dbName,{auth:{authdb:"admin"}});`

this

`mongoose.connect(mongodb://user:pass@localhost:27017/dbName,{auth:{authdb:"dbName"}});`

And this:

`mongoose.connect("mongodb://user:pass@localhost:27017/dbName?authSource=admin");`

And always get this error:

Authentication failed

What would be doing wrong?

Node version: 6.10.3
Mongoose Version: 4.8.5
MongoDB version: 3.4.4

**Comment by dmolineuxcb** [comment]
It should be
```
let url = "mongodb://user:pass@localhost:27017/dbName";
mongoose.connect(url, {server: { poolSize: 10 }}, function(error) {
	if (error) {
                console.log("err", err);
	} else {
		console.log("woohoo");
	}
});
```

**Comment by varunjayaraman** [comment]
yeah why are you passing in the authSource option? There's a specific use case for it: https://docs.mongodb.com/manual/reference/connection-string/

**Comment by varunjayaraman** [comment]
hi @Hanzofm can you please clarify? Otherwise I'm marking this as stale and will close soon

**Comment by kunilkuda** [comment]
I have the same problem, and it solved by removing the 'authSource' param

```
/* Not working */
mongoose.connect("mongodb://localhost:27017/test", {
    "auth": { "authSource": "admin" },
    "user": "admin",
    "pass": "admin123",
    "useMongoClient": true
});
```
```
/* Working */
mongoose.connect("mongodb://localhost:27017/test", {
    "user": "admin",
    "pass": "admin123",
    "useMongoClient": true
});
```
Tested on Mongoose-v5.0.0

**Comment by gianpaj** [comment]
I got a similar issue:

works ✅:
```js
mongoose
  .connect('mongodb://host:27017/mydata', {
    user: 'myuser',
    pass: 'mypass',
  })
```

doesn't work ⛔️: 
```js
mongoose
  .connect('mongodb://myuser:mypass@host:27017/mydata')
```

```
node_modules/agenda/node_modules/mongodb/lib/mongo_client.js:462
            throw err
            ^
MongoError: Authentication failed.
    at Function.MongoError.create (node_modules/mongodb-core/lib/error.js:31:11)
    at node_modules/mongodb-core/lib/connection/pool.js:497:72
```

```
MongoDB server version: 3.6.2

"mongoose": "5.0.8"

user is located in the "mydata" database
```

**Comment by gianpaj** [comment]
Actually the issues was that I wasn't encoding the username using `encodeURIComponent()` 😅

**Comment by rjangir** [comment]
Works great!!
`mongoose
    .connect(`mongodb+srv://@clusterAnything.mongodb.net/test?retryWrites=true&w=majority`,
        {
            user: process.env.MONGO_USER,
            pass: process.env.MONGO_PASSWORD,
            useNewUrlParser: true,
            useUnifiedTopology: true
        })`

**Comment by rjangir** [comment]
mongoose
    .connect(`mongodb+srv://@cluster0-upr67.mongodb.net/test?retryWrites=true&w=majority`,
        {
            user: process.env.MONGO_USER,
            pass: process.env.MONGO_PASSWORD,
            useNewUrlParser: true,
            useUnifiedTopology: true
        })
