### ISSUE TITLE
save method return/resolve wrong object

### ISSUE THREAD

**Issue by rapkin** [Automattic/mongoose#5236]
I think `.save()` method works not as expected.
When I try to save item:
```js
const schema = Schema({value: String})
const model = mongoose.model('model', schema)

const item = new model({value: 'some value', _id: null})
const saved = await item.save()
console.log("saved", saved) // saved { __v: 0, value: 'some value', _id: null }
// but in database saved something like: { __v: 0, value: 'some value', _id: ObjectId("5911af9fc7ce1f179f66a0be") }
```

I think `.save()` method should return/resolve actually saved object.

Nodejs: v7.9.0
MongoDB: 3.4
Mongoose: 4.9.6

**Comment by basileos** [comment]
It's expected behaviour - ["Mongoose can't save a document without knowing its id"]( http://mongoosejs.com/docs/guide.html#_id)

**Comment by rapkin** [comment]
@basileos this guide doesn't apply to that problem. Problem in result of `.save()` method:
I expect to receive same object as in DB (with autogenerated _id), but method returns `_id: null`.
For example if `_id: undefined` all works as expected (result contains autogenerated field `_id: ObjectId(...)`)

**Comment by varunjayaraman** [comment]
`null` and `_id` are different values: `null` is the intentional absence of a value. Don't pass in `null` if you don't want it to be null

**Comment by varunjayaraman** [comment]
yeah i could see this being a bug. I think @basileos is right that grabbing the doc from the db is impossible without knowing the _id so maybe dont do that?

I wonder if we should throw an error if you pass `_id: null` without setting `_id: false` as an option?

**Comment by houssem-yahiaoui** [comment]
I do believe that the Db will add it whether you liked it or not, so like @varunjayaraman said, you probably don't want to use it, cause probably everything else will depend on that field, and set it as null, should definitely from my own understading be an error.

**Comment by rapkin** [comment]
I think method should return object that stored in the database. Error is also a good solution - but in this case behavior of library and behavior of MongoDB will be different (and it's not so good in my opinion).
```js
const item = new model({value: 'some value', _id: null})
const saved = await item.save() // should throw new Error or return something like {_id: ObjectId(...), value: 'some value'}
```
As I wrote - I prefer to get saved object.

**Comment by houssem-yahiaoui** [comment]
But with the auto generated id, is the expected native behaviour since the issue here is setting the _id to null, i saw it over the new milestone, hopefully that will return an error, i don't want to mess with _id's all over the place.

**Comment by fiznool** [comment]
I really think this should have been released as a breaking change. My app depends on creating a model with an _id equal to null and after much debugging I have realised that this commit has now broken my app.

**Comment by rapkin** [comment]
@fiznool but what is the reason for this (to set _id as null)?

**Comment by fiznool** [comment]
The model wasn't being saved to the database, it is used as an 'internal' model. But that's an implementation detail - my point was that this is a breaking change and should have been released in a new major version.

**Comment by vkarpov15** [comment]
@fiznool you're right, sorry about the inconvenience. The actual bug here was not that `_id` should not be null, but that the model thought the `_id` was null when it actually wasn't. I opened up an issue :point_up: to fix that for the next minor release.
