### ISSUE TITLE
TypeError: Cannot read property 'saveSubdocs' of undefined

### ISSUE THREAD

**Issue by bonesoul** [Automattic/mongoose#5238]
with 4.9.8 i started getting the error.
with 4.9.7 i don't see any errors.

any ideas?

**Comment by gastonelhordoy** [comment]
I'm facing a similar situation, error message is slightly different, but it also started after updating to version 4.9.8:

`TypeError: Cannot read property '0' of undefined`

**Comment by varunjayaraman** [comment]
please provide a repro script, i can't debug this without seeing the code

**Comment by bonesoul** [comment]
i'll try to nail down the actual offending code and provide you one.

**Comment by bonesoul** [comment]
i've tracked this down to: https://github.com/cbargren/express-brute-mongoose/blob/master/lib/index.js

**Comment by varunjayaraman** [comment]
Can you please post the full stack trace?

**Comment by bonesoul** [comment]
I think this is actually caused by the mentioned package itself and reported to them, but i'll still post the stack trace.

**Comment by vedmalex** [comment]
the same issue. Reverted back to working version.

**Comment by vkarpov15** [comment]
Please post a stack trace and code samples. A single error message and a sentence of prose is not an actionable bug report.
