### ISSUE TITLE
Custom Schema Required Fields and Middleware

### ISSUE THREAD

**Issue by c1moore** [Automattic/mongoose#5241]
I am trying to figure out how to add basic functionality of a normal schema to a custom schema.  For example, I would like to make fields required, have `pre` and `post` hooks, etc.  At the moment it is not clear _if_ I can do this or _how_ I would go about it if this is supported.  If adding this behavior is not supported, this is a feature request.  If this behavior is supported, this is a "bug" report for the documentation.

Below is an example of what I would like to do.  Imagine I have the following schema called `LaptopSchema`:

```javascript
var LaptopSchema = new Schema({
  cpu:  {
    type:     String,
    required: true
  },
  ram:  {
    type:     Number
  }
});

LaptopSchema.pre('save', function() {
  // Do something.
});
```

How would I properly convert this into a custom schema type that behaves the same as above?

Presumably, I could throw an error in the constructor for a required field, but this doesn't make sense based on current behavior by builtin schemas.  For example, a required field isn't actually checked until the document is about to be saved.  While I am fine with throwing an error if a required field is not specified at construction time, will mongoose be able to handle this?  Also, if `cast()` is defined on the same class that defines the structure of the schema (e.g. `class Laptop extends mongoose.SchemaTypes`), it appears that the constructor would have to be able to handle no arguments (unless the document is passed to the class that defines `cast()`).  Below is an example of what I imagine are the two possibilities for mongoose when calling cast:

Method 1:
```javascript
  var schemaInstance = new CustomSchema();
  var castedObj = schemaInstance.cast(document);
```

Method 2:
```javascript
  var schemaInstance = new CustomSchema(document);
  var castedObj = schemaInstance.cast(document);
```

If Method 1 is used and the custom schema class also extends `mongoose.SchemaTypes`, it cannot throw an error in the constructor when a required field is omitted.  If Method 2 is used, why pass the object into `cast()`?  It would make more sense to make `cast()` a static method of the custom schema class, that way you could do something like `var castedObj = CustomSchema.cast(document);`.  Since the class is passed into the schema definition, this would make more sense (from the outside looking in, granted).

**Do you want to request a *feature* or report a *bug*?**
Not sure, it depends on whether the functionality exists or not (explained above).

**What is the current behavior?**
It either is not possible to extend custom schemas with `pre` and `post` hooks (and the like) or the documentation does not clearly show how to do so.

**What is the expected behavior?**
Custom Schemas should be able to be extended in the same way that builtin schemas can be extended and it should be documented [here](http://mongoosejs.com/docs/customschematypes.html).

**Please mention your node.js, mongoose and MongoDB version.**
Node: 6.9.5
Mongoose: 4.8.4
MongoDB: 3.4.2

**Comment by varunjayaraman** [comment]
@vkarpov15  might have more information on the motivation behind `cast()`'s design.

As for your question about extending custom schemas, I think you are conflating a schema and a custom type. All mongoose schemas are custom in a way aren't they? You can customize them with various hooks. So why can't you just put a pre hook on a schema that contains a field with the custom type and run whatever logic you need?

**Comment by c1moore** [comment]
@varunjayaraman When I say custom schema type, I am referring to the schema types mentioned [here](http://mongoosejs.com/docs/customschematypes.html).  Basically a Schema alone won't do for what I am wanting to accomplish and a Model is overkill.

I basically want a class so that I can create instances of the class that can be converted into a Schema I can save in other models elsewhere.  A model won't do because that creates a (useless) table in the database and a schema alone won't do because I cannot create an instance of a schema.  There are also some other limitations of models that I may run into (e.g. [no support for multi-level inheritance](https://github.com/Automattic/mongoose/issues/2851)).  That's why I turned to "Custom Schema Types".  The example above is quite simple and really doesn't elude to the underlying problem.

**Comment by vkarpov15** [comment]
You can't add pre or post hooks to custom types, you really should use a single nested schema if you really need that functionality. What exactly do you mean by "create an instance of a schema"? If you do something like `const personSchema = new Schema({ laptop: LaptopSchema });` and set `new Person({ laptop })` mongoose will cast the laptop doc to the laptop schema...

**Comment by c1moore** [comment]
I'm pretty sure custom types aren't what I'm looking for anymore and I don't think what I want is supported natively by mongoose.  However, by "create an instance of a schema" I was referring to something like the following situation.

```javascript
  var laptop = new Laptop();

  // Do some processing, maybe even some I/O.
  laptop.setRam(magicRamNumber);
  laptop.setCpu(magicCpuModel);

  // A little later often I somehow obtain a user
  user.addLaptop(laptop);

  user.save();
```

In the example above, I need to create an instance of a `Laptop`, which is and should be a class.  I create an instance of `Laptop` before I know the user, so I cannot simply pass the Laptop's data to a `User` object.  The user may already exist or may need to be created, that is beside the point and unknown while I am setting up the `Laptop`.

Here are some of the requirements I was trying to accomplish:
- I want to create an instance of `Laptop`.  As I said early, it makes sense for `Laptop` to be a class of its own.  I may use that instance to do computation or for constructing something larger.
- Laptop doesn't need its own database table/collection, which means I cannot create a `Laptop` model. 
 Even if it were OK to create a model for `Laptop`, there are limitations to using a model over using a pure JS class.  Furthermore, this kinda boxes me into using mongoose forever if I build all of my business logic around mongoose (in case you're wondering why this is a bad idea, [check out this video](https://www.youtube.com/watch?v=Nltqi7ODZTM)).

In one sentence, I want a `Laptop` class to exist that I can create instances of and eventually store to the database as part of another model, if I choose to do so, but that does not create a collection in the database.

**Comment by vkarpov15** [comment]
If you're concerned about building all your business logic into mongoose you could keep `Laptop` as a separate class independent of mongoose, and then [load that class into a schema](http://mongoosejs.com/docs/advanced_schemas.html) so you can access the same methods within mongoose.

**Comment by c1moore** [comment]
That is closer to what I wanted, but still not quite there.  I ended up making a class that did what I wanted, so I agree this issue can be closed.  If my company ends up open-sourcing it, which we are discussing along with some other modules, I'll add a link to it here.

Thanks for you help.
