### ISSUE TITLE
Skipping documents that were inserted with $position

### ISSUE THREAD

**Issue by OKrawi** [Automattic/mongoose#5242]
Hi, 
When I push into an array of a document the _id of another document using $position: 0 , and then I run populate with skip as an option, mongoose skips from the bottom.

Here's the schema : 
```
const mongoose   = require("mongoose");
const fooSchema= new mongoose.Schema({
  bars: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: "bar"
    }]
});
module.exports = mongoose.model("Foo", fooSchema);
```
Here's my update function: 

```
Foo.findByIdAndUpdate(foo_id, {'$push': {'bars': { "$each" : [bar_id], "$position": 0}}})
     .exec((err, foo) => {
          if(err){ return handleError(err)}
          // do something
});
```
Here's my query:

```
Foo.findById(foo_id, 'bar').populate({ path: 'bars', options: { skip: 10, limit: 10})
     .exec((err, foo) => {
          if(err){ return handleError(err)}
          // do something
});
```
This will actually skip the last ten documents ( it will skip from the bottom ), so if i have 15 documents in my collection, this will return the first five documents only. However, I think it should skip the first 10 items and return the last five only. 

Is this the expected behavior? Am I doing something wrong? 
I am new to MongoDB and mongoose, and I am still learning, but I believe something is wrong here. 
If this is how it should work please tell me how can I achieve this feature. I would like new 'bars' to be added at the start of the Foo array so that I always return the newest 'bars' to the user.

I am using the latest versions of both mongoose and node. 

Cheers and thanks a miliion for your work.

**Comment by varunjayaraman** [comment]
actually it seems to skip from the beginning documents for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const assert = require('assert');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5242`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const bookSchema = new mongoose.Schema({ name: String });

    const Book = db.model('Book', bookSchema);


    const authorSchema = new mongoose.Schema({
      name: String,
      books: [{ type: mongoose.Schema.Types.ObjectId, ref: 'books' }]
    });

    const Author = db.model('Author', authorSchema);

    yield [Book.remove(), Author.remove()];

    /**
     * Create books this way to guarantee insertion order
     */
    const books = [
      yield Book.create({ name: 'book 1' }),
      yield Book.create({ name: 'book 2' }),
      yield Book.create({ name: 'book 3' })
    ];

    const author = yield Author.create({
      name: 'ze author',
      books: books.map(book => book._id)
    });

    const newBook = yield Book.create({ name: 'book 4' });

    const updatedAuthor = yield Author.findByIdAndUpdate(
      author._id,
      {
        $push: {
          books: {
            $each: [newBook._id],
            $position: 0
          }
        }
      },
      { new: true }
    );

    console.log(`Updated book ${newBook._id.toString()}`);

    const populatedAuthor = yield Author
      .findById(author._id)
      .populate({
        path: 'books',
        model: Book,
        options: { skip: 2, limit: 2 }
      });
    
    console.log(`Populated Author`, populatedAuthor);

    const populatedBooks = populatedAuthor.books;
    assert.equal(populatedBooks[0].name, 'book 4');
    assert.equal(populatedBooks[1].name, 'book 3');
  });
}
```

Does this script error for you (note the `assert`s at the bottom)?

**Comment by OKrawi** [comment]
Hi, 
Thanks for the follow up.

If I understood your example correctly, you pushed book 4 to be at position [0] of the array, therefore the books array should be something like: 
```
[
   book4._id,
   book1._id,
   book2._id,
   book3._id
]
```

Then when you skip two items, I should get books 2 and 3, because books 4 and 1 (which are supposedly at the beginning of the array) are skipped.  

For the test to be correct change the `assert `s at the bottom to be: 
```
    assert.equal(populatedBooks[0].name, 'book 2');
    assert.equal(populatedBooks[1].name, 'book 3');
```

**Comment by varunjayaraman** [comment]
so i guess i think of `$skip` as skipping inside the collection itself and not the array you are populating. If you think about it, books 3 and 4 were the last 2 books created. 

I could label this a feature request (treating `$skip` differently inside a populated array), but I honestly think it's not necessary. What you're looking for can be accomplished with a simple filter or a sort on the array before you populate it.

thoughts @vkarpov15 ?

**Comment by OKrawi** [comment]
Thanks on the clarification on `$skip`, I wasn't aware that it skips inside the collection itself.  
I have already found a way to accomplish what I needed. 

I believe you are right, this is not really necessary. 
Thank you and sorry for the trouble.

**Comment by varunjayaraman** [comment]
no worries, all issues are appreciated :)
