### ISSUE TITLE
Can't create a Document with Mongoose

### ISSUE THREAD

**Issue by zulbil** [Automattic/mongoose#5243]
I'm trying to figure out what exactly is happening when i want to add a document to the mongoDB database. 

When i try to add a document i'm getting this error: 
```
{
"errors": {
"name": {
"message": "Path `name` is required.",
"name": "ValidatorError",
"properties": {
"type": "required",
"message": "Path `{PATH}` is required.",
"path": "name"
},
"kind": "required",
"path": "name"
}
},
"message": "Product validation failed",
"name": "ValidationError"
}
```

So i'm using Express Js and Mongoose to perform this action. 
In my model: product.js
**********************************************************
```
var mongoose = require('mongoose'); 

var productSchema = new mongoose.Schema({
	name: {type: String, required: true}, 
	category: {type: String, default: ''}, 
	price: { type: Number, default: 0}, 
	picture: { type: String}, 
	quantity: {type: Number, default: 0}, 
	status: { 
		type: String, 
		enum: ['pending', 'In Progress', 'Cancelled', 'Done'], 
		default: 'pending' 
	}, 
	date: { type: Date, default: Date.now}, 
	description: { type: String}, 
	owner: {type: String}
}); 

var Product = mongoose.model('Product', productSchema); 

module.exports = Product; 
```
*******************************************************************

In my api routes, when i define the path for performing this action: 
index.js 
********************************************************************
```javascript
var express = require('express'); 
var router = express.Router(); 
var productCtrl = require('../controllers/productCtrl'); 

router.get('/products', productCtrl.getAllProducts); 
router.get('/products/:productId', productCtrl.readProduct); 
router.post('/products', productCtrl.createProduct); 
router.delete('/products/:productId', productCtrl.removeProduct); 
router.put('/products/:productId', productCtrl.updateProduct); 

module.exports = router; 
```
******************************************************************
Finally, in my controller file: 
productCtrl.js
******************************************************************
```javascript
var Product = require ('../models/products'); 
var sendJsonResponse = function(res, status, content) {
   res.status(status);
  res.json(content);
}
 module.exports.createProduct = function (req, res){
	Product
		  .create({
		  	name: req.body.name, 
		  	category: req.body.category, 
		  	price: req.body.price, 
		  	picture: req.body.picture, 
		  	quantity: req.body.quantity,
		  	status: req.body.status, 
		  	date: req.body.date, 
		  	description: req.body.description, 
		  	owner: req.body.owner

		  }, function createProduct(err, product){
		  	if(err){
		  		sendJsonResponse(res, 404, err); 
		  		return; 
		  	}
		  	else {
		  		sendJsonResponse(res, 201, product); 
		  	}
		  });
} 
```
*******************************************************************

The behavior excepted is that i should have product document returned in json format 

About my environnement, i'm using : 
node.js: 6.9.4
mongoose: ^4.9.8
mongodb: 3.2.7
Os: Windows 10

I really need help guys

**Comment by varunjayaraman** [comment]
the error message is saying that the `field` name is undefined when you are creating the document. Can you log `req.body` and show the contents? My guess is that it doesnt have `.name` set

**Comment by zulbil** [comment]
Actually in my postMan Client, i fill all the fiels of my product Model. It's finally works. I have just installed the latest version of mongoDb, I mean mongoDb version 3.4.4. And everything works ![bitmoji](https://render.bitstrips.com/v2/cpanel/9281517-267514955_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by varunjayaraman** [comment]
sounds good, i'm going to close this issue then
