### ISSUE TITLE
Mongoose hangs up with $or and $regex.

### ISSUE THREAD

**Issue by serge-nikitin** [Automattic/mongoose#5245]
Here is the problem code:

```
async function findByIdOrNameCaseInsensitive(value) {
  const regex = new RegExp(value.toLowerCase().trim(), 'i')
  const res = await models.Channel.findOne({
    $or: [
      { _id: { $regex: regex } },
      { name: { $regex: regex } }],
  })
  console.log(res)
  return res
}
```

This code works fine when there is a result, when it can found anything. But for the case without result this code doesn't return null, it just hand up.

I checked the same logic in mongo console, and it works fine with the same test data:
```
db.channels.findOne({     $or: [       { _id: { $regex: /cbn/i } },       { name: { $regex: /cbn/i } }]   })
```
This request returns one document, and Mongoose returns the same.

***************
```
db.channels.findOne({     $or: [       { _id: { $regex: /cbn2/i } },       { name: { $regex: /cbn2/i } }]   })
```
This request returns null in mongo console, but Mongoose hangs up.

Node v7.9.0
Mongoose v4.9.8

**Comment by serge-nikitin** [comment]
It looks like the problem with $regex and no result.

This request has result and returns it:
`let channel = await models.Channel.findOne({ _id: { $regex: /cbn/ } })`

This request doesn't have result and hangs up:
`let channel = await models.Channel.findOne({ _id: { $regex: /cbn2/ } })`

**Comment by indatawetrust** [comment]
Hi. I was having a similar problem. In the node-mongodb-native tests, I saw https://github.com/mongodb/node-mongodb-native/blob/70dffb8ca098b71ed154accfc05bc2bbcd2b9ede/test/functional/examples_tests.js#L172. I tried and worked without RegExp. Could you try your code in the following way. I hope it works.

```js
async function findByIdOrNameCaseInsensitive(value) {
  value = value.toLowerCase().trim();

  const res = await models.Channel.findOne({
    $or: [
      {
        _id: {
          $regex: value,
          $options: 'ig',
        },
      },
      {
        name: {
          $regex: value,
          $options: 'ig',
        },
      },
    ],
  });

  console.log(res);

  return res;
}
```

**Comment by varunjayaraman** [comment]
my suspicion is that you are not catching your error from your async function and it's silently failing because you're using a `$regex` on an `ObjectId`. See in the following script how ONLY case 5 triggers an error:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const assert = require('assert');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5245`;

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String
    });

    const Model = db.model('Model', schema);

    yield Model.remove();

    yield Model.create({ name: 'cbn' });

    const successRegex = new RegExp('cbn', 'i');
    const failureRegex = new RegExp('cbn2', 'i');
    const failureRegex2 = new RegExp('cbn3', 'i');
    
    setTimeout(() => { throw new Error(`MONGOOSE HUNG ON FINDONE`) }, 5000);

    // 1) SUCCESS CASE WITH $or AND $regex
      // const doc = yield Model.findOne({
      //   $or: [
      //     { name: { $regex: successRegex } },
      //     { name: { $regex: failureRegex } }
      //   ]
      // });
      // assert.ok(doc);

    // 2) SUCCESS CASE WITH JUST $regex
      // const doc = yield Model.findOne({ name: { $regex: successRegex } });
      // assert.ok(doc);
    
    // 3) FAILURE CASE WITH JUST $regex
      // const doc = yield Model.findOne({ name: { $regex: failureRegex } });
      // assert.ok(!doc);
    
    // 4) FAILURE CASE WITH $regex AND $or
      // const doc = yield Model.findOne({
      //   $or: [
      //     { name: { $regex: failureRegex } },
      //     { name: { $regex: failureRegex2 } }
      //   ]
      // });
      // assert.ok(!doc);
    
    // 5) REGEX ON _id
      const doc = yield Model.findOne({
        $or: [
          { _id: { $regex: failureRegex } },
          { name: { $regex: failureRegex } }
        ]
      });
      assert.ok(!doc);
  });
}
```

**Comment by varunjayaraman** [comment]
hi @serge-nikitin can you please clarify if catching your error solves your issue? I'm going to mark this as stale and will close soon unless the issue persists

**Comment by serge-nikitin** [comment]
@varunjayaraman 

There were no any errors with regex, _id, and ObjectId. My model has _id: string type. 
But now I can't reproduce the problem too.

**Comment by varunjayaraman** [comment]
Ok if you can't repro, I'm going to closet he issue. Feel free to open up again when youve found a way to reproduce it

**Comment by vaishusawant18** [comment]
let findQuery = {
                $and: [{
                    $or:
                        [
                            { 'title': { $regex: value, $options: 'i' } },
                            { 'description': { $regex: value, $options: 'i' } },
                            { 'reminder': { $regex: value, $options: 'i' } },
                            { 'color': { $regex: value, $options: 'i' } }
                        ]
                }, { 'userId': noteRequestData.userId }]
            }
