### ISSUE TITLE
Blocker - Mongoose v4.9.9 hangs on call to connect()

### ISSUE THREAD

**Issue by erezool** [Automattic/mongoose#5249]
It simply hangs during the mongoose.connect() (callback is never called)

**Comment by cortezcristian** [comment]
Same here, had to downgrade to v4.9.8

**Comment by jeffwhelpley** [comment]
Same here. downgraded.

**Comment by sshen81** [comment]
Same issue. As a workaround, using promises resolved it for me.

**Comment by varunjayaraman** [comment]
Hm, that's weird. The callback executes for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5249`;


exec();

function exec() {
  mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`, function() {
    co(function* () {
      const schema = new mongoose.Schema({
        name: String
      });


      const Model = mongoose.model('Model', schema);

      yield Model.remove({});

      const doc = yield Model.create({ name: 'test' });

      console.log('successfully created doc');
    }).catch(error => console.error(error));
  });
}
```

**Comment by erezool** [comment]
Apologies, I apparently did not mention important information:

- I overwrite mongoose default Promise to bluebird
- I try to connect to a replica set

Here's a reproducible example:
```javascript
var mongoose = require('mongoose');
var bluebird = require('bluebird');

mongoose.Promise = bluebird;

var conn = 'mongodb://primary,secondary/test?replicaSet=test';
mongoose.connect(conn, function(err, result) {
        console.error('Errori:', err);
});
```
Actual result: code hangs and console.error never printed.

**Comment by jeffwhelpley** [comment]
I am having the issue and I connect to a replica set as well. I do not override the promise library, but promises are hanging.

**Comment by vkarpov15** [comment]
Fixed, my sincerest apologies for the trouble, some of the refactoring work for #5229 made it so that the callback to `mongoose.connect()` doesn't get called in 4.9.9. Mongoose does connect successfully, it just doesn't call the callback. Will release 4.9.10 immediately to fix this issue :+1:
