### ISSUE TITLE
Set field behaviour broken (no default)

### ISSUE THREAD

**Issue by alem0lars-yoroi** [Automattic/mongoose#5257]
When I try to set a field to a javascript object (without merging the single fields) the default values aren't considered.

**Comment by houssem-yahiaoui** [comment]
Mind share your code sample, so we can have a better idea of where your problem is coming from ?

**Comment by vkarpov15** [comment]
I'm going to close this, this is a poster child for non-actionable bug reports. Please follow the issue template next time.
