### ISSUE TITLE
Aggregate.sort() doesn't work with text search

### ISSUE THREAD

**Issue by johnrodes** [Automattic/mongoose#5258]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When sorting by [relevance score](https://docs.mongodb.com/v3.2/tutorial/text-search-in-aggregation/#return-results-sorted-by-text-search-score), the sort() method swaps the ```{ score: { $meta: "textScore" } }``` for ```{ score: 1 }```

```javascript
const aggregate = Cakes.aggregate();
aggregate.match({ $text: { $search: "chocolate" } });
aggregate.sort({ score: { $meta: "textScore" } });
```

The resulting query logged with mongoose.set('debug', true):
```javascript
cakes.aggregate([{ '$match': { '$text': { '$search': 'chocolate' } } }, { '$sort': { score: 1 } }])
```

**What is the expected behavior?**
```javascript
cakes.aggregate([{ '$match': { '$text': { '$search': 'chocolate' } } }, { '$sort': { score: { '$meta': 'textScore' } } }])
```
**Please mention your node.js, mongoose and MongoDB version.**
Node: v6.3.10
MongoDB: v3.2.13
Mongoose: v4.9.9

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in 4.10.1 :+1:
