### ISSUE TITLE
Can't populate data when selecting attributes.

### ISSUE THREAD

**Issue by muhammadfaizan** [Automattic/mongoose#5261]
I am using 4.4.20

Its a bug that i want to report.

` MyModel.find({})
                .populate({path: 'attr', select: 'type'})`
when I call this function,
The returned data only has one field that is `_id` of _attr_
I also tried 

` MyModel.find({})
                .populate({ 'attr', 'type'})`
it didnt work either.
I only get  _id populated but not 'type' is it some sort of restriction, that i can't use a field named _'type'_.

**Comment by vkarpov15** [comment]
What do your schemas look like?

**Comment by varunjayaraman** [comment]
@muhammadfaizan can you please clarify what your schemas look like? This is 18 days old so it's a bit stale, so I'll need to close this soon without further information
