### ISSUE TITLE
Why mongoose changes _id to id for subdocument?

### ISSUE THREAD

**Issue by codeofnode** [Automattic/mongoose#5262]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
when we add a subdocument, probably with `$` option, mongoose changes _id to id

```
mongoose.model('colname').update({someFilter:true},{{ "$addToSet" : { "subDocumentArray" :  { "$each" : [ {name:"ABC",_id:CustomObjectId }]  } } } })
```
the `{name:"ABC",_id:CustomObjectId }` results as  `{name:"ABC",id:StringOfCustomObjectId }`

Where is _id gone in db, i need _id for all the sub document as well.
And there is id instead of _id. I need only _id, not at all any id.
SubDocument has the simple schema `{ name : String }` without any _id or id option.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
mongoose.model('colname').update({someFilter:true},{{ "$addToSet" : { "subDocumentArray" :  { "$each" : [ {name:"ABC",_id:CustomObjectId }]  } } } })
```

**What is the expected behavior?**
Inside database the subdocument should be as `{name:"ABC",_id:CustomObjectId }`

**Please mention your node.js, mongoose and MongoDB version.**
node : v7.10.0
├─┬ mongoose@4.7.9
│ ├─┬ mongodb@2.2.22
│ │ ├── mongodb-core@2.1.7

**Comment by vkarpov15** [comment]
Can't repro, below script gives me the correct output. Please modify the script to reproduce your issue:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/test');

async function start() {
  const mySchema = new Schema({ docArr: [{ name: String }] });
  const M = mongoose.model('Test', mySchema);

  await mongoose.connection.dropDatabase();
  await M.create({});

  const update = { $addToSet: { docArr: { $each: [{ _id: new mongoose.Types.ObjectId(), name: 'Test' }] } } };
  const res = await M.findOneAndUpdate({}, update, { new: true });
  console.log(res);
}

start().catch(error => console.error(error.stack));
```

Output:

```javascript
$ node gh-5262.js 
Mongoose: tests.insert({ _id: ObjectId("5920750902094c43a13ad16c"), docArr: [], __v: 0 })
Mongoose: tests.findAndModify({}, [], { '$addToSet': { docArr: { '$each': [ { _id: ObjectId("5920750902094c43a13ad16d"), name: 'Test' } ] } } }, { new: true, upsert: false, remove: false })
{ _id: 5920750902094c43a13ad16c,
  __v: 0,
  docArr: [ { name: 'Test', _id: 5920750902094c43a13ad16d } ] }
^C
$ 
```

**Comment by codeofnode** [comment]
Apologies,

I just reverted to that project under issue and found i was using toObject
custom transform method.

Its just not a bug.
Apologies again.
Please close it.
