### ISSUE TITLE
DeleteMany

### ISSUE THREAD

**Issue by kamarajuPrathi** [Automattic/mongoose#5263]
when I am using entityModel.deleteMany(filter)

it returns me 
`{
  "n": 3,
  "opTime": {
    "ts": "6420947176620294147",
    "t": 6
  },
  "electionId": "7fffffff0000000000000006",
  "ok": 1
}`

instead of 

`{ "acknowledged" : true, "deletedCount" : 3 }`

**Comment by vkarpov15** [comment]
Weird. Can you provide a more complete code sample that repros this issue? Also, is the 2nd example something that the mongodb shell returns?

**Comment by varunjayaraman** [comment]
@kamarajuPrathi do you have a code sample or repro script? Without further context it's hard to repro this. I am marking this as stale for now and will close soon since its not actionable without further information.

**Comment by mendoanjoe** [comment]
i have same issue with deleteMany, iam using `"mongoose": "^5.2.3",`

**logs**
```
2018-07-21T09:29:03.932112+00:00 app[web.1]: deleteMany
2018-07-21T09:29:03.935454+00:00 app[web.1]: { n: 0,
2018-07-21T09:29:03.935456+00:00 app[web.1]: opTime:
2018-07-21T09:29:03.935460+00:00 app[web.1]: { ts: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1532165337 },
2018-07-21T09:29:03.935463+00:00 app[web.1]: t: 1 },
2018-07-21T09:29:03.935464+00:00 app[web.1]: electionId: 7fffffff0000000000000001,
2018-07-21T09:29:03.935466+00:00 app[web.1]: ok: 1 }
```

**script**
```
exports.deleteKeranjangIf = (lineIds, isStatus) => {
  Pesanan.deleteMany({status: isStatus, lineId: lineIds}, (err, res) => {
    if(err){return console.log(err)};
    console.log("deleteMany")
    return console.log(res);
  });
};
```

**Comment by biblicalph** [comment]
I'm using `"mongoose": "^5.4.3"`. 
```
const result = await PersonModel.deleteMany({ firstName: "john" })
```
`result` is an object with 2 fields as below
```
{
   n: 1
   ok: 1
}
```

**Comment by vkarpov15** [comment]
@biblicalph yes that's [exactly what the docs say](https://mongoosejs.com/docs/api.html#query_Query-deleteMany) should be returned. Is there a problem here that I'm missing?
