### ISSUE TITLE
support question - TTL indexes in MongoDB version <3.x

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5266]
Any idea if TTL indexes are supported in MongoDB version 2.x?

https://docs.mongodb.com/manual/core/index-ttl/

definitely supported in 3.4

thanks!

**Comment by vkarpov15** [comment]
2.x covers about 4 years of code so you'll have to be more exact about which version you're concerned about. Based on my reading [TTL indexes were introduced in 2.2.0](https://docs.mongodb.com/v2.2/tutorial/expire-data/) so you should be good.

**Comment by ORESoftware** [comment]
Thanks that helps
