### ISSUE TITLE
Update validators checking for required fields [subdocuments]

### ISSUE THREAD

**Issue by enrichz** [Automattic/mongoose#5269]
I'm using findOneAndUpdate ($set and $unset) with the option runValidators: true.
I see from the documentation that it does not check for required fields if not explicitely using $unset.
Does anyone know a workaround for this?
How likely will this behaviour change in the future?
Thanks

**Comment by vkarpov15** [comment]
What exactly are you trying to achieve? `required` doesn't really make sense with update validators because mongoose doesn't know whether the field is set or not when it is running validation.

**Comment by enrichz** [comment]
This is the scenario:
```javascript
var dSchema = new mongoose.Schema({
  d1: {
    type: String,
    required: true
  },
  d2: {
    type: String
  }
}, {_id: false});

var toastSchema = new Schema({
  _id: {
    type: String,
    required: true
  },
  a: {
    type: String
  },
  b: {
    type: Number,
    required: true,
    max: 2,
    min: 1
  },
  c: {
    c1: {
      type: Number,
      required: true,
      max: 2,
      min: 1
    },
    c2: {
      type: String
    }
  },
  d: dSchema
});
mongoose.model("Toast", toastSchema);
```

When I update a document, I could insert an object without d1, which is required. Let's say I have this document in the db:
```javascript
{
      _id: "aaa",
      a: "hi",
      b: 1,
      c: {
        c1: "how",
        c2: "are"
      },
      d: {
        d1: "you",
        d2: "doing"
      }
}
```
Then I can perform the following code without errors:
```javascript
Toast.findOneAndUpdate({_id: "aaa"}, 
      {$set: {d: {d2: "today"}}},
      { runValidators: true }, 
  function(err) {
    if (err) {
      // no errors here
    }
    ...
});
```
I find this to be a odd behaviour, am I missing something?

**Comment by varunjayaraman** [comment]
yeah, i would use `document.save()` in this case. an update op won't validate or required fields unless you use `$unset`

**Comment by enrichz** [comment]
Also, c1 gets validated correctly:
```javascript
Toast.findOneAndUpdate({_id: "aaa"}, 
      {$set: {c: {c1: 5}}},
      { runValidators: true }, 
  function(err) {
    if (err) {
      // error here!
    }
    ...
});
```
This code throws an error as expected: ValidatorError: Path `c.c1` (5) is more than maximum allowed value (2).

**Comment by varunjayaraman** [comment]
It isnt validating for the `required`, but for `max`. Can you try using `.save`? Or does that not meet your use case?

**Comment by enrichz** [comment]
Yeah I know it's for `max`, I was just wondering why validate `max` and not `required`, that's all. Unfortunately I can't use `save`.
Is this considered a bug or a wanted behaviour? I just need to know if I have to implement some application logic to fix this or wait for a future release.

**Comment by vkarpov15** [comment]
When you `$set`, mongoose has no way of knowing what fields are already set on the document in MongoDB, so update validators don't run unless you explicitly set or unset. It's an inconsistent behavior, but update validation doesn't really work right without this inconsistency

**Comment by enrichz** [comment]
I understand that mongoose doesn't know what's on MongoDB, and the fact that it validates only the fields that are being set makes perfect sense.
The problem is with the nested documents. From my example, I would expect that when I `$set` the field `d` of the document (so `d` is being `$set`), mongoose would validate the entire thing that I'm setting ( `{$set: {d: {d2: "today"}}}` ). At the time of the operation, mongoose does know which fields are present (ie: `d2`) and which are not (ie: `d1`), and it doens't need to know what's on the db.
I hope I explained myself.

**Comment by enrichz** [comment]
I made a mocha test for this:
```javascript
'use strict'

const mongoose = require('mongoose')
const Schema = mongoose.Schema
const mongoUrl = 'mongodb://localhost/test-issue5269'

/*
 * DEFINE SCHEMAS AND MODEL
*/
const dSchema = new mongoose.Schema({
  d1: {
    type: String,
    required: true
  },
  d2: {
    type: String
  }
}, {_id: false})

let toastSchema = new Schema({
  _id: {
    type: String,
    required: true
  },
  a: {
    type: String
  },
  b: {
    type: Number,
    required: true,
    max: 2,
    min: 1
  },
  c: {
    c1: {
      type: Number,
      required: true,
      max: 2,
      min: 1
    },
    c2: {
      type: String
    }
  },
  d: dSchema
})
const Toast = mongoose.model("Toast", toastSchema)

describe('reproduce mongoose issue 5269', function () {
  before(function (done) {
    // connect to mongodb
    mongoose.connect(mongoUrl, function () {
      // empty the collection
      Toast.remove(function (err) {
        if (err) {
          return done(err)
        }
        // insert test document
        let t = new Toast({
            _id: 'newtoast',
            a: 'hi',
            b: 1,
            c: {
              c1: 2,
              c2: 'are'
            },
            d: {
              d1: 'you',
              d2: 'doing'
            }
        })
        t.save(function (err) {
          if (err) {
            return done(err)
          }
          done()
        })
      })
    })
  })

  after(function (done) {
    // disconnect mongodb
    mongoose.disconnect()
    done()
  })

  it('should fail but it succeeds', function (done) {
    Toast.findOneAndUpdate(
        {_id: "newtoast"}, 
        {$set: {d: {d2: "today"}}},
        { runValidators: true }, 
      function(err) {
        if (err) {
          return done(err)
        }
        done()
    })
  })
})
```
