### ISSUE TITLE
Aggregate $hour not local Timezone

### ISSUE THREAD

**Issue by smalike** [Automattic/mongoose#5272]
Look code:
```
db.getCollection('logger').aggregate([
    {
        $project:
        {
            hour: {$hour: '$date'},
            date: '$date'
        }
    }
])
```
Result JSON:
```
{
  _id: ....
  hour: 9,
  date: 2017-04-21 17:15:06.470+08:00
}
```
'hour' not local Timezone

**Comment by vkarpov15** [comment]
[MongoDB's `$hour` operator currently only supports UTC](https://docs.mongodb.com/manual/reference/operator/aggregation/hour/#exp._S_hour). Nothing mongoose can do about that right now. If you need local time you're gonna have to do your aggregation in memory.
