### ISSUE TITLE
Docs re: calling `populate()` multiple times on the same path

### ISSUE THREAD

**Issue by JustWalters** [Automattic/mongoose#5274]
I have two models that look something like
```
ThreadSchema = new Schema({
  name: String
});
    
ThreadSchema.virtual('posts', {
  ref: 'Post',
  localField: '_id',
  foreignField: 'thread'
});
    
PostSchema = new Schema({
  thread: { type: Schema.Types.ObjectId, ref: 'Thread' },
  createdAt: Date
});
```
For any query for a thread or threads, I always want to populate the posts and sort those by their createdAt property, and I was hoping that I could add query middleware to handle this. That way I could search for a specific thread from an api route handler without having to worry about the posts.

I added the following lines to the Query#merge method and I got my desired result.
```
if (source._mongooseOptions) {
  this._mongooseOptions || (this._mongooseOptions = {});
  utils.mergeClone(this._mongooseOptions, source._mongooseOptions);
}
```

In a quick search and with my very limited knowledge of the Mongoose internals, I didn't notice any potential _mongooseOptions keys that would prevent this from being added, and I couldn't find any discussion about this. If I missed something or there's another way to do this, I'd be happy to hear it. If not, I guess this is a feature request.

**Comment by vkarpov15** [comment]
Hmm why do you need to change the internals? Why not just:

```javascript
PostSchema.pre('find', function() {
  this.populate('posts');
});
```

Or something like [mongoose-autopopulate](https://www.npmjs.com/package/mongoose-autopopulate)?

**Comment by JustWalters** [comment]
It looks like mongoose-autopopulate can do what I was looking for. For now, I decided not to use middleware for this, but I realized that while trying to boil this down, I lost track of the reason I first started looking into merging queries in the first place.  Here's a better example.

```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/test');

const ThreadSchema = new Schema({
  name: String
});
    
ThreadSchema.virtual('posts', {
  ref: 'Post',
  localField: '_id',
  foreignField: 'thread'
});

ThreadSchema.pre('findOne', function() {
  this.populate('posts');
});
   
const PostSchema = new Schema({
  thread: { type: Schema.Types.ObjectId, ref: 'Thread' },
  createdAt: Date
});

const Thread = mongoose.model('Thread', ThreadSchema);
const Post = mongoose.model('Post', PostSchema);

new Thread({ name: 'Test' }).save()
  .then(() => { 
    Thread
      .findOne()
      .populate({
        path: 'posts',
        options: { limit: 5 }
      })
      .exec();
  });
```

This shows that mongoose is missing the option and running

```js
Mongoose: threads.insert({ name: 'Test', _id: ObjectId("59252a9386e1327918b9b442"), __v: 0 })
Mongoose: threads.findOne({}, { fields: {} })
Mongoose: posts.find({ thread: { '$in': [ ObjectId("592522232711117549a66866") ] } }, { fields: {} })
```
The hook part is actually irrelevant. It is just multiple calls to populate the same path, with newer calls overwriting the older one. I was a little surprised by that. I'm not sure anymore that I want that behavior changed in the way I proposed, but maybe making it clear in the docs?

**Comment by vkarpov15** [comment]
I don't understand your question, can you please clarify?

**Comment by JustWalters** [comment]
I would expect `Post.findOne().populate({ path: 'user', options: { limit: 5 } }).populate({ path: 'user', options: { sort: 'name' } })` to apply the limit and the sort, but it only does the most recent one (the sort in this case).

Originally, I was requesting that the options be merged, so the limit and sort would both happen. Now, I'm not sure it's necessary, so I'm asking if you think it would make sense to have the documentation mention that populating a query multiple times with the same path may not work as expected.

**Comment by vkarpov15** [comment]
Good suggestion, will add that to the docs

**Comment by jmdmao** [comment]
I found a solution:
https://stackoverflow.com/a/32473842/9509575
