### ISSUE TITLE
My code stoped working

### ISSUE THREAD

**Issue by Fazendaaa** [Automattic/mongoose#5278]
Mongo version: 3.4.3
node version: 7.10.0
Mongoose version: 4.10.0

I have this piece of code, and it was working fine. But when I exclude all database and started a new, it simply does not work anymore. Unfortunately, I don' know whether or not I was using the latest version of Mongoose before I ran 'npm update' -- right after see this awkward error, so I could check out if any patch could correct this.

I have read the doc saying to use .exc(). I tried but the error keeps happening. Actually, I don' know anymore what to do.

```javascript
const userSchema = mongoose.Schema({
    id: Number,
    animes: [Number]
});
const User = mongoose.model('users', this.userSchema);
```
```javascript
return User.findOneAndUpdate({id: user_id}, {id: user_id},  {upsert: true, new: true, setDefaultsOnInsert: true})
    .then(result => {
        /*  Add new anime id to the user    */
        binaryInsert(anime_id, result.animes);
        return result.save().then(data => 'Sucess').catch(err => console.log('[Error]AddEntry save:', error))
}).catch(error => console.log('[Error]AddEntry User:', error))
```

Btw, I expect that this code finds the user if exists, if not create one -- it's what the code was doing.

**Comment by varunjayaraman** [comment]
does it throw an error or does it just not work?

**Comment by Fazendaaa** [comment]
It throws that User is null.
I tried again, same code, with older DB and works fine. Now I don't know anymore I could possibly be wrong.

**Comment by varunjayaraman** [comment]
wait what? it shouldn't throw an error if user is null, nothing will happen. Can you show a stack trace please?

**Comment by varunjayaraman** [comment]
@Fazendaaa any update on this?

**Comment by Fazendaaa** [comment]
Sorry about the delay. I think it was some problem in the folder that I had. It was fixed after deleting it.
