### ISSUE TITLE
doc.validate() promise returns undefined if validation was successful

### ISSUE THREAD

**Issue by hastom** [Automattic/mongoose#5280]
First of all im trying to make some validations before update action.
Some of those validations runs into pre validate hook. 
I found that pre validate is not triggered with flag "runValidators". So I tried to get my object, update fields manualy run doc.validate() and save. That worked for me but im using promises and got another problem.
When I return doc.validate() to chain for next promise I cannot run doc.save() in the chain because doc.validate() does not return doc.
Here is an example
```
Task.findById(req.params.id)
		.then(task => {
			if (!task) {
				res.status(404);
				throw new Error('Task not found');
			}
			if (task.user_id.toString() !== req._user._id.toString()) {
				res.status(403);
				throw new Error('Forbidden');
			}
			for (let field in req.body) {
				if (field in task) {
					task[field] = req.body[field];
				}
			}
			return task.validate();
		})
		.then(function (task) {
			console.log(task); //undefined
                        task.save() // error
		})
		.catch(err => {
			if (err.name === 'ValidationError') {
				res.json(Object.keys(err.errors).map(key => err.errors[key].message));
			} else {
				res.send(err.message);
			}
		})
```
I can chain inside without returning validation result but I feel like its complete wrong from the design point
I'm kind of new to mongoose so maybe that behavior is ok, but then i dont know how to solve my problem

**Comment by varunjayaraman** [comment]
This is by design. `.validate()` will reject with an error if there is a validation error. it will resolve with `undefined` if there are no errors:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5280`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: { type: String, required: true }
    });

    const Model = db.model('Model', schema);

    yield Model.remove({});

    // 1) Invalid document case
    // const doc = new Model();
    // const errors = yield doc.validate();
    // console.log(`Errors ${ errors }`); // this never runs because `.validate()` threw

    // 2) valid document case
    const doc = new Model({ name: 'test' });
    const errors = yield doc.validate();
    console.log(`This ran because there are no errors!`);
    console.log(`And errors is undefined: `, errors === undefined);
  });
}
```

I see that you are trying to access `task` in the next `.then()`. To do that, you'll need to do a roundabout way of validating it (unless you use `co` or a wrapper around promise control-flow like `async/await`):

1) You could wrap `task.validate()` in a function call that resolves if there are no errors and rejects if it doesn't:

```javascript
function validateDoc(doc) {
  return new Promise((resolve, reject) => {
    doc.validate(err => {
      if (err) {
        return reject(err);
      } else {
        return resolve(doc);
      }
    });
  })
}
```

and then you could do `return validateDoc(task)`

2) just do this:

```javascript
return task.validate().then(() => task);
```

the error will bubble up to the catch, and the next `.then()` will grab the `task` if it succeeded (so intentionally do not put a `.catch()` on your `.validate()` call

**Comment by hastom** [comment]
sure, ty
