### ISSUE TITLE
Memory leak in 4.10.1 when saving an array of arrays

### ISSUE THREAD

**Issue by jakeapeters** [Automattic/mongoose#5282]
I'm having some issues with the Mongoose 4.10.1 (tested on Node 7.1, 6.4 and 4.2) when I have an array of arrays in my schema (and the new document I'm trying to save).

The promise returned by `.save()` never resolves, neither do callbacks. Then it causes a huge spike in memory and CPU usage. Enough to crash a few of our production Heroku dynos. 

Here's a minimal failing test case:

```javascript
const mongoose = require('mongoose');
const mainDB = require('../databases/mainDB'); /* connects to one of two databases */
const Schema = mongoose.Schema;

const testAccountSchema = new Schema({
  redirects: [ [ String, String ] ],
});

let TestAccount = mainDB.model('TestAccount', testAccountSchema);

new TestAccount({
  redirects: [
    ['/from', '/to']
  ],
}).save()
  .then(account => console.log(account))
  .catch(err => console.log(err));
```
 Any help would be 💯. I've rolled back to Mongoose 4.8.6 for now, issue not present. Only started this week, so assumedly after the 4.10.1 release.

**Comment by varunjayaraman** [comment]
thanks for the catch. it looks like you using the shorthand for a string array is what is causing it.

See how this works:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5282`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const testAccountSchema = new mongoose.Schema({
      redirects: [{ type: [String] }],
    });

    let TestAccount = db.model('TestAccount', testAccountSchema);

    yield TestAccount.remove({});

    return new TestAccount({
      redirects: [
        ['/from', '/to']
      ],
    })
      .save()
      .then(account => console.log(account));
  });
}
```
I'm not sure if you'd want to do `[[String, String]]` in the first place, seems like you would rather do `[[String]]` and just put a max length of 2 on it with a validator, or go with my way and put a `maxlength: 2`, but i'll mark this as a bug nonetheless

**Comment by jakeapeters** [comment]
Got it! You're a lifesaver. `[{ type: [ String ], maxLength: 2 }]` works perfectly in 4.10.1.

Thanks for looking into this 🙏

**Comment by varunjayaraman** [comment]
no worries. I'm thinking the best behavior here would be to treaty `[[String, String]]` as just `[[String]]`, thoughts @vkarpov15 ?

**Comment by vkarpov15** [comment]
Yeah I'm pretty sure `[[String, String]]` is equivalent to `[[String]]` currently. I would not recommend doing `[[String, String]]` though because that doesn't enforce length 2.
