### ISSUE TITLE
bug on connection with replicat set.

### ISSUE THREAD

**Issue by xileftenurb** [Automattic/mongoose#5284]
node.js version : 6.2
mongoose version : ^4.10.0 (lastest)
mongodb version : 3.2.4

I got a strange bug since I updated mongoose to last version.
it worked without any problem in mongoose ~4.4.0

I have a replicat set of 3 machine (2 nodes and 1 arbiter), hosted on google-cloud-platform with mostly the default config (as created with the mongodb quickdeploy of the platform)
I want to connect to it in my node application with the following (simplified) code : (fictional ip adress)
`var url = "mongodb://username:password@104.0.0.0:27017,104.0.0.1:27017/admin"
mongoose.createConnection(url, options);`

after some time (3-5 second), the application crash with this trace :
```
E:\Developpement Node\serveur-everest\node_modules\mongodb\lib\replset.js:364
          process.nextTick(function() { throw err; })
                                        ^
MongoError: failed to connect to server [developement-server-2:27017] on first connect [MongoError: getaddrinfo ENOTFOUND developement-server-2 developement-server-2:27017]
    at .<anonymous> (E:\Developpement Node\serveur-everest\node_modules\mongodb-core\lib\topologies\server.js:328:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (E:\Developpement Node\serveur-everest\node_modules\mongodb-core\lib\connection\pool.js:274:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (E:\Developpement Node\serveur-everest\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

"development-server-2" is the name of my server as defined in the config on the server.

**Comment by xileftenurb** [comment]
I tried to do a bit of exploration by myself in the code.
it's seem 7 mongodb server object are created. (the class in mongodb-core\lib\topologies\server.js)
first, as I can tell by the stack trace, there is 2 server created direcly by mongoose at line 196 of mongoose\lib\drivers\node-mongdb-native\connection.js.
these 2 are created with the good Ip address and work fine. 

after that, 2 other server object are created by mongo, with the same IP address as the first. this is triggered by the line 215 of mongoose\lib\drivers\node-mongdb-native\connection.js

finally, mongo try to create 3 server object by discovering all mongod connected in the replicat set (so 2 mongo and 1 arbiter).
on google-cloud-platform, the server are able to find each other only with the name of each google compute engine. but outside of the network of the google project, the name mean nothings, and mongo fail to connect and throw an (unhandled) error.

this is what is happening as far as I can tell. I am not expert in mongo nor in mongoose code, but I hope this can help resolve the bug.

**Comment by vkarpov15** [comment]
That error means mongoose can't connect to your servers. Can you please double check whether you can connect using the mongodb shell?

**Comment by xileftenurb** [comment]
I can. These server are live and the same application can connect to them with mongoose 4.4 without any error.

the error come up when I try to update mongoose to the last version (4.10)
