### ISSUE TITLE
Populate in nested schema/Sub docs

### ISSUE THREAD

**Issue by Linux249** [Automattic/mongoose#5286]
I'm looking for a way to define default population behavior for references (Object id's) in nested schema. 

I know how to define default populate for a schema with the find/findOne middleware. There we can use "[Populating across multiple levels](http://mongoosejs.com/docs/populate.html)" to populate the references in the child-schema - this small example should explain what I mean: 
(The child schema is for saving metadata, like who has set the value of an attribute)
`const metaSchema = Schema({  user: { type: Schema.Types.ObjectId, ref: 'user' })`

We want to use this Schema for every attribute in every other Schema.
```
const fooSchema = Schema({ bar: { value: String, meta: metaSchema} })
const autoPopulateFoo = next => {
    this.populate({path: 'bar.meta', populate: {path: 'user'}
}
fooSchema .pre('find', autoPopulateFoo)
```

My problem is, that we use the metaSchema in nearly every schema for every attribute. Since the "how" to populate metaSchema is always the same, I'm looking for a shorter way than defining it the described way like for every attribute. The doc's says that child schema have only save/validate as middleware (http://mongoosejs.com/docs/subdocs.html)

**Comment by varunjayaraman** [comment]
could you use discriminators to inherit from a base schema that has the hook you're looking for? Or does that not solve your use case.

**Comment by Linux249** [comment]
The discriminatores doesn't look helpful.

I just try out the [mongoose-autopopulate](https://github.com/mongodb-js/mongoose-autopopulate) plugin: 
`const metaSchema = Schema({ user: { type: Schema.Types.ObjectId, ref: 'user', autopopulate: true })`

This also does not work - It looks like this plugin also using the find/findOne pre-hooks which are not available in a nested schema. 

Again: I Know how to populate the nested schema from the parant schema. Because of using the nested schema a thousend times (with different pathes and always the same populate behavior) I'm looking for a shorter way.

**Comment by varunjayaraman** [comment]
@Linux249 do you mind explaining why discriminators do not solve your use case?

**Comment by varunjayaraman** [comment]
@Linux249 without further clarification, I'll need to close this as stale soon
