### ISSUE TITLE
Recursive model definition

### ISSUE THREAD

**Issue by ruiixu23** [Automattic/mongoose#5289]
Let's say I want define a model to store mathematical equations using a binary tree. Using the following model:

```javascript
let schema = new mongoose.Schema({
  operator: {
    enum: ['plus', 'minus', 'multiply', 'divide'],
    type: String
  },
  value: number
});

schema.add({
  left: schema,
  right: schema
});

let model = mongoose.model('Node', schema);
```

Now if I have a document `doc` whose JSON representation is:

```json
{
  "_id": ObjectId("5926e40540129112aada9ac3"),
  "operator": "multiply",
  "left": {
    "operator": "plus",
    "left": {
      "value": 1,
    },
    "right": {
      "value": 2
    }
  },
  "right": {
    "operator": "minus",
    "left": {
      "value": 5,
    },
    "right": {
      "value": 6
    }
  }
}
```

Then accessing `doc.left.right` gives `undefined`. I found a solution by modifying the model definition to:

```javascript
let schema = new mongoose.Schema({
  operator: {
    enum: ['plus', 'minus', 'multiply', 'divide'],
    type: String
  },
  value: number
});

schema.add({
  left: schema,
  right: schema
});

/* Add left again*/
schema.add({
  left: schema,
});

let model = mongoose.model('Node', schema);
```
I wonder if there is more elegant way of solving this recursive model definition problem?

The code was executed using Node.js v6.10.3, MongoDB v3.4.4, and Mongoose v4.10.0

**Comment by varunjayaraman** [comment]
probably not, that's a javascript limitation. You can't use the object name unless you're inside a function because then the object reference has been established.

For example

```javascript
const obj = {
  x: obj.y,
  y: 4
}
```

This won't work, but this will:

```javascript
const obj = {
  x: function() { return obj.y },
  y: 4
}
```

**Comment by varunjayaraman** [comment]
Also, I thought of this solution. It's a bit more verbose and not exactly more elegant, but it eliminates the second `schema.add` call that might be confusing to someone looking at your code and trying to wrapt heir head around it:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5285`


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    let schema = new mongoose.Schema({
      operator: {
        enum: ['plus', 'minus', 'multiply', 'divide'],
        type: String
      },
      value: Number
    });

    schema.add({
      left: mutateSchema(schema, 'right'),
      right: schema
    });

    function mutateSchema(_schema, leftRight) {
      const newSchema = _schema.clone()
      newSchema.add({ [leftRight]: _schema });
      return newSchema;
    }

    let model = mongoose.model('Node', schema);

    const doc = new model({
      operator: 'multiply',
      left: { operator: 'plus', left: { value: 1 }, right: { value: 2 } },
      right: { operator: 'plus', left: { value: 5 }, right: { value: 6 } }
    });

    console.log(doc.left.right);

    console.log(doc.right.left);
  });
}
```

**Comment by jjongsma** [comment]
Instead of referencing the schema itself in left/right, just create the recursive schema object structure before constructing it.

let structure = {
      operator: {
        enum: ['plus', 'minus', 'multiply', 'divide'],
        type: String
      },
      value: Number
};

structure.left = structure;
structure.right = structure;

let schema = mongoose.Schema(structure);

**Comment by varunjayaraman** [comment]
@ruiixu23 can i close this out, do those solutions work?

**Comment by ruiixu23** [comment]
Yes. It it working with the workaround. Thanks a lot for the help and discussion

On 8 Jul 2017, at 21:45, Varun Jayaraman <notifications@github.com<mailto:notifications@github.com>> wrote:


@ruiixu23<https://github.com/ruiixu23> can i close this out, do those solutions work?

**Comment by vkarpov15** [comment]
Yeah the only way to handle recursive definition is `schema.add()`. This isn't really a mongoose problem, JavaScript enforces that `schema` is undefined when it is passed to the `Schema` constructor below

```javascript
let schema = new mongoose.Schema({
  operator: {
    enum: ['plus', 'minus', 'multiply', 'divide'],
    type: String
  },
  value: number,
  left: schema
});
```
