### ISSUE TITLE
Upgrade 4.9.10 to 4.10.0 - Warning: Possible EventEmitter memory leak

### ISSUE THREAD

**Issue by AndrewBarba** [Automattic/mongoose#5290]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When starting Mongoose on versions 4.10.0, 4.10.1, and 4.10.2 these logs appear:

```
(node:42202) Warning: Possible EventEmitter memory leak detected. 11 init listeners added. Use emitter.setMaxListeners() to increase limit
(node:42202) Warning: Possible EventEmitter memory leak detected. 11 save listeners added. Use emitter.setMaxListeners() to increase limit
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Sorry, I don't know... Happens in one of our projects (over 40 models) and doesn't happen in another (8 or so models). Hoping you might have a better idea of the changes from 4.9.10 to 4.10.0. Looking for save listeners I see:

```
./node_modules/mongoose/lib/schema/embedded.js:      parent.on('save', function() {
./node_modules/mongoose/lib/types/documentarray.js:    doc.on('save', arr._handlers.save);
./node_modules/mongoose/lib/types/embedded.js:  _this.on('save', function() {
./node_modules/mongoose/lib/types/embedded.js:  owner.on('save', emitRemove);
./node_modules/mongoose/lib/types/subdocument.js:  owner.on('save', emitRemove);
```

Sorry this isn't more helpful...

**What is the expected behavior?**
I expect no EventEmitter warnings to appear. They did not appear on 4.9.10

**Please mention your node.js, mongoose and MongoDB version.**
Node 6.10.3, Mongoose 4.10.x, MongoDB  3.4.4

**Comment by varunjayaraman** [comment]
hmm, are you setting a bunch of listeners somewhere else? Or is it just from mongoose?

**Comment by AndrewBarba** [comment]
It's only from Mongoose. I do not have any listeners for `on('save')` or `on('init')` but Mongoose does. Thats what I posted above. Again, Doesn't happen in 4.9.10, happens in 4.10.0

**Comment by vkarpov15** [comment]
Yeah this will be very hard for us to figure out how to repro. Can you investigate and create a code sample for us @AndrewBarba ?

**Comment by lchenay** [comment]
Same for me.
This warning is shown on my code only when using ```query.cursor().asyncEach(fn, {parallel: concurrency})``` with concurrency > 2.
This bug seems to depend on previous query because changing order of query call or changing parameters of previous query cause this error or not.

More over once this warning as been displayed next query will result in exception:
```javascript
TypeError: Cannot read property 'socketTimeout' of null
         at Connection.messageHandler (node_modules/mongodb-core/lib/connection/pool.js:410:16)
         at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:351:20)
         at emitOne (events.js:96:13)
         at Socket.emit (events.js:188:7)
         at readableAddChunk (_stream_readable.js:176:18)
         at Socket.Readable.push (_stream_readable.js:134:10)
         at TCP.onread (net.js:548:20)
```

Unable to write a simplified code to reproduce.

**Comment by vkarpov15** [comment]
@lchenay can you please provide some code samples even if you can't provide a simplified repro? I don't understand what you mean by "changing order of query call or changing parameters of previous query"
