### ISSUE TITLE
key $unset must not start with '$'

### ISSUE THREAD

**Issue by sradu** [Automattic/mongoose#5294]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

I'm afraid I can't provide a script to reproduce it, but I have the debug logs:

Mongoose: obj.update({ _id: ObjectId("59277caacb208dbcca7c77dc"), __v: 0 }, { '$unset': { one: 1, two: 1, three: 1, four: 1 }, '$set': { currency_formats: null, urls: [ 'http://www.google.com' ], updated_at: new Date("Fri, 26 May 2017 00:54:08 GMT") }, '$inc': { __v: 1 } }, { j: 1, w: 'majority', wtimeout: 10000, checkKeys: true, serializeFunctions: undefined, promiseLibrary: { [Function: wrappedPromise] accept: undefined, all: { [Function: __NR_wrappedCast] __NR_original: [Function: all], __NR_unwrap: [Function: __NR_unwrap] }, defer: undefined, race: { [Function: __NR_wrappedCast] __NR_original: [Function: race], __NR_unwrap: [Function: __NR_unwrap] }, reject: { [Function: __NR_wrappedCast] __NR_original: [Function: reject], __NR_unwrap: [Function: __NR_unwrap] }, resolve: { [Function: __NR_wrappedCast] __NR_original: [Function: resolve], __NR_unwrap: [Function: __NR_unwrap] }, super_: [Function: Promise], __NR_original: [Function: Promise], __NR_unwrap: [Function: __NR_unwrap] } })

And the message is:
Error: key $unset must not start with '$'

**What is the expected behavior?**

To save the object.

**Please mention your node.js, mongoose and MongoDB version.**
node v7.9.0
├─┬ mongoose@4.10.2
│ ├─┬ mongodb@2.2.26
│ │ ├─┬ mongodb-core@2.1.10

**Comment by varunjayaraman** [comment]
do you have the code that produces this log, like how you are doing the update?

**Comment by sradu** [comment]
I'm afraid I haven't been able to create a small sample test. That being said, it works on 4.9.5 and fails on 4.9.6. Unsure what change there could have affected it.

**Comment by dhritzkiv** [comment]
I am getting similar errors with update throwing an error complaining about $set. Here is my simplest test code:

```js
const schema = new Schema({
	email: {
		type: String,
		required: true,
		trim: true,
		lowercase: true,
		select: false//select this
	}
}, {
	safe: {
		w: "majority",
		wtimeout: 1e4
	}
});

const model = mongoose.model("Users", schema);

//...
//Note: the following is in a async function

//create user instance
let user = new mongoose.models.Users({
	email: "foo@bar.com"
});

//initial save to DB
try {
	user = await user.save();
} catch (e) {
	//no errors thrown
}

//make a change
user.email = "bar@foo.com";

//subsequent update via `save`
try {
	user = await user.save();
} catch (e) {
	//error is thrown:
	console.error(e);
}
```

The results of the errors (module paths redacted):

```error
Error: key $set must not start with '$'
    at serializeInto ([REDACTED]/node_modules/bson/lib/bson/parser/serializer.js:752:19)
    at serializeObject ([REDACTED]/node_modules/bson/lib/bson/parser/serializer.js:308:18)
```

When I inspect the value of `object` in the serializer file at L752, it's equal to: `{ '$set': { email: 'bar@foo.com'} }`, which seems right for an update query (which `#save` uses internally).

---

Strangely, if instead of calling `save` a second time,  I call `update` with the same values, nothing happens:

```js
//subsequent update via `update`
try {
	user = await user.update({$set: {email: "bar@foo.com"}});
} catch (e) {
	//no error is thrown:
}
//works okay!
```

**Comment by varunjayaraman** [comment]
it looks like its the `safe` option passed to your schema options that is causing it. Worth investigating:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5294`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const schema = new mongoose.Schema({
      email: {
        type: String,
        required: true,
        trim: true,
        lowercase: true,
        select: false //select this 
      }
    }, {
      safe: {
        w: "majority",
        wtimeout: 1e4
      }
      // if this is just `true`, it doesnt error
    });


    const User = db.model('User', schema);

    yield User.remove({});

    let user = new User({
      email: "foo@bar.com"
    });

    //initial save to DB
    try {
      user = yield user.save();
    } catch (e) {
      //no errors thrown
      console.log('error 1', e);
    }

    //make a change
    user.email = "bar@foo.com";

    //subsequent update via `save`
    try {
      user = yield user.save();
    } catch (e) {
      //error is thrown:
      console.error('error 2', e);
    }
  });
}

```

**Comment by dhritzkiv** [comment]
Can confirm. Ran the code. Throws an error with the `safe` option; succeeds otherwise.

**Comment by sradu** [comment]
Removing the custom safe option fixed the issue on my end as well.
