### ISSUE TITLE
Is Mongo DB Collation at Collection Level Supported

### ISSUE THREAD

**Issue by thaoula** [Automattic/mongoose#5295]
Hi Guys,

Just wondering if it possible to set the Collation?
https://docs.mongodb.com/manual/reference/command/create/#dbcmd.create

Cant seem to set this option. I would like to use this approach to avoid setting collation at every index, sort and query request.

Also, anyone know when the Typescript files will be updated to allow usage of the Collation helper methods.

Many thanks in advance

Regards,
Tarek

**Comment by vkarpov15** [comment]
Unfortunately not, mongoose currently does not have support for creating collections manually. I would recommend you use the mongodb shell directly to do that.

Also, mongoose does not have officially supported typescript bindings, so please report that issue to whichever TS bindings you use.
