### ISSUE TITLE
How should a plugin detect the correct Promise implementation to use?

### ISSUE THREAD

**Issue by binki** [Automattic/mongoose#5305]
**Do you want to request a *feature* or report a *bug*?**

I think there is a bug with the documentation. It does not describe how a [plugin](http://mongoosejs.com/docs/plugins) should determine the right [`Promise`](http://mongoosejs.com/docs/promises) implementation to use to respect the user’s preference (i.e., the user may set the default via `mongoose.Promise = myPromiseImplementation`).

**What is the current behavior?**

The only way I could figure out to lookup the right `Promise` implementation to use is, from a context where `this` is a Mongoose-related object with a `base` property (such as a [`Model`](http://mongoosejs.com/docs/api.html#model_Model-base)), to access `this.base.Promise.ES6`. This took me a while to figure out because [the docs have you assign a `Promise` constructor to `Mongoose#Promise`](http://mongoosejs.com/docs/promises) but when reading that property you get something that is not a `Promise` constructor. I now see that the [`ES6` is described in the docs](http://mongoosejs.com/docs/api.html#promise_Promise.ES6), but I don’t see the `Mongoose#Promise` property described in the API so I had to source dive to figure out how that property worked.

At the same time, it felt like maybe I was accessing something which I shouldn’t be because the `Mongoose#Promise` property is not documented. I’m worried that when I wrote code contributing to a plugin, https://github.com/drudge/mongoose-findorcreate/commit/80a3a708a12517f70ad587f0717c81f030edf62b#diff-168726dbe96b3ce427e7fedce31bb0bc , I might be accessing an API that could change without warning.

**What is the expected behavior?**

I would like a documented way/official example for plugins to access the ES6 constructor. Or a recommendation on a better way to add statics to a model that supports both the callback and Promise asynchronous patterns.

**Please mention your node.js, mongoose and MongoDB version.**

* node-6.9.5
* mongoose-4.10.3
* npm module mongodb-2.2.27
* MongoDB-3.4.4

**Comment by vkarpov15** [comment]
That's a fair suggestion. `self.base.Promise.ES6` is the way to go right now, but we were planning on removing the `.ES6` bit for the next major release, because it's a hack for legacy promise libraries. Perhaps `self.base.getPromise()`?

**Comment by binki** [comment]
Sure. Anything that gets documented and guaranteed to stick around in the API for a while would be helpful :-).

**Comment by vkarpov15** [comment]
Added `getPromiseConstructor` to 4.10.6, will ship it tomorrow :+1:
