### ISSUE TITLE
{_id: false} Doesn't apply when inserting a document with update and {upsert: true}

### ISSUE THREAD

**Issue by biskazz** [Automattic/mongoose#5308]
Latest current versions of NodeJS, MongoDB and Mongoose
I have the following model:

```
const mongoose = require('mongoose')
const shortid = require('shortid')
const FollowSchema = mongoose.Schema({
  _id: {
    type: String,
    default: shortid.generate
  },
  followerId: {
    type: String,
    required: true,
    index: true
  },
  followeeId: {
    type: String,
    required: true,
    index: true
  }
}, { timestamps: true, _id: false })
module.exports = mongoose.model('Follow', FollowSchema)
```

Which model is consumed the following way:

```
Follow.findOneAndUpdate(
 { followerId, followeeId },
 { followerId, followeeId },
 { upsert: true, setDefaultsOnInsert: true })
```

The point of this insertion is to not have dublicates in the collection.
The actual bug is that _id fails to set with `shortid.generate`, which is the _default_.
This leads me to think this is an issue with ` setDefaultsOnInsert: true `.

**Comment by vkarpov15** [comment]
I'm not sure I understand, can you please clarify this sentence: "The actual bug is that _id fails to set with shortid.generate, which is the default."?

**Comment by varunjayaraman** [comment]
@biskazz do you have any further information on this? I'll need to close this as stale soon

**Comment by biskazz** [comment]
Go ahead and close it. Can't remember what I did to workaround it but i'm pretty sure i used .update or .updateOne.

**Comment by divinzer** [comment]
same issue
because 'upsert' make id property to only ObjectId not String

so shortid didn't work
