### ISSUE TITLE
execPopulate() with top-level populate virtuals

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5311]
https://github.com/Automattic/mongoose/issues/5240#issuecomment-303420745

**Comment by rockmacaca** [comment]
Unfortunately this broke document#populate() for me. 4.10.4 works, 4.10.5 breaks it. I haven't tested if nested virtuals are affected, I currently only have top level ones defined at the moment.

(also pardon me for posting this comment in the wrong issue earlier, I had two tabs open with very similar looking issue numbers)

**Comment by randallmeeker** [comment]
@rockmacaca same was for me but 4.10.6 fixed again.

**Comment by vkarpov15** [comment]
@rockmacaca can you try upgrading to 4.10.6 and see if it fixed your issue? If not, please open up a separate issue with repro instructions

**Comment by rockmacaca** [comment]
Yep, still not working. I'll see about making an isolated case soon when I have a chance.
