### ISSUE TITLE
typeKey not handled in array of reference Id

### ISSUE THREAD

**Issue by jbdemonte** [Automattic/mongoose#5313]
Node v6.10.0 - Mongo 3.4.2 - Mongoose 4.8+ / 4.10.4

Changing typeKey in array of { type: Schema.Types.ObjectId, ref: 'Book' } results in a single array of Ids instead of dealing with the objects)

    var mongoose = require('mongoose')
      , Schema = mongoose.Schema

    var personSchema = Schema(
      {
        name    : {$type: String},
        favorite: { $type: Schema.Types.ObjectId, ref: 'Book' }, // works
        books : [{ $type: Schema.Types.ObjectId, ref: 'Book' }] // doesn't work => ids instead of objects
      },
      {
        typeKey: '$type'
      }
    );

    var bookSchema = Schema({
      title    : String
    });

    var Book  = mongoose.model('Book', bookSchema);
    var Person = mongoose.model('Person', personSchema);

    var book1 = new Book({title: 'The Jungle Book'});
    var book2 = new Book({title: '1984'});

    var person = new Person({name: 'Bob', favorite: book1, books: [book1, book2]})

    console.log(person); 

This codes logs:

    { name: 'Bob',
      favorite: { title: 'The Jungle Book', _id: 592e4c38f9c3bc48349608d0 },  
    _id: 592e4c38f9c3bc48349608d2,
      books: [ 592e4c38f9c3bc48349608d0, 592e4c38f9c3bc48349608d1 ] }

While the same code without a custom typeKey logs:

    { name: 'Bob',
      favorite: { title: 'The Jungle Book', _id: 592e4bae83ec144817516ab4 },
      _id: 592e4bae83ec144817516ab6,
      books:
      [ { title: 'The Jungle Book', _id: 592e4bae83ec144817516ab4 },
        { title: '1984', _id: 592e4bae83ec144817516ab5 } ] }

When using typeKey, the books data are lost and replaced by the _id

**Comment by varunjayaraman** [comment]
yup, this looks like a bug:

```javascript
var mongoose = require('mongoose')
  , Schema = mongoose.Schema

// WITH custom type key
var personSchema = Schema(
  {
    name    : {$type: String},
    favorite: { $type: Schema.Types.ObjectId, ref: 'Book' }, // works
    books : [{ $type: Schema.Types.ObjectId, ref: 'Book' }] // doesn't work => ids instead of objects
  },
  {
    typeKey: '$type'
  }
);

// WITHOUT custom type key
// var personSchema = Schema(
//   {
//     name    : {type: String},
//     favorite: { type: Schema.Types.ObjectId, ref: 'Book' }, // works
//     books : [{ type: Schema.Types.ObjectId, ref: 'Book' }] // doesn't work => ids instead of objects
//   }
// );

var bookSchema = Schema({
  title    : String
});

var Book  = mongoose.model('Book', bookSchema);
var Person = mongoose.model('Person', personSchema);

var book1 = new Book({title: 'The Jungle Book'});
var book2 = new Book({title: '1984'});

var person = new Person({name: 'Bob', favorite: book1, books: [book1, book2]})

console.log(person); 
````
