### ISSUE TITLE
Nested pre hooks losing context

### ISSUE THREAD

**Issue by despreston** [Automattic/mongoose#5315]
Not sure if this is a bug or there is a way (not apparent in the docs) on how to do this.

If I have 3 models: Project, Note, and Comment.

A Project has a list of Notes, and a Note has a list of Comments.

When I delete a Project, I have a pre 'remove' hook to remove all related Notes. When I delete a Note, I have a pre 'remove' hook to remove all Comments for that Note. So deleting a Project results in a cascade of pre 'remove' hooks.

The problem is, inside the pre 'remove' hook for Notes, it seems the method is losing its context. So my query: `Comment.find` throws an error that `find` is undefined. When I console.log Comment in that pre remove hook, its a blank object. 

Any ideas? There must be a way to do this sort of cascade of pre 'remove' hooks.

**Comment by vkarpov15** [comment]
Please provide code samples, prose !== code

**Comment by despreston** [comment]
So I was able to circumvent this issue by writing `mongoose.models[<model name .]' in order to make queries.

```
return mongoose.models['notification']
  .find({ 'related.item': this._id })
  .then(notifications => Promise.all(notifications.map(n => n.remove())))
  .then(() => {
    // remove all reactions for the note
    return mongoose.models['reaction']
    .find({ 'note': this._id })
    .then(reactions => Promise.all(reactions.map(reaction => reaction.remove())))
  })
  .then(() => {
    // remove all comments for the note
    return mongoose.models['comment']
    .find({ 'note': this._id })
    .then(comments => Promise.all(comments.map(comment => comment.remove())));
  })
  .then(() => next());
```

I've got 4 other schemas that have similar pre 'remove' hooks such as the one above. A common pattern among them is to remove all 'notifications' related to the item being removed. It's a typical cascading pattern of removals. 

If I write the above code like this: `Notification.find`, `Comment.find`, etc, it fails in the second level of the "tree" of pre 'remove' hooks. If I look at `Comment` where it fails (`console.log(Comment)`) it appears to be an empty object with no prototype methods.

**Comment by varunjayaraman** [comment]
can you please post the error/bug-producing version of your code?

**Comment by olivierto** [comment]
Got the same issue here.
Here is my code : 
`var mongoose = require('mongoose'),
    Schema = mongoose.Schema;;
var Campaign = require('../campaign/campaign.model'),
    logger = require('../../utils/logger');;

var ReportSchema = new Schema({
    user: {
        type: Schema.Types.ObjectId,
        ref: 'user',
        required: true
    },
    creationDate: {
        type: Date,
        default: Date.now
    },
    campaign: {
        type: Schema.Types.ObjectId,
        ref: 'Campaign',
        required: true
    },

    details: {
        type: Schema.Types.Mixed,
        required: true
    }
}, { discriminatorKey: 'type' });

ReportSchema.post('remove', function(doc) {
    //remove reports attached to sut
    logger.debug('Will delete campaign linked to report : %s', doc);
   Campaign.find({ _id: doc.campaign }).remove(
        (err) => {
            if (!err) {
                logger.debug('Campaign linked were successfuly deleted');
            } else {
                logger.error('can\t delete campaign relative to reprort %s', err);
            }

        })
});
module.exports = mongoose.model('Report', ReportSchema);`

Which leads to this error : 'Campaign.find is not a function'.

When debugging, Campaign is an instance of Object and not a schema. So post hooks are loosing Model schema context.

**Comment by varunjayaraman** [comment]
what does `campaign.model` export?

**Comment by varunjayaraman** [comment]
@olivierto can you please update this issue with an answer to my question? Otherwise i'll need to close this as stale soon

**Comment by olivierto** [comment]
> what does campaign.model export?

Sorry for late reply but can you be more specific? 
Here is my exports of the Campaign schema
`module.exports = mongoose.model('Campaign', CampaignSchema);`

**Comment by vkarpov15** [comment]
You're not using `this` in your hook function, so you're not losing function context. Either way, I suspect you have a circular dependency using `require()`, if you have file A that requires file B and then file B requires file A, file B will get an empty object as the return value from `require('fileA')`. I'd use `mongoose.model('Campaign')` instead of `require()`-ing the model as OP suggested.
