### ISSUE TITLE
Batch Queries

### ISSUE THREAD

**Issue by ed-zm** [Automattic/mongoose#5319]
hello guys, I have doubt.
Is there any way to make batch queries? 
I know I can use `$in` operator, but what if I need to batch an array of arrays? for example:

normal way using `$in` operator: 

`UserModel.find( {"_id": { "$in": [ 1, 2, 3 ] } } )`

but how can I batch something like this:

`UserModel.find( {"_id": { "$in": [ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 1, 3, 5 ] ] } } )`

I see bulk operation is just available for writes and not for queries. 

Thanks in advance

**Comment by vkarpov15** [comment]
Can you please clarify what you're trying to do? `UserModel.find( {"_id": { "$in": [ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 1, 3, 5 ] ] } } )` do you have documents whose `_id` properties are arrays?
