### ISSUE TITLE
Option to disable sslv2/sslv3

### ISSUE THREAD

**Issue by erappaport** [Automattic/mongoose#5320]
I have a large client that requires SSLv2 to be disabled. Would you please add this option to the next Mongoose release.

**Comment by vkarpov15** [comment]
Can you please clarify? I don't understand your issue.

**Comment by erappaport** [comment]
SSLv2 is not secure. It must be disabled.

SSLv3 is not secure. It must be disabled.

Mongoose must not allow incoming SSLv2 or SSLv3 connections.

**Comment by vkarpov15** [comment]
Mongoose doesn't handle any inbound SSL connections, that's up to your web server. If you want to set up SSL for mongodb, that's outside the scope of mongoose, but you can check out [mongodb's docs on setting up SSL](https://docs.mongodb.com/manual/tutorial/configure-ssl/)
