### ISSUE TITLE
population on nested type with default value

### ISSUE THREAD

**Issue by albert-92** [Automattic/mongoose#5322]
I have a problem with mongoose v4.10.4.

I have a Page defined like so:

```
Page = {
  title: String,
  creator: { type: Schema.Types.ObjectId, ref: 'User', required: true }
}
```
Now i want to populate the creator with .populate('page.creator')

If define page like this

```
page: Page // .populate('page.creator') does work
```

it works just fine, but if i define it like this to set a default value

```
page: { type: Page, required: true, default: {} } // .populate('page.creator') does not work
```

it does not work and returns `page.creator = null`.

What am i doing wrong here?

**Comment by vkarpov15** [comment]
Unfortunately that's not how mongoose schemas work. `page: { type: Page, required: true, default: {} }` is really the same as:

```javascript
page: {
  type: {
    title: String,
    creator: { type: Schema.Types.ObjectId, ref: 'User', required: true }
  },
  required: true,
  default: {}
}
```

Which mongoose interprets as `page: { type: {}, required: true, default: {} }`, in other words, `page` is a mixed type and `page.creator` does not have a `ref`. If you want to do that, do something like this:

```javascript
var pageSchema = new Schema({
  title: String,
  creator: { type: Schema.Types.ObjectId, ref: 'User', required: true }
});

var schema = new Schema({
  page: { type: pageSchema, required: true, default: {} }
});
```
