### ISSUE TITLE
Model.aggregate().sample() is not sampling from the entire collection

### ISSUE THREAD

**Issue by SamDelgado** [Automattic/mongoose#5326]
I am attempting to pull 2 random documents from a collection by using `Model.aggregate().sample(2)`. This works fine but over time new documents added to the collection are never randomly chosen. Even with a very small dataset of only 20 documents, there will be documents that are never randomly selected even after thousands of samplings.

I am not sure if this is even a Mongoose issue, but I have also tried running `reIndex({})` on the collection to no avail. I can query the collection like normal, it is only the random sampling that is not working properly. Any ideas?

MongoDB version: 3.4.2
Mongoose version: 4.10.4
NodeJS version: v7.10.0

**Comment by vkarpov15** [comment]
Can you provide a code sample that reproduces your issue? I really doubt this is a mongoose issue, mongoose doesn't do anything beyond delegating to the `$sample` stage in this case: https://docs.mongodb.com/manual/reference/operator/aggregation/sample/ .

**Comment by varunjayaraman** [comment]
@SamDelgado do you have a repro script? I'm going to mark this as stale and will close soon without something more actionable
