### ISSUE TITLE
ensureIndexes does not create indexes when schema.options.autoIndex === false

### ISSUE THREAD

**Issue by whyhankee** [Automattic/mongoose#5328]
To test, disable autoIndex for your model:

```
var yourSchema = new mongoose.Schema({
  email: {type: String, required: true, unique: true},
  // etc
}, {
  id: false,
  autoIndex: false
});
```

Then call ensureIndexes() on your model and check mongo for your collection and see that indexes are *not* created.

I have traced this to the function _ensureIndexes() where a couple of lines where preventing the operation to continue:

```
if (model.schema.options.autoIndex === false ||
   (model.schema.options.autoIndex == null && model.db.config.autoIndex === false)) {
      return done();
}
```
These same check is done in init() where it belongs so it seemed safe to remove them here. This seems to have fixed my problems.

I have created a fix in #5324
note: that there was already an test-error in master when I started this fix.

It might be related to #5317, waiting for a response from the OP.

MongoDB version: 3.4.4
Mongoose version: 4.10.4
NodeJS version: v6.10.3

(edit: added used software versions)

**Comment by Bexanderthebex** [comment]
In v5.2.6, the problem still exists. When I set the options autoIndex to false and wants to create indexes on other schemas, it wont create any other index on those schemas
