### ISSUE TITLE
Using Mongoose Cursors with NewRelic: memory leaking very quickly

### ISSUE THREAD

**Issue by loris** [Automattic/mongoose#5329]
I'm pretty sure this has something to do with the NewRelic agent and not mongoose, but I'm posting this here too in case some has this issue too or it could be helpful to mongoose/newrelic users:

Our setup is running:

- Node v7.10.0
- Mongoose v4.10.4
- NewRelic Agent v1.39.1

The problem is:

- One of our Express app route do open a Mongoose cursor (http://mongoosejs.com/docs/api.html#querycursor_QueryCursor) to fetch documents (might be ~100k), pipe them into a CSV stream then pipe them into Express response.
- This is working super fine with `NEW_RELIC_ENABLED=false`, memory goes from 100mo to 130mo, and stays that way during the streaming of the CSV (which can take up to a minute).
- When NewRelic is enabled, the memory goes from 100mo to 500mo (our provider's, Heroku, limit) in less than 10 seconds (during the CSV is being streamed) and the app then crash.
- We tried disabling instrumentation for that route (`NEW_RELIC_IGNORING_RULES='.*format=csv.*'`) but it keeps leaking the same
- According to your documentation, there is a known issue with MongoDB cursors (https://docs.newrelic.com/docs/agents/nodejs-agent/troubleshooting/troubleshooting-large-memory-usage-nodejs#mongo), but i'm not so sure it is related since Mongoose handles the cursor closing properly (https://github.com/Automattic/mongoose/blob/4.10.4/lib/querycursor.js), and the memory leak happen as soon as the cursor is being streamed anyway.
- Our only solution right now is to disable NewRelic completely
- Is there a way to fix this issue? or at least to make NewRelic ignore that transaction / Mongoose cursor methods?

source: https://discuss.newrelic.com/t/using-mongoose-cursors-memory-leaking-very-quickly/49270

**Comment by varunjayaraman** [comment]
I haven't used NewRelic much but I remember reading that it monkey patches the mongodb driver so that might have something to do with it.

@vkarpov15 have you seen this issue before?

**Comment by loris** [comment]
I opened a private ticket on the NewRelic side and will let you know. I striped down my code to the bare minimum that would cause the issue, the following code ran on my machine will leak from 60MB to 600MB in a few seconds (the User collection need to have a decent amount of documents, otherwise the stream will end too fast to cause any leak):

```js
require('newrelic');
const express = require('express');
const mongoose = require('mongoose');

const app = express();
mongoose.connect(process.env.MONGODB_URI);

const User = mongoose.model('User', new mongoose.Schema({}));

app.get('/test', (req, res) => {
  User
    .find()
    .select('_id')
    .lean()
    .cursor()
    .map(doc => JSON.stringify(doc))
    .pipe(res);
});

app.listen(process.env.PORT);
```

**Comment by loris** [comment]
I'm closing this issue and will let you know if NR is able to find out the culprit. Anyway this has nothing to do with Mongoose. NR still leaks the same using `mongodb/node-mongodb-native`:

```
require('newrelic');
const express = require('express');
const MongoClient = require('mongodb').MongoClient;

const app = express();

app.get('/test', (req, res) => {
  MongoClient.connect(process.env.MONGODB_URI, function(err, db) {

    db.collection('users')
      .find()
      .project({ _id: 1 })
      .map(doc => JSON.stringify(doc))
      .pipe(res);
  });
});

app.listen(process.env.PORT);
```

**Comment by vkarpov15** [comment]
I would advise against using NR if you're concerned about performance. Because NR monkey-patches the mongodb driver internals, you're not really running mongoose or mongodb in production, but some quirky amalgam of mongoose, mongodb, and NR that isn't tested at all by the mongoose devs.
