### ISSUE TITLE
Can't connect to the mongodb database in digital ocean server.

### ISSUE THREAD

**Issue by apoorvtomar2222** [Automattic/mongoose#5330]
Unable to connect to the mongodb database in Digital ocean server.

> 0|app      | Error: Error connecting to db: connection 0 to 139.59.21.76:17218 timed out
> 0|app      |     at /home/so-delhi-api-gateway/sodelhi/node_modules/connect-mongodb-session/index.js:45:17
> 0|app      |     at /home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/lib/mongo_client.js:276:20
> 0|app      |     at /home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/lib/db.js:224:14
> 0|app      |     at null.<anonymous> (/home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/lib/server.js:234:9)
> 0|app      |     at g (events.js:260:16)
> 0|app      |     at emitTwo (events.js:87:13)
> 0|app      |     at emit (events.js:172:7)
> 0|app      |     at null.<anonymous> (/home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:310:10)
> 0|app      |     at g (events.js:260:16)
> 0|app      |     at emitTwo (events.js:87:13)
> 0|app      |     at emit (events.js:172:7)
> 0|app      |     at null.<anonymous> (/home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:93:12)
> 0|app      |     at g (events.js:260:16)
> 0|app      |     at emitTwo (events.js:87:13)
> 0|app      |     at emit (events.js:172:7)
> 0|app      |     at Socket.<anonymous> (/home/so-delhi-api-gateway/sodelhi/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:133:10)
> 0|app      |     at Socket.g (events.js:260:16)
> 0|app      |     at emitNone (events.js:67:13)
> 0|app      |     at Socket.emit (events.js:166:7)
> 0|app      |     at Socket._onTimeout (net.js:318:8)
> 0|app      |     at _runOnTimeout (timers.js:524:11)
> 0|app      |     at _makeTimerTimeout (timers.js:515:3)

**Comment by varunjayaraman** [comment]
Are you sure port 27017 is exposed. And are you even using mongoose, I don't see that in the stack trace. If you aren't using mongoose this issue is better suited for the node mongodb client

**Comment by vkarpov15** [comment]
Not a mongoose issue, the connection issue is with [connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session).
