### ISSUE TITLE
Option to add indexes as called instead of in background for tests

### ISSUE THREAD

**Issue by OmgImAlexis** [Automattic/mongoose#5342]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Mongoose sets `background: true` with `ensureIndex`.

**What is the expected behavior?**
When `NODE_ENV=test` allow `ensureIndex` to create indexes as the model is loaded. This fixes issues with tests running before indexes are created and ending up with `text index required for $text query`.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.0.0
Mongoose: 4.10.5

**Comment by vkarpov15** [comment]
You can always overwrite the background property on your indexes conditionally, like:

```javascript
new Schema({
  name: String,
  email: { type: String, index: { unique: true, background: false } }
});
```

Easy to adapt this for NODE_ENV:

```javascript
new Schema({
  name: String,
  email: { type: String, index: { unique: true, background: process.env.NODE_ENV !== 'test' } }
});
```

As long as I'm working on the project, mongoose will never support any `NODE_ENV` functionality switches. Libs depending on environment variables is a gross antipattern.
