### ISSUE TITLE
Support MongoDB connection Setting

### ISSUE THREAD

**Issue by thomas-lee** [Automattic/mongoose#5345]
In the latest mongodb, the previous setting on properties db, server,replicaset are deprecated.
http://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/

Do current mongoose support those settings?

From the code, it seems still separate into db, server, replicaset in the parse method. 
Want to know if any plans to support the simplified configuration ?

Thanks

**Comment by vkarpov15** [comment]
See #5355. We're planning on deprecating current connection behavior in 4.11 in favor of the simplified approach and just delegating everything to the MongoDB driver.
