### ISSUE TITLE
runSettersOnQuery doesn't apply when used as a query option

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#5350]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`runSettersOnQuery` doesn't appear to work as a query option, e.g. `A.findOneAndUpdate({}, {...}, {runSettersOnQuery: true})` doesn't run setters. It does work as a schema option.

**If the current behavior is a bug, please provide the steps to reproduce.**
These assertions will fail (modified only slightly from your gh-4569 test case):
```js
  it('lowercase in update (gh-XXXX)', function(done) {
    var db = start();

    var testSchema = new Schema({
      name: { type: String, lowercase: true }
    });

    var Test = db.model('gh-XXXX', testSchema);
    Test.create({ name: 'val'}).
      then(function() {
        return Test.findOne({ name: 'VAL' }, { runSettersOnQuery: true });
      }).
      then(function(doc) {
        assert.ok(doc);
        assert.equal(doc.name, 'val');
      }).
      then(function() {
        return Test.findOneAndUpdate({}, { name: "UPPERCASE" }, { new: true, runSettersOnQuery: true });
      }).
      then(function(doc) {
        assert.ok(doc);
        assert.equal(doc.name, 'uppercase');
      }).
      then(function() { done(); }).
      catch(done);
  });
```

**What is the expected behavior?**
It should run the setters on the `query` and `update` docs, as far as I understand the documentation.

**Please mention your node.js, mongoose and MongoDB version.**
Current master branch

**Comment by vkarpov15** [comment]
As documented, `runSettersOnQuery` can **only** be set on the schema options, not query options. Will add this as an enhancement for a future release.

**Comment by zbjornson** [comment]
It's actually documented as an option to [findOneAndUpdate](http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate), [findByIdAndUpdate](http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate) and [findOneAndRemove](http://mongoosejs.com/docs/api.html#model_Model.findOneAndRemove) already...

**Comment by zbjornson** [comment]
(PS: I saw your other issue for making `runSettersOnQuery: true` the only behavior in 5.0. Depending on when that ships, it might not make sense to support it at as a 4.x query option -- i.e. could just remove from the docs.)

**Comment by vkarpov15** [comment]
Good call, that's my mistake. Will fix this in a patch release. We'll keep the option for now because the timeline for releasing 5.0 is still hazy.
