### ISSUE TITLE
Populate Error.

### ISSUE THREAD

**Issue by muratersin** [Automattic/mongoose#5352]
I got this error:

Exception has occurred: Object
#<MongooseError>
MissingSchemaError: Schema hasn't been registered for model "LegalEntiyRequest".

From this code.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Throws error:
```bash
Exception has occurred: Object
#<MongooseError>
MissingSchemaError: Schema hasn't been registered for model "LegalEntiyRequest".
```

**If the current behavior is a bug, please provide the steps to reproduce.**
After assure of legalEntityRequest I try this populate, sub document population like below
```js
  StoreRequest.findById(storeRequestId)
      .populate('legalEntityRequest')
      .populate({
        path: 'legalEntity',
        populate: {
          path: 'legalEntityRequest'
        }
      })
      .then((result) => {
        req.storeRequest = result;
        next();
      })
      .catch((err) => {
        let error = app.icErrors.extractError(err);
        res.boom.badRequest(error.message, error);
      });
```

But this code is work:

```javascript
    LegalEntityRequest.find().then((result) => {
        console.log(result);
    });
```
**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
node version: 6.10.0
mongoose: 4.6.8

**Comment by zbjornson** [comment]
Looks like you have a typo: "LegalEntiyRequest" vs. "Entity".

**Comment by varunjayaraman** [comment]
yeah it looks like a typo. How do you define your model?

**Comment by muratersin** [comment]
My model defination.

```javascript
app.icMongoose.model('LegalEntityRequest', legalEntityRequest);
```
This code is working greatly by now. But deteriorated for no reason.
