### ISSUE TITLE
ValidationError is no longer compatible with boom

### ISSUE THREAD

**Issue by davebaol** [Automattic/mongoose#5359]
Mongoose 4.10.0 has broken the compatibility between `ValidationError` and [boom](https://www.npmjs.com/package/boom). Mongoose 4.9.10 and earlier had no problem at all with it.

This issue was supposed to be fixed - see https://github.com/Automattic/mongoose/issues/5309 and https://github.com/Automattic/mongoose/issues/5307 - but it's not in my case.

Here's a repro script taken from https://github.com/Automattic/mongoose/issues/5309#issuecomment-306660774 and specifically modified to use `boom.wrap()`:

````javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5359`;

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    require('boom').wrap(error, 400, 'A validation error occurred');
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: { type: String, required: true }
    });


    const Model = db.model('Model', schema);

    const doc = new Model();
    
    yield doc.validate();
  });
}
````

**Result using mongoose 4.10.0 -> 4.10.6:**
````
(node:22520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
TypeError: Cannot set property message of [object Object] which has only a getter
````

**Result using mongoose 4.9.10 (expected output):**
````
Error: ValidationError: Path `name` is required.
ValidationError: A validation error occurred: Model validation failed
    at MongooseError.ValidationError (<MY_PATH>\node_modules\mongoose\lib\error\validation.js:23:11)
    ...
````
**Software version:**
Node 6.10.2
Mongodb 3.4.1
Mongoose 4.9.x (working), 4.10.0 -> 4.10.6 (broken)

**Comment by paranormal** [comment]
The same, after https://github.com/Automattic/mongoose/issues/5309 and 4.10.6 the error is still there.
```Cannot set property message of```

**Comment by vkarpov15** [comment]
Good suggestion, will fix for next patch release.

**Comment by davebaol** [comment]
@vkarpov15 
Great! I got it working now using the master branch 👍

**Comment by vkarpov15** [comment]
Glad it works. Try upgrading to 4.10.8 or 4.11.0, should be fixed in those. Thanks for your patience and the detailed repro instructions

**Comment by davebaol** [comment]
Both 4.10.8 and 4.11.0 work for me. Thanks
