### ISSUE TITLE
Model.update fails on array of embedded docs with Decimal values 

### ISSUE THREAD

**Issue by alaa-ismail** [Automattic/mongoose#5361]
**What is the current behavior?**
Calling update on a model with an array of embedded documents containing a decimal type fails with the error `MongooseError: Cast to embedded failed for value`  

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect('mongodb://localhost:27017/test');

var schema = new mongoose.Schema({
    name: String,
    pricing: [{
        _id: false,
        program: String,
        money: mongoose.Schema.Types.Decimal
    }]
});

var Person = mongoose.model('Person', schema);

var data = {
    name: 'Jack',
    pricing: [
        { program: 'A', money: mongoose.Types.Decimal128.fromString('1.2') },
        { program: 'B', money: mongoose.Types.Decimal128.fromString('3.4') }
    ]
};

Person.create(data) // create works fine
    .then(data => {
        var newData = {
            name: 'Jack',
            pricing: [
                { program: 'A', money: mongoose.Types.Decimal128.fromString('5.6') },
                { program: 'B', money: mongoose.Types.Decimal128.fromString('7.8') }
            ]
        };
        return Person.update({ name: 'Jack' }, newData); // update doesn't work

    }).then(result => {
        console.log('done');
    });
```
**Current Behavior**
An error is thrown when trying to update
`MongooseError: Cast to embedded failed for value "{ money: { \'$numberDecimal\': \'7.8\' }, program: \'B\' }" at path "pricing"`

**Expected Behavior**
The model should be updated with the new value

**Versions**
Mongoose v4.10.6
MongoDB v3.4.3
Node v7.9.0

**Comment by varunjayaraman** [comment]
thanks, this looks like a problem with the `Embedded` constructor. Going to investigate further
