### ISSUE TITLE
Populated query can throw uncaught synchronous MissingSchemaError.

### ISSUE THREAD

**Issue by serhalp** [Automattic/mongoose#5364]
## Summary

When executing a query with a `populate()` with the signature without an explicit reference to the other model, mongoose throws a `MissingSchemaError` when that model isn't found. That this would not work is expected. However, `exec()` is async (it takes either a callback or returns a promise) but this error is thrown asynchronously and uncaught.

i.e. `Foo.find().populate('bar').exec()` where the model ref for the `bar` property is unknown triggers a node process `uncaughtException` (and likely shutdown of the process) – no promise rejection, no callback call with an error, no synchronous error.

## Repro
[Here are simple repro steps](https://gist.github.com/serhalp/cfd9e1af047a0b57034d0842d8a25e2a). Unfortunately this requires splitting the code across multiple files to repro (we need documents to exist, and we need the `Bar` model not to be registered in memory):
```
> node ./setup.js
> node ./index.js
Uncaught exception! { MissingSchemaError: Schema hasn't been registered for model "Bar".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (./node_modules/mongoose/lib/connection.js:889:11)
    at getModelsMapForPopulate (./node_modules/mongoose/lib/model.js:3408:18)
    at populate (./node_modules/mongoose/lib/model.js:2978:15)
    at _populate (./node_modules/mongoose/lib/model.js:2946:5)
    at Function.Model.populate (./node_modules/mongoose/lib/model.js:2906:5)
    at Immediate.cb (./node_modules/mongoose/lib/query.js:1126:17)
    at Immediate.<anonymous> (./node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  message: 'Schema hasn\'t been registered for model "Bar".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
```

## Expected behavior
- I would expect the gist I provided [to log "rejected with" followed by the `MissingSchemaError`](https://gist.github.com/serhalp/cfd9e1af047a0b57034d0842d8a25e2a#file-index-js-L16).
- I would expect the gist I provided, but with `Foo.find().populate('bar').exec(function (err, foos) { console.log('called back with', err, foos))`, to log "called back with" followed by the `MissingSchemaError`.

## Partial explanation
As far as I can tell, this is because [the `populate()` helper function in `lib/model.js` calls `getModelsMapForPopulate()` without a try-catch](https://github.com/Automattic/mongoose/blob/7d49b3722b74c382f60c067d29290aba51a691f9/lib/model.js#L2978) despite the fact that this function in turn [calls `model()`](https://github.com/Automattic/mongoose/blob/7d49b3722b74c382f60c067d29290aba51a691f9/lib/model.js#L3341), which [`can throw synchronous errors`](https://github.com/Automattic/mongoose/blob/7d49b3722b74c382f60c067d29290aba51a691f9/lib/connection.js#L888-L890). It seems that that `populate()` function should catch synchronous errors and call `callback(err)` with them. If that sounds right, I can open a PR.

What I don't quite understand is why that error [doesn't even bubble up as a synchronous error](https://gist.github.com/serhalp/cfd9e1af047a0b57034d0842d8a25e2a#file-index-js-L20-L24) – instead it's completely uncaught.

## Notes

Tested against mongoose@4.10.6, node@6.9.1, mongod@3.2.8.

**Comment by vkarpov15** [comment]
Thanks for finding this, will fix for next patch release.
