### ISSUE TITLE
Won't build with rollup.js

### ISSUE THREAD

**Issue by krstffr** [Automattic/mongoose#5365]
Using rollup with rollup-plugin-commonjs will throw the error `Error: Dynamic requires are not currently supported by rollup-plugin-commonjs` when trying to run a bundled app depending on mongoose.

This is the part throwing the error, I guess there's no obvious way around this? https://github.com/Automattic/mongoose/blob/67c465aac5c864c3004d11d49934605037c8f520/lib/drivers/index.js#L8

node v8.1.0
mongoose 4.10.5
rollup 0.42.0
rollup-plugin-commonjs 8.0.2

**Comment by vkarpov15** [comment]
No obvious away around this right now. Removing this dynamic import would be very backwards breaking. Are you trying to use mongoose in the browser?

**Comment by varunjayaraman** [comment]
yeah unfortunately the same problem occurs with webpack, although there's a hack that can be implemented to bypass this in webpack. I wonder if it's worth avoiding the dynamic import in 5.0 @vkarpov15 ?

**Comment by vkarpov15** [comment]
Might be fixed by #5443 . Re-open if there's a similar issue.
