### ISSUE TITLE
Query#populate with object in array returns null

### ISSUE THREAD

**Issue by Airblader** [Automattic/mongoose#5367]
I have a mongoDB database which is generated using a script that uses only the node.js mongoDB driver without mongoose. Later on, in the application, I want to use mongoose to load a document and have a reference be populated automatically; however, this only ever returns `null`.

The following code (requiring `npm install mongodb mongoose`) reproduces the problem (watch out, it destroys a local database named `test` if you have one already):

    const mongodb = require('mongodb');
    const mongoose = require('mongoose');
    const Schema = mongoose.Schema;
    
    (async () => {
        // Step 1: Insert data. This is done using the mongodb driver without mongoose.
        const db = await mongodb.MongoClient.connect('mongodb://localhost/test');
        await db.dropDatabase();
        await db.collection('persons').insertOne({ name: 'Joe' });
    
        const joe = await db.collection('persons').findOne({ name: 'Joe' });
        await db.collection('tasks').insertOne({ items: [{ title: 'Test', person: joe._id }] });
    
        await db.close();
    
        // ================
        // Step 2: Create the schemas and models.
        const PersonSchema = new Schema({
            name: String,
        });
        const Person = mongoose.model('Person', PersonSchema);
    
        const TaskSchema = new Schema({
            items: [{
                title: String,
                person: { type: Schema.Types.ObjectId, ref: 'Person' },
            }],
        });
        const Task = mongoose.model('Task', TaskSchema);
    
        // ================
        // Step 3: Try to query the task and have it populated.
        mongoose.connect('mongodb://localhost/test');
        mongoose.Promise = Promise;
    
        // I also tried adding .exec() and using a callback instead of Promises+await to no avail.
        const myTask = await Task.findOne({}).populate('items.person');
    
        // :-( Unfortunately this prints only
        // { _id: "594283a5957e327d4896d135", items: [ { title: 'Test', person: null } ] }
        console.log(JSON.stringify(myTask, null, 4));
    
        mongoose.connection.close();
    })();

The _expected_ output would be

    { _id: "594283a5957e327d4896d135", items: [ { title: 'Test', person: { _id: "594283a5957e327d4896d134", name: "Joe" } } ] }

I have verified that the two `_id`s actually match using mongo shell:

    > db.persons.find({})
    { "_id" : ObjectId("594283a5957e327d4896d134"), "name" : "Joe" }
    > db.tasks.find({})
    { "_id" : ObjectId("594283a5957e327d4896d135"), "items" : [ { "title" : "Test", "person" : ObjectId("594283a5957e327d4896d134") } ] }

Based on the docs and, for example, [this](https://alexanderzeitler.com/articles/mongoose-referencing-schema-in-properties-and-arrays/) I think the code *should* work, but it doesn't. Versions I'm using:

* mongoDB: 3.4.3
* mongoose: 4.10.6
* mongodb (npm): 2.2.28

This has also been posted to [StackOverflow](https://stackoverflow.com/questions/44568253/mongoosepopulate-returns-null-in-nested-object-inside-array).

**Comment by Airblader** [comment]
Well, false alarm, I guess. The problem here is that mongoose infers the collection name `people` for the model `Person` and not `persons`.

Before closing this ticket – are these non-trivial decisions documented somewhere?

**Comment by Airblader** [comment]
Searching the code for pluralization rules (which are in `bin/mongoose.js` for anyone looking for it – watch out, they are written with regular expressions and not easily searchable) I found that pluralization is deprecated anyway, so closing this due to #1350.

**Comment by vkarpov15** [comment]
Sorry about the inconvenience, this is why we're removing pluralization :)
