### ISSUE TITLE
Failing to install Mongoose

### ISSUE THREAD

**Issue by Nazarah** [Automattic/mongoose#5375]
I am having the following error when I am trying to install mongoose using npm.

Here is the message displayed in the GitShell

~\Documents\GitHub\zodiac-api\node_modules> npm install mongoose
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\Omistaja\Documents\GitHub\zodiac-api\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '/' at 1:1
npm ERR! // package.json
npm ERR! ^
npm ERR! File: C:\Users\Omistaja\Documents\GitHub\zodiac-api\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Omistaja\Documents\GitHub\zodiac-api\node_modules\npm-debug.log

I am also attaching the log file 
<img width="961" alt="capture" src="https://user-images.githubusercontent.com/17976243/27278952-a29abd54-54eb-11e7-9141-0e7bd456de83.PNG">

**Comment by kevinadi** [comment]
The error seems to point out that the file `C:\Users\Omistaja\Documents\GitHub\zodiac-api\package.json` contains an unexpected character (apparently a slash `/`).

This doesn't look like a mongoose issue.

**Comment by varunjayaraman** [comment]
the error message indicates that there's probably a typo in your package.json, can you post it here? Or pass it through a json validator?

**Comment by Nazarah** [comment]
@varunjayaraman thanks for your reply.
here is the content of the package.json file

// package.json

{
    "name": "node-api",
    "main": "server.js",
    "dependencies": {
        "express": "~4.0.0",
        "mongoose": "~3.6.13",
        "body-parser": "~1.0.1"
    }
}

**Comment by rodrigoalviani** [comment]
Simple remove this line from your package.json:
`// package.json`

**Comment by vkarpov15** [comment]
There's no way to put comments in JSON, remove the `//` line and you should be fine. Either way, this is not a mongoose issue.
