### ISSUE TITLE
Timeout when Parallelizing queries

### ISSUE THREAD

**Issue by cyrilchapon** [Automattic/mongoose#5376]
When parallelizing queries with `Promise.all` approach, we're taking a timeout.

```
Promise.all([
  col1.find({longQuery: true}),
  col2.find({longQuery: true})
])
.spread(function(result1, result2) {
  //stuff
});
```

throws 

```
error:  MongoError: connection 15 to <MYCONNECTION> timed out
    at Function.MongoError.create (<MYPATH>\node_modules\mongodb-core\lib\error.js:29:11)
    at TLSSocket.<anonymous> (<MYPATH>\node_modules\mongodb-core\lib\connection\connection.js:188:20)
    at TLSSocket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

whereas 
```
col1.find({longQuery: true})
.then(function(result1) {
  return Promise.all([
    result1,
    col2.find({longQuery: true})
  ]);
})
.spread(function(result1, result2) {
  //stuff
});
```

Doesn't.

We are using this config :
```
    "<MYCONN>": {
      "server": {
        "poolSize": 5,
        "socketOptions": {
          "autoReconnect": true,
          "keepAlive": 120,
          "socketTimeoutMS": 0,
          "wtimeoutMS": 0,
          "connectTimeoutMS": 0
        }
      },
      "replset": {
        "poolSize": 5,
        "socketOptions": {
          "autoReconnect": true,
          "keepAlive": 120,
          "socketTimeoutMS": 0,
          "wtimeoutMS": 0,
          "connectTimeoutMS": 0
        }
      }
    }
```

Versions :
```
node -v
v6.9.1
```

```
npm list mongodb-core
`-- mongoose@4.10.6
  `-- mongodb@2.2.27
    `-- mongodb-core@2.1.11
```

**Comment by vkarpov15** [comment]
What promise lib are you using, also what's your ssl config?

**Comment by cyrilchapon** [comment]
I'm using bluebird, and I just have ssl=true

**Comment by cyrilchapon** [comment]
(but actualy it does the same both on mongo cloud with a replica + shard under SSL and in local with mongo running without SSL)

**Comment by vkarpov15** [comment]
Roughly how long is the query taking to run?

**Comment by cyrilchapon** [comment]
Probably something between 2 and 3 seconds

**Comment by vkarpov15** [comment]
You mentioned that you're using sharding, have you tried adding `mongos` to your options above?

```javascript
{
      "server": {
        "poolSize": 5,
        "socketOptions": {
          "autoReconnect": true,
          "keepAlive": 120,
          "socketTimeoutMS": 0,
          "wtimeoutMS": 0,
          "connectTimeoutMS": 0
        }
      },
      "replset": {
        "poolSize": 5,
        "socketOptions": {
          "autoReconnect": true,
          "keepAlive": 120,
          "socketTimeoutMS": 0,
          "wtimeoutMS": 0,
          "connectTimeoutMS": 0
        }
      },
      "mongos": {
        "poolSize": 5,
        "socketOptions": {
          "autoReconnect": true,
          "keepAlive": 120,
          "socketTimeoutMS": 0,
          "wtimeoutMS": 0,
          "connectTimeoutMS": 0
        }
      }
    }
```

Also, I'd recommend you use the `useMongoClient` option in 4.11 so you can use top-level `socketTimeoutMS` in your options, that's much easier:

```javascript
const mongoose = require('mongoose');

test().catch(error => console.log(error.stack));

async function test() {
  await mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true, socketTimeoutMS: 0 });

  await mongoose.connection.dropDatabase();

  const M1 = mongoose.model('M1', new mongoose.Schema({ name: String }));
  const M2 = mongoose.model('M2', new mongoose.Schema({ name: String }));

  await M1.create({ name: 'test' });
  await M2.create({ name: 'test' });

  await Promise.all([
    M1.find({ $where: 'sleep(31000); return true;' }),
    M2.find({ $where: 'sleep(31000); return true;' })
  ]);
  console.log('done');
}
```

Finally, there's also operating system level timeouts on sockets that you may need to tweak manually. Here's some info on the windows ones: https://unix.stackexchange.com/questions/136642/how-to-make-a-tcp-socket-time-out

**Comment by binki** [comment]
Maybe fixed by switching to `useMongoClient`? See [my experience in #4789](https://github.com/Automattic/mongoose/issues/4789#issuecomment-410130496). This seems to be the intermittent timeout errors for heavy but short-running queries mentioned on that same issue thread.

**Comment by SergeyVatz** [comment]
mongodb-core@2.1.10
mongodb@2.2.26
mongoose@4.9.10
Have the same problem, 1.5M errors in roll bar for a couple of days, with what it can be connected? How resolve?
<img width="671" alt="screen shot 2019-02-25 at 2 54 01 pm" src="https://user-images.githubusercontent.com/36629375/53338879-7c0b8a80-390d-11e9-8823-4e592b4d2593.png">
<img width="790" alt="screen shot 2019-02-25 at 2 55 27 pm" src="https://user-images.githubusercontent.com/36629375/53338880-7ca42100-390d-11e9-87fa-42b2bd6231a6.png">
<img width="925" alt="screen shot 2019-02-25 at 2 53 37 pm" src="https://user-images.githubusercontent.com/36629375/53338905-8a59a680-390d-11e9-9826-acf95786af0a.png">

**Comment by vkarpov15** [comment]
@SergeyVatz I'm guessing this is due to slow queries timing out the socket. Try increasing your socketTimeoutMS: https://mongoosejs.com/docs/connections.html#options

**Comment by SergeyVatz** [comment]
@vkarpov15 I set a timeout of 0, and I think this fixed the problem, is this the right solution? And will there be any problems in the future? Or the best solution would be to raise the timeout?

**Comment by vkarpov15** [comment]
Setting the timeout to 0 means never time out, which should prevent these timeouts from happening in general. That should solve your problem going forward. See https://mongoosejs.com/docs/connections.html#options for more options

**Comment by SergeyVatz** [comment]
@vkarpov15 thx!
