### ISSUE TITLE
Attempting to save a field not in schema with strict:false does not save the field. 

### ISSUE THREAD

**Issue by omanizer** [Automattic/mongoose#5378]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
When saving a non-strict model that contains fields not in the schema I would expect it to save all fields.
**If the current behavior is a bug, please provide the steps to reproduce.**

```
let schema = new mongoose.Schema({
  fieldOne: String
}, {
  strict: false
})

let Model = mongoose.model('Model', schema)

let func = async () => {
  let instance = new Model()
  instance.fieldOne = 'abc'
  instance.fieldTwo = 'def'
  await instance.save()

  let instance2 = await Model.findOne({_id: instance._id})

  console.log(instance2.fieldOne)
  console.log(instance2.fieldTwo)
}

func()
```
When I run it I get this output:
```
abc
undefined
```

**What is the expected behavior?**
I would expect to get the below output:
```
abc
def
```
**Please mention your node.js, mongoose and MongoDB version.**
node v7.10
mongoose@4.10.6
mongo 3.4

**Comment by omanizer** [comment]
Seems to be a dup of https://github.com/Automattic/mongoose/issues/1994

**Comment by omanizer** [comment]
It's noteworthy that this works (in context of the above code):

```
instance.set('fieldTwo', 'def')
console.log(instance.get('fieldTwo')) // def
```

I can achieve the desired behavior using a proxy object but it would be much more convenient to not need to go this route and be able to assign to the object directly.

**Comment by kevinadi** [comment]
Note that you can set the custom fields during object creation instead:

```js
var Person = mongoose.model('person', mongoose.Schema({
    name: String
}, {strict: false}));

var db = mongoose.connect('mongodb://localhost:27017/test').connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function(){
    var doc = new Person({
        name:'Bob',
        phone:'123-4567'  // set custom field during document creation
    });
    doc.save(function(err) {
        if (err) {
            return console.log(err);
        }
        db.close();
    });
});
```

This results in:

```
> db.people.find()
{
  "_id": ObjectId("594b69e77b67c106cb95dd4e"),
  "name": "Bob",
  "phone": "123-4567",
  "__v": 0
}
```

Is this what you require? I believe you would need to use the [Document set method](http://mongoosejs.com/docs/api.html#document_Document-set) if the document is already instantiated. Hence, I don't think this is a bug.

**Comment by omanizer** [comment]
For my use case the document will already be instantiated.  Ended up doing this as a hack since I needed to be able to set actual properties to the model rather than call getter/setter methods:

```
let Person = mongoose.model('person', mongoose.Schema({
  name: String
}, {strict: false}))
let myModel = new Person()
let modelProxy = new Proxy(myModel, {
  get (target, key) {
    target.get(key)
  },
  set (target, key, value) {
    target.set(key, value)
    return true
  }
})
// Then later on
modelProxy.randomFact = 'Joe Cool' // This works now
```

I'd argue that it is behavior is not ideal since many instances in the docs illustrate getting/setting fields using assignment as object properties rather than getter/setter methods.  This is one of the enticements for me to use mongoose as it pretends to be sort of an "active record".

Anyway, the proxy object works fine for my use cases but I think property assignment should work in non-strict mode rather than having to use the get/set methods.  If I turn off "string" I'm basically saying that I don't want mongoose to manage properties going in/out of the model instance for me, regardless of the path I take to get/set data, yet it still does to some extent.

**Comment by varunjayaraman** [comment]
the docs presume you are not setting `{ strict: false }` in those examples. I will label this a feature request because this definitely not a bug, it's intentional behavior. To be honest, I think forcing the user to do `doc.set` makes them think about what fields they want to set in the db that dont live in the schema, which is a good thing. 

Also, under the hood, mongoose properties have internal getters and setters anyway, so you can't really get around that.

**Comment by vkarpov15** [comment]
Upon closer inspection this will be exceptionally difficult and error-prone to support given mongoose's internals. Each document has an `_doc` that contains the underlying data, so we'd need to make sure to sync `instance.fieldTwo` with `instance._doc.fieldTwo` without knowing ahead of time that `fieldTwo` will be set. That's not really possible without proxies, and relying on proxies is not on the table at least until 5.0.

For now, you need to use `.get()` and `.set()` to deal with fields that aren't in the schema. These fields will still be in the `JSON.stringify()` and `toObject()` output:

```javascript
let func = async () => {
  let instance = new Model()
  instance.fieldOne = 'abc'
  instance.set('fieldTwo', 'def')
  await instance.save()

  let instance2 = await Model.findOne({_id: instance._id})

  console.log(instance2.fieldOne)
  console.log(instance2.get('fieldTwo'))
  // Has `fieldTwo`
  console.log(instance2.toObject())
}
```

**Comment by codiophile** [comment]
> That's not really possible without proxies, and relying on proxies is not on the table at least until 5.0.

@vkarpov15 5.0 has been out for a while now, so I thought I'd ask for an update: Is this now something that you are considering or this still remains a `won't fix` issue?

**Comment by vkarpov15** [comment]
No this is still a won't fix. It's a massive change and will have a lot of unintended consequences for use cases like storing temporary values on docs to pass data between middleware functions.

**Comment by makiJS** [comment]
Still getting this in this on the new model initialization:

```
let schema = new mongoose.Schema({
  fieldOne: String
}, {
  strict: false
})

let Model = mongoose.model('Model', schema)

let func = async () => {
  let instance = new Model({
    fieldOne: 'abc',
    fieldTwo: 'def'
  })
  await instance.save()

  let instance2 = await Model.findOne({_id: instance._id})

  /**
  OUTPUT instance2 OBJECT 
  {
    _id: mongoId, 
    fieldOne: 'abc'
  }
  **/
}

func()
```

**Comment by vkarpov15** [comment]
@makiJS see this comment please: https://github.com/Automattic/mongoose/issues/5378#issuecomment-396011405
