### ISSUE TITLE
findOne returning plain object instead of model in callback

### ISSUE THREAD

**Issue by johannesspohr** [Automattic/mongoose#5379]
I'm using findOne inside a plugin schema method, and the passed parameter is an instance of Object and therefore has no save method. It's working as expected in mongoose 4.2.4, but not in the latest version (4.10). Am i doing something wrong or is this a bug?
(same in latest node 6 and 8, MongoDB version 3.4.5)

```js
schema.methods.saveScoped = function(auth, callback) {
        var conditions = ...
        var savecallback = function(e, res) {
            if (e)
                callback(e);
            if (res) { // an entry was found that matches the scope and the id
		console.log(res.save); // <--- undefined in latest mongoose version
                ....
                res.save(callback); // <-- obviously fails becaue no save method is present
                return res;
            } else {
               ...
            }
        };

	this.collection.findOne(conditions, savecallback);
    };
```

**Comment by vkarpov15** [comment]
Why are you doing `this.collection.findOne` ? That would never return a model instance. Why not just `this.findOne`?

**Comment by johannesspohr** [comment]
I was a little confused with how to get the Model of a Document (like "this" is in the example since it's a method of Document, and because it worked in older version I thought this would be the right way). So this.findOne is undefined, but after a little research i found out that this.constructor.findOne should be the right way here. Thanks for the hint.

**Comment by vkarpov15** [comment]
Yep `this.constructor.findOne()` is the way to go. `doc.constructor` is how you get the model from the document.
