### ISSUE TITLE
Model in middleware?

### ISSUE THREAD

**Issue by cyper8** [Automattic/mongoose#5381]
Is there a way to have Model instance (or something to fire new query) in post middleware (either document or query)?

Just to clarify - i'm setting a hook in a plugin context, so i don't have an outer scope with model instance.
I can (and probably will) try to `this.find({newqueryoptions})` in _query middleware_ since `this` is a query instance (still unsure about outcome of it - can query be reexecuted?), but what to do with 'save' and 'remove' hooks? - I have no idea

**Comment by cyper8** [comment]
Ok, so after some research I can say that in query middleware (where `this` __is__ an instance of `Query`) you can reach current model at `this.model`. However `insertMany` is not a query middleware that way (despite the documentation states otherwise) because it's `this` is the Model itself (mongoose v4.10.5) and argument is an array of newly inserted & created documents - much like in _document middleware_.
As for the _query middleware_ - `this.find().exec()` reexecutes previous query as __find__ query. It is handy if you __realy, absolutely__ need to have docs (or at least their ids), affected by the hooked operation and they cannot be retrieved from the hook argument (specifically _updated docs' Ids_, since upserted Ids and inserted Ids are returned). Its another round trip to a DB and its __bad__.
Now - _document middleware_. Model here is reachable at `this.constructor`. and docs are always returned as an argument - whew ;)

**Comment by cyper8** [comment]
I'd better reopen this, cause Docs still have to be corrected - 'insertMany' hook has either to be moved to a document middleware or 'insertMany', 'save' and 'remove' have to be separated to new category - say - "Model middleware".

**Comment by varunjayaraman** [comment]
sorry, are you saying you dont think the middleware for those latter hooks belong in the section they are currently in?

**Comment by cyper8** [comment]
I guess the best way would be not to "categorize" middleware but to explicitly describe how the bonded function is called upon each hook: what is `this`, what arguments are passed and so on. Since I had to investigate without relying on the docs.

**Comment by varunjayaraman** [comment]
Will take that into consideration, thanks
