### ISSUE TITLE
Models Validate before setting defaults

### ISSUE THREAD

**Issue by deathgaze** [Automattic/mongoose#5383]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I set both `default` and `required` on a schema, saving a model causes an error if the model was instantiated using default values.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const Todo = new Schema({
  text: {
    type: String,
    required: true,
    default: '',
  },
  done: {
    type: Boolean,
    required: true,
    default: false,
  },
});

export default mongoose.model('Todo', Todo);
```
Later...
```
  new Todo()
  .save()
  .then(newTodo => res.json(newTodo))
  .catch(e => res.status(500).send(e));
```
Causes error: 
```
{
    "errors": {
        "text": {
            "message": "Path `text` is required.",
            "name": "ValidatorError",
            "properties": {
                "type": "required",
                "message": "Path `{PATH}` is required.",
                "path": "text",
                "value": ""
            },
            "kind": "required",
            "path": "text",
            "value": ""
        }
    },
    "_message": "Todo validation failed",
    "name": "ValidationError"
}
```

Additionally, I can inspect the value of the created todo before I save it and I can see that it's properly populating. However Mongoose still won't let me save. :(

For example:
```
  let todo = new Todo();
  console.log(todo.inspect());
  // { _id: 594972eefe0b873338fe939d, done: false, text: '' }
  // It's populated! Why won't it save?

  todo
  .save()
  .then(newTodo => res.json(newTodo))
  .catch(e => res.status(500).send(e));
```

**What is the expected behavior?**
Mongoose should be setting defaults on the model's data members before it's doing validation checks on missing paths. This way, objects can be instantiated with sensible defaults without losing the ability to require a field be present at all times. Of course, there might be a way to do this that I'm not seeing...

**Please mention your node.js, mongoose and MongoDB version.**
Node: 6.0.0 
Mongoose: 4.10.5
MongoDB: 3.5.8-82-g60341ff

**Comment by kevinadi** [comment]
I would think that having the setting `{required: true, default: ''}` is a contradiction, and the `required: true` setting should have precedence over the `default`.

My reasoning is:
* `default` is the value if **no value** is given during construction
* `required` means that the model **must** have a supplied value during construction

I think this is "Works as designed" and not a bug.

**Comment by varunjayaraman** [comment]
yeah this doesn't seem like a bug to me. `''` is a falsey value in javascript

**Comment by vkarpov15** [comment]
Expected behavior, the empty string `''` does not satisfy the `required` condition for strings.
