### ISSUE TITLE
During update--> RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by obbiettivo** [Automattic/mongoose#5386]
Dear All

I have update nodejs version to 0.11(mongoose working) from 4.8.3(failed).

During the change mongoose, at application restart detect the following error:

/home/vincenzo/sviluppo/backend/node_modules/mongoose/lib/utils.js:426
      return '[object Object]' == toString.call(arg);
                                           ^    
    RangeError: Maximum call stack size exceeded
        at Object.toString (native)
        at Object.exports.isObject (/home/vincenzo/sviluppo/backend/node_modules/mongoose/lib/utils.js:426:40)
        at merge (/home/vincenzo/sviluppo/backend/node_modules/mongoose/lib/utils.js:362:24)
        at merge (/home/vincenzo/sviluppo/backend/node_modules/mongoose/lib/utils.js:363:7)

-Follow the versioning used:
Node Version: v4.8.3
db version v3.2.10
mongoose": "4.4.14",

Note: this problem occurred on any mongoose version tested 
(I run [Nodejs  v4.8.3] -[db version v3.2.10] with  mongoose": >= "4.X.X until to "latest"  without success ,

 while it works if I use:

Node Version: v2.5.0
db version v3.2.10
mongoose": "4.4.14",

Where I'm wrong?

Regards
Vincenzo Centofanti

**Comment by vkarpov15** [comment]
I'm going to need more code samples, like what does the code that triggers this error looks like. I suspect this may be related to relying on `global.toString()`, which confuses certain brittle libraries like jest (https://github.com/mongodb/node-mongodb-native/pull/1494) but without code samples I'd be just taking shots in the dark.

**Comment by obbiettivo** [comment]
Okay, I will check my source, 
your indication above already help me to focus the problem......

I will let you know...
thanks
Vincenzo

**Comment by obbiettivo** [comment]
**Dear Karpov

Follow a detailed analysis, with cfg files used:


Current errore traced is:**

/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:499
      return Object.prototype.toString.call(arg) === '[object Object]';
                                       ^
    
    RangeError: Maximum call stack size exceeded
        at new Boolean (native)
        at Boolean.toString (native)
        at Object.exports.isObject (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:499:36)
        at merge (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:423:26)
        at merge (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:424:9)
        at merge (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:424:9)
        at merge (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:424:9)

**In my utils.js in  extendModel function a console.trace was inserted**
##############################################################
exports.extendModel = function(modelName, newModelName, extendedSchema, collection) {
    console.trace();
    var path = ('../models/' + modelName).toLowerCase();
    var baseModel = require(path);

    extendedSchema.set('discriminatorKey', 'kind');
    extendedSchema.set('versionKey', false);

    return baseModel.discriminator(newModelName, extendedSchema, collection);
}
####################################################################
**And the Trace reported me**:

    Trace
        at Object.exports.extendModel (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/libs/util.js:2:13)
        at Object.<anonymous> (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/models/story.js:119:23)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/libs/elastic/util.js:2:13)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/libs/index.js:8:17)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
    /home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/node_modules/mongoose/lib/utils.js:499
#####################################################################

**I think that the error is in  story.js row number 119 at follow ==>(module.exports = Util.extendModel('Content', 'Story', storySchema, 'contents');**

        at Object.<anonymous> (/home/vincenzo/sviluppo/story-viewer/node_modules/cms-4-0/models/story.js:119:23)


STORY.JS file
############################################################
var mongoose = require('mongoose');
var ContentModel = require('./content');
var FolderModel = require('./folder');
var Util = require('../libs/util');
var mongoosastic = require('mongoosastic');
//Configurazione elasticsearch
var config = Util.Configuration.getConfig();
var port = 9200;
var host = 'localhost';
if(config && config.database && config.database.elastic){
	port = config.database.elastic.port;
	host = config.database.elastic.hostname;
}
if (config.script) {
        console.log('Story model loaded from elastic sync script');
}

var block = mongoose.Schema({
    type                : String,
    vTour               : String,
    text                : {
        it: String,
        en: String,
        fr: String,
        es: String,
        de: String
    },
    storyBricks         : [{ type: mongoose.Schema.Types.ObjectId, ref: ContentModel.modelName }],
    option              : {
        counter             : Number,
        fit                 : { type: Boolean, default: false },
        showtext            : { type: Boolean, default: true },
        reverse             : { type: Boolean, default: false },
        bigbrick            : { type: Boolean, default: false },
		stripes				: { type: Boolean, default: false },
        fixedbrick          : { type: Boolean, default: false },
        float               : { type: String, default: '' },
        animation           : {
            keyframe            : { type: Number, default: 0 },
            duration            : { type: Number }
        },
        textAnimation       : {
            nameId              : { type: Number, default: 0 }
        },
    }
});

var viewOption = {
    coverStyle          : {type: String, default: 'contain'},
    showContacts        : {type: Boolean, default: true},
    suggestion          : {type: Boolean , default: true},
    template            : {type: String, default:'default'},
    colNum              : {type: Number, default: 2},
    itemsPerCol         : Number,
    footerNotes         : String,
    personalCss         : String,

};

var data = mongoose.Schema({
    date : Date,
    views : { type: Number },
    uniqueViews : { type: Number }
});

var storySchema = mongoose.Schema({
    parent              : { type: mongoose.Schema.Types.ObjectId, ref: FolderModel.modelName, index: true },
    languages           : [],
    defaultLanguage     : {type: String, enum: ['it', 'en', 'fr', 'es', 'de']},
    storyType           : {type: String, enum: ['curated', 'didactic', 'dynamic', 'map', 'path'], default: 'curated'},
    title               : {
        it: String,
        en: String,
        fr: String,
        es: String,
        de: String
    },
    description         : {
        it: String,
        en: String,
        fr: String,
        es: String,
        de: String
    },
    coverImage: {
        origin: String,//card.origin,
        imageUrl: String,//card.multimediaImg,
        link: String,//card.sourceLink
    },
    mobileCoverImage   : {
        origin: String,//card.origin,
        imageUrl: String,//card.multimediaImg,
        link: String,//card.sourceLink
    }, // low resolution
    blocks              : [block],
    track               : { type: mongoose.Schema.Types.ObjectId, ref: ContentModel.modelName },  // Traccia audio per template multimediale.
    permission          : { type: String, enum: ['public', 'private','visible'], default: 'private' },
    analytics           : { type: [data] },
    sponsored           : {type: Boolean, default: false, index: true},
    viewOption          : viewOption,
    elastic             : {type: Object, default:{}}
});

storySchema.pre('save', function(next){
    if (!config.script)
	   this.modifiedAt = new Date();
	this.languages = Util.setLanguages(this.title.toObject(),this.description.toObject(),this.blocks.toObject());
	this.elastic = {};
    this.elastic.name = this.name;
	this.elastic.createdAt = this.createdAt;
	this.elastic.modifiedAt = this.modifiedAt;
 	this.elastic.meanLocation = Util.locationReduce(this.location);
	this.elastic.location = this.location;
	this.elastic.available = this.status.available;
	next();
});

storySchema.plugin(mongoosastic,{bulk:false,host:host,port:port});
module.exports = Util.extendModel('Content', 'Story', storySchema, 'contents');
############################################################################

****Infact if this row ==>**
(module.exports = Util.extendModel('Content', 'Story', storySchema, 'contents');)

**is disabled the error disappeared...
But  I am unable to focus the cause

Regards
Vincenzo****

**Comment by obbiettivo** [comment]
Dear Kaparov

Please discard the issue above, the error was removed using 
Node 7.6.0 and mongoose 4.11.1 togheter

thanks
Vincenzo
