### ISSUE TITLE
Add dropCollection() helper to connection

### ISSUE THREAD

**Issue by irakli2692** [Automattic/mongoose#5393]
On the line
`mongoose.connection.db.dropCollection('projects');`
I am getting error
```
 TypeError: Cannot read property 'commandsTakeWriteConcern' of null
      at decorateWithWriteConcern (node_modules\mongodb\lib\db.js:497:36)
      at Db.dropCollection (node_modules\mongodb\lib\db.js:846:3)
      at Object.exports.truncateProjectsCollection (test\helpers\project-db-hooks.js:9:33)
      at Context.<anonymous> (test\users-routes.js:27:22)
```

mongoose: 4.10.8
node.js: 6.10.2
MongoDb: 3.2.8

**Comment by irakli2692** [comment]
```js
const projectsCollection = 'projects';

exports.truncateProjectsCollection = function () {
  return mongoose.connection.db.collection(projectsCollection).remove();
};
```

**Comment by irakli2692** [comment]
```js
const projectsCollection = 'projects';

exports.truncateProjectsCollection = function () {
  return mongoose.connection.db.dropCollection(projectsCollection);
};
```

as I understood, when dropCollection is called mongoose is not connected yet.

I am using this for api testing. when I add other tests that run before the test, that calls `dropCollection`, then everything works well.

**Comment by vkarpov15** [comment]
Mongoose buffering doesn't work if you bypass mongoose collections entirely. Try doing `mongoose.connection.collections[projectsCollection].drop()` instead. We'll add a `dropCollection()` helper to mongoose for the next minor release
