### ISSUE TITLE
DateSchema does not behave as the Date object in Javascript does.

### ISSUE THREAD

**Issue by gregksurveillus** [Automattic/mongoose#5395]
This is the code in mongoose from THIS repository (as far as I can tell this in the current release):

`SchemaDate.prototype.cast = function(value) {`
 ```
...
 if (value instanceof Number || typeof value === 'number'
      || String(value) == Number(value)) {
    // support for timestamps
    date = new Date(Number(value));
  }
...
```
The check`String(value) == Number(value)` combined with the actual construction `date = new Date(Number(value));` causes things like` cast('2017')` to return a date 2017 milliseconds into January 1, 1970 versus exactly January 1, 2017 which is what `new Date('2017')` does.

**Comment by varunjayaraman** [comment]
I'd say that is probably a weird value to pass in but you're right, it leads to wonky results

**Comment by vkarpov15** [comment]
I agree this is weird, but changing this would be backwards breaking so will consider it for a future backwards breaking release
