### ISSUE TITLE
Docs for default behavior of Model/Query.remove and justOne option are wrong

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#5396]
**Do you want to request a *feature* or report a *bug*?**

Error in docs.

http://mongoosejs.com/docs/api.html#model_Model.remove says it *"Removes the first document that matches conditions from the collection. To remove all documents that match conditions, set the justOne option to false."*

As far as I've tested and read the source code, `Model.remove`/`Query.remove` actually removes *all* matching documents by default, and the `justOne` option does nothing.

The corresponding option in the mongodb driver is called `single` and it defaults to `false` ([docs](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#remove)).

Passing a `single` option to `Model.remove`/`Query.remove` *does* work.

I'm about to submit a PR to change the option name and correct the docs. It's sort of a breaking change to rename the option to `single`, except that it doesn't work currently.

**Comment by varunjayaraman** [comment]
you're right, the docs are wrong:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5396`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: String
    });


    const Model = db.model('Model', schema);

    yield Model.remove({});

    yield Model.create([
      { name: 'test' },
      { name: 'test' },
      { name: 'test' }
    ]);

    yield Model.remove({ name: 'test' });

    console.log(yield Model.count({ name: 'test' })); // 0 :(
  });
}
```
