### ISSUE TITLE
Upsert duplicate key error mongoose

### ISSUE THREAD

**Issue by KaranSaldhana** [Automattic/mongoose#5400]
I have a collection named 'staff' where I am trying to update this collection with upsert as true using mongoose. But as I am trying to update my collection its giving me an error
E11000 duplicate key error collection: pms_db.persons index: _id_ dup key: { : ObjectId('593a6432a745f6108ef3c47f') }

**Query**: staffs.update({ _id: '593a6432a745f6108ef3c47f' }, {"$set":{"visit_type_code_duration":[{"facility_id":"58d37cec31a7361b85670b74","visit_type_code":"590439ad7abc11fb61c2022f","duration_in_minute":50},{"facility_id":"58d37cec31a7361b85670b74","visit_type_code":"59043a0a7abc11fb61c202d9","duration_in_minute":30},{"facility_id":"58d37cec31a7361b85670b74","visit_type_code":"592527ee2b8ed23cb2f844
b5","duration_in_minute":10}]}})

But when I execute the same query in MongoDB its working properly

**Comment by davebaol** [comment]
You got the duplicate key error on collection `persons`, not `staff` as you said.
I'm just taking a wild guess, maybe you've mapped the `Staff` model to the wrong collection?

**Comment by KaranSaldhana** [comment]
I forgot to mention i am using mongoose extend plugin. 
[https://www.npmjs.com/package/mongoose-schema-extend](url)
I have a main schema named Persons which is been extended by staffs and providers schemas.

When I try to execute update query for staff schema with upsert its not working but the same is working for providers schema in mongoose.

**Comment by davebaol** [comment]
🤔 What's the advantage of that plugin over regular mongoose discriminators?
Just curious

**Comment by varunjayaraman** [comment]
yep @davebaol is right on 2 both counts: 1) looks like the duplicate key is on your persons collection, so could i see how your current operation uses the Person model and 2) whats the advantage of that plugin over just using a discriminator?

**Comment by KaranSaldhana** [comment]
I'll try using mongoose discriminator see if it works

**Comment by vkarpov15** [comment]
I'd also be careful about using mongoose-schema-extend, it does some monkey-patching of mongoose internals and there are much easier ways to do schema inheritance in mongoose

**Comment by varunjayaraman** [comment]
thanks, can you let us know if discriminators resolve your issue @KaranSaldhana ?

**Comment by spruce** [comment]
@vkarpov15 what is the easier way? using discriminators?

**Comment by vkarpov15** [comment]
@spruce 

```javascript
function baseSchema() {
    Schema.apply(this, arguments);

    this.add({
        name: String
    });
    this.statics.testFn = function() { return 42; };
}

// `mySchema` will also get a `name` property and a `testFn` static function from `baseSchema`
var mySchema = new baseSchema({ otherProp: String }, { strict: false });
```

I'm sure there's neater ways to do it with ES6 classes but the above is how you'd do it with ES5.

**Comment by pramod1792** [comment]
I am getting this same error [ MongoError: E11000 duplicate key error collection: bases Failed _id or unique key constraint ] while using mongoose(^5.0.11) with discriminators
