### ISSUE TITLE
Support question - populate on a file other than "_id"

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5408]
Hey all, simple support question here - I am wondering if we can use the "populate" feature with a field besides the _id field.

Say we have a model with fields like so:

```js
  userId: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },

  promptId: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'Prompt'
  },
```

we can populate like this:

```
    TheAboveModel.find({
        promptId: {
          $in: promptIds
        }
      }, {populate: ['userId', 'promptId']}, cb);

```

I am wondering if we had this, instead:

```js
  userId: {
    type: String,   // not an ObjectId
    required: true,
    ref: 'User',
  },

  promptId: {
    type: String,  // not an ObjectId
    required: true,
    ref: 'Prompt'
  },
```

If we could still somehow populate `TheAboveModel`.

The only way I could think of doing this, would be like so:

```js
  userId: {
    type: String,   // not an ObjectId
    required: true,
    ref: 'User.username',   // use dot notation to determine what field to use to join
  },

  promptId: {
    type: String,  // not an ObjectId
    required: true,
    ref: 'Prompt.designator' // use dot notation to determine what field to use to join
  },
```

would this be reasonable? It would be backwards compatible - if there is no dot present, it would default to the _id field.

**Comment by vkarpov15** [comment]
Use [virtual populate](http://mongoosejs.com/docs/populate.html#populate-virtuals) for this
