### ISSUE TITLE
Query.update() with timestamps enabled throws MongoError: '$set' is not valid for storage

### ISSUE THREAD

**Issue by hendrichbenjamin** [Automattic/mongoose#5413]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When I try to upsert a document with timestamps enabled, mongoDB throws the following error:
```
{ MongoError: The dollar ($) prefixed field '$set' in '$set' is not valid for storage.
    at Function.MongoError.create (/home/benjamin/development/test/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/benjamin/development/test/node_modules/mongodb/lib/utils.js:139:22)
    at /home/benjamin/development/test/node_modules/mongodb/lib/collection.js:1060:67
    at /home/benjamin/development/test/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'The dollar ($) prefixed field \'$set\' in \'$set\' is not valid for storage.',
  driver: true,
  index: 0,
  code: 52,
  errmsg: 'The dollar ($) prefixed field \'$set\' in \'$set\' is not valid for storage.' }
```
mongoose.set('debug', true) outputs the following when trying to run the below code:
```
Mongoose: testmodels.update({ _id: 'someFancyId' }, { updatedAt: new Date("Thu, 29 Jun 2017 07:28:54 GMT"), createdAt: new Date("Thu, 29 Jun 2017 07:28:54 GMT"), '$set': { data: 'aValue' } }, { overwrite: true, upsert: true })
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/mongoosetest');
const db = mongoose.connection;

db.once('open', () => {
	const schema = new mongoose.Schema({
		_id: { type: String, index: true, required: true },
		data: String
	}, {
		timestamps: true
	});

	const model = mongoose.model('testModel', schema);

	writeToDb('someFancyId', 'aValue')
		.then(console.log)
		.catch(console.error);

	function writeToDb(_id, data) {
		mongoose.set('debug', true);
		return model
			.where({_id})
			.setOptions({overwrite: true, upsert: true})
			.update({data})
			.exec();
	}
});
```

**What is the expected behavior?**
I would expect the update to be successful.
Either the timestamps should also be inside the $set operation or the data given in .update() should be outside of it.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v6.11.0
mongoose: v4.11.0
MongoDB: v3.0.15

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will fix asap

**Comment by vkarpov15** [comment]
Also, protip: please, please, please do **not** set `index: true` on `_id`. There is no harm in doing so currently, but it is completely unnecessary because MongoDB automatically creates an index on `_id` for every collection, and that index cannot be deleted or modified in any way. And if the `_id` index configuration changes in a future version of MongoDB, your model's index build will start failing.

**Comment by hendrichbenjamin** [comment]
Thank you for the fix and the tip about indexing, will keep that in mind.
