### ISSUE TITLE
hope type [String] support build-in validator enum

### ISSUE THREAD

**Issue by zwzw911** [Automattic/mongoose#5415]
request a feature

**What is the current behavior?**
if a path type is String, the build-in validator **enum** works.  
if a path type is Array, like [String], seems it not support **enum**.  In lib/schema/array.js, seems only **required** supported.    

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
hope [String] can also support build-in validator **enum**.    

**Please mention your node.js, mongoose and MongoDB version.**
mongoose@4.11.0  
node@7.9.0  
mongodb@3.2.10

**Comment by vkarpov15** [comment]
`arr: [{ type: String, enum: allowedValues }]`
