### ISSUE TITLE
Mongoose 4.11.0 error (node:11568)

### ISSUE THREAD

**Issue by Thinkdiff** [Automattic/mongoose#5417]
I've just updated Mongoose in my project to 4.11.0 and I got this error:
![sda](https://user-images.githubusercontent.com/7890134/27694548-9ccda094-5d01-11e7-8a17-1f8b10d59aa7.PNG)

Could you help me?

**Comment by itpcc** [comment]
Please see at #5399

**Comment by vkarpov15** [comment]
Not error, warning. See #5399 for discussion and http://mongoosejs.com/docs/connections.html#use-mongo-client for how to fix
