### ISSUE TITLE
$pull doesn't work with an array of embedded documents.

### ISSUE THREAD

**Issue by c4milo** [Automattic/mongoose#542]
I'm trying to delete an element from an internal array in a document. In mongo shell it works okay but not with mongoose. 

/**
- Embedded document
  */

var Foo = new Schema({
    foo_id : { type: String, required: true, set: toLower },
    user_id     : { type: String, required: true, set: toLower },
    foo_type        : { type: String, enum: ['type1', 'type2'], set: toLower}
});

/**
- Main document
  */

var Bar = new Schema({
    id          : { type: String, index: {unique: true}, set: toLower },
    name        : { type: String, index: true, required: true },
    user_id     : { type: String, index: true, required: true, set: toLower},
    description : { type: String},
    foos  : [ Foo ]
});

*This works in mongo shell: 
db.bars.update({id: '123'}, {$pull: {foos: { foo_id: '456', foo_type: 'type1'}}});

*with Mongoose I did the following but it didn't delete the element from the "foos" array:

BarModel.update({id: '123'},
{$pull: {foos: { foo_id: '456', foo_type: 'type1'}}}, 
function(error, data) {
        console.log(data); //returns 1
        console.log(error); //returns null
        callback(error, data);
});

**Comment by Al-Imran123** [comment]
Hi c4milo did you define foos array into your BarModel schema ?
