### ISSUE TITLE
insertMany() output non-well-formed iterable

### ISSUE THREAD

**Issue by erwin16** [Automattic/mongoose#5421]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
  cannot use ES6 for..of  !

**If the current behavior is a bug, please provide the steps to reproduce.**

```
  return Group.insertMany(multiGroups)
   .then((insertedGroups) => {
     const insertedGroupsIterable = insertedGroups => !!insertedGroups && typeof insertedGroups[Symbol.iterator] === 'function';
     console.log('insertedGroups is iterable ?', insertedGroupsIterable());
      return insertedGroups;
    });
    
  return Role.insertMany([roleA1, roleA2, roleA3, roleB2, roleB3, roleC3, role4 ])
    .then((insertedRoles) => {
      const insertedRolesIterable = insertedRoles => !!insertedRoles && typeof insertedRoles[Symbol.iterator] === 'function';
      console.log('insertedRoles is iterable ?', insertedRolesIterable());
      return insertedRoles;
    }); 
```

 **console.log**    
```
      insertedGroups is iterable ? false
      insertedRoles is iterable ? false
```

**What is the expected behavior?**

      insertedGroups is iterable ? true
      insertedRoles is iterable ? true

**Please mention your node.js, mongoose and MongoDB version.**
node.js  v7.4.0
mongoose. v4.9.3
mongoldb: 2.2.25

**Comment by vkarpov15** [comment]
I hate to say RTFM, but for the love of god [RTFM](http://www.ecma-international.org/ecma-262/6.0/#sec-iterator-interface) before you report such an insipid issue. For an iterable, the `Symbol.iterator` property is an **object** that has a `next()` function, **not** a function. As a side node, `insertMany()` resolves to a plain JavaScript array, which [is definitely an iterable](http://www.ecma-international.org/ecma-262/6.0/#sec-array-iterator-objects).
