### ISSUE TITLE
Allow validators to access values already in database

### ISSUE THREAD

**Issue by Nokel81** [Automattic/mongoose#5425]
**Do you want to request a *feature* or report a *bug*?**
Feature

Allow for validators (could be for only in the pre('validate') hook) to access values in the collection. This would allow for range uniqueness for dates.

Example:

```js
var dateRange = new Schema({
    start: {
        type: Date,
        required: true
    },
    end: {
        type: Date.
        required: true
});

dataRange.pre('validate', function(next, schema) {
    schema.find({})
        .exec((err, ranges) => {
            if (err) {
                this.invalidate('start', 'Internal error');
            } else {
                for (let i = 0; i < games.length; i++) {
                    let range = ranges[i];
                    if (range.start <= this.end) {
                        this.invalidate('end', 'Cannot overlap with an existing range');
                        return;
                    } else if (range.end >= this.start) {
                        this.invalidate('start', 'Cannot overlap with an existing range');
                        return;
                    }
                }
                next();
        });
});
```

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB v3.4.2
Mongoose v4.10.5
NodeJS v6.10.2

**Comment by vkarpov15** [comment]
I don't understand your feature request. You can already execute queries in the `pre('validate')` hook using `this.constructor.find()`

**Comment by Nokel81** [comment]
This is exactly what I was looking for. However I couldn't find information on this while looking at `pre('validate)` so more documentation would be nice
