### ISSUE TITLE
insertMany() - pre-save hooks not called

### ISSUE THREAD

**Issue by erwin16** [Automattic/mongoose#5428]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
saving multiple documents w insertMany([..,...]) don't call any pre-save hooks

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
pre-save hooks being called

**Please mention your node.js, mongoose and MongoDB version.**
node.js v7.4.0
mongoose v4.9.3
mongoldb v2.2.25

**Comment by vkarpov15** [comment]
`insertMany` !== `save`. If you want pre save hooks to be called, use `create()` instead.

**Comment by troywweber7** [comment]
@vkarpov15 The benefit of `insertMany` is that if anything is wrong with a single document, then none are added. Is that true of `create` as well? Or will a different approach be necessary to prevent partial document saves? Do you have a suggestion for this behavior?

**Comment by vkarpov15** [comment]
@troywweber7 sounds like you want to use a transaction: https://mongoosejs.com/docs/transactions.html

**Comment by troywweber7** [comment]
That is a nice feature to know about and just might do it. Thanks for the
tip.
