### ISSUE TITLE
Query#Populate: deep virtual populate not working

### ISSUE THREAD

**Issue by fredericosilva** [Automattic/mongoose#5431]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Document is not populated

**If the current behavior is a bug, please provide the steps to reproduce.**

```
'use strict';

const mongoose = require('.');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost/test');

const personSchema = new mongoose.Schema({
  name: String,
  band: String
});

const bandSchema = new mongoose.Schema({
    name: String
  , data: {
        field: String
    }
});
bandSchema.virtual('data.members', {
  ref: 'Person',
  localField: 'name',
  foreignField: 'band',
  justOne: false
});

bandSchema.set('toObject', { virtuals: true })

const Person = mongoose.model('Person', personSchema);
const Band = mongoose.model('Band', bandSchema);

Band.find({}).populate('data.members').exec(function(error, bands) {
    // Doesn't work, data.members is not populated
    console.log(error || bands)
    /*[{
        _id: 59594234430f451a6c97ce07,
        name: 'band1',
        __v: 0,
        data: { members: null },
        id: '59594234430f451a6c97ce07'
    }]*/

    bands.forEach(band => band.populate('data.members', err => {
        // works
        console.log(err || band)
        /*{
            _id: 59594234430f451a6c97ce07,
            name: 'band1',
            __v: 0,
            data: { members: [ [Object], [Object] ] },
            id: '59594234430f451a6c97ce07'
        }*/
    }));
});
```

**What is the expected behavior?**
Document should be populated

**Please mention your node.js, mongoose and MongoDB version.**
node 8.1.3
mongoose 4.11.0 and master fb3636d4
mongo 3.4.4

**Comment by hbthegreat** [comment]
I had this issue on one of my servers recently when I tried to update to a newer version. Didn't have much time to dig into it but rolled back to 4.8.4 as it is definitely working now.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix asap

**Comment by vkarpov15** [comment]
Below script works for me on 4.11.0 and 4.11.3. Please modify the below script to reproduce your issue

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost/test');

const personSchema = new mongoose.Schema({
  name: String,
  band: String
});
const bandSchema = new mongoose.Schema({
  name: String,
  data: {
    field: String
  }
});
bandSchema.virtual('data.members', {
  ref: 'Person',
  localField: 'name',
  foreignField: 'band',
  justOne: false
});

bandSchema.set('toObject', { virtuals: true });

const Person = mongoose.model('Person', personSchema);
const Band = mongoose.model('Band', bandSchema);

mongoose.connection.dropDatabase().
  then(() => Band.create({ name: 'Motley Crue', data: { field: 'test' } })).
  then(band => Person.create({ name: 'Vince Neil', band: 'Motley Crue' })).
  then(() => test());

function test() {
  Band.find({}).populate('data.members').exec(function(error, bands) {
    console.log(bands);
    console.log(bands[0].data.members);

    bands.forEach(band => band.populate('data.members', err => {
      console.log(band);
      console.log(band.data.members);
    }));
  });
}
```

**Comment by fredericosilva** [comment]
It fails if *data* is not set or set to an empty object.

```js
then(() => Band.create({ name: 'Motley Crue', data: { } }))
```

full teste case
```js
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost/test');

const personSchema = new mongoose.Schema({
  name: String,
  band: String
});
const bandSchema = new mongoose.Schema({
  name: String,
  data: {
    field: String
  }
});
bandSchema.virtual('data.members', {
  ref: 'Person',
  localField: 'name',
  foreignField: 'band',
  justOne: false
});

bandSchema.set('toObject', { virtuals: true });

const Person = mongoose.model('Person', personSchema);
const Band = mongoose.model('Band', bandSchema);

mongoose.connection.dropDatabase().
  then(() => Band.create({ name: 'Motley Crue', data: {} })).
  then(band => Person.create({ name: 'Vince Neil', band: 'Motley Crue' })).
  then(() => test());

function test() {
  Band.find({}).populate('data.members').exec(function(error, bands) {
    console.log(bands);
    console.log(bands[0].data.members);

    bands.forEach(band => band.populate('data.members', err => {
      console.log(band);
      console.log(band.data.members);
    }));
  });
}
```
Thanks

**Comment by varunjayaraman** [comment]
yup this looks like a bug, thanks for the repro script

**Comment by SAHEB24027824** [comment]
const mongoose=require('mongoose');

//Database Connect 
mongoose.connect('mongodb://localhost:27017/Company',{useNewUrlParser:true})
.then(()=>{
    console.log('DB connected')
}).catch((e)=>{
    console.log(e);
})




var Author=mongoose.model('author',{
    name:String,
    website:String,
    age:String
})

var Book=mongoose.model("book",{
    name:String,
    author:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Author'
    }
})


Book.find({}).populate('author').then((result)=>{
    console.log(result)
}).catch((e)=>{
    console.log(e);
})




======================================


{ MissingSchemaError: Schema hasn't been registered for model "Author".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at NativeConnection.Connection.model (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/connection.js:791:11)
    at getModelsMapForPopulate (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/model.js:4000:20)
    at populate (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/model.js:3502:21)
    at _populate (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/model.js:3472:5)
    at utils.promiseOrCallback.cb (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/model.js:3445:5)
    at Object.promiseOrCallback (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/utils.js:231:14)
    at Function.Model.populate (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/model.js:3444:16)
    at cb (/Users/sahebsutradhar/Desktop/final/node_modules/mongoose/lib/query.js:1659:17)
    at result (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/operations/cursor_ops.js:218:62)
    at handleCallback (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/cursor.js:887:14)
    at _endSession (/Users/sahebsutradhar/Desktop/final/node_modules/mongodb/lib/cursor.js:898:37)
  message: 'Schema hasn\'t been registered for model "Author".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }







could you please help  to resolve this issue

**Comment by lineus** [comment]
`ref: ‘Author’ ` should be `ref: ‘author’` It’s the value that you pass as
the first argument to mongoose model.

**Comment by SAHEB24027824** [comment]
thank you so much  for the solution lineus
