### ISSUE TITLE
Exception thrown in mongoose validator not caught in the .catch block of the promise.

### ISSUE THREAD

**Issue by perevorskyy** [Automattic/mongoose#5436]
I have an issue very similar to #3669 except the validator is custom and async. Reproduced on mongoose 4.7 and 4.11.1.

To sum up: There is a nested schema. The child schema has one async custom validator defined. This validator throws an exception. This exception is not caught by the .catch method of the promise chain.

Code snippet in this comment https://github.com/Automattic/mongoose/issues/3669#issuecomment-176304225 can be used to reproduce the problem (except the validator needs to be changed to an async one).

**Comment by varunjayaraman** [comment]
@perevorskyy the example you linked to is a bit different from custom async validators i think. I tried to reproduce, but the error does get handled:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.Promise = require('bluebird');
mongoose.connect('mongodb://localhost:27017/gh-5436', { useMongoClient: true });

var NestedSchema = new Schema({
  name: {
    type: String,
    trim: true,
    validate: {
      isAsync: true,
      validator: function() {
        throw new Error('error');
      }
    }
  }
});

var ContainerSchema = new Schema({
  name: {
    type: String,
    required: 'Name required',
    trim: true
  },
  items: [NestedSchema]
});

var Container = mongoose.model('test', ContainerSchema);

Container.create({
  name: 'name',
  items: [{
    name: null // Intentional Error
  }]
}).then(function() {
  console.log('Success');
}).catch(function(err) {
  console.error('Error', err);
}).finally(function() {
  mongoose.disconnect();
});
```

**Comment by heinhoang** [comment]
exactly like me. I even use createAsync from PromisifyAll from Bluebird but it's not working too.

**Comment by vkarpov15** [comment]
@heinhoang please provide a repro script. "This happens to me too" is not actionable when we can't reproduce the issue.
