### ISSUE TITLE
Behaviour change in the way hooks work

### ISSUE THREAD

**Issue by suprememoocow** [Automattic/mongoose#5438]
The following commit introduced a change in the way middleware hooks behave in Mongoose:
https://github.com/Automattic/mongoose/commit/6d83cd2a433119dc9b0552ec0fefe7a5585aa380

Although this change appears to be subtle, it means that I'll need to do some fairly major refactoring on a complex application in order to use `mongoose 4.8.0` are later.

First, the issue:

Before this commit, the following code would work "as expected"

```js
    var Schema = mongoose.Schema({
        displayName: { type: String }
    });

    var TestModel = mongoose.connection.model('Test1', Schema);

    Schema.pre('remove', function(next) {
      // Do something
      next();
    });
   
    var model = ... // Fetch a model
    model.remove()
      .then(function() {
        // Expect the middleware to have been called
      });
```

After the commit, the code above does not work as expected and the middleware does not get called unless the `pre` method is called *before* the model is instantiated.

Here is a mocha script that I used in `git bisect` to find the problem:

```js
describe('mongoose-test', function() {

  it('should save', function() {
    var mongoose = require('mongoose');

    var Schema = mongoose.Schema({
        displayName: { type: String }
    });

    mongoose.connect('mongodb://localhost/gitter');

    var TestModel = mongoose.connection.model('Test2', Schema);

    var p = new Promise(function(resolve) {
      Schema.pre('save', function(next) {
        resolve();
        next();
      });
    });

    return TestModel.create({ displayName: 'bob' })
      .then(function(d) {
        return p;
      })
  });

})

```

### Why not just setup the middleware callbacks before creating the models?

This is a contrived example. In the real application, the mongoose definitions occur in different modules to where the middlewares are attached. Adding the middlewares earlier would result in circular dependencies in the node `require` chain. It is possible to fix this, but requires a fair amount of refactoring. (The code in question is [Gitter](https://gitlab.com/gitlab-org/gitter/webapp/tree/master/modules/persistence/lib/schemas), which recently got open-sourced)

So, my questions are:

* Was this change intentional in Mongoose?
* If not, is this something that would be easy to fix inside Mongoose?
* Or do you think that the best course of action is to carry out the refactor?

Thanks, as always, for a fantastic library!

**Comment by vkarpov15** [comment]
Hi Andrew, sorry for the trouble but mongoose never formally supported modifying middleware after model compilation. It worked unintentionally between 4.0 and 4.8, but also added a lot of performance overhead. I'm happy to help out with any questions you have re: refactoring but this is unfortunately a change youre going to have to make on your end

**Comment by blyork** [comment]
Is there any plans for allowing models to be rebuilt after modifying a schema object?

**Comment by vkarpov15** [comment]
Not currently

**Comment by aletorrado** [comment]
Hi, is it safe now in v5 to do this? I'm stuck on 4.7 just because of this.

**Comment by vkarpov15** [comment]
@aletorrado no, mongoose 5 does not support modifying hooks after creating the model. The performance impact of allowing this is massive (orders of magnitude) for docs with lots of subdocuments. I hate using performance as a justification for less developer convenience, but in this case the performance gain is too significant to ignore.
