### ISSUE TITLE
Disallow setting indexes that involve `_id`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5439]

**Comment by KingDGrizzle** [comment]
So we won't be able to manually set `_id` for a specific value? (for instance a random number)

**Comment by vkarpov15** [comment]
Your documents can store whatever type of value you want in `_id`: numbers, strings, buffers, etc. This issue will not change that.

However, MongoDB currently [creates an index on `_id` by default for every collection](https://docs.mongodb.com/manual/core/index-single/) and disallows modifying it in any way. This causes problems when people think they need to put `unique: true` on `_id` in their schema.

**Comment by vkarpov15** [comment]
Going to close this in favor of #5820
