### ISSUE TITLE
Can't use $exist with ObjectId

### ISSUE THREAD

**Issue by muhammadfaizan** [Automattic/mongoose#5441]
`db.people.find({client: $exist : true})`
My query is giving error: _Can't use $exist with ObjectId_

client is an attribute referncing to Client Collection

Why is it happening, can you guys help.
Thanks !

**Comment by vkarpov15** [comment]
`$exists`, don't forget that last s.

**Comment by muhammadfaizan** [comment]
I feel stupid, but hey thanks :)

**Comment by vkarpov15** [comment]
No worries, typos happen :+1:
