### ISSUE TITLE
server/replset/mongos options are deprecated => documentation?

### ISSUE THREAD

**Issue by peterpeterparker** [Automattic/mongoose#5442]
**Do you want to request a *feature* or report a *bug*?**

Documentation enhancement

**What is the current behavior?**

Using Mongoose 4.11.1 I get following deprecation warning:

> the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,promoteLongs,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions]

**What is the expected behavior?**

Following the warning, I was searching the documentation about how to resolve this warning (http://mongoosejs.com/docs/connections.html#use-mongo-client) but didn't found anything about it aka anything about how I should migrate these options

**Please mention your node.js, mongoose and MongoDB version.**

Node.js v8.1.3
Mongoose 4.11.1
Mongodb v3.2.14

**Comment by serganus** [comment]
+1

**Comment by HadrienR** [comment]
+1

**Comment by flinn** [comment]
+1

**Comment by edgarmarkosov** [comment]
+1

**Comment by BeeeQueue** [comment]
The message says that all of the server, replset, and mongos options have been moved to the top level of the options object.

Simply move the settings from the `server`, `replset`, and `mongos` keys up into the top level of the object.


```javascript
mongoose.connect( 'mongodb://localhost/db',
  {
    useMongoClient: true,
    server: {
      poolSize: 2
    },
    promiseLibrary: global.Promise
  }
);
```

turns into

```javascript
mongoose.connect( 'mongodb://localhost/db',
  {
    useMongoClient: true,
    poolSize: 2,
    promiseLibrary: global.Promise
  }
);
```

**Comment by linsolas** [comment]
Hello,

Just for information, on my case I used an old version of `winston-mongodb` (v1), and got these warnings.
I upgraded to v2 (cf. https://github.com/winstonjs/winston-mongodb/issues/90), and the warnings are now gone.

**Comment by vkarpov15** [comment]
Will add more details to the docs about thjs

**Comment by sulhome** [comment]
I am still getting this warning message. Here is what I am doing

**options and connect**
```typescript
const options = {
    useMongoClient: true,
    server: { socketOptions: { keepAlive: 300000, connectTimeoutMS: 30000 } },
    replset: { socketOptions: { keepAlive: 300000, connectTimeoutMS: 30000 } }
};

mongoose.connect(<url>, options)
    .then(() => {
        logger.log('info', 'connected to mongodb');
    })
    .catch((error) => {
        logger.log('info', 'error connecting to db: ' + error);
    });
```

**warning message**
```bash
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,promoteLongs,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions]
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,promoteLongs,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions]
```

**Comment by tommarien** [comment]
@sulhome Just move it too main options object like this

``` js
const options = {
    useMongoClient: true,
    keepAlive: 300000, 
    connectTimeoutMS: 30000,
};
```

**Comment by sulhome** [comment]
@tommarien but there is `keepAlive` and `connectTimeoutMS` for `server` and for `replset` as well so when you put it on the top level which one are you setting the value for? `server` or `replset`?

**Comment by vkarpov15** [comment]
@sulhome both, as well as `mongos`.

**Comment by qworld** [comment]
just put all the options in top level, it works.

old format:
var options = {
  db: { native_parser: true },
  server: { poolSize: 5 }
}
mongoose.connect(uri, options);

new format (just one level):
var options = {
  native_parser: true,
  poolSize: 5,
}
mongoose.connect(uri, options);

**Comment by CuAnnan** [comment]
mongoose.connect(
	mongoString,
	{
		useMongoClient:true,
		db:mongoConf.db
	}
);

Happening here too.

**Comment by highsea** [comment]
原来是将 **options** 对象配置 提升到了顶级

**Comment by azachar** [comment]
Hi there, 
Could any one suggest, what to use instead of 
```js
options: {
    db : {
        safe: true
    }
}
```

This code can be located from https://github.com/angular-fullstack/generator-angular-fullstack/blob/ab8624002cd90aac100dbb6cc263d92f7f599588/templates/app/server/config/environment/index.js#L43 which still use mongoose before 4.12, I want to upgrade it, but cannot find any  relevant migration info for this.

Thanks for any advices!

Cheers,
Andrej

**Comment by vkarpov15** [comment]
@azachar here's some docs: http://mongoosejs.com/docs/connections.html#use-mongo-client . However, using `safe` is no longer necessary because [the mongodb driver uses acknowledged writes by default now](https://docs.mongodb.com/manual/release-notes/drivers-write-concern/), `safe` was a 2011-2012 construct to turn on acknowledged writes and journaling in one command, but it is now an anachronism. I would recommend just removing it entirely.

**Comment by azachar** [comment]
Thank you very much for your response!

**Comment by skarface** [comment]
Same to me, I don't know the equivalent for db:safe option.

**Comment by karnavkumar** [comment]
+1
