### ISSUE TITLE
Pre-save middleware cannot be called

### ISSUE THREAD

**Issue by jiujieti** [Automattic/mongoose#5444]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Please check the gist below:
https://gist.github.com/jiujieti/0830446aad84a9e887b17a3fce447927

**If the current behavior is a bug, please provide the steps to reproduce.**
Please check the gist and it could be run by ```node test.js``` (For the db URI you could replace it with your own db)

**What is the expected behavior?**
Pre-saved middleware should be called and the password of the current user ```jiujieti``` should be added with the string "hello". But I checked the saved password, it is still the original password set by user. Also ```console.log``` inside of the pre-save hook does not output anything.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v6.9.4
mongoose: v4.10.3
MongoDB: v3.2.14

I am new to Mongoose so I am not sure the unexpected behaviour is due to my code or there is a bug in Mongoose. Any help will be appreciated, thanks a lot!

**Comment by jiujieti** [comment]
I update the gist with a runnable minimal example. Hope now it is more clear.

**Comment by vkarpov15** [comment]
You need to add middleware before calling `mongoose.model()`, not after

**Comment by patters** [comment]
@vkarpov15 it would be great if this was documented somewhere. Migrating a project from 3.x to 4.x and it appears that this is a new requirement.

**Comment by vkarpov15** [comment]
@patters it is documented [here](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#query-middleware), the 2nd item on the migration guide. Where did you look for info on how to migrate?

**Comment by patters** [comment]
Didn't know that existed, thanks! 🤷‍♂️ (It'd be great to link to that from the README.) 

For what it's worth, I threw together [something](https://gist.github.com/patters/8345bb294cc3d1aba0fb400f07093dcc) that allows hooks to be added after models are created, by storing "new" middleware in another object and registering one hook before the model is created to call the new middleware.
