### ISSUE TITLE
Validate method on Schema instances

### ISSUE THREAD

**Issue by radixo** [Automattic/mongoose#5445]
Why not to have validate method on the schema instance, passing an object, or a document to be validated?

I need to use the same model with distinct validations. How to do so?

Reading the sources I saw a way to create a model with the sambe name passing an Object with a property "cache": false to the skipInit param. It is a workaround for my problem, but I think it would be better to have a validate method in Schemas instances.

What do you think?

**Comment by vkarpov15** [comment]
Not really possible with how mongoose is currently structured. Validation is mostly done by individual schema paths, it is tied very closely to mongoose docs and change tracking, and changing that while keeping the same api would be extremely tricky.

If you want to validate pojos independent of mongoose models you should check out archetype: https://www.npmjs.com/package/archetype-js . similar syntax, but a lighter lib gives you more flexibility.

Can you clarify what you mean by same model with distinct validations?

**Comment by varunjayaraman** [comment]
@radixo any update on this?

**Comment by varunjayaraman** [comment]
@radixo without any further information, i'll need to close this as stale soon
