### ISSUE TITLE
.slice() on an array causes "select: false" properties to be returned.

### ISSUE THREAD

**Issue by JacobReynolds** [Automattic/mongoose#5450]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When calling .slice({'subArray':[number]}) on a request, the subarray is sliced properly, but the result returns properties that have "select: false" set.  Subarray meaning a property of a schema that is an array.  Example below.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/JacobReynolds/f2284c4142ebdf7dc101bce0778350a4

**What is the expected behavior?**
The subarray will be sliced and "select:false" properties will not be returned.

**Please mention your node.js, mongoose and MongoDB version.**
#### Mongoose
```
> var mongoose = require('mongoose')
undefined
> mongoose.version
'4.11.1'
```
#### MongoDB
```
C:\>"C:\Program Files\MongoDB\Server\3.4\bin\mongod.exe" --version
db version v3.4.6
git version: c55eb86ef46ee7aede3b1e2a5d184a7df4bfb5b5
allocator: tcmalloc
modules: none
build environment:
    distmod: 2008plus
    distarch: x86_64
    target_arch: x86_64
```
#### Node
```
C:\>node --version
v6.10.3
```

**Comment by vkarpov15** [comment]
Thanks for the detailed repro instructions. Were behind on bug reports right now but will get to this one asap.

**Comment by newsiberian** [comment]
Hi, @vkarpov15, seems this where is still an issue with `$slice` and `select`.
i.e.
```js
const TestSchema = ({
  ...
  array1: [string],
  ...
});
```

if we are make request like:
```js
Test.find(_id: 3).slice('array1', [0, 5]).then() <-- result as expected
```
but if we modify it to:
```js
Test.find(_id: 3)
  .slice('array1', [0, 5]) <-- this is ignored
  .select({ 'array1': 1 })
  .then()
```
the result ignores `slice()`.

**Comment by vkarpov15** [comment]
@newsiberian to me this sounds like expected behavior to me. [`slice` is a projection](https://docs.mongodb.com/manual/reference/operator/projection/slice/), `.slice('array1', [0, 5])` is equivalent to `.select({ array1: { $slice: [0, 5] } })`, so putting `select({ array1: 1 })` afterward overwrites the `slice` projection.
