### ISSUE TITLE
Strange error on "new Error()" in model applyHooks

### ISSUE THREAD

**Issue by SBRK** [Automattic/mongoose#5451]
I'm having yet another strange error linked to Error handling, a little bit like #5366 

Using mongoose 4.11.0, when calling `save` on a document, I get an Error at `lib/services/model/applyHooks` line 111, which only does a `new Error()`
https://github.com/Automattic/mongoose/blob/4.11.0/lib/services/model/applyHooks.js#L111

I have only the stacktrace, no error message, no nothing. Again, I've seen the error only in production and I'm unable to reproduce in local.

Any idea on what could be going on ?

**Comment by vkarpov15** [comment]
No ideas. Can you provide a more thorough code sample?

**Comment by SBRK** [comment]
I wish I could but unfortunately it seems environment related so I can't even reproduce in local :(

**Comment by vkarpov15** [comment]
Weird. Feel free to re-open this issue if you can reproduce it.

**Comment by astevelinocermati** [comment]
i thought i was the only one who got this error haha
