### ISSUE TITLE
find some docs by $or and $ lte，the result is null

### ISSUE THREAD

**Issue by tong3jie** [Automattic/mongoose#5452]
the result is true at  mongobooster

> `orderModel.find({
            "$or": [{
                "returncode": {
                    $exists: false
                },
                "amount": {
                    $exists: false
                },
                "reprice": {
                    $exists: false
                },
                "streamingNO": {
                    $exists: false
                }
            }, {
                "reason": "2",
                "returncode": "8"
            }, {
                "reason": "3",
                "returncode": "8"
            }],
            "reqTime.reqTimes": {
                "$gte":0,
                "$lte": 200
            }
        }, null,
         {
            sort: {
                'reqTime.reqTimes': 1,
                'reqTime.reqTimestamp': 1
            }
        }
        )`

**Comment by varunjayaraman** [comment]
This isn't really a repro script or actionable. What exactly is your bug and do you have a repro script?

**Comment by varunjayaraman** [comment]
without a repro script or a better idea of what your bug is, I'm going to need to close this issue soon
