### ISSUE TITLE
MongoError: no primary found in replicaset

### ISSUE THREAD

**Issue by allanchau** [Automattic/mongoose#5456]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Connections using `mongoose.connect()` work but `mongoose.createConnection()` breaks.

Compose uses a failover server and the native mongo driver incorrectly assumes this is a replicaset. The connection fails with the error `MongoError: no primary found in replicaset`.
https://www.compose.com/articles/connecting-to-the-new-mongodb-at-compose/

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Connect to a compose.com db  using the `createConnection()` method.
`mongodb://<user>:<password>@aws-us-east-1-portal.7.dblayer.com:10764,aws-us-east-1-portal.10.dblayer.com:10361/examples?ssl=true  `

**What is the expected behavior?**
The `createConnection` string should ignore the failover database like `mongoose.connect()`. At least thats what I think it does anyway.

**Please mention your node.js, mongoose and MongoDB version.**
node: v6.10.1
mongoose: 4.11.1
MongoDB 3.2.11

**Comment by vkarpov15** [comment]
Are you using useMongoClient ? Can you show a code sample of what your connection logic looks like?

**Comment by allanchau** [comment]
The connection is being created using something like this:

```javascript
const connect = (connections) => new Promise((resolve, reject) => {

    require('./certs')
      .then(loadedCerts => Promise.all(connections.map(({ options, uri }) => {

          const defaults = { useMongoClient: true };

          if (loadedCerts.length && options.ssl && options.sslValidate) {

              defaults.ssl = true;
              defaults.sslCA = loadedCerts;
              defaults.sslValidate = true;

          }

          debug(`Connecting to database: ${uri} ${loadedCerts.length > 0 ? 'with' : 'without'} SSL`);

          return mongoose.connect(uri, Object.assign({}, defaults, options));

      })))
      .then(resolve)
      .catch(reject);

});
```

**Comment by vkarpov15** [comment]
Try upgrading to mongoose 4.11.3? Also, compose recommends [you only list one mongos in your connection string](https://www.compose.com/articles/connecting-to-the-new-mongodb-at-compose/#drivingtoyourfirstdatabase), please try using that.

**Comment by varunjayaraman** [comment]
@allanchau have you tried @vkarpov15 's solution?

**Comment by allanchau** [comment]
Hey sorry guys, been super busy.

Upgrading mongoose doesn't work but using a single connection string does.

This doesn't really fix the issue though because `mongoose.connect` still works with the 2 mongos.

**Comment by vkarpov15** [comment]
I'm going to call this a non-issue, it only happens if you explicitly go against compose's best practices so I don't think we can support this behavior without help from compose.

**Comment by joeauty** [comment]
Compose does not recommend a single node, Compose says that you might have to go with a single node if the drivers are not up to the job:

https://www.compose.com/articles/a-rough-guide-to-composing/

```
If you have less modern drivers or applications then they may only use a single hostname, a port and a database name because they don't know about replica sets. You can extract that information from the Replica Set URI or you can look down to the Mongo Console command beneath it. It uses a simplified address for the database because it can only talk to a single server at a time. Here you can see the hostname, a colon, the port number and the database name. This will allow you to connect but you should be thinking about updating your drivers so you can work with the Compose MongoDB replica set. Once you've done that your application will be resilient to any configuration changes.
```

That being said, I'm able to connect to a comma separated Compose replica set using both `Mongoose.connect` and `Mongoose.createConnection` with Mongoose 4.13.0, so perhaps this problem has since been resolved.
