### ISSUE TITLE
Searching/filterning is not working for date and time type feilds 

### ISSUE THREAD

**Issue by AnitaMehta** [Automattic/mongoose#5457]
I am using node version v6.10 and mongoose v4.9.5.
Trying to do filter(column based and whole document), for type number and date, it is not working and getting the error.
Here is my code for schema:
{
        technologyCode: { type: Number, required: true, unique: true},
        technologyName: { type: String, required: true },
        description: String,
        active: Boolean,
        customerUnit :{ type :[String], required : true}, 
        createdDate: { type: Date},
        lastUpdatedDate: { type: Date}
    }

 query = {'$or':[
                {technologyCode: new RegExp(searchText,'i')},
                {technologyName: new RegExp(searchText,'i')},
                {description: new RegExp(searchText,'i')},
                {customerUnit: new RegExp(searchText,'i')}
            ]
         };

 technology.paginate(query, queryParams, function(err, result) {
        if (err){
            return response(res, 500);
        }else{         
            return response(res, 200, result);
        }
    });

Please let me know is it possible to do in mongoose.

**Comment by vkarpov15** [comment]
Please define "not working" and "getting the error", I don't understand the question

**Comment by varunjayaraman** [comment]
@AnitaMehta do you have any more info on what exactly you mean by this?

**Comment by varunjayaraman** [comment]
@AnitaMehta I'll need to close this as stale soon without further information on what you mean
