### ISSUE TITLE
Urgh!  const results = Model.find({}).exec()

### ISSUE THREAD

**Issue by smooJitter** [Automattic/mongoose#5459]
For the life of me, I do not understand why the documentation does not address this simple use case.  

`const results = Model.find({}).exec()`

I mean who cares about spitting out a console log e.g,

```
const results Model.find({})..exec(function(err,jedis){
   if(err)
      return console.log(err);
   jedis.forEach(function(jedi){
      console.log(jedi.name);
   });
});
```
I've looked for ways to address simple task in a  straight forward way.  This tasks looks to be a FAQ, nevertheless finding an answer is enough to turn beginners away.  I have spent at least 20 hours of productivity (over 4 - 6 months) trying to figure out the many some what convoluted solution approaches.  The solution above works fine; it prints a list of results to the console, but it does not  assign the outcomes to an array of results. 

I feel silly posting the question here. Frankly, considering this is such a popular task, I do not understand why the docs are void of a practical example or returning an array of records from a mongoose query; consol.log(..) only frustrates the matter.  As a beginner, I assume a basic query will lead to a cursor of results. Looping over the results and printing them to the console only confirms the expected behavior.  I apologize for the rant but this simple task is driving me nuts.

**Comment by hendrichbenjamin** [comment]
```javascript
const results = Model.find({}).exec()
```
will lead you to results being a Promise.

What you want is basically already what you did.
You already console.log the data you want. You just have to work with it now.
As finding data from the Database is asynchronous, you either have to work inside your callback, like you did, use [the Promise](http://mongoosejs.com/docs/promises.html) from your first example
```javascript   
const resultPromise = Model.find({}).exec();

resultPromise.then(function (jedis) {
     // do whatever you want with your jedis
});

// or directly chained
Model.find({}).exec()
    .then(function (jedis) {
       // here are your jedis again
   })
```
or use something that allows you to write asynchronous code more synchronous like [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) (requires node v8 or [transpiler](https://babeljs.io/)) or [generators](https://eladnava.com/write-synchronous-node-js-code-with-es6-generators/)

If you insist on retrieving a cursor, you have to [specifically request one.](http://mongoosejs.com/docs/api.html#query_Query-cursor)

**Comment by smooJitter** [comment]
You are right, I did not ask a specific question. I apologize for the rant.  While you provide the most candid demonstration I've seen so far, you confirm the query results a trapped.  Here's my setup

```
function mockItems(){
    return  Items.find({}).exec()
}
const fakeAccout = {
     userID: 'fhydrke',
      items: mockItems(),
   }

export default funtion doSomethingWith(user){
    return Object.assign({}, fakeAccount, user);
},
```
I'd like a way to extract the list of items into an array of objects.

It appears you are suggesting I do something like this,

```
function mockItems(){
    Items.find({}).exec()
       .then((items) => {
            const list = items.map(item => item);
            const fakeAccout = {
               userID: 'fhydrke',
               items: list ,
             }
       )
}
```
Now fakeAccount is trapped in a promise.

**Comment by hendrichbenjamin** [comment]
As soon as you have one single asynchronous call, you are indeed trapped inside asynchronous handling. You cannot revert the asynchronousity, but you don't really need to. You can just as well work with it.

Or, if you prefer to write your code without callbacks, you would need to use either es7 async/await, as mentioned earlier, or generators. These techniques merely mask the asynchronous work though.

I don't understand what you are trying to do with the mapping. That currently does nothing for you.
But yes, fakeAccount does now have the list as items.
Better would be:
```
function mockItems(){
  return Items.find({}).exec()
    .then(items => {
      const fakeAccout = {
        userID: 'fhydrke',
        items
      };

      // do something with faceAccount
      // or return it out of this promise
      return faceAccount;
    );
}

// and use it after calling mockItems
mockItems()
  .then(faceAccount => {
    // like so.
  });
```

**Comment by varunjayaraman** [comment]
sorry im confused by whats pissing you off. Do you want a cursor? If so you can just do:

`Model.find().cursor()` and then asynchronously loop through the cursor with `await cursor.next()`

Otherwise, mongoose will give you back a promise that resolves with an array of the documents you want

**Comment by vkarpov15** [comment]
It definitely takes a while to wrap your head around async code. We do the best we can with the docs but there's only so much we can do. I'm going to close this unless there's something actionable here
