### ISSUE TITLE
Can't use mongoose .populate on secondary in replica set

### ISSUE THREAD

**Issue by Niicck** [Automattic/mongoose#5460]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm attempting to run a .populate query on a secondary member of my replica set. This query works fine off the primary. And I can do others queries off the secondary member by specifying  .read('secondary'). Only .populate behaves differently and throws "MongoError: not master and slaveOk=false".

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduce by running a .populate command on a secondary member of a replica set.

**What is the expected behavior?**
Running a populate query off a secondary member should give the same result as a populate query running off a primary member.

**Please mention your node.js, mongoose and MongoDB version.**
node.js v6.11.0
mongoose v4.11.1
mongodb v3.4.1

**Comment by vkarpov15** [comment]
Please provide code samples, prose descriptions of code do not qualify

**Comment by Niicck** [comment]
A populate query like this works fine when connected to a primary member of a replica set:
```
Model.findOne().populate('drivers vehicles').lean()
```
But when I'm connected to a secondary member this same query will fail:
```
Model.findOne().populate('drivers vehicles').read('secondary').lean()
```
If I take out the populate step, my reads from the secondary member all succeed. So I can rule out the connection itself being the issue:
```
Model.findOne().read('secondary').lean()
```
Does that make sense?

**Comment by vkarpov15** [comment]
I think I see what the issue is, I believe it's because the `read()` isn't propagating down to the queries that `populate()` uses. As a workaround, try this:

```javascript
Model.findOne().populate({ path: 'drivers', options: { readPreference: 'secondary' } }).read('secondary').lean()
```

**Comment by Niicck** [comment]
Yes, thank you that solved it! The readPreference option is also required on the populate query.
