### ISSUE TITLE
Resurrect from post save error middleware

### ISSUE THREAD

**Issue by porsager** [Automattic/mongoose#5464]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Once post save error middleware is reached it's not possible to return to the success path

**What is the expected behavior?**
A way to return from post save error middleware to resolve the initial promise

**Use case**
For instance handle a duplicate error (11000) by creating a new identifier which isn't a duplicate and resave the document returning the new save promise to the initial save call.

**Please mention your node.js, mongoose and MongoDB version.**
node 8.1.4, mongoose 4.11.1, mongo 3.4.6

**Comment by vkarpov15** [comment]
Thanks for the suggestion, we'll add this feature in a future release.
