### ISSUE TITLE
populate throws exception: limit value must be non-negative

### ISSUE THREAD

**Issue by mozi** [Automattic/mongoose#5468]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
*exception thrown*

**If the current behavior is a bug, please provide the steps to reproduce.**

> can't share exact code; pseudo code below to explain the situation causing the bug
> example populating the pre/next related docs with doc._id being a number
```
TestSchema = new mongoose.Schema({
	_id: Number,
	prevnxt: { type: [Number], ref: 'test' }
});

model = mongoose.model('test', TestSchema, 'TestCollection');
model._populate = model.populate
model.populate = (doc, options, callback)=>
	doc.prevnext = [doc._id+1, doc._id-1];
	options.filter((pop)-> pop.path is 'prevnext').forEach((opt)=> opt.limit = 2);
	model._populate doc, options, callback
```

**What is the expected behavior?**
populate to complete without exceptions with all array elements populated

**Please mention your node.js, mongoose and MongoDB version.**
nodejs 6.9.4, mongodb 3.2.x, mongoose 4.9.10

here is the options shown in the debug when streaming a large set of data whilst populating on the fly
`{ limit: 9223372036854776000, fields: {} }`

commenting out the following line in lib\model.js (line 3039) solves the issue
`mod.options.options.limit = mod.options.options.limit * ids.length;`

[related to 1251 as per this comment](https://github.com/Automattic/mongoose/issues/2151#issuecomment-305006030)

**Comment by varunjayaraman** [comment]
first off, why are you overwriting the `Model.populate()` method on Models? Cant you just write a model static that can call `.populate()` from the static?

**Comment by varunjayaraman** [comment]
Furthermore, can you please try to at least create a repro script with actual code that resembles your issue in the code you can't use here?

**Comment by mozi** [comment]
the reason behind overriding the populate, is because so far there is no way to populate a virtual property on the fly, in the example above **prevnext** property isn't a property of the underlying document, ideally would have been a virtual property with a getter but that doesn't get called pre populate hence the hack around the populate.

coming from mongoose 4.4.x up to the latest 4.11.x, and now with the virtual populate feature, it comes handy only when the **localField** exists in the underlying document, which works around the crank up of limit bug explained above.

so far couldn't find a way to use virtual populate to do left outer join based on a virtual foreign key that gets generated at runtime. 

happy to be corrected, and i will try to attach a full repro script shortly.

**Comment by vkarpov15** [comment]
Confirmed, here's a repro:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5468`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true })

    yield mongoose.connection.dropDatabase();

    const refSchema = new mongoose.Schema({
      _id: Number,
      name: String
    });
    const Ref = mongoose.model('Ref', refSchema);

    const testSchema = new mongoose.Schema({
      _id: Number,
      prevnxt: { type: [Number], ref: 'Ref' }
    });
    const Test = mongoose.model('Test', testSchema);

    for (let i = 0; i < 1000; ++i) {
      yield Ref.create([{ _id: 3 * i }, { _id: 3 * i + 1 }, { _id: 3 * i + 2 }]);
      yield Test.create({ _id: i, prevnxt: [3 * i, 3 * i + 1, 3 * i + 2] });
    }

    const cursor = Test.find().populate({ path: 'prevnxt', options: { limit: 2 } }).cursor();
    yield new Promise((resolve, reject) => {
      cursor.on('data', doc => console.log(doc));
      cursor.on('error', err => reject(err));
      cursor.on('end', () => resolve());
    });
    console.log('done');
    process.exit(0);
  });
```

**Comment by RezaErfani67** [comment]
this error has been occurred  in version 6

**Comment by vkarpov15** [comment]
@RezaErfani67 please open a new issue and follow the issue template
