### ISSUE TITLE
Embedded objects have properties that they shouldn't have; stability of properties/own properties in API

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#5470]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

Embedded objects have own properties from the object in which they're embedded. That is, this test fails (using the `EmployeeSchema` from the mongoose test suite):

```js
    it("own properties don't include parent properties", function () {
      var employee = new Employee({
        name: {
          first: "Firstname",
          last: "Lastname"
        },
        department: "Parks and recreation"
      });
      var nameOwnProperties = Object.getOwnPropertyNames(employee.name);
      assert(!nameOwnProperties.includes("department"));
    });
```

`employee.name.department` is the value `undefined` -- like if you do:
`x = {a: undefined}`
then:
`x.a === undefined // true`
`"a" in x // true`

The full contents of `nameOwnProperties` are:

```
[ '$__',        
  'isNew',      
  'errors',     
  '_doc',       
  'department', 
  '_id',        
  'id',         
  'name',       
  'gender',     
  '__v',        
  '__t',        
  'toObject',   
  'toJSON',     
  '$__isNested',
  'full',       
  'last',       
  'first' ]     
```

I'm not sure why `department`, `name`, `gender`, `_id`, `id`, `__t` or `__v` are present on `employee.name`, when they should presumably only be on `employee`.

This is vaguely similar to #4603. Even if the above is intended behavior, it would be nice if the own properties and the prototype properties were considered part of the stable and locked API. We've made a number of assumptions about these properties and they have periodically proven to be false. :(

**Please mention your node.js, mongoose and MongoDB version.**

Node 6, mongoose master branch (4f2c023), mongodb 3.x

**Comment by vkarpov15** [comment]
If you ever need to iterate over properties, you should just use `.toObject()` before. We'll investigate and see if we can change this

**Comment by vkarpov15** [comment]
I'm going to need to push this one back, it's proving very tricky. The fundamental issue is that `employee.name` has the same prototype as `employee`, which means it has to have all the top-level keys that `employee` does, and changing this is proving to be quite difficult. As a workaround, use `Object.keys()` or filter out non-enumerable props, or just use `toObject()`.

**Comment by zbjornson** [comment]
No problem, it's nothing urgent, and thanks for the update.

Thanks for all your hard work!

**Comment by vkarpov15** [comment]
I put in a PR above. Surprisingly subtle and that PR may have some unintended consequences, so we won't put it out in a patch release. We'll sit on it for a bit until we release 4.12.
