### ISSUE TITLE
Authenticating while connecting to multiple database using mongoose

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [Automattic/mongoose#5474]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have set up auth in my MongoDB as mentioned [here](https://docs.mongodb.com/manual/tutorial/enable-authentication/). Initially, in my project I was accessing a single database say, `firstdb` from mongoose using

    let url = "mongodb://localhost:27017/firstdb";
    let options = {
        server:{
            socketOptions:{
                keepAlive:120
            }
        },
        user:"username1",
        pass:"mypassword1"
    };
    mongoose.connect(url,options,callback);

The user with `username` and `mypassword` was created in the `firstdb` itself giving it `readWrite` perms. I did this while logged in with my admin user.

Things were working smoothly. Then I had a requirement of connecting to a second database. So I changed my code as such

    let url1 = "mongodb://localhost:27017/firstdb";
    let options1 = {
        server:{
            socketOptions:{
                keepAlive:120
            }
        },
        user:"username1",
        pass:"mypassword1",
        auth:{
            authdb:"firstdb"
        }
    };
    let connection1 = mongoose.createConnection(url1,options1);

    let url2 = "mongodb://localhost:27017/seconddb";
    let options2 = {
        server:{
            socketOptions:{
                keepAlive:120
            }
        },
        user:"username2",
        pass:"mypassword2",
        auth:{
            authdb:"seconddb"
        }
    };
    let connection2 = mongoose.createConnection(url2,options2);

This time I created user `username2` the same way in the `seconddb` database. But now mongoose is unable to perform any operation and is failing with `Not authorized to execute command`. I can access the db through mongo shell though. I also spun up the code in my local system which doesn't have mongodb auth enabled and it works fine there. Please help
**What is the expected behavior?**
The queries should work as expected

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS : 8.1.0
mongoose : 4.10.4
MongoDB : 3.2

**Comment by vkarpov15** [comment]
How are you creating your models?

**Comment by SayakMukhopadhyay** [comment]
I am exporting the connections using `module.exports.conn1 = connection1`. I am also exporting the mongoose instance using `module.exports.mongoose = mongoose`. Then I am using them in my model file as such
```
module.exports = new Promise((resolve, reject) => {
    let db = require('../db');
    let connection = db.conn1;
    let mongoose = db.mongoose;
    let Schema = mongoose.Schema;

    let body = new Schema({
        id: { type: Number, unique: true },
        created_at: Date,
        updated_at: Date,
        name: String
    }, { runSettersOnQuery: true });

    let model = connection.model('body', body);

    resolve(model);
})
```

**Comment by vkarpov15** [comment]
How are you creating your users? I started a fresh mongod with `mongod --nojournal --noprealloc --ipv6 --auth` and ran:

```
$ mongo admin
MongoDB shell version v3.4.1
connecting to: mongodb://127.0.0.1:27017/admin
MongoDB server version: 3.2.10
WARNING: shell and server versions do not match
> db.createUser(
...   {
...     user: "myUserAdmin",
...     pwd: "abc123",
...     roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
...   }
... )
Successfully added user: {
	"user" : "myUserAdmin",
	"roles" : [
		{
			"role" : "userAdminAnyDatabase",
			"db" : "admin"
		}
	]
}
> db.auth('myUserAdmin', 'abc123')
1
> use firstdb
switched to db firstdb
> db.createUser({ user: 'firstdbuser', pwd: 'abc123', roles: [{ role: 'readWrite', db: 'firstdb' }] })
Successfully added user: {
	"user" : "firstdbuser",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "firstdb"
		}
	]
}
> use seconddb
switched to db seconddb
> db.createUser({ user: 'seconddbuser', pwd: 'abc123', roles: [{ role: 'readWrite', db: 'seconddb' }] })
Successfully added user: {
	"user" : "seconddbuser",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "seconddb"
		}
	]
}
> 
```

Below script works as expected, prints `done()` and exits.

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

let url1 = "mongodb://localhost:27017/firstdb";
let options1 = {
    server:{
        socketOptions:{
            keepAlive:120
        }
    },
    user:"firstdbuser",
    pass:"abc123",
    auth:{
        authdb:"firstdb"
    }
};
let connection1 = mongoose.createConnection(url1,options1);

let url2 = "mongodb://localhost:27017/seconddb";
let options2 = {
    server:{
        socketOptions:{
            keepAlive:120
        }
    },
    user:"seconddbuser",
    pass:"abc123",
    auth:{
        authdb:"seconddb"
    }
};
let connection2 = mongoose.createConnection(url2,options2);

Promise.all([run(connection1), run(connection2)]).then(() => {
  console.log('done');
  process.exit(0);
});

async function run(connection) {
  let body = new Schema({
    id: { type: Number, unique: true },
    created_at: Date,
    updated_at: Date,
    name: String
  }, { runSettersOnQuery: true });

  let model = connection.model('body', body);

  await model.create({ id: 1 });
}
```

Please modify the above script to reproduce your issue.

**Comment by SayakMukhopadhyay** [comment]
I am yet to check the above reproduction steps but I recently have managed a workaround. If I put my username and password in the connection url itself, things work fine. I will revert back after I go through the above steps.
