### ISSUE TITLE
Abandon queries when there are too many requests at the same time.

### ISSUE THREAD

**Issue by boylove142** [Automattic/mongoose#5478]
When I do a 340+ find queries at the same time using `Promise.map` (from bluebirdjs), the operation just hangs halfway. There was no error, it just stopped processing somewhere between operation 300th.

Later, I found out that the problem was due to the number of `poolSize` setting when initializing mongodb connection. I changed from 5 to 100 and the hang disappeared.

The problem is what if later on, the number of queries running at the same time increase and I forgot to increase the `poolSize`. Would my application just hang somewhere in the code.

**Comment by vkarpov15** [comment]
Depends on how slow the queries are. MongoDB only lets you do one operation per connection in the pool at a time, so if you execute 300 operations in parallel MongoDB will only execute them 5 at a time or 100 at a time depending on `poolSize`. If you have a lot of queries executing at once, they might get backed up.
