### ISSUE TITLE
.id returns string while ._id returns object. is this a bug?

### ISSUE THREAD

**Issue by adamz123** [Automattic/mongoose#548]
In the following function, test1 is a string because the virtual path runs through a different codeset and runs the toString() function, whereas test2 is an object with the 'id' set to the hex id.  The console.log will produce the same result since console.log will call the .toString function in the object.  However, I was under the impression .id and ._id were supposed to be the same thing.  Which one am I supposed to be using or is this a bug?

function createSegment(options, callback){
    var location = options.location;
    var newSegment = new Segment({coordinates: new Array(location)});
    newSegment.save(function(err){
        if(err) {callback(err); return;}
        debugger;
        var test1 = newSegment.id;
        var test2 = newSegment._id;
        console.log(newSegment.id);
        console.log(newSegment._id);
        callback(null, newSegment.id);
    });
}

**Comment by technotronic12** [comment]
@aheckmann I am also using my own id (a string guid) as well as _id. recently I started receiving this error: Named property 'id' of types 'IMaintenance' and 'Document' are not identical. Any idea what might cause it?
