### ISSUE TITLE
Mongoose subdocuments with rangeerror: maximum call stack size

### ISSUE THREAD

**Issue by robsonc** [Automattic/mongoose#5480]
I use mongoose in renderer process of a electron application and after update to the version 4.8.0 or later, mongoose launch this error when I try to save a document with new subdocuments.

Until version 4.7.9 works normally. But the error only occurs in the renderer process of the electron, in the main process it runs normally.

I've tried everything and nothing.

```
RangeError: Maximum call stack size exceeded
at canAttachTrace (C:\ElectronApps\TodoList\node_modules\bluebird\js\release\util.js:246:32)
at Object.ensureErrorObject (C:\ElectronApps\TodoList\node_modules\bluebird\js\release\util.js:258:17)
at Promise._rejectCallback (C:\ElectronApps\TodoList\node_modules\bluebird\js\release\promise.js:466:22)
at Promise._resolveFromExecutor (C:\ElectronApps\TodoList\node_modules\bluebird\js\release\promise.js:492:17)
at new Promise (C:\ElectronApps\TodoList\node_modules\bluebird\js\release\promise.js:79:10)
at EmbeddedDocument.wrappedPointCut [as save] (C:\ElectronApps\TodoList\node_modules\mongoose\lib\services\model\applyHooks.js:119:23)
at EmbeddedDocument._done (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:101:24)
at _next (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:64:28)
at fnWrapper (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:186:8)
at EmbeddedDocument.<anonymous> (C:\ElectronApps\TodoList\node_modules\mongoose\lib\plugins\sharding.js:16:5)
at _next (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:62:30)
at fnWrapper (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:186:8)
at EmbeddedDocument.<anonymous> (C:\ElectronApps\TodoList\node_modules\mongoose\lib\schema.js:821:7)
at _next (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:62:30)
at fnWrapper (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:186:8)
at EmbeddedDocument.<anonymous> (C:\ElectronApps\TodoList\node_modules\mongoose\lib\plugins\saveSubdocs.js:12:7)
at _next (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:62:30)
at fnWrapper (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:186:8)
at EmbeddedDocument.<anonymous> (C:\ElectronApps\TodoList\node_modules\mongoose\lib\plugins\validateBeforeSave.js:12:14)
at _next (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:62:30)
at fnWrapper (C:\ElectronApps\TodoList\node_modules\hooks-fixed\hooks.js:186:8)
at EmbeddedDocument.<anonymous> (C:\ElectronApps\TodoList\node_modules\mongoose\lib\plugins\sharding.js:16:5)
```

This is the piece of code
```

    function addItem(saleId, item) {
        var deferred = $q.defer();

        Sale.findById(saleId).exec(function (err, sale) {
            if (err) deferred.reject(err);

            sale.lineItems.push({
                description: item.description,
                unitPrice: item.unitPrice,
                quantity: item.quantity
            });

            sale.save(function (err, sale) {
                if (err) deferred.reject(err);
                deferred.resolve(sale);
            });
```
        });

        return deferred.promise;
    }

**Comment by vkarpov15** [comment]
No idea, we don't currently test mongoose with electron. We'll try to repro.

**Comment by varunjayaraman** [comment]
@robsonc if possible, does the same code work outside electron for your app (or is it possible to even try to repro that way?)

**Comment by robsonc** [comment]
@varunjayaraman the same code work outside electron and in electron main process... I run this code inside a angular service, but I try to execute outside angular and doesn't work. 

This is my app.js, the first .js file loaded in index.html.

```
(function () {
    'use strict';

    //var bluebird = require('bluebird');
    var mongoose = require('mongoose');
    var async = require('async');
    var _ = require('lodash');
    var FB = require('fb');

    var GoogleCalendarService = require('./../libs/google-calendar-api');
    var FacebookGraphService = require('./../libs/facebook-graph-api');
    var ipcRenderer = require('electron').ipcRenderer;

    //mongoose.Promise = bluebird;
    mongoose.Promise = global.Promise;

    mongoose.connect('mongodb://localhost/todolistdb', {
        useMongoClient: true
    });

    mongoose.options = {
        debug: true
    };

    angular.module('TodoList', [
        'bs.dolists',
        'bs.crm',
        'bs.sales',
        'ui.router',
        'ui.sortable',
        'ui.bootstrap',
        'ui.bootstrap.tpls',
        'ngAnimate',
        'ngSanitize',
        'angularTrix',
        'ngContentEditable'
    ]);

    angular.module('TodoList')
        .constant('$mongoose', mongoose)
        .constant('async', async)
        .constant('_', _)
        .constant('GoogleCalendarService', GoogleCalendarService)
        .constant('ipcRenderer', ipcRenderer)
        .constant('FacebookGraphService', FacebookGraphService);
})();
```
Now the .js file that loads the model

```
(function() {
    'use strict';

    //entities
    var Sale = require('./../../models/sale');

    angular.module('bs.sales', ['ui.router']);
    angular.module('bs.sales')
        .constant('Sale', Sale);
})();
```
But as I said earlier, the code also did not work outside the scope of the angular.

**Comment by robsonc** [comment]
The version of electron that I use is "electron": "^1.6.11"

**Comment by robsonc** [comment]
And this is my model

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var salesLineItemSchema = new Schema({
    description: String,
    unitPrice: Number,
    quantity: Number    
}, {
    timestamps: true
});

salesLineItemSchema.virtual('subtotal').get(function(){
    return this.unitPrice * this.quantity;
});

var saleSchema = new Schema({
    identifier: String,
    date: {
        type: Date,
        default: new Date()
    },
    discount: Number,
    lineItems: [SalesLineItem]
}, {
    timestamps: true
});

saleSchema.virtual('subtotal').get(function(){
    var total = 0;

    this.lineItems.forEach(function(item){
        total += item.subtotal;
    });

    return total;
});

module.exports = mongoose.model('Sale', saleSchema);
```

**Comment by robsonc** [comment]
I try now, and discover a important issue. If remove the timestamps property, the code works properly.

**Comment by varunjayaraman** [comment]
that's really weird. I'm sorry I can't help more, I've never really worked with electron before

You still kept the timestamps on the `saleSchema` though right? and that works?

**Comment by enderdickerson** [comment]
I'm experiencing a similar issue. I can create a document and add additional subdocuments to it. However, if I try to modify and then save an existing subdocument I get the 'Maximum call stack size exceeded' error. The last few calls are to saveSubdocs, sharding, validateBeforeSave, saveSubdocs, sharding, etc.

I am using electron 1.6.11 and mongoose 4.11.4. 

Here is my code: 


    const Report = this.db.mongoose.model('Report');

    Report.findOne({_id: originalReport.id}, (err, report) => {
      if (err) {
        deferred.reject(err);
        return;
      }

      const result = report.results.id(run);

      result.ignore = true;

      report.save((err2) => {
        if (err2) {
          deferred.reject(err2);
          return;
        }

        deferred.resolve();
      });
    });

I have tried replacing report.save with result.save to no avail. Any help/workarounds would be appreciated. Thanks!

**Comment by ranaali0095** [comment]
I also experience similar issue, while using mongoose with electron. But I fix it by using insertMany()  instead of save().


```
Sale.insertMany(sale).then(sale => {
    
})
```

**Comment by mariohmol** [comment]
Hi there, having a similar issue, maybe is related

https://github.com/Automattic/mongoose/issues/5302

One time i could fix this error changing `save` to `create`, but now i have a new case where `create` does not work.

I tested `insertMany` instead of `create` and same thing, i just can insert if there is no subdocs

**Comment by varunjayaraman** [comment]
@vkarpov15 was this issue potentially resolved by https://github.com/Automattic/mongoose/issues/5513 ?

**Comment by vkarpov15** [comment]
Actually @varunjayaraman could be right. Does the renderer process in electron have a `window` global? If so, mongoose will assume its running in the browser, which was the root of #5513. Will have to check more closely.

**Comment by vkarpov15** [comment]
Yep this was indicative of a couple nasty bugs affecting document arrays in electron (similar to the bugs with jest in jsdom mode), because the electron environment is very strange. Will be fixed on 4.11.9.

**Comment by xaviertung** [comment]
the version 4.11.9 is OK,  but greater than 4.11.10 and 5.0-rc seems a bug yet.

**Comment by vkarpov15** [comment]
@xaviertung code samples please?
