### ISSUE TITLE
Clarity on schema.index function for nested objects

### ISSUE THREAD

**Issue by zackiles** [Automattic/mongoose#5482]
I'd like to set a text index on a property calling it like `schema.index({fieldname:'text'})` but using a nested object so like `schema.index({'nested.prop': 'text'})`

I know you can put `index: true` in the schema property definition itself, but this doesn't seem to work when I want to do multiple properties in the text index like when I can go `schema.index({prop1: 'text', prop2: 'text'})` schema.index seems the only way to create that compound index. I know I can just create a compound index manually too as a separate property and index that, but I'd also not like to use that solution as  it doesn't work well in my situation.

Any clarity on how to pass a dot notation to schema.index? It doesn't look like this works.

**Comment by varunjayaraman** [comment]
@zackiles I'm not able to reproduce, this works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5482`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true })
    const schema = new mongoose.Schema({
      parent: {
        child: String
      }
    });

    schema.index({ 'parent.child': 'text' })
    const Model = mongoose.model('Model', schema);

    yield Model.remove({});

    yield Model.create({ parent: { child: 'test string' } });

    const doc = yield Model.findOne({ $text: { $search: 'test' } });

    console.log('doc', doc); // logs doc
  });
}
```

log output:
```
doc { _id: 5973860a1abb8839496ee780,
  __v: 0,
  parent: { child: 'test string' } }
```

**Comment by vkarpov15** [comment]
Re: using `index: true`, you're right that the only way to create a compound index is `schema.index({ field1: 1, field2: 1 })`, no way to do that with `index: true`. We have no intention of supporting a way to declare compound indexes using schema paths currently.

**Comment by varunjayaraman** [comment]
hmm i think @zackiles 's original question was whether or not you could define a compound index with dot notation. Can you confirm if that is what you were asking? Because that works in the script i posted

**Comment by tomwanzek** [comment]
@vkarpov15 First of all, thanks for all the great work on mongoose.

One question, before I try to do the impossible. Am I reading your comment:

> We have no intention of supporting a way to declare compound indexes using schema paths currently.

correctly, that it is not possible to create a compound index on nested fields using mongoose:

```js
MySchema.index({'header.projectId': 1, 'header.name': 1}, {unique: true});
```

**mongoose version**: 5.0.x

If not, is there a recommended work-around? Manual index creation in MongoDB? This feature seems rather critical, IMHO.

**Comment by tomwanzek** [comment]
@vkarpov15 My question above seems to be obsolete. I just checked that my compound unique index on the two nested properties is enforced. Yeah 🕺 😄
