### ISSUE TITLE
Invalid query automatically provided (injects `_id` when using `.update`)

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#5483]
I think this is a core bug, but it needs reproduced by someone else, perhaps @vkarpov15 can help here?  Per my messages in Mongoose's Slack channel...

The bug basically causes a random `_id` value to be passed to a query:

```js
const chalkline = require('chalkline');

chalkline.green();
const query = {
  items: {
    product: original._id
  }
};
console.log('started query', query);
await lib.db.model('Subscription').update(query, {
  $set: {
    'items.$.product': product._id
  }
}, {
  multi: true
});
console.log('done with query');
chalkline.green();
```

The resulting output (note that the Mongoose debug output shows that it injects a `_id` property in the update query, when I clearly did not specify this above):

```log
started query { items: { product: 596e959a7d020e7776d9c4d8 } }
Mongoose: subscriptions.update({ items: { product: ObjectId("596e959a7d020e7776d9c4d8"), _id: ObjectId("596e9a872da2df7c82b0b8ec") } }, { '$set': { 'items.$.product': ObjectId("596e9a872da2df7c82b0b8eb") } }, { multi: true })
done with query
```

Screenshot of [chalkline](https://github.com/niftylettuce/chalkline) output:

<img width="1264" alt="screen shot 2017-07-18 at 7 33 45 pm" src="https://user-images.githubusercontent.com/523141/28344933-d28dd9ae-6bf4-11e7-9435-82bdedb437df.png">

I've temporary fixed it by converting the nested query to be a string `items.product` (and following log/screenshot shows this fixes the issue):

```js
chalkline.green();
const query = {
  'items.product': original._id
};
console.log('started query', query);
await lib.db.model('Subscription').update(query, {
  $set: {
    'items.$.product': product._id
  }
}, {
  multi: true
});
console.log('done with query');
chalkline.green();
```

Screenshot showing that it no longer injects the `_id` property:

<img width="1261" alt="screenshot" src="https://user-images.githubusercontent.com/523141/28345075-a43ea2ee-6bf5-11e7-8327-e62ee533d7f4.png">

---

Can we see if this is reproducible by someone else?

Currently on Node v8.0.0, Mongoose v4.9.9, and MongoDB v3.4.2.

**Comment by varunjayaraman** [comment]
yep, looks like a bug:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5483`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true })
    
    const refSchema = new mongoose.Schema({
      name: String
    });

    const Ref = mongoose.model('Ref', refSchema);

    const schema = new mongoose.Schema({
      name: String,
      testRefs: [{ ref: { type: mongoose.Schema.Types.ObjectId, ref: Ref } }]
    });

    const Model = mongoose.model('Model', schema);

    const ref = yield Ref.create({ name: 'test-ref' });

    const doc = yield Model.create({ name: 'test-model', testRefs: [{ ref: ref._id }] });


    yield Model.update({ testRefs: { ref: ref._id } }, { $set: { name: 'update-test-model' } }); // attaches _id to query
  });
}
```

mongoose debug output:

```
Mongoose: refs.insert({ name: 'test-ref', _id: ObjectId("596ec78504232cc835ed3e3e"), __v: 0 })

Mongoose: models.insert({ name: 'test-model', _id: ObjectId("596ec78504232cc835ed3e3f"), testRefs: [ { ref
: ObjectId("596ec78504232cc835ed3e3e"), _id: ObjectId("596ec78504232cc835ed3e40") } ], __v: 0 })

Mongoose: models.update({ testRefs: { ref: ObjectId("596ec78504232cc835ed3e3e"), **_id: ObjectId("596ec78504232cc835ed3e41")** } }, { '$set': { name: 'update-test-model' } }, {})
```

That `_id` shouldn't be in the update find condition

**Comment by niftylettuce** [comment]
Any update here?

**Comment by vkarpov15** [comment]
Sorry for the delay @niftylettuce , we're behind on a bunch of issues. I took a closer look and this isn't a bug, its intentional behavior. Here's why:

```javascript
    const schema = new mongoose.Schema({
      name: String,
      testRefs: [{ ref: { type: mongoose.Schema.Types.ObjectId, ref: Ref } }]
    });
```

is equivalent to:

```javascript
    const schema = new mongoose.Schema({
      name: String,
      testRefs: [new mongoose.Schema({ ref: { type: mongoose.Schema.Types.ObjectId, ref: Ref } })]
    });
```

Mongoose implicitly creates a schema when you add a document array to a schema. Because of this, your document arrays will have an `_id` by default. That brings us to the first way to work around your issue:

```javascript
    const testRefSchema = new mongoose.Schema({ ref: { type: mongoose.Schema.Types.ObjectId, ref: Ref } }, { _id: false }); // <-- disable `_id` for this schema. Often useful for embedded docs

    const schema = new mongoose.Schema({
      name: String,
      testRefs: [testRefSchema]
    });
```

If you don't turn `_id` off, here's what happens:

```javascript
const query = {
  items: { // <-- Mongoose will cast `items` to the correct schema, which includes `_id`
    product: original._id
  }
};
await lib.db.model('Subscription').update(query, update);
```

Mongoose will add `_id` because when you're querying by `items`, mongoose will cast using the schema you provided, which includes an `_id` field by default.

However, the question is, why are you querying by `items: { product: original._id }` instead of `'items.product': original._id` ? The former asks MongoDB to do a deep equality check, it will only match if `items` contains a doc with exactly one key, `product`, whose value is `original._id`. The latter will match if `items` contains a doc whose key `product` is equal to `original._id`, even if the doc contains other keys. In other words, if mongoose didn't insert `_id` for you in your original query, the query still would not match any documents because mongoose inserts the `_id` by default when you `save()` the document.
