### ISSUE TITLE
orm

### ISSUE THREAD

**Issue by lkdevgenesis** [Automattic/mongoose#5485]
hi team,

can you suggest how can handle orm in mongoose like laravel orm elquent if any plugin or libery please suggest me because of  find user then create foreach with conncect another collection then not so better

**Comment by varunjayaraman** [comment]
i don't understand what you're looking for. if you're asking how to create docs and find documents in a db, everything is available on the mongoose API documentation

**Comment by lkdevgenesis** [comment]
one to one or one to many relationship between two collection like sql join in nodejs mongoose scheme or other packagers may be helpfull for me
