### ISSUE TITLE
Organizing static functions in mongoose

### ISSUE THREAD

**Issue by sanjeevmalagi1** [Automattic/mongoose#5489]
I am building application in node js using mongodb. I am using mongoose as ODM. The problem is I have lot of static functions in mongoose model which are attached to schema.

Is there a way to write these functions in another file(or module) and import and attach them to schema. Thanks.

https://stackoverflow.com/questions/45191271/organizing-static-functions-in-mongoose

**Comment by varunjayaraman** [comment]
yes, you can use a plugin if you want. A plugin is basically just a function that takes a schema and mutates it, so you can import the plugin from another file and call `schema.plugin(thePlugin)`:

http://mongoosejs.com/docs/plugins.html
