### ISSUE TITLE
Subdocument inheritance not working

### ISSUE THREAD

**Issue by kadosh1000** [Automattic/mongoose#5490]
Here is a sample code: 

    // Children
    function abstractSchema() {
        Schema.apply(this, arguments);

        this.add({
            name: String
        });
    };

    util.inherits(abstractSchema, Schema);

    var mySchema = new abstractSchema();

    // 
    // Inherited Types 

    var textPropertySchema = new abstractSchema({
        length: Number
    });

    var numberPropertySchema = new abstractSchema({
        dp: Number
    });

    //
    // Parent Model

    var myModelSchema = mongoose.Schema({
        name: String,
        properties : [mySchema]   
    });

When i save each an instance of numberPropertySchema or textPropertySchema, the _t (type is written) and is able to deserialise properly.
When however added as a sub doc array, they're all persisted with the base object properties only.
Is there any way round this? any extensions that could be used?

**Comment by varunjayaraman** [comment]
@kadosh1000 i'm confused, are you not using mongoose discriminators?

http://mongoosejs.com/docs/discriminators.html

**Comment by vkarpov15** [comment]
You're defining `properties` using `mySchema`, so mongoose will use `mySchema` to cast. It has no knowledge of `textPropertySchema` or `numberPropertySchema`, you need to use discriminators for that.

**Comment by varunjayaraman** [comment]
@kadosh1000 can you try using discriminators and let us know if that solves your problem?

Let us know if you need help with the syntax / how to use discriminators!
