### ISSUE TITLE
Support question - override validation - force insertion to db

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5491]
A quick google search did yield anything - is there a way to do something like this:

```js
  Prompt.update({'specialId': 'STANDARD_TEXT_RESPONSE'}, {
        '#id': 'NO_LINK',
        'specialId': 'STANDARD_TEXT_RESPONSE',
        'acqId': 'DUMMY_ACQ',
        'parentId': null,
        'kind': 'text',
        'value': '[placeholder text]'
      }, {upsert: true, multi: false, force: true}, cb);   // force is true

```
(Obviously, "force" is probably not a real property on the options object, but just an example.)

I need to force this into the DB. The validation error is that 'DUMMY_ACQ' cannot be cast to ObjectId, but I would like to ignore that error and force this document into the collection.

any help appreciated.

**Comment by varunjayaraman** [comment]
not that i know of. Your best bet is to either create a union type through a discriminator or to make it a Mixed Type (but make sure to manually `markModified()` if you use a Mixed Type and are doing `save` ops)

@vkarpov15 can you think of a way to do this?

**Comment by ORESoftware** [comment]
@varunjayaraman thanks, I was reading some older issues and it seems like you can use a plugin or something which simply skips the validation, but still not sure how to do that. But, I would rather be able to skip the validation in the context of the `Prompt.update` call.

**Comment by varunjayaraman** [comment]
@ORESoftware you could try using the underlying driver and bypassing mongoose for this?

**Comment by ORESoftware** [comment]
@varunjayaraman yeah I think that's reasonable, thanks
