### ISSUE TITLE
Binary buffer saved incorrectly  (breaking change)

### ISSUE THREAD

**Issue by ValYouW** [Automattic/mongoose#5497]
Hi,

When saving GUID to mongo using MongooseBuffer it is being saved incorrectly, this is a breaking change that apparently introduced in version 4.11.2 (I suspect this commit: 1613ef522fb44a2870041b8833bf2f3b36fc45a0)

 I create the value as:
```js
var buffer = uuidParse.parse(string); // Some guid string
return new mongoose.Types.Buffer(buffer).toObject(0x04);
```
And the value is being saved in the db as:
```
"user" : { "$binary" : "OyRXTOkgQGaO7JL55GgnAg==", "$type" : "00" }
```
While in version 4.11.1 it is being saved as:
```
"user" : UUID("3b24574c-e920-4066-8eec-92f9e4682702")
```

While debugging method `Query.prototype._findAndModify` I can see that the value in `castedDoc` object is different, in 4.11.1 is:
![binary_4_11_1](https://user-images.githubusercontent.com/4539636/28503129-57bfce76-7009-11e7-9252-8a361b7dcb8b.png)

While in 4.11.2 it is:
![binary_4_11_2](https://user-images.githubusercontent.com/4539636/28503130-6225f750-7009-11e7-9df3-76e3910e710d.png)

I think it happens because of changes in the commit referenced above makes it so `SchemaBuffer.prototype.castForQuery` is not being called.

Thanks.

**Comment by vkarpov15** [comment]
Thanks for reporting and providing detailed info. We'll try to repro soon and get back to you.

**Comment by ValYouW** [comment]
@vkarpov15 You can try this:
```js
var mongoose = require('mongoose'),
	uuid = require('uuid'),
	uuidParse = require('uuid-parse');

mongoose.Promise = Promise;

function generateUUID() {
	var buffer = uuid.v4(null, new Buffer(16));
	return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

function toUUID(string) {
	if (!string) {return null;}
	var buffer = uuidParse.parse(string);
	return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

function fromUUID(buffer) {
	if (!buffer || buffer.length !== 16) {return null;}
	return uuidParse.unparse(buffer);
}

var UserSchema = new mongoose.Schema({
	name: String,
	foo: {
		type: mongoose.Schema.Types.Buffer,
		get: fromUUID,
		set: toUUID
	}
}, {collection: 'users'});

var UserModel = mongoose.model('User', UserSchema);

var connStr = 'mongodb://test:test@127.0.0.1/test';
mongoose.connect(connStr);

var user = {name: 'insert', foo: uuid.v4()};
console.log('Inserting user, my foo will be OK:', user);
var dalUser = new UserModel(user);
dalUser.save().then(() => {
	console.log('User inserted successfully');
}).catch(console.error);


user = {name: 'upsert', foo: uuid.v4()};
console.log('Upserting user, my foo will be wrong:', user);
var opts = {upsert: true, setDefaultsOnInsert: true };
UserModel.findOneAndUpdate({foo: user.foo}, user, opts).exec().then(() => {
	console.log('User upserted successfully');
}).catch(console.error);
```

**Comment by varunjayaraman** [comment]
@ValYouW there was some wonky async handling in your script so i made this:

```javascript
var mongoose = require('mongoose'),
  uuid = require('uuid'),
  uuidParse = require('uuid-parse');

mongoose.Promise = Promise;

function generateUUID() {
  var buffer = uuid.v4(null, new Buffer(16));
  return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

function toUUID(string) {
  if (!string) { return null; }
  var buffer = uuidParse.parse(string);
  return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

function fromUUID(buffer) {
  if (!buffer || buffer.length !== 16) { return null; }
  return uuidParse.unparse(buffer);
}

var UserSchema = new mongoose.Schema({
  name: String,
  foo: {
    type: mongoose.Schema.Types.Buffer,
    get: fromUUID,
    set: toUUID
  }
}, { collection: 'users' });

var UserModel = mongoose.model('User', UserSchema);

var connStr = 'mongodb://localhost:27017/gh-5497';
mongoose.connect(connStr);

var user = { name: 'insert', foo: uuid.v4() };
console.log('Inserting user, my foo will be OK:', user);
var dalUser = new UserModel(user);
dalUser.save().then(() => {
  console.log('User inserted successfully');



  user = { name: 'upsert', foo: uuid.v4() };
  console.log('Upserting user, my foo will be wrong:', user);
  var opts = { upsert: true, setDefaultsOnInsert: true };
  UserModel.findOneAndUpdate({ foo: user.foo }, user, opts).exec().then(() => {
    console.log('User upserted successfully');
  }).catch(console.error.bind(console));
}).catch(console.error.bind(console));

```

I'm still confused though, which part of the script are you saying is not getting inserted into the db correctly?

**Comment by ValYouW** [comment]
@varunjayaraman Hey, the code doesn't need to be synchronized, it doesnt really matter. What I do is 2 independent things:
1. Insert new user with `name=insert` using the `Model.save` method
1. Insert new user with `name=upsert` using `Model.findOneAndUpdate` and `upsert=true`

Now if you examine in the DB the `foo` property (which is the binary field) you will find that for the 1st user, which was inserted using `Model.save` the value of `foo` is `UUID("5fcc7668-2716-4f99-9c71-03e14cbeaa8f")`.
While that for the 2nd user, which was inserted using `Model.findOneAndUpdate` the value of `foo` is `{ "$binary" : "YzA1NDk5ZWEtOWUzNy00NmFhLThlNzMtNGZmN2Q0Nzg5MjYz", "$type" : "00" }`

Here is a screenshot:
![image](https://user-images.githubusercontent.com/4539636/28864782-4bfc884e-7776-11e7-83a1-7732b57c21ed.png)

**Comment by vkarpov15** [comment]
@ValYouW the problem is that mongoose doesn't run setters when you do `findOneAndUpdate()` by default for backwards compatibility. You need to use the `runSettersOnQuery` option.

```javascript
// Need to modify your setter to handle values that are already buffers
function toUUID(string) {
  if (!string) { return null; }
  if (Buffer.isBuffer(string) || Buffer.isBuffer(string.buffer)) { return string; }
  var buffer = uuidParse.parse(string);
  return new mongoose.Types.Buffer(buffer).toObject(0x04);
}

// If you set `runSettersOnQuery`, your setter will get run and so you'll get a UUID in the database
  user = { name: 'upsert', foo: uuid.v4() };
  console.log('Upserting user, my foo will be right because of `runSettersOnQuery`:', user);
  var opts = { upsert: true, setDefaultsOnInsert: true, runSettersOnQuery: true };
  UserModel.findOneAndUpdate({ foo: user.foo }, user, opts).exec().then(() => {
    console.log('User upserted successfully');
  }).catch(console.error.bind(console));
```

**Comment by ValYouW** [comment]
@vkarpov15 im not sure I'm following, this code run as expected on older versions of mongoose, it stopped working on 4.11.2, it is breaking compatibility... Please see my original big desc

**Comment by ValYouW** [comment]
@vkarpov15 Can you please elaborate on why it stopped working?  Did it worked like it did by mistake?
