### ISSUE TITLE
Some connection events not fired when `useMongoClient` is true

### ISSUE THREAD

**Issue by davebaol** [Automattic/mongoose#5498]
With reference to [the connection API documentation](http://mongoosejs.com/docs/api.html#connection_Connection), looks like some connection events are not emitted when `useMongoClient` is true.
Especially, listeners are invoked for `connecting`, `connected` and `open` events when you first connect to the db.
However, I cannot get `disconnected` and `reconnected` events on reconnection scenarios.
Those events are properly emitted when `useMongoClient` is false.

**Software version:**
Node 6.10.2
Mongodb 3.4.1
Mongoose 4.11.4

**Comment by vkarpov15** [comment]
Thanks for reporting, we'll try to repro ASAP. If you can provide a standalone script that reproduces your issue it'll save us a bunch of time and help us fix this faster.

**Comment by davebaol** [comment]
Sure, I'm going to try. Just not clear to me how to reproduce programmatically a disconnection/reconnection scenario through a mocha test.

**Comment by davebaol** [comment]
Ok here's a simple repro script. Not a mocha test, but still....
Just start and stop manually the database to see fired events.

````javascript
const mongoose = require('mongoose');

const GITHUB_ISSUE = `gh-5498`;

mongoose.Promise = global.Promise;
mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true, promiseLibrary: global.Promise });

[
  "connecting",
  "connected",
  "open",
  "disconnecting",
  "disconnected",
  "close",
  "reconnected",
  "error",
  "fullsetup",
  "all"
].forEach(event => {
    mongoose.connection.on(event, function () {
    console.log('Mongoose event ' + event);
  });
});
    
function ping() {
  mongoose.connection.db.admin().ping(function (err, result) {
    if (err || !result)
      console.log('no ping result');
    else
      console.log('ping');
  });
}

setInterval(ping, 5000); 
````

**Comment by cdchase** [comment]
I believe this may be related to a problem I had with the availability of the connection object properties when using `openUri()`. I've supplied [PR 5503](https://github.com/Automattic/mongoose/pull/5503) which I think will resolve both of our issues--it does mine.

**Comment by varunjayaraman** [comment]
thanks @davebaol it looks like the `disconnected` and `error` events dont get reported with `useMongoClient`

**Comment by djanowski** [comment]
We're upgrading our connection code to use MongoClient, also to debug connection issues, so losing these events defeats the point.

I appreciate that you're looking into this. Thank you.
