### ISSUE TITLE
Query main document by subdocument

### ISSUE THREAD

**Issue by vforv** [Automattic/mongoose#5499]
I am not sure if that functionality exists, but would be realy useful.

I am trying to get some data from main document only if something exists in subdocument.

Ex.

`Product.find({}).populate('user', ['deactived', false])`

It should like something like in example above and it will return just products where in subdocument user is not deactived.

I know there is also option to filter document after query but it is not good solution because if we add pagination, code will not work properly.

**Comment by catchshyam** [comment]
If you are using Mongod 3.2 or later, have a look at $lookup in the aggregation framework.

https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/

**Comment by vkarpov15** [comment]
```javascript
Product.find({}).populate({ path: 'user', match: { deactivated: false } })
```

See "Query conditions and other options" on [populate docs](http://mongoosejs.com/docs/populate.html)

**Comment by vkarpov15** [comment]
Ah woops I slightly misread your question. No, there is no way to find products where user is not deactivated with populate. You would have to use `$lookup`, or add a `userDeactivated` property to products.
