### ISSUE TITLE
Behavior of `MongooseArray.push()` Dependent on Original Contents And Empty Array Simply Uses ObjectId

### ISSUE THREAD

**Issue by c1moore** [Automattic/mongoose#5504]
This is a bug report and I am using Mongoose v4.11.1 and MongoDB v3.2.  This bug is best explained in the code snippet below.  Basically, when using `MongooseArray.push()`, what gets pushed to the MongooseArray depends on the contents of the MongooseArray.  If the MongooseArray was initialized with a subdocument, `push()` adds a subdocument to the array, this is the expected behavior.  However, if the MongooseArray was empty, just the `ObjectId` of the subdocument is added to the list.

In my opinion, what is pushed to the array is what should be added to the array.  Mongoose attempting to determine what to push to the array based on current contents can result in unexpected behavior.  For example, I'm not sure how it would handle of mixture of `ObjectId`s and subdocuments.

```javascript
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.Promise = require('bluebird');

var Referrer;

function endProcess(error) {
  error && console.error(error);

  Referrer.remove({});

  process.exit();
};

mongoose.connect('mongodb://localhost/test', {
  useMongoClient: true
}).then(
  function() {
    var referenceA,
        referenceB,
        referrerA,
        referrerB;

    const ReferringSchema = new Schema({
      reference:  [{
        type:       Schema.Types.ObjectId,
        ref:        'Referrer'
      }]
    });

    Referrer = mongoose.model('Referrer', ReferringSchema);

    referenceA = new Referrer();
    referenceB = new Referrer();

    referrerA = new Referrer({reference: [referenceA]});
    referrerB = new Referrer();

    referrerA.reference.push(referenceB);
    console.log(referrerA);
    console.log(referrerA.reference[0] instanceof Referrer);  // true, as expected
    console.log(referrerA.reference[1] instanceof Referrer);  // true, as expected

    referrerB.reference.push(referenceB);
    console.log(referrerB);
    console.log(referrerB.reference[0] instanceof Referrer);  // false
  },
  function(error) {
    console.error(error);

    process.exit();
  }
).then(endProcess, endProcess);
```

**Comment by vkarpov15** [comment]
This is intentional behavior that we added into 4.0, general idea is that this is "manually populating" a document array. If you don't want this behavior, push the_id. I'm open to considering changing this if you have a strong argument against this behavior

**Comment by c1moore** [comment]
To the contrary, I like "manual population."  The problem is its use is sporadic.  If the array does not currently have anything in it and you push a manually populated document to the array, it will convert it to an ObjectId instead of leaving the document manually populated.  The script should provide you with a demo.

I would argue that if you push a manually populated document to the array, it should remain manually populated.

**Comment by c1moore** [comment]
@vkarpov15 Any thoughts on this issue?  It's affecting some of my current projects where I basically don't want to leak any implementation details about how the subdocuments are stored (i.e. as ObjectIds instead of real documents).

**Comment by vkarpov15** [comment]
@c1moore an alternative would be to use the `depopulate` option for `toObject()` and `toJSON()`

```javascript
var schema = new Schema({
}, { toJSON: { depopulate: true }, toObject: { depopulate: true } });
```

This will make sure to remove any populated docs when using `JSON.stringify()`, `res.json()` with Express, etc. Would this work for you?

**Comment by c1moore** [comment]
@vkarpov15 I'm not sure we're on the same page.  The problem isn't depopulation either.  Let's say I have a Model (say `Referrer`) as above that stores an array of `ObjectId`s which reference some other Model (say `Reference`).

### Scenario 1

I create a new `Referrer` and initialize it with a pre-populated `Reference`, as follows

```javascript
var referrer = new Referrer({
  referencedWorks: [new Reference()]
});

referrer.referencedWorks[0].should.be.instanceOf(Reference);  // => true
```

Using this method, `referrer.referencedWorks[0]` is an instance of a `Reference`, as expected.  Now if we add another `Reference` as below, `referrer.referencedWorks[1]` will also be an instance of `Reference`.

```javascript
referrer.referencedWorks.push(new Reference());

referrer.referencedWorks[1].should.be.instanceOf(Reference);  // => true
```

### Scenario 2 (Error-Prone Scenario)

In this scenario, we simply create a new `Referrer` as below:

```javascript
var referrer = new Referrer();
```

Now we add a pre-populated `Reference` as below:

```javascript
referrer.referencedWorks.push(new Reference());

referrer.referencedWorks[0].should.be.instanceOf(Reference);  // => Error: Expected '55...fe' to be instance of Reference
```

The thing added to `referrer.referencedWorks` is an `ObjectId`, not the "manually populated" document I tried to push to the array.  In Scenario 1, this worked, but here the behavior is different and herein lies the problem.  There really isn't (or shouldn't be) any _real_ difference between creating a new document initialized with some manually populated subdocuments then pushing more to it and creating a new document and pushing manually populated subdocuments to it.

### Possible Problem/Solution
Again, I like the manual population feature, I just want the behavior to be consistent from the point of view explained above.  I haven't been able to look into the problem myself, but I assume the problem is with code somewhere in the core that behaves similar to the following:

```javascript
if(this.populated(path)) {
  this[path].push(manuallyPopulatedDoc);

  return;
}

this[path].push(manuallyPopulatedDoc._id);
```

A simple solution that would work for me is to replace that algorithm with something like

```javascript
if(this.populated(path) || !this[path].length) {
  this[path].push(manuallyPopulatedDoc);

  return;
}

this[path].push(manuallyPopulatedDoc._id);
```

### Monkey Patch

A temporary monkey patch for this appears to be

```javascript
var referrer = new Referrer();

referrer.populate('referencedWorks').execPopulate();  // Don't actually need to wait for results since its an empty array.

referrer.referencedWorks.push(new Reference());
referrer.referencedWorks.push(new Reference());

_.forEach(referrer.referencedWorks, (referencedWork) => console.log(referencedWork instanceof Reference)); // => true\ntrue
```

**Comment by vkarpov15** [comment]
Ah ok, I see the issue now. Thanks for your patience in explaining this, we'll fix this for the next patch release :+1:

**Comment by c1moore** [comment]
@vkarpov15 This appears to still be an issue for similar methods like `splice()` and `unshift()`.  Can we extend this functionality to those methods, too?

**Comment by vkarpov15** [comment]
Gotcha. Will fix.

**Comment by c1moore** [comment]
@vkarpov15 Thanks for staying on top of this.  There appears to be one last method that needs updates: `addToSet()`

**Comment by vkarpov15** [comment]
Gotcha :+1:
