### ISSUE TITLE
App just won't connect to DB, Need assistance.

### ISSUE THREAD

**Issue by violetzie** [Automattic/mongoose#5508]
Hello.

I have deployed my node.js app to an Ubuntu 16 VPS, I got everything set up but my app is hanging on connecting to the mongoDB on mLab and I couldn't find a solution anywhere..

The app crashes on
`MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]`

Which is strange since it shouldn't be trying to connect to localhost but towards mLab. As in the actual connect script

`mongoose.connect('mongodb://username:password@server.mlab.com:27153/dbname', options);`

in this format.

I have triple checked all my credentials and everythings ok. I tried connecting to mongo directly from my VPS via 

`mongo host -u username -p password`

, which works fine.

**Server node.js version**: 5.8.0
**Server MongoDB shell version**: 3.4.6 (I can connect with this one I guess?)

**Project Mongoose version**: 4.11.4
**Project Mongoose MongoDB (bundled)** : 2.2.27

**mLab mongod version**: 3.2.13

Could someone point me in a direction of fixing this? Can't seem to find anything and so far it seems like the bundled MongoDB version in Mongoose might be the culprit? (Maybe not?)

Thank you in advance

**Comment by violetzie** [comment]
Complete error message. Tried updating node.js to 6.11.1, didn't help.

```
{ MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/adserver/node_modules/mongodb-core/lib/topologies/server.js:329:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/adserver/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/adserver/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
```

**Comment by deathlover** [comment]
i have got the exact same issue. 
did u manage to solve?

**Comment by violetzie** [comment]
@deathlover I discovered it was one of my other packages that was trying to use mongoose and connect to localhost through its config file (that I had no idea I had to edit) , I edited it and it started working, can't vouch that it's the same problem for you though.

**Comment by Ridge2** [comment]
@violetzie Can you tell me exactly what you did? I'm having the same issue right now.

**Comment by deiangi** [comment]
@violetzie How did you solve your problem?

**Comment by deathlover** [comment]
short and sweet way to solve the issue:

consider there are two server:
202.202.202.202 - App Server
202.202.202.203 - Database Server

Mongo should be installed on both the servers for the inter connectivity of mongoose from one server to another one.
