### ISSUE TITLE
Upsert update for a GeoJSON, results in a path StrictModeError

### ISSUE THREAD

**Issue by uripre** [Automattic/mongoose#5509]
**I have the following schema:**

```
const ZoneSchema = mongoose.Schema({
    name: String,
    country: String,
    geo: {
        type: { type: String, enum: ['Point', 'LineString', ...],
        coordinates: mongoose.Schema.Types.Mixed,
    },
}, { timestamps: true, minimize: true });

ZoneSchema.index({ geo: '2dsphere', name: 1 });
export default mongoose.model('Zone', ZoneSchema);

```
**I later try to do:**

`Zone.update({ country: 'US', geo: null }, { name: 'Zone 1' }, { upsert: true, setDefaultsOnInsert: true });`

**It fails with the following error message:**

`StrictModeError: Path "geo" is not in schema, strict mode is 'true', and upsert is 'true'.`

**Why does it behave this way? Isn't a bug?** 

_node.js 6.11.1   mongoose 4.11.4   MongoDB 3.4.4_

**Comment by vkarpov15** [comment]
I believe this is a duplicate of #5467, try upgrading to 4.11.5

**Comment by varunjayaraman** [comment]
@uripre can you confirm updating to 4.11.5 fixes it for you?
