### ISSUE TITLE
Checking connection status in MongooseJS ES6 model constructors

### ISSUE THREAD

**Issue by jhyland87** [Automattic/mongoose#5511]
I'm working on a project in which we use MongooseJS for our ODM. These Mongoose models will be utilized on various other projects by other developers. Thus, I'd like to implement some logic to verify that there's an active connection to the backend Mongo database.

I'm trying to implement said logic within the ODM models themselves that will verify that there's an active connection to a MongoDB database. I have the check logic itself figured out, but I seem to be having some issues with having the check execute at the proper time. 

The below JS code is the relevant code of a Mongoose ODM model; You'll notice the `isConnected()` function is **executed at the top level of the file** (as opposed to being executed within one of the model methods):

```js
/**
 * FILE: models/Account.js
 */

const _             = require( 'lodash' )
const Mongoose      = require( 'mongoose' )
const { Schema, Types, Model } = Mongoose

// Checks if the mongoose connection readyState is either 1 (connected) or 2 (connecting)
function isConnected( mdb ){
  return _.indexOf( 
    [ 1, 2 ],  
    _.get( mdb, 'connection.readyState', null )
  ) !== -1
}

if ( ! isConnected( Mongoose ) )
  throw new Error( 'The Mongoose connection is not active' )

class Account extends Model {
  constructor ( data ) {
    super( data )
  }

  // Methods truncated...
}

Account.Model = Mongoose.model( Account, Account.Schema )

module.exports = Account
```

And the above works fine provided the connection to the MongoDB server is established **prior** to the ODN modules being loaded; Otherwise, it fails:

```js
const Mongoose  = require( 'mongoose' )

/**
 * EXAMPLE A - SUCCESS - MDB connection & module inclusion
 */
Mongoose.connect( 'mongodb://127.0.0.1:27017/Foo', {
  useMongoClient: true,
  config: { autoIndex: false }
})

const Account = require('./Account')

new Account({/* Stuff */}).save()
  .then( doc => console.log( 'Created:', doc ) )
  .catch( err => console.error( 'ERROR:',err ) )
  .finally( () => Mongoose.connection.close() )

/**
 * EXAMPLE B - FAIL - Module included *before* MDB connection established
 */ 
const Account = require('./Account')

Mongoose.connect( 'mongodb://127.0.0.1:27017/Foo', {
  useMongoClient: true,
  config: { autoIndex: false }
})

new Account({/* Stuff */}).save()
  .then( doc => console.log( 'Created:', doc ) )
  .catch( err => console.error( 'ERROR:',err ) )
  .finally( () => Mongoose.connection.close() )
```

## Question
**How can I have the `isConnected()` function execute _whenever a new object is instantiated_**, as opposed to when the file is loaded via `require()`? **I did try to simply adding `isConnected()` to the `constructor` method in `Account`**, but it seemed that the `isConnected()` was getting executed **after** the object was saved, which seems counterintuitive to me; I'm assuming this is due to the asynchronous nature of NodeJS, but 

**Here's an example of what I'm looking for:**

```js
const Mongoose  = require( 'mongoose' )

/**
 * EXAMPLE A - This should FAIL due to an instantiation of a new 
 * Account object before the OMD connection is established 
 */
const Account = require('./Account')

new Account({/* Stuff */}).save()
  .then( doc => console.log( 'Created:', doc ) )
  .catch( err => console.error( 'ERROR:',err ) )
  .finally( () => Mongoose.connection.close() )

Mongoose.connect( 'mongodb://127.0.0.1:27017/Foo', {
  useMongoClient: true,
  config: { autoIndex: false }
})


/**
 * EXAMPLE B - This should SUCCEEDE since the Account class is merely 
 * included via require(), but the MongoDB connection is established 
 * prior to any Account object instantiation
 */
const Account = require('./Account')

Mongoose.connect( 'mongodb://127.0.0.1:27017/Foo', {
  useMongoClient: true,
  config: { autoIndex: false }
})

new Account({/* Stuff */}).save()
  .then( doc => console.log( 'Created:', doc ) )
  .catch( err => console.error( 'ERROR:',err ) )
  .finally( () => Mongoose.connection.close() )
```

My attempt at accomplishing this was to move the validation into the class constructor:

```js
/**
 * FILE: models/Account.js
 */

const _             = require( 'lodash' )
const Mongoose      = require( 'mongoose' )
const { Schema, Types, Model } = Mongoose

// Checks if the mongoose connection readyState is either 1 (connected) or 2 (connecting)
function isConnected( mdb ){
  return _.indexOf( 
    [ 1, 2 ],  
    _.get( mdb, 'connection.readyState', null )
  ) !== -1
}

class Account extends Model {
  constructor ( data ) {
    super( data )

    if ( ! isConnected( Mongoose ) )
      throw new Error( 'The Mongoose connection is not active' )
  }

  // Methods truncated...
}

Account.Model = Mongoose.model( Account, Account.Schema )

module.exports = Account
```

But, as stated earlier, **the exception seemed to be executing _before_ `isConnected()` was executed**

Any input is appreciated, thank you!

**Comment by vkarpov15** [comment]
Thanks for the detailed issue report, I'll look into this shortly and get back to you.

**Comment by mleanos** [comment]
This type of abstraction is always interesting to me. I have a similar use case in a Typescript project.

I'm curious why the connection state is so important in your situation. I can see the need to foresee (prevent) connectivity exceptions during mongoose operations, but that risk will always be present unless you check for connection state before any operation; mongoose will already notify you when there's no connection in an error response. This is why I'm interested to know if you have a special use case that really requires this.

SIDE NOTE: Even if you put the connection state check in the constructor, connection could be lost before your operation starts. 

In most of my use cases I load my models into Mongoose after a successful connection. I also extend the Mongoose Model class with my own models, like you're doing. However, I have a `registerModel` method of my classes that I call when the `mongoose.connect` resolves.

**Comment by vkarpov15** [comment]
I can see one reason for doing this: mongoose buffering is a common gotcha, sometimes people forget to `connect()`, create a few models, and are baffled as to why all their database operations hang forever.

I think you're going about this in the wrong way. One way to work around this is to [turn off `bufferCommands` in your schema](http://mongoosejs.com/docs/guide.html#bufferCommands), then mongoose will immediately callback with an error (or reject the promise) if you try to do anything that touches the mongodb server if you haven't connected yet.

Another approach would be to export schemas rather than models, and then call `mongoose.model()` in one centralized location rather than in individual files. You're right in that calling `mongoose.model()` in individual files is dangerous because you might not have a connection, but you're better off having a separate function that's responsible for connecting and then creating models rather than relying on each file to check on its own.
