### ISSUE TITLE
with secondaryPreferred,mongo read from every node

### ISSUE THREAD

**Issue by 5977862** [Automattic/mongoose#5512]
I try to use read mode with primary, primaryPreferred, secondary and secondaryPreferred.

When read mode is secondaryPreferred, mongo read from all the nodes, and no date write to primary as same time.

I found this problem from online slow log, I wander why so many read slow log in primary node.

When I try it in local,I am sure when use secondaryPreferred,It not read from secondary,it read from all the nodes.

Why?

**Comment by vkarpov15** [comment]
Please provide code samples, I don't understand the issue
