### ISSUE TITLE
By default, npm installs unstable versions.

### ISSUE THREAD

**Issue by caiges** [Automattic/mongoose#5514]
By default, npm installs unstable versions. This is ridiculous and stupid and will lead to users using something they likely shouldn't. Use proper prerelease version identifiers so that people get something stable out of the box. It's 2017 guys. 

If for some reason I am missing something completely obvious I will gladly eat my hat.

**Comment by vkarpov15** [comment]
I must have missed something, we haven't used unstable releases since early 2015. If there is one, I'd be quite shocked.

**Comment by caiges** [comment]
This was my fault, we had a really old version pinned deep in the depths. I was also a grouch when I submitted and have eaten said hat :tophat: Thanks!

**Comment by vkarpov15** [comment]
No worries, it happens. I thoroughly expect a [Herzog-style documentary](https://en.wikipedia.org/wiki/Werner_Herzog_Eats_His_Shoe) though :laughing:
