### ISSUE TITLE
How to stop data migration when starting the server

### ISSUE THREAD

**Issue by khoa162** [Automattic/mongoose#5515]
Hi Folks, I dont want my database to be updated when starting the server. How can I do that in the best practice

**Comment by varunjayaraman** [comment]
what do you mean? Are you running an update operation on start up? Can you just not do that?

**Comment by khoa162** [comment]
I mean stop data migration when starting the server. Because when the server is started, the database has been updated

**Comment by varunjayaraman** [comment]
sorry, I don't understand what you mean

**Comment by khoa162** [comment]
what I mean is data migration, the data migration is executed whenever I start the server. That is unnecessary to me.

**Comment by varunjayaraman** [comment]
what data migration are you talking about?
