### ISSUE TITLE
Problem when populate from different databases

### ISSUE THREAD

**Issue by emilhamep** [Automattic/mongoose#5519]
I'm newbie about Mongoose(4.9.6), MongoDB( 2.2.26)and Node JS(6.10.2). So I have two different db connections and three models. My purpose is to populate from three models. But the error message appears "Schema hasn't been registered for model user".

My model as shown below:
`var mongoose = require('mongoose');`
`var moment = require('moment')`
`var async = require('async');`

`var conn1 = mongoose.createConnection('myconnection1');`
`var conn2 = mongoose.createConnection('myconnection2');`

`var Schema = mongoose.Schema;`

`var CategorySchema = Schema({`
  `name: {type: String, min: 1, max: 100, required: true}`
`},{collection: 'category'});`

`var ActivitySchema = Schema({`
 ` title: {type: String, min: 1, max: 100, required: true},`
 ` user: {type: Schema.ObjectId, ref: 'user', required: true},`
 ` category: {type: Schema.ObjectId, ref: 'category_activity', required: true}`
`},{collection: 'activity'});`

`var UserSchema = Schema({`
  `email: {type: String, min: 1, max: 100, required: true}`
`},{collection: 'user'});`

`module.exports = conn1.model('user', UserSchema)`
`module.exports = conn2.model('category_activity', CategorySchema)`
`module.exports = conn2.model('activity', ActivitySchema)`

**Comment by raghuveer-s** [comment]
I'm not entirely certain, but I think it might be because the model name in the schema constructor and the model retrieval methods are not matching. Try changing `conn2.model('category_activity', CategorySchema)` to `conn2.model('category', CategorySchema)` and see if that helps.

**Comment by emilhamep** [comment]
@raghuveer-s Thank you for you respond, I've tried your suggestion. But still doesn't work. The message says 'Schema hasn't been registered for model user'

**Comment by emilhamep** [comment]
Finally, I got the answer. The problem is they way how to populate them. I follow this approach to achive my purpose: https://stackoverflow.com/questions/36962294/mongoose-populate-schema-from-different-database
