### ISSUE TITLE
Running Aggregate over a mongoDB view returns no results

### ISSUE THREAD

**Issue by adylevy** [Automattic/mongoose#5525]
Node 7.9
Mongo 3.4
Mongoose 4.11.5

Hi
I have created a view in my mongo shell, setup a model using this line - 

const UsersFriends = mongoose.model('UsersFriends', usersFriendsSchema, 'usersFriends');

When I run find or any 'simple' call it works fine but when I try running aggergate with empty match, no other pipeline items I am getting no result.

running the debug output on my mongo shell works perfect - debug query:
db.usersFriends.aggregate([ { '$match': {} } ], {})

using this line: 
const res = await userFriendsModel.aggregate({ $match: {} })

I have tried to Profile mongo calls and the only diff i'm seeing (not sure if it's related) - 

"protocol" - "op_query" (using mongoose) vs "op_command" (using shell)

Please advise

**Comment by varunjayaraman** [comment]
not sure what youre doing wrong, this works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5525`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const usersFriendsSchema = new mongoose.Schema({
      name: String
    });

    const UsersFriends = db.model('UsersFriends', usersFriendsSchema, 'usersFriends');
    
    yield UsersFriends.remove({});
    
    yield UsersFriends.create([{ name: 'test-1' }, { name: 'test-2' }]);

    console.log(yield UsersFriends.aggregate([
      { $match: {} }
    ]));
  });
}
```

log output:
```
[ { _id: 59863860f0a5c1b563f96b35, name: 'test-1', __v: 0 },
  { _id: 59863860f0a5c1b563f96b36, name: 'test-2', __v: 0 } ]
```
