### ISSUE TITLE
pre-find, pre-findOne in nested schema plugins not executed

### ISSUE THREAD

**Issue by masterBrog** [Automattic/mongoose#5526]
looks like it's a similar issue to:
pre-save middleware not getting called on embedded schema #5437
Which has made pre-save work for me.

However, pre-find, pre-findOne hooks in plugins i'm applying to nested document schemas don't get applied. It does work on the parent as with the resolved issue above. I haven't got round to trying with other pre-hooks but maybe there are issues with them too?

mongoose v4.11.5
mongodb v2.2.30
node v8.1.3

Cheers for all the epic work on mongoose!

**Comment by varunjayaraman** [comment]
yeah i guess the reasoning is that the child schema isnt really the one with the `find` hook because the Model is on the parent doc, but I'm open to labelling this as a bug, what do you think @vkarpov15 ?

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5526`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

    const childSchema = new mongoose.Schema({
      age: Number
    });

    childSchema.pre('find', function(next) {
      console.log('running child schema pre hook'); // does not run
      next();
    });

    const schema = new mongoose.Schema({
      child: childSchema
    });

    schema.pre('find', function(next) {
      console.log('running parent schema pre hook');
      next();
    });

    const Model = db.model('Model', schema);

    const doc = yield Model.create({ child: { age: 24 } });

    yield Model.find();
  });
}
```

**Comment by masterBrog** [comment]
Yeah, I can see how this could go either way depending on your use case. I'm trying to write a plugin that applies redaction policies against any schema it's applied to (including subdocs) so for this use case it would be very useful. Cheers

**Comment by vkarpov15** [comment]
There's a few ways to work around this. The best way to do redaction in mongoose IMO is either using `select` in your schema: `age: { type: Number, select: false }`, or a post init hook:

```javascript
    const childSchema = new mongoose.Schema({
      age: Number
    });

    childSchema.post('init', function(next) {
      console.log('running child schema pre hook', this);
      this.age = null;
      next();
      return this;
    });
```

If you need something more sophisticated, you can also scan through the child schemas:

```javascript
    schema.childSchemas.forEach(({ schema }) => {
      console.log(schema.obj);
    });
```
