### ISSUE TITLE
Error messages cannot be overridden globally

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#5534]
Similar to how we can specify `mongoose.Promise = global.Promise`, we should be able to specify error messages globally, such as putting `mongoose.Error.messages.general.required = "The field {PATH} is required"` anywhere in our codebase.

Specifying this in one file, and then defining a schema in another results in the schema defined having the standard built-in error messages here <https://github.com/Automattic/mongoose/blob/e659958fe80c5d03a7cb89a4e43804c1dd3ddda2/lib/error/messages.js>.

As mentioned on [this line](https://github.com/Automattic/mongoose/blob/e659958fe80c5d03a7cb89a4e43804c1dd3ddda2/lib/error/messages.js#L5), it is suggested you can define them "globally", however `global.mongoose` is never defined, only `global.db` is in Mongoose.

cc @vkarpov15

**Comment by niftylettuce** [comment]
Ping @vkarpov15

**Comment by vkarpov15** [comment]
@niftylettuce the below script works as expected:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh5534`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

mongoose.Error.messages.general.required = 'Required fail!';

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({
    name: { type: String, required: true }
  }));

  await Model.create({}); // ValidationError: Test validation failed: name: Required fail!
}
```

Is there something else you're looking for?

**Comment by niftylettuce** [comment]
Yes @vkarpov15 - having to define the line `mongoose.Error.messages.general.required = 'Required fail!';` on every file that has a `require('mongoose');` in it is annoying

**Comment by niftylettuce** [comment]
I had to resort to doing this at the top of each file:

```js
const mongoose = require('mongoose');
Mongoose.error.messages = require('@ladjs/mongoose-error-messages');

// .. my schema definition
```

**Comment by niftylettuce** [comment]
I guess doing it global also would not permit each schema to have its own error messages - so perhaps some way to configure this would be nice.

**Comment by vkarpov15** [comment]
You don't have to put that line in every file you `require('mongoose')`. Remember that `require()` always returns a singleton, so you only need to set `mongoose.Error.messages` once, ideally right after the first time you `require('mongoose')`. What makes you think you need to set the message in every file?

If you want a specific error message for a given schema, you could do something like this:

```javascript
const schema = new Schema({
  str: {
    type: String,
    required: [true, 'My custom required message here']
  }
});
```
