### ISSUE TITLE
createConnection does not work with Promise.all()

### ISSUE THREAD

**Issue by jlyonsmith** [Automattic/mongoose#5540]
**Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug.

**What is the current behavior?**
If you use `createConnection` with the `useMongoClient` option a promise is returned that resolves with the connection object.  If you put returned promise inside a `Promise.all([ ... ])` to combine it with other Promises then when `Promise.all` resolves the connection object just a plain object, not a Mongoose connection.

**If the current behavior is a bug, please provide the steps to reproduce.**
The following ES6 script, when run with `babel-node` reproduces the behaviour:

```
import mongoose from 'mongoose'

mongoose.Promise = global.Promise
const p = mongoose.createConnection('mongodb://localhost/test', { useMongoClient: true })
Promise.all([ p ]).then((y) => {
  console.log(y.length)
  console.log(y[0])
})
```

**What is the expected behavior?**
That the value of `y` is an array containing a valid Mongoose connection object.

**Please mention your node.js, mongoose and MongoDB version.**
I'm running mongoose@4.11.6 and node@8.1.3

**Comment by daltones** [comment]
No. The expected behavior of your code is that `y` should be an array with a single element (mongoose connection instance).

I guess you're missing something...

**Comment by jlyonsmith** [comment]
My mistake.  You are correct, my statement about the return value was wrong.  My actual original problem was because I was using the wrong destructuring syntax in ES6 `const { conn, ... } = ...` instead of `const [ conn, ... ] = ...`.  

Closing the issue.  Sorry for the false report.
