### ISSUE TITLE
$text search in mongoose only looking for the first field

### ISSUE THREAD

**Issue by askri2pac** [Automattic/mongoose#5543]
I have a weird problem and I haven't been able to figure it out. I have an schema in mongoose with about 5 keys and I would like to use the $text query in 2 of them, it looks like this:

`var ProduitSchema = new Schema({
ref : { type: Number },
title: {type: String, default: 'nouveau produit'},
adresse: {type: String, default: null},
telephone: {type: String, default: null},
prestations: {type: String, default: null},...
`

and :  `ProduitSchema.index({ title: 1, adresse: 1});`

Then in my route file I perform the following query:

`ProduitSchema.find({$text: { $search: " \"my_query_text\" "}  } }, function (err,...`

if the word I enter into the query is a value that can be found in tkey "title" I get the correct result no problem, but If I enter a value that I know exist on one of the keys "adresse" my query turns up empty.

Any idea of why $text is not looking into the other keys I tried to index?

**Comment by varunjayaraman** [comment]
@askri2pac can you confirm it works with the correct way to set text indices?

**Comment by askri2pac** [comment]
yes i confirmed
