### ISSUE TITLE
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

### ISSUE THREAD

**Issue by deathlover** [Automattic/mongoose#5550]
Version : 
Node JS : 7.10.0
Mongoose : 4.11
Mongo : 3.4.1

` MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]`

Scenario : Trying to connect with remote server, with this URL

`mongoose.connection.openUri("mongodb://id:pass@ip/db)`

Dont know why it gets triggered on 127.0.0.1

Note: The server which is establishing the connection is a https based server. (is this is a issue?)

**Comment by varunjayaraman** [comment]
mongod is probably not running, did you check for that?
