### ISSUE TITLE
overriding schema.methods.toJSON not working when validation fails

### ISSUE THREAD

**Issue by fcastro16** [Automattic/mongoose#5552]
I'm trying to change the toJSON method, but it doesn't work when path validation fails because of a duplicate path already in the db. The error object contains three functions; toJSON, toString and getOperation.

The toJSON poses a security threat because it returns the document that already exists.
Let's say I'm trying to create a new user, if I enter a username that already exists the validation will fail, and the error object will return the existing user document with all its paths. 

Example 
```
{
    "code": 11000,
    "index": 0,
    "errmsg": "E11000 duplicate key error collection: ole.user index: email_1 dup key: { : \"email1@gmail.com\" }",
    "op": {
        "email": "email1@gmail.com",
        "password": "$2a$10$Mvgon/mjguAqRLUGLqoLRezvCpc6zTPWXmm.sU9JGYTjPiyQJ0Vbi",
        "_id": "5992bc6e5c3b2f0580fdf7d9",
        "tokens": [],
        "__v": 0
    }
}
```

The op property is what toJSON returns.
I know I could do something like the code below to fix it, but I think overriding the toJSON method during a failed path validation should work like it does when saving or updating a document.
I believe sending the original document should be removed completely from mongoose.

```
 if(_.has(error, "toJSON")){
      return res.status(400).send(_.omit(error, "toJSON"));
 }
```

**Comment by vkarpov15** [comment]
I don't understand your issue, can you please provide more detailed code samples?

**Comment by supperdsj** [comment]
have a Schema like this
`const UserSchema = new mongoose.Schema({
    email: {
        type: String,
        required: true,
        trim: true,
        minlength: 1,
        unique: true,
        validate: {
            // validator:(value)=>{
            //     return validator.isEmail(value);
            // },
            validator: validator.isEmail,
            message: '{VALUE} is not a valid email'
        }
    },
    password: {
        type: String,
        required: true,
        minlength: 6
    },
    tokens: [{
        access: {
            type: String,
            required: true
        },
        token: {
            type: String,
            required: true
        },

    }]
}, {
    usePushEach: true
});

UserSchema.methods.toJSON = function () {
    const user = this;
    const userObject = user.toObject();
    return {userObject.email,userObject._id};
};
`
and when i insert a user that email is already exist,will get result and 'UserSchema.methods.toJSON ' is not working

`
{
    "code": 11000,
    "index": 0,
    "errmsg": "E11000 duplicate key error collection: TodoApp.users index: email_1 dup key: { : \"2321717733@qq.com\" }",
    "op": {
        "email": "test@gmail.com",
        "password": "dsadsa",
        "_id": "5a3747e67242c915908185d4",
        "tokens": [],
        "__v": 0
    }
}
`
