### ISSUE TITLE
$where  bug

### ISSUE THREAD

**Issue by xiachaoxulu** [Automattic/mongoose#5554]
when i use query for a deep query,like follow:
<img width="677" alt="2" src="https://user-images.githubusercontent.com/12043917/29313446-a22ccc26-81ec-11e7-97d0-1033bee6c2a4.png">
i am sure, item is defined.
the result as follow, 
<img width="917" alt="3" src="https://user-images.githubusercontent.com/12043917/29313451-a4341484-81ec-11e7-9aac-60f3cdad6800.png">

**Comment by xiachaoxulu** [comment]
is scope chain miss cause that.?
if like that, how to compelete the functions like the pic

**Comment by bugall** [comment]
where are you defined the 'item'?  Can you show full-content?

**Comment by varunjayaraman** [comment]
is `item` defined in that scope?

**Comment by xiachaoxulu** [comment]
no , item is defined in global scope

**Comment by vkarpov15** [comment]
That's weird. Have you tried with `global.item`?

**Comment by varunjayaraman** [comment]
@vkarpov15 mongo probably wont have access to your app's proccess's `global` though when it executes your JS

**Comment by xiachaoxulu** [comment]
mongoose will transmit the function to mongodb，mongodb execute the function。 so，how to transmit the function？ ，must transmit the function  as pure string，by call the function's .toString method. that cause the function‘s scope chain break。 so ...

**Comment by vkarpov15** [comment]
Oh my mistake, I misunderstood the question. You need to stringify the function, so something like

```javascript
query.$where(`function() {
  return '${item.value}';
}`);
```

Note the back-ticks around the function. Probably the easiest way to do this, just be careful about using `where()` with queries unless you absolutely have to.

**Comment by varunjayaraman** [comment]
@xiachaoxulu can you confirm that works for you?
