### ISSUE TITLE
How to force a query to Reject a Promise so I can test the code?

### ISSUE THREAD

**Issue by cklanac** [Automattic/mongoose#5561]
I'm trying to create an integration test to check the `.catch()` condition similar to Issue #2680 where you override `.exec()` to throw an error to the callback. 

For simple queries I can override the `.find()` method to reject the Promise [see this gist](https://gist.github.com/cklanac/e0c895bf9c72484fb1172fea152c65cb), But this doesn't work when the query also includes subsequent filters like `.skip()` or `.limit()`.

I'm hoping to create a pattern that will work for a variety of queries like `.find(), `.findById()`, `.findByIdAndUpdate()` etc. Here's a sample of the kind of the endpoint and mongoose query I'm trying to test.

```js
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

router.get('/', (req, res) => {

  // setup and validation removed for brevity...

  Restaurant
    .find(criteria)
    .skip(pagination.page * pagination.limit)
    .limit(pagination.limit)
    .then(results => res.json(results) )
    .catch(err => res.status(500).json({ message: 'Internal server error' }) );
});
```

And here's the related test. So far I've tried overriding `.exec` and `.then` on the Model (shown below) as well as the `Model.Query.base`.

```
describe('Forced Mongoose errors.', function () {

  const _exec = Restaurant.exec;
  beforeEach(function () {
    Restaurant.exec = function () {
      return Promise.reject();
    };
  });
  afterEach(function () {
    Restaurant.exec = _exec;
  });
  it('should respond with a server error', function () {
    const spy = chai.spy();
    return chai
      .request(app)
      .get('/restaurants')
      .then(spy)
      .catch((err) => {
        const res = err.response;
        res.should.have.status(500);
      })
      .then(() => {
        spy.should.not.have.been.called();
      });
  });
}); 
```

I'm using Node 6.11.1 and Mongoose: 4.11.6.
Any help would be appreciated.

**Comment by varunjayaraman** [comment]
i suppose you could do this in a `post` find hook or something but i would say this is generally a bad idae to only do in your tests and i would recommend stubbing out a different function after the find or something to throw the error

**Comment by varunjayaraman** [comment]
you could also pull the query itself into another function and stub that method out to throw an error

**Comment by cklanac** [comment]
I like the idea of wrapping the query in a function and stubbing it out to throw an error. thanks

**Comment by varunjayaraman** [comment]
no worries

**Comment by vkarpov15** [comment]
Another strategy I've used in the past is making a sinon stub that returns an object which has the chainable methods stubbed out. Kinda hacky but gets the job done.
