### ISSUE TITLE
Promise.all and populated issue

### ISSUE THREAD

**Issue by akaNightmare** [Automattic/mongoose#5564]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const testSchema = new mongoose.Schema({
  users: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    require: true,
  }],
});
testSchema.method('getTestActiveUsers', async function () {
  if (!this.populated('users')) {
    await this.populate('users').execPopulate();
  }
    return _.filter(this.users, { status: 'ACTIVE' };
});
testSchema.method('getTestInactiveUsers', async function () {
  if (!this.populated('users')) {
    await this.populate('users').execPopulate();
  }
  return _.reject(this.users, { status: 'ACTIVE' };
});
const Model = mongoose.model('Test', testSchema);
const [testActiveUsers, testInactiveUsers] = await Promise.all([
  Model.getTestActiveUsers(),
  Model.getTestInactiveUsers(),
]);
```
**What is the current behavior?**
Population for `Model.getTestActiveUsers(),` - is OK, and I see filtered populated users
Population for `Model.getTestInactiveUsers(),` - is not OK, users are not populated and I don't see filtered populated users.
**What is the expected behavior?**
Both population should work.

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 8.2.1
Mongoose: 4.11.7

**Comment by varunjayaraman** [comment]
you aren't returning the promises in your `methods`. you should also return `Promise.resolve()` invoked on the return values after the `if` checks so that your function consistently returns a promise

**Comment by akaNightmare** [comment]
@varunjayaraman added `async`

**Comment by varunjayaraman** [comment]
how are you testing if it is populated? Are you logging the returned object from the `method`? You still aren't returning the promise that is `await`ed

**Comment by akaNightmare** [comment]
@varunjayaraman for `Model.getTestActiveUsers()` I see
```js
[
  { _id: 'id1', users: [ { _id: 'id11', status: 'status' }, { _id: 'id13', status: 'status' }, { _id: 'id13', status: 'status' } ] },
]
```
for `Model.getTestInactiveUsers()` - 
```js
[
  { _id: 'id1', users: [ 'id11', 'id12', 'id113', ] },
]
```

**Comment by akaNightmare** [comment]
@varunjayaraman it doesn't matter, if function has `async` operator, and this function **always** will return a promise.

**Comment by varunjayaraman** [comment]
Oh I see, I misunderstood what you were trying to do with the async methods. The point I was trying to make was that if you dont return the awaited promise, the returned object wouldnt be populated, but I see that you are mutating the document and returning an array of `this.users` anyway, so my point is moot, my bad.

Anyway, I'll take a look at this when I'm on my personal computer, but does `this.populated` return false for you if you log it out?

**Comment by akaNightmare** [comment]
@varunjayaraman the reason why it happens:
Promise.all() -> runs function in parallel, and for first function is OK, but for second it's already populated, but no data.

**Comment by varunjayaraman** [comment]
do you think it might be because you are concurrently running 2 async methods that mutate `this`? so `!this.populated` might be true for one of the 2 async conditions (aka there might be a race condition)?

**Comment by akaNightmare** [comment]
@varunjayaraman yes

**Comment by vkarpov15** [comment]
Mongoose currently marks a path as populated before the async `populate()` is done, :point_up: fixes that. Be careful about the pattern you're using though, that will do the same exact populate twice.
