### ISSUE TITLE
 DeprecationWarning: `open()` is deprecated in mongoose

### ISSUE THREAD

**Issue by pankaja92** [Automattic/mongoose#5565]
Nodejs version : v8.0.0
Mongodb version : 3.2.16
Mongoose version : 4.11.7

According to mongoose official document [here](http://mongoosejs.com/docs/index.html) I connected mongodb in my API 

`mongoose.connect('mongodb://localhost:27017/myapp');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  console.log("Database is connected");
});
`

db.once function is running. But I'm getting the below error as well.

**(node:7648) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client**

Is it a bug or the documentation is outdated ?

**Comment by varunjayaraman** [comment]
you are supposed to pass `useMongoClient: true` to your connection options (it says it in the error message, but I'll show you the text from the docs itself anyway):

```
Mongoose's default connection logic is deprecated as of 4.11.0. Please opt in to the new connection logic using the useMongoClient option, but make sure you test your connections first if you're upgrading an existing codebase!
```

**Comment by BooMiny** [comment]
(node:2756) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, us
e `openUri()` instead, or set the `useMongoClient` option if using `connect()` o
r `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mong
o-client
