### ISSUE TITLE
How to run validators for null and undefined values?

### ISSUE THREAD

**Issue by binki** [Automattic/mongoose#5569]
**Do you want to request a *feature* or report a *bug*?**

bug.

**What is the current behavior?**

As defined in [the documentation](http://mongoosejs.com/docs/validation.html):

> Validators are not run on undefined values. The only exception is the [`required` validator](http://mongoosejs.com/docs/api.html#schematype_SchemaType-required).

This means that it is impossible to write a validator that allows `null` but disallows `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

I attempt to use a validator to disallow `undefined` and can’t: https://gist.github.com/binki/cf735173ac4c5b17376f8f69c846a558

I follow [the instructions offered on SO to workaround this by setting `required` to a function](https://stackoverflow.com/a/44336895/429091), but I find this doesn’t work for subdocuments: https://gist.github.com/binki/8d262eda2134756e695ecf5e3253450a

**What is the expected behavior?**

To have validators be less of a special case and run for everything consistently so that I can disallow `undefined` and require `null`.

**Please mention your node.js, mongoose and MongoDB version.**

```
ohnob@DESKTOP-A4G2C0J MSYS ~/repos/mongoose-validators-hard-to-use
$ node --version
v6.11.1

ohnob@DESKTOP-A4G2C0J MSYS ~/repos/mongoose-validators-hard-to-use
$ npm list mongoose
mongoose-validators-hard-to-use@1.0.0 C:\Users\ohnob\repos\mongoose-validators-hard-to-use
`-- mongoose@4.11.7  extraneous

npm ERR! extraneous: mongoose@4.11.7 C:\Users\ohnob\repos\mongoose-validators-hard-to-use\node_modules\mongoose
```

**Comment by varunjayaraman** [comment]
i think the problem is when you do `this.someProp = undefined`, mongoose will unset the field so then it wont even run the validator on it.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');

const ThingSchema = new mongoose.Schema({
  // https://stackoverflow.com/a/44336895/429091, doesn’t support
  // subdocuments.
  undefinedDisallowed: {
    type: String,
    valiate: {
      validator: function (v) {
        return v !== undefined;
      },
    },
    default: null,
  },
});

const Thing = mongoose.model('Thing', ThingSchema);

const thing = new Thing();
assert.ifError(thing.validateSync());
console.log(thing);
thing.undefinedDisallowed = undefined;

console.log(thing);
assert.ok(thing.validateSync());
```

**Comment by vkarpov15** [comment]
Your second gist helped us identify a bug that should now be fixed in master :+1: :point_up: . That gist should work when we release 4.11.10 this week.

Also, as per my comments on SO, I recommend you do this instead:

```javascript
const SuperDocumentSchema = new mongoose.Schema({
  thing: {
    type: ThingSchema,
    // https://stackoverflow.com/q/35494875/429091
    default: () => ({}), // <-- make the default an empty object so you don't get a mess
  },
});
```
