### ISSUE TITLE
Configuration to disable inclusion of embedded document schema index definitions

### ISSUE THREAD

**Issue by randypuro** [Automattic/mongoose#5575]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When embedding a schema type, the parent type automatically adopts all the embedded type indexes at the given path.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Would love to have a global configuration option (or schema configuration option) that determines whether or not a parent adopts the path relative index definitions of the embedded children.

We frequently have schemas for documents that are stored both in their own collection as well as embedded in other collections. We would like to be able to define indexes for this schema that apply in it's collection, but not when it's embedded in other collections.

**Please mention your node.js, mongoose and MongoDB version.**
 node 8, mongoose 4, mongoose 3.2

**Comment by vkarpov15** [comment]
Can you please provide some code samples? I don't quite understand the feature request.

**Comment by randypuro** [comment]
Sorry for the delay:

```
const vendorSchema = new mongoose.Schema({
  name: {type: String, index: true},
});

const Vendor = mongoose.model('Vendor', vendorSchema);

const productSchema = new mongoose.Schema({
  vendor: {type: vendorSchema},
});

const Product = mongoose.model('Product', productSchema);
```

The current behavior is to create the `name` index for the vendors collection, and the `vendor.name` index in the products collection. But in our case, we do NOT want the `vendor.name` index in the products collection. We do this fairly often (embed documents from one collection into another), and almost never want the index definitions when embedded; so not sure what api makes the most sense to disable this behavior - global config, at the definition of the embedded document property, or on the definition of the embeddable document property index, but any of those would work for us. Does this make sense?

**Comment by vkarpov15** [comment]
Yeah that makes sense. Here's an alternative suggestion: we already have a [`schema.clone()` function](http://mongoosejs.com/docs/api.html#schema_Schema-clone), so how about something like this?

```javascript
const vendorSchema = new mongoose.Schema({
  name: {type: String, index: true},
});

const Vendor = mongoose.model('Vendor', vendorSchema);

const embeddedVendorSchema = vendorSchema.clone().removeIndexes();

const productSchema = new mongoose.Schema({
  vendor: {type: embeddedVendorSchema},
});

const Product = mongoose.model('Product', productSchema);
```

We would just need a function to remove indexes from a schema.

**Comment by randypuro** [comment]
We could make that work, but I think it's perhaps less than ideal? Generally, we almost never want the indices from the child schema on the parent, and having them by default simply causes extra storage and write costs in our db. I can't help but feel it would be better if we could do something at embed declaration time. Like:

```
const productSchema = new mongoose.Schema({
  vendor: {type: VendorSchema, includeIndices: false},
});
```

Also, I'll have to look further, but I believe deeply nested schemas, when creating nested indices, create them incorrectly on the root schema.

**Comment by vkarpov15** [comment]
If the latter is the case, that's definitely a bug. I like your feature suggestion, the `includeIndices` option seems like the way to go. Thanks.

**Comment by armaserg** [comment]
Hello. Does it work now?
There is no documentation about this: https://mongoosejs.com/docs/search.html?q=excludeIndexes :(

I have such schemas:
```
const TechnologySchema: Schema = new Schema({
  name: {type: String, unique: true, excludeIndexes: true}
}, {excludeIndexes: true});

const ProjectSchema: Schema = new mongoose.Schema({
  name: String,
  technologies: [TechnologySchema],
}, {excludeIndexes: true});
```
But in 'projects' collection I still have 'technologies.name' unique index :(

How can I prevent this?
thanks!
