### ISSUE TITLE
the Schema default value does not work for  while using Model.bulkWrite updateOne  upsert

### ISSUE THREAD

**Issue by koiszzz** [Automattic/mongoose#5577]
Here is my code below:

> `var RoleSchema = Schema({`
 `   name: String,`
`role: String,`
`    createTime: {type:Date, default: Date.now()},`
`    lastUpdateTime: Date,`
`    isDeleted: {type:Boolean, default:false},`
`   deleteTime: Date,`
`});`
`var RoleModel = mongoose.model('role', RoleSchema);`
`     `
`RoleModel.bulkWrite(['`
`{updateOne: {`
`             filter: {name:'somebody'},`
`            update: {name:'somebody',role:'admin'},`
`            upsert: true,`
`}},`
`{updateOne: {`
`            filter: {name:'nobody'},`
`            update: {name:'nobody',role:'normal'},`
`            upsert: true,`
`}},`
>`]);`

When i  execute code above, the datas what I insert miss the createTime and isDeleted property. It seems that default value not working for this situation. What is the proper way to do batch saveorupdate? Help

**Comment by vkarpov15** [comment]
Right now `bulkWrite()` does not set defaults with `updateOne`. `replaceOne` will work if you don't mind that other fields will get overwritten. If that doesn't work, you need to use `updateOne` and turn on the `setDefaultsOnInsert` option: `RoleModel.updateOne({ name: 'somebody' }, { $set: {name: 'somebody', role: 'admin' } }, { upsert: true, setDefaultsOnInsert: true })` and do this for every doc you want to update.

**Comment by vkarpov15** [comment]
I'm going to close this. Recommended approach is to set `setDefaultsOnInsert` in your [`updateOne` in `bulkWrite()`](https://mongoosejs.com/docs/api.html#model_Model.bulkWrite) like you would `upsert`:

```javascript
Model.bulkWrite([{
  updateOne: {
    filter: { num: 0 },
    update: {
      $inc: { num: 1 }
    },
    upsert: true,
    setDefaultsOnInsert: true
  }
}]);
```
