### ISSUE TITLE
Mongoose.Types.ObjectId call is not consistant.

### ISSUE THREAD

**Issue by ndaljr** [Automattic/mongoose#5579]
**Do you want to request a *feature* or report a *bug*?**
Report a bug. 

**What is the current behavior?**
I work on a node app that has to interface with a python process. The requirements given to me 
is that `_id's` have to be converted to a string. As such, when I call new on a model and I pass it a function call to ObjectId, it sometimes works and sometimes throws a duplicated key error. 

Here is my model. 

```
const userSchema = new Schema(
  {
    _id: {
      type: String,
    },
    email: {
      type: String,
      required: [true, THIS_FIELD_IS_REQUIRED],
      unique: true,
      validate: {
        validator: value => isEmail(value),
        message: INVALID_EMAIL_ADDRESS,
      },
    },
    is_email_verified: {
      type: Boolean,
      default: false,
    },
    encryption_keys: [
      {
        type: String,
        ref: "Encryption_Key",
      },
    ],
    password: {
      type: String,
      required: [true, THIS_FIELD_IS_REQUIRED],
      minlength: [8, SHORT_PASSWORD],
    },
    password_last_updated: {
      type: Date,
      default: new Date(),
    },
    password_attempts_count: {
      type: Number,
      default: 0,
    },
    is_account_locked: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  },
);
```

And in my controller I instantiate a new instance of a model like this. 
```
    user = new User({
      _id: mongoose.Types.ObjectId().toString(),
      email,
      password: hashedPassword,
    });
    await user.save();

```

**If the current behavior is a bug, please provide the steps to reproduce.**

The save operation fails sometimes citing duplicated key error. To fix this. I have to do this.

```
    const _id = mongoose.Types.ObjectId().toString(); // <--- Note the extra variable here
    user = new User({
      _id,
      email,
      password: hashedPassword,
    });
    await user.save();

```
**What is the expected behavior?**
I want to be able to save  my model without having to make a variable for a generated object id. Is the behaviour of `mongoose.Types.ObjectId().toString()` asynchronous? Is this a bug or is this intended?

**Please mention your node.js, mongoose and MongoDB version.**
Node version: 8.4.0
Mongoose version: 4.11.8
MongoDB version: 3.2.16

**Comment by vkarpov15** [comment]
That's very strange, the latter should not be any different from the former. The `ObjectId()` call is definitely not async, and a quick spot check in the node shell shows that we get different ids each time:

```
$ node
> const mongoose = require('mongoose')
undefined
> [mongoose.Types.ObjectId().toString(), mongoose.Types.ObjectId().toString(), mongoose.Types.ObjectId().toString(), mongoose.Types.ObjectId().toString(), mongoose.Types.ObjectId().toString()]
[ '59a4b80d70d03b24acfb78bf',
  '59a4b80d70d03b24acfb78c0',
  '59a4b80d70d03b24acfb78c1',
  '59a4b80d70d03b24acfb78c2',
  '59a4b80d70d03b24acfb78c3' ]
> 
(To exit, press ^C again or type .exit)
> 
$ 
```

Can you provide a script that reproduces your issue? Below script seems to work as expected for me:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test');

const userSchema = new mongoose.Schema({
  _id: {
    type: String
  }
});

const User = mongoose.model('Test', userSchema);

run().catch(error => console.error(error));

async function run() {
  for (let i = 0; i < 1000; ++i) {
    let user = new User({
      _id: mongoose.Types.ObjectId().toString()
    });
    await user.save();
  }

  console.log('done');
}
```
