### ISSUE TITLE
When using timestamps option, embeded documents and default values are not retrieved

### ISSUE THREAD

**Issue by cacilhas** [Automattic/mongoose#5581]
BUG

When I use the `timestamps` option on schema creation, the retrieved documents return `undefined` for embeded documents (the data are in the MongoDB, but Mongoose returns `undefined`), and fields with default value doesn’t take advantage of it – also return `undefined` if there is no data in MongoDB.

**Comment by vkarpov15** [comment]
Please provide code samples
