### ISSUE TITLE
text search fails even though text index exists

### ISSUE THREAD

**Issue by clement2705** [Automattic/mongoose#5582]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
the text index creation does not work

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const MockSchema = new mongoose.Schema({
  person: {
    type: {
      embeddedSchema
    }
  },
  tags: {
    type: [String]
  }
});

MockSchema.index({ tags: 1 });

MockSchema.index(
  { 'person.name': 'text' },
);
```
gives me a error message: Unhandled promise rejection (rejection id: 1): MongoError: text index required for $text query

if I create the indexes in the other order I don't get an error statement
```javascript
MockSchema.index(
  { 'person.name': 'text' },
);
MockSchema.index({ tags: 1 });
```

**What is the expected behavior?**
Sequence of text index definition should not matter

**Please mention your node.js, mongoose and MongoDB version.**
mongoose version 4.11.8

node version 8.1.3

mongoDB version 3.4.5

**Comment by vkarpov15** [comment]
Sounds like your index build is failing for some reason. Can you please [enable the `emitIndexErrors` option](http://mongoosejs.com/docs/guide.html#emitIndexErrors) and post the error that you get, if any? I suspect you have a conflicting index on `tags`
