### ISSUE TITLE
using findOne() with an undefined value returns the first document and not an error

### ISSUE THREAD

**Issue by mansona** [Automattic/mongoose#559]
The code I'm using is: 

LoginModel.findOne({'fbLogin.userID' : req.body.id}, function(err, doc){
    //Here err is null and doc is the first (and only) object in the collection used by the LoginModel. 
});

Please note that req.body.id is undefined. 

I would expect this to thow an error. I tried the same thing using the mongo client and I get the following error: 

> db.logins.find({'fbLogin.userId': undefined})
> error: { "$err" : "can't have undefined in a query expression", "code" : 13629 }

This seems like an inconsistency between mongo and mongoose.

**Comment by hasumashi** [comment]
I've also faced the same problem, it's very dangerous. I was writing authentication for my application and by mistake I was looking for undefined value in findOne which caused that some user got data from another person.
