### ISSUE TITLE
Intermittent failures when running tests

### ISSUE THREAD

**Issue by kevinburke** [Automattic/mongoose#5595]
Running the current tip of `master` (commit 5dac9c6) in Travis CI occasionally yields the following errors:

```
1) validation docs The `unique` Option is Not a Validator:
     Uncaught MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: mongoose_test.u1.$username_1  dup key: { : "Val" }
      at Function.MongoError.create (node_modules/mongodb-core/lib/error.js:31:11)
      at toError (node_modules/mongodb/lib/utils.js:139:22)
      at node_modules/mongodb/lib/collection.js:669:23
      at handleCallback (node_modules/mongodb/lib/utils.js:120:56)
      at node_modules/mongodb/lib/bulk/unordered.js:465:9
      at handleCallback (node_modules/mongodb/lib/utils.js:120:56)
      at resultHandler (node_modules/mongodb/lib/bulk/unordered.js:413:5)
      at node_modules/mongodb-core/lib/connection/pool.js:469:18
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

```
  1) model: populate: across DBs:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

An example failing Travis build can be found here: https://travis-ci.org/kevinburke/mongoose/builds/269445303. Those errors seem to occur randomly across Node versions (the first one I got on Node 5 and iojs but no others), making me think it's more a problem with the tests than with Node.

Updates #5594.

**Comment by vkarpov15** [comment]
Yeah it is very likely a test issue. The unique validator one is new, we'll look into that. Occasional timeouts have always happened in Travis across different projects, so I think a more long term solution would be to switch off travis

**Comment by kevinburke** [comment]
I think we should reopen this, since the CL you merged still had a failing build
