### ISSUE TITLE
Fields not matched in population return null

### ISSUE THREAD

**Issue by Slaventsiy** [Automattic/mongoose#5596]
**Do you want to request a *feature* or report a *bug*?**
Not sure whether this is intended.

**What is the current behavior?**
Returns
`{
    "__v": 0,
    "_id": "59a536f4ea0d2256653e77e1",
    "userFleets": [
        {
            "fleet": {
                "_id": "59a536f4ea0d2256653e77df",
                "name": "Populatable",
                "__v": 0
            }
        },
        {
            "fleet": null
        }
    ]
}
`

**If the current behavior is a bug, please provide the steps to reproduce.**
[Test to reproduce](https://gist.github.com/Slaventsiy/b2c52c1dc235c958e51ae9ee2779b83a
)

**What is the expected behavior?**
Returns
`{
    "_id": "59a536f4ea0d2256653e77e1",
    "userFleets": [
        {
            "fleet": {
                "_id": "59a536f4ea0d2256653e77df",
                "name": "Populatable",
                "__v": 0
            }
        },
        {
            "fleet": "59a536f4ea0d2256653e77dg"
        }
    ]
}
`

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.2.0
Mongoose 4.11.9
MongoDB 3.4

**Comment by vkarpov15** [comment]
This is expected behavior. Mongoose will set the property to `null` if it can't find the document you're trying to populate. If you want the original `_id`, `doc.populated('userFleets.fleet')` will be an array that contains the original `_id`'s.
