### ISSUE TITLE
Convert string IDs to object IDs in aggregations and bulk ops

### ISSUE THREAD

**Issue by QuotableWater7** [Automattic/mongoose#5597]
**Feature**
-------
**What is the current behavior?**
Queries like `find`, `update`, etc work when you pass a string, as mongoose will automatically convert the string to an object ID.  Currently, I have to convert strings to objectIds for aggregations and bulk ops manually, and the times I've forgotten to do this have resulted in some lost hours trying to figure out why a query isn't working.

**What is the desired behavior?**
Convert strings to IDs in all types of queries

**Please mention your node.js, mongoose and MongoDB version.**
Node v6.11.1
Mongoose v4.9.10
Mongo DB v3.0.8

**NOTE**: I am 100% happy to write the code to make this happen, I just wanted to get the OK from you guys.

**Comment by vkarpov15** [comment]
Bulk ops sure, aggregations no. Aggregate can transform the shape of the data, so mongoose schemas don't necessarily apply. We could maybe support casting the first stage in the pipeline if its `$match`, but that seems like a very brittle API. Also, I think we already do casting for bulk ops (`bulkWrite()`), have you found a case where we don't?

**Comment by vkarpov15** [comment]
@QuotableWater7 any more info re: casting for bulkWrite?

**Comment by QuotableWater7** [comment]
@vkarpov15 thanks for your replies and sorry for the delay!

> We could maybe support casting the first stage in the pipeline if its $match, but that seems like a very brittle API

100% agree with you here on both the reasons for not casting, and also that casting the first stage feels brittle / awkward.

> I think we already do casting for bulk ops 

I just verified locally that there is no casting for bulk ops.  I'll take a look at the difficulty in adding casting there.

**Comment by vkarpov15** [comment]
Can you provide code samples for that you mean by bulk ops? `Model.bulkWrite()` definitely casts

**Comment by QuotableWater7** [comment]
@vkarpov15 I think this is another case where we used the deprecated `initializeUnorderedBulkOp` instead of `bulkWrite`, so I'll close this issue.  Thanks 😄
