### ISSUE TITLE
Unique indexes not working

### ISSUE THREAD

**Issue by diogobaeder** [Automattic/mongoose#56]
Hi, I'm trying to use model indexes with unique properties, but it's not working as expected by the native ensureIndex method from MongoDB. This is a sample of my model code:
    indexes: [
        [{username: 1}, {unique: true, dropDups: true}]
    ],
the instance save calls are generating subsequential records in the base.

**Comment by alexbooker** [comment]
I am having this issue now.

**Comment by vkarpov15** [comment]
@alexbooker please provide more information and open up a new issue

**Comment by kaasdude** [comment]
It this still an issue?
Mongoose version: 4.9.3

**Comment by SagnikH** [comment]
[https://stackoverflow.com/a/10167170/13962659](url)

This helped me with the problem of creating unique constraints on secondary index fields.
