### ISSUE TITLE
"refPath" doesn't work for virtuals?

### ISSUE THREAD

**Issue by miliu99** [Automattic/mongoose#5602]
I love the "refPath" instead of "ref" for dynamic population. This works great.
```
    var activitySchema = new Schema({
        refId: {type: Schema.ObjectId, refPath: 'refKind'},
        refKind: String
    };
```

However, I don't like to share the same field "refId" for either id or the object. So, I found a great solution using virtuals. However, to my dismal, the "refPath" doesn't seem to work for virtuals, although "ref" works.

  ```
  var activitySchema = new Schema({
        refId: {type: Schema.ObjectId},
        refKind: String
    }, { _id: false, toObject: {virtuals: true}, toJSON: { virtuals: true }});
    activitySchema.virtual('refObj', {refPath: 'refKind', localField: 'refId', foreignField: '_id', justOne: true});
```

I understand that nothing is mentioned in the document about using refPath in virtuals, so I'm not sure if this is just not supported or a bug. Here is something I tried that doesn't work. Any clue?

Oh, I'm using v4.10.8. Not sure if it is working in 4.11.9 because I run into other problems (DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `
useMongoClient` option if using `connect()` or `createConnection()`.) when trying to use the latest version, so I have to roll back.

**Comment by vkarpov15** [comment]
Definitely a feature we need to add, thanks for the suggestion.

Also, to get rid of the warning add `useMongoClient: true`, like `mongoose.connect(MONGO_URI, { useMongoClient: true })`

**Comment by vkarpov15** [comment]
In order to be more consistent with the API for #5704, defaults, etc. we'll instead support setting `ref` to a function in your virtual with the doc as the context. So instead of:

```javascript
  activitySchema.virtual('refObj', {refPath: 'refKind', localField: 'refId', foreignField: '_id'});
```

You will have to do

```javascript
activitySchema.virtual('refObj', {ref: function() { return this.refKind; }, localField: 'refId', foreignField: '_id'});
```

Should make for a cleaner API, we'll consider doing this for regular refPath as well.

**Comment by vkarpov15** [comment]
@p3x-robot I don't understand your question, can you please clarify with some code samples?

**Comment by vkarpov15** [comment]
@p3x-robot I opened up a new issue to track this :point_up:
