### ISSUE TITLE
Express Request hangs after mongoose disconnect

### ISSUE THREAD

**Issue by FeaRCODE** [Automattic/mongoose#5604]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?** 
When `bufferCommands` is set to false, and mongoose fails to connect, any request/query will immediately throw an error that can be caught with a try/catch. However, if the connection is dropped (mongod service stopped) the disconnect event fires, and any query after that hangs. Shouldn't `bufferCommands` keep this from happening? I am relatively new to MongoDB and mongoose.

I also noticed auto reconnect doesn't work if the initial connection fails.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create schema with `bufferCommands: false`

2. Start the `mongod` service and run a query (should be successful) 

3. Stop mongod and try to query. Notice how the request hangs instead of throwing an error.
![image](https://user-images.githubusercontent.com/6901336/29910719-99d94db4-8df0-11e7-90e5-0225aede3e19.png)

database.js
```javascript
module.exports = () => {
    const mongoose = require("mongoose");
    mongoose.connect(process.env.DBUri, {
        useMongoClient: true,
        authSource: "admin",
        autoReconnect: true,
        reconnectTries: Number.MAX_VALUE,
        reconnectInterval: 3000
    });

    mongoose.Promise = Promise; // yea... this is kinda odd 

    mongoose.connection.on("connected", () => {
        console.log("Connection Established");
    });

    mongoose.connection.on("reconnected", () => {
        console.log("Connection Reestablished");
    });

    mongoose.connection.on("disconnected", () => {
        console.log("Connection Disconnected");
    });

    mongoose.connection.on("close", () => {
        console.log("Connection Closed");
    });

    mongoose.connection.on("error", (error) => {
        console.log("ERROR: " + error);
    });
    return mongoose;
};
```

**What is the expected behavior?**
Mongoose should throw an error instead of hang/buffer commands when the app gets disconnected from the database. Also, `mongoose.connection.readyState` doesn't seem to change on disconnect.

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 8.4.0
Mongoose: 4.11.9
MongoDB: 3.4.6

**Comment by vkarpov15** [comment]
Thanks for reporting this issue, will investigate ASAP.

**Comment by vkarpov15** [comment]
Almost right. The node driver also does its own buffering, to disable that you need to set `bufferMaxEntries` to 0 when using `mongoose.connect()`. We've confirmed that `connection.readyState` doesn't change, will fix that. Here's a script where the query fails fast when mongodb is disconnected, note that you need to set both `bufferCommands` on the schema level to false **and** `bufferMaxEntries` to 0 on the connection level.

```javascript
const mongoose = require('mongoose');
mongoose.Promise = Promise; 

mongoose.connection.on("connected", () => {     
  console.log("Connection Established");
});

mongoose.connection.on("reconnected", () => {
  console.log("Connection Reestablished");
});

mongoose.connection.on("disconnected", () => {
  console.log("Connection Disconnected");
});

mongoose.connection.on("close", () => {
  console.log("Connection Closed");
});

mongoose.connection.on("error", (error) => {
  console.log("ERROR: " + error);
});

var nodeSchema = new mongoose.Schema({}, { bufferCommands: false });
var Node = mongoose.model('Node', nodeSchema);

run().catch(error => console.error(error));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useMongoClient: true,
    autoReconnect: true,
    reconnectTries: 1000000,
    reconnectInterval: 3000,
    bufferMaxEntries: 0 // Disable node driver's buffering as well
  });

  while (true) {
    console.log('Query', await Node.findOne());
    await new Promise(resolve => setTimeout(() => resolve(), 2000));
  }
}
```
