### ISSUE TITLE
Can I have some discriminators in a different collection?

### ISSUE THREAD

**Issue by miliu99** [Automattic/mongoose#5608]
I use discriminators for sharing some comment fields sometimes, not because they are parent-children in nature. So, because of this, putting them all in one collection doesn't make much sense. I don't need to query across different types. I'm also worried that put a lot of things in one collection may hurt the performance later on. So, can I have a separate collection for some?

I understand I can share some fields using schema sharing, but I don't like it somehow.

**Comment by miliu99** [comment]
Okay, I found this stackoverflow question [https://stackoverflow.com/questions/35361297/inheriting-mongoose-schemas](url)...so it appears I should use mongoose-extend-schema instead of discriminators, right?

**Comment by vkarpov15** [comment]
Yes use https://github.com/doasync/mongoose-extend-schema . I would strongly recommend using mongoose-extend-schema rather than [mongoose-schema-extend](https://www.npmjs.com/package/mongoose-schema-extend), be careful not to mix the two up.
