### ISSUE TITLE
Unable to find data from an Object id

### ISSUE THREAD

**Issue by Gianolag** [Automattic/mongoose#5611]
I have a User collection, it has a company field that is a reference to another collection called Company.
then i assign the company to the user. when i try to print the data inside the company field it returns me : undefined.

this is the code that i use, 
```
console.log('company: ' + req.user.company); 
if(req.user.company) 
   console.log("LOGGED IN USER" + "\n Email:" + req.user.username + "\n Psw: " + req.user.password + "\n Role: " + req.user.role + "\n Company: " + req.user.company.name);
```

and this is the response on the terminal:
```
company: 59aab09745db5532c4321742
LOGGED IN USER
 Email:user@admin.com
 Psw: $2a$10$Z7h3ikaDJLhLXMotV.odaerGf5RFRXxDmlVxCFdvTaL48WalNIwRy
 Role: admin
 Company: undefined
```

as you can see the first terminal line shows the company id assigned to that particular user, but when i try to print the name of that company it returns undefined.

this is the Company collection entry, it has the name field and the object id is the same as i print above

![image](https://user-images.githubusercontent.com/12983292/29996366-8b5b7a3c-8ffd-11e7-95f7-eb097b9e3084.png)

where am i wrong?
thank you

**Comment by vkarpov15** [comment]
Can you show your schemas please?
