### ISSUE TITLE
model.findOneAndUpdate falsly refers to findAndModify

### ISSUE THREAD

**Issue by japrescott** [Automattic/mongoose#5616]
I was debugging some performance bottlenecks in my app and noticed that a model.findOneAndUpdate actually triggers findAndModify. This causes mongodb to read/write lock way more since it could affect many documents instead of the assumed "atomic" operation.

refering to the mongodb driver, [findAndModify is deprecated](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#findAndModify).

Is there a specific reason mongoose doesn't use this feature which was introduced with MongDB 3.2? Or is it solely for backwards compatibility?

**Comment by japrescott** [comment]
with further analysis, i've found out that the native mongodb driver also uses[ findAndModify under the hood](https://github.com/mongodb/node-mongodb-native/blob/7cb2b7dcfc3bd5fdcbfff56883df3c809f3e5aa3/lib/collection.js#L2378). I find this very strange as [mongoDB 3.2+ has a native findOneAndUpdate function](https://docs.mongodb.com/v3.4/reference/method/db.collection.findOneAndUpdate/) which I assume is more performant. Why aren't we using it?

**Comment by vkarpov15** [comment]
We are going to switch over for the next backwards breaking release. Haven't done so yet because mongoose 4.x supports back to mongodb 2.4

**Comment by Root-Core** [comment]
@vkarpov15 Mongoose 5.x still seems to rely heavily on `findAndModify()`, but does not support MongoDB  2.x. Will the 5.x releases see an update on this topic? It looks like a natural change to do.

I'm implementing mongoose drivers for some other databases than MongoDB and none of them support `findAndModify()`. This makes things _way_ more complex, without implementing `findAndModify()` in these databases.

**Comment by vkarpov15** [comment]
Thanks for pointing this out, we missed this one for 5.0.0. We will add a flag to support this ASAP

**Comment by vkarpov15** [comment]
In 5.0.7 you'll be able to do `mongoose.set('useFindAndModify', false)` to opt in to using native `findOneAndUpdate()` as opposed to `findAndModify()`.

**Comment by ranjanasinha89** [comment]
> useFindAndModify

So I tried using this **mongoose.set('useFindAndModify', false)**. It doesn't update, but it returns success as null. Any idea whats going on?

**Comment by lineus** [comment]
@ranjanasinha89 what are your versions of
   1. mongoose
   1. node
   1. mongodb server

**Comment by ranjanasinha89** [comment]
@lineus I got it to work. It was some other silly thing, that was creating the problem. Thanks for the promt reply though.
