### ISSUE TITLE
Can't change collection name - v4.11.9 - latest build

### ISSUE THREAD

**Issue by nemanjapetrovic** [Automattic/mongoose#5617]
Hi, I am using the latest version of mongoose (4.11.9) and I am having some trouble to change collection name. 

Platform:
Windows 7 x64
Node: v6.11.2
MongoDB: v3.4

**What is the current behavior?**
I created mongo scheme like on the code below:

```
var mongoose = require('mongoose');

var logSchema = mongoose.Schema({
    date: {
        type: Date,
        default: Date.now
    },
    log: String,
    additionalData: {}
});

module.exports = mongoose.model('Log', logSchema);
```

and I have a function like this one:
```
function saving(line) {
        var log = new Log();
        log.log = line;
        log.additionalData = additionalLogData;

        log.collection.collectionName = collection;
        log.collection.name = collection;

        log.save(function (err) {
            if (err)
                throw err;
        })
    }
```
These two lines are not changing collection name at all, the mongoose is still using an auto generated name of the collection - do you have any info about this problem?
Is there any better way to change collection name during runtime?

```
log.collection.collectionName = collection;
log.collection.name = collection;
```

**Comment by koliaVasyliv** [comment]
Hi, you can change collection name when you are creating a schema.
http://mongoosejs.com/docs/guide.html#collection

**Comment by nemanjapetrovic** [comment]
@koliaVasyliv Is there any posibility to change collection name during runtime?

**Comment by koliaVasyliv** [comment]
@nemanjapetrovic, After you make a connection to the database, you can get db instance and use mongodb driver to rename a collection (but make sure that you are connected to the database): 
```
mongoose.Promise = Promise;

let db = mongoose.connection.db;
// Rename collection
db.collection('a1').rename('a2')
 .then(() => {
   console.log('rename successful');
 })
 .catch(e => {
   console.log('rename failed:', e.message);
 })
```

**Comment by nemanjapetrovic** [comment]
@koliaVasyliv Thanks, that's what I was looking for!
