### ISSUE TITLE
Post hook synchronous or asynchronous are called depending of the presence of an error or not

### ISSUE THREAD

**Issue by Eygle** [Automattic/mongoose#5620]
Mongoose v4.11.10

The post save hook synchronous (1 param) is called when no errors occurred.
The post save hook asynchronous (3 params for me) is called when an error occurred.

__The expected behavior for me is to call the asynchronous hook everytime (like the pre save).__

Here is my code:

```javascript
// const _schema refer to the mongoose.Schema before it is loaded with mongoose.model(...)
// This schema represent a Member with a unique email

_schema.post('save', function (error, doc, next) {
    console.log("Member post save hook asynchronous");
    // my custom error overriding
    next(error);
});

_schema.post('save', function (doc) {
  console.log("Member post save hook synchronous");
  if (!this.isNew) {
    Cache.remove(this._id.toString());
  }
});

/*
* When I add a member with an existing email the asynchronous hook is called with an error filled
* When I add a member with a new email not present in db the synchronous hook is called (but not the asynchronous)
*/
```

What I want to do after a save is to override the raised Errors to replace them with my custom error. I also want to remove the member from cache after each successfull modification.

If I remove the second post hook (synchronous) the remaining hook is never called if no errors occurred.

**Comment by varunjayaraman** [comment]
Well wouldn't you expect the first middleware to not run if there are no errors? Your first hook is specifically error-handling middleware.

**Comment by Eygle** [comment]
Well it's curious because it is called in a pre save hook that raise (or not) an error.
The error parameter can be null (I actually use it that way anywhere and it is working except in the post middleware).

I understood from the doc that the difference between those two hooks are that one is synchrone and the other asynchrone but not that one is an error handler and not the other. Am I wrong?

**Comment by Eygle** [comment]
Indeed you are right, I'm sorry I didn't understood that.
This issue is invalid.

I expected the behaviour to  match express' one (which hav hooks are called with a 'null' error parameter when no errors occurred and allowed to have a single hook).

I would suggest you implement this in a future version to avoid having two hooks (one for errors and one for success), of course it's up to you.
