### ISSUE TITLE
Create query failing on shard collection

### ISSUE THREAD

**Issue by alopezvillaverde** [Automattic/mongoose#5621]
According the documentation, in order to use a shard collection we just need to set the **_shardKey_** schema option and we’ll be all set meanwhile the shard key will be present in all insert/update operations.

Let's say my partitioned collection is _action_ with shard key _actionId_

```
const mongoose = require('mongoose');
const actionModel = new mongoose.Schema({
    actionId: { type: Number, required: true, unique: true },
    name: { type: String, required: true, unique: true },
 }, {
    shardKey: { actionId: 1 },
 });
```
I can do a _findOne_ or _findOneAndUpdate_ query without any problems but not a **_create_** one facing the following error.

> PartitionKey value must be supplied for this operation

```
actionModel.create({ actionId, name}, (err, response) => {
    //logic
});

actionModel.findOne({ actionId }, (err, response) => {
    //logic
});

actionModel.findOneAndUpdate({ actionName }, data, { new: true, lean: true }, (err, response) => {
    //logic
});
```

I'm using node.js 6.11.1 version + mongoose 4.10.8 version on an Azure Cosmos DB environment

**Comment by varunjayaraman** [comment]
Hm, I'm not able to reproduce. This works for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5621`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`)
    const schema = new mongoose.Schema({
      actionId: { type: Number, required: true, unique: true },
      name: { type: String, required: true, unique: true },
    }, { shardKey: { actionId: 1 } });

    const Model = db.model('Model', schema);

    const doc = yield Model.create({ actionId: 123, name: 'test-name'});
  });
}
```

**Comment by varunjayaraman** [comment]
@alopezvillaverde does my script work for you?

**Comment by alopezvillaverde** [comment]
Thank you for the response @varunjayaraman I was able to do a _create_ operation at the end since the issue was on the database side. I was using Azure Document DB which was causing the error above.
