### ISSUE TITLE
this context for insertMany pre hook is not a query

### ISSUE THREAD

**Issue by Faleij** [Automattic/mongoose#5624]
The pre hook function context is the current model. Any other query pre hook function context is the query instance. The reason I need the function context to be the query instance is to modify the $comment field for the query.

node - 6.10.0
mongoose - 4.11.9

**Comment by vkarpov15** [comment]
I'd need to investigate whether its possible to add `$comment` to an insertMany. As is, `insertMany` is [not query middleware, but a distinct type of middleware](http://mongoosejs.com/docs/middleware.html).

**Comment by vkarpov15** [comment]
Yeah unfortunately as far as I can tell you can only add `$comment` to cursors and aggregate queries currently, can't do it for `insertMany`. https://docs.mongodb.com/manual/reference/operator/query/comment/#op._S_comment
