### ISSUE TITLE
Model.populate should infer model from call

### ISSUE THREAD

**Issue by jordonbiondo** [Automattic/mongoose#5629]
This appears to be a regression introduced at some point in time.

Current Behavior
``` js
  const thing = await Thing.create();
  const obj = {things: [thing.id]};
  const objs = [obj];
  await Thing.populate(objs, {path: 'things'})
  // objs === [{things: [thing.id}] 
  // objs.things is not populated
  await Thing.populate(objs, {path: 'things', model: Thing})
  // objs is populated correctly
```

Expected Behavior
``` js
  const thing = await Thing.create();
  const obj = {things: [thing.id]};
  const objs = [obj];
  await Thing.populate(objs, {path: 'things'})
  // objs is populated correctly, model: Thing should be inferred by the use of Thing.populate
```

The weird thing about it is that the Model you call populate on doesn't matter if you specify a model option so writing `SomeUnrelatedModel.populate(objs, {path: things, model: Thing})` works to populate Thing records on objs.

Ideally Model.populate would have some code that does `if options.model was not provided then options.model is this.modelName`

**Comment by varunjayaraman** [comment]
well you can specify it in the schema, but i could label this an enhancement (since i dont think this was ever actually a feature)

**Comment by jordonbiondo** [comment]
In my use real-world use cases the model name was always specified in the schema, perhaps this was a misfeature that got removed at some point.

In my use cases I was performing the same steps as shown in the first example and Thing models were populated as expected but it was only when upgrading to 4.11.5 from 4.4.7 that I started having to specify modelName in the calls to `AModel.populate(simpleObjects, options)`

**Comment by vkarpov15** [comment]
The below script seems to work for me, can you modify it to reproduce your issue?

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/gh5629');

run().catch(error => console.error(error.stack));

async function run() {
  const Model = mongoose.model('Test', new mongoose.Schema({
    models: [{ type: mongoose.Schema.Types.ObjectId }]
  }));

  const doc1 = await Model.create({});
  const doc2 = await Model.create({ models: [doc1._id] });

  const fromDb = await Model.findById(doc2._id);
  await Model.populate(fromDb, { path: 'models' });
  console.log(fromDb);
  console.log(fromDb.populated('models'));
}
```

Output:

```
$ node gh-5629.js 
(node:24918) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:24918) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
{ _id: 59c467fb795dea61560eadbb,
  __v: 0,
  models: [ { _id: 59c467fb795dea61560eadba, __v: 0, models: [] } ] }
[ 59c467fb795dea61560eadba ]
^C
$ 
```
