### ISSUE TITLE
Timeouts when autoReconnect is false

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5634]
https://github.com/mongodb-js/mongodb-core/pull/215 and https://github.com/Automattic/mongoose/issues/4513 and https://github.com/Automattic/mongoose/issues/5604 bring up some good points regarding how we handle `autoReconnect: false` and the 'timeout' event. If a socket dies because of a timeout and the driver doesn't automatically reconnect, we may not be able to execute any commands anymore depending on if there are any sockets left. For example, see repro for #4513, if `poolSize` is 1 and `autoReconnect` is false, any timeout leads to a dead connection where `mongoose.connection.readyState` is still 'CONNECTED'.

**Comment by elizatlawy** [comment]
Hey does the `autoReconnect` option still exist?

**Comment by vkarpov15** [comment]
@elizatlawy no, this issue is not relevant in Mongoose 6. In Mongoose 6, the MongoDB driver will always attempt to retry an operation for up to `serverSelectionTimeoutMS`. So if you execute `Model.findOne()` after initial connection, Mongoose will attempt to execute that query for up to `serverSelectionTimeoutMS`.
