### ISSUE TITLE
Cast to ObjectId failed  when i use RegExp

### ISSUE THREAD

**Issue by xiachaoxulu** [Automattic/mongoose#5637]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
 Cast to ObjectId failed for value "/59b741516fdef93a3567f81f/i" at path "_id"
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
6.9.1    4.11.3

**Comment by vkarpov15** [comment]
Please provide code samples
