### ISSUE TITLE
[Regression] Updating array document fails starting  release 4.8.3

### ISSUE THREAD

**Issue by catchshyam** [Automattic/mongoose#5638]
This is a regression starting release 4.8.3. It works fine on the previous versions

Update fails with the array elements included in the query.

### Schema:
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var MemberSchema = new Schema({
    _id: false,
    teamId: {type: Schema.Types.ObjectId},
    name: String,
    value: String
});

var GroupSchema = new Schema({
    members: [MemberSchema],
    status: String
});

mongoose.model('Group', GroupSchema);

```

### Sample Document:

```
{
    "_id" : ObjectId("597620fcba76f211586c9203"),
    "members" : [ 
        {
            "name" : "John",
            "value" : "abc",
            "taskId" : ObjectId("597620fcba76f211586c9402")
        }, 
        {
            "name" : "Jane",
            "value" : "123",
            "taskId" : ObjectId("597620fcba76f211586c9405")
        }
    ]
}

```
### Sample Application Code:

```
    mongoose.set('debug', true);
    var Group = mongoose.model('Group');
    Group
        .findById("597620fcba76f211586c9203", "_id members")
        .lean()
        .exec()
        .then(function (group) {
            Group.update(group, {$set: {"members.0.value": "abc"+Math.random()}}).exec().then(function (result) {
                console.log("Group update result ", result);
            });
        });

```
### Debug Output in Mongoose v4.8.3:

Mongoose: groups.findOne({ _id: ObjectId("597620fcba76f211586c9203") }, { fields: { _id: 1, members: 1 } })
Mongoose: groups.update({ members: [ { name: 'John', value: 'abc0.5795092725356088' }, { name: 'Jane', value: '123' } ], _id: ObjectId("597620fcba76f211586c9203") }, { '$set': { 'members.0.value': 'abc0.5011072844149436' } }, {})
Group update result  { ok: 1, **nModified: 0**, n: 0 }

### Output in Mongoose v4.8.2:

Mongoose: groups.findOne({ _id: ObjectId("597620fcba76f211586c9203") }, { fields: { _id: 1, members: 1 } })
Mongoose: groups.update({ members: [ { name: 'John', value: 'abc0.5795092725356088' }, { name: 'Jane', value: '123' } ], _id: ObjectId("597620fcba76f211586c9203") }, { '$set': { 'members.0.value': 'abc0.5011072844149436' } }, {})
Group update result  { ok: 1, **nModified: 1**, n: 0 }

However, update works fine when I issue the update command just with the _id field in the query like,

`Group.update({_id: group._id}, {$set: {"members.0.value": "abc"+Math.random()}}).exec()`

My Node version is 6.11.2.

Thanks,
Shyam

**Comment by vkarpov15** [comment]
Confirmed that the below script doesn't work in 4.8.3:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
  mongoose.set('debug', true);
const { Schema } = mongoose;

run().catch(error => console.error(error.stack));

async function run() {
  mongoose.connect(`mongodb://localhost:27017/gh-5638`, { useMongoClient: true });
  var Schema = mongoose.Schema;
  var MemberSchema = new Schema({
    _id: false,
    teamId: {type: Schema.Types.ObjectId},
    name: String,
    value: String
  });
  var GroupSchema = new Schema({
    members: [MemberSchema],
    status: String
  });

  const Group = mongoose.model('Group', GroupSchema);

  let doc = await Group.create({
    "members" : [
        {
            "name" : "John",
            "value" : "abc",
            "taskId" : "597620fcba76f211586c9402"
        },
        {
            "name" : "Jane",
            "value" : "123",
            "taskId" : "597620fcba76f211586c9405"
        }
    ]
  });

  doc = await Group.findById(doc._id).select('_id members');

  console.log(await Group.update(doc, { $set: { 'members.0.value': 'abcd' } }));
}
```

However, it works properly in >= 4.11.4 so this bug is fixed. https://github.com/Automattic/mongoose/blob/master/History.md#4114--2017-07-23
