### ISSUE TITLE
findOne throws Internal Server Error if object isn't found

### ISSUE THREAD

**Issue by martijnhiemstra** [Automattic/mongoose#5639]
When I use the findOne or findOneAndUpdate method, if the filtering doesn't find an object then a 500 Internal Server Error is thrown which is wrong if you ask me. A 500 error would suggest that an exception has happen and a non existing id isn't an exception, it's a possibility. Exceptions are  This is my code:

    MyObject.findOne({
        _id: mongoose.Types.ObjectId(req.params.id)
      }, function(err, myObject) {
         // This function isn't called.
      }

What should happen is that the err property should be supplied and that the function is called so that we have control over how to handle a non existing id.

**Comment by vkarpov15** [comment]
Mongoose doesn't return internal server errors or any other HTTP specific errors, so I don't understand the question. Can you provide more detailed code samples?

**Comment by martijnhiemstra** [comment]
For some reason I can't reproduce the error. I do notice that err and myObject are null. Perhaps an idea if the object can't be found that the err object contains an actual error for example: "Can't find object with id"

I am used to working with Java and empty error objects when there is an error is a wierd thing. Perhaps it's more normal in the Javascript world.

**Comment by vkarpov15** [comment]
Yeah in mongoose and MongoDB in general `findOne()` that doesn't match any document is not considered an error. You can easily write middleware to make `findOne()` error if no docs were found though:

```javascript
schema.post('findOne', function(result, next) {
  if (result == null) {
    return next(new Error('Can\'t find object'));
  }
  next();
});
```

**Comment by niklasbuhl** [comment]
I have the same problem now. `Model.findOne({ _id: <id> })` or `Model.findById(<id>)` throws an error if no match is found.

**Comment by vkarpov15** [comment]
@niklasbuhl please open a new issue and follow the issue template
