### ISSUE TITLE
Problem with () =>

### ISSUE THREAD

**Issue by stephanebressani** [Automattic/mongoose#5646]
Hello,

in last version  
``` 
"mongoose": "^4.11.11",
```
in package.json

in schema

the syntax is ok 👍 :
```
schema.virtual('name').get(function () {
    return this.firstName + ' ' + this.lastName;
});
```

and with :
```
schema.virtual('name').get(() => {
    return this.firstName + ' ' + this.lastName;
});
```
the 2 values are undefined, the syntax() => {} works with the rest

**Comment by vkarpov15** [comment]
Can you please clarify? The latter example with `() => {}` should never work because arrow functions clobber `this`.

**Comment by stephanebressani** [comment]
the first one works and the second one ```() => {}``` gives me variable ```this``` to undefined

i don't understand why the arrow functions clobber ```this```

i submited this to issues because I've been searching for more then 10minutes the problem in my code !

**Comment by MatthiasKunnen** [comment]
Arrow functions don't bind `this`. Read the following specification: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_this](). Support for arrow functions in this context will be part of v5 ([https://github.com/Automattic/mongoose/milestone/31](v5)). Follow issue #3379 for updates.

**Comment by varunjayaraman** [comment]
@MatthiasKunnen is correct. You can't use arrow functions because they have no lexical scope
