### ISSUE TITLE
Fast insert

### ISSUE THREAD

**Issue by wholcman** [Automattic/mongoose#5649]
Having some troubles.

Config: 
- 1 clustering nodeapp
- Socket-io.client server side
- When an event fired, I save into the database
- To avoid some duplicate events due to the cluster, I check if this event is already in the database before insert.

What is the "better" way to deal with? Should I only open sockets for only one cluster?
Or just define a unique constraint in the model? Redis ?

**Comment by AdrianSchneider** [comment]
Ignoring mongoose for a sec, you want to upsert your event into the database and key it on something unique. If you don't have a unique id yet, consider generating one whenever events are generated.

Upserts in mongoose should just look like:

```
Model.update(
  { yourUniqueKey: id },
  { $set: {
    // .. your data
  } },
  { upsert: true }
);
```

Similarly, you can use `findOneAndUpdate` to do an atomic write + fetch if you actually want to have it in memory after, without the concurrency problems that two queries would have. (To elaborate, if two servers fetch at the same time, not find anything, then insert, you'll have issues)

**Comment by vkarpov15** [comment]
Unique index and `findOneAndUpdate()` with `upsert` option is the way to go. Doing `find()` and then `insert()` has a race condition because there's no guarantee that another `insert()` didn't happen after your `find()` but before your `insert()`.

**Comment by wholcman** [comment]
No way to get a callback or a return value of `Model.addToSet(obj)` ?
Actually, it returns always an array even if the object is not inserted.
