### ISSUE TITLE
schema.pre('save') AND doc.invalidate(path,errMsg) question

### ISSUE THREAD

**Issue by r3wt** [Automattic/mongoose#5650]
#

**Do you want to request a *feature* or report a *bug*?**
possibly report a bug or ask a question about the weird behavior.

**What is the current behavior?**

calling document.invalidate from within pre save hook does nothing, and the changes are saved.

**What is the expected behavior?**

the validation fails because doc.invalidate() was called, resulting in doc.save() failing with err message.
NOTE: if you uncomment line 61 `$doc.ignore()` prevents the change but still no error is displayed.

Line where it fails:
https://github.com/r3wt/mongoose-auto-increment/blob/master/index.js#L60

reproduction:

clone the repo and run `npm install` then run `node test`

**Comment by vkarpov15** [comment]
Upon closer review this is expected behavior. You should instead invalidate in pre validate, because mongoose runs validate as pre save middleware
