### ISSUE TITLE
Using $set : {'array.1' : value } converts array to object

### ISSUE THREAD

**Issue by manu354** [Automattic/mongoose#5651]
I have a Model that looks something like this:

    {
        values: [
            {
               myContent
            },
        ]
    
    }
I want to replace the element/object in the array `values` at index `i` 

I wrote this simple code to do that:

    let i = doco.values.length - 1;
    
    let field = "values." + i;
    let set = {};
    
    set[field] = doco.values[i];
    await bulk.find({'_id': doco._id }).upsert().updateOne( {'$set' : set } );

However, instead of the intended functionality, that function does this to my document:

    "values": {
            "0": {
                "_id": {
                    "$oid": "59c01a7705659d1f686d1cf4"
                },
                "objValue": 'myValue',
        }

It turns it into an object and assigns a key of `i`.

Any suggestions? Perhaps my syntax is wrong?
Thanks.

**Comment by varunjayaraman** [comment]
@manu354 try this:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5651`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
    process.exit(1);
  });


function exec() {
  return co(function* () {
    yield mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`, { useMongoClient: true });
    const schema = new mongoose.Schema({
      values: [{ name: String }]
    });

    const Model = mongoose.model('Model', schema);

    const doc = yield Model.create({ values: [{ name: 'test-0' }] });

    let i = doc.values.length - 1;

    let field = "values." + (doc.values.length - 1);
    let set = {
      [`values.${i}`]: { name: 'test-replacement' }
    };

    const update = yield Model.findByIdAndUpdate(doc._id, set, { upsert: true, new: true });

    console.log(update.values);
  });
}
```

**Comment by varunjayaraman** [comment]
@manu354 can you confirm that works for you?
