### ISSUE TITLE
Documentation for hooks

### ISSUE THREAD

**Issue by zoellner** [Automattic/mongoose#5654]
The documentation for the hooks fired is inconsistent. 
For example, in order to find out whether the post remove hook is fired for Model.findByIdAndRemove one has to essentially read the code. 
There are a few notes throughout the documentation that mention that a hook is **not** fired - that doesn't give me full confidence that the omission of the note means hooks **are** fired.

Model.create seems to be the only one that has a "Hooks Triggered" section. Would be good to add such a section to other methods as well.

**Comment by vkarpov15** [comment]
That's a good suggestion, thanks :beers:
