### ISSUE TITLE
mongoose not connecting when using mongod --auth

### ISSUE THREAD

**Issue by staminna** [Automattic/mongoose#5660]
I am trying to connect to MongoDB with mongod --auth, even though I can successfully authenticate in mongo shell, when I run the MEAN stack in:

> node_modules/mongoose/node_modules/mongodb/lib/utils.js:123
>     process.nextTick(function() { throw err; });
>                                   ^
> MongoError: not authorized on webapplication to execute command { listIndexes: "sessions", cursor: {} }
>     at Function.MongoError.create (/website/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
>     at queryCallback (/website/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:212:36)
>     at /website/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
>     at nextTickCallbackWith0Args (node.js:489:9)
>     at process._tickDomainCallback (node.js:459:13)
> 

MongoDB version is 3.2 on Mac OS.
Mongoose@4.11.12
Nodejs 4.6.0
My mongod.conf is configured to use authentication and the MEAN stack is running with SSL.

**Comment by vkarpov15** [comment]
How are you authenticating in mongoose?

**Comment by staminna** [comment]
I tried two different methods:
The strange thing is It doesn't reach that part of the code!

Method one:
`var db = mongoose.connect(config.db, {
	options: {
		user: 'username',
		pass: '_password_'	
	}		
}, function(err) {
	if (err) {
		console.error('Could not connect to MongoDB!');
		console.log(chalk.red(err));
	}
});`

Method two look like:
```
module.exports = {
db: process.env.MONGOHQ_URL || process.env.MONGOLAB_URI || 
'mongodb://username:password@localhost/webapplication',
...
}
```

**Comment by vkarpov15** [comment]
Hmm and what method are you using to connect with the mongo shell?

**Comment by staminna** [comment]
`$ mongo
`

I am specifying --config and --auth to mongod
mongod.conf:

```
security:
  authorization: enabled
```

**Comment by vkarpov15** [comment]
Can you clarify whether the user that you're trying to auth with is on the webapplication database or another database? Also, is 'mongodb://username:password@localhost/webapplication' the URI you're connecting with in mongoose or are you overriding with an environment variable?

**Comment by staminna** [comment]
Not sure why, but I had to use both URI and Env variable at the same time. Maybe it's an old version of MEAN.JS. 

I got away with the following warnings: 

> Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
