### ISSUE TITLE
Extra fields are projected when using $elemMatch on findOneAndUpdate's projection

### ISSUE THREAD

**Issue by themetalfleece** [Automattic/mongoose#5661]
I found what I believe is a bug on mongo v3.2.9, mongoose 4.11.12, node 7.10.0

When using `$elemMatch` inside the `fields` parameter on `findOneAndUpdate`, extra fields are being returned.

For example,
```
            return Model.findOneAndUpdate(
                {
                    currentStatus: 'inactive'
                },
                {
                    currentStatus: 'active'
                },
                {
                    fields: {
                        array: {
                            $elemMatch: {
                                statusString: 'two',
                                statusNumber: 2
                            }
                        }
                    }
                }
            )
```
projects the correct array element but also projects the `currentStatus` field which was not included in the `fields`. Adding `lean()` after `findOneAndUpdate` solves the problem (projects only the _id and the array element), which makes me think it's a mongoose bug.

Full code for reproduction can be found [in this gist](https://gist.github.com/themetalfleece/18efb0be3953ce0887fc68f37b469716)

**Comment by vkarpov15** [comment]
Fix will be in 4.11.14, thanks for the detailed repro :+1:
