### ISSUE TITLE
Model.findById Not Always Works

### ISSUE THREAD

**Issue by SasoN-BrahA** [Automattic/mongoose#5662]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Hi,
I have a local variable called `foundUser` that I get from `User.findById`. I'm using that variable to add` "Welcome, #{foundUser.username}"` (and to change the nav bar according the permisson) in my layout.pug.
This is the code: 
```
app.all('*', (req, res, next) => {
// Coming from Passport Js
  if(req.isAuthenticated()) {
    let userPromise = User.findById({_id: req.user.id}).exec();
    userPromise.then((user) => {
      res.locals.foundUser = user;
    })
    .catch((err) => res.send(err));
  }
  next();
});
```
**If the current behavior is a bug, please provide the steps to reproduce.**
On the /users route, the problem always occurs for users without access. (I'm using a function to block access for regular users):
```
// Validate Client Permission
function checkPermission(req, res, next) {
  let loggedUser = req.user.id,
      errorMessage = 'Access Denied';
  User.findById(loggedUser, (err, foundUser) => {
    if(foundUser.perSta < 1) {
      req.flash('error', errorMessage);
      res.render('permission', {title: errorMessage});
    } else {
      return next();
    }
  });
}
```
Here's a video of the issue: https://www.youtube.com/watch?v=hxJaANU0B3I&feature=youtu.be;
On other route that I have, the this issue is vary random, somtimes when I login the the message doesn't show or when I refrash my browser allot (about 99% of the time it does show though).

**my /users route:** https://gist.github.com/SasoN-BrahA/ed4dd128a3efff57fe6cd6493b70f0e7
**my app.js:** https://gist.github.com/SasoN-BrahA/f99b8aa992ebb197849b305eed7ec9d9;
**my layout.pug:** https://image.prntscr.com/image/EpoyWKDLRWWw9f7q7e8biQ.png
**This is the error I get after removing the if statment:** https://image.prntscr.com/image/5y4Mxi4vRVupARIJk7eefQ.png

**What is the expected behavior?**
Always show welcome message.
**Please mention your node.js, mongoose and MongoDB version.**
Node: 6.11.3
MongoDB: latest, just installed it.
Mongoose: 4.11.12

**Comment by AugustBrenner** [comment]
I'm experiencing the same issue.  findById works some places, and not others.  It works always on my production environment, but not locally.

**Comment by vkarpov15** [comment]
You have a gaping race condition in your middleware

```javascript
app.all('*', (req, res, next) => {
// Coming from Passport Js
  if(req.isAuthenticated()) {
    let userPromise = User.findById({_id: req.user.id}).exec();
    userPromise.then((user) => {
      res.locals.foundUser = user;
    })
    .catch((err) => res.send(err));
  }
  // Race condition: kicks off next middleware before setting `res.locals.foundUser`
  next();
});
```

Do this instead

```javascript
app.all('*', (req, res, next) => {
// Coming from Passport Js
  if(req.isAuthenticated()) {
    let userPromise = User.findById({_id: req.user.id}).exec();
    userPromise.then((user) => {
      res.locals.foundUser = user;
      next();
    })
    .catch((err) => res.send(err));
  } else {
    next();
  }
});
```
