### ISSUE TITLE
One more dropDatabase issue

### ISSUE THREAD

**Issue by wertlex** [Automattic/mongoose#5664]
Hey!
Trying to write good reusable wrapper for testing models with mongoose and stuck a bit with dropping database. When write operations are executed after calling `dropDatabase()` it triggers re-creation of database. So, when there are any queries which was launched without awaiting result (or returning promise, but example is `async/await`-based) and right after that I call `dropDatabase()` it end up with dropped database and creating new one with same name. Is there any way to fix that behaviour given that I can't enforce user to `await` for all his queries or returning promise?

Here is brief example: 
```
const mongoose = require('mongoose');

async function withTempDb(dbName, action) {
	const mongoUri	= `mongodb://localhost:27017/${dbName}`;
	const opts	= {useMongoClient: true, promiseLibrary: global.Promise };

	const conn = mongoose.createConnection(mongoUri, opts);							
	const onceOpen = new Promise( resolve => conn.once('open', resolve ));			
	await onceOpen;						

	let result;

	try {
		result = await action(conn);												
	} finally {
		await conn.dropDatabase();
		await conn.close();
	}

	return result;
}

withTempDb('dummy', () => console.log('Sync ok'));

withTempDb('correct', async db => {
	const collection = db.collection('languages');
	await collection.insert({name: 'JS'});
	console.log('correct async okay');
});

// do not forget to drop 'tempDB-incorrect' after 
withTempDb('tempDB-incorrect', async db => {
	const collection = db.collection('languages');
	collection.insert({name: 'JS'});  // note, no await here, so not waiting for query result
	console.log('not waiting for insert result here...');
});
```

I'm expecting that after calling `Connection.close()` no new queries are accepted and `close` event emitted after every query performed through given connection is finished. But seems like even when `close` emitted queries are still in progress.

P.S. also tried with `conn.db.close(true)` - same result.

**Comment by vkarpov15** [comment]
Will check, `close(true)` should work...

**Comment by vkarpov15** [comment]
Confirmed, force close `close(true)` was not working. 4.11.14 will be released this weekend, once that's done you should be able to do `await conn.close(true);` and all subsequent writes will error out.
