### ISSUE TITLE
Mongoose does not throw error for wrong database name

### ISSUE THREAD

**Issue by nakshay** [Automattic/mongoose#5666]
I have database name called blogger and collection name blog.
I was using below connection string
`mongodb://localhost/blogs` instead of `mongodb://localhost/blogger`
but db.on('error') and db.once('open') did not throw any error and shown connected to database message.

after changing connection url blogs to  blogger I got my data. but I was expecting mongoose to throw an error for wrong database connection.

**Comment by vkarpov15** [comment]
How would mongoose know that its the wrong database? Perfectly valid to connect to an empty database.

**Comment by nakshay** [comment]
Yes, it creates and connects to empty database.
