### ISSUE TITLE
Subdocument Array, push updates data immediately

### ISSUE THREAD

**Issue by NicolaiSchmid** [Automattic/mongoose#5668]
Bug:
I've create a mongoose schema, with a subdocumented array.
```
const sub = new Schema({
   attributes: [String]
});

const schema = new Schema({
   id: String
   test: [sub],
});
```
When I now query for the the schema
```
const data = await Schema.findOne({id: 'asdf'}).setOptions({lean: true}).exec();
```
and I modify the data inside the subdocument, eg: 
```
data.attributes.push('string');
```
The data variable gets updated immediately. I would expect the constant to remain with the same value and don't update the data in-place.

I'm not quite sure what causes this bug. Maybe it's something inside my code, but I've literally tested every single scenario the last 2 hours. And I've narrowed it down to the data getting changed during the `push` method.
My versions are: 
```
mongoose: 4.11.13
node: 8.4.0
mongo: 3.4.5
```

**Comment by vkarpov15** [comment]
Can you please clarify "The data variable gets updated immediately. I would expect the constant to remain with the same value and don't update the data in-place."? I don't see any constants?

**Comment by NicolaiSchmid** [comment]
Of course!
With this exact snippet: 
```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.connect('mongodb://172.17.0.2/development')
    .catch((error) => {
        console.log(error);
        throw new Error(error.message);
    });


const schema = new Schema({
    id: String,
    test: [String],
});

const Model = mongoose.model('schema', schema);

async function exec() {
    try {

        console.log(await new Model({
            id: 'id',
            test: [],
        }).save());

        const oldState = await Model.findOne({ id: 'id' }).setOptions({ lean: true }).exec();
        console.log(oldState);
        let test = oldState.test;
        test.push('string');
        console.log(oldState);

    } catch (error) {
        console.log(error);
    }
}

exec();
```
I get an output of:
```js
{ __v: 0, id: 'asdf', _id: 59ca1f191e1b4943c5ff9b6c, test: [] }
{ _id: 59ca1f191e1b4943c5ff9b6c, id: 'asdf', test: [], __v: 0 }
{ _id: 59ca1f191e1b4943c5ff9b6c,
  id: 'asdf',
  test: [ 'string' ],
  __v: 0 }
```
As opose to:
```js
{ __v: 0, id: 'asdf', _id: 59ca1f191e1b4943c5ff9b6c, test: [] }
{ _id: 59ca1f191e1b4943c5ff9b6c, id: 'asdf', test: [], __v: 0 }
{ _id: 59ca1f191e1b4943c5ff9b6c, id: 'asdf', test: [], __v: 0 }
```
I would expect the `oldState` constant to have the same value after the modification of the subproperty

**Comment by vkarpov15** [comment]
This is not an issue with mongoose, `push()` in JavaScript modifies arrays in-place. If you want a copy of the array you should do `let test = [].concat(oldState.test); test.push('string');`

**Comment by NicolaiSchmid** [comment]
Thank you! I wasn't aware of that, I'm sorry to bother you!
