### ISSUE TITLE
Turn on `usePushEach` by default

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5670]
Re: #5574, #4455

**Comment by vkarpov15** [comment]
82aeba5 was painful. Tests that have side effects on subsequent tests is definitely [an idea that hasn't stood the test of time](https://github.com/Automattic/mongoose/blob/b62164649c6ade14dbd847b39f65e1a00cc40682/test/model.update.test.js)

**Comment by AttilaSATAN** [comment]
@vkarpov15 Is this patch in placed only v5 releses? I've just getting `Unknown modifier: $pushAll` on Mongo 3.6 with Mongoose 4.13.9
