### ISSUE TITLE
mquery@2.3.1 depends on the vulnerable package debug@2.6.8

### ISSUE THREAD

**Issue by subesokun** [Automattic/mongoose#5677]
As `mquery@2.3.1` explicitly depends on the vulnerable package `debug@2.6.8` the NSP security check fails, see https://nodesecurity.io/advisories/534

Please upgrade at least to `mquery@^2.3.2` and if possible avoid pinning dependencies.

**Comment by vkarpov15** [comment]
Fixed in #5679 :+1:
