### ISSUE TITLE
Feature: Do not throw error on bulkOp.execute() when there are no operations

### ISSUE THREAD

**Issue by QuotableWater7** [Automattic/mongoose#5678]
This is a **feature-ish** request (or change in behavior request).

**What is the current behavior?**
If you initialize a bulk operation object and don't end up adding bulk operations, calling `bulkOperation.execute()` will throw an error.

To avoid that error, we often use a local variable `anyBulkOps` and set it to `true` once we've hit a condition where something needs to be updated or created.

**What is the ~expected~ desired behavior?**
When we run bulk ops, we don't care if we didn't end up adding anything to the bulk operation.  It would be nice if `execute` in that case did not throw an error, but rather just didn't do anything.

Here is some example code that would be nice to be able to run without tracking if bulk ops were added:
```js
const bulkOperation = mongoDocs.reduce(
  (bulkOp, mongoDoc) => {
     if (mongoDoc.someValue > 5) {
       bulkOp.find({ _id: mongoDoc._id }).update({ dateUpdated: Date.now() }) 
     }

     return bulkOp
  },
  mongoModel.collection.initializeUnorderedBulkOp()
)

bulkOperation.execute() // currently throws error if all docs were value 5 or below
```
Here is what code in our codebase often ends up looking like:

```js
let anyBulkOps = false

const bulkOperation = mongoDocs.reduce(
  (bulkOp, mongoDoc) => {
     if (mongoDoc.someValue > 5) {
       anyBulkOps = true
       bulkOp.find({ _id: mongoDoc._id }).update({ dateUpdated: Date.now() }) 
     }

     return bulkOp
  },
  mongoModel.collection.initializeUnorderedBulkOp()
)

if (anyBulkOps) {
  bulkOperation.execute()
}
```

**Please mention your node.js, mongoose and MongoDB version.**
node 8.4.0
mongoose 4.9.1
mongodb 3.0.8

--------

Thanks for your time!

**Comment by QuotableWater7** [comment]
If this sounds like a good change to the maintainers, I'm happy to take a stab at implementing the changes.

**Comment by vkarpov15** [comment]
Why do y'all use `initializeUnorderedBulkOp()` instead of `bulkWrite()`? It would be hard to add this to `initializeUnorderedBulkOp()` because that function is currently not in mongoose, and we don't really want to add it because the whole `initializeUnorderedBulkOp()` has been quietly deprecated by mongodb for quite some time.

**Comment by QuotableWater7** [comment]
@vkarpov15 we've been slow upgrading mongoose -- I'll close the issue and try replacing `initializeUnorderedBulkOp` with `bulkWrite`.  Thanks!
