### ISSUE TITLE
Promise deprecation warning is shown despite setting connect option in 4.12

### ISSUE THREAD

**Issue by kdekooter** [Automattic/mongoose#5686]
I am connecting to mongodb following the sample on mongoose's home page (version 4.12.0):

`mongoose.connect(process.env.MONGO_URL, {useMongoClient: true, promiseLibrary: global.Promise})`

Still the node console prints:
`(node:37709) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html`

**Comment by vkarpov15** [comment]
Please read the docs linked to in the warning, they'll show you that you also need to do `mongoose.Promise = global.Promise;` . The `promiseLibrary` option is used to set the underlying node driver's promise library, which you usually don't need to do.

**Comment by kdekooter** [comment]
I am sorry but in that case it should probably not be part of the second line of the sample code on the home page.

**Comment by vkarpov15** [comment]
What home page are you talking about?

**Comment by kdekooter** [comment]
http://mongoosejs.com/

**Comment by vkarpov15** [comment]
![image](https://user-images.githubusercontent.com/1620265/31204966-4daa03b8-a923-11e7-8b14-41638c6284c3.png)

Thanks for reporting, fixed in master and will be released when we release 4.12.1 :+1:
