### ISSUE TITLE
Noobie question - testing framework (chai) throws 'Cast to ObjectId failed' error on subdocs

### ISSUE THREAD

**Issue by cenkozan** [Automattic/mongoose#5688]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

It throws:
```{ CastError: Cast to ObjectId failed for value "{ title: 'x' }" at path "appointments"```

**If the current behavior is a bug, please provide the steps to reproduce.**
My Client:
```
'use strict';
import * as mongoose from 'mongoose';
const clientSchema = new mongoose.Schema({
  name: String,
  appointments: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Appointment' }]
});
const Client = mongoose.model('Client', clientSchema);
export default Client;
```
My Appointment:
```
'use strict';
import * as mongoose from 'mongoose';
const AppointmentSchema = new mongoose.Schema({
  title: String,
});
const Appointment = mongoose.model('Appointment', AppointmentSchema);
export default Appointment;
```
My controller:
```
abstract class ClientCtrl {
  abstract model: Client;
  insert = (req, res) => {
    const obj = new this.model(req.body);
    obj.save((err, item) => {
      if (err && err.code === 11000) {
        res.sendStatus(400);
      }
      if (err) {
        return console.error(err);
      }
      res.status(200).json(item);
    });
  }
  // Get by id
  get = (req, res) => {
    this.model.findOne({ _id: req.params.id }, (err, obj) => {
      if (err) { return console.error(err); }
      res.json(obj);
    });
  }
}
export default ClientCtrl;
```
My chai test:
```
import * as chai from 'chai';
import * as chaiHttp from 'chai-http';
process.env.NODE_ENV = 'test';
import { app } from '../app';
import Client from '../models/Client';
const should = chai.use(chaiHttp).should();
describe('Clients', () => {
    it('should save clients appointments', done => {
      const client = new Client({name: 'Dave'});
      client.save((error, newClient) => {
        chai.request(app)
          .put(`/api/client/${newClient.id}`)
          .send({ appointments: [{title: 'x'}] })
          .end((err, res) => {
            res.should.have.status(200);
            res.body.should.have.property('appointments');
            done();
          });
      });
    });
});
```
I am using latest node, mongo, and mongoose. 
Help please.

**Comment by vkarpov15** [comment]
First, do **not** use `import * as mongoose from 'mongoose';` . Use `import mongoose from 'mongoose';`. There is a very subtle difference there that breaks mongoose.

Secondly, why are you passing down `{ title: 'x' }` instead of an ObjectId?

**Comment by varunjayaraman** [comment]
yeah @cenkozan the error message says it all: you're trying to store `{ title: someString }` where it should just be an `ObjectID` as per your schema

**Comment by cenkozan** [comment]
I have tried ```import mongoose from 'mongoose';```, mongoose didn't initialise. I am getting some other errors when I try other things. I am thinking there is something wrong in the configuration with the repo I started building on my solution. So, I moved on from using subdocs. I saved the id of the other model and moved on. Thank you so much anyway!!!
