### ISSUE TITLE
Transform to another model on post init

### ISSUE THREAD

**Issue by kadosh1000** [Automattic/mongoose#5689]
Hi, I am using the latest mongoose.
The thing I try to accomplish is to transform my query results to another model on the post init hook.

for eaxmple, the results of my query are from model A, and in the post init I wish to transform it to a new document from model B.

The thing is that I can't assign to `this` and if I try to merge the two objects (using underscore's `.merge`) it indeed transforms to model B but it causes other problems with future queries.

How would you recommend on doing that?

**Comment by vkarpov15** [comment]
`doc = new ModelB(doc.toObject())`
