### ISSUE TITLE
Using Document method Inside model method

### ISSUE THREAD

**Issue by mittal01091997** [Automattic/mongoose#5691]
**Do you want to request a *feature* or report a *bug*?**
[x] Question

**What is the current behavior?**
The code is throwing an error:

`(node:7700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Example.someDocumentMethod is not a function`

**If the current behavior is a bug, please provide the steps to reproduce.**
<pre><code>const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const ExampleSchema = new mongoose.Schema({
    // some attributes
});

ExampleSchema.methods.someDocumentMethod= function () {
    // some calculation on this document
};

ExampleSchema.statics.someModelMethod= function (value) {
    this.find({someAttr: value}).then((exampleDoc) => {
        exampleDoc.someDocumentMethod();
    }
};

const Example= mongoose.model('Example', ExampleSchema);
module.exports = {Example};</code></pre>

The function someModelMethod is called inside a route as:

`Example.someModelMethod(somevalue);`

**What is the expected behavior?**
being able to use a document method (called on individual documents) inside a model method (called on the model). Is this usual behavior, or its a bug

**Please mention your node.js, mongoose and MongoDB version.**
current mongoose version: ^4.11.10
current node version v6.11.0
current mongodb version 3.4.5

**Comment by varunjayaraman** [comment]
your problem is that `.find` returns an array. the individual elements in the array will be mongoose documents and you can use instance methods on those objects

**Comment by varunjayaraman** [comment]
sorry, didnt mean to prematurely close. try using `findOne` and see if that works
