### ISSUE TITLE
Suppressing: DeprecationWarning: 'ensureIndex()' is deprecated in Mongoose >= 4.12.0, use 'createIndex()

### ISSUE THREAD

**Issue by MongoExpUser** [Automattic/mongoose#5692]
How can we suppress the following warning in Mongoose 4.12.0, when connecting MongoDB with mongoose. This warning message only appears when I upgraded to 4.12.0.

**DeprecationWarning: 'ensureIndex()' is deprecated in Mongoose >= 4.12.0, use 'createIndex()' instead**

**Comment by amihailes** [comment]
This arrives with a mongoDB 3.4.7 on my machine.

**Comment by lcaouen** [comment]
I have the same issue with:
- Mongoose 4.12.0
- MongoDB 3.2.16
- NodeJS 6.11.3

**Comment by vkarpov15** [comment]
That's strange. Are you calling `ensureIndexes()` manually? Can you show me your connection code? Mongoose 4.12 should call `createIndex()` under the hood.

**Comment by CivFactions** [comment]
I'm not using `ensureIndex()` anywhere in my project and I still get this error with v4.12.0.

```
  mongoose.Promise = global.Promise;
  mongoose.connect(config.MONGO_URI, {
    useMongoClient: true,
    promiseLibrary: global.Promise
  });
  this.connection = mongoose.connection;
```

**Comment by MongoExpUser** [comment]
I'm not using or calling ensureIndex() anywhere in my code. See below:
------------------------------------------------------------------
var mongoose                = require('mongoose');                  
mongoose.Promise        = require('bluebird');  
var fs                              = require('fs'); 
var uri                             = 'mongodb://user:password@domain.com/dbName'; 
var optionsSSL               = { //read in certs};
var connectionOptions   = { //specify connection options};  

mongoose.connect(uri, connectionOptions, function(err) 
{
    if (err) {console.log(err)};
});
------------------------------------------------------------------

I also feel that this is strange behavior. 

May be this has  to do with the MongoDB server version?

I am using MongoDB server version: 3.4.9.

**Comment by X-XXX** [comment]
encounter the same problem 
mongoose.connect('mongodb://127.0.0.1:27017/text',{ useMongoClient: true},function(err){
    if (err) {
      console.log('-----------NO------------');  
    }else{
      console.log('-----------OK------------');  
    }
});
setting session 

store: new MongoStore({
    mongooseConnection: mongoose.connection, 
    autoRemove:'native'
})

**Comment by ivancsicsmarkus** [comment]
I've tested things out. MongoStore causes this notice.

**Comment by amihailes** [comment]
I use also MongoStore.

It seems to be an issue with the combination mongoose/MongoStore

Nodejs 6.11.14
mongoose 4.12.0
MongoDB 3.4.9

**Comment by CivFactions** [comment]
There's an open pull request in connect-mongo to fix this issue.
https://github.com/jdesboeufs/connect-mongo/pull/269

**Comment by MongoExpUser** [comment]
I can also confirm that the warning message is from the mongo **"store"** module that I am using for session management, which is  **connect-mongo**.

So replacing  **connect-mongo** with another "store" management module that calls **createIndex()** should eliminate the warning.

In the alternative, I think there is **an open pull request in connect-mongo** to fix the issue as mentioned by CivFactions.

Thank you all.

**Comment by ac1dr3d** [comment]
same here people but... this MongoStore thing is in my react project also... so... id be glad to hear solution... please. thanks.

**Comment by MongoExpUser** [comment]
ac1dr3d,
If your **mongoStore**  is using **connect-mongo**, then you have to wait until the issue is resolve in on **connect-mongo**. 

If you want to replace your **mongoStore** with another module, check the link below for **recommended** modules:

1) express-session-mongo:      https://www.npmjs.com/package/express-session-mongo
2) connect-mongodb-session:  https://www.npmjs.com/package/connect-mongodb-session
3) sessionstore:                     https://www.npmjs.com/package/sessionstore
4) express-mongoose-store:    https://www.npmjs.com/package/express-mongoose-store
5) etc..

**Comment by amihailes** [comment]
Hi,

I use express-session-mongo and I have the warning.........

**Comment by amihailes** [comment]
In fact, express-session + connect-mongodb-session:

 session = require('express-session'),
    MongoDBStore = require('connect-mongodb-session')(session),

**Comment by MongoExpUser** [comment]
amihailes,
It means that **connect-mongodb-session** is probably **calling createIndex()**  somewhere under the hood. So, it might be worth trying other modules listed above or others that could be found on **npm** to see which ever works for you.

**Comment by jdesboeufs** [comment]
Working on this!

**Comment by jdesboeufs** [comment]
Published `connect-mongo@2.0.0`

**Comment by CivFactions** [comment]
Thanks @jdesboeufs

**Comment by MongoExpUser** [comment]
Thank you jdesboeufs.
