### ISSUE TITLE
Is there a way we can handle views with mongoose !?

### ISSUE THREAD

**Issue by muhammadfaizan** [Automattic/mongoose#5694]
***feature***

**What is the current behavior?**
currently there is a plugin, but that only selects few fields, and doesn't work on multiple models

**What is the expected behavior?**
https://docs.mongodb.com/manual/reference/method/db.createView/#db.createView

using mongoDB 3.4

**Comment by vkarpov15** [comment]
Not sure what you mean by handling views. What's the plugin you're talking about?

Once a view is created, as far as mongoose is concerned it is just a read-only collection, so as long as you have a schema in mongoose you can query the view as you would any normal collection.

**Comment by muhammadfaizan** [comment]
I meant how can i create read only collection with mongoose, that is allowed by mongodb

**Comment by vkarpov15** [comment]
`MyModel.connection.db.createCollection('myViewName', { viewOn: 'existingCollection', pipeline: [/* aggregation pipeline here */] });` http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#createCollection

**Comment by alzalabany** [comment]
so we can use createCollection to create a view. and redirect our model to use that view ?
im trying to implement something like soft delete where i have 2 collections 1_ all_data & 2nd active_only . and i want to from now on only use active only every where in app to hide deleted docs. but i cannt wrap my head how to do so with mongoose

**Comment by vkarpov15** [comment]
@alzalabany you would create 2 separate models, one that points to the allData collection and one that points to the activeData view. Use the third param to mongoose.model to specify the collection name http://mongoosejs.com/docs/api.html#mongoose_Mongoose-model

**Comment by blazestudios23** [comment]
It would be great if there was some kind of code example of this.
