### ISSUE TITLE
Second level of populate doesn't work

### ISSUE THREAD

**Issue by stephanebressani** [Automattic/mongoose#5696]
**Do you want to request a *feature* or report a *bug*?** **(I don't know)**
node version : 6.11.0
mongoose version : 4.11.13
mongodb : mLab

In Backend express.js:
<img src="https://img11.hostingpics.net/pics/869829Capturedecran20171007a131913.png">

populate "ingredients.DA01" doesn't work, populate "ingredients" (DA07RecIng) works, but the second level of populate (model "DA01Ingredient") in this exemple (picture above) doesn't work 

Result in front-end:
<img src="https://img11.hostingpics.net/pics/751989Capturedecran20171007a131827.png">

Model from "DA02Recette" with a array "ingredients" to "DA07RecIng"
<img src="https://img11.hostingpics.net/pics/236612Capturedecran20171007a132036.png">

Model from "DA07RecIng"
<img src="https://img11.hostingpics.net/pics/750583Capturedecran20171007a132100.png">

Model from "DA01Ingredient"
<img src="https://img11.hostingpics.net/pics/308565Capturedecran20171007a132000.png">

Have you a trick to acomplish this ?

**Comment by Spown** [comment]
have you tried... oh idunno... [RTFM](http://mongoosejs.com/docs/populate.html#deep-populate)? Also this is what StackOverflow is for.

**Comment by varunjayaraman** [comment]
yeah, this is in the docs @stephanebressani, here's an example:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5696`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    yield mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`, { useMongoClient: true });

    const deepNested = new mongoose.Schema({ name: String });
    const DeepNested = mongoose.model('DeepNested', deepNested);

    const nested = new mongoose.Schema({
      deepNested: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'DeepNested'
      }
    });

    const Nested = mongoose.model('Nested', nested);

    const schema = new mongoose.Schema({
      nested: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Nested'
      }
    });
    const Model = mongoose.model('Model', schema);

    const dn1 = yield DeepNested.create({ name: 'test' });
    const n1 = yield Nested.create({ deepNested: dn1._id });

    const m1 = yield Model.create({ nested: n1._id });

    let doc = yield Model
      .findById(m1._id)
      .populate('nested'); // nested is populated
    console.log('doc with nested populate', doc);

    doc = yield Model
      .findById(m1._id)
      .populate('nested')
      .populate('nested.deepNested');
    console.log('doc with 2 populates', doc);

    doc = yield Model
      .findById(m1._id)
      .populate({ path: 'nested', populate: { path: 'deepNested' }});
    
    console.log('doc with correct populates', doc); // has deepNested populated
  });
}
```

**Comment by stephanebressani** [comment]
Thank you ! it's works 👍 

```
.populate({ path: 'nested', populate: { path: 'deepNested' }});
```

**Comment by varunjayaraman** [comment]
cool!

**Comment by vkarpov15** [comment]
Glad you found the issue :+1: 

@Spown thanks for your docs link but please be more respectful in the future :+1: :palm_tree:

**Comment by akritibhat** [comment]
submissionModel
        .findById(sid)
        .populate({ path: 'answers', populate: { path: 'question' }})
        .exec()


not working

**Comment by b000cw** [comment]
Hi, I am able to get the deepNested, but in my Database I am having a newDeepNested inside deepNested like 

` const deepNested = new mongoose.Schema({ name: { type : String } , newDeepNest: { type: Schema.ObjectId, ref : "newDeepNest" }});`

` const newDeepNest = new mongoose.Schema({ name: String }); `

while using populate for nested how can I get the newDeepNest too.
