### ISSUE TITLE
Anchoring in docs

### ISSUE THREAD

**Issue by Spown** [Automattic/mongoose#5697]
I've noticed that some headers are anchorable, while most are not. And it seems that there is even a css for highliting them with ">>>" http://mongoosejs.com/docs/populate.html#deep-populate. However, as you can see in the link there is no way to actually link it other then to go to the source, copy the id and construct the link yourself. And the page I linked to has only like the half of the headers supplied with id's (that often do not even correspond to the text of the header). 

Doing it manually is probably not going to happen. So maybe something like [this](https://jsfiddle.net/Spown/7hxctgav/)?

JSFiddle seems to be protecting itself from hot-linking, so opening new tab/url from the anchored direct url or from here shows a blank page. It only works when coming from this page http://fiddle.jshell.net/Spown/7hxctgav/show. but it seems to work though.

**Comment by vkarpov15** [comment]
Good idea. We're going to be doing some work on the docs in the next couple months so I'll keep this in mind.
