### ISSUE TITLE
Virtual variable mixed between threads

### ISSUE THREAD

**Issue by DiV666** [Automattic/mongoose#5699]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When two threads are executed in the same time period, the virtual variable of the first thread takes the value of the second variable.

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce the error two requests must be sent and the second must be sent before the first one is finished.
Model:
```
const mongoose = require('mongoose');
const operationSchema = new mongoose.Schema({
	fileName:	{ type: String, required: true }
}, {
	toObject: {
		virtuals: true
	},
	toJSON: {
		virtuals: true 
	}
});

operationSchema.virtual('file').get(() => {
	return this.file;
}).set(value => {
	this.file = value;
});
module.exports = mongoose.model('Operation', operationSchema);
```

Controller:
```
// POST -> .../api/sign
function sign(req, res) {
	const operation = new OperationModel({
		fileName: req.body.file.name,
		file: req.body.file
	});

	console.log('#1: ' + req.body.file.name);
	console.log('#1.1: ' + operation.fileName);
	console.log('#1.2: ' + operation.file.name);

	setTimeout(() => {
		console.log('#2: ' + req.body.file.name);
		console.log('#2.1: ' + operation.fileName);
		console.log('#2.2: ' + operation.file.name);

		res.end('OK');
	}, 3000);
}
```

If I send 2 requests, one with file.name "1.pdf" and the second with "2.pdf", when the 3 seconds of settimeout ends, the first throw in console:
```
#2: 1.pdf
#2.1: 1.pdf
#2.2: 2.pdf
```

**What is the expected behavior?**
The expected behavior is that the virtual variable should not take the value of another thread.

**Please mention your node.js, mongoose and MongoDB version.**
node.js -> 8.6.0
MongoDB -> 3.0.8
mongoose -> 4.12.1

**Comment by DiV666** [comment]
Sorry, I just realized that the problem is because the arrow functions don't bind this. I have changed the declaration of the virtual variable by this:
```
operationSchema.virtual('file').get(function () {
	return this._file;
}).set(function (value) {
	this._file = value;
});
```
Would it be correct or should it be otherwise?

**Comment by vkarpov15** [comment]
That's correct. Don't use arrow functions with mongoose getters/setters or anything else that depends on `this`.
