### ISSUE TITLE
lowercase not enforced on findByIdAndUpdate

### ISSUE THREAD

**Issue by dyladan** [Automattic/mongoose#5705]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

On `Model.findByIdAndUpdate(id, object)` if a field with `lowercase: true` is updated to a value with uppercase characters, the value is saved with the characters still uppercase

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a model with a string field with lowercase true
2. Create and save an instance of the model
3. Update the model with findByIdAndUpdate
4. Query the model

**What is the expected behavior?**

I would expect the field to be lowercased

**Please mention your node.js, mongoose and MongoDB version.**
nodejs 8.4
mongodb 3.5
mongoose 4.11.7

**Comment by Spown** [comment]
do you actually change the value of said field or do you update other fields, and the upper case string of the filed is from before ``.findByIdAndUpdate``? Does the ``object`` in ``Model.findByIdAndUpdate(id, object)`` actually has a field that should be lowercased? Because if it's not - the lc setter wouldn't be invoked and the field stays the same.

**Comment by dyladan** [comment]
Yes the field is changed, prior to the update it is actually not set, and yes the field should be lowercased. If I have time later today I will try to come up with a minimal example.

**Comment by dyladan** [comment]
@Spown Here is a minimal example

```
"use strict";

const mongoose = require("mongoose");

const testSchema = new mongoose.Schema({
  name: { type: String, required: [true, "A name is required"] },
  lowerfield: { type: String, lowercase: true },
}, { timestamps: true });

const TestModel = mongoose.model("Test", testSchema);

mongoose.connect("mongodb://localhost/mongotest");

let objId;
TestModel.create({ name: "test object" })
  .then((obj) => {
    if (!obj) {
      throw new Error("No object created");
    }

    objId = obj._id;
    return TestModel.findByIdAndUpdate(obj._id, { lowerfield: "Lowercase Pls" });
  })
  .then(() => {
    // requery the object
    return TestModel.findById(objId);
  })
  .then((obj) => {
    console.log(obj);
  });

// Prints the following
// { _id: 59de7a78d8710cd4374b36d8,
//   updatedAt: 2017-10-11T20:09:28.323Z,
//   createdAt: 2017-10-11T20:09:28.203Z,
//   name: 'test object',
//   __v: 0,
//   lowerfield: 'Lowercase Pls' }
```

**Comment by Spown** [comment]
well, 
```
return TestModel.findByIdAndUpdate(obj._id, { lowerfield: "Lowercase Pls" }, {runSettersOnQuery : true});
```
does work correctly. so the question is why the setter doesn't trigger. Looks like a bug to me.

I'm not a dev here, so I'm out.

**Comment by vkarpov15** [comment]
Yeah you need to opt in to this behavior using the runSettersOnQuery option. We keep that behind a flag for backwards compat because running setters on a findOneAndUpdate has ramifications for custom setters.

**Comment by Spown** [comment]
You probably should mention it in the docs.

**Comment by dyladan** [comment]
Yea it's quite misleading

**Comment by vkarpov15** [comment]
It is in the docs: http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate . Where would you expect it to be in the docs?

**Comment by Spown** [comment]
Oh yeah, it is in the Note. However it speaks of ``findAndModify`` not mentioning ``findByIdAndUpdate`` explicitly, so when running through the docs (which I did) it kinda slips through. But it's my (consumer's) fault for not reading properly and not making obvious conclusions, I guess. So never mind.

**Comment by dyladan** [comment]
I would put it with the setter docs maybe. "only runs on initial object
creation" or something to that effect

**Comment by vkarpov15** [comment]
Yeah it's definitely something to improve. I think mentioning `findAndModify()` does more harm than good because `findAndModify()` is underneath `findOneAndUpdate` and `findOneAndRemove`, which in turn are called by `findByIdAndUpdate` and `findByIdAndRemove`, but most people don't use `findAndModify()` anymore...

@dyladan which setter docs are you referring to?

**Comment by dyladan** [comment]
@vkarpov15 I would put a note [here for instance](http://mongoosejs.com/docs/api.html#schema_string_SchemaString-lowercase).

I would probably put a note [here](http://mongoosejs.com/docs/api.html#schematype_SchemaType-set) and link to it from anywhere that adds a default setter such as lowercase. Something to the effect of "Setters only run on initial object creation, not updates, unless you use <option>"
