### ISSUE TITLE
Connection time out with connectTimeoutMS

### ISSUE THREAD

**Issue by LeonLiber** [Automattic/mongoose#5717]
Hello,

I'm running about 80K update operations (as promises) in Promise.all() and although I've set connectTimeoutMS - I'm getting the following error after about 3 minutes:

```
name: 'MongoError',
message: 'connection 2 to localhost:27017 timed out'
```

 I've set `connectTimeoutMS` in both connection string and `options` (just in case) like so:
`mongodb://localhost/network?connectTimeoutMS=6600000`
and
```
mongoose.connect(config[env].connString, { 
  socketOptions: {
    keepAlive: 6600000,
    connectTimeoutMS: 6600000,
    auto_reconnect: true
  },
  useMongoClient: true, 
  promiseLibrary: global.Promise });
```
Mongoose version: 4.12.0
Mongo version: 3.2.8

I hope someone can help, been strugling with this for days..

BTW, same happens in production on Google App Engine with replset:

```
name: 'MongoError', 
message: 'connection 3 to cluster0-shard-00-00-2gkuy.mongodb.net:27017 timed out'
```

**Comment by vkarpov15** [comment]
You're looking for `socketTimeoutMS`. `connectTimeoutMS` is a timeout for initial connection. Try the below:

```javascript
mongoose.connect(config[env].connString, { 
  keepAlive: 6600000,
  connectTimeoutMS: 6600000,
  socketTimeoutMS: 6600000,
  useMongoClient: true, 
  promiseLibrary: global.Promise });
````

**Comment by LeonLiber** [comment]
Thank you!

Another thing that helped me and could help others was that I split the execution of the 80K queries to smaller chunks with the help of Bluebird promise library, like so:

```javascript
Promise.map(rows, (row) => {
            return offerPerformanceModel.findOneAndUpdate(row.keys, row.value, { upsert: true });
          }, { concurrency: 500 });
```

where `rows` is a JSON object with the data I want to update and it's keys
