### ISSUE TITLE
Update sub-sub-doc

### ISSUE THREAD

**Issue by npalem** [Automattic/mongoose#5723]
Here is my schema:
```
const Test = new Schema({
_id: String,
subscribers: [{
subscriberId: String,
users: [{
userId: String,
mode: [String]
}]
}]
}

```
I am trying to pull an element from users array for a given match. Here is my query.

```
  Test.findOneAndUpdate({
    _id: '123'
  }, {
      subscribers: {
        subscriberId: 'sub-123',
        $pull: {
          users: {
              userId: 'user-123'
          }
        }
      }
    }, { multi: false, new: true }, (err, doc) => {
      if (err) {// throw error}
      else{//do something}
});
```

It's removing all the elements from the users array. 

Could you please help me resolving this problem? Or Can anyone suggest a better solution?
I already have another solution which uses index to remove from array and then use doc.save(). But, I would like to implement using findOneAndUpdate().

**Comment by vkarpov15** [comment]
You're using `$pull` incorrectly, it should be at top level

```javascript
  Test.findOneAndUpdate({
    _id: '123'
  }, {
      $pull: {
        subscribers: { subscriberId: 'sub-123', 'users.userId': 'user-123' }
    }, { multi: false, new: true }, (err, doc) => {
      if (err) {// throw error}
      else{//do something}
});
```

**Comment by vkarpov15** [comment]
See https://docs.mongodb.com/manual/reference/operator/update/pull/ for more examples

**Comment by npalem** [comment]
The above example removes entire subscriber element. I am trying to remove only from users array.

**Comment by vkarpov15** [comment]
Can you please clarify? I don't understand.

**Comment by npalem** [comment]
Sure!

For example:

```
{
   _id: 1,
   subscribers: [
      { subscriberId: "A", users: [{userId: 'X', mode: ['m']}, {userId: 'Y', mode: ['m']}] },
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}] }
   ]
}
{
   _id: 2,
   results: [
      { subscriberId: "C", users: [{userId: 'X', mode: ['m']}, {userId: 'Y', mode: ['m']}]  },
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}]  }
   ]
}
```
If we apply the following query;
```
Test.findOneAndUpdate({
    _id: '1'
  }, {
      $pull: { subscribers: { subscriberId: 'A', 'users.userId': 'X' } }
    }, { multi: false, new: true }, (err, doc) => {
      if (err) {// throw error}
      else{//do something}
});
```

Results are:

```
{
   _id: 1,
   subscribers: [
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}] }
   ]
}
{
   _id: 2,
   results: [
      { subscriberId: "C", users: [{userId: 'X', mode: ['m']}, {userId: 'Y', mode: ['m']}]  },
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}]  }
   ]
}
```

The above query removes entire subscriber element. But I only want to remove user element for a given match. So I need the following results;

```
{
   _id: 1,
   subscribers: [
      { subscriberId: "A", users: [{userId: 'Y', mode: ['m']}] },
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}] }
   ]
}
{
   _id: 2,
   results: [
      { subscriberId: "C", users: [{userId: 'X', mode: ['m']}, {userId: 'Y', mode: ['m']}]  },
      { subscriberId: "B", users: [{userId: 'Y', mode: ['m']}]  }
   ]
}
```

**Comment by vkarpov15** [comment]
Unfortunately there's no way to do this in MongoDB right now, MongoDB's support for nested arrays isn't as neat as its support for non-nested arrays. You will have to load the document using `.findOne()`, do the removal logic in node, then `.save()`

**Comment by npalem** [comment]
Hi @vkarpov15, Thank you for the response. 

Yes, I already have the other solution, but I was just wondering if we could do that in one step using mongoose. Because here in this situation, the combination of .findOne() and .save() depends on indexes. Which sometimes (especially for simultaneous queries) do not remove a proper element from array.

I really look forward to have this solution from mongoose/mongodb.

**Comment by vkarpov15** [comment]
Yeah that's an unfortunate limitation. You could try changing your data structure to flatten the array, so instead of `[{ subscriberId: "A", users: [{userId: 'Y', mode: ['m']}] }]` you have `[{ subscriberId: "A", userId: 'Y', mode: ['m']}]`, or [queueing](http://thecodebarbarian.com/queueing-function-calls-with-node.js-and-mongodb.html).
