### ISSUE TITLE
Mongoose date query is not working

### ISSUE THREAD

**Issue by Thefounderscafe** [Automattic/mongoose#5725]
Node.js `7.10.1` MongoDB `3.4.9` mongoose `4.12.3`
So, the situation is I need to get all the bookings between a date bracket.

```
  let date1 = new moment.tz(req.body.startDate, 'GMT');
  let date2 = new moment.tz(req.body.startDate, 'GMT');
  date1 = date1.toDate();
  date2 = date2.hour(date2.hour() + 24);
  date2 = date2.toDate();
  Meeting.find({
    startDate: {$gte: date1, $lt: date2},
    planId: req.params.planId,
    activeStatus: true
  })
```
I am not receiving any data with this. but then if I try this in mongo shell
`db.meetings.find('startDate': {'$gte': ISODate('2017-10-21T16:30:00Z'), '$lte': ISODate('2017-10-22T16:29:59Z')})`. I get the results, that I am expecting.

Could you help me understand this behavior? What is that I am doing wrong?

**Comment by star212** [comment]
i had same problem
