### ISSUE TITLE
Setting values based on other fields on creation and update.

### ISSUE THREAD

**Issue by JonathanWbn** [Automattic/mongoose#5727]
I want to have a field which creates and updates its value based on other values of the document. I don't want to use virtuals but instead, have an actual value in the document.

Given this schema:
```
const calculatorSchema = new mongoose.Schema({
  a: Number,
  b: Number,
  sum: Number
});
```
I am looking for a way to automatically update the `sum` based on `a` and `b`.

For the creation I am using the `save` middleware:
```
calculatorSchema.pre('save', function (next) {
  if (isNumber(this.a) && isNumber(this.b)) this.sum = this.a + this.b;
  next();
});
```

But when it comes to updating, I can't find a good solution. This is what I was trying:
```
calculatorSchema.pre('update', function (next) {
  const update = this.getUpdate();
  // this is where it gets ugly (i would also have to check the .$set...
  if (isNumber(update.a) && isNumber(update.b)) {
    this.update({}, { sum: update.a + update.b });
  }
  next();
});
```

Since I don't have access to the updated document in the `update` hook, this doesn't work like the `save` hook.

Is there a way to do this?

**Comment by varunjayaraman** [comment]
Not that I know of. Is it possible for you to use `save` only when you are updating those fields?

**Comment by JonathanWbn** [comment]
@varunjayaraman Is the only way to use `safe` for updating to do a `find`, then update values on the returned document and then call `safe` or are there any methods that combine those i.e. a `findOneAndUpdate` that uses `safe` under the hood?

**Comment by vkarpov15** [comment]
The right way to do this is using `pre('update')`. Can you explain why that doesn't work for your case?

**Comment by JonathanWbn** [comment]
@vkarpov15 In the `pre('save')`, I have access to the document, so I can easily do calculations or whatever. In the `pre('update')` I can only access the update object, which might not include all the values I need for my calculation. I would need to be able to get the full updated document.

**Comment by vkarpov15** [comment]
Yeah if you need the full document you need to use `pre('save')`, or you can fetch the document using `findOne()` in your `pre('update')`. There's no guarantee that the document is in memory when you do `update()`
