### ISSUE TITLE
Query not executing

### ISSUE THREAD

**Issue by chriskacerguis** [Automattic/mongoose#5729]
I seem to be running into an odd issue.  I'm trying to iterate over the results of a ```.find()```, do something, then update the document.  However, it never seems to run the update.  Here's an example:
```node
// Doesn't work
Model.find(function (err, items) {
  if (err) return console.log(err)
  items.forEach(function (item) {
    var query = {name: item.name}
    Model.findOneAndUpdate(query, {updated_at: Date.now()}, function (err, doc) {
      if (err) return console.log(err)
      console.log(doc)
    })
  })
})

// Works!
var query = {name: 'John Doe'}
Model.findOneAndUpdate(query, {updated_at: Date.now()}, function (err, doc) {
  if (err) return console.log(err)
  console.log(doc)
})
```

The ```Model.findOneAndUpdate``` never seems to run, I don't know if I'm doing something wrong, or if there is some strange bug.  Running Node 8.7.0, and MongooseJS 4.12.1

**Comment by varunjayaraman** [comment]
Check the docs: http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate 

if you dont pass `{ new: true }` as an option, `doc` will be the document BEFORE the update was applied. So your log is just misleading
