### ISSUE TITLE
Discriminated model using the wrong connection when dealing with multiple connections

### ISSUE THREAD

**Issue by drummerboof** [Automattic/mongoose#5732]
Mongoose: 4.12.3
OS: OSX 10.11.6
Node 8.2.1 (also happens on 7.8)
MongoDB: 3.4.4

## Summary
**When using multiple connections, documents found using a model with discriminators registered to a secondary connection are bound to the master connection despite coming from the secondary connection. Any updates the documents are applied against the wrong collection and silently do nothing (presumably because no document exists with the ID).**

I have created a repo which reproduces the issue here: https://github.com/drummerboof/mongoose-discriminator-issue/blob/master/index.js

## Background
In our application we have a master database and secondary databases (one per "application"). We have some schemas which are available in both the master databases and secondary databases. Users can define global cross application template data which they can then use in their application by copying it across (which clones it from the master database into the application databases).

We register all of our schemas against the root mongoose import during bootstrap. and then when we want to use a model we grab the connection we are interested in (master or application specific) and get the model class to begin querying:

#### During bootstrap
```javascript
mongoose.model('stuff', StuffSchema);
```

#### On a request
```javascript
const Stuff = resolvedConnection.model('stuff');
const stuff = await Stuff.findById(id);
```

The models are all registered with the main connection, and when requested against a secondary connection they are correctly "subclassed", bound to the secondary connection and cached against that connection object's models map.

This has been working fine until we used this pattern with a single collection storing multiple discriminated models. We register the discriminated models at the same time during bootstrap:

#### During bootstrap
```javascript
const Stuff = mongoose.model('stuff', StuffSchema);
Stuff.discriminator('special-stuff', SpecialStuffSchema);
```

Later on, we use the parent discriminator model to query for a document by ID from a secondary collection. Mongoose correctly creates us an instance based on the type of the document found, BUT, the database connection associated with the created instance is incorrect.

#### On a request
```javascript
// id is an ID of a stuff document in the collection stored with __t = special-stuff
// resolvedConnection is the secondary connection
const Stuff = resolvedConnection.model('stuff');
const stuff = await Stuff.findById(id);
```
In the example above, stuff is a SpecialStuff document retrieved from the collection in the secondary database, but is bound to the master connection despite being found using a model bound to the secondary connection. If we update and save the document, the update is not applied to Mongoose as it tries to update a document in the primary database collection which doesn't exist. This does not return an error but silently does nothing.

## Current Behaviour
Documents found using a model with discriminators registered to a secondary connection are bound to the master connection despite coming from the secondary connection.

## Expected Behaviour
Documents found using a model with discriminators registered to a secondary connection are bound to the connection of the model from which they were queried.

**Comment by vkarpov15** [comment]
Thanks for the repro script, will investigate ASAP :+1:

**Comment by drummerboof** [comment]
Thanks @vkarpov15 let me know if there's anything I can do to help!

**Comment by vkarpov15** [comment]
@drummerboof unfortunately this is currently expected behavior, although I admit this is super confusing and we should consider changing this in the next backwards breaking release.

The issue is that when you call `secondary.model('shape');`, you're getting the default connection's 'shape' model because you have not created a 'shape' model on the `secondary` connection. Your code with the below changes works as expected.

```javascript
// We retrieve our connection scoped models using the model method on the connections.
// This works as expected for non discriminated models - the model is scoped to the connection.
const SecondaryShape = secondary.model('shape', ShapeSchema);
const PrimaryCircle = primary.model('circle');
const SecondaryCircle = SecondaryShape.discriminator('circle', CircleSchema);
```
