### ISSUE TITLE
Errors swallowed on schema.pre('save') middleware hook

### ISSUE THREAD

**Issue by danielgormly** [Automattic/mongoose#5738]
Hi,

I have a possible bug:
```javascript
const mySchema = new mongoose.Schema( ... )
mySchema.pre('save', function (next) {
	console.log('Throwing error'); // Throwing error
	throw new Error('error'); // Error
	next();
});
const MyModel = mongoose.model('User', mySchema);
MyModel.create({ modelSchema })
.then(data => console.log(data)) // never gets called
.catch(err => console.log(err)) // never gets called
```

**What is the current behavior?**
Any errors thrown from pre save middleware hooks are suppressed. Also I have tried to include an error handler which isn't called either.
```javascript
userSchema.pre('save', function(error, res, next) {
	console.log(error);
	next();
});
```

**What is the expected behavior?**
On `myModel.create()`, trigger rejection handler.

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose version: 4.12.4
Node version: 8.7.0
Mongodb: 3.4.9

Thanks!

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will investigate ASAP
