### ISSUE TITLE
Can virtual be used as query criteria？

### ISSUE THREAD

**Issue by zwzw911** [Automattic/mongoose#5739]
4.12.4

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Define a virtual getter like below  

*const collSchema=new mongoose.Schema(
    duration:{type:Number}, 
    cDate:{type:Date,default:Date.now},
)
collSchema.virtual('isExpire').get(function(){
        return (this.cDate.getTime()+this.duration\*86400000)<Date.now()
})
mongoose.model(“Daily”,collSchema)
const collModel=connectedDb.model(“Daily”,collSchema)*  

then try to find the record not expire by *collModel.find({"isExpire:false"})*, it always return empty array; if use other non virtual field as query criteria, expected document return.

So I wonder if virtual can be used as query criteria? if not, is it possible add such feature into mongoose?  

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
Not possible. The purpose of virtuals is that they are not stored in the database, so you can't query by them. If you want to query by a computed property, you usually want to use getters/setters rather than virtuals.
