### ISSUE TITLE
Model.find(undefined, ..... Return all data Model

### ISSUE THREAD

**Issue by UsuJuan** [Automattic/mongoose#5741]
When executed Model.find(undefined, ... Return all my data register in this model.
When executed Model.findOne(id: undefined, ... Return my first register in this model collection is the same like Model.findById(undefined,.

Is a bug or I am doing something wrong ??

**Comment by vkarpov15** [comment]
I don't understand, can you please clarify with some code samples?

**Comment by UsuJuan** [comment]
`User.find(undefined, function(err, user) {
        if (err) {
            return done(err, false);
        }
        return user;
    });`
This function return ====> 
[
{'id':'4234234234','name':'user1'},
{'id':'36353634','name':'user2'},
{'id':'3663634623','name':'user3'},
{'id':'23523523','name':'user4'}
], this all data in my collection.

**Comment by varunjayaraman** [comment]
thats not a bug, you arent really passing in a query so mongoose assumes you want everything in the collection:

```javascript
