### ISSUE TITLE
share connection pool across databases on same server

### ISSUE THREAD

**Issue by vkeyrockz** [Automattic/mongoose#5746]
am working on creating multi-tenant app with db per tenant but common schema and app logic. so i need to create the connection to mongodb server with pool size 'x' and switch db(share pool) on demand while users playing the api.

currently am doing it with native node mongo driver,

```
const createConnection =  ()=>{
        return new Promise((res,rej)=>{
          // am not mentioning db name so it connect to admin on localhost
            MongoClient.connect('mongodb://localhost', function(err, db) {
                if(err){
                    rej(err);
                } else{
                    res(db);
                }
            });
        });
    };

const dbConnection = createConnection();
app.post(/products,(req,res)=>{
//assume the user is make this call is 'sam' his db is 'sam'
dbConnection.then((db)=>{
const switchedDb = db.db('sam');
switchedDb.collection('product').save(data);
})
});
```

note : here i make the connection with server and share the connection pool by switching to db on demand.

how can i do this with mongoose.  i no need to create connecion every time and i need to share the same connection pool on demand.

**Comment by componentDidMount** [comment]
Hi @vkeyrockz, I think you want to use useDb (https://github.com/Automattic/mongoose/blob/4.12.4/lib/drivers/node-mongodb-native/connection.js#L77:L87), hope that help. I used this in the past do accomplish the same thing, multi-tenancy on-the-fly.

**Comment by vkeyrockz** [comment]
but useDb seems to open new connection i.e like new connection pool. i want to share the connection pool in existing connection.

**Comment by componentDidMount** [comment]
"Switches to a different database using the same connection pool"

**Comment by vkeyrockz** [comment]
if thats the case thats really i want. but saw several issues on usedb 
https://stackoverflow.com/questions/25300584/mongoose-usedbname-not-allowing-more-than-10-concurrent-request
is this right? and it is overcomed on latest versions?

**Comment by componentDidMount** [comment]
We never faced any issues with it using it in a large scale application with 10+ different tenants (dbs), I don't know what you mean with overcomed though, when we used it, it was mongoose v3, I've not yet used v4 for any project with usage of useDb, so I cannot speak for that, sorry.

**Comment by vkarpov15** [comment]
Mongoose doesn't currently have a helper for this but you can just do `dbConnection.db.db(newDb)` and that will [switch the database the underlying mongodb connection uses](http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#db). I would recommend you be very careful doing this though, if you switch databases while operations are still in flight you may get inconsistent results. If you're doing multi-tenant and want to share connection pools, you need to be careful and ensure that there are no in-flight operations when you switch.

**Comment by vkeyrockz** [comment]
thankyou so much @vkarpov15 this answer is actually i want.   my need is sharing connection pool, but i have to be aware of in-flight operations because mongoose shares a same underlying mongo-native connection. So here there is a risk for miss DB operations. My one more doubt is , if i use "dbConnection.db.db(newDb)" this native switch i have to recreate the mongoose model or not?.
Note : my schemas are common across tenant. and here am only switching underlying connection.

**Comment by vkarpov15** [comment]
@vkeyrockz I'll need to investigate to give you more information. Will get back to you ASAP

**Comment by vkarpov15** [comment]
So I was wrong in my previous comment, `dbConnection.db.db(newDb)` actually would not work because that [creates a new db handle rather than modifying the existing one](http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html#db). @componentDidMount is right, you'll have to use `useDb()`: http://mongoosejs.com/docs/api.html#drivers_node-mongodb-native_connection_NativeConnection-useDb . Unfortunately, you'll also have to recreate your models on the new connection as well, so `const newConn = oldConn.useDb('otherDb'); newConn.model('myModel', mySchema);`
