### ISSUE TITLE
Help with structure containing Array of Objects with nested Arrays

### ISSUE THREAD

**Issue by damianfabian** [Automattic/mongoose#5747]
**Do you want to request a *feature* or report a *bug*?**
Possible Bug or maybe I'm doing something wrong.

**What is the current behavior?**
I have this structure:

```
{
name: 'root',
path: '/',
children: [
  { name: 'Folder1', path: '/Folder1', children: [] },
  { name: 'Folder2', path: '/Folder2', children: [] }
]
}
```

I'm trying to simulate a file system, I have been available to create children to the root object, but if I add a new item in any children, I don't get any error or problem but the data is not saved. If I use the object returned by the save function the subfolder is there, but the subfolder is not saved to the database.

I already try using: 
```
// I already have a function that inspect all the object for the correct node,  this is just an example
const node = model.children.find(f => f.path === param.path)
// Here I can not use set because this array is not a MongooseArray
node.children.push({ name: 'newFolder', path: `${param.path}/newFolder`, children: [] })
model.markModified('anything') // it does not work for me.

model.save(function(err) { 
  if (err) console.log(err)    // Not error handle or returned
}).then(function(doc) {
  return doc // Here the value is correct, I can see the new Folder belongs to the array
})
```

I made a debug and all the arrays inside the first children are normal Arrays instead of the first children attached to the root object that is a MongooseArray. I don't know if that could be the problem. 

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce just create the previous structure and try to add a new item to the children to get something like this:

```
{
name: 'root',
path: '/',
children: [
  { name: 'Folder1', path: '/Folder1', children: [
      { name: 'SubFolder1', path: '/Folder1/SubFolder1', children: [] }
    ] 
  },
  { name: 'Folder2', path: '/Folder2', children: [] }
]
}
```

**What is the expected behavior?**
I want to be available to save/modify infinite children in my structure to emulate a file system.

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB: 3.4.7
NodeJS: V8.4.0
mongoose: 4.7.1

**Comment by varunjayaraman** [comment]
What do you mean by its not a mongoose array? Is it a `Mixed` type?

**Comment by damianfabian** [comment]
No, I mean if you made debug, you can see the arrays attached to the Mongoose Model are MongooseArray objects, but the arrays inside those MongooseArray are simple array Objects.

**Comment by vkarpov15** [comment]
What do your schemas look like?

**Comment by damianfabian** [comment]
Hi @vkarpov15 my schema looks like this:

`
var Types = require('mongoose-easy-types').Types;
var schema = mongoose.Schema({
        created_at: Types.date.past({ default: Date.now }),
	path: Types.random.word({ require: true }),
        user : [{ type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }],
	name: Types.name.firstName({ required: true }),
        size: Types.random.number({ default: 0}),
        folders: Types.random.number({ default: 0}),
        files: Types.random.number({ default: 0}),
        children : Types.helpers.shuffle() //This define an array type
});
`

I'm using Types just to generate fake models with Testing. You can see the docs in [Here](https://github.com/Chkhikvadze/mongoose-easy-types).

I was able to save the data replacing all the node from the root children element like this:

`Model.children.set(1, firstChild)`

But my concern is why I could not do this operation inside a children of firstChild? I found the children element from firstChild is a simple array object. However, Model children element is a MongooseArray type. 

I was expecting to affect only the node I want to change, not all the element from the root.

**Comment by vkarpov15** [comment]
That's because `children: Types.helpers.shuffle()` is equivalent to `children: { type: [] }`, which means `children` is an array of [mixed type](http://mongoosejs.com/docs/schematypes.html#mixed). Mixed means no casting, validation, or change tracking, just a plain JS object.
