### ISSUE TITLE
Schema cloning does not clone the queries property

### ISSUE THREAD

**Issue by amerryma** [Automattic/mongoose#5752]
**Do you want to request a *feature* or report a *bug*?**
bug/feature

**What is the current behavior?**
`schema.clone()` does not currently clone the `schema.queries` property.

**If the current behavior is a bug, please provide the steps to reproduce.**

Basically I have a plugin that adds some ACL to a query. For example:
``` javascript
schema.query.asUser = function (user) {
  return this.find({
    // my query
  })
}
```
Then, I have another plugin that ends up cloning this schema. 

**What is the expected behavior?**
The problem is that the `schema.clone()` method does not clone the chained queries so the `asUser` method does not exist on the cloned schema.

**Please mention your node.js, mongoose and MongoDB version.**
```
node.js: 8.7.0
mongoose: 4.11.10
MongoDB: 3.4.9
```

**Comment by varunjayaraman** [comment]
yeah this looks like a bug:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const assert = require('assert');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5752`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    yield mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true })
    const schema = new mongoose.Schema({
      name: String
    });

    schema.query.test = function() {
      return 'test';
    }

    const Model = mongoose.model('Model', schema);

    const clone = schema.clone();
    assert.ok(clone.query.test);
  });
}
```
