### ISSUE TITLE
Types for flattened structure of ConnectionOptions 

### ISSUE THREAD

**Issue by bompi88** [Automattic/mongoose#5755]
**Do you want to request a *feature* or report a *bug*?**
feature. located here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5baaeafba907bac24c091bdf38048313835ebfac/types/mongoose/index.d.ts#L354

**What is the current behavior?**
Types for new flattened option structure are not available. Getting the following TypeError:
```txt
error TS2345: Argument of type '{ useMongoClient: true; socketTimeoutMS: number; keepAlive: boolean; reconnectTries: number; }' is not assignable to parameter of type 'ConnectionOptions'.

Object literal may only specify known properties, and 'socketTimeoutMS' does not exist in type 'ConnectionOptions'.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Using `typescript v2.5.x`, and `@types/mongoose v4.7.24` transpile the following:
```js
mongoose.connect('mongodb://localhost/myapp', {
    useMongoClient: true,
    socketTimeoutMS: 0,
    keepAlive: true,
    reconnectTries: 30
});
```
**What is the expected behavior?**
Typescript should transpile successfully.

**Please mention your node.js, mongoose and MongoDB version.**
`node v8.6.0`, `mongoose v4.11.14`, `mongoDB v3.4.9`

**Comment by vkarpov15** [comment]
This is a bug with DefinitelyTyped. Mongoose does not have any officially supported typescript bindings, please report issues on DefinitelyTyped's repo :+1:
