### ISSUE TITLE
ipv6 connect stopped working after updating to 4.10+ (host has no ipv4)

### ISSUE THREAD

**Issue by iliakan** [Automattic/mongoose#5760]
The issue appeared when I updated mongoose 4.9 to 4.10.

We had a connection string like "mongodb://my.mongo.com/db".
Our mongodb has only ipv6, no ipv4.

After updating to 4.10+ mongoose starts to show "MongoError: getaddrinfo ENOTFOUND my.mongo.com". So the old code stops working.

I guess, we should supply `family=6` somewhere?

Posting this, because it looks strange that updating to a minor version broke the existing connection code.

**Comment by amaxcz** [comment]
if mongodb host resolves via DNS and has only AAAA, it's should use ipv6 by default.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:

**Comment by vkarpov15** [comment]
Thanks for reporting, this is an issue with the underlying mongodb driver (see https://github.com/mongodb-js/mongodb-core/pull/183) that we pulled in on 4.11.6 with this commit: https://github.com/Automattic/mongoose/commit/93e771ce5678c20da3a8dd08a4b77de8a1380446 . I put in a PR to fix it here: https://github.com/mongodb-js/mongodb-core/pull/230, I'm going to push to get that fix bubbled up into mongoose ASAP.

As a workaround, do this:

```javascript
mongoose.connect('mongodb://ip6-localhost:27017', { useMongoClient: true, family: 6 })
```

And you should be able to connect normally. Sorry for the trouble :palm_tree:

**Comment by iliakan** [comment]
I see those were merged, maybe the bug can be closed?

**Comment by vkarpov15** [comment]
@iliakan unfortunately not, because the mongodb driver hasn't shipped a release with these changes. They're currently busy working on the 3.0.0 release and haven't had time to make another 2.x release

**Comment by vkarpov15** [comment]
Fixed in the 4.x branch. Thanks for your patience, the mongodb node driver team was swamped trying to release v3 of the driver to support mongodb 3.6, but they got a new release out. Will ship 4.13.9 shortly :+1:
