### ISSUE TITLE
How can I get populated doc after 'post' middleware for 'save'?

### ISSUE THREAD

**Issue by qwang07** [Automattic/mongoose#5768]
MongoDB: v3.0 Node: v8.7.0 Mongoose: v4.12.0
I want to get populated doc for the doc that I just saved using Model.create(). I try to implement it in 'post' middleware for 'save' but it doesn't return by Model.create().

```
   MySchema.pre('post', async function (doc) {
     const populatedDoc = await doc.populate('user').execpopulate()
     console.log(populatedDoc) // that's correct, but how can I return it by Model.create()
   })
```
Or I have to populate after Model.create()?

**Comment by vkarpov15** [comment]
Unfortunately no good way to do that with post hooks currently, in an ideal world you'd do :point_down: , but that's waiting on #3232. Follow that issue for updates

```javascript
MySchema.post('save', function(doc, next) {
  doc.populate('user').execPopulate(function() {
    next();
  });
});
```

**Comment by BorntraegerMarc** [comment]
@vkarpov15 With 5.0 now released should we maybe add this post hook to the docs?

**Comment by BorntraegerMarc** [comment]
And how would it be done with `insertMany`? can we also use population directly in a post hook?

**Comment by vkarpov15** [comment]
@BorntraegerMarc thanks for your PR. You should be able to `populate()` in `post('insertMany')` as well, don't see why not.
