### ISSUE TITLE
Mongoose 4.12.5 Error during npm start

### ISSUE THREAD

**Issue by docmur** [Automattic/mongoose#5769]
Hey Guys

When I run npm start, after install Mongoose 4.12.5 I'm getting:

> Error
>     at MongooseError (C:\Users\docmur\git\jPanel\node_modules\mongoose\lib\error\index.js:12:11)
>     at Timeout._onTimeout (C:\Users\docmur\git\jPanel\node_modules\mongoose\lib\model.js:146:18)
>     at ontimeout (timers.js:386:14)
>     at tryOnTimeout (timers.js:250:5)
>     at Timer.listOnTimeout (timers.js:214:5)

That block of code is:

```
function MongooseError(msg) {
  Error.call(this);
  if (Error.captureStackTrace) {
    Error.captureStackTrace(this);
  } else {
    this.stack = new Error().stack;
  }
  this.message = msg;
  this.name = 'MongooseError';
}
```

Is this an existing issue?  My package.json:

```
{
  "name": "jpanel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "babel-node index.js --presets es2015,stage-2"
  },
  "repository": {
    "type": "git",
  },
  "author": "Andrew Murdoch",
  "license": "ISC",
  "dependencies": {
    "bluebird": "^3.5.0",
    "body-parser": "^1.17.2",
    "eslint": "^4.4.0",
    "express": "^4.15.3",
    "express-graphql": "^0.6.7",
    "graphql": "^0.10.5",
    "graphql-server-express": "^1.0.5",
    "graphql-tools": "^1.1.0",
    "mongodb": "^2.2.30",
    "mongoose": "^4.12.5",
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "express-graphql": "^0.6.7",
    "graphql": "^0.10.5"
  }
}
```
I've had the same issue with 4.12.4.

Thanks
Docmur

**Comment by vkarpov15** [comment]
Can you please provide more substantial code samples?

**Comment by docmur** [comment]
Sure, I'll post the actual mongoose file when  I get home.

**Comment by docmur** [comment]
Weird, this problem went away without me doing anything, if I see it again, I'll post code, now it's working fine.
