### ISSUE TITLE
Try get model

### ISSUE THREAD

**Issue by cyrilchapon** [Automattic/mongoose#5781]
One could find very useful to have a way to "try to get a model".

My use case is the following :

I'm trying to create a "singleton-model", requirable cross-project.

I've made a git project containing my schemas and models, exported like this :

**model/bear.js**
```
const modelName = 'Bear';

module.exports = function(mongoose) {
  let model = mongoose.getModel(modelName);

  if (!model) {
    model = mongoose.model(
      modelName,
      new mongoose.Schema({
        name: String
      })
    );
  }

  return model;
};
```

**index.js**
```
module.exports = {
  model: {
    bear: require('./model/bear')
  }
}
```

That I share accross projects, I require them this way

```
let myMongooseInstance = //retreive my local mongoose instance
let Bear = require('my-model-module').model.bear(myMongooseInstance);
```

Which is ok, but ONLY because I defined somewhere (once per project..)
```
mongoose.getModel = function(modelName) {
  try {
    return this.model(modelName);
  } catch(err) {
    if(err instanceof this.Error.MissingSchemaError) {
      return null;
    }
    throw err;
  }};
}
```

Indeed, the only way I found to "get current instance internal model by name" is `Mongoose.model()` which is actually both a setter AND a getter, and throws when :
- We access a non-existing model
- We re-set an existing model

Is there a better way to do this ?

**Comment by vkarpov15** [comment]
No better way to do this right now. You're welcome to make this a plugin but I'm hesitant to put this helper into the core lib unless there's a lot of demand for it. Gonna close this for now but thanks for opening this issue :+1: :palm_tree:

**Comment by cyrilchapon** [comment]
I turned it a one-liner by checking ` modeNames()` and ES6 `.includes()` as so :

```
if(mongoose.modelNames().includes(modelName)) {
  return mongoose.model(modelName);
}

return mongoose.model(modelName, /*...define schema...*/);
```
