### ISSUE TITLE
Schema.Type.Mixed fields do not update when type coercion is in question

### ISSUE THREAD

**Issue by zlatinejc** [Automattic/mongoose#5785]
Version 4.13.0

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Mongoose fails to save correct (new values of different type) when type coercion is executed on a updating field that is of type Schema.Types.Mixed.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a simple model with an attribute of Schema.Type.Mixed
2. Insert a record with a type of an empty string "" to an attribute that is of type from the 1. step
3. Update a record from step 2. on a field which is of type from step 1. with a value 0 that is of type Integer
4. The field of the updating record is not updated with the new value
5. You can reproduce this error updating the same field with other values of different types eg: false, undefined ... basicly with any value that touches the infamous Type Coercion field of JavaScript.
  
**What is the expected behavior?**
Just save the value I pass to a specific field that is of type Schema.Types.Mixed -> it is the reason why I use this type in the first place :)

**Please mention your node.js, mongoose and MongoDB version.**
Node 4.8.4, MongoDB 3.4.6

**Comment by varunjayaraman** [comment]
@zlatinejc are you using `markModified()`?

**Comment by zlatinejc** [comment]
as a workaround, yes.

**Comment by vkarpov15** [comment]
Please provide code samples, converting prose to code is error prone

**Comment by zlatinejc** [comment]
OK, here we go:

1. Creating a simple model
```javascript
const mongoose = require('mongoose'),
SampleSchema = new Schema({
  value: {
    type: Schema.Types.Mixed,
    required: 'missing_value'
});
mongoose.model('SampleSchema ', SampleSchema );
```

2. Inserting initial record
```javascript
const initialRecord = new SampleSchema({ value : '' });
initialRecord.save(); // save OK, value has been set to ''
```

3. Updating existing record with new value of 0 (type Number)
```javascript
initialRecord.value = 0;
initialRecord.save(); // update OK, value has not been set to ''
```
4. The record's value is not updated to value of 0.
```javascript
console.log(initialRecord.value); // the value is still an empty string ''
```

5. The workaround I currently use, although I would prefer if would not to, is:
```
SampleSchema.pre('validate', (next) => {
  this.markModified('value');
  next();
});

PS: handling node's asynchrony is intentionally left out for the purpose of simplicity.

**Comment by varunjayaraman** [comment]
@zlatinejc you have to use `markModified()` with Mixed types, that's why I asked. 

Check the docs: http://mongoosejs.com/docs/schematypes.html

**Comment by zlatinejc** [comment]
So it is by design as I see ... inconvenient though imho.

Thx for clarification.
