### ISSUE TITLE
Cast error on Update

### ISSUE THREAD

**Issue by br0p0p** [Automattic/mongoose#5787]
Node: 8.9.0
Mongoose: 4.13.0
MongoDB: 3.4.5

---

**Originally, the User model was defined like so:**
```js
const userSchema = new Schema({
     name: Schema.Types.String,
     roles: [Schema.Types.String]
});

const User = mongoose.model('User', userSchema);
```
An example User would look like `{ _id: '...', name: 'John Smith', roles: ['admin', 'user'] }`.

**We updated the User schema to this:**
```js
const userSchema = new Schema({
    name: Schema.Types.String,
    roles: [{type: Schema.Types.ObjectId, ref: 'Role'}]
});
```
where the roles field contains `Role` `_id`s, where `Role` is another model we defined.

---

**My problem:**

I'm trying to write a migration that will update all the User documents to the new `Role` model but I keep getting a Cast error when doing an update: 

> `'Cast to ObjectId failed for value "admin" at path "roles" for model "User"'`

Is there a way to disable type casting for an update like this? As you can see, I've tried several options I thought might do the trick: `runValidators: false`, `strict: false`, `safe: false`, but to no avail.

**Flow:**
For every user with `{ roles: 'admin' }`:
- find the new "admin" `Role` document's `_id`
- push the `_id` to the `User.roles` field
- remove the old "admin" String from the `User.roles` field
- repeat for each role

**Code:**
```js
const roleConversions = [
  {
    oldName: "user",
    newName: "USER"
  },
  {
    oldName: "admin",
    newName: "ADMIN"
  }
];

roleConversions.map(async role => {
  try {
    const newRole = await Role.findOne({ name: role.newName });

    await User.update(
      { roles: role.oldName },
      { $push: { roles: newRole._id } },
      { runValidators: false, multi: true, strict: false, safe: false }
    );

    await User.update(
      { roles: role.oldName },
      { $pull: { roles: role.oldName } },
      { runValidators: false, multi: true, strict: false, safe: false }
    );
  } catch (err) {
    console.error(err);
  }
});
```

**Comment by vkarpov15** [comment]
Do the below instead, `User.collection.update()` will bypass mongoose casting entirely. You should usually do that for migrations because mongoose casting and validation tends to make migration scripts more cumbersome.

```javascript
await User.collection.update(
      { roles: role.oldName },
      { $push: { roles: newRole._id } },
      { runValidators: false, multi: true, strict: false, safe: false }
    );

    await User.collection.update(
      { roles: role.oldName },
      { $pull: { roles: role.oldName } },
      { runValidators: false, multi: true, strict: false, safe: false }
    );
```

**Comment by br0p0p** [comment]
Ah, thanks so much!
