### ISSUE TITLE
Mongoose library catching the exceptions thrown by chai library

### ISSUE THREAD

**Issue by SankaD** [Automattic/mongoose#5788]
I'm trying to test a functionality using mocha and chai libraries.

Since the chai expect throws an exception it's handled by mongoose library rather than the mocha library. This causes tests to crash at the first failure which goes through mongoose callback handling.

```
describe.only("mongoose test", function () {
it("test", function (done) {
    UserModel.find({}, function (error, user) {
        expect(1).to.equal(2);
        return done();
    });
});
});
```
which gives following error.

> error: uncaughtException: expected 1 to equal 2 date=Sat Nov 04 2017 13:35:17 GMT+0530 (Sri Lanka Standard Time), pid=13912, uid=null, gid=null, cwd=E:\Work\project\dev\project\server, execPath=C:\Program Files\nodejs\node.exe, version=v8.5.0, argv=[C:\Program Files\nodejs\node.exe, E:\Work\project\dev\project\server\node_modules\mocha\bin_mocha, --ui, bdd, --reporter, C:\Users\user.IntelliJIdea2017.2\config\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js, --recursive, E:\Work\project\dev\project\server\test\bdd], rss=83312640, heapTotal=61116416, heapUsed=40648848, external=18624866, loadavg=[0, 0, 0], uptime=191033.0283878, trace=[column=26, file=E:\Work\project\dev\project\server\test\bdd\tests.js, function=null, line=246, method=null, native=false, column=16, file=E:\Work\project\dev\project\server\node_modules\mongoose\lib\model.js, function=null, line=4020, method=null, native=false, column=48, file=E:\Work\project\dev\project\server\node_modules\kareem\index.js, function=null, line=213, method=null, native=false, column=16, file=E:\Work\project\dev\project\server\node_modules\kareem\index.js, function=null, line=131, method=null, native=false, column=7, file=internal/process/next_tick.js, function=_combinedTickCallback, line=131, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[AssertionError: expected 1 to equal 2, at E:\Work\project\dev\project\server\test\bdd\tests.js:246:26, at E:\Work\project\dev\project\server\node_modules\mongoose\lib\model.js:4020:16, at E:\Work\project\dev\project\server\node_modules\kareem\index.js:213:48, at E:\Work\project\dev\project\server\node_modules\kareem\index.js:131:16, at _combinedTickCallback (internal/process/next_tick.js:131:7), at process._tickCallback (internal/process/next_tick.js:180:9)]

Although following test fails without crashing the program.  

```
describe.only("mongoose test", function () {
it("test", function (done) {
    // expect(1).to.equal(2);

    throw Error("Test");

    UserModel.find({}, function (error, user) {
        // expect(1).to.equal(2);
        return done();
    });
});
});
```
Is there any workaround for this? Or am I doing something wrong here?

Following is from line \node_modules\mongoose\lib\model.js:4020:16

```
Model.$wrapCallback = function(callback) {
  var _this = this;
  return function() {
    try {
      callback.apply(null, arguments);
    } catch (error) {
      _this.emit('error', error);
    }
  };
};
```
library versions are as follows...

> "mongodb": "2.2.33",
> "mongoose": "4.13.0",
> "chai": "4.1.2",
> "mocha": "4.0.1",

[Asked on Stackoverflow](https://stackoverflow.com/questions/47108677/mocha-tests-crashing-due-to-mongoose-callback-handling)

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap :+1:

**Comment by varunjayaraman** [comment]
This just has to do with error handling in callbacks. You either need to do `try catch` or you could handle the mongoose errors with error middleware or add a hook to the model:

```javascript
const mongoose = require('mongoose');
const co = require('co');
const { expect } = require('chai');

mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5788`;


mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true });

const schema = new mongoose.Schema({ age: Number });

const Model = mongoose.model('Model', schema);

Model.on('error', err => {
  console.log('handled error', err);
});

Model.find({}, function(error, result) {
  expect(1).to.equal(2); 
  console.log('hi!');
});

```

**Comment by vkarpov15** [comment]
Below script works just fine for me with mocha 4.0.1 and mongoose 4.13.0. Can you modify the below script to reproduce your issue?

```javascript
const { expect } = require('chai');
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true });
mongoose.Promise = global.Promise;

const UserModel = mongoose.model('Test', new mongoose.Schema({}));

describe.only("mongoose test", function () {
  it("test", function (done) {
    UserModel.find({}, function (error, user) {
        expect(1).to.equal(2);
        return done();
    });
  });
});
```

```
$ ./node_modules/.bin/mocha gh-5788.js 


  mongoose test
    1) test


  0 passing (46ms)
  1 failing

  1) mongoose test
       test:

      Uncaught AssertionError: expected 1 to equal 2
      + expected - actual

      -1
      +2
      
      at gh-5788.js:12:22
      at model.Query.<anonymous> (/home/val/Workspace/MongoDB/mongoose/lib/model.js:4032:16)
      at /home/val/Workspace/MongoDB/mongoose/node_modules/kareem/index.js:273:21
      at /home/val/Workspace/MongoDB/mongoose/node_modules/kareem/index.js:131:16
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)



^CTerminated
$ tail -n 2 node_modules/mocha/package.json 
  "version": "4.0.1"
}
$ 
```
