### ISSUE TITLE
findOneAndUpdate inserting a new document upon pushing items to existing document

### ISSUE THREAD

**Issue by slibin** [Automattic/mongoose#5789]
I have a use case where i need to create a new document when user submit enquiry for the first time and add message to the first document if he\she send a new request.

Creating the first document works fine perfectly with my code.When hit the api for the second time to add new items to existing document it's creating a new document with an empty array as given below.

I tried all the options with my limited knowledge.Any help in resolving the issue will be really appreciated

Model

    const collection = 'contactus';
    var contactUsSchema = new Schema({
        emailID: {
            type: String,
             required: false, unique: true, trim: true, match: /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/           
        },
        userFullName: { type: String, required: false, unique: false, trim: true },
        enquiry: [{
            subject: { type: String, required: false, unique: false, trim: true },
            message: { type: String, required: false, unique: false, trim: true },
            updated_at: { type: Date, required: false, default: Date.now }
        }]
   });

controller

      var mongoose = require('mongoose');
     var Promise = require('promise');
     var contactusModel = mongoose.model('contactus');

     module.exports.submitContact = function (req, res) {

      var contactusSchema = new contactusModel();

    new Promise(function (resolve, reject) {

        contactusModel.findOne({ "emailID": req.body["emailID"]}, function (err, doc) {
            if (doc == null) { /* If it's the first enquiry from user*/
                contactusSchema.emailID = req.body["emailID"],
                    contactusSchema.userFullName = req.body["userFullName"],
                    contactusSchema.enquiry =
                    [{
                        subject: req.body["subject"],
                        message: req.body["message"]
                    }]
                    resolve()

            } else {  /* Update if atlest one query is present for the same user*/
                contactusModel.findOneAndUpdate({ "emailID": req.body["emailID"]},
                    {                        
                        "$push": {
                            "enquiry": {
                                "subject": req.body["subject"],
                                "message": req.body["message"],                                                               
                            }
                        }
                    },
                    { new: true,upsert:false}, function (err, doc) {
                        if (err) { 
                            //do something                      
                        } else if (doc === null) {
                            //do something                      
                        } else {
                            resolve();
                        }
                    });
            }
        })
    }).then(function () {
        contactusSchema.save(function (error, data) {
            if (error) {
                //return error                
            }
            else {
                return res.json({ "Message": "Thank you" });
            }
        })        
    }).catch(function (err) {        
    })
}
Output

      {
        "_id" : ObjectId("59fd8daa88b3491b0055e024"),
        "userFullName" : "myname",
        "emailID" : "abcd@gmail.com",
        "enquiry" : [
                {
                        "subject" : "hi2",
                        "message" : "new message  2",
                        "_id" : ObjectId("59fd8daa88b3491b0055e025"),
                        "updated_at" : ISODate("2017-11-04T09:51:38.937Z")
                },
                {
                        "message" : "new message  2",
                        "subject" : "hi2",
                        "_id" : ObjectId("59fd8dae88b3491b0055e027"),
                        "updated_at" : ISODate("2017-11-04T09:51:42.928Z")
                }
        ],
        "__v" : 0
}
        { "_id" :  ObjectId("59fd8dae88b3491b0055e026"), "enquiry" : [ ], "__v" : 0 }
        //Above is the unwanted document gets added automatically

**Comment by vkarpov15** [comment]
Do this instead, not sure why you have that 2nd `save()` going.

```javascript
  var mongoose = require('mongoose');
 var Promise = require('promise');
 var contactusModel = mongoose.model('contactus');

 module.exports.submitContact = function (req, res) {

new Promise(function (resolve, reject) {

    contactusModel.findOne({ "emailID": req.body["emailID"]}, function (err, doc) {
        if (doc == null) { /* If it's the first enquiry from user*/
            var contactusSchema = new contactusModel();
            contactusSchema.emailID = req.body["emailID"],
                contactusSchema.userFullName = req.body["userFullName"],
                contactusSchema.enquiry =
                [{
                    subject: req.body["subject"],
                    message: req.body["message"]
                }]
                contactusSchema.save().then(() => resolve())

        } else {  /* Update if atlest one query is present for the same user*/
            contactusModel.findOneAndUpdate({ "emailID": req.body["emailID"]},
                {                        
                    "$push": {
                        "enquiry": {
                            "subject": req.body["subject"],
                            "message": req.body["message"],                                                               
                        }
                    }
                },
                { new: true,upsert:false}, function (err, doc) {
                    if (err) { 
                        //do something                      
                    } else if (doc === null) {
                        //do something                      
                    } else {
                        resolve();
                    }
                });
        }
    })
}).then(function () {
    if (error) {
            //return error                
        }
        else {
            return res.json({ "Message": "Thank you" });
        }     
}).catch(function (err) {        
})
```
