### ISSUE TITLE
Unexpected async behaviour - findOne is returning old data after save

### ISSUE THREAD

**Issue by mjgs** [Automattic/mongoose#5792]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Model.findOne is returning old data after save

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');

const mongoUrl = `mongodb://localhost:${process.env.DBPORT}/findone-test`;
mongoose.connect(mongoUrl, { user: '', pass: '' });
mongoose.set("debug",true);

const UserSchema = new mongoose.Schema({
  username: { type: String, unique: true },
  testParam: { type: String, default: 'testValue' },
}, { timestamps: true });
const User = mongoose.model('User', UserSchema);

const username = 'test';
const user = new User();
user.username = username;
user.save(function(err, savedUser) {
  if (err) { throw err };
  console.log(`STEP 1: user created: ${JSON.stringify(savedUser, 0, 2)}`);

  savedUser.testParam = undefined;
  savedUser.save(function(err, updatedUser, numAffected) {
    if (err) { throw err };
    console.log(`STEP 2: user update: ${JSON.stringify(numAffected, 0, 2)}`);
    console.log(`STEP 2: user updated: ${JSON.stringify(updatedUser, 0, 2)}`);

    User.findOne({
      username: username,
    }, function(err, foundUser) {
      if (err) { throw err }
      console.log(`STEP 3: user found: ${JSON.stringify(foundUser, 0, 2)}`);
      // foundUser still has unset property testParam, in the db it's been deleted already
      process.exit();
    });
  });
});
```

**What is the expected behavior?**

Expected behavior is that foundUser.testParam should not be defined inside the findOne callback. What happens is that findOne returns an object with testParam still defined, even though it's been unset in previous save, and in the database it has been deleted:

```
MongoDB shell version: 3.2.4
connecting to: test
> use findone-test
switched to db findone-test
> db.users.find()
{ "_id" : ObjectId("5a001714d4194f1a193b5a68"), "updatedAt" : ISODate("2017-11-06T08:02:28.910Z"), "createdAt" : ISODate("2017-11-06T08:02:28.833Z"), "username" : "test", "__v" : 0 }
```

In the application I am writing it is resulting in old data getting saved back to the database.

**Please mention your node.js, mongoose and MongoDB version.**
node v7.8.0
mongoose 4.13.0

**Comment by vkarpov15** [comment]
That's because `testParam` has a default, `user` will not have `testParam` set but when you call `findOne()` the default will get set.

**Comment by mjgs** [comment]
When I look in the database as I step through the code, the testParam default value appears in the database at creation time, right after the initial save (STEP 1). 

STEP 1: savedUser.testParam is 'testValue' (correct)
STEP 2: updatedUser.testParam is undefined (correct)
STEP 3: foundUser.testParam is 'testValue' --> not correct, it should be undefined

I don't understand how the schema default could affect the value returned by findOne, since according to the database the default has been applied at creation time, could you explain in more detail? Thanks

**Comment by mjgs** [comment]
I've investigated this further and it's not possible to delete properties that have been set using default. Imo it's a bug. Anyhow the work around I found was instead of using defaults for properties that might need to be deleted, set their values in a save pre function, checking if the model is new first using user.isNew.
