### ISSUE TITLE
Mongoose Version 4.11.1 with MongoDB atlas giving connection timeout error

### ISSUE THREAD

**Issue by muhammad786** [Automattic/mongoose#5793]
Hey All, we are using "mongoose": "4.11.1", Node v6.9.5, MongoDB 3.4.10. We are using PM2 for clustering mode & digital ocean as cloud hosting. We are getting the "connection timeout" issue randomly. 

Our mongoose code
https://prnt.sc/h6v7a4

connection string for replica set 
const DEV_DB_URL = 'mongodb://username:password@' + 
'foodatedev-shard-00-00-4crvp.mongodb.net:27017,'+
'foodatedev-shard-00-01-4crvp.mongodb.net:27017,'+
'foodatedev-shard-00-02-4crvp.mongodb.net:27017/Dev_db?'+
'ssl=true&replicaSet=FoodAteDEV-shard-0&authSource=admin';

More details of ERROR
https://prnt.sc/h6v7le

Please help for this issue, we are struggling to settle this issue. Thanks!

**Comment by vkarpov15** [comment]
Have you tried increasing your `socketTimeoutMS`? Also, have you contacted Atlas support?

**Comment by muhammad786** [comment]
Thanks for replying sir. We have added the socketTimeoutMS now. And we communicated with ATLAS support and they checked the complete LOGS and no issue on their side. 

I need to confirm 1 thing from you ...
1: Our POOL-SIZE in Mongoose is 20 ... so lets say if our app will get 300 concurrent/parallel requests then will Mongoose allow app to create connections greater than 20?
2: Also please confirm that this error **https://prnt.sc/h6v7le** is from NODE MONGODB driver?

Thanks for help!
