### ISSUE TITLE
`depopulate()` does not accept multiple paths

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#5797]
I noticed a discrepancy between populate and depopulate, where depolulate doesn't accept a space separated string of multiple paths.

If I have time I'll try to create a PR for this, because it would be nice to depopulate 5 fields at once in one call, rather than 5 separate calls.

**Comment by vkarpov15** [comment]
Thanks for your PR :+1: :rocket:

**Comment by adamreisnz** [comment]
No worries 🎉
