### ISSUE TITLE
Feature Request: support "populate as" for compatibility with GraphQL

### ISSUE THREAD

**Issue by sarora2073** [Automattic/mongoose#5801]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**

Populate feature can only populate the field containing the ObjectID itself, effectively masking the original ObjectID field

e.g. For an Order Model that contains a userId field like so:

  userId: { type: Schema.Types.ObjectId, ref: 'User' }

If I do something like Order.find({}).populate('user') then the userId field will substitute the entire User Object for the userId. This creates a problem for Graphql and other solutions that put another data access layer in front of mongoose, since userId is no longer an ObjectId on read operations, although it is in fact an ObjectId. **Since GraphQL relies on strict type definitions, the mongoose populate feature is effectively unusable with GraphQL, at least not without some cumbersome workarounds.** 

**If the current behavior is a bug, please provide the steps to reproduce.**

n/a
**What is the expected behavior?**

I would contend that morphing the object type for the field 'userId' in this example is bad design necessitated by current limitations in mongoose, and that the best way forward would be to allow a "populate AS" feature that allows an alternate materialized field to be populated. e.g. a schema definition as follows could indicate that a second 'user' field should contain the populated field based off userId.

  userId: { type: Schema.Types.ObjectId, ref: 'User', populateAs: 'user' }

**Please mention your node.js, mongoose and MongoDB version.**
latest as of Nov 2017

**Comment by varunjayaraman** [comment]
can you post a code sample / pseudo code to illustrate exactly how this would look? I'm a little unclear on the feature being requested

**Comment by sarora2073** [comment]
Thanks for looking into this. I'm guessing posting GraphQL code won't help much for anyone not working with it, so I'll spare that level of detail. 

I'm going to extend on the example above where I have a User that i'm trying to save. 

There is a GraphQL layer that processes the CRUD operations from a web app prior to invoking mongoose commands. In GraphQL there is a description of the Order object which is similar to the mongoose schema description of the Order object.  
So for example in both Order schemas (mongoose and GraphQL), there is a userId field. In GraphQL I  also add a field in the Order object for the user (to detail user.firstname, user.lastname etc.) whenever i query an Order. That user field (not the userId field) in GraphQL is what I want to populate using mongoose, using this 'populate as' feature. Hopefully what I'm trying to accomplish and why makes sense?

In terms of the code on the mongoose side, as I said, instead of Schema definition in mongoose like this:

`userId: { type: Schema.Types.ObjectId, ref: 'User' }`

I'd instead like to be able to write something like this:

userId: { type: Schema.Types.ObjectId, ref: 'User', populateAs: 'user' }

If you prefer to rename populateAs to something like 'alias' or 'materializedField' maybe that will be more intuitive to some? Anyhow, the point is that my userId field shouldn't get masked when I tell mongoose that it's a reference to a User, and I should get a *new* field with the user details. 

If it's still not quite clear please let me know. Thanks again.

**Comment by varunjayaraman** [comment]
yeah i understand now, since GraphQL schemas arent dynamic (I'm guessing), you need to specify this field as a different name to represent an object containing the user schema's properties, rather than as a mongo id object / string.

I'm wondering, can you just implement this as a schema `method` or a `virtual` that returns a `Promise`?

**Comment by vkarpov15** [comment]
Have you looked at [populate virtuals](http://mongoosejs.com/docs/populate.html#populate-virtuals)?

**Comment by sarora2073** [comment]
Thanks for looking further. 

re: "GraphQL schemas arent dynamic (I'm guessing)"...
I would suggest thinking of GraphQL schemas as overlaying the data that mongoose can return. It provides advantages to pulling from multiple DBs, shaping queries, and more. Because it overlays, in the code we define a *static mapping* between it and the underlying schema e.g. a string field in GraphQL layer needs to be a string field in mongoose etc. It's not that GraphQL can't be flexible on read vs. write operations per se, but it would overly-complicate the implementation. 

Moreover, on the GraphQL side there is a notion of an [Object Type](http://graphql.org/learn/schema/#object-types-and-fields).  Just as a string should remain a string, at a higher-level in the static mapping we define, a data object (e.g. a User) would ideally map to a User schema in mongoose for the implementation to be smooth.

This request isn't a search for workarounds as much as an attempt to get mongoose schemas and GraphQL Object definitions to "play well" together, since they are both foundational for many open-source stacks. 

In terms of virtual populate I remember trying it out following this [article](http://thecodebarbarian.com/mongoose-virtual-populate) and as far as I can tell it suffers from the same issue...a field that contains an ObjectId gets returned as an Object instead, which creates the static mapping headaches. 

For now I'm populating individual fields by avoiding populate on the mongoose side, and defining custom fields and "resolvers" in GraphQL to do lookups across documents...that works for occasional lookups. 

If I need to write more advanced queries (including nesting), query-building with various conditions etc. then I think I would need to be able to leverage populate functionality. Please let me know if you agree it makes sense to improve the populate functionality for the longer-term. Thanks.

**Comment by sarora2073** [comment]
Update: Virtual Populate works! :-) Sorry I got caught up in the conventional populate approach. The virtual field plays well with GraphQL approach. Thank you!!!
