### ISSUE TITLE
Deciding sub-document type based on Enum Value

### ISSUE THREAD

**Issue by narulakeshav** [Automattic/mongoose#5802]
**Do you want to request a *feature* or report a *bug*?**
This is regarding the implementation of the enum in a mongoose schema.

**What is the current behavior?**
I have two types of users: `Student` and `Professor`; each with their own respective schemas. They can create a **discussion**. But in the discussion, the `_author` field could either be type `Student` or type `Professor`. 

How do I determine and set the value as to what kind of author it is during the creation of the document? And also, I want to store this `_author` object as a **sub-document** so how would I go about populating the data?

`_authorField in Schema`:

```js
_author: {
  type: Schema.Types.ObjectId,
  enum: [ 'Student', 'Professor' ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I don't know the correct implementation of it, so I couldn't get it to work.

**What is the expected behavior?**
Expected Behavior should be the following:
While the document is being created, the frontend should tell whether the author is a `Student` or `Professor` type and based on that, the document should store the `_id` in the `_author` field.

Then during retrieval, I should be able to just do, `findOne({...}).populate('_author').exec()` to get the data associated with that ID.

**Please mention your node.js, mongoose and MongoDB version.**
Node: `v8.2.1`
Mongoose: `v4.12.13`
MongoDB: `v3.4.6`

**Comment by varunjayaraman** [comment]
can you do this in a pre save hook? http://mongoosejs.com/docs/middleware.html

**Comment by vkarpov15** [comment]
[Dynamic references for populate](http://mongoosejs.com/docs/populate.html#dynamic-ref) sound like what you're looking for
