### ISSUE TITLE
Query really really slow!

### ISSUE THREAD

**Issue by lcortess** [Automattic/mongoose#5805]
Hi! 

I am having an issue with really slow queries
My query is really simple:

```
//Where start is a number field that contains unixtime and name is a simple string
const query = { 
    start: {
         '$gt': 1510117200, 
         '$lt': 1510289999 
     },
     name: 'a name'
};
```

The final query using mongoose looks like this:

```
console.time('query');
MyModel.find(query).then((data) => {
    console.timeEnd('query')
});
```
This query is returning ~200 rows and it's taking about 4 seconds! If I do the query directly in the mongodb console it takes 10ms.

Then if I add the `.lean()` option the difference is about 1 second

```
console.time('query');
MyModel.find(query).lean().then((data) => {
    console.timeEnd('query')
});
```

Then I've tried to use a specific index for my query like this:

```
console.time('query');
//MyModel.find(query).lean().hint({name: 1, start: -1}).then((data) => {
MyModel.find(query).lean().hint('indexName').then((data) => {
    console.timeEnd('query')
});
```
And the time difference is still about 1 second

The real issue is when I extend the range in the `start` field, if I set a difference that returns 10k rows using `.lean()` and spicifying an index using `hint()` my server crash =(

The query doesn't even finish when the server crash after about 2 minutes with this result:

```
<--- Last few GCs --->

 1965612 ms: Mark-sweep 1381.2 (1434.6) -> 1381.2 (1434.6) MB, 1033.8 / 0.0 ms [allocation failure] [GC in old space requested].
 1966701 ms: Mark-sweep 1381.2 (1434.6) -> 1381.2 (1434.6) MB, 1088.0 / 0.0 ms [allocation failure] [GC in old space requested].
 1967798 ms: Mark-sweep 1381.2 (1434.6) -> 1382.7 (1418.6) MB, 1096.8 / 0.0 ms [last resort gc].
 1968862 ms: Mark-sweep 1382.7 (1418.6) -> 1384.8 (1418.6) MB, 1063.5 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x178e45dcf781 <JS Object>
    1: deserializeObject(aka deserializeObject) [/var/www/node-server/node_modules/bson/lib/bson/parser/deserializer.js:~39] [pc=0x234e8b8f8de7] (this=0x178e45d04381 <undefined>,buffer=0x2bd6a700de41 <an Uint8Array with map 0x2f99c91070c1>,index=4880,options=0x9626ddaa019 <an Object with map 0x15df21dbf51>,isArray=0x178e45d04271 <false>)
    2: deserializeObject(aka deserializeObject) [/var/www...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x109f13c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x234e8a8079a7
Aborted (core dumped)
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

The same query in the mongo console takes ~20ms and if I see the explain it's using an index.

Any idea of what I am doing wrong?

Mongoose version: 4.13.1
MongoDb version: 3.0.11
Node Version: 6.11.5

**Comment by wlingke** [comment]
Without seeing the rest of your codebase, it's hard for me to tell what's going on here. Do you have a minimal repro script & db dump file for us to try?

Based on what you posted, there shouldn't be that big of a difference. I've used queries just like that in production and they work fine. If I were to guess, it would be that something else in your codebase is causing the issue.

**Comment by varunjayaraman** [comment]
yeah i guess couple of questions:

1) are you indexing this field through mongoose? Would these queries run before the indices are finished?

2) Do your memory problems happen locally if you run the query in isolation or only in production?
