### ISSUE TITLE
`strict: false` flag not respected for search parameters in update operation

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#5809]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I changed a schema property from type `String` to type `ObjectId`.
After having done that, I wanted to create a migration script to update to the new ID's, e.g.:

```js
const strValue = 'foo';
const idValue = new ObjectId();

Foo.update({bar: strValue}, {
  $set: {bar: idValue}},
}, {multi: true, strict: false});
```
This results in a (somewhat vague) TypeError:

```
TypeError: Cannot use 'in' operator to search for '_id' in foo
```

**What is the expected behavior?**
With strict mode disabled, Mongoose should not care what value I'm trying to match against the `bar` field, and whether it's an `ObjectId` or a `String`. It should just perform the query and respect the strict flag.

The TypeError (for when using strict mode) could be made a bit clearer as well, something along the lines of `Could not use 'foo' as search value for '_id' as it's not an ObjectId`.

In the mean time, a workaround is to use the underlying collection directly:

```js
Foo.collection.update({bar: strValue}, {
  $set: {bar: idValue}},
}, {multi: true});
```

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.6.0, Mongoose 4.13.0, MongoDb 3.4.7

**Comment by heisian** [comment]
I think the thing to do here is just query MongoDB directly with your update. In my experience, changing field types is not handled well and typically I end up just dropping the database (clearly not a good option in production..).

**Comment by adamreisnz** [comment]
@heisian no indeed, it's not an option for our production database ;)

In my experience it generally actually works quite well, and I've done quite a few migrations where we renamed fields, which works as expected, but in this case we're also wanting to change the data type, and that's causing the hiccup.

**Comment by vkarpov15** [comment]
Unfortunately this is a case where you need to do `Foo.collection.update()`, or temporarily remove `bar` from your schema. Changing the type of a field is messy in mongoose because mongoose will always cast query values. `strict` only changes how mongoose handles fields that are not defined in the schema (`false` = allow, `true` = silently strip out, `'throw'` = throw an error), not whether it casts fields that are defined in the schema.

**Comment by adamreisnz** [comment]
Bummer! It appears I've reached the limits of what's possible with Mongoose :)

**Comment by vkarpov15** [comment]
Hahah call it a feature. Mongoose tries hard to prevent you from writing values that don't match your schema to the db :)
