### ISSUE TITLE
How can I chain $pull and $addToSet?

### ISSUE THREAD

**Issue by earthyearth** [Automattic/mongoose#5810]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It only $addToSet

**If the current behavior is a bug, please provide the steps to reproduce.**

I am running this query:     
`Word.updateMany({ word, "pronunciations.likes": userId}, { $pull: { "pronunciations.$.likes" : userId }})
    Word.findOneAndUpdate({ word, 'pronunciations.pronunciation': pro }, { $addToSet: { 'pronunciations.$.likes': userId }})`
**What is the expected behavior?**
I would expect to remove every `userId` in every `likes` array, then add `userId` to a different one. 

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by varunjayaraman** [comment]
sorry I don't understand the issue. Can you please post a more complete code sample to illustrate your issue?

**Comment by varunjayaraman** [comment]
are you waiting for the first promise to resolve before invoking the second promise?
