### ISSUE TITLE
Most efficient way to map a large collection of objects before inserting them with a bulk insert?

### ISSUE THREAD

**Issue by peb7268** [Automattic/mongoose#5811]
Im using mongoose 4.13.0 and node 6.9.1. 

My question is this:

I have a large dataset and the fields in the dataset have very ambiguous names.  In my mongoose schema I renamed those ambiguous names to stuff that makes sense. 

What is the best way to do a map over these objects in a large array and convert the properties to names to properties that match my schema? 

I am trying to avoid doing a map over the whole set before I hand it off to mongoose as I think that would use a good bit of memory, be slow and such. I thought this seemed like a thing mongoose would probably have some sort of ability to handle.

Thanks!

**Comment by varunjayaraman** [comment]
Not really, this isnt really a mongoose-level concern. You should prepare your data to meet the schema field names before handing the object off to mongoose.

You could chunk up the array and iterate through the chunks, remap the data, and await a promise to bulk write each chunk. This would be slower than asynchronously handling the entire dataset but it might help get around memory issues

**Comment by peb7268** [comment]
Thanks for the reply @varunjayaraman . I figured this was the case but wanted to confirm there wasn't any mongoose utilities for this before rolling my own solution.
