### ISSUE TITLE
Connection to replica set

### ISSUE THREAD

**Issue by mouhsine786** [Automattic/mongoose#5819]
Bug: Mongoose fail to connect to replica set
Following this tutorial, http://www.sohamkamani.com/blog/2016/06/30/docker-mongo-replica-set/, I have created a replica set of 3 members (1 primary and 2 secondary).  The replica set is working perfectly, i have tested it on mongo management studio (i.e if i stop the primary,  a secondary member becomes the primary and so on).

i tried connecting to the replica set from mongoose, i get this error
![image](https://user-images.githubusercontent.com/6974634/32831461-d83e2112-ca11-11e7-9b96-9ffa05edcdf4.png)

Here is the code:
```
const options = {
    autoReconnect: true,
    replicaSet: 'my-mongo-set'
    //useMongoClient: true
};

var db = mongoose.connect('mongodb://localhost:30001,localhost:30002,localhost:30003/arkcash', options, function(err) {
    console.log('err', err);
});
```

Node version: v6.12.0
Mongo version: v3.4.10
Mongoose version: 4.13.2

If i run the same code with mongoose v4.5.9, i can connect to the replica set.  But the problem with this version is that mongoose encounters some problem to reconnect to the primary member of the replica set after i switch off the new primary member a few times.

If i run the same code with mongoose v4.7.4, i get the following error on launching the application
![image](https://user-images.githubusercontent.com/6974634/32831968-703e95d6-ca13-11e7-9b61-90b72d34563e.png)

**Comment by vkarpov15** [comment]
Yeah unfortunately this tutorial isn't very high quality, doesn't really teach you how to connect to the replica set. Things get very confusing with mongodb if you're connecting to a replica set using 'localhost' but the replica set thinks that its members are named 'mongo1', 'mongo2', and 'mongo3'. Mongoose then thinks that there's more members of the replica set that it can't connect to.

I'd just add the following lines to `/etc/hosts` in your `Dockerfile`:

```
127.0.0.1 mongo1
127.0.0.1 mongo2
127.0.0.1 mongo3
```

**Comment by mouhsine786** [comment]
**No primary found in replicaset**

Ok i have included the above codes in my /etc/hosts. Now it seems mongoose is able to connect to the replicaset. But now i am having a new probleme.
Although i have a primary member in my replica set i an getting this error:
![image](https://user-images.githubusercontent.com/6974634/32876931-7577ae20-cab8-11e7-93b2-306d43aafeea.png)

Here is my connection to the replica set
`const options = {
    autoReconnect: true,
    replicaSet: 'my-mongo-set',
    useMongoClient: true
};

var db = mongoose.connect( /*process.env.MONGO_PATH*/ 'mongodb://localhost:30001,localhost:30002,localhost:30003/arkcash', options, function(err) {
    if (!err)
        insertDefaultUser();
});`

I have found that in the mongoose version 4.5.10, it works.  But onwards i get the above error.

Node version: v6.12.0
Mongo version: v3.4.10
Mongoose version: 4.13.2

**Comment by vkarpov15** [comment]
Switch to:

```
var db = mongoose.connect('mongodb://mongo1:27017,mongo2:27017,mongo3:27017/arkcash', options, function(err) {
    console.log('err', err);
});
```

In general, be very careful to make sure that the hostname you're using in `mongoose.connect()` lines up with your replica set config and the hostname is something your app can resolve.
