### ISSUE TITLE
Creating a new document with invalid data returns a new document that cannot be saved because a validation error is attached to errors

### ISSUE THREAD

**Issue by lopugit** [Automattic/mongoose#5826]
**Do you want to request a *feature* or report a *bug*?**
It might be a feature request..

**What is the current behavior?**
When creating a new document like so
`let newDoc = new docModel(data)`

where data is 
`{name: 'foo', others: [{name: 'bar'}] }`

and schema is
`let schema = new Schema({name: {type: String}, others: {type: [{type: Schema.ObjectId}] } })`

When you try to save the newDoc, it throws an error, cast to array failed for value "[{name: 'bar'}]" at path "others"

`newDoc.save()
    .then((savedDoc, err)=>{
        if(!err){
            //yay
        } else {
            //damn
        }
    .catch(err=>{
        console.error(err)
     }`

you will catch an error that looks something like this

`{ stateId: 'f7a6cb05-0006-4f33-8c76-f733339ad7fe',
4|agoraser |   text: 'agagagagagag',
4|agoraser |   _id: 5a0ec213b93d4b5a521a061d,
4|agoraser |   stateCreated: 2017-11-17T11:02:46.214Z,
4|agoraser |   lifetime: 0,
4|agoraser |   age: 0,
4|agoraser |   inception: 2017-11-17T11:02:46.214Z,
4|agoraser |   created: 2017-11-17T11:02:46.214Z,
4|agoraser |   contract: [],
4|agoraser |   payees: [],
4|agoraser |   owners: [ 59e33eafe6e689b86bc65726 ],
4|agoraser |   properties: [],
4|agoraser |   states: [],
4|agoraser |   parents: [ 5a0d6d0fa3f92f1ffc9504ad ],
4|agoraser |   things: [],
4|agoraser |   list: [],
4|agoraser |   realms: [ 'all' ],
4|agoraser |   names: [ 'new', 'unsaved', 'editing' ] }
4|agoraser | err
4|agoraser | { ValidationError: thing validation failed: properties: Cast to Array failed for value "[ { title: 'options',
4|agoraser |     list: [ 'editing', 'edited' ],
4|agoraser |     things: [],
4|agoraser |     properties: [] } ]" at path "properties"
4|agoraser |     at ValidationError.inspect (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/error/validation.js:57:23)
4|agoraser |     at formatValue (util.js:430:38)
4|agoraser |     at inspect (util.js:324:10)
4|agoraser |     at format (util.js:191:12)
4|agoraser |     at Console.warn (console.js:139:21)
4|agoraser |     at thingModelled.save.then.catch.err (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:1246:23)
4|agoraser |     at tryCatcher (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/util.js:16:23)
4|agoraser |     at Promise._settlePromiseFromHandler (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/promise.js:512:31)
4|agoraser |     at Promise._settlePromise (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/promise.js:569:18)
4|agoraser |     at Promise._settlePromise0 (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/promise.js:614:10)
4|agoraser |     at Promise._settlePromises (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/promise.js:689:18)
4|agoraser |     at Async._drainQueue (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/async.js:133:16)
4|agoraser |     at Async._drainQueues (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/async.js:143:10)
4|agoraser |     at Immediate.Async.drainQueues (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/bluebird/js/release/async.js:17:14)
4|agoraser |     at runCallback (timers.js:789:20)
4|agoraser |     at tryOnImmediate (timers.js:751:5)
4|agoraser |   errors: 
4|agoraser |    { properties: 
4|agoraser |       { CastError: Cast to Array failed for value "[ { title: 'options',
4|agoraser |     list: [ 'editing', 'edited' ],
4|agoraser |     things: [],
4|agoraser |     properties: [] } ]" at path "properties"
4|agoraser |     at new CastError (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/error/cast.js:27:11)
4|agoraser |     at model.Document.$set (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/document.js:761:7)
4|agoraser |     at model._handleIndex (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/document.js:590:14)
4|agoraser |     at model.Document.$set (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/document.js:550:24)
4|agoraser |     at model.Document (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/document.js:77:12)
4|agoraser |     at model.Model (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/model.js:55:12)
4|agoraser |     at new model (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node_modules/mongoose/lib/model.js:3879:13)
4|agoraser |     at Promise (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:1232:31)
4|agoraser |     at new Promise (<anonymous>)
4|agoraser |     at makeBackupState (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:1222:12)
4|agoraser |     at Promise (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:777:15)
4|agoraser |     at new Promise (<anonymous>)
4|agoraser |     at saveThing (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:741:12)
4|agoraser |     at Socket.socket.on (/media/rick/hyper/Dropbox/host-root/var/www/nodes/agora/server/node/app.js:297:5)
4|agoraser |     at emitOne (events.js:116:13)
4|agoraser |     at Socket.emit (events.js:211:7)
4|agoraser |         message: 'Cast to Array failed for value "[ { title: \'options\',\n    list: [ \'editing\', \'edited\' ],\n    things: [],\n    properties: [] } ]" at path "properties"',
4|agoraser |         name: 'CastError',
4|agoraser |         stringValue: '"[ { title: \'options\',\n    list: [ \'editing\', \'edited\' ],\n    things: [],\n    properties: [] } ]"',
4|agoraser |         kind: 'Array',
4|agoraser |         value: [Array],
4|agoraser |         path: 'properties',
4|agoraser |         reason: [Object] } },
4|agoraser |   _message: 'thing validation failed',
4|agoraser |   name: 'ValidationError' }`

This is from my real data log, I tried to simplify the reproduction data a bit.

But the principle is the same, if there is an error in validation when creating a document by giving the model constructor invalid data, then you get a document return, with the invalid data taken out, and an error attached somewhere to the document json, (I'm not sure where that is?)

which means that when you try to save the actually valid document, the error from invalid data being passed to the model constructor carries through and the document isn't able to be saved.

Is this the expected behaviour? How do I then apply my own pre hook validation so I can filter arrays of objects which are meant to arrays of ObjectId's but either haven't been saved yet or were given in a document which had that array populated. 

**If the current behavior is a bug, please provide the steps to reproduce.**
let mongoose = require('mongoose')
let Schema = mongoose.Schema
let schema = new Schema({name: {type: String}, others: {type: [{type: Schema.ObjectId}] } })
let newDoc = new docModel({name: 'foo', others: [{name: 'bar'}] })

**What is the expected behavior?**
I expected it to just return a valid document, then have that version of the document be saveable as it's technically valid, not have the error stick to it and make it unsaveable.

**Please mention your node.js, mongoose and MongoDB version.**
nodejs v8.9.1
mongoDB v3.6.0-rc3
mongoose v^4.11.12

**Comment by vkarpov15** [comment]
I'm not sure I understand your issue, can you please clarify?

**Comment by lopugit** [comment]
So basically I figured it out

`let thingModelled = new thingModel(JSON.parse(JSON.stringify(thing)))
              thingModelled.stateId = commonStateHash
              //remove errors
              delete thingModelled.errors
              delete thingModelled.$__.validationError
              thingModelled.save()
                .then((thingServer)=>{
                  resolve({thing, thingServer})
                })
                .catch(err=>{
                  console.error(err)
                  reject(err)
                })`

What happens is that validation errors are added to the document when you create it via new Model(data).

Even though the data is deleted

Meaning that if I have a schema like:

`
{
    list: { type: [String] }
}
`

And I go
`
let newDoc = new Model({ list: [{foo: 'bar'}]})
// Will return newDoc = { list: [] }
`
but will not be saveable. 

It just seems weird that the new Model() constructor creates a valid document, but attaches those validations errors which mean it can't be saved if you try. You can just remove those validation errors and you kind of get a parsed, valid to save document.

See what I mean?

And, because of this validation and data transformation done by the new Model() constructor, there's no where to add hooks to handle the validation done by the constructor your self? 'pre' for example when saving but validation happens on document construction so...?

**Comment by vkarpov15** [comment]
Yeah if you delete the internal errors then `save()` will succeed. Generally you don't want to do that.

Re: "there's no where to add hooks to handle the validation done by the constructor your self", you can just call `$markValid()` on the path you want to make valid in a `pre('validate')` hook.
