### ISSUE TITLE
How to set a timeout for idle open connections

### ISSUE THREAD

**Issue by diaswrd** [Automattic/mongoose#5827]
Hello folks, I'm using mongoose v4.13.0 and I have some code running in AWS Lambda that connects with a database instance running on Atlas.

Basically, after running my function, mongoose will keep the connection with the database open for up to 30 minutes, allocating resources unnecessarily since my function container is long gone by that time. So I'm trying to find a way to setup a timer where the connection closes if it's idle for longer than 5 minutes, instead of 30 which seems to be the default behaviour.

I've checked the documentation from both mongoose and Node.js MongoClient API, tried several different combinations of values for `keepAlive`, `autoReconnect`, `connectTimeoutMS` and `socketTimeoutMS` with no luck so far.

Does anyone have any suggestions on how to configure the connection to drop **if** idle after a specific amount of time?

My stack is:
```
Node.js v6.9.1 (AWS Lambda)
Mongoose v4.13.0 (AWS Lambda)
MongoDB v3.4.10 (Atlas)
```

Thanks!

EDIT: My connection code sample
```
mongoose.connect(dbUri, {
      useMongoClient: true,
      autoReconnect: false,
      keepAlive: false,
      connectTimeoutMS: 300000,
      socketTimeoutMS: 300000
}, (err) => {});
```

**Comment by diaswrd** [comment]
After digging into mongodb native driver's code, I found [this line](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/url_parser.js#L236), which throws an error if you try to set `maxIdleTimeMS` via the connection URI. Looks like mongo was failing silently, not broadcasting the proper error message from the driver to the application.

Anyway, I'll close this ticket since it was a design decision by the driver and not mongoose.

**Comment by GeniusBrother** [comment]
@diaswrd How do you solve this problem later?

**Comment by ScreamZ** [comment]
@diaswrd Do you have some way to play with that in 2020? Does function end send a SIGTERM or something like this ?
