### ISSUE TITLE
How to count the number of embeded ref

### ISSUE THREAD

**Issue by adeelsalim** [Automattic/mongoose#5837]
I am using node.js express and mongoose

i have following schema

```javascript
var playerSchema = mongoose.Schema({
    id: Number,
    name: String,
    scores: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Score"
        }
    ]

});

var scoreSchema = mongoose.Schema({

        id: Number,
        score: Number,


});
```

now every player has array of scores. in the route app i need to count the number of scores

To count the number of players is easy i can count like this

```javascript
app.get("/:id", function(req, res){
   Player.count({},function(err, count) {
       console.log(count);
       });
});
```

but to count the number of scores here is the problem how can i count them i am trying to do this but it throws an error

```javascript
Player.findByID(req.params.id, function(err, data){
   data.scores.length // doesnt work
   data.scores.forEach // doesnt work
})
```

any ideas how to count the number of scores for any given player

**Comment by vkarpov15** [comment]
What error does it throw?

**Comment by varunjayaraman** [comment]
Can you please provide more details @adeelsalim ? What is the error being thrown? are you handling the error in your callback first?
