### ISSUE TITLE
error using Schema in browser:  __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by raythree** [Automattic/mongoose#5842]
We have a react-slingshot project that uses Mongoose.schema in the browser for form validation. We have this in our webpack config as per the docs:
```
new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
```
Everything worked fine when we started the project using mongoose ```4.11.5```. After upgrading to mongoose ```4.13.4``` the project no longer runs in dev mode (npm start) generating this error:
```
embedded.js?9a85:7 Uncaught TypeError: __webpack_require__(...) is not a function
```
From inside one of the mongoose files. It occurs on the first line shown below when requiring the Document:
```
var Document = require('../document_provider')();
var EventEmitter = require('events').EventEmitter;
var PromiseProvider = require('../promise_provider');

/**
 * EmbeddedDocument constructor.
 *
 * @param {Object} obj js object returned from the db
 * @param {MongooseDocumentArray} parentArr the parent array of this document
 * @param {Boolean} skipId
 * @inherits Document
 * @api private
 */

function EmbeddedDocument(obj, parentArr, skipId, fields, index) {
 ...
```
Initially we didn't lock down the version of mongoose inside package.json and this started happening after version 4.11.5. I tried with the latest and it still persists. Locking the mongoose version at 4.11.5 works fine. Any ideas what changes would have caused this?

Thanks!

**Comment by vkarpov15** [comment]
I don't know unfortunately, we don't really have good support for webpack ATM. @varunjayaraman is the resident expert on the interplay with mongoose and webpack.

**Comment by raythree** [comment]
Yeah that makes sense, as mongoose is primarily backend. Hopefully it's easy to workout because your decision to support schema validation in the browser is great for DRY in isomorphic js apps, and most using React on the front-end use Webpack.

**Comment by varunjayaraman** [comment]
hey @raythree sorry ive been on vacation, anyway this is a problem that unfortunately creeps up from time to time with mongoose. I've been able to reproduce your issue with a simple repro script

# webpack.config.js
```javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/client.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  plugins: [
    new webpack.DefinePlugin({ 'typeof window': '\"object\"' })
  ]
}
```

#src/client.js

```javascript
import mongoose from 'mongoose';
```

# index.html
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
  </head>

  <body>
    <div>hi</div>
    <script src="dist/bundle.js"></script>
  </body>
</html>
```

#package.json
```json
{
  "name": "gh-5842",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^4.13.6",
    "webpack": "^3.10.0"
  }
}
```
