### ISSUE TITLE
Post save hook not firing

### ISSUE THREAD

**Issue by christofferskog** [Automattic/mongoose#5843]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The post save hook is never called despite the document being saved.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've included the code that executes in my scenario here:

https://stackoverflow.com/questions/47437948/mongodb-mongoose-post-save-hook-not-running

I'll include the same code here too if necessary but I don't want to bloat the issue if I don't have to.

**What is the expected behavior?**
I expect the post save hook to fire properly since the document is saved. I am calling .save on the schema/model which should trigger the hook as the documentation for the hooks state.

**Please mention your node.js, mongoose and MongoDB version.**
node - v8.7.0
mongoose - v4.13.1
mongodb - v2.2.33

**Comment by PeideAmonNg** [comment]
Has it been fixed?

**Comment by vkarpov15** [comment]
@PeideAmonNg please open up a separate issue and follow the issue template.
