### ISSUE TITLE
$in is not working

### ISSUE THREAD

**Issue by WwwappZ** [Automattic/mongoose#5847]
When I use the mongodb query in the terminal:
db.getCollection('fotoboeks').find({"tags":{"$in":["5a15e594308d87d63f5d951f"]}});

I get 3 records what will contain in tags array: 5a15e594308d87d63f5d951f

When I use this query in mongoose

```
  Fotoboek.find({"tags":{"$in":["5a15e594308d87d63f5d951f"]}}, function(err, results) {
    if (err) {
      console.log(err);
      return next(err);
    }
    res.json({results});
  });
};
```
I get only 1 record. The record contains in the tag only: 5a15e594308d87d63f5d951f. While the other records contains more than one item in the taks array. 

This is my schema

```
const FotoboekSchema = new Schema({
  naam: String,
  image: String,
  thumbnail: Array,
  beschrijving: String,
  eigenaar: String,
  tags: Array,
  themes: Array,
  actief: Boolean,
  downloads: Number,
  datum: Date
});
```
I use the latest mongoose version

**Comment by vkarpov15** [comment]
Can you show me the output of the `db.getCollection('fotoboeks').find({"tags":{"$in":["5a15e594308d87d63f5d951f"]}});` query from the mongo shell? That will really help in reproducing this issue.

**Comment by abhishekpankar** [comment]
I'm also facing the same issue

**Comment by abhishekpankar** [comment]
This is my schema:

```
let schema = new Schema({
        title: {type: String},
        members: {type: [Id], required: true},
        isGroup: {type: Boolean, required: true, default: false},  // ignore this
        messages: {type: [messagesSchema], required: true, default: []} // ignore this
}
```

Query:

```
let result = await db.aggregate([
        { $match: { isGroup: true, members: { $in: [userId] } } },  // this $in operator is not working as expected
        { $group: { _id: null, groupIds: { $push: "$_id" } } },
        { $project: { _id: 0 } }
]);
return result;
```

Same query works in terminal but returns 0 records when executed through mongoose.

**Comment by vkarpov15** [comment]
@abhishekpankar please open a new issue and follow the issue template.
