### ISSUE TITLE
Get connection state - aws lambda

### ISSUE THREAD

**Issue by tho068** [Automattic/mongoose#5849]
Hello

I am writing an aws lambda function, and I am trying to reuse the database connection. I am doing that by defining the connection outside of the lambda handler. I use db.readyState to check the health of the connection. However, the problem is that it takes quite a while before the readyState variable updates.

Is there a way to check the health of the connection right away?

**Comment by vkarpov15** [comment]
Honestly I've never tried using mongoose with lambda so I don't have any insights. Can you post the function you're trying to write and I'll investigate?

**Comment by tho068** [comment]
Yes, I will get back to you in the morning with  the function and some description about it.

The idea behind the function is taken from the official mongodb lambda guide, regarding database connection reuse.

So it is basically the same, except for mongoose.

Sendt fra min iPhone

5. des. 2017 kl. 01:28 skrev Valeri Karpov <notifications@github.com<mailto:notifications@github.com>>:


Honestly I've never tried using mongoose with lambda so I don't have any insights. Can you post the function you're trying to write and I'll investigate?

-

**Comment by vkarpov15** [comment]
Sorry about the long delay in getting to this, the 5.0.0 release took up pretty much all of my time for the last couple months.

Are you sure you're setting `context.callbackWaitsForEmptyEventLoop = false;` in your function? Otherwise, the below script works fine for me with Lambda + MongoDB atlas, modulo the omitted connection string.

```javascript
const co = require('co');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

let conn = null;

const uri = 'mongodb://OMITTED';

exports.handler = function(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false;

  run().then(res => { callback(null, res); console.log('done'); }).catch(error => callback(error));
};

function run() {
  return co(function*() {
    console.log(conn && conn.readyState);
    if (conn == null) {
      conn = yield mongoose.createConnection(uri, { useMongoClient: true });
      conn.model('Test', new mongoose.Schema({ name: String }));
    }
    console.log(conn.readyState);

    const M = conn.model('Test');

    const doc = yield M.findOne();
    console.log(doc);

    return doc;
  });
}
```

Below is the output I get from lambda with mongoose 4.13.11. Note the first '1' is the initial `readyState`, which means that mongoose is successfully connected.

![image](https://user-images.githubusercontent.com/1620265/35946478-c2268c90-0c18-11e8-881f-15df2e5abdb3.png)

**Comment by tho068** [comment]
Hello

Yes I am sure. For how long have you persisted the connection? Problems started about five minutes after the first call.

In other words, the problem started when the function went from warm to cold state, and back to warm state again.

When the con state is checked, the output is then true, even though the connection is dead.

Sendt fra min iPhone

8. feb. 2018 kl. 00:09 skrev Valeri Karpov <notifications@github.com<mailto:notifications@github.com>>:


Sorry about the long delay in getting to this, the 5.0.0 release took up pretty much all of my time for the last couple months.

Are you sure you're setting context.callbackWaitsForEmptyEventLoop = false; in your function? Otherwise, the below script works fine for me with Lambda + MongoDB atlas, modulo the omitted connection string.

const co = require('co');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

let conn = null;

const uri = 'mongodb://OMITTED';

exports.handler = function(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false;

  run().then(res => { callback(null, res); console.log('done'); }).catch(error => callback(error));
};

function run() {
  return co(function*() {
    console.log(conn && conn.readyState);
    if (conn == null) {
      conn = yield mongoose.createConnection(uri, { useMongoClient: true });
      conn.model('Test', new mongoose.Schema({ name: String }));
    }
    console.log(conn.readyState);

    const M = conn.model('Test');

    const doc = yield M.findOne();
    console.log(doc);

    return doc;
  });
}

Below is the output I get from lambda with mongoose 4.13.11. Note the first '1' is the initial readyState, which means that mongoose is successfully connected.

[image]<https://user-images.githubusercontent.com/1620265/35946478-c2268c90-0c18-11e8-881f-15df2e5abdb3.png>

-

**Comment by vkarpov15** [comment]
Nope works fine for me, ran the function twice, once after a couple weeks:

![image](https://user-images.githubusercontent.com/1620265/36461482-827ac886-1672-11e8-8e67-95dab5b23c48.png)

and then after about 6 minutes:

![image](https://user-images.githubusercontent.com/1620265/36461477-76b01722-1672-11e8-8c17-2b0af5fac3d9.png)

First time the initial connection was `null`, which is expected, 2nd time it still had `readyState = 1`.

Can you post your lambda function code with sensitive credentials commented out?

**Comment by tho068** [comment]
The problem is that when the connection is lost for whatever reason. The ready state does not update until after a few minutes.

My function is called at regular intervals, maybe every minute, and after about five minutes when the lambda function is not hot anymore. The ready state stays 1 for some time after the connection dropped.

I will post my code today if I get the time.
