### ISSUE TITLE
New jsonSchemas in MongoDb 3.6 and the strictness of reading of Mongoose schemas

### ISSUE THREAD

**Issue by MidnightP** [Automattic/mongoose#5851]
By design, Mongoose does not apply the schema in reading. 

Considering the announced possibility of "Schema validation with JSON Schema for new data governance controls" with the release of MongoDB 3.6, can I expect any changes / additions in relation to this topic?

Will we in the future be able to apply the Javascript Mongoose schema as a jsonSchema to the MongoDB collection itself?

Issues on strictness of reading:
#4279
#5743

**Comment by vkarpov15** [comment]
I'm going to close this as a duplicate of #4279, see my comments here: https://github.com/Automattic/mongoose/issues/4279#issuecomment-347035613
