### ISSUE TITLE
Searching on a field in a Ref inside a Ref (Refception)

### ISSUE THREAD

**Issue by guillaume-g** [Automattic/mongoose#5852]
Hi everyone, thanks for doing your great work ! You should know that we are using Moongose in production and it's a great tool :)

I didn't find anything to resolve my issue **(it's not a bug)**, even if I can't hardly explain it for Google...

Here is the context : 

- I have three model called Stock, Product and Category.

- A Stock has a Ref on a Product._id and a Product has a Ref on a Category._id

What I am trying to perform is a find with a query from a Stock like this 
**{ 'product.categories._id' }**

Categories is an Array of Category._id

Do you know if it's possible ?

Thanks in advance

**I am using Node 8.4 and Mongoose 4.11.9.**

**Comment by varunjayaraman** [comment]
if they need to be populated unfortunately you cant affect the top level query by conditions in a nested populate. You should find the things you need in the nested populate and use those to constrain the conditions for the original query you wanted to apply conditions for.

Does that make sense @guillaume-g ?
