### ISSUE TITLE
pre findOneAndUpdate issue

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [Automattic/mongoose#5854]
**Do you want to request a *feature* or report a *bug*?**
Encountered a bug with a pre findOneAndUpdate middleware.

**What is the current behavior?**
When I use from  `pre findOneAndUpdate` hook, my original function `findOneAndUpdate` is not working and not update the document. 
Bellow is my `findOneAndUpdate` function:
```
var updateUserEducation = function (req, res) {
    var educationInfo = {
        level: req.body.education.level,
        name: req.body.education.institute.name,
        country: req.body.education.institute.address.country,
        state: req.body.education.institute.address.state,
        city: req.body.education.institute.address.city,
        qualificationMajor: req.body.education.qualificationMajor,
        attendanceType: req.body.education.attendanceType,
        achievements: req.body.education.achievements,
        educationId: req.body.education.educationId,
        userId: req.params.userId
    };
    console.log(educationInfo, 'ggg');   // Here my data is complete, and fields has data.
    Profile.findOneAndUpdate({"$and":[{"userId": ObjectId(req.params.userId)},{"educations.educationId": 
           ObjectId(req.body.education.educationId)}]}, {$set:{"educations.$": educationInfo}}, function (err, user) {
        console.log(user, 'here???????')   // Here user is undefined when i use `pre hook`, but if i change to `post hook` it is ok.
       if (err) {
            sendJsonResponse(res, 404, err);
      } else {
           sendJsonResponse(res, 200, user);
      }
    })
};
```
and this is my hook:
```
userProfileSchema.pre('findOneAndUpdate', function (profile,  next) {
  next();
});
```

**What is the expected behavior?**
I want to check data and modify based on my conditions in pre `findOneAndUpdate`, suppose want to check if some fields are new (has value), and its previous value was empty or null, then i want to increment a value in his/her profile.
But with `pre hook` my original `findOneAndUpdate` is not working, if i change it to `post hook` its working.

**Please mention your node.js, mongoose and MongoDB version.**
node version is `8.9.1`, and MongoDb version is `3.2.17`

**Comment by varunjayaraman** [comment]
sorry is the issue that the result object is undefined in the callback? You have to pass `{new: true}` to `findOneAndUpdate` if you want the object returned from the db

**Comment by Mobasher-NetLinks** [comment]
@varunjayaraman But its strange for me, why result is undefined when i use from pre hook, but not in post hook?

**Comment by vkarpov15** [comment]
The first param to pre('findOneAndUpdate') is `next()`, you need to look at `this` in your query middleware to access data about the query.

```javascript
userProfileSchema.pre('findOneAndUpdate', function (next) {
  // `this` refers to the query
  console.log(this.getQuery());
});
```
