### ISSUE TITLE
Discriminators causing everything to be "unselected" when using "select"

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#5859]
I am attempting to use `.select` in a query with a discriminator model. The example below uses the projection to pull a `textScore` (meant for use with a `$text` query) but the bug is not specifically related to this use case.

When making a `find` call, the returned objects do NOT have `trackField` or `eventField` and they are selected out automatically without me specifying it.

See Repro Script:
```
const mongoose = require('./');
mongoose.set('debug', true);

const Schema = mongoose.Schema;

mongoose.connect('mongodb://127.0.0.1/test');
const db = mongoose.connection;

db.once('open', async () => {
  try {
    const eventSchema = new Schema({
      eventField: String
    }, { id: false });

    const Event = mongoose.model('Event', eventSchema);

    const trackSchema = new Schema({
      trackField: String,
    });

    const Track = Event.discriminator('Track', trackSchema);

    const trackedItem = new Track({
      trackField: 'trackField',
      eventField: 'eventField',
    });
    await trackedItem.save();

    const events = await Event.find({}).select({ score: { $meta: 'textScore' } }).exec();
    const tracks = await Track.find({}).select({ score: { $meta: 'textScore' } }).exec();
    console.log(events); // no trackField or eventField
    console.log(tracks); // no trackField or eventField

    db.close();
  } catch (e) {
    console.log(e);
  }
});

```

When you attach the debugger, it shows this query:
`events.find({}, { fields: { score: { '$meta': 'textScore' }, __t: 1 } })`

I imagine that the `__t: 1` is causing this.

If I run `await Event.find({}).exec()`, the mongoose debugger shows 
`events.find({}, { fields: {} })` which is why normally everything is selected.

The problem that this causes is that you can't run a $text query sorting by textScore on anything that has a discriminator without specifically projecting every single field in the schema.

Is there any way to override the `__t: 1`? I tried setting `{__t: null}` but that didn't work. Or is there a mongodb projection operator that I'm not aware that might solve this problem?

**Comment by vkarpov15** [comment]
Thanks for the detailed repro, will fix. The `__t: 1` getting added is a bug, mongoose should only add it if the user-provided projection is inclusive. `{ score: { $meta: 'textScore' } }` is not an inclusive projection, so I imagine we're checking for truthiness somewhere as opposed to looking for `$meta` and `$slice`.

**Comment by wlingke** [comment]
awesome thanks so much

**Comment by dimaip** [comment]
> The `__t: 1` getting added is a bug

Is it a different bug then? I have the same problem, I have a `BaseUser` model and `User` model discriminated on top of it.
When I do query like this `BaseUser.findById(req.user._id, '+email')` I'm only getting the `email` field in response. This happens because `__t` gets included in the query, and so it yields `exclude = false` in `applyPaths`.

**Comment by vkarpov15** [comment]
@dimaip  looks like this bug was fixed in 5.x then. Is there something that prevents you from upgrading?

**Comment by dimaip** [comment]
@vkarpov15 I already did, the upgrade process went smooth.
