### ISSUE TITLE
pre save middleware return - next() does not end middleware without a return statement

### ISSUE THREAD

**Issue by florianbepunkt** [Automattic/mongoose#5866]
**Do you want to request a *feature* or report a *bug*?**
Not completely sure if this is a bug or by design. If the latter please update the docs

**What is the current behavior?**
```
OrderSchema.pre('save', function(next) {
  if ('apples' == 'apples') {
    console.log('we should exit early');
    next();
  }

  console.log('this should not be called but is');
});

```
Both console.logs get called. Above is a simplified version of my middleware hook… basically I need to set a few conditions and perform actions based on whether they are met.

If I add a `return;` statement after `next()` only the first console.log gets called.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
next() would end the middleware. If this is by design, it would be nice to mention this in the docs.

**Please mention your node.js, mongoose and MongoDB version.**
mognoose 4.12.4 mongoDb 3.4.10

**Comment by varunjayaraman** [comment]
@florianbepunkt this is kind of how most middleware in the node world works. Its not a promise so if you dont return it will continue execution in that function. I'm not sure if we could short circuit the function, i'll let @vkarpov15 chime in though

**Comment by florianbepunkt** [comment]
@varunjayaraman My bad. I simply wasn't aware that you need to return the next()… but if it's common convention and by design, no need to change anything. Thank you.

**Comment by vkarpov15** [comment]
You don't have to `return`, you can also do an `else`. No way to do early function termination in JS without throwing an error. Either way, it doesn't seem like idiomatic JS because when you call a function you generally assume execution will continue, and `next()` is a regular old JS function. Will add a note in the docs
