### ISSUE TITLE
SSL website for docs

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#5867]
http://mongoosejs.com -> https://mongoosejs.com

we could also use JS.org to have SSL cert and then just setup wildcard DNS redirect to https://mongoose.js.org

**Comment by vkarpov15** [comment]
Definitely something to add. We use github pages right now, so no https unless we do a proxy.

**Comment by niftylettuce** [comment]
we could use https://github.com/js-org/dns.js.org

i use it for https://lad.js.org and https://lass.js.org, no issues ever

**Comment by vkarpov15** [comment]
Good call, will do. HTTPS is definitely important, just havent quite had the time to dedicate to the docs site yet

**Comment by vkarpov15** [comment]
Closed in #6856
