### ISSUE TITLE
Using increment query with a unique integer index, seems to cause problems

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#5872]
This is probably a bug with MongoDB not Mongoose, but I want your feedback please.

We have an index on a model that looks like so:

```js
categorySchema.index({sortOrder: 1}, {unique: true, background: false});
```

sometimes we insert a new document into the collection, which has a sortOrder which bisects the unique set. So we have to go in and update all the documents where the sortOrder equals the new documents value and increment by one. We actually do the update first, then do the insert. There are no race conditions because we acquire an external lock before we do the update/insert sequence.

But when we use this query:

```js
  Category.update(
      {
        sortOrder: {
          $gte: sortOrder
        }
      },
      {
        $inc: {
          sortOrder: 1
        }
      },
      {
        upsert: false
      }
    )
```

what seems to happen, is that as it increments, it trips the unique index restriction.

At least this is what appears to be happening.  Does it make sense?

**Comment by ORESoftware** [comment]
This bug makes sense, so I am not sure I would even call it a bug, just need to figure out a good workaround.

**Comment by vkarpov15** [comment]
Yeah, I don't think there's any guarantee on the order in which documents are updated. As a workaround you might consider updating docs one by one so you can ensure order.

**Comment by ORESoftware** [comment]
Yeah thanks, right now we have a finite number of documents, let's say 800. So we just increment each one by 801 and it should work.
