### ISSUE TITLE
Mongoose custom validation transaction function

### ISSUE THREAD

**Issue by almgwary** [Automattic/mongoose#5876]
We have a calendar API for booking a slot during a day

**SlotShcema** 

    startDateTime:Date  // showing the day and the starting hour
    duration:number // showing the slot duration 

we can calculate the slot end
  
  `endDateTime = startDateTime +  duration` 
 

We want add a validation, so no two slot intersect, and only one user can book it .

I found costume [Async Custom Validators](http://mongoosejs.com/docs/validation.html), but we cannot find any doc for our scenario .

Question at stackoverflow [https://stackoverflow.com/questions/47643429/mongoose-custom-validation-transaction-function](https://stackoverflow.com/questions/47643429/mongoose-custom-validation-transaction-function)

**Comment by vkarpov15** [comment]
There's an easy way to do this by just doing a query in an async custom validator to check using `$gte` and `$lte`. That would work except for a minor race condition where two concurrent saves might save conflicting bookings.

An alternative that doesn't have race conditions would be to, instead of structuring slots as a start time and duration, structure slots as just a `startTime` and assume that all slots have the same duration, say 30 minutes. Then you can just use a unique index.

Either way, this isn't really a bug report, so I'm gonna close this.

**Comment by almgwary** [comment]
@vkarpov15  
The issue is to find way to solve the race condition where two concurrent saves might save conflicting bookings "transaction"  . i did my own validate function before start create the slot, but if there is a race condition it may save two slots at same time which is wrong . 
**Is there any way to solve the race condition ?**

**Comment by almgwary** [comment]
@vkarpov15  we need help at this issue, as we want to go production ASAP .

**Comment by vkarpov15** [comment]
Creating the right unique index would be the easiest way http://thecodebarbarian.com/enforcing-uniqueness-with-mongodb-partial-unique-indexes.html . distributed locks would also work but be trickier

**Comment by almgwary** [comment]
**unique index**  won't work, for example 
```
let slot-1 = {startDateTime:09:00,endDateTime:09:59}
let slot-2 = {startDateTime:09:30,endDateTime:09:45}
let slot-3 = {startDateTime:08:00,endDateTime:09:15}
```
these 3 slots will be saved in race condition, which is wrong

**Comment by vkarpov15** [comment]
Yes, for unique indexes to work you would have to assume each slot is the same length, say 30 mins, and starts in 30 minute intervals. May be too limiting for your use case. Try this lib for distributed locks https://www.npmjs.com/package/mongoose-distributed-lock

**Comment by almgwary** [comment]
Final work around worked for me is to call the function in queue with callback . it works for me, but it little slow . 

This an example [JS-Promise-Race-Condition-Queue](https://github.com/almgwary/JS-Promise-Race-Condition-Queue)
- - - - -
if you want to make this solution faster  you should make queue per intersection which will make the concurrency conflict . for example date range .
