### ISSUE TITLE
Save() should fail, rather than block, if model is not associate with connection

### ISSUE THREAD

**Issue by ajmas** [Automattic/mongoose#5879]
**Do you want to request a *feature* or report a *bug*?**

Bug, though it could be considered a feature?

**What is the current behavior?**

If a model is created via mongoose.model() and then we connect using `createConnection()` attempts to model.save() will result in a blocked promise.

While `connect()` will resolve the issue, it is not clear in the documentation or failure that this is the solution. 

**If the current behavior is a bug, please provide the steps to reproduce.**

[test.js.txt](https://github.com/Automattic/mongoose/files/1540962/test.js.txt)

**What is the expected behavior?**

`save()` method should throw an exception or some behaviour to make it clear there is an issue. 

**Please mention your node.js, mongoose and MongoDB version.**

Environment: 

  - nodejs 8.9.0
  - node modules: 
    - mongoose 4.13.6
    - mongodb 2.2.33
  - MongoDB server 3.2.9

**Comment by varunjayaraman** [comment]
yeah youre right, it does hang, although If I remember correctly thats because the default behavior is to buffer commands until the connection is established, so I believe the behavior is intentional. For now I will label this as a potential bug and a docs issue depending on where we decide to go with it.

Looping @vkarpov15 in here because he'll have more knowledge on the matter but heres a repro script that is more copy pastable:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5879`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

const UserSchema = new Schema({
    email: { type: String, required: true, index: { unique: true } },   
    name: { type: String, required: false },
    password: { type: String, required: true }
});

console.log('connection string', connectionString);


const User = mongoose.model('User', UserSchema);

mongoose.createConnection(connectionString, {
    useMongoClient: true
})
.then((connection) => {


    connection.on('open', function() {
       console.log('open'); 
    });

    connection.on('error', function() {
        console.log('error'); 
     });

    const user = new User({
        email: 'someuser@somedomain.com',
        password: 'xxxxx'
    });

    const prom = user.save();

    // Displays: 'promise: Promise { <pending> }'
    console.log('promise:', prom);

    return prom
    .then((result) => {
        // Don't see this output
        console.log('result:', result);
    })
    .catch((error) => {
        // Don't see this output either
        console.log('error:', error);
    });
})
.catch((error) => {
    console.log(error);
});
```

**Comment by vkarpov15** [comment]
Buffering is something we've thought about removing now that there's async/await and callbacks are largely a thing of the past. Unfortunately that's a huge backwards breaking change that we don't want to make right now. We have this question on the [FAQ](http://mongoosejs.com/docs/faq.html#callback_never_executes)  and there's also the [bufferCommands option](http://mongoosejs.com/docs/guide.html#bufferCommands) option for both schemas and connections. If you want to opt out of buffering, just do this:

```javascript
const UserSchema = new Schema({
    email: { type: String, required: true, index: { unique: true } },   
    name: { type: String, required: false },
    password: { type: String, required: true }
}, { bufferCommands: false });
```

**Comment by vkarpov15** [comment]
5.0.0 will also have the ability to shut buffering off for all connections with 1 line:

```javascript
mongoose.set('bufferCommands', false);
```
