### ISSUE TITLE
Problem: Array not returning values.

### ISSUE THREAD

**Issue by RobJmz** [Automattic/mongoose#5884]
I ran into a problem and I can't seem to get where is my mistake.

I am making a call from my frontend to my backend, in my backend I call:
(I am using VueJS + NodeJS + Express + MongoDB

`City.findById(params.idCity)`

My schema is:
```
name: {
    type: String
  },
  coordinates: [
    [Number]
  ],
  pickupLocations: [{
    coordinates: {
      lat: Number,
      lng: Number
    }
  }]
```

I print my returned object city to the console and it prints out all my properties correctly except for the coordinates array.

It prints out:

```
2017-12-08T23:37:45.569794+00:00 app[web.1]: [ { _id: 5a1dce7f59fe5b0014997881,
2017-12-08T23:37:45.569806+00:00 app[web.1]:     updatedAt: 2017-12-08T21:31:28.925Z,
2017-12-08T23:37:45.569807+00:00 app[web.1]:     createdAt: 2017-11-28T21:00:47.798Z,
2017-12-08T23:37:45.569808+00:00 app[web.1]:     name: 'Monterrey',
2017-12-08T23:37:45.569808+00:00 app[web.1]:     __v: 160,
2017-12-08T23:37:45.569809+00:00 app[web.1]:     pickupLocations: [],
2017-12-08T23:37:45.569813+00:00 app[web.1]:     coordinates: [] } ]
```

Although when I do search my array with Robo T3 i clearly get the following:
![image](https://user-images.githubusercontent.com/10425977/33789615-83d6dae8-dc3f-11e7-8121-1b077df5a72c.png)

So it clearly has data in my array, but I can't seem to retrieve it, the only big concern I have is the fact that there are so many arrays inside that array, and maybe it generates that problem.

Any clue what is happening wrong or how I can handle it?

As a note: I inserted the document with Robo T3 and not with mongoose, since I couldn't update my document with nodeJS, I think it is because it's a very large array, is there any way to properly handle them?

**Comment by JasonCust** [comment]
Quoting from the referenced [contributing](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) guidelines when creating a new issue:
> If you have a question about Mongoose (not a bug report) please post it to either [StackOverflow](http://stackoverflow.com/questions/tagged/mongoose), or on [Gitter](https://gitter.im/Automattic/mongoose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

You are more likely to get a response much sooner on either of those while not adding to a backlog of bugs/features that the maintainers need to sift through here.

**Comment by varunjayaraman** [comment]
I'm not able to reproduce your issue:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5884`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    yield mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`, { useMongoClient: true })
    const schema = new mongoose.Schema({
      coordinates: [[Number]]
    });


    const Model = mongoose.model('Model', schema);

    const doc = yield Model.create({ coordinates: [[2, 3], [4, 5]]});

    console.log(yield Model.findById(doc._id));
  });
}
```

the log output:

```
[[2,3],[4,5]]
{ _id: 5a3b21483f68692e3fd561bb,
  __v: 0,
  coordinates: [ [ 2, 3 ], [ 4, 5 ] ] }
successfully ran program
```
