### ISSUE TITLE
Populate does not call discriminators' middleware.

### ISSUE THREAD

**Issue by phyllisstein** [Automattic/mongoose#5886]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Calls to `Query#populate` appear to fire the `find` middleware for the model being populated. However, if the model being populated is a discriminator, only the root model's middleware are invoked.

**If the current behavior is a bug, please provide the steps to reproduce.**
<details>
  <summary>Test Script</summary>

```js
import mongoose from 'mongoose'
import Promise from 'bluebird'

mongoose.Promise = Promise

const personSchema = new mongoose.Schema({
  age: Number,
  name: String,
  stories: [{ ref: 'Story', type: mongoose.Schema.Types.ObjectId }],
}, { discriminatorKey: 'kind' })

personSchema
  .pre('findOne', function(next) {
    console.log('personSchema#findOne')
    next()
  })
  .pre('find', function(next) {
    console.log('personSchema#find')
    next()
  })

const storySchema = new mongoose.Schema({
  author: { ref: 'Person', type: mongoose.Schema.Types.ObjectId },
  fans: [{ ref: 'Person', type: mongoose.Schema.Types.ObjectId }],
  title: String,
})

storySchema
  .pre('findOne', function(next) {
    console.log('storySchema#findOne')
    next()
  })
  .pre('find', function(next) {
    console.log('storySchema#find')
    next()
  })

const fanSchema = new mongoose.Schema({
  favoriteCharacter: String,
})

fanSchema
  .pre('findOne', function(next) {
    console.log('storySchema#findOne')
    next()
  })
  .pre('find', function(next) {
    console.log('storySchema#find')
    next()
  })

const Person = mongoose.model('Person', personSchema)
const Story = mongoose.model('Story', storySchema)
const Fan = Person.discriminator('Fan', fanSchema)

;(async () => {
  await mongoose.connect('mongodb://db/test', { useMongoClient: true })
  await mongoose.connection.db.dropDatabase()

  const author = new Person({
    age: 50,
    name: 'Ian Fleming',
  })

  await author.save()

  const fan1 = new Fan({
    favoriteCharacter: 'Bond... James Bond',
  })

  await fan1.save()

  const story1 = new Story({
    author,
    title: 'Casino Royale',
  })

  story1.fans.push(fan1._id)

  await story1.save()

  const sa = await Story
    .findOne({ title: 'Casino Royale' })
    .populate('author')

  console.log('The author is %s', sa.author.name)

  const sf = await Story
    .findOne({ title: 'Casino Royale' })
    .populate('fans')

  console.log('The first fan\'s favorite character is %s', sf.fans[0].favoriteCharacter)
})()
```

</details>

**What is the expected behavior?**
The test script logs the following:

```
storySchema#findOne
personSchema#find
The author is Ian Fleming
storySchema#findOne
personSchema#find
The first fan's favorite character is Bond... James Bond
```

I would expect to see `fanSchema#find` logged to the console during the second query, in addition to `personSchema#find`, based on the docs:

> Discriminators also take their base schema's pre and post middleware. However, you can also attach middleware to the discriminator schema without affecting the base schema.

**Please mention your node.js, mongoose and MongoDB version.**

Node.js `v9.2.1`
Mongoose `v4.13.6`
MongoDB `v3.6.0`

---

Please let me know if I can furnish any additional color! It's not impossible that I'm misunderstanding something, but I haven't gotten very far trying to understand what 🙊. Thanks in advance for taking a look.

**Comment by phyllisstein** [comment]
Not seconds after posting this issue I noticed that changing the `fans` object's `ref` to `Fans` in the `storySchema` caused the middleware to fire as expected:

```diff
@@ -20,9 +20,9 @@
})

const storySchema = new mongoose.Schema({
author: { ref: ‘Person’, type: mongoose.Schema.Types.ObjectId },
- fans: [{ ref: 'Person', type: mongoose.Schema.Types.ObjectId }],
+ fans: [{ ref: 'Fan', type: mongoose.Schema.Types.ObjectId }],
title: String,
})

storySchema
```

This doesn't quite solve the issue that I'm having in my actual application, though. I was hoping to prepopulate a schema property that could be one of several types using the pre-`find` hooks; unfortunately, none of the child schemas' hooks fire because the parent uses a generic `ref` to its own model. (I don't think I'm explaining myself especially well, but there's code here: <https://gist.github.com/phyllisstein/b51cb0aeea941392ad1ab4aabb836a54>.) Is there any way to propagate the `find` calls down to discriminators?

I suspect this can be closed as a bug, but I'd still be grateful for thoughts or advice. Thanks so much!

**Comment by vkarpov15** [comment]
Unfortunately not, find() hooks are attached to the model you're calling find() on, so the Fan models find hooks will never fire if you call Person.find(). You might try doing this in the personSchema's post find hook, there you can loop through all result docs and attach whatever properties you desire

**Comment by phyllisstein** [comment]
Thanks for the suggestion! I'll give that a shot. I also found that I could call `this.populate('discriminatorAttribute')` in the root model's `find` hook and that it would populate the attribute if it was present.
