### ISSUE TITLE
explain() doesn't execute pre or post aggregate hooks

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5887]

**Comment by jdmoliner** [comment]
Any news? Moongose 5.6.0 doesn't execute explair() with aggregate.

With this;

Model.aggregate([...]).explain("executionStats")

I get:

Model.aggregate(...).explain(...).exec is not a function

**Comment by vkarpov15** [comment]
@jdmoliner that isn't what this issue is about. `explain()` returns a promise as shown in the docs you linked to, so no need to call `exec()`
