### ISSUE TITLE
Change Streams and Mongoose

### ISSUE THREAD

**Issue by MDrooker** [Automattic/mongoose#5888]
Thoughts on how/when Change Streams (now released in 3.6) will be implemented in Mongoose?  
5.0?

Or a release before?

**Comment by vkarpov15** [comment]
Planning on releasing 5.0.0-rc0 in the next couple weeks, which will use mongodn driver 3.x. We currently do not have any plans to build features on top of the drives change streams support. Please follow mongoose on Twitter: https://twitter.com/mongoosejs?s=09 or join our slack channel for updates

**Comment by markstos** [comment]
@MDrooker Mongoose does support Change Streams in 5.0. Docs are are here: https://github.com/Automattic/mongoose/issues/5888

**Comment by mattdone01** [comment]
Hi there. Are there docs for this? Can you do collection.watch({ fullDocument: 'updateLookup' }); I am keen to use it into a AWS Lambda function and replicate changes to S3 for Redshift ingestion.

**Comment by markstos** [comment]
@mattdone01 You asked "Are there docs for this?", but the the previous comment said "Docs are here" and provided a link. Did you follow the link?

**Comment by mattdone01** [comment]
I sure did. The Link provided doesn't go anywhere.

**Comment by markstos** [comment]
@mattdone01 As @vkarpov15 says, the underlying driver is used for this feature, which is documented here: https://docs.mongodb.com/manual/changeStreams/ You can select the "Node.js" tab.

**Comment by vkarpov15** [comment]
It'll be good to have mongoose-specific docs for this. The closest thing we have right now is [a blog post on the subject](http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html#change-streams-in-mongoose)

**Comment by vkarpov15** [comment]
@proworkdev can you show the code you're using? Is it the same code as from the blog post?

Also, does '/home/Documents/publicapis_db/src/data/db' exist? If not, you'll need to create that directory.
