### ISSUE TITLE
Multiple number of callback-style test written incorrectly

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#5891]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I've haven't looked through all the tests, but look at `schema.validation.test.js`. The `done` function is called synchronously and doesn't wait for any of the `asserts` to be done.

```
      it('array required', function(done) {
        var Loki = new Schema({
          likes: {type: Array, required: true}
        });

        Loki.path('likes').doValidate(null, function(err) {
          assert.ok(err instanceof ValidatorError);
        });

        Loki.path('likes').doValidate(undefined, function(err) {
          assert.ok(err instanceof ValidatorError);
        });

        Loki.path('likes').doValidate([], function(err) {
          assert.ok(err instanceof ValidatorError);
        });
        done();
      });
```

This causes just about anything to pass...

```
      it('array required', function(done) {
        var Loki = new Schema({
          likes: {type: Array, required: true}
        });

        Loki.path('likes').doValidate(['this test should throw an error'], function(err) {
          assert.ok(err instanceof ValidatorError);
        });
        done();
      });
```

I'll try to clean up some of these where I can, but I don't have a full understanding of the test suite to know where these issues may be.

**Comment by vkarpov15** [comment]
Good catch, definitely need to fix this.

**Comment by vkarpov15** [comment]
This issue isn't as major as I thought because `doValidate()` does execute synchronously in the case of these tests, but it's definitely worth refactoring because if we ever change `doValidate()` to always be async, these tests will be dangerously wrong.

**Comment by wlingke** [comment]
@vkarpov15 Yea doValidate can execute synchronously, but the way those tests are written, doValidate is executing asynchronously right? So we still need to fix them? Otherwise stuff like that example I shared will pass even though its supposed to fail.

```
it('array required', function(done) {
        var Loki = new Schema({
          likes: {type: Array, required: true}
        });

        Loki.path('likes').doValidate(['this test should throw an error'], function(err) {
          assert.ok(err instanceof ValidatorError);
        });
        done();
      });
```

**Comment by vkarpov15** [comment]
No `doValidate()` is calling the callback in the same tick in these tests as far as I can tell, but I might not be looking at the same test. Either way, we need to fix this.
