### ISSUE TITLE
When ever i run the application i always get "require not a function" which came from embedded.js

### ISSUE THREAD

**Issue by iamrommel** [Automattic/mongoose#5894]
I'm using mongoose 4.13.6 (which is the latest as of this writing).

**Do you want to request a *feature* or report a *bug*?**
I think this is a bug
**What is the current behavior?**
When ever i run the application i always get "require not a function" which came from embedded.js
See the image below
![image](https://user-images.githubusercontent.com/177265/33819844-762b9ccc-de87-11e7-8702-70a94d0ef925.png)
And it's point to **node_modules/mongoose/lib/types/embedded.js**
  
![image](https://user-images.githubusercontent.com/177265/33819858-8f67c1b6-de87-11e7-892d-1d21cdbb729f.png)

I was using 4.10.7, and everything was working fine before. Is there any breaking changes, that i needs to be aware between those version

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
Nodejs 8.4.0
Mongoose 4.13.6
MongoDb 3.4

Please also not that i was using this mongoose on my meteor app.

**Comment by vkarpov15** [comment]
No intentional breaking changes. Can you please provide more detailed code samples? Hard to make any headway on without seeing your webpack config and how youre using mongoose

**Comment by varunjayaraman** [comment]
Sorry, this is a known issue with recent versions of mongoose and webpack. It is proving extremely difficult to track down why this is happening, but we are aware of it. But ditto on what @vkarpov15 asked for, could we see your webpack config?
