### ISSUE TITLE
Pre hooks and timestamps not triggered

### ISSUE THREAD

**Issue by bitflower** [Automattic/mongoose#5897]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
No pre hooks are triggered. Also the timestamps are not updated.

**If the current behavior is a bug, please provide the steps to reproduce.**
## Schema (typescript):
```typescript
import { Schema, SchemaOptions, SchemaDefinition } from 'mongoose';

const schemaOptions: SchemaOptions = {
  timestamps: {
    createdAt: 'created',
    updatedAt: 'updated'
  },
  retainKeyOrder: true // http://mongoosejs.com/docs/guide.html#retainKeyOrder
};

const schemaDefinition: SchemaDefinition = {
  version: {
    type: Number,
    default: 1.0 // Application version
  },
  created: {
    type: Date,
    default: Date.now
  },
  updated: {
    type: Date,
    default: Date.now
  }
};

const BASE_SCHEMA: Schema = new Schema(schemaDefinition, schemaOptions);

// /******************
//  * Pre-save hook
//  ******************/

console.log('WOOOOP');

BASE_SCHEMA.pre('validate', beforeSave);
BASE_SCHEMA.pre('save', beforeSave);
BASE_SCHEMA.pre('update', beforeSave);
BASE_SCHEMA.pre('findOneAndUpdate', beforeSave);
function beforeSave(next: Function): void {
  console.log('MÖÖÖP');
  // Set dates
  const now: Date = new Date();
  this.updated = now;
  if (!this.created) {
    this.created = now;
}
next();
}

export { BASE_SCHEMA };
```
It is defined in an external node module which is being imported into an express app. Model instantiation, data creating, loading etc all works fine. Only the pre hooks and timestamps features don't work.

And this is a derived schema (via plugin mongoose-extend-schema recommended by mongoose team) that is used to instantiate models:
```typescript
import { Document } from 'mongoose';
import * as extendSchema from 'mongoose-extend-schema';
import { BASE_SCHEMA } from './base.schema';
import {
  REPOSITORY_FIELD_SCHEMA,
  IRepositoryField
} from './repository-field.schema';

export interface IRepositorySchema extends Document {
  name: String;
  namespace: String;
  type: String;
  fields: any[];
}

export class RepositoryItem {
  _id: string;
  name: string;
  namespace: string;
  fields: IRepositoryField[];
}

const repositoryFields: any = {
  name: {
    type: String,
    required: true,
    trim: true
  },
  namespace: {
    type: String,
    required: true,
    trim: true,
    lowercase: true,
    index: {
      unique: true,
      background: false
    }
    // validate: nameSpaceValidator
  },
  type: {
    type: String,
    default: 'coCustomCollection' // später weitere Optionen: 'REST-Resource', etc...
  },
  fields: [REPOSITORY_FIELD_SCHEMA]
};
export const REPOSITORY_SCHEMA = extendSchema(BASE_SCHEMA, repositoryFields);

```

I have already tried to put the ```pre```hooks on the derived ```REPOSITORY_SCHEMA``` schema - no effect!

## Model instantiation
```typescript
export function instantiateDataModel(
  mongooseInstance: Mongoose,
  repository: string
): Promise<Model<IRepositorySchema>> {
  return new Promise(resolve => {
    // Check if model was already created
    if (mongooseInstance.modelNames().indexOf(repository) < 0) {
      // Create dynamic model
      getDataSchema(mongooseInstance, repository).then((schema: Schema) => {
        resolve(
          mongooseInstance.model<IRepositorySchema>(
            repository,
            schema,
            repository
          )
        );
      });
    } else {
      // Use existing model
      resolve(mongooseInstance.model<IRepositorySchema>(repository));
    }
  });
}
```

```getDataSchema``` return the schema (a mix of the above BASE_SCHEMA and a dynamically filled ´´´fields```field), ```repository```is just a string. Like I said: I can write data, read it, delete it. All good. Except the hooks.....

**What is the expected behavior?**
Pre hook to be called and the timestamps to be set.

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose Version: 4.13.6
Node: 6.12.0
Mongo DB: 3.4.10

**Comment by bitflower** [comment]
One more thought: I'm handing over the main mongoose instance created in the express app to the module with the schema, models, etc.

Would this have any effects on the ```hooks```given that the other things work (reading, writing, deleting data)?

**Comment by vkarpov15** [comment]
Based on my reading of mongoose-schema-extend's source code, it looks like it doesn't actually copy the base schemas hooks... I will put in a pr for this later.

**Comment by vkarpov15** [comment]
I'm going to close this. If you want a simple workaround you can just use this function:

```javascript
function extendSchema(schema, definition) {
  var clone = schema.clone();
  schema.add(definition);
  return schema;
}
```

**Comment by bitflower** [comment]
Hey Valeri,
yeah, I put in some time to investigate as well. 

The ```schema.add()```way is neat!

Thanks

**Comment by Jule-** [comment]
@vkarpov15 just asking, is your code really what you want to write?

This make more sense to me:
```javascript
function extendSchema(schema, definition) {
  var clone = schema.clone();
  clone.add(definition);
  return clone;
}
```
😄

**Comment by vkarpov15** [comment]
@Jule- you're right, thanks for pointing out my mistake, I'll fix that to prevent future confusion.
