### ISSUE TITLE
New Feature save Embedded Docs as hash/object ??

### ISSUE THREAD

**Issue by hiteshsomani** [Automattic/mongoose#5898]
**Do you want to request a *feature* or report a *bug*?**
  Feature
**What is the current behavior?**
    Docs States that http://mongoosejs.com/docs/2.7.x/docs/embedded-documents.html You can embed a docs as an array . If one can embed a docs as `json` the retrieval will be faster as one doesn't has to iterate on the entire array , one can fetch data from  the key .
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
I don't understand your suggestion, can you clarify?

**Comment by hiteshsomani** [comment]
As per my understanding after going through [mongoose-embedded-docs](http://mongoosejs.com/docs/2.7.x/docs/embedded-documents.htmll)

        var Comments = new Schema({
                title     : String
               , body      : String
               , date      : Date
        });

     
         var BlogPost = new Schema({
               author    : ObjectId
              , title     : String
              , body      : String
              , date      : Date
              , comments  : [Comments] // can't it be {Comments}  one doesn't have to iterate if its a json
                            // if someOne have to fetch a particular comment one has to itirate
                           // over the array , if its a json one can fetch it by its key  
              , meta      : {
              votes : Number
             , favs  : Number
          }
      });

       mongoose.model('BlogPost', BlogPost);

**Comment by varunjayaraman** [comment]
sorry I still don't understand what you're asking for? DO you want to store an array or a hash/object ?

**Comment by vkarpov15** [comment]
Mongoose currently doesn't have support for schema types with arbitrary keys (maps, hashes, etc.), follow #681 for updates. Planning on adding that in Q1 2018.
