### ISSUE TITLE
Schema.index() not working

### ISSUE THREAD

**Issue by srsandy** [Automattic/mongoose#5900]
Using "mongoose": "4.13.6"

I have Schema 
```
 import mongoose from 'mongoose';

 let fbUserSchema = mongoose.Schema({
    _id :  mongoose.Schema.Types.ObjectId,
    facebookId : { type: String, required: true, index: true},
    gender : String,
    profileUrl : String,
    imageUrl : String,
    firstName : String,
    token : String,
    email : String
 });

 fbUserSchema.index({firstName: 'text'});
 const fbUser = module.exports = mongoose.model('fbUser', fbUserSchema);
```

I do a query 

```
import fbUser from '../model/fbUser';

fbUser.find({ $text: { $search: 'Ann' } }, function(err, data) {
    if(err) throw err;
    console.log(data);
  });
```

This returns me 
`[]`

But in my collection, I have a firstName as 'Anna' .

```
{
    "_id" : ObjectId("5a26d554677475818a795f75"),
    "facebookId" : "123456",
    "gender" : "Female",
    "profileUrl" : "https://www.facebook.com/asdfasf",
    "imageUrl" : "/img/profile/sm1.jpg",
    "firstName" : "Anna",
    "token" : "ldhajksdkjasdakjsdajksd",
    "email" : "sm1@gmail.com"
}
```

PLS HELP ME 
ASAP

**Comment by JasonCust** [comment]
Quoting from the referenced [contributing](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) guidelines:
> If you have a question about Mongoose (not a bug report) please post it to either [StackOverflow](http://stackoverflow.com/questions/tagged/mongoose), or on [Gitter](https://gitter.im/Automattic/mongoose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

You are more likely to get a response much sooner on either of those while not adding to a backlog of bugs/features that the maintainers need to sift through here.

**Comment by vkarpov15** [comment]
Mongodb text search only matches whole words modulo stemming, see https://docs.mongodb.com/manual/reference/operator/query/text/#search-for-a-single-word . "Ann" will not match "Anna"
