### ISSUE TITLE
Possible issue with modifiedPaths for subdocument arrays

### ISSUE THREAD

**Issue by JasonCust** [Automattic/mongoose#5904]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure if this is a bug aside from the current behavior is dependent on if a property belongs to a subdocument or a subdocument array.

**What is the current behavior?**
Currently, if a subdocument is modified the full path is included in `doc.modifiedPaths()` whereas if the property was modified via adding a subdocument to an array only the subdocument path is included.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const teamSchema = new mongoose.Schema({
  name: String,
  colors: {
    primary: {
      type: String,
      enum: ['blue', 'green', 'red', 'purple', 'yellow', 'white', 'black']
    }
  },
  members: [{
    name: String,
  }]
});

const Team = connection.model('Team', teamSchema);

const jedis = new Team({
  name: 'Jedis',
  colors: {
    primary: 'blue'
  },
  members: [{ name: 'luke' }]
});

console.dir(jedis.modifiedPaths(), { depth: null, color: true });
// CURRENT: [ 'members', 'colors', 'colors.primary', 'name' ]
```

**What is the expected behavior?**
```js
// EXPECTED: [ 'colors', 'colors.primary', 'members', 'members.0', 'members.0.name', 'name' ]
```
**Please mention your node.js, mongoose and MongoDB version.**
Node: 4.8.7, 6.12.2, 8.6.0 (only three tested on)
Mongoose: 4.13.1
MongoDB: 3.4.10, 3.6.0 (only two tested on)

**Comment by vkarpov15** [comment]
Yeah this is an unfortunate implementation detail currently. Will take another stab at improving this but in the meantime, what issue is this behavior causing for you?

**Comment by JasonCust** [comment]
@vkarpov15 I wrote a plugin that uses the `modifiedPaths` method as a source of truth for all modified properties of a document to generate a diff object that has the original values, [mongoose-plugin-diff](https://github.com/CentralPing/mongoose-plugin-diff), specifically [line 66](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.js#L66).

I can't put out a new release on npm because the following tests would fail if I removed the `not` from the assertions: [line 92](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L92), [line 180](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L180), [line 251](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L251), [line 343](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L343), [line 360](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L360), [line 418](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L418), [line 510](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L510), and [line 527](https://github.com/CentralPing/mongoose-plugin-diff/blob/master/lib/index.test.js#L527).

**Comment by vkarpov15** [comment]
Thanks for the detailed links, I'll take a closer look at this later. Right now we're finishing up working on 5.x, so we've fallen behind on issue reports, so thanks for being patient.

**Comment by JasonCust** [comment]
No worries. Let me know if you need any further information.

**Comment by vkarpov15** [comment]
Thanks for your patience, `console.dir(jedis.modifiedPaths({ includeChildren: true }), { depth: null, color: true });` will handle this case correctly in 5.1.7.
