### ISSUE TITLE
why is document#validateSync different in browser

### ISSUE THREAD

**Issue by alechstong** [Automattic/mongoose#5906]
mongoose version: 4.0.2 (included in a script tag as instructed in the [documentation](http://mongoosejs.com/docs/browser.html))

Expected behavior: same as it is in node env
Current behavior: does not accept any parameter

I moved some of the validation to ui, but got different behaviors. Apparently validateSync in browser does not accept the pathsToValidate param, and instead only validate the selected path (from the query that initiated the doc).

It is not difficult to workaround the difference, but I'm wondering if the inconsistency is there by design, or if there's any good reason for it?

**Comment by vkarpov15** [comment]
The pathsToValidate param wasn't added until 4.1.0, https://github.com/Automattic/mongoose/blob/master/History.md#410--2015-07-24 need to upgrade to that version in your script tag as well
