### ISSUE TITLE
Virtual populates and aggregates with $lookup

### ISSUE THREAD

**Issue by ramonitor** [Automattic/mongoose#5908]
I'm trying to do aggregations on Mongoose schemas that use the virtual populate functionality (using Mongoose 4.13, Mongo 3.4).

```
const ProjectSchema = new mongoose.Schema({
  projectId: Number,
  description: String
});

ProjectSchema.virtual('tasks', {
  ref: 'Task',
  localField: 'projectId',
  foreignField: 'projectId' 
  justOne: false
]);

const TaskSchema = new mongoose.Schema({
  taskId: Number,
  projectId: Number
  hours: Number
});

const Project = mongoose.model('Project', ProjectSchema);
const Task = mongoose.model('Task', TaskSchema);

```

Querying on Project and populating relating tasks is working fine using .populate() like:

`Project.find({projectId: <id>}).populate('tasks');
`

But now I would like to sum the hours on tasks by project (left the $sum part out below btw..). I'm only getting empty arrays back no matter what. Isn't it possible to aggregate with virtual populate or?

```
const result = await Project.aggregate([
   { $match : { projectId: <id> } },
   { $lookup: { 
       from: 'tasks',
       localField: 'projectId',
       foreignField: 'projectId',
       as: 'tasks'
     },
     {
        $unwind: '$tasks' 
     }
   }
 ]);
```

**Comment by JasonCust** [comment]
Quoting from the referenced [contributing](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) guidelines when creating a new issue:
> If you have a question about Mongoose (not a bug report) please post it to either [StackOverflow](http://stackoverflow.com/questions/tagged/mongoose), or on [Gitter](https://gitter.im/Automattic/mongoose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

You are more likely to get a response much sooner on either of those while not adding to a backlog of bugs/features that the maintainers need to sift through here.

**Comment by ramonitor** [comment]
@JasonCust, good point. I actually did post this question to Stackoverflow ([mongoose-virtual-populate-and-aggregates](https://stackoverflow.com/questions/47669178/mongoose-virtual-populate-and-aggregates) but could not get a proper response. I found a post that someone claims to get it working, but I could not find much in the Mongoose docs on the limitations of virtual populate.

**Comment by ramonitor** [comment]
@JasonCust, thanks for your SO example. Can be closed now.
