### ISSUE TITLE
Typescript: document id property

### ISSUE THREAD

**Issue by simonxca** [Automattic/mongoose#5911]
http://mongoosejs.com/docs/api.html#document_Document-id

Says the `id` property is a getter than returns a string version of `_id`.
If I initialize a schema using the option `{ id: false }`, that means the `id` property can be any type I want right?

Can we clarify this in the docs? Because my PR is being blocked.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21856#discussion_r157023816

**Comment by JasonCust** [comment]
It's pretty clear in the docs already: http://mongoosejs.com/docs/guide.html#id

It is linked from the documentation link you provided via `Schema options`.

**Comment by simonxca** [comment]
Thanks.

**Comment by vkarpov15** [comment]
Thanks for maintaining the TS bindings @simonxca and thanks for the issue help @JasonCust . A very merry Christmas to you both! 👍 🎄 🎅
