### ISSUE TITLE
collectionInstance.attribute.push() isn't working. MongoError: Unknown modifier: $pushAll

### ISSUE THREAD

**Issue by trainsOE2** [Automattic/mongoose#5912]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by trainsOE2** [comment]
mongoose: **4.13.7**
Mongodb version: **3.6.0**
node.js version: **8.9.1**

**Comment by trainsOE2** [comment]
https://github.com/trainsOE2/WebDev/blob/master/Associations/embed.js

Just trying to push an array element in the array "posts" which in turn is a field/attribute in a collection: "User".with the Schema: "userSchema"
The array: "posts" has the type "postSchema"  which is also a Schema in the collection: postSchema.

**Comment by trainsOE2** [comment]
.

**Comment by vkarpov15** [comment]
Use the usePushEach option in >= 4.6.4 as a workaround, 5.x will not have this issue but 4.x has backwards compatibility constraints.
