### ISSUE TITLE
[Feature Request]: Extend mongoose class

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Automattic/mongoose#5915]
I'm struggling on how to implement or add a pubsub service on the existing functions like this
i'm doing this on my apollo graphql server
for Example

```js
import pubsub from "./pubsub"
class User {
  update(data) {
    super.update(data)
    pubsub("Trybe","UPDATED",data)
  }
}

can i just use the mongoose class instead

rather using the schema.loadClass

**Comment by vkarpov15** [comment]
I don't understand, can you please clarify?

**Comment by ralphchristianeclipse** [comment]
@vkarpov15 

I mean if I can override the methods when I do a schema.loadClass

or maybe do a super on the functions

**Comment by vkarpov15** [comment]
I still don't understand. Can you please provide some code samples?
