### ISSUE TITLE
overriding schema.methods.toJSON not working when i get a error

### ISSUE THREAD

**Issue by supperdsj** [Automattic/mongoose#5916]
have a Schema like this
```
const UserSchema = new mongoose.Schema({
    email: {
        type: String,
        required: true,
        trim: true,
        minlength: 1,
        unique: true
    },
    password: {
        type: String,
        required: true,
        minlength: 6
    },
    tokens: [{
        access: {
            type: String,
            required: true
        },
        token: {
            type: String,
            required: true
        },
    }]
}, {
    usePushEach: true
});

UserSchema.methods.toJSON = function () {
    const user = this;
    const userObject = user.toObject();
    return {userObject.email,userObject._id};
};
```
and when i insert a user that email is already exist,will get result and 'UserSchema.methods.toJSON is not working
```
{
    "code": 11000,
    "index": 0,
    "errmsg": "E11000 duplicate key error collection: TodoApp.users index: email_1 dup key: { : \"2321717733@qq.com\" }",
    "op": {
        "email": "test@gmail.com",
        "password": "dsadsa",
        "_id": "5a3747e67242c915908185d4",
        "tokens": [],
        "__v": 0
    }
}
```

**Comment by vkarpov15** [comment]
I don't understand the problem. If email should be unique, wouldn't you expect that there would be an error if you same a user with a duplicate email? Also, isn't the return statement in your toJSON method invalid syntax?

**Comment by varunjayaraman** [comment]
The error message is self-explanatory here @supperdsj your issue is not your `toJSON` method( which @vkarpov15 mentioned is syntactically incorrect), but you have a unique index on email so it'll error if you try to insert the same email

**Comment by varunjayaraman** [comment]
@supperdsj can you let us know if you are still having trouble understanding the error message? I'm more than happy to explain further if so
