### ISSUE TITLE
Is there a way to define a sub document of sub documents?

### ISSUE THREAD

**Issue by lopugit** [Automattic/mongoose#5919]
**Do you want to request a *feature* or report a *bug*?**
request a feature, ask about one
**What is the current behavior?**
Currently you can only define a type of [ObjectId's, ref: 'some model'] but I have really been needing the usefulness of being able to say that a property is an object, where every property of that object must be a sub document or adhere to a schema.

Right now I'm giving my sub document schema a property called title, and a property called value, and then in production creating a "mapped" property on the array, looping over all the sub documents in the array, and going array.mapped[subdocument.title] = subdocument

so I was just wondering if this feature has been thought about?

**Please mention your node.js, mongoose and MongoDB version.**
node v8 and mongoose v4+ mongodb v idk what it's up to..

ty ty

**Comment by vkarpov15** [comment]
Perhaps [subdocs](http://mongoosejs.com/docs/subdocs.html)? I don't quite understand your question because prose descriptions of code tend to not convey intent well, can you provide some pseudocode please?

**Comment by lopugit** [comment]
yes @vkarpov15  sorry and thanks for the response, not sure why I didn't include some better examples

basically you can define a schema that says 

```javascript
```

**Comment by vkarpov15** [comment]
I see what you're asking for, arbitrary keys in an object is not something we support, but we're planning on adding that in Q1 2018. Follow #681 for updates.

**Comment by lopugit** [comment]
@vkarpov15  would it be that hard? It seems like just changing the array validation mechanism to loop over own properties instead of 0-length-1 like in an array, I might work on an implementation because I've needed it for some time. 

thanks for your reply :) <3

**Comment by vkarpov15** [comment]
Yeah I think a custom map type would be pretty useful. You're welcome to give it a shot, you can try [building a custom schema type plugin](http://mongoosejs.com/docs/customschematypes.html). You can ask for help on our [slack channel](http://slack.mongoosejs.io/)

**Comment by lopugit** [comment]
@vkarpov15 
what's up with this link? http://plugins.mongoosejs.io/

It doesn't load for me

**Comment by vkarpov15** [comment]
It's been down for a bit, haven't gotten around to fixing it because the app as written has some heavy memory needs.

**Comment by lopugit** [comment]
@vkarpov15 it's written in node right? I've run into some memory issues with node apps too, you just kind of write whatever logic you want, and then apps can balloon when running in production... 

I can try to write the plugin off other plugin examples :)

**Comment by vkarpov15** [comment]
Hahah the reason for ballooning is it imports every npm module that has "mongoose" in the keywords into a mongodb instance. We managed to get it to work with JSONstream but its still not as robust as I'd like.

**Comment by lopugit** [comment]
wait what how do you store a file system in mongodb?

**Comment by vkarpov15** [comment]
Not a file system, just a doc for every npm module with mongoose in the keywords. Nothing that sophisticated. 

If you want a mongodb backed file system theres mongofuse https://github.com/scotthernandez/mongo-fuse
