### ISSUE TITLE
Turn usePushEach on for all models?

### ISSUE THREAD

**Issue by ducdigital** [Automattic/mongoose#5924]
Since the mongodb upgraded to 3.6 and dropped all support for `$pushAll`, Would there be any possible way to set usePushEach on by default for all schemas? 

Node 8,
Mongoose 4.13.7 
Mongodb 3.6

**Comment by vkarpov15** [comment]
Should be able to do it with a one liner:

```javascript
mongoose.plugin(schema => { schema.options.usePushEach = true });
```

We'll be releasing 5.0.0-rc0 soon, which will remove the dependency on `$pushAll` for good.

**Comment by dhazlettjr** [comment]
```mongoose.plugin(schema => { schema.options.usePushEach = true });```

where should this go??

**Comment by lineus** [comment]
@dhazlettjr right after you require mongoose will work.

```js
const mongoose = require('mongoose');
mongoose.plugin(schema => { schema.options.usePushEach = true });
const mySchema = new mongoose.Schema({ stuff: String });
const Model = mongoose.model('model', mySchema);
const otherSchema = new mongoose.Schema({ otherStuff: String });
const OtherModel = mongoose.model('other', otherSchema);
```

This will apply the plugin to all future schema as documented [here](http://mongoosejs.com/docs/plugins.html#global)

**Comment by dcabib** [comment]
Guys, it worked for me... I have no Idea what is mongoose.plugin(schema => { schema.options.usePushEach = true }); but it works ;-)

Thanks a lot....

**Comment by ffbeatsolutions676** [comment]
Since the mongodb upgraded to 3.6 and dropped all support for $pushAll, Would there be any possible way to set usePushEach with Heroku (using mLab add-on for DB).

I am using Heroku for my application. I am not sure where to provide this.

**Comment by vkarpov15** [comment]
@ffbeatsolutions676 doesn't matter if you're using heroku or not, the below code should work.

```javascript
const mongoose = require('mongoose');
mongoose.plugin(schema => { schema.options.usePushEach = true });
```

**Comment by Codedecks** [comment]
Thank you, I've pulling my hair out try to find a solution for this issue.
