### ISSUE TITLE
Await promise never fulfills on disconnect or reconnect

### ISSUE THREAD

**Issue by bpoulse** [Automattic/mongoose#5928]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have an application that periodically pushes data from a local MongoDB to a server MongoDB. I am doing this because a lot of data can be generated quickly (to the point where the number of updates becomes the bottleneck) and the application must be able to handle a spotty internet connection.

No matter what I've tried, when the internet connection on localhost experiences issues, my mongo queries (launched by awaiting promises) never throws an error. Promise library is set to `bluebird`,  `bufferCommands` is set to false, `maxBufferEntries` is set to 0, and `autoReconnect` is set to false (just to rule out the option). On the other end, setting these options with defaults, if the internet connection is reestablished, the reconnected event is fired but the query never finishes (I tried leaving it for several hours). No errors are thrown to post. The process hangs on any queries that start with `this.cloud`.

I have also tried tracking the last time a promise was successfully fulfilled. If it lasts longer than a set threshold, I explicitly close the connection: `this.cloud.connection.close()` but to no avail. The promise is never rejected.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
    async syncData() {
        this.isSyncing = true;
        Logger.Synchronizer('Starting data sync...');
        try {
            let localRecords = await this.local.stateData.find().exec();
            Logger.Synchronizer(localRecords.length + ' records to sync...');
            await Promise.all(localRecords.map(record => this.cloud.stateData.findByIdAndUpdate(record._id, record, {
                upsert: true
            }).exec()));
            Logger.Synchronizer('Push successful! Removing completed local states...');
            await this.local.stateData.find({
                '_id': {
                    '$in': localRecords.filter(record => record.timeend !== null).map(record => record._id)
                }
            }).remove().exec();
            this.lastSynced = Moment.utc();
            Logger.Synchronizer('Data synced.');
        } catch (error) {
            Logger.Error(error);
        }
        this.isSyncing = false;
    };
```

**What is the expected behavior?**

With all buffer options set to false, the promise should be rejected and move on. With default options, the promise should be fulfilled at some point instead of hanging.

**Please mention your node.js, mongoose and MongoDB version.**

Node: 8.9.1
Mongoose: 4.13.7
MongoDB: 3.4.10

**Comment by markovchainz** [comment]
+1

**Comment by vkarpov15** [comment]
Just to be 100% clear, are you connected to a standalone mongodb server, a replica set, or a sharded cluster? Also, check out this blog post with some more details: http://thecodebarbarian.com/mongoose-4.12-improved-connection-events.html

**Comment by bpoulse** [comment]
I am using a replica set. The provided blog post is referring to when there are server(s) outages, which fires disconnected events. I haven't been able to get a disconnected event to fire (or a query to reject) when the *client's* internet goes down, which is my main problem. I have tried several combinations of timeouts. It might be my misunderstanding of how the Mongo driver handles replica sets, but I thought it should fail on all of them since the client connection is down. Currently, I have a workaround:
```javascript
function queryHandler(query, message, timeout) {
    return new Promise(((resolve, reject) => {
        setTimeout(() => {
            reject(message || 'Query Timeout');
        }, timeout || Config.SYNC_RATE*10);
        query.exec().then(data => resolve(data)).catch(error => reject(error));
    }));
}
```
If this is expected behaviour, I will close and post on SO on how to resolve my particular issue.

**Comment by vkarpov15** [comment]
Unfortunately I don't cover replica sets in that article, but there's some more detail on dealing with [replica sets with the node driver in this article](http://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html). The MongoDB driver very stubbornly refuses to give up on reconnecting to a replica set, so you should listen to `mongoose.connection.on('left')` to check if the primary left the replica set as described in the article. I'll look into why the queries aren't rejecting ASAP.

**Comment by vkarpov15** [comment]
The parameter to toggle here is `socketTimeoutMS`:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5928`;

mongoose.set('debug', true);

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    yield mongoose.connect(`mongodb://val:mypw@myuri/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin`, { useMongoClient: true, replicaSet: 'rs0', socketTimeoutMS: 5000, keepAlive: 1000 });
    
    const M = mongoose.model('Test', new mongoose.Schema({ x: Number }), 'Test');

    while (true) {
      console.log('Executing query...');
      yield M.findOne();
      console.log('done');
      yield cb => setTimeout(() => cb(), 1000);
    }
  });
}
```

Disabling wifi then gives me a nice timeout error when connected to a mongodb atlas replica set:

```
$ node gh-5928.js 
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
done
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
done
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
done
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
done
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
done
Executing query...
Mongoose: Test.findOne({}, { fields: {} })
Error: MongoError: connection 1 to XXXX:27017 timed out
MongoError: connection 1 to XXXX:27017 timed out
    at Function.MongoError.create (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
    at TLSSocket.<anonymous> (/home/val/Workspace/MongoDB/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:198:20)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:400:8)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
^C
$ 
```
