### ISSUE TITLE
doc.pull inconsistent behaviour when multiple pull request

### ISSUE THREAD

**Issue by boulepick** [Automattic/mongoose#5931]
node v7.7.1
mongodb: 2.2.33,
mongoose: 4.13.7

Hello all,

i'm having this unexpected behaviour when trying to update a document with multiple pull request based on matching criterias. here is what i mean

my document schma looks like this

```
{
    "_id": "5a1c0c37d1c8b6323860dfd0",
    "ID": "1511781786844",
    "main": {
        "_id": "5a3c37bfc065e86a5c593967",
        "plan": [
            {
                "field1": 1,
                "field2": 1,
                "_id": "5a3c30dfa479bb4b5887e56e",
                "child": []
            },
            {
                "field1": 1,
                "field2": 2,
                "_id": "5a3c30e1a479bb4b5887e5c",
                "child": []
            },
            {
                "field1": 1,
                "field2": 3,
                "_id": "5a3c37bfc065e86a5c593968",
                "child": []
            },
            {
                "field1": 1,
                "field2": 4,
                "_id": "5a3c37bfc065e86a5c593655",
                "child": []
            },
            {
                "field1": 1,
                "field2": 5,
                "_id": "5a3c30dfa479bb4b5887e56f",
                "child": []
            },
            {
                "field1": 1,
                "field2": 6,
                "_id": "5a3c30e1a479bb4b6887e545",
                "child": []
            },
            {
                "field1": 1,
                "field2": 7,
                "_id": "5a3c37bfc065e86a5c5939658",
                "child": []
            },
            {
                "field1": 2,
                "field2": 2,
                "_id": "5a3c37bfc065e86a5c593963",
                "child": []
            },
        ]
    },
		...
		....
}
```

and this is my code to update the document:

```
Schema.findOne({ID: data.ID})
      .then(function(doc) {

        var array = doc.main.plan;

	for (i = 0; i < array.length; i++) {
		if ( array[i].field1=== 1 )) {
			var id = array[i]._id;
			console.log('pulling');
			doc.pull( { _id: id });
		}
	}

	doc.save().then(function(doc) {
		console.log('saving');
		// console.log(doc);
		if (doc && doc.docID) {
			return { success: true };
		} else {
			return { success: false, error: 'unknownError'}
		}
	})
}
```
now the issue is let's say  my array has 7 objects that matches the test (array[i].theField === parseInt(updFields.theField)), when i run this and check the logs i see that it will basically pull half of the objects and do a save.

so i would get 
pulling
pulling
pulling
pulling
save.

and then i have to run the code for the remaining 3 objects in the array and get 
pulling
pulling
saving

so i have to run  it a third time to completely clear the array.

**Comment by vkarpov15** [comment]
I don't understand, can you clarify your issue with some more code samples? You lost me on that last part, after "now the issue is..."

**Comment by KingDGrizzle** [comment]
If I understand this right, he means:

- He runs a test that matches 7 elements in the array of child-objects
- He iterates through said 7 elements, removing them in the process.

The first time he iterates through, 4 of the elements get removed. Another iteration removes the rest.

I'll attempt to create a easy-to-show code sample to see if this is a bug or not

**Comment by KingDGrizzle** [comment]
Awesome. I got this to be reproduced with [this script](https://gist.github.com/KingDGrizzle/7c274172050689b1ea69369e784c7410) (of course, most things are just to make sure they're not equal, but this should allow you to reproduce the issue)

The expected result was that in the `plan` array there would only ever remain the object that doesn't pass the filter. In fact, it seems like that is not the case, and in my testing, it removed 5 of the child-objects that passed the check then saved. Probably requiring another run on the same ID.

**Comment by boulepick** [comment]
Thanks KingDGrizzle, this is exactly the issue. so basically in my case to remove the 7 elements that matches i have to go through 3 iterations. the first one removes 4, the second removes 2 and then one last time to remove the last one. This should be only one iteration to remove all the elements that matches the test.

**Comment by vkarpov15** [comment]
Ah I see the issue. Going by @KingDGrizzle 's [example](https://gist.github.com/KingDGrizzle/7c274172050689b1ea69369e784c7410), `doc.main.plan.pull({ _id: id });` mutates the length of the array and removes the first element. Same thing happens if you do `splice()` on a plain old JS array in a for loop. Do this instead:

```javascript
                doc.pull({ almostAlwaysEqual: 1 });
```

**Comment by boulepick** [comment]
Thanks for all the help, however it still did not work. so i created a little workaround by doing a recursive function to pull all with only one click. not pretty but it does the job.

```
const delObjArray = (doc, cond) => {
      const checkField = cond.field;
      const checkVal = cond.value;
      _.forEach(doc, (value) => {
        if (value && value[checkField] === checkVal) {
          doc.pull({ _id: value._id });
        }
      });
      const isFound = _.some(doc, { [checkField]: checkVal });
      if (isFound) {
        delObjArray(doc, cond);
      } else {
        return true;
      }
      return true;
    };
```
