### ISSUE TITLE
Connection method is not documented similarly in documentations.

### ISSUE THREAD

**Issue by livey0u** [Automattic/mongoose#5933]
In `http://mongoosejs.com/docs/connections.html` page, `mongoose.connect` method options are documented as follows:
<img width="759" alt="screen shot 2017-12-22 at 1 26 14 pm" src="https://user-images.githubusercontent.com/25579753/34286454-c817078c-e71b-11e7-942e-beae33bc3956.png">
In `http://mongoosejs.com/docs/guide.html`, `mongoose.connect` method options are documented as follows:
<img width="726" alt="screen shot 2017-12-22 at 1 28 05 pm" src="https://user-images.githubusercontent.com/25579753/34286501-fa8d0e96-e71b-11e7-869d-01de5d42f13a.png">

Notice that, the actual `options` are nested inside `config` property in the later.

**Comment by vkarpov15** [comment]
Good catch, will fix asap. Thanks :+1:
