### ISSUE TITLE
Hooks for distinct

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5938]

**Comment by bojanbass** [comment]
Hi. Looks like distinct hooks are not implemented yet. Is there any workaround to apply some additional query filters on distinct queries?

**Comment by vkarpov15** [comment]
@bojanbass not currently. Will add for our next minor release. In the meantime, you could just add your own `distinct()` method: https://mongoosejs.com/docs/api.html#model_Model.distinct, https://mongoosejs.com/docs/guide.html#methods

**Comment by bojanbass** [comment]
Ok, thank you for the answer.
