### ISSUE TITLE
Unexpected virtual property behavior

### ISSUE THREAD

**Issue by khacminh** [Automattic/mongoose#5943]
**Do you want to request a *feature* or report a *bug*?**

This is a **BUG**

**What is the current behavior?**
In my schema, I would like to add non-saved property, but can be export when using **toJSON()**. So that, I define it as a virtual property. However, the virtual property doesn't working as my expected (or I misunderstood the way virtual property works) 

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is my code:
```javascript
const mongoose = require('mongoose');
const { Schema } = mongoose;

const mySchema = new Schema({
    name: { type: String, required: true },
});

mySchema.virtual('vProp')
  .get(() => this.vProp)
  .set((v) => { this.vProp = v; });

const Model = mongoose.model('model', mySchema);

const items = [];
for (let i = 0; i < 5; i += 1) {
    const item = new Model({name: `item + ${i + 1}`});
    item.vProp = i;
    items.push(item);
}

for (let i = 0; i < items.length; i += 1) {
    const item = items[i];
    const jsonItem = item.toJSON({ virtuals: true });
    console.log(jsonItem.vProp);
}
```

**What is the expected behavior?**

I expected the result will be:
```sh
2
4
6
8
```

But what I get is:

```sh
8
8
8
8
```

----
If I replace block
```javascript
mySchema.virtual('vProp')
  .get(() => this.vProp)
  .set((v) => { this.vProp = v; });
```
by:
```javascript
mySchema.virtual('vProp')
   .get(function getFunc() { return this.vProp;})
   .set(function setFunc(v) { this.vProp = v; });
```

The ​​**Maximum call stack size exceeded​​** exception will occurs at line
```javascript
item.vProp = i * 2;
```

**Please mention your node.js, mongoose and MongoDB version.**
I'm using node.js version **8.9.1**, mongoose version **4.13.8** and MongoDB **3.4**

**Comment by vkarpov15** [comment]
Do this instead:

```javascript
mySchema.virtual('vProp')
   .get(function getFunc() { return this._vProp;})
   .set(function setFunc(v) { this._vProp = v; });
```

If the setter for `vProp` does a set on `vProp`, you'll get infinite recursion.
