### ISSUE TITLE
[Discussion] Automate Dependency Upgrades

### ISSUE THREAD

**Issue by ChristianMurphy** [Automattic/mongoose#5953]
**Do you want to request a *feature* or report a *bug*?**

infrastructure feature

**What is the current behavior?**

Dependencies are upgraded manually, `dependencies` are updated fairly regularly, `devDependencies` semi-regularly.

**What is the expected behavior?**

This process _could_ be automated to run on a regular schedule or update whenever a new version is released.

**Potential Solutions**

[Renovate](https://renovateapp.com) and [GreenKeeper](https://greenkeeper.io) both can handle automated dependency upgrades.
GreenKeeper has pretty good defaults, and is fast at upgrading, but offers little configuration.
Renovate needs configuration to be set, but is flexible as to when and how it will upgrade dependencies.

**Caveats**

GreenKeeper can become noisy (comment and PR wise) if versions aren't upgraded, renovate has options for [managing noise](https://renovateapp.com/docs/deep-dives/noise-reduction).
PRs still require manual review, renovate offers [automerging](https://renovateapp.com/docs/deep-dives/noise-reduction#automerging), but that requires significant trust in the tests.

**Benefits**

Automate tracking down new versions, which otherwise can be menial and time consuming.

**Comment by vkarpov15** [comment]
Setting up greenkeeper sounds like a good idea. Do you have any experience doing that @ChristianMurphy ?

**Comment by ChristianMurphy** [comment]
I've set both systems up before.
GreenKeeper has a setup guide https://greenkeeper.io/docs.html#installation that covers the process pretty well.

Renovate has a similar initial setup: https://renovateapp.com/docs/getting-started/install-github-app
They also having configuration set in package.json ([example](https://github.com/ChristianMurphy/selective/blob/3d91990b5fc04191b269fc877759d4fd43cbec51/package.json#L79-L90), [list of configs](https://renovateapp.com/docs/configuration-reference/config-presets#example-configs), [list of options](https://renovateapp.com/docs/configuration-reference/configuration-options))

**Comment by vkarpov15** [comment]
Could you set it up for mongoose or would you need push access to do that?

**Comment by ChristianMurphy** [comment]
I believe the hosted versions of GreenKeeper and Renovate both require an organization admin to do the setup.

**Comment by vkarpov15** [comment]
That's going to be a major problem, I don't have admin access to the Automattic org and don't have any connections within Automattic to figure out how we might get them to set that up.

**Comment by ChristianMurphy** [comment]
Yep, that's going to be a blocker. :disappointed: 
Both services are open source and can be custom hosted, but that cost money :dollar: :euro: 

I'll close this out for now, it can be revisited later.

**Comment by ChristianMurphy** [comment]
Renovate has become pretty easy to self host now, and the self hosted version does not need admin access.
Opened #7481 with more information.
