### ISSUE TITLE
[5.x] legacy pluralization not working by default

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#5958]
User collection is named `User` as opposed to `users` for instance.  I think the plugin is not working out of the box on the latest 5.x rc in npm.

**Comment by vkarpov15** [comment]
This only affects `mongoose.model()`, if you're using `mongoose.createConnection().model()` it works, we just missed a spot in our tests and logic.

**Comment by vkarpov15** [comment]
Good catch, this affected `mongoose.model()` and was fixed in 5.0.0-rc1
