### ISSUE TITLE
5.0.0-rc1 the options [useMongoClient] is not supported

### ISSUE THREAD

**Issue by Jinshihao** [Automattic/mongoose#5961]
The 5.x version was not supported useMongoClient？I  create a connection use createConnection(uri,{useMongoClient:true}) ,but receive the warn;

```
const db = mongoose.createConnection(config.db, {
    poolSize: 20,
    useMongoClient: true
});
```

`waring:the options [useMongoClient] is not supported`

NodeVersion:8.9.3
MongodbVersion:3.4.10

**Comment by happyzhanls** [comment]
The quick start page does not show a connect initialization with the "useMongoClient" options though. There will be a final version later released so I won't worry too much. 
Link: -> http://mongoosejs.com/docs/index.html.

**Comment by vkarpov15** [comment]
Apologies for the confusion. We'll update the docs. The `useMongoClient` option is no longer necessary in >= 5.0.0-rc0.

**Comment by cheri3a** [comment]
thank-s
