### ISSUE TITLE
Couldn't run all tests on branch 5.0.

### ISSUE THREAD

**Issue by fenanquin** [Automattic/mongoose#5963]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
I was reading the contributing file and I tried to run the tests on branch 5.0, so I executed npm test, but after some time MongoDB 3.6 threw the following error many times:

2018-01-03T22:10:32.645-0200 I NETWORK  [listener] Error accepting new connection on 127.0.0.1:27017: Too many open files

And then it crashed stating:
Aborted (core dumped)

**If the current behavior is a bug, please provide the steps to reproduce.**

Execute: npm test on branch 5.0, without any additional flags.

**What is the expected behavior?**
To execute all the defined test cases.

**Please mention your node.js, mongoose and MongoDB version.**
node 9.3.0, mongoose 5.0.0-pre and MongoDB 3.6

**Comment by vkarpov15** [comment]
I'm going to venture a guess and say you're using OSX because I've seen this issue with many mongodb projects on OSX. Here's a few approaches to fix this issue:

1) https://stackoverflow.com/questions/20931909/too-many-open-files-while-ensure-index-mongo
2) Use the mmapv1 storage engine: https://docs.mongodb.com/manual/core/mmapv1/
3) Run tests on some flavor of linux or windows powershell

Do any of these work for you?

**Comment by fenanquin** [comment]
The first and second approaches worked pretty well.
Since I am using Ubuntu I didn't need to test the third one.

Thank You!

**Comment by vkarpov15** [comment]
Ah my mistake, I just find most mongoose devs use macs :+1: :palm_tree: We use mmapv1 for tests on Travis to work around this issue without using ulimit: https://github.com/Automattic/mongoose/blob/57b26e24dec91d97b85081d101da1683c142aed8/.travis.yml#L15

**Comment by fenanquin** [comment]
I ran all the test cases a few times using wiredTiger and mmapv1 and I found out that, at least on Ubuntu, it took double of the time when wiredTiger is used. So, definitely, it's much better to use mmapv1 on the tests. I think it would be nice including the mmap flag on [contributing](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#running-the-tests).

While running the test cases, I also found out that with the flag [--nojournal](https://docs.mongodb.com/v3.0/reference/program/mongod/#cmdoption-nojournal) on mongod using mmap, data files occupy about 640MB on file system, and without that flag, they occupy about 3.8GB, journal folder occupies 3.2GB (O.O), so I think it's worth to add that flag on [travis](https://github.com/Automattic/mongoose/blob/57b26e24dec91d97b85081d101da1683c142aed8/.travis.yml#L15). 

I also saw on [travis](https://github.com/Automattic/mongoose/blob/57b26e24dec91d97b85081d101da1683c142aed8/.travis.yml#L15) that it's starting mongod with the flag [--nopreallocj](https://docs.mongodb.com/v3.0/reference/program/mongod/#cmdoption-noprealloc) which is deprecated since MongoDB 2.6, then it can be removed.

**Comment by vkarpov15** [comment]
Good idea

**Comment by fenanquin** [comment]
May I work on this task of the connections you've mentioned?

**Comment by vkarpov15** [comment]
Please do, that would be much appreciated. Should mostly consist of just taking tests that do `var db = start();` and pulling that out into a mocha `before()` hook

**Comment by vkarpov15** [comment]
I added a note to contributing, going to move this to another milestone for future work re: refactoring tests to start fewer connections

**Comment by fenanquin** [comment]
I've finished the refactoring about the connections, but I have the following doubt: as this task is labeled as 5.x, it should makes part of branch 5.0 (correct?), then I did all the work on my branch 5.0, but I rebased it from mongoose repo master to keep it synced and now it is 66 commits ahead of the mongoose branch 5.0. So, which path (master or 5.0) should I consider on my pull request to avoid possible conflicts?

Another thing, these tests ['watch() (gh-5964)'](https://github.com/Automattic/mongoose/blob/master/test/model.test.js#L5078) and ['watch() before connecting (gh-5964)'](https://github.com/Automattic/mongoose/blob/master/test/model.test.js#L5097) are failing on my machine. I runned mongod using mmap, and they failed stating: 
`Uncaught MongoError: Majority read concern requested, but it is not supported by the storage engine.`, 
then I switched the storage engine to wiredTiger and they also failed but now stating: 
`Uncaught MongoError: The $changeStream stage is only supported on replica sets`.
So, should we now run mongod with replica sets on tests?

**Comment by vkarpov15** [comment]
Ah you're using MongoDB 3.6? I usually run tests against 3.4, but for 3.6 tests I run `./$(THREE-SIX)/bin/mongod --nojournal --noprealloc --ipv6 --enableMajorityReadConcern --replSet rs0`.

Also, please make the changes against master. The 5.0 branch was for the work we did to get 5.0.0-rc0 out, but new changes go into master.

**Comment by fenanquin** [comment]
Yes, I'm using MongoDB 3.6.
With the flags you've mentioned, those tests worked, thanks.

**Comment by Fonger** [comment]
I had the same issue on my Ubuntu 16.04. Increase the [ulimit](https://docs.mongodb.com/manual/reference/ulimit/) helps.

**Comment by vkarpov15** [comment]
@Fonger good idea. Maybe we put it in the CONTRIBUTING.md file?
