### ISSUE TITLE
mongoose multiple update

### ISSUE THREAD

**Issue by mgh64** [Automattic/mongoose#5965]
Hi...
i use mongoose verion 4.13.8 in node.js
this is my json

```javascript
> {
   "_id" : 1,
   "grades" : [
      { "grade" : 80, "mean" : 75, "std" : 6 },
      { "grade" : 85, "mean" : 90, "std" : 4 },
      { "grade" : 85, "mean" : 85, "std" : 6 }
   ]
}
{
   "_id" : 2,
   "grades" : [
      { "grade" : 90, "mean" : 75, "std" : 6 },
      { "grade" : 87, "mean" : 90, "std" : 3 },
      { "grade" : 85, "mean" : 85, "std" : 4 }
   ]
}
```

when i use this statement : 
```javascript
let result = await db.tests.update({}, {
      $set: {
        "grades.$[elem].mean": 100
      }
    }, {
      multi: true,
      arrayFilters: [{
        "elem.grade": {
          $gte: 85
        }
      }]
    })
```

return no error 
but does not change data
return => { ok: 0, n: 0, nModified: 0 }
please help me.
very thanks...

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP.

**Comment by varunjayaraman** [comment]
Can you post the surrounding code @mgh64 ? Are you not using mongoose? You seem to be using the underlying mongo driver

**Comment by mgh64** [comment]
Hello my friend.
I installed version 4.13.9 mongoos that you corrected this item
But I did not answer
My problem is mentioned in  [this link](https://github.com/Automattic/mongoose/issues/5986
) too
thank you...
