### ISSUE TITLE
mongoose.connect() no longer returns the connection created in 5.x

### ISSUE THREAD

**Issue by devinus** [Automattic/mongoose#5974]
The current version returns the created connection, while 5.x resolves to the Mongoose instance.

**Comment by vkarpov15** [comment]
I'm not sure I understand the issue, can you please clarify? There were some changes with `mongoose.connect()` in 5.0 that you can read about here: https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#promises-and-callbacks-for-mongooseconnect

**Comment by varunjayaraman** [comment]
@devinus like @vkarpov15 mentioned, those docs cover the breaking changes in mongoose 5.x. Most notably, `mongoose.connect` actually resolves to `null`, not the Mongoose instance:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5974`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

run().catch(error => console.error(error.stack));

async function run() {
  console.log(await mongoose.connect(connectionString));
}
```
