### ISSUE TITLE
Regex: Error: Can't use $options with String

### ISSUE THREAD

**Issue by steren** [Automattic/mongoose#598]
As defined in the [MongoDB documentation](http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-RegularExpressions), the following syntax :

```
find(name: { $regex : 'abc', $options: 'i' } )
```

is correct.

However, I've got the error _Can't use $options with String_

The same query works when I use directly the mongo shell.
I'm using mongoose 2.3.10 and mongo 2.0

**Comment by jwerre** [comment]
Another consideration is that Mongo supports PCRE allowing for things like negative look-behinds where javascript does not. Passing strings allows us to reconcile these differences.

**Comment by vkarpov15** [comment]
Actually this has long-since been fixed. Should work fine @jwerre

**Comment by relief-melone** [comment]
I'm having the same issue. mkpolas workaround worked for me. The only thing I'm not getting is that the

`{"$regex", "something", "$options": "i"}`

works in one script and in the other one it doesn't even though they are more or less identical.

**Comment by lineus** [comment]
@relief-melone can you craft a complete example with the query you expect to work but isn't working? You can share it here, or create a new issue, or feel free to join us on either [Slack](https://mongoosejsteam.slack.com/) or [Gitter.im](https://gitter.im/Automattic/mongoose) to chat about it.

**Comment by easyhjq** [comment]
content := param
query:=bson.M{"name " :bson.M{"$regex":content , "$options": "$i"}}

**Comment by easyhjq** [comment]
Also i find  it it doesn't work well if there are some special characters in your query,like Brackets，Quotation mark，and so on .
So use regexp.QuoteMeta(Your content) will work.

**Comment by haternesto** [comment]
The issue looks resolved here [](https://groups.google.com/g/mongoose-orm/c/rtsE40Vqz7I)
