### ISSUE TITLE
Middleware for model statics

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#5982]
https://github.com/Automattic/mongoose/issues/3298#issuecomment-356741072

```javascript
schema.static('findMinOne', function (conditions, callback) {
   return this.find(conditions, callback)
})

schema.post('findMinOne', function (data, next) {
   if (!data) {
      return next(new Error('No docs found in schema "' + schema + '"!'))
   }
   next()
})
```

**Comment by web-mi** [comment]
+1

This would be great and would make it much more extendable!

**Comment by juampi92** [comment]
I think the `findOrFail` / `findOneOrFail` makes more sense as an API.

And also, leaving this.find(condition, callback) limits the function to only two parameters (I know that it returns a chainable query, but still).
The correct way will be to

````js
schema.static('findOrFail', function () {
   return this.find.call(this, Array.prototype.slice.call(arguments));
})
````

**Comment by vkarpov15** [comment]
Good idea, this would work

```javascript
schema.static('findOrFail', function () {
   return this.find.call(this, Array.prototype.slice.call(arguments)).then(res => assert.ok(res.length > 0));
})
```

**Comment by juampi92** [comment]
@vkarpov15 not really..
Sometimes the parameters are only for inserting the query, and then we use chainable methods to specify other params, like `sort()`, `select()`, etc.

Also, the last argument might be the callback. So you shouldn't assume that `then` would always work.

http://mongoosejs.com/docs/queries.html -> Check out those examples and you'll know what I'm saying

**Comment by vkarpov15** [comment]
Ah yeah that's right, I keep on forgetting about that.

**Comment by marcuspoehls** [comment]
Do you have a working solution for `findOneOrFail or `findOrFail`?
@vkarpov15 @juampi92

**Comment by vkarpov15** [comment]
@marcuspoehls here's an alternative using [query helpers](http://thecodebarbarian.com/mongoose-custom-query-methods) that could work.

```javascript
schema.query.findOrFail = function() {
  return this.find().exec().then(res => {
    assert.ok(res.length > 0);
    return res;
  });
};
```

Then you can do `await Model.find().where('foo').eq('bar').findOrFail();` Does that work for your use case?

**Comment by marcuspoehls** [comment]
@vkarpov15 Your example fits my needs. I was thinking of a method that finds or fails for a query on a model id field.

Honestly, this is a convenience feature for an app I'm building. It's totally fine for if I do these restrictions. The query builder example is really nice.

Thank you!
