### ISSUE TITLE
E11000 duplicate key error collection: test.bookstores index: bookname_1 dup key: { : null }

### ISSUE THREAD

**Issue by binita12345** [Automattic/mongoose#5988]
I get the above mentioned error as soon as more than 1 data tries to insert into my collection.
 I am using latest version of mongoose.
node.js version --> "v6.12.3",
mongoose version --> "^4.13.9",
MongoDB version --> "^3.0.1"

**getting following error when saving another docs after one doc is saved in collection MongoDB**

{
    "error": {
        "stack": "MongoError: E11000 duplicate key error collection: test.bookstores index: bookname_1 dup key: { : null }\n    at Function.MongoError.create",
        "statusCode": 404,
        "error": "Not Found",
        "message": "E11000 duplicate key error collection: test.bookstores index: bookname_1 dup key: { : null }"
    }
}

**My code for save data in collection is here:**

    var book = new bookModel(newBook);

      book.save(function (error, result) {
        return callback(error, result);
      });

First time data is inserted and saved, but getting above error at second time when i save inserted second one doc.

> Please reply as soon as possible.

**Comment by hope-himalaya-ahuja** [comment]
Please write the solution as well to this before closing.
