### ISSUE TITLE
Mongoose querys taking so long when mongodb is down

### ISSUE THREAD

**Issue by santimendoza** [Automattic/mongoose#5991]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When mongodb is down, the querys wait a long time until throwing an error.

**What is the expected behavior?**

Is mongodb is down, it should throw an error more quickly. Or the find, findOne and other querys functions should have a maxTime or maxTimeMS option. Searching in the documentation and trying to create a plugin does not seems to work with findOne for example:

```js
schema.set('findOne', {
    maxTime: 3000,
    maxTimeMS: 3000
});
```

**Comment by varunjayaraman** [comment]
@santimendoza the docs cover this pretty well: http://mongoosejs.com/docs/connections.html

Using mongoose 4.x, you can tell the mongoose connection to not buffer commands to the db and it will fail immediately.

The following repro scripts have a `wait` function during which you can terminate the connection to mongodb to reproduce:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5991`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useMongoClient: true, bufferCommands: false, bufferMaxEntries: 0 });

  const schema = new mongoose.Schema({ name: String });
  const Model = mongoose.model('Model', schema);

  await wait();
  const doc = await Model.findOne({ name: 'test' });
}

function wait(time = 5000) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, time);
  });
}
```

If you run this, it will immediately fail on the severed connection. 

The docs also cover how to do this at the schema level: http://mongoosejs.com/docs/connections.html

Here's a repro script for the schema-level use case:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5991`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useMongoClient: true, bufferMaxEntries: 0 });

  const schema = new mongoose.Schema({ name: String }, { bufferCommands: false });
  const Model = mongoose.model('Model', schema);

  await wait();
  const doc = await Model.findOne({ name: 'test' });
}

function wait(time = 5000) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, time);
  });
}
```
