### ISSUE TITLE
Middleware pre/post remove/findOneAndRemove not called when calling Model.remove({...}).

### ISSUE THREAD

**Issue by qventura** [Automattic/mongoose#5992]
`DummyModel.remove({ ... })` doesn't call any middleware. Is that the expected behaviour? I was expecting this method to be an alias for `findOneAndRemove`.

Does it have some specific middleware that are not documented? 

Here is a gist showing the problem: https://gist.github.com/qventura/a82991fa1acea0272bd71f25f67bc75c

Resulting in:
```
Model created { _id: 5a59299a8fc021a3ab5e8343,
  requiredAttribute: 'something',
  __v: 0 }
Using instance.remove, should call the Docucment Middlewares
pre Remove 1!
post Remove 1!
Existing models []


Model created { _id: 5a59299a8fc021a3ab5e8344,
  requiredAttribute: 'something',
  __v: 0 }
Using class.remove, should call the Query Middlewares ???
Existing models []


Model created { _id: 5a59299a8fc021a3ab5e8345,
  requiredAttribute: 'something',
  __v: 0 }
Using class.findOneAndRemove, should call the Query Middlewares
pre Remove 2!
post Remove 2!
Existing models []
```

**Comment by qventura** [comment]
Just re-read the doc and found that:

>>>
Note: There is no query hook for remove(), only for documents. If you set a 'remove' hook, it will be fired when you call myDoc.remove(), not when you call MyModel.remove(). Note: The create() function fires save() hooks.

I'll close. Why is that the case though? 
What's the difference between: `Model.remove(criteria)` and `Model.findOneAndRemove(criteria)`?

**Comment by vkarpov15** [comment]
The reason for doc.remove() vs Model.remove() is that doc.remove() middleware long predates query middleware, so we would need a switch to handle whether pre('remove') applies to doc.remove() or Model.remove(). Follow #2812 for updates on that, or just use deleteOne() and deleteMany() .

remove() is a distinct operation on the mongodb server from findOneAndRemove. Most notably, remove() doesn't return the document(s) that were deleted

**Comment by nuthinking** [comment]
Can anyone point me to a working example? Can't manage to get the hook work with any permutation. Thanks!

**Comment by vkarpov15** [comment]
@nuthinking can you please explain what you're looking for a working example of?
