### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by saiichihashimoto** [Automattic/mongoose#5993]
5.0.0-rc2

**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behavior?**
Error when loading page that imports mongoose on the client side when using webpack (exactly like #5610) but NOT with react-create-app.

This line of code:

new webpack.DefinePlugin({ 'typeof window': '"object"' })

from
http://mongoosejs.com/docs/browser.html

does not appear to fix it.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using webpack with Mongoose. Also, having `resolve.extensions: ['.web.js', '.js', '.json']` in the webpack config.

**What is the expected behavior?**
App loads without error

**Please mention your node.js, mongoose and MongoDB version.**
Node: 9.30
NPM: 5.6.0

![image](https://user-images.githubusercontent.com/2819256/34901474-9a586584-f7bf-11e7-9bfd-1ef203cf03a1.png)
![image](https://user-images.githubusercontent.com/2819256/34901480-a72a0984-f7bf-11e7-9fbb-5c36fce8d3f2.png)
![image](https://user-images.githubusercontent.com/2819256/34901482-ac687610-f7bf-11e7-8c50-57ac59332549.png)

Looking through #5610 and investigating, I've discovered a few things, but none of them solve the problem.

- There is a `lib/document_provider.js` & a `lib/document_provider.web.js`. Presumably, the `.web` version is meant for the browser but webpack doesn't resolve to the [`.web` version anymore](https://webpack.js.org/configuration/resolve/#resolve-extensions) but create-web-app is still [configured to do so](https://github.com/facebookincubator/create-react-app/blob/99c14e710ffb01d1c4a1124fc3ed2172bf58afbd/packages/react-scripts/config/webpack.config.prod.js#L99) (and so am I), so maybe that's something.
- Which leads to: some files (specifically `lib/document_provider.js`, `lib/document_provider.web.js`, `lib/browser.js`) have requires with `.js` in them. This is preventing the `.web` version from being required at all.
- Regardless, looking at that stack trace, `lib/document_provider.js` eventually requires `lib/document_provider.web.js`. Even fixing the `.web, it's still a [cyclical dependency](https://nodejs.org/api/modules.html#modules_cycles), which I doubt was the intention.

**Comment by florianbepunkt** [comment]
I also get this error… it seems it's not just related to create-react-app but when used in a react webpack setup. Basically seeing this error with every react boilerplate that uses webpack dev server as well as when setting up such a setup manually.

**Comment by vkarpov15** [comment]
Yeah there are several issues with mongoose and webpack that we don't really have the expertise to fix right now. I'm going to mark this as help wanted for now. @varunjayaraman is the expert on mongoose + webpack, perhaps he has some thoughts?

**Comment by saiichihashimoto** [comment]
It *is* causing errors in webpack, but if you artificially throw an error on the same line, the stack trace will still show the cyclical dependency with `document_provider.js` so I'm not sure if this is a webpack specific issue. I'm not sure why no error is happening in the usual use cases, but is the cyclical dependency expected?

**Comment by vkarpov15** [comment]
Nope not expected. But I don't really see where the cyclical dependency comes in, I don't see how `document_provider.js` can lead to requiring in `document_provider.web.js`...

**Comment by saiichihashimoto** [comment]
`browser.js` [requires](https://github.com/Automattic/mongoose/blob/master/lib/browser.js#L3) `document_provider.js` (with the extension, so resolving to `document_provider.web.js` is impossible)
`document_provider.js` [requires](https://github.com/Automattic/mongoose/blob/master/lib/document_provider.js#L8) `document.js` (again, with the extension)
`document.js` [requires](https://github.com/Automattic/mongoose/blob/master/lib/document.js#L10) `schema`

... lots of requires in that stack trace above leads to ...

`types/embedded.js` [requires](https://github.com/Automattic/mongoose/blob/master/lib/types/embedded.js#L7) `document_provider` (no extension, so it COULD resolve to `.web`)
`document_provider.js` (or `document_provider.web.js`, they both do it) [requires](https://github.com/Automattic/mongoose/blob/master/lib/document_provider.web.js#L8) `browserDocument.js`
`browserDocument.js` [requires](https://github.com/Automattic/mongoose/blob/master/lib/browserDocument.js#L5) `document`.
`browserDocument.js` [tries to use](https://github.com/Automattic/mongoose/blob/master/lib/browserDocument.js#L95) `document` and throws the error.


Basically: `document_provider.js` requires `document.js` (ultimately) requires `document_provider.web.js` requires `browserDocument.js` requires `document.js` (which hasn't resolved yet) so it's null.

Since `types/embedded` requires `document_provider.js` & `browser` requires `document_provider`, it gets required twice. I'm not sure why there's no cyclical issues in mongoose currently, but these webpack builds aren't throwing the error there because having the `.js` makes it so that `document_provider.js` doesn't end up requiring itself, but rather brings in both versions to the bundle.

I'd:

- Remove the `.js` from every require that has it. (there's 3, I think) Makes it so that either the `.web` version is being used or not being used, but never both.
- I'm guessing that `document_provider.js` is for *not* the web and `document_provider.js` is for the web. In that case, I'd remove `document_provider.js`'s dependency on `browserDocument.js` at all. Either tell people they need webpack to prioritize `.web` extensions or have `browser.js` require `document_provider.web` directly so that you can avoid the other path entirely.
- Either way, I'm not sure why mongoose isn't creating a cyclical dependency, already. `document_provider` eventually requires `types/embedded` requires `document_provider`.

**Comment by varunjayaraman** [comment]
@saiichihashimoto trying to follow the logic here, although I think you may be onto something here:

`types/embedded` is dynamically required in in `lib/document.js` here: https://github.com/Automattic/mongoose/blob/master/lib/document.js#L858

and here: https://github.com/Automattic/mongoose/blob/master/lib/document.js#L1928

Where i lose you is how eventually `document_provider.web.js` eventually gets required here

**Comment by saiichihashimoto** [comment]
Well, `document_provider` gets required from `embedded` [here](https://github.com/Automattic/mongoose/blob/master/lib/types/embedded.js#L7). If you set the extensions in webpack to include `.web.js`, it'll require `document_provider.web.js`. This used to [be the default](https://github.com/webpack/docs/wiki/configuration#resolveextensions), though I don't think it is anymore. I think a lot of webpack projects have that set since it's really useful to have webpack specific files.

`browser` will always require `document_provider.js` (not `document_provider.web.js`) because the require [includes the extension](https://github.com/Automattic/mongoose/blob/master/lib/browser.js#L3).

Either way, some version of `document_provider` eventually requires `embed`, which requires `document_provider`.

**Comment by vkarpov15** [comment]
Should be fixed with #5842 and https://github.com/Automattic/mongoose/commit/31b84f042d5786cbb674daa9974155f5af9e8b62

**Comment by florianbepunkt** [comment]
@vkarpov15 The error is gone, but when importing mongoose into an react app it gives me an error on connecting: `mongoose.connect is not a function`

Mongoose is imported however the connect functionality seems unavailable on the mongoose object.

It would be nice to use mongoose on the client side. We build a lot of internal only apps where using mongoose on the client side would reduce the overhead that comes with an extra express server.

**Comment by vkarpov15** [comment]
@florianbepunkt mongoose's browser side component is [currently limited to just schemas and documents](http://mongoosejs.com/docs/4.x/docs/browser.html). There's no `save()`, no `connect()`, etc. The only use case that mongoose currently supports in the browser is validating an object against a schema. Connecting directly to mongodb in the browser is not something we will support in the foreseeable future because the mongodb driver doesn't support that.

**Comment by saiichihashimoto** [comment]
Not to mention, there's no reliable secure way to hold authentication to the db in the client anyhow. Unless you're making a mongodb "shell" in the browser for users to connect to databases, I can't imagine a use case where direct access is a good idea.

**Comment by vkarpov15** [comment]
@saiichihashimoto that's a fair point. I imagine @florianbepunkt is building something like that where anyone using the service should have admin access to the database already. Its a valid use case, but the task of getting a mongodb driver that works in the browser is a very troublesome one. If mongoose were to support it, we would probably have to do it through [a mongodb REST API client](https://docs.mongodb.com/ecosystem/tools/http-interfaces/) anyway

**Comment by saiichihashimoto** [comment]
Oh, gotcha. That's definitely an edge case. Still, if mongoose did move to using [adapters](https://github.com/Automattic/mongoose/issues/6002#issuecomment-358804474), that wouldn't be super difficult to implement.
