### ISSUE TITLE
Typescript Mongoose schema not working

### ISSUE THREAD

**Issue by ciiidi** [Automattic/mongoose#5995]
Hi, I can't use the schema of mongoose, I don't know what I am missing.
**My model is:**

![image](https://user-images.githubusercontent.com/19199918/34907815-6e9e8bca-f8bf-11e7-874b-d9381d5015c7.png)

**and I have repository or data access like this**

![image](https://user-images.githubusercontent.com/19199918/34907822-8863bf94-f8bf-11e7-9660-3ee0dd23a26e.png)

**and I tried to simulate it using this code:**
![image](https://user-images.githubusercontent.com/19199918/34907831-9ca46b02-f8bf-11e7-849a-9d6be3dd36cd.png)

**Result is no logs and also it doesn't create a database.**

**Comment by varunjayaraman** [comment]
That should be working. Are you sure `DatabaseService.connect()` is working properly / not erroring?

**Comment by ciiidi** [comment]
My database service connect function is:
mongoose.createConnection('mongodb://.../databasename');
I am not sure why it didn't work, but when i try the default connection of mongoose it went ok.

> Also, Typescript is compile-time, are there any typescript errors in the transpilation process? Can you verify the transpiled code seems correct?

yes the transpilation process is ok
