### ISSUE TITLE
Documentation of the "lean" option

### ISSUE THREAD

**Issue by aguyinmontreal** [Automattic/mongoose#5996]
I need some clarifications. I think there is some confusion with the "lean" option in the Mongoose documentation.

Under `Query#setOptions(options)`, it says: 

> The following options are only for find(), findOne(), findById(), and findOneAndUpdate():
> - lean

First, why does it include `findOneAndUpdate` but not `findByIdAndUpdate` ?

Second, why can I then find the `lean` option in the `Model.geoSearch` option list?

Third, why is the `lean` option not in the `Model.findOneAndUpdate` options list?

Thank you in advance!

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in the next release :+1:

**Comment by vkarpov15** [comment]
On second thought, also need to apply this to the 4.x docs

**Comment by aguyinmontreal** [comment]
Alright!  So what is the truth?  Which ones are compatible with the `lean` option? Thanks!
