### ISSUE TITLE
findById always reject in Promise

### ISSUE THREAD

**Issue by kamontat** [Automattic/mongoose#6000]
**Do you want to request a *feature* or report a *bug*?**
- report a *bug*

**What is the current behavior?**
1. run
```js
Model.findById(req.params.fid)
        .then(model => {
            if (!model) {
                return res.status(404).send({
                    complete: false,
                    message: "Model Not Found",
                });
            }
            return res.status(200).send({"complete": true});
        })
        .catch(error => {
            res.status(400).send(error);
        });
```

**What is the expected behavior?**
When I try with callback, It's work correctly. so I notice that having some bug with `promise`

**Please mention your node.js, mongoose and MongoDB version.**
node --version: `v9.3.0`
mongo --version: 
```
MongoDB shell version v3.6.2
git version: 489d177dbd0f0420a8ca04d39fd78d0a2c539420
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```
mongoose: `4.13.9`

PS: I use `bluebird` as promise library to avoid `DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated`

**Comment by kamontat** [comment]
The status always return `400` when use `promise`, 
Otherwise status become 200 if use `callback`

**Comment by vkarpov15** [comment]
I don't understand your issue. Can you show how you're doing "try with callback"?

**Comment by kamontat** [comment]
Sorry, I already fix this. I forgot to run `exec()` for executing query
