### ISSUE TITLE
how unique is _id  generated by mongoose for sub-document?

### ISSUE THREAD

**Issue by artofspeed** [Automattic/mongoose#6001]
Using this schema
```
mongoose.Schema({
    world: String,
    color: [{ name: String }]
});
```
Gives me document that have sub-documents containing _id fields.

```
{ _id: 'a9ec8475bf0d285e10ca8d42'
  world: 'matrix', 
  color: [
    { name: 'blue',  _id: '4a8c0e12135fa32e13db9ce9' },
    { name: 'red',   _id: '4a8c0a62254cd32e13db4ad8' },
    { name: 'white', _id: '4a8c04e2687ea32e13db1da7' }
]
```
Since mongodb doesn't generate _id for sub-fields by default, I want to know how unique are they, are they unique across all documents, or only across the nested level it is in? Thanks!

**Comment by vkarpov15** [comment]
It's the same id generation logic as the top-level `_id`, so it should be unique across all subdocuments with [high probability](https://www.mongodb.com/blog/post/generating-globally-unique-identifiers-for-use-with-mongodb). You can enforce it by creating a unique index on `color._id`: http://mongoosejs.com/docs/guide.html#indexes.
