### ISSUE TITLE
Retryable Writes

### ISSUE THREAD

**Issue by yuricamara** [Automattic/mongoose#6003]
Hi,

[MongoDB 3.6 introduced Retryable Writes feature](https://github.com/mongodb/specifications/blob/master/source/retryable-writes/retryable-writes.rst)

I would like to know if It is already possible to use this feature with Mongoose or when it will be.

Thanks in advance!

**Comment by vkarpov15** [comment]
You should be able to access them in mongoose >= 5.0.0-rc2 by specifying the `retryWrites` option in your connection string:

```javascript
mongoose.connect('mongodb://localhost:27017/test?retryWrites=true');
```

See https://emptysqua.re/blog/driver-features-for-mongodb-3-6/#retryable-writes for more info

**Comment by yuricamara** [comment]
Nice @vkarpov15 ! Thank you
