### ISSUE TITLE
Collection Name some times refers plurals and some time sigular. 

### ISSUE THREAD

**Issue by kohakade** [Automattic/mongoose#6005]
We have a model named Company in the codebase. We have two instances of a database.
1. Dev
1. Test

We deployed the same codebase for both the environment. We never checked collection names in the database. But recently we face an issue when Company model returns no records. Then we found out, Development environment database have collection name `companies` and test environment database have collection name `company`. But now test server checks for collection `companies`. Resulting in no records return for find query. 

node: v8.9.3
Mongo: 3.4
├─┬ mongoose@4.13.4
│ ├─┬ mongodb@2.2.33
│ │ ├─┬ mongodb-core@2.1.17

We are going to use Mongoose in Production. If the same thing happens when we go into Production then it is difficult to notice. Also Please let us know is there any way we get notified of such changes.

**Comment by vkarpov15** [comment]
So mongoose should use the same collection names regardless of environment, we don't switch based on `NODE_ENV` or anything like that. Can you show me how you're declaring your models?

**Comment by kohakade** [comment]
Thanks!
The NODE_ENV doesn't affect it. If it was then it still should be. 

This is how we Define model
company.js
```
module.exports = function(Schema) {
  const Company = new Schema({
    name: {
      required: true,
      type: String,
      comment: 'Name of the company.'
    },
    address: {
      type: String
    },
    brand: {
      type: String
    },
    createdBy: {
      required: true,
      type: String
    },
    updatedBy: {
      required: true,
      type: String
    },
    deletedAt: {
      type: Date,
      default: null
    }
  {
    timestamps: true
  });

  return Company;
};
```

And We register those model from directory
index.js
```
const fs = require('fs');
const path = require('path');
const config = require('.../config').storage['companies'];
const mongoose = require('mongoose');
const basename = path.basename(module.filename);
mongoose.Promise = global.Promise;

const dbConnection = mongoose.createConnection(config, { useMongoClient: true });

const db = {};

fs
  .readdirSync(__dirname)
  .filter((file) => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach((file) => {
    const model = require(path.join(__dirname, file))(mongoose.Schema);
    const modelName = file.substr(0, file.length - 3);
    db[modelName] = dbConnection.model(modelName, model);
  });

module.exports = db;
```

**Comment by vkarpov15** [comment]
That's strange, I don't see any reason why you should have different collection names. Do you know how the data got into the 'company' collection on your test server? Did that go through mongoose or could it have been inserted some other way?

**Comment by kohakade** [comment]
Hello Valeri,

The documents inserted in `company` collection using Mongoose only. The same mongoose was retrieving data from `company` collection. But since 4 -5 days mongoose is retrieving/inserting data to/from `companies` collection. Which results we are not able to retrieve old data. We were going to use same mongo-Mongoose tack in Production. If anything happens such like in Production we ended up losing data. As it is very difficult to track. Please let us know, is something missing?

Thank You.

**Comment by vkarpov15** [comment]
Did you use mongoose 5.0.0-rc0? We unfortunately had a bug with that release that had mongoose writing to the wrong collection by default, and that's the only other possible explanation I can think of.

**Comment by varunjayaraman** [comment]
@kohakade can you confirm whether or not you were using mongoose 5.0.0-rc0 ? Going to mark this as stale for now
