### ISSUE TITLE
unable to connect to mongoose database

### ISSUE THREAD

**Issue by doriandun** [Automattic/mongoose#6006]
Bug

syntax error: Invalid regular expression /0|[0-9]\d*/: Range out of order in character class

the following lines in semver.js stops mongoose from connecting to a new database 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
connection to database, 

Fixed by omitting following lines from semver.js file 

line 203 and 204

//re[COMPARATORTRIM] = new RegExp(src[COMPARATORTRIM], 'g');

//nodevar comparatorTrimReplace = '$a$2$3';

and line 232

//  re[i] = new RegExp(src[i]);

**Please mention your node.js, mongoose and MongoDB version.**
node js ver 8.93  "mongoose": "^5.0.0-rc2",

![mongo db error](https://user-images.githubusercontent.com/11408411/35049293-685578e8-fb97-11e7-90aa-ec73d3ed597a.png)

**Comment by vkarpov15** [comment]
I don't see anything in your stack trace that indicates this is a mongoose issue. Can you provide some more substantial code samples please?

**Comment by varunjayaraman** [comment]
agreed, @doriandun this seems purely a user-error on using regexes. Can you please post a full code sample?

**Comment by doriandun** [comment]
i had no regex setup, basically a schema and model, thats it, when i ran nodemon index.js the error illustrated in the picture would come up, after deliberating for a while decided to remove line 203,204 from semver.js file, another error message prompted my to take a look at line 232, i removed it and the result was mongoose  connection was initiated, i no longer have the code, as i decided to just use mongoclient instead
