### ISSUE TITLE
New docs: code examples are not being formatted

### ISSUE THREAD

**Issue by jvitoroc** [Automattic/mongoose#6008]
http://mongoosejs.com/docs/queries.html
![image](https://user-images.githubusercontent.com/25753747/35075663-9556139a-fbdb-11e7-9aa3-7e057c7fd44c.png)

**Comment by vkarpov15** [comment]
Thanks for pointing this out, looks like we missed a spot when refactoring our docs build. Fix will be deployed when 5.0.1 is released, should be within the next 48 hours
