### ISSUE TITLE
Calling populate on embedded doc of embedded doc

### ISSUE THREAD

**Issue by dmmalam** [Automattic/mongoose#601]
Hey, 
I have the following schemas ( simplified for issue)

User = new Schema 
  login:String

A = new Schema
 emb: [B]
 comments: [Comments]

//and following embedded schemas

B = new Schema
  comments: [Comments]

Comments = new Schema
   creator:
    type: ObjectId
    ref: 'User'
  message: String

Now while populate works on A
eg A.find().populate('comments.creator')

it doesn't work on the double nested embedded doc
eg A.find().populate('emb.comments.creator')

Any ideas?

**Comment by joaom182** [comment]
Not working for me.

models/missionParticipation.js
```
var deepPopulate = require('mongoose-deep-populate');
var mongoose = require('mongoose');
var Types = mongoose.Schema.Types;

var missionParticipationSchema = new mongoose.Schema({
        user: {
            type: String,
            default: ''
        },
        mission: {
            type: Types.ObjectId,
            ref: 'Mission'
        },
        images: [{
            type: Types.ObjectId,
            ref: 'Image'
        }]
    }, {
        toJSON: {
            getters: true,
            virtuals: true
        },
        toObject: {
            getters: true,
            virtuals: true
        }
    });

    missionParticipationSchema.plugin(deepPopulate, {
        whitelist: [
            'images',
            'mission',
            'mission.images.poster',
            'mission.images.banner'
        ]
    });

var MissionParticipation = mongoose.model('MissionParticipation', missionParticipationSchema);

module.exports = MissionParticipation;
```

services/missionParticipationService.js
```
MissionParticipation.find({user: userID}).deepPopulate('mission.images.poster mission.images.banner').exec(function (err, missionParticipationsDocs) {
    // do the magic.
});
```

And i get this error on console

```
TypeError: Object #<Query> has no method 'deepPopulate'
```

**Comment by Swissbite** [comment]
@joaom182 
I did not yet use deepPopulate, but recording to the docs on http://npm.taobao.org/package/mongoose-deep-populate I would assume that the correct call should be:

```javascript
MissionParticipation.find({user: userID}, function (err, participations) {
  MissionParticipation.deepPopulate(participations, 'mission.images.poster mission.images.banner', function(err) {
    if (err) {
      //handle it
      return void 0;
    }
    //do your magic stuff. with participations, which are populated in place in the examples 
  })
})
```

Regards

**Comment by joaom182** [comment]
I found another way, but I'm concerned about the performance, I try to make a comparison.

The other way uses the [async](https://github.com/caolan/async) module

```javascript
MissionParticipation.find({
   user: userID
}).populate('mission').exec(function (err, missionParticipationsDocs) {
   if (err)
      return; // handle error

   async.forEach(missionParticipationsDocs, function (mp, callback) {
      mp.mission.populate('images.poster', 'images.banner', 'prize', function (err, result) {
         callback();
      });
   }, function (err) {
      // forEach async completed
      if(err)
         return; // handle error
      resolve(missionParticipationsDocs);
   });
});
```

**Comment by buunguyen** [comment]
@joaom182 you're a bit too fast :). Although I added code to bring `deepPopulate` to `Query`, I delayed pushing a new version on NPM so that I could test a bit more. 

I've just pushed the new version (0.0.7). So this syntax you used should work after you update the dependency:

```javascript
MissionParticipation
  .find({user: userID})
  .deepPopulate('mission.images.poster mission.images.banner')
  .exec(cb);
```

**Comment by joaom182** [comment]
@buunguyen Awesome!

**Comment by vkarpov15** [comment]
Can y'all open future issues in the [mongoose-deep-populate repo](https://github.com/buunguyen/mongoose-deep-populate) please? Makes everyone's life a little easier :)

**Comment by andersLindqvist** [comment]
@buunguyen Awesome! The best thing that happened to my project and You made my day! Thanks!
