### ISSUE TITLE
Mongoose promise rejection inside router don't raise to app error handler

### ISSUE THREAD

**Issue by Iworb** [Automattic/mongoose#6010]
Node version: v8.9.4
Mongoose version: v5.0.0

I have a server app like this:
```
const express = require('express')
const app = express()
const router = require('express').Router()
...
route.post('/dogs', (req, res, next) => {
  const dog = new Dog() // it defined in real app
  dog.validate() // error happens here
    .then(() => {
      return res.status(201)
    })
    // [1]
})
...
app.use('/api/v1', router)
app.use(notFoundErrorHandler)
app.use(globalErrorHandler)

function notFoundErrorHandler (req, res, next) {
  res.status(404)
  res.send({error: 'Not found'})
}

function globalErrorHandler (err, req, res, next) {
  if (err) {
    res.status(err.status || 500)
    res.json({error: err.message || err})
  }
}
```
If there an error occures during validation/saving/etc it rejecting promise and I've got "UnhandledPromiseRejectionWarning: Unhandled promise rejection" in my console.
Normally, throwing any error handled in `globalErrorHandler `, but not these ones.
If I catch and rethrow this (`.catch(err => { return next(err) }) // [1]`) it works as expected.
Is it usual behaviour for promise-based methods?

**Comment by rafalt** [comment]
const **dog** = new Dog() // it defined in real app
  **bog**.validate() // error happens here


Is not a problem with name dog vs bog??

**Comment by Iworb** [comment]
No, just an misstype

**Comment by vkarpov15** [comment]
Do this instead:

```javascript
dog.validate() // error happens here
    .then(() => {
      return res.status(201)
    })
    .catch(next)
```

You need to make sure to call `next()` to kick off the next middleware in the chain in Express, including [error handling middleware](http://thecodebarbarian.com/80-20-guide-to-express-error-handling)
