### ISSUE TITLE
Breaking change in doc.validate()

### ISSUE THREAD

**Issue by jozsi** [Automattic/mongoose#6014]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the expected behavior?**
Previously, doc.validate() was returning undefined as the first parameter of the callback function (or `then`) if no validation errors happened.

**What is the current behavior?**
doc.validate() now returns the document itself if validation succeeded.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
  it('should be valid', async () => {
    const user = new User(DATA);
    const errors = await user.validate();
    expect(errors).toBeUndefined();  // Mongoose 4: undefined; Mongoose 5: the document itself
  });
```

**Please mention your node.js, mongoose and MongoDB version.**
- node v9.2.0
- mongoose 5.0.0
- MongoDB 3.6.1

**Comment by vkarpov15** [comment]
Thanks for reporting, fixed in master and fix will be in 5.0.1 :+1:
