### ISSUE TITLE
Will mongoose have it's own unique validator?

### ISSUE THREAD

**Issue by jvitoroc** [Automattic/mongoose#6015]
I know there is this package: [mongoose-unique-validator](https://www.npmjs.com/package/mongoose-unique-validator)
But I wonder why mongoose do not implement something like this?

**Comment by vkarpov15** [comment]
We have the `unique` option: http://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator but that is not a validator. The MongoDB server already has support for unique indexes, and implementing a validator that enforces inter-document constraints comes with [caveats](https://www.npmjs.com/package/mongoose-unique-validator#caveats)
