### ISSUE TITLE
I don't know if there is a companion in Chinese, but I really want to find a solution for my confusion.Thanks!

### ISSUE THREAD

**Issue by jcindex** [Automattic/mongoose#6017]
当我使用mongoose.model("Admin", adminSchema);新建model进行findOne查询，却读取不到mongodb中名叫'admins'的集合中的数据，反而在数据库中生成了一个新集合'Admin',但在我其他项目中的配置就能正常使用admins中的数据。怎么回事？

**Comment by jcindex** [comment]
The version of the mongoose I used is 5.0.0-rc0.

**Comment by vkarpov15** [comment]
Based on what I got from google translate, you should upgrade to 5.0.0-rc1, this was a bug in 5.0.0-rc0.
