### ISSUE TITLE
Migrating mpromise plugin to Mongoose 5

### ISSUE THREAD

**Issue by xlinulx** [Automattic/mongoose#6018]
I need help porting this plugin to Mongoose 5
[https://github.com/janez89/mongoose-materialized](https://github.com/janez89/mongoose-materialized)

The plugin is probably not working due to mpromise being deprecated on Mongoose 5, I'm getting 'promise resolver undefined is not a function' while running any method.

![image](https://user-images.githubusercontent.com/6248689/35184964-270788ce-fdca-11e7-976e-21fc414e57d2.png)

![image](https://user-images.githubusercontent.com/6248689/35184970-3fdbca4a-fdca-11e7-96cc-0796b99afb4a.png)

However when I try replacing the mongoose.Promise, I can't figure out how to plug in the new promise resolver, I really have no clue.

**Comment by vkarpov15** [comment]
So the new `mongoose.Promise` is always just a [plain old ES6 promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), see [this article for some more details on native promises in mongoose 5](http://thecodebarbarian.com/introducing-mongoose-5.html#native-promises-by-default)

Here's a quick sketch of how you'd switch over. Here's the function as implemented:

```javascript
    schema.static('Remove', function (conditions, callback) {
        if ('function' === typeof conditions) {
            callback = conditions;
            conditions = {};
        }

        var self = this;
        var promise = new mongoose.Promise;
        if (typeof callback === 'function')
            promise.addBack(callback);

        self.find(conditions).exec(function (err, docs) {
            async.mapLimit(docs, options.mapLimit, function (doc, cbNext) {
                doc.remove(function (err) {
                    cbNext(err, null);
                });
            }, function (err, res) {
                if (err)
                    return promise.error(err);
                promise.complete();
            });
        });
        return promise;
    });
```

Here's the simplest way to refactor it to use ES6 promises:

```javascript
    schema.static('Remove', function (conditions, callback) {
        if ('function' === typeof conditions) {
            callback = conditions;
            conditions = {};
        }

        var self = this;
        return new mongoose.Promise((resolve, reject) => {
          self.find(conditions).exec(function (err, docs) {
            async.mapLimit(docs, options.mapLimit, function (doc, cbNext) {
                doc.remove(function (err) {
                    cbNext(err, null);
                });
            }, function (err, res) {
                if (err) {
                  callback && callback(err);
                  return reject(err);
                }
                callback && callback(null);
                return resolve();
            });
          });
        });
    });
```

This refactor would **not** be compatible with mongoose 4.x. There is a way to do it with promise chaining that would work in both mongoose 4 and mongoose 5 but that will take more work.

**Comment by vkarpov15** [comment]
Let me know if you have any more questions :+1: I'm happy to help in any way I can

**Comment by xlinulx** [comment]
@vkarpov15 Thank you Valeri, I'm so grateful.
