### ISSUE TITLE
Express, using Mongoose, connect to MongoDb with authentication

### ISSUE THREAD

**Issue by alu0100502114** [Automattic/mongoose#6023]
As my  mongoldb needs authentication, I cannot use a singleton, as stated everywhere, to make a connection, instead I have to use a middleware to get saved username and password from session and use it to establish a new connection url.

So, every time I make a request to express, a connection is established, data extracted from mongodb and connection closed.

I have read, and I agree with it, that establishing a connection is expensive but I do not find a better way to make all this.

Is there a better way to use mongoose with authenticated mongodb?

Node v8.9.3
Mongoose 5.0.0
MongoDb 3.6.2

**Comment by vkarpov15** [comment]
Can you show me some code samples? It sounds like you have separate auth credentials to the mongodb server for every user in your database?

**Comment by alu0100502114** [comment]
You are right!
Every user has their own credentials to access DB.
My solution has been to create a Superuser to connect to DB, so far.
This way Expressjs connects as it starts working and from there, every user is validated using Passport and, depending on their role, the given menu they see is different from the other users.
This way I have a fast and permanent connection to DB and every user only delays his access once as they login using Express.

**Comment by varunjayaraman** [comment]
Why did you choose to do it this way versus creating separate connections with certain roles?

**Comment by alu0100502114** [comment]
I suppose you tell me to start express and, instead of creating one connection alone as I have, create one connection for every role I have and use one or the other depending on every user...
I think result is the same and I have only one connection versus one for every role.
Remember that given menu depends on user role.
I agree it would be better if connection used would depend on every user role. This way I could control user access by role and not only by menu, but I would have to control a pool of connections... or you tell me to create one on every user request?

**Comment by vkarpov15** [comment]
I'd challenge you to think why you need a separate user in the database for every user in your system. Generally, you decouple these two concepts, so your application is always logged in to the database as a superuser, and then your application uses passport middleware and interacts with a 'users' collection in the database to determine roles. MongoDB auth is not meant to be a tool for handling user-facing wuth with passport
