### ISSUE TITLE
.collection.initializeUnorderedBulkOp() no longer working

### ISSUE THREAD

**Issue by zeg-io** [Automattic/mongoose#6025]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Model.collection.initializeUnorderedBulkOp() returns undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const report = db.mongoose.model('Report')
const bulk = report.collection.initializeUnorderedBulkOp()
```

**What is the expected behavior?**
I'd expect the bulk object to be returned.

**Please mention your node.js, mongoose and MongoDB version.**
node 8.2.1
mongoose 5.0.0
MongoDB 3.4

**Comment by vkarpov15** [comment]
Below script works for me in 5.0.0:

```javascript
const mongoose = require('mongoose');

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  await mongoose.connection.dropDatabase();

  const report = mongoose.model('Report', new mongoose.Schema({}));
  const bulk = report.collection.initializeUnorderedBulkOp();
  console.log(!!bulk);
}
```

Can you modify it to reproduce your issue?

**Comment by abhishekvaid** [comment]
I'm having the same issue.

**Comment by varunjayaraman** [comment]
@abhishekvaid and @zeg-io can you try running @vkarpov15 's script and see what your results are?

**Comment by gilles-yvetot** [comment]
I don't have the issue when I execute @vkarpov15 's code but I still have the same issue as long as I import my model

**Comment by kennu** [comment]
I witnessed the same problem when I connect() to the database, but don't wait for the connection promise to resolve before calling initializeUnorderedBulkOp().

**Comment by vkarpov15** [comment]
@kennu unfortunately that's what you currently have to do if you want to use `initializeUnorderedBulkOp()`.  I would recommend you just use [`BulkWrite()`](http://mongoosejs.com/docs/api.html#bulkwrite_bulkWrite) instead
