### ISSUE TITLE
Virtual Populate with no related documents result in null values

### ISSUE THREAD

**Issue by senser1** [Automattic/mongoose#6026]
With Mongoose 4.13.7 and 5.0.1 using virtual populate I'm getting null values back if there are no corresponding documents to popluate. I think that is a bug. 

For instance, I have a TicketSchema and an AccountSchema. The TicketSchema has a virtual type refering to the Account model based on a property called 'accountID'.

Account schema with accountID:

```
const AccountSchema: mongoose.Schema = new mongoose.Schema({
    accountName: String,
    accountID: { type: Number, index: { unique: true }, required: true },
});
```

TicketSchema with a virtual populate type to Account and toJSON property set to output virtuals in JSON:

```
TicketSchema.virtual('account', {
    ref: 'Account',
    localField: 'accountID',
    foreignField: 'accountID',
    justOne: true
});

TicketSchema.set('toJSON', { virtuals: true });
```

I get the ticket and populate account like this (ES6 async/await syntax):

`const ticket = await Ticket.findOne({ticketID: 1}).populate('account')`;  

If there is a corresponding account I get the following result back:

```
{ 
  ticketID: 1,
  account: { 
    accountID: 2
  }
}
```

If there is no corresponding account, I get back:

```
{ 
  ticketID: 1,
  account: null
```

**Comment by vkarpov15** [comment]
This behavior is by design and we think it makes sense. If there's no matching document, setting the virtual to `null` seems like the right thing to do because [`null` means 'intentional absence of a value' in the ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-null-value). What alternative would you suggest?

**Comment by senser1** [comment]
@vkarpov15, thanks, makes sense I guess. 

I think I got set to the mindset something was wrong by finding other related issues with virtual populate and null values (like ([https://github.com/Automattic/mongoose/issues/4278](https://github.com/Automattic/mongoose/issues/4278)) but that seems to describe a different scenario. 

Can be closed now.
