### ISSUE TITLE
Model.find() does not cast to correct schema with discrimination for single nested document

### ISSUE THREAD

**Issue by williamdang** [Automattic/mongoose#6027]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
The `Model.find()` does not correctly parse discriminated single nested document.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is my test script:

    const Mongoose = require('mongoose');
    const Schema = Mongoose.Schema;
    const expect = require('expect.js');
    
    describe('Mongoose', function () {
      Mongoose.Promise = global.Promise;
      Mongoose.set('debug', true);
      
      const ownerSchema = new Schema({
        _id: false,
      }, {
        discriminatorKey: 'type',
      });
      
      const userOwnerSchema = new Schema({
        id: {type: Schema.Types.ObjectId, required: true},
      });
      
      const tagOwnerSchema = new Schema({
        id: {type: String, required: true},
      });
      
      const activitySchema = new Schema({
        owner: {type: ownerSchema, required: true},
      });
      
      activitySchema.path('owner').discriminator('user', userOwnerSchema);
      activitySchema.path('owner').discriminator('tag', tagOwnerSchema);
      
      const Activity = Mongoose.model('Activity', activitySchema);
      
      before(async function () {
        await Mongoose.connect('mongodb://localhost/test', {useMongoClient: true});
      });
      
      after(async function () {
      });
      
      describe('insertMany()', function () {
        it('should save without error', async function () {
          const newActivity = await Activity.insertMany([
            {
              owner: {
                id  : '5a042f742a91c1db447534d5',
                type: 'user',
              },
            },
            {
              owner: {
                id  : 'asdf',
                type: 'tag',
              },
            },
          ]);
          
          expect(newActivity.length).to.be(2);
        });
      });
      
      describe('find()', function () {
        it('should be parse with correct schema', async function () {
          const activity = await Activity.find({
              owner: {
                id  : '5a042f742a91c1db447534d5',
                type: 'user',
              },
            })
            .exec();
          
          expect(activity.length).to.be(1);
        });
      });
    });

Running above script produces these errors:

    to String failed for value "user" at path "type"
      at CastError (node_modules/mongoose/lib/error/cast.js:27:11)
      at SingleNested.$set (node_modules/mongoose/lib/document.js:773:7)
      at SingleNested._handleI

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
I am using the latest Mongoose.

**Comment by varunjayaraman** [comment]
I've tried running your script and I don't get a syntax error. The test fails but there is no syntax error and the failure is based on the assertion

**Comment by williamdang** [comment]
I'm sorry. After upgrading to version 5, no errors were thrown. However, the bug is still persisted.
The assertion fails because the query was wrong.
If you take a look at the Mongoose log:

    Mongoose: activities.find({ owner: { type: 'user' } }, { fields: {} })

However, in the test, the query should be:

    Activity.find({
          owner: {
            id  : '5a042f742a91c1db447534d5',
            type: 'user',
          },
        })
        .exec();

**Comment by varunjayaraman** [comment]
you're right, the test shouldnt be failing, its producing an incorrect query:

```javascript
const Mongoose = require('mongoose');
const Schema = Mongoose.Schema;
const assert = require('assert');

Mongoose.set('debug', true);

describe('Mongoose', function () {
  Mongoose.Promise = global.Promise;
  Mongoose.set('debug', true);
  
  const ownerSchema = new Schema({
    _id: false,
  }, {
    discriminatorKey: 'type',
  });
  
  const userOwnerSchema = new Schema({
    id: {type: Schema.Types.ObjectId, required: true},
  });
  
  const tagOwnerSchema = new Schema({
    id: {type: String, required: true},
  });
  
  const activitySchema = new Schema({
    owner: {type: ownerSchema, required: true},
  });
  
  activitySchema.path('owner').discriminator('user', userOwnerSchema);
  activitySchema.path('owner').discriminator('tag', tagOwnerSchema);
  
  const Activity = Mongoose.model('Activity', activitySchema);
  
  before(async function () {
    await Mongoose.connect('mongodb://localhost/gh-6027');
    await Activity.remove({});
  });
  
  after(async function () {
  });
  
  describe('insertMany()', function () {
    it('should save without error', async function () {
      const newActivity = await Activity.insertMany([
        {
          owner: {
            id  : '5a042f742a91c1db447534d5',
            type: 'user',
          },
        },
        {
          owner: {
            id  : 'asdf',
            type: 'tag',
          },
        },
      ]);
      
      assert.equal(newActivity.length, 2);
    });
  });
  
  describe('find()', function () {
    it('should be parse with correct schema', async function () {
      console.log(await Activity.count()) // 2, as it should be
      console.log(await Activity.find({ owner: { type: 'user' } })); // this should not be 0
      const activity = await Activity.find({
          owner: {
            id  : '5a042f742a91c1db447534d5',
            type: 'user',
          },
        }, 'owner');
      
      assert.equal(activity.length, 1);
    });
  });
});
```

The mongoose logs show that the query:

```javascript
Activity.find({
          owner: {
            id  : '5a042f742a91c1db447534d5',
            type: 'user',
          },
        })
        .exec();
```

is being translated by mongoose to

```javascript
activities.find({ owner: { type: 'user' } }, { fields: {} })
```

**Comment by vkarpov15** [comment]
Similar to #5841 . Working on a fix.

**Comment by williamdang** [comment]
Is there any workaround? Because the `strict` one does not work.

**Comment by vkarpov15** [comment]
@williamdang only current workaround that I can think of is to bypass mongoose's casting

```javascript
const activity = await Activity.collection.find({
          owner: {
            id  : new mongoose.Types.ObjectId('5a042f742a91c1db447534d5'),
            type: 'user',
          },
        })
```
