### ISSUE TITLE
Failed `.connect()` hangs Node for 30 seconds

### ISSUE THREAD

**Issue by franksrevenge** [Automattic/mongoose#6028]
Tested on **5.0.1** and **Node 8.9.4**

```js
const mongoose = require( 'mongoose' );
const m = new mongoose.Mongoose();

m.connect( 'mongodb://thisdoesntexist:27017' )
  .then(
    () => { console.log( 'Success!' ); },
    ( err ) => { console.error( err ); }
  );
```

Results:
1. Promise is rejected pretty much immediately. (As expected)
1. Node.js process hangs (=does not exit) for 30 seconds. (Not expected)

Intuitive expectation would be that connection process comes to an end when the `.connect()` promise is rejected. Seems like something keeps going on in the background after that, though.

**Comment by varunjayaraman** [comment]
I'm not able to reproduce this. If i run your script it errors immediately for me.

**Comment by varunjayaraman** [comment]
sorry I've deleted my previous comment, i was able to reproduce this actually. To clarify, the node process in this script shouldnt hang for 30 seconds, it should exit immediately. I've even tried passing `reconnectTries: 0` to the connection options, and it still hangs:

```javascript
const mongoose = require( 'mongoose' );
const m = new mongoose.Mongoose();

m.connect( 'mongodb://thisdoesntexist:27017', { reconnectTries: 0, useMongoClient: true } )
  .then(
    () => { console.log( 'Success!' ); },
    ( err ) => { console.error( err ); }
  );
```

**Comment by vkarpov15** [comment]
Tracked this down to a bug in the mongodb driver and put in a patch with some questions, see mongodb-js/mongodb-core#275
