### ISSUE TITLE
inconsistency in count()

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#6032]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`count()` is not removing field which are not present in model

```js
const model = Schecma({
field: String
})

model.count({field:"abc", imnotpresentinthemodel:1})
// -> collection.count({field:"abc"}, {})


```

**What is the expected behavior?**
`count()` should remove fields which are not present in model

**Please mention your node.js, mongoose and MongoDB version.**
node 8.9
mongoose 5.0.0

**Comment by varunjayaraman** [comment]
I think what @TrejGun is getting at here is that mongoose should strip fields from a query that dont exist in the schema. I'm not sure if this is by design or not, but right now mongoose will send extra fields to the query to mongodb:

```javascript
const mongoose = require('mongoose');
const assert = require('assert');
mongoose.Promise = global.Promise;

mongoose.set('debug', true);

const GITHUB_ISSUE = `gh-6032`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(`mongodb://localhost:27017/${ GITHUB_ISSUE }`);

  const schema = new mongoose.Schema({ name: String });

  const Model = mongoose.model('Model', schema);

  await Model.remove({});

  await Model.create({ name: 'test' });
  const count = await Model.count({ name: 'test', nonExistentField: 'asdf' });
  assert.equal(count, 1);
}
```

**Comment by vkarpov15** [comment]
This has been an issue for quite some time. We added a `strictQuery` option to tune strict mode for query filters in 4.10.0 with #4136 but didn't do a good job documenting it. In 5.0.4 you'll be able to set `strictQuery: true` on individual queries or on your schema to make strict mode apply to query filters. Thanks for reporting :+1: :palm_tree:
