### ISSUE TITLE
Set function throwing error when running for query? Upgrading from v4

### ISSUE THREAD

**Issue by Hunchmun** [Automattic/mongoose#6033]
Running "^5.0.1",

Bug exists where set function is run for a field (In my example, email) within a findOne query, looking for email. This breaks my code for version 4 that would look within `this` to find other values that are part of this instance of the model.

```js
email: {
        type: String,
        required: true,
        set: function(value) {
            this.settings.email.verified = false;
            return value.toLowerCase();
        }
    },
```

`this.settings.email.verified` is not defined because settings is undefined because `this` is not an instance of User, but instead a query object? Why is the set function run within a query?

For creating a new instance and saving the model it works fine. Please can you inform me how I can mitigate this abnormal behaviour?

Thanks

**Comment by vkarpov15** [comment]
This is one of the backwards braking changes for 5.0.0. In our experience most setters just edit the value passed in, so we now run setters on queries and updates so you dont need to manually lowercase. You can modify your setter to only set `verified` if `!(this instance of Query)`. Does this workaround work for you?

**Comment by Hunchmun** [comment]
Thanks for your reply,

That workaround sounds sufficient however I have since settled with making that change manually outside of the Mongoose object for now,

Feel free to close this issue unless you think it would be useful for someone else to stumble upon,

Thanks,
