### ISSUE TITLE
null saved for Boolean field

### ISSUE THREAD

**Issue by ypanyukov** [Automattic/mongoose#6034]
NodeJS: 8.9.4
Mongoose: 5.0.1
MongoDB: 3.6.2

1. Create Schema with Boolean field (boolField), set default false
2. Try to insert new document with boolField: null
3. Check document

Actual result - boolField: null, instead of false (that behaviour was in 4.13.9)
Expected result - boolField: false or error should be returned

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap

**Comment by ypanyukov** [comment]
is there something needed from me?

**Comment by vkarpov15** [comment]
A standalone script that reproduces your issue is the next step. If you can provide that, that would make the mongoose devs' lives a little easier :+1:

**Comment by ypanyukov** [comment]
So, in your case don't save null field then. I think type Boolean assumes only Boolean values. I'm not sure that null is Boolean in any universe :)

**Comment by vkarpov15** [comment]
@varunjayaraman this is the [correct behavior for now](https://github.com/Automattic/mongoose/issues/3981#issuecomment-200899915), and consistent across other types:

```javascript
  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false },
    numField: { type: Number, default: 0 },
    strField: { type: String, default: 'test' }
  });

  const Model = mongoose.model('Model', schema);

  const doc = await Model.create({ boolField: null, numField: null, strField: null });

  // All 3 fields will be `null`
  console.log(doc);
```

If you don't want to allow saving `null`, use `required: true`. See below:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6034`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false, required: true }
  });

  const Model = mongoose.model('Model', schema);

  // Throws an error because `boolField` is `required`
  await Model.create({ boolField: null });
} 
```

**Comment by ypanyukov** [comment]
I don't understand why we need default then?

IMHO. Behaviour in v4 I liked more

**Comment by vkarpov15** [comment]
What makes you think the behavior was different in 4.x? The below script still prints `boolField` as null in 4.13.10:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6034`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false }
  });

  const Model = mongoose.model('Model', schema);

  const doc = await Model.create({ boolField: null });

  console.log(doc);
}
```

`default` is helpful because otherwise you'd get an error with `required`

**Comment by ypanyukov** [comment]
My case was a little bit different

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6034`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false },
    stringField: { type: String }
  });

  const Model = mongoose.model('Model', schema);
  const reqBodyFields = {
    stringField: 'TEST'
  }

  const doc = await Model.create({
     boolField: reqBodyFields.boolField,
     stringField: reqBodyFields.stringField,
  });

  console.log(doc);
}
```

In 4.x doc will have only stringField, in 5.0.1 was stringField and boolField as null and in 5.0.3 (just checked) again only stringField. Looks like 5.0.3 fixed that case for me. Thanks!

P.S. I understand that in this case `reqBodyFields.boolField` is undefined instead of null which I mentioned, looks like i have mistaken in description. Sorry!

**Comment by ypanyukov** [comment]
I found! And Fully understand this bug

```const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6034`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run () {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false },
    stringField: { type: String }
  });

  const Model = mongoose.model('Model', schema);
  const reqBodyFields = {
    stringField: 'TEST'
  };

  Model.findOneAndUpdate({
    boolField: reqBodyFields.boolField,
    stringField: reqBodyFields.stringField
  }, {}, {
    upsert: true,
    new: true
  }, (err, doc) => {
    console.log(doc);
  });
}
```

**Comment by vkarpov15** [comment]
We made some changes with [boolean casting in mongoose 5](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#boolean-casting) that cause this. Mongoose 4 would incorrectly coerce `undefined` to a boolean in updates, which was inconsistent with how undefined is handled everywhere else. We added a new option `omitUndefined` that will remove undefined keys from updates, so that will help your use case because then `setDefaultsOnInsert` will kick in.

```javascript
async function run () {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new mongoose.Schema({
    boolField: { type: Boolean, default: false },
    stringField: { type: String }
  });

  const Model = mongoose.model('Model', schema);
  const reqBodyFields = {
    stringField: 'TEST'
  };

  Model.findOneAndUpdate({
    stringField: reqBodyFields.stringField
  }, {
    boolField: reqBodyFields.boolField
}, {
    upsert: true,
    new: true,
    setDefaultsOnInsert: true,
    omitUndefined: true // New option will be in mongoose 5.0.8
  }, (err, doc) => {
    console.log(err, doc);
  });
}
```

**Comment by ypanyukov** [comment]
Thanks!

**Comment by HenrikGr** [comment]
Question: How is empty string casted if I want to update where a field is of type boolean?
For me it sounds ok to cast to false.

**Comment by vkarpov15** [comment]
@HenrikGr by default, Mongoose throws a cast error if it gets an empty string for a boolean property. Do this to configure Mongoose to convert '' to `false` for you:

```javascript
// `mongoose.Schema.Boolean.convertToFalse` is a set of all primitive values Mongoose will cast to `false`
mongoose.Schema.Boolean.convertToFalse.add('');
```

**Comment by AhmedQamar10** [comment]
> @HenrikGr by default, Mongoose throws a cast error if it gets an empty string for a boolean property. Do this to configure Mongoose to convert '' to `false` for you:
> 
> ```js
> // `mongoose.Schema.Boolean.convertToFalse` is a set of all primitive values Mongoose will cast to `false`
> mongoose.Schema.Boolean.convertToFalse.add('');
> ```

updateUserTweet: async (userId, context) => {
    try {
      if (!context.user) {
        throw new Error('Unauthorized');
      }
      if (User.findById(context.user)) {
        const result = await Tweet.findByIdAndUpdate(userId,
          { text: userId.tweetInput.text }, { new: true });
        if (!result) {
          throw new Error('Not found!');
        }
        //console.log(result);
        return {
          ...result._doc,
          _id: result.id,
          createdTweets: two.bind(this, result.createdTweets)
        };
      }
      //}
    } catch (err) {
      throw err;
    }
  } 

My problem is i can make any transaction like insert or update or delete in another users but can't do it in my account I want only authenticated user of a post  can update it
Example
You can update in your profile but another users must can't do it please solve my problem

**Comment by vkarpov15** [comment]
@AhmedQamar10 I do not understand your question, can you please clarify?

**Comment by AhmedQamar10** [comment]
> @AhmedQamar10 I do not understand your question, can you please clarify?

I want only authenticated user (not users) of a post can update it

**Comment by AhmedQamar10** [comment]
> > @AhmedQamar10 I do not understand your question, can you please clarify?
> 
> I want only authenticated user (not users) of a post can update it

updateUserTweet: async (userId, context) => {
    try {
      if (!context.user) {
        throw new Error('Unauthorized');
      }
      if (User.findById(context.user)) {
        const result = await Tweet.findByIdAndUpdate(userId,
          { text: userId.tweetInput.text }, { new: true });
        if (!result) {
          throw new Error('Not found!');
        }
        //console.log(result);
        return {
          ...result._doc,
          _id: result.id,
          createdTweets: two.bind(this, result.createdTweets)
        };
      }
      //}
    } catch (err) {
      throw err;
    }
  }

**Comment by AhmedQamar10** [comment]
I want only authenticated user (not users) of a post can update it

updateUserTweet: async (userId, context) => {
try {
if (!context.user) {
throw new Error('Unauthorized');
}
if (User.findById(context.user)) {
const result = await Tweet.findByIdAndUpdate(userId,
{ text: userId.tweetInput.text }, { new: true });
if (!result) {
throw new Error('Not found!');
}
//console.log(result);
return {
...result._doc,
_id: result.id,
createdTweets: two.bind(this, result.createdTweets)
};
}
//}
} catch (err) {
throw err;
}
}

**Comment by vkarpov15** [comment]
I still don't understand the question. Please explain it another way.
