### ISSUE TITLE
Right way to add reference to models and find it

### ISSUE THREAD

**Issue by SilencerWeb** [Automattic/mongoose#6035]
I have such models:
```js
const suckerSchema = new mongoose.Schema({
  id: Number,
  chats: [
    {
      id: Number,
      allSucksCount: Number,
      weekSucksCount: Number,
    },
  ],
});

const Sucker = mongoose.model('Sucker', suckerSchema);


const chatSchema = new mongoose.Schema({
  id: Number,
  suckers: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Sucker',
  }],
});

const Chat = mongoose.model('Chat', chatSchema);
```

I save references to chat models just pushing `_id` of sucker models. And when I'm trying to check if I have already saved such reference I never can do it because if it is even saved, it gives me false.

```js
const chatSuckerIndex = chat.suckers.findIndex((suckerRef) => {
  return suckerRef === sucker._id; // never gives true
});
```

So, I want to know:
1. How to find the correct reference?
2. Is it the right way to save references(just pushing `_id`)?

node.js - v9.1.0
mongoose - v5.0.1
MongoDB - v3.6.2

**Comment by vkarpov15** [comment]
1. `chat.suckers.find(id => id.toString() === sucker._id.toString()` is the cleanest way. Remember that _id is an object.

2. Thats correct
