### ISSUE TITLE
broken import

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#6039]
**Do you want to request a *feature* or report a *bug*?**
bug
may be related to #3768

**What is the current behavior?**
works fine
```js
import {Schema} from "mongoose";

console.log(Schema); // -> [Function: Schema]
```

works fine
```js
import mongoose from "mongoose";

console.log(mongoose, mongoose.Schema); // -> Mongoose, [Function: Schema]
```

for some reason says undefined
```js
import mongoose, {Schema} from "mongoose";

console.log(mongoose, mongoose.Schema, Schema); // -> Mongoose, [Function: Schema], undefined
```

**What is the expected behavior?**
same as react should export underline components in both ways
```js
import React, {Component} from "react";

console.log(React, React.Component, Component); // -> React, [Function: Component], [Function: Component]
```

**Please mention your node.js, mongoose and MongoDB version.**
node 8.9.4
mongoose 5.0.1
babel 7.0.0-beta.38

**Comment by vkarpov15** [comment]
We don't currently support imports like `import { Schema } from 'mongoose'`, right now you must always use `import mongoose from 'mongoose';` . I'll investigate why this particular case bugs out but you shouldn't use any syntax other than the recommended one
