### ISSUE TITLE
Mongoose 5.0.1 MongoError: unknown string alias for $type: 2dsphere

### ISSUE THREAD

**Issue by heiba** [Automattic/mongoose#6043]
**Do you want to request a *feature* or report a *bug*?**

Reporting a bug

**What is the current behavior?**

I were using Mongoose 4.x and everything was fine. Soon I updated it to Mongoose 5.0.1, I started getting this error

```
/Users/me/ExampleCode/example-backend/example-backend-admin/example-backend-admin-places/node_modules/mongoose/lib/utils.js:417
    throw err;
    ^
MongoError: unknown string alias for $type: 2dsphere
at Function.MongoError.create (/Users/me/ExampleCode/example-backend/example-backend-admin/example-backend-admin-places/node_modules/mongodb-core/lib/error.js:45:10)
at /Users/me/ExampleCode/example-backend/example-backend-admin/example-backend-admin-places/node_modules/mongodb/lib/db.js:1103:54
at /Users/me/ExampleCode/example-backend/example-backend-admin/example-backend-admin-places/node_modules/mongodb-core/lib/connection/pool.js:541:18
at process._tickCallback (internal/process/next_tick.js:150:11)

Process finished with exit code 1
```
I never touched the schema for a long while, the only change was updating mongoose, so I'm sure it's where the problem is.

Here's the relevant part in the Mongoose Schema

`geometry: {type: String, trim: true, index: {unique: false, name: 'geometry', partialFilterExpression: {geometry: {$type: '2dsphere'}}}},`

I'm drowning .... save me ....

**If the current behavior is a bug, please provide the steps to reproduce.**

create a schema where a field has a partialFilterExpression: {geometry: {$type: '2dsphere'}}}}

**What is the expected behavior?**

Mongoose 4.x accepts the schema perfectly and ensure index works fine without outputting any error.

**Please mention your node.js, mongoose and MongoDB version.**

node.js v9.3.0
mongoose npm package v5.0.1
mongodb npm package v3.0.1

**Comment by vkarpov15** [comment]
Thanks for reporting and for your patience, we're a bit behind on issues but will investigate this ASAP :+1:

**Comment by varunjayaraman** [comment]
@heiba do you have a repro script or code sample showing what value you are trying to create for that field? I can't replicate your error
