### ISSUE TITLE
Is it possible to issue a pull request for the documentation?

### ISSUE THREAD

**Issue by caaker** [Automattic/mongoose#6045]
found here:

http://mongoosejs.com/

both of the github links on the front page are broken and there might be a documentation issue regarding promises.

What communication means are there to clear this up?

**Comment by vkarpov15** [comment]
I fixed the links in github, the changes will go live when we deploy 5.0.3. Regarding the promise docs issue, you're more than welcome to describe the issue on this thread. You can also put in a pull request, the raw code for the [promises docs](http://mongoosejs.com/docs/promises.html) is in the [`test/docs/promises.test.js` file](https://github.com/Automattic/mongoose/blob/c3451124b403d2dd66e41dd14f7707fa2b2a2fd3/test/docs/promises.test.js). To compile the docs locally, you can run `node website.js` and then `node static.js` to start a web server on port 8088.

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#documentation

**Comment by caaker** [comment]
I noticed that the Discover Plugins link is also broken on

http://mongoosejs.com/

It is pointing to 

http://plugins.mongoosejs.io/
