### ISSUE TITLE
[Question] How can I solve this problem? (response will not be returned.)

### ISSUE THREAD

**Issue by turbographics2000** [Automattic/mongoose#6049]
[My Project](https://github.com/turbographics2000/mongoose_probrem)
If you run this project and click the "Log In" button, the response will not be returned.
The task of findOne is addQueue, but it seems to be caused by not doQueue after that. (collection.js)
How can I solve this problem?

mongoose 5.0.1

**Comment by vkarpov15** [comment]
It looks like the [code that's supposed to be connecting to mongoose is commented out](https://github.com/turbographics2000/mongoose_probrem/blob/7d10e7ae646c571bdc11fa4431313d1ee7098e54/server.js#L9-L15)
