### ISSUE TITLE
Need to update nested object

### ISSUE THREAD

**Issue by Saravana-Kumar-putta** [Automattic/mongoose#6050]
**bug**

**Current Behaviour**
Not able to update the nested objects .

**Steps to reproduce bug**

```javascript
{
        "_id" : ObjectId("5a5f5b7bb457094c7c023033"),
        "name" : {
                "firstName" : "saravana",
                "lastName" : "kumar"
        },
        "__v" : 0
}
```

In the above code I tried to update the firstName using the below script 
```javascript
app.put('/api/users/:_id', function(req, res){
    var id = req.params._id;
    var user = {
      name : {
        firstName : "sssssssss"
      }
    }
    User.updateUser(id, user, {}).then(function(User){
      res.json(user);
    }).catch(function(err){
      res.status(500).send('Error Occured');
    });
  });
```

It gets updated, but removes the lastName in name object. The result is below : 

```
{
        "_id" : ObjectId("5a5f5b7bb457094c7c023033"),
        "name" : {
                "firstName" : "sssssssss"
        },
        "__v" : 0
}
```

**Expected Behaviour**

It should update only the firstName in name object and lastName should remain.

node v6.11.2
mongoose 4.13.0
mongodb 3.4

**Comment by vkarpov15** [comment]
Do `User.updateUser(id, { 'name.firstName': 'sssssss' })` instead of `User.updateUser(id, { name: { firstName: 'ssss' } })`. See [MongoDB docs on the subject](https://docs.mongodb.com/manual/reference/operator/update/set/#set-fields-in-embedded-documents)
