### ISSUE TITLE
Mongoose 5.0.1 MongoError: there are no users authenticated - unhandled correctly

### ISSUE THREAD

**Issue by mariusbancos** [Automattic/mongoose#6051]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
When trying to handle the connection errors for connection to MongoDB (I've switched from "authorization: disabled" to "authorization: enabled") mongoose doesn't handle correctly if I try to connect without using an user and password in the URI string.
When using the URI string "mongodb://localhost:27017/app" it throws an error even Iḿ trying to catch it. If I add some dummy user and password (not the correct ones) the error is correctly handled. The code is below:
```node
mongoose.connect(mongoDB)
    .then(() => {
      logger.info('Connection to database has been established successfully.');
    })
    .catch(err => {
      logger.error('Unable to connect to the database:', err);
    });
```
and the error thrown is:
```node
/../node_modules/mongoose/lib/utils.js:417
        throw err;
        ^
MongoError: there are no users authenticated
    at queryCallback (/../node_modules/mongodb-core/lib/cursor.js:223:25)
    at /../node_modules/mongodb-core/lib/connection/pool.js:541:18
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
even if I have the catch (seems it returns a response not an error)

**If the current behavior is a bug, please provide the steps to reproduce.**
Try connecting using mongoose to a MongoDB instance that is authenticated, first not using in the URI string a user and a password (which is handled incorrect) and second using a user and a password.

**What is the expected behavior?**
Expected behaviour is that the error is handled correctly.

**Please mention your node.js, mongoose and MongoDB version.**
node: v9.4.0
mongoose: 5.0.1
MongoDB: 3.6.2

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:

**Comment by varunjayaraman** [comment]
@mariusbancos this doesnt happen for me. I've created a database `gh-6051` in my local mongo setup and once inside that db in the mongo shell, I ran the following:

```javascript
db.createUser({ user: 'test', pwd: 'test', roles: [] })
```

Then i ran the following script:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6051`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({ name: String })

  const Model = mongoose.model('Model', schema);

  console.log(await Model.create({ name: 'test' }));
}
```

If i try to run this while `mongod` is up in authenticated mode, i get the following error (that is successfully caught):

```
Error! MongoError: not authorized on gh-6051 to execute command { insert: "models", ordered: false, $db: "gh-6051" }
```
