### ISSUE TITLE
Mongoose crashing node on virtual property array lookup -- seeing undefined instead of empty array when value not set.

### ISSUE THREAD

**Issue by claykohut** [Automattic/mongoose#6053]
Hey All,

We're totally stumped as to what's going on here.

Basically, we're having an issue where mongoose isn't defaulting to empty arrays on our production box, but it works properly on local. We're not aware of any config changes so we're very perplexed.

On our user model we have an array defined on the schema like:

```
sentInvites: [{
        email: { type: String },
        created: { type: Date, default: Date.now },
    }],
```

and a virtual property like:

```
UserSchema
    .virtual('emailInvitesInPastDay')
    .get(function () {
        return this.sentInvites.reduce((prev, cur) => {
           /// do stuff here
        }, 0);
    });
```

This code has worked for the past 8 months, but now on a recent deploy it has started crashing because `this.sentInvites` is being interpreted as `undefined` instead of an empty array when it's not set.

Does anyone have any idea what could be causing this? We're not aware of any config changes (but something obviously seems to have changed, as it's worked previously and works fine on our local / dev environments).

Thanks a lot,
Clay

**Comment by vkarpov15** [comment]
@claykohut can you check the mongoose version on both machines? Just print out `require('mongoose').version`
