### ISSUE TITLE
Dead Link to plugins page

### ISSUE THREAD

**Issue by ronaldlong46** [Automattic/mongoose#6057]
When clicking the "Discover Plugins" it leads to plugins.mongoose.io which returns a HTTP 408 error. If I navigate to plugins.mongoose.com on my own, however, it works fine. It seems there may have been a typo in the link and it lead to plugins.mongoose.com and not plugins.mongoose.io?

**Comment by vkarpov15** [comment]
https://github.com/Automattic/mongoose/pull/6062#issuecomment-361740573
