### ISSUE TITLE
Updating date with moment throws error

### ISSUE THREAD

**Issue by Sapenaattori** [Automattic/mongoose#6059]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Updating moment seems to now throw error: uncaughtException: Cannot create property '_isAMomentObject' on number '1517046698230'... 

**If the current behavior is a bug, please provide the steps to reproduce.**

The following example code has been working prior to 5.0 release:

```javascript
const DateTestSchema = mongoose.Schema({
    key: String,
    date: Date
});

const DateTest = mongoose.model('DateTest', DateTestSchema);

DateTest.update(
    { key: 'testkey'},
    {
        $set: {
            date: moment(),
        }
    },
    {upsert: true, setDefaultsOnInsert: true}
).exec();
```

**Please mention your node.js, mongoose and MongoDB version.**

node: v8.9.4
mongoose: 5.0.1
MongoDB: 3.4.7

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix :+1:
