### ISSUE TITLE
Cannot read property of null in mongoose

### ISSUE THREAD

**Issue by saeedhei** [Automattic/mongoose#6060]
I want to save my users and get their token after saving and after if block.
In First time I have This error: `TypeError: Cannot read property 'tok' of null` but in Secend Try I Can See users Token and is okey.
When I Added a `return doc;` before closing if, it just save user and Then nothing with no error.

How Can I Get users token in First Time? I mean Save Them in if Block and Get Their Token After If Block without null Error?
(I added Async But Not Work)

**Code:**
```js

      User.findById(msg.chat.id)
        .then(async (doc) => {
          if (!doc) { // Isn't in DB   First I Saved Users
            kitty.save()
              .then(async () => {
                await console.log('User Saved');
              }).catch((err) => {
                if (err) {
                  console.log(err);
                }
              });
          }
    
          const itok = await doc.tok;  // I Need Get Their Token here After Saving in First run
          console.log(itok);
        }).catch((err) => {
          if (err) {
            console.log(err);
          }
        });
    });


```
I Asked in [stackoverflow](https://stackoverflow.com/questions/48480868/cannot-read-property-of-null-in-mongoose) too

**Comment by vkarpov15** [comment]
I think this will solve your problem:

```javascript
             // Add `await` here
             await kitty.save()
              .then(async () => {
                await console.log('User Saved');
              }).catch((err) => {
                if (err) {
                  console.log(err);
                }
              });
```

In general, looking at your code I think you really need to get a better grasp of async/await fundamentals, I'd recommend you take 30 minutes to read this: http://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js.html

**Comment by saeedhei** [comment]
I Added But still doc.tok is null ! I added a return; before if `}` and I haven't any error and havent any Output for:
```
 const itok = await doc.tok;  // I Need Get Their Token here After Saving in First run
          console.log(itok);
```
