### ISSUE TITLE
4.13.10 is tagged as "latest" on npm

### ISSUE THREAD

**Issue by rarkins** [Automattic/mongoose#6063]
**Do you want to request a *feature* or report a *bug*?**

I cannot be sure but I suspect it's a mistake. When v4.13.0 was released just now, it reverted npmjs's "latest" tag from 5.0.1 to 4.13.10. Anyone running "npm install mongoose" etc will get 4.x not 5.x

Cc @vkarpov15 as it looks to be your commit, but not sure if you published.

**Comment by vkarpov15** [comment]
I published. We're shipping 5.0.2 shortly so this will be resolved by that, but thanks for reporting, we'll fix our release scripts to account for that :+1:
