### ISSUE TITLE
Finding records with ID's in an array - inconsistent results.

### ISSUE THREAD

**Issue by jpmyob** [Automattic/mongoose#6066]
**Do you want to request a *feature* or report a *bug*?**
BUG - This is a restatement of https://github.com/Automattic/mongoose/issues/3090, because I am seeing the same behavior, on a much later version. 

**What is the current behavior?**
I need to query out records that have a 'tenants' ID in an array of tenant ObjectID's

here is the data structure from the previous post - but, it's exactly my scenario

```javascript
{
  "_id": ObjectId("abc"),
  "name": "Miroslav",
  "tenants": [
    ObjectId("123"),
    ObjectId("456")
  ]
}

{
  "_id": ObjectId("abd"),
  "name": "Lothar",
  "tenants": [
    ObjectId("123"),
    ObjectId("694")
  ]
}
```

When using this syntax  

```
    User.find( { 'tenants': ObjectId(id) } ); 
```

I get this error
    ReferenceError: ObjectId is not defined

HOWEVER - when I use this syntax

```
    User.find( { 'tenants': mongoose.Schema.ObjectId(id) } );
```

I get ALL records EXCEPT those with the ID in the array.
This is OPPOSITE the expected result

I have a total of 8 records, with 2 having "tenants" IDs that match - so I get 6 back with the above.
Of course when I run the 

```
    User.find( { 'tenants': ObjectId(id) } ); 
```

In compass - I get the 2 records I expect.

ENVIRONMENT
  "dependencies": {
    "bluebird": "^3.5.1",
    "body-parser": "*",
    "cors": "*",
    "express": "*",
    "mongoose": "4.9.8",
    "xoauth2": "^1.2.0"
  },

CONNECTING TO
MongoDB ATLAS 3.4.10

USER MODEL

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const UserSchema = new Schema({
	name: {
		type: String
		,required: true
	},
	tenants: {
		type: Array
		,required: false
	}	
}, {strict:false} );

const User = module.exports = mongoose.model('User', UserSchema);

module.exports.getUserTenants = function( id, callback ) {
	User.find( { 'tenants': mongoose.Schema.ObjectId(id) }, callback );
}

**Comment by jpmyob** [comment]
Found an answer 
use mongoose.Types.ObjectId instead of mongoose.Schema.ObjectId.

https://stackoverflow.com/questions/48499024/mongoosejs-find-docs-with-ids-in-an-array/48509187#48509187

**Comment by vkarpov15** [comment]
@jpmyob you want `User.find( { 'tenants': mongoose.Types.ObjectId(id) } );` not `User.find( { 'tenants': mongoose.Schema.ObjectId(id) } );` . `ObjectId()` is a global in compass but not in node.js.
