### ISSUE TITLE
.save() does not work for items I construct myself

### ISSUE THREAD

**Issue by xjamundx** [Automattic/mongoose#607]
Mongoose 2.3.12

Schema:

```
var Scores = module.exports = new Schema({
    _id: String
    , name: String
    // many more fields
})
```

In the actual database:
    db.scores.findOne()

```
{ name: 'city',
      _id: 'city'
}
```

Some bits of code:

```
var score = new Scores({_id: "city"})
score.name = "seattle"
score.save(function(err) {
    if (err) console.log(err) // E11000 duplicate key error index: augment.scores.$_id_  dup key: { : "city" }
})
```

A really bad attempt to make it work failed as well:

```
var score = new Scores({_id: "city"})
score.isNew = false
score.name = "seattle"
score.save(function(err) {
    if (err) console.log(err) // Mod on _id not allowed on { name: 'city',
})
```

This probably works, but it's annoying if I'm updating more than just "name"

```
var score = new Scores({_id: "city"})
Scores.update({_id: score.id}, {$set: {name: score.name}, function(err) {
  // happy save, but super annoying
})
```

Same basic issue as before

```
var score = {_id: "city", name: "seattle"}
Scores.update({_id: score._id}, {$set: {name: score.name}},  function(err) {
  // happy save, but super annoying
})
```

I assume this is a known limitation, but it's sort of unclear in the docs or maybe I just missed something. Any help would be appreciated. Thanks!

**Comment by meetDeveloper** [comment]
Hey,
I want to ask how .save() works, when we do findOne, and then change the retrieve document and save, it updates.

```
User.findOne({name: "Hermione Granger"}, function(err, user){
    if(err){
        console.log(err);
    } else {
        user.posts.push({
            title: "3 things I really hate",
            content: "Voldemort, Voldemort, Voldemort"
        });
        user.save(function(err, user){
            if(err){
                console.log(err);
            } else {
                console.log(user);
            }
        })
    }
})
```

But suppose I knew the Id and do something like:

```
var newUser = new User({
    email: "hello@gmail.com",
    name: "Hermione Granger",
      _id: "5a3372598b2918098cffa4e4"             //I knew the Id
});


newUser.save(function(err, user){
    if(err){
        console.log(err);
    } else {
        console.log(user);
    }
});
```
Then it gives the error, I want to know why save() behave differenly under findOne() where it updates and here it gives error, `11000 E11000 duplicate key error index`

**Comment by santhosh77h** [comment]
It looks like _id you are using is duplicate as error suggests *duplicate
key error index*

**Comment by meetDeveloper** [comment]
I used duplicate id purposely, I wanted to know when we do findOne and then save it, it saves and updates, I wanted to know then why does when I am doing it myself  using the id, then it is showing that id is duplicate, look at the first snippet, then save is working, but then I myself used _id hoping that it would find that this document already exists in the collection and update it.

**Comment by meetDeveloper** [comment]
@xjamundx  I have a doubt, which I have written above, can you please help me.

**Comment by vkarpov15** [comment]
Internally each document has an `isNew` property. If that is true, save() tries to insert a new document. If you have an existing document, you should create the document using `User.hydrate(pojo)` instead of `new User(pojo)`

**Comment by fr6nco** [comment]
@vkarpov15 the hydrate seems not to work. save() wont save the object to the DB. Attaching snippet:

```
 let role = await this.getRoleById(id);
    
    const roleObj = {
      ...role.toObject(),
      ...update
    };
    const updatedRole = this.getModel().hydrate(roleObj);
    
    console.log(updatedRole);

    await updatedRole.save();
    return updatedRole;
```

Am I missing something?
UpdateOne just works fine, however I want to track the _v in the object too. When using update _v is not updated

**Comment by vkarpov15** [comment]
@fr6nco you should do `const Model = this.getModel(); const updatedRole = new Model(roleObj); await updatedRole.save();`. The `hydrate()` function creates a document with no modified fields, so `save()` is a no-op unless you change something.

**Comment by fr6nco** [comment]
Yes, thank you. I figured it out later.
