### ISSUE TITLE
Mongoose automatically converting Binary data to base64

### ISSUE THREAD

**Issue by syedmkazmi** [Automattic/mongoose#6071]
Im experiencing some weird behaviour from Mongoose/MongoDB. Im using Mongoose Version **4.13.4**.

**My data schema is:**

        photo: {data: Buffer, contentType: String}

**I uploaded an image to mongoose using the following the code:**

    let upload = (req, res) => {
       User.findByIdAndUpdate(req.params.id, { photo: fs.readFileSync(`uploads/${req.file.originalname}`)
      }, {safe: true, new: true})
        .exec()
        .then(() => {
            sendJsonResponse(res, 200, {"message": "photo uploaded"})
        })
        .catch(err => {
            sendJsonResponse(res, 500, err)
        })
     };

**The above successfully uploads an image as follows:**

[![enter image description here][1]][1]

**The weird behaviour:**

According to my knowledge mongoose/mongoDB returned `binary data` as `binary data` and the user had to convert it to `base64 string` before it could be used. Am I wrong?

In my case when I pull the data from mongoose I don't get the `binary data`. I get the converted `base64`. **Please note that I have not placed any code anywhere that is converting binary data.**

Below is an image of what the returned data looks like:

[![enter image description here][2]][2]

**Before returning the data to the user I `console.log` my data server side:**

[![enter image description here][3]][3]

**My Questions:**

 1. Can anyone explain whats causing this?
 2. Is mongoose capable of automatically converting binary data?
 3. Does this mean I don't need to implement "binary to base64" conversion code?

If mongoose is capable of automatically doing this then that is great! **But I am confused whether this is a bug or a feature.**

  [1]: https://i.stack.imgur.com/scecQ.png
  [2]: https://i.stack.imgur.com/zBv6v.jpg
  [3]: https://i.stack.imgur.com/CsHFf.png

**Comment by vkarpov15** [comment]
That's very strange and not expected at all. For one thing, its strange that `photo` is a string rather than an object. With `{ photo: fs.readFileSync(`uploads/${req.file.originalname}`) }`, it looks like you're passing a buffer to the photo object, perhaps you mean to do `{ photo: { data: fs.readFileSync(`uploads/${req.file.originalname}`), contentType: 'foo' } }` ?

**Comment by syedmkazmi** [comment]
Ah okay. I didn't notice that I'll try it and update back here again. One question though, in mongoose whats the difference between:

`photo: {data: Buffer, contentType: String}`

and

`photo: {type: Buffer, contentType: String}`

**Comment by vkarpov15** [comment]
In the former, `photo` is an object with 2 properties, `data` and `contentType`. In the latter, `photo` is a buffer and the `contentType` property is ignored because you need to be [careful about properties named 'type'](http://mongoosejs.com/docs/faq.html#type-key) in mongoose.

**Comment by luciodale** [comment]
You are not getting base64 because you forgot this line of code `res.setEncoding('base64')`. Add it before you send your JSON response.
