### ISSUE TITLE
Depopulate all fields

### ISSUE THREAD

**Issue by bisubus** [Automattic/mongoose#6073]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

There's no way to depopulate a document without knowing the paths and listing them.

Automatically populated fields in some models are desirable for most cases I have. But this prevents from saving modified document with `save` in this models because validators are triggered and fail on populated fields.

Even though populated documents are in use, the class that calls `model.save()` is unaware of populated documents, and hard-coded `model.depopulate('foo').depopulate('bar')` results in unwanted tight coupling.

**What is the expected behavior?**

The suggestion is to make `path` argument optional in `depopulate` and `populated` methods and apply them to all populated fields when the argument is not specified, like `model.depopulate()`.

**Please mention your node.js, mongoose and MongoDB version.**

Mongoose 4.11.6

**Comment by vkarpov15** [comment]
I like this feature, but I'm not sure it is necessary for your use case. If I'm reading this correctly, you don't want to call `save()` because you're worried mongoose will `save()` the modified populated docs, but `save()` does **not** recursively save populated docs so that shouldn't be a problem. Can you elaborate on the "But this prevents from saving modified document with save" issue?

**Comment by bisubus** [comment]
@vkarpov15 I'm sorry for not being specific enough. Yes, `save` itself works but it triggers validators, like

```
foo: {
	type: mongoose.Schema.Types.ObjectId,
	ref: 'Foo',
	validate: {
  	  	validator: mongoose.Types.ObjectId.isValid,
		type: 'custom',
		message: 'foo'

	}
}
```
Validators fail for populated fields , and this prevents it from being saved.

And it is saved normally with `model.depopulate('foo').save()`.

**Comment by vkarpov15** [comment]
Ah that is definitely a separate issue, custom validators should be smart enough to not send populated docs down. Will investigate fixing this issue for a patch release and then add a separate issue for the `depopulate()` issue
