### ISSUE TITLE
`depopulate()` with no args should depopulate all paths

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6075]
Re: https://github.com/Automattic/mongoose/issues/6073#issuecomment-361816491

**Comment by lineus** [comment]
This sounded like a fun thing to implement. As it turns out it's already done 😃. Closing.

**Comment by adamreisnz** [comment]
This doesn't work for me:

```js
doc.depopulate()
```

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at model.Document.depopulate (node_modules/mongoose/lib/document.js:2994:25)
```

**Comment by adamreisnz** [comment]
@lineus could you see what's happening here? Only if I specify paths to depopulate does it actually work.

**Comment by lineus** [comment]
@adamreisnz yeah 👍  looking into now.

**Comment by lineus** [comment]
@adamreisnz it looks like if you call depopulate on a doc that hasn't been populated this error is thrown. while tracking this down I noticed that it doesn't remove populated virtual paths. I think I should have put more energy into testing this before I closed it :smile:. Reopening this. Thanks for pointing it out!

**Comment by adamreisnz** [comment]
Cheers thanks! Pretty sure my document was populated though, as it was outputting populated JSON, and after I added the line to depopulate, it wasn't.

**Comment by lineus** [comment]
@adamreisnz can you share a simplified example schema that demonstrates this on a populated doc?

**Comment by adamreisnz** [comment]
Yes this was the schema:

```
const IntegrationSchema = new Schema({
  club: {
    type: Schema.Types.ObjectId,
    ref: 'Club',
  },
  type: {
    type: String,
  },
  apiKey: {
    type: String,
  },
  oAuth: {},
  data: {},
  private: {},
});
```

The `club` field is what I was trying to depopulate. `integration.depopulate('club')` worked fine, but `integration.depopulate()` threw the error I reported above.

**Comment by adamreisnz** [comment]
Thanks for the swift resolution!
