### ISSUE TITLE
Discriminator Schema Union Failures with Recursion

### ISSUE THREAD

**Issue by stieg** [Automattic/mongoose#6076]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I describe a schema for a discriminator in which a top level field Object but a child field within the object has specific requirements, the casting will not apply and will cause validation failures.  If the top level fields are different types then it works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
[See the following code](https://github.com/stieg/mongoose-discriminator-recursion-failure)
```javascript
"use strict";
const Promise = require('bluebird');
const assert = require('assert');
const mongoose = require('mongoose');

console.log('mongoose version:', mongoose.version);
mongoose.Promise = Promise;

var schema = mongoose.Schema({
  account: {
    type: Object,
  },
  info: {
    ref: 'Bar',
    required: true,
    type: mongoose.Schema.Types.ObjectId,
  }
});

var Model = mongoose.model('Thing', schema);
Model.on('error', function(err) {
  console.log('Hit Model Error ', err.message);
});

var discSchema = mongoose.Schema({
  account: {
    user: {
      ref: 'Foo',
      required: true,
      type: mongoose.Schema.Types.ObjectId,
    }
  }
});

var Disc = Model.discriminator('ThingDisc', discSchema);

function main() {
  const m1 = new Model({
    info: 'AAAAAAAAAAAAAAAAAAAAAAAA',
  });
  const m1Err = m1.validateSync();
  console.log('M1:', m1);
  assert(!m1Err, m1Err);

  const d1 = new Disc({
    account: {
      user: 'AAAAAAAAAAAAAAAAAAAAAAAA',
    },
    info: 'AAAAAAAAAAAAAAAAAAAAAAAA',
  });
  console.log('D1:', d1);
  const d1Err = d1.validateSync();
  assert(!d1Err, d1Err);

  console.log('Success');
};

main();
```

**What is the expected behavior?**
I would expect that the discriminator schema would win out over the parent and would properly cast the objects recursively.
**Please mention your node.js, mongoose and MongoDB version.**
Node v8.9.4
Mongoose 5.0.2, 4.13.{9,10}

**Comment by stieg** [comment]
@vkarpov15 I see you added the "Needs Repro Script" tag?  Is the example I provided insufficient?  If so let me know what you are missing and I will do what I can to provide it.  Cheers.

**Comment by varunjayaraman** [comment]
hey @stieg sorry we're just a bit behind processing issues. THank you for the detailed repro script!

It looks like for the top-level field, mongoose thought the field existed even though you passed it an invalid type, and once it stripped it the validation had already passed so it was missed in `validateSync()`, while that did NOT happen for the child discriminator field

**Comment by varunjayaraman** [comment]
gonna remove the "needs repro script" tag on this one, the original repro script is fully copy-pastable
