### ISSUE TITLE
Unrecognized argument to $dateToString: timezone

### ISSUE THREAD

**Issue by talentedandrew** [Automattic/mongoose#6077]
**Do you want to request a *feature* or report a *bug*?**
Want to report this bug.

**What is the current behavior?**
I'm executing this querry

`Sessions
            .aggregate([
                {
                    $project: {
                        "parts": {
                            $dateToString: {
                                format: '%Y-%m-%d %H:%M:%S',
                                date: '$sessionDate',
                                timezone: "$timeZone"
                            }
                        }
                    }
                }
            ])`

But its giving me this error.
`Unrecognized argument to $dateToString: timezone`

**Please mention your node.js, mongoose and MongoDB version.**
nodejs version 8.9 and mongod version: 3.4.9 (MMAPv1)

**Comment by lineus** [comment]
It looks like the timezone optional parameter for dateToString isn't available in [3.4 docs](https://docs.mongodb.com/v3.4/reference/operator/aggregation/dateToString/)
it does exist in 3.6 however [3.6 docs](https://docs.mongodb.com/manual/reference/operator/aggregation/dateToString/)

**Comment by talentedandrew** [comment]
@lineus  Ok thanks. Please close this issue

**Comment by varunjayaraman** [comment]
yup, thanks @lineus!
