### ISSUE TITLE
$pull won't remove subdocument

### ISSUE THREAD

**Issue by ronaldlong46** [Automattic/mongoose#6078]
I'm using Mongoose 4.13.10.
**What is the current behavior?**
nRemoved is showing as 0, and not removing the subdocument yet the subdocument exists.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here are my schemas:
```
var locationSchema = new mongoose.Schema({
    name: String,
    gps: String,
    thumbnail: String,
    image: String,
    description: String,
    catches: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Catch"
        }
        ]
});
```

```
var catchSchema = mongoose.Schema({
    species: String,
    weight: String,
    image: String,
    catchlocation: String,
    catchlocationid: String,
    description: String,
    timePosted: { type: Date, default: Date.now },
    author: {
        id: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User"
        },
        username: String
    }
},
   {timestamps: true}
);
```

Basically, I am trying to remove the referencing ObjectId "Catch" from the "Location" schema. I am using this route to do so:
```
app.get("/locations/:id/catch/:catchid/deleteref", function(req, res){
    Location.findById(req.params.id, function(err, post){
        if(err){
            console.log(err)
        } else {
            post.update({
                'catches._id': req.params.catchid
              }, {
                $pull: { catches: { _id: req.params.catchid } }
              }, function (error, result) {
                  console.log("The location ID is " + post);
                  console.log("The catch ID is " + req.params.catchid);
                  console.log(result);
                  res.redirect("/")
              });
        }
    })
});
```
The strange thing is. When the catchid is being console logged, said catchid is matching the referencing ObjectId that stills exists in the database. Yet I am still getting:
`{ ok: 0, n: 0, nModified: 0 }`

Not sure if I'm doing something wrong or what, I've been trying to solve this for days to no avail.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js v8.9.4, mongodb-core: 2.1.18
![problem](https://user-images.githubusercontent.com/35465493/35677485-99f20948-0704-11e8-96c2-67786f9a20eb.png)

**Comment by lineus** [comment]
@ronaldlong46 I'm by no means an expert, but I'm trying to learn this stuff so I'm just jumping in. I created a gist with a working version [here](https://gist.github.com/lineus/dc69627879877f74193870a3e1a31587) 
the only thing that didn't work at all for me from your code was: 
```
            post.update({
                'catches._id': req.params.catchid
              }, {
                $pull: { catches: { _id: req.params.catchid } }
              }
```
hopefully there is something in my gist that helps you, if not please let me know why it won't work for you so I can learn from it.

**Comment by ronaldlong46** [comment]
@lineus 

I edited my route to be more in line with how you're did yours.
```
app.delete("/locations/:id/catch/:catchid/deleteref", function(req, res){
    Location.findById(req.params.id, function(err, post){
        if(err){
            return console.log(err)
        }
        post.catches.pull(req.params.catchid._id)
        post.save(function(err, editedLocation){
            if(err){
                return console.log(err)
            }
            console.log(editedLocation.catches.length);
            console.log(req.params.catchid)
        })
    })
});
```

It still isn't deleting the referencing objectid. Any ideas on what I'm doing wrong. Does doing something like .toString() for the req.params matter? I'm so stumped haha.

**Comment by lineus** [comment]
```
post.catches.pull(req.params.catchid._id)
```
without seeing exactly what data you're passing in, this is just a guess, but that _id seems superfluous. 
Just based on the parameter name. is req.params.catchid an object with an _id property or is it the id itself?

**Comment by ronaldlong46** [comment]
@lineus I changed it to `post.catches.pull(req.params.catchid)` and it worked. It's now deleting the reference. Thank you so much for the help!
