### ISSUE TITLE
populating an array returns [[Object], [Object]] instead of actual content of objects

### ISSUE THREAD

**Issue by shoudou** [Automattic/mongoose#6079]
Hello Everyone,
I am having a problem populating array field on mongoose.  When I tried to populate a field of type array, it print out [[Object], [Object]] instead of the actual populated content of the array.  the following is my Model, JS code, and output. 

myModel.js
```
const mongoose = require('mongoose');
const helpers = require('../helpers/helpers');
const Schema = mongoose.Schema;

// Create Schema
const MessageSchema = new Schema({
  sender: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  subject: {
    type: String
  },
  content: {
    type: String
  },
  receiversList: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  individual: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'PersonServed'
  },
  date: {
    type: Date,
    default: Date.now()
  }
});

const Message = mongoose.model('Message', MessageSchema);
exports.Message = Message;
```

JS Code
```
//get msg sent
exports.getMessageSent = (req, res) => {
  Message.find({ sender: req.user.id })

    .populate({
      path: 'individual',
      model: PersonServed,
      select: 'firstName'
    })
    .populate({
      path: 'receiversList',
      model: User,
      //select: 'name'
    })
    .then(sentMessageList => {

      console.log(sentMessageList);
      res.render('message/messageSent', {
        pTitle: 'Message Sent',
        sentMessageList: sentMessageList,
      });
    })
}
```

Output
```
  { _id: 5a7305148696b13b68b4f35d,
    subject: 'test',
    sender: 5a6ea52f492a77551c0cc1f1,
    content: 'test ',
    individual: { _id: 5a7006919193b14e50761d3e, firstName: 'Jame' },
    __v: 0,
    date: 2018-02-01T12:15:41.521Z,
    receiversList: [ [Object], [Object] ] } ] <<<== This is my problem
```
As you can see, it populates 'individual' but not 'reveiversList'. I want it to return the actual content of the objects inside the array so I can sent the data to the views. Thank you very much in advance

**Comment by lineus** [comment]
I took a look at this and in the process created a single file to test from:
[gist here](https://gist.github.com/lineus/be6c0f9e722d8983d4c307fe198fb637)
I ran it on mongoose 5.0.3 and node 9.3.0.  In your getMessageSent route you do a Model.find which returns an array (even if theres only one result from the find). the output.txt in my gist shows what I think you're expecting to see.

**Comment by wxs77577** [comment]
it's ok, just because you use `console.log` in console, it's fold nested data by default. my be you need `console.log(util.inspect(ret.toJSON(), true, 10))`.
ps. don't forget to `require('util')`
