### ISSUE TITLE
Empty enum value

### ISSUE THREAD

**Issue by yamifr07** [Automattic/mongoose#6085]
MongoDB version: 3.4.9
Mongoose version: 4.13.10 (because some plugins do not support 5.x)
Node version: 8.6.0

When a schema has an optional enum field and I want to clear it, I set to undefined (myElement.enumField = undefined;). Instead of unsetting the field, in mongo I see {enumField: null}. If I get the element using a query and try to save it, mongoose throws an error:
ValidatorError: 'null' is not a valid enum value for path 'enumField'

**Comment by varunjayaraman** [comment]
yes because `null` is the intentional absence of a value, so we treat it as a value that must be validated amongst `enum` values. Add `null` to your list of acceptable values for the `enum` field and it will work.

See: https://github.com/Automattic/mongoose/issues/3044 for reference

**Comment by yamifr07** [comment]
thank you @varunjayaraman but I don't know why if I unset it using doc.field = undefined mongo set the enum to null. I'd like to unset enum fields to avoid adding null value to non required enum fields.

**Comment by varunjayaraman** [comment]
if you want to unset the value you can do `findByIdAndUpdate(doc._id, { $unset: { pathToField: '' } })`
