### ISSUE TITLE
Array update operator $addToSet doesn’t work as described in the official documentation of MongoDB native driver

### ISSUE THREAD

**Issue by melyourhero** [Automattic/mongoose#6086]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When to I try to update a document using the $addToSet operator with strings, mongoose simply concatenates it to a single element, when I try it with numbers mongoose simply cleans the whole array.

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimum steps to reproduce this behavior: https://github.com/melyourhero/mongoose-bug

**What is the expected behavior?**
The expected behavior described in official MongoDB native driver documentation here: https://docs.mongodb.com/manual/reference/operator/update/addToSet/#behavior

**Please mention your node.js, mongoose, and MongoDB version.**
Node: v8.5.0
MongoDB: v3.4.10
mongoose: v5.0.3

**Comment by varunjayaraman** [comment]
youre right, it seems to be clearing the array:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6086`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

  const schema = new mongoose.Schema({
    letters: [String],
    numbers: [Number]
  });

  const Model = mongoose.model('Model', schema);

  // with letters
  const doc = await Model.create({ letters: ['a', 'b'] });

  const update = await Model.findByIdAndUpdate(doc._id, { $addToSet: { letters: ['c', 'd'] } }, { new: true });

  console.log(update);

  const docNumbers = await Model.create({ numbers: [1, 2] });
  const updateNumbers = await Model.findByIdAndUpdate(
    docNumbers._id,
    { $addToSet: { numbers: [3, 4] } },
    { new: true }
  );

  console.log(updateNumbers);
}
```

That final log output shows:

```
{ letters: [ 'a', 'b', 'c,d' ],  numbers: [],
  _id: 5a791b58293ba7ab0c48a349,  __v: 0 }
{ letters: [],  numbers: [],  _id: 5a791b58293ba7ab0c48a34a,  __v: 0 }
```

where `numbers` should be `[1, 2, 3, 4]`

**Comment by evanhenke** [comment]
Correct me if I'm wrong, but I'm not sure this is a bug.  Per the MongoDB docs to append an array to another array you would have to use the $each modifier.  So adjusting your updates, @varunjayaraman , to look like this:

```
const update = await Model.findByIdAndUpdate(
	  doc._id,
	  { $addToSet:  { letters: { $each: ['c', 'd'] } } },
	  { new: true }
  );
```
and 
```
const updateNumbers = await Model.findByIdAndUpdate(
	    docNumbers._id,
	    { $addToSet: { numbers: { $each:  [3,4] } } },
	    { new: true }
  );
```

Should work, or at the least could be a workaround.  Granted I tried this with MongoDB 3.6 and not 3.4, but the docs don't suggest that it'd be any different.

**Comment by varunjayaraman** [comment]
@evanhenke im aware of that actually, in this case though it will just append the string `'c,d'` if you use `$addToSet` with an array.

The bug here is that it seems to be treating strings and numbers differently. While the first case(with strings) appends a joined version of the string with a `,` delimiter, the second case (with numbers) clears the array entirely

**Comment by evanhenke** [comment]
Ah, my mistake. I guess I don't know how to read.

**Comment by vkarpov15** [comment]
@evanhenke is right in that this needs to be `{ $addToSet: { numbers: { $each: [3, 4] } } }`. With this fix, mongoose will cast `{ $addToSet: { numbers: [3, 4] } }` to `{ $addToSet: { numbers: { $each: [3, 4] } } }`. Mongoose is not emptying out the array in the mongodb server, just mongoose gives up because it doesn't know what to do with `[1, 2, [3, 4]]` as a value for `numbers`.
