### ISSUE TITLE
Model.find() is not returning all documents

### ISSUE THREAD

**Issue by gasteve** [Automattic/mongoose#609]
With a particular model, I have ~120 documents.  When I run model.find({}, function(err, list) {…}); some documents for that model are not returned.  If I add a clause to the query, I can make it return certain matching documents that are not returned with an empty query.  The problem can also occur when I specify a query parameter that matches many documents (one or two are missing from the returned results).

I'm curious if others have experienced this problem and how they fixed it.  Is it a mongoose issue, the mongo native module, or mongodb itself?  What did others do to fix it?

I am running mongoose 1.3.7 and mongodb 1.8.1 on Ubuntu Linux.

**Comment by totty90** [comment]
Any news? I'm making tests and the indexes are run after the queries or inbetween.

**Comment by vkarpov15** [comment]
@totty90 the server ticket unfortunately is still open. You can either disable index creation and just create them manually before your tests run, or you can wait for the `Model.on('index')` event to start your tests.

**Comment by totty90** [comment]
I've made a script to wait for the index event to fire. https://github.com/totty90/mongoose-connect

**Comment by mernxl** [comment]
I am facing the same problems when i use the query builder on some of my Models. 
The model's collection has `45 documents`, but on doing the following;
```
const query = Model.find();
... build with query

const docs = await query.exec();
```
I receive `19 documents`.

But on executing 
```
const docs = await Model.find();
````
I receive all `45 documents`.

Any help will be very mch appreciated.

**Comment by vkarpov15** [comment]
Instead of using `Model.on('index')`, in mongoose 5 you can do [`Model.init().then()`](http://mongoosejs.com/docs/api.html#init_init), `Model.init()` returns a promise that is fulfilled after index build is done, or immediately if `autoIndex` is disabled.

**Comment by MajidJafari** [comment]
For me, it was, part of documents `timestamp` fields type was `Double` and the other part of documents were in `IsoDate` format. So `Mongoose` filtered them out. Using `aggregate` instead of `find` saved me.
