### ISSUE TITLE
how can i return mongoose query results to a variable?

### ISSUE THREAD

**Issue by javadrajabi** [Automattic/mongoose#6091]
i wanna return mongoose query results to a variable but i can't... 
router.get('/products', function(req, res) {
var prod;
  Products.find({},function (err, pro){
     prod=pro;
       });
console.log(prod); //is undefined...
   });
  });
how i can do it??

so...
i wanna run a function after mongoose find but i can't... 

router.get('/products', function(req, res) {
  Products.find({},function (err, pro){
       res.render('dashboard/products', { 
         title: 'Express',
         text:req.session.text,
         products:pro
       });
   });
     req.session.destroy('text') ;  //this line has error :"callback" argument must be a function
  });
 plz help me..

**Comment by javadrajabi** [comment]
How can I access documents outside of the function?

**Comment by lineus** [comment]
@javadrajabi  [this](http://gitter.im/Automattic/mongoose) is a better venue to ask for general help with mongoose.
in short, your console.log is being executed before the assignment.
```
router.get('/products', function(req, res) {
var prod;
Products.find({},function (err, pro){
prod=pro; 
});
console.log(prod);  // this happens before prod=pro in your find callback.
});
});
```
please feel free to join the link above to gitter and ask for help. I'll be back online in an hour to assist further.

**Comment by javadrajabi** [comment]
tnx  brother.i'm waiting for you answer

**Comment by lineus** [comment]
@javadrajabi can you close this issue and join [Automattic/mongoose](http://gitter.im/Automattic/mongoose) ? I'm online there now. Thanks!

**Comment by javadrajabi** [comment]
ok
