### ISSUE TITLE
Broken link on mongoosejs.com

### ISSUE THREAD

**Issue by smonff** [Automattic/mongoose#6096]
The button linking to plugins on the http://mongoosejs.com homepage target a non-existant location: it goes to an .io URL when it should go to the .com one.

Changing the link to http://plugins.mongoosejs.com fix the problem.

**Comment by lineus** [comment]
@smonff there have been a few bugs for this opened up already. you can close this, the devs are aware of it.

**Comment by smonff** [comment]
Sorry, didn't saw it before posting.
