### ISSUE TITLE
Mongoose 5.0.0 broken merge-behavior in where 

### ISSUE THREAD

**Issue by nodkz** [Automattic/mongoose#6097]
Example code:
```js
// default query
const userQuery = User.where({ status: 'approved' }); 

// some logic, which generates additional criterias or change default
const someFilter = { 
  status: { $ne: 'delayed' },
};

// merging criterias and query execution
const data = await userQuery.where(someFilter).exec();
```

**With Mongoose 4 it works without problem**
It generates/merge following criteria: `{ status: { $ne: 'delayed' } }`.

**With Mongoose 5.0.3 it fails with error** 
<details>
  <summary>`Cannot create property '$ne' on string 'approved'`</summary>

  - utils.js:320 merge
    [npm_ram_disk]/[mongoose]/lib/utils.js:320:15
  - utils.js:322 Object.merge
    [npm_ram_disk]/[mongoose]/lib/utils.js:322:7
  - query.js:1417 model.Query.Query.merge
    [npm_ram_disk]/[mongoose]/lib/query.js:1417:9
  - mquery.js:276 model.Query.Query.where
    [npm_ram_disk]/[mquery]/lib/mquery.js:276:17
  - filter.js:151 filterHelper
    [npm_ram_disk]/[graphql-compose-mongoose]/lib/resolvers/helpers/filter.js:151:47
  - count.js:40 resolve
    [npm_ram_disk]/[graphql-compose-mongoose]/lib/resolvers/count.js:40:33
  - connectionResolver.js:147 _callee$
    [npm_ram_disk]/[graphql-compose-connection]/lib/connectionResolver.js:147:34
  - runtime.js:62 tryCatch
    [npm_ram_disk]/[regenerator-runtime]/runtime.js:62:40
  - runtime.js:296 Generator.invoke [as _invoke]
    [npm_ram_disk]/[regenerator-runtime]/runtime.js:296:22
  - runtime.js:114 Generator.prototype.(anonymous function) [as next]
    [npm_ram_disk]/[regenerator-runtime]/runtime.js:114:21
  - asyncToGenerator.js:17 step
    [npm_ram_disk]/[babel-runtime]/helpers/asyncToGenerator.js:17:30
  - asyncToGenerator.js:35
    [npm_ram_disk]/[babel-runtime]/helpers/asyncToGenerator.js:35:14
  - Promise
  - _export.js:35 F
    [npm_ram_disk]/[core-js]/library/modules/_export.js:35:28
  - asyncToGenerator.js:14
    [npm_ram_disk]/[babel-runtime]/helpers/asyncToGenerator.js:14:12
  - connectionResolver.js:275 resolve
    [npm_ram_disk]/[graphql-compose-connection]/lib/connectionResolver.js:275:21
  - resolver.js:523
    [npm_ram_disk]/[graphql-compose]/lib/resolver.js:523:18
  - resolver.js:523
    [npm_ram_disk]/[graphql-compose]/lib/resolver.js:523:18
  - resolver.js:523
    [npm_ram_disk]/[graphql-compose]/lib/resolver.js:523:18
  - jobTC.js:554 rp
    /Volumes/npm_ram_disk/build/development/webpack:/src/schema/job/jobTC.js:554:1
  - resolver.js:354
    [npm_ram_disk]/[graphql-compose]/lib/resolver.js:354:18
  - resolver.js:341 resolve
    [npm_ram_disk]/[graphql-compose]/lib/resolver.js:341:29
  - Array.reduce
  - Array.reduce
  - index.js:164
    [npm_ram_disk]/[express-graphql]/dist/index.js:164:37
  - next_tick.js:228 process._tickDomainCallback
    internal/process/next_tick.js:228:7
</details>

### As a workaround what you can suggest me?
How to remove some keys from creteria? Is there public mongoose api for this:
```diff
const userQuery = User.where({ status: 'approved' });
const someFilter = { status: { $ne: 'delayed' } };

Object.keys(someFilter).forEach(key => {
-   delete userQuery._criteria[key];
+   some proper way to remove existed condition, for avoiding incorrect merge behavior
});
 
const data = await userQuery.where(someFilter).exec();
```

**Comment by varunjayaraman** [comment]
yup this looks like a confirmed bug:

```javascript
const mongoose = require('mongoose');

const GITHUB_ISSUE = `gh-6097`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
mongoose.Promise = global.Promise;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({ status: String });

  const Model = mongoose.model('Model', schema);

  await Model
    .where({ status: 'approved' })
    .where({ status: { $ne: 'delayed' } });
}
```

This should not throw with the following error:

```
TypeError: Cannot create property '$ne' on string 'approved'
```

As a workaround for now I'd suggest merging the objects manually before passing it to `.where`
