### ISSUE TITLE
Create multiple collections with a same model, how can it be achieved? 

### ISSUE THREAD

**Issue by anatoly314** [Automattic/mongoose#6103]
Hi,
I need to create two collections based on the same model, found this solution on stackoverflow - [Mongoose - Same schema for different collections in (MongoDB).
](https://stackoverflow.com/questions/13337155/mongoose-same-schema-for-different-collections-in-mongodb) According to a positive score of the answer, it should work but it doesn't.

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var schema = new Schema({...});
var model1 = mongoose.model('model1', schema);
var model2 = mongoose.model('model2', schema);
```
I'm creating different models based on same schema, nothing happen. Mongoose doesn't store items in database, no error is thrown. What can be issue? 

**I'm using:**
>  mongoose - v4.13.10
>  mongo database - v3.4.10

Thank you in advance.

**Comment by anatoly314** [comment]
Ok, it was the issue in my code. It didn't have required fields and mongoose didn't throw any exceptions.

**Comment by khouloud93** [comment]
hi plz i want to ask how multiple models will share the same collection in MongoDB.

**Comment by vkarpov15** [comment]
@khouloud93 [discriminators](https://mongoosejs.com/docs/discriminators.html)
