### ISSUE TITLE
Mongoose $inc array of subdocuments does not modify anything

### ISSUE THREAD

**Issue by yharaskrik** [Automattic/mongoose#6104]
**Do you want to request a *feature* or report a *bug*?**

Bug Report

**What is the current behavior?**

```
this.campaignModel.update(
          { campaignId: '5a7a017e0aa5311d9c75c86b', 'subCampaigns.subCampaignId': '5a7a153fe035de396c6f5b3c' },
          { $inc: { 'subCampaigns.$.amountRaised': 10}},
          (err: any, subResult: any) => {...
```

Does not update the subdocument within the array as per this schema.

````
{
    "_id" : ObjectId("5a7a017e0aa5311d9c75c86b"),
    "campaignId" : "5a7a017e0aa5311d9c75c86b",
    "subCampaigns" : [ 
        {
            "_id" : ObjectId("5a7a0eee6849f507d0499a18"),
            "name" : "test5",
            "campaignId" : ObjectId("5a7a017e0aa5311d9c75c86b"),
            "subCampaignId" : "1aKysewspn6CqNGVkv6pyL"
        }
        {
            "name" : "test8",
            "amountRaised" : 20.0,
            "campaignId" : ObjectId("5a7a017e0aa5311d9c75c86b"),
            "subCampaignId" : "5a7a153fe035de396c6f5b3c",
            "_id" : ObjectId("5a7a153fe035de396c6f5b3c")
        }
    ],
    "name" : "test8",
    "__v" : 12,
    "totalDonated" : 110.0
}
````

**If the current behavior is a bug, please provide the steps to reproduce.**

Attempt to use $inc on the value of a matched subdocument within an array of schemas.

**What is the expected behavior?**

`db.getCollection('campaigns').update({"_id": ObjectId("5a7a017e0aa5311d9c75c86b"), "subCampaigns.subCampaignId":"5a7a153fe035de396c6f5b3c"}, {$inc: {"subCampaigns.$.amountRaised": 10}})`

It should increment the amountRaised value in the matched subdocument within the subCampaigns array

**Please mention your node.js, mongoose and MongoDB version.**

node 8.9.4
MongoDB 3.6
Mongoose 5.0.2

**Comment by wentout** [comment]
![image](https://user-images.githubusercontent.com/1651439/35980813-bf534172-0cfc-11e8-8e41-c443e719be06.png)

?

**Comment by yharaskrik** [comment]
Is your question why I am using the dollar sign operator? To my knowledge (and it seems in the command line command) it is the positional operator that references the matched documents in the array?

Correct me if I am wrong as that could be the problem but then why would it work from CL but not mongoose?

**Comment by wentout** [comment]
Thank you for that a fast answer. Sorry, I'm just trying to understand and learn. I'm not a pro, just found similar question. Seems my knowledge are not so far. It is obvious that technique used for mongo CLI is not the same as you doing withing Mongoose. I think mongoose is unable to treat sub-document values. If I would try to write this exactly part of code I will use .forEach and update everything manually.

And I still wonder if this feature can be implemented also.

**Comment by yharaskrik** [comment]
The nice thing about this particular case is there will only ever be one subdocument updated, what I am trying to do by using $inc is avoid a race condition by reading the value of amountRaised into memory changing it and writing it back.

**Comment by lineus** [comment]
I wrote a simple ( contrived ) example of this:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/spin')

const subTestSchema = mongoose.Schema({
  name: String,
  widgets: Number
})

const testSchema = mongoose.Schema({
  name: String,
  subTests: [ subTestSchema ]
})

const Test = mongoose.model('test', testSchema)

const subTestsA = [
  { name: 'fizzle', widgets: 42 }, // note widgets = 42
  { name: 'frank' },
  { name: 'boon', widgets: 16 },
  { name: 'alibaster' },
  { name: 'wonky', widgets: 2 },
  { name: 'janky', widgets: 1000 },
  { name: 'sport' }
]

const subTestsB = [
  { name: 'shirley' },
  { name: 'boostbobble', widget: 11 },
  { name: 'mcnugget', widgets: 5000 },
  { name: 'schmarny', widgets: 8 },
  { name: 'zooblewee' },
  { name: 'sparticusser', widgets: 1000 },
  { name: 'fillywhipple' }
]

const a = new Test({
  name: 'gloop',
  subTests: subTestsA
})

const b = new Test({
  name: 'popstance',
  subTests: subTestsB
})

let promiseA = a.save()
let promiseB = b.save()
Promise.all([promiseA, promiseB]).then(function (res) {
  Test.update({ name: 'gloop', 'subTests.name': 'fizzle' },
    { $inc: { 'subTests.$.widgets': 10 } }, function (err, res) {
      if (err) { return console.error(err) }
      Test.findOne({ name: 'gloop' }, function (err, doc) {
        if (err) { return console.error(err) }
        console.log(doc)
        mongoose.connection.close()
      })
    })
})
```
output:
```
{ subTests: 
   [ { _id: 5a7cacc0dea1cb652b2f5cec, name: 'fizzle', widgets: 52 }, // it worked here.
     { _id: 5a7cacc0dea1cb652b2f5ceb, name: 'frank' },
     { _id: 5a7cacc0dea1cb652b2f5cea, name: 'boon', widgets: 16 },
     { _id: 5a7cacc0dea1cb652b2f5ce9, name: 'alibaster' },
     { _id: 5a7cacc0dea1cb652b2f5ce8, name: 'wonky', widgets: 2 },
     { _id: 5a7cacc0dea1cb652b2f5ce7, name: 'janky', widgets: 1000 },
     { _id: 5a7cacc0dea1cb652b2f5ce6, name: 'sport' } ],
  _id: 5a7cacc0dea1cb652b2f5ce5,
  name: 'gloop',
  __v: 0 }
```
@yharaskrik Can you provide a complete example of code that fails?

**Comment by yharaskrik** [comment]
I feel like kind of an idiot now, your code reminded me to go check the one thing that I did not before posting everywhere! I failed to include amountRaised in the subCampaign schema.. As soon as I added that in it worked perfectly fine. 

Closing issue now. Thank you for the help.

**Comment by portothree** [comment]
> Is your question why I am using the dollar sign operator? To my knowledge (and it seems in the command line command) it is the positional operator that references the matched documents in the array?
> 
> Correct me if I am wrong as that could be the problem but then why would it work from CL but not mongoose?

I have been using without the $, just 'object.key' and works well, can you confirm if its changes after the date of your issue? I saw at the documentation without the dollar sign too
