### ISSUE TITLE
databaseName option in `.connect()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6106]
The `mongodb+srv` protocol for mongodb atlas [doesn't support specifying the db name in the connection string](https://github.com/mongodb/specifications/blob/master/source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst#specification). That means mongoose will always connect to admin, which is bad because atlas doesn't allow raw queries on admin

**Comment by Autom3** [comment]
My temporary fix (for people who need this ASAP, until it either gets added to the spec, or the functionality gets added to mongoose)
```js
mongoose.connection.on('connected', function() {
    // Hack the database back to the right one, because when using mongodb+srv as protocol.
    if (mongoose.connection.client.s.url.startsWith('mongodb+srv')) {
        mongoose.connection.db = mongoose.connection.client.db('yourDatabase');
    }
    console.log('Connection to Mongo established.')
});
mongoose.connect(...);
```

**Comment by Autom3** [comment]
Seems like my suggestion might get added to the srv spec, might still be a good feature to have though.

**Comment by vkarpov15** [comment]
Yeah I hope it gets added to the srv spec too, thanks for suggesting it. It is extremely weird that it isn't in there already, but you can work around it with this `dbName` option for now :+1:

**Comment by healyje** [comment]
Seeing this as well. Pretty annoying, thanks for the workaround.
