### ISSUE TITLE
mongoose save not working

### ISSUE THREAD

**Issue by aartiHarshe** [Automattic/mongoose#6108]
mongoose - 4.11.7
node - 8.9.1

```javascript
User.findOne({"_id": req.auth.credentials.id}).exec(function(err, user) {
            if(err) return reply(reformatErrors(err));
            if(!user) return reply(Boom.forbidden(req.i18n.__('invaliduser')));
            if(!user.education) {
                user.education = [];
            }
            user.education.push(req.payload);
            user.save(function(err, user) {
                if(err) return reply(reformatErrors(err));
                reply(HapiResponse(false, req.i18n.__('educationadd')));
            });
        });
```

I am trying to save user but it is going in to infinite looping and not calling the callback. Not only in this function, but in some of the other functions as well, mongoose save is not working.
How i can resolve this issue. Please help me to solve the issue.

**Comment by wentout** [comment]
Hi,

First of all seems if your "education" field is an array, you need to add
`user.markModified('education');
`
before the line where you are saving modified user.
More details [schema docs](http://mongoosejs.com/docs/schematypes.html).

And, please, add description of how you've figured out this was a mongoose infinite looping, but not yous fault in other parts of code. I don't see any other strange things here, only the meaning of that "reply", "reformatErrors" and "HapiReasponse" methods is hidden from us. So... I still suppose this is not the fail inside of mongoose, may be you are able to get stacktrace from [node --inspect](https://nodejs.org/dist/latest-v8.x/docs/api/inspector.html) ?

**Comment by markstos** [comment]
@aartiHarshe Are you getting "RangeError Maximum Call Stack Exceeded" ? There are other issues you could search for about that.

**Comment by varunjayaraman** [comment]
Can you confirm that its getting to `user.save()` ? Maybe putting a log right above it? Also can we see the schema?

**Comment by varunjayaraman** [comment]
@aartiHarshe can you please confirm? Marking this as stale

**Comment by daynier** [comment]
Having the same issue on my first go around with mongoose. It's strange because as I step into the save method I can see the code execution, but it just never comes back out. On top of that if you make the same call again it generates an error stating "Can't save() the same doc multiple times in parallel. Document: 5d2523ce4306449c7978ffc0".
