### ISSUE TITLE
Virtual Population Fields Causing Slowdown on Document Initialization 

### ISSUE THREAD

**Issue by makinde** [Automattic/mongoose#6120]
**What is the current behavior?**
I'm loading a small set of documents (~300). Using opbeat and new relic, I'm seeing 300-600ms of time in node after the query comes back from the server.

The slowdown seems to have started as I started using virtual population (those last 4 at the bottom). Adding others virtually populated fields in the schemas seems to further slow init time.

I can use `.lean()`, which speeds things up (~0.1ms per document), but it seems like I should be able to load this much data without having to use `.lean()` for reasonable performance.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/makinde/9655c3f89412e75efd5e96a4b7be57b8

**What is the expected behavior?**
I'm seeing document init times between 1-4ms per document.

**Please mention your node.js, mongoose and MongoDB version.**
node 8.9.4, mongoose 4.13.6, MongoDB 3.0.10 ...running on Heroku/mLab

**Comment by vkarpov15** [comment]
Do you have indexes on your `foreignFields`? Also, how are you determining that the time is spent in node as opposed to waiting for the query to respond?

**Comment by makinde** [comment]
> Do you have indexes on your foreignFields?

I do have indexes on the foreign fields. Note, in my example in the gist, I'm not actually populating the virtual fields. When i remove those virtual fields from my schema, the instantiation of the member objects becomes much faster. I've also been able to slow down my other schemas by adding bogus virtual populate fields (that are never used in the rest of the codebase).

> Also, how are you determining that the time is spent in node as opposed to waiting for the query to respond?

I'm relying on a couple factors. (A) The new relic graph below shows that my requests are spending the vast majority of time in node as opposed to queries. (B) Adding `.lean()` to the query reduces the time for that query 10x. (C) I've added pre/post init hooks and timed the gap between them getting called for each instantiation and I get ~1.7ms per object instantiation.
 
![screen shot 2018-01-25 at 3 55 13 pm](https://user-images.githubusercontent.com/157415/36134859-c1d5d618-10ca-11e8-8b1d-53118bdeb31e.png)

**Comment by vkarpov15** [comment]
Thanks for clarifying, will investigate. Can you provide a standalone script that shows the slow code? That will help speed things up.

**Comment by vkarpov15** [comment]
I appreciate your patience with the delay in getting back to you, we've been struggling to keep up on issue reports post 5.x release. I put together a repro script and haven't been able to reproduce this issue unfortunately, I'm getting ~0.5ms average, nowhere near the performance numbers you mentioned. Can you provide some sample data or modify the below script to reproduce your issue?

```javascript
const mongoose = require('mongoose');

const GITHUB_ISSUE = `gh-6120`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
mongoose.Promise = global.Promise;

const idValidator  = require('mongoose-id-validator');
const leanVirtuals = require('mongoose-lean-virtuals');
const mongooseLeanId = require('mongoose-lean-id');
const moment       = require('moment');
const gravatar     = require('gravatar');
const _            = require('lodash');

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useMongoClient: true });
  await mongoose.connection.dropDatabase();

  const Member = mongoose.model('Member', getSchema());

  const numMembers = 600;
  const numReps = 100;

  await Member.deleteMany();

  for (let i = 0; i < numMembers; ++i) {
    await Member.create({
      name: 'Test' + i,
      email: 'Test@test.co'
    });
  }

  let total = 0;
  for (let i = 0; i < numReps; ++i) {
    const start = Date.now();
    const res = await Member.find({ status: 'ACTIVE' });
    total += Date.now() - start;
  }

  console.log('Average time in ms', total / numReps);
}

function getSchema() {
  const Schema = mongoose.Schema;

  const memberSchema = new Schema({
    name             : {
      type: String,
      required: true
    },
    active           : {
      type: Boolean,
      default: true,
      index: true,
    },
    kind             : {
      type   : String,
      enum   : ['MEMBER', 'AFFILIATE', 'STAFF', 'ADVISOR', 'PLACEHOLDER'],
      default: 'MEMBER',
      index  : true
    },
    email            : {
      type     : String,
      index    : true,
      lowercase: true,
      trim     : true
    },
    phone            : String,
    calendar         : String,
    gender           : String,
    birthday         : Date,
    shirt_size       : String,
    live             : String,
    university       : String,
    employer         : String,
    title            : String,
    industry_entrance: Date,
    linkedin         : String,
    facebook         : String,
    twitter          : String,
    github           : String,
    training         : {
      type  : String,
      enum  : ['Other', 'Test'],
      default: 'Other',
      set   : v => v
    },
    preferred_channel: {
      type: String,
      enum: ['EMAIL', 'FACEBOOK', 'SLACK', 'TWITTER'],
      default: 'EMAIL',
      set   : v => v
    },
    mentees          : [{
      type: Schema.Types.ObjectId,
      ref : 'Member'
    }],
    long_goals       : String,
    expertise        : String,
    needs            : String,
    offer_help       : [{ type: String, enum: ['Test'] }],
    get_help         : [{ type: String, enum: ['Test'] }],
    squad            : {
      type: String,
      ref: 'Squad',
      index: true,
      set: v => v
    },
    app_score        : Number,
    slack_name       : String,
    slack_id         : String,
    slack_img        : String,
    future_focus     : {
      type: String,
      enum: ['Test'],
      set: v => v
    },
    past_focus       : [{ type: String, enum: ['Test'] }],
    career_stage     : {
      type: String,
      enum: ['SENIOR', 'MID-LEVEL', 'JUNIOR'],
      set: v => v
    }
  }, {
    // Options
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at'
    }
  });

  memberSchema.index({'created_at': 1});

  memberSchema.pre('validate', function(next) {
    // There is sometimes messy data in our list of areas for offering
    // and getting help. Clear that out by trimming the list.
    if (this.get_help) {
      this.get_help = _.filter(this.get_help);
    }
    if (this.offer_help) {
      this.offer_help = _.filter(this.offer_help);
    }
    if (this.past_focus) {
      this.past_focus = _.filter(this.past_focus);
    }
    if (!this.future_focus) {
      this.future_focus = undefined;
    }

    const origObj = this.toObject();
    const training = origObj.training;
    if (training !== undefined && !training) {
      this.training = undefined;
    }
    const pc = this.toObject().preferred_channel;
    if (pc !== undefined && !pc) {
      this.preferred_channel = undefined;
    }

    next();
  });

  memberSchema.virtual('first_name').get(function () {
    return this.name.split(' ')[0];
  });
  memberSchema.virtual('first_name').get(function () {
    return this.name.split(' ')[0];
  });

  memberSchema.virtual('last_name').get(function () {
    // split the name by the first space and return the rest
    return this.name.split(' ').slice(1).join(' ');
  });

  memberSchema.virtual('years_experience').get(function () {
    if (!this.industry_entrance) {
      return 0;
    }

    const years_apart = moment().diff(this.industry_entrance, 'years', true);
    return Math.ceil(years_apart);
  });

  memberSchema.virtual('photo_url').get(function() {
    // Strategy is to use gravatar first, and then set the backup URL be twitter,
    // facebook, github, or a default, in that order. So if someone wants to
    // change what shows up here, there best bet is to update gravatar (which will
    // also update Slack as well). We try github last since having an account
    // doesn't assure us that there's a profile pic like fb/twitter would.
    let url = '';
    const default_dimensions = 128; // matches the md size for the fb/twitter pics

    // gravatar fallback must seem like jpg's or png's :P
    // https://en.gravatar.com/site/implement/images/
    const fake_jpg_ending = '#.jpg';

    const profile_url = this.twitter || this.facebook || this.github || '';
    const username = _.last(_.filter(profile_url.split('/')));
    if (this.twitter) {
      url = 'https://avatars.io/twitter/' + username;
    } else if (this.facebook) {
      // remove periods from username to fix question mark issue
      url = 'https://avatars.io/facebook/' + (username || "").replace(/\./g,'') + '/medium';
    } else if (this.slack_img) {
      url = this.slack_img;
    } else if (this.github) {
      url = 'https://avatars.githubusercontent.com/' + username + fake_jpg_ending;
    } else {
      url = gravatar.url(this.email, {
        size: default_dimensions
      });
    }

    return url;
  });

  memberSchema.virtual('region').get(function () {
    if (_.startsWith(this.squad, 'M') || _.startsWith(this.squad, 'BK')) {
      return 'NY';
    } else {
      return 'SF';
    }
  });

  memberSchema.virtual('props_received', {
    ref: 'Props',
    localField: '_id',
    foreignField: 'receivers',
  });

  memberSchema.virtual('props_given', {
    ref: 'Props',
    localField: '_id',
    foreignField: 'giver',
  });

  memberSchema.virtual('goals', {
    ref: 'Goal',
    localField: '_id',
    foreignField: 'owner',
  });

  memberSchema.virtual('primary_squad', {
    ref: 'Squad',
    localField: '_id',
    foreignField: 'members',
    justOne: true,
  });

  memberSchema.plugin(idValidator);
  memberSchema.plugin(leanVirtuals);
  memberSchema.plugin(mongooseLeanId);

  return memberSchema;
}
```

**Comment by makinde** [comment]
If there's a way to DM you, I can send you the info for our test DB on mLab.

I think you may be seeing the same/similar perf I'm seeing. I captured a couple CPU profiles on my local machine. It looks like garbage collection gets in the way sometimes, and there's variance in how long objects take to create, as well as what function they spend time in.
https://www.dropbox.com/s/8x519wzfg9mqidk/CPU-20180228T191840.cpuprofile?dl=0
https://www.dropbox.com/s/t0vnpslzg40r7x8/non-bluebird.cpuprofile?dl=0

It is good to know that ~0.5ms is expected for object instantiation. I'd assumed it should be faster than that. With those speeds, datasets >20 will start to take longer to construct mongoose objects than it does to run the query and get the data back to the server.

Happy to look into `lean`ing all my read queries if that's best practice.

**Comment by vkarpov15** [comment]
Sure, you can just email me at val@karpov.io . Keep in mind the times that I measured are for instantiating 600 docs, not just one.

In general, I'd recommend using `lean()` if you're just reading data to send to the client. You're already using `mongoose-lean-virtuals`, so this will save you the overhead of instantiating a full mongoose doc. Also, there's no need to use both `mongoose-lean-virtuals` and `mongoose-lean-id`, `mongoose-lean-virtuals` is a superset of the functionality of `mongoose-lean-id`.
