### ISSUE TITLE
default value for linked models?

### ISSUE THREAD

**Issue by johnantoni** [Automattic/mongoose#6127]
Little question, when defining your model's and you have a table attribute linking to another table what should I set the default value to?

```
var donationSchema = Schema({
  project: {
    type: Schema.Types.ObjectId,
    ref: 'projects',
    default: null
  },

```

Some people say to set it as a number which kind of makes sense:

```
var donationSchema = Schema({
  project: {
    type: Schema.Types.ObjectId,
    ref: 'projects',
    default: 0
  },

```

What's recommended?

Thanks,

**Comment by lineus** [comment]
@johnantoni In my experience so far ( in the docs and issues here ), I haven't seen the default field set on a reference. Being unaware of your use case, it's kind of hard to imagine a scenario where the specific "falsey" value held there would make much difference unless you were specifically looking for it in your implementation. **It's safe to just add the reference to the schema without the default.**

**Comment by johnantoni** [comment]
Thanks @lineus you're probably right. I'll try without and see how that goes, thanks
