### ISSUE TITLE
near does not seem to work

### ISSUE THREAD

**Issue by pronebird** [Automattic/mongoose#6132]
I have a very simple piece of code that doesn't seem to work with mongoose v5:

Works with mongo:
```
MySchema.query.nearBy = function (lon: number, lat: number, maxDistanceKm: number) {
  const maxDistanceRadians = maxDistanceKm / 6371;
  return this.find({
    location: {
      $near: [lon, lat],
      $maxDistance: maxDistanceRadians
    }
  });
};
```

Does not work with mongoose:

```
MySchema.query.nearBy = function (lon: number, lat: number, maxDistanceKm: number) {
  const maxDistanceRadians = maxDistanceKm / 6371;
  return this.near({
    center: [lon, lat],
    maxDistance: maxDistanceRadians
  });
};
```

Used in both cases as:

```
const result = await MySchema
      .find()
      .nearBy(lon, lat, maxDistance)
      .exec();
```

Wat?

**Comment by Zwimber** [comment]
Might have to do with: 

https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#geonear

And 

https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#geonear

**Comment by pronebird** [comment]
@Zwimber I don't think there is a single mention of `$geoNear` in this issue. Have you mistakenly posted a comment in the wrong thread?

**Comment by lineus** [comment]
@pronebird can you please elaborate on what you mean by "Does not work with mongoose"? Are you getting an error, is nothing happening? It would help to know your versions of mongoose, mongodb server, and node as well.

**Comment by pronebird** [comment]
@lineus no results.

**Comment by lineus** [comment]
@pronebird is it possible for you to provide a minimal (but complete) example of this? also, I'm curious, are you running this against a sharded collection?

**Comment by pronebird** [comment]
@lineus I just realized I forgot to give it a field with `where` clause. WTH it was looking for LOL. Case closed thanks for bearing with me.
