### ISSUE TITLE
5.0.5 API Docs are incomplete.

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6135]
@nfearnley on gitter.im pointed out that the api docs are only showing the model docs.

She pointed to this file: [link](https://github.com/Automattic/mongoose/blob/f90244f029d26401ff402fe8b813d54d61803642/docs/source/api.js#L15)

**Comment by vkarpov15** [comment]
Fixed by #6136, thanks for catching, will push a release within the next 24 hours to fix
