### ISSUE TITLE
CastUpdate always generate error even if no error happen - bug

### ISSUE THREAD

**Issue by workfel** [Automattic/mongoose#6137]
Hi all,
I'm using Mongoose 4.13.6, node 8.6.0 and i have a problem with mongoose and azure app-insights.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I activated app-insights on my app, and when i test my application, app-insight throw an error on my all mongoose update.

I debug mongoose and i found in `castUpdate.js` file this (line 105) . 
```js

function walkUpdatePath(schema, obj, op, strict, context, pref) {
  var prefix = pref ? pref + '.' : '';
  var keys = Object.keys(obj);
  var i = keys.length;
  var hasKeys = false;
  var schematype;
  var key;
  var val;

  var hasError = false;
    var aggregatedError = new ValidationError();

  var useNestedStrict = schema.options.useNestedStrict;
 // ....
```
A instance of `new ValidationError()` is created even is no error happen.  So app-insight catch this error and put the app on error.

I simply modified this function, remove the intanciation ( `var aggregatedError = new ValidationError();`)  on all catch if create the new instance and all work's fine.

```js

function walkUpdatePath(schema, obj, op, strict, context, pref) {
  var prefix = pref ? pref + '.' : '';
  var keys = Object.keys(obj);
  var i = keys.length;
  var hasKeys = false;
  var schematype;
  var key;
  var val;

  var hasError = false;
    

  var useNestedStrict = schema.options.useNestedStrict;

  while (i--) {
//...
        if ('$each' in val) {
          try {
            obj[key] = {
              $each: castUpdateVal(schematype, val.$each, op, context)
            };
          } catch (error) {

            hasError = true;
              var aggregatedError = new ValidationError();
            _handleCastError(error, context, key, aggregatedError);
          }
//...
```

So, it's a bug or i can bypass this current version and go work fine for me ?

Thx

**Comment by vkarpov15** [comment]
We'll fix this for next release :+1:
