### ISSUE TITLE
Default not used when value is null

### ISSUE THREAD

**Issue by JonathanWbn** [Automattic/mongoose#6138]
I want to report a bug.

**Current behaviour:**
When updating a Document with a property's value being `null` and that property being defined with `required: true` and `default: {DEFAULT_VALUE}` in the Schema, the default Value is not replacing `null`.

**How to reproduce:**
```
const DogSchema = new Schema({
  legs: { type: Number },
  name: { type: String },
});

const dog = await DogSchema.create({ legs: 4, name: null });

const NewDogSchema = new Schema({
  legs: { type: Number },
  name: { type: String, default: 'Bello', required: true },
});

const dog = await DogSchema.findByIdAndUpdate(
  dog._id,
  {},
  { new: true, upsert: true, setDefaultsOnInsert: true }
);

// dog.name === null
```

**Expected behaviour:**
The default property should replace `null`. (`dog.name` should equal `'Bello'`)

mongoose: 4.13.7
MongoDB: 3.4.2

**Comment by lineus** [comment]
Hi @JonathanWbn can you provide the part of your code that declares what Schema is?
```const Schema = ?``` if it's being required from a module, please include the module code as well.  Thanks!

**Comment by JonathanWbn** [comment]
Hi @lineus, my bad, the complete version would look more like this:
```
const DogSchema = new mongoos.Schema({
  legs: { type: Number },
  name: { type: String },
});

const DogModel = mongoose.model('Dog', DogSchema);

const dog = await DogModel.create({ legs: 4, name: null });

const NewDogSchema = new mongoose.Schema({
  legs: { type: Number },
  name: { type: String, default: 'Bello', required: true },
});

const NewDogModel = mongoose.model('Dog', NewDogSchema);

const dog = await NewDogModel.findByIdAndUpdate(
  dog._id,
  {},
  { new: true, upsert: true, setDefaultsOnInsert: true }
);
```

**Comment by lineus** [comment]
No worries @JonathanWbn. Here is my implementation of your code:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/test_db')
const Schema = mongoose.Schema

async function run () {
  const dogSchema = new Schema({
    legs: { type: Number },
    name: { type: String }
  })

  const DogModel = mongoose.model('Dog', dogSchema)

  const dog = await DogModel.create({ legs: 4, name: null }, (err, saved) => {
    if (err) { return console.error(err) }
    console.log(saved)
  })

  const newDogSchema = new Schema({
    legs: { type: Number },
    name: { type: String, default: 'Bello', required: true }
  })

  var NewDogModel

  try {
    NewDogModel = mongoose.model('Dog', newDogSchema)
    const findOpts = {
      new: true,
      upsert: true,
      setDefaultsOnInsert: true
    }
    await NewDogModel.findByIdAndUpdate(dog._id, {}, findOpts, (err, saved) => {
      if (err) {
        return console.error(err)
      }
      console.log(saved)
    })
  } catch (e) {
    console.log(e)
  }
}

run()
```
and it's output:
```
/Users/lineus/dev/Help/4/: ./6138.js 
{ mongooseVersion: '4.13.7',
  mongodbNativeVersion: '2.2.33',
  nodeVersion: 'v8.9.4',
  mongodbServerVersion: '3.4.4' }
{ __v: 0, legs: 4, name: null, _id: 5a84ea13e7701b735a17d25f }
{ OverwriteModelError: Cannot overwrite `Dog` model once compiled.
    at new OverwriteModelError (/Users/lineus/dev/Help/4/node_modules/mongoose/lib/error/overwriteModel.js:18:11)
    at Mongoose.model (/Users/lineus/dev/Help/4/node_modules/mongoose/lib/index.js:405:13)
    at run (/Users/lineus/dev/Help/4/6138.js:28:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Cannot overwrite `Dog` model once compiled.',
  name: 'OverwriteModelError' }
^C
/Users/lineus/dev/Help/4/: 
```
attempting to overwrite an existing Model ( Dog in this case ) results in an OverwriteModelError so the findAndUpdateOne never runs.

**Comment by JonathanWbn** [comment]
Thank you.
But I'm not sure if that covers what I was actually trying to do:
In my real life code, I am not defining a new Schema, but updating the old one. I'm not sure how I can put that into a script, tho.

**Comment by lineus** [comment]
@JonathanWbn What is the impetus for updating the existing schema? 

Describe the problem you're trying to solve in more detail and let's see if we can sort it out.

**Comment by JonathanWbn** [comment]
Sounds good, I am basically trying to manage the migrations of schemas that I am using.
For example, when I am adding a new property to my schema, say, an object, and I then update a document that was created with the old Schema, I want to avoid errors. To achieve this, I want to figure out how to set the correct defaults to always get a document that has the shape of the new schema.

I would also like to handle the edge case that that new property has a value of `null`, not `undefined`. I would still want this property to use the default that is set in the new schema.

**Comment by lineus** [comment]
That's an interesting scenario, one that I personally have not encountered yet. #3340 seems to be doing something similar but instead of keeping the docs in the same collection, they're migrating to a new one. Is this an option for you?

**Comment by JonathanWbn** [comment]
Interesting! I like the idea. But I would like this migration to take place `as I update`. This would mean that given a Document id, I would have to know which version of the schema this is on, to get the correct version, right? Is there a smart way of using this technique to migrate 'on the fly'?

**Comment by lineus** [comment]
@JonathanWbn when I use mongoose to query mongodb ( findOne etc ), the document that gets returned is an instance of model. As far as I can tell, that instance of model is immutable. I can change values for keys that existed in the schema when it was compiled by mongoose.model() and save it, but not add new properties to it. Can you use a contrived example to demonstrate what you are doing with your migration code?

**Comment by JonathanWbn** [comment]
What I wanted to achieve was that `null` values would be overridden with default values when they have a Type that is not `Object`. Now I learned that `null` is a valid value, so the desired behaviour cannot be expected and that makes sense.

I would still be very appreciative of any idea on how to tackle this scenario, but closing since this is not a bug.
