### ISSUE TITLE
InsertMany promise rejections only get caught some of the time

### ISSUE THREAD

**Issue by Fire-Brand** [Automattic/mongoose#6147]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When parsing large CSV files to JSON (using [csvtojson](https://github.com/Keyang/node-csvtojson)), some promise rejection are not caught by `catch()` on `insertMany()` (E11000 duplicate key error ).
I can see that most duplicates errors rejections are caught, but sometimes one slips away and crashes the program.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
parseAndSaveCsvToMongo = (csvFilePath) => {
    return new Promise((resolve, reject) => {
        let docsArr = [];

        csvToJson({
            workerNum: 1,
            constructResult: false,
            maxRowLength: 65535
        }).fromFile(csvFilePath)
            .on('json', async (jsonObj) => {
                let doc = {
                    name: jsonObj.name, // 'Chris'
                    age: jsonObj.age, // 16
                    scroe: jsonObj.score // 93.234
                }

                if (!isNaN(doc.scroe)) { //don't save if the score is invalid
                    docsArr.push(doc);
                }

                if (docsArr.length % 10000 === 0) {
                    // insert to DB
                    await PeopleModel.insertMany(docsArr, { ordered: false }).catch(error => {
                        console.log(`insert error: ${error}`)
                    });
                    docsArr = [];
                }

            })
            .on('done', async () => {
                if (docsArr.length > 0) { // add the remaining docsArr
                    await PeopleModel.insertMany(docsArr);
                }
                resolve();
            })
            .on('error', (error) => {
                console.log(`parsing from file error: ${error}`);
                reject(error);
            });
    });
}
```
**What is the expected behavior?**
Expected behavior is that all promise rejections will be caught

**Please mention your node.js, mongoose and MongoDB version.**
node.js 8.9.4 , mongoose 5.0.6, MongoDB 3.6.4

**Comment by lineus** [comment]
@Fire-Brand when you run this against your input, and it crashes, are you seeing the standard deprecation warning for uncaught promises? It seems inevitable that your .on('done') is going to run at some point with docs remaining in docsArr and there is no .catch on that insertMany().

**Comment by Fire-Brand** [comment]
@lineus , you are absolutely right, spent so much time trying to make this work for mongoose 4 that, when i finally upgraded to 5, i missed that.
Thanks a lot!
