### ISSUE TITLE
populate is not a function

### ISSUE THREAD

**Issue by yuu2lee4** [Automattic/mongoose#6148]
when i use like this:
onst post = await Post.findById(id).populate('category');

if reported 'populate is not a function',

but when i use` find` or `findOne` insted:
const post = await Post.findOne({ _id: id }).populate('category', 'name'); 

it worked.

environment:
node:v8.9.3 mongoose: 5.0.6 macos10.13.3 koa:2.5.0 MongoDB shell version v3.4.0

**Comment by lineus** [comment]
Hi @yuu2lee4 I tried to duplicate your issue using this contrived example:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/test_db')
const Schema = mongoose.Schema
require('get-mongoose-versions').get('mongodb://localhost/test')
  .then(versions => console.log(versions))

const postSchema = new Schema({ title: String })
const Post = mongoose.model('posts', postSchema)
const post = new Post({ title: 'testing123' })

async function saveAndFind () {
  await Post.remove({}) // beware: this example clears db.test.posts
  const goodID = post._id
  const badID = '5a8855269c35d39c0a688738' // arbitrary id from a previous example
  const saved = await post.save()
  const findPostByGoodID = await Post.findById(goodID)
  console.log('existing id: ', findPostByGoodID)
  const findPostByBadID = await Post.findById(badID)
  console.log('nonexistent id:', findPostByBadID)
  mongoose.connection.close()
}

saveAndFind()
```
In the case of both existing and !existing ids, populate is a function for me that as expected returns the following results:
```
InspiredMacPro:5 lineus$ ./6148.js
{ mongooseVersion: '5.0.6',
  mongodbNativeVersion: '3.0.2',
  nodeVersion: 'v8.9.3',
  mongodbServerVersion: '3.6.2' }
existing id:  { _id: 5a8858bde899e1a0ce40da53, title: 'testing123', __v: 0 }
nonexistent id: null
InspiredMacPro:5 lineus$
```
Can you please provide a minimal but complete example that demonstrates the issue you're experiencing?

**Comment by varunjayaraman** [comment]
@yuu2lee4 i too am not able to reproduce this. Can you please confirm @lineus's script works or not for you?

**Comment by yuu2lee4** [comment]
It's so strange, i remember i has replied the topic.
It's my fault,I add a static method on model with the same name `findById`.
