### ISSUE TITLE
Cast to ObjectId failed for value "76198769" at path "_id" for model "Message"

### ISSUE THREAD

**Issue by saeedhei** [Automattic/mongoose#6151]
I have a normal _id for Message Schema and a custom Number _id For Person Schema,
How Should I Solve This Error when I use findById and save() in reference documents ?

**Person Schema:**
```js
const personSchema = new Schema({
  _id: Number,   // 76198769
  name: String,
});
```
**Message Schema:** 
```js
const messageSchema = new Schema({
  m: String
  personId: {type: Number, ref: 'Person'}, // 76198769
});
```
**Code:**
```js
const User = new Person({
    _id: msg.id, // 76198769
    name: msg.name,
 });
 const Message1 = new Message({
    personId: User.id, // 76198769
    m: 'Hello World',
  });
const promise = Person.findById(msg.id).exec();
.
.
.
```
**Error:**
`CastError: Cast to ObjectId failed for value "76198769" at path "_id" for model "Message"`

**Comment by markstos** [comment]
As seen in the Contributing guidelines, if you have questions about Mongoose, you should ask them on StackOverflow or Gitter: https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md You should include which version of Mongoose you are using.

**Comment by saeedhei** [comment]
Ok  @markstos , my version is upper than 5

**Comment by Redsandro** [comment]
![image](https://user-images.githubusercontent.com/1702193/49216199-c2af1e80-f3ca-11e8-853d-674fbc89a35c.png)

**Comment by markstos** [comment]
@Redsandro punishment by death is not that funny. Consider a more civil response in the future.
