### ISSUE TITLE
.create() returning plain object instead of model(function) in callback

### ISSUE THREAD

**Issue by ayoubelmoudni** [Automattic/mongoose#6153]
i'm creating a campground with Campground.create() and inside the callback i'm trying create and add a comment to that specific camground, can anyone help!!
Her's the code
`data.forEach(function (camp) {`
    `Campground.create(camp, function (err, addedCamp) {`
    `if (err) {`
    `console.log(err);`
    `} else {`
    `console.log(typeof (Campground)); // function`
    `console.log(typeof (camp)); // object`
    `// console.log(camp);`
    `Comment.create({`
           `text: 'Officia minim amet quis ipsum tempor deserunt.',`
           `author: 'Rob Ivan'`
     ` }, function (err, com) {`
     `if (err) {`
           `console.log(err);`
     ` } else {`
           `camp.comments.push(com); // can't push to undifind`
           `camp.save(); // can't call .save()`
           ` // console.log('Comment Added!!');`
         `}`
     ` });`
     `}`
    `});`
` });`

**Comment by markstos** [comment]
As seen in the Contributing guidelines, if you have a question about Mongoose, post it StackOverflow or Gitter: https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md You should include the version of Mongoose you are using.
