### ISSUE TITLE
Finding By ObjectId as String in a Collection

### ISSUE THREAD

**Issue by viniciusrc15** [Automattic/mongoose#6159]
**Do you want to request a *feature* or report a *bug*?**

Can be seen as a bug or feature, not sure

**What is the current behavior?**

Think that i have one array with Strings, as hashids.

Example of Data
```
{ 
status: 'active',
  users: [ '5a79a62e7875a14ef8a2a798' ]  
}
```

Then i search using mongo client and find results
```
db.sellers.find({ status: 'active', users: { '$in': [ '5a79a62e7875a14ef8a2a798' ] } })
```

When i find by mongo driver directly, i get results as well

```
  mongoose.connection.db.collection('sellers')
.find({ status: 'active', users: { '$in': [ '5a79a62e7875a14ef8a2a798' ] } })
.toArray( (e,c)=> console.log(' aqq',c));
  ```

But when i try to get using mongoose, i get NO results

```
  Seller.find({ status: 'active', users: { '$in': [ '5a79a62e7875a14ef8a2a798' ] } }, fields)
```

**What is the expected behavior?**

I expect to get results from moongoose the same way mongo driver and mongo shell.

The thing here might be related to the model , that has this schema

```
status: {type: String},
users: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User',unique: true, required: [true,'No user id found']}],
 ```

**Please mention your node.js, mongoose and MongoDB version.**

* mongoose : 4.11.6 or 4.13.x or 5.0.5
* MongoDB shell version: 3.2.19

**Comment by mariohmol** [comment]
If we have in the database the Id as a ObjectId, it works

``` { 
status: 'active',
  users: [ ObjectId('5a79a62e7875a14ef8a2a798') ]  
} ```

So mongoose its taking the schema and forcing to be an ObjectId.. wouldnt it be better if it works for string or objectid?

**Comment by vkarpov15** [comment]
This is by design. If your schema says `users` is an array of ObjectIds, mongoose will coerce your `$in` query to be an array of ObjectIds rather than strings. If you want it to work with strings, make `users` an array of strings. Or an array of mixed type `[{}]` to skip all casting.

**Comment by mariohmol** [comment]
Will an array of mixed types break the populate idea? or the deepPopulate as well?

**Comment by vkarpov15** [comment]
@mariohmol array of mixed types will work with populate as long as you keep `ref`. Open an issue if you find an issue with that.
