### ISSUE TITLE
Return a mongoose ValidationError from post findOneAndUpdate middleware

### ISSUE THREAD

**Issue by jeremyml** [Automattic/mongoose#6161]
I must use the post `findOneAndUpdate` middleware to do validation using multiple fields since the entire document is not available on the native `validator()` function.  I would like to be able to throw a mongoose Validation Error from inside the middleware like this

```
schema.post('findOneAndUpdate', result =>{
  if (result.docField == 'invalidValue'){
    throw new mongoose.Error.ValidationError('docField had an invalid value');
  }
});
```

Is there any way to do validation in the post `findOneAndUpdate` middleware?  Every time I throw an error from here the error is uncaught.  I would prefer a way to stop the update and throw a catchable `ValidationError` object.

**Comment by vkarpov15** [comment]
@jeremyml use [async post hooks](http://mongoosejs.com/docs/middleware.html#post-async), like:

```javascript
schema.post('findOneAndUpdate', (result, next) =>{
  if (result.docField == 'invalidValue'){
    return next(new mongoose.Error.ValidationError('docField had an invalid value'));
  }
  // ...
});
```

**Comment by jeremyml** [comment]
Perfect, thanks!
