### ISSUE TITLE
Add `findOneAndDelete()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6164]
Just like `findOneAndRemove()`, but always uses native `findOneAndDelete()` instead of `findAndModify()`

**Comment by CruiseMan** [comment]
@vkarpov15 What is the reason to name mongoose method `findOneAndRemove()` differently that native  mongodb `findOneAndDelete()` ?. Thank you.

**Comment by vkarpov15** [comment]
Because Mongoose had `findOneAndRemove()` long before MongoDB had
`findOneAndDelete()` :)
