### ISSUE TITLE
Array required validation is not checked

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#6176]
EDIT:
Found this: https://github.com/Automattic/mongoose/issues/1335#issuecomment-252129243
With the following schema I get the expected behaviour:
```js
{
  testArray: {
    type: [String],
    default: () => void 0,
    required: true
  }
}
```
But this should definitely show in `required` documentation

------------------------------------
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
An empty array is always saved in the database even if not provided upon creation.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a model with the following schema: 
```js
{testArray: {type: [String], required: true}}
```
or even this schema: 
```js
{
  testArray: {
        type: [String],
	required: function() {
		return Array.isArray(this.testArray) && this.testArray.length > 0;
  	}
  }
}
```
Save a model of this type:
```js
let obj = new Model({});
obj.save();
```
You will have a document in the database with an empty `testArray`

**What is the expected behavior?**
- the existence of the array in the creation `new Model({})` should be checked.
- Additionally, Mongoose implicitly casts array items and implicitly creates arrays when passing an primitives. This is not documented and leads to unexpected behaviour which I just found out about.

**Please mention your node.js, mongoose and MongoDB version.**
- Mongoose v5.0.7
- Node v6.9.2
- Mongo v3.4.0

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP

**Comment by varunjayaraman** [comment]
yup, this looks like a confirmed bug:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6176`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

  const schema = new mongoose.Schema({
    testArray: {
      type: [String],
      required: function() {
        return Array.isArray(this.testArray) && this.testArray.length > 0;
      }
    }
  });

  const Model = mongoose.model('Model', schema);

  console.log(await Model.create({}));
}
```

log output:
```
{ testArray: [], _id: 5aa063141b34a8df566fab98, __v: 0 }
```

**Comment by vkarpov15** [comment]
This behavior is correct and [documented](http://mongoosejs.com/docs/schematypes.html#arrays), you need to use `default: void 0` to get the behavior you want. Although unfortunately, we currently don't have a link to the schematypes guide from the docs, will add that.
