### ISSUE TITLE
Getting "MongoError: driver is incompatible with this server version" Error intermittently

### ISSUE THREAD

**Issue by rusiarohit** [Automattic/mongoose#6177]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
Getting *MongoError: driver is incompatible with this server version* as intermittent error.

**If the current behavior is a bug, please provide the steps to reproduce.**

It's intermittent. I saw at same moment or in retry it does the job  fine.
**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
node.js 6.9.1
mongoose 4.11.14
mongodb npm module 2.2.31
mongoDB server 3.2.19

**Comment by vkarpov15** [comment]
You shouldn't have a problem according to the [mongoose version compatibility guide](http://mongoosejs.com/docs/compatibility.html). Can you use `npm list | grep "mongo"` and post the output to check if you have some other dependency that's using an old version of mongodb?
