### ISSUE TITLE
Documentation - is emitIndexErrors still used?

### ISSUE THREAD

**Issue by isaackwan** [Automattic/mongoose#6181]
Apparently from #5910 this option is no longer used as errors are emitted regardless of settings now.

However on [the reference for Schema](http://mongoosejs.com/docs/api.html#model_Model.ensureIndexes) and [guide](http://mongoosejs.com/docs/guide.html#options) still both mentions `emitIndexErrors` although the anchor links are still there, causing confusion...

Can send PR if this is indeed true.

Cheers

**Comment by lineus** [comment]
it looks like the only occurrence of emitIndexErrors *in the source code itself* is in the schema.js jsdocs here:
```
InspiredMacPro:lib lineus$ find . -type f \! -regex '.*node_modules.*' \! -regex '.*docs.*' \! -regex '.*test.*' | xargs egrep 'emitIndexErrors'
./schema.js: * - [emitIndexErrors](/docs/guide.html#emitIndexErrors): bool - defaults to false.
InspiredMacPro:lib lineus$ 
``` 
If you have the cycles for a PR go for it. If not, let me know, I have some time later.

**Comment by vkarpov15** [comment]
Not used, we just had a couple vestigial references in the docs that were fixed. Thanks for the PR :+1:
