### ISSUE TITLE
Rename `History.md` to `CHANGELOG.md`

### ISSUE THREAD

**Issue by alexilyaev** [Automattic/mongoose#6183]
**Do you want to request a *feature* or report a *bug*?**
Just a small Git repo experience

**What is the current behavior?**
- Entering the repo on GitHub
- Clicking Releases to see version changes (nothing there)
- Looking for `CHANGELOG.md` file (a standard on GitHub)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Should rename `CHANGELOG.md`

Based on:  
http://keepachangelog.com/en/0.3.0/#what-should-the-change-log-file-be-named

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
Worth discussing more. What benefits does renaming have? Are there some tools that rely on the presence of 'CHANGELOG.md' vs 'History.md'?

**Comment by alexilyaev** [comment]
I'm not aware of tools that rely on the presence of `CHANGELOG.md`.

The benefits would be:

- Easier to find the changelog, as it is common, people expect to find such a file
- Consistency with other files (e.g. `README`, `LICENSE`, `CONTRIBUTING`)

**Comment by vkarpov15** [comment]
The website you linked to lists `History.md` as a reasonable alternative, so the former reason isn't sufficient to justify breaking all the already existing links that point to `History.md`. The latter reason also isn't sufficient. Thanks for the suggestion, we'll keep it in mind for the future.

**Comment by alexilyaev** [comment]
@vkarpov15 Actually, it states right after the alternatives list:  
"It’s a mess. All these names only makes it harder for people to find it."

The reason I opened this ticket is because it took me some time to find the changelog and I'm sure it'll happen to others.

**Comment by vkarpov15** [comment]
That's fair. The downside though is that all links that point to `History.md` will be broken if we change the file name, and I would imagine plenty of people end up on `History.md` from links

**Comment by alexilyaev** [comment]
@vkarpov15 Not sure how to find such links, didn't find any through Google.  
Do you have examples?

The last idea I have is to keep `History.md` only with some text linking to `CHANGELOG.md` and retire `History,md` after a period of time.

If you're still not convinced, that's fine, and you can close this ticket.

**Comment by vkarpov15** [comment]
The only place where I post these links is mongoose's [Twitter](https://twitter.com/mongoosejs) and sometimes our slack channel. I'm not entirely convinced that this change is worth making at this time. Perhaps if some tooling in the future makes this naming convention more compelling we'll make the change, but for now this just seems like there's no significant benefit in adopting this naming convention.

**Comment by alexilyaev** [comment]
Thanks for considering it.
