### ISSUE TITLE
Feature Request: Migration/Seed framework

### ISSUE THREAD

**Issue by ksmithut** [Automattic/mongoose#6188]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Although mongoose provides a nice abstraction for adding schema to a schema-less database, it is inevitable for a long-running project to not make any breaking changes to the schema, which requires migrations. There are various solutions provided for this in the user space, but it would be nice if this were a first-class concern of mongoose.

Something like [knex's migration api](http://knexjs.org/#Migrations) would be pretty neat. I've used [east](https://github.com/okv/east) with [east-mongo](https://github.com/okv/east-mongo) before, but this is just raw mongo queries bypassing mongoose typechecking, casting, and whatnot.

It's fine if this is purposefully not included in mongoose, but it just seems like an odd omission especially because having a schema is precisely why you need migrations. It would be nice to at least have some sort of section dedicated to migrations in the documentation, even if it just references one of the community migration solutions. I've seen far too many developers depend on mongoose for it's easy-to-use api because they don't need to setup `CREATE TABLE` statements and migration frameworks, but always run into the need for programmatically migrating data from one version of the schema to the next (adding/changing indexes, renaming collections, etc). Even if migration steps aren't desired, then at least something stating the complications of breaking changes to the api.

**Comment by vkarpov15** [comment]
This is a reasonable suggestion, but realistically not something we have time to implement. Mongoose is  meant to be a library, not an operational tool for managing your database.
