### ISSUE TITLE
connection url for model does not reflect all nodes in url

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6191]
Support question here, we have this:

```js
// debugging output, as json, at a url endpoint:
mongodbConnection: {
  host: "mngdb-cbt-x-01",
},
```

```js
// our db configuration
db: {
 uri: "mongodb://cdtdev:zzzzz@mngdb-cbt-x-01:27058,mngdb-cbt-x-02:27058,mngdb-cbt-x-03:27058/cdt_dev?authSource=cdt_dev&replicaSet=cbt-stg-rep",
 useMongoClient: true,
 autoReconnect: true,
 options: {
   autoReconnect: true,
   useMongoClient: true
},

```

the above `mongodbConnection` data is generated via: `host: [Model].db.host`,

so I simply wondering: is it only showing one of the nodes in the connection url string for a reason, when we log  [Model].db.host? or is it only connected to one node? how does that work?

what does it mean for the host to be:

`mngdb-cbt-x-01`

instead of:

`mngdb-cbt-x-01:27058,mngdb-cbt-x-02:27058,mngdb-cbt-x-03:27058`

?

thanks

**Comment by lineus** [comment]
Hi @ORESoftware , great question! Here is what I found:

Model.db.host is just the first parsed seed host from the url string and doesn't update when the topology changes.

### from lib/connection.js openUri()
```
      this.host = parsed.servers[0].host || parsed.servers[0].domain_socket;
      this.port = parsed.servers[0].port || 27017;
```

### running a test script to see if it updates after the primary replica changes:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
const Schema = mongoose.Schema

const H = [
  'localhost:27030',
  'localhost:27031',
  'localhost:27032'
]

const N = 'testing123'

const URI = `mongodb://${H.join(',')}/reptest?replicaSet=${N}`

const testSchema = new Schema({
  name: String
})

const Test = mongoose.model('test', testSchema)

console.log(URI)
mongoose.connect(URI).then(connected, notConnected)

function connected () {
  clh()
  setTimeout(clh, 30 * 1000) // during this timeout I issue rs.stepDown(1000) on primary
  function clh () {
    console.log(Test.db.host + ':' + Test.db.port)
  }
}

function notConnected (err) {
  console.error(err)
  return mongoose.connection.close()
}
```
### output:
```
InspiredMacPro:mongoose5 lineus$ ./6191.js
mongodb://localhost:27030,localhost:27031,localhost:27032/reptest?replicaSet=testing123
localhost:27030
localhost:27030
^C
InspiredMacPro:mongoose5 lineus$ 
```
The native driver/core libraries handle the events for replicasets and the actual work of finding the new primary. 
Here are the [native driver ](https://github.com/mongodb/node-mongodb-native) and the [core](https://github.com/mongodb-js/mongodb-core) repositories, if you're interested in learning more about them.

I hope that helps :)

**Comment by ORESoftware** [comment]
yeah that's good info thanks!
