### ISSUE TITLE
Add connection options changes to migrating_to_5.md

### ISSUE THREAD

**Issue by Owumaro** [Automattic/mongoose#6193]
Hi, I just updated from mongoose v4 to 5 on an old project.

I followed the guide migrating_to_5.md but it wasn't enough.

I had to look up in the docs to find these breaking changes :
http://mongoosejs.com/docs/connections.html#v5-changes

Since my project was using an old mongo url format it didn't work anymore.
It would be nice to add a link to this in the migration guide.

Thanks,

EDIT: the docs says you can have warning, but in my case I had errors :

> Connection to mongo server got error : Error: Unsupported host 'ip:27017/db,mongodb://user:password', hosts must be URL encoded and contain at most one unencoded slash

(in v4 I was using an url "mongodb://user:password@server/db,mongodb://user:password@server/db" which worked fine)

After fixing the url:

> Connection to mongo server got error : MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name

Then after fixing this it worked again.

So it's not just warnings.

**Comment by vkarpov15** [comment]
@Owumaro thanks for reporting, will fix asap
