### ISSUE TITLE
Error: Key must be a buffer

### ISSUE THREAD

**Issue by cezarlz** [Automattic/mongoose#6194]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Error: Key must be a buffer

This happens after I call the method `model.save`.

```js
user.validate(err => {
      if (err) return next(generateError(err.message, 400));

      user.save(err => {
        if (err) {
          const message =
            err.code === 11000 ? 'User already exist.' : err.message;

          return next(generateError(message, 400));
        }
....
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
Error: Key must be a buffer
  File "/app/helpers/errors.js", line 2, col 15, in generateError
    const err = new Error(message);
  File "/app/routes/auth.js", line 60, col 23, in user.save.err
    return next(generateError(message, 400));
  File "/app/node_modules/mongoose/lib/model.js", line 4046, col 16, in null.<anonymous>
    callback.apply(null, arguments);
  File "/app/node_modules/mongoose/lib/services/model/applyHooks.js", line 175, col 17, in null.<anonymous>
    fn(error);
  File "internal/process/next_tick.js", line 150, col 11, in process._tickCallback
```

**What is the expected behavior?**
Create a record.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v9.6.1
Mongoose:  4.13.6
mongodb: 2.2.33
mongodb-core: 2.1.17
mongod version: 3.4.9

**Comment by lineus** [comment]
Hi @cezarlz Can you please create a minimal example that duplicates the issue? Seeing your schema, the context of the Model.save(), and what you are actually saving are imperative for helping troubleshoot.

**Comment by varunjayaraman** [comment]
@cezarlz can you please produce a more reproducible example? I'm going to mark this as stale for now. We need something more actionable to investigate
