### ISSUE TITLE
`Reverse lean()` or `unlean()` on plain object after queried with lean()

### ISSUE THREAD

**Issue by Altiano** [Automattic/mongoose#6198]
**Do you want to request a *feature* or report a *bug*?**
Feature

Given the already constructed system where every document is `lean()`'ed, I have a requirement where I only need to turn some of documents to Full Mongoose instance after query. 

I don't see how the current API provide a solution for this.

**Comment by vkarpov15** [comment]
[Use `Model.hydrate()`](http://mongoosejs.com/docs/api.html#hydrate_hydrate)
