### ISSUE TITLE
can't set separate property in timestamps

### ISSUE THREAD

**Issue by dtanphat9388** [Automattic/mongoose#6201]
**Do you want to request a *feature* or report a *bug*?**
timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } // ok
timestamps: { createdAt: true updatedAt:  true }     //ok
timestamps: { createdAt: false updatedAt:  true }     //error
timestamps: { createdAt: true updatedAt:  false }     //error

**What is the current behavior?**
error at document.js:1008
  var pieces = path.split('.');

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
i want 
timestamps: { createdAt: true updatedAt:  false }     //ok

**Please mention your node.js, mongoose and MongoDB version.**
node 8.9.3
mongoose 5.0.6

note: i am living in VN, I do not speak English well, I hope you understand

**Comment by lineus** [comment]
Hi @dtanphat9388 

the timestamps option will always create both created_at and updated_at options. If you want to only have a createdAt timestamp on your documents, you can add a Date path in your schema that defaults to Date.now(). 

### Here is an example:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('./lib/test_db')
const Schema = mongoose.Schema

const testSchema = new Schema({
  name: String,
  createdAt: {
    type: Date,
    default: Date.now()
  }
})

const Test = mongoose.model('tests', testSchema)

const test = new Test({
  name: 'tester'
})

test.save().then((res) => {
  Test.findById(test._id, (err, doc) => {
    mongoose.connection.close()
    if (err) {
      return console.error(err)
    }
    return console.log(JSON.stringify(doc))
  })
}, (rej) => {
  mongoose.connection.close()
  return console.error(rej)
})
```
### output:
```
InspiredMacPro:mongoose5 lineus$ ./6201.js 
{"createdAt":"2018-03-04T13:56:44.152Z","_id":"5a9bfb1c7a8b771ef539030a","name":"tester","__v":0}
InspiredMacPro:mongoose5 lineus$ 
```
I hope that helps. Let me know if you have any further questions.

**Comment by dtanphat9388** [comment]
thank you very much for helps
