### ISSUE TITLE
Embedded discriminators in Embedded arrays dont work

### ISSUE THREAD

**Issue by pwhissell** [Automattic/mongoose#6202]
**Do you want to request a *feature* or report a *bug*?**
bug/feature I guess I'll let you choose

**What is the current behavior?**
Embedded discriminators in arrays work fine, I've used the example given at http://mongoosejs.com/docs/discriminators.html#embedded-discriminators-in-arrays

```
var eventSchema = new Schema({ message: String }, { discriminatorKey: 'kind'});
//var batchSchema = new Schema({ events: [eventSchema] }); <--- Simple Array would work
var batchSchema = new Schema({ events: [[eventSchema]] });    //<--- Embedded Array will not work
var docArray = batchSchema.path('events');

var clickedSchema = new Schema({
      element: {type: String, required: true}
});
var Clicked = docArray.discriminator('Clicked', clickedSchema); //<--- docArray.discriminator is not implemented

var PurchasedSchema = new Schema({
      product: {
        type: String,
        required: true
      }
};
var Purchased = docArray.discriminator('Purchased', PurchasedSchema));//<--- docArray.discriminator is not implemented

```

_note: I left out the option disabling the implicit id because it is not relevant to this issue_

However you can't have the discriminator applied to an array of array, because the  batchSchema.path('events') returns a SchemaArray which does not implement the "discriminator" function.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
There should be a way to use discriminators no matter how many dimensions an array has. Maybe

**Please mention your node.js, mongoose and MongoDB version.**
nodejs: v9.3.0
mongoose: v5.0.8

**Comment by pwhissell** [comment]
I found a workaround. You can use the "caster" property of the SchemaArray. It's value is a DocumentArray which exposes the discriminator function.
```
var eventSchema = new Schema({ message: String }, { discriminatorKey: 'kind'});
//var batchSchema = new Schema({ events: [[eventSchema]] });    <--- Embedded Array 
var schemaArray = batchSchema.path('events'); <--- Returns a schemaArray 

var clickedSchema = new Schema({
      element: {type: String, required: true}
});
//var Clicked = schemaArray .discriminator('Clicked', clickedSchema);<-- wont work
var Clicked = schemaArray .caster.discriminator('Clicked', clickedSchema);<--- works

var PurchasedSchema = new Schema({
      product: {
        type: String,
        required: true
      }
};
//var Purchased = schemaArray.discriminator('Purchased', PurchasedSchema)); <-- wont work
var Purchased = schemaArray .caster.discriminator('Purchased', PurchasedSchema));  <--- works
```

**Comment by vkarpov15** [comment]
Thanks for reporting, we'll implement this :+1:
