### ISSUE TITLE
question: does Mongoose support decimals and integers (MongoDB NumberDecimal, NumberLong, NumberInt)

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#6207]
Mongoose 5.0.8
MongoDB 3.6

in the docs I can still only find Number as SchemaType....

**Comment by marcelh-gh** [comment]
there is all kinds of contradictory information about this in _stackoverflow_ etc.
It would be nice if some clarification could be added to the official docs.

**Comment by marcelh-gh** [comment]
Apparently decimals are supported.

But the current docs (5.0.8) don't mention the schema type Decimal128. It was in the docs for version 4...

**Comment by lineus** [comment]
Hi @marcelh-gh 

check out [this article](http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-34-decimal.html). It's based on older versions of mongo*/node, but I don't believe any of the core ideas represented there have changed. I hope this helps!

**Comment by varunjayaraman** [comment]
it does look like the Decimal type isnt in the docs though: http://mongoosejs.com/docs/schematypes.html

**Comment by adamreisnz** [comment]
What about integers? Are there any plans to make a proper, first class integer schema type?
Currently even if the data we pass to Mongoose is an integer, it tends to convert it to decimal and it gets stored in the database as `9.0` instead of `9`.

**Comment by vkarpov15** [comment]
@adamreisnz we have plugins like [mongoose-int32](https://plugins.mongoosejs.io/plugins/int32) and [mongoose-long](https://www.npmjs.com/package/mongoose-long) for this. We don't have plans to make a first-class integer type currently.

What is your use case for specifically wanting an integer as opposed to a double?

**Comment by adamreisnz** [comment]
We were running into some data not being stored as expected, in particular after operations like `$inc`, where data ended up being decimal rather than integer.

My thinking was that if there were a native mongoose integer type it'd be easier to enforce the correct format without having to worry about these differences.

I will check out the plugins.

**Comment by vkarpov15** [comment]
In that case I'd recommend you try out mongoose-long. Let me know if you run into any issues.

**Comment by acomito** [comment]
What is the mongoose equivalent of NumberDecimal?

**Comment by vkarpov15** [comment]
@acomito the [`Decimal128` type](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-Decimal128)
