### ISSUE TITLE
When is mongoose to follow modern es2015+ style?

### ISSUE THREAD

**Issue by anlexN** [Automattic/mongoose#6212]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
no friendly to es2015+

**What is the expected behavior?**
i hope mongoose can be modern es2015+ style!
**Please mention your node.js, mongoose and MongoDB version.**
all are the latest

**Comment by varunjayaraman** [comment]
what do you mean? do you mean the API is not es6+ friendly? OR do you mean the code itself is not written in es6+ ?

**Comment by varunjayaraman** [comment]
How is the api not es6 friendly? Please clarify

**Comment by anlexN** [comment]
IE, don't  have arrow function, class, and so on.

**Comment by vkarpov15** [comment]
We're slowly switching over to using let and const, and arrow functions where appropriate, but we only dropped support for ES5 earlier this year so it is still a work in progress. If you're looking to contribute, feel free to use ES6.
