### ISSUE TITLE
Date is not storing correctly

### ISSUE THREAD

**Issue by iridiumsoft** [Automattic/mongoose#6222]
I have setup schema correctly for `created_on` to `Date` Type but for some reasons instead of storing ISODate format it store date object incorrectly like this:
`'date': {
        '_isAMomentObject': '1',
        '_isUTC': '',
        '_pf': {
            'empty': '',
            'unusedTokens': [  ],
            'unusedInput': [  ],
            'overflow': -2,
            'charsLeftOver': 0,
            'nullInput': '',
            'invalidMonth': '',
            'invalidFormat': '',
            'userInvalidated': '',
            'iso': '',
            'parsedDateParts': [  ],
            'meridiem': '',
            'rfc2822': '',
            'weekdayMismatch': ''
        },
......... 
`

when inserting new document i use `new Date()` I have tried different version of mongoose but no luck.
Anyone can help?
`mongoose: 5.6.0`
`Node: 9.4.0`
`MongoDB: 3.2.4`

**Comment by lineus** [comment]
@iridiumsoft have you tried Date.now() ? if that doesn't work, please include your schema and the code where you create and save a new document here and we'll help you figure it out.

**Comment by JasonCust** [comment]
@iridiumsoft I'd recommend posting this on SO and tagging it with "mongoose". Include your schema and the applicable code for creating and saving the record.

**Comment by varunjayaraman** [comment]
@iridiumsoft we cant do much more without a schema. Please post a schema so we can help resolve this issue
