### ISSUE TITLE
How to get intellisense for schema properties of a mongoose model

### ISSUE THREAD

**Issue by tommarien** [Automattic/mongoose#6226]
I've already posted this on https://groups.google.com/forum/#!searchin/mongoose-orm/document%7Csort:date/mongoose-orm/GEJjJ6Jr1gc/pGvddou4BgAJ but got no answer.

I am looking for a way to increase discoverability of mongoose models either trough jsdoc or trough added a model.d.ts file. I've found in langer projects i can become quite of a hassle to know which properties are on a specific model

``` js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var blogSchema = new Schema({
  title:  String,
  author: String,
  body:   String,
  comments: [{ body: String, date: Date }],
  date: { type: Date, default: Date.now },
  hidden: Boolean,
  meta: {
    votes: Number,
    favs:  Number
  }
});

var Blog = mongoose.model('Blog', blogSchema);
var blog = new Blog();
blog.title (jsdoc intellisense )
```

**Comment by lineus** [comment]
I have a very limited amount of experience with typescript, but I believe these are kept up to date:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose

**Comment by tommarien** [comment]
@lineus What i ment is in javascript not in typescript, i want intellisense on properties and methods of my models. I get intellisense if i add @types/mongoose on all build in methods but not on my model props and methods

**Comment by lineus** [comment]
sorry for the misunderstanding. I don't thing jsdocs will get you there ( not for schema properties anyway ). You'll probably need to roll your own typescript file. There's a guide for that [here](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

**Comment by tommarien** [comment]
Nevermind already found my solution, fyi

# blog.js
```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var blogSchema = new Schema({
  title:  String
});

var Blog = mongoose.model('Blog', blogSchema);
```
# blog.d.ts
``` ts
import { Document, Mode } from 'mongoose'

interface Blog extends Document {
    title: string;
}

let blog: Model<Blog>;

export = blog;
```

Now if you installed @types/mongoose you will get intellisense over your model properties

```js
const blog = new Blog();
blog.title = 'title' (with intellisense now)
```

**Comment by lineus** [comment]
awesome. I'll keep that in mind! thanks for sharing the answer you found @tommarien. Can you close this out when you get a chance? Thanks :)

**Comment by ilogicsoftwares** [comment]
> Nevermind already found my solution, fyi
> 
> # blog.js
> ```js
> var mongoose = require('mongoose');
> var Schema = mongoose.Schema;
> 
> var blogSchema = new Schema({
>   title:  String
> });
> 
> var Blog = mongoose.model('Blog', blogSchema);
> ```
> 
> # blog.d.ts
> ```ts
> import { Document, Model } from 'mongoose'
> 
> interface Blog extends Document {
>     title: string;
> }
> 
> let blog: Model<Blog>;
> 
> export = blog;
> ```
> 
> Now if you installed @types/mongoose you will get intellisense over your model properties
> 
> ```js
> const blog = new Blog();
> blog.title = 'title' (with intellisense now)
> ```
> 
> Maybe this can be added to documentation in some way ?

Awesome Solution My friend just what i was finding

**Comment by gabrieltong** [comment]
thanks @tommarien , what about `mongoose static methods` ?

**Comment by vkarpov15** [comment]
@gabrieltong if you write your own custom methods, you'll need to add your own typescript bindings.
