### ISSUE TITLE
can't handle error hooks in promise

### ISSUE THREAD

**Issue by dtanphat9388** [Automattic/mongoose#6230]
**Do you want to request a *feature* or report a *bug*?**
*bug*

```
let saveHooks = {
    pre: {
        onsave(next){
            return next(new Error("can't save"))
        },
        onerror(err){
            log("Error hooks: ",err.message)
        }
    }
}

personSchema.pre('save', saveHooks.pre.onsave, saveHooks.pre.onerror)
```

**What is the current behavior?**
```
Person.create({name: 'tanphat', age:18}, (err, person) => log(err.message, person)) // ok

Person.create({name: 'tanphat', age: 18})
    .then(person => log(person))
    .catch(err => log(err.message)) // error: mongoose can't catch error
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
mongoose can catch error in promise style

**Please mention your node.js, mongoose and MongoDB version.**
node, mongoose: latest verson

p/s: i am not speak English for gook, i hope you understand, thanks you

**Comment by vkarpov15** [comment]
I have never seen this syntax before:

```
personSchema.pre('save', saveHooks.pre.onsave, saveHooks.pre.onerror)
```

Where did you find this syntax?

Also, I don't understand what your issue is, can you please clarify?

**Comment by dtanphat9388** [comment]
i mean: error callback defined in pre hooks is not supported in catch promise

p/s: i am not speak English for gook, i hope you understand, thanks you

**Comment by vkarpov15** [comment]
I definitely do not understand at all. Please use the correct syntax for [error handling middleware as described in the docs](http://mongoosejs.com/docs/middleware.html)

**Comment by dtanphat9388** [comment]
thank you very much for reply
