### ISSUE TITLE
.save() doesn't throw error if not connected to database

### ISSUE THREAD

**Issue by beanilsson** [Automattic/mongoose#6231]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
If I run .save on a mongoose schema without being connected to the database, the callback is never called. I don't get any errors either. The process seems to be running forever. Also, if I'd run an empty .save(), `message.save()` before the actual save, I get the 200 response back. Not sure if that's the expected behaviour or not.

**If the current behavior is a bug, please provide the steps to reproduce.**
Controller:
```
    var message = new Message({
        content: "Much content"
    });
});

    // message.save(); <--- run this to get the 200 response
    message.save(function (err) {
        if (err){
            console.log('Something went wrong: ' + err);
            return res.status(500).send("Something went wrong: " + err);
        }
        return res.status(200).send("Saved!");
    });

```
Model:
```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
// Schema.set('validateBeforeSave', false); // to validate data manually

//mongoose.connect('mongodb://localhost:27017/userFeedback'); <--- don't connect to database
mongoose.set('debug', true);

var MessageSchema = new Schema({
    content: String
});

module.exports = mongoose.model('Message', MessageSchema);
```

**What is the expected behavior?**
Some sort of error message telling me that I'm not connected to the database and that the data will not be saved.

_I am using version 5.0.9 which is the latest version at this point._

**Comment by beanilsson** [comment]
Thanks for the clarification. Personally, I think that's a very strange default behaviour. But I do realize the benefits of it.

**Comment by vkarpov15** [comment]
It's a behavior that made a lot more sense when everybody used callbacks, but it's less useful now that we have async/await. As async/await becomes more prevalent we'll consider changing it.

**Comment by manastasiadi** [comment]
In what world is this acceptable default behaviour? Please fix.
