### ISSUE TITLE
Add examples using async functions as middleware to docs

### ISSUE THREAD

**Issue by h2non** [Automattic/mongoose#6235]
Async/await sugar operators are finally becoming a mainstream pattern to deal with async logic in JS.

The proposal here is to have first-class support for async functions that yield promises in Mongoose without forcing developers to abuse of wrappers or fancy abstractions.

Potential implementation ideas for a healthy convergence between existent interface and future ones without breaking changes could be:

- Dynamically infer if a middleware function has a callback argument via its arity. Cons: a potential source of FUD for developers, behavior misunderstanding.
- Infer if the given function is a generator and/or an async function signature (e.g: via `Function.prototype.toString()`.
- Verify if the function returns a `Promise` like object and handle it accordingly, potentially also inferring the function signature arity to remove handling ambiguity (I think this is already supported anyway)

I guess this should be considered to be implemented at `Kareem` package level.

Thanks.

**Comment by vkarpov15** [comment]
I believe we already support this in 5.x: http://thecodebarbarian.com/introducing-mongoose-5#promises-and-async-await-with-middleware . In general, we handle any function that returns a promise, no need to infer whether the function is async or just returns a promise.

**Comment by h2non** [comment]
Oh, cool. My fault. I wasn't able to find any example or reference in the docs. I have actually discovered the `Promise` support by reading the code afterward.

**Comment by vkarpov15** [comment]
Lack of docs is a problem, we'll fix that. Thanks for pointing that out.
