### ISSUE TITLE
mongoose @types for generic model?

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6238]
This issue regards the TS typings for mongoose. I have this:

![screenshot 2018-03-13 12 00 59](https://user-images.githubusercontent.com/11139560/37363898-4cf1e9f2-26b6-11e8-80ad-91bacf07fde6.png)

which is exactly:

```js
import * as mongoose from 'mongoose';

const ctrl = {
  update: function (q: object, data: typeof mongoose.Model, opts: Object, cb?: Function) {
      delete data['$$hashKey'];
      delete data['__v'];
      delete data._id;
      return Model.update(q, data, opts).exec(cb);
    }
};
```

is there someway to recognize the `$$hashKey` and `__v` fields of a generic mongoose Model?

**Comment by lineus** [comment]
@simonxca I hope you don't mind me CC'ing you here. Is this something you can answer?

**Comment by simonxca** [comment]
Could be an implicitAny issue.
What is the error message?

Are you able to add this to your tsconfig.json?
```js
{
    "compilerOptions": {
        "suppressImplicitAnyIndexErrors": true,
    }
}
```

**Comment by ORESoftware** [comment]
$$hashkey is an Angular1.x thing

I think this is what I am looking for:

`import {Document} from 'mongoose';`

an instance of Document should have __v and _id fields defined, etc.

**Comment by vkarpov15** [comment]
Can we move this issue to DefinitelyTyped or something like that? Mongoose doesn't have any official TypeScript bindings so this is off-topic for this repo.

**Comment by ORESoftware** [comment]
yeah np will close here thx
