### ISSUE TITLE
Bug Report: Can't use an array variable with enum

### ISSUE THREAD

**Issue by haydaralrikabi** [Automattic/mongoose#6239]
Hi,
The following enum validation is ignored:

> `myArray = ["one", "two", "three"];`
> 
> `const numbers = new mongoose.Schema({`
`range: { type: String, enum: myArray }`
`});`

However, using the array explicitly with enum works, e.g:
> `range: { type: String, enum: ["one", "two", "three"] }`

I searched up and down for a solution but I couldn't find one.

I am currently using:
Node.js@v9.8.0
mongoose@5.0.9
MongoDB@2.6.10

Thank you in anticipation.

**Comment by lineus** [comment]
Hi @haydaralrikabi 

### I tested this out on 5.0.9 with the following script:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const myArray = ['one', 'two', 'three']

const schema = new Schema({
  range: {
    type: String,
    enum: myArray
  }
})

const Test = mongoose.model('test', schema)

const test1 = new Test({
  range: 'one'
})

const test2 = new Test({
  range: 'two'
})

const test3 = new Test({
  range: 'three'
})

const test4 = new Test({
  range: 'four'
})

const promises = [test1.save(), test2.save(), test3.save()]

function resolve (results) {
  mongoose.connection.close()
  console.log(results)
  return test4.save((err, doc) => {
    if (err) {
      return console.error('validation works as expected.')
    }
  })
}

function reject (error) {
  mongoose.connection.close()
  return console.error(error)
}

Promise.all(promises).then(resolve, reject)
```
### output:
```
InspiredMacPro:mongoose5 lineus$ ./6239.js 
[ { range: 'one', _id: 5aa83a9c0351e966ef69c8a3, __v: 0 },
  { range: 'two', _id: 5aa83a9c0351e966ef69c8a4, __v: 0 },
  { range: 'three', _id: 5aa83a9c0351e966ef69c8a5, __v: 0 } ]
validation works as expected.
InspiredMacPro:mongoose5 lineus$ 

```
Am I doing something different from what you have in your code? try and run my example and see if it still doesn't work for you. Alternatively you could provide your entire script and I'm happy to take a look.

**Comment by haydaralrikabi** [comment]
Here is the full code. Basically, what it does is checking if an inserted video title has a valid genre's category in the database. Genres and videos are saved in two different collections.
There may be a better way to write this code, but my point is about using _enum_ with _gendersList_.

I am actually creating the array on the fly, from the database. I've noticed that when I create the schema inside the same function as the dynamic array then there is no issue at all.
It is only when the schema is outside the function of the dynamic array that the issue happens.

**This code works** because _videoSchema_ and _golbal.Video_ are in the same function as the dynamic array _genresList_.
```javascript
const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');

const genresList = [];

const genresSchema = new mongoose.Schema({ cat: String });
const Genre = mongoose.model('Genre', genresSchema);

const getGenres = async function(){
    const data = await Genre.find();

    for (index in data) {
        genresList.push(data[index].cat);
    }

    const videoSchema = new mongoose.Schema({
        title:{
            type:String,
            required:true,
            minlength:2
        },
        genre:{
            type:String,
            required:true,
            minlength:3,
            enum:genresList
        }
    });

    global.Video = mongoose.model('Video', videoSchema);
}

getGenres();

router.post('/', async (req, res) => {
    let video = new Video({
        title: req.body.title,
        genre: req.body.genre
    });
    video = await video.save().catch(err => res.send(err.message));
    res.send(video);
});

module.exports = router;
```
I wonder if there is a way to use the _genresList_ array as the value for _enum_ if the validation is happening outside the function where _genresList_ is updated.
I feel like the schema is created before the array is updated in the function _getGenres_.

**Comment by lineus** [comment]
@haydaralrikabi 

the fact that the genresList requires an async operation to get the data is going to 
mean you're always going to need to handle that with async/await or a promise that doesn't
create the schema until the genre data has been retrieved. 

The only other option that I can think of (that wouldn't be async or blocking) would be to store hard-coded genres in the array instead of generating them dynamically. 

Any other choice, a mongodb call, an http call, a file on disk, they're all going to block on some kind of I/O. It might be worth testing out which option is faster, but either way, the array will need to be populated by the time the schema gets compiled.

**Comment by haydaralrikabi** [comment]
Thank you very much for your help.

**Comment by lineus** [comment]
my pleasure @haydaralrikabi :)

Can you close this when you have a sec? Thanks!
