### ISSUE TITLE
Get decent TS typings for model/models using basic Mongoose API

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6241]
This is probably a feature request - specifically to improve `@types/mongoose` ...

I am seeing this:

![screenshot 2018-03-13 17 23 49](https://user-images.githubusercontent.com/11139560/37376790-5003770a-26e3-11e8-9519-f204cc5262c3.png)

Mongoose typings don't know what either err or models is..
Shouldn't mongoose have a decent understanding of what interface the callback should have?

shouldn't the callback basically look like this?

```js
import {Model} from 'mongoose';
type MongooseCB = (err: Error, models: Array<Model<any>>) => void;
```

is there someone that can improve the TS typings for this?

**Comment by lineus** [comment]
Hi @ORESoftware the type definitions are maintained by DefinitelyTyped [issues here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues). You might want to check there for existing issues, and potentially raise a new one, or file a PR there if you have the time. The mongoose type are [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose). I hope that helps :)

**Comment by ORESoftware** [comment]
Thanks, I solved it like so:

```js
'use strict';

import {Schema, Document, model, Model} from 'mongoose';
import {CDTBase, CDTBaseModel} from "../base-model";

/////////////////////////////////////////////////////////////////////

const rolesSchema = new Schema(Object.assign({

  _id: {
    type: Schema.Types.ObjectId,
    required: true,
    auto: true
  },

  key: {
    type: String,
    required: true
  },

  name: {
    type: String,
    required: true
  },

  active: {
    type: Boolean,
    default: true
  }

}, CDTBase));


rolesSchema.index({name: 1}, {unique: true, background: false});
rolesSchema.index({key: 1}, {unique: true, background: false});

export interface CDTModel extends CDTBaseModel, Document{
  key: string,
  name: string,
  active: boolean,
}

export const cdtmodel = model<CDTModel>('Role', rolesSchema, 'roles');
```

**Comment by ORESoftware** [comment]
unfortunately it requires a separate TS interface (CDTModel), but other than that, not so bad.

**Comment by lineus** [comment]
Thanks for posting your resolution here! If you're all set, can you close this?

**Comment by ORESoftware** [comment]
yeah np sounds good thx
