### ISSUE TITLE
mongoose findone return undefine

### ISSUE THREAD

**Issue by zeteticl** [Automattic/mongoose#6243]
I have a bot. It can input some text and return some word.

I would like to use MongoDB. Because Heroku can't store data. 

So I add function.js that use mongoose.

     console.log('data.functionswitch = ' + data.functionswitch);  
console log is work fine. It can reply what i want.
     
     return data.functionswitch;
but  return data.functionswitch  only return undefined when i call it in input.js/.

I have try async/await.

But it only stops working. 

How can I improve it and make it work? Thank you.

-

-
function.js

    function switchfind(id, name) {
    mongodb.functionSwitch.findOne({ groupid: id, functionname: name }, function (err, data) {
        if (err) {
            console.log(err);
            return null;
        }

       else if (data == null) {
            console.log("No record found")
            return null;
        }
        else
        console.log('date = ' + data);
        // { _id: 5aa15sf,groupid: '002', functionname: 'luck', functionswitch: '0', __v: 0 }
        console.log('data.functionswitch = ' + data.functionswitch);
        //data.functionswitch = 0
        return data.functionswitch;
    })
    };

input.js

    function parseInput(input) {
	_isNaN = function (obj) {
		return isNaN(parseInt(obj));
	}
	var inputStr = input.message.text;
	let msgSplitor = (/\S+/ig);
	let mainMsg = inputStr.match(msgSplitor); //
	let trigger = mainMsg[0].toString().toLowerCase(); 
	console.log(input);
	//switchfind

	if (exports.mongoose.switchfind(mainMsg[1], mainMsg[2]) == 0) {
		return null;
	}
	else {
    //SOME CODE
	}
    }

**Comment by lineus** [comment]
Hi @zeteticl. I assumed that you are using mongoose 5, If you're on an earlier version let me know and I'll update my answer for that version. 

Here is a basic implementation of what you're trying to do:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  what: String,
  when: Date
})

const Test = mongoose.model('test', schema)

function getData () {
  return Test.findOne({})
}

async function run () {
  let data = await getData()
  console.log(data)
}

run()
```
output:
```
mongoose5: ./6243.js 
{ _id: 5aa92cf5e18f481ed3475abf,
  what: 'customized',
  when: 2017-11-08T00:10:06.106Z,
  __v: 0 }
^C
mongoose5: 
```
For future reference, there are several communities of folks who are happy to help, 
[slack](https://mongoosejsteam.slack.com/messages/C2CA1AWQP/details/)
[gitter](https://gitter.im/Automattic/mongoose)
[stackoverflow](https://stackoverflow.com/questions/tagged/mongoose)

let me know if you have any questions.

**Comment by varunjayaraman** [comment]
does the document exist? Can we see the schema?
