### ISSUE TITLE
Overloaded schema fails to trigger due to kareem update to 2.0.5

### ISSUE THREAD

**Issue by gforge** [Automattic/mongoose#6250]
In the `mongoose-delete` plugin (https://github.com/dsanel/mongoose-delete/issues/36) the tests started failing when `kareem` package was updated to version 2.0.5. After some debugging it turns out that this only occurs when passing a callback function to the the overloaded function. I've created a test case that fails on the last assertion:

```
it('statics', async (done) => {
  var called = false;
  var filter_plugin = function(schema) {
    schema.add({ filter: Boolean })
    schema.statics.count = function() {
      called = true;
      return mongoose.Model['count'].apply(this, arguments).where('filter').eq(true);
    }
  }

  var TestSchema = new Schema({ name: String });
  TestSchema.plugin(filter_plugin);
  var TestModel = db.model('PluginTests', TestSchema);

  await TestModel.create(
      [
          { name: 'Obi-Wan Kenobi', filter: true},
          { name: 'Darth Vader'},
          { name: 'Luke Skywalker', filter: true}
      ]);

  assert.equal(called, false);
  var count = await TestModel.count();
  assert.equal(called, true);
  assert.equal(count, 2);

  return TestModel.count(function (err, count) {
    assert.equal(called, true);
    assert.equal(count, 2);
    done();
  })
});
```

The error is due to this commit: https://github.com/vkarpov15/kareem/commit/5afc5b9ab34f82702c8cd3a700c0f67fdfe4c86d I'm not sure though if where this bug belongs. Since the failure above doesn't use hooks, I've decided to first post the issue here. 

A full standalone test-file is available in my fork: https://github.com/gforge/mongoose/blob/master/test/schema.plugins.test.js

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP :+1:
