### ISSUE TITLE
feature request - allow users to plugin caching functionality

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6252]
Not sure if this functionality exists or not...
We all have the following methods on models etc:

```
User.find()
User.findOne()
etc etc.
```

Our team is going to try to implement caching on our server for collections that are finite in size. The problem is our codebase has all sorts of random calls to read/find models from the db.

One thing we could do, is monkey-patch the Model methods that read from the db, something like this:

```js
const findOne = User.findOne;
User.findOne = function(q, cb){
   const args = Array.from(arguments);
    searchForUserInCache(q, function(err, model){
       if(model) return cb(null, model);
       findOne.apply(User, args);
   })
}
```

but doing this monkey patching is definitely a horrible idea - is there some sort of way we can implement caching with Mongoose - is there a way to plugin some sort of caching functionality without monkey-patching etc?

**Comment by vkarpov15** [comment]
Right now you would have to use [query middleware](http://mongoosejs.com/docs/middleware.html), so `pre('find')`, `pre('findOne')`, etc. if you want to implement your own caching. I haven't used any of the caching plugins out there so I don't have any suggestions for plugins.
