### ISSUE TITLE
The field 'rooms' must be an array but is of type object in document

### ISSUE THREAD

**Issue by akashbharadwaj** [Automattic/mongoose#6253]
My Schema is like this:
var hotelSchema = new mongoose.Schema({
    
    name : {
        type : String,
        required : true
    },
   // name : String,
    location : String,
    locationCode : String,
    rating : Number,
    description : String,
    services : [String],
    photos : [String],
    rooms : [
        {
            roomType : String,
            number : Number,
            description : String,
            photos : [String],
            price : Number

        }
    ],
    flagDeleted : Boolean
});

mongoose.model('Hotel',hotelSchema,'hotelsData');
//query
Hotel.findOneAndUpdate(
                { "name": name },
                {
                    "$push": {
                        "rooms": {
                            "roomType": req.body.type,
                            "number": req.body.number,
                            "description": req.body.description,
                            "photos": req.body.photos,
                            "price": req.body.price
                        
                        }
                    }
                },
                { "new": true }, // return the modified document
                function(err, roomsHotel) {
                    if (err) {
                        console.log('NO SUCH rooms');
                        res.json(err);
                    } else {
                        console.log(roomsHotel); // modified document
                    }
                }
            );
            }
I am getting this error : 'The field 'rooms' must be an array but is of type object in document'

**Comment by lineus** [comment]
@akashbharadwaj the formatting is very hard to read on your issue report. Generally speaking, if you declare your schema with square brackets around a value, then the document validation will expect an array to be assigned to that property, and that the elements match the type specified in the schema. If this doesn't clear up your issue, please feel free to include a comment with your complete schema, and either the actual object you're using to create a new document with, or at least a sample object that has been sanitized ( sensitive data redacted ).

**Comment by varunjayaraman** [comment]
I'm not able to reproduce this, here is a simple repro script:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-6253`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`);

  const schema = new mongoose.Schema({
    rooms: [{
      name: String
    }]
  });

  const Model = mongoose.model('Model', schema);

  const doc = await Model.create({
    rooms: [{ name: 'test-0' }]
  });

  await Model.findByIdAndUpdate(doc._id, {
    $push: {
      rooms: { name: 'test-1' }
    }
  });

  console.log(await Model.findById(doc._id));
}
```

This logs out without error:

```
{ rooms:
   [ { _id: 5abaa307ea32d8ac0585b36b, name: 'test-0' },
     { _id: 5abaa307ea32d8ac0585b36c, name: 'test-1' } ],
  _id: 5abaa307ea32d8ac0585b36a,
  __v: 0 }
```

**Comment by varunjayaraman** [comment]
@akashbharadwaj can you see if the error is producible in that script i created?
