### ISSUE TITLE
How can I keep DRY in query chain, for example, .populate('address', 'field1 field2' )?

### ISSUE THREAD

**Issue by janckerchen** [Automattic/mongoose#6254]
I want to populate address filed after all CRUD action,  should I repeat '.populate('address', 'field1 field2' )'  in all of them?

```
Account.find().populate('address', 'field1 field2' )
Account.update(...)..populate('address', 'field1 field2' )
Account.delete(id)..populate('address', 'field1 field2' )
Account.create(...)..populate('address', 'field1 field2' )
```

**Comment by lineus** [comment]
@janckerchen .populate can also take an object. You can create a default population object and re-use it.

### example:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const citySchema = new Schema({
  name: String
})

const stateSchema = new Schema({
  name: String
})

const testSchema = new Schema({
  name: String,
  address: {
    city: {
      type: Schema.Types.ObjectId,
      ref: 'city'
    },
    state: {
      type: Schema.Types.ObjectId,
      ref: 'state'
    }
  }
})

const City = mongoose.model('city', citySchema, 'city')
const State = mongoose.model('state', stateSchema, 'state')
const Test = mongoose.model('test', testSchema)

const tucson = new City({
  name: 'Tucson'
})

const arizona = new State({
  name: 'Arizona'
})

const test = new Test({
  name: 'Lute',
  address: {
    city: tucson._id,
    state: arizona._id
  }
})

async function run () {
  await City.remove({})
  await State.remove({})
  await Test.remove({})
  await tucson.save()
  await arizona.save()
  await test.save()
  const defPop = {
    path: 'address.city address.state',
    select: 'name -_id'
  }
  await Test.findOne().populate(defPop).exec((err, doc) => {
    if (err) { return console.error(err) }
    console.log(doc)
  })
  await Test.findOneAndUpdate({ _id: test._id }, { name: 'Sean' }, { new: true })
    .populate(defPop)
    .exec((err, doc) => {
      if (err) { return console.error(err) }
      console.log(doc)
      return mongoose.connection.close()
    })
}

run()
```
 ###output:
```
issues: ./6254.js 
{ address: { city: { name: 'Tucson' }, state: { name: 'Arizona' } },
  _id: 5ab4c20a2736f33049a9cc25,
  name: 'Lute',
  __v: 0 }
{ address: { city: { name: 'Tucson' }, state: { name: 'Arizona' } },
  _id: 5ab4c20a2736f33049a9cc25,
  name: 'Sean',
  __v: 0 }
issues: 
```

**Comment by varunjayaraman** [comment]
@lineus i think @janckerchen 's request was to dry up the `populate` call across various routes.

You can do this @janckerchen with a model static and use that model static instead of the default mongoose ones.

Another thing to consider: if you are always going to need the `address`, one of the benefits of mongodb is that you can just nest it in the document. If its a 1 to many association that may not be ideal, but based on your use case you might consider avoiding a populate altogether and just putting it in your schema

**Comment by vkarpov15** [comment]
If you always want to populate `address` you can just use [the mongoose-autopopulate plugin](https://www.npmjs.com/package/mongoose-autopopulate) to automatically populate using your preferred options. This works great if you rarely need to load an account without calling `populate('address')`.

You can also use [query helpers](http://mongoosejs.com/docs/guide.html#query-helpers) to encapsulate `populate('address', 'field1 field2' )` into a helper function like `.populateAddress()` so you don't have to copy the fields repeatedly. This works if you mongoose-autopopulate feels a little too heavy-handed.
