### ISSUE TITLE
MongoError: add index fails, too many indexes causes Uncaught Exception Error

### ISSUE THREAD

**Issue by Hyperblaster** [Automattic/mongoose#6255]
Hey there, I recently updated our version of mongoose from v3 to v5.
All looks good, except we are currently at our limit of indexes for a certain collection, as i understand it mongoose on initialization creates indexes for schemas with 'unique'/'sparse' attributes.

All good, but instead of throwing a warning, mongoose crashes the entire process with an Uncaught Exception Error, Is there anyway to suppress or handle this silently? Seems a bit extreme.

**Comment by vkarpov15** [comment]
Add a handler to `Model.on('error')`, or you can [set the `autoIndex` option to `false` for your schema](http://mongoosejs.com/docs/api.html#schema_Schema) if you just want to skip building indexes for this one model because you know it'll fail anyway.

```javascript
new Schema({ /* definition */, { autoIndex: false });
```
