### ISSUE TITLE
how to initiate connection error event

### ISSUE THREAD

**Issue by dudilugasi** [Automattic/mongoose#6258]
i have some logic i want to test inside connection error callback.
how can i initiate the connection error event in order to test my logic?
var connection = mongoose.createConnection(conn.url, options);
connection.on("error", function (err) {
    console.log("connection error")
});

**Comment by lineus** [comment]
hi @dudilugasi connection error is going to be emitted on initial connection, so pointing createConnection at a port or a host with no mongodb server will work.

### example
```
#!/usr/bin/env node
'use strict'

const noMongoOnPort = 'mongodb://localhost:27999/test'
const mongoose = require('mongoose')

const conn = mongoose.createConnection(noMongoOnPort)
conn.catch(() => { })

conn.on('error', (err) => {
  console.error(`${err.name}: ${noMongoOnPort}`)
})
```
### output:
```
issues: ./6258.js 
MongoNetworkError: mongodb://localhost:27999/test
^C
issues: 
```

**Comment by dudilugasi** [comment]
ahh so if the connection is closed after connection it will not emit an error event?

**Comment by lineus** [comment]
That is correct. It will however eventually emit reconnect and reconnectFailed events depending on your reconnect [connection options](http://mongoosejs.com/docs/connections.html#options).

**Comment by dudilugasi** [comment]
ok thank you for the help! this issue can be closed now
