### ISSUE TITLE
Expires index issue

### ISSUE THREAD

**Issue by akaNightmare** [Automattic/mongoose#6259]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I have a schema/model with expires field (1hour), and when I changed it to another value (for instance: 7200), Mongoose does not override it and the previous configuration still exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const revokedAuthTokenSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
        },
        jti: {
            type: String,
            require: true,
        },
        iat: {
            type: Date,
            require: true,
            expires: 3600,
        },
    },
    {
        collection: 'revoked_auth_tokens',
        timestamps: null,
    },
)
    .index({ user: 1 })
    .index({ jti: 1 }, { unique: true });
```
**What is the expected behavior?**

**Please mention your node.js, mongoose, and MongoDB version.**
MongoDB: 3.6
Mongoose: 5.0.10

**Comment by lineus** [comment]
@akaNightmare can you comment with a specific example of what you mean by change it to another value? 

From looking at the [docs](https://docs.mongodb.com/manual/core/index-ttl/index.html#restrictions), once the index is created with the expiresAfterSeconds option, only running collMod with the index collection flag will change it. The native driver and mongoose offer convenience methods to drop and create indexes, but I couldn't find anything that would allow you to change it.

**Comment by akaNightmare** [comment]
@lineus I have a config for `expires` field in `revoked_auth_tokens` collection, sometimes I need to change it, but mongoose cannot to do that, and I have to change it manually.

**Comment by vkarpov15** [comment]
@akaNightmare that's because the `expires` field creates a [TTL index](https://docs.mongodb.com/manual/core/index-ttl/), so unfortunately you need to [drop the index in the mongodb shell](https://docs.mongodb.com/manual/reference/method/db.collection.dropIndex/) before mongoose will be able to successfully create the new index. In general, mongoose doesn't delete old indexes for you, so you still need to manage indexes on your own.
