### ISSUE TITLE
Remove usage of deprecated Buffer API

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6260]
Re: https://github.com/nodejs/node/issues/19079#issuecomment-374635556

**Comment by Fonger** [comment]
#6829 has fixed this.

If we drop support for node.js 4 and node.js 5 in a future release,
we can simply remove `safe-buffer` and everything still work.

**Comment by Flarna** [comment]
I still get this warning via bson module used by mongoose, seems this is fixed in bson since 4.x but mongoos2 requires 1.1.0

**Comment by vkarpov15** [comment]
That is because the mongodb driver still depends on bson 1.1 as well. When they start using bson 4.x, we will too
