### ISSUE TITLE
Default getter/setter for virtual fields

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#6262]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature description**
I find myself needing to type the following often, when I want to append a non-persistent virtual field to a model:

```js
CustomerSchema.virtual('totalValue')
  .set(function(totalValue) {
    this._totalValue = totalValue;
  })
  .get(function() {
    return this._totalValue;
  });
```

This is fine if you need to do it once or twice, but when you have a lot of those properties it begins to feel a bit verbose.

It'd be create if this could be the default for a virtual field, so that I could simply write:

```js
CustomerSchema.virtual('totalValue');
CustomerSchema.virtual('numOrders');
//etc
```

The default getter/setter would then be implied if you don't provide any.

**Comment by lineus** [comment]
Hi @adamreisnz You can achieve this now with a schema plugin. Here's an example of a schema plugin applied globally to all schemas, but you can also add them to individual schemas. The [docs are here](http://mongoosejs.com/docs/plugins.html).

### totalValue.js
```
'use strict'

module.exports = function (schema) {
  schema.virtual('totalValue')
    .set(function (totalValue) {
      this._totalValue = totalValue
    })
    .get(function () {
      return this._totalValue
    })
}
```

### index.js
```
#!/usr/bin/env node
'use strict'

const totalValue = require('./totalValue')
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
mongoose.plugin(totalValue)
const Schema = mongoose.Schema
const sOpts = { getters: true, virtuals: true }

const trinketSchema = new Schema({ name: String }, { toObject: sOpts })
const gadgetSchema = new Schema({ name: String }, { toObject: sOpts })

const Trinket = mongoose.model('trinket', trinketSchema)
const Gadget = mongoose.model('gadget', gadgetSchema)

const bobble = new Trinket({
  name: 'necklace'
})

const doodad = new Gadget({
  name: 'Bluetooth Toilet Flusher'
})

bobble.totalValue = 8
doodad.totalValue = 'priceless'

console.log(bobble)
console.log(doodad)
process.exit(0)
```
### output:
```
6262: ./index.js 
{ _id: 5ab4ea215621af4b61284544,
  name: 'necklace',
  totalValue: 8,
  id: '5ab4ea215621af4b61284544' }
{ _id: 5ab4ea215621af4b61284545,
  name: 'Bluetooth Toilet Flusher',
  totalValue: 'priceless',
  id: '5ab4ea215621af4b61284545' }
6262: 
```

**Comment by adamreisnz** [comment]
No I understand that, but that's not the use case or problem I was trying
to solve.

My problem is having to create multiple simple getter/setter properties on
a single schema, which is quite verbose currently.

Hence the idea of a simple default setter / getter for every new virtual
property.

**Comment by lineus** [comment]
You're right. My example sucked.  I got so excited about the possibilities of what someone could do to automate adding virtuals to a schema... Then in order to not get carried away, I re-focused instead on the fact that it was possible at all and lost sight of the point of your feature request in the process. Apologies if I came off as shooting your idea down, I wasn't.

**Comment by adamreisnz** [comment]
No worries, no offence taken :)

**Comment by varunjayaraman** [comment]
i don't think it's a good solution to default to using underscore-prefixed private properties like that. That seems a bit too opinionated on mongoose's part. Some people abhor that convention and others like it, i think it's a slight inconvenience but overall better for the library to not inject magic like that

**Comment by adamreisnz** [comment]
I didn't mean to recommend that we use underscores, if there's a better way of implementing it I'm all for it! 

This is my default approach though to creating simple getter/setter virtual properties, as it's easiest and simplest. Yet, if you have to create several properties like that it just feels quite verbose.

**Comment by lineus** [comment]
@adamreisnz I edited my example above to be more relevant ( I hope! ).

**Comment by adamreisnz** [comment]
Interesting idea, but I don't like having to apply the plugin afterwards. I generally define all general plugins globally for all schema's, in advance of defining the schema's. So it kind of moves the problem to having to remember to apply this plugin to each schema after setting up virtuals.

But good effort, I might look at hacking it into Mongoose in some way if I find the time.

**Comment by lineus** [comment]
I was actually thinking about this earlier, so I decided to test it when I had time tonight. I just assumed that because the plugin was relying on the virtuals being declared already, that it would have to run afterwards. I was wrong. 
**It turns out that this works just fine as a global plugin.**

**Comment by vkarpov15** [comment]
I understand @varunjayaraman 's concerns about having an opinionated default, but to work around that we could also support `CustomerSchema.virtual('totalValue', '$totalValue')` or some similar syntax. Thoughts?

**Comment by adamreisnz** [comment]
Yes, that could work, to specify the underlying field. But I still think a default could be used, as long as the likelihood of it clashing with another property is very small, e.g. something verbose as `$__private_totalValue`. As long as it's dynamically generated under the hood, who cares really how the properties are called? And it would save further keystrokes and verbosity when setting up simple virtuals.

**Comment by vkarpov15** [comment]
Yeah that's fair. I would probably err on the side of just using `$totalValue` by default, but you're right, it isn't really a big deal unless the property clashes, in which case we would be better off nesting these virtual properties underneath a separate object.

**Comment by vkarpov15** [comment]
5.2.0 will add getters/setters for you if there aren't any getters or setters defined. By default, the default virtual will be equivalent to:

```javascript
CustomerSchema.virtual('totalValue');

CustomerSchema.virtual('totalValue2') // Equivalent getters/setters
  .set(function(totalValue) {
    this.$totalValue = totalValue;
  })
  .get(function() {
    return this.$totalValue;
  });
```

**Comment by adamreisnz** [comment]
That's great, thanks for that 👍
