### ISSUE TITLE
Allow same array entry in different documents

### ISSUE THREAD

**Issue by hemor** [Automattic/mongoose#6264]
In my schema, I have a property, keywords, which is an array. Mongoose automatically prevents entering the same array value in different documents. What I want to achieve is to prevent the same value from being entered twice in the keywords array of the same document but other documents should be able to reuse the entry i.e uniqueness should be per document only.

I already checked the documentation, the github issues and I did a lot of google search but I couldn't find anything on how to achieve that which is why I'm creating a new issue.

I also added unique: false, hoping that will totally disable the unique validation but that doesn't work either.

This is the part of schema that has the validation issue

keywords: [{
      type: String,
      required: true,
      unique: false
}]

Node JS version - 8.9.4
MongoDB version - 3.6.3
Mongoose version - 5.0.7

**Comment by lineus** [comment]
@hemor I tried to duplicate this on mongoose@5.0.7, but it seems to work for me. Can you comment with a minimal but complete example that demonstrates the issue you're seeing?

### 6264.js :
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  post: String,
  keywords: [{
    type: String,
    required: true,
    unique: false
  }]
})

const BlogPost = mongoose.model('blog', schema)

const kw = []
for (let i = 0; i < 10; i++) {
  kw.push('Meh')
}

const post1 = new BlogPost({
  post: 'Ten words on my trip to Cleveland',
  keywords: kw
})

const post2 = new BlogPost({
  post: 'Ten reasons why I will not move to Cleveland',
  keywords: kw
})

async function run () {
  await BlogPost.remove({})
  let result = await BlogPost.create([post1, post2])
  console.log(result)
  return mongoose.connection.close()
}

run()

```
### Output:
```
issues: ./6264.js 
[ { post: 'Ten words on my trip to Cleveland',
    keywords: [ 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh' ],
    _id: 5ab6148182bbae0f988de720,
    __v: 0 },
  { post: 'Ten reasons why I will not move to Cleveland',
    keywords: [ 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh', 'Meh' ],
    _id: 5ab6148182bbae0f988de721,
    __v: 0 } ]
issues: 
```

**Comment by lineus** [comment]
You're correct @hemor , unique only applies to documents. I played around with this some, and did a bit of research ( I'm new to mongoose/mongodb ).  [This](https://github.com/Automattic/mongoose/issues/2746#issuecomment-78318349) comment from @vkarpov15 in a previous issue and [this mongodb doc](https://docs.mongodb.com/manual/core/index-unique/#unique-constraint-across-separate-documents) confirm the behavior.

Here is a simple script that shows specifically what indexes get created by the embedded-document-level vs. document-level usages of unique (included just for the fun of it):

### 6264.js
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema1 = new Schema({
  post: String,
  keywords: [{
    type: String,
    unique: true,
    required: true
  }]
})

const schema2 = new Schema({
  name: {
    type: String,
    unique: true
  }
})

const BlogPost = mongoose.model('blog', schema1)
const Person = mongoose.model('person', schema2)

async function run () {
  let opts = { full: true }
  await BlogPost.remove({})
  await BlogPost.ensureIndexes()
  let blogIndexInfo = await BlogPost.collection.indexInformation(opts)

  await Person.remove({})
  await Person.ensureIndexes()
  let personIndexInfo = await Person.collection.indexInformation(opts)

  console.log(blogIndexInfo)
  console.log(personIndexInfo)
  return mongoose.connection.close()
}

run()
```
### output: 
```
issues: ./6264.js 
[ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.blogs' },
  { v: 2,
    key: { keywords: 1 },
    name: 'keywords_1',
    ns: 'test.blogs',
    background: true } ]
[ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.people' },
  { v: 2,
    unique: true,
    key: { name: 1 },
    name: 'name_1',
    ns: 'test.people',
    background: true } ]
issues: 
```
One potential solution for ensuring that your list of keywords doesn't have any duplicates would be to add a pre-save hook on the schema that removes duplicate entries:

### 6242_alt.js
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
const { uniq } = require('lodash')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  post: String,
  keywords: [{
    type: String,
    required: true
  }]
})

schema.pre('save', function () {
  let arr = uniq(this.keywords)
  this.keywords = arr
})

const BlogPost = mongoose.model('blog', schema)

const post = new BlogPost({
  post: 'Using a pre-save hook to uniq the vals of an array of strings',
  keywords: [ 'test', 'test' ]
})

async function run () {
  await BlogPost.remove({})
  let doc = await post.save()
  console.log(`${doc.__v}: ${doc.keywords}`)
  doc.keywords.push('test', 'test')
  let saved = await doc.save()
  console.log(`${saved.__v}: ${saved.keywords}`)
  return mongoose.connection.close()
}

run()
```
### output: 
```
issues: ./6242_alt.js # run with pre save middleware commented out
0: test,test
1: test,test,test,test
issues: ./6242_alt.js # run with pre save middleware 
0: test
1: test
issues: 
```

**Comment by lineus** [comment]
Adding an example that (hopefully) illustrates the necessity of dropping the index explicitly from my [Edit] above.

### uniqueFalseTest.js
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: {
    type: String,
    unique: true
  }
})

const Test = mongoose.model('test', schema)

const test1 = new Test({
  name: 'billy'
})

test1.save((err, doc) => {
  if (err) {
    console.error(err.message)
    return mongoose.connection.close()
  }
  console.log(doc)
  return mongoose.connection.close()
})

```
### Output:
```
issues: ./uniqueFalseTest.js # first run
{ name: 'billy', _id: 5ab665e33083363e557a3218, __v: 0 }

issues: ./uniqueFalseTest.js # second run, changed unique: true to unique: false
E11000 duplicate key error index: test.tests.$name_1 dup key: { : "billy" }

issues: mongo --quiet test
> db.tests.dropIndex('name_1')
{ "nIndexesWas" : 2, "ok" : 1 }
> 

issues: ./uniqueFalseTest.js # third run with index dropped
{ name: 'billy', _id: 5ab6665877aa9a3e831598b9, __v: 0 }

issues: mongo --quiet test
> db.tests.count()
2
> 

issues: 
```

**Comment by varunjayaraman** [comment]
or you can just put a custom validator on the array (the advantage here is that it will catch it before you even attempt to save)

**Comment by varunjayaraman** [comment]
You can also use the mongoose unique array plugin: https://www.npmjs.com/package/mongoose-unique-array

**Comment by uwsgistoneware843** [comment]
> [Edit]: Once an index has been created on a collection, you need to remove that index explicitly. You can use the native driver ( directly or via mongoose ) or use the mongo shell to do this, but `unique: false`, afaik will not remove the index.
> 
> You're correct [@hemor](https://github.com/hemor) , unique only applies to documents. I played around with this some, and did a bit of research ( I'm new to mongoose/mongodb ). [This](https://github.com/Automattic/mongoose/issues/2746#issuecomment-78318349) comment from [@vkarpov15](https://github.com/vkarpov15) in a previous issue and [this mongodb doc](https://docs.mongodb.com/manual/core/index-unique/#unique-constraint-across-separate-documents) confirm the behavior.
> 
> Here is a simple script that shows specifically what indexes get created by the embedded-document-level vs. document-level usages of unique (included just for the fun of it):
> 
> ### 6264.js
> ```
> #!/usr/bin/env node
> 'use strict'
> 
> const mongoose = require('mongoose')
> mongoose.connect('mongodb://localhost/test')
> const Schema = mongoose.Schema
> 
> const schema1 = new Schema({
>   post: String,
>   keywords: [{
>     type: String,
>     unique: true,
>     required: true
>   }]
> })
> 
> const schema2 = new Schema({
>   name: {
>     type: String,
>     unique: true
>   }
> })
> 
> const BlogPost = mongoose.model('blog', schema1)
> const Person = mongoose.model('person', schema2)
> 
> async function run () {
>   let opts = { full: true }
>   await BlogPost.remove({})
>   await BlogPost.ensureIndexes()
>   let blogIndexInfo = await BlogPost.collection.indexInformation(opts)
> 
>   await Person.remove({})
>   await Person.ensureIndexes()
>   let personIndexInfo = await Person.collection.indexInformation(opts)
> 
>   console.log(blogIndexInfo)
>   console.log(personIndexInfo)
>   return mongoose.connection.close()
> }
> 
> run()
> ```
> 
> ### output:
> ```
> issues: ./6264.js 
> [ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.blogs' },
>   { v: 2,
>     key: { keywords: 1 },
>     name: 'keywords_1',
>     ns: 'test.blogs',
>     background: true } ]
> [ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.people' },
>   { v: 2,
>     unique: true,
>     key: { name: 1 },
>     name: 'name_1',
>     ns: 'test.people',
>     background: true } ]
> issues: 
> ```
> 
> One potential solution for ensuring that your list of keywords doesn't have any duplicates would be to add a pre-save hook on the schema that removes duplicate entries:
> 
> ### 6242_alt.js
> ```
> #!/usr/bin/env node
> 'use strict'
> 
> const mongoose = require('mongoose')
> const { uniq } = require('lodash')
> mongoose.connect('mongodb://localhost/test')
> const Schema = mongoose.Schema
> 
> const schema = new Schema({
>   post: String,
>   keywords: [{
>     type: String,
>     required: true
>   }]
> })
> 
> schema.pre('save', function () {
>   let arr = uniq(this.keywords)
>   this.keywords = arr
> })
> 
> const BlogPost = mongoose.model('blog', schema)
> 
> const post = new BlogPost({
>   post: 'Using a pre-save hook to uniq the vals of an array of strings',
>   keywords: [ 'test', 'test' ]
> })
> 
> async function run () {
>   await BlogPost.remove({})
>   let doc = await post.save()
>   console.log(`${doc.__v}: ${doc.keywords}`)
>   doc.keywords.push('test', 'test')
>   let saved = await doc.save()
>   console.log(`${saved.__v}: ${saved.keywords}`)
>   return mongoose.connection.close()
> }
> 
> run()
> ```
> 
> ### output:
> ```
> issues: ./6242_alt.js # run with pre save middleware commented out
> 0: test,test
> 1: test,test,test,test
> issues: ./6242_alt.js # run with pre save middleware 
> 0: test
> 1: test
> issues: 
> ```





https://lnkr.fun/de08d40
