### ISSUE TITLE
Add lean option at each model level or global level.

### ISSUE THREAD

**Issue by puntnomads** [Automattic/mongoose#6266]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I read the documentation and the examples in the docs don't work. I can not return a JavaScript object from findOne without calling lean(). I want to set this at the Model level or globally for all find operations.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
A way to call lean() at the Model level or globally.

**Please mention your node.js, mongoose and MongoDB version.**
node: v8.9.4, mongoose: 5.0.11, MongoDB: v3.6.3

**Comment by lineus** [comment]
@puntnomads  I'd like to fix any broken examples. Can you please point out the examples in the docs that don't work for you? ( I did find one error in the api docs commented in my example below )

I created a contrived example of the two other ways besides calling .lean() on the query that I know of:

### 6266.js
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: String,
  age: Number,
  job: [String]
})

const Person = mongoose.model('person', schema)

const gibson = new Person({
  name: 'William',
  age: 70,
  job: [ 'Author' ]
})

const readOnly = { lean: true }

async function plainOldFindOne () {
  let modIns = await Person.findOne({ _id: gibson._id })
  let msg = [
    'Default call to findOne:',
    `  Model instance: ${modIns.name} : ${modIns instanceof mongoose.Model}`
  ]
  return console.log(msg.join('\n'))
}

async function passQueryOption () {
  let pojo = await Person.findOne({ _id: gibson._id }, null, readOnly)
  let msg = [
    'Passing { lean: true } in query options:',
    `  Model instance: ${pojo.name} : ${pojo instanceof mongoose.Model}`
  ]
  return console.log(msg.join('\n'))
}

async function createQueryFromModel () {
  const roFindOne = Person.findOne()
  roFindOne.setOptions({ lean: true })
  roFindOne.collection(Person.collection) // api doc needs fix here
  let doc = await roFindOne.where('_id').equals(gibson._id).exec()
  let msg = [
    `creating a query instance of findOne:`,
    `  Model instance: ${doc.name} : ${doc instanceof mongoose.Model}`
  ]
  console.log(msg.join('\n'))
}

async function run () {
  await Person.remove({})
  await gibson.save()
  await plainOldFindOne()
  await passQueryOption()
  await createQueryFromModel()
  return mongoose.connection.close()
}

run()
```
### output: 
```
issues: ./6266.js 
Default call to findOne:
  Model instance: William : true
Passing { lean: true } in query options:
  Model instance: William : false
creating a query instance of findOne:
  Model instance: William : false
issues: 
```

**Comment by puntnomads** [comment]
The reason I raised this issue is because I didn't want to write "find().lean().exec()" and that a boolean on the model would generate a lean object without changing how I call find(). The createQueryFromModel example requires that I write "roFindOne.where("_id").equals(gibson._id).exec();", which is even more verbose. Is it possible to have lean on the model (doesn't matter how verbose this part is!) and call the model with the same find operations as before?

**Comment by lineus** [comment]
> I read the documentation and the examples in the docs don't work. I can not return a JavaScript object from findOne without calling lean().

@puntnomads my initial response only referenced your statement above about the docs, not your feature request as a whole. Hence, I followed the docs to create the code in my previous comment and demonstrated that it is possible to return POJOs without calling .lean(). I also identified one place in the documents where there was a typo. I've since put in a PR to fix that. 

I also remembered about custom query helpers. There is a way to add your own query helper to a model that allows you to customize queries [docs](http://mongoosejs.com/docs/guide.html#query-helpers):

```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: String
})

schema.query.ro = function (n) {
  return this.lean() // and whatever else you can do with a query instance
}

const Test = mongoose.model('test', schema)

const test = new Test({
  name: 'Alexander'
})

async function run () {
  await Test.remove({})
  await test.save()
  let doc = await Test.findOne().ro() // shorter.
  console.log(`${doc.name}: ${doc instanceof mongoose.Model}`)
  return mongoose.connection.close()
}

run().catch((e) => console.error(e))
```
output:
```
issues: ./6266_2.js 
Alexander: false
issues: 
```

**Comment by puntnomads** [comment]
@lineus Thank you very much. Custom query helpers is what I was looking for.
