### ISSUE TITLE
Setters not running on array types on query?

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#6277]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Array setter function not called on find query

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/natanavra/abaf9a334e69d663a66952d8cb02297c

**What is the expected behavior?**
The array setter should be called when running a query.

**Please mention your node.js, mongoose and MongoDB version.**
Node 9.6.1
Mongo 3.4.0

**Comment by lineus** [comment]
@natanavra I edited your example slightly so the query would find a matching doc:
```
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost:27017/test')
const Schema = mongoose.Schema

const schema = new Schema({
  strings: {
    type: [String],
    default: () => void 0,
    required: true,
    set: function (items) {
      console.log('array of strings setter called')
      for (let i = 0; i < items.length; i++) {
        items[i] = normalize(items[i])
      }
      return items
    }
  }
})

const Model = mongoose.model('Object', schema)

function normalize (url) {
  return url.substr(0, url.length - 1)
}

function main () {
  const item = new Model({ strings: ['first', 'second', 'third'] })
  item.save()

  Model.findOne({ strings: 'firs' }) // (removed t) when saved initially, array values are truncated.
    .then(console.log)
    .catch(console.error)
}
main()

```
### output:
```
issues: node ./6277.js
array of strings setter called
{ _id: 5ab8e0a2cb3079773ae9aa8d,
  strings: [ 'firs', 'secon', 'thir' ],
  __v: 0 }
^C
issues: 
```

**Comment by lineus** [comment]
the setter also does not run if you actually update the value of the array:
```
async function main () {
  const item = new Model({ strings: ['first', 'second', 'third'] })
  await item.save()

  Model.findOneAndUpdate({ strings: 'firs' }, { strings: ['wxyz', 'abcd'] }, { new: true })
    .then(console.log)
    .catch(console.error)
}
main()
```
output: 
```
issues: node ./6277.js
array of strings setter called
{ _id: 5ab8e0a94c372077437511d2,
  strings: [ 'wxyz', 'abcd' ],
  __v: 0 }
^C
issues: 
```

**Comment by natanavra** [comment]
I meant I was expecting the setter to run on the query object, so the 't' would be removed by the setter. This does happen with primitive fields setter.
The behaviour is not documented and I'm not sure what to expect.

**Comment by lineus** [comment]
@natanavra I agreed with you in my first comment that the setter for the array path is not running on query. 

Here is an example that codifies the expectation that setters on arrays should behave the same on queries as string setters do ( but they don't): 
### 6277.js
```
'use strict'

const assert = require('assert')
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost:27017/test')
const Schema = mongoose.Schema

var s = 0
var a = 0

const schema = new Schema({
  name: {
    type: String,
    set: function (str) {
      s++
      return str
    }
  },
  strings: {
    type: [String],
    default: () => void 0,
    required: true,
    set: function (items) {
      a++
      return items
    }
  }
})

const Model = mongoose.model('Object', schema)

const item = new Model({
  name: 'Mark',
  strings: ['first', 'second', 'third']
})

async function main () {
  await Model.remove({})
  await item.save()

  let doc = await Model.findOne({ strings: { $elemMatch: { $in: ['first'] } } })
  await Model.findOne({ name: 'Mark' })

  assert.equal(doc.name, 'Mark')
  assert.equal(s, 2, 'String setter not called twice')
  assert.equal(a, 2, 'Array of Strings setter not called twice')

  return mongoose.connection.close()
}

main().catch(e => {
  console.error(e)
  return mongoose.connection.close()
})
```
### Output:
```
issues: node ./6277.js 
{ AssertionError [ERR_ASSERTION]: Array of Strings setter not called twice
    at main (/Users/lineus/dev/Help/mongoose5/issues/6277.js:46:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 2,
  operator: '==' }
issues: 
```

My second comment was just me trying to understand the problem space and I should have just kept it in a private note to myself. It wasn't meant as a suggestion for what you should be doing.

**Comment by natanavra** [comment]
@lineus Sorry, I misinterpreted your comments, looked at the modified code example (which does return the desired output, but the original was written that way on purpose to show that if the setter would have executed, we would get the desired output).
Thanks for the elaborate response.

**Comment by lineus** [comment]
That's my fault, I wasn't clear about the purpose of the comment :) 

I was also totally wrong about the query not returning a result because of the condition in the findOne({ strings: 'first' }). I tried to read everything I could about setters/getters, but I misunderstood that the setter would effect the condition before the query gets sent. Which in hindsight is silly :)

**Comment by varunjayaraman** [comment]
I've narroed the problem down. The one time the setter runs is because of the save operation i believe. SO it does look like setters are not being run in find operations on array fields:

```javascript
'use strict'

const assert = require('assert')
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost:27017/test')
const Schema = mongoose.Schema

var s = 0
var a = 0

const schema = new Schema({
  name: {
    type: String,
    set: function (str) {
      s++
      return str
    }
  },
  strings: {
    type: [String],
    default: () => void 0,
    required: true,
    set: function (items) {
      console.log('running')
      a++
      return items
    }
  }
})

const Model = mongoose.model('Object', schema)

const item = new Model({
  name: 'Mark',
  strings: ['first', 'second', 'third']
})

async function main () {
  await Model.remove({})
  await item.save()

  console.log('a before finds', a);
  let doc = await Model.findOne({ strings: 'first' })
  let doc2 = await Model.findOne({ strings: 'secon' })

  assert.equal(doc.name, 'Mark')
  console.log('a', a)
  assert.equal(a, 2, 'Array of Strings setter not called twice')

  return mongoose.connection.close()
}

main().catch(e => {
  console.error(e)
  return mongoose.connection.close()
})
```

**Comment by lineus** [comment]
just a quick update: the value of `this` in `this.setters` in SchemaType.prototype._applySetters() **during the query operation** is `SchemaString`, so it's not magically picking the correct SchemaType based on the schema, but more than likely picking it based on the condition type in the query. Trying to sort this out now.

**Comment by vkarpov15** [comment]
As a workaround, instead of this:

```javascript
const schema = new Schema({
    strings: {
        type: [String],
        default: () => void 0,
        required: true,
        set: function(items) {
            console.log('strings setter called');
            for(let i = 0 ; i < items.length ; i ++) {
                items[i] = normalize(items[i]);
            }
            return items;
        }
    }
});
```

Do this:

```javascript
const schema = new Schema({
    strings: {
        type: [{
          type: String,
          set: normalize
        }],
        default: () => void 0,
        required: true
    }
});
```

Should be equivalent for most cases and I can confirm this setter will run in mongoose 5.0.12.

**Comment by vkarpov15** [comment]
Upon closer inspection I'm going to have to chalk this up to expected behavior. Sorry for the inconvenience, but the [workaround I mentioned](https://github.com/Automattic/mongoose/issues/6277#issuecomment-377831918) is the right way to go about this. This change would likely be backwards breaking and also break the contract that a setter on a given schematype runs when we're actually casting a value to that schematype.

**Comment by natanavra** [comment]
How is that expected behaviour? Can you point me in the direction? Since the documentation is rather vague about Setters to begin with. 
This makes finding bugs very difficult, I'm not sure when mongoose works its magic and when not...

**Comment by vkarpov15** [comment]
What do you mean by "can you point me in the direction"?

**Comment by natanavra** [comment]
Where the expected behavior is documented and explained

**Comment by BrunoGodefroy** [comment]
@vkarpov15 Your work around is an elegant solution in the use case described above but what would be your recommended way to go in case the setter is supposed to transform the array globally? Like in this example:

```
const schema = new Schema({
    numbers: {
        type: [Number],
        set: items => items.sort((a, b) => a - b),
    }
});
```

**Comment by vkarpov15** [comment]
@BrunoGodefroy if your query is `MyModel.find({ numbers: 2 })` there is no array to transform, just a single isolated value. However, you are right that the setter won't run if you do `MyModel.find({ numbers: [2] })`, that's a problem that we need to fix.

**Comment by Vishal23016** [comment]
{
	_id:13213
	name:'test',
	demo:[{
		name:'test',
		is_active:true,
	},{
		name:'test1',
		is_active:false,
	}]
}
db.User.find({"_id": '13213',"demo.is_active": true});
db.User.find({"_id": '13213',demo: {"$elemMatch": {is_active: true}});

both queries are not working

**Comment by softpot9** [comment]
db.User.find({"_id": '13213',demo: {"$elemMatch": {is_active: [true]}});
maybe it will be works.

**Comment by vkarpov15** [comment]
@Vishal23016 can you please clarify what you mean by "not working", what output are you getting and what output do you expect?

**Comment by Vishal23016** [comment]
i try find array of object is_active key only true

ex
:[{name:'test',is_active:true},{name:'test1',is_active:true},{name:'test',is_active:false}]

need to out only true array of object

**Comment by vkarpov15** [comment]
Do you mean you're trying to filter out all elements of the array where `is_active = false`?
