### ISSUE TITLE
Setters are called twice on primitives when running query

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#6278]
I saw an issue that was closed and fixed around 5.0.8, but it still happens on 5.0.11

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Primitive set function is called twice on query

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/natanavra/bde432a4f54fc6e7b44961d0ba30c08b

**What is the expected behavior?**
set function should called once

**Please mention your node.js, mongoose and MongoDB version.**
Node 9.6.1
Mongo 3.4.0

**Comment by lineus** [comment]
@natanavra running your example on mongoose 5.0.11 I see only 2 calls to the setter:

### example from gist ( 6278_orig.js )
```
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const schema = new Schema({
  item: {
    type: String,
    set: function (item) {
      console.log('item setter called')
      return normalize(item)
    }
  }
})
const Model = mongoose.model('Object', schema)

function normalize (url) {
  return url.substr(0, url.length - 1)
}

(function main () {
  const item = new Model({ item: 'item' })
  item.save()

  Model.findOne({ item: 'item' })
    .then(console.log)
    .catch(console.error)
})()
```
### output:
```
issues: node ./6278_orig.js
item setter called
item setter called
^C
issues: 
```
There is no doc returned from the findOne because you are running two asynchronous calls concurrently ( item.save() and Model.findOne() ).

### slightly modified example ( with async main() ) (6278_mod.js):
```

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  item: {
    type: String,
    set: function (item) {
      console.log('item setter called')
      return normalize(item)
    }
  }
})
const Model = mongoose.model('Object', schema)

function normalize (url) {
  return url.substr(0, url.length - 1)
}

(async function main () {
  const item = new Model({ item: 'item' })
  await item.save()

  await Model.findOne({ item: 'item' })
    .then(console.log)
    .catch(console.error)
})()
```
### output: 
```
issues: node ./6278_mod.js
item setter called
item setter called
{ _id: 5aba14c76cccf4a7971d1cca, item: 'ite', __v: 0 }
^C
issues: 
```

**Comment by natanavra** [comment]
You're right, I was on 5.0.7 (even though running npm update, but the semver was a strict version...)
