### ISSUE TITLE
Support for pagination along with sorting and filters

### ISSUE THREAD

**Issue by newkillerbeast2017** [Automattic/mongoose#6279]
Currently, Mongoose allows to filter results, limit them and do some sorting. It would be nice to have some offset that can be used to paginate the data. This will be particularly useful when the data to be shown on the UI is huge and needs to be paginated and support lazy loading. Let us assume the below example:

```
models.User
.find({active: 1})
.sort({'date': -1})
.limit(20)
.exec(function(err, users) {
     // `users` will be of length 20
});
```
What would be great to have is some sort of an offset that can given first 20, next 20 and so on so all functionalities can be combined into one.

NOTE: I do agree that there are some npm module when combined can give them but I don't find them well suited for the purpose plus there are accuracy issues. Let say, I had a filter for `active=1` and then descending sort on the `name` field and also perform a limit of 20, I don't get the exact results I am expecting. Would be good if there is at least a temporary workaround for the same. 

**Additional Information:**
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Querying data for specific filters

**What is the expected behavior?**
Be able to combine filters, orderby and paginate results(using an offset) all in a single query.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js - 9.2.0
MongoDB - 3.4
Mongoose - 4.13.7

**Comment by dsinecos** [comment]
@newkillerbeast2017 Any chance `.skip()` would be of help? [Reference](http://mongoosejs.com/docs/api.html#query_Query-skip)

**Comment by vkarpov15** [comment]
@dsinecos is right, `.skip()` does exactly what you want :+1:
