### ISSUE TITLE
custom fields for swagger UI

### ISSUE THREAD

**Issue by binarytracer** [Automattic/mongoose#6283]
**first question:** can i  add some "meta" fields for mongoose schema without disrupting its internal behaviours?

user.model.js
```javascript
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const newSchema = new Schema({
 name: { 
  type String, 
  description: 'this is description',
  example: 'this is example' 
}
},{versionKey: false});

module.exports = mongoose.model('users', newSchema);
```
this is my first time attempting to do this, by adding the **description** and **example**. My intention only is to have expressive way of presenting description to [Swagger Data Model](https://swagger.io/docs/specification/data-models/).

**second question**: if allowed, what are acceptables "meta" fields?

**Comment by varunjayaraman** [comment]
no, because mongoose will strip those fields it doesnt recognize in your options for defining a field's parameters:

```javascript
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const newSchema = new Schema({
 name: { 
  type: String, 
  description: 'this is description',
  example: 'this is example' 
}
},{versionKey: false});

const Model = mongoose.model('users', newSchema);

mongoose.connect(`mongodb://localhost:27017/gh-6283`)
  .then(() => Model.create({ name: 'test' }))
  .then((doc) => console.log('ran!', doc.name.description)) // undefined
  .catch(console.error.bind(console));
```

**Comment by binarytracer** [comment]
you can get the **description** and **example** by this,
```js
...
const Model = mongoose.model('users', newSchema);

const fieldMetas = Model.schema.paths['name'].options;

console.log(fieldMetas); // { type: [Function: String],  description: 'this is description',  example: 'this is example' }
```

**Comment by vkarpov15** [comment]
@binarytracer you're right, I think Varun just misread your question. You should be able to put any meta properties you want except for these:

* `type`
* `validate`
* `required`
* `min`
* `max`
* `minlength`
* `maxlength`
* `default`
* `get`
* `set`
* `default`
* `alias`

These are [listed in the docs](http://mongoosejs.com/docs/schematypes.html#schematype-options). These are the only ones mongoose uses currently, but plugins you use may have their own properties they look out for.

**Comment by binarytracer** [comment]
@vkarpov15 thanks for the confirmation.
