### ISSUE TITLE
Upsert duplicate key error mongoose with discriminators

### ISSUE THREAD

**Issue by pramod1792** [Automattic/mongoose#6285]
I have implemented  discriminators with mongoose and connecting to Azure cosmos db's Mongo APIs.
I have a base collection as bases and 2 other collections say coll1 and coll2 inherited from bases (code looks like one in here https://anthonychu.ca/post/cosmos-db-mongoose-discriminators/ )

Those 2 collections contains same field(macId) on which i have implemented upsert on update.

Insert on 1st collection is successful But getting following error while inserting object of second collection 
MongoError: E11000 duplicate key error collection: bases Failed _id or unique key constraint

**Comment by varunjayaraman** [comment]
can you please post your schemas?
