### ISSUE TITLE
Deep Population of Sub Documents Across Arbitrary Levels

### ISSUE THREAD

**Issue by varun1729** [Automattic/mongoose#6290]
Potenial Feature request

Currently in Mongoose I can populate references to documents by using the populate() function. However the function only works when I know how many levels deep I want to populate. There is no way for me to populate references to documents across arbitrary levels.

Consider the following schema of task with references to child tasks:

```
let taskSchema = new mongoose.Schema({
	name: String,
        ...
        childTasks: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: "Task"
	}],
        ...
});
```

I want a task object returned, when I perform the deep population, that looks something like this
{
name:
...
[ 
{ //child tasks
  name
  ...
  [
     {
        name
        ...

//and so on
As you can see each task has child tasks and each child task has child tasks so an so forth. I would like to populate a task such that, I get a nested list (array) of child tasks that is also populated.

I tried using the plugin [mongoose-deep-populate](https://www.npmjs.com/package/mongoose-deep-populate) but the plugin populates the references, but does not nest them appropriately. 

Node 5.6.0 and mongoose 5.0.12

**Comment by vkarpov15** [comment]
Mongoose already has [support for deep populate](http://mongoosejs.com/docs/populate.html#deep-populate)
