### ISSUE TITLE
Missing Document.prototype.remove() method from api docs

### ISSUE THREAD

**Issue by ztrange** [Automattic/mongoose#6295]
Documentation for 5.0.12

http://mongoosejs.com/docs/api.html#Document

**Comment by lineus** [comment]
@ztrange  a Document is an instance of a Model:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: String
})

const Test = mongoose.model('test', schema)

const test = new Test({
  name: 'Testing 123'
})

async function run () {
  await Test.remove({})
  let saved = await test.save()
  let msg = `${saved instanceof mongoose.Model}`
  console.log('saved is an instance of model:', msg)
  return mongoose.connection.close()
}

run()
```
output:
```
issues: ./6295.js
saved is an instance of model: true
issues:
```
When you call `.remove()` on a document, you're actually calling `Model.prototype.remove()` which is documented [here](http://mongoosejs.com/docs/api.html#model_Model-remove)

**Comment by ztrange** [comment]
Wow, that actually helps me a lot. Thank you for clarifying it.

**Comment by lineus** [comment]
@ztrange please feel free to submit a PR for any changes to the documentation/code. 

Currently the first paragraph on [The Document page](http://mongoosejs.com/docs/documents.html) in the guide covers the relationship of documents to models. If you think it should also be in the API docs, or be explained differently, [here](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) is the link to the contributing guidelines where you can find instructions specifically on documentation updates. Let me know if I can help with any part of the process.

**Comment by lineus** [comment]
Hi @govindrai ! 

The remove method **is** documented. It is inherited from Model, hence it's documentation is located under the `Model` section in the documentation. 

The last line of my initial response ( under the code/output ) to this issue has a link to `Model.prototype.remove` in the docs.

**Comment by govindrai** [comment]
Thanks @lineus that makes sense. Still I am a bit confused. `save` is documented on both Model _and_ Document API docs (Model.prototype.save/Document.prototype.save). The documentation for both is almost exactly the same. Why is this documented in both places? I feel like I am missing a just bit of the puzzle 😄
