### ISSUE TITLE
Not playing along nicely with Decimal.js library

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#6299]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am using [decimal.js](https://github.com/MikeMcl/decimal.js/) to work with numbers, and it's supposed to have a cast to `Number` support, so you can just substitute Decimal objects whenever you'd use `Number`'s

However, when I pass these values to a Mongoose model, it seems to incorrectly cast it to a Number. The value becomes an object instead.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
'use strict';

const mongoose = require('mongoose');
const Decimal = require('decimal.js');
const {Schema, Types: {ObjectId}} = mongoose;

const TestSchema = new Schema({
  amount1: {
    type: Number,
  },
  amount2: {
    type: Number,
  },
});

const Test = mongoose.model('Test', TestSchema);

//Create test number
const num = new Decimal(10);

//For reference, use toNumber and casted values
const toNum = num.toNumber();
const casted = Number(num);

//Create instance
const test = new Test({
  amount1: 5,
  amount2: num,
});

//Test output
console.log(toNum, typeof toNum); //Expected 10, 'number'
console.log(casted, typeof casted); //Expected 10, 'number'
console.log(test.amount1, typeof test.amount1); //Expected 5, 'number'
console.log(test.amount2, typeof test.amount2); //Expected 10, 'number'
```

**What is the expected behavior?**
Expected output of console logs is:

```
10 'number'
10 'number'
5 'number'
10 'number'
```

Actual output however is:
```
10 'number'
10 'number'
5 'number'
[Number: 10] 'object'
```

That last entry is boggling me. What is Mongoose doing to produce this kind of strange object? It seems to neither cast the value to a `Number`, nor call the `toNumber()` method.

Worth noting that after actual persisting to database, the value is correctly cast and saved.

**Possible solutions**
I don't know where in the code this casting happens, but it may be that a `typeof value === 'object'` check is done and then it incorrectly converts. Maybe it needs a check for a `toNumber` method and then call it instead, or simply coerce with `Number(value)`?

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.10.0
Mongoose 5.0.12

**Comment by rwmia** [comment]
Decimal js creates objects from values. Use demicaljs to convert to number before inserting to db. I think it’s toDP(num).

**Comment by adamreisnz** [comment]
I am aware of the [`toNumber`](http://mikemcl.github.io/decimal.js/#toNumber) method in Decimal.JS, but the whole point is _not_ having to use that in every single location because it will be a royal pain the ass to refactor the whole codebase to guard against Decimals.

I figured this is a perfect task for Mongoose, since for example, it can also handle conversion of `moment` objects to primitive `Date`'s automatically.

The same should be true for Decimal objects in my opinion, especially if it has a `toNumber` method that can be called by Mongoose, much as it calls `valueOf` or `toDate` for moment objects.

I could bother making a plugin to handle this, but I really think Mongoose could check this itself.

**Comment by lineus** [comment]
Hi @adamreisnz! The casting ( in this case ) happens in `mongoose/lib/schema/number.js`.

The specific part of 5.0.12 is:
```
    if (val.toString && !Array.isArray(val) && val.toString() == Number(val)) {
      return new Number(val);
    }
}
```
if you play this out in the repl it goes a little something like this (hit it):
```
issues: node
> let d = require('decimal.js')
undefined
> let num = new d(10)
undefined
> let newNum = new Number(num)
undefined
> newNum
[Number: 10]
>
```

I think in most cases the assumption that if val.toString and Number(val) are loosely equal returning new Number(val) works, but in the case of decimal.js obviously it's not going to do the right thing. Maybe we can check for a toNumber method on val before we get to val.toString and prefer that. I'll throw in a PR for this at some point today barring any objections.

**Comment by lineus** [comment]
I feel like I want to object to my own solution of preferring toNumber, because who knows what toNumber is *really* going to return? (at least on non decimal.js objects)

I think a better solution would be to change the return in SchemaNumber.prototype.cast:
from:
```
    if (val.toString && !Array.isArray(val) && val.toString() == Number(val)) {
      return new Number(val);
    }
```
to:
```
    if (val.toString && !Array.isArray(val) && val.toString() == Number(val)) {
      return Number(val);
    }
```
Returning Number vs new Number:
   1. aligns SchemaNumber.prototype.cast's intent of conversion with Number's documented usage ( no new === conversion ) ([Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)) 
   1. making this change doesn't break any current tests (**FWIW**)
   1. results in the expected output for this issue:
```
issues: awk 'NR==227 { print }' ../node_modules/mongoose/lib/schema/number.js
      return Number(val);
issues: ./6299.js
10 'number'
10 'number'
5 'number'
10 'number'
^C
issues:
```

**Comment by adamreisnz** [comment]
Thanks for looking into it. Personally, I think checking for a `toNumber` is better than checking for a `toString` anyway. Yes, you don't know what it will return, but it's a pretty high chance that it will return a number right?

> who knows what toNumber is really going to return

Who knows what `toString` is really going to return? 😄  

That has more chances of being non-conform output than `toNumber` imo. For example, it's conceivable that some object for a number representation has `$200` as the `toString` output.

But anyway, your proposed fix seems to solve the issue at hand and remains backwards compatible (probably?) so that's great, we can leave it at that. 👍

**Comment by lineus** [comment]
After some background processing of this during the day, and reading your excellent point on toString vs toNumber, I agree with you. 

All of **our** tests still pass, after returning `Number(val)` instead of `new Number(val)`, but that doesn't mean other people's code won't break on typeof vs instanceof. I can argue for and against both potential solutions.

@vkarpov15 @varunjayaraman Thoughts?

**Comment by adamreisnz** [comment]
Good point, that might indeed be an issue.

What if we do something like:

```js
if (typeof val.toNumber === 'function') {
  return val.toNumber();
}
else if (val.toString && !Array.isArray(val) && val.toString() == Number(val)) {
  return new Number(val);
}
```

This should only call the function if an object is passed and such a method is present on it, and fall back to the current implementation if it isn't. In theory, that should remain backwards compatible and only add new functionality for objects that do have a `toNumber` converter to use it.

**Comment by adamreisnz** [comment]
By the way that last condition in the existing code should probably be updated to `val.toString() === String(Number(val))`, in order to be explicit and avoid the weak `==` comparison.

**Comment by vkarpov15** [comment]
@adamreisnz see my comments on #6306, I think the better approach would be to look for `.valueOf()` rather than `.toNumber()`, which is non-standard. Any thoughts?

**Comment by adamreisnz** [comment]
Thanks I've commented in the PR

**Comment by vkarpov15** [comment]
Fixed by #6306

**Comment by marcelh-gh** [comment]
I don't see this working. Assigning a decimal.js object to a property of type Decimal128 I get a cast error.

@lineus I have seen your test for this. Have you also actually tried it out with a decimal.js object?

Thanks!
Marcel

**Comment by marcelh-gh** [comment]
adding something like 
`  if (typeof value === 'object' && typeof value.valueOf === 'function') {
    return Decimal128Type.fromString(value.valueOf());
  }`

to decimal128.js

probably solves this...

**Comment by adamreisnz** [comment]
@marcelh-gh Mongoose probably doesn't want to have decimal.js as a dependency, so your proposed solution won't work as it implies Mongoose needs to load the library to do that string conversion.

**Comment by vkarpov15** [comment]
@marcelh-gh is right, I merged the PR and the fix will be in 5.0.18 :+1:

**Comment by adamreisnz** [comment]
My bad, I thought `Decimal128Type` came from decimal.js 👍

**Comment by vkarpov15** [comment]
No worries. Check out [my article on the MongoDB decimal type](http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-34-decimal.html) for more info, the decimal type is pretty special.

**Comment by jessealama** [comment]
(Chiming in to an ancient issue with a request for comments:)

There's [a proposal](https://github.com/tc39/proposal-decimal) to build exact decimal numbers in to JS. I guess a number of the concerns raised here (lack of roundtrippability, dependency concerns) would be addressed if decimals were available out-of-the-box in JS. Any comments on the proposal are welcome!

**Comment by adamreisnz** [comment]
Thanks for raising awareness on that proposal @jessealama

**Comment by vkarpov15** [comment]
Nice, I'm glad TC39 is discussing adding Decimal support to JavaScript. Here's my thoughts, which I also shared on the survey.

I strongly support native decimal primitives in JavaScript, something like the `1.289m` syntax. If JavaScript can support this syntax for BigInts (which, IMO, was a completely useless addition to the language), JS can support this syntax for decimals. Again, it still baffles me that in 2024 it is non-trivial to make a device called a "computer" accurately compute 0.1 + 0.2. I understand the proposal indicated that implementers don't like this approach, but I think 0.1d + 0.2d === 0.3d is the way to go.

I am moderately opposed to a native Decimal128 class in JavaScript. A Decimal128 class doesn't provide enough benefit IMO. We already have userland Decimal128 classes, and I don't use them much because of the friction inherent with needing to instantiate Decimal128s.
