### ISSUE TITLE
exec() expecting 1 argument

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#6303]
In Webstorm code editor, it is saying that `exec()` is expecting one argument. I'm assuming that the code editor looks at the npm package installed (mongoose v4.9.2) and works this out, so is there a way to improve the code hinting?

**Comment by vkarpov15** [comment]
We don't have any formal support for webstorm or any other IDE, so there's not much we can do. However,  you usually don't need to do `.exec()` without any parameters. If you're trying to use queries with promise chaining, you can just do `MyModel.find().then(docs => { /* ... */ });`.
