### ISSUE TITLE
Can't .where on virtual relations

### ISSUE THREAD

**Issue by lauriejim** [Automattic/mongoose#6307]
**Do you want to request a *feature* or report a *bug*?**

A bug I think or maybe it's not possible.

**What is the current behavior?**

Can't make .where() on virtuals

**If the current behavior is a bug, please provide the steps to reproduce.**

Create `Articles` with virtual (`created_by`) relation to `User` (`owned`, polymorph relation)
And try to get `Articles` witch have a specific `created_by`

**What is the expected behavior?**

Be able to find `Articles` created by specific `User` (by virtuals relation)

**Please mention your node.js, mongoose and MongoDB version.**

node: 9.4.0
mongoose: 5.0.4
mongo: v3.2.11

**Comment by vkarpov15** [comment]
Can you elaborate with more code samples? I don't understand

**Comment by lauriejim** [comment]
To be more simple @vkarpov15 

Is it possible to make a where on `virtuals` ?

**Comment by varunjayaraman** [comment]
@lauriejim is the feature you're looking for the ability to use a virtual fieldname in a query?

 like so:

```javascript
Article.where({ someVirtualFieldName: someVirtualValue });
```

**Comment by lauriejim** [comment]
Yes, something like that.

**Comment by lauriejim** [comment]
And in my case the virtual value is an ObjectId of an other model.

**Comment by vkarpov15** [comment]
@lauriejim no, `Article.where({ someVirtualFieldName: someVirtualValue })` doesn't work because `someVirtualFieldName` is not stored in the database, so MongoDB can't filter on it.
