### ISSUE TITLE
mode.save fails with new style MongoDB 3.6.3 Atlas URL

### ISSUE THREAD

**Issue by lakamsani** [Automattic/mongoose#6310]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`model.save` fails with new style URL but work with old style URL. See this [gist](https://gist.github.com/lakamsani/d5e13580b5e36cf399aafaad95e15d92) for details. Error when it fails is:
```bash
/Users/vamsee/Development/server/node_modules/mongoose/lib/utils.js:429
        throw err;
        ^
MongoError: not authorized on admin to execute command { listIndexes: "test_mongoose_models", cursor: {}, $clusterTime: { clusterTime: Timestamp(1522809279, 1), signature: { hash: BinData(0, 491C7B0335A1A6235847FA6D0A01C974E9B3BD91), keyId: 6534092244582924289 } }, lsid: { id: UUID("6ba3d09f-e575-4512-bc3a-aca117e5852a") }, $db: "admin" }
    at queryCallback (/Users/vamsee/Development/node_modules/mongodb-core/lib/cursor.js:223:25)
    at /Users/vamsee/Development/server/node_modules/mongodb-core/lib/connection/pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Process finished with exit code 1
```
**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/lakamsani/d5e13580b5e36cf399aafaad95e15d92
You can see from the gist that I already tried the workaround suggested in https://github.com/Automattic/mongoose/issues/6041 but it still fails.  Worked with Atlas support to reproduce this problem by using MongoClient directly. They suggest getting the db with the client as shown in the docs [here](https://docs.atlas.mongodb.com/driver-connection/#node-js-driver-example) `client.db("test")` and then using that `db` for subsequent operations on collections including creating indexes. But not sure how to do that with mongoose. 
**What is the expected behavior?**
`model.save` should work as it does with old style url. 
**Please mention your node.js, mongoose and MongoDB version.**
node 8.9.4, mongoose 5.0.12, MongoDB 3.6.3

**Comment by vkarpov15** [comment]
@lineus bumped in master, will release with 5.0.15 :+1:

**Comment by lakamsani** [comment]
Just tried this with mongoose 5.0.15 +  mongodb 3.0.6 and still get the same error with the sample in https://gist.github.com/lakamsani/d5e13580b5e36cf399aafaad95e15d92 with Atlas/MongoDB 3.6.3. `npm ls` shows: 

```bash
└─┬ mongoose@5.0.15
  └── mongodb@3.0.6
```

**Comment by lineus** [comment]
I just tested mongoose 5.0.15 against my atlas free cluster using the new srv uri using the following code and it works for me. The only obvious difference being that the uri provided from my atlas dashboard doesn't have the authSource query parameter.

### 6310.js
```js
#!/usr/bin/env node
'use strict';

const uri = require('/Users/lineus/.env').ATLASSRV;
const sharable = uri.replace(/\/[^:]+:[^@]+@/,'/**:**@');
console.log(sharable);
const mongoose = require('mongoose');
mongoose.connect(uri);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log(found);
  return conn.close();
}

run();
```
### output:
```
mongodb+srv:/**:**@cluster0-m1luc.mongodb.net/test
{ _id: 5ad6f46c467f0dda29b0a759, name: 'test', __v: 0 }
issues:
```
