### ISSUE TITLE
how to achieve multi-level schema inheritance or compose?

### ISSUE THREAD

**Issue by anlexN** [Automattic/mongoose#6311]
i have read mongoose document once by once.
Summary:
**there are 4 possible solution**
* [populate](http://mongoosejs.com/docs/populate.html)
* [discriminators](http://mongoosejs.com/docs/discriminators.html)
* [plugin](http://mongoosejs.com/docs/plugins.html)
* [loadClass](http://mongoosejs.com/docs/advanced_schemas.html)
i expect such like this relational schema , inspired by [shema.org](http://schema.org/docs/full.html):
```
        thingSchema
            |
  creativeworkSchema
            |
      ArticleSchema
```
So, @mongoosejs team, can you explain more much inheritance or compose with shcema?

**Comment by vkarpov15** [comment]
@anlexN populate and plugins aren't really a mechanism for inheritance. Discriminators are used if you want to have multiple types of documents in a single collection, but that's a special case of general schema inheritance. IMO the below would be the cleanest way to do generic schema inheritance:

```javascript
const mongoose = require('mongoose');

class thingSchema extends mongoose.Schema {
  constructor(obj, options) {
    super(obj, options);
    this.add({ test: String });
  }
}

class creativeWorkSchema extends thingSchema {
  constructor(obj, options) {
    super(obj, options);
    this.add({ test2: String });
  }
}

const schema = new creativeWorkSchema();

const Model = mongoose.model('Test', schema);

console.log(new Model({ test: 'abc', test2: 'abc' }));
```
