### ISSUE TITLE
Documentation href not set properly

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#6314]
http://mongoosejs.com/docs/api.html#update_update

In this page, under Model.update() the options appear like this:
```
[options] «Object» optional see [`Query.prototype.setOptions()`](http://mongoosejs.com/docs/api.html#query_Query-setOptions)
```
I believe that's not what was intended

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix :+1:
