### ISSUE TITLE
Docs for Mongoose 5.0 Promise error handling in hooks

### ISSUE THREAD

**Issue by BorntraegerMarc** [Automattic/mongoose#6315]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
In http://mongoosejs.com/docs/middleware.html#pre it is written: `In mongoose 5.x, instead of calling next() manually, you can use a function that returns a promise. In particular, you can use async/await.`

Which is very nice! But under the Section "Error handling" it is written: `If any middleware calls next or done with a parameter of type Error, the flow is interrupted...`

My question is, if using `async / await` should it not also be possible to throw an object of type Error to signal to mongoose that an error happened? And if yes -> We should add this info to the docs

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by lineus** [comment]
@BorntraegerMarc I think the wording in the docs makes it sound like returning a promise and using async/await are one inextricably linked feature, but it's actually two separate features. 

## You can call the next hook by returning a promise
Consider the following 
### contrived example:
```js
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: String
})

schema.pre('save', function (next) {
  console.log('one!')
  next()
})

schema.pre('save', function () {
  console.log('two!')
  return banBilly(this.name)
})

schema.pre('save', function () {
  console.log('three!')
})

function banBilly (name) {
  return new Promise((resolve, reject) => {
    if (name === 'billy') {
      return reject(new Error('No Billies!'))
    } else {
      return resolve('hello ' + name)
    }
  })
}

const Test = mongoose.model('test', schema)

const sally = new Test({ name: 'sally' })
const billy = new Test({ name: 'billy' })

async function run () {
  await Test.remove({})
  await Test.create([sally, billy])
}

run().catch((e) => { 
  console.error(e); 
  return mongoose.connection.close() 
})
```
### output:
```
issues: ./6315.js
one!
one!
two!
two!
three!
Error: No Billies!
    at Promise (/Users/lineus/dev/Help/mongoose5/issues/6315.js:29:21)
    at new Promise (<anonymous>)
    at banBilly (/Users/lineus/dev/Help/mongoose5/issues/6315.js:27:10)
    at model.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6315.js:19:10)
    at model.next (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:63:31)
    at _next (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:106:10)
    at process.nextTick (/Users/lineus/dev/Help/mongoose5/node_modules/kareem/index.js:427:38)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
issues:
```

You can see that all three hooks get called despite not explicitly calling next() on the second hook (even though I didn't use an async function in hook 2). Just the act of returning a promise is enough. As long as the promise you return rejects with an error it will cause the next hook to throw.

## You can pass async functions into middleware
Consider the following example:
```js
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')
const Schema = mongoose.Schema

const schema = new Schema({
  name: String
})

schema.pre('save', async function (next) {
  let num = await Test.count()
  console.log(`There were ${num} docs before we added this one.`)
  next()
})

const Test = mongoose.model('test', schema)

const test = new Test({ name: 'billy' })

async function run () {
  await test.save()
  return mongoose.connection.close()
}

run()
```
### output of several consecutive runs:
```
issues: ./6315_2.js
There were 1 docs before we added this one.
issues: ./6315_2.js
There were 2 docs before we added this one.
issues: ./6315_2.js
There were 3 docs before we added this one.
issues: ./6315_2.js
There were 4 docs before we added this one.
issues: ./6315_2.js
There were 5 docs before we added this one.
issues:
```
let me know if this makes sense. I'm happy to throw together a PR for a change to the docs.

**Comment by BorntraegerMarc** [comment]
thanks for the input @lineus 
that makes sense. So this should work:
```
schema.pre('save', async function (next) {
  let num = await Test.count()
  if (num === 0) {
    throw new Error('It's zero!');
  }
  return next()
})

async function run () {
  try {
    await test.save()
  } catch (err) {
    console.log(err.message) // <- this logs "It's zero!"
  }
  return mongoose.connection.close()
}
```

correct?

**Comment by BorntraegerMarc** [comment]
Maybe a small description (with the above code examples) would be helpful in the docs

**Comment by lineus** [comment]
>correct?
yeah, that's a valid pattern. Though this got me to wondering if we would get a different Error stack by returning next(error) instead, but alas, they're the same either way. 

I don't personally know of a reason not to just throw in this context ( as opposed to returning next(new Error()) ).

**Comment by varunjayaraman** [comment]
yeah @lineus is right, async/await is just a wrapper around promises at the end of the day :)

I'm open to adding to the docs

**Comment by vkarpov15** [comment]
Re: "the wording in the docs makes it sound like returning a promise and using async/await are one inextricably linked feature, but it's actually two separate features" @lineus , they are one inextricably linked feature. An `async` function always returns a promise and there's no way to tell the difference between a regular function that returns a promise and an `async` function based on their return value.

Re: OP's question, yes, you can throw an error in an async function and that will work the same as `next(err)`. Will add docs about that
