### ISSUE TITLE
$limit and $skip not working in aggregate  

### ISSUE THREAD

**Issue by priyank21** [Automattic/mongoose#6317]
`
var perPage = 2;
 var skip = perPage * (page - 1);
Order.aggregate(
      [
        {
          $match: find_query
        },
        {
          $lookup: {
            localField: local_id,
            from: "users",
            foreignField: "_id",
            as: "order_to"
          }
        },
        
        { $sort: { created_at: -1 } },
        { $limit: perPage },
        { $skip: skip },
        
      ],
      function(err, gettt) {
        if (err) {
          res.json({ status: false, data: err });
          return false;
        } else {
         res.json({ status: false, data: gettt });
}
});`

**Comment by lineus** [comment]
@priyank21 Can you please create an example with a schema and all variable definitions including your query and any relevant output or errors?

**Comment by varunjayaraman** [comment]
yeah, please create a more reproducible script. Can you also clarify what you mean by "not working" ?

Also please format your code more readably next time, it makes it easier for us to understand your issue.

**Comment by lineus** [comment]
@priyank21 if you're still having an issue with this please comment per the instructions above and we'll be happy to re-open this and take a look.
