### ISSUE TITLE
model.save response too slow

### ISSUE THREAD

**Issue by StanislavRastorguev** [Automattic/mongoose#6321]
Probably bug
with mongoose 5.0.12 and 5.0.13 mongoose model.save after start project first response 1s, with mongoose 5.0.4 it start fine (this problem only with 1st save, get.request returns fast, after 1st save it works fine)

first run with 5.0.4v  55.944 ms
first run with 5.0.13v  1076.606 ms
first run with 5.0.12v 1076.509 ms

node 8.7.0
mongoDB 3.6.1

**Comment by lineus** [comment]
@StanislavRastorguev I tried to duplicate what you are seeing with the following script

### 6321.js
```js
#!/usr/bin/env node
'use strict'

const mtime = require('microtime')
const mongoose = require('mongoose')
const ver = mongoose.version
const Schema = mongoose.Schema

const schema = new Schema({
  test: String
})

const Test = mongoose.model('test', schema)

const test = new Test({
  test: 'test'
})

process.stdout.write(`version: ${ver} `)

async function run () {
  const connStart = mtime.now()
  const conn = await mongoose.connect('mongodb://localhost/test')
  const connTime = (mtime.now() - connStart) / 1000
  process.stdout.write(`conn: ${connTime} `)
  await conn.connection.dropDatabase()
  const saveStart = mtime.now()
  await test.save().then((doc) => {
    const saveTime = (mtime.now() - saveStart) / 1000
    process.stdout.write(`save: ${saveTime} ms `)
  })
  const doc = await Test.findOne({}).exec()
  if (doc) {
    console.log('verified: true')
  }
  return mongoose.connection.close()
}

run()

```
### output for versions 5.0.{4..13)
```
issues: for i in {4..13};do npm install mongoose@5.0.${i} 1>/dev/null 2>&1 && ./6321.js;done
version: 5.0.4 conn: 53.755 save: 29.708 ms verified: true
version: 5.0.5 conn: 54.135 save: 29.249 ms verified: true
version: 5.0.6 conn: 53.633 save: 28.902 ms verified: true
version: 5.0.7 conn: 58.189 save: 29.201 ms verified: true
version: 5.0.8 conn: 58.354 save: 35.925 ms verified: true
version: 5.0.9 conn: 56.456 save: 33.584 ms verified: true
version: 5.0.10 conn: 57.203 save: 33.499 ms verified: true
version: 5.0.11 conn: 59.012 save: 34.513 ms verified: true
version: 5.0.12 conn: 59.12 save: 36.282 ms verified: true
version: 5.0.13 conn: 58.253 save: 32.219 ms verified: true
issues:
```
Can you please provide a similar script that demonstrates the issue? Feel free to use mine and report back with your results.

**Comment by StanislavRastorguev** [comment]
I took part of your script in my project, mongoose conection starts with project, so no need to include it.

process.stdout.write(`version: ${ver} `);
          const saveStart = mtime.now();
          board.save((err, newBoard) => {
            const saveTime = (mtime.now() - saveStart) / 1000;
            process.stdout.write(`save: ${saveTime} ms `);

All this results is only 1s save after start project
version: 5.0.4 save: 23.001 ms
version: 5.0.5 save: 19.001 ms
version: 5.0.6 save: 17.001 ms
version: 5.0.7 save: 20.001 ms
version: 5.0.8 save: 1036.059 ms
version: 5.0.9 save: 1037.059 ms 
version: 5.0.10 save: 1041.06 ms 
version: 5.0.11 save: 1046.06 ms 
version: 5.0.12 save: 1034.059 ms
version: 5.0.13 save: 1033.059 ms

**Comment by lineus** [comment]
@StanislavRastorguev can you include your schema, connection details, and some sample data to help isolate the problem?

**Comment by StanislavRastorguev** [comment]
@lineus sure, just tell me what you need, this my schema, idk what you mean about connection details and sample data
```javascript
const mongoose = require('mongoose');

let taskSchema = new mongoose.Schema({
  taskName: {type: String, required: true},
  description: {type: String, 'default':''},
  date: {type: Date, 'default':null},
  attachments: [String]
});

let listSchema = new mongoose.Schema({
  listName: {type: String, required: true},
  tasks: [taskSchema]
});

let boardSchema = new mongoose.Schema({
  lists: [listSchema],
  color: {type: String, "default":"#0079BF"},
});

mongoose.model('Board', boardSchema);
```

**Comment by lineus** [comment]
by connection details I mean the uri string ( minus any sensitive data ) and the options that you are passing into mongoose.connect or mongoose.createConnection. 

sample data would be an example of a doc that you are saving ( minus any sensitive data )

**Comment by StanislavRastorguev** [comment]
@lineus db connection data
```javascript
const mongoose = require('mongoose');
const dbURI = 'mongodb://localhost/here_is_name';
mongoose.connect(dbURI);

const db = mongoose.connection;

db.on('error', (err) => {
  console.log('Mongoose connection error: ' + err);
});
db.on('connected', () => {
  console.log('Mongoose connected to ' + dbURI);
});
db.on('disconnected', () => {
  console.log('Mongoose disconnected');
});

require('./board');
```

**Comment by StanislavRastorguev** [comment]
and data for save
{ lists:
   [ { tasks: [], _id: 5ac840cf7f7a1718d8390dfc, listName: 'Test1' },
     { tasks: [], _id: 5ac840db7f7a1718d8390dfd, listName: 'Test2' },
     { tasks: [], _id: 5ac840dd7f7a1718d8390dfe, listName: 'Test3' },
     { tasks: [], _id: 5ac86650f5692c19c81d072f, listName: 'aaaaaaa' } ],
  color: '#D29034',
  _id: 5ac840c27f7a1718d8390dfb,
  __v: 133 }

**Comment by StanislavRastorguev** [comment]
@lineus if you need more information, i can invite you in bitbucket repository

**Comment by lineus** [comment]
@StanislavRastorguev did you happen to try running my test script as is? I'm curious if the isolated test-case behaves the same as your app. Can you change the db or collection names as necessary if you already have a db called test, and try to run my code?

**Comment by StanislavRastorguev** [comment]
@lineus did you reload app after every start script? this happens only after first start project and first save

**Comment by lineus** [comment]
yes. I installed each version of mongoose and ran the test script in a for loop on the command line. So this would have been the first connection and first save each time.

**Comment by StanislavRastorguev** [comment]
@lineus Acually i tested few min ago 5.0.12 version on another project, and it works fine. Its rly wierd, because that project have same algoritm. Any idea what i need to do now?

**Comment by lineus** [comment]
let me see if I still have a bitbucket account and I'll take a look at it if you like.

**Comment by StanislavRastorguev** [comment]
or not
{ tasks: [], _id: 5ac94af29f43341f2883f342 }
POST /api/list/5ac94af29f43341f2883f342/task 201 1088.834 ms - 132

this another project with 5.0.12

**Comment by lineus** [comment]
and your mongodb server is on localhost? 

my bitbucket account name is nerdfizzle and my email is lineus@gmail.com

**Comment by StanislavRastorguev** [comment]
@lineus yes, mongo in localhost
i invited you in this project, and you can see in github another project, it has problem with 5.0.12 too
https://github.com/StanislavRastorguev/todo-list

**Comment by StanislavRastorguev** [comment]
Since you master of mongoose, can you tell me how solve one problem. When i start mongo before project it works fine, if i reload mongo it works fine, but if i start project and then start mongo, it not connecting.

**Comment by lineus** [comment]
I installed your app, then added the timing bits to your controller, and ran it. In the UI I then created a todo list. 
here's my output on 5.0.4 ( note the save time log )
```
controllers: npm run-script dev

> new-folder@0.0.0 dev /Users/lineus/dev/opc/todo-list
> nodemon

[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
Mongoose connected to mongodb://localhost/todo_list_mean
GET / 304 8.507 ms - -
GET /lib/angular/angular.min.js 304 3.022 ms - -
GET /common/services/todoListData.service.js 304 2.163 ms - -
GET /home/home.controller.js 304 2.791 ms - -
GET /app.js 304 3.318 ms - -
GET /lib/angular/ui-utils.min.js 304 3.327 ms - -
GET /lib/angular/angular-ui-router.min.js 304 3.307 ms - -
GET /common/services/taskData.service.js 304 3.290 ms - -
GET /lib/javascript/jquery.js 304 1.000 ms - -
GET /lib/bootstrap/js/bootstrap.min.js 304 0.917 ms - -
GET /lib/bootstrap/css/bootstrap.min.css 304 1.946 ms - -
GET /lib/stylesheets/style.css 304 1.248 ms - -
GET /home/home.template.html 304 0.446 ms - -
GET /api/lists 304 15.886 ms - -
save time: 39.6
POST /api/list 201 41.744 ms - 76
^Ccontrollers: gv mongoose
    "type": "version",
  "version": "5.0.4"
```
here's my output on 5.0.13 ( note the save time log)
```
controllers: gv mongoose
  "version": "5.0.13"
controllers: mongo --quiet todo_list_mean
> db.dropDatabase()
{ "dropped" : "todo_list_mean", "ok" : 1 }
>
controllers: npm run-script dev

> new-folder@0.0.0 dev /Users/lineus/dev/opc/todo-list
> nodemon

[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
Mongoose connected to mongodb://localhost/todo_list_mean
GET / 304 8.601 ms - -
GET /lib/bootstrap/css/bootstrap.min.css 304 1.813 ms - -
GET /lib/stylesheets/style.css 304 1.240 ms - -
GET /lib/angular/angular.min.js 304 1.557 ms - -
GET /lib/angular/angular-ui-router.min.js 304 1.781 ms - -
GET /lib/angular/ui-utils.min.js 304 1.916 ms - -
GET /app.js 304 1.898 ms - -
GET /home/home.controller.js 304 1.974 ms - -
GET /common/services/todoListData.service.js 304 1.909 ms - -
GET /common/services/taskData.service.js 304 1.892 ms - -
GET /lib/javascript/jquery.js 304 1.898 ms - -
GET /lib/bootstrap/js/bootstrap.min.js 304 0.427 ms - -
GET /home/home.template.html 304 0.501 ms - -
GET /api/lists 304 16.035 ms - -
save time: 48.175
POST /api/list 201 50.364 ms - 76
^Ccontrollers:
```
here's the change to the todoLists.js
```
+  let start = mtime.now();^M
   TodoList.create({
-    name: "new todo list",
+    name: 'new todo list',^M
     tasks: []
   }, (err, lists) => {
     if (err) {
       sendJsonResponse(res, 404, err);
     } else {
+      let distance = (mtime.now() - start) / 1000;^M
+      console.log(`save time: ${distance}`);^M
       sendJsonResponse(res, 201, lists);
     }
```

**Comment by lineus** [comment]
>Since you master of mongoose

I'm just a nutcase who enjoys learning by solving problems ( or trying to )

>When i start mongo before project it works fine, if i reload mongo it works fine, but if i start project and then start mongo, it not connecting.

the mongodb native js driver does not attempt to reconnect on a failed first connection, so the db must be up and running first.

**Comment by StanislavRastorguev** [comment]
@lineus can you try another way pls, install in this tido-list mongo 5.0.12, create few lists, then reload project and try to create task, this where in this todo list i have problem, it creating lists without problem

**Comment by lineus** [comment]
sure:
```
controllersnpm install mongoose@5.0.12
npm WARN @uirouter/angularjs@1.0.15 requires a peer of angular@>=1.2.0 but none is installed. You must install peer dependencies yourself.

+ mongoose@5.0.12
updated 1 package in 5.743s
controllers: npm run-script dev

> new-folder@0.0.0 dev /Users/lineus/dev/opc/todo-list
> nodemon

[nodemon] 1.17.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
Mongoose connected to mongodb://localhost/todo_list_mean
save time: 19.067
POST /api/list/5ac956b9ec2638286cf9754e/task 201 66.179 ms - 146
^Ccontrollers:
```

**Comment by StanislavRastorguev** [comment]
Then i don't understand what is the problem, it's only with some mongoose versions and with some apis and only 1st save after reload. I can ofc just install mongoose 5.0.7 as i did, but it not solving problem.

**Comment by lineus** [comment]
what version of mongodb server are you running locally?

**Comment by StanislavRastorguev** [comment]
i guess it's 3.6.1, can you tell me how i can check it?

**Comment by lineus** [comment]
controllers: mongo --quiet todo_list_mean
> db.runCommand({ serverStatus: 1}).version
3.6.2
>

**Comment by StanislavRastorguev** [comment]
yes, its 3.6.1

**Comment by StanislavRastorguev** [comment]
@lineus idk how it works, we end on this stage or we will try to find problem until we don't solve it?

**Comment by lineus** [comment]
We can pick it back up tomorrow for sure. It’s late here :) maybe we can chat in either the mongoose slack or gitter channel. I have a feeling we blew up some inboxes today!

**Comment by StanislavRastorguev** [comment]
here is 4:51 am ;) sure, can you invite me in slack channel?

**Comment by vkarpov15** [comment]
@StanislavRastorguev worth asking: are you connecting to MongoDB Atlas or are you running MongoDB locally, and if you're running locally are you running with SSL enabled? We had an issue a while back that affected Atlas connections that should be fixed but maybe this is related.

**Comment by StanislavRastorguev** [comment]
@vkarpov15 i'm running MongoDB locally, abut SSL, i didn't turn it on, but idk, maybe it enable automaticly. I'll make more tests with mongoose versions a little bit later. If you need some information for fix, i'll glad to share with you.

**Comment by vkarpov15** [comment]
SSL is off by default, so if you're running MongoDB locally and didn't turn on SSL we can rule out that issue. Here's a couple possible ideas:

1) Try increasing [the `poolSize` option](http://mongoosejs.com/docs/connections.html#options) to 15. Maybe you have some initial operation that's hogging a socket.

2) Is mongoose connected when your first save starts? Print out `db.readyState`, or `TodoList.db.readyState`, if it is '0' that means mongoose isn't connected yet and your `save()` won't start until mongoose has successfully connected.

**Comment by StanislavRastorguev** [comment]
@vkarpov15  i did all your advices, but it don't helps

my connection
const mongoose = require('mongoose');
const dbURI = 'mongodb://localhost/trello_clone';
mongoose.connect(dbURI, {poolSize: 15});

const db = mongoose.connection;

db.on('error', (err) => {
  console.log('Mongoose connection error: ' + err);
});
db.on('connected', () => {
  console.log('Mongoose connected to ' + dbURI);
  console.log('Ready state ' + db.readyState)
});
db.on('disconnected', () => {
  console.log('Mongoose disconnected');
});

some information from console
Mongoose connected to mongodb://localhost/trello_clone
Ready state 1
PUT /api/board/5ac840c27f7a1718d8390dfb/lists 200 1192.622 ms - 7317
it's first save

**Comment by StanislavRastorguev** [comment]
@vkarpov15 with mongoose 5.0.15 it works fine? this save i tested with mongoose 5.0.12

**Comment by vkarpov15** [comment]
Glad it's fixed! :+1:
