### ISSUE TITLE
How automatically create databases and collections?

### ISSUE THREAD

**Issue by Jinshihao** [Automattic/mongoose#6326]
I create a connection use createConnection,but the mongodb not have any database and collections.

```
const db = mongoose.createConnection(config.db, {
    poolSize: 20
});

db.once('connected', async () => {
    logger.info("connect success");
});

db.on('error', (err) => {
    logger.error("Error in mongodb connection: ", err);
    db.disconnect();
});
```

NodeJS Version: 8.11.1
mongoose Version: 5.0.12
Mongodb Version: 3.6.3

**Comment by lineus** [comment]
Hi @Jinshihao,

In order to create a collection with mongoose you need to create a Model and save a document.
Consider the following example:

### 6326.js
```js
'use strict'

const mongoose = require('mongoose')
const uri = 'mongodb://localhost/test'
const db = mongoose.createConnection(uri)
const Schema = mongoose.Schema

const testSchema = new Schema({
  name: String,
  age: Number
})

const Test = db.model('test', testSchema)

const test = new Test({ name: 'Billy', age: 31 })

db.once('connected', function (err) {
  if (err) { return console.error(err) }
  Test.create(test, function (err, doc) {
    if (err) { return console.error(err) }
    console.log(doc)
    return db.close()
  }) 
})
```
### output: 
```
issues: mongo --quiet test
> show dbs
local  0.000GB
>

issues: node ./6326.js
{ _id: 5aca1aaf5980fe6eb243c8ab, name: 'Billy', age: 31, __v: 0 }

issues: mongo --quiet test
> show collections
tests
>

issues: mongo --quiet test
> db.tests.find().pretty()
{
        "_id" : ObjectId("5aca1aaf5980fe6eb243c8ab"),
        "name" : "Billy",
        "age" : 31,
        "__v" : 0
}
>
issues:
```

If you have any questions or just want to chat about mongoose, feel free to join us on the [slack channel for mongoose](https://mongoosejsteam.slack.com/) or the [gitter community for mongoose](https://gitter.im/Automattic/mongoose)

**Comment by Jinshihao** [comment]
@lineus I've solved the problem, because I used the global `mongoose.Model() ` when I mounted the Schema. thx for your reply.

**Comment by abhirocks550** [comment]
> @lineus I've solved the problem, because I used the global `mongoose.Model() ` when I mounted the Schema. thx for your reply.

How did fix your problem?

**Comment by vkarpov15** [comment]
Use the [`autoCreate` schema option](https://mongoosejs.com/docs/guide.html#autoCreate)
