### ISSUE TITLE
Fix for Apply defaults after setting initial value doesn't work on find

### ISSUE THREAD

**Issue by mjgallag** [Automattic/mongoose#6330]
Fix for Apply defaults after setting initial value doesn't work on find. The default function runs but the values of existing fields are undefined. Defaults not based on existing fields are correctly set on find for documents where they did not previously exist (i.e. a new default field).

https://github.com/Automattic/mongoose/issues/3781
https://github.com/Automattic/mongoose/pull/6119

Note that I tested this in  `5.0.14`

**Comment by vkarpov15** [comment]
Can you provide some code samples please? This bug report isn't very actionable
