### ISSUE TITLE
MongoDB 1243 ($[] notation) - Mongoose Support?

### ISSUE THREAD

**Issue by shivpatel** [Automattic/mongoose#6333]
Does Mongoose support the functionality added in https://jira.mongodb.org/browse/SERVER-1243 (MongoDB 3.5.12)?

I am specifically interested in the update all documents in array capability:

```
db.coll.update({}, {$set: {“a.$[].b”: 2}})
Input: {a: [{b: 0}, {b: 1}]}
Output: {a: [{b: 2}, {b: 2}]}
```

I have tried this syntax style with Mongoose 4.11.9 and 5.0.14 and get the following error:

`MongoError: '$unset' is empty. You must specify a field like so: {$unset: {<field>: ...}}`

My code looks like this:

`await MyModel.update({ someId }, { $unset: { 'friends.$[].relation': 1 } });`

**Comment by vkarpov15** [comment]
@shivpatel mongoose 5.x does have support for this syntax. Can you please provide your schemas and more substantial code samples? We [added tests for this](https://github.com/Automattic/mongoose/commit/4ffbb4b6345db0daf8d79be4665d08ea1f907d11) and those tests are passing.
