### ISSUE TITLE
The promise api doubts

### ISSUE THREAD

**Issue by mariodu** [Automattic/mongoose#6335]
versions: 
+ mongoose 5.x

see the code:

```javascript
const query = User.findOne();
const result = await query;
```
why `query` is a instance of `Query`, but not a normal promise object?

I should call `then` or `exec` to get promisify return. I think it's easy to be confused.

```javascript
const result = await User.findOne().then((d) => d);
```

**Comment by lineus** [comment]
@mariodu 

> why query is a instance of Query, but not a normal promise object?

In addition to having all of the same behaviors as Promise, the Query instance also has several additional methods like `.populate()`, `.and()`, `.where()`, and `.gte()` [documented here](http://mongoosejs.com/docs/api.html#Query). These are referred to as query builder methods. They help make very human-readable queries like:

`Users.find({}).where('name', 'betty').gte('age', 23).populate('address' 'zipcode -_id')`

> I should call then or exec to get promisify return.

Consider the following contrived example:

### 6335.js
```js
#!/usr/bin/env node
'use strict';

function getPromise(val) {
  return new Promise(function(resolve, reject) {
    if (val > 0) {
      return resolve('Hello World');
    } else {
      return reject(new Error('GoodBye World'));
    }
  });
}

async function run() {
  let res = await getPromise(1);
  console.log(res);
  let fail = await getPromise(0);
}

run().catch(console.error);
```
### outputs:
```
issues: ./6335.js
Hello World
Error: GoodBye World
    at getPromise (/Users/lineus/dev/Help/mongoose5/issues/6335.js:8:27)
    at run (/Users/lineus/dev/Help/mongoose5/issues/6335.js:15:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
issues:
```

Notice that in my example, await resolves/rejects the returned promise ( just like it does the returned query ) for you. In other words, when you **await** a promise, `.then()` or `.catch()` is executed implicitly.

**Comment by mariodu** [comment]
Get your point.

In some cases, `.then()` or `.catch()` not must be called. The other module may be doing this like:

```
const urllib = require('urllib');

await urllib.request('http://google.com');
// same as
await new Promise((resolve, reject) => {
  urllib.request('http://google.com', (err, res) => {
    if(err) return reject(err);
    return resolve(res);
  });
});
```

Some people will be used to think it's the same.

**Comment by mariodu** [comment]
The wrong example: https://github.com/myfjdthink/pandora-koa-mongoose-demo/blob/master/src/App.ts#L21

Found it in one of our feedback. It use Chinese to describe, so may be have trouble to understand.
But the key question is what I wrote above.

https://github.com/midwayjs/pandora/issues/221

**Comment by lineus** [comment]
@mariodu I tried both of the examples you provided, and in both cases, queries behave exactly like promises.

> Use mongoose like this, but query not work.

### 6335.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test1 = new Test({ name: 'billy' });
const test2 = new Test({ name: 'sarah' });

async function run() {
  await conn.dropDatabase();
  await Test.create([test1, test2]);
  let doc = await new Promise((resolve, reject) => {
    Test.findOne({}, (err, doc) => {
      if (err) { return reject(err); }
      return resolve(doc);
    });
  });
  console.log(doc);
  return conn.close();
}

run();
```
### output:
```
issues: ./6335.js
{ _id: 5ad2060b02a1be498249ba9a, name: 'billy', __v: 0 }
issues:
```

>The wrong example

I copied the async functions from the example you provided and ran them with just mongoose:

### 6335.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test1 = new Test({ name: 'billy' });
const test2 = new Test({ name: 'sarah' });

async function d1() {
  return await d2();
}

async function d2() {
  const user = await Test.findOne();
  return user;
}

async function run() {
  await conn.dropDatabase();
  await Test.create([test1, test2]);
  const name = await d1();
  console.log(name);
  return conn.close();
}

run();
```
### output:
```
issues: ./6335.js
{ _id: 5ad203a15a014d48d630d3d8, name: 'billy', __v: 0 }
issues:
```

**Comment by mariodu** [comment]
I think `User.findOne()` and `User.findOne().then()` may have difference with executed.

**Comment by vkarpov15** [comment]
I don't really understand what the issue is here. The reason why `User.findOne()` returns a query object is because [mongoose has a chainable query builder](http://mongoosejs.com/docs/queries.html), so you can chain method calls to construct a query. `await User.findOne();` should work fine, see [this article on mongoose with async/await](http://thecodebarbarian.com/using-async-await-with-mocha-express-and-mongoose#mongoose).
