### ISSUE TITLE
Mongoose version 5.0.13 stops responding after a while

### ISSUE THREAD

**Issue by gsteri1** [Automattic/mongoose#6338]
Hello,

I am reporting a presumed bug. I am running Mongoose v5.0.13 under Node 8.9.4 with MongoDb version 3.0.4. The setup is as follows:

On one openSUSE server reside Node and a MongoDb instance. The server is not under any extreme load, the load average numbers rarely make it over 1.0. There is no replication. There are no network hops between app and db, the total size of the db is 6.4Gb on disk. The primary use pattern is adding to a collection and reading back the most recent adds.

Node is hosting a custom webapp which uses express and other node libraries. Mongoose is used (primarily) to persist a set of documents which correspond roughly to "Tweets". The documents are composed of plain text (the tweets) and an image stored as a Base64 string. Every morning, the user (primarily me) creates some content and submits it to the appropriate social media platform. 

The mode of operation has been the same for two years. I have used Mongoose since v4.11.3. I upgraded my setup last week. I moved from v5.0.0-rc2 to the most recent I could find v5.0.13. Here are the symptoms:

1. General sluggishness: This is not something which I can give metrics on, but the portions of the App which are dependent on the db (in an async fashion) take a lot longer to return with documents.

2. Reads start to fail:  That is, I can verify documents matching a criterion exist, but none will return. This is driven by load and usage. The more times I use the app, the more likely the reads are to fail.  

3. The Mongoose connector hangs: After failing reads, the connector will cease to respond. 

What have I done to debug?

1. Elements of the app which are not dependent on Mongoose continue to function. The Node event queue is not in any weird state, it continues to function. 

2. Restarting the db does nothing. If I stop and restart the daemon, nothing happens. Mongoose (apparently) stays in this weird state. 

3. A recycle of the app: pm2 stop 0, pm2 start 0 causes everything to resume working. Missing records "come back" and application functions as it has for two years. 

 I assume this will eventually resolve to idiot user error, but in the mean time what can I do to further debug this assumed issue? 

Thank you,

-Greg

**Comment by vkarpov15** [comment]
This bug report is exceedingly vague, I'd need a lot more information before I could make an educated guess. Regarding general sluggishness, no ideas. Regarding the read failures, does this app go through long periods of inactivity, where no database operations happen? Your socket might be timing out if that's the case: https://scalegrid.io/blog/understanding-mongodb-client-timeout-options/

**Comment by lineus** [comment]
@gsteri1 are you still experiencing this issue?

**Comment by gsteri1** [comment]
I installed the new version. 
Good:The queries seem to have gone back to being very quick.
Bad: The whole application stops responding as it waits for mongoose to process a query. This is happening much quicker now. Where I restarted once or twice a week. I needed to restart since yesterday. The writes seem unaffected-only find and findOne.

**Comment by gsteri1** [comment]
It has just stopped responding again.

**Comment by lineus** [comment]
@gsteri1 Can you either create a reproducible code example or share a link to your repo so that we can assist you?
