### ISSUE TITLE
will support mongodb 4.0 multi-document ACID transactions？

### ISSUE THREAD

**Issue by chelsh** [Automattic/mongoose#6342]
will support mongodb 4.0 multi-document ACID transactions？

**Comment by vkarpov15** [comment]
Yes, as soon as we can after the [mongodb driver finalizes their transaction support](https://github.com/mongodb/node-mongodb-native/pull/1681)

**Comment by Rukeith** [comment]
@vkarpov15 The PR is merge. Does it means mongoose now support transaction?

**Comment by lineus** [comment]
@Rukeith Yes. it's supported in 5.2.

**Comment by Rukeith** [comment]
@lineus Does it have any demo ? Because I couldn't find it in document.

**Comment by lineus** [comment]
@Rukeith check out [This post on @vkarpov15's blog](http://thecodebarbarian.com/a-node-js-perspective-on-mongodb-4-transactions.html) There's a section on transactions in mongoose.

**Comment by Rukeith** [comment]
@lineus Thanks, it helps me a lot.
