### ISSUE TITLE
Can't save a DBref changes

### ISSUE THREAD

**Issue by etshy** [Automattic/mongoose#6345]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug.
**What is the current behavior?**
can't save DBRef changes

**Please mention your node.js, mongoose and MongoDB version.**
node : v8.9.4
mongoose : "mongoose": "^5.0.14" (from package.json)

-------------------

so  here is my situation (it'll be long):

I have a symfony app working with DoctrineODM and Reference in ODM use DBREF Object.
I did a node script to get some items, made little changes (using a node package) and then save the changes.

in this script, I use mongoose and mongoose-gridfs

```
var mongoose = require('mongoose');
var fs = require('fs');
var stream = require('stream');

var chapterId = process.argv[2];
var seed = process.argv[3];
var url = 'mongodb://XXX';

var imgScramble = require('image-scramble');
```

Once connected I somehow managed to get the DBRef (and can use its $id property) with the following schemas/model
```


    Schema = mongoose.Schema;
    // setup the schema for DB


    //instantiate mongoose-gridfs
    var gridfs = require('mongoose-gridfs')({
        collection:'files',
        mongooseConnection: mongoose.connection,
        model: 'Files'
    });

    //Files = gridfs.model;
    var FilesSchema = gridfs.schema;

    FilesSchema.add({
        _id: Schema.Types.ObjectId,
        name: String,
        mime: String,
        filename: String,
        type: String
    });

    Files = mongoose.model('Files', FilesSchema);

    var imageSchema = new Schema({
        oid: Schema.Types.ObjectId
    });
    imageSchema.virtual('id',{
        ref:'Files',
        localField: 'oid',
        foreignField: '_id'
    });

    var pageSchema = new Schema({
        order: Number,
        image: imageSchema,
        scrambled: Boolean
    });

    var ChapterSchema = new Schema({
        _id: Schema.Types.ObjectId,
        pages: [pageSchema]
    });

    var Chapter = mongoose.model('Chapter', ChapterSchema, "Chapter");
```

with this all, I can access `chapter.pages[0].image.oid` to have the $id of the reference when I do the find()

```
Chapter.findById(chapterId)
        .populate('pages.image.id')
        .exec(*...
```

after that I loop through the pages and find the file

```
    var file = currentPage.image;
    Files.findById(file.oid)
         .exec(...
```

once I'm sure the file exist, I read it to have the buffer to use in the imgScramble function

```
Files.readById(file.id, function(error, buffer){
    if(error) {
        console.log(error);
    }
    imgScramble({
        image:buffer, // source Buffer
        seed:seed, // seed
        sliceSize:8, // slice size
        buffer:true
    },function(err, scrambled){
        ...
    })
```

Once it's scrambled I save it with the `Files.write()` method of `mongoose-gridfs`
and once it's saved, I update it (because mongoose-gridfs add property I don't need and don't want to keep)

After all that, the problem is to save this new File id in my reference on chapter.pages[x].image

I tried the following things but non worked to change the $id property of the DBRef.
```
chapter.page[x].image.id = newFile.id; // does nothing
chapter.page[x].image._id = newFile.id; // change the _id of the DBRef Object on node, but add a _id property on Database
chapter.page[x].image.oid = newFile.id; // add a oid property on database
chapter.page[x].image.$id = newFile.id; // does nothing ($id is not added on node DBRef object so not save on Database)
```

So i manage to have all my script works, except the `chapter.save()` to save the new file in my chapter.page[x].image DBRef.

Also I tried to treat the image DBRef as an ARRAY type, to acces/change its property like i want, but the `find()` always return an object like :
```
image:
     { _id: 5ad21e71894bb34410648b71,
       _bsontype: 'DBRef',
       namespace: 'files',
       oid: 5acfabc5de75345dbc001aad,
       db: 'readDat' }
```

It's my first time with node and mongoose, and I'm completely lost with this DBRef thing.
Thanks in advance if someone could help me.

ps : If posting my entire script could help, or if a point is unclear, let me know.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:

**Comment by vkarpov15** [comment]
@etshy as you probably noticed, mongoose doesn't have support for the DBRef type because we have our own notion of refs. Your best bet would be to mark `image` as a [`Mixed` type](http://mongoosejs.com/docs/schematypes.html#mixed) so you can make modifications easily, the below script works for modifying the DBRef's `oid` property.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh6345`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
mongoose.Promise = global.Promise;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const { DBRef, MongoClient, ObjectId } = require('mongodb');

  const client = await MongoClient.connect(connectionString);
  await client.db().collection('tests').insertOne({
    ref: new DBRef('tests2', new ObjectId(), GITHUB_ISSUE)
  });

  const TestSchema = new mongoose.Schema({
    ref: {}
  });

  const Test = mongoose.model('Test', TestSchema);

  const doc = await Test.findOne();

  console.log('Before modification', doc);

  doc.ref.oid = new ObjectId();
  doc.markModified('ref');

  await doc.save();

  console.log(await Test.findOne());
  // Bypass mongoose and use the underlying mongodb driver
  console.log(await Test.collection.findOne());
}
```
