### ISSUE TITLE
Discriminator schema path: convert unique index to partial unique index

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6347]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When a discriminator schema path is created with the `unique: true` option, the resulting index  on the collection breaks the discriminator. The unique index on the collection means that the 2nd document ( and every one after it ) saved in the collection without that path will technically be a duplicate and cause save fails. There is a way to allow unique index creation though, by instead creating a [partial unique index](https://docs.mongodb.com/manual/core/index-partial/#partial-index-with-unique-constraint) that filters the unique index on the discriminator key.

Excerpt from the example in #6343:

### this breaks the discriminator:
```
const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String, unique: true, index: true },
  firstName: { type: String },
});

const User = Base.discriminator('userdetails', userSchema);
```
### this does not:
```
const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String },
  firstName: { type: String },
});

userSchema.path('emailId').index({ 
  unique: true, 
  partialFilterExpression: {
    '__type': 'userdetails'
  }
});
const User = Base.discriminator('userdetails', userSchema);
```

**What is the expected behavior?**

It would be a helpful feature for mongoose to detect the unique option on the schema paths **of discriminators** and create the partial unique index on the collection for the user instead of the unique index. 

Alternatively, If this seems like too much magic, I think mongoose should throw an error when a user creates a unique index on a discriminator schema path.

**Please mention your node.js, mongoose and MongoDB version.**
This would be applicable only to MongoDB 3.2 and higher

**Comment by vkarpov15** [comment]
That's a very good idea. Even easier would be to use a sparse index, and that would work with mongodb 3.0.
