### ISSUE TITLE
Mongoose query on a very small collection takes 2.1ms

### ISSUE THREAD

**Issue by TheCactusBlue** [Automattic/mongoose#6348]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Mongoose takes between 2~2.2 seconds to execute a query
**If the current behavior is a bug, please provide the steps to reproduce.**
Measure model findOne speed using console.time.

**What is the expected behavior?**
When tried directly from mongo shell, it takes much less. Query on a collection with 1 document should not take 2.2 seconds.

**Please mention your node.js, mongoose and MongoDB version.**
Node 9.3.0, Mongoose 5.0.14, MongoDB 3.6.1

```javascript
const mongoose = require("mongoose");

mongoose.connect("mongodb://localhost/databasename").then(async function(){
  const schema = new mongoose.Schema({
    name: {type: String, required: true, index: true, unique: true},
    email: {type: String, required: true, index: true, unique: true},
  });

  const model = mongoose.model("Account", schema);

  console.time("query");
  await model.findOne({email: "thecactusblue@gmail.com"});
  console.timeEnd("query");
});
```
Just removed a bunch of stuff from my project file, got an example. For the reference, my collection contains only one document ATM.

**Comment by TheCactusBlue** [comment]
I've confirmed it to be a bug: testing with mongoose 5.0.9 gives a much higher result of 20ms per query.

**Comment by lineus** [comment]
Some attempts to replicate this behavior.

**I added a document in the collection**  
**With the following versions:**
   node 9.3.0
   mongoose 5.0.14
   mongodb 3.6.2

**Here is my output:**
```
issues: ./6348.js
query: 23.116ms
^C
issues:
```

**After adding a call to connection.close and augmenting the console.time string**
like this:
```
  const str = `query>${mongoose.version}`;
  console.time(str);
  await model.findOne({ email: 'thecactusblue@gmail.com' });
  console.timeEnd(str);
  return mongoose.connection.close();
});
```

**I ran the following loop several times to install each version since 5.0.10 and run the example:**

```
iissues: for i in 10 11 12 13 14; do npm install mongoose@5.0.${i} >/dev/null 2>&1 && ./6348.js; done
query: 18.838ms
query: 19.201ms
query: 22.183ms
query: 25.972ms
query: 25.597ms
issues: for i in 10 11 12 13 14; do npm install mongoose@5.0.${i} >/dev/null 2>&1 && ./6348.js; done
query: 19.060ms
query: 18.083ms
query: 25.747ms
query: 24.900ms
query: 23.410ms
issues: for i in 10 11 12 13 14; do npm install mongoose@5.0.${i} >/dev/null 2>&1 && ./6348.js; done
query: 18.202ms
query: 23.081ms
query: 23.388ms
query: 25.315ms
query: 27.246ms
issues: for i in 10 11 12 13 14; do npm install mongoose@5.0.${i} >/dev/null 2>&1 && ./6348.js; done
query: 19.408ms
query: 19.281ms
query: 27.799ms
query: 24.269ms
query: 25.085ms
issues:
```

**Comment by TheCactusBlue** [comment]
Currently using 4.13.12 until the problem is fixed.

**Comment by vkarpov15** [comment]
@TheCactusBlue are you connecting to a local mongodb instance or are you connecting to Atlas?

**Comment by TheCactusBlue** [comment]
I am testing on a local instance.

**Comment by martonboti** [comment]
I can confirm. It occurs when trying to run tests, they all fail because a simple query takes more than 2 seconds. Version 4.13.12 works fine.

**Comment by vkarpov15** [comment]
Hmm @TheCactusBlue is there any way we can hop on a video chat? I haven't been able to repro and I don't think we'll be able to make much progress on this via GitHub issues, we'll need a faster feedback loop.
