### ISSUE TITLE
TypeError: callback.apply is not a function

### ISSUE THREAD

**Issue by DavidHaintz** [Automattic/mongoose#6352]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Crashes on update negative increase.
> TypeError: callback.apply is not a function
>     at /***/node_modules/mongoose/lib/model.js:3950:16
>     at Immediate._handleWriteOpResult (/***/node_modules/mongoose/lib/queryhelpers.js:261:12)
>     at Immediate._onImmediate (/***/node_modules/mquery/lib/utils.js:119:16)
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ***@1.0.0 start: `node ./src/Server.js`
> npm ERR! Exit status 1

**If the current behavior is a bug, please provide the steps to reproduce.**
`await whereResult.update({ $inc: { x: -1 } }).exec();`

**What is the expected behavior?**
Should just work as positive increase.

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose 5.0.14
Node 8.11.1
MongoDB 3.6

**Comment by lineus** [comment]
Hi @DavidHaintz The following example shows that it should work as you expect:

### 6352.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  num: Number
});

const Test = mongoose.model('test', schema);

const test = new Test({ num: 1 });

async function run() {
  await conn.dropDatabase();
  const saved = await test.save();
  await saved.update({ $inc: { num: -1 } });
  const doc = await Test.findOne({ _id: test._id });
  console.log(doc.num);
  return conn.close();
}

run();

```
### output:
```
issues: ./6352.js
0
issues:
```

Can you include a complete example that demonstrates the behavior you're seeing? Feel free to modify mine to replicate the behavior of your current code.

**Comment by DavidHaintz** [comment]
Sorry, I can't provide more data. The exact same code with positive value (1) works. Starting value is bigger than 0 (but shouldn't matter, right?).

Thanks for your reply!

**Comment by DavidHaintz** [comment]
Seems like the issue is on my side. I'll close since it's not reproducable.
