### ISSUE TITLE
Model includes() does not works as indexOf(). 

### ISSUE THREAD

**Issue by mapo-job** [Automattic/mongoose#6354]
**Report *bug***

**What is the current behavior?**
Model includes() does not works as indexOf().  As define here: [Includes  ES6 ](https://nodesource.com/blog/six-of-the-most-exciting-es6-features-in-node-js-v6-lts/#checkingarrayvalueswitharrayincludes)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use these schema:
```
var User = new Schema({
    name:{
        type: String,
        default: ''
    }
});

var relationSchema = new Schema({
    user:  { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    friends: [ { type: mongoose.Schema.Types.ObjectId, ref: 'User' } ]
});
```

2. Insert doc in DB

User:
```
{ 
     "_id" : ObjectId("5acd4da4c271813c48bcd843"), 
    "name" : "Alice"
},
{
    "_id" : ObjectId("5ad4eb200a67063840c158d5"), 
    "name" : "Bob"
}
```
Relation:
```
{ 
    "_id" : ObjectId("5acd7fa7f7be5030fc626dd0"), 
    "friends" : [
        ObjectId("5ad4eb200a67063840c158d5")
    ], 
    "user" : ObjectId("5acd4da4c271813c48bcd843"), 
}
```

3. Test the method.
```
let userId= "5acd4da4c271813c48bcd843";
let friendId= "5ad4eb200a67063840c158d5";

//Relation contains the friendId in friends
Relations.findOne({user: userId})
    .then((rel) => {
        consloe.log(rel.friends.includes(friendId)); // false
        console.log(rel.friends.indexOf(friendId)); //0
```

**What is the expected behavior?**
indexOf and includes must return the same results

**Please mention your node.js, mongoose and MongoDB version.**
Node v8.9.1
Mongoose v5.0.14
MongoDb v3.4.4

**Comment by mapo-job** [comment]
Hi @lineus,
    Thanks for the clarification, I understand that adding `MongooseArray.includes()` would be a backward compatibility issue and prefer if it's in a major release. Until then, I'll use indexOf...  

I try with ObjectID but the object is not the same so it does not work.

```
console.log(relation.friends.indexOf(user1.id)); //1
console.log(relation.friends.indexOf(new ObjectID(user1.id))); //1

console.log(relation.friends.includes(user1._id)); // true note the use of _id
console.log(relation.friends.includes(new ObjectID(user1.id))); //false
console.log(relation.friends.includes(new mongoose.Types.ObjectId(user1.id))); //false
```

**Comment by khaledosman** [comment]
just ran into this issue..
I agree adding MongooseArray.prototype.includes as a new feature would be great since its an expected behaviour. 

Most other Array methods are implemented in MongooseArray so it can be very confusing to figure out why includes doesn't work.

**Comment by Smembe812** [comment]
I just ran into similar problem 

`rel.friends.includes(friendId)` is comparing a String to Objetcs, so using Array.prototype.includes() shouldn't work

However, the code below should work.

`
console.log(JSON.stringify(rel.friends).includes(friendId)) // true
`

**Comment by hansemannn** [comment]
I added a pull request: https://github.com/Automattic/mongoose/pull/7732

**Comment by magbicaleman** [comment]
I noticed locally listofObjectIds.includes(user._id) worked but in a Heroku environment `.includes` array prototype did not work the same, so locally it was returning true, but on Heroku same code was returning false.

I ended up mapping to string, but perhaps I'll change to indexOf.

```
const isFriend = friends.map(f => f._id.toString()).includes(user._id.toString);
```

**Comment by vkarpov15** [comment]
@magbicaleman are you sure you were running the same version of Mongoose locally and on Heroku? Which version?
