### ISSUE TITLE
Adding toHexString() function causes a document to pass ObjectId.isValid test

### ISSUE THREAD

**Issue by jwhollingsworth** [Automattic/mongoose#6359]
**What is the current behavior?**
After upgrading to mongoose 5.0.15 -- with the addition of the 'toHexString()' function (#6115) -- documents are now considered valid ObjectIds because of the below check in ObjectID.isValid() of the bson module (https://github.com/mongodb/js-bson/blob/1.0-branch/lib/bson/objectid.js#L351):

```
ObjectID.isValid = function isValid(id) {

...

  // Duck-Typing detection of ObjectId like objects
  if (id.toHexString) {
    return id.id.length === 12 || (id.id.length === 24 && checkForHexRegExp.test(id.id));
  }
};
```
If nothing else, this change may have more impact than first realized. For all I know, this is the intended behavior, but adding this in case this effect was not considered. 

It at least causes breaking changes to my code, as I was relying on ObjectID.isValid to tell me if a field was populated or not -- where a populated field would be invalid, and an unpopulated field valid (again, there is likely a better way to do this -- including using the newly added toHexString()).

Contrived example below:
```
let user = await User.findOne({name: 'test'}).populate('project');
let projectId = (ObjectId.isValid(user.project)) ? user.project : user.project._id;
```
But where in 5.0.14, projectId was assigned user.project._id, it now is assigned user.project (the populated project document).

**Comment by vkarpov15** [comment]
Thanks for catching this, we'll fix this issue ASAP. We had not considered this issue when adding `toHexString()`.
