### ISSUE TITLE
First-class support for sessions

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6362]

**Comment by thaoula** [comment]
Hi @vkarpov15,

Thanks for your work on this!

When are you aiming to release a test version. Mongo DB 4 beta has just been released and we would love to start playing around with transactions.

Regards,
Tarek

**Comment by vkarpov15** [comment]
@thaoula we normally don't do formal beta programs with mongoose, but we may for this release if there's sufficient demand for it. Is this blocking you from trying out transactions?

**Comment by thaoula** [comment]
Hi @vkarpov15,  yeah, it is a little blocking.

**Comment by thaoula** [comment]
Hi @vkarpov15,

Is this now available on 5.1?

Many thanks for this.

Regards,
Tarek

**Comment by vkarpov15** [comment]
@thaoula yes it is in 5.1. We need to add better docs, but the general idea is that `findOne({}, null, { session })` means that future `save()` calls on that document will use the same session, and `doc.$session()` lets you get/set the session associated with a document

**Comment by vkarpov15** [comment]
See:

http://mongoosejs.com/docs/api.html#document_Document-$session

http://mongoosejs.com/docs/api.html#query_Query-setOptions
