### ISSUE TITLE
Using Delete > Create

### ISSUE THREAD

**Issue by mattc41190** [Automattic/mongoose#6369]
https://github.com/Automattic/mongoose/blob/0693937abb8bc55a696795f48ab75553f0342cc4/docs/api.html#L343

Looks like a simple case of copy paste :)

**Comment by mattc41190** [comment]
<img width="934" alt="screen shot 2018-04-19 at 1 41 28 pm" src="https://user-images.githubusercontent.com/8837616/39011603-88298d48-43d7-11e8-98a4-1cf85e46ae7a.png">

**Comment by vkarpov15** [comment]
Closed by #6370
