### ISSUE TITLE
Runner error: Overflow sort stage buffered data usage...

### ISSUE THREAD

**Issue by cnits** [Automattic/mongoose#6371]
**## Report Issue**

I met this case: 
> Runner error: Overflow sort stage buffered data usage of 33567746 bytes exceeds internal limit of 33554432 bytes

**Memo**
- I have a dataset with 844 documents.
- I paginate them with page size: 15 and total page: 57
- From page 1 -> 27, getting data is OK.
- But from page 28 -> end, it throw the above message.
- **Note**: When I run by mongo shell, everything is OK.

**Thanks in advance.**

**Additional Info**
> Nodejs v.9.11.1
> Mongoose v5.0.15
> MongoDB v2.2.33

**Comment by lineus** [comment]
@cnits can you please include more details?

For instance:
   1. What code causes it to fail? 
   1. What commands are you running in the mongo shell that succeed? 
   1. What does your schema look like?
   1. Do you have any indexes created on the collection?

**Comment by cnits** [comment]
@lineus Thank you for you reply. 
For more details:

1. `myModel.find({}).sort({name: -1}.skip(27).limit(15)`

2. `db.getCollection('mymodel').find({}).sort({name: -1}.skip(27).limit(15)`

3. `mongoose.model("mymodel", new mongoose.Schema({code: string, name: string}));`

4. I have no any index.

Thanks!

**Comment by lineus** [comment]
@cnits can you create an index on the collection for name ( either by adding the index option to your schema path for name, or issuing the create index command in mongodb)? I'm researching why it would work in the shell but not in mongoose, but having the index should help.

**Comment by cnits** [comment]
Thank you, @lineus .

I'll try with setting the index.

**Comment by lineus** [comment]
@cnits did adding the index fix the problem?
