### ISSUE TITLE
Why was findOneAndUpdate() changed to returning the old document by default?

### ISSUE THREAD

**Issue by mweiczorek** [Automattic/mongoose#6377]
Not a bug, but the rationale behind requiring `{ new: true }` to be set is something I want to understand.

I realize it's the default in Mongo, but isn't the point of an abstraction library to hide away some of the nitty-gritty of the native API?

For update operations, returning the NEW document by default is simply the more logical choice - as opposed to explicitly passing an option that fits 99% of use cases, makes as much sense as writing an operating system in PHP.

Again, I'd like to know *why*.

Ta.

**Comment by vkarpov15** [comment]
Thanks for clarifying @lineus . `new: true` is what I use more often personally, but an abstraction library should provide meaningful benefit, and in this case I don't think we provide enough benefit by making `new: true` by default. You can easily make it true by default across your entire app:

```javascript
mongoose.plugin(schema => {
  schema.pre('findOneAndUpdate', function() {
   if (!('new' in this.options)) {
     this.setOptions({ new: true });
   }
  });
});
``
