### ISSUE TITLE
mongoose doesn't load property which value is empty object

### ISSUE THREAD

**Issue by bhushankumarl** [Automattic/mongoose#6380]
I am using mongoose : 5.0.15

**Do you want to request a *feature* or report a *bug*?**
It does look like a bug.

**What is the current behavior?**
I am not able to retrieve properties which are empty. i.e `address : {} ` than Non of find query does return address property in response.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add any document in the MongoDB.
Mark one of property is empty OBJECT  i.e `address : {} `
Execute any findOne query
You will see in response, you will not get the `address: {} ` when it is empty.

**What is the expected behavior?**
All find query should return all properties whether it does empty or not.

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB shell version: 3.2.19

**Comment by lineus** [comment]
@bhushankumarl Check out the schema option [minimize](http://mongoosejs.com/docs/guide.html#minimize). 

Here is an example:

### 6380.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema1 = new Schema({
  name: String,
  hobbies: {}
});

const One = mongoose.model('one', schema1);

const schema2 = new Schema({
  name: String,
  hobbies: {}
}, { minimize: false });


const Two = mongoose.model('two', schema2);

const one = new One({
  name: 'ONE',
  hobbies: {}
});

const two = new Two({
  name: 'TWO',
  hobbies: {}
});

async function run() {
  await conn.dropDatabase();
  const min = await one.save();
  console.log(min);
  const notMin = await two.save();
  console.log(notMin);
  return conn.close();
}

run();
```

### Output:
```
issues: ./6380.js
{ _id: 5adc7bc015290134facfcdef, name: 'ONE', __v: 0 }
{ _id: 5adc7bc015290134facfcdf0,
  name: 'TWO',
  hobbies: {},
  __v: 0 }
issues:
```

**Comment by bhushankumarl** [comment]
I am using the nested property :
```

const userSchema = new Schema({
    email: String,
    password: String,
    locations: {
        business: {
            address: {
                country: String,
                locality: String
            },
            coordinates: {
                lat: String,
                lng: String
            }
        }
    },
    isEnable: Boolean,
    isEmailVerified: Boolean
}, {minimize: false});
const userModel = mongoose.model('users', userSchema, 'users');
```

And when I use ``` {minimize: false} ``` option. It does show me all children in output :oncoming_police_car: 

```
    "locations": {
        "business": {
            "address": {},
            "coordinates": {}
        }
    }
```

My actual document is like : 
```
    "locations": {
        "business": {
        }
    }
```

**Comment by bhushankumarl** [comment]
@lineus Thank you.

**Comment by adamreisnz** [comment]
For anyone reading this, note that this setting also affects schema's which explicitly define an empty object as a default value for a property, e.g.

```
foo: {
    type: {},
    default: {},
  },
```

When the document is converted to JSON, it will *not* include the `foo: {}` property as expected, unless the `{minimize: false}` option is used. Not sure if this could be classified as a bug or expected behaviour, but setting the option to false works for us.
