### ISSUE TITLE
Db.prototype.authenticate error

### ISSUE THREAD

**Issue by ntlzz93** [Automattic/mongoose#6382]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

> Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
let connectOptions = {
    useMongoClient: true,
    autoReconnect: true,
    // promiseLibrary: global.Promise
};
mongoose.Promise = global.Promise;
mongoose.connect(db_url: 'mongodb://username:password@host:27017/database', connectOptions);
```
**What is the expected behavior?**
no throw this warning again

**Please mention your node.js, mongoose and MongoDB version.**
Node 8.11.0 LTS
MongoDB version: 3.6.4
Mongoose: 4.13.12

**Comment by lineus** [comment]
I set up a db with auth enabled and attempted to reproduce this with the following code:

### 6382.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');

console.log(mongoose.version);

const connectOptions = { 
  useMongoClient: true,
  autoReconnect: true
};

const uri = 'mongodb://testUser:testPass@localhost:27072/database';

mongoose.Promise = global.Promise;

mongoose.connect(uri, connectOptions);

```
### Output:
```
issues: ./6382.js
4.10.5
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
^C

issues: npm install mongoose@4.13.12 >/dev/null 2>&1

issues: ./6382.js
4.13.12
^C

issues:
```

I was able to reproduce the error on a version previous to @4.11, but not on @4.13.12.

@ntlzz93 can you add a call to `console.log(mongoose.version)` in your example code and share the output here as it appears on your console ( like I did above )?

**Comment by lineus** [comment]
@ntlzz93 can you run this isolated test case with your mongodb host, port, and auth details and post your output here?

```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');

console.log(mongoose.version);

const connectOptions = { 
  useMongoClient: true,
  autoReconnect: true
};

const uri = 'mongodb://testUser:testPass@localhost:27072/database';

mongoose.Promise = global.Promise;

mongoose.connect(uri, connectOptions);
```

**Comment by ntlzz93** [comment]
@lineus : The program's output was posted previous comment. The same code with you.

**Comment by lineus** [comment]
are you running this code using [clonq/revo](https://github.com/clonq/revo)?

**Comment by ntlzz93** [comment]
@lineus No , I don't. This is just only program name. No specical

**Comment by vkarpov15** [comment]
@ntlzz93 can you post the output of `npm list | grep "mongo"`? This message may be coming from another npm module

**Comment by lineus** [comment]
@ntlzz93 If you're still experiencing this issue, please comment here and we'll reopen this.

**Comment by ntlzz93** [comment]
thank for support, the issue was resolved

**Comment by helgeh** [comment]
@ntlzz93 Any way you could share what the issue was and how you resolved it?
