### ISSUE TITLE
Support - changestream error

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6387]
I have this Q on SO, and looking for answers:
https://stackoverflow.com/questions/49989101/mongoerror-unrecognized-pipeline-stage-name-changestream

Here is the error I am getting:

```console
    MongoError: Unrecognized pipeline stage name: '$changeStream'
        at queryCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:244:25)
        at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:544:18
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at Immediate._tickDomainCallback (internal/process/next_tick.js:218:9)
        at runCallback (timers.js:800:20)
        at tryOnImmediate (timers.js:762:5)
        at processImmediate (timers.js:733:5)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I am on Mongoose `5.0.16`, and running Mongo version `3.4.10`.

I start Mongo locally with:

```bash
sudo mongod  --dbpath "${HOME}/local_mongo_data" --replSet rs0 --enableMajorityReadConcern
```

When I connect to the mongo instance, the replica sets are in action, I connect to the PRIMARY.

Here is my code:

```js
'use strict';

import caches = require('../../models/caches');
import {Phase, Acquisition, Category, FunctionalGroup, Role, User, Workstream} from "../../models";

Acquisition.watch().on('change', function (c) {
  console.log('acq change:', c);
});

Category.watch().on('change', function (c) {
  console.log('category change:', c);
});

FunctionalGroup.watch().on('change', function (c) {
  console.log('functional team change:', c);
});

Role.watch().on('change', function (c) {
  console.log('role change:', c);
});

User.watch().on('change', function (c) {
  console.log('user change:', c);
});

Workstream.watch().on('change', function (c) {
  console.log('workstream change:', c);
});
```

**I am guessing that the problem is that the data in our db was partly created by Mongo v2.6.x. So maybe the documents in the DB are missing fields? Not sure how to fix, but need help!**

**Comment by ORESoftware** [comment]
Given some comments on the SO question, my current best guess is that because ChangeStreams are a new feature to version 3.6, that because I am using 3.4, my code won't work.

However, what is confusing to me, is that it looks like I can run this code against Mongo version 3.4:



```js
      const q = self.rawCursor = coll.find(self.query || query)
      .addCursorFlag('tailable', true)
      .addCursorFlag('awaitData', true)  // true or false?
      .addCursorFlag('noCursorTimeout', true)
      .addCursorFlag('oplogReplay', true)
      .setCursorOption('numberOfRetries', Number.MAX_VALUE)
      .setCursorOption('tailableRetryInterval', 200);
      
      return self.rawStream = q.stream();
```

where coll is:

```js
    return MongoClient.connect(this.uri).then((client) => {
      const db = client.db('local');
      // db.oplog.rs.find()
      this.client = client;
      this.coll = db.collection('oplog.rs');  //  <<<< coll is defined here
      return null;
    });
```

I thought  `q.stream()` returned a `ChangeStream`, so what gives?

**Comment by lineus** [comment]
@ORESoftware yes, changeStreams are only available on 3.6. The return from `Cursor.stream()` in the native driver is not a [ChangeStream](https://mongodb.github.io/node-mongodb-native/3.0/api/ChangeStream.html), it's a [Readable Stream](https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_readable_streams).

**Comment by ORESoftware** [comment]
@lineus thank you for that clarification! good to know.

**Comment by ORESoftware** [comment]
@lineus btw if you add an answer to the SO question I can guarantee at least 25 points from me.

**Comment by vkarpov15** [comment]
@lineus is correct, you could tail the oplog in previous versions of MongoDB, but change streams are new in 3.6
