### ISSUE TITLE
findOne / findById only respond with _id field

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#6388]
I have this Q on SO: https://stackoverflow.com/questions/49990411/findbyid-query-is-only-returning-id-field

this seems like a bug.
My exact Mongoose version is `5.0.16`

I have this query:

```js
      return Role.findById(_id, {lean: true}).exec().then(function (role: any) {
        
        if (!(role && role.key && role._id)) {
          log.error('role doc was missing the "key"/"_id" field =>', role);
          return;
        }
        
        caches.RolesCache[role.key] = role;
        caches.RolesCacheById[role._id] = role;
      });
```

I am getting this logged:

>     role doc was missing the "key"/"_id" field => { _id: 5ade466c1384a4deffac6b09 }

**Why would the findById function only return the _id field of the document? So weird. I swear this used to work fine.**

**_Note that I also tried:_**

`Role.findById(_id).lean().exec()`
 
`Role.findById(_id).exec()`

`Role.findOne({_id}).exec()`

and have the same issue.
when I use the shell, I run:

>     rs0:PRIMARY> db.roles.find({_id:ObjectId("5ade466c1384a4deffac6b09")})
>     { "_id" : ObjectId("5ade466c1384a4deffac6b09"), "active" : true, "functionalGroup" : "IT", "defaultCategories" : [ "CATEGORY_GENERAL", "CATEGORY_NETWORK_LANDSCAPE", "CATEGORY_CALL_CENTER", "CATEGORY_TELECOMMUNICATIONS", "CATEGORY_VIDEO" ], "key" : "ROLE_XXX", "name" : "ROLE_XXX", "createdBy" : "alexamil", "createdAt" : ISODate("2018-04-23T20:47:40.413Z"), "updatedBy" : "alexamil", "updatedAt" : ISODate("2018-04-23T20:47:40.413Z"), "__v" : 0 }

**anyone know what's going on?** 

> I am on Mongoose version: 5.0.16, and Mongo version: 3.4.x

**Comment by lineus** [comment]
@ORESoftware 

In your example query, you are passing `{ lean: true }` as the second parameter to `findById()`. The 2nd parameter to `findById()` is the projections object which determines which fields get returned in the document. Your query would return the `lean` and `_id` fields, but since you don't have a field called lean you only get the `_id` field back.

here is a minimally complete example that demonstrates the query that isn't working for you and one that should:

### 6388.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  key: String
});

const Test = mongoose.model('test', schema);

const tests = [];

for(let i = 0; i < 10; i++) {
  tests.push(new Test({ name: `name${i}`, key: `key${i}`}));
}

async function run() {
  await conn.dropDatabase();
  await Test.create(tests);
  let bad = await Test.findById(tests[4]._id, { lean: true });
  console.log(bad);
  let good = await Test.findById(tests[4]._id).lean().exec();
  console.log(good);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6388.js
{ _id: 5ae06d5419e2e5d0036c8d03 }
{ _id: 5ae06d5419e2e5d0036c8d03,
  name: 'name4',
  key: 'key4',
  __v: 0 }
issues:
```
