### ISSUE TITLE
memory leak since version 5.0.15

### ISSUE THREAD

**Issue by RomanSchmidtAppinio** [Automattic/mongoose#6391]
**Do you want to request a *feature* or report a *bug*?**
It seams to be s a bug since version 5.0.15. Was seen also in 5.0.16.

**What is the current behavior?**
A continuously growing memory heap. NodeJS Server consistently has 0.5gb of memory usage in version 5.0.14. Server reaches 2gb in less than 30 minutes with version 5.0.15 and 5.0.16.

**If the current behavior is a bug, please provide the steps to reproduce.**
No changes in the code. Can not say what exactly causes the problem.  Just upgrade from 5.0.14 to 5.0.15 / 5.0.16

**Please mention your node.js, mongoose and MongoDB version.**
node: 8.11.1, mongoose since: 5.0.15, mongo: 3.6.4 (no issues there)

**Note**
I am working with call backs and npm async, not with promisses or await / asnyc...

**Comment by markstos** [comment]
Thanks for the notice, I'll stick with 5.0.14 until I hear more about this.

**Comment by markstos** [comment]
@vkarpov15 I chose to deploy 5.0.14 based on this report. After 24 hours, the memory use of 5.0.14 looks stable.

**Comment by RomanSchmidtAppinio** [comment]
FINALY FOUND:
Sense version 5.0.15 you have to close the cursor manually. Every request as cursor will not close automatically as before so you will run into a memory leak.

sry, too dumb to format right

``
const
    async = require('async'),
    mongoose = require('mongoose'),
    schema = new mongoose.Schema({
        bar: Number,
    });

const
    dbServer = mongoose.createConnection(connection.url, connection.options),
    fooModel = dbServer.model('foo', schema);

dbServer.once('connected', () => {
    async.waterfall([
        done => fooModel.remove({}, err => done(err)),
        done => {
            const updates = new Array(100000);
            updates.fill({bar: 1});
            fooModel.insertMany(updates, err => done(err));
        },
        (done) => async.forever(done => {
            const cursor = fooModel.find({}).lean().cursor();
            cursor.next(err => {
                if (err) {
                    done(err);
                    return;
                }
                //cursor.close(done); // for version >= 5.0.15++
                done(); // for version <= 5.0.14
            })
        }, done)
    ], (err) => {
        if (err) {
            throw Error(err);
        }
        console.log('this should never be called')
        process.exit();
    });
});

dbServer.on('error', err => {
    throw Error(err);
});
``

**Comment by vkarpov15** [comment]
Thanks for reporting, I need to investigate this.

**Comment by RomanSchmidtAppinio** [comment]
@markstos

The script I wrote does not make any big sense then just show the behavior of the memory leak.

My script shows how the forever function of npm async creates a new instance of the closure that creates a new cursor over and over again. As soon as the closure gets destroyed the smart pointer loses his only reference in this closure and gets closed. The used memory gets free again.

Like it seems does mongoose hold since 5.0.15 a reference of this pointer (i hope not npm mongo). So after the destroy of my closure in forever there still exists a reference. The smart pointer lives for ever, the close function gets never called and the memory stays used in the next loops. So after a while you will run out of memory on NodeJS side if you do not call the close function on your own.

I hope I have explained it a bit understandable. Sorry if not.

**Comment by RomanSchmidtAppinio** [comment]
@pawsong You seems be right. Release of node-mongodb-native v3.0.5 says "Collection: fix session leak in parallelCollectonScan".
I don't know about previous versions but it works with the current mongoose 5.1.3.

**Comment by vkarpov15** [comment]
We upgraded from node-mongodb-native 3.0.4 to 3.0.6 in [5.0.15](https://github.com/Automattic/mongoose/blob/master/History.md#5015--2018-04-16), so I'm not certain that's the correct explanation. But if the problem is gone with mongoose 5.1.3, that's fine for now :+1:

**Comment by vkarpov15** [comment]
Please re-open if you see this issue pop up again.
