### ISSUE TITLE
TypeError: Cannot create property '_idlePrev' on string '[Circular]'

### ISSUE THREAD

**Issue by univec** [Automattic/mongoose#6393]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

Error crashing the server:

internal/linkedlist.js:30
    item._idleNext._idlePrev = item._idlePrev;
                             ^

TypeError: Cannot create property '_idlePrev' on string '[Circular]'
    at remove (internal/linkedlist.js:30:30)
    at Object.append (internal/linkedlist.js:45:3)
    at insert (timers.js:144:5)
    at Object.exports._unrefActive (timers.js:110:3)
    at TLSSocket.unrefTimer [as _unrefTimer] (net.js:194:12)
    at TLSSocket.Socket._writeGeneric (net.js:669:8)
    at TLSSocket.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at TLSSocket.Writable.write (_stream_writable.js:220:11)
    at TLSSocket.Socket.write (net.js:650:40)
    at Connection.write (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:543:23)
    at /var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1298:44
    at waitForAuth (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1156:39)
    at /var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1164:5
    at /var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:1028:21

**If the current behavior is a bug, please provide the steps to reproduce.**

we are connecting like this: 

mongoose.createConnection([REDACTED], {
        ssl:true,
        replicaSet:[REDACTED],
        authSource:"admin",
        useMongoClient:true// happens both with and without this options.
    });

**What is the expected behavior?**

No crash

**Please mention your node.js, mongoose and MongoDB version.**
mongoose 4.13 or 4.9, mongodb 3.4, node 5 or 6.9.1

**Comment by lineus** [comment]
@univec Can you provide some details about the mongodb server you are connecting to? Is it a cloud service like atlas, etc or is it a server that you maintain?

**Comment by univec** [comment]
@lineus Absolutely. It is an atlas cluster of 3 servers hosted on AWS.

**Comment by lineus** [comment]
@univec your connection options aren't going to work as they are.

Here is an example of my connection details using mongoose 4.13.12 and Atlas
that demonstrates a working connection. 

### 6393.js
```js
#!/usr/bin/env node
'use strict';

const uri = require('/Users/lineus/.env').ATLAS;
const sharable = uri.replace(/\/[^:]+:[^@]+@/, '/**:**@');
console.log(sharable);
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const opts = {
  useMongoClient: true,
};

mongoose.connect(uri, opts);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log(found);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6393.js
mongodb:/**:**@cluster0-shard-00-00-m1luc.mongodb.net:27017,cluster0-shard-00-01-m1luc.mongodb.net:27017,cluster0-shard-00-02-m1luc.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin
{ _id: 5ae091ac69324cdfc24f3b9f, name: 'test', __v: 0 }
issues:
```

I hope this helps, let me know if you have any questions 😀

**Comment by vkarpov15** [comment]
I would recommend you don't set `ssl` and `replicaSet` in your options, for connecting to Atlas you should just copy the Atlas URL.

**Comment by univec** [comment]
Thank you for your advice. We are trying with the only option being `useMongoClient: true`. Will report back soon.

**Comment by lineus** [comment]
@univec I'm assuming you got this worked out. If you're still having connection issues please comment here and I'll reopen this.
