### ISSUE TITLE
How to count in aggregate ? 

### ISSUE THREAD

**Issue by albertyou2** [Automattic/mongoose#6395]
hi  @Automattic 
this is my test code here : 

 pageItems = await app.model.UserFiles.aggregate([
            {
                $match: { uid:uid }
            },
            {
                $lookup: {
                    from         : 'statistic_user_poster_total',
                    localField   : 'fid',
                    foreignField : 'fid',
                    as           : 'statistic'
                }
            },

             {  // I only want to count player number , here 
                $lookup: {
                    from         : 'activate_player',
                    localField   : 'fid',
                    foreignField : 'fid',
                    as           : 'players'
                }
            },
            {   
                $project : { 
                    fid       : 1,
                    statistic : 1,
                    players  : 1 // i did not need all the data of players ,i just want to count the player number for a 'fid'
                } 
             }
        ])

Did some one meet this problem before? 
Thank you very much!

**Comment by msoula** [comment]
I think you should read this article: https://docs.mongodb.com/manual/reference/operator/aggregation/sum/
