### ISSUE TITLE
schema.options is null if Schema is not created inline (TypeError: Cannot read property 'collation' of undefined)

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#6397]
Apologies for the bad title, don't know how to describe the issue.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`myDoc.update(myDoc, {upsert: true});` throws
```
TypeError: Cannot read property 'collation' of undefined
    at model.Query.Query [as constructor] (node_modules/mongoose/lib/query.js:83:50)
```

Namely this line of code:
```js
if (this.schema != null && this.schema.options.collation != null) {
```

It seems like an `options` object is not created for the schema, if I change the above `if` to:
```js
if (this.schema != null && this.schema.options && this.schema.options.collation != null) {
```

It throws in another place:
```
TypeError: Cannot read property 'versionKey' of undefined
    at _update (node_modules/mongoose/lib/model.js:2606:28)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I've tried reproducing it via an isolated script but I'm unable to do this.
What I see in my code is related to how I create a `Schema` for a discriminator.

*Omitted most of schema definition*
```js
const mongoose = require('mongoose');
const BaseModel = require('./BaseModel');

const schema = {
	type: {type: String, default: 'mytype'},
	webhookId: {type: String},
};

const MySchema = new mongoose.Schema(schema);
module.exports = BaseModel.discriminator('SubModel', MySchema);
module.exports.schema = schema;
```

Replacing `MySchema` with an inline definition of a schema: `const schema = new mongoose.Schema({...});` solves the issue. But I'd like to export the schema object for other models.

**What is the expected behavior?**
Should not throw an error.

**Please mention your node.js, mongoose and MongoDB version.**
Node 9.6.1
MongoDB 3.6.4
Mongoose 5.0.16

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP :+1:

**Comment by vkarpov15** [comment]
I'm unable to reproduce this either:

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh-6397`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
mongoose.Promise = global.Promise;

const { Schema } = mongoose;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const BaseModel = mongoose.model('Test', new Schema({}));
  const schema = {
        type: {type: String, default: 'mytype'},
        webhookId: {type: String},
  };

  const MySchema = new mongoose.Schema(schema);
  const MyModel = BaseModel.discriminator('SubModel', MySchema);

  const doc = await MyModel.create({});
  await doc.update({ webhookId: 'test' });

  console.log('done');
}
```

Can you work on modifying the above script to reproduce your issue? In particular, what are you using the `.schema` export for?

Also, 2 more ideas to try:

1) Can you try cloning `schema` before exporting it?
2) `MySchema.obj` should contain the original object you pass to `mongoose.Schema`, so you shouldn't need to export the object.

In the meantime, I changed the relevant lines of code to use [lodash.get](http://npmjs.com/package/lodash.get), so those shouldn't fail anymore with 5.0.17.

**Comment by natanavra** [comment]
The `.schema` is for exporting the schema to another model to be used.
Even if I'm not exporting it, the issue persists.

1. I tried cloning, there was some error related to it as well, I'll try to reproduce it.
2. Thanks, didn't know about it - I'll use this.

Thanks for providing the fix with `_.get`

**Comment by isitavi** [comment]
I'm using mongoose  5.2.17 and face this error but when i downgrade mongoose version this problem fixed automatically

**Comment by lineus** [comment]
@isitavi can you please provide a reproducible script that shows the issue?
