### ISSUE TITLE
can I find objects with specific age (calculate age from a birthday string field)

### ISSUE THREAD

**Issue by yaoyonstudio** [Automattic/mongoose#6400]
I have "birthday" field in my User model, like '1990-8-12',  I want query some objects base on the user's age.

like:
http://test.com/users?min_age=25&max_age=30

How can I do that??  need help?

**Comment by vkarpov15** [comment]
I'd just use [moment](https://www.npmjs.com/package/moment) for this sort of thing

`User.find({ birthday: { $gte: moment(date).subtract(30, 'years'), $lte: moment(date).subtract(25, 'years') } })`

**Comment by lineus** [comment]
Hi @yaoyonstudio! For future reference, you'll get help faster by asking for help in one of the following communities:

[StackOverflow](https://stackoverflow.com/questions/tagged/mongoose)
[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)

The best way (IMO) to do what you are asking is to store the person's age in the document on the DB, this will make querying for ranges trivial.

Given the following documents in a test collection:
```
  { name: 'John', birthday: '1975-04-23' },
  { name: 'Jack', birthday: '1952-12-11' },
  { name: 'Joe', birthday: '2002-07-31' }
```

You could add the ages to the users with something like this:

###6400.js
```js
#!/usr/bin/env node
'use strict';


const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;


const schema = new Schema({
  name: String,
  birthday: String,
  age: Number
});

const Test = mongoose.model('test', schema);

function getYears(x) {
  return Math.floor(x / 1000 / 60 / 60 / 24 / 365);
}

async function run() {
  let promises = [];
  let docs = await Test.find({});
  
  docs.forEach((doc) => {
    let n = Date.now();
    let d = new Date(doc.birthday);
    doc.set('age', getYears(n - d));
    promises.push(doc.save());
  });
  
  Promise.all(promises).then((saved) => {
    console.log(saved);
    return conn.close();
  });
  
}

run().catch(console.error);
```
### Output:
```
issues: ./6400.js
[ { _id: 5ae3851be04126304d0d06a7,
    name: 'Joe',
    birthday: '2002-07-31',
    __v: 0,
    age: 15 },
  { _id: 5ae3851be04126304d0d06a6,
    name: 'Jack',
    birthday: '1952-12-11',
    __v: 0,
    age: 65 },
  { _id: 5ae3851be04126304d0d06a5,
    name: 'John',
    birthday: '1975-04-23',
    __v: 0,
    age: 43 } ]
issues:
```

Then to query by a range you can use:
### 6400query.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  birthday: String,
  age: Number
});

const Test = mongoose.model('test', schema);

async function run() {
  let docs = await Test.find({
    $and: [
      { age: { $gt: 40 } },
      { age: { $lt: 70 } }
    ]
  });
  docs.forEach((doc) => {
    console.log(`${doc.name} is ${doc.age}`);
  });
  return conn.close();
}

run();
```

### output:
```
issues: ./6400query.js
Jack is 65
John is 43
issues:
```

I hope this helps!

**Comment by wsulbaran** [comment]
Hello, I want to consult the users by age range with their date of birth, the search range is from 28 to 37. My problem is that there are who were born in 83 and are still 37 years old. I need help

**Comment by vkarpov15** [comment]
@wsulbaran please open a new issue and follow the issue template.
