### ISSUE TITLE
Fix error using mongoose with vuex

### ISSUE THREAD

**Issue by phucvo0709** [Automattic/mongoose#6402]
I trying to use mongoose with vuex, but it have all of all packages that are installed enough, but run program error!

![untitled](https://user-images.githubusercontent.com/35060381/39391756-ad374de4-4ad2-11e8-942e-2e60e66ef9e3.png)

**Comment by lineus** [comment]
Hi @phucvo0709 

The **warnings** you have pointed out are from webpack. [They are documented here](https://webpack.js.org/guides/dependency-management/#require-with-expression) and shouldn't cause your code to fail. 

Can you please describe in more detail how your code isn't working as expected and include any relevant stack trace info?

**Comment by vkarpov15** [comment]
Are you trying to use mongoose in the browser or is this for server-side rendering?

**Comment by lineus** [comment]
@phucvo0709 were you able to resolve this issue?
