### ISSUE TITLE
Turn off colors when mongoose debug is set to true

### ISSUE THREAD

**Issue by tarun1793** [Automattic/mongoose#6403]
How do we turn off colored debug output? 
It adds extra colors data to the printed logs, which breaks our log parsing system

**Comment by lineus** [comment]
@tarun1793 

You can pass a custom log function as the second parameter to `mongoose.set()` instead of a boolean. 

A simple example:

### 6403.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', customLogger);

function customLogger(coll, op, doc, proj) {
  process.stdout.write(`${coll}.${op}(${JSON.stringify(doc)}`);
  if (proj) {
    process.stdout.write(',' + JSON.stringify(proj) + ')\n');
  } else {
    process.stdout.write(')\n');
  }
}

mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Marilyn'
});

async function run() {
  await conn.dropDatabase;
  await test.save();
  await Test.findOne({ _id: test._id }, 'name');
  return conn.close();
}

run();
```

### Output:
```
issues: ./6403.js
tests.insert({"_id":"5ae580410b18b35bd96440ff","name":"Marilyn","__v":0})
tests.findOne({"_id":"5ae580410b18b35bd96440ff"},{"fields":{"name":1}})
issues:
```

**Comment by tarun1793** [comment]
Thanks for this workaround!

**Comment by lineus** [comment]
happy to help 😄

**Comment by Mangosteen-Yang** [comment]
I have the same question.
I tried custom log before and works well however when my project become bigger and bigger, I got `JSON.stringify` error sometimes, however, works well with `debug` on only.

If possible, I hope there is an option for debug color on/off.

**Comment by vkarpov15** [comment]
@Mangosteen-Yang no option currently. You would have to use a custom logger as [shown here](https://github.com/Automattic/mongoose/issues/6403#issuecomment-385235354).

**Comment by hasezoey** [comment]
@vkarpov15 shouldnt #8033 close this issue?

**Comment by vkarpov15** [comment]
@hasezoey yes it should. Thanks! To disable colors, you can do `mongoose.set('debug', { color: false });`
