### ISSUE TITLE
Update of an existing document with _id value of null causes server to crash 

### ISSUE THREAD

**Issue by odedsh** [Automattic/mongoose#6406]
model.Model.$__delta assumes that this._doc._id. In unlikely cases it can be null (mongodb certainly allows it). 
However instead of failing and return an MongooseError the function crashes and no callback is called causing the server running mongoose to crash / hang

Here is a simple reproduction:

```
var mongoose = require('mongoose');

mongoose.connect("mongodb://localhost:27017/bug");
var TestModel = mongoose.model('test-collection',
  new mongoose.Schema({_id: Number, val:String})
);
var _id = null;

return Promise.resolve(null)
  .then( ()=> {
    return TestModel.findOneAndUpdate(
      {_id:_id},
      { val:"bug-test"},
      {upsert:true});
  })
  .then( ()=> {
    return TestModel.findOne({_id:_id});
  })
  .then( doc=> {
    doc.val = "update";
    return doc.save();
  })
  .then( doc => {
    console.log("Success")
  })
  .catch( err => console.log("Success"))
  .then(()=> mongoose.disconnect(), ()=> mongoose.disconnect())
```
I'd expect this code to reach either the then block or catch block for all documents, not to crash.
I was using:
mongoose 5.0.16
mongo: 3.4.7
node: 8.9.1

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP :+1:
