### ISSUE TITLE
Custom Schema Types for BSON "Double" failing

### ISSUE THREAD

**Issue by tannerwelsh** [Automattic/mongoose#6407]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Despite using a custom schema type to coerce a value to the BSON type "double", Mongoose fails to save the field as the appropriate type unless the input value is a non-integer.

**If the current behavior is a bug, please provide the steps to reproduce.**

Attempting to force a number to use the `"double"` BSON type. Here's the schema:

```js
const mongoose = require('mongoose')

const OrganizationSchema = new mongoose.Schema({
  name: { type: String, required: true },
  handle: { type: String, required: true },
  weight: { type: Number, required: false, min: 0, max: 10 },
})

const Organization = mongoose.model('Organization', OrganizationSchema)

const o = new Organization({ name: 'A', handle: 'B', weight: 1 })
o.save().then(console.log).catch(console.error)
```

Works correctly when passing `{ weight: 0.5 }` (i.e. saves a `Double`), but fails when passing an integer, e.g. `{ weight: 1 }`. It inserts a document with a weight type of `Int32`.

To get around this, I've tried using the [mongoose-double](https://github.com/mongoosejs/mongoose-double) package:

```js
const mongoose = require('mongoose')
require('mongoose-double')(mongoose)

const OrganizationSchema = new mongoose.Schema({
  name: { type: String, required: true },
  handle: { type: String, required: true },
  weight: { type: Schema.Types.Double, required: false, min: 0, max: 10 },
})

const Organization = mongoose.model('Organization', OrganizationSchema)

const o = new Organization({ name: 'A', handle: 'B', weight: 1 })
o.save().then(console.log).catch(console.error)
```

But this also failed to coerce an integer into a double, and still saved it as type `Int32`.

So then I made my own custom schema type, according to the docs:

```js
const mongoose = require('mongoose')

class MyDouble extends mongoose.SchemaType {
  constructor(key, options) {
    super(key, options, 'MyDouble')
  }

  cast(val) {
    let asNumber = Number(val)
    if (isNaN(asNumber)) {
      throw new Error('MyDouble: ' + val + ' is not a number')
    }
    asNumber = mongoose.mongo.Double(asNumber)
    return asNumber
  }
}

mongoose.Schema.Types.MyDouble = MyDouble

const OrganizationSchema = new mongoose.Schema({
  name: { type: String, required: true },
  handle: { type: String, required: true },
  weight: { type: MyDouble, required: false, min: 0, max: 10 },
})

const o = new Organization({ name: 'A', handle: 'B', weight: 1 })
o.save().then(console.log).catch(console.error)
```

Which has roughly the same effect as the `mongoose-double` library. The `weight` property is coerced into an object `{ [Number: 1] _bsontype: 'Double', value: 1 }`, yet upon saving it is still treated as an `Int32` and saved to the DB as such.

**What is the expected behavior?**

I'd expect that forcing a value to use a native type (i.e. BSON "double") in the schema would maintain that type at insert time.

The only way around this I found was to use the underlying driver directly, which would mean abandoning Mongoose entirely for any collection using the "double" type.

This script inserts the correct type:

```js
const mongo = require('mongodb')
const { MongoClient }= mongo

const url = 'mongodb://localhost:27017'
const dbName = 'myDb'

MongoClient.connect(url, function(err, client) {
  const db = client.db(dbName)
  const collection = db.collection('organizations')

  collection.insertOne({
    name: 'A',
    handle: 'B',
    weight: mongo.Double(1),
  }, (err, result) => {
    if (err) console.err(err)
    else console.info(result)
    client.close()
  })
})
```

**Please mention your node.js, mongoose and MongoDB version.**

Node.js v8.4.0
Mongoose v5.0.17
MongoDB v3.6.3

**Comment by vkarpov15** [comment]
This is very ironic, I just [rewrote mongoose-double yesterday to make it actually work](https://github.com/mongoosejs/mongoose-double/pull/4) before I saw this bug report, I just haven't been able to publish to `mongoose-double` because  @aheckmann hasn't given me npm publish access yet. Unfortunately the old `mongoose-double` did not actually verify the type in the db, but the [new iteration does](https://github.com/mongoosejs/mongoose-double/blob/7e4c5b95ed03339a01a23fc22fa95192834c95e9/test/example.js#L30-L43). I published the new rewrite as [`@mongoosejs/double` on npm](https://www.npmjs.com/package/@mongoosejs/double). Please try that package and let me know if you find any issues in the [mongoose-double GitHub repo](https://github.com/mongoosejs/mongoose-double).

**Comment by tannerwelsh** [comment]
Fantastic! What timing, @vkarpov15. Thank you!
