### ISSUE TITLE
insertMany results in empty documents when using not declared keys

### ISSUE THREAD

**Issue by hnitzsche** [Automattic/mongoose#6416]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Saving an array of objects with keys not declared in the Schema result in new empty documents with just an ObjectID written to the database.

Setting {strict: true} explicitly in the Schema (read that it is default actually) makes no difference.

If I set {strict: "throw"} a StrictModeError is thrown, but I can't catch it.

**What is the expected behavior?**
No empty documents should be written to the database.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose: 5.0.17
node: v8.9.4
mongod version: 3.4.13

**Comment by vkarpov15** [comment]
Please provide code samples, converting prose to code is error prone.

**Comment by hnitzsche** [comment]
```
let MemberSchema = new mongoose.Schema({
    firstname: String,
    lastname: String,
    email: String
}, { collection : 'members' }
);
```
```
let Member = mongoose.model('Member', MemberSchema);
```

```
let members = [{notInSchema: 'value'}, {alsoNotInSchema: 'value'}];

async function insertMany(members) {
    try {
         return await Member.insertMany(members)
            .then(() => {console.log('success')}, err => {throw new Error(err.message)});
    } catch (e) {
        console.log(e);
    }
}
```

Result is an empty document in the collection _members_ with just an _ObjectID_. So I see the strictmode is correctly omitting the keys that aren't in the Schema. But why is the result an empty document? Is this maybe MongoDB behaviour itself and hast nothing to do with Mongoose?

**Comment by vkarpov15** [comment]
No, this is expected behavior from mongoose. By default, mongoose silently strips out keys that aren't in the schema. If you want to make mongoose throw an error if keys that aren't in the schema are specified, use `strict: 'throw'`

```javascript
let MemberSchema = new mongoose.Schema({
    firstname: String,
    lastname: String,
    email: String
}, { collection : 'members', strict: 'throw' }
);
```
