### ISSUE TITLE
Mongoose best practices

### ISSUE THREAD

**Issue by i0natan** [Automattic/mongoose#6424]
Hey friends, we want to add to our "node best practices" repo (link below) a section about data-access practices, will you kindly contribute some ideas based on your vast experience?

For example, the following might be best practices when working with ORMs: (a) Instantiating the ORM object only once per process (b) never do automatic sync in production (c) your ideas?

Thanks for your help!

**Comment by lineus** [comment]
@i0natan There is no link your issue

**Comment by i0natan** [comment]
Sorry: https://github.com/i0natan/nodebestpractices
