### ISSUE TITLE
mongo error 

### ISSUE THREAD

**Issue by moustafamakadi** [Automattic/mongoose#6428]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by moustafamakadi** [comment]
i am trying to find the nearby hotels by using geoNear method i also use mongoos and make an schema 
and this the is Hotel.model code var mongoose = require('mongoose');

var reviewSchema = new mongoose.Schema({
  name : {
    type : String,
    required : true
  },
  rating : {
    type : Number,
    required : true,
    min : 0,
    max : 5
  },
  review : {
    type : String,
    required : true
  },
  createdOn : {
    type : Date,
    "default" : Date.now
  }
});

var roomSchema = new mongoose.Schema({
  type : String,
  number : Number,
  description : String,
  photos : [String],
  price : Number
});

var hotelSchema = new mongoose.Schema({
  name : {
    type : String,
    required : true
  },
  stars : {
    type : Number,
    min : 0,
    max : 5,
    default : 0
  },
  services : [String],
  description : String,
  photos : [String],
  currency : String,
  reviews : [reviewSchema],
  rooms : [roomSchema],
  location : {
    address : String,
    // Always store coordinates longitude (East/West), latitude (North/South) order.
    coordinates : {
      type : [Number],
      index : '2dsphere'


    

    }
  }
});

mongoose.model('Hotel', hotelSchema);

i will also show you hotel.controlles code to hel me to find out the bug
var mongoose=require('mongoose');
var Hotel=mongoose.model('Hotel');


var runGeoQuery=function(req,res){
  var lng=parseFloat(req.query.lng);
  var lat=parseFloat(req.query,lat);
  


    var point = {
      coordinates: [47.502649, 19.066785],

      type: "Point"
  };

  var geoOptions = {

    sphreical:true,
    maxDistance:2000,
    num:5
  

  };
  Hotel
  .geoNear(point, geoOptions, function(err,results,stats){
    if(err){
      console.log(err);
    }
    console.log("Geo results",results);
    console.log("Geo stats",stats);
    res
    .status(200)
    .json(results);





  }); 


};

module.exports.hotelsGetAll = function(req, res) {

  var offset = 0;
  var count = 5;
  
  if(req.query && req.query.lat && req.query.lng){
    runGeoQuery(req,res);
    return;


  }




  if (req.query && req.query.offset) {
    offset = parseInt(req.query.offset, 10);
  }
  
  if (req.query && req.query.count) {
    count = parseInt(req.query.count, 10);
  }
  Hotel
  .find()
  .skip(offset)
  .limit(count)
  .exec(function(err,hotels){
   console.log("Found hotels",hotels.length);
   res
   .json(hotels);   
  
  
  });




};

module.exports.hotelsGetOne = function(req, res) {
  var hotelId = req.params.hotelId;
  console.log('GET hotelId', hotelId);

  Hotel
  .findById(hotelId)
   .exec(function(err,doc){
     res
     .status(200)
     .json(doc);
   
  
   });
  

};

module.exports.hotelsAddOne = function(req, res) {
  console.log("POST new hotel");
  var db = dbconn.get();
  var collection = db.collection('hotels');
  var newHotel;

  if (req.body && req.body.name && req.body.stars) {
    newHotel = req.body;
    newHotel.stars = parseInt(req.body.stars, 10);
    collection.insertOne(newHotel, function(err, response) {
      console.log("Hotel added", response);
      console.log("Hotel added", response.ops);
      res
        .status(201)
        .json(response.ops);
    });
    // console.log(newHotel);
    // res
    //   .status(200)
    //   .json(newHotel);
  } else {
    console.log("Data missing from body");
    res
      .status(400)
      .json({ message : "Required data missing from body" });
  }

};
ok i run these code but this error occurs
GET /api/hotels?lng=47.502649&lat=19.066785
{ MongoError: 2dsphere index must have spherical: true
    at Function.MongoError.create (C:\Users\DELL\Documents\choosetocode\welcome to c\mean\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
    at commandCallback (C:\Users\DELL\Documents\choosetocode\welcome to c\mean\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:936:66)
    at Callbacks.emit (C:\Users\DELL\Documents\choosetocode\welcome to c\mean\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:116:3)
    at Connection.messageHandler (C:\Users\DELL\Documents\choosetocode\welcome to c\mean\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:286:23)
    at Socket.<anonymous> (C:\Users\DELL\Documents\choosetocode\welcome to c\mean\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:285:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
  name: 'MongoError',
  message: '2dsphere index must have spherical: true',
  ok: 0,
  errmsg: '2dsphere index must have spherical: true',
  code: 17301,
  codeName: 'Location17301' }
Geo results undefined
Geo stats undefined

please guys help me and thanks in advance

**Comment by vkarpov15** [comment]
Typo in your `geoOptions`:

```
var geoOptions = {

    sphreical:true,
    maxDistance:2000,
    num:5
  

  };
```

Change that to:

```javascript
var geoOptions = {
    spherical: true, // make sure you spell "spherical" correctly
    maxDistance:2000,
    num:5
  };
```
