### ISSUE TITLE
VersionError: include path(s) that caused the error

### ISSUE THREAD

**Issue by paglias** [Automattic/mongoose#6433]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
5.x

When a VersionError is thrown it would be extremely useful if Mongoose could include information about the operation that's causing the problem in the error. It would make debugging much easier when dealing with big schemas with several arrays where it's not always easy to figure out what caused the problem

Thanks

**Comment by vkarpov15** [comment]
Good suggestion :+1: We'll put it in the error message itself as well as in a property on the error object

**Comment by paglias** [comment]
I've been looking at mongoose's internals and if you want I can publish a PR in the next few days

**Comment by vkarpov15** [comment]
Yeah go for it. Let me know if I can provide any guidance.

**Comment by paglias** [comment]
PR available at https://github.com/Automattic/mongoose/pull/6464, let me know if I have to change something
