### ISSUE TITLE
Node.js DEP0079 Warning when creating new document

### ISSUE THREAD

**Issue by redSilkTie** [Automattic/mongoose#6438]
**Using mongoose v5.0.17 and node.js v10.0.0**

Every time I create a new document and save it, I get the following deprecation warning from node:

_[DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated_

I was not experiencing this when using mongoose 4 and earlier versions of node.
Anyone knows what is causing this?

**Comment by lineus** [comment]
[from this comment](https://github.com/Automattic/mongoose/issues/6420#issuecomment-386764692) on #6420 

>...deprecation warning in Node.js 10. Looks like [this](https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect) is the relevant deprecation. Mongoose relies on custom inspect() functions to make debug output readable, but looks like Node.js 12.x will not support that. We'll work around that, but for now it is safe to ignore this warning.
