### ISSUE TITLE
Where is documentation for the Schema.methods method?

### ISSUE THREAD

**Issue by oshihirii** [Automattic/mongoose#6440]
"mongoose": "^5.0.17"
Node: 10.0.0
NPM:  5.6.0

I am following tutorial code that uses this:

```
export const UserSchema = new Schema({
	username: {
		type: String,
		required: true
	},
	email: {
		type: String,
		required: true
	},
	hashPassword: {
		type: String,
		required: true
	},
	created_date: {
		type: Date,
		default: Date.now
	}
}); 

UserSchema.methods.comparePassword = (password, hashPassword) => {
	return bcrypt.compareSync(password, hashPassword);
}; 
```

I am trying to find documentation for the `.methods` method, but cannot see it online, only the `.method` method (without the 's'):

http://mongoosejs.com/docs/api.html#schema_Schema-method

Where is documentation for the `Schema.methods` method?

Thank You.

**Comment by lineus** [comment]
@oshihirii `methods` is just an object literal so it doesn't have any documentation. 

`.method()` is a function that adds the passed in function to the specified property of the `methods` object. 

Whether you use the `.method()` convenience method, or add the function directly to the object yourself `mySchema.methods.someCoolMethod = function(){}`, beware using arrow functions, as mentioned in the [FAQ](http://mongoosejs.com/docs/faq.html)

**Comment by vkarpov15** [comment]
I'll reopen this, we will add a clarification about this difference in the schema docs
