### ISSUE TITLE
`.populate(...)` is not populating a document whose Schema has refs to itself.  

### ISSUE THREAD

**Issue by picklechips** [Automattic/mongoose#6447]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`document.populate(...)` is not populating a model with subdocuments of itself.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://stackoverflow.com/questions/50264345/mongoose-populate-not-working

**What is the expected behavior?**
Currently, `curUser.recievedRequests = [{ _id : 5ae94b5f29c86c4a343d2d0a }]` however it should contain the user Object, but instead it still only holds the user id. 

**Please mention your node.js, mongoose and MongoDB version.**
Everything is the newest version. If you want specific versions I can provide.

**Comment by lineus** [comment]
Here is a self contained example based on your SO question:

### 6447.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  selfs: [{
    self: {
      type: Schema.Types.ObjectId,
      ref: 'test'
    }
  }]
});

const Test = mongoose.model('test', schema);

const test1 = new Test({ name: 'test1' });
const test2 = new Test({ name: 'test2' });
test1.selfs.push({ self: test2._id });
test2.selfs.push({ self: test1._id });

async function run() {
  await conn.dropDatabase();
  await Test.create([test1, test2]);
  let docs = await Test.find({}).populate('selfs.self', 'name -_id');
  docs.forEach((doc) => {
    doc.selfs.forEach((ref) => {
      console.log(`${doc.name} refers to ${ref.self.name}`);
    });
  });
  return conn.close();
}

run();

```
### Outputs:
```
issues: ./6447.js
test1 refers to test2
test2 refers to test1
issues:
```
@picklechips Can you please create a minimally complete reproducible example that demonstrates the behavior that you're experiencing? Feel free to use mine as a starting point.

**Comment by lineus** [comment]
@picklechips did you still need help with this?

**Comment by picklechips** [comment]
@lineus Sorry, I've had to set the project I was encountering this on aside for the time being since I became busy with other work. 

I may come back to it in the future but for now I'm not worrying about it. Thanks for your response though!

**Comment by lineus** [comment]
@picklechips no worries! If you pick it back up and need assistance let us know 👍
