### ISSUE TITLE
"Error: document must have an _id before saving".

### ISSUE THREAD

**Issue by Juffff** [Automattic/mongoose#6452]
I have this error when I add a lot of documents  to DB very fast.
The code to create new Item:
                const id = translit(data.article).toString();
                const item = new Item({
                    _id: id,
                    type: data.type,
                    kind: data.kind,
                    brand: data.brand
                   .............
                });

                return item.save(function (err, product) {
                    if (err) {
                        console.log(err);
                        console.log(id);
                        console.log(item);
                        callback(err);
                    } else {
                        callback(product)
                    }
                });

As variant, I used this _id type:

"_id": new ObjectID()

and the behavior was the same.

When I used a pause in 1 second between queries - there is no errors.

How can I solve this problem?

**Comment by lineus** [comment]
@Juffff can you post a more complete example that shows the behavior that you are describing and the output from that script including the error stack trace?

**Comment by Juffff** [comment]
g01389_chernyy **//- IT IS _ID IN MY OBJECT**
{ MongooseError: document must have an _id before saving
at new MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11)
at Timeout._onTimeout (/app/node_modules/mongoose/lib/model.js:148:18)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
message: 'document must have an _id before saving',
name: 'MongooseError' }
MongooseError: document must have an _id before saving
at new MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11)
at Timeout._onTimeout (/app/node_modules/mongoose/lib/model.js:148:18)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
**//AND THERE IS NO MY _ID AND THE DOCUMENT IS NOT SAVED**
{ type: 'Обувь',
kind: 'Ботинки',
brand: 'Diesel',
grander: 'Женский',
size: { '41': 1 },
color: 'Черный',
country: 'Португалия',
season: 'осень-весна',
consist: 'шерсть/кожа/резина',
rsp: 7900,
price: 1904,
images: 
[ 'g01389_chernyy_!_1.jpg',
'g01389_chernyy_!_3.jpg',
'g01389_chernyy_!_4.jpg',
'g01389_chernyy_!_5.jpg' ] }

**Comment by lineus** [comment]
@Juffff What is `translit()` in your snippet? Is it an async operation? Is it possible that translit might ever return undefined? If either is the case, you need to test your `id` variable for a sane value before trying to save.

here is an example script that is minimal, complete, and reproducible:

### 6452.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  _id: String,
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({
  _id: undefined,
  name: 'Bransfordston'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.find({}).lean();
  console.log(doc);
  return conn.close();
}

run().catch((e) => console.error(e.message));

```
### Output:
```
issues: ./6452.js
document must have an _id before saving
^C
issues:
```

If my advice above didn't help, can you please create a reproducible example script ( or adapt mine ) that demonstrates the issue that you are experiencing?

**Comment by Juffff** [comment]
translit() - is the function that convert cyrillic symbols to US qwerty.
It is not async operation and can not newer return undefined.
As I written above - if I use "_id": new ObjectID() sometimes the issue repeats with the same stack trace.
Today I tried set delay between queries - 2 seconds. As a result I got 3000 success operation.
When I set delay = 1 second (whith same queries), I got 2-3% fails.
When I set the delay=0 (whith same queries) seconds I have 5-10% fails.

**Comment by lineus** [comment]
@Juffff without a repro script, I'm not sure how much help we can provide, other than to say that you could try wrapping your save call in a test for item._id like:
```js
if (item._id) {
  return item.save(function(err, doc){
    if (err) { return console.error(err) };
    return callback(doc)
  });
} else {
  console.error('no _id on');
  console.error(item);
}
```
### 1) see if you get any console errors with the string 'no _id on':

*Then you shouldn't be calling save on those documents, you'll need to sort out why _id is undefined.*

### 2) If you still get the `document must have an _id` error from your save callback:

*please create **a repro script** or **a gist** or **a repository** with the code in question and share it here* 

We're always happy to help but we need more information.
