### ISSUE TITLE
Queries created from constructors do not invoke query hooks

### ISSUE THREAD

**Issue by zapthedingbat** [Automattic/mongoose#6455]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When executing a query created from a [query constructor](http://mongoosejs.com/docs/api.html#query_Query-toConstructor) does not execute hooks

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

// Define schema
const schema = new mongoose.Schema({});

// Add a find query hook
schema.pre('find', function logHook() {
    // Log the execution of the hook
    console.log(`Executing hook`);
});

// Create model
const model = mongoose.model('Model', schema);

// The following code should cause the pre 'find' hook to execute but does not

// Create a query constructor
const Query = model.find({}).toConstructor();

// Create and execute a query from the query constructor
const query = new Query().exec();
```

**What is the expected behavior?**
Hooks should execute when queries created from query constructors are executed.

**Please mention your node.js, mongoose and MongoDB version.**
- node 8.2.1
- mongoose 5.0.18
- MongoDB 3.6.4

**Comment by lineus** [comment]
it looks like this has been the case since v5.0.0. I don't see this mentioned in the [migration guide](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md), but it's possible that this was an intentional change in version 5. I'm labeling this as `bug?` for now. 

Running this example:
### 6455.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
var opts = {};

if (Number(mongoose.version.charAt(0)) < 5) {
  mongoose.Promise = global.Promise;
  opts = { useMongoClient: true };
}

mongoose.connect('mongodb://localhost/test', opts);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

schema.pre('find', function logHook() {
  console.log('Executing hook');
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'Romero' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  const Query = Test.find({}).toConstructor();
  const query = new Query();
  let docs = await query.exec();
  console.log(docs);
  return conn.close();
}

run();
```
### Output on version 4.13.12:
```
issues: ./6455.js
Executing hook
[ { _id: 5af6b749aadd80114e7da768, name: 'Romero', __v: 0 } ]
issues:
```
### Output on version >= 5.0.0:
```
issues: ./6455.js
[ { _id: 5af6b7cfcee4a411850da297, name: 'Romero', __v: 0 } ]
issues:
```

**Comment by zapthedingbat** [comment]
The bug seem to be that [applyQueryMiddleware](https://github.com/Automattic/mongoose/blob/c09202fc5538b6ea2d2530adc1f9e0f587a29aaa/lib/model.js#L4073) is only called when the model is compiled. The new instance of [CustomQuery](https://github.com/Automattic/mongoose/blob/c09202fc5538b6ea2d2530adc1f9e0f587a29aaa/lib/query.js#L190) that is created in `toConstructor` dosn't get the `_find` method that was wrapped by Kareem in `applyQueryMiddleware`.

**Comment by vkarpov15** [comment]
Not intentional, this is definitely a bug. We'll fix this ASAP :+1:
