### ISSUE TITLE
Call stack error iterating through lean() js object in 5.0.18

### ISSUE THREAD

**Issue by sjensenihi** [Automattic/mongoose#6462]
I ran into an issue when upgrading from mongoose 5.0.17 and 5.0.18. I had previously used mongoose's findOne().lean() with await to get an javascript object that I then would recursively iterate through to remove _id, __v from it to have an object that I'd sent to an API. After 5.0.18, I can see when I iterate through the object that there are now fields such as $__ and other getters and setters that I expect to be removed. The issue is that the deep traversing I do with my function will cause a `maximum call stack size exceeded error` because it will get stuck in some of these mongoose specific fields that shouldn't be there.

Was there some sort of api change with how we are supposed to get a pure js object from a mongoose model?

Thanks!

**Comment by lineus** [comment]
@sjensenihi did you get this worked out? is it still a problem?
