### ISSUE TITLE
How is "emit" defined in this example? (docs question)

### ISSUE THREAD

**Issue by StellarTabi** [Automattic/mongoose#6465]
I inherited a codebase and I noticed that there is an undefined function in use called `emit`. It looks like it was ripped (with minor modifications) from the docs:

http://mongoosejs.com/docs/api.html
```
var o = {};
o.map = function () { emit(this.name, 1) }
o.reduce = function (k, vals) { return vals.length }
User.mapReduce(o, function (err, results) {
  console.log(results)
})
```
How is `emit` defined? eslint is mad at me over this. I don't yet know if this codesample is dead code or not.

**Comment by lineus** [comment]
Hi @StellarTabi, emit doesn't get run locally, it's a method on an object that gets passed to the mongodb server where emit **is** defined. The documents pertaining to the mapReduce map function [are here](https://docs.mongodb.com/manual/reference/command/mapReduce/index.html#requirements-for-the-map-function). You can safely tell eslint to ignore that line.
