### ISSUE TITLE
console.table() does not print the data from the Model.find() callback correctly

### ISSUE THREAD

**Issue by septum** [Automattic/mongoose#6468]
**Do you want to request a *feature* or report a *bug*?**
A bug
**What is the current behavior?**
```
┌─────────┬─────────────────┬───────┬───────────┬──────────┬───────┐
│ (index) │       $__       │ isNew │  errors   │   _doc   │ $init │
├─────────┼─────────────────┼───────┼───────────┼──────────┼───────┤
│    0    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    1    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    2    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    3    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    4    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    5    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    6    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
│    7    │ [InternalCache] │ false │ undefined │ [Object] │ true  │
└─────────┴─────────────────┴───────┴───────────┴──────────┴───────┘
```
**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
myModel.find(function(err, data) {
  //...
  console.table(data);
  //...
});
```
**What is the expected behavior?**
```
┌─────────┬────────────────────────────┬─────────────────┬─────┐
│ (index) │            _id             │      name       │ __v │
├─────────┼────────────────────────────┼─────────────────┼─────┤
│    0    │ '5af8794359ca970cea91e556' │     'hello'     │  0  │
│    1    │ '5af879ff13ca870d74d58be7' │    'another'    │  0  │
│    2    │ '5af87a1013ca870d74d58be8' │      'Why'      │  0  │
│    3    │ '5af87a1d13ca870d74d58be9' │      'the'      │  0  │
│    4    │ '5af87a2e13ca870d74d58bea' │    'alert?'     │  0  │
│    5    │ '5af87af213ca870d74d58beb' │     'Test'      │  0  │
│    6    │ '5af884d0d8c23316c07c8d06' │   'one more'    │  0  │
│    7    │ '5af896dd60e2f823909aa62a' │ 'One more even' │  0  │
└─────────┴────────────────────────────┴─────────────────┴─────┘
```
**Please mention your node.js, mongoose and MongoDB version.**
- mongoose v5.1.0
- MongoDB v3.6.3
- nodejs v10.1.0

**Comment by lineus** [comment]
@septum Thanks for pointing this out. 

In the meantime, one potential userland solution for this:
### 6468.js
```js
#!/usr/bin/env node --no-deprecation
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'Maxwell' });
const test2 = new Test({ name: 'Folgers' });

function table(arr) {
  let lean = arr.map((doc) => doc.toObject());
  return console.table(lean);
}

async function run() {
  await conn.dropDatabase();
  await Test.create([test, test2]);
  let found = await Test.find();
  table(found);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6468.js
┌─────────┬──────────────────────────┬───────────┬─────┐
│ (index) │           _id            │   name    │ __v │
├─────────┼──────────────────────────┼───────────┼─────┤
│    0    │ 5af99230a256115d03ed63c6 │ 'Maxwell' │  0  │
│    1    │ 5af99230a256115d03ed63c7 │ 'Folgers' │  0  │
└─────────┴──────────────────────────┴───────────┴─────┘
issues:
```

**Comment by septum** [comment]
Thank you, I'll use the provided solution.

**Comment by mhombach** [comment]
I'm not sure if this should be considered a bug. The Object itself is correctly printed with `(index), $__, isNew, error, _doc, $init` and so on. If you want the data from the document, then you should use the `lean` function or write your own table-log. Because what would you do if we change the behaviour and then someone wants to get the view of what it is right now?
You can always go a level down to a child-element and print that.
I first thought about implementing something like `data.printDocAsTable()` but to be honest, i doubt that it's worth the time. Console-logging a table should only be used in development and debugging. If you want custom and nice output, you should just format it yourself :)

**Comment by vkarpov15** [comment]
@mhombach `console.log()` prints a nicely formatted doc with the Mongoose internals hidden, would be nice if `console.table()` was consistent.

**Comment by mhombach** [comment]
I still doubt that this will be used/relevant often, but about the consistency i must admit that you are right :)

**Comment by mhombach** [comment]
@septum @vkarpov15 i just tested this and my nodeJS seems to not print anything when i try to console.table(somearray)... there are additional npm packages that provide a console.table function, but those seem to be somewhat old and not very stable. Am i missing something here?
If one would need to install an additional package for printing a table, we might aswell implement Document.printTable(). I could try to implement this, that‘s why i ask for clarififcation :)

**Comment by vkarpov15** [comment]
Of course, give it a shot :) This is the `console.table()` I think OP is referring to: https://nodejs.org/api/console.html#console_console_table_tabulardata_properties

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior, not much Mongoose can do about it since [`console.table()` calls `Object.keys()`](https://github.com/nodejs/node/blob/6948a95562884636fdbf9627069e3ebc801a71ec/lib/internal/console/constructor.js#L476) and doesn't respect custom `toJSON()` or `inspect()`. As a workaround, you'll have to call `toObject()` before passing a mongoose document to `console.table()`.
