### ISSUE TITLE
Problem using findOneAndUpdate and validation

### ISSUE THREAD

**Issue by skrichten** [Automattic/mongoose#6476]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
When using findOneAndUpdate, if I have a schemetype with a required function, "this" is null in the function.  Also, in any validation functions I get "this.constructor.findOne is not a function" if I try to reference that.  This same code works fine for a normal insert.

**If the current behavior is a bug, please provide the steps to reproduce.**
Call something like
`User.findOneAndUpdate({ _id: req.params.id }, req.body, { new: true, upsert: true, setDefaultsOnInsert: true, runValidators: true }).exec()`
on a schema that has a type with a required function.  And in the function 'this' will be null.
And have a validator that tries to call this.constructor.findOne

**What is the expected behavior?**
should give same behavior as a normal insert... 'this' should reference the schema object in the required function.
In the validation function this.constructor.findOne should be available.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 8.9.1, windows 10 64bit
mongoose 5.1.1

**Comment by lineus** [comment]
@skrichten [check out the update validator docs](http://mongoosejs.com/docs/validation.html#update-validators-and-this). The behavior you are describing is intentional.

**You can pass the `context: 'query'` option to your `findOneAndUpdate()` call which will set `this` in the validator function to the query. Here is an example:**

*note that below, I use validate instead of required. Custom validators can be async but `required` functions can not be.* ( this can be observed by changing `validate` to `required` in the schema below. )

### 6476.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;
const ObjectId = mongoose.mongo.ObjectId;

const called = [];

const schema = new Schema({
  name: {
    type: String,
    validate: async function() {
      if (this instanceof mongoose.Query) {
        let doc = await this.model.findOne();
        console.log(`found: ${doc}`);
      }
    }
  }
});

schema.post('save', function () {
  called.push('save-done');
});

schema.post('findOne', function () {
  called.push('findOne-done');
});

schema.post('findOneAndUpdate', function () {
  called.push('findOneAndUpdate-done');
});

const Test = mongoose.model('test', schema);
const test1 = new Test({ name: 'test1' });

async function run() {
  await conn.dropDatabase();
  let saved = await test1.save();
  console.log(`saved: ${saved}`);
  
  let cond = { _id: new ObjectId() };
  let doc = { name: 'test2' };
  let opts = { 
    new: true, 
    upsert: true, 
    setDefaultsOnInsert: true, 
    runValidators: true,
    context: 'query'
  };

  let created = await Test.findOneAndUpdate(cond, doc, opts).exec();
  console.log(`created: ${created}`);
  console.log(called);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6476.js
saved: { _id: 5afd5291362f14ea97bb69f0, name: 'test1', __v: 0 }
found: { _id: 5afd5291362f14ea97bb69f0, name: 'test1', __v: 0 }
created: { _id: 5afd5292362f14ea97bb69f1, __v: 0, name: 'test2' }
[ 'save-done', 'findOne-done', 'findOneAndUpdate-done' ]
issues:
```

**Comment by skrichten** [comment]
@lineus Thanks for the explanation!

**Comment by lineus** [comment]
@skrichten happy to help!

**Comment by hamit-zor** [comment]
Hello, this is a known issue and mentioned in here : https://mongoosejs.com/docs/validation.html#the-context-option
My problem is that `this` indeed points to the document being validated, but when I try to access its parent with `this.parent()` I just get undefined. iff I use `Model.findOne` and make changes in actual object in the memory, I can access the parent with `this.parent()`. Is this a known issue?

**Comment by vkarpov15** [comment]
@hamit-zor please open up a separate issue and follow the issue template
