### ISSUE TITLE
Can we make MongooseMap toJSON return a POJO of properties with string keys?

### ISSUE THREAD

**Issue by JackyW83** [Automattic/mongoose#6478]
Hi guys,

I declare a Map type in my schema like below:
`const StoreSchema = new mongoose.Schema({
  id: String,
  test: {
    type: Map,
    of: String
  }})`

Then I set the key/value map to my store
`const store = new Store();`
`store.test = new Map(); `
`store.test.set('key', 'value');`
`//this works, output: value`
`console.log(store.test.get('key'));`

`//this is not working, the test is empty object ( {} ) in output`
`console.log(JSON.stringify(store));`
`store.save();`
In above code, I could get the value from first console.log, but the test is empty object when 
second console.log and store.save()
any clue of this?

my environment:
nodejs version: 8.11.2
mongodb version: 3.4.2
mongoose version: 5.1.1

thank you in advance

**Comment by lineus** [comment]
@JackyW83 Map keys can be any type including objects, functions, arrays, etc. JSON requires keys as strings. They are not compatible:
```
issues: node
> var map = new Map();
undefined
> map.set('k', 'v');
Map { 'k' => 'v' }
>
> console.log(map);
Map { 'k' => 'v' }
undefined
> console.log(JSON.stringify(map))
{}
undefined
>
issues:
```

You can however add a toJSON method to your map that will return a POJO of the string key'd properties of your map like this:
### 6478.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  test: {
    type: Map,
    of: String,
    default: new Map()
  }
});

const Test = mongoose.model('test', schema);

const mapTest = new Test({});

mapTest.test.set('key1', 'value1');

async function run() {
  await conn.dropDatabase();
  await mapTest.save();
  let found = await Test.findOne();
  found.test.toJSON = function () {
    let ret = {};
    for (let [key, value] of this) {
      if (typeof key === 'string') {
        ret[key] = value;
      }
    }
    return ret;
  };

  console.log(JSON.stringify(found));
  return conn.close();
}

run();
```
### Output:
```
issues: ./6478.js
{"test":{"key1":"value1"},"_id":"5afed1b454f11f5f1885ebe1","__v":0}
issues:
```

This is something that I think the MongooseMap could do instead of returning an instance of Map the way it does now. I'll give this some more thought and potentially put in a PR for it. Either way I'll report back here.

**Comment by JackyW83** [comment]
thanks you @lineus

**Comment by tomerb15** [comment]
Thought you should know that calling toJSON on a model that have a complex structure including sub documents, maps and arrays is not working all the way.

consider the following Schema structure, toJSON will not drill down the tree.

```
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var ordersAmountSceme = new Schema({
    amount: String,
    by: String
});
var targetingSceme = new Schema({
    gender: [{
        type: String
    }],
    ordersAmount: {type: ordersAmountSceme, default: {}},
    purchasedItems: [{
        type: String
    }],
    addedNotPurchased: [{
        type: String
    }],
    refs: [{
        type: String
    }],
    followingHour: String,
    sendAfterAbandonedMin: String 
});

var btnsScheme = new Schema({
    type : String,
    title : String,
    payload : String
});
var msgScheme = new Schema({
    title : String,
    subtitle : String,
    type : String,
    image_url : String,
    buttons : [btnsScheme]
});
var resultSchema = new Schema({
    impressions: {type: Number, default: 0},
    impressions2: {type: Number, default: 0},
    opened: {type: Number, default: 0},
    opened2: {type: Number, default: 0},
    clicks: {type: Number, default: 0},
    clicks2: {type: Number, default: 0},
    sales: {type: Number, default: 0},
    sales2: {type: Number, default: 0},
    frequencyBlocked: {type: Number, default: 0},
    frequencyBlocked2: {type: Number, default: 0}
});
var dripCampaignSchema = new Schema({
    _id: String,
    name: String,
    lastUpdated: Number,
    orgId: String,
    status: String,
    targetingRules: {type: targetingSceme, default: {}},
    firstMessage: [msgScheme],
    trigMsgMap: {
        type: Map,
        of: [msgScheme]
    },
    creationDate: Number,
    analytics : {type: resultSchema, default:{}},
    priority: Number,
    xDaysNoActionAmount: {type: Number, default: null}
});

db.model('drip_campaigns', dripCampaignSchema);
```

**Comment by vkarpov15** [comment]
@tomerb15 what do you mean by "complex structure" and "will not drill down the tree"? What is the output you get and what is the output that you expect?

**Comment by tomerb15** [comment]
@vkarpov15 Thanks for the reply:
Complex Structure = Document with sub docs with sub docs etc...

Basically when i call `camp.toJSON()` (where `camp` is a `dripCampaignSchema` model)
I expect the entire object will become simple JSON without the mongoose special structure.
Something similar to what you get when using `lean()`.

However, that is not the case. The `trigMsgMap` is not lean
I'm using the latest mongoose.

**Comment by vkarpov15** [comment]
@tomerb15 this information isn't very helpful. Please open up a separate issue and follow the issue template. Make sure you clarify what you mean by "is not lean" and "without the mongoose special structure."
