### ISSUE TITLE
schema path stripped in multi-dimensional array of embedded docs

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6493]
@saeedhei on gitter was requesting assitance with defining a schema to store [inlineKeyboardButton Objects as defined in here in the telegram bot api](https://core.telegram.org/bots/api#inlinekeyboardbutton).

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When embedding docs in a multi-dimensional array, only the first path of the 2nd dimension of the array gets through.

**If the current behavior is a bug, please provide the steps to reproduce.**

### 6493.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const oneSchema = new Schema({
  text: String,
  callback_data: String
}, { _id: false });

const twoSchema = new Schema({
  text: String,
  url: String
}, { _id: false });

const doesntWorkSchema = new Schema({
  reply_markup: {
    inline_keyboard: [
      [oneSchema],
      [twoSchema]
    ]
  }
});

doesntWorkSchema.pre('validate', function() {
  process.stdout.write('pre val hook on doesntwork: ');
  console.log(this.reply_markup.inline_keyboard[1][0]);
});

const doesWorkSchema = new Schema({
  reply_markup: {
    inline_keyboard: [
      [Schema.Types.Mixed],
      [Schema.Types.Mixed]
    ]
  }
});

doesWorkSchema.pre('validate', function () {
  process.stdout.write('pre val hook on doeswork: ');
  console.log(this.reply_markup.inline_keyboard[1][0]);
});

const Works = mongoose.model('works', doesWorkSchema);
const Fails = mongoose.model('fails', doesntWorkSchema);

const test = {
  reply_markup: {
    inline_keyboard: [
      [{ text: 'one', callback_data: 'data' }],
      [{ text: 'two', url: 'url' }]
    ]
  }
};

async function run() {
  await conn.dropDatabase();
  await Works.create(test);
  await Fails.create(test);

  let works = await Works.findOne({}).lean();
  let a = works.reply_markup.inline_keyboard;
  assert.strictEqual(a[0][0].text, 'one');
  assert.strictEqual(a[0][0].callback_data, 'data');
  assert.strictEqual(a[1][0].text, 'two');
  assert.strictEqual(a[1][0].url, 'url');

  let fails = await Fails.findOne({}).lean();
  let b = fails.reply_markup.inline_keyboard;
  assert.strictEqual(b[0][0].text, 'one');
  assert.strictEqual(b[0][0].callback_data, 'data');
  assert.strictEqual(b[1][0].text, 'two');
  assert.strictEqual(b[1][0].url, 'url', 'url field is being stripped');
  return conn.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return conn.close();
}
```
### Output:
```
issues: ./6493.js
pre val hook on doeswork: { text: 'two', url: 'url' }
pre val hook on doesntwork: { text: 'two' }
{ AssertionError [ERR_ASSERTION]: url field is being stripped
    at run (/Users/lineus/dev/Help/mongoose5/gitter/saeedhei.js:77:10)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: 'url',
  operator: '===' }
issues:
```
**What is the expected behavior?**
all paths in the schema should make it through to the doc.

**Please mention your node.js, mongoose and MongoDB version.**
node: 8.11.1
mongoose: 5.1.1
mongodb: 3.6.4

**Comment by vkarpov15** [comment]
That's because

```javascript
const doesntWorkSchema = new Schema({
  reply_markup: {
    inline_keyboard: [
      [oneSchema],
      [twoSchema]
    ]
  }
});
```

Is equivalent to:

```javascript
const doesntWorkSchema = new Schema({
  reply_markup: {
    inline_keyboard: [[oneSchema]]
  }
});
```

The way to do this is via [embedded discriminators](http://thecodebarbarian.com/mongoose-4.8-embedded-discriminators)

**Comment by lineus** [comment]
Thanks for clarifying this for me @vkarpov15 . Discriminators was my first instinct, but also one of my biggest weak spots. I'll create an example for @saeedhei using a discriminator.

**Comment by saeedhei** [comment]
@lineus Which one is better and faster To access child object value?
What's the difference between below Schema and your Examples?
```
  reply_markup: {
    inline_keyboard: [
      [Schema.Types.Mixed],
      [Schema.Types.Mixed],
    ],
  },
```

**Comment by lineus** [comment]
model compilation will ignore the second array in your schema path array of arrays, so this:
```
  reply_markup: {
    inline_keyboard: [[Schema.Types.Mixed]],
  },
```
is a more accurate representation. ( I just learned this too )

The Discriminator example above gives you the ability to explicitly declare the acceptable types for specific paths which gives you type ( and potentially required, if you use it ) validation for each discriminator schema path. At the end of the day, this will only let mongoose save valid docs to the db.

With `Schema.Types.Mixed`, you can put any arbitrary object in the array and mongoose will save it. 

I haven't explicitly tested it, but I would assume there would be *some* speed difference between the two with Mixed being faster, however I would also contend that the benefit of validation out weighs the potential speed difference.

**Comment by vkarpov15** [comment]
@lineus I opened up a new issue to track the `.caster` bit. You shouldn't have to access `.caster` for embedded discriminators on multi-dimensional arrays, we'll have to improve that.
