### ISSUE TITLE
findOneAndUpdate updates multiple times 

### ISSUE THREAD

**Issue by pwrnrd** [Automattic/mongoose#6494]
**Do you want to request a *feature* or report a *bug*?**
*bug* or I'm doing something wrong (which is also highly likely)

**What is the current behavior?**
findOneAndUpdate runs multiple times when passed a callback. While running the code below the logs show: 

_first run:_
` inner count: 10` 
`outer count: 11`
_second run:_
` inner count: 12` 
`outer count: 13`

If I delete the callback function, the outer count increments by one (as expected).

**If the current behavior is a bug, please provide the steps to reproduce.**
````  // create or update
 const res = await Bot.findOneAndUpdate(
    { ip: input.ip }, //query
    {
      ...input, // input
      $inc: {
        count: 1
      }
    },
    { //options
      new: true,
      upsert: true,
      setDefaultsOnInsert: true
    },
    (err, bot) => { // callback
      new Promise((resolve, reject) => {
        if (err) reject(Error(err));
        console.log('inner count: ', bot.count);
        resolve(bot);
      })
    }
  );
  console.log('outer count', res.count);
````
**What is the expected behavior?**
findOneAndUpdate runs once. I would expect that the cod above returns the following log entries:

_first run:_
` inner count: 10` 
`outer count: 10`
_second run:_
` inner count: 11` 
`outer count: 11`

**Please mention your node.js, mongoose and MongoDB version.**
node.js: 9.11.1
mongoose: 5.1.1
MongoDB: 3.4.7

**Comment by lineus** [comment]
@pwrnrd Using a callback and a promise simultaneously will result in the query being executed twice. You should be using one or the other, but not both.

Check out the mongoose guide [here](http://mongoosejs.com/docs/queries.html)

**Comment by vkarpov15** [comment]
Also, check out the [promises docs](http://mongoosejs.com/docs/promises.html#queries-are-not-promises)

**Comment by pwrnrd** [comment]
@lineus and @vkarpov15 , thank you for your reactions! I read the docs so I knew that the function does not return a Promise but a Query object. Hence, I thought, I could create the Promise myself in the callback, what am I missing?

I updated the callback such that it no longer returns a Promise (sell below). However, if I use the callback below I still get the same behaviour. If I execute the query again, the count still seems to increase by 2 if the callback is provided, while the count increases by 1 if I delete the callback.

````
    //new callback
    (err, res) => {
      if (err) throw Error('something went wrong');
      console.log('inner count', res.count);
      return (res);
    }
````

**Comment by lineus** [comment]
@pwrnrd when you `await Query` you are using the promise-like super powers of Query.  Passing a callback as well will result in the behavior you're describing.

use:

`await Model.findOneAndUpdate(query, doc, options)`
**OR**
`Model.findOneAndUpdate(query, doc, options, callback)`

**Comment by vkarpov15** [comment]
Yeah in general don't mix promises and callbacks, that leads to spaghetti code whether or not you're using mongoose. `await Model.findOneAndUpdate(query, doc, options)` is the way to go if you're using async/await.

**Comment by pwrnrd** [comment]
Ok clear, thank you both!

**Comment by homavand** [comment]
also clear    .catch(err => console.log(err))     end of the query statement
