### ISSUE TITLE
Move "Queries are not promises" section to queries docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6495]
Issues like #6494 pop up fairly frequently. It would be handy to clarify the difference between mongoose queries and conventional promises.

Also, making a note to think about whether using `Query.prototype.then()` should prevent the query from being executed again. @lineus thoughts?

**Comment by lineus** [comment]
@vkarpov15 I have some silly questions for myself to answer before I respond :smile:

**Comment by AbdelrahmanHafez** [comment]
Ah, that makes sense. Thank you.
