### ISSUE TITLE
Overflow error from mongodb when using mongoose but not when using command line mongo client

### ISSUE THREAD

**Issue by 0505gonzalez** [Automattic/mongoose#6497]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The following code fails:
```
MyModel.find({$or: [condition1, condition2]}).limit(3000).sort({sequence: -1})
```

```
MongoError: getMore executor error: Overflow sort stage buffered data usage of 33555076 bytes exceeds internal limit of 33554432 bytes
```

However, when I set a batchSize >= limit, it works fine: 
```
MyModel.find({$or: [condition1, condition2]}).limit(3000).sort({sequence: -1}).batchSize(3000)
```

Additionally, when I run the same query using RoboMongo or the command-line mongo client, there is no issue and they return all 3k documents I queried for with the default batchSize.

Other info:
* I have indexes on both of the conditions in the or + on the sequence
* Using .explain, I verified that Robomongo and the command line mongo client are using the correct indexes
* The native node mongodb driver uses it's default batchSize of 1k (https://github.com/mongodb/node-mongodb-native/blob/master/lib/cursor.js#L159)

Why am I getting an overflow error in mongoose when the batchSize is smaller than my limit? If it was an index problem, shouldn't it fail even when batchSize is large?

Is this a mongoose issue? Given that I can't reproduce this with other clients I'm inclined to think it's an issue with either mongoose, node mongodb or node mongodb-core.

Can anyone shed some light on this issue?

**What is the expected behavior?**
I should be able to use mongoose to query for 3k documents without having to set the batchSize to a value > the limit (3k).

**Please mention your node.js, mongoose and MongoDB version.**
Node 8, mongoose 4.12, mongodb 3.0.15

Note: I tried mongoose 5 and the issue still exists.

**Comment by vkarpov15** [comment]
Can you show me what indexes are on this collection and tell me approximately how many documents are in the collection? Also, have you tried without the `$or`, just `MyModel.find({}).limit(3000).sort({sequence: -1})`

**Comment by 0505gonzalez** [comment]
The indexes are: `{ sequence: -1, sender_id: 1, sender_type: 1 }` and `{ sequence: -1, receiver_id: 1, receiver_type: 1 }`. There are approximately 17m documents in the collection. I have not tried without the $or, but without it the query would not be as useful as I would have to merge the results from the two or conditions in the application layer.

**Comment by vkarpov15** [comment]
Can you try doing `explain` with mongoose as well to see whether it is using the index or not? `MyModel.find({}, null, { explain: true }).limit(3000).sort({ sequence: -1 })` or just drop in the [`mongoose-explain` plugin](https://www.npmjs.com/package/mongoose-explain). Also, here's a couple questions regarding your indexes:

1) Are these indexes created by mongoose or did you create them outside of mongoose?
2) Are you printing these indexes as shown by mongoose or by the mongodb shell?
3) Why is `sequence: -1` first on both indexes?

At this stage, my guess is that this is an issue with `retainKeyOrder` in 4.x that's also getting into 5.x because mongoose 4.x built the indexes, so I'm trying to confirm whether that is the case.

**Comment by 0505gonzalez** [comment]
@vkarpov15 I used `explain` with the command line mongo client, and it does use the correct indices. This problem only happens when I use mongoose, it never happens when I use the commandline mongo client nor Robomongo.

1. The indices were created by mongoose
2. The indices above are as shown by mongoose, but I verified that they were successfully created in the db
3. Both $or conditions need to return docs sorted on `sequence`

**Comment by vkarpov15** [comment]
Can you use explain with mongoose? Mongoose 4.x has the unfortunate tendency to reverse keys if you don't use `retainKeyOrder`, which often leads to index misses.

**Comment by 0505gonzalez** [comment]
@vkarpov15 Is there a way to explain() for find queries in mongoose? I tried searching the 4.x docs but could not find it. 5.x seems to have an explain method only for aggregations.

**Comment by vkarpov15** [comment]
@0505gonzalez use [`Model.find({}, null, { explain: true })`](http://mongoosejs.com/docs/api.html#find_find)
