### ISSUE TITLE
multiple uniq index 

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#6499]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
errors are missing

**If the current behavior is a bug, please provide the steps to reproduce.**
lets say i have model with 2 fields with uniq index
```js
const User = new Schema({
  email: {
    type: String,
    lowercase: true,
    match: [reEmail, "invalid"],
    required: [true, "required"],
    trim: true,
    index: {
      unique: true,
      name: "email-duplicate"
    }
  },
  wallet: {
    type: String,
    lowercase: true,
    required: [true, "required"],
    index: {
      unique: true,
      name: "wallet-duplicate"
    }
  }
});
```
then i create 2 same records in a row
```js
User.create({email: "me@example.com", wallet: "123"})
    .then(() => {
        return User.create({email: "me@example.com", wallet: "123"});
    })
```
in this case i will have only error about duplication email and the error about duplication wallet will be lost, and i will found that my wallet is dup anly after i fix my email. This makes our registration process longer.

**What is the expected behavior?**
It would be good to have both errors at once, is it possible?

**Please mention your node.js, mongoose and MongoDB version.**
node 10.1.0
npm 6.0.1
mongoose 5.1.0
mongodb v3.6.4

**Comment by lineus** [comment]
@TrejGun I like this idea, but given that mongodb only returns the first field that violates any unique index, I don't think it can be done in a single insert call.

You could use a pre-validate hook that does an $or'd find on the unique paths and returns an array of paths/values containing all violations:

*I choose pre-validate because it was the only way I could think of to bail out of the save call*

### 6499.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const reEmail = /[a-z0-9.]+@[a-z0-9.]+/; // i know it's lame.

const userSchema = new Schema({
  email: {
    type: String,
    lowercase: true,
    match: [reEmail, 'invalid'],
    required: [true, 'required'],
    trim: true,
    index: {
      unique: true,
      name: 'email-duplicate'
    }
  },
  wallet: {
    type: String,
    lowercase: true,
    required: [true, 'required'],
    index: {
      unique: true,
      name: 'wallet-duplicate'
    }
  }
});

userSchema.pre('validate', async function() {
  let paths = ['email', 'wallet'];
  let objs = paths.map((p) => {
    let ret = {};
    ret[p] = this[p];
    return ret;
  }, this);

  let found = await User.find({ $or: objs });

  if (found.length) {
    found.forEach((doc) => {
      paths.forEach((path) => {
        if (doc[path] === this[path]) {
          this.invalidate(path, 'dupe', this[path]);
        }
      }, this);
    }, this);
  }
});

const User = mongoose.model('user', userSchema);

const user1 = new User({
  email: 'billy@thekid.com',
  wallet: 'leather'
});

const user2 = new User({
  email: 'billy@thekid.com',
  wallet: 'leather'
});

async function run() {
  await conn.dropDatabase();
  await user1.save();
  await user2.save().catch(error);
}

run();

function error(e) {
  console.error(Object.keys(e.errors).map(key => e.errors[key].properties));
}
```
### Output:
```
issues: ./6499.js
[ { path: 'email',
    message: 'dupe',
    type: 'user defined',
    value: 'billy@thekid.com' },
  { path: 'wallet',
    message: 'dupe',
    type: 'user defined',
    value: 'leather' } ]
^C
issues:
```

**Comment by lineus** [comment]
You could do this with multiple pre-save hooks:
```
userSchema.pre('save', async function() {
  let paths = ['email', 'wallet'];
  let objs = paths.map(p => {
    let ret = {};
    ret[p] = this[p];
    return ret;
  }, this);

  let found = await User.find({ $or: objs });

  if (found.length) {
    found.forEach((doc) => {
      paths.forEach((path) => {
        if (doc[path] === this[path]) {
          this.invalidate(path, 'dupe', this[path]);
        }
      }, this);
    }, this);
  }
});

userSchema.pre('save', function() {
  return this.validate();
});
```

has the same output as above

**Comment by vkarpov15** [comment]
@TrejGun @lineus is right, the unique index violation comes from MongoDB so there isn't much mongoose can do to surface that error. You can use the pre save hook approach @lineus mentioned, that unfortunately suffers from a race condition. Transactions in MongoDB 4.0 will make it easy to work around the race condition though.

**Comment by TrejGun** [comment]
thanks guys. yeah .find() before .create() is what we are doing now, still would be good to have some build-in solution
