### ISSUE TITLE
MissingSchemaError when destructuring 

### ISSUE THREAD

**Issue by benjamin-halter** [Automattic/mongoose#6500]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
MissingSchemaError thrown when registering a model that extends the Model class by destructuring .

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const { Model, Schema } = require('mongoose')
const mongoose = require('mongoose')

class User extends Model {
    static structure () {
        return new Schema({
            username: String,
        })
    }
}

const connection = mongoose.createConnection(`mongodb://127.0.0.1:27017/example`)

connection.model(User, User.structure())

const UserModel = connection.model('User')

const user = new UserModel({ username: 'demo' })

module.exports = user
```

The createConnection also fails if used when destructuring hence required twice. If model and schema are set using `const Model = mongoose.Model` then it works as expected.

Interestingly, removing lines 395-397 in `lib/index.js` fixes this issue. 

**What is the expected behavior?**
The model is registered as expected

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS: 8.10, Mongoose 5.1.2, MongoDB 3.6.3 Community

**Comment by lineus** [comment]
Hi @benjamin-halter. Thanks for reporting this issue. 

The only supported import statement at the moment is `import mongoose from 'mongoose';`

see #6379, #6039

**Comment by lineus** [comment]
@benjamin-halter Thanks for reporting this issue. See [this comment](https://github.com/Automattic/mongoose/issues/3768#issuecomment-172249735) on #3768. 

At the moment the supported syntax for requiring mongoose is:
`const mongoose = require('mongoose');`
