### ISSUE TITLE
bump async version to get improvements/fixes to async.queue

### ISSUE THREAD

**Issue by solotoo** [Automattic/mongoose#6505]
Current version of mongoose has a dependancy on  "async": "2.1.4" which is an old version (currently on 2.6.1). This old async is dependant on lodash 4.16.4 which `nsp check` reports as having a vulnerability to prototype pollution

https://nodesecurity.io/advisories/577
updating the async dependancy will fix this

**Comment by lineus** [comment]
Thanks for reporting @solotoo! This fix will be in 5.1.3, merged in PR #6514

**Comment by solotoo** [comment]
Hi @lineus , the fix in 5.1.3 hasn't updated the async version just added a new pull from lodash. Which, I guess fixes the issue I found but still using out of date deps. If thats for a specific reason, I happy.
