### ISSUE TITLE
Push into array of arrays

### ISSUE THREAD

**Issue by NovakZ** [Automattic/mongoose#6506]
Hello, idk this is the right place to post this kind of issue but I need some help, so I have this schema:

    const mongoose=require("mongoose");
    
    const listSchema=mongoose.Schema({
        name:{
            type: String,
            required: true
        },
        description:{
            type: String,
            required: true
        },
         tasks:[{
                name:{
                    type: String   
                },
                description:{
                    type: String                
                },
                due_date:{
                    type: String              
                },
            sub_tasks:[{
                    name:{
                        type: String,
                        required: true
                    },
                    description:{
                        type: String,
                        required: true
                    },
                    due_date:{
                        type: String,
                        required:true
                    }
                }] 
            }]
        });
    
    const list = module.exports = mongoose.model("list", listSchema);
What I want to achieve is to add a subtask into the task array, right now I have managed to add a task into this schema fairly easy, I'm finding it impossible to add a sub_task. I'm trying to use this query:

    router.put("/addSubTask/:id", (req, res,)=>{
        list.update({_id: req.params.id},{'$addToSet':{tasks:{sub_tasks:{'$each':{_id:req.body.id, name:req.body.name,
            description:req.body.description, due_date:req.body.due_date}}}}},(err, result)=>{
                if(err){
                    res.json(err);
                }else{
                    res.json(result);
                }
            })
                }) 
But its only either deleting the whole task content, or creating a new empty task. Is there any way to add a subtask correctly? Thanks!

**Comment by AbdelrahmanHafez** [comment]
One of the problems is that you're not specifying which task to add the subtask under.

Generally, you wanna do something similar to this:

```js
  list.updateOne(
    { _id: req.params.id, 'tasks.name': 'do development stuff' },
    {
      $addToSet: {
        'tasks.$.sub_tasks': {
          '$each': {
            _id: req.body.id,
            name: req.body.name,
            description: req.body.description,
            due_date: req.body.due_date
          }
        }
      }
    }
  )
```

The `$` is called [positional operator](https://docs.mongodb.com/manual/reference/operator/update/positional/) it adds the subtask to the task specified in the query (which has name of 'do development stuff')

Some other advice that I hope you might find useful:
1- You might find using [a linter](https://eslint.org/docs/user-guide/getting-started) useful to your code, it's fairly easy to use and super useful.
2- For due_date, you wanna use type: Date instead of String.
3- It's convention to use camelCase in JavaScript instead of dashes.

**Comment by lineus** [comment]
@AbdelrahmanHafez is correct @NovakZ. 

In addition to his example, if you know the task id of the task that you are adding a subtask to, you can also use the mongoose array `.id()` method to get the subdoc that you can add the sub task to. Examples of both methods below:

### 6506.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const listSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  description: {
    type: String,
    required: true
  },
  tasks: [{
    name: {
      type: String
    },
    description: {
      type: String
    },
    due_date: {
      type: String
    },
    sub_tasks: [{
      name: {
        type: String,
        required: true
      },
      description: {
        type: String,
        required: true
      },
      due_date: {
        type: String,
        required: true
      }
    }]
  }]
});


const Test = mongoose.model('test', listSchema);

const test = new Test({
  name: 'test',
  description: 'd',
  tasks: [ { name: 'first task', description: 'd2', due_date: 'tomorrow'} ]
});

function addSubTask1(doc, taskID, subTask) {
  let task = doc.tasks.id(taskID);
  task.sub_tasks.addToSet(subTask);
  return doc.save();
}

function addSubTask2(docID, taskName, subTask) {
  let cond = {
    _id: docID,
    'tasks.name': taskName
  };
  let update = {
    $addToSet: {
      'tasks.$.sub_tasks': subTask
    }
  };

  return Test.update(cond, update);
}

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log('initial:');
  console.log(found.tasks[0].sub_tasks);
  console.log();

  let tID = found.tasks[0].id;
  let newSubTask = { 
    name: 'subtask one', 
    description: 'd3', 
    due_date: 'today' 
  };
  await addSubTask1(found, tID, newSubTask);

  let again = await Test.findOne();
  console.log('addSubTask1:');
  console.log(again.tasks[0].sub_tasks);
  console.log();

  let newSubTask2 = {
    name: 'subtask two',
    description: 'd4',
    due_date: 'tomorrow'
  };
  await addSubTask2(again._id, 'first task', newSubTask2);

  let final = await Test.findOne({});
  console.log('addSubTask2:');
  console.log(final.tasks[0].sub_tasks);
  console.log();
  return conn.close();
}

run();
```
### Output:
```
issues: ./6506.js
initial:
CoreMongooseArray []

addSubTask1:
CoreMongooseArray [
  { _id: 5b0a65a5d58a12285904f04c,
    name: 'subtask one',
    description: 'd3',
    due_date: 'today' } ]

addSubTask2:
CoreMongooseArray [
  { _id: 5b0a65a5d58a12285904f04c,
    name: 'subtask one',
    description: 'd3',
    due_date: 'today' },
  { _id: 5b0a65a5d58a12285904f04d,
    name: 'subtask two',
    description: 'd4',
    due_date: 'tomorrow' } ]

issues:
```

Let us know if you have any more questions, and please always feel free to join us in any of these online communities:

[StackOverflow](https://stackoverflow.com/questions/tagged/mongoose)
[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)
