### ISSUE TITLE
Deep cloning a mongoose model with arrays inside doesn't work after #6431

### ISSUE THREAD

**Issue by fbudassi** [Automattic/mongoose#6507]
I'm using MongoDB 3.6.5 Community, NodeJS 9.11.1 and Mongoose 5.1.2, on Ubuntu 16.04.

Before the changes introduced in [this commit](https://github.com/Automattic/mongoose/commit/7edfede0bdfc1786a923cda1244a367adc58366b) to fix #6431, it was possible to do a

`_.deepClone(mongooseModel)`

where _ is lodash 4.11.1 and mongooseModel is a document that holds an array as one of its properties in the schema.

The error shown in the console looks like the following:

> (node:58559) UnhandledPromiseRejectionWarning: TypeError: Class constructor CoreMongooseArray cannot be invoked without ‘new’

Would it be possible to change the way CoreMongooseArray has been implemented in order to make it easier to deep clone?

**Comment by lineus** [comment]
@fbudassi I wasn't able to replicate the TypeError you ran into with this example:

### 6507.js
```js
#!/usr/bin/env node
'use strict';

const _ = require('lodash');
const mongoose = require('mongoose');
console.log(_.VERSION, mongoose.version, process.version);
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  arr: {
    type: [String]
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({
  arr: ['one', 'two', 'three']
});

const testClone = _.cloneDeep(test);

async function run() {
  await conn.dropDatabase();
  await testClone.save();
  let found = await Test.findOne();
  console.log(found);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6507.js
4.11.1 5.1.2 v9.11.1
{ arr: [ 'one', 'two', 'three' ],
  _id: 5b0a5d8b1df6182500b83c4b,
  __v: 0 }
issues:
```

Can you provide a reproducible example or modify mine to demonstrate the error?

**Comment by valterkraemer** [comment]
Using MongoDB `3.6.3`, Mongoose `5.1.2`, Lodash `4.17.4` I get the Error `Unhandled rejection TypeError: Class constructor CoreMongooseArray cannot be invoked without 'new'`. But after updating Lodash to `4.17.10` I don't get the error anymore.

```
const mongoose = require('mongoose')
mongoose.Promise = require('bluebird')
const Schema = mongoose.Schema
const _ = require('lodash')

mongoose.connect('mongodb://localhost/test')

const UserSchema = new Schema({
  name: String,
  items: [{
    name: String
  }]
})

const User = mongoose.model('User', UserSchema)

return User.create({
  name: 'Arnold',
  items: [{
    name: 'Item 1'
  }]
})
.then(user => {
  const copy = _.cloneDeep(user)
})
```

**Comment by lineus** [comment]
@valterkraemer I was able to reproduce with lodash 4.17.4 and confirm that 4.17.10 fixes it. Thanks for reporting this, I'm glad it's sorted out.

**Comment by fbudassi** [comment]
Thank you all for your time. As @valterkraemer and @lineus reported, upgrading lodash to 4.17.10 fixed the problem.

**Comment by joebowbeer** [comment]
Is there a unit test for this? I'm seeing the same issue now with `mongoose@6.1.4` and `lodash@4.17.21`

**Comment by joebowbeer** [comment]
@vkarpov15 Thanks! I was just wondering (via unit test) whether this had regressed. However, in my case, I think the error I was seeing was due to tripping over the _doc internal structure. I changed deepClone to toJSON and my problem went away.

**Comment by vkarpov15** [comment]
If we had a unit test, our CI would fail and we wouldn't release until we'd fixed it :) We'll take a quick look and see if there's an issue.

**Comment by piyushk96** [comment]
Problem for me too. Upgrading mongoose to the latest version (v6.2.3) just broke my code. I was using _.cloneDeep before updating the existing document to maintain an older copy of data. This caused me to move back to older version.

**Comment by vkarpov15** [comment]
@piyushk96 can you please provide some code samples that demonstrate the behavior you're seeing?

**Comment by piyushk96** [comment]
@vkarpov15 
```
async update(id, input, oldItem) {
  if (!oldItem) oldItem = await this.findOneById(id);
  const newItem = _.cloneDeep(oldItem).set(input);

  if (!newItem.modifiedPaths().length) throw new Error('Nothing to change');
  return newItem.save();
}
```
I have this simple function to update items. After updating to mongoose v6.2.3, this stopped working for schemas having array subdocument and throws following error:
```
TypeError: this.__parentArray.$path() is not a function
```

I have tried skipping `_.cloneDeep` and directly updating the oldItem but since the `set` function mutates the same object the oldItem object also gets updated in function which calls `update`.

**Comment by rickgladwin** [comment]
I don't know if it'll work for your use case (luckily it did mine), but replacing `_.cloneDeep` with `_.clone` got rid of the error for now. 

In my use case, though, I only need those top-level properties on the document/object, so `cloneDeep` is overkill.

**Comment by vkarpov15** [comment]
@piyushk96 why are you cloning the item? Why not just do `oldItem.set(input); await oldItem.save();` ?

**Comment by piyushk96** [comment]
@vkarpov15 as I mentioned `set` function mutates the same object so the oldItem also gets updated in function that calls this update function and in the caller function I need both old and new items

**Comment by vkarpov15** [comment]
@piyushk96 what version of Lodash? Below script works as expected with lodash.clonedeep@4.5.0 and Mongoose 6.3.1.

```javascript
const cloneDeep = require('lodash.clonedeep');
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  const Test = mongoose.model('Test', new mongoose.Schema({
    arr: [{ _id: false, prop1: String, prop2: String }]     
  }));

  let doc = new Test({ arr: [{ prop1: 'test' }] });
  await doc.save();
  doc = await Test.findById(doc);

  const newDoc = cloneDeep(doc);
  newDoc.set({ arr: [{ prop1: 'test2' }] });
  console.log(newDoc);
} 
```

As an alternative, you can use `const newItem = new MyModel().init(oldItem).set(input)`, which will deep clone `oldItem` for you.

**Comment by piyushk96** [comment]
Thanks, @vkarpov15, I can confirm that `_.cloneDeep` is now working in mongoose `v6.6.5`. 

But to your alternate solution `const newItem = new MyModel().init(oldItem).set(input)` has some issues. On using this initialization the newItem field contains the updated data but on calling `const newObj = newItem.toObject()` newObj still contains the old data
