### ISSUE TITLE
Connection Bug on MongoDB Arbiter Setup

### ISSUE THREAD

**Issue by larsdecker** [Automattic/mongoose#6512]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug.

**What is the current behavior?**
We got lot´s of logs on a arbiter instance.
`I ACCESS   [conn5918755] SCRAM-SHA-1 authentication failed for xxx on xxx from client 10.0.0.126:32804 ; UserNotFound: Could not find user xxx@xxx`

**If the current behavior is a bug, please provide the steps to reproduce.**

We have a replicaSet (MongoDB 3.4.4) with 3 members and 2 arbiter (MongoDB 3.4.10). An all arbiter we got a lot log message of failed connections errors (see message above).

The connections itself seems working correctly.

Our Connection looks like:

```js

const connectionString = "mongodb://xxx:xxx@mongo-34-xx:27017, mongo-34-xx:27017, mongo-34-xx:27017/xxx?replicaSet=rs0&wtimeoutMS=2000";

const mongoooseOptions = {

};

let connection = Mongoose.connect(mongoUrl, mongoooseOptions);

```

**What is the expected behavior?**
No logs on the arbiter.

**Please mention your node.js, mongoose and MongoDB version.**
nodeJS: 10.1.0
mongoose: 5.1.2
MongoDB Driver: 3.0.8

Did anyone have any idea how to fix this problem?

**Comment by lineus** [comment]
Hi @larsdecker this is a known issue with the mongodb native js driver [HERE](https://jira.mongodb.org/browse/NODE-1318?jql=project%20%3D%20NODE%20AND%20text%20~%20arbiter) which points to them refactoring the [Server Discovery And Monitoring code](https://jira.mongodb.org/browse/NODE-1290). Leaving this issue open here until the driver issue is resolved.

**Comment by larsdecker** [comment]
Thank you for your reply. Hopefully there fix the problem soon.

**Comment by lucaswxp** [comment]
How can I fix this?

**Comment by larsdecker** [comment]
We have deactivated the arbiter completely. But maybe they have fixed the bug in the new driver 3.1.4.
In the issue you can see, that the affected versions are 3.0.1 <> 3.04 of the driver version.

**Comment by lucaswxp** [comment]
Yeah, on version 5 this doesn't happen. Thanks!

**Comment by larsdecker** [comment]
@lucaswxp 

On which version? Did you use the latest version of mongoose?
We have the problem with the connection with mongoose 5.1.2, but the mongodb-team has worked on the driver.

Did they fixes the problem with the arbiter in the latest driver version?

**Comment by lucaswxp** [comment]
Hey Lars!

Currently I'm using mongoose@5.3.7, and the problem doesn't happen.

Em seg, 5 de nov de 2018 às 12:24, Lars Decker <notifications@github.com>
escreveu:

**Comment by larsdecker** [comment]
Good to know, that the driver team has fixed that issue.
I think we can here close the issue.

**Comment by vkarpov15** [comment]
@tzwickl have you tried upgrading to the latest version of Mongoose?
