### ISSUE TITLE
Update middlewares are not working

### ISSUE THREAD

**Issue by tosbaha** [Automattic/mongoose#6513]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Update middleware is not working.
**If the current behavior is a bug, please provide the steps to reproduce.**
I have following middleware setup.

```javascript

var ParcelSchema = mongoose.Schema({
    owner : { type:mongoose.Schema.Types.ObjectId, ref: 'User' ,index: true},
    name: String,
    trackingNumber: String,
    updateDate: Date,
    startDate: {type: Date, default:Date.now }
});

ParcelSchema.index({ owner: 1, trackingNumber: 1 },{ unique: true }); // schema level

ParcelSchema.pre('find', function() {
    console.log('Pre Find');
    console.log(this instanceof mongoose.Query); // true
});

ParcelSchema.pre('update',function(next) {
    console.log('Pre Update!');
    this.updateDate = new Date();
    next();
});

ParcelSchema.pre('save', function (next) {
    console.log('Pre Save!');
    this.updateDate = new Date();
    next();
});


ParcelSchema.post('find', function(result) {
    console.log(this instanceof mongoose.Query); // true
    // prints returned documents
    console.log('find() returned ' + JSON.stringify(result));
    // prints number of milliseconds the query took
    console.log('find() took ' + (Date.now() - this.start) + ' millis');
});


ParcelSchema.post('update',function(next) {
    console.log('Post Update!');
    this.updateDate = new Date();
    next();
});

ParcelSchema.post('save', function(doc) {
    console.log('%s has been saved', doc._id);
});

var Parcel = mongoose.model("Parcel", ParcelSchema);
module.exports = Parcel;
```
I am using following code to update set of values 

```swift
Parcel.findOneAndUpdate({_id: id, owner:userId},{$set:input}, {new: true})
```

**What is the expected behavior?**
I want to see console.log
**Please mention your node.js, mongoose and MongoDB version.**
Node v9.11.1 MongoDB 3.2.19 Mongoose v4.13.13

**Comment by AbdelrahmanHafez** [comment]
`findOneAndUpdate` and `update` are two different methods, and have different middlewares.

Try this instead:

 ```js
ParcelSchema.pre('findOneAndUpdate', function (next) {
  console.log('findOneAndUpdate middleware');
});
```

**Comment by tosbaha** [comment]
Thanks @AbdelrahmanHafez I didnt see this middleware in documents. In 4.x help [docs](http://mongoosejs.com/docs/4.x/docs/middleware.html), it only shows an example for `find` hook under explanation of `findOneAndUpdate` It is really misleading.

**Comment by lineus** [comment]
Thanks for jumping in and assisting @AbdelrahmanHafez.

@tosbaha ,

>it only shows an example for find hook under explanation of findOneAndUpdate It is really misleading.

I'm assuming you mean the example under the heading `Notes on findAndUpdate() and Query Middleware`. This section of the docs isn't an explanation of findOneAndUpdate, but just a couple of important points about update/findOneAndUpdate and how query middleware differ from document middleware.

If you would like to make any improvements to the docs, please feel free to submit a Pull Request for the docs, [the instructions are here](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#documentation)
