### ISSUE TITLE
Model.remove works even when given an invalid _id to remove

### ISSUE THREAD

**Issue by fnoori** [Automattic/mongoose#6515]
Bug Report.

Problem function

```
Vehicle.remove({'_id': vehicleId, 'Dealership._id': dealershipId})
    .exec().then(result => {
        console.log(result);

        return resMessages.resMessagesToReturn(200, resMessages.VEHICLE_DELETED_SUCCESSFULLY, res);
    }).catch(removeErr => {
        resMessages.logError(removeErr);
        resMessages.resMessagesToReturn(500, removeErr, res);
    });
}
```

____
#### Current behaviour
When passing a valid _id and valid Dealership._id, remove works as intended, the vehicle is removed from the collection.
However, when passing an invalid _id and invalid Dealership._id, the function also executes without any errors, but obviously since nothing in the database matches the _ids, nothing is deleted.

___
#### Steps to reproduce
Not able to create gist to reproduce the issue as it is connected to my private instance of MongoDB.

___
#### Expected behaviour
When passing invalid parameters in the Model.remove call (in this **case _id** and **Dealership._id**), it should throw an error.

# EDIT
Contents of *result* when passing an invalid _id
**Notice the** ```n: 0```
```
{ n: 0,
  opTime:
   { ts: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1527208824 },
     t: 3 },
  electionId: 7fffffff0000000000000003,
  ok: 1,
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1527208824 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1527208824 },
     signature: { hash: [Object], keyId: [Object] } } }
```

Contents of *result* when passing a valid _id
**Notice the** ```n: 1```
```
{ n: 1,
  opTime:
   { ts: Timestamp { _bsontype: 'Timestamp', low_: 30, high_: 1527208852 },
     t: 3 },
  electionId: 7fffffff0000000000000003,
  ok: 1,
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 30, high_: 1527208852 },
  '$clusterTime':
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 30, high_: 1527208852 },
     signature: { hash: [Object], keyId: [Object] } } }
```
I don't know if this result is by design or it's a bug, any insight would be appreciated !
___
#### Versions
NodeJS: **6.11.2**
Mongoose: **5.0.17**
MongoDB: **3.6.4**

**Comment by lineus** [comment]
@fnoori When you pass in a key/value to a query condition object where that path is defined in your schema as an ObjectId type, mongoose will attempt to cast the string to an objectId and return an error if it can't.

for example:

### 6515.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  other: Schema.Types.ObjectId
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Francis',
  other: new mongoose.Types.ObjectId()
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let rem = await Test.remove({ _id: test._id, other: 'x' }); // can't cast 'x' to an ObjectId.
  console.log(rem);
  return conn.close();
}

run().catch(error);

function error(e) {
  console.log(e.message);
  return conn.close();
}
```
### Output:
```
issues: ./6515.js
Cast to ObjectId failed for value "x" at path "other" for model "test"
issues:
```

On the other hand, if the query conditions object that is passed into remove does contain **valid** string representations of ObjectIDs, but doesn't match any documents (ie. you query for a set of key/value pairs that don't exist on any docs) then nothing will get removed and the n property of the return object will be 0 ( **meaning 0 documents were removed** ). 

This isn't an error condition but rather the expected behavior of trying to remove something that doesn't exist.

A few potential causes for this are:
   1. an issue with the code that generated the condition object keys/values 
   1. an issue with your dataset having incomplete/incorrect information.
   1. incorrect user input in a form field

In addition to handling the error in the `Query.catch()` method, you can test for `n === 0` in the `Query.then()` method and take some action, ie. logging, or a 2nd query based on a different set of conditions etc.

for example:
```js
Vehicle.remove({'_id': vehicleId, 'Dealership._id': dealershipId})
    .then(result => {
      if (result.n) {
        return resMessages.resMessagesToReturn(200, resMessages.VEHICLE_DELETED_SUCCESSFULLY, res);
      } else {
        someFunctionToHandleUnsuccessfulThings()
      }
    })
```

**Comment by fnoori** [comment]
Thanks for the reply @lineus. I have (since I had originally posted this issue) been testing for the ```n``` value.

Since this is the expected behaviour of the system, then I will close this issue 👍

**Comment by praveen70** [comment]
const graphql = require('graphql');
const _=require("lodash");
const Book = require("../models/book");
const Author = require("../models/author");
const {
    GraphQLObjectType, GraphQLString,GraphQLInt, GraphQLID, 
    GraphQLSchema,
    GraphQLList
} = graphql;




const BookType = new GraphQLObjectType({
    name:'Book',
    fields:()=>({
        id:{type:GraphQLID},
        name:{type:GraphQLString},
        genre:{type:GraphQLString},
        author:{
            type:AuthorType,
            resolve(parent, args){
                console.log(parent);
                // return _.find(authors,{id:parent.authorId});
            }
        }
    })
})
const AuthorType = new GraphQLObjectType({
    name:'Author',
    fields:()=>({
        id:{type:GraphQLID},
        name:{type:GraphQLString},
        age:{type:GraphQLInt},
        books:{
            type:new GraphQLList(BookType),
            resolve(parent,args){
                // return _.filter(books,{authorId:parent.id});
            }
        }
    })
})

const RootQuery = new GraphQLObjectType ({
    name:"RootQueryType",
    fields:{
        books:{
            type:BookType,
            args:{id:{type:GraphQLID}},
            resolve(parent, args){
                
                //return _.find(books,{id:args.id});
            }
        },
        author:{
            type:AuthorType,
            args:{id:{type:GraphQLID}},
            resolve(parent, args){
                //return _.find(authors,{id:args.id});
            }
        },
        books:{
            type:new GraphQLList(BookType),
            resolve(parent, args){
                //return books
            }
        },
        authors:{
            type:new GraphQLList(AuthorType),
            resolve(parent, args){
                //return authors
            }
        }

    
    }
});
const Mutation  = new GraphQLObjectType({
    name: "Mutation",
    fields:{
        addAuthor:{
            type:AuthorType,
            args:{
                name:{type:GraphQLString},
                age:{type:GraphQLInt},
                
            },
            resolve(parent,args){
                let author = new Author({
                    name:args.name,
                    age:args.age,
                    
                });
                return author.save();
            }

        }
    }
});

module.exports = new GraphQLSchema({
    query:RootQuery,
    date: { type: Date, default: Date.now },
    mutation:Mutation
})


////getting error
{
  "errors": [
    {
      "message": "not authorized on praveen_graphql to execute command { insert: \"authors\", ordered: true, $clusterTime: { clusterTime: Timestamp(1536137345, 18), signature: { hash: BinData(0, 046EAFCC070976F77AEFFA253C8FB104566D7887), keyId: 6597602102082535425 } }, lsid: { id: UUID(\"b0c9c03a-db3f-427e-880b-9225324d52fd\") }, $db: \"praveen_graphql\" }",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addAuthor"
      ]
    }
  ],
  "data": {
    "addAuthor": null
  }
}

**Comment by vkarpov15** [comment]
@praveen70 can you clarify what the above means and how it is relevant to this issue?
