### ISSUE TITLE
Registering model on mongoose.createConnection() registers wrong name

### ISSUE THREAD

**Issue by benjamin-halter** [Automattic/mongoose#6517]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently the model method on the connection prototype does not check if the passed `name` is a function ie. extending the model class. Therefore it is not registered under the correct name to the connections models and throws a schema not found error. 

**If the current behavior is a bug, please provide the steps to reproduce.**

The code to check if the name is an instance of the `Model` should also be used in the connection model method: 

```
if (typeof name === 'function') {
    model = name;
    name = model.name;
    if (!(model.prototype instanceof Model)) {
      throw new mongoose.Error('The provided class ' + name + ' must extend Model');
    }
  }
```

Currently the name is registered as a strignified version of the function which when using the correct name is obviously not found locally or if **the cache is off** it also won't be registered to the base instance. As such it will throw a MissingSchema error.

**What is the expected behavior?**
A model extending the `mongoose.Model` constructor can be passed to a non-default mongoose connection ie. mongoose.createConnection(uri) and register the model correctly.

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS: 8.10, Mongoose 5.1.2, MongoDB 3.6.3 Community

**Comment by lineus** [comment]
confirmed with the following repro script

###6517.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const conn = mongoose.createConnection('mongodb://localhost/test');
const Schema = mongoose.Schema;
const Model = mongoose.Model;

const schema = new Schema({
  name: String
});

class Person extends Model { }

const Test = conn.model(Person, schema);

process.stdout.write('connection model names: ');
console.log(conn.modelNames());

const test = new Test({
  name: 'Wyatt'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log(found);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6517.js
connection model names: [ 'class Person extends Model { }' ]
{ _id: 5b094defc048d300e5f1e7c7, name: 'Wyatt', __v: 0 }
issues:
```
