### ISSUE TITLE
$lookup and $match help request

### ISSUE THREAD

**Issue by alperenboyaci** [Automattic/mongoose#6518]
Hi
I need getting 3level treeview data from database and I tried to make it with using $lookup function and it is working correctly just now with code below.
But I need complex queries and sorting on it which I cannot make it.
Can anybody help me ?
Thanks

```
app.get('/sm/:appId', function (req, res) {
    storemodels.aggregate([
            {$unwind:{path: '$modData'}},

                //level-2 :titles 
                { $lookup: { 
                    from: 'titles', 
                    localField: 'modData.titleId', 
                    foreignField: '_id', 
                    as: 'titles' }    
                },

                    //level-3 : issues
                    { $lookup: { 
                        from: 'issues', 
                        localField: 'titles._id', 
                        foreignField: 'titleId', 
                        as: 'issues'},
                    }
        ])
       .exec(function (err, results)
   {
        if (err) return res.status(500).send("There was a problem finding the Issues.");
        if (!results) return res.status(404).send("No Issues found.");
        res.status(200).send(results)
    })
});  

```

I need complex data filtering/matching/sorting/selecting for each level internally summary that (looks not like mongodb syntax): 

	level-1 query  - appId=req.params.appId
				 and isActive=true
				 orderby updatedAt
					 
	level-2 query  - puslished=true

	level-3 query  - avalibility=true 
					 and issueReleaseDate<Date 
					 and (issueEndDate =null or >Date) 
					 and (issueType = [default,free]) 
					 and (issueDevice= Universal or paramsDevice)
					 and (issueLang= Universal or paramsLang)
					 orderby createdAt

				
	
May be developers can improve $lookup function to the in the future:					
		{ $lookup: { 
                        from: '', 
                        localField: '', 
                        foreignField: '', 
                        as: ''
			****match: ????
			****sort: ???
			****select: ???},
                    }

**Comment by vkarpov15** [comment]
I'm not sure I understand your question, can you please clarify? If you're looking to add matching and filtering to $lookup, [mongoose aggregate supports chaining](http://mongoosejs.com/docs/api.html#aggregate_Aggregate), so you could just do `storemodels.aggregate().unwind(/*...*/).lookup(/*...*/).match(/*...*/).lookup(/*...*/)`
