### ISSUE TITLE
Mongo 4.0

### ISSUE THREAD

**Issue by Igor-Lopes** [Automattic/mongoose#6521]
Is mongoose going to support Mongo 4.0 new features ? I've notice that [Mongo 4.0](https://www.mongodb.com/blog/post/mongodb-40-release-candidate-0-has-landed) Release Candidate 0 is available. 

**Do you want to request a *feature* or report a *bug*?**
Feature

**Comment by lineus** [comment]
@Igor-Lopes there will continue to be patch releases for 4.x to fix bugs but future development of new features will take place in version 5. Can you elaborate on what is preventing you from upgrading to 5? What feature are you hoping to have?

**Comment by Igor-Lopes** [comment]
@StefanoDeVuono That's right. @lineus I refer to Mongo 4.0 new features, such as Multi-Document ACID Transactions.

**Comment by lineus** [comment]
@Igor-Lopes my bad :smile: I’m sure we will, not sure if there’s a roadmap or timeline.

@vkarpov15 do you have a mongoose version in mind for adding mongodb server version 4 support?

**Comment by vkarpov15** [comment]
@lineus we're waiting on the [MongoDB driver](https://www.npmjs.com/package/mongodb) to release their 3.1.0 release for 4.0 support. Currently, the plan is to ship mongoose 5.2.0 to support MongoDB 4.0's new features. Given how big this release is, we'll release a 5.2.0-rc0 in June.

**Comment by koresar** [comment]
Good news. MongoDB driver v3.1 was released a week ago.
https://github.com/mongodb/node-mongodb-native/releases/tag/v3.1.0

And seems like there is multi-doc transactions support in it!
https://github.com/mongodb/node-mongodb-native/compare/v3.1.0...master#diff-f75c26f0111411002bdf59671ac76906R55

**Comment by vkarpov15** [comment]
@koresar yep! Here's a [blog post to get you started with MongoDB transactions in Node.js](http://thecodebarbarian.com/a-node-js-perspective-on-mongodb-4-transactions.html) with the MongoDB driver and mongoose :+1:
