### ISSUE TITLE
Dynamic validator message

### ISSUE THREAD

**Issue by lucandrade** [Automattic/mongoose#6523]
# Validator message as a function

**Feature**
I want to be able to pass a function as a parameter to the validator message

**Current behavior**
We cannot pass a function as a parameter to the `message`

**Expected behavior**
We can have a dynamic message based on the value or path

### Use case

I have a generic message for a duplicated entry in the db.

```
This {{PATH}} is already registered
```

I want to be able to translate this message.  
At the time I'm passing the message to the validator I don't know which path will be.  
To make it work I must create one translation for each unique field I have on my db.   

MongoDB version: 3.6.0
Mongoose version: 5.0.16

I had made this change on my local mongoose. I can open a PR if that works for you. Thanks.

**Comment by lineus** [comment]
@lucandrade PRs are always welcome. [The guidelines are here](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md#fixing-bugs--adding-features).
