### ISSUE TITLE
mongoose timestamps

### ISSUE THREAD

**Issue by hadiMh** [Automattic/mongoose#6525]
Hi,
i added this to mongoose schema to use timestamps. When I find a blog post data from my database using mongoose, i send the founded data to a page using ejs template language. now i want to get the createAt time from my data in ejs file but i can't. Is there a solution for it or not? Tnx in advance

**Comment by lineus** [comment]
@hadiMh It's very difficult to help without seeing example code that is minimally complete and reproducible. Please either create a complete example like the one below or modify this one to reproduce your issue.

( **NOTE:** the default properties are **createdAt** and **updatedAt** ):

### 6525.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

schema.set('timestamps', true);

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Ted'
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log(`name: ${found.name} created: ${found.createdAt}`);
  return conn.close();
}

run();
```
### Outputs:
```
issues: ./6525.js
name: Ted created: Sun May 27 2018 05:41:12 GMT-0400 (EDT)
issues:
```
