### ISSUE TITLE
Virtual nested populate breaks options on parent populate.

### ISSUE THREAD

**Issue by Mikeysax** [Automattic/mongoose#6528]
I believe there is a bug using nested populates and options.

My current query is as follows:
```js
...
await Post.find(
          { teacher: req.params.id },
          {},
          {
            sort: { createdAt: -1 },
            limit: 5,
            skip: parseInt(req.query.skip, 10)
          }
        ).populate([
        {
          path: 'comments',
          options: {
            limit: 5,
            sort: { createdAt: -1 }
          },
          populate: { path: 'user', select: '-password' }
        }
      ])
...
```

When including `options` on the `comments` populate (which has another populate nested inside), it returns more than specified `limit` and `sort` is not applied. If the nested populate is removed, it works as intended.

Currently, using:

Node 10.2.1
Mongoose 5.1.2
Mongo 3.6.5

Is this a bug or am I missing something?

I believe this might be related: https://github.com/Automattic/mongoose/issues/4321

**Comment by vkarpov15** [comment]
Yeah limit and populate has been a thorn in our side for a very long time. The general idea is that we'll have to fall back to doing separate queries for each doc if you use `populate()` with `limit` and you get multiple docs back.
