### ISSUE TITLE
feathers-mongoose, promises, and runValidators, oh my!

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6541]
source code for feathers-mongoose has this comment:

    // NOTE (EK): We need this shitty hack because update doesn't
    // return a promise properly when runValidators is true. WTF!

I'll try and reproduce this based on the context in the [source code here](https://github.com/feathersjs-ecosystem/feathers-mongoose/blob/e03287691c505769c0e33d6bc30792221a423b7b/lib/service.js#L269)

**Comment by lineus** [comment]
unable to duplicate.

**Comment by vkarpov15** [comment]
Weird. Might have been a bug at some point in the past or just a PEBKAC moment, but glad it isn't a bug anymore. Thanks for looking into this.
