### ISSUE TITLE
Regression in 5.1.3: TypeError: Cannot read property 'toHexString' of undefined

### ISSUE THREAD

**Issue by ssilve1989** [Automattic/mongoose#6542]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Creating models via Typegoose results in 
```
TypeError: Cannot read property 'toHexString' of undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a mongoose connection and pass it to a TypeGoose model as 
```
    const someModel = new SomeModel({}).getModelForClass(SomeModel, {
      existingConnection: connection,
    });
```

**What is the expected behavior?**
Expect no errors to be thrown when using the connection.

**Please mention your node.js, mongoose and MongoDB version.**
node: 8.11.1
mongoose: 5.1.3
mongoDB: 3.6.3

This does not occur in my previous version which was `mongoose@5.0.16` and the Typegoose version has not changed.

**Comment by lineus** [comment]
@ssilve1989 can you please provide a more complete repro script? I'm not familiar with Typegoose, but I'd like to help if I can.

This could be related to a schema.method called `toHexString` that was added very briefly in 5.0.16/17  and was subsequently removed in 5.0.18 ( see #6115 ). Not sure if maybe your code is trying to access the removed method, or maybe the specific version of Typegoose is? - just a thought
