### ISSUE TITLE
" $dateToString to return the date field as formatted strings" Is it ready?

### ISSUE THREAD

**Issue by huuquyasb** [Automattic/mongoose#6562]
Can i use "datetosting" on Model.find()?
Link
https://docs.mongodb.com/manual/reference/operator/aggregation/dateToString/

**Comment by lineus** [comment]
@huuquyasb aggregation operators are only available in aggregation pipeline stages in calls to `Model.aggregate()`. 

If you would like some help converting a date stored in mongodb to a string, please provide a code sample that includes your schema and an example of what you want the end result to be.
