### ISSUE TITLE
Can't compare with $eq, but $ne works

### ISSUE THREAD

**Issue by johnantoni** [Automattic/mongoose#6564]
Related to issue https://github.com/Automattic/mongoose/issues/2752

I can't compare a value with $eq, this fails:

    Classroom.find({ 'user': id, 'archived': {$eq: true} })

but this is ok

    Classroom.find({ 'user': id, 'archived': {$ne: false} })

Using mongoose 5.0.10

Anyone else having the same issue? or am I doing this wrong?

**Comment by lineus** [comment]
@johnantoni 

I tried to replicate with this script, but it works for me:

### 6564.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  george: Boolean
});

const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 0; i < 100; i++) {
  let g = ( i % 2 === 0);
  tests.push(new Test({ name: `test${i}`, george: g }));
}

async function run() {
  await conn.dropDatabase();
  await Test.create(tests);
  let found = await Test.find({ george: { $eq: true } });
  assert.strictEqual(found.length, 50);
  return conn.close();
}

run();
```

### Output:
```
issues: ./6564.js
issues:
```

Can you please either modify the above code or create your own complete example that demonstrates the failure?

**Comment by johnantoni** [comment]
Thanks for the speedy reply.

I'll close this, did it wrong.

Thanks again,
