### ISSUE TITLE
Schema.pre('save') not accepting closures

### ISSUE THREAD

**Issue by wesleimarinho** [Automattic/mongoose#6565]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Expected object to be available inside closure, as it does with functions.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;


const schema = new Schema({
  name: String
});

//schema.pre('save', function (next) {
schema.pre('save', (next) => {
  console.log(this.name);
  next();
});

const Test = mongoose.model('test', schema);

const test = {name: "Xyz"};

async function run() {
  await conn.dropDatabase();
  await Test.create(test);
  
  return conn.close();
}

run().catch(console.error);
```

**What is the expected behavior?**

To print the name of the object, however if I interchange the commented line with the next one it will print object name as expected.

**Please mention your node.js, mongoose and MongoDB version.**

Mongoose 5.1.4
NodeJS: 8.9.4
MongoDB: 3.6.3

**Comment by lineus** [comment]
@wesleimarinho please see the [faq here](http://mongoosejs.com/docs/faq.html#arrow-functions). You can't use arrow functions for middleware. They don't treat `this` the same as common js functions. This behavior is inherent to arrow functions as [described here on mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by vkarpov15** [comment]
Also, please be aware that "arrow function" and "closure" are very different terms. You can have an arrow function that isn't a closure and a closure that isn't an arrow function. A closure is just a fancy way of saying [a function that's inside another function](https://www.w3schools.com/js/js_function_closures.asp). An arrow function is a function declared using the `=> {}` syntax that has certain neat properties like lexical context (`this` is the same inside the arrow function as outside the arrow function). There's nothing stopping you from declaring a top-level arrow function, in which case it wouldn't be a closure.
