### ISSUE TITLE
findOne() query chains using custom query helpers return an array

### ISSUE THREAD

**Issue by LK** [Automattic/mongoose#6567]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using a custom query helper in a `findOne()` query, it still returns an array of results instead of one object.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduced here: https://gist.github.com/LK/fe2618b295db417f7b50fcc8e8ccd90a

**What is the expected behavior?**
`findOne()` should return one object instead of an array of matches.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 9.5.0
Mongoose: 5.1.4
MongoDB: 3.4.2

**Comment by lineus** [comment]
@LK Thanks for the complete repro script! 

## In your query helper, you are explicitly returning a find query which returns an array. 

### 6567.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');

let embedded = new mongoose.Schema({
  val: Number
});

let schema = new mongoose.Schema({
  name: String,
  embedded: embedded
});

schema.query.isJohn = function () {
  return this.find({ name: 'John' });
};

let Model = mongoose.model('Model', schema);

Model.remove()
  .then(() => {
    return Model.create([
      {
        name: 'Jim',
        embedded: {
          val: 5
        }
      },
      {
        name: 'John',
        embedded: {
          val: 6
        }
      }
    ]);
  })
  .then(() => {
    return Model.findOne().isJohn();
  })
  .then(results => {
    console.log(results);
  });
```
### output: 
```
issues: ./6567.js
[ { _id: 5b1bb13b9884d35af00857fa,
    name: 'John',
    embedded: { _id: 5b1bb13b9884d35af00857fb, val: 6 },
    __v: 0 } ]
^C
issues:
```

## If you change the `find` in the query helper to `where` you get a single document as expected.
```js
schema.query.isJohn = function () {
  return this.where({ name: 'John' });
};
```
### output:
```
issues: ./6567.js
{ _id: 5b1bb1a403f2b65b1600d15d,
  name: 'John',
  embedded: { _id: 5b1bb1a403f2b65b1600d15e, val: 6 },
  __v: 0 }
^C
issues:
```

**Comment by LK** [comment]
@lineus Makes sense, thank you for clarifying! The documentation on query helpers is a bit sparse, I could only find [this example](http://mongoosejs.com/docs/guide.html#query-helpers) in the docs which uses `find` instead of `where` -- should that example be updated to use `where`?

**Comment by lineus** [comment]
The example worked well because both the query and the helper used find, but I think by making the query helper in the example use where we can show off the ability to share the helper between query types. Thanks @LK!
