### ISSUE TITLE
Projecting from another schema

### ISSUE THREAD

**Issue by Drago96** [Automattic/mongoose#6569]
I currently have a PostSchema which looks something like this: 

```
{
  title: String,
  content: String
}
```

And a CommentSchema which looks something like this:

```
{
  content: String,
  post: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Post"
  }
}
```

I prefer to not store the comments as subdocuments in the PostSchema, or as an array of refs, in case the comments for a single post become way too many.

On querying a post, however, I want to return the comments count, alongside all the other relevant information.

I am currently achieving this with a virtual and an instance method on the PostSchema like this:

```
PostSchema.virtual("commentsCount")
  .get(function() {
    return this._commentsCount || null;
  })
  .set(function(value) {
    this._commentsCount = value;
  });

PostSchema.methods.setCommentsCount = async function() {
  const post = this;

  const commentsCount = await Comment.count({ post: post._id });

  post.commentsCount = commentsCount;
};
```

However, if I want to get the comments count for multiple posts at once, I feel like this will be a big performance hit.

Is there any way to get the count of related objects from another Schema using PostSchema.find({}) and if there isn't what is the most elegant way to approach this.

**Comment by lineus** [comment]
@vkarpov15 might have more insight into this than I, but I think if you have an index built on your comment collection for the post field, this approach is fine. You **could** instead add a `commentsCount` field to your post schema and have a post-save hook on the comments schema that increments the field on the specified post. 

something like:
```js
commentSchema.post('save', function() {
  Post.update({ _id: this.post }, { $inc: { commentsCount: 1 }})
});
```

**Comment by Drago96** [comment]
@lineus  Thank you for the response, very clean approach and I will probably use it.
I also tried using an aggregation query which allowed me to get the comments count for all posts in a single query like this:

`  const commentsCount = await Post.model("Comment").aggregate([
    {
      $match: {
        post: {
          $in: postIds
        }
      }
    },
    {
      $group: {
        _id: {
          post: "$post"
        },
        count: { $sum: 1 }
      }
    }
  ]);`

**Comment by vkarpov15** [comment]
@lineus ' approach is the right one. Denormalizing and storing the `commentsCount` seems counter-intuitive if you're coming from an SQL background, but in MongoDB the principle is to store what you query for. If you need the `commentsCount`, store the comments count and increment it when there's a new comment added, because if you're like most apps you load the number of comments orders of magnitude more often than you change the number of comments.
