### ISSUE TITLE
Dates and Mongoose

### ISSUE THREAD

**Issue by wavded** [Automattic/mongoose#657]
I am running into an interesting issue.  I initially started diving into it here:

https://github.com/andrewplummer/Sugar/issues/78

But found out the vanilla JS produces the same issue.  Whenever I store a date (no timestamp) and then I go to retrieve that date and format it, its a day behind.  There is a simple example in the case, I can get you more info if you need.  I'm central time.  Here is a snippet of a stored doc in MongoDB that will be a date behind when I format it (e.g. getDate()).

``` json
{ "_id" : ObjectId("4eeb6c1822501a661600003b"), 
  "dateExample" : ISODate("2011-12-19T00:00:00Z")
}
```

Does mongoose store UTC dates to MongoDB or is there some other reason why this would be?

**Comment by nasr18** [comment]
i have a field like this....

`"addedOn" : ISODate("2016-03-10T14:18:55.339Z")`

and i wanna get count of data which are inserted today. how to get that????

**Comment by vkarpov15** [comment]
Use  $gte : moment.utc().startOf('day').toDate() and $lte: moment.utc().endOf('day').toDate()

**Comment by nasr18** [comment]
how do i can store data with and without time??? like one field with datetime and another field only with date.

**Comment by vkarpov15** [comment]
No way to do that right now. In the past I've just stored dates as a string in 'YYYYMMDD' format (like '20160317'). This has the nice feature that you can still sort by date and use ordering operators like $gt.

**Comment by nasr18** [comment]
I need help to fetch data from mongodb using mongoose. I have to weekly data in graph. So If today is monday means i need data from last monday to this monday(today) and if today is tuesday means i need to show data from last tuesday to this tuesday(today). Help me pls.

**Comment by vkarpov15** [comment]
@nasr18 `MyModel.find({ timestamp: { $gte: moment().subtract(7, 'days').toDate(), $lte: moment().toDate() } });`

Or use https://www.npmjs.com/package/mongodb-moment to make the `toDate()` call unnecessary

**Comment by Dom07** [comment]
> Use $gte : moment.utc().startOf('day').toDate() and $lte: moment.utc().endOf('day').toDate()

Thanks man this made my day.
