### ISSUE TITLE
`.pre('validate'` doesn't run on updates but validations run

### ISSUE THREAD

**Issue by ForsakenHarmony** [Automattic/mongoose#6573]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Validation runs (`runValidators: true`), but the middleware doesn't

**If the current behavior is a bug, please provide the steps to reproduce.**

1. create a schema
2. add a pre validate middleware 
3. create and then update 

**What is the expected behavior?**

the validate middleware should run

**Please mention your node.js, mongoose and MongoDB version.**

Nodejs: 10.4.0
MongoDB: 3.6.5

**Comment by lineus** [comment]
@ForsakenHarmony pre and post validate hooks only get called when you call `doc.save()` or `doc.validate()`. 

This is because the value of `this` in validate middleware is the document and with queries the document probably doesn't exist in memory. 

There is a previous issue [here](https://github.com/Automattic/mongoose/issues/964) for historical context. 

You can use pre and post `update` hooks instead accordingly.

For Example:

### 6573.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;
var called = 0;

const schema = new Schema({
  name: {
    type: String,
    validate: function (val) {
      console.log(`validating: ${val}`);
      return true;
    }
  }
});

schema.pre('validate', function() {
  console.log(`called: ${++called}`);
});

schema.pre('update', function() {
  console.log('pre-update: `this` is the query,', this instanceof mongoose.Query);
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Thelonious'
});

async function run() {
  await conn.dropDatabase();
  await test.validate();
  await test.save();
  await Test.update({ _id: test._id }, { name: 'Monk' }, { runValidators: true });
  let found = await Test.findOne({ _id: test._id });
  console.log(`found: ${found}`);
  assert.strictEqual(called, 2);
  return conn.close();
}

run();
```
### Outputs:
```
issues: ./6573.js
called: 1
validating: Thelonious
called: 2
validating: Thelonious
pre-update: `this` is the query, true
validating: Monk
found: { _id: 5b1cf010eb75d81d41ad23fa, name: 'Monk', __v: 0 }
issues:
```
