### ISSUE TITLE
throw new mongoose.Error.MissingSchemaError(name);       ^ MissingSchemaError: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by abrahamwilliam** [Automattic/mongoose#6576]
const JwtStrategy = require("passport-jwt").Strategy;
const ExtractJwt = require("passport-jwt").ExtractJwt;
const mongoose = require("mongoose");
const User = mongoose.model("users");
const keys = require("../config/keys");

const opts = {};
opts.jwtFromRequest = ExtractJwt.fromAuthHeaderAsBearerToken();
opts.secretOrKey = keys.secretOrKey;

module.exports = passport => {
  passport.use(
    new JwtStrategy(opts, (jwt_payload, done) => {
      User.findById(jwt_payload.id)
        .then(user => {
          if (user) {
            return done(null, user);
          }
          return done(null, false);
        })
        .catch(err => console.log(err));
    })
  );
};

**Comment by abrahamwilliam** [comment]
What is the issue above , i have schema correctly in the above defined, please help

**Comment by lineus** [comment]
@abrahamwilliam Please check out [the guide here](http://mongoosejs.com/docs/guide.html#definition)

You need to define a schema to pass into `mongoose.model()` as the second parameter.

```js
const userSchema = new mongoose.Schema({
   email: {type: String, required: true},
   password: {type: String, required: true}
});

const User = mongoose.model('users', userSchema); // note the second parameter here
```

Mongoose will use this schema to determine if the contents of the user data you are trying to save to the db match what you expect, and that the data is complete. 

Here is an example with a stack trace that shows where the error is:

### 6576.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;

const Test = mongoose.model('test');

const test = new Test({
  key: String
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  return conn.close();
}

run().catch(console.error);
```
### Outputs:
```
issues: ./6576.js

/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/index.js:337
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "test".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/Users/lineus/dev/Help/mongoose5/node_modules/mongoose/lib/index.js:337:13)
    at Object.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6576.js:8:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
issues:
```

Note the following line under the `Outputs:` header above:
```
at Object.<anonymous> (/Users/lineus/dev/Help/mongoose5/issues/6576.js:8:23)
```
This calls out the 8th line of the example script which is:
```
const Test = mongoose.model('test');
```

**Comment by lineus** [comment]
@abrahamwilliam please also feel free to join us in any or all of the following online communities:
[StackOverflow](https://stackoverflow.com/questions/tagged/mongoose)
[Gitter.im](https://gitter.im/Automattic/mongoose)
[Slack](https://mongoosejsteam.slack.com/)

**Comment by hjeff15** [comment]
This was HUGELY helpful! Thanks!
