### ISSUE TITLE
Configuration to make runValidators default to true?

### ISSUE THREAD

**Issue by joeytwiddle** [Automattic/mongoose#6578]
Until I discovered [runValidators](http://mongoosejs.com/docs/validation.html#update-validators) recently, I had always assumed mongoose did validation on updates by default. But it doesn't!

Would it be possible to add a global config or a schema config that would make `runValidators` default to `true` for all updates? (We could then override with `false` on individual queries, if we need to.)

----

The documentation says:

> Be careful: update validators are off by default because they have several caveats.

And the caveats are well documented below that.

In our apps, we tend to use only simple validators, so most of the caveats don't apply. If we do expand our validators, we could either turn off the option for that schema, or adapt our validators and update queries as per the docs.

**Comment by vkarpov15** [comment]
That's a good idea. Right now the way to do it would be with a global plugin:

```javascript
mongoose.plugin(schema => {
  schema.pre('findOneAndUpdate', setRunValidators);
  schema.pre('updateMany', setRunValidators);
  schema.pre('updateOne', setRunValidators);
  schema.pre('update', setRunValidators);
});

function setRunValidators() {
  this.setOptions({ runValidators: true });
}
```

Would be neat to have this as a one-liner though.

**Comment by joeytwiddle** [comment]
Some other nice global one-liners might be:

- Make all fields `required: true` by default.
- Make all schemas `strict: 'throw'` by default.

I have been using those policies in our projects (implemented in our common model builder function) because it helps to detect typos and other developer mistakes sooner. We override the defaults when we need to.

So if you are thinking of introducing some global settings in future, let's try to find something that works neatly for all of those!

Anyway the example above is good enough for me, for now, thanks.

**Comment by vkarpov15** [comment]
The `required: true` one I'm not sure is a good idea. I like the `strict: 'throw'` idea though, opened up #6658 to track.

**Comment by AbdelrahmanHafez** [comment]
The code below works, and throws an error as expected.

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.plugin(schema => {
  schema.pre('findOneAndUpdate', setRunValidators);
  schema.pre('updateMany', setRunValidators);
  schema.pre('updateOne', setRunValidators);
  schema.pre('update', setRunValidators);
});

function setRunValidators () {
  this.setOptions({ runValidators: true });
}


mongoose.connect('mongodb://localhost:27017/test', { family: 4, useNewUrlParser: true });


const userSchema = new Schema({
  name: { type: String, required: true },
  age: { type: Number, min: 13, max: 90 }
});


const User = mongoose.model('User', userSchema);

const hafez = new User({ name: 'Hafez', age: 24 });

async function run () {
  await User.remove();
  await hafez.save();

  await User.updateOne({}, { name: null });
}

run().catch(console.error);
```

However, running this doesn't work throw an error. I can't seem to find a reference to `mongoose.set('runValidators', true);` anywhere in the docs.

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.set('runValidators', true);


mongoose.connect('mongodb://localhost:27017/test', { family: 4, useNewUrlParser: true });


const userSchema = new Schema({
  name: { type: String, required: true },
  age: { type: Number, min: 13, max: 90 }
});


const User = mongoose.model('User', userSchema);

const hafez = new User({ name: 'Hafez', age: 24 });

async function run () {
  await User.remove();
  await hafez.save();

  await User.updateOne({}, { name: null });
}

run().catch(console.error);
```

**Comment by AbdelrahmanHafez** [comment]
Also would be great to have a global option to `setDefaultsOnInsert`.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP

**Comment by tcstory** [comment]
who can tell me where are the caveats of updating validators?  I can't find it.

**Comment by tcstory** [comment]
@lineus thx

**Comment by lqzhgood** [comment]
> That's a good idea. Right now the way to do it would be with a global plugin:
> 
> mongoose.plugin(schema => {
>   schema.pre('findOneAndUpdate', setRunValidators);
>   schema.pre('updateMany', setRunValidators);
>   schema.pre('updateOne', setRunValidators);
>   schema.pre('update', setRunValidators);
> });
> 
> function setRunValidators() {
>   this.setOptions({ runValidators: true });
> }
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> Would be neat to have this as a one-liner though.

If I set it like this，How can I cancel a special update?
`Tool.findOneAndUpdate({ _id }, { $set: body }, { runValidators: false })`
is not work,  the `schema.pre`  is after Model `findOneAndUpdate` ~ Will override my customization options

**Comment by vkarpov15** [comment]
@lqzhgood check https://mongoosejs.com/docs/api.html#query_Query-getOptions

```javascript
  function setRunValidators() {
    if ('runValidators' in this.getOptions()) {
      return;
    }
    this.setOptions({ runValidators: true });
  }
```

**Comment by yeknava** [comment]
@vkarpov15 i get "this.setOptions is not a function" error.
it works on local machine btw. but not in production.

**Comment by AbdelrahmanHafez** [comment]
@yeknava Do you happen to be using an arrow function instead of the code snippet above? Maybe share some code?

**Comment by yeknava** [comment]
sure @AbdelrahmanHafez , here is my code:
```js
function setRunValidators() {
        this.setOptions({ runValidators: true, new: true });
}
mongoose.plugin(schema => {
    schema.pre('findOneAndUpdate', setRunValidators);
    schema.pre('updateMany', setRunValidators);
    schema.pre('updateOne', setRunValidators);
    schema.pre('update', setRunValidators);
});
```
