### ISSUE TITLE
Does mongoose ready for mongodb 4 ?

### ISSUE THREAD

**Issue by lakshmipriyamukundan** [Automattic/mongoose#6579]
Can I use mongoose for mongodb 4 ?

**Comment by vkarpov15** [comment]
We're working on it, will have an update for you shortly

**Comment by nasa8x** [comment]
@vkarpov15 Plz, support mongodb transactions for this version. 
Thank you and appreciate the efforts of your team.

**Comment by alexk111** [comment]
Are there any breaking changes in MongoDB 4 for the current version of Mongoose? Is it safe to use? Or better to either downgrade to mongo 3 or wait until 5.2.0 release?

**Comment by lineus** [comment]
@alexk111 

I'm running a mongodb 4 replica set locally ( thanks to @vkarpov15's awesome [run-rs tool](https://www.npmjs.com/package/run-rs) ) all tests **but one** on the current master branch (5.1.8-pre) pass on mongdb 4. 

As long as you're not using the `$isolated` operator, it should *work*.

**Comment by alexk111** [comment]
@lineus Thank you! 👍
