### ISSUE TITLE
Option to run mongodb on memory using mongoose

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#6582]
It would be awesome if mongoose had an option that makes it possible to run mongoose in memory, a use case for that would be running tests and not really caring about persistence, we just want to run the tests faster.

There are already a couple of libraries out there that help with this, such as [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server) and [mockgoose](https://github.com/mockgoose/mockgoose), but they require having to await for the queryString, and then connecting, which could add unnecessary complexity to the db connection initialization process for those who want to just run their tests.

An option out of the box would look like:

```js
const mongoose = require('mongoose');

mongoose.connect(connectionString, { inMemory: true })
```

I know this is easier said than done, but I believe it's worth considering.

**Comment by vkarpov15** [comment]
To be honest, I don't think we're going to implement something like this anytime in the foreseeable future. To support this we'd have to support the entire MongoDB API, so we'd have to implement and maintain our own MongoDB-compatible database. There's the potential of integrating with [nedb](https://www.npmjs.com/package/nedb) but that would distract us from staying focused on making our MongoDB integration as seamless as possible across the whole range of supported MongoDB versions.

I would imagine the [MongoDB in-memory storage engine](https://docs.mongodb.com/manual/core/inmemory/) would help speed up your tests, and there's plenty of other tips and tricks for making MongoDB tests faster, like avoiding `dropDatabase()` if you're using the WiredTiger storage engine. Perhaps these could help speed up your test suite?
