### ISSUE TITLE
Array of subdocuments not working inside a discriminator.

### ISSUE THREAD

**Issue by ggJSC** [Automattic/mongoose#6586]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`TypeError: Undefined type 'model' at array 'logEntries' at Function.Schema.interpretAsType`

**If the current behavior is a bug, please provide the steps to reproduce.**

Tried loading this Schema into application but getting a TypeError even though array of subdocuments is valid as per the documentation. 

```
const SimSection = require('./SimSection');
const LogEntrySchema = require('./LogEntry');

const LogEntrySectionSchema = SimSection.discriminator(
  'LogEntrySection',
  new Schema({
    simStartTime: {
      type: Date,
      default: null
    },
    realStartTime: {
      type: Date,
      default: null
    },
    logEntries: [LogEntrySchema]
  })
);
```

**LogEntry.js**

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const LogEntrySchema = new Schema({
  timestamp: {
    type: Date,
    default: Date.now
  },
  html: {
    type: String,
    default: ''
  },
  delta: {
    type: Object,
    default: function() {
      return {
        'ops': [
          { 'insert': '' }
        ]
      };
    }
  },
  connections: [{
    updateId: Schema.Types.ObjectId,
    updateParentId: Schema.Types.ObjectId,
    parentType: {
      type: String,
      enum: ['action-item', 'lesson-learned', 'failure']
    }
  }]
});

module.exports = mongoose.model('LogEntry', LogEntrySchema);
```

**What is the expected behavior?**

logEntries is an array of subdocuments of model LogEntry

**Please mention your node.js, mongoose and MongoDB version.**

**node -v**

`v8.9.3`

**mongoose**

`"mongoose": "^5.1.4"`

**Comment by vkarpov15** [comment]
`const LogEntrySchema = require('./LogEntry');` <-- in this statement, `LogEntrySchema` is a model, **not** a schema. Change `LogEntry.js` to:

```javascript
module.exports = LogEntrySchema;
```

**Comment by ggJSC** [comment]
So am I mistaken for using `mongoose.model` in the `module.exports` as opposed to simply including the schema?

**Comment by vkarpov15** [comment]
Depends on whether you're looking to export a [Schema](http://mongoosejs.com/docs/guide.html) or a [Model](http://mongoosejs.com/docs/models.html). They're two separate concepts. If you're just looking to use `LogEntry` as an embedded schema, you don't need to create a model.
