### ISSUE TITLE
findOneAndRemove omit _id on delete

### ISSUE THREAD

**Issue by CruiseMan** [Automattic/mongoose#6589]
Native mongodb method [findOneAndDelete](https://docs.mongodb.com/v3.2/reference/method/db.collection.findOneAndDelete/) has an option to omit on return `_id` by specifying `projection: {_id: 0}` in options. How i can do that with  `findOneAndRemove` ?

**Comment by lineus** [comment]
@CruiseMan you can pass the desired projection option into mongoose's `Model.findOneAndDelete()` or `Model.findOneAndRemove()` Example Below:

### 6589.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  age: Number
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'abc',
  age: 12
});

const test2 = new Test({
  name: 'def',
  age: 34
});

async function run() {
  await conn.dropDatabase();
  await Test.create([test, test2]);
  let cond1 = { _id: test._id };
  let cond2 = { _id: test2._id };
  let opts = { projection: { _id: 0 } };
  let doc = await Test.findOneAndRemove(cond1, opts);
  let doc2 = await Test.findOneAndDelete(cond2, opts);
  let count = await Test.count();
  console.log(`test: ${doc} removed.`);
  console.log(`test2: ${doc2} removed.`);
  console.log(`Collection has ${count} docs remaining.`);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6589.js
test: { name: 'abc', age: 12, __v: 0 } removed.
test2: { name: 'def', age: 34, __v: 0 } removed.
Collection has 0 docs remaining.
issues:
```

Leaving this open to track adding the projection option to the api docs.

**Comment by CruiseMan** [comment]
Thank you for example. If i understand correctly, `findOneAndRemove` missing `projection` option in docs ?.
i'm getting TS error using `@types/mongoose": "^4.7.24` and `"mongoose": "^5.0.0"`

`[ts] Type '{ projection: { _id: number; }; }' has no properties in common with type '{ sort?: Object; maxTimeMS?: number; select?: Object; }'.`

**Comment by lineus** [comment]
@CruiseMan Yes, it works as expected. You might consider opening a PR against the type definitions for mongoose or raising an issue at [this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose) for the typescript piece.
