### ISSUE TITLE
MongoError: Authentication failed

### ISSUE THREAD

**Issue by Sandrine75** [Automattic/mongoose#6591]
Hi,
I have this message 👍 (node:5524) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Authentication failed.
(node:5524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
What does it mean ?
How can i solve that ?
Many thanks
Sandrine

**Comment by lineus** [comment]
> What does it mean ?

It could potentially be incorrect credentials, or your password contains special characters but isn't encoded. You could *try using `encodeURIComponent()`* if your password contains [any special characters](https://tools.ietf.org/html/rfc3986#section-2.2)

If this information doesn't help, please share some more details about your setup, including  whether the server you are connecting to is locally run or a cloud based servce, does it have auth enabled? Include the connection string/options you are connecting with **after redacting sensitive data like actual passwords**

**Comment by Sandrine75** [comment]
Thanks, i am going to try and come back if not running.
Best regards
Sandrine

**Comment by lineus** [comment]
@Sandrine75 I'm assuming you got this working. I'll close this for now, but if you need me to reopen it, just let me know.
