### ISSUE TITLE
schema.add does not apply alias

### ISSUE THREAD

**Issue by LucGranato** [Automattic/mongoose#6593]
When calling schema.add at any plugin, the alias is not applied to the schema.

~~~javascript
schema.add({
    my_field: {
        type: String,
        alias: 'customfieldname'
    }
})
~~~

At `schema.js` it seems that the function `aliasFields` is called only in the `constructor`.

Node.js `8.11.1`
Mongoose `5.1.5`

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP

**Comment by LucGranato** [comment]
Only for clarification this issue is related to an older issue #5855 
Thanks @vkarpov15 !
