### ISSUE TITLE
When my program runs longer and longer，cursor.next is slower and slower ？

### ISSUE THREAD

**Issue by liuqipeng417** [Automattic/mongoose#6594]
## Env

- Node: 8.11.2
- Mongoose: 4.13.14
- MongoDB: 3.6.2

## Problem
Find the following through the observation log：

- When the program is just starting, `cursor.next()` gets the data very fast(handle 2000-3000 doc per second), but as the program runs longer and longer, Subsequent `cursor.next()` becomes very slow(handle 200 doc per second), and from the `top` instruction, CPU is very high, even reaching 100%.
- Restart program recovery speed 
- The amount of data per query is about hundreds of thousands to tens of millions.
- I also use `cursor({ batchSize })`, but it doesn't work.
- Program memory is normal.
- MongoDB connection amount is normal.
- MongoDB memory and cpu is normal

## Code Example

```
default: {
	url: 'mongodb://127.0.0.1:27016,127.0.0.1:27015/test'
	options: {
	  useMongoClient: true,
	  poolSize: 20,
	  autoIndex: true,
	  replicaSet: 'testRepl',
	  readPreference: 'secondaryPreferred',
	  reconnectTries: 180,
	  reconnectInterval: 10000
	}
}
```

```
const logger = console;
const cursor = this.ctx.model.xxx
	.find({
	  create_time: {
		$gte: new Date(startTime),
		$lt: new Date(endTime)
	  }
	})
	.lean()
	.cursor({
	  batchSize: 5000
	});

let countNum = 0;
let info;
while (info = await cursor.next()) {
	// do something, it doesnt make long time

	countNum++;
	logger.info(countNum);
}
```

## Guess

- poolSize too small
- cursor stream highwatermark too small

**Comment by vkarpov15** [comment]
Do you know if the CPU usage comes from your program or from the mongodb server?

**Comment by liuqipeng417** [comment]
@vkarpov15 My program logic is not complicated, and should not make CPU 100%.

**Comment by liuqipeng417** [comment]
PS:My mongodb stores hundreds of millions of data

**Comment by tracycollins** [comment]
I'm seeing something very similar. Code below will start off quickly and then slow to a crawl, eventually crashing with error.  I'm not sure if I'm understanding and using cursors correctly, so it may be pilot error on my part, but I've not been able to figure this out in the past few days.

I only have about 20K docs in the collection.  I'm fetching the documents in batches. I've tried different batch sizes and limit/skip sizes, nothing seems to make a difference.

I'm running node 10.6.0, mongoose 5.2.2, mongoDb 3.1.1 on Debian stretch.

(parameter values don't seem to be important)
```
const queryParam = {
   "$or": [ 
        { "category": { $nin: [ false, null ] } } , 
        { "categoryAuto": { $nin: [ false, null ] } }
   ] 
};
const projectionParam = "category categoryAuto";
const sortParam = {"nodeId": 1};
const skipParam = currentSkipValue;
const limitParam = 100;
const batchSizeParam = 100;

const cursor = MyModel.find(queryParam)
  .select(projectionParam)
  .sort(sortParam)
  .skip(skipParam)
  .limit(limitParam)
  .cursor({ batchSize: batchSizeParam });

cursor.eachAsync(function(doc){
 // process doc
})
.then(function(){
 // all docs processed
})
.catch(function(err){
});



```
Crash error:

> TypeError: callback is not a function
>  at handleCallback (/myproject/node_modules/mongodb/lib/utils.js:128:55)
>  at result.toArray (/myproject/node_modules/mongodb/lib/operations/collection_ops.js:236:16)
>  at err (/myproject/node_modules/mongodb/lib/utils.js:415:14)
>  at executeCallback (/myproject/node_modules/mongodb/lib/utils.js:404:25)
>  at handleCallback (/myproject/node_modules/mongodb/lib/utils.js:128:55)
>  at cursor._endSession.cursor._endSession (/myproject/node_modules/mongodb/lib/operations/cursor_ops.js:214:38)
>  at AggregationCursor.Cursor._endSession (/myproject/node_modules/mongodb-core/lib/cursor.js:193:5)
>  at AggregationCursor.Cursor._endSession (/myproject/node_modules/mongodb/lib/cursor.js:226:59)
>  at cursor._next (/myproject/node_modules/mongodb/lib/operations/cursor_ops.js:214:20)
>  at Store.addObjectAndMethod (/myproject/node_modules/mongodb/lib/topologies/topology_base.js:77:12)
>  at nextFunction (/myproject/node_modules/mongodb-core/lib/cursor.js:606:39)
>  at AggregationCursor.Cursor.next (/myproject/node_modules/mongodb-core/lib/cursor.js:824:3)
>  at AggregationCursor.Cursor._next (/myproject/node_modules/mongodb/lib/cursor.js:211:36)
>  at fetchDocs (/myproject/node_modules/mongodb/lib/operations/cursor_ops.js:211:12)
>  at toArray (/myproject/node_modules/mongodb/lib/operations/cursor_ops.js:241:3)
>  at executeOperation (/myproject/node_modules/mongodb/lib/utils.js:420:24)
>  at AggregationCursor.Cursor.toArray (/myproject/node_modules/mongodb/lib/cursor.js:818:10)
>  at coll.aggregate (/myproject/node_modules/mongodb/lib/operations/collection_ops.js:235:12)
>  at handleCallback (/myproject/node_modules/mongodb/lib/utils.js:128:55)
>  at Collection.aggregate (/myproject/node_modules/mongodb/lib/collection.js:1825:10)
>  at countDocuments (/myproject/node_modules/mongodb/lib/operations/collection_ops.js:233:8)
>  at executeOperation (/myproject/node_modules/mongodb/lib/utils.js:420:24)

**Comment by vkarpov15** [comment]
@tracycollins are you executing this code as a standalone script or is it part of an API endpoint that you're hitting? If you're incrementing `skip` repeatedly that might explain why your code is slow.

**Comment by vkarpov15** [comment]
This issue's gone stale, I'm gonna close this. Feel free to open if new information surfaces.
