### ISSUE TITLE
CastError: Cast to string failed for value  "{ subscibe: { secretToken: '1111' } }" at path "secretToken" for model "subscribe" at new CastError 

### ISSUE THREAD

**Issue by techapoorva** [Automattic/mongoose#6595]
I am having this error when I am using findOne with mongoose model. its not able to find the document in the db.

post(async (req, res, next) => {
    try {
      const secretToken = req.body;
      /**Find account with matching secret token */
      const subscribe = await Subscribe.findOne({
        'secretToken': secretToken
      });
      console.log(subscribe);
      return false;

and my mongoose schama look like this 
const someSchema = new Schema({
          name: String,
          email: String,
          secretToken: String,
});

const someVar = mongoose.model('exportModelName', someSchema);
module.exports = someVar;

plus there is no problems in exporting the model

I am using "mongoose": "^5.1.3",
                  nodejs : v8.11.2
                  mongodb: version v3.6.5
Thanks ,

**Comment by techapoorva** [comment]
new update const { subscribe: { secretToken } } = req.body; so which actually assigns the "property" you want. You are trying to assign the "whole object" 
So i changed it now I am getting 
CastError: Cast to string failed for value "{ secretToken: '9891' }" at path "secretToken" for model "subscribe" at new CastError

**Comment by lineus** [comment]
@techapoorva looks like you resolved this issue on stackOverflow [here](https://stackoverflow.com/questions/50868833/casterror-cast-to-string-failed-for-value-subscibe-secrettoken-1111) Let me know if I'm mistaken and you need me to reopen this.
