### ISSUE TITLE
Schema for Polygon confusing

### ISSUE THREAD

**Issue by ntk860** [Automattic/mongoose#6597]
I suspect that it is a bug that has to be fixed. 
I am using mongoose 5.0.13 and mongodb version 3.4.7

My schema has a geospatial field that looks like this. 
```
....
geo: {
   type: { type: String, enum: "Polygon", default: "Polygon" },
   coordinates: { type: Array }
},
.....

Schema.index({'geo.coordinates': '2dsphere'});
```

it should represent a polygon as it shows

I am inserting the data as following 

```
geo : {
   coordinates : [ [0, 1], [1, 2], [2, 3], [3,4] ]
}
```

of course I am inserting real coordinates [long, lat] extracted from a google map but the error I am getting is 

'Can\'t extract geo keys: Point must only contain numeric elements',

**Comment by lineus** [comment]
@ntk860 I've never worked with geoSpatial data before, but from looking at the mongodb docs on [polygons](https://docs.mongodb.com/manual/reference/geojson/index.html#polygon) and [2dsphere indexes](https://docs.mongodb.com/manual/core/2dsphere/index.html) I believe the Index that you are creating should be on the `geo` field, not the `geo.coordinates` field, and the data you put in the `geo.coordinates` field should be an **array** of **arrays** of **arrays** of **numbers**. 

Here is an example that MongoDB doesn't error on:

### 6597.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  geo: {
    type: { type: String },
    coordinates: Array
  }
});

schema.index({ 'geo': '2dsphere' });

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'fourCorners',
  geo: {
    type: 'Polygon',
    coordinates: [[ [0,0], [0,4], [4,4], [4,0], [0,0] ]] // note the extra [] here
  }
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne({});
  console.log(found);
  return conn.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./6597.js
{ geo: { coordinates: [ [Array] ], type: 'Polygon' },
  _id: 5b24fb30ee463c17a9ebb0f3,
  name: 'fourCorners',
  __v: 0 }
issues:
```
