### ISSUE TITLE
INFO: new mongoose.Model doesn't work

### ISSUE THREAD

**Issue by barraponto** [Automattic/mongoose#6598]
The documentation guide recommends using `new mongoose.Schema` to create a schema. When creating models, I thought I should use `new mongoose.model` but that is *not* the case. Why is that? Can someone clarify it for me?

**Comment by lineus** [comment]
@barraponto `mongoose.Schema()` is a constructor, `mongoose.model()` itself is not ( it returns one though ). `mongoose.model()` can be used to compile a schema into a Model or to retrieve a Model that has already been created.

For example:

### 6598.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

mongoose.model('test', schema); // create a Model

const Test = mongoose.model('test'); // retreive a Model

const test = new Test({ name: 'Mars' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne({});
  console.log(doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6598.js
{ _id: 5b24e32829b7ec0eb5ca62a1, name: 'Mars', __v: 0 }
issues:
```

**Comment by vkarpov15** [comment]
In general, a schema and a model are two separate concepts. A schema is essentially a configuration object for a model, and model = schema + connection.
