### ISSUE TITLE
geoIntersects not working in any way shape or form

### ISSUE THREAD

**Issue by ntk860** [Automattic/mongoose#6599]
I have a field structured this way 

`location: [[Array]]`

and I am inserting the data as such [ [0, 1], [1, 2], [2, 3], [3, 4] ]

running the query 

`{location: { $geoIntersects: { $geometry: { type : "Point", coordinates:[long, lat] } } } }`

and its not returning any thing.

I want to search a point on a polygon.

**Comment by lineus** [comment]
@ntk860 your query looks fine, and works as expected. Here is an example:

### 6599.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  geo: {
    type: { type: String },
    coordinates: Array
  }
});

schema.index({ 'geo': '2dsphere' });

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'fourCorners',
  geo: {
    type: 'Polygon',
    coordinates: [[ [0,0], [0,4], [4,4], [4,0], [0,0] ]]
  }
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  // inside the polygon
  let one = { 
    geo: { 
      $geoIntersects: { 
        $geometry: { 
          type: 'Point', 
          coordinates: [1, 1] 
        } 
      } 
    } 
  };
  // outside the polygon
  let two = {
    geo: {
      $geoIntersects: {
        $geometry: {
          type: 'Point',
          coordinates: [5, 5]
        }
      }
    }
  };
  let intersects = await Test.findOne(one);
  console.log(intersects.name);
  let doesnt = await Test.findOne(two);
  console.log(doesnt);
  return conn.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./6599.js
fourCorners
null
issues:
```

As pointed out in #6597 your coordinates path should be [[[Number]]] ( an **array** of **arrays** of **arrays** of Numbers ).

If you were already able to successfully create the 2dsphere index and insert docs, is it possible that the point you are querying for is outside the polygons in your collection? If you believe this isn't the case please add a complete example here (like mine above) that shows the schema, model creation, data insertion, and query you believe should match a document. This will make it easier to assist.

**Comment by ntk860** [comment]
Thank you so much! For two days I was trying to figure this out! Thank you!

**Comment by lineus** [comment]
anytime!

**Comment by vkarpov15** [comment]
Good catch @lineus . Opened up an issue for officially supported geojson types.

If you're struggling with geojson and mongodb, check out my [article on geo operators in MongoDB](http://thecodebarbarian.com/80-20-guide-to-mongodb-geospatial-queries).
