### ISSUE TITLE
Use tc39 Decorators (candidate proposal) to define schemas

### ISSUE THREAD

**Issue by pwhissell** [Automattic/mongoose#6601]
This is a feature request.

Before I start, I want to make sure I have the right definition of "Model" and "Schema". To me a "model" is an instance of a class of object that has certain attributes. Ex: a chair has for Legs and is blue:

### Model
```
class Chair {
  constructor(legs, color) {
    this.legs = legs;
    this.color = color;
  }
}
let legs = ...;
let kitchenChair = new Chair(legs, 'blue')
```
_kitchenChair would be my model and would be represented as a json object in a mongodb_

Inheritance makes it possible to generalize types of objects that have common attributes by grouping them together. Ex. If we pretend every furniture in a kitchen has legs for the sake of the example we could have something like

```
class Furniture {
  constructor(legs, color) {
    this.legs = legs;
    this.color = color;
  }
}
class Chair extends Furniture {
  constructor(chairback, legs, color) {
    super(legs, color);
    this.chairback = chairback;
  }
}
let chairback = ...;
let legs = ...;
let kitchenChair = new Chair(chairback, legs, 'blue')
```
in a mongodb the kitchenchair would be a json object for which the class hierarchy could be represented using many methods, one way would be using a discriminator like so:
```
{
    typeDiscriminator: 'chair'
    chairback: {...},
    legs: [...],
    color: 'blue'
}
```

### Schema

If I understood correctly, schemas are used to describe validations that must be made on objects before they are persisted. In other words, they decorate the models by restraining their attribute values to a subset of possibilities. That being said, it would really be awesome if mongoose were to evolve with ecmascript, and provide a set of implemented decorators as specified by [TC39's decorator proposal](https://github.com/tc39/proposal-decorators) which is [currently](https://github.com/tc39/proposals) in phase 2 (candidate). These decorators would be used to define model validations.

For example schemas would be defined by decorators annotated with the \@  perhaps over getters like so:
```
class Furniture {
  constructor(legs, color) {
    this.legs = legs;
    this.color = color;
  }
  @Type(Leg[]) //<---- decorator implemented by mongoose
  @Size(4)
  get legs() {return this.legs;}
}

class Chair extends Furniture {
  constructor(chairback, legs, color) {
    super(legs, color);
    this.chairback = chairback;
  }
  @Type(String)
  @NotNull
  get color() { return this.color;}
}
```

In the background mongoose would generate the [mongodb syntaxe for model validation](https://docs.mongodb.com/manual/core/schema-validation/) and abstract the existance of mongodb schemas.

**Comment by pwhissell** [comment]
1. Thanks for the distinction between model and document
2. That Shema.loadClass() function is cool since I can use my existing [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) models to generate my Shema yet I wish the Schema object could be transparent to a mongoose user and so I'll be waiting for the tc39 Decorators and your suggested plugin before using mongoose.

**Comment by TrejGun** [comment]
sounds good but, decorators are broken since babel 7.0.0-beta.36

**Comment by vkarpov15** [comment]
@pwhissell what format are your models defined in?

**Comment by pwhissell** [comment]
javascript classes

**Comment by pwhissell** [comment]
@vkarpov15 
here is an example I re-wrote in typescript  format just so the values my attributes can take are a little clearer

```
class Form {

  _id: string;
  formElements: FormElement[][] = [];
  name: TranslatedString;

  constructor() { }

};
```

then I had to create validation schemas apart from my models like so:

```
FormElementSchema = require('./form-element/form-element.model').FormElementSchema;
FormElementTypes = require('./form-element/form-element-types.model').FormElementTypes;
TranslatedStringSchema = require('../shared/translated-string.model').TranslatedStringSchema;

const FormSchema = new mongoose.Schema({
  "name": {
    "type": TranslatedStringSchema,
    "required": true
  },
  "formElements": {
    "type": [[FormElementSchema]],
    "required": true
  }
}, {
    strict: true,
    useNestedStrict: true
  }
);

FormElementTypes.forEach(elementType => {
  FormSchema.path('formElements').caster.discriminator(elementType.discriminator, elementType.schema);
});

module.exports.FormSchema = FormSchema;
module.exports.Form = mongoose.model('Form', FormSchema);
```

what I would have wanted would look somthing like:

```
@Collection
class Form {
  @Type(TranslatedString)
  _id

  @NotNull
  @Type(FormElement[][])
  formElements = [];

  @NotNull
  name;

  constructor() { }

};
```

where the decorators would generate a [JSON schema](https://tools.ietf.org/html/draft-zyp-json-schema-04) for me without me ever having to tamper with it

**Comment by vkarpov15** [comment]
Worth looking into, thanks for the suggestion
