### ISSUE TITLE
geojson docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6607]

**Comment by gkatsanos** [comment]
@vkarpov15 hey Valeri, thank you for updating the docs, but I don't see the indexes declared there, which is a topic that after going around SO and the issue tracker seems to be a confusing one. It would super great if you could add the index creation (for example '2dsphere') as when browsing the documentation we see a variety of ways to create them fro geoJSON.  https://mongoosejs.com/docs/geojson.html https://mongoosejs.com/docs/api.html#schematype_SchemaType-index

**Comment by vkarpov15** [comment]
Thanks for the suggestion @gkatsanos . I opened up a separate issue ☝️ to track that.
