### ISSUE TITLE
Projection not working with positional parameter $

### ISSUE THREAD

**Issue by pramodrwt** [Automattic/mongoose#6609]

**Comment by lineus** [comment]
@pramodrwt are you referring to [Query.prototype.select()](http://mongoosejs.com/docs/api.html#query_Query-select)? The select method on Queries only accepts inclusive or exclusive strings/objects of field names to return as described in the documentation above. How are you expecting `$` to behave with select? Please share some information describing what you are trying to do.

**Comment by pramodrwt** [comment]
I am try to apply projection in this case: 

`Student.findOne({
	_id: studentId,
        'courses.courseId': courseId},{
        'courses.$' : 1
	});`

I need selected fields

**Comment by lineus** [comment]
@pramodrwt My bad, I forgot that you could project just the first matched element in an array with the `$` positional operator in projections. I tried the following example and it works as expected:

### 6609.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  arr: [{ x: String, y: Number }]
});

const Test = mongoose.model('test', schema);

const test = new Test({
  arr: [
    { x: 'Two', y: 1},
    { x: 'Two', y: 2 },
    { x: 'Two', y: 3 },
  ]
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne({ 'arr.x': 'Two' }, { 'arr.$': 1 });
  console.log(doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6609.js
{ _id: 5b30f704632cb11d98309bdc,
  arr: [ { _id: 5b30f704632cb11d98309bdf, x: 'Two', y: 1 } ] }
issues:
```

Can you create a complete example that shows your schema, model creation, doc insertion, and query that demonstrates the behavior like mine above?

**Comment by pramodrwt** [comment]
@lineus  I am taking reference of your example 
My data array like this 
 `arr: [
    { x: 'Two', y: 1, z: 2, a:1},
    { x: 'Two', y: 2, z: 2, a:2},
    { x: 'Two', y: 3, z: 2, a:3},
  ]`

so with { 'arr.$': 1 } It will return me first object which is something like this.. 
`{ x: 'Two', y: 1, z: 2, a:1}`
 
but now i need projection here i need output like..
`{ x: 'Two', y: 1}`

**Comment by lineus** [comment]
@pramodrwt I believe this is a limitation of the positional operator in mongodb projections. You can have the positional operator return only the first match, **or** you can return a specific set of array fields, but you can't do both at the same time. [At least, thats what I got from docs here](https://docs.mongodb.com/manual/reference/operator/projection/positional/#projection). 

You could use `Model.aggregate()` to construct a pipeline that does this:

### 6609.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  arr: [{ x: String, y: Number, z: Number, a: Number }]
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'X',
  arr: [
    { x: 'Two', y: 1, z: 1, a: 2 },
    { x: 'Two', y: 2, z: 2, a: 3 },
    { x: 'Two', y: 3, z: 3, a: 4 },
  ]
});

async function run() {
  await conn.dropDatabase();
  await test.save();
  let docs = await Test.aggregate([
    {
      $match: {
        _id: test._id
      }
    },
    {
      $unwind: '$arr'
    },
    {
      $match: {
        $and: [
          { 'arr.x': 'Two' },
          { 'arr.y': 1}
        ]
      }
    },
    {
      $project: {
        _id: 0,
        x: '$arr.x',
        y: '$arr.y'
      }
    }
  ]);
  docs.forEach((d) => console.log(d));
  return conn.close();
}

run();
```
### Output:
```
issues: ./6609.js
{ x: 'Two', y: 1 }
issues:
```

**Or alternatively, you could just return the entire matching element **or** the entire array and do what you need to in your node process.**

**Comment by pramodrwt** [comment]
@lineus  Since my data contain nested array so i will handle this with application level projection
