### ISSUE TITLE
If post('save') throws an error, it is expected to doc.save() catch that error?

### ISSUE THREAD

**Issue by LucGranato** [Automattic/mongoose#6615]
I always believed that `schema.post('save', function ({ ... }))` runs after the saved doc is resolved at `doc.save().then(savedDoc => { ... })`.

But recently I realized that if I return a *rejected promise* at post save, my save is rejected too, even with my document having been saved.

Its really expected this behavior?

~~~javascript
const mongoose = require('mongoose'),
    Promise = require('bluebird'),
    Schema = mongoose.Schema;

mongoose.Promise = Promise;

mongoose.connect("mongodb://localhost:27017/test");

const NoteSchema = new Schema({
    body: String
});

NoteSchema.pre('save', function (next) {
    return next();
});

NoteSchema.post('save', function () {
    return Promise.reject(new Error('some error'));
});

const Note = mongoose.model('Note', NoteSchema);

var myNote = new Note({
    body: 'Quick note'
});

myNote.save()
.then(myDoc => {
    console.log('saved');
})
.catch(error => {
    console.log('error');
});
~~~

Thanks!

**Comment by LucGranato** [comment]
http://thecodebarbarian.com/whats-new-in-mongoose-5-improved-post-hooks

**Comment by vkarpov15** [comment]
@LucGranato we changed this behavior in mongoose 5 as described in the blog post you linked to. You can work around this by not returning the promise from your post save hook.
