### ISSUE TITLE
populate not running getter on localField

### ISSUE THREAD

**Issue by trungtin** [Automattic/mongoose#6618]
**Do you want to request a *feature* or report a *bug*?**
maybe *bug*

**What is the current behavior?**
I'm migrating from parse-server to mongoose. Parser server save pointer in this shape `Model$_id`.  So in schema definition I have set a getter to transform `Model$xxxxx` => `xxxxx`.
But when using this field to populate, the getter does not run (so mongoose look for _id by `Model$xxxxx`, not `xxxxx`  as expected)

I have tried to add a new virtual field as opose to using getter and use new virtual field to populate, it also not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
mongoose@5.1.6

**Comment by trungtin** [comment]
User table

_id | refferer
--- | ---
xxx | *undefined*
yyy | _User$xxx

```
const userSchema = new Schema({
  _id: String,
  refferer: {
    type: String,
    get: this.refferer && this.referrer.slice(6)
  }
})

userSchema.virtual('referrerUser', {
  ref: '_User',
  localField: 'refferer', <= it search _User table for for `_User$xxx` not `xxx`
  foreignField: '_id',
  justOne: false
});
```
work around:
```
userSchema.virtual('referrerUser', {
  ref: '_User',
  localField: (doc) => {
     if (doc.refferer) {
       doc.refferer_temp = doc.refferer.slice(6)
     }
     return 'refferer_temp'
   },
  foreignField: '_id',
  justOne: false
});
```

**Comment by lineus** [comment]
@trungtin I think I was able to duplicate this with the following code:

### 6618.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/gh-6618');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const userSchema = new Schema({
  name: String
});

const schema = new Schema({
  referrer: {
    type: String,
    get: function(val) {
      console.log(val);
      return val.slice(6);
    }
  }
});

schema.virtual('referrerUser', {
  ref: 'user',
  localField: 'referrer',
  foreignField: '_id',
  justOne: false
});

const User = mongoose.model('user', userSchema);
const Test = mongoose.model('test', schema);

const user = new User({ name: 'billy' });
const test = new Test({ referrer: 'Model$' + user.id });

async function run() {
  await conn.dropDatabase();
  await user.save();
  await test.save();
  // let pop = await Test.findOne().populate('referrerUser');
  // console.log(pop);
  return conn.close();
}

run().catch((e) => { console.error(e.message); return conn.close();});
```
### Output:
```
issues: ./6618.js
Cast to ObjectId failed for value "Model$5b358cd8dee63f0ab27fa77a" at path "_id" for model "user"
issues:
```

Is this the behavior you are describing?

**Comment by vkarpov15** [comment]
Re: #6844, this change was unintentionally backwards breaking for some people, so we're going to have to [put this behavior behind an option](https://github.com/Automattic/mongoose/issues/6844#issuecomment-414116620). You will need to set the `getters` option to true to run getters on your populate's `localField` in Mongoose 5.2.10:

```javascript
schema.virtual('foo', {
  ref: 'Bar',
  localField: 'baz',
  foreignField: '_id',
  getters: true // Opt in to calling getters on 'baz'
});
```

```javascript
await BlogPost.findOne().populate({ path: 'author', options: { getters: true } });
```

**Comment by trungtin** [comment]
totally agree with this. Thank you
