### ISSUE TITLE
enum error message missing string substitution

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6621]
The enum error message seems like it wants to have variable substitution, but it isn't happening.
**I'll see if I can sort this out in the AM**
### 6621.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: {
    type: String,
    enum: ['Billy', 'Bobby', 'Branford', 'Banksy']
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'Basquiat'
});

async function run () {
  await conn.dropDatabase();
  await test.save()
    .catch((err) => {
      console.error(err.errors.name.properties.message);
      return conn.close();
    });
}

run();
```
### Output:
```
issues: ./6621.js
`{VALUE}` is not a valid enum value for path `{PATH}`.
issues:
```

**Note to Self:** it looks like if I just `console.error(err);` it's there, if I try to access the full property path it doesn't work.
**Please mention your node.js, mongoose and MongoDB version.**
mongoose 5.1.6, node 8.11.1, mongodb 3.6.2

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix asap.

**Comment by vkarpov15** [comment]
`console.error(err.errors['name'].message);` works. Will add the correct message to properties as well
