### ISSUE TITLE
save() function called once but stores twice

### ISSUE THREAD

**Issue by Eksapsy** [Automattic/mongoose#6626]
- [ ] feature
- [x] bug

**What is the current behavior?**
Saves twice the document in the database when used in pure code

**If the current behavior is a bug, please provide the steps to reproduce.**
Firstly, I am using [mlab](http://mlab.com).
When used like in the code below, it saves twice. Although, the `save()` seems to be called only once. I tested that by placing a `then()` after save printing the **document**, which **document** was normally saved in the database along with another one with same data but with different `_id`.
```javascript
const AnimalSchema = mongoose.Schema({
  name: {
    type: String,
    required: false
  },
  type: {
    type: String,
    required: true
  }
});
const Animal = mongoose.model('Animal', AnimalSchema);

new Animal({
    name: 'idiots',
    type: 'catdog'
  })
  .save();
```

When used in a `POST` request, like displayed below, it stores the documents in the database normally.
```javascript
// HTTP SERVER
const app = express();

// URL-ENCODED to `req.body`
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));

// POST REQUEST
app.post(
  '/save',
  async (req, res) => {
    const {name, type} = req.body;
    res.json( await saveAnimal(name,type)).status(200);
  }
);
```

**What is the expected behavior?**
To save the document only once, even when used without an `HTTP REQUEST`.

**Please mention your node.js, mongoose and MongoDB version.**
```bash
nodejs --version
v8.10.0
yarn info mongoose version
5.1.7
```
**mlab** - mongod version: 3.4.15 

edit: Added MongoDB Version
edit2: Fixed syntax error
edit3: clarification that using mlab

**Comment by lineus** [comment]
@Eksapsy your first code sample results in a syntax error:
```
new Animal({
    'idiots',
    'catdog'
  })
```

running a slightly modified version of your sample:

### 6626.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true); // so we can see the calls to the db
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const AnimalSchema = new Schema({
  name: {
    type: String,
    required: false
  },
  type: {
    type: String,
    required: true
  }
});

const Animal = mongoose.model('Animal', AnimalSchema);

new Animal({ name: 'idiots', type: 'catdog' }) // changed this line.
  .save()
  .then(console.log)
  .then(() => {
    return conn.close();
  });
```
Shows there is only one call to the DB.
### Output:
```
issues: ./6626.js
Mongoose: animals.insertOne({ _id: ObjectId("5b32b2f49b3de43c40298e1f"), name: 'idiots', type: 'catdog', __v: 0 })
{ _id: 5b32b2f49b3de43c40298e1f,
  name: 'idiots',
  type: 'catdog',
  __v: 0 }
issues:
```
Can you see if my example also saves 2 docs for you?

**Comment by Eksapsy** [comment]
Yes, with your code it only saves once.
The **solution** in your code is in these lines
```javascript
  .then(() => {
    return conn.close();
});
```
You close the connection before it saves twice. But, why it saves twice in the first place?

**Comment by lineus** [comment]
@Eksapsy for me, even without explicitly closing the connection, it only saves once.

### 6626.js (*modified*)
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const AnimalSchema = new Schema({
  name: {
    type: String,
    required: false
  },
  type: {
    type: String,
    required: true
  }
});

const Animal = mongoose.model('Animal', AnimalSchema);

new Animal({ name: 'idiots', type: 'catdog' })
  .save()
  .then(console.log);
```
### Output:
```
issues: mongo --quiet test
> db.animals.count()
0
>
issues: ./6626.js
Mongoose: animals.insertOne({ _id: ObjectId("5b32b8e21a22b43d97d05961"), name: 'idiots', type: 'catdog', __v: 0 })
{ _id: 5b32b8e21a22b43d97d05961,
  name: 'idiots',
  type: 'catdog',
  __v: 0 }
^C  // note the control-c here, no connection.close() this time.
issues: mongo --quiet test
> db.animals.count()
1
>
issues:
```

**Comment by Eksapsy** [comment]
Maybe it's an [mlab](http://mlab.com) issue. I don't have a local mongodb database, I'll set up one and I'll update you. Or if you want, you could test it in [mlab](http://mlab.com) for Free. It's really not much of a hustle to set up a db there, takes 1-2 mins.

Thanks, for the response. At least we probably found where the issue comes from.

**Comment by lineus** [comment]
I tried with MLab got the same results:
```
issues: go2mlab // simple bash function to connect to my mlab instance via mongo shell
>db.animals.count()
0
>
issues: ./6626.js
URI: mongodb://**:**@host.mlab.com:17701/lineus-test
Mongoose: animals.insertOne({ _id: ObjectId("5b32c0495194674273a15b14"), name: 'idiots', type: 'catdog', __v: 0 })
{ _id: 5b32c0495194674273a15b14,
  name: 'idiots',
  type: 'catdog',
  __v: 0 }
^C
issues: go2mlab
>db.animals.count()
1
>
issues:
```

I'll give this some thought. Something weird is definitely going on 👍

**Comment by Eksapsy** [comment]
A small update on this to help the debugging ...
I woke up, booted and tested the same thing on both **localhost** and [MLab](https://mlab.com/).
It worked nicely.
Tried without `conn.clode()`. Still worked nicely.

It is really weird and hard to debug it at that point. Which also keeps my interest alive. 
For all I know, the platform the database is on doesn't matter (**localhost** or [MLab](https://mlab.com/)).  It either has something to do with the network, or with the library. 
Although, even if it's on the network, it would be a good thing to find the bug so the library can prevent that kind of behavior.

**Comment by lineus** [comment]
Yeah, running the above code with nodemon and saving changes to the file will cause multiple saves:

### Verified:
```
issues: nodemon ./6626.js
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./6626.js`
URI: mongodb://**:**@host.mlab.com:17701/lineus-test
Mongoose: animals.insertOne({ _id: ObjectId("5b338a1a8485c620d4d46481"), name: 'idiots', type: 'catdog', __v: 0 })
{ _id: 5b338a1a8485c620d4d46481,
  name: 'idiots',
  type: 'catdog',
  __v: 0 }
[nodemon] restarting due to changes...
[nodemon] starting `node ./6626.js`
URI: mongodb://**:**@host.mlab.com:17701/lineus-test
Mongoose: animals.insertOne({ _id: ObjectId("5b338a2270e59920d8d957ca"), name: 'idiots', type: 'catdog', __v: 0 })
{ _id: 5b338a2270e59920d8d957ca,
  name: 'idiots',
  type: 'catdog',
  __v: 0 }
^Cissues
issues: go2mlab
>db.animals.count()
2
>^C
issues:
```
