### ISSUE TITLE
Collection is expiring fast

### ISSUE THREAD

**Issue by ralphchristianeclipse** [Automattic/mongoose#6633]
![image](https://user-images.githubusercontent.com/25447231/42075886-8d1d1260-7ba5-11e8-9525-a8fa5b14e9e1.png)

I want the message document expires 7d based on it's creation date

but i noticed it's deleted 60 seconds or earlier after the creation

**Comment by lineus** [comment]
@ralphchristianeclipse what are the indexes that currently exist on the collection in question?

**Comment by ralphchristianeclipse** [comment]
i think it's already fixed

hmmm so indexes are not cleaned up correctly
