### ISSUE TITLE
When search an empty collection with filter param will throw this errors

### ISSUE THREAD

**Issue by QYANGGITHUB** [Automattic/mongoose#6646]
{
    "nested": {
        "message": "Parameter \"obj\" to Document() must be an object, got 5b39e7257d220364d4e3d8a4",
        "name": "ObjectParameterError"
    },
    "stack": "NestedError: Failed to filter resources\n    at mongoDb.getResources.then.catch.err (d:\\Bitbucket\\ERP\\erp-server-middleware\\api\\helpers\\dbClient\\dbClient.js:124:27)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused By: ObjectParameterError: Parameter \"obj\" to Document() must be an object, got 5b39e7257d220364d4e3d8a4\n    at new ObjectParameterError (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\error\\objectParameter.js:23:11)\n    at EmbeddedDocument.Document (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\document.js:66:11)\n    at EmbeddedDocument [as constructor] (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\types\\embedded.js:32:12)\n    at new EmbeddedDocument (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schema\\documentarray.js:75:17)\n    at DocumentArray.SchemaArray.castForQuery (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schema\\array.js:283:13)\n    at d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schematype.js:1052:18\n    at Array.map (<anonymous>)\n    at DocumentArray.handle$in (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schematype.js:1048:14)\n    at DocumentArray.SchemaArray.castForQuery (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schema\\array.js:234:19)\n    at DocumentArray.SchemaType.castForQueryWrapper (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\schematype.js:1077:17)\n    at cast (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\cast.js:284:39)\n    at model.Query.Query.cast (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\query.js:3355:12)\n    at model.Query.Query._castConditions (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\query.js:1327:10)\n    at model.Query.Query._find (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\mongoose\\lib\\query.js:1342:8)\n    at process.nextTick (d:\\Bitbucket\\ERP\\erp-server-middleware\\node_modules\\kareem\\index.js:333:33)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"
}

**Comment by vkarpov15** [comment]
Please provide some code samples, stack trace isn't very helpful in this case.

**Comment by QYANGGITHUB** [comment]
I has found the issue in my code. I has send a string value to filter an object properties.
Thank you for the reply.

**Comment by adamreisnz** [comment]
@vkarpov15 I also ran into this error, same cause I presume, but I'm pretty sure this code used to work before.
Doesn't mongoose convert a string Object ID to actual ObjectId internally for queries if it's known to be an ObjectId from the schema?

**Comment by vkarpov15** [comment]
@adamreisnz yes it should. Can you open up a separate issue with a repro script that demonstrates the issue you're seeing?

**Comment by adamreisnz** [comment]
I think in this particular case the problem arose when I had unexpected data structure due to denormalization of our data. It's probably not worth opening an issue for, so I'll leave it for now, thanks!
