### ISSUE TITLE
Update to 5.2.0 and reports Authentication failed

### ISSUE THREAD

**Issue by isLishude** [Automattic/mongoose#6648]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

My code runs normal before 5.2.x but reports Authentication failed after update to 5.2 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

node version: 10.5.0
mongodb version: 3.4.6

```js
const mongoConfig = {
  dbName: process.env.db || "test",
  pass: process.env.passwd || "",
  reconnectInterval: 500,
  reconnectTries: Number.MAX_VALUE,
  user: process.env.user || ""
}

const uri = `mongodb://${ip}:${port}`;
const con = mongoose.createConnection(uri, mongoConfig);
```

**Comment by isLishude** [comment]
5.1.7 is OK.

**Comment by cosminn777** [comment]
This happens to me too.

**Comment by cosminn777** [comment]
More details, in MongoDB log:
...
Supported SASL mechanisms requested for unknown user 'xxx@xxx'
...
SASL SCRAM-SHA-1 authentication failed for xxx on trades from client 127.0.0.1:13289 ; UserNotFound: Could not find user xxx@yyy
....

**Comment by dbellavista** [comment]
Looking at the new documentation for 3.1

https://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#.connect

The `auth` was removed. So authentication should be provided via the connection string

**Comment by cosminn777** [comment]
Connecting with the string with ?authSource=admin

**Comment by lukywong** [comment]
met the same issue for 5.2.0

**Comment by lineus** [comment]
@isLishude Have you tried explicitly setting the authSource option? 

[according to the docs here](https://docs.mongodb.com/manual/reference/connection-string/) if you don't specify the db in the connection string it will use the 'admin' db for auth. 

Given the uri from your report above it sounds like it's possible you have the user on your db, but are authenticating against `admin`.

Here is an example connection to atlas passing all details but the hosts and ports into the options object that works on mongoose 5.1.7 and 5.2.0:

### 6648.js
```js
#!/usr/bin/env node
'use strict';

const env = require('/Users/lineus/.env');
const uri = env.ATLAS_HOSTS_ONLY;
const sharable = uri.replace(/[a-z0-9.]+.mon/g, 'host.mon');

const opts = {
  dbName: 'test',
  ssl: true,
  user: env.ATLAS_USER,
  pass: env.ATLAS_PASS,
  authSource: 'admin',
  replicaSet: env.ATLAS_RS,
  reconnectInterval: 500,
  reconnectTries: Number.MAX_VALUE,
  retryWrites: true
};

const mongoose = require('mongoose');
let conn = mongoose.createConnection(uri, opts);
const Schema = mongoose.Schema;

const schema = new Schema({
  test: String
});

const Test = conn.model('test', schema);

const test = new Test({ test: 'test' });

async function run() {
  console.log(`mongoose: ${mongoose.version}`);
  console.log(`uri: ${sharable}`);
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  console.log('saved:', found);
  return conn.close();
}

run().catch(console.error);
```
### Output:
```
issues: npm install mongoose@5.1.7 >/dev/null 2>&1
issues: ./6648.js
mongoose: 5.1.7
uri: mongodb://cluster0-shard-00-00-host.mongodb.net:27017,cluster0-shard-00-01-host.mongodb.net:27017,cluster0-shard-00-02-host.mongodb.net:27017/
saved: { _id: 5b3b5784eeaa6913e0227398, test: 'test', __v: 0 }
issues: npm install mongoose@5.2.0 >/dev/null 2>&1
issues: ./6648.js
mongoose: 5.2.0
uri: mongodb://cluster0-shard-00-00-host.mongodb.net:27017,cluster0-shard-00-01-host.mongodb.net:27017,cluster0-shard-00-02-host.mongodb.net:27017/
saved: { _id: 5b3b579414ed2313fdcdac05, test: 'test', __v: 0 }
issues:
```

**Comment by isLishude** [comment]
@lineus I see, but only 5.2.0+ reports this error.

**Comment by cosminn777** [comment]
@lineus I'm passing authSource in url with username and pass and it's not working (I'm using MongoDB 4.0). I Tried Mongoose 5.1.7 and 5.1.8 with MongoDB 4.0 and it's still not working.
Connecting with createConnection worked well with Mongoose 5.1.7 and MongoDB 3.6.5 but after updating to Mongo0ose 5.2.0 and MongoDB 4.0 it stopped working.

**Comment by mjason4x** [comment]
If you have (authSource) query in your connection string, its been converted to lowercase (authsource) by mongodb-core uri_parser which makes the option invalid...

Specifying the `authSource` directly on the opts object as @cosminn777  suggests fixes this ... 

But I believe it shouldn't be so and should respect my connection string ....

**Comment by arvi** [comment]
I experienced this also and I changed my code from:

```js
const dbOptions = {
  user: config.db.authUsr,
  pass: config.db.authPwd,
  auth: { authdb: config.db.authDb },
  useNewUrlParser: true,
  useCreateIndex: true, // https://github.com/Automattic/mongoose/issues/6890
};

// make mongoose use bluebird for promises - https://stackoverflow.com/a/40822769
mongoose.Promise = bluebird;
mongoose.connect(
  `mongodb://${config.db.host}:${config.db.port}/${config.db.name}`,
  dbOptions,
);
```

to:

```js
const dbOptions = {
  authSource: config.db.authDb,
  auth: { 
    user: config.db.authUsr,
    password: config.db.authPwd,
  },
  useNewUrlParser: true,
  useCreateIndex: true, // https://github.com/Automattic/mongoose/issues/6890
};
```

**Comment by vkarpov15** [comment]
@arvi `authSource` is the fix you need to make, the `user` -> `auth.user` change is unnecessary

**Comment by arvi** [comment]
@vkarpov15 I got confused with what you said I’m sorry. My code now works using the “to” section of my previous comment.

**Comment by vkarpov15** [comment]
This should work too:

```javascript
const dbOptions = {
  authSource: config.db.authDb,
  user: config.db.authUsr,
  pass: config.db.authPwd,
  useNewUrlParser: true,
  useCreateIndex: true, // https://github.com/Automattic/mongoose/issues/6890
};
```
