### ISSUE TITLE
URGENT 5.2.0: _Cannot specify a custom index on `_id`, MongoDB does not allow overwriting the default `_id` index_ is not correctly implemented

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#6650]
5.2.0 took a too restrictive measure to fix #6605:
- it makes sense not to create a duplicate index on _id
- it does not make sense to prevent any index designating _id as part of a list of indexed fields, e.g.:
    - { _categoryId: 1, _id: 1}
    - { _userId: 1, _id: 1 }

With 5.2.0, any index containing _id: 1 raises an error because of https://github.com/Automattic/mongoose/blob/master/lib/model.js#L1208

```
if (index[0]._id != null) {
```
should be replaced with something like

```
if (Object.keys(index[0]).length === 1 && index[0]._id != null) {
```

**Comment by bruun** [comment]
I agree this should not raise an error, at least not in a minor release. Perhaps emitting an error would be more suitable?

However: Does compound indexes with `_id` even make sense at all, since it is unique?

**Comment by jlchereau** [comment]
They make sense for sorting among other uses.

**Comment by vkarpov15** [comment]
@jlchereau thanks for the clarification and sorry about the trouble. We'll convert this to printing a warning if an index only has `_id` and no other fields.

**Comment by jlchereau** [comment]
In my opinion, you can throw and error when:

1. the index is a single file index designating _id
2. the index is a multi-field (compound) index and _id is not the last field.

**Comment by vkarpov15** [comment]
I think that's the case as well, but I'm going to err on the side of caution. When you make a mistake, there's very rarely just one mistake, so for now we'll keep it as a warning and consider adding the error back later if there aren't any issues with the warning.
