### ISSUE TITLE
Mongoose 5.2.0 parsing of URL is incorrect and won't allow connections to replicaSet clusters when specified in the URL

### ISSUE THREAD

**Issue by will3942** [Automattic/mongoose#6651]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Connecting to a replicated cluster will not work when specifying replicaSet in the URL.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
  const MONGODB_URI = 'mongodb://username:password@host1:27017,host2:27017/database?replicaSet=r123';

  const opts = {
    useMongoClient: true,
    keepAlive: 120,
    socketTimeoutMS: 30000,
    poolSize: 100,
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 500,
    autoReconnect: true,
  };

  mongoose.connect(MONGODB_URI, opts);
```

This will result in `MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name`.

However this does work:

```
  const MONGODB_URI = 'mongodb://username:password@host1:27017,host2:27017/database?replicaSet=r123';

  const opts = {
    useMongoClient: true,
    keepAlive: 120,
    socketTimeoutMS: 30000,
    poolSize: 100,
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 500,
    autoReconnect: true,
    replicaSet: 'r123',
  };

  mongoose.connect(MONGODB_URI, opts);
```

I believe this is due to this bug https://jira.mongodb.org/browse/NODE-1542, as soon as this is available in NPM the Mongoose dependency `mongodb-core` will need to be updated to fix this.

**What is the expected behavior?**

replicaSet can be set in both URL paremeters and options.

**Please mention your node.js, mongoose and MongoDB version.**

Node: 9
Mongoose: 5.2.0
MongoDB 3.4

**Comment by svda** [comment]
Same issue here.

**Comment by thlgrant** [comment]
Same issue here

**Comment by ceepeeuk** [comment]
Yep me too

**Comment by lineus** [comment]
@will3942 thanks for the report. You're correct about this being related to the issues with the new url parser which mongoose 5.2 uses.

**Comment by tpina** [comment]
If you end up in this thread please also read: #6648 

>  If you have (authSource) query in your connection string, its been converted to lowercase (authsource) by mongodb-core uri_parser which makes the option invalid...
> 
> Specifying the authSource directly on the opts object as @cosminn777 suggests fixes this ...

**Comment by NewEraCracker** [comment]
Same issue I had this morning. Ended up downgrading to 5.1.8 on my projects package.json

**Comment by vkarpov15** [comment]
We'll push a release within 24 hours with a fix, sorry for the trouble.
