### ISSUE TITLE
Is it possible to populate a subdocument from another subdocument?

### ISSUE THREAD

**Issue by akashdeepsinghal** [Automattic/mongoose#6654]
**Do you want to request a *feature* or report a *bug*?**
Neither.
I want to confirm: Is it possible to populate a subdocument from another subdocument of the same document model?

**Please provide the steps to reproduce.**

I have a document model called **school** which in turn has two subdocuments:
1. students
2. batch

Each student belongs to one batch.

```
var batchSchema = new Schema({
	name: {type : String}
});

var studentSchema = new Schema({
	name : {type : String, required:true},
	batch: { type: ObjectId, ref: 'School.batches' },
});

var schoolSchema = new Schema({
	name : {type : String, required:true},
	students : [studentSchema],
	batches : [batchSchema]
});

var School = mongoose.model('School', schoolSchema);
```

Now when I am fetching a student, I want to populate the batch as well. I am doing this as:
```

var school_id = req.params.school_id;
var student_id = req.params.student_id;

School
    .findOne({'_id': school_id, 'students._id': student_id})
    .populate({path: 'students.batch'})
    .exec(function (err, data) {
        done(err, data);
    });
```

When I do this, I get following error:
```

"message": "Schema hasn't been registered for model \"School.batches\".\nUse mongoose.model(name, schema)",
"name": "MissingSchemaError"

```

I also tried with virtual populate, I was getting null as the result.

**What is the expected behavior?**
When the details of a student is fetched (as above), I expected the result to populate the batch as well.

Please tell me if I am doing something wrong 
OR
It is possible to populate a subdocument from another subdocument?

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.11.2
Mongoose: v5.1.6
MongoDB: v3.6.5

**Comment by vkarpov15** [comment]
You should be able to populate embedded paths.  Although I don't understand why mongoose is looking for a model called 'School.batches', should be looking for 'Institute.batches'. Is 'School.batches' the model name for your 'School' model?

**Comment by akashdeepsinghal** [comment]
@vkarpov15 Yes that is not 'Institute.batches', that's 'School.batches'. I have corrected it in my question. (My bad)

No, but I am not being able to populate with that query statement.

**Comment by akashdeepsinghal** [comment]
Before anything else, I want to confirm,

**1. Is it valid to reference a subdocument from another subdocument?**

Like I have done in:
```
var studentSchema = new Schema({
	name : {type : String, required:true},
	batch: { type: ObjectId, ref: 'School.batches' },
});
```

**2. If inter-subdoc referencing is supported, am I doing this in the right manner?** 
{ type: ObjectId, **ref: 'School.batches'** }

**3. I also tried with 'refPath' rather than 'ref', but that doesn't work as well.**

**Comment by vkarpov15** [comment]
I think I see the issue, you don't have a model named 'School.batches', you have a model named 'School' and you're trying to reference the `batches` property on a school document. That is not supported, `populate()` only words if `ref` is the name of a model.

**Comment by akashdeepsinghal** [comment]
Can you please help me out for what do I 'ref' if I want to populate the subdoc named 'batches' in the model schema 'School'.

I tried to explain my concern in my second comment as well. Can you please help me out with this?

**Comment by vkarpov15** [comment]
I guess I'm just confused what you mean by "reference a subdocument from another subdocument"?  How does what you're trying to do differ from this?

```javascript
var batchSchema = new Schema({
	name: {type : String}
});

var studentSchema = new Schema({
	name : {type : String, required:true},
	batch: { type: ObjectId, ref: 'School' },
});

var schoolSchema = new Schema({
	name : {type : String, required:true},
	students : [studentSchema],
	batches : [batchSchema]
});

var School = mongoose.model('School', schoolSchema);

School.find().populate('students.batch');
```

**Comment by justraman** [comment]
Sorry, but i also encounter same problem
```javascript
var OfferSchema = new Schema({
        name:String,
        otherdata:String,
        category: [{name:String, description:String}]
});
mongoose.model('Offer', OfferSchema);

var UserSchema = new Schema({
       product:String,
       category:{type:ObjectId , ref:"Offer.category"}
});
mongoose.model('User', UserSchema);
```
**i want to populate category name and description**
Something Like:
```javascript
   let doc = await User.find({}).populate(category).exec();
   // doc.category ---> {name : 'offer name',description:'offer description'}
```
Is it Possible?

**Comment by vkarpov15** [comment]
@justraman what is the `User` model?

**Comment by justraman** [comment]
Edited ! ,

Mongoose populate works charm when reference an another collection document but  what if i want to reference a document array with their id. 

I know thier are other ways of doing it. But embedded documents make more sense in mongodb.

**Comment by vkarpov15** [comment]
@justraman If what you're trying to do is populate a single entry from `Offer.category`, that's not something we support right now. As a general rule of thumb, if you want to reference an entry in an array independently of the top-level document, you should store that entry in a separate collection. So if you find yourself populating product categories independent of offers, you should just store `Category` as a separate model.

**Comment by RezaErfani67** [comment]
is there any solution for this topic with new version of mongoose

**Comment by vkarpov15** [comment]
@RezaErfani67 can you please open a new issue and follow the issue template?
