### ISSUE TITLE
Populate to a new field

### ISSUE THREAD

**Issue by LK** [Automattic/mongoose#6655]
When you populate a field, it will always replace the field with the full object represented by the ID. This is messy; if I have a field like `user: { type: ObjectId }`, then it is not intuitive that this field does not hold the full object. Conversely, a field like `userId: { type: ObjectId }` becomes unintuitive when you populate the field. Furthermore, this behavior makes deciding to populate a field a breaking change for downstream API consumers; if I had an API returning a `Message` object with an unpopulated `user` field and then I decide to start populating it, all API clients must update.

I'll outline below the structure for document references that I've adopted in my project, would love to hear thoughts on it and how Mongoose can better support this style of referencing. At a minimum, being able to specify a new field name in which populated documents will be inserted will solve the inconsistencies outlined above.

Our project has two styles of references: an ID reference and a denormalized reference.

ID reference:
```
{
    userId: { type: ObjectId, ref: "User" }
}
```

Denormalized reference:
```
{
    user: {
        _id: { type: ObjectId, ref: "User" },
        name: { type: String },
        email: { type: String }
    }
}
```

In either case, we can implement the desired "populate" behavior by rewriting our query as an aggregation pipeline using a `$lookup` operator — in the first case, we create a new field called `user` which includes the full user document, while in the second case we replace the `user` object by the full document referenced in `user._id`. This allows us to draw a clear distinction between when we are returning an ObjectId and when we are returning a full object (or a subset of an object). We have a custom Mongoose plugin to automatically generate these embeddable sub-schemas (so `UserSchema.Embed(["name", "email"])` returns the schema embedded for users above). 

I'm not sure how much of this functionality would make sense to include natively in Mongoose and how much is best left out as custom extensions, but would be great to have some more robust reference handling behavior implemented somewhere.

**Comment by vkarpov15** [comment]
I agree this behavior is often inconvenient, that's why we have [virtual populate](http://mongoosejs.com/docs/populate.html#populate-virtuals) which does essentially what you suggest.
