### ISSUE TITLE
QUESTION: generate multiple virtuals from one calculation, without having to do the calculation in each virtual getter?

### ISSUE THREAD

**Issue by r3wt** [Automattic/mongoose#6660]
Hi, i need to generate two virtuals, but the problem is they each depend on the same calculation. i cannot show the calculation as it is proprietary in nature, but i can provide an example of what i need to do.

i am wondering if there is any problem with just creating a dummy virtual with a weird name like `trigger_calc`, and then setting the properties on the model from this getter. example:

```js
schema.virtual('trigger_calc').get(function(){
    const {foo,bar} = proprietaryCalculation(this);//uses some model properties to generate two values
    this.foo = foo;// would be spit out of the algorithm
    this.bar = bar;// ditto
    return null;//return nothing, this getter is just used to trigger the calculation of the above fields
});
```

is this acceptable? i am wondering what side effects this could cause? or would i also need to define getters for `foo`, and `bar`. i am really confused on what the best approach would be here. Thanks!

**EDIT:**
what order are getters executed in? if it can be guaranteed that they execute in the order defined, then i could run 1 getter first to get the first value, then read that value when the next getter runs to generate that value. that would be the best solution, if its possible.

**Comment by vkarpov15** [comment]
There's no guarantee the order that virtuals are run in. Say you have 2 virtuals, `foo` and `bar`, and `foo` is declared before `bar`. If you do `doc.toJSON({ virtuals: true })`, the getters for `foo` and `bar` will run in order. But you could do `doc.bar; doc.foo;` and then the `bar` getter would run before the `foo` getter.

There's nothing wrong with this `trigger_calc` approach, it is a little confusing though. What prevents you from running `proprietaryCalculation(this);` in both the `foo` getter and the `bar` getter?

**Comment by r3wt** [comment]
@vkarpov15 because it is wasteful (Doing same mathematical computation twice), and node.js is single threaded, so the algorithm can't be made async.

**Comment by vkarpov15** [comment]
Yeah that's correct. Here's another option: what if your virtual returned an object?

```javascript
schema.virtual('calc').get(function() {
  const { foo, bar } = proprietaryCalculation(this);
  return { foo, bar };
});
```

**Comment by r3wt** [comment]
@vkarpov15 it would work, but i would prefer to avoid doing that. a nice flat object is preferrable, i hate nesting foolishly, especially when there are already two other related fields in object, it would be weird to have these two nested and the other two related fields not
