### ISSUE TITLE
Cannot connect to MongoDB with mongoose.connect()

### ISSUE THREAD

**Issue by jochenshi** [Automattic/mongoose#6661]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I cannot connect to the MongoDB with the method ```mongoose.connect()```, it reports 
```database connection failed { MongoError: Authentication failed.```

**If the current behavior is a bug, please provide the steps to reproduce.**

1.create a database named "testServer" and then create a user ```user1``` in database ```admin``` and assign it the relative rights.
2.try to connect the database ```testServer``` with the user "user1" like:
```mongoose.connect("mongodb://user1:passeord@ip:port/testServer?authSource=admin")```
3.then it arrives at the error as below:
```database connection failed { MongoError: Authentication failed.```
and i check the log info, it seems that the db still tries to check the credential info in database ```testServer``` rather than the database ```admin```

**What is the expected behavior?**
connect success

**Please mention your node.js, mongoose and MongoDB version.**
nodejs v8.9.1
mongoose v5.2.0
MongoDB v4.0.0

**Comment by zoulux** [comment]
me too

**Comment by lineus** [comment]
please try mongoose 5.2.1 which was released late yesterday evening. There is a an issue in the latest version of the native driver regarding the new url parser addressed in issues #6651, #6647, and #6656 that should be resolved by using 5.2.1.

**Comment by jochenshi** [comment]
This problem has been solved in V5.2.1

**Comment by amoriqbal** [comment]
I am facing this issue in 5.9.6 now.

**Comment by vkarpov15** [comment]
@amoriqbal please open a new issue and follow the issue template.
