### ISSUE TITLE
Global default required configuration

### ISSUE THREAD

**Issue by joeytwiddle** [Automattic/mongoose#6662]
https://github.com/Automattic/mongoose/issues/6578#issuecomment-402029769

`mongoose.set('required', true)` to make all fields `required: true` by default.

I know Valeri was not so keen on this idea, so I will try to provide my justification below...

(I brought my comments to this new issue because I thought it might be clearer in a fresh thread.)

**Comment by joeytwiddle** [comment]
I can imagine that developers who have been using Mongoose for some time will find this counter-intuitive.

But I love setting `required: true` globally at the start of a project. Let me explain why...

I have worked with developers who create a schema without bothering to mark which fields are required:
```js
const userSchema = new Schema({
  name: String,             // should have been marked required
  email: String,            // should have been marked required
  favouriteColor: String,   // optional, ok
});
```

By the time I realise that they missed the option, it's too late: our database now has invalid documents in it. (We have users without names, or without email addresses, because buggy code never threw any errors.)

Furthermore, sometimes I will look at a schema and I have no idea which fields should have been marked required and which should not.

I would rather force all fields to be required by default. Then if the developer doesn't want it to be, they can add `required: false` to the schema. They will often do this after creating their first minimal test document. After that, the intent of the code is now very clear.

(In fact, when I write a schema, I always write `required: true` or `required: false`. That makes it clear that I have thought about it, and made a decision. And that code will work the same way, regardless of the global setting.)

----

The `strict: 'throw'` is useful when 5 minutes later they forget what the names of the fields were:
```js
await User.create({
  userName: 'harry',
  emailAddress: 'harry@hogwarts.com',
});
```
By default mongoose's behaviour would be to silently drop those fields, and create an empty document. That won't be noticed until the document is read back later. I would prefer to catch that mistake at creation time, sooner rather than later.

**Comment by vkarpov15** [comment]
Worth considering, thanks for the detailed justification. My concern is more just API consistency. The `mongoose.set('strict', 'throw')` approach is consistent with options like [`bufferCommands`](http://mongoosejs.com/docs/api.html#mongoose_Mongoose-set), where the mongoose global can modify defaults that schema options can override. But we don't have a precedent for a mongoose global option that modifies a default for schema types.

**Comment by marcelh-gh** [comment]
@vkarpov15 
There might be another use case for a global schema setting.
I have a rather large amount of schemas, many of them nested into each other.
Most of them have getters and setters.
To have those executed when necessary I need  `schema.set('toObject', { getters: true });`.
Without a global setting this has to be done for every schema. A global setting that could be modified
locally would be much more convenient.

Since this exists already:

> 'objectIdGetter': true by default. Mongoose adds a getter to MongoDB ObjectId's called _id that returns this for convenience with populate. Set this to false to remove the getter.

...I think it would not be inconsistent to have more global settings like this.
Any thoughts?

**Comment by vkarpov15** [comment]
That's a good idea, I opened up an issue to track.

**Comment by libook** [comment]
I always made mistakes on spelling "required". It is hard to find out. It may be very helpful if there is an option can make all fields required on default. I can also set "required: false" on fields when I need. And this kind of spelling issues won't affect data in database.

**Comment by vkarpov15** [comment]
Fixed in 5.9, see http://thecodebarbarian.com/whats-new-in-mongoose-59-schematype-default-options-and-per-document-populate.html

**Comment by joeytwiddle** [comment]
Thanks!

I see that not all types have the `set` function (for example DocumentArray and Embedded do not).

Therefore, for my use case, I think I can set all fields of all types required by default, like this:

```js
var allTypes = Object.values(mongoose.Schema.Types);
allTypes.forEach(type => {
  if (typeof type.set === 'function') {
    type.set('required', true);
  }
});
```

**Comment by vkarpov15** [comment]
Thanks for pointing that out @joeytwiddle, we will add that in a future release :+1:

But yes that should work for setting all types to be required by default.
