### ISSUE TITLE
countDocuments() with 0 results throws an Error

### ISSUE THREAD

**Issue by matthagemann** [Automattic/mongoose#6666]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The following query results in `TypeError: Cannot read property 'n' of undefined`:
```
var start = moment().subtract(1, 'day').startOf('day')
var cutoff = moment().subtract(1, 'day').endOf('day')

var result = await User.countDocuments({
  'createdAt': {
    $lte: cutoff,
    $gte: start,
  }
})
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Execute above code (either use momentjs or vanilla Date() objects)

**What is the expected behavior?**
Should return the document count.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose: 5.2.1
MongoDB: 4.0.0
Node.js: 8.11.1

**Comment by lineus** [comment]
@matthagemann It seems like there's more going on here than what is in your example code. Can you try and expand your example, or adapt mine to reflect the behavior you're seeing?

### 6666.js
```js
#!/usr/bin/env node --no-deprecation
'use strict';

const moment = require('moment');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  createdAt: Date
});

const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 0; i < 100; i++) {
  let date = moment().subtract(i, 'days');
  tests.push(new Test({ name: `name${i}`, createdAt: date }));
}

async function run() {
  await conn.dropDatabase();
  await Test.create(tests);
  const start = moment().subtract(50, 'days').startOf('day');
  const cutoff = moment().endOf('day');
  const result = await Test.countDocuments({
    createdAt: {
      $lte: cutoff,
      $gte: start
    }
  });
  console.log(result);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6666.js
51
issues:
```

**Comment by matthagemann** [comment]
Thanks for hacking that file so quick, @lineus. I think I got to the core of the issue. The error can be reproduced if you try to achieve 0 document counts. One way is to simply remove `.subtract(50, 'days')` in your file like this:
```
const start = moment().startOf('day');
```
You should then get that error instead of 0 count.

**Comment by lineus** [comment]
You're welcome @matthagemann 👍 There's an existing bug in the current native driver that breaks countDocuments with results of 0 length. The fix will ship in driver 3.1.1. [here's the link](https://jira.mongodb.org/browse/NODE-1543). We can leave this open until we ship the next driver version.

**Comment by fundon** [comment]
https://github.com/mongodb/node-mongodb-native/releases/tag/v3.1.1

**Comment by fernandolguevara** [comment]
can you make a release to fix this bug please 🙏@lineus @vkarpov15

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/41ec904c5afd4bcb87822a6216c73183c16668d0, will ship 5.2.2 later this weekend.
