### ISSUE TITLE
aliases do not work with nested properties

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#6671]
**What is the current behavior?**

```
const bookSchema = new mongoose.Schema({
    author: {
        _userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            alias: 'userId' // <------------- does not create corresponding getter/setter 
        }
    },
    title: {
        type: String,
        trim: true,
        required: true
    }
});
```

**What is the expected behavior?**

JSON is hierarchical so book.author.userId should work.

**Please mention your node.js, mongoose and MongoDB version.**

5.2.0 + 4.0

**Comment by jlchereau** [comment]
It needs to be set as `alias: 'author.userId'`

**Comment by lineus** [comment]
I'm reopening this to track potentially adding something to the docs about nested paths.
