### ISSUE TITLE
How to not select fields that not defined in a schema?

### ISSUE THREAD

**Issue by RidgeA** [Automattic/mongoose#6673]
Hi!

I'd like to use one collection for two schemas
E.g:
Document in DB:
```
{"name":"John", "position":"CEO"}
```

Schema `User`: 
```
{
"name" : String
}
```

Schema `Employee`: 
```
{
"name" : String,
"position" : String
}
```

Nevertheless, when selecting a user (`User.findById()`) in the result I can see all the fields from the document, even not defined in the schema.
I don't want to disclose some fields in a stripped-down model at all so `select: false` for such fields is not what I'm looking for ...
Also, I'd like to prevent saving any fields not listed in a schema.

Is it possible to define a schema in such way?

Or I'm wrong and `select:false` is exactly what I'm looking for? :-) 

I'm using Mongoose `5.0.14` but it is not a problem to update to the latest version if it would help.

**Comment by vkarpov15** [comment]
Mongoose doesn't save properties that aren't in the schema by default unless you [turn off the `strict` option](http://mongoosejs.com/docs/guide.html#strict). Can you post your full schema? Also, Mongoose doesn't apply schemas when reading from the db, so if your schema doesn't have a `position` property but the document in the db has a `position` property that property will still show up if you load that document using `User.findOne()`.

Also, you might want to look at [discriminators](http://mongoosejs.com/docs/discriminators.html).

Does this help?

**Comment by RidgeA** [comment]
@vkarpov15 
Thank you for your reply.

Discriminators won't help me because I'd like to define a new model based on existing data in the collection depends on user's privileges. For a user with lower privileges, I'd like to show a model with a limited set of fields - some kind of ViewModel. But it is the same data and I haven't field in the collection to distinguish one model from another.

In order to hide some fields, I have to define `select:false` for such fields. But it makes it possible to save this fields. I want neither to fetch nor give chance to saving this fields. 

Since MongooseJS haven't such possibility I believe it is possible to close this issue.

Nevertheless, I convinced, that this option will be useful in some cases, so I would be nice to see this option in following releases
