### ISSUE TITLE
`model.remove((err, doc) => {...});` now returns err as undefined instead of null

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#6674]
**What is the current behavior?**

`model.remove((err, doc) => {...});` now returns err as undefined instead of null. This is not consistent  with save, update, ...

**What is the expected behavior?**

`model.remove((err, doc) => {...});`  should return null err when succcessful.

**Please mention your node.js, mongoose and MongoDB version.**

5.2.1 + 4.0

**Comment by jlchereau** [comment]
`expect(err).to.be.null;` failed repeatedly while switching code to promises but cannot reproduce anymore.

**Comment by vkarpov15** [comment]
Thanks for closing, feel free to re-open if this issue pops up again :+1:
