### ISSUE TITLE
Separate `cleanIndexes()` helper function that removes non-schema indexes

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6676]
I'm happy to see something like `Model.syncIndexes()` made its way to mongoose, thanks!

I'm a bit worried it should be split into 2 separate methods though, or its behavior should be configurable via flags. I wanted to use it together with schema migration, but there's an issue.

Imagine the following schema migration scenario:
1. You have a collection with fields A and B, unique index is set on A
2. You want to write a migration script that swaps the values of A and B and 'moves' the unique index to B

What you have to do is:
1. Drop the index on A
2. Run a migration that swaps A and B
3. Create the index on B

If you'd drop the index on A and create an index on B in the same step, you'd violate the unique constraint. And that's what the `Model.syncIndexes` is doing.

Of course it's a trivial, non real world example, but I think it demonstrates the issue clearly. Supporting something like
* `Model.syncIndexes({removeOnly: true})`
* `Model.syncIndexes({createOnly: true})`

could cover slightly more complex use cases.

**Comment by vkarpov15** [comment]
How about if we add a separate method like `Model.cleanIndexes()` that removes indexes that aren't in the schema, so `syncIndexes()` will just do `cleanIndexes().then(() => ensureIndexes())`. Would that work for you?

**Comment by jlsjonas** [comment]
This would solve certain migration issues for us too.

**Comment by vkarpov15** [comment]
@jlsjonas can you please describe the issues you're experiencing?

**Comment by jlsjonas** [comment]
@jlsjonas during migration we should be able to `cleanIndexes` to remove indexes that don't exist anymore in the new model (without destroying ALL indexes), run migration to convert old data, then `ensureIndexes` to add any new indexes.
