### ISSUE TITLE
[Docs] Middleware updateOne, and updateMany

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#6679]
http://mongoosejs.com/docs/middleware.html

The middleware docs for mongoose has some typos, and lacks examples for pre/post updateOne and updateMany middlewares. And the version is set to 4.x in the very beginning of the page, which should be changed to 5.x.

Will be creating a PR with these changes ASAP.

**Comment by vkarpov15** [comment]
Great, looking forward to the PR. Make sure you make the changes to `docs/middleware.jade`, **not** `docs/middleware.html`

**Comment by danpe** [comment]
Docs still missing?

**Comment by AbdelrahmanHafez** [comment]
@danpe 
[This PR](https://github.com/Automattic/mongoose/commit/bea998d8b50801c5c34005c130035eb0189b6c33) is merged, is it what you're looking for?
