### ISSUE TITLE
Field default function called during findOne

### ISSUE THREAD

**Issue by Spyridox** [Automattic/mongoose#6684]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When calling findOne default functions are called. I didn't test if this happens also with other functions.
This might be related to #6410.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
//##################################
// userSchema.js
const UserSchema = new mongoose.Schema({
    name : {
        type: String,
        required: true,
        unique: true,
        default: function() {
            console.log('called');
            return 'John';
        }
    }
});

export default mongoose.model('User', UserSchema);

//##################################
// otherFile.js

import User from 'models/userSchema';

// assume a User document already exists in the db
User.findOne({ name: 'John' }, function(err, user) {
    //...
    console.log(user);
});

```

**What is the expected behavior?**
I expected default functions to be called only on document creation if the field is not given, and never again.

**Please mention your node.js, mongoose and MongoDB version.**
`node v8.11.3`
`"mongodb": "^3.1.0"`
`"mongoose": "^4.13.14"`

**Comment by vkarpov15** [comment]
This is expected behavior, we run defaults when hydrating a document from MongoDB. What problems does this behavior cause for you?

**Comment by Spyridox** [comment]
Well, if the field already has an assigned value, what is the need of calling the default?
It could be a problem if the function takes a long time to execute, or if it throws errors (i.e. a function that generates a unique token and that throws an error after three failed attempts); when the `User` is created, it can make sense, but during a `findOne` it be unexpected.

**Comment by vkarpov15** [comment]
Ah ok, I misunderstood the question, I thought for some reason the document didn't have the `name` property in the database. Will investigate ASAP, thanks for reporting and clarifying.

**Comment by vkarpov15** [comment]
Yeah the below script calls your default function in 4.x, but not in mongoose `>= 5.0.18` re: #6410. Is there something that prevents you from upgrading to mongoose 5.x?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh6684`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const UserSchema = new mongoose.Schema({
    name: {
      type: String,
      required: true,
      default: function() {
        console.log('called');
        return 'John';
      }
    }
  });

  const User = mongoose.model('gh6684', UserSchema);

  await User.create({});

  console.log('----------');
  const doc = await User.findOne({ name: 'John' });
  console.log(doc);
}
```

**Comment by Spyridox** [comment]
Thanks for the help!
As of now, I don't know if there are problems with upgrading, I'll ask.

**Comment by vkarpov15** [comment]
I'll close this for now. If you have significant issues with upgrading to 5.0.18 post on this issue and we'll look into backporting this fix to 4.x.
