### ISSUE TITLE
We need to update the compatibility guide to reflect mongodb 4

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6685]
http://mongoosejs.com/docs/compatibility.html should reflect mongodb 4 for version 5.2 and up.

**Comment by kvanrobbroeck** [comment]
Hey, I was planning to take on this issue as my first contribution to a FOSS project after talking to @lineus about it earlier today, but it seems you beat me to it. Oh well. Thanks for a great library guys! We use it at work and it's awesome! FOSS really makes the world a better place!

**Comment by lineus** [comment]
That's on me @kvanrobbroeck 😈 I should have mentioned it in a comment here after we spoke. There are some other documentation issues you could tackle if you're interested. I hope to see you around some more 👍

**Comment by vkarpov15** [comment]
Ditto, PRs are always welcome :) next time @lineus if you mark something as a good first issue I'll assume that means someone is working on it, sound good?

**Comment by lineus** [comment]
That works for me @vkarpov15
