### ISSUE TITLE
How to populate notifiId to Notifications

### ISSUE THREAD

**Issue by bonnguyenitc** [Automattic/mongoose#6686]
const userSchema = new mongoose.Schema({
      email: { type: String, unique: true },
      password: String,
      notifications: [{
        notifiId: {type: Schema.Types.ObjectId, ref: 'Notifications' },
        viewed: { type: Number, default: 0 }
      }],
    }));
----------aaaaaaaaa-----------
How to populate notifiId to Notifications 
My code:

User
    .findOne({_id: userNotifications.userId})
    .populate({path:'notifications', match: {notificationType: 
    userNotifications.notificationType}, populate: {path: notifiId })
    .exec(function(err, user){
      if(err || !user){
        return callback(1, null);
      }
      return callback(null, user.notifications)
    });

**Comment by vkarpov15** [comment]
Just do `populate('notifications.notifId')`
