### ISSUE TITLE
Empty MongoError on Connect

### ISSUE THREAD

**Issue by kmccmk9** [Automattic/mongoose#6687]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When connecting it does not hit the Promise catch but throws an empty "MongoError"
**If the current behavior is a bug, please provide the steps to reproduce.**
```
mongoose.Promise = global.Promise
mongoose.connect(process.env.URL_Mongo, { useNewUrlParser: true }).then(() => {
  console.log('MongoDB Successfully connected')
}).catch((err) => {
  console.log('MongoDB Connection Error: ' + err)
  process.exit(1)
})
```

Output in Console:
```
MongoDB Successfully connected
MongoError
```
**What is the expected behavior?**
Connect successfully or throw a meaningful error from the Promise.
**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 10.3.0
Mongoose: 5.2.1
MongoDB: db version v3.4.1

**Comment by lineus** [comment]
@kmccmk9 are you running that **exact** code to get that ouput? The 2nd line of your output doesn't look like it came from this code.

For example, when I run your code with a port that mongodb isn't listening on:

### 6687.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const u = 'mongodb://localhost:27018/test';
mongoose.connect(u, { useNewUrlParser: true })
  .then(() => {
    console.log('MongoDB Successfully connected');
  })
  .catch((err) => {
    console.log('MongoDB Connection Error: ' + err);
    process.exit(1);
  });
```
### The output is:
```
issues: ./6687.js
MongoDB Connection Error: MongoNetworkError: failed to connect to server [localhost:27018] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27018]
issues:
```

**Comment by kmccmk9** [comment]
I can confirm I do not have any other references to mongoose or mongo in my code. However, I will note that I am using the vermongo plugin with Mongoose.

**Comment by kmccmk9** [comment]
I am sorry for wasting any time. If I comment out mongoose-vermongo lines it appears to work as expected. Therefore I believe the issue is in their plugin not mongoose core.
