### ISSUE TITLE
Unable to set array to `null` as default

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6691]
**Do you want to request a *feature* or report a *bug*?**

Bug in the latest mongoose version (5.2.1)

**What is the current behavior?**

Schemas ignore `default: null` for arrays, empty array is created instead.

```js
const schema = new mongoose.Schema({
  arrayThatShouldBeNull: {
    type: [String],
    default: null,
    required: false
  },

  arrayThatShouldContainTwoEntries: {
    type: [String],
    default: ['asd', '123'],
    required: false
  }
}, {
  minimize: false // not sure if relevant
});

const Model = mongoose.model('test', schema);
const instance = new Model();

expect(instance.arrayThatShouldBeNull).to.be.null; // fails
expect(instance.arrayThatShouldContainTwoEntries).to.deep.equal(['asd', '123']); // passes
```

**What is the expected behavior?**

`instance.arrayThatShouldBeNull` should be set to null, but instead an empty array is created

**Comment by lineus** [comment]
Hi @sebastian-nowak,

if you want a null value for the array default you need to return it from a function. Your example would become:

### 6691.js
```js
#!/usr/bin/env node
'use strict';

const chai = require('chai');
const expect = chai.expect;
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  arrayThatShouldBeNull: {
    type: [String],
    default: () => { return null; },
    required: false
  },

  arrayThatShouldContainTwoEntries: {
    type: [String],
    default: ['asd', '123'],
    required: false
  }
}, {
  minimize: false // not sure if relevant
});

const Model = mongoose.model('test', schema);
const instance = new Model();

expect(instance.arrayThatShouldBeNull).to.be.null; // now succeeds
expect(instance.arrayThatShouldContainTwoEntries).to.deep.equal(['asd', '123']); // passes
```
### Output:
```
issues: ./6691.js
issues:
```

**Comment by sebastian-nowak** [comment]
Thanks for clarification. Is this behavior documented somewhere? I find it a bit surprising, I don't see any immediately obvious reason why `null` wouldn't work as a default value. Are there any other types that also required returning `null` via function?

**Comment by lineus** [comment]
It's mentioned [here](http://mongoosejs.com/docs/faq.html#array-defaults) in the FAQ, but I just noticed that the example needs to be changed there as the text says null but the example returns undefined.

**Comment by lineus** [comment]
opened PR #6695 for this.

**Comment by shashwat-idm** [comment]
this is still a thing in mongoose v7.
Why is this the default behaviour?
If i'm explicitly setting it to null, it should be null

**Comment by MiguelBrito1086** [comment]
@vkarpov15 is this actually working. I’m on v8.5.1 using
`schemaKey: {type: [myArray], default: null, _id: false}` and it fails. Validation error but works if I use a function returning `null` for default.
