### ISSUE TITLE
thousands of ESTABLISHED connections to mongos on localhost per node process

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#6692]
**Do you want to request a *feature* or report a *bug*?**
bug / question

**What is the current behavior?**
I'm expieriencing some weird behaviour and trying to lock it down now: On my "worker" several node processes are forked. Each forked process has it's own mongoose connection pool (poolSize 5). After several hours, netstat shows me 2800 ESTABLISHED connections from just a single forked process. Shouldn't it be higher than 5 at all? Or do I miss something here? The problem is that I have more than one process that forks, so right now there are 10567 open established connections to my mongos (localhost). 

**If the current behavior is a bug, please provide the steps to reproduce.**
Nothing special, just let a script run for a while that does a lot of queries. If this isn't a configuration issue, I will provide a test script.

Options I pass to mongoose:
```
{
                useNewUrlParser: true,
                autoReconnect: true,
                noDelay: true,
                keepAlive: 30000,
                connectTimeoutMS: 360000,
                socketTimeoutMS: 900000,
                reconnectTries: 30,
                reconnectInterval: 1000,
                poolSize: 5,
                readPreference: 'secondaryPreferred',
                autoIndex: false
}
```

**What is the expected behavior?**
No more than 5 open connections in parallel.

**Please mention your node.js, mongoose and MongoDB version.**
node 8.11.3
mongoose 5.2.1
mongodb 4.0.0

thanks
Simon

**Comment by simllll** [comment]
Somehow I have a hand for things that are not easy to debug, I just tried several test scripts.. no chance to get the connectinos above 5 per node process. I'm switching now from "127.0.0.1" to "localhost" to use tcp6 instead of 4. Any other ideas what is happening here?

**Comment by simllll** [comment]
Seems like the issue was caused by a 3th party library. Closing this for now.
As general hint if someone ever has a similar issue:
Check that you do not have more than one mongoose "connectino" pool defined, try to reuse it as much as you can.

**Comment by vkarpov15** [comment]
Also, can you clarify which 3rd party library was causing the issue @simllll ?

**Comment by simllll** [comment]
@vkarpov15 my issue was related with a promise that took some time to resolve and returned an intialized flag to a new database connection. This was hard to debug, because under test cases the promises returned immediately, only under heavy load it took longer. And also only happened when the promise hasn't been called before. It was a fork of "Agenda" (job scheduler).

I didn't response earlier, because I'm still looking into some strange issues I have. 
1.) Right now it looks some queries just take way longer than before, but could also be related to mongo 4.0.0, due to the reason that the query also takes ages in mongo shell. It is a very simple query that asks only for keys in a a combined index (shared cluster and the collection is sharded), but asks with a "large" array if any of the values exists (large means between 10.000 and 50.000). Query size is below 16mb though.
2.) If I have more than 60 parallel connections to mongos, everything becomes slower, If I increase the poolsize by 10 and fork some queries to establish more connections and go than back in "sleep" mode (no querires running), mongos is also very slow establishing new connections.

It seems that this things causing "mongos" to slow down a lot, which causes a lot of other issues too. I see initial connection requests up to 30 seconds with the mongo cli to mongos. Very strange.

I was playing around with ShardingTaskExecutorPoolMaxSize (100) taskExecutorPoolSize (4) and serviceExecutor (adaptive). Setting this parameters to the values in the brackets flattens out the problem, but does not eliminate it.

regards
Simon

**Comment by simllll** [comment]
update, i just checked my log files and see a lot of lines like this:
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15843 connections now open)
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15842 connections now open)
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15841 connections now open)
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-11] end connection anonymous unix socket:27017 (15840 connections now open)
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15839 connections now open)
Jul 12 15:25:08 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15838 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15837 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15836 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15835 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15834 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15833 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15832 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15831 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15830 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-11] end connection anonymous unix socket:27017 (15829 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15828 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-8] end connection anonymous unix socket:27017 (15827 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15826 connections now open)
Jul 12 15:25:09 ip-10-0-12-91 mongos.27017[10596]: [worker-10] end connection anonymous unix socket:27017 (15825 connections now open)

it actually seems like mongoose is connecting and disconnecting very heavily.

still looking into it.

**Comment by simllll** [comment]
I have these listeners:
```
        mongoose.connection.on('connected', function () {
            console.log('Mongoose default connection open');
        });

        mongoose.connection.on('error', function (err) {
            console.log('Mongoose default connection error: ' + err);
        });

        mongoose.connection.on('disconnected', function () {
            console.log('Mongoose default connection disconnected');
        });

```
And I also see a lot of  entries like this:
```
[17:33:57.125] [LOG]   11/backend/joblog.js,backend/usernews.js: Mongoose default connection open
[17:33:57.125] [LOG]   11/backend/joblog.js,backend/usernews.js: Mongoose default connection reconnected
[17:34:07.128] [LOG]   11/backend/joblog.js,backend/usernews.js: Mongoose default connection

```
In the same second it seems that it is connecting and also reconnecting?

**Comment by simllll** [comment]
"funny" side fact: Increasing the servers capactiy (increasing mongos limits and co), results in even more connections, current day record: **26976** connections now open.

Btw I see this from time to time:
```
[ERROR] Uncaught exception in { MongoError: Couldn't get a connection within the time limit
    at /var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:580:63
    at authenticateStragglers (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:503:16)
    at Connection.messageHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:539:5)
    at emitMessageHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
  name: 'MongoError',
  message: 'Couldn\'t get a connection within the time limit',
  ok: 0,
  errmsg: 'Couldn\'t get a connection within the time limit',
  code: 202,
  codeName: 'NetworkInterfaceExceededTimeLimit',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 9, high_: 1531465757 },
  '$clusterTime': 
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 9, high_: 1531465757 },
     signature: { hash: [Object], keyId: [Object] } },

```
Shouldn't this be catched by mongoose and "auto-retried"?

Thanks
Simon

**Comment by vkarpov15** [comment]
Are you sure this is mongoose connecting / disconnecting and not agenda? Also, since the query is slow in the shell, have you tried doing `explain()` on it?

**Comment by simllll** [comment]
Yes,because I pass mongoose.connection to agenda..agenda has no own connection anymore. 

Yeah the issue is indeed very strange,if I split the query to several smaller ones, performance is back and also the load drops significantly.

**Comment by vkarpov15** [comment]
Yeah MongoDB currently can only make progress on one operation per socket, so generally splitting up one operation into multiple operations is slower but allows for better throughput.

Also, does agenda actually support mongoose connections? I wasn't aware of this...

**Comment by vkarpov15** [comment]
Would you be interested in putting in a PR with your fork? I have push access to agenda and it would be great to have that functionality in agenda for the next release

**Comment by simllll** [comment]
I will look into it later this month, but basically it's not a big deal since mongo-3 support in agenda, I basically just connect mongoose and pass mongoose.connection (which is a mongodb native connection) to agenda via mongo parameter. So it's not really mongoose, but the same connection pool "managed" and connected via mongoose.

**Comment by valayDave** [comment]
@simllll : I am facing the same problem. We are running a MongoDB shared cluster with multiple mongos's interacting with Nodejs microservices. All microservices are using mongoose for handing mongodb database models. 

```
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:07:53 GMT+0530 (IST)
 Mongoose Connected To URI Fri Jul 20 2018 17:07:53 GMT+0530 (IST)
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:08:03 GMT+0530 (IST)
 Mongoose Connected To URI Fri Jul 20 2018 17:08:03 GMT+0530 (IST)
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:08:13 GMT+0530 (IST)
 Mongoose Connected To URI Fri Jul 20 2018 17:08:13 GMT+0530 (IST)
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:08:23 GMT+0530 (IST)
 Mongoose Connected To URI Fri Jul 20 2018 17:08:23 GMT+0530 (IST)
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:08:33 GMT+0530 (IST)
 Mongoose Connected To URI Fri Jul 20 2018 17:08:33 GMT+0530 (IST)
 Mongoose Default Connection Disconnected Fri Jul 20 2018 17:08:43 GMT+0530 (IST)
```
These are the logs from one of my micro service.

The below are my connection options 

```
        socketTimeoutMS: 100000,
        connectTimeoutMS: 500,
        reconnectTries: 400, // Never stop trying to reconnect
        reconnectInterval: 500, // Reconnect every 500ms
        keepAlive: true, 
        keepAliveInitialDelay: 300000
```

I am using Mongoose version 5.2.4. I really think this is a mongoose client connection problem. We have been using the same micro services for months and not faced any issue with the connections. The microservices do on an average 20 Million db operations a day. We faced no issues for 3 months. This recently starting popping up. 

I am currently going to rollback to one of the previous versions of mongoose. Need a fix to this problem soon.
