### ISSUE TITLE
Implement estimatedDocumentCount

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#6697]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
count() has been depreaced in favor of countDocuments() and estimatedDocumentCount(). Only countDocuments is implemented in mongoose yet. The native driver supports both functions already.

Unhandled rejection in TypeError: Translation.estimatedDocumentCount is not a function

**Workaround**
Use via "collection" property: Model.collection.estimatedDocumentCount()

**Comment by simllll** [comment]
Thanks :) this was quick ;)

**Comment by vkarpov15** [comment]
Happy to help, thanks for reporting :+1:
