### ISSUE TITLE
Bug: Can't create an instance of a model using new mongoose.model('myModel')(data)

### ISSUE THREAD

**Issue by unusualbob** [Automattic/mongoose#6698]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to create an instance of a model using `new mongoose.model('myModel')(data)` results in an error.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/testModelBug', { useNewUrlParser: true });

const Person = new mongoose.Schema({
  name: {
    given: {
      type: String,
      required: true
    },
    family: {
      type: String,
      required: true
    }
  }
});

mongoose.model('Person', Person);

try {
  console.log('This will fail');
  let x = new mongoose.model('Person')({
    name: {
      given: 'Test',
      family: 'Fail'
    }
  });
  console.log('Didn\'t fail');
} catch (e) {
  console.log('Failed:', e);
}

try {
  console.log('This will not fail');
  let Person = mongoose.model('Person');
  let x = new Person({
    name: {
      given: 'Test',
      family: 'Success'
    }
  });
  console.log('Didn\'t fail');
} catch (e) {
  console.log('You should not see this', e);
}

mongoose.modelProxy = function() {
  return mongoose.model(arguments[0]);
};

try {
  console.log('This will also not fail');
  let x = new mongoose.modelProxy('Person')({
    name: {
      given: 'Test',
      family: 'Success'
    }
  });
  console.log('Didn\'t fail');
} catch (e) {
  console.log('You should not see this', e);
}

mongoose.connection.close();
```

**What is the expected behavior?**
It seems like mongoose.model is behaving differently depending on whether or not `new` is used. In reality it should just be returning the model here and not care.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose 5.2.1
node 8.9.1
mongo 3.0.15

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap

**Comment by vkarpov15** [comment]
Unfortunately there isn't much mongoose can do about this. `new mongoose.model(foo)(bar)` is equivalent to `(new mongoose.model(foo))(bar)`, so you lose the context. As a workaround, do `mongoose.model(foo)(bar)` without the `new`, or `new (mongoose.model(foo))(bar)`
