### ISSUE TITLE
GridFSBucket helper

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6703]
Currently, in order to create a GridFSBucket, you need to use the native driver directly to get it done:

### gfs.js
```js
#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;

function saveFile(b, p) {
  return new Promise((resolve, reject) => {
    fs.createReadStream(p)
      .pipe(b.openUploadStream(path.basename(p)))
      .on('error', function (err) { reject(err); })
      .on('finish', function (file) { resolve(file); });
  });
}

async function run() {
  await conn.dropDatabase();
  let opts = {
    bucketName: 'Movies'
  };
  const bucket = new mongoose.mongo.GridFSBucket(conn.db, opts);
  let res = await saveFile(bucket, '/Users/lineus/test.mov');
  console.log(res);
  return conn.close();
}

run();
```
### Output:
```
$: ./gfs.js
{ _id: 5b44ad3daae1c11b7c550db7,
  length: 40499139,
  chunkSize: 261120,
  uploadDate: 2018-07-10T12:57:35.226Z,
  filename: 'test.mov',
  md5: '20a78a40fbdac4c850967da496f1b3a8' }
$:
```

It would be nice to have a helper ( **at the connection level** )? to get this done. So that we could instead call

```js
  const bucket = new conn.GridFSBucket(opts);
```

**Comment by vkarpov15** [comment]
Worthwhile idea, at least for a plugin. GridFS isn't a very common use case for mongoose, which is why we don't have good support for it. Are you interested in writing a plugin for this?

**Comment by lineus** [comment]
yeah, that sounds like fun. I didn't have a need for it myself, just helping someone out somewhere, heh, I can't remember where :smile: the gitter channel maybe?

**Comment by LeonardoFuba** [comment]
i am trying to store jpg,png images in a mongoDB cloud using the node.

https://github.com/LeonardoFuba/store-photo-mongodb

I was successful with the GridStore, but it is deprecated.
I was unable to update my code to GridFSBucket using the @lineus code above.
