### ISSUE TITLE
Calling updateMany() on a mongoose Model does not update values of its discriminator

### ISSUE THREAD

**Issue by jhillejan** [Automattic/mongoose#6704]
**Do you want to request a *feature* or report a *bug*?**
Report a bug (I might be wrong, but I could not find anything about this certain behavior in the documentation or elsewhere)

**What is the current behavior?**
Calling updateMany() on a mongoose Model does not update values of its discriminator (in my case an array property), but model.collection.updateMany() does.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require('mongoose');

const { ObjectId } = mongoose.Schema.Types;

const baseSchema = mongoose.Schema({
  title: {
    type: String,
    required: true,
  },
}, { discriminatorKey: 'type' });

const Base = mongoose.model('Base', baseSchema);

Base.discriminator(
  'sub',
  new mongoose.Schema({
    someArray: [{
      type: ObjectId,
      default: [],
    }],
  }, { }),
);

(async () => {
  // 1) Call `updateMany()` on the model directly (this does not work)

  // Create an object
  const createdDocument1 = await Base.create({
    title: 'some title',
    type: 'sub',
    someArray: [mongoose.Types.ObjectId('5b3a1dc17381ba9a574f62d7')],
  });
  console.log('createdDocument1', createdDocument1);

  // Update the object
  const result1 = await Base.updateMany(
    {  },
    { $pull: { someArray: { $in: [mongoose.Types.ObjectId('5b3a1dc17381ba9a574f62d7')] } } },
  );
  console.log('result1', result1); // { ok: 0, n: 0, nModified: 0 }


  // 2) Call `updateMany()` on the collection property of the model (this works)

  // Create another object
  const createdDocument2 = await Base.create({
    title: 'some title',
    type: 'sub',
    someArray: [mongoose.Types.ObjectId('5b44a0020d03081718aebde0')],
  });
  console.log('createdDocument2', createdDocument2);

  // Update the object
  const result2 = await Base.collection.updateMany(
    { },
    { $pull: { someArray: { $in: [mongoose.Types.ObjectId('5b44a0020d03081718aebde0')] } } },
  );
  console.log('result2', result2.result); // { n: 2, nModified: 1, ok: 1 }
})();
```
**What is the expected behavior?**
Values of "someArray" in the discriminator "sub" should be updated (in this case the array should be empty afterwards).

The behavior of Base.collection.updateMany(...) is correct.

**Please mention your node.js, mongoose and MongoDB version.**
node.js 9, mongoose 5.0.17, mongoDB 3.6.5

**Comment by vkarpov15** [comment]
Use `Base.discriminator('sub').updateMany()` instead. Mongoose doesn't handle casting paths defined in the discriminator when running a query on the base model, and I don't think there's a good way to do that because what if two discriminators have a `someArray` path with different types?

**Comment by vkarpov15** [comment]
You can also work around this with:

```
const result1 = await Base.updateMany(
    {  },
    { $pull: { someArray: { $in: [mongoose.Types.ObjectId('5b3a1dc17381ba9a574f62d7')] } } },
    { strict: false }
  );
```

**Comment by arch1995** [comment]
> Use `Base.discriminator('sub').updateMany()` instead. Mongoose doesn't handle casting paths defined in the discriminator when running a query on the base model, and I don't think there's a good way to do that because what if two discriminators have a `someArray` path with different types?

If I use this, I am getting the below error
```
 You must pass a valid discriminator Schema
```
How do I get around this? I want to use updateMany with Discriminators and passing 
`{ strict: false }` is not an option for me.

Thanks

**Comment by vkarpov15** [comment]
@arch1995 my mistake, you should use this:

```javascript
mongoose.model('sub').updateMany()
```

Or one of several other approaches for getting the discriminator model.
