### ISSUE TITLE
Search in Mongoose api documentation

### ISSUE THREAD

**Issue by imromec** [Automattic/mongoose#6706]
**Do you want to request a *feature* or report a *bug*?**
*feature*
**What is the current behavior?**
There is no way to search/find the mongoose web doc. And because of user needs to spend some time to reach that API documentation and go through that.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Having this feature will reduce the browsing time for a developer.
**Please mention your node.js, mongoose, and MongoDB version.**
Mongoose 5.2.1 (http://mongoosejs.com/docs/guide.html)

**Comment by vkarpov15** [comment]
Good suggestion, will add. Thanks.

**Comment by vkarpov15** [comment]
@thewizarodofoz does jekyll-algolia work if you don't use jekyll? Mongoose definitely does not.

**Comment by thewizarodofoz** [comment]
Sorry, for some reason I thought Mongoose docs was based on GitHub Pages. My bad.

**Comment by vkarpov15** [comment]
It is based on GitHub pages, but you can use GitHub pages without Jekyll
