### ISSUE TITLE
Node process does not exit correctly with mongoose index

### ISSUE THREAD

**Issue by rap2hpoutre** [Automattic/mongoose#6707]
**Do you want to request a *feature* or report a *bug*?**

Bug. Node process does not exit correctly with mongoose index.

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

Running this script with node:

```
const mongoose = require('mongoose')
const FooSchema = new mongoose.Schema({
    name: {type: String, required: true}
})
FooSchema.index({name: 'text'})
const Foo = mongoose.model('Foo', FooSchema)

mongoose.connect('mongodb://localhost/foo')
mongoose.disconnect()
```

Results in:

> MongoError: topology was destroyed

But if I remove the `index` line, I have no error:

```
const mongoose = require('mongoose')
const FooSchema = new mongoose.Schema({
    name: {type: String, required: true}
})
const Foo = mongoose.model('Foo', FooSchema)

mongoose.connect('mongodb://localhost/foo')
mongoose.disconnect()
```

_It seems I can not disconnect mongoose if I use an index._

**What is the expected behavior?**

No error with `mongoose.disconnect()` even if I use an index.

**Please mention your node.js, mongoose and MongoDB version.**

 - mongoose: ^5.1.7
 - node: v10.4.0
 - MongoDB shell version v3.6.5

An issue was posted here: https://stackoverflow.com/questions/51142490/node-process-does-not-exit-with-mongoose-index

**Comment by lineus** [comment]
@rap2hpoutre you are calling disconnect without waiting for the index to be built on the DB. [Model.ensureIndexes](http://mongoosejs.com/docs/api.html#ensureindexes_ensureIndexes) will handle this for you. Here are some examples of using `Model.ensureIndexes()`.

## An async function on the `open` event:
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const FooSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

FooSchema.index({ name: 'text' });

const Foo = mongoose.model('Foo', FooSchema);

mongoose.connect('mongodb://localhost/foo');

mongoose.connection.on('open', async function () {
  await Foo.ensureIndexes();
  return mongoose.disconnect();
});
```
### Output
```
issues>: ./6707.js
issues>:
```
## An async callback passed into `.connect()`
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const FooSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

FooSchema.index({ name: 'text' });

const Foo = mongoose.model('Foo', FooSchema);

mongoose.connect('mongodb://localhost/foo', async function () {
  await Foo.ensureIndexes();
  return mongoose.disconnect();
});
```
### Output:
```
issues>: ./6707.js
issues>:
```
## An async function 
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const FooSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

FooSchema.index({ name: 'text' });

const Foo = mongoose.model('Foo', FooSchema);

async function run () {
  await mongoose.connect('mongodb://localhost/foo');
  await Foo.ensureIndexes();
  return mongoose.disconnect();
}

run();
```
### Output:
```
issues: ./6707.js
issues:
```

## nested callbacks
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
const FooSchema = new mongoose.Schema({
  name: { type: String, required: true }
});

FooSchema.index({ name: 'text' });

const Foo = mongoose.model('Foo', FooSchema);

mongoose.connect('mongodb://localhost/test', function(err) {
  if (err) { return console.error(err); }
  Foo.ensureIndexes(function(err) {
    if (err) { return console.error(err); }
    return mongoose.disconnect();
  });
});
```
### Output:
```
issues: ./6707.js
issues:
```

**Comment by vkarpov15** [comment]
Gonna reopen this, might be a bug and worth investigating more.

**Comment by golfadas** [comment]
Per @lineus comment, disconnecting mongoose only after all indexes are created fixed this issue while running tests within `Jest` with `MongodbMemoryServer` (one db is setup and destroyed per test file)

Instead of disconnecting on model at a time, this can be done dynamically with:

```
await Promise.all(mongoose.modelNames().map(model => mongoose.model(model).ensureIndexes()));

await mongoose.disconnect();
```
