### ISSUE TITLE
countDocuments missing in Typescript type definitions

### ISSUE THREAD

**Issue by ondratra** [Automattic/mongoose#6709]
In package @typed/mongoose is missing definitions for countDocuments. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts

Types missing are available in native mongodb package and can be seen here .
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/981fcd2f64b4e8f1d8991b0a0697029d61235997/types/mongodb/index.d.ts#L504

Can somebody add relevant definitions, please?

**Comment by lineus** [comment]
@ondratra mongoose doesn't maintain typescript definitions. you can open an issue in the repository that you mentioned [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new).
