### ISSUE TITLE
Save with populated reference not working

### ISSUE THREAD

**Issue by civilatio** [Automattic/mongoose#6714]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If i save a document with a reference populated, this does not work as intended. I have kind of an entity hierarchy, where each entity has an attribute "parent.item" and "parent.kind". But this is _not_ set as required.
In the failing example, the entity is a mongoose document with its parent populated. The parent is the root entity with no parent attribute.

This is the coding:

    static saveUpdatesWithConcurrency(entity, updates, user) {
        ControllerHelper._checkLockingVersion(entity, updates);
        updates.lockingVersion = new mongoose.Types.ObjectId();
        updates.lastUpdate = {
            alias: user.alias,
            date: Date.now()
        };
        entity.set(updates);
        return entity.save();
    }

If the coding executes i get: `error:  ValidationError: parent.item: Path `parent.item` is required.
    at new ValidationError`

If i change the coding to the following, everything works fine:

    static saveUpdatesWithConcurrency(entity, updates, user) {
        ControllerHelper._checkLockingVersion(entity, updates);
        updates.lockingVersion = new mongoose.Types.ObjectId();
        updates.lastUpdate = {
            alias: user.alias,
            date: Date.now()
        };

        entity.parent.item = entity.parent.item._id;

        entity.set(updates);
        return entity.save();
    }

This was not the case in mongoose version 4.x. The coding worked fine with MongoDB 3.6 and mongoose 4.x.

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 8.9.4, mongoose: 5.2.3, MongoDB: 4.0.0

**Comment by lineus** [comment]
@civilatio it's hard to say what's going on here exactly without a more complete code sample. What do your schema look like? What options are you populating with?

**Comment by civilatio** [comment]
All schemas have this part included:

    parent: {
        kind: {
            type: String,
        },
        item: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            refPath: 'parent.kind'
        }
    }

in a concrete example i select a a Role and pass the req.body after some validation (it is only possible to change some description fields, but not the parent for example) to the saveUpdatesWithConcurrency method:

    let role = (await Role.findById(req.params.roleId).withParent())[0];
    [...]
    role = await ControllerHelper.saveUpdatesWithConcurrency(role, req.body, req.requester);

The withParent-method is a custom query:

    RoleSchema.query.withParent = function (fields) {
    return this.find({}).populate({
        path: 'parent.item',
        select: fields ? fields : 'active parent title',
        populate: {
            path: 'perms',
            options: {lean: true}
        }
    });
    };
