### ISSUE TITLE
Post create - hook

### ISSUE THREAD

**Issue by gitfy** [Automattic/mongoose#672]
Hi,
At the moment, there is a hook for the post init which gets called when a document is loaded from the DB.

Is there a possibility to get a hook for newly created documents, which could be used for example to default certain properties of the document based on some configuration data ???

Thanks.

**Comment by akshaypuradkar** [comment]
@bradynpoulsen, not exactly! the pre-save is called after thing.save() whereas the pre-create is called right after new ThingSchema()

**Comment by puradawid** [comment]
I am looking for something which allows me create a hook after creating an instance of model. Mongoose-lifecycle is only supporting `save()` post and pre which is not really comfortable for me. Does Mongoose supports such hooks?

**Comment by vkarpov15** [comment]
Take a look at the schema.queue function in the api docs, that enables you to queue up functions to execute every time a new document is created. Mongoose uses it internally for hooks but 4.1.0 formally added that to the public facing API

**Comment by ajsharp** [comment]
I think what the OP was looking for (and I'm looking for it too), is to define a callback function to run after the document is created/inserted, *not* every time it is saved. So, something like this:

```js
var UserSchema = new Schema ({
  email: {type: String, unique: true, sparse: true},
});

UserSchema.post('create', function(done) {
  var email = new WelcomeEmail({to: this.email});
  email.send(done);
});
```

**Comment by vkarpov15** [comment]
@ajsharp the below should work. Unfortunately, it's not really possible to make an async post create hook, because creating a new doc is assumed to be synchronous.

```javascript
var UserSchema = new Schema ({
  email: {type: String, unique: true, sparse: true},
});

UserSchema.methods.email = function() {
  var email = new WelcomeEmail({to: this.email});
  email.send();
};

UserSchema.queue('email');
```

**Comment by rmgreenstreet** [comment]
According to vkarpov15's final answer here, the `queue` call should only call the `email` method once, after the document is created.

I'm experiencing that the `queue` call is being called every time the document is interacted with, including `find()` query operations.

Should I open a new issue?

**Comment by vkarpov15** [comment]
@rmgreenstreet yes please :+1:
