### ISSUE TITLE
Mongoose can't write array of Decimal128 values to MongoDB (when using Decimal128 instead of Schema.Types.Decimal128)

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#6720]
If a schema property is an array of decimal128 values, Mongoose creates below error message instead of writing the values into MongoDB.

`ValidationError: validation failed: Cast to Array failed for value...
`

It makes no difference if the values are already cast to Decimal128 or just plain numbers.

---
Node.js 10.5
Mongoose 5.2.3

**Comment by marcelh-gh** [comment]
@lineus thanks for the quick look into this. :-) **your code snippet works indeed.**

mine gets transpiled and I was using just the BSON `Decimal128` type so far instead of Mongoose `Schema.Types.Decimal128`. If you replace `[Schema.Types.Decimal128]` with `[Decimal128]` in your code snippet, you'll get the error.

Using the BSON `Decimal128` type works perfectly fine for single values - only within an array it causes this problem.

**Comment by vkarpov15** [comment]
@marcelh-gh what do you mean by "using just the BSON Decimal128 type"? What does your `package.json` and your `require()` look like?

**Comment by marcelh-gh** [comment]
`import {Decimal128} from "bson" `ends up as `const bson=require("bson")` and `bson.Decimal128`

I wouldn't say this is a Mongoose bug - changed the title already.
What is strange though is the error message claiming that cast to _array_ didn't work..

**Comment by vkarpov15** [comment]
Weird. Can you show me the output of `npm list | grep "mongo"` and `npm list | grep "bson"` for your repo? Also, looks like you're using a transpiler, can you clarify which one you're using and how its configured?

**Comment by marcelh-gh** [comment]
using Decimal128 from the bson module also causes other problems since Mongoose 5.2.9.
Just using Decimal128 from the mongodb module solves all problems. :-)
The issue of the op seems to have been more related to the Decimal128 from bson than to arrays of it in Mongoose.
Therefore I'll close this issue.
