### ISSUE TITLE
Mongoose - error: UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by Carlavn84** [Automattic/mongoose#6721]
I am using: 
var versions = [{mongoose: 5.2.3}, {nodejs: 8.11.1}]. 

When i was trying to insert data into Mongoose with codes as below: 

mongoose.connect('mongodb://<dbuser>:<dbpassword>@ds137661.mlab.com:37661/mytodoapp', {useNewUrlParser: true});  

var todoSchema = new mongoose.Schema({   item: String }); 
 var Todo = mongoose.model('Todo', todoSchema); 
var itemOne = Todo({item: 'buy a cat'}).save(function(err){  
 if(err) throw err;   
console.log('item saved'); }).
I got errors: 
"(node:13452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:13452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code." 

 How can I deal with this issue? Tks!

**Comment by lineus** [comment]
Maybe try adding the new keyword?

‘var itemOne = Todo(‘

Should be

‘var itemOne = new Todo(‘
