### ISSUE TITLE
Inconsistent `this` in getters of schema types

### ISSUE THREAD

**Issue by daltones** [Automattic/mongoose#6726]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
As of `5.2.3`, _getters_ of schema types have inconsistent `this` context.

Before that release we used to assume that `this` would be the instance of `Model`. Now, when a path has a getter and is populated by a `ref`, at some point that getter is invoked with `this` being the plain object `doc`.

I couldn't found in the documentation that the old behavior is a public API, but having two calling contexts for getters is a bit messy.

Unfortunately my application depended on the old behavior. :disappointed:

I've found that this issue was introduced here: https://github.com/Automattic/mongoose/pull/6702/files#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR3947

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const BarSchema = new mongoose.Schema({});
const Bar = mongoose.model('Bar', BarSchema);

const FooSchema = new mongoose.Schema({
  bar: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Bar',
    get(value) {
      console.log(this.constructor.name); // sometimes it prints `model`, sometimes `Object` 
      return value;
    },
  },
});
const Foo = mongoose.model('Foo', FooSchema);

const bar = new Bar();
await bar.save();

const foo = new Foo({bar: bar});
await foo.save();

const fooWithPopulate = await Foo.find({_id: foo._id}).populate('bar');
fooWithPopulate.bar;
```

**What is the expected behavior?**
`this` in a getter function should always be the instance of `Model`.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v10.6.0
mongoose: v5.2.3
MongoDB: v3.6.1

**Comment by lineus** [comment]
Thanks for reporting @daltones :)
