### ISSUE TITLE
Trying to connect to mongodb locally gives this error

### ISSUE THREAD

**Issue by thetinygoat** [Automattic/mongoose#6727]
im trying to connect to mongodb and follwing error occurs

~~~
{ err: 'socketHandler',
  trace: '',
  bin: undefined,
  parseState:
   { sizeOfMessage: 1347703880,
     bytesRead: undefined,
     stubBuffer: undefined } }
~~~

here is the code im trying to run
~~~javascript
const mongoose = require('mongoose');
const db = "mongodb://localhost:8080/collabmelon";

mongoose.Promise = global.Promise;
mongoose.connect(db, { useNewUrlParser: true })
    .then(res => console.log("Connected to DB"))
    .catch(err => console.log(err));

module.exports.user = require('./user');
~~~

**Comment by NCMoseley** [comment]
I am having the same issue. I will update if I find a resolution. Good luck

**Comment by NCMoseley** [comment]
I found that I had to specify the port correctly: 

mongodb://localhost:27017/DATABASE_NAME.

my code: 

mongoose
  .connect(
    'mongodb://localhost:27017/auth',
    { useNewUrlParser: true }
  )
  .then(() => console.log('MongoDB Connected'))
  .catch(err => console.log('Mongo Error:'));

Good luck

**Comment by thetinygoat** [comment]
Yeah I figured it out.

**Comment by wagnermaciel** [comment]
What do you mean by "I had to specify the port correctly"? I'm also experiencing this issue.

**Comment by NCMoseley** [comment]
> What do you mean by "I had to specify the port correctly"? I'm also experiencing this issue.

my original path was: 

`mongoose.connect( **'mongodb://localhost:auth/auth'**) `

I swapped `auth/auth` for `21017/auth`

**Comment by wagnermaciel** [comment]
Hmm, that's interesting. I've been defining my port this entire time but I'm still getting that error.

```
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:3000/test', { useNewUrlParser: true });
const connection = mongoose.connection;
connection.on('error', (error) => {
  console.log('Error connecting to MongoDB', error);
});

connection.once('open', () => {
  console.log('Connected to MongoDB');
});
```

**Comment by wagnermaciel** [comment]
Figured it out! I had forgotten to start the database in a separate terminal window. Thanks for your help, @NCMoseley !!!

**Comment by JacquesGarre** [comment]
If anyone here didn't solve his problem by changing the port, try replacing 'localhost' with '127.0.0.1'. It worked for me, after 1 hour searching for a solution.

**Comment by vkarpov15** [comment]
Sorry for the trouble @JacquesGarre . For posterity, [here's the answer in the docs](https://mongoosejs.com/docs/connections.html)
