### ISSUE TITLE
Override default timestamp (for testing)?

### ISSUE THREAD

**Issue by RobinJayaswal** [Automattic/mongoose#6728]
Just wondering if there is a way to bypass the default updatedAt property on a mongoose model. For testing some functionality that depends on time periods I would like to pretend that an object was last updated some number of hours ago. 

The following seems to still just save an updatedAt of current time, which is of course expected behavior, but I'm curious as to how I might go about overriding it.

```
 User
 .findOneAndUpdate({_id: userId}, {'streak.numDays': CURR_STREAK, 'streak.updatedAt': twentyFourBack.toDate()})
```

Desired: User has updatedAt property of 24 hours ago.

Actual / probably expected: User has updatedAt property of time test is run.

Any ideas for how I could do this?

**Comment by lineus** [comment]
@RobinJayaswal in your `findOneAndUpdate()` call, try setting the option `{ overwrite: true}`

```js
  let cond = {_id: userId};
  let update = {
    'streak.numDays': CURR_STREAK,
    'streak.updatedAt': twentyFourBack.toDate()
  };
 User.findOneAndUpdate(cond, update, opts)

**Comment by vkarpov15** [comment]
RIght now the only way to do this is to update the document in the database using [`findOneAndUpdate()`](http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate) or [`updateOne()`](http://mongoosejs.com/docs/api.html#query_Query-updateOne). We'll add a `mongoose.now()` function that you'll be able to stub out for Mongoose 5.3.
