### ISSUE TITLE
MongoError: Topology was destroyed   ... 

### ISSUE THREAD

**Issue by Yangk030208** [Automattic/mongoose#6730]
This error occurred, a classic mistake. I tried a lot of methods, but they were useless. [
（link）](https://stackoverflow.com/questions/30909492/mongoerror-topology-was-destroyed)

OS： Ubuntu 16.04 LTS
Nodejs:9.8.0
mongodb:4.0.0
mongoose:5.0.10

this is my code ,simple enough,

`  "mongoose":{
   "uri":"mongodb://127.0.0.1/grow",
   "options":{
          }
  },

    mongoose.connect(config.uri,config.options);
`

who can help me ? thank you

**Comment by lineus** [comment]
@Yangk030208 if you're connecting to a mongodb 4 server, you will probably be better off with mongoose@5.2.3.

It's hard to say what's going wrong without a more complete example. Here is one that you can start from to create a complete example that demonstrates what you are experiencing.

### 6730.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gh6730', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'one' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne();
  console.log(doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6730.js
{ _id: 5b4c8aa5fbe1bd1a3f3bf862, name: 'one', __v: 0 }
issues:
```
