### ISSUE TITLE
StrictModeError when updating document with virtuals in the update doc

### ISSUE THREAD

**Issue by mark-langer** [Automattic/mongoose#6731]
***Feature* or *bug*?**
Bug

**Current behavior?**
When retrieving a document from mongoose including virtual getter values and saving that exact document, a validationError is thrown (schema config set to [strict = 'throw'](http://mongoosejs.com/docs/guide.html#strict)).

**Steps to reproduce.**
```
const InvoiceSchema = new mongoose.Schema({
    _id:      String,
    total:    Number, 
 }, {
    strict: 'throw'
});

InvoiceSchema.virtual('valueAddedTax')
    .get(function () {
        return this.total * 0.19;
    });
```

Mongoose will return a document of this shape:
```
{
    _id: '123456abc',
    total: 1000.00,
    valueAddedTax: 190.00
}
```
This is correct. However, it will throw an error ( ~ `Validation Error: 'valueAddedTax' is not in schema`) when saving that document. Defining a `set` virtual does not change this behavior.

**Expected behavior?**
To my mind, mongoose should know that the `valueAddedTax` property came from a virtual and just drop it (or use the set virtual if defined) instead of throwing an error. This could be accomplished by looping over all virtual getters and remove the properties before saving.

We implemented this behavior manually like so:
```
for (const virtualName in schema.virtuals) {
   context = discard(virtualName)(context);
}
```

What do you guys think about this? Shouldn't this be a task delegated to mongoose?

**node.js, mongoose and MongoDB version.**
Node: 8.9.4
Mongoose: 5.2.3
MongoDB: 3.4.10

**Comment by mark-langer** [comment]
@lineus Thank you for the blazing fast reply.

I figured out the case in which the bug is thrown. It's when I use `Model.update()`, in this case `Test.update()`.

This is the code:

```javascript
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  _id: String,
  total: Number
}, { strict: 'throw' });

schema.set('toObject', {virtuals: true, getters: true});
schema.virtual('valueAddedTax').get(function() {
  return this.total * 0.19;
});

const Test = mongoose.model('test', schema);

const test = new Test({
    _id: '123456abc',
    total: 1000
  });

async function run() {
  console.log(`Mongoose: ${mongoose.version}\n`);

  // clear database
  await conn.dropDatabase();

  // Create first Test record
  await test.save();

  // Check what has been saved
  let doc = await Test.findOne();
  console.log('initial doc:\n\n', doc);


  // run update
  await Test.update({_id: '123456abc'}, { // <<<------ Error
    total: 1200,
    valueAddedTax: 500
  }).catch((e) => console.error(e));

  // Check what has been saved
  const updateDoc = await Test.findOne();
  console.log(`Updated Doc: `, updateDoc);

  return conn.close();
}

run();
```
To my mind, Mongoose should treat this update in a similar way as if I called Test.save() with a `valueAddedTax` property. What do you think?

**Comment by lineus** [comment]
I think that this behavior makes sense. This property doesn't exist on the schema but rather as a virtual which doesn't get stored in the db. When you try to add the property to a document in the db the `StrictModeError` should apply.

**Comment by mark-langer** [comment]
Thanks for updating the title. It reflects the actual case much better now!

I agree that there should be an error if you try to save a property that is *completely* outside the schema. But a virtual is sort of part of a schema since it is defined on it, right? I figure that's why calling `save()` on a model won't trigger the error.

The scenario in which this causes problems is when a client wants to modify a document:

1. Client asks web server for document (including virtuals)
1. Client modifies document
1. Client sends modified document back to server, with server using the `Model.update()`-method ---> Validation error

If the server now takes the same steps (read, modify, save), the virtual property does not trigger the error. It would appear a more consistent behavior if the `update` and `save` routines would work the same way here.

The `save` method seemingly already has a routine to filter out virtuals. Wouldn't it be possible to adapt that for the `update` method too?

**Comment by mark-langer** [comment]
@lineus Do you agree with the point I made?

**Comment by lineus** [comment]
@vkarpov mark makes a good point. What are your thoughts?

**Comment by vkarpov15** [comment]
I agree, your point is very solid. We'll fix this within the next couple weeks :+1:
