### ISSUE TITLE
countDocuments is missing in index.d.ts (only count available)

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#6733]
```
@types/mongoose 5.2.0
Node.js 10.5
Mongoose 5.2.3
```

**Comment by lineus** [comment]
Hi @marcelh-gh, mongoose doesn't maintain typescript definitions, but [there is already a PR opened for countDocuments with definitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27283) (the folks that do maintain them). Hopefully it will get published soon 👍

**Comment by marcelh-gh** [comment]
oh, sorry. next time I'll check with them directly. Thank you.

**Comment by lineus** [comment]
No worries! Here’s hoping it gets resolved quickly :)
