### ISSUE TITLE
minimize: false defaults sub-schema values to empty json

### ISSUE THREAD

**Issue by vinaykhebbar** [Automattic/mongoose#6734]
Do you want to request a *feature* or report a *bug*?
Bug

What is the current behavior?
I am currently having the below schema:

var TestSchema = new Schema({
    x: Schema.Types.Mixed
}, {minimize: false})

TestSchema.add({
y: { z: String}
})

When I create a new document using the above schema definition - 
new Test({x: {a: 1, b: {}}})
It's creating the document in the below format - 
{x: {a: 1, b: {}}, y: {}}

Without minimize property the document will be saved as {x: {a: 1}}.
We have a scenario where we don't want the sub-schema(y) to be populated with {} but want the mixed fields to retain the empty object.

What is the expected behavior?
The sub-schema fields should not get defaulted to empty object if they are not set.

**Comment by lineus** [comment]
This doesn't appear to be a bug, `minimize: false` is [behaving as expected](http://mongoosejs.com/docs/guide.html#minimize).

You can however, control the behavior of `y`, by assigning it a default of undefined:

### 6734.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gh6734', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;
const Mixed = Schema.Types.Mixed;

const ySchema = new Schema({
  z: String
});

const schema = new Schema({
  x: Mixed
}, { minimize: false });

schema.add({ y: { type: ySchema, default: void 0 } });

const Test = mongoose.model('test', schema);

const test = new Test({ x: { a: 1, b: {} } });

console.log('javascript doc:\n', test);

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.collection.findOne();
  console.log('mongodb doc:\n', doc);
  return conn.close();
}

run();
```
### Output:
```
issues: ./6734.js
javascript doc:
 { _id: 5b4ddcddf75df01335178761, x: { a: 1, b: {} } }
mongodb doc:
 { _id: 5b4ddcddf75df01335178761, x: { a: 1, b: {} }, __v: 0 }
issues:
```
