### ISSUE TITLE
.save() very slow in mongoose 5+ when running in webpack with source maps

### ISSUE THREAD

**Issue by solgarius** [Automattic/mongoose#6735]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
My server script is built using webpack and I run my tests using mocha-webpack module. 
This module automatically creates source map files, and we also do this for production and normal development (albeit without source maps included in production). 
When I run my tests in mongoose 5.2.4 each call to .save (e.g. via a create) results in the save taking at least 1.5 seconds. 
In production it is taking closer to ~20ms

In mongoose 4.13.14 in both cases its closer to ~2-3ms

It seems from doing a `--inspect` on the server that all of the time is being spent generating the stack trace which is created for every save call. The stack trace causes the source-map-plugin to generate a stack trace based on the js source map.

looking at the code in `lib/model.js` it seems this was added for Automattic/mongoose#2633 so that `VersionError` could better show where it was generated. It appears that `ParallelSave` is now also generating a stack trace.

Is it possible to add an option to mongoose to switch off these stack traces being generated as it is prohibitively expensive for very large code bases.

**If the current behavior is a bug, please provide the steps to reproduce.**
difficult to reproduce as it would mostly only be exacerbated by large code bases.

**What is the expected behavior?**
Either don't generate stack traces at all or add a config option to disable the stack trace generation. Note sure how it would work with the parallel save error though.

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose 5.2.4
mongoDB 3.4 with driver 3.1.1
node.js 8.9.4

**Comment by solgarius** [comment]
Its going to be difficult to share our webpack config as its a huge project, but I'll see if I can come up with a simplified one that will reproduce this, though I suspect its due to the size of the project and resulting source map files that causes this to be such a clear issue.

So `new Error()` is not actually the slow part, its the `.stack` calls on the error, as the stack is lazily generated because it is an expensive operation. So we generally don't have this issue very often because the stack is only needed when there's an actual error in the system where we need to report the stack trace, typically no worse than once every few minutes and generally much rarer in production.

In the case of the `.save()` call every mongoose write, a new stack trace is getting generated (well two actually, one for `$__.saving` and one for `originalStack`). Our system does many writes, usually a few hundred per second, so even in production the extra 10-20ms adds up really quickly. I would guess even if we weren't using webpack, there's still the 10-20ms hit here as a stack trace on a minified file (without a source map) would be similar to a non-webpacked stack trace in terms of this performance hit.

I do understand the value of having the `originalStack` for debugging purposes, and this is why I suggest a flag, as it could be handy for many people to switch this off in production to give faster performance while switching it on in development for easier debugging.

As for the `ParallelSaveError`, this one I'm not sure what the solution should be to have a similar purpose to what is intended, though I do note at the moment as far as I can tell the error is not actually used anywhere, and the `$__.saving` value is practically ignored. But I presume its also a case of handy to know about in development and possible to switch off in prod.

**Comment by solgarius** [comment]
I'm not sure that fix will have the desired outcome. As the stack trace is generated based on when the `.stack` call happens, the stack trace will once again be in the callback and not in the original call. I could be wrong though.

**Comment by vkarpov15** [comment]
Let's give this a shot and see if it helps. If not, I'll try to replicate your webpack setup and see if there's something we can do. Based on your comments, I assumed you meant the `.stack` getter was what was slow, not the `new Error()` call.

**Comment by solgarius** [comment]
Oh sorry, it is the stack getter that is slow. What I mean is that I'm pretty sure the stack getter reports the stack at the time the stack getter is called. So by not calling it anymore the stack will just be the stack at the time of the callback not of the original call.

The previous code records the stack at the time of calling `.save`, with presumably the intent that mongoose will show the Dev which save call it was that caused the version error.

So this new code should be fast but I think it will lose the context of the stack, causing a regression on the original bug it was meant to fix. But I will test tomorrow to make sure and see if i can think of any solution that might work.

I'm pretty sure that from node 10+ if async/await was used it would be okay, but that obviously would lock mongoose to node 10+ which I doubt that you want. 

I'm hopeful that the fix you did does keep the context though as that would be super useful and performant.

**Comment by vkarpov15** [comment]
Glad your issue is fixed, happy to help!

Unfortunately async/await wouldn't help with this particular stack trace error, we still need to record the error when the function is called in order to provide a meaningful stack trace. Async functions don't help with long stack traces.
