### ISSUE TITLE
Mongoose "converts" string to ObjectId for properties of type ObjectId

### ISSUE THREAD

**Issue by Ncifra** [Automattic/mongoose#6742]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When sending a string value that is 12 characters long, the "ObjectId" validation seems to be bypassed. We have tried with "Select Type:" and "Select Typ18" (not that they should be relevant I think), and these values are "saved| as ObjectId's inside the schema. The ObjectId's are actually random, even though that actual property refers to an external id from another schema.

**If the current behavior is a bug, please provide the steps to reproduce.**
I think the above description is explanatory.

**What is the expected behavior?**
An error of "Cast to ObjectID failed for value ..." should be thrown.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 6.9.1
Mongoose: 4.13.11
MongoDB: 3.4

**Comment by lineus** [comment]
@Ncifra please see #1959 for an explanation of why this isn't a bug. We should add this to the FAQ. I'm leaving this open to track that.

**Comment by Ncifra** [comment]
Yes, I expected this to be something "normal", considering the stored ObjectID's are 24 characters long, while this one is half, so there was some relation.
