### ISSUE TITLE
Validation doesn't continue in arrays with objects after first failure

### ISSUE THREAD

**Issue by martypdx** [Automattic/mongoose#6746]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Validation will not continue after one object of array has validation errors. Validation does continue when array contains primitives.

**If the current behavior is a bug, please provide the steps to reproduce.**
[Tests showing current behavior with bug](https://gist.github.com/martypdx/2a169b71b0a8d81b49014d85e0aea9f5)

**What is the expected behavior?**
Third test passes, both failed objects of array reported in validation

**Please mention your node.js, mongoose and MongoDB version.**
* mongoose 5.2.4
* node 10.3.0

**Comment by vkarpov15** [comment]
We'll add a flag to opt in to this is a future release, thanks for reporting.

**Comment by vkarpov15** [comment]
Upon further inspection, this only affects `validateSync()`, so we'll just fix it in 5.3.15.
