### ISSUE TITLE
Model.aggregate() session

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6752]
According to the docs `Model.aggregate()` doesn't accept any `options` object:

<img width="528" alt="screen shot 2018-07-22 at 16 10 47" src="https://user-images.githubusercontent.com/5895458/43046496-d5bce000-8dc9-11e8-9ea3-a8ebea879f78.png">

It also returns `Aggregate` instance which doesn't have a `session()` setter like `Query`.

Is there a way to run an aggregation query within a transaction?

**Comment by vkarpov15** [comment]
With aggregate, you can do `Model.aggregate().option({ session: session })`, we'll add a `.session()` helper and add this to the docs.
