### ISSUE TITLE
Text Search on Mongoose schema which references another schema ?

### ISSUE THREAD

**Issue by lyquocnam** [Automattic/mongoose#6757]
I am trying to add an index to fields which are references to other Schemas. For example my model looks like the following:
```js
var Book = new Schema({
        "title": String,
        "createdAt": Date,
        "publisher": {
             "type": Schema.ObjectId,
             "ref": "Publisher"
        },
        "author": {
             "type": Schema.ObjectId,
             "ref": "Author"
        },
        "isbn": String
    });
```
So something like the following indexing doesn't work when you perform a search query as described below:
```js
Indexing: Book.index({"title": "text", "publisher.name": "text", "author.firstName": "text"});
```
Search query:
```js
function searchBooks(req, res) {
    var query = req.query.searchQuery;

    Book.find({ $text: { $search: query } })
        .populate('author publisher')
        .limit(25)
        .exec(function(err, books) {
            if (err) {
                res.json(err);
            } else {
                res.json(books);
            }
        }
    );
}
```
Does anyone have any suggestions of how to add a text index in for the "publisher" and "author" fields, I am using the `populate` mongodb method to pull in the data for these schemas.

**Comment by vkarpov15** [comment]
You can't have an index that references another collection currently. You need to write a separate query to pull publishers matching the text query.
