### ISSUE TITLE
Add `mongoose.Boolean`, `mongoose.ObjectId`, etc. as a replacement for `mongoose.Schema.Types.Boolean`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6760]
Too many dots make code hard to read.

**Comment by sebastian-nowak** [comment]
Something to consider: with this change the difference between `mongoose.ObjectId` and `mongoose.Types.ObjectId` wouldn't be so obvious.

**Comment by vkarpov15** [comment]
Granted. But in my experience people use `mongoose.Schema.Types.ObjectId` far more than `mongoose.Types.ObjectId`. Perhaps if we add an FAQ section on the difference between `mongoose.Types.ObjectId` and `mongoose.ObjectId`?

**Comment by felipevignon** [comment]
If I may add: I don't feel like it's clear AT ALL in the docs what's the difference between mongoose.Types.ObjectId and mongoose.Schema.Types.ObjectId. It's possible that I just missed it but it was quite the challenge understanding when to use each and it took me a few server crashes. Please add a few lines regarding this in api docs!

**Comment by vkarpov15** [comment]
That's a good idea, thanks for your suggestion. In https://github.com/Automattic/mongoose/commit/b68c992ff3d9d23c45803ac431a7faac280817e9#diff-6d186b954a58d5bb740f73d84fe39073 we added some notes about how to use `mongoose.ObjectId` vs `mongoose.Types.ObjectId`. TLDR; `mongoose.ObjectId` is the same as `mongoose.Schema.Types.ObjectId`. `mongoose.ObjectId` is only useful when declaring a schema, it is one of the ways to tell Mongoose that a given path should be casted to an ObjectId.
