### ISSUE TITLE
Schema to require an array which can be empty?

### ISSUE THREAD

**Issue by picklechips** [Automattic/mongoose#6762]
I'd like my schema to require an array which can be empty. Currently I only know how to create an array which is required, but can't be empty - or doesn't have to exist at all. I just want to enforce there is always at least an array object on this field.

Apparently this used to be default behaviour prior to mongoose 5, but now I'm having difficulty figuring out how to achieve this.

**Comment by vkarpov15** [comment]
Actually, [in Mongoose 5 we made it so array `required` allows empty arrays](https://github.com/Automattic/mongoose/blob/master/migrating_to_5.md#required-validator-for-arrays), so you should be able to do this in Mongoose 5.
