### ISSUE TITLE
Throw clean error in `openUri()` if uri is `undefined`

### ISSUE THREAD

**Issue by rockchalkwushock** [Automattic/mongoose#6763]
**Do you want to request a *feature* or report a *bug*?**

I am trying to get a failing service back up and running. After updating to `mongoose@5.2.5` I get the following error message:

```text
UnhandledPromiseRejectionWarning: MongoParseError: URI malformed, cannot be parsed
```

I'm using mLab so my connection string looks like:

```text
mongodb://<user>:<password>@ds227525.mlab.com:27525/dbname
```

```javascript
mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  auth: {
    user: process.env.MONGO_USER,
    password: process.env.MONGO_PASSWORD
  }
})
```

 My question is does `auth.user` and `auth.password` get injected into the user/password part of the connection string? Everything I'm trying is still yielding the error message

node 8.11.1
mongoose 5.2.5
mongoDb 4.0.0

**Comment by rockchalkwushock** [comment]
Is there anyway to return the url so I can see what it looks like? This would be helpful in the debug process.

**Comment by rockchalkwushock** [comment]
I'm confused by this because it works in development with no issues but when running in production the URL is no longer valid. Same URL being used, literally nothing has changed from one environment to the other for the URL.

**Comment by lineus** [comment]
It seems like the value of `process.env.MONGO_URI` in your production environment is different from the one in your development environment, possibly being null or undefined.

>Is there anyway to return the url so I can see what it looks like? This would be helpful in the debug process.

Have you tried inspecting (console.info, etc ) the value of `process.env.MONGO_URI` **in your production environment** right before it's passed into `mongoose.connect()`? 

Something like the following would ensure it's set properly before trying to connect:
```
  try {
    assert.ok(typeof process.env.MONGO_URI === 'string')
  } catch(e) {
    console.error('process.env.MONGO_URI isn't set correctly')
    process.exit(1)
  }
```

What you are seeing can be replicated by explicitly passing null or undefined (*basically anything that isn't a string, ie `{}` or `42`*) as the first argument to `mongoose.connect()`. All of these values have the same output as `null` below:

### 6763.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect(null, { useNewUrlParser: true }).catch(e => {
  console.error(e.message);
});
```
### output:
```
issues: ./6763.js
URI malformed, cannot be parsed
issues:
```

>My question is does auth.user and auth.password get injected into the user/password part of the connection string?

Mongoose's connection code will potentially set connection options based on the connection string, but mongoose doesn't mutate the string based on the options ( or in any way that I'm aware of ).

Just to be sure, I tested mongoose 5.2.5 with my MLab test account and it works without error for me:

### 6763.js
```js
#!/usr/bin/env node
'use strict';

const { MLAB, sharable, MLAB_USER, MLAB_PASS } = require('/Users/lineus/.env');
const mongoose = require('mongoose');
const conn = mongoose.connection;
const opts = {
  useNewUrlParser: true,
  auth: {
    user: MLAB_USER,
    password: MLAB_PASS 
  }
};
mongoose.connect(MLAB, opts).catch(e => {
  console.error(e.message);
});

const Test = mongoose.model('test', { name: String});

const test = new Test({ name: 'one' });

async function run() {
  console.log(`Mongoose: ${mongoose.version}`);
  console.log(`conn string: ${sharable(MLAB)}`);
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne();
  console.log(doc);
  console.log(sharable.toString());
  return conn.close();
}

run();
```
### Output: 
```
issues: ./6763.js
Mongoose: 5.2.5
conn string: mongodb://user:pass@host.mlab.com:port/dbname
{ _id: 5b57146c9cf05b568a68e8c1, name: 'one', __v: 0 }
function (str) {
    return str.replace(/\/\/[\w]+:/, '//user:')
              .replace(/:[\w]+@/, ':pass@')
              .replace(/@[\w]+\./, '@host.')
              .replace(/(net|com):[0-9]{5}/g, '$1:port')
              .replace(/\/[^/]*$/, '/dbname')
  }
issues:
```
*I included the toString() value of sharable to show how I'm mutating my connection string when I print it out here*
Feel free to join us on either [Gitter.im](https://gitter.im/Automattic/mongoose) or [Slack](https://mongoosejsteam.slack.com/) to chat about it in real time.

**Comment by rockchalkwushock** [comment]
@lineus 

You are absolutely right. For whatever reason `process.env.MONGO_URI` evaluates to `undefined` in production. Thank you for taking the time to look at my issue and presenting what was probably happeneing. 🎉 🙏

**Comment by vkarpov15** [comment]
I'll re-open this to track us adding a clean error for this case.

**Comment by sadelokiki** [comment]
Hello, any solution to this yet?

**Comment by chriselliott82** [comment]
I am getting the same error in dev, 

"message: 'The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.',
  name: 'MongooseError'"

**Comment by vkarpov15** [comment]
@chriselliott82 that's the new error message that we added. Please read me the error message and make sure you aren't calling `mongoose.connect()` with no parameters.
