### ISSUE TITLE
The subdocs help is not clear

### ISSUE THREAD

**Issue by lubodrinka** [Automattic/mongoose#6765]
http://mongoosejs.com/docs/subdocs.html
This manual is not have head and foot.
There is no tree. how the schema work.
If I create subdocs follow the manual I cannot add new because the child is undefined in docs, if I create with child as required it say, it had missing path.
 ```
var Schema = mongoose.Schema;
var childSchema  = new Schema({
    // Single nested subdocuments. Caveat: single nested subdocs only work
  // in mongoose >= 4.2.0
description:String,
   duration:Number,
   date:{ type: Date, default:  new Date() }  
});

  
var blogSchema = new Schema(
  { name:  {
    type: String,
    required: true},
   child: childSchema
  
         
});
 
 
var Person = mongoose.model('Person4', blogSchema);
```
And when I want add new values docs.child is undefined
```
app.post("/api/exercise/new-user", function (req, res ) {
   console.log(req.body.username)
   //res.json(req.body,{id:  docs});
var person = new Person({ name: req.body.username})
//var url = req.body.url
Person.findOne({name :req.body.username},                          
  function (err, docs) {
  if(docs) { res.send('username already taken')}
  else{  
  person.save(function(err, docs) {
 if (err) res.json({err:err});
  console.log(docs)
   res.json({name:req.body.username,id:docs._id});
 });    
  }
})
})
```

There are example
```
var Parent = mongoose.model('Parent', parentSchema);
var parent = new Parent({ children: [{ name: 'Matt' }, { name: 'Sarah' }] })
parent.children[0].name = 'Matthew';

```
What is this, what that doing? Is look like as rewrite the  Matt by Matthew, but I only guess.
And how can I know how many are there children? It's look like solid fix schema, but I still make guess. Why any body write manuals without say what he had on mind?

In adding subdocs to array
1. How is look the whole schema?
2. this is not working:
`var newdoc = parent.children.create({ name: 'Aaron' })`;  I can only guess the next step ```
[is newdoc.save(function (err) {
  if (err) return handleError(err)
  console.log('Success!');
});]
```
and the same problem the children is undefined. because no defaults children values exists.

**Comment by vkarpov15** [comment]
I don't understand what your question is, can you clarify what you mean by "the same problem the children is undefined. because no defaults children values exists" with some code samples?

**Comment by lubodrinka** [comment]
That is one thing it si not described. I saw many crazy frameworks and I said that dint work and that did, because of author will he break rules. How can I now is this case you cannot add push to children only to [children]? The [children ] works, but not as classic push expected and that is not described.

the declaration: child: children doesn't work absolutely. from this manual I cannot deciphre how can that work.
It's same as [children]?If yes, why that same logic doesn't  work or get same output?See manual is very poor. There is no usefull example of work code. there is declarations, updating child[0] , but one how to add values.


for other who loos for solutions 

```
app.post("/api/exercise/add", function (req, res ) {
   console.log(req.body)
  

var personId = req.body.userId
Person.findById(personId,                          
  function (err, docs) {
  if(!docs) { res.send('First add new user')}
  else{  
     console.log(docs)
  var date=new Date(req.body.date)
     docs.child.push({description:req.body.description,duration:req.body.duration,date: date})
  docs.save(function(err, docs) {
 if (err) res.json({err:err});
  console.log(docs)
   res.json({description:req.body.description,duration:req.body.duration,date: date.toDateString()});
 });    
  }
})
})
```
