### ISSUE TITLE
Bug? 

### ISSUE THREAD

**Issue by teddis** [Automattic/mongoose#6775]
My server has been running fine for over a year on Mongoose 4.x. I've upgraded to latest Mongoose 5.2.5 with Typescript@2.7.2, @types/Mongoose@5.2.2, Node 9.2.1, and MongoDb 3.6.6. I'm seeing different document casting behavior when retrieving documents. Now documents are retrieved as "model" objects by default instead of expected classes with the generic type when creating the model. I've never had to cast these before. I can't tell if upgrading to Mongoose is the culprit or some bug on my part. This is urgent as all of my code no longer works as before.

Current behavior is to simply return a "model" class. Expected behavior is to return a document with the generic type passed to model function. 

I've also defined instance methods on these classes but can no longer access them since the document object returned is not properly cast. I should not have to cast the document to the desired class. Or is this new undocumented behavior?

```
export class UserClass {
    public email: string = '';
}
const schema = new Schema({
    email: {type: String, index: true, unique: true}
     // additional fields not important/mentioned...
}
export interface TUser extends UserClass, Document {
}
export const UserModel: Model<TUser> = model<TUser>('User', schema);
const user = UserModel.findOne() // user is type "model"
```
Appreciate any insights. Thanks.

**Comment by vkarpov15** [comment]
I don't understand what the issue is here, can you please provide a standalone script that reproduces your issue?
