### ISSUE TITLE
[enhancement] add functionality to accept hash of name/fn pairs to schema.prototype.virtual

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#6778]
Both adding instance or a static methods to a schema/model can be done using a hash of name/function pairs.

It would be great if virtuals could be set up in the same way. Currently they have to be set up one by one.

Mongoose 5.2.4
MongoDB 4.0

**Comment by vkarpov15** [comment]
Good idea, we'll add this for the next minor release.

**Comment by vkarpov15** [comment]
This is trickier than I thought because how would you set up getters/setters? Something like this?

```javascript
schema.virtual({
  v1: { get: function() { /*...*/ }, set: function() { /*...*/ } },
  v2: { get: function() { /*...*/ }, set: function() { /*...*/ } }
});
```

**Comment by vkarpov15** [comment]
I'm going to close this one for now. I don't have a good idea of how this will look syntax-wise.
