### ISSUE TITLE
default with Promise or AsyncFunction 

### ISSUE THREAD

**Issue by Fonger** [Automattic/mongoose#6781]
It would be helpful if the default options accept `AsyncFunction` or `Promise`

Use case:
Automatically generate a new api key when the document is created
generateHexString is a async function that use `crypto.randomBytes` to generate hex asynchronously

```js
new Schema({
  apiKey: { type: String, default: generateHexString, required: true}
})
```

I review some of the implementation and find out that this feature is difficult to implement because the code works synchronously.

Any idea if it is worthy to support this in core? in plugin?
Or we should just use `pre('save', ...)` that has `next` callback to support this?

**Comment by vkarpov15** [comment]
We can't support async defaults without making `new Model()` async, which we can't really do. However, you can do something like this:

```javascript
const schema = new Schema({
  apiKey: { type: String, required: true}
})

schema.pre('save', async function() {
  if (this.apiKey == null) {
    this.apiKey = await generateHexString();
  }
});
```

Does this work for you?

**Comment by Fonger** [comment]
@vkarpov15 Looks great! I didn't know we can use async function in middleware since mongoose v5+

**Comment by nikitkhakholia** [comment]
This did not work...
My code
`var mongoose = require("mongoose");
const { getNextSequenceValue } = require("../Controllers/CountersController");

var siteMstSchema = new mongoose.Schema(
  {
    _id: {
      type: Number,
    },
    name: String,
  },
  { timestamps: true }
);

siteMstSchema.pre("save", async () => {
  console.log(123);
  if (!this._id) {
    this._id = await getNextSequenceValue("siteMst");
  }
});

module.exports = mongoose.model("SiteMst", siteMstSchema);
`

**Comment by vkarpov15** [comment]
@nikitkhakholia it looks like you aren't using defaults at all, so I fail to see how this is related to the issue reported. Please open a new issue and follow the issue template.
