### ISSUE TITLE
Automatic field selections for populated fields causes unexpected behaviors when it's combined with explicit field selections

### ISSUE THREAD

**Issue by Daeik** [Automattic/mongoose#6785]
**Do you want to request a *feature* or report a *bug*?**

Possibly a bug (It might be an expected behavior)

**What is the current behavior?**

Given the case https://github.com/Automattic/mongoose/issues/5669#issuecomment-335088444 already mentioned and is resolved https://github.com/Automattic/mongoose/issues/5669#issuecomment-335895106, it is somewhat similar problem that I'm facing.

**If the current behavior is a bug, please provide the steps to reproduce.**
**What is the expected behavior?**

In the comment where the case(which is solved) was like this:

```js
// Query
Test.find().select('key').populate([ { path: 'key.sub'} ])
// Result
[{ key: [{ sub: {} }] }]
// Expected result (from 4.12.2)
[{ key: [{ sub: {}, other: '' }] }]
```
If you query and populate with following conditions, where considering `key` field has `{ select: false }` option:

```js
// Query
Test.find().select('+key').populate([ { path: 'key.sub'} ]) // '+key' unlike previous case
// Result (5.2.5)
[{ key: [{ sub: {} }] }]
// Expected result
[{ key: [{ sub: {}, other: '' }] }]
```
I think since `.select('key').populate([ { path: 'key.sub'} ])` works as expected from `4.12.2`, `'+key'` should make the same result considering explicit selection of a field implies that you have selected the whole child fields.

For now, I wrote my code to be `.select('+key key').populate([ { path: 'key.sub'} ])`.

**Please mention your node.js, mongoose and MongoDB version.**

Node: 8.1.4
MongoDB: 3.4
Mongoose: 5.2.5 (Latest)

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP

**Comment by Fonger** [comment]
@vkarpov15 I investigate and find that `Query#select` does not support `+` syntax at all. So the field name is `+key` that's why `key` is not selected.

https://github.com/Automattic/mongoose/blob/d4f507f5a1670747ada0529ceafca60e1ff0f717/lib/query.js#L885-L892

I diff the code with `mquery` and find that `select` has exactly the same implementation with `mquery`.
mongoose has duplicate code that overwrites mquery.prototype.select.

**Comment by Daeik** [comment]
@Fonger That is quite strange, I remember there is a syntax for selecting hidden(select: false) fields by using `+` prefix in a select clause. I actually found that there is a comment https://github.com/Automattic/mongoose/blob/master/lib/query.js#L852-L853 in the code which states aforementioned. But it seems like the parts that you highlighted indeed doesn't include `+` a prefix parser.

**Comment by Fonger** [comment]
@Daeik I believe it is just a documentation error. I see [the comment is added on 2013](https://github.com/Automattic/mongoose/commit/bfe9db82306a14f1a087a3ff072d21a377d9a35e) and at that time, it uses `mquery@0.2.4` directly. [`mquery@0.2.4` doesn't support `+` at that time either](https://github.com/aheckmann/mquery/blob/5fdca1edc96662bca23d97652ebe83d56422d559/lib/mquery.js#L1054).

**Comment by Daeik** [comment]
@Fonger Since `+` prefix is deprecated now and considering `.select('key').populate([ { path: 'key.sub'} ])` works as an intended Mongoose specification, I don't think it is needed to bring back `+` prefix.

Though fixing the comment/docs would be nice, since it can mislead Mongoose users. (not that everyone reads code comments 😄)

**Comment by vkarpov15** [comment]
There's some more subtle issues at play here with the '+' syntax. The '+' syntax is _only_ useful if the path is excluded at the schema level (that's why it isn't in mquery, because mquery has no notion of schemas). The point is to add a field that has `select: false` to the query result without changing to an inclusive projection:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh6785`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    name: { type: String },
    age: { type: Number, select: false },
    city: { type: String, select: false }
  });

  const M = mongoose.model('Test', schema);

  await M.create({ name: 'Val', age: 29, city: 'Miami' });

  console.log(await M.findOne()); // { _id: ..., name: 'Val', __v: 0 }
  console.log(await M.findOne().select('age')); //  { _id: ..., age: 29 }
  console.log(await M.findOne().select('+age')); // { _id: ..., name: 'Val', age: 29, __v: 0 }
}
```

So we still need to investigate this issue.
