### ISSUE TITLE
[Feature] Custom query when populating virtuals

### ISSUE THREAD

**Issue by sandrocsimas** [Automattic/mongoose#6787]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Can't make a different query when populating virtuals. If this is already implemented, sorry, I didn't saw this feature on the doc.

**What is the expected behavior?**
I have the following model:
````
const Task = new Schema({
  company: {type: ObjectId, ref: 'Company', required: true, index: true},
  client: {type: ObjectId, ref: 'Client', required: true, index: true},
  name: {type: String, required: true},
  status: {type: String, required: true},
  schedule_date: {type: Date},
  registration_date: {type: Date, required: true},
}, {collection: 'tasks'});
Task.virtual('attachments', {
  ref: 'TaskAttachment',
  localField: '_id',
  foreignField: 'task',
});
Task.virtual('comments', {
  ref: 'TaskComment',
  localField: '_id',
  foreignField: 'task',
});
````
Is there a way to create some custom query in the virtual? I want to do  a lot of things like count, sort, filter, etc...

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.10.0
Mongoose: 5.2.5
MongoDB: 4.1.1

**Comment by vkarpov15** [comment]
Depends on what you want to do. You can do sort and limit using `options`:

```javascript
Task.virtual('attachments', {
  ref: 'TaskAttachment',
  localField: '_id',
  foreignField: 'task',
  options: { sort: { createdAt: -1 }, limit: 5 }
});
```

Do you need something beyond this?

**Comment by sandrocsimas** [comment]
Can you include filters on this option?
Something like:
````
Task.virtual('attachments', {
  ref: 'TaskAttachment',
  localField: '_id',
  foreignField: 'task',
  options: { 
   filters: {status: 'pending'},
    sort: {createdAt: -1 },
    limit: 5
  }
});
````

**Comment by vkarpov15** [comment]
That's a good point, we don't have that right now. Will add that ASAP, that's a meaningful gap in virtual populate's API.

**Comment by kemalcany** [comment]
I believe this feature is not available anymore ? Asking for future reference
