### ISSUE TITLE
Deprecation warning : "mongoose": "5.2.6",

### ISSUE THREAD

**Issue by Sidd27** [Automattic/mongoose#6789]
`mongoose.connect('mongodb://localhost:27017/scraping').then(() => {
      console.log('Database Connected Succesfully');
    })
    .catch(e => {
      console.log(e);
      process.exit();
    });`

DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Comment by lloydst** [comment]
mongoose.connect('mongodb://localhost:27017/scraping', { useNewUrlParser: true } ).then(() => { console.log('Database Connected Succesfully'); }) .catch(e => { console.log(e); process.exit(); });
should be this docs are in need of updates (still reference useMongoClient)

**Comment by vkarpov15** [comment]
Woops, https://github.com/Automattic/mongoose/commit/be190adcb66ccf2dc246e1891187353054d1277e should refer to #6814

**Comment by eylesa** [comment]
`const mongoose=require('mongoose');
mongoose.Promise = require('bluebird');

var mongoDB = 'mongodb://localhost/db_name';

mongoose.connect(mongoDB, { useNewUrlParser: true }).then(
  () => {
   console.log("DB is connect succesful.")
  }
).catch(() => {
  console.log("error!! doesnt connect.");
});`

This is my code. it says "error!! doesnt connect.". pls help!!

**Comment by vkarpov15** [comment]
@eylesa do `var mongoDB = 'mongodb://localhost:27017/db_name';`, add the port number please. The new url parser requires specifying a port.
