### ISSUE TITLE
What is the current behavior of .populate()?

### ISSUE THREAD

**Issue by ErnestoSalazar** [Automattic/mongoose#6790]
Hello everyone, i have a doubt about the **populate** method, and i couldn't find anything that could resolve it.
im using mongo 4 and mongoose 5.2.6,

i was reading that mongo now comes with a **$lookup** that works like a "join" without making extra queries to unify associated documents from other collections, my question is that if .populate does the same thing as $lookup without generating extra queries to retrieve associate data.

thanks in advance

**Comment by vkarpov15** [comment]
No, each `populate()` call means a separate query under the hood. We've considered switching to using `$lookup`, but the performance implications are tricky and `populate()` supports certain features that $lookup does not.

**Comment by ErnestoSalazar** [comment]
thanks for you answer, it is really useful to know this.
