### ISSUE TITLE
Connection failure after hundreds of thousands of queries.

### ISSUE THREAD

**Issue by carlosdelfino** [Automattic/mongoose#6791]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
Connection failure after hundreds of thousands of queries.

I have a script for inserting and analyzing data to pre-populate a database after installing the service, the data is retrieved in CSV files and everything goes well up to tens of thousands of inserts.

However, it is necessary to make queries to consolidate the inserted data and when I take to the production environment, and I will insert hundreds of thousands of record, it generates 10 x more queries, that is, thousands of thousands of queries.

The system arrives one hour to stop querying and some time later it issues the timeout error on the connection.

I have tried in every way that I can idealize and code to chain the promises and avoid overloading with them, so I use Promise.all and Promise.race in order to manage the promises in the best way and avoid memory leaks, but I could not even manage the overhead of timeouts, not even increasing the pool of connections, the greater the connection pool only the longer the wait time for the error to occur.

**If the current behavior is a bug, please provide the steps to reproduce.**

Make a sequencial of thousands of thousands of queries and inserts.

**What is the expected behavior?**
Make a bulk of queries and inserts sequentially.

**Please mention your node.js, mongoose and MongoDB version.**

I'm using the following environment for both production and development:

* Windows 10 Portuguese;
* MS Visual Studio Code
* MongoDB 4.0.0

```
$ node --version
v9.3.0
```
```
"dependencies": {
    "@google-cloud/text-to-speech": "^0.3.0",
    "@google/maps": "^0.5.5",
    "bcrypt": "^3.0.0",
    "body-parser": "^1.18.3",
    "chokidar": "^2.0.4",
    "compression": "^1.7.2",
    "csv-parse": "^2.5.0",
    "dotenv": "^6.0.0",
    "express": "^4.16.3",
    "express-jwt": "^5.3.1",
    "helmet": "^3.12.1",
    "jsonwebtoken": "^8.3.0",
    "memwatch-next": "^0.3.0",
    "moment": "^2.22.2",
    "mongoose": "^5.2.2",
    "morgan": "^1.9.0",
    "validator": "^10.4.0"
  },
  "devDependencies": {
    "nodemon": "^1.18.3"
  },
```
### Error Stack:

```
app_server\node_modules\mongoose\lib\utils.js:452
        throw err;
        ^
MongoNetworkError: connection 1 to localhost:27017 timed out
    at Socket.<anonymous> (C:\Users\Admin\workspace\Tintometria\agendamento_e_chamados\app_server\node_modules\mongodb-core\lib\connection\connection.js:258:7)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at Socket._onTimeout (net.js:421:8)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agendamento_e_chamados_app_server@0.0.1 start:import: `node ./importers`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the agendamento_e_chamados_app_server@0.0.1 start:import script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-31T17_49_12_263Z-debug.log
```

**Note:**

During the import process, I regularly check with the Robot 3T the status of MongoDB and the collections involved, and the insertion occurs late when the error does not occur, but all occur correctly.

When the error occurs, the inserts are not actually made, and the log does not appear to need to be stacked to the nextTick.

**Comment by carlosdelfino** [comment]
@vkarpov15 , thanks for you attention, I Update the environment info!

**Comment by vkarpov15** [comment]
Hard to provide any info, this report is pretty vague, but here's a few questions and suggestions

1) Are any of your inserts particularly slow?
2) Try bumping [`poolSize` to 20](http://mongoosejs.com/docs/connections.html#options)
3) Set `socketTimeoutMS` to larger than your longest running operation
