### ISSUE TITLE
Mongoose in docker cant getaddrinfo to ReplicaSet. with error first connect [MongoError: getaddrinfo ENOTFOUND]

### ISSUE THREAD

**Issue by VampireDaniel** [Automattic/mongoose#6793]
I have a mongo replica set (version 3.6) like this
mongodb1. corp. com(10.10.10.1) mongodb2. corp. com(10.10.10.2) mongodb3. corp. com(10.10.10.3)

and I have a nodejs application to connect to this RS, and it works fine in dev,qa,prod without docker.

the mongodb connection string like this
mongodb://username:userpwd@10.10.10.1:27017,10.10.10.2:27017,10.10.10.3:27017/db?replicaSet=rs0’

now we are going to use docker to deploy the app, so I made a image for my app, the docker file is like below.

FROM node:6

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

COPY package.json .

...

CMD ["grunt"]

#Expose the port
EXPOSE 8000

CMD ["node", "/usr/src/app/server.js"]
after all, I use this command to run docker but get the error below as well
sudo docker run -e NODE_ENV=dev -p 8000:8000 dockerrepo/$TAGVERSION

error: failed to connect to server [mongodb1.corp.com:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb1. corp. com mongodb1. corp . com:27017]

docker version
Docker version 18.06.0-ce, build 0ffa825

mongoose version
4.13.7

you can get that in connection string I used ip address, but in error info it shows hostname, so it means the dns and network is good, right?

please let me know if you need more info, thanks.
and need to mention again that, all the code work fine in dev, qa, prod without docker. and the error msg wouldnt be mongodb1. corp. com always, its random, maybe mongodb1, mongodb2, or mongodb3

**Comment by VampireDaniel** [comment]
then I `exec -it` into the container, ping the ip and telnet ip 27017, they both workable.

then I try to dig into the issue.
I ping the `mongodb1. corp. com` ,  a surprise occur,
`ping: unknown host mongodb1. corp. com`, then I know this is dns problem, then I add`--network host` while I start the container.

yeeee, everything works fine. but out of a sudden, a voice come into my mind, does this really the dns problem?

for my understanding, at the first connect when the app try to connect to the db replica set by ip address, this should be good, because the hostname has been gotten.
then I think the mongoose use the hostname to do the rest things this is why I got the issue `error: failed to connect to server [mongodb1.corp.com:27017]`, because at that moment, only mongoose know and try to connect the hostname, am I right? can any mongoose expert give the correct answer?

**Comment by vkarpov15** [comment]
I really don't understand your 2nd comment, can you please clarify what you mean by "why the mongoose use hostname instead of ip address which is provided in connection string, furthermore the hostname are gotten by ip. dose this by design?"

Sounds like a DNS issue. Try adding your hostnames to your dockerfile's `/etc/hosts` with [`--add-host`](https://docs.docker.com/engine/reference/run/#network-settings).

**Comment by VampireDaniel** [comment]
Hi vkarpov15, thanks for your reply. 

let me clarify,

the mongodb connection I provide in code is `mongodb://username:userpwd@10.10.10.1:27017,10.10.10.2:27017,10.10.10.3:27017/db?replicaSet=rs0`

but error log shows `error: failed to connect to server [mongodb1.corp.com:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongodb1. corp. com mongodb1. corp . com:27017]`

in connection string is ip, but in log is hostname. so for my understanding, mongoose could connect to 10.10.10.1 and could get the hostname, then in the further connection, it seems that mongoose use the hostname instead of the ip to connect to my db cluster. just like what i mentioned, after i add--network host, it works fine. 

On the surface, it seems a dns problem, but my question is, why mongoose dosent use the ip which is provided by connection string?

**Comment by vkarpov15** [comment]
Mongoose doesn't do anything like that to the best of my knowledge. Are you sure you don't have another createConnection or connect call somewhere that's using mongodb1.corp.com ? Also, what does your /etc/hosts look like?

**Comment by VampireDaniel** [comment]
its at the begin of my code running, and I am sure that there is no other code to create a connection in my project. 

```
127.0.0.1       localhost
127.0.1.1       D-SHD-00802973-Linux

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by DavidSanchezRuiz** [comment]
Hello, Could you fix the error?
