### ISSUE TITLE
BUG: select:false not working on contentType: buffer

### ISSUE THREAD

**Issue by mlasy** [Automattic/mongoose#6795]
Hey,

i created a field in my UserSchema:
`const UserSchema = new mongoose.Schema({ 
userimage:{ data: Buffer, contentType: String, select: false}
}`

when querying for User, the field and data from userimage is still showing up.

    "mongodb": "^2.2.33",
    "mongoose": "^4.13.14",
     node: v8.9.4

**Comment by vkarpov15** [comment]
Don't you mean `const UserSchema = new mongoose.Schema({ userimage:{ type: Buffer, contentType: String, select: false} }`? Try replacing 'data' with 'type', that should work. Also, what prevents you from upgrading to Mongoose 5.x?
