### ISSUE TITLE
mongoose jest memory leak

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#6797]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
the heap usage keeps increasing when using mongoose

**If the current behavior is a bug, please provide the steps to reproduce.**

You can reproduce this bug using this repo https://github.com/graphql-compose/graphql-compose-mongoose from @nodkz 

run `jest --logHeapUsage`

heap usage will keep increasing:

![image](https://user-images.githubusercontent.com/2005841/43522568-25b402f2-9570-11e8-8360-b2b1302c1893.png)

You can also run with `jest --detectLeaks --detectOpenHandles` and check that there are some open handles that keeps Jest from exiting:

![image](https://user-images.githubusercontent.com/2005841/43522712-902b5180-9570-11e8-86fb-736c7e57b69a.png)

**What is the expected behavior?**
The expect behavior is to clean up the heap usage after each test

**Please mention your node.js, mongoose and MongoDB version.**
mongodb version: 3.x.x and 4.x.x
mongoose 5.2.6
node 8.x.x and 10.x.x

related to https://github.com/Automattic/mongoose/issues/2874

more info  here https://github.com/facebook/jest/issues/6787

I've tried to add this to `afterEach`, `afterAll` and it did not help

https://github.com/Automattic/mongoose/issues/2874#issuecomment-388588452

```jsx
mongoose.connections.forEach(connection => {
  const modelNames = Object.keys(connection.models)

  modelNames.forEach(modelName => {
    delete connection.models[modelName]
  })

  const collectionNames = Object.keys(connection.collections)
  collectionNames.forEach(collectionName => {
    delete connection.collections[collectionName]
  })
})

const modelSchemaNames = Object.keys(mongoose.modelSchemas)
modelSchemaNames.forEach(modelSchemaName => {
  delete mongoose.modelSchemas[modelSchemaName]
})
```

is there any place where mongoose keep references? that is not garbage collected properly?

**Comment by sibelius** [comment]
afterAll worked well to reduce memory leak in mongoose

we fixed the rest of leak mocking `graphql-redis-subscriptions`

**Comment by murbanowicz** [comment]
What did you add exactly to the `afterAll`?
