### ISSUE TITLE
Required custom validations called multiple times on single nested sub-documents

### ISSUE THREAD

**Issue by kprenger** [Automattic/mongoose#6801]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I have a single nested sub-document, required validations are called multiple times.

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist with tests showing that `validate` custom validations are only called once, but `required` custom validations are called multiple times for single nested sub-documents:  https://gist.github.com/kprenger/c5c615dc2ff57e3b5d0e85ae425cd13b

**What is the expected behavior?**
I would expect the custom validation in the `required` attribute to behave the same as a custom validation in the `validate` attribute - in that it is only called one time.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose v5.2.6
node v8.11.3
mongo v3.6.5

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP

**Comment by vkarpov15** [comment]
Fixed in master, fix will be in 5.2.8.

**Comment by sebastian-nowak** [comment]
FYI this fix broke https://github.com/Automattic/mongoose/issues/6892
