### ISSUE TITLE
Validation error messages are duplicated on single nested sub-documents

### ISSUE THREAD

**Issue by kprenger** [Automattic/mongoose#6802]
I'm reporting this as a bug, but it may be intended behavior that isn't documented very well. In which case, I'd request it as a feature (possibly as an option that can be passed in to `validate` or `save`).

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a validation error occurs on a single nested sub-document, that error is duplicated for every parent of that sub-document. For example, if I have a Schema that has Parent -> Child -> Grandchild with a validation on the Grandchild's `name`, running a validation against Parent results in the following error object if the Grandchild's `name` validation fails (trimmed down for brevity):
```
{
'child.grandchild.name': { message: 'ValidatorError: Validator failed for path `name` with value `John`' },
'child.grandchild': { message: 'ValidationError: Validation failed: name: Validator failed for path `name` with value `John`' },
'child': { message: 'ValidationError: Validation failed: child.name: Validator failed for path `name` with value `John`, child: Validation failed: name: Validator failed for path `name` with value `John`' }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist that shows this behavior failing for both `required` and `validate` custom validations for 2- and 3-level deep single nested sub-documents.
https://gist.github.com/kprenger/fef87b8f517cd00f8eb4f9b49c1683b1

**What is the expected behavior?**
When a validation error occurs on a single nested sub-document, that error only appears once for the specific path to the validation. Example (trimmed down for brevity):
```
{
'child.grandchild.name': { message: 'ValidatorError: Validator failed for path `name` with value `John`' }
}
```

**Please mention your node.js, mongoose and MongoDB version.**
mongoose v5.2.6
node v8.11.3
mongo v3.6.5

**Comment by kprenger** [comment]
This behavior does not appear to happen on arrays of sub-documents, which is why I brought this up as what I believe is a bug.

https://gist.github.com/kprenger/ca9a3d9db6d1845af54e165da8c31f5e

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP. I suspect this may be expected behavior but worth looking into.

**Comment by hypersolution1** [comment]
I have the same issue. It seems that there is a nested version and a non nested version of a field error, however the nested version is missing the field in array. Another issue with the non nested version is that the path field is incomplete. I have to iterate with Object.keys() to get all the information. 

I wouldn't bother having both version coexist, but I find it kind of hacky to look for an 'errors' property to figure out if the element is nested or not.

I have this schema structure:

```javascript
{
 profile: {
  name: {type:"String"},
  places: [{
    name: {type:"String"},
    ...,
  }],
  ...,
}
```

```javascript
{
  "errors": {
    "profile.name": {
      "message": "Path `name` is required.",
      "name": "ValidatorError",
      "properties": {
        "message": "Path `name` is required.",
        "type": "required",
        "path": "name",
        "value": ""
      },
      "kind": "required",
      "path": "name",
      "value": "",
      "$isValidatorError": true
    },
    "profile.places.0.name": {
      "message": "Path `name` is required.",
      "name": "ValidatorError",
      "properties": {
        "message": "Path `name` is required.",
        "type": "required",
        "path": "name",
        "value": ""
      },
      "kind": "required",
      "path": "name",
      "value": "",
      "$isValidatorError": true
    },
    "profile": {
      "errors": {
        "name": {
          "message": "Path `name` is required.",
          "name": "ValidatorError",
          "properties": {
            "message": "Path `name` is required.",
            "type": "required",
            "path": "name",
            "value": ""
          },
          "kind": "required",
          "path": "name",
          "value": "",
          "$isValidatorError": true
        }
      },
      "_message": "Validation failed",
      "message": "Validation failed: name: Path `name` is required.",
      "name": "ValidationError"
    }
  },
  "_message": "Association validation failed",
  "message": "Association validation failed: profile.name: Path `name` is required., profile.places.0.name: Path `name` is required., profile: Validation failed: name: Path `name` is required.",
  "name": "ValidationError"
}
```
