### ISSUE TITLE
Why deleteMany doesn't support session

### ISSUE THREAD

**Issue by Trucc** [Automattic/mongoose#6805]
Assuming this function :

```
  const session = await mongoose.startSession()
  session.startTransaction();
  try{
    let deleted;
    if((deleted = await node.findByIdAndRemove(id, { session })) == null) throw Error("L'objet node ne peut pas être supprimé")
    await Capteur.deleteMany({_id : {$in : deleted.children}}, { session })
    await node.update({}, {$pull : {children : id}}, { session, multi : true})
    await session.commitTransaction();
    session.endSession();
  }catch(err){
      await session.abortTransaction();
      session.endSession()
      throw Error("Erreur lors de l'ajout d'un node")
  }
  return
```

`await Capteur.deleteMany({_id : {$in : deleted.children}}, { session })` return this MongooseError "Callback must be a function, got [object Object]"

Why can't we use session there as we can use it for Model.update() or Model.findByIdAndRemove() ?

**Comment by Fonger** [comment]
`deleteMany` does not accept `options` in parameter
I submit a pull request and should fix this.

Sorry for messing up with the logs. I deleted the old branch to keep commits clean.
