### ISSUE TITLE
docs embedded in object w/ arbitrary keys?

### ISSUE THREAD

**Issue by ghost** [Automattic/mongoose#681]
Is there a way to use embedded docs within a object that doesn't have predetermined keys? i.e. Rather than having a situation like this:

``` javascript
var myschema = new mongoose.Schema({
   field : { foo: String, bar: String }
});
```

Being able to say something like:

``` javascript
var myschema = new mongoose.Schema({
   field : { *: String }
});
```

Makes it a little more array like in that way - but the idea is that I don't know the keys in advance, but I'd still like to be able to have an embedded doc.

**Comment by coty-crg** [comment]
+1

**Comment by tieblumer** [comment]
+1

**Comment by rubenstolk** [comment]
+1

**Comment by rohithn** [comment]
+1

**Comment by Elements-** [comment]
+1

**Comment by smarom25** [comment]
+1

**Comment by aivel** [comment]
+1

**Comment by voodee** [comment]
+1

**Comment by raub** [comment]
+1

**Comment by gabrielcsapo** [comment]
+1

**Comment by Kanwer-Singh** [comment]
+1

**Comment by Michael77** [comment]
I have needed this a well

**Comment by mosane** [comment]
+1

**Comment by qqilihq** [comment]
Stop those meaningless +1 , which end up in watching peoples' inboxes. 

There are "Subscribe" and "Reaction" buttons for a reason.

**Comment by coty-crg** [comment]
+1

**Comment by raub** [comment]
@qqilihq, do implement plx, then we stop +1, kthxbye

**Comment by Flicksie** [comment]
"no one has needed it before"
5 years later, a ton of +1s later, still no updates on this?

**Comment by vkarpov15** [comment]
Since this is the oldest issue I can find related to this one, I'll re-open this and close #1522 so as many people as possible can track for updates.

**Comment by doneumark** [comment]
+1

**Comment by adamreisnz** [comment]
How did this feature get released so quietly that I wasn't aware of it?! 💯

**Comment by vkarpov15** [comment]
@adamreisnz lol thanks. Where do you look for Mongoose feature updates? Changelog? Twitter?

**Comment by adamreisnz** [comment]
Changelog usually, but must have missed this one!

**Comment by objective-cwan67** [comment]
> +1





https://admiral-tranquil.github.io/ram58/
