### ISSUE TITLE
Deprecation warning can't be solved.

### ISSUE THREAD

**Issue by firattale** [Automattic/mongoose#6825]
**Do you want to request a *feature* or report a *bug*?**
I think it is a bug.
**What is the current behavior?**
After I start my app, I get this warning :

`
(node:47425) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
`

I add that object then I have this error and can't start the app.
`(node:47381) UnhandledPromiseRejectionWarning: MongoError: port must be specified
.......
(node:47381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:47381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
`

```javascript
mongoose.connect("mongodb://localhost/restful_blog_app", { useNewUrlParser: true });
```

**If the current behavior is a bug, please provide the steps to reproduce.**

just node app.js
**What is the expected behavior?**
I think it should start smoothly,after I add what you say.
**Please mention your node.js, mongoose and MongoDB version.**
node 8.11.3
mongoose latest
mongo 4.0.0

**Comment by Fonger** [comment]
Hi, the error suggest that you should specify the port in url when using new url parser.

Try the following code to see if it works

```js
mongoose.connect("mongodb://localhost:27017/restful_blog_app", { useNewUrlParser: true });
```

**Comment by firattale** [comment]
Yeap, It worked, thank you Fonger, I tried 3000 but didnt think about mongo port :)

**Comment by LFaseva** [comment]
And what if I have the same mistake but i use a remote connection to DB without localhost?

**Comment by lineus** [comment]
@LFaseva Regardless of hostname, when you set `{ useNewUrlParser: true }`, you must specify the port number explicitly. [This bug](https://jira.mongodb.org/browse/NODE-1547) is open with the underlying native driver to address the issue.
