### ISSUE TITLE
DeprecationWarning: collection.count is deprecated

### ISSUE THREAD

**Issue by NewEraCracker** [Automattic/mongoose#6831]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```
(node:5004) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
````

**If the current behavior is a bug, please provide the steps to reproduce.**

I am not sure where this comes from, but is probably an internal library that mongoose is using.

**What is the expected behavior?**

No warning.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.11.3
Mongoose: 5.2.7
MongoDB: 3.6

**Comment by NewEraCracker** [comment]
Could it be this?
https://github.com/Automattic/mongoose/blob/2e71feaa7beee28ffef11889d6fac811a29d3c66/lib/query.js#L1957

**Comment by lineus** [comment]
The underlying mongodb driver has deprecated the `.count()` method. You should use `.estimatedDocumentCount()`  or `.countDocuments()` instead.

[estimatedDocumentCount docs here](http://mongoosejs.com/docs/api.html#model_Model.estimatedDocumentCount)
[countDocuments docs here](http://mongoosejs.com/docs/api.html#model_Model.countDocuments)

**Comment by bcmux** [comment]
This isn't fixed, though. This is inherently a problem with what @NewEraCracker pointed out. For example, using **findById** will reproduce this error in **mongoose@5.4.3** with **MongoDB@3.6** and **Node@10.15.0**.

**Problem:**
node_modules/mongoose/lib/query.js:2086
```
this._collection.count(conds, options, utils.tick(callback));
```

**Fix:**
```
  this._collection.countDocuments(conds, options, utils.tick(callback));
```

**Comment by DomBreno** [comment]
I changed the "this._collection.count (conds, options, utils.tick (callback));"
by "this._collection.collection.countDocuments (conds, options, utils.tick (callback));" and it worked for me.
