### ISSUE TITLE
SchemaType Property 'set' being called on Model.find()

### ISSUE THREAD

**Issue by ajbieber** [Automattic/mongoose#6832]
### Current Behavior
Currently, if a model is being queried by Model.find() (I don't know if this is an issue in other queries), the 'set' property of any model attributes are called. On the system I am working, it is causing the value to be reset, and thus returning no documents.

### Steps to Reproduce
(1) Create a model, and in the model add an attribute similar to the following:
```javascript
id: {
  type: String,
  required: false,
  unique: true,
  set: function(v) {
    console.log("Hello world!");
    return v;
  }
}
```
(2) Create a document with whatever name you choose. The setter in the id field SHOULD correctly be called.
(3) Query the model using something like Model.find({id: 'myID'}) and you will find that the setter gets incorrectly called.

### Expected Behavior
The setter should not get called on a find query, only a getter if anything.

### Versions

node: 10.4.1
Mongoose: 5.2.7
MongoDB: 3.1.0

**Comment by vkarpov15** [comment]
This is expected behavior in Mongoose 5.x in order to make common setters like `lowercase: true` apply to queries. If you don't want your setter to run on queries, you should do:

```javascript
id: {
  type: String,
  required: false,
  unique: true,
  set: function(v) {
    if (this instanceof mongoose.Query) {
      return v;
    }
    console.log("Hello world!");
    return v;
  }
}
```
