### ISSUE TITLE
ObjectId getting convert to string after stringify a mongo document object

### ISSUE THREAD

**Issue by priytam1993** [Automattic/mongoose#6833]
favorite
1
I want to write mongodb document to json file in node but after getting data from database when i stringfy mogodb object all ObjectId("yt33..") getting change to simple sting "yt33.." Here is the code i have written for it .

http://prntscr.com/kgidxr

db.user.findById(id, function(err, data) { if (err) throw err;

    var json = JSON.stringify(data);

    fs.writeFileSync(exportDir + 'grades.json', json, {
        encoding: 'utf8',
        flag: 'w'
    }, function() {
        console.log('completed..');
    });

**Comment by vkarpov15** [comment]
Expected behavior, `ObjectId('abc123')` is not valid JSON. JSON doesn't support any custom types, so object ids become strings.

**Comment by Zhenhong-Lyu** [comment]
but this will cause problems when posting data back to store in mongodb. How to solve this issue?

**Comment by vkarpov15** [comment]
@Zhenhong-Lyu Mongoose documents cast strings back into ObjectIds based on your schema, so if you create a new document from data serialized using `JSON.stringify()`, you'll get an ObjectId.
