### ISSUE TITLE
Mongoose v4 sort/limit issue with MongoDB v2.4

### ISSUE THREAD

**Issue by freewil** [Automattic/mongoose#6835]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Query should return 1001 docs based on 2000 `limit`, but only returns 1000.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const assert = require('assert')
const async = require('async')
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const BookSchema = new Schema({
  title: { type: String }
})

const Book = mongoose.model('Book', BookSchema)

mongoose.connect('mongodb://localhost:27017/batchsizetest3')

// drop any existing collection
Book.collection.drop(function (err) {
  if (err) console.error('Failed to drop existing collection')

  // create 1001 docs
  async.timesSeries(1001, function (n, next) {
    Book.create({ title: 'title-' + n }, next)

  }, function (err) {
    if (err) return console.error('error creating books', err)

    // confirm number of docs created
    Book.count(function (err, count) {
      if (err) return console.error('error getting book count', err)
      console.log('Book count', count)
      assert.equal(count, 1001)

      // query all the docs out
      Book
        .find()
        .sort('_id title')
        .limit(2000)
        .exec(function (err, books) {
          if (err) return console.error('error querying books', err)

          console.log('Books queried', books.length)
          assert.equal(books.length, 1001)
          mongoose.disconnect()
        })
    })
  })
})

```

**What is the expected behavior?**
should return all 1001 docs.

**Please mention your node.js, mongoose and MongoDB version.**
node@6.14.3
mongoose@4.13.14
async@2.6.1
MongoDB Server 2.4.12

I know this is an older version of mongoose and MongoDB, so if this is closed as `wontfix`, I understand - but please at least confirm my workaround is correct here.

This code works correctly with `mongoose@3.8.35` instead of `mongoose@4.13.14` OR MongoDB Server 2.6 instead of MongoDB Server 2.4.12. This appears to be a bug as best as I can tell either in Mongoose or the driver that Mongoose uses. A workaround appears to be to set `batchSize()` so that it is >= `limit()` but it seems that should not be necessary here.

**Comment by freewil** [comment]
Some more information on this. It appears the default batchSize is 1000. If I turn on profiling via the `mongo` shell, `db.setProfilingLevel(2)` - I can see with 2.6 there are properly 2 ops - `query` and `getmore` - with 2.4 I only see 1 op - the query, but no `getmore` op.

**Comment by vkarpov15** [comment]
I think your workaround works, but [MongoDB 2.4 is no longer supported by the underlying MongoDB driver](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-node) so I would recommend upgrading to MongoDB 2.6 at least. Why are you using 2.4?

**Comment by freewil** [comment]
> Why are you using 2.4?

Legacy :(

**Comment by freewil** [comment]
was 2.4 dropped? It seems like the version of core that 4.x branch uses still supports it: https://github.com/mongodb-js/mongodb-core/blob/v2.1.18/lib/wireprotocol/2_4_support.js

**Comment by vkarpov15** [comment]
Weird, I'll take a look. I'm just going by the compatibility matrix on the mongdb docs, which unfortunately doesn't list 2.4 anymore

**Comment by freewil** [comment]
FWIW, specifying the `batchSize()` worked as a workaround in production. The database where this was discovered was also upgrade to MongoDB 3, which should remove the necessity for the workaround. I don't know, maybe still worth some investigation though if this bug somehow affects something in newer versions of mongoose/driver/server?

**Comment by vkarpov15** [comment]
Good call. I thought I had reopened this issue already, looks like that didn't go through. Will investigate

**Comment by vkarpov15** [comment]
I dug into this in excruciating detail and came to the conclusion that this is due to a known bug with unindexed sorts in MongoDB 2.4: https://jira.mongodb.org/browse/SERVER-12438 . Under the hood, the MongoDB driver sets a batch size of 1000, so that's why you're getting this issue. Another way to work around it is to sort by `_id` instead of `'_id title'`:

```javascript
Book.find() .sort('_id').limit(2000)
```

If you want to sort by title, you need to build an index on it:

```javascript
const BookSchema = new Schema({
  title: { type: String, index: true }
})
```

I wish I had a better answer for you, but unfortunately there isn't much Mongoose can do about it if the MongoDB server tells the driver there's only one batch.

**Comment by freewil** [comment]
Awesome, thanks for the investigation! Glad it's already a known bug that's since been fixed.
