### ISSUE TITLE
MongoError: Transaction 1 has been committed.

### ISSUE THREAD

**Issue by nathanchan01** [Automattic/mongoose#6837]
** case 1 
`await connection.collection("invoice").insert(invoice, {session});`

**case 2 
`await invoice.save({ session});`
invoice is a mongoose model

Case 2 doesn't work when it runs 2 functions and each inserts multiple invoices 

error msg : MongoError: Transaction 1 has been committed.

does it have anything wrong?

**Comment by vkarpov15** [comment]
I don't understand the issue, can you please expand your code samples and add a full stack trace?
