### ISSUE TITLE
Query helper: `.orFail()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6841]
General idea:

```javascript
await Model.find({ foo: 'bar' }).orFail(); // throws if no results
await Model.updateOne({ foo: 'bar' }, { $set: { answer: 42 } }).orFail(); // throws if no documents updated
await Model.deleteOne({ foo: 'bar' }).orFail(); // throws if no documents deleted
```

Is this useful?

[![](https://api.gh-polls.com/poll/01CMJ7KDM5WEY6GZ1HP64RVADT/Yes)](https://api.gh-polls.com/poll/01CMJ7KDM5WEY6GZ1HP64RVADT/Yes/vote)
[![](https://api.gh-polls.com/poll/01CMJ7KDM5WEY6GZ1HP64RVADT/No)](https://api.gh-polls.com/poll/01CMJ7KDM5WEY6GZ1HP64RVADT/No/vote)

**Comment by vkarpov15** [comment]
Re: https://github.com/Automattic/mongoose/issues/5982

**Comment by marcuspoehls** [comment]
@vkarpov15 this is a great idea. I really like it. 

Do you think it will be possible to pass a custom Error as a parameter to ".orFail"?

**Comment by vkarpov15** [comment]
Added in 5.3 branch

**Comment by marcuspoehls** [comment]
@vkarpov15 awesome 😍
