### ISSUE TITLE
Configure what values Mongoose runs defaults for

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6849]
Right now, defaults only run if the value is undefined. That is cumbersome in cases where you might get an empty string for a date field like in #6827 because that's what some date pickers give you if the user doesn't select a value. Also, some people may prefer to run defaults if a value is `null`.

Is this useful? Suggestions welcome.

/poll "Yes" "No"

**Comment by Fonger** [comment]
/poll "Yes"

Many forms post with empty string and I have to pick it out in my code
It will be great if this can be done on mongoose.

Hope we can use it like this:

```js
time: {
  type: Date,
  shouldRunDefault: (value) => {
    return value === 'CURRENT_SERVER_DATE_PLEASE'
  }
  default: Date.now
}
```
and this function should be run before `casting`.


Or **a more general way to support form use case**

```js
comments: {
  type: String,
  shouldRemoveField: (value) => (typeof value === 'string' && value.trim() === '')
}
```

removeField should run before `casting and default` so if the field is deleted (hence `undefined` ), the default value will apply. If there's no default, then the field is omitted in database.

**Comment by Fonger** [comment]
@vkarpov15 Yes! Adding setters on SchemaType is really a good idea because it makes mongoose API more consistent.

**Comment by vkarpov15** [comment]
It looks like we already support global setters: https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html . So we can close this because global setters give you the same result.
