### ISSUE TITLE
Enable https for documentation site mongoosejs.com

### ISSUE THREAD

**Issue by Fonger** [Automattic/mongoose#6856]
GitHub has supported free custom domain with https
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Although this is just a document website, enabling https can prevent MITM malicious code injection attack

- [x] Enable https for https://mongoosejs.com
- [x] Fix mix content error for doc site
- [ ] Enable https for plugins.mongoosejs.**com** ( ? )
- [ ] Enable https for plugins.mongoosejs.**io** ( ? )

**Comment by vkarpov15** [comment]
I wish we could but unfortunately it requires DNS access and I don't have access to the mongoosejs.com DNS. If you know anyone at Automattic that could help out with that, I would appreciate some help.

**Comment by ebastos** [comment]
Hello!

DNS was updated according to the [instructions here](https://help.github.com/articles/setting-up-an-apex-domain/).

```
$ host mongoosejs.com ns1.automattic.com
Using domain server:
Name: ns1.automattic.com
Address: 198.181.116.5#53
Aliases: 

mongoosejs.com has address 185.199.109.153
mongoosejs.com has address 185.199.108.153
mongoosejs.com has address 185.199.110.153
mongoosejs.com has address 185.199.111.153

```

Custom domain had to be removed/recreated as per step 4:

> If you're updating the IP address of an existing A record, first remove and then re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS. For more information, see "Adding or removing a custom domain for your GitHub Pages site."

The TTL was set to 24hrs, so it may take a while to propagate.

**Comment by vkarpov15** [comment]
Awesome, thanks @ebastos . If you don't mind me asking, how did you find your way to this issue?

**Comment by ebastos** [comment]
We got [pinged](https://twitter.com/ChingFengHsu/status/1029216340924461056) by @Fonger ;)

Let us know if you don't see these DNS changes propagated.

**Comment by danielmcq** [comment]
Guys, the https site is using the *.github.com cert, and makes it invalid for the domain mongoosejs.com. The docs site is currently broken. :(

**Comment by ebastos** [comment]
DNS propagation:

Using Google as the DNS:

```
$ host mongoosejs.com 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

mongoosejs.com has address 192.30.252.154
mongoosejs.com has address 192.30.252.153
```

Once all caches are gone we should see:

```
$ host mongoosejs.com ns1.automattic.com
Using domain server:
Name: ns1.automattic.com
Address: 198.181.116.5#53
Aliases: 

mongoosejs.com has address 185.199.108.153
mongoosejs.com has address 185.199.110.153
mongoosejs.com has address 185.199.111.153
mongoosejs.com has address 185.199.109.153
```

Which will yield:

```
$ http -h https://mongoosejs.com
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Age: 28
Cache-Control: max-age=600
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 2908
Content-Type: text/html; charset=utf-8
Date: Tue, 14 Aug 2018 16:09:05 GMT
Expires: Tue, 14 Aug 2018 16:13:01 GMT
Last-Modified: Tue, 14 Aug 2018 15:14:09 GMT
Server: GitHub.com
Vary: Accept-Encoding
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Fastly-Request-ID: 004e265dc07786341f387af94142b038469d86bb
X-GitHub-Request-Id: 2686:2E92:171D939:20F33B9:5B72FE84
X-Served-By: cache-jfk8147-JFK
X-Timer: S1534262945.414092,VS0,VE1
```

**Comment by Fonger** [comment]
@ebastos Thank you for such a quick action! 💯

**Comment by ebastos** [comment]
Looks like the DNS caching is causing issues, so I temporarily disabled the HTTPS redirection and will re-enable in 24hrs when propagation should be done.

Thanks, @vkarpov15 for keeping a close eye on it.

**Comment by Fonger** [comment]
@vkarpov15 #5867 is duplicate and can be closed

**Comment by vkarpov15** [comment]
@Fonger I opened up a separate issue for the plugins site. I'm pretty surprised that plugins.mongoosejs.com is still running, but the .io site is the right one. I don't have access to plugins.mongoosejs.com, perhaps @ebastos can help us out with redirecting that to plugins.mongoosejs.io?

**Comment by ebastos** [comment]
I raised the plugins.mongoosejs.com with the team and their assessment is that it should be shutdown since it's not in use anymore. Redirection to the .io seems to be a no-go.

I am not aware about who owns the heroku hosting, but they should probably retire it as well.

Sorry for the delay getting back to you.

**Comment by vkarpov15** [comment]
Can you remove the `plugins.mongoosejs.com` DNS entry then? I don't think I have access to the heroku setup.
