### ISSUE TITLE
write concern timeout(wtimeout) not working

### ISSUE THREAD

**Issue by pcharithareddy** [Automattic/mongoose#6862]
Mongoose version: 5.2.7
Node version: 8.9.4

This is timing out immediately if there are no enough number of nodes and not waiting for the wtimeout period. Previously I was using Mongoose v5.0.4 and it wasn't supporting write concern. After i upgraded to the latest version(5.2.7) w option works but not wtimeout. I tried passing these options even in the database connection URI but of no use.

```
 const options = {
    w: 3,
    wtimeout: 3000
 };
 await mongoose.connect(dburl, options)
   .then(() => console.log("Successfully established connection"))
   .catch((err) => {
       console.log("Failed to establish connection");
       throw err;
   });
```

**Comment by Fonger** [comment]
According to (mongoose doc](https://mongoosejs.com/docs/guide.html#writeConcern),
When defining write concern and wtimeout at schema level, you should use the following format:

```js
const schema = new Schema({ name: String }, {
  writeConcern: {
    w: 'majority',
    j: true,
    wtimeout: 1000
  }
});
```

**Comment by pcharithareddy** [comment]
Does Mongoose allow passing write concern in the connection string?

**Comment by pcharithareddy** [comment]
Also I tried with setting at schema level and it still doesnt work:

const schema = new Schema({ name: String }, {
  writeConcern: {
    w: 5,
    wtimeout: 5000
  }
});

**Comment by Fonger** [comment]
Thank you for reporting this! This is a **confirmed** and **critical** bug
mongoose just ignore any write concern options

I've submitted a pull request to fix this.

**Comment by vkarpov15** [comment]
@Fonger thanks for finding this, will release asap. As a workaround, you can pass `w` and `wtimeout` directly to save: `await doc.save({ w: 3, wtimeout: 1000 });`

**Comment by Fonger** [comment]
@vkarpov15 The workaround didn't work either. It only accepted `safe` and `session` options, before the fix.

The correct workaround for mongoose before 5.2.8 is
`await doc.save({ safe: { w: 3, wtimeout: 1000 } });`

**Comment by vkarpov15** [comment]
@Fonger you're correct, thanks for pointing out my mistake.
