### ISSUE TITLE
After $rename via mongoose, I can't access the new name 

### ISSUE THREAD

**Issue by arielkotch** [Automattic/mongoose#6864]
I am using the latest version of mongoose version 5.2.8 and I am getting weird behavior with $rename.

```
var assert = require('assert');
var MarioChar = require('../models/marioCharacter');
describe('Updating',function(){
  var char;
    beforeEach(async function(){
        //beforeEach test we want to create an item,
        //then remove it from the database
         char=new MarioChar({
            name:'mario',
            weight:50
        });
        await char.save();
        console.log('Saved to the database');

    })
    it('Increments the weight by one',async function(){
      //calling update on a model will update all the records
      await  MarioChar.update({},{
          $inc:{weight:1},
          $rename:{name:'callSign'}
        });

      var results=await MarioChar.findOne({
           callSign:'mario'
        });
      

        console.log(results,'result');
        console.log(results.callSign);
        console.log(results.weight);
        assert(results.weight===51);
        assert(results.callSign==='mario')
        console.log(results,'result');
    });
});
```
<img width="772" alt="screen shot 2018-08-14 at 7 47 42 pm" src="https://user-images.githubusercontent.com/16893982/44124373-f098b1ae-9ffa-11e8-91b9-aea4428a3709.png">

Why is results.callSign undefined? When it returns the object?

**Comment by lineus** [comment]
@arielkotch the `$rename` is succeeding in mongodb, but has no affect on the schema in mongoose, so when the findOne responds with the `callsign` field, mongoose is unaware of it and ignores it. 

**see the complete example below**

Adding compatibility with `$rename` has come up in the past but wasn't adopted [see this bug](https://github.com/Automattic/mongoose/issues/4100). 

@vkarpov15 is adding support for `$rename` still off the table? I could see rename causing a bit of trouble if the path being renamed is used **anywhere** else in the code ( which seems probable ). 

# Example

### 6864.js
```js
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/gh6864', { useNewUrlParser: true });
const { Schema } = mongoose;

const schema = new Schema({
  name: String,
  weight: Number
});

const MarioChar = mongoose.model('mariochar', schema);

describe('Updating', function () {
  before(async function () {
    await MarioChar.remove({});
    let char = new MarioChar({
      name: 'mario',
      weight: 50
    });
    await char.save();
  });

  after(function() {
    return mongoose.connection.close();
  });

  it('Increments the weight by one', async function () {
    await MarioChar.update({}, { $inc: { weight: 1 } });
    const results = await MarioChar.findOne({});
    assert.strictEqual(results.weight, 51);
  });

  it('renames the name path', async function() {
    await MarioChar.update({}, { $rename: { name: 'callSign' } });
    const results = await MarioChar.findOne({});

    assert.strictEqual(results.callSign, 'mario');
    console.log(results, 'result');
  });
});
```
### Shell Output:
```
issues: mocha ./6864.js


  Updating
    ✓ Increments the weight by one
    1) renames the name path


  1 passing (79ms)
  1 failing

  1) Updating
       renames the name path:
     AssertionError [ERR_ASSERTION]: undefined === 'mario'
      at Context.<anonymous> (6864.js:39:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



issues:
```

### Mongo Shell Output:
```
issues: mongo --quiet gh6864
>db.mariochars.findOne()
{
        "_id" : ObjectId("5b738683f66e220bc074a8e3"),
        "weight" : 51,
        "__v" : 0,
        "callSign" : "mario"
}
>^C
issues:
```

**Comment by Fonger** [comment]
IMO, schema should not be changed during run-time of an application.
Otherwise it loses the meaning of what schema is.

**Comment by arielkotch** [comment]
@Fonger but what if you have a set schema and only want to update one object from the schema using $rename?

**Comment by Fonger** [comment]
@arielkotch you should get the document, update it and then save it. 

mongoose can't support $rename because it sends a $rename update request without knowing the 
 actual data. So there's no validation and schema type casting.

Consider this case:
```js
{
  aaa: { type: [Number] }
  bbb: { type: Schema.Types.Mixed }
}
```

What if you rename `bbb` to `aaa`?
Rename request will success. However if the original value of `bbb` can't cast to type of `aaa`, mongoose may throw an error, which is meanless because it's too late. The data modification has already done on mongodb server.

**Comment by vkarpov15** [comment]
@arielkotch the workaround is to have both `name` and `callSign` in your schema when you call `$rename`. Mongoose can't really help out with `$rename` because even if we were smart enough to know that you called `$rename` on a schema path, Mongoose doesn't persist any data so it would lose that information the next time your server restarted.
