### ISSUE TITLE
Connecting with srv URI string sans credentials ( in options instead ) causes errors

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#6881]
repro code:
### 6881.js
```js
#!/usr/bin/env node --no-deprecation
'use strict';

const env = require('/Users/lineus/.env');
const uri = env.ATLASSRV_HOST_ONLY;

const sharable = uri.replace(/cl[^:]+mon/, 'cluster.mon');
const opts = {
  dbName: 'gh6881',
  auth: {
    user: env.ATLAS_USER,
    password: env.ATLAS_PASS
  },
  useNewUrlParser: true
};

const mongoose = require('mongoose');
mongoose.connect(uri, opts);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test1 = new Test({ name: 'one' });
const test2 = new Test({ name: 'two' });

async function run() {
  console.log(`version: ${mongoose.version}`);
  console.log(`conn string: ${sharable}`);
  await conn.dropDatabase().catch(error);
  await Test.create([test1, test2]).catch(error);
  let docs = await Test.find().catch(error);
  console.log(docs);
  return conn.close().catch(error);
}

run();

function error(e) {
  console.error(e.message);
}
```
### Output:
```
issues: ./6881.js
version: 5.2.9
conn string: mongodb+srv://cluster.mongodb.net/?retryWrites=true
user is not allowed to do action [dropDatabase] on [gh6881.]
user is not allowed to do action [insert] on [gh6881.tests]
user is not allowed to do action [find] on [gh6881.tests]
undefined
issues:
```

### also tried:
```js
const opts = {
  dbName: 'gh6881',
  user: env.ATLAS_USER,
  pass: env.ATLAS_PASS,
  useNewUrlParser: true
};
```

## ~~It works in the native driver~~:
*note that in this example useNewUrlParser === false*
### 6881_native.js
```js
#!/usr/bin/env node
'use strict';

const env = require('/Users/lineus/.env');
const { MongoClient } = require('mongodb');

const uri = env.ATLASSRV_HOST_ONLY;
const opts = { auth: { user: env.ATLAS_USER, password: env.ATLAS_PASS } };

const sharable = uri.replace( /cl[^:]+mon/, 'cluster.mon');

const pkg = require.resolve('mongodb').replace(/\/[^/]*$/, '/package.json');
const ver = require(pkg).version;

async function run() {
  console.log(`version: ${ver}`);
  console.log(`conn string: ${sharable}`);
  const client = await MongoClient.connect(uri, opts);
  const db = client.db('gh-6881');
  await db.dropDatabase().catch(handleError);
  await db
    .collection('tests')
    .insertOne({ name: 'Billy' })
    .catch(handleError);

  let found = await db
    .collection('tests')
    .findOne({})
    .catch(handleError);
  console.log(found);
  process.exit(0);
}

run();

function handleError(e) {
  return console.error(e.message);
}
```
### Output:
```
issues: ./6881_native.js
version: 3.1.3
conn string: mongodb+srv://cluster.mongodb.net/?retryWrites=true
{ _id: 5b771cd55bea4d41be7642b7, name: 'Billy' }
issues:
```

**Comment by lineus** [comment]
I was looking at my native driver script and realized that I failed to pass in the `useNewUrlParser: true` option. This is why it worked before. [Here is the Native Driver Bug opened for this issue](https://jira.mongodb.org/browse/NODE-1635). 

### 6881_native.js
```js
#!/usr/bin/env node
'use strict';

const env = require('/Users/lineus/.env');
const { MongoClient } = require('mongodb');

const uri = env.ATLASSRV_HOST_ONLY;
const opts = { 
  useNewUrlParser: true,
  auth: { 
    user: env.ATLAS_USER, 
    password: env.ATLAS_PASS 
  }
};

const sharable = uri.replace( /cl[^:]+mon/, 'cluster.mon');

const pkg = require.resolve('mongodb').replace(/\/[^/]*$/, '/package.json');
const ver = require(pkg).version;

async function run() {
  console.log(`version: ${ver}`);
  console.log(`conn string: ${sharable}`);
  const client = new MongoClient(uri, opts);
  await client.connect();
  const db = client.db('gh-6881');
  await db.dropDatabase().catch(handleError);
  await db
    .collection('tests')
    .insertOne({ name: 'Billy' })
    .catch(handleError);
  
  let found = await db
    .collection('tests')
    .findOne({})
    .catch(handleError);
  console.log(found);
  process.exit(0);
}

run();

function handleError(e) {
  return console.error(e.message);
}
```
### Output:
```
issues: ./6881_native.js
version: 3.1.3
conn string: mongodb+srv://cluster.mongodb.net/?retryWrites=true
user is not allowed to do action [dropDatabase] on [gh-6881.]
user is not allowed to do action [insert] on [gh-6881.tests]
user is not allowed to do action [find] on [gh-6881.tests]
undefined
issues:
```

**Comment by vkarpov15** [comment]
Thanks for providing a repro script @lineus, hope this'll get fixed soon.

**Comment by lineus** [comment]
reopening this as the issue seems to be unresolved in the latest native driver.

**Comment by Vikashumar** [comment]
i am trying to connect to mongodb Atlas...its working fine with local host but getting error while connecting to atlas...

var bodyParser = require('body-parser');
 const mongoose = require('mongoose');
 mongoose.Promise = global.Promise;
//  mongoose.connect('mongodb+srv://loginUser:loginUser@cluster0-ccbhk.mongodb.net/test?retryWrites=true&w=majority');
 mongoose.connect('mongodb+srv://loginUser:loginUser@cluster0-ccbhk.mongodb.net/test?retryWrites=true&w=majority', { useNewUrlParser: true},{ useUnifiedTopology: true })

mongoose.connect('mongodb://localhost/userdata');
mongoose.connection.once('open',function(err){
   if(err) throw err;
   console.log('connected successfully');
})
 var Schema = mongoose.Schema;

 var TodoSchema = new Schema({
    username:String,
    useremail:String
 });

 var userData = mongoose.model('userdata',TodoSchema);

 const urlencoded = bodyParser.urlencoded({ extended: false });  


module.exports = function(app){

    app.get('/',function(req,res){

       res.render('index');
    })
    app.get('/index',function(req,res){

        res.render('index');
     })
     app.get('/contact',function(req,res){

        res.render('contact');
     })

     app.get('/login',function(req,res){

      res.render('login');
   })
   
   app.post('/login',urlencoded,function(req,res){

      var data = {
         username:req.body.name,
         useremail:req.body.email
      }
      newuser = userData(data).save(function(err,data){
         if(err)throw err;
         console.log(req.body)
         res.render('login-success',{data:data});
      })
   
   })
}

error:.....

(node:20280) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true 
} to MongoClient.connect.
(node:20280) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
listening to port 3000
connected successfully
(node:20280) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at C:\mywebsite\node_modules\mongoose\lib\connection.js:786:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{}
[Object: null prototype] {
  name: 'lkjdoqhdhw',
  email: 'kumar@kjhkje.com'
}



How to solve this error..anyone please as im new to it.

Thanks

**Comment by vkarpov15** [comment]
It looks like you're calling `mongoose.connect()` twice, once with an options object as the callback:

```
// Third argument below is `{ useUnifiedTopology: true }`, that should be a callback
mongoose.connect('mongodb+srv://loginUser:loginUser@cluster0-ccbhk.mongodb.net/test?retryWrites=true&w=majority', { useNewUrlParser: true},{ useUnifiedTopology: true })
```

Why are you calling `mongoose.connect()` twice?

I opened up a new issue to track reporting a more readable error re: object as callback param.
