### ISSUE TITLE
v5.2.9 breaks on Node 4.1 and 5.9 (+more) Buffore.alloc

### ISSUE THREAD

**Issue by mblarsen** [Automattic/mongoose#6884]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Since 5.2.9 the mongo library (in current range) causes:

```
Uncaught TypeError: Buffer.alloc is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a test case that shows the error:

for 5.9 https://travis-ci.org/mblarsen/mongoose-hidden/jobs/417260776#L628
for 4.1 https://travis-ci.org/mblarsen/mongoose-hidden/jobs/417260777#L538

Note that just above you'll see:

> current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

I'm not sure that is related.

**Please mention your node.js, mongoose and MongoDB version.**

`"mongoose": "^5.0.0",`

No MongoDB depency since my code is a Mongoose library. The error occurs on Travis.

`services: mongodb`

**Comment by Fonger** [comment]
This is underlying library issue. https://github.com/mongodb/node-mongodb-native/commit/759dd85
Since mongodb@3.1.2+ they use Buffer.alloc without any polyfill like mongoose does

**Comment by mblarsen** [comment]
@Fonger, I was unable to find those issues, thanks for adding them

Anyway it is also occurring in Node 5.9 which should have `Buffer.alloc` right?

**Comment by Fonger** [comment]
@mblarsen That's because `Buffer.alloc` was actually added in 5.10 and back port to node.js 4.5

**Comment by vkarpov15** [comment]
Thanks for finding this @Fonger, great job :+1:

**Comment by Fonger** [comment]
They merged my 2 pull requests with [this comment](https://github.com/mongodb-js/mongodb-core/pull/346#issuecomment-414306960):

> We are indeed deprecating node v4 in the upcoming months, but in the meantime should in fact be using this. Thanks for the contribution!
