### ISSUE TITLE
[QUESTION] Updating Part of String Without Querying Docs

### ISSUE THREAD

**Issue by spolat** [Automattic/mongoose#6891]
```json 
"dependencies": {
    "mongoose": "^5.2.8"
  }
```
```json
"coverImage" : {
        "url" : "http://foo.com/media/hgfr2um5oqibs8lbjbv7.jpg",
        "size" : 0,
        "filename" : "hgfr2um5oqibs8lbjbv7.jpg"
    }
```

Hi everyone. I'm trying to update url to `https://bar.com.s/media/hgfr2um5oqibs8lbjbv7.jpg` without querying doc and updating. Is there anyway to do it ?

**Comment by Fonger** [comment]
Unfortunately you can't not update the document based on it's value.

This is not supported by mongodb. There is an [unresolved feature request at SERVER-1765](https://jira.mongodb.org/browse/SERVER-1765) and it was open 8 years ago. I wonder if they will support it. You can log in to up vote for this feature.

However, there is another way to do so by using aggregation.
You can get what you want within a single aggregation query:

```js
Image.aggregate()
  .match({ size: 0 })
  .project({ filename: 1, size: 1, url: { $concat: ['https://bar.com.s/media/', $filename] })
  .exec()
  .then(res => console.log(res));
```

Although you can't modify the data simultaneously, you can use [$out](https://docs.mongodb.com/manual/reference/operator/aggregation/out/) to save the aggregation result to another collection. For example:

```js
Image.aggregate([
  { $match: { size: 0 } }, // condition
  {
    $project: {
      size: 1,
      filename: 1,
      url: { $concat: ['https://bar.com.s/media/', '$filename'] }
    }
  },
  { $out: 'collectionName' }
]).exec(function(err, result) {
  if (err) console.error(err);
  console.log('done', result);
})
```

**Comment by spolat** [comment]
Hey @Fonger  just resolved my issue by writing query in the robomongo like below. Thanks for the reply :)

```javascript
db.media.find({mediaContainer:"ContainerS3"}).forEach(function(e,i) {
    e.url=e.url.replace("//a.n.com","//b.n.com");
    db.media.save(e);
});
```
