### ISSUE TITLE
Mongoose Create in Lambda not executing when tested as event in AWS Lambda console

### ISSUE THREAD

**Issue by galaxy79** [Automattic/mongoose#6894]
**BUG**

I have an AWS lambda function that works fine through serverless when I tested. The document is created in the mlabs server without any issue. But the same function when I test through AWS Lambda test event returns me null without creating the document in the DB. On debug, the console.log provided after model.create method is not even executed. There is no error in execution. 

`       
          module.exports.createProduct = async (event,context) =>      
           {context.callbackWaitsForEmptyEventLoop = false;
              var mongoose = await dbConnect(mongoString)
              let respmsg = {
              statusCode: '',
              headers: {
                "Content-Type": "*/*"
              },
              body: {}
              }
              console.log("my event is ", event.body);
             const productreq = event.body;
             console.log(productreq);
             try {
                 var productinstance = new prdModel(productreq);
                console.log("creating model")
                prdModel.create(productreq, function (err, doc) {
                    if (err) {
                    console.log(err.message)
                    respmsg.statusCode = 500
                    respmsg.body = JSON.stringify({
                      "message": err.message
                    })
                    console.log("response message is ",respmsg)
                    return respmsg
                  } else {

          respmsg.statusCode = 201
          respmsg.body = JSON.stringify({
            id: doc.id
          })
          console.log("response message is ",respmsg)
          return respmsg
        }
                });
     
            } catch (error) {

              console.log("Error message is ",error)
    
            }

          }
`

AWS Lambda Logs:

`
    START RequestId: f485539d-a341-11e8-9f9d-432e5751767e Version: $LATEST
2018-08-18T23:53:52.265Z	f485539d-a341-11e8-9f9d-432e5751767e	(node:1) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2018-08-18T23:53:53.286Z	f485539d-a341-11e8-9f9d-432e5751767e	my event is { productcategory: 'test',
department: 'test',
producttitle: 'test',
productseller: 'test',
productquantity: '2',
sizemap: [ { size: 'test' } ],
colormap: [ { color: 'test' } ],
productdescription: 
[ { feature: 'test' },
{ feature: 'test' },
{ feature: 'test' },
{ feature: 'test' } ],
productimages: 
[ { imagepath: 'test' },
{ imagepath: 'test' },
{ imagepath: 'test' },
{ imagepath: 'test' } ],
price: { marketprice: '900', saleprice: '800' } }
2018-08-18T23:53:53.288Z	f485539d-a341-11e8-9f9d-432e5751767e	{ productcategory: 'test',
department: 'test',
producttitle: 'test',
productseller: 'test',
productquantity: '2',
sizemap: [ { size: 'test' } ],
colormap: [ { color: 'test' } ],
productdescription: 
[ { feature: 'test' },
{ feature: 'test' },
{ feature: 'test' },
{ feature: 'test' } ],
productimages: 
[ { imagepath: 'test' },
{ imagepath: 'test' },
{ imagepath: 'test' },
{ imagepath: 'test' } ],
price: { marketprice: '900', saleprice: '800' } }
2018-08-18T23:53:53.309Z	f485539d-a341-11e8-9f9d-432e5751767e	creating model
END RequestId: f485539d-a341-11e8-9f9d-432e5751767e`

DB Connection Function:
`async function dbConnect(mongoString) {

  var options = {
    //native_parser: true,
    //poolSize: 1,
    bufferCommands:false,
    bufferMaxEntries: 0
    
  }
 // mongoose.set('bufferCommands', false);
  try {

    if (mongoose.connection.readyState === 0) {

      return await mongoose.createConnection(mongoString,options)

    };
  } catch (ex) {
    console.log("Error in connecting to database " + ex)
  }
};`

NodeJs:8.10
Mongoose Version:5.2.9
MongoDB:3.6.6

**Comment by vkarpov15** [comment]
That's because you're doing work in the callback to create() and not awaiting on create(). Instead of `Model.create(doc, fn)`, just do `await Model.create(doc); fn();`
