### ISSUE TITLE
translateAliases not recognized in Typescript

### ISSUE THREAD

**Issue by jackswift21** [Automattic/mongoose#6896]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Migrating a working backend from pure JS to TS, and came across a thorn I cannot seem to fix without bothering the mongoose team. Using 5.0.3 in the JS version of the app, I was easily able to integrate the use of aliases into my project with no problems at all. Absolutely love that functionality... however, TS does not.
![image](https://user-images.githubusercontent.com/33332432/44305906-8e4ab180-a349-11e8-8911-f95b782b556f.png)
I attempted to create a mongoose.d.ts and add translateAliases from an interface extending the Mongoose namespace and Model interface. TS has no idea what Im talking about and I'm not very good at creating type files on the fly. I also attempted to add a standalone "translateAliases" type within the model file and then add it to the model's type definition before the actual model schema declaration. Negatory. I believe translateAliases just needs to be added as a property to the mongoose.model interface/type (if there is such a thing), but this is well beyond my scope. Apologies for any wordiness or lack of clarity/coded reproduction, this is my first time ever submitting a package issue. Thanks all!

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
export type UserModel = mongoose.Document & {handle:string};
const user = new mongoose.Schema({h:{type:String,alias:"handle"}});
const User = mongoose.model("User",user);

/* in some other file */
const handle = "Iwantmyaliases";
const user = new User({handle});
user.save().then(() =>
User.findOne(User.translateAliases({handle})).then(someuser => console.log("here's",someuser.handle)));
// prints "here's Iwantmyaliases"

**Please mention your node.js, mongoose and MongoDB version.**
node 8.11.1, mongoose 5.2.9 (was 5.0.3 but upgraded to be sure), mongo 3.2.9

**Comment by vkarpov15** [comment]
What typescript bindings are you using? We don't have officially supported ts bindings, so you would need to report a bug in the ts bindings' GitHub repo

**Comment by jackswift21** [comment]
Not sure how to properly answer that, but my typescript version is 2.7.2 and @types/mongoose is 4.7.34.

**Comment by vkarpov15** [comment]
You'll need to open up an issue on the @types/mongoose GitHub repo here: https://github.com/DefinitelyTyped/DefinitelyTyped#readme .
