### ISSUE TITLE
createConnection while the DB is down, causes the app to crash

### ISSUE THREAD

**Issue by tomgrossman** [Automattic/mongoose#6903]
**Do you want to request a *feature* or report a *bug*?**

**Bug - critical**
The bug was fixed in `node-mongodb-native` but not in a version yet:
https://github.com/mongodb/node-mongodb-native/commit/918a1e06fbf2cf672b0cff97681972100e7569bb#diff-12bc6199a1348e0428b4b9ebeb881206

The bug occurs in `mongoose` `5.2.9` while in `5.2.8` it's ok

**What is the current behavior?**
Connecting to a `mongos` or a `mongod` instance while the DB is down, crash the app.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
    const mongoose = require('mongoose');

    const DB_URL = 'mongodb://localhost:2244,localhost:2255/test_database';

    const ConnectionOptions = {
        poolSize: 20,
        socketTimeoutMS: 0,
        connectTimeoutMS: 0,
        useNewUrlParser: true
    };

    mongoose.createConnection(DB_URL, ConnectionOptions, (err) => {
        if (err) {
            console.log(err.message)
        }
    });
```
**What is the expected behavior?**
In `mongoose` `5.2.8` the same code while the DB is down, just returns an error to the `createConnection` function (and console log it). but in `5.2.9` the app crashes with the following error:

> TypeError: Cannot read property 'close' of undefined
    at topology.connect (/home/tom/intsights/test-project/node_modules/mongodb/lib/operations/mongo_client_ops.js:412:16)
    at Mongos.<anonymous> (/home/tom/intsights/test-project/node_modules/mongodb/lib/topologies/mongos.js:231:11)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Mongos.emit (events.js:211:7)
    at Timeout.<anonymous> (/home/tom/intsights/test-project/node_modules/mongodb-core/lib/topologies/mongos.js:759:14)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Waiting for the debugger to disconnect...

**Please mention your node.js, mongoose and MongoDB version.**
node.js - 8.11.4
mongoose - 5.2.9
MongoDbB - 3.6

**Comment by actraiser** [comment]
Thanks for the info! I noticed the same error this morning after upgrading from mongoose 5.2.8 to 5.2.9 and my mocha tests started to fail. Now it's clear that your reported bug is triggered when dropping the database after each test. Switched back to 5.2.8 for the time being.

Greets
-act

**Comment by lineus** [comment]
This is related to [a merged pr on the native driver here](https://github.com/mongodb/node-mongodb-native/pull/1812) that hasn't been released just yet. The fix for this will be in the next native driver version.
