### ISSUE TITLE
Missing Query.prototype.getOptions() helper

### ISSUE THREAD

**Issue by LeoPapais** [Automattic/mongoose#6906]
Hi There,

I couldn't find a way to access the 'options' parameter inside a ```.pre('update'``` middleware. I see in the docs that ``` Query.prototype.getQuery() ``` and  ```Query.prototype.getUpdate() ``` are available but I can't figure out if my ``` update ``` is set to be  ``` multi: true ``` or ``` multi: false ```.

Can you help me please?

**Comment by Fonger** [comment]
You can just use `this.options` to access the query options.
It's nice to have a getOptions() helper though.

**Comment by LeoPapais** [comment]
Ok. I just couldn't find anything in the docs. Thanks for you answer :)
