### ISSUE TITLE
Single values are not cast to Array anymore

### ISSUE THREAD

**Issue by SimonMARTIN87** [Automattic/mongoose#6908]
Hi.
This is not a trivial issue to explain, it might be easier with an little story.
Last year, I had this model : 
`mongoose.model('Job', 
    {company :{
                type: Schema.Types.ObjectId,
                ref: 'Company',
                required: true
            },
 ...}
`

However, the product has evolved, and now a "Job" can refer to multiple "Companies". So i made this change : 
`mongoose.model('Job', 
    {company : [{
                type: Schema.Types.ObjectId,
                ref: 'Company',
                required: true
            }],
 ...}
`

With mongoose 4.x, no problems, with that query : 
`job.find({...}).populate('company').exec()`
ALL the docs in the collections were populated with arrays, even if I never made any migration. I guess mongoose 4 made a forced cast...
But now, with mongoose 5.2.9 (on a mongoDB 3.6), some of the "old" items in the collection (created before the change in the model) are directly populated with a `Company` object, NOT WITH AN ARRAY!
So later in my code, when I try to `map`on that member, I obviously get a TypeError `job.company.map is not a function`.

What the hell am I missing??  Mongoose 4 was working like a charm on that specific problem, and I can't believe it's a regression, so I guess there is an option somewhere... however, I can't find anything about it.

In advance, thanks for helping me!
Simon.

**Comment by SimonMARTIN87** [comment]
Update.
While searching for a solution, I thought that I could use the validation method to force a cast. So I just made a simple function, fetching all the `jobs` and calling `.save()` on them.
However, the save DO NOT THROW ANY ERROR, even if the `company` member is NOT an array!!!!

I'm totally loosing my mind... I must be missing something. Please, help me.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap

**Comment by SimonMARTIN87** [comment]
Thanks for investigating.
For now I made a dirty forced cast in my model : 
`job.company = Array.isArray(job.company) ? job.company : [job.company]`
But this situation (switching from a 1-to-1 to a 1-to-many relation) is something that can happen quite often in a project. 
On a project management level, writing a migration script would probably be the better way to do, but in a "we need a quickfix" emergency situation (nooo, that never happens...), mongoose 4 was actually my savior!
