### ISSUE TITLE
Model.create method does not return session on documents

### ISSUE THREAD

**Issue by felipe-augusto** [Automattic/mongoose#6909]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When saving a model using `Model.create` and passing a session, documents returned from the operation does not keep the same session.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just start a session and a transaction, create a document and try to save this document after changing some property.
```js
const session = await mongo.client.startSession({ causalConsistency: true })
session.startTransaction({ mode: 'primary' })

let customer = (await Customer.create([params], { session }))[0]
// ...
customer.newProp = true
await customer.save() // DocumentNotFoundError: No document found for query "{ _id: 5b7c3e5a67989e4bc54ccc6b }"
```
**What is the expected behavior?**
I expect that the documents returned from the `Model.create` should contain the associated session passed when I created those documents. I can fix this manually by resetting the session, but I do not think this is the correct behavior:

```js
const session = await mongo.client.startSession({ causalConsistency: true })
session.startTransaction({ mode: 'primary' })

let customer = (await Customer.create([params], { session }))[0]
// ...
customer.newProp = true
customer.$session(session) // fix session
await customer.save() // now this works
```

**Please mention your node.js, mongoose and MongoDB version.**
node 8.1.2
mongoose 5.2.9
mongo 4.0.1

**P.S:** If it is possible to write the line below in a better way, please let me know:
`let customer = (await Customer.create([params], { session }))[0]`

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix asap
