### ISSUE TITLE
Model.countDocuments() throwing error when using $near

### ISSUE THREAD

**Issue by peteboere** [Automattic/mongoose#6911]
**Do you want to request a *feature* or report a *bug*?**
bug (unless this is intended behaviour and I can't find documentation)

**What is the current behavior?**
Throws error:
MongoError: $near is not allowed inside of a $match aggregation expression

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute Model.countDocuments() with a filter that includes a $near expression.

**What is the expected behavior?**
That it does not throw an error (like Model.count())

**Please mention your node.js, mongoose and MongoDB version.**
mongo v3.4.13
node v8.11.1
mongoose v5.2.9

**Comment by Fonger** [comment]
This is an [underlying library issue](https://github.com/mongodb/node-mongodb-native), they use [aggregation and $match in pipeline](https://github.com/mongodb/node-mongodb-native/blob/master/lib/operations/collection_ops.js#L193-L218) to count the documents.

**Comment by vkarpov15** [comment]
@Fonger is correct, we still need to find a workaround for this. Until we do, please continue to use `count()`. Even though it is deprecated, count() will not be formally removed from the API for a while

**Comment by Fonger** [comment]
@vkarpov15 @peteboere 

I think I find a workaround and it makes sense.
Since what we want is counting, you can use `$center` or `$centerSphere` to replace the query.

$near will return the result from nearest to the furthest.
If what we want is just counting, we don't need such sorting.

So replace $near with [$geoWithin + $centerSphere](https://docs.mongodb.com/manual/reference/operator/query/centerSphere/)

For example, the following works in aggregation and it will also use geo index
```js
    const area = { center: [<longitude>, <latitude>], radius: <radius>, spherical: true }
    Model.where('location').within().circle(area).countDocuments().then(...)
```

**Comment by Fonger** [comment]
@vkarpov15 I find these [migration guide](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#countDocuments) description in mongodb docs

> **Note**: When migrating from Collection#count to Collection#estimatedDocumentCount
the following query operators must be replaced:
>
> | Operator | Replacement |
> | -------- | ----------- |
> | `$where`   | [`$expr`][1] |
> | `$near`    | [`$geoWithin`][2] with [`$center`][3] |
> | `$nearSphere` | [`$geoWithin`][2] with [`$centerSphere`][4] |

[1]: https://docs.mongodb.com/manual/reference/operator/query/expr/
[2]: https://docs.mongodb.com/manual/reference/operator/query/geoWithin/
[3]: https://docs.mongodb.com/manual/reference/operator/query/center/#op._S_center
[4]: https://docs.mongodb.com/manual/reference/operator/query/centerSphere/#op._S_centerSphere
