### ISSUE TITLE
pre remove middleware no longer called

### ISSUE THREAD

**Issue by lobermann** [Automattic/mongoose#6914]
**Do you want to request a *feature* or report a *bug*?**
Undocumented Behaviour, Possible Bug?

**What is the current behavior?**
Using following code from previous version with the latest version:
```
let user = await Models.user.findById(req.params.id)
...
await user.remove()
```

When using Object.remove() it also calls `schema.pre('remove', function...` . But now in the latest version when using remove it prints: `collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.`. But with that the pre('remove') no longer gets called. I tried the deleteOne and the oder findByIdAndDelete() calls but the pre('remove') gets never called.

**What is the expected behavior?**
I can not find in the docs if the pre('remove') still exists and if what action actually invoked it.

**Please mention your node.js, mongoose and MongoDB version.**
node v9.5.0
mongoose 5.2.9
mongodb 3.6

**Comment by lineus** [comment]
The following script  shows that the remove hooks are still being called despite the deprecation warnings ( deprecation warnings covered in #6880 ):

### 6914.js
```js
#!/usr/bin/env node
'use strict';

var preHookWasCalled = false;
var postHookWasCalled = false;

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

schema.pre('remove', function() {
  preHookWasCalled = true;
});

schema.post('remove', function () {
  postHookWasCalled = true;
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'one' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  let doc = await Test.findOne();
  await doc.remove();
  let { length } = await Test.find();
  assert.strictEqual(mongoose.version, '5.2.9');
  assert.strictEqual(preHookWasCalled, true);
  assert.strictEqual(postHookWasCalled, true);
  assert.strictEqual(length, 0);
  console.log('all tests pass');
  return conn.close();
}

run();

```
### Output: 
```
issues: ./6914.js
(node:4593) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:4593) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:4593) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
all tests pass
issues:
```

The current docs still have the remove hook [documented on the middleware page](https://mongoosejs.com/docs/middleware.html)

Only calling `.remove()` **on a document** will fire remove hooks. 
[Calling Model.remove](https://mongoosejs.com/docs/api.html#model_Model.remove) or [Model.deleteMany](https://mongoosejs.com/docs/api.html#model_Model.deleteMany) or [Model.deleteOne](https://mongoosejs.com/docs/api.html#model_Model.deleteOne) will not fire remove hooks.

**Comment by lobermann** [comment]
> Only calling .remove() on a document will fire remove hooks.
Calling Model.remove or Model.deleteMany or Model.deleteOne will not fire remove hooks.

I read the issue #6880 , so that is clear to me now.

But, if Document.remove() get's deprecated and removed at some point, what will be the new way of removing a document that will invoke the hooks?

**Comment by lineus** [comment]
document.remove() has been updated in the master branch to call `collection.deleteOne` instead of `collection.remove()`. The hooks will still be called and no further deprecation warnings will come from calling document.remove(). The next release of mongoose will contain the fix for this 👍

**Comment by lobermann** [comment]
Awesome! Thank you very much for your assistance! Appreciate it.
