### ISSUE TITLE
Finding and saving document with Date object not working

### ISSUE THREAD

**Issue by benoit-hocquet** [Automattic/mongoose#6918]
mongoose 5.2.9 ;
Have a schema with the {type: Date}
Creation of a first document with Date.now() is OK.

Finding the document, then modifying with new Date() then saving : **KO**. (The db is not updated, but the promise returns successfully)

Workaround:
finding the document, then modifying with (new Date()).**toString()** : **OK**.

expected behaviour:
when schema has a prop with Date type, it should update and save succesfully the prop is given a Date object.

**Comment by freewil** [comment]
You're saving the date with a different type each time. You should make sure you're always using a Date object.

```
> typeof Date.now()
'number'
> typeof new Date()
'object'
> typeof new Date().toString()
'string'
```

**Comment by vkarpov15** [comment]
Please provide code samples, converting prose to code is error prone
