### ISSUE TITLE
mongoid with usePushEach

### ISSUE THREAD

**Issue by ffbeatsolutions676** [Automattic/mongoose#6932]
I am using mongoid in my application for models/ saving data. It was working with mongoDB version 3.4.
Now i have upgraded mongoDB version to 3.6. I can't degrade it's version.

Can anyone help me out in this.

**Comment by vkarpov15** [comment]
If you're using mongoid, you should probably open up an issue on the [mongoid GitHub repo](https://github.com/mongodb/mongoid). Mongoose !== mongoid.
