### ISSUE TITLE
Isolate objects (Schema, Query, etc...) for differents connections.

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#6933]
**Do you want to request a *feature* or report a *bug*?**
don't know, it depends on the point of view
**What is the current behavior?**
I've a FW app with multisite support, so inside a site libraries you can define extra schematypes, plugins, schemas, models, etc... but as Schema object is not isolated from connection, if I define a type in one site it's spreaded to the rest, I use new mongoose.Mongoose() to try to isolate as much as I can but I've this issue, I guess it's because this objects are in the prototype definition.

Is there anyway to avoid this definition replica between differents mongooses?

If not, maybe the solution is to require without cache.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I hope when you use a new mongoose.Mongoose() the objects inside the returned object were isolated.
**Please mention your node.js, mongoose and MongoDB version.**
Node 10.8.0, mongoDB 3.6.4, mongoose 5.2.10

**Comment by vkarpov15** [comment]
I don't understand the issue, can you elaborate with some code samples please?

**Comment by chumager** [comment]
Hi, maybe what I ask is too specific, for example, I've 2 connections, with different models, in one I set a new schema type, let's say type "a" with a populate property in the options, with a select. In the other connection I have the same type "a" but I don't want to set the select property in the populate field, but it seems that Schema connection property is passes as prototype, so when I define a schema type in one connection it's defined for all my connections, same for Query object, even if I use new mongoose.Mongoose.

That's why i suggest maybe a solution for my problem is to require without cache. 
Other solution could be passing a new (Schema and Query) to the prototype or maybe the objects like Type in Schema could be defined isolates and the overcharged with the core definitions.

Regards.

PS:I'll try to disassemble my code to show you an example, for now I've my code in severals archives all of then parsed in my framework.

**Comment by vkarpov15** [comment]
Let me just rephrase your question in my own words to make sure I understand: you're creating a custom schema type as demonstrated in the [custom schema types docs](https://mongoosejs.com/docs/customschematypes.html), but when you attach it to an instance of `new Mongoose()`, all mongoose instances get that schema type?

**Comment by chumager** [comment]
I copied my code from that page, the problem is I have several connection isolated and want to have the same type defined differently in each new mongoose but it's copied, so the last one gets the type defined. That's why I suggest to make the new mongoose with all the prototypes defined as new with no object references to avoid to share the same object, it's like you allow to have different connections but not allow to have diferents schema objects nor diferents schema types.
