### ISSUE TITLE
Push in nested array

### ISSUE THREAD

**Issue by mirik999** [Automattic/mongoose#6934]
Hi people, i am new in mongoose. I cant find any example or guide how to change data in nested array. Screen attached:

![screenshot_8](https://user-images.githubusercontent.com/29675733/44746405-55fe5c80-ab1b-11e8-884d-4822e8f90139.png)

P.S. i am using latest version mongoose and nodejs v10.6.0

**Comment by lineus** [comment]
@mirik999 Here is an example that uses 2 different methods to update values of specific subdocuments contained in an array. 

*The first method `remote()` issues one call to the db to perform the update.* 

*The second method `local()` issues two calls to the db, one to first retrieve the document, and a second to save the updated document.*

I think the better choice is the first, as it incurs less overhead, but the syntax requires some research when first starting out with mongodb.

### 6934.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  arr: [{ x: String }]
});

const Test = mongoose.model('test', schema);

const test = new Test({ 
  arr: [
    { x: 'one' }, 
    { x: 'two' }, 
    { x: 'three' }
  ]
});

function remote(id) {
  let cond = { _id: test.id, 'arr._id': { $eq: id } };
  let update = { $set: { 'arr.$.x': '2' } };
  return Test.updateOne(cond, update);
}

async function local(id) {
  let doc = await Test.findOne({});
  doc.arr.id(id).set('x', '3');
  return doc.save();
}

async function run() {
  await conn.dropDatabase();
  await test.save();
  const idFor2 = test.arr[1]._id;
  const idFor3 = test.arr[2]._id;

  await remote(idFor2);
  await local(idFor3);

  let updated = await Test.findOne();

  assert.strictEqual(updated.arr[0].x, 'one');
  assert.strictEqual(updated.arr[1].x, '2');
  assert.strictEqual(updated.arr[2].x, '3');
  
  console.log('All assertions pass.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6934.js
All assertions pass.
issues:
```

**Comment by mirik999** [comment]
lineus, thanx, but what is it ? i am new beginner on mongoose , i am trying to understund how this code works but i cant. This is my code where i want to implement:
![screenshot_9](https://user-images.githubusercontent.com/29675733/44797125-7bdd3d00-abbf-11e8-845f-d4194f63d34f.png)

**Comment by lineus** [comment]
@mirik999 can you join us on either [Gitter.im](https://gitter.im/Automattic/mongoose) or [Slack](https://mongoosejsteam.slack.com/) to chat about it in real time?

**Comment by mirik999** [comment]
yes ofcourse.
