### ISSUE TITLE
What are the plans of Mongoose to support BigInt?

### ISSUE THREAD

**Issue by koresar** [Automattic/mongoose#6936]
Starting node.js v10.3 the new data type was introduced - [BigInt](https://github.com/tc39/proposal-bigint). It's [Stage 3](http://2ality.com/2018/02/ecmascript-2019.html) atm.

Are there any plans or work going to support it same as `Number`, `Buffer`, `Date`, `Map` etc are [supported](https://mongoosejs.com/docs/schematypes.html)?

**Comment by Fonger** [comment]
MongoDB does not support BigInt type atm.
As long as mongodb does not support it, mongoose shouldn't support it.

Creating a mongoose plugin for BigInt is possible though however you have to cast BigInt to string or binary in MongoDB.

**Comment by vkarpov15** [comment]
This is something we should be able to add for the future. JavaScript BigInts are just 64 bit ints, and MongoDB [does support 64 bit ints](http://bsonspec.org/spec.html), so we would just need to expand [mongoose-long](https://www.npmjs.com/package/mongoose-long) to cast BigInts. Should be doable.

**Comment by koresar** [comment]
So which is right Vitaliy?

Mongoose do not plan to support BigInt natively.

Mongoose plans to support BigInt natively.

Mongoose is indecisive at the moment.

**Comment by Fonger** [comment]
@koresar Sorry I didn't know that BigInt was just 64 bit int so @vkarpov15 was right.

Mongoose will support BigInt because MongoDB has Long type (basically the same)
There's an existing plugin called [mongoose-long](https://github.com/mongoosejs/mongoose-long) which can do this. This is doable by casting BigInt to BSON.Long.

I think if if BigInt is out, it's time to consider support it by native. Not just in a plugin.
That's just my opinion though.

**Comment by koresar** [comment]
I've taken a deeper look at the `BigInt`. It's definition is: _**Arbitrary** Precision Integer_. This means they are not 64 bit ints.
https://github.com/tc39/proposal-bigint

Run this line in latest Chrome console:
```js
const myBigInt = 2n**524288n;
console.log(myBigInt);
```
It will render 157828 characters long string!

So, @Fonger you were actually right in the beginning. I really doubt MongoDB would ever support this type of data. :)

Let me clarify for future: mongoose does not support ESNext `BigInt` natively and do not plan to.

Thanks you all!
Cheers.

**Comment by vkarpov15** [comment]
Ah ok, I misread [this part of the BigInt spec](https://github.com/tc39/proposal-bigint#other-api-notes). This means we would need a new plugin, mongoose-long won't work. MongoDB does support storing binary data so we might store bigints using buffers. Thoughts?

**Comment by koresar** [comment]
Sounds like a plan. The new plugin name better be `mongoose-bigint` (not yet taken).

**Comment by nodegin** [comment]
This is really needed, Node.js now support BigInt natively and we definitely do not want to deal with Decimal128.

**Comment by vkarpov15** [comment]
@Fonger that's an interesting idea, we should be able to store BigInts as buffers, but then you won't be able to do `$inc`, etc.
