### ISSUE TITLE
about 2dsphere search

### ISSUE THREAD

**Issue by mambahao** [Automattic/mongoose#6937]
I updated to 5.2.10 at today, but I found a problem.

I have a field is coords: { type: [Number], index: '2dsphere' }

I use the query 

Store.find({ status }).where('coords').near({ center: { type: 'Point', coordinates }, maxDistance }).limit(parseInt(limit)).populate('tags', 't')

The query is working at yesterday, but I get a error now

Cannot read property 'path' of undefined
node_modules/mongoose/lib/schema/number.js:214:31

Please check and help me, thank you very much.

**Comment by stockrel** [comment]
Same here. Switching back to 5.1.0 fixes the problem for me.
