### ISSUE TITLE
ReferenceError: returnVal is not defined

### ISSUE THREAD

**Issue by cacothi** [Automattic/mongoose#6949]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
ReferenceError: returnVal is not defined

**If the current behavior is a bug, please provide the steps to reproduce.**

file: mongoose/lib/schematype
line: 903 

`function asyncValidate(validator, scope, value, props, cb) {
  let called = false;
  const returnVal = validator.call(scope, value, function(ok, customMsg) {
    if (called) {
      return;
    }
    called = true;
    if (typeof returnVal === 'boolean') {
      return;
    }
    if (customMsg) {
      props.message = customMsg;
    }
    cb(ok, props);
  });`

**What is the expected behavior?**
if (typeof returnVal === 'boolean') {

supposed to be

if (typeof customMsg === 'boolean') {

file: mongoose/lib/schematype
line: 903 

**Please mention your node.js, mongoose and MongoDB version.**

    "mongoose": "^5.2.12",

**Comment by Fonger** [comment]
Fixed in #6950
