### ISSUE TITLE
How to remove the all indexes of  the array of sub-documents in the array without passing any args about the indexes of the array sub-document's fields?

### ISSUE THREAD

**Issue by fahidarif** [Automattic/mongoose#6951]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
I don't understand the issue, can you please clarify with code samples?
