### ISSUE TITLE
[QUESTION] Partitioning - workaround?

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#6964]
This is neither a feature request nor bug report, I'm asking how I could accomplish partitioning via workaround and would like to get your feedback:
I have a pretty big collection ~50G (more than 100.000.000 entries) which is also one very heavily accessed one. It gets updates and a lot of reads. This collection is already sharded, but now I was thinking about why not splitting it up? There are basically 3 countries combined in there, so splitting by country, would already allow a easy and great partitioning of this collection.
So far so good, mongodb does not support partitioning though (https://jira.mongodb.org/browse/SERVER-2097). So I was thinking of "implementing" my own method:

Using one model, but specifying a different model name for each country.
e.g. exports.module = (country) => mongoose.model('Collection'+country, mongooseSchema);
and then grabbing the correct model with myPartionedCollection('at').

It's not super elegant, I would always need the correct country beforehand, but as my shard key is part of this already it's doable.

Would that give me actually any benefits? Do you think this approach is "valid"? Or do I break mongoose with it? ;)

Thanks
Simon

**Comment by vkarpov15** [comment]
Nothing wrong with it at all. You can still populate using refPath, so I don't see any reason why this wouldn't work well. Feel free to reach out if you have any problems, I'm happy to help.

**Comment by simllll** [comment]
Yeah thanks for your response, for reference if someone is thinking about the same:
I have a model that returns a new instance of the schema via function. It's important that you really make a new instance of the schema,otherwise some parameters are overwritten.
The benefits on my side are great, I even could drop some indexes and save disk space!

**Comment by vkarpov15** [comment]
@simllll I'm glad the function approach works for you, but any particular reason why you don't just use `clone()`? https://mongoosejs.com/docs/api.html#schema_Schema-clone

**Comment by simllll** [comment]
Wasn't ware of clone() looking into it right now :+1:
