### ISSUE TITLE
Confusing docs around index creation

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#6966]
The docs state `Indexes are created in the background by default. Specify background: false to override.`. 

I took this to mean `background: false` would cause mongoose to invoke a blocking request to create the index before moving forward. This is what I thought was the case.. for years... but actually testing this feature out and seeing 0 indexes being created on the collection (apart from the `_id`) is the actual output.

Or am I actually right and indexes should be created? Either way, it would be a very helpful update to the docs.

**Comment by Fonger** [comment]
Sound like you have an error occurred during the creation of the index and you doesn't catch it.

You can call [Model.init()](https://mongoosejs.com/docs/api.html#model_Model.init) to catch the error.
If you don't do this, the index creation will fail in silence ( See #6955 ).

Mongoose should document this behavior indeed.

**Comment by govindrai** [comment]
@Fonger Thanks for responding. I did not know about Model.init()! It did show me errors, which I fixed but unfortunately doesn't solve my problems as it doesn't seem to _properly_ be to doing its job of "performing an async initialization of the model against the MongoDB". I will open a separate ticket for that.

**Comment by vkarpov15** [comment]
@Fonger mongoose 5 should throw an error if index build fails and the error isn't handled. I suppose the docs on background index builds are overdue for some maintenance, will look into this
