### ISSUE TITLE
Model.init() doesn't create all indexes

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#6967]
Here's my deployment file:

```
const db = require('../lambda/modules/db');
const User = require('../lambda/models/User');

async function createDatabase() {
  try {
    await db.connect();
    await db.dropDatabase();
    await User.init();
    const indexes = await User.listIndexes();
    console.log(indexes);
    await db.disconnect();
  } catch (e) {
    console.log('error');
    console.log(e);
    process.exit(1);
  }
}

createDatabase();
```

Here's what the logging returns: 
```
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: false })
DB Connection Created
DB Dropped Successfully
Took 0.008466666666666667 minutes
Mongoose: users.ensureIndex({ phoneNumber: 1 }, { unique: true, background: false })
Mongoose: users.ensureIndex({ location: '2dsphere' }, { background: false })
Mongoose: users.listIndexes()
[ { v: 2, key: { _id: 1 }, name: '_id_', ns: 'bru-test.users' },
  { v: 2,
    unique: true,
    key: { phoneNumber: 1 },
    name: 'phoneNumber_1',
    ns: 'bru-test.users',
    background: false },
  { v: 2,
    key: { location: '2dsphere' },
    name: 'location_2dsphere',
    ns: 'bru-test.users',
    background: false,
    '2dsphereIndexVersion': 3 } ]
DB Connection Closed
```

I create the DB connection, I drop the DB, then I initialize my User's model. However the email index never gets built. Why? (I do see the first ensureIndex command goes out first because the model is loaded through the require call. But that's why after I finish dropping the database, then I call User.init() to get it to create indexes which are on my schema but not in mongodb.

Also what is interesting is I don't see any debug logging from Mongoose when I call `Model.init()`. 

Thank you.

**Comment by Fonger** [comment]
The indexes are being created when you call mongoose.model(). Even if you don't explicitly call model.init(), mongoose will do that in background.

The indexed may be created and you then call dropDatabase() so the indexes are removed.
There's an open issue for this #6796.

**Comment by govindrai** [comment]
@Fonger Thank you for your response. The moment I add the `autoIndex` option, I start getting this error:

```
DB Connection Created
DB dropped successfully
Took 0.00165 minutes
Mongoose: users.listIndexes()
error
{ MongoError: Database bru-test doesn't exist
    at queryCallback (/Users/govindrai/Projects/bru/bru-backend/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /Users/govindrai/Projects/bru/bru-backend/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  ok: 0,
  errmsg: 'Database bru-test doesn\'t exist',
  code: 26,
  codeName: 'NamespaceNotFound',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1536012643 },
  '$clusterTime': 
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 2, high_: 1536012643 },
     signature: { hash: [Object], keyId: [Object] } },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by lineus** [comment]
This appears to indeed be a bug. Here's my repro script:

### 6966.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
}, { autoIndex: false });

schema.index({ name: 1 }, { unique: true, background: false });

const Test = mongoose.model('test', schema);

function save2SameNameDocs() {
  let obj = { name: 'same' };
  return Promise.all([Test.create(obj), Test.create(obj)]);
}

async function run() {
  let error;
  await conn.dropDatabase();
  await Test.init().catch(() => process.exit(1));
  await save2SameNameDocs().catch(e => { error = e; });
  
  try {
    assert.ok(error instanceof Error, 'error should be an Error');
  } catch (e) {
    console.error(e.message);
  }

  await Test.createIndexes()
    .catch(() => console.log('createIndexes failed because of existing docs'));
  
  return conn.close();
}

run();
```
### Output:
```
issues: ./6966.js
error should be an Error
createIndexes failed because of existing docs
issues:
```

It looks like `createIndexes()` is working correctly. @govindrai can you try that?

**Comment by govindrai** [comment]
Thanks for responding @lineus. I ran your example and got the same feedback. In your example, the reason `Model.init()` doesn't build the indexes and error out is because the `autoIndex` is set to `false`. In this case, there needs to be a manual call to `Model.createIndexes()`. 

Here's what the docs say verbatim:

> Performs any async initialization of this model against MongoDB. Currently, this function is only responsible for building indexes, unless `autoIndex` is turned off.

I think this statement can be improved, ("performs any async initialization" seems very vague") and state something around the lines of "Builds indexes against MongoDB for a model if `autoIndex` is enabled. To build indexes when `autoIndex` is turned off, manually call `Model.createIndexes()`.  Note: `autoIndex` is enabled by default."

The reason I started getting "the database doesn't exist errors" after enabling `autoIndex` was because I made a call to `Model.listIndexes()` which goes to MongoDB and gets a list, but because I never manually called `Model.createIndexes` no collection was ever created and consequently no database was created. wow. 😂

This also negates the solution provide by @vkarpov15, as init() will not build indexes if `autoIndex` is `false`:

> By default, Mongoose starts building indexes when you declare the model with mongoose.model(). If you want to manually call init() to build indexes, use mongoose.connect(uri, { autoIndex: false }). Does that work for you?

That thread should be updated with this note if you agree.

---

Nice, so that's out of the way. Unfortunately, this does not solve the issue in the first scenario, where `autoIndex` is enabled and after dropping the db, `Model.init()` does not many times build all the indexes since some of the `ensureIndex` calls end up going out before the database is dropped, but that will be covered by #6796.

**Comment by lineus** [comment]
@govindrai nice catch. I can't believe I missed that 👍 

Feel free to put in a PR for the docs if you like, I think a semi-colon separating the two current sentences would link the second idea to the first a little more clearly. Honestly though, after having read it in this context it seems pretty clear as-is.

**Comment by vkarpov15** [comment]
Yeah unfortunately calling `dropDatabase()` right after connecting is pretty messy. We need to improve that. What you need to do right now is set `autoIndex: false` and call [`Model.createIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.createIndexes) instead of `init()`.

@lineus @Fonger what do you think about making `dropDatabase()` cancel any in-flight `init()` calls and then the user can call `init()` again?

**Comment by Fonger** [comment]
@vkarpov15 sounds wise. #6796 can be closed too.
