### ISSUE TITLE
Array validator incorrectly failing on $pull

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6971]
Followup of https://github.com/Automattic/mongoose/issues/6889 and https://github.com/Automattic/mongoose/issues/6960. The first one is marked as fixed and the other one is categorized as enhancement instead of a bug, so I'm posting it separately as it's not exactly the same issue.

The repro script below demonstrates a valid use case for an array validator which is going to incorrectly fail on `$pull`:

```js
#!/usr/bin/env node
(async function () {
  const mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true});

  const reviewerSchema = new mongoose.Schema({
    name: String
  });

  const pullRequestSchema = new mongoose.Schema({
    reviewer: {
      type: [reviewerSchema],
      validate: {
        validator: function (arr) {
          return arr.length >= 2;
        },
        message: 'Pull request must have at least 2 reviewers.'
      }
    }
  });

  const Model = mongoose.model('pr', pullRequestSchema);
  await Model.findOneAndUpdate({}, {
    $pull: {reviewer: {name: 'John'}}
  }, {
    runValidators: true
  });
})();
```

Tested on mongoose 5.2.13

**Comment by vkarpov15** [comment]
@sebastian-nowak I looked into this and settled on just not running array validators on `$pull`. There's no good way for the validator to determine whether the array is in a `$pull` or `$set`, and you don't get access to the full array in `$pull`.

**Comment by foray1010** [comment]
if you really need this feature, you may have a look at mongo's `$jsonSchema`
https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/
