### ISSUE TITLE
Inner `required` validator fails on $pull

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#6972]
Required validator for a subdocument field fails on `$pull` even though the field is defined.

```js
#!/usr/bin/env node
(async function () {
  const mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true});

  const schema = new mongoose.Schema({
    someArray: {
      type: [{
        innerField: {
          type: mongoose.Schema.Types.ObjectId,
          required: [true, 'Should not fail']
        }
      }]
    }
  });

  const Model = mongoose.model('pr', schema);
  await Model.findOneAndUpdate({}, {
    $pull: {someArray: {innerField: '507f191e810c19729de860ea'}}
  }, {
    runValidators: true
  });
})();
```

As a side note, I don't think `required` validators should be called here at all, because the full subdocument isn't present and it's valid to omit fields in `$pull`. It's a query.

Tested on mongoose 5.2.13

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix

**Comment by sebastian-nowak** [comment]
Thanks @vkarpov15. Are you sure you wanted to tag it as an 'enhancement'? It's a pretty obvious bug, it's causing the `$pull` operation to fail in lots of scenarios when combined with global `runValidators` option. It's common to have a nested `required` validator, so it's definitely affecting lots of larger projects.

**Comment by vkarpov15** [comment]
Good point, we will treat this as a bug

**Comment by sebastian-nowak** [comment]
I've just updated to 5.2.17 and all of my tests are now passing. The repro code from the first post seems to be working correctly too. I don't know how, but it looks like it has been accidentally fixed :)

**Comment by vkarpov15** [comment]
Glad it works now :+1:
