### ISSUE TITLE
Cannot read property 'originalRequiredValue' at mongoose/lib/document.js:1483:18

### ISSUE THREAD

**Issue by Hyperblaster** [Automattic/mongoose#6974]
Really strange error i hit intermittently when 
```

TypeError: Cannot read property 'originalRequiredValue' of undefined
    at /node_modules/mongoose/lib/document.js:1483:18
    at Array.filter (<anonymous>)
    at _getPathsToValidate (/node_modules/mongoose/lib/document.js:1478:63)
    at model.Document.$__validate (/node_modules/mongoose/lib/document.js:1576:17)
    at /node_modules/kareem/index.js:276:8
    at _next (/node_modules/kareem/index.js:102:16)
    at process.nextTick (/node_modules/kareem/index.js:427:38)
    at process._tickCallback (internal/process/next_tick.js:112:11) TypeError: Cannot read property 'originalRequiredValue' of undefined
    at /node_modules/mongoose/lib/document.js:1483:18
    at Array.filter (<anonymous>)
    at _getPathsToValidate (/node_modules/mongoose/lib/document.js:1478:63)
    at model.Document.$__validate (/node_modules/mongoose/lib/document.js:1576:17)
    at /node_modules/kareem/index.js:276:8
    at _next (/node_modules/kareem/index.js:102:16)
    at process.nextTick (/node_modules/kareem/index.js:427:38)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

Line 1483 is here, it's possibly something to do with my schema fields being required?
```

function _getPathsToValidate(doc) {
  var i;
  var len;

  // only validate required fields when necessary
  var paths = Object.keys(doc.$__.activePaths.states.require).filter(function(path) {
    if (!doc.isSelected(path) && !doc.isModified(path)) {
      return false;
    }
    var p = doc.schema.path(path);
    if (typeof p.originalRequiredValue === 'function') {
      return p.originalRequiredValue.call(doc);
    }
    return true;
  });


```

Any help would be greatly appreciated, It's intermittent so it's hard to see if it's to do with a specific document or something else

**Comment by lineus** [comment]
We should probably change:
```
if (typeof p.originalRequiredValue === 'function') {
```
to:
```
if (p && typeof p.originalRequiredValue === 'function') {
```

I think it's worth investigating what's causing `schema.path()` to return an undefined value. 
@Hyperblaster Can you add your schema here? 

Thanks!

**Comment by Hyperblaster** [comment]
Yep, i just realised that I forgot to provide the mongoose version etc, I've just updated all our packages and now using 
Mongoose Version 5.2.13

The issue is now at
 /node_modules/mongoose/lib/document.js:1629:18

This part of the code doesn't seem to have changed, but just so you are aware of where it is now.

I think a simple check like you have above is the correct solution, but i can't seem to find out the schema it is that is causing this problem, i'll dig further

**Comment by vkarpov15** [comment]
@lineus your solution would help with this error, but the issue here is that the `this` value is wrong for some reason. Definitely worth investigating more. Do you have any idea what triggers this @Hyperblaster ?

**Comment by vkarpov15** [comment]
I haven't been able to repro this @Hyperblaster , I put the patch in and will release it with 5.2.18. But it would be helpful if you could provide an example of a schema that causes this issue. Since we can't reproduce it, we can't add a test that makes sure this issue doesn't happen again...

**Comment by Hyperblaster** [comment]
No problem. I haven’t been able to test yet as we had to downgrade the mongoose version because of the array to object population issue. If i can get some code to cause it again i’ll reopen with more details.

Thanks for all your hard work!
