### ISSUE TITLE
[Configuration] Hit into staled MongoDB connection on Lambda?

### ISSUE THREAD

**Issue by newbaluku** [Automattic/mongoose#6975]
**MongoError: no connection available for operation and number of stored operation > 0**

Encountered the above error in production running on Lambda randomly when I'm trying to reuse existing DB connection. I wonder if this is due to DB disconnection in the driver after a period of inactivity.

would like to check if there are any mongoose configurations that I could tweak to workaround the issue.

my code fragment for reusing DB connection is as followed:

```
let isConnected;

mongoose.Promise = global.Promise;

const connectToDatabase = () => {
  if (isConnected) {
    console.log('using EXISTING database connection...');
    return Promise.resolve();
  }

  const options = {};
  if (process.env.ON_SLS) {
    console.log('running on serveless, disable mongoose and MongoDB driver buffering...');
    // http://mongoosejs.com/docs/lambda.html
    // Buffering means mongoose will queue up operations if it gets
    // disconnected from MongoDB and send them when it reconnects.
    // With serverless, better to fail fast if not connected.
    options.bufferCommands = false; // Disable mongoose buffering
    options.bufferMaxEntries = 0; // and MongoDB driver buffering
  }

  console.log('CREATING a new database connection.');
  return mongoose.connect(process.env.DATABASEURL, options).then((db) => {
    isConnected = db.connections[0].readyState;
    console.log(`MongoDB - isConnected: ${isConnected}`);
  });
};
```

modules version:
node.js v8.1
mongoose v5.1.2
MongoDB v3.6.7 (hosted on Atlas)

full stack trace:
```
{ MongoError: no connection available for operation and number of stored operation > 0
    at Function.MongoError.create (/var/task/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:45:10)
    at Store.addObjectAndMethod (/var/task/node_modules/mongoose/node_modules/mongodb/lib/topologies/topology_base.js:78:18)
    at nextFunction (/var/task/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:602:39)
    at Cursor.next (/var/task/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:810:3)
    at Cursor._next (/var/task/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:202:36)
    at nextObject (/var/task/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:720:8)
    at next (/var/task/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:272:3)
    at executeOperation (/var/task/node_modules/mongoose/node_modules/mongodb/lib/utils.js:420:24)
    at Cursor.next (/var/task/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:258:10)
    at findOne (/var/task/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1349:10)
    at executeOperation (/var/task/node_modules/mongoose/node_modules/mongodb/lib/utils.js:420:24)
    at Collection.findOne (/var/task/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1339:10)
    at NativeCollection.(anonymous function) [as findOne] (/var/task/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:142:28)
    at NodeCollection.findOne (/var/task/node_modules/mquery/lib/collection/node.js:42:19)
    at model.Query.Query.findOne (/var/task/node_modules/mquery/lib/mquery.js:1816:20)
    at model.Query.Query._findOne (/var/task/node_modules/mongoose/lib/query.js:1529:22)
  name: 'MongoError',
  message: 'no connection available for operation and number of stored operation > 0',
  driver: true }
```

**Comment by vkarpov15** [comment]
Is the ON_SLS environment variable set? Also, how are you calling connectToDatabase() ?

**Comment by newbaluku** [comment]
the ON_SLS environment is set.

and connectToDatabase is called on every endpoint invocations in this function:

```
app.use((req, res, next) => {
  connectToDatabase().then(() => {
    next();
  })
  .catch((e) => {
    console.log('Failed to connect to MongoDB:', e);
    res.status(500).send();
  });
});
```

I have updated mongoose latest version (5.2.13) and didn't see this error in the last two days of running, will continue to monitor this..

**Comment by newbaluku** [comment]
// With serverless, better to fail fast if not connected.
    options.bufferCommands = false; // Disable mongoose buffering
    options.bufferMaxEntries = 0; // and MongoDB driver buffering

just wonder what is your rationale for above strategy, could you elaborate more?

**Comment by newbaluku** [comment]
still getting the error but happening at a lower rate compared to previous version.

**Comment by vkarpov15** [comment]
Re: the buffering strategy, its to avoid the case where you have a function hanging because Mongoose is disconnected. Having to go in and manually kill functions in lambda is very messy.

Also, in comment https://github.com/Automattic/mongoose/issues/6975#issuecomment-419680268 it looks like you're using Express as well? How are you using Express on Lambda?

**Comment by newbaluku** [comment]
> Re: the buffering strategy, its to avoid the case where you have a function hanging because Mongoose is disconnected. Having to go in and manually kill functions in lambda is very messy.
> 
> Also, in comment [#6975 (comment)](https://github.com/Automattic/mongoose/issues/6975#issuecomment-419680268) it looks like you're using Express as well? How are you using Express on Lambda?

I'm wrapped my Express object using the serverless-http npm module. It allows my code to run on Lambda with minimal modification.

**Comment by newbaluku** [comment]
> Re: the buffering strategy, its to avoid the case where you have a function hanging because Mongoose is disconnected. Having to go in and manually kill functions in lambda is very messy.
> 

if that is the case I should remove my catch block and let my lambda function die fast. Right?

app.use((req, res, next) => {
  connectToDatabase().then(() => {
    next();
  })
  _.catch((e) => {
    console.log('Failed to connect to MongoDB:', e);
    res.status(500).send();
  });_
});

**Comment by vkarpov15** [comment]
@newbaluku I'd recommend failing fast if initial connection fails

**Comment by dunika** [comment]
I've been running into this issue as well. I've decided to remove `bufferCommands = false` and `bufferMaxEntries = 0`. From what I understand the worse case is that when it is connecting or the connection is lost any `mongoose` operations will hang until the connection is established?

I'm using `mongoose` with my `graphql` `lambda` instance and from what I can see the worse case will be that the function runs until the `lambda` times out. I've been using `mongoose` on my production server for quite some time and I haven't noticed any issues with operations hanging too long. So I don't really think that are any issues with connecting or reconnecting to the database

This seems to cater for a very small edge case where perhaps my database becomes totally unavailable. Or maybe I am missing something?

**Comment by vkarpov15** [comment]
You're right that the worst case is the function runs until it times out. That's exactly what the recommendation to set bufferMaxEntries and bufferCommands is trying to avoid. But if that case isn't a concern for you then you don't have to set those options

**Comment by duro** [comment]
I too am getting this same error.

@dunika how has running with a buffer been going for you?

**Comment by adir1661** [comment]
same error here on development while using lambda and mongodb atlas

**Comment by dunika** [comment]
@duro I haven't noticed any issues. It feels like the suggestion to set `bufferCommands = false` and `bufferMaxEntries = 0` is a little overly cautious. 

99.9% of the time, at least for me, mongo connections seem very reliable. I'm using `mLab` for my mongo db if that helps. Perhaps results may vary for self hosted instances and other providers.

**Comment by adir1661** [comment]
i had 2 different connections, one mongoose.createConnection, and another mongoose.connect.  i merged it into one methud and it fixed the problem, btw i used chachedDB also i dont know if it is related.. buy now it works fine .. without any buffer changing
