### ISSUE TITLE
collection system.indexes gets name undefined in cosmos db

### ISSUE THREAD

**Issue by ahce** [Automattic/mongoose#6989]
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
Mongoose  >= 5.2.0
![image](https://user-images.githubusercontent.com/12452003/45194795-f98df200-b22a-11e8-87e4-a448439a06fb.png)

**What is the expected behavior?**
Mongoose  >= 5.0.0 <= 5.1.8 
![image](https://user-images.githubusercontent.com/12452003/45194534-de6eb280-b229-11e8-960b-b2286b343635.png)

Node: 8.11.4
Mongoose: 5.2.13

**Comment by lineus** [comment]
@ahce can you provide your **schema** and **connection url/settings with sensitive data removed**?

**Comment by lineus** [comment]
@ahce **What database service are you connecting to, or is it local?** I verified that with Mongodb Atlas, database.system.indexes is not accessible, but with a local server it is. 

**With mongoose `5.2.13` do you see the index listed in the output of `Model.listIndexes()`?**

For example:

### 6989.js
```js
#!/usr/bin/env node
'use strict';

const { ATLASSRV } = require('/Users/lineus/.env');

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);

let opts = {
  useNewUrlParser: true,
  dbName: 'gh6989'
};

const uri = ATLASSRV.replace('?retryWrites=true', '');
mongoose.connect(uri , opts);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  nameIndex: {
    type: String
  }
});

let indexOptions = { name: 'nameUnique', unique: true, background: false };
schema.index({ nameIndex: 1 }, indexOptions);

async function run() {
  assert.strictEqual(mongoose.version, '5.2.13');
  console.log('Using mongoose 5.2.13:');
  await conn.dropDatabase();
  const Test = mongoose.model('test', schema);
  await Test.init();
  const indexes = await Test.listIndexes();
  assert.strictEqual(indexes[1].name, 'nameUnique');
  console.log('nameUnique index was created.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6989.js
Using mongoose 5.2.13:
nameUnique index was created.
issues:
```

**Note:** [the \<database\>.system.indexes collection has been deprecated since mongodb server version 3.0](https://docs.mongodb.com/manual/reference/system-collections/#%3Cdatabase%3E.system.indexes). The docs say to use `listIndexes()` instead.

**Comment by ahce** [comment]
@lineus the service is azure cosmos db.
system.indexes is accesible, but the collection name is undefined.
This only happens in mongoose  >= 5.2.0
![image](https://user-images.githubusercontent.com/12452003/45258319-f0686680-b38b-11e8-9b6b-4752f0855bbc.png) 
The docs have this structure:
{
	"_id" : ObjectId("5b942ce6c3f7f87890c4b524"),
	"ns" : "dbName.collection",
	"key" : {
		"nameIndex" : 1
	},
	"name" : "nameUnique",
	"unique" : true,
	"background" : true
}

**Output:**

Using mongoose 5.2.13:
(node:364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined

const indexes is empty array.

**Comment by lineus** [comment]
@ahce Apologies, I missed Cosmos in the title :smile: 

I created an account on azure and a cosmosdb instance and tested this with the above script. I can verify what you're seeing. 

I also verified that the same behavior is true when only using the native driver:

### 6989_native.js
```js
#!/usr/bin/env node
'use strict'

const env = require('../.env')
const { MongoClient } = require('mongodb')
const dbName = 'gh6989'
const opts = { useNewUrlParser: true }

const uri = env.uri(dbName)
const sharableURI = uri
  .replace(/\/[^:]+:/, '\/\/user:')
  .replace(/r:[^@]*@/, 'r:pass@')
  .replace(/@[^.]*\./, '@host.')
  .replace(/:[0-9]+\//, ':27017/')
  .replace(/t=.*$/, 't=myRS')

async function run() {
  console.log(`connected to: \n ${sharableURI}`)
  const client = await MongoClient.connect(uri, opts)
  const db = client.db(dbName)
  await db.dropDatabase()
  let Test = await db.createCollection('tests')
  let iOpts = { unique: true, background: false }
  await Test.createIndex({ name: 1 }, iOpts).catch(console.error)
  let indexes = await Test.listIndexes().toArray()
  console.log(`There are ${indexes.length}`)
  return client.close()
}

run().catch(e => console.error(e.message))
```
### Output:
```
issues: ./6989_native.js
connected to:
 mongodb://user:pass@host.documents.azure.com:27017/gh6989?ssl=true&replicaSet=myRS
There are 0 indexes
issues:
```

I don't believe there's much mongoose can do to help here, as cosmos isn't really mongodb and only supports a subset of the mongodb spec. I opened [this native driver issue](https://jira.mongodb.org/browse/NODE-1662) but I suspect the answer will be that you need to contact azure support or wait for azure to catch up to the latest mongodb spec.

**Comment by vkarpov15** [comment]
Just FYI, mongoose does **not** officially support cosmosdb. It should work if cosmos is MongoDB compatible as advertised, but we don't actually test against cosmosdb so I wouldn't be surprised if there were some quirks.
