### ISSUE TITLE
validating an array is failing when array value made required:true

### ISSUE THREAD

**Issue by darshanan24** [Automattic/mongoose#6990]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Expected an error, its not throwing any validation error. directly storing the without the array values in to db.
**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/darshanan24/2e8dfc273d7ddfc5c19bc45835ac6a7b
I tried following the blog
http://jasonjl.me/blog/2014/10/23/adding-validation-for-embedded-objects-in-mongoose/
Its not helping me.
**What is the expected behavior?**
It should throw an validation error.
**Please mention your node.js, mongoose and MongoDB version.**
MongoDB shell version v3.6.7
node-v 9.2.0
"mongoose": "^5.0.15"

**Comment by lineus** [comment]
@darshanan24 your custom validator isn't quite in the right place to validate the array.  Please check out the following example, noting that the validator is attached outside the type property of the schema path.

### 6990.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const notEmptyRan = [];
const notEmptyMsg = 'Please add at least one feature in the features array';

var notEmpty = function (columns) {
  if (columns.length === 0) { notEmptyRan.push(false); return false; }
  else { notEmptyRan.push(true); return true; }
};

const schema = new Schema({
  columns: {
    type: [{
      type: mongoose.Schema.ObjectId,
      ref: 'column'
    }],
    required: true,
    validate: [notEmpty, notEmptyMsg]
  }
});

const Test = mongoose.model('test', schema);

const test = new Test;
const test2 = new Test({ columns: [] });
const test3 = new Test({ columns: ['f0'.repeat(12)]});
async function run() {
  let errors = [];
  await conn.dropDatabase();
  await test.save().catch(e => errors.push(e.message));
  await test2.save().catch(e => errors.push(e.message));
  await test3.save();

  let docs = await Test.find({});

  assert.strictEqual(mongoose.version, '5.0.15');
  assert.deepEqual(notEmptyRan, [false, false, true]);
  assert.strictEqual(errors.length, 2);
  assert.strictEqual(docs.length, 1);

  console.log('All Assertions Pass.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6990.js
All Assertions Pass.
issues:
```

**Comment by darshanan24** [comment]
actually my concern is to pass the function inside required: isEnriched(){if(this.type===enriched) return true; else return false;}
suppose if  i m passing type = enriched, then columns should be required:true, if pass other than that for eg, type= raw, required :has to be false.

**Comment by lineus** [comment]
@darshanan24 here is the example with your `isEnriched` function for the columns path required property, I believe it works as expected:

### 6990.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

let enrichedSansRef;
const notEmptyRan = [];
const notEmptyMsg = 'Please add at least one feature in the features array';
var notEmpty = function (columns) {
  if (columns.length === 0) { notEmptyRan.push(false); return false; }
  else { notEmptyRan.push(true); return true; }
};

function isEnriched() {
  if (this.type === 'Enriched') {
    return true;
  }
  return false;
}

const schema = new Schema({
  type: {
    $type: String,
    enum: ['Raw', 'Enriched', 'Joined']
  },
  columns: {
    $type: [{
      $type: mongoose.Schema.ObjectId,
      ref: 'column'
    }],
    default: void 0,
    required: isEnriched,
    validate: [notEmpty, notEmptyMsg]
  }
}, { typeKey: '$type'});

const Test = mongoose.model('test', schema);

// test1 saves to the db, because columns is only required if type === 'Enriched'
const test1 = new Test({ type: 'Raw' }); // and isn't caught by notEmpty because it's undefined

// test2 fails to save because columns is required when type === 'Enriched'
const test2 = new Test({ type: 'Enriched' }); 

// test3 fails because columns is defined and fails the notEmpty validator
const test3 = new Test({ columns: [] });

// test4 saves to the db
const test4 = new Test({ type: 'Enriched', columns: ['f0'.repeat(12)]});

async function run() {
  let errors = [];
  await conn.dropDatabase();
  await test1.save().catch(e => errors.push(e.message));
  await test2.save().catch(e => errors.push(e.message));
  await test3.save().catch(e => errors.push(e.message));
  await test4.save().catch(e => errors.push(e.message));

  let docs = await Test.find({});

  assert.strictEqual(mongoose.version, '5.0.15');
  assert.deepEqual(notEmptyRan, [false, true]);
  assert.strictEqual(errors.length, 2);
  assert.strictEqual(docs.length, 2);

  console.log('All Assertions Pass.');
  return conn.close();
}

run();
```
### Output:
```
issues: ./6990.js
All Assertions Pass.
issues:
```

Is this correct?

**Comment by darshanan24** [comment]
@lineus You are just awesome. You made me realize my problem , and also you just corrected my entire code. Thank you so much.

**Comment by darshanan24** [comment]
Hi @lineus , the above way mentioned by you is working just perfectly, but contradicts the saving of data to database.

**Comment by darshanan24** [comment]
@lineus when i try to post empty array, It should prompt an error saying that, "message": "Path{PATH}is required.", "type": "required", "path": "fields", right? but its not throwing any error.
method 1:
> filters: {type:[filters], required:true}

however, when i post some data in the array, it ll accept the data. So to make it as required , i tried method 2:

> fields : { type:[{ type: mongoose.Schema.ObjectId, ref: fields }], default: void 0, required:true }.

now this code snippet will throw an error when i try to post an empty array. But however, when i post data inside an array it ll say

    {
    "error": {
    "errors": {
    "fields": {
    "message": "Cast to Array failed for value "[ { label: 'Connection Url',\n value: 'connection.url',\n type: 'url',\n required: true },\n { label: 'Username',\n value: 'connection.user',\n type: 'string',\n required: true },\n { label: 'Password',\n value: 'connection.password',\n type: 'password',\n required: true } ]" at path "fields"",
    "name": "CastError",
    "stringValue": ""[ { label: 'Connection Url',\n value: 'connection.url',\n type: 'url',\n required: true },\n { label: 'Username',\n value: 'connection.user',\n type: 'string',\n required: true },\n { label: 'Password',\n value: 'connection.password',\n type: 'password',\n required: true } ]"",
    "kind": "Array",
    "value": [
    {
    "label": "Connection Url",
    "value": "connection.url",
    "type": "url",
    "required": true
    },
    {
    "label": "Username",
    "value": "connection.user",
    "type": "string",
    "required": true
    },
    {
    "label": "Password",
    "value": "connection.password",
    "type": "password",
    "required": true
    }
    ],
    "path": "fields",
    "reason": {
    "message": "Cast to ObjectId failed for value "{ label: 'Connection Url',\n value: 'connection.url',\n type: 'url',\n required: true }" at path "fields"",
    "name": "CastError",
    "stringValue": ""{ label: 'Connection Url',\n value: 'connection.url',\n type: 'url',\n required: true }"",
    "kind": "ObjectId",
    "value": {
    "label": "Connection Url",
    "value": "connection.url",
    "type": "url",
    "required": true
    },
    "path": "fields"
    }
    }
    },
    "_message": "sourceType validation failed",
    "message": "sourceType validation failed: fields: Cast to Array failed for value "[ { label: 'Connection Url',\n value: 'connection.url',\n type: 'url',\n required: true },\n { label: 'Username',\n value: 'connection.user',\n type: 'string',\n required: true },\n { label: 'Password',\n value: 'connection.password',\n type: 'password',\n required: true } ]" at path "fields"",
    "name": "ValidationError"
    }
    }

Summary of my problem is: in method 1, i m not getting an error, but when i post data , i m able to save it in db. In method 2, mongoose throws an error when i don't post anything(which is what i needed) and also it throws an error of casting to an array is failed when i m pushing valid data.

I m unable to find out where i m doing mistake. Please help me.

**Comment by lineus** [comment]
@darshanan24 in your first method, the array is initialized with an empty array because that's the standard default value for mongoose array paths.  

In your second method, it looks like the schema has defined that path ( `fields` ) as type ObjectId but you're passing in an object that can't be cast to one. Please create a minimally complete example that shows the schema/model creation and the data being used to create a new doc.

**The following example shows some various values that will be cast successfully to ObjectIds**. 

### 6990.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const Schema = mongoose.Schema;

const schema = new Schema({
  arr: {
    type: [{ type: Schema.Types.ObjectId, ref: 'other' }]
  }
});

const Other = mongoose.model('other', { name: String });
const Test = mongoose.model('test', schema);

const seeds = [
  { 
    desc: 'string of 24 hex chars', 
    val: 'f0'.repeat(12) 
  },
  { 
    desc: 'an OjbectId', 
    val: new mongoose.Types.ObjectId() 
  },
  {
    desc: 'an object with a _id path containing an ObjectId',
    val: { x: 'yz', _id: new mongoose.Types.ObjectId() }
  },
  {
    desc: 'an object with a _id path containing a string',
    val: { x: 'yz', _id: 'ee'.repeat(12) }
  }
];

const test = new Test({ arr: seeds.map(s => s.val)});

test.save()
  .then(d => JSON.stringify(d, null, 2))
  .then(j => console.log(j))
  .then(() => mongoose.disconnect())
  .catch(e => console.error(e.message));
```
### Output:
```
issues: ./6990_2.js
{
  "arr": [
    "f0f0f0f0f0f0f0f0f0f0f0f0",
    "5b9b7649a5a6f508fb56a224",
    "5b9b7649a5a6f508fb56a225",
    "eeeeeeeeeeeeeeeeeeeeeeee"
  ],
  "_id": "5b9b7649a5a6f508fb56a226",
  "__v": 0
}
issues:
```

**Comment by darshanan24** [comment]
Schema Model:

const mongoose = require('mongoose');

const EventTypes = ['Raw', 'Enriched', 'Joined']
const EventFormats = ["JSON", "DELIMITED", "FIXEDWIDTH", "REGEX"]
const ColumnDataTypes = ["int", "float", "Double", "string"]
const ColumnTypes = ["Description", "ID", "Time"]

const notEmptyRan = [];
const notEmptyMsg = 'Please add at least one feature in the columns array';
var notEmpty = function (columns) {
    console.log("inside notEmpty function")
  if (columns.length === 0) { notEmptyRan.push(false); return false; }
  else { notEmptyRan.push(true); return true; }
};

const Columns = mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    type: {
        type: String,
        enum: ColumnTypes,
        required: true
    },
    startIndex: {
        type: Number,
        required: true
    },
    timeFormat: {
        type: String,
        required: false
    }
});


const filters = mongoose.Schema({
    columns: {
        user_id: {
            type: String,
            required: true
        },
        product_value: {
            type: String,
            required: true
        }
    },
    expressions: {
        type: String,
        required: true
    }
})




const eventSchema = mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    projectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Project',
        required: true
    },
    name: {
        type: String,
        required: true,
        unique: true
    },
    type: {
        type: String,
        enum: EventTypes,
        required: isEnriched
    },
    source: {
        type: mongoose.Schema.Types.String,
        ref: 'DataSource',
        required: isRaw
    },
    parentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Event',
        required: isRaw
    }, //parentEventId
    delimiter: {
        type: String,
        required: isDelimited
    },
   columns:  {
        type:[{
           type: mongoose.Schema.ObjectId,
           ref: Columns
           }],
           default: void 0,
           required: isEnriched,
           validate: [notEmpty, notEmptyMsg]
       },
    filters: [filters]
});


//Validations 

//Check if event is Raw 
function isRaw() {
    if ((this.type) === 'Raw') {
        console.log("inside raw");
        return true;
    }
    console.log("outside raw");

    return false;
}

//Check if event is Enriched
function isEnriched() {
    if ((this.type) === 'Enriched') {
        console.log("inside Enriched");
        return true;
    }
    console.log("outside enriched")
    return false;
}

//Check if Delimiter Required
function isDelimited() {
    if ((this.format) === 'DELIMITED') {
        return true;
    }
    return false;
}

module.exports = mongoose.model('Event', eventSchema);

my router file:

const express = require("express");
const router = express.Router();
const mongoose = require("mongoose");
const checkAuth = require("../../config/check_auth");
const Project = require("../models/project");
const Event = require("../models/event");
//const RawEvent = require("../models/rawEvent")

router.get("/:projectId/events/event", checkAuth, (req, res, next) => {
    const projectId = req.params.projectId;
    Event.find({
            "projectId": projectId
        })
        .exec()
        .then(docs => {
            res.status(200).json({
                count: docs.length,
                events: docs.map(doc => {
                    return {
                        _id: doc._id,
                        name: doc.name,
                        description: doc.description,
                        type: doc.type,
                        source: doc.source,
                        format: doc.format,
                        delimiter: doc.delimiter,
                        parentId: doc.parentId,
                        projectId: doc.projectId,
                        DataSource: doc.DataSource,
                        columns: doc.columns
                    };
                })
            });
        })
        .catch(err => {
            res.status(500).json({
                error: err
            });
        });
});

function livy_call(result) {
    var obj = JSON.parse(result);
    var request = {
        "optionName": "",
        "schema": [],
        "regex": " ",
        "kafkaReadOptions": {
            "subscribe": ""
        },
        "kafkaRejectedOptions": {
            "topic": "",
        },
        "kafkaWriteOptions": {
            "publish": ""
        },
        "format": "",
        "filters": []
    }
    var test = [];
    for (i = 0; i < obj.columns.length; i++) {
        test.push({
            name: obj.columns[i].name,
            startIndex: obj.columns[i].startIndex,
            endIndex: obj.columns[i].endIndex,
            type: obj.columns[i].type
        })
    }
    var filters = [];
    for (i = 0; i < obj.filters.length; i++) {
        filters.push({
            user_id: obj.filters[i].columns.user_id,
            product_value: obj.filters[i].columns.product_value
        })
    }

    request.schema = test;
    request.format = "dd/MMM/yyyy:HH:mm:ss xxxx";
    request.filters = filters;
    request.regex = obj.regex;
    request.optionName = obj.format;
    request.kafkaRejectedOptions.topic = obj.name + "_Rejected";
    request.kafkaWriteOptions.publish = obj.name;
    Event.find({
            _id: obj.parentId
        })
        .exec()
        .then(Event => {
            request.kafkaReadOptions.subscribe = Event.name;
            console.log(request);
        })
        .catch(err => {
            console.log(err);
            res.status(500).json({
                error: err
            });
        });
}

router.post("/:projectId/events/event", checkAuth, (req, res, next) => {
    const event = new Event({
        _id: mongoose.Types.ObjectId(),
        name: req.body.name,
        projectId: req.params.projectId,
        description: req.body.description,
        type: req.body.type,
        source: req.body.source,
        delimiter: req.body.delimiter,
        parentId: req.params.projectId,
        format: req.body.format,
        columns: req.body.columns,
        regex: req.body.regex,
        filters: req.body.filters
    });
    return event.save()
        .then(result => {
            livy_call(JSON.stringify(result));
            res.status(201).json({
                message: "Event stored",
                createdEvent: {
                    _id: result._id,
                    projectId: result.projectId,
                    name: result.name,
                    description: result.description,
                    type: result.type,
                    source: result.source,
                    delimiter: result.delimiter,
                    parentId: result.parentId,
                    columns: result.columns,
                    format: result.format,
                    regex: result.regex,
                    filters: result.filters
                }
            });

            return Project.findOneAndUpdate({
                _id: result.projectId
            }, {
                $push: {
                    events: result._id
                }
            })
        })
        .catch(err => {
            console.log(err);
            res.status(500).json({
                error: err
            });
        });

});

module.exports = router;

The data i m trying to push:

{
	        "name": "anantaNaabaPadmarukminiyaLoverBereInyaruAllaAnantaneAntaTV9SamstapakaradaRaviPrakashRavaruHelali",
            "description": "its good to be back",
            "type": "Enriched",
			"source": "joe",
			"parentId":"5b8e6bc2a5931460f940bfd7",
			"format": "DELIMITED",
			"delimiter": ",",
			"regex": "lpgas",
			"columns": 
				[
				{
				"name": "hi",
				"type":"Description",
				"startIndex": "9",
				"timeFormat": "something"
				},
				{
				"name": "hi",
				"type":"Description",
				"startIndex": "9",
				"timeFormat": "something"
				}
				]
			
}
            
The error i m getting:
"_message": "Event validation failed",
        "message": "Event validation failed: columns: Cast to Array failed for value \"[ { name: 'hi',\n    type: 'Description',\n    startIndex: '9',\n    timeFormat: 'something' },\n  { name: 'hi',\n    type: 'Description',\n    startIndex: '9',\n    timeFormat: 'something' } ]\" at path \"columns\"",
        "name": "ValidationError"

**Comment by lineus** [comment]
@darshanan24 If you want to store an array of ObjectIds in the columns path, you'll need to provide an array of values that either are, or can be cast to, ObjectIds.

### In your `eventSchema` you have defined the columns path as an array of ObjectIds
```
   columns:  {
        type:[{
           type: mongoose.Schema.ObjectId,
           ref: Columns
           }],
           default: void 0,
           required: isEnriched,
           validate: [notEmpty, notEmptyMsg]
       },
```
### The input data shows that columns is an array of objects that **can't** be cast to ObjectIds:
```
			"columns": 
				[
				{
				"name": "hi",
				"type":"Description",
				"startIndex": "9",
				"timeFormat": "something"
				},
				{
				"name": "hi",
				"type":"Description",
				"startIndex": "9",
				"timeFormat": "something"
				}
				]
```

If you're looking to store references to the columns collection in the columns path of event docs, you'll need to create the column docs first and pass the resulting _ids from that creation into the event doc columns path. Here's a simple example with no dependencies other than mongoose that shows one way to do it:

### 6990.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection } = mongoose;
const URI = 'mongodb://localhost:27017/gh-6990';
const OPTS = { useNewUrlParser: true };

const columnSchema = new Schema({
  name: String
});

const eventSchema = new Schema({
  name: String,
  columns: [{
    type: Schema.Types.ObjectId,
    ref: 'column'
  }]
});

const Column = mongoose.model('column', columnSchema);
const Event = mongoose.model('event', eventSchema);

function mockRoute(req) {
  return Column.create(req.body.columns)
    .then(columns => {
      // each element in columns has an _id which can be cast to an ObjectId
      return Event.create({ name: req.body.name, columns });
    });
}

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const input = {
    body: {
      name: 'testEvent',
      columns: [
        { name: 'testColumn1' },
        { name: 'testColumn2' }
      ]
    }
  };
  await mockRoute(input);
  let found = await Event.findOne({}).populate('columns');
  // console.log(JSON.stringify(found, null, 2));
  assert.strictEqual(found.columns.length, 2);
  found.columns.forEach(c => assert.ok(c.name));
  console.log('All Assertions Pass.');
  return connection.close();
}

run();
```
### Output:
```
issues: ./6990.js
All Assertions Pass.
issues:
```

**Comment by Aviv-Hoitash** [comment]
\
`][pohcxdfghiopghjkl` o[p]
[[\]p[ojpihugyjchfxhcghijokp[]\
[`<hj>`](

> _url_

)
