### ISSUE TITLE
Document.prototype.save() returning old version, not saved version of document

### ISSUE THREAD

**Issue by adueck** [Automattic/mongoose#6993]
I must be missing something, but it seems that my `Document.prototype.save()` is not working for me properly in Mongoose 5.2.10.

[The docs say](https://mongoosejs.com/docs/api.html#document_Document-save) that the callback returns the saved document.

> The callback will receive two parameters
> 
> - `err` if an error occurred
> - `product` which is the saved product

For me, it seems to be returning the original version of the document before the update and save. Either I'm doing something wrong, or the docs are a little misleading or vague.

After calling save, the document is updated in the database, but the callback returns the old document, as it was before the modification.

I have been calling save like this (inside an async function):

```
const myDocument = await User.findOne({ name: 'billy' });
const updatedInfo = {
    foo: 'update here',
    bar: 'some other new stuff'
};
myDocument.update({ $set: updatedInfo }, (err) => { console.log(err) });
myDocument.save((err, savedDoc) => {
    if (err) { console.log(err); }
    // Should return saved doc here
    console.log(savedDoc);
});
```
And like this:

```
myDocument.update({ $set: updatedInfo }, (err) => { console.log(err) });
myDocument.save().then((savedDoc) => {
    // Should return saved doc here
    console.log(savedDoc);
}).catch((err) => { console.log(err); });
```

But can't get it to return me the saved document. `savedDoc` ends up being the old version of the document, while the new version does get saved in the database.

**Comment by Fonger** [comment]
You shouldn't call `update` directly.
It's a different way to update the document.

Try this:

```js
const myDocument = await User.findOne({ name: 'billy' });
myDocument.foo = 'update here';
myDocument.bar = 'some other new stuff';
myDocument.save().then((savedDoc) => {
    // Should return saved doc here
    console.log(savedDoc);
}).catch((err) => { console.log(err); });
```

**Comment by adueck** [comment]
My problem is that in my logic I need to update a bunch of values on a document. In my REST api I receive an object full of the updated values, without knowing which ones or how many they well be. It would be really nice if I could just plug that object of updated values into the document.

So the only way to do this is to loop through the array and assign each of the values using computed keys? It would be nice if there was a nicer way to update a bunch of values at once on a doc.

I think I can do this with findOneAndUpdate, and get the saved doc, but is there really no way to do it with an already found document?

**Comment by Fonger** [comment]
You can call update surely but you must ensure it’s completed by providing a callback or await it.

The original code you provide doesn’t work because you don’t await it or provide a completion callback

**Comment by adueck** [comment]
Ohh, I see, so since the update is a async operation. My changes called using `update` do get saved in the db, but they're not quite there yet to be called back when a call `save`.  👍

**Comment by lineus** [comment]
@adueck assuming your route's request object has a property that corresponds to a unique path in your schema, like _id or name (if it has a unique index), you can use `Model.findOneAndUpdate()` with the new option set to true to update that doc and return the newly saved doc in one query.

Here's a generic example:

```js
app.post('/myUpdateRoute', (req, res) => {
  let cond = { _id: req.body.id }
  let update = req.body
  let opts = { new: true }
  MyModel.findOneAndUpdate(cond, update, opts, (err, doc) => {
    if (err) { return res.status(500).json({ error: err }) }
    return res.status(200).json({ doc })
  })
})
```

**Comment by adueck** [comment]
@lineus Yes, I thought of doing that but for cleanliness and simplicity I was wondering if there was a different way to do it. This is because in my case I

- get new info for a doc
- query the doc and find it
- go through a whole bunch of long logic to deal with compare the new info and the queried doc
- send back `res.send()` if there's something wrong with the update
- if everything's ok and update-able, I put the updated info in the document
- save the document
- return the newly saved document

I was wondering if there's a nice way to do this without having to call another query with `findOneAndUpdate` at the end of the process. 

It seems that the only way I can get a returned, newly saved document is to use:
- `findOneAndUpdate`
- updating individual keys/values with `myDocument.foo = 'info'` and then using `myDocument.save()`

It would be a nice feature if there was a way to update a document with a full object of info, and then get a callback with the updated document. `myDocument.update()` doesn't provide the updated document in the callback. 🤔

**Comment by vkarpov15** [comment]
@adueck try `myDocument.set()`: https://mongoosejs.com/docs/api.html#document_Document-set

```javascript
const doc = await MyModel.findOne({ _id });
doc.set(req.body);
await doc.save();
return { doc };
```

**Comment by adueck** [comment]
@vkarpov15 Perfect! Thank you! 👍 Yes, this is exactly the functionality that I was looking for. Sorry I didn't see that in the docs.
