### ISSUE TITLE
"update" and "findByIdAndUpdate" don't increment "__v"

### ISSUE THREAD

**Issue by FelixFurtmayr** [Automattic/mongoose#6994]
I guess by design, someone thought the update functions do not need to increment __v. 
For me it seems like a bug, as I expected it always to be updated.

There has already been an issue about it, but was not resolved: https://github.com/Automattic/mongoose/issues/1265
The Issue is in all mongoose Versions (tested with mongoose 5, 4, 3).

## Problem
Someone with an older version of the doc could overwrite a newer version.
Example: Two people editing a document in the frontend - and they both want to save it. We might get version conflicts, but as __v is not updated, we cannot check it.

## Conclusion
* It is good to always increment __v, also on the "update" functions.
* Why
  * allow prevent conflicts using __v
  * it seems intuitive to me, as other functions increment __v.
  * the basic idea if __v is to be incremented

## Code Snippet for Testing and Workaround

I made a script for testing - copy it in a file 'mongoose__v.js' and execute it with:

> node mongoose__v.js

The script will create a document 'catty' in the collection 'kitten' on the first run. Execute it several times to try to update the version. The console.logs will show, that __v is not updated.

```js
const mongoose = require('mongoose');

// prepare  database
const db = mongoose.connection;
const kittySchema = mongoose.Schema({
   name: String,
   dummy: Array
});
const kitten = mongoose.model('kitten', kittySchema);
mongoose.connect('mongodb://localhost/test', {useNewUrlParser: true});


db.once('open', function () {



   // imagine we just fetched a document from the database
   // and we want to write it back using 'findOneAndUpdate'.
   // our object might look like this
   let catty = {
      _id: '5b9397d6ef2995794af001a3',
      dummy: [ 1, 2, 3 ],
      name: 'catty',
      __v: 0 // as expected, there is a mongoose version here
   };


   // by default, the function "findOneAndUpdate" below will not update __v
   // we can force it manual with the "$inc" operator in the following two lines:
   // delete catty.__v; // ensure, there is no __v in the update object, otherwise it would be editied twice => error
  // catty.$inc = { __v: 1};


   kitten.findOneAndUpdate({
      'name': 'catty' // will not be found on first run, so it will be created
   }, catty, {
      upsert: true,
      new: true
   }, function (err, cattyFromDb) {
      if (err) return console.error(err);
      console.log('updated kitty "catty":', cattyFromDb.__v);
      process.exit(0);
   });
});

```

### workaround
Uncomment those lines and execute the script again several times - now __v should be updated.
```js
   delete catty.__v; // ensure, there is no __v in the update object, otherwise it would be editied twice => error
   catty.$inc = { __v: 1};
```

Also this works, it would be really great, if it would be the mongoose default.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP

**Comment by vkarpov15** [comment]
I took a closer look at this and this is going to have to wait for a minor release. Right now update operations never update the version key, we'll have to add a `versionKey` option to queries to opt into incrementing versions. Currently Mongoose only increments the version key through `save()`, I'll add a note to the [docs](https://mongoosejs.com/docs/guide.html#versionKey) for now.

**Comment by FelixFurtmayr** [comment]
Hi vkarpov15, thank you for preparing this feature :-)
An option to enable it would be great.
I guess it should be enabled by default, but for legacy reasons, disabling it will be the best thing in the near future.

**Comment by vkarpov15** [comment]
I dug into this for 5.4 and I think its best to implement this as a plugin for now. Check out [mongoose-update-versioning on npm](http://npmjs.com/package/mongoose-update-versioning) and our [docs](http://plugins.mongoosejs.io/plugins/update-versioning)

**Comment by DigivolveIo** [comment]
is this being looked at still?

**Comment by vkarpov15** [comment]
@DigivolveIo please check the [mongoose-update-versioning plugin docs](http://plugins.mongoosejs.io/plugins/update-versioning)
