### ISSUE TITLE
I want to auto convert ObjectId to string

### ISSUE THREAD

**Issue by lagmanzaza** [Automattic/mongoose#6996]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I use with Apollo server 2.0. when I want _id, but in response data, ObjectId is not converted to String.
**What is the expected behavior?**
How to auto convert ObjectId to String?
**Please mention your node.js, mongoose and MongoDB version.**
"mongoose": "^5.2.13",
node: 8
MongoDB: 3.6

**Comment by Lanfei** [comment]
GraphQL have used [a new method](https://github.com/graphql/graphql-js/commit/3521e1429eec7eabeee4da65c93306b51308727b#diff-87c5e74dd1f7d923143e0eee611f598eR183) to serialize ID, the new method doesn't support ID in object type anymore, but following codes will help on this:

```js
const mongoose = require('mongoose');

const ObjectId = mongoose.Types.ObjectId;

ObjectId.prototype.valueOf = function () {
	return this.toString();
};
```

Hope mongoose will support this feature soon :)

**Comment by vkarpov15** [comment]
Interesting idea @Lanfei , will investigate that for a future release.

**Comment by Lanfei** [comment]
@vkarpov15 Nice, thanks :)

**Comment by cannap** [comment]
Hi any news about this?

**Comment by vkarpov15** [comment]
@cannap #6912 should help with this, you'll be able to do:

```javascript
mongoose.Schema.ObjectId.get(v => v != null ? v.toString() : v);
```

Does that API make sense?

**Comment by johnlife** [comment]
@vkarpov15, definitely, great idea, waiting for 5.4 patiently.
Thanks for great middleware.

**Comment by vkarpov15** [comment]
5.4.0 is out, [here's the workaround](http://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters)
