### ISSUE TITLE
Mongoose 5.2.12 (MongoDB 3.6.0-47) Not returning (hangs) Polygon Coordinates.

### ISSUE THREAD

**Issue by brucesemple** [Automattic/mongoose#6999]
Schema:

```javascript
const neighborhoodSchema = new Schema({
    geometry: {
	   coordinates: {
            type: [[[Number]]], // Array of arrays of arrays of numbers
            required: true
        },
		type: {
           type: String,
           enum: ['Polygon'],
           required: true
        }
     },
   name: String,	 
  }, {collection: 'neighborhoods'});
```

This works:

```javascript
myNeighborhood = await Neighborhoods.findOne({ geometry: { $geoIntersects: { $geometry: myQTH}}}).select({name: true});
```

This Hangs --  it appears the callback is not getting called.

```javascript
myNeighborhood = await Neighborhoods.findOne({ geometry: { $geoIntersects: { $geometry: myQTH}}});
```

this hangs also ==>

```javascript
 rList = await Restaurants.find({ location: { $geoWithin: { $geometry: myNeighborhood.geometry } }}).select({name: true, geometry: true});
```

It looks like I can't return the array of spatial coordinates for the polygon back through mongoose.

This query works when typed into the mongo cli

```javascript
db.neighborhoods.findOne( { geometry: { $geoIntersects: { $geometry: { type: "Point", coordinates: [ -73.93414657, 40.82302903 ] } } } } )
```

This is an example from here ==> https://docs.mongodb.com/manual/tutorial/geospatial-tutorial/

**Comment by brucesemple** [comment]
Circling back to this issue finally .. 
I did turn off mongoose buffering just to see if that would have any effect on the problem, it did not.

I started with this post ==> https://docs.mongodb.com/manual/tutorial/geospatial-tutorial/

If I add a select to my query and only return the name of the neighborhood .. the query works ... 
The query appears to fail if I return the geometry as well. 

If I use the mongo client  and just enter the query this way ... 
var neighborhood = db.neighborhoods.findOne( { geometry: { $geoIntersects: { $geometry: { type: "Point", coordinates: [ -73.93414657, 40.82302903 ] } } } } )
db.restaurants.find( { location: { $geoWithin: { $geometry: neighborhood.geometry } } } ).count()

it works .. 

I believe there is some issue with mongoose being able to handle a geometry with a large number of points.

**Comment by brucesemple** [comment]
Use the  neighborhood dataset from that geospatial-tutorial post .. The neighborhoods have a very large number of sides of the polygon.  That first neighborhood - Bedford - has at least 150 pairs of coordinates.  Does mongoose just have a hardcoded array limit?

**Comment by vkarpov15** [comment]
@brucesemple we do not have any hardcoded limit on array size. It might be that you're running into the 16MB document size limit but unlikely. Can you give me an example doc so I might try it out?

**Comment by renanboni** [comment]
@vajrasar Of course the example that you did works for you, because it's wrong.

You can specify any latitude and longitude and your example always will return a output even that is invalid.

Try:
