### ISSUE TITLE
Virtual field set callback not setting required field in express route.  

### ISSUE THREAD

**Issue by Euklidian-Space** [Automattic/mongoose#7000]
**Do you want to request a *feature* or report a *bug*?**
Possibly a bug?  If not feel free to close this out. 

**What is the current behavior?**

I am having an issue test driving an endpoint for an API I am building. The endpoint is for a person to register as a new user /user/register. When I hit the route with the following request body { "name": "john", "email": "john@example.com" "password": "Password1234!" }

I get a 404 because a validation error from the user schema gets raised. The error states that the passwordHash path is required. The way I have my schema set up is that I have a virtual password field and I hash that field and save it to a passwordHash field which is required.  For some reason the passwordHash field fails to get set.  This is only happening when I create a new User from a route.

The relevant files are pasted below. If you want to look at the app and run it here is the repo https://github.com/Euklidian-Space/voter-node/tree/user_routes .  I traced the 

Here is the route definition

```javascript
const router = require("express").Router();
const UserController = require("../controllers/user_controller");

router.get("/:id", UserController.verifyToken, UserController.show);
router.post("/register", UserController.create);

module.exports = router;
```
Here is the create action in the User Controller
```javascript
exports.create = async (req, res, next) => {
  const [err, user] = await to(createUser(req.body)); 
  if (err) return next(err);

  const respObj = {
    user,
    token: token(user.id, JWT_KEY, jwt)
  };

  res.status(200).send(respObj);
  return Promise.resolve(respObj);
};
```

Here is the User Schema

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const bcrypt = require('bcryptjs');
const { validatePassword } = require("./validations");

const userSchema = new Schema({
  name: {type: String, required: true},
  email: {type: String, required: true},
  passwordHash: {type: String, required: true},
  polls: [{type: Schema.Types.ObjectId, ref: "Poll"}]
});

userSchema.virtual("password")
  .get(function() { return this._password; })
  .set(function(val) {
    this._password = val;
    validatePassword(val)
      .then(pw => {
        const salt = bcrypt.genSaltSync(10);
        const hash = bcrypt.hashSync(pw, salt);
        this.passwordHash = hash;
      }).catch(err => this.invalidate("passwordHash", err));
  });

module.exports = userSchema;
```

**If the current behavior is a bug, please provide the steps to reproduce.**
If you can, clone the repo of my project and run npm run test-watch.  The failing test highlights this issue.  If you can't clone here is the test.

```javascript
const request = require("supertest");
const app = require("../../app");
const { populateUsers } = require("../helpers");
let users;

beforeAll(async done => {
  users = await populateUsers(10);
  done();
});
describe("POST /users/register", () => {
    let request_body;
    beforeEach(() => {
      request_body = {
        email: "john@example.com",
        name: "johnny5",
        password: "Secret1234!"
      };
    });
    it("should send new user id and jwt", () => {
      return request(app)
        .post("/user/register")
        .send(request_body)
        .expect(200)
        .then(({ body }) => {
          console.log(body)
          expect(body.id).toBeDefined();
          expect(body.token).toBeDefined();
        });
    });
  });
```

**What is the expected behavior?**

No validation errors when providing the user model with correct data.  

**Please mention your node.js, mongoose and MongoDB version.**
Node Version 8.11.4
MongoDB version 3.4.17
Mongoose 5.2.14

**Comment by vkarpov15** [comment]
Your `password` virtual is async and you're not waiting for that promise to resolve. Instead of using a virtual, I'd recommend just have an async `setPassword()` method similar to how its done in [this comment](https://github.com/Automattic/mongoose/issues/5762#issuecomment-339965468). The method approach isn't as neat syntactically but that's the only way to do it until we add support for async virtuals. Follow #5762 for updates on async virtuals.
