### ISSUE TITLE
MongoError: Updating the path '__v' would create a conflict at '__v'

### ISSUE THREAD

**Issue by Polarisation** [Automattic/mongoose#7003]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using findByIdAndUpdate() or findOneAndUpdate() with the `upsert` option, a `__v` key, and `$unset`, the following error is thrown:
```
MongoError: Updating the path '__v' would create a conflict at '__v'
    at ~/mongoose-test/node_modules/mongodb-core/lib/connection/pool.js:581:63
```
This bug appears similar to #5973 which is supposed to have been fixed. As far as I can tell, the difference here is that in this case the `$unset` key is being used.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-7003`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  const schema = new mongoose.Schema({ name: String, description: String });
  const Model = mongoose.model('Model', schema);
  const doc = await Model.create({ name: 'test', description: 'we want to unset this description later' });
  await Model.findByIdAndUpdate(doc._id, {
    '$unset': { description: '' },
    __v: 0,
    name: 'update'
  }, { upsert: true });
  console.log('updated __v');
}
```
When running this script, an error is thrown before the console.log.

**What is the expected behavior?**

The record should update without at error. Remove either `__v`, `$unset`, or the `upsert` option from the example and it works as expected.

**Please mention your node.js, mongoose and MongoDB version.**

Node.js: v10.9.0
Mongoose: v5.2.14
MongoDB: v3.6.3 (with setFeatureCompatibilityVersion: 3.6)

**Comment by lineus** [comment]
@Polarisation if you change your `findByIdAndUpdate` call to:
```js
  await Model.findByIdAndUpdate(doc._id, {
    '$unset': { description: '' },
    '$set': {
      __v: 0,
      name: 'blargh'
    }
  }, { upsert: true });
```
It will work as expected. 

@vkarpov15 I marked this as a confirmed bug, but now I'm not so sure. If an update doc is passed in with one dollarKey, should all top level keys be dollarKeys? Marking as `bug?` for now.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP
