### ISSUE TITLE
aggregate $lookup from Discriminator

### ISSUE THREAD

**Issue by TeslaAdis** [Automattic/mongoose#7004]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am using CosmosDB with MongoDB/Mongoose.

I have created one collection as the base with many different collections using this Base as a discriminator. (They have _type as explaining what Collection it is - not sure if explaining correctly)

```
const baseOptions = {
    discriminatorKey: '_type',
    collection: 'AllData',
    timestamps: true
}
const Base = mongoose.model('Base', new mongoose.Schema({}, baseOptions));
```

Creating models:
`Base.discriminator('User', UserSchema);`

Everything works fine until I wanted to run $lookup where the foreign field is named the same in multiple collections. 
UserConnection, GroupUser, EventUser all have field user which represents user._id.
  
Running next lookup will result in returning all matches from all collections above.
```
{
      $lookup: {
            from: 'AllData',
            localField: 'data.connection.connectionStatus',
            foreignField: 'user',
            as: 'data.connection.connectionStatus'
      }
 }
```

**What is the expected behavior?**
Is there a way to reference discriminator instead of 'AllData'

Sorry if badly formatted and asked, please ask what to provide if needed.
Thank you for your time.

**Comment by lineus** [comment]
@TeslaAdis, if CosmosDB supports the $lookup `pipeline` operator you can do something like the following:

### 7004.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const baseSchema = new Schema({
  common: String,
  name: String
}, { discriminatorKey: 'kind' });

const Base = mongoose.model('base', baseSchema, 'base');

const disc1Schema = new Schema({
  x: String
});

const Disc1 = Base.discriminator('disc1', disc1Schema);

const disc2Schema = new Schema({
  y: String
});

const Disc2 = Base.discriminator('disc2', disc2Schema);

let docs = [];

for (let i = 0; i < 10; i++) {
  let suffix = (i % 2 === 0) ? 'XXX':'YYY';
  docs.push(new Base({ name: `base${suffix}` }));
  docs.push(new Disc1({ name: `discOne${suffix}`, x: `something${i}` }));
  docs.push(new Disc2({ name: `discTwo${suffix}`, y: `otherthing${i}` }));
}

docs.forEach(d => d.common = 'xyz123');

const otherSchema = new Schema({
  name: String,
  k: String,
  n: String
});

const Other = mongoose.model('other', otherSchema);
const other = new Other({ name: 'OTHER', k: 'disc1', n: 'discOneXXX' });

async function run() {
  assert.strictEqual(mongoose.version, '5.2.14');
  await conn.dropDatabase();
  await other.save();
  await Base.create(docs);

  let res = await Other.aggregate([
    {
      $lookup: {
        from: 'base',
        let: { key: '$k', name: '$n' },
        pipeline: [
          { 
            $match: {
              $expr: {
                $and: [
                  { $eq: ['$kind', '$$key'] },
                  { $eq: ['$name', '$$name'] }
                ]
              }
            }
          }
        ],
        as: 'referenced'
      }
    }
  ]);

  assert.strictEqual(res[0].referenced.length, 5);
  res[0].referenced.forEach(d => assert.strictEqual(d.name, 'discOneXXX'));

  console.log('All Assertions Pass.');
  return conn.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./7004.js
All Assertions Pass.
issues:
```

I hope I understood you correctly, it's easier when there is a complete/self-contained example with assertions that show exactly what your expectations are. It's difficult for **anyone** to translate prose to code :smile:

**DISCLAIMER: CosmosDB only supports a subset of mongodb features and is not officially supported by mongoose or mongodb** 

If you are locked into Azure, and CosmosDB doesn't support all of the mongodb features that you require, you might consider deploying an atlas cluster to Azure instead of using CosmosDB.

**Comment by TeslaAdis** [comment]
I know about $lookup with the pipeline. But unfortunately they run MongoDB 3.4.2 on their side, and the pipeline has been introduced in 3.6. I have moved to MongoDB Hosting for the development phase. We will probably be ready to pay full price for individual collections once we get to production. And maybe they even update their MongoDB to use latest versions.

Thank you for your time
