### ISSUE TITLE
[latest version 5.2.14] Issue running on AWS lambda Cannot find module './drivers/node-mongodb-native'

### ISSUE THREAD

**Issue by fyn-dev** [Automattic/mongoose#7010]
Request crash when when I try to execute connection to mongodb in AWS Lambda function

`"errorType":"Error","stackTrace":["Error: Cannot find module './drivers/node-mongodb-native'","at webpackEmptyContext (/src/handlers/webpack:/node_modules/mongoose/lib sync:2:1)","at Object../node_modules/mongoose/lib/index.js (/src/handlers/webpack:/node_modules/mongoose/lib/index.js:9:25)","at __webpack_require__ (/src/handlers/webpack:/webpack/bootstrap:19:1)","at Object../node_modules/mongoose/index.js (/src/handlers/webpack:/node_modules/mongoose/index.js:9:18)","at __webpack_require__ (/src/handlers/webpack:/webpack/bootstrap:19:1)","at Module../src/handlers/AuthHandler.ts (/src/handlers/AuthHandler.js:149782:66)","at __webpack_require__ (/src/handlers/webpack:/webpack/bootstrap:19:1)","at Object.0 (/src/handlers/AuthHandler.js:149977:18)","at __webpack_require__ (/src/handlers/webpack:/webpack/bootstrap:19:1)","at ./node_modules/aes-js/index.js.convertUtf8.toBytes (/src/handlers/webpack:/webpack/bootstrap:83:1)","at Object.<anonymous> (/src/handlers/AuthHandler.js:87:10)","at Module._compile (module.js:653:30)","at Object.Module._extensions..js (module.js:664:10)","at Module.load (module.js:566:32)","at tryModuleLoad (module.js:506:12)","at Function.Module._load (module.js:498:3)","at Module.require (module.js:597:17)","at require (internal/module.js:11:18)","at Object.createHandler (/node_modules/serverless-offline/src/functionHelper.js:104:21)","at handler (/node_modules/serverless-offline/src/index.js:548:40)","at Object.internals.handler (/node_modules/hapi/lib/handler.js:96:36)","at request._protect.run (/node_modules/hapi/lib/handler.js:30:23)","at module.exports.internals.Protect.internals.Protect.run (/node_modules/hapi/lib/protect.js:64:5)","at exports.execute (/node_modules/hapi/lib/handler.js:24:22)","at each (/node_modules/hapi/lib/request.js:384:16)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at module.exports.internals.Auth.internals.Auth._authenticate (/node_modules/hapi/lib/auth.js:210:16)","at internals.Auth.authenticate (/node_modules/hapi/lib/auth.js:202:17)","at each (/node_modules/hapi/lib/request.js:384:16)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at request.connection.states.parse (/node_modules/hapi/lib/route.js:379:20)","at Items.serial (/node_modules/statehood/lib/index.js:244:16)","at done (/node_modules/items/lib/index.js:31:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at done (/node_modules/items/lib/index.js:28:25)","at Items.serial (/node_modules/statehood/lib/index.js:184:20)","at iterate (/node_modules/items/lib/index.js:36:13)","at Object.exports.serial (/node_modules/items/lib/index.js:39:9)","at exports.Definitions.internals.Definitions.internals.Definitions.parse (/node_modules/statehood/lib/index.js:158:11)","at internals.state (/node_modules/hapi/lib/route.js:360:31)","at each (/node_modules/hapi/lib/request.js:384:16)","at iterate (/node_modules/items/lib/index.js:36:13)","at Object.exports.serial (/node_modules/items/lib/index.js:39:9)","at internals.Request._lifecycle (/node_modules/hapi/lib/request.js:387:11)","at internals.Request._execute (/node_modules/hapi/lib/request.js:302:21)","at Domain.request._protect.enter (/node_modules/hapi/lib/connection.js:261:25)","at Domain.run (domain.js:242:14)","at module.exports.internals.Protect.internals.Protect.enter (/node_modules/hapi/lib/protect.js:80:17)","at Server.<anonymous> (/node_modules/hapi/lib/connection.js:259:30)","at emitTwo (events.js:126:13)","at Server.emit (events.js:214:7)","at parserOnIncoming (_http_server.js:634:12)"]`

Code to reproduce issue:
```
// Lambda function in TypeScript
export const testMongoDb: Handler = async (event: APIGatewayEvent, context: Context) => {
 await mongoose.connect('YOUR_CONNECTING_MONGODB_URI', {
    dbName: 'DB_NAME',
    user: 'DB_USER',
    pass: 'DB_PASSWORD'
  });

return { statusCode: 200, headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Headers': '*'
          }, body: '' }
}
```

When I use older version 5.1.8 for example I don't have this issue at all. Everything works smooth.

Node.Js v8.12.0
mongoDB v3.6
mongoose v.5.2.14
TypeScript v2.8.3

**Comment by jaydp17** [comment]
Same here, it's because of the dynamic require in https://github.com/Automattic/mongoose/blob/master/lib/index.js#L9

**Comment by fyn-dev** [comment]
@jaydp17 
I still not clear what exactly steps require to resolve issue from my side?
I should change global.MONGOOSE_DRIVER_PATH to some other value? How? And what value?

**Comment by jaydp17** [comment]
@fyn-dev we'll have to change a line of code in mongoose to make it work.
I've created a PR (#7014) to do that, meanwhile, you can use
```
// package.json
"mongoose": "git+https://git@github.com/PleaseDotCom/mongoose.git#9ec6e88",
```

It's a fork with the above fix.

**Comment by vkarpov15** [comment]
You should not need to set MONGOOSE_DRIVER_PATH to anything special. 5.2.15 should fix this issue

**Comment by michaelbats** [comment]
getting this issue with latest...

**Comment by vkarpov15** [comment]
@michaelbats :-1: please open up a separate issue and follow the issue template. "getting this issue with latest" is exceedingly unhelpful.
