### ISSUE TITLE
Improve documentation on dynamic ref

### ISSUE THREAD

**Issue by horoscop** [Automattic/mongoose#7013]
Hi!

Could you please improve the documentation on this topic? I don't really understand how to apply it.
https://mongoosejs.com/docs/populate.html#dynamic-ref

Thank you!

**Comment by vkarpov15** [comment]
Here's a few ideas:

1) more practical example
2) demonstrate how you would do the example with ref as opposed to refPath
3) better name: just call it refPath rather than dynamic ref

Would

**Comment by horoscop** [comment]
@vkarpov15 Hello! Thank you for your answer!
So, I want to create a commenting system. Users will be able to comment to a specific blog post or a specific product.
```js
element: { //element means blog post or product
        type: mongoose.Schema.ObjectId,
        ref: 'Post',  // I will need also 'Product'
        required: 'You must supply an element'
    },
```

Do you know how this can be achieved? (I want to keep the required attribute)

Thank you!

**Comment by vkarpov15** [comment]
Instead if ref: 'Post', use refPath: 'elementModel'. You then have an elementModel path in your schema that contains either 'Post' or 'Product'. Does that make sense?
