### ISSUE TITLE
MongoError: the limit must be positive

### ISSUE THREAD

**Issue by vatex** [Automattic/mongoose#7015]
unhandledRejection:  { MongoError: the limit must be positive
    at Function.MongoError.create (/var/app/current/node_modules/mongodb-core/lib/error.js:31:11)
    at /var/app/current/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/var/app/current/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/var/app/current/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/var/app/current/node_modules/mongodb-core/lib/connection/connection.js:317:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
  name: 'MongoError',
  message: 'the limit must be positive',
  ok: 0,
  errmsg: 'the limit must be positive',
  code: 15958,
  codeName: 'Location15958' }

Mongoose: 4.7.5
MongoDB: 3.4
Node.js: 6.9.1

I've used mongoose operation more than 100 places and I don't know exactly which failed, but anyone could let me know where this message comes from?

**Comment by lineus** [comment]
@vatex it looks like you're passing a negative value to a $limit stage of an aggregation pipeline. It can be replicated with:

### 7015.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);
const test = new Test({ name: 'one' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  const pipeline = [{ $match: { name: 'one' } }, { $limit: -1 }];
  await Test.aggregate(pipeline);
}

run().catch(e => {
  console.error(e.stack);
  return conn.close();
});

```
### Output:
```
issues: ./7015.js
MongoError: the limit must be positive
    at queryCallback (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
issues:
```

Is there anywhere in your code that you're passing a variable into an aggregate $limit stage? If so, you'll need to add a test for each one that ensures that the value is positive.

**Comment by dbellavista** [comment]
Also `0` is not positive, so it may be `$limit: 0`

**Comment by vatex** [comment]
Thanks, somewhere limit was negative and that's why the error was occurring.

**Comment by vkarpov15** [comment]
@kmorte what version of Mongoose? Below script executes without error on Mongoose 6.0.9:

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Test = mongoose.model('Test', Schema({ name: String }));

  await Test.find().limit(0);
  console.log('Done');
}
```
