### ISSUE TITLE
MongoError: Projection cannot have a mix of inclusion and exclusion.

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#7017]
I want to report a bug, unfortunately I was not totally able to reproduce the original case I have, but stumbled on something simliar that could be related. 

**What is the current behavior?**
If you have a model that has some fields unselected by default, and explicity selecting another one that is not part of the definition (this is the test case, in my original case the defintion is part of it, but I guess it is related to the other bug where mongoose can not correctly read the type definition #7016 ) the query fails with projection cannot have a mix of inclusion and exlusion.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

console.log(mongoose.version);

run().catch(error => console.error(error.stack));

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test3');

    const ModelA = mongoose.model('ModelA', new mongoose.Schema({
        a: {
            select: false,
            type: {
                _reference: {
                    type: mongoose.Schema.Types.ObjectId,
                    ref: 'ModelB'
                },
            }
        },
        b: { select: false, type: String }
    }));

    const result = await ModelA.find({}, '+c');

    console.log('result', JSON.stringify(result, false, 3));
}

```

**What is the expected behavior?**
The expected behavior is that this query still runs, without a mix up in the projection. I would assume as soon as I specify a "+" select, mongoose does not add any "-" select to the query.

**Please mention your node.js, mongoose and MongoDB version.**
mongoose 5.2.15, v8.11.4, mongodb 3.6

**Comment by vkarpov15** [comment]
Does it work if you don't pretend + to the path? + is special and select('+c') is slightly different from select('c')

**Comment by Wim-mie** [comment]
I got the same error. it happened when i tried to exclude a filed that popped up in my results due to a `ClientSchema.set( 'toJSON', { getters: true } );`.
It still happened when I removed the toJSON option for the getters, and forgot to remove the exclusion. Once I removed that exclusion (but kept the -_id exclusion) it worked fine.
(tried several ways: `select('+field1 -_id -getter-to-exclude')`, `select({field:1, _id:0, getter-to-exclude:0})`, `find({_id: req.params.clientId}, {field:1, _id:0, getter-to-exclude:0})`, all resulting in same error).
version: mongoose 5.2.15, nodeJS 10.15.1, MongoDB 4.0.2

**Comment by vkarpov15** [comment]
@Wim-mie the below script works as expected, no errors. Please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7017`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    field1: { type: String, select: false },
    foo: String
  });

  const Model = mongoose.model('Test', schema);

  await Model.create({ field1: 'test', foo: 'test' });

  const doc = await Model.findOne().select('+field1 -_id -foo');
  console.log(doc);
}
```

**Comment by neeltiwari** [comment]
If you have used Mongo Projection or Project so might be you have added that key name those are not in the document.
Remove projection key and check it

**Comment by Facebook-c-sdkinverted5** [comment]
@vkarpov15 https://phps.space/questions/how-can-i-remove-specific-fields-from-mongodb-using-mongo-php
