### ISSUE TITLE
Feature/bug: Send mongoose debug info to stdout instead of stderr

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#7018]
Right now, we have this:

```js
const mongoose = require('mongoose');
mongoose.set('debug', config.get('debug'));
```

the above means that logging goes to stderr:

```console
chat-service: Mongoose: appointments.ensureIndex({ user: 1, deleted: 1, patient: 1 }, { background: true })
chat-service: Mongoose: reminders.ensureIndex({ 'externalId.source': 1, 'externalId.value': 1, deleted: 1 }, { background: true })
chat-service: Mongoose: waitlists.ensureIndex({ deleted: 1, user: 1, patient: 1, provider: 1 }, { background: true })
```

my request is - is there a way to send it to stdout instead of stderr?

**Comment by lineus** [comment]
@ORESoftware what does config.get('debug') return? I'm assuming it's a custom function?

**In the case of passing true into mongoose set debug** the default is to `console.info()` the debug information which goes to stdout.

**If you pass a custom function into mongoose set debug** It will print the logs wherever you tell it to. 

Here's an example:

### 7018.js
```js
#!/usr/bin/env node
'use strict';
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', customLogger); // change this to true, output still goes to stdout.

function customLogger(coll, op, doc, proj) {
  process.stdout.write(`${coll}.${op}(${JSON.stringify(doc)}`);
  if (proj) {
    process.stdout.write(',' + JSON.stringify(proj) + ')\n');
  } else {
    process.stdout.write(')\n');
  }
}

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);
const test = new Test({ name: 'test' });

async function run() {
  await conn.dropDatabase();
  await test.save();
  let found = await Test.findOne();
  assert.ok(found);
  return conn.close();
}

run();
```
### Output with customLogger:
```
issues: ./7018.js 2>/dev/null
tests.insertOne({"_id":"5ba34aab4cd8b804b659b9fd","name":"test","__v":0})
tests.findOne({},{"projection":{}})
issues:
```

### Output with true
```
issues: ./7018.js 2>/dev/null
Mongoose: tests.insertOne({ _id: ObjectId("5ba34c367f40fd04dacb39ee"), name: 'test', __v: 0 })
Mongoose: tests.findOne({}, { projection: {} })
issues:
```

**Comment by ORESoftware** [comment]
I don't really want to write a custom logger because I am at work and going through the hassle of getting a PR approved is undesirable..I just want an option to send all of that info to stdout instead of stderr, something like this:

```js
mongoose.set('debug', config.get('debug'), process.stdout);
```

in fact, it should accept a stream to write to, as I just demonstrated...so you could do this instead:


```js
mongoose.set('debug', config.get('debug'), fs.createWriteStream(file));
```

**Comment by lineus** [comment]
@ORESoftware If config.get('debug') is returning true, then mongoose should already be using stdout. **The default debug function uses console.info to print the debug messages** ( *this is shown above in my example output using true* ) as I've redirected stderr to /dev/null but you still see the messages.

Can you reproduce mongoose sending debug messages to stderr? Is it possible that there is something in your environment that is changing the default behavior?

**Comment by ORESoftware** [comment]
we are on:

```
"mongoose": "4.13.13"
```

double-checking it does look like it is going to stdout not stderr, not sure why I thought it was going to stderr. However, it would be nice to pass a stream to the `mongoose.set()` call.

**Comment by lineus** [comment]
@ORESoftware My bad, I instinctively assumed you were using `@latest` without information to the contrary. 

Looking at the source for `@4.x`, that **is** going to stderr. I created a PR that adds a note to the migration guide about that for future upgraders. With 4.x, for now at least, you'll need to pass in a custom function. 

With regard to changing the behavior in 4.x, I think the major version bump was probably the right place to do it.

With regard to passing in a stream to `.set()`, personally, I think being able to pass a function in as the value of debug is just the right amount of configuration on the part of mongoose. 

A function lets you handle the messages without adding an optional 3rd parameter to the `mongoose.set()` api, especially one that only applies to 1/10 of the use cases of `mongoose.set()`.  

@vkarpov15 what do you think about passing in a stream to debug, or back-porting 4.x to use `console.info()`?

**Comment by ORESoftware** [comment]
@lineus yes you nailed it, thank you

**Comment by vkarpov15** [comment]
Supporting passing a stream is a great idea. That way you can redirect the stream wherever you want: to a socket, file, etc. without having to write a custom logger. Brilliant.

**Comment by ORESoftware** [comment]
might want to be 

`mongoose.set('debug', true, new Writable());`

so to turn it off, do:

`mongoose.set('debug', false, new Writable());`

but either way
