### ISSUE TITLE
[Symbol(mongoose:lean_populate)] when lean option is passed to find

### ISSUE THREAD

**Issue by Faran52** [Automattic/mongoose#7026]
I'm using 
> mongoose 5.2.15
> Node 8.9.3

Here is my query 
`myschema_instance.findOne(
{},
{},
{
   lean: true
}
)`

Here is my schema
`myschema = new mongoose.schema({
     to_be_populated: {
         type: mongoose.Schema.Types.ObjectId,
         ref" : "model_2"
   }
})
`
`myschema.pre('findOne', function() {
       this.populate({path: "model_2"})
})`

When ever I log the query result I get following attached as well
`{ promo_code: 
   {  //Data populated from model is here,
      [Symbol(mongoose:lean_populate)]: 
      { [Function: model]
        hooks: [Object],
        base: [Object],
        modelName: 'promo_code',
        model: [Function: model],
        db: [Object],
        discriminators: undefined,
        '$appliedMethods': true,
        '$appliedHooks': true,
        schema: [Object],
        collection: [Object],
        Query: [Object],
        '$__insertMany': [Function],
        '$init': [Object],
        '$caught': true } } }` 

I get this Symbol(mongoose:lean_populate) field extra attached, however I don't get this field if I dont  use lean option and manually convert mongoose document to POJO using toObject()

**Comment by vkarpov15** [comment]
Mongoose adds this property to keep track of the model that the lean document was populated with to work around issues like #6908. You're right, it does show up in `console.log()`, but it will never show up in `JSON.stringify()`. We'll see if we can work around this using [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) instead.

**Comment by Faran52** [comment]
I was thinking the same thing setting as WeakMap or if possible we can add another _mongooseOption like lean_debug something for getting lean property attached as a weakMap.

**Comment by vkarpov15** [comment]
The problem with adding a _mongooseOption is that a lean document doesn't have _mongooseOptions :) That's why we added a symbol instead. But a WeakMap will likely be a better approach for debugging purposes.

**Comment by Faran52** [comment]
Yeah you are right
