### ISSUE TITLE
How to add function to response's prototype?

### ISSUE THREAD

**Issue by maxzhou0** [Automattic/mongoose#7028]
```
 require('http').ServerResponse.prototype.success = (data,code='0')=>{
   console.log(this)
   this.send({code:'0',data:data})
 }
```

this.send is not a function and this is {}

**Comment by lineus** [comment]
**Please only open mongoose related issues in this queue.**

   1) arrow functions don't treat `this` the same as common functions. Use common a common function to define `success` on the ServerResponse prototype.
   1) http.ServerResponse doesn't have a send method ( maybe you're using express? if so, `this` should be correct now ).

**here's a simple example that shows a common function defining success and the output on the client side:**

### 7028.js
```js
#!/usr/bin/env node
'use strict';

const http = require('http');
const port = 3000;

http.ServerResponse.prototype.success = function() {
  this.end(JSON.stringify({ code: '0', data: { x: 'yz' } }));  // note end not send.
};

const requestHandler = (request, response) => {
  response.success();
};

const server = http.createServer(requestHandler);

server.listen(port, (err) => {
  if (err) {
    return console.log('something went wrong', err);
  }

  console.log(`listening on ${port}`);
});
```

### Client Output:
```
~: curl http://localhost:3000
{"code":"0","data":{"x":"yz"}}
```
