### ISSUE TITLE
Model remains opened handles

### ISSUE THREAD

**Issue by Rokt33r** [Automattic/mongoose#7029]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When I run Jest with --detectOpenHandles, I keep getting lots of warnings from the mongoose models.

```
  ●  PROMISE

      69 | }
      70 |
    > 71 | const User = connection.model<User>('User', UserSchema, 'User', true)
         |                         ^
      72 |
      73 | export default User
```

Same as https://stackoverflow.com/questions/50687592/jest-and-mongoose-jest-has-detected-opened-handles/50704478#50704478

I assume it should return a Promise which never returns.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can find it if you run any tests with mongoose model in Jest

**What is the expected behavior?**

There should be no opened handles.

**Please mention your node.js, mongoose and MongoDB version.**

Mongoose  v5.1.2
Node.js v10.6.0

**Comment by lineus** [comment]
@Rokt33r Are you explicitly closing your connection(s) after all of your tests have completed? Are you running jest in the 'node' testEnvironment?

Here is an example that has no open handles:

### jest.config.js
```js
module.exports = {
  testEnvironment: 'node'
}

```

### 7029.test.js
```js
'use strict';

const mongoose = require('mongoose');
const { Schema, connection } = mongoose;

describe('tests', function() {
  beforeAll(async function() {
    const URI = 'mongodb://localhost:27017/gh7029';
    const OPTS = { useNewUrlParser: true };
    await mongoose.connect(URI, OPTS);
  });
  
  afterAll(function() {
    connection.close();
  });
  
  it('gh7029', async function() {
    const schema = new Schema({ name: String });
    const Test = mongoose.model('test', schema);
    await Test.create({ name: 'abcxyz' });
    let doc = await Test.findOne({});
  
    expect(doc).toHaveProperty('_id');
    expect(doc).toHaveProperty('name', 'abcxyz');
  });
});
```
### Output: 
```
7029: ./node_modules/.bin/jest --detectOpenHandles
 PASS  ./7029.test.js
  tests
    ✓ gh7029 (64ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.659s, estimated 3s
Ran all test suites.
7029:
```

**Comment by andersnm** [comment]
FYI I had what sounds like a related issue. After adding an index to a schema, Jest started to randomly complain about `Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.` and failed the test. (although running Jest with --detectOpenHandles seemed to fix the issue!)

To progress, I had to await the model's init method like this:

```js
const Test = mongoose.model('test', schemaWithIndex);
await Test.init();
```

(Spent a day on this until I accidentally read the documentation for Model.init()

**Comment by Rokt33r** [comment]
It works fine after I run tests in `node` test env!
