### ISSUE TITLE
When querying, {field: value} gets overridden by {field: mongoQuery}— only in 5 (not 4)

### ISSUE THREAD

**Issue by n-rook** [Automattic/mongoose#7030]
Here is a possible bug I found when upgrading Mongoose 4 to 5. If you have a query like this;

```javascript
  const results = await Baseball.find({
    status: 'baseball',
  }).where({status: {$ne: 'wiffleball'}});
```

In Mongoose 4, the query will be debug logged as: `baseballs.find({ status: 'baseball' }, { fields: {} })`
In 5, it will be: `baseballs.find({ status: { '$ne': 'wiffleball' } }, { projection: {} })`

And indeed, in 5, it matches documents whose status is neither "baseball" nor "wiffleball". But in 4, it doesn't.

If I replace `status: 'baseball'` with `status: {$eq: 'baseball'}`, I get the expected behavior.

I think this is a bug, but I am not sure. If it is expected behavior, you might want to update the migration notes.

A full reproduction script is below.
```javascript
const mongoose = require('mongoose');
const Promise = require('bluebird');

mongoose.Promise = Promise;

mongoose.connect('mongodb://localhost/minimal', {});
mongoose.set('debug', true);

const baseballSchema = mongoose.Schema({
  status: {
    type: String,
    enum: ['baseball', 'softball', 'wiffleball']
  }
});
const Baseball = mongoose.model('Baseball', baseballSchema);

async function run() {
  await Baseball.deleteMany();
  await Baseball.create({
    status: 'softball',
  });

  const results = await Baseball.find({
    status: 'baseball',
  }).where({status: {$ne: 'wiffleball'}})
  console.log('* Results *\n', results);
  // Prints the softball on 5, prints nothing in 4
}

run();
```

I am running on Node 8.9.1. The versions of Mongoose I saw this with were 5.2.15 and 4.13.17.

**Comment by vkarpov15** [comment]
This seems like expected behavior. If you overwrite a property that you're filtering by, Mongoose should overwrite it. I'll add it to the release notes, thanks for the info.
