### ISSUE TITLE
unable to find index for $geoNear query even if it exists

### ISSUE THREAD

**Issue by jairusd** [Automattic/mongoose#7035]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
unable to find index for $geoNear query even if it exists

**If the current behavior is a bug, please provide the steps to reproduce.**

This is how my schema looks like:
```javascript
export const ProviderSchema = new Schema({
  address: {
    location: {
      coordinates: {
        required: true,
        type: [Number],
      },
      type: {
        enum: ['Point'],
        required: true,
        type: String,
      },
    },
  },
}, {
  timestamps: true,
});

ProviderSchema.index({ 'address.location': '2dsphere' });
export const Provider = mongoose.model('Provider', ProviderSchema);
```

This is how my aggregate looks like:
```javascript
return Provider
  .aggregate([
    {
      $geoNear: {
        distanceField: 'address.distance',
        near: [parseFloat(lng), parseFloat(lat)],
        query,
      },
    },
  ])
```

I know my collection is indexed because Provider.listIndexes() returns this result:
```javascript
[
  { v: 2, key: { _id: 1 }, name: '_id_', ns: 'patients.providers' },
  { v: 2,
    key: { 'address.location': '2dsphere' },
    name: 'address.location_2dsphere',
    ns: 'patients.providers',
    background: true,
    '2dsphereIndexVersion': 3
  }
]
```

And when i run this query directly on mongodb, It works as expected:
```javascript
db.providers.aggregate([
    {
        $geoNear: {
            near: { type: 'Point', coordinates: [-104,39]},
            distanceField: 'address.distance',
            spherical: true
        }
    }
])
```

**What is the expected behavior?**

Should aggregate properly with the distance appended in the address field

**Please mention your node.js, mongoose and MongoDB version.**
version: "mongodb": "^3.1.6", "mongoose": "^5.2.16",

**Comment by jairusd** [comment]
Hi @lineus you are correct i was missing the spherical option so it was looking for the 2d index instead of the 2dsphere. That was my bad. I think it would be a good idea to make the error message more specific at this point saying you are trying to to query for a spherical/non-spherical geoquery but what you have in your index is  spherical/non-spherical or whatever works at this point.

Also i think there are discrepancies in the docs: https://mongoosejs.com/docs/api.html#aggregate_Aggregate-near

near says 'Appends a new $geoNear operator to this aggregate pipeline.' but it didn't work so I used the geoNear keyword instead and now it works.

**Comment by lineus** [comment]
@jairusd I'm glad it was something we could help with!

**With regard to the error message**, It's hard to say without having seen it, but it probably says `MongoError:`. If so, then it comes from the underlying native mongodb driver as opposed to mongoose. If you'd like, I can see if I can help with a native driver example that has the same output to open a new issue directly with them.

**With regard to the When you pass an array into** `Model.aggregate()`, mongoose passes the pipeline stages directly through to the driver as you wrote them. *However*, when you use the mongoose aggregation helper methods to create the pipeline, **which is what the docs you pointed out are for**, calling the near helper method will add a `$geoNear` stage to the pipeline.

Here's a trimmed down version of the example I shared earlier that demonstrates this.

### 7035_2.js
```js
#!/usr/bin/env node --no-deprecation
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
let URI = 'mongodb://localhost:27017/test';
let OPTS = { useNewUrlParser: true };

mongoose.connect(URI, OPTS);
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({});

async function run() {
  assert.strictEqual(mongoose.version, '5.2.16');
  const Test = mongoose.model('test', schema);
  
  const nearObject = {
    distanceField: 'address.distance',
    near: [3, 3],
    spherical: true,
    query: { name: /^Test/ }
  };

  let agg = Test.aggregate().near(nearObject);
  console.dir(agg._pipeline);
  assert.ok(Object.keys(agg._pipeline[0]).includes('$geoNear'));
  console.log('All Assertions Pass.');
  return conn.close();
}

run().catch(console.error);

```
### Output:
```
issues: ./7035_2.js
[ { '$geoNear':
     { distanceField: 'address.distance',
       near: [Array],
       spherical: true,
       query: [Object] } } ]
All Assertions Pass.
issues:
```
