### ISSUE TITLE
findOneAndUpdate doesn't run validations

### ISSUE THREAD

**Issue by NormanPerrin** [Automattic/mongoose#7037]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`findOneAndUpdate` doesn't run the `required` validations, neither with the third parameter of the method or with the pre hook.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. The model: `model/section.js`
```javascript
const Section = new Schema({
    _id: {type: String},
    name: {type: String, required: true, unique: true},
    title: {type: String, required: true, unique: true}
}, {collection: 'sections', timestamps: true});

Section.pre('findOneAndUpdate', function (next) {
    // workaround that works..
    // const {title, name} = this.getUpdate();
    // if (!isString(name)) {
    //     throw new Error('cannot save a Section with undefined name');
    // }
    // if (!isString(title)) {
    //     throw new Error('cannot save a Section with undefined title');
    // }

    this.options.upsert = true;
    this.options.runValidators = true;
    this.setDefaultsOnInsert = true;

    next();
});

module.exports = mongoose.model('Section', Section);
```

2. The service: `service/section.js`
```javascript
const {Section} = require('../model');
const {isNil, isString, assign} = require('lodash');

class SectionService {
    static save(section) {
        if (isNil(section)) {
            throw new Error('undefined Section');
        }
        return Section.findOneAndUpdate(
            {_id: section.name},
            assign(section, {_id: section.name})
        ).lean().exec();
    }
}
```

3. Try to save a document:
```javascript
SectionService.save({name: 'name', custom: 'custom'});
```

4. Then the document it's saved without the `custom` field.

**What is the expected behavior?**
Should throw an error for being with a `title` field as`required`.

**Please mention your node.js, mongoose and MongoDB version.**
`5.2.16`

**Comment by lineus** [comment]
>What is the expected behavior?
Should throw an error for being with a title field asrequired.

Update validators only run on paths in the update doc [as described in the docs here](https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths)

**Comment by NormanPerrin** [comment]
So this should run validations? @lineus 

```javascript
static save(section) {
    return Section.updateOne(
        {_id: section.name},
        {$set: assign(section, {_id: section.name})},
        {upsert: true, runValidators: true, setDefaultsOnInsert: true}
    ).exec();
}
```

**Comment by lineus** [comment]
@NormanPerrin No, regardless of the update method called or whether defaultsOnInsert is true or false, **only on the paths that are in the update doc** *( the second parameter to `Model.*update*()` )* will be **validated** with `{ runValidators: true }`. 

### Here are a couple of potential solutions

You could write a static method that calls `Model.findOne()` and either `Model.updateOne()` or `Model.create()` depending on the existence of a doc that matches your condition. Using this static method instead of `Model.findOneAndUpdate()` will ensure new docs are validated as expected, but results in two db operations instead of one.

Or, you could write a pre hook on `findOneAndUpdate` that checks for `upsert`, and the presence of all `required` paths in the update doc. This has the benefit of only one db operation, but returns a generic error instead of a mongoose validation error.

Here's an example that includes both of these options:

### 7037.js
```js
#!/usr/bin/env node
'use strict';

const errors = [];
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useFindAndModify', false);
const { Schema, connection} = mongoose;
const GH = 'gh7037';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: {
    type: String,
    required: true
  },
  other: {
    type: String,
    required: true
  }
});

schema.statics.updateOrSaveNew = async function(cond, update) {
  let existing = await this.findOne(cond);
  if (existing) {
    return this.updateOne(cond, update);
  } else {
    return this.create(update.$set || update);
  }
};

schema.pre('findOneAndUpdate', function(next) {
  let options = this.getOptions();
  let update = this.getUpdate();
  if(options.upsert === true) {
    schema.requiredPaths().map(p => {
      if (!(update[p] || update.$set[p])) {
        let str = `path '${p}' is required with upsert === true`;
        return next(new Error(str));
      }
    });
  }
  next();
});

const Test = mongoose.model('test', schema);

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();

  // findOneAndUpdate upsert with missing path ( error )
  let cond = { name: 'doesnt exist' };
  let update = { $set: { name: 'something' } };
  let opts = { new: true, upsert: true };
  await Test.findOneAndUpdate(cond, update, opts).catch(error);
  let none = await Test.countDocuments();
  assert.strictEqual(none, 0);

  // findOneAndUpdate upsert with both paths ( works )
  update.$set.other = 'now';
  await Test.findOneAndUpdate(cond, update, opts).catch(error);
  let one = await Test.countDocuments();
  assert.strictEqual(one, 1);

  // use static method with missing path ( error )
  update = { $set: { name: 'xyz' } };
  await Test.updateOrSaveNew(cond, update).catch(error);
  one = await Test.countDocuments();
  assert.strictEqual(one, 1);

  // use static method with both paths ( works )
  update.$set.other = 'testing123';
  await Test.updateOrSaveNew(cond, update).catch(error);
  let two = await Test.countDocuments();
  assert.strictEqual(two, 2);

  assert.strictEqual(errors.length, 2);
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
  
function error(e) {
  errors.push(e.message);
}

```

### Output:
```
issues: ./7037.js
All Assertions Pass.
issues:
```

@vkarpov15 thoughts?

**Comment by vkarpov15** [comment]
It might be an interesting idea to validate that all required paths are set in $set or $setOnInsert if upsert and run validators are set. What do you think about that @lineus ?

**Comment by lineus** [comment]
I like that idea @vkarpov15. I think a shortcoming in my handling of the missing paths in the pre hook above is that it will error out on the first path, it might be better if we include all paths that are missing in the update doc instead.
