### ISSUE TITLE
Links to built-in validators broken in documentation

### ISSUE THREAD

**Issue by d4mr** [Automattic/mongoose#7040]
**Bug**

**Current Behaviour:**
Links lead to the docs API homepage

**Steps To Reproduce:**
The page at https://mongoosejs.com/docs/validation.html#built-in-validators states that "each of the validator links above provide more information about how to enable them and customize their error messages." However, the links lead straight to the API homepage. A search of that page suggests that there is no information regarding built-in-validators there.

**Expected Behaviour:**
Should lead to pages detailing built-in-validators.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP
