### ISSUE TITLE
Mongoose cannot register a global plugin on runtime

### ISSUE THREAD

**Issue by vorillaz** [Automattic/mongoose#7042]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug

**What is the current behavior?**
I am trying to register a global plugin within a closure with not

**If the current behaviour is a bug, please provide the steps to reproduce.**
I am trying to bootstrap mongoose with a simple Express.js app. My app sets up a few dependencies and I am trying to pass a global plugin for mongoose within a closure. The `console.log` does not work at all and the methods are missing from my schemas.

```javascript
const mongoose = require('mongoose');

const config = {};
const {DB_CONNECT} = process.env;

const myPlugin = schema => {
  console.log('done'); // this line is not executed
  schema.methods.mymethod = () => {};
}

const connectAndAddPlugins = async () => {
  await mongoose.connect(
    DB_CONNECT,
    {...config}
  );
  mongoose.plugin(myPlugin)
};

connectAndAddPlugins();
```

**What is the expected behavior?**
`mymethod` shall be present to my internal models.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v9.3.0
mongoose: ^5.2.13
MongoDB: v4.0.2

**Comment by vorillaz** [comment]
Apparently, since mongoose compiles the first model global plugins are not applied any more.

**Comment by LouisGirones** [comment]
Sorry to comment on old issue but I am actually having the exact same problem. 
There is still no way to registerate a global plugins ? 

Did exactly what is posted on https://mongoosejs.com/docs/plugins.html#global except my plugin is just 

```
module.exports = exports = function myPlugin (schema, options) {
  console.log('hello mongoose global plugin')
}
```

But there is no console output.
Also I am doing 
`mongoose.plugin(require(./myPlugin.js))`

before doing anythin, my server.js file looks likes :

```
// some require 
mongoose.plugin(require(./myPlugin.js))
mongoose.connect(...)

const app = express()
const server = http.createServer(app)

// routes config

server.listen(config.port, () => {
    console.log(`Express server listening on port ${config.port}, in ${app.get('env')} mode`)
})
``
