### ISSUE TITLE
some of the functions is missing with ^5.2.16

### ISSUE THREAD

**Issue by deckyfx** [Automattic/mongoose#7043]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

[BUG] 
Version: ^5.2.16
MongoDB: not yet connected
Current behavior: some of the functions is missing, for example ```mongoose.model```
Expected: ```model<T extends Document>(name: string, schema?: Schema, collection?: string,
    skipInit?: boolean): Model<T>;```

the types definition is working, but when compiled / used, it crash in runtime since model function is missing

here is the contents of ```import * as mongoose```
```
{ PromiseProvider:
   { _promise: [Function: callIntoRenderer],
     get: [Function: callIntoRenderer],
     set: [Function: callIntoRenderer] },
  Error: [Function: callIntoRenderer],
  Schema: [Function: callIntoRenderer],
  Types:
   { Array: [Function: callIntoRenderer],
     Buffer: [Function: callIntoRenderer],
     Embedded: [Function: callIntoRenderer],
     Document: [Function: callIntoRenderer],
     DocumentArray: [Function: callIntoRenderer],
     Decimal128: [Function: callIntoRenderer],
     ObjectId: [Function: callIntoRenderer],
     Map: [Function: callIntoRenderer],
     Subdocument: [Function: callIntoRenderer] },
  VirtualType: [Function: callIntoRenderer],
  SchemaType: [Function: callIntoRenderer],
  utils:
   { toCollectionName: [Function: callIntoRenderer],
     deepEqual: [Function: callIntoRenderer],
     last: [Function: callIntoRenderer],
     clone: [Function: callIntoRenderer],
     promiseOrCallback: [Function: callIntoRenderer],
     options: [Function: callIntoRenderer],
     random: [Function: callIntoRenderer],
     merge: [Function: callIntoRenderer],
     toObject: [Function: callIntoRenderer],
     isObject: [Function: callIntoRenderer],
     isPOJO: [Function: callIntoRenderer],
     args: [Function: callIntoRenderer],
     tick: [Function: callIntoRenderer],
     isMongooseObject: [Function: callIntoRenderer],
     expires: [Function: callIntoRenderer],
     PopulateOptions: [Function: callIntoRenderer],
     populate: [Function: callIntoRenderer],
     getValue: [Function: callIntoRenderer],
     setValue: [Function: callIntoRenderer],
     object:
      { vals: [Function: callIntoRenderer],
        shallowCopy: [Function: callIntoRenderer],
        hasOwnProperty: [Function: callIntoRenderer] },
     isNullOrUndefined: [Function: callIntoRenderer],
     array:
      { flatten: [Function: callIntoRenderer],
        unique: [Function: callIntoRenderer] },
     buffer: { areEqual: [Function: callIntoRenderer] },
     getFunctionName: [Function: callIntoRenderer],
     decorate: [Function: callIntoRenderer],
     mergeClone: [Function: callIntoRenderer],
     each: [Function: callIntoRenderer],
     noop: [Function: callIntoRenderer] },
  Document: [Function: callIntoRenderer] }
```

**Comment by vkarpov15** [comment]
`import * as mongoose` is not supported. The only ES6 import syntax we currently support is `import mongoose from 'mongoose';` and in general there really isn't a way for us to support `import * as mongoose` with the way our code is currently structured. Sorry for the trouble.

**Comment by deckyfx** [comment]
```import mongoose from 'mongoose'; ```
raise error ```mongoose has no default export```

while
```import * as mongoose from 'mongoose'; ```
still work at the following versions
```"mongoose": "^5.2.2",
"@types/mongoose": "^5.2.0",```

**Comment by vkarpov15** [comment]
@deckyfx what transpiler are you using? I haven't seen the 'no default export' error you mentioned even though we [support building with webpack](https://mongoosejs.com/docs/browser.html#webpack). If you're using typescript, you might try the suggestion from [this comment](https://github.com/Microsoft/TypeScript-React-Starter/issues/8#issuecomment-301265017)
