### ISSUE TITLE
Number silently casted to an array

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#7046]
When assigning a number to `[String]`, it's silently converted to an array. Document validation succeeds. It makes it impossible to write reliable validation code if values are converted like that.

```js
#!/usr/bin/env node
(async function () {
  const mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true});

  const schema = new mongoose.Schema({
    someArray: [String]
  });
  const Model = mongoose.model('model', schema);
  const doc = new Model();

  doc.someArray = 123123;
  console.log(doc.someArray); // ['123123']
  console.log(doc.validateSync()); // no error
})();
```

Tested on mongoose 5.2.17

**Comment by lineus** [comment]
Closing this in favor of #7045, as this is expected, but I agree it would be cool to be able to turn it off.
