### ISSUE TITLE
How to check modified state on nested schemas

### ISSUE THREAD

**Issue by sarneeh** [Automattic/mongoose#7048]
**Do you want to request a *feature* or report a *bug*?**

A bug, I guess.

**What is the current behavior?**

`doc.modifiedPaths()` returns that paths have been modified (even if they didn't) on models that have nested schemas. What is also interesting: it works completely fine when i don't do `type: ChildSchema` and just embed the schema inline.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const BarSchema = new Schema(
  {
    bar: {
      type: String
    }
  },
  { _id: false }
);

const FooNestedSchema = new Schema({
  foo: {
    type: BarSchema
  }
});

const FooSchema = new Schema({
  foo: {
    bar: {
      type: String
    }
  }
});

const FooNested = mongoose.model('fooNested', FooNestedSchema);
const fooNested = new FooNested({ foo: { bar: 'value' } });

const Foo = mongoose.model('foo', FooSchema);
const foo = new Foo({ foo: { bar: 'value' } });

(async () => {
  await fooNested.save();
  await foo.save();

  fooNested.set({ foo: { bar: 'value' } });
  foo.set({ foo: { bar: 'value' } });

  fooNested.modifiedPaths(); // WRONG: [ 'foo', 'foo.bar' ]
  foo.modifiedPaths(); // CORRECT: []
})();
```

**What is the expected behavior?**

It would be a lot less confusing if both examples would behave the same.

**Please mention your node.js, mongoose and MongoDB version.**

- Node.js: 10.9.0
- Mongoose: 5.2.17

**Additional info**

Is there any workaround for this issue? Can I somehow manually check for equality on a saved document? `schema.pre('validate', () => {})` gives me only access to the already changed document, which is already a bummer. Any ideas?

**Comment by vkarpov15** [comment]
Thanks for reporting, will look into this ASAP. As a workaround, you can use a deep equality check like `lodash.deepEquals()`, just make sure you call `toObject()` on both documents that you're comparing.
