### ISSUE TITLE
refs using mongoose.Types.ObjectId throwing error

### ISSUE THREAD

**Issue by felipevignon** [Automattic/mongoose#7049]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
When using refs in a Schema by mongoose.Types.ObjectId, an error is being thrown: 
"TypeError: Undefined type `ObjectID` at `referenceField`
  Did you try nesting Schemas? You can only nest using refs or arrays."

**If the current behavior is a bug, please provide the steps to reproduce.**
`schema = new mongoose.Schema({
    referenceField = {
      type: mongoose.Types.ObjectId,
      ref: 'OtherSchema'
    }
})
`

**What is the expected behavior?**
this always worked as expected, but now an error is being thrown.
It still works using mongoose.Schema.Types.ObjectId, but I don't really know the difference between the two and the docs are not very clear on this.

EDIT: Actually this doesn't work either. It lets me build my schemas just fine, but when I try to convert a hex into an objectId (i.e. `let oid = new mongoose.Schema.Types.ObjectId(hexStr)`), I'm getting this object (which apparently does not behave like an ObjectId should at all):

> {
  "path": "5a1db79cb96b57f4f95c87e8",
  "instance": "ObjectID",
  "validators": [],
  "setters": [],
  "getters": [],
  "_index": null
}

**Please mention your node.js, mongoose and MongoDB version.**
mongoDB  3.6
nodejs 8.11.4
mongoose 5.2.17

**Comment by felipevignon** [comment]
quick update: for some reason mongoose is all over the place now. Still won't let me use mongoose.Types.ObjectId, yet when I use mongoose.Schema.Types.ObjectId, assigning a perfectly valid hex string to an objectid (i.e. `let oid = new mongoose.Schema.Types.ObjectId(hexStr)`) throws an error. I'm absolutely at a loss here, please help!

**Comment by vkarpov15** [comment]
I'll make a note to clarify this in the docs. Plus, Mongoose should be able to handle `type: mongoose.Types.ObjectId`, no reason why not, and it'll save people some headache.
