### ISSUE TITLE
select via populate force inclusion excludes other fields

### ISSUE THREAD

**Issue by thomasraydeniscool** [Automattic/mongoose#7050]
**Do you want to request a *feature* or report a *bug*?**
Report a bug regarding forced inclusion (`select: false`).

**What is the current behaviour?**
`Model.select('+field')` behaves differently compared to `.populate({ select: '+field' })`.

- `.populate({ select: '+field' })` is inclusive therefore excludes all the other fields not projected.

- `Model.select('+field')` *(desired behaviour)* just force includes the projected fields and doesn't remove other fields on the document.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const oneSchema = mongoose.Schema({
  two: {
    type: ObjectId,
    ref: 'Two'
  }
});

const twoSchema = mongoose.Schema({
  hello: {
   type: String,
   select: false
  },
  world: {
    type: String
  }
});

const One = mongoose.model('One', oneSchema);
const Two = mongoose.model('Two, twoSchema);

One.find().populate({ path: 'two', select: '+hello' });
// result: [{ two: { hello: 'test' } }]

Two.find().select('+hello');
// result: [{ two: { hello: 'test', world: 'test' } }]
```

**What is the expected behavior?**
`.populate({ select: '+field' })` should not remove other fields when force including.
```
...

One.find().populate({ path: 'two', select: '+hello' });
// result: [{ two: { hello: 'test', world: 'test' } }]

Two.find().select('+hello');
// result: [{ two: { hello: 'test', world: 'test' } }]
```

**Please mention your node.js, mongoose and MongoDB version.**
- Node version: v10.10.0
- Mongoose version: v5.2.17

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP

**Comment by vkarpov15** [comment]
Hmm upon closer inspection it looks like I can't repro this. The below script gives me the desired output on 5.2.17 and 5.3.1:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7050`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const oneSchema = mongoose.Schema({
    two: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Two'
    }
  });

  const twoSchema = mongoose.Schema({
    hello: {
     type: String,
     select: false
    },
    world: {
      type: String
    }
  });

  const One = mongoose.model('One', oneSchema);
  const Two = mongoose.model('Two', twoSchema);

  const two = await Two.create({ hello: 'foo', world: 'bar' });
  await One.create({ two: two._id });

  // Prints out with both "hello" and "world" paths in 'two'
  console.log(await One.find().populate({ path: 'two', select: '+hello' }));

  console.log(await Two.find().select('+hello'));
}
```

Can you please modify the above script to reproduce your issue?

**Comment by thomasraydeniscool** [comment]
I just tested and your right, it has gone away for me too. I think it might have been a problem with my node_modules. I have been having this issue on and off, so it's been hard to pin it down. I'll let you know if it starts happening again and I can reproduce it.

**Comment by vkarpov15** [comment]
Thanks, will investigate ASAP

**Comment by vkarpov15** [comment]
@thomasraydeniscool I ran your script locally and got the expected output, the `cat` property shows up on both Mongoose 5.2.17 and 5.3.2.

```
{ _id: 5bbcaf8a644ad00ec3d373af,
  name: 'Zildjian',
  __v: 0,
  friends: 
   [ { _id: 5bbcaf8a644ad00ec3d373b0,
       cat: 5bbcaf8a644ad00ec3d373af,
       secret: 'I ate all the scooby snacks!' } ],
  id: '5bbcaf8a644ad00ec3d373af' }
```

Does this not work on your machine?

**Comment by thomasraydeniscool** [comment]
That script doesn't work on my machine no.

I should have included the expected output, sorry, because you got the error also.
**Notice how inside the friends array the object has no** `name` **field?**

The output should be:
```
{ _id: 5bbcaf8a644ad00ec3d373af,
  name: 'Zildjian',
  __v: 0,
  friends: 
   [ { _id: 5bbcaf8a644ad00ec3d373b0,
       name: 'Scooby',
       cat: 5bbcaf8a644ad00ec3d373af,
       secret: 'I ate all the scooby snacks!' } ],
  id: '5bbcaf8a644ad00ec3d373af' }
```

**Comment by vkarpov15** [comment]
Oh good catch, I missed that. Will fix this asap
