### ISSUE TITLE
Warning when adding hashed index to _id field

### ISSUE THREAD

**Issue by toniov** [Automattic/mongoose#7053]
Hi there,

I'm setting the `_id` field as `hashed`:

```
{ _id: { index: 'hashed' } }
```

But I'm getting the next warning (current version 5.2.17):

```
mongoose: Cannot specify a custom index on `_id` for model name "bar", MongoDB does not allow overwriting the default `_id` index. See http://bit.ly/mongodb-id-index
```

I think in this case this warning does not make sense, since it's possible to [add a hashed index](https://docs.mongodb.com/manual/core/index-hashed/#create-a-hashed-index) to the `_id` field in MongoDB.

Regards.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP :+1:
