### ISSUE TITLE
mongoose does not work with child processes nodejs ??

### ISSUE THREAD

**Issue by monasingh27294** [Automattic/mongoose#7054]
mongoose does not work with child processes nodejs ??
const cp = require('child_process');
const child = cp.fork('./workers');

child.send({id:123});

child.on('message', function(m) {
   console.log('received: ' + m);
});

./worker file

const users = require('../models/user');
process.on('message', function (data) {
  users.findOne().then((user) => {
           **console.log("in this")**
           process.send(user)
        }).catch((err) => {
            console.log(err)
         })

})

Its not working,
even though **console.log("in this")** its also not logging

**Comment by lineus** [comment]
are you connecting to the database in your worker @monasingh27294 ?

The following example works:

### 7054.js
```js
#!/usr/bin/env node
'use strict';

const cp = require('child_process');
const child = cp.fork('./workers');

child.on('message', m => {
  console.log(m);
});

child.on('close', c => {
  console.log(`Child exited with code: ${c}`);
  process.exit(c);
});
```
### workers.js
```js
'use strict';

const mongoose = require('mongoose');
const { Schema, connection } = mongoose;
const URI = 'mongodb://localhost:27017/gh-7054';
const OPTS = { useNewUrlParser: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.create({ name: 'test1' });
  let found = await Test.findOne({});
  process.send(found);
  return connection.close();
}

run();
```

### Output:
```
7054: ./7054.js
{ _id: '5bab85ab9ef81b4e3a516cdb', name: 'test1', __v: 0 }
Child exited with code: 0
7054:
```

**Comment by monasingh27294** [comment]
I am using this code in worker file


process.on('message', function (m) {

    require('../../../config/mongoose'); // connection to a DB 
   let user = require('./models/user) 

    user.find((x) => {
        console.log("----------------")
        process.send(x);

    }).catch((err) => {
        console.log(err)
    });

});


but receiving null

**Comment by lineus** [comment]
@monasingh27294 you should either pass a callback or use the promise like methods on queries, not use both at the same time. 

The first parameter to the callback is error, so in your example you are only handling the error in the callback and the error in catch, you never see the found documents.

try:
```
user.find({})
  .then((x) => {
    console.log("----------------")
    process.send(x);
  })
  .catch((err) => {
    console.log(err)
  });
```

**Comment by monasingh27294** [comment]
Thanx
