### ISSUE TITLE
List out all supported operations and options for `bulkWrite()`

### ISSUE THREAD

**Issue by horoscop** [Automattic/mongoose#7055]
Hi!

With all due respect, could you please improve your documentation? We all have to search again and again for things that usually should be in the documentation. 
Example: https://stackoverflow.com/questions/39988848/trying-to-do-a-bulk-upsert-with-mongoose-whats-the-cleanest-way-to-do-this

Make it available for edit, idk.. but do something..

Thank you!

Later edit:
Hit the like button to highlight the need for better docs.

**Comment by vkarpov15** [comment]
Thanks for the suggestion re: listing out what operations and options go into `bulkWrite()`. We'll add that. But next time, can you please provide more actionable issues than "please improve your documentation"? The more concrete your suggestions are, the more we can do to help :+1:
