### ISSUE TITLE
new TypeError('Undefined type `' + name + '` at `' + path +     ^  TypeError: Undefined type `undefined` at `name.required`

### ISSUE THREAD

**Issue by Anant016** [Automattic/mongoose#7066]
let mongoose = require('mongoose');

let UserSchema = mongoose.Schema({
    name:{
        user: String,
        required: true
    },
    password:{
        type : String,
        required:true
    },

})

let User = module.exports = mongoose.user('User', UserSchema);

**Comment by lineus** [comment]
@Anant016 it looks like you want the `name.user` path to be required, if that's the case you need to nest the required path with a type under `name.user` like:

```js
let UserSchema = mongoose.Schema({
  name: {
    user: {
      type: String,
      required: true
    }
  },
  password: {
    type: String,
    required: true
  }
});
```
