### ISSUE TITLE
Cannot manually populate a dynamic reference (refPath)

### ISSUE THREAD

**Issue by aletorrado** [Automattic/mongoose#7070]
Hi, I'm trying to manually populate a dynamic reference, because I'm applying a custom filter for populating (which doesn't seem to fit the populate options, because it receives a static match query), but it doesn't seems to be working.

This is the code to verify:

```
db.Conversation.findOne().exec().then(conv=>{
	db[conv.model].findById(conv.doc).exec().then(doc=>{
		conv.doc = doc;
		console.log(doc, conv)
	})
})
```

Can you confirm me if this is a bug, or which workaround may I use?

Thanks

**Comment by aletorrado** [comment]
Yeap. I have a model named Conversation which is transversal to any model. I defined it like this:

```
const mySchema = Schema({
	model: { type: String, required: true },
	doc: { type: mongoose.Schema.Types.ObjectId, required: true, refPath: 'model' },
	....

const Conversation = mongoose.model('Conversation', mySchema);
```

**Comment by aletorrado** [comment]
Hi, do you need any more info about this? It's pretty straightforward to test, but let me know how can I help.

BTW, do you have any bulletproof way to force manual population in the meanwhile?

**Comment by lineus** [comment]
@aletorrado you've defined the path `doc` on your Conversation schema with `type: ObjectId`, but after you find `doc` from the referenced collection, you try and save the whole value of `doc` back to the conversation `doc` path. 

**Because the Conversation `doc` path is defined as `type: ObjectId`, the value you attempt to assign to it will be cast to an `ObjectId`.** Meaning you end up with the exact same value you started off with in the `doc` path. **This is demonstrated in the following example:**

*note that I did not define the `refPath` property in either of the examples below. I opted not to do so because we're manually selecting the model to populate from based on the `model` property*

### 7070.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7070';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const referencedSchema = new Schema({
  name: String
});

const conversationSchema = new Schema({
  model: {
    type: String,
    required: true
  },
  doc: {
    type: Schema.Types.ObjectId
  }
});

const Other = mongoose.model('other', referencedSchema);
const Conversation = mongoose.model('conversation', conversationSchema);

const other = new Other({ name: 'other1' });
const conversation = new Conversation({ model: 'other', doc: other._id });

function manualPopulate() {
  return Conversation.findOne({}).then(conv => {
    return connection.models[conv.model].findById(conv.doc).then(doc => {
      conv.doc = doc;
      return conv;
    });
  });
}

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await other.save();
  await conversation.save();
  let conv = await manualPopulate();
  assert.deepStrictEqual(conv.doc, conversation.doc);
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7070.js
All Assertions Pass.
issues:
```

**If you want to store the information returned from the other model in the original conversation doc, you'll need to add a path to the conversation schema to do so** ( presumably a [virtual property](https://mongoosejs.com/docs/guide.html#virtuals) to prevent that data from being stored in the db ). **Here's an example:**

### 7070_2.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7041';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const referencedSchema = new Schema({
  name: String
});

const conversationSchema = new Schema({
  model: {
    type: String,
    required: true
  },
  doc: {
    type: Schema.Types.ObjectId
  }
});

conversationSchema.virtual('referencedDoc').get(function() {
  return this.$rDoc;
}).set(function(v) {
  this.$rDoc = v;
});

const Other = mongoose.model('other', referencedSchema);
const Conversation = mongoose.model('conversation', conversationSchema);

const other = new Other({ name: 'other1' });
const conversation = new Conversation({ model: 'other', doc: other._id });

function manualPopulate() {
  return Conversation.findOne({}).then(conv => {
    return connection.models[conv.model].findById(conv.doc).then(doc => {
      conv.referencedDoc = doc;
      return conv;
    });
  });
}

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await other.save();
  await conversation.save();
  let conv = await manualPopulate();
  assert.strictEqual(conv.referencedDoc.name, 'other1');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7070_2.js
All Assertions Pass.
issues:
```

**Comment by aletorrado** [comment]
Thanks for all those examples. That workaround seems to do the trick fine.

I understand the casting behavior of the mongoose document, but if I hardcode the `ref: 'OtherModel'` option, and set on that path a document of OtherModel, the casting behavior is disabled (Manual Population). I think the same should apply when using `refPath` if the referenced document's model matches the one stated on the refPath.

What do you think about this? May this kind of improvement feasible?

**Comment by lineus** [comment]
@vkarpov15 should we formalize ( add to the docs ) the current behavior of paths that are defined with `ref` being allowed to be set manually, and also make paths defined with `refPath` behave the same way?

This issue can be summed up with:

### 7070_3.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7070';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const referencedSchema = new Schema({
  name: String
});

const conversationSchema = new Schema({
  model: {
    type: String,
    required: true
  },
  doc: {
    type: Schema.Types.ObjectId,
    ref: 'other'
  },
  nope: {
    type: Schema.Types.ObjectId,
    refPath: 'model'
  }
});

const Other = mongoose.model('other', referencedSchema);
const Conversation = mongoose.model('conversation', conversationSchema);

const other = new Other({ name: 'other1' });
const conversation = new Conversation({
  model: 'other',
  doc: other._id,
  nope: other._id
});

function manualPopulate() {
  return Conversation.findOne({}).then(conv => {
    return connection.models[conv.model].findById(conv.doc).then(doc => {
      conv.doc = doc;
      conv.nope = doc;
      return conv;
    });
  });
}

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await other.save();
  await conversation.save();
  let conv = await manualPopulate();
  assert.strictEqual(conv.doc.name, 'other1');
  assert.strictEqual(conv.nope.name, 'other1', 'refPath does not allow set');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output:
```
issues: ./7070_3.js
{ AssertionError [ERR_ASSERTION]: refPath does not allow set
    at run (/Users/lineus/dev/node/mongoose/issues/7070_3.js:57:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: 'other1',
  operator: 'strictEqual' }
issues:
```

**Comment by vkarpov15** [comment]
Closed in https://github.com/Automattic/mongoose/commit/7d46351bacd732701441253d013c2a7067802989

**Comment by riginoommen** [comment]
> Yeap. I have a model named Conversation which is transversal to any model. I defined it like this:
> 
> ```
> const mySchema = Schema({
> 	model: { type: String, required: true },
> 	doc: { type: mongoose.Schema.Types.ObjectId, required: true, refPath: 'model' },
> 	....
> 
> const Conversation = mongoose.model('Conversation', mySchema);
> ```
> 
> No more code than this should be relevant.

Where you had refenced the model set https://mongoosejs.com/docs/populate.html#dynamic-ref Referencing this URL
