### ISSUE TITLE
deleteOne is not an option when used with find query indexes

### ISSUE THREAD

**Issue by Faran52** [Automattic/mongoose#7071]
I have a query like this 
`model.find({}, (err, res_query) => {
   /** some additonal code here*/
    res_query.map(q => {
        q.deleteOne();
    })
})`

the problem is deleteOne does not work in this case and reports deleteOne is not a function, I've updated from mongoose 4 to 5 so I've changed remove to deleteOne. It was working fine with remove,  can I not do this and must use removeMany in this case ?
Isn't each `q` doc a document instance ?

EDIT: delete() seems to be working so does remove() on a `q` doc instance and doesn't give any deprecation warning is this intended behavior ?

**Comment by vkarpov15** [comment]
There's a `delete()` function for documents: https://mongoosejs.com/docs/api.html#model_Model-delete . But it is just an alias for doc.remove() , which becomes a deleteOne under the hood. You can use either one interchangeably
