### ISSUE TITLE
mongoose :  replica set  , Error message ::: no primary found in replicaset or invalid replica set name

### ISSUE THREAD

**Issue by gom3441** [Automattic/mongoose#7075]
mongoose version : 5.3.0

    cont  mongoose = require('mongoose')
    
    mongoose.connect('mongodb://localhost:27017,localhost:27017,localhost:27017/test?replicaSet=rsName', {useNewUrlParser:true, });

error message  : no primary found in replicaset or invalid replica set name

I want to duplicate. Yes I followed it correctly and I get an error. What is the problem?

**Comment by vkarpov15** [comment]
Why do you have 'localhost:27017' repeated 3 times? You need 3 distinct host/port combinations. Also, can you [connect with the mongodb shell](https://docs.mongodb.com/manual/reference/program/mongo/#description)?
