### ISSUE TITLE
Document the `fields` parameter for `Model`

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#7077]
**Do you want to request a *feature* or report a *bug*?**
Docs update

**What is the current behavior?**
Docs don't mention the `fields` parameter for the `Model` constructor

**What is the expected behavior?**
Document this behaviour so that we can use it.

To clarify:

https://github.com/Automattic/mongoose/blob/master/lib/model.js#L66
https://mongoosejs.com/docs/api.html#model_Model

I was wondering how Mongoose could create documents when querying and selecting specific fields, without those documents having their defaults set. When I was creating new documents, it would always initialise the defaults, and I didn't find anything in the docs about how to disable that.

After some digging in the code I discovered the `fields` parameter for Model/Document, which essentially provides this functionality. By passing in a projection of fields that you want to include/exclude, Mongoose will respect this and not try to set default values for any fields that aren't included. This is exactly what I was after, would be great if it could be documented.

**Comment by vkarpov15** [comment]
Good idea. We should also make the document constructor public, that will help with this because the `Model()` constructor just calls `Document()` under the hood.
