### ISSUE TITLE
Timestamps not working in 5.3.1

### ISSUE THREAD

**Issue by Christilut** [Automattic/mongoose#7083]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Mongoose 5.3.1
Mongo 3.6.8

Saving any document with the `timestamps` option enabled seems to no longer add any timestamps.

My previous version was `5.2.17` where it does work (downgraded to confirm).

**If the current behavior is a bug, please provide the steps to reproduce.**
The following code:
```js
InvoiceModel.schema.set('timestamps', true)
```

Save a new item. No `createdAt` or `updatedAt` appear in the database.

**What is the expected behavior?**

Timestamps should be saved.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate ASAP. Can you add more substantial code samples? That will help us investigate.

Also, it looks like you're modifying the schema after compiling your model. That is generally not right. Can you try calling `schema.set('timestamps', true)` before calling `mongoose.model('InvoiceModel', schema)`?

**Comment by Christilut** [comment]
I'm using Typegoose and AFAIK it doesn't support setting schema options
during creation so I'm setting them afterwards. Maybe something changed
that setting them afterwards doesn't work anymore?

I thought the timestamps bug might have been Typegoose somehow but since a
mongoose version downgrade fixes it I figured it isn't.

**Comment by Christilut** [comment]
Okay I re-created the bug in a minimal case but the problem must indeed be typegoose since the identical scenario works in mongoose but not typegoose.
Sorry for the waste of time!
