### ISSUE TITLE
Timestamps error when updating document field

### ISSUE THREAD

**Issue by tsybinAndrey** [Automattic/mongoose#7084]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Get document by id. 
Change field and doc.save() return error TypeError: (intermediate value)(intermediate value)(intermediate value).constructor.base.now is not a function
Works OK if I remove `{timestamps: true}` from model
**If the current behavior is a bug, please provide the steps to reproduce.**
```
const userSchema = new Schema({
  email: { type: String },
  info: {
    name: {type: String}
  }
},
{ timestamps: true });
const User = connection.model('User', userSchema);
const found = await User.findById(id)
found.info.name ="New User Name"
await found.save()
```

**What is the expected behavior?**
Timestamps and document should be updated with no error
**Please mention your node.js, mongoose and MongoDB version.**
Mongoose 5.3.1
Node.js v8.11.3

**Comment by vkarpov15** [comment]
The below script works without any errors. Can you please modify the below script to repro your issue?

```javascript
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

run().catch(error => console.error(error.stack));

async function run() {
  const connection = await mongoose.createConnection('mongodb://localhost:27017/test');
  await connection.dropDatabase();

  const userSchema = new Schema({
    email: { type: String },
    info: {
      name: {type: String}
    }
  },
  { timestamps: true });
  const User = connection.model('User', userSchema);

  await User.create({ email: 'test' });

  const found = await User.findOne()
  found.info.name ="New User Name"
  await found.save()

  console.log('done');
}
```
