### ISSUE TITLE
BUG. Embedded Documents Return Only [Object] from Aggregate Query

### ISSUE THREAD

**Issue by wlockiv** [Automattic/mongoose#7087]
Howdy, I'm currently using v8.11.3 of Node, 4.0.3 of MongoDB Shell, v3.1.6 of the MongoDB js library v5.3.1 of Mongoose.

I am trying to render an ejs page with some data from a Mongo db. I am using an aggregate function to `$match`, and `$project` the data (I would like to break the date up into a friendlier format). Instead of displaying the entries (`date`and `hoursWorked`) from the embedded document, `laborEntries`, it simply returns `laborEntries: [ [Object], [Object] ],` in the result. The renderer will then not execute a `forEach()` on that array and claims it is _undefined_. When I query the Mongo db from the command line in the same fashion, it returns the full values of those entries. 

```JavaScript
// The Schema File (./models/iso.js)

var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var IsoSchema = mongoose.Schema({
  isoTag: {
    type: String,
  },
  laborEst: {
    type: Number,
  },
  laborEntries: [{
    date: Date,
    hoursWorked: Number
  }],
  percentComplete: [Schema.Types.Decimal128]
})

var Iso = module.exports = mongoose.model('Iso', IsoSchema, 'iso-progress');
```

```JavaScript
// The aggregate query in question (./routes/isos.js)

router.get('/', (req, res) => {
  let tag = req.query.tag;
  Iso.aggregate([
    {
      '$match': {
        isoTag: tag,
      }
    },
    {
      '$project': {
        _id: false,
        isoTag: true,
        percentComplete: true,
        laborEntries: true,
      }
    }
  ], (err, result) => {
    if (err) return console.log(err);
    console.log(result);
    res.render('iso.ejs', { iso: result });
  });
});
```

```JSON
// Output from the console.log(result) above

[ { isoTag: '4-L04-WB-A-DW-ISO01',
    laborEntries: [ [Object], [Object] ],
    percentComplete:
     Decimal128 {
       _bsontype: 'Decimal128',
       bytes: <Buffer 4b 00 00 00 00 00 00 00 00 00 00 00 00 00 3c 30> } } ]
```

```JSON
// In contrast, what the MongoDB CLI shows me
// when I copy that query into it the cmd line.

{
        "_id" : ObjectId("5bb3e3a81c9d440000154c39"),
        "isoTag" : "4-L04-WB-A-DW-ISO01",
        "laborEst" : 24,
        "laborEntries" : [
                {
                        "date" : ISODate("2018-10-01T21:33:13Z"),
                        "hoursWorked" : 10
                },
                {
                        "date" : ISODate("2018-10-02T21:33:13Z"),
                        "hoursWorked" : 4
                }
        ],
        "percentComplete" : NumberDecimal("0.75")
}
```

I have searched thoroughly to find others who have had this issue but the proposed solutions don't change the behavior. I've tried defining the schema differently, but to no avail. The `find()` and `findOne()` functions seem to preserve the date and hoursWorked fields similar to the MongoDB CLI.

You can find a repo of the project here: [https://gitlab.com/wlockiv/iso-progress-capture](https://gitlab.com/wlockiv/iso-progress-capture). I've commented out the aggregate function to keep the app working.

Please let me know if you need any more information. This is the first time I've submitted an issue on something like this so I'm sure there's something missing.

**Comment by lineus** [comment]
@wlockiv To fix the `laborEntries: [ [Object], [Object] ]`, instead of `console.log(result)` try `console.log(JSON.stringify(result, null, 2))`. This will display the contents of result[0].laborEntries. This doesn't change the data returned from the aggregation, but it will allow you to see the entirety of the object on console.

**Comment by wlockiv** [comment]
@lineus Thank you! I also realize the aggregate method isn't the only way to do what I'm wanting to do, it seems virtuals are the mongoose way.

**Comment by vkarpov15** [comment]
When you use aggregate, mongoose doesn't hydrate the returned object, so you don't get any of Mongoose's handy inspect output. See https://mongoosejs.com/docs/api.html#model_Model.hydrate
