### ISSUE TITLE
Encoding issue in mongoose documentation

### ISSUE THREAD

**Issue by yoannpicquenot** [Automattic/mongoose#7091]
**Do you want to request a *feature* or report a *bug*?**
Report a little bug in the documentation

**What is the current behavior?**
Just an error of encoding in the **Error message templates:** section of https://mongoosejs.com/docs/api.html#schematype_SchemaType-validate

**If the current behavior is a bug, please provide the steps to reproduce.**

![image](https://user-images.githubusercontent.com/6999772/46462890-e129dc80-c7c2-11e8-8fce-262180c471d6.png)

**What is the expected behavior?**
Having:
`props => ` instead of `props =&gt`

**Please mention your node.js, mongoose and MongoDB version.**
None.

PS Sorry if I've made syntax mistakes :)

**Comment by lineus** [comment]
That's a weird one 👍 Thanks for reporting @yoannpicquenot.
