### ISSUE TITLE
mongoose custom query options: migrating from mongoose 4 to mongoose 5

### ISSUE THREAD

**Issue by joniba** [Automattic/mongoose#7092]
(copied [from stackoverflow](https://stackoverflow.com/questions/52645767/mongoose-custom-query-options-migrating-from-mongoose-4-to-mongoose-5))

I'm trying to upgrade from mongoose 4 to the mongoose 5 (currently 5.3.1). It seems that mongoose 5 no longer supports passing custom options (or even any options for `find`?). Our codebase is highly dependent on various mongoose middlewares that receive their options via custom options, as in:

`myModel.find({}, null, {myCustomMiddlewareOption: true})`

in mongoose 4, myCustomMiddlewareOption would be available on the context and could be read by middleware, as in the following pseudocode:

```
schema.pre('find', function (next) {
    if (this.options.myCustomMiddlewareOption)
        // do something

    return next();
});
```
In mongoose 5 these options are not passed. I also tried using `setOptions`

Is there any known upgrade strategy for this issue? It doesn't seem to be listed in the migration documentation.

**Comment by lineus** [comment]
@joniba The following example shows that your custom option is still passed to the pre query hook. I'm using the `query.prototype.getOptions()` method to get the options in the hook. 

### 7092.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const GH = 'gh7041';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: String
});

schema.pre('find', function() {
  console.log(this.getOptions());
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.1');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  await Test.find({}, null, { myCustomOption: true });
  console.log('All Assertions Pass.');
  return connection.close();
}

run();
```
### Output:
```
issues: ./7092.js
{ myCustomOption: true }
All Assertions Pass.
issues:
```

I'll do a bit of research, I suspect `.options` changed to `._options` or something like that. I'll open a PR for the migration docs once I find the change.

**Comment by joniba** [comment]
sorry it does seems to be working, closing the issue
