### ISSUE TITLE
Contradictions in 'remove' hooks docs

### ISSUE THREAD

**Issue by Spown** [Automattic/mongoose#7093]
Node 10, Mongoose 5.3.1, Mongo 3.2

There are numerous contradictions in the docs regarding this. 

Firstly in the very start there is this:

![](https://drive.google.com/uc?id=1B108_hLgasTuNcpknWQbFSN3FTn0UjL7)

Then goes this note:

![](https://drive.google.com/uc?id=1kWS2DJqTdeLadvSVxGX97xzOpVtpnCs6)

Furthermore to make things even more complicated there is this [Naming Conflicts](https://mongoosejs.com/docs/middleware.html#naming) section that states that

>Mongoose has both __query__ and document hooks for remove().
...
You can pass options to Schema.pre() and Schema.post() to switch whether Mongoose calls your remove() hook for Document.remove() or __Model.remove()__:
...
// Only query middleware. This will get called when you do __Model.remove()__

Both ``schema.pre('remove', { query: true }, callback);`` and ``schema.post('remove', { query: true }, callback);`` work for ``Model.remove():`` (But in the docs for [Model.remove()](https://mongoosejs.com/docs/api.html#model_Model.remove)  it is also stated that it should not work):

>Note:
This method sends a remove command directly to MongoDB, no Mongoose documents are involved. Because no Mongoose documents are involved, no middleware (hooks) are executed.

So which is it? I'm confused.

**Comment by vkarpov15** [comment]
Good catch, will fix asap
