### ISSUE TITLE
[BUG] Aggregate $match with dates not working

### ISSUE THREAD

**Issue by Ncifra** [Automattic/mongoose#7095]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
Having an aggregation with dates in $match, returns no results.
The following:

```
....
match.$match = JSON.parse({"createdAt":{"$gt":{"$date":"2016-08-01"},"$lt":{"$date":"2018-08-05"}}});
filter.push(match);
User.aggregate(filter).sort('name')....
```

With debug on produces this query:

> users.aggregate([{"$match":{"createdAt":{"$gt":{"$date":"2016-08-01"},"$lt":{"$date":"2018-08-05"}}}}{"$sort":{"name":1}}])

The above returns results from MongoDB's shell directly, but seems not to be working with mongoose. Other inputs, like string searching, seem to be working okay.

Also tried removing the "$" from the $date operator, and also removing the $date operator totally from the query, but still empty.

**What is the expected behavior?**
Return the actual results expected from the above date comparison

**Please mention your node.js, mongoose and MongoDB version.**
node.js - 6.9.1
MongoDB - 3.4
mongoose - 4.13.11

**Comment by Ncifra** [comment]
@lineus $date seems to be available only in [MongoDB's strict mode](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#data_date). And from mongoose's documentation it should be [enabled](https://mongoosejs.com/docs/guide.html#strict) by default. In case these two are different types of 'strict' we should be okay in recognizing it.

Also, as I said, the query from the debug mode of mongoose, executes correctly in MongoDB, so please, reopen this, or at least investigate it further, because something doesn't quite add up. Of course, I know that I can do this by "find()", and also by type casting the dates manually, but I think this other one, since it works purely in MongoDB, should work through mongoose too.

Thank you

**Comment by lineus** [comment]
>The strange thing is that mongoose produces the query with it

If by "produces", you mean *allows* it, this is expected. **Mongoose performs no sanity checks, or mutations on aggregation pipeline stages**. We only verify that there is a pipeline present. So whatever objects you put into the pipeline array is exactly what mongoose will send to the native driver's `collection.aggregate()` method. 

>where an external user has access to direct aggregation queries by sending the query in the request

Aggregations can be resource intensive on the server side; both intentionally and accidentally. This seems like a dangerous design choice from both a security perspective and an availability one.

> so that's why I can't convert to Date(), since I parse his request directly.

If you're not in a position to sanitize the incoming pipeline stages before they gets passed along to mongoose, you could write a pre aggregate hook that does. Here's an example of a pre aggregate hook that mutates any `$match` stages that use `$date` under a comparison operator, removing the `$date` and converting the date string to a Date value that can be used in aggregate:

### 7095_2.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const { Schema, connection } = mongoose;
const GH = 'gh7095';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { useMongoClient: true };

const schema = new Schema({
  name: String,
  when: Date
});

schema.pre('aggregate', function() {
  let pipeline = this.pipeline();
  for (let stage of pipeline) {
    for (let op in stage) {
      if (op === '$match') {
        for (let path in stage[op]) {
          for (let queryOp in stage[op][path]) {
            if ( queryOp === '$gt' || '$lt' || '$gte' || '$lte' || '$ne') {
              for (let key in stage[op][path][queryOp]) {
                if (key === '$date') {
                  if (typeof stage[op][path][queryOp][key] === 'string') {
                    stage[op][path][queryOp] = new Date(
                      Date.parse(stage[op][path][queryOp][key])
                    );
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  this._pipeline = pipeline;
});

const Test = mongoose.model('test', schema);

const tests = '12345'.split('').map(n => {
  return {
    name: `test${n}`,
    when: Date.UTC(2018, 7, Number(n))
  };
});

async function run() {
  assert.strictEqual(mongoose.version, '4.13.17');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.create(tests);

  const badMatch = {
    $match: {
      when: {
        $gt: {
          $date: '2018-08-01'
        },
        $lt: {
          $date: '2018-08-05'
        }
      }
    }
  };

  const goodMatch = {
    $match: {
      when: {
        $gt: new Date(Date.UTC(2018, 7, 1)),
        $lt: new Date(Date.UTC(2018, 7, 5))
      }
    }
  };

  let test1 = await Test.aggregate([badMatch]);
  let test2 = await Test.aggregate([goodMatch]);

  assert.deepStrictEqual(test1.map(d => d.name).sort(), ['test2', 'test3', 'test4']);
  assert.deepStrictEqual(test2.map(d => d.name).sort(), ['test2', 'test3', 'test4']);

  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./7095_2.js
All Assertions Pass.
issues:
```
You can see that both the badMatch and goodMatch stages return the correct docs, as shown in the assertions.

**Comment by lineus** [comment]
@Ncifra here's an example script that uses the [mongodb-extjson](https://www.npmjs.com/package/mongodb-extjson) package to convert your pipeline stages to objects that mongodb understands whether they're defined in extended JSON or not. it's a better solution than the convoluted way I came up with :smile:

*NOTE that the output of ejson.parse() on your `$match` object is an equivalent conversion from `badMatch` to `goodMatch` in previous examples.* 

### 7095_3.js
```js
#!/usr/bin/env node
'use strict';

const ejson = require('mongodb-extjson');
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const { Schema, connection } = mongoose;
const GH = 'gh7095';
const URI = `mongodb://localhost:27017/${GH}`;
const OPTS = { useMongoClient: true };

const schema = new Schema({
  name: String,
  when: Date
});

schema.pre('aggregate', function () {
  let pipeline = this.pipeline();
  pipeline.forEach(stage => {
    let topLevelKey = Object.keys(stage)[0];
    let json = ejson.stringify(stage[topLevelKey]);
    stage[topLevelKey] = ejson.parse(json);
  });
});

const Test = mongoose.model('test', schema);

const tests = '12345'.split('').map(n => {
  return {
    name: `test${n}`,
    when: Date.UTC(2018, 7, Number(n))
  };
});

async function run() {
  assert.strictEqual(mongoose.version, '4.13.11');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.create(tests);
  
  const badMatch = {
    $match: {
      when: {
        $gt: {
          $date: '2018-08-01'
        },
        $lt: {
          $date: '2018-08-05'
        }
      }
    }
  };

  let test1 = await Test.aggregate([badMatch]);
  assert.deepStrictEqual(test1.map(d => d.name).sort(), ['test2', 'test3', 'test4']);

  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./7095_3.js
All Assertions Pass.
issues:
```

**Comment by Ncifra** [comment]
> Aggregations can be resource intensive on the server side; both intentionally and accidentally. This seems like a dangerous design choice from both a security perspective and an availability one.

This is supposed to be used for advanced filtering, but from what has been used up until now, the searches can be achieved with find() too actually. We used it first to have the concat() method, but we can have the same with a virtual when I think about it.

I normally posted this not because of not being able in achieving those results, but because as I said, I think that the funcionality in mongoose and MongoDB, especially in returning query results, without any mutations as you noticed, should have been the same. Since we have been using mongoose (and Mongo of course) for at least a year and a half, and have seen quite the capabilities of it, we wanted to notice an improvement to be done, or maybe a missing FAQ, not just being able to solve our own problem and go on. That's why I am being a bit nitpicky in pointing it out, more as someone fixated with strange behaviour in systems I have been working on myself.

These tests are very cool and helpful, we will need to do some training (even of mental laziness), in using these while debugging ourselves.
