### ISSUE TITLE
is not function updateOne

### ISSUE THREAD

**Issue by DorisKGB** [Automattic/mongoose#7096]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by lineus** [comment]
Can you please include a code sample that reproduces what you are seeing @DorisKGB? Here's an example that shows the schema, doc creation, using `Model.updateOne()`, and assertions that codify my expectations for clarity. The Output shows the result of running the script.

### 7096.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7096';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.1');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  await Test.updateOne({ _id: test._id }, { name: 'testONE'});
  let updated = await Test.findOne({});
  assert.strictEqual(updated.name, 'testONE');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7096.js
All Assertions Pass.
issues:
```
