### ISSUE TITLE
bug: bulk create fails after first error

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#7097]
If we do this:

```js
Model.create([ m1, m2, m3, m4, m5 ], function(err, results){

});
```

if inserting m3 fails, the remaining inserts also seem to fail. I would expect that if an insert fails, the other inserts would not be affected. Is there a setting we can use to allow everything else to succeed even if there is a failure?

It looks like `Model.insertMany([])` has the same behavior as `Model.create([])`

**Comment by ORESoftware** [comment]
I tried this too:

		const bulk = Model.collection.initializeUnorderedBulkOp();

I got the same problem. Sad.

**Comment by lineus** [comment]
@ORESoftware what kind of error are you getting when `Model.create()` fails on one of the inputs?

**Comment by lineus** [comment]
@ORESoftware What version of mongoose on you using? 

The following example shows explicitly that with the latest version, **a unique index failure does not inherently cause `Model.create()` to skip creating the rest of the documents**. Can you edit the code to reproduce the issue? 

### 7097.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
const { Schema, connection} = mongoose;
const DB = '7097';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const schema = new Schema({
  name: {
    type: String,
    unique: true
  }
});

const tests = '1223'.split('').map(n => { return { name: `test${n}`};});

const errors = [];
function error(e) {
  errors.push(e.message);
}

async function run() {
  assert.strictEqual(mongoose.version, '5.3.1');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const Test = mongoose.model('test', schema);
  await Test.init();
  await Test.create(tests).catch(error);

  let created = await Test.find({}).lean();
  assert.strictEqual(created.length, 3);
  assert.deepStrictEqual(created.map(d => d.name), ['test1', 'test2', 'test3']);
  assert.strictEqual(errors.length, 1);
  assert.ok(/^E11000/.test(errors[0]));
  console.log('All Assertions Pass');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7097.js
All Assertions Pass
issues:
```

**Side Note**: *if you want your issue addressed without getting asked questions in return, please provide a complete and reproducible script that demonstrates the issue and follow the issue template completely by providing the relevant versions to mongoose/nodejs/mongodb.*

**Comment by lineus** [comment]
One thing worth noting is that `Model.create()` doesn't currently collate all of the errors and return them **all** in the Error. I think this is something we could potentially do, [I updated this pre-existing issue](https://github.com/Automattic/mongoose/issues/1731) for this.

**Comment by ORESoftware** [comment]
We are on mongoose version `"mongoose": "4.13.13"`, do you think the behavior changed with mongoose version 5?

**Comment by ORESoftware** [comment]
Ok so I tried this with version 4.13.13:

```js
Model.insertMany([1,2,3,4,5], {ordered: false}, (err, results) => {});
```

and it works. My only remaining question - is this sending 5 HTTP requests or just 1?

**Comment by lineus** [comment]
`Model.insertMany()` [only sends one insert](https://mongoosejs.com/docs/api.html#model_Model.insertMany).

**Comment by ORESoftware** [comment]
You mean it's just one HTTP request. I assume the 5.x behavior is the same as the 4.x behavior in this case. It seems to be.

**Comment by lineus** [comment]
Mongodb doesn't use http to communicate, it uses the [mongodb wire protocol](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#mongodb-wire-protocol) ( hence the `mongodb://` in all of our connection strings ). The `insertMany()` function sends only one insert command/operation/message to the server containing all of the docs, where as create sends one insert operation per doc. This is true for mongoose 4 and 5.

**Comment by ORESoftware** [comment]
Yeah I should have just said "network request" instead of HTTP, thx
