### ISSUE TITLE
middleware not working after update

### ISSUE THREAD

**Issue by renehauck** [Automattic/mongoose#7100]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I updated an application today by "npm update" for about 2 months and now mocha threw me a few errors.
After a short debug I found out that the two middlewares `post("save")` and `post("remove")` are no longer triggered.
I used the old mongoose version "5.1.6" again and the middlewares was executed as usual.
Is this a bug or did I miss something?

**Comment by lineus** [comment]
@renehauck The following script shows that they should still work as expected. Can you edit it to replicate what you're seeing?

### 7100.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7100';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };
const hooks = [];

const schema = new Schema({
  name: String
});

schema.post('save', function() {
  hooks.push('save');
});

schema.post('remove', function () {
  hooks.push('remove');
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.1');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  await doc.remove();
  assert.deepStrictEqual(hooks, ['save', 'remove']);
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```
### Output:
```
issues: ./7100.js
All Assertions Pass.
issues:
```

**Comment by JeremieTouze** [comment]
Same issue there. Since I updated from mongoose 5.2.12 to 5.3.2  yesterday none of my ".pre" middleware are not triggered (without any error catched). I went back to 5.2.12 and it works again.

**Comment by lineus** [comment]
@JeremieTouze can you create a reproducible example ( or edit mine above ) to demonstrate the behavior you're seeing? I haven't been able to reproduce this yet.

**Comment by JeremieTouze** [comment]
@lineus just did a simple script with mongoose 5.3.2 and the middleware work fine. As soon as I have time, I'll build upon this script to meet to same "non triggered middleware issue", and hopefully figure out where the problem is.

**Comment by JeremieTouze** [comment]
@lineus  Okay I figured out what was wrong ! This issue has been described before [https://github.com/Automattic/mongoose/issues/4955](url). Middleware must be defined before calling mongoose.model . However I don't understand why with mongoose 5.2.12, middleware were called even if declared after mongoose.model call. 
Please let me know if you would like to see the scripts (the issue version and the fixed version).
Thanks for minding about this issue !
