### ISSUE TITLE
Associated document session isn't propagated to its subdocuments

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#7104]
Transaction that's associated with a doc isn't propagated to its subdocuments:

```js
const [doc] = await Model.create([{
  someData: 'asd'
}], {associatedSession});

// doc.$session() correctly returns associatedSession

doc.arrayOfSubDocs.push({
  someData: 123
});

// doc.arrayOfSubDocs[0].$session() returns null
```

**Comment by lineus** [comment]
@sebastian-nowak I don't have a lot of meaningful experience with sessions yet. What impact does this have on you?

**Comment by sebastian-nowak** [comment]
It's causing a lot of a trouble. JavaScript has no reasonable way of creating an execution context, the only existing API that was available in node.js was deprecated a while ago. The only way to implement transactions in JS is to pass along the transaction handle manually, which gets incredibly hard in complex systems. All methods have to be transaction aware.

Mongoose implemented a nice approach, it's possible to associate a transaction with a document instance using `doc.$session(handle)` and it'll automatically use the handle for all `doc` related queries. It allows writing custom schema methods that simply retrieve the current handle using `this.$session()` and then they pass it along. It works nicely, but unfortunately breaks for subdocs as described in the first post.

It's even more confusing when you create a document using mongoose from within transaction. Its handle is associated with the doc automatically, but it's not available from subdocs.

CC @vkarpov15 (I think you originally added the `$session()` helper)

**Comment by vkarpov15** [comment]
Thanks for reporting @sebastian-nowak , you're exactly right about this. We'll make it so that `$session` propagates down to all child docs.

**Comment by sebastian-nowak** [comment]
Hey @vkarpov15,

I just updated to the latest version (5.3.6) and the issue from the first post still occurs.  I think that the session handle is still not propagated on `push()`, it only works when the subdoc was there from the start and session handle was set later.

Cheers,
Sebastian

**Comment by vkarpov15** [comment]
@sebastian-nowak good call, thanks :+1:
