### ISSUE TITLE
Question: is it possible to use a match query when populating a refPath field?

### ISSUE THREAD

**Issue by aletorrado** [Automattic/mongoose#7112]
Hi, as I recently stated in #7070 I use refPath in some cases, and need to filter the results with a match query.

I think it's not possible at the moment. Can someone please confirm me if this is true?

**Comment by salmanahmad94** [comment]
@aletorrado it's not working  as of mongoose 5.8.1. I'm using a fairly complex query including the $and, $or operators and the refPath field is not populating.

**Comment by vkarpov15** [comment]
@salmanahmad94 please open up a new issue and follow the issue template.
