### ISSUE TITLE
use aggregate.count() and return collection (array object).

### ISSUE THREAD

**Issue by samtsai15** [Automattic/mongoose#7114]
MongoDB : 3.4
Mongoose : 5.1.6 

Hi , I use count with aggregate and return array object. example: 

```
const aggregateForCount = example.aggregate();
aggregateForCount.match({});
let count = (await aggregateForCount.count('count').exec());
```
and it return : 

```
[ { count: x } ]
```
 
According to MongoDB Docs.
https://docs.mongodb.com/v3.4/reference/operator/aggregation/count/

It should be return object only.  
So it will be fix or not ?

Thanks.

**Comment by lineus** [comment]
@samtsai15 Mongoose, as well as the underlying Mongodb Native Driver, either return an AggregationCursor or an array ( the default in mongoose ) from calls to aggregate. The example in the docs you linked to is from the mongo shell, whose behavior can differ from other drivers/libraries.  

@vkarpov15 In future versions of mongoose, would it be a good idea to detect when `$count` is the last stage in a pipeline and return the resulting object sans the array? Or maybe add an option to do this?

**Comment by vkarpov15** [comment]
@lineus that's an interesting idea, but I don't think it offers enough benefit to justify breaking consistency with the MongoDB API.

The MongoDB docs you linked to are misleading in their use of the term 'return'. When you `aggregate()` with `$count` in the mongo shell, you actually get back a cursor (see below). The reason why it shows up as a single doc in the output is that's how the mongo shell handles rendering a cursor. We'll add a PR to the mongodb docs to improve the wording.

```
rs:PRIMARY> res = db.test.aggregate([{ $count: 'sum' }])
{ "sum" : 2 }
rs:PRIMARY> Object.keys(res)
[
	"_batch",
	"_useReadCommands",
	"_cursorid",
	"_batchSize",
	"_maxAwaitTimeMS",
	"_ns",
	"_db",
	"_collName",
	"_cursorHandle"
]
rs:PRIMARY> 
```
