### ISSUE TITLE
BUG: {new: true} on the create method returns unexpected results

### ISSUE THREAD

**Issue by tomanagle** [Automattic/mongoose#7116]
**What is the current behavior?**
When you give the create method a settings object that contains {new: true}, it will create your given object and an object with just default fields populated, all packed up into an array.

Here is a create method with the {new: true} option. 
```
 const newConversation = await Conversation.create({
      users: [user._id, connectionRequest.from],
      messages: [],
      lastMessage: new Date()
    }, {new: true})
    .then((data) => {
      return data;
    }).catch((error) => {
      throw error;
    });
```

```{ newConversation:
   [ { users: [Array],
       messages: [],
       _id: 5bbcb96b5ced9d7b248f5139,
       lastMessage: 2018-10-09T14:21:31.967Z,
       updatedAt: 2018-10-09T14:21:31.980Z,
       createdAt: 2018-10-09T14:21:31.980Z,
       __v: 0 },
     { users: [],
       messages: [],
       _id: 5bbcb96b5ced9d7b248f513a,
       updatedAt: 2018-10-09T14:21:31.980Z,
       createdAt: 2018-10-09T14:21:31.980Z,
       __v: 0 } ] }
```

**What is the expected behavior?**
The create method should either:
1) Ignore the new option and return a single object as expected, or
2) Throw an error telling the user that this option is not valid for the create method

**Please mention your node.js, mongoose and MongoDB version.**
mongoose 5.3.2
node.js 8.11.1

**Comment by brodeynewman** [comment]
I'd like to hop on this if this is a confirmed bug?

**Comment by vkarpov15** [comment]
Not a bug. If you want the 2nd arg to create to be treated as an options object, you need to pass an array as the first arg. Use `Conversation.create([doc], { new: true })` . Also, why are you passing a `new` option to create? See create docs: https://mongoosejs.com/docs/api.html#model_Model.create
