### ISSUE TITLE
pre/post query hooks return a different query

### ISSUE THREAD

**Issue by israelidanny** [Automattic/mongoose#7118]
**Do you want to request a *feature* or report a *bug*?**
reporting a bug

**What is the current behavior?**
Currently, a "pre" and a "post" query hook will return a different result for `this.getQuery()`. For example, mongoose usually converts "true" strings into boolean trues, as well as document objects into `_id` ObjectId fields.

**What is the expected behavior?**
pre/post queries shouldn't be different, or at the very least a "pre" hook should have access to the "processed" query as it appears in "post". Otherwise it is very hard to implement caching middlewares (which is my use case).

**Please mention your node.js, mongoose and MongoDB version.**
mongoose v5.2.5
node v8.11.4

**Comment by vkarpov15** [comment]
This is a very good point. Mongoose 5 defers casting the query conditions until all middleware is done, which makes it easy to modify the query in middleware in a predictable way, but hard to get the actual query going to the server. We will add a function that explicitly casts the query conditions.

**Comment by vkarpov15** [comment]
Turns out we already have a function for this: [`Query.prototype.cast`](https://mongoosejs.com/docs/api.html#query_Query-cast).

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7118`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ test: Boolean });

  schema.pre('find', function() {
    this.cast(this.model);
    console.log(this.getQuery()); // `test` will be a boolean
  });

  const M = mongoose.model('Test', schema);

  await M.find({ test: 'true' });
}
```
