### ISSUE TITLE
 Mixed schema type without assigning any property name(key )

### ISSUE THREAD

**Issue by darshanan24** [Automattic/mongoose#7128]
can i know how to use Mixed schema type without assigning any property name(key )?
for example: This  is a valid mongoose schema:

> const mongoose = require('mongoose');
> 
> const cubeSchema = mongoose.Schema({
>     _id:mongoose.Schema.Types.ObjectId,
>     cube: {type:mongoose.Schema.Types.Mixed, required:true}
> })
> 
> module.exports= mongoose.model("Cube", cubeSchema);

the output for above code is: // just taking some random json

```
 {
        "cube": {
            "name": "JdbcSourcennector",
            "configuration": {
                "connector.class": " io.confluent.connect.jdbc.JdbcSourceConnector",
                "tasks.max": "1",
              }
        },
        "_id": "5bc06f086e25d246029de1de"
    }
```

But i would like to Post the data and get the data without propertyname(key).
for example something like this:

> const mongoose = require('mongoose');
> 
> const cubeSchema = mongoose.Schema({
>     {type:mongoose.Schema.Types.Mixed, required:true}
> })
> 
> module.exports= mongoose.model("Cube", cubeSchema);

Expected output: 
// without the cube(key name)
{
            "name": "JdbcSourcennector",
            "configuration": {
                "connector.class": " io.confluent.connect.jdbc.JdbcSourceConnector",
                "tasks.max": "1",
              }
}

Is there any way available for the way i mentioned above? Thanks

_Originally posted by @darshanan24 in https://github.com/Automattic/mongoose/issue_comments#issuecomment-429311873_

**Comment by vkarpov15** [comment]
I answered in https://github.com/Automattic/mongoose/issues/4614#issuecomment-430002218
