### ISSUE TITLE
please writing source code in ecmascript 2015+ syntaxs, ok?

### ISSUE THREAD

**Issue by anlexN** [Automattic/mongoose#7130]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
very boring
**What is the expected behavior?**
mordern syntaxs
**Please mention your node.js, mongoose and MongoDB version.**
latest

i reviews mongoose source code that is written by older javascript, it' s very verbose and boring

**Comment by nik72619c** [comment]
what type of changes are expected here ... kindly describe? willing to work on this one.
