### ISSUE TITLE
pre update(One) - no way to change anything?

### ISSUE THREAD

**Issue by YuriGor** [Automattic/mongoose#7133]
Is there any way to do something useful in the update hook?
`this` is just global or even undefined when setting hook from mongoose plugin.
Nothing useful is passed into hook callback as arguments.
I Expected to have a query object or modifier object parameter.

(K)Ubuntu 18.04
Node v10.7.0
mongodb 3.6.3
mongoose v5.3.3

https://gist.github.com/YuriGor/cc8114a0d0b1ad151eaf58baab24aa3a

regex hook name and options object parameter look like not working.

**Comment by YuriGor** [comment]
Shame on me, it was not a good idea to use arrow functions as pre callbacks.

**Comment by YuriGor** [comment]
Okay, regex works on latest version of mongoose, 
but `options.document/query` parameter looks like ignored.
no matter how do I set this flags, hook always runs.

**Comment by vkarpov15** [comment]
Right now we don't support hooking `doc.updateOne()`, we only support hooking the functions listed on the [middleware docs](https://mongoosejs.com/docs/middleware.html). In particular, the document/query parameter only affects `remove()`. We'll add hooks for `doc.updateOne()` in a future release.
