### ISSUE TITLE
How to get document _id in pre updateOne hook?

### ISSUE THREAD

**Issue by YuriGor** [Automattic/mongoose#7134]
I do updateOne for my model and have pre updateOne hook on my scheme like this:
```javascript
    const schema = new mongoose.Schema({ name: { type: String } });
    schema.pre('updateOne', async function() {
      fs.writeFileSync('./query.json', stringify(this, null, 2), 'utf-8');
    });
    const Model = mongoose.model('Model', schema);
    let res = await Model.create({
      name: "I'll be updated soon",
    });
    console.log(res.name, res._id);
    await Model.updateOne(
      ({ _id: res._id }, { $set: { name: 'I was updated!' } }),
    );
```
But I cant find any way to get currently updating document's id
Here is a working test script:
https://gist.github.com/YuriGor/04192230fb63542c1af5ff5c19b3a724

Note: in real life this will happen inside mongoose plugin, so I cant just save doc _id to some variable in parent scope, as I do in this script.

**Comment by vkarpov15** [comment]
```javascript
schema.pre('updateOne', async function() {
  console.log(this.getQuery()._id);
});
```

Does that help?

**Comment by vkarpov15** [comment]
See https://mongoosejs.com/docs/api.html#query_Query-getQuery

**Comment by YuriGor** [comment]
Hi Valery, thank you for reply!
`this.getQuery()` returns empty object `{}`
I believe `this` is already pointing to query object, but there is no _id inside.
The most relevant i found inside this is
```javascript
..
 "op": "updateOne",
  "options": {},
  "_conditions": {},
  "_update": {
    "$set": {
      "name": "I was updated!"
    }
  },
..
```
but _conditions is empty too.

**Comment by vkarpov15** [comment]
What does your query look like? If _id is in your query, you can get the id with getQuery. If _id isn't in the query, you unfortunately can't get it unless you execute an extra query.

**Comment by YuriGor** [comment]
Please take a look at first comment here
```javascript
await Model.updateOne(
  ({ _id: res._id }, { $set: { name: 'I was updated!' } }),
);
```
it is my updateOne query.

**Comment by YuriGor** [comment]
also at first comment I provided link to gist. There are full version of the script and query object(this) exported as JSON file.

**Comment by santhosh77h** [comment]
No need of using $set in update it seems.
https://stackoverflow.com/questions/14199529/mongoose-find-modify-save

>

**Comment by YuriGor** [comment]
AFAIK mongoose will wrap it into $set anyway, so there is no difference.
I tried both ways.
I think this is a bug. 
`this._conditions` should be filled with update search criteria described in first parameter of updateOne method, but it's empty.

**Comment by vkarpov15** [comment]
Thanks for your patience @YuriGor , I repro-ed the issue locally and will fix ASAP.

**Comment by YuriGor** [comment]
Thank you!
Also please check `update` and `updateMany` - this methods has absolutely the same bug.

**Comment by vkarpov15** [comment]
@YuriGor I found the issue, it isn't a bug in Mongoose, it is a weird syntactic quirk in your code:

```javascript
await Model.updateOne(
      ({ _id: res._id }, { $set: { name: 'I was updated!' } }),
    );
```

In JavaScript `(1, 2) === 2`, so those extra params mean the above is equivalent to `await Model.updateOne({ $set: { name: 'I was updated!' } })`. I can confirm the below update works as expected:

```javascript
await Model.updateOne({ _id: res._id }, { $set: { name: 'I was updated!' } });
```

**Comment by YuriGor** [comment]
Thank you a lot and sorry for wasting your time. 
Looks like I copy-pasted arguments from some manual with parentheses, and prettier made it multiline, so it's become difficult to detect.
