### ISSUE TITLE
Array validation doesn't occur with $set but does with $push during an updateOne operation

### ISSUE THREAD

**Issue by asafch** [Automattic/mongoose#7135]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
When attempting to update a document's property, which is an array, during an `updateOne` operation and turning on validation with the `{runValidators: true}` option, the array isn't validated when it's updated with the `$set` operator, but it does get validated when using the `$push` operator.
The reason for using a `$set` operator is to add new elements in the _head_ of the array (index 0) rather than its tail, via application code. However, it is more important for me to have validation than to insist on a specific array structure.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const bluebird = require("bluebird");
const mongoose = require("mongoose");
mongoose.set("debug", true);
mongoose.Promise = bluebird.Promise;

(async () => {
	try {
		const db = mongoose.createConnection("mongodb://localhost/test_db");
		const ElementSchema = mongoose.Schema({
			a: { type: String, required: true },
			b: {
				c: {type: String, required: true}
			}
		}, { _id: false });
		const ArraySchema = mongoose.Schema({
			anArray: [ElementSchema]
		});


		const TestModel = db.model("ArraySchema", ArraySchema, "test_collection");
		const document = TestModel({})

		await document.save();

		const fetchedDocument1 = (await TestModel.find({}))[0];

		console.log(fetchedDocument1);

		const setResult1 = await TestModel.updateOne({_id: fetchedDocument1._id}, {
			$set: {
				anArray: [{}]
			}
		},
		{ runValidators: true });

		// I expect the validation to prohibit saving the document due to an empty object inside the array

		console.log(setResult1);

		const setResult2 = await TestModel.updateOne({_id: fetchedDocument1._id}, {
			$push: {
				anArray: {
					a: "hello",
					b: {
						c: "world"
					}
				}
			}
		},
		{ runValidators: true });

		// I expect the validation to pass because the element conforms to the schema

		console.log(setResult2);
	} catch (err) {
		console.log(err);
	}
})();

```
**What is the expected behavior?**
- The update operation result stored in `setResult1` should report an error, not a success, due to adding an empty element to the array.

**Please mention your node.js, mongoose and MongoDB version.**
Node - `10.0.0`
MongoDB - `3.4.14`
mongoose - `5.0.5`

**Comment by asafch** [comment]
Please note that this is not the same issue as described in #6102.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP

**Comment by asafch** [comment]
@vkarpov15 I haven't tested this bug in `update` and `updateMany` operations to see if it exists there as well - I think it would be prudent to do so.

**Comment by lineus** [comment]
@vkarpov15 Is this expected? 

The offending `$set` operation doesn't have any paths defined and [update validators only run on updated paths](https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths):
```
  $set: {
    anArray: [{}] 
  }
```
