### ISSUE TITLE
Mongoose + Aggregate : Date Casting issue

### ISSUE THREAD

**Issue by pankajs-iprogrammer** [Automattic/mongoose#7140]
I'm new to mongoose, please guide me if I'm doing anything wrong here..

When I perform following query in mongo, its working fine :

```
db.getCollection('patients').aggregate({
    "$match": {
    "demographics.dob": new Date("2018-01-17T00:00:00.000Z")
   }
})
```
But when I remove new Date(), its not working.

```
db.getCollection('patients').aggregate({
    "$match": {
    "demographics.dob": "2018-01-17T00:00:00.000Z"
   }
})
```
Now why I want to remove this is because when I'm trying to send date, its going in string format, following is my code :

 `filter["demographics.dob"] = new Date(filter["demographics.dob"]).toISOString();`

I know that in aggregate, type casting is not done internally so please suggest me the way to do it in other way :)

Following is the result of mongoose debug log:

    ```
patients.aggregate([
    {
        "$project": {
        "demographics.legalFirstName": "$demographics.legalFirstName",
        "demographics.lastName": "$demographics.lastName",
        "updatedAt": "$updatedAt",
        "_id": 1
        }
    },
    {
        "$match": {
        "$and": [
            {
            "demographics.dob": "2018-01-17T00:00:00.000Z"
            }
        ]
        }
    },
    {
        "$sort": {
        "updatedAt": -1
        }
    },
    {
        "$skip": 0
    },
    {
        "$limit": 2
    }
    ],
    , {}
    )
```

**Comment by vkarpov15** [comment]
Why don't you just do `filter["demographics.dob"] = new Date(filter["demographics.dob"])`? If you want to match by a date, you should put a native JS date in your `$match`.

**Comment by pankajs-iprogrammer** [comment]
@vkarpov15 : I tried that too but it was also not working as It returns date in "Thu Oct 18 2018 12:07:34 GMT+0530 (India Standard Time)" format where I'm storing date in  ISO String format i.e "2018-10-18T06:38:01.709Z"

**Comment by pankajs-iprogrammer** [comment]
@vkarpov15 : I found the solution, it started working when I did following change : 

```
{
  "$match": {
    "$expr": {
      "$eq": [
        "$demographics.dob",
        {
          "$dateFromString": {
            "dateString": "2018-01-17T00:00:00.000Z"
          }
        }
      ]
    }
  }
}
```

**Comment by vkarpov15** [comment]
That works. Although you shouldn't need to do that, you should be able to just pass in a native JS date object.
