### ISSUE TITLE
How to define a custom query helper with typescript?

### ISSUE THREAD

**Issue by baterson** [Automattic/mongoose#7141]
Hello! I want to define custom query helper using  [query helper api][1] . 
Here the example:

    // models/article.ts

    import { Document, Schema, Model, model } from 'mongoose';
  
    interface IArticle extends Document {
	   name: string;
    }

    interface IArticleModel extends Model<IArticle> {
	   someStaticMethod(): Promise<any>;
    }

    const ArticleSchema = new Schema( { name: String } )
 
    ArticleSchema.query.byName = function(name) {
        return this.find({ name })
    }

    export default model<IArticle, IArticleModel>('Article', ArticleSchema);

    // routes/article.ts
    import ArticleModel from '../models/article.ts'
     
    router.get('/articles, (req, res) => {
        ArticleModel.find().byName('example')
    })

Typescript complains about `byName` method when I chain it with defaults.  
I can put it in `IArticleModel` interface but in that case I could only call it from model.   
Where should I put the definition of this method to use it in chainable way?

  [1]: https://mongoosejs.com/docs/guide.html#query-helpers

**Comment by lineus** [comment]
@baterson check out [this issue in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23132) that directly relates to your question. It looks like it's been open for a while, you might add a comment there to help get some traction on it. 

Mongoose doesn't provide support for the typescript definitions, and from what I can tell, the current type definitions maintained by DefinitelyTyped don't support custom query methods.
