### ISSUE TITLE
$pull operator doesn't work with dot notation

### ISSUE THREAD

**Issue by rvaz55** [Automattic/mongoose#7147]
-Reporting a bug
-Version I'm using: "mongoose": "^5.0.17"

**What is the current behavior?**
I'm trying to delete a sub-document the way that is specified in the documentation but I keep getting an error that says  

**What is the expected behavior?**
Delete the 'jerk spices' subdocument by using its 'itemID'

    code: 28
    codeName: "PathNotViable"
    errmsg: "Cannot use the part (itemID) of (stockedItems.itemID) to traverse the element ({stockedItems: [ { itemName: \"jerk spices\", price: 3, category: \"Condiment\", itemID:  ObjectId('5bc8c1ffe08e8720dffec07e') }, { itemName: \"qw\", price: 1, category: \"Herbal\", itemID: ObjectId('5bc8c380b68351222654b1b5') } ]})"

    name: "MongoError"
    ok: 0'

**The error I get after clicking the 'x' to delete an entry'**
![storeinventorybrowser](https://user-images.githubusercontent.com/34892816/47174942-a56d3780-d2d7-11e8-960f-601a4c49acf6.png)

**This is my schema setup**
![schemastores](https://user-images.githubusercontent.com/34892816/47174949-ab631880-d2d7-11e8-8234-b2950982e51f.png)

**Comment by lineus** [comment]
@rvaz55 As far as I can tell, the `$pull` operator doesn't accept dot notation ( e.g. stockedItems.itemID' ). I tested it out in the mongo shell and got the same error. Your update doc syntax should look more like `{ $pull: { stockedItems: { itemId: req.params.itemId } } }`

Here's  a contrived example:

### 7147.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '7147';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = {};

const schema = new Schema({
  arr: [{
    _id: false,
    a: String,
    b: String
  }]
});

const Test = mongoose.model('test', schema);

const test = new Test({
  arr: [
    { a: 'one', b: 'one' },
    { a: 'two', b: 'two' }
  ]
});

async function run() {
  assert.equal(mongoose.version, '5.0.17');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);

  // const fails = { $pull: { 'arr.a': 'one' } };
  const works = { $pull: { arr: { a: 'one' } } };
  const opts = { new: true };
  const updated = await Test.findByIdAndUpdate(test._id, works, opts);
  assert.deepStrictEqual(updated.toObject().arr, [{ a: 'two', b: 'two' }]);

  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e);
  return connection.close();
}
```
### Output:
```
issues: ./7147.js
All Assertions Pass.
issues:
```
