### ISSUE TITLE
Unit test failed when using mongoose.Types.ObjectId() in aggregate()

### ISSUE THREAD

**Issue by slim-hmidi** [Automattic/mongoose#7149]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug.
**What is the current behavior?**
I wrote a query that filter a list of tasks and returns an array:
```js
const filteredTasks = await this.model.aggregate([])
        .match({ statusId: native.Types.ObjectId(statusId) })
        .project({
          name: 1,
          taskTypeId: 1,
          start: 1,
          end: 1,
          duration: 1,
          statusId: 1,
          position: { $arrayElemAt: [{ $map: {
            input: {
              $filter: {
                input: '$attributes',
                as: 'attribute',
                cond: { $eq: ['$$attribute.attributeTypeId', native.Types.ObjectId(attributeTypeId)] },
              },
            },
            as: 'attributeType',
            in: '$$attributeType.value',

          } }, 0] },
        });
```
The query works well when I test it with postman.
I tried to write unit testfor the api containing this query using jest, when I run the api and I give such inputs `statusId` and `attributeTypeId`, the query doesn't work .

I verified the type of input values in both (when testing with postman and mocha test) and it is of type `string`.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I want to get an array contained the list tasks.
**Please mention your node.js, mongoose and MongoDB version.**
Node.js: 8.12.0
MongoDB: 4.0.2

**Comment by lineus** [comment]
@slim-hmidi is `entityTypeId` the same type **(e.g. typeof entityTypeId === 'string')** in both the route that you're testing with postman and the mocha test? *It sounds like you're passing in a string to the api route and an ObjectId to the mocha test.*

**Comment by slim-hmidi** [comment]
@lineus I updated the question and I verify the type of input and they are of same type.
