### ISSUE TITLE
Required validator does not run

### ISSUE THREAD

**Issue by pronebird** [Automattic/mongoose#7151]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

My schema:

```js
const WatSchema = new mongoose.Schema({
  url: {
      type: String,
      required: function(value) {
        return value === null || typeof value === 'string';
      }
    }
});

const Wat = mongoose.model('Wat', WatSchema);

const watwat = await Wat.create({}); // no error
watwat.url // undefined, wat?
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

`Wat.create({})` should fail because `url` is `undefined`

**Please mention your node.js, mongoose and MongoDB version.**

Not sure

**Comment by lineus** [comment]
@pronebird in your example, when the required function is called, `value` is `undefined` which is not strictly equal `===` to `null`, and *obviously isn't a string*. The result is that the required validator is set to false. 

You can test for `undefined` loosely equal to `null` with `==` or strictly test for `undefined`. Here's an example:

### 7151.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = 'test';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const WatSchema = new Schema({
  url: {
    type: String,
    required: function (value) {
      // return value === undefined || typeof value === 'string'; // works too
      return value == null || typeof value === 'string';
    }
  }
});

const Wat = mongoose.model('Wat', WatSchema);

async function run() {
  assert.strictEqual(mongoose.version, '5.3.4');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  let error;
  await Wat.create({}).catch(e => error = e);
  assert.ok(error instanceof Error);
  console.log('All Assertions Pass.');
  return connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  return connection.close();
}
```
### Output:
```
issues: ./7151.js
All Assertions Pass.
issues:
```

**Comment by lineus** [comment]
yes, the `required` schemaType option as a custom function can conditionally disable/enable whether or not the specified path is required as opposed to the `validate` schemaType option which allows you to specify a function to actually validate a field. It allows us a great deal of flexibility in our schema design. Rather than have a binary choice between required or not required, we can have path that is required only if certain other conditions are met.
