### ISSUE TITLE
Im having a deprecation warning upon connecting to mongodb via cloud.. 

### ISSUE THREAD

**Issue by reanraynera** [Automattic/mongoose#7154]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by lineus** [comment]
@reanraynera There is a [guide here](https://mongoosejs.com/docs/deprecations.html) for handling the various deprecation warnings from the native driver. You can also find [previously closed issues here](https://github.com/Automattic/mongoose/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+deprecation+in%3Atitle) for more details.
