### ISSUE TITLE
Plugin: Luxon type

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#7156]
Re: #5110

**Comment by Uzlopak** [comment]
Moment.js is deprecated.
https://momentjs.com/docs/#/-project-status/

So we should not implement a moment type anymore.

**Comment by adamreisnz** [comment]
Agreed! A Luxon DateTime type might be a good alternative though.

**Comment by rkreienbuehl** [comment]
Is it anyhow possible to set a default getter for Date type like ist is possible for ObjectId?
`mongoose.Schema.Types.ObjectId.get((v) => (v ? v.toString() : undefined));`
With Date this doesn't work. If this would be possible, there would be no need for a Luxon DateTime plugin.

**Comment by vkarpov15** [comment]
@rkreienbuehl  Yeah there is. `mongoose.Schema.Types.Date.get((v) => DateTime.fromJSDate(v));` should work.

**Comment by rkreienbuehl** [comment]
@vkarpov15 Thanks for your answer. I tried it like this before, but when I do this, I get the following error:
```ts
TypeError: mongoose_1.default.Schema.Types.Date.get is not a function
```

**Comment by rkreienbuehl** [comment]
@vkarpov15 Tested it right now. I had `v7.0.3` and now I updated to `v7.1.1`, but still have this error.

**Comment by vkarpov15** [comment]
@rkreienbuehl oops, it looks like some of our schematypes don't have a `.get()` function. We'll add that for a future minor release.

In the meantime, you can do the following:

```javascript
'use strict';

const mongoose = require('mongoose');
const {DateTime} = require('luxon');

mongoose.SchemaType.get.call(mongoose.Date, (v) => DateTime.fromJSDate(v));

const Test = mongoose.model('Test', mongoose.Schema({ date: Date }));
const doc = new Test({ date: new Date() });
console.log(doc.date instanceof DateTime); // true
```

**Comment by rkreienbuehl** [comment]
> 

@vkarpov15 Thanks for your workaround. Had to use `mongoose.SchemaType.get.call(mongoose.Schema.Types.Date, (v) => DateTime.fromJSDate(v));` instead of `mongoose.SchemaType.get.call(mongoose.Date, (v) => DateTime.fromJSDate(v));` for TypeScript, but then it works perfectly.
