### ISSUE TITLE
Custom Types does not work anymore for custom mongoose connection

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#7158]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Since 5.3.2 I can't use custom types, nor by class neither by function for my custom mongoose instance (fix(mongoose): isolate Schema.Types between custom Mongoose instances #6933)
**If the current behavior is a bug, please provide the steps to reproduce.**

"use strict";
const mongoose = require("mongoose");
const assert = require("assert");
const db = new mongoose.Mongoose();
const {Schema} = db;
db.connect("mongodb://localhost/test").then(()=>{
    function Int8(key, options) {
        db.SchemaType.call(this, key, options, "Int8");
    }
    Int8.prototype = Object.create(db.SchemaType.prototype);

    // `cast()` takes a parameter that can be anything. You need to
    // validate the provided `val` and throw a `CastError` if you
    // can't convert it.
    Int8.prototype.cast = function(val) {
        var _val = Number(val);
        if (isNaN(_val)) {
	    throw new Error("Int8: " + val + " is not a number");
        }
        _val = Math.round(_val);
        if (_val < -0x80 || _val > 0x7F) {
	    throw new Error("Int8: " + val +
		" is outside of the range of valid 8-bit ints");
        }
        return _val;
    };

    // Don't forget to add `Int8` to the type registry
    db.Schema.Types.Int8 = Int8;

    var testSchema = new Schema({ test: Int8 });
    var Test = db.model("CustomTypeExample", testSchema);

    var t = new Test();
    t.test = "abc";
    console.log(t.validateSync());
    assert.equal(1,1);
    assert.ok(t.validateSync());
    assert.equal(t.validateSync().errors["test"].name, "CastError");
    assert.equal(t.validateSync().errors["test"].message,
        "Cast to Int8 failed for value \"abc\" at path \"test\"");
    assert.equal(t.validateSync().errors["test"].reason.message,
        "Int8: abc is not a number");
});

**What is the expected behavior?**
It does not work with "Int8" nor Int8 as type, my custom types are built around this example, so if this doesn't work neither my code.
**Please mention your node.js, mongoose and MongoDB version.**
node 10.12.0
MongoDB shell version v4.0.2
git version: fc1573ba18aee42f97a3bb13b67af7d837826b47
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: debian92
    distarch: x86_64
    target_arch: x86_64
mongoose since 5.3.2

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap

**Comment by chumager** [comment]
Thanks a lot, it worked...
