### ISSUE TITLE
Find document with Select statement doesn't populate the default values

### ISSUE THREAD

**Issue by yyosifov** [Automattic/mongoose#7159]
BUG

**What is the current behavior?**

We're migrating mongoose from `4.3.0` to `5.3.4` in our project and we hit a breaking change, which our system doesn't expect.

If you have a nested document with a property with default value, and in the DB the document doesn't have this property set - the default value is not populated when `find/findOne` the document from the DB with a `select` statement. If you don't use a `select` statement, it works as expected and the property is populated with the default value.

The case is for documents, which are stored already without the `default` values and the `default` value is added to the schema at a later stage.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've used as a base the `model.field.selection.test.js` file and changed it to isolate and reproduce the case:

```
before(function () {
    const CalendarSchema = new Schema({
      dateFormat: {
        type: String,
        default: 'dd/MM/yyyy'
      },
      culture: {
        type: String,
        default: 'en-gb'
      }
    }, {
      _id: false,
      minimize: false
    });
    modelName = 'CalendarSchema';

    const SettingsSchema = new Schema({
      calendar: {
        type: CalendarSchema,
        default: {}
      }
    }, {
      _id: false,
      minimize: false
    });

    modelName = 'SettingsSchema';
    mongoose.model(modelName, SettingsSchema);

    BlogPostB = new Schema({
      title: String,
      author: String,
      settings: {
        type: SettingsSchema,
        default: {}
      }
    }, { minimize: false });

    modelName = 'model.select.blogpost';
    mongoose.model(modelName, BlogPostB);
    collection = 'blogposts_' + random();
    db = start();
  });

  after(function (done) {
    db.close(done);
  });

it.only('excluded fields should be undefined', async function (done) {
    const BlogPostB = db.model(modelName, collection);

    const doc = {
      title: 'subset 1',
      author: 'me',
      settings: {
        calendar: {
          dateFormat: '1234'
        }
      }
    };

    const query = {
      author: 'me'
    };
    await BlogPostB.create(doc);

    await BlogPostB.update(
      query, {
        $unset: {
          'settings.calendar.culture': ""
        }
      }
    );
    const withoutSelect = await BlogPostB.findOne(query).exec();
    const withSelect = await BlogPostB.findOne(query).select('settings title').exec();

    assert.strictEqual('en-gb', withoutSelect.settings.calendar.culture);
    assert.strictEqual('1234', withoutSelect.settings.calendar.dateFormat);
    assert.strictEqual('1234', withSelect.settings.calendar.dateFormat);
    assert.strictEqual('en-gb', withSelect.settings.calendar.culture);

    done();
  });
```

I am `unsetting` the `settings.calendar.culture` because when you save the document, the default value is persisted and I want to setup a Document which doesn't have the field set (like when you have existing documents saved and you add a new property with default value to the schema).

Without the `select` statement it works and is populated as expected, with the `select` statement it doesn't populate the default value.

**What is the expected behavior?**

In both cases the `settings.calendar.culture` should be set the default value `en-gb`.

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v8.9.3
mongoose: tested in 5.3.5-pre and 5.3.4
MongoDB: 3.4.10

**Comment by vkarpov15** [comment]
Thanks for the detailed report, will investigate asap

**Comment by yyosifov** [comment]
@vkarpov15 thanks for the fast fix! We've already updated our version and it works as expected now.
