### ISSUE TITLE
Bug in Updating multiple model (Number)

### ISSUE THREAD

**Issue by kevinhimawan** [Automattic/mongoose#7163]
Hello, i have a problem in updating multiple model in mongoose

Here is the steps
1. We got labels id from client (Process printing label)
2. Find all labels and reduce to get total Quantity of all labels
 *Each labels has different Quantity
3. Update Section (a.k.a Product) quantity ++
4. Update Order item totalProduction quantity ++
5. Update Label print repition ++1

**Step 1**
for (let i = 0; i < req.body.labels.length; i++) {
    req.body.labels[i] = ObjectId(req.body.labels[i])
  }
let findAllLabels = await Label.aggregate([
      {'$match': {
        '_id': {'$in' : req.body.labels},
        'printStatus': false
        }
      }
    ])

**Step 2**
let total = findAllLabels.reduce((acc, curr) => {
        acc += curr.quantity
        return acc
      },0)

**Step 3**
let sectionDB = await Section.findOne({ '_id': req.body.sectionid })
    sectionDB.quantity += Number(total)
    await Section.update (
      {'_id': sectionDB._id},
      { "$set": sectionDB }
    )

**Step 4**
    const sectionIn = await SectionIn.findOne({'_id': req.params.sectioninid})
    let oiDB = await OrderItem.findOne({ "_id": sectionIn.orderItem })
    oiDB.productionQuantity += Number(total)
    await OrderItem.update(
      { "_id": oiDB._id },
      { "$set": oiDB }
    )

**Step 5**
await Label.update(
      {"_id": {$in: req.body.labels}},
      {"$set": { printStatus: true, is_used: true },
     "$inc": {
       printRepitition: 1
     }}
    { multi: true }
   )

Let say from step 2 the total quantity from 8 Labels is 16pcs of products, Section will update quantity ++16, however in OrderItem sometimes updating totalProductionQuantity not same ++16 (Ratio 1:10) in ten printing process one will occured this bug (updating different quantity from total quantity in Step 2)

However when it goes into step 5, all Labels 8 always updated perfectly, all 8 Labels print repitition update ++1

**Notes**
1. We use $inc in the first place, but result same,
2. We change use $set, but still same

Please, you guys have any advice? 
Thank you,
Kevin

**Comment by vkarpov15** [comment]
This looks like a race condition in your code. Is it possible that you have 2 instances of this logic running at the same time or is it guaranteed to only run one at a time?

**Comment by kevinhimawan** [comment]
No, we only have one instances in this logic, however now we change the process Step 4 then Step 3. It has been 9 days seems there is no problem at it. Changing step 4 and 3 suppose does not change value quantity of all labels

**Comment by kevinhimawan** [comment]
All incrementing problem is already solved, thank you. So far mongoose didn't have any incrementing issues

Thank you
