### ISSUE TITLE
mongoNetwork error when using replicaSet option in connecting

### ISSUE THREAD

**Issue by amiiy** [Automattic/mongoose#7165]
when connecting to another host MongoDB from application I used:
```

try {
  mongoose
    .connect(
      connectionString,
      { connectTimeoutMS: 4000, useNewUrlParser: true, replicaSet },
    )
    .then(() => mongoose.connection.db.admin().command({ setFeatureCompatibilityVersion: '4.0' }));
} catch (error) {
  console.log('Mongodb Connection Error');
}
```
now when I want to connect to local database its fine and connect well. but when `connectionsString` changed to `mongodb://172.116.12.8:27017/new` for example it returns some error like below:
```
MongoNetworkError: failed to connect to server [localhost:27019] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27019]
    at Pool.<anonymous> (/home/xxx/Desktop/work/x-project-backend/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/xxx/Desktop/work/x-project-backend/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
```
pay attention to its error log which say cannot connect to port `27019` which is another replica but i said to application to connection `27017` which is master.
i using the latest `mongoose` and `mongodb` with replicaSet option which are in same network.

**Comment by lineus** [comment]
@amiiy are you using docker?

**Comment by amiiy** [comment]
No. I installed MongoDB in Linux system and using `systemclt` for status and start.

**Comment by lineus** [comment]
@amiiy can you connect to your replicaSet with the shell and print out your members and their status? 

Something like:

```
issues: mongo --host localhost --quiet
rs:PRIMARY> rs.status().members.forEach(m => print(m.name, m.state))
127.0.0.1:27017 1
127.0.0.1:27018 2
127.0.0.1:27019 2
rs:PRIMARY>
issues:
```
*This is the output from a local replicaSet on my machine started with [run-rs](https://www.npmjs.com/package/run-rs) running server version 3.6.7*

**Comment by CareerFairPlus** [comment]
I'm seeing a similar error when I provide a connection string with 2 different servers/ports and using the replSet option.  It seems to think I'm connecting to localhost, but the connection string I'm passing in doesn't have localhost in it.

```
/app/node_modules/mongodb/lib/mongo_client.js:794 
           throw err; 
           ^ 
 Error: Error connecting to db: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] 
     at /app/node_modules/connect-mongodb-session/index.js:47:17 
     at err (/app/node_modules/mongodb/lib/utils.js:415:14) 
     at executeCallback (/app/node_modules/mongodb/lib/utils.js:404:25) 
     at /app/node_modules/mongodb/lib/mongo_client.js:271:21 
     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:946:5) 
     at /app/node_modules/mongodb/lib/mongo_client.js:791:11 
     at process._tickCallback (internal/process/next_tick.js:61:11) 
```

Unfortunately, I don't have permissions to run rs.status() from the mongo client:
```
:PRIMARY> rs.status()
{
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { replSetGetStatus: 1.0 }",
	"code" : 13
}
```

Node: v10.11
NPM: v6.4.1
Mongoose: v5.3.8
---
MongoDB Server: v3.0.11 (Compose from Heroku, I can't do anything about the version at this time)

**Comment by lineus** [comment]
@CareerFairPlus can you share your connection string ( with sensitive data redacted )?

**Comment by amiiy** [comment]
@lineus  I connect to mongo in another host: 
`➜ mongo  mongodb://172.16.25.66:27017 `
then I run your query. and it's successful:
```rs0:PRIMARY> rs.status().members.forEach(m => print(m.name, m.state))
localhost:27017 1
localhost:27018 2
localhost:27019 2
```
I think mongoDb itself is ok, but mongoose seem to have problem in connecting to replicaSet.

**Comment by CareerFairPlus** [comment]
> @CareerFairPlus can you share your connection string ( with sensitive data redacted )?

mongodb://[username]:[password]@[server1]:[port1],[server2]:[port2]/[dbName]?replicaSet=[setName]

**Comment by lineus** [comment]
@CareerFairPlus can you try connecting with just the native driver and **the same connection string** and share the results here? ( *example above* ) 

Also, feel free to join us on [Gitter](https://gitter.im/Automattic/mongoose) or [Slack](https://mongoosejsteam.slack.com/).

**Comment by CareerFairPlus** [comment]
@lineus That is what I posted above.  It connected successfully but when attempting to change the db to `gh-7167` is when it errored out with the above error.

**Comment by lineus** [comment]
sorry @CareerFairPlus I guess I needed to refresh before I commented :)

what version of mongoose are you using? Is mongodb from the native example installed separately? if so, what version is it?

Can you adjust the script so that you can safely run it against the database on the server that you **do** have access to. Something like:

```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const { MongoClient } = require('mongodb');

const D = 'YOUR_DB_NAME';
const R = 'YOUR_REPLICA_SET_NAME';
const URI = `mongodb://host1:port1,host2:port2/${D}?replicaSet=${R}`;
const OPTS = { useNewUrlParser: true };

const client = new MongoClient(URI, OPTS);

async function run() {
  await client.connect();
  const db = client.db(D);
  const coll = db.collection('YOUR_COLLECTION_NAME');
  const found = await coll.findOne({});
  console.log('connected succesfully');
  return client.close();
}

run().catch(error);

function error(e) {
  console.error(e.stack);
  process.exit(1);
}
```

**Comment by CareerFairPlus** [comment]
@lineus That example connected successfully:
```
the options [useNewUrlParser] is not supported
connected successfully
```

However, attempting to connect through mongoose still results in the same error referenced above:
https://github.com/Automattic/mongoose/issues/7165#issuecomment-434488818
(see versions in the comment linked above as well)

**Comment by CareerFairPlus** [comment]
@lineus It appears my connection issue is related to `connect-mongodb-session`, not `mongoose`.  Thank you for your help, and sorry for the confusion!!!

**Comment by vkarpov15** [comment]
Also, read up on [this section of our docs on replica set hostnames](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). This issue seems like another issue with mixed-up hostnames in replica sets, it is pretty common. TLDR; connect using the mongo shell and run `rs.conf()`, and make sure the hostnames in `rs.conf()` are the same as the ones in your connection string.

**Comment by TranKimHieu** [comment]
Same issue, solved by below:
use `extra_hosts` instend of `network_mode: host`
env: Macos

```
services:
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo
    restart: always
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
```
