### ISSUE TITLE
query casting attempts to cast comparison operator on nested objects

### ISSUE THREAD

**Issue by lineus** [Automattic/mongoose#7166]
regarding #2901, a comment by @SachinBhandari [here](https://github.com/Automattic/mongoose/issues/2901#issuecomment-431769767)

### Repro Script (2901.js)
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection } = mongoose;
const DB = '2901';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const nestedSchema = new Schema({
  to: Number
});

const schema = new Schema({
  name: String,
  nested: nestedSchema
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1', nested: { to: 42 } });

async function run() {
  assert.strictEqual(mongoose.version, '5.3.5');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);

  const cond = {
    $or: [
      { nested: { to: { $lt: 50 } } },
      { name: /2$/ }
    ]
  };

  const found = await Test.findOne(cond).catch(assert.ifError);
  assert.ok(found);
  assert.strictEqual(found.name, 'test1');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.message);
  return connection.close();
}

```
### Output:
```
issues: ./2901.js
ifError got unwanted exception: Cast to Number failed for value "{ '$lt': 50 }" at path "to" for model "test"
issues:
```

**Comment by SachinBhandari** [comment]
Any help on evading this casting?

**Comment by lineus** [comment]
@SachinBhandari You can use dot notation in the query doc instead of nested objects. e.g. if you change the query doc in my example to 

```js
  const cond = {
    $or: [
      { 'nested.to': { $lt: 50 } },
      { name: /2$/ }
    ]
  };
```
The output becomes
```
issues: ./2901.js
All Assertions Pass.
issues:
```

**Comment by SachinBhandari** [comment]
> @SachinBhandari You can use dot notation in the query doc instead of nested objects. e.g. if you change the query doc in my example to
> 
> ```js
>   const cond = {
>     $or: [
>       { 'nested.to': { $lt: 50 } },
>       { name: /2$/ }
>     ]
>   };
> ```
> 
> The output becomes
> 
> ```
> issues: ./2901.js
> All Assertions Pass.
> issues:
> ```

Actually my use case is different, I want to match the condition in the same embedded document. I have already also posted my query over there #2901 .

**Comment by SachinBhandari** [comment]
> > @SachinBhandari You can use dot notation in the query doc instead of nested objects. e.g. if you change the query doc in my example to
> > ```js
> >   const cond = {
> >     $or: [
> >       { 'nested.to': { $lt: 50 } },
> >       { name: /2$/ }
> >     ]
> >   };
> > ```
> > 
> > 
> > The output becomes
> > ```
> > issues: ./2901.js
> > All Assertions Pass.
> > issues:
> > ```
> 
> Actually my use case is different, I want to match the condition in the same embedded document. I have already also posted my query over there #2901 .

Thought $elemMatch solved the problem,
    
    AllocatedStationery.find({
        "kind":"awb",
        "serial":true,
        "consumerTeamId":"5afcedd5236ca628a123e41",
        "prefix":"ON",
        "to":{"$gte":32164},
        "from":{"$lte":32164},
        "consumed":{"$ne":32164},
        "$or":[
            {
                "spoiled":
                    {
                        $elemMatch: {
                            "to":{
                                "$lt":32164
                            },
                            "from":{
                                "$gt":32164
                            }
                        }
                    }
                },
            {
                "spoiled":[]
            }
        ]
    })

**Comment by lineus** [comment]
@SachinBhandari 

I'm not sure if you meant to say **"Though $elemMatch solved the problem"** or that *you* **"Thought $elemMatch solved the problem"** *but it didn't.*

If it's the second case, here's an example of what I meant, that instead has 2 fields in the nested doc/query. 

### 2901.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection } = mongoose;
const DB = '2901';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const nestedSchema = new Schema({
  to: Number,
  from: Number
});

const schema = new Schema({
  name: String,
  nested: [nestedSchema]
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test1',
  nested: [
    { to: 42, from: 9 },
    { to: 49, from: 12 }
  ]
});

async function run() {
  assert.strictEqual(mongoose.version, '5.3.6');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);

  const cond = {
    $or: [
      { 
        $and: [
          { 'nested.to': { $lt: 50 } },
          { 'nested.from': { $gt: 10 } }
        ]
      },
      { name: /2$/ }
    ]
  };

  const found = await Test.findOne(cond).catch(assert.ifError);
  assert.ok(found);
  assert.strictEqual(found.name, 'test1');
  assert.strictEqual(found.nested.length, 2);
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(error);

function error(e) {
  console.error(e.message);
  return connection.close();
}
```
### Output:
```
issues: ./2901.js
All Assertions Pass.
issues:
```

**Comment by SachinBhandari** [comment]
@lineus , 
    Sorry for the typo. I actually mean $elemMatch solved my problem.

Above example does not solved my problem as I want to match `nested.from` and `nested.to` to same 
sub document.

**Comment by SachinBhandari** [comment]
```Even if the query { nested: { to: { $lt: 50 } } } makes it down to the MongoDB server, it will return no results```. 

Before mentioning here, I ran the same query in Mongo Shell and it returned the expected result just to make sure I might be wrong in building the query or may be it's not possible in MongoDB.
