### ISSUE TITLE
When does debug print? Before or after the successful call?

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#7172]
Hi, I am wondering whether debugging statements get printed before or after a successful db operation. I am asking because my debugging statements seem to print out of order from time to time (sometimes way later). Of course everything is asynchronous, but I have some operations that I wait (`await`) to complete and so the debugging statements should show up before any future operations get printed, but they still seem to print way later. 

The fact that these operations are part of an await operation and print later is sort of concerning since my code operates in a serverless environment and I want to ensure the call succeeded before my environment spins down (i.e. aws lambda). Hoping there can be some light shed on debugging and console logging. 

Thanks!

I am using mongoose 5.3.5 and node 8.11.4

**Comment by vkarpov15** [comment]
The debug messages print right before Mongoose calls the underlying MongoDB driver, but after all Mongoose-specific logic. So a pre('find') hook will run before Mongoose prints `find()` to debug, but the actual process of sending the `find()` to the server happens after Mongoose prints `find()` to debug. Does that make sense?
