### ISSUE TITLE
strictQuery throw an error where it shouldn't

### ISSUE THREAD

**Issue by abarriel** [Automattic/mongoose#7178]
Hey!
I am wondering why the script below throw a validation error.
I set strictQuery to throw, but the filter in find is correct.

**Solution found**  if a use a dot notation in the find filter, it works great.
There is a slice difference between `dot notation` and using an `object notation` in the filter (either it look for  exactly the same object, or only the key provided) but still we should be able to perform a find with the two syntax.
```javascript
	// solution found
	await Test.find({"customer.persona": "whatever"});
```

```javascript
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const TestSchema = new Schema(
  {
    customer: {
      persona: String,
    },
  },
  { strictQuery: "throw", timestamps: true },
);

const Test = mongoose.model("Test", TestSchema);

mongoose.connect("mongodb://localhost:27017/test");

async function main() {
  const res = await Test.find({
    customer: {
      persona: "whatever",
    },
  });
  console.log(res);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });

```

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix ASAP
