### ISSUE TITLE
Fix for "Apply defaults after setting initial value" doesn't work when documents are loaded via a query

### ISSUE THREAD

**Issue by bloveridge** [Automattic/mongoose#7182]
PR #6119 for issue #3781 addressed an issue that caused the context object (`this`) provided to `default` function callback handlers to only have access to properties set in other default handlers, not the contents of the document itself. This works when creating a document, but it does not work when loading a document via a query. This causes problems where we are trying to do conditional defaults—based on another property, the default value should either be changed or removed entirely.

Another ticket was opened about this issue and closed because no code samples were provided (
#6330). I'm pretty sure this is the same issue I'm having.

The code snippet below reproduces the current behavior, with assertions for what is expected to happen. The second assertion fails because `this.type` was `undefined` in the default callback function.

Tested using Node 8.11.3, mongoose 5.3.6, mongo 3.4.2.

```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const schema = new Schema({ type: String, choices: String });
schema.path('choices').default(function () {
  return this.type === 'mc' ? 'ABCDE' : this.type === 'rubric' ? '12345' : 'ERROR';
});

const Model = mongoose.model('Test', schema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const created = new Model({ type: 'mc', id: 1 });
  await created.save();
  assert.equal(created.choices, 'ABCDE'); // works

  // clear it out to test what happens when a loaded document needs a default
  await Model.collection.updateOne({_id: created._id}, {$set: {type: 'rubric'}, $unset: {choices: 1}});
  const loaded = await Model.findById(created._id).exec();
  assert.equal(loaded.choices, '12345'); // fails because `this` was an empty object in default handler
}

run().catch(error => console.error(error.stack));
```

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap :+1:
