### ISSUE TITLE
findByIdAndUpdate upsert race condition

### ISSUE THREAD

**Issue by bangbang93** [Automattic/mongoose#7183]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Duplicate key
**If the current behavior is a bug, please provide the steps to reproduce.**
<https://gist.github.com/bangbang93/083711c487b61237a09d2d789954f42b>
the mongoose function throws an exception `MongoError: E11000 duplicate key error collection: test.ts index: _id_ dup key: { : 1 }`.
But the mongodb function using mongodb native function `findOneAndUpdate`, and successfully update the document.

And sometimes, mongodb function can successfully update the document to `{_id:1, a:2}`, but the exception is thrown in the same way.
**What is the expected behavior?**
Update document, just like mongodb.findOneAndUpdate
**Please mention your node.js, mongoose and MongoDB version.**
nodejs v10.11.0
mongoose@5.3.6
mongodb-server 3.4.4-1.4

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap :+1:

**Comment by vkarpov15** [comment]
Do you get this error consistently? Running your script in vanilla node works fine on my machine against mongoose 5.3.6 and MongoDB 3.4.4:

```javascript
const Mongoose = require('mongoose');

Mongoose.connect('mongodb://localhost/test')

Mongoose.set('debug', true)

const schema = new Mongoose.Schema({
  _id: {
    type: Number,
  },
  a: {
    unique: true,
    type: String,
  }
})

const model = Mongoose.model('t', schema)

async function mongoose() {
  function fn(a) {
    return model.findByIdAndUpdate(1, {$set: {a}}, {upsert: true})
      .exec()
  }

  fn(1).catch(err => console.log('Error', err));
  fn(2).catch(err => console.log('Error', err));
}

async function mongodb() {
  const collections = Mongoose.connection.collection('ts')

  function fn(a) {
    return collections.findOneAndUpdate({_id: 2}, {$set: {a}}, {upsert: true})
  }

  fn(1)
  fn(2)
}

mongoose()
mongodb()
```

Output:

```
$ ~/Workspace/libs/node-v10.12.0-linux-x64/bin/node gh-7183.js 
(node:11631) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: ts.findOneAndUpdate({ _id: 2 }, { '$set': { a: 1 } }, { upsert: true })
Mongoose: ts.findOneAndUpdate({ _id: 2 }, { '$set': { a: 2 } }, { upsert: true })
Mongoose: ts.ensureIndex({ a: 1 }, { unique: true, background: true })
Mongoose: ts.findAndModify({ _id: 1 }, [], { '$setOnInsert': { __v: 0 }, '$set': { a: '1' } }, { upsert: true, new: false, remove: false, projection: {} })
Mongoose: ts.findAndModify({ _id: 1 }, [], { '$setOnInsert': { __v: 0 }, '$set': { a: '2' } }, { upsert: true, new: false, remove: false, projection: {} })
(node:11631) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:11631) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
^C
$ 
```

It may have something to do with the fact that the import you're using is wrong. Mongoose does **not** support `import * as Mongoose from 'mongoose'`, you must use `import Mongoose from 'mongoose'`, see [the FAQ for more details](https://mongoosejs.com/docs/faq.html#destructured-imports). In the meantime, can you also try using vanilla JS rather than typescript and see if you still get this error?

**Comment by bangbang93** [comment]
Typescript only allow that `import something` from `export default`
`import * as Mongoose from 'mongoose'` will be compiled to `const Mongoose = require('mongoose')`.This is different from the babel.

I can reproduce in 5.3.8
![image](https://user-images.githubusercontent.com/3430784/47987290-1d31c380-e11a-11e8-92dd-cf0553bc26b4.png)
My mongodb is on a remote server. Maybe it's related to network latency?

**Comment by bangbang93** [comment]
I cannot reproduce on a local mongodb server too.
But almost 100% on a remote mongodb server.

**Comment by vkarpov15** [comment]
Will check against a remote, maybe latency has something to do with it

**Comment by vkarpov15** [comment]
Hmm still no error, even when runniing against MongoDB Atlas. Can you clarify what version of MongoDB you're running? I don't recognize `3.4.4-1.4` as a valid MongoDB version...

**Comment by bangbang93** [comment]
db.serverBuildInfo()
```json
{
	"version" : "3.4.4-1.4",
	"gitVersion" : "3ee0bb263c7a6747ac2cea4e54fa67eabc11faff",
	"modules" : [ ],
	"allocator" : "tcmalloc",
	"javascriptEngine" : "mozjs",
	"sysInfo" : "deprecated",
	"versionArray" : [
		3,
		4,
		5,
		-100
	],
	"openssl" : {
		"running" : "OpenSSL 1.0.1e-fips 11 Feb 2013",
		"compiled" : "OpenSSL 1.0.1e-fips 11 Feb 2013"
	},
	"buildEnvironment" : {
		"distmod" : "",
		"distarch" : "x86_64",
		"cc" : "/usr/local/gcc-5.4.0/bin/gcc-5.4: gcc-5.4 (GCC) 5.4.0",
		"ccflags" : "-fno-omit-frame-pointer -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -Werror -O2 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-but-set-variable -Wno-missing-braces -fstack-protector-strong -fno-builtin-memcmp",
		"cxx" : "/usr/local/gcc-5.4.0/bin/g++-5.4: g++-5.4 (GCC) 5.4.0",
		"cxxflags" : "-Woverloaded-virtual -Wno-maybe-uninitialized -std=c++11",
		"linkflags" : "-pthread -Wl,-z,now -rdynamic -Wl,--fatal-warnings -fstack-protector-strong -fuse-ld=gold -Wl,--build-id -Wl,-z,noexecstack -Wl,--warn-execstack -Wl,-z,relro",
		"target_arch" : "x86_64",
		"target_os" : "linux"
	},
	"bits" : 64,
	"debug" : false,
	"maxBsonObjectSize" : 16777216,
	"storageEngines" : [
		"devnull",
		"ephemeralForTest",
		"inMemory",
		"mmapv1",
		"rocksdb",
		"wiredTiger"
	],
	"ok" : 1
}
```

**Comment by vkarpov15** [comment]
Hmm looking more closely it looks like you're running [Percona server for MongoDB](https://www.percona.com/downloads/percona-server-mongodb-3.4/), not an officially supported MongoDB version. Can you confirm this?

**Comment by vkarpov15** [comment]
Unfortunately I've tried time and again to repro this with percona on local and remote boxes, and same result every time - no error. Mongoose debug logs show that the query sent to the server is correct, so I'm going to have to close this.

For posterity, here's how to download the referenced version of percona server for mongodb:

```
wget https://www.percona.com/downloads/percona-server-mongodb-3.4/percona-server-mongodb-3.4.4-1.4/binary/tarball/percona-server-mongodb-3.4.4-1.4-xenial-x86_64.tar.gz
```
