### ISSUE TITLE
the schema type option unique doesn't work

### ISSUE THREAD

**Issue by MonsterGene** [Automattic/mongoose#7194]
**Do you want to request a *feature* or report a *bug*?**

I think it's a bug.

**What is the current behavior?**

I want the field value to be unique index, so i write schema like this:
```
const schema = new mongoose.Schema({
	expect: { // 期号
		type: String,
		unique: true // 设为唯一性索引
	}
})
```
but when i create some data, the unique doesn't work, and print awarning by node.js 
>(node:10156) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

Is that mean you may be update code about that function?

version :
node.js 8.11.2
mongodb 4.0.0
mongoose 5.3.7

**Comment by lineus** [comment]
@MonsterGene you can add `mongoose.set('useCreateIndex', true);` after you require mongoose. This behavior is documented [here in the deprecations guide](https://mongoosejs.com/docs/deprecations.html)
