### ISSUE TITLE
Lean option cannot be explicitly set to `false` in QueryCursor

### ISSUE THREAD

**Issue by letsgolesco** [Automattic/mongoose#7197]
**Do you want to request a *feature* or report a *bug*?**
Bug. Node 8.12.0, mongoose 5.3.7, mongodb 4.0.3.

**What is the current behavior?**
As of version 5.3.5, explicitly setting `lean: false` in cursors will result in `lean` being set to `true`. This still happens on the latest version, 5.3.7.

This commit seems to be the culprit: https://github.com/Automattic/mongoose/commit/dc34561729ca821ee918461781e5e7f1a950a4cd

Previous behavior:
```javascript
opts.lean = false;
opts.lean === true // evaluates to `false`
```

Current behavior:
```javascript
opts.lean = false;
opts.lean != null // evalueates to `true`
```

**Steps to reproduce.**
- Set up a schema (with an instance method to clearly illustrate whether found documents are lean)
- Insert some documents to the schema's collection
- Create a cursor with `lean` set to `false`
- Inspect the found documents to see if they're lean (e.g. try to execute an instance method)

Example script:
```javascript
const FruitBasket = new mongoose.Schema({ name: String, fruits: [String] });
FruitBasket.methods.getFruitsSorted = function() {
  return this.fruits.sort();
}
/* <connect to database> */
db.model('FruitBasket', FruitBasket);
await db.model.FruitBasket.insertMany([
  { name: 'berries', fruits: ['blueberry', 'strawberry', 'raspberry'] },
  { name: 'citrus', fruits: ['lemon', 'lime', 'orange'] },
  { name: 'tropical', fruits: ['banana', 'pineapple', 'mango'] },
]);
db.model.FruitBasket
  .find({})
  .lean(false)
  .select({ fruits: 1 })
  .batchSize(100)
  .cursor()
  .eachAync(fruitBasket => {
    const fruitsSorted = fruitBasket.getFruitsSorted();
    // TypeError: fruitBasket.getFruitssorted is not a function
  });
```

**What is the expected behavior?**
Setting the `lean` option to `false` should not cause `lean` to be `true`. Objects returned by the cursor should be full mongoose documents.

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap
