### ISSUE TITLE
*bug* connection on replicaset MongoDB

### ISSUE THREAD

**Issue by ddtraceweb** [Automattic/mongoose#7205]
I'm on node v9.11.1
last version of mongodb 4
last version of mongoose

```
let mongoFullUrl = getMongoFullUrl(app);
  const options = {
    autoIndex: true, // Don't build indexes
    reconnectTries: Number.MAX_VALUE, // Never stop trying to reconnect
    reconnectInterval: 500, // Reconnect every 500ms
    useNewUrlParser: true,
    poolSize: 20, // Maintain up to 10 socket connections
    socketTimeoutMS: 0,
    keepAlive: true,
    keepAliveInitialDelay: 300000
  };
setTimeout(function() {
    let mongoDB = mongoose.connect(mongoFullUrl, options)
      .then(function(){
        log('Successfully connected to database ' + mongoFullUrl);
      })
      .catch(function(err) {
        // Check error in initial connection. There is no 2nd param to the callback.
        log('Error when connecting to db ' + mongoFullUrl + '\n\r' + err);
      });
    mongoose.set('debug', app.get('debug'));
    return mongoDB;
  }, 60);
```

the connections nevers close and create an infinity of connection on mongodb.

This bug is since version mongoose 5.3 i think.

Thanks for your help :)

**Comment by teslaji** [comment]
I am facing problem with 5.3.8 version. it doesn't connect db but throws NaN error

**Comment by vkarpov15** [comment]
@teslaji can you clarify what you mean by "NaN error"?

Also, can you verify that your [hostnames are correct](https://mongoosejs.com/docs/connections.html#replicaset-hostnames)?

**Comment by teslaji** [comment]
@vkarpov15 This got resolved , it was an oversight error by me, I forgot to add my new IP to whitelist when i was trying to access from different location. I am able to connect and create documents to my database. 

Ill reproduce the code, which is very basic.

`
const obj = require('./db.json')
const mongoose = require('mongoose')
const dbUrl = obj.uri
console.log(dbUrl)

mongoose.connect(dbUrl, {
  useNewUrlParser: true
}, err => {
  if (err) {
    console.error('Error!' + err)
  } else { 
    console.log('Connected to MongoDb')
  }
})`

my url is an JSON obj.

My apologies for mistake and Thanks for raising concerns.
