### ISSUE TITLE
✅ FEATURE REQUEST 🔥: Mongodb Query Timeout with inactive connection

### ISSUE THREAD

**Issue by AbdullahAli** [Automattic/mongoose#7206]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Mongoose does not timeout if a query never resolves with an inactive connection.  eg: If we never `connect`, then `Model.find()` never resolves or rejects.

**If the current behavior is a bug, please provide the steps to reproduce.**
Not a bug

**What is the expected behavior?**
It would be great to add a feature to timeout, with an inactive connection.  Similar to `maxTime`, but within mongoose itself, rather than relying on the mongo driver.

**Please mention your node.js, mongoose and MongoDB version.**
Node v10, Mongoose 5.3.8, MongoDB 3.2.3

**Comment by AbdullahAli** [comment]
Maybe introduce a top level config variable?

**Comment by vkarpov15** [comment]
[`mongoose.set('bufferCommands', false)`](https://mongoosejs.com/docs/connections.html#buffering) should work for what you're trying to achieve. Please re-open if it doesn't.
