### ISSUE TITLE
Add additional parameter for bulkwrite to trigger middleware

### ISSUE THREAD

**Issue by pshox** [Automattic/mongoose#7211]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
When do bulkwrite it doesnt trigger middleware such as pre save in models.
**If the current behavior is a bug, please provide the steps to reproduce.**

db.collection.bulkWrite(operations, options);

**What is the expected behavior?**
It would be great if the options could take additional arguments to trigger pre save, create and so on operations

const options = {
  triggerSave: true // triggerSave or however 
};

**Please mention your node.js, mongoose and MongoDB version.**
node: v8
mongo: v4

**Comment by vkarpov15** [comment]
Why not just use create() ? That triggers save middleware: https://mongoosejs.com/docs/api.html#model_Model.create

**Comment by pshox** [comment]
Ok, we got it. Thanks!

**Comment by bonesoul** [comment]
@vkarpov15 in my case i can't use create as in my bulkwrite some documents are newly created and some are just updates.

any way to force middlewares in  bulkwrite?

**Comment by vkarpov15** [comment]
@bonesoul which hooks specifically are you looking to trigger?

**Comment by bonesoul** [comment]
findOneAndUpdate or just validate.

**Comment by vkarpov15** [comment]
We could maybe do validate middleware if you're doing insertOne with bulkWrite (), but even that is a but if a stretch. Another alternative would be for you to explicitly run `validate()` on a bunch of documents before using bulkWrite ().

Another question: why are you using bulkWrite to begin with? Is there a meaningful performance difference for you?

**Comment by bonesoul** [comment]
i'm updating 2000 documents at a single pass. anyway i've somewhat changed my logic and no more need to use validate.
