### ISSUE TITLE
The query post remove hook do not pass removed doc as argument

### ISSUE THREAD

**Issue by blueyestar** [Automattic/mongoose#7212]
The query post remove hook do not pass removed doc as argument but the document post remove hook does. It's hard to keep same behavior within query post remove hook and document post remove hook.

How to reproduce:
const authorSchema = new Schema({
articles: [type: Schema.Types.ObjectId, ref: "Article"],
});

// this works
authorSchema.post('remove', {query: false, document: true}, async function(author, next){
  await ArticleModel.remove({author: author._id});
  next();
});

// this does not work
authorSchema.post('remove', {query: true, document: false}, async function(){
  // not able to get the removed author
  await ArticleModel.remove({author: author._id});
});

node.js        8.11.3
mongoose  5.3.8
MongoDB   3.4.17

**Comment by vkarpov15** [comment]
Unfortunately this is expected behavior. If you want the removed doc you will need to use findOneAndDelete https://mongoosejs.com/docs/api.html#model_Model.findOneAndDelete
