### ISSUE TITLE
Recursive error with discriminators in custom mongoose

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#7214]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After the fix in 5.3.8 I tested my app and realize there is a problem with discriminators, but only with custom mongoose.

It seems that the lib/utils.js merge function has a recursive problem with no effective escape.

**If the current behavior is a bug, please provide the steps to reproduce.**
happily the recursive problem it's very easy to reproduce.
```"use strict";
const mongoose = require("mongoose");
const db = new mongoose.Mongoose();
const {Schema} = db;
db.connect("mongodb://localhost/test");
let test = new Schema({
    a:Number
});
let test2 = new Schema({
    b:Number,
});
let Test = db.model("Test",test);
let Test2 = Test.discriminator("Test2",test2);
``` 

BTW if you test it with default mongoose it works.

**What is the expected behavior?**
Since the custom types problem started in 5.3.2, I can't tell you when it begins. So I've to stay in 5.3.1, nor 5.3.8 neither 5.3.9 fix this problem.
**Please mention your node.js, mongoose and MongoDB version.**
node 10.12
mongo 4

**Comment by vkarpov15** [comment]
This was fixed in 5.3.10 with the fix for #7200 , I can confirm this script fails in 5.3.9 but succeeds in 5.3.10.
