### ISSUE TITLE
Change detection in pre-save middleware

### ISSUE THREAD

**Issue by normads** [Automattic/mongoose#7216]
This is not a bug, but I'm trying to implement a use case mentioned in the docs but it's not clear to me how.

I want to trigger a set of asynchronous tasks based on the property that's being updated. I figured i can do this in the pre save hookup but in order to detect the parameters being updated i need change detection to trigger the right callback. Is there any way to do this? Since mongoose inherently uses change detection is there any way we can access the same information?

node v8.11.4, mongodb 4.0.2, mongoose 4.13.12

**Comment by vkarpov15** [comment]
See [`Document.prototype.modifiedPaths()`](https://mongoosejs.com/docs/api.html#document_Document-modifiedPaths), that should be what you need.

```javascript
schema.pre('save', function() {
  console.log(this.modifiedPaths()); // Prints an array of paths that were modified
});
```
