### ISSUE TITLE
Filtering results based on multiple models?

### ISSUE THREAD

**Issue by jimpsson** [Automattic/mongoose#7217]
I index podcasts and podcast episodes. Using a podcast and a episode model. The podcast model has information like language, URL of the RSS feed, and an array of referenced ObjectIDs to all its episodes.

I would like to filter some results based on locale on my site, this has not been an issue earlier because I did only index podcasts in one language.

So for example, when I show the latest episodes in one page, I simply fetch them by using the Episode model, then populating the podcast path (reference pointing back to the Podcast model).

As I have come to understand, what I really should be doing if I want to filter based on language and such I would need to initiate the call by first finding all Podcasts in one language and then populating all its episodes and then filtering based on timestamps. But when I do it this way I create an array of podcasts with an array of episodes and not the opposite which is what I am doing currently.

Is there any way around working this out, or should I think of it in another way perhaps? Is there any solution that can simplify this for me, like any plugin for example. Or can I solve this in some way?

**Comment by jimpsson** [comment]
OK, so I was able to do this, but only by filtering the results locally in JS after the population. Simply use a filter method testing wether the path was populated or not, but this way the numbers of documents in the end will not be the same as what I've to limit in the mongoose function call.

Is there any way around filtering locally so that I can better control the end result?

**Comment by vkarpov15** [comment]
@jimpsson can you please provide some code samples, like schemas and the code that does the filtering? Converting prose to code is very tricky.

**Comment by jimpsson** [comment]
``
const lang = req.params.lang ? [req.params.lang] : ['en', 'us']

const PodcastSchema = new Schema({
  slug: String,
  title: String,
  description: String,
  language: String,
  episodes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Episode' }]
})

const EpisodeSchema = new Schema({
  slug: String,
  title: String,
  description: String,
  publicationDate: {
    type: Date,
    default: Date.now
  },
  podcast: {
    type: Schema.Types.ObjectId,
    ref: 'Podcast',
    required: true
  }
})

exports.get = (req, res, next) => {
Episode.find({
  publicationDate: {
    $gte: new Date(new Date().setDate(new Date().getDate() - 7))
  }
})
  .select('slug title description publicationDate')
  .populate({
    path: 'podcast',
    select: 'title description language slug',
    match: { language: { $in: lang } }
  })
  .limit(200)
  .exec(function(err, docs) {
    if (err) {
      next(err)
    }
    docs = docs.filter(function(doc) {
      return doc.podcast
    })
    res.json(docs)
    // do stuff with docs
  })
})
``

That is how I've solved it so far, because of the match condition on population I get null return if the match does not meet the criteria. But that makes the 200 document limit not accurate and I don't know if there is any mongoose or mongodb option for this, or if it's up to me after the population to solve?

**Comment by vkarpov15** [comment]
There's no option for this unfortunately. The easiest way to do this in MongoDB is to add a `language` property to your `EpisodeSchema`. Always remember, "store what you query for".

```javascript
const EpisodeSchema = new Schema({
  slug: String,
  title: String,
  description: String,
  publicationDate: {
    type: Date,
    default: Date.now
  },
  podcast: {
    type: Schema.Types.ObjectId,
    ref: 'Podcast',
    required: true
  },
  language: String // Copied from podcast
})
```

Sure this isn't third normal form, but [3NF was designed to minimize storage costs](https://en.wikipedia.org/wiki/Third_normal_form) as opposed to query speed. You can use [middleware](https://mongoosejs.com/docs/middleware.html) to make sure the language stays in sync, but I imagine you don't really change a podcast's language often.

If you can't add the `language` property, you need to use MongoDB's aggregation framework and [`$lookup`](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/).
