### ISSUE TITLE
Feature request: Composing schemas from seperate schemas

### ISSUE THREAD

**Issue by florianbepunkt** [Automattic/mongoose#7218]
It would be great to be able to compose complex schemas out of simpler schemas, using them like building blocks. I'm working on an app with a lot of different models where often discriminators make no sense, but composing schemas out of smaller ones would make code much more DRY.

Schm has a functionality like this, quoting from their medium article, this explains what I mean:

Say you have separate schemas describing a body, identity and other things, and want to compose them to build a human schema. That's as easy as it sounds:

```
const schema = require("schm");

const identitySchema = schema({
  name: String,
  birthdate: Date,
});

const bodySchema = schema({
  height: Number,
  weight: Number,
});

const humanSchema = schema(
  identitySchema, 
  bodySchema,
  {
    age: Number,
  }
);
```

(source: https://medium.freecodecamp.org/how-to-write-powerful-schemas-in-javascript-490da6233d37)

so in this case the resulting human schema would be 

```
{
  name: String,
  birthdate: Date,
  height: Number,
  weight: Number,
  age: Number,
}
```

**Comment by vkarpov15** [comment]
What about [plugins](https://mongoosejs.com/docs/plugins.html), see [this blog post too](http://thecodebarbarian.com/2015/03/06/guide-to-mongoose-plugins) ? [`Schema.add()`](https://mongoosejs.com/docs/api.html#schema_Schema-add) supports passing in a schema as of 5.3.0, so you can do something like:

```javascript
const identityPlugin = schema => schema.add({
  name: String,
  birthdate: Date,
});

const humanSchema = new Schema().plugin(identityPlugin)
```

See [`Schema.plugin()`](https://mongoosejs.com/docs/api.html#schema_Schema-plugin)

**Comment by florianbepunkt** [comment]
Thank you. Using the plugin approach would be a bit too verbose imo. I quoted the human/indentiy case as a simplified example. In my particular use case I have about 15 "schema" blocks with which I would like to build models.

I did not know that you could add a schema with Schema.add(), so this should be doable (will try tomorrow) Being able to compose/include schemas inline might be syntactically cleaner though.

**Comment by vkarpov15** [comment]
Hmm ok so you're thinking of an API where you can pass a list of schemas or objects to the schema constructor, like:

```javascript
new mongoose.Schema([baseSchema, childSchema, { name: String, specialProperty: String }]);
```

Is that a fair description of what you're trying to do?

**Comment by florianbepunkt** [comment]
Exactly

**Comment by vkarpov15** [comment]
Will do :+1:
