### ISSUE TITLE
Bug : ERROR IN NPM UPDATE / NPM INSTALL MONGOOSE 

### ISSUE THREAD

**Issue by DaggieBlanqx** [Automattic/mongoose#7221]
51 info outdated     what: 'mongoose@5.3.9' } ]
52 silly install loadCurrentTree
53 silly install readLocalPackageData
54 http fetch GET 200 https://registry.npmjs.org/mongoose 25ms (from cache)
55 silly fetchPackageMetaData error for mongoose@5.3.9 Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
56 timing stage:rollbackFailedOptional Completed in 1ms
57 timing stage:runTopLevelLifecycles Completed in 345ms
58 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
58 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by NewEraCracker** [comment]
What's your npm version?

**Comment by DaggieBlanqx** [comment]
@NewEraCracker @vkarpov15 
The NPM version is 6.4.1 .
**_npm install_** fails , but **_yarn add_** works .

**Comment by NewEraCracker** [comment]
that is strange. I use also npm 6.4.1 and is working here.

Do you have further details such as:
* Operating system
* Output of ```npm -g ls```

Can you try reinstalling npm with:
* ```npm -g i npm```

**Comment by NewEraCracker** [comment]
Also it could be that the package.json or package-lock.json on your project is corrupted. Maybe you could share those files with us too (unless they contain private intellectual property)

**Comment by DaggieBlanqx** [comment]
Attached is the log and the package.json .

**Comment by DaggieBlanqx** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mongoose@5.3.9' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose npm-session 595909a2b30f9952
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/mongoose failed, reason: connect ETIMEDOUT 104.16.27.35:443
8 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
9 http fetch GET 200 https://registry.npmjs.org/mongoose 133607ms (from cache)
10 silly fetchPackageMetaData error for mongoose@5.3.9 Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
11 timing stage:rollbackFailedOptional Completed in 2ms
12 timing stage:runTopLevelLifecycles Completed in 138354ms
13 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
13 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
13 verbose stack     at JSON.parse (<anonymous>)
13 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
13 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose stack From previous event:
13 verbose stack     at runCallback (timers.js:694:18)
13 verbose stack     at tryOnImmediate (timers.js:665:5)
13 verbose stack     at processImmediate (timers.js:647:5)
13 verbose stack From previous event:
13 verbose stack     at fetchPackument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:91:7)
13 verbose stack     at getManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:37:10)
13 verbose stack     at manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:10)
13 verbose stack     at Object.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\index.js:12:12)
13 verbose stack     at Object.Fetcher#manifest [as manifest] (C:\Program Files\nodejs\node_modules\npm\node_modules\genfun\lib\genfun.js:15:38)
13 verbose stack     at manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetch.js:16:18)
13 verbose stack     at pinflight (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\manifest.js:24:12)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:29:24
13 verbose stack From previous event:
13 verbose stack     at _inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:28:25)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:22:14
13 verbose stack     at runCallback (timers.js:694:18)
13 verbose stack     at tryOnImmediate (timers.js:665:5)
13 verbose stack     at processImmediate (timers.js:647:5)
13 verbose stack From previous event:
13 verbose stack     at inflight (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-inflight\inflight.js:14:40)
13 verbose stack     at Object.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\manifest.js:22:10)
13 verbose stack     at fetchPackageMetadata (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:58:10)
13 verbose stack     at limited (C:\Program Files\nodejs\node_modules\npm\node_modules\call-limit\call-limit.js:29:10)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:235:14
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
13 verbose stack     at Array.forEach (<anonymous>)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
13 verbose stack     at Array.forEach (<anonymous>)
13 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
13 verbose stack     at exports.getAllMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:206:3)
13 verbose stack     at Installer.loadArgMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install.js:360:3)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:695:16
13 verbose stack     at BB.join.then (C:\Program Files\nodejs\node_modules\npm\lib\install\read-shrinkwrap.js:34:16)
13 verbose stack From previous event:
13 verbose stack     at readShrinkwrap (C:\Program Files\nodejs\node_modules\npm\lib\install\read-shrinkwrap.js:34:5)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:691:7
13 verbose stack     at a (C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\iferr.js:3:64)
13 verbose stack     at thenHandleErrors (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-tree\rpt.js:248:5)
13 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
13 verbose stack     at asyncForEach (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-tree\rpt.js:11:31)
13 verbose stack     at thenProcessChildren (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-tree\rpt.js:215:12)
13 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
13 verbose stack     at thenReaddir (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-tree\rpt.js:150:20)
13 verbose stack     at gotStat (fs.js:1574:21)
13 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
13 verbose stack     at FSReqWrap.oncomplete (fs.js:154:21)
14 verbose cwd E:\bug
15 verbose Windows_NT 10.0.17134
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose@5.3.9"
17 verbose node v10.10.0
18 verbose npm  v6.4.1
19 error Unexpected end of JSON input while parsing near '..."1.1.22","dependencie'
20 verbose exit [ 1, true ]

**Comment by DaggieBlanqx** [comment]
{
  "name": "app",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by NewEraCracker** [comment]
try to run ```npm cache clean --force``` this looks like npm did not manage to download the full json at https://registry.npmjs.org/mongoose

**Comment by vkarpov15** [comment]
Also, does this still happen with Mongoose 5.3.10 and 5.3.12?

**Comment by riftninja** [comment]
@NewEraCracker thanks, worked for me.

**Comment by DaggieBlanqx** [comment]
I want to close down this . Since we have moved on . We are using yarn instead of npm . If there is any more concern. Please email me daggieblanqx@gmail.com .Thanks.
