### ISSUE TITLE
Unable to fetch bulkwriteresult result upon update to mongoose 5

### ISSUE THREAD

**Issue by arvi** [Automattic/mongoose#7225]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Upon updating to mongoose 5 from mongoose 4, bulkwriteresult object is unable to retrieve nMatched, nModified, etc. It is now `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
          const bulkWriteResult = await Student.bulkWrite(
            [...bulkAddDeleteOps, ...bulkUpdateOps, ...bulkDeleteOps],
            { ordered: true, w: 1 },
            (err, result) => {
              if (err) throw err;
            },
          );

          // this used to work before package upgrade
          bulkWriteStatus = {
            matched: bulkWriteResult.nMatched,
            modified: bulkWriteResult.nModified,
            ok: bulkWriteResult.ok,
          };
```

```js
// when I log `bulkWriteResult` in console, it shows this
 BulkWriteResult {
   result:
    { ok: 1,
      writeErrors: [],
      writeConcernErrors: [],
      insertedIds: [],
      nInserted: 0,
      nUpserted: 0,
      nMatched: 28,
      nModified: 28,
      nRemoved: 0,
      upserted: [] },
   insertedCount: 0,
   matchedCount: 28,
   modifiedCount: 28,
   deletedCount: 0,
   upsertedCount: 0,
   upsertedIds: {},
   insertedIds: {},
   n: 0 }
```
**What is the expected behavior?**
Work as-is the current version

**Please mention your node.js, mongoose and MongoDB version.**
node: 8.9.4
mongoose: 5.3.10
mongodb: 3.6.4

**Comment by vkarpov15** [comment]
We will need to make a note of these changes in the migration guide, but the new properties are [documented here](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#~BulkWriteOpResult) so you should either do `.then(res => res.result)` or use the new property names.
