### ISSUE TITLE
How would one add a field to a Schema AFTER it has already been created?

### ISSUE THREAD

**Issue by Jaskiratpal** [Automattic/mongoose#7229]
I recently started developing an app for my senior project which requires me to use some type of database. For that I decided to go with Mongoose since it is noSQL and slightly easier to pick up.

So, fast forward and I run into a problem where I can't figure out how to edit an already existing Schema and add new keys into it.

For example, I have this Schema which represents a post(think Tweets or Facebook posts) that holds:

    A string that holds the body of the post
    The id of the user that created the post
    The Date of when the post was created

My code for that is:

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Schema
const PostsSchema = new Schema({
  Value: {
    type: String,
    required: true
  },
  User: {
    type: Schema.Types.ObjectId,
    ref:'users'
  },
  Date: {
    type: Date,
    default: Date.now
  }
});

// Create collection and add schema
mongoose.model('posts', PostsSchema, 'posts');
```
 
I have done `Posts.schema.add({Device: {type: String, default: "iPhone"}}); `and that shows up in the database as such: 
```
{
    "_id": {
        "$oid": "1831g98af21n9s5u7s9ccchj5"
    },
    "Value": "Beautiful day outside, can't wait to go jogging!",
    "User": {
        "$oid": "9a79ab143lbk9lk55wq327oi3226m"
    },
    "Date": {
        "$date": "2018-10-29T01:28:44.408Z"
    },
    "Device":  "iPhone"
    "__v": 0
}
```
but it doesn't seem to be added into the schema because every time I try to access it using 
```
Posts.findOne({Device: "iPhone"}) 
    .then(posts=> {console.log(posts.Device)}); 
```

I get undefined. But if I do 

```
Posts.findOne({Value: "Beautiful day outside, can't wait to go jogging!"}) 
    .then(posts=> {console.log(posts)}); 
```
it shows Device: "iPhone"

So what is causing it to show up in the Database but I can't access as I can other fields of the same schemas?

Is there an alternative way that you can change the code to do what I want?
Aka have a similar functionality to MongoDB's $set keyword which updates the field if it exists, otherwise it creates a new field.

**Comment by NewEraCracker** [comment]
Just update your code like this
```
const PostsSchema = new Schema({
  Value: {
    type: String,
    required: true
  },
  User: {
    type: Schema.Types.ObjectId,
    ref:'users'
  },
  Date: {
    type: Date,
    default: Date.now
  },
{Device: {type: String, default: "iPhone"}} // the new property you just added for each document
});
```

**Comment by Jaskiratpal** [comment]
I get that but I wanted to make it so it we can extend the Schema based on user input. For the app I'm making, the Schema is for music genres and I want to have some way to add a new field into the schema if it doesn't exist. 

Imagine I have Rock, HipHop, Classical already in the schema and a user wants to insert House as a new genre, I want to know how I can do that? So the Schema basically expands based on user input.

**Comment by vkarpov15** [comment]
@Jaskiratpal Mongoose doesn't support editting a model's schema after it has already been compiled into a model with [`mongoose.model()`](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-model). If you want to support arbitrary keys, you can use a [mixed type](https://mongoosejs.com/docs/schematypes.html#mixed) as @mhombach suggested. Based on what you're asking for though, I think the [map type](https://mongoosejs.com/docs/schematypes.html#maps) would be a better fit for your use case.

**Comment by aseemmohds** [comment]
Hi @vkarpov15,  how to add new encrypt fields to a collection with out dropping collection while createCollection already been using for automatic encryption

**Comment by vkarpov15** [comment]
I haven't tried this, but I think the [collMod command](https://www.mongodb.com/docs/manual/reference/command/collMod/) is your best bet.

If collMod doesn't work, you'll likely have to drop and recreate your collection.
