### ISSUE TITLE
TypeError: Cannot read property '_path' of undefined

### ISSUE THREAD

**Issue by suddrey** [Automattic/mongoose#7230]
Hi!
I am working on a large project, and one of the schemas in the project contains the following item:

```javascript
clients: [
    new Schema({
      company: {
        type: Schema.Types.ObjectId,
        ref: 'Company'
      },
      sites: [{
        type: Schema.Types.ObjectId,
        ref: 'Site'
      }],
      assigned_by: {
        type: Schema.Types.ObjectId,
        ref: 'Company'
      },
      is_active: Boolean
    }, { _id: false })
  ],
```

One of the methods attached to the model for this schema performs the following push operation:

```javascript
this.clients.push({
        company: site.owner,
        assigned_by: this.parent,
        is_active: true,
        forms: [],
        sites: [site]
});
```

However, I experienced strange behaviour where none of the data on the pushed object seemed to be stored on the document.

Eventually, through a fair amount of prodding and poking, I found that by using a modified version of the code, seen below:

```javascript
this.clients.push({
        company: site.owner,
        assigned_by: this.parent,
        is_active: true,
        forms: [],
        sites: []
});
this.clients[this.clients.length-1].push(site);
```

Produced the error:
```javascript
TypeError: Cannot read property '_path' of undefined
    at EmbeddedDocument.$__fullPath (PROJECT_PATH/node_modules/mongoose/lib/types/embedded.js:400:44)
    at Function.SchemaType._isRef (PROJECT_PATH/node_modules/mongoose/lib/schematype.js:1049:22)
    at ObjectId.cast (PROJECT_PATH/node_modules/mongoose/lib/schema/objectid.js:92:18)
    at ObjectId.SchemaType.applySetters (PROJECT_PATH/node_modules/mongoose/lib/schematype.js:763:12)
```

Modifying ```paths.unshift(parent.__parentArray._path);``` on line 400 of embedded.js to ```paths.unshift(parent.__parent._path);``` seems to fix this error, but I'm not familiar enough with this library to know why this error is occurring, or what unexpected behaviour might arise from my change. 

Any thoughts/feedback would be appreciated.

Edit: Fixed copy/paste error

**Comment by mhombach** [comment]
We need the code where you do `paths.unshift`.
The Error you get is not really tied to mongoose but to some mistake you do in JS.
Read the errormessage carefully:
`Cannot read property _path of undefined`.
This means that if you access `parent.__parentArray._path` and you get the error, then `parent.__parentArray` is UNDEFINED.
Debug this: before you do your line of code, print a stringified version of `parent` or `parent.__parentArray` and find your mistake :)

**Comment by mhombach** [comment]
We need the code where you do `paths.unshift`.
The Error you get is not really tied to mongoose but to some mistake you do in JS.
Read the errormessage carefully:
`Cannot read property _path of undefined`.
This means that if you access `parent.__parentArray._path` and you get the error, then `parent.__parentArray` is UNDEFINED.
Debug this: before you do your line of code, print a stringified version of `parent` or `parent.__parentArray` and find your mistake :)

**Comment by suddrey** [comment]
I'm not sure I understand your point. ```paths.unshift``` is is a line from mongoose/lib/types/embedded.js, which is most certainly NOT my code. The error message is quite explicit in stating this in fact.

**Comment by mhombach** [comment]
Misread that part, sorry. Didn't realized it's from a lib.
What i saw now is, that you have a typo in your code:
`this.clients[this.clients.length-1].push(site);` is mostly wrong, correct would be `this.clients[this.clients.length-1].sites.push(site);`
It still bugs me that you wrote that you had problems at first when creating the document with `sites`-array already be filled with `site`... Maybe you can check into that error again too?

**Comment by suddrey** [comment]
Sorry, ```this.clients[this.clients.length-1].sites.push(site);``` was my actual test code. I wrote the edit on my phone on the bus home from work after seeing that I had copy/pasted the same code twice.

I have tried both pre-initialising the array with a site and having an empty array that I push on to and I get the same error. Updating the lib was the only thing that fixed the issue for me.

**Comment by mhombach** [comment]
With "updating the library" you mean you modified the npm-package by hand in the way you wrote in your first post? Or you did a `npm update`?

**Comment by suddrey** [comment]
As in I modified the library file by hand to replace ```paths.unshift(parent.__parentArray._path);``` with ```paths.unshift(parent.__parent._path);``` 

I am running the latest version of the library.

**Comment by mhombach** [comment]
What i would do:
- delete `sites` array from the object you are pushing and see what happens
- if the above fails, delete as many entries and see if there is some special entry that is causing the error
- create json.stringify logs on each steap of the way to see what happens within the `clients`-object/array

Personally I doubt that the library has an issue of that scale.
If you don't give feedback here today of you finding the "real" issue, then i can test your code tomorrow, maybe in about 4-5 hours or so when i'm at home :)

**Comment by mhombach** [comment]
Ok, i now had time to try this for myself and it works without any problems.
Here is my code (i modified it slightly to not need to code your whole reference-structure but the main parts are the same, see for yourself):
```
let mongoose = require('mongoose');

let Clients_schema = new mongoose.Schema({
    clients: [
        new mongoose.Schema({
          company: {
            type: Number
          },
          sites: [{
            type: Number
          }],
          assigned_by: {
            type: Number
          },
          is_active: Boolean
        }, { _id: false })
      ]
});

const _clients = mongoose.model("clients", Clients_schema, 'clients');

myVar = new _clients();
myVar.clients.push({
    company: 1,
    assigned_by: 2,
    is_active: true,
    forms: [],
    sites: [1,2,3,4,5,6]
});
console.log(JSON.stringify(myVar.clients));
```

This outputs: `[{"sites":[1,2,3,4,5,6],"company":1,"assigned_by":2,"is_active":true}]`.

Maybe you can compare bot codes and see where you maybe did something wrong? Maybe the way you create the parent model, idk...
Sometimes it helps to delete the node_modules folder and ALSO the npm-cache (google where to find it), i also hadd some errors months before where something in a npm-package was broken and the cache didn't update itself...

**Comment by suddrey** [comment]
The issue I have is with embedded documents, not with primitive field types. I will try to test this more clearly in isolation over the weekend to see if I can replicate it with an example that I can upload.

**Comment by suddrey** [comment]
After some pretty heavy debugging, I finally discovered the source of my issue. For some of my schemas, I define a parent virtual to store a temporary relationship between documents after retrieval, as seen below.

```javascript
ExampleSchema.virtual('parent')
  .set(function (parent) {
    this.__parent = parent;
  })
  .get(function () {
    return this.__parent;
  });
```

I did not realise at the time that ```this.__parent``` was setting a reserved variable used by mongoose to perform its document traversals. I have now changed the name of this variable to something else, and my error has gone away.

Thank you for your time, and I'm super irritated with myself for not finding this sooner.

**Comment by mhombach** [comment]
I'm very proud of you for 2 things:
1: Sticking to finding the real issue and using a workaround like "patching" an existing npm-package
2: Coming back to this thread, giving a detailed explanation on what the real issue was (and so helping others that might fall into the same pitfall) and then closing the issue.
Really, thank you :)

**Comment by vkarpov15** [comment]
We should really work around this, it is hard to know all the internal properties that mongoose relies on. In this case, we should just use a symbol
