### ISSUE TITLE
Unexpected behavior for virtuals overriding 

### ISSUE THREAD

**Issue by joaoritter** [Automattic/mongoose#7234]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Every time I override a virtual property, I expect it to be the newly referenced version when called.
**Please mention your node.js, mongoose and MongoDB version.**
8.6.0, 5.1.5

**Comment by mhombach** [comment]
@joaoritter Please fill out the issue-template you provided mostly empty. Without more information nobody is able to help you. give code-examples of what you are doing, what you expect to happen and what happens in reallity.

**Comment by vkarpov15** [comment]
@joaoritter please provide some code samples.
