### ISSUE TITLE
How to return count:0 in an aggregation if there is no match

### ISSUE THREAD

**Issue by BengBu-YueZhang** [Automattic/mongoose#7236]
## Do you want to request a *feature* or report a *bug*?

feature

## If the current behavior is a bug, please provide the steps to reproduce.

How to return count:0 in an aggregation if there is no match

## detail

There's elasticsearch where I can return something that counts to zero. How do I do that in mongoose?

```shell

{
  "size": 0,
  "aggs": {
    "date": {
      "date_histogram": {
        "field": "at",
        "interval": "day",
        "min_doc_count": 0,
        "order": {
          "_key": "desc"
        }
      }
    }
  }
}
```

**Comment by vkarpov15** [comment]
It is pretty hard to do this in general with the aggregation framework, here's a [SO question that may be helpful](https://stackoverflow.com/questions/50243295/mongodb-aggregate-return-count-of-0-if-no-documents). I would recommend doing this in your node app though.
