### ISSUE TITLE
Have data but queries string in array always returns empty array.

### ISSUE THREAD

**Issue by knighLin** [Automattic/mongoose#7239]
**Do you want to request a *feature* or report a *bug*?**
feature

**Please mention your node.js, mongoose and MongoDB version:**
My Node.js is v8.12.0 ,MongoDB is  v4.0.3 and Mongoose is 5.3.9.

**My code for that is:**

```javascript
var ProjectDataSchema = new mongoose.Schema({
	name:String,
	background:String,
	objective:String,
	group:[String],
	createTime:Date,
	updateCount:Number
});
var ProjectData = mongoose.model('ProjectData',ProjectDataSchema,'ProjectData');
ProjectData.find({group:"PM001"},(err,doc)=>{
         console.log(doc);
});
```

**My Json Data for that is:**

```
{
    "_id" : ObjectId("5be93a946ebad90a1c364e3d"),
    "name" : "A",
    "background" : "231",
    "objective" : "123",
    "group" : [ 
        " PM001", 
        " E001"
    ],
    "createTime" : ISODate("2018-11-12T16:32:20.156+08:00"),
    "updateCount" : 0,
    "__v" : 0
}
```

I want to know why queries string in array always returns an empty Array. I‘m sure my database has this data.
I want to get doc but the doc is an empty array.
I had tried '$in' and '$elemMatch' too.But thay are not useful.
So hope somebody can tell me why and how to change my code.

**Comment by mhombach** [comment]
Please give more details on what data you get as a result of your query.

**Comment by vkarpov15** [comment]
It looks like in your JSON data, the `group` property always starts with a space, but your query is searching by 'PM001' not ' PM001'. Can you check if that is the issue?

**Comment by knighLin** [comment]
> 看起來在您的JSON數據中，`group`屬性始終以空格開頭，但您的查詢是按'PM001'搜索而不是'PM001'。你能檢查一下這是不是問題？

**Comment by knighLin** [comment]
@vkarpov15  You are right. This is the data problem. I have a blank space in ejs file.So my data was wrong. Thank you.
