### ISSUE TITLE
Problem with method mongoose.connect()

### ISSUE THREAD

**Issue by leandrosoares6** [Automattic/mongoose#7243]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
The problem happens when trying to connect to mLab database URI with mongoose.connect().

**If the current behavior is a bug, please provide the steps to reproduce.**

The following program can be used to reproduce this:

 const mongoose = require('mongoose');
mongoose.connect('mongodb://user:password@ds133601.mlab.com:33601/myapp-backend', { 
     useNewUrlParser: true 
 });

**This is the exception that gets thrown:**

(node:1176) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [ds133601.mlab.com:33601] on first connect [MongoNetworkError: connect ETIMEDOUT 34.207.173.58:33601]
    at Pool.<anonymous> (C:\Users\myUser\OneDrive\Js Projects\myApp\backend\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (C:\Users\myUser\OneDrive\Js Projects\myApp\backend\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (C:\Users\myUser\OneDrive\Js Projects\myApp\backend\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:1176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

	
**What is the expected behavior?**
Instead of a fatal error the method should consolidate the connection of the app with the database.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 11.1.0, Mongoose: 5.3.12

**Comment by mhombach** [comment]
Can you test the connection with some clientsoftware as "MongoDB-Compass" from the same computer you are executing node? The issue may be caused by firewall-settings or slightly incorrect connection-data.
Connecting with mongoose works just fine as me and hundreds of user can confirm to you, so the problem must be within a different part of your application/infrastructure.

**Comment by leandrosoares6** [comment]
I even thought it was some rule from my Firewall, busy port or something. But I downgraded to version 5.3.9 and returned to normal operation. I'll try your suggestion.

**Comment by leandrosoares6** [comment]
> Can you test the connection with some clientsoftware as "MongoDB-Compass" from the same computer you are executing node? The issue may be caused by firewall-settings or slightly incorrect connection-data.
> Connecting with mongoose works just fine as me and hundreds of user can confirm to you, so the problem must be within a different part of your application/infrastructure.

I did as you suggested and managed to connect seamlessly on MongoDB Compass.

**Comment by mhombach** [comment]
Hmm.... 2 references you should check out:
[This reference](https://stackoverflow.com/questions/40780131/mongoose-connection-error-when-connecting-to-mlab) mentions that if your password or username contains `@` it may not work as you would expect.
On [this reference](https://gist.github.com/arshdkhn1/b402fcada5117b8a2f17859a753bf9b9) a user posted recommenced connection settings for mLab.
Try both of those and tell us if it worked :)

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate. Can you confirm whether your username or password contains any special characters, like `@` or `:` or `&`?

**Comment by leandrosoares6** [comment]
@vkarpov15 my password and username does not contain these characters, no special characters.

**Comment by vkarpov15** [comment]
Below script works fine for me against a free tier mlab instance running MongoDB 3.6.6 with Mongoose 5.3.13

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7243`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(`mongodb://user:pass@ds14XYZ.mlab.com:43737/plugins`, { useNewUrlParser: true });
}
```

Can you confirm your MongoDB server version and what mlab tier you're using? Also, can you confirm you haven't added any [IP whitelist rules](https://docs.mlab.com/security/)?
