### ISSUE TITLE
how to manually create indexes in mongoose?

### ISSUE THREAD

**Issue by xxyyzz2050** [Automattic/mongoose#7247]
how can I excute db.collection.createIndex() via mongoose, and what "db" refers for? is it refers for mongoose.connection or model ar schema?

**Comment by vkarpov15** [comment]
Use [`Model.collection.createIndex()`](https://mongoosejs.com/docs/api.html#model_Model-collection) . `Model.collection` gives you access to the [MongoDB native driver collection](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html) that this model uses.
