### ISSUE TITLE
Command find requires authentications on Cluster

### ISSUE THREAD

**Issue by chhatrachhorm** [Automattic/mongoose#7250]
**Do you want to request a *feature* or report a *bug*?**
Report a BUG
**What is the current behavior?**
Mongoose/Mongo command find requires authentications.
The setup is working fine until sometimes mongo return MongoError.
**If the current behavior is a bug, please provide the steps to reproduce.**

Not possible. I can only provide this log
{"operationTime":"6623943767869095937","ok":0,"errmsg":"command find requires authentication","code":13,"codeName":"Unauthorized","$clusterTime":{"cluste
rTime":"6623943767869095937","signature":{"hash":"khZb6D6CBTw1RsN+Gs1QlE+7vno=","keyId":"6600193315981754370"}},"name":"MongoError"}
**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
"node": "8.11.2"
"npm": "5.6.0"
"mongoose": "^5.3.12"

**Comment by vkarpov15** [comment]
We can't make any progress on this issue with just this log message. Can you describe your setup a bit more?

1) Standalone mongod, replica set, or sharded cluster?
2) Node.js server, Lambda, or something else?
3) What sort of operations does your application do?
4) Are there any disconnects around when this log happens?
5) What is your application doing when this log message happens?

**Comment by dbalodia** [comment]
I am facing the same issue. While I am connecting to mongo atlas. From mongo shell, I am able to fetch and create data but using mongoose it is throwing an error.

Mongoose v -  ^5.0.0-rc0
MongoDb Shell - v4.0.9

{ domain: 'proderp.cannaonblock.com', status: 'Active' }
==================================== { MongoError: command find requires authentication
    at queryCallback (/home/dheeraj/Desktop/Code/aob-iam-service/node_modules/mongodb-core/lib/cursor.js:223:25)
    at /home/service/node_modules/mongodb-core/lib/connection/pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'MongoError',
  message: 'command find requires authentication',
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1556776476 },
  ok: 0,
  errmsg: 'command find requires authentication',
  code: 13,
  codeName: 'Unauthorized',
  '$clusterTime': 
   { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1556776476 },
     signature: { hash: [Object], keyId: [Object] } } }

**Comment by vkarpov15** [comment]
@dbalodia it looks like you're trying to connect to a mongodb instance that requires authentication and not authenticating. Please open up a new issue and follow the issue template.
