### ISSUE TITLE
Feature suggestion: accept models in addition to strings for 'ref' option on schemas

### ISSUE THREAD

**Issue by connorspeers** [Automattic/mongoose#7253]
Pretty low priority, but ran into a problem that confused me for awhile and thought it would be worth mentioning here.

**What is the current behavior?**
Currently, the 'ref' schema option only accepts string values (<a href="https://github.com/Automattic/mongoose/blob/master/lib/helpers/populate/validateRef.js" target="_blank">and functions</a> I guess?). In the case where a defined model isn't imported anywhere in application code but is still required to be a registered model for use as references in other models, mongoose will throw a MissingSchemaError (as it should).

For example:

```javascript
// src/models/User.js
// This file isn't imported anywhere, so the model never gets registered
import mongoose from 'mongoose'

const userSchema = new mongoose.Schema({
  name: String,
})

export default mongoose.model('User', userSchema)
```

```javascript
// src/models/Post.js
// This file is imported in application code, so this model is registered
// When the model is used, however, mongoose throws a MissingSchemaError because
// the 'User' model isn't registered
import mongoose from 'mongoose'

const postSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },
})

export default mongoose.model('Post', postSchema)
```

The workaround solution to this is, of course, to make sure all models are imported in the application code at some point before they are used. However, I think a cleaner method would be to allow passing models as the value for the ref; this would allow/encourage models to express dependency on one another declaratively via import/require statements. Here's what I mean:

```javascript
// src/models/Post.js
import mongoose from 'mongoose'
import User from './User'

const postSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: User,
  },
})

export default mongoose.model('Post', postSchema)
```

The problem I ran into was that I was doing the above thinking it was standard syntax, and nothing was throwing an error (the <a href="https://github.com/Automattic/mongoose/blob/master/lib/helpers/populate/validateRef.js" target="_blank">validateRef</a> helper in the mongoose codebase accepts functions as valid values). But when I wanted to populate those reference fields on document instances, population would fail silently and the fields would stay ObjectIDs. Likewise, when setting those fields with model instance values, the model instance values would be typecast to ObjectIDs and the fields would not be model instances as I had expected.

To get the import-model-dependencies syntax I wanted while keeping population functionality, I've gotten into the habit of doing the following as a compromise, which is arguably just as simple as the above proposal:

```javascript
// src/models/Post.js
import mongoose from 'mongoose'
import User from './User'

const postSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: User.modelName,
  },
})

export default mongoose.model('Post', postSchema)
```

mongoose version: 5.3.11
node version: 11.1.0
mongodb version: 4.0.4

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix. I had assumed this worked because we allow passing a [model as a param to `populate()`](https://mongoosejs.com/docs/api.html#model_Model.populate):

```javascript
const post = await Post.findOne().populate({ path: 'user', model: User });
```
