### ISSUE TITLE
Sort, limit and skip do not work on large amounts of data.

### ISSUE THREAD

**Issue by samuelcecilio** [Automattic/mongoose#7258]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Sort, limit and skip do not work on large amounts of data.

````
MongoError: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
````

**If the current behavior is a bug, please provide the steps to reproduce.**

````js
const items = await Item.find(filter, projection).sort(sort).limit(limit).skip(limit * (page - 1)).lean().exec()
````

The MongoDB documentation suggests the use of indexes.

After creating the indexes, the following command ran through the terminal. But it did not work through mongoose.

````js
db.items.find({ disabled: false }, { _id: 0, __v: 0, disabled: 0 }).sort({ name: 1 }).limit(50).skip(50 * (1600 - 1)).pretty()
````

````
db.items.stats()
{
	"size" : 59118985,
        "nindexes" : 4,
	"totalIndexSize" : 2576384,
	"indexSizes" : {
		"_id_" : 729088,
		"itemId_1" : 819200,
		"disabled_1" : 290816,
		"name_1" : 737280
	}
}
````

**What is the expected behavior?**

It is expected that the moongose use the indexes to avoid the error.

**Please mention your node.js, mongoose and MongoDB version.**

node v10.13.0
mongoose 5.3.12
MongoDB 4.0.4

**Comment by tarun1793** [comment]
Mongoose can not add indices by itself. You will need to define the indices yourself, after evaluating your query. If this happens even after setting all the required indices, you can either increase mongodb's RAM buffer, or set the `allowDiskUse` to true

**Comment by samuelcecilio** [comment]
Worked with native driver

````js
// models/items.js

name: { type: String, required: true, index: 'text' }
````

````js
// test.js

const express = require('express')
const app = express()

const MongoClient = require('mongodb').MongoClient
const url = 'mongodb://localhost:27017'
const dbName = 'blitz'
const client = new MongoClient(url)

app.get('/', function (req, res, next) {
  client.connect(function (err, client) {
    if (err) { return next(err) }
    const db = client.db(dbName)

    const sort = { name: 1 }
    const limit = 50
    const page = 1596

    db.collection('items')
      .find({ disabled: false })
      .sort(sort)
      .limit(limit)
      .skip(limit * (page - 1))
      .toArray(function (err, result) {
        if (err) { return next(err) }

        res.send(result)
      })
  })
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
````

**Comment by tarun1793** [comment]
Just to confirm, the index on name existed even when ran via mongoose? In other words, if you were to re-run the mongoose sort, it would again throw the same error?

**Comment by samuelcecilio** [comment]
I can use the skip, sort and limit combination up to a certain number of pages. Then the error appears.

With the native driver, I can navigate all pages.

**Comment by vkarpov15** [comment]
@samuelcecilio it looks like you have separate indexes on `name` and `disabled`. Try creating a [compound index](https://mongoosejs.com/docs/api.html#schema_Schema-index) on `{ disabled, name }`:

```javascript
schema.index({ disabled: 1, name: -1 });
```

That way MongoDB can use a single index for both filtering and sorting.

**Comment by samuelcecilio** [comment]
That easy? Thanks!
