### ISSUE TITLE
cannot use findByIdAndUpdate inside mongoose middleware

### ISSUE THREAD

**Issue by kayali1411** [Automattic/mongoose#7260]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
User.findByIdAndUpdate is not a function.

**If the current behavior is a bug, please provide the steps to reproduce.**
I want to update existing document in User collection after creating a new charity document using post middleware.

**Please mention your node.js, mongoose and MongoDB version.**
node.js version 10.13.0
MongoDB version 3.2

**Code**
```
router.post('/add', auth, (req, res) => {
    let body = _.pick(req.body, ['name', 'description', 'foundedYear', 'city', 'location', 'address', 'phoneNumber', 'icon']);
    body._userId = req.user.id;

    let charity = new Charity(body);

    charity.save().then((charity) => {
        return res.json({success, charity});
    }).catch((e) => {
        return res.json({error, message: e.message});
    });
});
```
```
const User = require('./user');
charitySchema.post('save', function(next) {
    User.findByIdAndUpdate(this._userId, {accountCreated: true}).then(() => {
        next();
    });
});
```

**Comment by tarun1793** [comment]
Can you post content of the `./user` file? Coz the post save should be within the model schema definition.

**Comment by kayali1411** [comment]
@tarun1793 
I found a solution by using this
```
let User = this.model('User');
```
but currently I got another issue, I am unable to call next
**error message: next is not a function**

**Comment by tarun1793** [comment]
this is the format for post hooks, taken from docs
schema.post('save', function(doc, next) {
  setTimeout(function() {
    console.log('post1');
    // Kick off the second post hook
    next();
  }, 10);
});
```
// Will not execute until the first middleware calls `next()`
schema.post('save', function(doc, next) {
  console.log('post2');
  next();
});
```

please note use of `next` is not mandatory in post middleware

**Comment by kayali1411** [comment]
@tarun1793 thanks for clarification.

**Comment by aryan-upa** [comment]
> @tarun1793 I found a solution by using this
> 
> ```
> let User = this.model('User');
> ```
> 
> but currently I got another issue, I am unable to call next **error message: next is not a function**

Hey, can you please let me know how to implement this solution. I am currently facing the same issue.
