### ISSUE TITLE
Prevent pre hooks firing

### ISSUE THREAD

**Issue by alexluong** [Automattic/mongoose#7262]
Hi. I wonder if there's a way to prevent `pre` hooks firing. I want to run a migration script, but it will run the pre hooks and mess up timestamps. I wonder if there's a way to prevent those from running.

Thanks!

**Comment by mhombach** [comment]
There are many ways i guess.

One way is, you could set a global variable (bool) "import" or "skipHooks" and check for its value in your pre hooks.
Or you could set your hook so that the timestamp only get's a new value if no value is provided and in your import script you provide the old timestamps.

**Comment by mhombach** [comment]
@alexluong Please be so kind and tell us if these are valid options for your usecase or if there maybe is something else that bothers you about those methods :)

**Comment by alexluong** [comment]
Thanks for your response. I'm still not clear on what you mean on those methods. As for right now since I haven't used the middlewares heavily, I just move the timestamps back to the update call.

However, as for `mongoose`, may I suggest having an options to bypass pre hooks? Something like this:

```
Model.findByIdAndUpdate(
  id,
  body,
  {
    disableHooks: {
      save: true,
      findByIdAndUpdate: true
    }
  }
)
```

I think those are the most intuitive for me as a user, and I don't think it would be too hard to implement.

**Comment by vkarpov15** [comment]
Are you using [Mongoose's built-in timestamps](https://mongoosejs.com/docs/guide.html#timestamps) or your own timestamps? If you're using Mongoose's native timestamps, you can [set `{ timestamps: false }` on your query](https://mongoosejs.com/docs/api.html#query_Query-setOptions):

```javascript
Model.findOneAndUpdate(filter, update, { timestamps: false });
```

**Comment by mhombach** [comment]
@alexluong see the given answer above or you could also create a virtual attributes, which can be set/read like normal attributes but those aren't stored in the database. You could then create the virtual attribute `importProcedude` and in your import-script you set its value to `true`. In your hooks you can then `if` for that virtual attribute and if its value is `true` then you skip all hook-actions.
This applies for ALL possible scenarios, but if you are using the default timestamps, then the above answer is the way to go.

**Comment by alexluong** [comment]
Thank you all for the enthusiasm. I was using my own timestamps, so I couldn't use the `timestamps` option.

I believe using virtual attribute would be able to solve my problem. It's quite a feature that I didn't know exists before now.

Regardless, thank you all for the help!!
