### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by Altiano** [Automattic/mongoose#7263]
```
 const models = [
    Model1.createCollection(),
    ....
    Model25.createCollection(),
  ]

await Promise.all(models)

```

Simple.. There is (potential) memory leaks when running this all promises..
I need to ensure all collection is created when Node first run.
All the collection will use `transaction` API so they need to be sure that the collection is created first

**Comment by mhombach** [comment]
Can you provide further information on where you think a memory leak might happen?
From what i can see the collections are created and the `models` variable will be garbage collected after the scope is closed.

**Comment by Altiano** [comment]
I'm not sure where.. Node js just complain about it..

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 open listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by mhombach** [comment]
Took me 1 minute to google the message, please follow this link and tell us if this solved your problem or if your bug has another source:
https://www.reddit.com/r/javascript/comments/6b0qz0/asyncawait_possible_eventemitter_memory_leak/

**Comment by Altiano** [comment]
I use this code
```
connection.on('close', () => {
    connection.removeAllListeners();
});
```

The warning still exists.
My workaround is to increase the default max listeners:
```
require('events').EventEmitter.defaultMaxListeners = 25
```

When I try to create just <10 collection at the same time with `Promise.all()`, it's all fine.
But if more than that and the default max listeners not changed, the warning show up.

Could you experiment it yourself?
My guess the issue is because the connection is really fast to the localhost, and the fact that all the promises
executed almost the same time, the removal from event listeners is too late.

**Comment by mhombach** [comment]
I see... what i can tell you now is, that this issue has nothing to do with mongoose. It is related purely to nodeJS. See here for more Information: https://github.com/Automattic/mongoose/issues/1992

The `events` talked about are a nodeJS thing. You can guess that from your workaround:
`require('events').EventEmitter.defaultMaxListeners = 25`
The `events`-library has nothing to do with mongoose, it's a builtin library of nodeJS. And since changing something there makes the problem go away, the issue never really was mongoose.
From what i read now the "events" talked about are not Database-Events but "then"-events in JS.

> That's unfortunately by design - mpromise uses events internally so every time you call .then() that adds an event handler, hence the warning. Fixing mpromise is not a priority going forward since you can set your own promises library in >= 4.1.0. As a workaround in 3.8 you can shut this warning off with setMaxListeners() on the promise itself

and

> Just use mongoose.Promise = global.Promise; (if you're using node 4 and mongoose 4.1) and this issue should go away as specified in #1992 (comment)

Could it be that you are using some 3rd party promise-library and not the builtin Promise-library of the newest nodeJS-version?

**Comment by Altiano** [comment]
I don't use any 3rd party promise library.

**Comment by mhombach** [comment]
@Altiano please close this issue if there is nothing else to discuss on that topic :)

**Comment by mhombach** [comment]
@vkarpov15 just curious, do you think that this can be fixed in mongoose? I really thought that this is related directly to nodeJS :/

**Comment by vkarpov15** [comment]
I can't repro this, can you modify the below script to demonstrate this issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7263`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const models = [];
  for (let i = 0; i < 25; ++i) {
    models.push(mongoose.model(`Test${i}`, new Schema({})));
  }

  await Promise.all(models.map(m => m.createCollection()));
}
```

Output:

```
$ node gh-7263.js 
(node:29621) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
done
^C
$ 
```

No event emitter warnings.

**Comment by ammar-sayed-taha** [comment]
this issue shown up because of the URL is deprecated and will be removed soon so you can use this snippet code as an example I hope that help :)
```
mongoose.connect(URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true
}, (err) => {
    err ? console.log(`cannot connect to the database ;(`) : //if(err)
        console.log(`the database is connected and the port is ${process.env.PORT || 3030}`) //else
});
```
