### ISSUE TITLE
Error: on nested schema, date change detected where it should not

### ISSUE THREAD

**Issue by StphnDamon** [Automattic/mongoose#7264]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Updating a date field in a sub schema with the same **string** value triggers a modifiedPath whereas:
- updating the same field in the main schema does not trigger it
- updating with a Date object does not trigger it either

This behavior occurs since the v5.3.9 and is related to [gh-4224](https://github.com/Automattic/mongoose/issues/4224).

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const subSchema = new mongoose.Schema({
  date2: {type: Date}
});

const schema = new mongoose.Schema({
  date1: {type: Date},
  subSchema: {type: subSchema}
});

const Schema = mongoose.model('Schema', schema);

const date = '2018-11-22T09:00:00.000Z';
console.log('try to create new doc');

new Schema({
  date1: date,
  subSchema: {
    date2: date
  }
})
  .save()
  .then(doc => {

    console.log(doc.modifiedPaths());
    // [] -> OK

    doc.set('date1', date);
    doc.set('subSchema.date2', date);

    console.log(doc.modifiedPaths());
    // expected : []
    // actual: [ 'subSchema', 'subSchema.date2' ] (and what difference with date1?)

  });
```

**What is the expected behavior?**
Even not casted, the same date, in a sub schema, should not trigger a modifiedPath.

**Please mention your node.js, mongoose and MongoDB version.**
- node  v10.5.0
- mongoose v5.3.9
- mongodb v3.2.10

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap
