### ISSUE TITLE
Can't connect to mongodb inside docker with 5.3.13

### ISSUE THREAD

**Issue by HRK44** [Automattic/mongoose#7270]
**Do you want to request a *feature* or report a *bug*?**
Bug ?

**What is the current behavior?**

My mongo docker is not connecting anymore, this is the issue :

mongodb       | 2018-11-21T14:24:50.356+0000 I ACCESS   [conn3] Supported SASL mechanisms requested for unknown user 'testroot@data'
mongodb       | 2018-11-21T14:24:50.359+0000 I ACCESS   [conn3] SASL SCRAM-SHA-1 authentication failed for testroot on data from client 172.28.0.3:55362 ; UserNotFound: Could not find user testroot@data
mongodb       | 2018-11-21T14:24:50.361+0000 I NETWORK  [conn3] end connection 172.28.0.3:55362 (0 connections now open)

**If the current behavior is a bug, please provide the steps to reproduce.**
It was working fine before, I don't understand why it's not finding the user anymore.

**What is the expected behavior?**
Find the user and create a connection to the DB

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS : 10
Mongo: 4.0.3
Mongoose: 5.3.13

It was working fine so far with mongoose 5.3.12.... I didn't think that a version bump would break anything :/

**Comment by HRK44** [comment]
Some code on for the connect :

```javascript
    mongoose.connect(DB_HOST,
        {
            user: DB_USER,
            pass: DB_PASSWORD,
            auth: {
                authdb: DB_AUTHDB
            },
            autoIndex: NODE_ENV === 'dev',
            useNewUrlParser: true,
            reconnectTries: Number.MAX_VALUE,
            reconnectInterval: 500, // Reconnect every 500ms
            poolSize: 10 // Maintain up to 10 socket connections
    }
);
```

**Comment by mhombach** [comment]
Please use some client to check if it's really mongoose that is failing here.
Try downloading "MongoDB Compass (community edition)" and try connection with the exact same login data and connection options.
Also rethink if you maybe changed something else and just have forgotten about it ;)

**Comment by HRK44** [comment]
I found a work around, I removed the DB name from the connection string :
``DB_HOST=mongodb://mongodb:27017/mydb`` -> ``DB_HOST=mongodb://mongodb:27017`` and I set up the **optional** ``dbName`` attribute in the mongoose connection params to ``mydb``.

So it seems that the issue comes from the mongodb-core package, the new way they parse the connection string.

**Comment by HRK44** [comment]
Ok so from https://jira.mongodb.org/browse/NODE-1772 it looks like they *fixed* the default auth DB, so now it is actually pulling whatever DB name is after the ``/`` in the connection string.

Since I had ``/mydb``, it's trying to authenticate using ``mydb``, but according to the [mongo docs](https://docs.mongodb.com/manual/reference/connection-string/), the db after the ``/`` should be the auth DB and not the default selected DB (which I thought it was).

I switched my connection string to ``mongodb://mongodb:27017/admin' and this works again.

**Comment by NewEraCracker** [comment]
Just out of curiosity if you change DB_HOST to mongodb://mongodb:27017/mydb?authSource=admin does it work?

**Comment by HRK44** [comment]
@NewEraCracker it works with ``/mydb?authSource=admin`` but at this point I'm wondering what's the point of ``/mydb``.

Some testing (with mongoose 5.3.13) :
- connection string without any ``/db`` and ``auth: { authdb: 'admin'}`` doesn't work
- connection string with ``/admin`` (auth db) works
- connection string with ``/mydb?authSource=admin`` works (what's the point of ``mydb`` in this case?

It doesn't seem that the ``auth`` object is used anywhere, especially the ``auth: {authdb: 'admintest1'}`` ?

**Comment by HRK44** [comment]
This is my final setup that works with 5.3.13 (without the auth object) :

```javascript
    mongoose.connect(DB_HOST, //mongodb://mongodb:27017/admin (admin IS THE AUTH DB)
        {
            user: DB_USER, //testroot
            pass: DB_PASSWORD, //password
            dbName: DB_NAME, // 'mydb' which is the default selected DB
            autoIndex: NODE_ENV === 'dev',
            useNewUrlParser: true,
            reconnectTries: Number.MAX_VALUE,
            reconnectInterval: 500, // Reconnect every 500ms
            poolSize: 10 // Maintain up to 10 socket connections
        }
    );
```

**Comment by NewEraCracker** [comment]
> @NewEraCracker it works with `/mydb?authSource=admin` but at this point I'm wondering what's the point of `/mydb`.

Maybe selecting the mydb as the database to do read and write operations against...

**Comment by HRK44** [comment]
@NewEraCracker That's what I thought too at the beginning, but here is the link from the mongo docs : 

https://docs.mongodb.com/manual/reference/connection-string/

> /database | Optional. The name of the database to authenticate if the connection string includes authentication credentials in the form of username:password@. If /database is not specified and the connection string includes credentials, the driver will authenticate to the admin database.

So it's about the auth db and not the default db to use for collections.

**Comment by NewEraCracker** [comment]
https://docs.mongodb.com/manual/reference/method/connect/

« The following example instantiates a new connection to the MongoDB instance running on the localhost interface and returns a reference to myDatabase:
```db = connect("localhost:27017/myDatabase")```

**Comment by HRK44** [comment]
@NewEraCracker It's actually confusing, but I think that even in this piece of doc, ``/myDatabase`` refers to the auth DB.

**Comment by vkarpov15** [comment]
@HRK44 `/myDatabase` is the authentication database, and the database that Mongoose will use for storing documents. That's what the point of it is. Since you specify [the `dbName` option](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect) (https://github.com/Automattic/mongoose/issues/7270#issuecomment-441239121), you don't need to specify the db name in the connection string.
