### ISSUE TITLE
Populate nested array with dynamic references not working

### ISSUE THREAD

**Issue by clasqui** [Automattic/mongoose#7273]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When populating **an array of an array** of documents using dynamic references (using refPath), population gets done but at the end _item_ equals `null` in returned document.

**If the current behavior is a bug, please provide the steps to reproduce.**
You need an array of objects that have another array of elements you need to populate, using a field inside for the ObjectId and another field to indicate the model we will use to populate.

Conflictive part of the schema used:
```javascript
  equips: [
    {
      item: { type: Schema.Types.ObjectId, ref: 'equips' }, // <-- ignore this 
      assistents: [
        {
          item: { type: Schema.Types.ObjectId, refPath: 'equips.assistents.col' }, // <-- THIS is the populate that fails
          rol: String,
          col: String, // <-- here we can find the model to populate with
          convocat: Boolean,
          confirmat: Boolean,
          validat: Boolean
        }
      ]
    }
  ],
```
And now part of the logic that invokes the populate:
```javascript
for (var i = 0; i < doc.equips.length; i++) {
  for (var j = 0; j < doc.equips[i].assistents.length; j++) {
    doc.populate({ path: 'equips.' + i + '.assistents.' + j + '.item', populate: { path: 'idUsuaria', select: 'desc' } });
  }
}
```
And later I execute the `execPopulate()` on the document instance.

**What is the expected behavior?**
Getting the document with the indicated paths populated

**Please mention your node.js, mongoose and MongoDB version.**
mongodb version v3.6.6
mongoose version 5.3.13
nodejs v8.10

#### Investigation
After a little bit of debugging I realized that the `modelsMap` that returns the function `getModelsMapForPopulate` it's not correct.  In my case, that we can find ~13 paths populated using 2 different models, the modelsMap gets filled with only one of the 13 IDs and (but repeated 13 times) and using the wrong model (although it is divided in two different arrays, as there are two models):

```
[
  ["5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe"],
  ["5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe","5bb47cd4724c8263c770cabe"]
]
```
and I could even find another strange behaviour in the `getModelsMapForPopulate()`, in the following piece of code:
```javascript
try {
  Model = originalModel && originalModel[modelSymbol] ?
  originalModel :
  modelName[modelSymbol] ? modelName : model.db.model(modelName);
} catch (error) {
  return error;
}
```
given that we have `k`, that iterates through the modelNames **starting from the top**, and that we have `modelName = modelNames[k]` that equals the model that corresponds to the last path being populated, which is not the current one;  after executing the `Model` assignation, tie condition falls to `model.db.model(modelName)` which equals **the incorrect model** (the last one in the array), because in the first condition `originalModel[modelSymbol]` equals `undefined`.

It then continues the iteration filling the map with all the same Id but with the models not being applied correctly.

**Comment by vkarpov15** [comment]
I can confirm this is a bug, but I'm also curious why you're looping over each element in the array and populating every element in the array? That shouldn't be necessary, see the below script:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7273`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const Item1 = mongoose.model('Item1', new Schema({ name: String }));
  const Item2 = mongoose.model('Item2', new Schema({ name: String }));
  
  const schema = new Schema({
    equips: [{
      item: { type: Schema.Types.ObjectId, ref: 'equips' }, // <-- ignore this 
      assistents: [ 
        {
          item: { type: Schema.Types.ObjectId, refPath: 'equips.assistents.col' }, // <-- THIS is the populate that fails
          rol: String,
          col: String, // <-- here we can find the model to populate with
        }
      ]
    }]
  });
  
  const Model = mongoose.model('MyModel', schema);
  
  const item1 = await Item1.create({ name: 'item1' });
  const item2 = await Item2.create({ name: 'item2' });
  
  await Model.create({
    equips: [{
      assistents: [{ item: item1._id, col: 'Item1' }, { item: item2._id, col: 'Item2' }]
    }]
  });
  
  // Do this instead:
  let doc = await Model.findOne().populate('equips.assistents.item');
  
  console.log(doc.equips[0].assistents); // both `item1` and `item2` populated

  // Not this:
  doc = await Model.findOne();
  
  for (let i = 0; i < doc.equips.length; ++i) {
    for (let j = 0; j < doc.equips[i].assistents.length; ++j) {
      doc.populate('equips.' + i + '.assistents.' + j + '.item');
    }
  }

  doc = await doc.execPopulate();

  console.log(doc.equips[0].assistents); // `item2` not populated
}
```

**Comment by clasqui** [comment]
Definetely, I will change that piece of code.  Thanks for the tip!  
Anyway, if you try to reproduce this bug please **still use the code I gave to you** because there is another part on my logic (where the bug is also present) where I can't populate the whole array of subdocuments because I need to check some thing first for each.
