### ISSUE TITLE
Document collection override with `strict: false` causes process crash

### ISSUE THREAD

**Issue by dbellavista** [Automattic/mongoose#7276]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**

Mongoose schema doesn't allow to set `collection` as field. However, by using `strict: false`, one can create using `new Model` or `Model.create` a document with an overrided `collection`.

In most common scenario, this would cause a process crash (`uncaughtException`).

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/dbellavista/08abb3e912e61e829a87b4fb5729ac64

**What is the expected behavior?**

The creation should fail by rejecting the promise and/or invoking the callback with an error

**Please mention your node.js, mongoose and MongoDB version.**

Node 10, mongoose 5.3.13, mongoDB 3.6

**Comment by vkarpov15** [comment]
Thanks, this is a pretty bad bug. Will fix ASAP.
