### ISSUE TITLE
find() method not returning array of objects

### ISSUE THREAD

**Issue by Enado95** [Automattic/mongoose#7278]
I'm using mongoose 5.3.13

When use I use the find() method to retrieve documents, my Array of objects are displayed as below in phone number property. Instead, [ [Object] ] is returned even after i explicitly define the schema. Ive included code below as well. `
![image](https://user-images.githubusercontent.com/25810206/48954979-bda92580-ef19-11e8-91a0-a3f538e281c3.png)

`const customerSchema = new mongoose.Schema({
    PID: Number,
    PERSON_NAME: String,
    PERSON_DOB: String,
    PERSON_TRN: String,
    address: {
        PERSON_PRIMARY_STREET_ADDRESS_1: String,
        PERSON_PRIMARY_CITY: String,
        PERSON_PRIMARY_PARISH: String,
    },
    emailAddress: [String],
    phoneNumber: [{
        Mobile_Number_IFormat: String,
        Mobile_Number_LFormat: String   
    }]
});

const Customer = mongoose
    .model('Customer', customerSchema, 'Customers');

async function getCustomers() {

const result = await Customer.find().select({PERSON_NAME: 1, PERSON_DOB: 1,phoneNumber: 1, '_id': 0}).limit(3);
    console.log(result);    
}

getCustomers();`

if i use the findById() method then everything is returned perfectly. 
Please help!

**Comment by mhombach** [comment]
I can't reproduce that behaviour with the information you providedd.

Can you please provide a complete script to reproduce the issue, including inserting one or more dummy-entries?

**Comment by vkarpov15** [comment]
Just do `console.log(result[0])`. Or `console.log(require('util').inspect(result, { depth: 20 }))`. `console.log()` cuts off at a certain depth by default, `depth: 20` will make the objects show up.
