### ISSUE TITLE
orFail() does not work with findOneAndUpdate()

### ISSUE THREAD

**Issue by greengiraffe** [Automattic/mongoose#7280]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

When `orFail(new Error())` is chained on a `findOneAndUpdate()` query, **no error is thrown when no document is found.** Instead the query result is `null` as if `orFail()` was not used. This is contrary to one of the examples given for `orFail()` in the docs (https://mongoosejs.com/docs/api.html#query_Query-orFail):

```js
// Throws "Not found" error if no document was found
await Model.findOneAndUpdate({ foo: 'bar' }, { name: 'test' }).
  orFail(() => Error('Not found'));
```

The issue is _probably_ (not tested) also observable with `findOneAndDelete()`, `findOneAndRemove()` and other operations that are not listed in this switch statement: https://github.com/Automattic/mongoose/blob/master/lib/query.js#L3713

**If the current behavior is a bug, please provide the steps to reproduce.**

See code example above (taken from the Mongoose 5.3.13 docs).

**What is the expected behavior?**

An error should be thrown if the no document was found in a `findOneAndUpdate().orFail(new Error())` scenario. This _might_ also apply to other operations as mentioned above.

**Please mention your node.js, mongoose and MongoDB version.**

Node: `10.13.0`
MongoDB: `3.1.10`
Mongoose: `5.3.13`

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate asap
