### ISSUE TITLE
findByIdAndUpdate/FindOneAndUpdate are setting __v to null

### ISSUE THREAD

**Issue by brianmtully** [Automattic/mongoose#7284]
node.js : v8.11.1
mongodb: v3.6.8
mongoose: v5.3.13

After performing a findByIdAndUpdate or a findOneAndUpdate (using the _id in query) on a document the saved document then has a __v value of null. This causes a MongoError: Cannot apply $inc to a value of non-numeric type on every subsequent save of the document. 

Example to illustrate:
1. __v has a value of 1.
2. execute mongoose.model('Vehicle').findByIdAndUpdate(doc.vehicleID, { price: 500}, function(err, vehicle){ });
3. document is updated but now __v has a value of null
4. All updates after this error

This seems like a major bug, I dont think __v should ever be set to null.

Thanks.

**Comment by brianmtully** [comment]
This commit on October 18th

https://github.com/Automattic/mongoose/commit/5f6bb9a9d6f38fc27d6ff49c051e02d87cf66cb4#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfa

specifically the following section in _decorateUpdateWithVersionKey, are what are causing the bug. Since I am not using the upsert option, the if-statement is false and returns.

`
function _decorateUpdateWithVersionKey(update, options, versionKey) {
  if (!versionKey || !get(options, 'upsert', false)) {
    return;
  }
`

**Comment by brianmtully** [comment]
@vkarpov15 if I remove the `!get(options, 'upsert', false)` from the if-statement it seems to work. I'm not sure the reasoning for the change to the if-statement.

**Comment by brianmtully** [comment]
Looks like this has been an issue for much longer. I am trying to upgrade from 4.X to 5.X and Im rolling back thru the 5.X versions and getting the same issue

**Comment by brianmtully** [comment]
How is this not a critical bug? Using findOneAndUpdate makes basically corrupts the document

**Comment by brianmtully** [comment]
After more troubleshooting, I think this is actually caused by the mongoose-history package

**Comment by niftylettuce** [comment]
I got the same issue.  I don't think it's just `mongoose-history` @briancolinger 	

cc @vkarpov15

**Comment by vkarpov15** [comment]
@niftylettuce please open up a separate issue with some code samples :+1:
