### ISSUE TITLE
Better documentation of sub-documents

### ISSUE THREAD

**Issue by aymericbouzy** [Automattic/mongoose#7291]
**Do you want to request a *feature* or report a *bug*?**

documentation

In issue #7283 , we've identified documentation should be improved to give more details on these questions : 

* what is the default value when you declare a sub-document with a POJO
* what is the default value when you declare a sub-document with a sub schema
* how to define a value by default when you declare a sub-document with a sub schema
* when should you prefer using a POJO and when a sub schema when declaring a sub-document

**Comment by aymericbouzy** [comment]
I'm ready to open a PR if a contributor tells me it has chances of being accepted 😉

**Comment by vkarpov15** [comment]
Sounds like an excellent PR :+1: [This file](https://github.com/Automattic/mongoose/blob/master/docs/subdocs.jade) is where you'll want to make the changes.
