### ISSUE TITLE
Saving document when selecting specific fields fails.

### ISSUE THREAD

**Issue by azampagl** [Automattic/mongoose#730]
Saving a document that was loaded with a specific set of fields fails if a required field was left out.

eg.

User.findById(_id, ['_id', 'email', 'locale', function(err, user) { ... });

Now there is a document (user) with only those particular fields.  Upon saving, validation errors occur for fields that are required, but weren't loaded (say I have a required password field, but didn't want to load it).

I was hoping this was possible based on your comments in the api "we can determine the MINIMUM set of dirty data that we want to send to MongoDB on a Document save."  Is there any way to get the save to transparently ignore required fields if they weren't loaded in the first place?

**Comment by mostafaD** [comment]
i have faced the same problem and just fixed it by adding to the selection '__v'
this error happened to me a lot but i couldn't produce it easily
i noticed that it happen if you take a long time before saving
example
`var m = require('mongoose');
m.connect('mongodb://localhost:27017/mongoose-test');

var user;

user = new m.Schema({
    nick: {
        type: String,
        required: true
    },

    bla: {
        firstName: {
            type: String,
            required: true
        }
    }
});

m.model('user', user);

var UserModel = m.model('user');

UserModel.findOne({}, ['bla'], function(err, userDoc) {
    console.error(userDoc);
    setTimeOut(function(){
      userDoc.save(console.error);
    }, 5000)
    

});

console.error(m.version);`
