### ISSUE TITLE
Model.deleteOne always reports 0 documents deleted

### ISSUE THREAD

**Issue by sircody01** [Automattic/mongoose#7300]
Maybe I'm missing something, but the result returned by `Model.deleteOne` always reports 0 documents deleted, even when it actually deleted one. Whether or not a document was deleted the result returned is this JSON:

`{ n: 0, ok: 1 }`

I expected the value of n in the JSON to be either 0 or 1 depending on whether or not it found and deleted a document matching the query criteria.

Note that `Model.deleteMany` correctly reports how many documents were deleted i.e. n correctly reflects the number of documents deleted.

Node.js : 8.12.0
MongoDB : 3.1.10
mongodb-core: 3.1.9
Mongoose : 5.3.14

Sample code:

```
    public deleteMonitor(req: Request, res: Response) {
        SelGridMon.deleteOne({ User: req.params.user }, (err) => {
            if (err) {
                res.send(err);
            }
        })
            .then(result => {
                console.log(result);
                if (result.n === 0) {
                    res.sendStatus(404);
                } else {
                    res.setHeader('Access-Control-Allow-Origin', '*');
                    res.json({ message: 'Successfully deleted monitor!' });
                }
            });
    }
```

**Comment by mhombach** [comment]
I cannot reproduce that issue:
```js
async function run() {
	await mongoose.connect(connectionString);
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ name: String });
	const User = mongoose.model("User", userSchema);
	await User.create({ name: "a"});
	await User.create({ name: "b"});
	await User.create({ name: "c"});
	let result = await User.deleteOne({name: "b"});
	console.log("result=" + JSON.stringify(result));
	process.exit(0);
}
```
This returns `result={"n":1,"ok":1}`.
I have tried that with version 5.3.13 and 5.3.14, but print the same result.
Can you try to reproduce your issue with my example code? Maybe your issue is related to something else.

**Comment by sircody01** [comment]
Interesting you're unable to reproduce this. It reproduces 100% reliably in my Angular app. Maybe it has something to do with the schema I'm using. I'll investigate this further later today and try your example code. I'm located in the US so expect a small delay relative to your time zone.

**Comment by mhombach** [comment]
Allright :)
And please try to add every possible information about any middleware/custom settings you are using with mongoose, because that might change behaviour of queries.

**Comment by sircody01** [comment]
Got it! It has something to do with having an index. Once I removed my index from the collection, then deleteOne started returning the result value I expected. Try this:

```
async function run() {
	await mongoose.connect(connectionString);
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ name: {
            type: String,
            required: 'Enter a username',
            index: true,
            unique: true
        }});
	const User = mongoose.model("User", userSchema);
	await User.create({ name: "a"});
	await User.create({ name: "b"});
	await User.create({ name: "c"});
	let result = await User.deleteOne({name: "b"});
	console.log("result=" + JSON.stringify(result));
	process.exit(0);
}
```

**Comment by sircody01** [comment]
Oh, and I forgot to mention I am using mongoose-valid8 v1.3.1.

**Comment by sircody01** [comment]
Also I'm creating the connection differently:

```
async function run() {
	await mongoose.connect(connectionString, {
            useNewUrlParser: true,
            useCreateIndex: true
        });
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ name: {
            type: String,
            required: 'Enter a username',
            index: true,
            unique: true
        }});
	const User = mongoose.model("User", userSchema);
	await User.create({ name: "a"});
	await User.create({ name: "b"});
	await User.create({ name: "c"});
	let result = await User.deleteOne({name: "b"});
	console.log("result=" + JSON.stringify(result));
	process.exit(0);
}
```

**Comment by mhombach** [comment]
When i am running the exact code you postet in your last comment, then i get the result of `result={"n":1,"ok":1}` so this also works for me.
I also installed `mongoose-valid8` (latest version) and uses that schema in the example code instead of the normal mongoose-schema and it still prints the same result (as it should be).
Can you please create a new `.js` file and test this exact code?:
```js
const mongoose = require("mongoose");
const { model, Schema } = require('mongoose-valid8');

const GITHUB_ISSUE = `gh7300`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
//const { Schema } = mongoose;

run()
.then(() => console.log("done"))
.catch(error => console.error(error.stack));

async function run() {
	await mongoose.connect(connectionString, {
			useNewUrlParser: true,
			useCreateIndex: true
		});
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ name: {
			type: String,
			required: 'Enter a username',
			index: true,
			unique: true
		}});
	const User = model("User", userSchema);
	await User.create({ name: "a"});
	await User.create({ name: "b"});
	await User.create({ name: "c"});
	let result = await User.deleteOne({name: "b"});
	console.log("result=" + JSON.stringify(result));
	process.exit(0);
}
```
If the result is NOT `result={"n":1,"ok":1}` on your pc, then maybe something with your packages is not correct. then try to create a clean project folder, install the latest versions of mongoose and the valid8 package and check again :)

**Comment by sircody01** [comment]
@mhombach I appreciate your efforts trying to repro this! Is it possible the version of MongoDB has something to do with it? I'm using MongoDB 4.0.4 on Windows. What version of MongoDB are you using?

**Comment by mhombach** [comment]
I am using mongoDB version 4.0.2.
Did you try to reproduce the issue with my exact example code from my post above with the latest version of `mongoose-valid8` installed and a clean test-db?

**Comment by sircody01** [comment]
Hi, not yet. 😄 It's only 7am here... I'm just starting my day. I will later on.

**Comment by sircody01** [comment]
@mhombach No repro using your suggested code, even while using the exact same physical node_modules files. I'm now trying to figure out what's the difference because it still repro's 100% of the time in my RESTful app. I'll update you once I come up with code you can use to repro this.

**Comment by sircody01** [comment]
Here's your repro. Note it's intermittent. Sometimes it does work as expected, but most of the time it does not work as expected:

```
const mongoose = require("mongoose");
const { model, Schema } = require('mongoose-valid8');

const GITHUB_ISSUE = `gh7300`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
//const { Schema } = mongoose;

run()
.then(() => console.log("done"))
.catch(error => console.error(error.stack));

async function run() {
	await mongoose.connect(connectionString, {
			useNewUrlParser: true,
			useCreateIndex: true
		});
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ User: {
			type: String,
			required: 'Enter a username',
			index: true,
			unique: true
		}});
	const User = model("User", userSchema);
	await User.create({ User: "a"});
	await User.create({ User: "b"});
	await User.create({ User: "c"});
        await User.deleteOne({ User: "b" }, (err) => {
        if (err) {
            console.log(err);
        }})
        .then(result => {
            console.log(result);
            if (result.n !== 1) {
                throw new Error("result.n isn't 1 as expected.");
                process.exit(1);
            }
        });
    process.exit(0);
}

```

Running this yields:

```
>node repro.js
{ n: 0, ok: 1 }
Error: result.n isn't 1 as expected.
    at User.deleteOne.then.result (C:\...\api\repro.js:36:23)
    at <anonymous>

```

**Comment by mhombach** [comment]
Wow.... i can now partly reproduce this.
I first ran your exact code, no changes were made.
Result: `{ n: 1, ok: 1 }`.
Then i just ran the code for a 2nd time:
Result: `{ n: 0, ok: 1 } Error: result.n isn't 1 as expected.`....

What i tested so far:

- This seems to be no timing issue: I waited around 10 seconds after each execution and the result still was wrong at random.
- I even restarted the MongoDB after each execution and it still failed at random (m y thought was that the mongodb-driver had some caching-issues)
- The order in which the execution is wrong/correct seems to be completely random

**Comment by mhombach** [comment]
@sircody01  Update: Can you check if this code gets you the correct result each time?
```javascript
const mongoose = require("mongoose");
const { model, Schema } = require('mongoose-valid8');

const GITHUB_ISSUE = `gh7300`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
//const { Schema } = mongoose;

run()
.then(() => console.log("done"))
.catch(error => console.error(error.stack));

async function run() {
	await mongoose.connect(connectionString, {
			useNewUrlParser: true,
			useCreateIndex: true
		});
	await mongoose.connection.dropDatabase();

	const userSchema = new Schema({ User: {
			type: String,
			required: 'Enter a username',
			index: true,
			unique: true
		}});
	const User = model("User", userSchema);
	await User.create({ User: "a"});
	await User.create({ User: "b"});
	await User.create({ User: "c"});
    let result = await User.deleteOne({ User: "b" }).exec();
    console.log("result: " + JSON.stringify(result));
    process.exit(0);
}
```
The only thing i edited is to use the query as a Promise and await it. In this code i don't use the callback. I executed it 10 times in a row with the correct result (n: 1).
Please test this and tell me if this works for you too, then we can try to analyze what's going wrong on the callback :)

**Comment by sircody01** [comment]
Yes! Modifying my code per your suggestion does work reliably. I still don't understand why my original code doesn't work as expected. I confess I'm very new to NodeJS and JavaScript (though I've been a C/C++/C# developer for decades). Callbacks I get, but I'm still trying to wrap my head around promises and how they work.

Here's my latest version that is working reliably:

```
    public async deleteMonitor(req: Request, res: Response) {
        const result = await SelGridMon.deleteOne({ User: req.params.user }).exec();
        console.log(result);
        if (result.n === 0) {
            res.sendStatus(404);
        } else {
            res.json({ message: 'Successfully deleted monitor: ' + req.params.user + '!' });
        }
    }
```

I still need to catch and handle fatal error's such as MongoDB is offline. Would you have any suggestions how that should be handled, a try catch block wrapping the deleteOne call?

My original code:

```
    public deleteMonitor(req: Request, res: Response) {
        SelGridMon.deleteMany({ User: req.params.user }, (err) => {
            if (err) {
                res.send(err);
            }})
            .then(result => {
                console.log(result);
                // Assume 1 record was deleted until the result.n problem is fixed
                // if (result.n === 0) {
                //     res.sendStatus(404);
                // } else {
                    res.json({ message: 'Successfully deleted monitor: ' + req.params.user + '!' });
                // }
            });
```

Note the original method is not async while the updated method is. To give you more context, this is being called from the router:

```
    public routes(app): void {
        // Grid Monitors
        app.route('/api/v1/selgridmon/:user')
            .delete((req: Request, res: Response, next: NextFunction) => {
                // middleware
                console.log(`Request from: ${req.originalUrl}`);
                console.log(`Request type: ${req.method}`);
                if (req.query.key !== API_SECRET_KEY) {
                    res.status(401).send('You shall not pass!');
                } else {
                    next();
                }
            }, this.gridMonController.deleteMonitor)
        ;
    }
```

And the routes are add in the main app.ts:

```
import * as express from 'express';
import * as bodyParser from 'body-parser';
import { Routes } from './routes/crmRoutes';
import * as mongoose from 'mongoose';
import { MONGODB_URI } from '../../util/secrets';

class App {

    public app: express.Application;
    public routePrv: Routes = new Routes();
    public mongoUrl = MONGODB_URI;

    constructor() {
        this.app = express();
        this.config();
        this.routePrv.routes(this.app);
        this.mongoSetup();
    }
```

Thank you for your assistance!
Cody

**Comment by vkarpov15** [comment]
@sircody01 that's because passing a callback and calling `.then()` on a query executes the query twice. So your code is executing two `deleteOne()`'s, not one. See [these docs](https://mongoosejs.com/docs/queries.html#queries-are-not-promises).
