### ISSUE TITLE
mongoose insertMany wont execute

### ISSUE THREAD

**Issue by sivatharan** [Automattic/mongoose#7308]
Node version v8.13.0
Mongoose 5.3.13"

i have try to insert **1 million** record 

`fs.createReadStream(config.uploadDir +'/'+req.body.filePath)
	    .pipe(csv({delimiter: ',',skip_empty_lines:true}))
	    .on('data', function(csvrow) {
			
			if(count !=0){ // aviod first header row from csv
				data.push({
					_id: csvrow[msisdnInx]+'_'+req.body.accountId,
					"msisdn" : csvrow[msisdnInx],
					"name" : (nameInx == undefined?"":csvrow[nameInx]),
					"email" : (emailInx == undefined?"":csvrow[emailInx]),
					"attributes" : prepareAttribute(mapObject,csvrow), // prepare dynamic object from csv file
					"accountId" : req.body.accountId,
					"createdBy" : req.user.email,
					"status" : 1,
					"createdAt" : new Date(),
					"updatedAt" : new Date()
			
				});
			}
			count++;		
	                
	    })
	    .on('end',function() {
			try {
				Contact.insertMany(data,{ ordered: false }, function(err, result) {
					var ids = [];
					if(err){
						ids = err.result.result.insertedIds;
					}else{
						ids = result; // get all ides form inserted one
					}
						{
						if(req.body.groupIds.length>0){
							insertContatcToGroup(req,ids);// insert in to ContactGroupUser
						}
					}
				})
			}catch (e) {
				console.info (e);
			 }	
			
		});`

but it wont execute
**no error 
no result**

**Comment by mhombach** [comment]
A few things:
- if you want to debug an issue and you get no error or warnings, then use `console.log` to print out the value of some important variables during runtime.
- if you encounter problems with mongoose, try to enable the debugging-option in mongoose, so you can see which queries mongoose executes.
- If you post something here, you may want to try to reduce your problem to some code-snippet that you can post here and which is complete (from importing mongoose to the end of execution).

Also: I think you named `insertContatcToGroup` wrong but that should throw an error if execution reaches that point.

Please try ou the things i mentioned and give feedback here, what the result is and if the problem still exists :)

**Comment by vkarpov15** [comment]
Try shutting off [`bufferCommands`](https://mongoosejs.com/docs/connections.html#buffering), you might not be connected to the db.
