### ISSUE TITLE
I need help with query 'find' pre middleware hooks.

### ISSUE THREAD

**Issue by zacharymorel** [Automattic/mongoose#7310]
Hello, 
I am in need of help.  I have a specific situation where I need to have my collection populated before the find query happens, so I can apply the filtered params the user inputs against the population ref's from other collections. 

I am trying to use the pre hook so I can populate the needed paths before the find query fires on the "SampleSchema". If I try to apply the filter to the SampleSchema without pre-populating the schema, the find can't correctly filter the results and it errors out.

```ERROR:  { CastError: Cast to ObjectId failed for value "Foo" at path "program" for model "Sample" ...}```

```
SampleSchema.pre('find', function() {
	console.log('HELLO I FIRED FIND PRE HOOK');
	this.populate('program history type status')
	// return next()
})
```
EDIT* 
Here's the population docs for reference: 
https://mongoosejs.com/docs/populate.html
*Scroll to the bottom*

How do I go about this? 

Thank you

**Comment by zacharymorel** [comment]
@mhombach 

Here is my "SampleSchema.

`let SampleSchema = new Schema({
    number: {
        type: Schema.Types.Number,
        required: true
    },
    type: {
        type: Schema.Types.ObjectId,
        ref: 'ROType',
        required: true
    },
    assignedTo: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: false
    },
    site: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: false
    },
    changedBy: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: false
    },
    originatedBy: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: false
    },
    reportedBy: {
        type: Schema.Types.ObjectId,
        ref: 'Contact',
        required: false
    },
    program: {
        type: Schema.Types.ObjectId,
        ref: 'Program',
        required: false
    },
    parts: [{
        type: Schema.Types.ObjectId,
        ref: 'PhysicalPart',
        required: false
    }],
    documents: [{
        type: Schema.Types.ObjectId,
        ref: 'Document',
        required: false
    }],
    category: {
        type: Schema.Types.ObjectId,
        ref: 'Category',
        required: false
    },
    severity: {
        type: Schema.Types.ObjectId,
        ref: 'Severity',
        required: false
    },
    status: {
        type: Schema.Types.ObjectId,
        ref: 'MROStatus',
        required: false
    },
    metric: {
        type: Schema.Types.ObjectId,
        ref: 'Metric',
        required: false
    },
    changeDate: {
        type: Schema.Types.Date,
        required: false
    },
    dueDate: {
        type: Schema.Types.Date,
        required: false
    },
    date: {
        type: Schema.Types.Date,
        required: false
    },
    closeDate: {
        type: Schema.Types.Date,
        required: false
    },
    replacementSentDate: {
        type: Schema.Types.Date,
        required: false
    },
    replacementSent: {
        type: Schema.Types.Boolean,
        default: false,
        required: true
    },
    joNumber: {
        type: Schema.Types.Number,
        required: false
    },
    problem: {
        type: Schema.Types.String,
        required: false
    },
    notes: {
        type: Schema.Types.String,
        required: false
    },
    description: {
        type: Schema.Types.String,
        required: false
    },
    testInstructions: {
        type: Schema.Types.String,
        required: false
    },
    resolution: {
        type: Schema.Types.String,
        required: false
    },
    history: [{
        type:Schema.Types.ObjectId,
        ref: 'MROHistory',
        required: false
    }]
})`

**Comment by vkarpov15** [comment]
@zacharymorel can you describe in more detail what you mean by "apply the filter to the SampleSchema", preferably with some code samples? That's a key detail that's missing here.

I think this might be a case of malformed data, the below script is an example of a similar (but slightly different) error.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7310`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const SampleSchema = new Schema({
    program: {
      type: Schema.Types.ObjectId,
      ref: 'Program',
      required: false
    }
  });
  
  SampleSchema.pre('find', function() {
    this.populate('program');
  });
  
  const Sample = mongoose.model('Sample', SampleSchema);

  const Program = mongoose.model('Program', new Schema({ name: String }));
  
  await Sample.collection.insertOne({ program: 'Foo' });

  await Sample.find(); // Cast to ObjectId failed for value "Foo" at path "_id" for model "Program"
}
```
