### ISSUE TITLE
How to calculate distance between two point when the address is an array

### ISSUE THREAD

**Issue by TonyGao** [Automattic/mongoose#7314]
Hi, there

version: mongoose@5.3.12

I have a situation that a model has an address which is an array, there is a field "location" in that array, the field "location" is a PointSchema and index by 2dsphere.

The question is how can I calculate the distance from the current location(which I know the longitude and latitude), Or how to determine whether the point I know longitude and  latitude is within range 
of circle by specific radius which center is the "location" in the address array.

I read many blog and the documents about near, circle method, 
but not suitable for my situation, please give me some suggestions, thank you.

model code

```javascript
'use strict';

module.exports = app => {
  const mongoose = app.mongoose;
  const PointSchema = new mongoose.Schema({
    type: {
      type: String,
      enum: ['Point'],
      required: true
    },
    coordinates: {
      type: [Number],
      required: true
    }
  });
  const AttendanceGroupSchema = new mongoose.Schema({
    /**
     * Attendance Group Name
     */
    name: {
      type: String,
      unique: true,
      required: true,
    },
    /**
     * Attendance Check valid address
     * There are many locations
     */
    address: [{
      addressName: String,
      addressDescription: String,
      location: {
        type: PointSchema,
        index: '2dsphere'
      }
    }]
  }, {
    timestamps: true,
  });

  return mongoose.model('AttendanceGroup', AttendanceGroupSchema);
}
```  

current location
```javascript
const currentLocation = { type: 'Point', coordinates: [117.650734, 39.022214] };
```

**Comment by vkarpov15** [comment]
Try this blog post: http://thecodebarbarian.com/80-20-guide-to-mongodb-geospatial-queries . There's a section on finding documents that are within a certain distance of a given point
