### ISSUE TITLE
Improve populate() with limit

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#7318]
See https://github.com/Automattic/mongoose/issues/2151#issuecomment-444487939 , etc.

Right now `populate()` with limit doesn't work in general if there are multiple docs, like with `find()`.

**Comment by RezaErfani67** [comment]
Related to this issue:

i have set of company and each company has multi task and each task  has multi message...
my query is:
```javascript
  CrmCompany.paginate(query  , {
                page: req.query.page,
                limit:limit,
                populate:{
                    path:'crmTasks',options:{limit:3,sort:'-updatedAt'},
                    populate:{path:'crmMessages',options:{limit:3,sort:'-nextCall'}}
                    },
                sort: {title:1}
            }, function (err, result) {
                if(err) return gldone.fail(err);
                return gldone({message:"fetch data",data:result});
            })
```
but it does not return data correctly...
some company have a task with no messages...
is it possible to fix proble?
Here is what the query says:
```javascript
Mongoose: crmCompany.find({}, { sort: { title: 1 }, skip: 0, limit: 5, projection: {} })
Mongoose: crmTask.find({ crmCompany: { '$in': [ ObjectId("5d595a7573a83128e89f6f6c"), ObjectId("5d595bb373a8
3128e89f6f95"), ObjectId("5d595a0a73a83128e89f6f63"), ObjectId("5d595a1673a83128e89f6f64"), ObjectId("5d595b
9973a83128e89f6f91") ] }}, { limit: 15, sort: { updatedAt: -1 }, projection: {} })
Mongoose: crmMessage.find({ crmTask: { '$in': [ ObjectId("5d5a4db34d70af2b081bd87d"), ObjectId("5d5a48c164f2
012454f3e7a4"), ObjectId("5d5963a073a83128e89f6fd4"), ObjectId("5d5961f973a83128e89f6fc8") ] }}, { limit: 12
, sort: { nextCall: -1 }, projection: {} })

```

**Comment by RezaErfani67** [comment]
can you please write sample code or introduce reference?

**Comment by vkarpov15** [comment]
```javascript
const docs = await   CrmCompany.paginate(query  , {
                page: req.query.page,
                limit:limit,
                sort: {title:1}
            }, function (err, result) {
                if(err) return gldone.fail(err);
                return gldone({message:"fetch data",data:result});
            })

for (const doc of docs) {
  await doc.populate({
                    path:'crmTasks',options:{limit:3,sort:'-updatedAt'}
                    }).execPopulate();
}
```

You'll also need to do a separate loop to populate each of `crmMessages`. I agree this is very painful and I apologize for the rough API. The problem is that once you introduce `limit`, Mongoose can no longer execute one query for each `populate()` call if you have multiple documents. When you do `populate('crmTasks')`, Mongoose executes exactly one query on the `CrmTasks` model, but if you use `limit` and have multiple `CrmCompany` docs, that approach breaks. Changing this requires significant refactoring, but it's something we want to tackle in the near future.
