### ISSUE TITLE
query timeout

### ISSUE THREAD

**Issue by ybwin** [Automattic/mongoose#7319]
Connection Settings
![image](https://user-images.githubusercontent.com/31563989/49789114-23910c00-fd66-11e8-8700-9f30e99aaed5.png)

Version
 mongose4.13.17  mongodb3.4.15 

The problem
Probabilistic query timeouts occur

A piece of my mind
1.expand  poolsize
2. change connectTimeoutMS，socketTimeoutMS？
3. The problem comes from node-mongodb-native？

Current solutions
   Query the database table if the query fails  execute
            setTimeout(function(){
                process.exit(7);
             }, 2000);

Any Ideas
Any ideas how I can get this to stop happening?

I'm happy to gather any more debugging info, just let me know what info to get.

**Comment by mhombach** [comment]
Please provide more information on what yu are doing and what error in what circumstances does occur :) 
In normal situations there is no need to expand the poolsize or work with query-timeouts when you are working with localhost or some network server.

**Comment by ybwin** [comment]
@mhombach  I'm very happy to have received your response

There are 2 situations that can cause this problem.
1.Stress test large traffic writes cause mongodb io to occupy high cause query timeout
2.Long-term work program seems to be connected to mongodb, and virtually no response from mongodb has been received.(Frequent occurrence)

Any idea is very grateful

**Comment by ybwin** [comment]
I'm very happy to have received your response



There are 2 situations that can cause this problem.
1.Stress test large traffic writes cause mongodb io to occupy high cause query timeout
2.Long-term work program seems to be connected to mongodb, and virtually no response from mongodb has been received.(Frequent occurrence)

Any idea is very grateful







At 2018-12-11 21:05:23, "mhombach" <notifications@github.com> wrote:


Please provide more information on what yu are doing and what error in what circumstances does occur :)
In normal situations there is no need to expand the poolsize or work with query-timeouts when you are working with localhost or some network server.

**Comment by ybwin** [comment]
@mhombach  @vkarpov15
![image](https://user-images.githubusercontent.com/31563989/49928111-6552bb80-fefa-11e8-9aac-7b05db419185.png)

**Comment by vkarpov15** [comment]
What's the actual error message you get?
