### ISSUE TITLE
"errmsg" : "not master and slaveOk=false"

### ISSUE THREAD

**Issue by sshael** [Automattic/mongoose#7323]
2018-12-12T12:51:20.890+0530 E QUERY    [js] Error: error: {

	"operationTime" : Timestamp(1544599278, 71),

	"ok" : 0,

	"errmsg" : "not master and slaveOk=false",

	"code" : 13435,

	"codeName" : "NotMasterNoSlaveOk",

	"$clusterTime" : {

		"clusterTime" : Timestamp(1544599278, 71),

		"signature" : {

			"hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),

			"keyId" : NumberLong(0)

		}

	}

} :

_getErrorWithCode@src/mongo/shell/utils.js:25:13

DBCommandCursor@src/mongo/shell/query.js:708:1

DBQuery.prototype._exec@src/mongo/shell/query.js:113:28

DBQuery.prototype.hasNext@src/mongo/shell/query.js:288:5

DBQuery.prototype.forEach@src/mongo/shell/query.js:500:12

@(shell):1:1

**Comment by vkarpov15** [comment]
This error is from the MongoDB shell, not mongoose.
