### ISSUE TITLE
after connecting, mongoose not returning models, and hence queries are not working.

### ISSUE THREAD

**Issue by UtkarshYeolekar** [Automattic/mongoose#7325]
Hello @aheckmann 

Today i have updated the mongoose library to the latest "mongoose": "^5.3.16".
After connection, i have seen that my queries are not working, neither callbacks and promises are returning. 
Then i have try to log the connection object. There i have seen the difference, the connection object doesn;t list already existed models.

![image](https://user-images.githubusercontent.com/23631648/49882308-587c8c00-fe56-11e8-8792-0309640570fe.png)

After i downgrade the version to "mongoose":"^5.3.13", everything works fine.
![image](https://user-images.githubusercontent.com/23631648/49882596-f40dfc80-fe56-11e8-90d2-9f4a7ec46832.png)

**Comment by mhombach** [comment]
It would be of help, although your code was working before the update, to post snippets about how you are initializing mongoose/models :)

**Comment by vkarpov15** [comment]
@UtkarshYeolekar please provide some code samples, there's not enough information here for us to take any action.
