### ISSUE TITLE
Neither allowDiskUse nor cursor are not working as expected with mongoose version 5.2.4

### ISSUE THREAD

**Issue by blueskies0** [Automattic/mongoose#7328]
When doing aggregation, setting the graphlookUp from a large document(with a size 15MB json utf-8 format), it returns the following error:   
code:40099
MongoError: $graphLookup reached maximum memory 
It seems a bug that no matter I use 'allowDiskUse' or 'cursor', I could not avoid this error.
The code I wrote is as below:
 
 Book.aggregate([{$project: queryProject}, {$match:  queryMatch}, {$graphLookup:  queryGraphLookup},
          queryUnwind, queryGroup2, queryGroupTest])
        .allowDiskUse(true)
        .then(book => {
          if (!book) {        
            return;
          }
        res.status(constants.HTTP_STATUS_OK);
        res.send(book);
      }).catch(err => {
           errorUtil.handleError(constants.HTTP_STATUS_INTERNAL_SERVER_ERROR, 
          idArray[0] + err.errmsg, res);       
      });
It goes into the catch part with the error code =40099, then I tried to use cursor as below:
 
let cursor = Book.aggregate([{$project: queryProject}, {$match:  queryMatch}, {$graphLookup:  queryGraphLookup},queryUnwind, queryGroup2, queryGroupTest])
      .allowDiskUse(true)
      .cursor({ batchSize: 10000 }).exec();
      cursor.eachAsync(doc => {
        //res.send(doc);
        console.log(doc);
      })
      .then(() => console.log('done!'));

I still received  40099 error with nothing is written to console. I change the batchSize to 10 but it is of no help.

Could you tell how to resolve the problem?

**Comment by blueskies0** [comment]
I think the problem is expected because  graphLookup can only consume at most 100MB of memory, and does not allow disk use even if { allowDiskUse: true }.But I wonder if mongoose could repackage mongodb's API and solve the problem?

**Comment by vkarpov15** [comment]
You're right, MongoDB only allows [100mb max for `$graphLookup` and explicitly ignores `allowDiskUse` for `$graphLookup`](https://docs.mongodb.com/manual/reference/operator/aggregation/graphLookup/#memory). That's very unfortunate, nothing Mongoose can do about that. The MongoDB server does all aggregations, so if the server doesn't support it, Mongoose can't do anything.

Perhaps you could just use [populate](https://mongoosejs.com/docs/populate.html) instead?
