### ISSUE TITLE
Reconnected event broken

### ISSUE THREAD

**Issue by nooks** [Automattic/mongoose#7330]
Bug

The reconnected event no longer works for replica sets.
I still need the proper driver events emitted to support this again.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Start application
* Kill all replicaset workers
* Wait events

**What is the expected behavior?**

* Start application
* Kill all replicaset workers
* Emit event for disconnected 

Node.js: v8.11.2
MongoDB Server (bare metal replica set): 3.6.5
Mongoose: 5.3.16

**Comment by vkarpov15** [comment]
I'm not sure I understand your issue. Is the issue that you're not seeing a disconnected event if you kill all replica set members, or that you're not seeing a reconnected event when you bring the replica set back up?

**Comment by nooks** [comment]
I do not see the event when I kill all replica sets

**Comment by vkarpov15** [comment]
Which event specifically? Can you provide some code samples please?

**Comment by nooks** [comment]
```JavaScript

'use strict'

/*!
 * Module dependencies.
 */
const mongoose = require('mongoose')
const { mongodb } = require('config')
const log = require('common/lib/logger')
const healthz = require('common/lib/healthz')

const connection = mongoose.connection

mongoose.Promise = global.Promise

/*!
 * Subscribes.
 */
connection.on('error', onError)
connection.on('connected', onConnected)
connection.on('disconnected', onDisconnected)
connection.on('reconnect', onReconnect)

mongoose.set('useCreateIndex', true)

/*!
 * Initialize connection.
 */
mongoose.connect(mongodb.url, mongodb.options).catch(onError)
mongoose.set('useCreateIndex', true)
mongoose.set('debug', true)

/*!
 * Expose main connection.
 */
module.exports = mongoose.connection

/**
 *
 * @param {Error}
 */
function onError(err) {
  healthz.setReady(false)
  log.error({ err }, 'MongoDB')
}

/**
 *
 */
function onConnected() {
  healthz.setReady(true)
  log.info('MongoDB connected')
}

/**
 *
 */
function onReconnect() {
  log.info('MongoDB reconnect')
}

/**
 * 
 */
function onDisconnected() {
  healthz.setReady(false)

  log.info('MongoDB disconnected.')

  if (connection.auto_reconnect !== false && !process.QUITING) {
    setTimeout(() => {
      mongoose.connect(mongodb.url, mongodb.options).catch(onError)
    }, 1000).unref()
  }
}
```

**Comment by vkarpov15** [comment]
Put in a fix that'll make the `disconnected` event show up if Mongoose loses connection to the primary.

Although FYI, you shouldn't manually reconnect if you lose connection to the replica set. I recommend removing the `setTimeout(() => mongoose.connect())` part, see [this blog post](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html#replica-set-outages) for more info.
