### ISSUE TITLE
Which command runs listIndexes ?

### ISSUE THREAD

**Issue by CruiseMan** [Automattic/mongoose#7332]
`Problem` -  `MongoError: command listIndexes requires authentication` while connecting to Atlas M5 and M10 instance, user has `atlasAdmin @admin` acces,
`Question` - Which mongoose command runs underneath `listIndexes` ?

**Comment by vkarpov15** [comment]
[`Model.listIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.listIndexes) and [`Model.syncIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.syncIndexes)
