### ISSUE TITLE
Model.runcommand not working with the mongoose 5.X

### ISSUE THREAD

**Issue by ashishlal91** [Automattic/mongoose#7334]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
`Model.runCommand()` isn't a function in any version of Mongoose that I'm aware of. Can you please clarify with some code samples and follow the issue template?

**Comment by vkarpov15** [comment]
Unfortunately the MongoDB node driver doesn't support `runCommand()`, so Mongoose doesn't have it either

![image](https://user-images.githubusercontent.com/1620265/51637719-86abbc00-1f2a-11e9-998d-7ca61c6061da.png)
