### ISSUE TITLE
Document `mongoose.connections`

### ISSUE THREAD

**Issue by GarrettGeorge** [Automattic/mongoose#7338]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

When trying to access the default connection `mongoose.connection` is a nice way for other files to access models via `mongoose.model('Model')`. However when you have multiple connections via `createConnection` there's no nice way for other files to access the model. Yes I know there's `conn.useDb('asdf').model('Model')` but that only works if the connection has been made and access to that `conn` object is done. 

With the default connection this is trivial because `mongoose.model` doesn't care if the default connection is even up and running yet, _*but*_ when you're trying to access a model that's been registered on a connection with `createConnection` it immediately checks if the model has been registered on that connection.

**Comment by vkarpov15** [comment]
We actually have a `mongoose.connections` property, it just isn't documented unfortunately. Will add.
