### ISSUE TITLE
Using virtual field as refPath

### ISSUE THREAD

**Issue by tamirvs** [Automattic/mongoose#7341]
I'm trying to use refPath but instead of a field which contains the full name of the model (e.g. `Player`, `Tribe`) it will contain a number (`1` = Player, `2` = Tribe) to save space in the database.
I thought about using refPath which points to a virtual field that will translate the code to the full model name:
```
const schema = new mongoose.Schema({
  matches: [{
    modelCode: Number,
    model: {
      type: Number,
      refPath: 'modelName' //also tried 'matches.modelName'
    }
  }]
})

schema.virtual('matches.modelName').get(function() {
  return checkSomething() ? 'Player' : 'Tribe';
})
```
But that doesn't work.

The only solution to my problem was to create a virtual field with a `ref` function (and `localField, foreignField`) and populate that virtual field, but that is just adding an extra field, and I feel like the code I posted should work..

**Comment by vkarpov15** [comment]
That's an interesting idea, will consider it for a future release. Can you please post the code you used with the virtual ref function for future reference?

**Comment by SzHeJason** [comment]
+1 , I don't want to save model name  in DB
