### ISSUE TITLE
When findOneAndRemove doesn't find anything there's no error thrown

### ISSUE THREAD

**Issue by gkatsanos** [Automattic/mongoose#7343]
Hello, using latest mongoose/mongo with express. I already read https://github.com/Automattic/mongoose/issues/2233 which seems pretty related. 

So I have the following controller:

```
exports.refresh = async (req, res, next) => {
  try {
    const { email, refreshToken } = req.body;
    const refreshObject = await RefreshToken.findOneAndRemove({
      email,
      refreshToken,
    });
    const { user, accessToken } = await User.findAndGenerateToken({ email, refreshObject });
    const response = generateTokenResponse(user, accessToken);
    return res.json(response);
  } catch (err) {
    return next(err, req, res, next);
  }
};
```
Sometimes the `refreshObject` returned from `.findOneAndRemove()` is `null`. 
Then `findAndGenerateToken` fails but it's too late.. 

I would like to stop the flow and move on to my error handling middleware and not reach findAndGenerateToken at all if `refreshObject` is `null`. 
I guess I'd like to throw somehow and go to `catch` when findOneAndRemove doesn't return anything. Do I have to use a callback function in `findOneAndRemove()`? Any example?

**Comment by mhombach** [comment]
Maybe i'm missing the point in your question but why not check for `if(refreshObject  == null)` ?
If you don't want to continue your dataflow, just check for values you don't want to work with.
Also i would say that, like already commented in #2233, it's not very elegant to throw an error on such a thing. If you do a `find all entries where age > 30` query then getting 0 results returned is a completely normal and positive way of telling you that the query ran perfectly fine, all fields were typed correct and the query returned 0 results.
Returning 0 Results (or `null`) is not always a "problem" or "error". If i, for example, want to know that a user isn't already registered in the db when signing up and i do a query `find all entries where username = myUsername` then getting `null` returned is the most positive answer i can hope for... I hope you get my point :)

**Comment by gkatsanos** [comment]
The thing is that this is in a try/catch block and I wouldn't like to manually have to `throw` (although it seems I ll have to ).
I completely understand, semantically it's not an error, 0 results can be a good thing or a bad thing.

**Comment by gkatsanos** [comment]
What do you think of 
```
exports.refresh = async (req, res, next) => {
  try {
    const { email, refreshToken } = req.body;
    const refreshObject = await RefreshToken.findOneAndDelete({
      email,
      refreshToken,
    });
    if (refreshObject) {
      const { user, accessToken } = await User.findAndGenerateToken({ email, refreshObject });
      const response = generateTokenResponse(user, accessToken);
      return res.json(response);
    }
    const err = Boom.unauthorized('refreshToken expired');
    return next(err, req, res, next);
  } catch (err) {
    return next(err, req, res, next);
  }
};
```

**Comment by mhombach** [comment]
Seems fine :)

**Comment by vkarpov15** [comment]
@gkatsanos I wouldn't recommend putting everything in try/catch. In this case it should work, but try/catch with async/await has some quirks when you return a promise. Check out https://www.npmjs.com/package/@awaitjs/express for an alternative.

**Comment by vkarpov15** [comment]
@gkatsanos If you return a promise in a `try/catch`, the `catch` block will not run.

```javascript
run().then(() => console.log('success'), error => console.error(error.stack));

async function run() {
  try {
    return Promise.reject(new Error('Oops'));
  } catch(err) {
    console.log('Caught', err); // Never prints
  }
}
```

Shameless plug: [chapter 3 of my async/await ebook](http://asyncawait.net/) discusses this and other important fundamental async/await details in depth.

**Comment by gkatsanos** [comment]
@vkarpov15 aha!
but if you just save it in a variable without returning, you're good, right?


```
run().then(() => console.log('success'), error => console.error(error.stack));

async function run() {
  try {
    let response = await Promise.reject(new Error('Oops'));
  } catch(err) {
    console.log('Caught', err); // Never prints
  }
}
```

**Comment by vkarpov15** [comment]
yep exactly, just do `return response;` as well. You can also do `return await Promise.reject(new Error('Oops'))`. I'm not sure how I feel about the latter, it is a bit of a head-scratcher for beginners.

**Comment by gkatsanos** [comment]
Ah yeah. Straightforward, it's a promise so you can either await it or then() it..
Will look into the book :)
