### ISSUE TITLE
Invalid docs for SchemaString.cast() and SchemaBoolean.cast()

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#7351]
The docs for `SchemaString.cast()` and `SchemaBoolean.cast()` are copy-pasted docs for `ObjectId.cast()`, they weren't updated:

https://github.com/Automattic/mongoose/blob/79118950a0a3bed4609a36c5cf0013fe814c87ef/lib/schema/string.js#L50-L70

https://github.com/Automattic/mongoose/blob/79118950a0a3bed4609a36c5cf0013fe814c87ef/lib/schema/boolean.js#L45-L65

Thanks for implementing it by the way! Excellent work :)

**Comment by vkarpov15** [comment]
Thanks for finding this :+1:
