### ISSUE TITLE
Unable to define collection name via POST

### ISSUE THREAD

**Issue by pulse1989** [Automattic/mongoose#7354]
**Do you want to request a *feature* or report a *bug*?** 
bug

**What is the current behavior?**
Document id does not get generated when trying to pass in a collection name

**If the current behavior is a bug, please provide the steps to reproduce.**

When i define the schema:
```
const userDBSchema = new Schema({
    userName: {
    	type:String
    },
    musicType: {
        type: String,
    },
}, { collection: 'userData' });

```
then run a post to the database, using this function:

```
exports.saveUser = (req, res) => {
    const username = req.params.user;

    const newUser = new UserInfoDb(req.body, {'collection': username}) ;
    newUser.save((err, response) => {
        if (err) { res.status(500).send(err); }
        res.status(201).json(response);
    });
};

```

i get this error:

```
{
    "message": "document must have an _id before saving",
    "name": "MongooseError"
}
```

Even when i manually define the id, with the following in my schema:

```
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        index: true,
        required: true,
        auto: true
    },
```

 i get this error:

```
{
    "errors": {
        "_id": {
            "message": "Path `_id` is required.",
            "name": "ValidatorError",
            "properties": {
                "message": "Path `_id` is required.",
                "type": "required",
                "path": "_id"
            },
            "kind": "required",
            "path": "_id"
        }
    },
    "_message": "userDB validation failed",
    "message": "userDB validation failed: _id: Path `_id` is required.",
    "name": "ValidationError"
}

```

**What is the expected behavior?**

That i can pass in the name of a collection I want to access from the POST, then write the body of my request into that collection

**Please mention your node.js, mongoose and MongoDB version.**

node version: v11.3.0
npm version : 6.4.1

**Comment by mhombach** [comment]
> const newUser = new UserInfoDb(req.body, {'collection': username}) ;

Can you please tell me what the 2nd parameter in the Model-constructor is for (`{'collection': username}`)? I don't know a 2nd parameter there and haven't found a documentation online or in Typescript-declaration. From what i see there does only exist one parameter.
Executing your code does give me the same error of a missing `_id` but removing that 2nd parameter there let's the error disappear.
I'm not saying that there isn't a reason for you putting a 2nd parameter there, just asking. Maybe you mixed up some things from the documentation?
Maybe you can also tell me/us what you want the 2nd parameter to do :)

**Comment by pulse1989** [comment]
@mhombach I'm also trying to figure it out. I would have thought that the second parameter allowed me to pass through a collection to use for that specific request which is my goal as i've defined it in the schema constructor but this is not the case. The data will definitely save if you remove that second constructor - but that doesn't solve what im trying to achieve - being able to specify a collection to write to before the saving happens

**Comment by pulse1989** [comment]
I would have never ran a search across any amount of collections. i'm pretty sure the docs specify what collection you can search on based on certain criteria.  

I'm trying to store user records based on different criteria. a simple example would be storing your favourite food and music. So i would have each document storing food information and another document storing music information. Each document has it's own schema and stored in the user's collection

**Comment by mhombach** [comment]
I'm not sure why you want to save those information in different collections:
```typescript
const userDBSchema = new Schema({
    userName: {
    	type:String
    },
    musicType: {
        type: String,
    },
    foodType: {
        type: String,
    }
}
```
You can also do this:
```typescript
const userMusicSchema = new Schema({
    userName: {
    	type:String
    },
    musicType: {
        type: String,
    }
})

const userFoodSchema = new Schema({
    userName: {
    	type:String
    },
    foodType: {
        type: String,
    }
})
```

Or you can use [Discriminators](https://mongoosejs.com/docs/discriminators.html) to do the above.
You can read in the docs about [all available query-options](https://mongoosejs.com/docs/api.html#query_Query-setOptions) and there is no option for defining a collection. As i said, this won't make sense.

I think the best way for you is to use the "discriminator" i mentioned. This makes it possible to store different variations of a schema/model in the same collection.

> So i would have each document storing food information and another document storing music information

This is not how MongoDB should be used. You can just [embed sub-documents](https://mongoosejs.com/docs/subdocs.html), which your usecase here is perfectly working fine with. If you want to store hughe lists of music and food for a user you should create own schema/models for "food" and "music" and store each in a separate collection. Then do link and `aggregate` those to your user.

Also, if you are really sure you read about storing documents in separate collections or using `find()` on different collections, then please provide the link to the docs. As i said, there isn't any documented way for this that i found regardless of reasoning.

**Comment by pulse1989** [comment]
@mhombach thanks a lot man. looks like i have some further reading and understanding to do!

**Comment by vkarpov15** [comment]
@mhombach is right, discriminators are the way to go here. It is strange that you're getting that _id error though, I'll take a quick look

**Comment by vkarpov15** [comment]
I can't repro the `_id` error:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7354`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        index: true,
        required: true,
        auto: true
    },
    userName: {
        type:String
    },
    musicType: {
        type: String,
    },
  }, { collection: 'userData' });

  const User = mongoose.model('User', userSchema);

  await User.create({ _id: void 0, userName: 'test', musicType: 'test' });
}
```

Works without error.
