### ISSUE TITLE
[BUG] the server/replset/mongos/db options are deprecated

### ISSUE THREAD

**Issue by drakescai** [Automattic/mongoose#7356]
**Bug**
Mongoose Version: Latest - 5.x
Behavior: 
`the server/replset/mongos/db options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,useNewUrlParser]` is outputted when following new MongoClient format.

Example:
```
const connectionString = "mongodb://localhost:27017/someDB";
const connectionObject = {};
connectionObject.replSet = "someSet";
connectionObject.authSource = "admin";
connectionObject.user = "someUser";
connectionObject.pass = "somePassword";
connectionObjet.family = 4;

await mongoose.connect(connectionString, connectionObject);
```
Expected:
For the deprecation message to disappear as the new format is being followed.

Node.js Version: 10.4.1
Mongoose Version: 5.4.0
MongoDB Version: 4.X

**Comment by vkarpov15** [comment]
The correct option now is `replicaSet`, see http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html . The `replSet` option used to be replica set specific options, but that is now deprecated
