### ISSUE TITLE
Mongoose overwriting updatedAt on new records when it's provided

### ISSUE THREAD

**Issue by jnardone** [Automattic/mongoose#7357]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I specify a createdAt and updatedAt timestamp on a new record, Mongoose overwrites the updatedAt timestamp with the createdAt timestamp.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a schema with timestamps.  Insert a document.  Retrieve document.  Change _id and save document.  The created/updated timestamps should be the same in both documents, but are not.  This is here:

```
    if (updatedAt && (this.isNew || this.isModified())) {
      let ts = defaultTimestamp;
      if (this.isNew) {
        if (createdAt != null) {
          ts = this.get(createdAt); // **** ARGH
        } else if (auto_id) {
          ts = this._id.getTimestamp();
        }
      }
      this.set(updatedAt, ts);
}
```
in schema.js

**What is the expected behavior?**
If I am explicitly specifying timestamps in my document, those should be respected 

**Please mention your node.js, mongoose and MongoDB version.**
This is in Mongoose 5.4.0 (node 10.13) with Mongo 3.6.

**Comment by govindrai** [comment]
Ah, this is a clash of whats best for most users, not really a bug. Although, I will admit it's not really documented anywhere that mongoose will/will not overwrite timestamps (this should be added to the docs). Contrary to your problem, I _quite_ like the functionality where my clients can't mess with the createdAt, updatedAt timestamps, it helps with data integrity.

If you don't want mongoose overwriting timestamps, you should remove `{timestamps: true}` from your schema options and handle timestamps yourself. Also, you could can request a feature from the mongoose team that allows us to overwrite the timestamp as a configurable option, maybe something like

`{ timestamps: { createdAt: 'created_at', overwriteable: true } }`.

**Comment by jnardone** [comment]
I disagree, and this is counter to what most ORMs do.  `timestamps` is there for convenience, not for integrity.  Ultimately the developer is in charge of their data, and if they know what the values of a record should be, the code should not (silently!) be counteracting that.  The developer should decide what is "best" - I'd say if anything the current behavior should be something a developer should have to opt INTO - e.g. "preventWriting: true" on the timestamps configuration.

**Comment by vkarpov15** [comment]
We'll add an option to shut this off in `save()` to match the existing `timestamps` option for `update()` : https://mongoosejs.com/docs/api.html#query_Query-setOptions .

This is very much intentional because Mongoose aims to make it as safe as possible to store data coming in to an API over the network in MongoDB. Allowing API clients to overwrite timestamps runs counter to that.

**Comment by LargeOrange** [comment]
why I use { timestamps: false } it does not work?

**Comment by vkarpov15** [comment]
@LargeOrange please provide some code samples. Are you sending `timestamps: false` in `save()` or in your schema?

**Comment by duenguyen2103** [comment]
I try to skip the timestamps by using `timestamps: false` like this but it does not work: 

>    await customerTicketModel.save({ timestamps: false}, () => {});
> 

`timestamps` does not exist in `saveOptions` object.

**Comment by vkarpov15** [comment]
@duenguyen2103 can you please open up a new issue and follow the issue template?

**Comment by michaelcanonizado** [comment]
@govindrai @vkarpov15  I think it would be neat that the developers would be given the option to overwrite the timestamps (createdAt and updatedAt). I am currently facing this issue. I want to seed mongoDB with data that I have stored in google sheets, which is linked to a google form. By default, google forms also handles the timestamps and adds a separate column to the linked spreadsheet. I wanted to migrate that data from google sheets, seed my project, and preserve the timestamps.

What are some solutions to this? I still want mongoose to handle the timestamps after seeding. Can I temporarily include the timestamps in the schema and handle it myself while seeding, then remove it and bring back { timestamps: true } afterwards? Or would this also result in a conflict?

**Comment by vkarpov15** [comment]
@michaelcanonizado Mongoose does currently support disabling timestamps on individual operations, like `findOneAndUpdate(filter, update, { timestamps: false })`. Does that help?
