### ISSUE TITLE
the options [useNewUrlParser] is not supported

### ISSUE THREAD

**Issue by gpa-athatcher** [Automattic/mongoose#7359]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When passing in `{useNewUrlParser: true}` to `mongoose.connect()`, I'm getting a console error stating that `the options [useNewUrlParser] is not supported]`. The application still connects to the database, however. Just trying to make sure that this isn't a subtle issue that's going to break my application down the line.

**If the current behavior is a bug, please provide the steps to reproduce.**

Connection code:
```mongoose.connect(conString, {useNewUrlParser: true});```

**What is the expected behavior?**
To not throw an error.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.11.3
mongoose: v5.4.0
MongoDB: v3.6.4

**Comment by vkarpov15** [comment]
Can you double check your mongoose version with `console.log(mongoose.version)` and also verify what other mongodb related modules you're using? This warning could be coming from another npm module
