### ISSUE TITLE
Document.prototype.updateOne()

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#7366]
Something has changed in behavior, unsure if it is a documentation bug or a driver bug.
I get following error: errorz.updateOne(...).exec is not a function

The code behindt this is something like following:
`myDocument.updateOne({$inc: {counter: 1}}).exec();`

I first fetch a document, and increase a counter on it afterwards, this worked before, but since updating mongoose to the latest version I get this error. Accoridng to the docs, this should return a "Query", and therefore exec() should work?

**Comment by vkarpov15** [comment]
Thanks for the repro, looks like we didn't have tests to ensure that `Document#updateOne()` returned a query. So when we added support for document `updateOne()` hooks in 5.4.0, that broke. Fix will be in 5.4.2 :+1:
