### ISSUE TITLE
mongoose.disconnect in Mocha "after all" hook doesn't work

### ISSUE THREAD

**Issue by maxaus** [Automattic/mongoose#7367]
**Do you want to request a *feature* or report a *bug*?**

Probably a bug.

**What is the current behavior?**

I used `mongoose.disconnect` inside Mocha's `after` hook for a long time in following way:
```
after((done) => {
  mongoose.disconnect(done);
});
```
With Mongoose v5.2.5 it worked well, but stopped after updated to v5.4.0. Now running tests ending with error:
```
  1)  "after all" hook:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Also tried async/await syntax for the hook function:
```
after(async () => {
  await mongoose.disconnect();
});
```
but it didn't help.

**If the current behavior is a bug, please provide the steps to reproduce.**
It could be long to describe all test script, but first before running all Mocha tests, connection is established with following options:
```
mongoose.connect(dbConnectionString, { useNewUrlParser: true, useFindAndModify: false, useCreateIndex: true })
```

**What is the expected behavior?**

Mongoose should close connection and `mongoose.disconnect` promise resolved or callback function called.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js v8.11.1
Mongoose v5.4.0
MongoDB v3.6.3

**Comment by vkarpov15** [comment]
I'm unable to repro this. The below script works fine for me:

```javascript
before(function() {
  return mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useFindAndModify: false,
    useCreateIndex: true
  });
});

after(function(done) {
  return mongoose.disconnect(done);
});
```

Output:

```
$ npm list | grep "mocha"
├─┬ mocha@5.2.0
$ ./node_modules/.bin/mocha gh-7367.js 


  0 passing (2ms)

$ 
```

Can you modify this script to repro your issue?

**Comment by maxaus** [comment]
@vkarpov15 sorry, at the time I was posting initial issue, I wan't sure, what exactly causes failure, but now seems to  be not `after` hook, but due to `sinon.useFakeTimers` used in our test. So updated example script could be following:
```
const chai     = require('chai');
const mongoose = require('mongoose');
const sinon    = require('sinon');

before(function () {
  return mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser : true,
    useFindAndModify: false,
    useCreateIndex  : true
  });
});

after(function (done) {
  return mongoose.disconnect(done);
});

describe('tests', function () {
  it('case', function () {
    let clock      = sinon.useFakeTimers();
    const baseDate = new Date('2017-11-05T11:00:00.000Z');
    clock.setSystemTime(baseDate);

    chai.expect('1').equal('1')
  })
});
```
If 3 strings starting with `sinon.useFakeTimers` are removed, then test passes, but with fake time it fails. 
This happens with latest `5.4.2` version, but if I revert Mongoose version to `5.2.5` we used before, then test starting to pass again, so it seems to be something related to latest Mongoose changes.
Thanks in advance for your help!

**Comment by maxaus** [comment]
Thanks a lot for pointing out `useFakeTimers()` disadvantages, and for the tip about using own `util/time.js` and stub for `now()` function, we will try to rework tests in this way.

**Comment by dtosato** [comment]
Any update for the problem? I am still facing it using
Node.js v8.16.0
Mongoose v5.6.9
MongoDB v4.0.11

**Comment by vkarpov15** [comment]
@dtosato please open up a new issue with detailed code samples

**Comment by abou7mied** [comment]
I faced the same issue and figured out that it's due to mocking the time like ` sinon.useFakeTimers` and forgot to restore after the test finishes `sinon.restore()`

**Comment by FarbodShabani** [comment]
Hi guys 
I have a better solution. You can easily use try catch and async-await instead of then. when you are using then you are somehow trying to return and use a promise but with async-await, it doesn't consider that. So in the end, You don't need to use the done method because of async-await.
this is my code
feel free to check out :
https://replit.com/@farbodesham/Mochajs-Test-Automation?v=1
