### ISSUE TITLE
Updating an object causes conflict

### ISSUE THREAD

**Issue by SirwanAfifi** [Automattic/mongoose#7369]
I have following hook for updating a date/time field inside an object called `metaData`:

```js
MySchema.pre("update", function(next) {
  const now = new Date().toISOString();
  this.findOneAndUpdate(
    {},
    { $set: { "metaData.lastModified": now, lastModified: now } }
  );
  next();
});
```

At the same time I want to update another field inside this object (`metaData`) not by using hooking, its value comes from outside:

```js
update: async (id, model) => {
  model.user = "Sirwan"; // I get this value from UI
  return await MySchema.update({ id }, model);
},
```

But when I run my app I get this error:

`MongoError: Updating the path 'metaData' would create a conflict at 'metaData'"`

But when I remove hook, it works, Any idea?

**Comment by vkarpov15** [comment]
Sorry for missing this bug report. You would need to check if `metaData` is already being updated, the MongoDB server doesn't let you `$set` both `metaData` and `metaData.lastModified` in the same update, which is why you're getting the "conflict" error.
