### ISSUE TITLE
Disable custom casting for arrays

### ISSUE THREAD

**Issue by sebastian-nowak** [Automattic/mongoose#7371]
Thanks to the recent update it's now possible to disable casting for lots of types, finally making it possible to write reliable validation code. Unfortunately I'm still not able to disable casting for arrays:

```js
#!/usr/bin/env node
(async function () {
  const mongoose = require('mongoose');
  mongoose.Schema.Types.Boolean.cast(false);
  mongoose.Schema.Types.Date.cast(false);
  mongoose.Schema.Types.Decimal128.cast(false);
  mongoose.Schema.Types.Number.cast(false);
  mongoose.Schema.Types.ObjectId.cast(false);
  mongoose.Schema.Types.String.cast(false);
  mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true});

  const schema = new mongoose.Schema({
    authors: [{
      type: String
    }]
  });
  const Model = mongoose.model('test', schema);

  const doc = new Model();

  console.log('before:' + await doc.validate()); // OK - validates correctly
  doc.authors = 'not an array';
  console.log('after:' + await doc.validate()); // NOT OK - should fail but it doesn't
  console.log(doc.toJSON());
})();
```

The `'not an array'` string is silently converted to an array with a single item. Is there a way to disable this behavior?

CC @vkarpov15 

Thanks!

**Comment by vkarpov15** [comment]
I'll look into this and see if there's a workaround for now. Arrays are trickier because we depend on casting internally to convert args to `push()` and other array functions.

**Comment by mariusailisoaie** [comment]
Hello @vkarpov15 ! I'm using mongoose for a project at work and I need to disable casting for a field of type Array, the same thing that @sebastian-nowak needed. I tried setting 'cast' to false but it does not work. I was looking online for a solution but I did not find it so far. Has this been implemented for arrays? Thank you for the help!
