### ISSUE TITLE
Document#directModifiedPaths()

### ISSUE THREAD

**Issue by govindrai** [Automattic/mongoose#7373]
Happy holidays!

**Do you want to request a *feature* or report a *bug*?**
Feature
MongoDb allows you to modify a nested path by using dot notation. This allows you to send less data over the wire sending only the data that needs to be changed. `document.prototype.modifiedPaths` is a great resource when wanting to know what is modified and can be used to create an update object to be used as an argument to document.prototype.updateOne, for example:

```
userSchema.methods.updateUserPostGeneration = function() {
  Logger.log('info:model:User:updateUserPostGeneration');
  const modifiedPaths = this.modifiedPaths();
  Logger.log('info:model:User:updateUserPostGeneration:modifiedPaths', modifiedPaths);
 
  const userUpdates = modifiedPaths.reduce((updates, modifiedPath) => {
    // this check is necessary because when a nested property 'c' with path 'a.b.c' is modified
    // mongoose will mark paths 'a', 'a.b', and 'a.b.c' as modified
    // this logic only includes the top level path 'a' in the update query, otherwise update conflict
    if (modifiedPath.includes('.')) {
      return updates;
    }
    updates[modifiedPath] = this[modifiedPath];
    return updates;
  }, {});

  return this.updateOne(userUpdates);
};
```

I am requesting (without fully understanding the repercussions for mongoose) that when a nested path is modified, only the nested path should be marked as modified, not all intermediary paths.

**What is the current behavior?**
Marking a nested path as modified, marks all intermediary paths as modified. Although technically correct, this is causing issues because I have a map which may have up to 1000 properties and I want to update one or two and I end up writing the entire map vs writing just the two properties. This is because a markModified returns something like this:

My log:
```
{
    "logLevel": "info",
    "logName": "model:User:updateUserPostGeneration:modifiedPaths",
    "message": [
        "modifiedProperty",
        "modifiedProperty.propertyB",
        "modifiedProperty.propertyA",
        "anotherModifiedProperty"
    ]
}
```

My application logic iterates over the modifiedPaths array and creates an update object that I submit to document.prototype.updateOne. Firstly, I am having to exclude any paths with `.` (periods) because having both intermediary and top level properties creates a conflict. Of course I could explicitly exclude the modified property, but I don't want to have to hardcode the property names because I have a couple of properties similar to this and I don't want to worry about forgetting to do this for a future property. 

Is there a reason mongoose marks all intermediary properties as being modified?

**Please mention your node.js, mongoose and MongoDB version.**
node 8.11.4, mongoose 5.4.0

**Comment by vkarpov15** [comment]
I think you're looking for [`Document#isDirectModified()`](https://mongoosejs.com/docs/api.html#document_Document-isDirectModified). We should also add a helper function `directModifiedPaths()` to go along with `modifiedPaths()`. The notion of a "direct modified path" is what you're looking for - we consider a path "modified" if any child path was changed, but "direct modified" means someone explicitly set that path, not one of its children. So instead of checking for `.`, check if `!this.isDirectModified(modifiedPath)`

**Comment by govindrai** [comment]
Cool! Didn't know there was a `Document#isDirectModified()`. Will use this for now, but agree `Document#directModifiedPaths()` would be a great addition and I would prefer to use that vs. checking each path in modified paths to check if it was a direct modified path. 

Thanks!
