### ISSUE TITLE
Connection#plugin()

### ISSUE THREAD

**Issue by ztrange** [Automattic/mongoose#7378]
**Do you want to request a *feature* or report a *bug*?**
request a feature

**What is the current behavior?**
I can only call mongoose.plugin(myBasePlugin). But if I want to work with more than one connection to the DB and use a different default plugin for each connection, I have to manually specify the plugin for each of the schemas on each connection. 

I was under the impression that a connection object would have the same methods than a mongoose object (from require('mongoose')). But I see it is not. One example would be that I can do mongoose.plugin() but I can not do connection.plugin(). There are other differences.

I believe it would be reasonable for a connection object to have access to any and all functions available from the mongoose module object.

**Comment by vkarpov15** [comment]
Not a bad idea. Will add this for a future release.
