### ISSUE TITLE
ensureIndex is called for each discriminator model

### ISSUE THREAD

**Issue by arkihillel** [Automattic/mongoose#7379]
**Bug**

Whenever using discriminators, the index creation is called for the main schema and for every discriminator schemas

Minimal reproduction:
```js
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/discriminator', {
	useNewUrlParser: true, 
	useCreateIndex: true
});

mongoose.set('debug', true);

var options = {discriminatorKey: 'kind'};

var eventSchema = new mongoose.Schema({time: {type: Date, index: true}}, options);
var Event = mongoose.model('Event', eventSchema);

var ClickedLinkEvent = Event.discriminator('ClickedLink',
  new mongoose.Schema({url: String}, options));
```

Output
```sh
$ node index.js 
Mongoose: events.createIndex({ time: 1 }, { background: true })
Mongoose: events.createIndex({ time: 1 }, { background: true })
```

**Expected behavior**
`createIndex` is called only from the main schema

This is a pretty minor issue but might be worth taking a look at just in case it hides something else.

Mongoose 5.4.1
NodeJS 10
MongoDB 4

**Comment by vkarpov15** [comment]
It is expected behavior for now because we don't want to diff indexes between the discriminator schema and the base schema, and because calling `createIndex()` multiple times shouldn't cause any errors AFAIK. Will keep this open for the future.
