### ISSUE TITLE
Python / Go Version(s)

### ISSUE THREAD

**Issue by jamalabo1** [Automattic/mongoose#7385]
**Do you want to request a *feature* or report a *bug*?**
feature

I have searched the web for alternative to Node.js (native support), And "Go" and "Python" were amazing programming languages, so first thing i have done is searching for MongoDB ODM, did't find Great ODM like Mongoose, 
So I'm Requesting Support For Python / Go Lang,
Python would be better since Django is written in Python.

**Comment by vkarpov15** [comment]
Not a bad idea, but that doesn't really line up with the work we're doing here. For Python, check out [mongoengine](http://mongoengine.org/) or [humbledb](https://humbledb.readthedocs.io/en/latest/), both written/maintained by very talented engineers :+1:
