### ISSUE TITLE
.connect/.createconnection - user/company connects to their DB 

### ISSUE THREAD

**Issue by ANorseDude** [Automattic/mongoose#7386]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
Using .connect to connect to mongodb. This result in that when company a connects everything works, but when company b connects both company a and b is connected to company b:s DB.

**What is the expected behavior?**

When the user logs in they are connected to their DB. Can anyone show me an example of how this is done? 

Tried reading the docs but I just can't figure it out. I guess it is the .createConnection that has to be used but it just doesn't work. 

Please help, I'm just about to wrap this application up and my alternative is just to have everything saved to the same DB which will work, but out of different reason I would like to have each company's data separated I to their own DB. 

**Please mention your node.js, mongoose and MongoDB version.**

Latest

**Comment by vkarpov15** [comment]
Quick solution is [`Connection#useDb()`](https://mongoosejs.com/docs/api.html#connection_Connection-useDb), just do `mongoose.connection.useDb('other-db')`.

In general, you're looking for a multi-tenancy solution for Mongoose. We don't have any plugins we recommend for that now, but you can take a look at [this blog post](http://nmajor.com/posts/multi-tenancy-with-expressmongoose).

Out of curiousity, why do you need every company's data in a separate db?

**Comment by ANorseDude** [comment]
Handling data from a govermental body so I'm was striving to keep the data as "siloed" as possible. 

But I've read a few different takes on this and it seems like it would work nicely with the use of "identifier" (objectId related to the company) and actually build a stronger validation for querys and such. 


But I do think it would be a nice addon to mongoose, which i quite enjoy, to simplify how to setup a multi-tenancy solution. Or maybe just update the docs with one or two examples.. 

Anyway, thank you. I'm going with the one db and stronger validation when it comes to writing/reading data.

**Comment by vkarpov15** [comment]
I'm going to close this for now. Multi-tenancy is something we're thinking about, but it is not a priority for the foreseeable future unless there's a lot of demand.
