### ISSUE TITLE
New Feature Request: description for each field in schema

### ISSUE THREAD

**Issue by taina0407** [Automattic/mongoose#7390]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Schema Type has no description for each field

**If the current behavior is a bug, please provide the steps to reproduce.**
Not a bug

**What is the expected behavior?**
SchemaTypes might have description options for developer team to understand the field, and might useful when expose the Model with Field description so the whole team better understand schema. For example client team will have API documentation (OpenAPI 3.0) with Model definition that have description for each field

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
You can always add a `description` field:

```javascript
new Schema({
  name: {
    type: String,
    description: 'First and last name'
  }
});
```

See [docs](https://mongoosejs.com/docs/schematypes.html#schematype-options). Mongoose won't do anything with the `description` option, so you can safely just add it.
