### ISSUE TITLE
Mongoose not sending shard key on remove()

### ISSUE THREAD

**Issue by GINCHER** [Automattic/mongoose#7393]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behavior?
When I use remove() on a Document, it returns 'query in command must target a single shard key', even though the schema knows about the shard key and all the documents have valid shard key value.

### If the current behavior is a bug, please provide the steps to reproduce.
**The following code _doesn't_ work:**
```
import { Schema, model as Model } from "mongoose";

let schemaData = {
    secret: {
        type: String,
        required: true,
        trim: true,
        unique: true,
    },
    user: {
        type: Schema.Types.ObjectId,
        required: true,
        ref: "user",
    },
    used: {
        type: Boolean,
        required: true,
        default: false
    }
};

export let schema = new Schema(schemaData, { shardKey: {user: 1} });

export let model = Model("token", schema)

model.find({})
    .exec()
    .then(r => r[0].remove())
    .catch(e => console.error(e))
```
**The following code _does_ work:**
```
    model.find({}).exec().then(r => {
        r.forEach(async row => {
            await model.deleteOne({_id: row.id, user: row.user})
                .catch(e => console.error(e))
        })
    })
```
The shard key is `user`, and it doesn't work on `findById`, `findOne`, etc. Find methods work as expected, and all the documents in the collection are valid and have a valid `user` value.

### What is the expected behavior?
Send the shard key with the ID on `remove()`.

### Please mention your node.js, mongoose and MongoDB version.
**Node:** v11.3.0
**Mongoose:** 5.3.15
**MongoDB:** Azure CosmosDB (compatible with MongoDB version 3.2)

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in 5.4.4.

Also, FYI, Mongoose does [not support destructured imports in general](https://mongoosejs.com/docs/faq.html#destructured-imports). I recommend you use `import mongoose from 'mongoose'`, there may be bugs with alternative syntaxes.
