### ISSUE TITLE
"addCursorFlag is deprecated" warning when tests are run

### ISSUE THREAD

**Issue by epicfaace** [Automattic/mongoose#7394]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I run tests using `npm test`, this warning shows:
```
(node:3047) DeprecationWarning: Mongoose: `Aggregate#addCursorFlag()` is deprecated, use `option()`instead
```

**What is the expected behavior?**
No warnings

**Please mention your node.js, mongoose and MongoDB version.**
Mongoose v5.4.2
MongoDB v4.0.1
Node v8.12.0

**Comment by epicfaace** [comment]
@vkarpov15  This runs from a test that is already written though. Nothing got to do with my code.

**Comment by vkarpov15** [comment]
@epicfaace can you show the test please?
