### ISSUE TITLE
E11000 Duplicate Key Error with New Indexes After Removing `Unique: True`

### ISSUE THREAD

**Issue by dark-swordsman** [Automattic/mongoose#7396]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am getting the infamous E11000 duplicate key error, however, I can't simply drop indexes or the database since it's a production environment for my company. I have found no other solution after hours of digging on the web.

Previously in a model, we had `urlName: { type: String, required: true, unique: true, lowercase: true, trim: true }`. After removing `unique: true` and restarting the dev server, the first document saves with one urlName, but the second one with the same urlName gets the same error.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Have model with `urlName` entry set to `unique: true`
- Try to make two entries with the same urlName (expected to not work)
- Doesn't save second one
- Remove `unique: true` from urlName on model
- Make new entry with a new urlName
- Entry saves
- Make second entry with this same new urlName
- Second one still has same error and doesn't save even though `unique` is not set to `true` anymore

**What is the expected behavior?**
Multiple documents can have the same urlName. 

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.11.4
Mongoose: 5.3.9
MongoDB: unknown (will edit)

**Comment by vkarpov15** [comment]
[All `unique` does is build a unique index](https://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator). So you would have to actually drop the unique index.

You might want to try [`Model.syncIndexes()`](https://mongoosejs.com/docs/api.html#model_Model.syncIndexes), that function adds/drops indexes so they line up with your schema.

**Comment by dark-swordsman** [comment]
@vkarpov15 Okay. So this simply re-indexes the entries? It doesn't actually drop any documents or lose them?

**Comment by vkarpov15** [comment]
@dark-swordsman dropping an index doesn't drop any documents

**Comment by Rohit8376** [comment]
thanks @dark-swordsman this will solve my problem had wasted lots of time in it thanks gain
