### ISSUE TITLE
Populate `match` option as a function

### ISSUE THREAD

**Issue by dupkey** [Automattic/mongoose#7397]
**Do you want to request a *feature* or report a *bug*?**
Help

**What is the current behavior?**
I'm trying to "match" a referenced document (populated) with the parent document id. Example below.

The goal is to only show members permissions for the specific organization and not all the other permissions they may have. So the 'entity.item', in this case an organization, would have to match the parent organization id. I'm trying to find out how, if possible, to access the parent organization id from a child doc.

```
let userId = '123';
return await Organization.find().where('members.includes(userId)').populate({
  path: 'members',
  options: { sort: { name: 1 } },
  populate: {
    path: 'permissions',
    match: {
      'entity.kind': 'Organization',
      'entity.item': organization._id    // HERE
    },
    populate: {
      path: 'entity.item'
    }
  }
});
```

**What is the expected behavior?**
Some kind of way to reference the row id of the parent doc.

**Please mention your node.js, mongoose and MongoDB version.**
Node: v8.12.0
Mongoose: 5.3.14
MongoDB: 4.0.1

**Comment by vkarpov15** [comment]
Not possible right now unfortunately, you'll need to loop over each organization and populate manually:

```javascript
const orgs = await Organization.find().where('members.includes(userId)');
for (const org of orgs) {
  await org.populate({
    path: 'members',
    populate: { path: 'permissions', match: { 'entity.item': org._id } }
  }).execPopulate();
}
```

See docs:
* https://mongoosejs.com/docs/api.html#document_Document-populate
* https://mongoosejs.com/docs/api.html#document_Document-execPopulate

We should add support for function `match` in a future release.

**Comment by dupkey** [comment]
I ended up using the lookup operator on the aggregate method. Still testing use cases but seems to be working.

```
let organizations = await Organization.aggregate([
  { $sort: { name: 1 } },
  { $match: { $expr: { $in: [ user.id, '$members' ] } } },
  {
    $lookup: {
      from: 'user',
      let: { id: '$_id', members: '$members' },
      pipeline: [
        { $match: { $expr: { $in: [ '$_id', '$$members' ] } } },
        { $addFields: { id: '$_id' } },
        {
          $lookup: {
            from: 'permission',
            pipeline: [
              { $match: { $expr: { $and: [
                { $eq: [ '$entity.kind', 'Organization' ] },
                { $eq: [ '$entity.item', '$$id' ] }
              ] } } },
              { $addFields: { id: '$_id' } },
              {
                $lookup: {
                  from: 'organization',
                  pipeline: [
                    { $match: { $expr: { $eq: [ '$_id', '$$id' ] } } },
                    { $addFields: { id: '$_id' } }
                  ],
                  as: 'entity.item'
                }                      
              }
            ],
            as: 'permissions'
          }
        }
      ],
      as: 'members'
    }
  },
  { $addFields: { id: '$_id' } }
]);
```

**Comment by dupkey** [comment]
I just realized you tagged this 'new feature' so I'll reopen. It would be great if mongoose could simplify joins.
