### ISSUE TITLE
User.set is not a function

### ISSUE THREAD

**Issue by crazycodewriter** [Automattic/mongoose#7399]
We are trying to update user profile details and whatever we do it throws an error.
The local server runs perfectly when we click the update settings button for updating user details it throws User.set is not a function. 

**Model**

```
const userSchema = new mongoose.Schema({
      username: { type: String },
      email: { type: String },
      isVerified: { type: Boolean, default: false },
      password: { type: String },
      passwordResetToken: String,
      passwordResetExpires: Date,
      firstName: { type: String },
      lastName: { type: String },
      jobTitle: { type: String },

module.exports = mongoose.model('User', userSchema);
```

**Controller**

```
async EditUser(req, res,next) {
User.findById(req.user.id, function (err, user) {

  if (!User) {
    return res
    .status(httpStatus.INTERNAL_SERVER_ERROR)
    .json({ message: 'User is not found' });
}

  const schema = Joi.object().keys({
    username: Joi.string()
                .min(4)
                .max(10)
                .required(),
            email: Joi.string()
                .email()
                .required(),
            firstName: Joi.string().required(),
            lastName: Joi.string().required(),
            jobTitle: Joi.string().required(),
  });

  const { error, value } = Joi.validate(req.body, schema);
  if (error && error.details) {
    return res.status(HttpStatus.BAD_REQUEST).json({ msg: error.details })
  }

        const email = Helpers.lowerCase(req.body.email);
        const username = Helpers.lowerCase(req.body.username);
        const firstName = req.body.firstName;
        const lastName = req.body.lastName;
        const jobTitle = req.body.jobTitle;

        User.set({
            email: email,
            firstName: firstName,
            lastName: lastName,
            username: username,
            jobTitle: jobTitle
})

User.save(function (error, updatedUser) {
  if (error) {
    return res
    .status(httpStatus.INTERNAL_SERVER_ERROR)
    .json({ message: 'User is wrong' });
  }
})
});
}

```
**Mongoose version**

`"mongoose": "^5.2.1",`

we tried to use user.set in that case it throws can't read property 'set' of null when using User.set it throws user.set is not a function. The same thing happened to save function in the past when we didn't implement set. yet. After adding set it throws for that one since it is used on the top of save.

**Comment by crazycodewriter** [comment]
@vkarpov15 Thanks for replying. In your advised case, when I click the update button it throws internal server error with the user is not found.  While other user-specific functions are working perfectly at the same time besides this one. Also here is its router.
`router.post('/user/edit-user', AuthHelper.VerifyToken, UserCtrl.EditUser);`

**Comment by vkarpov15** [comment]
Check to see that `req.user.id` is actually set and is the value that you expect. You can either `console.log(req.params.id)`, or turn on [`mongoose.set('debug', true)`](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-set)
