### ISSUE TITLE
findByIdAndUpdate

### ISSUE THREAD

**Issue by masoudmp** [Automattic/mongoose#7401]
**Please mention your node.js, mongoose and MongoDB version.**
MongoDb Atlas VERSION 4.0.5
mongoose version : 5.4.2
nodejs : v10.11.0

using findByIdAndUpdate returns this warning : 
(node:7916) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.

my code:
router.put("/:id", async (req, res) => {
  const { error } = validateGenre(req.body);
  if (error) return res.status(400).send(error.details[0].message);

  const genre = await Genre.findByIdAndUpdate(
    req.params.id,
    { name: req.body.name },
    { new: true }
  );
  if (!genre)
    return res.status(404).send("The genre with the given ID was not found.");

  res.send(genre);
});

**Comment by vkarpov15** [comment]
Please see [these docs](https://mongoosejs.com/docs/deprecations.html#-findandmodify-)
