### ISSUE TITLE
BUG? : Setter ONLY working with findOneAndUpdate

### ISSUE THREAD

**Issue by fazulk** [Automattic/mongoose#7404]
mongoose version 5.4.2
node 8.9.4

BUG (possibly?)

Setters are only firing on findOneAndUpdate, they are not working on any queries, or any other "Updates"

        const name = `serials`,
            schema = new Schema(
                {
                    number: {
                        type: String,
                        unique: true,
                        trim: true
                    },
                    shipDate: {
                        type: Date,
                        set: function(a) {
                            console.log(`HI IM WORKING`, a)
                        }
                    }
                },
                {
                    timestamps: true
                }
            )

        mongoose.models[name] = db.model(name, schema)

///////////////////

    async function TEST_A(req, res, next) {
        let list = await Serials.find()
            res.json(list)
    }
    router.get(`/test-route`, TEST_A)

Console.log should display anytime serials model is called - correct?

**Comment by vkarpov15** [comment]
@fazulk for queries, the custom set will be called any time `shipDate` is in the filter or the update. If the `shipDate` key is not in either the filter or the update, the setter won't run on the query. For example:

```javascript
  const schema = new Schema({
    name: String,
    shipDate: {
      type: Date,
      set: function(v) {
        console.log('Set', v);
        return v;
      }
    }
  });
  const Model = mongoose.model('Test', schema);

  await Model.find({ shipDate: '2018-06-01' }); // Yes
  await Model.find({}); // No

  await Model.updateOne({}, { shipDate: '2017-06-01' }); // Yes
  await Model.updateOne({}, { name: 'test' }); // No
```

Does this make sense?

**Comment by fazulk** [comment]
Absolutely, thank you!
