### ISSUE TITLE
Is it safe/ok to create static ATTRIBUTES on schema?

### ISSUE THREAD

**Issue by mhombach** [Automattic/mongoose#7411]
This is a question which could lead into a feature-request.

The mongoose-docs show that it's possible to assign functions directly to the schema:

```js
// assign a function to the "statics" object of our animalSchema
  animalSchema.statics.findByName = function(name, cb) {
    return this.find({ name: new RegExp(name, 'i') }, cb);
};
```
I want to know if it's possible to also create static attributes on a schema like this:
```js
animalSchema.statics.bestAnimal = "dog";
/// ... later in code
let pet = await Animal.findOne();
if(pet == Animal.bestAnimal ) {
  console.log("i am happy");
}

// ... and i want to be able to change the attribute later on runtime
if(pet.cute == true) {
  Animal.bestAnimal = pet;
  // or like this
  Animal.changeBestAnimal(pet);
}
```

Update:
I did test the scenario and it seems to work just like i wrote in my example. But i still wonder if this is "clean" and intented, because it's not explicitly documented in the docs...

**Comment by vkarpov15** [comment]
Static attributes should be fine as long as they don't conflict with any Mongoose functions. We generally don't document it because I don't see it being a common enough use case.
