### ISSUE TITLE
DeprecationWarning: collection.count is deprecated

### ISSUE THREAD

**Issue by bcmux** [Automattic/mongoose#7412]
**Do you want to request a feature or report a bug?**
Bug.

**What is the current behavior?**

> DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

**If the current behavior is a bug, please provide the steps to reproduce.**
Use **findById** on a schema.

**What is the expected behavior?**
**Query.prototype._count** should be updated to use **countDocuments** rather than **count**.

**Problem:**
https://github.com/Automattic/mongoose/blob/a3988096afe0abd4d9dab7cab559bd8beb1514c5/lib/query.js#L2086

**Fix:**
```
this._collection.countDocuments(conds, options, utils.tick(callback));
```

**Please mention your node.js, mongoose and MongoDB version.**
Node@10.15.0
mongoose@5.4.3
MongoDB@3.6

**Comment by vkarpov15** [comment]
The below script doesn't print any deprecation warnings. Please modify the below script to repro your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7412`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  await Model.findById(new mongoose.Types.ObjectId()); // No warning
}
```

And we aren't going to change that line, because [`count()`](https://mongoosejs.com/docs/api.html#query_Query-count) and [`countDocuments()`](https://mongoosejs.com/docs/api.html#query_Query-countDocuments) are handled slightly differently by the MongoDB server, so changing this might have unexpected consequences for some users.

**Comment by achalkias** [comment]
Still there is a deprecation warning.  

DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

"mongoose": "^5.4.5",
"mongoose-paginate": "^5.0.3",

**Comment by janexpando** [comment]
@vkarpov15 
Documentation says, that method count is deprecated: 
https://mongoosejs.com/docs/api.html#query_Query-count

Not changing that line will have unexpected consequences for all users in the future.

**Comment by vkarpov15** [comment]
See [deprecation warning docs for how to work around this](https://mongoosejs.com/docs/deprecations.html#-count-)
