### ISSUE TITLE
Mongoose can not check unique field.

### ISSUE THREAD

**Issue by sangjs** [Automattic/mongoose#7413]
Mongoose 5.4.1
My Schema like this
```javascript
email: {
    type: Schema.Types.String,
    unique: true,
    description: 'The email of user',
    required: true
  }
```
But unique property do not work.

**Comment by vkarpov15** [comment]
Please define what you mean by "do not work." Also, please read [this section of the docs](https://mongoosejs.com/docs/validation.html#the-unique-option-is-not-a-validator) and make sure your [indexes are building correctly by listening to `Model.on('index', err => console.log(err))`](https://mongoosejs.com/docs/api.html#model_Model.init)

**Comment by gempeler** [comment]
Try to drop the index from your collection. If your collection is named 'users' and your index name is 'email_1' then run the following command in the mongo Shell: 

```
db.users.dropIndex('email_1')
```

This worked for me when I changed unique to true on a **exisiting** collection
