### ISSUE TITLE
Error: Cyclic Dependancy Detected

### ISSUE THREAD

**Issue by AlfiePerkins123** [Automattic/mongoose#7415]
Edit: This is my first time posting an issue, if i did something wrong please let me know!

I am using the correct version of mongoose, all my modules are up to date

**Do you want to request a *feature* or report a *bug*?**
I'd like to report a bug

**What is the current behaviour?**
When adding a member to an array i get "Cyclic Dependency Detected"

**If the current behaviour is a bug, please provide the steps to reproduce.**
Just adding a string to an array(not sure what to put here tbh)

`   else return Teams.findOneAndUpdate({ $push: { Members: addMember }}) `
Schema: `const mongoose = require("mongoose");

const teamSchema = mongoose.Schema({
    TeamName: String,
Captain: String,
CaptainID: String,
Members: Array

})

module.exports = mongoose.model("Teams", teamSchema)`

**What is the expected behaviour?**
Its supposed to add "addMember" to the Members array
**Please mention your node.js, mongoose and MongoDB version.**
Mongoose: 5.4.3
Node: 10.9.0

**Comment by mhombach** [comment]
Welcome :)
I tried to reproduce your error and on my system it works.
The errormessage "cyclic dependency" is hinting you to a problem of this type:
- Package/Library A needs Package/Library B to run
- Package/Library B needs Package/Library A to run

So Package A needs Package B, which needs Package A but A needs B which needs A which needs B which needs.... i hope you get my point ;)
For us beeing able to further help you, we need more code.
If your project is public, you can link it.
If not, try to reduce your code to a minimal version but with the error still there.

**Comment by AlfiePerkins123** [comment]
Hi! Here is the code for adding a member: http://www.hatebin.com/vrtuuoqrel

I understand what you mean but not really how to fix it aha.

Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by AlfiePerkins123** [comment]
Right im back home now infront of my pc!

This is wear the error occurs, since whenever you try and Push The member to the team it gives the cyclic dependency detected and doesn't push them!

`else return Teams.findOneAndUpdate({ $push: { Members: addMember }}) `

**Comment by mhombach** [comment]
Please provide the exact errormessage and give us more details about what the actual data is.
Also, please give us insight on what `addMember` contains the exact moment before it is going to be pushed by the query.
If you can, try to give us one complete code-snippet that we can copy and run on our systems. Pushing to an array in mongoose works, so the error must be somewhere else. And for that we need more (or all) code :)

**Comment by AlfiePerkins123** [comment]
Right, thank you so much for this when you said what it contains it made me want to actually check what it did contain, i presumed it contained their username but i didn't actually have that in the code.

Its now fixed i needed to change `  let addMember = message.mentions.members.first()` to `let addMember = message.mentions.members.first().user.username;` Which now made it a string!
