### ISSUE TITLE
Update Field Within Array

### ISSUE THREAD

**Issue by Luk3HD** [Automattic/mongoose#7420]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I'm trying to update a pythias inside a field in an array. I could not currently do that. I have tried everything and a colleague of mine said that it is only possible to modify if you modify the whole field.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
update only the expired field inside the mutes array

**Please mention your node.js, mongoose and MongoDB version.**
```
exports.unmute= async (guild, id) =>{
    const guild= Guild.findOneAndUpdate({id: guild}, function (erro, done){
      console.log(done)
        if(done) done.updateOne({"mutes.id": id, "mutes.expired":false}, {$set: {"mutes.$.expired":true}}, (erro,aew) =>{
          if(erro) console.log(erro)
          if(aew) console.log(aew)
          done.save()
        })
    })
}
```

NodeJS: v10.12.0
Mongoose: 5.4.4

**Comment by mhombach** [comment]
Please reformat the code, so that we can read it better :)

**Comment by vkarpov15** [comment]
You're looking for $elemMatch : https://docs.mongodb.com/manual/reference/operator/query/elemMatch/

Also, why are you doing findOneAndUpdate and then a separate update? That seems wasteful at first glance
