### ISSUE TITLE
Mongoose gives Cast to ObjectId failed for a nested Schema

### ISSUE THREAD

**Issue by LukvonStrom** [Automattic/mongoose#7429]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
Given the Schemas, which are listed below, the Database gives this cryptic error when I attempt to read all of the Projects `find().exec()` (after successfully writing the JSON String listed below)

`CastError: Cast to Array failed for value "[ { name: 'Container 3',
          typeC: 'container',
          containerContent: null,
          taskContent: [ [Object] ] } ]" at path "containerContent"`

**Please provide the steps to reproduce.**
### Project Schema
```
export const ProjectSchema = new mongoose.Schema({
  content: ContainerSchema,
});

ProjectSchema.pre('find', function() {
  this.populate('content');
})
```

### Container Schema
```
export const ContainerSchema = new mongoose.Schema({
  name: String,
  typeC: { type: String, enum: ['container'] },
  taskContent: [TaskSchema],
  containerContent: [this],
}, { _id: false });
```

### Task Schema
```
export const TaskSchema = new mongoose.Schema({
  title: String,
});
```

### JSON string I want to write in the `content` field of the Project Schema:
```
{
  "name": "Container1",
  "typeC": "container",
  "containerContent": [
    {
      "name": "Container 2",
      "typeC": "container",
      "taskContent": [],
      "containerContent": [
        {
          "name": "Container 3",
          "typeC": "container",
          "containerContent": [],
          "taskContent": [
            {
              "title": "Expensive Task2"
            }
          ]
        }
      ]
    }
  ],
  "taskContent": []
}
```

**What is the expected behavior?**
I expected a successful read of the Project Model without any errors

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS v 10.10.0, mongoose v5.4.3, mongodb-memory-server 2.9.3

**Comment by mhombach** [comment]
On me this is working perfectly fine. so i guess your error has to be somewhere else.
Can you check if my code runs on your side without any problems and then try to find any difference?
```js
const mongoose = require('mongoose');
const DB = 'test_db';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { family: 4, useNewUrlParser: true };

const TaskSchema = new mongoose.Schema({
    title: String,
});

const ContainerSchema = new mongoose.Schema({
    name: String,
    typeC: { type: String, enum: ['container'] },
    taskContent: [TaskSchema],
    containerContent: [this],
}, { _id: false });

const ProjectSchema = new mongoose.Schema({
    content: ContainerSchema,
});

ProjectSchema.pre('find', function() {
    this.populate('content');
});

var ProjectModel = mongoose.model('Project', ProjectSchema);

async function run() {
    await mongoose.connect(URI, OPTS);
    let testString = `
    {
        "name": "Container1",
        "typeC": "container",
        "containerContent": [
          {
            "name": "Container 2",
            "typeC": "container",
            "taskContent": [],
            "containerContent": [
              {
                "name": "Container 3",
                "typeC": "container",
                "containerContent": [],
                "taskContent": [
                  {
                    "title": "Expensive Task2"
                  }
                ]
              }
            ]
          }
        ],
        "taskContent": []
      }
    `;
    await ProjectModel.create({
        content: JSON.parse(testString)
    });
    var find = await ProjectModel.findOne();
    console.log("found:" + JSON.stringify(find));
}
run();
```

**Comment by LukvonStrom** [comment]
I think I found a working solution. Thanks to @mhombach, I could reproduce that mongoose does not support populating a subschema (at least at my local machine) and that I "double stringified" the payload for inserting, which did not work for mongoose somehow (It had problems with the newline chars). Thx for helping!
