### ISSUE TITLE
ignored mongoose.connect()'s options?

### ISSUE THREAD

**Issue by EinYs** [Automattic/mongoose#7436]
expected behavior
some options like mongoose.connect ( {useNewUrlParser: true} ) works well

what happened
I got depreciation warning which suggests to use the options which I'm using

**Please mention your node.js, mongoose and MongoDB version.**
node v10.11.0
mongoose v4.13.18

I suppose current version 4.13.18 is ignoring mongoose.connect()'s options. I got all depreciation warning even though I put that options, and mongoose could not parse my URI, 
I roll-backed mongoose version to 5.2.12, all warnings gone and cleanly worked.

**Comment by mhombach** [comment]
`{useNewUrlParser: true} ` is working fine in my code, without any deprecation warning.
Please provide all of the code that is related to connecting to mongoose and also post the exact errormessage you are given.

**Comment by EinYs** [comment]
> I could reproduce error. repo [https://github.com/EinYs/mongoose-rep.git](url)
To do it,  first please set your mongodb uri in dotenv file (I'm using 'mongodb+srv://' shaped one) , and command 'npm run dev'

errormessage (my project folder name : mongoose-rep)

`Error: Invalid mongodb uri "mongodb+srv:// <--((((my private uri))))--> ". Must begin with "mongodb://"
    at muri (C:\ ... \mongoose-rep\node_modules\muri\lib\index.js:28:11)
    at NativeConnection.Connection._handleOpenArgs (C:\Users\...\mongoose-rep\node_modules\mongoose\lib\connection.js:199:16)
    at NativeConnection.<anonymous> (C:\Users\ ... \mongoose-rep\node_modules\mongoose\lib\connection.js:309:37)
    at NativeConnection.deprecated [as open] (internal/util.js:67:15)
    at Mongoose.connect (C:\Users\ ... \mongoose-rep\node_modules\mongoose\lib\index.js:268:47)
    at Object.<anonymous> (C:\Users\ ... \mongoose-rep\api\index.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
i Preparing project for development                                                                                                                                               20:43:01
i Initial build may take a while                                                                                                                                                  20:43:01
**(node:7148) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client**
Server is listening on http://localhost:3000
√ Builder initialized                                                                                                                                                             20:43:01
√ Nuxt files generated                                                                                                                                                            20:43:01`

With mongoose 5.2.12, my code is okay.

**Comment by mhombach** [comment]
Look at your errormessage:
`Error: Invalid mongodb uri "mongodb+srv:// <--((((my private uri))))--> ". Must begin with "mongodb://"`
If you don't want to give us the full string of your uri, that's fine, but please provide it neithertheless (you can anonymize some parts in the middle, but the important part is the beginning).
Also: Please change, for debugging purpose only, to using a static string-variable in your index.js file with your uri and not reading it from the environment.
If you can do this and give us feedback, i am sure we can help you :)

**Comment by mhombach** [comment]
As long as you don't give an example of what your final uri looks like, nobody can help you solve this.
Just replace your real ip/servername with a random one when posting it here but please give us an example on what your final uri looks like.
The way you have described your uri in your repo is wrong. But i cannot tell for sure if that's the real error because i need a final example-uri.

**Comment by EinYs** [comment]
mongodb+srv://AAAAAA:11111111@ccccccccc-dddddd.mongodb.net/test

And what do you mean by '"mongodb+srv://" at the start of an uri will not work.'? I said two times my code is okay with another version of mongoose. I don't need help but just reporting :)

**Comment by mhombach** [comment]
https://mongoosejs.com/docs/connections.html

> **useNewUrlParser** - The underlying MongoDB driver has deprecated their current connection string parser. Because this is a major change, they added the **useNewUrlParser** flag to allow users to fall back to the old parser if they find a bug in the new parser. You should set **useNewUrlParser**: **true** unless that prevents you from connecting. Note that if you specify **useNewUrlParser**: **true**, you **must** specify a port in your connection string, like **mongodb://localhost:27017/dbname**. **The new url parser does not support connection strings that do not have a port, like mongodb://localhost/dbname**.

So the official documentation are already telling you that your provided connection-string is not going to work together with `useNewUrlParser: true` (which you are using).
Try to reformat the uri-string to something like this:
`mongodb://AAAAAA:11111111@ccccccccc-dddddd.mongodb.net/test`
and tell us if that worked :)

**Comment by vkarpov15** [comment]
`mongodb+srv` URIs aren't supported in Mongoose 4 AFAIK. You should use Mongoose 5.x for that.
