### ISSUE TITLE
findById throws unhandled promise rejection warning

### ISSUE THREAD

**Issue by LonJonn** [Automattic/mongoose#7439]
Not sure if this is intended or not, but when using findOne by field, for e.g.
```javascript
let foundUser = await User.findOne({ email: "foo" });
if (!foundUser) ...
```
foundUser will be "null" if no user is found, allowing for conditional statements
  
however,
```javascript
let foundUser = await User.findById(id);
if (!foundUser) ...
```
throws an unhandledPromiseRejectionWarning, same for .findOne({ _id: id })
Thanks.

**Comment by mhombach** [comment]
I just tested this.
This code here should of the same type as yours but it doesn't throw any error:
```js
const MyModel = mongoose.model("MyModel", new mongoose.Schema({name: String, _id: String}));
// connect to db...
await MyModel.create({name: "user1", _id: "m"});
  await MyModel.create({name: "user2", _id: "b"});

  let test1 = await MyModel.findOne({name: "t"}).exec();
  let test2 = await MyModel.findOne({_id: "o"}).exec();
  let test3 = await MyModel.findById("l").exec();
```
It also doesn't throw any error if i don't put the `.exec()` at the end of each query.
Can you check if my code-example throws errors on your machine?

**Comment by LonJonn** [comment]
Nevermind, im an idiot. It was trying to convert "" into an mongo ObjectId, which is impossible and then threw a CastError in an unhandledRejectionWarning since I was using async/await. I just need to use try catch to solve this. Thanks.

**Comment by mhombach** [comment]
Glad you found your mistake :)
If there isn't any question left regarding this issue, it would be nice if you could close this issue, so it doesn't get focused by others anymore =)
