### ISSUE TITLE
call Document.prototype.update only change the db record,not include the instance object?

### ISSUE THREAD

**Issue by fuguohong** [Automattic/mongoose#7444]
**What is the current behavior?**

const inst = await MyModel.findById( id )
console.log(inst.name) // aaa
await inst.update( {name:"bbb"} )
console.log(inst.name) /// aaa , in db its bbb

**What is the expected behavior?**
await inst.update( {name:"bbb"} )
console.log(inst.name) /// bbb

**Please mention your node.js, mongoose and MongoDB version.**
node : 10.14.1
mongoose: 5.4.5

**Comment by vkarpov15** [comment]
Yes, [`Document#update()`](https://mongoosejs.com/docs/api.html#document_Document-update) and [`Document#updateOne()`](https://mongoosejs.com/docs/api.html#document_Document-updateOne) are currently just shorthands for [`Model.update({ _id: doc._id })`](https://mongoosejs.com/docs/api.html#model_Model.update)
