### ISSUE TITLE
How to update nested array of all elements in mongodb

### ISSUE THREAD

**Issue by PRUDHVi100** [Automattic/mongoose#7445]
My database structure is like this.
```
_id:12345
Article:Array
0:Object
articleId:789
Content:Array
0:Object
title:"xx"
1:Object
title:"yy"
2:Object
title:"zz"
```

I am trying to update all title elements in content array.
I wrote this
```
userRouter.post('/updatecontent',(req,res)=>{
    console.log(req.body._id);
    console.log(req.body.articleId);
    console.log(req.body.title);
    Collections.user.update({_id:req.body._id,article:{$elemMatch:{articleId:req.body.articleId}}},{"$set":{"article.0.content.$[].title":req.body.title}},function(err,result){
        if(err)
        res.send(err)
        else
        res.send(result)
        console.log(result);
    })
})
```

Here the data is updating but only one problem. let if i kept 0 object of title is Apple and 1 object of title is Orange and 2 object of title is Mango. then i am getting result all objects of title is Mango only.

Can someone please help. How to sort out this and what i need to put.
Thanks in advance.

**Comment by vkarpov15** [comment]
Can you please put your data structure in JSON? I don't understand the "database structure" snippet.
