### ISSUE TITLE
Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by crsten** [Automattic/mongoose#7446]
**Bug?**

I'm running mongoose in production and i'm getting this error several times a day in the last couple of days. Did an update from 5.1.2 to 5.4.6 10 days ago but i'm not sure if it is related to this issue.

It is very hard to debug since i can't reproduce it actively. It just happens some times.

Here is a screenshot from sentry.io:

![image](https://user-images.githubusercontent.com/7532696/51669341-8cee7680-1fc4-11e9-99f3-285cb639a179.png)

Would appreciate if someone with deeper knowledge could point me in the right direction. 

Node: 10.13.0
mongoose: 5.4.6
MongoDB: 3.2

**Comment by LucGranato** [comment]
@vkarpov15 please I'm running with this issue too on production..

**Comment by vkarpov15** [comment]
Should be fixed by #7451, will release 5.4.7 tomorrow

**Comment by crsten** [comment]
Any updates on this?

**Comment by vkarpov15** [comment]
@crsten we released 5.4.7, should be fixed in that release. Are you still experiencing this issue?
