### ISSUE TITLE
String is not cast to ObjectId in array of subdocuments

### ISSUE THREAD

**Issue by GriffinSauce** [Automattic/mongoose#7449]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Strings that should be ObjectIds are not casted for subdocuments. It may be relevant that these subdocuments are set with discriminators.

```.js
Order.count({
  'lines.sellerId': '5bc0afe0dd135e925b55e6ff',
}),
// -> Does not find anything

Order.count({
  'lines.sellerId': new mongoose.Types.ObjectId('5bc0afe0dd135e925b55e6ff'),
})
// -> returns correct count
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The schema: Order.js (the relevant parts):
```.js
const mongoose = require('../../utils/mongoose');
const { Schema } = mongoose;

// There are some other kinds besides this one
const ListingLineSchema = new Schema({
    sellerId: Schema.Types.ObjectId,
    // More props
});

const OrderSchema = new Schema(
    {
        lines: [
            new Schema(
                {
                    amount: Number,
                },
                {
                    discriminatorKey: 'kind',
                },
            ),
        ],
        // More props
    }
);

const lineArray = OrderSchema.path('lines');
lineArray.discriminator('listing', ListingLineSchema);

module.exports = mongoose.model('Order', OrderSchema);
```

An example document (filtered to relevant parts):
```.js
{
    "_id" : ObjectId("5bf673faf66e9e007cac3a32"),
    "lines" : [
        {
            "_id" : ObjectId("5bf673faf66e9e007cac3a34"),
            "kind" : "listing",
            "sellerId" : ObjectId("5bc0afe0dd135e925b55e6ff"),
            "amount" : 100
        },
    ],
}
```

See the queries above, both `count` and `find` display the same behaviour. Using `$elemMatch` also doesn't help.

**What is the expected behavior?**

Mongoose should cast the query value to an objectId.

**Please mention your node.js, mongoose and MongoDB version.**

node: 8.15
mongoose: 5.3.3
mongodb: 3.6.8

**Comment by vkarpov15** [comment]
For now, this is intended behavior because Mongoose doesn't know what type `sellerId` should be. What if you have multiple discriminators under `Order.lines` that specify different types for `sellerId`? We'll improve this in the future for cases when there's only one discriminator that specifies `sellerId`.

However, there is another bug here because the below should work:

```javascript
await Order.count({
  lines: {
    $elemMatch: {
      kind: 'listing',
      sellerId: '5bc0afe0dd135e925b55e6ff'
    }
  }
})
```

But unfortunately it doesn't cast `sellerId`. We'll fix that.
