### ISSUE TITLE
Error: Cannot find module './drivers/node-mongodb-native/connection

### ISSUE THREAD

**Issue by shadiabusamra** [Automattic/mongoose#7450]
Locally working fine but when uploading it to lambda the issue occurred.

"mongoose": "5.4.6"

**Comment by vkarpov15** [comment]
Not enough info to take action on this. How are you bundling your lambda function? Please provide a detailed description with package versions, configs, code samples, etc.

**Comment by michaelbats** [comment]
@shadiabusamra  have you found a solution to this? just ran into it myself...
