### ISSUE TITLE
Continuous Disconnect Connect Loop when connecting with MongoLab

### ISSUE THREAD

**Issue by cpres** [Automattic/mongoose#7452]
With a brand new setup of a server using the latest Mongoose (v5.4.6), when I just leave the server on, after about 30 (or much less sometimes) seconds I start to see "database disconnected" then "database connected", on and on, each after about 5 seconds... Following all the basic tutorials out of the box I was very confused, and then I decided to roll back to Mongoose 4.11.9, and no more disconnects! Just stable.

So changed to '5.3.4' and interestingly enough in the console I get:
database reconnected!
database reconnected!
database reconnected!
This happens every 10 seconds. 

node v11.2.0 and v8.11.3
mongolab: mongod version: 3.4.14

**Comment by vkarpov15** [comment]
Can you provide some code samples that show what events you're listening to?

**Comment by cpres** [comment]
> 	const options = {
		bufferCommands: false,
		poolSize: 3,
	    keepAliveInitialDelay: 3000000,
	    connectTimeoutMS: 5000,
        socketTimeoutMS: 5000,
        // MaxConnectionIdleTime: TimeSpan.FromMinutes(1),
        reconnectInterval: 10000,
        reconnectTries: 3,
        autoReconnect:true
	};
	mongoose.connect(_cs, options);
	_connection = mongoose.connection;

    _connection.once('open', function() {
        console.log('once connected');
    })
	_connection.on('connected', function() {
		console.log('database connected');
	});
	_connection.on('close', function() {
		console.log('database connection closed');
    });
    _connection.on('reconnected', function () {
        console.log('database reconnected!');
      });

>
