### ISSUE TITLE
Virtuals from populated object (Cross db populate on post hook middleware on schema level)

### ISSUE THREAD

**Issue by Ncifra** [Automattic/mongoose#7454]
We want to implement some "fake" virtuals as discussed below:

After initialiazing the `user` document we want to populate it with some data from the user (let's call them `userData`) that are in a separate schema. Due to the fact that the API is currently being used and these "separated" data have been up until now inside the main `user` schema, we want to attach the after "populate" data to the old fields. We don't want to use populated virtuals, considering that we would need to do one populate for each virtual, even though they are part of the same schema, we would need to save the populated subdocument + we would need to test this behaviour with cross-db virtual population (virtuals + cross-db haven't been mentioned up until now as far as we have seen).

The way of implementation for that will be this:
```
userSchema.post("init", function (data) {
    if (this.userData) {
        this.populate("userData")
            .execPopulate()
            .then(function(){
                UserData.schema.eachPath(function(path){
                    this[path] = this.userData[path];
                });
            },function (err) {
                //Log keeping
            });
    }
});
```

The problem with the above behaviour, is that `init` hooks are synchronous, while populate is asynchronous. How can we make sure that we don't have deviations in this case?

Mongoose: 5.4.5
MongoDB: 3.4
NodeJS: 8.12.0

**Comment by mhombach** [comment]
Well, since, as you already know, init-hooks are synchnonous, there is no "direct" way of doing this in my opinion.
What you maybe could do:
- create a virtual property called like "postInitPromise" on the userSchema
- within the post-init hook, you `.exec()` your population-query and save the resulting PROMISE-object into the `postInitPromise`-attribute (don't "await" it, just save it there.
- From outside, you can init your object the normal way and then `await doc.postInitPromise` to wait for the fired population-function to be completed.

Can you tell me, if that would work for you or if i misunderstood something in your usecase?

**Comment by Ncifra** [comment]
Yes, thank you, you understood it correctly, and I actually made a bit of the opposite of this just before coming back to the issue:

```
/**
 * Returns a string representing the name of the user
 */
userSchema.virtual("name").get(function () {
    if (this.userData) {
        return this.userData.name;
    } else {
        return null;
    }
});

userSchema.post("init", function (data) {
    if (this.userData) {
        this.populate("userData")
            .execPopulate()
            .then(function () {
            }, function (err) {
                //Log keeping
            });
    }
});
```

The problem with what I have made above, is that I am not waiting for the populate to finish, so the virtual may get an undefined `name` (especially considering that the `userData` schema will be in a separate server).

The problem with your suggestion, if I understand it correctly, is that I won't be able to send the user directly, since the virtual itself is an unresolved promise. So I would need to resolve it somewhere before using it normally. Maybe it's just that I am getting a bit lost in promise-async/await logic, having been used more to callback logic, but please advise.

Thank you again.

**Comment by Ncifra** [comment]
Yes, I studied them a bit, and was seeing your [@awaitjs/express](https://www.npmjs.com/package/@awaitjs/express) package to fully go from callback based to await/async for express. But for now, there are some limitations with the above approach:

1. Using await for every call to the virtual defeats the purpose of using the middleware hooks to concentrate code and avoid duplication, because this will mean that there will be code like:
```
let user = await User.findOne(byId);
await user.userData;
//We currenty have certain data inside the `user`, like `name`, `lastname`, etc., so we would need to //provide them again as part of the same "object" in the response
//We could do that either like this
user.name = user.userData.name;
user.lastname = user.userData.lastname;
....
//or
UserData.schema.eachPath(function(path){
    //careful not to include fields like `_id` and timestamps that may be the same for schemas
    this[path] = this.userData[path];
});
```
This will happen for every call to findOne(). Maybe if there were some sort of cross schema aliases, so that after population we have the virtuals for our needed fields, the above code after `await` could be spared.
2. Cross-db population for virtuals hasn't been mentioned. I don't know how it has been implemented internally, but this is something to be tested since we are going for cross-db.

For this purpose, I moved previous populate on init() logic to the post("findOne") hook:
```
//Don't mind the name change of the schema name, I actually did a bit of the opposite than before, //instead of populating from `user` to `userData`, it's the opposite. It was an internal thing, not related to //the issue at hand
userDataSchema.post("findOne", function (doc, next) {
    if (doc && doc.userData) {
        doc.populate("userData", null, User).execPopulate()
            .then(function () {
                next();
            }, function (err) {
                next(err);
            });
    } else {
        next();
    }
});
```
And inside the schema I have declared virtuals for every field we need like so:
```
userSchema.virtual("name").get(function () {
    if (this.userData) {
        return this.userData.name;
    } else {
        return null;
    }
});
...
```
It seems to be working okay (which means that virtuals are initialized after the "post findOne" hooks). For now this seems the only solution that provides:

1. Ability to save the nested object due to it being returned from a populate function
2. Having the old fields as part of the same returned object
3. Maintaining existing CRUD routes without many major modifications

This will still mean though that for find() queries there would need to be something else (having a populate() for each returned object would be overkill), so maybe we would need to pass to the aggregation framework for this case, if cross-schema fields are needed.

If anything from the above could be made better, please advise.

Thank you

**Comment by vkarpov15** [comment]
[Cross-db populate](https://mongoosejs.com/docs/populate.html#cross-db-populate) is supported with both conventional populate and [virtual populate](https://mongoosejs.com/docs/populate.html#populate-virtuals), it just becomes a `find()` under the hood.

Also, I don't understand your question about "Chaining a `populate` after the `findOne` function on a nested field that depends on the post("findOne") populate", can you please clarify?

**Comment by Ncifra** [comment]
> [Cross-db populate](https://mongoosejs.com/docs/populate.html#cross-db-populate) is supported with both conventional populate and [virtual populate](https://mongoosejs.com/docs/populate.html#populate-virtuals), it just becomes a `find()` under the hood.

All right, so this is out of the way, but still it doesn't have `mongoose` document methods like `save()` and `remove()` since virtuals shouldn't have data persisting methods if I am not wrong.

> Also, I don't understand your question about "Chaining a `populate` after the `findOne` function on a nested field that depends on the post("findOne") populate", can you please clarify?

Yes, it is a bit fuzzy:
So we have the post("findOne") that populates the `userData` property of `user`. 
```
userSchema.post("findOne", function (doc, next) {
    if (doc && doc.userData) {
        doc.populate("userData", null, UserData).execPopulate()
            .then(function () {
                next();
            }, function (err) {
                next(err);
            });
    } else {
        next();
    }
});
```
And then we want to also `populate()` some data (`status`) inside the resultant `userData` object, after the `findOne()` call to `user`.

`let deepPopulatedUser = await User.findOne(id).populate("userData.status");`

So the nested `status` property of `userData` above is not available to the "chained" `populate()` even though it is after the `findOne()` method that should have also populated the `userData` property `post("findOne")`, and hence made available the nested `status` property. I am expecting that the `post("findOne")` hook executes after the chained methods to `findOne()`.

**Comment by vkarpov15** [comment]
Unfortunately we don't support deep populate with dotted keys, especially since your populate('userData.status') happens before `populate('userData')` . See these docs for how deep populate works: https://mongoosejs.com/docs/populate.html#deep-populate .

In your case you should do `doc.populate('userData.status`).execPopulate()` after your findOne()

**Comment by Ncifra** [comment]
So I am having problems with the above approach that seemed to be correct up until now. It seems that I am not treating very well the asynchronous nature of the requests, because sometimes I do have the populated `userData` model after calling findOne (inside its callback), and sometimes not.

To resume:
Having the following `post("findOne")` middleware inside the user schema:
```
userSchema.post("findOne", function (doc, next) {
    if (doc && doc.userData) {
        doc.populate("userData", null, UserData).execPopulate()
            .then(function () {
                next();
            }, function (err) {
                next(err);
            });
    } else {
        next();
    }
});
```
And then calling:

```
User.findOne(queryCondition, {
                "app_download_code": 0
            }, function (err, prepopulatedUser) {
   //prepopulatedUser.userData is not always a model, sometimes its still an ObjectId
}
```

Judging from the order of things I was expecting to alway have the populated object inside the callback of `findOne`.

**Comment by Ncifra** [comment]
All right, so scratch the part about the destructuring, it was something wrong on my part, but I can confirm that this works with populate() from the Query class, but it doesn't work with the populate() of the Document class (as above).

**Comment by vkarpov15** [comment]
@Ncifra the below script works without error for me and I don't quite understand your comments. Describing code with prose is tricky, it is usually more effective to just show the code. Please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7454`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ name: String, friend: { type: Schema.Types.ObjectId, ref: 'User' } });

  userSchema.post('findOne', (doc, next) => {
    if (doc.friend == null) {
      return next();
    }
    doc.populate('friend').execPopulate().then(() => next(), next);
  });

  const User = mongoose.model('User', userSchema);

  const slash = await User.create({ name: 'Slash' });
  const axl = await User.create({ name: 'Axl Rose', friend: slash._id });

  const res = await User.findOne({ name: 'Axl Rose' });

  console.log(res.friend);
}
```

**Comment by Ncifra** [comment]
Fortunately for this I am reproducing with the simple use case:

```
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7454`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
const {Schema} = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
    const db = await mongoose.connect(connectionString);
    const db2 = mongoose.createConnection(`mongodb://localhost:27017/1001`);
    await mongoose.connection.dropDatabase();

    const userSchema = new Schema({name: String, friend: {type: Schema.Types.ObjectId, ref: 'Member'}});
    const memberSchema = new Schema({name: String});

    const User = db.model('User', userSchema);
    const Member = db2.model('Member', memberSchema);

    userSchema.post('findOne', (doc, next) => {
        if (doc.friend == null) {
            return next();
        }
        doc.populate('friend', null, memberSchema).execPopulate().then(() => next(), next);
    });

    const axl = await Member.create({name: 'Axl Rose'});
    const gnr = await User.create({name: 'GNR', friend: axl._id});

    const res = await User.findOne({name: 'GNR'});

    console.log(res.friend);
}
```

As you may test the population doesn't happen as expected, and instead we get just the `friend` "_id".

**Comment by vkarpov15** [comment]
@Ncifra your example has a couple bugs that you should fix. Once those are fixed, this example works.

1) You must register pre and post hooks _before_ calling `mongose.model()`. See [docs on model compilation](https://mongoosejs.com/docs/models.html#compiling)

2) Where did you get the `doc.populate('friend', null, memberSchema)` syntax? AFAIK that syntax doesn't work nor is it documented anywhere. You should do `doc.populate({ path: 'friend', model: Member })` instead. See [docs](https://mongoosejs.com/docs/api.html#model_Model.populate).

Here's the complete working example:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7454`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;
const {Schema} = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
    const db = await mongoose.connect(connectionString, { useNewUrlParser: true });
    const db2 = mongoose.createConnection(`mongodb://localhost:27017/1001`);
    await mongoose.connection.dropDatabase();

    const userSchema = new Schema({name: String, friend: {type: Schema.Types.ObjectId, ref: 'Member'}});
    const memberSchema = new Schema({name: String});

    userSchema.post('findOne', (doc, next) => {
        if (doc.friend == null) {
            return next();
        }
        doc.populate({ path: 'friend', model: Member }).execPopulate().then(() => next(), next);
    });

    const User = db.model('User', userSchema);
    const Member = db2.model('Member', memberSchema);

    const axl = await Member.create({name: 'Axl Rose'});
    const gnr = await User.create({name: 'GNR', friend: axl._id});

    const res = await User.findOne({name: 'GNR'});

    console.log(res.friend);
}
```

**Comment by Ncifra** [comment]
>     2. Where did you get the `doc.populate('friend', null, memberSchema)` syntax? AFAIK that syntax doesn't work nor is it documented anywhere. You should do `doc.populate({ path: 'friend', model: Member })` instead. See [docs](https://mongoosejs.com/docs/api.html#model_Model.populate).

I got it from the test for cross db [here](https://github.com/Automattic/mongoose/blob/91347cf80271fc968ab385f179858132e177eec3/test/model.populate.test.js#L129-160). I had it wrong above though, according to the cited test instead of `doc.populate('friend', null, memberSchema)` it should have been `doc.populate('friend', null, Member)` (the way I had been using in my code) but the result is the same. 

I see though that it is documented like in your example but I started digging deeper then necessary in examples it seems.

Thank you

**Comment by vkarpov15** [comment]
I fixed the test to use more correct syntax. The `doc.populate('friend', null, memberSchema)` isn't documented. It theoretically could work, but it looks like it doesn't work with `null` as 2nd param. You should use the [object syntax for `Model.populate()`](https://mongoosejs.com/docs/api.html#model_Model.populate)
