### ISSUE TITLE
document.remove() removes document when session is aborted

### ISSUE THREAD

**Issue by jearangoo** [Automattic/mongoose#7455]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
document.save() does not save the document in the database if the transaction associated with the document is aborted( https://mongoosejs.com/docs/transactions.html#with-mongoose-documents-and-save- ) but document.remove() removes the document from the database when the transaction associated with the document is aborted

**What is the expected behavior?**
that document.remove() do not remove the document from the database if the transaction associated with the document is aborted

**Please mention your node.js, mongoose and MongoDB version.**
node v10.14.2, mongoose v5.4.6, mongodb v4.1.1

**Comment by mhombach** [comment]
Can you post a small example-snippet of code so we can easily reproduce this?
Also, if what you are describing is true, i think that would be a **bug** and not a feature request ;)

> The most important feature of transactions is the ability to roll back **ALL** operations in the transaction using the abortTransaction() function. (https://mongoosejs.com/docs/transactions.html#aborting-a-transaction)

**Comment by jearangoo** [comment]
@mhombach of course here is the example
https://github.com/jearangoo/example1/blob/0c116d99ff2da3ee7e86c38c9b0402129b8382c8/index.js#L1-L40
