### ISSUE TITLE
Passing information into pre('save') hooks

### ISSUE THREAD

**Issue by normads** [Automattic/mongoose#7457]
This is not a bug. I'm trying to find a way to pass some information into the pre('save') hook from the context of the function that calls the save() function. Since the document object is immutable it doesn't seem possible to attach anything to the _this_ object.
One way i could think of to do this was to create an _Object_ type property in the schema and to attach information to that. But there has to be a way to do it without adding mock properties to the schema?
What am i missing here?

**Comment by mhombach** [comment]
As the docs are telling (https://mongoosejs.com/docs/api.html#document_Document-save), the `save()`-function does not take custom arguments.
I think that your use-case is not what needs to be done with a pre-save hook.
The hooks are meant "let the document manage itself" (my own interpretation), (mostly) not linked to outer circumstances.
From what you are describing, maybe a better solution would be to just create a separate function for example like `preFillDoc(myData)` which takes your data, does stuff and finally saves the document.
A "dirty" way would be to create a virtual attribute on the schema and pass data to it. But, as mentioned, that's not the best and cleanest way in my opinion, because those data are not "related" to the document but only needed by one single function.

**Comment by normads** [comment]
Yeah I understand the possibility of doing it outside the pre-save hook but the reason I'm trying to do it using the pre-save hook is to keep the rest of the code base generic. That way other people can call the save() function without having to know of the custom function that I've written. 
I can't go into too much details of the use case but i hope I'm making some sense? So if there's no clean way to do it i should probably consider creating a mock attribute or a virtual attribute like you've suggested.
Thanks :)
Would mongoose consider this as a possible feature for future releases? some context information can go a long way in writing quite useful generic decoupled hooks.

**Comment by mhombach** [comment]
Well... i now am thinking of maybe some even better way, though it's maybe not 100% the way it's supposed to be:
You can create your own functions/methods on a schema... So.... you could basically create a function on your schema called `saveWithParameters(parameters)`.
Then, from the outside, you could call this function, pass your arguments there, and from WITHIN that `saveWithParameters`-function you can call `this.save()` to save the document after you did some special things.
This way you would need to move your logic from the hook-function to the new function, but it should work the way you described needing it...
I don't know if mongoose considers this a possible feature in the future. Technically this is really not hard to do in my opinion, i think it's more that if you want to allow passing outside-data into a document-function in general :)

**Comment by mhombach** [comment]
Hmm... Maybe the best approach to do this is not to store the original-document during a whole bunch of code (maybe even passing it through functions and stuff).
Maybe the best way would be to let the document query its original db-state within the hook.
So you just do a `let originalModel = await MyModel.find(this._id);` within the hook and you will have the old/original state. One query shouldn't be a performance-problem, since you are searching by the index, which is ultra-fast.

**Comment by normads** [comment]
Even though it's one query it'll be one query _per each_  save query. Wouldn't it have a significant impact on the database loads while scaling up?
Perhaps the best way forward is to hack the `markModified` method for arrays and somehow make it include the indices of items added or removed, in the `modifiedPath`. That information should be sufficient for me to do _some_ optimizations on the hook algorithms.

**Comment by mhombach** [comment]
Hmm... ok what about this approach:
- create your Schema/Model "MySchema"
- create a virtual attribute called "_original" (or whatever)
- define a post-FIND hook
- within that post-FIND hook you simply copy `this._original = this`
- from that moment on you will keep the complete original document in that virtual attribute
- witin your pre-save hook you now can access `_original` to fully access the previous state

Tell me if this works for you :)

**Comment by normads** [comment]
Can virtuals really hold data? In my understanding a virtual is a getter/setter for manipulating existing data. Unless you can somehow store the value in a closure? I don't see an obvious way to do it though.  
We can hold the data on a mock attribute in the schema and clear it before the actual save. Which kinda takes us back to square one hehe  
Also i think `this._original = this` copies the reference. Probably better to use `.toObject()`

**Comment by mhombach** [comment]
Damn, you are right about the reference, it seems i was already sleeping when writing this.
Use `.toObject()` or do some json-parse-stringify to get the old attributes (or, if there aren't that many attributes at all, copy the attributes manually....).

About the virtual-thing: I think i had some other ORM in my mind when writing this, sorry. In Mongoose it seems you really can just set/get things but not save them like this.
But you could declare a normal attribute like `__original` and put the original data there. As Type you could use a [Mixed](https://mongoosejs.com/docs/schematypes.html#mixed).
After that, you use the pre-save hook and write a `this.__original = undefined` at the bottom of it.

I think i will open a feature-request for creating a new data-type "virtual" as for exampe the ORM "sequelize" or "TypeORM" (which both are not the best solution for MongoDB) do have.

**Comment by normads** [comment]
Yes a _virtual_ type property would be really useful! Not only to store intermediate data across the save pipeline, but also to store some static information related to the schema. eg. static permissions declarations.

**Comment by mhombach** [comment]
Ok, i created a new issue for the request. You can "follow" it for discussion or seeing how this is developing :)
https://github.com/Automattic/mongoose/issues/7465

**Comment by vkarpov15** [comment]
See #7375 . We'll add a `this.$locals` property specifically for this, but in the meantime ES6 symbols are another good alternative:

```javascript
const symbol = Symbol.for('foo');

doc[symbol] = 'bar';
doc.save(); // Will never save `symbol`
doc[symbol]; // 'bar'
```

**Comment by normads** [comment]
@vkarpov15 thanks! :)

**Comment by samikarak** [comment]
I somehow cannot retrieve the symbol property inside my pre.save hook (inside the properties of this). Is this a desired behaviour ?

**Comment by vkarpov15** [comment]
@samikarak you should be able to access the symbol property. Can you provide a script that demonstrates the issue you're having?

**Comment by samikarak** [comment]
// somewhere in my application
// creating user
const user = {foo : 'bar'};
const userSymbol = Symbol.for('user');
user[userSymbol] = true;
await UserModel.create(user);

// pre save hook in schema
UserSchema.pre('save', async function() {
  var user = this;
  const userSymbol = Symbol.for('user');
  user[userSymbol] // undefined
  user._doc[userSymbol] // undefined
});

**Comment by mhombach** [comment]
Please use the following style when post code on github :)
\`\`\`js
// your code goes here
\`\`\`
```js
// somewhere in my application
// creating user
const user = {foo : 'bar'};
const userSymbol = Symbol.for('user');
user[userSymbol] = true;
await UserModel.create(user);

// pre save hook in schema
UserSchema.pre('save', async function() {
var user = this;
const userSymbol = Symbol.for('user'); // -> I think this line overwrites the symbol again
user[userSymbol] // undefined
user._doc[userSymbol] // undefined
});
```

Can you try your code without the const-assignment of the symbol within your hook-function ?

**Comment by samikarak** [comment]
```
// pre save hook in schema
UserSchema.pre('save', async function() {
var user = this;
user[Symbol.for('user')] // undefined
user._doc[Symbol.for('user')] // undefined
});
```

seems to be the same

**Comment by samikarak** [comment]
I tried the same without asigning the userSymbol again in the hook, And I got the same result. I should also mention, that the hook is in another file ... I dont know exactly how the global symbol registry works, but maybe this could be problem.
Maybe this could be solved by using $locals, but I dont know how to use them !?

**Comment by vkarpov15** [comment]
@samikarak if it's in another file, I recommend using the $locals property: https://mongoosejs.com/docs/api/document.html#document_Document-$locals

**Comment by paullaffitte** [comment]
> I tried the same without asigning the userSymbol again in the hook, And I got the same result. I should also mention, that the hook is in another file ... I dont know exactly how the global symbol registry works, but maybe this could be problem.
> Maybe this could be solved by using $locals, but I dont know how to use them in my case !?

According to the [documentation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Symbol)

```javascript
const sym1 = Symbol("foo");
const sym2 = Symbol("foo");
sym1 === sym1; // true
sym1 === sym2; // false
```

You should create the symbol once (for instance in a constants.js file), import it and then use the same symbol everywhere you need it.

**Comment by AbdelrahmanHafez** [comment]
Perhaps a different solution would've been passing an option from save:

```js
userSchema.pre('save', function() {
  const options = this.$__.saveOptions;
  if (options.notifyOnSlack) {
    sendSlackMessage('registration', this.name);
  }
});
```

later:
```js
const user = new User({ name: 'John Doe' });
await user.save({ notifyOnSlack: true });
```

The only thing I don't like about this solution is the fact that we have to access options using `this.$__.saveOptions`, I think we should have an external method that gets saveOptions, not sure if we already do.

@normads would this have solved the issue?

**Comment by acomito** [comment]
@AbdelrahmanHafez did you ever find an alternative? Have you had issues using your solution?

**Comment by vkarpov15** [comment]
@acomito @AbdelrahmanHafez 's solution is one of our recommended approaches for passing params to pre save hooks.

Another alternative would be using `$locals` as follows. This approach works, just requires you to clean up the `notifyOnSlack` property if you don't want to reuse it.

```javascript
userSchema.pre('save', function() {
  if (this.$locals.notifyOnSlack) {
    sendSlackMessage('registration', this.name);
  }
  delete this.$locals.notifyOnSlack;
});

// Later
user.$locals.notifyOnSlack = true;
await user.save();
```
