### ISSUE TITLE
poolSize reaches the specified size , which causes application to slow down drastically

### ISSUE THREAD

**Issue by zombieleet** [Automattic/mongoose#7459]
I have 3 replica set running and I am also using the cluster module to fork 3 other processes ( the number of replica set created, does not have anything to do with the number of process forked ). In mongoose `connect` method i have the following option set

```javascript
"use strict";

const mongoose = require("mongoose");
const config   = require("../config.js");
// Set up mongoose connection

mongoose.connect( config.mongoURI, {

    useNewUrlParser: true,

    // silent deprecation warning
    useCreateIndex: true,

    // auto reconnect to db
    autoReconnect: true,

    // turn off buffering, and fail immidiately mongodb disconnects
    bufferMaxEntries: 0,
    bufferCommands: false,

    keepAlive: true, 
    keepAliveInitialDelay: 450000,

    // number of socket connection to keep open
    poolSize: 1000
}, error => {
    if (error) {
        console.log(error);
    }
});


module.exports = mongoose.connection;


```

The above code is in a file named db.js. In my server.js which starts the express application i require db.js.

Whenever i reload the webpage multiple times it get's to a point were the app slows down to load drastically ( all this started happening when i decided to use a replica set ). I connected to mongdb through mongo shell and ran db.serverStatus().connections everytime i reloaded the page the current field increases ( which is what is expected anytime a new connection is made to mongodb ), but the problem is whenever the current field reaches the specified poolSize the application takes a lot of time to load. I tried calling db.disconnect() whenever the end event is emitted on the req express object, which will disconnect from mongodb ( this worked as expected but since i am using stream changes the above solution to close opend connections will throw MongoError: Topology was destroyed. The error been throwed is not the problem, the problem is preventing the app to slow down drastically if the currently opened connection hits the specified poolSize.

I also tried setting maxIdleTimeMS in the mongodb connection string, and it is not working ( maybe mongoose does not support it )

Note: whenever i run db.currentOps() all active connections are set to false

**Comment by vkarpov15** [comment]
`poolSize: 1000` is probably too big for your use case. Having 1000 sockets open to each of 3 different servers across 4 different processes is a lot of sockets. Why is your `poolSize` so high?

**Comment by zombieleet** [comment]
I am heavily using change streams in the app. And the higher the number of collections am watching i will also need to have a high number of pool size.   
https://jira.mongodb.org/browse/DOCS-11270

**Comment by vkarpov15** [comment]
Hmm can you describe how you're using change streams? Maybe you should use a separate [connection](https://mongoosejs.com/docs/connections.html) for your change streams from the one you use to serve up your page?

**Comment by gtzinos** [comment]
Hello, how can we calculate the ideal value for the poolSize ?

**Comment by vkarpov15** [comment]
@gtzinos depends heavily on your app, specifically the number of concurrent operations you expect per connection and how long those operations take. If you have many slow concurrent operations that are backing up behind each other, there are [several ways to work around this](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs). `poolSize` is just one option, although increasing `poolSize` from 5 to 10 or even 20 is often the easiest way to patch this issue.

If you're not seeing operations queued up behind each other, no need to worry about `poolSize`.
