### ISSUE TITLE
Model automatically saves into a " (modelname)+s " collection

### ISSUE THREAD

**Issue by zipippino** [Automattic/mongoose#7460]
Hi, I'm using mongoose (last version , fresh install) for a MEAN architecture (mongo+express+angular+nodejs) and i'm approaching to save some data into my mongodb.
I have a db called "cogestione" and three collections: "ragazzi", "sedi" and "corsi".
I want to save a data of type Ragazzo in collection "ragazzi". I connect with:
`mongoose.connect("mongodb+srv://admin:************.mongodb.net/cogestione?retryWrites=true", { useNewUrlParser: true })
    .then(() => console.log("Connection to database correctly happened"))
    .catch((err) => console.log(err))`

and all goes smoothly. In another file i have the model:

`const mongoose = require("mongoose");

const postSchema = mongoose.Schema(
  {
    nome: {
			type: 'String'
		},
		cognome: {
			type: 'String'
		},
		classe: {
			type: 'String'
		},
		email: {
			type: 'String'
		}
  }
  );

module.exports = mongoose.model("ragazzo" , postSchema);
`

and i export it with the last line. Then , back in the app i send it to the db with:
`const post = new Ragazzo({
    nome: req.body.nome,
    cognome: req.body.cognome,
    classe: req.body.classe,
    email: req.body.email
  });
  console.log(post);
  post.save()
    .catch((err)=>{console.log(err)});
  res.status(201).json({message : "Post added"});` 

The problem is that it doesn't save my doc into "ragazzi" collection , but it creates a new collection called "ragazzos"... how can i tell mongoose to save it into a fixed collection?

**Comment by zipippino** [comment]
You saved my life

**Comment by mhombach** [comment]
Glad i could help :)
If there is no question left, please close this issue so others won't think it's unsolved? ;)

**Comment by zipippino** [comment]
I just wanted to try it before doing it. It works as expected. Close the issue

**Comment by zipippino** [comment]
Close #7460
