### ISSUE TITLE
[Docs] Promise or callback.

### ISSUE THREAD

**Issue by libook** [Automattic/mongoose#7461]
As I know, mongoose support 2 ways to get data:
1. Promise
2. callback

Most of the methods have an optional callback parameter. If I want to use callback, just pass my callback. If I want to use Promise, I can directly get my Promise(thenable object) from the return of these methods without passing callback.

The docs says:

> Passing a callback immediately executes the query

This is confused to others who want to learn mongoose.
I saw someone coding like this:

```javascript
let myData = await TheModel.find({
  "name": "aa"
},function(error,data){
  return data;
})
// He said that he wanted the query executing immediately.
```

Maybe to someone good at JS and Node.js, this seems like a joke; but it happened.

It would be great if there were more detail on the docs.

**Comment by mhombach** [comment]
I helped people with exactly this issue and from what i can tell, it's not a problem of understanding the doc.

I hope we can agree on:

> Passing a callback immediately executes the query

is in no way the same as

> To execute the query you MUST pass a callback

The problem i saw with users running into this is, that they don't really understand the way a Promise and a callback works in JS. ... Maybe they understand callbacks, but the Promise-way is not that easy to understand, it seems.
If they would fully understand Promises, then they would also know, that  calling `await` will return the returnvalue of the function, after it has finished executing async. The same applies for the callback.
So, if you use both ways to get the returnvalue but execute different code based on it in different locations in your code, then this get's messy and inconsistent.

Maybe linking to some good Promise-Explanation in the mongoose-docs would be helpfull, but on the other side nobody should expect a documentation to link every single word to a tutorial.

**Comment by libook** [comment]
@mhombach Thanks for your replying.

I agree that people who made that kind of mistake don't have much experience with Promise.
Well, I disagree that they should have these experience by reading manual of Promise.

The callback style is not included in the specification of Promise.
Not everything which use Promise can provide callback style usage.
It is more like a kind of flexibility designing.

In another hand; callbacks are everywhere.
A callback can be a way to get the data asynchronously.
And a callback can also be a processor just like the one in Array.prototype.map.

At last, the Query object is not a standard Promise, it is a 'thenable' object. I mean it may be harder to know that it has some functions as a 'promise'.

So I wish that the docs can point out that the existence of the two ways for getting query results.
At least like this:

> Passing a callback which you use to get the result with, or use the Query object returned.

Sorry for my 'Chinglish'.

**Comment by mhombach** [comment]
I understand your position and arguments.
But:

> Passing a callback which you use to get the result with[...]

This is the standard definition of a `callback` and should not be needed (just my personal opinion).
Also, the then-able Query-object can be executed directly to get a Promise (via `.exec()`, which is documented).

> The callback style is not included in the specification of Promise.

That is correct but since callbacks and promises are not related to each other, i don't see why this should be specifically pointed out :/

### Edit:
I just found that the description of mongoose about "queries" is mostly the exact thing we are talking about here:

> A mongoose query can be executed in one of two ways. First, if you pass in a callback function the operation will be executed immediately with the results passed to the callback.
A query also has a .then() function, and thus can be used as a promise.
(https://mongoosejs.com/docs/queries.html)

Also about the promises:

> Mongoose async operations, like .save() and queries, return thenables. This means that you can do things like MyModel.findOne({}).then() and await MyModel.findOne({}).exec() if you're using async/await.
(https://mongoosejs.com/docs/promises.html)

I didn't find your description `Passing a callback immediately executes the query` in any of those 2 sites. Can you link me to where you found it? Maybe it's an old documentation or some small documentation-part that was not updated with the other ones :)

**Comment by libook** [comment]
> Passing a callback immediately executes the query.

https://mongoosejs.com/docs/api.html#model_Model.distinct

I found that this is the only place with this description. So it may be old.

---

> The callback style is not included in the specification of Promise.

Someone who may knows about Promise, but he didn't know he didn't need to write callback while he was using await.

Because he didn't know what the 'callback' here exactly is.

Maybe it is an individual case...

I think [this](https://mongoosejs.com/docs/queries.html) may be useful if he knows that the 'callback' of Model.distinct is the 'callback' in the document of 'queries'.

**Comment by libook** [comment]
Well, the [guide of 'queries'](https://mongoosejs.com/docs/queries.html) are useful.
Thank @mhombach for your help.
I think I should close this issue if you think there is no need to change the docs.

**Comment by mhombach** [comment]
You're welcome :)
And it's always good to discuss existing documentation/structures, because otherwise new/better ideas cannot be implemented =)

**Comment by JulioJu** [comment]
Hi,

For instance, for https://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate maybe a solution could be to add 

<hr />
**Returns**
  * Query 
  * Promise if no callback
<hr /> 

Doc above It's exactly like https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findOneAndUpdate

Furthermore https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts  should be updated accordingly. 

What do you think about that?
