### ISSUE TITLE
Schema with a table of subdocument. At creation of document, undefined in table, no error raised.

### ISSUE THREAD

**Issue by Maltemo** [Automattic/mongoose#7469]
**Do you want to request a *feature* or report a *bug*?**
I think this is a bug, or I just don't understand well enough mongoose to understand the behavior.

**What is the current behavior?**

So this is an extract of my mongoose Schema :
```js
//Validating functions
const existingArray = function(tab){ return tab !== null && typeof tab == "object" && tab instanceof Array};
const existingArrayNotEmpty = function(tab){ return existingArray(tab) && tab.length > 0 };

//Creation of type that can't be casted
let StringS = mongoose.Schema.Types.String;
let NumberS = mongoose.Schema.Types.Number;
StringS.cast(false);
NumberS.cast(false);

const contactSchema = mongoose.Schema({
	name : { type : StringS, required : true },
	surname : { type : StringS, required : true },
	mail : { type : StringS, required : true },
	phone : { type : StringS, required : true }
},{strict : true});

const providerSchema = mongoose.Schema({
	name : { type : StringS, required : true },
	address : StringS,
	website : StringS,
	contacts : { type : [contactSchema], validate : existingArrayNotEmpty, required : true},
},{ strict : true, useNestedStrict: true });

var Provider = mongoose.model("Provider",providerSchema);
```

Now i'm testing the code, my aim here is to be sure that mongoose will handle all errors if I give something that doesn't match the schema that I showed previously.

So in my unit tests, I tried this : 
```js
let providerWrongType = {
	name : 1,
	address : { x : 1 },
	website : x=>{return x},
	contacts :[ undefined ]
};

Provider.create(providerWrongType,function(err,provider){
    err ? console.log(err) : console.log(provider);
});
```
Mongoose give me errors of cast for name, address, website but not for contacts.
This case appears only if I put `undefined` or `null` in the table of contacts. For every other case, I got errors when I don't respect the schema.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the code above

**What is the expected behavior?**
I expected to have an error if I didn't respect the `contactSchema` for every element in the contacts table.

**Please mention your node.js, mongoose and MongoDB version.**
mongodb : db version v3.2.21
node : v10.15.0
mongoose : mongoose@5.4.7

I hope I gave every useful information, and I'm hoping that I just missed an important line in the documentation.

Have a good day.

**Comment by mhombach** [comment]
Hmm... I could be wrong  but i think your validation is not precise enough:


```js
const existingArray = function(tab){ return tab !== null && typeof tab == "object" && tab instanceof Array};
```
- (tab is `undefined` but not `null`), so the first check is TRUE
- tab is an object , so it's TRUE too
- tab is an instance of Array, so also TRUE

```js
const existingArrayNotEmpty = function(tab){ return existingArray(tab) && tab.length > 0 };
```
- first check returns TRUE
- 2nd check also returns TRUE because the array has exactly one entry, which content is `undefined`

So... it just logically passed your validation ^^°

**Comment by Maltemo** [comment]
Thanks for your response. I don't think the problem is coming from the validate part. I know that it will pass. The problem comes from the fact that mongoose doesn't check if the elements of the table `contacts` respects the constraints of the `contactSchema` type. It does when I pass everything other than `null` or `undefined` in the table.

So I changed with `undefined` as you said, but it doesn't resolve the bug. I still got no error from mongoose.

Does the `validate` parameter where I pass `existingArrayNotEmpty` override the normal behavior of mongoose Schema ? By that, I mean does it still checks if the elements in the table are respecting the rules of the contactSchema type ?

I'll continue searching

**Comment by Maltemo** [comment]
As you asked, you can now test my problem from this repository : 
https://github.com/Maltemo/pocMongooseProblem

Installation is available in the README.md file.
Comments in the code helps to explain my  problem too.

Don't hesitate to ask more questions.

**Comment by vkarpov15** [comment]
I took a closer look at this, and it is expected behavior that Mongoose allows `null` and `undefined` in [document arrays](https://mongoosejs.com/docs/schematypes.html#arrays). In other words, Mongoose considers `[undefined]` to match the schema `[contactSchema]`. You'll get an error for arrays like `[false]`.

In general, Mongoose allows `null` and `undefined` for any property _unless_ `required` is `true`. Set `required` on the actual array elements and Mongoose will report an error for `undefined` in your array:

```javascript
  const providerSchema = mongoose.Schema({
        contacts : {
          type : [{ type: contactSchema, required: true }], // <-- Add `required` within the array
          required : true
        },
  },{ strict : true, useNestedStrict: true });
```

**Comment by Maltemo** [comment]
Thank you for your answer @vkarpov15 and your help !
Sorry that I took some of your time for this kind of misconfiguration.

Best regards.
