### ISSUE TITLE
custom error msgs for built-in validators

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#747]

**Comment by denizozger** [comment]
An example would be great..

**Comment by crispen-smith** [comment]
I've actually resorted to using a really hacky check against each of the errors in the error object and just setting a binary flag in my template for final output.  so a Big +1 from me on some examples.

**Comment by vkarpov15** [comment]
There's a [basic example in the validation docs](http://mongoosejs.com/docs/validation.html) but could be improved. Open to PR :) See #2778 to track that issue.
