### ISSUE TITLE
Having any dot / period character in the string for the key of a Map will cause a cast failed error

### ISSUE THREAD

**Issue by nbkhope** [Automattic/mongoose#7470]
### Versions

Mongoose: 5.3.12
Nodejs: v8.11.1
MongoDB: MongoDB 4.0.5 Enterprise

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When you try to create a new document with a property that is of Map type, the key of the dictionary structure cannot have a dot, otherwise it will give out an error (`Cast to Map failed for value`).

**If the current behavior is a bug, please provide the steps to reproduce.**

### 1. Define a schema:
```
const MySchema = mongoose.Schema({
  entries: {
    type: Map,
    of: String
  }
});
```

### 2. Define a model:

```
const MyModel = mongoose.model('MyModel', MySchema);
```

### 3. Try to create an entry using a key that has a dot character.

```
await MyModel.create({ entries: {
  'Hello.World': 'Will Error Out'
}});
```

Error:

```
"MyModel validation failed: entries: Cast to Map failed for value "{ 'Hello.World': 'Will Error Out' }" at path "entries""
```

**What is the expected behavior?**

Having a dot character (`.`) anywhere inside the string for the entry key should not cause an error. 

Using `'Hello World': 'Will Not Error Out'` works fine:

```
{
  _id: "5c52281b0eb5fc172321a998",
  entries: {
    Hello World: "Will Not Error Out"
  },
  __v: 0
}
```

**Comment by nbkhope** [comment]
Nevermind, I found out MongoDB has restrictions on the field name and doesn't allow a dot character.

Ref https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names
> Until support is added in the query language, the use of $ and . in field names is not recommended and is not supported by the official MongoDB drivers.

<img width="793" alt="screen shot 2019-01-30 at 5 02 29 pm" src="https://user-images.githubusercontent.com/13649002/52023152-d7825e00-24b0-11e9-8c48-2e935a8007c1.png">

**Comment by vkarpov15** [comment]
That's correct, currently the mongodb driver doesn't allow storing keys with dots. We may add this to Mongoose in the near future if mongodb doesn't add support for it soon. If you need dotted key names, you should declare a field of type `[[String]]` and store values as `[[key, value], [key, value]]`

**Comment by mapleeit** [comment]
Hi @vkarpov15. Could you give more detail or an example about how to use `[[String]]`. Thank you

**Comment by Leo7654** [comment]
@mapleeit He may mean...
```
const MySchema = mongoose.Schema({
  entries: {
    type: [[String]]
  }
});
await MyModel.create({ entries: {
  [['Hello.World', 'Will Error Out'], ['Hello.World2', 'Will Error Out2']]
}});```

**Comment by vkarpov15** [comment]
@Leo7654 that's exactly what I mean :+1: Using an array of arrays with key/value pairs similar to [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) is the way to go.

**Comment by mapleeit** [comment]
> That's correct, currently the mongodb driver doesn't allow storing keys with dots. We may add this to Mongoose in the near future if mongodb doesn't add support for it soon.

Hi, @vkarpov15. Is there any progress on this. Really look forward to this feature.

**Comment by vkarpov15** [comment]
@mapleeit not currently.

**Comment by vijaycorestack** [comment]
Any update on this
