### ISSUE TITLE
Documentation: connection events

### ISSUE THREAD

**Issue by lonix1** [Automattic/mongoose#7477]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
There is no documentation for mongoose events anywhere. There are comments [in this code](https://github.com/Automattic/mongoose/blob/master/lib/connection.js), but that isn't documentation and is liable to change.

Please list and document all the events, so they form a contract that is dependable to code against.

**Comment by vkarpov15** [comment]
Do you mean specifically connection-level events?

**Comment by lonix1** [comment]
I wasn't aware there were more events, I thought those were the only ones?

**Comment by lonix1** [comment]
@vkarpov15 Thanks for the [new docs](https://mongoosejs.com/docs/connections.html#connection-events).

I think `reconnectFailed` is missing?

**Comment by vkarpov15** [comment]
Yep you're right, will add that
