### ISSUE TITLE
Documentation of the "save" method options

### ISSUE THREAD

**Issue by kareemadel** [Automattic/mongoose#7484]
**Do you want to request a *feature* or report a *bug*?**
It's a documentation error.

**What is the current behavior?**
The save method accept the ["session" option](https://github.com/Automattic/mongoose/blob/master/lib/model.js#L236) but this is not specified in the [API documentation](https://mongoosejs.com/docs/api.html#model_Model-save). So I am not sure if it's okay to use it or it's unspecified behavior and may not be supported in later versions.

**Comment by vkarpov15** [comment]
It is safe to use, we just missed adding it to the docs. Thanks for reporting this issue.
