### ISSUE TITLE
TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by APixelVisuals** [Automattic/mongoose#7490]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
I get the following error:
```
TypeError: CreateListFromArrayLike called on non-object
    at Collection.deprecated [as find] (/root/Geola/node_modules/mongodb/lib/utils.js:681:15)
    at NativeCollection.(anonymous function) [as find] (/root/Geola/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:146:28)
    at NodeCollection.find (/root/Geola/node_modules/mquery/lib/collection/node.js:26:19)
    at model.Query.<anonymous> (/root/Geola/node_modules/mongoose/lib/query.js:1808:20)
    at model.Query._wrappedThunk [as _find] (/root/Geola/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at process.nextTick (/root/Geola/node_modules/kareem/index.js:369:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Call `Model.find()` with anything in the `options` parameter (3rd param). For example:

This will cause the error: `Model.find({}, null, { limit: 5 })`
This won't: `Model.find({}, null, {})`
This won't either: `Model.find({})`

This is true for pretty much any schema, but here's the one I tested with:
```js
{
    _id: {
        server: String,
        user: String
    },
    bot: {
        type: Boolean,
        required: true
    },
    xp: {
        xp: {
            type: Number,
            default: 0
        },
        totalXP: {
            type: Number,
            default: 0
        },
        level: {
            type: Number,
            default: 0
        },
        cooldown: {
            type: Number,
            default: 0
        }
    },
    currency: {
        type: Number,
        default: 0
    }
}
```

**What is the expected behavior?**
The query should return a result

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS: 9.0.0
Mongoose: 5.4.10
MongoDB: 4.0.6

Note: This started happening when I upgraded from MongoDB 3.2.x to 4.0.6

Edit: The problem persists even if I use the query builder.

Edit 2: This problem is only happening on my Ubuntu 16.04 VPS, it works fine from my Windows 10 machine using a remote connection. To clarify, I'm talking about the app being on different platforms, MongoDB is on the VPS in both cases.

**Comment by abullard** [comment]
I'm experiencing this issue as well. Error output is basically identical. 

However, I'm seeing it with the `projection` parameter.
This is currently producing the error: 
```
Model.find({}, { name: 1, age: 1, _id: 0 }).sort({ age:1 })
```

**Please mention your node.js, mongoose and MongoDB version.**
Node.JS: 8.1.0
Mongoose: 5.4.2
MongoDB: 3.1.10

Note: No packages were upgraded when this error started populating.

**Comment by APixelVisuals** [comment]
Fixed the issue by reinstalling Node.JS and MongoDB (as well as all my NPM packages).

**Comment by APixelVisuals** [comment]
Update: It now produces the same error... Just took it a while to start again

**Comment by APixelVisuals** [comment]
Since this was labeled to be needing a repro script, here it is:

```
let data = await models.members.find(
        {
            "_id.server": "1234567890123456789",
            bot: false,
            "xp.totalXP": { $gt: 0 }
        },
        "xp currency",
        {
            sort: { "xp.totalXP": -1 },
            limit: 5
        }
    );
```

Note: This code uses the Schema provided in the original post

**Comment by APixelVisuals** [comment]
@vkarpov15, since you labeled this to be needing a repro script, here it is:

```
let data = await models.members.find(
        {
            "_id.server": "1234567890123456789",
            bot: false,
            "xp.totalXP": { $gt: 0 }
        },
        "xp currency",
        {
            sort: { "xp.totalXP": -1 },
            limit: 5
        }
    );
```

Note: This code uses the Schema provided in the original post

**Comment by APixelVisuals** [comment]
Is the script above acceptable?

**Comment by vkarpov15** [comment]
@APixelVisuals  not quite, it needs to be a standalone script or GitHub repo that we can run in node.js, not an isolated code sample. For example, you don't show your schema, how you're connecting to mongodb, or how you're importing mongoose.

If you have time to do this, that would be very helpful. Otherwise, we'll get to it within the next couple weeks.

**Comment by APixelVisuals** [comment]
@vkarpov15 My project is open source, it has a lot of other code in it obviously, but it might help. Link to the repo is https://github.com/APixelVisuals/geola/

Connection is at `main.js`
Schema at `modules/misc/getModels/members.js`
Query being run at `modules/globalLeaderboard.js`

**Comment by vkarpov15** [comment]
@APixelVisuals do you have any tests for this issue?

**Comment by APixelVisuals** [comment]
@vkarpov15 What do you mean? The query being run is above in these comments.

**Comment by vkarpov15** [comment]
@APixelVisuals the below script works without any errors for me on Node 9.0.0 and Mongoose 5.4.10. Please modify the below script to repro your issue

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7490`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', new Schema({
    _id: {
        server: String,
        user: String
    },
    bot: {
        type: Boolean,
        required: true
    },
    xp: {
        xp: {
            type: Number,
            default: 0
        },
        totalXP: {
            type: Number,
            default: 0
        },
        level: {
            type: Number,
            default: 0
        },
        cooldown: {
            type: Number,
            default: 0
        }
    },
    currency: {
        type: Number,
        default: 0
    }
  }));

  let bot = true;
  let type = 'xp';
  let place = 5;
  await Model.find({
            bot,
            [type === "xp" ? "xp.totalXP" : "cubits"]: { $gt: 0 }
        },
        "xp cubits",
        {
            sort: type === "xp" ? { "xp.totalXP": -1 } : { cubits: -1 },
            limit: 5,
            skip: place
        });
}
```
