### ISSUE TITLE
feature request: nested schemas - fully declarative pojo schema definitions

### ISSUE THREAD

**Issue by captaincaius** [Automattic/mongoose#7494]
**Do you want to request a *feature* or report a *bug*?**

*feature*

This is very related to #7181 but after starting to write there I decided it's probably off-topic.

TL;DR: 
- hail mary request: nested objects in schema configuration objects make child schemas by default - just like arrays already do.
- next best thing request: an boolean OPTION to do it without needing to use { type: new Schema(...) }

**What is the current behavior?**

- If you want validation on multiple levels (and don't want Mixed), you need a child schema.
- When a schema configuration has an array, a child schema is created automatically, and a simple pojo can fully describe your schema (including subschemas) \o/.

But when it's not an array, it's impossible to do so without:

child: { type: new Schema({...}) }

That means there are certain schemas that can't be fully described with passing a single configuration pojo to Schema() (namely when you need single subdocuments).

"What's the big deal?  Just wrap the child in 'new Schema()' and move on", you say?

I share my schema definitions between /packages/client and /packages/server, and I currently can't have just a simple pojo in /packages/shared.

Instead of this:

``` javascript
export const schema = {
  sub: {
    type: {
      from: Number,
      to: Number
    },
    validate: ...
  }
}

```

I have to turn it into a factory of sorts so I can use the right "mongoose" - something like this:

``` javascript
export const schemaFactory = (mongoose) => ({
  sub: {
    type: new mongoose.Schema({
      from: Number,
      to: Number
    }),
    validate: ...
  }
});

```

**What is the expected behavior?**

Making the two equivalent would be great, but I don't think everyone would want it.  So if instead, we can have a subSchema: true option or something like that it would be awesome possum.

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by vkarpov15** [comment]
I like this idea, it's related to #7408. Will look into the option approach for 5.5, making this change in a minor release is probably a bit too heavy
