### ISSUE TITLE
slice after populate doesnt work

### ISSUE THREAD

**Issue by waynemichaels** [Automattic/mongoose#7495]
Item.Product.find({ _id: item_id })
              .populate({
                path: "reviews"
              })
              .slice("reviews", [start - 1, limit])
              .exec((err, response) => {
                res.send(response);
              });

 The query above returns an empty reviews array. 

{
db version v4.0.4
git version: f288a3bdf201007f3693c58e140056adf8b04839
allocator: tcmalloc
modules: none
build environment:
    distmod: 2008plus-ssl
    distarch: x86_64
    target_arch: x86_64
}

**Comment by waynemichaels** [comment]
Item.Product.find({ _id: item_id })
              .populate({
                path: "reviews"
              })
              .slice("reviews", [start - 1, limit])
              .exec((err, response) => {
                res.send(response);
              });

**Comment by vkarpov15** [comment]
What do your schemas look like?
