### ISSUE TITLE
Using Mongoose `pre` hook to get document before findOneAndUpdate()

### ISSUE THREAD

**Issue by darrenbrett** [Automattic/mongoose#7497]
I am running "mongoose": "5.4.9".

I am trying to use Mongoose `pre` and `post` hooks in my MongoDB backend in order to compare the document in its pre and post-saved states, in order to trigger some other events depending on what's changed. So far however I'm having trouble getting the document via the Mongoose `pre` hook. 

According to the docs "pre hooks work for both doc.save() and doc.update(). In both cases this refers to the document itself... ". So I here's what I tried. First in my model/schema I have the following code:

    let Schema = mongoose
      .Schema(CustomerSchema, {
        timestamps: true
      })
      .pre("findOneAndUpdate", function(next) {
        trigger.preSave(next);
      })
      // other hooks
    }

... And then in my triggers file I have the following code:

    exports.preSave = function(next) {
      console.log("this: ", this);
      }
    };

But this is what logs to the console:

> this:  { preSave: [Function], postSave: [AsyncFunction] }

So clearly this didn't work. This didn't log out the document as I was hoping for. Why is `this` not the document itself here, as the docs themselves appear to indicate? And is there a way I can get a hold of the document with a `pre` hook?

**Comment by vkarpov15** [comment]
Read up on query middleware vs document middleware: https://mongoosejs.com/docs/middleware.html#types-of-middleware
