### ISSUE TITLE
[NoSuchTransaction] Model.create throws error with session sometimes, while Model.insertMany doesnt?

### ISSUE THREAD

**Issue by DakshMiglani** [Automattic/mongoose#7502]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behavior?**

Code:

    let session = await Mongoose.startSession();
    session.startTransaction();
    const docs = await Model.create(array, { session });

Result:
error label: TransientTransactionError
codeName: NoSuchTransaction
errmsg: Given transaction number 1 does not match any in-progress transactions.

**What is the expected behavior?**

It shouldn't throw that error.

When I do this with insertMany, it works.

**Please mention your node.js, mongoose and MongoDB version.**

mongoose: ^5.3.0
node: v10.8.0

**Comment by vkarpov15** [comment]
What does `array` look like? Does this `create()` without the session arg?

Also, just to confirm, `array` is an array, not an object?

**Comment by DakshMiglani** [comment]
Array looks like: [{ field1: 'value1' }, { field1: 'value2' }]

and yes it works without session.

**Comment by vkarpov15** [comment]
What does "keep trying" mean, can you clarify with some code samples?

**Comment by DakshMiglani** [comment]
So basically, I've a rest api which executes the code i mentioned in the original comment. If I keep sending a request, it was throwing the session error 3 out of 4 times until I switched to insertMany, which never did that.

**Comment by vkarpov15** [comment]
This looks related to [this MongoDB server issue](https://jira.mongodb.org/browse/SERVER-36428). This is because `create()` runs 2 inserts in parallel, and this may cause write conflicts in the MongoDB server. Since this is a TransientTransactionError, you should [retry it](https://docs.mongodb.com/manual/core/transactions/#retry-transaction). For example:

```javascript
  app.get('*', async function(req, res) {
    let session;
    try {
      session = await mongoose.startSession();
      for (let i = 0; i < 5; ++i) {
        try {
          session.startTransaction();
          await Model.create([{ name: 'foo' }, { name: 'bar' }], { session });
          await session.commitTransaction();
        } catch (err) {
          await session.abortTransaction();
          if (err.errorLabels != null && err.errorLabels.includes('TransientTransactionError') && i < 5) {
            console.log('Retry...');
            await new Promise(resolve => setTimeout(resolve, 100));
            continue;
          }
          throw err;
        }
      }
      res.json({ ok: 1 });
      console.log('ok');
    } catch (error) {
      console.log(error);
      res.status(500).send(error.message);
    }
  });
```

**Comment by vkarpov15** [comment]
Here's the full script I used to debug this, for posterity:

```javascript
const assert = require('assert');
const express = require('express');
const mongoose = require('mongoose');
const superagent = require('superagent');

mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7502`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', new Schema({ name: String }));
  const app = express();

  await Model.createCollection();
  await new Promise(resolve => setTimeout(resolve, 1000));

    app.get('*', async function(req, res) {
    let session;
    try {
      session = await mongoose.startSession();
      for (let i = 0; i < 5; ++i) {
        try {
          session.startTransaction();
          await Model.create([{ name: 'foo' }, { name: 'bar' }], { session });
          await session.commitTransaction();
        } catch (err) {
          await session.abortTransaction();
          if (err.errorLabels != null && err.errorLabels.includes('TransientTransactionError') && i < 5) {
            console.log('Retry...');
            await new Promise(resolve => setTimeout(resolve, 100));
            continue;
          }
          throw err;
        }
      }
      res.json({ ok: 1 });
      console.log('ok');
    } catch (error) {
      console.log(error);
      res.status(500).send(error.message);
    }
  });

  app.listen(3000);

  const promises = [];
  for (let i = 0; i < 4; ++i) {
    promises.push(superagent.get('http://localhost:3000').catch(() => {}));
  }
  await Promise.all(promises);
  console.log('Done');

  await mongoose.connection.dropDatabase();
}
```

**Comment by felipe-augusto** [comment]
@vkarpov15 Having the same problem here running `Model.findOneAndUpdate` in parallel. My code is similar to your previous, the only difference is that for some reason, after the first `WriteConflict` error I got stuck in a loop with `NoSuchTransaction` error, so I  had to do this:

```js
// using a snippet of your code as an example
if (err.errorLabels != null && err.errorLabels.includes('TransientTransactionError') && i < 5) {
  
  // transaction vanished for some reason, so we will restart it for the next attempt
  if(err.codeName == 'NoSuchTransaction') {
    await session.abortTransaction()
    await session.startTransaction()
  }

  console.log('Retry...');
  await new Promise(resolve => setTimeout(resolve, 100));
  continue;
}
```

Do you have any ideais why the transaction is aborting by itself?

**Comment by chidiwilliams** [comment]
Hey @felipe-augusto, I've been having this same issue as well. I submitted an issue with MongoDB a while ago but it hasn't been resolved yet (I also did one here yesterday https://github.com/Automattic/mongoose/issues/7571).

I've knocked the problem into two tests here: https://github.com/chidiwilliams/mongodb-transactions-test.

The first test starts 10 transactions with an interval of 500ms, while the second one uses an interval of 100ms.
```js
  const user = await User.create({});

  async function txnFunc(session) {
    // const op = await conn.db.db.executeDbAdminCommand({ currentOp: 1 });
    // fs.appendFileSync('logs/500.log', `${JSON.stringify({ timestamp: new Date(), op })}\n`);
    await User.findByIdAndUpdate(user._id, { $inc: { count: 1 } }, { session, new: true });
  }

  await Promise.all(
    [...new Array(10)].map((x, i) => asyncTimeout(async () => {
      const session = await conn.db.startSession({ readPreference: { mode: 'primary' } });
      await session.startTransaction({
        readConcern: { level: 'snapshot' },
        writeConcern: { w: 'majority' },
      });

      await runTransactionWithRetry(txnFunc, session);
      await commitWithRetry(session);
    }, i * 500)), // interval is 100ms for second test
  );

  const dbUser = await User.findById(user._id);
  expect(dbUser).toHaveProperty('_id');
  expect(dbUser).toHaveProperty('count', 10);
  done();
```

Test 1 passes but test 2 retries indefinitely till the tests timeout.

**Comment by DakshMiglani** [comment]
@felipe-augusto does it work with `Model.update(query, update, { session: sess })`?

**Comment by felipe-augusto** [comment]
@DakshMiglani No, it does not. If there are two concurrent operations, it fails.

**Comment by felipe-augusto** [comment]
@chidiwilliams I made a fork of your code and kind of "fixed it", but I think this is only a temporary solution. The problem actually is that when you decrease the timeout, you force two operations to occur at the same time (i.e: concurrence). But in my computer, the tests completed normally, I think it's because I have an SSD and operations are faster then a normal HD.

So, I removed the timeout to force all operations to be triggered at the same time. Can you please check the code at my fork and see if it's working?

Here's the PR: chidiwilliams/mongodb-transactions-test/pull/1

**Comment by chidiwilliams** [comment]
@felipe-augusto I ran the tests with this https://github.com/Automattic/mongoose/issues/7502#issuecomment-468000075 change and it works well. The transactions retry and eventually complete. It's quite strange that this works. Is this a safe solution also? Is this a MongoDB/Mongoose issue?

**Comment by felipe-augusto** [comment]
@chidiwilliams After digging this up a little bit, I came across this thread on [MongoDB issues](https://jira.mongodb.org/browse/SERVER-36428?focusedCommentId=2136170&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2136170), that sort of explains their logic. You can read it for a more in depth explanation. 

The **bottom line** is that you can call this a MongoDB "issue", but they decided it to be this way.

@atcabral explains in this thread that:
"The MongoDB team has spent a lot of time minimizing write conflict by having transactions act off of the most current snapshot available. **For sustained contentious documents, the clients must be prepared to retry in the case of write conflicts.**

**We are currently working on drivers helpers that just have you pass in a transaction callback and will auto-retry.** I'd love to get your early feedback. Can I email you to set something up? "

This [video](https://www.youtube.com/watch?v=3x_Pf9rQGCo&feature=youtu.be&t=723) also explain WriteConflicts and this image extracted from it is illuminating, because explains why `WriteConflict` evolves to `NoSuchTransaction`:

![image](https://user-images.githubusercontent.com/9551950/53968915-a52ed680-40d6-11e9-933b-310f97ac914c.png)

**Comment by vkarpov15** [comment]
@felipe-augusto I'd love to take a look at the retry helpers you mentioned if they're open source.

**Comment by felipe-augusto** [comment]
@vkarpov15 Sure, I'll make you a gist as soon as possible.

**Comment by albertyou2** [comment]
THE SAME PROBLEM HERE,this is my code :

const Tool = require('../../libs/tool');
// 每节课上课前，把这节课应道学生写入课程表
module.exports = app => {
  return {
    schedule: {
      cron: '*/40 * * * * *',
      type: 'worker'
    },


    async task(ctx) {
      console.log('/************saveForUnSignInedTeas schedule :: start *********/');
      let locked = undefined;
      const service = ctx.service;
      const session = await app.mongoose.startSession({
        readPreference: { mode: 'primary' },
      });

      try {

        // locked
        let _lockKey = `saveForUnSignInedTeas_schedule `;
        let lockRes = await service.distrubuteLock.lock(_lockKey);
        if (!lockRes) {
          ctx.app.logger.error(`saveForUnSignInedTeas  :: 上次任务未完成 或 锁未释放`)
          return;
        }
        locked = _lockKey;

        // 启动 事务
        await session.startTransaction({
           readConcern: { level: 'snapshot' },
           writeConcern: { w: 'majority' },
        });

        // 找出已经结束10分钟以上的课程，冗余5分钟
        let before = Date.now() - 10 * 60 *1000;
        let before_before = Date.now() - 40 * 60 *1000;// 结束时间小于20分钟的课程

        const courses = await app.model.CourseSchema.find({
          $and :[ // 找出 1分钟内上课，且 应到学生不存在的课程
            {endTime: {$gte: new Date(before_before)}},
            {endTime: {$lte: new Date(before)}},
            {isCreateUnsignInedTea: false},
          ],
        });
        //console.log('tea end courses    :::    ' +  JSON.stringify(courses));
        if (courses.length === 0) {
          return;
        }

        for (let i = 0; i < courses.length; i++) {
          let needSignTeaIds = courses[i].teachers.map(e => (e._id)); //需要签到的老师
          // 已经签到的记录
          let signRecordOrigin = await app.model.TeacherSignIn.find({course : courses[i]._id,teacher:{$in:needSignTeaIds}}).sort({created:-1});
          //console.log('needSignTeaIds    ::::::::::::::::::::::::::: ' + JSON.stringify(needSignTeaIds));

          //console.log('signRecordOrigin    ::::::::::::::::::::::::::: ' + JSON.stringify(signRecordOrigin));

          let needCreateSignTeas = []; // 需要创建未签到的老师
          
          for (let n in needSignTeaIds){
            let isSigned = false;
            for (let s in signRecordOrigin){
              if (String(signRecordOrigin[s].teacher) === String(needSignTeaIds[n])) {
                isSigned =true;
              }
            }
            //console.log('n    ::::::::::::::::::::::::::: ' + needSignTeaIds[n]);
            if (!isSigned) {
              let courseNum = await service.courseSchema.getCourseNum( courses[i].class, courses[i].term, courses[i]._id);
              let school    =  await app.model.School.findOne({_id:  courses[i].school}).select('name');
              let classRoom =  await app.model.ClassRoom.findOne({_id:  courses[i].classRoom}).select('name');
              let classInfo =  await app.model.Class.findOne({_id:  courses[i].class}).select('courseFee');
              let tea = await app.model.RoleMap.findOne({_id:needSignTeaIds[n]}).select('phone');
              let signInTime= Date.parse( courses[i].endTime) + 10*60*1000;
              let item = {
                teacher   : app.mongoose.Types.ObjectId(needSignTeaIds[n]),
                courseFee : classInfo .courseFee,
                course:   app.mongoose.Types.ObjectId(courses[i]._id),
                stuNum: -1,
                addr: "未签到，无签到地址",
                schoolAddr: school.addr || '',
                classRoomName: classRoom.name || '',
                term:   app.mongoose.Types.ObjectId(courses[i].term),
                class:   app.mongoose.Types.ObjectId(courses[i].class),
                courseNum,
                type:"unSignIn",
                school:   app.mongoose.Types.ObjectId(courses[i].school),
                longitude: -1.0 ,
                latitude:  -1.0,
                phone: tea.phone,
                created : new Date(signInTime),
                updated : new Date(signInTime),
              };
              needCreateSignTeas.push(item);
            }
          }

          if (needCreateSignTeas.length > 0) { //
            console.log('updated !!! ::::::::: ') 
            await app.model.TeacherSignIn.create(needCreateSignTeas , {session} );
            await app.model.CourseSchema.updateOne(
              {_id:courses[i]._id},
              {isCreateUnsignInedTea:true},
              {session},
            );
          }
        }
        await session.commitTransaction(); // 提交事务

      } catch(err) {
        await session.abortTransaction(); // 回滚
        console.log(`\x1B[41;37m ERROR: schedule, saveForUnSignInedTeas.js \x1B[0m ${err}`);
        return {code:500, msg:'server error', result: false};
      }finally{
        await session.endSession(); // 结束
        if (locked) {
          await service.distrubuteLock.unlock(locked);
          locked = undefined;
        }
        console.log('/************saveForUnSignInedTeas  :: end *********/');
      }
    }
  }
}
