### ISSUE TITLE
find consider order of object keys

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#7503]
I have the following User model with nested document structure like this:
```jsx
const UserSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      trim: true,
      index: true,
    },
    taxID: {
      taxID: {
        type: String,
        index: true,
      },
      type: {
        type: String,
        uppercase: true,
      },
    },
})

const UserModel = mongoose.model('User', Schema);
```

When doing a find on them using an object, it returns different results for different orders of keys of the search object
```jsx
const taxID = { taxID: '1234', type: 'ok' };
const taxID2 = { type: 'ok', taxID: '1234' };
const users = await UserModel.find({ taxID});
const users2 = await UserModel.find({ taxID: taxID2 });
```

is this the expect behaviour? how can I make the key ordering not matter?

**Comment by vkarpov15** [comment]
This is expected behavior enforced by the mongodb server. If you're querying for an object, mongodb looks for objects that are exactly equal, including types and key order. To make key order not matter, do `{ 'taxID.type': 'ok', 'taxID.taxID': '1234' }` .
