### ISSUE TITLE
[Doc] MongooseError should become simply Error

### ISSUE THREAD

**Issue by JulioJu** [Automattic/mongoose#7509]
Hi !

Actually, https://mongoosejs.com/docs/api.html#Error reference « MongooseError », but there isn't object MongooseError available in the public API, the object Alvailable in public API is Error (see [./lib/index.js](https://github.com/Automattic/mongoose/blob/7e39b9990e643c5b178d6c176e4c6a95babfbcec/lib/index.js#L944)) .

Therefore in the doc, maybe we must rename all MongooseError to Error. Probably, it could be done thanks a hook in https://github.com/Automattic/mongoose/blob/master/docs/source/api.js ? (not investigated more). 

Furthermore, Error are not referenced in the left navigation pane. Maybe it should be added ? 

Same observation for `MongooseArray`. 

What do you think about that?

**Comment by vkarpov15** [comment]
Not a bad idea. We try to not clutter the left panel with too much info, but we can add mongoose errors to the API docs

**Comment by JulioJu** [comment]
Ok so cool ! Yes, as `Error` is often used ! The interest of a Validation tool is the Errors sent ;-).
