### ISSUE TITLE
Update method in documentation doesn't fire setters

### ISSUE THREAD

**Issue by ghost** [Automattic/mongoose#751]
From the documentation:

```
  Model.update(conditions, update, options, callback);
```

doesn't seem to fire any setters.  The only way I could get the setters to work on updates was the build a query and do something like this:

```
  documents.forEach (doc) ->
        # merge this document with update data
        extend(doc, update_data)
        doc.save()
```

If this is expected behavior, it should be explained in the docs.

**Comment by unutoiul** [comment]
Hi,

Is setters working with update or findOneAndUpdate?

Thanks,
Lucas

**Comment by cavitkeskin** [comment]
Is there any way to work setter with findByIdAndUpdate

**Comment by vkarpov15** [comment]
Not currently.
