### ISSUE TITLE
Mongoose virtual with multiple foreignFields

### ISSUE THREAD

**Issue by VassilisPallas** [Automattic/mongoose#7517]
I have a Schema named Events which has a key creator which is a reference to the creator and a key musicians which is an array with the musicians.

A Musician can create Events or/and participate as a musician. I want to create a virtual property named **events** to the musician model which will contain all the events that the musician has created and the events that participate.

I tried this:

```
MusicianSchema.virtual('events', {
    ref: 'Events',
    localField: '_id',
    foreignField: ['creator, musicians'],
    justOne: false,
});
```
but this returns an empty array. Is there any way to make it work, or mongoose doesn't have this feature?

I also asked in [stackoverflow](https://stackoverflow.com/q/54640195/3763848), but I didn't get any response.

My node version is 9.11.1 and the mongoose version is 5.3.5.

**Comment by vkarpov15** [comment]
@VassilisPallas we don't currently support populating on multiple foreign fields. Please track #6608 for updates on this issue.

As a workaround, you'll need 2 separate virtuals:

```javascript
MusicianSchema.virtual('createdEvents', {
    ref: 'Events',
    localField: '_id',
    foreignField: 'creator',
    justOne: false,
});

MusicianSchema.virtual('attendingEvents', {
    ref: 'Events',
    localField: '_id',
    foreignField: 'musicians',
    justOne: false,
});
```

**Comment by EmmanuelAmet** [comment]
I was facing similar situation during the development and what I did was to replicate the same code twice as @vkarpov15 started as a work around and it works perfectly. 


​MusicianSchema​.​virtual​(​'createdEvents'​,​ ​{​
    ​ref​: ​'Events'​,​
    ​localField​: ​'_id'​,​
    ​foreignField​: ​'creator'​,​
    ​justOne​: ​false​,​
​}​)​;​


​MusicianSchema​.​virtual​(​'musicianEvents'​,​ ​{​
    ​ref​: ​'Events'​,​
    ​localField​: ​'_id'​,​
    ​foreignField​: ​'musician​,​
    ​justOne​: ​false​,​
​}​)​;​
