### ISSUE TITLE
Mongoose Website Documentation

### ISSUE THREAD

**Issue by danielturus** [Automattic/mongoose#7519]
Hello!

### Intro
I want to thank you for this wonderful piece of software.
I opened this issue because I find https://mongoosejs.com/docs/ website difficult to work with.

### Why?
Because it's based on one page, and that's not great for SEO.

### Example:
I need the documentation for Model.findOneAndUpdate(). I search on Google for this term, Google is unable to send me to the exact place. This happens all the time. 

### Fix:
This affects me and a few hundred thousand of users. Could you please re-build the website in a user friendly way? The best example is https://vuejs.org

Thank you!

**Comment by vkarpov15** [comment]
Do you mean specifically the [API docs](https://mongoosejs.com/docs/api.html)?

You can also use the search feature on the left panel, which looks within individual pages:

<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.useloom.com/embed/bdc3b80f83484a1388da5dc1915c16fb" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

**Comment by danielturus** [comment]
Yes, indeed. Have not noticed that search box :) 
Also Lodash.com have the same structure. You have to do a few more steps on the sites with this structure because Google is not able to send you to the right spot ( ex: `https://mongoosejs.com/docs/api.html#mongoose_Mongoose-Aggregate` ) - google don't send you to the above URL, but to the `https://mongoosejs.com/docs/api.html`

Keeping in mind that your site have more than 900k visits per month, and each user will have to do at least 2 steps (let's say 1.5 seconds in average) compared to ideal SEO version of the site, you would save a ton of developers time.

Don't get me wrong, I really appreciate this wonderful module and also the work you put in, but I think it can be done an improvement to the site. I also believe designers / developers will be pleased to help and build the site (for free)

Thank you!

**Comment by vkarpov15** [comment]
Yeah you make a good point about SEO improvements. The API docs could use some work there.

In the meantime, you can use our search box to work around this limitation
