### ISSUE TITLE
Error creating index: user is not allowed to do action [createIndex]

### ISSUE THREAD

**Issue by clarkbrent** [Automattic/mongoose#7522]
Let us know if this is still an issue for you @kimmanwky, closing this for now.

_Originally posted by @lineus in https://github.com/Automattic/mongoose/issues/6976#issuecomment-426476126_

I'm having the same exact issue as @kimmanwky was in their original issue.

Error: `Error creating index: user is not allowed to do action [createIndex] on [mongodb.system.indexes]`

Atlas MongoDB: 4.0.6
mongoose: 5.4.11
Node: 10.15.1

Model: ` email: { type: String, unique: true }`

Passing the following Mongoose options:
```
options: {
      useCreateIndex: true,
      useNewUrlParser: true
}
```

I get the error whether I include `retryWrites=true` or not in the connection string URI. User has readWrite to the database.

**Comment by clarkbrent** [comment]
Problem seems to be unrelated to Mongoose after making a few tests. Closing this.

**Comment by SabrinaDanielle** [comment]
@clarkbrent  how did you resolve this?

**Comment by vkarpov15** [comment]
@SabrinaDanielle please open up a separate issue and follow the issue template.
