### ISSUE TITLE
_id field bug introduced with v5.4.11

### ISSUE THREAD

**Issue by hanMarr** [Automattic/mongoose#7524]
On Friday, Feb 8th, we started experiencing a failure on our integration tests (that spin up a in memory version of mongodb, inserts docs, and runs tests). There were a series of failures but it started with this one:

*The _id field cannot be changed from {_id: ObjectId('5c648eb8ec93cd5888f9c9de')} to {_id: \"5c648eb8ec93cd5888f9c9de\"}.*

This error happened when we were trying to write to mongo with the ".replaceOne()" method.

After testing out many versions of mongodb and mongodb-memory-server, we finally nailed down the issue to the mongoose library. We were using *mongoose 5.4.12.*

To reproduce: 
use mongodb v 3.1.13 and mongodb-memory-server v3.1.1 and *mongoose v5.4.11* (this is the version where the problem started but it was carried through to 5.4.12). node v10.6.0

The solution to our issue was to revert back to mongoose 5.4.10 (using the same mongodb libraries as above) still using the same version of the other libraries listed above.

**Comment by rvillane** [comment]
we are experiencing a very similar issue, like if a recent change on Mongoose is messing up with the type of "_id" on existing documents.  Seems that is trying to cast from ObjectId to String.  As you pointed out 5.4.11 is the version where this behavior was introduced.  

Any ideas ?

**Comment by ahce** [comment]
@vkarpov15 Please check this.

The bug is introduced in this [commit](https://github.com/Automattic/mongoose/commit/1b1acd5e3d9c78a67ce0bd65f5af5ac7c814f2be)

exampleBreak is broken because _id false from otherProps causes the _id deletion of the schema. It only happens when otherProps is used as an object.
```
const mongoose = require('mongoose');

const otherProps = require('./otherProps');

/* otherProps
  {
    _id: false, // this breaks to exampleBreak
    prop1: { type: String },
    prop2: { type: String },
    prop3: { type: String }
  }
*/

const exampleWorks = new mongoose.Schema(
  {
    name: {
      type: String
    },
    data: [
      otherProps
    ]
  },
  {
    timestamps: true
  }
);

const exampleBreak = new mongoose.Schema(
  {
    name: {
      type: String
    },
    data: otherProps
  },
  {
    timestamps: true
  }
);

mongoose.model('exampleWorks', exampleWorks);
mongoose.model('exampleBreak', exampleBreak);
```

**Comment by cosminn777** [comment]
We also moved back to mongoose 5.4.10 (some find queries were not working after the update).
Mongodb 4.0.6

**Comment by vkarpov15** [comment]
@ahce we fixed this in master, but your schema doesn't do what you expect it'll do. Your schema:

```javascript
const otherProps = {
  _id: false,
  prop: { type: String }
};

const exampleBreak = new mongoose.Schema(
  {
    name: {
      type: String
    },
    data: otherProps
  },
  {
    timestamps: true
  }
);
```

Does **not** remove a `nested._id` path. It instead **creates** a `data._id` path with [arbitrary type](https://mongoosejs.com/docs/schematypes.html#mixed). That `data._id` path would not be there if you didn't put `_id: false`. Please just remove that `_id: false` from your schema.
