### ISSUE TITLE
Compound Unique Index Key does not work

### ISSUE THREAD

**Issue by nicewaytodoit** [Automattic/mongoose#7529]
This is a bug:

If I try to create a simple schema:
```
cons mySch = new Schema(
  {
    author: String,
    date: String,
    text: String,
,  
  { 
    _id: true,
    timestamps: true,
  }
);
```
and create index as compound key
```
mySch.index({ author: 1, date: 1 }, { unique: true });
```

If I try to create records as:
```
author: 'Foo',
date: '2011-11-11'
```
first record creation will succeed, then inserting different author but same date
```
author: 'Foo1',
date: '2011-11-11' //equal dates
```
-- will also succeed, but if I try 
```
author: 'Foo1', // same name
date: '2011-11-12' // but different date
```
This record will fail despite combination author+date does not exist.

node: v10.15.0
npm: v6.4.1
mongoose: v5.4.9

**Comment by vkarpov15** [comment]
The below script runs without issue for me, please modify the below script to repro your issue:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7529`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const mySchema = new Schema(
  {
    author: String,
    date: String,
    text: String,
  },
  {
    _id: true,
    timestamps: true,
  }
  );

  mySchema.index({ author: 1, date: 1 }, { unique: true });

  const MyModel = mongoose.model('Test', mySchema);

  await MyModel.init();

  await MyModel.create({ author: 'Foo', date: '2011-11-11' });
  await MyModel.create({ author: 'Foo1', date: '2011-11-11' });
  await MyModel.create({ author: 'Foo1', date: '2011-11-12' });
}
```

**Comment by dewwwald** [comment]
I want to reopen this issue as I am also encountering the same problem. 

version - ^5.4.0

I have 3 fields as part of the index. Could it be related to the fact that there was pre-existing data in the database?

**Comment by dewwwald** [comment]
I pasted this test into my project and added all my decorations to the code you provided and it works as expected. I am perplexed. I can't for the life of me figure out exactly where this is happening. Could it be that the index does not build?

**Comment by dewwwald** [comment]
Differences I can find in the config of the schema:
- The index fields in my schema have a ref
- The index fields in my schema are required
- The index fields in my schema are all typed as Schema.Types.ObjectId
- I see there is a superfluous schema.set('timestamps', true); and { timestamp: true } on my schema
- Your schema defines _id: true, mine does not

**Comment by dewwwald** [comment]
I could reproduce:
- Run the code once
- I commented out the line dropDatabase
- Commented the line that adds the Compound Index
- Restarted the script

So I guess I have to rebuild indices?

**Comment by dewwwald** [comment]
Simple to solve. Just run this command `Model.syncIndexes()` after you added a major index that does not seem to register.

```
(async function run() {
  class CustomSchema extends Schema {
    constructor() {
      super({
        author: {
          type: Schema.Types.ObjectId,
          required: true
        },
        date: {
          type: String,
          required: true
        },
        text: {
          type: String,
          required: true
        },
      },
      {
        _id: true,
        timestamps: true,
      }
      );
    }
  }
  const mySchema = new CustomSchema();

  const MyModel = mongoose.model('Test', mySchema);
  await MyModel.syncIndexes();
})()
```
