### ISSUE TITLE
timestamps not updated when option strict: false

### ISSUE THREAD

**Issue by talr1** [Automattic/mongoose#7531]
**Do you want to request a *feature* or report a *bug*?**
Report a possible bug

**What is the current behavior?**
schema with options timestamps enabled and strict: false not updated using findOneAndUpdate
schema with options timestamps enabled and strict: true updated using findOneAndUpdate

**If the current behavior is a bug, please provide the steps to reproduce.**

```
 var schema = new mongoose.Schema({}, 
  { 
      timestamps: { 
          createdAt: 'created_at', 
          updatedAt: 'modified_at' 
      },
      strict: false
  })

  var model = mongoose.model(`mycollection`, schema)
```
```
    var obj = await model.findOneAndUpdate(
            { _id: some_id }, 
            new_doc, 
            { new: true }).orFail(new Error('failed to update object'))

```

**What is the expected behavior?**
modified_at should contain the update date

I've added the following hook to do it manually but expect to be handled by mongoose:

```
schema.pre('findOneAndUpdate', async function() {
     this._update.modified_at = Date.now()
})
```

on schema with strict: true (the default) calling findOneAndUpdate updates the modified_at correctly

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: v10.15.0
Mongoose: 5.4.12
MongoDB: 4.0.4

**Comment by vkarpov15** [comment]
The below script executes updates timestamps correctly. Please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7531`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

   var schema = new mongoose.Schema({},
  {
      timestamps: {
          createdAt: 'created_at',
          updatedAt: 'modified_at'
      },
      strict: false
  })

  var model = mongoose.model(`mycollection`, schema)

  var doc = await model.findOneAndUpdate(
            { },             
            {},     
            { new: true, upsert: true });

  console.log(doc);
}
```

**Comment by cristhianGomez** [comment]
why are u using comma I'm confused Q_Q 
![image](https://user-images.githubusercontent.com/28577306/54085227-9b40e980-4309-11e9-96fd-c2ac609216b7.png)
