### ISSUE TITLE
unable to fetch data from mongodb using v5.4.13 but 5.0.0-rc0 working

### ISSUE THREAD

**Issue by techyaura** [Automattic/mongoose#7532]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
unable to fetch data from mongodb using v5.4.13

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
should fetch data from mongodb using v5.4.13

**Please mention your node.js, mongoose and MongoDB version.**
nodejs:  10.3.0
mongoose": 5.4.13
mongod version: 3.6.9

**Comment by vkarpov15** [comment]
Please provide code samples and explain how mongoose is failing to fetch - is there an error message? Are queries hanging?

**Comment by techyaura** [comment]
Thanks @vkarpov15 fo rthe reply.
Here is the code sample: 

`mongoose.connect('mongodb://<URL>', {useNewUrlParser: true});`

No error is coming, even queries are executing but with no results. But when I am using `mongoose 5.0.0-rc0`, everything is working smoothly.

**Comment by vkarpov15** [comment]
Do you set the database name in your connection string? Try explicitly setting the dbName option: https://mongoosejs.com/docs/api.html#mongoose_Mongoose-connect
