### ISSUE TITLE
Potential Memory Leak on queries

### ISSUE THREAD

**Issue by BrandonCopley** [Automattic/mongoose#7533]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**
model.query objects are retaining memory even after the query is completed

**If the current behavior is a bug, please provide the steps to reproduce.**
do a find that returns 200MB worth of data. that 200MB worth of space is allocated and never released.

**What is the expected behavior?**
memory should be released and not hanging around in "retained size"

**Please mention your node.js, mongoose and MongoDB version.**
node js, v10.15.1
mongoose, 5.4.13

I'm specifically running a very large query every few hours, and I'm noticing that this query is causing our applications memory usage to climb every time this query is run. Is there a better way to do this? I tried using cursors but I'm retrieving 10k+ documents and cursors seem to be incredibly slow for retrieving that many documents 1 at a time.

**Comment by vkarpov15** [comment]
Do you have code samples? There's any number of reasons why the memory isn't getting cleared, might not be an issue with mongoose

**Comment by mahaben** [comment]
Hello, I'm facing the same issue. I have a collection with 1400 documents  and I'm running a query using `lean`  to retrieve these documents every 5min. The query is as following and it is causing memory usage to climb:

`const orderArticles: OrderArticleDocument[] = await OrderArticleModel.find({
    accountId,
    ...(shopId ? { shopId } : {}),
    ...(orderArticleIds.length ? { _id: { $in: orderArticleIds } } : {}),
    ...(orderIds.length ? { orderId: { $in: orderIds } } : {}),
    ...(pickingContainerIds.length
      ? { pickingContainerId: { $in: pickingContainerIds } }
      : {}),
    ...(packingContainerIds.length
      ? { packingContainerId: { $in: packingContainerIds } }
      : {}),
    ...(statuses.length ? { status: { $in: statuses } } : {}),
  }).lean();

  return orderArticles.map(orderArticle => {
    return {
      ..._.omit(orderArticle, '__v', '_id', 'createdAt', 'updatedAt'),
      id: orderArticle._id,
    };
  });`

**Comment by vkarpov15** [comment]
@mahaben I'm unable to repro. It might be that you're just not waiting long enough for the garbage collector to kick in - V8's garbage collector is somewhat unpredictable. For example, given the below script:

```javascript
'use strict';
  
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  const schema = mongoose.Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  const numDocs = 1500;
  let count = await Model.countDocuments({});
  while (count < numDocs) {
    await Model.create({ name: `doc${++count}` });
  }

  const start = Date.now();
  while (true) {
    console.log(Date.now() - start, process.memoryUsage().heapUsed);
    const allDocs = await Model.find().lean();

    await new Promise(resolve => setTimeout(resolve, 500));
    console.log(Date.now() - start, process.memoryUsage().heapUsed);
    await new Promise(resolve => setTimeout(resolve, 500));
  }
}
```

Here's the heap usage `process.memoryUsage().heapUsed` I get over 60 seconds:

![chart](https://user-images.githubusercontent.com/1620265/67427881-02669200-f5ab-11e9-9a9d-a08e28f9a73c.png)

However, once I [expose `global.gc()` and force a garbage collection every iteration](https://www.xarg.org/2016/06/forcing-garbage-collection-in-node-js-and-javascript/) as shown below:

```javascript
'use strict';
  
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  const schema = mongoose.Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  const numDocs = 1500;
  let count = await Model.countDocuments({});
  while (count < numDocs) {
    await Model.create({ name: `doc${++count}` });
  }

  const start = Date.now();
  while (true) {
    console.log(Date.now() - start, process.memoryUsage().heapUsed);
    const allDocs = await Model.find().lean();

    await new Promise(resolve => setTimeout(resolve, 500));
    console.log(Date.now() - start, process.memoryUsage().heapUsed);
    global.gc(); // Force garbage collection
    await new Promise(resolve => setTimeout(resolve, 500));
  }
}
```

Then I get a consistent graph:

![chart (1)](https://user-images.githubusercontent.com/1620265/67428139-92a4d700-f5ab-11e9-8602-645a988a3b99.png)

So I don't see any indication that this particular script causes a memory leak - garbage collector can clean up all the memory just fine. If you can modify the above script to trigger a memory leak, I'm happy to look into it :+1:
