### ISSUE TITLE
Enum validation doesn't get executed.

### ISSUE THREAD

**Issue by fataltrace** [Automattic/mongoose#7536]
**Environment**
nodejs 10.8.0
mongoose 5.4.13
mongoDB 4.0.4

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can set any value for the "item" field.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const rootSchema = new Schema({
  ...
}, { minimize: false, timestamps: true, strict: 'throw', useNestedStrict: true })

const childSchema = new Schema({
  item: {
    type: String,
    enum: ['foo', 'bar'],
    default: 'foo'
  }
})

const query = { id: 1 }
const update = {
  $set: {
    'parents.$[parent].children.$[child].item': 'anyValue'
  }
}

const options = {
  new: true,
  runValidators: true,
  arrayFilters: [
    { 'parent.id': 'parent_id' },
    { 'child.id': 'child_id' }
  ]
}

Model.findOneAndUpdate(query, update, options)
```

**What is the expected behavior?**
I can set only "foo/bar" values because I use the "enum" validator. If I try to set something else then I will get an exception.

**Comment by fataltrace** [comment]
Thank you for the quick fix, but now I have next exception:
Field `items.ers.updatedAt` is not in schema and strict mode is set to throw.

**Comment by vkarpov15** [comment]
@fataltrace can you provide a code sample? That error isn't happening in our test case.
