### ISSUE TITLE
Document#deleteOne hooks

### ISSUE THREAD

**Issue by jojomon42153** [Automattic/mongoose#7538]
**Do you want to request a *feature* or report a *bug*?**
not feature, not bug, but misunderstanding some things
-EDIT- Now it's a feature request => see comment below -EDIT-

**What is the current behavior?**
My behavior is seemly like #6914.

I'm surely a big jerk but I passed half a day searching a way to do this;

Everywhere in my backend, I use deleteOne functions for my objects.
But now, I want to cascade-delete all childs objects when deleting a parent.
Now, warnings are not allowed at my job and Document.remove() throw warnings.

I know that [here](https://mongoosejs.com/docs/middleware.html), you say that `Schema.pre('deleteOne')` is not a document middleware but a query middleware, so `this` refers to the query, and I tested many solutions to bring the to-delete document in the callback, but many are really disgusting.

My question is: how can I get my document deleted by deleteOne in my `pre('deleteOne')` callback function?

Here is an example of where I want to apply it:
```
const notificationSchema = new mongoose.Schema({
  eventId: ObjectId,
});
const Notification = mongoose.model('Notification', notificationSchema);

const eventSchema = new mongoose.Schema({
  imagesUrl: Array,
});

eventSchema.pre( 'deleteOne', (next) => {
  // eventDeleted is the object deleted by deleteOne
  Notification.deleteOne({ eventId: eventDeleted._id }, (err) => { //do stuff  });
  eventDeleted.imagesUrl.forEach((url) => { functionToDeleteMyImages(url) });
});
const Events = mongoose.model('Events', eventSchema);

// we create an event1 and a notification with eventId = event1._id;

Event.deleteOne({ _id: event1id }, (err) => { // Do stuff });
```

**What is the expected behavior?**
Trigger a deleteOne middleware (pre or post, idc) and find the data deleted in the callback function

**Please mention your node.js, mongoose and MongoDB version.**
package.json:`
    "mongoose": "^5.3.1"
    "node": "^10.13"
`
MongoDB 3.6.8 Community

**Comment by jojomon42153** [comment]
So... i thought that remove throws some warnings... my bad... 
my solution: 
```
EventObject.findById(eventId, (err, document) => {
      if (err) {
        res.status(500).end();
      } else {
        document.remove((error, product) => { // triggers 'remove' document middleware
          if (error) {
            res.status(500).end();
          } else {
            res.status(200).end();
          }
        });
      }
});
```
So I edit my post in feature request:
it will be very cool to allow that `findOneAndRemove` and other query middlewares can be accessed in document middleware :)
like this: 
```
// Model
EventSchema.pre('findByIdAndRemove', (params) => {
     console.log(this);
     // output: { imagesUrl: [ url1, url2, ... ] }
})
// Service
EventObject.findByIdAndRemove(eventId, (err, document) => {
      if (err) {
        res.status(500).end();
      }  else {
        res.status(200).end();
      }
});
```

**Comment by vkarpov15** [comment]
We will add a deleteOne hook in the next minor release. Until then, you can use findOneAndDelete, and you can use findOne() in your pre('findOneAndDelete') hook as shown here: http://thecodebarbarian.com/introducing-mongoose-5.html

**Comment by jojomon42153** [comment]
Thanks :3 and with this feature the deleteOne function will trigger the pre middleware with `this = documentDeleted` ?

**Comment by vkarpov15** [comment]
Yes, but only if you're doing `doc.deleteOne()`, not if you do `Model.deleteOne()`.

**Comment by elginbeloy** [comment]
Hey, this issue seems to still be persisting with me using Mongoose 5.6.0 (npm).

Given a schema with the following middleware hook:

``` javascript

exampleSchema.post('deleteOne', function(next) {
  console.log("removing example...")
  console.log(this.attributeExample);

  doStuff();

  next();

});

```

And a deleteOne being called on a document like so:

``` javascript

let toDelete = await projectClass.findOne({
      _id: args.id,
      owner: context.user ? context.user.id : null
    }).exec();

let deleteResponse = await toDelete.deleteOne();

```

The delete happens and the document is indeed gone, however the hook is never called. Could just be me with some user error though?

Thanks in advance! :)

**Comment by vkarpov15** [comment]
@elginbeloy do this:

```javascript
schema.post('deleteOne', { document: true, query: false }, function() {
  console.log("removing example...")
  console.log(this.attributeExample);

  doStuff();
});
```

**Comment by elginbeloy** [comment]
Ah, works perfectly. Thank you bunches! Super appreciate it. :)

**Comment by nacimgoura** [comment]
Same problem, when the hook for deleteOne will be published?

**Comment by vkarpov15** [comment]
@nacimgoura already released. See [this comment](https://github.com/Automattic/mongoose/issues/7538#issuecomment-505275691) and [`Model#deleteOne()` in the docs](https://mongoosejs.com/docs/api/model.html#model_Model-deleteOne).
