### ISSUE TITLE
Model not aware of current connections transactions

### ISSUE THREAD

**Issue by samikarak** [Automattic/mongoose#7543]
**Do you want to request a *feature* or report a *bug*?**
I want to report a potential bug

**What is the current behavior?**
when I run a findOneAndUpdate() with a session, I get the following Error : 
> MongoError: Given transaction number 1 does not match any in-progress transactions.

The Link below describes the behaviour.

**If the current behavior is a bug, please provide the steps to reproduce.**
link : https://stackoverflow.com/questions/54768847/mongoose-model-has-no-access-to-connections-in-progress-transactions

**What is the expected behavior?**
expect to normally commitTransaction

**Please mention your node.js, mongoose and MongoDB version.**
nodejs : 8.11.1
mongodb : 4.0.6 - Type : replica set
mongoose : 5.4.14

**Comment by vkarpov15** [comment]
Can you please provide a more detailed code sample? Also, can you check if this is a TransientTransactionError? See my notes here: https://github.com/Automattic/mongoose/issues/7502#issuecomment-466517662

**Comment by samikarak** [comment]
It seemed to be a TransientTransactionError. solved on stacloverflow. Thanks
