### ISSUE TITLE
Feature Request: toObject with virtuals/getters but without aliases

### ISSUE THREAD

**Issue by ozomer** [Automattic/mongoose#7548]
The document `toObject` can be called with `virtuals: true` to include all virtuals in the result, which is very useful to get "calculated fields" in addition to the stored fields. For example, this could be useful to pass information to a user in a response to a GET request.
Aliases are a special type of virtuals which do not calculate anything new - they just help saving storage and converting data formats. In our case, for example, many camelCase fields also have their snake_case counterpart as an alias - so if in some part of the code there was a misnamed modification of `my_value` instead of `myValue`, it would still work. Another example could be copying JSON data from a different data source with misnamed fields .
If the user calls a GET request, I would like to be able to call something like `toObject({ virtuals: true, aliases: false })` and get an object with all the "calculated fields" but without the redundant aliases that the user don't care about.

**Comment by vkarpov15** [comment]
Good idea, will add for a future release. Something like `toObject({ virtuals: true, aliases: false })` sound about right?

**Comment by ozomer** [comment]
Yes, sounds great 👍
