### ISSUE TITLE
Incorrect binding of this variable in custom validator on update

### ISSUE THREAD

**Issue by jonasschmedtmann** [Automattic/mongoose#7549]
**Do you want to request a *feature* or report a *bug*?**
Bug, I think

**What is the current behavior?**
`this` is not defined as current document in custom validator when document is updated using `findByIdAndUpdate`. Works as predicted using `create`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const productSchema = new mongoose.Schema({
  price: {
    type: Number,
    required: [true, "Product must have a price"],
    min: 100
  },
  priceDiscount: {
    type: Number,
    validate: {
      validator: function(val) {
        return val < this.price;
      },
      message: "Discount price ({VALUE}) must be below regular price"
    }
  }
});

const Product = mongoose.model("Product", productSchema);

const product = await Product.findByIdAndUpdate(req.params.id, req.body, {
  new: true,
  runValidators: true
});
```

**What is the expected behavior?**
`this` should point to current document in custom validator, no matter if a new document is created or one is updated. Please correct me if I'm wrong.

**Please mention your node.js, mongoose and MongoDB version.**
Node: 10.11.0
Mongoose: 5.4.14
MongoDB: 4.0.6

**Comment by vkarpov15** [comment]
The problem is that the current document might not be in memory yet if you're using findByIdAndUpdate, so Mongoose would have to findOne() to load the document under the hood. You can use the context option to get access to the query as `this` instead: https://mongoosejs.com/docs/validation.html#the-context-option
