### ISSUE TITLE
List of bulkWrite options including ordered vs unordered

### ISSUE THREAD

**Issue by vladikus10** [Automattic/mongoose#7550]
**Do you want to request a *feature* or report a *bug*?**
Question

**What is the current behavior?**
When trying to insert duplicate documents using `bulkWrite` and `insertOne`, the function throws a duplicate error.

**What is the expected behavior?**
I expected, unlike `insertMany`, to add the error to `writeErrors` array of the result instead of throwing and canceling the whole operation.

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 8.15,
Mongoose: 5.4.9,
MongoDB: 4.0.5

**Comment by vkarpov15** [comment]
I'm not sure I understand the question, can you provide some code samples please?

**Comment by vladikus10** [comment]
Hi, sorry for the unclear question, so for example if I have a model **Entry** with schema:
```
new Schema({
        id:  {
               type: Number,
               unique: true
        }
})
```
Then, if the database already has an **Entry** with **id** = 2 and I make a `bulkWrite` operation:
```
const result = await Entry.bulkWrite([{
    insertOne: {
        document: {
          id: 1
        }
    }
}, {
    insertOne: {
        document: {
          id: 2
        }
    }
}, {
    insertOne: {
        document: {
          id: 3
        }
    }
}])
```
Then it would throw a `E11000` error, and the third operation never occurs. What I expected to happen: the `bulkWrite` does not throw any errors, instead it completes and adds the `E11000` error to the `writeErrors` parameter of the result.

**Comment by vladikus10** [comment]
Just as a clarification of what I'm trying to achieve: I'm trying to send multiple insert commands, where it is not important for all to succeed, some can fail while others will succeed. I was hoping to use `bulkWrite` to do this in a single mongo request instead of sending `insertOne` for each doc.

**Comment by vkarpov15** [comment]
Do `bulkWrite(ops, { ordered: false })`. See http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#bulkWrite . We will add this to our docs as well

**Comment by vladikus10** [comment]
Yes, `{ ordered: false }` did work, but I did notice that if at least one error occurs it still throws it with the result. However, as long as the error object contains the insert results as well, I can work with that.

Thanks for the help.

**Comment by bonesoul** [comment]
@vladikus10 will bulkwrite return the list of errors with `{ ordered: false }`?

**Comment by vkarpov15** [comment]
@bonesoul it should according to [the mongodb docs on error handling with `bulkWrite()`](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#error-handling)
