### ISSUE TITLE
Populate with where not working.

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [Automattic/mongoose#7551]
I have a method that just passes the query object to be treated in other points of the project, like
```js
const query = this.prepareQueryToMany(this.model.find())
```
the query object can be configured with several filters, but in this example I'm trying to popularize and do a filter treatment in another collection
```js
prepareQueryToMany(query) {
  query.populate({
    path: 'user',
    select: 'rule',
    options: { 
      where: { 
        'user.rule': new RegExp('admin', 'i') 
      } 
    }
  })
  return query
}
```
I just want to get the user admin rule, but it did not work, I also tried with the snippet `query.populate('user', 'rule').where({ 'user.rule': new RegExp('admin', 'i') })` and it did not work. I did some research and in all cases the examples used did not work, as they are very old examples I believe. 
I decided to come here to know which way to go?

**Comment by vkarpov15** [comment]
`query.populate({ path: 'user', match: { rule: ... } })`

**Comment by vkarpov15** [comment]
See populate API docs: https://mongoosejs.com/docs/api.html#model_Model.populate
