### ISSUE TITLE
Clarify that versioning only impacts arrays

### ISSUE THREAD

**Issue by rycfung** [Automattic/mongoose#7555]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** 
When a schema is created without turning off versioning, running the following does not increment the version of the document:
```
u = await User.findOne()
u.__v  // 0
u.profile.name = <some new value>
u.save()
u.__v // 0
u = await User.findOne() // assuming this is the only user in the collection
u.__v // 0
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a User schema with a single attribute (say name) that is embedded in an object 
eg. `{ profile: {name: 'John'}}`
2. Run the steps above

**What is the expected behavior?**
I expect __v to increment.

**Please mention your node.js, mongoose and MongoDB version.**
node: 8.15.0
mongoose: 5.4.15
mongodb: 4.x

**Comment by rycfung** [comment]
I did some digging and found that the document.$__dirty() method which is suppose to return an array of dirty values, does not contain any changed embedded documents. When is this going to be fixed.

**Comment by vkarpov15** [comment]
Currently Mongoose only bumps the version when you modify an array using an operation like push() or splice(). See here for more info: http://aaronheckmann.tumblr.com/post/48943525537/mongoose-v3-part-1-versioning
