### ISSUE TITLE
(node:21916) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by setsenbat** [Automattic/mongoose#7557]
Hello,

Could you please suggest me here:
I am having this error when I am trying to loop inside of post request:

`    server.post('/count', (req, res, next) => {
        //Check for JSON
        if (!req.is('application/json')) {
            return next(new errors.InvalidContentError("Expects 'application/json'"));
        }
        let counts = req.body;
        var element = Object.keys(counts);

        element.forEach(async (e) => {
            // console.log(counts[e]._EPC);
            epcs.push({
                _EPC: counts[e]._EPC
            });
            
            const x = await Inventory.find({});
            console.log(x); // works fine
            const newUpdate = await x.forEach(element => {
                 let epc1 = element.epc;
                 console.log(epc1);  //line causes error
             });

            try {
                await res.send(201);
                next();
            } catch (err) {
                return next(new errors.InternalError(err.message));
            }
        });
    });`

**Comment by XuToTo** [comment]
hi, reference #6420  ;-)

**Comment by vkarpov15** [comment]
What version of Mongoose are you on? This issue appears fixed as of v5.2.8

**Comment by setsenbat** [comment]
Hello, I am on v 5.4.8

**Comment by vkarpov15** [comment]
The below script executes without any warnings for me. Please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7557`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  console.log(process.version);
  console.log(mongoose.version);

  const Model = mongoose.model('Test', new Schema({ name: String }));
  await Model.create({ name: 'test' });

  const docs = await Model.find();

  docs.forEach(doc => console.log(doc));
}
```

Output:

```
$ node gh-7557.js 
v11.12.0
5.4.8
Mongoose: tests.insertOne({ _id: ObjectId("5caf53dbccdea76151901514"), name: 'test', __v: 0 })
Mongoose: tests.find({}, { projection: {} })
{ _id: 5caf53dbccdea76151901514, name: 'test', __v: 0 }
done
^C
$ 
```
