### ISSUE TITLE
Date type returns date-1 (date minus one day)

### ISSUE THREAD

**Issue by tagisen** [Automattic/mongoose#756]
I have the User Schema and the following instance
user = new UsersCollection({
    email: "i.beqiri@gmail.com",
    title: "Mr.",
    first_name: "Chuck",
    last_name: "Norris",
    birthday: "26 August 1983"
  });

The date type works perfectly when casting from any input format. The only problem was that the saved date would be moved to one day earlier.

Did not have time to investigate deeper. The solution I made was to change /lib/schema/date.js line 62 to 

if (date.toString() != 'Invalid Date')
    return date+1;

**Comment by Onheiron** [comment]
Same here.
From facebook API I get: `birthday: '05/28/1987'`
Then when I look into the DB: birthday: `'1987-05-27 22:00:00.000Z'`

**Comment by vkarpov15** [comment]
@Onheiron time zone issues. Looks like you're in UTC +2. Convert your date string to '1987-05-28 00:00:00.000Z' and you'll get the right date in the db.
