### ISSUE TITLE
.populate is returning empty array

### ISSUE THREAD

**Issue by seanlawrenz** [Automattic/mongoose#7562]
**Do you want to request a *feature* or report a *bug*?**
Bug, but might be my fault.

**What is the current behavior?**
.populate is returning empty array
**If the current behavior is a bug, please provide the steps to reproduce.**
Here is my models:
```
import mongoose, { Schema } from 'mongoose';

const DriverSchema = new Schema({
  name: String,
  trips: [{ type: Schema.Types.ObjectId, ref: 'Trip' }],
});

export default mongoose.model('Driver', DriverSchema);
```

```
import mongoose, { Schema } from 'mongoose';

const TripSchema = new Schema({
  startTime: Date,
  endTime: Date,
  miles: Number,
  driver: {
    type: Schema.Types.ObjectId,
    ref: 'Driver',
  },
});

export default mongoose.model('Trip', TripSchema);
```
Controller
```
export const getDrivers = async (req, res) => {
  try {
    const drivers = await Driver.find()
      .populate('trips')
      .exec();
    return res.json({ success: true, drivers });
  } catch (error) {
    return res.json({ success: false, error });
  }
};
```

**What is the expected behavior?**
Should return the trips that have the key value of driver
**Please mention your node.js, mongoose and MongoDB version.**
Node -v 11.10.0 mongoose 5.4.14 mongoDB 3.6 <-- this is being hosted on mLab

**Comment by chidiwilliams** [comment]
See https://github.com/Automattic/mongoose/issues/2562

**Comment by vkarpov15** [comment]
@seanlawrenz can you please provide a standalone script that demonstrates this issue? This looks like standard populate, and our tests are all passing.

One potential possibility: we don't support combining default imports and named imports in general. Try just doing `import mongoose from 'mongoose'`. 

Also, is your drivers array nonempty in the database?

**Comment by seanlawrenz** [comment]
@vkarpov15 Thats why I was super confused it is a standard populate. 

Drivers are nonempty in the data base. I'll get an example running soon.

**Comment by MaxLeiter** [comment]
@seanlawrenz I have a similar issue now. Very standard populate, array in DB is populated, but the array is returning empty. Did you find a solution?
