### ISSUE TITLE
DeprecationWarning: useNewUrlParser: true , port specified 

### ISSUE THREAD

**Issue by SlaySayto** [Automattic/mongoose#7566]
Hi, i am still getting the deprecated parser warring even after adding the option { useNewUrlParser: true }, also i specified the port my connection string is : "db": "mongodb://localhost:3200/auto-ecole-dev"
this error came after i move the code responsable for connection to the database to the db.js file :  
`const mongoose = require('mongoose');
const {logger} = require('../startup/logging');
const config = require('config');
// const dbDebug = require('debug')('app:db');

module.exports = () => {
    // connect to database
    mongoose.connect(config.get('db'), {
        useCreateIndex: true,
        useNewUrlParser: true
    })
        .then(() => logger.info( `connection to db: ${config.get('db')} succeeded`));
};`

mongoose version: 5.4.16
mongoDB version: 3.6.3
node version 11.8.0

**Comment by vkarpov15** [comment]
Do you have any other npm modules that connect to MongoDB, like connect-mongo or agenda? Try `npm list | grep "mongo"`

**Comment by SlaySayto** [comment]
This is the result of the command:
`
├─┬ mongoose@5.4.16
│ ├─┬ mongodb@3.1.13
│ │ ├── mongodb-core@3.1.11 deduped
│ ├─┬ mongodb-core@3.1.11
│ ├── mongoose-legacy-pluralize@1.0.2
└─┬ winston-mongodb@4.0.3
  └── mongodb@3.1.13 deduped
`

**Comment by vkarpov15** [comment]
Can you make sure this warning isn't coming from winston-mongodb? Try removing that winston transport and see if you still get the warning.
