### ISSUE TITLE
bulkWrite updateOne is not working with sub documents but query directly work in mongodb via Robot 3T

### ISSUE THREAD

**Issue by eldhoseelias** [Automattic/mongoose#7567]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by eldhoseelias** [comment]
UserModel.collection.bulkWrite(
[
    
      { updateOne : {
           "arrayFilters": [ { "userId": 1 ,"vehicles.plateNumber": {$in : ['1'] } } ], 
         "filter" : { "userId" : 1 , "vehicles.plateNumber":'1' },
         "update" : { $set : { "vehicles.$.vehicleType" : "name old" } }
      } },
         { updateOne : {
             "arrayFilters": [ { "userId": 1 ,"vehicles.plateNumber": {$in : ['2'] } } ], 
         "filter" : { "userId" : 1 , "vehicles.plateNumber":'2' },
       "update" : { $set : { "vehicles.$.vehicleType" : "name new" } }
      } },
        
   ]
      );

**Comment by eldhoseelias** [comment]
User collection
{
    "_id" : ObjectId("5be2a42703e4b31d28050481"),
    
    "userId" : 1,
    
    "vehicles" : [ 
        {
            "plateNumber" : "1",
            "vehicleType" : "name old"
        }, 
        {
            "plateNumber" : "2",
            "vehicleType" : "C44 Car11"
        }
    ],
   
}

**Comment by vkarpov15** [comment]
Can you please clarify what you mean by not working? Is there an error message of some sort? Also. What version of mongoose?
