### ISSUE TITLE
parent() function is not documented (for subdocuments and embedded documents)

### ISSUE THREAD

**Issue by marcospgp** [Automattic/mongoose#7576]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`parent()` function is present in `/lib/types/subdocument.js` and `/lib/types/embedded.js` but not documented:

```
/**
 * Returns this sub-documents parent document.
 *
 * @api public
 */

Subdocument.prototype.parent = function() {
  return this.$parent;
};
```

```
/**
 * Returns this sub-documents parent document.
 *
 * @api public
 */

EmbeddedDocument.prototype.parent = function() {
  return this[documentArrayParent];
};
```

The `parent()` function was last documented in the v3 docs.

I'm not sure what the difference is between subdocuments and embedded documents!

**If the current behavior is a bug, please provide the steps to reproduce.**
No steps

**What is the expected behavior?**
These functions should be described in the docs.

**Please mention your node.js, mongoose and MongoDB version.**
Latest (cloned repo and checked online docs).

**Comment by vkarpov15** [comment]
One is for single nested sundocs and one is for document arrays. We've been looking to reconcile those but haven't gotten to it yet.
