### ISSUE TITLE
Does document.save() return an error if the document is not found?

### ISSUE THREAD

**Issue by marcospgp** [Automattic/mongoose#7580]
Please point this out in the docs as I couldn't find any information. Thanks!

**Comment by vkarpov15** [comment]
Yes, although the only place I can find where we reference this is [here](https://mongoosejs.com/docs/api.html#mongooseerror_MongooseError-name). There will be a `DocumentNotFoundError` if the document has [`isNew` = false](https://mongoosejs.com/docs/api.html#document_Document-isNew) and the underlying document doesn't exist.
