### ISSUE TITLE
add $match to options watch() changes streams

### ISSUE THREAD

**Issue by becerriljc** [Automattic/mongoose#7581]
I need add to watch event the option $match how in mongodb docs:

const pipeline = [
  { $match: { 'fullDocument.username': 'alice' } },
  { $addFields: { newField: 'this is an added field!' } }
];

const collection = db.collection('inventory');
const changeStream = collection.watch(pipeline);

Because only accept fulldocument option.

Thanks

**Comment by vkarpov15** [comment]
Use [`Model.watch()`](https://mongoosejs.com/docs/api.html#model_Model.watch) in place of `collection.watch()`. See [this article](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html) for a walkthrough of how to do change streams with Node

**Comment by wolfejw86** [comment]
what am i missing here?  I am definitely using Model.watch() with the following code, and it doesn't seem to allow the pipeline to go in as a function (at least for typescript types) and even if i ignore types, it definitely doesn't trigger the aggregation:

**Comment by vkarpov15** [comment]
@wolfejw86 remember that the `$match` in `watch()` is aggregating on an [update document](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html#updates-and-the-fulldocument-option), _not_ on a `Person`. Do this instead:

```javascript
  Person.watch([{ $match: { 'fullDocument.address.1': { $exists: true } } }]).
    on('change', data => console.log(new Date(), data));
```
