### ISSUE TITLE
Missing documentation for return value of document.updateOne()

### ISSUE THREAD

**Issue by marcospgp** [Automattic/mongoose#7582]
I discovered by trial that document.updateOne() returns a value in the format `{ n: 1, nModified: 1, ok: 1 }`. I believe this is returned directly from MongoDB, but it would be great if this could be mentioned in the docs!

**Comment by mhombach** [comment]
Yeah, i think it's the pure result of MongoDB:
https://docs.mongodb.com/manual/reference/command/update/#update-command-output

Would be nice to have that linked in the mongoose-documentation :)
