### ISSUE TITLE
Populate a field inside an aggregate $lookup.

### ISSUE THREAD

**Issue by eliomaria** [Automattic/mongoose#7588]
Hey guys,

So i am new to mongo and mongoose and i am stuck with an issue that i cant seem to resolve.
So i have 3 entities, Organisation, Company and Country, like this examples:

```
Organisation: {"_id":"5c76b1aedc1a07350b8538fe","users_per_company":100,"lessons_per_company":20,"max_companies":1,"deleted":false,"name":"My Organization","createdAt":"2019-02-27T15:50:06.943Z","updatedAt":"2019-02-27T15:50:06.943Z","__v":0}

Company:
{"_id":"5c780440efc19d4b8255a80d","deleted":true,"name":"My COmpany","domain":"company.net","address":"beta strasse, 43","city":"Zurich","postal_code":"4812-112","country":"5c3dc4331f5eaa949664b3f6","organization":"5c76b1aedc1a07350b8538fe","createdAt":"2019-02-28T15:54:40.125Z","updatedAt":"2019-03-04T12:37:46.185Z","__v":0,"deletedAt":"2019-03-04T12:37:46.184Z","deletedBy":null}

Country:
{"_id":"5c3dc4331f5eaa949664b3f6","deleted":false,"tag":"CH","name":"Switzerland","area":"Europe","gmt":"+2","__v":0}
```

Now i want to get the list of organisations with a list of companies inside it. So i cannot do it with populate, because its not a relation in organisation. So i used an aggregate with a lookup to get a list of organisations with the companies related:

```
Organisation.aggregate([
      {
        $lookup: {
          from: 'companies',
          localField: '_id',
          foreignField: 'organisation',
          as: 'companies'
        }
      }
    ])
```

And this works perfectly. My problem now is that inside a company i want to get the related country too. I tried with another type of lookup, with a pipeline, but i cannot access the company to get the related country. Tried as well with a $map on companies, but without success either.

Any of you guys know a way to do this inside the aggregate? I tried to review all documentation of aggregate in mongo and mongoose, but without success.
I also didn't want to have an array of companies inside each organisation, or else i will need to manage this relation both in the company side and organisation side.

Thanks in advance!

**Comment by eliomaria** [comment]
I just used a virtual populate for it, so i dont need aggregations anymore.

**Comment by vkarpov15** [comment]
Perfect 👍 for future reference, here's the virtual populate docs: https://mongoosejs.com/docs/populate.html#populate-virtuals

And for your original problem, you likely needed to $unwind: https://mongoosejs.com/docs/api.html#aggregate_Aggregate-unwind . But in general, populate should be easier to use for nested relationships
