### ISSUE TITLE
connection 211 to cluster0- closed or timeout

### ISSUE THREAD

**Issue by zack1991** [Automattic/mongoose#7590]
I get this error from my running nodejs application on runtime.

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
83|node-sl | MongoError: connection 211 to cluster0-<>:27017 closed
83|node-sl |     at Function.MongoError.create (/data/node-slots-service/node_modules/mongodb-core/lib/error.js:29:11)
83|node-sl |     at TLSSocket.<anonymous> (/data/node-slots-service/node_modules/mongodb-core/lib/connection/connection.js:202:22)
83|node-sl |     at Object.onceWrapper (events.js:315:30)
83|node-sl |     at emitOne (events.js:121:20)
83|node-sl |     at TLSSocket.emit (events.js:211:7)
83|node-sl |     at _handle.close (net.js:561:12)
83|node-sl |     at Socket.done (_tls_wrap.js:360:7)
83|node-sl |     at Object.onceWrapper (events.js:315:30)
83|node-sl |     at emitOne (events.js:116:13)
83|node-sl |     at Socket.emit (events.js:211:7)
83|node-sl |     at TCP._handle.close [as _onclose] (net.js:561:12)

My Mongodb Connection Code :- 

```
mongoose.Promise = global.Promise;
mongoose.connect(configDB.url, {
    keepAlive: true,
    useMongoClient: true,
    autoIndex: false, //false
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 500, //In milliseconds
    poolSize: 50, //default maxPoolSize is 100 and default minPoolSize is 5,  Increase poolSize if Concurrent Users increase
    socketTimeoutMS: 45000 //Close sockets after 45 seconds of inactivity
}).then(() => {
    console.log("Database connected successfully");
}).catch(err => {
    console.error('App starting error:', err.stack);
});

mongoose.connection.on('connected', function () {
    console.log("MongoDB event connected");
});

mongoose.connection.once('open', function () {
    console.log('Connection to mongodb database is open');
});

mongoose.connection.on('disconnected', function () {
    console.log("MongoDB event disconnected");
});

mongoose.connection.on('reconnected', function () {
    console.log('MongoDB event reconnected');
});

mongoose.connection.on('error', function (err) {
    console.log('MongoDB event error: ' + err);
});
```

**Comment by vkarpov15** [comment]
This issue is most likely due to a database operation running longer than `socketTimeoutMS`, 45 seconds in your case. For example:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7590`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, {
    useNewUrlParser: true,
    socketTimeoutMS: 100
  });
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  await Model.create({ name: 'foo' });

  // This will throw "MongoNetworkError: connection 0 to localhost:27017 timed out"
  await Model.find({ $where: 'sleep(1000) || true' });
}
```

You can also just set `socketTimeoutMS` to 0 to [make sockets never time out](https://mongoosejs.com/docs/connections.html#options).

**Comment by zack1991** [comment]
This is my server code and i am handling **unhandledRejection** in my code, but on unhandled promise rejection this block never called and my process getting crashed. How can i stop my process to getting crashed due unhandledRejection.

Mongoose Version - 4.11.1
MongoDB Version - 3.4.20

var express = require('express'),
        app = express(),
        http = require('http'),
        port = process.env.PORT | 1339,
        bodyParser = require('body-parser'),
        mongoose = require('mongoose'),
        fs = require('fs'),
        configDB = require('./app/config/database.js');

app.use(bodyParser.urlencoded({extended: true, limit: '3mb'}));
app.use(bodyParser.json({limit: '3mb'}));

//Database connection start
mongoose.Promise = global.Promise;
mongoose.connect(configDB.url, {
    keepAlive: true,
    useMongoClient: true, 
    autoIndex: false, //false
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 500, //In milliseconds
    poolSize: 50, 
    socketTimeoutMS: 45000 //Close sockets after 45 seconds of inactivity
}).then(() => {
    console.log("Database connected successfully");
}).catch(err => {
    console.error('App starting error:', err.stack);
});

mongoose.connection.on('connected', function () {
    console.log("MongoDB event connected");
});

mongoose.connection.once('open', function () {
    console.log('Connection to mongodb database is open');
});

mongoose.connection.on('disconnected', function () {
    console.log("MongoDB event disconnected");
});

mongoose.connection.on('reconnected', function () {
    console.log('MongoDB event reconnected');
});

mongoose.connection.on('error', function (err) {
    console.log('MongoDB event error: ' + err);
});
//Database connection end


// Add headers
app.use(function (req, res, next) {

    // Website you wish to allow to connect
    res.setHeader('Access-Control-Allow-Origin', '*');

    // Request methods you wish to allow
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

    // Request headers you wish to allow
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

    // Set to true if you need the website to include cookies in the requests sent
    // to the API (e.g. in case you use sessions)
    res.setHeader('Access-Control-Allow-Credentials', true);

    // Pass to next layer of middleware
    next();
});

app.post('/slots/api/v1/game_user/*', [require('./app/middlewares/validateToken')]);
require('./app/routes.js')(app);

//Start the server
var httpServer = require('http').createServer(app);
httpServer.listen(port, function () {
    console.log('Server running on port ' + port + '.');
});

app.use(function (req, res) {
    res.status(404).send({url: req.originalUrl + ' not found', status_code: 404});
});


//To caught unhandled exception
process.on('uncaughtException', (error) => {
    console.log('Uncaught Exception :- ' + error.stack);
});

**//To caught unhandled rejection or rejected promise
process.on('unhandledRejection', (reason, p) => {
   console.log('Unhandled Rejection at :- ', p, '\n reason :- ', reason);
});**

//Custom Exception handling
app.use((err, req, res, next) => {
    if (err) {
        console.log('Custom Uncaught exception message :- ' + err.message + '\n Stack Trace :- ' + err.stack);
        res.send({result: 0, error_code: 701, error_message: 'Custom Uncaught Exception :- ' + err});
    }
});

**Comment by vkarpov15** [comment]
@zack1991 what error message are you getting and what happens leading up to the crash?

**Comment by zack1991** [comment]
I am getting this error message which leads to crash.

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection.
connection 2 to cluster timed out

**Comment by vkarpov15** [comment]
@zack1991 please read my [comments from March 10](https://github.com/Automattic/mongoose/issues/7590#issuecomment-471371796)
