### ISSUE TITLE
bug: `listeners` may not be used as a schema pathname

### ISSUE THREAD

**Issue by anasqadrei** [Automattic/mongoose#7593]
`listeners` is not one of [the reserved words](https://mongoosejs.com/docs/api.html#schema_Schema.reserved) but I get the above error when my schema has it.

`
const schema = mongoose.Schema({
listeners: Number
})
`

I'm using the below versions:
node.js 8.10
mongoose 5.3.4
MongoDB 4.0.6

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/5b8093439485d8a7b2ba3eadf62b05b655fd490e
