### ISSUE TITLE
why mongoose version 5 is so slow ? 

### ISSUE THREAD

**Issue by Zoha** [Automattic/mongoose#7596]
Hi.
I started a normal project and install mongoose. 
the version that was installed is `5.4.18`
after creating some models ] wanted to test models with mocha . 
and ] figure out that mongoose queries are too slow . 
each query takes about 1 - 2 second to execute!!
I understood that if I switch to previous versions like `4.4.10` queries will work properly.
this is my simple code for test speed : 
```
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect("mongodb://localhost:27017/testdb");

let User  = mongoose.model('User', new mongoose.Schema({
    username: {
        type: String,
        required: false,
        default: '',
        min: 0,
        max: 255,
    },
    email: {
        type: String,
    }
}));

let user = new User({
    username: 'test',
    email: 'tesafdjklas@gmail.com',
});

let time = (new Date).getTime();
user.save().then(() => {
    console.log('OK :' + ((new Date).getTime() - time));
});
```
after execute with mongoose version `5.4.18` it prints `OK :1004` -> about 1 seconds to execute
but by version `4.4.10` it prints `OK :40` -> 40 ms 
So . why new version is too slow ? 
or if I'm doing something wrong, what is it ?

**Comment by Zoha** [comment]
I replaced : 
`mongoose.connect("mongodb://localhost:27017/testdb");`
with : 
`mongoose.connect("mongodb://127.0.0.1:27017/testdb");`
and it is ok now :)

**Comment by vkarpov15** [comment]
ipv4 vs ipv6: See: https://mongoosejs.com/docs/connections.html#options .
