### ISSUE TITLE
Retry transaction automatically if possible

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#7598]
Re: https://github.com/Automattic/mongoose/issues/7502
Specifically this comment: https://github.com/Automattic/mongoose/issues/7502#issuecomment-470586927

**Comment by tomdee** [comment]
This seems to document a feature which doesn't exist. I can't see any references to the withtransaction helper in the code.

**Comment by vkarpov15** [comment]
@tomdee `withTransaction()` is implemented in the underlying MongoDB node driver, here's the release notes: https://github.com/mongodb/node-mongodb-native/releases/tag/v3.2.1
