### ISSUE TITLE
MongoNetworkError: connection closed at TLSSocket.

### ISSUE THREAD

**Issue by CFzsNanohaS** [Automattic/mongoose#7602]
**Do you want to request a *feature* or report a *bug*?**
No.

**What is the current behavior?**
Asking question for resolve this problem. I don't know what wrong with it. I want to connect with mongodb atlas free trial cluster. This is my connection.
> mongoose.connect('mongodb+srv://**username**:**password**@cluster0-a9jet.mongodb.net/<dbName>?retryWrites=true', { useNewUrlParser: true }).then(
    console.log("MongoDB is connected.")
).catch( (error) => { console.log(error) });

This is the error that I get.
 > MongoNetworkError: connection 3 to cluster0-shard-00-00-a9jet.mongodb.net:27017 closed
   at TLSSocket.<anonymous> (D:\Project\WalkingTrail\backend\node_modules\mongodb-core\lib\connection\connection.js:276:9)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at _handle.close (net.js:610:12)
    at TCP.done (_tls_wrap.js:386:7)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} 

I had try to close my firewall.
I had add my current IP address in IP whitelist.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
1. How can I resolve it?  
2. Why this error is happen?

**Please mention your node.js, mongoose and MongoDB version.**
node.js - v.10.15.0
mongoose - 5.3.12
MongoDB - v.3.6.5

**Comment by 720degreeLotus** [comment]
Did you check connecting with another tool to the DB directly, for example with "mongoDB compass"?

**Comment by CFzsNanohaS** [comment]
> Did you check connecting with another tool to the DB directly, for example with "mongoDB compass"?

I try to connect by using robo and I can't connect too.  

Now I think it's happen when I change IP in IP whitelist. After the status was active. I try to connect it again. It will can't connect.

**Comment by 720degreeLotus** [comment]
> > Did you check connecting with another tool to the DB directly, for example with "mongoDB compass"?
> 
> I try to connect by using robo and I can't connect too.
> 
> Now I think it's happen when I change IP in IP whitelist. After the status was active. I try to connect it again. It will can't connect.
> 
> And I don't know why and how long sometime I can connect.

Ok, that moves the problem away from mongoose to your database :)
If you cannot connect to your database with any tool, then this has nothing to do with mongoose.
You might want to disable ip-whitelisting for a short period of time to see, if that's the issue.
But this issue here can be closed :)

**Comment by CFzsNanohaS** [comment]
Thank you for your suggestion. I will colse it. I think it from my db.
