### ISSUE TITLE
can't save or update data in map or any loop

### ISSUE THREAD

**Issue by SaddamMakrani** [Automattic/mongoose#7605]
Here is my code which i use please provide me solution of this how can i update data in foor loop or any other loop.

this code is return this error
"TypeError: myDoc.update is not a function"

Model.find({ lookbooks: { $in: [req.params.id] } }).lean().exec(function(err, contst) {
                    contst.map(function(myDoc) {
                        var srt = (myDoc.lookbooks).toString();
                        var idx = srt.indexOf(req.params.id);
                        if (idx < 0) {
console.log("in if condition")
} else {
                            myDoc.lookbooks.splice(idx, 1);
                        }
                        myDoc.update();
                        return myDoc;
                    });
                });

**Comment by vkarpov15** [comment]
Get rid of `.lean()`, [lean means Mongoose doesn't hydrate the doc](https://mongoosejs.com/docs/api.html#query_Query-lean), so that means no `.update()`

**Comment by SaddamMakrani** [comment]
Thank You vkarpov15 its worked thanks for you help
