### ISSUE TITLE
Upgrade breaking plugin

### ISSUE THREAD

**Issue by j-norwood-young** [Automattic/mongoose#7609]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A plugin that is expected to work on _find_ no longer returns results. 
Working in Mongoose version 5.4.0, not working in 5.4.19.

**If the current behavior is a bug, please provide the steps to reproduce.**

NPM (unfortunately Github link is dead): https://www.npmjs.com/package/mongoose-post-find
A working repository with the plugin: https://github.com/digipolis/mongoose-post-find

**Comment by vkarpov15** [comment]
This plugin is no longer necessary, weve supported post find middleware since 4.0: https://mongoosejs.com/docs/middleware.html#types-of-middleware.
