### ISSUE TITLE
does Model.syncIndexes works?

### ISSUE THREAD

**Issue by mohsen89z** [Automattic/mongoose#7610]
**Do you want to request a *feature* or report a *bug*?**
None! I need a simple explanation:)
**What is the current behavior?**
I was trying to use this function in typescript as you wrote in your documentation:
`await Customer.syncIndexes()`
Apprently options is ***required***! so I passed an empty object to the function! I didn't work as expected! it recreated all the indexes!
Therefore I start reading your code:
<img width="983" alt="Screen Shot 2019-03-15 at 12 02 40 PM" src="https://user-images.githubusercontent.com/8802395/54420198-6cb47b80-471a-11e9-9d29-c258b080df2d.png">
what's the usage of options? and why an unused variable is required?

**What is the expected behavior?**
to stop creating already existed indexes!

**Please mention your node.js, mongoose and MongoDB version.**
node.js: v10.13.0
mongoose: ^5.4.19
MongoDB: latest

**Comment by vkarpov15** [comment]
Options is not required. Your screenshot excludes the relevant part of the `syncIndexes()` function. As the [`syncIndexes()` docs say](https://mongoosejs.com/docs/api.html#model_Model.syncIndexes), `options` is passed to `createIndexes()` [on this line](https://github.com/Automattic/mongoose/blob/6250902f34ec1f5988ace9cb16c3f7281d9d1f84/lib/model.js#L1291).

And `syncIndexes()` _only_ drops indexes that are not defined in your schema. Can you please provide your schema and the details of the indexes that were dropped?
