### ISSUE TITLE
bypassDocumentValidation is not working

### ISSUE THREAD

**Issue by Bexanderthebex** [Automattic/mongoose#7611]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
bypassDocumentValidation is not working despite the documentation

**If the current behavior is a bug, please provide the steps to reproduce.**

``` javascript
const addStatement = {
  $addToSet: { courses: { $each: coursesToAdd } },
};
const pullStatement = {
  $pull: { courses: { _id: { $in: courseIdsToPull } } },
};
const updateStatements = [
          insertOne: {
            filter: { _id: courseAssign.user_id },
            update: { pullStatement },
          },
          insertOne: {
            filter: { _id: courseAssign.user_id },
            update: { addStatement },
          },
]
const result = await User.bulkWrite(updateStatements, { options: { bypassDocumentValidation: true } });
```
the result is that it throws an error saying that the operation violates the validations for my user collection

**What is the expected behavior?**
The bulk write operation should bypass the document validation

**Please mention your node.js, mongoose and MongoDB version.**
node.js 8.11.3
mongoose 5.4.19
mongodb 4.0.0

**Comment by Bexanderthebex** [comment]
Solved this and the problem is that I am using insertOne and not updateOne. That is the reason why it is running it's validation.

**Comment by vkarpov15** [comment]
Why `options: { bypassDocumentValidation: true }` instead of just `bypassDocumentValidation: true`? That syntax is incorrect, see the bulkWrite docs: https://mongoosejs.com/docs/api.html#model_Model.bulkWrite
