### ISSUE TITLE
Wrong callsignature for $all/all?

### ISSUE THREAD

**Issue by 720degreeLotus** [Automattic/mongoose#7612]
In the current mongoose-version (as in the online-documentation) the function for mongo-db "$all"-operator is defined as this:

> Query.prototype.all()
> Parameters:
> - [path] <String>
> - val <Number>

How does this make sense? In the old 2.7.x-documentation this is documented as:
`query.all(path, array)` or
`query.all(array)`
which makes much more sense.

How should we use the `all()` function at this time, when we can only provide a pure `number` and not an array?
I am 99% sure this is an important bug, but if someone can tell me how this function has to be used (there is no example to find on the documentation or on the internet) then i'm also happy.

**Comment by 720degreeLotus** [comment]
@vkarpov15 Thx so much for that fast fix.
I want to commit a change to apply this bugfix to the documentation, but i do not understand:

> If  you're making a change to documentation, do **not** modify a `.html` file directly. Instead find the corresponding `.jade` file or test case in the `test/docs` directory.

I found the `api.jade` file but although i was able to change the html-file directly, i really don't understand how the jade-file must be changed. As far as i understand, it loops (`each item in docs`) through some "docs"-object but i could not find where this `docs` comes from (i think i need to do the changes within that object).
Can you shortly give me an answer here or should i open a new issue for this question?

**Comment by 720degreeLotus** [comment]
Question(s) moved to new issue (https://github.com/Automattic/mongoose/issues/7623).

**Comment by vkarpov15** [comment]
The API docs are special in that they're generated by parsing comments out of `lib/` by `docs/source/api.js` . So if you want to change the API docs, you change the corresponding comments like I did to fix this issue
