### ISSUE TITLE
Can't return list of enumvalues when key is array object

### ISSUE THREAD

**Issue by travis5491811** [Automattic/mongoose#7613]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

I have a model where one of the fields accepts an array of values. When i submit the data, it validates correctly, but I'm unable to get a list of values using enumValues. 

I've tried the following:
```javascript
// model
const Outside = new Schema({ tree: [{type: String, enum: ['big', 'bigger']}]);

// in controller
const result = await Outside.schema.path('tree').enumValues;
console.log(result);
```

Result is always undefined and if i take off enumValues to see what was found, I can only see:
```SHELL
SchemaArray {
  casterConstructor: { [Function: SchemaString] schemaName: 'String' },
  caster:
   SchemaString {
     enumValues:
      ['big', 'bigger']
...
```

...but `Outside.schema.path('tree').SchemaArray` doesn't get me anywhere either.

**What is the expected behavior?**

`Model.schema.path('tree').enumValues` should return array. Is this a bug?

**Please mention your node.js, mongoose and MongoDB version.**
MongoDB version v3.6.3
Node version 10.12.0
mongoose": "^4.13.17"

**Comment by vkarpov15** [comment]
It shouldn't return a value because an array is a separate path. You should do `schema.path('tree').caster.enumValues` or `schema.path('tree.0').enumValues`
