### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by useo6** [Automattic/mongoose#7614]
**Do you want to request a *feature* or report a *bug*?**

- [x] Bug
- [ ] Feature

**What is the current behavior?**
mongoose consumes more and more memory and with every query, the entire app slows down more and more. Finally, the app crashes with the following message:

```
<--- Last few GCs --->

[1112:0000026D4B56BE20]   621345 ms: Mark-sweep 1401.9 (1478.3) -> 1401.9 (1444.8) MB, 1662.8 / 0.0 ms  last resort GC i
n old space requested
[1112:0000026D4B56BE20]   622442 ms: Mark-sweep 1401.9 (1444.8) -> 1401.9 (1444.8) MB, 1097.5 / 0.0 ms  last resort GC i
n old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000145096A5879 <JSObject>
    0: builtin exit frame: concat(this=000002A7857CE149 <JSArray[0]>,000002093DD02201 <JSArray[113485]>)

    1: next(aka next) [<< Cutted Off >>\node_modules\mongoose\lib\model.js:3903] [bytecode
=0000006885C9D711 offset=98](this=000000D720F822D1 <undefined>,options=000002A7857CE011 <Object map = 000002D831C3FD41>,
assignmentOpts=000002A7857CE081 <Object map = 0000...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::Factory::NewJSArrayStorage
 6: v8::internal::WasmDebugInfo::SetupForTesting
 7: v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString
 8: v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString
 9: v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString
10: 000000B2FB506B21
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! myapp@1.0.0 start: `node index.js`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the myapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2019-03-16T21_51_55_126Z-debug.log
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Unfortunately I cannot provide any code because I don't know the reason why or when it's happening :-(

**What is the expected behavior?**

That the memory usage doesn't increase significant :-)

**Please mention your node.js, mongoose and MongoDB version.**

nodejs: 8.11.4
mongoose: 5.4.19
MongoDB: 3.6

**Comment by 720degreeLotus** [comment]
Well, without any code, we cannot do much :/
I guess if you just create a basic model and create a loop where data is written and read to the database, that should not have any significant impact on the nodejs-app whatsoever.
So maybe you have something in your code that produces this issue? Can you try to, after creating a backup, delete more and more code segments from your application until the issue vanishes? This way we can try to pinpoint, what segment is producing this issue.

**Comment by vkarpov15** [comment]
Without more information there isn't much we can do with this. There's way too many possible explanations for us to make an informed hypothesis about the cause of this. Code samples would help

**Comment by useo6** [comment]
I't hard to figure out when this happens, but i'll try. In my database, I've two schemas: schema 1 (s1) has 57 entries while schema 2 (s2) has 115033 entries. Each entry in s2 is assigned to exactly one entry in s1. Now... I've a webpage that executes the following query:

`s1.find({}).populate({ path: 'schema2', model: s2}).exec((e, r) => response.render('schemas', r))`

The query is very slow (takes about 1 minute to complete), although I'm using the _id-field to populate s2 which is marked as index. Furthermore after executing this query multiple times my app starts to slow down and finally crashes with the 'JavaScript heap out of memory'-exception.

**Comment by 720degreeLotus** [comment]
@useo6 we need more "technical" information :)
1. if we are talking about just 2 schemas, then please post those 2 schemas/models here, i m ean "eactly" those schemas. Sometimes it's the small things/mistakes that matter.
2. please show us the code you are executing (is it only the population or is your code doing some other things too?)
3. Can you give us some information about the hardware of the database? from my experience such a query should, on my laptop for example, take just a 1-2 seconds.
4. You are saying that your app slows down and crashes after several iterations of execution. This may be linked to some memory-leak in your app, so we need, as mentioned in (2), your code.

**Comment by vkarpov15** [comment]
@useo6 sounds like there's a lot of IDs in `s1.schema2`, how many IDs are in one of those arrays?
