### ISSUE TITLE
Mongoose coercing array to string

### ISSUE THREAD

**Issue by marcospgp** [Automattic/mongoose#7619]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Value of a field in the database is an array. Mongoose schema type for that field is string. Mongoose coerces value to string. This is bad and error prone.

**What is the expected behavior?**
Mongoose should throw an error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`"mongoose": "^5.4.14",`
`mongo: image: mongo:4.0`

**Comment by 720degreeLotus** [comment]
Can you provide example code?
If you specify an `array` in a mongoose schema, it will stay an array in the database and will not getting stringified or something like that.

**Comment by marcospgp** [comment]
@720degreeLotus in this case we specified string in the schema, not array. Mongoose hides the fact it is an array in the database, presenting the value on the app as "value1,value2".

**Comment by 720degreeLotus** [comment]
@marcospgp I can tell you, that a **string** in mongoose is saved as a **string** in the mongoDB database and not as an aray.
Please post us your schema-definition and we can help you :)

**Comment by vkarpov15** [comment]
I'm not sure I like throwing an error when loading the doc. We could treat this as a cast error. It's also worth it to check if disabling array casting fixes this, I'll look into it
