### ISSUE TITLE
syncIndexes() should handle schema-level collation differences

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#7621]
I ran into an issue today where sorting on an indexed field was hitting the 32MB MongoDB memory issue.

It turns out that defining `new Schema({ ..., full_name: { index: true, type: String } }, { collation: { locale: 'en' } });` doesn't automatically set the collation option on the index for `full_name`.

I've fixed it manually by:

```sh
> db.users.dropIndex({ full_name: 1 });
{ "nIndexesWas" : 38, "ok" : 1 }
> db.users.ensureIndex({ full_name: 1 }, { collation: { locale: 'en' } });
{
    "createdCollectionAutomatically" : false,
    "numIndexesBefore" : 37,
    "numIndexesAfter" : 38,
    "ok" : 1
}
```

However if I migrate this to another server, Mongoose doesn't set this by default, so I'd have to re-run the above script.

Is there a way to set this as a global default if `collation: ...` option is passed to the schema for indices?

**Comment by vkarpov15** [comment]
That's an interesting idea. Will consider for a future release

**Comment by niftylettuce** [comment]
Thanks

**Comment by niftylettuce** [comment]
For anyone else reading this, here is the workaround (remove `index: true` in your schema first):

```js
// fix per <https://github.com/Automattic/mongoose/issues/7621>
User.index({ full_name: 1 }, { collation: { locale: 'en' } });
```

**Comment by Enado95** [comment]
can't you add strength for case insensitivity @niftylettuce ? I tried and it didn't really work. Only works if i create the collection manually first

**Comment by vkarpov15** [comment]
I took a closer look and it looks like the MongoDB server does pull the collection-level collation when creating indexes, at least as of MongoDB 4.2:

```javascript
    const testSchema = new Schema(
      { name: { type: String, index: true } },
      { collation: { locale: 'en' } }
    );
    const Test = db.model('Test', testSchema);

    await Test.init();

    console.log(await Test.collection.listIndexes().toArray());
```

Prints:

```
[
  {
    v: 2,
    key: { _id: 1 },
    name: '_id_',
    collation: {
      locale: 'en',
      caseLevel: false,
      caseFirst: 'off',
      strength: 3,
      numericOrdering: false,
      alternate: 'non-ignorable',
      maxVariable: 'punct',
      normalization: false,
      backwards: false,
      version: '57.1'
    }
  },
  {
    v: 2,
    key: { name: 1 },
    name: 'name_1',
    background: true,
    collation: {
      locale: 'en',
      caseLevel: false,
      caseFirst: 'off',
      strength: 3,
      numericOrdering: false,
      alternate: 'non-ignorable',
      maxVariable: 'punct',
      normalization: false,
      backwards: false,
      version: '57.1'
    }
  }
]
```

However, keep in mind that adding a `collation` option to your schema will not affect existing indexes, _unless_ you call `syncIndexes()`. Mongoose doesn't modify existing indexes by default.
