### ISSUE TITLE
options.dbName Authentication failed.

### ISSUE THREAD

**Issue by baijunjie** [Automattic/mongoose#7622]
Use mongo user connection successfully
```sh
$ mongo 127.0.0.1:27017/mydb -u mydb-manager -p123456
```
`mydb-manager` authority is `[{role: 'dbOwner', db: 'mydb'}]`

Use mongoose url connection successfully
```js
mongoose.connect(`mongodb://${host}:${port}/mydb`,  {
    user: 'mydb-manager',
    pass: '123456',
    ...
});
```

Use mongoose `options.dbName` connection failed: `{ MongoError: Authentication failed. }`
```js
mongoose.connect(`mongodb://${host}:${port}/`,  {
    user: 'mydb-manager',
    pass: '123456',
    dbName: 'mydb',
    ...
});
```

Why?

mongoose Version: 5.4.19

**Comment by vkarpov15** [comment]
`dbName` is the database mongoose uses for loading and storing documents, not the database mongoose uses for authentication. These are two separate concepts. Set `authSource: 'mydb'` : http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html

**Comment by baijunjie** [comment]
Thanks
