### ISSUE TITLE
How to commit to documentation?

### ISSUE THREAD

**Issue by 720degreeLotus** [Automattic/mongoose#7623]
@vkarpov15 To not discuss this in an already closed issue, i created this one new (relates: https://github.com/Automattic/mongoose/issues/7612)

A few question regarding the official mongoose documentation:

1. Is there some explanation how the jade-structure is working? As mentioned here (https://github.com/Automattic/mongoose/issues/7612#issuecomment-474344166), even when understanding the concept of jade, it's not easy to find the "entry-points" where changes should be made (because, like in the example of `https://github.com/Automattic/mongoose/blob/master/docs/api.jade`. In this file the structure for the html-file is generated, but i cannot find where the `docs`-"object" for generation (`each item in docs`) is defined and filled, so i can add to the documentation.

2. If i were to edit/change the documentation on, for example, 3 different parts, should i put those changes in one single pull-request or each changed part in a separate pullrequest?

3. Is there a known ("best pratice")-way to "preview" the changed jade/html files (include CSS and scripts) without running a a local webserver with the complete project?

**Comment by vkarpov15** [comment]
1. Nope there's no explanation out there. It's a bit of a hodge podge right now. But the api.jade file is generated by `docs/source/api.js`
2. One PR is fine
3. Nope. `make gendocs` and `node static.js` is the only way I can think of

**Comment by 720degreeLotus** [comment]
@vkarpov15 Wow, ok this seems pretty clever :) Will try to add to that, whereever it's possible and needed.
