### ISSUE TITLE
[feature] How can i add a project stage in pre aggregation middleware?

### ISSUE THREAD

**Issue by desmondiazz** [Automattic/mongoose#7624]
mongodb: v3.6.3
mongoose: 5.4.8
node: 8.12.0

I have a schema in which im making multiple aggregate calls , and all of these aggregate calls have the same project stage. so i was looking for a middleware function so that i have to write the project stage once for that schema and not every time i make an aggregate call. 
i came  a across the "pre aggregation" middleware. but im not sure if it is possible to archive this.

`Schema.pre('aggregate', function () {
    this.project({ title: 0 }).pipeline();
});`

i have tried this but didnt get the expected results.
can anyone tell me if this is possible or is there a better method to archive this
Thank you

**Comment by vkarpov15** [comment]
`Schema.pre('aggregate', function() { this.project({ title: 0 }); })` should be sufficient. You only need `pipeline()` if you want to add a stage that isn't the last stage in the pipeline: https://mongoosejs.com/docs/api.html#aggregate_Aggregate-pipeline
