### ISSUE TITLE
The return result is wrong, when i try to remove a document.

### ISSUE THREAD

**Issue by snowdream** [Automattic/mongoose#7629]
when i try to remove a document with model.remove,  the document is removed.
but the result result is wrong:
{
  "n": 1,
  "ok": 1
}

but not 
{
  "n": 1,
  "ok": 1,
 "deleteCount":1
}

**Comment by vkarpov15** [comment]
What version of MongoDB and mongoose?

**Comment by snowdream** [comment]
@vkarpov15 
MongoDB shell version v3.4.10
"mongoose": "^5.4.19",
