### ISSUE TITLE
【Bug at v5.3.15+】The nested Map cannot be read?

### ISSUE THREAD

**Issue by baijunjie** [Automattic/mongoose#7630]
Schema
```js
const schema = new mongoose.Schema({
    describe: {
        type: Map,
        of: Map,
        default: {}
    }
});

const GoodsInfo = mongoose.model('GoodsInfo', schema);
```

At v5.3.14
```js
(async function(){
    try {
        let goodsInfo = new GoodsInfo();
        goodsInfo.describe = new Map();
        goodsInfo.describe.set('brand', new Map([['en', 'Hermes']]));
        
        await goodsInfo.save();
        const id = goodsInfo.id;
        console.log(id);

        goodsInfo = await GoodsInfo.findById(id);
        console.log(goodsInfo.describe); // => Map(1) {"brand" => Map(1)}
    } catch (err) {
        console.error('ERROR :', err);
    }
})()
```
As expected
![3](https://user-images.githubusercontent.com/7956480/54795758-cd9b0100-4c90-11e9-9030-c22df3ebd0e6.jpg)

At v5.3.15+
```js
(async function(){
    try {
        let goodsInfo = new GoodsInfo();
        goodsInfo.describe = new Map();
        goodsInfo.describe.set('brand', new Map([['en', 'Hermes']]));
        
        await goodsInfo.save();
        const id = goodsInfo.id;
        console.log(id);

        goodsInfo = await GoodsInfo.findById(id);
        console.log(goodsInfo.describe); // => Map(0) {}
    } catch (err) {
        console.error('ERROR :', err);
    }
})()
```
I get one empty Map
![1](https://user-images.githubusercontent.com/7956480/54795773-d8ee2c80-4c90-11e9-84c8-44f353fc48e4.jpg)

At v5.3.15+ modify Schema
```js
const schema = new mongoose.Schema({
    describe: {
        type: Map,
        of: Object, // Map change to Object
        default: {}
    }
});
```
Non-nested Map schema for correct reading
![2](https://user-images.githubusercontent.com/7956480/54795784-dbe91d00-4c90-11e9-82c6-343262406e33.jpg)

**Comment by 720degreeLotus** [comment]
I can confirm this. `v5.3.14` works correct, `5.4.19` (latest) for example doesn't work.
I also checked the values stored in the DB with MongoDB-Compass and the man is not stored.
Did we maybe miss any breaking changes?

**Comment by 720degreeLotus** [comment]
I also verified that when i manually revert the few changes made in https://github.com/Automattic/mongoose/commit/07fc01757640be6a071f299e6d40358f8d8a3e22 , the code works as expected, even in `v5.4.19`.
Don't have time right now to dive into this in more detail, but i think this should be doable very easy, since the commit only contains a hanful of new lines and changes.
Will try  to see, if i can fix this later today.
