### ISSUE TITLE
Empty result when a field of a populated object is filtered.

### ISSUE THREAD

**Issue by fernandops26** [Automattic/mongoose#7632]
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.4.19.
Node: 8.15.1
MongoDB: 4.0.6

I am trying apply a filter to specific field of a populated model of mongo, but the result is empty.

This are the schemas:

```js
const inspectionSchema = new Schema(
	{
		inspectionNumber: String,
		campaign: { type: Schema.Types.ObjectId, ref: 'campaigns' },
	},
	{ timestamps: { createdAt: 'createDate' } }
);

const campaignSchema = new Schema({
	name: String,
	commodity: { type: Schema.Types.ObjectId, ref: 'commodities' },
});

const commoditySchema = new Schema({
	name: String,
	image: String
});
```

My config to populate:

```js
const populateConfig = [
	{
		path: 'campaign',
		select: 'name _id commodity',
		populate: {
		     path: 'commodity',
		     select: 'name image _id'
	        }
        }
];
```
		
The filter:

```js
const filter = {'campaign.commodity': '5c3e3111cd152d205b868f6d' };
```
Here, `this.paginate` is a custom function where is used `mongoose-paginate-v2`.

```js
const result = await this.paginate(filter, 1, {
	populate: this.populateConfig,
	sort: { createDate: 'desc' }
});
```
But I am not get any result, what I am doing wrong? :|

**Comment by vkarpov15** [comment]
MongoDB doesnt let you query on foreign fields, you'll need to use $lookup : http://thecodebarbarian.com/node-perspective-on-mongodb-3.2-$lookup-$sample
