### ISSUE TITLE
docs: useCreateIndex is NOT a connection option but it is documented as one

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#7638]
The option `useCreateIndex` is not a connection option, and when using it as a connection option you will receive the following warning:

```sh
the options [useCreateIndex] is not supported
```

It is documented as one here: <https://mongoosejs.com/docs/deprecations.html

References:
https://github.com/Automattic/mongoose/issues/6890#issuecomment-418694010

**Comment by vkarpov15** [comment]
@niftylettuce can you double check your [Mongoose version](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-version) and make sure you're on at least [5.2.16](https://github.com/Automattic/mongoose/blob/master/History.md#5216--2018-09-19) ? Below script doesn't print this warning for me using v5.4.21:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7638`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true, useCreateIndex: true });
  await mongoose.connection.dropDatabase();
}
```
