### ISSUE TITLE
The method set can not be used to an uninitialised field of type Map

### ISSUE THREAD

**Issue by dirchev** [Automattic/mongoose#7642]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

We have a schema with a field of type `Map`. When creating a document and trying to set a property to the field of type `Map` - we get an error `TypeError: Cannot read property 'set' of undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have written a test for that which you can find [here](https://github.com/dirchev/mongoose/blob/master/test/document.test.js#L5651-L5666)

```javascript
    it.only('Allows setting a map propery', function(done) {
      const schema = new mongoose.Schema({
        name: String,
        arrField: [String],
        mapField: {
          type: Map,
          of: String
        }
      }, { strict: true });

      const Model = db.model('maptest', schema);
      const doc = new Model({name: 'something'});
      doc.arrField.push('a'); // this is OK
      doc.mapField.set('a', 'a'); // this throws an error
      done();
    });
```

**What is the expected behavior?**

I was expecting to be able to use the method `set` even if the field has never been initialised. This behaviour exists with fields of type `Array` (as shown in the test above), where `push` can be used on the field even if it had never been initialised

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node - `v10.15.1`
MongoDB - `v3.4.17`
Mongoose - fails on `master` and `5.4.15` as far as I have tested

**Comment by dirchev** [comment]
The current workaround I have found is to initialise the field as a `Map`:
So the test would be:

```
    it.only('Allows setting a map propery', function(done) {
      const schema = new mongoose.Schema({
        name: String,
        arrField: [String],
        mapField: {
          type: Map,
          of: String
        }
      }, { strict: true });

      const Model = db.model('maptest', schema);
      const doc = new Model({name: 'something'});
      doc.arrField.push('a'); // this is OK
      doc.set('mapField', new Map());
      doc.mapField.set('a', 'a'); // now it is OK
      done();
    });
```

**Comment by vkarpov15** [comment]
This is expected behavior currently, because `doc.mapField` is null. You should set a default for `mapField`:

```javascript
      const schema = new mongoose.Schema({
        name: String,
        arrField: [String],
        mapField: {
          type: Map,
          of: String,
          default: () => ({})
        }
      }, { strict: true });
```

So Mongoose will initialize it to an empty map for you.

Arrays are fine because they [implicitly have empty array `[]` as their default](https://mongoosejs.com/docs/schematypes.html#arrays).
