### ISSUE TITLE
Destructuring Document causes error `obj.toObject` is not a function

### ISSUE THREAD

**Issue by uptownhr** [Automattic/mongoose#7645]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have upgraded to the latest mongoose from 4.x to 5.x and now currently if I destructure the document described below, I run into an error `obj.toObject` is not a function. 

I will add that I have ran this same test against another schema and was not able to reproduce this error. Would appreciate the help identifying what in the profileSchema is causing this.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/uptownhr/048749c0d85264d502dd9df467dfb1d0

**What is the expected behavior?**
Should destructure properly and be able to output without error and be used.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 8.12.0
Mongoose: 5.4.19

**Comment by vkarpov15** [comment]
@uptownhr running the below script still gives me an error in 4.8, albeit a slightly different one:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7645`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
console.log(mongoose.version);

  const profileSchema = new Schema({ name: String, email: String });
  const companyUserSchema = new Schema({
    profile: {
      type: profileSchema,
      default: {}
    }
  });

  const CompanyUser = mongoose.model('Test', companyUserSchema);

  const cu = new CompanyUser({});
  cu.profile = { name: 'foo', email: 'bar' };

console.log('------');
  cu.profile = { ...cu.profile };
console.log('------');

  console.log(cu);
}
```

In 4.8:

```
$ node gh-7645.js 
(node:10163) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
4.8.7
------
------
RangeError: Maximum call stack size exceeded
    at exports.isMongooseObject (/home/.../mongoose/lib/utils.js:532:36)
^C
$ 
```

**Comment by vkarpov15** [comment]
Fix will be in 5.4.21 :+1:

**Comment by ishan123456789** [comment]
Still facing it in version `"mongoose": "^5.8.9",`

**Comment by vkarpov15** [comment]
@ishan123456789 please open a new issue and follow the issue template. +1 comments on long-closed issues are not helpful.
