### ISSUE TITLE
Not able to populate array of arrays

### ISSUE THREAD

**Issue by lakshmipriyamukundan** [Automattic/mongoose#7647]
I have a mongoose model with following field. And I am not able to populate the 'recordings'.

`
recordings: [[{
    cueIn: Number,
    file: {
      type: Schema.ObjectId,
      ref: 'asset',
    }
  }]]
`

**Comment by 720degreeLotus** [comment]
How (code) are you trying to populate it?

**Comment by lakshmipriyamukundan** [comment]
This is how I do populate:
```js
Movies
.find({})
.populate({ path: 'recordings.file' })
```

**Comment by 720degreeLotus** [comment]
You have double brackets `[[...]]`, can you tell me the reason for this?
Does your code throw any error?
And for the future: If you ask for help, regardless where, please provide as MUCH information as possible in your first post:
- We don't know your code
- We don't know the version of your nodeJs, of your mongoose or your mongoDB
- we don't know if and what errors are thrown

:)
