### ISSUE TITLE
Date changed when the object is saved

### ISSUE THREAD

**Issue by moadennagi** [Automattic/mongoose#7648]
**Do you want to request a feature or report a bug?**
A bug.

**What is the current behavior?**
When passing an incorrect date format (`11111-012-31`) to the model constructor I get a weird date format.
```
{ _id: 5caca77d48831c446ea1ba64,
  date: +011111-12-30T23:00:00.000Z,
  __v: 0 }
```

**Steps to reproduce**
```
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });

const userSchema = new mongoose.Schema({ date: Date });
const User = mongoose.model('User', userSchema);

let user = new User({date: '11111-012-31'})
  .save()
  .then(doc => console.log(doc))
  .catch(err => err);
```

**What is the expected behavior?**
Should raise a `ValidationError`.

**What are the versions of Node.js, Mongoose and MongoDB you are using?** 
Node: 9.2.0
MongoDB: 4.0.8
Mongoose: 5.4.19

**Comment by vkarpov15** [comment]
Unfortunately, I'm going to have to mark this as expected behavior for now. Mongoose defers parsing dates to the native JavaScript date constructor modulo [one edge case](https://mongoosejs.com/docs/tutorials/dates.html#casting-edge-cases), and the date constructor casts that string successfully:

```
$ node
> new Date('11111-012-31')
+011111-12-31T05:00:00.000Z
> 
```
