### ISSUE TITLE
Models do not return a Promise

### ISSUE THREAD

**Issue by FlorisSchippers** [Automattic/mongoose#7651]
**Do you want to request a feature or report a bug?**  
A bug.

**What is the current behavior?**  
```
4:27:56 PM dev.1 |  not found
4:27:56 PM dev.1 |  (node:42399) UnhandledPromiseRejectionWarning: No webComponent found
4:27:56 PM dev.1 |  (node:42399) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
4:27:56 PM dev.1 |  (node:42399) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
4:27:56 PM dev.1 |  Success: null
```

**If the current behavior is a bug, please provide the steps to reproduce.**  
```
WebComponent.findOne({mwcm_uri}, (err, webComponent) => {
    if (err) {
        console.log('err');
        return Promise.reject(err);
    } else if (webComponent) {
        console.log('webComponent');
        return Promise.resolve(webComponent);
    } else {
        console.log('not found');
        return Promise.reject('No webComponent found');
    }
})
    .then(webComponent => console.log('Success:', webComponent),
        reason => console.log('Error:', reason));
```

**What is the expected behavior?**  
It should either log `webComponent` && `Success: <webComponent>` or log `not found` && `Error: <reason>`

Background  
I'm running NodeJs with ExpressJs as an API and webserver.  
When I try to use `findOne` on a `model`, I cannot handle a callback using a Promise.reject or a Promise.resolve.  
In the `.then(resolve, reject)` the resolve is called, even though the Promise is rejected.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**  

`node -v`: `v11.6.0`
`mongoose.version`: `5.4.20`
`MongoDB`: `3.2.2`

**Comment by vkarpov15** [comment]
Do this instead:

`WebComponent.findOne().orFail().then(component => { ... })`

In general, don't mix promises and callbacks unless you really know what you're doing. For one thing, your code as written executed the query twice: https://mongoosejs.com/docs/queries.html#queries-are-not-promises

See also docs on orFail: https://mongoosejs.com/docs/api.html#query_Query-orFail
