### ISSUE TITLE
Transaction's session isn't available in validators

### ISSUE THREAD

**Issue by mateo-gallardo** [Automattic/mongoose#7652]
**Do you want to request a *feature* or report a *bug*?**
Bug. May be an enhancement, but a necessary one.

**What is the current behavior?**
Validator functions don't have access to the session being used in a transaction.

In my case I have a reference validator that checks that the references inserted actually exist in the DB. The problems is that if I insert a document inside a transaction and then use it in a reference field, the validator tries to find it, but fails because it needs to use the session in the query.

Calling `this.$session()` inside the validator function returns `null`, so I can't use that.

**If the current behavior is a bug, please provide the steps to reproduce.**
Standalone script:
```
const mongoose = require('mongoose');

mongoose.connection.on('error', err => {
  console.log(`MongoDB connection error: ${err}`);
  process.exit(-1);
});

mongoose.connect(
  YOUR_MONGO_URI_HERE,
  {
    keepAlive: 1,
    useNewUrlParser: true,
    useCreateIndex: true
  }
);

(async () => {
  const someSchema = new mongoose.Schema(
    {
      name: String
    },
    { autoCreate: true }
  );
  const SomeModel = mongoose.model('SomeModel', someSchema);

  const someOtherSchema = new mongoose.Schema(
    {
      fieldWithReference: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'SomeModel',
        validate: {
          isAsync: true,
          validator(value, cb) {
            // Need session here
            // this.$session() returns null
            console.log(`this.$session() value: ${this.$session()}`);

            SomeModel.findOne({ _id: value })
              .session(this.$session())
              .exec((err, doc) => {
                if (doc) {
                  console.log('Success! Reference found!');
                } else {
                  console.error('Failed! No reference found!');
                }

                cb(doc);
              });
          }
        }
      }
    },
    { autoCreate: true }
  );
  const SomeOtherModel = mongoose.model('SomeOtherModel', someOtherSchema);
  let session;

  try {
    session = await mongoose.startSession();
    session.startTransaction();
    const [insertedDocument] = await SomeModel.create([{ name: 'Potato' }], { session });
    await SomeOtherModel.create([{ fieldWithReference: insertedDocument }], { session }); // Validator returns false because it can't find insertedDocument
    session.commitTransaction();
  } catch (err) {
    if (session) {
      session.abortTransaction();
    }

    console.error(err);
  }
})();
```

**What is the expected behavior?**
Either the validator function should have access to the same session that was passed down to the `.create` method (probably as a third param), or `this.$session()` should return that same session.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 10.15.1
Mongoose: 5.4.9
MongoDB: 4.0.4

I'll get started on a PR this weekend if I can.

**Edit**: Updated standalone script.

**Comment by vkarpov15** [comment]
`this.$session()` should work. If it doesn't, it might just be that it isn't getting set before validators run. Will investigate

**Comment by yinonby** [comment]
Can someone please explain how the this.$session() is supposed to work? When I'm trying to access it within the validator, I'm getting my own class member as the reference of "this", and not the schema (which is what I'm guessing the intention is).
I can't find any documentation for it as well.

**Comment by yinonby** [comment]
solved. should not use arrow functions. see https://stackoverflow.com/questions/66768458/how-to-get-mongoose-session-in-mongoose-schema-validator#66798049.
