### ISSUE TITLE
Creating a document with a null _id via findOneAndUpdate

### ISSUE THREAD

**Issue by Pmarkoalt** [Automattic/mongoose#7653]
#### Bug found
I have inadvertently found that you can create a record in mongo with _id set as null using findOneandUpdate and upsert as true. I am currently using Elastisearch and Mongoose so the reason I am pulling a record down and then doing a findOneandUpdate is due to my projects stack.

### Example
	// This is a null/undefined value
	record._id = results.hits.hits[0]._id;
      SubscriptionModel.findOneAndUpdate(
        { _id: record._id, is_active: true },
        {$set: {sentTo: record.sentTo}},
        { upsert: true, new: true },
        (error, subRecord) => {
          if (error) {
            console.log(error);
            return res.status(400).send(Boom.badRequest('invalid query', error));
          }
          return res.status(200).json({ status: 'complete' });
      });

**What is the expected behavior?**
I would expect that if null is passed into _id that the query would be kicked back to the user and create an error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
I am using Node v10.11, Mongoose v5.3.10, and Mongo v4.05

**Additional notes**
While this is a easily resolved issue on my end, I thought it was worth pointing out to your dev team.

**Comment by vkarpov15** [comment]
You can set `required: true` on `_id` as a workaround. But you're right, we should err on the side of disallowing `_id: null` by default. Will consider that for our next major release

**Comment by ashatat** [comment]
@Pmarkoalt I am wondering how did you resolve this?
the only way I could think of is to do two queries update and create?

**Comment by Pmarkoalt** [comment]
@ashatat We just had to do some manual checking within our JS logic before making our query to ensure the id was not null.

**Comment by vkarpov15** [comment]
The changes required here are:

1) Mongoose's auto `_id` should have `required: true`
2) Queries should explicitly check that `_id` is not nullish if `_id` is the `_id` property that Mongoose automatically adds to schemas

**Comment by vkarpov15** [comment]
Here's a test case for this one:

```javascript
  it('throws a cast error when upserting with a `null` _id (gh-7653)', function() {
    const Test1 = db.model('Test1', Schema({
      name: String
    }));

    const Test2 = db.model('Test2', Schema({
      _id: Number,
      name: String
    }));

    return co(function*() {
      // This operation should succeed, because `Test2` uses a custom `_id`
      yield Test2.findOneAndUpdate({ _id: null }, { name: 'test' }, { upsert: true, new: true });

      // This operation should fail with a CastError, because `Test1` uses Mongoose's default `_id` and we don't
      // want the user to be able to accidentally upsert a document with `_id = null`
      yield Test1.findOneAndUpdate({ _id: null }, { name: 'test' }, { upsert: true, new: true });

      // This operation should also fail. Be careful of the difference between `{}` and `{ _id: undefined }`
      yield Test1.findOneAndUpdate({ _id: undefined }, { name: 'test' }, { upsert: true, new: true });
    });
  });
```

The necessary changes are in `lib/cast.js`. We only need to worry about the query `filter` rather than the update portion, and only if the `upsert` option is set. The MongoDB server throws an error if you try to modify a document's `_id`, so we don't have to worry about the update.

**Comment by pate313373** [comment]
So why I need upsert, if it does not generate a new _id?
From my point of view, it should rather generate an _id.

**Comment by vkarpov15** [comment]
@pate313373 I don't understand your comment, can you please elaborate?

**Comment by pate313373** [comment]
Well from my understanding upsert true and new true allows to create a new document, if none was found, right?
I would like to pass id_: undefined as a filter and get a new document (with _id generated by the server) in return.

Basically, my point is that the server should take care of _id creation to make sure it's free of collisions.
With the current implementation however, the client must generate an _id before sending the new object to the DB.

**Comment by vkarpov15** [comment]
The client doesn't need to generate an `_id`, the MongoDB server will generate one if there isn't an `_id`. The problem here is the difference between [explicitly setting a property to `undefined` versus not setting a property at all](https://masteringjs.io/tutorials/fundamentals/undefined-check#checking-whether-object-properties-are-undefined): if you explicitly set `_id: undefined`, you'll get `_id = null`. If you don't set `_id`, you'll get an automatically generated _id.
