### ISSUE TITLE
findOneAndReplace is broken

### ISSUE THREAD

**Issue by kaitlynbrown** [Automattic/mongoose#7654]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
when an `options` argument is passed, it ends up being used as the `replacement` argument when calling the driver's `findOneAndReplace`. There doesn't seem to be any way to actually pass `options` to the driver.

**If the current behavior is a bug, please provide the steps to reproduce.**
call `findOneAndReplace` and pass in an object as the `options` argument
examine the DB to see that your document has been replaced by the `options` you passed

**What is the expected behavior?**
according to the mongodb docs, I should be able to pass the following arguments: `filter`, `replacement`, `options` (in that order)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.3.15
node 10.14
mongodb 4.x

**Comment by vkarpov15** [comment]
Please provide code samples. Converting prose to code is error prone

**Comment by kaitlynbrown** [comment]
this is the line of code that is incorrect: https://github.com/Automattic/mongoose/blob/92dd3464ed3bc695abc54b91cf28b26b7314441f/lib/query.js#L3204

`this._collection.collection.findOneAndReplace(filter, options, callback)`
should be
`this._collection.collection.findOneAndReplace(filter, replacement, options, callback)`

The way it is being called now, mongodb will treat the options object you are passing as if it is the replacement

mongodb docs for findOneAndReplace:
https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndReplace/

**Comment by cjntaylor** [comment]
This is still broken in the current release - the replacement object still isn't provided when calling the underlying mongodb method here: https://github.com/Automattic/mongoose/blob/master/lib/query.js#L3226

The options object will be passed as the replacement object, and the options are omitted. The call needs 4 parameters as referenced here:

> this is the line of code that is incorrect:
> 
> https://github.com/Automattic/mongoose/blob/92dd3464ed3bc695abc54b91cf28b26b7314441f/lib/query.js#L3204
> 
> `this._collection.collection.findOneAndReplace(filter, options, callback)`
> should be
> `this._collection.collection.findOneAndReplace(filter, replacement, options, callback)`
> 
> You'll also need to take the replacement as an argument in `model.findOneAndReplace` and forward it to `query.findOneAndReplace`
> 
> The way it is being called now, mongodb will treat the options object you are passing as if it is the replacement
> 
> mongodb docs for findOneAndReplace:
> https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndReplace/

**Comment by cjntaylor** [comment]
Thanks for fixing the function. Apologies, but there is one issue remaining - the "default" projection is not applied to the result object; the returned document returns fields where "select: false" is set in the schema.

Is there some way I should be calling the query to force this to happen? Is it expected behaviour that the "default" projection is ignored when calling this method?

Sorry to keep making requests - if I understood the internals a little bit better I'd be happy to make a pull request to fix these things. I haven't been able to grok how the "default" projection applies in other queries so far 😅

**Comment by vkarpov15** [comment]
@cjntaylor no worries, we'll look into it :+1:

**Comment by JorgeJOcampo** [comment]
Same issue with timestamp option.
![code](https://user-images.githubusercontent.com/21157995/80292272-cc59c480-872b-11ea-8ad8-c7fd9fc2637c.png)

![image](https://user-images.githubusercontent.com/21157995/80292268-c5cb4d00-872b-11ea-83b1-18fb55635fce.png)

**Comment by vkarpov15** [comment]
@JorgeJOcampo please open a new issue and follow the issue template.
