### ISSUE TITLE
Default functions, this, and findOneAndUpdate

### ISSUE THREAD

**Issue by mathpere** [Automattic/mongoose#7655]
Hello,

I'm using mongoose 5.4.20, Node.js 10.13.0.
I'm not sure if it's a bug or a missing feature and I didn't find any related issues.

When I'm running method `findOneAndUpdate`, my schema default methods are correctly executed but `this` do not refer to the document. So I can not read the other fields.

Here is a script to reproduce the behaviour based on the [documentation sample](https://mongoosejs.com/docs/defaults.html#default-functions-and-this):

```
const mongoose = require('mongoose');
const db = mongoose.createConnection(<mongo URL>, <mongo options>);

const assert = (condition, message) => {
  if (!condition)
    throw message;
};

const schema = new mongoose.Schema({
  title: String,
  released: Boolean,
  releaseDate: {
    type: Date,
    default: function () {

      console.log('Hello !');

      if (this.released) {
        return Date.now();
      }
      return null;
    }
  }
});

const Movie = db.model('Movie', schema);

(async () => {

  try {

    const movie = await Movie.findOneAndUpdate({title: 'Terminator'}, {$set: {released: true}}, {new: true, upsert: true, setDefaultsOnInsert: true});
    assert(movie.title === 'Terminator', 'Title should be equals to Terminator');
    assert(movie.released, 'Movie should be released');
    assert(movie.releaseDate !== null, 'Release date should be defined because movie is released');

  } catch (ex) {
    console.error(ex);
  }

})();
```

Log outputs are:

```
Hello !
Release date should be defined because movie is released
```

I would expect the message `Release date should be defined because movie is released` doesn't print :-)

Am I missing something?

**Comment by vkarpov15** [comment]
Right now this is expected behavior. We run setters on queries as well, and `this` refers to the query. We'll look into adding a workaround, but for now you can skip your setter by checking `if (!(this instanceof Document)) return`
