### ISSUE TITLE
[Bug] Mongoose blocks kill event by Seneca

### ISSUE THREAD

**Issue by pusaphil** [Automattic/mongoose#7659]
**Do you want to request a *feature* or report a *bug*?**  **Bug**

**What is the current behavior?**

RPC Script using Seneca and Mongoose Modules **do not shutdown even if Seneca emit 'kill' event**. While RPC Script using Seneca Module alone do shutdown on Seneca emit 'kill' event.

**If the current behavior is a bug, please provide the steps to reproduce.**

I am working with the ff packages:
mongoose v5.0.9 (but I also tried this using the latest version but same result)
seneca v3.4.3 with seneca-amqp-transport and rabbitMQ as a broker (not sure if terminology is correct)

I noticed that if i have a simple seneca listener script (RPC) with rabbitMQ connection alone, no mongoose connection, the listener script dies after the rabbitMQ dies. This is because somehow seneca emits a 'kill' signal which okay with me. I want the listener script to die if it got disconnected to rabbitMQ.

But if the seneca listener script (RPC) have rabbitMQ and mongoose connections, and the rabbitMQ dies, the listener script is still up and running. Somehow the mongoose is keeping the connection or the script up and running.

See output below:

```
INFO [2019-03-21T06:37:23.934Z] (27933 on mylaptop): Workers initialized...
^CINFO [2019-03-21T06:37:33.382Z] (27933 on mylaptop): -- Executing SIGINT listener...
INFO [2019-03-21T06:37:33.384Z] (27933 on mylaptop): Closing Database connection.
INFO [2019-03-21T06:37:33.387Z] (27933 on mylaptop): Closing Message broker.
INFO [2019-03-21T06:37:33.388Z] (27933 on mylaptop): Message broker closed.
INFO [2019-03-21T06:37:33.389Z] (27933 on mylaptop): Database connection closed.
INFO [2019-03-21T06:37:33.391Z] (27933 on mylaptop): Graceful exit done. Terminating process...
INFO [2019-03-21T06:37:33.391Z] (27933 on mylaptop): -- Executing exit listener...
INFO [2019-03-21T06:37:33.391Z] (27933 on mylaptop): Closing Database connection.
INFO [2019-03-21T06:37:33.392Z] (27933 on mylaptop): Database connection closed.
INFO [2019-03-21T06:37:33.392Z] (27933 on mylaptop): Closing Message broker.
INFO [2019-03-21T06:37:33.392Z] (27933 on mylaptop): Message broker closed.
```

As you can see, i triggered the Ctrl+C (SIGINT) because the listener script did not respond to the rabbitMQ shutdown, but you can also see that the `-- Executing exit listener...` - the exit signal by seneca - is already in the event loop of NodeJS but somehow not prioritized(?)/executed by NodeJS.

Working sample code here https://github.com/pusaphil/nodejs_seneca_mongoose_poc

**What is the expected behavior?**

RPC Script using Seneca and Mongoose Modules **should shutdown even if Seneca emit 'kill' event**. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- node 8.11.3
- mongoose v5.0.9 (but I also tried this using the latest version but same result)
- seneca v3.4.3 with seneca-amqp-transport and rabbitMQ as a broker (not sure if terminology is correct)
- mongo 4.0

**Comment by vkarpov15** [comment]
I took a closer look at this and I figured out the issue: [the `exit` event is a core Node.js event](https://nodejs.org/api/process.html#process_event_exit), it has nothing to do with seneca. Node emits that event when the event loop is empty and the process is about to exit. So there's no need to disconnect when you get an 'exit' event - there's no way you'll get an 'exit' event as long as Mongoose is connected to MongoDB.
