### ISSUE TITLE
Cannot create namespace [jobs] in multi-document transaction

### ISSUE THREAD

**Issue by nathanchan01** [Automattic/mongoose#7661]
```
let job = {title: 'ABC'};
this.mConn = await mongoose.createConnection(dbConfig.getDB());
this.mSession = await this.mConn.startSession();
      this.mSession.startTransaction({
        readConcern: { level: 'snapshot' },
        writeConcern: { w: 'majority' }
      });
await this.mConn.collection('jobs').insertOne(job, { session: this.mSession });
```
return error !

the collection [jobs] exists already!
monoose version 5.2.5

**Comment by vkarpov15** [comment]
Does the collection exist in the database you're using? How are you creating the collection?

As a workaround, you can explicitly create the collection: https://mongoosejs.com/docs/api.html#model_Model.createCollection
