### ISSUE TITLE
Connection 3 to Cluster failed

### ISSUE THREAD

**Issue by AdeelMughal** [Automattic/mongoose#7662]
Hi ! I am new with MongoDB. Please tell me how can i fix it ? Whenever i run node server this error pops up in terminal.

{ MongoNetworkError: connection 3 to mycluster-shard-00-00-tmlh2.mongodb.net:27017 closed
    at TLSSocket.<anonymous> (/Users/max/ReactGit/ReactGit/Auth/Server/node_modules/mongodb-core/lib/connection/connection.js:276:9)
    at Object.onceWrapper (events.js:285:13)
    at TLSSocket.emit (events.js:202:15)
    at _handle.close (net.js:611:12)
    at TCP.done (_tls_wrap.js:412:7)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

My Code : 
const mongoose = require('mongoose');

mongoose.Promise = global.Promise;

mongoose
.connect(
    'mongodb+srv://AuthUser:password@mycluster-tmlh2.mongodb.net/test?retryWrites=true'
    ,{ useNewUrlParser: true}
)
.then(() => {
    console.log('DB connected');
}).catch((err) => {
    console.log(err)
});

module.exports = mongoose;

**Comment by vkarpov15** [comment]
Sounds like you're connecting to an instance that doesn't accept ssl connections or vice versa. Are you using Atlas? If so, can you clarify what your Atlas setup is?
