### ISSUE TITLE
memory leak issue with mongoose,aerospike,pm2,node js.

### ISSUE THREAD

**Issue by anujnit2007** [Automattic/mongoose#7667]
We are facing pm2 restart due to  memory exceed issue on our prod environment .
Tool versions are as below
node-v8.11.4
pm2 - 3.4.0
mongoose-5.0.2
aerospike npm -^2.7.2
aerospike server version-3.12.0
We are scheduling few jobs using agenda to send broadcast to large number of users.
We are maintaining the scheduler using pm2 but pm2 memory increase 400-600 MB daily(pm2 list).
As we have kept max memory 4GB so pm2 restarts in every 5-6 days.
I have tried to replicate the issue on my local and tried to send the message to 4M users.
When I enable aerospike in my local , there is 3-4 MB difference in heap dump(before and after) and in difference I can see there are 6 tcpwrap objects each of 500kb.This difference is not there once I have run the same job with disabling the aerospike. Can anyone help us to rectify this memory issue and guide me what other steps we can try to remove this issue.

**Comment by vkarpov15** [comment]
Unfortunately I can't even begin to provide any meaningful insight without code samples. Memory leaks are hard to track down even if you have access to the codebase, without any code samples there's no way to make meaningful progress.
