### ISSUE TITLE
Feature Request - make ref callable

### ISSUE THREAD

**Issue by reduxdj** [Automattic/mongoose#7669]
Why can't the ref property be callable? It would make creating ref model fields work with virtuals better and support dynamic type assignment?

For example: 
```
const schema = new mongoose.Schema({
  populatedField: {
    type: mongoose.Schema.Types.ObjectId,
    ref: (doc) => doc.productType === 'CANDY' ?   'Candy' : 'Vegetable'
  }
});
```

**Comment by vkarpov15** [comment]
You can specify ref as a function for [populate virtuals](https://mongoosejs.com/docs/populate.html#populate-virtuals), but it doesn't look like it works for conventional populate yet. Will add in a future release.
