### ISSUE TITLE
4.x to 5.x migration - find and then save of subdocument don't work with no err

### ISSUE THREAD

**Issue by kobiBarac** [Automattic/mongoose#7670]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Finding a document (which was created in Mongoose 4), assigning a new value to one of its nested document ("dreamJob" field below) - which contain arrays, then calling "Save()" - completed successfully but actually overwrite the nested documents arrays.

**If the current behavior is a bug, please provide the steps to reproduce.**

This code used to work in Mongoose 4.13.14
```
CandidateInfo.findOne({email: email}, function (err, candidate) {
// candidate found
        candidate.dreamJob = dreamJob;
        return candidate.save(function (err) {
            if (err) {
                return callback(err);
            } else {
                return callback(null, candidate);
            }
        });
```

Also getting - (node:12586) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

**What is the expected behavior?**
The candidate document would get updated
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS:10.0.14
Mongoose: 5.4.20
MongoDB: 3.6

**Comment by vkarpov15** [comment]
Can you please show your schema and show what your `dreamJob` object looks like?

**Comment by yair5124302** [comment]
I've encountered a similar issue.
After updating mongoose to 5.4.19, updating nested schema in a document returned by mongoose query is not working.

This is my use-case:

```
let schemaB = new Schema({
  _id: { auto: false },
  fieldA: String,
  fieldB: Number
}

let schemaA = new Schema({
  name: String,
  bval: schameB
}

...

// load document of type schemaA
let doc = await ModelA.findById(id).exec();
// --------------------------------
doc.bval = {fieldA: 'a', fieldB: 'b'};
// --------------------------------
await doc.save();
```

If I replace the marked line with Object.assign the object is updated correctly:

`Object.assign(doc.bval, {fieldA: 'a', fieldB: 'b'});
`

Have this functionality changed?

**Comment by michaelwclark** [comment]
We have incountered similar issues with mongoose   "version": "5.5.0".

Whenever we tried to `findByIdAndUpdate` with subdocs we got some very odd behavior. It would seem to update every other call.. See the video for an example via our GraphQL layer (we ruled out that as the culperate, but will illustrate the problem)

[MAGIC.mov.zip](https://github.com/Automattic/mongoose/files/3068864/MAGIC.mov.zip)

Under the covers of our graphql layer the update simply did a:

```   
   ...findById(...)...
   doc.set(recordData);
   yield doc.save();
```

we also tried to manually test this with the following code and got the same unexpected behavior (despite bypassing our GraphQL layers of abstraction and interacting with mongoose directly, thus confirming it's an issue in mongoose.)

```
async function testUpdate(){
  const testAddress = { address_1: "testAddress", address_2: "testAddress2"}
  // const updated = await AgentMVP.findByIdAndUpdate({_id: "5cae60ba1be950b4141ada28", address: testAddress}) // doesnt work
  const updated = await AgentMVP.update({_id: "5cae60ba1be950b4141ada28"}, {$set: {address: testAddress}}) // works
  return updated
}
testUpdate().then(x=>console.log(x))
```


Our Schema:

```

const AgentSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true
    },
    first_name: String,
    last_name: String,
    account_id: { type: ObjectId, ref: 'Account', required: true },
    address: {
      type: new mongoose.Schema({
        address_1: String,
        address_2: String,
        city: String,
        zip_code: String,
        state: String
      })
    },
    office_phone: String,
    mobile_phone: String,
  },
  {
    strict: true,
    collection: 'agents_mvp_v2'
  }
)
```

**Comment by vkarpov15** [comment]
@michaelwclark shouldn't `await AgentMVP.findByIdAndUpdate({_id: "5cae60ba1be950b4141ada28", address: testAddress})` be `await AgentMVP.findByIdAndUpdate({_id: "5cae60ba1be950b4141ada28"}, {address: testAddress})` ? Looks like you're just passing incorrect parameters to `findByIdAndUpdate()`...

**Comment by vkarpov15** [comment]
@yair5124302 looks like you're running into #7660, etc. Please upgrade to 5.5.1

**Comment by michaelwclark** [comment]
> @michaelwclark shouldn't `await AgentMVP.findByIdAndUpdate({_id: "5cae60ba1be950b4141ada28", address: testAddress})` be `await AgentMVP.findByIdAndUpdate({_id: "5cae60ba1be950b4141ada28"}, {address: testAddress})` ? Looks like you're just passing incorrect parameters to `findByIdAndUpdate()`...

🤦‍♂️  thanks... lol
