### ISSUE TITLE
Immutable properties

### ISSUE THREAD

**Issue by hugree** [Automattic/mongoose#7671]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
There's no ability to tell what fields have changed if the upsert is called as the findOneAndUpdate executes. 

**What is the expected behavior?**
Added ways to check what fields have changed within a schema. Some immutability options would be nice too.

I know people have asked for this a lot. Some answers point to some pre/post hook solutions that work only for the standard save method and not the findOneAndUpdate. Others who want immutability use some 3rd party plugins, but from my investigation having those plugins and doing toObject transformations do not get along.

What's the best way of doing "let's make sure nobody changes this or that field" ever with mongoose?

**Comment by vkarpov15** [comment]
There's no built-in way, but we can add support for this in the future. Can you point me to some plugins you've looked at for this case?

**Comment by vkarpov15** [comment]
There's no good way that I know of to tell what changed in a `findOneAndUpdate()` if you use `new: true`.
