### ISSUE TITLE
MongoError: user is not allowed to do action [find]

### ISSUE THREAD

**Issue by orwell1984** [Automattic/mongoose#7673]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`MongoError: user is not allowed to do action [find]` when looking up entries in the Atlas mongodb database.
**If the current behavior is a bug, please provide the steps to reproduce.**

Using the following code https://github.com/phylogeny-explorer/explorer/blob/master/common/databases/factory.js

**What is the expected behavior?**
Working connection

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
npm -> 6.7.0
node -> v11.10.1
mongoose -> 5.3.12

**Comment by orwell1984** [comment]
ping @vkarpov15

**Comment by orwell1984** [comment]
Hi guys, sorry for nagging but this is really hitting us hard. Please help.

**Comment by js-kyle** [comment]
@orwell1984 is this something you experience intermittently?

**Comment by vkarpov15** [comment]
Not sure how I missed this one. What roles does the user you're authenticated as have? Does the user have read permissions for the database and collection in question? Some further reading:

https://docs.mongodb.com/manual/reference/built-in-roles/

**Comment by MauryaAmardeep** [comment]
user is not allowed to do action [createCollection] on [StudentDB.students] how to solve this error
