### ISSUE TITLE
$geoNear aggregation not working

### ISSUE THREAD

**Issue by jonasschmedtmann** [Automattic/mongoose#7674]
**Do you want to request a *feature* or report a *bug*?**
Bug 🐛

**What is the current behavior?**
I'm trying to use a geospatial aggregation. The code below works just fine in the MongoDB Compass app, but with mongoose, I get the following error: `"$geoNear is only valid as the first stage in a pipeline."`.

But, as seen in the code, `$geoNear` is in fact the first stage. I tried removing the `$project` phase and many other things. Again, it works perfectly in Compass, which is why I suspect it's an issue with mongoose.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
  const distances = await Tour.aggregate([
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [-118.09, 37.82]
        },
        distanceField: 'distance',
        distanceMultiplier: 0.001
      }
    },
    {
      $project: {
        distance: 1,
        name: 1
      }
    }
  ]);
```

**What is the expected behavior?**
A `distance` field should be added to each document (works in Compass app)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v10.11.0
MongoDB: 4.0.6 Enterprise
Mongoose: 5.4.20

**Comment by vkarpov15** [comment]
Is `Tour` a discriminator? Can you show me the schema for `Tour` and how it is declared?

**Comment by jonasschmedtmann** [comment]
Thank you for replying, I actually just solved it. I had this piece of code in my model declaration file causing the error:

```javascript
tourSchema.pre('aggregate', function(next) {
  this.pipeline().unshift({ $match: { secretTour: false } });
  next();
});
```
