### ISSUE TITLE
There is no way to use a cursor on a nested array of objects

### ISSUE THREAD

**Issue by jakeleventhal** [Automattic/mongoose#7675]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If a model has an attribute that is an array of `mongoose.Schema.Types.ObjectId`, there is no good way to use a cursor on these objects after populating them. (For example a `User` has an array of `Friends`)

**What is the expected behavior?**
There should be a way to do use a cursor on an attributes nested objects.
For example, if a User has thousands of friends and you dont want to load all of the object ids into memory, there should be a way to use a cursor on the User's populated Friends so that each one can have some sort of function done one at a time.
Something like this:
```javascript
User.find({ _id: userID }).
    .cursor('Friends')
    .eachAsync(async (friend) => {
           // Do something with each friend
    });
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 11.7.0
Mongoose: 5.4.20
MongoDB: 4.0.0

**Comment by vkarpov15** [comment]
If a `User` document can have a `friends` array with thousands of elements, then you're better off having a separate mapping collection `UserFriends`. In general, if a document is getting too big to fit in memory, then denormalization is doing more harm than good. The MongoDB server API doesn't support streaming individual properties of a document, so Mongoose has no good way to do this.

**Comment by jakeleventhal** [comment]
This is an excellent idea, thanks @vkarpov15

**Comment by jakeleventhal** [comment]
If there is a `UserFriends` collection, then don't you run into the same problem?
```javascript
// User schema
const User = mongoose.model(
  'User',
  new mongoose.Schema({
    UserFriends:
      {
        default: [],
        ref: 'Friend',
        type: mongoose.Schema.Types.ObjectId
      }
  })
);

// UserFriends schema
const UserFriends = mongoose.model(
  'UserFriends',
  new mongoose.Schema({
    Friends: [
      {
        default: [],
        ref: 'User',
        type: mongoose.Schema.Types.ObjectId
      }
    ]
  })
);
```

If you tried to use a cursor on the `UserFriends`' `Friends` attribute, you run into the same problem as before?

**Comment by vkarpov15** [comment]
@jakeleventhal `UserFriends` would contain 1 document for each pair of users that are friends, so there would be a lot of documents but each doc would only contain references to exactly 2 users.

```javascript
const userFriendsSchema = new Schema({
  users: {
    type: [mongoose.ObjectId],
    validate: v => v == null || v.length === 2
  }
});
```
