### ISSUE TITLE
Authentication fail error

### ISSUE THREAD

**Issue by vickOnRails** [Automattic/mongoose#7677]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**

I'm working with mongoose 5.4.17 (Latest as of now). Everything works fine when I use it with MongoDB locally (localhost/db) but it's time to host my app on cPanel & use Mongo Atlas. I've gone through all the steps of generating a user, and I'm now trying to connect. but it gives this error.

`{ MongoError: authentication fail
    at C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\topologies\replset.js:1458:15
    at C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\connection\pool.js:869:7
    at C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\connection\pool.js:845:20
    at finish (C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\auth\scram.js:233:16)
    at handleEnd (C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\auth\scram.js:243:7)
    at C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\auth\scram.js:352:15
    at C:\Users\Victor\Desktop\projects\creativeComps\lensees_app\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errors:
   [ { name: 'cluster0-shard-00-02-nxamh.mongodb.net:27017',
       err: [Object] },
     { name: 'cluster0-shard-00-01-nxamh.mongodb.net:27017',
       err: [Object] },
     { name: 'cluster0-shard-00-00-nxamh.mongodb.net:27017',
       err: [Object] } ],
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }`

**If the current behavior is a bug, please provide the steps to reproduce.**

` let mongoose = require("mongoose"),
  connection = mongoose.connect(
    "mongodb+srv://<<username>>:<<password>>@cluster0-nxamh.mongodb.net/test?retryWrites=true",
    { useNewUrlParser: true },
    (err, success) => {
      if (err) console.log(err);
      if (success) console.log(success);
    }
  );

module.exports = mongoose; `

**What is the expected behavior?**
Mongoose.connect() is supposed to connect me to the cluster created on Mongo Atlas

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**

"mongoose": "^5.4.17",
"node": v8.12.0

**Comment by vickOnRails** [comment]
**Fixing my own issue.**
After days of trying to solve this issue, I was advised to change my password. That did it for me. I suspect the presence of special characters in the previous password was causing the authentication error.

**Comment by vkarpov15** [comment]
For future reference, you should `encodeURIComponent()` your password if it contains special characters.

**Comment by vickOnRails** [comment]
Yea that should work too. Thanks
