### ISSUE TITLE
Possible memory leak when deleting models

### ISSUE THREAD

**Issue by MarcoCanalcar** [Automattic/mongoose#7682]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**

If you delete a mongoose Model from mongoose.models, mongoose.connections.models and mongoose.modelSchemas, the model remains in memory and the memory usage of the process grows uncontrollably
**If the current behavior is a bug, please provide the steps to reproduce.**

Run this gist:
https://gist.github.com/MarcoCanalcar/a978e4acd8effb7910f71c734c890fa6
**What is the expected behavior?**

The memory usage of the process should be stable
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v11.12.0
Mongoose: 5.4.21
MongoDB: Not relevant, we are able to reproduce the bug without even connecting to mongodb

Note: We got the instructions for deleting a model from #2874

**Comment by vkarpov15** [comment]
Found the issue, fix will be in 5.5.2.

Also, I'd recommend using [`connection#deleteModel()`](https://mongoosejs.com/docs/api.html#connection_Connection-deleteModel) instead of deleting from `models`, `modelSchemas`, etc. yourself.
