### ISSUE TITLE
how to Sorting Null values last in results

### ISSUE THREAD

**Issue by ystyle** [Automattic/mongoose#7683]
**Do you want to request a *feature* or report a *bug*?**
help

**What is the current behavior?**
I want to Sorting Null values last in results

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Sorting Null values last in results

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
MongoDB sorts based on the [order of types in bson spec](http://bsonspec.org/spec.html), so `null` should come after any number or string. Can you provide more info on what you're trying to sort null against?

**Comment by ystyle** [comment]
```json
[
  {"id": 1, "name": "1"},
  {"id": 3, "name": "3"},
  {"id": 2, "name": "2"},
  {"name": null},
]
```

order by id asc , then `name = null` will be first

**Comment by vkarpov15** [comment]
So I took a closer look and this is [how the MongoDB server sorts values](https://docs.mongodb.com/manual/reference/method/cursor.sort/#ascending-descending-sort). Mongoose can't do anything about that unfortunately. As a workaround, you would have to execute two separate queries with `{ name: { $type: 'string' } }` and `{ name: { $not: { $type: 'string' } } }`
