### ISSUE TITLE
Indexes not being created for all unique fields in schema

### ISSUE THREAD

**Issue by chaeron** [Automattic/mongoose#7694]
Mongoose v5.5.0
MongoDB  v4.0.8 Community
Node v10.15.3

When I do something like this:

 ```
var testSchema = new Schema({
    _id:            mongoose.Schema.Types.ObjectId,
    name:        { type: String, unique: true },
    email:        { type: String, unique: true },
    etc....
  });

```
AutoIndex is on by default.  Mongoose only creates indexes for _id and name but not for email.

If I remove the unique tags, and add the following:

```
testSchema.index( { name: 1 }, { unique: true } );
testSchema.index( { email: 1 }, { unique: true } );
```

Then both indexes for name and email are created.

**Comment by jblevins1991** [comment]
I am having an identical issue. My databases are hosted on MLab and I have a model that looks like this.

```
const mongoose = require('mongoose');
const ObjectId = mongoose.Schema.Types.ObjectId;

const Project = mongoose.Schema({
    id: { type: ObjectId },
    name: { type: 'String', required: true, unique: true },
    client: { type: ObjectId, ref: 'Client' },
    paymentStatus: { type: ['DEVELOPMENT', 'DUE', 'PAID'], default: 'DEVELOPMENT' }
});

module.exports = mongoose.model('Project', Project);
```

Yet I can have multiple records with identical names fields. I am really confused on what might be happening. What is the point of even having the unique property on a model's field if it is never enforced?

**Comment by chaeron** [comment]
> I am having an identical issue. My databases are hosted on MLab and I have a model that looks like this.

Not really the same problem, jblevins1991.....my issue was having two+ indexed fields only the index for the first one is created by Mongoose.  You are only using one indexed field in your example.

There are some complexities with indexes.  If there is already data in the collection with replicated values for your indexed field, then the index won't be created.

**Comment by vkarpov15** [comment]
@chaeron are you using mlab as well?

**Comment by chaeron** [comment]
> @chaeron are you using mlab as well?

Nope....local mongoDB database here (for now....will go Atlas hosted eventually)

**Comment by jblevins1991** [comment]
I figured out some of the behavior. One of my older projects used MLab and the database documents were created on a need-to-know bases, as in the documents don't exist until an endpoint has told them to. My newer project, for some reason or another, creates all documents when I start the server up.

I have not had a lot of time to look through changelogs or really research the problem. All I know is, I changed a schema definition after the server started (and created the schema docs) and then I expected the schema doc to be created when I tested my endpoint. The schema definition on mlab and my local express server did not match up at all.

**Comment by vkarpov15** [comment]
@chaeron the below script successfully creates two indexes. Can you please modify the below example to demonstrate your issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7694`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const testSchema = new Schema({
    _id:            mongoose.Schema.Types.ObjectId,
    name:        { type: String, unique: true },
    email:        { type: String, unique: true }
  });
  const Model = mongoose.model('Test', testSchema);

  await Model.init();
  console.log(await Model.listIndexes());
}
```
