### ISSUE TITLE
Given transaction number [n] does not match any in-progress transaction

### ISSUE THREAD

**Issue by cyrilchapon** [Automattic/mongoose#7697]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I tried to make a function that run queries inside a transaction, and auto-commit or rollback the transaction. Pretty similar to [Sequelize managed transactions](http://docs.sequelizejs.com/manual/transactions.html#managed-transaction--auto-callback-)

I discovered that transactions are not ok in a single mongod instance, so I started a replica-set with 

```shell
run-rs --dbpath /Users/cyril/data/mongo-run-rs
```

```js
// Wrote that function
const mongoTransaction = async (mongoConnection, queries) => {
  return mongoConnection.startSession()
    .then(session => {
      session.startTransaction()

      return Promise.resolve()
        .then(() => queries(session))
        .then(() => {
          session.commitTransaction()
        })
        .catch((err) => {
          session.abortTransaction()
          throw err
        })
        .finally(() => session.endSession())
    })
}

const mongooseConfig = {
  useNewUrlParser: true,
  autoIndex: false
}
// Instanciated some mongoose
const { Mongoose } = require('mongoose')
const mongoose = new Mongoose()

return Promise.resolve()
  // Connected it
  .then(() => mongoose.connect(process.env['MONGO_URI'], mongooseConfig))
  // Ran some DDL query inside the session
  .then(() => {
    return mongoTransaction(mongoose, s => {
      return mongoose.collection('associationTokens')
        .createIndex({
          value: 1
        }, {
          unique: false,
          name: 'valueIndex',
          session: s
        })
    })
  })

```

I'm getting

> MongoError: Given transaction number 1 does not match any in-progress transactions.

**What is the expected behavior?**

I'd expect it to work 😅

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
> mongoose.version
5.4.19

$ node -v
v11.10.1

$ run-rs
Running '/Users/cyril/.nvm/versions/node/v11.10.1/lib/node_modules/run-rs/4.0.6/mongod' [ 27017, 27018, 27019 ]
Starting replica set...
Started replica set on "mongodb://localhost:27017,localhost:27018,localhost:27019?replicaSet=rs"
```

And using `MONGO_URI=mongodb://localhost:27017,localhost:27018,localhost:27019?replicaSet=rs` as environment variable

**Comment by vkarpov15** [comment]
I found one minor issue:

```javascript
return Promise.resolve()
        .then(() => queries(session))
        .then(() => {
          session.commitTransaction()
        })
```

Should be:

```javascript
return Promise.resolve()
        .then(() => queries(session))
        .then(() => session.commitTransaction())
```

Because `commitTransaction()` returns a promise. But otherwise, for the life of me I can't get `createIndex()` to work in a transaction. The below script gives me `Cannot write to system collection test.system.indexes within a transaction.`:

```javascript
const mongodb = require('mongodb');

run().catch(error => console.log(error));

async function run() {
  const client = await mongodb.MongoClient.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs', {
    useNewUrlParser: true
  });
  const db = client.db();

  await db.dropDatabase();
  await db.createCollection('Test');

  const session = await client.startSession();
  let success = false;
  for (let i = 0; i < 10; ++i) {
    try {
      session.startTransaction();
      await db.collection('Test').insertOne({ value: 'foo' }, { session });
      await db.collection('Test').createIndex({ value: 1 }, { session });
      await session.commitTransaction();
      success = true;
      break;
    } catch (err) {
      await session.abortTransaction();
      if (err.errorLabels != null && err.errorLabels.includes('TransientTransactionError')) { 
        console.log('Retry...');
        await new Promise(resolve => setTimeout(resolve, 100));
        continue;
      }
      throw err;
    }
  }

  if (!success) { 
    throw new Error('Failed!')
  }
}
```

As a workaround, I'd recommend thinking about whether you truly want to create an index using a transaction. I might be missing something but that doesn't seem particularly useful...

**Comment by vkarpov15** [comment]
I opened up an issue on MongoDB's JIRA: https://jira.mongodb.org/browse/NODE-1948

**Comment by vkarpov15** [comment]
So as it turns out, [you can't create an index in a transaction](https://docs.mongodb.com/manual/core/transactions/#restricted-operations). The error message is unfortunately not helpful, we'll see if MongoDB can improve that. I'll close this issue for now.

**Comment by cyrilchapon** [comment]
Hey @vkarpov15 

> As a workaround, I'd recommend thinking about whether you truly want to create an index using a transaction. I might be missing something but that doesn't seem particularly useful...

Well, if like me you're a rough guy, and you have "migrations" involving both Sequelize and Mongoose for "DDL" upgrades, and wishes to upgrade **both** Mongo and Postgre DDL if success, or **none** if one of them fail 🤓😀

**Comment by vkarpov15** [comment]
In my mind, a migration is something that modifies data, not metadata like indexes. Unfortunately, Mongoose can't support creating an index in a transaction without help from the MongoDB server, so you'd have to keep a list of indexes that you've created and delete them if your migration fails. My apologies for the inconvenience.
