### ISSUE TITLE
TypeError: Cannot read property 'now' of undefined - Function._setTimestampsOnUpdate

### ISSUE THREAD

**Issue by kriegerlukas** [Automattic/mongoose#7698]
After deploying our service, we had a lot of errors like in the headline.

`
TypeError: Cannot read property 'now' of undefined
at Function._setTimestampsOnUpdate (/app/node_modules/mongoose/lib/schema.js:1059:33)
`

For a quick fix we set the version of mongoose back to `5.4.22`

On a local machine with a fresh `npm install`, i did not get the errors.
Local node version: v10.9.0
Remote node version: v10.15.3

**Comment by nick13jaremek** [comment]
Same thing happened to us today.

 @kriegerlukas thank you very much for providing the info and the `mongoose` version to avoid the fix.

**Comment by ilkkaparssinen** [comment]
Same here. In our case the actual cause of error seems to be npm library mongoose_delete which overrides mongoose methods for soft delete. For example findOneAndUpdate method fails.  If line "UserSchema.plugin(mongoose_delete, { overrideMethods: true });" is commented - then there is no errors in following example. 

`let mongoose = require('mongoose');
let mongoose_delete = require('mongoose-delete');

let UserSchema = new mongoose.Schema({
    name: "String"
},{ timestamps: { updatedAt: 'updated_at', createdAt: 'created_at' }});

UserSchema.plugin(mongoose_delete, { overrideMethods: true }); // Soft delete support
let testUser = mongoose.model('TestUser', UserSchema);
runTest();    

async function runTest() {
    try {
        await mongoose.connect("mongodb://localhost:27017");
        let user = await (new testUser({name: "Smith"})).save();
        await user.save();
        await testUser.findOneAndUpdate({_id: user._id},  {name: "xx"});
        console.log("No errors");
        process.exit(0);
    } catch (err) {
        console.log("Test failed",err);
    }
}`

**Comment by mattwills8** [comment]
Same error here:

`TypeError: Cannot read property 'now' of undefined -- at Function._setTimestampsOnUpdate (/home/nowuser/src/node_modules/mongoose/lib/schema.js:1059:33)`
