### ISSUE TITLE
TypeError: cursor.each is not a function

### ISSUE THREAD

**Issue by Tom-3000** [Automattic/mongoose#7699]
I installed the latest mongoose and follow the documented example in https://mongoosejs.com/docs/api.html#aggregate_Aggregate-cursor

var cursor = Model.aggregate(..).cursor({ batchSize: 1000 }).exec();
cursor.each(function(error, doc) {
  // use doc
});

It doesn't work and reports 'TypeError: cursor.each is not a function'
It tried cursor.eachAsync method and it works.

Is the document wrong?

**Comment by vkarpov15** [comment]
Docs are incorrect, there's no each() function for query cursors. We'll fix the docs, but that would be a good function to add as well
