### ISSUE TITLE
Expires keyword gets ignored if it's greater than 6 days

### ISSUE THREAD

**Issue by jz222** [Automattic/mongoose#7703]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I create a new collection with the model shown below, the index won't have the expireAfterSeconds key. I tried to use expireAfterSeconds instead of expires in model, but I get the same results. The index only contains the expireAfterSeconds key, if I define a timeframe smaller than 7 days in the model. I, of course, dropped the entire collection before my various attempts. However, if I execute `db.integrationcounts.ensureIndex({ createdAt: 1 }, { expireAfterSeconds: 6048000 })`, the index looks as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
I used the following model to create the collection.

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const IntegrationCountSchema = new Schema({
  integration: {
    type: Schema.Types.ObjectId,
    ref: 'integration'
  }
}, { timestamps: true });

// Everything below 7d works
IntegrationCountSchema.index({ createdAt: 1 }, { expires: '7d' });

const modelClass = mongoose.model('integrationCount', IntegrationCountSchema);

module.exports = modelClass;
```

**What is the expected behavior?**
It should create an index with an expireAfterSeconds key, which is greater than 7 days.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 11.6.0
Mongoose: 5.5.0
MongoDB: 4.0.8 at Atlas

Thank you for your help.

**Comment by vkarpov15** [comment]
The below script works fine for me, prints 2 indexes. Can you modify the below script to demonstrate your issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7703`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const IntegrationCountSchema = new Schema({
    integration: {
      type: Schema.Types.ObjectId,
      ref: 'integration'
    }
  }, { timestamps: true });

  // Everything below 7d works
  IntegrationCountSchema.index({ createdAt: 1 }, { expires: '7d' });

  const modelClass = mongoose.model('integrationCount', IntegrationCountSchema);

  await modelClass.init();

  console.log(await modelClass.listIndexes());
}
```

Output:

```
$ node gh-7703.js 
(node:20136) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: integrationcounts.ensureIndex({ createdAt: 1 }, { expireAfterSeconds: 604800, background: true })
(node:20136) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: integrationcounts.listIndexes()
[ { v: 2,
    key: { _id: 1 },
    name: '_id_',
    ns: 'gh7703.integrationcounts' },
  { v: 2,
    key: { createdAt: 1 },
    name: 'createdAt_1',
    ns: 'gh7703.integrationcounts',
    expireAfterSeconds: 604800,
    background: true } ]
done
^C
$ 
```

**Comment by Martii** [comment]
@vkarpov15 

Sorry to dig this up but this seems to be the nearest relation. 

Is there a numerical cap on the index `expireAfterSeconds`? 

Everything I seem to read, example wise, implies it's `7d` or under for the TTL maximum and I can't find any citation in searches to this limitation. I'm shooting for '30d' but doesn't appear to last that long. Thanks for the relook.

**Comment by vkarpov15** [comment]
@Martii AFAIK there is no limit on `expireAfterSeconds`. What does your schema definition look like?

**Comment by Martii** [comment]
@vkarpov15 

See [OpenUserJS/OpenUserJS.org/blob/`9afd03b`/models/sync.js#L21](https://github.com/OpenUserJS/OpenUserJS.org/blob/9afd03bf8755221caef7c9c3120c539c28b978bd/models/sync.js#L21)

Also:

Current *node* deps at [OpenUserJS/OpenUserJS.org/blob/`9afd03b`/package.json#L41-L42](https://github.com/OpenUserJS/OpenUserJS.org/blob/9afd03bf8755221caef7c9c3120c539c28b978bd/package.json#L41-L42)

``` shell
$ mongo --version
MongoDB shell version v4.4.0
Build Info: {
    "version": "4.4.0",
    "gitVersion": "563487e100c4215e2dce98d0af2a6a5a2d67c5cf",
    "openSSLVersion": "OpenSSL 1.1.1d  10 Sep 2019",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "debian10",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```

and 


``` js
> db.syncs.getIndexes();
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_"
        },
        {
                "v" : 2,
                "key" : {
                        "created" : 1
                },
                "name" : "created_1",
                "expireAfterSeconds" : 604800,
                "background" : true
        }
]
```

Tomorrow will be the 7th day *(604800 seconds)* for [my last sync with GH](https://github.com/Martii/UserScripts/commit/dfa3ad0370082a2a9e1d211cd24374e308bd37d0) from OUJS... so I'll know for sure if my rough theory is correct here for the current implementation but all of the ones I did a few days before are already gone... so are anyone elses account that I've observed as the Admin over there for the last 7ish days. :\


Thanks for the reponse. :)

**Comment by Martii** [comment]
@vkarpov15

Okay so it's been a little over `7d` and the document is definitely gone from the DB.

Here is the screen shot I took right after I posted the [above comment](https://github.com/Automattic/mongoose/issues/7703#issuecomment-684213566) *(and a few EDITs to fill in some more info)*:

<a href="https://user-images.githubusercontent.com/114709/91948533-1d229080-ecbd-11ea-903c-cd3e5086655c.jpg" alt="Syncs left for self  20200831_232452" title="Click to enlarge... Syncs left for self  20200831_232452"><img src="https://user-images.githubusercontent.com/114709/91948533-1d229080-ecbd-11ea-903c-cd3e5086655c.jpg" width="82" height="74" /></a>

... and here is the one taken a few moments ago:

<a href="https://user-images.githubusercontent.com/114709/91950529-a4700400-ecbd-11ea-8cd8-9d53d4098bfa.jpg" alt="Syncs left for self  20200902_013235" title="Click to enlarge... Syncs left for self  20200902_013235"><img src="https://user-images.githubusercontent.com/114709/91950529-a4700400-ecbd-11ea-8cd8-9d53d4098bfa.jpg" width="82" height="74" /></a>

So my theory panned out with a confirmation. So I guess my next possibe conclusion would be the title of this issue... "Expires keyword gets ignored if it's greater than 6 days"... albeit technically 7 days for our projects test. 

My next question is why is it doing this on a `7d` period when the [line here](https://github.com/OpenUserJS/OpenUserJS.org/blob/9afd03bf8755221caef7c9c3120c539c28b978bd/models/sync.js#L21) has always seen `30d` *(calculated in seconds manually and confirmed at least 3 times now)* on production? :\

Thanks for any feedback which is highly appreciated.

**Comment by vkarpov15** [comment]
@Martii it might be that your index build is failing for some reason. I'll double check and see how Mongoose handles changing the expiration of a TTL index.

**Comment by vkarpov15** [comment]
It appears like, unless you do `mongoose.set('useCreateIndex', true)`, setting a different `expireAfterSeconds` doesn't error out. You should either drop the conflicting index, or use `syncIndexes()`: https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes

**Comment by Martii** [comment]
> It appears like, unless you do `mongoose.set('useCreateIndex', true)`, setting a different expireAfterSeconds doesn't error out.

We do use that option at [OpenUserJS/OpenUserJS.org/blob/`491699c`/app.js#L77](https://github.com/OpenUserJS/OpenUserJS.org/blob/491699cb694ffa5d7e7fbf502bfb0464c4f071c1/app.js#L77) on pro *(and a [little further down](https://github.com/OpenUserJS/OpenUserJS.org/blob/491699cb694ffa5d7e7fbf502bfb0464c4f071c1/app.js#L87) from that on dev)*.

So what do you mean by ~it should be erroring out?

> You should either drop the conflicting index...

Not sure we had one... but did drop the `7d` equivalent index that was created by *mongoose* directly in `mongo` and when the app was restarted it was recreated with the correct value of the equivalent of `30d`. Is that what you mean?

> ... or use `syncIndexes()`

We currently only have one model that utilizes that [here](https://github.com/OpenUserJS/OpenUserJS.org/blob/491699cb694ffa5d7e7fbf502bfb0464c4f071c1/models/script.js#L83-L89). Guess I could just add it to our stock model creation especially if the `expires` keyword in *mongoose* is going to need this to sync with the backend properly.

> https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes

Will give that a good read in a bit. Thanks. :)

**Comment by vkarpov15** [comment]
@Martii yes, Mongoose's `Model.init()` should error if the index build fails, which is what should happen if MongoDB can't create an index because there's already an existing incompatible index.

"Not sure we had one... but did drop the 7d equivalent index that was created by mongoose directly in mongo and when the app was restarted it was recreated with the correct value of the equivalent of 30d. Is that what you mean?" Yes that is what I mean. Right now, you need to explicitly drop the old 7d index before Mongoose can create the 30d index. You would need to do that manually, or `syncIndexes()` can do that for you.
