### ISSUE TITLE
Silently fail or allow fail for population when invalid Mongo ID

### ISSUE THREAD

**Issue by Hyperblaster** [Automattic/mongoose#7706]
Hi there,

I want to request a feature, that for us would be hugely helpful.
Let's say i have a  schema like this
```
var Contact = new Schema({
   data: {
        type: Schema.Types.Mixed
    },
})
```

And some documents like this:
```
[
{
data:{
    pets:"5aa70fdf93b42f2c57db2a31"
  }
},
{
data:{
    pets:{
     "_id":"5aa70fdf93b42f2c57db2a31",
     "title":"Dog"
    }
  }
},
{
data:{
    pets:"5aa70fdf93b42f2c57db2a31"
  }
},
]
```

Currently if i request to populate something like this
```
Contact.find({
gender:'male',
}).populate('data.pets')
.exec()
```

It will result in an error that breaks the entire query
```
kind: "ObjectId"
message: "Cast to ObjectId failed for value "pets" at path "_id" for model "title""
name: "CastError"
path: "_id"
stringValue: ""contact""
value: "contact"

```

What i would like to request is that we add in that before trying to Cast as an Object ID we do the following, or at least have the ability to do the following

1. check if the value of key we are populating on is an Object, and whether it has an _id property, if try and Cast that instead
2. Ignore populating that specific item, and just skip past and populate the rest.

As i believe Mongoose manually goes and creates the query that populates those items, AND it kind of fills in the gaps when depopulating/saving already anyway, this would be of great help when running large queries, by not breaking the entire result because one document in the set wasn't depopulated correctly

Appreciate your help/thoughts, and if there is a way that i can do it already, i'm keen to know

**Comment by vkarpov15** [comment]
Right now you would have to execute two separate queries:

```javascript
// Find all contacts with a properly formatted 'data.pets'
Contact.find({
  gender:'male', 'data.pets': { $type: 'string' }
}).populate('data.pets')
.exec()

// Avoid populating the rest
Contact.find({
  gender:'male'
})
.exec()
```

No better workaround right now. We could consider adding a `skipInvalid` option to `populate()` to skip any values that fail to cast rather than throwing an error. What do you think @Hyperblaster ?

**Comment by Hyperblaster** [comment]
Ok thanks for the reply.

I think my issue is that i have some records with it depopulated correctly, and some where it's not so if i used your workaround i wouldn't be able to retrieve all the records.  But only the records that have been formatted back to an ObjectId or an array of ObjectIds,

We run a CMS on mongoose where people can change their own schemas dynamically, and sometimes they change the schema after having already created documents.

Currently if there is a document in the result set the entire node application process blows up with an uncaught exception.

If you could add a skipInvalid option it would be amazing, otherwise i can possibly just hack the core for now as a workaround.

**Comment by JoePassanante** [comment]
I agree this this feature request. 

Would help with developer error.  In some cases, a document will be removed from a collection without knowing about other documents refering to it. 

This completely blocks running populate on large search queries because that one refering document will cause mongoose to throw an error. 

Adding an option would be preferable, maybe even an option that sets the targetted population value to null. (or up to the developer)

**Comment by vkarpov15** [comment]
I added a `skipInvalidIds` option in the 5.6 branch, the below script now executes without error:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7706`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const ContactSchema = new Schema({
   data: {
        type: Schema.Types.Mixed
    },
  });
  const Contact = mongoose.model('Contact', ContactSchema);
  
  const Pet = mongoose.model('Pet', new Schema({ name: String }));
  
  const pets = await Pet.create([
    { name: 'Pooka' },
    { name: 'Kona' }
  ]);
  
  await Contact.create([
    { data: { pets: pets[0]._id } },
    { data: { pets:{ _id: pets[1]._id, title: 'Dog' } } }
  ]);

  const res = await Contact.find().populate({
    path: 'data.pets',
    model: 'Pet',
    justOne: true,
    skipInvalidIds: true // <-- Set this option
  });

  console.log(JSON.stringify(res.map(res => res.data), null, 2));
}
```

Output:

```
[
  {
    "pets": {
      "_id": "5cfaad0fcdc60447484a1600",
      "name": "Pooka",
      "__v": 0
    }
  },
  {
    "pets": {
      "_id": "5cfaad0fcdc60447484a1601",
      "name": "Kona",
      "__v": 0
    }
  }
]
```

**Comment by Hyperblaster** [comment]
This is awesome. Exactly what we needed. Will be testing it out this week
