### ISSUE TITLE
Saving nested model sets property to undefined

### ISSUE THREAD

**Issue by TomVanHaver** [Automattic/mongoose#7707]
**Do` you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Saving nested model sets property to undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

1/ Consider the following parent/child schema:

```
const childSchema = new mongoose.Schema({
    importantProp: {
        name: {
            type: String,
        },
        active: {
            type: Boolean,
            default: true,
        },
    },
}, { _id: false });

const parentSchema = new mongoose.Schema({
    filters: childSchema,
});
```

2/ when i update the model with model.filters = updatedModel.filters where name and active have different values, the "active" property is updated with the new value, but name becomes undefined.

**What is the expected behavior?**
name property should not be undefined, but the updated value.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.5.0
MongoDB: 3.6.8
NodeJS: 10.15.3 LTS

**Comment by vkarpov15** [comment]
We fixed a similar issue in v5.5.1 (#7660), can you try upgrading and see whether that fixes your issue?

Also, can you clarify what "where name and active have different values, the "active" property is updated with the new value" means with some code samples?

**Comment by Msordet** [comment]
Hi, I am having a similar issue with validation, here's the [code](https://gist.github.com/Msordet/0396a7f0f3d067dedbdd34b1506c84a6) to reproduce using mongoose@5.5.1.
The error is:
> Fail at user validation
> ValidationError: User validation failed: position.geometry.type: Path `geometry.type` is required., position: Validation failed: geometry.type: Path `geometry.type` is required.

Let me know if I should create a separate issue or if this is acceptable here.

**Comment by paglias** [comment]
Getting the same errors with 5.5.1 despite the fix

**Comment by vkarpov15** [comment]
@paglias can you please open up a separate issue with code samples?

**Comment by paglias** [comment]
@vkarpov15 I can create a new issue if needed but the script @Msordet posted in the previous comment at https://gist.github.com/Msordet/0396a7f0f3d067dedbdd34b1506c84a6 seems to be a good repro for the issue. I just tested it on mongoose 5.5.3 and it shows the problem
