### ISSUE TITLE
Got unexpected result from `new Types.Array()` 

### ISSUE THREAD

**Issue by NateScarlet** [Automattic/mongoose#7710]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Got `[null]` when using `new Types.Array()`

**If the current behavior is a bug, please provide the steps to reproduce.**

test.js:
```javascript
const { Types, version } = require('mongoose');
const mongooseArr = new Types.Array();
const nativeArr = new Array();

console.log(version);
console.log('mongoose');
console.log('arr', mongooseArr);
console.log('len', mongooseArr.length);
console.log('native');
console.log('arr', nativeArr);
console.log('len', nativeArr.length);
```

```shell
$ node test.js
5.5.1
mongoose
arr [null]
len 1
native
arr []
len 0
```

**What is the expected behavior?**

Got a empty array when using `new Types.Array()`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 10.9.0
mongoose: 5.5.1

**Comment by NateScarlet** [comment]
Found this seems to be a private api

I'll just replace `doc.arr = new Types.Array()` with 

```javascript
doc.arr.splice(0, doc.arr.length)
```

**Comment by vkarpov15** [comment]
Why are you looking to instantiate a mongoose array that isn't tied to a document? That isn't something we support because there hasn't really been a use case, so I'd love to hear your use case

**Comment by NateScarlet** [comment]
I'm using typescript so i had to use `Types.Array` on my model's interface:
```typescript
import { Schema, model, Model, Document, Types } from 'mongoose';

export interface IFoo extends Document {
  arr: Types.Array<string>; // Not native array if i want use mongoose array api
}

const schema: Schema = new Schema({
  arr: [{ type: String, required: true }],
});

export const fooModel: Model<IFoo> = model<IFoo>('foo', schema);
```

Then when i want to clear a array, i can not just reassign it with a empty array:
```typescript
const value: IFoo = new fooModel({ arr: [1, 2, 3] });
value.arr = []; // This will cause a ts error: Type 'undefined[]' is missing the following properties from type 'Array<string>': $shift, remove, $pop, addToSet, and 5 more.ts(2740)
```

This will avoid that error but come with wrong result (and https://github.com/Microsoft/tslint-microsoft-contrib/issues/856):
```typescript
const value: IFoo = new fooModel({ arr: [1, 2, 3] });
value.arr = new Types.Array();
```

A shortcut method calls `arr.splice(0, arr.length, input)` may be needed to set or clear array value

**Comment by vkarpov15** [comment]
The whole point of Mongoose is that `value.arr = []` converts `[]` to a Mongoose array for you. Would using `value.set('arr', [])` help this pass your linter? https://mongoosejs.com/docs/api.html#document_Document-set .

**Comment by NateScarlet** [comment]
> The whole point of Mongoose is that `value.arr = []` converts `[]` to a Mongoose array for you. Would using `value.set('arr', [])` help this pass your linter? https://mongoosejs.com/docs/api.html#document_Document-set .

That is what i need, thank for the help.
