### ISSUE TITLE
Mongoose is returning only one document for array of same object id

### ISSUE THREAD

**Issue by viveksharmaui** [Automattic/mongoose#7711]
Hi guy's i'm using **mongoose version 5.4.0** and i'm using find() for find all documents in array of object id . this array of object id can be same or different , but when same object id in an array occured mongoose returning single document for that same object id , suppose if i have a array of id's ['123','123'.'123'] i want 3 documents for that but mongoose is returning only one document . why is that ? 
Thanks :)

**Comment by 720degreeLotus** [comment]
Hi @viveksharmaui  :)
To help you, can you provide us with example-code?
I think, for this use-case, the code related to your query should be enough :)

**Comment by viveksharmaui** [comment]
> Hi @viveksharmaui :)
> To help you, can you provide us with example-code?
> I think, for this use-case, the code related to your query should be enough :)

Hi i have array of object id let arr = ['123','123','123'] I'm using find() 
like that 
model.find({_id:arr}).then((response) => {
console.log(response)  // this response is an array of json and it's length is 1 
})

**Comment by 720degreeLotus** [comment]
Ah, i see :)
If you want to search for multiple IDs, you should use the `$in`-operator:

```js
model.find({
    _id: {
        $in: ['123','456','789']
    }
})
.then((response) => {
    console.log(response) // this response is an array of json and it's length is 1
})
```
or just use `$in: arr` in your case.
I hope this helps :)

Also, if you are posting code on github-comments, it's better to use this syntax:

> \`\`\`js
> // your code goes here
> \`\`\`

This way your code get's highlighted in the correty syntax and this makes it more readable for others, who want to help =)

**Comment by viveksharmaui** [comment]
> Ah, i see :)
> If you want to search for multiple IDs, you should use the `$in`-operator:
> 
> ```js
> model.find({
>     _id: {
>         $in: ['123','456','789']
>     }
> })
> .then((response) => {
>     console.log(response) // this response is an array of json and it's length is 1
> })
> ```
> 
> or just use `$in: arr` in your case.
> I hope this helps :)
> 
> Also, if you are posting code on github-comments, it's better to use this syntax:
> 
> > ```js
> > // your code goes here
> > ```
> 
> This way your code get's highlighted in the correty syntax and this makes it more readable for others, who want to help =)

I have used $in operator but it still returns single document . Did you try your example ? Is it returning 3 documents for array of same object ids for you ?

**Comment by viveksharmaui** [comment]
> Ah, i see :)
> If you want to search for multiple IDs, you should use the `$in`-operator:
> 
> ```js
> model.find({
>     _id: {
>         $in: ['123','456','789']
>     }
> })
> .then((response) => {
>     console.log(response) // this response is an array of json and it's length is 1
> })
> ```
> 
> or just use `$in: arr` in your case.
> I hope this helps :)
> 
> Also, if you are posting code on github-comments, it's better to use this syntax:
> 
> > ```js
> > // your code goes here
> > ```
> 
> This way your code get's highlighted in the correty syntax and this makes it more readable for others, who want to help =)

By the way I'm finding data from same object ids not different object ids .

**Comment by 720degreeLotus** [comment]
Wait... i thought i misinterpreted your question.
You are really putting the same id into the search-array?
What is the reason for this? If it's all the same, then just search for the id, not the array.
And what do you expect to be returned?
I think we may need more information, can you post us your schemas?^^°

**Comment by viveksharmaui** [comment]
> Wait... i thought i misinterpreted your question.
> You are really putting the same id into the search-array?
> What is the reason for this? If it's all the same, then just search for the id, not the array.
> And what do you expect to be returned?
> I think we may need more information, can you post us your schemas?^^°

Yeah! 
I have model in which i have assigned field which is array and in this array i have jsons

My Schema
assigned:[{
type:String,
id:ObjectId,
data:String
}]
in this assigned array i have jsons in those jsons i have field id , which is mongoose id for user according to our requirements we can assign different data to same user now suppose if i want to assign data to user whose object id is 1 twice then this assigned array will be

assigned :[{
type:'User',
id:'abc',
data:'do homework'
},
type:'User',
id:'abc',
data:'write some code'
},
]

Now if i query this with aggregate function it simply returns single information in response .

**Comment by vkarpov15** [comment]
When you do `.find()`, you only get back top level documents. You don't get back the subdocuments individually. So when you do `.find({ arr: '123' })` you get back all top level docs whose `arr` array contains '123'

**Comment by viveksharmaui** [comment]
Hi Guy's i'm sharing my code with you

**Comment by viveksharmaui** [comment]
Hi Guy's i'm sharing codes and schema with you :) 

`const trip = new Schema({
  assignedTo : [
    {
      type : { type : String , enum : TRIP_ASSIGN_TO } ,
      driver : { type : ObjectId , ref : "Drivers" } ,
      vehicle : { type : ObjectId , ref : "Vehicles" } ,
      broker : { type : ObjectId , ref : "Brokers" } ,
      brokerVehicleType : { type : ObjectId , ref : "VehicleTypes" } ,
      brokerDriver : { type : String } ,
      brokerVehicle : { type : String }
    }
  ] ,
});`

**Comment by viveksharmaui** [comment]
Hi Guy's i'm sharing codes and schemas with you

**Comment by viveksharmaui** [comment]
Hi Guy's i'm sharing codes and schemas with you .

My Schema : 
> const trip = new Schema({
  assignedTo : [
    {
      type : { type : String , enum : TRIP_ASSIGN_TO } ,
      driver : { type : ObjectId , ref : "Drivers" } ,
      vehicle : { type : ObjectId , ref : "Vehicles" } ,
      broker : { type : ObjectId , ref : "Brokers" } ,
      brokerVehicleType : { type : ObjectId , ref : "VehicleTypes" } ,
      brokerDriver : { type : String } ,
      brokerVehicle : { type : String }
    }
  ] ,
});

**This assignedTo array can consist of multiple objects** 

If i have inserted a documents .

> {
 _id:ObjectId("5c96d79be711a32dd0ce9612")
assignedTo:[{
   type:'Driver',
   driver:ObjectId('5c96d79be711a32dd0ce9611'),
   vehicle:ObjectId('5c96d79be711a32dd0ce9610')
},{
   type:'Driver',
   driver:ObjectId('5c96d79be711a32dd0ce9611'),
   vehicle:ObjectId('5c96d79be711a32dd0ce9610')
}]}

I have a situation where i can assign trip to multiple drivers , brokers and those drivers , brokers can be same , see above document i have same driver .

Now if i query that document by using aggregate 

> trip.aggregate([{
  {
  $lookup:{from:"drivers",
    localField:"assignedTo.driver",
    foreignField:"_id",
   as:"drivers"
  },
}
}])

This query is returning on one driver when driver id is same  ..

But i want two documents even for same driver ids .

Thank You !

**Comment by vkarpov15** [comment]
Can you clarify what you mean by "this query is returning only one driver when driver id is same"?

**Comment by viveksharmaui** [comment]
> Can you clarify what you mean by "this query is returning only one driver when driver id is same"?

I mean that for same driver object id's mongoose is returning single document . 
suppose **driver ids = ['123','222','123']**
so mongoose is returning only two documents for this array if i query this array . 
I think that this is default behavior of mongodb .. What you think ? 
**Should i map each element of array and use findOne instead of find() on driver ids array ?** 
Is it the good practice for using map i mean i will check each driver id and in single driver i can have 20 to 50 driver ids .

**Comment by Rock-Moon** [comment]
@viveksharmaui  I also have the same problem？Have you solved this problem yet?

**Comment by viveksharmaui** [comment]
> @viveksharmaui I also have the same problem？Have you solved this problem yet?

I have solved problem by mapping each and every element in an array and using findOne() inside map() but this is not the feasible solution ,

**Comment by vkarpov15** [comment]
@viveksharmaui the below script shows `$unwind` produces 3 docs. Can you please modify the below script to demonstrate your issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7711`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    assigned: [{ driverId: Number }]
  });
  const Model = mongoose.model('gh7711', schema);

  await Model.create({ assigned: [{ driverId: 1 }, { driverId: 2 }, { driverId: 1 }] });

  const res = await Model.aggregate([{
    $unwind: {
      path: '$assigned',
      preserveNullAndEmptyArrays: true
    }
  }]);

  console.log(res);
}
```

**Comment by viveksharmaui** [comment]
@vkarpov15  here is my script which produces only 1 doc .

> ```js
> const assert = require('assert');
> const mongoose = require('mongoose');
> mongoose.set('debug', true);
> 
> const GITHUB_ISSUE = `gh7711`;
> const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
> const { Schema } = mongoose;
> 
> run().then(() => console.log('done')).catch(error => console.error(error.stack));
> 
> async function run() {
>   await mongoose.connect(connectionString);
>   await mongoose.connection.dropDatabase();
> 
> 
>   const driver = new Schema({name:String,driverId:Number});
>   
>  const driverModel = mongoose.model('driver',driver);
> 
>  await driverModel.create({name:"vivek",_id:1},{name:"fahad",_id:2})
> 
>   const schema = new Schema({ assigned: [{ driverId: ObjectId }]});
> 
>   const Model = mongoose.model('gh7711', schema);
> 
>   await Model.create({ assigned: [{ driverId: 1 }, { driverId: 2 }, { driverId: 1 }] });
> 
> 
>   const res = await Model.aggregate([{
> $lookup:{
>    from:"drivergh7711",
>    localField:"driverId",
>    foreignField:"_id",
>    as:"driverInformation"}
> }]);
> 
>   console.log(res);
> }
> ```

**Comment by vkarpov15** [comment]
@viveksharmaui that's expected behavior. There's only one doc in the collection, so one doc goes into `$lookup`, and `$lookup` always produces one document for every document that comes in. You need to use [`unwind()`](https://mongoosejs.com/docs/api.html#aggregate_Aggregate-unwind) as I did in [this comment](https://github.com/Automattic/mongoose/issues/7711#issuecomment-486296879) to get one doc for every `assigned` subdoc.

**Comment by viveksharmaui** [comment]
Hi guy's i didn't find any solution of this problem this is the default behavior of mongodb and mysql i don't know about other database but these two database use set at backend to get document from unique array of object id's .

**Comment by mhombach** [comment]
> Hi guy's i didn't find any solution of this problem this is the default behavior of mongodb and mysql i don't know about other database but these two database use set at backend to get document from unique array of object id's .

- mysql has no documents and no arrays with object-IDs
- as you already said, this is default behaviour. Did you try the solution of @vkarpov15 and it didn't work? Help us helping you by providing a code-snipped of what you tried and what didnt work :)
