### ISSUE TITLE
New change in document.js caused dead loop when object contain '_parent' object?

### ISSUE THREAD

**Issue by BaronChen** [Automattic/mongoose#7717]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
An infinite loop with a `RangeError: Maximum call stack size exceeded`  error and server crashed eventually
**If the current behavior is a bug, please provide the steps to reproduce.**
In document.js line 821 and line 788, if an object have a '_parent' reference, it will cause a dead loop? I think it is because we are don't use isPOJO to check object anymore? We got this in our system after update. 
<img width="853" alt="Screen Shot 2019-04-17 at 10 35 07 pm" src="https://user-images.githubusercontent.com/7041385/56287990-20b58600-6161-11e9-9750-a5c716423605.png">

The use case of us if adding one existing model as a child of a new model and then save the new model (we want the first document to become a child of the second document)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.5.2

**Comment by vkarpov15** [comment]
The stack trace is helpful, but still not enough to determine how we can most effectively fix this issue. The below script executes without error for me, can you modify the below script to demonstrate your issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7717`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    _parent: { name: String }
  });
  const Model = mongoose.model('Test', schema);

  const doc = new Model();
  doc.$set({ _parent: { name: 'foo' } });

  await doc.save();
}
```
