### ISSUE TITLE
The getter function is called for 3 times

### ISSUE THREAD

**Issue by FrXer** [Automattic/mongoose#7719]
The mongoose version is 5.5.2

Is it a bug or expected behavior?

My script:
```var mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test', { useNewUrlParser: true })
mongoose.set('debug', true)
var db = mongoose.connection
db.on('error', console.error.bind(console, 'connection error:'))

db.once('open', function() {
  console.log('DB connected!')

  // test
  var kittySchema = new mongoose.Schema({
    name: {
      type: String,
      set: function(v) {
        console.log('Setter called')
        return v
      },
      get: function(v) {
        console.log('Getter called')
        return v
      }
    }
  })
  var Kitten = mongoose.model('Kitten', kittySchema)

  var silence = new Kitten({ name: 'silence' })
  console.log('-------')
  silence.save(function(err) {
    if (err) return console.error(err)
  })
})
```
I got below:
DB connected!                                                                                        
Setter called                                                                                        
'-------                                                                                              
Getter called                                                                                        
Getter called                                                                                        
Mongoose: kittens.insertOne({ _id: ObjectId("5cb742e867934d2eb0e7c2f8"), name: 'silence', __v: 0 })  
Getter called          

Why Getter called 3 times?  What am i missing?

**Comment by vkarpov15** [comment]
Might be a bug, I'll have to investigate more.

**Comment by FrXer** [comment]
@vkarpov15  thanks! Waiting for your further investigation.
BTW, I found if I close **validateBeforeSave** before save, like below, the Getters will be called 2 times.
Hope this is helpful for your investigation.
 ```
kittySchema.set('validateBeforeSave', false)
```
