### ISSUE TITLE
Schema instance methods referencing this.find, this.findOnce, etc. throws

### ISSUE THREAD

**Issue by torgeir** [Automattic/mongoose#772]
Hi,

The following

``` javascript
var mongoose = require('mongoose')
  , CarSchema
  , Car

mongoose.connect('mongodb://localhost/bug_or_feature');

CarSchema = new mongoose.Schema({ reg: Number });
CarSchema.methods.byReg_FAILING = function (reg, fn) {
  this.find({ reg: reg }, fn);
};
CarSchema.methods.byReg = function (reg, fn) {
  Car.find({ reg: reg }, fn);
};
Car = mongoose.model('Car', CarSchema);

var c = new Car();
c.byReg_FAILING('666');
c.byReg('1337');

mongoose.disconnect();
```

Produces

``` bash
$ node mongoose-test.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object { _id: 4f5f67d498d17ca168000001 } has no method 'find'
    at model.byReg_FAILING (/home/torgeir/code/mongoose-test.js:9:8)
    at Object.<anonymous> (/home/torgeir/code/mongoose-test.js:17:3)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

Reading [docs](http://mongoosejs.com/docs/methods-statics.html) and the [example](https://github.com/LearnBoost/mongoose/blob/master/examples/schema.js#L76) my impression was that both of CarSchema's instance methods should be working?

Changing `this.find` for `this.db.model('Car').find`, however, seems to be working.

Regards,
Torgeir

**Comment by jesse1981** [comment]
Thankyou! Same problem for me.

**Comment by enthusiast94** [comment]
Thanks! I was having the same issue.

**Comment by RachelScodes** [comment]
Same here! thank you!

**Comment by nicholaswmin** [comment]
+1

**Comment by codingmaven** [comment]
+1

**Comment by MustafaDal** [comment]
+1

**Comment by varunjayaraman** [comment]
Can you explain what error you're seeing? instances should NOT have the `.find` property on them. That is a schema-level method. This functionality is intentional.

**Comment by RachelScodes** [comment]
@varunjayaraman 

>  instances should NOT have the .find property on them. That is a schema-level method. This functionality is intentional.

This ticket was opened a while ago. As of the last time I checked, they now do correctly show that when using `find` on an instance method it should be invoked as `this.Model.find`, aka calling find on the class, not the instance, which makes total sense.

**Comment by Royal-XL** [comment]
Thanks @varunjayaraman

**Comment by luchotess** [comment]
@RachelScodes

> it should be invoked as this.Model.find

it should be actually `this.model('Car').find()` according to the documentation.
