### ISSUE TITLE
Bug in Schema.clone() with Backbone validators

### ISSUE THREAD

**Issue by tomgreenfield** [Automattic/mongoose#7720]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
In our app, we specify validators provided by [Backbone Forms](https://github.com/powmedia/backbone-forms#examples-5) in our schema. Please [here](https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/properties.schema#L53) for an example.

Using schema that contains `validators: ["required"]`, the following code introduced in **mongoose@5.4.15** has caused our app to crash:
https://github.com/Automattic/mongoose/blob/92dd3464ed3bc695abc54b91cf28b26b7314441f/lib/schematype.js#L39-L41

The above code was added for the `clone()` function:
https://github.com/Automattic/mongoose/blob/92dd3464ed3bc695abc54b91cf28b26b7314441f/lib/schematype.js#L1340-L1343

This function blends the `this.validators` array into the `options` schema to pass the array through the constructor and into the cloned instance.

For context:

| Variable | Description |
| - | - |
| `this.validators` | An array of validator objects for the `SchemaType` instance |
| `options.validators` | Our Backbone Forms validation directives from the schema |

**What is the expected behavior?**
Instead of blending the instance property `this.validators` with the `options` schema, the two domains should remain separate. The validators can be added to the cloned instance after it is created, rather than passing them through the constructor, i.e.:
```js
SchemaType.prototype.clone = function() {
  const options = Object.assign({}, this.options); // Clone the schema
  const cloned = new this.constructor(this.path, options, this.instance); // Clone the instance
  cloned.validators = this.validators; // Copy of the validators
  return cloned;
};
```
then line 39 can be reverted to:
```js
this.validators = [];
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
* NodeJS: 10.11
* Mongoose: 5.5.2
* MongoDB: 3.2

**Comment by oliverfoster** [comment]
Repo script:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

const NewSchema = new Schema({
  object: {
    type: 'string',
    validators: ['string']
  }
});

// Will error on save as validators are absorbed as
// a functional part of schema validation.

const TestModel = mongoose.model('ModelName', NewSchema);
const instance = new TestModel();
instance.object = 'value'; // Cause validation to execute

instance.save(function (err) { // Execute validation
  
});
```
