### ISSUE TITLE
`RangeError: Maximum call stack size exceeded` error occurs for v5.5.2

### ISSUE THREAD

**Issue by uhdang** [Automattic/mongoose#7722]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

`RangeError: Maximum call stack size exceeded` error occurs

**If the current behavior is a bug, please provide the steps to reproduce.**

referencing :: https://stackoverflow.com/questions/24466366/mongoose-rangeerror-maximum-call-stack-size-exceeded

Infinite recursive occurs.
In my case, I save a document using `.save()` and then make modification and then `.save()`, which seems to trigger a similar behavior as the entry referenced above as opposed to saving / inserting a plain json object.

![image](https://user-images.githubusercontent.com/20474346/56362678-bd703600-61ea-11e9-899c-0552bc0b4ea5.png)

**What is the expected behavior?**
No recursive error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node v7.9.0
mongoose ^5.3.11
mongodb 2.2.11

**How it's been resolved**
Error is gone when I change mongoose version to 5.5.1.
This started happening when 5.5.2 is published.
I wanted to let u guys know of this

**Comment by vkarpov15** [comment]
Please provide code samples, stack trace isn't particularly helpful
