### ISSUE TITLE
mongoose function create and insertMany auto convert array to object

### ISSUE THREAD

**Issue by ngankt2** [Automattic/mongoose#7727]
DataFakeTest.create({
        'tags':["tech","php","sql"]
});

data after insert

`/* 13 */
{
    "_id" : ObjectId("5cbd96e102c912558673dc26"),
    "tags" : {
        "0" : "tech",
        "1" : "php",
        "2" : "sql"
    },
    "__v" : 0
}`

Please help me
my data is array object (not object)

**Comment by vkarpov15** [comment]
@ngankt2 what does your schema look like?

**Comment by ngankt2** [comment]
@ValYouW  My code
`
```javascript
import mongoose from 'mongoose';

/**
 *
 */
const DataFakeTestSchema = new mongoose.Schema({}, {strict: false}
);
DataFakeTestSchema.options.strict = false;
DataFakeTestSchema.options.toJSON = {
    transform: function (doc, ret) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
        return ret;
    },
};

const DataFakeTest = mongoose.model('data_fake_test', DataFakeTestSchema, 'data_fake_test');
export default DataFakeTest
````

**Comment by ngankt2** [comment]
@ValYouW 
Can you help me!
Please

**Comment by snakierten96** [comment]
This appears to reproduce from version 5.5.1 and onwards. Earlier versions do not show the same behavior

**Comment by vkarpov15** [comment]
This is a duplicate of #7733, please upgrade to 5.5.6 for the fix :+1:

**Comment by jomgapuz** [comment]
Can we reopen this? The bug is apparent on `"^6.0.4"`.

**Comment by vkarpov15** [comment]
@jomgapuz no. Please open a new issue and follow the issue template, including detailed code samples. Also, please stop spamming.
