### ISSUE TITLE
Array type data converted on Object (Map with key and value)

### ISSUE THREAD

**Issue by raj-here** [Automattic/mongoose#7733]
I have dynamic json (Structure is not defined) which have to stored into db.

```
let data = {
    "channelTaxonomyList": [
        { "categoryId": "10187", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10237", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10025", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10030", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10157", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10278", "taxonomyName": "Website Taxonomy" },
        { "categoryId": "10055", "taxonomyName": "Website Taxonomy" }
    ]
};

let newProduct = new product(data);

newProduct.save(function (err, savedProduct) {
    if (err) {
        console.log("err", err)
    } else {
        console.log("savedProduct", savedProduct)
    }
})
```

**Expectation:** 
saved document should like this. **channelTaxonomyList** must be type **Array**
```
{ _id: 5cbefb9d663e872f07f79467,
  channelTaxonomyList: 
   [ { categoryId: '10187', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10237', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10025', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10030', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10157', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10278', taxonomyName: 'Website Taxonomy' },
     { categoryId: '10055', taxonomyName: 'Website Taxonomy' } ],
  __v: 0 }
```
**Actual Result:**  channelTaxonomyList converted into Object (Map Type with key and value).
Array index changes into key and array elements into values.

```
{ _id: 5cbefb85a09e6a1d4376ebec,
  channelTaxonomyList:
   { '0': { categoryId: '10187', taxonomyName: 'Website Taxonomy' },
     '1': { categoryId: '10237', taxonomyName: 'Website Taxonomy' },
     '2': { categoryId: '10025', taxonomyName: 'Website Taxonomy' },
     '3': { categoryId: '10030', taxonomyName: 'Website Taxonomy' },
     '4': { categoryId: '10157', taxonomyName: 'Website Taxonomy' },
     '5': { categoryId: '10278', taxonomyName: 'Website Taxonomy' },
     '6': { categoryId: '10055', taxonomyName: 'Website Taxonomy' } },
  __v: 0 }
```

As i describe above the json have no predefined structure, key may be change at run time, So in **schema** i'm using **{ strict: false }**.

My schema and model is :

```
import * as mongoose from 'mongoose';
const ProductSchema = new mongoose.Schema({
}, { strict: false });

ProductSchema.index({ '$**': 'text' });
export default mongoose.model('new_products', ProductSchema);
```

**Node Version:**  8.10.0
**@types/mongoose:**  5.3.24
**mongoose:**  5.4.20

**Note:** Working fine in local machine (OS: Mac- High Sierra).
               Bug is producible on AWS server (OS: Ubuntu: 18.04.2 LTS)

**Comment by raj-here** [comment]
Looking relatable to #7727 .

**Comment by snakierten96** [comment]
Version as reported does not reproduce. The issue does reproduce off current 5.5.3 and from 5.5.1 onwards.

**Comment by ashu8006kumar** [comment]
Actually in my package.json mongooes version is declared as **"mongoose": "^5.4.20"**. So i think carets(^) was the problem behind it for this version. It was automatically upgraded to latest one. after removing caret(^), it is working fine for that version.

**Comment by raj-here** [comment]
Actually in my package.json mongooes version is declared as **"mongoose": "^5.4.20"**. So i think carets(^) was the problem behind it for this version. It was automatically upgraded to latest one. after removing caret(^), it is working fine for that version.

**Comment by jomgapuz** [comment]
Can we reopen this? The bug is apparent on `"^6.0.4"`.

**Comment by vkarpov15** [comment]
@jomgapuz no. Please open a new issue and follow the issue template, including detailed code samples.
