### ISSUE TITLE
Error: EBADNAME on macOS (executes fine on Windows)

### ISSUE THREAD

**Issue by bradenmitchell** [Automattic/mongoose#7739]
I am trying to connect to MongoDB Atlas via mongoose in a node/express application.
The server.js code below executes as expected on my Windows 10 machine at work, but when I run it on my MacBook Pro it throws the following error:

**Error**
```
{ Error: queryTxt EBADNAME development-zv5hp.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
  errno: 'EBADNAME',
  code: 'EBADNAME',
  syscall: 'queryTxt',
  hostname: 'development-zv5hp.mongodb.net' }
```

**server.js**
```
const express = require('express');
const mongoose = require('mongoose');
const keys = require('./config/keys')

const app = express();

mongoose
  .connect(keys.mongoURI, { useNewUrlParser: true })
  .then(result => {
    console.log('MongoDB Connected');
    const PORT = process.env.PORT || 5000;
    app.listen(PORT, () => console.log(`Server running on port ${PORT}...`));
  })
  .catch(err => console.log(err));
```

I have triple checked the Atlas connection string (the `keys.mongoURI` variable) - as mentioned this connects fine on windows but not macOS. I have also tried setting up a different cluster on Atlas and creating new users/updating passwords, but still get the same error.

the Atlas connection string is of type:
`mongodb+srv://USERNAME:PASSWORD@development-zv5hp.mongodb.net/DB_NAME?retryWrites=true`

Versions
mongoose: 5.5.3
node: 10.15.3
express: 4.16.4

**Comment by Fonger** [comment]
Maybe there's some problem with your DNS on your macbook
Try `dig development-zv5hp.mongodb.net` and see if the ＤＮＳ return an ＩＰ for you on Ｍａｃｋｂｏｏｋ.

Note: your domain seems to not work at this moment.

**Comment by BradenLM** [comment]
Ran the dig command with the following output:

```
; <<>> DiG 9.10.6 <<>> development-zv5hp.mongodb.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49827
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;development-zv5hp.mongodb.net.	IN	A

;; AUTHORITY SECTION:
mongodb.net.		60	IN	SOA	ns-761.awsdns-31.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 60

;; Query time: 492 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Sat Apr 27 07:57:42 ACST 2019
;; MSG SIZE  rcvd: 139
```

**Comment by vkarpov15** [comment]
@BradenLM have you tried using a different network? There may be some firewall issue.

**Comment by BradenLM** [comment]
@vkarpov15 Good point - I just tried hotspotting macbook off my phone and it connected perfectly. Swapped back to the wifi network and it throws the error. 

Any ideas about what might be causing this?

**Comment by vkarpov15** [comment]
I unfortunately don't know, there are numerous possibilities. I'd guess there's some firewall on your work's network that's preventing the connection, but I have no way of confirming that.

**Comment by junweipan** [comment]
I have the same issue when I use my home wifi:'EBADNAME': queryTxt EBADNAME gettingstarted-hkp01.mongodb.net.

But when I change to use my iPhone hotspot, it works.
That is so strange.
