### ISSUE TITLE
Session is not available in pre('save') hook

### ISSUE THREAD

**Issue by artempokutnii** [Automattic/mongoose#7742]
**What is the current behavior?**
In document creation process we set session to document as **doc.save({ session })**,
but in model pre('save') hook session is not available.

**What is the expected behavior?**
After some investigation we defined that all pre('save') hooks are processing before 
**doc.save({ options })** options arguments registration.

Reason - **$__handleSave** runs after **createWrapper('save')**.

It is right way that session which was passed as **.save()** options is not available in pre('save') hook?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node - 10.15.0
Mongoose - 5.5.3
MongoDB - 4.0.0

Some example

**Controller**
```javascript
async function create (req, res, next) {
  try {
    // start session
    const session = await mongoose.startSession();
    session.startTransaction();

    // get doc
    const doc = await SampleModel.model.findOne();
    doc.foo = 'bar';

    // save doc with session
    doc.save({ session });

    // commit session
    await session.commitTransaction();
    session.endSession();

    // return res
    return res.json(doc);
  } catch (e) {
    return next(e);
  }
}
```

Model

```javascript
SampleModel.schema.pre('save', async function (next) {
  try {
    const session = this.$session();
    console.log(session); // null
    next();
  } catch (e) {
    return next(e);
  }
});
```

**Comment by vkarpov15** [comment]
Good idea. We will improve this. Unfortunately I don't have a good workaround unless you explicitly pass the session as an option.

**Comment by zinzinday** [comment]
1+) To the best we can implement session to middleware hook and custom validate.
mongodb core current not working session with unique key (on one session we can insert multiple duplicated key into database)...

**Comment by artempokutnii** [comment]
@vkarpov15 Hi!
One more question - can your team add this feature to **pre('remove')** hook too? For example for cascade deletion

**Comment by vkarpov15** [comment]
@artempokutnii thanks for the suggestion. We'll look into it.
