### ISSUE TITLE
Old dependencies in 5.5.4

### ISSUE THREAD

**Issue by qmmr** [Automattic/mongoose#7753]
BUG

**What is the current behavior?**
```
mongoose@5.5.4:
  version "5.5.4"
  resolved "https://registry.yarnpkg.com/mongoose/-/mongoose-5.5.4.tgz#77b0664dd7e49a0a158d1eb83f6e53433b57b48b"
  integrity sha512-xzS7fJtXGjCOZozCtlyFS8graMub1L9knp37+1dJCDmWzOtXVHeLjV2XIC9tX0sE54cxeG5rHvSmIkLpeHjjmA==
  dependencies:
    async "2.6.1"
    bson "~1.1.1"
    kareem "2.3.0"
    mongodb "3.2.2"
    mongodb-core "3.2.2"
    mongoose-legacy-pluralize "1.0.2"
    mpath "0.5.2"
    mquery "3.2.0"
    ms "2.1.1"
    regexp-clone "0.0.1"
    safe-buffer "5.1.2"
    sift "7.0.1"
    sliced "1.0.1"
```
---

Looking at the yarn.lock after installing version `5.5.4` I can still see old dependencies of `mongodb` and `mongodb-core` from version `3.2.2`

**What is the expected behavior?**

According to this https://github.com/Automattic/mongoose/commit/23158ba9b1172c7dc280ea72c7190c4722f88dbd `mongodb` and `mongodb-core` should be version `3.2.3`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

`mongoose.version 5.5.4`

This is related to https://github.com/zeit/now-builders/issues/335

**Comment by vkarpov15** [comment]
@qmmr those changes were not part of the 5.5.4 release. They'll be in v5.5.5. See #7752.
