### ISSUE TITLE
npm returns 404 Not Found: mongooose@latest

### ISSUE THREAD

**Issue by jtmilne** [Automattic/mongoose#7755]
npm seems to be down and build is currently failing...

**Comment by AbdulRehman3** [comment]
Its working here with me, try
`npm i -s mongoose@latest
`

> npm 6.5.0
> node 10.15.2
> mongoose 5.5.4

**Comment by jtmilne** [comment]
That worked. No idea why `npm i --save mongoose` didn't work and `npm i -s mongoose@latest` worked. And now after installing mongoose@latest I can revert and install just mongoose without a 404.
