### ISSUE TITLE
Mongoose transactions not working

### ISSUE THREAD

**Issue by krishnavissapragada** [Automattic/mongoose#7758]
i want to report a *bug*

**What is the current behavior?**
 i have two documents which are related. i have to save the _id of one document into other document. i am using transactions to update two documents at a time so that the data is not corrupted.

But the problem is documents are not getting update . Here is my code
`
    const session = await mongoose.startSession();

    session.startTransaction();

    try {
        MoneyTransactions.updateMany({
            _id: { $in: [id1,id2 ]}
        }, {
                settledOnImport: importTransaction._id
            }, { session }
        )

        Imports.update(
            { _id: importTransaction._id },
            {
                settledOn: Date.now()
            }, { session })

        await session.commitTransaction()

        return importTransaction;

    }

    catch (e) {

        return null;

    }

    finally {
        session.endSession();
    }
`

**What is the expected behavior?**
Transactions should update the documents

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node version-v10.15.3
mongoose   -5.5.4
 typescript   - ^3.4.4
mongodb    -4.0.1

**Comment by zinzinday** [comment]
What's debug error message? your method to initial database connection? mongoose.connect or mongoose.createConnection()? if your method connect with connection = mongoose.createConnection then by use connection.startSession()

```ts
await model.updateMany(condition, data2update).session(session).exec();
```

**Comment by krishnavissapragada** [comment]
yes it worked when i added await... Thanks!

**Comment by rupeshpawar93** [comment]
Hey I am using mongoose.connect  and i am getting error MongoError: No transaction started

**Comment by krishnavissapragada** [comment]
> Hey I am using mongoose.connect and I am getting error MongoError: No transaction started
> Can anyone help me on that?

are you running relicaset locally?

**Comment by rupeshpawar93** [comment]
ty for the help but  i have solved the issue.

> > Hey I am using mongoose.connect and I am getting error MongoError: No transaction started
> > Can anyone help me on that?
> 
> are you running replicaset locally?
