### ISSUE TITLE
Queries with $all operator return odd results

### ISSUE THREAD

**Issue by theochampion** [Automattic/mongoose#7759]
Hi there,

I'm trying to match an array field in one of my queries using the `$all` operator but I noticed something weird, the result returned is odd and does not match the query.

```javascript
const conversation = await ConversationModel.findOne({
	peers: { $all: ["5cb9adf5b374f37876d67188"] }
}).exec();

console.log(conversation);
```

gives me 

```bash
{ peers:
   [ 5ca0b855e5aea8e0cd94886e,
     5cb9adf5b374f37876d67188,
     5cbd8da83407747ad45faca7 ],
  _id: 5cbdb9544719733f281c07eb,
  createdAt: 2019-04-22T12:53:40.814Z,
  updatedAt: 2019-04-22T12:53:40.814Z,
  __v: 0 }
```

Which as you can see doesn't match the query.

Any idea of what's going on?

I'm using mongoose `v5.5.4`.

**Comment by Fonger** [comment]
This is how [$all works in MongoDB](https://docs.mongodb.com/manual/reference/operator/query/all/) so it does match the query.

**Comment by vkarpov15** [comment]
@Fonger correct again, thanks for your help with this issue :+1:

**Comment by theochampion** [comment]
@Fonger Thanks for the reply!

I tried your solution for the exact match but still having problem, it is now throwing a exception

```javascript
Cast to ObjectId failed for value "{ peers: [ \'5ca0b855e5aea8e0cd94886e\' ] }" at path "peers" for model "Conversation"
```

Any idea?
