### ISSUE TITLE
arrayFilters in findByIdAndUpdate (at least) not working (Using TypeScript)

### ISSUE THREAD

**Issue by relief-melone** [Automattic/mongoose#7760]
**Type**: Bug

**Current Behaviour:**
Using arrayFilters on findOneAndUpdate results in error (code 16837)
> cannot use the part (Wheels of Wheels.$[w].Id) to traverse the element ({Wheels: [ { _id: ObjectId('5cc85e475d23112104afbc02'), Size: "19 inch", Id: "1" }, { _id: ObjectId('5cc85e475d23112104afbc01'), Size: "19 inch", Id: "2" } ]})

**Steps to reproduce**

```typescript
const carSchema = new Schema({
    Make: String,
    Wheels: [{
        Size: String,
        Id: String
    }]
})

const carModel = mongoose.model('car', carSchema);

let created = await carModel.create({
    Make: "BMW",
    Wheels: [{
        Size: "19 inch",
        Id: 1
    }, {
         Size: "19 inch",
         Id: 2
    }]
})

let updated = await carModel.findByIdAndUpdate(created._id, {
    $set: { "Wheels.$[w].Id": 3 }
}, {
    arrayFilters: [{
        "t.id": 2
     }]
} as any)
```

**Expected Behaviour:**
Updating Wheel with Id: 2 to Id: 3 in Document

**Versions**
Node: 8.12.0
Mongoose: 5.5.4
MongoDB: 3.6

Notice that I also have to use Type "any" on the options Object as arrayFilters seems to be missing in @types/mongoose QueryFindOneAndUpdateOptions interface. So I am not 100% sure if this is just a feature that's not supported yet or I am doing something completely wrong, but I guess this is a bug.

**Comment by vkarpov15** [comment]
Your array filter uses `t`, but the `$set` uses `w`, so it looks like your variable names are incorrect. Try `arrayFilters: [{ 'w.Id': 2 }]`.

We don't support @types/mongoose, you'll have to report your issue on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose).
