### ISSUE TITLE
Make async validator docs use `throw`

### ISSUE THREAD

**Issue by zinzinday** [Automattic/mongoose#7761]
How to remove warning `isAsync` was deprecated when custom validation with multiple callback with custom message

(node:8021) DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async validators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators
My abstract example
```ts
MySchema.path('multiplePattern').validate({
isAsync: true,
validator: async function(value, callback){
  let xyz = await connection.model('xyz').findById('xyz').exec();
   if(!conditionRef2XYZ){
     return callback(false, "messageA"),
   }
   if(!condition2Ref2XYZ){
     return callback(false, "messageB"),
   }
   callback(true);
}
})
```
If we remove option `isAsync: true` in validation obj then `callback` function is `undefined`.
Please help to me.
Thanks advanced
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node -v
v8.16.0

"mongoose": "^5.5.4",
"@types/mongoose": "^5.3.27",

**Comment by vkarpov15** [comment]
If you have an async function, you shouldn't be using a callback. Change to:

```javascript
async function(value, callback){
  let xyz = await connection.model('xyz').findById('xyz').exec();
   if(!conditionRef2XYZ){
     return false
   }
   if(!condition2Ref2XYZ){
     return false
   }
   return true
}
```

**Comment by zinzinday** [comment]
@vkarpov15 I want to multiple callback with custom message

**Comment by vkarpov15** [comment]
Fix should be in https://github.com/Automattic/mongoose/commit/9cc3c439f4d0c2b8a37e175cff05ce37257fe31a

**Comment by iliakan** [comment]
not documented yet?

**Comment by iliakan** [comment]
Is that a correct change?

Before:
```js
validator(value, respond) {
    if (!value) return respond(false, 'No value');
    ...
}
```

After:
```js
async validator(value) {
    if (!value) throw new Error('No value');
    ...
}
```

**Comment by vkarpov15** [comment]
@iliakan correct. We'll improve the docs.
