### ISSUE TITLE
bulkWrite session not being set

### ISSUE THREAD

**Issue by saadshahd** [Automattic/mongoose#7769]
I'm trying to access the `bulkWrite` session from the prevalidate hook but It's always `null`

```js
this.bulkWrite(operations, {
  session: await this.startSession()
});
```

in the pre-validate hook `this.$seesion()` should return the session instead it returns `null`

**Comment by Fonger** [comment]
It does use the session to send write request to MongoDB server.
However it's a bug that you can't access it in a pre-validate hook for bulkWrite or insertMany.

**Comment by saadshahd** [comment]
@Fonger  now I could get the session from `this.$__.session` but not from `this.$session`, is that a bug?
