### ISSUE TITLE
add documentation for data seeding

### ISSUE THREAD

**Issue by zhangkaiyulw** [Automattic/mongoose#7773]
Hi,

Some ORMs provide documentation for seeding data e.g. [sequelize](http://docs.sequelizejs.com/manual/migrations.html#creating-first-seed). They also provide seeding feature officially. In mongoose ecosystem, every team has its own ways to seed data and most of them cannot handle references across models easily. And existing seeder tools are hard to use, require user to write a lot of code. Thus few people are using them and those projects are not actively maintained. I want to help people that are struggling on data seeding with mongoose. That's why I created [Seedgoose](https://github.com/zhangkaiyulw/seedgoose).

[Seedgoose](https://github.com/zhangkaiyulw/seedgoose) has a lot of killer features.
### It has a CLI
To seed data into database, just run `seedgoose seed`, `seedgoose reseed` or `seedgoose unseed`. These three commands have different behaviors for overwriting.
### It supports a wide variety of data languages
**Write data in JSON**
``` json
{
  "iphonex": {
    "name": "iPhone X",
    "vendor": "apple"
  },
  "galaxy-note9": {
    "name": "Galaxy Note 9",
    "vendor": "samsung"
  }
}
```
**Write data in YAML**
```yaml
apple:
  name: Apple
galaxy-note9:
  name: Galaxy Note 9
```
### It supports references across model definitions
After seeding the previous files into the database, we actually get
```json
[
  { "_id": "1234567890abcdef12341234", "name": "iPhone X", "vendor": "1234567890abcdef12341236" },
  { "_id": "1234567890abcdef12341235", "name": "Galaxy Note 9", "vendor": "1234567890abcdef12341237" }
]
```
and
```json
[
  { "_id": "1234567890abcdef12341236", "name": "Apple" },
  { "_id": "1234567890abcdef12341237", "name": "Samsung" }
]
```

Even dynamic references inside of array are considered. It supports references linking by reading mongoose schema. 

We may help people who needs data seeding by including `Seedgoose` in README or documentations. What's your opinions on this?

**Comment by vkarpov15** [comment]
Not a bad idea, can you explain a little more how the references support works? https://github.com/zhangkaiyulw/seedgoose#design-concept . How does the content of `authors.json` know to look at `posts.json`?

**Comment by zhangkaiyulw** [comment]
Hi @vkarpov15 ,

Thanks. I've included the internal mechanism used by seedgoose in the [Introduction](https://github.com/zhangkaiyulw/seedgoose#introduction) of the README.

`authors.json` know to look at `posts.json` is because, there is a model called `Author` and a model called `Post`, and in the mongoose schema file, there is something like `author: { type: ObjectId, ref: 'Author' }`.

**Comment by vkarpov15** [comment]
Hmm I'm still not sure I get it. In your example, `_id` is a string. How would that work with `authors.json`, `posts.json`, and `author` as an ObjectId?

**Comment by zhangkaiyulw** [comment]
Hi @vkarpov15, Seedgoose convert this `string` into `ObjectId`. Since Seedgoose traverses the schema, Seedgoose knows what field is supposed to be an `ObjectId`.

**Comment by Fonger** [comment]
It's a good idea to have a seeding tool.

> Since Seedgoose Seedgoose traverses the schema, Seedgoose knows what field is supposed to be an ObjectId.

IMO, Seedgoose should handle not only `ObjectId`, but also [other mongoose supported schema types](https://mongoosejs.com/docs/schematypes.html). Or at least document supported types.

For example, `"2019-05-18T20:11:57.293Z"` with schema type `Date` should be converted to `Date` Type. I tried but seedgoose save the date as `String` in mongodb instead of `Date`.

```js
mongoose.model('Platform', new Schema({ name: String, date: Date }));
```
```json
{
  "windows 10": {
    "name": "Windows 10",
    "date": "2019-05-18T20:11:57.293Z"
  },
  "macOS mojave": {
    "name": "macOS Mojave",
    "date": "2019-05-18T20:11:57.293Z"
  }
}
```

**Comment by zhangkaiyulw** [comment]
Hi @Fonger, you are right. Seedgoose should support type casting.

**Comment by vkarpov15** [comment]
@zhangkaiyulw I'm mostly concerned about whether you have to type out the full ObjectId every time. Your [original example](https://github.com/Automattic/mongoose/issues/7773#issue-441026239) doesn't have ObjectIds, it looks like they're added implicitly?

**Comment by zhangkaiyulw** [comment]
Hi @vkarpov15, we don't need to type 24 digits hex ids. when using array syntax, we need to specify an identifier. when using object syntax, the key is the id identifier. It is saved into another collection, preserves across sessions.

**Comment by vkarpov15** [comment]
@zhangkaiyulw still don't understand. Can you point to the code that does this in seedgoose?

**Comment by zhangkaiyulw** [comment]
Hi @vkarpov15

https://github.com/zhangkaiyulw/seedgoose/blob/db9b21d2f53e88129eef1952de073e777fc5dfa2/lib/getUniqId.js#L1

https://github.com/zhangkaiyulw/seedgoose/blob/db9b21d2f53e88129eef1952de073e777fc5dfa2/lib/seed.js#L37

**Comment by vkarpov15** [comment]
Cool. I'll give seedgoose a shot and see how it works :+1:

**Comment by zhangkaiyulw** [comment]
Hi @vkarpov15 and @Fonger , I'm currently implementing a new feature, for @Fonger's advice on `Date` casting.
