### ISSUE TITLE
CoreMongooseArray in 5.5.6: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ajmas** [Automattic/mongoose#7776]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Running CoreMongooseArray.length creates error `Cannot read property 'length' of undefined` on Mongoose 5.5.6

**If the current behavior is a bug, please provide the steps to reproduce.**

If I run the following code, where 'entry' is an object coming from the database, then I get `Cannot read property 'length' of undefined`:

```
const ratingTypes = ['-2', '-1', '0', '1', '2'];

function processEntry(imageEntry) {
    const ratings = imageEntry.ratings;
    let total = 0;
    for (let i=0; i<=ratingTypes.length; i++) {
        total += ratings[ratingTypes[i]].length;
    }
}
```

The data schema is as follows: 

```
const VoteSchema = new mongoose.Schema( {
});

const ImageSchema = new mongoose.Schema( {
   name: String,
   url: String,
   ratings: {
      '-2': [VoteSchema],
      '-2': [VoteSchema]
      '0': [VoteSchema]
      '1': [VoteSchema]
      '2': [VoteSchema]
   }
});
```

**What is the expected behavior?**

The expected behaviour is to return the length of the array, as did in Mongoose 5.5.2.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**OS:** macOS 10.14.3
**NodeJS:** v10.15.3
**Mongoose:** 5.5.6
**MongoDB:** v4.0.4 (installed via MacPorts)

**Comment by vkarpov15** [comment]
Your code has a couple mistakes and typos. Here's how you fix it:

1) `for (let i=0; i<=ratingTypes.length; i++)` should be `i < ratingTypes.length`. Part of the reason for this error is that `ratingTypes[i]` is undefined for `i = 5`

2) You have `'-2': [VoteSchema]` twice. The 2nd one should be `'-1': [VoteSchema]`. 

Below script works without error:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7776`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const VoteSchema = new mongoose.Schema({});
  const ImageSchema = new mongoose.Schema({
   name: String,
   ratings: {
      '-2': [VoteSchema],
      '-1': [VoteSchema],
      '0': [VoteSchema],
      '1': [VoteSchema],
      '2': [VoteSchema]
   }
  });

  const Image = mongoose.model('Image', ImageSchema);
  const doc = await Image.create({ name: 'foo', ratings: { '-2': {}, '-1': {}, '0': {}, '1': {}, '2': {} } });
  const ratingTypes = ['-2', '-1', '0', '1', '2'];
  function processEntry(imageEntry) {
    const ratings = imageEntry.ratings;
    let total = 0;
    for (let i=0; i<ratingTypes.length; i++) {
        total += ratings[ratingTypes[i]].length;
    }
  }

  processEntry(doc);
}
```
