### ISSUE TITLE
Change the value of a field may not mark it as modified.

### ISSUE THREAD

**Issue by jinCN** [Automattic/mongoose#7779]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Change the value of a field may not mark it as modified.
Useless code can change behavior of modification detection of a document.

**If the current behavior is a bug, please provide the steps to reproduce.**

mo=require('mongoose')
mo.connect('mongodb://localhost:27017/test')
aa=mo.model('aa',new mo.Schema({aa:mo.Mixed}))
kk=new aa({aa:{ a: 1, b: { c: 1 } }})
await kk.save()
kk=await aa.findOne();
console.log(kk.toString())//"{ _id: 5cd29606974a7b09819c53e2,aa: { a: 1, b: { c: 1 } },__v: 0 }"
kk.aa.b={c:2};// this line of code has evil
kk.aa={a:1,b:{c:2}}
kk.save()
kk=await aa.findOne();
console.log(kk.toString())//"{ _id: 5cd29606974a7b09819c53e2,aa: { a: 1, b: { c: 1 } },__v: 0 }"

**What is the expected behavior?**
The document should be changed.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs v8.2.1
mongoose@5.5.6 
MongoDB v4.0.3

**Comment by jinCN** [comment]
I see. Can you introduce how this can be solved by modification detection with ES6 Proxy?

**Comment by Fonger** [comment]
[on-change](https://github.com/sindresorhus/on-change) is a good example

**Comment by vkarpov15** [comment]
For now you need to [explicitly call `markModified()` when you update a subpath of a mixed path](https://mongoosejs.com/docs/schematypes.html#mixed).
