### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#7780]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am trying to perform `findOneAndUpdate` operation and its saying 

```
DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```

The only option while connecting mongodb in `mongoose.connect` function, i am using is `useNewUrlParser: true`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Perform `findOneAndUpdate`

**What is the expected behavior?**
It should not show deprecated warning

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: 10.15.0
Mongoose: 5.5.6
MongoDB: 4.0.6

**Comment by tbhaxor** [comment]
Still the warning

**Code for mongodb connection**

```js
// connecting to db
mongoose
  .connect(dbUrl, {
    useCreateIndex: true,
    useNewUrlParser: true,
    useFindAndModify: true
  })
  .then(() => {
    console.log("Conneted to '%s'", config.db.name);
  })
  .catch(reason => {
    process.stdout.write("Can't Connect to DB : ");
    console.error(reason.message);
    process.exit(1);
  });
```

**Console  Output**
![image](https://user-images.githubusercontent.com/28386721/57476203-abe2f100-72b3-11e9-8712-459f0f0c75b7.png)

**Comment by Fonger** [comment]
`useFindAndModify` should be `false`

```diff
mongoose
  .connect(dbUrl, {
    useCreateIndex: true,
    useNewUrlParser: true,
-    useFindAndModify: true
+    useFindAndModify: false
  })
```

**Comment by tbhaxor** [comment]
@Fonger thanku so much :heart:
