### ISSUE TITLE
Reload model instance

### ISSUE THREAD

**Issue by julesGoullee** [Automattic/mongoose#7781]
I have two model instances of the same document in two different places in my code. One update the document, I want to keep the other instance and refresh for the database the data of it. There is something like  `reload()` or `refresh()` method?

**Comment by Fonger** [comment]
No but you can easily do this via defining a custom [instance model](https://mongoosejs.com/docs/guide.html#methods)

For example,
```js
const animalSchema = new Schema({ name: String });

animalSchema.methods.getLatest = function() {
  return this.model('Animal').findById(this.id);
};

const Animal = mongoose.model('Animal', animalSchema);

async function test() {
  let dog = new Animal({ name: 'dog' });
  await dog.save();
  // get the latest data model
  // note that you have to assign the result to self.
  dog = await dog.getLatest();
}
test();
```

**Comment by vkarpov15** [comment]
Is there any reason why you can't just [`findOne()`](https://mongoosejs.com/docs/api.html#model_Model.findOne) the document? That's effectively the same as reloading the document.

**Comment by raquelhortab** [comment]
> Is there any reason why you can't just [`findOne()`](https://mongoosejs.com/docs/api.html#model_Model.findOne) the document? That's effectively the same as reloading the document.

I'd say that is a bit cumbersome, not very nice when there could be a builtin function that retrieves the info and refreshes the model. Similar to this question, what if I want to reload a pre-populated association, from inside the model? Is there any way to do so? E.g. If I have the model game, which has an array of players and has the field populated, how can I, inside a game method, refresh and get the up-to-date version of the players array?

**Comment by vkarpov15** [comment]
Not built-in, you would have to explicitly `populate()` the path you want to refresh.

**Comment by mickyginger** [comment]
I appreciate this is pretty old, but I've come up with the following solution:

```js
const reloadRecord = function reloadRecord(schema) {
  schema.methods.reload = async function() {
    const record = this.constructor.findById(this); 
    Object.assign(this, record);
    return record;
  }
}

mongoose.plugin(reloadRecord);
```

Now you can use it like so:

```
await user.reload(); // user is now updated
```

**Comment by andreas-bergstrom** [comment]
> I appreciate this is pretty old, but I've come up with the following solution:
> 
> ```js
> const reloadRecord = function reloadRecord(schema) {
>   schema.methods.reload = async function() {
>     const record = this.constructor.findById(this); 
>     Object.assign(this, record);
>     return record;
>   }
> }
> 
> mongoose.plugin(reloadRecord);
> ```
> 
> Now you can use it like so:
> 
> ```js
> await user.reload(); // user is now updated
> ```

You probably want to await this.constructor.findById(this)

**Comment by mickyginger** [comment]
> You probably want to await this.constructor.findById(this)

🤦 

Thanks @andreas-bergstrom , I'll update the snippet 👍

**Comment by julesGoullee** [comment]
Looks nice thx guys
