### ISSUE TITLE
Bug introduced in 5.4.17 won't populate a subdocument with `fill` in the path

### ISSUE THREAD

**Issue by sergei202** [Automattic/mongoose#7782]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The property stays unpopulated

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/sergei202/c59b4cafebbf16ec8bf49d8d93e1d964

Install 5.4.16 and run the script, you will see `parent.list[0].fill.child` populated.
Install a newer version (broken in 5.4.17) and you will only see the ObjectId.

**What is the expected behavior?**
It should be populated regardless of property name.  Renaming the property from `fill` to something like `filling` works.  Just the word `fill` that causes it to break.  Interestingly, it only breaks when its a subdocument.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v10.15.3
MongoDB: 4.0.5
Mongoose: 5.5.6

**Comment by Fonger** [comment]
It's introduced by https://github.com/Automattic/mongoose/commit/f91b4e71a74fbeae06ed879c4b12840026134c13

The `fill` property happens to be `Array.prototype.fill` which resolves to a `function` so the whole population is skipped.

**Comment by sergei202** [comment]
You guys rock, thank you!
