### ISSUE TITLE
model.query is running twice instead of once.

### ISSUE THREAD

**Issue by BloodLetterStudios** [Automattic/mongoose#7788]
**What is the current behavior?**
I am running a query on an event and a model.query seems to be running more than once, and its only on one model, every other model is working as intended. Here is the code for it:
```javascript
socket.on('upgrade-stat', data => {
      const args = {
        id: socket.handshake.session.passport.user
      };
      console.log('Snapshot Start');
      Snapshot.updateOne(
        { userid: args.id },
        {
          $inc: {
            'stats.str': 1
          }
        }
      ).then(res => {
        console.log('Snapshot done');
      });
      console.log('Start increment query');
      User.updateOne(
        { _id: args.id },
        {
          $inc: {
            'currency.cs': 1
          }
        },
        (err, res) => {
          if (err) console.log(err);
        }
      ).then(user => {
        console.log('End increment query');
        return 'It worked';
      });
    });
```

I enabled debugging:
```
Snapshot Start
Start increment query
Mongoose: users.updateOne({ _id: ObjectId("5cd49529b7809f44e48f84ed") }, { '$inc': { 'currency.cs': 1 } }, {})
Mongoose: snapshots.updateOne({ userid: '5cd49529b7809f44e48f84ed' }, { '$inc': { 'stats.str': 1 } }, {})
Mongoose: users.updateOne({ _id: ObjectId("5cd49529b7809f44e48f84ed") }, { '$inc': { 'currency.cs': 1 } }, {})
Snapshot done
End increment query
```

Expected behavior is to only run once.

Node.js version: 11.12.0
Mongoose version: 5.4.19
MongoDB version; 4.0.6

**Comment by Fonger** [comment]
According to the [docs: queries are not promise](https://mongoosejs.com/docs/queries.html#queries-are-not-promises) you shouldn't mix `callback` function and `then()` otherwise it will run twice.

**Comment by BloodLetterStudios** [comment]
It's weird, I did the same to the Snapshot query but it didn't run twice. Maybe its cause I did model.query().then(), while not mixing the callbacks? Would that work without using the .exec method?

Either way, I absolutely need it to do a .then() because it I don't it doesn't return the right information in callbacks. 

Thank you for your help though, it was very informative.
