### ISSUE TITLE
When new object inserted the MongoDB setting null to _id in case of upsert: true. 

### ISSUE THREAD

**Issue by zeeshanaligold** [Automattic/mongoose#7791]
How to fix null value  in _id when new object inserted? It should be unique id. thanks

Voucher.updateOne({ _id: voucherId }, cardDetails, { upsert: true }, (err, voucher) => {
    if (err) return res.json(err)
    res.status(200).json({
      status: 200,
      result: voucher,
    })
  })

**Comment by vkarpov15** [comment]
@zeeshanaligold I don't understand your question, can you please clarify?

**Comment by zeeshanaligold** [comment]
Hi @vkarpov15 
     I want to update document if exists else insert.

**Comment by vkarpov15** [comment]
Set the [`upsert` option to `true` for `updateOne()`](https://mongoosejs.com/docs/api.html#query_Query-updateOne)

**Comment by pate313373** [comment]
Upsert will do the insert, but _id is set to null.
Just like he described.......

**Comment by pate313373** [comment]
> 
> 
> Hi @vkarpov15
> I want to update document if exists else insert.

The point is, what might not be that obvious:
If you run your code, the value of _id will be null, which is indeed a problem.
