### ISSUE TITLE
Prevent adding same Document to Array where only timestamps differ

### ISSUE THREAD

**Issue by Enado95** [Automattic/mongoose#7793]
Is there a way to prevent adding duplicate documents in an array that only have different timestamps with the $addToSet function?

So say i have an array:

    Schools: [
      {
        Name: 'Jack High',
        State: 'DC',
        created: '2019-05-02 11:03:35.344'
      }
    ]

I want to prevent thee addition of : 

    {
        Name: 'Jack High',
        State: 'DC',
        created: '2019-05-05 11:03:35.344'
     }

because it has the same values just different create dates.

Any ideas of how to do this using Express and mongoose

**Comment by vkarpov15** [comment]
@Enado95 unfortunately not with `$addToSet`. [`$addToSet` only skips adding a document if another document in the array is exactly equal](https://docs.mongodb.com/manual/reference/operator/update/addToSet/#value-to-add-is-a-document). You might consider:

1) Separate out `schools` into a separate collection, create a unique index on `{ name: 1, state: 1 }`, and use [populate](https://mongoosejs.com/docs/populate.html).

2) Check for duplicates in Node.js and [explicitly increment the document's version every time](https://mongoosejs.com/docs/api.html#model_Model-increment) so Mongoose will refuse to save if the array changed in the database when you're trying to save.
