### ISSUE TITLE
Document.set fails in 2D nested arrays

### ISSUE THREAD

**Issue by Faibk** [Automattic/mongoose#7799]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When setting a path containing a nested array (of array of schema) using `document.set` the values are not set. Actually it fails silently in line 380 of documentarray.js because of `prev` not having an id function which is correct since the prev is an array as well.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
'use strict';
var assert = require('assert');
var mongoose = require('../../');

describe('nested arrays', function () {
  var Schema = mongoose.Schema;

  it('update array of array of schema', function(done) {
      const subSchema = new Schema({
        title: String
      });

      const nestedSchema = new Schema({
        nested: [[ subSchema ]]
      });

      const Nested = mongoose.model('Nested', nestedSchema);

      let doc = new Nested({nested: [[{title: 'cool'}, {title: 'not cool'}]]});
      assert.equal(doc.nested[0].length, 2);

      //fails
      doc.set({nested: [[{title: 'new'}]]});
      assert.equal(doc.nested[0].length, 1);

      //fails
      doc.nested = [[{title: 'new'}]];
      assert.equal(doc.nested[0].length, 1);

      //works
      doc.nested[0] = [{title: 'new'}];
      assert.equal(doc.nested[0].length, 1);

      done();
    });

});
```

**What is the expected behavior?**
Set the values correctly in the array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.5.8
node 10.15.3
mongodb 3.6.12

**Comment by Fonger** [comment]
Note in your repro code, the working one doesn't work actually when it comes to saving the document. Although it does modify the document in javascript, you can't save it to mongodb because you [directly modify an array document, which is not supported by mongoose](https://mongoosejs.com/docs/faq.html). 

My PR will fix the first 2 cases though.
