### ISSUE TITLE
Model.update setter documentation inaccuracy / misdirection

### ISSUE THREAD

**Issue by natanavra** [Automattic/mongoose#7801]
**Do you want to request a *feature* or report a *bug*?**
documentation inaccuracy / misdirection

**What is the current behavior?**
documentation states `Update` will not apply setters, but setters are run (`this` is the `Query`)
https://mongoosejs.com/docs/api.html#model_Model.update

> Although values are casted to their appropriate types when using update, the following are not applied:
> - defaults
> - setters
> - validators
> - middleware

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const event = new Schema({
  url: {
    type: String,
    required: true,
    set: function(value) {
        this.shortUrl = value.substr(0, 100);
        return value;
    }
  },
  shortUrl: {type: String, maxlength: 100},
  count: {type: Number}
});
mongoose.model('Event', event);

const url = 'https://google.com/' + 'path'.repeat(50);
const shortUrl = url.substr(0, 100);
Event.update(
  {url}, 
  {$setOnInsert: {shortUrl}, $inc: {count: 1}}, 
  {upsert: true}
);
```

**What is the expected behavior?**
Judging from the docs, the `set` function should not run

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 9.6.1
Mongoose 5.0.16 (did not update due to too many deprecation warnings)
MongoDB 4.02

**NOTE**
Just found this comment: https://github.com/Automattic/mongoose/issues/7404#issuecomment-454120358
> **vkarpov15**: the custom set will be called any time shipDate is in the filter or the update

So I'm guessing the behavior changed but not reflected in docs?

**Comment by vkarpov15** [comment]
The docs are incorrect, will fix. Thanks for pointing this out.

My apologies for all the deprecation warnings. [Our deprecation warnings guide](https://mongoosejs.com/docs/deprecations.html) should help you sort those out.
