### ISSUE TITLE
pre 'findOneAndDelete' and deleteMany

### ISSUE THREAD

**Issue by leo-khramtsov** [Automattic/mongoose#7809]
I have a User model and BlogPost model. User model stores an array of blogPosts. I setup a pre 'findOneAndDelete' hook, to deletMany blogPosts associated with the user, using Model.deleteMany, but its not working and blogPosts are not being deleted. User is deleted successfully. There is 1 post in blogPosts array.

Result from deleteMany inside the middleware is as followes
```
await BlogPost.deleteMany({ _id: { $in: this.blogPosts } });
```
result:
```
{ n: 0, ok: 1, deletedCount: 0 }
{ n: 0, ok: 1, deletedCount: 0 }
{ n: 0, ok: 1, deletedCount: 0 }
```

The same pre hook works, if change the hook from 'findOneAndDelete' to 'remove', but 'remove is deprecated.

Any ideas? Is my understanding of using Query middleware wrong here and it cannot be used like this?

"mongoose": "^5.5.8",
Node v12.0.0

**User schema**
```
const UserSchema = new Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    validate: {
      validator(name) {
        if (name.length > 2 && name.length < 10) {
          return true;
        }
        return false;
      },
      message: () => "Name must be between 2 and 10 characters"
    }
  },
  posts: [PostSchema],
  likes: {
    type: Number,
    default: 0
  },
  blogPosts: [
    {
      type: Schema.Types.ObjectId,
      ref: 'blogPost'
    }
  ]
});

UserSchema.pre('findOneAndDelete', async function(next) {
  const BlogPost = mongoose.model("blogPost");
  const res = await BlogPost.deleteMany({ _id: { $in: this.blogPosts } });
  next();
});
```

**BlogPost schema**
```
const BlogPostSchema = new Schema({
  title: String,
  content: String,
  comments: [
    {
      type: Schema.Types.ObjectId,
      ref: 'comment'
    }
  ]
});
```

**Comment by vkarpov15** [comment]
What function are you using to delete the user? If you don't call [`Query#findOneAndDelete()`](https://mongoosejs.com/docs/api.html#query_Query-findOneAndDelete), Mongoose won't call your middleware.
