### ISSUE TITLE
Throw an error if calling `mongoose.connect()` multiple times while connected

### ISSUE THREAD

**Issue by Arp-1** [Automattic/mongoose#7814]
**Do you want to request a *feature* or report a *bug*?**
   Bug
**What is the current behavior?**
    When  a document with a field `username` is updated twice(with another field `token` changed),
    I get a validation error with message  path `username` validation is invalid. Note that it happens alternately.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It shouldn't give any validation error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js v8.10.0 mongoose v5.5.9 mongodb v4.0.9

More detailed issue can be found [here](https://stackoverflow.com/questions/56145471/how-to-fix-mongoose-giving-validation-error-on-alternate-doc-save-execution-w) on stackoverflow.

Thanks!

**Comment by vkarpov15** [comment]
What does `getData()` look like? That isn't in your SO post.

**Comment by Arp-1** [comment]
Thanks @vkarpov15  for taking time to look into the issue!

Here is my getData.js file:

```javascript
module.exports = async function putData(database, model, query, fields, queryType='one'){
    let mongoose = require('mongoose');
    const connectionURL = `mongodb://127.0.0.1:27017/${database}`;
    mongoose.connect(connectionURL, {
        useNewUrlParser: true,
        useCreateIndex: true
    });

    return model.init().then(async ()=>{
        let res;
        switch(queryType){
            case 'one':
                res = await model.findOne(query).select(fields).exec();
                break;
            case 'all':
                res = await model.find(query).select(fields).exec();
        }
        return res;
    })
}
```

**P.S.** : I have also added this file to my [SO question](https://stackoverflow.com/questions/56145471/how-to-fix-mongoose-giving-validation-error-on-alternate-doc-save-execution-w)

**Comment by vkarpov15** [comment]
There's a wide variety of mistakes in this code, but I think the big problem is that you're calling `mongoose.connect()` repeatedly when Mongoose is already connected. There's no need to call `mongoose.connect()` in `getData()` or `putData()`. See [FAQ](https://mongoosejs.com/docs/faq.html#creating_connections)

**Comment by Arp-1** [comment]
Sorry about the late reply, been busy with my academic work.
@vkarpov15 as you mentioned that mongoose.connect() is causing problem, now I am closing the connection after opening it as soon as I am done. But the problem still persists.

**Note**: I have updated my [SO question](https://stackoverflow.com/questions/56145471/how-to-fix-mongoose-giving-validation-error-on-alternate-doc-save-execution-w) according to the new files I have.

**Comment by vkarpov15** [comment]
You're still calling `mongoose.connect()` in `getData()` and `putData()`. Remove that and see if that helps.

**Comment by Arp-1** [comment]
I cannot change those function to connect to a static database as I connect to different database(s) at different times and changing those functions will make it lose the generality of those functions.

However I have written a new small script, which connect to database outside the function and still gives me same validation error.

**script: **

```javascript
let mongoose = require('mongoose');
const connectionURL = `mongodb://127.0.0.1:27017/mockdb`;

async function putData(model, data, save=false){
    return model.init()
    .then(async ()=>{
        let prom;
        if(save){
            prom = await data.save();
        }
        else{
            let doc = new model(data);
            prom = await doc.save();
        }
        return prom;
    })
}

let userSchema = new mongoose.Schema({
    fname: {
        type: String,
        match: /^[A-Za-z]*$/g
    },
    lname: {
        type: String,
        match: /^[A-Za-z]*$/g
    }
})

let userModel = mongoose.model('user', userSchema);

mongoose.connect(connectionURL, {
    useNewUrlParser: true,
    useCreateIndex: true
})
.then(()=>{
    console.log('----Connected----');
    return putData(userModel, new userModel({
        fname: 'Arpit',
        lname: 'Bhadauria'
    }))
})
.then((doc)=>{
    console.log('Created new document');
    doc.fname = 'Shivay';
    console.log(Object.getPrototypeOf(doc).constructor.name);
    return putData(userModel, doc, true);
})
.then(doc => {
    console.log(doc.fname);
    process.exit(0);
})
.catch(err => {
    console.log(err);
    process.exit(0);
})
```

When I am changing *doc.fname* to *Shivay*, I get a validation error.
To make sure that doc is an instance of *model* and not a *plain js object*, I also logged the name of the constructor to terminal, but it logs *model* in the console(Hence no problem there).

Thanks!

**Note**: I have used mongoose v5.6.0 and mongodb v4.0.9 for this script

**Comment by Arp-1** [comment]
@vkarpov15 I tried to track this issue and It turns out that the problem was in the match function shown below:

**lib/schema/string.js**
```javascript
SchemaString.prototype.match = function match(regExp, message) {
  // yes, we allow multiple match validators

  const msg = message || MongooseError.messages.String.match;

  const matchValidator = function(v) {
    if (!regExp) {
      return false;
    }

    const ret = ((v != null && v !== '')
      ? regExp.test(v)
      : true);
    return ret;
  };

  this.validators.push({
    validator: matchValidator,
    message: msg,
    type: 'regexp',
    regexp: regExp
  });
  return this;
};
```

Logging the value of `ret` to the console, I get `true` for all paths when I first create the document. But when I did `doc.fname = 'Shivay';` I get `ret` to be `false`(No Idea why!) for path `fname`. I also logged `v` and `regExp` to the console. But they seem to be fine. Here is the output  with code:

**lib/schema/string.js**
```javascript
SchemaString.prototype.match = function match(regExp, message) {
  // yes, we allow multiple match validators

  const msg = message || MongooseError.messages.String.match;

  const matchValidator = function(v) {
    if (!regExp) {
      return false;
    }

    const ret = ((v != null && v !== '')
      ? regExp.test(v)
      : true);

    console.log(regExp, v, ret);

    return ret;
  };

  this.validators.push({
    validator: matchValidator,
    message: msg,
    type: 'regexp',
    regexp: regExp
  });
  return this;
};
```
**Output:**
![output of the code](https://user-images.githubusercontent.com/37845584/60393736-a11c3e00-9b37-11e9-9c31-c6c8d4d37cb9.png)

Interestingly If I call regExp.test(v) again the code works:

**lib/schema/string.js**
```javascript
SchemaString.prototype.match = function match(regExp, message) {
  // yes, we allow multiple match validators

  const msg = message || MongooseError.messages.String.match;

  const matchValidator = function(v) {
    if (!regExp) {
      return false;
    }

    const ret = ((v != null && v !== '')
      ? regExp.test(v)
      : true);
    regExp.test(v); // This call is doing some magic
    console.log(regExp, v, ret);

    return ret;
  };

  this.validators.push({
    validator: matchValidator,
    message: msg,
    type: 'regexp',
    regexp: regExp
  });
  return this;
};
```

Output: 
![Screenshot 2019-06-30 13:09:51](https://user-images.githubusercontent.com/37845584/60393790-623ab800-9b38-11e9-9394-251c9d2b64e1.png)

Logging `regExp.test(v)` to the console, I came to know that it is always returning **false** and somehow `ret` becomes `true` through that ternary operator(:confused:).

Furthermore, If I remove `g` modifiers from my RegExp(s), the code works without any modification in the above `SchemaString.prototype.match` function.

Also, please reopen the issue since it isn't resolved.

Thanks!

**Comment by vkarpov15** [comment]
@Arp-1 I don't see what your issue has to do with the original issue. The original issue is about calling mongoose.connect() multiple times. Also, can you please post your schema? It looks like you're setting a value that doesn't match the `match` regexp in your schema, which is expected behavior

**Comment by Arp-1** [comment]
I am using the exactly same script as I had posted in one of my above comments. Here it is:

**index.js:**
```javascript
let mongoose = require('./mongoose');
const connectionURL = `mongodb://127.0.0.1:27017/mockdb`;

async function putData(model, data, save=false){
    return model.init()
    .then(async ()=>{
        let prom;
        if(save){
            prom = await data.save();
        }
        else{
            let doc = new model(data);
            prom = await doc.save();
        }
        return prom;
    })
}

let userSchema = new mongoose.Schema({
    fname: {
        type: String,
        match: /^[A-Za-z]*$/g
    },
    lname: {
        type: String,
        match: /^[A-Za-z]*$/g
    }
})

let userModel = mongoose.model('user', userSchema);

mongoose.connect(connectionURL, {
    useNewUrlParser: true,
    useCreateIndex: true
})
.then(async ()=>{
    console.log('----Connected----');
    return putData(userModel, {
        fname: 'Arpit',
        lname: 'Bhadauria'
    });
})
.then((doc)=>{
    console.log('Created new document');
    doc.fname = 'Shivay';
    return putData(userModel, doc, true);
})
.then(doc => {
    console.log(doc.fname);
    process.exit(0);
})
.catch(err => {
    console.log(err);
    process.exit(0);
})
```

And the issue was supposed to be related with calling mongoose.connect() multiple times, but I guess that really wasn't the source of error.

**Comment by vkarpov15** [comment]
@Arp-1 why does `putData()` use `Model.init()`? Also, why are you mixing promise chaining and async/await? There is never any reason to do `.then(async () => { /* ... */ })` unless you're purposely trying to obfuscate your code.
