### ISSUE TITLE
Decimal128 Precision and Scale

### ISSUE THREAD

**Issue by yosbi77** [Automattic/mongoose#7815]
I believe since MongoDB 3.4, there was a new data type introduced which is Decimal. I also know that Mongoose has the Schema Type of Decimal128 to cater the Decimal in MongoDB. Currently, I am using mongoose-float instead of Decimal. They allow us to set the scale. Quoting from mongoose-float:
```
var mongoose = require('mongoose');
var Float = require('mongoose-float').loadType(mongoose, 4);
 
var ProductSchema = mongoose.Schema({ price: { type: Float } });
var Product = mongoose.model('Product', ProductSchema);
 
var product = new Product({ price: 200.222222222 });
 
// Output: product.price = 200.2222
```
The example above set the scale to 4, so the fractional digits would be limited to 4. I would like to set the scale, and also precision if possible, but using Decimal128 from Mongoose (in data modelling, to be precise). I cannot find the way to do it anywhere. Any responses would be very much appreciated.

**Comment by vkarpov15** [comment]
You'd have to use getters and setters to handle this. For example:

```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  x: {
    type: mongoose.Decimal128,
    get: v => new mongoose.Types.Decimal128((+v.toString()).toFixed(4))
  }
});
const Model = mongoose.model('Test', schema);

const doc = new Model({ x: 200.22222222 });

console.log(doc.x); // Decimal128 { _bsontype: 'Decimal128', bytes: '200.2222' }
```

We'll add support for this and similar options for Decimal128 in a future release.

See [my blog post on Decimal128](http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-34-decimal.html).

**Comment by yosbi77** [comment]
Hi Karpov,

Thank you for the reply.

I have made the change in my schema based on your reply. I set the fraction digits in toFixed to 2 like so:
```
x: {
	type: mongoose.Decimal128,
	get: v => new mongoose.Types.Decimal128((+v.toString()).toFixed(2)),
	default: 0
}
```
After the object was created, I did some simple calculations, something like this:
```
x = a / b* 100;
```
It resulted as below:
```
"x": {
    "$numberDecimal": "9.090909090909092"
}
```
I do not mind about the $numberDecimal. It's about the fraction digits, which previously was set to 2. Anything I should do to get the correct result (in this case, 9.09)?

**Comment by vkarpov15** [comment]
@yosbi77 you'll need a custom setter for that:

```javascript
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });

const schema = new mongoose.Schema({
  x: {
    type: mongoose.Decimal128,
    set: v => {
      return new mongoose.Types.Decimal128(v.toFixed(4));
    }
  }
});
const Model = mongoose.model('Test', schema);

const doc = new Model({ x: 200.22222222 });

console.log(doc.x); // Decimal128 { _bsontype: 'Decimal128', bytes: '200.2222' }

doc.save();
```

The custom getter just rounds after the fact, the data stored in MongoDB won't be limited to 2 places after the decimal. With a custom setter, the data in MongoDB will be limited to 2 places after the decimal.

**Comment by yosbi77** [comment]
@vkarpov15 Hi, I added the custom setter like so:
```javascript
x: {
    type: mongoose.Decimal128,
    get: v => new mongoose.Types.Decimal128((+v.toString()).toFixed(2)),
    set: v => new mongoose.Types.Decimal128(v.toFixed(2)),
    default: 0
}
```
Then, I recalculate again, still using the same calculation in my previous reply. And I got this:
```javascript
"x": {
    "$numberDecimal": "1.50994953E-6168"
}
```
Do I have to do something in my calculation? It was just a simple calculation:
```javascript
let a = 0; // later will be incremented
const b = anArray.length;
x = a / b * 100;
```

**Comment by vkarpov15** [comment]
@yosbi77 in this case, you don't need a getter if you have a setter. The setter handles rounding to 2 decimal places, so you don't need a getter to round again. Try removing the getter and it should work.

**Comment by yosbi77** [comment]
@vkarpov15 I removed the getter but the result is still the same.

I have been using Postman as my testing application and all of the results from previous replies were from Postman. So, I printed the console output and the result is as expected. Somehow Postman does not give the same result. Though, when I use mongoose-float, it will return as expected (in Postman).

These are results:
1. mongoose-float
Console output:
```javascript
console.log(doc.x); // 9.09
```
Postman:
```javascript
"x": 9.09
```

2. Using custom getter for Decimal128
Console output:
```javascript
console.log(doc.x); // Decimal128 { _bsontype: 'Decimal128', bytes: '9.09' }
```
Postman:
```javascript
"x": {
    "$numberDecimal": "9.090909090909092"
}
```

3. Using custom setter for Decimal128
Console output:
```javascript
console.log(doc.x); // Decimal128 { _bsontype: 'Decimal128', bytes: '9.09' }
```
Postman:
```javascript
"x": {
    "$numberDecimal": "1.50994953E-6168"
}
```

**Comment by yosbi77** [comment]
@vkarpov15 I made a public repo to reproduce this issue: [https://github.com/yosbi77/repros](url)

I use these:
1. Node.js (10.15.1)
2. MongoDB (4.0.4)
3. Mongoose (5.5.11)
4. Postman (6.7.4)

I use default ports (3000 for application and 27017 for MongoDB). The name of the database is "decimal" and the collection is "as".

The steps to test:
1. Start the DB service with normal "mongod" and the application with "node app.js"
2. These are the following APIs:
    - POST: localhost:3000/a (**create**)
    - GET: localhost:3000/a (**getAll**)
    - GET: localhost:3000/a/submit/:id (**submit**)
3. Create by calling **create** with the body of raw JSON of {"x": 0} (or you can set any other numeric value, since I will do a hard-coded calculation in **submit**)
4. See the stored data by calling **getAll**
5. Do the calculation by calling **submit**
6. See the modified data by either calling **getAll** or in the database ("use decimal" and "db.as.find()")

**Comment by yosbi77** [comment]
@vkarpov15 any update on this?

**Comment by vkarpov15** [comment]
@yosbi77 not yet, will take a look this week.

**Comment by yosbi77** [comment]
@vkarpov15 sure, just let me know if anything comes up.

**Comment by vkarpov15** [comment]
Looks like my setter was incorrect, sorry about that. The MongoDB driver has a separate [`fromString()` helper to instantiate a Decimal128 from a string](http://mongodb.github.io/node-mongodb-native/3.1/api/Decimal128.html).

```javascript
const ASchema = new mongoose.Schema({
  x: {
    type: mongoose.Decimal128,
    set: v => mongoose.Types.Decimal128.fromString(v.toFixed(2)),
    default: 0
  }
});
```

**Comment by yosbi77** [comment]
@vkarpov15 this works.

The Postman gives me this:
```javascript
"x": {
    "$numberDecimal": "81.82"
}
```
And, the data stored in DB like this:
```javascript
"x" : NumberDecimal("81.82")
```

Thank you for helping me through all this.
