### ISSUE TITLE
Sockets are not closed after disconnect in v5.5.x

### ISSUE THREAD

**Issue by stgogm** [Automattic/mongoose#7816]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug.

**What is the current behavior?**
Sockets are not closed when disconnecting.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using Mocha, run a test that connects to the database and add an `after` function that disconnect from the database. The test will not exit automatically and if you use `wtfnode` it'll indicate that some sockets to a mongo database are still open:

```
- Sockets:
  - x.x.x.x:xxxxx -> x.x.x.x:27017
```

This was introduced in version `5.5.x` as version `5.4.23` works as expected.

**What is the expected behavior?**
That all sockets are closed after calling `mongoose.disconnect()`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- **NodeJS:** `v8.16.0`.
- **MongoDB (Atlas):** `v4.0.9`.
- **Mongoose:** `v5.5.9` and `v5.4.23`.

**Comment by vkarpov15** [comment]
Can you provide a more detailed repro script? Specifically, how are you connecting to mongodb? Using `mongoose.connect()` or `mongoose.createConnection()`?

**Comment by stgogm** [comment]
We're using this inside a component in a Lambda function like this:

https://github.com/dotstudio-io/fi-slseed-api/blob/master/service/components/database.js

https://github.com/dotstudio-io/fi-slseed-api/blob/master/service/functions/users/index.js#L15

Then, when running tests, the unexpected behavior happens after calling `mongoose.disconnect()` directly inside a Mocha `after()` function.

**Comment by stgogm** [comment]
After further investigation we detected that this happens when using remote databases, like Atlas.

I've updated the repo to be able to reproduce this behavior:

1. Clone or download the repo from https://github.com/dotstudio-io/fi-slseed-api.
1. Run `npm i` (defaults to `mongoose@5.4.23`).
1. Create a `.env.local` file with the following contents in the project root:
```
NODE_ENV=local
DB_URI=mongodb+srv://user:pass@yourcluster.mongodb.net/dbname?retryWrites=true
```


##### Successful behavior:
1. Install the previous minor Mongoose version with `npm i mongoose@5.4`.
1. Ensure Mongoose version with `npm ls mongoose`.
1. Run a loop of tests with `for i in {1..10}; do npm run test:components; done`
1. All tests will exit automatically.

##### Unsuccessful behavior:
1. Install the latest Mongoose with `npm i mongoose@5.5`.
1. Ensure Mongoose version with `npm ls mongoose`.
1. Run a loop of tests with `for i in {1..10}; do npm run test:components; done`
1. Some tests will randomly fail to exit automatically.

**Comment by vkarpov15** [comment]
I managed to repro this with the MongoDB node driver, I opened up [an issue on the MongoDB driver JIRA page](https://jira.mongodb.org/projects/NODE/issues/NODE-1560?filter=allopenissues).

**Comment by Katafalkas** [comment]
Experiencing the same issue with `Node 10.16.0`
