### ISSUE TITLE
insertMany return blank if all inserted docs is error (duplicated error) but not if one insertable item to return validation error

### ISSUE THREAD

**Issue by eisenhaus335** [Automattic/mongoose#7822]
When i insert docs with everything is duplicated items i got blank response 
its really just give me this response [] (from console.log)

But when i give one something insertable. Its give me this response
```
{
    "result": {
        "ok": 1,
        "n": 1,
        "opTime": {
            "ts": "6693001219876585484",
            "t": 16
        }
    },
    "ops": [
        {
            "_id": "5ce2512c3dfc5d1704812804",
            "sku": "test15",
            "name": "barang",
            "qty": 20,
            "type": "pcs",
            "__v": 0
        }
    ],
    "insertedCount": 1,
    "insertedIds": {
        "0": "5ce2512c3dfc5d1704812804"
    },
    "mongoose": {
        "validationErrors": [
            {
                "errors": {
                    "sku": {
                        "message": "SKU already exists",
                        "name": "ValidatorError",
                        "properties": {
                            "message": "SKU already exists",
                            "type": "user defined",
                            "path": "sku",
                            "value": "test11"
                        },
                        "kind": "user defined",
                        "path": "sku",
                        "value": "test11"
                    }
                },
                "_message": "product validation failed",
                "message": "product validation failed: sku: SKU already exists",
                "name": "ValidationError"
            }
        ]
    }
}
```

```
const Product = require('../models/product')

async function add(ctx, next) {
    await Product.insertMany(ctx.request.body, { ordered: false, rawResult: true })
        .then(function (result) {
            console.log(result)
            ctx.body = {
                ...result
            }
        })
        .catch(function (err) {
            console.log(err)
            ctx.throw(401, 'something is wrong')
        })
}
```
PS: SKU is unique

Node.js: v12.2.0
"mongoose": "^5.5.9"
Mongodb: 4.0.9

**Comment by vkarpov15** [comment]
What does your schema look like? Also, can you please post the custom validator that's reporting the 'SKU already exists' message?

**Comment by eisenhaus335** [comment]
```
ProductSchema.path('sku').validate(async (value) => {
    const SKUCount = await mongoose.models.product.countDocuments({ sku: value });
    return !SKUCount;
}, 'SKU already exists');
```
const CreatedSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.ObjectId,
        ref: 'user'
    },
    time: { type: Date, default: Date.now() }
}, { _id: false })
const QtySchema = new mongoose.Schema({
    location: {
        type: mongoose.Schema.ObjectId,
        ref: 'location'
    },
    value: Number
}, { _id: false })
```
const ProductSchema = new mongoose.Schema({
    sku: {
        type: String,
        index: true,
        unique: true, 
        required: true
    },
    name: String,
    qty: [QtySchema],
    type: String,
    created_by: [CreatedSchema]
})
```
I though this was intended cause you said " but if ordered is not set (true by default) we should fall back to the current behavior."
https://github.com/Automattic/mongoose/pull/5698#pullrequestreview-67874003

**Comment by vkarpov15** [comment]
I'm still not sure I understand the issue here. I'm guessing you have an issue with `insertMany()` throwing a validation error and not inserting any docs if there's a duplicate sku number?

**Comment by Elyx0** [comment]
The problem seem to arise when it hits the quick escape 
```javascript
    // We filter all failed pre-validations by removing nulls
    const docAttributes = docs.filter(function(doc) {
      return doc != null;
    });
    // Quickly escape while there aren't any valid docAttributes
    if (docAttributes.length < 1) {
      callback(null, []);
      return;
    }
```
At this step all the information about the `validationErrors` array defined above are dropped even if the array is not empty but `docs` is. 

I recomment exiting with `res.mongoose` set like a few lines below. This seems like a leftover from https://github.com/Automattic/mongoose/issues/5337 and https://github.com/Automattic/mongoose/issues/6228

**Comment by vkarpov15** [comment]
I'm going to close this issue and lock it, I haven't seen anything even remotely coherent in this thread. Please open up a separate issue with detailed code samples.
