### ISSUE TITLE
[solved][documentation issue] Model.aggregate()

### ISSUE THREAD

**Issue by xxyyzz2050** [Automattic/mongoose#7823]
in the documentation:
If a callback is passed, the aggregate is executed and a Promise is returned. If a callback is not passed, the aggregate itself is returned.

but in the example in the same page, it didn't use a callback, but a promise returned -not an Aggregate- so it could use .then()

```
Users.aggregate([
  { $group: { _id: null, maxBalance: { $max: '$balance' }}},
  { $project: { _id: 0, maxBalance: 1 }}
]).
then(function (res) {
  console.log(res); // [ { maxBalance: 98000 } ]
});

```

is Aggregate itself has .then() method, like promises?

**Comment by Fonger** [comment]
Yes, see [Aggregate#then](https://mongoosejs.com/docs/api.html#aggregate_Aggregate-then)
