### ISSUE TITLE
cors error searching documentation

### ISSUE THREAD

**Issue by Simon-Co** [Automattic/mongoose#7824]
I'm getting a cors error when trying to use the search function at https://mongoosejs.com/docs/search.com - on my larger monitor this function is currently hidden behind an add on the homepage.  

Access to fetch at 'https://8jekzv4pyd.execute-api.us-east-1.amazonaws.com/prod/search?search=test' from origin 'https://mongoosejs.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

also comes with this error messasge cors erropr searchign documentation

**Comment by vkarpov15** [comment]
That's strange, the response from the search backend has an access-control-allow-origin header:

![image](https://user-images.githubusercontent.com/1620265/58432964-f4a3f380-8082-11e9-8e7e-d7491c895f22.png)

[Here's the relevant code](https://github.com/mongoosejs/search/blob/master/index.js#L24).

**Comment by vkarpov15** [comment]
Are you still getting this error? We recently migrated the search backend to a different EC2 box, so it might have somehow been fixed by that...

**Comment by Simon-Co** [comment]
I just checked and it looks like it is working again.
