### ISSUE TITLE
Documentation: Statics described differently in Guide and API

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7827]
From https://mongoosejs.com/docs/guide.html#statics

`animalSchema.statics.findByName = function(name, cb) { ... }`

From https://mongoosejs.com/docs/api.html#schema_Schema-static

`schema.static('findByName', function (name, callback) { ... }`

I am not sure if both are legit or not, but:

1) The Guide documentation should probably show the preferred way, if there is one?
2) The API docs should show both ways?

(Not a huge issue I know, but reading documentation is a beginner makes you wonder about these things)

**Comment by vkarpov15** [comment]
@thernstig these two approaches are equivalent. We'll add a note about this to the statics section about this.
