### ISSUE TITLE
Save array of week days

### ISSUE THREAD

**Issue by bilal68** [Automattic/mongoose#7829]
I am trying to save the start and end time for the whole week.
 working_hours : [
        Monday:{
             start:String,
             end:String
         },
        Tuesday:{
             start:String,
             end:String
         },
    ],
something like this..i am very confuse in building schema.can anyone help me to build suitable schema for my problem.

**Comment by makrandgupta** [comment]
You probably want to store the day of the week in the objects themselves:
```js
working_hours: [{
  day: {
    type: String,
    enum: ['Monday', 'Tuesday', ...],
  },
  start: String,
  end: String,
}]
```

Also this is not an issue with mongoose itself. You should look at resources like tutorials online and go to stackoverflow for questions like these
