### ISSUE TITLE
set() does not overwrite an entire document as documentation says

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7830]
**Do you want to request a *feature* or report a *bug*?**
Documentation bug?

**What is the current behavior?**
According to https://mongoosejs.com/docs/documents.html#overwriting it says:

> You can overwrite an entire document using .set(). This is handy if you want to change what document is being saved in middleware.

As an example:

```javascript
Tank.findById(id, function (err, tank) {
  if (err) return handleError(err);
  // Now `otherTank` is a copy of `tank`
  otherTank.set(tank);
});
```

If otherTank contains some keys that tank does not have, those are retained in the new version of otherTank. As such, the **entire** document is not overwritten, but rather only those paths that both documents contained.

A question tied to this:
What I tried to achieve was to implement a HTTP PUT call where a user supplies just the parts they want in the new document and the rest gets overwritten. I assume the only way to overwrite everything and still get validation is to do a const test = new X() followed by a test.validate() and then a replaceOne() on the old id? The problems with this approach is that version does not increase, and timestamps (if enabled on the schema) replaces createdAt with the timestamp of when the replacement happens. So I am actually confused how to implement a HTTP PUT properly.

**Comment by vkarpov15** [comment]
Thanks for reporting, will look into this issue this week.

**Comment by vkarpov15** [comment]
You're right that the docs are incorrect, we'll fix that. Admittedly this isn't the way we think about HTTP PUT, but you're right we should have support for that approach as well. Here's an example of how I'd recommend overwriting a document while still retaining `createdAt`:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7830`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String, age: Number }, { timestamps: true });
  const Model = mongoose.model('Test', schema);

  await Model.create({ name: 'foo', age: 99 });

  const body = { name: 'bar' };
  await new Promise(resolve => setTimeout(resolve, 1000));

  // Replace `doc` with the contents of `body`
  const doc = await Model.findOne();
  const newDoc = new Model(Object.assign(body, { _id: doc._id, createdAt: doc.createdAt, __v: doc.__v }));
  newDoc.isNew = false;
  await newDoc.save();
}
```

This isn't really documented anywhere and is a bit counterintuitive, so we'll improve our support for overwriting an existing doc while retaining internal data like `__v` and `createdAt`.

Versioning would never get bumped if you're replacing an entire document, it only gets bumped when you use Mongoose array helpers like `push()`, `pull()`, etc.

**Comment by thernstig** [comment]
@vkarpov15 That is very cool, thank you very much. In your example you specify that `__v` should not increase, but would one not consider it a new version? I.e. that it should be bumped like `__v: doc__v +1`.

> Admittedly this isn't the way we think about HTTP PUT

What did you mean specifically there?

**Comment by vkarpov15** [comment]
In my experience, I've usually seen HTTP PUT used as an `updateOne()` rather than a `replaceOne()` - replace the keys specified in the update, don't touch the other ones. However, you're right that strict REST calls for `replaceOne()` semantics rather than `updateOne()`, and Mongoose should have some documented way to support this via `save()`.

Mongoose versioning [is designed to protect against accidentally overwriting array fields when using array update operators](http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html), so if you only use `$set`, there's no need for versioning.

**Comment by thernstig** [comment]
@vkarpov15 I noticed you removed it from the documentation, maybe that is the right solution here. I was thinking that possibly just changing the text instead to mention that it updates just the intersections/overlapping elements.

When using set() and an object as the first element, I've noticed that e.g. if you've set timestamps on the schema and if one do `a.set(b)`, where updatedAt is included in `b`, it still updates the updateAt field. All good here! But, if one also includes the __v in `b`, it does not get updated when saving `a`. Is this intentional?

I assume so, but what is the suggested way to do this then but still update the version? A pre-save hook that updates __v if no matter what, not relying on internal __v updating?

**Comment by vkarpov15** [comment]
Can you please clarify what you mean by "When using set() and an object as the first element, I've noticed that e.g. if you've set timestamps on the schema and if one do a.set(b), where updatedAt is included in b, it still updates the updateAt field. All good here! But, if one also includes the __v in b, it does not get updated when saving a. Is this intentional?" with some code samples?

**Comment by thernstig** [comment]
Ok let's see. When I said "as the first element" I was refering to that the first argument to set() takes both a path or an object, and in my example I was refering to the usage of an object: https://mongoosejs.com/docs/api.html#document_Document-set

Let's say you have `{ timestamps: true }` on the schema. And you want to update existingDoc:

```javascript
const existingDoc = {
  label: 'label 1',
  createdAt: '2019-05-27T08:22:04.478Z',
  updatedAt: '2019-05-27T08:22:04.478Z',
  __v: 0
};

const updates = {
  label: 'label 2',
  createdAt: '2019-05-27T08:22:04.478Z',
  updatedAt: '2019-05-27T08:22:04.478Z',
  __v: 0
};

existingDoc.set(updates);
```

When this is done, it works perfectly if I remove `__v` from `updates`. The timestamp `updatedAt` will get updated even though I included it. But if I include `__v` (as is done in the code above) it fails with `No matching document found for id "5cf681a25b7ead613d8cdc44" version 1 modifiedPaths "prop1, prop2, updatedAt, __v"`.

I was kind of hoping it would ignore `__v` in this scenario as it does with `updatedAt`. The reason why I do this is that we basically create resources in our backend with mongoose and then send the complete output to the frontend. If a property is updated in the frontend, we update that part and send the complete doc back down to the backend and do a mongoose `set()` to overwrite. It works great except for the `__v` part which we have to remove before send it down to the backend.

**Comment by vkarpov15** [comment]
You could just disable versioning if you're having trouble with it: https://mongoosejs.com/docs/guide.html#versionKey . If you're using `set()`, versioning doesn't provide any benefits.

**Comment by thernstig** [comment]
I would have thought using `set()` is the best way to update a document if you want validation. I.e. findOne -> set() -> save().

**Comment by vkarpov15** [comment]
@thernstig [using `save()` is the best way to update the document](https://masteringjs.io/tutorials/mongoose/update), you're right. But Mongoose versioning only kicks in when you modify an array in place using `push()`, `pull()`, etc. If you always overwrite the entire array using `set()`, versioning won't do anything.
