### ISSUE TITLE
Schema Static Method Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by ianjstewart** [Automattic/mongoose#7831]
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
When using a schema static function with "this.findById" the application crashes with the error:

`TypeError: Cannot read property 'paths' of undefined`

This same code is confirmed as working on <=5.5.7, but produces the above error on >=5.5.8
I console.log'd the model.schema.paths directly before the calling line to this.findById and the paths were output.

**If the current behavior is a bug, please provide the steps to reproduce.**
- create a schema+model
- add a static method that calls this.findById
- require the model from another point in the application and call the static function

**What is the expected behavior?**
Expect this to not error and return the query as before.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v9.2.1
Mongoose: 5.5.8
MongoDB: 3.2.3

**Full Error Stack (paths sanitized)**

> TypeError: Cannot read property 'paths' of undefined
at docReducer (/[PATH]/node_modules/mongoose/lib/document.js:2556:49)
at /[PATH]/node_modules/mongoose/lib/document.js:2587:16
at Array.reduce (<anonymous>)
at docReducer (/[PATH]/node_modules/mongoose/lib/document.js:2586:31)
at /[PATH]/node_modules/mongoose/lib/document.js:2595:12
at Array.reduce (<anonymous>)
at model.Document.$__getAllSubdocs (/[PATH]/node_modules/mongoose/lib/document.js:2594:42)
at model.$session (/[PATH]/node_modules/mongoose/lib/document.js:712:26)
at completeMany (/[PATH]/node_modules/mongoose/lib/helpers/query/completeMany.js:45:12)
at cb (/[PATH]/node_modules/mongoose/lib/query.js:1827:9)
at result (/[PATH]/node_modules/mongodb/lib/utils.js:410:17)
at executeCallback (/[PATH]/node_modules/mongodb/lib/utils.js:402:9)
at handleCallback (/[PATH]/node_modules/mongodb/lib/utils.js:128:55)
at cursor.close (/[PATH]/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
at handleCallback (/[PATH]/node_modules/mongodb/lib/utils.js:128:55)
at completeClose (/[PATH]/node_modules/mongodb/lib/cursor.js:898:14)
at Cursor.close (/[PATH]/node_modules/mongodb/lib/cursor.js:917:10)
at cursor._next (/[PATH]/node_modules/mongodb/lib/operations/cursor_ops.js:224:23)
at handleCallback (/[PATH]/node_modules/mongodb-core/lib/cursor.js:204:5)
at _setCursorNotifiedImpl (/[PATH]/node_modules/mongodb-core/lib/cursor.js:426:38)
at self._endSession (/[PATH]/node_modules/mongodb-core/lib/cursor.js:434:46)
at Cursor._endSession (/[PATH]/node_modules/mongodb-core/lib/cursor.js:195:5)
at Cursor._endSession (/[PATH]/node_modules/mongodb/lib/cursor.js:231:59)
at _setCursorNotifiedImpl (/[PATH]/node_modules/mongodb-core/lib/cursor.js:434:17)
at setCursorNotified (/[PATH]/node_modules/mongodb-core/lib/cursor.js:426:3)
at setCursorDeadAndNotified (/[PATH]/node_modules/mongodb-core/lib/cursor.js:419:3)
at nextFunction (/[PATH]/node_modules/mongodb-core/lib/cursor.js:547:5)
at Cursor.next (/[PATH]/node_modules/mongodb-core/lib/cursor.js:766:3)

**Comment by makrandgupta** [comment]
Can you share the code you were trying to use?

**Comment by ianjstewart** [comment]
I will work on a simple re-produceable example as my code has a lot of structure too it and reply.

**Comment by ianjstewart** [comment]
I was able to make a simple nodejs script that will recreate the issue.  In my simplified example I now get `TypeError: Cannot read property '$init' of undefined` but I arrived at this example by tracing through the original issue. I had to delete out a ton of code before getting to that point. 

In my original comment I mentioned that the issue arose from a static method, but from more testing that portion is irrelevant.  The issue happens on any database interaction that comes after a query which involves a nested property named "schema" from what I can tell.

I put the code for the package.json and server.js file at the bottom.

I also tested this by changing "schema" in the model1 definition to anything else and the issue went away so I would guess that's where the issue is coming from.

Please feel free to close or change this issue as the title is not really representative of the issue.  Hope this is helpful.



**instructions**

1. put server.js and package lock in a directory, install dependancies.  
2. run with nodemon 
3. access script with GET http://localhost:9000/
4. first time no errors recieved
5. Manually insert a document into the "model1" collection:
```
{
    "test" : {
        "schema" : "test"
    }
}
```
6. Access script again, should get the error
7. Change dependancy for mongoose to 5.5.7, rerun, will not recieve an error




**server.js**
```
"use strict";
const express             = require('express');
const http                = require('http');
const app                 = express();
const mongoose            = require('mongoose');

// set up mongoose to avoid deprecation warnings
mongoose.Promise = global.Promise;
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);

// test db url
const dbURL = 'mongodb://127.0.0.1/test';

// create 2 models, first model has a nested path named "schema"
const schema1 = new mongoose.Schema({
    test: {
        schema: { type: String },
    },
});
const Model1 = mongoose.model('model1', schema1);

// second model is purely for testing making a second query
const schema2 = new mongoose.Schema({
    test: { type: String, index: true },
});
const Model2 = mongoose.model('model2', schema2);



// Connect to mongoose
new Promise((resolve, reject) => {
    mongoose.connect(dbURL, {}, (err) => {
        if(err) {
            reject(err);
        }
    });

    mongoose.connection.on('error', (err) => reject(err));
    mongoose.connection.on('connected', () => resolve());
    mongoose.connection.on('close', () => {
        mongoose.connection.removeAllListeners();
        resolve();
    });
})
    .then(() => {
        // Declare a router, make a simple test route that does a query to each model
        return new Promise((resolve, reject) => {

            const router = express.Router();

            router.get('/', (req, res, next) => {
                Model1.find({}, (err, tasks) => {
                    Model2.find({}, (err, user) => {
                        if(err) {
                            next(err)
                        } else {
                            res.json({'success' : true})
                        }
                    });
                });
            });


            app.use('/', router);
            http.createServer(app).listen(9000);
            resolve();
        });
    })
    .catch((err) => {
        console.log(err);
    });
```
**package.json**
```
{
    "name": "test_mongo",
    "main": "server.js",
    "scripts": {
        "start:local": "nodemon server"
    },
    "dependencies": {
        "async": "^2.6.2",
        "express": "^4.16.4",
        "mongodb": "^3.2.3",
        "mongoose": "5.5.10"
    },
    "devDependencies": {
        "nodemon": "^1.19.0"
    },
    "engines": {
        "node": ">= 8.0.0",
        "npm": ">= 5"
    }
}

```

**Comment by vkarpov15** [comment]
This is most likely due to the fact this doc has a property named `schema`. Will investigate.

Also, in the future, you can just use this template to generate a repro script. Adding a `package.json`, nodemon, express, etc. just makes repro scripts bloated and harder to read.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `X`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
}
```

**Comment by ianjstewart** [comment]
Sorry about that! I will use that in future if I have to report anything else.
