### ISSUE TITLE
Unable to proper update polymorphic document (discriminator)

### ISSUE THREAD

**Issue by elincognito** [Automattic/mongoose#7833]
Hi what is the proper way to update an document:
Imagine i have the following schema:

```
const UserSchema = new Schema({
  alias: {
    type: String,
    required: true
  },
  email: {
    type: String,
    required: true
  },
  password: {
    type: String,
    required: true
  },
  date: {
    type: Date,
    default: Date.now
  }
});

const User = mongoose.model("users", UserSchema);

const Admin = User.discriminator('Admin', new Schema({
  adminField: String
}));


const Guest = User.discriminator('Guest', new Schema({
  guestField: String
}))
````

And i have saved an admin onto mongo
```
let admin = new Admin({...});
let admin = await admin.save();

```

Later on i want to update it to be a Guest

User.findOneAndUpdate won't work since it will ignore the fields unrelated to User (The guest ones)

and 

Guest.findOneAndUpdate will give out an error `E11000 duplicate key error collection`
my guess is that it isn't finding the admin since its another schema, and then tries to insert a new one with the same ObjectId

Gist to reproduce: https://repl.it/@ArsenioCosta/Updating-a-polymorphic-mongo-document

**Comment by vkarpov15** [comment]
@elincognito try deleting the admin and then recreating it:

```javascript
const data = admin.toObject();
delete data.__t;
const guest = new Guest(data);

await admin.deleteOne();
await guest.save();
```
