### ISSUE TITLE
post middleware return new doc

### ISSUE THREAD

**Issue by Mangosteen-Yang** [Automattic/mongoose#7834]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Currently post middleware in findOneAndUpdate return finded document rather than new document unless set {new: true} in original findOneAndUpdate

**What is the expected behavior?**
Post middleware should return the updated document or allow set {new: true} in middleware option.
It will be better to note this in the document or else it is really easy to dismiss.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 12.0
Mongoose 5.5.11
MongoDB 4.0.9

**Comment by vkarpov15** [comment]
The document in `post('findOneAndUpdate')` is the same as the document that will be returned from `findOneAndUpdate()`, so you need to set `{ new: true }`. Where in the docs would you expect this information to be?
