### ISSUE TITLE
__v versionKey error when using replica sets

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#7835]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It throws version mismatch error

**If the current behavior is a bug, please provide the steps to reproduce.**

```
 No matching document found for id "5ce4048e507c03003591dce8" version 5 modifiedPaths "jobs"
```

my schema to save a list of jobs ids 
```jsx
const Data = new mongoose.Schema({
   jobs: [
      {
        type: String,
        description: 'job ids for this events',
      },
    ],
})
```

This is the code that throws errors when running on replica set

- First find a new data
```jsx
const data = await Data.findOne({
    _id: dataId,
  });
````

- Clear jobs array and save data
```jsx
data.jobs = [];
await data.save();
```

- modify jobs to have the new jobs
```jsx
data.jobs = newJobs.map(j => j.id);
await data.save();
```

it will throw in the second `.save` call

**What is the expected behavior?**
it should not throw mismatch error in this case

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: v5.58
mongo: v4
node: v10.15.0

**Comment by vkarpov15** [comment]
Are those two `save()` calls running in parallel? The below script executes without any errors for me. Please modify it to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7835`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const DataSchema = new mongoose.Schema({
   jobs: [
      {
        type: String,
        description: 'job ids for this events',
      },
    ],
  });

  const Data = mongoose.model('Test', DataSchema);

  await Data.create({ jobs: ['123'] });
  const data = await Data.findOne({});

  data.jobs = [];
  await data.save();

  data.jobs = [{ id: 'abc' }].map(j => j.id);
  await data.save();
}
```

**Comment by sibelius** [comment]
can you test on replica set?

```
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
```

Our connection string is like this

```
mongodb://mongodb1.mongo,mongodb2.mongo,mongodb3.mongo/feedback?replicaSet=rs0&readPreference=primaryPreferred
```

**Comment by vkarpov15** [comment]
Same thing, I started a replica set with run-rs , below script doesn't error out:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7835`;
const connectionString = `mongodb://localhost:27017,localhost:27018,localhost:27019/${GITHUB_ISSUE}?replicaSet=rs&readPreference=primaryPreferred`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const DataSchema = new mongoose.Schema({
   jobs: [
      {
        type: String,
        description: 'job ids for this events',
      },
    ],
  });

  const Data = mongoose.model('Test', DataSchema);

  await Data.create({ jobs: ['123'] });
  const data = await Data.findOne({});

  data.jobs = [];
  await data.save();

  data.jobs = [{ id: 'abc' }].map(j => j.id);
  await data.save();
}
```

I doubt that replica set or standalone makes a difference in this case, unless there was a replica set failover when you're running this code?

Can you confirm whether the above script works for you? If not, can you modify it to demonstrate your issue?

**Comment by sibelius** [comment]
it works well locally, it only fails on our staging/production environment

I'm gonna close now, and reopen if I find more info about it

can we improve the error message?

**Comment by vkarpov15** [comment]
@sibelius I'd love to improve the error message, any suggestions for what we should add to it? Maybe the model name?
