### ISSUE TITLE
Bug`s report 

### ISSUE THREAD

**Issue by IDONTSUDO** [Automattic/mongoose#7841]
** Do you want to request * a function * or report an error *? **

Mistake
![ScreenRecorderProject2](https://user-images.githubusercontent.com/44754773/58396257-8fd1a480-8054-11e9-8abc-85d19c9ab171.gif)

-------------------------------
** What is the current behavior? **
-------------------------------
I am trying to create a new user in my collection. And mongoose. He writes that he created, but he is not in the collection.
-------------------------------
Steps to play are shown in gif.
-------------------------------
This code crashes
https://github.com/IDONTSUDO/CRM/tree/master/server
-------------------------------
** What behavior is expected? **
Creating a new collection
-------------------------------
https://github.com/IDONTSUDO/CRM/tree/master/server
node v12.2.0
hapy
Mongoose 5.0.0
-------------------------------

**Comment by IDONTSUDO** [comment]
endpoint: /newuser/newuser 
requser type:  POST 
input data:
{
    "first_name": "nononon",
    "last_name": "nononon",
    "email": "nononon@nononon.com",
    "password": "nononon",
    "created": "2019-05-27T04:35:15.376Z"
}

**Comment by IDONTSUDO** [comment]
environment: WIN10

**Comment by eisenhaus335** [comment]
can you reupload more HD gif so I can help out. the gif is so pixelated

**Comment by IDONTSUDO** [comment]
I can not download it here.

**Comment by eisenhaus335** [comment]
if you still has the saved GIF try reupload it somewhere else than put the link here so we can look up (imgur maybe?) 

PS: btw i am not mod or anything just passengerby

**Comment by IDONTSUDO** [comment]
Well thank you. It is a pity that you are not moder.

**Comment by IDONTSUDO** [comment]
https://imgur.com/E6jL8cZ gif

**Comment by eisenhaus335** [comment]
try change this on your newuser routes
```
bcrypt.hash(req.payload.password, 10, (err, hash) => {
                  console.log(req.payload.password)
                  console.log('Error Hash: ', err)
                  console.log('Hash', hash)
                  userData.password = hash
                  return User.create(userData)
                    .then(user => {
                      return { status: user.email + ' Registered!' }
                    })
                    .catch(err => {
                      return 'error: ' + err
                    })
                })
```
console.log('Error Hash', err) show this error
```
Error Hash:  Error: data and salt arguments required
    at Object.hash (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\bcrypt\bcrypt.js:138:17)
    at C:\Users\green\Documents\Workarea\CRM-master\server\routes\Manage\NewUserManage.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports.internals.Manager.execute (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\hapi\lib\toolkit.js:35:28)
    at async Object.internals.handler (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\hapi\lib\handler.js:50:20)
    at async exports.execute (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\hapi\lib\handler.js:35:20)
    at async Request._lifecycle (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\hapi\lib\request.js:265:32)
    at async Request._execute (C:\Users\green\Documents\Workarea\CRM-master\server\node_modules\hapi\lib\request.js:170:9)
```
this mean either data or salt argument is required (other word its undefined).
So i do the console.log(req.payload.password) and its show req.payload.password is undefined. thats why its showing that error


Btw make habit to always show the promise error. like this
```
bcrypt.hash(req.payload.password, 10, (err, hash) => {
                  if(err) console.log(err)
````
so you will know what goes wrong immediatly

**Comment by eisenhaus335** [comment]
![image](https://user-images.githubusercontent.com/25275731/58400286-d0e1ad00-8084-11e9-834a-983409635b58.png)
try this and its should do the jobs. its seems the server parse the body and not the params

**Comment by eisenhaus335** [comment]
I am not sure wth is happened but somehow user.create create document into collection at 'orders'. I am impressed you managed to make that error.
try change User.create into Users.create. i looked the code twice and never looked User so i wonder why the heck the code is not failing instead its inserting document into collection 'orders'.
In short you mistype the User with Users

**Comment by eisenhaus335** [comment]
I just realize the errors after seeing the folder models
Lookup into file Orders.js at line 24
`module.exports = User = mongoose.model('orders', TaskSchema)`

You should change it to Order cause you already 'module.exports' ing at User.js

if you lookup into User.js you module.exports = user too so its get replaced by that order

**Comment by IDONTSUDO** [comment]
Thx!
