### ISSUE TITLE
'upsert' / 'findsert' on find

### ISSUE THREAD

**Issue by sebjwallace** [Automattic/mongoose#7849]
*feature*

If a document with existing values already exists then I would like to return it, else I would like to create a new document with the query values. Singleton document.

With update operations we have the opportunity to insert if the document does not exist. The same idea goes here but for find operations. It would be good to have something like:

`Model.findOne( { name }, { upsert: true } )`

For now I use something like `Model.findOneAndUpdate( { name }, {}, { upsert: true } )`

**Comment by vkarpov15** [comment]
That's exactly what `findOneAndUpdate()` with `upsert` does. I'm not sure I understand the benefit of having a separate `findsert()` if `findOneAndUpdate()` already does that...

**Comment by sebjwallace** [comment]
I'm concerned about semantics. findOneAndUpdate tells the person reading the code that you

**Comment by vkarpov15** [comment]
See our [`findOneAndUpdate()` tutorial](https://mongoosejs.com/docs/tutorials/findoneandupdate.html) for more info :+1:
