### ISSUE TITLE
mongoose.connect() - unpredictable rejection

### ISSUE THREAD

**Issue by avasuro** [Automattic/mongoose#7850]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
mongoose.connect() returns promise, which should be rejected (or should call passed callback with error passed in first argument) on connection failed, and resolved (or should call passed callback without error passed in first argument) on connection established. But this logic works improperly if there is 'error' event handler assigned (in that case promise will never be rejected, or error will not be passed inside callback)

**steps to reproduce:**
```javascript
mongoose.connect().then(
    () => { console.log('Doing something that can be done only when connection is established...'); },
    (e) => { console.log('Doing something that can be done only when failed to connect to DB...'); }
)

// If you uncomment the following - promise will never be rejected, 
// so error handler will never be called, and success handler will always be called:

/* 
mongoose.connection.on('error', () => 
    console.log('Error thrown, but promise will not be rejected');
)); 
*/
```

**What is the expected behavior?**
OR promise should be always rejected/resolved properly, regardless of presence of 'error' event listener, OR remove promise response at all to prevent developers for writing potentially buggy, unstable and unpredictable code.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node.js: 11.4.0
mongoose: 5.5.11

**Comment by tomyitav** [comment]
Hi, I am also getting unexpected results connecting with mongoose@5.5.11 on my macbook pro. (NodeJS v12.1.0)
The Promise returned by connect
```javascript
Mongoose.connect(`mongodb://${urls}/${name}?ssl=true&replicaSet=${replicaName}&authSource=admin`, options)
        .then((res) => {
          console.log('Connected to db...')
          resolve(res)
        })
        .catch((err) => {
          console.error('Got error in connecting- ', err)
          reject(err)
        })`
`
```

Is neither resolved or rejected. It works perfectly fine on v5.4.23

**Comment by vkarpov15** [comment]
@avasuro the below code works fine for me when connecting to a mongodb server that's down, the promise rejects as expected:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7850`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true }).then(
    () => { console.log('Doing something that can be done only when connection is established...'); },
    (e) => { console.log('Doing something that can be done only when failed to connect to DB...'); }
  )
  
  mongoose.connection.on('error', () => console.log('Error thrown, but promise will not be rejected')); 
}
```

@tomyitav please provide some more information. What result do you expect? Is the MongoDB instance that you're connecting to actually running? Is it configured to accept SSL connections?

**Comment by avasuro** [comment]
@vkarpov15 

Because "error" listener is set after connection established (because of `await mongoose.connect(...`.

Move `mongoose.connection.on('error', ...` outside the "run" function or place it before `await mongoose.connect(...`
