### ISSUE TITLE
insertMany does not respect discriminator when using optional key

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7851]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using a discriminator child model with the third argument (the optional key), it is then not possible to do a parent.insertMany with discriminator value set to the same as the optional key. It will instead create the document against the parent schema only, dropping the other properties.

**If the current behavior is a bug, please provide the steps to reproduce.**
Consider that kind is a discriminator key. The kind will not be respected when having set 'child' as the optional key.

```javascript
await Test.insertMany([
    {
        title: 'Title 1',
        __t: 'child',
        label: 'label 1'
    }
]);

const TestChild= Test.discriminator(
  'TestChild',
  testChildSchema,
  'child'
);
```

**What is the expected behavior?**
For the child schema properties/values to be inserted into the created document(s)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Moongose 5.5.2
Mongodb 3.6.3
Node.js 10.13.0

**Comment by thernstig** [comment]
Actually it does not seem to work for a normal const parent = new Parent() followed by parent.save() either.

**Comment by thernstig** [comment]
Oh and most likely a separate issue, but https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts does not account for the third parameter to discriminator()

**Comment by vkarpov15** [comment]
Thanks for reporting, will investigate.

We do not support @types/mongoose, so you'll have to open up an issue on DefinitelyTyped for that.
