### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by radcapitalist** [Automattic/mongoose#7853]
Hey,

I was under the impression that a node.js module should not be tagged as MIT-licensed if it has dependencies that have a more restrictive license, such as the dreaded GPL.  At the very least, I am under the impression that it is impolite.

Mongoose claims to be MIT-licensed, but it depends on MongoDB, which sports a GPL license.

Is that really an OK thing to do?

Thanks!

Eric

**Comment by vkarpov15** [comment]
I'll preface this with the fact that I'm not a lawyer or any sort of legal expert, and I won't make any official comments on this matter without consulting legal counsel.

However, some unofficial thoughts: Mongoose only interacts with MongoDB via the [MongoDB Node.js driver](https://www.npmjs.com/package/mongodb), which is Apache 2 licensed and compatible with the MIT license. Furthermore, it is possible to run Mongoose without MongoDB, Mongoose doesn't depend on MongoDB in the same way that it depends on node modules like mquery.
