### ISSUE TITLE
Connection error to MongoDB Atlas

### ISSUE THREAD

**Issue by vadim-96** [Automattic/mongoose#7854]
I want to report a bug:
Configuration: Windows 7 x86, Node 12.3.1 x86, Mongoose 5.5.11, MongoDB Atlas 4.0.9.
I have this error in my app when I try to start the app:

> Error: querySrv EBADRESP _mongodb._tcp.cluster0-wuhae.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19) {
  errno: 'EBADRESP',
  code: 'EBADRESP',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.cluster0-wuhae.mongodb.net'
}

The code:
```
.connect(
    'mongodb+srv://user:password@cluster0-wuhae.mongodb.net/',
    { dbName: 'shop', useNewUrlParser: true },
  )
```
If I replace the connection string to an older string, then it works fine:

`mongodb://user:password@cluster0-shard-00-00-wuhae.mongodb.net:27017,cluster0-shard-00-01-wuhae.mongodb.net:27017,cluster0-shard-00-02-wuhae.mongodb.net:27017/shop?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true`

BUT, on Windows 10 x64, Node 12.3.1 x64, Mongoose 5.5.11, MongoDB Atlas 4.0.9, with the new connection method (**mongodb+srv://**) the mongoose successfully connected!

**Comment by vkarpov15** [comment]
I'm not sure what the issue is here but it sounds like an issue with Node.js dns on Windows 7. Do you get this error consistently on Windows 7 or is it intermittent?

**Comment by vadim-96** [comment]
> I'm not sure what the issue is here but it sounds like an issue with Node.js dns on Windows 7.
Yes I guess. I've checked my DNS address and set the address to 8.8.8.8. After that, the error was gone.
