### ISSUE TITLE
Implementing MongoDB views

### ISSUE THREAD

**Issue by BusbyActual** [Automattic/mongoose#7855]
**Do you want to request a *feature* or report a *bug*?**
bug / clarification

**What is the current behavior?**
Mongoose appears to be creating a collection however it doesn't behave as a view. No data is returned from requests. I followed a [related #5694](https://github.com/Automattic/mongoose/issues/5694) issue and follow [this](https://stackoverflow.com/questions/51544962/mongoose-querying-views) with little success.

**If the current behavior is a bug, please provide the steps to reproduce.**

         // OR mongoose.connection.db.createView
      mongoose.connection.db.createCollection('myViewNames', {  viewOn: 'runtime',  pipeline: [ 
        { 
          $group: {
           _id:  { channel: "$channel", connection: "$connection", deviceUniqueId: "$deviceUniqueId", month: { $month: "$date" }, day: { $dayOfMonth: "$date" }, year: { $year: "$date" } },
           count: {
             $sum: 1
           },
           formula: {
             $avg: "formula"
           }
        }
       }])
   
    module.exports.runtimeView = mongoose.model('myviewname', runtimeSchema);
    // OR module.exports.runtimeView = mongoose.model('myViewName', runtimeSchema);
   
    runtimeView.find().then((data) => {
         console.log(data, '%%');
    });

**What is the expected behavior?**
Mongoose should create a [view](http://www.mongoing.com/docs/reference/method/db.createView.html) and when querying the view it should return the aggregate values. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

"Node":  "8.2.1"
"Mongoose": "^5.5.11"
"MongoDB":  "3.6.2"

**Comment by BusbyActual** [comment]
Since mongoose makes the views plural changing the target resolves the issue
`viewOn: 'runtime' `
to
`viewOn: 'runtimes'`

**Comment by BusbyActual** [comment]
I'm still at an impasse for the proper way to query the view. 
`
    const runtimeSchema = new Schema({

  deviceUniqueId: { type: String }, 
  date: { type: Date, default: () => Date.now() },
  formula: { type: String, max: 100 },
  connection: { type: Number },
  channel: { type: Number },

}, { usePushEach: true });
module.exports.runtime = mongoose.model('runtime', runtimeSchema);
runtimeSchema.index({ 'date': 1, 'deviceUniqueId': 1, 'channel': 1, 'connection': 1 });

// const runtimeViewSchema
module.exports.runtimeView = mongoose.model('runtime', runtimeSchema);
`

`
runtimeView.find().then((data) => {
     console.log(data, '%%');
});
`

**Comment by vkarpov15** [comment]
In your [last comment](https://github.com/Automattic/mongoose/issues/7855#issuecomment-497837298), `runtimeView` isn't defined when you do `runtimeView.find()`.

You're also adding indexes to your schema after compiling your model. That won't work.

Here's a working example of creating and querying a view with Mongoose:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7855`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', new Schema({ name: String }));
  await Model.create({ name: 'foo' });

  await mongoose.connection.db.createCollection('testview', {
    viewOn: 'tests',
    pipeline: [
      { $group: { _id: '$name', count: { $sum: 1 } } }
    ]
  });

  const ViewModel = await mongoose.model('TestView', new Schema({ _id: String, count: Number }), 'testview');

  console.log(await ViewModel.findOne());
}
```
