### ISSUE TITLE
how to get raw value after specify getter

### ISSUE THREAD

**Issue by GeniusBrother** [Automattic/mongoose#7858]
const schema = new mongoose.Schema({
    name: {type: String, get: v => 'getter name'}
})
const Model = mongoose.model("Model", schema);

let model = new Model({name: "original name"})

console.log(model.name)    // getter name

What should I do if I want to get `original name`?

Thank you for your answer！

**Comment by vkarpov15** [comment]
`model.get('name', null, { getters: false })` or `model.toObject({ getters: false }).name`

**Comment by vkarpov15** [comment]
See [`Document#get()`](https://mongoosejs.com/docs/api.html#document_Document-get) and [`Document#toObject()`](https://mongoosejs.com/docs/api.html#document_Document-toObject)

**Comment by GeniusBrother** [comment]
thank you @vkarpov15 I may have missed the options. I am very sorry to bother you because of this low level problem.

**Comment by vkarpov15** [comment]
No worries, happy to help :+1:
