### ISSUE TITLE
Schema Map not properly validating/casting value type

### ISSUE THREAD

**Issue by JustaFrank** [Automattic/mongoose#7859]
**What is the current behavior?**

If I create a schema containing a `Map` of another schema, the type casting and validation does not seem to be working correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const userSchema = new mongoose.Schema({
  modules: {
    type: Map,
    of: {
      isRequired: {
        type: String,
        required: true
      },
      hasDefault: {
        type: String,
        default: "test"
      }
    }
  }
})

const User = model('User', userSchema)

// Successfully creates user
User.create({ modules: { example: { /* missing isRequired and hasDefault property */ } } })
```

**What is the expected behavior?**

Throw an error as a result of missing `isRequired` and fill in `hasDefault` to be `"test"`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: 12.3.1
Mongoose: 5.5.12
MongoDB: Atlas

**Comment by JustaFrank** [comment]
The solution is to nest schemas:
```
const userSchema = new mongoose.Schema({
  modules: {
    type: Map,
    of: {
      new mongoose.Schema({
        isRequired: {
          type: String,
          required: true
        },
        hasDefault: {
          type: String,
          default: "test"
        }
      })
    }
  }
})
```

**Comment by Fonger** [comment]
@vkarpov15 In Mongoose Map schema, `of` should be one of the valid value of `type`.

Like in normal schema, `type: { xxx: x }` is actually interpreted as `Mixed` type so `of: { xxx: x }` should be interpreted as Mixed type too.

If we really want to support this, I think #7181 will cover this issue and need to be discussed.
