### ISSUE TITLE
Validation failure when updating sub-document fields

### ISSUE THREAD

**Issue by DavidCaabeiro** [Automattic/mongoose#7862]
I have the following schema:

```
const profileSchema = new mongoose.Schema({
    firstname: { type: String },
    lastname: { type: String },
  });

const userSchema = new mongoose.Schema({
    userId: { type: String, required: true, unique: true },
    category: {
      type: String,
      required: true,
      enum: [
        CATEGORY_GOLD,
        CATEGORY_SILVER,
      ],
      default: CATEGORY_GOLD
    },
    email: { type: String, required: true },
    profile: profileSchema,
  },
  {
    timestamps: true,
    toJSON: { virtuals: true }
  });
```
and an API endpoint doing a partial update (PATCH):
```
    const response = await User.updateOne(
      { userId },
      { "profile.firstname": "John" },
      { runValidators: true }
    );
```
When doing so I'm getting the following exception:
```
{
    "errors": {
        "category": {
            "message": "Path `category` is required.",
            "name": "ValidatorError",
            "properties": {
                "message": "Path `category` is required.",
                "type": "required",
                "path": "category"
            },
            "kind": "required",
            "path": "category"
        }
    },
    "_message": "Validation failed",
    "message": "Validation failed: category: Path `category` is required.",
    "name": "ValidationError"
}
```

If I include the `category` field in the updateOne() call above, it works as expected. 

This seems to go against what's stated [here](https://mongoosejs.com/docs/validation.html#update-validators-only-run-on-updated-paths)

Expected behaviour: the code above should validate instead of throwing an error.

Mongoose version: 5.5.12
Node version: 10.1.0

**Comment by DavidCaabeiro** [comment]
Turns out the issue was related for not using the `omitUndefined` option. The object passed to the updateOne() call was marshaled like this:

```
    const obj = {
      category: get(body, 'category'),
      'profile.firstname': get(body, 'profile.firstname'),
      'profile.lastname': get(body, 'profile.lastname'),
    };
```

This way, passing just a single field (for example "firstname") to the PATCH call would generate the following object:
```
{
  category: undefined,
  firstname: "John",
  lastname: undefined,
}
```
but without the `omitUndefined` option set, the undefined fields would be converted to `null`, thus making the validation fail.

**Comment by vkarpov15** [comment]
Here's some more info on [`omitUndefined` in the API docs](https://mongoosejs.com/docs/api.html#query_Query-updateOne)
