### ISSUE TITLE
Can i find or write an Objectid property with string?

### ISSUE THREAD

**Issue by snowdream** [Automattic/mongoose#7863]
For example,
GongsiSchema.add(
    {
        yewuyuanid: Schema.Types.ObjectId
    }

when i find or save as string,
find({yewuyuanid: "5cdf72283da29c570dff4436")

yewuyuanid = "5cdf72283da29c570dff4436"
save(yewuyuanid)

My question is :
can the string be auto converted to ObjectId("5cdf72283da29c570dff4436"), when i try to find or save?

**Comment by vkarpov15** [comment]
Yes, as long as your schema specifies that `yewuyuanid` is an ObjectId.
