### ISSUE TITLE
Documentation: Mongoose errors API missing information about how to get an error instance

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7867]
https://mongoosejs.com/docs/api.html#Error

I noticed that the only way to get an mongoose error instance is to do the following:

`err instanceof mongoose.Error.ValidationError`

Unfortunately I could not find this documented anywhere in the mongoose API. The above API just says it is "MongoError.X" which I could not find out how to use.

Also is there no way to reach the normal MongoError via an import for mongoose? Because I found nothing in the documentation.

**Comment by vkarpov15** [comment]
Re: normal MongoError, `mongoose.mongo.MongoError` should work. You're right re: the docs, will fix that.
