### ISSUE TITLE
Document method name collisions

### ISSUE THREAD

**Issue by kelbongoo** [Automattic/mongoose#7869]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
It's too easy to end up with property name collisions with internal mongoose methods, and this leads to bugs which are very difficult to track down.
Example below: 'getValue', but I have been through this before and I forget what the other names were :(

**If the current behavior is a bug, please provide the steps to reproduce.**

    const schema = new mongoose.schema({ foo: { type: String, required: true } })
    const myClass = class { 
        constructor(data){
            Object.assign(this, data)
        }

        getValue(){
            console.log('evil collision')
        }
    }
    
    schema.loadClass(myClass)
    const model = new mongoose.model('Foo', schema, 'foo')

    await model.create({ foo: 'foo test' }) // error - field 'foo' is required

-> There is an internal function 'getValue' attached to the new 'document' before the validation step and also before the class methods are attached via schema.loadClass(). So my class method 'getValue' overrides this function and thus breaks the validation step.

**What is the expected behavior?**
It should validate the new document's fields correctly.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 8, mongoose 5.4.19

Internal names, particularly commonly used ones like 'getValue', should be underscored if used internally and if a collision is possible.

**Comment by vkarpov15** [comment]
@kelbongoo we have a list of reserved words that can't be schema properties [here](https://github.com/Automattic/mongoose/blob/94292e6c107cbe7f99c48133d529c55a20a04c51/lib/schema.js#L450-L515).

For example, creating a schema with a property 'save'` will throw an error: `new Schema({ save: String })`. Looks like we missed a spot with `getValue()` though, thanks for pointing that out.

**Comment by Xenya0815** [comment]
Hi,
I have an question depending on the changes for that bug fix.

I used the `getValue` function to get the raw value of the property without calling the getters. I know that the `getValue` (or now `__getValue`) is an private method which should not be used but I haven't found a better way.
What is the preferred way to get explicitly the raw value of a property?

**Comment by vkarpov15** [comment]
@Xenya0815 `doc.get(path, null, { getters: false })`, see [`Document#get()` API docs](https://mongoosejs.com/docs/api/document.html#document_Document-get)

**Comment by Xenya0815** [comment]
How it was possible that I overlooked it? I only knew the second param. Perhaps I overlooked it perhaps it is not supported at the typescript declarations.

Thanks for the answer.

**Comment by vkarpov15** [comment]
@Xenya0815 that was a [new feature in 5.5.0](https://github.com/Automattic/mongoose/blob/master/History.md#550--2019-04-08), so perhaps the typescript definitions haven't caught up yet.
