### ISSUE TITLE
Perform actions when initiating reconnection attempts

### ISSUE THREAD

**Issue by andr01d-1** [Automattic/mongoose#7872]
Hello, thanks for taking time to answer the questions. I understand that `mongoose.connect` should only be called once per application lifecycle. 

However we have a use-case that we would like to be notified when every reconnection try starts instead of reconnection succeed. According to doc, there is no available event that we could listen to, since `connecting` event only be emitted once per `mongoose.connect`.

Something we contemplate to do is
```
mongoose.connection.on('disconnected', () => {
       // do other stuff while trying to reconnect to mongo. 
      setTimeout(() => {
         mongoose.connect(mongo_uri)
      }, 60000)
})

Is there a canonical way to achieve above functionality? 

Thank you.

**Comment by vkarpov15** [comment]
Why are you explicitly reconnecting? [Mongoose automatically reconnects for you](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html).

Also, why does the 'disconnected' event not work for your use case?

**Comment by andr01d-1** [comment]
Hi @vkarpov15 , 

What we are trying to achieved is when mongoose automatically reconnecting, we would like to be notified for some or each of reconnecting requests.

Thank you.

**Comment by vkarpov15** [comment]
Re: discussion in https://github.com/mongodb-js/mongodb-core/pull/445, the underlying MongoDB driver will not support this behavior because they're in the process of making some major changes to connection events. We'll put the 'attemptReconnect' event in for now, but just be aware that this event will most likely go away in Mongoose 6.0.

**Comment by andr01d-1** [comment]
Thanks for updating the issue. We will actively test it upon library changes.
