### ISSUE TITLE
A schema path setter run after an update $push has an undefined 'this'

### ISSUE THREAD

**Issue by brettkiefer** [Automattic/mongoose#7876]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**

A schema path setter run after an update involving $push has 'this' undefined. This is a change in behavior starting with d8e46e1846f1ee4dad721a761cd72443526392b0.

```
'use strict';

/* eslint-disable no-console */

const mongoose = require('.');

const SSchema = new mongoose.Schema({ f1: String });
const MSchema = new mongoose.Schema({ s: { type: [SSchema] } });

MSchema.path('s').set(function(val) {
  // Does not throw in Mongoose 5.4.23
  if (!this) throw new Error('No this!');
  return val;
});

mongoose.model('M', MSchema);
mongoose.connect('mongodb://mongodb:27017/test-mongoose', {
  useNewUrlParser: true,
});

(async () => {
  const M = mongoose.model('M');
  const m = await M.create({ s: [{ f1: 'first' }] });
  await M.updateOne({ _id: m._id }, { $push: { s: { f1: 'second' } } });
  mongoose.connection.close();
})();
```

Prior to d8e46e1846f1ee4dad721a761cd72443526392b0, the script succeeds silently. After d8e46e1846f1ee4dad721a761cd72443526392b0, it throws.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Reproduces with Node v10.14.0 and Mongoose 5.5.13.

**Comment by brettkiefer** [comment]
I see that the issue here is that we're running the setters at all, but they seem like they ought to have 'this' set to the model.

**Comment by Fonger** [comment]
@brettkiefer 
> I see that the change here is that we're running the setters at all, but they seem like they ought to have 'this' set to the model in this context as in others.

I've fixed this in my PR. However, this may be Query or Document type here according to [this docs](https://mongoosejs.com/docs/api.html#schematype_SchemaType-set), `this` of setters in mongoose v5 may be Document or Query depending on actions.
  > You can also use setters to modify other properties on the document. If you're setting a property name on a document, the setter will run with this as the document. Be careful, in mongoose 5 setters will also run when querying by name with this as the query.
  > 
  > ```js
  > const nameSchema = new Schema({ name: String, keywords: [String] });
  > nameSchema.path('name').set(function(v) {
  >   // Need to check if `this` is a document, because in mongoose 5
  >   // setters will also run on queries, in which case `this` will be a
  >   // mongoose query object.
  >   if (this instanceof Document && v != null) {
  >     this.keywords = v.split(' ');
  >   }
  >   return v;
  > });
  > ```

**Comment by brettkiefer** [comment]
@Fonger Thank you for the fix, and for pointing that out in the docs; I would have hit that problem next.
