### ISSUE TITLE
how to dynamic adjust connection pool size

### ISSUE THREAD

**Issue by GeniusBrother** [Automattic/mongoose#7879]
For example Set to 5 when the server is idle, and set to 10 when high concurrent.

like this maxPoolSize and minPoolSize
https://docs.mongodb.com/manual/reference/connection-string/

**Comment by vkarpov15** [comment]
The MongoDB driver actually grows/shrinks the connection pool under the hood based on utilization, [`poolSize` is actually a maximum](https://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/). Also, there's no real reason to shrink the connection pool when the server is idle, unused connections have minimal impact on server performance as far as I know.
