### ISSUE TITLE
Feature Request - Default Session

### ISSUE THREAD

**Issue by abettke** [Automattic/mongoose#7881]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently, to perform CRUD operations within a transaction in mongoose you need to manually create a session by calling `startSession` either on mongoose or the model and then save that reference which can be passed to further calls like `find` or `create`. Example:
```
const session = await mongoose.startSession();
const TestModel = mongoose.model('testModel');

session.startTransaction();

// these instances will be rolled-back on abort because a session was passed
const notPersisted = await TestModel.create([{field: 'value'}], { session });
const notPersisted2 = await TestModel.create([{field: 'value'}], { session });
const notPersisted3 = await TestModel.create([{field: 'value'}], { session });
const notPersisted4 = await TestModel.create([{field: 'value'}], { session });
const notPersisted5 = await TestModel.create([{field: 'value'}], { session });

// these instances will persist because session was not passed
const persisted = await TestModel.create([{field: 'value'}]);

await session.abortTransaction();

const count = await TestModel.countDocuments();
console.log(count); // 1
```

**What is the expected behavior?**
It would be nice to have a way to define a default session that all mongoose operations will use if no session is passed during an operation call. It becomes quite tedious to always need to create a session and pass it to each individual operation to specify it needs to be tracked in the transaction. Example:
```
mongoose.set('defaultSession', await mongoose.startSession());
mongoose.defaultSession.startTransaction();

const TestModel = mongoose.model('testModel');

// Each call below will internally leverage the default session since one exists and a session
// was not passed. 
const notPersisted = await TestModel.create([{field: 'value'}]);
const notPersisted2 = await TestModel.create([{field: 'value'}]);
const notPersisted3 = await TestModel.create([{field: 'value'}]);
const notPersisted4 = await TestModel.create([{field: 'value'}]);
const notPersisted5 = await TestModel.create([{field: 'value'}]);

await mongoose.defaultSession.abortTransaction();

const count = await TestModel.countDocuments();
console.log(count); // 0
```

**Comment by vkarpov15** [comment]
I don't think a global session is viable, because you can only have one transaction per session at a time. That means if you have one global session, you'll get an error if you have two simultaneous requests.

**Comment by DenisPalchuk** [comment]
At this case it will be great to get a model from session ```sesionWithTransaction.getModel()``` or add a method to model for adding session by default ```model.setSession(sesionWithTransaction)```

**Comment by vkarpov15** [comment]
Sessions are tied to connections, not models, so there's no way to map 1 session to 1 model.

If you want to map a session 1-to-1 to a model, you may consider using a [Map](https://masteringjs.io/tutorials/fundamentals/map) to map models to sessions.

```javascript
const m = new Map();
m.set(mongoose.model('testModel'), await mongoose.startSession());
```
