### ISSUE TITLE
schema.eachPath with subdocument return a lot of data

### ISSUE THREAD

**Issue by klaveren** [Automattic/mongoose#7883]
Hello friends,
I'm using mongoose 5.5.13 with node v11.1.0.

So I'm trying to get schematype directlly from my model, and am experiencing a problem when the field in question is a subdocument. When I find one subdocument field, this returns thousands of rows of information about this submodel.

1. Firstly, I would like to understand why this returned object is incredibly large, its normal? this works this way? How can I make it better?

2. Secondly, I need to get only the 'paths' of this object returned. So, is there another way to get a schematype for the subdocuments model? The 'paths' object works fine for me, but one problem with that is that my terminal still takes a few secounds to process, and the response time has been very slow.

model.js

```
const configureCrudChildFields = new Schema({
  configure_crud_child_field_pathname: {
    type: String,
    required: true,
    default: ''
  })

const configureCrudFields = new Schema({
  configure_crud_field_pathname: {
    type: String,
    required: true,
    default: ''
  })

const configureCrud = new Schema({
  configure_crud_path: {
    type: String,
    required: true,
    default: ''
  },
  configure_crud_title: {
    type: String,
    default: ''
  },
  configure_crud_subtitle: {
    type: String,
    default: ''
  },
  configure_crud_fields: [configureCrudFields],
  configure_crud_child_fields: [configureCrudChildFields]
})
```

response.js

```
const Database = require(`./model.js`)
Database.schema.eachPath((pathname, schematype) => {
  console.log('pathname:', pathname, schematype ) // if pathname === configure_crud_fields || pathname === configure_crud_fields I'll print a lot of data.
})

```

**Comment by vkarpov15** [comment]
1) Yes, this is normal. Why is it a problem?

2) Can you please clarify? What do you mean by "the 'paths' of this object returned" and "response time is very slow"?
