### ISSUE TITLE
run validators not working for array of objects

### ISSUE THREAD

**Issue by siddisking** [Automattic/mongoose#7886]
**1.  Before creating an issue please make sure you are using the latest version of mongoose** 
Can't update to the latest version of MongoDB right now as there is a chance of code breakage

**2. Do you want to request a feature or report a bug?**
 Bug

**3. What is the current behavior?**
I have a complex schema which has an array of objects like this

```
var log = new Schema({
  myField: [
    {
      keyOne: {
        type: Number,
        required: true
      },
      keyTwo: {
        type: String,
        required: true
      }
    }
   ]
});
```

When I save this validation does occur but when I update it using $set it doesn't perform validation for either key.

here is the code for saving

```
const keys = [{keyOne:123}]

log.update(
      { user_id: userId },
      { $set: keys },
      {runValidators:true}
    );
```
it saves with missing key "keyTwo"

**If the current behavior is a bug, please provide the steps to reproduce.**

**4 What is the expected behavior?**
It should not save as I am passing runValidators true

**5 What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node : v10.16.0
Mongoose: ^4.13.17,
MongoDB: ^2.2.19

**Comment by vkarpov15** [comment]
I can confirm the below script correctly throws an error for all Mongoose versions since 5.3.0. Please upgrade to at least 5.3.0 to fix this issue :+1:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7886`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const logSchema = new Schema({
    myField: [{
      keyOne: {
        type: Number,
        required: true
      },
      keyTwo: {
        type: String,
        required: true
      }
    }]
  });
  const Log = mongoose.model('Test', logSchema);

  await Log.updateOne({}, { myField: [{ keyOne: 1 }] }, { runValidators: true });
}
```
