### ISSUE TITLE
Hook to collection creation

### ISSUE THREAD

**Issue by abouroubi** [Automattic/mongoose#7893]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
I want to execute some custom commands on collection creation.
Is there a way to hook to or to override the automatic collection creation by mongoose ?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
By default, Mongoose doesn't create collections automatically unless you [enable `autoCreate`](https://mongoosejs.com/docs/guide.html#autoCreate). MongoDB automatically creates collections though.

We can add middleware for `Model.createCollection()`, so you could do `schema.pre('createCollection')`. Would that help?

**Comment by abouroubi** [comment]
That would be helpful yes, thank you.

Will it be possible to override the creation process or just add pre creation commands ?

**Comment by vkarpov15** [comment]
@abouroubi just add pre and post creation commands. Is that enough for your use case?

**Comment by FortesJos** [comment]
We'd love to see a `schema.pre('createCollection')`-hook (or `connection.pre('createCollection')`.) As far as I can see it hasn't been implemented currently

**Comment by FortesJos** [comment]
The use case is preventing (accidental) creation of new collections.

**Comment by vkarpov15** [comment]
The problem is that, if you attempt to insert a document into a nonexistent collection, MongoDB will create the collection automatically. So there's no good way to prevent accidentally deleting a collection in all cases. Would that be a deal breaker for you?

**Comment by FortesJos** [comment]
That is not an issue. We'll be using it to stop running the app initially. When inserting would be an issue later on, these can be caught via the usual hooks.
