### ISSUE TITLE
connect-mongo causes DeprecationWarning: collection.ensureIndex 

### ISSUE THREAD

**Issue by jeremyml** [Automattic/mongoose#7896]
**EDIT**: I updated the title after resolved to reflect the ultimate cause, hoping this will help index for searches.

**Original below:**

I am using Mongoose 5.5.5, but I am not benefiting from the bugfix referenced near the end of [ticket 6890](https://github.com/Automattic/mongoose/issues/6890) which is supposed to resolve the deprecation warning for ensureIndex.  My mongo connection:

```
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect(mongoConnStr, {
    useNewUrlParser: true,
    useCreateIndex: true, 
    useFindAndModify: false });
```
I do export models, but I don't want to put the `mongoose.set('useCreateIndex', true);` in every route file.  Instead I want to put `mongoose.set('useCreateIndex', true);` only once in the application.

This collaborator [said I could use a global config](https://github.com/Automattic/mongoose/issues/6890#issuecomment-418694010) now, but it's not working for me.

**Comment by vkarpov15** [comment]
Do you create models before or after calling `mongoose.set('useCreateIndex', true)`? https://mongoosejs.com/docs/deprecations.html#ensureindex . I've seen a few cases where people still get the warning because they call `mongoose.model()` a couple times before calling `mongoose.set()`.

**Comment by jeremyml** [comment]
I create models after calling `mongoose.set('useCreateIndex', true)`.  I tried moving `mongoose.set('useCreateIndex', true)` very early in the app code, but I still get the DeprecationWarning.

**Comment by vkarpov15** [comment]
@jeremyml can you provide a code sample that demonstrates this issue?

**Comment by jeremyml** [comment]
Node runs file named `www `below, and `www` requires `app.js` in the fist line.  File `app.js` immediately calls `mongoose.connect()`.

**www**
```
#!/usr/bin/env node
const app = require('../app.js');
```

**app.js**

```
const path = require('path');
global.appRootPath = __dirname.replace(/\\/g,'/');
const credentials = require(global.appRootPath + '/credentials.js');
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
const mongodbUserPass = credentials.mongodb.username ?
	credentials.mongodb.username + ':' + credentials.mongodb.password + '@' : '';
mongoose.set('useCreateIndex', true)
const mongoConnStr = 'mongodb://' + mongodbUserPass + credentials.mongodb.hostname +
          '/' + credentials.mongodb.dbName;
mongoose.connect(mongoConnStr, 
       {useNewUrlParser: true, useCreateIndex: true, useFindAndModify: false });
// ... more lines to app.js below...
```

This results in the error message:

`(node:17) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

**Comment by jeremyml** [comment]
I isolated the cause of the deprecation warning to the 6 lines which make up the command `app.use(session({...});` inside `app.js`.

Node runs file named `www `below, and `www` requires `app.js` in the fist line.  File `app.js` immediately calls `mongoose.connect()`.

The call `app.use(session({...});` below triggers the deprecation warning.  When I comment out the 6 lines for `app.use(session({...});`, then the deprecation warning goes away.

**www**
```
#!/usr/bin/env node
const app = require('../app.js');
```

**app.js**

```
const path = require('path');
global.appRootPath = __dirname.replace(/\\/g,'/');
const credentials = require(global.appRootPath + '/credentials.js');
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
const mongodbUserPass = credentials.mongodb.username ?
	credentials.mongodb.username + ':' + credentials.mongodb.password + '@' : '';
mongoose.set('useCreateIndex', true)
const mongoConnStr = 'mongodb://' + mongodbUserPass + credentials.mongodb.hostname +
          '/' + credentials.mongodb.dbName;
mongoose.connect(mongoConnStr, 
       {useNewUrlParser: true, useCreateIndex: true, useFindAndModify: false });
	   
// ... skip some lines to app.js below...

const MongoStore = require('connect-mongo')(session);
app.use(session({
	secret: credentials.sessionSecret,
	store: new MongoStore(mongoStoreOptions),
	resave: false,
	saveUninitialized: false
}));
```

This results in the error message:

`(node:17) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

**Comment by jeremyml** [comment]
I isolated the cause of the deprecation warning to the 6 lines which make up the command `app.use(session({...});` inside `app.js`.

Node runs file named `www `below, and `www` requires `app.js` in the fist line.  File `app.js` immediately calls `mongoose.connect()`.

The call `app.use(session({...});` below triggers the deprecation warning.  When I comment out the 6 lines for `app.use(session({...});`, then the deprecation warning goes away.

**www**
```
#!/usr/bin/env node
const app = require('../app.js');
```

**app.js**

```
const path = require('path');
global.appRootPath = __dirname.replace(/\\/g,'/');
const credentials = require(global.appRootPath + '/credentials.js');
const mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
const mongodbUserPass = credentials.mongodb.username ?
	credentials.mongodb.username + ':' + credentials.mongodb.password + '@' : '';
mongoose.set('useCreateIndex', true)
const mongoConnStr = 'mongodb://' + mongodbUserPass + credentials.mongodb.hostname +
          '/' + credentials.mongodb.dbName;
mongoose.connect(mongoConnStr, 
       {useNewUrlParser: true, useCreateIndex: true, useFindAndModify: false });
	   
// ... skip some lines to app.js below...

const session = require('express-session');
const MongoStore = require('connect-mongo')(session);
app.use(session({
	secret: credentials.sessionSecret,
	store: new MongoStore(mongoStoreOptions),
	resave: false,
	saveUninitialized: false
}));
```

This results in the error message:

`(node:17) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

**Comment by vkarpov15** [comment]
@jeremyml what are `mongoStoreOptions` in your example? It might be that `create-mongo` is using `ensureIndex()`, not Mongoose.

You might want to try using [connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session) instead of connect-mongo.

**Comment by jeremyml** [comment]
Ok, I'll try connect-mongodb-session to see if the deprecation warning does away.

To answer your question, these are the options.
```
const mongoStoreOptions = { // session cookie options
	mongooseConnection: mongoose.connection,
	ttl: 3600 * 24 * 14, // = 2 week session cookie lifespan
	collection: 'userSession',
	stringify: false,
	touchAfter: 1 * 3600, // time period in seconds.  Lazily update session with this much time between intervals.
};
```

**Comment by vkarpov15** [comment]
Also, what version of connect-mongo? I seem to remember older versions of connect-mongo creating their own separate connection...

**Comment by jeremyml** [comment]
I was using connect-mongo `v1.3.2`, and when I changed to connect-mongodb-session `v2.2.0` the DeprecationWarning for collection.ensureIndex no longer appeared.  So that solved it, thanks!

Perhaps the older version of connect-mongo contributed to the problem.  In any case, I'll probably switch to connect-mongodb-session because you are the contributor.  Anything special to know about switching?

**Comment by jeremyml** [comment]
I switched to connect-mongodb-session v2.2.0 and no problems, working great.

**Comment by vkarpov15** [comment]
Great :+1:
