### ISSUE TITLE
Find Documents By Ref Object ID Does Not Work

### ISSUE THREAD

**Issue by janschmutz** [Automattic/mongoose#7901]
Hey there. So I encountered some problems retrieving mongoose Objects by their Ref ID.

I have two Schemas, User and Company:
```javascript
const UserSchema = new mongoose.Schema({
    _createdAt: Date,
    company: {type: mongoose.Schema.Types.ObjectId, ref: 'company'},
    email: String,
});

const CompanySchema = new mongoose.Schema({
    _createdAt: {
        type: Date,
        required: true
    },
    name: {
        type: String,
        required: true
    }
});

const userModel = mongoose.model("user", UserSchema, "user");
const companyModel = mongoose.model("company", CompanySchema, "company");
```
I would now like to query for a specific User by his Company _id, but for some reason this is not working, it returns an empty array even though I have a user with the exact company ObjectId in my Database.

```javascript
userModel.find({company: "5cfa4352ffc1c8135d8276a4"}) 
         .exec((err, user) => {
             console.log(user);
         }
//same Problem for {company: mongoose.Types.ObjectId('5cfa4352ffc1c8135d8276a4')}
```
In my mongo shell the command
```
db.user.find({company: "5cfa4352ffc1c8135d8276a4"})
```
returns the users as expected so why does this not work in mongoose? Thanks in advance

**Comment by Fonger** [comment]
Hi, are you sure your `company` is saved as `ObjectId` type?
If you can find the document in mongo shell, it means it's saved as `String` type.

In mongoose, if you define the schema with ObjectId,
the query will be automatically cast into ObjectId type.
So if the `company` is a String, it won't work.

```sh
// mongo shell
db.user.find({company: "5cfa4352ffc1c8135d8276a4"}) //company is String
db.user.find({company: ObjectId("5cfa4352ffc1c8135d8276a4")}) // company is ObjectId

```

**Comment by vkarpov15** [comment]
@Fonger is right, it looks like `company` is a string, not an ObjectId, in your database. Do `company: {type: String, ref: 'company' }` instead and it should work

**Comment by janschmutz** [comment]
Thanks for the Help, that solved it for me!
