### ISSUE TITLE
OverwriteModelError: Cannot overwrite `....` model once compiled.

### ISSUE THREAD

**Issue by Raycoms** [Automattic/mongoose#7904]
**Do you want to request a *feature* or report a *bug*?**
Either it's a bug, or I need the feature:

**What is the current behavior?**

I have different models.
- Company
- Product

And these models have sub-schemas with the sub types (discriminator based):

- Company:
- Google Subsidiary
....

- Product:
- Google Product
....

In these cases I set the discriminator of both to type: 'google'.

Nonetheless, this failed to compile.

`OverwriteModelError: Cannot overwrite `google` model once compiled.`

**What is the expected behavior?**

I would like to be able to have subclasses of different models with the same type discriminator.

Versions:
Node: 10.8.0
Mongoose: 5.5.15,
MongoDB 4.0.10 Enterprise

**Comment by vkarpov15** [comment]
The way we'd recommend doing this is to prefix the discriminator name with the model name, for example:

```javascript
Company.discriminator('Company:google', googleCompanySchema, 'google');
Product.discriminator('Product:google', googleProductSchema, 'google');
```

The [3rd param to `Model.discriminator()`](https://mongoosejs.com/docs/api/model.html#model_Model.discriminator) is the value of the discriminator key, so you can still create models with `{ __t: 'google' }`, just a slightly different model name to avoid conflicts. Let me know if this helps or if you have more questions :+1:

**Comment by Raycoms** [comment]
That helps thanks =)
