### ISSUE TITLE
Mismatch between mongoose.connect() documentation and implementation

### ISSUE THREAD

**Issue by joebowbeer** [Automattic/mongoose#7906]
The specifications of the returned Promise do not agree with each other or with the implementation.

The documentation and implementation below indicate that connect() returns a Promise that resolves to Mongoose:

https://github.com/Automattic/mongoose/blob/master/docs/api/mongoose.html#L83

https://github.com/Automattic/mongoose/blob/master/lib/index.js#L284

While the documentation below indicates that connect() returns a Promise that resolves to undefined:

https://mongoosejs.com/docs/migrating_to_5.html#promises-and-callbacks

https://mongoosejs.com/docs/connections.html

**Comment by Fonger** [comment]
> The specifications of the returned Promise do not agree with each other or with the implementation.
> 
> The documentation and implementation below indicate that connect() returns a Promise that resolves to Mongoose:
> 
> https://github.com/Automattic/mongoose/blob/master/docs/api/mongoose.html#L83
> 
> https://github.com/Automattic/mongoose/blob/master/lib/index.js#L284
> 
> While the documentation below indicates that connect() returns a Promise that resolves to undefined:
This is a migration guide from v4 to v5. It used to return mongoose singleton directly in mongoose v4.
The documentation just says it returns a promise, not a promise resolves to undefined. If a callback is specified, it returns `null`. 

> 
> https://mongoosejs.com/docs/migrating_to_5.html#promises-and-callbacks
> 
> https://mongoosejs.com/docs/connections.html

**Comment by joebowbeerxealth** [comment]
The second doc link says the promise resolves to undefined:

```
// Or using promises
mongoose.connect(uri, options).then(
  () => { /** ready to use. The `mongoose.connect()` promise resolves to undefined. */ },
  err => { /** handle initial connection error */ }
);
```

**Comment by joebowbeer** [comment]
The second doc link says the promise resolves to undefined:

```
// Or using promises
mongoose.connect(uri, options).then(
  () => { /** ready to use. The `mongoose.connect()` promise resolves to undefined. */ },
  err => { /** handle initial connection error */ }
);
```

**Comment by Fonger** [comment]
Yeah you're right. This should be fixed
