### ISSUE TITLE
Documentation: setting _id to false works

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#7910]
Setting `_id: false` works the same way as disabling it via the Schema options like so https://mongoosejs.com/docs/guide.html#_id

Is setting _id to false a supported way of doing this that is undocumented, or is it a hack that one should not use?

**Comment by vkarpov15** [comment]
You can use `_id: false` and we support it because it has unfortunately become a pervasive meme that's too widely used to remove, see #7558. However, I'd rather not document it and actively discourage people from using it, because it's a pattern that doesn't generalize to other schema options.
