### ISSUE TITLE
Mongoose schema hook recieve data from express.js controller

### ISSUE THREAD

**Issue by yiperean** [Automattic/mongoose#7915]
Please is there anyway you can help me with this issue.

I want to get a variable which is inside express.js controller into the schema in order to perform some operation on the variable and result of the operation inside the schema. Example below

express.js

	userschema.full_name = fullName;
	userschema.other_fields = other_details;

	var variableName = 'inside the controller';

	schema2 = new schema(req.body);
	schema1.save(function (err, result){
	});

schema1.js

	var schema1 = mongoose.Schema({
	    full_name: String,
	    other_fields : String//etc
	})

	schema1.pre('save', function(){
	    var fullName = this.full_name;
	    var otherFields = this.other_fields;

	    //get variableName which is inside the controller
	    //but is not a field in schema1

	    //perform operation inside schema and compare 
	    //result with controller variableName
	})

How can I get variableName which is inside the controller but is not a field in schema1 perform operation inside schema and compare result with the controller variableName.
I could not see anything inside the documentation that points to this. Please

**Comment by vkarpov15** [comment]
Pass the variable as an option to save.

```javascript
schema.pre('save', function(next, options) {
  options.variableName; // 'variableValue'
});

await doc.save({ variableName: 'variableValue' });
```

**Comment by yiperean** [comment]
thank you very much. Very useful.
However I do not want to use await. Is there a danger not using await

**Comment by vkarpov15** [comment]
Nope, you can use callbacks as well 

```javascript
doc.save({ variableName: 'variableValue' }, function(err) { /* ... */ })
```
