### ISSUE TITLE
OverwriteModelError: Cannot overwrite `textBlock` model once compiled. on require().

### ISSUE THREAD

**Issue by jblevins1991** [Automattic/mongoose#7918]
**Do you want to request a *feature* or report a *bug*?**

Help, as i'm sure I am doing something incorrectly.

**What is the current behavior?**

When I start my server, I recieve an OverwriteModelError: Cannot overwrite `textBlock` model once compiled error message.

**What is the expected behavior?**

When I start my server, I expect it to start without the OverwriteModelError message.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

I am using Mongoose 5.6.0, Node 11.3.0, and npm 6.7.0.

Here is the mongoose model file.

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const textBlock = new Schema({
    dateCreated: {
        type: Date,
        default: Date.now(),
        required: true
    },
    lastUpdated: {
        type: Date,
        default: Date.now(),
        required: true
    },
    tag: {
        type: String,
        enum: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'small', 'strong', 'b', 'i'],
        default: 'h1',
        required: true
    },
    content: {
        type: String,
        default: '',
        required: true
    }
});

module.exports = mongoose.model('textBlock', textBlock);
```

If I add the `delete mongoose.connection.models['textBlock'];` the model no longer has this issue. The error actually is triggered when I use a require() on the model's file.

**Comment by vkarpov15** [comment]
Can you show how you're requiring the file? This error shouldn't happen because `require()` caches the included file, so your `mongoose.model()` call should only execute once.

**Comment by jblevins1991** [comment]
I can. 

`const textBlock = require('../../models/textBlock');`

If I change the file at any point what does `require()` do with the cached file? Is it invalidated?

**Comment by vkarpov15** [comment]
What does the stack trace look like?

And what do you mean by "change the file"? Do you have something like nodemon that restarts the process if the file changes?

**Comment by jblevins1991** [comment]
Sorry, let me clarify what my question was.

I was wondering if there was an older version of the model cached somewhere. I am using nodemon, but can't quite understand why I would get this error. I should also let you know that I am using mlab for my sandboxed database.

**Comment by vkarpov15** [comment]
Can you clarify which version of nodemon? I'm not sure if nodemon does some sort of smart reloading, or just restarts the entire process. If it restarts the entire process then you shouldn't be getting this error, but if it does something more sophisticated then there might be an old version of the model.

Also, are you running this through a test runner like Mocha, or is this code just run through nodemon?

**Comment by jblevins1991** [comment]
That is an excellent question. Here is my entire `package.json` file.

```
{
  "name": "blog-api",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon src/index.js",
    "lint": "eslint src/*.js",
    "fix": "eslint src/*.js --fix",
    "test": "mocha ./test --recursive",
    "debug": "nodemon --inspect ./src/index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "dotenv": "^8.0.0",
    "express": "^4.17.1",
    "express-winston": "^3.1.0",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^5.6.0",
    "winston": "^3.2.1"
  },
  "devDependencies": {
    "@babel/preset-stage-1": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "concurrently": "^4.1.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-babel": "^5.3.0",
    "mocha": "^6.1.4",
    "nodemon": "^1.19.1",
    "supertest": "^4.0.2"
  }
}
```
I am not running mocha when I recieve this error. It also occurs when I run `npm run  start` for the first time too.

**Comment by vkarpov15** [comment]
I notice you've got some babel dependencies. Are you transpiling your code?

**Comment by jblevins1991** [comment]
I am not. That is only there to run eslint on the entire project.

**Comment by vkarpov15** [comment]
Can you try running your script without nodemon and see if you still get this error? Also, what do you use concurrently for?

I tried running your script via nodemon:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const textBlock = new Schema({
    dateCreated: {
        type: Date,
        default: Date.now(),
        required: true
    },
    lastUpdated: {
        type: Date,
        default: Date.now(),
        required: true
    },
    tag: {
        type: String,
        enum: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'small', 'strong', 'b', 'i'],
        default: 'h1',
        required: true
    },
    content: {
        type: String,
        default: '',
        required: true
    }
});

module.exports = mongoose.model('textBlock', textBlock);
```

And then requiring this file in a separate file:

```javascript
require('./gh-7918');
```

Running this via nodemon doesn't throw any errors, even when I make changes:

```
$ ./node_modules/.bin/nodemon ./gh-7918-index.js 
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./gh-7918-index.js`
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node ./gh-7918-index.js`
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node ./gh-7918-index.js`
[nodemon] clean exit - waiting for changes before restart

```

**Comment by jblevins1991** [comment]
Here is the repository. Maybe having the full project's code may be helpful. I know it's me doing something wrong somewhere.

https://github.com/jblevins1991/joshuablevins

**Comment by jblevins1991** [comment]
I can create a repro script sometime this weekend. I will just work on implementing lerna the rest of the way and then use that to automate bootstrapping everything.

**Comment by vkarpov15** [comment]
Hmm the link you gave doesn't seem to work: https://github.com/jblevins1991/joshuablevins. Can you please provide a link to the actual project?
