### ISSUE TITLE
E11000 duplicate key error collection : error while streaming the excel and saving that in the MongoDB using mongoose as ODM

### ISSUE THREAD

**Issue by shreyansh-goyal** [Automattic/mongoose#7922]
I am facing a issue.I am a streaming a excel with a unique key attribute named CA_Number.While storing the data I am getting the error of duplicate key despite all of them are unique.
my model schema is looked as follows

****************************************************************************************************************
var reportArray= new tpddlReportSchema({
    CA_Number:{type:Number,required:true,unique:true},
})
module.exports = mongoose.model("tpddl",reportArray);
*****************************************************************************************************************

my function which is parsing and storing the excel is looking as follows:-

***********************************************************************************************
app.get('/readTheExcel',(req,res)=>{
    readXlsxFile(fs.createReadStream('./user.xlsx')).then((rows) => {
        for(i in rows)
        {
            if(rows[i][0]=="CA_NUMBER")
            {
             ;   
            }
            else{
                var CA_Details = new TPDDL_REPORTS({ 
                    CA_Number:rows[i][0]
                })
                CA_Details.save((err,doc)=>{
                    if(err)
                    {
                        console.log(err);
                    }
                })
            }
        }
    })  
***************************************************************************************************************

my excel is having all unique field I am not having a slight clue what is happening.

**Comment by vkarpov15** [comment]
Is there already data in the database when you start running your script?

You might want to take a look at [this tutorial about debugging E11000 errors in Mongoose](https://masteringjs.io/tutorials/mongoose/e11000-duplicate-key)

**Comment by shreyansh-goyal** [comment]
No I already try that by dropping the collection but the error was same.

**Comment by vkarpov15** [comment]
What does your duplicate key error message look like?

**Comment by shreyansh-goyal** [comment]
MongoError: E11000 duplicate key error collection: tpddlUserReports.tpddls index: CA_Number_1 dup key: { : 1300 }
    at Function.create (/home/shreyansh/Videos/angular_complete/tpddlReportGeneratorNodeFile/node_modules/mongodb-core/lib/error.js:43:12)
    at toError (/home/shreyansh/Videos/angular_complete/tpddlReportGeneratorNodeFile/node_modules/mongodb/lib/utils.js:149:22)
    at /home/shreyansh/Videos/angular_complete/tpddlReportGeneratorNodeFile/node_modules/mongodb/lib/operations/collection_ops.js:859:39
    at /home/shreyansh/Videos/angular_complete/tpddlReportGeneratorNodeFile/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error collection: ' +
    'tpddlUserReports.tpddls index: CA_Number_1 dup key: ' +
    '{ : 1300 }',
  [Symbol(mongoErrorContextSymbol)]: {}
}

**Comment by shreyansh-goyal** [comment]
I am getting this type of error.

**Comment by vkarpov15** [comment]
How are you verifying that all the `CA_Number` properties in the spreadsheet are unique? Can you double check there aren't multiple rows with 'CA_Number = 1300'?

**Comment by shreyansh-goyal** [comment]
I am nesting the function in findone and if value is falsy I am creating that entry

**Comment by unboxx** [comment]
@shreyansh-goyal I am not sure how you are handling async behavior inside the loop. I would suggest using insertMany https://mongoosejs.com/docs/models.html, something like this.

readXlsxFile(fs.createReadStream(path.join(__dirname, 'user.xlsx'))).then(rows => {
    const updateUserData = []; 
    for (i in rows) {
      updateUserData.push({ user_id: rows[i][0] })
    }
    User.insertMany(updateUserData, (err) => { // Note: User is model here.
      if (err) console.log(err);
      console.log('success');
    })

**Comment by vkarpov15** [comment]
@unboxx good suggestion, it might be something due to the OP executing all the saves in parallel rather than in series. @shreyansh-goyal give [`insertMany()`](https://mongoosejs.com/docs/api/model.html#model_Model.insertMany) a shot.

**Comment by shreyansh-goyal** [comment]
@unboxx @vkarpov15  thanks a lot I have realized the bug in my code.Thanks a lot it was due to lot of async task which I managed now.
Thanks again.
