### ISSUE TITLE
Add useCache to documentation

### ISSUE THREAD

**Issue by gotenxds** [Automattic/mongoose#7923]
useCache on useDB: `mongoose.connection.useDb(config.get('dbName'), { useCache: true });`

exists since https://github.com/Automattic/mongoose/pull/6036 but is not documented and nor has an overload in the @types for typescript.

**Comment by Mihailoff** [comment]
Is there any memory considerations? For example with `useCache: true` and many-many-many databases will the number of active connections linearly increase?

**Comment by vkarpov15** [comment]
@Mihailoff with `useCache: false` the number of connection objects will increase linearly with the number of calls to `useDb()`. If that is a concern, we recommend using `useCache: true`, or not using `useDb()`.
