### ISSUE TITLE
Reserved schema pathname conflict

### ISSUE THREAD

**Issue by exentrich** [Automattic/mongoose#7924]
I have issue with using word `collection` as a pathname in schema.
I know that this word is reserved internally and could not be used. But maybe some one could share any workaround how to bypass this limitation? I can't unfortunately change name of this field in documents.

If it helps I'm only interested in using `collection.$id` pathname.

**Comment by vkarpov15** [comment]
If a document in your db has a property named `collection`, you can still access it using [`Document#get()`](https://mongoosejs.com/docs/api/document.html#document_Document-get) as shown below. You just can't put `collection` in your schema.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7924`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  await Model.collection.insertOne({ name: 'test', collection: 'foo' });

  const doc = await Model.findOne();
  console.log(doc.get('collection')); // 'foo'
}
```
