### ISSUE TITLE
Bug: 'fullsetup' event not emitted on reconnection

### ISSUE THREAD

**Issue by lobabob** [Automattic/mongoose#7927]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

On reconnect, the 'connected' and 'reconnected' events are emitted. However, variations of the connected event that denote a finer granularity are not emitted (e.g. 'fullsetup').

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Setup a 'fullsetup' event listener for the connection
```javascript
const mongoose = require('mongoose')

mongoose.connect(....)
mongoose.connection.on('fullsetup', () => console.log('Should trigger on reconnect'))
```
2. Restart your mongo server to initiate a reconnect attempt from your script

**What is the expected behavior?**

The 'fullsetup' event should trigger twice. Once on initial connection and once after reconnecting.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node: 10.15.3
- Mongoose: 5.5.13
- MongoDB: 4.0.6

**Comment by vkarpov15** [comment]
Hmm I'm not sure why you expect 'fullsetup' to be emitted multiple times. The [MongoDB driver docs say that it is only emitted during initial connection](http://mongodb.github.io/node-mongodb-native/3.1/api/Db.html#event:fullsetup). Can you describe your use case for multiple 'fullsetup' events?

**Comment by lobabob** [comment]
If the mongodb driver docs say it's only on initial connection then I suppose you're fine. 

The use case I was thinking of was for reconnects. There may be some stuff you want to do only when you've connected (or reconnected in this case) to a primary and at least one secondary, and listening to this event could've been a way to do that if it was emitted on reconnect.

**Comment by vkarpov15** [comment]
Would it be helpful if instead there was a way to check whether your replica set currently has a primary?

There are 'joined' and 'left' events that you can listen for which can tell you whether you lost a primary. [That's the preferred way to handle replica set outages](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html#replica-set-outages).

**Comment by RyuuGan** [comment]
@vkarpov15 

Hey, just to clarify a little bit, that state of connection is not synced with the real state of replica set and connection:

First subscribe to all events like this:
```
[
  "connecting",
  "connected",
  "open",
  "disconnecting",
  "disconnected",
  "close",
  "reconnected",
  "error",
  "fullsetup",
  "all"
].forEach(event => {
  mongoose.connection.on(event, function () {
    console.log('Mongoose event ' + event);
  });
});
```

Then start application and it will correctly connect to a replica set:

```
Mongoose event connecting
Mongoose event connected
Mongoose event open
```

Then disable primary node of `replica set`:

```
Mongoose event disconnected
```

And then `mongoose` and connection will be always in disconnected mode, but you can still save and query data using it.

**Comment by RyuuGan** [comment]
And also the connection from client (`mongoose.connection.client.topology.s.connected`) is always true.

**Comment by vkarpov15** [comment]
@RyuuGan can you please open a new issue and follow the issue template? The below script always prints "1" as the `readyState` even if I `stepDown()` the primary:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs', {
    useNewUrlParser: true,
    useUnifiedTopology: false
  });

  [
  "connecting",
  "connected",
  "open",
  "disconnecting",
  "disconnected",
  "close",
  "reconnected",
  "error",
  "fullsetup",
  "all"
].forEach(event => {
  mongoose.connection.on(event, function () {
    console.log('Mongoose event ' + event);
  });
});

  while (true) {
    console.log(new Date(), mongoose.connection.readyState, mongoose.connection.client.topology.s.connected);
    await new Promise(resolve => setTimeout(resolve, 2000));
  }
}
```

Output:

```
(node:24492) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2019-12-21T19:18:08.770Z 1 undefined
Mongoose event fullsetup
2019-12-21T19:18:10.773Z 1 undefined
2019-12-21T19:18:12.776Z 1 undefined
2019-12-21T19:18:14.778Z 1 undefined
2019-12-21T19:18:16.778Z 1 undefined
Mongoose event disconnected
Mongoose event connected
Mongoose event reconnected
2019-12-21T19:18:18.779Z 1 undefined
2019-12-21T19:18:20.780Z 1 undefined
2019-12-21T19:18:22.783Z 1 undefined
```

With `useUnifiedTopology` I don't get the events, but `readyState` is still 1:

```
2019-12-21T19:16:45.574Z 1 undefined
2019-12-21T19:16:47.578Z 1 undefined
2019-12-21T19:16:49.581Z 1 undefined
2019-12-21T19:16:51.584Z 1 undefined
2019-12-21T19:16:53.587Z 1 undefined
2019-12-21T19:16:55.587Z 1 undefined
2019-12-21T19:16:57.589Z 1 undefined
2019-12-21T19:16:59.592Z 1 undefined
2019-12-21T19:17:01.593Z 1 undefined
2019-12-21T19:17:03.595Z 1 undefined
2019-12-21T19:17:05.596Z 1 undefined
2019-12-21T19:17:07.599Z 1 undefined
2019-12-21T19:17:09.600Z 1 undefined
2019-12-21T19:17:11.600Z 1 undefined
```

**Comment by RyuuGan** [comment]
Hello @vkarpov15 ,

It looks like I was using a little bit outdated library version (`5.7.5`) and the problem was here, thanks for pointing that in the latest version everything is working fine. 

Sorry for inconvenience and have a good day.
