### ISSUE TITLE
Bug: ChangeStream doesn't get marked as closed correctly

### ISSUE THREAD

**Issue by lobabob** [Automattic/mongoose#7930]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

If an external event closes a ChangeStream, the closed property is not set to true.

E.g. If you start a change stream and the server goes down for over a minute, a MongoError is produced (timed out waiting for connection). The 'close' event is emitted from the ChangeStream, but the `closed` property is still false.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set up a 'close' event listener on a change stream
```javascript
const SomeModel = mongoose.model(...)

SomeModel.watch()
  .on('close', function () {
    console.log('closed is:', this.closed)
  })
```
2. Close your DB and wait for a time out (should be a minute)
3. Observe the value of the log statement

**What is the expected behavior?**

The `closed` property on a Mongoose ChangeStream should always be true when the close/end event is emitted.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: 10.15.3
Mongoose: 5.5.13
MongoDB: 4.0.6

**Comment by vkarpov15** [comment]
Oddly enough, I don't get a 'closed' event at all running the below script:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7930`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String });

  const Model = mongoose.model('Test', schema);

  await Model.create({ name: 'foo' });

  const stream = await Model.watch()

  stream
  .on('close', function () {
    console.log('closed is:', stream.closed)
  })
  .on('end', () => console.log('end', stream.closed))
  // Prints "Caught MongoError: Timed out waiting for connection"
  .on('error', err => console.log('Caught', err, stream.closed));
}
```

I just get the 'error' event. Although I agree in this case the stream should emit a close event, because there will be no more events if the underlying connection is dead.

Can you check the above script and see if you still get a 'close' event?

**Comment by lobabob** [comment]
Ah yeah, sorry my example was a bit messed up. I meant to say the error event occurs and closed never occurs (and the closed state itself is never set).

This is def an underlying issue with the mongodb driver. However, you could add an error listener that sets the closed state to true when it detects a timeout error as part of the mongoose ChangeStream wrapper.

**Comment by lobabob** [comment]
That PR only fixes part of the problem. The other part of the problem is within Mongoose itself.

If the underlying native change stream emits a 'close' event, Mongoose never sets its internal 'closed' state to true.

**Comment by lobabob** [comment]
^^^ Ignore that. You already do that in the _bindEvents method.
