### ISSUE TITLE
syncIndexes dies with "no collection" if createDatabase isn't called first

### ISSUE THREAD

**Issue by captaincaius** [Automattic/mongoose#7931]
First off, <3ing syncIndexes and all the recent features!

All in all the process went smoothly thanks to the good docs and blog posts.  But from the perspective of someone transitioning to it, I hit a few little gotchas I thought I'd report.

**Do you want to request a *feature* or report a *bug*?**

Could be solved w/ a little documentation or could be solved with changed behavior.

**What is the current behavior?**

1. syncIndexes assumes collection exists
  a. Turn off autoIndex at the connection level
  b. On a NEW database, make some kind of db initialization that runs syncIndexes on all models.
  c. expected: it works.  actual: it fails with "no collection"
  d. If it's by design, it's not super clear in the docs that you need to call createCollection before calling syncIndexes.  init() does not work.
2. speaking of createCollection - the docs could be a little clearer that it's safe to call when the collection already exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

syncIndexes works before the collection has been created (or it's documented :P).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.5.2
node: 10
mongo: 3.2
smartassiness: latest ;)

**Comment by vkarpov15** [comment]
Good suggestion, we should make `syncIndexes()` create the underlying collection if it doesn't already exist. It should be safe to call `createCollection()` if the collection already exists - you'll get an error if the collection options don't line up, but you won't break the database.

**Comment by captaincaius** [comment]
Awesome!

Looked through the code and it looks like one I might be able to handle this weekend.

**Comment by captaincaius** [comment]
<3 ! Thanks!
