### ISSUE TITLE
[Docs] Links in search results are broken sometimes

### ISSUE THREAD

**Issue by phil-r** [Automattic/mongoose#7932]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Some links in docs search results point to .pug files instead of .html

**If the current behavior is a bug, please provide the steps to reproduce.**

Go to https://mongoosejs.com/docs/search.html?q=id , second result will point to https://mongoosejs.com/docs/guide.pug#id

**What is the expected behavior?**

Search results should always point to .html files

**Comment by vkarpov15** [comment]
Thanks for pointing this out, will fix for next release :+1:
