### ISSUE TITLE
Compare ObjectId to array of (ObjectId) Strings

### ISSUE THREAD

**Issue by sarora2073** [Automattic/mongoose#7933]
**Do you want to request a *feature* or report a *bug*?**
Feature
Please note: This request is the inverse of #6159 which is worth reading for background. That request describes comparing an array of objectIds to a string. This request is the opposite i.e. comparing an objectId field to an array of strings (when you want the array of strings to be treated as an array of objectIds). 

In my scenario, the objectId field can't be converted..it is what is is in the collection. I frequently need to pass in an array of strings (via API), and then find all documents with a fieldId matching an Id in the array. I would image this is common use case.

**What is the current behavior?**
querying for something like this doesn't work unless the array of strings is first converted to an array of objectIds:

userId: { $in: [array of strings]}

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Preferred behavior would be to allow the array of strings to automatically be handled as an ObjectId.

Note: I currently workaround this by manual conversion using a function like this:
```
let toObjectIdArray = function(arr) {
  let objIdArray = arr.map(function (id) {
    return ObjectId(id);
  });
  return objIdArray;
}

```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v10.16.0
mongodb 4.0.6
mongoose 5.6.1

**Comment by vkarpov15** [comment]
What does your schema look like? If userId is an ObjectID in your schema, mongoose will convert strings to objectids for you

**Comment by sarora2073** [comment]
Sorry but I think you missed the point.. usedId IS an ObjectId, but I need to compare it an array of Object Ids. When I pass an array of Object IDs via an API they will necessarily be considered strings. If i recall, mongodb will handle an $in operation against an array of strings gracefully i.e. coerce them into being handled as ObjectIds..this request is that mongoose do the same.

**Comment by vkarpov15** [comment]
MongoDB won't coerce strings in an array into ObjectIds if you pass a `$in` operation with ObjectIds. MongoDB doesn't do any type coercion on queries at all. But Mongoose does, depending on your schema. See [query casting](https://mongoosejs.com/docs/tutorials/query_casting.html)

**Comment by sarora2073** [comment]
If MongoDB doesn't do it either then I had the wrong impression that this was a "gap" in what MongoDb does natively vs what Mongoose does with the $in operator. Thanks for clarifying and appreciate your help!
