### ISSUE TITLE
Configuration does not work “maxTransactionLockRequestTimeoutMillis”  

### ISSUE THREAD

**Issue by jiangwei1995** [Automattic/mongoose#7936]
config "maxTransactionLockRequestTimeoutMillis" : 20000
Start with a business logic at the same time
Error reporting for two transaction conflicts
MongoError: WriteConflict

**Comment by jiangwei1995** [comment]
@wvl @genexp @Sija @lackac

**Comment by vkarpov15** [comment]
@jiangwei1995 can you please provide code samples that demonstrate the issue and clarify what the behavior you expect is?
