### ISSUE TITLE
Updating multiple fields in array of objects doesn't seem to work

### ISSUE THREAD

**Issue by chamorin** [Automattic/mongoose#7937]
Hi,

I'm trying to make a simple update on two fields (opening, closing) of all objects in an array. To achieve this, I'm using this piece of code: 
```
await model.update({
     $set: {
	 'times.$.opening': '17:00',
	 'times.$.closing': '18:00'
     }
});
```

Here's the array for times:
![times](https://user-images.githubusercontent.com/24239074/60273163-7d50c200-98c3-11e9-8d02-9bac853f5cad.png)

I'm trying to give to all objects in the array the same opening and closing value.

What I get instead is an error saying : `MongoError: The positional operator did not find the match needed from the query`

What should be a simple update is giving me a real headache. I followed exactly whats in the mongodb documentation https://docs.mongodb.com/manual/reference/operator/update/positional/#update-documents-in-an-array

I'm using:
"mongodb": "^3.0.6",
"mongoose": "^5.5.10",
"node": "11.10.0"

Thank you

**Comment by vkarpov15** [comment]
Use `$[]` instead of `$` . The positional operator only updates at most one element of the array, if I'm reading correctly you're trying to overwrite all of them. Here's some more info: https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html
