### ISSUE TITLE
Confusing output when printing null object

### ISSUE THREAD

**Issue by junthehacker** [Automattic/mongoose#7942]
**Do you want to request a *feature* or report a *bug*?**

Feature suggestion.

**What is the current behavior?**

Currently, when setting a nested subdocument to `null`, then `console.log` it, mongoose produces `null` as output, even though it is an object, not really a JavaScript null.

Can be very confusing when debugging, because if used inside if statements, this type of null value will evaluate to true.

The following script will demonstrate the problem

```
const mongoose = require('mongoose');

mongoose.connect("mongodb://localhost:27017")
    .then(() => {
        console.log("mongoose connected");
    });

let testSchema = mongoose.Schema({
    name: String,
    subDoc: {
        name: String,
    },
});


const Test = mongoose.model('Test', testSchema);

(async () => {

    let test = new Test({name: "sample", subDoc: {name: "subname"}});

    await test.save();

    console.log(test.subDoc);

    test.subDoc = null;

    await test.save();

    console.log(test.subDoc);
    console.log(!!test.subDoc);

})();

```

once you run it, it should produce the following output:

```
mongoose connected
{ name: 'subname' }
null   <- Confusing
true  <- null evaluates to true???
```

**What is the expected behavior?**

It should produce something like `null object` to clearly indicate it is a custom object, not `null`. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.6.2, MongoDB 4.0.10

**Comment by vkarpov15** [comment]
This is an unfortunate quirk of nested properties, and why we have the $isEmpty function: https://mongoosejs.com/docs/api/document.html#document_Document-$isEmpty . Since you can't set getters and setters on null, Mongoose stores empty objects under the hood for nested properties.

If you do `subdoc: new Schema({ name: String })` then your checks will work as expected.
