### ISSUE TITLE
compare two date object

### ISSUE THREAD

**Issue by etrikhayri** [Automattic/mongoose#7946]
I'm trying to get list of users who subscribed before 30 days, i used $lt to compare date but i get nothing.

- this is my schema model:
`var VisitorsSchema = new Schema({
    firstname: String,
    lastname: String,
    subDate: Date
}, {
    collection: 'users'
});`

- this how i'm trying to get users subscribed before 30 days :

`users.find({
    "subDate": {
        $lt: new Date(new Date().setDate(new
            Date().getDate() - 30))
    }
}, function (err, resp) {
    if (err) {
        return next(err);
    }
    console.log(resp);
    res.send(resp);
});`

- Note: when i get one user and compare his date of subscribe like this:
`var de=new Date(new Date().setDate(new Date().getDate()-30));
res.send(resp[0]['subDate']>de);`

it works fine and i get correct result(true or false).

**Comment by etrikhayri** [comment]
subDate's format in mongo is like this : 2017-10-05T11:25:00+02:00

**Comment by etrikhayri** [comment]
i try to add work with moment.js library, i have added this part of cide just to get all users subscribed before to day but i get nothing : 

> `visitors.find({ "creationDate": { $lte:today } } `

**Comment by vkarpov15** [comment]
[JavaScript's `setDate()` function returns a number, not a date](https://www.w3schools.com/jsref/jsref_setdate.asp), that might be one problem.

With your moment example, are you sure you're querying the right model and the right property? In the original post you have a 'users' model and a `subDate` property, and in the 3rd post you have a 'visitors' model and a `creationDate` property.

**Comment by etrikhayri** [comment]
problem resolved by adding toISOString() :
`$lte: new Date(new Date().setDate(new Date().getDate()-daysNumber)).toISOString()`
