### ISSUE TITLE
Replica set connection not reliably closed on disconnect

### ISSUE THREAD

**Issue by yelworc** [Automattic/mongoose#7947]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

As of v5.5.7, the `disconnect` function sometimes does not close all connections from our API server (running on Heroku) to its database (a replica set on MongoDB Cloud). The `close` event is fired, `mongoose.connection.readyState` changes to 0, but the process does not exit. wtfnode shows that there are open socket connections to one or two of the DB servers. It only happens occasionally, but we are running a number of scheduled background tasks in separate processes (daily, hourly, etc), and those are now regularly getting stuck. I can also reproduce it locally quite easily (connecting to the same MongoDB Cloud database).

I've narrowed it down to [commit a0f6ac1](https://github.com/Automattic/mongoose/commit/a0f6ac1); no idea how that change might have this side effect, but that is the first commit where the issue occurs.

**What is the expected behavior?**

All DB connections should be consistently closed on `disconnect()`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 5.5.7 (also tried 5.6.0, same behavior), MongoDB as running on MongoDB Cloud (currently 4.0.10), latest Node.js v12 (currently 12.5.0).

**Comment by yelworc** [comment]
Oops – spoke too soon, apparently. The issue did eventually pop up in a version _before_ the aforementioned commit. Since v5.5.6 is the last "known good" version, that only leaves [commit 524d981](https://github.com/Automattic/mongoose/commit/524d981fdd727beb9b017878e1097f36f41e5e8d) as the potential culprit…

**Comment by vkarpov15** [comment]
The below script exits successfully for me using Mongoose 5.6.5 connecting to MongoDB Atlas. Can you check whether the below script fails for you against your database?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7947`;
const connectionString = 'mongodb+srv://USER:PW@cluster0-XYZ.mongodb.net/admin?retryWrites=true&w=majority';
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  console.log('Connected');

  await mongoose.disconnect();
  console.log('Disconnected');
} 
```

**Comment by yelworc** [comment]
Ha – it works just fine with v5.6.4, but it fails (i.e. doesn't exit) with Mongoose up to v5.5.13. v5.5.14 included a MongoDB driver update, maybe that fixed something.

Anyway, I'll update all our systems, and will close this issue in a few days if it really resolves the problem. Thanks!

**Comment by yelworc** [comment]
So, after 3 days with Mongoose v5.6.4, I'm happy to report that everything is looking good (disconnecting cleanly). Thanks again for the help!
