### ISSUE TITLE
$ field gets removed before check that assumes it's there (castUpdate)

### ISSUE THREAD

**Issue by jnardone** [Automattic/mongoose#7949]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

The fix for https://github.com/Automattic/mongoose/issues/7917 -> 
https://github.com/Automattic/mongoose/commit/e22746eaa4d0cf050ba48092a721be11d7b11258 introduces a check that is sometimes invalid

```
    if (op.startsWith('$') && Object.keys(val).length === 0) {
      delete ret[op];
    }
```

`val` can sometimes be undefined.  

**If the current behavior is a bug, please provide the steps to reproduce.**

In tracing `castUpdate`, obj starts out as this object (shown as JSON for readability):

```
{"description":"Ipsam doloribus","$addToSet":{"changed":{"$each":["description"]}},"updatedAt":"2019-07-01T20:12:15.284Z","createdAt":"2019-07-01T20:12:15.284Z"}
```

in the while loop https://github.com/Automattic/mongoose/blob/e22746eaa4d0cf050ba48092a721be11d7b11258/lib/helpers/query/castUpdate.js#L71 before the "if" check on line 76, `ret` is

```
{"createdAt":"2019-07-01T20:12:15.284Z","updatedAt":"2019-07-01T20:12:15.284Z","$addToSet":{"changed":{"$each":["description"]}},"description":"Ipsam doloribus"}
```

but by line 94, it's now

```
{"createdAt":"2019-07-01T20:12:15.284Z","updatedAt":"2019-07-01T20:12:15.284Z","description":"Ipsam doloribus"}
```

*What happened to `$addToSet`?*

When the loop gets to the `$addToSet` op, this will now fail because on line 95 `Object.keys(val).length` will reference an undefined value (`val` is `ret['$addToSet']`).  

**What is the expected behavior?**
This code shouldn't error out.  I don't know whether the bug is that `$addToSet` is getting removed in the `if` block, or if the `Object.keys(val)` code needs to check if `val` is undefined/null...

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 10.16.0
mongo: 4.0.9
mongoose: 5.6.2

**Comment by vkarpov15** [comment]
I haven't been able to repro this issue, but I added an extra `null` check. Next time, it would be helpful if you provided code samples that demonstrate the issue rather than walking through the Mongoose code.
