### ISSUE TITLE
Rename `Query#map()` -> `Query#transform()` to avoid conflating with `Array#map()` and chaining

### ISSUE THREAD

**Issue by dietergeerts** [Automattic/mongoose#7951]
**Do you want to request a *feature* or report a *bug*?**
Request a deprecation of a feature, in order to reduce the code and API.

**What is the current behavior?**
We have `Query.map()`, and that just maps the result of the query to something else, based on the function you give it. So basically, this just runs a function. So basically, this doesn't add anything of actual value, as you can just take the result yourself, and run it through the function you would have given to the `map` helper. Also, it returns `this`, and combined with the fact that this will only run after all post hooks, can be confusing, as it can be placed in any order of steps being added, but not executing when you declared.

**What is the expected behavior?**
That there is no `Query.map()`, to remove confusion, code and API that can be achieved with plain JavaScript.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Not relevant

IF there are real benefits of having this, I would like to see them in the docs, as right now, it just shows something that can be done after the query in plain JavaScript.

**Comment by vkarpov15** [comment]
We actually added it to the API specifically because we were asked to in #7142 . It exists primarily to support `orFail()`, because we want `orFail()` to run after any post hooks that might modify the output. I don't really see much harm in leaving it in the API - what confusion has `map()` caused you?

**Comment by dietergeerts** [comment]
> what confusion has `map()` caused you?
Not me personally, but when placing `map()` in between steps, one might think that it will be applied between them, instead of in the end, after all post hooks.

It's not a big deal, as one should read the docs and know how it works, but because this can be achieved with plain JS, not having this feature exposed would just avoid this confusion.

**Comment by vkarpov15** [comment]
That's a fair concern, and something we'll think about for the future.
