### ISSUE TITLE
toJSON or reverseTranslateAliases function to return alias keys

### ISSUE THREAD

**Issue by abhisekp-bac** [Automattic/mongoose#7952]
**Do you want to request a *feature* or report a *bug*?**
> *feature*

**What is the current behavior?**
> `findOneAndUpdate` query `toJSON` doesn't return the aliased keys. Rather it returns the original keys.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`toObject` or `toJSON` should return the aliased keys instead of the raw keys. Or a custom function like [`reverseTranslateAliases`](https://mongoosejs.com/docs/api.html#model_Model.translateAliases) can be implemented.
Related to #5184

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.6.2
node: 12.0.0
npm: 6.9.0

**Comment by abhisekp-bac** [comment]
Adding the following to the mongoose schema options solves the issue.

```js
{
    toJSON: {
      virtuals: true,
      transform: (doc: any, ret: any, opts: any) => {
        Object.keys(doc.schema.obj)
          .filter(k => doc.schema.obj[k].alias)
          .forEach(ak => delete ret[ak]);
      }
    }
}
```

Maybe a plugin can help?

**Comment by vkarpov15** [comment]
This is by design. The primary purpose of aliasing keys is to reduce storage in the database and network overhead between Node.js and MongoDB by shortening the keys when they're stored in the database, and converting the aliased keys back to long-form keys in Node.js.

**Comment by klemensz** [comment]
If it's by design, then why doesn't it work as designed?

**Comment by vkarpov15** [comment]
@klemensz if it doesn't work as designed, please open up a new issue and follow the issue template.
