### ISSUE TITLE
`timestamp` does not exist in `saveOptions` object for Model#save()

### ISSUE THREAD

**Issue by duenguyen2103** [Automattic/mongoose#7960]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`timestamp` does not exist in `saveOptions` object for Model#save()
**If the current behavior is a bug, please provide the steps to reproduce.**

I try to skip the timestamps by using timestamps: false like this but it does not work:

> await customerTicketModel.save({ timestamps: false}, () => {});

**What is the expected behavior?**
`timestamp` should exist in `saveOptions` object so we can skip the timestamp for this save.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v8.9.0, Mongoose: v5.6.3, MongoDB: v4.0.3

**Comment by vkarpov15** [comment]
The below script works for me. Please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7960`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String }, { timestamps: true });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ name: 'test' });
  const updatedAt = doc.updatedAt;

  doc.name = 'foo';
  await doc.save({ timestamps: false });

  const _doc = await Model.findOne();
  assert.equal(_doc.updatedAt.valueOf(), updatedAt.valueOf());
}
```
