### ISSUE TITLE
on may not be used as a schema pathname

### ISSUE THREAD

**Issue by 03balogun** [Automattic/mongoose#7967]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

According to the documentation here [https://mongoosejs.com/docs/populate.html#dynamic-ref](https://mongoosejs.com/docs/populate.html#dynamic-ref) Mongoose can populate from multiple collections based on the value of a property in the document. When I tired creating a schema similar to the example from the page I got an error  *`on` may not be used as a schema pathname*

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const commentSchema = new Schema({
  body: { type: String, required: true },
  on: {
    type: Schema.Types.ObjectId,
    required: true,
    // Instead of a hardcoded model name in `ref`, `refPath` means Mongoose
    // will look at the `onModel` property to find the right model.
    refPath: 'onModel'
  },
  onModel: {
    type: String,
    required: true,
    enum: ['BlogPost', 'Product']
  }
});
const Product = mongoose.model('Product', new Schema({ name: String }));
const BlogPost = mongoose.model('BlogPost', new Schema({ title: String }));
const Comment = mongoose.model('Comment', commentSchema);
```

**What is the expected behavior?**

The collection should be created without error

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v10.11.0
Mongoose: v5.6.3
MongoDB: v4.0.3

**Comment by 03balogun** [comment]
It was a mistake from the example code example.
**on** is a reserved keyword in mongoose used to listening for events, it can't be used as a pathName

The below code snippet works.
```
const commentSchema = new Schema({
  body: { type: String, required: true },
  modelId: {
    type: Schema.Types.ObjectId,
    required: true,
    // Instead of a hardcoded model name in `ref`, `refPath` means Mongoose
    // will look at the `modelName` property to find the right model.
    refPath: 'modelName'
  },
  modelName: {
    type: String,
    required: true,
    enum: ['BlogPost', 'Product']
  }
});
const Product = mongoose.model('Product', new Schema({ name: String }));
const BlogPost = mongoose.model('BlogPost', new Schema({ title: String }));
const Comment = mongoose.model('Comment', commentSchema);
```

**Comment by sagarbetkar** [comment]
The above solution is also half correct. In refpath writing, the only modelName won't populate the document.
Instead use
```
refpath: 'modelId.modelName'
```

**Comment by JorgeGuerraPires** [comment]
it seems that `modelName` is also a problem, I had to use `modelName`2`, I am not sure it will work, but stopped the compilation error similar to on

**Comment by JorgeGuerraPires** [comment]
It did not work :). See there my thread: https://stackoverflow.com/questions/60890440/dynamic-references-via-refpath-does-not-seem-to-work-any-suggestion

**Comment by mustafaKamal-fe** [comment]
Following the docs and above disscusion, i was not able to get the exmple in the docs work either way. Is there anyway clear explination on how to utilize this feature please?
