### ISSUE TITLE
get value of arrayFilter array index and use as a value

### ISSUE THREAD

**Issue by yiperean** [Automattic/mongoose#7974]
I want to update a field using the arrayfilter variable this is what I have done so far.

	var items='green shirt'

	Model.update({
		id: 7c59453a6194a90217defc70
	},{
		{$set:{
			'arrayname.$[firstArray].field1':'my new name',
			'arrayname.$[firstArray].field2':'myusername'
			'arrayname.$[firstArray].field3':[items+[arrayname.$[firstArray].field4]]
		},
		arrayFilters:[{"firstArray._id":7c59453a6194a90217defc70}],
		new:true, safe:false}},
		function(err, update){
			if(err){}
			else{}
		})
	
By using the arrayFilter I would be able to get the specific array which I want to work on. 
Now my logic is, the arrayFilter would get the index of the specific item and make it 
available within the $set expression. 
How can I get the arrayIndex and use it as a variable for the value. as indicated in field3 above

	'arrayname.$[firstArray].field3':[items+[**arrayname.$[firstArray].field4**]]
	This produced an error arrayname is undefined
	
Some other which I have tried

	1.  'arrayname.$[firstArray].field3':[items+[`**arrayname.$[firstArray].field4**`]]
	It was inserted into the data as a string
	
	
Some might say the best is to use a find and save method inside the update, but I am looking at
a way of reducing the call to the server. 

This would do (as I believe) make the program more efficient

**Comment by vkarpov15** [comment]
MongoDB doesn't support updating a property based on the value of another property, like `$set: { fullName: firstName + lastName }`. You should do this using `find()` and `save()`.
