### ISSUE TITLE
Explain family: 0 option

### ISSUE THREAD

**Issue by DavidTheWin** [Automattic/mongoose#7976]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Mongoose fails to connect to MongoDB giving an ENOTFOUND error on a dns lookup despite a similar manual dns lookup of the host being successful

**If the current behavior is a bug, please provide the steps to reproduce.**

Redacted sample code below. If I downgrade Mongoose to the version we used previously (4.13.4) it connects fine. Changing the connection string to use the IP addresses of the hosts still gives a dns error with the hostname somehow (either a successful dns lookup or it fetches it from the replica set config?). The connection string is a valid MongoDB connection string and works fine from the same machine when connecting to MongoDB directly or via Robo 3T.

`const mongoose = require('mongoose');
const dns = require('dns');

const connectionString = 'mongodb://username:password@host1:27017,host2:27017/database?replicaSet=replicaSetName';

mongoose.connect(connectionString, { useNewUrlParser: true});
mongoose.connection.on('open', () => console.log('connected'));
mongoose.connection.on('error', console.log);`

**What is the expected behavior?**

A successful connection

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 12.1.0
Mongoose 5.6.4
MongoDB 4.0.6

**Comment by DavidTheWin** [comment]
Apologies for the title, I can't edit it now

**Comment by vkarpov15** [comment]
The MongoDB node driver fetches the host names from the replica set config, so you're likely running into [this issue](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). You might need to tweak the `/etc/hosts` on the machine running Mongoose to map the reported hostname to the IP.

**Comment by DavidTheWin** [comment]
Both hosts report their hostname in the replica set config correctly.

I think I've fixed it by setting the family option to 0 when connecting, I'm not entirely sure why. The mongoose type definition only accepts 4 and 6 as options despite 0 being a valid input to the DNS lookup options.

**Comment by vkarpov15** [comment]
How do you define "correctly"? And can the DNS on your app server resolve those hostnames?

Also, `family: 0` is equivalent to not setting `family` at all: https://nodejs.org/api/dns.html#dns_dns_lookup_hostname_options_callback
