### ISSUE TITLE
Error : Calling `mongoose.connect()` multiple times while connected

### ISSUE THREAD

**Issue by RohithKilaparthi** [Automattic/mongoose#7977]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
My use-case is to connect to different DBs at run-time based on the input of the API and access data from that DB. 
```
getConnectionForDB: async function (dbName) {
        if (await this.checkDatabaseExistence(dbName)) {
            var dbConnector = "mongodb://" + DB_USERNAME + ":" + DB_PASSWORD + "@" + DB_URI + "/" + dbName + "?authSource=" + DB_AUTH_SOURCE;
            return await mongoose.connect(
                dbConnector,
                { useNewUrlParser: true }
            );
        }
        throw new Error("DB doesn't exist");
    },
```
```
getInitialConnectionForDB: async function () {
        //var dbConnector = "mongodb://" + DB_USERNAME + ":" + DB_PASSWORD + "@" + DB_URI + "/" + SHIKSHALAYAS_DB + "?authSource=" + DB_AUTH_SOURCE;
        var dbConnector = "mongodb://localhost/" + SHIKSHALAYAS_DB;
        return await mongoose.connect(
            dbConnector,
            { useNewUrlParser: true }
        );
    },
```
When is application boots up, I call getInitialConnectionForDB function and whenever I want to switch the DB, I used to simply call the getConnectionForDB function passing the dbName as parameter. But now, the recent update is throwing an error ``` You can not `mongoose.connect()` multiple times while connected. ```  when I am trying to switch the db.

**If the current behavior is a bug, please provide the steps to reproduce.**
The code is failing with mongoose version 5.6.4, whereas it is working as expected with 5.4.22.

**What is the expected behavior?**
No error should be thrown

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node - 10.16.0
Mongoose - 5.6.4
Mongodb: 2.2.33

**Comment by RohithKilaparthi** [comment]
I am following multi-tenant architecture. That is the reason I had to switch between multiple DBs. I have checked the previously raised issues, but did not find a proper solution.
I tried using mongoose.createConnection in getConnectionForDB function, but the data is still falling into Default Database. 
Please suggest me on what can be done to get this resolved.

**Comment by vkarpov15** [comment]
We'll remove this error, looks like this check caused more problems than it solves. We will likely make this change again in Mongoose 6.0.0.

As an alternative, I recommend using [`useDb()`](https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb):

```javascript
mongoose.connection.useDb(dbName, { useCache: true });
```

**Comment by RohithKilaparthi** [comment]
Thanks a lot for the swift response. I will try to use the recommended and update the thread.
