### ISSUE TITLE
Documentation on MongooseArray has vanished ?

### ISSUE THREAD

**Issue by theenglishway** [Automattic/mongoose#7979]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Some documentation is missing on https://mongoosejs.com/docs/ and/or some links within the documentation are broken

There used to be a whole section dedicated to 'MongooseArray' in the [API page](https://mongoosejs.com/docs/api.html) (even though it was not referenced in the side menu), but for a few weeks now, the term 'MongooseArray' itself is nowhere to be found within the page, all the related documentation is gone, it seems, and the links to it in the other parts of the documentation lead to nowhere

Note that the API page ends on a "Array" header with an empty section ; that seems weird and might be related ?

**If the current behavior is a bug, please provide the steps to reproduce.**
Visit e.g. https://mongoosejs.com/docs/subdocs.html#adding-subdocs-to-arrays and click on any of the links on "push, unshift, addToSet" : [push](https://mongoosejs.com/docs/api.html#mongoosearray_MongooseArray-push)

Links further below in the same page like [this one](https://mongoosejs.com/docs/api.html#types_documentarray_MongooseDocumentArray.create) or [that one](https://mongoosejs.com/docs/api.html#types_embedded_EmbeddedDocument-remove) do not link to anywhere either, so they are either broken or the relevant content in the API docs has gone as well

**What is the expected behavior?**
The full documentation should be printed

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Version 5.6.4
(I started using mongoose about 2 months ago and the content in question was there at the time)

**Comment by vkarpov15** [comment]
Looks like #7798 wiped out the array API docs, fix will be in 5.6.6. Thanks for reporting :+1:
