### ISSUE TITLE
How to extract connection object from mongoose query object correctly?

### ISSUE THREAD

**Issue by sandeepsuvit** [Automattic/mongoose#7982]
Hi i am using the version 5.6.3 version of mongoose with typescript in one of my projects. I am currently trying to create a custom plugin on mongoose, using which i wanted to extract the mongo connection object for making db calls from within the plugin. 

From mongoose documents object i am able to get the underlying connection using `doc.collection.conn` on `save` pre hook. I also wanted to get the same from query object that is available from pre hooks for `findOneAndUpdate`. Is a way to get this done?

```typescript
export function CustomPlugin(schema: Schema) {
    schema.pre('save', function(next) {
        const self = this; // here `this` represents a mongoose document
        console.log(self.collection.conn); // gives the connection object
        return next();
    });

    schema.pre('findOneAndUpdate', function(next) {
        const self = this; // here `this` represents a mongoose query
        console.log(self.mongooseCollection.conn); // gives the connection object
        return next();
    });
}
```

I have tried using `query.mongooseCollection.conn` and it gives me the connection but i am not sure if that is the correct approach because in the above code connection is present in two different objects.

**Comment by vkarpov15** [comment]
I think the best way would be `self.model.db`, but your approach is equivalent.
