### ISSUE TITLE
Documentation on Embedded.prototype.discriminator

### ISSUE THREAD

**Issue by xileftenurb** [Automattic/mongoose#7983]
Documentation issue.

There is writed no-where, in documentation nor in index.t.ds, that the class `Embedded` found at "mongoose/lib/schema/embedded.js" have the function "discriminator.
even if the jsdoc (line 273 of said file) say it is part of the public api.

Is it safe to use this feature like the discriminator function of "DocumentArray"? does it do the same thing? the function seem similar, but I don't understand the whole code in it's context.

**Comment by vkarpov15** [comment]
We'll add it to the API docs and the [discriminator docs](https://mongoosejs.com/docs/discriminators.html). It should be safe to use this feature.
