### ISSUE TITLE
Post Validate hook does not fire when using findOneAndUpdate with the runValidators option set to true

### ISSUE THREAD

**Issue by mistermoe** [Automattic/mongoose#7984]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**  Post Validate hook does not fire when using `findOneAndUpdate` with the `runValidators` option set to `true`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.set('useCreateIndex', true);
mongoose.set('useFindAndModify', false);

(async () => {
    const UserSchema = new mongoose.Schema({
        email: {
            type: String,
            required: 'You must provide an email to create an account.',
        },
        password: {
            type: String,
            minlength: [8, 'User password must be at least 8 characters long.'],
            trim: true,
            required: 'You must provide a password to create an account.',
        }
    });

    UserSchema.pre('save', function (next) {
        console.log('pre save');

        return next();
    });

    UserSchema.pre('findOneAndUpdate', function (next) {
        console.log('pre findOneAndUpdate');

        return next();
    });

    UserSchema.post('validate', function() {
        console.log('post validate');
    });



    const User = mongoose.model('User', UserSchema);
    await mongoose.connect('mongodb://mongo:27017/test', { useNewUrlParser: true });
    await User.create({ email: 'hello@gmail.com', password: 'password' });
    await User.findOneAndUpdate({ password: 'password1' }, { runValidators: true });

    await mongoose.disconnect();
})();
```

The output you'll see when you run the above code will be:
```
post validate
pre save
pre findOneAndUpdate
```

**What is the expected behavior?**
The output when running the code i've provided would be:
```
post validate
pre save
pre findOneAndUpdate
post validate
```
ideally validation would happen prior to the pre `findOneAndUpdate` hook in order to remain consistent with the order things run for saving but at the very least the post validation hook should fire when running `findOneAndUpdate` with `runValidators` set to true

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.5.0
Mongoose: v5.6.4
MongoDB: v4.0.9

---

Let me start by saying i've read through all documentation pertinent to update validators. I'm aware that document validation works differently than update validation. 

Additionally, here's a concrete scenario as to why i believe the post validate hook not firing  when running `findOneAndUpdate` with `runValidators` set to `true` is a bug.

Let's we have a simple `User` schema with `email`, and `password`. We add some simple validation for `password` that requires the password to be at least 8 characters long. Prior to saving the user's password to mongo, we want to bcrypt it. We'd want to do this whenever the user is created or whenever the user's password is updated. The order in which the middlewares run when creating a document makes this quite simple. We'd do something like so:

```js
UserSchema.pre('save', function (next) {
    if (this.password) {
        this.password = encryptPassword(this.password)
    }

    return next();
});
```

For creation, the following steps occur:
1. provided password is validated
2. provided password is encrypted
3. encrypted password is saved to mongo

For updating however, this becomes more difficult because validation happens *after* the pre `findOneAndUpdate` hook which means the provided password could be less than 8 characters but encrypted to greater than 8 characters which would cause the subsequent validation to pass. With this in mind, the only place to put password encryption would be in a post validate hook. Unfortunately, this hook doesn't fire.

**Comment by mistermoe** [comment]
worth noting that i did find this issue -> #7845 which looks to be a reason as to why the pre/post validate hooks don't fire

**Comment by vkarpov15** [comment]
You make a good point about validation happening after `pre('findOneAndUpdate')` making it difficult. We will consider adding a validate function for queries that runs update validators, so you can hook into update validators in a way that's more consistent with document validators.

As a workaround, you could do bcrypt encryption in the same `pre('findOneAndUpdate')` hook as validation.

```javascript
UserSchema.pre('findOneAndUpdate', function (next) {
    const update = this.getUpdate();
    if (update.password != null) {
        assert.ok(update.password.length >= 8);
        update.password = encryptPassword(update.password);
    } else if (update.$set != null && update.$set.password != null) {
        assert.ok(update.$set.password.length >= 8);
        update.$set.password = encryptPassword(update.$set.password);
    }

    return next();
});
```

**Comment by mistermoe** [comment]
Thanks!

**Comment by danbergelt** [comment]
Hi, I see this has a pending release label on it. Are there any plans to add this functionality? It'd be really nice to get access to validation in a `pre(findOneAndUpdate)` call.

**Comment by enkeyz** [comment]
Late, but I see this has been fixed, but sadly I can't find the documentation on this.

**Comment by vkarpov15** [comment]
Is there a `password` property in `req.body` @enkeyz ?
