### ISSUE TITLE
Mongoose init hook toObject() gets data of another document 

### ISSUE THREAD

**Issue by yiperean** [Automattic/mongoose#7985]
var userSchema = mongoose.Schema({
		armor	: Number
		rounds	: Number
		health	: Number
	})

	userSchema.post('init', function(next){
		fullArmor = this.toObject().armor;
		fullRounds = this.toObject().rounds;
		fullHealth = this.toObject().health;
	})
I want to get existing data for a "specific" document and add extra information relating to that document only. 
So if I change to another document I expect it to pick up information relating to that document only and not include information for another document. 
But when I save a document and then save another new document, it picks up information relating to the earlier document and add it to the new document.
i.e.
FullArmor2 would contain information relating to FullArmor1

When I save a new documnt, It saves existing information into the docuemnt. But when I

**Comment by vkarpov15** [comment]
The below script works as expected for me, no information leakage between post('init') hooks. Please modify the below script to demonstrate your issue:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7985`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  var userSchema = mongoose.Schema({
        armor   : Number,
        rounds  : Number,
        health  : Number
  })

  userSchema.post('init', function(next){
        fullArmor = this.toObject().armor;
        fullRounds = this.toObject().rounds;
        fullHealth = this.toObject().health;
        console.log(fullArmor);
  })

  const User = mongoose.model('User', userSchema);

  await User.create([{ armor: 1 }, { armor: 2 }]);

  // Prints "1"
  await User.findOne({ armor: 1 });

  // Prints "2"
  await User.findOne({ armor: 2 });
}
```
