### ISSUE TITLE
TypeError: res.status is not a function

### ISSUE THREAD

**Issue by IDONTSUDO** [Automattic/mongoose#7987]
*bug

*behavior
I have a request.

He walks through the router. He sends it to check for two callbacks. These calbacks complement the Req data. I expect that the application will collect data from two collections. And on the basis of them will create a new collection.

**If the current behavior is a bug, please provide the steps to reproduce.**
git clone https://github.com/IDONTSUDO/CRM-
npm i
npm run dev
and watch video https://www.youtube.com/watch?v=0io--BhXVwk&feature=youtu.be
`TypeError: res.status is not a function

    at C:\Users\User\CRM\CRM-\controllers\user\Order.js:62:24

    at C:\Users\User\CRM\CRM-\node_modules\mongoose\lib\model.js:4733:16

    at C:\Users\User\CRM\CRM-\node_modules\mongoose\lib\utils.js:255:11

    at C:\Users\User\CRM\CRM-\node_modules\mongoose\lib\query.js:4216:18

    at model.Query.<anonymous> (C:\Users\User\CRM\CRM-

    \node_modules\mongoose\lib\query.js:2018:5)

    at model.Query._wrappedThunk [as _findOne] (C:\Users\User\CRM\CRM-

    \node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)

    at C:\Users\User\CRM\CRM-\node_modules\kareem\index.js:369:33

    at processTicksAndRejections (internal/process/task_queues.js:82:9)

    Emitted 'error' event at:

    at C:\Users\User\CRM\CRM-\node_modules\mongoose\lib\model.js:4735:13

    at C:\Users\User\CRM\CRM-\node_modules\mongoose\lib\utils.js:255:11

    [... lines matching original stack trace ...]

    at processTicksAndRejections (internal/process/task_queues.js:82:9)

    [nodemon] app crashed - waiting for file changes before starting...`

**What is the expected behavior?**

I expected to be saved
MongoDb 3.2.5 Mongoose last version Node js last version.

**Comment by vkarpov15** [comment]
Your stack trace points to the `userbyid` function in `controllers/user/Order.js`, check to see what the `res` parameter is there. It's hard for me to debug your code, I get errors when I run your project:

```
$ npm install nodemon

> nodemon@1.19.1 postinstall /home/val/Workspace/MongoDB/troubleshoot-mongoose/CRM-b2b/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN nodeapi@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ nodemon@1.19.1
added 188 packages in 7.249s
$ npm run dev

> nodeapi@1.0.0 dev /home/val/Workspace/MongoDB/troubleshoot-mongoose/CRM-b2b
> nodemon app.js

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
module.js:540
    throw err;
    ^

Error: Cannot find module './routes/manage/products.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/val/Workspace/MongoDB/troubleshoot-mongoose/CRM-b2b/app.js:32:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...
^C$ 
```

Also, 'last version' is not a version. Please get the [actual mongoose version](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-version).

**Comment by IDONTSUDO** [comment]
I'm sorry, I just changed the project. Since the guys from express.js this error is not reproduced. But I can write another project in which this error will be reproduced.

**Comment by vkarpov15** [comment]
@IDONTSUDO if you could repro this error in another project, that would be very helpful :+1:
