### ISSUE TITLE
Populate in query can't populate an array

### ISSUE THREAD

**Issue by Ku4rtz** [Automattic/mongoose#7988]
Here is my Game Schema :

```
var mongoose = require('mongoose');

const GameSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },

    publishers: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Publisher'
        }
    ]
});

var GameModel = mongoose.model('Game', GameSchema);
module.exports = GameModel;
```

Here is my Publisher Schema :

```
var mongoose = require('mongoose');

const PublisherSchema = new mongoose.Schema({
    companyName: {
        type: String,
        required: true
    },

    firstParty: {
        type: Boolean,
        required: true
    },

    website: {
        website: String,
    }
});

var PublisherModel = mongoose.model('Publisher', PublisherSchema);

module.exports = PublisherModel;
```

I have a picture of what you can find in my collection "games" in mongoDB :

![Capture](https://user-images.githubusercontent.com/38097175/61272024-61478e80-a7a6-11e9-8b58-812d1e494449.JPG)

Here is the picture of what you can find in my collection "publishers" in mongoDB : 

![Capture](https://user-images.githubusercontent.com/38097175/61272135-aec3fb80-a7a6-11e9-9a70-443f329b1cd8.JPG)

When I use this route :

```
router.get('/games', async function(req, res) {

    const games = await Game
        .find()
        .populate('publishers')
        .select('title publishers')

        res.json(games);
})
```

Here is what Postman gives me : 

![Capture](https://user-images.githubusercontent.com/38097175/61272212-e337b780-a7a6-11e9-84c2-6255c6f73967.JPG)

I have empty arrays as result for the publishers. If I don't use an array in Schema, this is correcly populated and I got data of publisher into each game. So why mongoose doesn't populate when it is an array?

**Comment by vkarpov15** [comment]
Can you please clarify what you mean by "If I don't use an array in Schema, this is correcly populated and I got data of publisher into each game"?
