### ISSUE TITLE
Reconnect manually after reconnectFailed requires manual disconnect

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#7991]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I just stumbled over a bug in 5.5.* where I couldn't manually recover after a `reconnectFailed` event, but upgrading to 5.6.4 fortunately fixed that (Kudos for that!). However, I noticed that I still have to manually disconnect before attempting to reconnect. Otherwise, mongoose still assumed it is still connected and fails - despite having thrown the `reconnectFailed` event.

This of course implies that if `disconnect` fails for any reason, my application is basically dead in the water :)

**If the current behavior is a bug, please provide the steps to reproduce.**

First, connect to the DB successfully, then cut the connection, which triggers the reconnect events, and then eventually the `reconnectFailed` event.

This is my current script:

	async function initMongoDb(config) {

		try {
			// perform initial connect
			const uri: string = config.mongoDbUri;
			const db: Mongoose = await mongoose.connect(uri, {
				useNewUrlParser: true,
				reconnectTries: 2,
				reconnectInterval: 500,
				connectTimeoutMS: 3000,
				socketTimeoutMS: 3000,
			});

			// note: simplified code, i'm only subscribing to this event once
			mongoose.connection.on("reconnectFailed", async err => {
				try {
					// THE APP IS DEAD WITHOUT THIS
					await db.disconnect();

					// start a new connection attempt
					initMongoDb(config, logger);
				} catch (e) {
					// never invoked
				}
			});
		} catch (e) {
			// never invoked
			initMongoDb(config);
		}
	}

**What is the expected behavior?**

I'd expect mongoose to be aware of it's connection status. The current state after `reconnectFailed` feels very brittle.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.6.4, mongodb 3.4.2, node 10.16.0

**Comment by vkarpov15** [comment]
So if I kill mongodb with the below script running, Mongoose correctly reports its connection state as 'disconnected':

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7991`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, {
    useNewUrlParser: true,
    reconnectTries: 2,
    reconnectInterval: 500
  });

  mongoose.connection.on('reconnectFailed', function() {
    console.log('Ready state', mongoose.connection.readyState); // Prints "0", which means disconnected
    mongoose.connect(connectionString, {
      useNewUrlParser: true,
      reconnectTries: 2,
      reconnectInterval: 500
    }).catch(err => console.log('caught', err));
  });
} 
```

Taking a closer look at the code, I don't see how it could be possible for mongoose's connection state to be 'connected' if 'reconnectFailed' is emitted.

What makes you think you need to disconnect before reconnecting? Do you get some sort of error message if you call `mongoose.connect()` in the 'reconnectFailed' error handler?

**Comment by hardcodet** [comment]
@vkarpov15 

Yes, if I comment out `await db.disconnect();`, I'm ending up with the following exception:

> 'You can not `mongoose.connect()` multiple times while connected.',

As you can see in the snippet above, my reconnect is invoked _only_ from within the `reconnectFailed` event listener.

The repro on my side is easy:

- start the application with MongoDB running (in my case, that's a local Docker container)
- Pause the MongoDB container
- Wait until reconnects fail an `reconnectFailed` is invoked, then try to connect again (as in the snippet above)

**Comment by hardcodet** [comment]
I also just added a console output for the ready state within my  `reconnectFailed` listener, and it's indeed `1`. My guess would be that "network issues" trigger different internal events. (Side note:  I also could break the AMQP library with just taking the Docker container out of commission. I guess sockets in Node are tricky (but I'm not very experienced with the stack yet)).

In any case, I can reliably repro that mongoose thinks it has a healthy connection even though it triggers the `reconnectFailed` event.

**Comment by vkarpov15** [comment]
We removed the 'You can not mongoose.connect() multiple times while connected.' error in 5.6.5: https://github.com/Automattic/mongoose/blob/master/History.md#565--2019-07-17 . So if you upgrade, you should be able to work around this issue.

It is very strange that you see `readyState = 1` after `reconnectFailed`. Do you get a 'disconnected' event when you pause the MongoDB container? Also, are you connecting to a standalone server or replica set?

**Comment by hardcodet** [comment]
Sorry for the delay - only just got back to work - I will try to get back to you within the next 2 days...

**Comment by hardcodet** [comment]
@vkarpov15 I upgraded to `5.6.7`, and I can confirm that I'm getting the `disconnected` event. It is being issued _after_ the `reconnectFailed` event though:

1: `reconnectFailed - readyState: 1`
2: `disconnected - readyState: 0`

Maybe this is just about timing and updating the internal state flags?

**Comment by vkarpov15** [comment]
I'm gonna guess it is a standalone as well. Are you using any other mongodb related libraries, like connect-mongo? Maybe show me the output of `npm list | grep "mongo"`? I'm at a loss to explain how you could get [`reconnectFailed`](https://masteringjs.io/tutorials/mongoose/connect) before `disconnected`.

Also, now that the 'You can not mongoose.connect() multiple times while connected.' error is gone, do you still have an issue here?

**Comment by hardcodet** [comment]
@vkarpov15 I'm only using mongoose:

```
+-- mongoose@5.6.7
| +-- async@2.6.2
| | `-- lodash@4.17.15
| +-- bson@1.1.1
| +-- kareem@2.3.0
| +-- mongodb@3.2.7
| | +-- mongodb-core@3.2.7 deduped
| | `-- safe-buffer@5.2.0
| +-- mongodb-core@3.2.7
| | +-- bson@1.1.1 deduped
| | +-- require_optional@1.0.1
| | | +-- resolve-from@2.0.0
| | | `-- semver@5.7.0 deduped
| | +-- safe-buffer@5.2.0
| | `-- saslprep@1.0.3
| |   `-- sparse-bitfield@3.0.3
| |     `-- memory-pager@1.5.0
| +-- mongoose-legacy-pluralize@1.0.2
```

May main issue is gone, so I'll be fine. Feel free to close this, or ping me if I can do anything to help you triangulate this. Thanks for the support and all the good work!

**Comment by hardcodet** [comment]
If it helps for a repro, here's the connection code I use (Typescript). I'll just paste it as it is (commented out section was my root issue):

    public async initMongoDb(attemptCounter = 0, subscribeToEvents = true) {
        const logger = this.logger;
        const config = this.config;

        try {
            // perform connect
            attemptCounter++;
            const uri: string = this.config.mongoDbUri;

            const options = {
                user: config.mongoDbUser || undefined,
                pass: config.mongoDbPass || undefined,
                useNewUrlParser: true,
                reconnectTries: config.mongoDbReconnectAttempts || 10,
                reconnectInterval: config.mongoDbReconnectInterval || 1500,
                connectTimeoutMS: config.mongoDbConnectTimeoutMs || 3000,
                socketTimeoutMS: config.mongoDbSocketTimeoutMs || 8000,
            };
            logger.debug("Initializing MongoDB", {name: "dbConnectionOptions", ...options});
            const db: Mongoose = await mongoose.connect(uri, options);

            if (subscribeToEvents) {

                // register event listener to track connection losses
                mongoose.connection.on("error", err => {
                    logger.error(`MongoDB connection lost (error) @ ${config.mongoDbUri}! Auto-retry is active - check for reconnect event...`, err);
                });

                mongoose.connection.on("reconnectFailed", async err => {
                    try {
                        // all reconnection attempts failed - log fatal right away
                        logger.fatal(`MongoDB auto-reconnection failed @ ${config.mongoDbUri}! Attempting to reset the connection...`, err);

                        try {
                            if (mongoose.connection.readyState !== 0) {
                                logger.warn(`Mongoose issued a 'reconnectFailed' event, but doesn't reflect it (readyState is ${mongoose.connection.readyState}).`);
                                // attempt a disconnect - in case of a network issue, mongoose my still thinks the connection is healthy
                                // repro: connect to a Rabbit container, pause the container after initial connect
                                // see https://github.com/Automattic/mongoose/issues/7991
                                // await db.disconnect();
                            }
                        } catch (e) {
                            logger.error("Disconnect on MongoDb during 'reconnectFailed' caused an error. Ignoring the exception - if the reconnect now fails, this is logged separately.", e);
                        }

                        // start a new connection attempt
                        await PromiseUtil.delay(1500);
                        this.initMongoDb(0, false);
                    } catch (e) {
                        logger.fatal("Attempting to recover from MongoDb reconnect error failed with another exception. The data tier is dead now!", e);
                    }
                });

                mongoose.connection.on("reconnected", err => {
                    logger.info(`MongoDB reconnection success @ ${config.mongoDbUri}`, err);
                });
            }

            logger.info("Successfully connected to MongoDb");
        } catch (e) {
            // mongoose doesn't recover automatically from this kind of exception - reconnect manually
            logger.fatal(`Failed connect to MongoDB @ ${config.mongoDbUri} (attempt #${attemptCounter})! Will retry...`, e);
            await PromiseUtil.delay(2000);
            await this.initMongoDb(attemptCounter, false);
        }
    }
