### ISSUE TITLE
Query executed before calling exec

### ISSUE THREAD

**Issue by ramiel** [Automattic/mongoose#7992]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If I define a function like this

```js
  const getOrCreateQuery = async ({ userId }) => {
    await ... // some async code here

    const query = Model.findOneAndUpdate(
      { user: userId },
      {},
      {
        new: true, upsert: true, setDefaultsOnInsert: true, runValidators: true,
      },
    );
    return query;
  };
```

when I call it

```js
const query = await getOrCreateQuery({ userId: ... });
```
I expect query to be a Query instance, instead it is the found document. From the documentation I understand that the query should not be executed, but it is. What is wrong here?

**If the current behavior is a bug, please provide the steps to reproduce.**

As before

**What is the expected behavior?**
The query should be returned for chaining.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 10.16.0
mongoose: 5.6.4
mongoDB: 3.4

**Comment by vkarpov15** [comment]
@ramiel that is because Mongoose queries have a `then()` function ([more info here](https://mongoosejs.com/docs/queries.html#queries-are-not-promises) ), so you cannot return a query from an async function without executing it. The workaround is to wrap the query in a POJO:

```javascript
const getOrCreateQuery = async ({ userId }) => {
  // ...
  return { query };
};

// Later
const { query } = await getOrCreateQuery({ userId: ... });
```

**Comment by ramiel** [comment]
Ok, thank you
