### ISSUE TITLE
Moving items in field of type "Array of String" does not saved

### ISSUE THREAD

**Issue by Zagonine** [Automattic/mongoose#7993]
Moving items in field of type "Array of String" does not saved. 

This simple code reproduce this behavior: 

```javascript
const mongoose = require('mongoose')

const AcmeSchema = new mongoose.Schema({
  arrayOfString: [String]
})

AcmeSchema.pre('save', function() {
  console.log(this.modifiedPaths())
})

const AcmeModel = new mongoose.model('acmes', AcmeSchema)

const acme = new AcmeModel({
  arrayOfString: ['first', 'second', 'third']
})

acme.save(_err => {
  const tmpValueFirst = acme.arrayOfString[0]
  const tmpValueSecond = acme.arrayOfString[1]

  acme.arrayOfString[0] = tmpValueSecond
  acme.arrayOfString[1] = tmpValueFirst

  acme.save()
})
```

We can see, when adding some items in `arrayOfString` this is working, but when try to moving some items, the field is not mark as modified, so not updated in database.

Mongoose: 5.6.4
Node version: 10.16.0
MongoDB: 4.0.10

**Comment by vkarpov15** [comment]
See [the first question on the FAQ](https://mongoosejs.com/docs/faq.html). Use `acme.arrayOfString.set(0, tmpValueSecond)` as a workaround
