### ISSUE TITLE
how to pull nested object in array by condition _id

### ISSUE THREAD

**Issue by shipcake** [Automattic/mongoose#7995]
hi. I stuck how to pull nested array in 1 document I use findOneAndUpdate And I map _id like [_id1,_id2,...] how to find condition and pull them.

mongodb and I highlight pull them out by _id condition data._id
https://ibb.co/8mkHngS

My code
https://gist.github.com/shipcake/c5e2221a25c9032f04c2931435aa0fcc

**Comment by vkarpov15** [comment]
`products.findOneAndUpdate({}, { $pull: { 'property_type.$[].subtypeid': id } })`. [Here's some more info on the all positional operator in Node](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html#using-array-filters)
