### ISSUE TITLE
[Bug Report] ObjectID not valid from  Schema.Types.ObjectId

### ISSUE THREAD

**Issue by Bogdah9** [Automattic/mongoose#7996]
Mongoose version 5.6.1 

 Errore:`UnhandledPromiseRejectionWarning: ValidationError: Model validation failed: address.1.id: Cast to ObjectID failed for value "<Buffer 5d 31 c2 a5 54 32 36 2b 64 53 bc a6>" at path "id", address.0.id: Cast to ObjectID failed for value "<Buffer 5d 31 c2 a5 54 32 36 2b 64 53 bc a6>" at path "id"`

 `
const isValid = require('mongoose').Types.ObjectId.isValid
console.log('valid',isValid('5d31c2a55432362b6453bca6'))  //valid true`

 Schema = `{
..,
  address:[ 
    {
      id: {
       type:Schema.Types.ObjectId,
       required: [true, c.E.REQUIRED],
       ref:'Model2'
      },
      kind: {
       type:String,
       default:'reg',
       validator: function(val){
         if(val!=='reg' && val!=='fact') return c.E.INVALID
       }
      },
      _id:false
    }
  ],
....
}`

This error works very randomly.

**Comment by vkarpov15** [comment]
Can you show me the output of your `npm list | grep "mongo"`? This sort of thing usually happens when you're getting an ObjectId from a different version of mongodb / mongoose.

**Comment by Bogdah9** [comment]
I found a problem. It consisted in the fact that I addressed the array ObjectId, not Objects. And in ObjectId itself there is an id field. ObjectId.id = <Buffer ...>. So this is not an idea. And all this assignment was pseudo random (1/3) * 100%. Sorry to be distracted
