### ISSUE TITLE
TypeError: mongoose.use is not a function

### ISSUE THREAD

**Issue by simonflk** [Automattic/mongoose#7998]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

https://mongoosejs.com/docs/guide.html#autoIndex describes setting `mongoose.use('autoIndex', false)`, but mongoose.use is not a function

The same page also says to use this function to override the default value of `autoCreate`

I believe that it should instead be instructing to call `mongoose.set('autoIndex', false)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');
mongoose.use('autoIndex', false);
```

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose@5.5.15
nodejs@12.4.0

**Comment by vkarpov15** [comment]
Fixed in master and fix will be in 5.6.6, thanks for reporting :+1:
