### ISSUE TITLE
Conditionally immutable fields

### ISSUE THREAD

**Issue by behzadnm99** [Automattic/mongoose#8001]
hello. i want to set permission on schemas. i want to dont let users to edit some fields of schemas.
and i want the admin user can do all operation on all schema
please help me.

**Comment by vkarpov15** [comment]
Right now you would need to handle this in your application using something like lodash's omit function. For example:

```javascript
const disallowEdit = {
  admin: [],
  user: ['adminOnlyField']
};

app.put('/user/:id', function(req, res) {
  const update = _.omit(req.body, disallowEdit[req.role]);
  User.updateOne({ _id: req.params.id }, update).then(() => res.json({ ok: 1 }));
});
```

We should add the ability to make fields conditionally [immutable](https://mongoosejs.com/docs/api/schematype.html#schematype_SchemaType-immutable) to make this easier.
