### ISSUE TITLE
perform single query count on model with array of ids?

### ISSUE THREAD

**Issue by gpbaculio** [Automattic/mongoose#8005]
i have this code, a book can have many comments, i want to put their counts on an array

`const bookCommentsLoader = new DataLoader(async bookIds => {
  const comments = await Comment.count({
    bookId: { $in: bookIds }
  })
  ...
})`

the problem with graphql dataloader is that, when returned, the result and length of ids must match, so i want it to return this this:

`model id-> ['1','3','12'] must return model counts like [5,7,1]`

i dont want to use loop caust it will send multiple query, i want to use single query, help?

**Comment by vkarpov15** [comment]
You could always just do `const comments = await Comment.find({ bookId: { $in: bookIds } })` and group the comments in your application.

I'd recommend considering the multiple query approach. [Many fast queries is better than one slow query in MongoDB](http://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs)
