### ISSUE TITLE
Support options arg for `distinct()`: Model.distinct() doesn't have { session }

### ISSUE THREAD

**Issue by exentrich** [Automattic/mongoose#8006]
Unlike other methods `distinct()` doesn't have { session } option.
How to workaround it?

**Comment by Fonger** [comment]
You can use it this way
```js
Model.distinct(...).setOptions({ session: exampleSession })
```

The reason why distinct doesn't support options in this function is that we can't distinguish the input object is for `conditions` or `options` since both of them are optional.

**Comment by exentrich** [comment]
Thank you for clarification!
