### ISSUE TITLE
withTransaction() mentioned in the docs doesn't exist in the code.

### ISSUE THREAD

**Issue by tomdee** [Automattic/mongoose#8009]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The docs at https://mongoosejs.com/docs/transactions.html refer to a withTransaction() helper, but that doesn't exist in the code.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
That the code and the docs match.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 12.5, mongoose 5.6.6 and mongodb 4.x

**Comment by Fonger** [comment]
This is a feature coming from underlying MongoDB Node.js driver.

It's documented here.

https://mongodb.github.io/node-mongodb-native/3.2/api/ClientSession.html#withTransaction
