### ISSUE TITLE
[Bug] Array default with transfrom

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8012]
mongoose version: 5.6.6(NPM)
nodejs: 12.7.0

reproduce script:
```ts
import * as mongoose from "mongoose";

const testSchema = new mongoose.Schema({
    testArray: [{ default: ["testDefault"], type: String, lowercase: true }]
});

const testModel = mongoose.model("test", testSchema);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const doc = new testModel({});
    await doc.save();
    console.log(doc.toObject());

    await mongoose.disconnect();
})();
```

log
```
Mongoose: tests.insertOne({ testArray: [], _id: ObjectId("5d38883c65478f080346dfad"), __v: 0 }, { session: null })
{ testArray: [], _id: 5d38883c65478f080346dfad, __v: 0 }
```

current behavior: dosnt apply the default value when formatted so / has a "string" transform
wanted behavior: applys default value when formatted so

PS: i make this a question, because i dont know if this is an actual bug
and if there is actually an other issue having this problem, i didnt find it...

**Comment by vkarpov15** [comment]
Going to postpone this until 5.7.0 because I think this is a bit too risky for a patch release.

**Comment by hasezoey** [comment]
@vkarpov15 after testing it in mongoose@5.7.0 the initial example i gave, dosnt work, but others do

works:
```ts
import * as mongoose from "mongoose";

const testSchema = new mongoose.Schema({
  testArray: [{ type: String, lowercase: true }]
});

const testModel = mongoose.model("test", testSchema);

(async () => {
  mongoose.set("debug", true);
  await mongoose.connect(`mongodb://localhost:27017/verify`, {
    useNewUrlParser: true,
    useFindAndModify: true,
    useCreateIndex: true,
    autoIndex: true
  });

  const doc = await testModel.create({ testArray: ["MAKE ME LOWERCASE"] });
  console.log(doc.toObject());

  await mongoose.disconnect();
})();

// result:
// {"testArray":["make me lowercase"],"_id":"5d772503932ef4351940bff4","__v":0}
```

dosnt work:
```ts
import * as mongoose from "mongoose";

const testSchema = new mongoose.Schema({
  testArray: [{ default: ["testDefault"], type: String, lowercase: true }]
});

const testModel = mongoose.model("test", testSchema);

(async () => {
  mongoose.set("debug", true);
  await mongoose.connect(`mongodb://localhost:27017/verify`, {
    useNewUrlParser: true,
    useFindAndModify: true,
    useCreateIndex: true,
    autoIndex: true
  });

  const doc = await testModel.create({});
  console.log(doc.toObject());

  await mongoose.disconnect();
})();
// result:
// { testArray: [], _id: 5d77249e9341eb34490df597, __v: 0 }
```

so my assumption is that default dosnt get applied to arrays when defined so

**Comment by hasezoey** [comment]
@vkarpov15 is there some documentation that shows which options are "inner-Options" and which are "outer-options"?

**Comment by vkarpov15** [comment]
@hasezoey what is an inner-option and what is an outer-option? I do not understand these terms.

**Comment by hasezoey** [comment]
@vkarpov15 sorry if i was not clear:

```ts
new mongoose.Schema({
  testArray: {
    type: [{ type: String, inner_values: true }],
    outer_values: true
  }
})
```

does this clear what i mean?

**Comment by vkarpov15** [comment]
What you call "outer options" are just options for the array schematype, whereas inner options are the options for the array's nested schematype. So if you have `[{ type: String }]`, all options that are valid for string types are also valid for the "inner type".

**Comment by hasezoey** [comment]
so there is not an official documentation / api to use to get it?

i think it is confusing, because so i cant really confirm which types are valid where and where not

PS: i would need it for typegoose as shown here https://github.com/typegoose/typegoose/pull/29/files#diff-17dec77f694b959d451c11a845c30a77 , i think it current is a bit hacky, but when i understand you correctly, the only way currently

**Comment by vkarpov15** [comment]
Not currently. The issue is that the valid "inner options" depend on `type`. `type: String` means `enum`, etc. are valid as inner options. So you need logic to switch on the `type` option.

Would it help if we had a separate `SchemaTypeOptions` class, with corresponding `StringTypeOptions` that inherits from `SchemaTypeOptions`? We've been meaning to do that anyway.

**Comment by hasezoey** [comment]
*Sorry for the delayed answer*

it would definitely help, could i know how to access it? is it accessible like `mongoose.Schema.TypeOptions` & `mongoose.Schema.TypeOptions.StringTypeOptions?` or will it be different?

**Comment by vkarpov15** [comment]
@hasezoey `mongoose.Schema.Types.String.prototype.OptionsConstructor`, `mongoose.Schema.Types.Number.prototype.OptionsConstructor`, etc.

**Comment by hasezoey** [comment]
*will it be in 5.7.4?*
thanks for the implementation, could you could give me (when fully implemented) a link to the doc's for this?

**Comment by vkarpov15** [comment]
Sorry I missed this comment. We need to also add these new options classes to the docs

**Comment by hasezoey** [comment]
Thanks for implementing it and for the documentation, but now where i try to implement it, i got some question on *how* to use it, because:
- `mongoose.Schema.Types.String.prototype.OptionsConstructor instanceof mongoose.SchemaTypeOptions` returns `false`
- and (example) `trim` dosnt exists on `mongoose.Schema.Types.String.prototype.OptionsConstructor`

what i more fully mean:
```ts
// logger is npm package "log-level"
const returnObject = {
  type: [{
    type: Type
  }]
};

// @ts-ignore
if (Type.prototype.OptionsConstructor instanceof mongoose.SchemaTypeOptions) { // returns false
  for (const [key, value] of Object.entries(options)) {
    if (key in Type.prototype.OptionsConstructor) { // when disabling the "returns false" check above, this always takes the else route
      logger.debug('Value is in OC:', key);
      returnObject.type[0][key] = value;
    } else {
      logger.debug('Value is not in OC:', key);
      returnObject[key] = value;
    }
  }

  logger.debug('final obj', returnObject);
}
```

am i just using it wrong? @vkarpov15

**Comment by vkarpov15** [comment]
`mongoose.Schema.Types.String.prototype.OptionsConstructor` is the constructor used to instantiate options, not an instance of options. For example, you'll see `mongoose.Schema.Types.Boolean.prototype.OptionsConstructor === mongoose.SchemaTypeOptions`. And, similarly:

```javascript
> Object.getOwnPropertyDescriptor(mongoose.Schema.Types.String.prototype.OptionsConstructor.prototype, 'trim')
{ value: null,
  writable: true,
  enumerable: true,
  configurable: true }
> 
> Object.getOwnPropertyNames(mongoose.Schema.Types.String.prototype.OptionsConstructor.prototype)
[ 'constructor', 'enum', 'match', 'lowercase', 'trim', 'uppercase' ]
> 
```

Sorry for the long stream of dots and prototypes. Might be easier to just export `mongoose.SchemaStringOptions` so you can do `Object.getOwnPropertyNames(mongoose.SchemaStringOptions.prototype)`

**Comment by hasezoey** [comment]
> Sorry for the long stream of dots and prototypes. Might be easier to just export

im fine with it, as long as it is consistent

---

> For example, you'll see `mongoose.Schema.Types.Boolean.prototype.OptionsConstructor === mongoose.SchemaTypeOptions` = `true`

but `mongoose.Schema.Types.String.prototype.OptionsConstructor === mongoose.SchemaTypeOptions` = `false`

-> it seems like `Schema.Types.Boolean` does not have an entry in `lib/options`, just wanted to share that, might be right so or forgotten, i dont know

---

it seems the type `Schema.Types.String` is missing some options, like `maxlength`, `minlength` @vkarpov15 

---

Thanks for this, it made the typegoose code more understandable & maintainable instead of having to redefine the options when mongoose updates :)

**Comment by vkarpov15** [comment]
No but `mongoose.Schema.Types.String.prototype.OptionsConstructor` is a class that inherits from `mongoose.SchemaTypeOption`.
