### ISSUE TITLE
Virtual fields are null when creating new documents.

### ISSUE THREAD

**Issue by chukwumaijem** [Automattic/mongoose#8014]
I have a model with virtual fields
```
const PeopleSchema = new mongoose.Schema({
  name: { type: String, default: 'Untitled idea', maxLength: 2000 },
  post_ids: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Post' }],
  image_ids: [{ type: mongoose.Schema.Types.ObjectId, ref: 'ImageSource' }],
},
{
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
});

PeopleSchema.virtual('posts', { ref: 'Post', localField: 'post_ids', foreignField: '_id' });
PeopleSchema.virtual('images', { ref: 'ImageSource', localField: 'image_ids', foreignField: '_id' });
```

When I do `PeopleSchema.find()`, I get 
```
name: "person_name"
posts:[]
images:[]
__v: 0
_id: "5d38953a9cd68f00fa0c2128"
```
Which is what i expect to get. But when i create a new person, like
```
    const newPerson = new PeopleSchema({
      name: req.user.name,
    });
```
the newPerson returned has
```
name: "person_name"
post_ids: []
posts: null
image_ids: []
images: null
__v: 0
_id: "5d38953a9cd68f00fa0c2128"
```

I'm using MongoDB 3.6.10, Mongoose=4.5.4,Node.js=8.14

Are post_ids and image_ids supposed to be returned when new documents are created? If not, what am i doing wrong.

**Comment by vkarpov15** [comment]
This is currently by design - if a populate virtual isn't populated, the value of the virtual will be `null`. However, `image_ids` and `post_ids` will not be `null`, because [Mongoose arrays have an implicit default value](https://mongoosejs.com/docs/schematypes.html#arrays) of `[]`.
