### ISSUE TITLE
aggregate's pre hook not support changing the pipline

### ISSUE THREAD

**Issue by inseptember** [Automattic/mongoose#8017]
**Do you want to request a *feature* or report a *bug*?**
I guess it's a bug
**What is the current behavior?**
aggregate's pre hook not support changing the pipline; but when using the aggregate's cursor, then it is OK.
**If the current behavior is a bug, please provide the steps to reproduce.**

schema.pre('aggregate', function(next) {
    this.append({ $lookup: options });
    next();
  });
I guess it's the lib/aggregate.js#L959, the pipeline passing to collection.aggregate cannot be changed. But the lib/cursor/AggregationCursor.js#L58 use the _pipline directly
**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Repro script:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh8017`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String });
  schema.pre('aggregate', function(next) {
    this.append({ $match: { name: 'foo' } });
    next();
  });
  const Model = mongoose.model('Test', schema);

  await Model.aggregate([{ $project: { name: 1 } }]);
}
```
