### ISSUE TITLE
Feature: On / Off per HTML spec as boolean castable string values

### ISSUE THREAD

**Issue by DevBrent** [Automattic/mongoose#8019]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** "on" is no longer cast as true for Boolean fields.

**What is the expected behavior?** "on" and "off" should be cast as true/false like "yes" and "no"

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.** 5.6.6

It looks like in Mongoose 5.X only specific string values are permitted to be cast as Boolean. The default value for a checkbox in HTML spec is "on".

By default, unchecked checkboxes simply do not pass a value when forms are serialized but it might make sense to include an "off" counterpart for falsey conversion.

Thoughts? This can improve native compatibility with form submissions from HTML forms. I am not certain of potential negative impacts. This also restores Pre-5.X functionality for input checkbox form submissions while maintaining the improvements in boolean casting introduced.

While I agree that `converting any non falsy value to true` is too permissive, "on" and "off" are clearly boolean values.

Related:
https://github.com/Automattic/mongoose/pull/5344#issuecomment-406161112

**Comment by vkarpov15** [comment]
We'll consider adding this in a minor release since it is fairly common. However, adding support for 'on/off' is a two-liner, see [boolean schematype docs](https://mongoosejs.com/docs/schematypes.html#booleans).

```javascript
mongoose.Schema.Types.Boolean.convertToTrue.add('on');
mongoose.Schema.Types.Boolean.convertToFalse.add('off');
```
