### ISSUE TITLE
reference the nested document in a mongoose array

### ISSUE THREAD

**Issue by true-doc** [Automattic/mongoose#8023]
I have a mongoose schema which has an array I want to reference a document
that is nested inside that array from another schema. How can I go about it.

This is my schema

	var userSchema = mongoose.Schema({
		username: String,
		first_name 		: String,
		last_name		: String,
		exam_test_id	:{
			type			: Schema.Types.ObjectId,
			ref				: 'department.members'
		}
	});

	var departmentSchema = mongoose.Schema({
		name				: String,
		description			: String,
		members				:[{
			commencement_date	: Date, 
			post				: String,
			function			: String
		}]
	})

I am confused whether that ref is appropriate, if it is not right is there another 
way I can go about it while still have a nested sub document

**Comment by vkarpov15** [comment]
I think you're looking for [populate virtuals](https://mongoosejs.com/docs/populate.html#populate-virtuals).

```javascript
var userSchema = mongoose.Schema({
	username: String,
	first_name 		: String,
	last_name		: String,
        examTestId: Schema.Types.ObjectId
});

userSchema.virtual('examTest', {
  ref: 'Department',
  localField: 'examTestId',
  foreignField: 'members._id'
});
```
