### ISSUE TITLE
Dose transaction can only run Serially at the sametime?

### ISSUE THREAD

**Issue by albertyou2** [Automattic/mongoose#8025]
mongoose : 5.6.7
mongodb : 4.0.9
centeos: 7.0
nodejs:v11.14.0

......
const session = await app.mongoose.startSession({ // egg-mongoose is a very simple ware for mogoose!
   readPreference: { mode: 'primary' },
});

await session.startTransaction({
     readConcern: { level: 'snapshot' },
      writeConcern: { w: 'majority' },
  });

teacher = await app.model.RoleMap.findOneAndUpdate(
            { _id: body.teacherIds[i] },
            { $pull : { role : "teacher" }},
            { new: true, session :session }
  );

await app.model.Class.updateOne({_id: e._id}, {teachers},{ session });
 await session.commitTransaction(); // 

......

### 

then I test this by use these codes:
// simulate 2 request send at the sametime!
var opt = {
	method:'POST',
	url:`https://${host}/api/role/del`,
  json:true,
  headers:
  body: {"teacherIds":["5d3d067ce4a51b0394b89b7b"]},
}

var opt1 = {
  method:'POST',
  url:`https://${host}/api/role/del`,
  json:true,
  body: {"teacherIds":["5d3d068ee4a51b0394b89b7c"]},
}

request(opt,(err,res,body)=>{ //reques one 
    if(err){
      console.log(err);
      return;
    }
    console.log(body);
    console.log(res.headers);
});

request(opt1,(err,res,body)=>{  //reques two  
    if(err){
      console.log(err);
      return;
    }
    console.log(body);
    console.log(res.headers);
});

i found that somtimes olny one teahcer data was updated successfully, somtimes NOT any one can be updated!

Am I missing sth important?Does any one hit this problem?

**Comment by vkarpov15** [comment]
I don't understand the question, can you please clarify what you mean by "i found that somtimes olny one teahcer data was updated successfully, somtimes NOT any one can be updated!"?

**Comment by albertyou2** [comment]
@vkarpov15 
Really sorry , These days I found that was my fault.
I made a mistake in Test script.
Sorry again
