### ISSUE TITLE
Clarification about `module.exports = exports` approach on mongoose plugins

### ISSUE THREAD

**Issue by LucGranato** [Automattic/mongoose#8026]
**Do you want to request a *feature* or report a *bug*?**
*Clarification*

In most mongoose plugin is common to see the following exportation approach.

```javascript
module.exports = exports = function myPlugin(schema, options) {
  //plugin code...
}
```

Is there any problem removing the `exports`?

```javascript
module.exports = function myPlugin(schema, options) {
  //plugin code...
}
```

I would like to understand what is the consequence of using `module.exports = exports` exportation.

It's something related to ES6 import?

Thanks!

**Comment by vkarpov15** [comment]
Nope, in this case `module.exports = exports` causes confusion and doesn't provide any value. There's no problem in removing `exports`.
