### ISSUE TITLE
Maximum times mongoose.connect() not connecting to mongodb and not getting any error

### ISSUE THREAD

**Issue by zack1991** [Automattic/mongoose#8029]
Mongoose : 4.13.19
Node : 8.12.0

```
mongoose.Promise = global.Promise;

mongoose.connection.on('connected', function () {
    console.log("MongoDB event connected");
    createServer(app);
});

mongoose.connection.once('open', function () {
    console.log('Connection to mongodb database is open');
});

mongoose.connection.on('disconnected', function () {
    console.log("MongoDB event disconnected");
});

mongoose.connection.on('reconnected', function () {
    console.log('MongoDB event reconnected');
    createServer(app);
});

mongoose.connection.on('error', function (err) {
    console.log('MongoDB event error: ' + err);
});

mongoose.connect(configDB.url, {
    keepAlive: 3000,
    useMongoClient: true, //Needed in mongoose older version <= 4.13.8
    autoIndex: false, //false
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 500, //In milliseconds
    poolSize: 50, //default maxPoolSize is 100 and default minPoolSize is 5,  Increase poolSize if Concurrent Users increase
    socketTimeoutMS: 60000, //Close sockets after 45 seconds of inactivity
}).then(() => {
    console.log("Database connected successfully");
}).catch(err => {
    console.log('App starting error:' + err.stack);
});

```

Previously i was using the mongoose version 4.13.8, it was running perfect, but it has the some issues that was resolved in later version thats why i updated it to 4.13.19. After updating i am getting the issue.

**Comment by vkarpov15** [comment]
What exactly is the issue? Is there some error message?

**Comment by zack1991** [comment]
The problem is i am not getting any error message and control is not going inside the then method of mongoose.connect(). This only happening for mongoose version > 4.13.8 and <= 4.13.19.
This is not happening all the time sometimes it connected easily with the database.

**Comment by vkarpov15** [comment]
What version of MongoDB are you connecting to? Also, are you connecting to a standalone MongoDB instance, replica set, or sharded cluster? Are you connecting to Atlas?

**Comment by SanchitB23** [comment]
I have the same issue, Mongoose is not connecting to MongoDB, I am using Atlas. 
`  console.log("Test", mongoURI);

  const m = await mongoose.connect(mongoURI, {
    useNewUrlParser: true,
    dbName: 'Users'
  }, (onerror) => console.log("Err", onerror))
      .then(r => console.log("Then", r))
      .catch(r => console.log("Catch", r))
      .finally(r => console.log("Finally", r));
  console.log("Test2", m);`

After about 10-20sec This appears in the console

![image](https://user-images.githubusercontent.com/24359070/62647009-37c8ef80-b96d-11e9-9ad3-25ab3266cbfc.png)

**Comment by agharshit08** [comment]
The problem can be in your cluster which is finding it hard to connect you may try changing network access IP to 0.0.0.0

**Comment by vkarpov15** [comment]
@SanchitB23 are you able to connect using the mongodb shell? Are you copying the URI from Atlas? What version of Mongoose are you using?

**Comment by SanchitB23** [comment]
> 
> 
> @SanchitB23 are you able to connect using the mongodb shell? Are you copying the URI from Atlas? What version of Mongoose are you using?

@vkarpov15 Do I need to install Mongodb shell to use Atlas? 
Yes, I am copying my URI from Atlas.
Mongoose Version: `5.6.8`

**Comment by vkarpov15** [comment]
@SanchitB23 you do not need to download the mongo shell to use Atlas. We just use it to debug connection issues, because if both the mongo shell and mongoose can't connect, then odds are the issue isn't with mongoose

**Comment by SanchitB23** [comment]
> 
> 
> @SanchitB23 you do not need to download the mongo shell to use Atlas. We just use it to debug connection issues, because if both the mongo shell and mongoose can't connect, then odds are the issue isn't with mongoose

Okay thank you for this Information, Apparently, when I used Mongo shell, This is the following error that is shown now.

```
mongo "mongodb+srv://feedbuzz-dev-rjypb.mongodb.net/test" --username sanchitb23      
                            DNSHostNotFound: Failed to look up service "":This operation returned because the timeout period expired.     try 'mongo --help' for more information 
 ```

The IP Address wasn't the problem it seems.

**Comment by Mdsp9070** [comment]
I'm having this same issue and my database has access to any IP. My mongo version is `4.2.6 `and on atlas is the same, so what could be the root of the problem? Only connected to node when I selected version `2.2.12` or later. My node version is `14.2.0`.

**Comment by vkarpov15** [comment]
@Mdsp9070 please open a new issue and follow the issue template.
