### ISSUE TITLE
[Question] how can i filter some properties before query?

### ISSUE THREAD

**Issue by highalps** [Automattic/mongoose#8038]
mongoose: ^5.6.3
node: v11.13.0

i apply 'softDelete' plugin that set deletedAt as new Date() and status as 'inactive'
when trying to using static method 'delete', 'deleteById'

```
export default function (schema: Schema, _options?: SchemaOptions) {
    schema.add({
        deletedAt: Date,
        status: String
    })

    schema.statics.delete = function (query) {
        return this.findOneAndUpdate(query, {
            deletedAt: new Date(),
            status: 'inactive'
        })
    }

    schema.statics.deleteById = function (id) {
        return this.findByIdAndUpdate(id, {
            deletedAt: new Date(),
            status: 'inactive'
        })
    }
```

i want to filter by status property when using find queries (find, findOne, findById,.. and with aggregate with $match pipeline also)

for example,

```
Model.find({})  => active only
Model.findById('....') => return document or null if status inactive
Model.aggregate({ $match: { level: 0 }) => return level 0 document with status 'active'
```

i don't want write down condition { status: 'active } in every mongoose query

how can i do this?

**Comment by vkarpov15** [comment]
Middleware is your best bet. Add `this.where({ status: 'active' })` to `schema.pre('find')`, `schema.pre('findOne')`. In `schema.pre('aggregate')`, you can do `this.pipeline().unshift({ $match: { status: 'active' } })`

See:

* https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-pipeline
* https://mongoosejs.com/docs/api/query.html#query_Query-where
