### ISSUE TITLE
[BUG] Version error and memory leak

### ISSUE THREAD

**Issue by LaurensRietveld** [Automattic/mongoose#8040]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What happens:**
- After recently updating mongoose, we've experienced a memory leak. 
- When saving a document, a version-error is created and saved to `this.$__.$versionError`
- When creating this version error it runs a captureStacktrace command. Capturing the stack means references to it's stack (for us that included CLS, requests, etc) are retained. This is related to [this nodejs issue](https://github.com/nodejs/node/issues/4910)
- As a result, the errors and their stack are not garbage collected. With many save operations this would cause our process to run out of memory

**Why this didnt happen before**
- In [this commit](https://github.com/Automattic/mongoose/commit/ae8206280fa9861495b6bcf62a8fc7b5d6ca60bf) the versionerror is stored in   `this.$__.$versionError` instead of `options.$versionError`
- The options object is cleaned up after a save (see [here](https://github.com/Automattic/mongoose/blob/ae8206280fa9861495b6bcf62a8fc7b5d6ca60bf/lib/model.js#L471)). The `this.$__.$versionError` however isnt

**Workaround**
- Using a post-save hook that deletes `this.$__.$versionError`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.6.3
node: v10.16.0
mongo: 3.4.1

cc @thombohlk

**Comment by vkarpov15** [comment]
Fix will be in 5.6.9 within the next 48 hours :+1:

**Comment by LaurensRietveld** [comment]
@vkarpov15  an@Fonger : This is still an issue 5.7.5. We still experience a memory leak when we remove our post-save hook that deletes the versionError manually.
It seems the above fix contains a typo. `delete this.$__.versionError;` should be `delete this.$__.$versionError;`

**Comment by Fonger** [comment]
Sorry it's my bad. A revised PR has submitted #8326
