### ISSUE TITLE
this.parent() returns undefined in validation function when using Model.update()

### ISSUE THREAD

**Issue by hamit-zor** [Automattic/mongoose#8041]
**Do you want to request a *feature* or report a *bug*?**
A feature

**What is the current behavior?**
Cannot access the parent documents within validation functions when using `Model.update()` with options `runValidators: true` and `context: 'query'`

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is what I mean:
```
(async function () {
  const mongoose = require('mongoose')

  const url = `mongodb://foo:bar@localhosst:27017/test`
  mongoose.connect(url, { useNewUrlParser: true })

  const Schema = mongoose.Schema

  const ChildSchema = new Schema({
    name: {
      type: String,
      validate: function () {
        console.log("this: ", this)
        console.log("parent :", this.parent && this.parent())
      }
    }
  })

  const ParentSchema = new Schema({
    child: ChildSchema,
    childs: [ChildSchema]
  })

  const ChildModel = mongoose.model('ChildModel', ChildSchema)
  const ParentModel = mongoose.model('ParentModel', ParentSchema)

  const parent = new ParentModel()
  const parentId = parent._id

  const child = new ChildModel({ name: 'Foo' })

  await ParentModel.updateOne(
    { id: parentId },
    { $set: { child: child }, $push: { childs: child } },
    { runValidators: true, context: 'query' })
  // this.parent() is undefined. if $set presents this.parent is also undefined

  parent.child = child
  parent.childs = [child]
  await parent.save()
  // this.parent() is correct

  process.exit(0)
})()
```

**What is the expected behavior?**
`this.parent()` should return correct document instead of undefined

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 10.16.0
Mongoose: 5.6.7
MongoDB : 4.0.6

**Comment by SmirnovM91** [comment]
How do you resolve it?

**Comment by vkarpov15** [comment]
@SmirnovM91 In this case, there's no way to work around it other than to use `save()`. In OP's case, the subdoc's `parent()` might not exist in memory. You can read more on the tradeoffs of [different ways to update a document in Mongoose](https://masteringjs.io/tutorials/mongoose/update).

**Comment by malka-rom** [comment]
what we can do on find function the parent is undefined too

**Comment by vkarpov15** [comment]
@malka-rom can you please clarify with some code samples?
