### ISSUE TITLE
not a bug, a design issue, but I am stuck, server returns an array why not a json

### ISSUE THREAD

**Issue by szklarca** [Automattic/mongoose#8047]
The below cited code is  part of a server side application Node(v8.12.0)/Express(v4.16). Mongoose(v4.13.12), MongoDB (v3.6.4) that I develop for for educational purposes;
I made a new model and a router based on the code that I know is working with other models and on other paths (see below);
The new thing is this double reference and double population;
It works only partially, there are the issues:
1) I get an array [] instead of a json {}; any idea why?
2) timestamps do not work
3) comments.author field inside dish does not get populated; why?

**// this is my model**
<
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const FavoriteSchema = new Schema({
  user:  { 
        type: Schema.Types.ObjectId, 
        ref: 'User'  },
    dishes:  [{ 
        type: Schema.Types.ObjectId, 
        ref: 'Dish' }] 
}, {
    usePushEach: true,
    timestamps: true
});
module.exports = mongoose.model('Favorite', FavoriteSchema);
>

**// this is my router**
<
favoriteRouter.route('/')
.options(cors.corsWithOptions, (req, res) => { res.sendStatus(200); })
.get(cors.cors, authenticate.verifyUser, (req, res, next ) => { 
  Favorite.find({ user: req.user._id })
  .populate('user')
  .populate('dishes')
    if (err) return next (err);
   res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.json(result); // should have returned {} why it is returning [{}]??
  })
});
>

the problem is that when I send a GET request to the /favorites/ the server returns an array inside which there is a json object I expect (see below);

<
[
    {
        "_id": "5d397562ecc7981d76be9e9f",

        "user": {
            "_id": "5d396cdeecc7981d76be9e9e",
            "username": "Fela",
            "__v": 0,
            "admin": false,
            "lastname": "",
            "firstname": "" },

        "__v": 2,

        "dishes": [
            {
                "_id": "5affe7b72ee9ee32dc8d8e1e",
                "updatedAt": "2018-05-19T11:40:04.687Z",
                "createdAt": "2018-05-19T09:00:39.092Z",
                "name": "Phappizza",
                "image": "images/uthappizza.png",
                "category": "mains",
                "price": 499,
                "description": "A unique combination ......",
                "__v": 1,
                "comments": [
                    {
                        "rating": 5,
                        "comment": "Can not be any better",
                        "author": "5af7eeeab00a562182a7380d",
                        "_id": "5b000d14c4fcd23bf6f98dc0"
                    }
                ],
                "featured": true,
                "label": "Hot"
            },
            {
                "_id": "5affe5c9fdb2023255d58d38",
                "updatedAt": "2018-05-19T08:52:25.052Z",
                "createdAt": "2018-05-19T08:52:25.052Z",
                "name": "Aghatathappizza",
                "image": "images/uthappizza.png",
                "category": "mains",
                "price": 499,
                "description": "A unique combi....",
                "__v": 0,
                "comments": [],
                "featured": true,
                "label": "Hot"
            }
        ]
    }
]
>
any suggestions greatly appreciated; can I design the model differently? 
Best. A

**Comment by sgatade** [comment]
You are using `.find()` which by default returns an Array of objects!

Documentation here [Mongoose Query](https://mongoosejs.com/docs/queries.html)

![image](https://user-images.githubusercontent.com/13362030/62409920-9cd3bc80-b5de-11e9-83b3-6b0512d85ec3.png)

Try using .findOne() to return a single & first matching object.

![image](https://user-images.githubusercontent.com/13362030/62409918-83cb0b80-b5de-11e9-8c20-67dbc6f2bef2.png)

Cheers!

**Comment by szklarca** [comment]
True!
Surprisingly (or not),  timestamps code works now, maybe it does not like an array. 
Best.

**Comment by sgatade** [comment]
Good to know it works, can you please close this issue?

Cheers!
