### ISSUE TITLE
Overwrite data in pre-validate hook

### ISSUE THREAD

**Issue by alexcaglairi** [Automattic/mongoose#8052]
Hi all,

i have a problem using the pre validate hook in a mongoose model.

What i want is to "overwrite" in the pre-validate hook the data that will bepassed to validation and post-validate .

My code is:

```
bookSchema.pre('validate', async function () {

  let test = Object.assign({},this._doc);

  ...

  test.field = 'abc';

  ...

  //What i have to do to pass "test" var to validate?

});
```
I need to pass my "test" object to validate and post validate method...I didn't find anything in documentation...

I need to overwrite passed data....How can i do?

**Comment by Ncifra** [comment]
You could just create a field inside the global scope like:

```
bookSchema.pre('validate', async function () {

  this.test = Object.assign({},this._doc);

  ...

  this.test.field = 'abc';

  ...

});
```

Also check out the other issue you opened, you seem to not respond anymore to your issues.

**Comment by vkarpov15** [comment]
@Ncifra 's solution is correct, although you should use [the `$locals` property instead](https://mongoosejs.com/docs/api/document.html#document_Document-$locals)

```javascript
this.$locals.test = Object.assign({}, this._doc);
```

Also, why are you copying the document and what do you mean by "passing my 'test' object to validate"?
