### ISSUE TITLE
Cast to ObjectId failed for value \"\" at path \"_id\""

### ISSUE THREAD

**Issue by Firebrand** [Automattic/mongoose#8060]
Hi guys, I've search long and hard for an answer to what seems like a pretty straightforward problem. This is my simple schema file:

> const mongoose = require("mongoose");
> const Schema = mongoose.Schema;
> 
> const PageSchema = new Schema({
>   name: String,
>   type: String
> });
> 
> const NavSchema = new Schema({
>   user_id: Schema.Types.ObjectId,
>   pages: [PageSchema]
> });
>
> module.exports = mongoose.model("Nav", NavSchema);`

This is the mutation I'm trying to perform:

> const addPage = async (navId, name, type, location) => {
> const nav = await Nav.findById(navId);
> const subdoc = await nav.pages.create({ name: name, type: type });
> nav.components.push(subdoc);
> return nav.save();
> }

When I try to run this I get the casting error mentioned in the title of this post. I have done console.log at different stages and found that everything is working correctly and all variables are exactly what they should be. The only part that causes this to fail is the last line: nav.save();

I appreciate the help

**Comment by Firebrand** [comment]
Nope had to do with existing stuff in the db itself

**Comment by vkarpov15** [comment]
Also, you can just push() a POJO, no need to explicitly call `create()` before `push()`
