### ISSUE TITLE
findById seems broken

### ISSUE THREAD

**Issue by Firebrand** [Automattic/mongoose#8061]
Pretty simple. This:

`const user= await User.findById(id);`

... gets converted by Mongoose into this (I have debug on):

`componentpages.findOne({ _id: ObjectId("5d50887dc6150a0048a77a5a") }, { projection: {} })`

Which is not executable by MongoDB at all. What's projection:{}? (Projections are supposed to be [fieldname]:bool).  If I cut that part out it works perfectly.

**Comment by Firebrand** [comment]
Nevermind. This is true, the generated query doesn't work in MongoDB but somehow Mongoose makes it work.

**Comment by vkarpov15** [comment]
The generated query is for the mongodb node driver, it doesn't necessarily line up exactly with the syntax the mongo shell expects. And the mongodb server has its own syntax under the hood for queries that both the mongo shell and the node driver convert to
