### ISSUE TITLE
Query when using .stream() method does not understand Strings as ObjectIDs or Dates

### ISSUE THREAD

**Issue by Hyperblaster** [Automattic/mongoose#8065]
When running a find() and then stream() as per below
```
Model.find({
 "_id":{
     "$in":["5aa8f1226744783cd807a817"]
 },
 "date":{
    "$gte":"2019-08-14T23:38:17.123Z"
  }
})
.lean()
.batchSize(100)
.stream();
```

Mongoose does not cast the  "5aa8f1226744783cd807a817" as an ObjectID, neither does it cast "2019-08-14T23:38:17.123Z" as a Date, it runs the query with those values typed as a String and doesn't return match the records from the database.

However running the same query with the .exec() method works correctly. 

```
Model.find({
 "_id":{
     "$in":["5aa8f1226744783cd807a817"...]
 },
"date":{
    "$gte":"2019-08-14T23:38:17.123Z"
  }
})
.lean()
.exec(function(err, docs) {

});

```

This has only been an issue since we upgraded to a recent version of Mongoose

**Comment by vkarpov15** [comment]
Which version of mongoose did you upgrade to? stream() is no longer supported, it's been replaced by cursor() : https://thecodebarbarian.com/cursors-in-mongoose-45

**Comment by vkarpov15** [comment]
@Hyperblaster what makes you think it is only loading one record at a time?

**Comment by Hyperblaster** [comment]
When swapping the code

.stream() to .cursor() as identified in that linked issue, and logging each entry as it is streamed to the console.

The stream batch size correlates with the speed of which each item is logged, (if i change the batchSize to 1 it is very slow and streams each document in series) if i change it to 1000 it is ~1000 times faster as it is streaming the documents in parallel.

Using the cursor() method it always logs out at the same speed as batchSize 1 even if batchSize is set to 1000. It’s clearly running in series one document at a time.

**Comment by vkarpov15** [comment]
I'm unable to find any indication that `cursor()` is orders of magnitude slower than `stream()`. Consider the below script:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  for (let i = 0; i < 10000; ++i) {
    let name = '' + i;
    for (let i = 0; i < 100; ++i) { name += 'a' }
    await Model.create({ name });
  }

  const startTime = Date.now();
  //const cursor = Model.find().lean().batchSize(1000).stream();
  const cursor = Model.find().lean().batchSize(1000).cursor();
  let count = 0;

  await new Promise(resolve => {
    cursor.on('data', () => ++count);
    cursor.on('end', () => resolve());
  });
  console.log('Time elapsed:', Date.now() - startTime);
  console.log('Num docs:', count);
}
```

Mongoose 5.7 using `cursor()`:

```
$ node gh-8039.js 
(node:1288) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:1288) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Time elapsed: 96
Num docs: 10000
^C
$ 
```

Mongoose 4.13 using `stream()`:

```
$ node gh-8039.js 
(node:1285) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
(node:1285) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
(node:1285) DeprecationWarning: Mongoose: Query.prototype.stream() is deprecated in mongoose >= 4.5.0, use Query.prototype.cursor() instead
Time elapsed: 77
Num docs: 10000
^C
$
```

How are you iterating through the stream?
