### ISSUE TITLE
validator function invoked multiple times for object

### ISSUE THREAD

**Issue by sashaaKr** [Automattic/mongoose#8067]
**Do you want to request a *feature* or report a *bug*?**
This is a bug report

**What is the current behavior?**
`validator` function invoked multiple times for objects - it seems that invocation done per each object key.

The code below under `mongoose@5.6.8` and `mongoose@5.6.9` will print:
```
array [{"_id":"5d53b5b465534b406ecc71fb","timer":{"time":{"type":{"hours":24,"allowed":true}}}}]
arrayItem { type: { hours: 24, allowed: true } }
arrayItem { hours: 24, allowed: true }
arrayItem 24
arrayItem true
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
function validateArray(array) {
  console.log('array', array);
}

function validateArrayItem(arrayItem) {
  console.log('arrayItem', arrayItem);
}

const itemArray = new Schema({
  timer: {
    time: {
      type: {
        hours: Number,
        allowed: Boolean,
      },
      validate: {
        validator: validateArrayItem,
        message: 'Invalid itemArray',
      },
    },
  },
});

const Obj = new Schema({
  items: {
    type: [itemArray],
    validate: {
      validator: validateArray,
      message: 'invalid items',
    },
  },
});

const obj = db.model('Obj', Obj);
    const nl = new obj({
      items: [
        { timer: { time: { type: { hours: 24, allowed: true } } } },
      ],
    });
await nl.save();
```

**What is the expected behavior?**
`validator`  function should be invoked once.
Previous code under `mongoose@5.6.7` will print:
```
array [{"_id":"5d53b55bf1b64c404a686939","timer":{"time":{"type":{"hours":24,"allowed":true}}}}]
arrayItem { type: { hours: 24, allowed: true } }
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node - v8.13.0
mongoose - 5.6.8, 5.6.9

**Comment by vkarpov15** [comment]
We'll look into this, but I suspect the issue will go away if you define your schema correctly. [Be careful with keys named 'type' in Mongoose](https://mongoosejs.com/docs/faq.html#type-key). Do this instead:

```javascript
const itemArray = new Schema({
  timer: {
    time: {
      type: {
        type: new Schema({
          hours: Number,
          allowed: Boolean
        }),
        validate: {
          validator: validateArrayItem,
          message: 'Invalid itemArray',
        }
      },
    },
  },
});
```

**Comment by qqilihq** [comment]
> but I suspect the issue will go away if you define your schema correctly. Be careful with keys named 'type' in Mongoose.

The issue affects us too, but in ours case there’s no “type” involved.

**Comment by vkarpov15** [comment]
@qqilihq can you please open up a separate issue with a repro script?
