### ISSUE TITLE
Instrument Mongoose

### ISSUE THREAD

**Issue by talr1** [Automattic/mongoose#8069]
Hi

I'm looking for away to instrument mongoose actions against the DB using opentracing.
this means that before any action i'd like to setup a span and when the action is done i'd like to finish the span which later on will be reported to the tracing back-end.

I've looked for various ways and i'm not sure what will be the right approach.
maybe writing a global plugin that will use schema hooks (pre, post, queries) on each model but that seems like error-prune as when there are new actions i'll need to update my plugin code.

i can't find any docs for model.on('') events, only error which does not help here.
it is unclear how model.events can be used.
I've found this but not sure it could fit: 
https://github.com/Automattic/mongoose/issues/2090#issuecomment-124159367

any help would be great

**Comment by vkarpov15** [comment]
Depends on what you specifically mean by "action". You can use a regexp with middleware:

```
schema.pre(/*/)
```

You can also try using mongoose debug mode: https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set

**Comment by talr1** [comment]
an action is anything my app is doing in mongodb: insert, update, delete, query
schema.pre(/*/) could be fine, but do i have the same schema.post(/*/) for each action?
i don't want to be left with an action in which i open span and which i can't close in a post..

as for the mongoose debug, i've already thought about it, but i was not sure if it actually run before the action is sent to mongodb or after. in either case i will still need a "before" and "after" context and the debug does not seem to provide it...

maybe an extension to the current debug could be nice (before & after callbacks)

**Comment by vkarpov15** [comment]
You're right, you'll have to do both `schema.pre(/.*/)` and `schema.post(/.*/)`. That's the best way to instrument all inserts, updates, queries, and deletes.

**Comment by talr1** [comment]
Thanks

 could be a nice feature to have a 2 "global" events "before" and "after" for any access from mongoose to mongdb. could be helpful for debugging and instrumentation in this case. 
or maybe extend the current debug mode.

with the current approach i'm not sure if 2 consecutive calls to the same model pre hook would be sync or async (or maybe this depends how i define the hook, sync or async). 
if it is async, i would have a problem open a span and close it it's 'post' hook as i could wrongly close an unfinished span (unless adding some 'magic' to detect the right one to close)

**Comment by talr1** [comment]
schema.pre(/.*/) and schema.post(/.*/) are already occupied
I assume i can't have a them and also a specific impl, lets say schema.pre('findOneAndUpdate')...

also, instrumenting the calls in each hooks will require too much work, and i was hoping to do it in a single global location for all db actions.

more than that, the code i aiming for is to be a generic one so i  could use it in many repo's and it won't be specific for one app.

having a global before/after db action, might help achieve this

**Comment by vkarpov15** [comment]
What do you mean by "schema.pre(/./) and schema.post(/./) are already occupied"?
