### ISSUE TITLE
Can't set updatedAt manually

### ISSUE THREAD

**Issue by schwarmco** [Automattic/mongoose#8071]
**Do you want to request a *feature* or report a *bug*?**

A Bug - or at least unexpected behaviour

**What is the current behavior?**

While trying to migrate from an sql database to mongodb, i wanted to keep the existing createdAt and updatedAt timestamps.

Having a model with `timestamps: true` option, you can't set `updatedAt` on insert as it's overwritten to `createdAt`'s value.

Trying to set `updatedAt` on existing documents also doesn't work, as it's get overwritten by current timestamp.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require('mongoose')

const schema = new mongoose.Schema({
    name: String
}, {
    timestamps: true
})
const Entity = new mongoose.model('Entity', schema)

mongoose.connect('mongodb://localhost/gh-8071').then(() => {
    const e = new Entity({
        name: 'test',
        createdAt: '2018-01-01 12:00:00',
        updatedAt: '2019-08-15 12:00:00'
    })
    e.save().then(() => {
        console.log(e)
        e.updatedAt = '2019-08-15 12:00:00'
        e.save().then(() => {
            console.log(e)
        })
    })
})
```

Outputs:
```
{ _id: 5d5575a5d7b20e1b6998d7b6,
  name: 'test',
  createdAt: 2018-01-01T11:00:00.000Z,
  updatedAt: 2018-01-01T11:00:00.000Z,
  __v: 0 }
{ _id: 5d5575a5d7b20e1b6998d7b6,
  name: 'test',
  createdAt: 2018-01-01T11:00:00.000Z,
  updatedAt: 2019-08-15T15:09:25.817Z,
  __v: 0 }
```

**What is the expected behavior?**

updatedAt should not be changed, if it's set.

https://github.com/Automattic/mongoose/blob/b41f93c0fc073c8a702f4c2101ed42d09705a5ca/lib/schema.js#L842-L852

A possible solution could be: 

```javascript
if (updatedAt && (this.isNew || this.isModified()) && !this.isModified('updatedAt')) { 
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS 11.12.0
MongoDB 4.0.8
Mongoose 5.6.4

**Comment by vkarpov15** [comment]
We'll make a workaround for this. The rationale for this behavior is that it should be safe to pass unsanitized user data into `new Model().save()` without risking corruption, and overwriting `updatedAt` is corruption

**Comment by vkarpov15** [comment]
Actually, upon further inspection, we already support this via the [`timestamps` option to `save()`](https://mongoosejs.com/docs/api/model.html#model_Model-save).

```javascript
const mongoose = require('mongoose')

const schema = new mongoose.Schema({
    name: String
}, {
    timestamps: true
})
const Entity = new mongoose.model('Entity', schema)

mongoose.connect('mongodb://localhost/gh-8071').then(() => {
    const e = new Entity({
        name: 'test',
        createdAt: '2018-01-01 12:00:00',
        updatedAt: '2019-08-15 12:00:00'
    })
    e.save().then(() => {
        console.log(e)
        e.updatedAt = '2019-08-15 12:00:00'
        e.save({ timestamps: false }).then(() => {
            console.log(e)
        })
    })
})
```
