### ISSUE TITLE
Socket timeouts not handled gracefully (promise rejections)

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#8072]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Socket timeouts seem to yield unhandled promise errors. Those currently just show up on the console without consequences, but will crash the application in future versions of Node. (Note the deprecation warning).

**If the current behavior is a bug, please provide the steps to reproduce.**

My DB was timing out due to a low socket timeout setting. This yielded the following console output:

```
[0] (node:16528) UnhandledPromiseRejectionWarning: MongoNetworkError: connection 13 to localhost:27017 timed out
[0]     at Socket.<anonymous> (C:\myapp\node_modules\mongodb-core\lib\connection\connection.js:335:7)
[0]     at Object.onceWrapper (events.js:286:20)
[0]     at Socket.emit (events.js:198:13)
[0]     at Socket._onTimeout (net.js:442:8)
[0]     at ontimeout (timers.js:436:11)
[0]     at tryOnTimeout (timers.js:300:5)
[0]     at listOnTimeout (timers.js:263:5)
[0]     at Timer.processTimers (timers.js:223:10)
[0] (node:16528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promi
se which was not handled with .catch(). (rejection id: 1)
[0] (node:16528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected behavior?**

Exceptions should be handled more gracefully I guess. Not sure it can be done by Mongoose, or if it's really buried in `mongodb-core`. This is currently not an issue, but will be fatal once the Node.js process crashes due to the failing promise.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.6.7
node v11.2.0

**Comment by vkarpov15** [comment]
Can you provide a script that demonstrates this?

**Comment by hardcodet** [comment]
I'm afraid not - my local MongoDb has been misbehaving, which is why I saw the exception in the first place. You would need a DB with socket timeouts in order to repro - I don't have any code executing (just an idle connection).

**Comment by vkarpov15** [comment]
The below script doesn't print any unhandled rejections. Can you please modify the below script to demonstrate your issue?

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `8072`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true, socketTimeoutMS: 1000 });
  await mongoose.connection.dropDatabase();

  await new Promise(resolve => setTimeout(resolve, 10000));
}
```

**Comment by hardcodet** [comment]
I'm afraid I can't repro this with this script? I still do have timeouts, but even in debug mode, there's no output, I'm just getting the unhandled promise rejections that hit through to my global exception handler... Anything else I can support you with?

As said, this is currently not an issue for me (I'm just catching those, and with a functional DB, they aren't an issue in the first place). I rather posted this because it could be potentially fatal if unhandled promises start to kill the whole node process.

**Comment by vkarpov15** [comment]
Another possibility is that these issues are due to slow queries - for example, the below script prints the same error message because the query runs longer than `socketTimeoutMS`.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `8072`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true, socketTimeoutMS: 1000 });
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));

  await Model.create({ name: 'test' }, { name: 'test2' });

  await Model.find({ $where: 'sleep(1500) || true' });
}
```

Read up on [slow queries in MongoDB](http://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs) and try increasing `socketTimeoutMS` to something higher than what you have now. If you don't set `socketTimeoutMS`, it is 30000 (30 seconds) by default. Here's the [Mongoose docs on `socketTimeoutMS`](https://mongoosejs.com/docs/connections.html#options).

**Comment by hardcodet** [comment]
Maybe, I couldn't tell. I saw the issues on a somehow botched Docker container - in my current environment, there's no timeouts in the first place.
In any case, I wasn't so much worried about the fact that were timeouts, but the fact that those timeouts were not handled and just hit through.

It's not an issue for me though - I just wanted to let you know about the potential ramifications of undhandled promise exceptions. I'll close this for now, ok?

**Comment by vkarpov15** [comment]
Go for it. If there's an unhandled promise rejection in mongoose we'll fix it. But in this case I haven't been able to confirm that this unhandled rejection actually comes from mongoose.
