### ISSUE TITLE
ValidationError: MyThing validation failed: strings: Cast to Array failed for value "[ '1' ]" at path "strings"

### ISSUE THREAD

**Issue by patran** [Automattic/mongoose#8074]
mongoose version: 5.6.9

I am using Typescript and Mongoose. I have probably covered all existing postings on "Cast to Array failed". I was not able to find a solution. I would appreciate your support.

Please note the code works with the exception of the "strings" array. Any array would fail.

export const MySchema = new Schema({
    myId: String,
    strings: [String],
});

export interface IMyThing extends Document  {
    myId: string;
    strings: string[];
}

let MyThing = dataConn.model<IMyThing>("MyThing", MySchema);
let myMongo: IMyThing = new MyThing;
myMongo.myId = "id-1";
myMongo.strings = ['hello'];
await myMongo.save();

    { ValidationError: MyThing validation failed: strings: Cast to Array failed for value "[ 'hello' ]" at path "strings"

      errors:
       { strings:
          MongooseError {
            message:
             'Cast to Array failed for value "[ \'hello\' ]" at path "strings"',
            name: 'CastError',
            stringValue: '"[ \'hello\' ]"',
            kind: 'Array',
            value: [Array],
            path: 'strings',
            reason: [MongooseError] } },
      _message: 'MyThing validation failed',
      name: 'ValidationError' }

**Comment by patran** [comment]
This may be a duplicate of #8053. I am checking to see if my issue is indeed a duplicate.

**Comment by patran** [comment]
I do use jest. Downgraded to mongoose 5.6.8 solved the issue. It does indeed seem to be a duplicate of #8053

**Comment by vkarpov15** [comment]
We released 5.6.10. I would recommend switching off of Jest - it is a separate JavaScript environment, **not** a testing framework, and I'm not aware of any node modules that test Jest in addition to Node.js. Mongoose may start testing Jest as a separate JavaScript runtime, but for now we'll fix Jest-specific issues as they pop up.
