### ISSUE TITLE
Is there memory leap after session commit without end?

### ISSUE THREAD

**Issue by cncolder** [Automattic/mongoose#8076]
**Do you want to request a *feature* or report a *bug*?**

bug (maybe)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Below will throw `MongoError: Use of expired sessions is not permitted`

```ts
        let user = await new User({ balance: 1 }).save()

        let session = await mongoose.startSession()
        session.startTransaction()
        user.balance = 2
        await user.save({ session })
        await session.commitTransaction()

        session.endSession()

        user.balance = 3
        await user.save()
```

**What is the expected behavior?**

Mongoose associate `session` to document.

Is this behavior for session reuse?
What time did mongoose end session?
Should I delete `session.endSession()` leave it there?

It make me confuse because I cannot `operate`(save/update/...) my document after there is a session associate on it.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js v12.8.1
Mongoose 5.6.9
MongoDB v4.0.5

**Comment by vkarpov15** [comment]
When you `save()` with a session option, Mongoose stores that session for future `save()` calls. The [`$session()` function](https://mongoosejs.com/docs/api/document.html#document_Document-$session) stores the current session associated with the document, Mongoose will use the associated session by default for any `save()` or `remove()` calls.

To work around this behavior, do this:

```javascript
        await user.save({ session })
        await session.commitTransaction()

        session.endSession()

        user.balance = 3
        user.$session(null); // Remove the associated session
        await user.save()
```
