### ISSUE TITLE
MongoDB node Driver v3.3 / MongoDB 4.2

### ISSUE THREAD

**Issue by natac13** [Automattic/mongoose#8078]
I was just curious if support for MongoDB 4.2 will be coming soon? I have look at the [compatibility page](https://mongoosejs.com/docs/compatibility.html) in the docs as well as the linked [table](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility), which seems like MongoDB 4.2 requires mongodb node drive of version >= 3.3.

If this is just a version bump as I see from previous upgrades ([3.2.3](https://github.com/Automattic/mongoose/commit/23158ba9b1172c7dc280ea72c7190c4722f88dbd & [3.2.4](https://github.com/Automattic/mongoose/commit/715ee77740e571ddccd87a1a3a26358e33f0411b)) then I will gladly open a pull request for the project. 

However I was unsure if there would be anything else that would need changing to upgrade to [mongodb 3.3](https://github.com/mongodb/node-mongodb-native/tree/v3.3.0)

**Comment by natac13** [comment]
I see that `mongo-core` is still on version [`3.2.7`](https://github.com/mongodb-js/mongodb-core/blob/master/package.json). Does this upgrade need to wait until both `mongo-core` and `node-mongodb-native` are at v3.3?

**Comment by dtboy1995** [comment]
mark it.

**Comment by billouboq** [comment]
@natac13 mongodb-core is now inside node-mongodb-native.

see [release 3.3](https://github.com/mongodb/node-mongodb-native/releases)

> Merged mongodb-core into node-mongodb-native
> Up until this release, the mongodb driver has consisted of two components:
> 
> mongodb-core: The low-level engine of the driver.
> node-mongodb-native: The API layer of the driver, published as mongodb
> Over time, this separation has done more harm than good, and has led to increased development time for repairing bugs and implementing new features. Starting in the 3.3 release of mongodb, we have merged mongodb-core into node-mongodb-native, removing this barrier to development.

**Comment by natac13** [comment]
Hey @billouboq 

My pull request failed and I am thinking it is because [`node-mongodb-native` does not expose at top level the `parseConnectionString`](https://github.com/mongodb/node-mongodb-native/blob/9cde4b9b6ed4f6dd62989ec4ee02a68d12b70b79/index.js) that mongoose relies on from [`mongo-core`](https://github.com/mongodb-js/mongodb-core/blob/master/index.js). 

Im not sure what the best approach is for this. Maybe just keep `mongo-core 3.2.7`? But that seems counter-productive to what you have said about it being included in `mongodb driver` now. Maybe a pull request to the driver to include `parseConnectionString`?
