### ISSUE TITLE
Return string instead of array in document 

### ISSUE THREAD

**Issue by msgenesis** [Automattic/mongoose#8080]
document in mongodb
`{
    "_id" : ObjectId("5d3964c27a757f1e04c44317"),
    "ip" : [ 
        "123.123.123.123", 
        "123.123.123.122"
    ],
    "__v" : 0
}`

the response i get is
`{_id: "5d3964c27a757f1e04c44317", ip: "123.123.123.123,123.123.123.122", __v: 0}`

"mongoose": "5.0.12"

**Comment by natac13** [comment]
What does your mongoose model look like? 

``` js
const docSchema = new mongoose.Schema({
  field1: String,
  ip: [String],
  ...
})
```
