### ISSUE TITLE
Queries on an array of nested schemas to match empty string throws ObjectParameterError

### ISSUE THREAD

**Issue by coox** [Automattic/mongoose#8086]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

Considering the following schemas:

```js
const nestedObjectSchema = new mongoose.Schema({});
const schemaWithArrayOfNestedObjects = new mongoose.Schema({
  nestedObjects: [nestedObjectSchema],
});
```

Any query attempting to match the empty string `''` results in the following exception being thrown:

`ObjectParameterError: Parameter "obj" to Document() must be an object, got `

Example queries:

```
ModelWithArrayOfNestedObjects.find({ nestedObjects: '' });

ModelWithArrayOfNestedObjects.countDocuments({ nestedObjects: { $in: [[], null, ''] } });
```

This is quite similar to what has been reported in #7242 with boolean values (now fixed).

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/db', {
  useNewUrlParser: true,
});

const schemaWithArrayOfStrings = new mongoose.Schema({
  strings: [String],
});
const ModelWithArrayOfStrings = mongoose.model(
  'ModelWithArrayOfStrings',
  schemaWithArrayOfStrings
);

const schemaWithArrayOfObjects = new mongoose.Schema({
  objects: [{}],
});
const ModelWithArrayOfObjects = mongoose.model(
  'ModelWithArrayOfObjects',
  schemaWithArrayOfObjects
);

const nestedObjectSchema = new mongoose.Schema({});
const schemaWithArrayOfNestedObjects = new mongoose.Schema({
  nestedObjects: [nestedObjectSchema],
});
const ModelWithArrayOfNestedObjects = mongoose.model(
  'ModelWithArrayOfNestedObjects',
  schemaWithArrayOfNestedObjects
);

mongoose.connection.on('connected', async () => {
  await ModelWithArrayOfStrings.countDocuments({
    strings: { $in: [[], null, ''] },
  });
  // Mongoose: modelwitharrayofstrings.countDocuments({ strings: { '$in': [ [], null, '' ] } }, {})
  // ⇒ 0

  await ModelWithArrayOfObjects.countDocuments({
    objects: { $in: [[], null, ''] },
  });
  // Mongoose: modelwitharrayofobjects.countDocuments({ strings: { '$in': [ [], null, '' ] } }, {})
  // ⇒ 0

  await ModelWithArrayOfNestedObjects.countDocuments({
    nestedObjects: { $in: [[], null, ''] },
  });
  // ObjectParameterError: Parameter "obj" to Document() must be an object, got
});
```

**What is the expected behavior?**

Mongoose is expected to build, run, and return the result of the query from Mongo.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Reproduced in 5.6.7, 5.6.9, and 3feb60b.

**Comment by vkarpov15** [comment]
Why is this a bug? Empty string isn't something you can convert into an object in an obvious way, so Mongoose casting fails. What's your use case for this?

**Comment by ajitharx** [comment]
By the way, I am using mongoose 5.6.9 and get a similar error when trying push a new sub-document using a variable. However, If i hard code the value of the same variable inside push, it would work. Is this an issue ?
form1.configdefinition[groupIndex].annotations.push(newannotation);  fails throwing a cast error for "_id" but,
form1.configdefinition[groupIndex].annotations.push({"annotation":{"annotid":"ABCD1234", "annotcoord":"435,345, 657,768"}}); works fine.

**Comment by vkarpov15** [comment]
@ajitharx what is the value of `newannotation` and what does your schema look like? Please open up a new issue and follow the issue template.
