### ISSUE TITLE
Unable to apply mongoose plugin globally to all schemas

### ISSUE THREAD

**Issue by jeremyml** [Automattic/mongoose#8088]
I am unable to apply a plugin `mongoose-lean-virtuals` to all schemas.  I can set the plugin on a particular schema, but not on all schemas globally.  Is this the expected behavior?

Below is an example of code which does not apply `mongoose-lean-virtuals` to all schemas.

```
const mongoose = require('mongoose');
mongoose.plugin(require('mongoose-lean-virtuals'));
const express = require('express');
mongoose.connect(mongoConnStr, {useNewUrlParser: true, useCreateIndex: true, 
    useFindAndModify: false });
const db = mongoose.connection;
const app = express();
// ... register some routes below
```

**Comment by vkarpov15** [comment]
What output do you get? Can you please provide an example of how you're registering models and using `mongoose-lean-virtuals`?

**Comment by jeremyml** [comment]
I solved my problem, and your suggestion to look at registering models helped me to solve it.

Apparently I was registering a model in an included file prior to attempting to apply the global plugin.  This prevents the global plugin from being applied.

I moved the global plugin near the beginning of the app, and now the plugin is applied to all models.  Thanks for the help!
