### ISSUE TITLE
.parent on references

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8092]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`.parent` on populated references returns undefined

**If the current behavior is a bug, please provide the steps to reproduce.**
```ts
class Schema1Class {
  public test() {
    console.log('Schema1 Parent', this.parent); // returns undefined
  }
}
const schema1 = new mongoose.Schema({});
schema1.loadClass(Schema1Class);

class Schema2Class {
  public test() {
    console.log('Schema2 Parent', this.parent); // should return undefined
    console.log('Schema2.nested Parent', this.nested.parent); // returns undefined
  }
}
const schema2 = new mongoose.Schema({
  nested: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Model1'
  }
});
schema2.loadClass(Schema2Class);

const Model1 = mongoose.model('Model1', schema1);
const Model2 = mongoose.model('Model2', schema2);

const m1doc = await Model1.create({});
const m2doc = await Model2.create({ nested: m1doc });
const found = await Model2.findById(m2doc._id).populate('nested').exec();

console.log('found', found);
found.test();
found.nested.test();
```

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 12.8.1
mongodb: 4-xenial (docker)
mongoose: 5.6.10

PS: the [docs in here](https://mongoosejs.com/docs/populate.html) are a bit outdated, like `Schema` cant be used without `new`

PPS: `.parent` dosnt have type information (in mongoose's .d.ts)

**Comment by vkarpov15** [comment]
`Schema()` can be used without new. We don't support typescript bindings.

Will look into the reported issue.

**Comment by vkarpov15** [comment]
Right now a populated document isn't an instance of a [subdocument](https://mongoosejs.com/docs/subdocs.html), so it doesn't have `.parent()` or `.ownerDocument()`. We'll need to add that in a minor release.
