### ISSUE TITLE
Model.exists() should return a query instead of a promise

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8097]
Re: #8075 , `Model.exists()` is very inconsistent with other helper functions.

**Comment by felixveysseyre** [comment]
I cannot agree more with @vkarpov15

With current implementation, there is no way to use `exists` in a transaction context 😭

**Comment by vkarpov15** [comment]
@felixveysseyre there is an options parameter to `exists()`, you should be able to do `Model.exists(filter, { session })`. Does that not work for you?

**Comment by felixveysseyre** [comment]
@vkarpov15 Thanks for your answer 🙃

Looking [into the sources](https://github.com/Automattic/mongoose/blob/master/lib/model.js), I have been able to find the options parameters you are talking about.

I've been tricked by the [outdated documentation] (I suppose)(https://mongoosejs.com/docs/api/model.html#model_Model.exists) and the [wrong types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L3067) 😭

**Comment by vkarpov15** [comment]
Making a note of this for #8108

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
This will make it so that `Model.exists(...)` won't trigger pre-findOne hooks, correct?

If so, this should fix #8739

**Comment by AbdelrahmanHafez** [comment]
Should revert #8764 once this is released.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez actually `exists()` will still trigger pre('findOne') hooks. Unless you happen to change query op before executing.
