### ISSUE TITLE
How to get a Limit range on each Ids and not on the entire result set

### ISSUE THREAD

**Issue by sonnyk22** [Automattic/mongoose#8103]
Querying a document to return `Posts `result based on a list of postIds (`'postId': { $in: ids }`) and using the `Skip `and `Limit `range is as seen below.  

```
const query = {
    'isActive': true,
    'postId': { $in: ids }
};

let selection = {
    '__v': 0,
    'isActive': 0,
    'modifiedTS': 0
}

Posts
    .find(query, selection)
    .sort({ 'createdTS' : -1 })
    .skip(skip)
    .limit(limit)
    .exec((err, retModel) => {
        // Code
    });
```

I am hoping to get help on how to get a `Limit `range **'on each PostId** `and not on the entire result set.  

I’ve been looking for this solution for a few days without success.  I hope to get some guidance on this.

Thank you

**Comment by vkarpov15** [comment]
There isn't a way to ensure you get at most one `Post` document for each `postId` in a single query. You have 2 options:

1) Use the aggregation framework
2) Execute a separate [`findOne()`](https://mongoosejs.com/docs/api/query.html#query_Query-findOne) for each `postId`
3) Restructure your data

I'd recommend doing (2) unless you absolutely need this query to be fast, in which case you can do either (1) or (3)
