### ISSUE TITLE
findOneAndUpdate $push returns old record value for array types

### ISSUE THREAD

**Issue by mesthabro** [Automattic/mongoose#8106]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
Model.findOneAndUpdate(filter, {'$push': {attribute: value}}) does not return the updated array values.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const UserSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  enrollments: [{
    type: Schema.Types.ObjectId,
    ref: 'Enrollment',
  }],
});

const EnrollmentSchema = new Schema({
  title: {
    type: String,
  },
})

const User = mongoose.model("User", UserSchema);
const Enrollment = mongoose.model('Enrollment', EnrollmentSchema)

let newUser = new User({name: 'John Doe'})
let newEnrollment = new Enrollment({title: 'Sample title'})

let savedUser = await newUser.save()
let savedEnrollment = await newEnrollment.save()

let updatedUser = await User.findOneAndUpdate({ _id: savedUser._id }, {"$push": {enrollments: savedEnrollment._id}})

// updatedUser:
// Expected: { name: 'John Doe'. enrollments: [ ObjectId ] }
// Returned value: {name: 'John Doe', enrollments: []}
// query User.findOne({}) and you can see the item updated in the db
```

**What is the expected behavior?**
The method should return the updated document. But fails to return the updated record if there is any Array. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js version v10.16.0
MongoDB shell version v4.0.11

Mongoose version 5.6.7
Okay

**Comment by vkarpov15** [comment]
It looks like you're not setting the [`new` option to `findOneAndUpdate()`](https://mongoosejs.com/docs/api/model.html#model_Model.findOneAndUpdate). Do this instead:

```javascript
let updatedUser = await User.findOneAndUpdate({ _id: savedUser._id }, {"$push": {enrollments: savedEnrollment._id}}, { new: true })
```
