### ISSUE TITLE
Print warning when schema `type` is a POJO with non-zero number of properties

### ISSUE THREAD

**Issue by hardcodet** [Automattic/mongoose#8107]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have the following schema:

```
export const AuthorizationSchema = new mongoose.Schema({
    foo: {type: String, required: true },

    nested: {
        type: {
            xxx: { type: String, required: true },
            yyy: { type: String, required: true }
        },
        required: false
    },
    createdBy: {type: String, required: true }
});
```

If I `save()` an object I retrieved before, only the top-level properties are getting saved, not the nested one:

```
item.foo = "hello"; //will be saved
item.nested.xxx = "world" //won't be saved
```

**Edit:** This seems to be related to the `type` section I introduced to mark the nested type as optional. If I declare it like this, saving it works, but of course, the item is now required.

```
    nested: {
            xxx: { type: String, required: true },
            yyy: { type: String, required: true }
    },
```

Also, declaring the nested type as a schema of its own seems to work, so that's a fix that works:

    nested: {
        type: NestedSchema,
        required: false
    },

My understanding is that nested items in arrays are not automatically updated, but this isn't one.
A workaround would be to use `markModified` with the path, but I hope that's just a dirty hack ;)
I saw this reported in an earlier bug (see last comment on #6152) that was marked as resolved, but if that was fixed, it has resurfaced.

Mongoose version: `5.6.10` (I think), then upgraded to `5.6.11`

**Comment by vkarpov15** [comment]
Your schema is incorrect. When you do `nested: { type: { xxx: String } }`, Mongoose considers that equivalent to `nested: { type: {} }` and makes nested a [mixed path](https://mongoosejs.com/docs/schematypes.html#mixed). You should do `nested: { type: NestedSchema }` like you suggested.

We should at least print a warning when this happens, it's a common mistake.

**Comment by hardcodet** [comment]
Thanks for the context, Valeri!

(I'll leave the ticket open since you labeled it - as far as I'm concerned, I'm all good :)

**Comment by vkarpov15** [comment]
We don't need this anymore, because in Mongoose 6 `nested: { type: { xxx: String } }` is equivalent to `nested: { type: new Schema({ xxx: String }) }`. So `nested` will be a [subdocument](https://mongoosejs.com/docs/subdocs.html).
