### ISSUE TITLE
Run Save on References that are created inside of a parent model

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8115]
**Do you want to request a *feature* or report a *bug*?**
enhancement / bug?

**What is the current behavior?**
Does not actually get saved without a pre hook

**If the current behavior is a bug, please provide the steps to reproduce.**
```ts
// Note this is copied & modified from @vkarpov15 version
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh8115`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const ClubSchema = new Schema({
    name: String,
    location: String
  });
  
  const Club = mongoose.model('Club', ClubSchema);
  
  const PlayerSchema = new Schema({
    name: String,
    club: { 
      type: Schema.Types.ObjectId,
      ref: 'Club'
    } 
  });

  const Player = mongoose.model('Player', PlayerSchema);

  const p = new Player({ name: 'Test2', club: new Club({ name: 'Test1' }) });
  await p.save();
}
```

**What is the expected behavior?**
to actually save the references instead of needing a pre hook

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 12.9.1
mongoose: 5.6.11
mongodb: 4.2-bionic (docker)

---

Continuation of #2228 (because it got locked)

**Comment by vkarpov15** [comment]
This is something we considered a few years ago in #2418 and #3416. There's plenty of arguments on both sides but we've decided against implicitly saving populated docs by default. We may consider adding a `save({ populated: true })` or `save({ refs: true })` option as suggested in [this comment](https://github.com/Automattic/mongoose/issues/2418#issuecomment-61536738) in the future.

**Comment by Arsenalist** [comment]
Can you recommend a workaround for this issue if you're not going to support it?

**Comment by vkarpov15** [comment]
@Arsenalist right now you'd need to go through all paths that you've populated and get the documents. We opened up #9702 with a potential workaround.
