### ISSUE TITLE
Auth support for `useDb()`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8116]
Re: #2874, `useDb()` should have the option to provide auth credentials in case the currently logged in user doesn't have access to the new database.

https://mongoosejs.com/docs/api/connection.html#connection_Connection-useDb

**Comment by linuscarlstrom** [comment]
We are a handful of developers working on a multi-tenancy solution, and this has quickly become an issue. Each tenant has their own database with a specific user.

Creating new connections or establishing and saving a connection for each request feels expensive. Is there another workaround for this until it's added in the mongoose library?

Thanks in advance!

**Comment by vkarpov15** [comment]
Creating new connections for each tenant is generally the way to go. Switching on each request using `useDb()` is not a good way to implement multi-tenant: you may switch databases in the middle of a multi-request operation like `populate()`. That makes `useDb()` risky for multi-tenant unless you implement queuing.

**Comment by linuscarlstrom** [comment]
Cool cool, we'll keep our approach as is then, thanks for the response 👍

**Comment by vkarpov15** [comment]
I took a closer look and unfortunately this is not possible. The [MongoDB Node.js driver deprecated support for additional `authenticate()` calls in 2017](https://github.com/mongodb/node-mongodb-native/blob/3.6/HISTORY.md#2227-2017-05-22). So there's no way for Mongoose to support different auth credentials on the same connection pool.

**Comment by vkarpov15** [comment]
In order to connect to different databases with different authentication requirements, you need to use [multiple connections](https://mongoosejs.com/docs/connections.html#multiple_connections).

**Comment by darinrogers** [comment]
@vkarpov15 What if you connect to one database with one set of credentials, but then try to `useDb` to another database which happens to have a user with same credentials? I believe that even with the same credentials, they are different users. At the command line, I need to call the `auth` method. But it seems like there's no way to do this from Mongoose? Is a [multi-tenant architecture](https://mongoosejs.com/docs/connections.html#multi-tenant-connections) only possible if you _don't_ use authentication?

**Comment by vkarpov15** [comment]
@darinrogers Mongoose's docs on [multi-tenant connections](https://mongoosejs.com/docs/connections.html#multi-tenant-connections) describe 2 patterns for multi tenancy: 1) shared connection pool using `useDb()`, 2) separate connection pool per tenant. Pattern (1) is not possible when you need to authenticate as different users for different databases, because the MongoDB server does not support authenticating as multiple users on the same connection pool. But there's no problem with using pattern (2).

**Comment by vkarpov15** [comment]
@darinrogers Mongoose's docs on [multi-tenant connections](https://mongoosejs.com/docs/connections.html#multi-tenant-connections) describe 2 patterns for multi tenancy: 1) shared connection pool using `useDb()`, 2) separate connection pool per tenant. Pattern (1) is not possible when you need to authenticate as different users for different databases, because the MongoDB server does not support authenticating as multiple users on the same connection pool. But there's no problem with using pattern (2).

**Comment by vkarpov15** [comment]
Yeah, unfortunately there's no way to make `useDb()` work with multiple authentications, and there's nothing Mongoose can do about it unless the MongoDB server adds support for multiple auth on the same connection.

One potential alternative is to cap the number of sockets per connection: the MongoDB Node driver allows up to 100 sockets per connection by default. You can reduce that with the `maxPoolSize` option. Would that help?

**Comment by darinrogers** [comment]
That's what we're doing and it does help. It prevents us from hitting a connection limit. But now, each service/tenant has a small number of sockets per connection and it's noticeably slowing things down. And this doesn't scale well. So I think an architectural change is in order.
