### ISSUE TITLE
Validator called more than once (5.6.9), called never (5.6.11)

### ISSUE THREAD

**Issue by qqilihq** [Automattic/mongoose#8117]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
This is a follow-up for https://github.com/Automattic/mongoose/issues/8067

Scenario: Validator is used on an object property. With 5.6.9 the validator gets called **several** times, with 5.6.11 it gets **not** called at all.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose'); // no mongoose.version when using import?!

(async () => {
  const Model = mongoose.model('model', new mongoose.Schema({
    name: { type: String },
    level1: {
      level2: {
        type: Object,
        validate: {
          validator: (v: any) => {
            console.log('called validator with', v);
            return true;
          }
        }
      }
    }
  }));

  const doc = new Model({ name: 'bob' });
  console.log(mongoose.version);
  doc.level1 = { level2: { a: 'one', b: 'two', c: 'three' } };
  await doc.validate();
  console.log('done');
})().catch(err => console.error(err));
```

Running with Mongoose 5.6.9 I see:
```
$ ./node_modules/.bin/ts-node ./src/mongoose-8067.ts 
5.6.9
called validator with { a: 'one', b: 'two', c: 'three' }
called validator with one
called validator with two
called validator with three
done
```

Running with Mongoose 5.6.11 I see:
```
$ ./node_modules/.bin/ts-node ./src/mongoose-8067.ts 
5.6.11
done
```

I admittedly didn't try the version in between :-P

**What is the expected behavior?**
The validator should execute once with `{ a: 'one', b: 'two', c: 'three' }`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by thnima** [comment]
I observed the same behaviour (see also here: https://github.com/Automattic/mongoose/issues/8113)
Looks like this misbehaviour got introduced in 5.6.10
