### ISSUE TITLE
FindOneAndUpdate method options in @types/mongoose

### ISSUE THREAD

**Issue by iamchathu** [Automattic/mongoose#8118]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`omitUndefined` and `timestamps` options are documented in Documentation but TypeScript `QueryFindOneAndUpdateOptions` interface doesn't have that options defined. So  it doesn't allowed to use them with TypeScript.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Install Latest Mongoose and @types/mongoose
* Write a method with findOneAndUpate with options either one or both `omitUndefined` or `timestamps` to be true.
* Typescript will yell they are not defined in `QueryFindOneAndUpdateOptions`

**What is the expected behavior?**

To use `omitUndefined` and `timestamps` options in TypeScript enviroment.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
Node: v10.53.3
"mongoose": "^5.6.11"
"@types/mongoose": "^5.5.16"
"typescript": "^3.5.3",
```

**Comment by welljsjs** [comment]
@iamchathu 
I ran into the same problem. I think you need to report this issue on the [DefinitlyTyped repo.](https://github.com/DefinitelyTyped/DefinitelyTyped)

I just had a look over there and it seems [like so already reported that problem in June](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36437). So far, no-one seems to have cared about that. However, you could support the bug by giving it a thumbs-up. That might raise some attention.

**Comment by iamchathu** [comment]
@welljsjs I have added my own types to project and fixed the issue. Also I sent a PR to DefinitlyTyped repo.

**Comment by vkarpov15** [comment]
This project isn't `@types/mongoose`, that's DefinitelyTyped. Please follow #8108 for updates on typescript support - right now Mongoose doesn't have any official typescript support.
