### ISSUE TITLE
Is there a max amount of schema i can use per model?

### ISSUE THREAD

**Issue by Enado95** [Automattic/mongoose#8120]
I'm trying to find out if there is a maximum amount of schemas that you can use per model?

for example:

I want to have one product **Model** , with a mortgage, loan and credit card schema?
And also if there are any implications to this approach

`const mortgage = model('Mortgage', productSchema, 'products')`
`const mortgage = model('Loans', productSchema, 'products')`
`const mortgage = model('CreditCard', productSchema, 'products')`

and so on

**Comment by vkarpov15** [comment]
It sounds like you're looking for [discriminators](https://mongoosejs.com/docs/discriminators.html).
