### ISSUE TITLE
error on {type:Object}

### ISSUE THREAD

**Issue by RezaErfani67** [Automattic/mongoose#8122]
i have a field with Object Type
```javascript
flowchart : { type : Object, required : true },
```
my app works good with version 5.6.5...
but after update it 5.6.11 bellow error has shown...
flowchart.nodes: Path `flowchart.nodes` is required.,
 flowchart.links: Path `flowchart.links` is required.

**Comment by vkarpov15** [comment]
Can you please show a more complete code sample?
