### ISSUE TITLE
text index required for $text query

### ISSUE THREAD

**Issue by mohammadzafardoost** [Automattic/mongoose#8126]
Can anyone help solve this problem? You can see it at stackoverflow. I fully explained

https://stackoverflow.com/questions/57783054/indexnotfound-text-index-required-for-text-query

**Comment by vkarpov15** [comment]
Are you sure you're connected to the right database? Perhaps try running [`Business.listIndexes()`](https://mongoosejs.com/docs/api/model.html#model_Model.listIndexes) to confirm the index is already built?

Also, are you dropping the database before running your script?

**Comment by mohammadZF** [comment]
Yes I'm pretty sure the connection is right ...
index made ...
I tested it with all kinds of third party software.
I updated the stack post:
EDITED: this error does not occur when this query has a result! Only occurs when the query result is null.
---
I even got this result.
I had never encountered such a problem before, and it really got into trouble.

**Comment by mohammadZF** [comment]
> Are you sure you're connected to the right database? Perhaps try running [`Business.listIndexes()`](https://mongoosejs.com/docs/api/model.html#model_Model.listIndexes) to confirm the index is already built?
> 
> Also, are you dropping the database before running your script?

**Comment by mohammadZF** [comment]
Yes I'm pretty sure the connection is right ...
index made ...
I tested it with all kinds of third party software.

I updated the stack post:
EDITED: this error does not occur when this query has a result! Only occurs when the query result is null.

I even got this result.
I had never encountered such a problem before, and it really got into trouble.

**Comment by vkarpov15** [comment]
What is the output of `Business.listIndexes()` before running your query?

Also, you didn't answer this question: are you dropping the database before running your script?

**Comment by mohammadzafardoost** [comment]
output of Business.listIndexes() :
```
[ 
  { v: 2,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'name_text_family_text',
    ns: 'Test.users',
    background: true,
    weights: { family: 1, name: 1 },
    default_language: 'english',
    language_override: 'language',
    textIndexVersion: 3 
 }
]
```
About dropping the database you mentioned, Yes I dropped the database but the problem didn't solved.

**Comment by mohammadzafardoost** [comment]
Something unusual happened
I was not there for a while and had not worked on the problem, and to this day my system was inactive,
But unbelievably this problem has been fixed!
Without any changes to the code or database.

**Comment by brunoqs** [comment]
So, to user that $text feature, need to drop database?

**Comment by vkarpov15** [comment]
@brunoqs no, you do not need to drop the database. You need to wait for the index to finish building before using `$text`.

**Comment by Mahdi-Soultana** [comment]
### 2022/01/01 The best method for me that woks with no wornnig is from mongodb Could
![1](https://res.cloudinary.com/soultana-mahdi/image/upload/v1640861929/cf08ijkyixcw98mf5ntw.png)
![2](https://res.cloudinary.com/soultana-mahdi/image/upload/v1640862061/jfosamuqg0goigo6d24h.png)


and from code you need to pass :>>
```

const blogPosts = await BlogPostModel.find({  $text: { $search: `"${req.query["your-search-quey"] }"`  } })

```
