### ISSUE TITLE
insertMany an empty array, got an error

### ISSUE THREAD

**Issue by leoDreamer** [Automattic/mongoose#8133]
mongooseVersion: 5.6.12
https://github.com/Automattic/mongoose/blob/70f678e69859cec93d3af9ad8991bf19591da702/lib/model.js#L3251
in this line throw an error 
![image](https://user-images.githubusercontent.com/16728066/64302911-1e40b500-cfb8-11e9-93c1-994832820001.png)
because of this code exec the callback function with any params https://github.com/Automattic/mongoose/blob/70f678e69859cec93d3af9ad8991bf19591da702/lib/helpers/parallelLimit.js#L15

**Comment by NdaJunior** [comment]
Currently getting this same error - did you manage to resolve it?

**Comment by MihaiBojescu** [comment]
Same happening here

**Comment by MihaiBojescu** [comment]
I worked around this by using mongoose `5.6.11` instead of `5.6.12`.

**Comment by HelloYie** [comment]
The same issue.

**Comment by vkarpov15** [comment]
We fixed this in 5.6.13, I'm sorry for the trouble. Please upgrade and this issue will go away.
