### ISSUE TITLE
5.6.13 Release to NPM

### ISSUE THREAD

**Issue by loren138** [Automattic/mongoose#8136]
5.6.13 includes an important bug fix that was introduced in 5.6.12, but it hasn't been released on NPM yet.

Do you know when it will get pushed there?  I see the release in github from 23 hours ago.

For now, we have pinned our version to 5.6.11 to avoid the bug.

![npm release](https://nodei.co/npm/mongoose.png)

**Comment by vkarpov15** [comment]
I'm not sure how I missed that, thanks for the heads up. I just published 5.6.13 to npm :+1:
