### ISSUE TITLE
Change data inside a static function

### ISSUE THREAD

**Issue by api-spinner** [Automattic/mongoose#8140]
I want to change user.payments on static function, and inside this function it really works.

```
UsersSchema.static('getUserByEmail', function (email) {
  return this.findOne({ email }, (err, user) => {
    user.payments.reverse()
    console.log('user:', user) // user.payments here is reversed
  })
})
```

But when I get user, user.payments is not reversed.

```
const user = await Users.getUserByEmail('my@email.com')
console.log('user:', user)
```

How can I do that?

**Comment by vkarpov15** [comment]
You're executing the query twice, see this section of the docs: https://mongoosejs.com/docs/queries.html#queries-are-not-promises . Use `.then()` instead of passing a callback. `return this.findOne().then(doc => doc.payments.reverse())`

**Comment by api-spinner** [comment]
It works. Thank you very much!
