### ISSUE TITLE
A possible mongoose cli to try?

### ISSUE THREAD

**Issue by waptik** [Automattic/mongoose#8142]
Hey! I don't know if i should put this here or not but i am giving it a shot.
A few months ago i was looking for possible mongoose cli packages to help generate my models and seeders for me but couldn't find a suitable one that meets my needs. So i went ahead and built mine which is heavily based on [sequelize-cli](https://github.com/sequelize/cli).

It helps generate models, seeders and migrations(if you need them) files for you from any cli by giving it a name and attributes. Here are:
- the [documentation](https://github.com/waptik/mongoose-cli#readme),
- an [example](https://github.com/waptik/mongoose-cli/tree/master/examples) folder of how it looks like, and
- a related post ➡️ on [dev.to](https://dev.to/waptik/introducing-mongoosejs-cli-generate-models-migrations-and-seeders-for-mongoosejs-right-from-your-terminal-2iei)

Please give it a try and give me a feedback.
Thanks 👍

**Comment by vkarpov15** [comment]
Nice, thanks! I'll take a look

**Comment by waptik** [comment]
> 
> 
> Nice, thanks! I'll take a look

Great! Looking forward to your feedback.

**Comment by vkarpov15** [comment]
Nice. I like how your models are structured as functions: https://github.com/waptik/mongoose-cli/blob/master/examples/models/Test.js . For your docs, I'd also add an example with [npx](https://thecodebarbarian.com/80-20-guide-to-the-npx-package-runner) like how [sequelize cli does](https://sequelize.org/master/manual/migrations.html).

Also, another suggestion: it's a bit hard to understand how to [configure umzug to use mongodbstorage](https://www.npmjs.com/package/umzug#mongodbstorage) with this cli, and IMO the ability to avoid re-running migrations is a key feature.

**Comment by waptik** [comment]
Thanks. I just tested with npx and it's working. So i'll update the docs this Thursday using npx in the instructions.
Umzug's mongodbstorage is only used to store and track migrations (and seeders with tweaks) in the database. but i'm open to suggestions on how best it can be used.

**Comment by vkarpov15** [comment]
Maybe my understanding of how people do migrations is limited, but in my experience avoiding re-running migrations is important, and ensuring that people delete migrations is brittle
