### ISSUE TITLE
Question regarding MongoClient reconnection and numberOfRetries counter

### ISSUE THREAD

**Issue by niftylettuce** [Automattic/mongoose#8143]
If a connection is established, does the MongoClient `numberOfRetries` count get reset back to zero?  For example. if I have retry count set to `5`, and it attempts to reconnect 3 times, then connection is established, does a future reconnect counter start at 0, or does it start at 3 (from the previous reconnect attempt)?

cc @vkarpov15

**Comment by vkarpov15** [comment]
It gets reset to 5. If you're connected, you need to fail reconnection `numberOfRetries` times in a row for the mongodb driver to give up reconnecting.
