### ISSUE TITLE
Support useUnifiedTopology in connection.openUri

### ISSUE THREAD

**Issue by AndrewBarba** [Automattic/mongoose#8146]
Feature Request:

Add support for `useUnifiedTopology` in `Connection.openUri`

Explanation:

Mongoose 5.7 upgraded to MongoDB v3.3 which supports the new `useUnifiedTopology` option. Currently Mongoose supports this in `createConnnection` but does not support it in `Connection.openUri`. We use `openUri` to delay the actual connecting process until something uses it, thus we do not pass any options into `createConnection` when our app starts up.

**Comment by AndrewBarba** [comment]
This might actually be supported as is, and is just missing from the `openUri` docs

**Comment by vkarpov15** [comment]
Looks like this issue was just in the docs, should be fixed in 5.7.1, which we will release within the next couple days :+1:

**Comment by Arman2205** [comment]
.
