### ISSUE TITLE
Write to mongodb using raw JSON not POJSOs

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#8147]
I probably should ask this question on StackOverflow but lately not getting good answers on there.

I want to do something like this:

```js
db.collection.insert(' [ { "foo": 55 }, { "foo" : 3 } ] ', // JSON string, not an object
   {
     writeConcern: <document>,
     ordered: <boolean>
   }
)
```

so what I mean is I want to write JSON directly to the DB, I don't want to convert to JS, then write to the DB. Is it possible to write JSON using one of the standard MongoDB SDKs or using Mongoose? I am looking to get high performance, mainly.

https://docs.mongodb.com/manual/reference/method/db.collection.insert/

I put the Q on SO too:
https://stackoverflow.com/questions/57863119/insert-raw-json-into-mongodb

**Comment by vkarpov15** [comment]
Unfortunately not, I don't know of anything that can go straight from JSON string to BSON directly without converting to JSON first. Are you concerned that the JSON string is too large? If that's the case you might want to try JSONStream or something similar.

**Comment by ORESoftware** [comment]
nah I mean instead ofo this:

```
coll.insert({foo:'bar'});
```

make something like this work:

```js
coll.insert('{"foo":"bar"}', {raw:true});
```

**Comment by vkarpov15** [comment]
I don't know of any JavaScript libs that can convert a JSON string to BSON without calling `JSON.parse()` to convert to a JS object.

My 2 cents: `JSON.parse()` is generally fast enough and unlikely to be a bottleneck. If your app is sufficiently performance sensitive that `JSON.parse()` is causing you performance issues, you might want to use a lower level language than JavaScript.
