### ISSUE TITLE
Warning: no saslprep library specified. Passwords will not be sanitized.

### ISSUE THREAD

**Issue by nviethuan** [Automattic/mongoose#8152]
Mongoose version: 5.7.0

-  connection.ts

```
connect(`mongodb://${ db_username }:${ db_password }@localhost:27017/${dbName}`).then(() => {
  console.log(`Connect database successfully!`);
}).catch(error => {
  console.error(error);
});
```

- my console.log

```
Warning: no saslprep library specified. Passwords will not be sanitized
Connect database successfully!
```

-  Catch error from /node_modules/mongodb/lib/core/auth/scram.js:14

```
Error: ENOENT: no such file or directory, open '/code-points.mem'
```

I installed `saslprep` from npm but not working and show warning. How i can remove this warning?

Node version: 10.16.0
Mongo version: 4.2.0 (pull lastest from https://hub.docker.com/_/mongo)

**Comment by tk120404** [comment]
@nviethuan the warning is not from mongoose whereas it is from [mongodb-core](https://github.com/mongodb-js/mongodb-core) js module. Requesting you to the close issue.

**Comment by sayhicoelho** [comment]
Solved installing the missing `saslprep` library. Ref: https://stackoverflow.com/a/57234317/4158755
