### ISSUE TITLE
Feature Request: Recursively deep populate collections that have refs onto themselves.

### ISSUE THREAD

**Issue by mkhoussid** [Automattic/mongoose#8153]
**Feature request**

**What is the current behavior?**
Mongoose `populate` does not deep populate documents with refs on themselves

**What is the expected behavior?**
If I have a schema defined as,

```
const commentSchema = new Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "user"
    replies: [
        {
        type: mongoose.Schema.Types.ObjectId,
        ref: "comment"
        }
    ], . . . .
```
And I query for all comments that have replies, which also may have replies, i.e.

```
const comments = await Comment.findById("comment1").populate({
  path: "replies",
  populate: [
    {
      path: "replies"
    }
  ]
});
```
I should get all replies deeply populated.

Instead, I get two levels populated, the main comment and its direct replies, excluding replies to those replies:

```
{
    "parentCommentId": null,
    "_id": "comment1",
    "user": "user1",
    "text": "OP",
    "post": "post1",
    "replies": [
        {
            "parentCommentId": "comment1",
            "replyCount": 1,
            "_id": "comment2",
            "user": "user2",
            "text": "reply",
            "post": "post1",
            "replies": [
                {
                    "parentCommentId": "comment2",
                    "_id": "comment3",
                    "user": "user3",
                    "text": "reply to a reply",
                    "post": "post1",
                    "replies": [
                        "5d7757a2e6835f6d98ce723f" // <--- this is not populated
                    ]
                }
            ]
        }
    ]
}
```

[Stackoverflow question](https://stackoverflow.com/questions/57867001/mongoose-query-not-deep-populating-fully?noredirect=1#comment102162093_57867001) for reference if neccessary.

I've taken a look at [mongoose-deep-populate](https://www.npmjs.com/package/mongoose-deep-populate), however it does not work as expected. I have to run a string builder to populate how many `replies` I want. Right now, I added a new property to `Comment`, and I'm building the string and populating that way:

```
    let i = 0;
    let nestedQueryString = "replies";

    for (i; i < selectedComment.totalNestsOfComments; i++) {
      if (i !== 0) {
        nestedQueryString += ".replies";
      }
    }

    const populatedSelectedComment = await selectedComment.deepPopulate(
      nestedQueryString
    );

    // nestedQueryString could be as long as 'replies.replies.replies.replies.replies.replies.replies'
```

**What are the versions of Node.js, Mongoose and MongoDB you are using?**
Node v12
MongoDB v4
Mongoose v5.5.11

**Comment by vkarpov15** [comment]
We're unlikely to support this anytime soon. The `populate()` API is designed to only populate the paths you specified, not guess which paths should be populated. The [mongoose-autopopulate plugin](https://plugins.mongoosejs.io/plugins/autopopulate) should be able to help you though: 

```javascript
const commentSchema = new Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "user",
        autopopulate: true
    replies: [
        {
        type: mongoose.Schema.Types.ObjectId,
        ref: "comment",
        autopopulate: true
        }
    ]
```
