### ISSUE TITLE
Model.populate() results in array, even if single ObjectID is being populated when using 'skipInvalidIds' option

### ISSUE THREAD

**Issue by Hyperblaster** [Automattic/mongoose#8157]
When calling Model.populate() on a document or an array of documents, Mongoose returns the populated path as an Array.

The expected behaviour would be that if the path's value is a single ObjectId, String or Object (_using the skipInvalidIds property_) it should return a single Document, and if the value is an array then to return an Array of documents.

**Schema**
```javascript
var PhotoSchema = new Schema({
    title: {
        type: String,
    },
    data: {
        type: Schema.Types.Mixed,
    },
});

var Photo = mongoose.model('photo', PhotoSchema);

```

**Example Document**
```json
{
  "title":"Example",
  "data":{
     "photographer":{
           "_id":"5a9390c84028396d2a374432",
           "title":"John Smith",
     }
  }
}
```

**Code to Populate**
```javascript

var items; //Array of documents containing the example document above

return Photo.populate(items, {
          path:"data.photograpger",
          select: controller.basicFields,
          skipInvalidIds: true, 
}, done);                        
```

**Current Output**
```json
{
  "title":"Example",
  "data":{
     "photographer":[
     {
           "_id":"5a9390c84028396d2a374432",
           "title":"John Smith",
     }
     ]
  }
}       
```

**Expected Output**
```json
{
  "title":"Example",
  "data":{
     "photographer":{
           "_id":"5a9390c84028396d2a374432",
           "title":"John Smith",
     }
  }
}       
```

This is really in relation to the skipInvalidIds feature, as if the objects are depopulated when saved to the database everything works as expected, It's just for when there are objects in the database that aren't plain ObjectIds but are objects with an _id that cause the issue.

My understanding was that  when using the 'skipInvalidIds' feature the data would stay the same as it originally was before calling populate(), It's seems like it's a bit smarter than that and is actually populating the object picking up the _id property. Which is nice, it just needs to understand whether it's a single ID or an array of multiple IDs when it returns

**Comment by vkarpov15** [comment]
You can work around this by setting the `justOne` option:

```javascript
var items; //Array of documents containing the example document above

return Photo.populate(items, {
          path:"data.photograpger",
          select: controller.basicFields,
          skipInvalidIds: true,
          justOne: true 
}, done);    
```

The fact that you need to set `justOne` here is a bug that we will fix. Just suggesting it as a workaround.
