### ISSUE TITLE
Cannot read property '_update' of undefined

### ISSUE THREAD

**Issue by AdamBCo** [Automattic/mongoose#8160]
**Do you want to request a *feature* or report a *bug*?**
*bug

**What is the current behavior?**
When using **findOneAndUpdate**, I receive the following error: **Cannot read property '_update' of undefined**. The **find** and **findOne** queries work as expected.

Please find the model I am using, along with the query I am trying to perform below.

### Model
    const schema = mongoose.Schema(
    	{
    		name: { type: String, trim: true }
    	}
    	{
    		timestamps: {
    			createdAt: 'created_at',
    			updatedAt: 'updated_at'
    		}
    	}
    )

    module.exports = mongoose.model('Contact', schema)

### Query
	Contact.findOneAndUpdate({
		_id
	}, {
		$set: {
		    name: "adam"
        }
	}, {
		new: true 
	})
		.then((result) => res.status(200).json(result))
		.catch((error) => res.boom.badRequest(error))
		
**What is the expected behavior?**
I expect to recieve an updated Contact object.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.7.0

**Comment by fernandolguevara** [comment]
@AdamBCo try with version 5.7.1 this bug is fixed with #8151

**Comment by vkarpov15** [comment]
This issue should be fixed in [5.7.1](https://github.com/Automattic/mongoose/blob/master/History.md#571--2019-09-13) as @fernandolguevara said. Sorry for the trouble!
