### ISSUE TITLE
Mongoose masks errors in setters

### ISSUE THREAD

**Issue by safer-bwd** [Automattic/mongoose#8162]
**Do you want to request a *feature* or report a *bug*?**
 I'm not sure. It seems to me like a bug.

**What is the current behavior?**
Mongoose masks errors in setters.

```javascript
import mongoose from 'mongoose';

const schema = new mongoose.Schema({
  name: {
    type: String,
    set: () => { throw new Error('Error!'); }
  }
});
const Model = mongoose.model('Model', schema);

const model = new Model({});
model.name = 'name'; // model.name === undefined
```

**What is the expected behavior?**
I think Mongoose should not masks errors  in setters.

```javascript
const model = new Model({});
model.name = 'name'; // throw error 
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.7.0

**Comment by vkarpov15** [comment]
It is expected behavior - we do not report the error until you try to [`validate()`](https://mongoosejs.com/docs/api/document.html#document_Document-validate) the document, including if you try to [`save()`](https://mongoosejs.com/docs/api/model.html#model_Model-save). Mongoose does track the error in the setter, it just doesn't report it until you call `validate()` or `save()`.

```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  name: {
    type: String,
    set: () => { throw new Error('Error!'); }
  }
});
const Model = mongoose.model('Model', schema);

const model = new Model({});
model.name = 'name'; // model.name === undefined

// Error: Error!
console.log(model.validateSync().errors['name'].reason);
```

**Comment by safer-bwd** [comment]
Ok, but if this is an error in the code. For example, _TypeError_ or _ReferenceError_. So mongoose masks bugs.

**Comment by vkarpov15** [comment]
It doesn't mask bugs, it surfaces them later when you try to `save()`.
