### ISSUE TITLE
Creating array discriminators only takes two parameters?

### ISSUE THREAD

**Issue by chaeron** [Automattic/mongoose#8164]
When you create an array discriminator, you do something like this:

var Clicked = docArray.discriminator('Clicked', clickedSchema);

But if you do a model discriminator you can add a third parameter to specify the discriminator key value:

var Clicked = Event.discriminator('Clicked', clickedSchema, "clicked");

Just wondering why we can't use a 3rd discriminator key parameter when we use array discriminators?  I'm assuming the first parameter is still the model name, so it would be nice to have the ability to specify the key value if you want it to be different from the Model name.

Thanks!

**Comment by vkarpov15** [comment]
Good suggestion, will fix.

**Comment by chaeron** [comment]
You going to update the documentation as well? ;-)

**Comment by vkarpov15** [comment]
I don't think we have docs for this yet, but that's definitely something to add for the future
