### ISSUE TITLE
Client-Side Field Level Encryption

### ISSUE THREAD

**Issue by b00tsy** [Automattic/mongoose#8167]
*Feature request*

Is the new mongo 4.2 feature [Client-Side Field Level Encryption](https://docs.mongodb.com/manual/core/security-client-side-encryption/ ) something you're planning to integrate or do you suggest using [mongoose-encryption](https://www.npmjs.com/package/mongoose-encryption) or [mongoose-field-encryption](https://www.npmjs.com/package/mongoose-field-encryption)?

**Comment by vkarpov15** [comment]
4.2's new field level encryption is something we'll look into for our next minor release (ETA December 2019). For now you can just use mongoose-encryption. Or if you're willing to help try out mongoose with field-level encryption, we're happy to help out with any issues you run into :+1:

**Comment by b00tsy** [comment]
Ok excellent. You say I should just try creating my mongoose connection by defining `autoEncryption` within the options as described here: https://www.npmjs.com/package/mongodb-client-encryption (which seems to be a part of nodejs mongodb client and see what happens?

I'm not quite sure, yet, how `manual field level encryption` client side encryption would work and how the `enterprise only` feature `automatic field level encryption` would work if I would only want to encrypt specific fields (https://docs.mongodb.com/manual/core/security-client-side-encryption/).

Would `manual field level encryption` mean implementing custom pre or post save hooks with mongoose for the fields I want to encrypt and then calling `ClientEncryption.encrypt()` and then again hooks to decrypt the data again?

I've had a look at https://www.npmjs.com/package/mongoose-field-encryption and was not very pleased to see that I would have to construct queries with encryption query parameters.

https://www.npmjs.com/package/mongoose-encryption looked more appealing letting me define specific fields I want to encrypt, but comes with the drawback, that `.lean()` would not work anymore.

**Comment by jakegibson** [comment]
@vkarpov15 is it looking like it will make it into the December release? Thanks!

**Comment by vkarpov15** [comment]
I took a closer look and there isn't much for Mongoose to do to support rudimentary client-side field level encryption. Here's the steps you need to follow.

1) Install MongoDB 4.2 Enterprise. In particular, make sure the new [`mongocryptd` executable](https://docs.mongodb.com/manual/core/security-client-side-encryption/#encryption-components) is in your `$PATH`. Client-side field level encryption (CSFLE for short) will **not** work on MongoDB community edition.

2) `npm install mongodb-client-encryption uuid-base64 mongoose@^5.7.13`

3) The below standalone script should work:

```javascript
'use strict';

const Encrypt = require('mongodb-client-encryption');
const base64 = require('uuid-base64');
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  /* Step 1: Connect to MongoDB using autoEncryption */

  // Create a very basic key. You're responsible for making
  // your key secure, don't use this in prod :)
  const arr = [];
  for (let i = 0; i < 96; ++i) {
    arr.push(i);
  }
  const key = Buffer.from(arr);

  const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    // Configure auto encryption
    autoEncryption: {
      keyVaultNamespace, 
      kmsProviders
    }
  });

  /* Step 2: create a key and configure encryption using JSONschema */

  // Currently, mongodb-client-encryption exports a constructor
  // that takes an instance of the mongodb module as a parameter
  const { ClientEncryption } = new Encrypt(require('mongodb'));
  const encryption = new ClientEncryption(mongoose.connection.client, {
      keyVaultNamespace,
      kmsProviders,
    });

  const _key = await encryption.createDataKey('local');

    // CSFLE is defined through JSON schema. Easiest way to set
  // a JSON schema on your collection is via `createCollection()`
  await mongoose.connection.dropCollection('tests').catch(() => {});
  await mongoose.connection.createCollection('tests', {
    validator: {
      $jsonSchema: {
        bsonType: 'object',
        properties: {
          // Automatically encrypt the 'name' property
          name: {
            encrypt: {
              bsonType: 'string',
              keyId: [_key],
              algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic' }
          }
        }
      }
    }
  });

  /* Step 3: Create a Mongoose model that uses the encrypted collection and see encryption in action */

  // 'super secret' will be stored as 'BinData' in the database,
  // if you query using the `mongo` shell.
  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  await Model.create({ name: 'super secret' });
}
```

We'll add some more syntactic sugar so you can define encryption in your schemas (#8406), but right now there's nothing blocking you from using CSFLE in Mongoose. Step (2) above is something you only need to do once, and you can do it in the mongo shell. Once you've configured the JSON schema correctly, all you need to do for CSFLE is to set the `autoEncryption` option to [`mongoose.connect()`](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-connect)

**Comment by maheshvadada** [comment]
Getting **TypeError: require(...) is not a function**

**Comment by LucaDario** [comment]
@vkarpov15 Hi and thx for the solution BUT not work for the same @maheshvadada  isuue.
I installated mongodb-client-encryption@1.0.0 and mongoose@5.8.1.

If I create a connection with this code:

```
const Encrypt = require('mongodb-client-encryption');
const base64 = require('uuid-base64');
const mongoose = require('mongoose');


const clientSideFieldLevelEncryptionOptions = {
        keyVaultNamespace : "client.encryption",
        kmsProvider : {
            aws : {
              accessKeyId : "AC",
              secretAccessKey : "SC"           
              }
          }
    }
mongoose.connect(uri, {autoEncryption: clientSideFieldLevelEncryptionOptions}, function(err) {
        if (err) {
            logging.logger.error(err);
        }
    });
```


getting TypeError: require(...) is not a function

**Comment by jakegibson** [comment]
This issue is fixed in mongodb 3.4 drive, we had to manually patch for time being

**Comment by LucaDario** [comment]
@jakegibson you know what  (and what  driver files) i must modify to resolve this issuee manually in mongoose 5.8.1?
Thx

**Comment by jakegibson** [comment]
@LucaDario Mongoose currently has  "mongodb": "3.3.5" as a dep in it's package.json.  Update this to 3.4.0 . @vkarpov15  is this getting bumped in the next mongoos release?

**Comment by vkarpov15** [comment]
@jakegibson yes we will use mongodb@3.4.1 for Mongoose 5.8.3.

**Comment by maheshvadada** [comment]
Getting error as `UnhandledPromiseRejectionWarning: MongoError: Unable to connect to `mongocryptd`, please make sure it is running or in your PATH for auto-spawn` with **MongoDB Atlas**

**Comment by LucaDario** [comment]
@maheshvadada you must create a uri connection with a mongocryptURI (put the uri connection of atlas).
Can put this value into the second value of MongoClient constructor. 
The code will look like:
`const encryptedClient = new MongoClient(uri, {
                useUnifiedTopology: true,
                autoEncryption: {
                    keyVaultNamespace,
                    kmsProviders,
                    schemaMap,
                    extraOptions: {
                        mongocryptdURI: uri
                    },
                }
            });`

extraOptions.mongocryptdURI is the uri of the mongocrypt.

**Comment by maheshvadada** [comment]
@LucaDario 
Getting error as  **UnhandledPromiseRejectionWarning: MongoError: BSON field 'insert.jsonSchema' is an unknown field.**

my code is 

```
await mongoose.connect(conn_str, {
  useNewUrlParser: true,
  useUnifiedTopology: true,  
  autoEncryption: {
	keyVaultNamespace,
	kmsProviders,
	extraOptions : {	  
	  mongocryptdURI: conn_str
	}
  }
});
const encryption = new ClientEncryption(mongoose.connection.client, {
  keyVaultNamespace,
  kmsProviders,
});

var key = await encryption.createDataKey('aws', {
  masterKey: {
	key: KMS_ARN,
	region: REGION,
  }
});
```

I am new to mongoDB Atlas. Can anyone help me to find out the **mongocryptdURI** path in mongoDB Atlas? or how to start the **mongocryptd** service in mongodb atlas?

**Comment by vkarpov15** [comment]
@maheshvadada when you create a collection, you also need to set a `validator.$jsonSchema` option on the collection as shown in [step 2 of this comment](https://github.com/Automattic/mongoose/issues/8167#issuecomment-562869693).

I took a look but I'm unable to figure out how to set up Atlas with mongocryptd. I'd reach out to Atlas support. You can also just [install mongocryptd](https://docs.mongodb.com/manual/reference/security-client-side-encryption-appendix/#installation) and run it locally, no need to go through Atlas.

**Comment by oscarhibbert** [comment]
Hi there and thank you for your solution. After creating a new collection with the jsonSchema, on write operations I get the error "Invalid schema containing the 'encrypt' keyword."

Here is my schema code:
`
// CSFLE is defined through JSON schema. Easiest way to set
    // a JSON schema on your collection is via `createCollection()`
    await mongoose.connection.dropCollection('entries').catch(() => {});
    await mongoose.connection.createCollection('entries', {
      validator: {
        $jsonSchema: {
          bsonType: ['object', 'array'],
          properties: {
            // Automatically encrypt the 'name' property
            name: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            },
            email: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            },
            text: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            }
          }
        }
      }
    });
`

**Comment by oscarhibbert** [comment]
Hi there and thank you for your solution. After creating a new collection with the jsonSchema, on write operations I get the error "Invalid schema containing the 'encrypt' keyword."

Here is my schema code:
```
// CSFLE is defined through JSON schema. Easiest way to set
    // a JSON schema on your collection is via `createCollection()`
    await mongoose.connection.dropCollection('entries').catch(() => {});
    await mongoose.connection.createCollection('entries', {
      validator: {
        $jsonSchema: {
          bsonType: ['object', 'array'],
          properties: {
            // Automatically encrypt the 'name' property
            name: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            },
            email: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            },
            text: {
              encrypt: {
                bsonType: 'string',
                keyId: [_key],
                algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic'
              }
            }
          }
        }
      }
    });
```

**Comment by vkarpov15** [comment]
@oscarhibbert please open a new issue and follow the issue template
