### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zack1991** [Automattic/mongoose#8168]
Hi, 

I am getting the exception **maximum call stack size exceeded** in below code.

Node - v8.12.0
mongoose - 5.7.0
mongodb - 4.0

```
exports.updateData = async function (req, res) {
    try {
        const dataToUpdate = {}, responseData = {result: 1};
        dataToUpdate[req.body.column] = parseInt(req.body.column_value);
        dataToUpdate['$inc'] = dataToUpdate;

        const dataToSelect = {};
        dataToSelect[req.body.column] = 1;
        const gameUserData = await updateAndGetGameUser({_id: req.body.user_id}, dataToUpdate, dataToSelect);
        if (gameUserData !== null) {
            responseData[req.body.column] = gameUserData[req.body.column];
        }
        res.send(responseData);
    } catch (exc) {
        console.log("Exception Message ==> " + exc.message + ", Stact Trace ==> " + exc.stack);
    }
}

function updateAndGetGameUser (match, dataToUpdate, dataToSelect, lean = false) {
    return new Promise((resolve, reject) => {
        GameUser.findOneAndUpdate(
                match,
                dataToUpdate,
                {lean: lean, new : true, fields: dataToSelect},
                function (error, userInfo) {
                    if (error) {
                        reject(error);
                    } else {
                        resolve(userInfo);
                    }
                }
        );
    });
};
```

Exception :- 
Exception Message ==> Maximum call stack size exceeded, Stact Trace ==> RangeError: Maximum call stack size exceeded
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)
12|node-slots-service-1339  |     at cloneObject (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:321:17)
12|node-slots-service-1339  |     at clone (/data/node-slots-service-v2/node_modules/mongoose/lib/utils.js:205:16)

Please help me how to resolve this issue.

**Comment by fernandolguevara** [comment]
@zack1991  try doing this 

```js
const dataToUpdate = {
  $inc: {
    [req.body.column]: parseInt(req.body.column_value),
  },
};
```

btw you can modify updateAndGetGameUser `findOneAndUpdate` already return a Promise

```js

function updateAndGetGameUser(match, dataToUpdate, dataToSelect, lean = false) {
  return GameUser.findOneAndUpdate(match, dataToUpdate, {
    lean: lean,
    new: true,
    fields: dataToSelect,
  });
}
```

**Comment by vkarpov15** [comment]
`dataToUpdate['$inc'] = dataToUpdate;` That line is your issue. If you pass a circular object to a query, you'll get this error. Why do you have this circular reference in your update?
