### ISSUE TITLE
Typescript: Asynchronous custom validation with error message

### ISSUE THREAD

**Issue by lambou** [Automattic/mongoose#8171]
The current validate type in _@types/mongoose/index.d.ts_ is:

```typescript
validate?: RegExp | [RegExp, string] |
    SchemaTypeOpts.ValidateFn<T> | [SchemaTypeOpts.ValidateFn<T>, string] |
    SchemaTypeOpts.ValidateOpts | SchemaTypeOpts.AsyncValidateOpts |
    SchemaTypeOpts.AsyncPromiseValidationFn<T> | SchemaTypeOpts.AsyncPromiseValidationOpts |
    (SchemaTypeOpts.ValidateOpts | SchemaTypeOpts.AsyncValidateOpts |
      SchemaTypeOpts.AsyncPromiseValidationFn<T> | SchemaTypeOpts.AsyncPromiseValidationOpts)[];
```

Here is the definition where you can give the validation message:
**[SchemaTypeOpts.ValidateFn<T>, string]** it is synchronous only

can you add somthing like **[SchemaTypeOpts.AsyncPromiseValidationFn<T>, string]**

so it will be possible to write (using async):

```typescript
const TestSchema = new Schema({  
    user : {
        type: Schema.Types.ObjectId,
        ref: 'User',
        validate: [
            async function(value){
                return UserSchema.findOne({_id: value}) != null;
            },
            `User doesn't exist.`
        ]
    }
}
```

Thanks in advance

**Comment by hasezoey** [comment]
mongoose currently dosnt make offical typescript types, you should open a new issue in https://github.com/DefinitelyTyped/DefinitelyTyped/issues

reference: https://github.com/Automattic/mongoose/issues/8108
