### ISSUE TITLE
Previously fixed bug was reintroduced

### ISSUE THREAD

**Issue by jimmytsao** [Automattic/mongoose#8173]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A previously reported bug was fixed in version 5.1.3 of mongoose. Starting with version 5.2.5, the bug has been reintroduced.

Previously fixed bug: https://github.com/Automattic/mongoose/issues/6488

**If the current behavior is a bug, please provide the steps to reproduce.**

See the reproduction script in the link above under the section: 

_Virtual Population NOT WORKING When Virtual Field Is Nested Within Embedded Object Schema_

**What is the expected behavior?**
I expected the issue to be resolved in all versions after 5.1.3

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.7.1
node: 10.14.1
mongo: 3.6.4

**Comment by vkarpov15** [comment]
Sorry for the trouble, it looks like our test case for #6488 didn't test the full integration, just tested a unit that happened to cause this issue in 2018. We added a full integration test for this issue, so virtual populate on a nested schema within an embedded discriminator should work fine going forward as of 5.7.3 :+1:
