### ISSUE TITLE
find document by the id of a referenced collection

### ISSUE THREAD

**Issue by byteCrunsher** [Automattic/mongoose#8174]
**Do you want to request a *feature* or report a *bug*?**

Help

**What is the current behavior?**

Currently I have two models. **AuthenticationModel**

```
const authenticationSchema: Schema = new mongoose.Schema({
	user: {
		ref: 'User',
		required: true,
		unique: true,
	},
	passwordHash: {
		type: String,
		required: true,
	},
	passwordSalt: {
		type: String,
		required: true,
	},
});
```

and **UserModel**

```
const userSchema: Schema = new mongoose.Schema({
	_id: mongoose.Schema.Types.ObjectId,
	username: {
		type: String,
		required: true,
		unique: true,
	},
});
```

I want to select one authentication document where the user id matches. Given this code

```
public fetchUserAuthenticationByUserId = async ({ user }: { user: Document }): Promise<Document> => {
	try {
		const authentication: Document | null = await AuthenticationModel.findOne().where(
			'user._id',
			user.toJSON()._id // Access the props from the document interface
		);

		if (!authentication) {
			throw new NotFoundException('User was not found.');
		}

		return authentication as Document;
	} catch (error) {
		throw error;
	}
};
```

I pass in a user document and want to select the authentication document by the user id. When running the application I get this error

>     throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
>           ^
> TypeError: Invalid schema configuration: `User` is not a valid type at path `user.ref`.

**What is the expected behavior?**

I would like to know how to select one document by passing in the ID of a unique foreign key.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node: v10.16.3
- Mongoose: 5.7.1
- @types/mongoose: 5.5.17
- MongoDB Compass: 1.19.12 Community Edition

**Comment by vkarpov15** [comment]
You need to set a `type` on your `user` path. For example:

```javascript
const authenticationSchema: Schema = new mongoose.Schema({
	user: {
                type: mongoose.ObjectId, // <-- this is what you're missing
		ref: 'User',
		required: true,
		unique: true,
	},
        // ...
```
