### ISSUE TITLE
Discriminator Key can only be of type String

### ISSUE THREAD

**Issue by arch1995** [Automattic/mongoose#8177]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently, Discriminator key can only be of string type even if we define the type of discriminator key in Schema as Number. But when we query using the Discriminator Model.find(), then it converts the number to a string and then adds it to the query.

Mongoose: v5.4.22
Node: v10.15.3

**Comment by vkarpov15** [comment]
What's the feature request here? Can you please provide some code samples?
