### ISSUE TITLE
Populate virtuals - exclude localField and foreignField from the query results if foreignField is null or an empty array

### ISSUE THREAD

**Issue by thecatishungry** [Automattic/mongoose#8179]
**Do you want to request a *feature* or report a *bug*?**

I have a question.

**What is the current behavior?**

    (async () => {
        const target_time = 1568851200000;
        const leagues = await Leagues
            .find({})
            .populate({ path: 'fixtures', match: { timestamp: { $gte: target_time } } })
            .lean();
            console.log(leagues);
    })();

**Current result**:

    [
        {
            id: 2,
            name: 'Champions League',
            fixtures: []
        },
        {
            id: 5,
            name: 'Europa League',
            fixtures: [
                [Object],
                [Object],
                [Object],
                [Object],
            ]
        },
        {
            id: 8,
            name: 'Premier League',
            fixtures: []
        }
    ];

**What is the expected behavior?**

Not expected, but desired (what my question is about).

**Desired result**:

    [
        {
            id: 5,
            name: 'Europa League',
            fixtures: [
                [Object],
                [Object],
                [Object],
                [Object],
            ]
        },
    ];

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v10.16.0
Mongoose: 5.7.1
Express: 4.17.1
MongoDB shell version v4.0.2
MongoDB server version: 4.0.2

---

**Full explanation:**

I have a simple question.

In Mongoose I have two models. One is for `Leagues` and the other one is for `Fixtures`. Each league has a unique `id`, and each fixture is related to a league with it's key of `league_id`.

In the `Leagues` schema I have also defined a virtual called `fixtures`.

    const mongoose = require('mongoose');
    const Schema = mongoose.Schema;
    
    const LeagueSchema = new Schema(
        {
            _id: { type: mongoose.Schema.Types.ObjectId, select: false, auto: true },
            id: { type: Number, required: true, unique: true, index: true },
            name: { type: String, required: true },
        }
    );
    
    LeagueSchema.virtual('fixtures', {
        ref: 'fixtures',
        localField: 'id',
        foreignField: 'league_id',
        justOne: false,
    });
    
    const Leagues = mongoose.model('leagues', LeagueSchema);
    
    const FixtureSchema = new Schema(
        {
            _id: { type: mongoose.Schema.Types.ObjectId, select: false },
            match_id: { type: Number, required: true, index: true, unique: true },
            league_id: { type: Number, required: true },
            league_name: { type: String, required: true },
            timestamp: { type: Number, required: true, index: true },
        }
    );
    
    const Fixtures = mongoose.model('fixtures', FixtureSchema);

Here is the problem. The list of all leagues is very big and not all of them will always have fixtures that match the `.populate()` so I want to exclude them from my query.

For example, if I don't want any fixtures older than a given timestamp, I will do the following:

    (async () => {
        const target_time = 1568851200000;
        const leagues = await Leagues
            .find({})
            .populate({ path: 'fixtures', match: { timestamp: { $gte: target_time } } })
            .lean();
            console.log(leagues);
    })();

What this does is it filters out the fixtures by timestamp correctly, but it does not exclude Leagues without fixtures from the query.

Here is what this query returns:

**Current result**:

    [
        {
            id: 2,
            name: 'Champions League',
            fixtures: []
        },
        {
            id: 5,
            name: 'Europa League',
            fixtures: [
                [Object],
                [Object],
                [Object],
                [Object],
            ]
        },
        {
            id: 8,
            name: 'Premier League',
            fixtures: []
        }
    ];

And here is what I want to achieve:

**Desired result**:

    [
        {
            id: 5,
            name: 'Europa League',
            fixtures: [
                [Object],
                [Object],
                [Object],
                [Object],
            ]
        },
    ];

I am aware that I can do something like `leagues.filter(item => item.fixtures.length > 0)`, but this query is going to be called tens of times each second, I'm afraid that running another filter after the query can lead to performance issues.

Any help or possible alternatives are appreciated.

**Comment by vkarpov15** [comment]
There's no way to do this with `populate()` unless you change your schema. `populate()` will load all leagues first, then execute a query for the corresponding fixtures. Even if `populate()` filtered for you, it would have to execute a `filter()` in memory like you suggested.

One potential workaround is storing each league's `firstFixtureTimestamp` - that's unlikely to change.

However, the likelihood that a single `filter()` will cause massive performance issues is minimal. If you find you have a performance issue with this query, you'd likely get much more performance improvement by [using `lean()`](https://mongoosejs.com/docs/tutorials/lean.html).
