### ISSUE TITLE
findOne({...data},{session}) Error

### ISSUE THREAD

**Issue by naxiaoguang** [Automattic/mongoose#8183]
mongodb4.2;
mongoose5.7.1;

```javascript
const options = {
  useNewUrlParser: true,
  useFindAndModify: false,
  readPreference: secondary,
};
mongoose.connect(uri, options);

const s = await mongoose.startSession();
```

1, await Article.findOne({ _id: articleId }).session(session);
"MongoError: Read preference in a transaction must be primary, not: secondary
please why?
2, await Article.findOne({ _id: articleId }).populate([path:'attr',options:{readPreference:secondary }]);
how to use session in populate ? 
Article.findOne({ _id: articleId },{populate:[{path:'attr'}], session}) ?

**Comment by vkarpov15** [comment]
Read the error message - apparently the MongoDB server doesn't support sessions if you're using `readPreference = 'secondary'`. Get rid of that and it should work. Why are you using sessions with secondary read preference? You can't write to the database if you're only sending operations to secondaries, and I don't know of any reason to use sessions if your application is read-only.
