### ISSUE TITLE
(node:25375) DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async va lidators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators

### ISSUE THREAD

**Issue by denzilgupta** [Automattic/mongoose#8184]
This is my code:

tags: {
        type: Array,
        validate: {
            isAsync: true,
            validator: function(value, callback) {
                setTimeout(() => {
                    const result =  value && value.minlength > 0;
                    callback(result);
                }, 4000);
            },
            message: 'A course must have at least one tag'
        }
    }

when I try to insert a value into mongodb, I get the below warning:
(node:25375) DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async va lidators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators

I saw the documentation and they too have used a callback function.
Please help me solve this problem!

Node Version:
v10.16.3

MongoDB Shell Version:
v4.2.0

Mongoose Version:
v5.7.1

**Comment by LouiseEmike** [comment]
@denzilgupta please how did you resolve this issue. I have the same issue now

**Comment by denzilgupta** [comment]
@LouiseEmike Can you show me the code? I think I'll be able to help you out better then.

**Comment by receptopalak** [comment]
@denzilgupta 
I get the same error, can you help me urgently


const mongoose = require('mongoose');
const Schema = mongoose.Schema;
//const GeoJSON = require('mongoose-geojson-schema');
const {
    Point,
    LineString,
    Polygon,
    MultiPoint,
    MultiLineString,
    MultiPolygon,
    Geometry,
    GeometryCollection
} = require('mongoose-geojson-schemas');


//new geo location schema
//const Geo = new Schema(Schema.Types.Point);

const geojson = new Schema(

    {
        konum: {
            type:  String,
            default: "Sazlıdere"
        },
        type: {
            type: String,
            default: "Feature"
        },
        properties: {
            name: {
                type: String,
                default: "bina"
            },
            surname: {
                type: String,
                default: "bina"
            }
        },
        geometry: Polygon
    }
);
const barrage = mongoose.model('intersect', geojson);
module.exports = barrage;

**Comment by denzilgupta** [comment]
> @denzilgupta
> I get the same error, can you help me urgently
> 
> const mongoose = require('mongoose');
> const Schema = mongoose.Schema;
> //const GeoJSON = require('mongoose-geojson-schema');
> const {
> Point,
> LineString,
> Polygon,
> MultiPoint,
> MultiLineString,
> MultiPolygon,
> Geometry,
> GeometryCollection
> } = require('mongoose-geojson-schemas');
> 
> //new geo location schema
> //const Geo = new Schema(Schema.Types.Point);
> 
> const geojson = new Schema(
> 
> ```
> {
>     konum: {
>         type:  String,
>         default: "Sazlıdere"
>     },
>     type: {
>         type: String,
>         default: "Feature"
>     },
>     properties: {
>         name: {
>             type: String,
>             default: "bina"
>         },
>         surname: {
>             type: String,
>             default: "bina"
>         }
>     },
>     geometry: Polygon
> }
> ```
> 
> );
> const barrage = mongoose.model('intersect', geojson);
> module.exports = barrage;

Are you getting an error on this file? Cause it seems to look fine.

**Comment by receptopalak** [comment]
@denzilgupta  yes, ı getting an error, ı think because of mongoose-geojson-schema npm package, can you help me ?

**Comment by vkarpov15** [comment]
@receptopalak please open a new issue and follow the issue template. Also, check out our geojson docs: https://mongoosejs.com/docs/geojson.html
