### ISSUE TITLE
ERROR AL CONECTAR MONGOBD ATLAS /NODEJS/Symbol(mongoErrorContextSymbol)

### ISSUE THREAD

**Issue by andreaAndrety** [Automattic/mongoose#8186]
"urlDB = 'mongodb + srv: //${USER}:${PASS}@cluster0-r8bkc.mongodb.net/cafe';
// }

process.env.URL_DB = urlDB;
mongoose.connect(process.env.URL_DB, {
        useNewUrlParser: true,
        useCreateIndex: true
    })
    .then(() => {
        //if (err) throw err;
        console.log("Base de datos online")
    }).catch((err) => {
        console.log(err);
    });"

![image](https://user-images.githubusercontent.com/32547893/65359945-a67fa680-dbc3-11e9-9608-512ea93fad01.png)

**Comment by vkarpov15** [comment]
Replace `mongodb + srv: //` with `mongodb+srv://`, no spaces.
