### ISSUE TITLE
loadClass and virtuals

### ISSUE THREAD

**Issue by waptik** [Automattic/mongoose#8188]
When using `loadClass`, how do i set `localField`, `foreignField` in virtuals?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.7.1

**Comment by vkarpov15** [comment]
I don't think there is a way currently if you're just using `loadClass()`. You would have to define virtuals that you `populate()` outside of `loadClass()` using `schema.virtual()`.

**Comment by waptik** [comment]
That's what i thought. Thanks for re-assuring me on it.

**Comment by vkarpov15** [comment]
I took a closer look and I don't think there's a viable way to do this using classes as they are in late 2019. We may be able to do this with property declarations, like

```javascript
class MyModel {
  myPopulateVirtual = { ref: 'MyOtherModel', localField: 'foo', foreignField: 'bar' }
}
```

But field declarations is still a stage 3 proposal. Something to think about later if Node.js has support for decorators or field declarations.
