### ISSUE TITLE
Validation: Access connection or custom validation sources

### ISSUE THREAD

**Issue by maikknebel** [Automattic/mongoose#8193]
**Do you want to request a *feature* or report a *bug*?**  => more like general help, maybe a feature(?)

**What is the current behavior?**
I am developing a RESTful-API and based on the context of the request, the validator should use differen data sources. At the time, when the models get loaded by mongoose, the data required for validation is not available yet. Actually i injected the data source right after i created a new object of the model. This works as expected so far, but i feel uncomfortable with this solution since i have to inject the data manually after every new call of a model.
The files below are simplified examples and separation of schema and connection is wanted, since the schema gets loaded into multiple different database-connections.

```
// animalSchema.js
import mongoose from 'mongoose';
const schema = new mongoose.Schema({
      species: {
        required: true,
        type: String,
        validate: {
          validator: function (v) {
            return this.$locals.availableSpecies.includes(v);
          }
        }
      }
    }));
export {schema as default};
```

```
// connection.js
import mongoose from 'mongoose';
import animalSchema from './animalSchema.js';
export const connection = mongoose.connect('....');
const AnimalModel = connection.model('Animal', animalSchema);

// => at this place i want to append availableSpecies= ['Cat', 'Bird', 'Cow'] to the model
// how?

// this would handy
AnimalModel.$locals = { foo: 'bar' } 

export AnimalModel;
```

```
// index.js
import {AnimalModel} from './connection.js';

const myPet = new AnimalModel({species: 'Fish'});

console.log(myPet.$locals.foo)      // undefined

// this is my workarround, but isn't very comfortable to manually add after every call of `new`
myPet .$locals.availableSpecies= ['Cat', 'Bird', 'Cow'];
myPet.validate();
```

**What is the expected behavior?**
Is there a way to add `availableSpecies` at a more centralized point, so i could access it at validation time (maybe via this or a parameter)?
Is there a way to access the connection, associated to the model, in the validation?

**What are the versions of Node.js, Mongoose and MongoDB you are using?**
mongoose: 5.7.1
nodejs: 12.9.1
mongodb: 4.0.4

**Comment by maikknebel** [comment]
Solved the problem myself by appending §locals to the connection object, that is accesible via this.db.$locals in the validation.

```
import mongoose from 'mongoose';

const connection = mongoose.connect('....');
connection.$locals = { 
    availableSpecies: ['Cat', 'Bird', 'Cow'] 
};

const AnimalModel = connection.model('Animal', new mongoose.Schema({
      species: {
        required: true,
        type: String,
        validate: {
          validator: function (v) {
            return this.db.$locals.availableSpecies.includes(v);
          }
        }
      }
    })));
```

**Comment by vkarpov15** [comment]
You could either do `AnimalModel.prototype.$locals = ...` or when accessing locals, do `this.constructor.$locals`
