### ISSUE TITLE
Mongoose x509 connection error

### ISSUE THREAD

**Issue by natvaldev** [Automattic/mongoose#8195]
I'm trying to connect to my `MongoDB` instance with connection string using `mongoose`.

I have succeeded connecting using `3T studio`, which is a mongodb ui viewer.

    const str = 'mongodb://host1,host2,host3/myapp?authSource=$external&replicaSet=myRep&ssl=true&authMechanism=MONGODB-X509&tlsCertificateKeyFile=key.pem&tlsCAFile=ca.pem'
    mongoose.connect(str, { useNewUrlParser: true })
      .then(console.log)
      .catch(console.error)

Both `key.pem` and `ca.pem` are in the same folder as `index.js` where I execute the app.

The error I get is:

    MongoNetworkError: Failed to connect to server [app1:27017] on first connect [MongoNetworkError: connect ETIMEOUT <IP>: 27017]
    name: 'MongoNetworkError',
    errorLabels: [ 'TransientTransactionError' ],
    [Symbol(mongoErrorContextSymbol)]: {}

What am I missing?  
How can I get a better error log?

**Comment by vkarpov15** [comment]
Based on the fact that the host name in the error message doesn't line up with the host name in your connection string, it sounds like you're running into this issue: https://mongoosejs.com/docs/connections.html#replicaset-hostnames . Make sure the hostnames on your replica set instances are correct.
