### ISSUE TITLE
`True` is not a valid type at path at propertyName.required

### ISSUE THREAD

**Issue by woodcockjosh** [Automattic/mongoose#8196]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a schema as follow

```js
const plansSchema = mongoose.Schema({
  frequency: {
    type: {
      type: {
        type: String,
       },
      length: {
        type: String,
        required: true,
      },
    },
    required: true,
  },
});
```
Get error when creating model: 
`True` is not a valid type at path `frequency.required`

or this: 
```js
const plansSchema = mongoose.Schema({
  frequency: {
    type: {
      type: String,
      length: {
        type: String,
        required: true,
      },
    },
    required: true,
  },
});
```
Get error when creating model: 
`True` is not a valid type at path `frequency.required`

or this: 
```js
const plansSchema = mongoose.Schema({
  frequency: {
      type: String,
      length: {
        type: String,
        required: true,
      },
    required: true,
  },
});
```
Get error when creating model: 
`True` is not a valid type at path `frequency.required`

**What is the expected behavior?**

Don't get an error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- NodeJS: 8.16.0
- mongoose: 5.7.1
- mongodb: 4.2.0

**Comment by sgatade** [comment]
@woodcockjosh 

```
const plansSchema = mongoose.Schema({    
  frequency: {    
    type: {    
      type: {    
        type: String,    
       },    
      length: {    
        type: String,    
        required: true,    
      },    
    },    
    required: true,    
  },    
});
```

has confusing Mixed types...

But this code works perfectly with the **new** keyword...

```
const plansSchema = new mongoose.Schema({
    frequency: {
        type: String,
        length: {
            type: String,
            required: true,
        },
        required: true,
    },
  });
```
Can you check?

Cheers!

SG

**Comment by vkarpov15** [comment]
Your schema as written defines a `frequency.type` path and a `frequency.required` path. Just get rid of the `required` declaration - it is redundant since `frequency.length` is required. 

Just do `Schema({ frequency: { type: { type: String }, length: { type: String, required: true } })`
