### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by orgads** [Automattic/mongoose#8200]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Inserting the first record causes "RangeError: Maximum call stack size exceeded"

**If the current behavior is a bug, please provide the steps to reproduce.**
* Start with a fresh Mongo database
* Set the following configuration:
```
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true); // this caused the bug
```
* Insert a document

**What is the expected behavior?**
It should work. We added this configuration to avoid deprecation warning in recent mongoose versions.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 10.16.3, mongoose 5.7.1, MongoDB 4.2.0

**Comment by vkarpov15** [comment]
What does your schema look like? Also, what does the stack trace look like? We have plenty of tests that cover the case you described and they're all passing
