### ISSUE TITLE
Change collection upon call

### ISSUE THREAD

**Issue by balexandre** [Automattic/mongoose#8205]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There is none, from the documentation

**What is the expected behavior?**
It would be really helpful to actually query MongoDB and have the possibility to pass the collection name we want to aim, so we could easily create a good use of dynamic collections

I've added a [Stackoverflow question](https://stackoverflow.com/q/58151499/28004), that maybe I could be wrong and there's a trick somewhere I miss... though without an answer

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node `10.16.0`
MongoDB using [mlab service](https://www.mlab.com) - running mongod version: 3.6.12 (MMAPv1)

mongoose npm package v. `5.7.1`

**Comment by sgatade** [comment]
Hi @balexandre,

Have you looked at the [Discriminator][1] feature of Mongoose? Using this, you can create a Base Log object and extend Prod/Dev/UT from the Base object. Mongoose will internally segregate between the types and choose the exact one for your queries...

[Simple example here][2]...

Cheers!

SG


  [1]: https://mongoosejs.com/docs/discriminators.html
  [2]: https://dev.to/helenasometimes/getting-started-with-mongoose-discriminators-in-expressjs--22m9

**Comment by balexandre** [comment]
Hey @sgatade, thanks for the reply, but it does not really work as you are working ion the schema level ... I need to work on runtime... 

would work well if I could use seomthing like `collection: process.env.COLLECTION` but in my request I have the environment ...

```text
/logs/dev&page=0
/logs/production
...
```

and for such, I need to be able to "switch" the collection, when calling `Collection.find()` for example ... it would be nice if I could simply do

```javascript
// tvshow.js

const Tvshow = new mongoose.Schema(
  {
    title: { type: String, required: true },
    season: { type: Number, required: true },
    release_date: { type: Date, required: true },
  }
);

module.exports = mongoose.model('Tvshow', TvshowSchema);

// query.js

exports.find = query => {
    Tvshow.setCollection(query.collection); // making sure I'm quering the right collection
    return Tvshow.find(query.options);
};

```

**Comment by vkarpov15** [comment]
Why don't you just register a separate model for each collection?

**Comment by balexandre** [comment]
> Why don't you just register a separate model for each collection?

if I have logs per `branch` (review app environments) I would need to edit my code for each an ever new branch? How would you make sure the registration only happens once?

Imagine if it bases on Client Guid's ... a new client, would have it's own collection, I would then need to check if the registrations for such client already existed or not ...

From you comment I started wonder and I've tried this successfully:

```javascript
const mongoose = require("mongoose");
const uuidv1 = require("uuid/v1");

const MONGO_URL ="mongodb://...";
mongoose.connect(MONGO_URL, { useNewUrlParser: true, useUnifiedTopology: true });

// registered upon start
const kittySchema = new mongoose.Schema({ name: String });
const Cat = mongoose.model("Cat-1", kittySchema, "Cat-1");

const main = collectionId => {
  let Cat = null;

  try {
    // attach if available
    Cat = mongoose.model(`Cat-${collectionId}`);
  } catch (err) {
    // Schema hasn't been registered for model XXXXX
    console.log("TRY/CATCH: " + err.message);
    // register
    Cat = mongoose.model(`Cat-${collectionId}`, kittySchema, `Cat-${collectionId}`);
    console.log(`Registration Cat-${collectionId} DONE`);
  }

  const kitty = new Cat({ name: "Zildjian - " + uuidv1() });
  kitty
    .save()
    .then(() => console.log(`meow (${collectionId})`))
    .catch(err => console.log("ERROR: ", err.message));
  // .then(() => process.exit(0));
};

main(1);
main(1);
main(2);
main(3);
main(4);
```

and I got it to work pretty well... just wish I could do the same (check for model availability) without the try/catch ... but then again, we're kind'a used to when it comes to async/await as well

Thanks @vkarpov15

**Comment by vkarpov15** [comment]
Hmm so you are programmatically creating collections based on user input? Like if I'm putting up a new branch for review, that creates a new collection? If so, why are you going that route?

**Comment by balexandre** [comment]
> Hmm so you are programmatically creating collections based on user input? Like if I'm putting up a new branch for review, that creates a new collection? If so, why are you going that route?

Exactly, branch is just as the example... I have clients, and those clients have employees and each employee have time entries that can be multiple per hour... for the last 5 years...

So I thought, as MongoDb says there's no issue if there's multiple collections or just one, the throughput is exactly the same, to make things easier for us humans ready stuff, if I setup a collection per each client, and every week there's 5 new clients ... so it has to be created programagically :)
