### ISSUE TITLE
Cross-posting question regarding un-handle-able disconnect/error event 

### ISSUE THREAD

**Issue by ORESoftware** [Automattic/mongoose#8206]
I have this question on SO:
https://stackoverflow.com/questions/58176277/how-to-handle-disconnect-error-for-mongodb

```

Uncaught exception: { Error: read ETIMEDOUT
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true } }

```

I am trying to trap that error for a particular connection and attempt to re-connect?
Something like this:

```js
import * as mdb from 'mongodb'
const d = new mdb.MongoClient(...);

let p = d.connect();

d.on('error', e => {
  console.error('mongo client error:',e);
  p = d.connect();  // reconnect here?
});
```

does anyone know why this error arises and how to handle it  - how to prevent it from bubbling up to the global space?

**Comment by ORESoftware** [comment]
bump, this question now has a 50 pt bounty on it.. thanks
https://stackoverflow.com/questions/58176277/how-to-handle-disconnect-error-for-mongodb

**Comment by vkarpov15** [comment]
I posted a response on SO: https://stackoverflow.com/questions/58176277/how-to-handle-disconnect-error-for-mongodb/58308782#58308782 . Hope it helps, that bounty looks nice :) I'm going to close this issue for now because it doesn't seem to be related to Mongoose.
