### ISSUE TITLE
No disconnected event when MongoDB docker container closed v5.7.3

### ISSUE THREAD

**Issue by shaneguayCanopy** [Automattic/mongoose#8212]
This is an interesting issue in that the 'disconnected' event is never triggered when the MongoDB is brought down.  We are running MongoDB through a Docker container and running a local node.js file.

We are using the latest Mongoose version 5.7.3.

When we tried an older version 5.0.12 it works.  We found a similar issue that was described as being fixed in 5.0.12 from this ticket ("error event not triggered #6131") and indeed in 5.0.12 we did properly receive the 'disconnected' event when we closed the MongoDB container.

So it seems this bug has regressed and is back in latest version

`mongoose.connection.on('disconnected', () => {
    console.log('DISCONNECTED!');
});`

**Comment by shaneguayCanopy** [comment]
We've tracked the issue down to the use of the `useUnifiedTopology: true` setting in the connect method.

When we remove this option it works in the latest Mongoose version 5.7.3.

```mongoose.connect(dbConnectionString, {
        useNewUrlParser: true,
        useFindAndModify: false,
        autoReconnect: false,
        autoIndex: false,
        //useUnifiedTopology: true,
        bufferMaxEntries: 0
    }).then```

**Comment by vkarpov15** [comment]
I'm unable to repro this. Below script prints out 'disconnected' in 5.7.3 when I shut down my local mongod instance. We also have test cases for this, and they pass on travis: https://github.com/Automattic/mongoose/blob/cdfb507be166e6f047b2a621403e63d93a58d418/test/connection.test.js#L183-L211.

What docker image are you using? Are you using docker compose? Also, does this issue happen without Docker?

**Comment by xinyangyuan** [comment]
The connection events also not firing when running node locally (mongoose version 5.7.5) and using MongoDB atlas. Simulate connection lost by manual computer internet connection, and none of the following events would fire:

```javascript
mongoose.connection.on('disconnected', function(e) {
  console.log('Disconnected: ' + e);
});
mongoose.connection.on('error', function(e) {
  console.log('Error: ' + e);
});
mongoose.connection.on('timeout', function(e) {
  console.log('Timeout: ' + e);
});
```

ps: not sure manual disconnect internet is the right way to simulate, but also experience connection lost without any error when the nodejs is hosted in ec2.

**Comment by vkarpov15** [comment]
@xinyangyuan the below script fires 'disconnected' correctly for me when I turn off wifi on my macbook, it just takes maybe 30 seconds or so.

```javascript
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

run().catch(error => console.log(error));

async function run() {
  await mongoose.connect('mongodb+srv://USER:PASS@cluster0-OMITTED.mongodb.net/test?retryWrites=true&w=majority', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    autoReconnect: false,
    bufferMaxEntries: 0
  });
mongoose.connection.on('disconnected', function(e) {
  console.log('Disconnected: ' + e);
});
mongoose.connection.on('error', function(e) {
  console.log('Error: ' + e);
});
mongoose.connection.on('timeout', function(e) {
  console.log('Timeout: ' + e);
});

  console.log('Connected');
}
```

Please make sure you give it some time to fire the disconnected event, it won't happen immediately.

**Comment by vkarpov15** [comment]
@igorz24 did you wait for 30 seconds? With `useUnifiedTopology`, you won't get a 'disconnected' error until then.

**Comment by xinyangyuan** [comment]
@vkarpov15 thank you so much, the `disconnected` does trigger for MongoAtlas cluster connection when I close wifi connection for 30 seconds (**mongoose 5.7.8**).

@igorz24 also tried your code with mongo atlas cluster, `disconnected ` was triggered as well, but `reconnected` was not fired after I turn the wifi back on. 

Output:

```
connecting to MongoDB...
MongoDB connected!
MongoDB connection opened!

# after internet disconnected for 30sec
MongoDB disconnected!
``` 

What connection options should I pass to the mongoose, if I want the mongo driver to retry connection? Have tried to change autoRecoonect and reconnectTries, but it does not seem to work:

```javascript
async function run() {
  await mongoose.connect('mongodb+srv://xxx', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    bufferMaxEntries: 0,
    autoReconnect: true,
    reconnectTries: Number.MAX_VALUE
  });
  console.log('Connected');
}
``` 

Thanks!

**Comment by igorz24** [comment]
@vkarpov15 You're right, I forgot to wait.

@xinyangyuan Try setting:
`useUnifiedTopology: false`

It works for me when I do. I think in general it shouldn't be the case, but right now there is a bug with Mongo driver for Node and it seems like it might be connected.
See the issue -> https://github.com/Automattic/mongoose/issues/8180
