### ISSUE TITLE
Timestamp propagation issue...

### ISSUE THREAD

**Issue by chaeron** [Automattic/mongoose#8214]
Latest Mongoose 5.7.3, MongoDB 4.2.

I have a situation with a root schema (eg. Root) with two subdocument schemas (S1 & S2).  All three schemas have timestamps enabled.

The problem is that if the timestamp on the Root model changes it propagates the changes to ALL subdocuments, and changes their embedded timestamps.

Here is the scenario: If you update S1, it's timestamp is modified (as expected) and this causes the Root timestamp to also change. So far so good. But then the Root schema in turn propagates to all children and changes the timestamp of S2, even though the S2 subdocument has NOT changed. From a typical business data model perspective, this doesn't make sense, since S2 did not change, so it's timestamps should have stayed intact.

This caused me to have to ignore the built in Mongoose timestamp handling and implement my own timestamp handling using custom middleware hooks.

Worth noting is that the Ruby/Rails Mongoid ORM which is officially supported by MongoDB does not do this. It acts correctly in the above scenario, leaving S2's timestamps unchanged.

At the least, there should be an option/flag to turn off propagation of timestamps from the parent to all children, to handle situations like the one I ran into without necessitating lots of custom middleware.

**Comment by vkarpov15** [comment]
Can you please provide code samples? I'm not sure I understand the issue.
