### ISSUE TITLE
insertMany always retruns result making it 3-4 slower than `Model.collection.insert`

### ISSUE THREAD

**Issue by ChoppinBlockParty** [Automattic/mongoose#8215]
More details [here](https://stackoverflow.com/questions/58226391/mongoose-vs-pymongo-drivers-write-insertmany-test). The idea that mongoose `insertMany` is slow due to returning all the documents back. In the test above if I replace it with `Model.collection.insert` it is even a little faster than the pymongo `insert_many`.

**Comment by vkarpov15** [comment]
The issue is that Mongoose casts each document in `insertMany()`, so there's some significant overhead to using `insertMany()`. If you want to bypass Mongoose's casting, use `MyModel.collection.insertMany()`
