### ISSUE TITLE
FindOneAndUpdate with upsert return Array if exists, object if new

### ISSUE THREAD

**Issue by BenjErgizerBunny** [Automattic/mongoose#8216]
**Do you want to request a *feature* or report a *bug*?**

Request a feature and understand design 

**What is the current behavior?**

I want to understand why FindOneAndUpdate with {upsert: true, new: true} returns an array when the document exists and an object if the document doesn't exist.  I find this makes it more difficult to handle the result as we need to be able to handle an array or an object with the same code afterwards.  

**What is the expected behavior?**

It would be great if the result could be consistent across both cases.  Returning one of the two types for both cases

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

    "mongoose": "^5.4.5"
node: v8.12.0

**Comment by vkarpov15** [comment]
Can you please add a repro script that demonstrates this behavior? `findOneAndUpdate()` should never give you back an array...
