### ISSUE TITLE
using "ref" & "required" together

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8217]
**Do you want to request a *feature* or report a *bug*?**

question / bug / feature

**What is the current behavior?**

when using `ref`, `required` is ignored

**If the current behavior is a bug, please provide the steps to reproduce.**

(imports are in the style of typescript, for example purposes "chai" are used)
```ts
import * as mongoose from "mongoose"; // mongoose@5.7.3
import { expect, assert } from "chai";

const Schema = mongoose.Schema;

const personSchema = new Schema({
    _id: Schema.Types.ObjectId,
    name: String,
    story: { type: Schema.Types.ObjectId, ref: "Story", required: true }
});

const storySchema = new Schema({
    title: String,
});

const Story = mongoose.model("Story", storySchema);
const Person = mongoose.model("Person", personSchema);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "testMongooseRefs" });

    // expect & assert from chai

    try {
        const person = new Person({ name: "Test" });
        console.log(person);
        assert.fail("Expected to throw ValidationError");
    } catch (err) {
        expect(err).to.be.an.instanceOf(mongoose.Error.ValidationError);
    }
})();
```

**What is the expected behavior?**

that when using `ref` and `required` that it would fail

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 12.10.0
mongo: 4.2-bionic (docker)
typescript: 3.6.3
mongoose: 5.7.3

---

sorry if this has been discussed before, but i couldnt find a directly related issue

*reference: https://github.com/typegoose/typegoose/issues/66*

**Comment by vkarpov15** [comment]
Actually this works as expected. You just aren't calling `validate()`. Mongoose doesn't throw a validation error when you create a new document, only when you call [`validate()`](https://mongoosejs.com/docs/api/document.html#document_Document-validate) or [`validateSync()`](https://mongoosejs.com/docs/api/document.html#document_Document-validateSync).

Here's the corrected script:

```javascript
'use strict';
const mongoose = require('mongoose');
const assert = require('assert');

const Schema = mongoose.Schema;

const personSchema = new Schema({
    _id: Schema.Types.ObjectId,
    name: String,
    story: { type: Schema.Types.ObjectId, ref: "Story", required: true }
});
const storySchema = new Schema({
    title: String,
});
const Story = mongoose.model("Story", storySchema);
const Person = mongoose.model("Person", personSchema);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "testMongooseRefs" });
    const person = new Person({ name: "Test" });
    await person.validate(); // throws
})();
```

**Comment by hasezoey** [comment]
didnt thought of this, sorry
