### ISSUE TITLE
Documentation for the return type of Model functions says <<Query>> but returns <<Model>>

### ISSUE THREAD

**Issue by apolopena** [Automattic/mongoose#8229]
Mongoose Documentation version: 5.7.3

Documentation for Model methods says that they return a Query object:
https://mongoosejs.com/docs/queries.html

The following code (assuming that `MyModel` is an instance of `Model`) shows that the object returned by a  Model method such as `Model.findByID()` is an instance of `Model` not `Query`

Example:
```
const mongoose = require('mongoose);
MyModel.findById(id, (err, doc) => if (!e) {
    console.log(d instance of mongoose.Query); // outputs false
    console.log(d instance of mongoose.Model); // outputs true
};
```
outputs:
```
false
true
```
From reading the documentation I would expect the output of the example to be:
```
true
false
```

Node.js version: 12.4.0
Mongoose version: 5.7.3
MongoDB version 4.2

**Comment by vkarpov15** [comment]
The document passed to the callback is not the same as the value the function returns. `const q = Model.findById()` means `q` is a query, not a model.

**Comment by apolopena** [comment]
Thank you for the clarification.
