### ISSUE TITLE
Sometimes we need to response the request immediately without waiting to update the data.

### ISSUE THREAD

**Issue by Manjiz** [Automattic/mongoose#8231]
**What is the current behavior?**

``` javascript
async test () {
  await this.model('user').findByIdAndUpdate('xxxxxx', {
    nickname: 'Tony2'
  })
  this.success('ok')
}
```

Without `await`, this update would not success.

**What is the expected behavior?**

Sometimes we need to response the request immediately without waiting to update the data.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- NodeJS 12.2.0
- Mongoose 5.7.1

**Comment by MGenteluci** [comment]
So, I see that you don't wanna for the promise. I think this may be a good solution for you:

```
async function updateModel() {
  await this.model('user').findByIdAndUpdate('xxxxxx', {
    nickname: 'Tony2'
  })
}

function test() {
  this.updateModel();
  this.success('ok')
}
```

**Comment by Manjiz** [comment]
@MGenteluci @MartinDrost Thanks for your advise. I also have found a hint in document:

> The operation is only executed when a callback is passed

So, either callback or promise.
