### ISSUE TITLE
MongoTimeoutError when using useUnifiedTopology:true 

### ISSUE THREAD

**Issue by basma-abdin** [Automattic/mongoose#8233]
**Do you want to request a *feature* or report a *bug*?**
 a bug

**If the current behavior is a bug, please provide the steps to reproduce.**

After i use useUnifiedTopology:true in mongoose constructor , i  get MongoTimeoutError error at 
`` at Timeout.setTimeout (/topology.js:850:16)
``
the code: 
![Screenshot from 2019-10-10 12-07-09](https://user-images.githubusercontent.com/26696922/66559934-96217280-eb56-11e9-803b-6181bb602a3a.png)

error:
![73357406_552689032134073_1924292296619065344_n](https://user-images.githubusercontent.com/26696922/66559768-3fb43400-eb56-11e9-9ab3-35c0445c1304.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

i use: 
mongoose version:5.7.4 
node version : 12.10.0

same issue without solution: #8180

**Comment by idanb11** [comment]
@basma-abdin - dealing with the same issue - on production !!!

removing `useUnifiedTopology: true` solved my issue...

bummer.

**Comment by vkarpov15** [comment]
What does your connection string look like? Please omit any sensitive credentials. Also, are you connecting to a standalone server, replica set, sharded cluster, or Atlas?

**Comment by vkarpov15** [comment]
Also, it's safe to unset `useUnifiedTopology` if it is causing issues for you in production. Just be aware that the ability to set that flag to `false` will be removed in Mongoose 6, so we'll hopefully work out all the issues with the MongoDB driver team before then :)

**Comment by mrbonini** [comment]
Hey man, I was having the same problem, but if I removed the useUnifiedTopology I wouldn't be able to connect to the DB anyways. So I tried creating a new Cluster and then when I went to get the connection details something pop up. They asked me to register my IP address. So I got back to the old cluster, the one that I would always get the 30k time out error, and then I Network Access, IP whitlist and added my current IP Address. Afterward the connection to the DB worked.
You should try that :)
