### ISSUE TITLE
Multiple database connections using TypeScript module

### ISSUE THREAD

**Issue by jamie3** [Automattic/mongoose#8236]
I'd like to use the mongoose typescript module to connect to two databases. Example code is below. Looking for examples on how to do this.

```
import mongoose from 'mongoose';

const schema1 = new mongoose.Schema({
});

const schema2 = new mongoose.Schema({
});

export const Model1 = mongoose.model<Document1>('Document1' schema1);   // database1
export const Model2 = mongoose.model<Document2>('Document2' schema2);   // database2
```

**Comment by vkarpov15** [comment]
See [multiple connections docs](https://mongoosejs.com/docs/connections.html#multiple_connections). Shouldn't be any problem using multiple connections with typescript.
