### ISSUE TITLE
schema validation does not work when including a schema from a different file

### ISSUE THREAD

**Issue by RuudVerhoef** [Automattic/mongoose#8240]
Using Mongoose: 5.7.1

The following schema A is being exported:
```
exports.ASchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    validate: {
      validator: (value) => importedValidationFunc(value),
      message: (props) => `${props.value} is not a valid name!`
    }
  }
});
```
This schema is being imported and used in schema B:
```
const BSchema = new mongoose.Schema({
  name: { type: String, required: true },
  instancesOfA: [ASchema],
});

module.exports = mongoose.model('B', BSchema);
```
If I now try to POST a new item of type B only the (custom) validators are fired for the B schema. If I do not abide to the A schema, adding object of type A to the array, Mongoose does not seem to care.

If I put the two schema together in 1 file it does work correctly and validation restrictions in A are enforced.

What is/could be the cause of this?

**Comment by vkarpov15** [comment]
Can you please provide a code sample demonstrating what "If I do not abide to the A schema, adding object of type A to the array, Mongoose does not seem to care." means?
