### ISSUE TITLE
Create index on __t on discriminator

### ISSUE THREAD

**Issue by Enado95** [Automattic/mongoose#8246]
I want to create an index on __t with collation to ignore case but is does not seem to work. Here's my code:

Product.js is my "base" model
```node.js
const mongoose = require('mongoose')

const productSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true
    },
    createBy: String
  },
  { timestamps: { createdAt: 'created', updatedAt: 'updateAt' }, collation: {locale: 'en_US', strength: 1} }
)

productSchema.index({__t: 1})

exports.Product = mongoose.model('products', productSchema, 'products')
```

CreditCard is derived from it: 

```node.js
const options = { discriminatorKey: 'type' }

const creditCardSchema = new mongoose.Schema({
  imageUrl: String,
  imageId: String,
  currency: {type: String, uppercase: true},
  billingCurrency: String,
  type: {type: String, lowercase: true},
  annualFee: Number,
  interestFee: Number,
  minSalReq: Number,
  cashAdvFee: Number,
  latePayFee: Number,
  minPayPcnt: Number,
  overLmtFee: Number,
  rewardsProgram: String
})

exports.CreditCard = Product.discriminator('CreditCard', creditCardSchema, options)
```
Is what I'm trying to do possible? I want the collation on the collection level, don't know if this is still an issue #5295

**Comment by vkarpov15** [comment]
Can you please describe what you mean by "does not seem to work"? How are you determining that the index isn't doing what you want?

**Comment by Enado95** [comment]
Its does not work for me. Even though I added the collation options to the schema, the  collection does not get created. Therefore when I create an Index on __t, by default it its not case insensitive, i have to add the collation to the query. However,  this [case insensitive](https://docs.mongodb.com/manual/core/index-case-insensitive/#case-insensitive-indexes-on-collections-with-a-default-collation) behavior is what i want.

**Comment by vkarpov15** [comment]
The below script works as expected for me with Mongoose 5.7.6: case insensitive search on `__t`. Please modify the below script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');
mongoose.set('debug', true);

const productSchema = new mongoose.Schema(
  {
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      required: false
    },
    createBy: String
  },
  { timestamps: { createdAt: 'created', updatedAt: 'updateAt' }, collation: {locale: 'en_US', strength: 1} }
);

productSchema.index({__t: 1});

const Product = mongoose.model('products', productSchema, 'products');

const options = { discriminatorKey: 'type' };

const creditCardSchema = new mongoose.Schema({
  imageUrl: String,
  imageId: String,
  currency: {type: String, uppercase: true},
  billingCurrency: String,
  type: {type: String, lowercase: true},
  annualFee: Number,
  interestFee: Number,
  minSalReq: Number,
  cashAdvFee: Number,
  latePayFee: Number,
  minPayPcnt: Number,
  overLmtFee: Number,
  rewardsProgram: String
});

const CreditCard = Product.discriminator('CreditCard', creditCardSchema, options);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
  await mongoose.connection.dropDatabase();

  await Product.deleteMany({});
  await CreditCard.create({ rewardsProgram: 'bar' });

  let doc = await Product.findOne({ __t: 'creditcard' });
  console.log(doc);
}
```
```

**Comment by Enado95** [comment]
Your solution works as expected. Thanks for the assistance

**Comment by vkarpov15** [comment]
It doesn't look like you actually have an index on `__t` in the screenshots you showed - perhaps you need to wait for the index to build using [`Model.init()`](https://mongoosejs.com/docs/api/model.html#model_Model.init)?

**Comment by Enado95** [comment]
Added but still the same results.
![image](https://user-images.githubusercontent.com/25810206/67713296-8fd32900-f993-11e9-9fee-5e4ca7a836c9.png)

**Comment by vkarpov15** [comment]
And are you actually using the credit card index after the `init()` promise resolves? It looks like you are just executing `.init()` in parallel without waiting for it to finish.

**Comment by Enado95** [comment]
Can you please provide a code example of the correct code implementation ?

**Comment by vkarpov15** [comment]
```javascript
async function run() {
  await Product.init();
  await CreditCard.init();

  await Product.deleteMany({});
  await CreditCard.create({ rewardsProgram: 'bar' });

  let doc = await Product.findOne({ __t: 'creditcard' });
  console.log(doc);
}
```

**Comment by Enado95** [comment]
No difference:

![image](https://user-images.githubusercontent.com/25810206/68325553-a5cda180-0097-11ea-8280-ec795048f8ac.png)

From the shell:

![image](https://user-images.githubusercontent.com/25810206/68325629-ceee3200-0097-11ea-8dbe-c01aa553f5a2.png)

I mean I know it works. But i want to know that the collation is actually being create on the collection so when I'm querying independent of the application I can utilize it.

**Comment by vkarpov15** [comment]
I see what the problem is. [Mongoose automatically adds the schema collation to the query](https://mongoosejs.com/docs/guide.html#collation). However, if you're querying in compass, you need to make sure you set the collation option:

```javascript
products.findOne({ __t: 'creditcard' }); // Doesn't work, no collation
products.findOne({ __t: 'creditcard' }, { collation: { locale: 'en_US', strength: 1 }, projection: {} }); // works
```

**Comment by Enado95** [comment]
Noted
