### ISSUE TITLE
mongoose.set('useUnifiedTopology', true); where can i use it for make mongoose work

### ISSUE THREAD

**Issue by hibaalaani** [Automattic/mongoose#8248]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Right after you `require('mongoose')` for the first time.

**Comment by hibaalaani** [comment]
Thank you ....

**Comment by pradip2048** [comment]
hello i am using just after require('mongoose') but not worked for me.

const express = require('express');
const bodyParser = require("body-parser");
const mongoose = require("mongoose");
mongoose.set('useUnifiedTopology', true);
