### ISSUE TITLE
strictQuery ignore logical operators

### ISSUE THREAD

**Issue by elainemarleyit** [Automattic/mongoose#8250]
mongo 4.2.0
mongoose 5.7.1
node 10.16.3

If I create my model with option strictQuery set to true when I try to launch find function on my model with logical operators these are ignored.

example:

let schema = new mongoose.Schema({ name: 'string', lastname: 'string'}, {strictQuery: true});
let User = mongoose.model('User', schema);

User.create({name:: "Mario", lastname:"Rossi"});
User.create({name:: "Filippo", lastname:"Rossi"});
User.create({name:: "Luca", lastname:"Bianchi"});
User.create({name:: "Mario", lastname:"Bianchi"});

User.find({name: "Mario"});
// return [{name:: "Mario", surname:"Rossi"}, {name:: "Mario", surname:"Bianchi"}]

User.find({surname: ""})
//return all documents:  surname is not  in User schema and mongoose strip it out  from query => the resultant filter is {}

User.find({"$or": [{name: "Mario"}, {lastname: "Rossi"}]})
//return all documents: mongoose trip out "$or" from filters because is not in schema
//this is a bug 'cause "$or" is not a property is operators and should not be removed from filters. "name" and "lastname"  should be stripped out if not were in schema.

same result if I use "or" function <User.find().or(...)> or others logical operators

**Comment by vkarpov15** [comment]
The below script demonstrates that `$or` isn't removed from filters if `strictQuery` is true. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

const Schema = mongoose.Schema;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
  await mongoose.connection.dropDatabase();

  const schema = Schema({ firstName: String, lastName: String }, { strictQuery: true });
  const Model = mongoose.model('Test', schema);
  
  await Model.create({ firstName: 'foo', lastName: 'bar' });
  
  const docs = await Model.find({ $or: [{ firstName: 'baz' }, { lastName: 'baz', notInSchema: 'foo' }] });
  console.log(docs);
}
```

**Comment by elainemarleyit** [comment]
sorry solved
