### ISSUE TITLE
Mongoose not updating a specific document

### ISSUE THREAD

**Issue by lukaswilkeer** [Automattic/mongoose#8252]
I'm attempt to update a document, using $set (atomic operations), therefore I tested other method there is update the role document (unaware if mongoose uses atomic operations by default)

Turned debug mode to true to see the behaviour and encounter the following error:

`clocks.updateOne({ _id: ObjectId("5d9a398306dbac37c44a920f") }, { '$set': { _id: ObjectId("5d9a398306dbac37c44a920f") } }, { itens: 98 })`

While other operations in that case, $set._id doesn't occur.

My query is simple.

`const update = await model.updateOne({'_id': id}, { 'itens': buyResult })
        .catch(null)`

This result's on locating the document but does not update it (only in this query).
Modifying the catch block the get errors returns nothing.

logging the result returns:

`updateClock { n: 1, nModified: 0, ok: 1 }`

**Comment by vkarpov15** [comment]
What is `model` in your example code? My best guess is that `model` is actually a document in your code and you're calling [`Document#updateOne()`](https://mongoosejs.com/docs/api/document.html#document_Document-updateOne) as opposed to [`Model.updateOne()`](https://mongoosejs.com/docs/api/model.html#model_Model.updateOne)

**Comment by lukaswilkeer** [comment]
I'm calling Model.updateOne instead Document#updateOne. Using the document solved my problem.
