### ISSUE TITLE
Connection useDb not working after database has switched

### ISSUE THREAD

**Issue by sevensand** [Automattic/mongoose#8254]
**Do you want to request a *feature* or report a *bug*?**
bug or feature

**What is the current behavior?**
I have 2 connection, Connection1 is for server  and the Connection2 is for Client.

theres two db in this connection 2,
the Connection2 is not switched to db2, it always fallback in first connection called db1. 
this is same model, same schemas but different data

**If the current behavior is a bug, please provide the steps to reproduce.**

and here is my code.
```
const conn1 = mongoose.createConnection(url, { useCreateIndex: true, useNewUrlParser: true , useFindAndModify: false }, function(err, db) {
    if(err) {
      console.log(err)
    } else {
      console.log("connected to Database");
    }
});
var connections = {};
function getDatabase(dbName){
  if(connections[dbName]){
    return connections[dbName]
  }else {
    connections[dbName] = conn1.useDb(dbName)
    return connections[dbName]
  }
}
module.exports = company: getDatabase()
```

```
const connection = require('../connection');
const UserSchema = mongoose.Schema({
    Name: {
        type: String,
        required: true
    },
})
module.exports = {
    User: connection.company.model(“user”, UserSchema)
}
```

When I cache the result inside this function getDabase the database name was change .

**What is the expected behavior?**
connection2 can switched either db1 or db2.

the model is always used the connection2 db1, thats why there's no effect on the model when i switched?? 

Can you help me to figure out why?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

"mongoose": "^5.5.13",

**Comment by vkarpov15** [comment]
Where are you actually calling `getDatabase()`? What file are you actually importing when you do `const connection = require('../connection');`?

Also, `module.exports = company: getDatabase()` is not syntactically valid JS. What are you trying to do there?

**Comment by sevensand** [comment]
Hi @vkarpov15 , thanks for your response

i'm calling my  getDatabase() in my route,
example of my route index.js.

`const express = require('express');
const config = require('./connection.js');
const app = express();

app.get('/*', function(req, res){
var result = req.headers.cookie;
config.getDatabase(result.databasename)
});
`
if the route is `/company1` the database would be company1db,
and if the route is `/company2` the database will switched to company2db


and here is my connection.js
this is the file that i import in my model
`const connection = require('./connection.js');`

`
const conn1 = mongoose.createConnection(url, { useCreateIndex: true, useNewUrlParser: true , useFindAndModify: false }, function(err, db) {
    if(err) {
      console.log(err)
    } else {
      console.log("connected to Database");
    }
});
var connections = {};
function getDatabase(dbName){
  if(connections[dbName]){
    return connections[dbName]
  }else {
    connections[dbName] = conn1.useDb(dbName)
    return connections[dbName]
  }
}
const conn2 = getDatabase();

module.exports = {
company: conn2,
server: conn1,
getDatabase
}
`

actually it's multiple object that i want to export.

**Comment by vkarpov15** [comment]
Why are you not doing `const conn2 = getDatabase('company2db')` ?
