### ISSUE TITLE
Meteor.userId can only be invoked in method calls or publications

### ISSUE THREAD

**Issue by Navyroot** [Automattic/mongoose#8257]
I try to use Meteor.userId() in hook of mongoose.
```js
Schema.pre('save', async function () {
  if (this.isNew) {
    let userId = await Meteor.userId()
    console.log('Meteor UserId', userId);
  }
}); 
```
But I get error when `save`

**Comment by vkarpov15** [comment]
What error do you get and what is Meteor.userId() ?

**Comment by Navyroot** [comment]
Error : `Meteor.userId can only be invoked in method calls or publications`

**Comment by vkarpov15** [comment]
@Navyroot that sounds like an issue with this meteor package, I don't see any indication this is an issue with Mongoose.
