### ISSUE TITLE
[bug] Transform functions are applied to nested documents

### ISSUE THREAD

**Issue by tarantoj** [Automattic/mongoose#8260]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Applying a transform to a document using `toObject()` or `toJSON()` methods is applied to subdocuments, conflicting with [online documentation](https://mongoosejs.com/docs/api.html#document_Document-toObject).

> Transforms are applied _only to the document and are not applied to sub-documents._

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a document with a subdocument, call `toObject()` or `toJSON()` with a `transform` function.
[Test script](https://gist.github.com/tarantoj/68a1df93955026d34d524e182cee088a)

**What is the expected behavior?**
Transform to only be applied to the root document

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v12.12.0
Mongoose: 5.7.1
MongoDB: N/A

**Comment by vkarpov15** [comment]
I think this behavior is intentional and the docs are misleading. The docs refer to transforms defined in the schema, like `schema.options.toObject.transform`. But if you pass a transform when calling `toObject()`, it applies to all documents, because otherwise the transform wouldn't be terribly useful.

Is this behavior causing you an issue?

**Comment by tarantoj** [comment]
Yeah, caused some problems when trying to use an inline transform function to remove sensitive data on an endpoint depending on the requested item and logged in user.

If recursive application of the transform function is intended behaviour, I'd agree with you that the docs could require some clarification, especially as I'm [not the only one](https://alexanderzeitler.com/articles/mongoose-tojson-toobject-transform-with-subdocuments/) to find this one out the hard way.
