### ISSUE TITLE
returnNewDocument is not working with Mongoose

### ISSUE THREAD

**Issue by shruti8597** [Automattic/mongoose#8261]
Mongo DB findOneAndUpdate returns updated document when returnNewDocument is set to true.

[Mongo Db Documentation](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/)

But this field doesn't work with mongoose but "new" does.

Mongoose Version - 5.5.1

**Comment by FernanddoSalas** [comment]
**returnNewDocument** option don't work because it's for mongodb driver

This opcion has been implemented in mongoose as **new** one

You can check it in the [Mongoose Documentation](https://mongoosejs.com/docs/api/model.html#model_Model.findByIdAndUpdate)

**Comment by vkarpov15** [comment]
`new` and `returnOriginal` are the options we support that do something similar. `returnNewDocument` isn't supported by the MongoDB Node driver or Mongoose. Just use `new: true`.
