### ISSUE TITLE
Make value casting in .find() queries less strict

### ISSUE THREAD

**Issue by MartinDrost** [Automattic/mongoose#8264]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently Mongoose strictly casts values given to queries to the types defined in the Model's Schema. This is great in most cases when you want to create or update an object or if you want to search for documents using clear variables but it restrains dynamic solutions.

I'm writing a generic solution to write find queries in my application and I'm bumping into the issue where Mongoose is throwing errors because I'm searching f.e. Number attributes with String values while this is perfectly possible within MongoDB itself.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
const mongoose = require("mongoose");

mongoose.connect("mongodb://localhost:32768/population");

/**
 * Define the user schema
 */
const userSchema = new mongoose.Schema({
  name: { type: String },
  age: { type: Number }
});

const userModel = mongoose.model("User", userSchema);
/**
 * Play out the scenario
 */
async function scenario() {
  userModel.create({ name: "John", age: 21 });
  try {
    await userModel.find({ age: "New York" });
  } catch (err) {
    console.log(err.message);
    // out: Cast to number failed for value "New York" at path "age" for model "User"
  }
}

scenario();

```

**What is the expected behavior?**
I expect .find() queries to accept my given search parameters and instead of throwing an error, to see that a String is not equal to a Number and move on to the next condition. This addition could be defined using a field in the options param like `.find({}, {}, { strictCasting: false })` to keep solutions expecting this behaviour intact.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v12.10.0
MongoDB: v4.2.0
Mongoose: v5.7.3

**Comment by vkarpov15** [comment]
In this case, you should just use `userModel.collection.find({ age: 'New York' })`. That skips all Mongoose casting for queries.

**Comment by vkarpov15** [comment]
Hmm so if all you want to do is bypass query casting but then get a full Mongoose document, you can use [`Model.hydrate()`](https://mongoosejs.com/docs/api/model.html#model_Model.hydrate)

```javascript
let users = await userModel.collection.find({ age: 'New York' });
users = users.map(u => userModel.hydrate(u));
```

**Comment by pepkin88** [comment]
> In this case, you should just use `userModel.collection.find({ age: 'New York' })`. That skips all Mongoose casting for queries.

Thanks, I'll use it!
My case was that Mongoose was silently transforming my query `{textField: {$nin: ['', null]}}` to `{textField: {$nin: ['', '']}}` and for a long time I wasn't aware of it.

(Why such query? Well, this "textField" was added later and in new documents was defaulting to `''`, but there was no need to apply this change to old documents, because the app could deal with missing fields.
And `{textField: {$ne: '', $exists: true}}` query had poor performance, didn't use indexes well.)
