### ISSUE TITLE
connection.UseDb not adopting connect options

### ISSUE THREAD

**Issue by sethgoodluck** [Automattic/mongoose#8267]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When switching databases, the connect options are not adopted nor can we write them

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new mongoose connection via `mongoose.connect(<uri>, { <options> })`
2. Create a model that uses a different database 
3. Call `mongoose.connection.useDb('NewDB') 

Outcome: `(node:12285) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

**What is the expected behavior?**
That the useDb method would adopt the options from the original connect object. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
	`"mongoose": "^5.7.5",`

**Comment by vkarpov15** [comment]
The below script doesn't print any deprecation warning. Please modify the below script to demonstrate your issue:

```javascript
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true
  });

  const schema = new mongoose.Schema({ name: String });
  schema.index({ name: 1 });
  const Model = mongoose.model('Test', schema);

  mongoose.connection.useDb('test3');

  await Model.init();
}
```

**Comment by hillct** [comment]
It's arguably worth making use of createIndex the default, rather than a constructor option, in any mongoose release that list as a dependency, a mongo driver version that displays the deprecation warning

**Comment by lucassimibueno** [comment]
I'm having the same behavior described here. Should I open another issue? The following script (based on @vkarpov15 previous one) reproduce the problem:

```javascript
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true
  });

  console.log(mongoose.connection.config);

  const schema = new mongoose.Schema({ name: String });
  schema.index({ name: 1 });

  let newDb = mongoose.connection.useDb('test3');
  console.log(newDb.config);
  newDb.set('useCreateIndex', true);
  console.log(newDb.config);

  const Model = newDb.model('Test', schema);
  await Model.init();
}
```

Basically the problem is to use the newDb returned by useDb method to create the model. With the console.log it is possible to see that config property is not equal to mongoose.connection.config. Also even after using the newDb.set it seems to not work.
I'm using mongoose 5.9.10. 

A possible workaround is to set the newDb.config directly. For example, after last console.log add the following:

```javascript
newDb.config.useCreateIndex = true;
console.log(newDb.config);
```

In this case the '(node:12285) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead' will not appear.

**Comment by tukusejssirs** [comment]
I am a MongoDB and Mongoose newbie and experienced this issue. I have found these Mongoose [Deprecation Warnings](https://mongoosejs.com/docs/deprecations.html) very useful.

**Comment by tukusejssirs** [comment]
Anyway, #8885 does not work for me with MongoDB 3.6.5 and Mongoose 5.12.3.

I use the following Mongoose config on the initial connection:

```js
useCreateIndex: true,
useFindAndModify: false,
useNewUrlParser: true,
useUnifiedTopology: true
```

However, the following outputs different config:

```js
const newDb = await mongoose.connection.useDb('newDb')
console.log('config : ', newDb.config)

// Output
config :  { autoIndex: true }
```
```

**Comment by IslandRhythms** [comment]
```
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true
  });

  console.log(mongoose.connection.config);

  const schema = new mongoose.Schema({ name: String });
  schema.index({ name: 1 });

  let newDb = mongoose.connection.useDb('test3');
  console.log(newDb.config);
  newDb.set('useCreateIndex', true);
  console.log(newDb.config);

  const Model = newDb.model('Test', schema);
  await Model.init();
}
```
