### ISSUE TITLE
Multiple connections with models located in separate files

### ISSUE THREAD

**Issue by weblogics** [Automattic/mongoose#8275]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

When initialising more than one connection (different hosts / servers) its impossible to separate models from the initial app. I have tried to implement `useDb()`, but this seems to be for the same connection with different DB's hosted on this.

I have also tried to implement `mongoose.connections[index].model('ModelName', Schema)`, this doesn't work if the connection hasn't been run yet (Please note: I'm using `mongoose.createConnection()`). Using TypeScript imports need to be the first thing in the file and therefore there's no way to create these connections prior to loading the models.

There really needs to be a better way to separate models from connections. Is there nothing that can be done to use a connection such as a `useConnection` function? The current implementation is unreliable and it's hard to work with.

Has anyone else managed to solve this issue? 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

MongoDB: 4.0.3
Node: v11.12.0
Mongoose: 5.7.5

**Comment by vkarpov15** [comment]
useConnection is an interesting idea, but we aren't likely to support it because it encourages changing the connection when using the model.

The right design pattern here is to export a schema, not a model. Then have a separate file that exports a function which registers models on a connection.

```
import fooSchema from './fooSchema';

export default function(conn) {
  conn.model('Foo', fooSchema);
}
```

**Comment by lauti7** [comment]
@vkarpov15 I am having same issue and in the docs, i saw that i have to create exported function but where i am supposed to run this function?

**Comment by vkarpov15** [comment]
@lauti7 there's a couple possibilities. First is to have separate connection files:

```javascript
// conn1.js
const config = require('./config');
const mongoose = require('mongoose');

const db = mongoose.createConnection(config.mongodbUri);
require('./decorateModels')(db);

module.exports = db;

// conn2.js
const config = require('./config');
const mongoose = require('mongoose');

const db = mongoose.createConnection(config.mongodbUri);
require('./decorateModels')(db);

module.exports = db;
```

Where `decorateModels()` is a function that attaches models to a connection.

Another alternative is to use a DI framework or some other IOC pattern. These days I just use [ramda's `applySpec()` for IOC](https://thecodebarbarian.com/using-ramda-as-a-dependency-injector).

**Comment by vkarpov15** [comment]
Will close this in favor of #8679
