### ISSUE TITLE
由于同时在连接选项中添加【useUnifiedTopology: true】拓扑与引用【excel-export】模块引发事件内存泄漏

### ISSUE THREAD

**Issue by hcdast** [Automattic/mongoose#8276]
mongoose版本：5.7.6
**Do you want to request a *feature* or report a *bug*?**
在连接选项中添加【useUnifiedTopology: true】后，在引用【excel-export】模块后，启动服务会报错
![image](https://user-images.githubusercontent.com/31917435/67448825-cf73db00-f64a-11e9-8382-acc04537dfff.png)
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by hcdast** [comment]
可能这块提到的有关https://jira.mongodb.org/browse/NODE-2123

**Comment by vkarpov15** [comment]
excel-export doesn't depend on mongodb or mongoose, so this shouldn't have anything to do with excel-export in particular. It looks like the issue you mentioned, https://jira.mongodb.org/browse/NODE-2123, will be fixed in mongodb@3.3.4, so once that is released we will upgrade.

**Comment by vkarpov15** [comment]
Should be closed by #8337
