### ISSUE TITLE
Is it possible to create and load async returned data in mongoose Schema?

### ISSUE THREAD

**Issue by debo024** [Automattic/mongoose#8278]
I am able to load data from node project to mongodb cluster when the data is coming from a simple function. Just like the previous state the data coming from an async function I am able to load in console.log but when it is being set by the set() function in the dataSchema the async returned data is not being created in the mongodb databaseor dataSchema.
So is there any other way to load a data which is being returned from an async function can be loaded in mongodb server? Does mongoose library supports async returned data loading to the servers?

**Comment by vkarpov15** [comment]
Please open a new issue and follow the issue template. This question is way too vague for me to provide a meaningful answer
