### ISSUE TITLE
Reference by other field instead of _id

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#8282]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
the use of "ref" prop in schemaType definition is very usefull, but what if we need to reference documents by other field? in my case I've a type model for a user model, but I need to be able to change the name field of type (users like to change the names), so the name can't be the _id because if I change it, a new document is created, besides that I need to be able to define a default prop for the type, if the field to be referenced is _id with the ObjectId type, it's imposible, I must change it hardcoded... 

But what I can do is to explicitly define de default by name prop, so I ain't have to change my code. I can't populate to a certain field, it's defined to match _id, it can't be changed.

It maybe can be done with a virtual, but it'll be very hard to implement for others, you'll have to define 2 fields, one to define the value of the field to match (with a default) and a virtual to define the population with the value defined before.
 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Be able to define a new prop like refField or whatever you like, to define the population match.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 12.13
mongoose: 5.7.7

**Comment by vkarpov15** [comment]
This sounds like exactly what [populate virtuals](https://mongoosejs.com/docs/populate.html#populate-virtuals) are for. Can you please clarify with code samples what you mean by "It maybe can be done with a virtual, but it'll be very hard to implement for others"?

**Comment by chumager** [comment]
Maybe I'm too enclosed to my project... where the "ref" attr let me choose for the reference, in the front end. 
In the normal case you'd need 2 fields to accomplish that, one to save the reference and a virtual to populate the reference with the match defined.

Besides that I thought I'd be easier, because it's more natural in the way you define de population functionality and it's not like the refPath in the way you just need to change the field to match, rather than be dynamic for each document.

I think it'll be a goo feature, for me virtual population is for complex references, with filters, projections, limits, etc... this feature will be good just for change the prop to match. The population functionality doesn't allow to change the ref.

If you think this is not necessary I can rebuild my libraries, just close this issue.

Best Regards.

**Comment by vkarpov15** [comment]
You can always set `model` on `populate()` and that will overwrite what was defined in the schema's `ref`. Doesn't matter whether you're using virtual populate or conventional populate, so you can always choose the reference on the frontend if you want.

```javascript
Model.find().populate({ path: 'myVirtual', model: 'otherRef' });
```

**Comment by smohammadhn** [comment]
2024 - Mongoose version 8

suppose you have two schemas:

```
const playlistSchema = new mongoose.Schema({
  externalId: String,
  title: String,
  videos: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Video',
  }],
});

const videoSchema = new mongoose.Schema({
  externalId: String,
  title: String,
});
```
And you want to populate the `videos` field from the playlistSchema based on `externalId` field from videoSchema:

There is a simple way to achieve this:
```
  PlaylistModel.find()
    .populate({
      path: 'videos',
      model: 'Video',
      select: 'title',
      foreignField: 'externalId',
    })
```

- path: specifies the field in the Announcement schema that you want to populate.
- model: specifies the model to use for population.
- select: specifies the fields to select from the referenced document.
- foreignField: specifies the field in the referenced model (Video in this case) that is used to match with the local field (videos in playlistSchema) for populating references. (**instead of the default _id**)

**Comment by chumager** [comment]
Hi, that sounds great, in my case, I made a endpoint wrapper for my needs so I use the refField attribute to tell the wrapper for what field to ask.

Best Regards.

**Comment by Greta-Calamari** [comment]
> 2024 - Mongoose version 8
> 
> suppose you have two schemas:
> 
> ```
> const playlistSchema = new mongoose.Schema({
>   externalId: String,
>   title: String,
>   videos: [{
>     type: mongoose.Schema.Types.ObjectId,
>     ref: 'Video',
>   }],
> });
> 
> const videoSchema = new mongoose.Schema({
>   externalId: String,
>   title: String,
> });
> ```
> 
> And you want to populate the `videos` field from the playlistSchema based on `externalId` field from videoSchema:
> 
> There is a simple way to achieve this:
> 
> ```
>   PlaylistModel.find()
>     .populate({
>       path: 'videos',
>       model: 'Video',
>       select: 'title',
>       foreignField: 'externalId',
>     })
> ```
> 
> * path: specifies the field in the Announcement schema that you want to populate.
> * model: specifies the model to use for population.
> * select: specifies the fields to select from the referenced document.
> * foreignField: specifies the field in the referenced model (Video in this case) that is used to match with the local field (videos in playlistSchema) for populating references. (**instead of the default _id**)




VERY GOOD ANSWER , it resolved my problem thank you
