### ISSUE TITLE
newurlparser issue

### ISSUE THREAD

**Issue by deepakdevrhwal** [Automattic/mongoose#8283]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

i used
 mongoose.connect("mongodb://localhost/cat_app", { useNewUrlParser: true });
and it still show the error
(node:10348) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
how can i correct it please tell

**Comment by chasegolem** [comment]
that error is for `useUnifiedTopology`, not `useNewUrlParser`. Try adding this line under the mongoose requirement: `mongoose.set("useUnifiedTopology", true)`.

**Comment by vkarpov15** [comment]
@chasegolem that's correct. Also see deprecation warnings guide here: https://mongoosejs.com/docs/deprecations.html#useunifiedtopology
