### ISSUE TITLE
Hiding Virtuals

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8284]
**Do you want to request a *feature* or report a *bug*?**

new feature / question

**Describe what you want**

It would be helpful if there is an option for virtuals to hide them from `enumeration` / from the output in `toJSON` / `toObject` (for plugin use)
-> setting `Object.defineProperty`'s `enumerable` to `false`

like
```ts
// TypeScript syntax
import { Schema, model as createModel } from "mongoose";

const sch = new Schema({});
sch.virtual("hidden", { hide: true }).get(() => "hello");
sch.set('toJSON', { getters: true, virtuals: true });
sch.set('toObject', { getters: true, virtuals: true });

const model = createModel("SomeModel", sch);
const doc = new model({});
console.log(doc); // expected "{ _id: someLongID, id: someLongID }"
console.log(doc.hidden); // to still work and return "hello"
```

it would be useful for something like in typegoose to not pollute user's output when virtuals are enabled
https://github.com/typegoose/typegoose/pull/97/files#diff-47432c0fca2331f971956d7674048e26R96-R100

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.7.7
node: 12.13.0
mongodb: 4.2-bionic (docker)

**Comment by vkarpov15** [comment]
Hmm if you want to remove virtuals from the `toObject()` output, why not just remove the `sch.set('toObject', { virtuals: true })` line? Setting `toObject.virtuals` to `true` is how you [opt in to including virtuals in `toObject()` output](https://mongoosejs.com/docs/api/document.html#document_Document-toObject), so all you need to do is remove that and your script will still work...

**Comment by hasezoey** [comment]
> why not just remove the sch.set('toObject', { virtuals: true }) line?

i meant the use of some plugin-like thing where the "plugin" adds an virtual, example: `typegooseClassName`, that should be accessible in an document, but like an normal property, and not like an function - that should not persists in the user's output

example use case (in the meaning of typegoose)
```ts
const someSchema = new mongoose.Schema({ firstName: String, lastName: String });

// Somewhere in typegoose's factory function
someSchema.virtual('typegooseClassName', { hide: true ).get(() => { // this is used to find the corresponding class for the resulting model
  return className; // "className" is a variable in the factory function
});
// end factory function

someSchema.virtual('fullName').get(function () {
  return this.firstName + " " + this.lastName;
});

sch.set('toJSON', { getters: true, virtuals: true }); // user wants virtuals in the output, but probably not "internal" class names

const someModel = mongoose.model('Some', someSchema);

const doc = new someModel({ firstName: "Will", lastName: "Smith" });
console.log(doc.toJSON()); // should not include "typegooseClassName", but "fullName"

// Sorry if there is an small type in here, i wrote this without using an editor
```

you might ask, why use an virtual for it: because to not call an function AND to have it available in nestedPaths

**Comment by vkarpov15** [comment]
The `hide: true` idea sounds convoluted. `options.toJSON.virtual = true` means include virtuals in `toJSON()` other than virtuals that have `hide: true`, but then we'll likely need another option to include hidden virtuals in `toJSON()` output... sounds a bit backwards. Especially since the whole point of virtuals is that they show up in `toJSON()` and `toObject()` - if you never want your virtual to show up in `toJSON()`, you might as well just use a method because the only thing that using a virtual gives you is saving typing out `()`.

Why not just `someSchema.methods.typegooseClassName = () => className` ?

**Comment by vkarpov15** [comment]
Woops, missed the last part of your comment. What does "to have it available in nestedPaths" mean?

**Comment by hasezoey** [comment]
> What does "to have it available in nestedPaths" mean?

sorry, forgot that methods are available in nested paths too, forget that

---

my main reason was `because to not call an function`, but when "idea sounds convoluted" a method sounds ok - you can see this feature-request as solved

**Comment by hasezoey** [comment]
i will close this because of no answer that @vkarpov15 wants to keep this open
