### ISSUE TITLE
Typescript: error when overriding checkRequired

### ISSUE THREAD

**Issue by lcswillems** [Automattic/mongoose#8286]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In my TypeScript project, this code:

```
mongoose.Schema.Types.String.checkRequired(v => v != null);
```
gives me this error:

```
Property 'checkRequired' does not exist on type 'typeof String'.
```

I use the last version of `@types/mongoose`, i.e. version 5.5.23.

**Comment by hasezoey** [comment]
This seems like an Typescript-Type Error, @types/mongoose is not officially supported, please open a new issue at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/

-> for more information look at https://github.com/Automattic/mongoose/issues/8108
