### ISSUE TITLE
A couple of gigabytes in a single transaction 

### ISSUE THREAD

**Issue by rostislavprovodenko** [Automattic/mongoose#8294]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am using latest mongo (4.2.1) and latest mongoose (5.7.6).
When attempting to insertMany or save a number of documents, with a total transaction size of over 3 GB I consistently get the following error:
```
{ MongoError: Transaction 2 has been aborted.
    at Connection.<anonymous> (/Users/rostislavprovodenko/repos/wla-soup2/backend/node_modules/mongodb/lib/core/connection/pool.js:454:61)
    at Connection.emit (events.js:182:13)
    at processMessage (/Users/rostislavprovodenko/repos/wla-soup2/backend/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at Socket.<anonymous> (/Users/rostislavprovodenko/repos/wla-soup2/backend/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
  errorLabels: [ 'TransientTransactionError' ],
  operationTime:
   Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1572452742 },
  ok: 0,
  errmsg: 'Transaction 2 has been aborted.',
  code: 251,
  codeName: 'NoSuchTransaction',
  '$clusterTime':
   { clusterTime:
      Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1572452742 },
     signature:
      { hash:
         Binary {
           _bsontype: 'Binary',
           sub_type: 0,
           position: 20,
           buffer:
            <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00> },
        keyId: 0 } },
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }

```
There is no issue with inserting a lesser amount of data.

**If the current behavior is a bug, please provide the steps to reproduce.**

    const db = await getMongooseDbConnection();
    await createCollections();
    const session = await db.startSession();
    await session.withTransaction(async () => {
    ...
    for (const curveFileName of curveFileNames) {
        const curve = await readFileAndConvertToJson(curvesFolder, curveFileName);
        // the error is raised here after successfully saving multiple files, skipping the file causes an exception to occur on the next file
        // so the issue is not with a particular file, but it seems to be with the total size of the transaction
        await (new CurvesModel({ ...curve, oilFieldId })).save({ session });
    }
}
**What is the expected behavior?**

The transaction should be successfully committed.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 11.4.0
Mongodb: 4.2.1
Mongoose: 5.7.6

**Comment by vkarpov15** [comment]
My best guess is that you're running into the [transaction time limit](https://docs.mongodb.com/manual/reference/parameters/#param.transactionLifetimeLimitSeconds). By default, MongoDB times out transactions after 60 seconds. This option is set on your MongoDB server, unfortunately you can't set it on an individual transaction.
