### ISSUE TITLE
CrosswordSolver on mongoosejs.com

### ISSUE THREAD

**Issue by emraeshine3** [Automattic/mongoose#8301]
Hi there,

I hope you had a wonderful weekend! My name is Emily with CrosswordSolver.com, a sponsor of mongoosejs.com.

We were hoping to get our logo & link added to your website. Is this possible? If so, would you need our logo?

Let me know and thank you very much for your help!

Smiles,
Emily

**Comment by vkarpov15** [comment]
Hi,

Your logo should be up now:

![image](https://user-images.githubusercontent.com/1620265/68325787-1d033580-0098-11ea-8cc8-8a4bceea042b.png)

Do you prefer a different logo or link? If so, please let me know!

Thanks,
Valeri

**Comment by emraeshine3** [comment]
Thank you so much, Valeri! Is it possible to switch the logo to the  
one attached?

We appreciate it!

Smiles,
Emily


Quoting Valeri Karpov <notifications@github.com>:

**Comment by emraeshine3** [comment]
Don't think the logo attached went sent via email. Here it is. Thank you so much!
![en_dark-500px](https://user-images.githubusercontent.com/56983804/68332852-6e65f180-00a5-11ea-8e20-48741f16c5ea.png)

**Comment by vkarpov15** [comment]
I added the logo. However I'm going to have to make the logo 80px high instead of 100px - our home page layout is only 600px wide so that logo will spill over if it is 100px.
