### ISSUE TITLE
Is it possible to remove default empty connection from `mongoose.connections`?

### ISSUE THREAD

**Issue by NenadJovicic** [Automattic/mongoose#8302]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
When mongoose is imported in some file, it will automatically call constructor of mongoose, where [we have call](https://github.com/Automattic/mongoose/blob/8c79cdde23b27b3d91326cdee92b775038980ca9/lib/index.js#L69) of `createConnection()` method, without any uri. 

That means that `mongoose.connections[0]` is a bit useless. So, when I use `.createConnection(someUri, options)` to have real connection to db and my connection will be on 2nd place in an array of connections. Problem here is that `mongoose.model()` won't be able to properly instance model, because it will watch default connection, which is equal to `mongoose.connections[0]`

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose');

(() => {
  console.log('Number of connections is', mongoose.connections.length); // will print that there is one connection
})();
```

**What is the expected behavior?**

Expecting that this default connection disappear from list of connections when real connection is provided and to override `mongoose.connection` with first connection from list

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 12.13.0
mongoose 5.7.7
mongoDB 3.6.2

**Comment by vkarpov15** [comment]
It should be safe, but the better question is, why do you need to do this? If you want to use `mongoose.model()`, we assume you're using `mongoose.connect()`. If you want to use a connection other than the default connection, you can just use [`Connection#model()`](https://mongoosejs.com/docs/api/connection.html#connection_Connection-model). So if you only want to use 1 connection, why do you need `createConnection()`?

**Comment by NenadJovicic** [comment]
@vkarpov15 well, i am using [nestjs framework]( https://nestjs.com/), which got its own module to connect to db, where I only provide params for connection
And now, I want to apply some plugin globally to mongoose, which use default `mongoose.connection`
Nestjs use in the background `createConnection` method, which means proper connection is the 2nd one in `mongoose.connections`, and `mongoose.connection` that plugin use is not proper one
So, I had to do a lot of hacking to make it work.

This is the main reason why I asked this question

Other reason was that, if I instance model differently from suggested way by framework, and I do `mongoose.model()`, it won't initialize model for proper db

https://github.com/nestjs/mongoose/issues/109
https://github.com/nestjs/mongoose/issues/27
some of the issues opened to this framework just because they changed from `mongoose.connect` to `mongoose.createConnection` and some plugins are not working

**Comment by vkarpov15** [comment]
So then why not use `mongoose.connections[0].model()`, or, better yet, `const conn = mongoose.connections[0]; conn.model();`?

**Comment by syned13** [comment]
> So then why not use `mongoose.connections[0].model()`, or, better yet, `const conn = mongoose.connections[0]; conn.model();`?

Doing so does not work because the first connection is an empty connection. The following error is thrown: 

```Schema hasn't been registered for model \"{MODEL_NAME}\".\nUse mongoose.model(name, schema)```

It might be the case where the schema is not present(let's say, something dynamic where that schema could be anything).

I'm building a plugin where that's the case.

@vkarpov15

**Comment by vkarpov15** [comment]
@syned13 I don't understand the issue. What do you mean by "the first connection is an empty connection"?

**Comment by vkarpov15** [comment]
Should be possible now with `createInitialConnection` option, just need a way to set that

**Comment by vkarpov15** [comment]
With #14679, `mongoose.set('createInitialConnection', false)` will also remove the existing default connection, as long as that default connection hasn't been used yet.
