### ISSUE TITLE
Cannot increment with non-numeric with mongoose

### ISSUE THREAD

**Issue by ThomasPerche** [Automattic/mongoose#8303]
**Do you want to request a *feature* or report a *bug*?**
I would like to report a bug

**What is the current behavior?**
I can't incremente a field number using a integer with mongoose

**If the current behavior is a bug, please provide the steps to reproduce.**
I have the latest version of Mongoose 5.7.8 and a system of vote where I count the vote thumbs up and the vote thumbs down. During the vote thumbs down, I'm creating an object using in parameter to a function which will rather incremente the thumbs up count or thumbs down count in the MongoDB. The object is like this : 
{ _id : id of the word
   vote : "down" or"up"}

and then I'm in this function : 

`        if(voteObj.vote=="down")
            { 
                Word.update({ _id: voteObj._id }, { $inc: { VoteAgainst: 1 } }, {new: true}, function (err, response) {
                    if (err) {
                        logger.error("[DATABASE] " + err);
                    } else {
                        logger.info("[SCRIPT] VoteAgainst incremented, idWord : " + voteObj._id);
                    }
                });
            }
`
**What is the expected behavior?**
The expected behavior is that $inc incremente my count but it shows this error : 

>  MongoError: Cannot increment with non-numeric argument: {VoteAgainst: \"1\"}","level":"error"}

I'm surprised because this method works in Robo 3T Mongo, and the field is properly a number. Do I miss something ? 

![image](https://user-images.githubusercontent.com/11762003/68417617-042d7980-0197-11ea-8301-454df460cbe1.png)

As you can see on the img above, I give to the mongoose method an integer but the output here shows that my integer is transformed into a string

![image](https://user-images.githubusercontent.com/11762003/68417672-1dcec100-0197-11ea-97dd-e0ecf25dab59.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS : v10.15.3
Mongoose : 5.7.8
MongoDB : I don't know, I use MLAB

**Comment by Niiitzer** [comment]
up

**Comment by ThomasPerche** [comment]
EDIT : It was my schema where I've defined my variable as a String

**Comment by Niiitzer** [comment]
DOWN
