### ISSUE TITLE
timestamps doesn't work with $addToSet on embedded document

### ISSUE THREAD

**Issue by devop911** [Automattic/mongoose#8305]
If Iam using findByIdAndUpdate to add an embedded document on a resource with $addToSet, the timestamps option on the model, doesn't have any effect, so created and updated at won't be applied.
If I use $push it will work.

I am asking my self if this is a bug, i could understand, if this is not possible with $addToSet, because the objects would differ with the timestamps.

**Comment by vkarpov15** [comment]
Please follow the issue template and provide code samples. Converting prose to code is error prone.
