### ISSUE TITLE
How to create Leaderboard in mongodb

### ISSUE THREAD

**Issue by zack1991** [Automattic/mongoose#8313]
Hi,

This question is out of mongoose context, but i did not find where to ask this question, if you have any idea so please suggest me.

Currently i have 1 million data of Players in mongodb  that has coins field, i want to create Leaderboard on that field. 
To achieve this i tried to sort the data on coins by descending order and get the sorted data, sorting the data is very expansive its taking 12-15 seconds to return the result, if each player will call leaderboard service then it will make much load on database. so please help me there is any other method to create the Leaderboard.

**Comment by Yonodactyl** [comment]
I should preface with the fact that I don't use Mongoose often.

Why don't you try to request the data in chunks? Have you looked into requesting with a limit and offset?

**Comment by simllll** [comment]
You could generate another collection with an index on the cummulated score and run a cron job that builds the table every e.g. 10 minutes?

Regards

**Comment by vkarpov15** [comment]
The easiest way is to [build an index on `Player.coins`](https://mongoosejs.com/docs/guide.html#indexes): `playerSchema.index({ coins: -1 })` - the `-1` is for descending order. That should make your sort faster and minimize the amount of work you need to do.

A more involved approach would be @simllll 's: you could use a library like node-schedule to build a `Leaderboard` document. Execute the query once every 10 minutes or 60 minutes, store the result. This could be quite helpful if you want to show multiple leaderboards, like a leaderboard by region.

Another alternative would be to use [Mongoose middleware](https://mongoosejs.com/docs/middleware.html) to update the leaderboard every time you update a player's coins.

```javascript
playerSchema.pre('save', async function() {
  if (this.isModified('coins')) {
    await updateLeaderboard();
  }
});
```

I'd recommend the node-schedule approach, the middleware approach is more involved and can be brittle if someone updates the database using a UI or the `mongo` shell.

**Comment by gupta-shrinath** [comment]
@zack1991 What approach did you take?
