### ISSUE TITLE
Replica Set Auto Reconnect

### ISSUE THREAD

**Issue by edahlseng** [Automattic/mongoose#8315]
**Do you want to request a *feature* or report a *bug*?**
Ask a question

**What is the current ~behavior~ question?**
In the [documentation for the `openUri` function](https://mongoosejs.com/docs/api/connection.html#connection_Connection-openUri), there is an option, `reconnectTries`, that says (emphasis mine):
> If you're connected to a single server or mongos proxy (as opposed to a replica set), the MongoDB driver will try to reconnect every reconnectInterval milliseconds for reconnectTries times, and give up afterward. When the driver gives up, the mongoose connection emits a reconnectFailed event. **This option does nothing for replica set connections.**

Why does reconnection not work for replica set connections? Is there another way to achieve reconnection with replica sets? (Please forgive me if this has been answered somewhere else – I checked a number of closed issues, but they all seemed to refer to bugs related to reconnect events, and I still haven't found a good answer to this question 😕.)

**Comment by edahlseng** [comment]
It sounds like Mongoose should automatically reconnect to replica sets regardless of the reconnect settings, and so there might be a bug here. See #8325 for more details.

**Comment by vkarpov15** [comment]
When connected to a replica set, mongoose will continue to try to reconnect indefinitely. That's why the `reconnectTries` option does nothing for replica sets - there's no way to tell the mongodb driver to stop trying to reconnect to a replica set after a certain number of failures.
