### ISSUE TITLE
triggering  event to be called each time exec is called 

### ISSUE THREAD

**Issue by med2bled** [Automattic/mongoose#8316]
**Do you want to request a *feature* or report a *bug*?**
 a feature 
**What is the current behavior?**
when you want to do something when each time a request has been sent "exec is called " especially when working with cache  you need to in somehow extend mongoose 
```
const exec = Mongoose.prototype.exec; 
Mongoose.prototype.exec = function() {
// do what you want here 
return exec.apply(this, arguments)
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It would be nicer if we could just make an event that gonna be called each time exec is called like 
```
Mongoose.onFetch(function() {
// do all the work here 
});
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.7.9

**Comment by vkarpov15** [comment]
We do currently have `pre('exec')` and `post('exec')` hooks, they just aren't documented yet. However, are you sure you need this? With caching you generally just want to cache `find()` and `findOne()`, not updates like `updateOne()`, etc. So you could just use [query middleware](https://mongoosejs.com/docs/middleware.html).

```javascript
schema.pre(['find', 'findOne'], function() { /* ... */ });
```

Would that work for you?

**Comment by med2bled** [comment]
yes  thank you , that exactly what i am looking for and i am 
sorry i didn't notice that because i have seen a lot of people are using  a hack to make it done like [mongoose-redis](https://github.com/nasa8x/mongoose-redis/blob/master/src/index.js) for example

**Comment by vkarpov15** [comment]
Hmm I haven't heard of anyone using mongoose-redis for a while. In my experience, caching is usually unnecessary with Mongoose and often indicative of schema design issues. See:

* http://thecodebarbarian.com/mongoose-schema-design-pattern-store-what-you-query-for.html
* https://www.getrevue.co/profile/masteringjs/issues/the-benefits-of-breaking-third-normal-form-209541

So I'm curious, why are you using caching with Mongoose? Not saying you're doing anything wrong, I can think of a few cases where it makes sense.

**Comment by med2bled** [comment]
i took a nodejs course where one of its section is about caching and the mentor  uses redis this is why. 
and again thank you

**Comment by vkarpov15** [comment]
Can you link me to the course? I like to see how people are teaching mongoose :)
