### ISSUE TITLE
TypeError: Cannot read property '$__' of undefined at _updateParentPopulated

### ISSUE THREAD

**Issue by shaolintl** [Automattic/mongoose#8317]
Hello, this seems similar to #3889.

I am using node 8.10.0, mongodb 3.2.11 and mongoose 5.7.9

I have the following code:

```
var forms = this.getFormalization();
var form = forms.find(f => f._id == id);
  if (typeof form.lastIndependentDate === 'undefined' || this.lastUpdate > 
      form.lastIndependentDate) {
    forms = forms.slice()
    forms.splice(forms.indexOf(form), 1)
```

The last line throws the error:

TypeError: Cannot read property '$__' of undefined
    at _updateParentPopulated (/home/shaolin/Documents/software/normative-gui/node_modules/mongoose/lib/types/documentarray.js:323:14)
    at CoreDocumentArray.splice (/home/shaolin/Documents/software/normative-gui/node_modules/mongoose/lib/types/documentarray.js:228:5)
    at model.theorySchema.methods.isIndependent (/home/shaolin/Documents/software/normative-gui/models/theory.js:145:11)
    at /home/shaolin/Documents/software/normative-gui/controllers/theoryController.js:202:14
    at /home/shaolin/Documents/software/normative-gui/node_modules/mongoose/lib/model.js:4604:16
    at /home/shaolin/Documents/software/normative-gui/node_modules/mongoose/lib/query.js:4351:12
    at process.nextTick (/home/shaolin/Documents/software/normative-gui/node_modules/mongoose/lib/query.js:2849:28)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The model is
```
var theorySchema = new Schema({
    lastUpdate        : Date,
    name 		          : String,
    description       : String,
    content           : String, // annotated XML
    comment           : String,
    vocabulary        : [{symbol: String, original: String, full: String}],
    autoVocabulary    : [{symbol: String, original: String, full: String}],
    formalization     : [{original: String, json: Object, formula: String, active: Boolean, lastIndependent: Boolean, lastIndependentDate: Date}],
    autoFormalization : [{original: String, json: Object, formula: String, active: Boolean, lastIndependent: Boolean, lastIndependentDate: Date}],
		user 							: { type: Schema.Types.ObjectId, ref: 'User' },
    clonedForm        : { type: Schema.Types.ObjectId, ref: 'Theory' },
    lastConsistency   : Boolean,
    lastConsistencyDate: Date,
    writeProtected    : Boolean
});


theorySchema.methods.getFormalization = function() {
  return this.formalization.concat(this.autoFormalization)
}
```
Downgrading to 4.4.3 also fixes it in my case.

Thank you.

**Comment by mcijsouw** [comment]
I'm running into the same issue after upgrading from 5.7.7 to 5.7.8!

**Comment by Geenzo** [comment]
had the same issue going to 5.6.x - 5.7.10, workaround i found was not mutating the original array from the document
![image](https://user-images.githubusercontent.com/6834228/68864124-80204800-06e8-11ea-8dd1-6956e7ac88c0.png)

**Comment by esodell** [comment]
Same issue going from 5.5.x to 5.7.11. Downgrading back to 5.7.7 fixed the issue

**Comment by AbdelrahmanHafez** [comment]
This is a bug with `map(...)` as well, creating a PR for it.

Repro script:
```js
'use strict';
const mongoose = require('./');
const {Schema} = mongoose;

const assert = require('assert');

const personSchema = new Schema({
  friends: [{ name: { type: String } }]
});

const Person = mongoose.model('Person', personSchema);

const person = new Person({ friends: [{ name: 'Hafez' }] });

const friendsNames = person.friends.map(friend => friend.name);

let threw = false;

try {
  friendsNames.push('Sam');
} catch (err) {
  threw = true;
  console.log(err);
}

assert.equal(threw, false);
assert.equal(friendsNames.length, 2);
assert.equal(friendsNames[1], 'Sam');
```
