### ISSUE TITLE
Batch Queries with array

### ISSUE THREAD

**Issue by goodnewso** [Automattic/mongoose#8320]
Hello guys i am having issues with batch queries.
Is there a way to batch this queries?
normally if i want to batch a single field i would use the $in operator 
`UserModel.find({ _id: { $in: arrayOfIds} })` but this is were the trouble lies.

i have a schema like this 

`new Schema({
  participants: {
    type: [ObjectId],
    required: true,
  },
  type: {
    type: String,
    required: true,
  },
});`

if there are several documents e.g

`
{ participants: [id1, id2]},
{ participants: [id5, id9]},
{ participants: [id1, id4]},
{ participants: [id5, id8]},
{ participants: [id7, id6]},
{ participants: [id2, id6]},
{ participants: [id10, id7]},
`
i want to batch a find request to return queries matching each of this array in any arrangement

`
[[id1, id2], [id4, id1], [id6, id7]]
`

my expected result is 

`
{ participants: [id1, id2]},
{ participants: [id1, id4]},
{ participants: [id7, id6]},
`

how do i construct this

am using node  node -v
v12.13.0
"mongoose": "^5.7.9",
and mongodb atlast Version 4.0.13

Thanks in advance

**Comment by vkarpov15** [comment]
Try the aggregation framework and [`$facet`](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-34-facet.html).

```javascript
Model.aggregate([{
  $facet: {
    participants1: [{ $match: { participants: { $in: [id1, id2] } } }],
    participants2: [{ $match: { participants: { $in: [id2, id3] } } }]
  }
}]);
```

I'd question why you need a batch query though as opposed to executing one query and then grouping in Node.js. The latter is much easier.
