### ISSUE TITLE
Decimal128 fromString not working

### ISSUE THREAD

**Issue by F1NYA** [Automattic/mongoose#8323]
You can reproduce this bug on `5.7.X`(+`5.3.7`)

Converts negatives of format `0.00XX` to zero:
```
mongoose.Types.Decimal128.fromString('-0.0097').toString()
-0.0000
mongoose.Types.Decimal128.fromString('-0.0022').toString()
-0.0000
```
If add zero to the end or replace to zero, it will work fine:
```
mongoose.Types.Decimal128.fromString('-0.0007').toString()
-0.0007
mongoose.Types.Decimal128.fromString('-0.00220').toString()
-0.00220
```

**Comment by F1NYA** [comment]
works on 5.3.7 too)

**Comment by vkarpov15** [comment]
That's strange, I can't repro this error on 5.7.11.

```
$ node
> const mongoose = require('mongoose')
mundefined
> mongoose.version
'5.7.11'
> mongoose.Types.Decimal128.fromString('-0.0097').toString()
'-0.0097'
> 
```

What version of node are you using and can you please run `npm list | grep "mongo"` and post the output to show what other mongodb-related packages you're using?

**Comment by F1NYA** [comment]
node 10.16.3
```
├─┬ @private/mongo@3.0.6
│ └── mongoose-beautiful-unique-validation@7.1.1
│ ├─┬ mongodb@3.3.2
│ ├─┬ mongodb-memory-server@3.1.3
│ ├── @private/mongo@3.0.6 deduped
│ ├─┬ mongoose-encryption@2.0.2
├─┬ @types/mongoose@5.3.7
│ ├─┬ @types/mongodb@3.1.18
├─┬ mongoose@5.7.1
│ ├── mongodb@3.3.2 deduped
│ ├── mongoose-legacy-pluralize@1.0.2
```

**Comment by F1NYA** [comment]
macOS, Linux(Ubuntu)
Bug reproduced even for node 9.2.0, but for 11.15.0 works fine

Repro script like this?
```
require('mongoose').Types.Decimal128.fromString('-0.0097').toString() === '-0.0000'
```

**Comment by vkarpov15** [comment]
@F1NYA I'm unable to repro this even with Node v10.16.3 on Ubuntu. Can you try in a clean project with just mongoose installed, without `@private/mongo` and `@types/mongo`?

Also, are you transpiling this code through Typescript?

**Comment by F1NYA** [comment]
Problem was in bson package
Npm resolved bson to version 4.0.2(why?) and for this version fromString do work correctly
In other project bson package was resolved to 2.0.8 with same bug

**Comment by F1NYA** [comment]
MacOS(10.14.6), Ubuntu(18.04)
NodeJS 10.16.3

bson@2.x.x, bson@3.x.x, bson@4.x.x :
`require('bson').Decimal128.fromString('-0.0099') === '-0.0000'`

bson-ext@2.x.x :
`require('bson-ext').Decimal128.fromString('-0.0099') === '-0.0000'`

mongoose with optional bson-ext@2.x.x :
`require('mongoose').Types.Decimal128.fromString('-0.0099') === '-0.0000'`

For NodeJS 11+, works fine

**Comment by vkarpov15** [comment]
Why is bson resolved to 4.x? Mongoose specifically requests bson@~1.1.1 in `package.json`, we don't support other versions of `bson` yet.

**Comment by QuyenTran93** [comment]
> Why is bson resolved to 4.x? Mongoose specifically requests bson@~1.1.1 in `package.json`, we don't support other versions of `bson` yet.
I think bson resolved to 4.x because dependency from mongodb package
![image](https://user-images.githubusercontent.com/18302324/119640708-14717c00-be43-11eb-980c-5fd37bbadff6.png)
