### ISSUE TITLE
Population match

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [Automattic/mongoose#8327]
I want to populate a field depending on another field in the same document, however, mongoose provides a matching mechanism to filter the population process but it only matching the populated the documents (not the parent document).

My scenario like this:

```
// Store Model
const StoreSchema = new Schema({
    name:  String,
    status: {
        type: String,
        enum: ['Pending', 'Approved', 'Active', 'Suspended'],
        default: 'Pending',
        required: "Status is required",
    },
    ...
});

// Category Model
const CategorySchema = new Schema({
    name:  String,
    status: {
        type: String,
        enum: ['Pending', 'Approved', 'Active', 'Suspended'],
        default: 'Pending',
        required: "Status is required",
    },
    ...
});

// Request Model
const RequestSchema = new Schema({
    type: {
        type: String,
        enum: ['Store', 'Category']
    },
    reference:  Schema.Types.ObjectId,  // ethir Store id or Category id
    ...
});

```

Now I want to populate Request depend on `type` field, I have tried the following:

```
Request.find().populate({
                path: 'reference',
                model: 'Store',
                match: {
                    type: 'Store'
                },
            });
```

`reference` got `null` because the `populate` function matches inside the `Store` document not `Request` document.

My suggestion is to provide a mechanism to matching fields in the parent document too.

**Comment by vkarpov15** [comment]
Why not do `Request.find({ type: 'Store' }).populate({ path: 'reference', model: 'Store' })` ?
