### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by JeffersonSchuler** [Automattic/mongoose#8329]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Randomly seeing in the AWS logs:  ERROR	(node:X) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit

**If the current behavior is a bug, please provide the steps to reproduce.**

Not sure what is causing the issue, but the error started to appear in the AWS logs after upgrading from v5.7.8 to v5.7.10.

**What is the expected behavior?**
No to see this error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node is v10.x (AWS Lambda)
Mongoose is v5.7.10
Mongo is v3.6.14

v5.7.10

**Comment by vkarpov15** [comment]
Mongoose doesn't listen to sigterm events, so I don't think this is a mongoose issue
