### ISSUE TITLE
MaxListenersExceededWarning causing 502 timeout

### ISSUE THREAD

**Issue by gregorskii** [Automattic/mongoose#8334]
Hi all,

Mongo released a fix for the MaxListenersExceededWarning causing Mongo to timeout. This is causing an issue in Strapi CMS see https://github.com/strapi/strapi/issues/4311.

Can Mongoose be updated to 3.3.4?

https://github.com/mongodb/node-mongodb-native/releases/tag/v3.3.4

Thanks!

**Comment by vkarpov15** [comment]
We released v5.7.11 which uses mongodb@3.3.4. see #8337

**Comment by gregorskii** [comment]
Amazing. Thank you!
