### ISSUE TITLE
immutable nested field with default does not get populated using findOneAndUpdate with upsert:true

### ISSUE THREAD

**Issue by jbemmel** [Automattic/mongoose#8342]
Given a User schema like this: { name: String }
and a nested object with 'meta' fields { created: { type: Date, default: Date.now } }

Creating a user works, and 'created' is set to the current time.
However, if I make the 'created' field immutable, it no longer gets populated

**Comment by vkarpov15** [comment]
The below script prints the current date for me. Please modify the below script to demonstrate your issue, and please follow the issue template next time.

```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  meta: {
    created: { type: Date, default: Date.now, immutable: true }
  }
});
const Model = mongoose.model('Test', schema);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const doc = new Model({});
  console.log(doc.meta.created);
}
```

**Comment by jbemmel** [comment]
Fair enough
```javascript
const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  name: String,
  meta: {
    created: { type: Date, default: Date.now, immutable: true },
    last_modified: { type: Date, default: Date.now },
  }
});
const Model = mongoose.model('Test', schema);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const doc = new Model({ name: 'x' });
  console.log(doc);

  const newObj = { name : 'y' };
  const doc2 = await Model.findOneAndUpdate( { name: 'y' }, newObj, { new: true, upsert: true } );
  console.log( doc2 );
}
```

**Comment by jbemmel** [comment]
Change immutable on 'create' to 'false' and it does get populated

**Comment by jbemmel** [comment]
I would also argue that 'created' and 'last_modified' should get the same value for Date.now, it should be evaluated once per object instead of once per field. The database action is supposed to be atomic

**Comment by vkarpov15** [comment]
The issue is that you're not setting the `setDefaultsOnInsert` option to `findOneAndUpdate()`, which means you aren't setting `meta.created` in the database. The reason why `last_modified` shows up and why `created` and `last_modified` are different is because Mongoose is displaying the `default` value. The below script works fine:

```javascript
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);
mongoose.set('debug', true);

const schema = new mongoose.Schema({
  name: String,
  meta: {
    created: { type: Date, default: Date.now, immutable: true },
    last_modified: { type: Date, default: Date.now },
  }
});
const Model = mongoose.model('Test', schema);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();

  const newObj = { name : 'y' };
  const doc2 = await Model.findOneAndUpdate( { name: 'y' }, newObj,
    { new: true, upsert: true, setDefaultsOnInsert: true } );
  console.log( doc2 );
}
```

In this case, I'd argue Mongoose's behavior is correct. If `created` is not defined on the raw document and the field is immutable, Mongoose shouldn't set the default value.

**Comment by jbemmel** [comment]
The behavior is clearly inconsistent: there are 2 Date fields with a default value, one immutable and one not. Mongoose should either set/show both, or neither one of them. If 'last_modified' is not stored in the database, it shouldn't pretend it's set by calling Date.now() when the object is printed.

The implementation may be correct given that there is this special flag that wasn't set, but I would argue the default behavior should be to set default values when upserting, I don't see a use case for not setting defaults when defined - especially in case of an immutable field.

Works as designed, but counter intuitive

**Comment by vkarpov15** [comment]
I opened up an issue to track enabling `setDefaultsOnInsert` by default in 6.0.0 :point_up:
