### ISSUE TITLE
Reopen: Configuration to disable inclusion of embedded document schema index definitions #5575

### ISSUE THREAD

**Issue by armaserg** [Automattic/mongoose#8343]
This topic was discussed here: #5575
It looks like the problem was fixed in mongosee 4.13

But, does it work now?
There is no documentation about this: https://mongoosejs.com/docs/search.html?q=excludeIndexes :(

I have such schemas:

```
const TechnologySchema: Schema = new Schema({
  name: {type: String, unique: true, excludeIndexes: true}
}, {excludeIndexes: true});

const ProjectSchema: Schema = new mongoose.Schema({
  name: String,
  technologies: [TechnologySchema],
}, {excludeIndexes: true});
```

But in 'projects' collection I still have 'technologies.name' unique index :(

How can I prevent this?
thanks!

**Comment by vkarpov15** [comment]
We need some docs and improvements for this option, but here's how you make it work:

```javascript
const ProjectSchema = new mongoose.Schema({
  name: String,
  technologies: { type: [TechnologySchema], excludeIndexes: true },
});
```

**Comment by victors1681** [comment]
@vkarpov15 man you deserve a beer! this `excludeIndexes` is very important option, when we are reusing Schema as a nested one. Definitely the doc need to improve that feature.
