### ISSUE TITLE
Virtual getters not available when using aggregate-sample to retrieve document

### ISSUE THREAD

**Issue by cloudkj** [Automattic/mongoose#8345]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

Virtual getters are not available on documents retrieved using `.aggregate().sample()`. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Script to reproduce behavior:

```
const mongoose = require('mongoose');
const async = require('async');

const schema = new mongoose.Schema(
  { a: String },
  { toObject: { virtuals: true },
    toJSON:   { virtuals: true }});
schema.virtual('b').get(() => 'b');
const Model = mongoose.model('Model', schema);

async.series([
    (cb) => new Model({ a: 'hello' }).save(cb),
    (cb) => Model.findOne({ a: 'hello' }).exec((e, d) => {
      console.log('findOne field: ' + d.a);
      console.log('findOne virtual: ' + d.b);
      cb(null);
    }),
    (cb) => Model.aggregate().sample(1).exec((e, d) => {
      console.log('aggregate sample virtual: ' + d[0].a);
      console.log('aggregate sample virtual: ' + d[0].b);
      cb(null);
    })
  ],
  () => {});
```

Script output:

```
findOne field: hello
findOne virtual: b
aggregate sample virtual: hello
aggregate sample virtual: undefined
```

**What is the expected behavior?**

The virtual getter should be available on documents retrieved from sampling. Specifying `{ virtuals: true }` in the schema options also does not seem to fix the problem.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: 12.13.0
Mongoose: 5.7.11
MongoDB: 4.2.1

**Comment by vkarpov15** [comment]
When you use the aggregation framework, Mongoose doesn't know the shape of the objects that come out of your aggregation, so it doesn't cast them into Mongoose documents. You should use [`Model.hydrate()`](https://mongoosejs.com/docs/api/model.html#model_Model.hydrate) if you want to convert documents coming out of an aggregation into fully fledged Mongoose documents.

```javascript
Model.aggregate().sample(1).exec((err, docs) => {
  docs = docs.map(doc => Model.hydrate(doc));
  docs[0].a; // Should be defined
});
```

**Comment by iamkk11** [comment]
> When you use the aggregation framework, Mongoose doesn't know the shape of the objects that come out of your aggregation, so it doesn't cast them into Mongoose documents. You should use [`Model.hydrate()`](https://mongoosejs.com/docs/api/model.html#model_Model.hydrate) if you want to convert documents coming out of an aggregation into fully fledged Mongoose documents.
> 
> ```js
> Model.aggregate().sample(1).exec((err, docs) => {
>   docs = docs.map(doc => Model.hydrate(doc));
>   docs[0].a; // Should be defined
> });
> ```

Thank you soo much this worked for me
