### ISSUE TITLE
`MongooseArray#map()`, `#filter()`, etc. should return vanilla JS arrays

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8356]
As opposed to Mongoose arrays. These methods create new arrays rather than modifying the existing array, and the newly created array isn't connected to a document. So we should consider making these methods return a vanilla JS array.

**Comment by vkarpov15** [comment]
See #8351

**Comment by AbdelrahmanHafez** [comment]
I am not familiar with all the uses of connecting an array to the parent document, but one way I would think about it is that:

If an array method returns entirely different values of the array items (such as `map(...)`), that should return a vanilla JS array, however on other methods such as `filter(...)` and `slice(...)`, we are getting part of that mongoose array, which one could argue should be a mongoose array itself.

Is there more to it than just the type, functionality-wise?

**Comment by vkarpov15** [comment]
The only purpose of Mongoose arrays is to track changes and store them correctly in the parent document - if there isn't a parent document, there isn't much Mongoose arrays do that's useful. The only public functions I can find for mongoose arrays that aren't on vanilla JS arrays are `addToSet()`, `nonAtomicPush()`, `set()`, `toObject()`, and `toBSON()`.

Maybe instead of returning a vanilla JS array, we should return an array that has `set()`, `toObject()`, `toBSON()`, but not the custom `push()`, `pull()`, etc methods that require an array parent.

**Comment by vkarpov15** [comment]
After more careful consideration, I think @AbdelrahmanHafez is right. `map()` should return vanilla arrays, but `slice()` and `filter()` can continue to return Mongoose arrays so you can modify subdocuments like `doc.arr.filter(doc => doc.createdAt < new Date('2019-01-01')).forEach(doc => { doc.archived = true; })`. We just need to make it so that `push()` on a filtered or sliced Mongoose array throws an error.
