### ISSUE TITLE
mongoose connection validation 

### ISSUE THREAD

**Issue by Stephennwac007** [Automattic/mongoose#8358]
**Do you want to request a *feature* or report a *bug*?**   feature

**What is the current behavior?** pass option { useUnifiedTopology: true }

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

(node:11888) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
connected to database sure
pass option { useUnifiedTopology: true }

**Comment by vkarpov15** [comment]
I don't understand the issue, can you please clarify?
