### ISSUE TITLE
AWS Lambda Connection Pooling, Connection Dropping But readyState is still 1

### ISSUE THREAD

**Issue by zoltowskit** [Automattic/mongoose#8359]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behaviour?**
In our Lambda code, we are using connection pooling that checks the readyState of the mongoose connection.  It appears that if the connection is dropped by the mongodb server after the lambda has run it will not register on the lambda server when it runs again.  This leads to us using a Connection that is no longer working and causes the querries to hang until the lambda function times out.  
**If the current behaviour is a bug, please provide the steps to reproduce.**

1.) Create a lambda with connection pool  
**Our Implimentation**
`if (mongoose.connection.readyState !== 1 && mongoose.connection.readyState !== 2) {
    await mongoose.connect(connectionString, {
      "useNewUrlParser": true,
      "useUnifiedTopology": true,
      "poolSize": 100,
      "socketTimeoutMS": 2000000,
      "keepAlive": true,
      "reconnectTries": 30,
      "reconnectInterval": 500,
    }`
    });
}
  mongoose.deleteModel(/.+/u);
  return mongoose;`
2.) invoke Lambda Function
3.) Allow Connection to be dropped by the mongo Server 
4.) invoke lambda function after the connection has been dropped but before the server that the lambda is running on dies (If you run it from a cold start it will just create a new connection) 
It should be noted that this behaviour is intermittent and sometimes hard to reproduce.
**What is the expected behaviour?**
We expect to be able to reuse connections and if the connection is dropped then we want to be able to create a new one.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose version: '5.7.11'

**Comment by zoltowskit** [comment]
**Quick Update** 
Even When setting `bufferMaxEntries": 0` and `"bufferCommands": false` the query will sting hang without ending, or failing,

**Comment by vkarpov15** [comment]
How do I "allow connection to be dropped by the mongo server"?
