### ISSUE TITLE
Depreciation Warning not resolving

### ISSUE THREAD

**Issue by TheArchsage** [Automattic/mongoose#8362]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
As per the docs, mongoose.set('useUnifiedTopology', true); , should eradicate the depreciation warning of: (node:597) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and
 will be removed in a future version. To use the new Server Discover and Monitoring engine, pass
 option { useUnifiedTopology: true } to the MongoClient constructor.

However, it does not.

**If the current behavior is a bug, please provide the steps to reproduce.**
run my app.js file with the 'node' command, using the Goorm ide. All I need is: const mongoose = require('mongoose'); .
Past this, regardless as to whether or not I have the aforementioned code or not, the depreciation warning is still triggered.

const mongoose = require("mongoose");
mongoose.connect("mongodb://localhost/cat_app", {useNewUrlParser: true});
mongoose.set('useUnifiedTopology', true);

**What is the expected behavior?**
No depreciation warning.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 10.16.3
Mongo: 4.0.13
Mongoose: 5.7.11

**Comment by AbdelrahmanHafez** [comment]
I noticed that some options need to be passed as key & value pairs in connection options, while other work just fine using `mongoose.set(...)` need to verify, though.

However, as temporary solution, try
```js
const mongoose = require("mongoose");
mongoose.connect("mongodb://localhost/cat_app", { useNewUrlParser:  true, useUnifiedTopology: true });
```

**Comment by lineus** [comment]
@TheArchsage mongoose.set(..) needs to be called before mongoose.connect(..) in order for the settings to be applied to the connection. Changing the order should fix your problem.

**Comment by TheArchsage** [comment]
@lineus After calling mongoose.set(...) before mongoose.connect(...) my issue was resolved!
Additionally @AbdelrahmanHafez Your temporary solution did fix the issue as well! Thank you both for the help!
