### ISSUE TITLE
Unhandled promise rejection warning

### ISSUE THREAD

**Issue by ta-web-mex** [Automattic/mongoose#8367]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I am seeding my database with a file running with NodeJS, included beneath. The connection to the database is working and it is indeed creating the documents in the db but when it tries to close the connection to the database with `mongoose.connection.close()`, it throws an error saying `UnhandledPromiseRejectionWarning: TypeError: illegal state transition from [closing] => [connecting], allowed: [closing,closed]`

**If the current behavior is a bug, please provide the steps to reproduce.**
This is the seeds file I'm running from the cli with node bin/seeds.js
```
const mongoose = require('mongoose')
const Celeb = require('../models/Celebrity')

const celebrities = [
  {
    name: "Arnold Schwarznegger",
    occupation: "Actor",
    catchPhrase: "Sayonara, baby",
  },
  {
    name: "Luis Miguel",
    occupation: "Singer",
    catchPhrase: "Ahora te puedes marchar",
  },
  {
    name: "Seth Rogen",
    occupation: "Comedian",
    catchPhrase: "Roll a joint",
  }
]

mongoose
  .connect('mongodb://localhost/celebrities', { useUnifiedTopology: true, useNewUrlParser: true })
  .then(() => {
    Celeb.create(celebrities)
    mongoose.connection.close()
  }).catch(err => console.log(err))
```

and this is the mongoose Model
```
const { model, Schema } = require("mongoose");

const celebs = new Schema(
  {
    name: String,
    occupation: String,
    catchPhrase: String,
  })

  module.exports = model("Celebrity", celebs);
```
**What is the expected behavior?**
Previously, with version 5.3.6, this would close the connection to the database with no error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Here's the `package.json` with the dependencies I'm using for the app and the other versions are:
NodeJS `12.13.0`
Mongo `4.2.1`

```
{
  "name": "starter-code",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www",
    "dev": "DEBUG=starter-code:* nodemon ./bin/www",
    "dev-windows": "nodemon ./bin/www"
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.4",
    "dotenv": "^6.2.0",
    "express": "^4.17.1",
    "hbs": "^4.0.6",
    "mongo": "^0.1.0",
    "mongoose": "^5.7.12",
    "morgan": "^1.9.1",
    "node-sass-middleware": "^0.11.0",
    "serve-favicon": "^2.5.0"
  },
  "devDependencies": {
    "nodemon": "^1.12.1"
  }
}
```
`mongoose.version` return same version as in the `package.json`, `5.7.12`

Thank you!

**Comment by AbdelrahmanHafez** [comment]
It seems because you are trying to close the connection while still saving the documents. You need to wait till documents are saved before you try to close the connection.

There are the changes required in your code snippet.
```js
mongoose
  .connect('mongodb://localhost/celebrities', { useUnifiedTopology: true, useNewUrlParser: true })
  .then(() => Celeb.create(celebrities))
  .then(() => mongoose.connection.close())
  .catch(err => console.log(err));
```


And here's an example using async/await

```js
const mongoose = require('mongoose');
const { Schema } = require('mongoose');

const celebs = new Schema({
  name: String,
  occupation: String,
  catchPhrase: String
});

const Celeb = mongoose.model('Celebrity', celebs);

const celebrities = [{ name: 'Arnold Schwarznegger', occupation: 'Actor', catchPhrase: 'Sayonara, baby' }, { name: 'Luis Miguel', occupation: 'Singer', catchPhrase: 'Ahora te puedes marchar' }, { name: 'Seth Rogen', occupation: 'Comedian', catchPhrase: 'Roll a joint' }];

async function run () {
  await mongoose.connect('mongodb://localhost/celebrities', { useUnifiedTopology: true, useNewUrlParser: true });

  // removing await here will trigger an UnhandledPromiseRejectionWarning
  await Celeb.create(celebrities);

  await mongoose.connection.close();
  console.log('Done.');
}


run().catch(console.error);
```

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez is right, you're not waiting for the `create()` call to finish before closing the connection, and you aren't handling errors on the `create()` call, hence the [unhandled rejection](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html). This is what you should do:

```javascript
mongoose
  .connect('mongodb://localhost/celebrities', { useUnifiedTopology: true, useNewUrlParser: true })
  .then(() => Celeb.create(celebrities))
  .then(() => mongoose.connection.close())
  .catch(err => console.log(err))
```
