### ISSUE TITLE
javascript Dynamic mongoose schema

### ISSUE THREAD

**Issue by josh-whit-me** [Automattic/mongoose#8375]
I have a model whose schema has some fields which is not known until run time. 
It looks like this
	
	Schema({
		name	 			: String,
		address				: String,
		unknown_fields		:{
			unknown_field1		: Schema.Types.Mixed//mixed for unknown type string, number, bool
			//there are other fields which are not known at development 
		}
	})
	
The number of fields are not known until runtime and the field name are also not known.
Is it possible to have such a schema and how would i use it in mongoose

**Comment by AbdelrahmanHafez** [comment]
You could use Schema.Types.Mixed on unknown_fields to achieve the same results.

```js

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://127.0.0.1/test', { family: 4, useCreateIndex: true, useFindAndModify: false, useNewUrlParser: true, useUnifiedTopology: true, poolSize: 10 });

const userSchema = new Schema({
  name: String,
  unknown: { type: Schema.Types.Mixed }
});

const User = mongoose.model('User', userSchema);

async function run () {
  const [firstUser, secondUser] = await User.create([
    { name: 'Hafez', unknown: [1, 2, 3] },
    { name: 'Sam', unknown: { nested: { field: 'some value' } } }
  ]);

  assert.equal(firstUser.unknown[2], 3);
  assert.equal(secondUser.unknown.nested.field, 'some value');
}

run().catch(console.error);
```

**Comment by vkarpov15** [comment]
You can also take a look at [mongoose maps](https://mongoosejs.com/docs/schematypes.html#maps)

**Comment by josh-whit-me** [comment]
> 
> 
> You could use Schema.Types.Mixed on unknown_fields to achieve the same results.
> So your schema needs to be just like that:
> 
> ```js
> Schema({
> 	name	 			: String,
> 	address				: String,
> 	unknown_fields		: Schema.Types.Mixed
> })
> ```
> 
> Play around with the code snippet below and see if it achieves your goal.
> 
> ```js
> const assert = require('assert');
> const mongoose = require('mongoose');
> const { Schema } = mongoose;
> 
> mongoose.connect('mongodb://127.0.0.1/test', { family: 4, useCreateIndex: true, useFindAndModify: false, useNewUrlParser: true, useUnifiedTopology: true, poolSize: 10 });
> 
> const userSchema = new Schema({
>   name: String,
>   unknown: { type: Schema.Types.Mixed }
> });
> 
> const User = mongoose.model('User', userSchema);
> 
> async function run () {
>   const [firstUser, secondUser] = await User.create([
>     { name: 'Hafez', unknown: [1, 2, 3] },
>     { name: 'Sam', unknown: { nested: { field: 'some value' } } }
>   ]);
> 
>   assert.equal(firstUser.unknown[2], 3);
>   assert.equal(secondUser.unknown.nested.field, 'some value');
> }
> 
> run().catch(console.error);
> ```

Thank you very much. Very grateful. Sorry for the delay. Been busy though not an excuse, sorry about that.

**Comment by josh-whit-me** [comment]
> 
> 
> You can also take a look at [mongoose maps](https://mongoosejs.com/docs/schematypes.html#maps)

Thank you very much. I have not tried that though. But I would give it a try. 
Thanks
