### ISSUE TITLE
Setting useUnifiedTopology 

### ISSUE THREAD

**Issue by shaolintl** [Automattic/mongoose#8379]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When connection to db fails and the useUnifiedTopology is set to true, the mongoose.connect promise doesnt return an error. When this option is removed, the error is returned.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
let db = "mongodb://unknown:27017/yyy"
mongoose.connect(db,` {useNewUrlParser: true, useUnifiedTopology: true}).
    catch(error => console.log(error));
```
Doesnt return an error while
```
let db = "mongodb://unknown:27017/yyy"
mongoose.connect(db,` {useNewUrlParser: true}).
    catch(error => console.log(error));
```
returns 
```
node:7452) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
  Getting products
{ MongoNetworkError: failed to connect to server [unknown:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND unknown unknown:27017]
```

**What is the expected behavior?**
The second behavior above should apply also with the flag set to true?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongodb: 4.0.13
mongoose: 5.7.12
node: 10.16.3

**Comment by vkarpov15** [comment]
With `useUnifiedTopology`, you need to wait until `serverSelectionTimeoutMS` elapses. That's 30 seconds by default. So your script will throw an error, it'll just take longer than it would without `useUnifiedTopology`
