### ISSUE TITLE
Connection.transaction: Model instance state is not reverted after a failed transaction

### ISSUE THREAD

**Issue by juona** [Automattic/mongoose#8380]
**Do you want to request a *feature* or report a *bug*?**

Something in between, probably more of a feature since it could be a large task.

**What is the current behavior?**

Model instance state is not reverted after a failed transaction and trying to save it after the transaction is aborted will result in a VersionError.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is a pseudo example, not a real-world scenario. It's enough to reproduce the problem.

```javascript
const session = await mongoose.startSession();
const user = await UserModel.findById(userId).session(session);

// Simulating a failed transaction
try {
  await session.withTransaction(async () => {
    user.name = "Updated name";
    await user.save();
    throw new Error("Fail the transaction");
  });
} catch (err) {
  logger.debug("Oops, transaction failed, updating user status...");
  user.status = "NAME_UPDATE_FAILED";
  // At this point user.name has not been reverted to what it was initially.
  // Furthermore, the version index user.__v will point to a non-existent document
  await user.save(); // This fails with a VersionError
}
```

If after the transaction fails I reset user.name and user.__v to their initial values, the catch statement executes correctly.

**What is the expected behavior?**

Model instance data is reverted to what it was initially if the related transaction fails.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

I use mongoose 5.6.9 and for the time being I'd like to avoid the update to 5.7.12 'cause my env is quite unstable. I checked the release notes and open issues and have not noticed this behavour mentioned anywhere.

**Comment by juona** [comment]
I can appreciate the potential difficulties in dealing with this, so no easy fix expected. Perhaps a compromise solution could be implemented, e.g. automatically managing only the internal fields such as ```_v```, etc. In case this is (for the time being?) too difficult to fix, some documentation would be nice. I could then know what exactly I have to do manually after my transaction fails, if I wish to continue using the same model instance. Happy to hear your thoughts!

**Comment by unexpectedShr3k** [comment]
shouldn't you use `session.abortTransaction()`?

**Comment by juona** [comment]
The `withTransaction` helper deals with that, AFAIK. If there's an error, it aborts the transaction.

**Comment by unexpectedShr3k** [comment]
I see. This works for me:

```
session.withTransaction(() => new Promise(resolve, reject) {

    /// ... more code
    throw new Error('message');
    // ... more code

})).catch(err => {
    // manage error
});
```
