### ISSUE TITLE
Mongoose queries works perfect on Windows 10, but hangs on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by HoeGaatie1611** [Automattic/mongoose#8384]
**Context**

I've developed a React system and the login is handled by an API that hands out JWT tokens. I've developed everything on Windows 10 and I will deploy it on a EC2 Ubuntu 18.04 LTS unit.

**The problem**

The API runs on Express. The app is able to make a DB connection (which is hosted on MongoDB Atlas) on both Windows and Linux (even though it takes much longer on Linux). However, the app is not able to make a query. The find or findOne functions both don't give any feedback, while they work perfectly fine on my Windows machine.

**The relevant code**

The code is as follows:

*App.js*

    const createError = require('http-errors');
    const express = require('express');
    const app = express();
    const path = require('path');
    const cookieParser = require('cookie-parser');
    const logger = require('morgan');
    const cors = require('cors');
    const mongoose = require('mongoose');
    const dotenv = require('dotenv');
    
    dotenv.config();
    
    //Connect to DB
    mongoose.connect(process.env.DB_CONNECT, {useNewUrlParser: true, useUnifiedTopology: true}, () => {
        console.log("Connected to DB!");
    });
    
    //Import routes
    ...
    const authentication = require('./routes/Auth');
    ...
    
    //Middleware
    app.use(cors());
    app.use(logger('dev'));
    app.use(express.json());
    app.use(express.urlencoded({extended: false}));
    app.use(cookieParser());
    app.use(express.static(path.join(__dirname, 'public')));
    
    //Route middleware
    ...
    app.use('/auth', authentication);
    ...
    
    // catch 404 and forward to error handler
    app.use(function (req, res, next) {
        next(createError(404));
    });
    
    // error handler
    app.use(function (err, req, res, next) {
        // set locals, only providing error in development
        res.locals.message = err.message;
        res.locals.error = req.app.get('env') === 'development' ? err : {};
    
        // render the error page
        res.status(err.status || 500);
        res.render('error');
    });
    
    app.listen(3003, () => {
        console.log("server is up and running");
    });
    module.exports = app;

*Auth.js*

    const router = require('express').Router();
    const User = require('../model/user');
    
    const jwt = require('jsonwebtoken');
    const bcrypt = require('bcryptjs');
    const {registerValidation, loginValidation} = require('../model/Validation');
    
    ...
    
    router.post('/login', async (req, res) => {
        //Validate the data
        const {error} = loginValidation(req.body);
        if(error) return res.status(400).send(error.details[0].message);
    
        //Check if exists
        //Application fails here
        const user = await User.findOne({email: req.body.email}, function (err) {console.log(err)});
        if(!user) return res.status(400).send('Email or password is wrong');
    
        //Check if password is correct
        const validPass = await bcrypt.compare(req.body.password, user.password);
        if(!validPass) return res.status(400).send('Email or password is wrong');
    
        //Create and assign a token
        const token = jwt.sign({_id: user._id}, process.env.TOKEN_SECRET, { expiresIn: 60 * 240});
        res.header('auth-token', token).send(token);
    })
    
    ...
    
    module.exports = router;

*user.js (the model)*

    const mongoose = require('mongoose');
    
    const userSchema = new mongoose.Schema({
        name: {
            type: String,
            required: true,
            max: 255
        },
        email: {
            type: String,
            required: true,
            max: 255
        },
        password: {
            type: String,
            required: true,
            max: 1024,
            min: 6
        },
        date: {
            type: Date,
            default: Date.now
        }
    });
    
    module.exports = mongoose.model('User', userSchema);

**What I've done**

 - I've checked for errors, but can't seem to find any.
 - I've checked the connection, and it is able to connect to the server.
 - I've changed the connection parameters, which did not change any behaviour. 

**Do you want to request a *feature* or report a *bug*?**

This is either a bug or I've done something wrong.

**What is the current behavior?**

Application is able to make a connection with the DB, but can't make any queries.

**What is the expected behavior?**

Being able to actually launch my queries.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v8.10.0, Mongoose 5.7.12, MongoDB 3.3.4.

**My goal**

I want to be able to run the API on my Linux Ubuntu VPS so I can deploy the actual React application. Right now the login obviously doesn't work. All the other endpoints in the API (has a lot of functions / endpoints, but these not related to either the login endpoint or MongoDB) are working perfectly fine.

Thanks in advance!

**Comment by HoeGaatie1611** [comment]
My problem was super simple actually... I noticed my readystate was on 0, so I added the following lines to my App.js file to see what went wrong exactly:

    //Connect to DB
    mongoose.connection.on('open', function (ref) {
        console.log('Connected to mongo server.');
    });
    mongoose.connection.on('error', function (err) {
        console.log('Could not connect to mongo server!');
        console.log(err);
    });
    mongoose.connect(process.env.DB_CONNECT, {useNewUrlParser: true, useUnifiedTopology: true}, () => {
        console.log("Connected to DB!");
    }).then(r => console.log(r.connections));

After that, I noticed that my connection was closed and I was having a TransientTransactionError. 

**The solution**

Well I just forgot to add the IP adress on the new server to my IP whitelist. This took me 2 days to find out which was a bit unfortunate.

**Comment by AbdelrahmanHafez** [comment]
Glad to know you have figured it out!
Please close the issue in order to help contributors focus on issues that need further action.
