### ISSUE TITLE
Modify `find()` results using `Array#filter()` in `post('find')`

### ISSUE THREAD

**Issue by xobotyi** [Automattic/mongoose#8393]
Is it possible somehow modify the `find*` results in post hooks?

**Example:** 
I have a schema of tokens, they have expiration time and i want expired tokens to be deleted automatically and not being presented in `find*` results.

Aggregation hooks solves the results presence issue but dow not solve the deletion.
Query hooks solves the deletion issue (which is the most important of two) mut lacks of result modification.

```javascript
const tokensSchema = new mongoose.Schema({
  exp: { type: Number, immutable:true }
});

tokensSchema.post('find', async (items)=>{
    const now = Date.now();

    const toDelete: IAuthToken[] = [];
    // is there a way to store filtered items?
    items = items.filter(item => {
      if (item.exp <= now) {
        toDelete.push(item);

        return false;
      }

      return true;
    });

    await Promise.all(toDelete.map(async (item) => await item.remove()));
  });
});

tokensSchema.post( /find(?:.+)/i,
  async function(item: IAuthToken) {
    const now = Date.now() + 3600000;

    item.exp <= now && await item.remove();
  });
```

I know that returned documents can be checked for deletion with `.$isDeleted()` method, but it is absolutely uncomfortable to check it everywhere right after the fetch.

I assume that i may not see/missed the right solution due to i'm new to the mongoose (and mongo at all tbh).

**Comment by vkarpov15** [comment]
The easiest way is to modify the result array in-place using [`items.splice()`](https://masteringjs.io/tutorials/fundamentals/array-splice). Unfortunately we don't have a good way to modify the query result using `filter()` right now, but we'll work on that for a future release.

**Comment by amolsr** [comment]
Yeah, I too need this feature. I need to filter spam users. Rather then writing code again and again I was thinking of a post hook on find.

**Comment by vkarpov15** [comment]
@amolsr you can use [`splice()` to modify the array in place](https://masteringjs.io/tutorials/fundamentals/array-splice) as a workaround.
