### ISSUE TITLE
Model.findOneAndUpdate does not allow for a session param

### ISSUE THREAD

**Issue by florianbepunkt** [Automattic/mongoose#8396]
I have a session object and want a Model.findOneAndUpdate operation to be part of a transaction. I stated a question on SO here, but inspecting the typescript definitions I think this is a bug / missing feature in mongoose. You can't pass a session param to `Model.findOneAndUpdate()`

**Do you want to request a *feature* or report a *bug*?**
Not sure, kind of both

**What is the current behavior?**
Model. findOneAndUpdate() does not allow to pass a session in TypeScript. The interface `QueryFindOneAndUpdateOptions` does not have a `session` param. The node.js driver however allows to pass a session object: http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findOneAndUpdate

**If the current behavior is a bug, please provide the steps to reproduce.**

> const doc = await AnyModel.findOneAndUpdate(
>   { query: {} },
>   {
>     $inc: { value: 1 }
>   },
>   { session: session }
> );
> 

**What is the expected behavior?**
You should be able to pass a session to findOneAndUpdate

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.7.12

Link to SO:
https://stackoverflow.com/questions/59156202/use-transaction-in-model-findoneandupdate

**Comment by florianbepunkt** [comment]
Okay, it looks like it is just a TypeScript problem and `QueryFindOneAndUpdateOptions` interface should include `session?: ClientSession;`

Do you maintain the typescript definitions? I could open a PR

**Comment by Fonger** [comment]
> Okay, it looks like it is just a TypeScript problem and `QueryFindOneAndUpdateOptions` interface should include `session?: ClientSession;`
> 
> Do you maintain the typescript definitions? I could open a PR

AFAIK typescript definitions are maintained by community. There’s no official one.

**Comment by vkarpov15** [comment]
@florianbepunkt I updated our docs. We don't maintain typescript definitions currently.
