### ISSUE TITLE
Virtuals options date cast failed

### ISSUE THREAD

**Issue by TeodorKolev** [Automattic/mongoose#8401]
When virtuals are created date is not able to cast.
```
userSchema.virtual('someName', {
  ref: 'TableRef',
  localField: '_id',
  foreignField: 'coolId',
  options: { match: { someBool: false, createdAt: { gt: new Date().toISOString() } } },
  count: true,
});
```
This will produce next error:
`'Cast to date failed for value "{ gt: 2019-12-05T14:59:58.953Z }" at path "createdAt" for model "TableRef"'`
Is there any remedy for this one? This makes virtuals unusable

**Comment by AbdelrahmanHafez** [comment]
You have a typo `gt` ==> `$gt`.
