### ISSUE TITLE
Connection timeout instead of error

### ISSUE THREAD

**Issue by KissBalazs** [Automattic/mongoose#8402]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I experience the same problem, described in this closed ticket: https://github.com/Automattic/mongoose/issues/8180 but I still get this problem, even with the newer versions. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');
const connectionString = "<<a connection, which has a bad password, or the db name not exists, any problem that might occure>>"
mongoose.connect(process.env.MONGODB_URI || connectionString,
    {
        useCreateIndex: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
        dbName: <<dbname>>
    })
    .then(() => console.log('DB Connected!'))
    .catch(err => {
        console.log("DB Connection Error: " + err.message + " | connection String was: " + connectionString);
    });
mongoose.Promise = global.Promise;

This produces 
`DB Connection Error: Server selection timed out after 30000 ms | connection String was: ...`
```
If I remove the         useUnifiedTopology: true, then it works fine. (but, a warning message gets printed out, to put it back... 

> (node:24883) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**What is the expected behavior?**
Should write an error message of bad credentials, or about what is the problem. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: "^5.7.13",
MongoDB Version: 4.2.1

**Comment by vkarpov15** [comment]
The error message appears after 30 seconds by default, and you can configure the timeout using `serverSelectionTimeoutMS`:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.connect('mongodb://fake:27017', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  // Throws an error after 5 seconds
  serverSelectionTimeoutMS: 5000
}).catch(err => console.log(err));
```

If you print out the error's `reason` property, you'll get more info. For example:

```javascript
'use strict';

const mongoose = require('mongoose');

// Prints "MongoError: bad auth Authentication failed."
mongoose.connect('mongodb+srv://username:wrongpw@cluster0-OMITTED.mongodb.net/test?retryWrites=true&w=majority', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  serverSelectionTimeoutMS: 5000
}).catch(err => console.log(err.reason));
```
