### ISSUE TITLE
Transform option for custom SchemaType

### ISSUE THREAD

**Issue by m-weeks** [Automattic/mongoose#8403]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
SchemaType only allows the manipulating of values through the `cast` function and `get` functions.

**What is the expected behavior?**
I would ideally like to be able to specify a `transform` function similar to that on a model which would allow the value to be modified in both `toJSON` and/or `toObject` calls.

Here is my example, I made a custom SchemaType for storing dates without a time that inherits the mongoose `Date` type. I do this by modifying the date in the `cast` function to set its time to midnight UTC. Now when Dates are returned in toJSON, they are returned as a full ISO string. I would like to return them as just the date string. As far as I can tell, there is no way of me being able to do this without specifying the `transform` on all my models that use this `SchemaType`.

Something like the following would be nice:
```
DateOnly.prototype.toJSON = function(val) { return /* format date */ }
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.7.13
Nodejs: 10.16.0
MongoDB: 4.0.3

**Comment by vkarpov15** [comment]
Good idea! Right now the only workaround is to define a [custom type](https://mongoosejs.com/docs/customschematypes.html), but that's pretty tricky.

**Comment by vkarpov15** [comment]
Combined with #8498, in 5.9.0 you'll be able to do this:

```javascript
mongoose.Date.set('transform', val => { /* format date */ });
```
