### ISSUE TITLE
documents with select false field which is an object(not mixed type) doesn't update without markModified, even though fields were explicitly selected when querying for document

### ISSUE THREAD

**Issue by r3wt** [Automattic/mongoose#8404]
It happens on multiple models for us, so i felt like maybe i should report it. I apologize if its a known issue, but my time is scant, far too scant at this particular moment to search through issues to see if its a duplicate.

```js
const fooSchema =  new Schema({
	foo: { type: String },
	sensitive_field:{
		select: false,
		type:{
			field1: { type: String, default: null },
			field2: { type: String, default: null },
			field3: { type: String, enum:['inactive','active','cancelled','grace','suspended'], default:'inactive' },
			field4: { type: String, enum:[ 'active','none','expired','expires_soon' ], default:'none' },
			field5: { type: Boolean, default: false }
		}
	},
});
```

This is roughly what one such field looks like, as shown here `sensitive_field`. without calling `doc.markModified('sensitive_field');`  document is not updated with changes to this field.

**Comment by vkarpov15** [comment]
That's because your schema as written [defines `sensitive_field` as a Mixed type](https://mongoosejs.com/docs/schematypes.html#mixed). We unfortunately don't support defining `type` as a POJO. You would need to do this:

```javascript
const fooSchema =  new Schema({
	foo: { type: String },
	sensitive_field:{
		select: false,
		type: new Schema({
			field1: { type: String, default: null },
			field2: { type: String, default: null },
			field3: { type: String, enum:['inactive','active','cancelled','grace','suspended'], default:'inactive' },
			field4: { type: String, enum:[ 'active','none','expired','expires_soon' ], default:'none' },
			field5: { type: Boolean, default: false }
		}
	},
});
```

Re: #7181, this behavior is risky and counter intuitive, and we'll change it going forward.

**Comment by r3wt** [comment]
@vkarpov15 thanks for the info, the workaround you provided is sufficient. I appreciate you helping me
