### ISSUE TITLE
error (discord.js)

### ISSUE THREAD

**Issue by M1chnt** [Automattic/mongoose#8405]
Help connect mongodb atlas.
code ` mongoose.connect('mongodb+srv://bot:<pass>@cluster0-shard-00-00-haryl.mongodb.net/namedb'); `

error `(node:13747) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:13747) UnhandledPromiseRejectionWarning: Error: querySrv ENOTFOUND _mongodb._tcp.cluster0-shard-00-00-haryl.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19)
(node:13747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by vkarpov15** [comment]
Make sure your connection string is correct, you're connected to the internet, and your IP is in the whitelist for your Atlas cluster. the error looks like Mongoose can't resolve the domain name.
