### ISSUE TITLE
Limit number of Results for individual referenced document

### ISSUE THREAD

**Issue by volunux** [Automattic/mongoose#8409]
Question 1:

I am creating a Content Management System and let's say I have three schemas or different collections as follows;

1. Post
2. Comment
3. Reply

Post have a reference to Comment collection by Virtual Population. Something like this

postSchema.virtual('comments' , {

'ref' : 'Comment' ,
'localField' : 'slug' , 
'foreignField' : 'post_slug' ,
'count' : false
});

Comment have a reference to Reply Collection by Virtual Population. Something like this

commentSchema.virtual('replies' , {

'ref' : 'Reply' ,
'localField' : 'slug' ,
'foreignField' : 'comment_slug' ,
'justOne' : false

});

So let's say we have a single entry in Post Collection like

{'_id' : 1 , 'text' : 'First Post' 'slug' : 'first-post' }

and two entries in the Comment Collection like

{'_id' : 1 , 'text' : 'First Comment' , 'slug' : 'first-comment' , 'post_slug' : 'first-post' }
{'_id' : 2 , 'text' : 'Second Comment' , 'slug' : 'second-comment' , 'post_slug' : 'first-post' }

and 4 entries in the Reply Collection like

{'_id' : 1 , 'text' : 'First Reply' , 'slug' : 'first-reply' , 'comment_slug' : 'first-comment' }
{'_id' : 2 , 'text' : 'Second Reply' , 'slug' : 'second-reply' , 'comment_slug' : 'first-comment' }
{'_id' : 3 , 'text' : 'Third Reply' , 'slug' : 'third-reply' , 'comment_slug' : 'second-comment' }
{'_id' : 4 , 'text' : 'Fourth Reply' , 'slug' : 'fourth-reply' , 'comment_slug' : 'second-comment' }

In summary to the last snippet, let's say in addition the first comment have 15 replies while the second comment has 2 replies still.

Now the problem I am facing is that when Querying my Database to retrieve

1. Post: I can easily populate the comments to the Post Result.

2. Comment: I can also populate the replies to the Comment Result.

But the challenge I am facing is with number 2 (two) in that I can't limit the number of replies returned individually for the comments I am querying for.

This is the result

{
    "post": {
        "title": "First Post",
        "slug": "first-post"
    },
    "comments": [
        {
            "_id": "1",
            "post_slug": "first-post",
            "text": "First Comment",
            "updatedAt": "2019-12-08T10:58:00.237Z",
            "slug": "first-comment",
            "replies": [
                {
                    "text": "First Reply",
                    "comment_slug": "first-comemnt",
                    "slug": "first-reply"
                },
                {
                    "text": "Second Reply",
                    "comment_slug": "first-comment",
                    "slug": "second-reply"
                }
            ]
        },
        {
            "_id": "2",
            "text": "Second Comment",
            "post_slug": "first-post",
            "updatedAt": "2019-12-08T10:49:03.803Z",
            "slug": "second-comment",
            "replies": []
        }
    ]
}

with Query like this

Post.findComment(post) // static method

.lean({})
.populate({'path' : 'replies' , 'select' : 'text slug -_id' , 'options' : {'limit' : 2}})
.select('text updatedAt slug post_slug')

If you look at the comments array thorougly, you will see that the reply array for the first comment is containing two replies while the reply array for the second comment is empty.
If I remove the limit, the result will contain all the replies for each comments, if first comment has 100 replies while the second comment has just 2 replies, All will be included in the query
result and I don't want it this way. I want if I say limit 2, It should be two replies for each comments that are found.

I don't know if it is possible but I will like something like this.

Question 2:

And one more thing for each comment and replies and other models, I want the reference from each of the result.

Like for example 

Reply: 

Not like this:
                {
                    "text": "Second Reply",
                    "comment_slug": "first-comment",
                    "slug": "second-reply"
                }
Like this:
                {
                    "text": "Second Reply",
                    "slug": "second-reply"
                }

Comment:

Not like this:
        {
            "_id": "2",
            "text": "Second Comment",
            "post_slug": "first-post",
            "updatedAt": "2019-12-08T10:49:03.803Z",
            "slug": "second-comment",
            "replies": []
        }
Like this:
        {
            "_id": "2",
            "text": "Second Comment",
            "updatedAt": "2019-12-08T10:49:03.803Z",
            "slug": "second-comment",
            "replies": []
        }

But my most important concern is number 1, I can manage number 2.

**Comment by vkarpov15** [comment]
For question (1), unfortunately `limit` doesn't work as expected with populate() and we're working on it, follow #7318 for updates. The workaround is to loop over the `Post` docs as suggested in [this comment](https://github.com/Automattic/mongoose/issues/7318#issuecomment-527929121):

```javascript
  const doc = await Post.findOne().lean().populate('comments');
  for (const comment of doc.comments) {
    await Comment.populate(comment, { path: 'replies', options: { limit: 2, lean: true } });
  }
```

Here's a complete standalone script to demonstrate:

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();
  
  const replySchema = mongoose.Schema({
    body: String,
    commentSlug: String
  });
  const Reply = mongoose.model('Reply', replySchema);

  const commentSchema = mongoose.Schema({
    body: String,
    slug: String,
    postSlug: String
  });
  commentSchema.virtual('replies', {
    ref: 'Reply',
    localField: 'slug',
    foreignField: 'commentSlug'
  });
  const Comment = mongoose.model('Comment', commentSchema);

  const postSchema = mongoose.Schema({
    slug: String
  });
  postSchema.virtual('comments', {
    ref: 'Comment',
    localField: 'slug',
    foreignField: 'postSlug'
  });
  const Post = mongoose.model('Post', postSchema);

    await Post.create({ slug: 'intro-to-mongoose' });
  await Comment.create([
    { body: 'great!', slug: 'intro-to-mongoose-1', postSlug: 'intro-to-mongoose' },
    { body: 'sweet', slug: 'intro-to-mongoose-2', postSlug: 'intro-to-mongoose' }
  ]);
  await Reply.create([
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: '+1', commentSlug: 'intro-to-mongoose-1' },
    { body: 'I agree!', commentSlug: 'intro-to-mongoose-2' },
    { body: 'I also agree!', commentSlug: 'intro-to-mongoose-2' },
  ]);

  // Doesn't work, see https://github.com/Automattic/mongoose/issues/7318
  /*const doc = await Post.findOne().lean().populate({
    path: 'comments',
    populate: { path: 'replies', options: { limit: 2 } }
  });*/

  // Correctly pulls 2 replies for each comment
  const doc = await Post.findOne().lean().populate('comments');
  for (const comment of doc.comments) {
    await Comment.populate(comment, { path: 'replies', options: { limit: 2, lean: true } });
  }

  console.log(doc.comments.map(c => c.replies));
}
```

We'll add a note about this to the docs.
