### ISSUE TITLE
Why I am getting wrong params

### ISSUE THREAD

**Issue by forza11879** [Automattic/mongoose#8412]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug
**What is the current behavior?**
I am building a feature of the app that will draw a chart by clicking the symbol from the list (ex: MSFT - Microsoft, AAPL - Apple, GOOG - Google). The symbol will be sent by the route `router.get('/app/:symbol', getWebApi);` as a parameter that will be used to draw and update the chart data from the database.

Database is being updated in a certain interval and observed by `MongoDB - change streams` to push data to front-end on('change'). Here is my problem. When I click first time on `MSFT - req.parms.symbol: MSFT` everything is working as it should be. On second click `AAPL - req.parms.symbol: AAPL` first console.log() gives me a correct parameter of the symbol but as soon as it hits `on('change')` it will `console.log()` the symbol `MSFT` from the first click and alternate with `AAPL` which is the current parameter.

Same thing will happen on the third click `GOOG`. So I am confused why I am getting parameters that were called on previous clicks.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^5.7.12"
"mongodb": "^3.3.4"
node - v12.8.0

**controller**

```
exports.getWebApi = async (req, res) => {
  try {
    const { symbol } = req.params;

    console.log('on entry req.params.symbol: ', symbol);
    console.log(typeof symbol);

    const apiKeyAlpha = process.env.API_KEY_ALPHAVANTAGE;

    const urlCompact = `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${symbol}&outputsize=compact&apikey=${apiKeyAlpha}`;

    const webApiData = await db.fetchWebApiStock(urlCompact);
    await db.creatUpdateStock(symbol, webApiData);

    const pipeline = [
      {
        $match: {
          'ns.db': 'myapp',
          'ns.coll': 'stocks',
          'fullDocument.symbol': symbol,
        },
      },
    ];

    const options = { fullDocument: 'updateLookup' };
    const changeStream = Stock.watch(pipeline, options);

    changeStream.on('change', change => {
      console.log('req.params.symbol in change: ', symbol);

      const { fullDocument } = change;

      const webApiDataParsed = fullDocument.data.map(item => ({
        date: parseFloat(item.date),
        open: parseFloat(item.open),
        high: parseFloat(item.high),
        low: parseFloat(item.low),
        close: parseFloat(item.close),
        volume: parseInt(item.volume),
      }));

      // pusher.trigger(channel, 'AnyEvent', {
      //   chartData: webApiDataParsed ,
      //   symbol: fullDocument.symbol,
      // });
    });

    res.send(webApiData);
  } catch (ex) {
    console.log('getWebApi error:', ex);
  }
};
```

**on first click** 

```
GET /stock/chart/MSFT 304 22.401 ms - -
GET /JS/chart.js 304 0.282 ms - -
GET /JS/chartWebSearch.js 304 0.286 ms - -
on entry req.parms.symbol:  MSFT
string
GET /stock/app/MSFT 304 896.008 ms - -
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
GET /stock/updatedb 304 908.734 ms - -
```

**on second click**

```
GET /stock/chart/AAPL 304 4.494 ms - -
GET /JS/chart.js 304 0.361 ms - -
GET /JS/chartWebSearch.js 304 0.354 ms - -
on entry req.parms.symbol:  AAPL
string
req.params.symbol in change:  MSFT
GET /stock/app/AAPL 304 558.962 ms - -
req.params.symbol in change:  MSFT
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
GET /stock/updatedb 304 893.851 ms - -
```

**on third click**

```
GET /stock/chart/GOOG 304 5.002 ms - -
GET /JS/chart.js 304 0.296 ms - -
GET /JS/chartWebSearch.js 304 0.451 ms - -
on entry req.parms.symbol:  GOOG
string
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  AAPL
GET /stock/app/GOOG 304 741.986 ms - -
req.params.symbol in change:  MSFT
req.params.symbol in change:  GOOG
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  GOOG
req.params.symbol in change:  GOOG
req.params.symbol in change:  GOOG
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
req.params.symbol in change:  GOOG
req.params.symbol in change:  GOOG
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL
req.params.symbol in change:  MSFT
req.params.symbol in change:  MSFT
GET /stock/updatedb 304 820.259 ms - -
```

**Comment by vkarpov15** [comment]
When you open up a change stream, the change stream stays open even after the request handler is done. That explains why you're getting multiple `on('change')` events when you make multiple API requests.

Why are you opening up a change stream in your request handler anyway? It looks like you're updating the stock price in your route handler and then relying on a change stream to pull out the update that you just sent to the database, which is unnecessary.

**Comment by forza11879** [comment]
I have a function that is using web api to update all stocks in the database during the market hours every 500ms and I am trying to implement a feature that will stream data from the database ```on('change') ``` only for ``` req.params.symbol``` requested stock to the front-end to update the stock chart using pusher:
```
    pusher.trigger(channel, 'AnyEvent', {
      chartData: webApiDataParsed ,
      symbol: fullDocument.symbol,
      });
```
As you mentioned the change stream ```on('change')``` stays open even after the request handler is done and it is streaming data from database for multiple stocks not the one that was requested.
I was inspired by your article on change streams and was thinking it is possible to implement it.

**Comment by forza11879** [comment]
> When you open up a change stream, the change stream stays open even after the request handler is done. That explains why you're getting multiple `on('change')` events when you make multiple API requests.
> 
> Why are you opening up a change stream in your request handler anyway? It looks like you're updating the stock price in your route handler and then relying on a change stream to pull out the update that you just sent to the database, which is unnecessary.

**Comment by vkarpov15** [comment]
In that case, you should filter your change stream to only look for changes to the stock you're watching. [`Model.watch()`](https://mongoosejs.com/docs/api/model.html#model_Model.watch) takes a `pipeline` parameter that you can use to filter and transform changes using aggregation framework syntax.

**Comment by forza11879** [comment]
I thought this is exactly what I was doing
``` const pipeline = [
  {
    $match: {
      'ns.db': 'myapp',
      'ns.coll': 'stocks',
      'fullDocument.symbol': req.params.symbol,
    },
  },
];

const options = { fullDocument: 'updateLookup' };
const changeStream = Stock.watch(pipeline, options); ```

**Comment by vkarpov15** [comment]
Can you please show the code for `creatUpdateStock()`?

**Comment by forza11879** [comment]
> Can you please show the code for `creatUpdateStock()`?
Here is the code for `createUpdateStock`
```
const createUpdateStock = async (symbol, webApiData) => {
  try {
    const webApiDataReversed = webApiData.reverse();
    const query = { symbol };

    const position = await Stock.findOne(query);

    if (!position) {
      console.log('New stock'.green);
      return Stock.create({
        symbol,
        data: webApiDataReversed,
      });
    }
    await Stock.bulkWrite([
      {
        updateOne: {
          filter: query,
          update: { $pop: { data: 1 } },
        },
      },
      {
        updateOne: {
          filter: query,
          update: {
            $addToSet: {
              data: webApiDataReversed,
            },
          },
        },
      },
    ]);
  } catch (err) {
    console.log('creatUpdateStock error: ', err);
  }
};
```

**Comment by vkarpov15** [comment]
And what about for `fetchWebApiStock()`? That looks like it is attached to `db` for some reason?

Doesn't look like there's anything strange in `createUpdateStock()`. I'd try printing out what `change` is for the extraneous 'change' events to get more info on what's happening.

**Comment by forza11879** [comment]
> And what about for `fetchWebApiStock()`? That looks like it is attached to `db` for some reason?
> 
> Doesn't look like there's anything strange in `createUpdateStock()`. I'd try printing out what `change` is for the extraneous 'change' events to get more info on what's happening.
Here is `fetchWebApiStock`:
```
const fetchWebApiStock = async url => {
  try {
    const response = await axios.get(url);
    const { data } = response;

    return Object.entries(data['Time Series (Daily)']).map(
      ([date, dateObj]) => ({
        date: Date.parse(date),
        open: Math.round(parseFloat(dateObj['1. open']) * 100) / 100,
        high: Math.round(parseFloat(dateObj['2. high']) * 100) / 100,
        low: Math.round(parseFloat(dateObj['3. low']) * 100) / 100,
        close: Math.round(parseFloat(dateObj['4. close']) * 100) / 100,
        volume: parseInt(dateObj['5. volume']),
      })
    );
  } catch (err) {
    console.log('fetchWebApiStock error: ', err);
  }
};
```

**Comment by vkarpov15** [comment]
It might be that you're running duplicate servers or something is updating the data in the background. Below script doesn't show double events for me:

```javascript
const mongoose = require('mongoose');
const express = require('express');

mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/myapp?replicaSet=rs', { useNewUrlParser: true, useUnifiedTopology: true });

const Stock = mongoose.model('Stock', mongoose.Schema({
  symbol: String,
  data: []
}));

const fetchWebApiStock = async url => {
  return [{ date: '2019-06-01', open: 100, high: 101, low: 99, close: 100, volume: 5 }];
};

const createUpdateStock = async (symbol, webApiData) => {
  try {
    const webApiDataReversed = webApiData.reverse();
    const query = { symbol };

    const position = await Stock.findOne(query);

    if (!position) {
      return Stock.create({
        symbol,
        data: webApiDataReversed,
      });
    }
    await Stock.bulkWrite([
      {
        updateOne: {
          filter: query,
          update: { $pop: { data: 1 } },
        },
      },
      {
        updateOne: {
          filter: query,
          update: {
            $addToSet: {
              data: webApiDataReversed,
            },
          },
        },
      },
    ]);
  } catch (err) {
    console.log('creatUpdateStock error: ', err);
  }
};

const getWebApi = async (req, res) => {
  try {
    const { symbol } = req.params;

    console.log('on entry req.params.symbol: ', symbol);
    console.log(typeof symbol);

    const apiKeyAlpha = process.env.API_KEY_ALPHAVANTAGE;

    const urlCompact = `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${symbol}&outputsize=compact&apikey=${apiKeyAlpha}`;

    const webApiData = await fetchWebApiStock(urlCompact);
    await createUpdateStock(symbol, webApiData);

    const pipeline = [
      {
        $match: {
          'ns.db': 'myapp',
          'ns.coll': 'stocks',
          'fullDocument.symbol': symbol,
        },
      },
    ];

    const options = { fullDocument: 'updateLookup' };
    const changeStream = Stock.watch(pipeline, options);

    changeStream.on('change', change => {
      console.log('req.params.symbol in change: ', symbol);

      const { fullDocument } = change;

      const webApiDataParsed = fullDocument.data.map(item => ({
        date: parseFloat(item.date),
        open: parseFloat(item.open),
        high: parseFloat(item.high),
        low: parseFloat(item.low),
        close: parseFloat(item.close),
        volume: parseInt(item.volume),
      }));
    });

        res.send(webApiData);
  } catch (ex) {
    console.log('getWebApi error:', ex);
  }
};

const app = express();

app.get('/listen/:symbol', getWebApi);

app.listen(5001);
```

Output after I hit `localhost:5001/GOOG`, `localhost:5001/AAPL`, `localhost:5001/AAPL` is shown below. I don't get a 'GOOG' change after hitting `/AAPL` twice.

```
$ node gh-8412.js 
on entry req.params.symbol:  GOOG
string
on entry req.params.symbol:  AAPL
string
on entry req.params.symbol:  AAPL
string
req.params.symbol in change:  AAPL
req.params.symbol in change:  AAPL

```

**Comment by forza11879** [comment]
It might be that you're running duplicate servers or something is updating the data in the background. 

Do you think it may be related to MongoDB replicaSet?
here is my logs for MongoDB replicaSet:
```
2020-01-20T00:29:49.009-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56143 #60 (2 connections now open)
2020-01-20T00:30:19.009-0500 I NETWORK  [conn60] end connection 127.0.0.1:56143 (1 connection now open)
2020-01-20T00:30:22.013-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56147 #61 (2 connections now open)
2020-01-20T00:30:52.014-0500 I NETWORK  [conn61] end connection 127.0.0.1:56147 (1 connection now open)
2020-01-20T00:30:55.019-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56149 #62 (2 connections now open)
2020-01-20T00:31:25.020-0500 I NETWORK  [conn62] end connection 127.0.0.1:56149 (1 connection now open)
2020-01-20T00:31:28.025-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56152 #63 (2 connections now open)
2020-01-20T00:31:58.025-0500 I NETWORK  [conn63] end connection 127.0.0.1:56152 (1 connection now open)
2020-01-20T00:32:01.030-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56154 #64 (2 connections now open)
2020-01-20T00:32:31.030-0500 I NETWORK  [conn64] end connection 127.0.0.1:56154 (1 connection now open)
2020-01-20T00:32:34.035-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56160 #65 (2 connections now open)
2020-01-20T00:32:49.132-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56184 #66 (3 connections now open)
2020-01-20T00:32:49.135-0500 I NETWORK  [conn66] received client metadata from 127.0.0.1:56184 conn66: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.4" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-18362-Microsoft" }, platform: "'Node.js v13.5.0, LE (unified)" }
2020-01-20T00:32:49.150-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56185 #67 (4 connections now open)
2020-01-20T00:32:49.150-0500 I NETWORK  [conn67] received client metadata from 127.0.0.1:56185 conn67: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.4" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-18362-Microsoft" }, platform: "'Node.js v13.5.0, LE (unified)" }
2020-01-20T00:32:49.152-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56186 #68 (5 connections now open)
2020-01-20T00:32:49.152-0500 I NETWORK  [conn68] received client metadata from 127.0.0.1:56186 conn68: { driver: { name: "nodejs|Mongoose", version: "3.4.1|5.8.4" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-18362-Microsoft" }, platform: "'Node.js v13.5.0, LE (unified)" }
2020-01-20T00:32:49.220-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56188 #69 (6 connections now open)
2020-01-20T00:32:49.221-0500 I NETWORK  [conn69] received client metadata from 127.0.0.1:56188 conn69: { driver: { name: "nodejs", version: "3.2.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-18362-Microsoft" }, platform: "Node.js v13.5.0, LE, mongodb-core: 3.2.7" }
2020-01-20T00:33:04.035-0500 I NETWORK  [conn65] end connection 127.0.0.1:56160 (5 connections now open)
2020-01-20T00:33:07.039-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56222 #70 (6 connections now open)
2020-01-20T00:33:37.040-0500 I NETWORK  [conn70] end connection 127.0.0.1:56222 (5 connections now open)
2020-01-20T00:33:40.044-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:56233 #71 (6 connections now open)
```

**Comment by forza11879** [comment]
> It might be that you're running duplicate servers or something is updating the data in the background. Below script doesn't show double events for me:
> 
> ```js
> const mongoose = require('mongoose');
> const express = require('express');
> 
> mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/myapp?replicaSet=rs', { useNewUrlParser: true, useUnifiedTopology: true });
> 
> const Stock = mongoose.model('Stock', mongoose.Schema({
>   symbol: String,
>   data: []
> }));
> 
> const fetchWebApiStock = async url => {
>   return [{ date: '2019-06-01', open: 100, high: 101, low: 99, close: 100, volume: 5 }];
> };
> 
> const createUpdateStock = async (symbol, webApiData) => {
>   try {
>     const webApiDataReversed = webApiData.reverse();
>     const query = { symbol };
> 
>     const position = await Stock.findOne(query);
> 
>     if (!position) {
>       return Stock.create({
>         symbol,
>         data: webApiDataReversed,
>       });
>     }
>     await Stock.bulkWrite([
>       {
>         updateOne: {
>           filter: query,
>           update: { $pop: { data: 1 } },
>         },
>       },
>       {
>         updateOne: {
>           filter: query,
>           update: {
>             $addToSet: {
>               data: webApiDataReversed,
>             },
>           },
>         },
>       },
>     ]);
>   } catch (err) {
>     console.log('creatUpdateStock error: ', err);
>   }
> };
> 
> const getWebApi = async (req, res) => {
>   try {
>     const { symbol } = req.params;
> 
>     console.log('on entry req.params.symbol: ', symbol);
>     console.log(typeof symbol);
> 
>     const apiKeyAlpha = process.env.API_KEY_ALPHAVANTAGE;
> 
>     const urlCompact = `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${symbol}&outputsize=compact&apikey=${apiKeyAlpha}`;
> 
>     const webApiData = await fetchWebApiStock(urlCompact);
>     await createUpdateStock(symbol, webApiData);
> 
>     const pipeline = [
>       {
>         $match: {
>           'ns.db': 'myapp',
>           'ns.coll': 'stocks',
>           'fullDocument.symbol': symbol,
>         },
>       },
>     ];
> 
>     const options = { fullDocument: 'updateLookup' };
>     const changeStream = Stock.watch(pipeline, options);
> 
>     changeStream.on('change', change => {
>       console.log('req.params.symbol in change: ', symbol);
> 
>       const { fullDocument } = change;
> 
>       const webApiDataParsed = fullDocument.data.map(item => ({
>         date: parseFloat(item.date),
>         open: parseFloat(item.open),
>         high: parseFloat(item.high),
>         low: parseFloat(item.low),
>         close: parseFloat(item.close),
>         volume: parseInt(item.volume),
>       }));
>     });
> 
>         res.send(webApiData);
>   } catch (ex) {
>     console.log('getWebApi error:', ex);
>   }
> };
> 
> const app = express();
> 
> app.get('/listen/:symbol', getWebApi);
> 
> app.listen(5001);
> ```
> 
> Output after I hit `localhost:5001/GOOG`, `localhost:5001/AAPL`, `localhost:5001/AAPL` is shown below. I don't get a 'GOOG' change after hitting `/AAPL` twice.
> 
> ```
> $ node gh-8412.js 
> on entry req.params.symbol:  GOOG
> string
> on entry req.params.symbol:  AAPL
> string
> on entry req.params.symbol:  AAPL
> string
> req.params.symbol in change:  AAPL
> req.params.symbol in change:  AAPL
> ```

Do you think it may be related to MongoDB replicaSet?
here is my logs for MongoDB replicaSet:

**Comment by vkarpov15** [comment]
Your logs show that there's a non-mongoose connection coming in: 

```
2020-01-20T00:32:49.221-0500 I NETWORK  [conn69] received client metadata from 127.0.0.1:56188 conn69: { driver: { name: "nodejs", version: "3.2.7" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.4.0-18362-Microsoft" }, platform: "Node.js v13.5.0, LE, mongodb-core: 3.2.7" }
```

Any idea what that could be? Are you using a session storage framework like connect-mongo or connect-mongodb-session?

**Comment by forza11879** [comment]
I am using  connect-mongodb-session.

**Comment by vkarpov15** [comment]
connect-mongodb-session shouldn't trigger your change stream, so I don't think that's an issue. You can only use change streams if you're using a replica set, they don't work on standalone servers, so that's not the problem either.

Honestly, I think your problem would be solved by not creating a change stream on every request. Instead of creating a new change stream in your request handler, just create one change stream when your server starts.

**Comment by forza11879** [comment]
that is a good point!!! I just have to figure out how to get the req.symbol
to filter the data
really appreciate your support! love your book on "Mastering  Async/Await"
it helped me to improve my code.

**Comment by vkarpov15** [comment]
@forza11879 why do you need to filter `req.symbol`? It looks like you call `pusher.trigger()` with the same channel every time... Doesn't look like you actually need to filter your change stream at all, just call `pusher.trigger()` with the correct data every time.

Thanks for your comments re: the book :+1: If you have a minute, could you leave a review on [goodreads](https://www.goodreads.com/book/show/41961722-mastering-async-await?from_search=true&qid=ALRdChPDyY&rank=1)?

**Comment by forza11879** [comment]
goodreads done!

**Comment by forza11879** [comment]
I have a collection of over 1000 symbols from north american market that is updated every 30 seconds. On the change all the updates are pushed to the front-end. And If I do not filter at the database level then I have to push the whole collection to the front-end and do the filtering on front-end. I am not sure it is the best practice but at the moment this is how it works.

**Comment by vkarpov15** [comment]
If you don't see any meaningful performance issues then I think that works. I haven't used pusher before, but I'm sure clients can pick which channels to subscribe to, and you could consider having a separate channel for each symbol.

Thanks :+1:

**Comment by forza11879** [comment]
I used pusher while following your tutorial but then I wanted to implement
the same feature with native JavaScript WebSocket. I am going to look into
separating a separate channel for each symbol. Never done it before. ;)
