### ISSUE TITLE
server selection timed out after 30000ms

### ISSUE THREAD

**Issue by rajanand261** [Automattic/mongoose#8416]
<SERVER SELECTION TIMED OUT AFTER 30000ms>

I am learning web development as i am using goorm ide with node js and trying to connect to MongoDB database.by following code.

whats currently showing:
root@goorm:/workspace/project/app# node mbd.js
server listening on port 3000
ERROR: Server selection timed out after 30000 ms
^C
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
const express = require('express');
const app = express();
const mongoose = require('mongoose');
mongoose.connect('mongodb+srv://rajanand261:<madehiddenbychoice>@disc-3ptcs.gcp.mongodb.net/test?retryWrites=true&w=majority', {
    useCreateIndex: true,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    promiseLibrary: global.Promise
}).then(() => {
	console.log('Connected to DB!');
}).catch(err => {
	console.log('ERROR:', err.message);
});

const PostSchema = new mongoose.Schema({
   title: String,
   description: String,
});

const Post = mongoose.model("Post", PostSchema);

app.get('/', async (req, res) => {
	let post = await Post.create({title: 'Test', description: 'This is a test also'});
	res.send(post);
});

app.listen(3000, () => {
	console.log('server listening on port 3000');
})
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
my JSON FOLDER:
{
  "name": "post",
  "version": "1.0.0",
  "description": "to post content",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "anand raj",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.19.0",
    "ejs": "^3.0.1",
    "express": "^4.17.1",
    "mongoose": "^5.7.14"
  }
}

What is the expected behavior?
IT SHOULD SHOW "connected to DB" .

THANKS IN ADVANCE . I DONT HAVE ANY CLUE WHATS GOING.

**Comment by vkarpov15** [comment]
Make sure your Atlas URI is correct and your IP is in your [Atlas cluster's IP whitelist](https://docs.atlas.mongodb.com/security-whitelist/). This is almost certainly due to Mongoose not being able to reach your Atlas cluster.

**Comment by Gazouly** [comment]
I solved this problem by deleting the whitelisted public ip 0.0.0.0/0 and added my server ip, and now it works perfectly.
