### ISSUE TITLE
.orFail() and Typescript: object can never be null

### ISSUE THREAD

**Issue by fromi** [Automattic/mongoose#8417]
Using Typescript, `.orFail()` should return a promise that cannot resolve to null. Currently it is not the case:
```
const foo = await FooModel.findById(id).orFail()
return foo.bar // Error TS2531: Object is possibly 'null'.
```
Expected behavior: foo should not be typed as nullable when orFail is used.

**Comment by vkarpov15** [comment]
Please open up an issue with your typescript bindings, we don't have any officially supported bindings. Follow #8108 for updates.
