### ISSUE TITLE
[bug] Update Immutable filed with findoneandupdate

### ISSUE THREAD

**Issue by huangxuewu** [Automattic/mongoose#8418]
**Do you want to request a *feature* or report a *bug*?**
Critical BUG

**What is the current behavior?**
The immutable field will set to undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

1.Set a field as immutable in schema
2.Save data
3. Use findOneAndUpdate to update the document without $set operator like this

Model.item.findOneAndUpdate({_id},updatedItem,{new:true});

4. The immutable field became undefined.

**What is the expected behavior?**
Value of the Immutable field should stay the same.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.7.12
MongoDB 4.0
Nodejs 13.3

**Comment by huangxuewu** [comment]
Im trying to provide a repro on this very issue but the repro script work as expected.
Following is the code in my environment that has this issue:

```javascript
async function updateTimer(order) {
    console.log("#1", order.number);
    if (!order.option.timer) return;

    const existTimer = await Model.timer.findOne({ 'order._id': order._id, completed: false });

    if (!existTimer) return addToPrintTimer.call(this, order);
    console.log("#2", existTimer.order.number);
    order.content.forEach(item => Object.assign(item, { pending: true }));
    console.log("#3", order.number)
    const timer = await Model.timer.findOneAndUpdate({ _id: existTimer._id }, {
        order,
        station: this.socket.station,
        creator: this.socket.operator,
        scheduledAt: order.option.timer
    }, { new: true });
    console.log("#4", timer.order.number);
}
```

![f5f3bdf6e786c945de675cfa7e1b0dd](https://user-images.githubusercontent.com/6463693/71055740-bce6c100-2124-11ea-9f12-a12f163b5177.png)

if i remove the immutable property for number in the order schema , console will output the 4 same numbers.

I will keep my eyes on this bug, if im able to provide the repro i will post as soon as possible.

**Comment by vkarpov15** [comment]
I'm unable to repro this, the below script shows that `constantProp` doesn't change. Please modify the below script to demonstrate your issue.

```javascriot
'use strict';

const mongoose = require('mongoose');
mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const orderSchema = mongoose.Schema({
    content: [{
      prop: String,
      constantProp: { type: String, immutable: true },
      pending: Boolean
    }]
  });
  const Model = mongoose.model('Test', mongoose.Schema({
    order: orderSchema
  }));

  await Model.deleteMany({});
  const order = {
    content: [
      { prop: 'num1', constantProp: 'old' },
      { prop: 'num2', constantProp: 'old' }
    ]
  };
  await Model.create({ order });

  order.content = order.content.map(o => { o.pending = true; return o; });

  const doc = await Model.findOneAndUpdate({}, { order }, { new: true });
  console.log(doc.order);
}
```

**Comment by huangxuewu** [comment]
so i turn on the debug mode on the mongoose, i noticed that the findOneAndUpdate is acutally parse the object into like 

```javascript

findOneAndUpdate(
{_id:...},
'$setOnInsert': {}
'$set': {}
)
```

the key with immutable prop is not in the $set. i think that is the reason cause the immutable data change to undefined. This issue may only hidden in the nested schema object. I do realized this is not a good practise to do so and i had a workaround to bypass this issue. 

Thank you for your time. Im close this issue now.

**Comment by EhsanKey** [comment]
Hello
How did you solve this problem?

**Comment by aprilmintacpineda** [comment]
This happens consistently when I do something like this:

```
const instance = await MyModel.create({
  ...values
});

instance.value = 'Value';
await instance.updateOne();
```

Note that `values` does not include `id` or `_id` but I get the error: `MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'`

**Comment by vkarpov15** [comment]
@aprilmintacpineda below script executes without error, please open a new issue and modify the below script to demonstrate the issue you're seeing.

```
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
  });

  const MyModel = mongoose.model('Test', mongoose.Schema({ name: String }));
  const values = { name: 'test' };
  const instance = await MyModel.create({
    ...values
  });

  instance.value = 'Value';
  await instance.updateOne();
  console.log('Done');
}
```

Also, your issue is unrelated to OP's. The MongoDB server enforces that `_id` is an immutable field, OP's issue is about Mongoose's implementation of immutable fields.
