### ISSUE TITLE
useUnifiedTopology problem since 5.7.11

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8419]
**Do you want to request a *feature* or report a *bug*?**
bug

## Story

I wanted to upgrade typegoose to mongoose 5.8.0, but noticed that my tests aren't exiting, but only in travis, so i tested previous versions (5.7.14, 5.7.10) and noticed that the tests aren't exiting since 5.7.11, and then i noticed that when setting `useUnifiedTopology` to `false`, everything worked just fine. I dont know which change made this or if this even should be here or on the mongodb driver

## Notes

build log with mongoose 5.7.11: https://travis-ci.com/typegoose/typegoose/jobs/265847179
build log with mongoose 5.7.11 and set to false: https://travis-ci.com/typegoose/typegoose/jobs/265851502

typegoose-test-mongoose file: https://github.com/typegoose/typegoose/blob/r6/v6.2/test/utils/mongooseConnect.ts

## Versions

mongodb: 4.2-bionic (Docker)
nodejs: 8, 10, 12, 13
mongoose: since 5.7.11

---

PS: i dont know what or where the bug is and that everything is working fine when not running in travis, so i couldnt provide an repro code

**Comment by r3b-fish** [comment]
I have the same problem with ReplicaSet for 3.x driver versions. 

The MongoDB team announced new version [3.4.0](https://github.com/mongodb/node-mongodb-native/releases/tag/v3.4.0) of the driver.  The problem may be fixed with update.

**Comment by vkarpov15** [comment]
@hasezoey do you use mongodb-memory-server in Travis? The [`mongooseConnect.ts` file](https://github.com/typegoose/typegoose/blob/r6/v6.2/test/utils/mongooseConnect.ts) has a switch for connecting to an existing mongod instance versus starting a new one with mongodb-memory-server.

**Comment by vkarpov15** [comment]
Also, we'll try to upgrade to mongodb driver 3.4 in mongoose 5.8.3 and see if that helps.

**Comment by hasezoey** [comment]
> do you use mongodb-memory-server in Travis

yes typegoose uses `mongodb-memory-server`, but it is just handling starting & stopping (& logging) and normal mongod instance, and what i have seen from the logs, it exits normally, and only since the upgrade to mongoose 5.7.11 it is not exiting correctly, which might be the mongodb driver

> Also, we'll try to upgrade to mongodb driver 3.4 in mongoose 5.8.3 and see if that helps.

i hope so - i will report back when i upgraded

**Comment by hasezoey** [comment]
so in the end, my problem was having:

```ts
if (extraConfig.createNewConnection) {
  connection = mongoose.createConnection(await instance.getConnectionString(extraConfig.dbName), staticOptions);
}

await mongoose.connect(await instance.getConnectionString(extraConfig?.dbName), staticOptions);
```
(double connect)
replaced it with:
```ts
if (extraConfig.createNewConnection) {
  connection = mongoose.createConnection(await instance.getConnectionString(extraConfig.dbName), staticOptions);
} else {
  await mongoose.connect(await instance.getConnectionString(extraConfig?.dbName), staticOptions);
}
```
([new version in file form](https://github.com/typegoose/typegoose/blob/r6/v6.2/test/utils/mongooseConnect.ts#L39-L43))

so, now my question would be, why did it suddenly stop working on 5.7.11?
one guess might be `fix(connection): bubble up connected/disconnected events with unified topology`

**Comment by vkarpov15** [comment]
Good catch, having an open connection would explain why script didn't close. I can confirm the below script exits successfully on 5.7.11, so failed connections aren't preventing the process from exiting:

```javascript
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test', {
  useUnifiedTopology: true,
  useNewUrlParser: true,
  serverSelectionTimeoutMS: 250
});
```

Glad you found the issue on your end. I'm not sure it's worth digging into this any further, any thoughts @hasezoey ?

**Comment by hasezoey** [comment]
> Glad you found the issue on your end. I'm not sure it's worth digging into this any further, any thoughts @hasezoey ?

my problem was just not noticing that i connected the already connected connection, which had after 5.7.11 not closed the script/tests anymore
-> i would recommend adding a warning when trying to connect to an already connected connection?

**Comment by vkarpov15** [comment]
In your case, you created a connection with `createConnection()`, and also connected [Mongoose's default connection](https://mongoosejs.com/docs/connections.html#multiple_connections) using `mongoose.connect()`. So you weren't trying to connect when you were already connected, you were trying to connect on two distinct connections. Not sure how we could warn there - it is perfectly valid to use `mongoose.connect()` and `createConnection()` in the same codebase.

**Comment by hasezoey** [comment]
> . So you weren't trying to connect when you were already connected, you were trying to connect on two distinct connections

no, my code was (with the bool enabled) "connection = mongoose.createConnection" (in the if) AND "mongoose.connect" again

**Comment by vkarpov15** [comment]
So when you call `mongoose.createConnection` with arguments, you create a new connection and try to connect to mongodb on that new connection. Then `mongoose.connect()` tries to connect Mongoose's default connection. That means you have 2 connections open when you do `mongoose.createConnection(uri)` and then `mongoose.connect()`
