### ISSUE TITLE
insertMany with large data 

### ISSUE THREAD

**Issue by Navyroot** [Automattic/mongoose#8420]
I try to insert data with `insertMany` in Mongoose .
```js
console.log('Starting...')
let data = JournalDetails.find().lean()
    // data maybe over 80000
    JournalDetails.deleteMany({})
    JournalDetails.insertMany(data)
console.log('done Journal details!')
```
but it alway execute two time when call it(1 time) .
![Screen Shot 2019-12-11 at 3 59 09 PM](https://user-images.githubusercontent.com/31533986/70610136-9bbe3600-1c35-11ea-86bb-53b3f887e589.png)

**Version**
 - Mongoose version 5.7.1
 - Mongo version 4.0.10
 - Node version 8.11.3
 - Meteor version 1.8.1

**Comment by AbdelrahmanHafez** [comment]
My first guess would be that this is an issue with the code calling this code snippet, since the `console.log(...);` runs twice, this has nothing to do with mongoose. If you could provide a reproduction script that would be very helpful.

**Comment by Navyroot** [comment]
- Code Server Side
 ```js
export const migrateDataDecimal = new ValidatedMethod({
  name: 'app.migrateDataDecimal',
  mixins: [CallPromiseMixin],
  validate: null,
  async run() {
    if (Meteor.isServer) {
      console.log('Starting...');
      let data
      data = await Journals.find().lean()
      await Journals.deleteMany({})
      await Journals.insertMany(data)
      console.log('done Journal!');
      return `Success`
    }
  },
})

```
- Code Client Side 
 I called it from client side
```js
// methods on client
migrateData() {
      this.loading = true
      migrateDataDecimal
        .callPromise()
        .then(res => {
          this.loading = false
          console.log('res', res)
        })
        .catch(err => {
          this.loading = false
          console.log('err', err)
        })
}
```

**Comment by AbdelrahmanHafez** [comment]
It's not easy for me to reproduce using a client side/server side code kind of thing. There is a lot that could change in my setup that would make my test inaccurate.

Can you abstract your code in a single script that reproduces the issue? An example would look like the first code snippet in https://github.com/Automattic/mongoose/issues/8371#issuecomment-565731275.

**Comment by vkarpov15** [comment]
So what exactly is the issue here? It looks like your code runs twice, and one of those times it takes longer to execute than the other. Is that the problem, or do you not expect the code to run twice?
