### ISSUE TITLE
Converting BSON ObjectId to String

### ISSUE THREAD

**Issue by lukaswilkeer** [Automattic/mongoose#8423]
**Do you want to request a *feature* or report a *bug*?**

- Bug

**What is the current behavior?**

MongoDb ObjectId.toString() not converting to properly hex string.

The current value of toString method is a string separately by comma with timestamp compared to the hex version stored in the database due to BSON type conversion.

Similar to https://github.com/Automattic/mongoose/issues/7968

I have attempted to convert the hex to a BSON formal Object using the Types.ObjectId, but the result differs from the expected.

**What is the expected behavior?**

Match the current id version the received id.

**What are the versions of Node.js, Mongoose and MongoDB you are using?**

- Node: 12.13.0
- Mongoose 5.6.11
- Mongo: 4.0.13

**Comment by lukaswilkeer** [comment]
Fortunately the BSON type posses a method call toHexString, that's supposed to work, both in this case regenerate a hex string that is not identical to the current document _id.

**Comment by vkarpov15** [comment]
Please provide a standalone script that demonstrates the issue you're seeing.

**Comment by lukaswilkeer** [comment]
@vkarpov15 I created a [repo](https://github.com/lukaswilkeer/reproduce-hex-string-issue/tree/master ) with a reproducible example of the problem.

Or the simply script (for me, doens't clarify at all).

```js
import express from 'express'
import bodyParser from 'body-parser'
import { model } from './model/model.js'
import './db-connection.js'

const router = express.Router()
const port = process.env.PORT || 3000

const app = express()

router.get('/items', async (req, res, next) => {
	const items = await model.find({}).catch(err => null)
	const getId = (item) => item._id

	return items !== null
		? res.status(200).send(items.map(getId))
		: res.status(500).send({'message': 'An error has occurred'})
})

router.post('/check/:id', async (req, res, next) => {
	const items = await model.find({}).catch(err => null)
	const getId = (item) => item._id
	const match = (current) => (id) => current === id

	const matchCurrentId = match(req.params.id)
	const item = items.filter(matchCurrentId)

	return item.length > 0
		? res.status(200).send(true)
		: res.status(500).send({'message': 'No items matched'})
})

app.use(router)
app.listen(port, () => console.info(`App running on ${port}`))

export default app

```

**Comment by vkarpov15** [comment]
@lukaswilkeer I still don't understand your issue, it looks like you're comparing BSON ObjectIds using `===`, which isn't expected to work. `===` between two objects doesn't do any type coercion. In order to match objectids, you need to do:

```javascript
const item = items.filter(item => item.toString() === req.params.id);
```

**Comment by lukaswilkeer** [comment]
@vkarpov15 you solutioned my question here:

> between two objects doesn't do any type coercion.

Thanks
