### ISSUE TITLE
"_id" in SchemaTypeOptions

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8424]
**Do you want to request a *feature* or report a *bug*?**
missing / enhancement

**What is the current behavior?**
`_id` is not in the SchemaTypeOptions class

**What is the expected behavior?**
i would expect `_id` to be in SchemaTypeOptions

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongo: 4.2-bionic (Docker)
mongoose: 5.8
node: 12.13.1

---

note about a use case:
in typegoose options are decorators, and for something like a map we use `SchemaTypeOptions` to map them to out `of` and in `of`, and because `_id` is not in `SchemaTypeOptions` it is not mapped in `of`

(note about what i mean with "in `of`" and "out `of`":
```ts
new mongoose.Schema({
  mapped: {
    type: Map
    // i mean this block for "out"
    of: {
     type: Schema
     // and i mean "in" for this block
   }
});
```
)

**Comment by vkarpov15** [comment]
I took a closer look and `_id` shouldn't be an option for all schema types. The only schema type that currently supports the `_id` option is single nested paths from #8137. You can do `of: { type: schema, _id: false }`, but in that case you need to figure out that `of: { type: schema }` means you should use `SchemaSingleNestedOptions`, not `SchemaTypeOptions`.

**Comment by hasezoey** [comment]
yes, thanks, didnt thought of that
