### ISSUE TITLE
Schema add example doesn't work 

### ISSUE THREAD

**Issue by GjeloshajAntoine** [Automattic/mongoose#8429]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Schema `Schema.prototype.add`  doesn't add field into the new schema.
The new object created from the corresponding models just remove the keys that were added from other model.

**If the current behavior is a bug, please provide the steps to reproduce.**
Starting from the schema `add` method example of the documentation at 
https://mongoosejs.com/docs/api.html#schema_Schema-add
From the two schemas,create two models and instaciate them.

```js
const mongoose = require("mongoose");

const ToySchema = new mongoose.Schema();
ToySchema.add({ name: "string", color: "string", price: "number" });
const toyModel = mongoose.model("toy", ToySchema);

const TurboManSchema = new mongoose.Schema();
TurboManSchema.add(ToySchema).add({ year: Number });
const TurboManModel = mongoose.model("turbo", TurboManSchema);

const aToy = new toyModel({
  name: "MyToyName",
  color: "red",
  price: 123,
  year: 2009
});
const aTurbo = new TurboManModel({
  name: "MyTurboName",
  color: "red",
  price: 123,
  year: 2009
});

console.log(aToy.toJSON()); // year is expectedly deleted
console.log(aTurbo.toJSON()); //everything but year is deleted

```

**What is the expected behavior?**
It is expected that the second schema(TurboManSchema) has the properties specified in the first one (ToySchema ).
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js v13.1.0
Mongoose 5.8.1

**Comment by dfdeagle47** [comment]
I did some additional tests and it seems that mongoose doesn't take into account the added fields on the base schema. Here's a slightly modified example

```javascript
const mongoose = require('mongoose');

const BaseSchema = new mongoose.Schema({
  baseProperty: String,
}).add({ baseAddedProperty: String });

const ChildSchema = new mongoose.Schema({ childProperty: String });
ChildSchema.add(BaseSchema).add({ childAddedProperty: String });

const BaseModel = mongoose.model('bases', BaseSchema);
const ChildModel = mongoose.model('childs', ChildSchema);

const baseInstance = new BaseModel({
  baseProperty: 'base-value',
  baseAddedProperty: 'base-added-value',
});
const childInstance = new ChildModel({
  baseProperty: 'base-value',
  baseAddedProperty: 'base-added-value',
  childProperty: 'child-added-value',
  childAddedProperty: 'child-added-value',
});

console.log(baseInstance.toJSON()); // Has `baseProperty` and `baseAddedProperty`

console.log(childInstance.toJSON()); // Has `baseProperty`, `childProperty` and `childAddedProperty`, but does *not* have `baseAddedProperty`
```

Sample output
```
{ _id: 5df75c8fedfd77016f47aa72,
  baseProperty: 'base-value',
  baseAddedProperty: 'base-added-value' }
{ _id: 5df75c8fedfd77016f47aa73,
  baseProperty: 'base-value',
  childProperty: 'child-added-value',
  childAddedProperty: 'child-added-value' }
```

The `childInstance` has the base properties defined directly in the schema, but doesn't have the properties added to the base schema.

**Comment by dfdeagle47** [comment]
From what I can tell, here's the cause
- The `Schema.prototype.add` uses the `merge` function (https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L448) if a schema is passed as parameter.
- The `merge` uses `s1.add(s2.obj || {});` (https://github.com/Automattic/mongoose/blob/83b44aedebf00c97cc6c8e8139122efb0f7bdcb6/lib/helpers/schema/merge.js#L4) to add the properties to the new schema. However the property `.obj` is the original object passed to the Schema constructor (https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L239). From what I can tell, this `.obj` is never modified even when adding new properties, so this means those newly added properties won't be copied when using `Schema.prototype.add` with an instance of a schema.
