### ISSUE TITLE
Unable to connect to MongoDB Atlas from application

### ISSUE THREAD

**Issue by darshankg29** [Automattic/mongoose#8433]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1)Create a cluster in MongoDb Atlas
2)Copy URL under connect through application option
3)Edit and replace password add it as variable in .env file
4)Run the server.js 

**What is the expected behavior?**
Database connected successfully message should appear in console

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose  - 5.8.1
Node - v12.13.1

I am able to connect through Compass
Have allowed all ips in white-list (0.0.0.0/0  (includes your current IP address))

**Server.js**

const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");

require("dotenv").config();

const app = express();
const port = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const uri = process.env.ATLAS_URI;
mongoose.connect(uri, { useNewUrlParser: true, useCreateIndex: true , useUnifiedTopology: true });
const connection = mongoose.connection;
console.log(mongoose.version);
connection.once("open", () => {
  console.log("MongoDB database connection established successfully");
});

app.listen(port, () => {
  console.log(`Server is running on port :${port}`);
});

**.env**
ATLAS_URI=mongodb+srv://admin:<mypassword>@cluster0-lrusn.gcp.mongodb.net/test?retryWrites=true&w=majority 

**CONSOLE**

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server is running on port :5000
(node:18952) UnhandledPromiseRejectionWarning: MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout._onTimeout (D:\Projects\MERN\MERNApp\exersise-tracker\mern-exersise-tracker\backend\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\server_selection.js:308:9)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:18952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AbdelrahmanHafez** [comment]
Just tried your code snippet, and things are working fine for me.

It's worth noting that when using special characters in my password, I had to URL encode it like so.

```js
const password = encodeURIComponent('J51EXYlUS*m@5cwe'); // not really my password
mongoose.connect(`mongodb+srv://hafez:${password}@cluster0-qfq4m.mongodb.net/test?retryWrites=true&w=majority`, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true });
```
Logs:
```
5.8.1
Server is running on port :5000
MongoDB database connection established successfully
```

**Comment by ruslanguns** [comment]
It is failing to me as well from yesterday!

**Comment by vkarpov15** [comment]
@ruslanguns so the issue was with your DNS server?

**Comment by ruslanguns** [comment]
@vkarpov15 yes kinda! Not really sure, since the shell was working but not from NodeJS app. I don´t really undertand the network issues with my node app however changing my local settings in my network adapter from automatic DNS to Google's one it did work.
