### ISSUE TITLE
Bug: Change stream returns wrong binary data.

### ISSUE THREAD

**Issue by manhnt9** [Automattic/mongoose#8437]
**What is the current behavior?**
Change stream returns invalid binary data of newly inserted document.

**Steps to reproduce.**
- Subscribe to a model change
- Insert new record to the collection
- Get the binary of newly inserted document via change stream
- Parse the binary as BSON
- Error happens

**What is the expected behavior?**
Binary data can be parsed as BSON.

**What are the versions of Node.js, Mongoose and MongoDB you are using?**

Node.js: 8.10.0
Mongoose: 5.0.16
MongoDB: 3.6.3
OS: Ubuntu 18.04

Sample data returned by change stream:
```
[130, 93, 249, 218, 100, 0, 0, 0, 1, 70, 100, 95, 105, 100, 0, 100, 93, 249, 218, 100, 184, 117, 215, 57, 216, 27, 54, 169, 0, 90, 16, 4, 103, 31, 100, 166, 60, 46, 74, 186, 129, 75, 118, 248, 232, 48, 67, 132, 4]
```

**Test**
```python
# make sure you have python3 and bson pip package installed
import bson

buf = [130, 93, 249, 218, 100, 0, 0, 0, 1, 70, 100, 95, 105, 100, 0, 100, 93, 249, 218, 100, 184, 117, 215, 57, 216, 27, 54, 169, 0, 90, 16, 4, 103, 31, 100, 166, 60, 46, 74, 186, 129, 75, 118, 248, 232, 48, 67, 132, 4]

print(bson.loads(bytes(buf))
```
```shell
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(bson.loads(bytes(buf)))
  File "/usr/local/lib/python3.6/dist-packages/bson/__init__.py", line 47, in loads
    return decode_document(data, 0)[1]
  File "/usr/local/lib/python3.6/dist-packages/bson/codec.py", line 277, in decode_document
    if data[end_point - 1] not in ('\0', 0):
IndexError: index out of range
```
According to Python bson's implementation, the error may caused by malformed binary data missing termination: https://github.com/py-bson/bson/blob/abfa524090b18b41346e7ed8c99fb7d1d62e5a9b/bson/codec.py#L277

This maybe a mongodb bug though, please confirm then I can report to them too.

**Comment by vkarpov15** [comment]
What exactly does this have to do with Mongoose? It looks like this is a Python issue?
