### ISSUE TITLE
Get operation name and collection from inside a hook?

### ISSUE THREAD

**Issue by C-Duv** [Automattic/mongoose#8439]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

It seems there is no way for a function used as an [hook](https://mongoosejs.com/docs/middleware.html) to determine the hook it's triggered for.

```JavaScript
hook = function() {
  if (this instanceof mongoose.Query || this instanceof mongoose.Aggregate) { // Works for Model.find(), Model.aggregate() and Model.updateOne()
    ({ collection } = this.model().collection);
    action = this instanceof mongoose.Query ? this.op : 'aggregate';
  } else if (this instanceof mongoose.Model) { // Works for "save" with Model.create()
    collection = '???'; // Can't seem to be able to get the collection name
    action = '???';
  } else { //
    
  }
  console.log(`I am an hook called for action "${action}" on collection "${collection}"`);
};

MySchema.post('find', hook);
MySchema.post('aggregate', hook);
MySchema.post('save', hook);
MySchema.post('insertMany', hook);
MySchema.post('updateOne', hook);
MySchema.post('updateMany', hook);
MySchema.post('remove', hook);
```

Ti final goal / use case is to have a hook to log durations, collection, etc. for all queries/actions. Just like #7608 which works for `find()` and `aggregate()` but does not for.

**Workaround**

Have multiple hook functions or use [partial NPM package](https://www.npmjs.com/package/partial) to enrich when declaring the hook:

```JavaScript
hook = function(goal, modelName, arg1, arg2) {
  ...
}

MySchema.post('find', partial(hook, 'find', 'MySchema'));
MySchema.post('aggregate', partial(hook, 'aggregate', 'MySchema'));
MySchema.post('save', partial(hook, 'save', 'MySchema'));
MySchema.post('insertMany', partial(hook, 'insertMany', 'MySchema'));
//...
```

**Comment by vkarpov15** [comment]
We'll add a workaround. To get the collection name for the `instanceof mongoose.Model` case, you can do `this.constructor.collection.name`. For Mongoose documents, `this.constructor` is the corresponding model. No way to tell whether the action is `save()`, `validate()`, or `remove()` though.
