### ISSUE TITLE
UpdateOne or save() working on localhsot but not on server

### ISSUE THREAD

**Issue by william-levi** [Automattic/mongoose#8442]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
this is a weird behaviour, when i test it out on localhost everything works fine (updateOne method).
But when i push the codes to server and run it from there it's not working(updateOne), i also tried the save() also working on local but not on server. Server and localhost are connecting to the same databse. I have the same mongoose versions. Other updateOne methods on other routes on my api are working perfectly both on localhost and server. Server on digitalocean(ubuntu 18.04)
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
should updateOne or save()
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
localhos: 10.16.3
server: 12.14.0

5.8.1

**Comment by AbdelrahmanHafez** [comment]
Without being able to reproduce the issue, it's really difficult to be able to help.

My best guess would be that you're connecting with a user that has admin privileges (read/write) on localhost, while on your server you're connecting with a user that has read-only privileges.

**Comment by william-levi** [comment]
Thank you for the response.. I have figured out the error. 
This is due in serve having two models with the same name
(Account.js, account.js) hahahaha sorry for the trouble. everything is ok now
