### ISSUE TITLE
Mongoose update was not working

### ISSUE THREAD

**Issue by sureshfz07** [Automattic/mongoose#8446]
var result = await srServiceRequest.update({ 'isActive': true, '_id': req.body._id }, { $set: { "assign.$[].isActive": false } });

The above query  was run and updated with success state in Robo 3T with mongodb version 4.2.2 but when we are using through mongoose it doesn't react for update.

**Comment by vkarpov15** [comment]
Please open up a new issue and follow the issue template. Include schemas and version numbers.
