### ISSUE TITLE
lib/schema/array.js#L192-L215 allow "Number" in SchemaArray.prototype.enum

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8449]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

https://github.com/Automattic/mongoose/blob/master/lib/schema/array.js#L192-L215

**What is the expected behavior?**

allow "Number" too

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.8.2
nodejs: 12.14.0

**Comment by vkarpov15** [comment]
Fixed by https://github.com/Automattic/mongoose/commit/e350e6a973170d88a1636a6a0067daa514fd6dae, I just typo-ed in the commit message.

**Comment by sashaaKr** [comment]
@vkarpov15 hey,
I just wonder should this kind of change be considered as breaking change?

Why?
Here is our example:
Recently we upgraded from mongoose `5.6.7` to `5.9.9`, after upgrade we found out that some of tests fails.
We discovered that by mistake some of our models used numbers for enums, so basically it did nothing, and after upgrade some of our flows breaks.
Of course there is our responsibility, of not correct usage, but from another side I'm expecting get mongoose errors something like: "Unsupported enum type" from this king of ambiguous usage.

Wdyt about it?

**Comment by vkarpov15** [comment]
@sashaaKr almost any change can be a breaking change depending on your perspective. If you have a workaround for a bug and we fix the bug, that might be a breaking change :)

We err on the side of allowing arbitrary options on schema types for plugin support - you could have implemented `SchemaNumber#enum()` as a plugin for earlier versions of Mongoose, for example. But if an option did nothing before and we add support for it, we do not consider that a breaking change.

**Comment by sashaaKr** [comment]
@vkarpov15 got you, thanks for clarification.
