### ISSUE TITLE
Geospatial index not generating receiving error!

### ISSUE THREAD

**Issue by magicmanj27** [Automattic/mongoose#8453]
Mongoose version 5.8.2

Reporting bug:
I am receiving an error when attempting to hit a route that determines the distances between  the users and the designated location.

Steps:
1. Created an index on my model that uses the geospatial 2dsphere option.
2. Created a controller that verifies the latitude and longitude and passes it into the geoNear as coordinate points.
!!!! The index does not propagate automatically to MongoDB therefore it cannot reference the geospatial index!!!!!

When hitting the route I receive, error provided below:
`{
"status": "error",
    "err": {
        "operationTime": "6773845114411286529",
        "ok": 0,
        "errmsg": "no geo indices for geoNear",
        "code": 27,
        "codeName": "IndexNotFound",
        "$clusterTime": {
            "clusterTime": "6773845114411286529",
            "signature": {
                "hash": "1ByrK4JiQhZXRWRjYSkEUlyUETY=",
                "keyId": "6719390010044317698"
            }
        },
        "name": "MongoError",
        "statusCode": 500,
        "status": "error"
    },
    "message": "no geo indices for geoNear",
    "stack": "MongoError: no geo indices for geoNear\n    at Connection.<anonymous> (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/pool.js:460:61)\n    at Connection.emit (events.js:209:13)\n    at processMessage (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/connection.js:368:10)\n    at TLSSocket.<anonymous> (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/connection.js:537:15)\n    at TLSSocket.emit (events.js:209:13)\n    at addChunk (_stream_readable.js:305:12)\n    at readableAddChunk (_stream_readable.js:286:11)\n    at TLSSocket.Readable.push (_stream_readable.js:220:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)"
}`

4. I manually add the geospatial index to MongoDB, see image below.

<img width="436" alt="Screen Shot 2019-12-23 at 8 23 59 PM" src="https://user-images.githubusercontent.com/19230226/71393659-7846a400-25c2-11ea-9eda-b8105ed3800b.png">

When hitting the route, I receive error provided below:
`{
    "status": "error",
    "err": {
        "operationTime": "6773857840399384578",
        "ok": 0,
        "errmsg": "'near' field must be point",
        "code": 17304,
        "codeName": "Location17304",
        "$clusterTime": {
            "clusterTime": "6773857840399384578",
            "signature": {
                "hash": "7g9jy0OMltiP6bqjyCOFEbSknjM=",
                "keyId": "6719390010044317698"
            }
        },
        "name": "MongoError",
        "statusCode": 500,
        "status": "error"
    },
    "message": "'near' field must be point",
    "stack": "MongoError: 'near' field must be point\n    at Connection.<anonymous> (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/pool.js:460:61)\n    at Connection.emit (events.js:209:13)\n    at processMessage (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/connection.js:368:10)\n    at TLSSocket.<anonymous> (/Users/jeremylee/Documents/Projects/natoursApp/node_modules/mongodb/lib/core/connection/connection.js:537:15)\n    at TLSSocket.emit (events.js:209:13)\n    at addChunk (_stream_readable.js:305:12)\n    at readableAddChunk (_stream_readable.js:286:11)\n    at TLSSocket.Readable.push (_stream_readable.js:220:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)"
}`

Expected Behavior:
When hitting the distance route it should reference the geospatial index and return a query with the distance field populated in the response.

Versions:
Node: v12.9.1 
MongoDB: v4.0.10
Mongoose: v5.8.2

Please let me know if I need to provide further information for clarity.

Best Regards.

Jay.

**Comment by magicmanj27** [comment]
`exports.getDistances = catchAsync(async (req, res, next) => {
  const { latlng, unit } = req.params;
  const [lat, lng] = latlng.split(',');
  console.log('This is the lattitude 😍', lat * 1);
  console.log('This is the longitude 🥰', lng * 1);

  if (!lat || !lng) {
    next(
      new AppError(
        'Please provide latitude and longitude in the format lat,lng.',
        400
      )
    );
  }

  const distances = await Tour.aggregate([
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [lat * 1, lng * 1]
        },
        distanceField: 'distance'
      }
    }
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      data: distances
    }
  });
});
`

**Comment by magicmanj27** [comment]
Below is the controller in question!

exports.getDistances = catchAsync(async (req, res, next) => {
  const { latlng, unit } = req.params;
  const [lat, lng] = latlng.split(',');
  console.log('This is the lattitude 😍', lat * 1);
  console.log('This is the longitude 🥰', lng * 1);

  if (!lat || !lng) {
    next(
      new AppError(
        'Please provide latitude and longitude in the format lat,lng.',
        400
      )
    );
  }

  const distances = await Tour.aggregate([
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [lat * 1, lng * 1]
        },
        distanceField: 'distance'
      }
    }
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      data: distances
    }
  });
});

**Comment by magicmanj27** [comment]
Below is the controller in question!?!?!
` exports.getDistances = catchAsync(async (req, res, next) => {
  const { latlng, unit } = req.params;
  const [lat, lng] = latlng.split(',');
  console.log('This is the lattitude 😍', lat * 1);
  console.log('This is the longitude 🥰', lng * 1);

  if (!lat || !lng) {
    next(
      new AppError(
        'Please provide latitude and longitude in the format lat,lng.',
        400
      )
    );
  }

  const distances = await Tour.aggregate([
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [lat * 1, lng * 1]
        },
        distanceField: 'distance'
      }
    }
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      data: distances
    }
  });
});
 `

**Comment by vkarpov15** [comment]
The below script works as expected for me, please modify the below script to demonstrate your issue.

```javascript
'use strict';
  
const mongoose = require('mongoose');

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const latlng = '25,-80';
  const [lat, lng] = latlng.split(',');
  console.log('This is the lattitude 😍', lat * 1);
  console.log('This is the longitude 🥰', lng * 1);

  if (!lat || !lng) {
    throw new Error('Please provide latitude and longitude in the format lat,lng.');
  }

  const Tour = mongoose.model('Tour', Schema({
    point: {
      type: Schema({
        type: String,
        coordinates: [Number]
      }),
      index: '2dsphere'
    }
  }));

  await Tour.create({
    point: {
      type: 'Point',
      coordinates: [-80, 25.0001]
    }
  });

  const distances = await Tour.aggregate([
    {
      $geoNear: {
        near: {
          type: 'Point',
          coordinates: [lng * 1, lat * 1]
        },
        distanceField: 'distance'
      }
    }
  ]);

  console.log(distances);
}
```

I saw two issues with your code that might explain what you're seeing:

1. Mongoose doesn't wait for indexes to finish building before letting your use the collection. If you want to ensure all indexes are built before using your model, use [`await Model.init()`](https://mongoosejs.com/docs/api/model.html#model_Model.init)
2. In GeoJSON, coordinate pairs are in the form `[lng, lat]`, **not** `[lat, lng]`. See the [Mongoose GeoJSON docs](https://mongoosejs.com/docs/geojson.html)

**Comment by imnomee** [comment]
It might be really late to add comments but:
for the same first code, if you use following when you create index. It should work. Worked for me:
`tourSchema.index({ 'startLocation.coordinates': '2dsphere' });`
and yes. startLocation.coordicates needs to be in quotes. It will captures the coordinates from startLocation.
