### ISSUE TITLE
populate undefined array is now returning undefined

### ISSUE THREAD

**Issue by m-weeks** [Automattic/mongoose#8455]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I just upgraded my mongoose from version `5.7.11` to `5.8.3` and on my models that have an undefined array, using `populate` on that field is returning `undefined` instead of `[]` like it previously did.

I'm not sure if this change was intentional or not, I couldn't seem to track it down in the issues over the past handful of releases.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
var TestSchema = new Schema({
  thingIds: { type: [Schema.Types.ObjectId] },
});

TestSchema.virtual('things', {
  ref: 'Thing',
  localField: 'thingIds',
  foreignField: '_id',
  justOne: false,
})
```
Then when `thingIds` is undefined in the database, I get the following:
```
var testModel = await Test.findById('<some ID'>).populate('things');
console.log(testModel.things) // undefined
```

**What is the expected behavior?**
A blank array should still be returned.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 10.16.0
Mongoose: 5.8.3
MongoDb: 4.0.6

**Comment by vkarpov15** [comment]
I think #8432 was what caused this issue, will investigate :+1:
