### ISSUE TITLE
Meteor pub/sub with mongooose

### ISSUE THREAD

**Issue by Navyroot** [Automattic/mongoose#8457]
I used `Meteor + Mongoose`, I tried to real-time data with meteor pub/sub. it's work on `local`, but when deploy project to `server(digitalocean,....)` it's not work when `insert update` and `remove`.

Mongoose config connection : 
```js
import Mongoose from 'mongoose'
run().catch(err => console.log(err));
async function run() {
  // for local 
  const HOST = 'localhost'
  // const HOST = 'mongodb' for deploy to server
  const PORT = 27017
  const DB_NAME = 'dbName'

  await Mongoose.connect(`mongodb://${HOST}:${PORT}/${DB_NAME}`, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
  });
}
```

 Config meteor pub on server side :
```js
import { Meteor } from 'meteor/meteor'

import Collection from 'path'

Meteor.publish('getDataRealTime', selector => {
  // Meteor._sleepForMs(100);
  return Collection.find(selector)
})

```    

meteor subscribe on client side I use veu-mixin: 

```js
import Collection from 'path'
export default {
  meteor: {
    $subscribe: {
      'getDataRealTime': function () {return []},
    },

    realTimeData() {
      let data = Collection.find(selector).fetch()

      return data
    },
  },
}
```
can you help me ?

**Comment by vkarpov15** [comment]
Can you describe what you're doing to 'deploy project to server`?

**Comment by Navyroot** [comment]
It's mean deploy project to `meteor galaxy`, `digitalocean`, .....

**Comment by vkarpov15** [comment]
I took a closer look at your code and it looks like you're hard coding 'localhost' or 'mongodb' as the 'HOST'. Can your production server actually connect to 'mongodb'? Try SSH-ing onto your prod server and running `mongo mongodb://mongodb:27017/dbName` and verify that works.

Also, can you clarify what you mean by "it's not work"? Is there some sort of error message?
