### ISSUE TITLE
Custom data type not returning in query db

### ISSUE THREAD

**Issue by sid120498** [Automattic/mongoose#8458]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
my nestjs app connects to mongo, saved data successfully and query is working fine
**If the current behavior is a bug, please provide the steps to reproduce.**
this is my schema

    import {mongoose} from  '../utils/bson-uuid.type';
    import  *  as  uuid4  from  'uuid/v4';
    import  *  as  crypto  from  'crypto';
    export  const  CampaignManagerSchema = new  mongoose.Schema({
    _id: {type:  'BsonUuid' , default: () =>  uuid4()},
    name: {type:  String, required:  true},
    adId: {type:  String , unique:  true, required:  true},
    password: {type:  String, required:  true},
    roles: [{type:  String}],
    });
    
   this is custom data type
  

    import  *  as  mongoose  from  'mongoose';
    import  *  as  MUUID  from  'uuid-mongodb';
    class  BsonUuidType {
    v: any;
    constructor(v){
    this.v = v;
    }
    toJSON() {
    return  this.v.toString();
    }
    toBSON() {
    return  MUUID.from(this.v);
    }
    toObject(){
    return  this.v.toString();
    }
    }
    class  BsonUuid  extends  mongoose.SchemaType {
    cast(v) {
    function  validateUuid(uuid) {
    return !!/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F
    {4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.exec(uuid);
    }
    if (v  instanceof  BsonUuidType) {
    return  v;
    }
    if (validateUuid(v)) {
    return  new  BsonUuidType(v);
    }
    throw  new  Error('Invalid');
    }
    }
    mongoose.Schema.Types.BsonUuid = BsonUuid;
    export {mongoose};

output:
    `{  "roles":  [],  "name":  "string",  "adId":  "string@string.com",  "password":  "c90f86e09c3461da52b3d8bc80ccd6a0d0cb893b1a41bd461e8ed31fa21c9b6e",  "__v":  0  }`

**What is the expected behavior?**
_id should also be in output,
 also there is more schemas where these ids are stored in different field other than _id

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node = v12.14.0, nest = 6.12.9 mongoose =5.7.13

**Comment by sid120498** [comment]
```js
const  mongoose = require('mongoose');

const  MUUID = require('uuid-mongodb');

const  uuid4 = require('uuid/v4');

// tslint:disable: max-classes-per-file

class  BsonUuidType {

v;

constructor(v){

this.v = v;

}

toJSON() {

return  this.v.toString();

}

toBSON() {

return  MUUID.from(this.v);

}

toObject(){

return  this.v.toString();

}

}

class  BsonUuid  extends  mongoose.SchemaType {

cast(v) {

function  validateUuid(uuid) {

return !!/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.exec(uuid);

}

if (v  instanceof  BsonUuidType) {

return  v;

}

if (validateUuid(v)) {

return  new  BsonUuidType(v);

}

throw  new  Error('Invalid');

}

}

  

mongoose.Schema.Types.BsonUuid = BsonUuid;

mongoose.connect('mongodb://localhost:27017/myapp', {useNewUrlParser:  true});

const  CampaignManagerSchema = new  mongoose.Schema({

_id: {type:  'BsonUuid' , default: () =>  uuid4()},

name: {type:  String, required:  true},

adId: {type:  String , unique:  true, required:  true},

});

  

var  cms = mongoose.model('cms', CampaignManagerSchema);

var  cm = new  cms({

name:"string",

adId:"string"

})

const  res = cm.save().then((res)=>{

console.log(res);

//here it is returned

/*{

name: 'string',

adId: 'string',

_id: BsonUuidType { v: '48bc455f-0e65-4e50-b9e0-18e54ea96e4a' },

__v: 0

}*/

cms.findOne({_id:res._id},(err, cm)=>{

/*{ name: 'string', adId: 'string', __v: 0 }*/

//field with custom id does not returned

console.log(cm);

});

}).catch((err)=>{

console.log(err);

})

**Comment by vkarpov15** [comment]
I took a closer look and it looks like you aren't casting data that's coming out of the database correctly. `uuid-mongodb` stores uuids using MongoDB's `Binary` type, so you need to cast those correctly. Here's the correct `cast()` function:

```javascript

class  BsonUuid  extends  mongoose.SchemaType {
  cast(v) {
    function  validateUuid(uuid) {
      return !!/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.exec(uuid);
    }

    if (v  instanceof  BsonUuidType) {
      return  v;
    }

    // Since MUUID stores `v` as a binary in MongoDB, you also need to
    // be able to cast MongoDB binary data to a BsonUuidType
    if (v instanceof mongodb.Binary) {
      return new BsonUuidType(MUUID.from(v).toString());
    }

    if (validateUuid(v)) {
      return  new  BsonUuidType(v);
    }

    throw  new  Error('Invalid');
  }
}
```
