### ISSUE TITLE
[Feature] Automatic casting for first stage in aggergation if it were $match

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8464]
@vkarpov15 3+ years have passed since https://github.com/Automattic/mongoose/issues/3251 https://github.com/Automattic/mongoose/issues/2548 https://github.com/Automattic/mongoose/issues/7095
Would you reconsider if someone were to put in a PR that casts the first stage if it were a `$match`?

In our application, we take match filters from the front-end via `req.query`, and do the casting manually (via mongoose's internals). We often pass moment dates and expect them to be parsed as well, forgetting that `.toDate()` bit often introduces bugs. I think that this is a common enough use-case to encourage the automatic casting for the first pipeline if it were $match.

```js
const { Order } = require('mongoose').models;

const filter = { ...req.query, isDeleted: false, userId: req.user._id };
const castedFilter = castFilter(Order, filter);

const orders = await Order.aggregate([
  { $match: castedFilter },
  // other stages
]);
``` 

I am curious, what kind of caveats would this introduce?

If the feature request is not approved, I think I could try to create a mongoose plugin that does this and make users explicitly opt-in into this behavior, would you, in this case, consider adding it on the official FAQ?

**Comment by AbdelrahmanHafez** [comment]
I created [this repo](https://github.com/AbdelrahmanHafez/mongoose-cast-aggregation) that casts `$match` stages whenever possible.

It supports casting multiple `$match`es, and casting after `$skip` or `$sort`, until it meets a pipeline that makes the shape of the result different than the schema (when it doesn't make sense to cast any more).

**Comment by vkarpov15** [comment]
I'm supportive of a plugin, but i think putting it in Mongoose core isnt a good choice - explaining that we only cast the first stage but not the rest sounds like a bit much

**Comment by AbdelrahmanHafez** [comment]
I see your point.

The way I see it, there are two factors to this:

1- How many people will face behavior that doesn't look right to them which will lead them to ask questions.
2- How complex the answer to the question is.

With the current implementation, many people of the aggregation framework users get an error because we are not casting, and the answer to their question is simple. We don't do casting on aggregation pipelines.

If we cast `$match` when it makes sense to do so, in Mongoose core, fewer people will face those issues, because casting works out of the box (when it makes sense), but when they face a bug caused by their expectations of casting, the answer will be a little bit more complicated: We don't do casting when it doesn't make sense (e.g. when the stage input is different from the defined schema).

In my opinion, the second option (fewer questions, a little bit more complicated answer) gives a better DX than the first option.

What do you think?

**Comment by vkarpov15** [comment]
You make a good point, and I like how clean and simple your plugin is. I'll think about this more for a future release. My concern is that people will start running into surprises when they try to do `$match` after `$group` and realize that Mongoose doesn't cast `$match` if it is after a certain stage, so then they'll try to shuffle around their aggregation stages. But admittedly that's a small concern.

Also, what do you think about adding `$lookup` to your list of [`pipelinesThatDoNotAffectProjection`](https://github.com/AbdelrahmanHafez/mongoose-cast-aggregation/blob/0fe242b2a4fabd20ae33ff79fa9478a618930fad/index.js#L4) ? AFAIK `$lookup` only adds fields, it doesn't change existing fields on the document.

**Comment by AbdelrahmanHafez** [comment]
Glad to know you'll reconsider.

I understand your concern about the issue with users running into surprises when `$match`ing after a `$group`.

As to the `$lookup` stage, It adds a document in a field (that may or may not have the same field name), and a user may try to `$match` something inside that field, which would be deleted by casting.  For example:

```js

await Order.aggregate([
  { $match: {} },
  { $lookup: { from: 'users', localField: 'userId', foreignField: '_id', as: 'userId' } },
  { $match: { 'userId.isDeleted': false } } // woulld be removed if we casted against the order schema
]);
```

We could, of course, try to handle such a case, but that would be too much magic. I am leaning towards keeping it as simple as possible, while still doing the casting. 

I just looked at the list of MongoDB aggregation stages, and added `$limit`, and `$sample`.
Right now the list looks like this: 
```js
['$match', '$limit', '$sort', '$skip', '$sample']
```

**Comment by AbdelrahmanHafez** [comment]
If and when you decide to move forward with this, let me know, I'll be more than happy to put in a PR that does just that in Mongoose's core.

Otherwise, I am always happy to know what you think of the matter.

**Comment by Ampilverma** [comment]
Below Here my aggregation function and working fine. but i want some improvement in this query so i want users enter the FristDay and LastDay  and data will fetch so how write query in below function

 const   ressult= await this.orderModel.aggregate([
      { $match:{orderStatus:"Delivered"}},
      {$group: { _id : {
        year:{$year:"$createdAt"},
        month:{$month:"$createdAt"},
        day:{$dayOfMonth:"$createdAt"}
        },
        count:{$sum: 1 }
      }
      }
      ], function (err, result) {
      if (err) {
        console.log(err);
        return;
      }
    console.log(result);
});

**Comment by AbdelrahmanHafez** [comment]
@Ampilverma 
You can filter the documents that go from one stage to another by `createdAt` field such as follows:
```js
const result = await this.orderModel.aggregate([
  { $match: { orderStatus: 'Delivered', createdAt: { $gte: firstDay, $lte: lastDay } } },
  // add the rest of your stages here
]);
```

Not sure if your issue is related to casting or a general aggregation question, if it's the latter, perhaps it would be a good idea to create a separate issue next time.

**Comment by AbdelrahmanHafez** [comment]
I'll update this reply with comments and threads in support of casting by default:
https://github.com/Automattic/mongoose/issues/8489#issuecomment-576537539 @rahulmathews
https://github.com/Automattic/mongoose/issues/2548#issue-52285268 @mauriciogior

**Comment by Ampilverma** [comment]
@AbdelrahmanHafez 
Thanks for response. it's general aggregation question i tried your code but still not working..
what  my question is  i want to do filter to above mention code. like if your are Admin and you want particular date(Like starting date) and end date(like last date) Oders data so how apply aggregation  on only you have createdAt as data base record no separate date, monht and years.

**Comment by AbdelrahmanHafez** [comment]
If I understand correctly, you want to get all records in a specific year/month/day, correct?

Let's assume you want all the records that are created on Jan. 21st 2020, you can simply do the following:

```js
const startDate = new Date(new Date('2020-01-21').setHours(0, 0, 0, 0));
const endDate = new Date(new Date('2020-01-21').setHours(23, 59, 59, 999));

const result = await this.orderModel.aggregate([
  { $match: { orderStatus: 'Delivered', createdAt: { $gte: startDate, $lte: endDate } } },
  // add the rest of your stages here
]);
```

Or with using [momentjs](https://momentjs.com/) (Recommended):
```js
const moment = require('moment');

// converting `toDate` manually because mongoose doesn't cast on aggregation (the current issue)
const startDate = moment('2020-01-21').startOf('day').toDate();
const endDate = moment('2020-01-21').endOf('day').toDate();

const result = await this.orderModel.aggregate([
  { $match: { orderStatus: 'Delivered', createdAt: { $gte: startDate, $lte: endDate } } },
  // add the rest of your stages here
]);
```

You can do the same with any dates, if you want all the records in a specific month, get the beginning and end of month (make sure you're getting the first second in the first day of the duration, and the last second of the last day of the duration, or simply use `moment(...).startOf(...).toDate()` and `moment(...).endOf(...).toDate()`.

If you have any further questions regarding this issue, please open a new issue so we can keep things focused here.

**Comment by Ampilverma** [comment]
@AbdelrahmanHafez 
Thanks  it's working!!!!!

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
[The plugin](https://www.npmjs.com/package/mongoose-cast-aggregation) seems to be getting some attention lately, 1.3~1.8k weekly downloads.

I think it would be a good idea to add it as an [officially supported plugin](https://mongoosejs.com/docs/plugins.html#official), which would give it more exposure, which will give us more insight on how much this behavior is desired, and we can decide accordingly whether or not we'll build this behavior in mongoose's core.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez :+1:
