### ISSUE TITLE
Mongoose 5.8.3 can't connect without sslCA option

### ISSUE THREAD

**Issue by WandersonAlves** [Automattic/mongoose#8470]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Can't connect in mongo instance without sslCA option enabled. The error above occurs (please, read the context section of this issue for more details)

```javascript
{ MongoTimeoutError: Server selection timed out after 30000 ms
    at Timeout.setTimeout (/home/popoto/Desktop/dev/e3/isa-v2/common-service/node_modules/mongodb/lib/core/sdam/server_selection.js:309:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'MongoTimeoutError',
  reason:
   { Error: self signed certificate in certificate chain
       at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
       at TLSSocket.emit (events.js:189:13)
       at TLSSocket._finishInit (_tls_wrap.js:633:8)
     name: 'MongoNetworkError',
     [Symbol(mongoErrorContextSymbol)]: {} },
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Connet to mongo instance

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 10.15.3
Mongoose: 5.8.3
MongoDB: 4.0 (IBM's Cloud Offering)

**Context**
In newer versions of mongoose, i can connect to the instance only passing a cert file to connection settings, just like this:

```typescript
connect(): Promise<this> {
    return new Promise(async (resolve, reject) => {
      try {
        this.db = await createConnection(`${env.mongodb_url}`, {
          authSource: env.mongodb_authsource ? env.mongodb_authsource : null,
          ssl: env.mongodb_replset ? true : false,
          sslCA: [readFileSync('mongo.pem')],
          replicaSet: env.mongodb_replset ? env.mongodb_replset : null,
          dbName: env.mongodb_database_name,
          appname: 'common-service',
        });
        if (this.db.readyState !== 1) {
          throw new MongoNotConnectedException();
        }
        resolve(this);
      } catch (err) {
        console.error(err);
        reject(err);
        process.exit(1);
      }
    });
  }
```

On a older version of mongoose (5.7.5 for example), i don't have to send a sslCA option to my connection settings:

```typescript
connect(): Promise<this> {
    return new Promise(async (resolve, reject) => {
      try {
        this.db = await createConnection(`${env.mongodb_url}`, {
          authSource: env.mongodb_authsource ? env.mongodb_authsource : null,
          ssl: env.mongodb_replset ? true : false,
          replicaSet: env.mongodb_replset ? env.mongodb_replset : null,
          dbName: env.mongodb_database_name,
          appname: 'common-service',
        });
        if (this.db.readyState !== 1) {
          throw new MongoNotConnectedException();
        }
        resolve(this);
      } catch (err) {
        console.error(err);
        reject(err);
        process.exit(1);
      }
    });
  }
```

The env attrs are this:

MONGO_URL=mongodb://{user}:{password}@130fc2df-d280-4d5b-8fd7-3856ff99d34e-0.2adb0220806343e3ae11df79c89b377f.databases.appdomain.cloud:32373,{another-replica-set-member}
MONGO_DB={some-default-db}
MONGO_REPLSET=replset
MONGO_AUTHSOURCE={some-authsource}

So, my question is: what have changed on mongoose to this starts to happen? Some security bug was fixed and now i'm getting a error that i should have on the past or this is something else entirely new?

**Comment by vkarpov15** [comment]
Your error says there's a "self signed certificate in certificate chain". As far as I know, that's a mongodb server configuration issue, has nothing to do with Mongoose: https://stackoverflow.com/questions/44560944/mongoerror-self-signed-certificate-in-certificate-chain .

Given that there's a simple workaround and that it seems like a server config issue, I'm going to close this.
