### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by lokothwayo** [Automattic/mongoose#8474]
I am using the latest version of mongoose but and have include {useNewUrlParser: true}, but the deprecationWarning still persists.

Below is just the top part of my code
var express = require("express");
var app = express();
var bodyParser = require("body-parser");
var mongoose = require("mongoose");

var localHost = '127.0.0.1'
var port = 3000;

app.set("view engine", "ejs") //setting the ejs files
//Using the body parser
app.use(bodyParser.urlencoded({extended: true}));

//setting and connecting to the database
mongoose.connect('mongodb://localhost:27017 /yelp_camp', { useNewUrlParser: true });

**Comment by vkarpov15** [comment]
Which deprecating warning are you seeing? Make sure you follow all the instructions on our [deprecation warnings docs](https://mongoosejs.com/docs/deprecations.html).
