### ISSUE TITLE
How to lookup subquery documents with another collection moongoose

### ISSUE THREAD

**Issue by dileepjb2** [Automattic/mongoose#8480]
Hi i Have 3 collections 
        new Schema({
        product_title:String,
        product_desc: String,
        Product_purchased:[
    {
        userid:mongoose.Schema.ObjectId,
        purchased_date:Date
        }]
        posteduserId: mongoose.Schema.ObjectId
        })
        
        Users=new Schema({
        _id:userId,
        name:String,
        Pic:String
        })
        
        then how to get result like below.
        [ 
           { 
              "product_title":"title",
              "product_desc":"desc",
              "Product_purchased":[ 
                 { 
                    "userid":"5d4hvh7duc7c7c8d9scbe",
                    "name":"name",
                    "Pic":"url",
                    "purchased_date":"Date"
                 },
                 { 
                    "userid":"5d4hvh7duc7c7c8d9scbe",
                    "name":"name",
                    "Pic":"url",
                    "puchased_date":"Date"
                 }
              ],
              "posteduserId": "5d4hvh7duc7c7c8d9scbe",
              "userid": "5d4hvh7duc7c7c8d9scbe",
              "name": "name",
              "pic": "url",
           }
        ]
        Join same user table with posted userid and subarray of purchased userIds.Please help me how to crack this one . Thanks in advance.

**Comment by vkarpov15** [comment]
You should be able to use [`populate()`](https://mongoosejs.com/docs/populate.html#population): `Product.populate('Product_purchased.userid')`
