### ISSUE TITLE
Apparently ObjectId has an _id property that points to itself

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#8483]
Just found that #6415 exists after using mongoose for about 5 years.

This is super handy 👏 , but I wish it were documented properly.

I couldn't find it in the documentation, and the link here https://mongoosejs.com/docs/api.html#types-objectid-js seems to point to itself, not really providing any details about the ObjectId type, nor that it has an _id property.

Am I looking with my nose, or is it not documented?

**Comment by vkarpov15** [comment]
If you couldn't find it in the docs, that's worth looking into :+1: thanks for the heads up.
