### ISSUE TITLE
[Feature] default options for specific data type

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8487]
There are types that I almost always use specific options with.

For example, I always use `trim: true` with fields that have `type: String`, and I require everything by default, the exception being things that are `required: false`, and numbers almost always have `min: 0`.

Is there a way we can add default options per field type, which can be overwritten by specifying some other value?

The way I imagine such an API would be as follows:
```js
// maybe per schema?
mongoose.fieldOptions({ type: String, defaultOptions: { trim: true, required: true  } });
```

Thoughts?

**Comment by vkarpov15** [comment]
I think we can support `mongoose.Schema.String.set('trim', true)`, does that seem like a reasonable API?

**Comment by AbdelrahmanHafez** [comment]
That would be incredible!
Do you think we can apply this to other options like `required`, `set`, `get`, `validate`?

This is an area in the codebase that I haven't touched before, it's a challenge that I'd like to take.
I'll try the `trim` option first, and let you know if I need help.

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15
So, I've been exploring how to implement the suggested API, there seems to be no property `String` under `mongoose.Schema`. Do you mean `mongoose.SchemaTypes.String`? Or do you want to add new properties under `Schema` for setting options?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez yep I meant `mongoose.SchemaTypes.String`, `lib/schema/String.js`
