### ISSUE TITLE
multiple database connection using same schema within the same session

### ISSUE THREAD

**Issue by josh-whit-me** [Automattic/mongoose#8492]
I just basically want to be able to change databases without loosing the session

I have an application which I want it to have multiple database connections but there would be a central db from which other dbs would run from.
So when the client connects to the application through the central db, based on what they provided they would be allocated to a specific database  and based on their activities they may also be transfered to another database while still in operation. And this connection would be used across several files which would be calling the various models

This is what I have so far
	
app.js

	var mongoose = require('mongoose');
	mongoose.connect('mongodb://localhost:27017/centraldb');
	app.use(function(req, res, next){
		var dbName =req.query.user_params;
		//connections[dbName] = mongoose.connection.useDb(dbName);
		connections[dbName] = mongoose.connect('mongodb://localhost:27017/' + dbName);
		next();
	});
	
This changes it to the new database but it cuts the connection to the session which I do not want.

This is a sample of the schema of a model
model.js
	
	var mongoose = require('mongoose');
	var userSchema = mongoose.Schema({
		first_name	 : String,
		other_names	 : String,
	})

this is the sample of a controller
file1.js
	
	var modelData            = require('./model')
	let modelData = new modelData();
	modelData.firstname = 'name'
	modelData.other_names = 'other names'
	modelData.save()
	
This has been used for a single database. But I want to use it for multiple databases i.e. while a user is in file1.js and (s)he is working on db1 (s)he can also change to db2 using the same model and perform operation on the same model but in a different db.
I am looking at not loosing the connection to the 1st database so probably keeping them in a pool or session.

**Comment by AbdelrahmanHafez** [comment]
Not sure I fully understand your problem.

Do you want to use the same model with different databases? If that's the case, you should consider exporting the schema, and building two different models each with its own connection, because a model always belongs to a single connection.

[This section](https://mongoosejs.com/docs/connections.html#multiple_connections) in the docs has an example where you can do that.

**Comment by vkarpov15** [comment]
I think I already answered this question somewhere recently. Read the [multiple connections](https://mongoosejs.com/docs/connections.html#multiple_connections) docs. TLDR; use `mongoose.createConnection()` to create a new connection. Calling `mongoose.connect()` connects Mongoose's default connection.
