### ISSUE TITLE
Client-Side Field Level Encryption with Atlas

### ISSUE THREAD

**Issue by rocksmash1** [Automattic/mongoose#8496]
_Bug Report_

Using CSFLE with MongoDB Atlas does not seem to function. To use this in production I need to be able to use an Atlas database. I use mongoose as a major part of my app and would like to continue using it over the normal MongoDB driver.

I have seen https://github.com/Automattic/mongoose/issues/8167 and wondering if there is an eta on a fix or possible work around, thanks!

The current error is **MongoError: BSON field 'insert.jsonSchema' is an unknown field.**
Using Mongo 4.2 on Atlas

```const mongodb = require('mongodb')
const { ClientEncryption } = require('mongodb-client-encryption');
const base64 = require('uuid-base64');
const mongoose = require('mongoose');
const { MongoClient, Binary } = mongodb
const { port, databaseUri, awsAccessID, awsAccessKey, awsRegion, cmkARN } = require('./env')

run().catch(err => console.log(err));

async function run() {

    const keyVaultNamespace = 'database.collection';
    const kmsProviders = {
        aws: {
            accessKeyId: `${awsAccessID}`,
            secretAccessKey: `${awsAccessKey}`,
        }
    }
    await mongoose.connect(databaseUri, {
         useNewUrlParser: true,
         useUnifiedTopology: true,
         autoEncryption: {
             keyVaultNamespace,
             kmsProviders,
             extraOptions: { mongocryptdURI: databaseUri }
         }


    });





    const encryption = new ClientEncryption(mongoose.client.connection, {
        keyVaultNamespace,
        kmsProviders,

    });
    const key = await encryption.createDataKey('aws', {
        masterKey: {
            key: cmkARN, // e.g. 'arn:aws:kms:us-east-2:111122223333:alias/test-key'
            region: awsRegion, // e.g. 'us-east-1'
        }
    });


}
```

MongoDB Version: 4.2.2
Mongoose Version 5.8.7
Node version 12.14.1

**Comment by rocksmash1** [comment]
Repro script has now been added!

**Comment by rocksmash1** [comment]
Just a bump to add the `Has Repro Script` Label to this. Let me know if you find anything while investigating as well thanks.

**Comment by vkarpov15** [comment]
It looks like you're trying to use your Atlas cluster as a replacement for the mongocryptd process. If you get rid of this line: `extraOptions: { mongocryptdURI: databaseUri }` and set up a mongocryptd locally, it works as expected. Below script works once I added `mongocryptd` to my PATH:

```javascript
const { ClientEncryption } = require('mongodb-client-encryption');
const mongodb = require('mongodb');

const { MongoClient, Binary } = mongodb;

const databaseUri = 'mongodb+srv://OMITTED:OMITTED@cluster0-OMITTED.mongodb.net/client?retryWrites=true&w=majority';

run().catch(err => console.log(err));

async function run() {
  const arr = [];
  for (let i = 0; i < 96; ++i) {
    arr.push(i);
  }
  const key = Buffer.from(arr);
  const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };

  const client = await MongoClient.connect(databaseUri, {
         useNewUrlParser: true,
         useUnifiedTopology: true,
         autoEncryption: {
             keyVaultNamespace,
             kmsProviders
         }
    });

  await client.db().collection('Test').findOne();


console.log('done');
}

```

I don't know what the recommended approach for running mongocryptd is when using Atlas, I recommend you [contact MongoDB Atlas support](https://docs.atlas.mongodb.com/support/) to ask how you should run mongocryptd.

**Comment by rocksmash1** [comment]
MongoDB Atlas claims that you can use your database URI as a mongocryptd process. I cannot install it locally because this api will be hosted on Heroku, so installing mongocryptd on my pc will have no effect on that.

**Comment by rocksmash1** [comment]
> It looks like you're trying to use your Atlas cluster as a replacement for the mongocryptd process. If you get rid of this line: `extraOptions: { mongocryptdURI: databaseUri }` and set up a mongocryptd locally, it works as expected. Below script works once I added `mongocryptd` to my PATH:
> 
> ```js
> const { ClientEncryption } = require('mongodb-client-encryption');
> const mongodb = require('mongodb');
> 
> const { MongoClient, Binary } = mongodb;
> 
> const databaseUri = 'mongodb+srv://OMITTED:OMITTED@cluster0-OMITTED.mongodb.net/client?retryWrites=true&w=majority';
> 
> run().catch(err => console.log(err));
> 
> async function run() {
>   const arr = [];
>   for (let i = 0; i < 96; ++i) {
>     arr.push(i);
>   }
>   const key = Buffer.from(arr);
>   const keyVaultNamespace = 'client.encryption';
>   const kmsProviders = { local: { key } };
> 
>   const client = await MongoClient.connect(databaseUri, {
>          useNewUrlParser: true,
>          useUnifiedTopology: true,
>          autoEncryption: {
>              keyVaultNamespace,
>              kmsProviders
>          }
>     });
> 
>   await client.db().collection('Test').findOne();
> 
> 
> console.log('done');
> }
> ```
> 
> I don't know what the recommended approach for running mongocryptd is when using Atlas, I recommend you [contact MongoDB Atlas support](https://docs.atlas.mongodb.com/support/) to ask how you should run mongocryptd.

MongoDB Atlas claims that you can use your database URI as a mongocryptd process. I cannot install it locally because this api will be hosted on Heroku, so installing mongocryptd on my pc will have no effect on that.

Also in the script above, I do not see mongoose anywhere? The issue of connecting is with mongoose, not with MongoDB or Atlas

**Comment by vkarpov15** [comment]
Can you link me to where they say that you can use your Atlas URI as a mongocryptd process? It might be that you need to have an Enterprise cluster on Atlas in order to use your database URI...

**Comment by feliperegis** [comment]
Hey @vkarpov15, we are facing the same issue @rocksmash1 is. I'm not sure if this issue was resolved for rocksmash1, wasn't it?We alson cannot install it locally because the api will be hosted externally, on Azure instead. For the same reasons, installing mongocryptd locally won't have effect.

Differently from rocksmash1, we are using C# but the logic and requirements are the same.

Tks!

**Comment by vkarpov15** [comment]
@felipelousantos if you're using C#, you aren't using Mongoose. Please ask questions / report an issue on the C# project you're using.

**Comment by felipelousantos** [comment]
It seems that I was pinged by mistake here. cc: @feliperegis
