### ISSUE TITLE
uncaughtException on network outage

### ISSUE THREAD

**Issue by keithchew** [Automattic/mongoose#8503]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When there is a network outage, we are experiencing an uncaughtException in our application, causing the process to terminate.

**If the current behavior is a bug, please provide the steps to reproduce.**
We have created a simple test to reproduce this issue.

Below are the options for mongoose:
```
                {
                    useNewUrlParser: true,
                    useUnifiedTopology: true,
                    serverSelectionTimeoutMS: 20000,
                    connectTimeoutMS: 8000,
                    socketTimeoutMS: 10000,
                    family: 4
                }
```
and our URL has the format: `mongodb+srv://`

Every 5s, we run:
```
const user = await User.findOne({ 'id': '1234' });
```

Randomly, we will unplugged the network cable, and within 5 to 10 tries, we will get this from the uncaughtException handler (for Node 8.9.3):
```
2020-01-05 18:58:12.0570 - error: uncaughtException: read ECONNRESET
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25)
```

On Node 12, this is the error:
```
2020-01-12 19:08:52.0880 - error: uncaughtException: read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)
```

**What is the expected behavior?**
This condition should be handled by the underlying library, to prevent the application from crashing.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 8.9.3 and 12.13.0
Mongoose - 5.8.4 (also tested on master branch latest commit 58c4c1af426b1a7e95eb736a5f227f5553189368)
MongoDB - 3.4.0

**Comment by AbdelrahmanHafez** [comment]
I don't think it's a good idea to have a connection error swallowed silently. Plus, what do you think is a proper value to return for the `const user = await User.findOne({ 'id': '1234' });` when connection fails?

That error is thrown by design. Connection errors should be thrown, and handled by the library user.

**Comment by keithchew** [comment]
My apologies, I should have clarified better. We do have a try catch block for the findOne, ie:
```
        try {
          const user = await User.findOne({ 'id': '1234' });
        } catch (err) {
            logger.error(`Failed to find user using MongoDB [${err}]`);
        }
```
The error is never thrown in this code flow.

**Comment by AbdelrahmanHafez** [comment]
So, does the try/catch here solve your issue? Or is there unexpected behavior even with the try/catch?

**Comment by keithchew** [comment]
We have always had the try/block, I just forgot to write it in this bug report earlier. There is still the expected behaviour with it. When unplugging and plugging the network, most of the time it will throw the expected error:
```
Failed to find user using MongoDB [MongoTimeoutError: Server selection timed out after 20000 ms]
```
But randomly, it will crash the application with the uncaughtException.

**Comment by AbdelrahmanHafez** [comment]
I think this might be thrown by the underlying MongoDB driver, and I believe this is by design as well.

In order to prevent your application from crashing, try the code snippet below, it should help.
```js
process.on('uncaughtException', (err) => {
  console.log('Uncaught exception:', err);
});

process.on('unhandledRejection', (err) => {
  console.log('Unhandled rejection:', err);
});
```

On a side note, I think you should try to handle the connection problem rather than trying to work around it, you'll fill your codebase with lots and lots of hacks in order to do that, and there will always be unexpected scenarios.

**Comment by keithchew** [comment]
I have already done that, which is how I am printing the logs of the uncaughtException in the bug report.

**Comment by keithchew** [comment]
From the stack trace, this error is thrown by the node TLSWrap:

https://github.com/nodejs/node/blob/master/src/tls_wrap.cc

But not handled by the either Mongoose or MongoDB (further down)...

**Comment by AbdelrahmanHafez** [comment]
Interesting.

It's my understanding that in order for an error to crash the application it has to propagate up to the application and never get caught.
One exception that I could think of would be some library in the middle catching the error, and explicitly exiting the process.

Can you create a [reproduction script](https://stackoverflow.com/help/minimal-reproducible-example) that mimics the network outage, crashing the application even with try/catch, `process.on('uncaughtException');`, `process.on('unhandledRejection');` so we could look deeper into this?

**Comment by keithchew** [comment]
OK, a couple of things.

First, I tracked down the culprit exiting the application. It was the logger winston:
```
By default, winston will exit after logging an uncaughtException. If this is not the behavior you want, set exitOnError = false
```
Setting exitOnError = false will at least buy us some time until the bug found and fixed.

Second, we reverted back to the non unified topology:
```
useUnifiedTopology: false,
```
The app seems stable, so the problem could be due to this flag (which is meant to default to true in the future).

Not sure if it helps, but we noticed that without unified topology, we received the "disconnected", "connected" and "reconnected" events, but with it, we don't see those events. Errors are also different, we get a mixture of:
- MongoError: no primary server available
- MongoError: Pool was force destroyed
- MongoNetworkError: write ECONNRESET

So perhaps there is still some work to get unified topology working reliably.

I will continue to observe the behavior, and report here if I can track it down further.

**Comment by keithchew** [comment]
Instead of physically unplugging and plugging in the network cable, I used a script to disconnect the connect the network interface every 90s.

I can confirm that with useUnifiedTopology = true, we get the uncaughtException after attempt 5. With useUnifiedTopology = false, the script has been running for over 30 attempts without any uncaught exceptions (yet).

**Comment by vkarpov15** [comment]
@keithchew can you please share the script you wrote? It would be very helpful in our attempts to track this down.

**Comment by keithchew** [comment]
@vkarpov15 of course!... here is one i used in Windows, which is in a .bat file (it will be a lot simpler if it was written in bash for linux/mac, basically disconnecting/connect the network interface in X seconds for Y attempts):
```
@echo off
REM netsh interface show interface

SET /A "sleepBeforeDisable = 90"
SET /A "sleepBeforeEnable = 90"
SET /A "index = 1"
SET /A "count = 100"

:while
if %index% leq %count% (
  FOR /L %%i IN (0,1,%sleepBeforeDisable%) DO (
    echo before disabling network sleep [%%i/%sleepBeforeDisable%]s progress [%index%/%count%]
    ping 127.0.0.1 -n 2 > nul
  )
  echo disabling network
  netsh interface set interface "Ethernet 6" disable

  FOR /L %%i IN (0,1,%sleepBeforeEnable%) DO (
    echo before enabling network sleep [%%i/%sleepBeforeEnable%]s progress [%index%/%count%]
    ping 127.0.0.1 -n 2 > nul
  )
  echo enabling network
  netsh interface set interface "Ethernet 6" enable

  SET /A "index = index + 1"
  goto :while
)
```

**Comment by vkarpov15** [comment]
I haven't been able to repro this, below script seems to work fine, no errors reported. Using [ubuntu](https://askubuntu.com/questions/434660/how-can-i-disable-my-internet-connection-from-terminal):

```javascript
'use strict';

const { execSync } = require('child_process');
const mongoose = require('mongoose');

mongoose.connect('mongodb+srv://OMITTED:OMITTED@cluster0-OMITTED.mongodb.net/test?retryWrites=true&w=majority', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  serverSelectionTimeoutMS: 5000
});

const Model = mongoose.model('Test', mongoose.Schema({ name: String }));

Promise.all([run(), toggleWifi()]).catch(err => console.log(err));

let start = Date.now();

async function toggleWifi() {
  while (true) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    console.log('Disable wifi...');
    execSync('nmcli networking off');
    await new Promise(resolve => setTimeout(resolve, 10000));
    console.log('Enable wifi...');
    execSync('nmcli networking on');
    await new Promise(resolve => setTimeout(resolve, 20000));
  }
}

async function run() {
  while (true) {
    const res = await Model.findOne();
    console.log(`+${Date.now() - start} Ran findOne()`);

    await new Promise(resolve => setTimeout(resolve, 1000));
  }
}

```

Output:

```
$ node gh-8503.js
+813 Ran findOne()
+1857 Ran findOne()
+2895 Ran findOne()
+3934 Ran findOne()
+4975 Ran findOne()
+6017 Ran findOne()
+7075 Ran findOne()
+8122 Ran findOne()
+9165 Ran findOne()
Disable wifi...
+10579 Ran findOne()
Enable wifi...
+42825 Ran findOne()
+43863 Ran findOne()
+44903 Ran findOne()
+45943 Ran findOne()
+46981 Ran findOne()
+48020 Ran findOne()
+49060 Ran findOne()
+50098 Ran findOne()
Disable wifi...
+51600 Ran findOne()
Enable wifi...
+68419 Ran findOne()
+69460 Ran findOne()
+70501 Ran findOne()
+71548 Ran findOne()
+72589 Ran findOne()
+73629 Ran findOne()
+74669 Ran findOne()
+75708 Ran findOne()
+76748 Ran findOne()
+77785 Ran findOne()
+78824 Ran findOne()
+79866 Ran findOne()
+80912 Ran findOne()
+81955 Ran findOne()
+82994 Ran findOne()
+84032 Ran findOne()
+85072 Ran findOne()
+86111 Ran findOne()
+87151 Ran findOne()
+88190 Ran findOne()
+89231 Ran findOne()
+90273 Ran findOne()
+91311 Ran findOne()
Disable wifi...
+92666 Ran findOne()
Enable wifi...
+125001 Ran findOne()
+126335 Ran findOne()
+127373 Ran findOne()
+128412 Ran findOne()
+129456 Ran findOne()
+130495 Ran findOne()
+131536 Ran findOne()
+132579 Ran findOne()
Disable wifi...
+134775 Ran findOne()
Enable wifi...
+167160 Ran findOne()
+168479 Ran findOne()
+169521 Ran findOne()
+170569 Ran findOne()
+171607 Ran findOne()
+172647 Ran findOne()
+173686 Ran findOne()
+174731 Ran findOne()
+175770 Ran findOne()
Disable wifi...
Enable wifi...
+207461 Ran findOne()
+208770 Ran findOne()
+209810 Ran findOne()
+210847 Ran findOne()
+211887 Ran findOne()
+212926 Ran findOne()
+213964 Ran findOne()
+215003 Ran findOne()
+216043 Ran findOne()
+217085 Ran findOne()
Disable wifi...
+219429 Ran findOne()
Enable wifi...
+251641 Ran findOne()
+252680 Ran findOne()
+253726 Ran findOne()
+254767 Ran findOne()
+255806 Ran findOne()
+256848 Ran findOne()
+257887 Ran findOne()
+258927 Ran findOne()
Disable wifi...
+259995 Ran findOne()
Enable wifi...
+276807 Ran findOne()
+277845 Ran findOne()
+278883 Ran findOne()
+279949 Ran findOne()
+280989 Ran findOne()
+282026 Ran findOne()
+283063 Ran findOne()
+284102 Ran findOne()
+285140 Ran findOne()
+286178 Ran findOne()
+287219 Ran findOne()
+288258 Ran findOne()
+289297 Ran findOne()
+290337 Ran findOne()
+291377 Ran findOne()
+292420 Ran findOne()
+293458 Ran findOne()
+294498 Ran findOne()
+295539 Ran findOne()
+296579 Ran findOne()
+297619 Ran findOne()
+298657 Ran findOne()
+299698 Ran findOne()
Disable wifi...
+300853 Ran findOne()
Enable wifi...
+333122 Ran findOne()
+334444 Ran findOne()
^C

```

Can you double check that the above script works for you, subbing out for windows specific commands?

**Comment by keithchew** [comment]
Hi @vkarpov15 

Can you please confirm:
- You can see the driver reconnecting to DB
- How long did you run the script for

**Comment by vkarpov15** [comment]
@keithchew yeah I left it running for 5 minutes, and yeah the driver reconnected to the db. If I need to leave the script running for 3 hours to repro the issue then I won't be able to debug it - if I can only try something out once every 3 hours then I'll be working on this issue and nothing else for weeks :)

**Comment by keithchew** [comment]
I would recommend just for the first time, leave it running for 1 day, without any debugging. If it triggers then, we have confirmed the issue, and can plan how to proceed.

**Comment by vkarpov15** [comment]
If there's an uncaught exception, the process will crash and log it anyway. Or does that not happen in your case?

**Comment by keithchew** [comment]
As mentioned above, winston logger was calling the process.exit(), but after we disabled that, the app does not exit. I did not investigate the state of the driver at that point, but I would assume it is in a bad state for the driver, eg reconnects could be broken.

After finding out it is caused by unified topology, I stopped my investigation and switched that off.

**Comment by mogadanez** [comment]
> Interesting.
> 
> It's my understanding that in order for an error to crash the application it has to propagate up to the application and never get caught. One exception that I could think of would be some library in the middle catching the error, and explicitly exiting the process.
> 
> Can you create a [reproduction script](https://stackoverflow.com/help/minimal-reproducible-example) that mimics the network outage, crashing the application even with try/catch, `process.on('uncaughtException');`, `process.on('unhandledRejection');` so we could look deeper into this?


Strange.  requirement to have unhandledRejection looks as  crutch.

since I have  wrapped 

try{
  await 
}
catch(e){

}

It should NOT  throw  error in another  flow.

and also  even if  i provide bufferCommands = false  



It also fall into unhandledRejection handler  with
```
 Cannot call `logEvent.insertOne()` before initial connection is complete if `bufferCommands = false`. Make sure you `await mongoose.connect()` if you have `bufferCommands = false`.
```

**Comment by vkarpov15** [comment]
@mogadanez I don't understand your comment, can you please clarify by providing a script that demonstrates the issue you're seeing?
