### ISSUE TITLE
(node:1124) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by Lucio-Valder** [Automattic/mongoose#8506]
I solved this Issue in my application  using this value in my mongoose connection:

mongoose.connect('mongodb+srv://lucio:<password>@cluster0-6izqv.mongodb.net/test?retryWrites=true&w=majority',{
 useCreateIndex:true,
} );

**Comment by AbdelrahmanHafez** [comment]
Duplicate of https://github.com/Automattic/mongoose/issues/6880

**Comment by vkarpov15** [comment]
https://mongoosejs.com/docs/deprecations.html
