### ISSUE TITLE
Server selection timed out after 30000 ms

### ISSUE THREAD

**Issue by premnath369** [Automattic/mongoose#8511]
**Do you want to request a *feature* or report a *bug*?**
A Bug.

**What is the current behavior?**
i have created the cluster and tried to access it from mongoose and from MonoDB Compass also.
From both places i am getting the following error.

Server selection timed out after 30000 ms

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a New Project
Create a User and for dbaccess, give read & write priviliges
White-list you IP for network access - access from anywhere / give your ip
Create a cluster
get the connection string for application / get the connection string for compass
try to access it

RESULT:
Server selection timed out after 30000 ms

**What is the expected behavior?**
Applicaton or DB Compass should connect to the monodb Cloud.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

express: V4.17.1
mongoose: V5.8.7
Node.js v13.6.0

Screenshots:
---------------------
![image](https://user-images.githubusercontent.com/6087379/72511068-7e9e0800-3870-11ea-9357-5cf6fc62312e.png)

![image](https://user-images.githubusercontent.com/6087379/72511152-a55c3e80-3870-11ea-821b-c7a8ea14cc61.png)

**Comment by vkarpov15** [comment]
Try using the standard connection string (the one that doesn't have `+srv`), that might work.

Also, can you provide some code samples please?

**Comment by AbdelrahmanHafez** [comment]
We've been getting this error (seemigly) randomly lately, I'll provide any more information if/when we can consistently reproduce the issue.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez if you do, please open a separate issue and follow the issue template.
