### ISSUE TITLE
$gt and $lt isn't working properly with dates.

### ISSUE THREAD

**Issue by KevinEdry** [Automattic/mongoose#8513]
Hey,
I am trying to figure out how to find all documents that have have updated in a 5 min period.
my query is quite simple:
`
{
  updatedAt:{
     $gt : new Date(Date.now() - 60 * 5 * 1000).toISOString()
  }
}
`
When I load it in Studio3t it wraps the date with ISODate and I am getting back a correct result, but when I am trying to run it with within nodejs it doesn't find any documents. from my research in js the only way to achieve ISODate that is with new Date, and I tried every combination possible to make this work.

I am stating to believe that this is an issue with mongoose, can anyone elaborate on this issue?

**Comment by KevinEdry** [comment]
Issue still persists

**Comment by cfgs** [comment]
Have you find a solution for this? Having the same issue.
