### ISSUE TITLE
Trying to convert ObjectId to a string

### ISSUE THREAD

**Issue by Herkina** [Automattic/mongoose#8515]
I am trying to convert ObjectId to a string. I fail to do so when trying .toString from the mongo shell in Ubuntu, I also have tried it on cmd, this failed also.
https://prnt.sc/qoskxs
This is the result I want from making a new document.

**Comment by Ncifra** [comment]
You are not giving much context, most likely you are not using `mongoose` at all.

**Comment by vkarpov15** [comment]
Please follow the issue template next time. I don't see any mention of Mongoose, it looks like your issue is with the MongoDB shell.
