### ISSUE TITLE
Document authSource option

### ISSUE THREAD

**Issue by harrisoff** [Automattic/mongoose#8517]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
MongoError: Authentication failed. But I could connect to the server with MongoDB Compass using the same username and password.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose');
function connectDB() {
  const databaseOption = {
    // useNewUrlParser: true,
    // useUnifiedTopology: true,
    auth: { authdb: 'admin', user: 'admin', password: 'mypassword' },
  };
  return new Promise((resolve, reject) => {
    mongoose.connect(
      'mongodb://ip:27017/db',
      databaseOption,
      async (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      },
    );
  });
}

connectDB()
  .then(() => {
    console.log('done');
  })
  .catch((err) => {
    console.error(err);
  });
```

**What is the expected behavior?**
Connected to mongodb server.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v12.13.1
mongoose v5.8.7
mongodb v4.2.2

**Comment by harrisoff** [comment]
The following didn't work either, which I believe is basically the sample given in the [document](https://mongoosejs.com/docs/connections.html#connections).
```js
function connectDB() {
  const databaseOption = {
    useNewUrlParser: true,
  };
  return new Promise((resolve, reject) => {
    mongoose.connect(
      'mongodb://admin:mypassword@ip:27017/db',
      databaseOption,
      async (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      },
    );
  });
}
```

**Comment by Ncifra** [comment]
Be sure not to have any special characters in the password that may need escaping. In that case it would be better to provide the password as a parameter inside the above `databaseOption` object.

**Comment by harrisoff** [comment]
Now it works.
```js
function connectDB() {
  const databaseOption = {
    useNewUrlParser: true,
    useUnifiedTopology: true
  };
  return new Promise((resolve, reject) => {
    mongoose.connect(
      'mongodb://admin:mypassword@ip:27017/db?authSource=admin',
      databaseOption,
      async (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      },
    );
  });
}
```
It seems that the key point is `authSource` in the query string. But this option is not mentioned in the document. I wonder why other codes did not work.
@Ncifra There are only numbers and normal english letters in my password.

**Comment by Ncifra** [comment]
That depends though on the type of user you are using, and where it was created. I think that by default it searches for users on the same database you have specified, sort of a database level user scope.

**Comment by vkarpov15** [comment]
We'll add `authSource` to the docs. [Here's some more info on the `authSource` option](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource). 

Also, I hate to be pedantic, but your `connectDB()` function is pretty clumsy:

```javascript
return new Promise((resolve, reject) => {
    mongoose.connect(
      'mongodb://admin:mypassword@ip:27017/db?authSource=admin',
      databaseOption,
      async (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      },
    );
  });
```

Please never make a callback `async`, that just leads to [unhandled promise rejections](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html). Furthermore, [`mongoose.connect()` returns a promise](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-connect), so there's no need for the additional code gymnastics. All you really need is:

```javascript
return mongoose.connect(
      'mongodb://admin:mypassword@ip:27017/db?authSource=admin',
      databaseOption);
```

**Comment by harrisoff** [comment]
@vkarpov15 
Thanks for your attention.
BTW I didn't mean to be pedantic, this is a fragment I copied from a project.

**Comment by harrisoff** [comment]
@vkarpov15 
Though it worked with username/password/authSource in the URL, is it a correct way to provide them in the options object?
Error message: Server selection timed out after 30000 ms.
Error reason: password must be a string.
```js
mongoose.connect(
  'mongodb://ip:27017/db',
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    user: 'admin',
    password: 'mypassword'
  }
);
```

**Comment by vkarpov15** [comment]
@harrisoff try `pass` instead of `password` as documented here: https://mongoosejs.com/docs/connections.html#options .

I would usually recommend putting username and password in the connection string, that makes it easier to connect to different mongodb instances for dev/prod.
