### ISSUE TITLE
findOneAndUpdate with pipline not updating 'updatedAt' and '__v'

### ISSUE THREAD

**Issue by lchimaru** [Automattic/mongoose#8524]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Whenever I use pipeline array instead of old `{ $set: { ...values } }` object as `update` argument, `__v` and `updatedAt` of document is not bumped.

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute findOneAndUpdate for model based on following schema: 
```ts
const BlogPost = new Schema({
  title: String
}, { timestamps: true });

const BlogPostModel = mongoose.model('BlogPost', BlogPost);
const post = new BlogPost({ title: 'a' });
await post.save();
await sleep(5000);
const updatedPost = await BlogPostModel.findOneAndUpdate({ title: 'a' }, [{ $set: { title: 'b' } }], { new: true });

// updatedPost.__v is 0
// updatedPost.updatedAt is the same as updatedPos.createdAt
```
**What is the expected behavior?**
`updatedAt` and `__v` should act the same not matter if update document or aggregation pipeline is passed.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 9.9.0 
mongoose - 5.8.9
mongo - 4.2.1

**Comment by vkarpov15** [comment]
Fixed for timestamps.

As of MongoDB 4.2, there's no way for an update pipeline to cause an increment of `__v` - you can't use `$pull` with update pipelines. Also, unfortunately, since update pipelines don't support `$setOnInsert` yet, there's no way for us to set `__v` when doing an upsert with update pipelines.
