### ISSUE TITLE
TypeError: Cannot read property 'namespace' of undefined     at Object.get [as dbName] 

### ISSUE THREAD

**Issue by amitbarik167** [Automattic/mongoose#8528]
Getting error 
TypeError: Cannot read property 'namespace' of undefined     at Object.get [as dbName]  when calling mongoose (const mongoose = require('mongoose');)  in a model. This occurs during nodejs debgging through nodemon in visual studio code. 
<img width="956" alt="MongooseError" src="https://user-images.githubusercontent.com/28583117/72962907-ea9dd600-3d72-11ea-8489-78725f4fff58.png">

This error comes in node_modules\mongodb\lib\collection.js.

**Comment by vkarpov15** [comment]
Can you please provide code samples?

**Comment by amitbarik167** [comment]
I am using visual studio code 1.41.1
Nodejs version - v12.13.0
Mongoose version - 5.8.9
MongoDB version - 4.2.2

Its failing here in the model.

const mongoose = require('mongoose');

const ProductCategorySchema = mongoose.Schema
    ({
        productCategoryCode:String,
        productCategoryName: String,
        productCategoryDesc: String
    },
        {
            timestamps: true
        }
    )

module.exports = mongoose.model('ProductCategory', ProductCategorySchema)


The above model is called from controller.

const ProductCategory = require('../models/product-category.model.js');
exports.create = (req, res) => {

    // Validate request
    if (!req.body.content) {
        return res.status(400).send({
            message: "product category content can not be empty"
        });
    }

    // Create a product category
    const productCategory = new ProductCategory({
        productCategoryCode: req.body.productCategoryCode,
        productCategoryName: req.body.productCategoryName || "Untitled product category",
        productCategoryDesc: req.body.productCategoryDesc
    });

    // Save Note in the database
    productCategory.save()
        .then(data => {
            res.send(data);
        }).catch(err => {
            res.status(500).send({
                message: err.message || "Some error occurred while creating the Product Category."
            });
        });
};

exports.findAll = (req, res) => {
    ProductCategory.find().then(productCategories => {
        res.send(productCategories);

    }).catch(err => {
        res.status(500).send({
            message: err.message || "Some error occurred while retrieving product categories."
        });
    });
};

exports.findOne = (req, res) => {
    ProductCategory.findById(req.params.productCategoryId).then(productCategory => {

        if (!productCategory) {
            return res.status(404).send({
                message: "product category not found with productCategoryId " + req.params.productCategoryId
            });
        }
        res.send(productCategory);

    }).catch(err => {
        if (err.kind === 'ObjectId') {
            return res.status(404).send({
                message: "product category not found with productCategoryId " + req.params.productCategoryId
            });
        }
        return res.status(500).send({
            message: "Error retrieving product category with productCategoryId " + req.params.productCategoryId
        });
    });
};

exports.update = (req, res) => {

    if (!req.body.content) {
        return res.status(400).send({
            message: "product category cannot be empty for update"
        });
    }

    ProductCategory.findByIdAndUpdate(req.params.productCategoryId, {
        productCategoryCode:req.body.productCategoryCode,
        productCategoryName: req.body.productCategoryName || "untitled product category",
        productCategoryDesc: req.body.productCategoryDesc

    }, { new: true }).then(productCategory => {

        if (!productCategory) {
            return res.status(404).send({
                message: "Product Category not found with id " + req.params.productCategoryId

            });
        }
        res.send(productCategory)

    }).catch(err => {
        if (err.kind === 'ObjectId') {
            return res.status(404).send({
                message: "Product Category not found with id " + req.params.productCategoryId
            });
        }
        return res.status(500).send({
            message: "Error updating product category with id " + req.params.productCategoryId
        });
    });
};


The controller is called from route

module.exports = (app) => {
    const productCategory = require('../controllers/product-category.controller.js');
    // Create a new product category
    app.post('/productCategory', productCategory.create);

    // Retrieve all product category
    app.get('/productCategory', productCategory.findAll);

    // Retrieve a single product category with productCategoryId
    app.get('/productCategory/:productCategoryId', productCategory.findOne);

    // Update a product category with productCategoryId
    app.put('/productCategory/:productCategoryId', productCategory.update);

    // Delete a product category with productCategoryId
    //app.delete('/productCategory/:productCategoryId', productCategory.delete);

}

The route is called from server.js 

const express = require('express');
const bodyParser = require('body-parser');


//create express app
const app = express();

// parse requests of content-type - application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }))

// parse requests of content-type - application/json
app.use(bodyParser.json())

// define a simple route
app.get('/', (req, res) => {
    res.json({"message": "Welcome to Doorstep application."});
});

//require product category routes
require('./src/app/routes/product-category.routes.js')(app);

// listen for requests
app.listen(3000, () => {
    console.log("Server is listening on port 3000");
});

// Configuring the database
const dbConfig = require('./config/database.config.js');
const mongoose = require('mongoose');

mongoose.Promise = global.Promise;

// Connecting to the database
mongoose.connect(dbConfig.url, {
    useNewUrlParser: true, useUnifiedTopology: true
}).then(() => {
    console.log("Successfully connected to the database");    
}).catch(err => {
    console.log('Could not connect to the database. Exiting now...', err);
    process.exit();
});

**Comment by amitbarik167** [comment]
@vkarpov15  - 

> Can you please provide code samples?

@vkarpov15  - Done

**Comment by vkarpov15** [comment]
No major problem here, your debugger shows that this is a caught error. But I figure if we avoid unnecessary caught errors, that can make debugging easier, so the fix will be in v5.8.11 :+1:
