### ISSUE TITLE
"Can't validate() the same doc multiple times in parallel" erroneously thrown

### ISSUE THREAD

**Issue by taxilian** [Automattic/mongoose#8531]
**Do you want to request a *feature* or report a *bug*?**
This is a bug

**What is the current behavior?**
I haven't tested enough to be certain what all different cases can reproduce this, but the case I tried was starting with a document  with a single nested path inside a document in an array inside a document inside an array, if you modify the contents of that nested path document and then save() the document you will get this error:

Can't validate() the same doc multiple times in parallel.

In our code we are updating the doc like this:

            const q: any = assn.answer_keys[0].questions[0];
            q.clip = {rows: 1, row_height: 3.5};

The error is occuring on the "clip" subdocument.

From digging in it seems to be calling the validator twice on that path, once as "questions.0.clip" and then again as "clip" -- but either the second time occurs as part of the validation for the first (async nesting) or else the first is never calling the callback because when it gets called a second time the validation error has not been cleared yet.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can run the unit test from https://github.com/taxilian/mongoose/tree/feature/validate_in_parallel_issue

or the gist https://gist.github.com/taxilian/0dc71f915eded06eed74112146de7887

**What is the expected behavior?**
It should save and not throw an exception =]

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node.js 10.17.0, mongoose 5.8.9

----

I will try to fix this myself, but if you have any suggestions on how to do it I'd appreciate it. I don't know if you frequent any discords or anything where I could get some suggestions. I've been hunting this through async stack traces for about 8 hours now.

**Comment by jnardone** [comment]
This may be related to the late comments in #8486 as well.

**Comment by taxilian** [comment]
I hadn't seen that one, but I almost guarantee it. Fixed in #8532

**Comment by taxilian** [comment]
I'm not sure how to address the build issues; they don't seem to be related to my pull request changes and are only on some versions of node
