### ISSUE TITLE
{ useUnifiedTopology: true } leads to MongoDB connection error: MongoTimeoutError: Server selection timed out after 30000 ms

### ISSUE THREAD

**Issue by PBrunoCyber** [Automattic/mongoose#8537]
Yesterday, the mongoose was working perfectly, but today it is unable to carry out any type of transaction. When I remove {useUnifiedTopology: true} or set it to false, it creates another problem, saying that it is necessary to make the connection, but when it is added, it generates the problem that is in the title. 

` UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms at new MongooseTimeoutError  `

My connection
`mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true });`

When I set useUnifiedTopology to false

`DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

**My ip has already been added to mongodb, but the problem still persists.**

**Comment by jloveridge** [comment]
@PBrunoCyber that deprecation warning is coming from the underlying MongoDB driver, as is the connection error, we too have seen some issues connecting to certain MongoDB deployments using their new unified topology server selection process, which actually seems to be more common than I think the MongoDB team anticipated. Your issue should be logged with them as it is not a mongoose specific issue.

**Comment by vkarpov15** [comment]
Are you using Atlas? Also, can you please clarify what you mean by "it creates another problem, saying that it is necessary to make the connection"?

You can feel free to turn off `useUnifiedTopology` for now and ignore the deprecation warning if it is causing you issues in production.

**Comment by PBrunoCyber** [comment]
I managed to solve it, it was really a mongoDB problem. He was not allowing to create another ip in the access to the network, but now it is working normally.

For those who are in the same situation, this problem is caused because their (dynamic) ip is different from the ip configured in mongoDB.

**To resolve this, you need to access the network access on mongoDB, delete the configured ip and add a new ip (your current ip).**
