### ISSUE TITLE
'this' in instance method is undefined when called from another instance method.

### ISSUE THREAD

**Issue by guptaamol** [Automattic/mongoose#8541]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
So i have a mongodb document with multiple methods. The methods work fine when called independently, but i am facing problem when calling from another method of the same document.

here is some sample code.

    const userGroupSchema = {
        ...define schema;
    };

    userGroupSchema.methods.findUser = async function(){
        ...findUserLogic
    };

    userGroupSchema.methods.updateUser = async function(){
        const { findUser } = this;
        const user = await findUser()
        ...updateUserUserLogic
    };

**What is the expected behavior?**
So when i do `userGroupDocument.findUser()` everything works fine, ie `this` has the correct values,  
but when is call `userGroupDocument.updateUser` , `updateUser` calls `findUser`, `this` in `findUser` is now `undefined`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"node": "v10.17.0"
"mongoose": "5.8.10"
"mongodb":"4.2.1"

**Comment by guptaamol** [comment]
I'm sorry this was my bad should have bound the function to the object context.
Thanks anyway

**Comment by vkarpov15** [comment]
You're [losing function context](https://masteringjs.io/tutorials/fundamentals/this). Don't destructure `this` :+1:
