### ISSUE TITLE
(node:18220) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

### ISSUE THREAD

**Issue by DaxDupont** [Automattic/mongoose#8549]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Even with the right connection settings the deprecationwarning is given

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const dbURL = format('mongodb://%s:%s@localhost:27017/%s?authMechanism=%s',
	user, password, dbName, authMechanism);

mongoose.connect(dbURL, {useNewUrlParser: true, useFindAndModify: false, useCreateIndex: true, useUnifiedTopology: true}).then(() => {
	console.info("DB connected");
}).catch(err => console.error(err));
```

**What is the expected behavior?**
To not show with the useUnifiedTopology set to true
(node:18220) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js v12.14.1.
MongoDB version v4.0.15
mongoose: "5.8.10"

**Comment by DaxDupont** [comment]
PS: when run on my linux environment it seems to be working fine.
On my windows environment the warning happens.

**Comment by jloveridge** [comment]
@DaxDupont This is not related to mongoose. As I have mentioned in every other issue filed by someone for this same concern it is a mongodb driver change and the warning is being generated by them, not mongoose. If you have a problem with the messaging, or even with the ideal of them changing the way server discovery works address it with them. Also it would be nice if you had searched for similar issues before filing a ticket since this has been asked and answered multiple times.

**Comment by lineus** [comment]
@DaxDupont the following script works without deprecation warnings, can you try it out in your windows environment and see if you have a different outcome? 

```js
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8549';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'test1' });

async function run() {
  assert.strictEqual(mongoose.version, '5.8.10');
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  console.log('all assertions pass.');
  await connection.close();
}

run();

```

In your code, are you using any plugins that also create connections to mongodb? This is often a secondary source of deprecation warnings ( forgetting to pass all options to plugin connections ).

**Comment by DaxDupont** [comment]
@jloveridge to be fair i got like a bazillion results and most of them said just add the flag
@lineus will double check
