### ISSUE TITLE
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

### ISSUE THREAD

**Issue by yugansh-dhir** [Automattic/mongoose#8550]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
throwing error
**If the current behavior is a bug, please provide the steps to reproduce.**

var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/catApp', {useNewUrlParser: true});
mongoose.set('useUnifiedTopology', true);

**What is the expected behavior?**
it should work

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
 "mongoose": version: "5.8.10

**Comment by jloveridge** [comment]
@yugansh-dhir as I mentioned in the last issue that someone posted regarding this exact deprecation message an error isn't being thrown, a warning is being logged by the MongoDB driver. This is not a mongoose issue. You should address driver complaints to the MongoDB drivers team.

**Comment by lineus** [comment]
@yugansh-dhir @jloveridge in this case the deprecation warning is the direct result of calling `mongoose.set()` **after** calling `mongoose.connect()`. 

By the time that `.set()` is called the MongoDB driver has already begun the connection process and the warning will be displayed. 

Either switch the order of operations ( call `.set()` before `.connect()` )
or pass both options in with the connection options object.
