### ISSUE TITLE
Bug: pre hook 'deleteOne' with document: true doesn't refers to document

### ISSUE THREAD

**Issue by maxsimych** [Automattic/mongoose#8555]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Documentation of mongoose says:

[Mongoose Schema-pre](https://mongoosejs.com/docs/api.html#schema_Schema-pre)
> Schema.prototype.pre():
> Parameters:
> The «String|RegExp» method name or regular expression to match method name
> [options] «Object»
> **[options.document] «Boolean» If name is a hook for both document and query middleware, set to true to run on document middleware.**
> [options.query] «Boolean» If name is a hook for both document and query middleware, set to true to run on query middleware.
> callback «Function»

And also about pre hook "deleteOne":
[Mongoose Middleware](https://mongoosejs.com/docs/middleware.html)
> Document middleware is supported for the following document functions. In document middleware functions, this refers to the document:
> **...deleteOne**
> 
> Query middleware is supported for the following Model and Query functions. In query middleware >functions, this refers to the query:
> **...deleteOne**

So, deleteOne is in Document and Query hook, now let's try to use this.

**Result: this refers to Query, not to Document.**
**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
mySchema.pre('deleteOne', { document: true }, function(next) {
  console.log(this)
  next()
})
```

**What is the expected behavior?**

Refers to Document

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 13.6.0
Mongoose: 5.8.10
MongoDB: 3.5.2

**Comment by maxsimych** [comment]
Oh, it is my bad, now I understand, that only in request document#deleteOne this refers to document.
It seems not clear from Docs, please, could somebody fix it a little, with more explanation. Thank you!

**Comment by vkarpov15** [comment]
Right now you need to explicitly set `query` to `false`:

```javascript
mySchema.pre('deleteOne', { document: true, query: false }, function(next) {
    console.log('This:', this)
    next()
  });
```

We'll add some improvements to the docs and make it so that you don't need to set `query: false` :+1:

**Comment by harveyconnor** [comment]
@vkarpov15 
I'm trying to call this hook and it doesn't appear to be calling. Using mongoose 5.9.12.
The typescript definitions don't let me put that options object in-between the method and callback.
```ts
schema.pre<IGroup>('deleteOne', { document: true, query: false }, function cleanup(next) {
  console.log('This:', this);
  next();
});
```
