### ISSUE TITLE
keep $locals when Model.create(), new Model and Document.set()

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#8561]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
To be able to use the ```$locals``` in my documents I need to be able to set it when I create a new Document, use ```Model.create()``` or ```Document.set()``` after retrieve... now in neither case it's possible.

This is because I get POJO from my frontend, and in there I define some behavior and I use ```Document.set()``` to validate the props I'm adding to the document.

Before $locals I've to **add** this properties directly to the Document, now I use $locals but this property is deleted when assigned to a new Document.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
"use strict";
const mongoose = require("mongoose");
const {Schema, model} = mongoose;
mongoose.connect("mongodb://localhost/test").then(() => {
  let test = new Schema({
    test: {
      type: Number
    }
  });
  let Test = model("Test", test);
  let template = {test: 1, $locals: {a: 1}};
  let t1 = new Test(template);
  console.log("new Test", t1.$locals);
  t1.set({
    $locals: {b: 2}
  });
  console.log("t1 set locals", t1.$locals);
  t1.$locals = {c: 3};
  console.log("t1 assign locals", t1.$locals);
  t1.save().then(t1 => console.log("t1 save", t1.$locals));
  Test.create(template).then(t2 => console.log("Test Create", t2.$locals));
});
```
**What is the expected behavior?**
I've a plugin that allows me to **update** refs documents and subdocuments, and other plugin that complements the document with the creation and update user, model, and date, so for me it's not just assign the $locals from POJO, because I could have several nested subdocuments and refs, and as this is a mongoose feature, I think I'll be nice if the mongoose functions allows to **keep** $locals by them selves... 
 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v12.14.1
mongoose: 5.8.11
mongodb: 4.2.3

**Comment by vkarpov15** [comment]
This is by design - `$locals` is meant to always contain program data. So if we allow you to set `$locals` when you do `new Model(req.body)`, that would allow malicious users to set values in `$locals`.

If you want something like `$locals` that you can set from `new Model()`, just create a new virtual:

```javascript
schema.virtual('_locals').get(function() { return this.$locals; }).set(function(v) { this.$locals = v; });
```

**Comment by chumager** [comment]
Hi, sure that way someone can inject malicious code, but to do that they must know what to inject and the circumstances where to inject it... like almost every interaction with the final user... that's a developer obligation to avoid it, not a module design pattern, for example, I don't allow any modification of data my lib doesn't send previously.

Either way thanks for the answer.

**Comment by vkarpov15** [comment]
I disagree. Part of Mongoose's goal is to sanitize user data and take as much of that load off of the developer as is reasonably possible. But if you want to potentially store user data in `$locals`, the workaround with virtuals works :+1:

**Comment by chumager** [comment]
Hi, for sure you must disagree, I guess that's why you develop it that way.

My point is this is the same behavior of set an injected json from a malicious user. If a hacker tries to change the data my Back End receives, it's the developer responsibility to verify that. The same should happens with $locals...

It's like ***I've to enforce the use of $locals, but it's a developer responsibility to enforce ```Document.create()```***

Do you get my point?

Regards...

**Comment by vkarpov15** [comment]
I'm afraid I don't get your point.
