### ISSUE TITLE
Connection fails when one node in replica set is down! Update Mongo driver

### ISSUE THREAD

**Issue by AguGriguol** [Automattic/mongoose#8563]
Hi!

I have a problem with the useUnifiedTopology: true parameter when one node in replicaset is down. The 3.5.0 version of mongo driver should fix this issue. Can you update the library?

https://jira.mongodb.org/browse/NODE-2407?jql=text%20~%20%22useUnifiedTopology%22

Thanks

**Comment by vkarpov15** [comment]
We're planning on releasing 5.9.0 with v3.5.0 of the mongodb driver today :+1:
