### ISSUE TITLE
current url string parser is deprecated

### ISSUE THREAD

**Issue by wongsn78** [Automattic/mongoose#8564]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
https://mongoosejs.com/docs/deprecations.html#the-usenewurlparser-option
