### ISSUE TITLE
mongo db connection reset not handled with mongoose connection

### ISSUE THREAD

**Issue by mike-j-gibson** [Automattic/mongoose#8570]
Cant handle a connection reset using a mongoose connection to a mongo database. With the code below, if the database connection gets reset or disconnected, the app will just crash with a message below. I do hit the connection.on('disconnected..., but not the catch statement.
------------------------------------------------------------
mongoose@5.8.11
mongo db version v4.0.9
---------------------------------------------------------
const mongoose = require("mongoose");
var connection = mongoose.connection;
connection.on('open', function ()
{
    console.log('connected.');
});
connection.on('error', error =>
{
    console.log('Error: connection failed!' + error );
});
connection.on('disconnected', error =>
{
    console.log('Error: disconnected!' + error);
});

mongoose.connect('mongodb://localhost:27017/testDB', { useNewUrlParser: true, useUnifiedTopology: true  } )
    .catch(error => {
        console.log('Error catch:' + error);
    }) ;

The error message is:

Error: Mongo database disconnected!
undefined
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Connection instance at:
    at Socket.<anonymous> (C:\........api\node_modules\mongoose\node_modules\mongodb\lib\core\connection\connection.js:340:10)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by overhead525** [comment]
I was able to get the following code to fire when I used MongoDB 4.2:

`connection.on('reconnect', () => {
    console.log("reconnected!");
});`

I'm currently switching to 4.0 to further replicate your issue, but I was wondering if there was anything keeping you from upgrading to version 4.2?

**Comment by mike-j-gibson** [comment]
Upgraded to mongo 4.2.  Still crashing.  
To clarify,  the app crashes when the mongo server is stopped or shutdown.  I am not asking about reconnecting.  I just want to keep the app from crashing.

**Comment by vkarpov15** [comment]
I'm unable to repro your issue, the below script shows a clean exit in nodemon:

```javascript
const mongoose = require("mongoose");
var connection = mongoose.connection;
connection.on('open', function ()
{
console.log('connected.');
});
connection.on('error', error =>
{
console.log('Error: connection failed!' + error );
});
connection.on('disconnected', error =>
{
console.log('Error: disconnected!' + error);
});

mongoose.connect('mongodb://localhost:27017/testDB', { useNewUrlParser: true, useUnifiedTopology: true, serverSelectionTimeoutMS: 1000 } )
.catch(error => {
console.log('Error catch:' + error);
}) ;

```

Nodemon output:

```
$ ./node_modules/.bin/nodemon --config ./nodemon.config.json ./gh-8570.js 
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): 
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./gh-8570.js`
Error: disconnected!undefined
Error catch:MongooseTimeoutError: Server selection timed out after 1000 ms
Error: connection failed!MongooseTimeoutError: Server selection timed out after 1000 ms
[nodemon] clean exit - waiting for changes before restart


```

`nodemon.config.json` is as shown below because I was getting an ENOSPC error:

```
{
  "watch": false
}
```
