### ISSUE TITLE
Error in cursor stream is never triggered when primary change in replicaset

### ISSUE THREAD

**Issue by AguGriguol** [Automattic/mongoose#8578]
Hi!

The error event is never triggered when the replicaset change the primary, consequently my flow stops receiving events. My config:
No event, connection or stream is triggered.

`mongoose.connect(mongodb://xxxx:xxxx@manager-database-0.manager-database.default.svc.cluster.local,manager-database-1.manager-database.default.svc.cluster.local/managerdb?replicaSet=rs0, {"useNewUrlParser": true, "useCreateIndex": true, "useUnifiedTopology": false })`

`['connecting', 'connected', 'open', 'disconnecting', 'disconnected', 'close', 'reconnected', 'error', 'fullsetup'].forEach(function(name) {
  mongoose.connection.on(name, function(err) {
    console.log('Mongoose event: ' + name + err);
  });
});`

`
        const stream = Event.find(filter).setOptions(opts).cursor();
        stream.on('data', onEvent);
        stream.on('error', onError);
        stream.on('close', onClose);`

**Comment by vkarpov15** [comment]
First of all, you aren't using a [change stream](https://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html). You're using a [cursor as a stream](https://thecodebarbarian.com/cursors-in-mongoose-45), which is a different concept.

Also, I'm unable to repro this issue. I get an error event if I `rs.stepDown()` the primary when the below script is running.

```javascript
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs', {
    useNewUrlParser: true,
    useUnifiedTopology: false
  });
  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  for (let i = 0; i < 100; ++i) {
    await Model.create({ name: `test${i}` });
  }
  
  const stream = Model.find({ $where: 'sleep(500) || true' }).setOptions({ batchSize: 1 }).cursor();
  stream.on('data', doc => console.log('Data', doc));
  stream.on('error', err => console.log('Err', err));
  stream.on('close', () => console.log('Close'));
}
```

Output:

```
$ node ./gh-8578.js 
(node:41472) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Data { _id: 5e66e172515b68a200025cfa, name: 'test0', __v: 0 }
Data { _id: 5e66e172515b68a200025cfb, name: 'test1', __v: 0 }
Data { _id: 5e66e172515b68a200025cfc, name: 'test2', __v: 0 }
Data { _id: 5e66e172515b68a200025cfd, name: 'test3', __v: 0 }
Data { _id: 5e66e172515b68a200025cfe, name: 'test4', __v: 0 }
Data { _id: 5e66e172515b68a200025cff, name: 'test5', __v: 0 }
Data { _id: 5e66e172515b68a200025d00, name: 'test6', __v: 0 }
Data { _id: 5e66e172515b68a200025d01, name: 'test7', __v: 0 }
Data { _id: 5e66e172515b68a200025d02, name: 'test8', __v: 0 }
Data { _id: 5e66e172515b68a200025d03, name: 'test9', __v: 0 }
Err { MongoNetworkError: connection 0 to localhost:27017 closed
    at Socket.<anonymous> (/Users/val/Workspace/MongoDB/mongoose/node_modules/mongodb/lib/core/connection/connection.js:372:9)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: { isGetMore: true } }
^C
$ 
```

Can you please modify the above script to demonstrate your issue?
