### ISSUE TITLE
Should be able to specify options for $unwind

### ISSUE THREAD

**Issue by jloveridge** [Automattic/mongoose#8594]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
When building an aggregation it isn't possible to use `.unwind()` to specific options such as `preserveNullAndEmptyArrays`.

**What is the expected behavior?**
Should be able to specify both `includeArrayIndex` and `preserveNullAndEmptyArrays` options for an unwind operation.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

*node:* 10.18.1
*mongoose:* 5.8.11
*mongodb:* 4.2.2

**Comment by vkarpov15** [comment]
We fixed this a long long time ago in #4239, it just looks like the docs are out of date. Will fix for 5.9.2 :+1:
