### ISSUE TITLE
Parallel validation error thrown in post validate hook if re-validating

### ISSUE THREAD

**Issue by m-weeks** [Automattic/mongoose#8597]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I just recently upgraded from 5.8.4 to 5.9, and the new Parellel validation error that was added in 5.8.5 is causing issues with some functionality I have.

When calling `this.validate` in a post validate hook, a Parallel validation error will be thrown. My guess is because `this.$__.validating` must still be set while the hook is running.

I'm not sure if this would be the desired behavior, what do you think? Perhaps the way I am writing the functionality would be better done another way, but I hadn't really thought of one.

**If the current behavior is a bug, please provide the steps to reproduce.**

Given a schema:
```
var EmployeeSchema = new Schema({
  name: {
    type: String,
    required: true,
  },
  employeeNumber: {
    type: String,
    validate: {
      validator: function() { return v.length > 5; },
      message: function(props) {
        return `${props.path} must be 5 characters long'`;
       }
    }
  }
});
```

For theoretical purposes similar to mine, let's say employeeNumber must be retrieved from an external API. This is how I have done it:

```
EmployeeSchema.post('validate', async function() {
  if (!this.employeeNumber && !this._employeeNumberRetrieved) {
    this.employeeNumber = await getEmployeeNumberFromApi(this.name);
    this._employeeNumberRetrieved = true;
    await this.validate();
  }
});
```

In my case, it isn't ideal to fetch this data if the other fields are invalid, because it's just going to get thrown out anyway, which is why I am doing it in a post validate hook. But I need to handle the case where if something about the returned employee number is invalid, which is why validation would need to be repeated.

**What is the expected behavior?**

A document should be able to be re-validated in a post('validate') hook

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 10.16.0
Mongoose 5.9.0
Mongodb 4.0.6

**Comment by vkarpov15** [comment]
Fix will be in v5.9.2. No reason that we can't allow calling `validate()` in `post('validate')` middleware since by the time post validate middleware runs, we've already copied over validation errors so you can use [`Document#invalidate()`](https://mongoosejs.com/docs/api/document.html#document_Document-invalidate) again.
