### ISSUE TITLE
import twstock.....

### ISSUE THREAD

**Issue by victorchenwei** [Automattic/mongoose#8600]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
@victorchenwei 
Welcome, and thanks for reporting an issue!

Please follow the [new issue format](https://github.com/Automattic/mongoose/issues/new), where most of the information is expected to be in the issue body, and the title is more of a quick description to the issue.

**Comment by lineus** [comment]
This doesn't appear to have anything to do with mongoose. I am moving the previous title to this comment for posterity's sake, and closing this issue. @victorchenwei please follow the issue template as described by @AbdelrahmanHafez.  

import twstock import requests  ifttt_key = 'blQjewWHZpmVZjsm_Q1234' #申請專屬的 webhooks ID event = 'stockLine' # IFTTT 建立的事件名稱 url_ifttt = 'https://maker.ifttt.com/trigger/{}/with/key/{}'.format(event,ifttt_key) #觸發 IFTTT 的 webhooks 網址  real = twstock.realtime.get('2330') #取出台積電股票 即時資料 if real['success']: #如果成功 True 抓取資料 realprice = real['realtime']['latest_trade_price'] #取出 即時目前股價 if float(realprice) > 290: #價股如果 大於 290元 就用 line 通知我 print('台積電超過290元:' + realprice) url_ifttt += '?value1=' + str(realprice) #觸發 IFTTT 的 webhooks 事件 來呼叫 line,並顯示即時目前股價 res = requests.get(url_ifttt) #對 網站伺服器發出請求,即:觸發 IFTTT 的 webhooks 事件 來呼叫 line,並顯示即時目前股價 print(res.text) else: print("抓不到股價資料:" + real['rtmessage'])
