### ISSUE TITLE
Update docs about bufferCommands to take into account useUnifiedTopology

### ISSUE THREAD

**Issue by Vignesh-01** [Automattic/mongoose#8604]
I am using MongooseJs for creating and reading database. I need my Mongoose to display the DB connection errors immediately on requests. but mongoose keeps buffering the connection errors. I also tried setting bufferCommands to false. but no luck...Is there any other method available?

I am using mongoose v5.8.13 and node v10.16.0

Thanks in advance

**Comment by AbdelrahmanHafez** [comment]
Could you provide more information on how you want mongoose to display connection errors immediately on requests?

AFAIK bufferCommands buffers all operations until a connection is established for the first time.

Perhaps a different solution to your situation would be to use [connection events](https://mongoosejs.com/docs/connections.html#connection-events).

**Comment by Vignesh-01** [comment]
I connect to the database with mongoose in my index.js
`    mongoose.connect(process.env.DB_CONNECT, {
        useUnifiedTopology:true,
        useNewUrlParser: true,
        useCreateIndex: true,
        bufferMaxEntries : 0,
        bufferCommands: false
    });`

And whenever i get a request...I need to send the details from DB or error code in case of errors **IMMEDIATELY** without buffering.

`router.get('/get/deviceDetails', async function (req, res) {      
    deviceMgmtServer.find({}).exec(function (err, deviceMgmtServerDetails) {
        if (err) {
          console.log(err);
          return res.send(err);
        }
        return res.status(200).send(deviceMgmtServerDetails);
     }`
I tried disconnecting the connection from Mongodb and sending the request.But I don't get any error message. It just keeps buffering and sends response once the connection re-established

**Comment by Vignesh-01** [comment]
> Could you provide more information on how you want mongoose to display connection errors immediately on requests?
> 
> AFAIK bufferCommands buffers all operations until a connection is established for the first time.
> 
> Perhaps a different solution to your situation would be to use [connection events](https://mongoosejs.com/docs/connections.html#connection-events).

I also tried connection events. It notifies after 30 seconds of disconnection

**Comment by AbdelrahmanHafez** [comment]
>I also tried connection events. It notifies after 30 seconds of disconnection

You can set connection/socket timeout in [connection options](https://mongoosejs.com/docs/connections.html#options).

**Comment by Vignesh-01** [comment]
> > I also tried connection events. It notifies after 30 seconds of disconnection
> 
> You can set connection/socket timeout in [connection options](https://mongoosejs.com/docs/connections.html#options).

I tried to set connectTimeoutMS and socketTimeoutMS. and it works for timeout on initial connection, but it doesn't work on my get and post request timeout error.

**Comment by vkarpov15** [comment]
@Vignesh-01 that's what the `useUnifiedTopology` option does. The underlying mongodb driver no longer tracks the current state of the connection, it keeps trying to send each operation for `serverSelectionTimeoutMS` milliseconds. If you want to time out after 1 second, you can do this:

```javascript
mongoose.connect(process.env.DB_CONNECT, {
useUnifiedTopology:true,
useNewUrlParser: true,
useCreateIndex: true,
serverSelectionTimeoutMS: 1000, // <-- configure `useUnifiedTopology`
bufferMaxEntries : 0,
bufferCommands: false
});
```

We should update the docs about bufferCommands to explain this.

**Comment by salmanahmad94** [comment]
> @Vignesh-01 that's what the `useUnifiedTopology` option does. The underlying mongodb driver no longer tracks the current state of the connection, it keeps trying to send each operation for `serverSelectionTimeoutMS` milliseconds. If you want to time out after 1 second, you can do this:
> 
> ```js
> mongoose.connect(process.env.DB_CONNECT, {
> useUnifiedTopology:true,
> useNewUrlParser: true,
> useCreateIndex: true,
> serverSelectionTimeoutMS: 1000, // <-- configure `useUnifiedTopology`
> bufferMaxEntries : 0,
> bufferCommands: false
> });
> ```
> 
> We should update the docs about bufferCommands to explain this.

Hey. Hope you're doing well. I tried this but the queries are not failing immediately. I've been using useUnifiedTopology eversince the deprecation warning started to appear but can't seem to test DB failure scenarios since the queries don't fail immediately.

**Comment by vkarpov15** [comment]
@salmanahmad94 correct, they don't fail immediately, they time out after `serverSelectionTimeoutMS`. Please open a new issue if that option doesn't work for you.
