### ISSUE TITLE
[Browser] Document created with data from API call doesn't include populated fields

### ISSUE THREAD

**Issue by lucafaggianelli** [Automattic/mongoose#8605]
**Do you want to request a *feature* or report a *bug*?**
I think this is a bug or I'm missing something from the docs

**What is the current behavior?**
My issue is with `mongoose/browser` package, I created a library to fetch data from a REST API into mongoose Documents. I have a problem with a schema with *refs*, I load data from a REST API, this data is populated server-side (that is, I use the same mongoose schema to build a mongoose model and then call `League.findOne('123').populate('users.user')`), then I create `Document` but the populated fields are stripped off.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here a reproduction link:
https://codepen.io/lucafaggianelli/pen/gOpMLLM?editors=0010

these are the schemas:
```js
const leagueSchema = {
  name: {
    type: String,
    required: true,
    minlength: 2,
    trim: true
  },
  users: [{
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    role: String,
    title: String
  }]
}

const userSchema = {
  email: {
    type: String,
    lowercase: true,
    trim: true,
    required: true,
    match: /\S+@\S+\.\S+/,
    index: true,
    unique: true
  }
}

const leagueData = {
  _id: '5da3707b4d460fb0c2e33fd4',
  name: 'My League',
  users: [
    {
      _id: '5da3707b4d460fb0c2e33fd5',
      user: { id: '5da3707b4d460fb0c2e33fd6', email: 'luca@example.com' },
      role: 'admin',
      title: 'Presidente'
    }
  ]
}

const league = mongoose.Document(leagueData, leagueSchema, 'user')
```

**What is the expected behavior?**
I expect to see the populated field in the `Document`, but `league.users[0].user` is a MongoDB ID, while I loaded a User object with `id` and  `email` fields

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v10.19.0
mongoose: v5.8.10
mongodb

**Comment by vkarpov15** [comment]
Unfortunately there isn't really a good way to do this without introducing a basic notion of models in the browser, so that's what we will do for 5.9.3. In v5.9.3 you'll be able to do this:

```javascript
const User = mongoose.model('User', userSchema);
leagueData.users.forEach(u => {
  u.user = new User(u.user);
});

const league = mongoose.Document(leagueData, leagueSchema);
```

Which is almost exactly how you would do that on the server side.

**Comment by lucafaggianelli** [comment]
Actually, that makes sense, you need the Model... though to make things working I made a workaround, so in a schema, I replace the `{ type: ObjectId, ref: 'User' }` with the actual user schema and it works flawlessly (I know it's ugly):

```js
import Model from './Model'
import schema from 'Schemas/LeagueSchema'
import UserSchema from 'Schemas/UserSchema'

schema.users[0].user = UserSchema // <-- Magic line

export default class League extends Model {
  constructor (data, fields) {
    super(data, schema, fields)
  }

  static route = '/leagues'

  static async findMine (userId) {
    if (!userId) { throw new Error('Please provide a userId in League.findMine()') }

    const leagues = await this.findOne({
      users: { $elemMatch: { user: { _id: userId } } }
    }, {
      populate: 'users.user' // <-- the REST API call returns a populated array of users
    })

    return leagues
  }
}
```

**Comment by vkarpov15** [comment]
Yeah that is a bit messy, but not too different from what we did in https://github.com/Automattic/mongoose/commit/d0ae2ccc009dc9034883e3e9d0d53c92bb3822e5 :)
