### ISSUE TITLE
AWS Lambda has a memory leak with mongoose

### ISSUE THREAD

**Issue by komanton** [Automattic/mongoose#8606]
**Do you want to request a *feature* or report a *bug*?**
I am pretty sure that it is a bug. This bug very important:
Firstly, AWS calculates payments for lamba by multiply it somehow with some proportion memory/CPU. And amount of CPU has a hard dependcy on amount of memory. So, we can not increase memory to mach.
Secondly, lambda code become extremely slow, when lambda richchs a limit of memory due to GC pauses

**What is the current behavior?**
I run my lambda in AWS in conjunction with mongoose. I use this example to create AWS Lambda with mongoose: https://mongoosejs.com/docs/lambda.html I have prepare Lambda handler code below to localize the problem. After running this code, I see in the logs (this is default logs for each lambda, you can find it in CloudWatch in AWS) of AWS that memory holds and encreased until Lambda's context reloads. You can find more about lambda context here: https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html

```import mongoose from "mongoose";

let conn: any = null;

const uri = "mongodb://127.0.0.1:27017/mydb?ssl=false";

export const handler = async (event: any, context: any): Promise<any> => {
  // Make sure to add this so you can re-use conn between function calls.
  // See https://www.mongodb.com/blog/post/serverless-development-with-nodejs-aws-lambda-mongodb-atlas
  context.callbackWaitsForEmptyEventLoop = false;

  // Because conn is in the global scope, Lambda may retain it between
  // function calls thanks to callbackWaitsForEmptyEventLoop.
  // This means your Lambda function doesn't have to go through the
  // potentially expensive process of connecting to MongoDB every time.
  if (conn == null) {
    conn = await mongoose.createConnection(uri, {
      // Buffering means mongoose will queue up operations if it gets
      // disconnected from MongoDB and send them when it reconnects.
      // With serverless, better to fail fast if not connected.
      bufferCommands: false, // Disable mongoose buffering
      bufferMaxEntries: 0, // and MongoDB driver buffering,
      useNewUrlParser: true,
      autoReconnect: true,
      connectTimeoutMS: 30000,
      poolSize: 5,
      reconnectInterval: 1000,
      reconnectTries: 300,
      socketTimeoutMS: 30000,
      useCreateIndex: true,
      useFindAndModify: false
    });
    conn.model('Group', new mongoose.Schema({
      id: String,
      name: String,
      userIds: [String],
      domains: [String],
      type: String,
      adminTenantId: String
    }));
  } else {
    console.log("connection is reused");
  }

  console.log("start");
  // @ts-ignore
  const M = conn.model('Group');

  const doc = await M.find();
  console.log(doc.length);
  console.log(doc[0].name);
  console.log("finish");

  return JSON.stringify(doc);
};
```
I attached by memory profiler to my local node process after this lambda's handler finished with help of this article https://www.alexkras.com/simple-guide-to-finding-a-javascript-memory-leak-in-node-js  (Take heap snapshot) and I found that heap contains a lot of objects (like InternalCache, model, arrays) with my data from DB in comparison with a heap snapshot before the line `const doc = await M.find()`;.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Run the code above
2) Attache by debugger
3) Take memory snapshot before the line `const doc = await M.find();` but after the line ` const M = conn.model('Group');`
4) Continue run
5) Do not kill the process of the node.exe (it emulates AWS Lamda context) 
(Do not put any break points after the line `const doc = await M.find();` - let's give a chance to GC to collect memory
6) Press 'Trash' button in memory profiler (It forces manual Garbage Collection)
7) Take memory snapshot 
8) In memory profiler: load both snapshots. Make 'Comparison' between two snapshots: just find objects: 'InternalCache'

**What is the expected behavior?**
**Expected behavior:** After AWS Lamda Hendler completed (**important: but not the node.exe process**), the memory should be release and all objects from DB **should be Garbage Collected**.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node v10.16.3
MongoDB: 3.6.17
"mongoose": "^5.8.11",

**Comment by vkarpov15** [comment]
Have you tried manually running `gc()`? V8 is pretty lazy about running garbage collection - often times what looks like a memory leak (monotonically increasing memory usage) is just a case of V8 not running garbage collection.

**Comment by komanton** [comment]
> Have you tried manually running `gc()`? V8 is pretty lazy about running garbage collection - often times what looks like a memory leak (monotonically increasing memory usage) is just a case of V8 not running garbage collection.

I have tried to press 'Trash' button in the memory profiler before taking last memory memory snapshot (It manually runs GC). Nothing changed - all InternalCache object still there in the memory. I have adjusted steps to reproduce with this information.

**Comment by vkarpov15** [comment]
I took a closer look at this and I don't think this issue is coherent enough for me to make an attempt at reproing it. I don't understand what "I attached by memory profiler to my local node process after this lambda's handler finished" or "important: but not the node.exe process" means. Can't tell whether you're running locally or in Lambda, or what debugger you're using, or much else for that matter. Can you please provide an isolated JavaScript script that prints out heap usage (like in the [blog post you linked to](https://www.alexkras.com/simple-guide-to-finding-a-javascript-memory-leak-in-node-js) ) that I can use to try to repro this, and confirm whether you can find the leak in Lambda or you're just seeing it locally?
