### ISSUE TITLE
Issue with {timestamps:true} with mongoose 5.8.11

### ISSUE THREAD

**Issue by kviswanatha1** [Automattic/mongoose#8607]
Hello, 
I have a query:-
we are trying to migrate to mongoose 5.8.11 from 5.5.7 
and while trying to call "save" function, we get typescript runtime error - "$__getValue() is not a function" with 5.8.11
we found that it seems to be because the schema definition has - "new mongoose.Schema({..},{ timestamps: true });"
When I remove { timestamps: true } from schema definition, it seems to work fine,

1. Is this an expected behavior ? Or a bug in mongoose, since the change history does not say anything about "{timestamp:true}" being not-supported?
2. If its not supported anymore, is there a way we can achieve same functionality with minimal changes ?

**Comment by vkarpov15** [comment]
@kviswanatha1 please open a new issue and follow the issue template. Timestamps are still supported, if `timestamps: true` causes your application to fail then that may be a bug and we need to investigate more.
