### ISSUE TITLE
Question about populating Map field

### ISSUE THREAD

**Issue by osmoliankin-cartera** [Automattic/mongoose#8608]
Hi guys,

I am wondering if it's possible to execute a populate method on a field with type = Map?
For example I have the following model:
`mongoose.model('Country', {
  name: {
    required: true,
    type: String
  },
  states: {
    type: Map,
    of: {
      name: String,
      cities: [{
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'City'
      }]
    }
  },
});`

And it's possible to get cities only for one state:
`Country.find({name: "US"}).populate("states.ca.cities")`
But how can I get all states for some country with populated cities in every state?

mongoose: 5.9.0
node: 10.15.3

**Comment by Dartv** [comment]
@osmoliankin-cartera why is this issue closed? How did you solve it?
