### ISSUE TITLE
Plugins are getting applied to subdocuments (fields that are of schema).

### ISSUE THREAD

**Issue by dibyajyotiron** [Automattic/mongoose#8609]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Let's take an example to understand the situation: 
My `plugin.js` looks like this: 
```
module.exports = {
    uidPlugin: function(schema) {
        schema.add({
            uid: {
                type: String,
                required: true,
                unique: true,
            },
        });
    },
};

```
My `mixin.js` looks like this: 
```
const { Schema } = require("mongoose");

const pointSchema = new Schema(
    {
        geometry: {
            type: {
                type: String, // Don't do `{ location: { type: String } }`
                enum: ["Point"], // 'location.type' must be 'Point'
                required: true,
            },
            coordinates: {
                type: [Number],
                required: true,
            },
        },
        type: {
            type: {
                type: String,
                enum: ["Feature"],
            },
        },
        properties: Object,
    },
    { _id: false },
);
module.exports = { pointSchema };
````
My `locality.js` looks like this:
```
const mongoose = require("mongoose");
const { Schema } = mongoose;
const { uidPlugin } = require("./plugins");
const { pointSchema } = require("./mixin");
const localitySchema = new Schema(
    {
        name: {
            type: String,
            required: true,
        },
        nameArabic: String,
        cityId: {
            type: Schema.Types.ObjectId,
            ref: "City",
        },
        status: {
            type: Boolean,
        },
        // can't use pointSchema here, since plugin will get attached to the pointSchema as well as that is also a schema nested under this one!
        location: pointSchema,
        createdAt: Date,
        updatedAt: Date,
    },
    // { timestamps: true },
);
localitySchema.plugin(uidPlugin);
module.exports.Locality = mongoose.model("Locality", localitySchema);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Now, the moment, for the location field, I use pointSchema, this plugin gets applied to the pointSchema as well, since uid is a required field, I get error `'E11000 duplicate key error collection: <db>.localities index: location.uid_1 dup key: { location.uid: null }'`
**What is the expected behavior?**
This should not happen since I'm specifying localitySchema.plugin(<plugin>), it should only get applied to the top level schema, not the nested schema's inside, `is there any way to prohibit this?`
 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.JS 12.13.1
mongoose version 5.9.1
mongo 4.2.0

**Comment by vkarpov15** [comment]
Set the [`applyPluginsToChildSchemas` option](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-set) to `false`:

```javascript
mongoose.set('applyPluginsToChildSchemas', false);
```
