### ISSUE TITLE
Bug: Aggregation with $sort and $limit cause unexpected behavior

### ISSUE THREAD

**Issue by danielbom** [Automattic/mongoose#8614]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I use an aggregation with $sort and $limit pipeline, the result is (limit - 1) out of expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try use an aggregation with $sort and $limit in a simple schema.

**What is the expected behavior?**
Return the correct limit of documents, if it's possible.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v10.16.0
mongoose: ^5.9.1
mongod: v4.0.11

![Captura de tela de 2020-02-22 18-25-08](https://user-images.githubusercontent.com/28939249/75099475-dbdc5600-55a0-11ea-8d5d-017dd5ee6ef3.png)
![Captura de tela de 2020-02-22 18-25-16](https://user-images.githubusercontent.com/28939249/75099477-dd0d8300-55a0-11ea-842b-7fa0af95b71e.png)

**Comment by lineus** [comment]
@danielbom the following code works as expected, can you edit it to reproduce the issue that you're seeing?

### 8614.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8614';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const tests = '0123456789'.split('').map(x => {
  return new Test({
    name: `test${x}`
  });
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const docs = await Test.create(tests);
  assert.ok(docs && docs.length === 10);

  const pipeline = [
    { $sort: { name: -1 } },
    { $limit: 5 }
  ];

  let results = await Test.aggregate(pipeline);
  assert.ok(results && results.length === 5);
  assert.ok(results[0].name === 'test9');
  assert.ok(results[4].name === 'test5');

  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```

###shell output:
```
➜  issues ./8614.js
All Assertions Pass.
➜  issues 
```

**Comment by danielbom** [comment]
It's all ok.

I'm using "$[*].summary" in insomnia and the summary its not required, then the element without summary its removed.

Sorry for inconvenience.
