### ISSUE TITLE
Document `match` and other `populate()` options as options to `Schema#virtual()` and `VirtualType` constructor

### ISSUE THREAD

**Issue by dar097** [Automattic/mongoose#8616]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Code snippet for use in explanations**
`Model.populate({
    path: 'items',
    match: { status: 'purchased' },
    as: 'purchased_items'
}).populate({
    path: 'items',
    as: 'all_items'
})`

**What is the current behavior?**
Using the above code snippet, the 'as' is ignored, and the last populate overrides the previous one, resulting in all items being returned under the name 'items'.

**What is the expected behavior?**
By providing the 'as' property, each populate is returned under its defined 'as' value, items with the status of 'purchased' under the property 'purchased_items' and all items under the property 'all_items'. This ideally would also work with virtual populate, allowing also count operations to be separable.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 10.16.0
Mongoose: 5.8.4
Mongodb: 3.4.1

**Comment by vkarpov15** [comment]
Why not just have `purchased_items` and `all_items` as [populate virtuals](https://mongoosejs.com/docs/populate.html#populate-virtuals)?

```javascript
schema.virtual('purchased_items', {
  ref: 'Item',
  localField: 'items',
  foreignField: '_id',
  justOne: false,
  match: { status: 'purchased' }
});

schema.virtual('all_items', {
  ref: 'Item',
  localField: 'items',
  foreignField: '_id',
  justOne: false
});
```

**Comment by dar097** [comment]
> 
> 
> Why not just have `purchased_items` and `all_items` as [populate virtuals](https://mongoosejs.com/docs/populate.html#populate-virtuals)?
> 
> ```js
> schema.virtual('purchased_items', {
>   ref: 'Item',
>   localField: 'items',
>   foreignField: '_id',
>   justOne: false,
>   match: { status: 'purchased' }
> });
> 
> schema.virtual('all_items', {
>   ref: 'Item',
>   localField: 'items',
>   foreignField: '_id',
>   justOne: false
> });
> ```

I was under the impression that match was not usable in virtual population, I'll try it out when I can.. If it is possible, is there any documentation of everything else that is possible here?

**Comment by vkarpov15** [comment]
You can use `match` with virtual populate. In general, conventional populate and virtual populate support the same options. [The API docs have a list of all options for `populate()`](https://mongoosejs.com/docs/api/model.html#model_Model.populate).

We need to add these options to [the `VirtualType` constructor's API docs](https://mongoosejs.com/docs/api/virtualtype.html).
