### ISSUE TITLE
Mongoose update method cannot change createdAt field

### ISSUE THREAD

**Issue by aminlatifi** [Automattic/mongoose#8619]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Model update method does not change `createdAt` field!

**If the current behavior is a bug, please provide the steps to reproduce.**

I want to change createdAt field to newCreatedAt value. I wrote the bellow script and it wasn't useful:
```
        const result = await Donations.findOneAndUpdate(
           { _id },
           { createdAt: newCreatedAt },
         ).exec();
```
Instead of `findOneAndUpdate`, I tried with `update` method too and result is the same.
However, this script works!
```
        const [d] = await Donations.find({_id}).exec();
        d.createdAt = newCreatedAt;
        const result = await d.save();
```
**What is the expected behavior?**
Update script should be able to update the `createdAt` field.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.1.3,
node: v10.9.0
Mongo: 4.2.2

**Comment by vkarpov15** [comment]
Set the `timestamps` option to `false` for your update, see [`updateOne()` docs](https://mongoosejs.com/docs/api/query.html#query_Query-updateOne). We need to add this option to `findOneAndUpdate()` docs.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String }, { timestamps: true });
  const Model = mongoose.model('Test', schema);

  // Sets `createdAt` to June 1, 2015
  await Model.findOneAndUpdate({}, { createdAt: new Date('2015/06/01') }, { timestamps: false });
}

```

**Comment by sean-hill** [comment]
@vkarpov15 this is not working for me. After making the update with the example above, and querying the fresh document, my `createdAt` timestamp is still the same 😭

**Comment by vkarpov15** [comment]
@sean-hill this  was for Mongoose 5. In more recent versions of Mongoose, we've made `createdAt` into an immutable property, so we need a little extra work. The following should work in Mongoose 8:

```javascript
  // Sets `createdAt` to June 1, 2015
  await Model.findOneAndUpdate({}, { createdAt: new Date('2015/06/01') }, { timestamps: false, strict: false });

```

However, we should make `overwriteImmutable` an option so we don't have to disable `strict` mode to overwrite immutable properties. And add this pattern to [timestamps docs](https://mongoosejs.com/docs/timestamps.html)

**Comment by sivastu** [comment]
Its working. @vkarpov15
