### ISSUE TITLE
Update to use node driver 3.5.4

### ISSUE THREAD

**Issue by Niffy** [Automattic/mongoose#8620]
Hi, the mongodb package, ~~yet to be released to what I assume is~~ version 3.5.4.
~~But~~ it will contain fixes which fixes a topology issue. It would be great if we can get this into mongoose.

Here is the original issue I raised.
https://jira.mongodb.org/projects/NODE/issues/NODE-2467

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/5f79b1aab037b92114e0ee19423b5eeeb110b619
