### ISSUE TITLE
(node:3968) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor

### ISSUE THREAD

**Issue by rubel1612** [Automattic/mongoose#8622]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by lineus** [comment]
Please see the documentation here: https://mongoosejs.com/docs/deprecations.html#useunifiedtopology

Also, before opening an issue, please look for existing issues per the contribution guidelines [here](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md)

**Comment by rubel1612** [comment]
thanks kev
