### ISSUE TITLE
useClass functionality is missed from documentation

### ISSUE THREAD

**Issue by svmn** [Automattic/mongoose#8623]
In the new documentation website (Version 5.9.2) page about Creating from ES6 Classes Using loadClass() is missing. Previously it was located at https://mongoosejs.com/docs/4.x/docs/advanced_schemas.html

**Comment by vkarpov15** [comment]
We removed that page for the Mongoose 5.x docs, there wasn't enough on that page to justify keeping it. We added a new section on the schema docs about `loadClass()` that will be in 5.9.5 :+1:
