### ISSUE TITLE
mongoose casts on every path of doc when getting it from mongodb but only on modified paths before save or validate

### ISSUE THREAD

**Issue by marcelh-gh** [Automattic/mongoose#8624]
Node 12.13.0
MongoDB 4.2.1
Mongoose 5.9.2

If you get a document from MongoDB via `findOne `etc, the resulting document has **all** paths casted (that is good and expected).

Before running `save` or `validate `on the document though, casting is **not** called for any paths.
That is bad because that means either lots of uncasted wrong values get saved to the db or with required validator on, they all get rejected.

The only paths that get saved or validated correctly are the ones where the path was specifically changed before (`doc.path=newValue;`) and therefore the casting was called on that path.

**Comment by marcelh-gh** [comment]
This might not be obvious when only _one-directional casting_ (application->database) is used (as it seem Mongoose is focused on by default).
The custom cast function of course allows bi-directional casting. But the described problem makes it impossible to use.

**Comment by vkarpov15** [comment]
@marcelh-gh Mongoose focuses on casting data going in to the database for a couple reasons. First, because `save()` only updates modified paths, so checking all paths isn't strictly necessary. Secondly, because mutating data that comes out of `find()` and `findOne()` can lead to a lot of confusion - data looks one way in the database and another way in node.

Can you please describe the use case where this behavior is causing you problems?

**Comment by marcelh-gh** [comment]
@vkarpov15 
The first point makes sense in general (only casting modified paths). An option to force casting on all paths would be great (rationale see further below).
The second point has problems:

- Mongoose **does** call the casting logic on` find() `and `findOne()` as you can read in my original post. Depending on if and how custom casting functions are defined, this becomes clear or not (if the custom casting logic only handles the direction to the db, the effect of the call is zero of course)
- I actually appreciate that the casting is called. Otherwise bi-directional custom casting would not be possible. I also don't see this as any source of confusion: the point is, that the built-in casting functions of Mongoose only cast towards the db. Anyone who defines a custom casting function in the other direction, expects the values to be cast and is not surprised.
- When custom bi-directional casting is used, my original post problem occurs during `save()`, therefore an option to force casting for all paths is all that is necessary to fix the issue.

I actually believe, optional bi-directional type casting via the ODM is essential for any application which is not just dumping data to the db to be consumed by some other app or via an API.
Other ODMs also do this.
Maybe we can have a some form of real-time communication (chat/call) to discuss further. That would be greatly appreciated. :-)

**Comment by vkarpov15** [comment]
I'm still not sure I understand your issue, but if your issue is that you want to validate data coming from the database before sending it to your client, you can use [`Model.validate()`](https://mongoosejs.com/docs/api/model.html#model_Model.validate). 

```javascript
const doc = await Model.findOne();

await Model.validate(doc.toObject()); // Validate all of the doc's paths against the model's schema, throw an error if it fails
```
