### ISSUE TITLE
Store document id as string

### ISSUE THREAD

**Issue by deligence** [Automattic/mongoose#8625]
Hello, I am converting my meteor web app to node with mongoose, I am facing a challenge here and it is that meteor app saves id as string into mongo database. Is there any way to save my mongoose database ids as string because i don't want to change my meteor database and if not is there any suggestion from your side.

**Comment by vkarpov15** [comment]
```javascript
new mongoose.Schema({ _id: String, /* other properties */ });
```

We'll add some more info on `_id` properties to the docs

**Comment by deligence** [comment]
Thanks, just FYI it wasn't enough to fixed the problem, I need to pass manually generated `_id` in `insert` query.

`const _id = mongoose.Types.ObjectId()`

Hope it will help other if they face the same issue.
