### ISSUE TITLE
Cannot connect to local mongodb conection when username and password are empty working in 5.6.2 version but not working in current version

### ISSUE THREAD

**Issue by dikshitthakral** [Automattic/mongoose#8640]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Cannot connect to local mongodb conection when username and password are empty working in 5.6.2 version but not working in current version . Error below : 
MongoParseError: Invalid empty username provided
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Expected behaviour it should except string 'mongodb://:@localhost:27017/db_name'.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node JS : 12.14.1
Mongoose : 5.9.2
@types/mongodb: ^3.1.28

**Comment by vkarpov15** [comment]
Does your mongodb server have an empty username and password? Or do you expect that empty username and password works the same as not specifying username and password at all?

**Comment by vkarpov15** [comment]
Unfortunately this is correct behavior according to the [MongoDB auth spec](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#errors). If `username` is empty and you're using the default authentication mechanism, the driver should throw an error, which it does as of [this commit](https://github.com/mongodb/node-mongodb-native/commit/507cc99dc76fd8e9384777b4148195dd033edb11).
