### ISSUE TITLE
TypeError: schema.plugin is not a function

### ISSUE THREAD

**Issue by yogesh-aggarwal** [Automattic/mongoose#8641]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
![](https://i.imgur.com/Mpquhuw.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Created the model

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.16.0
Mongoose: 5.9.3

**Comment by Uzlopak** [comment]
Well, this is a type error, which is thrown at compile time of typescript?!

**Comment by yogesh-aggarwal** [comment]
Yes I don't why it automatically solved 😅😂
