### ISSUE TITLE
Access connection in subdocument applied plugin

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8646]
**Do you want to request a *feature* or report a *bug*?**
question / feature request

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.9.3
nodejs: 12.16.1
typescript: 3.8.3

---

- Is there currently a way to access the connection used in an model from an plugin that is applied to an subdocument? 
- Is there an universal way to access the connection used by the model?

(the connection can be any connection not just the default one)

```ts
const Sub = new mongoose.Schema({ something: String });
Sub.plugin(function () {
  console.log(this.db); // this would work if it is the top-level schema, but not in an subdocument
}, {});
const Parent = new mongoose.Schema({ someotherthings: String, sub: Sub });

const ParentModel = mongoose.model("Parent", Parent);
```

PS: there isnt much documentation about plugins, and i couldnt find an example on how this would be done

**Comment by vkarpov15** [comment]
1) No, you can't access the connection from a plugin, because schemas don't have a connection. To access the connection, you'd need to get it from middleware.
2) [`Model#db`](https://mongoosejs.com/docs/api/model.html#model_Model-db)

**Comment by hasezoey** [comment]
@vkarpov15 like i said in the original issue, `this.db` cant be used if it is an sub-document, there it is just `undefined`

**Comment by vkarpov15** [comment]
Oh my mistake. You can then do `this.ownerDocument().db`
