### ISSUE TITLE
official mongoose doc demo about populate with sort does not currently work

### ISSUE THREAD

**Issue by manuelbarzi** [Automattic/mongoose#8647]
the demo described in the official mongoose's documentation about a populate  with sort options doesn't work (using mongoose ^5.9.3). here is the link https://mongoosejs.com/docs/api.html#query_Query-populate

the code is

```js
Kitten.find().populate({
  path: 'owner',
  select: 'name',
  match: { color: 'black' },
  options: { sort: { name: -1 } }
}).exec(function (err, kittens) {
  console.log(kittens[0].owner.name) // Zoopa
})

// alternatively
Kitten.find().populate('owner', 'name', null, {sort: { name: -1 }}).exec(function (err, kittens) {
  console.log(kittens[0].owner.name) // Zoopa
})
```
tested it in local and it does not sort as shown in the example

**Comment by AbdelrahmanHafez** [comment]
Could you provide some documents to test, with the expected results vs the actual results?

Also, this may be related to https://github.com/Automattic/mongoose/issues/2202 which is listed in the [FAQ](https://mongoosejs.com/docs/faq.html#populate_sort_order).

**Comment by manuelbarzi** [comment]
HERE's a demo with the failing test cases https://github.com/manuelbarzi/mongoose-find-populate-sort-issue-8647

**Comment by AbdelrahmanHafez** [comment]
I checked the script provided. The `match` condition is mistakenly added to the populated `owner`s, not the `kitten`s. Owners do not have a `color` field in their schema.

I changed the test a little bit, removing the first check with the `match` condition.

```js
const mongoose = require('mongoose');
const assert = require('assert');

mongoose.connect('mongodb://localhost/test', { useNewUrlParser: true, useUnifiedTopology: true });

const owner = new mongoose.Schema({ name: String });

const kitten = new mongoose.Schema({
  owner: { type: mongoose.Schema.Types.ObjectId, ref: 'Owner' },
  color: String
});

const Owner = mongoose.model('Owner', owner);
const Kitten = mongoose.model('Kitten', kitten);

async function run () {
  await Promise.all([Owner.deleteMany(), Kitten.deleteMany()]);

  const [john, mary] = await Owner.create([{ name: 'John' }, { name: 'Mary' }]);

  await Kitten.create([
    { owner: john._id, color: 'black' },
    { owner: mary._id, color: 'white' },
    { owner: mary._id, color: 'black' }
  ]);
  
  const kittens = await Kitten.find({ color: 'black' }).populate({
    path: 'owner',
    select: 'name',
    options: { sort: { name: 1 } }
  });
  
  assert(!!kittens[0].owner, 'should have owner'); // passes
  // fails because we're sorting owners within themselves
  // not sorting kittens by `owner.name`, since each kitten has a single owner
  // sorting here doesn't change anything
  assert.equal(kittens[0].owner.name, 'Mary', 'should owner name be Mary'); 
}

run().catch(console.error);
```

The way populate works is by making a call to the database, getting all the kittens, then getting all the owners ids from all kittens, creating a call for them, and sorting the owners within themselves, this has nothing to do with how the kittens will be sorted.

It would make more sense if each kitten had an array of owners, you would expect the `owners` for each kitten to be sorted by name.

Setting `mongoose.set('debug', true);` gives you the next results. Which is what happens under the hood.

```js
Mongoose: kittens.find({ color: 'black' }, { projection: {} })
Mongoose: owners.find({ _id: { '$in': [ ObjectId("5e66d5460216d85a54110878"), ObjectId("5e66d5460216d85a54110879") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, sort: { name: 1 }, projection: { name: 1 }})
```

And for what it's worth, if you need to sort parent documents by a field in a populated document, you can't do that using a query, you'll need to use the aggregation framework like so.

```js
  const kittens = await Kitten.aggregate([
    { $match: { color: 'black' } },
    { $lookup: { from: 'owners', localField: 'owner', foreignField: '_id', as: 'owner' } },
    { $unwind: { path: '$owner' } },
    { $sort: { 'owner.name': -1 } }
  ]);
```

I agree that the example in the documentation is a bit misleading, there is possibly a good reason for that, @vkarpov15 probably has a better idea on that bit of documentation.

**Comment by manuelbarzi** [comment]
yes, i had already solved it with aggregation https://github.com/manuelbarzi/mongoose-demos/tree/master/mongoose-aggregate-with-match-lookup-project-and-sort no problem with that

the only thing is this demo code in the official documentation which i understand now you confirm it is incorrect and should be reviewed, corrected and updated, so no to mislead the readers

**Comment by vkarpov15** [comment]
I can see why you think that example is misleading, we'll update that.

However, `sort` with `populate` does work as intended. When you pass `sort` to `populate()`, that `sort` applies to the foreign documents, not the local documents. For example, `Article.find().populate({ path: 'authors', sort: { name: 1 })` returns all articles in natural order, but with each article's authors sorted by their name. This is for performance reasons - sorting by a foreign field can be slow and expensive. But you're correct that you can do this using `$lookup` and aggregation.

**Comment by manuelbarzi** [comment]
thank you @vkarpov15
