### ISSUE TITLE
"TypeError: <model>.findByIdAndUpadte is not a function"

### ISSUE THREAD

**Issue by gString** [Automattic/mongoose#8649]
This line of code:
`let post = await Post.findByIdAndUpadte(request.params.id, request.body.post, { new: true });`
produce this error:
`TypeError: Post.findByIdAndUpadte is not a function`

While this code works just fine:
`let post = await Post.findById(request.params.id);
await post.update(request.body.post);`

Node v11.6.0
mongoose v5.9.2
MongoDB v4.0.3

**Comment by lineus** [comment]
you've got a typo - Post.findByIdAndUp**ad**te should be Post.findByIdAndUp**da**te
