### ISSUE TITLE
adding autoEncryption causes queries to hang

### ISSUE THREAD

**Issue by dphrag** [Automattic/mongoose#8650]
Mongoose 5.9.3
MongoDB 4.2.3 Enterprise Edition / Windows 10

As per https://github.com/Automattic/mongoose/issues/8167#issuecomment-562869693, when I add these lines:

```

 const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    // Configure auto encryption
    autoEncryption: {
      keyVaultNamespace, 
      kmsProviders
    }
  });

```

to my mongoose options, (with a more appropriate Buffer.from), it causes SOME future queries to just hang. I'm not adding any more options like the jsonschema and so on, removing the autoEncryption option fixes the issue.

Although obv. I need to further set up the $jsonSchema CSFLE information, it doesn't seem like adding this step should cause my queries to start hanging. I'm uncertain how to debug this.

**Comment by vkarpov15** [comment]
"it causes SOME future queries to just hang" <-- what does that mean? Can you provide some code samples that demonstrate the queries that are hanging?
