### ISSUE TITLE
i have an error when mongoose trying to connect

### ISSUE THREAD

**Issue by afzal173314** [Automattic/mongoose#8653]
E:\angular demo\My-App\server\config\mongoose.js:18
    throw new Error(`unabe to connect database: ${mongoUri}`);
    ^

Error: unabe to connect database: mongodb://localhost/productmart
    at NativeConnection.<anonymous> (E:\angular demo\My-App\server\config\mongoose.js:18:11)
    at NativeConnection.emit (events.js:223:5)
    at E:\angular demo\My-App\node_modules\mongoose\lib\connection.js:817:37
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
[nodemon] app crashed - waiting for file changes before starting...
                                                                  ### 

- 
THIS IS MY CODE
const mongoose = require('mongoose');
const util = require('util');
const debug = require('debug')('express-mongoose-es6-rest-api:index');
const config = require('../config/config');
const mongoUri = config.mongo.uri;

mongoose.connect(mongoUri, { keepAlive: 1, useNewUrlParser: true });

const db = mongoose.connection;

db.once('open', () => {
    console.log(`connected to the database: ${mongoUri}`);

});
db.on('error', () => {
    throw new Error(`unabe to connect database: ${mongoUri}`);
});
if (config.mongo.isDebug) {
    mongoose.set('debug', (collectionName, method, query, doc) => {
        debug(`${collectionName}.${method}`, util.inspect(query, false, 20), doc);
    });
}
module.exports = db;
- 

1.

**Comment by afzal173314** [comment]
any one know please help

**Comment by kolya182** [comment]
How does mongouri looks like ? Is mongo running ?

**Comment by afzal173314** [comment]
no

**Comment by afzal173314** [comment]
**when i run ** 
get this error:

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server`
(node:74056) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
server started on port 4050(development)
E:\angular demo\My-App\server\config\mongoose.js:20
    throw new Error(`unabe to connect database: ${mongoUri}`);
    ^

Error: unabe to connect database: mongodb://localhost/productmart
    at NativeConnection.<anonymous> (E:\angular demo\My-App\server\config\mongoose.js:20:11)
    at NativeConnection.emit (events.js:223:5)
    at E:\angular demo\My-App\node_modules\mongoose\lib\connection.js:817:37
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by vkarpov15** [comment]
Couple issues:

1) Your previous comment indicates that mongodb isn't running. So this is expected behavior.
2) Add the port to your URI, `mongodb://localhost:27017/productmart`
