### ISSUE TITLE
Problems with saving data to the data base using goormIDE and mongoDB

### ISSUE THREAD

**Issue by ttaarriik** [Automattic/mongoose#8654]
Hello everyone! I am trying to save some data to the database but I get some errors and depreciation warnings. I am using Node.js and mongoose downloaded from the goormIDE.

Here is my code:

var mongoose = require("mongoose");
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);
mongoose.connect("mongodb://localhost/cat_app");

var catSchema = new mongoose.Schema({
	name: String,
	age: Number,
	temperament: String
});

var Cat = mongoose.model("Cat", catSchema);

var george = new Cat({
	name: "George",
	age: 11,
	temperament: "Grouchy"
});

george.save(function(err, cat){
	
	if(err){
		console.log("OOps, something went wrong");
	}else {
		console.log("We just saved a cat to the db");
		console.log(cat);
	}
});

and here are the errors that I get:

    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejectin
g a promise which was not handled with .catch(). (rejection id: 1)
(node:1818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
 a non-zero exit code.

**Comment by AbdelrahmanHafez** [comment]
I am not sure what the issue exactly here is. Is it the deprecation warnings?
If that's the case, you can fix all the deprecation warnings following [these steps](https://mongoosejs.com/docs/deprecations.html#summary).

If you're facing an error while saving, Could you provide the Node/MongoDB/mongoose versions you're using?

I tested your code on my machine and things seem to be working just fine.
```
We just saved a cat to the db
{
  _id: 5e686f4368224930bc55bf9c,
  name: 'George',
  age: 11,
  temperament: 'Grouchy',
  __v: 0
}
```
You stated that you downloaded mongoose via goormIDE, which I am unfamiliar with.
Also, it seems like node doesn't get to run mongoose in the first place, is there more to the error stack or is that all?

Could you download it via npm and share the results?

**Comment by ttaarriik** [comment]
Thanks for the response, I actually figured out what the problem was, my mongoDB was not even running that's why I kept getting errors.

**Comment by ttaarriik** [comment]
> I am not sure what the issue exactly here is. Is it the deprecation warnings?
> If that's the case, you can fix all the deprecation warnings following [these steps](https://mongoosejs.com/docs/deprecations.html#summary).
> 
> If you're facing an error while saving, Could you provide the Node/MongoDB/mongoose versions you're using?
> 
> I tested your code on my machine and things seem to be working just fine.
> 
> ```
> We just saved a cat to the db
> {
>   _id: 5e686f4368224930bc55bf9c,
>   name: 'George',
>   age: 11,
>   temperament: 'Grouchy',
>   __v: 0
> }
> ```
> 
> You stated that you downloaded mongoose via goormIDE, which I am unfamiliar with.
> Also, it seems like node doesn't get to run mongoose in the first place, is there more to the error stack or is that all?
> 
> Could you download it via npm and share the results?

Thanks for the response, I actually figured out what the problem was, my mongoDB was not even running that's why I kept getting errors.

**Comment by AbdelrahmanHafez** [comment]
Glad to know you figured it out. 😄
