### ISSUE TITLE
orFail does not work with findById

### ISSUE THREAD

**Issue by lexdenotter** [Automattic/mongoose#8656]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When using orFail() on a findById() query, when no document is found error is not thrown, but undefined is returned

**What is the expected behavior?**
When no document is found, throw error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: v11.2.0, mongoose: 5.9.3

**Comment by lineus** [comment]
@lexdenotter the following repro script works as expected, can you modify it to demonstrate what you are seeing?

### 8656.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8656';
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

let shouldBeTrue = false;

const schema = new Schema({
  name: String
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'not_going_to_save' });

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  await Test.findById(test._id).orFail().catch((e) => {
    assert.ok(/^DocumentNotFoundError$/.test(e.name));
    shouldBeTrue = true;
  });
  assert.ok(shouldBeTrue);
  console.log('Model.findById(id).orFail threw a DocumentNotFoundError');
  await connection.close();
}

run().catch((e) => {
  console.error(e);
});
```

### Output:
```
➜  issues ./8656.js          
findById(id).orFail threw a DocumentNotFoundError
➜  issues 
```

**Comment by lexdenotter** [comment]
Yes the .catch() was the problem.
Documentation on this feature can be better imo.
According to documentation you don't need to catch the error, but you can throw one from the orFail

**Comment by vkarpov15** [comment]
@lexdenotter I don't understand your last comment, can you please clarify?

**Comment by lexdenotter** [comment]
As stated here in the [docs](https://mongoosejs.com/docs/api.html#query_Query-orFail)
the syntax is:
`// Throws if no doc returned
await Model.findOne({ foo: 'bar' }).orFail();

// Throws if no document was updated
await Model.updateOne({ foo: 'bar' }, { name: 'test' }).orFail();

// Throws "No docs found!" error if no docs match `{ foo: 'bar' }`
await Model.find({ foo: 'bar' }).orFail(new Error('No docs found!'));

// Throws "Not found" error if no document was found
await Model.findOneAndUpdate({ foo: 'bar' }, { name: 'test' }).
  orFail(() => Error('Not found'));`
But it doesn't seem to work without the .catch()

**Comment by vkarpov15** [comment]
That is the correct syntax. Can you please provide an example of what exactly doesn't work without [`.catch()`](https://masteringjs.io/tutorials/fundamentals/then#then-vs-catch)?

**Comment by lexdenotter** [comment]
``` 
const user = await this.userModel.findOne({ email }).ofFail(() => {throw new HttpException('User not found', HttpStatus.NOT_FOUND)});
return user
```
When no document was found, undefined was returned. 
When done like the example of @lineus the correct error was thrown when no document was thrown

**Comment by vkarpov15** [comment]
@lexdenotter the below script works fine - throws the custom error message as expected.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));

  await Model.findOne().orFail(() => {
    throw new Error('Did not find');
  });
}
```

Your example doesn't have a `.catch()` in it, so I'm still not sure what your issue is. If you're experiencing a bug or have a suggestion for our docs, please open up a new issue with detailed code samples and a clear description of what your point is.
