### ISSUE TITLE
Top-level populate `limit` doesn't apply limit to docs

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8657]
```javascript
const mongoose = require('mongoose');

const Article = mongoose.model('Article', mongoose.Schema({
  authors: [{ type: Number, ref: 'User' }]
}));
const User = mongoose.model('User', mongoose.Schema({ _id: Number }));

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await Article.deleteMany({});
  await User.deleteMany({});

  await Article.create([
    { authors: [1, 2] },
    { authors: [3, 4] }
  ]);
  await User.create({ _id: 1 }, { _id: 2 }, { _id: 3 }, { _id: 4 });

  // Works if using { options: { limit: 1 } }
  const res = await Article.find().populate({ path: 'authors',  limit: 1 });
  console.log(res);
}

```

**Comment by edgesinghkataria** [comment]
Hi @vkarpov15,

Do we need to add this feature? If yes, I can submit PR for this.

But the below change can get the required result.
`//this doesn't work but
await Article.find().populate({ path: 'authors',  limit: 1 });

// this works
await Article.find().limit(1).populate({ path: 'authors' });
`
Please let me know if I'm missing something.
Thanks

**Comment by vkarpov15** [comment]
@edgesinghkataria yes we do. `Article.find().populate({ path: 'authors', limit: 1 })` should limit `authors` to 1, it isn't the same thing as `Article.find().limit(1).populate({ path: 'authors' })`, which limits articles to 1.
