### ISSUE TITLE
Update validators for mixed types run with value of dotted properties and there's no way to know the path of the property

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#8659]
**Do you want to request a *feature* or report a *bug*?**
Feature/bug (not sure which)

**What is the current behavior?**
This test case passes, but see the comment inside the validator:

```js
it('runs top-level validator for dotted updates', function(done) {
  const testSchema = new Schema({
    n: {
      type: Schema.Types.Mixed,
      validate: {
        validator: function(v) {
          // v is 2, and there doesn't seem to be a way to determine the
          // path ('n.k' or just 'k' since we know we're in 'n' already).
          console.log(typeof v, v);
          return true;
        }
      }
    }
  });
  const Test = db.model('Test', testSchema);

  Test.
    findOneAndUpdate({}, {$set: {'n.k': 2}}, {runValidators: true}). // notice dotted path syntax
    exec(function(error) {
      assert.ifError(error);
      done();
    });
});
```

**What is the expected behavior?**

I'm not sure what the ideal behavior is, but the current behavior seems to make dotted notation impossible to use with update validators because you can't tell what path you're validating.

Possible ideas:

1. Add something to the validator's context, like `this.getPath()` (which would return `'k'` in this example). (Think this is my first choice.)

2. Synthesize an object to pass to the validator (`{k: 2}` in this example). Might be expensive and difficult to handle all of the atomic operators.

3. Require the use of the `path` method, so `testSchema.path('n.k').validate(fn)`. Mongoose would match the update's path with that validator's path, and not run `n`'s validator defined in the Schema config. This could work well...

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 5.9.4
MongoDB 4.2
Node.js 12.10.0

---

Relates to #6873

**Comment by vkarpov15** [comment]
Like in #6873, Mongoose shouldn't be running validators on parents of paths in dotted updates. Right now the only way to do this is with a `pre('findOneAndUpdate')` hook.

The idea of supporting `testSchema.path('n.k').validate(fn)` is interesting, but I'm not sure its viable because `n.k` isn't a path in the schema.

**Comment by zbjornson** [comment]
Thank you for the explanation and prompt fix!
