### ISSUE TITLE
Mongoose Transaction cannot get document ids of insertMany

### ISSUE THREAD

**Issue by mortillan** [Automattic/mongoose#8660]
**Do you want to request a *feature* or report a *bug*?**
Question or Bug?

**What is the current behavior?**
insertMany returns an empty array

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
await Item.createCollection()
const mongoose = require('mongoose')
const session = await mongoose.startSession()
await session.startTransaction()
const docs = await Item.insertMany(rows, { session })
await session.commitTransaction()
 const insertIds = docs.map(d => d.id())
console.log(insertIds)
resolve(insertIds) //resolves a promise
```

**What is the expected behavior?**
After commiting the transaction, the result of insertMany() w/c is array of documents should not be an empty array

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 12.16.1
Mongoose: 5.9.3
MongoDB: 4.2.3 in Atlas

**Comment by AbdelrahmanHafez** [comment]
AFAIK there is no `doc.id()` function. You probably wanna use that instead:
```js
const insertIds = docs.map(d => d._id);
```

The script below passes the assertion, could you modify it so that it shows the issue you're facing?
```js
const mongoose = require('mongoose');
const assert = require('assert');
mongoose.connect(MongoURI);

const Item = mongoose.model('Item', new mongoose.Schema({ code: Number }));

async function run () {
  await Item.createCollection();
  const session = await mongoose.startSession();
  await session.startTransaction();
  const docs = await Item.insertMany([{ code: 1 }, { code: 2 }, { code: 3 }], { session });
  await session.commitTransaction();

  const insertIds = docs.map(d => d._id);
  assert.equal(insertIds.length, 3);
}

run().catch(console.error);
```

**Comment by mortillan** [comment]
@AbdelrahmanHafez - thanks for looking onto it. I've beed debugging the whole day and because you pointed out that it should be working as intended I looked on other parts of the code and found the culprit
