### ISSUE TITLE
Upgrade mongodb version to fix cursor limit issue

### ISSUE THREAD

**Issue by StevenChin** [Automattic/mongoose#8664]
**Do you want to request a *feature* or report a *bug*?**

Report a bug. This isn't  a Mongoose bug but rather a bug in the underlying MongoDB client.

**What is the current behavior?**

Using `hasNext` on a cursor with a limit would not return the full set of results, see https://jira.mongodb.org/browse/NODE-2483 for more details.

**What is the expected behavior?**

Using `hasNext` on a cursor with a limit should return the full set of results.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node version: `v12.16.1`
Mongoose version: `5.9.4`
Mongo version used by mongoose: `3.5.4`
Mongo version with fix: `3.5.5`

**Comment by AbdelrahmanHafez** [comment]
Thank you for reporting this, it's fixed in #8667.

**Comment by StevenChin** [comment]
Awesome! Looking forward to the release 😃
