### ISSUE TITLE
Getting the result of an update operation

### ISSUE THREAD

**Issue by manast** [Automattic/mongoose#867]
Hello,

According to the documentation in mongodb (http://www.mongodb.org/display/DOCS/Updating#Updating-CheckingtheOutcomeofanUpdateRequest), it is possible to get the result of an update operation. In some cases it is extremely useful to be able to know if the update did update something or not. For instance in my application I want to update all the clients that are observing some document if that document has been changed or not. I can fake this by first getting the document and only updating if necessary, but it is quite inconvenient for several reasons. 

Is there any efficient way to get the update result information in mongoose or any good workaround for it?

regards.

**Comment by JorgeCeja** [comment]
For future reference:
```
var query   = { id: 8 }; 
var update  = { title: "new title" }; 
var options = { new: true }; 
MyModel.findOneAndUpdate(query, update, options, function(err, doc){ 
  // Done! 
  // doc.title = "new title" 
});
```

Credit: https://davidburgos.blog/return-updated-document-mongoose/
