### ISSUE TITLE
Hi! I'm facing "Server selection timed out after 30000 ms" error. Can anyone guide?

### ISSUE THREAD

**Issue by AminaZahid** [Automattic/mongoose#8670]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
That means you're having a problem with connecting to MongoDB.

Please use the issue template, and provide all the information in there, showing some code, and Node, mongoose, MongoDB versions.
