### ISSUE TITLE
Populate ref array from a model instance

### ISSUE THREAD

**Issue by zRelux** [Automattic/mongoose#8673]
# Question
Is it possible to populate ref array from a model instance?
Let's say I have a User Model.
Then I retrieve the user using find but NOT doing populate. Something like this
```javascript
const tmpUser = await User.find({email: value});
```
So my question would be can I from `tmpUser` do something like  this?
```javascript
const posts = await tmpUser.populate('Posts')
```

or I can only populate when fetching?

**Comment by AbdelrahmanHafez** [comment]
Yes, you can [populate fields from documents](https://mongoosejs.com/docs/api/document.html#document_Document-populate) after fetching them.

```js
const tmpUser = await User.find({email: value});

// now tmpUser.Posts is populated
await tmpUser.populate('Posts').execPopulate();
```

**Comment by zRelux** [comment]
Perfect!! Sorry but I couldn't find it in the docs. I'll close the issue now
