### ISSUE TITLE
If useUnifiedTopology is set to true it doesn't trigger connection error

### ISSUE THREAD

**Issue by EduardJacobs** [Automattic/mongoose#8676]
```javascript
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);
mongoose.set('useNewUrlParser', true);

mongoose.connect(config.dbUri, function(error) {
  if(error){
    console.log(`\nError. Could not connect to MongoDB\n`);
    process.exit(1);
  }
  
  console.log(`Connected to MongoDB on por ${app.get('port')}`);
});
```

If I comment out useUnifiedTopology then it throws an initial connection error if MongoDB connection is not present. If set to true it does nothing, no error triggering but if a connection is present then it connects to MongoDB fine. (Mongoose 5.7.12)

**Comment by AbdelrahmanHafez** [comment]
There has been a lot of work done on `useUnifiedToplogy` option later.

Could you update mongoose to v5.9.5 and see if the problem still occurs?

**Comment by EduardJacobs** [comment]
Didn't make any difference but thanks anyway!

**Comment by vkarpov15** [comment]
@EduardJacobs if `useUnifiedTopology` is `true` and Mongoose can't connect, you'll get an error after `serverSelectionTimeoutMS` milliseconds (30 seconds by default).
