### ISSUE TITLE
Multiple connections with models located in separate files

### ISSUE THREAD

**Issue by lauti7** [Automattic/mongoose#8679]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
When initialising more than one connection (different hosts / servers) its impossible to separate models from the initial app. I have tried to implement useDb(), but this seems to be for the same connection with different DB's hosted on this.

I have also tried to implement mongoose.connections[index].model('ModelName', Schema), this doesn't work if the connection hasn't been run yet (Please note: I'm using mongoose.createConnection()). Using TypeScript imports need to be the first thing in the file and therefore there's no way to create these connections prior to loading the models.

There really needs to be a better way to separate models from connections. Is there nothing that can be done to use a connection such as a useConnection function? The current implementation is unreliable and it's hard to work with.

**Comment by vkarpov15** [comment]
@lauti7 there's a couple possibilities. First is to have separate connection files:

```javascript
// conn1.js
const config = require('./config');
const mongoose = require('mongoose');

const db = mongoose.createConnection(config.mongodbUri);
require('./decorateModels')(db);

module.exports = db;

// conn2.js
const config = require('./config');
const mongoose = require('mongoose');

const db = mongoose.createConnection(config.mongodbUri);
require('./decorateModels')(db);

module.exports = db;
```

Where `decorateModels()` is a function that attaches models to a connection.

Another alternative is to use a DI framework or some other IOC pattern. These days I just use [ramda's `applySpec()` for IOC](https://thecodebarbarian.com/using-ramda-as-a-dependency-injector).
