### ISSUE TITLE
Topology was destoryed for any query after mongodb failover

### ISSUE THREAD

**Issue by colus001** [Automattic/mongoose#8681]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

When mongodb failover happens, previous request during failure brakes any query with error `Topology was destoryed` even after successful reconnection.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create mongodb container with docker
```
version: '2.1'

services:
  mongodb:
    container_name: local-db
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: always
```

2. Create server with express
```
const server = http.createServer(app);
```

3. Drop mongodb container
```
docker-compose down
```

4. Trying to query any collection with Mongoose until it shows following errors
```
GET /api
Error: Error finding BtTKm-gDCg5-Rito3dPRO7GZ7jrc-K_f: failed to reconnect after 30 attempts with interval 1000 ms
    at /Users/alma/Development/qwer.gg-back/node_modules/connect-mongodb-session/index.js:120:21
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:411:14
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:397:27
    at ClientSession.endSession (/Users/alma/Development/qwer.gg-back/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:395:17)
    at handleCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:128:55)
```

5. Next query it will shows errors like `Error: Error finding BtTKm-gDCg5-Rito3dPRO7GZ7jrc-K_f: Topology was destroyed`

```
GET /api
Error: Error finding BtTKm-gDCg5-Rito3dPRO7GZ7jrc-K_f: Topology was destroyed
    at /Users/alma/Development/qwer.gg-back/node_modules/connect-mongodb-session/index.js:120:21
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:411:14
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:397:27
    at ClientSession.endSession (/Users/alma/Development/qwer.gg-back/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:395:17)
    at handleCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/operations/collection_ops.js:597:29
    at /Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:411:14
    at executeCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:401:25)
    at handleCallback (/Users/alma/Development/qwer.gg-back/node_modules/mongodb/lib/utils.js:128:55)
```

6. Start mongodb docker container again.

7. Any of query still shows `Error: Error finding BtTKm-gDCg5-Rito3dPRO7GZ7jrc-K_f: Topology was destroyed` no matter what you do unless restart express application, although `reconnect` was successfully done. Following is option that I use for `mongoose.connect`

```
{
    dbName: 'test',
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    poolSize: 20,
    keepAlive: true,
    socketTimeoutMS: 10 * 1000,
    connectTimeoutMS: 10 * 1000,
  }
```

**What is the expected behavior?**

After node recover its connection to mongodb, query should not show destroyed topology error and fetch the result.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 12
Mongoose: 5.9.5
MongoDB: 4.2 (docker)

**Comment by vkarpov15** [comment]
Look at the stack trace, the error is in connect-mongodb-session. You'll want to read [this section about how to handle single server outages](https://thecodebarbarian.com/managing-connections-with-the-mongodb-node-driver.html#handling-single-server-outages). Or just turn on `useUnifiedTopology` for connect-mongodb-session.
