### ISSUE TITLE
The in's'te'r uses coordinates to create a document error in the session

### ISSUE THREAD

**Issue by shenqidebaozi** [Automattic/mongoose#8682]
mongoose version 5.6.7 
node version 12.14.0
Using the model create method, you can create, but you cannot pass the session
Cannot create using insertOne method
![image](https://user-images.githubusercontent.com/35397691/76916891-e0c0cb00-68fc-11ea-8d33-6e2aa51ee93a.png)
![image](https://user-images.githubusercontent.com/35397691/76916902-e9b19c80-68fc-11ea-8486-e2540a430666.png)
![image](https://user-images.githubusercontent.com/35397691/76916910-edddba00-68fc-11ea-8323-2ed8a486fe9a.png)
![image](https://user-images.githubusercontent.com/35397691/76916926-f9c97c00-68fc-11ea-9828-77ed2ccc7859.png)
![image](https://user-images.githubusercontent.com/35397691/76917136-8411e000-68fd-11ea-8f67-48fe1713871c.png)

**Comment by shenqidebaozi** [comment]
![image](https://user-images.githubusercontent.com/35397691/76917176-9b50cd80-68fd-11ea-8669-b10ae9b3cbea.png)

**Comment by AbdelrahmanHafez** [comment]
Please close the issue, and open a new one following the issue template, and please copy/paste the code as text, working with images makes it much more difficult for us to help you solve your issue.

**Comment by shenqidebaozi** [comment]
> Please close the issue, and open a new one following the issue template, and please copy/paste the code as text, working with images makes it much more difficult for us to help you solve your issue.

Duplicate of #8684
