### ISSUE TITLE
The insert uses coordinates to create a document error in the session

### ISSUE THREAD

**Issue by shenqidebaozi** [Automattic/mongoose#8684]
mongoose version 5.6.7
node version 12.14.0
Using the model create method, you can create, but you cannot pass the session
Cannot create using insertOne method

model:
`'use strict';

// eslint-disable-next-line valid-jsdoc
/**
 * 打卡记录
 * 出于记录持久化原则
 */
module.exports = app => {
  const mongoose = app.mongoose;
  // const pointSchema = app.PointSchema;
  const PointSchema = new mongoose.Schema({
    type: {
      type: String,
      enum: [ 'Point' ],
    },
    coordinates: {
      type: [ Number ],
    },
  });
  const AttendanceRecordSchema = new mongoose.Schema({
    /**
     * 员工id
     */
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    /**
     * 员工姓名
     */
    name: {
      type: String,
      required: true,
    },
    /**
     * 员工部门
     */
    department: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'department',
      required: true,
    },
    /**
     * 部门名称
     */
    departmentName: {
      type: String,
      required: true,
    },
    /**
     * 班次
     */
    arrange: {
      type: String,
    },
    /**
     * 应打卡时间
     */
    shouldTime: {
      type: String,
    },
    /**
     * 工号
     */
    userCode: {
      type: String,
    },
    /**
     * 职位
     */
    title: {
      type: String,
    },
    /**
     * 考勤日期
     */
    punchDate: {
      type: String,
    },
    /**
     * 打卡时间
     */
    punchTime: {
      type: Date,
      default() { return new Date().getTime(); },
      required: true,
    },
    /**
     * 当天打卡第几次
     */
    times: {
      type: Number,
    },
    /**
     * 打卡类型：on 上班打卡，off 下班打卡
     */
    type: {
      type: String,
    },
    /**
     * 打卡结果
     * 上班打卡、迟到打卡、严重迟到、旷工、下班打卡、早退打卡
     */
    result: {
      type: String,
    },
    /**
     * 最终考勤结果
     */
    finalResult: {
      type: String,
    },
    /**
     * 是否外勤打卡
     */
    field: {
      type: String,
    },
    /**
     * 是否使用人脸识别
     */
    isFace: {
      type: Boolean,
    },
    /**
     * 打卡模式  位置/WiFi
     */
    attendanceMode: {
      type: String,
    },
    /**
     * 打卡位置坐标
     */
    location: PointSchema,
    /**
     * 打卡地址
     */
    address: {
      type: String,
      default: '',
    },
    comment: {
      type: String,
    },
    /**
     * 打卡设备
     */
    device: {
      type: String,
    },
    /**
     * 打卡型号
     */
    model: {
      type: String,
    },
    uuid: {
      type: String,
    },
    /**
     * 变更备注
     */
    modifyComment: {
      type: String,
    },
  }, {
    timestamps: true,
  });

  AttendanceRecordSchema.index({ location: '2dsphere' });

  return mongoose.model('AttendanceRecord', AttendanceRecordSchema);
};
If you use insertOne
`  const result = await db
          .collection('attendancerecords')
          .insertOne(record, { session });

error: can't extract geo keys,
points must only contain numeric elements`

If you use create ,Do not pass the session. If an exception is thrown, it cannot be rolled back

`await ctx.model.AttendanceRecord.create(record);
`

If you pass a session, the code is warning, and subsequent code is no longer executed
`await ctx.model.AttendanceRecord.create(record,{ session });
`

**Comment by AbdelrahmanHafez** [comment]
Welcome @shenqidebaozi 

This issue is much better than the one you created earlier, however, it still doesn't follow the issue template, and it still is difficult to understand what the issue is. Could you please fill the issue template as is?

**Comment by vkarpov15** [comment]
Use:

```javascript
await ctx.model.AttendanceRecord.create([record], { session })
```

Make sure the first param to `create()` is an _array_, not a _document_, if you want to set `session`. Please see the [`Model.create()` docs](https://mongoosejs.com/docs/api/model.html#model_Model.create)
