### ISSUE TITLE
Docs: Document.post('save', function(doc, next) {...}). Does this === doc or not?

### ISSUE THREAD

**Issue by sgpinkus** [Automattic/mongoose#8686]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Doc ambiguous (https://mongoosejs.com/docs/middleware.html#post). Is `doc` argument to post save hook the same as `this`? Seems so (see below). Then what is the point in `doc`? Can I rely on `doc === this` always being the case? Docs should explain this.

**If the current behavior is a bug, please provide the steps to reproduce.**

    var mongoose = require('mongoose');

    let kittySchema = new mongoose.Schema({
      name: { type: String, index: true, required: true },
      color: { type: String },
    });

    async function main() {
      await require('./getTestConnection.js')();
      kittySchema.post('save', function(doc, next) {
        console.log(this.constructor, this);
        console.log('this === doc', this === doc);
        next();
      });
      const Kitty = mongoose.model('Kitty', kittySchema);
      let cat = new Kitty({name: 'alice', color: 'white' });
      await cat.save();
    }

    main()

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.9.5

**Comment by AbdelrahmanHafez** [comment]
I believe both refer to the document, yes, but there are cases where you'll _need_ to use `doc`, like for an arrow function:

```js
  // using arrow function, `this` will **not** refer to the document
  kittySchema.post('save', (doc, next) => {
    console.log(this.constructor, this);
    console.log('this === doc', this === doc); // false
    next();
  });
```

**Comment by sgpinkus** [comment]
Why would you need to use arrow functions?

I just was saying `doc` it's seems necessary so could cause confusion, so should be docd. Especially given the same problem exists from `pre()` but (unless I missed something) `pre()` has no `doc` arg. Advice is just not use arrow functions (can't remember where I read that but it's in the Mongoose doc somewhere).

**Comment by AbdelrahmanHafez** [comment]
>Why would you need to use arrow functions?

>Advice is just not use arrow functions (can't remember where I read that but it's in the Mongoose doc somewhere).

We don't know what the users' preferences are, and what use cases they could be working with, so we're not limiting them in any way, so the best we could do is provide information and let them use whatever they prefer. 

I am curious, what advantage do you think not passing `doc` as a parameter will have? You can always omit it and use `this` if that's what your preferred method.

In this section of the docs: [types of middleware](https://mongoosejs.com/docs/middleware.html#types-of-middleware) you'll find what `this` refers to under each type of middleware.

**Comment by sgpinkus** [comment]
> I am curious, what advantage do you think not passing doc as a parameter will have?

Non in particular. IT just confused me why it was there and what it was. This ticket is about *doc* not about code changes. That's why title is like "Docs: ...". Anyway, never mind.

**Comment by vkarpov15** [comment]
A few people over the last several years have mentioned that they have linters and strict company policies to only use arrow functions. Don't ask me why. But we do our best to make it easy to use both arrow functions and conventional functions.
