### ISSUE TITLE
unhandled promise rejection in goorm ide

### ISSUE THREAD

**Issue by krishnah60317** [Automattic/mongoose#8687]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Please close the issue and follow the issue template.
