### ISSUE TITLE
Improve stack trace of "Cast to ObjectId failed for value..." error

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#8691]
**Do you want to request a *feature* or report a *bug*?**
Improvement

**What is the current behavior?**
Current stack trace for this error is not very helpful, as it only logs Mongoose internals:

![image](https://user-images.githubusercontent.com/490562/77140080-4075cc80-6add-11ea-900f-b02827309539.png)

It is not possible to deduce where this error was thrown in the app.

Is there any way this can be improved so that the stack trace contains actual app lines to help us better figure out where this error is coming from?

For context, the error does specify the path and model, but we use this model in so many places that it's hard to find out what exactly is going wrong.

**Comment by vkarpov15** [comment]
New stack trace looks like this:

```
$ node gh-8691.js 
{ CastError: Cast to ObjectId failed for value "bad" at path "_id" for model "Test"
    at new CastError (/home/val/Workspace/MongoDB/mongoose/lib/error/cast.js:29:11)
    at model.Query.exec (/home/val/Workspace/MongoDB/mongoose/lib/query.js:4331:21)
    at run (/home/val/Workspace/MongoDB/troubleshoot-mongoose/gh-8691.js:20:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Just make sure you use `exec()` if you're using async/await. `await Model.findOne()` without `exec()` will unfortunately remove the calling file from the stack trace because of how V8's `await` handles custom thenables.

**Comment by adamreisnz** [comment]
Hmm, we do use async/await extensively everywhere, and only use `exec()` when populating. Are you recommending usage of `exec()` everywhere for every query when using async/await?

**Comment by vkarpov15** [comment]
@adamreisnz I've recently come to realize that using `exec()` gives you better stack traces. If you just use `await Model.findOne()`, the `exec()` call happens within `then()` in V8, and your stack trace won't include the `await Model.findOne()` line. I opened up an issue to investigate whether it is possible to get a better stack trace without explicitly calling `exec()`, but for now I'd recommend adding `exec()` if you're trying to track down where a cast error is coming from.

**Comment by adamreisnz** [comment]
Ok thanks for the insight. It's not practical to replace it _everywhere_ in our code, but I'll try to add it in future code and slowly sprinkle it around our existing codebase.

I hope this can be fixed and the stack trace improved without calling `.exec()` in the future.

**Comment by vkarpov15** [comment]
I hope so too. But feel free to sprinkle `exec()` where necessary, since `Query#then()` calls `Query#exec()` under the hood the only real difference is 7 extra characters.

**Comment by AshuGuptaGamer** [comment]
What about the #create() function? I can't attach a #exec() to it.

**Comment by vkarpov15** [comment]
@AshuGuptaGamer correct, you can't. Can you provide an example of what your source code looks like and what stack trace you're seeing?
