### ISSUE TITLE
(node:44688) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by marlonfsolis** [Automattic/mongoose#8694]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Printing warning on console.
(node:44688) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
If I specify the option **useCreateIndex:true** in the connection the warning is not printed.
```
mongoose.connect(conStr, {useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true})
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Use "unique: true" in a field of a schema definition.
```
const userSchema = mongoose.Schema({
    email: {
        type: String,
        require: true,
        **unique: true**
    }
});
```

**What is the expected behavior?**
Do not see deprecate warning.

**Please mention your node.js, mongoose and MongoDB version.**

Node v10.16.3
mongodb v4.2.3
mongoose v5.9.5

**Comment by AbdelrahmanHafez** [comment]
https://mongoosejs.com/docs/deprecations.html

**Comment by marlonfsolis** [comment]
Thanks Hafez for the link. I is fine work around this till the issue is fix.
