### ISSUE TITLE
5.9.5

### ISSUE THREAD

**Issue by 108St3R** [Automattic/mongoose#8695]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
It's not clear what the issue here is, please follow the issue template.
