### ISSUE TITLE
A way to subscribe to connection events in createConnection

### ISSUE THREAD

**Issue by rifler** [Automattic/mongoose#8696]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
```ts
const notDefaultConnection = mongoose.createConnection(...);

notDefaultConnection.on('connecting', () => console.log('never fired'));
```

**What is the expected behavior?**
```ts
const notDefaultConnection = mongoose.createConnection(..., {
	connecting: () => console.log('fired!');
});
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.9.5

**Comment by vkarpov15** [comment]
What is the benefit of this behavior? Passing an event handler as an option isn't a common pattern in JavaScript.

**Comment by rifler** [comment]
as I understand, some events can be triggered before you can subscribe. And if you use default connection, it can be fixed by subscribing before connect. But I don't realise how to do that with `mongoose.createConnection`

relative SO https://stackoverflow.com/questions/24100119/mongoose-connection-events-with-createconnection

**Comment by vkarpov15** [comment]
Are you just concerned about the 'connecting' event? I haven't looked, but I suppose it is possible that connections emit 'connecting' synchronously. It isn't possible for Mongoose to emit any other event synchronously though.

**Comment by dejayc** [comment]
> as I understand, some events can be triggered before you can subscribe. And if you use default connection, it can be fixed by subscribing before connect. But I don't realise how to do that with `mongoose.createConnection`

I do this by using `mongoose.createConnection` followed by `mongoose.openUri`:
```javascript
const connection = mongoose.createConnection();
await connection.openUri(connectionStr, connectOptions);
```
