### ISSUE TITLE
updateMany is not matching the mongodb behaviour 

### ISSUE THREAD

**Issue by mprinc** [Automattic/mongoose#8697]
**Do you want to request a *feature* or report a *bug*?**
+ bug

**What is the current behavior?**

the method has unexpected behaviour

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
<a model>.updateMany({}, {$set: {a: 1}});
```

is not updating any document

even though mongodb version

```
db.<a model>..updateMany({}, {$set: {a: 1}});
```

works well

the version with `[]` brackets works well:

```js
<a model>.updateMany({}, [ {$set: {a: 1}} ] );
```

Additionally, documentation is obsolated: https://mongoosejs.com/docs/api/model.html#model_Model.updateMany

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```json
"dependencies": {
        "@types/mongodb": "^3.5.2",
        "@types/mongoose": "^5.7.6",
        "bson": "^0.4.22",
        "mongoose": "^5.9.4"
    },
```

node -v
v12.10.0

mongod -v
db version v4.2.1

**Comment by AbdelrahmanHafez** [comment]
Welcome Sasha!

I wrote a script trying to reproduce the issue, with no luck. Could you modify the script below so it demonstrates the issue?

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

async function run () {
  await User.deleteMany();

  await User.create([{ name: 'first' }, { name: 'second' }, { name: 'third' }]);

  await User.updateMany({}, { $set: { name: 'new name' } });

  const users = await User.find();
  
  assert.deepEqual(users.map(user => user.name), ['new name', 'new name', 'new name']);

  console.log('Done.');
}


run().catch(console.error);
```

Also, in what way do you find the documentation obsolete?
