### ISSUE TITLE
When using bulkwrite, the document is not type checked against the schema?

### ISSUE THREAD

**Issue by masx200** [Automattic/mongoose#8698]
**Do you want to request a *feature* or report a *bug*?**
 

report a bug

**What is the current behavior?**

When using bulkwrite, the document is not type checked against the schema?

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts

export const port = 27017;
export const dbName = "controlplatform";

import mongoose from "mongoose";

export const dburl = "mongodb://localhost:" + port;
const connection = mongoose.createConnection(dburl, {
    useFindAndModify: false,
    autoIndex: true,
    useCreateIndex: true,
    dbName,
    useNewUrlParser: true,
    useUnifiedTopology: true
});

export { connection };

export const proconnect2 = connection.then(() => {
    console.log("mongodb connected ", port);
});

```
```ts

import mongoose from "mongoose";
import { connection } from "./connectdb-mongoose.js";
const { Schema } = mongoose;
const driverscollection = connection.model(
    "drivers",
    new Schema(
        {
            filename: { type: String, required: true },
            manufacturer: { type: String, required: true },
            devicetype: { type: String, required: true },
            classname: { type: String, required: true },
            readables: [{ type: String, required: true }],
            writeables: [{ type: String, required: true }],
            models: [{ type: String, required: true }],
            parameters: { type: Map, default: {} },
            valuetypes: { type: Map, required: true },
            options: { type: Map, default: {} }
        },
        { versionKey: false }
    ),
    "drivers"
);

export default driverscollection;


```

```ts
 await driverscollection.bulkWrite(
        metas.map((doc) => {
            
            return {
                updateOne: {
                    filter: { filename: doc.filename },
                    update: { $set:doc },
                    upsert: true
                }
            };
        })
    );
```

**What is the expected behavior?**

When the document type is incorrect, no error is reported and the document is added to the MongoDB database?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

https://mongoosejs.com/docs/api.html#model_Model.bulkWrite

"mongodb": "^3.5.5",

"mongoose": "^5.9.5",

nodejs  13.11

mongodb server 4.2.3

**Comment by AbdelrahmanHafez** [comment]
I can confirm that sending fields that do not exist in the schema as part of the filter/update object, still go through to MongoDB.

We should cast both the filter and the update, and if the update object is empty, we should not send it the operation altogether.

However, we can not do this with the filter object, because we can't tell whether it's intended to be an empty object (to update all documents in the collection) or it's empty because the user has entered a filter object with fields that do not exist in the schema.

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

async function run () {
  await User.deleteMany();

  await User.bulkWrite([
    {
      updateOne: {
        filter: { nonExistingField: 'should not be upserted' },
        update: { name: 'Hafez1' },
        upsert: true
      }
    },
    {
      updateOne: {
        filter: { name: 'Hafez2' },
        update: { nonExistingField: 'should not be upserted' },
        upsert: true
      }
    }
  ]);

  const usersCount = await User.countDocuments();

  assert.equal(usersCount, 0); // fails, count is 2

  console.log('Done.');
}


run().catch(console.error);
```


@vkarpov15 thoughts on this?

**Comment by masx200** [comment]
Due to the shortcomings of mongoose type checking, I have to set the MongoDB schema to ensure the correctness of the data type?

**Comment by masx200** [comment]
https://docs.mongodb.com/manual/core/schema-validation/

https://mongoosejs.com/docs/schematypes.html

**Comment by masx200** [comment]
The function db.createCollection provided by the MongoDB module is difficult to use. It cannot modify the schema of a collection in an existing database.

**Comment by masx200** [comment]
The solution is to run the `db.runCommand` function in the mongo shell to modify the schema of an existing collection.

**Comment by masx200** [comment]
Why doesn't the MongoDB module provide the `db.runCommand` function?

**Comment by masx200** [comment]
`mongo shell` is incomplete and inadequate, it does not support modularization, such as` require` or `import`

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 
I noticed [this tweet ](https://twitter.com/mongoosejs/status/1247903791736733696)by the mongoose account on Twitter, which specifies that the script below will throw an error before mongoose 5.9.7, trying this with mongoose 5.9.6 passes.

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

run().catch(console.error);

async function run () {
  await User.bulkWrite([
    {
      updateOne: {
        filter: { name: 'Test' },
        update: { notInSchema: true },
        upsert: true
      }
    }
  ]);
}
```

I suppose that the tweet refers to this issue. Now that I read the issue again, I am not sure my tests nor the tests provided in the commit refer to the issue at hand.

>When using bulkwrite, the document is not type checked against the schema?

@masx200 Could you provide more information on what exactly the issue here is? Please elaborate on your expectation

**Comment by masx200** [comment]
> @vkarpov15
> I noticed [this tweet ](https://twitter.com/mongoosejs/status/1247903791736733696)by the mongoose account on Twitter, which specifies that the script below will throw an error before mongoose 5.9.7, trying this with mongoose 5.9.6 passes.
> 
> ```js
> const mongoose = require('mongoose');
> const { Schema } = mongoose;
> 
> mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
> 
> const userSchema = new Schema({
>   name: { type: String }
> });
> 
> const User = mongoose.model('User', userSchema);
> 
> run().catch(console.error);
> 
> async function run () {
>   await User.bulkWrite([
>     {
>       updateOne: {
>         filter: { name: 'Test' },
>         update: { notInSchema: true },
>         upsert: true
>       }
>     }
>   ]);
> }
> ```
> 
> I suppose that the tweet refers to this issue. Now that I read the issue again, I am not sure my tests nor the tests provided in the commit refer to the issue at hand.
> 
> > When using bulkwrite, the document is not type checked against the schema?
> 
> @masx200 Could you provide more information on what exactly the issue here is? Please elaborate on your expectation

Sorry, Twitter is not available in China.

**Comment by vkarpov15** [comment]
I think he's asking about [MongoDB's schema validation](https://docs.mongodb.com/manual/core/schema-validation/). Mongoose does application-level schema validation for more flexibility and less operational overhead, we don't create MongoDB schemas currently.
