### ISSUE TITLE
[Feature] Document.prototype.clone

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8700]
It would be great if we had a method on documents to clone, the motive is to allow methods defined on the schema to create a clone of the document and operate on the clone, without having any side effects on the original document.

Example:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;

const authorSchema = new Schema({
  name: { type: String },
  isPremium: { type: Boolean }
});

const Author = mongoose.model('Author', authorSchema);

const blogPostSchema = new Schema({
  authorId: { type: Schema.ObjectId, ref: 'Author' },
  view: { type: Number }
});

blogPostSchema.methods.incrementViews = async function incrementViews () {
  const originalBlogPost = this;
  const blogPostClone = this.clone();  // <---- the requested feature

  await blogPostClone.populate('authorId');

  blogPostClone.views += 1;

  if (blogPostClone.authorId.isPremium) blogPostClone.views += 2;

  // this is the only thing that's changed by this method on the original document
  // populating authorId happens only on the clone, means no side effects happening
  originalBlogPost.views = blogPostClone.views;
};


mongoose.model('BlogPost', blogPostSchema);
```

This is different from .toObject() in the sense that it will return a clone of all the mongoose functionality added to that document, as if we just fetched the document from the database.

**Comment by vkarpov15** [comment]
You could do `const Model = this.constructor; const blogPostClone = new Model(this);`.

Another alternative would be to `populate('authorId')` and then `depopulate()` at the end if `incrementViews()`.

Would either of these approaches help?

**Comment by AbdelrahmanHafez** [comment]
>You could do const Model = this.constructor; const blogPostClone = new Model(this);.

This won't preserve the state of the document, the modified fields, `isNew` and all the cool stuff mongoose does.

>Another alternative would be to populate('authorId') and then depopulate() at the end if incrementViews().

Yes, that would work, but in a more complicated setup, I could easily forget to undo what I have done.

I've been exploring different ways to use mongoose methods as a wrapper for my business logic, and we currently can't depend on documents, we basically send the _id, and fetch the document from the database each time with its current state, and in the desired structure (the populated fields required for the function).

I am thinking that we should unify finding the document with its original shape, no populating at all, operate on it via methods, get all the required extra data on a clone inside the method, and reflect the findings on the original document in the end without any other side effects.

**Comment by vkarpov15** [comment]
Here's another option: a method that gives you the result of populating the `authorId` field without actually setting it on the document. Like a headless `populate()`. So you don't have to duplicate the query logic of populating a document, but you also don't modify the document. Maybe that would be a cleaner alternative?

**Comment by AbdelrahmanHafez** [comment]
A headless populate be a nice feature to have, but this isn't the only use case, I want to split my function into two parts, one that does the _how_ things happen, and in the end 2 or 3 lines with the changes that will happen to the original document.

So, I'd look at the last bit, and see what changed. If I am interested in knowing how those changes were calculated, I'd look at the rest of the function.

Admittedly, this may be out-of-scope and will push my whole codebase to revolve around mongoose, but it's a feature that I think would come quite handy.

**Comment by vkarpov15** [comment]
Hmm I'm not sure I understand. What's the concrete description of "how things happen"? Do you want a list of all the queries Mongoose will execute when populating?

**Comment by AbdelrahmanHafez** [comment]
My idea is to separate a function into two separate parts, the first is to gather data (possibly by mutating the document itself), and the second part is by injecting the gathered information in the end, once this convention is recognized by the developers working on the codebase, a developer would need to just look at the last 2 or 3 lines to know what this function changes in a document, and IF they need to understand how it got that information, they'll need to read the rest of the function.

Admittedly, this is probably a code-design issue, one that is out-of-scope for mongoose, so I'll try the `new Model(this);` approach and see if it works for us.

Perhaps at some point in the future, there'll rise a more concrete need for such `clone` functionality that will prompt us to implement it, but for now, I'll close this issue.
