### ISSUE TITLE
How to run error handling middleware on `validateSync()`?

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8703]
Right now we skip async validators on `validateSync()`, but the way we determine if a validator is async is based on the number of arguments. Since error handling middleware must take 3 arguments, `validateSync()` will never run error handling middleware #4885 

Re: #4885

**Comment by hasezoey** [comment]
is this still a issue because `doValidate` uses `isAsyncFunction` which checks the function prototype instead of argument length?

**Comment by Uzlopak** [comment]
I think a unit test, which proves that the error handling middleware is called should prove that this issue is done.

**Comment by hasezoey** [comment]
i have opened up #12371 which address *some* of this issue

i have noticed that `validateSync` does **not** trigger any hooks, even if they are normal sync functions, so i made #12372 as a draft for now - if it is wanted that this function to not execute hooks, please close the PR (stating that)
