### ISSUE TITLE
 How to use MongoDB for nodejs to modify the schema of an existing collection？

### ISSUE THREAD

**Issue by masx200** [Automattic/mongoose#8705]
**Do you want to request a *feature* or report a *bug*?**

request a feature

**What is the current behavior?**

Due to the shortcomings of mongoose type checking, I have to set the MongoDB schema to ensure the correctness of the data type?

https://github.com/Automattic/mongoose/issues/8698

The function db.createCollection provided by the MongoDB module is difficult to use. It cannot modify the schema of  an existing collection   

https://docs.mongodb.com/manual/core/schema-validation/

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

How to use MongoDB for nodejs to modify the schema of an existing collection？

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

"mongodb": "^3.5.5",

"mongoose": "^5.9.5",

nodejs 13.11

mongodb server 4.2.3

**Comment by masx200** [comment]
https://community.mongodb.com/t/how-to-use-mongodb-for-nodejs-to-modify-the-schema-of-an-existing-collection/1892/2

**Comment by vkarpov15** [comment]
You don't necessarily have to set MongoDB schemas with Mongoose. But if you want to, you can take a look at [this SO question](https://stackoverflow.com/questions/52350988/how-to-add-a-validator-to-an-existing-collection-via-node-js-mongodb-driver).
