### ISSUE TITLE
"llback is not defined"

### ISSUE THREAD

**Issue by gntsketches** [Automattic/mongoose#8709]
Using Mongoose ^5.9.5

**What is the current behavior?**
App crashes when attempting .findOne on a Model (empty string for "username" does not cause a crash.) See attached screenshots. Behavior appears normal when "llback" is changed to "callback" as shown.

<img width="548" alt="mongoose_llback" src="https://user-images.githubusercontent.com/39422326/77266827-dfc1cd80-6c5d-11ea-9401-847e5ff6d17a.png">

<img width="610" alt="mopngoose_llback_not_defined" src="https://user-images.githubusercontent.com/39422326/77266869-054ed700-6c5e-11ea-812e-c7cbf7e0ad17.png">

**Comment by lineus** [comment]
It doesn't appear that your copy of mongoose@5.9.5 was clean at the time you experienced this error. This can be demonstrated by doing a fresh install, and verifying that query.js has no occurrences of `llback`, and that the line in question ( **2869** ) returns `callback()` as expected. 

```
➜  mkdir issue_8709
➜  cd issue_8709
➜  npm init -y
Wrote to /Users/lineus/dev/issue_8709/package.json:

{
  "name": "issue_8709",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


➜  npm install mongoose@5.9.5
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN issue_8709@1.0.0 No description
npm WARN issue_8709@1.0.0 No repository field.

+ mongoose@5.9.5
added 30 packages from 18 contributors and audited 38 packages in 3.059s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.13.4 → 6.14.3       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.3   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

➜  grep llback ./node_modules/mongoose/lib/query.js| grep -iv callback
➜  awk 'FNR == 2869' ./node_modules/mongoose/lib/query.js
    process.nextTick(() => callback(null, casted));
➜ 
```
