### ISSUE TITLE
Cant connect to master slave mode

### ISSUE THREAD

**Issue by Nikhil2508** [Automattic/mongoose#8716]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot connect to mongodb in replica mode

**If the current behavior is a bug, please provide the steps to reproduce.**
Connect to mongodb using :

mongoose.connect("mongodb://username:pass@ip1:27017,ip2:27017/housiequiz?authSource=admin").catch(err => console.log(err)).then(msg => console.log(msg));

**What is the expected behavior?**
To create a connection

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node - 10.19.0
Mongoose - 5.9.6

I am unable to connect to mongo db in master slave mode.

**Comment by Nikhil2508** [comment]
MongoNetworkError: failed to connect to server [mongo3:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo3 mongo3:27017] This is the error I am getting

**Comment by vkarpov15** [comment]
See [replica set host names on the connection docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). TLDR; one of your MongoDB instances is running on a machine that calls itself 'mongo3', which is apparently not a host name your local machine can resolve. You can fix this by updating your `/etc/hosts` file to point to mongo3:

```
mongo3  192.155.XX.YY
```

where 192.155.XX.YY is the ip address of mongo3.
