### ISSUE TITLE
Mongoose Populate : There is any equivalent solution for aggregate lookup unwind preserveNullAndEmptyArrays in mongoose populate  

### ISSUE THREAD

**Issue by eldhose-cavli** [Automattic/mongoose#8717]
MongoDB
------------
`db.users.aggregate([
    {
        $unwind: "$profile",
        $unwind: {
            path: "$profile.universities",
            preserveNullAndEmptyArrays: false
        }
    }
])`

if **profile.universities** is empty, then the corresponding users record will be removed from the final result

There is any same alternatives available in mongoose populate ? 

`Users.find().populate({ path: 'profile'});`

**Comment by vkarpov15** [comment]
@eldhose-cavli I don't understand your question - Mongoose `populate()` doesn't do anything like `unwind`, so not sure what the behavior you expect is. Can you please follow the issue template and clarify?

**Comment by eldhose-cavli** [comment]
@vkarpov15
