### ISSUE TITLE
about UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms

### ISSUE THREAD

**Issue by kokoji** [Automattic/mongoose#8718]
Hi,

I use mongoose to connect mongoDB of cloud in node.js express application.
Sometimes the application stops responding, and the logs at that time are as follows(detail is attachment file). 
[mongooseTimeoutErrorLog.txt](https://github.com/Automattic/mongoose/files/4377560/mongooseTimeoutErrorLog.txt)

The reproduction method has not been established yet.
However, the same phenomenon occurs in development, staging, and production environments with similar configurations.
Three node.js apps are connected to one mongoDB, and if one fails, no error occurs in other apps.
Is there a good solution?

*******
Mar 23 15:12:31 cloudfoundry appname ERR (node:118) UnhandledPromiseRejectionWarning: MongooseTimeoutError: Server selection timed out after 30000 ms
Mar 23 15:12:31 cloudfoundry appname ERR     at new MongooseTimeoutError (/home/vcap/app/node_modules/mongoose/lib/error/timeout.js:22:11)
...
......
Mar 23 15:12:31 cloudfoundry appname ERR (node:118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4681)
********

mongoose: version5.8.10

The mongoose option is set as follows.

options: {
    useUnifiedTopology: true,
    ssl: true,
    user: 'user',
    pass: 'pass',
    native_parser: true,
    auto_reconnect: false,
    poolSize: 10,
    connectWithNoPrimary: true,
    sslValidate: false,
    useNewUrlParser: true,
    checkServerIdentity: false,
    sslCert: fs.readFileSync('./config/sslcerts/filename.crt'),
}

Thank you.

**Comment by vkarpov15** [comment]
The error message just indicates that your app has lost connection to MongoDB for some reason. Does your app print any other error messages around the same time? Any 'error' events on your [Mongoose connection](https://mongoosejs.com/docs/connections.html)?

**Comment by kokoji** [comment]
Hi,

Thank you for reply.
There doesn't seem to be any other errors before that one.
I'm trying to change some parameters in mongoose and see if I can get around the error.

Thank you.
