### ISSUE TITLE
AWS Node lambda invocation fails if the lambda execution context is re-used

### ISSUE THREAD

**Issue by sean-daley** [Automattic/mongoose#8719]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
We have a node application running in AWS lambda. For various reasons, this node application does NOT cache connections. It creates a new connection at the beginning of the invocation, uses it for some stuff, and then closes/disconnects at the end. When using mongoose 5.8.11 everything works just fine in lambda. About two weeks ago we upgraded to 5.9.4 and then it started failing if the lambda context was re-used after a period of inactivity (usually 5 - 10 minutes). We upgraded to 5.9.5 but the same issue happened. Before we even hit our app to actually connect, the lambda gets the following error and immediately exits:
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot set property 'isDirty' of null",
    "stack": [
        "TypeError: Cannot set property 'isDirty' of null",
        "    at Object.handleOperationResult [as cb] (/var/task/node_modules/mongodb/lib/core/sdam/server.js:470:49)",
        "    at (anonymous function).forEach.op (/var/task/node_modules/mongodb/lib/cmap/connection.js:78:12)",
        "    at Map.forEach (<anonymous>)",
        "    at TLSSocket.Connection.stream.on (/var/task/node_modules/mongodb/lib/cmap/connection.js:77:20)",
        "    at TLSSocket.emit (events.js:198:13)",
        "    at TLSSocket.Socket._onTimeout (net.js:443:8)",
        "    at ontimeout (timers.js:436:11)",
        "    at tryOnTimeout (timers.js:300:5)",
        "    at listOnTimeout (timers.js:263:5)",
        "    at Timer.processTimers (timers.js:223:10)"
    ]
}
```

We are using Mongo Atlas with a replicaset and are connecting using the following options:
```
{
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useCreateIndex: true,
        useFindAndModify: false
}
```

After running into this issue for a week or so, we then downgraded back to 5.8.11 and the problem has gone away. I have NOT tried setting `useUnifiedTopology` to false as it seems to be recommended that it's set to true going forward.

Just to repeat, this only happens if the lambda execution is re-used after some amount of inactivity (5 - 10 minutes). If it's continuously getting executed it works just fine.

**If the current behavior is a bug, please provide the steps to reproduce.**
Unfortunately, I cannot provide an easy STR for this. Hopefully the above explanation is enough to potentially figure things out.

**What is the expected behavior?**
When a lambda context is re-used with our app, it should not throw some type of a Timer error killing the lambda invocation. Since we close/disconnect everything, we are not sure where this Timer error is coming from?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose
* 5.8.11 - Works with this version
* 5.9.4 - Fails with this version
* 5.9.5 - Fails with this version

Node
* 10.x in AWS 

MongoDB
* Atlas 3 node cluster running 4.2

**Comment by vkarpov15** [comment]
I haven't been able to repro this, but I opened up a PR with the MongoDB driver :point_up: to see if this is an easy fix.

In the meantime, can you confirm that "creates a new connection at the beginning of the invocation" means your Lambda function looks something like what you see below?

```javascript
exports.handler = async function(event, context) {
  const db = await mongoose.createConnection(uri, { useUnifiedTopology: true });
  // Do stuff
  return db.close();
};
```

Any code samples you could provide would be helpful.

**Comment by sean-daley** [comment]
> I haven't been able to repro this, but I opened up a PR with the MongoDB driver ☝️ to see if this is an easy fix.
> 
> In the meantime, can you confirm that "creates a new connection at the beginning of the invocation" means your Lambda function looks something like what you see below?
> 
> ```js
> exports.handler = async function(event, context) {
>   const db = await mongoose.createConnection(uri, { useUnifiedTopology: true });
>   // Do stuff
>   return db.close();
> };
> ```
> 
> Any code samples you could provide would be helpful.

Yeah. That's effectively what we are doing. Originally we were initializing the DB outside of the handler and I thought that moving it into the handler would fix the problem but it didn't. I've spent some time trying to minimize the problem into a smaller test case but so far I haven't been able to reproduce the issue outside  of our full app either.

I fully understand the complexities of trying to resolve a problem like this without a proper STR though and I'll continue to try and work on that for you but also thanks for any help you've been providing!

**Comment by vkarpov15** [comment]
Looks like this particular error was fixed in https://github.com/mongodb/node-mongodb-native/commit/611be8dff663c33656db6d0355f049da94dffed9, it should be in mongodb@3.5.6 once that version is released. We'll keep an eye out for that release and upgrade Mongoose :+1:

**Comment by mete89** [comment]
Hi @vkarpov15,

I saw the same error on Lambda today. Using mongoose@5.9.2 with atlas. It seems that mongo@3.5.6 is ready. Do we need to expect the fix in mongoose@5.9.10?

Thanks

**Comment by AbdelrahmanHafez** [comment]
@mete89 There is a PR #8795 upgrading mongo to v3.5.6, if that fixes the issue, it will be out in mongoose v5.9.10.

**Comment by mete89** [comment]
Correct. Thanks @AbdelrahmanHafez

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/56a346d763d58c439ac391a37145b9f84c861345
