### ISSUE TITLE
connectTimeoutMS with useUnifiedTopology in docs

### ISSUE THREAD

**Issue by tomsh99** [Automattic/mongoose#8721]
I am trying to connect to my mongodb and I get timeout after 30 seconds. I tried to change it by defining the reconnectTimeoutMS for something else. But it seems that it’s not working. I guess it is related to the fact I set `useUnifiedTopology: true`.

**Comment by AbdelrahmanHafez** [comment]
You have a typo `reconnectTimeoutMS` => `connectTimeoutMS`
Also, you may wanna try `socketTimeoutMS` as well.

Here's a full list of the [connection options](https://mongoosejs.com/docs/connections.html#options).

**Comment by tomsh99** [comment]
Oops my bad. I used both socketTimeoutMS and connectTimeoutMS. I also tried each one of them alone...

**Comment by AbdelrahmanHafez** [comment]
Running the following script with **MongoDB down** asserts that the MongoDB tries until the specified timeout passes before throwing an error:

```js
const mongoose = require('mongoose');
const assert = require('assert');

const timeoutInMS = 60000;

async function run () {
  const startedConnectingAt = Date.now();

  const connectionOptions = { useNewUrlParser: true, useUnifiedTopology: true, serverSelectionTimeoutMS: timeoutInMS, connectTimeoutMS: timeoutInMS }

  await mongoose.connect('mongodb://localhost:27017/test', connectionOptions)
    .catch(err => console.log('Failed to connect.'));

  const actualConnectionDuration = Date.now() - startedConnectingAt;

  assert.ok(actualConnectionDuration >= timeoutInMS);
  console.log(`Failed after ${actualConnectionDuration}ms.`);
}


run().catch(console.error);
```

Try stopping MongoDB on your machine, and run the script. Does the assertion fail for you?

**Comment by vkarpov15** [comment]
I don't think `connectTimeoutMS` applies when you set `useUnifiedTopology`. `serverSelectionTimeoutMS` is what you need to set to tweak how long before initial connection times out with `useUnifiedTopology`.

**Comment by tomsh99** [comment]
> I don't think `connectTimeoutMS` applies when you set `useUnifiedTopology`. `serverSelectionTimeoutMS` is what you need to set to tweak how long before initial connection times out with `useUnifiedTopology`.

I’m using `mongoose@5.9.6` and I don’t have the option to set `serverSelectionTimeoutMS`...

**Comment by vkarpov15** [comment]
@tomsh99 why don't you have the option to set `serverSelectionTimeoutMS`? TypeScript?

**Comment by tomsh99** [comment]
> @tomsh99 why don't you have the option to set `serverSelectionTimeoutMS`? TypeScript?

Yes... I’m using `@types/mongoose@5.7.8`

**Comment by vkarpov15** [comment]
@tomsh99 then please try upgrading to the latest Mongoose types, and, if that still doesn't work, open up an issue on `@types/mongoose`'s github repo.

**Comment by tomsh99** [comment]
I updated to @types/mongoose@5.7.8 and it worked! Thank you
