### ISSUE TITLE
Infinite loop with doc.<map>.set

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#8722]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when using `doc.<map>.set` it will run infinitely the `$set` and `_handleIndex` functions

**If the current behavior is a bug, please provide the steps to reproduce.**
Note: uses typescript types & import
```ts
// NodeJS: 12.16.1
// MongoDB: 4.2-bionic (Docker)
import * as mongoose from "mongoose"; // mongoose@5.9.6

const SubSchema = new mongoose.Schema({ someValue: String });
const ParentSchema = new mongoose.Schema({ mapValue: { _id: false, type: Map, of: SubSchema } });

const ParentModel = mongoose.model("Parent", ParentSchema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "someDB", useCreateIndex: true, useUnifiedTopology: true });

  const doc = await ParentModel.create({
    mapValue: new Map([["someKey", { someValue: "hi1" }]])
  }) as mongoose.Document & { mapValue: Map<string, any>; };

  doc.mapValue.set("someKey", { // will infinitly loop with "$set" and "_handleIndex"
    ...doc.mapValue.get("someKey")
  });
  await doc.save();

  console.log("this message will never be logged");

  await mongoose.disconnect();
})();
```

**What is the expected behavior?**
to run without any infinite loops

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 12.16.1
mongodb: 4.2-bionic (Docker)
mongoose: 5.9.6

**Comment by vkarpov15** [comment]
Found and fixed. This issue _only_ happens if you copy the nested document using the [spread operator](https://thecodebarbarian.com/object-assign-vs-object-spread.html). `doc.mapValue.set("someKey", doc.mapValue.get('someKey'))` works.

Out of curiosity, why are you copying the document using the spread operator before setting? You realize you aren't writing React here lol, no need to copy objects every time you use them.

**Comment by hasezoey** [comment]
> Out of curiosity, why are you copying the document using the spread operator before setting?

when trying to modify just one value of an object inside the map, it replaces the whole object, and not just the modified value

```ts
const map = new Map();
map.set("someKey", { someValue1: true, someValue2: "hello" })
// and then anywhere
map.set("someKey", { someValue2: "hi" })
// then the final object would be
{ someValue2: "hi" } // also not including other values
```

otherwise, it is needed by an [user from typegoose](https://github.com/typegoose/typegoose/issues/207) where i noticed the infinite loop

**Comment by vkarpov15** [comment]
In that case I'd recommend just doing `doc.set('mapValue.someKey.someValue', 'hi')` or `doc.mapValue.get('someKey').someValue = 'hi'`.
