### ISSUE TITLE
Getter for custom SchemaType

### ISSUE THREAD

**Issue by timvol** [Automattic/mongoose#8723]
**Do you want to request a *feature* or report a *bug*?**
Neither nor... I think it's my failure / misunderstanding

**What is the current behavior?**
I created my own SchemaType as follows:

```js
class MyType extends mongoose.SchemaType {
  constructor (name, opts = {}) {
    super(name, opts, 'MyType')

    this._obfuscator = new Obfuscator({alphabet: 'abcdef123456'})
  }

  cast (v) {
    return obfuscate(v)
  }

  get (v) {
    console.log("calling get()")
    return deobfuscate(v)
  }
}

mongoose.Schema.Types.MyType = MyType
```

Now, my schema/model looks like:

```js
const MySchema = new mongoose.Schema({
  test: {
    type: MyType,
    alphabet: 'abcdef123456'
  }
})

const MyModel = mongoose.model('MySchema', MySchema)
```

But now... when I create a new document, store it in my db and retrieve it, I don't see "calling get()" and I'm retrieving the obfuscated text (not the "Hello World!"):

```js
const saved = await MyModel.create({
  test: 'Hello World!'
})

console.log(saved.test) // prints the obfuscated text instead of "Hello World!"
```

**What is the expected behavior?**

I thought that when I implement the get() function for my own SchemaType, it's called when I access the variable, but that's not the case. When I add the following line to my constructor, the get() function is called:

```js
  constructor (name, opts = {}) {
    super(name, opts, 'MyType')

    this._obfuscator = new Obfuscator({alphabet: 'abcdef123456'})

    super.get(this.get)
  }
```

In this case I've to add a second argument to my get() function that holds the MyType instance. But I don't thinkg that this is the correct way...

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 12.13.0
Mongoose: 5.9.6
MongoDB: 4.2

**Comment by vkarpov15** [comment]
I took a closer look and it turns out that you're not defining your custom getter property. Adding a `get()` method to your SchemaType isn't how you register a custom getter, as a matter of fact, you're making it impossible to register a custom getter :) Here's a better way to do what you're trying to do:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  class MyType extends mongoose.SchemaType {
    constructor (name, opts = {}) {
      super(name, opts, 'MyType')
    }

    cast(v) { return v; }
  }

  // Add a getter to all instances of `MyType`
  MyType.set(v => v != null ? `secret:${v}` : v);
  MyType.get(v => v != null && v.startsWith('secret:') ? v.slice('secret:'.length): v);

  mongoose.Schema.Types.MyType = MyType;

  const MySchema = new mongoose.Schema({
    test: MyType
  });

  const MyModel = mongoose.model('MySchema', MySchema);

  const saved = await MyModel.create({
    test: 'Hello World!'
  });

  console.log('-->', saved.test);
}
```

More about [defining custom getters for a given schematype here](http://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html).
