### ISSUE TITLE
virtual populate in two stages

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#8724]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Hi, I'd like yo get the virtual population in two stages, for example:
```javascript
User.virtual("comments", {
  ref: "Comments",
  localField: "_id",
  foreignField: "user",
  options: {
    select: "_id",
    lean: true
  }
});
```
When I populate this virtual I get an ```Array``` with objects containing ```{_id: xxxx}```, but in my case I need an ```Array``` with just ObjectId's, and later (maybe) populate this.

I know that I could have a pre or post hook in Comments to add a comment to an Array in the User but it becomes hard to track and keep all the data consistent.

For know I've develop a function in the mongoose object (with some overload definitions for my FW):
```javascript
"use strict";
module.exports = db => {
  db.SimpleRef = ({
    schema,
    name,
    filter,
    ref,
    refOptions = {},
    countOptions = {},
    select = "_id",
    transform = el => (el._id ? el._id : el),
    lean = true,
    distinct = false
  }) => {
    //PLRs
    if (!schema) throw new Error("No hay esquema");
    if (!name) throw new Error("No hay nombre para el virtual");
    if (!filter) throw new Error("No hay filtro para la consulta");
    refOptions = {type: ["ObjectId"], hidden: "view", ref, name: ref, ...refOptions};
    countOptions = {type: Number, hiddenDetail: true, name: refOptions.name || ref, ...countOptions};
    name = name || ref;
    Object.assign(
      schema.virtual(name).get(async function SimpleRef() {
        let localFilter;
        typeof filter === "function" ? (localFilter = await filter.call(this)) : (localFilter = filter);
        console.log("filter:", localFilter);
        let res;
        if (!distinct) {
          res = this.constructor.model(ref).find(localFilter);
          select && (res = res.select(select));
          lean && (res = res.lean());
        } else {
          localFilter.active = true;
          res = this.constructor.model(ref).distinct(distinct, localFilter);
        }
        res = await res;
        return res.map(transform);
      }).options,
      refOptions
    );
    Object.assign(
      schema.virtual(`${name}_count`).get(async function SimpleRefCount() {
        console.log("filter:", filter);
        let res = await this[name];
        return res.length;
      }).options,
      countOptions
    );
  };
};

```
So I can do something like: 
```javascript
  db.SimpleRef({
    schema: User,
    name: "comments",
    filter() {
      return {user: this._id};
    },
    ref: "Comments",
    refOptions: {name: "Comments"}
  });
``` 
And know I've a virtual "comments" (async) with the comments referenced and a virtual "comments_count" (also async) with the quantity of comments.

that's work great with my FW because I resolve everything before send it to the front end (with express-promise and co), then my front end can ask for the comments filtered by the ids in the virtual comments.

But if I need some operation, for example, add the upvotes in the comments belonging to a user I can't populate them to accomplish so I've to do another find and finally my virtual it's only functional outside the backend.

This is a good example for the issue #5762, besides my virtuals are forcibly async, I can't use them to populate because are not "standard"

As a solution I can do another virtual who use the result of this virtual an do a find o aggregate to accomplish the reduce function adding values.

But, as I can have defaults as Promises (I already have), also virtuals, it'd be good if I could resolve this problems more transparently.

For now I think if I can populate a virtual in 2 stages will be good to avoid having more data than needed and can also populate later this virtuals with the hole data or part of it so you can do something with it.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 12.16.1
mongoose: 5.9.6
mongodb: 4.2.3

**Comment by vkarpov15** [comment]
I'm not sure I understand your issue, specifically what you mean by "populate a virtual in 2 stages." I think what you're trying to get at is you want to first `populate()` with just `_id`, and then later potentially `populate()` the rest. Which is actually pretty easy.

```javascript
User.virtual("comments", {
  ref: "Comments",
  localField: "_id",
  foreignField: "user"
});

// First populate the bare minimum
const doc = await User.findOne().populate({
  path: 'comments',
  options: {
    select: "_id",
    lean: true
  }
});

// Later populate without any options to get all the comments.
await doc.populate('comments').execPopulate();
```

**Comment by chumager** [comment]
Thanks for the answer @vkarpov15, by "populate in two stages" I mean be able to work like if you have an ```Array``` of refs, like you do when you have a path like:
```javascript
comments: [
  {
    type: ObjectId,
    ref: "Comments"
  }
]
```
Maybe just a "transform" prop in the virtual will do it just fine, so instead of getting an array of objects with the _id, you can map it to get an array of ObjectId's.

I've been making some research about post hook and find out you can put a "transform" option in the virtual and it's passed to ```this``` in the post find hook, but it seems like the docs can't be modified in this hook... Am I right?

**Comment by vkarpov15** [comment]
Oh so you just want an array of ObjectIds? Why not just use native JavaScript `map()`?

```javascript
const doc = await User.findOne().populate({
  path: 'comments',
  options: {
    select: "_id",
    lean: true
  }
});

const commentIds = doc.comments.map(c => c._id);
```

I don't know of a `transform` option for virtuals. But you can modify documents in `post('findOne')` hooks.
