### ISSUE TITLE
Memory leak issue with Node 12.14 or above

### ISSUE THREAD

**Issue by priyank6796** [Automattic/mongoose#8726]
- We are using "mongoose 5.8.3".  

**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- We are facing a memory leak issue with mongoose. We are using node version 12.14 LTS.  When we downgrade the node version to 8.10 then it disappears. It's happening with 12.14 or above node version. When we remove the mongoose library then the issue seems to disappear.  We are using mongo atlas as a mongo cloud database. 

We are using following connection string to connect with DB.
`  Mongoose.connect(dbURL, { useNewUrlParser: true, useFindAndModify: false });`

I am sharing a screenshot of the memory usage of our application.
![036a285f-6511-4f5e-8cdd-622059c2bdaa](https://user-images.githubusercontent.com/17333370/77643561-9cc96800-6f85-11ea-901f-13b36c4904c7.jpeg)

**Comment by marioleczka20** [comment]
Fuck off

**Comment by marioleczka20** [comment]
Fuck off

**Comment by lineus** [comment]
I have reported the abusive user above. 

@priyank6796 The information you have provided isn't actionable. Can you provide a script that reliably demonstrates the issue that you described?
