### ISSUE TITLE
Can you "ref" and populate from a sub-document? 

### ISSUE THREAD

**Issue by harshmandan** [Automattic/mongoose#8728]
I have a Schema.

```
var postSchema = new mongoose.Schema({
    _id: { type: mongoose.Schema.Types.ObjectId},
    comments: [{
        _id: { type: mongoose.Schema.Types.ObjectId},
        text: { type: String },
    }]
  });
```

I'd like to create a "ref" of `comments._id` in another schema like so:

```
var otherSchema = new mongoose.Schema({
    _id: { type: mongoose.Schema.Types.ObjectId},
    comment_id: { type: mongoose.Schema.Types.ObjectId, ref: 'postSchema'},
  });
```

So I'd like to populate the comments using the `comments.id` ref. Can this be done?

**Comment by AbdelrahmanHafez** [comment]
Welcome @harshmandan!

It's not clear to me what you're trying to achieve.

```js
var postSchema = new mongoose.Schema({
    _id: { type: mongoose.Schema.Types.ObjectId},
    comments: [{
        _id: { type: mongoose.Schema.Types.ObjectId },
        text: { type: String },
    }]
  });

var otherSchema = new mongoose.Schema({
    _id: { type: mongoose.Schema.Types.ObjectId},
    comment_id: { type: mongoose.Schema.Types.ObjectId, ref: 'post.comment_id'},
  });
```



Assuming that you don't have a separate comments collection, and want to populate using the comment_id (which is `post.comments[0]._id` for example), I don't think there is a way to achieve that using mongoose.

Hopefully @vkarpov15 will correct me if I am wrong.

You may want to use a separate collection for comments, and use the comment._id as a reference, one other benefit for that is you'll avoid a situation where your comments array will grow until it hits the size limit.

This [blog post](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1) was quite useful in teaching me how to design my MongoDB schemas.

**Comment by vkarpov15** [comment]
@harshmandan I think what you're trying to do is populate comments from `otherSchema` given that `comments` is an embedded property in `postSchema`. That isn't possible. `populate()` can only pull in top level documents. So you would need to make a separate `Comment` model.
