### ISSUE TITLE
unhandled

### ISSUE THREAD

**Issue by GilgameshNapolean** [Automattic/mongoose#8729]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome @GilgameshNapolean!

Thank you for reaching out, please note that it's difficult to help without providing much information. I'll close this issue, and if you're facing an issue with mongoose, please open a new issue following the issue template.
