### ISSUE TITLE
Use discriminator to change schema of existing fields

### ISSUE THREAD

**Issue by bbhopesh** [Automattic/mongoose#8734]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently discriminators let you add fields only to the schema but don't let you modify schema of existing fields. Consider this code snippet
```
const VehicleSchema = new Schema({
  kind : String,
  chassis_details : {...},
  engine_details : {...}
}, {discriminatorKey : 'kind'});

const VehiclesSchema = new Schema({
  vehicles : [VehicleSchema]
}

const CarSchema = new Schema({
  car_specific_field : {...}
})

VehiclesSchema.path('vehicles').discriminator('car', CarSchema);
```
Above code snippet lets you add more fields to `VehicleSchema` if `kind` of vehicle is car but there is no way to add fields to `chassis_details` based on `kind` field in `VehicleSchema`.
I don't want to add fields to VehicleSchema but modify existing fields based on kind.

There is ofcourse a workaround by creating a new schema for each vehicle and having a `chassis_details` field in each of those but that is not ideal and could be very repetitive for large schemas.

**Comment by AbdelrahmanHafez** [comment]
AFAIK, you could override fields that already exist on the parent schema:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


const userSchema = new Schema({
  name: { type: String },
  interests: {
    sports: { type: String }
  }
}, { discriminatorKey: 'kind' });

const User = mongoose.model('User', userSchema);

const developerSchema = new Schema({
  interests: {
    sports: { type: String },
    programmingLanguage: String
  }
});

const Developer = User.discriminator('Developer', developerSchema);

const user = new User({
  name: 'Hafez',
  interests: { sports: 'Swimming' }
});
assert.equal(user.interests.sports, 'Swimming');

/*
A developer is a special kind of user who has
a programming language in their `interests` object
*/
const developer = new Developer({
  name: 'Hafez',
  interests: {
    sports: 'Swimming again',
    programmingLanguage: 'JS'
  }
});

assert.equal(developer.interests.sports, 'Swimming again');
assert.equal(developer.interests.programmingLanguage, 'JS');
```

If you have many fields like `sports` in your base schema, and don't want to repeat them, you can just use a dot notation like so:

```js
// will still have `sports` and all the fields in the base schema, and you would get the same results
const developerSchema = new Schema({
  'interests.programmingLanguage': String
});
```

Does that do the trick?

**Comment by bbhopesh** [comment]
yes, the dot notation will do the trick for me. Thanks.

**Comment by AbdelrahmanHafez** [comment]
Happy to help.
