### ISSUE TITLE
Mongoose One-to-many relationship does not show expected result

### ISSUE THREAD

**Issue by alakdam07** [Automattic/mongoose#8736]
**I am new in relational database**.I am using node js and express for the backend, REST API and database is MongoDB. I am using mongoose for connection and models. I successfully connect the database and able to post and get the data. From testing the app I am using Postman. I have created two models, one is a student and another is a course. **My goal is One student can have multiple courses and want to prevent duplicate student name, phone, email.** 
**I can post the courses with studentid which I got from MongoDB. When test course get  request I can see the relation between courses and student  but I try students get request I don't see the relation between student and course . Also When I try single student get request I don't see the relationship**

**This is my student model**

    `const mongoose = require("mongoose");
    const { Schema } = mongoose;
    
    const studentModel = new Schema({
      _id: mongoose.Schema.Types.ObjectId,
      name: {
        type: String,
        required: true,
        unique: true
      },
      birthday: {
        type: Date,
        required: true
      },
      address: {
        type: String,
        required: true
      },
      zipcode: {
        type: Number,
        required: true
      },
      city: {
        type: String,
        required: true
      },
      phone: {
        type: Number,
        required: true,
        unique: true
      },
    
      email: {
        type: String,
        required: true,
        unique: true
      },
      course: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "course"
      }
    });
    
    const student = mongoose.model("student", studentModel);
    module.exports = student;`

**This is my course model**

     `const mongoose = require("mongoose");
    const { Schema } = mongoose;
    
    const courseModel = new Schema({
      _id: mongoose.Schema.Types.ObjectId,
      name: {
        type: String,
        required: true
      },
      startdate: {
        type: Date,
        required: true
      },
      enddate: {
        type: Date,
        required: true
      },
    
      student: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "student"
      }
    });
    
    const course = mongoose.model("course", courseModel);
    module.exports = course;`

**This is my server and get and post request.**

    `require("dotenv").config();
    const express = require("express");
    const app = express();
    const morgan = require("morgan");
    const helmet = require("helmet");
    const cors = require("cors");
    const mongoose = require("mongoose");
    const student = require("./models/student");
    const course = require("./models/course");
    //app middlewear
    app.use(morgan("common"));
    app.use(helmet());
    app.use(cors());
    app.use(express.json()); //body Parser
    
    //Connect to db
    mongoose
      .connect(process.env.MONGODB_URI, {
        useUnifiedTopology: true,
        useNewUrlParser: true
      })
      .then(() => console.log("DB Connected!"))
      .catch(err => {
        console.log(err);
      });
    
    //student
    
    app.get("/students", async (req, res, next) => { //This is all students get request
      try {
        await student
          .find()
          .populate("course")
          .select("name birthday address zipcode city phone email course")
          .then(docs => {
            const response = {
              count: docs.length,
              students: docs
            };
            res.json(response);
          });
      } catch (error) {
        console.log(error);
      }
    });
    
    app.get("/students/:id", async (req, res, next) => { //THIS SINGLE STUDENTS GET REQUEST
      const id = req.params.id;
      try {
        student.findById(id).then(data => {
          console.log(data);
          res.json(data);
        });
      } catch (error) {
        console.log(error);
      }
    });
    
    
    
    app.post("/students", async (req, res, next) => {
      const logs = new student({
        _id: mongoose.Types.ObjectId(),
        name: req.body.name,
        birthday: req.body.birthday,
        address: req.body.address,
        zipcode: req.body.zipcode,
        city: req.body.city,
        phone: req.body.phone,
        email: req.body.email,

      });
      logs
        .save()
        .then(data => {
          console.log(data);
          res.json(data);
        })
        .catch(err => {
          console.log(err);
        });
    });
    //course
    app.get("/courses", async (req, res, next) => {//THIS IS COURSE GET REQUEST WHERE I CAN SEE THE POST AND RELATIONSHIP BETWEEN COURSE AND STUDENT
      try {
        await course
          .find()
          .select("name  student startdate enddate ")
          .populate("student") 
          .then(docs => {
            const response = {
              count: docs.length,
              courses: docs
            };
            res.json(response);
          });
      } catch (error) {
        console.log(error);
      }
    });
    
  
    
    app.post("/courses", async (req, res, next) => { //THIS IS COURSE POST REQUEST
      const logs = new course({
        _id: mongoose.Types.ObjectId(),
        name: req.body.name,
        startdate: req.body.startdate,
        enddate: req.body.enddate,
        student: req.body.studentid
      });
      logs
        .save()
        .then(data => {
          console.log(data);
          res.json(data);
        })
        .catch(err => {
          console.log(err);
        });
    });
    
    const port = process.env.PORT || 5000;
    app.listen(port, () => console.log(`🚀 App is listening at port ${port}!`));`

**Comment by vkarpov15** [comment]
Can you please clarify what you mean by "When test course get request I can see the relation between courses and student but I try students get request I don't see the relation between student and course"? I don't understand.

**Comment by alakdam07** [comment]
When I tried to see a relationship between one student took multiple courses by using postman. I don't see relationship but when I tried courses get request it shows courses which took.

**Comment by vkarpov15** [comment]
OK, so how about you provide some relevant information:

1) What request did you make to postman?
2) What was the response?
3) What is the response you expect?

Preferably in the form of code, not screenshots.
