### ISSUE TITLE
Documents Not Reset During Transient Transaction Errors

### ISSUE THREAD

**Issue by makinde** [Automattic/mongoose#8740]
**Do you want to request a *feature* or report a *bug*?**
Bug (or very unexpected behavior)

**What is the current behavior?**
```js
// Find docs
const group = await Group.findById(id).exec();
const profile = await Profile.findById(id2).exec();

// edit docs
group.name = 'foo';
profile.name = 'bar';

// Save the documents
await session.withTransaction(() => {
  await group.save({ session });
  await profile.save({ session });
});
```

When the second save encounters a `TransientTransactionErrors`, `withTransaction` retries the entire lambda. The problem is that while the first save gets rolled back, the `group` document still thinks that it has been saved. So the second time around, `group.save()` will think that there's nothing to save and will basically be a no-op. This is very hard to understand and debug.

**What is the expected behavior?**
Ideal would be that if the transaction fails, the state of the document is rolled back as well. This may be difficult.

Perhaps we can get away with talking about it more in the docs for transactions. I believe what is required right now is to move the entire code block above into the `withTransaction` lambda (the find, modification, and save). That way the documents are reset if the transaction fails.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.14.0
Mongoose: 5.9.6
MongoDB: 4.2.3

**Comment by AbdelrahmanHafez** [comment]
Is this the same behavior you're looking for? https://github.com/Automattic/mongoose/issues/8380
If so, let me know so we can close this and follow up on the issue above.

**Comment by makinde** [comment]
Ah yes, that looks like a very similar issue. In that issue, you’d want to reset the doc that had the error. In this issue, you want to reset the object  that had its own write “succeed”, but another action in the transaction failed. Depending on how the fix is implemented, it could be the same or a different fix.

**Comment by makinde** [comment]
Thanks for the quick triage.
