### ISSUE TITLE
[docs] Issues in Transactions Docs

### ISSUE THREAD

**Issue by makinde** [Automattic/mongoose#8741]
**Do you want to request a *feature* or report a *bug*?**
Bug (documentation)

**What is the current behavior?**
https://mongoosejs.com/docs/transactions.html#the-withtransaction-helper
The current documentation gives an example of use the `withTransaction` helper. There are a couple issues with the example compared to [this one](https://www.mongodb.com/blog/post/quick-start-nodejs--mongodb--how-to-implement-transactions) that mongoDB provides.

- AFAICT, `startSession` returns the session synchronously. The example was it within a promise chain.
- The example never calls `session.endSession()`, which the docs appear to mandate.

**Comment by vkarpov15** [comment]
1) [Mongoose's `startSession()` returns a promise](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-startSession), which is slightly different from the MongoDB driver's `startSession()`.

2) Where are the docs that mandate calling `session.endSession()`?

**Comment by makinde** [comment]
Thanks for the clarification on item 1.

I’m not sure if it’s required to call ends session. The example linked here does. If it’s not important, you can close and ignore.
https://www.mongodb.com/blog/post/quick-start-nodejs--mongodb--how-to-implement-transactions

**Comment by makinde** [comment]
Thanks!
