### ISSUE TITLE
I was having the same problem and when inserting useUnifiedTopology: true, stopped showing terminal error.

### ISSUE THREAD

**Issue by macindex** [Automattic/mongoose#8748]
I was having the same problem and when inserting useUnifiedTopology: true, useNewUrlParser: true, useFindAndModify: true, stopped showing terminal error.

Folow code:

mongo() {
this.mongoConnection = mongoose.connect(process.env.MONGO_URL, {
useUnifiedTopology: true,
useNewUrlParser: true,
useFindAndModify: true,
});
}

**Comment by AbdelrahmanHafez** [comment]
Welcome @macindex 

Please note that it's difficult to help without providing enough information, I'll be closing this issue, please open a new issue following the issue template.
