### ISSUE TITLE
MyModel.collection.insertMany() emits not authorised error

### ISSUE THREAD

**Issue by mickeyjohn** [Automattic/mongoose#8750]
Current behavior:
As mentioned in #8215, when I try to use the underlying collection of MyModel as: MyModel.collection.insertMany(docs, { bypassDocumentValidation: true }). It always emits error as following:

"MongoError: not authorized on agmission to execute command { insert: "...", documents: 100, ordered: true, bypassDocumentValidation: true, lsid: { id: UUID("3c81b623-50dc-4ddf-a639-b7f909e0e2af") }, $db: "..." }"

Expected behavior:
It should call the native insertMany function normally using the current default connection.

Using MyModel.insertMany(..) works normally. The user has 'readWrite' role with the database.

Mongoose version: 5.9.7
Node: 10.x

Updated: after couple of hours trying I found out that It was because the options used as { bypassDocumentValidation: true }. If using moongose insertMany's option as { lean: true }, I will work. However, the return result will be in a 'insertWriteOpCallback' object as mentioned in here:  https://mongodb.github.io/node-mongodb-native/3.5/api/Collection.html#~insertWriteOpCallback 

This seems inconsistent. What do you think?
Thanks a lot.

**Comment by AbdelrahmanHafez** [comment]
Could you modify the script below to demonstrate the issue you're facing?

```js
// 8750
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

async function run () {
  await User.deleteMany();

  const res = await User.collection.insertMany([{ name: 'Hafez' }], { bypassDocumentValidation: true });

  assert.equal(res.ops[0].name, 'Hafez');
  console.log('Done.');
}


run().catch(console.error);
```

**Comment by mickeyjohn** [comment]
Thanks for you prompt response and the sample testing codes. Please try to connect with a user only granted with 'readWrite' role, you will see the unauthorised error. It only works if the user granted with 'dbAdmin' role or the options must be { lean: true }. Thanks.

**Comment by mickeyjohn** [comment]
Given the sample code above:
In mongo shell, connect with admin user:
use test;
show users;
```
{
..
	"db" : "test",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "test"
		},
		{
			"role" : "dbAdmin",
			"db" : "test"
		}
	],
..
}
```
With this granted roles to user 'test', it works. Of course, the connect code should include the user credential.
`mongoose.connect('mongodb://localhost:27017/test', { user:'test', pass: '<password>',  useNewUrlParser: true, useUnifiedTopology: true });`

this will work:
`  const res = await User.collection.insertMany([{ name: 'Hafez' }], { bypassDocumentValidation: true}); `

Then, revoke the 'dbAdmin' role:
db.revokeRolesFromUser( 'test',   [ { role : 'dbAdmin', db : 'test' } ]);
show users;
```
{
..
	"db" : "test",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "test"
		}
..
}
```
Then run the sample codes again, it will fail with the unauthorised error.

**Comment by vkarpov15** [comment]
Confirmed, however, this is expected behavior. According to the [MongoDB docs on `bypassDocumentValidation`](https://docs.mongodb.com/manual/core/schema-validation/#bypass-document-validation), you need special permissions to use the `bypassDocumentValidation` option.

If the `dbAdmin` role is too permissive but your app needs `bypassDocumentValidation`, you need to [create a custom role](https://docs.mongodb.com/manual/reference/method/db.createRole/) with permission for the `bypassDocumentValidation` action. That's an administrative task and not something that Mongoose can handle for you currently.
