### ISSUE TITLE
Problem connecting to MongoDB

### ISSUE THREAD

**Issue by joaobonifacio** [Automattic/mongoose#8754]
I've been doing an app in Angular, mongodb, express and using mongoose.

Until today I had no problems accessing my Atlas db. 

I was using:

mongoose.connect("mongodb+srv://<User>:<Password>@cluster0-xfp1v.mongodb.net/<App Name>?retryWrites=true&w=majority") and all was fine.

Today I got connection failures and this deprecation warnings:

(node:37532) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:37532) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

I tryed using the connection string like:

mongoose.connect("mongodb+srv://<User>:<Password>@cluster0-xfp1v.mongodb.net/<App Name>?retryWrites=true&w=majority", { useNewUrlParser: true } )

and also 

mongoose.connect("mongodb+srv://<User>:<Password>@cluster0-xfp1v.mongodb.net/<App Name>?retryWrites=true&w=majority", { useNewUrlParser: true, useUnifiedTopology: true } )

But nothing works. Does anyone has any ideas?

**Comment by Enado95** [comment]
Warning still persists for me as well if i set `{useUnifiedTopology: true }`

**Comment by vkarpov15** [comment]
@joaobonifacio are you using any other MongoDB-related modules, like connect-mongo or connect-mongodb-session? Try running `npm list | grep "mongo"`.

Also, please read our [deprecation warning docs](https://mongoosejs.com/docs/deprecations.html)

**Comment by Enado95** [comment]
@vkarpov15 see screen below. Im one node 12 and mongoose 5.9.7. Im connecting to replicaSet.
Even after passing the option the warning still persists.
![useUnified](https://user-images.githubusercontent.com/25810206/78307692-1e803f00-750c-11ea-8262-fb1bbdb9a72c.PNG)

**Comment by AbdelrahmanHafez** [comment]
Just a shot in the dark, I've seen a couple of issues here where people had connection issues with Atlas that I wasn't able to reproduce, they turned out to be issues with their ISPs blocking Atlas for some reason.

Try changing your DNS to Google's `8.8.8.8`, or try a VPN to see if the problem still persists.

**Comment by Enado95** [comment]
Yes. I Read the docs. Did as recommend and the warning still persisted. @AbdelrahmanHafez

**Comment by vkarpov15** [comment]
@Enado95 you did not answer my question. Run `npm list | grep "mongo"` and paste the output.

**Comment by Enado95** [comment]
See below @vkarpov15 
![mongogrep](https://user-images.githubusercontent.com/25810206/78931905-428fd300-7a6c-11ea-841e-6a1f7f8a01d9.PNG)

**Comment by vkarpov15** [comment]
OK. Can you paste the code you're using to initialize winston-mongodb? This warning could be coming from that library as well.

**Comment by Enado95** [comment]
That is in fact correct. The option was missing from that (winston-mongodb) connect method.
