### ISSUE TITLE
Upgrade Bson to v4

### ISSUE THREAD

**Issue by AliYusuf95** [Automattic/mongoose#8759]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Move to support Bason v4, https://github.com/mongodb/node-mongodb-native/commit/30797c5c309a274106cca965e77c9013444c4641

**Comment by vkarpov15** [comment]
The change you linked to looks like it will be in v4.0 of the mongodb driver, so we'll have to upgrade to that version once it is released.
