### ISSUE TITLE
CastError when overwriting a document from discriminator

### ISSUE THREAD

**Issue by arrocke** [Automattic/mongoose#8765]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

Overwriting a document that is from a discriminator schema causes a CastError for the discriminator key because it is reset.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require("mongoose");

const BaseSchema = new mongoose.Schema({
  value: Number
});

const BaseModel = mongoose.model("BaseModel", BaseSchema);
const ChildModel = BaseModel.discriminator("ChildModel", new mongoose.Schema());

const model = new ChildModel({ value: 1 });
model.overwrite({ value: 2 });
model.save();
```

```
ValidationError: ChildModel validation failed: __t: Cast to String failed for value "undefined" at path "__t"
```

**What is the expected behavior?**

I would expect it to keep the discriminator key. Maybe there is a good reason to overwrite the discriminator key, but right now, I have to remember to pass it in when I call overwrite

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 12.16.1
mongoose: 5.9.7
mongodb: 3.6.8

**Comment by vkarpov15** [comment]
I can't think of a reason why your suggested solution wouldn't work off the top of my head. Feel free to put in a PR if you have time. If not, I should be able to take a look at this over the weekend.
