### ISSUE TITLE
individual inserts caching for regular bulk inserts

### ISSUE THREAD

**Issue by syffs** [Automattic/mongoose#8769]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
there is no way to optionally cache individual inserts in order perform regular bulk inserts.

**What is the expected behavior?**
individual insert on named collections are grouped together and regular bulk inserts are triggered based on the number of pending docs or a timeout

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

this is a common ORM library feature which usually reduces the application IOs as well as the database load. I'm not sure about the performance boost, but i think it makes sense to open the discussion.

**Comment by lineus** [comment]
This seems like an interesting idea that might be better suited as a plugin than supported natively. I created [one here called mongoose-cachedBulkInsert](https://github.com/lineus/mongoose-cachedBulkInsert).

@syffs I'm happy to spend time working on it if you find any issues or have ideas for making it better. Feel free to play with it and file issues over in [the repo](https://github.com/lineus/mongoose-cachedBulkInsert/issues).

@vkarpov15 @AbdelrahmanHafez do you think this should be a built-in?

**Comment by syffs** [comment]
thanks for the quick response, I'll try to find some time to play with it in the coming days, cheers !

**Comment by vkarpov15** [comment]
No I don't think this should be a built-in. Bulk inserts are generally an antipattern due to [slow trains](https://thecodebarbarian.com/slow-trains-in-mongodb-and-nodejs#break-up-one-slow-operation-into-many-fast-operations) - the right pattern for most apps is to break up one big slow operation into many small fast operations for more consistent performance. But if you find bulk writes are important for your app, I'm happy to link to plugins.

**Comment by syffs** [comment]
sorry, missed the reply
@vkarpov15 aggregation is not the use case I described here:

> individual insert on named collections are grouped together and regular bulk inserts are triggered based on the number of pending docs or a timeout

See it as many small fast operations that could bulk network IO into a single one. 

The point is really to reduce network IOs and the js stack load of individual `Model.create`. I don't think slow trains concept applies here, does it ?

**Comment by vkarpov15** [comment]
`bulkWrite()` is a single MongoDB operation, so in this case one slow `bulkWrite()` could block other faster operations.

@AbdelrahmanHafez was looking to work on a `bulkSave()` feature that sounds related, see #9673. Is that something that might be helpful?

**Comment by syffs** [comment]
In the use case I described, the idea is that these operations are not necessarily initiated at the same timestamp (like activity records for instance, which would be created over time). hence, the idea was to cache records and push bulks of them regularly instead of flooding the db with N ops/seconds

Now about `bulkwrite`: let's say you need to run 100k write operations (simple update/create on 1 collection), and you can:
1. do 100k unitary create/update
2. split them into 10k batches and use `bulkwrite` for each batch

So according to you, option 1 is faster than option 2 ?
If so, this doesn't make any sense to me, unless `bulkwrite` is wrongly designed

About `bulksave`, from my understanding, it's using `bulkwrite`, so it seems to be roughly the same idea (if you put apart the case of operations created over time and cached)

**Comment by vkarpov15** [comment]
Option 2 will be faster than option 1, but at the potential cost of making other operations on the same connection pool slower. If you're writing a one-off job, I'd say go with option (2). If you're building an API and expect this 100k write operation to happen regularly, I'd recommend option (1) unless you really need the extra perf. Mongoose is designed more for the API situation, but there's nothing stopping you from doing (2).
