### ISSUE TITLE
Populate doesn't work when setting the collection name

### ISSUE THREAD

**Issue by JuCarr** [Automattic/mongoose#877]
Hi,

I tried the documentation examples (http://mongoosejs.com/docs/populate.html) to understand how the populate method works and I got it worked without problem. But I would need to "force" the collection name like this:

``` javascript
var Story  = mongoose.model('Story', StorySchema, 'Story');
var Person = mongoose.model('Person', PersonSchema, 'Person');
```

instead of the doc example:

``` javascript
var Story  = mongoose.model('Story', StorySchema);
var Person = mongoose.model('Person', PersonSchema);
```

If I do that, populate doesn't work anymore. Instead of populating an array of object id with the corresponding documents, it just sets an empty array.

How could I make this works please?
Thank you very much!

**Comment by zain-creation** [comment]
hi @aheckmann i have the same problem with "mongoose": "~3.8.8" how i can fix this, this is my post on stackover http://stackoverflow.com/questions/29037348/mongoosejs-populate-doesnt-return-any-data , thnks :) .

**Comment by vkarpov15** [comment]
@zain-creation SO answer is correct - your Company schema is incorrect. Should look like this

```javascript
var CompanySchema = new Schema({
....
admins: [{type: Schema.Types.ObjectId, ref: 'Agent'}],
....
```
