### ISSUE TITLE
DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead

### ISSUE THREAD

**Issue by farazkhanfk7** [Automattic/mongoose#8773]
I have added `createIndex: true` like:
`mongoose.connect('mongodb://localhost/blogs',{ useNewUrlParser: true, useUnifiedTopology: true, createIndexes : true});`

But it is still showing the same DeprecationWarning.
`the options [createIndexes] is not supported
(node:15104) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`
npm version : 6.13.4
node version : v12.16.1
mongoose@5.9.7

**Comment by vkarpov15** [comment]
https://mongoosejs.com/docs/deprecations.html
