### ISSUE TITLE
insertMany fails silently by returning empty array if all the documents are invalid

### ISSUE THREAD

**Issue by tusharf5** [Automattic/mongoose#8776]
First of all thanks to all the contributors & the author for such a useful and amazing MongoDB library.

**Do you want to request a *feature* or report a *bug*?**

Bug

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a schema with a required field.
2. Create array of 100 documents that don't have that required field.
3. Insert those docs using the below options
```js
const res = await Model.insertMany(docs, { ordered: false, rawResult: true });
// res is []
```

**What is the expected behavior?**
It should return with a object with `mongoose.validationErrors` property instead of silently failing and returning an empty array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node - node:12.16-stretch-slim
mongoose - ~5.9.7

**Comment by AbdelrahmanHafez** [comment]
This is due to the fact that we're passing `ordered: false`. If you omit that, an error will be thrown.

I found the following in [the docs](https://mongoosejs.com/docs/api/model.html#model_Model.insertMany):

>Mongoose always validates each document before sending insertMany to MongoDB. So if one document has a validation error, no documents will be saved, unless you set the ordered option to false.

I think this behavior is by design and is inherited from the MongoDB driver since the native driver behaves [the same way](https://docs.mongodb.com/manual/reference/method/db.collection.insert/#db.collection.insert) when using `ordered: false`, it fails silently.

The script below passes, but correctly fails when we add `ordered: false`.
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  name: { type: String, required: true },
  age: Number
});

const User = mongoose.model('User', userSchema);

run().catch(console.error);

async function run () {
  await User.deleteMany();

  const err = await User.insertMany([{ age: 25 }]).catch(err => err);
  assert.ok(err.message.includes('Path `name` is required'));
}
```

**Comment by tusharf5** [comment]
It does report a list of errors if they are coming from the database.

According to me `ordered: false` implies that if a doc fails (either **client side validation** or **database write error**) it won't stop the other docs from saving if they are valid and at the end it returns a list of all the validation or write errors of unsuccessful documents that were not saved.

So I don't think that in this case returning just a `[]` would help even if it's by design as it should return a list of client side validation errors (in the above case).

**Comment by AbdelrahmanHafez** [comment]
`ordered: false` sends the valid docs all the way to the mongo side, but omits the invalid (client side) docs.


If you need to know the client-side errors, and the mongo-side errors you could do the following:
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const userSchema = new Schema({
  _id: Number,
  name: { type: String, required: true },
  age: Number
});

const User = mongoose.model('User', userSchema);

run().catch(console.error);

async function run () {
  await User.deleteMany();

  const docs = [
    { _id: 1, name: 'John' },
    { _id: 1, name: 'Hafez' }, // server-side error, _id is duplicated
    { _id: 2, name: 'Jane' },
    { _id: 3, name: null } // client-side error, name is required
  ]
    .map(doc => new User(doc));

  // caught client-side errors
  const mongooseErrors = docs.map(doc => doc.validateSync()).filter(Boolean);
  assert.ok(mongooseErrors[0].message.includes('Path `name` is required'));

  // caught server-side error
  const mongoError = await User.insertMany(docs, { ordered: false }).catch(err => err);
  assert.ok(mongoError.message.includes('E11000 duplicate key'));

  // all valid documents were successfully inserted, even though errors happened
  const insertedUsersCount = await User.countDocuments();
  assert.equal(insertedUsersCount, 2);
}
```

**Comment by tusharf5** [comment]
Thanks for the clarification. So according to your explanation by specifying `ordered: false` mongoose will not report client-side validation errors.

Doesn't make sense to me. If it is doing client-side validation then why not reporting client-side errors?

Also in the case where all the documents are invalid from client side validation mongoose shouldn't just return an empty array `[]`. That doesn't help at all. It could return the object that it returns whenever there is a successful write with its `insertedCount ` property set to `0`, `ops` as `[]` and `insertedIds ` as `{}`. Or even better if it adds a `mongoose.validationErrors` path which has all the  validation errors.

This(#7822) issue is for the same bug

**Comment by tusharf5** [comment]
I see the issue. 

When `rawResult` is `false`. We expect the result of `insertMany` to be an array of docs. When it fails we can expect the array to be `[]`.

This code (line `3352`) is responsible for that. https://github.com/Automattic/mongoose/blob/b30213869c3e2c48bc3daa24b3eb28b8b36718d6/lib/model.js#L3346-L3354

When `rawResult` is `true`. We get the result of `insertMany` inside an object `{ ops: [], errors: [], ..etc }` which is the raw object coming from the driver.

So when it fails one could expect the error to be inside of an object as well but we still get an array `[]` because of the code snippet above.

Makes sense to me now. Maybe could add something like this for consistency but not required though.

```js
 // Quickly escape while there aren't any valid docAttributes 
if (docAttributes.length < 1) {
  if (rawResult) {
    res.mongoose = {
      validationErrors: validationErrors,
    };
    return callback(null, res);
  }
  callback(null, []);
  return;
}
```

**Comment by AbdelrahmanHafez** [comment]
@tusharf5 that sounds fine by me, PRs welcome.
@vkarpov15 any thoughts on adding mongoose validation errors to raw result on insertMany with ordered: false?

**Comment by tusharf5** [comment]
I would like to see @vkarpov15 thoughts on this too. If it sounds good I can definitely submit a PR ✅

**Comment by AbdelrahmanHafez** [comment]
I don't think adding a property to the return value is a backward-breaking change.

**Comment by tusharf5** [comment]
Currently, if all the docs are invalid and `rawResult` is `true` it returns a `[]`. We have code in production that detects this scenario based on this result. If, it starts returning `{ errors: [...errors] }` then I guess that would break the code.

**Comment by tusharf5** [comment]
@vkarpov15 Let me know if I can submit a PR for this issue if you're not already working on it.

**Comment by vkarpov15** [comment]
@tusharf5 please submit a PR, I am not working on this issue currently.
