### ISSUE TITLE
Make minLength and maxLength behave the same as `minlength` and `maxlength`

### ISSUE THREAD

**Issue by m-weeks** [Automattic/mongoose#8777]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
`minLength` and `maxLength` validators are not giving errors for a `String` type as stated in the documentation at https://mongoosejs.com/docs/schematypes.html#string-validators and https://mongoosejs.com/docs/validation.html#built-in-validators

**If the current behavior is a bug, please provide the steps to reproduce.**

```
var EmployeeSchema = new mongoose.Schema({
  name: {
    type: String,
    maxLength: 100
  } ,
  bio: {
    type: String,
    minLength: 300
  }
});

var Employee = mongoose.model('Employee', EmployeeSchema);

var emp = new Employee({ name: 'a'.repeat(101), bio: 'b'.repeat(10) });

// no error thrown
emp.validate();
```

**What is the expected behavior?**
Errors should be thrown for violating the `minLength` and `maxLength` validators

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 12.16.1
mongoose: 5.9.7
Mongodb: 4.0.6

**Comment by lineus** [comment]
You've got a couple of typos, it should be `minlength` and `maxlength` as it appears in the docs. I've done the same thing :)

**Comment by m-weeks** [comment]
> You've got a couple of typos, it should be `minlength` and `maxlength` as it appears in the docs. I've done the same thing :)


Agh! I was baffled as to why it couldn't work. Can't believe I didn't think to check that it may not be camelCase!

**Comment by FlameFractal** [comment]
May I pick this @vkarpov15?

**Comment by vkarpov15** [comment]
Sure :+1:
