### ISSUE TITLE
Custom prototype method.

### ISSUE THREAD

**Issue by bhushan90** [Automattic/mongoose#8781]
It there any way to add custom prototype methods for mongoose.
I like to add my custom prototype method for pagination.
But it it not working.

I had tried below code
![15866010473545970146449677801408](https://user-images.githubusercontent.com/22069932/79041471-c7662280-7c0d-11ea-9be9-673147b2918d.jpg)

**Comment by AbdelrahmanHafez** [comment]
Welcome @bhushan90 
You could use a [static](https://mongoosejs.com/docs/guide.html#statics) along with a [global plugin](https://mongoosejs.com/docs/plugins.html#global)
```js
// assign this static function to all your mongoose models
mongoose.plugin(function (schema) {
  schema.statics.paginate = function (page, count, filter) {
    if (page <= 0) page = 1;
    if (count <= 0) count = 1;

    return this.find(filter).skip((page - 1) * count).limit(count);
  };
});

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

// now `User` model has the `paginate` static function
User.paginate();
```
Also, you may find one of these two plugins useful: [mongoose-paginate
](https://www.npmjs.com/package/mongoose-paginate) [mongoose-paginate-v2
](https://www.npmjs.com/package/mongoose-paginate-v2)

**Comment by vkarpov15** [comment]
Looks like you're looking for query helpers. See:

* https://mongoosejs.com/docs/guide.html#query-helpers
* http://thecodebarbarian.com/mongoose-custom-query-methods.html

**Comment by bhushan90** [comment]
> Welcome @bhushan90
> You could use a [static](https://mongoosejs.com/docs/guide.html#statics) along with a [global plugin](https://mongoosejs.com/docs/plugins.html#global)
> 
> ```js
> // assign this static function to all your mongoose models
> mongoose.plugin(function (schema) {
>   schema.statics.paginate = function (page, count, filter) {
>     if (page <= 0) page = 1;
>     if (count <= 0) count = 1;
> 
>     return this.find(filter).skip((page - 1) * count).limit(count);
>   };
> });
> 
> const userSchema = new Schema({
>   name: { type: String }
> });
> 
> const User = mongoose.model('User', userSchema);
> 
> // now `User` model has the `paginate` static function
> User.paginate();
> ```
> 
> Also, you may find one of these two plugins useful: [mongoose-paginate ](https://www.npmjs.com/package/mongoose-paginate) [mongoose-paginate-v2 ](https://www.npmjs.com/package/mongoose-paginate-v2)

Thank you so much for the help.

**Comment by bhushan90** [comment]
> Looks like you're looking for query helpers. See:
> 
> * https://mongoosejs.com/docs/guide.html#query-helpers
> * http://thecodebarbarian.com/mongoose-custom-query-methods.html

Thank yiu so much 🙂
