### ISSUE TITLE
Mongoose support for distributed transactions 

### ISSUE THREAD

**Issue by linus-hologram** [Automattic/mongoose#8787]
Hey there,

starting with 4.2, MongoDB supports distributed transactions. However, I haven’t found any documentation on how to do this with mongoose. Now I‘m wondering, if this is even possible with mongoose?

I know that this is actually the type of question that should be asked on StackOverflow. Unfortunately, I‘m not getting any answer and start to think that it’s not supported at all with mongoose (at least the docs don’t mention it)

For more details, I‘ve opened [this](https://stackoverflow.com/q/60849686/10203069) SO question.

I would be extremely glad if docs regarding distributed transactions would be added, provided they are supported.

**Comment by vkarpov15** [comment]
@linus-hologram as far as MongoDB clients (like Mongoose) are concerned, a distributed transaction is just a transaction. All the code in our [transactions docs](https://mongoosejs.com/docs/transactions.html) should work as written with distributed transactions in MongoDB 4.2.
