### ISSUE TITLE
i cant use mongoose on goorm.io and im new to development and dont understand what to do really

### ISSUE THREAD

**Issue by Abdelrahmanyassin786** [Automattic/mongoose#8789]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome @Abdelrahmanyassin786

It's really difficult to help without knowing enough details about what's happening, please open a new issue and try to fill the issue template as much as possible.

Perhaps share what appears in the logs?
