### ISSUE TITLE
Model.create(...) with an empty array should return an empty array

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8792]
Currently `await Model.create([ ])` returns `undefined`, I think it would make things more consistent if we were to return an empty array instead of `undefined`, so people won't have to check if dynamically constructed arrays have items in them or not.

I found some tests asserting that create with an empty array returns undefined, is this for internal testing? Or would it count as breaking changes?

**Comment by vkarpov15** [comment]
If there are tests that assert on this behavior, then that would count as a backwards breaking change. But I'm supportive of this change :+1:
