### ISSUE TITLE
querySrv ESERVFAIL MongoDB Atlas Issue 

### ISSUE THREAD

**Issue by Dsabillon** [Automattic/mongoose#8797]
I have this error from console Error: querySrv ESERVFAIL _mongodb._tcp.cluster0-s1rkv.mongodb.net.

**Comment by vkarpov15** [comment]
I think you're using the `mongodb+srv://` URL for Atlas. Try using the URL that doesn't have `+srv`.

**Comment by SamratDe** [comment]
@vkarpov15 I tried that one also. It connects for the first time after I changed the URL but after that it fails everytime.
