### ISSUE TITLE
Lean documents don't include subdocuments

### ISSUE THREAD

**Issue by mwanago** [Automattic/mongoose#8800]
**Do you want to request a *feature* or report a *bug*?**
It looks like it might be a bug

**What is the current behavior?**
I have the following schemas:
```
const departmentSchema = new mongoose.Schema({
  name: String,
  fieldsOfStudy: [fieldOfStudy],
  university: {
    ref: 'University',
    type: mongoose.Schema.Types.ObjectId,
  },
});
```
```
const fieldOfStudy = new mongoose.Schema({
  name: String,
  calculations: [calculation],
  thresholds: [threshold],
});
```
The crucial part here is that the `fieldOfStudy` is a subdocument.

I wanted to `find()` the departments in a lean format.
```
const departmentModel = mongoose.model<Department & mongoose.Document>('Department', departmentSchema);
```
```
departmentModel.find().lean();
```
It returns me an array of `Departments`.
Unfortunately, they don't include `fieldsOfStudy`.

**What is the expected behavior?**
I think my `Departments` should include `fieldsOfStudy`. I am aware that lean documents don't include things like virtuals, but I don't think the documentation mentions anything about subdocuments.
Is the above behavior intended?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 12.6.0
Mongoose: 5.9.9
MongoDB: 3.6.12 (mlab)

**Comment by mwanago** [comment]
That's interesting.. looks like `fieldsOfStudy` were undefined just in **some** cases.
I think Mongoose replaced missing `fieldsOfStudy` by empty arrays by default, but couldn't do that with lean documents.

**Comment by AbdelrahmanHafez** [comment]
Welcome @mwanago 
Can you modify the script below to demonstrate the issue you're facing?

```js
// 8800
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const fieldOfStudySchema = new Schema({ name: String });

  const departmentSchema = new Schema({
    name: String,
    fieldsOfStudy: [fieldOfStudySchema]
  });

  const Department = mongoose.model('Department', departmentSchema);


  await Department.create({ name: 'A', fieldsOfStudy: [{ name: 'field-a' }, { name: 'field-b' }] });


  const departments = await Department.find().lean();

  const fieldsNames = departments[0].fieldsOfStudy.map(field => field.name);
  assert.deepEqual(fieldsNames, ['field-a', 'field-b']);

  console.log('Done.');
}
```
