### ISSUE TITLE
Can't validate() the same doc multiple times in parallel - after updating to 5.9.9

### ISSUE THREAD

**Issue by iliakan** [Automattic/mongoose#8803]
Not sure if it's a bug or a feature.

I updated mongoose 5.4 to 5.9.9 and started to get error reports.

Saving an object now gives the error in some cases: "Can't validate() the same doc multiple times in parallel."

I browsed related issues. I don't run `validate` in parallel. I don't `save` in parallel.

The message sounds so odd, I'm not sure where to dig.

Could you provide any hint?

**Comment by vkarpov15** [comment]
@iliakan take a look at the stack trace to see where the `validate()` call is. One potential cause for this is calling `doc.validate()` before calling `doc.save()`, do you do that?

**Comment by iliakan** [comment]
@vkarpov15 as the issue was critical, I had to downgrade to 5.4.x.

And yes, I have calls `doc.validate()` before `doc.save()`. But these calls are separate. There's no parallel validation and saving.

Anything wrong with sequential validate → save calls?

**Comment by AbdelrahmanHafez** [comment]
Make sure you're waiting for the validation to end before trying to save, Document#validate returns a promise:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String, required: true }
  });

  const User = mongoose.model('User', userSchema);

  const user = new User({ name: 'Hafez' });

  await user.validate();
  await user.save();

  assert.ok(user.name);
  assert.ok(!user.isNew);
}
```

**Comment by iliakan** [comment]
Oh, I remember there was something like `validateAsync` and `validate`, was that changed?

Now `validate()` is the only method and it's async?

**Comment by AbdelrahmanHafez** [comment]
No, validateSync still exists, if you replace `await user.validate()` with `user.validateSync()` in the script above, you'll get the same results.

**Comment by iliakan** [comment]
Thanks!

**Comment by AbdelrahmanHafez** [comment]
Happy to help, out of curiosity was that the problem? Not waiting for validation to happen before trying to save?

**Comment by iliakan** [comment]
Yeah, there was no `await` before `.validate()` call. I somewhy thought that it's running only sync checks.

**Comment by iliakan** [comment]
Guess, that's a bug, in other places there's `await`. Mongoose 5.4. didn't complain about that, guess 5.9 behavior is better.
