### ISSUE TITLE
Discrepancies between Mongoose pool size and actual connections being made

### ISSUE THREAD

**Issue by 605kiya** [Automattic/mongoose#8805]
**Do you want to request a *feature* or report a *bug*?**
- Not necessarily a bug but want to understand if this is the expected behavior.
 
**What is the current behavior?**
- I am using mongoose `v5.9.9` to connect to my MongoDb cluster in MongoDb Atlas. I have specified for a max pool size of 5 (i know this is the default by nature). That being said, I'm also caching my db connections so they can be reused instead of opening new connections. I am also logging every query by MongoDB cluster based on if my application is using a cached connection or a new one. 

- That being said, I would not expect more than 5 connections happening on my MongoDb cluster. The problem is, when I view my connection logs provided by MongoDB atlas, I'm seeing an upwards of 70 active connections (i was doing performance testing by hitting my applications endpoints that makes queries against my mongodb cluster).

![image](https://user-images.githubusercontent.com/19699368/79540244-6bf0c600-804d-11ea-9d3a-0b0395e8d3b4.png)

Here is the code I'm using for my apps db connections:

```TypeScript
import mongoose from "mongoose";

let cachedDBConnection = null;

async function connectToDB(uri) {
  if (cachedDBConnection) {
    console.log(`Using cached connection. Connection number: ${cachedDBConnection.connections[0].id}`)
    return cachedDBConnection;
  } else {
    const dbConnection = await mongoose.connect(uri, {
      useNewUrlParser: true,
      useCreateIndex: true,
      useUnifiedTopology: true,
      useFindAndModify: false,
      poolSize: 5,
    });
    cachedDBConnection = dbConnection;
    console.log(`Using new connection. Connection number: ${dbConnection.connections[0].id}`)
    return dbConnection;
  }
}

export default async () => {
  await connectToDB(process.env.MONGODB_URL);
};
```

I'm calling the above dbconnection from my api routers as such:

```TypeScript
await mongoose();
```
- Any insight would be much appreciated

**What is the expected behavior?**
- The expected behavior is for mongoose to limit the number of connections my app is making to my mongodb cluster based on the `poolSize` parameter provided in the `mongoose.connect` call.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node version: `v12.14.0`
- Mongoose version: `v5.9.9`
- MongoDB: `Atlas`

**Comment by kiyapedia** [comment]
@aheckmann @AbdelrahmanHafez any insights on this?

**Comment by vkarpov15** [comment]
@kiyapedia do you have only 1 app server, or multiple? Also, your code has a race condition: if multiple `connectToDb()` calls happen before `cachedDBConnection` is set, you'll get multiple `mongoose.connect()` calls.

**Comment by kiyapedia** [comment]
@vkarpov15 — so my app is running on Zeit (Zeit.com) which is a serverless platform. So i'm abstracted from the underlying server. 

As far as the race condition, do you suggest not having the cached db section? Is there a preferred way in mongoose to cache DB connections?

**Comment by vkarpov15** [comment]
I'd recommend you do something similar to what is suggested in our [Lambda docs](https://mongoosejs.com/docs/lambda.html):

```javascript
let conn = null;

exports.connectToDb = async function(event, context) {
  if (conn == null) {
    conn = mongoose.createConnection(uri);
    await conn;
  }
  return conn;
}
```

I also don't think you can accurately predict the number of connections if you're running on a serverless platform. Now / Vercel may end up running different function calls in different containers, leading to double the connections.

**Comment by AbdelrahmanHafez** [comment]
fixed by https://github.com/Automattic/mongoose/pull/8847/commits/a359cc184688463178790cb370551dedd88d8e2b
