### ISSUE TITLE
DB connection doesn't start: Error: querySrv ESERVFAIL

### ISSUE THREAD

**Issue by akiosTerr** [Automattic/mongoose#8811]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

Sometimes the DB starts normally and sometimes doesn't, and sometimes the DB starts even with the error and works normally.
I was using mongoose **5.9.3** and updated to **5.9.9**, but the error persisted.
It was working normally earlier.

**What is the current behavior?**
```
Error: querySrv ESERVFAIL _mongodb._tcp.databasename-zcbag.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:202:19) {
  errno: 'ESERVFAIL',
  code: 'ESERVFAIL',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.databasename-zcbag.mongodb.net'
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**

here is the code:
```javascript
mongoose.connect(uri, {
	useUnifiedTopology: true,
	useNewUrlParser: true,
	useCreateIndex: true,
});
const connection = mongoose.connection;

connection
	.once('open', () => {
		console.log('mongoDB database connection established');
	})
	.on('error', (err) => {
		console.log('Error: ', err);
	});

```

**What is the expected behavior?**

It should connect to the DB normally 

Node: v12.14.1
Mongoose: 5.9.9
MongoDB: 4.2

**Comment by vkarpov15** [comment]
Try the following 3 options:

1) Use the alternate Atlas connection string that doesn't use `+srv`.
2) If you're running this code locally, try using a different internet provider, like using your phone's hotspot instead of your home wi-fi or vice versa. Some ISPs have trouble with Atlas.
3) Make sure you've [added all your IPs to the IP whitelist](https://docs.atlas.mongodb.com/security-whitelist/). I'd recommend allowing access from anywhere if you're having trouble connecting.

**Comment by akiosTerr** [comment]
1 - removing +srv locally gives a network error
2 - no chance of using another ISP 
3 - I already added 0.0.0.0/0 to Atlas to allow all IPs

what is weird about this bug specifically is that is not really constant, sometimes it works
and sometimes don't, as I explained in the question, sometimes even with this error the mongoose connects to DB. I don't really know what's causing it

**Comment by domssilva** [comment]
I'm having this exact same issue. sometimes it works sometimes it doesn't

**Comment by vkarpov15** [comment]
@akiosTerr what error do you get when you remove `+srv`? Make sure you use the alternate URL format, don't just use 'mongodb://databasename-zcbag.mongodb.net:27017'

**Comment by nicholasmullikin** [comment]
I had the same problem, but I resolved it by using a VPN with port forwarding. Perhaps there is some ISP level problems? I tried to use the non srv link without the VPN with no success.

**Comment by akiosTerr** [comment]
@vkarpov15 

### this is my URI : 

```
"mongodb+srv://username:passcode@databasename-zcbag.mongodb.net/test?retryWrites=true&w=majority"
```
### if I remove "+srv" it gives this error:

```
 message: 'getaddrinfo ENOTFOUND databasename-zcbag.mongodb.net',
  name: 'MongooseServerSelectionError',
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'databasename-zcbag.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  },
  [Symbol(mongoErrorContextSymbol)]: {}
```

MongooseServerSelectionError is the same kind of error that shows up when I'm trying to connect the DB inside Heroku, the only difference is the ENOTFOUND argument that shows up.

**Comment by vkarpov15** [comment]
@akiosTerr When I say the URL without `+srv`, I mean the one for older versions of the driver that should look something like:

```
mongodb://<username>:<password>@cluster0-shard-00-00-zcbag.mongodb.net:27017,cluster0-shard-00-01-zcbag.mongodb.net:27017,cluster0-shard-00-02-xvnqv.mongodb.net:27017/zcbag?ssl=true&replicaSet=Cluster0-shard-0&authSource=test&retryWrites=true&w=majority
```

**Comment by aifeipeng** [comment]
A colleague is experiencing the same problem, have you found a solution to this?
If he tries to use the older version of connection string he gets the error that he should add his IP address to the whitelist but he has added 0.0.0.0/0 (and his own IP) which should be all IPs

**Comment by vladimir-fadi** [comment]
We have the same issue in our k8s cluster, the legacy URL workaround works, but it's frustrating that the same URL doesn't work in Mongo Shell and in the library. Is the bug related to SRV record lookup somehow?

**Comment by vkarpov15** [comment]
@vladimir-fadi not sure, but the legacy URL should work with both the mongo shell and Mongoose. If `+srv` doesn't work for you, then don't use it.
