### ISSUE TITLE
Make `autoCreate` true by default

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8814]
Change streams and transactions don't work unless the collection already exists, so it would be helpful if `autoCreate` was automatically set so you could just call `Model.init()`.

**Comment by deser** [comment]
In documentation there is note that autoCreate is not supposed for production. Why it is written so? With mongoose 6 it will be ok for production?

**Comment by vkarpov15** [comment]
That's a good point. The reason why we're considering this change is for consistency with `autoIndex`: `autoIndex` is true by default, and we recommend turning that option off in prod as well. Worth thinking more about whether we optimize defaults for ease of development or ease of running in prod.

**Comment by deser** [comment]
But what should I do then when I can have some absent collections which might be created within transactions in prod ( I have 4.2)? Isn't `autoCreate` is the only option we have here besides calling `createCollection` manually (which is what `autoCreate` eventually does)?

**Comment by vkarpov15** [comment]
You would have to call `createCollection()`. However, it is unlikely that you would have to automatically create collections in prod, which is why we don't recommend `autoCreate` for prod: in most applications it is an extra round trip to the database when the app starts up that typically doesn't do anything, because in most cases the collection already exists.

**Comment by deser** [comment]
I think if this is the only reason you don't recommend to have `autoCreate` turned on in prod then it might be incorrect. On my project I am pretty ok about these roundtrips and I don't want to implement `autoCreate` by myself to not create mistakes in code. I must be sure that all collections create for transactions to not fail.

**Comment by vkarpov15** [comment]
In that case I think you're fine to enable `autoCreate` in prod.

**Comment by deser** [comment]
So documentation should mirror that case then and be not so strict on `not using autoCreate` in prod :)
