### ISSUE TITLE
Arrays don't validate empty strings

### ISSUE THREAD

**Issue by erezarnon** [Automattic/mongoose#8821]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Array elements which are empty strings don't run through validators

**If the current behavior is a bug, please provide the steps to reproduce.**

const TestModelSchema = new mongoose.Schema({
    array: {type: [{type: String, minlength: 1, maxlength: 128, required: true}], default: undefined},
})

const TestModel = mongoose.model('TestM', TestModelSchema);
TestModel.validate({array: ['']}).then(console.log)

**What is the expected behavior?**
Validation should give an error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs 12.16.2
mongo 3.6.3
mongoose 5.9.9

**Comment by AbdelrahmanHafez** [comment]
I can confirm that validation doesn't throw an error in this case, repro script:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run () {
  const userSchema = new Schema({
    friends: [{ type: String, required: true }]
  });

  const User = mongoose.model('User', userSchema);
  const err = await User.validate({ friends: [null] }).catch(err => err);

  assert.ok(err);

  console.log('Done.');
}
```
