### ISSUE TITLE
findOneAndDelete()

### ISSUE THREAD

**Issue by AmritaKumari59** [Automattic/mongoose#8826]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome @AmritaKumari59 
Without providing enough information, we can't help you solve the issue you're facing. I'll close this issue, please open a new issue following the issue template.
