### ISSUE TITLE
Whitelist Own's IP not working but 'allow from anywhere' works, not application's intention.

### ISSUE THREAD

**Issue by Maritcode** [Automattic/mongoose#8827]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce.**

Using mongoose connect to mongo atlas. Whitelist IP 'Allow from anywhere' works perfectly but this is not the application's intention. Whitelist 'Current IP' pops the following error message.
```
connection error: MongooseError [MongooseServerSelectionError]: con
nection <monitor> to XX.XXX.XXX.XXX:27017 closed
```

**What is the expected behavior?**
Connection Success, just like how 'Allow from anywhere' works.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose@5.9.9
mongodb@3.5.5
node@v12.14.1
```

**Comment by tusharf5** [comment]
1. Check if you are able to connect via shell from your local machine. If not, then there must be a problem with your network/firewall settings. The most common source of this error is a missing Atlas whitelist entry for the public IP address where your application is running.
2. Try to connect using the following code
```js
async function connect() {
  const connection = await mongoose.connect('connection_string_from_atlas', {
         useNewUrlParser: true,
         dbName: 'YOUR_DATABASE_NAME',
         keepAlive: true,
         useUnifiedTopology: true,
         useFindAndModify: false
    });
}
```

**Comment by Maritcode** [comment]
1. Turn off firewall and no restriction network setting. Added both private + public IPv4 address into whitelist. Still not working. Switched to 'Allow from anywhere' and it works again. Tested outgoing port @ http://portquiz.net:27017/ . My outgoing port is working fine though.

2. Tried the code. Still facing the same problem.

3. Removed and reinstall the node modules. Still same issues.

**Comment by tusharf5** [comment]
Where is your application hosted ?

**Comment by Maritcode** [comment]
Localhost. Dev environment.

**Comment by tusharf5** [comment]
I've been able to connect to multiple MongoDb Atlas clusters using different I.P settings. So this issue is possibly specific to your network settings and not necessarily a mongoose bug. I think it would be better to close this here and post this as a question on stackoverflow where people who've faced similar issues will be able to help you better.

Search **My public IP** on google and use that address on Atlas Settings. FYI these local IP addresses in most cases are dynamic and not static.

**Comment by vkarpov15** [comment]
For local development, I wouldn't recommend connecting to Atlas, especially if you have concerns about whitelisting all IPs. In my experience, running MongoDB locally for dev is much cleaner.
