### ISSUE TITLE
Unable to install mongoose

### ISSUE THREAD

**Issue by saravanakumarputta** [Automattic/mongoose#8830]
Got the error below on installing mongoose npm

Saravanas-MacBook-Pro:personalblog saravanan$ npm i -S mongoose
npm ERR! Unexpected end of JSON input while parsing near '....4.5":{"name":"bson",'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saravanan/.npm/_logs/2020-04-21T06_37_28_257Z-debug.log
Saravanas-MacBook-Pro:personalblog saravanan$ npm i mongoose
npm ERR! Unexpected end of JSON input while parsing near '....4.5":{"name":"bson",'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saravanan/.npm/_logs/2020-04-21T06_37_56_327Z-debug.log
Saravanas-MacBook-Pro:personalblog saravanan$

**Comment by AbdelrahmanHafez** [comment]
Could you verify that your package.json is valid JSON?
Can you install other packages?

**Comment by saravanakumarputta** [comment]
> Could you verify that your package.json is valid JSON?
> Can you install other packages?

Yes, Am able to install the other packages.

**Comment by tusharf5** [comment]
@saravanakumarputta  Try this and see if it works.

1. Remove `node_modules` folder
2. Remove `package-lock.json`
3. Remove `yarn.lock`
4. Run `npm cache clean --force`
5. Run `yarn cache clean`
5. Run `npm install`

**Comment by vkarpov15** [comment]
As @tusharf5 suggested, try clearing out `package-lock.json` and clear the cache. It looks like bson's `package.json` is cut off for some reason.

**Comment by saravanakumarputta** [comment]
> As @tusharf5 suggested, try clearing out `package-lock.json` and clear the cache. It looks like bson's `package.json` is cut off for some reason.

clearing the cache solved the issue. Thanks.
