### ISSUE TITLE
DB does not connect on Heroku Server. [MongooseServerSelectionError]

### ISSUE THREAD

**Issue by akiosTerr** [Automattic/mongoose#8832]
I am trying to deploy my app on Heroku, but Heroku doesn't start my DB connection.
It works normally on the local environment, I already configured the env variable inside Heroku settings with the URI, I am using React so I named the variable REACT_APP_MONGODB_URI, I don't know if that makes a difference in Heroku.

**Full Error:**

```
MongooseError [MongooseServerSelectionError]: connection <monitor> to 52.73.107.218:27017 closed
message: 'connection <monitor> to 52.73.107.218:27017 closed',
name: 'MongooseServerSelectionError',
reason: TopologyDescription {
type: 'ReplicaSetNoPrimary',
setName: null,
maxSetVersion: null,
maxElectionId: null,
servers: Map {
'dbname-shard-00-00-zcbag.mongodb.net:27017' => [ServerDescription],
'dbname-shard-00-01-zcbag.mongodb.net:27017' => [ServerDescription],
'dbname-shard-00-02-zcbag.mongodb.net:27017' => [ServerDescription]
},
 stale: false,
compatible: true,
compatibilityError: null,
logicalSessionTimeoutMinutes: null,
heartbeatFrequencyMS: 10000,
localThresholdMS: 15,
commonWireVersion: null
},
[Symbol(mongoErrorContextSymbol)]: {}

```

**The server script.**
```javascript
mongoose.connect(uri, {
	useUnifiedTopology: true,
	useNewUrlParser: true,
	useCreateIndex: true,
});
const connection = mongoose.connection;

connection
	.once('open', () => {
		console.log('mongoDB database connection established');
	})
	.on('error', (err) => {
		console.log('Error: ', err);
	});
```

**Versions**
Node: v12.14.1
Mongoose: 5.9.9
MongoDB: 4.2

**Comment by vkarpov15** [comment]
Have you added your Heroku IP to [the IP whitelist](https://docs.atlas.mongodb.com/security-whitelist/)? 

Also, how does the error you pasted relate to the "full error"? The first error message you pasted is indicative of a DNS error, where Mongoose can't resolve a hostname. The 2nd error message is indicative of Mongoose connecting to the server but losing connection, possibly due to whitelisting.

**Comment by akiosTerr** [comment]
The first error happens on the local env only when I remove the +SRV from the URI.
I mentioned just as context.

the second Error is the main problem,
 something is preventing the Heroku app from connecting to the database.

I could not find an Heroku IP
Instead, I added the IP 0.0.0.0/0 to the IP whitelist , in order to allow all IP addresses 

 I whitelisted the IP 0.0.0.0/0  on MongoDB Altas to allow all IP addresses 
(I don't really know if there is an IP for the Heroku App, I couldn't find one)

**Comment by akiosTerr** [comment]
[This answer from stackoverflow](https://stackoverflow.com/a/31932476/12788452), says that Heroku won't provide an static IP address, but you can use add-ons to achieve that.

But since I already allowed all IPs by adding 0.0.0.0/0 IP to the whitelist, 
this shouldn't be the problem right?

**Comment by mm-devpro** [comment]
Exactly the same problem for the same config, it seems like there is a problem with MongoDB connection, which has quite nothing to do with the code entered here....
Definitely need a hand as well

**Comment by jpmarinh92** [comment]
Having the same issue, works fine locally but once I upload the code to Heroku it doesn't work. Any solutions ?

**Comment by nikkster311** [comment]
I've had this issue for the past three weeks, I finally came back to it today. This video walked me through it.
https://www.youtube.com/watch?v=cRbf_33Rdo4
I hope it helps you too!

**Comment by akiosTerr** [comment]
@nikkster311 So that means the solution is using mLab instead of Atlas?

**Comment by nikkster311** [comment]
> @nikkster311 So that means the solution is using mLab instead of Atlas?

That was the solution I found, yes. There might be others, but this worked for me and I'm happy with it.

**Comment by mm-devpro** [comment]
With Atlas, I found a solution. You should enable all the ip's in the allow access part. It does the job, now is it that secure??

**Comment by akiosTerr** [comment]
@mm-devpro  how exactly did you enable all the ip's ?

**Comment by akiosTerr** [comment]
So, Heroku demands credit card information for using add-ons (even if it says that is free)
so I cant install mlab add-on. Its very frustrating, I am starting to think heroku is doing that on purpose, I tried MYSQL as well in a **PAID** database in a shared hosting plan from Hostgator. 
its works ok locally and then in Heroku it gives a strange error I cant fix just like this.
I know I am complaining in the wrong place, but this is what I get when I try to create a Ticket in Heroku.

"Technical support for **Free** applications is provided by the online community."

They can't do s***  for me unless I am paying, its really unfortunate.

**Comment by vkarpov15** [comment]
@akiosTerr I wish I could help more, but my only suggestions are (1) [follow these instructions for allowing inbound connections from all IPs to your Atlas cluster](https://docs.atlas.mongodb.com/security-whitelist/), and (2) don't use heroku. Easiest way would be to set up a free tier AWS EC2 instance or Azure VM and run your app there if you insist on a free solution.

**Comment by Spongeyboi** [comment]
I have the same problem on replit
