### ISSUE TITLE
updateOne hook not firing on child schema

### ISSUE THREAD

**Issue by andrewlorenz** [Automattic/mongoose#8838]
using mongoose 5.9.10
given:
```
const childSchema = new Schema({ text: { type: String }});
const parentSchema = new Schema({
  parent : { type: String },
  child : { type: childSchema },
});
childSchema.pre('updateOne', async function() { console.log('child updateOne'); });
parentSchema.pre('updateOne', async function() { console.log('parent updateOne'); });
```
but only the parent hook fires, not the childs?  I've also checked for save, find, and update hooks on the child but nothing fires.

**Comment by vkarpov15** [comment]
Document middleware, like `save()`, does fire on child schemas. But query middleware, like `findOne()`, does not. Please take a look at this section of the docs: https://mongoosejs.com/docs/middleware.html#notes
