### ISSUE TITLE
"01" and "1" create duplicate keys

### ISSUE THREAD

**Issue by Rickmey** [Automattic/mongoose#8841]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using "01" and "1" as unique strings will result in a duplicate key exception.
A zero in front of a number will be ignored.
"n012"/"n12" = duplicate key
"n120"/"n12" = okay

>MongoError: E11000 duplicate key error collection: coverinfo.artists index: uri_1 dup key: { uri: "C" }" }
>   [STACKTRACE]
>   driver: true,
>   index: 0,
>   code: 11000,
>   keyPattern: { uri: 1 },
>   keyValue: { uri: 'C\u000f\u0004\u0001\u0006\u0001\u0001\u0006\u0001' },
>   errmsg: 'E11000 duplicate key error collection: coverinfo.artists index: uri_1 dup key: { uri: "C\u000f\u0004\u0001\u0006\u0001\u0001\u0006\u0001" }',
>   [Symbol(mongoErrorContextSymbol)]: {}

**If the current behavior is a bug, please provide the steps to reproduce.**

No hooks, empty collection

```
Schema:
uri: { type: String, lowercase: true, unique: true, index: true, },
```

```
let artist1 = new ArtistModel({ uri: 'name-01' });
let artist2 = new ArtistModel({ uri: 'name-1' });
console.log(artist1.uri, artist2.uri);
await artist1.save();
console.log('artist 1 saved');
await artist2.save(); 
console.log('artist 2 saved');

Output:
// name-01 name-1
// artist 1 saved
// MongoError: E11000 duplicate key error collection: coverinfo.artists index: uri_1 dup key: { uri: "C"
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.9.10
mongodb: 4.2
node: v13.13.0

**Comment by Rickmey** [comment]
Thanks for the help.

I found the problem. Collation was active in the shema.

```
        collation: {
            locale: 'de',
            caseLevel: true,
            numericOrdering: true,
            strength: 4,
        },
```

**Comment by AbdelrahmanHafez** [comment]
Happy to help 👍
