### ISSUE TITLE
Unable to create multiple documents with references in same transaction

### ISSUE THREAD

**Issue by gaessaki** [Automattic/mongoose#8843]
**Do you want to request a *feature* or report a *bug*?**

Bug (or perhaps the behaviour is expected?)

**What is the current behavior?**

When creating a document with a reference to another and attempting to save them both in the same transaction, they fail to save.

```
ValidationError: Order validation failed: events: events references a non existing ID
    at new ValidationError (/Users/mansib/Documents/Project/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/Users/mansib/Documents/Project/node_modules/mongoose/lib/document.js:2555:32)
    at /Users/mansib/Documents/Project/node_modules/mongoose/lib/document.js:2377:17
    at /Users/mansib/Documents/Project/node_modules/mongoose/lib/schematype.js:1105:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
POST /api/orders 500 1268.570 ms - 23
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//simplified models
const OrderSchema = new Schema({
     number: { type: Number },
     items: { type: Schema.Types.ObjectId, ref: 'Product' },
     events: [{ type: Schema.Types.ObjectId, ref: 'OrderEvent' }]
});

const OrderEventSchema = new Schema({
    order: { type: Schema.Types.ObjectId, ref: 'Order', required: true },
    status: { type: String, enum: ['initialized', 'preparing', 'ready'] }
});

let Order = mongoose.model('Order', OrderSchema);
let OrderEvent = mongoose.model('OrderEvent', OrderEventSchema);

let session = await mongoose.startSession();
session.startTransaction();

try {
    let order = new Order({
        number: 5
    });

    let event = new OrderEvent({
        order: order.id,
        status: 'initialized'
    });

    await event.save({ session });
    order.events.push(event);
    await order.save({ session });
    await session.commitTransaction();
}
catch (err) {
    await session.abortTransaction();
}
finally {
    session.endSession();
}
```

**What is the expected behavior?**

What I'm attempting to do is to have the `OrderEvent` document fail to create if the `Order` itself fails to be created. My fallback right now consists of creating the event outside of the transaction and deleting it if the transaction is aborted.

I'm assuming the issue is that there is a race condition where neither document exists and thus can't be validated before being persisted.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js - 13.13.0_2
Mongoose - 5.9.10

**Comment by vkarpov15** [comment]
@gaessaki what plugin are you using for this? That error message 'references a non existing ID' doesn't come from Mongoose, Mongoose doesn't check if an id references a valid document before saving.

**Comment by gaessaki** [comment]
@vkarpov15 my apologies, I totally neglected that the issue may have been caused by a plugin. After going through them, seems like this one is the culprit: https://github.com/CampbellSoftwareSolutions/mongoose-id-validator.

Closing the issue. Thanks for the pointer as well as for all your great work on the project!
