### ISSUE TITLE
Connection.transaction: Reset `Document#isNew` if necessary when transaction is aborted

### ISSUE THREAD

**Issue by CombustiblePotato** [Automattic/mongoose#8852]
**Do you want to request a *feature* or report a *bug*?**
Question.

**What is the current behavior?**

I'm having a bit of hard time understanding the behaviour of the documents `save` method during transactions retries. As an transaction wrapper, I'm using [mongoose-tx](https://www.npmjs.com/package/mongoose-tx), only I had to modify it a bit by adding transaction abort if the database returned a `TransientTransactionError` :

```
        if (error.errorLabels && error.errorLabels.indexOf('TransientTransactionError') >= 0) {
            log.debug('TransientTransactionError, retrying transaction ...');
---->       await session.abortTransaction(); //Added here.
            await runTransactionWithRetry(txnFunc, session);
        } else {
            throw error;
        }
```

So the transaction itself is very simple: 

```
await Tx(async session => {
      await doc1.save({ session });
      await doc2.save({ session });
})
```

And it works fine when the transaction does not get errors, however, if I get a `TransientTransactionError` due to a `WriteConflictz then things get weird.

So for the above example, `doc2` is the one throwing the error and then two cases occur:

1. If `doc1` is a new document, then on the first transaction retry, it would throw a `DocumentNotFound` error and checking the `isNew` flag, I noticed that it was set to `false` even though the first transaction attempt failed (yes, `await session.abortTransaction()` was called.).

2. If `doc2` is not a new document, then on retry, it saves the document without errors, however due to the transaction error, it reverts any changes that were applied after retrieving it from the database.
  
**What is the expected behavior?**

I expected that `abortTransaction` would not revert the changes and for new documents it would reset the `isNew` flag. I don't know if this is the intended behaviour, but if it is, how do you properly handle retries with `save` ?

At the moment, as a workaround, I made a simple wrapper which either calls `Model.create` or `Model.updateOne` with modified paths instead of using `save`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.9.10
NodeJS: 12.15.0
MongoDB: 4.2.2

**Comment by vkarpov15** [comment]
Confirmed that this is an issue. Right now the only workaround is for you to manually set `isNew = true` on every document you tried to save in the transaction.

What we'll do for the next minor release is add a `mongoose.transaction()` or `db.transaction()` function that resetting `isNew` for you. There are also several other features that we want to support for transactions, like #8380, that would be nice to add.
