### ISSUE TITLE
Docs :: FAQ 1 :: That array changes are not save is not true for objects. Please update.

### ISSUE THREAD

**Issue by sgpinkus** [Automattic/mongoose#8854]
**Do you want to request a *feature* or report a *bug*?**
Bug in doc.

**What is the current behavior?**
Answer to [FAQ #1](https://mongoosejs.com/docs/faq.html#array-changes-not-saved) *"Why don't my changes to arrays get saved when I update an element directly?"* is only partially true. Quick scan of issues shows there is a lot of questions and confusion about arrays not saving. But array of objects *do* save (see below). This could easily lead one to think the behaviour is the same for primitives. The FAQ should be clearer about this.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
async function main() {
  let schema = new mongoose.Schema({
    objs: [{ txt: String, _id: false }],
    nums: [Number],
  });
  let Arrays = mongoose.model('Arrays', schema);
  await mongoose.connect('mongodb://localhost/test');
  await Arrays.deleteMany({});

  let d = new Arrays({
    objs: [{ txt: 1 }, { txt: 2 }, { txt: 3 }],
    nums: [1, 2, 3],
  });
  await d.save();
  d.objs[1].txt = 22;
  d.nums[1] = 22;
  console.log(d.isModified(), d.isModified('objs'), d.isModified('objs.1'), d.isModified('objs.2'));
  console.log(d.isModified(), d.isModified('nums'), d.isModified('nums.1'), d.isModified('nums.2'));
  await d.save();
  d = await Arrays.findById(d);
  console.log(d);
}
main().then(() => process.exit()).catch((e) => { console.error(e); process.exit(); })
```

*Give output:*

```
true true true false
true false false false
{
  nums: [ 1, 2, 3 ],
  _id: 5ea3c01300d915614d91d502,
  objs: [ { txt: '1' }, { txt: '22' }, { txt: '3' } ],
  __v: 0
}
```

**What is the expected behavior?**
N/A.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.9.9

```
Welcome to Node.js v12.16.2.
Type ".help" for more information.
> require('mongoose').version
'5.9.9'
```

**Comment by vkarpov15** [comment]
The docs are correct in the sense that `d.objs[1] = { txt: 22 }` won't save unless you use `markModified()`. We'll update the docs to reflect your suggestions.
