### ISSUE TITLE
Running Mongoose Transactions Periodically

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#8855]
**Do you want to request a *feature* or report a *bug*?**
Feature, if not exists, otherwise question

**What is the current behavior?**
I want to run the mongoose update and delete transactions periodically. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Currently, I am using node-cron, is there any feature in mongoose itself?

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Running things periodically is a cron job library's job, and out-of-scope for mongoose.
What you're doing is the right approach.
