### ISSUE TITLE
Mongoose is not working on the newest node version

### ISSUE THREAD

**Issue by ErezShahaf** [Automattic/mongoose#8859]
Hello, thought I would let you know that Mongoose does not work on node 14.0.0
it returns this error :

> (node:17848) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17848) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency  
(node:17848) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency   
(node:17848) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
(node:17848) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:17848) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Connected to database successfuly

**Comment by AbdelrahmanHafez** [comment]
Welcome @ErezShahaf

Those warnings do not mean that mongoose is not working, it means that something needs to be done to avoid a possible issue.

As for the circular dependency warnings, there is already [an issue](https://github.com/Automattic/mongoose/issues/8842) that's addressing those warnings.

As for `useNewUrlParser: true`, take a look at [mongoose deprecation warnings](https://mongoosejs.com/docs/deprecations.html).
