### ISSUE TITLE
[Docs] Model.insertMany(...) what does options.limit do?

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8864]
The only thing related to this I found was on #5529, which doesn't really explain much on what it does.

I assumed it would create batches with size of `limit` to avoid slow trains, but doing some debugging, it seems to be sending one big insert with all the documents.

Is this just limiting the number of documents processed (validated,/casted) on the mongoose side?

I also didn't find any `limit` option on the [MongoDB docs for insertMany](https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/).

**Comment by AbdelrahmanHafez** [comment]
Here's the script I used to test this out:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');
const sinon = require('sinon');

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  const users = Array.from({ length: 1000 }).map((v, i) => ({ name: i }));

  await User.init()

  const insertManySpy =  sinon.spy(User.collection,'insertMany');

  await User.insertMany(users,{limit:10});

  const collectionCalledWithDocsCount = insertManySpy.firstCall.args[0].length;

  assert.equal(collectionCalledWithDocsCount, 10);
}
```

Sadly I don't think there's a way to assert on the batches thing, so we'll have to set a breakpoint

**Comment by AbdelrahmanHafez** [comment]
Here's the script I used to test this out:

```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');
const sinon = require('sinon');

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  const users = Array.from({ length: 1000 }).map((v, i) => ({ name: i }));

  await User.init()

  const insertManySpy =  sinon.spy(User.collection,'insertMany');

  await User.insertMany(users,{limit:10});

  const collectionCalledWithDocsCount = insertManySpy.firstCall.args[0].length;

  assert.equal(collectionCalledWithDocsCount, 10);
}
```

**Comment by tusharf5** [comment]
I did some exploration on this. The mongo shell `insertMany` has no such `limit` option and it [expects](https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/#execution-of-operations) to only receive documents that do not exceed the **100,000** mark and if it does exceed that limit it divides it into groups of smaller sizes.

The Official Node.js Driver also doesn't use have a limit option for `insertMany` or the underlying `bulkWrite` method that it uses for `insertMany`. 

So I guess the `limit` option could be used here for the async's parallelLimit method to limit the number of concurrent documents being processes by mongoose at a given point of time.

https://github.com/andresattler/mongoose/blob/729ad628b1df13b8963ed0f596616ec44cffdf81/lib/model.js#L2059-L2061

```js
// instead of this
parallelLimit(toExecute, 1000, function(error, docs) {

// something like this with of course more validation
parallelLimit(toExecute, options.limit || 1000 , function(error, docs) {
```

> Is this just limiting the number of documents processed (validated,/casted) on the mongoose side?

Yes, It only limits the number of concurrent documents being processed by mongoose. As soon as it processes all of the documents, it calls the callback with an array of all those documents. In the end it still sends one big insert with all the documents.

One caveat with parallelLimit is that if the `toExecute` operations are synchronous then the `limit` provided as the second argument has no effect on its execution. It processes them all at once. The only benefit of using it is when if doing an async task and I don't know if this callback is async or not.

https://github.com/andresattler/mongoose/blob/729ad628b1df13b8963ed0f596616ec44cffdf81/lib/model.js#L2043-L2057

```js
 doc = new _this(doc);
      doc.validate({ __noPromise: true }, function(error) {
        if (error) {
          // Option `ordered` signals that insert should be continued after reaching
          // a failing insert. Therefore we delegate "null", meaning the validation
          // failed. It's up to the next function to filter out all failed models
          if (options != null && typeof options === 'object' && options['ordered'] === false) {
            return callback(null, null);
          }
          return callback(error);
        }
        callback(null, doc);
      });
    });
```

> I assumed it would create batches with size of limit to avoid slow trains, but doing some debugging, it seems to be sending one big insert with all the documents.

That would be very cool. But I guess it would be a tricky feature to implement.

**Comment by AbdelrahmanHafez** [comment]
So, from an end-user point of view, they should use it only to limit the number of documents being validated/cast concurrently

Most likely useful only when inserting a large number of documents. Does this sound about right?

**Comment by tusharf5** [comment]
Yes, although I don't think it's currently using the `limit` option to control that as it's set to a static value of `1000`.

**Comment by AbdelrahmanHafez** [comment]
I believe that it actually works. If you're referring to the 1000 in `const limit = get(options, 'limit', 1000);` That's a default, in case the user doesn't set a limit option.

**Comment by tusharf5** [comment]
I am referring to this line where it is directly set to `1000`.

https://github.com/andresattler/mongoose/blob/729ad628b1df13b8963ed0f596616ec44cffdf81/lib/model.js#L2060

```js
  parallelLimit(toExecute, 1000, function(error, docs) {
```

I could not find `const limit = get(options, 'limit', 1000);` in the insertMany method. Am I missing something ?

**Comment by AbdelrahmanHafez** [comment]
You're probably browsing an older version of the file (Aug, 2017).
Here's [the line](https://github.com/Automattic/mongoose/blob/798a77402596143cb89bf16e7e5bbd42c1439efe/lib/model.js#L3298) I am referring to in the latest commit.

**Comment by tusharf5** [comment]
Ha! my bad 😀Yes, you are right. It is using that option.
