### ISSUE TITLE
mongoose showing error

### ISSUE THREAD

**Issue by ismartushi789** [Automattic/mongoose#8870]
mongoose.connect(uri, { useNewUrlParser: true });
do we still have to use the given below line of code to make it work
mongoose.connect("mongodb://localhost/cat_app");

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome @ismartushi789 

Please provide more details, what does the error look like?

If you try this:
```js
  mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
```
Does it work correctly?
