### ISSUE TITLE
DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.

### ISSUE THREAD

**Issue by piavgh** [Automattic/mongoose#8871]
**Do you want to request a *feature* or report a *bug*?**
This is just a question. I got this error when I run my application or when CI runs the tests.

I checked this guide [https://mongoosejs.com/docs/deprecations.html](https://mongoosejs.com/docs/deprecations.html), but there is no instruction on this warning

I also checked the API documentation: https://mongoosejs.com/docs/api/model.html#model_Model-save

The `.save()` function is still there

So should I get rid of this `.save()` function in my code? I have a requirement from the PM to do so, but I'm not sure that I should do this.

**What is the current behavior?**
This warning message is shown 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
This warning message should not be shown

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v10.20.1
MongoDB: v3.2 (Docker)
Mongoose: v5.7.12

**Comment by AbdelrahmanHafez** [comment]
This deprecation warning is coming from the native driver, not from mongoose. Also, it's referring to db.**collection**.save(...) which is the native driver's methods, not Model.prototype.save(...);, which is provided by mongoose.

Notice the deprecation notice in the [MongoDB docs for db.collection.save()](https://docs.mongodb.com/manual/reference/method/db.collection.save/#db.collection.save).

**Comment by AbdelrahmanHafez** [comment]
Welcome @piavgh

This deprecation warning is coming from the native driver, not from mongoose. Also, it's referring to db.**collection**.save(...) which is the native driver's method, not Model.prototype.save(...);, which is provided by mongoose.

Notice the deprecation note in the [MongoDB docs for db.collection.save()](https://docs.mongodb.com/manual/reference/method/db.collection.save/#db.collection.save).

**Comment by piavgh** [comment]
> Welcome @piavgh
> 
> This deprecation warning is coming from the native driver, not from mongoose. Also, it's referring to db.**collection**.save(...) which is the native driver's method, not Model.prototype.save(...);, which is provided by mongoose.
> 
> Notice the deprecation note in the [MongoDB docs for db.collection.save()](https://docs.mongodb.com/manual/reference/method/db.collection.save/#db.collection.save).

Thank you. Turns out, it is from `gridfs-stream` library
