### ISSUE TITLE
Typescript: compiler throws a type error when passing a key from a custom base type as a condition to a generic model

### ISSUE THREAD

**Issue by afenrir** [Automattic/mongoose#8872]
**Do you want to request a *feature* or report a *bug*?**

Maybe a bug, maybe operator error.

**What is the current behavior?**

I wish to pass a generic model into a function as an argument. The generic model extends Document and a custom base type. However, attempts to operate on that model using conditions defined in the custom base type throws type errors at compile time. 

**If the current behavior is a bug, please provide the steps to reproduce.**

I have included here a code snippet and also a link to the TS playground where you can see the compiler error.

```typescript
import mongoose, { Document, Model, Schema } from 'mongoose';

interface User {
    name: string;
    age: number;
    favouriteAnimal: string;
}

const UserSchema = new Schema({
    name: String,
    age: Number,
    favouriteAnimal: String,
});

const UserModel = mongoose.model<User & Document>('User', UserSchema);

// This is an example of a successful `.findOne` call. The compiler has no issues with this. This is
// how I would have expected the generic function below to work.
function doSomething() {
    return UserModel.findOne({ user: 'john' }); 
}

// This is an example of a generic function where the compiler will throw a type error. I would expect
// to be able to pass `{ user: john }` as a condition to `.findOne`, because `T` extends `User`.
async function doSomethingGeneric<T extends User & Document>(model: Model<T>, key: keyof T) {
    const user = await model.findOne({ user: 'john' }); // Compiler errors on this line.
    return user![key];
}
```
This is the compiler error:
```
error TS2345: Argument of type '{ user: string; }' is not assignable to parameter of type 'MongooseFilterQuery<Pick<T, Exclude<keyof T, "toString" | "removeListener" | "off" | "update" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | "$session" | ... 47 more ... | "modelName">>>'.

Type '{ user: string; }' is not assignable to type '{ [P in keyof Pick<T, Exclude<keyof T, "toString" | "removeListener" | "off" | "update" | "invalidate" | "increment" | "model" | "$isDeleted" | "remove" | "save" | "__v" | "$isDefault" | "$session" | ... 47 more ... | "modelName">>]?: (P extends "_id" ? [...] extends [...] ? Condition<...> : Condition<...> : [...] e...'.

23    const user = await model.findOne({ user: 'john' });
```

Here is an interactive snippet on the TS playground where you can see the compiler error.

[Playground Link](https://www.typescriptlang.org/v2/en/play?#code/JYWwDg9gTgLgBCCA7A5hCBnApgGjgbzgBEIBjAVxCyRjwFkIATLAGzwGVSALLEAQzgBfOADMoEEHADkiVOmxSA3AChlwGligi+pLHACq2KAWVwzcJHyoAuOBhhR1KFebh8UWW0koAjTS-NtADcIckcYLABBJFA+Flt7R1QVQVVSZHsDI04efjgAXgssAHc4HN4+AAp8U3NLGzKHJxxas3dPOAA5X00W12DQ8KiY-njGpJQWwQBKFWV0pEzDTQZmFgKEZDRMLAA6RDWAHmXjADJiMkpqGAA+SqkTqTwT8v5Z1QB6D7gAFS5gDBwAFuJBwLAADysYBYeggIjcdnIpF0GAwInI6wABrsROpGAB5JBYTFwUhxFi7X48UkSMDAGHGLh8QFICBA1HkLCA4rAGBcOB8gGUv7AgHKL5wLgQUoASTgxVCLEYkr4QT0ELAWFIEWVfL0HiJjlIonISG1wGQcD8LGlArZCqgAGtdsp0WaYBbQYwIOwJFhBahKtMTK4oP6wqCTqtWDi8YSsNU4OQjLYpAArCBcJBSISzODKVLi74iwHAvigiFQmFwOEIg2aYDGt3my3FHhhgXU9LgemaeX09Z88SlAQwACemrBUHEUEpcoVGOVGq1MCLdqtej4PmrMDZYGZgMxhGTmlsGazQhJzIRC0YvM96+xuKQBKJmLwfjJJ7gmJ+JIhEQvoeJzYsozJjmaJrug+3q+lQAYoAA4tQDakIcPxguCgGMICJxwOcJAUFQNB3AcrC2NGLDoTceCOlgY62HRY61j8wY1K4CyZCexiFHwxR8LymxrLGL7xom3Gpue2a5oo+ahuGUCgtxACEADaTEALopEAA)

**What is the expected behavior?**

The expected behaviour is for the compiler to recognise `{ user: "John" }` as a valid condition.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.4.0
Typescript: v3.8.8
Mongoose: v5.9.10
Mongo: v4.2.3

**Comment by vkarpov15** [comment]
I took a closer look at this to learn a bit more about TypeScript, but I'm afraid I haven't been able to figure out how to work around this warning. I'd say your best bet would be to open an issue on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose), because those are the TypeScript bindings the TS playgound site is using.

Only workaround I can come up with is to just not use generics:

```
import mongoose, { Document, Model, Schema } from 'mongoose';

interface User {
    name: string;
    age: number;
    favouriteAnimal: string;
}

const UserSchema = new Schema({
    name: String,
    age: Number,
    favouriteAnimal: String,
});

const UserModel = mongoose.model<User & Document>('User', UserSchema);
const UserModel2 = mongoose.model<User & Document>('User2', UserSchema);

doSomething(UserModel2);

function doSomething(model: Model<User & Document>) {
    return model.findOne({ user: 'john' }); 
}
```
