### ISSUE TITLE
isModified() doesn't check the field against undefined

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#8874]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
`isModified()` returns **true** while the field is **undefined**.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
user.password = {
  // there is a 'password' field in the schema here as well, but not set here.
  resetExpires: tomorrow,
  resetToken = token
}
```

```js
schema.pre('save', function save(next) {
  // I have to check against undefined manually here.
  // && this.password !== undefined
  if (this.isModified('password')) {
    this.resetToken = null;
    this.resetExpires = null;
  }

  return next();
});
```

**What is the expected behavior?**
`isModified()` should understand the field is really changed or not. It should return true if and only if the field has changed.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`MongoDB: 4.2.5`
`Mongoose: 5.9.10`
`Node.js: 12.10.0`

**Comment by AbdelrahmanHafez** [comment]
Welcome @meness 

The test below passes, could you modify it to demonstrate the issue you're facing?
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ name: { type: String } });

  const User = mongoose.model('User', userSchema);
  const user = await User.create({ name: 'Hafez' });

  user.name = undefined;
  assert.ok(user.isModified('name'));
}
```

**Comment by meness** [comment]
Thanks for your quick reply @AbdelrahmanHafez.

As you see in my example codes above, I used an object, but you tested a single field with a type of `String`. Please test an object as I demonstrated below.

```js
// User Schema
{
  name: String,
  password: {
    password: String,
    resetToken: String,
    resetExpires: Date
}
```

**Note** that in my case, the password object schema is a sub-document used in the user schema, so I used `isModified()` inside of the password schema itself, not the user schema.

**Comment by AbdelrahmanHafez** [comment]
Running with a nested object passes the test as well.
Please modify the script below, and provide the full modified script where the test fails.
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ nested: { password: String } });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({ nested: { password: '123' } });
  assert.ok(!user.isModified('nested.password'));


  user.nested.password = undefined;
  assert.ok(user.isModified('nested.password'));

  console.log('Done.');
}
```

**Comment by meness** [comment]
Thanks for your time @AbdelrahmanHafez. Hope it helps you to fix the issue.

```js
const mongoose = require('mongoose');

const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: String,
    nested: { password: String, resetToken: String },
  });

  const User = mongoose.model('User', userSchema);

  const user = new User();
  user.init({ name: 'Ali' });

  // Magic happens here
  // I don't set the password field, but the other one.
  user.nested = {
    resetToken: 'token',
  };

  // The above codes cause nested.password to have a modified flag.
  // user.set('nested.resetToken', 'token'); // Using set() instead of the above codes works as expected.
  assert.equal(user.isModified('nested.resetToken'), true); // Passed
  assert.equal(user.get('nested.resetToken'), 'token'); // Passed

  assert.equal(user.isModified('nested.password'), false); // Error
}
```

**Comment by vkarpov15** [comment]
I looked into this more closely and this comes down to a conflict between how Mongoose thinks of modified versus how the end user thinks of modified. For Mongoose, a path being modified means Mongoose will set (or unset, in this case) that path when saving the document. By explicitly setting `user.nested = { resetToken: 'token' }`, you're also telling Mongoose to wipe out any existing value for `nested.password`.

I think the right way to work around this is to use `user.nested.resetToken = 'token'` instead.
