### ISSUE TITLE
Should we disallow discriminator names to have special characters in them?

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8879]
Currently we can add a discriminator with name `Product.Something` which can cause some bugs in the future. I think we should either throw errors when someone tries to create a discriminator with a special character in the discriminator/model name.

If we're not going to remove it, we have to at least explicitly support it by adding some tests.
Thoughts? @vkarpov15 @lineus

**Comment by vkarpov15** [comment]
What bugs does this pattern cause? I can't think of any off the top of my head. Frankly, this pattern is a good one because discriminator names can't conflict with model names :)

**Comment by AbdelrahmanHafez** [comment]
I think it might cause issues when trying to access values via `get(...)` but admittedly, the upsides of using such a pattern outweigh the possibility of such bug happening, and should just be fixed _if_ it occurs.
