### ISSUE TITLE
add `$locals` to schema.reserved

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8887]
Looking at https://github.com/Automattic/mongoose/issues/7375, 7457, and #7583
I noticed that `$locals` is a popular feature, but users can still set it on the schema which would conflict if they try to access it as a path.

```js
const userSchema = new Schema({
  $locals: String
});

const User = mongoose.model('User', userSchema);

const user = new User({});

// TypeError: Cannot set property 'a' of undefined
user.$locals.a = 'hello';
```

Perhaps something to consider for v6.0.
@vkarpov15 thoughts?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I'd say this isn't necessary because you can't save top-level keys that start with `$` in MongoDB.

**Comment by AbdelrahmanHafez** [comment]
Oh, I didn't know that! Thank you.
