### ISSUE TITLE
two level nested document does not get timestamps

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [Automattic/mongoose#8894]
**Do you want to request a *feature* or report a *bug*?**
Question/Bug

**What is the current behavior?**
One level nested document gets timestamps, but 2 level nested document does not get timestamps

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Expecting timestamps in **journal** entry

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.9.9
Node.js: 12.5.0
MongoDB: 4.0.2

**Additional info:**

// schema & model
```
const JournalSchema = new mongoose.Schema({
  message: {type: String},
}, {timestamps: true})

const ProductSchema = new mongoose.Schema({
  name: {type: String},
  journal: [JournalSchema]
}, {timestamps: true})

var LotSchema = new mongoose.Schema({
  products: [ProductSchema],
}, {timestamps: true})

const LotsModel = mongoose.model('Lots', LotSchema)
```

// wrapper function to add product
```
  function addProductIntLot (lotId, product) {
    const conditions = { _id: lotId }
    const update = { $push: { products: product } }
    const options = { new: true, runValidators: true, fields: { products: { $slice: -1 } } }

    return LotsModel.model.findOneAndUpdate(conditions, update, options)
  }
```

// adding product in existing lot
```
const lotId = '...'
const product = {
  name: 'mock-name',
  journal: [{message: 'Product has been created.'}]
}
addProductIntLot(lotId, product)
  .then(console.log)
  .catch(console.error)
```

The product gets createdAt and updatedAt properties.
However, journal entry never gets createdAt & updatedAt fields.

**Comment by anton-erofeev** [comment]
Its looks like you need to to upgrade mongoose from 5.9.9 to the latest version. This bug has been fixed in https://github.com/Automattic/mongoose/pull/8799

**Comment by AlbertHambardzumyan** [comment]
@anton-erofeev 
Unfortunately, still timestamps is missing with mongoose 5.9.11
