### ISSUE TITLE
Cannot populate refPath inside of a subschema

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#8898]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
It doesn't populate `refPath` inside of a subschema.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
// Child Schema
refId: {
  type: ObjectId,
  required: true,
  refPath: 'morph',
},
morph: {
  type: String,
  required: true,
  enum: ['ModelA', 'ModelB', 'ModelC'],
}

// Parent Schema
content: { type: ChildSchema, required: true },

// Populate
this.find({ })
  .populate('content.refId')
  .exec();
```

**Note** that I double-checked the ObjectIDs exist and also populating a flat field (not subschema) works.

**Note** that I tried with different field names!

**What is the expected behavior?**
It should populate `content.refId`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`MongoDB: 4.2.5`
`Mongoose: 5.9.10`
`Node.js: 12.10.0`

**Comment by AbdelrahmanHafez** [comment]
Change `refPath: 'morph'` to `refPath: 'content.morph'`.

Proof:
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();


  const commentSchema = new Schema({
    content: {
      documentId: {
        type: Schema.ObjectId,
        required: true,
        refPath: 'content.modelName'
      },
      modelName: {
        type: String,
        required: true,
        enum: ['Post']
      }
    }
  });

  const Comment = mongoose.model('Comment', commentSchema);

  const Post = mongoose.model('Post', { title: String });


  const post = await Post.create({ title: 'JS 2020' });

  await Comment.create({ content: { documentId: post._id, modelName: 'Post' } });


  const comment = await Comment.findOne()
    .populate('content.documentId');

  assert.equal(comment.content.documentId.title, 'JS 2020');
  console.log('All assertions passed.');
}
```

Please reopen the issue if you need any further assistance.

**Comment by meness** [comment]
@AbdelrahmanHafez Thanks for your help. It may help, I haven't tried yet, but it causes a possible future bug when we separate the subschema into another file because we need to take care of renaming over there too.

It's good to be done by Mongoose natively.

**Comment by AbdelrahmanHafez** [comment]
We need it to work on absolute paths instead of relative paths because `refPath` doesn't have to be in the same object with `documentId`.
