### ISSUE TITLE
Mongoose is incapable of querying date range

### ISSUE THREAD

**Issue by dibyajyotiron** [Automattic/mongoose#8903]
**BUG**

**What is the current behavior?**
Mongoose is not able to find documents between dates. Example is below.
When I query using mongoDB shell, using a query like this: 
```
db.<model>.find({createdAt: {$gte: new Date("2020-02-16T21:00:00Z"), $lte: new Date("2020-02-17T20:00:59Z")}})
```
it returns the expected data. 
But when I query in mongoose, it doesn't return anything, a very weird behavior.

My date query: 
```
await <MODEL>.find({
            someparam: { $in: params.map(m => m._id) }, -> `not am issue, works correctly`
            createdAt: {
                $gte: new Date(start),
                $lte: new Date(end),
            },
            status: { $in: ["some array"]},
        }).lean();
```
start/end format is `2020-02-16T20:00:59Z`
**What is the expected behavior?**
- Expected behavior is it should return me all the documents that fall in that date range. Tried everything from the docs, nothing seems to work.

**What are the versions of Node.js, Mongoose and MongoDB you are using?**
Mongo: 4.2.6
Mongoose: 5.9.1
Node.Js: 12.16.0

**Note that this is not the createdAt field I get using timestamps flag, it's a custom field, that actually has a value like: ``` { ..., createdAt: Date, ...} ```
The way it shows up in console is ```ISODate("2019-11-27T16:36:01Z")``` which is also expected.
Production application is stuck because of this!

**Comment by dibyajyotiron** [comment]
If I do 
```
await <MODEL>.find({
            someparam: { $in: params.map(m => m._id) }, -> `not am issue, works correctly`
            createdAt: {
                $gte: (start),
                $lte: (end),
            },
            status: { $in: ["some array"]},
        }).lean();
```
This also doesn't return any data.

**Comment by AbdelrahmanHafez** [comment]
Hello @dibyajyotiron

Mongoose is able to filter by a range of dates. It could be an issue with casting, or perhaps the field's type on the schema is different from the one on your database. Are there other apps that write to that database? Have you used a different type for that field before?

Tinker around with the script below, and see if you can make reproduce the issue.
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    bornAt: { type: Date }
  });

  const User = mongoose.model('User', userSchema);

  await User.create({ bornAt: new Date('1994-12-04') });

  const users = await User.find({ bornAt: { $gte: new Date('1994-01-01T00:00:00Z'), $lte: new Date('1995-01-01T00:00:00Z') } });

  assert.equal(users.length, 1);

  console.log('Assertions passed.');
}
```
