### ISSUE TITLE
DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated.

### ISSUE THREAD

**Issue by Akarami000** [Automattic/mongoose#8909]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by lineus** [comment]
Please search for open or previously closed issues that are relevant to your situation before opening a new one. There are many regarding deprecation warnings. Please see https://mongoosejs.com/docs/deprecations.html
