### ISSUE TITLE
(node:6308) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017     at new MongooseServerSelectionError (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\error\serverSelection.js:22:11)    

### ISSUE THREAD

**Issue by sumit409** [Automattic/mongoose#8912]
//This is my code.
const mongoose = require('mongoose')

mongoose.connect('mongodb://127.0.0.1:27017/task-manager-api',{
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useCreateIndex: true
})

const Task = mongoose.model('Task',{
    description:{
        type: String,
        required: true,
        trim:true
    },
    completed:{
        type: Boolean,
        default: false
    }
})

**Comment by imronpuji** [comment]
ahh same with me

**Comment by sumit409** [comment]
How can I fix it?

**Comment by lineus** [comment]
Do you have `mongod` running on the default port of 27017?

Can you connect to it with the `mongo` shell?
