### ISSUE TITLE
Mongoose populate limit doesn't return the expected limited items

### ISSUE THREAD

**Issue by tonywangcn** [Automattic/mongoose#8917]
**Do you want to request a *feature* or report a *bug*?**

I think it's a BUG

**What is the current behavior?**

CASE 1: set limit 5

The limit items returns less limit number or even none.

CASE 2: no limit

all the items ( ItemA ) referenced by ItemB are returned, more than 5

**If the current behavior is a bug, please provide the steps to reproduce.**

```
//model
var ItemASchema = new Schema({
    a: { type: String, required: true },
    updatedAt: { type: Date, default: Date.now },
}, { timestamps: true });

var ItemA = mongoose.model('ItemA', ItemASchema);
var ItemBSchema = new Schema({
    b: { type: String, required: true },
    items: [{
        type: String,
        ref: ItemA
    }],
    updatedAt: { type: Date, default: Date.now },
}, { timestamps: true})
var ItemB = mongoose.model('ItemB', ItemBSchema);

// controller

const qs = await ItemB.find({ }).populate({
            path: 'ItemA',
            options: {
                limit: 5,
                sort: { updatedAt: -1 },
            }
        })
```
actual response
```
{
    "status": 200,
    "data": [
        {
            "a": "84nVxE8s7",
            "item": [],
            "updatedAt": "2020-05-02T12:01:07.293Z"
        },
        {
            "a": "BIS4CGBrx",
            "items": [
                {
                    "b": "asdfwer",
                    "updatedAt": "2020-05-01T16:00:00.000Z"
                },
                {
                    "b": "asdf",
                    "updatedAt": "2020-05-01T16:00:00.000Z"
                }
            ],
            "updatedAt": "2020-05-02T12:04:04.107Z"
        },
        {
            "shortid": "HvS0Qe4dT",
            "items": [
                {
                    "b": "asdfsadfwer",
                    "updatedAt": "2020-05-01T10:03:00.000Z"
                },
                {
                    "b": "asdr",
                    "updatedAt": "2020-05-01T06:50:00.000Z"
                }
            ],
                    "b": "asdfsadfwer",
                    "lastBuildDate": "2020-05-02T12:01:24.064Z"
        },
        {
            "a": "UDp2g0Cpb",
            "items": [
                {
                    "b": "jkldgfdsg",
                    "updatedAt": "2020-05-01T16:00:00.000Z"
                }
            ],
            "updatedAt": "2020-05-02T12:01:25.560Z"
        },
        {
            "a": "V5kz0i50b",
            "items": [],
            "updatedAt": "2020-05-02T12:01:27.483Z"
        }
    ]
}

```

**What is the expected behavior?**

For every ItemB, it has more than 5 related ItemA. So with limit 5, it should return at least 5 ItemB in the field items. But some of them are less than 5 and some of are even empty.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v12.13.1
Mongoose 5.9.11

**Comment by AbdelrahmanHafez** [comment]
In that case, you want to use `perDocumentLimit` instead of `limit`. https://mongoosejs.com/docs/api/model.html#model_Model.populate

Valeri Karpov wrote a [blog post](https://thecodebarbarian.com/whats-new-in-mongoose-59-schematype-default-options-and-per-document-populate.html#new-populate-option-perdocumentlimit) explaining why.

**Comment by tonywangcn** [comment]
@AbdelrahmanHafez God, You save my day in just FIVE minutes ! I think this should be highlighted in the Doc. Thanks !!!

**Comment by AbdelrahmanHafez** [comment]
Happy to help!
It's already mentioned in [this section](https://mongoosejs.com/docs/populate.html#query-conditions) in the docs.
