### ISSUE TITLE
Mongoose populate with search param has empty score value

### ISSUE THREAD

**Issue by zRelux** [Automattic/mongoose#8920]
I'm trying to populate a field in a user document based on the search parameter given. 
```javascript
const Schema: Schema = new Schema(
  {
     name: {
      type: String,
      trim: true
    },
    description: {
      type: String,
      trim: true
    },
  }
);

Schema.index({ name: 'text', description: 'text' });
```

This schema is used as ref in a user schema. In my search being that I have an instance of the user model I try to populate these ref using the search and textScore but it seems that every item returns a score of 0 independent of the search query. hence the sort also is not working properly

```javascript
  const { schemaRefed } = await user
    .populate({
      path: 'schema',
      options: {
        match: { $text: { $search: search } },
        score: { $meta: 'textScore' },
        projection: { score: { $meta: 'textScore' } }, // I Read on SO that this is needed for refs but still not working
        sort: { score: { $meta: 'textScore' } },
        limit
      }
    })
    .execPopulate();
 ```

**Comment by AbdelrahmanHafez** [comment]
Instead of `projection: { ... }` use `select: { ... }`
If that doesn't work, please try to modify the script below to reproduce the issue.

```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({ name: { type: String } });
  userSchema.index({ name: 'text' });

  const User = mongoose.model('User', userSchema);

  const postSchema = new Schema({
    title: String,
    userId: { type: Schema.ObjectId, ref: 'User' }
  });

  const Post = mongoose.model('Post', postSchema);

  await User.init();

  const user = await User.create({ name: 'Hafez' });
  const post = await Post.create({ title: 'JS 2020', userId: user._id });


  await post.populate({
    path: 'userId',
    match: { $text: { $search: 'Hafez' } },
    score: { $meta: 'textScore' },
    select: { score: { $meta: 'textScore' } }
  }).execPopulate();

  const rawPost = post.toObject();

  assert.ok(rawPost.userId.score);
}
```

**Comment by zRelux** [comment]
Thank you for the script I was able to figure out the problem.
I had to lift `match: { $text: { $search: search } },` out of the option object.

Now secondary question I notice that this is only full text search, is there a quick way to also have partial search without integrating elasticsearch?

**Comment by AbdelrahmanHafez** [comment]
>Thank you for the script I was able to figure out the problem.

Happy to help.
>Now secondary question I notice that this is only full text search, is there a quick way to also have partial search without integrating elasticsearch?


That's not related to mongoose, but in my experience, MongoDB isn't the most powerful option when it comes to text search, I used Algolia, it's much easier to work with, and with great developer experience, and user experience, but comes with a hefty price tag. ElasticSearch can be powerful, and wallet-friendly, but a bit difficult to set up.

That's my personal opinion, though. Other people could have different experiences.
