### ISSUE TITLE
How to retrieve chat_id from the db

### ISSUE THREAD

**Issue by paulbraam** [Automattic/mongoose#8921]
Hi,

I'm working on a telegram bot based on `Telegraf`. I'm using `cron` to fire off the event.
I'm trying to retrieve `chat_id` from the database, but unfortunately without success.

Here is how my schema looks like.

```
const mongoose = require('mongoose')
const userSchema = mongoose.Schema({
  chat_id: {
    type: Number,
    index: true,
    unique: true,
    required: true
  },
}, {
  timestamps: true
})
module.exports = userSchema
```

Here is the event I'm trying to get to work.

```
const CronJob = require('cron').CronJob;

const job = new CronJob('*/5 * * * * *', async function() {
    const user = await db.User.findOne({chat_id: ctx.chat.id});
    await bot.telegram.sendMessage(user.chat_id, 'Hello World');
})

bot.command('launch', async (ctx) => {
  job.start()
})
```

The issue is if I use just `db.User.findOne()`, I'm able to get the `chat_id` of the first entry in the database.
I can get the right `chat_id` if I make it within the event that refers to `ctx`.
For example:

```
bot.command('launch', async (ctx) => {
  const user = await db.User.findOne({chat_id: ctx.chat.id});
  console.log(user.chat_id)
})
```

Please help me with the solution. I'm struggling with this issue for days.

**Comment by andreialecu** [comment]
Your problem isn't related to mongoose but to your usage of the `cron` package.

Your job function isn't passed the `ctx` parameter you're expecting and it ends up undefined. I suggest you post this on StackOverflow or look for resources on how to pass parameters to `node-cron` jobs.

**Comment by paulbraam** [comment]
@andreialecu, thanks for the answer.

**Comment by AbdelrahmanHafez** [comment]
I'll close the issue, reopen if you need any further assistance with the issue.
