### ISSUE TITLE
Use something other than dox to parse documentation

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8925]
Re: #8857, dox is long out of date and has a few upstream security vulnerabilities. Shouldn't impact users since dox is a dev dependency, but it causes confusion and reflects badly on us.

**Comment by hasezoey** [comment]
once https://github.com/tj/dox/pull/196 lands, would this issue still be needed?

the only "active" alternative i see is to use "typedoc", but for that to properly function, some typescript errors would have to be resolved

**Comment by Twipped** [comment]
https://github.com/tj/dox/releases/tag/v1.0.0

**Comment by vkarpov15** [comment]
I'll close this one for now, given #12024. Thanks @hasezoey !
