### ISSUE TITLE
Saving modified subdocuments in multidimensional arrays throws an error

### ISSUE THREAD

**Issue by beaulac** [Automattic/mongoose#8926]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unable to save modified subdocuments if they are in a multidimensional array. Saving such a document throws an error.

The 'modified path' is missing one of the indices in the subdocument's path, and so saving throws an error because it is trying to set a property on an array which is unsupported in Mongo.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const SubchildSchema = new mongoose.Schema({ title: String });

const ChildSchema = new mongoose.Schema({
	subchilds: [[SubchildSchema]],
});

const ParentModel = mongoose.model(
	'Parent',
	{ children: [ChildSchema] },
);

async function repro() {
	await mongoose.connect('mongodb://localhost:27017/test123');

	const { _id } = await ParentModel.create({
		children: [
			{
				subchilds: [
					[{}],
				],
			},
		],
	});

	const parent = await ParentModel.findById(_id);
	parent.children[0].subchilds[0][0].title = 'foo';
	return parent.save();
}

repro()
	.catch(console.error)
	.finally(mongoose.disconnect);

```

`MongoError: Cannot create field 'title' in element {0: [ { _id: ObjectId('5eaf31d48ba42b1eddc904b8') } ]}`

Seems the path calculated in `_markModified` in `core_array.js` is missing the index of the nested array. The path is 
`'parent.children.0.subchilds.0.title'` but should be `'parent.children.0.subchilds.0.0.title'`.

**What is the expected behavior?**

Able to save this subdocument update.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.16.3
Mongoose: 5.9.11

**Comment by AbdelrahmanHafez** [comment]
https://mongoosejs.com/docs/faq.html#array-changes-not-saved

**Comment by beaulac** [comment]
Sorry, I should have been clearer with the title; the issue isn't that the changes are not saved, but rather that it throws an error because it is trying to save an invalid path.

**Comment by AbdelrahmanHafez** [comment]
Oh, okay. I can confirm that this is a bug.

I played with the script you provided a little bit, and can confirm that the issue is we're sending the wrong index in the `update` operation.

```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const bookSchema = new Schema({ title: String });

  const aisleSchema = new Schema({
    shelves: [[bookSchema]]
  });

  const librarySchema = new Schema({ aisles: [aisleSchema] });

  const Library = mongoose.model('Library', librarySchema);

  await Library.create({
    aisles: [{ shelves: [[{ title: 'Clean Code' }]] }]
  });

  const library = await Library.findOne();
  library.aisles[0].shelves[0][0].title = 'Refactoring';

  await library.save();

  const foundLibrary = await Library.findOne();

  assert.equal(foundLibrary.aisles[0].shelves[0][0].title, 'Refactoring');
  console.log('All assertions passed.');
}
```

Current output:
```
{ '$set': { 'aisles.0.shelves.0.title': [ 'Refactoring' ] } }
```

Expected output:
```
{ '$set': { 'aisles.0.shelves.0.0.title': [ 'Refactoring' ] } }
```
