### ISSUE TITLE
$geoNear is only valid as the first stage in a pipeline.

### ISSUE THREAD

**Issue by khaled9544** [Automattic/mongoose#8928]
I'm getting the following error `$geoNear is only valid as the first stage in a pipeline.` while I'm doing an aggregation using nodejs as server-side.

Aggregation Object:

```
[ { '$geoNear':
     { near: [Object], distanceField: 'distance', spherical: true } },
  { '$lookup':
     { from: 'reviews',
       localField: '_id',
       foreignField: 'restaurant',
       as: 'reviews' } },
  { '$project':
     { logo: '$$ROOT.logo',
       name: '$$ROOT.name',
       cuisine: '$$ROOT.cuisine',
       rate: [Object],
       reservation: '$$ROOT.reservation',
       closeAt: '$$ROOT.closeAt',
       openAt: '$$ROOT.openAt',
       recommendationsLength: [Object],
       isLive: '$$ROOT.isLive',
       avgCost: '$$ROOT.avgCost',
       creationDate: '$$ROOT.creationDate',
       distance: '$$ROOT.distance' } },
  { '$sort': { distance: 1 } } ]
```
Versions:
Mongoose: ^5.9.11
Node: v10.16.3

any idea why I'm getting the error above? it is very weird

**Comment by AbdelrahmanHafez** [comment]
Well, the error is saying that you should use `$geoNear` as the first stage in the pipeline.

Is the model you're using `aggregate` on a discriminator? Does something (a pre-hook) modify the pipeline before it goes to mongo?

Please add `mongoose.set('debug', true);` before executing the aggregation, and share the output.

**Comment by alterEgo123** [comment]
Hey @khaled9544, did you find a solution for this? I'm facing the same issue, even if I have only ONE stage which $geoNear.

**Comment by Khaledneo** [comment]
@alterEgo123 I was applying this aggregation on a read-only document. and I concluded that the geoNear is not applicable on that type of documents

**Comment by vkarpov15** [comment]
@alterEgo123 can you please open a new issue and follow the issue template? That will help us figure out what the issue is :+1:
