### ISSUE TITLE
Mongoose Path “.” is required - problem with PostmanMocking 

### ISSUE THREAD

**Issue by DeszczMikolaj** [Automattic/mongoose#8932]
Hi, i am testing my mongoose (for MongoDB) schema, and I encountered an validation issue. After making POST verb I am getting en error:

     
    
 ```
 "message": {
            "errors": {
                "number": {
                    "message": "Path `number` is required.",
                    "name": "ValidatorError",
                    "properties": {
                        "message": "Path `number` is required.",
                        "type": "required",
                        "path": "number"
                    },
                    "kind": "required",
                    "path": "number"
                }
            },
            "_message": "eventArrayModel validation failed",
            "message": "eventArrayModel validation failed: number: Path `number` is required.",
            "name": "ValidationError"
        }
```
   

 This is my mocked json in Postman: 

  ```
    {
    	"arrayName": "displayedEvents",
    	"number": "4"
    }
```

    

And this is my mongoose schema:

  

    const mongoose = require("mongoose");
    
    const  eventSchema =  new mongoose.Schema({
        title: {
            type: String,
        //    required: true,
        },
        start: {
            type: Date,
         //   required: true,
        },
        end: {
            type: Date,
         //   required: true,
        },
        allDay: {type: Boolean, default: true},
        resource: {
            type: String,
          //  required: true,
        },
    });
    
    const eventArrayModel = mongoose.model("eventArrayModel", {
        arrayName: {
            type: String,
            required: true,
        },
       array: {type: [eventSchema]} ,
       number: {
            type: Number,
            required: true,
        }
    });
    
    module.exports = eventArrayModel;

And the get router:
```

    router.get('/',  async (req,res)=> {
    try{
        const posts = await eventArrayModel.find();
        res.json(posts);

    }catch(err){
        res.json({message: err});
    }
});
```

I can't see anything wrong about this code. It works fine without number field.

**Comment by lineus** [comment]
There isn't enough information to go on here. If you are having trouble with a POST request, it would be helpful to see the POST route that is failing.

**Comment by DeszczMikolaj** [comment]
Okey I found it, this part of code 
```
router.post('/', async(req,res)=>{
  const post = new eventArrayModel({
      arrayName: req.body.arrayName
  });
  try {
      const savedPost = await post.save();
      res.json(savedPost);
  }catch(err){
      res.json({message: err});
  }

});
```
Should looks more like this:
```

router.post('/', async(req,res)=>{
  const post = new eventArrayModel({
      arrayName: req.body.arrayName,
      array: req.body.array,
      myNumber: req.body.myNumber
  });
  try {
      const savedPost = await post.save();
      res.json(savedPost);
  }catch(err){
      res.json({message: err});
  }

});
```
