### ISSUE TITLE
Document with Date field in schema has field returned as String

### ISSUE THREAD

**Issue by JeremiGendron** [Automattic/mongoose#8939]
**Do you want to request a *feature* or report a *bug*?**
BUG (or is this expected behavior?)

**What is the current behavior?**
my schema:
```ts
const todoSchema = new Schema<TodoSchema>({
  todoId: {
    unique: true,
    type: String,
  },
  content: String,
  created: Date,
  tags: [String],
});
```
my save query: 
```ts
await new Todo({
  todoId,
  content,
  tags,
  created: new Date(),
} as TodoResource).save();
```
my find query:
```ts
const todos: TodoResource[] = await Todo.find();
```
the returned todos (green is what I got back, red the original field):
```diff
    {
     "content": "Pen spinning tricks",
-    "created": 2020-05-05T23:14:46.837Z,
+    "created": "2020-05-05T23:14:46.837Z",
      "tags": Array [
        "advanced",
        "basic",
        "intermediate",
      ],
      "todoId": "8147e256-9218-450a-a3fb-bf91dda168ba",
    },
```
**If the current behavior is a bug, please provide the steps to reproduce.**

With a schema containing a field of type `Date` (in this case `created`), after retrieving a document with the schema this `Date` field will actually hold a `String` value (even if a Date value was put in when saving).

**What is the expected behavior?**
Returned document has field of type defined in relevant schema (Date field value should be === Date field put in when saving).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 12.16.2
mongodb: 4.2
mongoose: 5.9.11

**Comment by JeremiGendron** [comment]
Test is now passing, might be an issue with jest...

**Comment by AbdelrahmanHafez** [comment]
Mongoose returns dates as date objects, not as strings. [JSON does not support date objects](https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates#json-dates-are-not-dates--they-are-strings), and converts them to strings.

proof:
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({
  joinedAt: { type: Date }
});

const User = mongoose.model('User', userSchema);
const user = new User({ joinedAt: Date.now() });

const isDate = user.joinedAt instanceof Date;
const isString = user.joinedAt instanceof String;

assert.ok(isDate);
assert.ok(!isString);

console.log('All assertions passed.');
```

**Comment by vkarpov15** [comment]
[Don't use jest](https://mongoosejs.com/docs/jest.html).
