### ISSUE TITLE
5.9.12 breaking change in model path names

### ISSUE THREAD

**Issue by bewest** [Automattic/mongoose#8940]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`5.9.12`: https://github.com/Automattic/mongoose/commit/c04a50d591c6b778295f7e7e8a578695a43c5504 this commit breaks schemas previously worked.

**If the current behavior is a bug, please provide the steps to reproduce.**

Upgrading from 5.9.9 to 5.9.12 with following:
```
var mongoose = require('mongoose');
var encrypt = require('mongoose-encrypt');

var accountSchema = new mongoose.Schema({
  account: { type: mongoose.Schema.Types.ObjectId },
  // status: { },
  db: {
    host: { type: String, default: '' },
    name: { type: String, default: '' }
  }
});
                                                                                    
```
After the patch level update, this causes process to crash.
```
 /app/node_modules/mongoose/lib/schema.js:646
    throw new Error('`' + firstPieceOfPath + '` may not be used as a schema pathname');
Error: `db` may not be used as a schema pathname
```

**What is the expected behavior?**
Minor patch level bump should not break existing code.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
npm ls mongoose mongodb
└─┬ mongoose@5.9.12 
  └── mongodb@3.5.5  deduped
$ node -v
v12.16.2

```
My solution in meantime is to pin version in package-lock.json, eager for advice.
This model is already shipped in software, and non-trivial to change the name.

**Comment by AbdelrahmanHafez** [comment]
I agree some apps could've used reserved schema keys as objects without being warned due to that bug in #8869, which is a breaking change for them.

I suggest we revert that PR, and move it to 6.0. Thoughts @vkarpov15?

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez no, I think we should use this as an opportunity to remove some reserved words. We can still leave `db` as a getter, but for internal purposes we should use a symbol like we did for `get()` in this commit: https://github.com/Automattic/mongoose/commit/de91e5ba23a504c62aa49fcc7c3bb09240dc3dc6

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I did some digging and there's no reason for `db` to be a reserved keyword. We don't use `this.db` in Mongoose anywhere, so Mongoose won't break if there's a user-defined schema path `db`.
