### ISSUE TITLE
Populate with virtual on subdocument clears out array

### ISSUE THREAD

**Issue by andreialecu** [Automattic/mongoose#8946]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Certain `populate` options seem to clear out results when used with virtuals and subdocuments.

I'm working on a graphql query parser that converts gql to mongoose populate options. I've noticed that in certain circumstances, the results get cleared out unexpectedly.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
"use strict";
const mongoose = require("mongoose");
const { Schema } = mongoose;

mongoose.set("debug", true);

run()
  .then(process.exit)
  .catch(console.error);

async function run() {
  await mongoose.connect(
    "mongodb://localhost:27017,localhost:27018,localhost:27019/test?replicaSet=rs",
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
  );

  await mongoose.connection.dropDatabase();

  const teamSchema = new Schema({
    members: [
      new Schema({
        user: { type: Schema.ObjectId, ref: "User" },
      }),
    ],
  });

  const userSchema = new Schema({
    name: { type: String },
  });
  userSchema.virtual("teams", {
    ref: "Team",
    localField: "_id",
    foreignField: "members.user",
    justOne: false,
    match: { deleted: { $ne: true } },
  });

  const User = mongoose.model("User", userSchema);

  const Team = mongoose.model("Team", teamSchema);

  const user = await User.create({ name: "User" });

  await Team.create({ members: [{ user: user._id }] });

  const results = await User.find().populate({
    path: "teams",
  });

  console.log(
    "Results1:",
    JSON.stringify(
      results.map(res => res.toJSON({ virtuals: true })),
      null,
      2,
    ),
  );

  const results2 = await User.find().populate({
    path: "teams",
    populate: {
      path: "members",
      populate: {
        path: "user",
      },
    },
  });

  console.log(
    "Results2:",
    JSON.stringify(
      results2.map(res => res.toJSON({ virtuals: true })),
      null,
      2,
    ),
  );
}
```

The output is:

```
Mongoose: users.find({}, { projection: {} })
Mongoose: teams.find({ deleted: { '$ne': true }, 'members.user': { '$in': [ ObjectId("5eb2fd5c55392e033f414a01") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {}})

Results1: [
  {
    "_id": "5eb2fc5617508d7ff8f2d654",
    "name": "User",
    "__v": 0,
    "teams": [
      {
        "_id": "5eb2fc5617508d7ff8f2d655",
        "members": [
          {
            "_id": "5eb2fc5617508d7ff8f2d656",
            "user": "5eb2fc5617508d7ff8f2d654",
            "id": "5eb2fc5617508d7ff8f2d656"
          }
        ],
        "__v": 0,
        "id": "5eb2fc5617508d7ff8f2d655"
      }
    ],
    "id": "5eb2fc5617508d7ff8f2d654"
  }
]

Mongoose: users.find({}, { projection: {} })
Mongoose: teams.find({ deleted: { '$ne': true }, 'members.user': { '$in': [ ObjectId("5eb2fd5c55392e033f414a01") ] }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {}})
Mongoose: users.find({ _id: { '$in': [ ObjectId("5eb2fd5c55392e033f414a01") ] } }, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {}})

// notice how teams is an empty array

Results2: [
  {
    "_id": "5eb2fc5617508d7ff8f2d654",
    "name": "User",
    "__v": 0,
    "teams": [],
    "id": "5eb2fc5617508d7ff8f2d654"
  }
]
```

**What is the expected behavior?**

The output should be the same as:

```
{
    path: "teams",
    populate: {
      path: "members.user",
    },
  }
```

Or, at a minimum, it shouldn't clear out existent results.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.9.10
node 13.7.0

**Comment by andreialecu** [comment]
Seems like the problem is related to `match` in the virtual schema. Without it everything is ok

**Comment by andreialecu** [comment]
Would be great if this worked without defining the populate `path` as `members.user`. Otherwise for my use case I need to pass the mongoose schema to my parser and have an ugly special case for subdocuments.

For context: based on these [StackOverflow answers](https://stackoverflow.com/questions/24414975/mongoose-populate-sub-sub-document), I think it's supposed to work that way too.

**Comment by andreialecu** [comment]
Also, maybe related, but running this:

```js
await User.find().populate({
    path: "a", // doesn't exist
  });
```

Results in the `members` property randomly being deleted:

```
Mongoose: users.find({}, { projection: {} })
Results2: [
  {
    "_id": "5eb310250818a8219bd28de0",
    "name": "User",
    "__v": 0,
    "id": "5eb310250818a8219bd28de0"
  }
]
```

**Comment by vkarpov15** [comment]
This is related to an issue we've been thinking about for a while: what should happen when you `populate()` a path that doesn't have a `ref`?

Right now `ref` defaults to the model being populated, so the underlying issue is that the below code:

```javascript
const results2 = await User.find().populate({
    path: "teams",
    populate: {
      path: "members",
    }
});
```

Says to populate `teams` from the `Team` model, and then populate `members` from the `Team` model. `members` is an array of objects, so no `Team` document has an `_id` that corresponds to an element of `members`, so Mongoose sets `members` to an empty array.

Maybe we should extend the behavior we're introducing for this case to all cases, so if you `populate()` a model that doesn't have a `ref`, Mongoose just ignores it? Thoughts @AbdelrahmanHafez @lineus ?

**Comment by AbdelrahmanHafez** [comment]
I think the behavior of `return accurate results when given accurate parameters, otherwise do a best effort to guess the correct parameters`  will come quite handy to users.

At most of the codebases I've worked on, we rely heavily on mongoose, and the frontend also depends on filtering/casting depending on mongoose models, so they send the filter on APIs that list documents, and mongoose does the heavy lifting of casting and removing the extra fields.

I believe this is a direction that we should be going towards.
