### ISSUE TITLE
this.$__path is not a function for stringify

### ISSUE THREAD

**Issue by WangHansen** [Automattic/mongoose#8955]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
`this.$__path is not a function`

**If the current behavior is a bug, please provide the steps to reproduce.**

see https://github.com/davidmarkclements/fast-safe-stringify/issues/43

**What is the expected behavior?**
No error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.13.1
Mongoose: 5.9.12
mongoDB: 3.6.12

**Comment by AbdelrahmanHafez** [comment]
I took a look at this yesterday, and `decirc` function modifies the document by adding a key `'[Circular]'`
It would be nice if you could provide a script that reproduces the issue without having to go into the internals of `fast-safe-stringify`.

**Comment by vkarpov15** [comment]
I'd advise against using fast-safe-stringify because, as @AbdelrahmanHafez noted, it mutates the object you pass in.

```javascript
const dangerouslyBrokenStringify = require('fast-safe-stringify');

const obj = {};
obj.obj = obj;

console.log(typeof obj.obj); // 'object'

dangerouslyBrokenStringify(obj);

console.log(typeof obj.obj); // 'string'
```

That being said, we'll work around this issue by using symbols for the offending property `scope` that fast-safe-stringify overwrites.
