### ISSUE TITLE
Remove `useNestedStrict`, always use child schema's `strict` mode

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#8961]
Re: #8922

**Comment by AbdelrahmanHafez** [comment]
Another option would be to set it as `true` by default, I've never needed to use that option, but some users might find the need to use that option.

**Comment by vkarpov15** [comment]
If you want `useNestedStrict: false`, you should be able to force `strict` mode for all child schemas using the `strict` option: `Model.updateOne(filter, update, { strict: Model.schema.options.strict })`. I should double check that you can do that when working on this.

**Comment by AbdelrahmanHafez** [comment]
That seems like a reasonable replacement.

**Comment by AdamGerthel** [comment]
Just found this thread because I discovered the hard way that strict mode wasn't being taken into account for subdocuments when using `Model.update()`. Is `useNestedStrict` being deprecated?

**Comment by AbdelrahmanHafez** [comment]
Yes, it should be in 6.0.
