### ISSUE TITLE
Date format for debug mode: new Date() vs. ISODate()

### ISSUE THREAD

**Issue by dandv** [Automattic/mongoose#8963]
**Do you want to request a *feature* or report a *bug*?**

Likely a feature.

**What is the current behavior?**

In [debug mode](https://mongoosejs.com/docs/faq.html#enable_debugging), mongoose 5.9.13 outputs queries with Date objects in the JavaScript format. This makes them cumbersome to run in the mongo shell, which expects ISODate().

> users.find({ createdAt: { '$lt': new Date("Sat, 09 May 2020 22:08:10 GMT") }, approved: true})

**What is the expected behavior?**

> users.find({ createdAt: { '$lt': ISODate("2020-05-09T22:08:10Z") }, approved: true })

Could `debug` be an option between `JavaScript` and `shell`, or something of that nature? Happy to submit a PR.

**Comment by vkarpov15** [comment]
`shell` would be a neat option, I'm open to a PR for this.

**Comment by FlameFractal** [comment]
May I pick this @vkarpov15?

**Comment by FlameFractal** [comment]
Where do the tests lie for this module?

**Comment by vkarpov15** [comment]
@FlameFractal I don't believe we have tests for this module. Feel free to add them :+1:

**Comment by vkarpov15** [comment]
Looks closed by #9532
