### ISSUE TITLE
WOW! MongoError: E11000 duplicate key error! How to display

### ISSUE THREAD

**Issue by leafyshark** [Automattic/mongoose#8967]
I am writing this to hopefully save someone lots of time because I just wasted a significant amount of time trying to figure out what was going on.

Using the [validator](https://www.npmjs.com/package/validator) library from npm, I was able to get Mongoose to return validation errors when I set them within the Schema. For example:

```
const validator = require("validator");

const userSchema = new Schema({
  email: {
    type: String,
    unique: true
    validate: [validator.isEmail, "Invalid email address."],
  },
})
```

If you enter a non-valid email address i.e. 'bob' you will get the following error:

`Error [ValidationError]: Client validation failed: email: Invalid email address.`

And if you enter an email address that already exists in the database you will get:

`E11000 duplicate key error collection: default_default.User index: email_1 dup key: { email: "bob@bob.com" }'`

I spent a few hours trying to log the actual object that contained the error message:

```
{
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: 'taylor@digitalspeed.co.uk' },
  errmsg: 'E11000 duplicate key error collection: default_default.User index: email_1 dup key: { email: "bob@bob.com" }',
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

It was seemingly impossible for several hours and I was tearing my hair out. The errors were being generated in the server log, but they seemed to be inaccessible. I thought, 'What's the point in having these errors if you can't display them to the user!?" - eventually, I figured out the issue.

My specific issue came about when batch saving documents from different collections using mongoose. I needed to Promise.all because I didn't want anything to save to the database unless it all could.

The issue was that the validation errors are promises, so using async/await in combination with Promise.all had a negative effect. For example, with the following code, it would return the error but there was not way to access it.

```
  const saveClient = await client.save();
  const saveAddress = await req.billing_address.save();
  const saveUser = await req.user.save();

  Promise.all([saveUser, saveClient, saveAddress])
    .then(() => {
   // do what you need to do
  }).catch((err) => {
  console.log(err); // this has absolutely NO effect! 
  });
```

As soon as I removed the **await** syntax, I was able to catch the error:

```
  const saveClient = client.save();
  const saveAddress = req.billing_address.save();
  const saveUser = req.user.save();

  Promise.all([saveUser, saveClient, saveAddress])
    .then(() => {
   // do what you need to do
  }).catch((err) => {
  console.log(err); // this now returns the error object I was looking for!!
  });
```

Maybe just a silly mistake on my part, but it surely took up a lot of my time, so I hope this helps someone else.

**Comment by AbdelrahmanHafez** [comment]
Welcome @leafyshark 

Notice that this is not exactly related to mongoose, but async/await and how they relate to promises in general.

Calling `await client.save()` is equivalent to calling `client.save().then()` (technically `Promise.resolve(client.save()).then(..)`).

So the code in your first snippet actually attempts to `save` documents twice.
That's an interesting read about [async/await error handling](https://javascript.info/async-await#error-handling).

I'll close this issue since it doesn't need any action, please reopen if you need any further assistance. Thanks for sharing the knowledge!

**Comment by AmakaJuliet** [comment]
Thank you for this, you just saved me
