### ISSUE TITLE
mongoose set  'useNewUrlParser'

### ISSUE THREAD

**Issue by anjneeksharma** [Automattic/mongoose#8968]
I am using latest version of node and useing mongonose. i am new to mongonose and i am new to team want to know something bellow i tried to search it in google but not able to understand it.

/* Configuring Mongoose */
mongoose.plugin((schema: any) => { schema.options.usePushEach = true; });
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);

**Comment by anjneeksharma** [comment]
can any one explain me this step by step.

**Comment by AbdelrahmanHafez** [comment]
Welcome @anjneeksharma 
```js
mongoose.set('useNewUrlParser', true);
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);
mongoose.set('useUnifiedTopology', true);
```
Those are added to avoid deprecation warnings. [Read more on mongoose deprecation warnings](https://mongoosejs.com/docs/deprecations.html).

```js
mongoose.plugin((schema: any) => { schema.options.usePushEach = true; });
```
This is a [global plugin](https://mongoosejs.com/docs/plugins.html#global) that sets `usePushEach` to true on all schemas.

**Comment by anjneeksharma** [comment]
thanks a lot @AbdelrahmanHafez  .

**Comment by AbdelrahmanHafez** [comment]
Happy to help 👍
