### ISSUE TITLE
[pre/post] Hooks do not work when using options argument

### ISSUE THREAD

**Issue by harveyconnor** [Automattic/mongoose#8971]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When calling the deleteOne function the pre and post hooks do not work when trying to specify an options argument object.
The docs show that you should do the following
```ts
toySchema.post('deleteOne', { document: true, query: false }, function() {
  // Runs when you call `doc.deleteOne()`
});

toySchema.pre('deleteOne', { document: true, query: false }, function() {
  // Runs when you call `doc.deleteOne()`
});
```

I did a little bit of digging and came across an issue with the way the hooks are applied. They seem to only grab the first and second argument. Now if the second argument is not a function like I have tried, it does nothing because you can't execute the option object as a function.
Where if I remove the options `{ document: true, query: false }`, it works just fine.

**If the current behavior is a bug, please provide the steps to reproduce.**
- I'm using typescript 3.8.3 with Mongoose 5.9.13.

**What is the expected behavior?**
The function will return and let me handle a callback.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS LTS 12, Mongoose 5.9.13, MongoDB 4.

**Comment by harveyconnor** [comment]
Docs show in this section: https://mongoosejs.com/docs/middleware.html#naming

Ref: https://github.com/Automattic/mongoose/issues/8555#issuecomment-586626291

@vkarpov15 You might have some insight into this?

**Comment by vkarpov15** [comment]
@harveyconnor according to your comment here: https://github.com/Automattic/mongoose/issues/8555#issuecomment-626460219 the issue is with your typescript type definitions. We do not maintain typescript definitions currently, you should open an issue on https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by harveyconnor** [comment]
No, that is not true.
There's a discrepancy between what you are telling people to do and the type defs.
 What you've said is to add the options argument `{ document: true, query: false }` however this does not work. Please read again.

**Comment by vkarpov15** [comment]
"Does not work" is not a valid bug report. Please explain exactly what happens - is there some sort of error message?

**Comment by harveyconnor** [comment]
That's the thing, nothing happens.
I set up the hook as you have explained previously and wait for that hook to call when performing the action. But nothing gets called.

**Comment by vkarpov15** [comment]
Are you calling `Query#deleteOne()` or `Document#deleteOne()`?

1) `Model.deleteOne({ name: 'test' })`

or:

2) `const doc = await Model.findOne(); await doc.deleteOne();`

**Comment by harveyconnor** [comment]
I'm calling `Model.deleteOne()`.

**Comment by harveyconnor** [comment]
Okay this is working:
```ts
const doc = await Group.findOne({ _id: id });
if (doc) {
  const removed = await doc.deleteOne({ _id: id });
  return Boolean(removed);
}
```

However the errors are shown:
`Property 'deleteOne' does not exist on type`

And the post hook has an error, I'll try and make a pull request for the type definitions because they are clearly outdated.

**Comment by amolsr** [comment]
You already have the document no need to search it through the _id for
deleting.

**Comment by harveyconnor** [comment]
@amolsr yep that was a mistake
