### ISSUE TITLE
pass index as a second argument for eachAsync

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8972]
re: #8962

Similar to how Bluebird's [Promise.map(...)](http://bluebirdjs.com/docs/api/promise.map.html) passes an index to parallel operations because maintaining your own counter in parallel can easily create bugs.
```js
let counter = 0;

await User.find().sort('order').cursor().eachAsync((doc, i) => {
  doStuffWithCounter(counter);

  // the right hand-side can be evaluated two times in parallel, where it will cause
  // incorrect end result for counter
  counter = counter + 1;
});
```

instead, we should:
```js
doStuffWithCounter(i);
```

Admittedly, I haven't been able to reproduce the parallel reassignment issue with the script above, but I've been bitten by that once before, and I am sure the people will find different ways to utilize it.

**Comment by vkarpov15** [comment]
The right hand side **cannot** be evaluated twice in parallel, JavaScript is single threaded :) It is possible for the counter to get out of sync if your `eachAsync()` callback is async and you use `parallel` though, so this seems helpful.

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 That's probably how I had that issue. Even though I tried to reproduce it with an async function now, with no luck.

https://github.com/Automattic/mongoose/issues/8962#issuecomment-626287856 is a good example that demonstrates the problem with managing an outer value with `parallel` option. I personally try to avoid this altogether.
