### ISSUE TITLE
Can I use Schema.path("production").discriminator(['value1', 'value2'], ProductionSchema) ?

### ISSUE THREAD

**Issue by Jawadgee** [Automattic/mongoose#8975]
I have 8 different types of discriminators in my model. Now some of those have more than one types.

Can I use Schema.path("production").discriminator(['CAMPAIGN_EXTERNAL','CAMPAIGN_INTERNAL'], ProductionSchema) ?

**Comment by vkarpov15** [comment]
@Jawadgee we do not currently support that. But you can do `['CAMPAIGN_EXTERNAL','CAMPAIGN_INTERNAL'].forEach(name => Schema.path("production").discriminator(name, ProductionSchema))` to get the same result.
