### ISSUE TITLE
find virtuals defined on child discriminators breadth-first

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#8980]
in #8978 we're looking for virtuals defined on the current schema, if it's not found, we look for it in discriminators depth-first, it makes more sense to look for it breadth-first.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez why does it make more sense to look for it breadth-first? Not saying you're wrong, I just can't think of a reason to prefer one over the other off the top of my head.

**Comment by AbdelrahmanHafez** [comment]
@vkarpov15 considering the models tree below, if a user tries to access `country` from model A.

The current implementation: it would match AB2.
The suggested implementation: it should match AC.

My reasoning is that AC is a closer version of A than the more mutated AB2, and I would expect to get a match from the closest version of the current model if more than one version have that field.

![models tree](https://user-images.githubusercontent.com/19984935/82624496-04491000-9be3-11ea-9e5d-11518d8d262a.png)

**Comment by vkarpov15** [comment]
Hmm we don't support nested discriminators, so I don't understand what the arrows in the above example mean.

**Comment by AbdelrahmanHafez** [comment]
The following is what I mean. Is this not valid?
```
A = model

AB = A.discriminator(...)
AC = A.discriminator(...)

AB1 = AB.discriminator(...)
AB2 = AB.discriminator(...)
```

**Comment by vkarpov15** [comment]
I don't believe so. A discriminator key is just a string, so we don't support sub-discriminators.

**Comment by AbdelrahmanHafez** [comment]
My whole life has been a lie, lol.
Just tested, you're right, we can not add sub-discriminators.
