### ISSUE TITLE
Cast bulkwrite according to discriminator key

### ISSUE THREAD

**Issue by thebrucecgit** [Automattic/mongoose#8982]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When updating a document with`$push` or `$addToSet` onto a discriminator field, it doesn't not work. I have tried with `findOneAndUpdate`, `findByIdAndUpdate`, `updateOne` and `updateMany`. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const { connect, Schema, model } = require("mongoose");

const personSchema = new Schema({
  name: String,
});

const Person = model("Person", personSchema);

Person.discriminator(
  "Worker",
  Schema({
    locations: [String],
  })
);

connect("mongodb://127.0.0.1:27017/test?gssapiServiceName=mongodb", {
  useNewUrlParser: true,
  useUnifiedTopology: true
}, async () => {
  console.log("Database connected")
  const person = await Person.create(
    {
      __t: "Worker",
      name: "John", 
      locations: ["America"],
    },
  )

  console.log(person);

  await Person.findByIdAndUpdate(
    person._id,
    {
      $push: { locations: "UK" }, 
    },
  )

  const updated = await Person.findById(person._id);

  console.log(updated);
});
```
Logs (the document failed to update):
```
Database connected
{
  locations: [ 'America' ],
  _id: 5eba65381c8ff1d0df0e7414,
  __t: 'Worker',
  name: 'John',
  __v: 0
}
{
  locations: [ 'America' ],
  __t: 'Worker',
  _id: 5eba65381c8ff1d0df0e7414,
  name: 'John',
  __v: 0
}
```

**What is the expected behavior?**
The string `"UK"` should've been pushed onto the `locations` field of the document in the second log. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.9.13
Node: v13.5.0
Mongodb: 4.0.8

**Comment by AbdelrahmanHafez** [comment]
Welcome @thebrucecgit

Discriminator inheritance goes from child => parent, not the other way around. `Person` doesn't know that `Worker` has a `locations` field, so that it's trimmed out of the update object.

The following would achieve the desired results:
```js
const Worker = Person.discriminator('Worker', Schema({ locations: [String] }));

await Worker.updateOne({ _id: person._id }, { $push: { locations: 'UK' } });
```

**Comment by thebrucecgit** [comment]
However, considering that the following works:
```js
const person = await Person.findById(person._id);
person.locations.push("UK");
await person.save();
```
Wouldn't it be expected that the `$push` would also work on the `Person` model?

**Comment by AbdelrahmanHafez** [comment]
After you fetch a document, it's already in memory, so we know at this point it's an instance of Worker, and treat it accordingly.

When sending an update command to the database, at this point we don't know if the document exists or not, and if it exists, we don't know which kind it is, so unless you provide information as to what kind the document is, there is no way to know.

**Comment by AbdelrahmanHafez** [comment]
@thebrucecgit turns out I was wrong, It's not fixed by the commit I mentioned. I just tested in 5.9.13, and the following script works. 

You don't need to wait for the next version. :)

```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Person = mongoose.model('Person', { });

  const Worker = Person.discriminator('Worker', new Schema({ locations: [String] }));

  const worker = await Worker.create({ locations: ['US'] });

  // should cast `update` according to `Worker` schema
  await Person.updateOne({ _id: worker._id, __t: 'Worker' }, { $push: { locations: 'UK' } });

  const person = await Person.findOne({ _id: worker._id });

  assert.deepEqual(person.locations, ['US', 'UK']);
  console.log('All assertions passed.');
}
```

**Comment by thebrucecgit** [comment]
@AbdelrahmanHafez Thanks for the help. I think there is a bug with using `__t: "Worker"` in `bulkWrite`. It causes a `multi update only works with $ operators` error. 

Try this out:
```js
const { connect, Schema, model, connection } = require("mongoose");
const assert = require("assert");

const personSchema = new Schema({ });

const Person = model("Person", personSchema);

Person.discriminator("Worker", new Schema({ locations: [String] }))

connect("mongodb://127.0.0.1:27017/test", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
}, async () => {
  await connection.dropDatabase();

  const person = await Person.create({ __t: "Worker", locations: ["US"] })

  const ids = [person._id];

  await Person.bulkWrite([
    {
      updateMany: {
        filter: { _id: { $in: ids }, userType: "Worker" },
        update: { $push: { locations: "UK" } }
      }
    }
  ]);

  const updated = await Person.findById(person._id);

  assert.deepEqual(updated.locations, ["US", "UK"]);
  console.log("Assertions complete")
});
```

**Comment by AbdelrahmanHafez** [comment]
@thebrucecgit please change the title of the issue to 
`Cast bulkwrite according to discriminator key`
