### ISSUE TITLE
exec() bypasses try/catch block if you don't pass a callback

### ISSUE THREAD

**Issue by chan-dev** [Automattic/mongoose#8989]
While debugging my code, i've seen some requests always were on a **pending** state when checking them on devtools

Here's the particular snippet.
```
try {
    // TODO: note that without the callback inside the .exec, it will
    // bypass the try/catch block when there's an error and will keep the request pending until
    // it timeouts
    subscriber = await Subscriber.findOne({ _id: id }).exec();

    if (!subscriber) {
      return res.status(404).json({
        message: 'Subscriber not found',
      });
    }
  } catch (error) {
    return res.status(500).json({
     message: 'Server error',
    });
  }
```

I've added breakpoints on certain lines inside the `try/catch` block, but when it reaches the line on the `exec()` call, it just skips the whole try/catch block.

But if i added a **calllback** on the `exec`, the error get's caught as expected within the try/catch block. 
```
  subscriber = await Subscriber.findOne({ _id: id }).exec(() => {});
```

May i know why does it behave like this?

While going thru the breakpoints, just stumbled upon this code under this [file](https://github.com/Automattic/mongoose/blob/1bdec388d65e149dbbab156af51bce62d7b3edbf/lib/model.js#L4879)

```
Model.$handleCallbackError = function(callback) {
  if (callback == null) {
    return callback;
  }
  if (typeof callback !== 'function') {
    throw new MongooseError('Callback must be a function, got ' + callback);
  }

  const _this = this;
  return function() {
    try {
      callback.apply(null, arguments);
    } catch (error) {
      _this.emit('error', error);
    }
  };
};

```

What's the reason for the first `if` statement?, i assume it's the one causing the unexpected behaviour?

**Comment by AbdelrahmanHafez** [comment]
Please modify the script below to demonstrate the issue you're facing.
### 8989.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  let caught = false;
  try {
    await User.findOne({ _id: 'invalid' }).exec();
  }
  catch (err) {
    caught = true;
  }

  assert.ok(caught);

  console.log('All assertions passed.');
}
```

### Output:
```
All assertions passed.
```

**Comment by chan-dev** [comment]
Just an update, it seems that it's related with [bufferCommands](https://mongoosejs.com/docs/guide.html#bufferCommands). I was doing a request with one of my mongo models while my **ip address** was not whitelisted in atlas so as a result it allows the mongo model to do the request even before confirming if my connection is ok.

What i did was set the `bufferCommands` option to false on both schema and connection so it would immediately throw any error and not buffer model queries

**Schema** level 
```
mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
```

*Connection* level
```
var schema = new Schema({..}, { bufferCommands: false });
```

Are there any disadvantages on using this setting and why is it not the default since we want to be notified of any error immediately?

**Comment by AbdelrahmanHafez** [comment]
`bufferCommands` was originally added to allow users to initialize their apps without waiting for the Mongo connection to be established. Mongoose buffering layer is being removed in v6 #8702 since Mongo is adding support for that natively.
