### ISSUE TITLE
NaN casting doesnt behave as expected

### ISSUE THREAD

**Issue by phinjensen** [Automattic/mongoose#8993]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Entering non-number value for a path with Number as its SchemaType just casts to undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// Setup, taken from the docs
const mongoose = require("mongoose")
const Schema = mongoose.Schema;
const schema = new Schema({ age: Number });
const Car = mongoose.model('Car', schema);

// All as expected:
new Car({ age: '15' }).age; // 15 as a Number
new Car({ age: true }).age; // 1 as a Number
new Car({ age: false }).age; // 0 as a Number
new Car({ age: { valueOf: () => 83 } }).age; // 83 as a Number

// These should result in a CastError, but instead return undefined
new Car({ age: NaN }).age;
new Car({ age: "test"}).age;
new Car({ age: [1, 2, 3, 4]}).age;
```

**What is the expected behavior?**
The [current docs](https://mongoosejs.com/docs/schematypes.html#numbers) say 

> NaN, strings that cast to NaN, arrays, and objects that don't have a valueOf() function will all result in a CastError.

So those last three statements should all result in a CastError. Instead, they return `undefined`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 12.16.2
Mongoose: 5.9.13 (same behavior on 5.7.7)
MongoDB: 4.2.6

**Comment by AbdelrahmanHafez** [comment]
Errors are thrown on validating documents, not on initializing them, the docs should make that clear.
### 8993.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({
  age: { type: Number }
});

const User = mongoose.model('User', userSchema);

const err = new User({ age: 'test' }).validateSync();

assert.equal(err.errors['age'].name, 'CastError');
assert.match(err.errors['age'].message, /Cast to Number failed/);

console.log('All assertions passed.');
```

### Output
