### ISSUE TITLE
$addToSet replaces the only value in my array rather than adding a new value to the existing list.

### ISSUE THREAD

**Issue by xkyrux** [Automattic/mongoose#9002]
**Do you want to request a *feature* or report a *bug*?** 
Report a bug

**What is the current behavior?**
Replaces my array with the given value

**If the current behavior is a bug, please provide the steps to reproduce.**
                    
                    settings.updateOne(
                        { $addToSet: { wordBlacklist: [args[1]] } }
                    )

**What is the expected behavior?**
I wanted to add the given word to a list of other words... Instead, it just replaces the same value in the array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.16.2
Mongoose: v5.9.13
MongoDB: I am using their online Atlas DB

**Comment by xkyrux** [comment]
I am stupid, my bad

**Comment by vkarpov15** [comment]
You're not stupid, we all make mistakes sometimes :+1:
