### ISSUE TITLE
[Feature request] add Enum as a SchemaType

### ISSUE THREAD

**Issue by OMGerCoder** [Automattic/mongoose#9008]
This is a feature request

**What is the current behavior?**
You cannot add an enum to a database (like a string that only allows certain values)

**What is the expected behavior?**
You should be able to make one.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
5.9.14

**Comment by OMGerCoder** [comment]
An example would be: `
const example = mongoose.Schema({
    exampleColumn: Enum('allowed1', 'allowed2', 'allowed3')
})

**Comment by AbdelrahmanHafez** [comment]
Welcome @OMGerCoder 

You can achieve that using `String` with `enum` option.
```js
const schema = new Schema({
  status: { type: String, enum: ['pending', 'processing', 'done'] } 
});
```
