### ISSUE TITLE
remove `useStrictQuery`, and use `strict` for both options

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9015]
on [strictQuery docs](https://mongoosejs.com/docs/guide.html#strictQuery) it mentions that
>For backwards compatibility, the strict option does not apply to the filter parameter for queries.

6.0 is a good opportunity to get rid of it, and use `strict` option for it by default.

**Comment by jonchurch** [comment]
I'm curious about the context around this change, is there an issue where this was discussed?

**Comment by vkarpov15** [comment]
@jonchurch TBH we should have had more discussion about this. We thought it would be good to remove an extra option, but missed that removing the option had some undesirable consequences.
