### ISSUE TITLE
Query middleware access to document

### ISSUE THREAD

**Issue by Derek-Baum** [Automattic/mongoose#9019]
I was looking at #7538 and there is a comment that seems to be exactly what I need, but it doesn't explain it.

"We will add a deleteOne hook in the next minor release. Until then, you can use findOneAndDelete, and you can use findOne() in your pre('findOneAndDelete') hook as shown here: http://thecodebarbarian.com/introducing-mongoose-5.html"

Is exactly what I'm looking to do, but that link doesn't seem to be about that issue at all.

**Comment by vkarpov15** [comment]
```javascript
schema.pre('findOneAndDelete', async function() {
  const doc = await this.model.findOne(this.getFilter());
  // use doc
});
```
