### ISSUE TITLE
.save() method not saving subdocuments

### ISSUE THREAD

**Issue by mattmcegg** [Automattic/mongoose#9020]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Embedded object not saving subdocuments when using .save() method

**If the current behavior is a bug, please provide the steps to reproduce.**
Write an entry to DB with:
```javascript
const customerDb = await new Customer({
      _id: objectId(),
      userId,
      customerId: customer.id,
      card: { brand: customer.card.brand, last4: customer.card.last4 },
      subscription: { id, status, plan: items.data[0].plan.id, current_period_end },
    }).save()
```
the _id, userId, and customerId write to the database perfectly. However, there is no 'card' or 'subscription' object. Seemingly just skips them:

```javascript
_id: "5ebf61788173562c701bd3d9"
userId: "5ebf616d8173562c7020eb83"
customerId: "cus_HHxd3f8RPKEZXR"
```
**What is the expected behavior?**
Write an entry to DB with:
```javascript
const customerDb = await new Customer({
      _id: objectId(),
      userId,
      customerId: customer.id,
      card: { brand: customer.card.brand, last4: customer.card.last4 },
      subscription: { id, status, plan: items.data[0].plan.id, current_period_end },
    }).save()
```

Expected Output:
```javascript
_id: "5ebf61788173562c701bd3d9"
userId: "5ebf616d8173562c7020eb83"
customerId: "cus_HHxd3f8RPKEZXR"
card: {
name: "VISA",
last4: "1234"
}
subscription: {
id: "sub_123123"
status: "active"
plan: "plan_123123123"
current_period_end: 1589777662
}
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node version: 12.13.1
MongoDB: 3.5.5
Mongoose version: When the bug was occurring, i was using ^5.9.9. I rolled back to 5.9.7 and it's now working.

Here is the Model:
```javascript
import mongoose from "mongoose";
import objectId from "../utils/generateObject";

const { ObjectId, Number, String } = mongoose.Schema.Types;

const CustomerSchema = new mongoose.Schema(
  {
    _id: {
      type: String,
      default: objectId()
    },
    userId: {
      type: String,
    },
    customerId: {
      type: String,
      required: false
    },
    'card.brand': {
      type: String,
      required: false
    },
    'card.last4': {
      type: String,
      required: false
    },
    'subscription.id': {
      type: String,
      required: false
    },
    'subscription.status': {
      type: String,
      enum: ['active', 'cancelling', 'canceled', 'none', 'trialing'],
      required: false
    },
    'subscription.plan': {
      type: String,
      required: false
    },
    'subscription.current_period_end': {
      type: Number,
      required: false
    }
  }, {collection: "Customers"});

export default mongoose.models.Customer || mongoose.model("Customer", CustomerSchema);
```

**Comment by AbdelrahmanHafez** [comment]
Welcome @mattmcegg

Thanks for reporting. This is happening because you're using 'card.brand' on your schema definition, but passing a structured object to your document. This is a bug that should be fixed by mongoose.

However, a couple of suggestions and notes: 
1- Until the bug is fixed, consider the following changes to your schema.
```js
const customerSchema = new mongoose.Schema(
  {
    userId: { type: String },
    customerId: { type: String },
    card: {
      brand: { type: String },
      last4: { type: String }
    },
    subscription: {
      id: { type: String },
      status: {
        type: String,
        enum: ['active', 'cancelling', 'canceled', 'none', 'trialing']
      },
      plan: { type: String },
      current_period_end: { type: Number }
    }
  }, { collection: 'Customers' });
```
2- on your customer schema, you don't need to [manually define an `_id` field](https://mongoosejs.com/docs/guide.html#_id), and calling `default: ObjectId()`, you want to pass `default: ObjectId` without calling it, [mongoose will call the function provided as a default for you](https://mongoosejs.com/docs/defaults.html#default-functions) on creating each document.

You don't need to set `required: false` that's the default.



### 9020.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const customerSchema = new Schema({
  'card.brand': String,
  'card.last4': String
});

const Customer = mongoose.model('Customer', customerSchema);

const customer = new Customer({
  card: { brand: 'VISA', last4: '1234' }
});

assert.equal(customer.card.brand, 'VISA');
assert.equal(customer.card.last4, '1234');

console.log('All assertions passed.');
```

### Output
```js
AssertionError [ERR_ASSERTION]: undefined == 'VISA'
```

Mongoose should structure the flattened paths on initializing the document. The following works
```js
const customer = new Customer({
  'card.brand': 'VISA',
  'card.last4': '1234'
});
```

**Comment by mattmcegg** [comment]
Thanks for the suggestions. I migrated from another database where the IDs were strings, so i had to set them manually like that. Hope this gets fixed soon, cost me about 8 hours yesterday going through code thinking it was an async/await issue with stripe data getting returned.

**Comment by AbdelrahmanHafez** [comment]
Oh, okay.
FWIW, you don't need to wait till it's fixed in order to go on with your life, you can simply change your schema from flattened to structured like so:
```js
const customerSchema = new mongoose.Schema(
  {
    card: {
      brand: { type: String },
      last4: { type: String }
    },
    subscription: {
      id: { type: String },
      status: {
        type: String,
        enum: ['active', 'cancelling', 'canceled', 'none', 'trialing']
      },
      plan: String,
      current_period_end: Number
    }
  });
```

**Comment by mattmcegg** [comment]
> Oh, okay.
> FWIW, you don't need to wait till it's fixed in order to go on with your life, you can simply change your schema from flattened to structured like so:
> 

that would require me updating every existing record in the database to the new schema.... no thanks lol

**Comment by vkarpov15** [comment]
Fix will be in 5.9.15 :+1:

**Comment by AbdelrahmanHafez** [comment]
@mattmcegg
Changing the schema will not require you to change records on your database, you'll be only changing the syntax of the schema definition.

**Comment by mattmcegg** [comment]
> @mattmcegg
> Changing the schema will not require you to change records on your database, you'll be only changing the syntax of the schema definition.

Ahh yes, I see now, I misinterpreted what you meant by flatten. Thanks!
