### ISSUE TITLE
MongooseDocument.validate()

### ISSUE THREAD

**Issue by RussellNur** [Automattic/mongoose#9022]
Hey guys,

Have you thought about changing the return of the **`(method) MongooseDocument.validate(callback?: (err: any) => void): Promise<void>`** to be a boolean rather than a promise?

**Comment by AbdelrahmanHafez** [comment]
Try [Document#validateSync](https://mongoosejs.com/docs/api.html#document_Document-validateSync), It returns an error or null.

```js
const err = doc.validateSync();
if (err) {
  handleError(err);
} else {
  // validation passed
}
```
