### ISSUE TITLE
explain is not work in aggregate

### ISSUE THREAD

**Issue by SHwan93** [Automattic/mongoose#9025]
**Do you want to request a *feature* or report a *bug*?**
question

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
"mongoose": "^5.9.6",

![image](https://user-images.githubusercontent.com/36143374/82178787-c82e5a80-9917-11ea-90e2-b5ea1afcc9f1.png)

![image](https://user-images.githubusercontent.com/36143374/82178840-eeec9100-9917-11ea-9e04-8f07e1995b44.png)

**Comment by vkarpov15** [comment]
The below script works as expected, no error thrown. Can you please show your schemas and connection logic? I'm guessing you have a schema-level or connection level [read preference](https://mongoosejs.com/docs/guide.html#read) or [write concern](https://mongoosejs.com/docs/guide.html#writeConcern)

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const MonitoringData = mongoose.model('Test', Schema({ name: String }));

  const res = await MonitoringData.aggregate([
    { $match: { name: 'test' } },
    { $sort: { name: -1 } },
    { $skip: 0 },
    { $limit: 10 }
  ]).explain();

  console.log(res);
}

```

**Comment by SHwan93** [comment]
![image](https://user-images.githubusercontent.com/36143374/83995716-1f62a080-a995-11ea-9d93-8d7f6ae5ad5d.png)


`import mongoose from "mongoose";

const Schema = mongoose.Schema;

const schema = new Schema(
  {
    brandId: { type: String, required: true },
    articleCode: { type: String, required: true },
    channelKeyname: { type: String, required: true, index: true },
  },
  { collection: "MonitoringData", timestamps: true }
);

schema.index(
  { brandId: 1, channelKeyname: 1, articleCode: 1 },
  { unique: true }
);

// collection name, schema
export default mongoose.model("MonitoringData", schema);
`

**Comment by vkarpov15** [comment]
Is there a readPreference option in your URL?

**Comment by SHwan93** [comment]
MONGODB_URL = "mongodb+srv://xxxxx:xxxxxxxxxxxxxxxxxxx/test?retryWrites=true&w=majority"

readPreference option is not set

**Comment by vkarpov15** [comment]
Oh that's why, you have `w=majority` in your MongoDB URL. That's a [writeConcern](https://mongoosejs.com/docs/guide.html#writeConcern). Remove the `w=majority` option and that should fix this error.

**Comment by SHwan93** [comment]
Thanks :)
now it works
