### ISSUE TITLE
document.save / document.update doesn't work

### ISSUE THREAD

**Issue by RobinSchapendonk** [Automattic/mongoose#9027]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
document.save() / document.update() doesn't save new values in a object in an array

**If the current behavior is a bug, please provide the steps to reproduce.**

Save an array (with objects in it) and change the value of one object
(`[{"test":"a"}] => [{"test":"b"}]`)
Then `document.save()` / `document.update()` doesn't work
`schema.updateOne(query}, data, callback);` does work

**What is the expected behavior?**
It should save the new value

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose v5.9.14
node v12.16.3

**Comment by AbdelrahmanHafez** [comment]
Instead of
```js
doc.myArray[0] = { test: 'b' };

await doc.save();
```

Try
```js
doc.myArray.set(0, { test: 'b' });

await doc.save();
```

Here's why: https://mongoosejs.com/docs/faq.html#array-changes-not-saved

Does this solve the issue you're facing?

**Comment by RobinSchapendonk** [comment]
okay thanks
