### ISSUE TITLE
Please document all parameters to .debug

### ISSUE THREAD

**Issue by dandv** [Automattic/mongoose#9029]
Maybe I haven't found the right documentation page, but the best information I could get about `.debug` was [here](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-set):

> `mongoose.set('debug', function(collectionName, methodName, arg1, arg2...) {}); // use custom function to log collection methods + arguments`

What are the other args?

It's odd that [this SO answer](https://stackoverflow.com/questions/18762264/log-all-queries-that-mongoose-fire-in-the-application/18763020#18763020) has more information than the official docs :) 

What I'm particularly interested in is a way to describe the operation that Mongoose sent to MongoDB at a higher level, e.g. see `populate` in the debugging info.

**Comment by vkarpov15** [comment]
The `...` is like a [spread operator](https://thecodebarbarian.com/object-assign-vs-object-spread.html), so everything after `methodName` is the args passed to the method. So `Model.insertMany([{ x: 1 }])` results in Mongoose passing `'collName', 'insertMany', [{ x: 1 }]` to the debug function.

**Comment by dandv** [comment]
Thanks! I've sent [this PR](https://github.com/Automattic/mongoose/pull/9059) hoping to clarify the docs on `.debug`. If it's too verbose, feel free to remove the "For example" sentence at the end.
