### ISSUE TITLE
Breaking change on version 5.9.14 or 5.9.15

### ISSUE THREAD

**Issue by fromi** [Automattic/mongoose#9035]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I upgraded to latest version today (5.9.15). It broke a feature in my project: when I push a new object into an array in my model, instead of having the object into the array directly, it gets wrapped into another array containing only one item (the object).
I forced back my mongoose dependency to 5.9.13 because it was working fine 8 days ago. It fixed my issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Use mongoose 5.9.13
- Use Typescript and Typegoose
- Create an abstract class, and 2 sub classes, with a shared property and custom properties for the sub types
- Try to push one of those object into an array using mongoose
=> The object gets wrapped into an extra array in the database.

**What is the expected behavior?**
No breaking changes in minor versions :)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v10.16.0
MonogDB: 4.2.6 Enterprise

**Comment by AbdelrahmanHafez** [comment]
Please provide a reproduction script in JavaScript, we don't maintain TypeScript definitions, if it's an issue with Typegoose, you'll need to create an issue there.

**Comment by vkarpov15** [comment]
Please, please, please don't write long prose descriptions of your code. Write an actual code sample. I'm going to close this issue, please open a new issue with code samples.
