### ISSUE TITLE
Aggregation cursor slow `end` event emission when no documents are found

### ISSUE THREAD

**Issue by mikitor** [Automattic/mongoose#9038]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
creating an aggregation pipeline that finds 0 documents and piping the result to any transform stream results in a really slow (approximately 1 min) firing of `end` event, compared to 1 ms in case of finding 1 matching document

**If the current behavior is a bug, please provide the steps to reproduce.**

using any model with a pipeline that produces 0 documents
```javascript
const stream = ExampleModel.aggregate(pipeline)
  .cursor()
  .exec()
  .on('end', () => console.log('aggregation cursor exhausted'))
  .pipe(someTransformStream())
```
**What is the expected behavior?**
emit the `end` event within a few seconds, similar to non 0 cases

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - 12.2.0
Mongoose - 5.9.15
MongoDB - 4.0

**Comment by AbdelrahmanHafez** [comment]
The code below passes. You need to set an event listener to `data` event, otherwise, the `end` event will never be called.

### 9038.js
```js
let endEventFired = false;

User.aggregate()
  .cursor()
  .exec()
  .on('data', console.log) // commenting this out makes the test fail
  .on('end', () => {
    endEventFired = true;
    console.log('aggregation cursor exhausted');
  });

setTimeout(() => {
  assert.ok(endEventFired);
  console.log('All assertions passed.');
}, 5);
```

### Output
```
All assertions passed.
```

**Comment by mikitor** [comment]
You are right, thank you.
