### ISSUE TITLE
list databases

### ISSUE THREAD

**Issue by its-dibo** [Automattic/mongoose#9048]
I am trying to list all databases useing mongodb and mongoose.
with mongodb it successesed, but with mogoose I got an error.

```
mongoose.connect(uri).then( connection=>{
    let Admin = mongoose.mongo.Admin;
    let admin = new Admin(connection.db);
    console.log({ admin });  //s: { db: undefined, topology: undefined, promiseLibrary: undefined }
    console.log({ dbs: admin.listDatabases() });
})
```

but I got the following error:
```
Cannot read property 's' of undefined
```

I'm using the last version of mongoose.

**Comment by eng-dibo** [comment]
solved by using:
```
let admin = new Admin(connection.connections[0].db);
```

**Comment by amankriet** [comment]
After trying the above method, I am getting a different error now - 
`return (0, execute_operation_1.executeOperation)(this.s.db.client, new list_databases_1.ListDatabasesOperation(this.s.db, options));
                                                                   ^

TypeError: Cannot read properties of undefined (reading 'client')`
