### ISSUE TITLE
how do i set custom expiry for each document? ;_;

### ISSUE THREAD

**Issue by babbaranish** [Automattic/mongoose#9051]

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @babbaranish 

Take a look at [MongoDB TTL Indexes](https://docs.mongodb.com/manual/core/index-ttl/). You also might find this [blog post](https://hassansin.github.io/working-with-mongodb-ttl-index) useful.

**Comment by babbaranish** [comment]
> Welcome to GitHub @babbaranish
> 
> Take a look at [MongoDB TTL Indexes](https://docs.mongodb.com/manual/core/index-ttl/). You also might find this [blog post](https://hassansin.github.io/working-with-mongodb-ttl-index) useful.


Thanks got this:

UserSchema.index({ deleteWhen: 1 }, { expireAfterSeconds: 0 });
