### ISSUE TITLE
Investigate async stack trace support

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9055]
Re: #9009. In Mongoose 5, we eagerly create `Error` instances for certain errors, like server selection errors, in order to ensure the user gets a stack trace that points to a line in their code rather than node internals. However, this pattern has significant performance implications because creating error instances takes a disproportionate amount of CPU time.

If we use `async function`s all the way through, we should be able to ensure readable stack traces with [async stack traces](https://thecodebarbarian.com/async-stack-traces-in-node-js-12).

**Comment by daukadolt** [comment]
Hi! Is this something community a newbie can contribute to?

If there is a way to contribute, I'd be thrilled to!

**Comment by vkarpov15** [comment]
@daukadolt you're most welcome to contribute. If you can get even one Mongoose function to work with async stack traces all the way through, that would be very helpful. Just make sure you base any pull requests for this issue against the `6.0` branch.

**Comment by daukadolt** [comment]
@vkarpov15 in the PR above you've mentioned bluebird.

Is supporting bluebird required for compatibility with pre-es2015 javascript?

**Comment by vkarpov15** [comment]
@daukadolt for better or for worse, a lot of people still use bluebird. We don't support pre-ES6 JavaScript (Mongoose 5 requires node 4 or higher), it's more about not wanting to break the guarantee that Mongoose always returns a Bluebird promise if you say `mongoose.Promise = require('bluebird')` given that a fair number of people use that.

**Comment by vkarpov15** [comment]
Going to close this re: https://github.com/Automattic/mongoose/pull/9100#issuecomment-819608011 . Something to consider in the future when there's less friction on async stack traces.
