### ISSUE TITLE
Any plan to be compatible with Deno?

### ISSUE THREAD

**Issue by ghost** [Automattic/mongoose#9056]
This is a feature request.
Do you have any plan to become typescript compatible with Deno?

Using pika.dev version of Mongoose will work?
pkg.fyi/npm:mongoose

Thanks!

**Comment by wenq1** [comment]
Any plan to make smarter judgements?

**Comment by vkarpov15** [comment]
Haven't tried with either Deno or Pika. Will test it out and see if there's anything blocking us.

**Comment by MeisterTea** [comment]
Did anybody managed to use mongoose with deno?

I get a `mongoose.connect` is not a function

**Comment by vkarpov15** [comment]
Haven't tried it yet. Will try out Deno over the weekend and evaluate how much work it would be for us to support it.

**Comment by vkarpov15** [comment]
I took a look at Deno and unfortunately we're currently blocked. Here's what's happening:

1) Do **not** use pika.dev's distribution of Mongoose. For some reason, they're pulling the [browser version of Mongoose](https://mongoosejs.com/docs/browser.html). So you won't be able to connect to MongoDB with Pika's version.

2) Deno currently bugs out with the [require_optional npm module](https://www.npmjs.com/package/require_optional), which is something that the MongoDB driver uses internally.

3) Even without `require_optional`, Deno currently doesn't have a polyfill for Node's crypto module: https://deno.land/std/node/README.md . That's going to be hard for the MongoDB driver to work around.

Here's the Deno script I was working with:

```
import { createRequire } from "https://deno.land/std/node/module.ts";

const require = createRequire(import.meta.url);

const mongoose = require('mongoose');

console.log(mongoose.version);
```

Anybody know of a good workaround for using crypto in deno?

**Comment by luckycreationsindia** [comment]
Anyone tried god crypto module?

https://github.com/invisal/god_crypto

Also MongoDB is available on deno platform:

https://deno.land/x/mongo@v0.12.1

**Comment by ebebbington** [comment]
@luckycreationsindia but deno_mongo is a deno plugin, thus very unstable

**Comment by KotadiyaHiral** [comment]
> Anyone tried god crypto module?
> 
> https://github.com/invisal/god_crypto
> 
> Also MongoDB is available on deno platform:
> 
> https://deno.land/x/mongo@v0.12.1

Yes, MongoDB is available on deno platform, but there is very limited database features.

**Comment by oceaann** [comment]
> I took a look at Deno and unfortunately we're currently blocked. Here's what's happening:

https://developer.mozilla.org/en-US/docs/Web/API/Crypto#browser_compatibility 
![image](https://user-images.githubusercontent.com/47253870/134815642-d0f48eaf-186f-4994-ba9a-ca0ab60311b7.png)

**Comment by rojserbest** [comment]
Ehm we need Deno support.

**Comment by oceaann** [comment]
> Ehm we need Deno support.
yes

**Comment by learner00000** [comment]
I wanna repeat the OP's question:

Any plan to be compatible with Deno?

**Comment by vkarpov15** [comment]
@learner00000 not currently.

**Comment by oceaann** [comment]
> I wanna repeat the OP's question:
> 
> Any plan to be compatible with Deno?

looks like deno will be compatible with mongoose, before they do anything (deno compact mode)

**Comment by Uzlopak** [comment]
It seems, that deno can now load mongoose when using the --unstable flag.

```
import { createRequire } from "https://deno.land/std/node/module.ts";

const require = createRequire(import.meta.url);

const mongoose = require('mongoose');

console.log(mongoose.version);
```

with unstable flag
```
uzlopak@Battlestation:~/workspace/deno-mongoose$ deno --unstable run mongoose.js 
⚠️  ️Deno requests env access to "NODE_DEBUG". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/home/uzlopak/workspace/deno-mongoose/package.json". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/home/uzlopak/workspace/deno-mongoose/node_modules". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/home/uzlopak/workspace/node_modules". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/home/uzlopak/node_modules". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/home/node_modules". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/node_modules". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests env access to all. Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
6.3.0
```

Without unstable-flag
```
uzlopak@Battlestation:~/workspace/deno-mongoose$ deno run mongoose.js 
Check file:///home/uzlopak/workspace/deno-mongoose/mongoose.js
error: TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
    this.#listener?.ref();
                    ~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:240:21

TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
    this.#listener?.unref();
                    ~~~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:243:21

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: { namespace: boolean; }; argv?: unknown[] | undefined; env?: Record<string, unknown> | undefined; execArgv?: string[] | undefined; stdin?: boolean | undefined; stdout?: boolean | undefined; ... 5 more ...; workerData?: unknown; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
        deno: { namespace: true },
        ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.135.0/node/worker_threads.ts:60:9

Found 3 errors.
```

**Comment by roj1512** [comment]
Oh.
