### ISSUE TITLE
Docs FR: add link to edit page on GitHub

### ISSUE THREAD

**Issue by dandv** [Automattic/mongoose#9058]
Would make drive-by edits via GitHub's UI much easier.

MongoDB does it, e.g. 
![image](https://user-images.githubusercontent.com/33569/82968603-8ab67680-9f82-11ea-80c3-7d6ab8e27e5d.png)

**Comment by dandv** [comment]
Thanks for adding this so quickly! Small improvement suggestion: would it make sense to have the link open in a `_blank` target?

**Comment by vkarpov15** [comment]
@dandv good idea, will add that
