### ISSUE TITLE
Unstable behaviour with Model.prototype.save() and await

### ISSUE THREAD

**Issue by pedrokohler** [Automattic/mongoose#9063]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unstable behaviour with save function and await. Sometimes the save function times out without apparent reason.

If you add a error handling callback to the function call it works even though it doesn't yield an error. But it also works in other situations without the error handling callback.

**If the current behavior is a bug, please provide the steps to reproduce.**
It's already kind of a complex project with lots of dependencies, so please access

`https://github.com/pedrokohler/bug-tracker-api`

clone the repository and run `yarn install` followed by `yarn test`.

You'll see that the following tests fail due to timeout

```
const saveMock = jest.spyOn(User.prototype, "save");
describe("createUser", ()=>{
	it("Should create a user", async () => {
		const user = await createUser({
			name: "Pedro",
			role: "Admin",
			profilePicture: "https://picsum.photos/200"
		});
		expect(user).toBeInstanceOf(mongoose.Model);
		expect(user).toHaveProperty("name", "Pedro");
		expect(user).toHaveProperty("role", "Admin");
		expect(user).toHaveProperty("profilePicture", "https://picsum.photos/200");
		expect(user).toHaveProperty("deleted", false);
		expect(user).toHaveProperty("_id");
	});

	it("Should save a user in the db", async ()=> {
		await createUser({
			name: "Pedro",
			role: "Admin",
			profilePicture: "https://picsum.photos/200"
		});
		expect(saveMock).toHaveBeenCalled();
	});
});
```

Both tests above fail, even though the API tests that use the same function work just fine, namely:
```
describe("/user API", ()=>{
	let userID;

	it("Should fail if inexistent user", async ()=>{
		try {
			const res = await supertest.get("/api/v1/user/171d909d-eddd-4a7d-8b8a-477b6dfba9d5");

			expect(res.status).toBe(404);
			expect(res.body).toHaveProperty("data");
			expect(res.body).toHaveProperty("success", false);
			expect(res.body).toHaveProperty("notifications");
		} finally {
			//
		}
	});
    
	it("Should create a new user", async ()=>{
		try {
			const res = await supertest.post("/api/v1/user").send({
				name: "John Doe", 
				role: "User",
				profilePicture: "https://picsum.photos/200"
			});

			expect(res.status).toBe(200);
			expect(res.body).toHaveProperty("data");
			expect(res.body).toHaveProperty("success", true);
			expect(res.body).toHaveProperty("notifications");

			const user = res.body.data;
			expect(user).toHaveProperty("name", "John Doe");
			expect(user).toHaveProperty("role", "User");
			expect(user).toHaveProperty("profilePicture", "https://picsum.photos/200");

			userID = user._id;
		} finally {
			//
		} 
	});

	it("workaround", async () => {
		await supertest.get("/api/v1");
	});
});
```

Everything also works if I call the API after running `yarn dev`.

Another thing I noticed is that if I change create user from 
```
const createUser = async (props) => {
	const user = new User(props);
	await user.save();
	return user;
};
```
to
```
const createUser = async (props) => {
	const user = new User(props);
	await user.save(err => console.log(err));
	return user;
};
```
Both tests work just fine. But this doesn't allow me to handle errors through my try..catch blocks.

**What is the expected behavior?**
It shouldn't time out if I don't use the callback function and shouldn't be unstable.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 14.0.0
Mongoose: 5.9.15
MondoDB: for the tests I'm using mongodb-memory-server version 6.6.1

**Comment by vkarpov15** [comment]
We will look into this, but can you please confirm that you've read and understood our [guide to to testing with Jest](https://mongoosejs.com/docs/jest.html)?

Jest is a very buggy and very nuanced test runner, and it is easy to misconfigure it if you're just getting started. I don't mean to be pedantic, but I strongly recommend using an alternative like [Mocha](https://mochajs.org/).

**Comment by vkarpov15** [comment]
So I dug into this and, once again, the answer is that Jest has a loaded footgun that isn't well documented. The issue is that you're calling `mongoose.connect()` in `globalSetup`, which runs through some [strange `runGlobalHook()` function](https://github.com/facebook/jest/blob/1cc205c274defb24f8b827b8a0c53c161c79d106/packages/jest-core/src/runJest.ts#L242) that seems to execute in a separate environment, which is why they say that you can't access globals from `globalSetup` in your tests. The Jest docs recommend connecting to MongoDB in a `beforeAll()` hook, not a `globalSetup`: https://github.com/facebook/jest/blob/cd415e75d6df4ade18a04007a95e8fc8fd82dd97/docs/MongoDB.md.

We'll add this to the docs. But, once again, I'd strongly recommend against using Jest for Node tests unless you're an expert developer with dozens of hours to spare for debugging odd quirks like this.
