### ISSUE TITLE
(node:3966) UnhandledPromiseRejectionWarning: Error: querySrv ECONNREFUSED

### ISSUE THREAD

**Issue by Lxkiyoshi** [Automattic/mongoose#9067]
## Issue

The following error appears when I make an axios call to fetch user data from mongoose query without internet connection. I've tried to wrap both the mongoose query `User.findOne()` and `mongoose.connect()` with `try catch`, but the error still remain.

> >(node:3966) UnhandledPromiseRejectionWarning: Error: querySrv
> ECONNREFUSED _mongodb._tcp.cluster1-94jth.mongodb.net [0]     at
> QueryReqWrap.onresolve [as oncomplete] (dns.js:196:19) [0] (node:3966)
> UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function
> without a catch block, or by rejecting a promise which was not handled
> with .catch(). (rejection id: 1) [0] (node:3966) [DEP0018]
> DeprecationWarning: Unhandled promise rejections are deprecated. In
> the future, promise rejections that are not handled will terminate the
> Node.js process with a non-zero exit code.

**FRONT-END**
=============

client.js
```
try {							
        const res = await axios.get('/auth/user?', {
                params: {
                    refreshToken: refreshToken,
                    uniqueDeviceID: uniqueDeviceID,
                    authTimestamp: authTimestamp,
                    userID: userID
                }
            }
        );						
        console.log(res.data);
    } catch (error) {
        if(error.toJSON().message === 'Network Error'){
            alert('no internet connection');								
        }
    }
```

**BACK-END**
=============

auth.routes.js
```
auth.get(
  '/user',
  async(req, res)=>{    
    try {
      const {userID, refreshToken, uniqueDeviceID, authTimestamp} = req.query;
      const existingUser = await User.findOne({
        $and: [
            {'user_id': userID},
            {'refresh_token': refreshToken},
            {'unique_device_id': uniqueDeviceID},
            {'auth_timestamp': new Date(authTimestamp).toISOString()}
        ]
      });    
      res.send(existingUser);
    } catch (error) {
      console.log(error);
    } 
  }
);
```

server.js
```
try {
    mongoose.connect(keys.mongoURI, {useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true});    
    console.log('Database Connected');
} catch (error) {
    console.log(error);    
}    
```

**Comment by AbdelrahmanHafez** [comment]
Welcome @Lxkev

That's an issue with mongoose connection to the database, frontend is irrelevant here.
Instead of `mongoose.connect(...)` try `await mongoose.connect(...)` otherwise your catch block will not be able to catch the connection error.
