### ISSUE TITLE
Possibility of having v4.13 use a patched version of mongodb?

### ISSUE THREAD

**Issue by rubenstolk** [Automattic/mongoose#9068]
Ref https://www.npmjs.com/advisories/1203

Legacy apps with mongoose v4 run into this npm vuln. Not sure if it is possible but could it be possible to use mongoose with mongodb > 3.1.13?

**Comment by vkarpov15** [comment]
Unfortunately not without breaking semver. Because of all the breaking changes between `mongodb@2.x` and `mongodb@3.x`, we aren't able to support `mongodb@3.x` with Mongoose 4.

Is there anything in particular blocking you from upgrading to Mongoose 5?

**Comment by rubenstolk** [comment]
Yeah, my time :)

**Comment by vkarpov15** [comment]
Sorry about that, wish I could be more helpful :( If you have any issues upgrading, drop a note here and I'm happy to help :+1:

**Comment by rubenstolk** [comment]
Thanks a bunch, like ever!
