### ISSUE TITLE
TypeError: options.populate.map is not a function

### ISSUE THREAD

**Issue by juji** [Automattic/mongoose#9073]
Happening on 5.9.16

On this:

```js
await Update.findOne({
  status: UPDATE_STATUS.PENDING,
  _id: update_id
})
.populate({
  path: 'place',
  populate: 'category'
})
.populate({
  path: 'user'
})
```

This is the error message:
```
TypeError: options.populate.map is not a function
at populate (/app/node_modules/mongoose/lib/model.js:4425:37)
at _populate (/app/node_modules/mongoose/lib/model.js:4302:5)
at /app/node_modules/mongoose/lib/model.js:4278:5
at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
at Function.Model.populate (/app/node_modules/mongoose/lib/model.js:4276:10)
at model.Query.Query._completeOne (/app/node_modules/mongoose/lib/query.js:2098:9)
at Immediate.<anonymous> (/app/node_modules/mongoose/lib/query.js:2137:10)
at Immediate.<anonymous> (/app/node_modules/mquery/lib/utils.js:116:16)
at processImmediate (internal/timers.js:456:21)
at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by AbdelrahmanHafez** [comment]
Please modify the script below in order to reproduce the issue.

### 9073.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();



  const userSchema = new Schema({ name: String });
  const User = mongoose.model('User', userSchema);

  const buildingSchema = new Schema({ ownerId: { type: Schema.ObjectId, ref: 'User' } });
  const Building = mongoose.model('Building', buildingSchema);

  const officeSchema = new Schema({
    title: String,
    buildingId: { type: Schema.ObjectId, ref: 'Building' },
    employeeId: { type: Schema.ObjectId, ref: 'User' }
  });
  const Office = mongoose.model('Office', officeSchema);

  const user = new User({ name: 'Hafez' });
  const building = new Building({ ownerId: user._id });
  const office = new Office({ buildingId: building._id, employeeId: user._id });

  await Promise.all([
    user.save(),
    building.save(),
    office.save()
  ]);

  const foundOffice = await Office.findOne({ _id: office._id })
    .populate({ path: 'buildingId', populate: 'ownerId' })
    .populate({ path: 'employeeId' });

  assert.equal(foundOffice.buildingId.ownerId.name, 'Hafez');
  assert.equal(foundOffice.employeeId.name, 'Hafez');
  console.log('All assertions passed.');
}


```

### Output
```
All assertions passed.
```

**Comment by Glangouet** [comment]
Hello,
it seems that I have the same problem with 5.9.10

Error: 

` | /app/node_modules/mongoose/lib/model.js:4425
 |       const opts = options.populate.map(pop => Object.assign({}, pop, {
 |                                     ^
 | 
 | TypeError: options.populate.map is not a function
 |     at populate (/app/node_modules/mongoose/lib/model.js:4425:37)
 |     at _populate (/app/node_modules/mongoose/lib/model.js:4302:5)
`

Model request:

`return this.TeamModel.findOne({
            '_id': teamId,
            $or: [{owner: user}, {members: {$in: [user._id]}}]
        }).populate([
            {path: 'owner', populate: ['profile_photo']},
            'files',
            {path: 'members', populate: ['profile_photo']},
            'cover_image',
            {path: 'training', populate: ['cover_image', 'files', 'user']},
            {path: 'messages', populate: [{path: 'user', populate: 'profile_photo'}]}
        ]).lean().exec();`

It seems to appear when I use .lean() and .exec()

**Comment by AbdelrahmanHafez** [comment]
@Glangouet adding `.lean().exec()` still passes in the script above, can you modify it to reproduce the issue?

**Comment by vkarpov15** [comment]
I wasn't quite able to repro this without making some changes internally, but I think this issue is due to users trying to `populate()` a nested path. Which is unnecessary of course, but we should just treat it as a no-op.
