### ISSUE TITLE
TypeError: currentTime isn't defined in SchemaTimestampsConfig

### ISSUE THREAD

**Issue by hrafaelveloso** [Automattic/mongoose#9074]
**Do you want to request a *feature* or report a *bug*?**
Type error

**What is the current behavior?**

As seen in https://mongoosejs.com/docs/guide.html#timestamps we can make mongoose use a different timestamp. However, when setting `currentTime` inside `timestamps` object, there's a TypeError: 

`Type '{ currentTime: () => Date; }' is not assignable to type 'boolean | SchemaTimestampsConfig'.`

```js
interface SchemaTimestampsConfig {
  createdAt?: boolean | string;
  updatedAt?: boolean | string;
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const timestamp = (): Date => {
  return zonedTimeToUtc(new Date(), timeZone);
};

const MySchema: Schema = new Schema(
  {
    ...schema,
  },
  {
    timestamps: {
      currentTime: () => timestamp(),
    },
  }
)
```

NodeJS v12.16.2
mongoose@5.9.16

**Comment by AbdelrahmanHafez** [comment]
Welcome @hrafaelveloso

We don't have official typescript support right now. Follow #8108 for updates. In the meantime, you'll have to open up an issue with DefinitelyTyped or whichever project you use for TypeScript bindings.
