### ISSUE TITLE
How to get the fields set 'select' to false in Schema

### ISSUE THREAD

**Issue by evergreencoder** [Automattic/mongoose#9084]
**Do you want to request a *feature* or report a *bug*?**
- feature

**What is the current behavior?**
- How to get all the field set 'select' to false in Schema

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want to write a curl query build of mongoose, use like this

> [GET] http://host/user/:id?query=&fields=name,photo to search data.

> The UserSchame = new Schema({
>     name: String,
>     gender: number,
>     password: { type: String, select: fasle }
>     otherPrivate: { type: String, select: false  }
> })

then use 

> Model.users.find().select(stringToSelect(**fields**)) 

to return data.
but if the **fields** contain password and otherPrivate it will return the user’s password 
if there some api to get all the field set select to false like
> User.schema.notSelectable or User.schema.selectable

then i can use **filedsArray**.filter(o => selectable.includes(o) ) to prevent damage

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.6

**Comment by AbdelrahmanHafez** [comment]
You can do that by writing a function that loops through paths and find the paths with `select: false` option.

### 9084.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({
  name: { type: String },
  private1: { type: String, select: false },
  private2: { type: String, select: false },
  nested: { private3: { type: String, select: false } }
});

const User = mongoose.model('User', userSchema);

const fields = getNonSelectableFields(User);
assert.deepEqual(fields, ['private1', 'private2', 'nested.private3']);

console.log('All assertions passed.');

function getNonSelectableFields(Model) {
  return Object.values(Model.schema.paths)
    .filter(path => path.options.select === false)
    .map(path => path.path);
}
```

### Output
```
All assertions passed.
```
