### ISSUE TITLE
MongooseDocument { undefined } and doc.someProp

### ISSUE THREAD

**Issue by thernstig** [Automattic/mongoose#9085]
**Do you want to request a *feature* or report a *bug*?**

Feature? Bug?

**What is the current behavior?**

I have a document field like:

```js
var parentSchema = new Schema({
  time: Date,
  child:  {
    prop1: String,
    prop2: String,
  }
}
```

According to https://mongoosejs.com/docs/subdocs.html#altsyntaxsingle this should not work since I do not have `{ typePojoToMixed: false }`.

Also, in the example in that link above it also shows that `type:` is needed (is that correct that it is needed?)

But it does work in a sense, or I am confused on what is supposed to happen according to the docs that says it is a mixed type instead.

I query (`findOne`) and get a document that has only filled in the date. When I then do `if (doc.child)` it returns true. Checking `console.log(doc.child)` gives `MongooseDocument { undefined }`.

Is the intention here that I need to do `doc.child.toObject()` (or `lean()` on the query) to have this work? Or is there a way mongoose could instead return undefined subdocs as `undefined` instead?

The reason I am asking is that this caused a bug in the above if check where the subdoc was undefined, but returned truthy since it was gave `MongooseDocument { undefined }`.

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose 5.9.13
Node.js 12.15.0
MongoDB 3.6

**Comment by vkarpov15** [comment]
You don't need `type`, that schema declaration works as expected and is **not** a mixed type. We'll improve the documentation around this.

The reason why `doc.child` is not undefined is explained in this comment: https://github.com/Automattic/mongoose/issues/5310#issuecomment-307666824 . TLDR; Mongoose needs it for change tracking on nested paths, because you can't `Object.defineProperty()` on a null value.

2 ways to work around this:

1) Check `if (doc.child.$isEmpty())` rather than `if (doc.child == null)`
2) Use a single nested subdoc instead: `new Schema({ child: new Schema({ prop1: String }) })`

**Comment by thernstig** [comment]
@vkarpov15 Does this mean if I remove `minimize: false` on the schema I have, then `if (doc.child)` will work in this case?

I read here https://mongoosejs.com/docs/guide.html#minimize that `doc.inventory; // {}` when  `minimize: false`, but should that piece of text instead show `MongooseDocument { undefined }`?

**Comment by thernstig** [comment]
Also `if (doc.child.$isEmpty())` did not work, it still passes as truthy. To be more explicit, this is what I see:

```javscript
  console.log(doc.child);              // MongooseDocument { undefined }
  console.log(doc.child.$isEmpty());   // true
  console.log(doc.child.toObject());   // undefined
```

**Comment by vkarpov15** [comment]
`minimize: false` just means that Mongoose won't automatically remove empty objects. `if (doc.child)` will still always be true.

Re: `doc.inventory; // {}`, you're right, we should change that.

Re: checking for empty, you should do `if (!doc.child.$isEmpty())`. `$isEmpty()` returns `false` if you have an empty nested path.

**Comment by thernstig** [comment]
Thanks. The `MongooseDocument { undefined }` is a bit confusing (and unconventional) hence, so easy to miss one has to use `$isEmpty()` - haven't seen other projects use that for empty objects but I do see the reasons being mentioned here https://github.com/Automattic/mongoose/issues/5310#issuecomment-307666824 - but I bet this will always continue to be a source of confusion for users, considering a nested path looks exactly like a nested object on a prop.

**Comment by vkarpov15** [comment]
I agree it is confusing and unconventional. We would love to replace this behavior someday, but don't have a good idea of how to do so right now. I'm hoping that the work we're doing with proxies for #8884 will lead to a better solution.
