### ISSUE TITLE
Memory issue in v5.9.16

### ISSUE THREAD

**Issue by markoboy** [Automattic/mongoose#9087]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

model.collection.insertMany stores does not release the memory allocation after functions have returned. I've been searching for more than 2 days and cant find a way to fix it.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a gist with the current code: https://gist.github.com/markoboy/5c14e3cf7ce0ba25589f1cdd0fafd8eb

I have a post route in an express server that parses a CSV file and then updates the DB with the incoming values. As I need to calculate the differences between the CSV data and the stored data, I am using bulkWrite to soft delete the data that are not included in the CSV and update the data that have different values from the ones stored in the DB. I was doing that with a map containing the deletes, updates and inserts but that was using too much memory resulting in heap memory error. The CSV data are 13k> rows, I need to compare the data and DB in order to update a third party with only the changed data.

The node server at the moment after the code has been executed has ~200MB memory allocated and it is not getting garbage collected. I have attached a few screenshots of the memory snapshot.

**What is the expected behavior?**

After the DB changes are made to release the memory.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.16.3
Mongoose: v5.9.16
MongoDB: v3.6.9 (MMAPv1) (Heroku mLab)

![image](https://user-images.githubusercontent.com/35178536/83668699-4a7d7680-a5c8-11ea-8442-5a52a9e8698c.png)
![image](https://user-images.githubusercontent.com/35178536/83668646-35a0e300-a5c8-11ea-9adf-2412a56b53e0.png)

Please let me know if I need to provide any further information, I am really struggling with this and have tried and search a lot. Thanks.

**Comment by markoboy** [comment]
Hello for anyone that might be facing similar issues, I was able to clear the memory by using bulkWrite operation instead with upsert for inserting documents instead.

Instead of having 2 different methods for updates/inserts I got one and update the db every 1000 objects:

```javascript
// Results is the array with all objects from the CSV
while (results.length) {
  const batch = results.splice(0, 1000);

  const updateRes = await updateVehicleCollection(DevVehicle, batch, changes);
}
```

Function declaration:

```javascript
function updateVehicleCollection(vehicleModel, collection, changes) {
  console.log('Bulkwrite for updating vehicles started');

  // createdAt -> When the vehicle is added in the Database
  // updatedAt -> When the vehicle is updated with new values, this is used to check for vehicle updates
  // lastUpdatedAt -> When the vehicle was last updated/added in the Database, this is needed to check if a vehicle needs to get deleted

  return vehicleModel.collection
    .bulkWrite([
      // Update vehicles that have different values from the ones in the collection
      ...collection.map(veh => (
        {
          updateOne: {
            filter: {
              $and: [
                { objectID: veh.objectID },
                {
                  $or: [
                    {
                      Price: { $nin: [veh.Price] }
                    },
                    {
                      VehicleStatus: { $nin: [veh.VehicleStatus] }
                    },
                  ]
                }
              ]
            }
          },
          update: { ...veh, updatedAt: changes.lastUpdate },
        }
      )),

      // Upsert vehicles that are not currently in the Database
      ...collection.map(veh => (
        {
          updateOne: {
            filter: { objectID: veh.objectID },
            update: {
              $setOnInsert: { createdAt: changes.lastUpdate },
              $set: { ...veh, lastUpdateAt: changes.lastUpdate }
            },
            upsert: true,
          }
        }
      )),
    ]);
}
```

**Comment by Uzlopak** [comment]
Why do you map through the arrays? Probably this is the reason, why node can not gc the data.

assign the data to a variable, then assign it to the mongoosequery and when you are done set the variable to undefined to potentially enforce node to gc the data.

**Comment by markoboy** [comment]
> Why do you map through the arrays? Probably this is the reason, why node can not gc the data.
> 
> assign the data to a variable, then assign it to the mongoosequery and when you are done set the variable to undefined to potentially enforce node to gc the data.

Hello @Uzlopak , sorry for the late response. I've tried that but I am still getting same results.

![image](https://user-images.githubusercontent.com/35178536/85288109-23121f00-b48d-11ea-9477-83e45b6c2fea.png)

```javascript
function updateVehicleCollection(vehicleModel, collection, changes) {
  let updateOperations = [];
  let insertOperations = [];

  collection.forEach(veh => {
    // Same query as the above snippet
    updateOperations.push({ updateOne: { filter: { ... }, update: { ...veh } } });
    insertOperations.push({ updateOne: { filter: { ... }, update: { ...veh }, upsert: true } });
  });

  const updateRes = await vehicleModel.collection.bulkWrite(updateOperations);
  const insertRes = await vehicleModel.collection.bulkWrite(insertOperations);

  insertOperations = [];
  updateOperations = [];

  return [updateRes, insertRes];
}
```

I have even separated the update/insert to two bulk operations, but it still keeps some memory as you can see on the graph above.

When there is a restart, the memory gets cleared as it should. When the server runs after it has finished its job (the spikes) it still keep the memory.

After the adoption of your suggestion it seems to store less memory than before when the job is done (after 9am). For some reason as you can see from the graph the memory allocation is always different after a job has finished. The CSV imported is around 190-220MB, when it finishes adding the data to DB, the memory allocation stays at 100-160MB.

I've tried a lot of ways on solving this, at least with the current implementation the server does not run out of memory and it updates everything as I need.

**Comment by vkarpov15** [comment]
Node's garbage collection is pretty unpredictable, because gc is expensive. Your graph doesn't show a memory leak, it just shows that node's garbage collector takes a little while to kick in.

If you're concerned about memory usage, I would recommend minimizing all the unnecessary object cloning using the spread operator:

```
// Replace this:
update: { ...veh, updatedAt: changes.lastUpdate }
// With this:
update: Object.assign(veh, { updatedAt: changes.lastUpdate })
```

Similarly, you can try using individual `updateOne()` operations in a `for` loop rather than a single `bulkWrite()`. That may help reduce the spike in memory usage.

Another possibility is that you're keeping a reference to `const form = new formidable.IncomingForm();` for the entire duration of the upload process. You may want to try creating a separate function that you run when you're done parsing the form.

**Comment by markoboy** [comment]
Hello for anyone that might be having similar issue. I managed to solve this, it was kinda stupid...

```
        {
          updateOne: {
            filter: {
              $and: [
                { objectID: veh.objectID },
                {
                  $or: [
                    {
                      Price: { $nin: [veh.Price] }
                    },
                    {
                      VehicleStatus: { $nin: [veh.VehicleStatus] }
                    },
                  ]
                }
              ]
            }, 
            update: { ...veh, updatedAt: changes.lastUpdate }, // should be inside updateOne query
          },
          // update: { ...veh, updatedAt: changes.lastUpdate },
        }
```

The **update** on the first bulk should be within the updateOne query. I managed to find this as the query was not working on Mongodb Atlas that uses newer version of the database.

Sorry for posting on a closed issue.
