### ISSUE TITLE
Mongoose sort - return falsy values last

### ISSUE THREAD

**Issue by Stanys-dev** [Automattic/mongoose#9090]
Some of my documents contain falsy values (Null). While sorting, I want that all documents containing falsy values would be returned last. Is it possible to do with MongoDB query? I'm using mongoose 5.9.7

Current sort results:
 

 - descending:  [{a:2}, {a:1}, {a:null}], this is correct.
 - ascending: [{a:null}, {a:1}, {a:2}], what I want is: [{a:1}, {a:2}, {a:null}]

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @Stanys-dev 

Sorting is determined by MongoDB, not mongoose. You can not do that with a regular query, you'll need to use the aggregation framework to achieve that.
### 9090.js
```js
'use strict';
const mongoose = require('mongoose');
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const User = mongoose.model('User', { age: Number });

  await User.insertMany([
    { age: 20 },
    { age: null },
    {},
    { age: 30 },
    { age: 25 }
  ]);

  const users = await User.aggregate([
    { $addFields: { ageFieldType: { $type: '$age' } } },
    { $sort: { ageFieldType: 1, age: 1 } }
  ]);

  const ages = users.map(user => user.age);

  assert.deepEqual(ages, [20, 25, 30, undefined, null]);

  console.log('All assertions passed.');
}
```



### Output
```
All assertions passed.
```

**Comment by vkarpov15** [comment]
Unfortunately not, MongoDB's sort order is [hard coded for different types](https://docs.mongodb.com/manual/reference/bson-type-comparison-order/#bson-types-comparison-order) currently. If you need a custom sort order, I'd recommend adding an `aPriority` field that contains a number that you sort by.

`[{a:1, aPriority: 1}, {a:2, aPriority: 1}, {a:null, aPriority: 0}]`

And then sort by `{ aPriority: -1, a: 1}` or `{ aPriority: -1, a: -1 }`
