### ISSUE TITLE
I'm trying to remove items from a list using this code,app.post("/delete", function (req, res) {      const checkeditemid=req.body.checkbox;      Item.findByIdAndRemove(checkeditemid, function(err){         if(!err){         console.log("deleted");   res.redirect("/");  } }); });  but it ain't working yet on mu mongoose connect i got this code,mongoose.connect("mongodb://localhost:27017/todolistDB", {useNewUrlParser:true , useUnifiedTopology: true,useFindAndModify:false,useCreateIndex:true}); 

### ISSUE THREAD

**Issue by markngunyangi** [Automattic/mongoose#9109]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by michaelgosling** [comment]
As was mentioned, you’ll have an easier time debugging this if you log the deletedItem. I would also recommend logging `JSON.stringify(req)` so you know what the request looks like, and also log `err` when it exists.

**Comment by cvivasa** [comment]
Try using:
`{_id: checkeditemid}` instead of `checkeditemid` ... 

Also `deleteOne` works best for me
