### ISSUE TITLE
Model.watch([pipeline], options) is not working.

### ISSUE THREAD

**Issue by williamdarkocode** [Automattic/mongoose#9112]
**Below is my current implementation of change streams using mongoose. I'm using mongodb atlas, and currently the existing examples of change streams with mongoose require you to create a replica set, which isn't needed on atlas. However, I'm following the `Model.watch([pipeline], options) `example on the mongoose docs, which is the same as the mongodb driver example, but the change stream doesn't pick up on any database changes when I insert, update, or delete. When the parameters of pipeline, and options are removed, however, the change stream works, returning all database changes, unfiltered, which isn't the desired behaviour.**

```
const mongoose = require("mongoose");
const mongodb = require('mongodb');

const db = process.env.MONGODB_URI_PROD;
mongoose
.connect(db, {
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
})
.then(() => {
    console.log("Connected to MongoDB...");
})
.catch(err => {
    console.log(err);
});

const pipeline = [
        { 
          '$match': {
            '$or': [{ 'operationType': 'insert' },{ 'operationType': 'update' }], 
            'fullDocument.institution': uniId 
          } 
        }
];

const changeStream = Post.watch(pipeline, options);

changeStream.on("change", next => {
        console.log("Changed happened: ", next);
        switch(next.operationType) {
          case 'insert':
            console.log('an insert happened...', "uni_ID: ", next.fullDocument.institution);
            let rooms = Object.keys(socket.rooms);
            console.log("rooms: ", rooms);
          
            nmsps.emit('insert', {
              type: 'insert',
              msg: 'New question available',
              newPost: next.fullDocument
            });
            break;
  
          case 'update':
            console.log('an update happened...');
  
            nmsps.emit('update', {
              type: 'update',
              postId: next.documentKey._id,
              updateInfo: next.updateDescription.updatedFields,
              msg: "Question has been updated."
            });
            break;
  
          case 'delete':
            console.log('a delete happened...');
  
            nmsps.emit('delete', {
              type: 'delete',
              deletedId: next.documentKey._id,
              msg: 'Question has been deleted.'
            });
            break;
  
          default:
            break;
        }
      })
```

**Comment by vkarpov15** [comment]
What is your `options` and what does your post schema look like? The below code successfully prints an event on every insert:

```javascript
const mongoose = require("mongoose");

const db = 'mongodb+srv://OMITTED:OMITTED@OMITTED.mongodb.net/<dbname>?retryWrites=true&w=majority';
mongoose
.connect(db, {
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true
})
.then(() => {
    console.log("Connected to MongoDB...");
})
.catch(err => {
    console.log(err);
});

const pipeline = [
        {
          '$match': {
            '$or': [{ 'operationType': 'insert' },{ 'operationType': 'update' }],
            'fullDocument.name': 'Test'
          }
        }
];

const Post = mongoose.model('Post', new mongoose.Schema({ name: String }));
const changeStream = Post.watch(pipeline);

setInterval(() => {
  Post.create({ name: 'Test' });
}, 10000);

changeStream.on("change", next => {
        console.log("Changed happened: ", next);
        switch(next.operationType) {
          case 'insert':
            console.log('an insert happened...', "uni_ID: ", next.fullDocument);
            break;
          case 'update':
            console.log('an update happened...');
            break;
          case 'delete':
            console.log('a delete happened...');
            break;
          default:
            break;
        }
      })
```

Please modify the above script to demonstrate your issue.

**Comment by Css-animations44** [comment]
> What is your `options` and what does your post schema look like? The below code successfully prints an event on every insert:
> 
> const mongoose = require("mongoose");
> 
> const db = 'mongodb+srv://OMITTED:OMITTED@OMITTED.mongodb.net/<dbname>?retryWrites=true&w=majority';
> mongoose
> .connect(db, {
>     useNewUrlParser: true,
>     useFindAndModify: false,
>     useUnifiedTopology: true
> })
> .then(() => {
>     console.log("Connected to MongoDB...");
> })
> .catch(err => {
>     console.log(err);
> });
> 
> const pipeline = [
>         {
>           '$match': {
>             '$or': [{ 'operationType': 'insert' },{ 'operationType': 'update' }],
>             'fullDocument.name': 'Test'
>           }
>         }
> ];
> 
> const Post = mongoose.model('Post', new mongoose.Schema({ name: String }));
> const changeStream = Post.watch(pipeline);
> 
> setInterval(() => {
>   Post.create({ name: 'Test' });
> }, 10000);
> 
> changeStream.on("change", next => {
>         console.log("Changed happened: ", next);
>         switch(next.operationType) {
>           case 'insert':
>             console.log('an insert happened...', "uni_ID: ", next.fullDocument);
>             break;
>           case 'update':
>             console.log('an update happened...');
>             break;
>           case 'delete':
>             console.log('a delete happened...');
>             break;
>           default:
>             break;
>         }
>       })
> Please modify the above script to demonstrate your issue.





https://yorklifter19.github.io/spleen27/
