### ISSUE TITLE
when i type name as "diagnosis" it save it in mongodb as "diagnoses"

### ISSUE THREAD

**Issue by Rocky49** [Automattic/mongoose#9113]
Bug

when i type name as "diagnosis" it save it in mongodb as "diagnoses"

**steps to reproduce.**
create a new model "diagnosis" and check what it stores it in mongodb

mongoose v5.9.10

**Comment by Green-Cat** [comment]
The plural of "diagnosis" is "diagnoses", this is correct.

**Comment by cvivasa** [comment]
This is a "by design" feature. As long as you keep it in mind for your schema its fine.

**Comment by vkarpov15** [comment]
This is by design. If you want to disable Mongoose automatically pluralizing collection names, you can use the [`mongoose.pluralize()` function](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-pluralize).

```javascript
mongoose.pluralize(null); // Now, if model name is 'Diagnosis', the collection name will also be 'Diagnosis'
```
