### ISSUE TITLE
Inconsistency in Model.schema.path, Model.schema.subpaths

### ISSUE THREAD

**Issue by horvbalint** [Automattic/mongoose#9114]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using the following field syntax for a schema
`field: {
    subfield: String
}`
I will get a 'field.subfield' entry in the Model.schema.paths object, recognizing, that "subfield" is an instance of built in StringSchema.

But when I use this syntax, which is in my opinion closer to what mongoose should like:        
`field: {
    type: {subfield: String},
    alias: 'Something',
    ...
}`
The  'field.subfield' entry in the Model.schema.paths object will not appear. Mongoose will only recognize that "field" is type 'Mixed'.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a schema with one field for both of the syntax above.
2. Inspect the Model.schema.paths route

**What is the expected behavior?**
In both of this cases mongoose should provide an entry in the Model.schema.paths object.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v10.20.1
Mongoose: ^5.9.0
MongoDB: 4.2.7

**Comment by vkarpov15** [comment]
See [mixed docs](https://mongoosejs.com/docs/schematypes.html#mixed). Unfortunately, this is currently expected behavior. Do this instead:

```javascript
field: { type: new Schema({subfield: String}), alias: 'Something', ... }
```

In 6.0, we'll automatically add the `new Schema()` bit for you (see #7181), but for Mongoose 5 you have to add it yourself.

**Comment by horvbalint** [comment]
Thank you very much!
This will help a lot.
