### ISSUE TITLE
Support MongoDB Atlas full text search

### ISSUE THREAD

**Issue by sanderfish** [Automattic/mongoose#9115]
**Feature request**

MongoDB Atlas announced Atlas Search is now generally available: 

https://www.mongodb.com/atlas/search
https://docs.atlas.mongodb.com/atlas-search/

Mongoose (5.9.17) currently doesn't support the Atlas Search `$search` pipeline in aggregations. It throws the error

```
MongoError: Unrecognized pipeline stage name: '$search'
```

It would be amazing if Mongoose could support Atlas Search.

**Comment by vkarpov15** [comment]
That error comes from MongoDB, not Mongoose. Make sure you're connecting to MongoDB Atlas and your cluster is running at MongoDB 4.2 or higher: https://docs.atlas.mongodb.com/atlas-search/. Below script works fine against my Atlas cluster:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb+srv://OMITTED:OMITTED@OMITTED.mongodb.net/sample_mflix?retryWrites=true&w=majority', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  const Movie = mongoose.model('Movie', Schema({
    title: String,
    plot: String
  }));

  const res = await Movie.aggregate([
  {
    $search: {
      "text": {
        "query": "baseball",
        "path": "plot"
      }
    }
  },
  {
    $limit: 5
  },
  {
    $project: {
      "_id": 0,
      "title": 1,
      "plot": 1
    }
  }
  ]);

  console.log('Result', res);
}

```

That being said, we'll add a `Aggregate#search()` helper for consistency with other pipeline stages.

**Comment by rocknrolla777** [comment]
you could check this package - https://www.npmjs.com/package/mongoose-atlas-search
