### ISSUE TITLE
Mongoose connects to any database name even if it does not exist

### ISSUE THREAD

**Issue by butlimous** [Automattic/mongoose#9116]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Mongoose successfully connects to any database name in the connection string even if it does not exist!

**If the current behavior is a bug, please provide the steps to reproduce.**
I use the following code to connect:
```
  try {
    await mongoose.connect(`mongodb://localhost:27017/test`,
      {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        serverSelectionTimeoutMS: 1000
      }
    );
    console.log('Database connected');
  } catch {
    console.log(`Failed to connect to MongoDB`);
  }
```

**What is the expected behavior?**
Only connect to the database name `test` ONLY if it exists. However, the connection successfully starts even if no database named `test`. It just accepts anything as database name!

I feel this is by design but I would appreciate it if you explain why it's designed like this.

**Comment by vkarpov15** [comment]
By design, because MongoDB lets you read from and write to non-existent databases, modulo any auth restrictions. Practically speaking, there's no difference between an empty database and a non-existent database. MongoDB just removes the extra overhead of having to manually create the database.
