### ISSUE TITLE
Default projections on Model.create not working?

### ISSUE THREAD

**Issue by js-kyle** [Automattic/mongoose#9118]
**Do you want to request a *feature* or report a *bug*?**
Possible bug, I'm unsure if it is intended behaviour or not.

**What is the current behavior?**
Model.create, will return the new Mongoose Document, which does not have Schema level projections applied, when I expected them to.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
'use strict';

const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const authorSchema = new mongoose.Schema({
    name: String,
    hiddenField: {type: String,  select: false }
  });

  const Author = mongoose.model('Author', authorSchema);

  let example = await Author.create({ name: 'John', hiddenField: 'A secret' });
  console.log(example.toJSON().hiddenField);
  // 'A secret' is logged, which was not expected

  example = await Author.findOne({ name: 'John'});
  console.log(example);
  // the field with a default project is not returned (expected)
}
```
**What is the expected behavior?**
In the above example, I would expect 'A secret' to not be logged, as it has a `false` projection applied to all find queries, set by ` select: false` in the schema

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose@5.9.18

**Comment by vkarpov15** [comment]
That's a good point. We'll investigate whether we can fix this in a patch or minor release.

**Comment by vkarpov15** [comment]
I took a closer look and making this change by default would be a bit too much for a minor or patch release. But we added a new `useProjection` option for 5.10 that will hide `select: false` fields in `toObject()` and `toJSON()` output:

```javascript
doc.toObject({ useProjection: true });
```

Or, to enable it at a schema level:

```javascript
new Schema({ ... }, { toObject: { useProjection: true }, toJSON: { useProjection: true } });
```

Or, to enable it globally (https://thecodebarbarian.com/whats-new-in-mongoose-53-orfail-and-global-toobject):

```javascript
const mongoose = require('mongoose');

mongoose.set('toObject', { useProjection: true });
mongoose.set('toJSON', { useProjection: true });
```

**Comment by js-kyle** [comment]
Awesome, thanks @vkarpov15
