### ISSUE TITLE
Problems returning query in async/await related to cursors

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9119]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
In async/await functions when you return a *thenable* object the result is a transitive promise, your queries are *thenable* with cursor property function, so if I return a query in asyc/await it's impossible to catch the cursor.
**If the current behavior is a bug, please provide the steps to reproduce.**

```js
"use strict";
const mongoose = require("mongoose");
const {Schema, model} = mongoose;
async function main() {
  await mongoose.connect("mongodb://localhost/test", {useNewUrlParser: true, useUnifiedTopology: true});
  const test = new Schema({
    a: Number,
  });
  test.static({
    async parseQuery(query) {
      //assume some async operations
      return query;
    },
    async getQuery(query) {
      const localQuery = await this.parseQuery(query);
      return this.find(localQuery);
    },
  });
  let Test = model("Test", test);
  await Test.create([{a: 1}, {a: 2}, {a: 3}]);
  const query = Test.getQuery({a: {$gt: 1}});
  console.assert(typeof query.then === "function", "query.then doesn't exists");
  console.assert(typeof query.cursor === "function", "query.cursor doesn't exists");
}
main();
```
**What is the expected behavior?**
Be able to use async/await functions and use ```cursor``` function.

Obviously it's a simplified example, my real code wraps ```res.json``` in *express.js* to redefine how to parse the argument so in some *other place* the function can be invoked with a promise, an object with promises properties, a stream, etc...

Maybe a thenable wrapper that forces the ```exec``` function after resolve, for now when I need to return a object with cursor capabilities I've to delete the ```then``` function 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.9.18
node: 14.3.0
mongo: 4.2.7

**Comment by vkarpov15** [comment]
This is by design so you can do `await Test.find()`. Two workarounds:

1) `return { query }` as opposed to `return query`

2) Pass the query as a parameter to `parseQuery()`, `getQuery()`, etc. and rely on those functions to modify `query`. `const query = Test.find(); await parseQuery(query);`

**Comment by chumager** [comment]
Surely wrapping inside an object will break the thenable chain, but then I'll not be able to parse the result in case of a cursor, as my parser is generic. I had to move the cursor return to the first stage in the chain so the promise returned is a cursor.

Either way thanks for the ideas.

Regards.
