### ISSUE TITLE
Mongoose populate not populating an array

### ISSUE THREAD

**Issue by sundarboss** [Automattic/mongoose#9120]
I am having an issue where my mongoose query does not populate an array correctly.
I am having two models namely Thread and Reply. A thread contains several details along with a list of replies which refers to the Reply model. The Reply model has a Thread field which indicates to which Thread the Reply belongs.

Below is my Thread Schema:
var threadSchema = new Schema({
    _id: Schema.Types.ObjectId,
    board: {type: String, required: true},
    text: String,
    delete_password: String,
    created_on: Date,
    bumped_on: Date,
    reported: Boolean,
    replies: [{ type: Schema.Types.ObjectId, ref: 'Reply' }]
  });

Below is my Reply Schema:
var replySchema = new Schema({
    thread: { type: Schema.Types.ObjectId, ref: 'Thread' },
    text: String,
    delete_password: String,
    created_on: Date,
    reported: Boolean
  });

var Thread = mongoose.model('Thread', threadSchema);
  
  var Reply = mongoose.model('Reply', replySchema);

Below is my code populate query that does not populate the record correctly.
app.route('/api/replies/:board')
    .get(function(req, res) {
      var board = req.params.board;
      var threadId = req.query.thread_id;
      Thread.findById(threadId)
            .populate({'replies'})
            .select({ reported: 0, delete_password: 0 })
            .exec(function(err, data) {
             if (err) return console.error(err);
             Reply.findOne({thread: threadId}, function(err, rep) {
               if (err) return console.log(err)
               console.log(rep);
               console.log(data.replies);
               res.json(data);
             })
             
      })
    })

In the above query, the data.replies must be an array of objects. But I am getting an empty array. But when I query the Reply model separately, I am getting the data correctly. Any help on this will be greatly appreciated. Thanks

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
You have a typo, instead of `.populate({'replies'})` try `.populate('replies')`.

**Comment by sundarboss** [comment]
Thanks Hafez, I resolved the issue. The issue was I never pushed the replies data into the repies array in thread model. Now it works.

**Comment by AbdelrahmanHafez** [comment]
Happy to help 👍
