### ISSUE TITLE
Namespace '".../mongodb/index"' has no exported member 'OptionalId'.

### ISSUE THREAD

**Issue by dondish** [Automattic/mongoose#9126]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Mongoose doesn't build in the latest version of TypeScript and Mongoose.
```
$ .../node_modules/.bin/tsc --pretty
node_modules/@types/mongoose/index.d.ts:191:17 - error TS2694: Namespace '".../node_modules/@types/mongodb/index"' has no exported member 'OptionalId'.

191       ? mongodb.OptionalId<CreateDocumentDefinition<D> & { _id: TId }>
                    ~~~~~~~~~~
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Update to the latest version and build it with typescript.

**What is the expected behavior?**
For it to build normally.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v12.16.2
TypeScript: 3.9.5
mongoose: 5.9.18
@types/mongoose: 5.7.24
mongodb: 3.5.8
@types/mongodb: 3.3.11

**Comment by vkarpov15** [comment]
Sounds like an issue with your TypeScript bindings. Please open up an issue on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), they're the ones who maintain `@types/mongoose` and `@types/mongodb`. We don't currently have officially supported TypeScript bindings.

**Comment by dondish** [comment]
It seems to be an issue with your version of mongodb which uses older typings.
