### ISSUE TITLE
Problems reusing the same schema for both collection and subdocument

### ISSUE THREAD

**Issue by rubenvereecken** [Automattic/mongoose#9128]
I'm mainly here to ask a question. I don't think this is a bug, just unexpected.

**What is the current behavior?**

I've got a schema `EventSchema`. I have Meetups and meetups have events. Now, I decided to go the denormalised route and have meetups _contain_ event documents for quicker reading and better/easier indexing. Aside from that, events also live in their own collection as a point of reference. So now Events live in two places: as a subdocument in a Meetup, and as its own collection/mongoose model. The problem is the indexes on Events. All indexes I've defined on the EventSchema appear to have been been taken up by the MeetupSchema. This is especially problematic because an Event is optional for a Meetup. Meaning two meetups can have no events, so they'll have `null` for all Event-related fields which tripped up the 'unique' index I'd defined on Events.

**What is the expected behavior?**

What I expected or what I want is the following. The indexes I've defined on the EventSchema works for the `events` collection. They do not come into play for Meetups. If I want Event-based indexes on my Meetups, I can define the indexes on my Meetups. I thought this was the default behaviour and it turns out it isn't. I don't really see how the current behaviour is very useful. It's a bit dangerous to have the logic spread out so much.

So my question: Is this a bug? Probably not. If not, how do I circumvent this? Can I achieve my desired behaviour somehow, turn off Event-based indexes for Meetups but still keep them on the `events` collection?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- node.js @ v12.16.2
- mongoose@5.9.16
- mongodb @ 4.2.6
- typegoose

**Comment by vkarpov15** [comment]
You can disable the schema-level `autoIndex` option on your `EventSchema` just for meetups as shown below:

```javascript
const eventSchema = require('./eventSchema').clone();
// Disable automatic indexing on a clone of `eventSchema`
eventSchema.options.autoIndex = false;

const meetupSchema = new mongoose.Schema({
  event: eventSchema
});

// You can then manually add indexes on `event` on the `meetupSchema`
meetupSchema.index({ 'event.eventProp': 1 }, { unique: true });
```

**Comment by rubenvereecken** [comment]
Thanks @vkarpov15 that would be a way to work around it. This would require me to manually set up indexes on events... not terrible. I'll have a look whether I can get this working with typegoose and I'll update the issue.

**Comment by AChangXD** [comment]
@rubenvereecken Running into the same issue with typegoose at the moment, it's tripping up a lot of unique indexes I set. What was your solution with typegoose?

**Comment by rubenvereecken** [comment]
@AChangXD exactly what @vkarpov15 recommended. Looked a bit funny but worked fine.

**Comment by AChangXD** [comment]
> @AChangXD exactly what @vkarpov15 recommended. Looked a bit funny but worked fine.

I ended up using excludeIndexes true:
`@Property({ required: true, default: [], excludeIndexes: true })
  bookableUsers: User[];`

And to index the _id of the subdoc, I did 
`@Index({ 'bookableUsers._id': 1 })`
on the parent class.

Idk if excludeIndexes was something that was added recently but it might be a better approach using decorators.
