### ISSUE TITLE
Mongoose can't add a 2dsphere index 

### ISSUE THREAD

**Issue by DoneDeal0** [Automattic/mongoose#9130]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have a schema, with a location field. A `2dsphere` index is added to it. When performing an `aggregation`, I receive the following error: 

[MongoError: $geoNear requires a 2d or 2dsphere index, but none were found](url)

I have read the other issues, and made sure to add `Shema.init() `before performing my aggregation. 

Here is my schema:
```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const userSchema = new Schema(
  {
    username: { type: String, required: true, unique: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    age: {type: Number},
    location: {
      type: { type: String, enum: ["Point"] },
      coordinates: { type: [Number] },
    },
  },
  { timestamps: true }
);

userSchema.index({ age: 1, location: "2dsphere"});

module.exports = mongoose.model("User", userSchema);
```

Here is my aggregation:
```
 User.aggregate([
        {$geoNear: {
            near: { type: "Point", coordinates: location },
            distanceField: "dist.calculated",
            maxDistance,
          }},
        {$match: {
            age: { $gte: minAge, $lte: maxAge },
          }},
      ]).exec((_, data) => res.json({ data })
      );
```

Here is the Mongoose initialization:
```
// Connect to MongoDB and start server
mongoose
  .set("useFindAndModify", false)
  .connect(process.env.MONGODB, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
    autoIndex: false,
  })
  .then(() =>
    server.listen(process.env.PORT, () =>
      console.log(`server is listening on ${process.env.PORT}!`)
    )
  )
  .catch((err) => console.log("error", err));
```

I've read the doc several times, I don't see where I have made a mistake. Any help would be greatly appreciated, thanks!

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: ^5.9.18
node: 12.7.0

**Comment by Neelaka-Rupun** [comment]
Hi what was happen to this ticket?

**Comment by Neelaka-Rupun** [comment]
i'm having the same issue

**Comment by vkarpov15** [comment]
@Neelaka-Rupun please open a new issue and follow the issue template.
