### ISSUE TITLE
mongoose.createConnection(DB_URL, {useUnifiedTopology: true}) produces a deprecationwarning.

### ISSUE THREAD

**Issue by kallezz** [Automattic/mongoose#9135]
**Do you want to request a *feature* or report a *bug*?**
a bug?

**What is the current behavior?**
createConnection() with useUnifiedTopology: true produces a deprecationwarning that tells me to set useUnifiedTopology: true.

**If the current behavior is a bug, please provide the steps to reproduce.**

CODE:
mongoose.createConnection(config.dev.DB_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true
});

CONSOLE:
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**What is the expected behavior?**
No deprecationwarning.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 10.16.3
Mongoose 5.9.2
MongoDB 4.2.0

**Comment by vkarpov15** [comment]
The below script doesn't print any deprecation warning. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.createConnection('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  console.log('Done');
  process.exit(0);
}

```

I'd suggest looking into:

1) Are you calling `mongoose.connect()` or `mongoose.createConnection()` anywhere else in your code?
2) Are you using any other npm modules that use MongoDB, like connect-mongo or connect-mongodb-session? Try running `npm list | grep "mongo"`.

**Comment by kallezz** [comment]
Here is the exact code, used for gfs file upload that produces the deprecationwarning for me.
I have connect() in my index file, but I couldn't get that to work with gfs so I had to use createConnection here. The code works fine but I'm just wondering why the deprecationwarning is happening.

`const mdbc = mongoose.createConnection(config.dev.DB_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true
});

let gfs;
mdbc.once("open", () => {
    // Init stream
    gfs = new mongoose.mongo.GridFSBucket(mdbc.db, {
        bucketName: "fs"
    });
});

// Storage
const storage = new gridFsStorage({
    url: config.dev.DB_URL,
    file: (req, file) => {
        return new Promise((resolve, reject) => {
            crypto.randomBytes(16, (err, buf) => {
                if (err) {
                    return reject(err);
                }
                const filename = buf.toString('hex') + path.extname(file.originalname);
                const fileInfo = {
                    filename: filename,
                    originalname: file.originalname
                };
                resolve(fileInfo);
            });
        });
    }
});

const acceptedFileTypes = [
    'image/jpeg',
    'image/png',
    'image/tiff',
    'image/gif',
    'application/pdf',
    'application/zip'
];

const fileFilter = (req, file, cb) => {
    if (acceptedFileTypes.includes(file.mimetype)) {
        cb(null, true);
    } else {
        cb(null, false);
    }
};

const upload = multer({
    storage,
    limits: {
        fileSize: 1024 * 1024 * 32
    },
    fileFilter
});`

**Comment by lineus** [comment]
@kallezz it's not clear where `gridFsStorage` comes from in your example, but the deprecation warning is probably coming from that connection to the db. Do you have the option to pass mongodb connection options into `gridFsStorage` ?

**Comment by kallezz** [comment]
> @kallezz it's not clear where `gridFsStorage` comes from in your example, but the deprecation warning is probably coming from that connection to the db. Do you have the option to pass mongodb connection options into `gridFsStorage` ?

Oh damn thats where it came from, the package in question was multer-gridfs-storage and it did indeed have the option to pass mongo options object into it. Thanks.
