### ISSUE TITLE
it doesnt work from me do we have to import any module?

### ISSUE THREAD

**Issue by rohan2734** [Automattic/mongoose#9136]
mongoose
  .connect(process.env.MONGO_URI, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
  })
  .then(() => console.log('DB Connected!'))
  .catch(err => {
    console.log(`DB Connection Error: ${err.message}`);
  });

_Originally posted by @TREagans in https://github.com/Automattic/mongoose/issues/8156#issuecomment-532747439_

**Comment by vkarpov15** [comment]
Please open a new issue and follow the issue template. Also, please describe what "it doesn't work" mean - do you get some sort of error message?
