### ISSUE TITLE
'this' does not refer to document while using 'remove' pre-hook as a document middleware.

### ISSUE THREAD

**Issue by temanisparsh** [Automattic/mongoose#9138]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
While using Document Middleware, ```this``` should refer to the document(As mentioned [here](https://mongoosejs.com/docs/middleware.html#types-of-middleware)) but that isn't the case with ```Pre-hook remove```.

**If the current behavior is a bug, please provide the steps to reproduce.**

Example:
```
const mongoose = require('mongoose');
const Value = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
});

Value.pre('remove', {query: false, document: true}, () => {
  console.log(this);
});

module.exports = mongoose.model('Value', Value);

```
Output: ```{}```

**What is the expected behavior?**
The output should be the document itself,
Example: 
```
{
        "_id": "5ee91d944bf113286bcaf532",
        "title": "value0",
        "__v": 0
}
```
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
Node.js: v10.20.1
Mongoose: v5.9.18
MongoDB: v4.2.5
```

**Comment by AbdelrahmanHafez** [comment]
use a function declaration instead of an arrow function.

```js
Value.pre('remove', {query: false, document: true}, () => {
  console.log(this); // does not work
});

Value.pre('remove', {query: false, document: true}, function() {
  console.log(this); // works
});
```

**Comment by temanisparsh** [comment]
Thanks, @AbdelrahmanHafez . 
Using the function declaration works fine.
