### ISSUE TITLE
Difficulties to query nested arrays with multiple itens

### ISSUE THREAD

**Issue by Girum** [Automattic/mongoose#9141]
Hi!

I`ve modeled a document to be:

```
let UserSchema = new Schema({
    name: { type: String, required: true, max: 50, unique: true },
    email: {type: String, required: true, max: 50, unique: true},
    password: {type: String, required: true, max: 20},
    monitoringProject: [
        {
            projectName: { type: String, required: true, max: 30},
            token: { type: String, required: true},
            dispositives: [
                {
                    name: { type: String, required: true, max: 15},
                    value: { type: String, required: true},
                    token: { type: String}
                }
            ]
        }
    ],
    controlProject: [
        {
            projectName: { type: String, required: true, max: 30},
            token: { type: String, required: true},
            dispositives: [
                {
                    name: { type: String, required: true, max: 15},
                    value: { type: String, required: true},
                    token: { type: String}
                }
            ]
        }
    ]
});
```
In the monitoringProject, for example, I can log too many different projects, and, to each project, I can log too many dispositives. So, I have nested arrays. In other project, where I have just one project, and many dispositives, I can list them and search for just one dispositive. But in this case, like this:

`[
    {
        "_id": "5ee18ece1ea5af75bae55f91",
        "monitoringProject": [
            {
                "dispositives": [
                    {
                        "_id": "5ee18ef31ea5af75bae55f9c",
                        "name": "Dispositivo 1",
                        "token": "$2b$15$NntmY9ihNZ7R1Vg1WMtmzOSjlfCoKIuHLofF6g5tKXA57WLLc2At2"
                    },
                    {
                        "_id": "5ee18ef81ea5af75bae55f9e",
                        "name": "Dispositivo 2",
                        "token": "$2b$15$OZB7HbDLvonsv6A71ozW7.yVY2vJOipTCj0AH7XzoafQwwDho.jpm"
                    },
                    {
                        "_id": "5ee18efc1ea5af75bae55fa0",
                        "name": "Dispositivo 3",
                        "token": "$2b$15$0hpDzNeTO2qJzBVyAHc/UesrnIRi/YpeAlpCLewNhmfl6fe3SEN0i"
                    },
                    {
                        "_id": "5ee2278d0754817853134bf3",
                        "name": "Dispositivo 4",
                        "token": "$2b$15$ldC5/CyxITPJGUvtXJ.2S.D6a3FBftg6ctQeS4ne/9xpMP5PPiszK"
                    },
                    {
                        "_id": "5ee2288956fc4c7870044395",
                        "name": "Dispositivo 6",
                        "token": "$2b$15$3rJt.gXEi/gALvrwxVUsWuwF2RUcBmZcoFOQeXwF45ZuKQrB3AGHG"
                    },
                    {
                        "_id": "5ee6d23d1756b7a8384bcff0",
                        "name": "Dispositivo 7",
                        "token": "$2b$15$C3I9STKJpf9i/7hzhvHEs.IizXpOEmgRTD3hd7ZSdcvATb73Z0zNC"
                    }
                ],
                "_id": "5ee18ede1ea5af75bae55f94",
                "projectName": "Projeto 2",
                "token": "$2b$15$xaytMbMnGd3BMAGapX8nn.imvkQKetqx0OIlUUyP3gCxlKz/G6DiG"
            }
        ]
    }
]`

I can only list all the Dispositives. I want to return just, for example, "Dispositivo 2".

I used to querys:

`    await User.find({ email: req.body.email, monitoringProject: { $elemMatch: { token: req.body.projecttoken, dispositives: { $elemMatch: { token: req.body.dispositivetoken } } } } }, { "monitoringProject.$.dispositives": 1} )
`

or

`    await User.find({ email: req.body.email, 'monitoringProject.token': req.body.projecttoken, 'monitoringProject.dispositives.token': req.body.dispositivetoken}, { 'monitoringProject.dispositives.$': 1 })
`

Using find or findOne. How can I return just the document I want? I tried so many different ways, but with no lucky.

**Comment by vkarpov15** [comment]
Unfortunately you can't project underneath nested arrays using `$elemMatch`. You have two alternatives:

1) Filter for the subdoc in Node.js:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = Schema({
    arr1: [{
      arr2: [{ test1: String, test2: String }]
    }]
  });
  const Model = mongoose.model('Test', schema);

  await Model.create({
    arr1: [
      { arr2: [{ test1: 'foo', test2: 'bar' }, { test1: 'bar', test2: 'bar' }] },
      { arr2: [{ test1: 'baz', test2: 'baz' }] }
    ]
  });

  const doc = await Model.findOne({ 'arr1.arr2.test1': 'foo' });
  const subdoc = doc.arr1.
    flatMap(subdoc => subdoc.arr2).
    find(doc => doc.test1 === 'foo');
  console.log(subdoc); // { _id: 5efba1d2ea4c88189ec99166, test1: 'foo', test2: 'bar' }
} 
```

2) Use the aggregation framework as described in [this SO post](https://stackoverflow.com/questions/28982285/mongodb-projection-of-nested-arrays).

I recommend (1) because it is much easier, but you can do (2) if you have a good reason to.
