### ISSUE TITLE
null should not be an allowed value on Primitive types.

### ISSUE THREAD

**Issue by sgpinkus** [Automattic/mongoose#9146]
**Do you want to request a *feature* or report a *bug*?**
It's either a bug or a request for a option to allow us to not allow null values for primitives or at least cast them since `null` is not a legal Boolean, Number, or String. null's type is actually object in Node:

```
> typeof null === 'object'
true
```

[ECMAScript spec](https://www.ecma-international.org/ecma-262/6.0/index.html#sec-null-value) actually says its type is `Null` but states `null` is a:

> primitive value that represents the intentional absence of any *object* value

not  the intentional absence of a primitive or any other type. It's like a null pointer in other languages. Allowing null in a property explicitly declared to to have a type (other than Object or Mixed) sort of degrades the meaningfulness of that declaration. Means more work for client to account for edge cases.

Secondly `null` actually has reasonable casts for primitives, so it confusing to not cast null while other mismatched types that have reasonable casts will be cast by Mongoose:

```
> Boolean(null)
false
> Number(null)
0
> String(null)
'null'
```
---

I realize you can use `required: true` to force non null, but 1. You have to make sure you do this for every primitive type which is a lot of work. 2. It's not exactly equivalent to not allowing null because you can not allow null while still allowing the value to be undefined.

**What is the current behavior?**
You can set property declared to be of type Boolean, Number String to null:

```
var mongoose = require('mongoose');

async function main() {
  await mongoose.connect('mongodb://localhost:27019/test', {});
  await mongoose.connection.dropDatabase();
  var TestSchema = new mongoose.Schema({
    a: { type: Boolean, default: false },
    b: { type: Number, default: 0 },
    c: { type: String, default: '' },
  });
  var Test = mongoose.model('Test', TestSchema);
  var myTest = await new Test({ a: null, b: null, c: null });
  await myTest.save();
  console.log(myTest)
}
main()
  .then(() => process.exit())
  .catch((e) => { console.error(e); process.exit(); })
```
Gives:
```
{ a: null, b: null, c: null, _id: 5eeaef8d8885f90cf6088e5f, __v: 0 }
```

**What is the expected behavior?**
See top.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
> process.version
'v12.18.0'
> mongoose.version
'5.9.17'
```

**Comment by vkarpov15** [comment]
For Mongoose, this is by design. Node allows storing `undefined` as a key, but MongoDB doesn't: the `undefined` BSON type is deprecated, and the MongoDB node driver implicitly converts `undefined` to `null`. So our answer to that is to treat [nullish values](https://masteringjs.io/tutorials/fundamentals/falsy#nullish-values) as equivalent.

To set `required` to true by default, use [global schematype configurations](https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration). For example, the below one-liner makes all numbers `required` by default.

```javascript
mongoose.Schema.Types.Number.set('required', true);
```

**Comment by sgpinkus** [comment]
OK, I see. Ugh.

Global schematype conf looks very useful here. Didn't know about it. Thanks for the links. Not sure that `mongoose.Schema.Types.Number.set('required', true);` solves the issue exactly but will look into other global conf, may a custom type.

**Comment by vkarpov15** [comment]
I'd recommend avoiding custom types unless you absolutely need to. Setting `required` globally should be enough to disallow `null` for all types.

Another possibility is to use custom casting: https://mongoosejs.com/docs/tutorials/custom-casting.html

**Comment by sgpinkus** [comment]
>  Setting required globally should be enough to disallow null for all types.

But with the consequence that the value is required. Can't use this to get not null and not required. i.e. if has a value the value is a real Boolean.

> Another possibility is to use custom casting: https://mongoosejs.com/docs/tutorials/custom-casting.html

@vkarpov15 actually cast seems to be bypassed for `null`:

```
const mongoose = require('mongoose');
const original = mongoose.Schema.Types.Boolean.cast();
mongoose.Schema.Types.Boolean.cast(v => {
  console.log(`Casting "${v}" of type ${typeof v}`);
  if (v === '') {
    return false;
  } else if (v === null) {
    return false;
  }
  return original(v);
});

const schema = new mongoose.Schema({
  a: Boolean,
  b: Boolean,
}, { _id: false });

const Model = mongoose.model('testing', schema);
const doc = new Model({ a: null, b: '' });
console.log(doc.a, doc.b);
doc.validateSync();
doc.b = null;
console.log(doc.a, doc.b);
doc.validateSync();
```

Gives:

```
Casting "" of type string
null false
null null
```
