### ISSUE TITLE
Compound indexes on parent + embedded discriminators

### ISSUE THREAD

**Issue by andreialecu** [Automattic/mongoose#9150]
**Do you want to request a *feature* or report a *bug*?**

Feature request I think.

**What is the current behavior?**

Assume the following sample schema:

```js
var eventSchema = new Schema({ message: String },
  { discriminatorKey: 'kind', _id: false });

var batchSchema = new Schema({ events: [eventSchema], user: String });

var docArray = batchSchema.path('events');

var clickedSchema = new Schema({
  element: {
    type: String,
    required: true
  }
}, { _id: false });

var Clicked = docArray.discriminator('Clicked', clickedSchema);

var Purchased = docArray.discriminator('Purchased', new Schema({
  product: {
    type: String,
    required: true
  }
}, { _id: false }));

var Batch = db.model('EventBatch', batchSchema);

```

It seems to be possible to add indexes to the embedded discriminator, and mongoose already nests them.

Say I want to add a compound unique index on `{ "user": 1, "element": 1 }` using `Clicked.index()`. Since `user` is on the root, and `element` is on the embedded discriminator, I don't see how to do this.

Calling `Clicked.index({ "user": 1, "element": 1 })` results in an index like `{ "events.user": 1, "events.element": 1 }`.

**What is the expected behavior?**

Is there any way to prevent it from applying nesting logic from certain keys? 

Unless I'm missing some more obvious way, a potential solution would be to introduce some sort of option that can be passed to the second parameter of `index`. Example:

```js
Clicked.index({ "user": 1, "element": 1 }, { 
	transformIndexName: 
		(transformedName, originalName) => 
			batchSchema.path(originalName) ? originalName : transformedName 
	} 
)
```

In this example, there would be a `transformIndexName` optional function that could be passed, which is called with `("events.user", "user") => result`, and the result of the function is used for the resulting index. 

That way there's a hook into how indexes are created, and one could manually override it. Developers would be responsible to ensure proper index names are generated.

**Comment by andreialecu** [comment]
A workaround is to call `Batch.index({ user: 1, "events.element": 1 })` instead, but that is less than ideal in certain cases. The parent needs knowledge of all embedded discriminators.

**Comment by andreialecu** [comment]
Apologies if this seems ridiculous, but another idea might be to have a way to define the index like this:

```js
Clicked.index({ batchSchema.indexToken("user"): 1, "element": 1 }
```

Where `indexToken` (better name needed) returns some sort of internal identifier that can be detected and transformed during index creation to point to the proper field on `batchSchema` in this case.

**Comment by vkarpov15** [comment]
Right now the only workaround we support is setting `excludeIndexes` on the nested schema to opt out of index builds, and then define indexes on the top-level schema:

```
const nestedSchema = mongoose.Schema({
    name: { type: String, index: true }
  }, { excludeIndexes: true }); // Will ignore all indexes on this schema
  const Model = mongoose.model('Test', mongoose.Schema({
    nested: nestedSchema,
    top: { type: String, index: true }
  }));
```

**Comment by vkarpov15** [comment]
What sort of index are you looking to build? I'm hard pressed to think of a case where you would want to have a completely different index given an embedded schema.

**Comment by andreialecu** [comment]
I have a Parent collection.

The Parent has an `invites` path which is an array of two possible embedded discriminated types.

One of the types has `team` in it which needs to be unique per matchday. The other does not have this property.

The index is supposed to be an unique index for`{ _id: 1, "invites.team": 1 }`

`_id` from parent and `team` from the discriminated embedded doc.

There seems to be no way to consistently declare this. The workaround in the original post works in this simple case, but a proper way to define it would be nice.

**Comment by vkarpov15** [comment]
Would a [partial index](https://docs.mongodb.com/manual/core/index-partial/) work here?

**Comment by andreialecu** [comment]
Yes. In addition to the above I also have a partial index requirement for this, in practice, which probably comes with its own set of problems regarding namespacing.

**Comment by andreialecu** [comment]
For more context:

Currently I have the below indexes defined, and mongoose creates them properly, but it's less than ideal, as I need to know all index types and their "namespacing" from the parent.

Note that the base `invites` schema type does not have `invites.user` (discriminator sub-type A has it) or `invites.players` or `invites.team` directly (discriminator sub-type B have them). 

```
  // unique index for embedded discriminator type A
  { _id: 1, "invites.user": 1 },
  {
    unique: true,
    partialFilterExpression: { "invites.user": { $exists: 1 } },
  },
```

```
  // unique index for embedded discriminator type B
  { _id: 1, "invites.team": 1, "invites.players.user": 1 },
  {
    unique: true,
    partialFilterExpression: { "invites.players.user": { $exists: 1 } },
  },
```

Hopefully this clears things up a bit.

**Comment by andreialecu** [comment]
Apparently the approach above doesn't work to enforce uniqueness because of a bug in MongoDB: 
https://jira.mongodb.org/browse/SERVER-1068

Some workarounds available here: https://stackoverflow.com/questions/10383143/how-to-ensure-unique-item-in-an-array-based-on-specific-fields-mongodb

I guess the feature request still stands though, even though I may need to move away from unique indexes in this particular scenario. There may be others where creating such an index is required (and especially if the bug above is fixed)

**Comment by andreialecu** [comment]
Actually, I can still use the indexes, even if the `unique` part doesn't work. They are still helpful in optimizing the query.

**Comment by vkarpov15** [comment]
I took a closer look and I'm afraid what you're trying to do isn't possible with MongoDB. You would need to make `invites` a separate model in order to enforce uniqueness on a key that's in one embedded discriminator schema but not the other.

**Comment by andreialecu** [comment]
@vkarpov15 the index I mentioned is definitely possible to add and is still a requirement, **even if it's not unique**, but mongoose doesn't allow you to add it properly except via workarounds I mentioned.

The only reason enforcing uniqueness in the particular scenario I linked doesn't work is due to the mongodb bug I linked. But that only affects the same array in the **same** document.

**However* it does enforce uniqueness properly across multiple documents. Example:

```
  { "someParentValue": 1, "invites.user": 1 },
  {
    unique: true,
    partialFilterExpression: { "invites.user": { $exists: 1 } },
  },
```

The above index does prevent **two separate documents** to have the same `user` value inside the `invites` array, and the same `someParentValue` (from the parent).

So there are many cases where this is still needed to be supported.

And `partialFilterExpression` allows specifying indexes that are applied only if certain paths exists (such as ones that may only be on a certain discriminator)

**Comment by vkarpov15** [comment]
@andreialecu oh ok, that's my mistake, I guess I assumed that I knew how it worked without actually trying it.

Based on your issue description, it sounds like you're looking for the [mongoose-unique-array plugin](https://www.npmjs.com/package/mongoose-unique-array)

**Comment by andreialecu** [comment]
Thanks, but I got around it by doing something like this:

```
await this.model.findOneAndUpdate(
  {
    _id: matchday._id,
    "invites.team": { $ne: new ObjectId(invite.team) },
  },
  {
    $push: { invites: invite },
  },
);
```

However, I still would like to use the index, just to optimize this query. 

A way to properly define such indexes is probably still needed.

**Comment by andreialecu** [comment]
Any particular reason this is `won't fix`?

**Comment by vkarpov15** [comment]
Because unfortunately MongoDB doesn't support such indexes currently. When you have a unique index on an array, MongoDB enforces that multiple documents can't have duplicate values within the array, but an individual document can have duplicate values within the array. That's why we have the mongoose-unique-array plugin.

**Comment by andreialecu** [comment]
I don't understand. The indexes **are** supported by MongoDB, just not by mongoose. The `unique` bug is not important, it's only a minor part of this.

Again, these indexes are proper MongoDB indexes:
```
  { _id: 1, "invites.team": 1, "invites.players.user": 1 },
  {
    unique: true,
    partialFilterExpression: { "invites.players.user": { $exists: 1 } },
  },
```

I can create them via the Parent schema with mongoose, but not from the individual embedded discriminator schema.

I'll add a repro script soon, perhaps that makes it clearer.

**Comment by andreialecu** [comment]
Alright, here's a small repro:

```ts
const mongoose = require('mongoose');
mongoose.set('debug', true);

const { Schema } = mongoose;

(async () => {
  const dbUri = 'mongodb://localhost:27017/test';
  const db = await mongoose.connect(dbUri, { useNewUrlParser: true });
  await db.connection.dropDatabase();

  const schema = new Schema({ name: String });
  const model = mongoose.model('item', schema);

  var eventSchema = new Schema({ message: String },
    { discriminatorKey: 'kind', _id: false });
  
  var batchSchema = new Schema({ events: [eventSchema], user: String });
  
  var docArray = batchSchema.path('events');
  
  var clickedSchema = new Schema({
    element: {
      type: String,
      required: true
    }
  }, { _id: false });
  
  var Clicked = docArray.discriminator('Clicked', clickedSchema);

  // this works, but `element` is part of Clicked, so it feels wrong to define on `eventSchema`
  // and in certain cases it can be hard to modify the parent index
  eventSchema.index({ message: 1, "events.element": 1 });

  // no way to get to `message` from the parent here:
  clickedSchema.index({ "$parent.message": 1, element: 1 })
  
  console.log("event indexes", eventSchema.indexes());
  console.log("clicked indexes", clickedSchema.indexes());

  await db.disconnect();
  process.exit(0);
})();
```

If there's no way to support creating such indexes other than from the parent, that's ok. But it might be a good idea to document it as such, as a caveat.

**Comment by andreialecu** [comment]
Here's another example that shows that the unique index does work:

```ts
const mongoose = require('mongoose');
mongoose.set('debug', true);

const { Schema } = mongoose;

(async () => {
  const dbUri = 'mongodb://localhost:27017/test';
  const db = await mongoose.connect(dbUri, { useNewUrlParser: true });
  await db.connection.dropDatabase();

  var eventSchema = new Schema({ message: String },
    { discriminatorKey: 'kind', _id: false });
  
  var batchSchema = new Schema({ events: [eventSchema], user: String });
  
  var docArray = batchSchema.path('events');
  
  var clickedSchema = new Schema({
    element: {
      type: String,
      required: true
    }
  }, { _id: false });
  
  var Clicked = docArray.discriminator('Clicked', clickedSchema);

  batchSchema.index({ user: 1, "events.message": 1, "events.element": 1 }, { unique: true });

  const model = mongoose.model('event', batchSchema);
  await model.createIndexes();

  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });
  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });
  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });
  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });
  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });
  await model.create({ user: "foo", events: [{message: "foo", kind: "Clicked", element: "bar" }] });


  await db.disconnect();
  process.exit(0);
})();
```

Output:

```
UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: test.events index: user_1_events.message_1_events.element_1 dup key: { user: "foo", events.message: "foo", events.element: "bar" }
```

**Comment by andreialecu** [comment]
Further clarification:

```
  clickedSchema.index({ message: 1, element: 1 }, { unique: true });
```

Properly creates:
```
{
    "events.message" : 1,
    "events.element" : 1
}
```

But the requirement is:

```
{
    "user": 1, // how to add this?
    "events.message" : 1,
    "events.element" : 1
}
```

Workaround is to call `batchSchema.index({ user: 1, "events.message": 1, "events.element": 1 }, { unique: true });` instead.

**Comment by vkarpov15** [comment]
@andreialecu thanks for clarifying, that makes more sense. Your workaround `batchSchema.index({ user: 1, "events.message": 1, "events.element": 1 }, { unique: true });` is the way to go. IMO the most robust way to define a multi-schema index is using `.index()` on the parent schema, exactly how you did it. Defining a multi-schema index on a child schema seems messier.
