### ISSUE TITLE
No easy way to cascade delete documents

### ISSUE THREAD

**Issue by a-koka** [Automattic/mongoose#9152]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
`pre` hooks are not designed to address cascade delete use cases.

**If the current behavior is a bug, please provide the steps to reproduce.**
Consider the following use case.
```
// Consider any simple User schema. Each user can have many UserLink(s)

const _preDelete = async function () {
  console.log('User.preDelete', this._id);
  await Promise.all([
    UserLink.deleteMany({ user: this._id }),
  ]);
};

UserSchema.pre('deleteOne', { document: true, query: true }, _preDelete);
UserSchema.pre('deleteMany', { document: true, query: true }, _preDelete);


// This will fire the pre hook with no id so its impossible to perform cascade deletes
User.deleteOne({email: 'abc@test.com'})

// This will fire the pre hook with the correct id but further cascades won't work
// as they use queries. One has to manually find and delete each document.
// What the point of query: true in the pre hook?
const user  = await User.findOne({email: 'abc@test.com'});
user.deleteOne();
```

**What is the expected behavior?**
`pre` hooks should allow an easy way to cascade delete all related documents.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 11.15.0
MongoDB 4.2.1
Mongoose 5.9.19

**Comment by vkarpov15** [comment]
@a-koka you would need to load the documents yourself in your middleware:

```javascript
UserSchema.pre('deleteOne', { document: false, query: true }, async function() {
  const doc = await this.model.findOne(this.getFilter());
  await UserLink.deleteMany({ user: doc._id });
});
```

**Comment by podsevalovAlex** [comment]
In addition to previous comment:
In case of plural remove:

`UserSchema.pre(
  "deleteMany",
  { document: false, query: true },
  async function (next) {
    const docs = await this.model.find(this.getFilter());
    const users = docs.map((item) => item._id); 
    await UserLink.deleteMany({ user: { $in: users } });
    next();
  }
);`
