### ISSUE TITLE
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

### ISSUE THREAD

**Issue by JAMAL-BASHA** [Automattic/mongoose#9154]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @JAMAL-BASHA 

Check out our deprecation warnings guide: https://mongoosejs.com/docs/deprecations.html
