### ISSUE TITLE
Get POJO to be saved from toJSON or other parser.

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9155]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
when I call ```Doc.toJSON``` I can't get what will be saved if there is a setter in the Schema definition.
AFAIK in the documentation there is no option for that behavior.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To be able to get the *real* object that will be saved, so I can compare between a Doc and the lean object from DB.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
I'm not sure I understand the issue: Mongoose doesn't call setters when you `save()`. Can you please clarify with an example of where comparing a doc to an object from the db doesn't work?
