### ISSUE TITLE
 Hello, I  have some trouble here!

### ISSUE THREAD

**Issue by ibandim123** [Automattic/mongoose#9156]
"mongoose": "^5.9.19"

**Do you want to request a *feature* or report a *bug*?**
  Yes.
**What is the current behavior?**

DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
**If the current behavior is a bug, please provide the steps to reproduce.**

const mongoose = require('mongoose')//import mongoose
//begin app
const app = express() // execute function express

//begin o database
mongoose.connect('mongodb://localhost:27017/nodeapi', {useNewUrlParser: true})
======================================================

**What is the expected behavior?**
connect with database mongodb

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

 "mongoose": "^5.9.19"
 db version v4.2.8
node -v
v12.18.1

**Comment by AbdelrahmanHafez** [comment]
Welcome @ibandim123 

Check out our guide on how to fix all deprecation warnings: https://mongoosejs.com/docs/deprecations.html
