### ISSUE TITLE
mongoose model not populating refrence model array

### ISSUE THREAD

**Issue by yg-yash** [Automattic/mongoose#9158]
**Do you want to request a *feature* or report a *bug*?**
Bug but i am not sure

**What is the current behavior?**
.populate is returning empty array

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my post schema
const mongoose = require('mongoose');

const postSchema = new mongoose.Schema(
  {
    _id: mongoose.Schema.Types.ObjectId,
    caption: String,
    tags: {},
    hashtags: {},
    location: {},
    images: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'GFS',
        required: true,
      },
    ],
    comments: [
      {
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'Comment',
        required: true,
      },
    ],
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Post', postSchema);

And this is my comment schema
const mongoose = require('mongoose');

const commentSchema = new mongoose.Schema(
  {
    _id: mongoose.Schema.Types.ObjectId,
    text: {
      type: String,
      required: true,
    },
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    postId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Post',
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Comment', commentSchema);

i want to populate comments when i make a api call to fetch posts

controller:
exports.getPosts =async (req, res) => {
try{
 const posts = await Post.find()
      .populate('comments') .exec();
   res.status(200).json({ posts });
//its returing empty comments array 
}
} catch (error) {
res.status(500).json({message:"something went wrong'})
}
}

**What is the expected behavior?**
Should return the comments array

**Comment by AbdelrahmanHafez** [comment]
Welcome @yg-yash 

Can you modify the script below to reproduce the issue you're facing?

### 9158.js
```js
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const postSchema = new Schema({
    caption: String,
    tags: {},
    hashtags: {},
    location: {},
    images: [{ type: Schema.ObjectId, ref: 'GFS', required: true }],
    comments: [{ type: [Schema.ObjectId], ref: 'Comment', required: true }]
  });

  const Post = mongoose.model('Post', postSchema);

  const commentSchema = new Schema({ text: { type: String, required: true } });

  const Comment = mongoose.model('Comment', commentSchema);

  const comments = await Comment.create([
    { text: 'First comment' },
    { text: 'Second comment' }
  ]);

  const createdPost = await Post.create({ comments: [comments[0]._id, comments[1]._id] });

  const post = await Post.findOne({ _id: createdPost._id }).populate('comments').exec();

  assert.deepEqual(
    post.comments.map(comment => comment.text),
    ['First comment', 'Second comment']
  );

  console.log(`Mongoose version: ${mongoose.version}`);
  console.log('All assertions passed.');
}
```

### Output
```
Mongoose version: 5.9.19
All assertions passed.
```

**Comment by yg-yash** [comment]
> Welcome @yg-yash
> 
> Can you modify the script below to reproduce the issue you're facing?
> 
> ### 9158.js
> ```js
> const mongoose = require('mongoose');
> const { Schema } = mongoose;
> const assert = require('assert');
> 
> 
> run().catch(console.error);
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017/test', {
>     useNewUrlParser: true,
>     useUnifiedTopology: true
>   });
> 
>   await mongoose.connection.dropDatabase();
> 
>   const postSchema = new Schema({
>     caption: String,
>     tags: {},
>     hashtags: {},
>     location: {},
>     images: [{ type: Schema.ObjectId, ref: 'GFS', required: true }],
>     comments: [{ type: [Schema.ObjectId], ref: 'Comment', required: true }]
>   });
> 
>   const Post = mongoose.model('Post', postSchema);
> 
>   const commentSchema = new Schema({ text: { type: String, required: true } });
> 
>   const Comment = mongoose.model('Comment', commentSchema);
> 
>   const comments = await Comment.create([
>     { text: 'First comment' },
>     { text: 'Second comment' }
>   ]);
> 
>   const createdPost = await Post.create({ comments: [comments[0]._id, comments[1]._id] });
> 
>   const post = await Post.findOne({ _id: createdPost._id }).populate('comments').exec();
> 
>   assert.deepEqual(
>     post.comments.map(comment => comment.text),
>     ['First comment', 'Second comment']
>   );
> 
>   console.log(`Mongoose version: ${mongoose.version}`);
>   console.log('All assertions passed.');
> }
> ```
> 
> ### Output
> ```
> Mongoose version: 5.9.19
> All assertions passed.
> ```

Thanks,
I Figured it out
