### ISSUE TITLE
$gt/$lt cannot compare string in aggregate pipeline  

### ISSUE THREAD

**Issue by zwang759** [Automattic/mongoose#9159]
const ProfileSchema = new mongoose.Schema({
    user: {
        type: Schema.Types.ObjectId,
        index : true
    },
    following: [
        {
            user: {
                type: Schema.Types.ObjectId
            },
            date: {
                type: Date,
                default: Date.now
            }
        }
    ],
});

  const following = await Profile.aggregate([
            {$match: {user: mongoose.Types.ObjectId(req.query.userId)}},
            {$project: {
                following: {
                    $slice: [
                        {$filter: {
                            input: "$following",
                            as: "item",
                            cond: {$lt: ["$$item.date", ISOStringTimestamp]}
                        }},
                        2
                    ]
                }}
            }
        ]);
The above code does not work as expected, as it failed to compare the date which is saved as ISOString format. 

Instead I have to parse the date to decimal and then it works.

  const following = await Profile.aggregate([
            {$match: {user: mongoose.Types.ObjectId(req.query.userId)}},
            {$project: {
                following: {
                    $slice: [
                        {$filter: {
                            input: "$following",
                            as: "item",
                            cond: {$lt: [{$toDecimal: "$$item.date"}, Date.parse(ISOStringTimestamp)]}
                        }},
                        2
                    ]
                }}
            }
        ]);

**Comment by AbdelrahmanHafez** [comment]
Mongoose does not cast aggregation pipelines:
https://mongoosejs.com/docs/faq.html#aggregate-casting

This plugin does a best effort to cast some of the stages when it can:
https://www.npmjs.com/package/mongoose-cast-aggregation
