### ISSUE TITLE
custom types not working? 

### ISSUE THREAD

**Issue by EhsanSarshar** [Automattic/mongoose#9161]
I a trying to store double type numbers inside mongodb. but I can't achieve it with mongoose.
I have tried both mongoose-float and @mongoosejs/double but neither of them worked for me.
they store the value as int instead of double

```
node: v12.13.0
mongoose: ^5.9.19
```
```
import mongoose, { Schema, model, Document } from "mongoose"
import Double from "@mongoosejs/double"

export const VariantSchema = new Schema(
    price: Double,
    discount: Double,
  }
)

export const Variant = model("Variant", VariantSchema, "Variant")
```

**Comment by EhsanSarshar** [comment]
ok it seems that I should use mongoose raw query instead of mongoose
import mongoose, {mongo} from 'mongoose'
mongoose.connection.collection('Variant').insertOne({price: new mongo.Double(345)})

**Comment by vkarpov15** [comment]
Will check on whether there's an issue with `@mongoosejs/double`.

The underlying MongoDB driver stores JavaScript numbers as doubles, unless the number is an integer, in which case it stores it as an int. In most cases this difference doesn't matter.

Can you please explain why double vs int is important for your use case?

**Comment by EhsanSarshar** [comment]
@vkarpov15 I am using prisma v1 and now I am to migrate from prisma to mongoose. so currently I just replaced mutation. and the way prisma work is that it store all the numbers as Double for Float graphql Type as it also expect the number to be double for querying.

**Comment by vkarpov15** [comment]
I took a closer look and the issue is this: `mongoose.connection.collection('Variant').insertOne({price: new mongo.Double(345)})` . By accessing `mongoose.connection.collection()` directly, you're bypassing Mongoose entirely. Please make sure you go through `save()` or through [mongoose queries](https://mongoosejs.com/docs/queries.html).

I can confirm the below script works as intended: both `price` and `discount` are stored as doubles

```javascript
'use strict';

const Double = require('@mongoosejs/double');
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const variant = new Schema({
    price: Double,
    discount: Double,
  });

  const Variant = mongoose.model('Variant', variant);

  await Variant.create({ price: 99, discount: 42 });

  console.log(await Variant.count({ price: { $type: 'double' } }));
  console.log(await Variant.count({ discount: { $type: 'double' } }));
}
```

**Comment by EhsanSarshar** [comment]
@vkarpov15 I just did as the script you posted but not worked. so the only solution remained was to access mongodb collection directly

**Comment by vkarpov15** [comment]
@EhsanSarshar can you please clarify what you mean by "not worked"? Is there some sort of error message? Please clarify the behavior that you expect and the behavior you observed.

**Comment by EhsanSarshar** [comment]
@vkarpov15 I need the value to store as double no matter what. but with the custom "Double" type it just work as normal mongoose "Number" type.

**Comment by vkarpov15** [comment]
What version of `@mongoosejs/double` are you using?
