### ISSUE TITLE
required filed is consider as unqiue

### ISSUE THREAD

**Issue by karthikeyanr1983** [Automattic/mongoose#9162]
why it's act line churchName unique filed i only given     required: true,

churchModel = mongoose.model(
  "churchs",
  mongoose.Schema({
    churchName: {
      type: String,
      required: true,
    },
    churchAddreess: {
      doorNo: String,
      streetName: String,
      place: String,
      postalcode: String,
    },
    contectPerson: String,
    PhoneNo: String,
    emailId: String,
    location: {
      latitude: Number,
      longitude: Number,
    },
    churchQuestion: [String],
    isActive: Boolean,
  })
);

**Comment by AbdelrahmanHafez** [comment]
It's likely that you have an index already set on the database. Try [dropping all the indexes on your collection](https://stackoverflow.com/questions/13014548/what-is-the-recommended-way-to-drop-indexes-using-mongoose).

**Comment by karthikeyanr1983** [comment]
Hi Hafez consider below filed response came here message par _id indexes dropped showing for me only name fiiled is required, if I get some other problem I will get.

{
    "nIndexesWas" : 2,
    "msg" : "non-_id indexes dropped for collection",
    "ok" : 1.0
}


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AbdelrahmanHafez** [comment]
I am not sure I understand. Does this solve your problem?

If not, run the following script, and share the output:
```js
churchModel.collection.getIndexes({full: true}).then(indexes => {
    console.log("indexes:", indexes);
    // ...
}).catch(console.error);
```

**Comment by karthikeyanr1983** [comment]
Previous solution is solved, But _id unique field also not available or what.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AbdelrahmanHafez** [comment]
Glad it worked.

As to the `_id` field, [MongoDB automatically creates unique index for _id on collection creation](https://docs.mongodb.com/manual/indexes/#default-id-index) to avoid creating two documents with the same identifier.

**Comment by karthikeyanr1983** [comment]
Where should I set to closed #9162<https://github.com/Automattic/mongoose/issues/9162>

**Comment by AbdelrahmanHafez** [comment]
I already closed the issue, no worries. For the future though, you can close an issue by going directly to the GitHub page, you'll find a *Close issue* button in the bottom.

**Comment by karthikeyanr1983** [comment]
Thank u
