### ISSUE TITLE
Throw error when `transform` returns a promise

### ISSUE THREAD

**Issue by botv** [Automattic/mongoose#9163]
Am I doing something wrong defining a transformer on a schema? Here's my schema code:

```js
const bookSchema = new Schema({
  title: {
    type: String,
    transform: async function(v) {
      return await Promise.resolve(v)
    }
  },
});
```

When I create a new `Book`, I get `title: {}`. Do transformers have to be synchronous?

**Comment by vkarpov15** [comment]
Yes they do. [`JSON.stringify()`](https://thecodebarbarian.com/the-80-20-guide-to-json-stringify-in-javascript) is a synchronous function, so `transform` needs to be synchronous as well.
