### ISSUE TITLE
Connection#getClient and setClient for interacting with connection’s underlying MongoClient instance

### ISSUE THREAD

**Issue by DExcalibur** [Automattic/mongoose#9164]
**Do you want to request a *feature* or report a *bug*?**
query (sorry, i was unable to find any community related to mongoosejs)

**What is the current behavior?**
N/A

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
N/A

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node.js = 7.8.0
mongodb = 3.4.14
mongoose = 5.9.19

i want reuse connection created by code mongodb library [mongodb][1] into mongoosejs library [mongoosejs][2]. how to achieve that. please let me know.

  [1]: https://www.npmjs.com/package/mongodb
  [2]: https://www.npmjs.com/package/mongoose

**Comment by vkarpov15** [comment]
We do not currently support that, although that would be a great feature to add. Thank you for the suggestion.
