### ISSUE TITLE
best way to split mongoose models in a monorepo

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#9166]
**Do you want to request a *feature* or report a *bug*?**
This is between a feature or a bug

**What is the current behavior?**
If you split your mongoose models across packages in your monorepo, and you have some circular dependencies some models will be undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

try to create 1 mongoose model per package, and make a direct or indirect circular dep

**What is the expected behavior?**
I want to be able to define models that have circular dependencies without causing undefined problems

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

## Possible solution
GraphQL use thunks to define lazy references likes this:

```jsx
const UserType = new GraphQLObjectType<RoleGroup, GraphQLContext>({
  name: 'User,
  fields: () => ({
})
})
```

node 12.8.0
mongoose: 5.9.17

**Comment by jgcmarins** [comment]
I tried several times to split my models into different packages and got the same problem.

**Comment by sibelius** [comment]
nevermind it was a wrong import

**Comment by sibelius** [comment]
not quite solved

now we got this error:

```jsx
OverwriteModelError: Cannot overwrite `User` model once compiled.
```

**Comment by sibelius** [comment]
wrong filesystem CaSe
