### ISSUE TITLE
Moongose don´t work with a combination of [aggregate|find] + match + sort + collation + locale + character accents

### ISSUE THREAD

**Issue by vadermemo** [Automattic/mongoose#9168]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
collation in aggregate/match/sort + locale {strength: 2} statement don´t work (Differentiate character accents, aka, latin encode (á, é, í, ó, ú))

**If the current behavior is a bug, please provide the steps to reproduce.**

YOUR_SCHEMA_MODEL
          .aggregate([
            {
              $match:match
            },
            { $sort : sort },
        ],
        )
        .collation({
          locale: "es",
          strength: 2,
        })
        .skip((limit * skip) - limit)
        .limit(limit)
        .then(products=>{
          return products
        })

**What is the expected behavior?**
A list sorted by name with custom locale

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v13.8.0
mongoose npm:5.9.20

5.9.20

**Comment by vkarpov15** [comment]
As far as I can tell, the collation works as expected. In the future, can you please clarify what you mean by "don't work" with examples of the behavior you expect versus the behavior you're seeing?

Below script:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const City = mongoose.model('City', Schema({ name: String }));

  await City.create([
    { name: 'orlando' },
    { name: 'órlando' },
    { name: 'ulanbataar' },
    { name: 'úlanbataar' }
  ]);

  const cities = await City.
    aggregate([{ $sort: { name: -1 } }]).
    collation({
      locale: "es",
      strength: 2
    });

  console.log('Cities', cities);
}
```

Output:

```
Cities [
  { _id: 5effa3abf6b033762658e21e, name: 'ulanbataar', __v: 0 },
  { _id: 5effa3abf6b033762658e21f, name: 'úlanbataar', __v: 0 },
  { _id: 5effa3abf6b033762658e21c, name: 'orlando', __v: 0 },
  { _id: 5effa3abf6b033762658e21d, name: 'órlando', __v: 0 }
]
```

When you remove the `collation()` call, you instead get the below output:

```
Cities [
  { _id: 5effa41ffeea32765f83d98c, name: 'úlanbataar', __v: 0 },
  { _id: 5effa41ffeea32765f83d98a, name: 'órlando', __v: 0 },
  { _id: 5effa41ffeea32765f83d98b, name: 'ulanbataar', __v: 0 },
  { _id: 5effa41ffeea32765f83d989, name: 'orlando', __v: 0 }
]
```
