### ISSUE TITLE
Allow readpreference in  findById and findOne queries

### ISSUE THREAD

**Issue by Rfrixy** [Automattic/mongoose#9169]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Currently only the find query allows setting a readpreference. It isn't supported by findOne or findById.
https://mongoosejs.com/docs/api.html#query_Query-setOptions

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
findById and findOne should also allow readpreference to be set as an option.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 10.18.1
Mongoose: 5.9.14
MongoDB: 4.2

**Comment by Rfrixy** [comment]
Functionality already works, even though not explicitly stated in the docs;


found in the example here-
https://mongoosejs.com/docs/api.html#model_Model.startSession

**Comment by vkarpov15** [comment]
Yep with `findOne()` the 2nd parameter is a projection, so to set the session or readPreference you need to do `Model.findOne(filter, null, { readPreference: 'secondaryPreferred' })`
