### ISSUE TITLE
Mention findbyIdAndUpdate in https://masteringjs.io/tutorials/mongoose/update

### ISSUE THREAD

**Issue by dandv** [Automattic/mongoose#9170]
https://masteringjs.io/tutorials/mongoose/update says there are 4 different ways to update a document, but findbyIdAndUpdate is not included.

**Comment by vkarpov15** [comment]
Fixed :+1:. `findByIdAndUpdate()` is just a thin convenience wrapper over `findOneAndUpdate()`, so they're practically identical.
