### ISSUE TITLE
Model.create() returns the field which in schema have select:false

### ISSUE THREAD

**Issue by bhrigushr** [Automattic/mongoose#9171]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The field is returned in the response to `Model.create()`
**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const assert = require("assert")
const mongoose = require("mongoose")
mongoose.set('debug', true);

const connectionString = 'mongodb://localhost:27017/test_db';
console.log('version:: ', mongoose.version)
run()
    .then(() => console.log('done'))
    .catch(error => console.error(error))
    .finally(() => {
        process.exit(1)
    })

async function run() {
    await mongoose.connect(connectionString);
    await mongoose.connection.dropDatabase();

    const schema = new mongoose.Schema(
        {
            name: { type: String },
            pwd: { type: String, select: false }
        }
    )
    const M = mongoose.model('Test', schema);

    const data = { name: 'abc', pwd: 'somesecurepwd' }
    const res = await M.create(data)
    assert.ok(!res.pwd);
}

```
**What is the expected behavior?**
Should not return field which is marked as `select:false`
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v10.15.3
MongoDB: v4.0.9
Mongoose: v5.9.19

**Comment by AbdelrahmanHafez** [comment]
We have another open issue regarding this matter, closing this in favor of https://github.com/Automattic/mongoose/issues/9118.
