### ISSUE TITLE
Question/ Documentation: Modification tracking and markModified()?

### ISSUE THREAD

**Issue by vinerich** [Automattic/mongoose#9173]
**Do you want to request a *feature* or report a *bug*?**
I want to ask a question which I can't resolve through the documentation. Or atleast I can't find it.

**What is the current behavior?**
I got a mongoose schema with some Array in it
```js
const FooSchema = new mongoose.Schema({
  fooArr: [
    {
      bar: { buzz: { type: Number } },
    },
  ],
  barArr: [
    {
      bar: { type: { buzz: { type: Number } }, required: true },
    },
  ],
});
const Foo = mongoose.model("Foo", FooSchema);
```

If i change the value in `fooArr` and `barArr`
```js
const testModified = async () => {
  const f = await Foo.create({
    fooArr: [{ bar: { buzz: 0 } }],
    barArr: [{ bar: { buzz: 0 } }],
  });
  f.fooArr[0].bar.buzz = 1;
  f.barArr[0].bar.buzz = 1;
  console.log("paths", f.modifiedPaths());
};
testModified();
```
output is `paths [ 'fooArr', 'fooArr.0', 'fooArr.0.bar', 'fooArr.0.bar.buzz' ]`

**What is the expected behavior?**
I expect the output to contain not only the changes to `fooArr` but also the changes to `barArr`.
The schema definition differs in the specification of the field `bar`.

Q1: If i want to make an object field required. Do I need to specify `type` and `required`?
Q2: Is the described behaviour expected or is it a bug?
Q3: Through `modifiedPaths()` it is clear that array elements are also referenced through dots with index. I'd like to have this in the documentation for `markModified()`. What's your opinion on this?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v12.18.0
Mongoose: 5.9.9
MongoDB: 4.2.5 Community

**Comment by vinerich** [comment]
A short followup:
If I do a
```javascript
const testModified = async () => {
  const f = await Foo.create({
    fooArr: [{ bar: { buzz: 0 } }],
    barArr: [{ bar: { buzz: 0 } }],
  });
  f.fooArr[0].bar.buzz = 1;
  f.barArr[0].bar.buzz = 1;

  const newF = f.save(); // this line is new
  console.log("newF", newF);
};
testModified();
```

`newF` contains the changes of `f.barArr[0].bar.buzz` even if they are not persisted to the database. According to the [doc](https://mongoosejs.com/docs/api.html#document_Document-save)
> If save is successful, the returned promise will fulfill with the document saved.

I would suppose the changes which are not persisted to the db are not reflected in `newF`.

**Comment by vkarpov15** [comment]
This is due to an error in your schema. As defined, `barArr` is an array of objects where the property `bar` has [mixed type](https://mongoosejs.com/docs/schematypes.html#mixed).

Do this instead and it will work as expected.

```javascript
const FooSchema = new mongoose.Schema({
  fooArr: [
    {
      bar: { buzz: { type: Number } },
    },
  ],
  barArr: [
    {
      bar: { type: new Schema({ buzz: { type: Number } }), required: true }, // <-- note the `new Schema(..)` here
    },
  ],
});
const Foo = mongoose.model("Foo", FooSchema);
```

We're aware that this behavior is confusing and risky, which is why it will change in 6.0 with #7181. Sorry for the trouble!
