### ISSUE TITLE
Question: How to programatically create multiple documents from another Schema?

### ISSUE THREAD

**Issue by Accretence** [Automattic/mongoose#9177]
const BarSchema = new mongoose.Schema({
      
      circulation: {
        type: String,
        default: "0",
      },

    });
    
    module.exports = Bar = mongoose.model("bar", BarSchema);

This **Bar** Schema is acting as a parent for another Schema called **Coin**. When I'm hitting my **Bar** API, I'm creating a Bar document but I want also to create as many **Coin** separate documents as is stated in **circulation** field in my request body, and all of them referencing this single **Bar** document's ObjectID.

This is my Bar API as of this moment: ( Product works as a parent for both Bar and Coin )

    router.post("/", auth, async (req, res) => {
    
      try {
        let bar = await Bar.create({ product: req.body.product._id });
    
        if (req.body.category === "coin") {
          let product = await Product.create({ title: req.body.title });
    
          let coin = await Coin.create({ product: product._id, bar: bar._id });
    
          res.json([bar, product, coin]);
        } else {
          res.json(bar);
        }
      } catch (err) {
        console.error(err.message);
        res.status(500).send("Server Error...");
      }
    });

How can I achieve this?

--

Also, I need to serialize these multiple documents on the order of their creation, For example if "circulation" is set to 50000, these documents need to be serialized from 1 to 50000. So I can't just loop through hitting the Coin API. ( As far as I know)

**Comment by vkarpov15** [comment]
Is there any reason why you don't just use [`Model.insertMany()`](https://mongoosejs.com/docs/api/model.html#model_Model.insertMany)?
