### ISSUE TITLE
Mongoose on DenoJS

### ISSUE THREAD

**Issue by emericspiroux** [Automattic/mongoose#9178]
Hello community !

Sorry, this is not really an issue but a discussion subject: I wonder if a Mongoose's version will be developed for DenoJS !

Is it on the roadmap ?

Best regards,

**Comment by AbdelrahmanHafez** [comment]
Welcome @emericspiroux 

We have an open issue regarding the matter, closing this one in favor of #9056.

**Comment by emericspiroux** [comment]
My bad, I seek issues about "DenoJs" not "Deno"...

**Comment by AbdelrahmanHafez** [comment]
Is DenoJS different from Deno? A quick Google search gave no results to DenoJS that is different than Deno.

Can you share a link to what you're referring to?

**Comment by emericspiroux** [comment]
No ! It the same ! I meant that I searched in the github issues research input, sorry for this misunderstanding...
