### ISSUE TITLE
Doc: Mention passing a session requires an array as the first arg in Model.create()

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#9181]
Please mention it's a must to pass an array as the first argument [here](https://mongoosejs.com/docs/api.html#model_Model.create).

**Comment by AbdelrahmanHafez** [comment]
I believe it's already mentioned:
>To specify options, docs must be an array, **not** a spread.

**Comment by meness** [comment]
Oh! I didn't see that. Sorry! Thanks for mentioning that
