### ISSUE TITLE
findAndUpdate: change the default `new` to `true` by default on mongoose?

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9184]
We could introduce a breaking change in 6.0 and make `findOneAndUpdate` have `new` option set to `true` by default, after implementing https://github.com/Automattic/mongoose/issues/9183 we will be giving users the option to change that behavior if they prefer.

I believe the majority of users would prefer to have the updated document returned from `findOneAndUpdate` by default.

Thoughts? @vkarpov15

**Comment by vkarpov15** [comment]
We changed `new` to `false` by default in 4.0 to be consistent with the MongoDB driver - all other MDB clients use `new: false` behavior by default, so I think we should err on the side of keeping it consistent. I like the idea of making it a globally configurable default like you suggested in #9183 though.

**Comment by AbdelrahmanHafez** [comment]
Ah, weird default from MongoDB, never seen a single `findOneAndUpdate(...)` out there that wasn't using `{ new: true }` unless it was missing by mistake.

IMO, it's more intuitive to have `new: true` by default, but I agree that we should be consistent with the MongoDB driver as long as we can globally configure it.
