### ISSUE TITLE
orFail() for each condition passed in the model.find() argument

### ISSUE THREAD

**Issue by abbasogaji** [Automattic/mongoose#9186]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Okay

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

### An intuitive "orFail()" which will be chained to find() function. throwing error per condition,
for example;

`mongooseModel.find({_id : "34343434", expired : false}).orFail("Record not found").orFail("Record expired")`

**Comment by vkarpov15** [comment]
Not realistically possible, I'm afraid. For example, what happens if neither is found? Either way, the MongoDB server doesn't send back this kind of information, Mongoose would have to execute a separate query for every key in the query filter to support this.
