### ISSUE TITLE
Document#toJSON({getters: true}) performance

### ISSUE THREAD

**Issue by kof** [Automattic/mongoose#919]
I have just benchmarked our performance problem - a query was running almost 3000 ms. The evil is Document#toJSON. It takes up to 70-80% of time from starting the query until getting plain json on large docs.

I was reading the code, It seems like the biggest impact comes from Document#get because it triggers every property getter on the document?

Probably you know a way how to optimize that, if not user need to be warned in the documentation.

Best,
Oleg

**Comment by jspavlick** [comment]
was this ever resolved? I am experiencing the *exact* same problem. I'm spending ~15ms on toJSON

**Comment by vkarpov15** [comment]
Nope, no progress was made. Can you provide an example of the code that you're seeing bad performance with?

**Comment by jspavlick** [comment]
For some background, I'm running on a single, Heroku dyno, talking to a free-tier MongoLab instance. New Relic is reporting that I spend a *long* time in my route code. See example screenshot. Most of my routes (not just the attached) look like this - the *majority* of the time spent in the route itself.

![screenshot 2015-03-23 16 24 25](https://cloud.githubusercontent.com/assets/5431318/6789779/542c396a-d179-11e4-9052-d56e305a175f.png)

I was doing something like <code>res.json(200, { users: _.invoke(users, 'toAdminJSON') });</code> where <code>toAdminJSON();</code> invokes <code>this.toJSON();</code> (as well as some hash munging) By avoiding a call to <code>toJSON();</code> - and instead using a handwritten function to accomplish the same thing for my specific model - I was able to shave a *few seconds* off that route, which, by the way, is returning about ~100 users. The route used to take ~5 seconds, now it takes ~3.

By using my hand-written toJSON, I've shaved off a few hundred milliseconds in a few other routes. I haven't looked into it much further. I will say that my documents are very large. About ~25kB per document on average.

**Comment by vkarpov15** [comment]
Could you show me a few example users? Would be helpful to be able to run this myself.

Also may be a case of your route sending too many users - if it takes 5 seconds for toJSON() to convert the users, it must be taking quite a while for your client to receive all that data.
