### ISSUE TITLE
Allow defining middleware for all query methods or all document methods, but not other middleware types

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9190]
### Use case:

Our team wants to implement sessions in our project, we came to a decision that each HTTP call will create its own session, and pass it around to all the inner functions that are called. It's fairly easy to miss passing the session to one operation though.

It would be neat if we could have an option, that when set to `true` would throw an error if the operation is not using a session.

```js

mongoose.set('requireSession', true);

// throws an error. `Session is required.`
const user = await User.create([{ name: 'Hafez' }]);

// works
const user = await User.create([{ name:'Hafez }], { session });
```

### Next step:
Then we could have an option to allow specific operations to run without a session, for example I have endpoints that only return data from the database, a session for those would be pointless, but I'd like to explicitly allow them.

```js
// option has to be passed explicitly or the operation will throw
const customers = await User.find({ roles: 'customer' }, null, { allowNoSession: true });
```

**Comment by vkarpov15** [comment]
This is an interesting problem. I'm not 100% sure that a global option to require the `session` option is the way to go though. I'd like to take some time to think about this.

Maybe there's some way we can solve this with the new `conn.transaction(async () => { ... })` function? Make it so that every operation within the `transaction()` function automatically gets the right session set?

**Comment by AbdelrahmanHafez** [comment]
Frankly I haven't explored Mongo transactions yet, so I am not familiar with the `conn.transaction(...)` function or how it works.

Any solution that reliably guarantees that I can not have my data in an invalid state if one operation fails does the job.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez I took a closer look and I think the right way to do this is via middleware:

```javascript
schema.pre('save', function() {
  if (this.$session() == null) {
    throw new Error('Session required');
  }
});
```

However, it will be a little more difficult to do this for queries. We should make it possible to define middleware for all queries, `schema.pre(/.*/, { query: true })`.

**Comment by AbdelrahmanHafez** [comment]
Sounds good to me. Only one modification I'd go for is make that happen under a high-level API:

So that all the user has to do is `mongoose.set('requireSessions', true);` and we'll handle setting the middleware under the hood.

**Comment by vkarpov15** [comment]
How about a require-sessions plugin?

**Comment by AbdelrahmanHafez** [comment]
Sounds good to me. 👍
