### ISSUE TITLE
req.body is empty on PUT request (findOneAndReplace)

### ISSUE THREAD

**Issue by alehabra** [Automattic/mongoose#9191]
Bug: req.body is empty on PUT request (findOneAndReplace)

i have a strange behavior on my express/node/mongodb server app, seems that only when i call a PUT request with findOneAndReplace method, this one look like empty.

In fact i have this error message for validation method:
![image](https://user-images.githubusercontent.com/10154872/86332784-44bc9480-bc4b-11ea-8b1a-c29c662b980c.png)

**Here the method**

`app.put('/api/aggiorna_cliente/:id', function(req, res, next) {
    console.log(JSON.stringify(req.body))
    console.log(JSON.stringify(req.params.id))
    Clienti.findOneAndReplace(
        { "_id":req.params.id },
        {
            address:req.body.address,
            brand:req.body.brand,
            cap:req.body.cap,
            city:req.body.city,
            civico:req.body.civico,
            email:req.body.email,
            fiscalcode:req.body.fiscalcode,
            provincia:req.body.provincia,
            utente:req.body.utente
        }, 
        function (err, post) {
            if (err) return next(err);
            res.json(post);
        });
});`

**here the CLIENTI model**

`			const mongoose = require('mongoose');

			const clientiSchema = mongoose.Schema({
				utente:{
					type: String,
					required:true
				},
				cap:{
					type: Number,
					required:true

				},
				civico:{
					type: String,
					required:true

				},
				city:{
					type: String,
					required:true

				},	
				address:{
					type: String,
					required:true
				},
				fiscalcode:{
					type:String,
					required:true
				},
				email:{
					type:String,
					required:true
				},		
				brand:{
					type:String,
					required:true
				},		
				provincia:{
					province: String,
					sigle: String
				}
			});

			const Clienti = mongoose.model('Clienti',clientiSchema);
			module.exports = Clienti;`

Node version 12.16.3
mongoose version: 5.9.21
mongodb version: ^3.1.13

**Comment by AbdelrahmanHafez** [comment]
The error message is telling you that the `brand`, `email`, `fiscalcode`, `address`, `city`, `civico`, `cap`, and `utente` fields are required.

For some reason they're not being passed in the body. What does `console.log(JSON.stringify(req.body)` log?

**Comment by alehabra** [comment]
hello @AbdelrahmanHafez . thank you
the strange behavior is that the console.log(JSON.stringify(req.body)
log the correct object populated.

currently i solved with updateOne method, but is strange that findOneAndReplace does not work

**Comment by AbdelrahmanHafez** [comment]
Can you try this and share the output?

```js
const clienti = new Clienti(req.body);
console.log({ body: JSON.stringify(req.body) });
console.log({ document: clienti.toJSON() });
```
