### ISSUE TITLE
Newly added array of subdocuments is not respected on retrieval from database

### ISSUE THREAD

**Issue by JosephScript** [Automattic/mongoose#9195]
**Do you want to request a *feature* or report a *bug*?**

I think this is a bug 🐛

**What is the current behavior?**

If a schema has been created and a document saved to the database. And then a _new_ array of subdocuments added to the schema, defaults are not returned and it is instead `undefined` until the document is resaved. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Step 1, create a schema:

```js
// classroom.js
import { Schema, model } from 'mongoose'
const ClassroomSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
  },
  {
    timestamps: true,
  },
)
  .set('toJSON', { virtuals: true })
export default model('Classroom', ClassroomSchema)
```

Step 2, save a document:

```js
import Classroom from './classroom'

const classroom = await Classroom.create({ name: 'Bio 101' })
```
Step 3a, update the schema:
```js
// classroom.js
import { Schema, model } from 'mongoose'
const ClassroomSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    students: {
      type: [Schema.Types.ObjectId],
      ref: 'Person',
      default: [],
    },
  },
)
  .set('toJSON', { virtuals: true })
export default model('Classroom', ClassroomSchema)
```

Step 3b, get the doc:

```js
import Classroom from './classroom.js'
const classroom = await Classroom.findOneById('theId').lean().exec()
console.log(classroom)
```

**What is the expected behavior?**

I would expect classroom to look like this:
```js
{
  name: 'Bio 101',
  students: []
}
```

But instead there is no array `students`, it is `undefined`.

Is there a way to force the defaults to return when the object is retrieved? 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v14.1.0, Mongoose v5.8.11, MongoDB 4.0.14 Community.

**Comment by vkarpov15** [comment]
The issue is that Mongoose skips defaults when using `lean()`. Use the [mongoose-lean-defaults plugin](https://www.npmjs.com/package/mongoose-lean-defaults) to work around this.

**Comment by JosephScript** [comment]
I didn't even think to check the docs for lean itself. Thanks a bunch!
