### ISSUE TITLE
Mongoose Error: Cannot read property 'name' of null. Any clues?

### ISSUE THREAD

**Issue by Pelesibt** [Automattic/mongoose#9197]
I keep getting this error, don't know why? Any clues?

             2| 
             3| 
       >> 4| <p><%= campground.name %></p>
             5| 
             6| 
             7| 

            Cannot read property 'name' of null

show.ejs:

           <%- include('partials/header')%>
               <h1>this is a show template</h1>
               <p><%= campground.name %></p>
           <%- include ("partials/footer") %>

index.ejs:

             <%- include ("partials/header") %>
               <div class="container">
	         <header class="jumbotron">
				<div>
					<h1>Welcome To YelpCamp!</h1>
					<p>View our hand-picked campgrounds from all over the world</p>
					<p> <a class="btn btn-primary btn-lg" href="/campgrounds/new">Add New Campground</a> </p>
				</div>
	        </header>

              
		<div class="row text-center" style="display:flex; flex-wrap:wrap">                                                        					 
                     <% campgrounds.forEach(function(campground){ %>
				<div class="col-md-3 col-sm-6"> 
					<div class="thumbnail">
						<img src="<%= campground.image %>">
							<div class="caption">
							        <h4> <%= campground.name %> </h4>
						       </div>
						       <p>
						            <a href="/campgrounds/ <%= campground._id %>" class="btn btn- 
                                                                                  primary">More Info</a>
						         </p>
					     </div>
				  </div>
					<% }) %>
	               </div>
                 </div>

             <%- include ("partials/footer") %>

app.js:

              var express = require("express"),
                     app  = express(),
               bodyparser = require("body-parser"),
               mongoose  = require("mongoose");
  
               mongoose.connect("mongodb://localhost:27017/yelp_camp", {useNewUrlParser: true, useUnifiedTopology: true});
               app.use(bodyparser.urlencoded({extended:true}));
               app.use(express.static("public"));
               app.use(express.static("views"));
               app.set("view engine", "ejs");

                  //SCHEMA SETUP
                  var campgroundSchema = new mongoose.Schema({
	          name : String,
	          image : String,
	          description : String,
	           _id : String
              });

              // var ObjectId = Schema.ObjectId;
                var Campground = mongoose.model("Campground", campgroundSchema);
                  app.get("/", function(req,res){res.render("landing");
	      });

            //INDEX ROUTE - Show all campgrounds
              app.get("/campgrounds", function(req,res){
                 // Get all campgrounds from DB
	           Campground.find({},function(err, allCampgrounds){
		                       if(err) {
			                      console.log(err);
		                                } else {
			                    res.render("index",{campgrounds: allCampgrounds});
		                        }
	                       });
                        });

               //CREATE ROUTE - add new campground to DB
               app.post("/campgrounds", function(req,res){
	       //get data from form and add to campgrounds array
	        var name = req.body.name;
	        var image = req.body.image;
	        var newCampGround = {name: name, image:image};
	      // Create a new campground and save to DB
	      Campground.create(newCampGround, function(err, newlyCreated){
		                        if(err){
			                        console.log(err);
		                               } else {
				            //redirect back to campgrounds page
	                                    res.redirect("/campgrounds");
	                	          }
	                           });
                            });	
                //NEW ROUTE - Show form to create new campground
                app.get("/campgrounds/new",function(req,res){
	                 res.render("new.ejs");
	               });

               //SHOW ROUTE - Shows more info about one campground
                app.get("/campgrounds/:id", function(req, res){
	       //find the campground with provided ID
	        Campground.findById(req.params.id, function(err, foundCampground){
		                                     if(err){
			                                     console.log(err)
			                                    } else {
			                                   //render show template with that campground
	                                                     res.render("show", {campground: foundCampground})
		                                            }
	                                           });
                                         });

                      app.listen(3000, function(){
	                   console.log("The YelpCamp Server Has Started!")
                      })

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @Pelesibt 

Would appreciate it if you could format the code more nicely next time, [learn how](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

Looking at the error you're getting
```
Cannot read property 'name' of null
```

It's saying that you're trying to access key `name` of an variable that is null, look at the stack trace, you'll find exactly where the error happened, the filename, the line, and the column.

Sharing it would help narrow down where the issue exactly is.

**Comment by zzdish** [comment]
@Pelesibt how did you resolve this issue, because i'm facing the same issue.
