### ISSUE TITLE
Context creation failed: connection (...) to (...):27017 timed out

### ISSUE THREAD

**Issue by andreyvital** [Automattic/mongoose#9200]
I keep getting on AWS Lambda:

```
(node:74961) UnhandledPromiseRejectionWarning: Error: Context creation failed: connection 8 to (...):27017 timed out
(node:74961) UnhandledPromiseRejectionWarning: Error: Context creation failed: connection 5 to (...):27017 timed out
(node:74961) UnhandledPromiseRejectionWarning: Error: Context creation failed: connection 2 to (...):27017 timed out
```

He's my connect function:

```TS
let cachedDB: Mongoose | null = null;

export default async function connectToMongo(logger: winston.Logger): Promise<Mongoose> {
  if (!process.env.MONGO_URI) {
    throw new Error("Missing `MONGO_URI` environment variable. Aren't you missing a .env file and is it up to date?");
  }

  if (cachedDB && cachedDB.connection) {
    return cachedDB;
  }

  const mongooseConnection = await mongoose.connect(process.env.MONGO_URI, {
    // https://github.com/Automattic/mongoose/issues/7108
    useNewUrlParser: true,
    bufferCommands: false,
    bufferMaxEntries: 0,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    poolSize: 10,
    dbName: process.env.MONGO_DB_NAME,
    // connectTimeoutMS: 3000,
    // socketTimeoutMS: 30000,
  });

  if (Environment.isProduction) {
    cachedDB = mongooseConnection;
    return cachedDB;
  }

  mongoose.set("debug", (collection: string, method: string, query: any, document: any, options: any) => {
    if (process.env.DEBUG_MONGO_QUERY_EXECUTION) {
      logger.info("Executing MongoDB query", {
        collection,
        method,
        query,
        document,
        options,
      });
    }
  });

  cachedDB = mongooseConnection;
  return cachedDB;
}
```

My server runs as a replica set on MongoDB Atlas. I'm connecting using the `mongodb+srv://` DSN.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
```
Node.js 12
> require('mongoose').version
'5.9.19'
```

I'm not sure what are other details I could provide to sort out this issue...it is pretty random and happens all day long :(

**Comment by andreyvital** [comment]
@vkarpov15 I not sure I can provide a script to reproduce the issue, this basically happens when connecting to the database. I'm not sure why

**Comment by andreyvital** [comment]
@vkarpov15 I'm not sure I can provide a script to reproduce the issue, it basically happens when connecting to the database. I'm not sure why

**Comment by vkarpov15** [comment]
@andreyvital the most common reason for the "connection X timed out" error is an exceedingly slow query that times out the socket. If your `socketTimeoutMS` is 30 seconds, any database operation that takes longer than 30 seconds will cause this error.

Can you confirm whether you have any queries or writes that may be taking this long?

You may also want to try increasing `socketTimeoutMS` to 120000 (120 seconds) as a workaround.

Also, your connection code has a slight race condition. Please do this instead:

```javascript
const mongooseConnection = mongoose;
if (Environment.isProduction) {
    cachedDB = mongooseConnection;
}
await mongoose.connect(process.env.MONGO_URI, { ... });
```

This will ensure that multiple calls to `connectToMongo()` at the same time don't cause multiple `.connect()` calls.

**Comment by andreyvital** [comment]
@vkarpov15 I doubt it

![image](https://user-images.githubusercontent.com/967317/87311740-05693000-c4f6-11ea-9d23-4511660bc750.png)

Here's a list of the last 24h of operations I pulled from Atlas. The maximum operation time took 4.09s. Unless I'm looking to the wrong metric, that doesn't seem to be the problem. I've increased the `socketTimeoutMS` to 120s as well—no effect. It continues to randomly timing out. Do you have any ideas of how can I track this down?

**Comment by vkarpov15** [comment]
Do you have any info on the query/operation that's causing this? Perhaps [error handling middleware](https://mongoosejs.com/docs/middleware.html#error-handling-middleware) might help you track down what's failing.

**Comment by andreyvital** [comment]
@vkarpov15 is there a way to do it for all models? maybe something at the root level in the connection?

**Comment by vkarpov15** [comment]
@andrenarchy [global plugins](https://mongoosejs.com/docs/plugins.html#global).

```javascript
mongoose.plugin(schema => {
  schema.post(/save/, function(err, res, next) {
    // do something with err
  });
});
```
