### ISSUE TITLE
Make calling `mongoose.connect()` while connecting or connected a no-op

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9203]
Calling `mongoose.connect()` multiple times currently causes issues (#9167, #9107) , but unfortunately people do that quite frequently. Should be fine to introduce this in a minor release.

**Comment by vkarpov15** [comment]
Also need to make sure the connection string is the same. Calling `mongoose.connect()` with a different connection string or db name while already connecting or connected should throw an error.

**Comment by roychri** [comment]
I think this change causes problems now.

https://github.com/Automattic/mongoose/issues/9335
