### ISSUE TITLE
I can't hide the mongoose log through Mongoose.set('debug', false)

### ISSUE THREAD

**Issue by cuiko** [Automattic/mongoose#9206]
**The version of mongoose is  v5.7.8**

In some case, I want to hide the mongoose log.
And then, I find the [mongoose doc](https://mongoosejs.com/docs/api.html#mongoose_Mongoose-set).
And I try to hide the mongoose log(Just like the following).

My Code
```js
const mongoose = require('mongoose')
mongoose.set('debug', false)
```

But the log is still printed.
I try to find the source code of mongoose, I see the following

```js
  // mongoose/lib/drivers/node-mongodb-native/collection.js => line 154
   if (debug) {
      if (typeof debug === 'function') {
        debug.apply(_this,
          [_this.name, i].concat(sliced(args, 0, args.length - 1)));
      } else if (debug instanceof stream.Writable) {
        this.$printToStream(_this.name, i, args, debug);
      } else {
        this.$print(_this.name, i, args, typeof debug.color === 'undefined' ? true : debug.color);
      }
    }
```

When I delete the fllowing.
> this.$print(_this.name, i, args, typeof debug.color === 'undefined' ? true : debug.color);

It works for me

And I print the value of the variable **debug**,  no matter what I pass in is **false** or **Function**, it's always outputs **true**.

At last, English is **not** my native language; please excuse typing errors.

**Comment by vkarpov15** [comment]
I'm unable to repro this issue, the below script shows that setting `mongoose.set('debug', false)` disables debug printing:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });


  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));
  await Model.create({ name: 'foo' });

  mongoose.set('debug', false);
  console.log('Set debug to false');

  await Model.create({ name: 'foo' });

  console.log('done');
}

```

Can you please modify the above script to demonstrate your issue?

**Comment by cuiko** [comment]
> I'm unable to repro this issue, the below script shows that setting `mongoose.set('debug', false)` disables debug printing:
> 
> 我无法重现这个问题，下面的脚本显示设置 mongoose.set (‘ debug’ ，false)将禁用调试打印:
> 
> ```js
> 'use strict';
>   
> const mongoose = require('mongoose');
> 
> mongoose.set('debug', true);
> mongoose.set('useFindAndModify', false);
> 
> const { Schema } = mongoose;
> 
> run().catch(err => console.log(err));
> 
> async function run() {
>   await mongoose.connect('mongodb://localhost:27017/test', {
>     useNewUrlParser: true,
>     useUnifiedTopology: true
>   });
> 
> 
>   await mongoose.connection.dropDatabase();
> 
>   const Model = mongoose.model('Test', Schema({ name: String }));
>   await Model.create({ name: 'foo' });
> 
>   mongoose.set('debug', false);
>   console.log('Set debug to false');
> 
>   await Model.create({ name: 'foo' });
> 
>   console.log('done');
> }
> ```
> 
> Can you please modify the above script to demonstrate your issue?
> 
> 您能否修改上面的脚本来演示您的问题？

Thank you for your reply, I think it's because of my code problem. I found that I wrote a piece of code before.
```js
if (process.env.NODE_ENV !== 'production') {
  mongoose.set('debug', true)
}
```
I'm so sorry for making such a stupid mistake, I will close this issue.
