### ISSUE TITLE
Any thought of creating rust implementaion?

### ISSUE THREAD

**Issue by amber-m-o-r-e** [Automattic/mongoose#9207]

**Comment by vkarpov15** [comment]
Do you mean re-implementing Mongoose internals in Rust but still leaving it as a JavaScript library, or creating a Mongoose-like library for Rust?

**Comment by amber-m-o-r-e** [comment]
Mongoose like a library for Rust.

**Comment by vkarpov15** [comment]
We've thought about it. Rust is a very cool language. But currently don't have the time or the support to work on this.
