### ISSUE TITLE
Documentation / Enhancement request for Model.find({}) .

### ISSUE THREAD

**Issue by jennifer-abu** [Automattic/mongoose#9210]
This is a documentation request ...

I often have trouble finding documentation for basic methods ...

In this case 

`Mode.find({})`

I am trying to find the documentation for this method with this particular syntax above ...

I looked here

https://mongoosejs.com/docs/api.html#model_Model.find

but could not find specific information about the behavior of the above method with the single argument {}.

**Comment by Rapol** [comment]
Most of the time you can look into the mongo equivalent query function and that will behave the same. https://docs.mongodb.com/manual/reference/method/db.collection.find/

For Model.find({}), it will return all records since all record satisfy the empty query criteria.
