### ISSUE TITLE
Support question 

### ISSUE THREAD

**Issue by mano3493** [Automattic/mongoose#9213]
Hi,

I have built a service using Nodejs and Mongodb and I use Mongoose as a client. And my service receives 1000QPS easily during normal days, Any sale time it would go till 3K QPS. But when I can see my node process is getting restarted very frequently, This is because we have configured it as restart on failure.

Whenever it restarts, whatever the request comes it is failing in nginx layer itself.

But we are not able to figure out the errors in logs, Since nothing is logged, All we see is 200 and success logs. But for sure something is breaking. 

I have added unCaughtException in the node process still no luck. But this failure is happening only when the load goes to Mongodb if i cut those calls (And proxy to any existing api) system is up and running fine. Whenever I enable mongo db this failure is happening.

I guess my Mongodb cannot take the load and its failing (Just a guess), This is because i have 4 boxes behind ELB and each box will run 4 node process which is behind Nginx load balancer. All the process are getting restarted one by one.

Any expertise here can help me with below questions.

- Does Mongo failure or any connect pool error make our node process fail ?

- If yes, how can we figure the failure, Where should we add logs ? I have application and api level logs already, but its not coming there

- And Is there a any common error that Mongoose wont log in default and I need to add manually  ?

Since a new user of Mongo and Mongoose, facing difficulty in figuring out what is going wrong, Any help would be much appreciated.

**Comment by vkarpov15** [comment]
1) No, MongoDB crashing should not cause your node process to exit.
2) I'd look into what "we have configured it as restart on failure" means for you, specifically what does "failure" mean. One issue I've seen is that people often configure health checks to fail if the api server doesn't respond after a certain period of time, leading to repeated restarts when the database is under high load.
3) Not that I know of.

Let me know if that helps or if you have any followup questions.
