### ISSUE TITLE
bufferMaxEntries is ignored and defaulted to 0 if bufferCommands is true

### ISSUE THREAD

**Issue by Rapol** [Automattic/mongoose#9218]
**What is the current behavior?**

When creating a connection with the following option:
```
{
   bufferCommands: true,
   bufferMaxEntries: 99
}
```

Mongoose will default to
```
{
   bufferCommands: true,
   bufferMaxEntries: 0
}
```
**What is the expected behavior?**

If bufferCommands is true, it should allow the user to set the bufferMaxEntries. This is the specific line https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L633

As far as my knowledge goes for bufferCommands and bufferMaxEntries and default mongo options, the if should change from 

`if (options.bufferCommands != null) {`

to

`if (!options.bufferCommands) {`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v10.14.1
Mongoose: 5.9.22
MongoDB: 3.2 (CosmoDB)

**Background**

We have a serverless environment (aws lambda and azure function app) and we were having problems with the recommended way of running mongo (https://mongoosejs.com/docs/lambda.html). Specifically, bufferCommands = false and bufferMaxEntries = 0. We are caching the database connection and we were getting this error randomly (always during insert, updates or deletes):

> MongoError: no connection available for operation and number of stored operation 

We decided to no longer set bufferCommand to false since from our understanding that will make mongo not autoReconnect which is something we would like to happen. After setting it to true, we were getting the same error. Which lead us to go into mongoose and found that it sets bufferMaxEntries to 0 when bufferCommands is not null which means you cannot pass bufferCommands = true.

This is the line in the mongo client that throws the error mentioned above because bufferMaxEntries is set to 0 by mongoose.

https://github.com/mongodb/node-mongodb-native/blob/5808e12f13e39bfddb26cc15fe9b4dd751e1f363/src/topologies/topology_base.ts#L36

**Comment by vkarpov15** [comment]
"We decided to no longer set bufferCommand to false since from our understanding that will make mongo not autoReconnect" is false. Mongoose will auto reconnect as expected regardless of `bufferCommands`. `bufferCommands` just means that Mongoose will error out immediately if it is disconnected, as opposed to waiting for reconnect.

We will get rid of the offending line, it doesn't seem to be necessary and can cause problems if you're running with `useUnifiedTopology: false`.
