### ISSUE TITLE
Validate before execute the query

### ISSUE THREAD

**Issue by mleiver** [Automattic/mongoose#9219]
**Do you want to request a *feature* or report a *bug*?**
feature

I have a "product model" and an endpoint where the user queries the products. As usual, the user can send fields in the query string to filter the results, but if the user sends a field with an invalid type, for example, a word in a numeric path, the validation fails and throws a CastError as expected.

```js
const ProductModel = require('../models/Product');

app.get("/products", async (req, res, next) => {
    // user sends {upc: "word"} when upc should be a number, therefore validation fails
    const products = await ProducstModel.find(req.qury);
})
```
The problem: Is there a way to validate the query against the model/schema? So that a validation error to be thrown.
Why do I want to do this? When creating a document, if validation fails, a ValidationError is thrown, which has all the errors, so I can respond to the user with it.
On the other hand, CastError is thrown at the first error found.

ValidationError: `"Product validation failed: upc: Cast to Number failed for value \"word\" at path \"upc\""`

CastError: `"Cast to ObjectId failed for value "word" at path "upc" for model "Product""`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.9.21
Node: 12.16.1

**Comment by Rapol** [comment]
https://mongoosejs.com/docs/validation.html

`doc.validate(callback) or doc.validateAsync()`

**Comment by mleiver** [comment]
> A quick google search gave me this https://mongoosejs.com/docs/validation.html
> 
> ```
> You can manually run validation using doc.validate(callback) or doc.validateSync()
> ```

@Rapol document#prototype#validate is for validating document instances, not for queries, at least as far as I know.
I would be nice if there was a method for queries, which does the same.

**Comment by Rapol** [comment]
Ah I see what you mean. Found an old issue from 2017 asking for the same feature https://github.com/Automattic/mongoose/issues/5137 and it still open :(

**Comment by mleiver** [comment]
Thanks, haven't seen that issue. I guess we have to wait for mongoose to implement it or make a plugin on our own. In the end, there is a good idea with `Model.validatePaths`, I think it might work for a plugin.

**Comment by vkarpov15** [comment]
@mleiver I think you're looking for [`Model.validate()`](https://mongoosejs.com/docs/api/model.html#model_Model.validate).

```javascript
// Validate `req.query` against `ProductsModel`, but just the `_id` and `upc` paths
await ProductsModel.validate(req.query, ['_id', 'upc']);

const products = await ProductsModel.find(req.query);
```
