### ISSUE TITLE
Document.prototype.save never calls callback, but document is saved correctly.

### ISSUE THREAD

**Issue by conorpo** [Automattic/mongoose#9220]
**Bug**

When I try to save a document, it saves correctly on the database, but the callback function is never called.
```js
console.log('Test A') //This shows
order.save((err,data) => {
    console.log('Test B') //This doesnt show, but doc is saved in db correctly
    if (err) return console.log(err);
    console.log(`Order ${data._id} saved.`);
    res.status(200).send(data);
})      
```
**What is the expected behavior?**
It should call the bacllback function

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v12.18.0
mongoose v5.9.22 (npm version)
Not using MongoDB since I'm just connecting to mongo atlas

**Comment by vkarpov15** [comment]
The below script prints 'saved' as expected. Please modify the below script to demonstrate your issue.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));

  const doc = new Model({ name: 'test' });
  doc.save(() => console.log('Saved!'));
}
```

**Comment by conorpo** [comment]
After making 0 changes it started to work, I believe it might have had something to do with Mongo Atlas, although I am not too sure.
