### ISSUE TITLE
Feature request: Add a findOrCreate() method

### ISSUE THREAD

**Issue by nspeedzy** [Automattic/mongoose#9221]
**Description**
Create a `findOrCreate()` method. What that method will do is, It will first find if a record exists taking a query as the first parameter. If a record exists, It will return a document. Otherwise, it will create a new record with the query as the document to be inserted.

**Syntax**:
```js
Model.findOrCreate(query, callback); // The query can be an object
```
**Example**:
```js
Model.findOrCreate({ clientId: "keyboard-cat" }, function(err, res) { // The 'res' parameter is the returned document
    if (err) { throw err; }
    else { console.log(res); }
});
```

**Do you want to request a *feature* or report a *bug*?**
A feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

| Environment | Version       | 
| -------------  |:-------------:| 
| Mongoose    | 5.9.22          | 
| MongoDB     | 4.2.6            | 
| Node.js         | 13.8.0          |

**Comment by Rapol** [comment]
There is no native findOrCreate mongo query so it will not be atomic. It is possible to use Model.findOneAndUpdate and Model.findByIdAndUpdate with upsert set to true as a findOrCreate alternative. This uses mongo findOneAndUpdate internally so in this case it will be atomic. You can pass the query object in both the query and data parameters and it would work the same as a findOrCreate.
https://stackoverflow.com/a/54067343

Or add the method to the model but again, this will not be atomic
https://stackoverflow.com/a/48358596

**Comment by nspeedzy** [comment]
Thanks @Rapol
