### ISSUE TITLE
Subdoc in array created without an _id

### ISSUE THREAD

**Issue by boydenhartog** [Automattic/mongoose#9222]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When I try to push a new child item into an array on an existing parent item, it is created with `_id: null`.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a model with an array of subdocs like so (I have also tried it with `{ _id: true }` as second arg for the mappingSchema):

```
const mappingSchema = new mongoose.Schema(
  {
    mapToField: {
      type: String,
      enum: [
        "subject",
        "location",
        "company",
        "hours",
        "rate",
        "startDate",
        "endDate",
      ],
      required: true,
    },
    mapToLabel: {
      type: String,
      required: true,
    },
    regex: {
      type: String,
      required: true,
    },
  }
);

const vendorSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      index: true,
    },
    mappings: [mappingSchema],
  },
  { timestamps: true }
);
const Vendor = mongoose.model("Vendor", vendorSchema);
```

When I create a **new** vendor with a few mappings, the vendor is created with an _id and the mappings are all created with their own _id. This is what I want. However when I try to create a new mapping for an **existing** vendor, the mapping is created with `id: null`. This is not what I am expecting.

I am creating the mappings like this (the `mapping` object in the function params comes from a form so it does not include an _id):

```
  async createMapping(vendorId, mapping) {
    const vendor = await Vendors.findOne({ _id: vendorId });
    vendor.mappings.push(mapping);
    return await vendor.save();
  },
```

**What is the expected behavior?**
When I try to add mappings to an existing vendor, they are created with `_id: null`. This is not what I'm expecting and is not in line with the examples in the documentation (https://mongoosejs.com/docs/subdocs.html#adding-subdocs-to-arrays). 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`node: v13.11.0`
`mongo: v4.2.6`
`mongoose: "^5.9.12"`

**Comment by boydenhartog** [comment]
The mapping has an `_id` only when it is created with a new vendor. When I try to push a new mapping into the array, it is created with `_id: null`. I have also tried to do it this way but the result is the same:
```
    return await Vendors.update(
      { _id: vendorId },
      { $push: { mappings: mapping } },
      { upsert: true }
    );
```

**Comment by boydenhartog** [comment]
For now I'm using this workaround but it feels a bit dirty:
```
const vendor = await Vendors.findOne({ _id: vendorId });
mapping._id = new Mongoose.mongo.ObjectId();
vendor.mappings.push(mapping);

return await vendor.save();
```

**Comment by vkarpov15** [comment]
The below script shows that pushing a mapping automatically creates a new `_id`. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

const mappingSchema = new mongoose.Schema(
  {
    mapToField: {
      type: String,
      enum: [
        "subject",
        "location",
        "company",
        "hours",
        "rate",
        "startDate",
        "endDate",
      ],
      required: true,
    },
    mapToLabel: {
      type: String,
      required: true,
    },
    regex: {
      type: String,
      required: true,
    },
  }
);



const vendorSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      index: true,
    },
    mappings: [mappingSchema],
  },
  { timestamps: true }
);
const Vendor = mongoose.model("Vendor", vendorSchema);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  await Vendor.create({ email: 'foo', mappings: [{ regex: 'bar', mapToLabel: 'baz', mapToField: 'subject' }] });

  const vendor = await Vendor.findOne();
  assert.ok(vendor.mappings[0]._id);

  vendor.mappings.push({ regex: 'a', mapToLabel: 'b', mapToField: 'subject' });
  assert.ok(vendor.mappings[1]._id);
  await vendor.save();

  const fromDb = await Vendor.findById(vendor);
  assert.ok(vendor.mappings[0]._id);
  assert.ok(vendor.mappings[1]._id);

  console.log('Done');
}
```
