### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by kamal1latiyal** [Automattic/mongoose#9226]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

After change, I used "mongoose.set('useUnifiedTopology', true);" this line but still getting the same error
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
plz have a look

**Comment by kamal1latiyal** [comment]
After change, I used "mongoose.set('useUnifiedTopology', true);" this line but still getting the same error
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
plz have a look

**Comment by dameunbite** [comment]
Same issue here

```
// mongodb connections
var options = {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    promiseLibrary: global.Promise,
    readPreference: 'primaryPreferred'
};

mongoose.Promise = require('bluebird');

mongoose.connect(process.env.MONGODB_URI, options, async function (err, db) {
    if (!err) {
        debug('Server Successfully Connected to Database');
    } else {
        debugErr(err);
    }
});
```

Error Message
```
(node:2850) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

**Comment by ha6000** [comment]
same here, but I noticed it starts happening after certain commit in my program, cant figure out what in the commit causes it.

**Comment by ha6000** [comment]
ok found the reason for mine, in another file I also connected to it, but I did not have that option, dont know if this is reason for your errors too (prop not)

**Comment by kamal1latiyal** [comment]
Good to hear from you that you found the reason. Although I was making a
mistake still my code is running and not giving error on running web page
but the warning is still there on visual studio.

**Comment by vkarpov15** [comment]
Are you using any other node modules that depend on mongodb? Try running `npm list | grep "mongo"` and paste the output here.

**Comment by kamal1latiyal** [comment]
well grep is not recognised in my vscode but I am pasting the output here for both of the commands separately run bcz in one time it's giving error
PS C:\Users\cu16b\webD\codeial> npm list | grep "mongo"
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+ npm list | grep "mongo"
+            ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\cu16b\webD\codeial> npm list
codeial@1.0.0 C:\Users\cu16b\webD\codeial
+-- body-parser@1.19.0
| +-- bytes@3.1.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.7.2
| | +-- depd@1.1.2 deduped
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.1 deduped
| | +-- statuses@1.5.0 deduped
| | `-- toidentifier@1.0.0
| +-- iconv-lite@0.4.24
| | `-- safer-buffer@2.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@6.7.0
| +-- raw-body@2.4.0
| | +-- bytes@3.1.0 deduped
| | +-- http-errors@1.7.2 deduped
| | +-- iconv-lite@0.4.24 deduped
| | `-- unpipe@1.0.0
| `-- type-is@1.6.18
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.27
|     `-- mime-db@1.44.0
+-- cookie-parser@1.4.5
| +-- cookie@0.4.0
| `-- cookie-signature@1.0.6
+-- ejs@3.1.3
| `-- jake@10.6.1
|   +-- async@0.9.2
|   +-- chalk@2.4.2
|   | +-- ansi-styles@3.2.1
|   | | `-- color-convert@1.9.3
|   | |   `-- color-name@1.1.3
|   | +-- escape-string-regexp@1.0.5
|   | `-- supports-color@5.5.0 deduped
|   +-- filelist@1.0.1
|   | `-- minimatch@3.0.4 deduped
|   `-- minimatch@3.0.4 deduped
+-- express@4.17.1
| +-- accepts@1.3.7
| | +-- mime-types@2.1.27 deduped
| | `-- negotiator@0.6.2
| +-- array-flatten@1.1.1
| +-- body-parser@1.19.0 deduped
| +-- content-disposition@0.5.3
| | `-- safe-buffer@5.1.2 deduped
| +-- content-type@1.0.4 deduped
| +-- cookie@0.4.0 deduped
| +-- cookie-signature@1.0.6 deduped
| +-- debug@2.6.9 deduped
| +-- depd@1.1.2 deduped
| +-- encodeurl@1.0.2
| +-- escape-html@1.0.3
| +-- etag@1.8.1
| +-- finalhandler@1.1.2
| | +-- debug@2.6.9 deduped
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- on-finished@2.3.0 deduped
| | +-- parseurl@1.3.3 deduped
| | +-- statuses@1.5.0 deduped
| | `-- unpipe@1.0.0 deduped
| +-- fresh@0.5.2
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- on-finished@2.3.0 deduped
| +-- parseurl@1.3.3
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@2.0.6
| | +-- forwarded@0.1.2
| | `-- ipaddr.js@1.9.1
| +-- qs@6.7.0 deduped
| +-- range-parser@1.2.1
| +-- safe-buffer@5.1.2
| +-- send@0.17.1
| | +-- debug@2.6.9 deduped
| | +-- depd@1.1.2 deduped
| | +-- destroy@1.0.4
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- etag@1.8.1 deduped
| | +-- fresh@0.5.2 deduped
| | +-- http-errors@1.7.2 deduped
| | +-- mime@1.6.0
| | +-- ms@2.1.1
| | +-- on-finished@2.3.0 deduped
| | +-- range-parser@1.2.1 deduped
| | `-- statuses@1.5.0 deduped
| +-- serve-static@1.14.1
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- parseurl@1.3.3 deduped
| | `-- send@0.17.1 deduped
| +-- setprototypeof@1.1.1
| +-- statuses@1.5.0
| +-- type-is@1.6.18 deduped
| +-- utils-merge@1.0.1
| `-- vary@1.1.2
+-- express-ejs-layouts@2.5.0
+-- express-session@1.17.1
| +-- cookie@0.4.0 deduped
| +-- cookie-signature@1.0.6 deduped
| +-- debug@2.6.9 deduped
| +-- depd@2.0.0
| +-- on-headers@1.0.2
| +-- parseurl@1.3.3 deduped
| +-- safe-buffer@5.2.0
| `-- uid-safe@2.1.5
|   `-- random-bytes@1.0.0
+-- mongoose@5.9.22
| +-- bson@1.1.4
| +-- kareem@2.3.1
| +-- mongodb@3.5.9
| | +-- bl@2.2.0
| | | +-- readable-stream@2.3.7
| | | | +-- core-util-is@1.0.2
| | | | +-- inherits@2.0.3 deduped
| | | | +-- isarray@1.0.0
| | | | +-- process-nextick-args@2.0.1
| | | | +-- safe-buffer@5.1.2 deduped
| | | | +-- string_decoder@1.1.1
| | | | | `-- safe-buffer@5.1.2 deduped
| | | | `-- util-deprecate@1.0.2
| | | `-- safe-buffer@5.1.2 deduped
| | +-- bson@1.1.4 deduped
| | +-- denque@1.4.1
| | +-- require_optional@1.0.1
| | | +-- resolve-from@2.0.0
| | | `-- semver@5.7.1 deduped
| | +-- safe-buffer@5.1.2 deduped
| | `-- saslprep@1.0.3
| |   `-- sparse-bitfield@3.0.3
| |     `-- memory-pager@1.5.0
| +-- mongoose-legacy-pluralize@1.0.2
| +-- mpath@0.7.0
| +-- mquery@3.2.2
| | +-- bluebird@3.5.1
| | +-- debug@3.1.0
| | | `-- ms@2.0.0 deduped
| | +-- regexp-clone@1.0.0 deduped
| | +-- safe-buffer@5.1.2 deduped
| | `-- sliced@1.0.1 deduped
| +-- ms@2.1.2
| +-- regexp-clone@1.0.0
| +-- safe-buffer@5.2.1
| +-- sift@7.0.1
| `-- sliced@1.0.1
+-- nodemon@2.0.4
| +-- chokidar@3.4.1
| | +-- anymatch@3.1.1
| | | +-- normalize-path@3.0.0 deduped
| | | `-- picomatch@2.2.2
| | +-- braces@3.0.2
| | | `-- fill-range@7.0.1
| | |   `-- to-regex-range@5.0.1
| | |     `-- is-number@7.0.0
| | +-- UNMET OPTIONAL DEPENDENCY fsevents@2.1.3
| | +-- glob-parent@5.1.1
| | | `-- is-glob@4.0.1 deduped
| | +-- is-binary-path@2.1.0
| | | `-- binary-extensions@2.1.0
| | +-- is-glob@4.0.1
| | | `-- is-extglob@2.1.1
| | +-- normalize-path@3.0.0
| | `-- readdirp@3.4.0
| |   `-- picomatch@2.2.2 deduped
| +-- debug@3.2.6
| | `-- ms@2.1.2
| +-- ignore-by-default@1.0.1
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- pstree.remy@1.1.8
| +-- semver@5.7.1
| +-- supports-color@5.5.0
| | `-- has-flag@3.0.0
| +-- touch@3.1.0
| | `-- nopt@1.0.10
| |   `-- abbrev@1.1.1
| +-- undefsafe@2.0.3
| | `-- debug@2.6.9 deduped
| `-- update-notifier@4.1.0
|   +-- boxen@4.2.0
|   | +-- ansi-align@3.0.0
|   | | `-- string-width@3.1.0
|   | |   +-- emoji-regex@7.0.3
|   | |   +-- is-fullwidth-code-point@2.0.0
|   | |   `-- strip-ansi@5.2.0
|   | |     `-- ansi-regex@4.1.0
|   | +-- camelcase@5.3.1
|   | +-- chalk@3.0.0
|   | | +-- ansi-styles@4.2.1
|   | | | +-- @types/color-name@1.1.1 deduped
|   | | | `-- color-convert@2.0.1
|   | | |   `-- color-name@1.1.4
|   | | `-- supports-color@7.1.0
|   | |   `-- has-flag@4.0.0
|   | +-- cli-boxes@2.2.0
|   | +-- string-width@4.2.0
|   | | +-- emoji-regex@8.0.0
|   | | +-- is-fullwidth-code-point@3.0.0
|   | | `-- strip-ansi@6.0.0
|   | |   `-- ansi-regex@5.0.0
|   | +-- term-size@2.2.0
|   | +-- type-fest@0.8.1
|   | `-- widest-line@3.1.0
|   |   `-- string-width@4.2.0 deduped
|   +-- chalk@3.0.0
|   | +-- ansi-styles@4.2.1
|   | | +-- @types/color-name@1.1.1
|   | | `-- color-convert@2.0.1
|   | |   `-- color-name@1.1.4
|   | `-- supports-color@7.1.0
|   |   `-- has-flag@4.0.0
|   +-- configstore@5.0.1
|   | +-- dot-prop@5.2.0
|   | | `-- is-obj@2.0.0
|   | +-- graceful-fs@4.2.4
|   | +-- make-dir@3.1.0
|   | | `-- semver@6.3.0
|   | +-- unique-string@2.0.0
|   | | `-- crypto-random-string@2.0.0
|   | +-- write-file-atomic@3.0.3
|   | | +-- imurmurhash@0.1.4
|   | | +-- is-typedarray@1.0.0
|   | | +-- signal-exit@3.0.3
|   | | `-- typedarray-to-buffer@3.1.5
|   | |   `-- is-typedarray@1.0.0 deduped
|   | `-- xdg-basedir@4.0.0 deduped
|   +-- has-yarn@2.1.0
|   +-- import-lazy@2.1.0
|   +-- is-ci@2.0.0
|   | `-- ci-info@2.0.0
|   +-- is-installed-globally@0.3.2
|   | +-- global-dirs@2.0.1
|   | | `-- ini@1.3.5
|   | `-- is-path-inside@3.0.2
|   +-- is-npm@4.0.0
|   +-- is-yarn-global@0.3.0
|   +-- latest-version@5.1.0
|   | `-- package-json@6.5.0
|   |   +-- got@9.6.0
|   |   | +-- @sindresorhus/is@0.14.0
|   |   | +-- @szmarczak/http-timer@1.1.2
|   |   | | `-- defer-to-connect@1.1.3
|   |   | +-- cacheable-request@6.1.0
|   |   | | +-- clone-response@1.0.2
|   |   | | | `-- mimic-response@1.0.1 deduped
|   |   | | +-- get-stream@5.1.0
|   |   | | | `-- pump@3.0.0 deduped
|   |   | | +-- http-cache-semantics@4.1.0
|   |   | | +-- keyv@3.1.0
|   |   | | | `-- json-buffer@3.0.0
|   |   | | +-- lowercase-keys@2.0.0
|   |   | | +-- normalize-url@4.5.0
|   |   | | `-- responselike@1.0.2
|   |   | |   `-- lowercase-keys@1.0.1 deduped
|   |   | +-- decompress-response@3.3.0
|   |   | | `-- mimic-response@1.0.1 deduped
|   |   | +-- duplexer3@0.1.4
|   |   | +-- get-stream@4.1.0
|   |   | | `-- pump@3.0.0
|   |   | |   +-- end-of-stream@1.4.4
|   |   | |   | `-- once@1.4.0 deduped
|   |   | |   `-- once@1.4.0
|   |   | |     `-- wrappy@1.0.2
|   |   | +-- lowercase-keys@1.0.1
|   |   | +-- mimic-response@1.0.1
|   |   | +-- p-cancelable@1.1.0
|   |   | +-- to-readable-stream@1.0.0
|   |   | `-- url-parse-lax@3.0.0
|   |   |   `-- prepend-http@2.0.0
|   |   +-- registry-auth-token@4.2.0
|   |   | `-- rc@1.2.8
|   |   |   +-- deep-extend@0.6.0
|   |   |   +-- ini@1.3.5 deduped
|   |   |   +-- minimist@1.2.5
|   |   |   `-- strip-json-comments@2.0.1
|   |   +-- registry-url@5.1.0
|   |   | `-- rc@1.2.8 deduped
|   |   `-- semver@6.3.0
|   +-- pupa@2.0.1
|   | `-- escape-goat@2.1.1
|   +-- semver-diff@3.1.1
|   `-- xdg-basedir@4.0.0
+-- passport@0.4.1
| +-- passport-strategy@1.0.0
| `-- pause@0.0.1
`-- passport-local@1.0.0
  `-- passport-strategy@1.0.0 deduped

PS C:\Users\cu16b\webD\codeial> grep "mongo"
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ grep "mongo"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\cu16b\webD\codeial> npm list | grep "mongo"
grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+ npm list | grep "mongo"
+            ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\cu16b\webD\codeial>

**Comment by ha6000** [comment]
I don't think grep is on windows?

**Comment by AbdelrahmanHafez** [comment]
@ha6000 try [cmder](https://cmder.net/), bash or Git bash.

**Comment by vkarpov15** [comment]
Hmm ok so you don't have any other MongoDB-related modules. That rules that out.

Are you calling  `mongoose.connect()` or `mongoose.createConnection()` multiple times in your code? Search your codebase for `mongoose.connect()` calls.

Also, make sure you call `mongoose.set('useUnifiedTopology', true)` **before** calling `mongoose.connect()`.
