### ISSUE TITLE
Failed to create array elements for multiple documents

### ISSUE THREAD

**Issue by dileepxdn** [Automattic/mongoose#9230]
What I am doing is, 
I have some MongoDB documents list, I iterate through each document item and each document has an array item and I push some empty objects at the end and then I add some data to the last object that I pushed and saving those documents one by one. Getting this error. 

mongoose: 5.4.22
node : 12.17.0

![image](https://user-images.githubusercontent.com/34201306/87220908-7dfcaf00-c385-11ea-9ce9-42b4788cc0a3.png)

**Comment by vkarpov15** [comment]
Please provide an actual code sample, don't just write a paragraph describing your code. Also, please copy/paste your stack trace as text, not a screenshot. It's difficult to read the line numbers in your screenshot.
