### ISSUE TITLE
Request to have type definitions stored in this repo and maintained by owners

### ISSUE THREAD

**Issue by harveyconnor** [Automattic/mongoose#9235]
Currently the @types/mongoose is reliant on community contribution and most of the time its either out of date or just doesn't actually have the correct definitions. I'm particularly experiencing this when trying to write hooks in Typescript as they don't match what I'm trying to do.

e.g. 
```ts
schema.pre('deleteMany', { document: false, query: true }, async function cleanup(next) {
  const docs = await this.model.find(this.getFilter()); // This method is not documented anywhere either.
});
```

My request is that we have something maintained in here without having to go through the complex and tedious process of contributing to @types/mongoose. Or at the very least we have something generated in here that we can modify to match the functionality.

**Comment by huming2207** [comment]
I agree. A separated `@types/mongoose` is usable for me, but it may cause some version inconsistency issues.

**Comment by AbdelrahmanHafez** [comment]
We're considering maintaining official TypeScript definitions, please follow #8108 for updates.
