### ISSUE TITLE
update operations do not support aggregation pipelines

### ISSUE THREAD

**Issue by syffs** [Automattic/mongoose#9236]
**Do you want to request a *feature* or report a *bug*?**

mongodb feature support

**What is the current behavior?**

update operations do not support aggregation pipeline. 
See reproduction: in Typescript, it ends up with the below result:
```ts
endDate: Date;
           ~~~~~~~
    The expected type comes from property 'endDate' which is declared here on type....
```
in Node:
```js
Cast to date failed for value '{$dateFromParts: {....'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this stack post](https://stackoverflow.com/questions/62813827/increment-months-to-a-date-using-an-element-attribute/62816110?noredirect=1#comment111191164_62816110)

**What is the expected behavior?**

As per [mongodb doc](https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/), aggregation pipelines are supported within update operations

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node: 12.16.3
mongoose 5.9.24
@types/mongoose: 5.7.31

**Comment by vkarpov15** [comment]
I'm unable to repro this, the below script demonstrates that update pipelines work fine in Mongoose 5.9.x. Just keep in mind that Mongoose doesn't cast aggregation pipelines currently.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Test = mongoose.model('Test', Schema({ test: Date }));

  await Test.create({ test: new Date('2015-06-01') });

  const res = await Test.findOneAndUpdate({}, [{
    $set: {
      test: {
        $dateFromParts: {
          year: 2012,
          month: { $add: [{ $month: '$test' }, 2] }
        }
      }
    }
  }], { new: true });
  console.log(res);
}
```

Please modify the above script to demonstrate your issue.
