### ISSUE TITLE
Get Deprecation warning after using right options also..

### ISSUE THREAD

**Issue by developersparadox** [Automattic/mongoose#9237]
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

![git](https://user-images.githubusercontent.com/57582408/87427541-91667f00-c5fe-11ea-823f-0d7f02a94dce.PNG)
![git1](https://user-images.githubusercontent.com/57582408/87427550-94616f80-c5fe-11ea-87f8-8bc88a8e589c.PNG)

**Comment by vkarpov15** [comment]
Try putting `set('useUnifiedTopology', true)` before `mongoose.connect()`.
