### ISSUE TITLE
Enable async function on Schema getter

### ISSUE THREAD

**Issue by HADMARINE** [Automattic/mongoose#9241]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
On Mongoose schema getter, no async method is allowed. So i suggest to add as a feature.
___
(ex)
```javascript
const AnySchema = new Schema{
    any: {
      type: String
      default: 'default',
      // THIS DOESN'T WORK! - NO ASYNC FUNCTION ALLOWED
      get: async (d) => {
          return await asyncFunction();
      },
    },
}
```
___
btw, On similar previous issue, the final answer was no. [Issue link](https://github.com/Automattic/mongoose/issues/517)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose : 5.9.18
mongodb : 3.8
node : 14.0.0

**Comment by vkarpov15** [comment]
No way for us to support async getters in any meaningful way. Because `JSON.stringify()` is sync and property accesses are sync, no way for us to consistently handle promises as document properties.
