### ISSUE TITLE
(node:70233) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by Robap56** [Automattic/mongoose#9246]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by Robap56** [comment]
siempre aparece al correr mi backend

**Comment by AbdelrahmanHafez** [comment]
Welcome @Robap56 
Check the following link to find out how to fix all deprecation warnings: https://mongoosejs.com/docs/deprecations.html
