### ISSUE TITLE
find uuid does not work well in aggregates

### ISSUE THREAD

**Issue by sibelius** [Automattic/mongoose#9250]
**Do you want to request a *feature* or report a *bug*?**
I think it is a bug, or an inconsistency behavior

**What is the current behavior?**
Searching by a UUID string works well on .find but not on aggregate, example below

```jsx
 const all = await App.find({
    uuid: uuid.toString(),
  });

  const all2 = await App.aggregate([
    {
      $match: {
        uuid: uuid.toString()),
      },
    },
  ]);
```

`all` return the items
but `all2` does not

**If the current behavior is a bug, please provide the steps to reproduce.**

steps below

**What is the expected behavior?**
it should work well in both

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 12
mongoose: 5.9.17
mongodb: 3.5.8

**Comment by vkarpov15** [comment]
[Mongoose doesn't cast aggregation pipeline stages](https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate). So you need to manually convert `uuid` to the correct type if you're using aggregations.

What is the type of `uuid` in your schema?

**Comment by sibelius** [comment]
Type Buffer subtype 4

**Comment by vkarpov15** [comment]
Does

```javascript
const all2 = await App.aggregate([
    {
      $match: {
        uuid: uuid,
      },
    },
  ]);
```

work?

**Comment by sibelius** [comment]
this work for us

`uuid: new mongoose.Types.Buffer(value).toObject(0x04)`

we used mongoose type Buffer and subtype `0x04`

**Comment by AbdelrahmanHafez** [comment]
@sibelius You might find [this plugin](https://www.npmjs.com/package/mongoose-cast-aggregation) useful.

**Comment by sibelius** [comment]
I think the problem is the inconsistent behavior

I'd rather be less explicit in casting behavior

but the plugin looks good
