### ISSUE TITLE
The connect() function accepts a callback parameter but not a promise

### ISSUE THREAD

**Issue by mijatovicmile** [Automattic/mongoose#9252]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
The current behavior when I try to connect to **MongoDB Atlas Cluster** is that get an error `MongoParseError: Invalid connection string` but only when I try to use *promise*, with *callback* works as expected. Password does not contains any special characters , just strings and numbers 

**If the current behavior is a bug, please provide the steps to reproduce.**

As I mention , *promise* does not work, code below: - **Output -> Unable to connect to MongoDB. Error: MongoParseError: Invalid connection string**

```
const mongoose = require("mongoose");

const config = require("./config");

// MongoDB URI
const mongoURI =
  "mongodb+srv//" +
  config.mongo.user +
  ":" +
  config.mongo.password +
  config.mongo.host +
  config.mongo.authDB +
  "?retryWrites=true&w=majority";

mongoose
  .connect(mongoURI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then((result) => { // Successfully connected
    console.log(result);
  })
  .catch((err) => {
    // Catch any potential error
    console.log(mongoose.version);
    console.log("Unable to connect to MongoDB. Error: " + err);
  });
```

*callback* works as expected - **Output -> 'Connected'**
```
const mongoose = require("mongoose");

const config = require("./config");

// MongoDB URI
const mongoURI =
  "mongodb+srv//" +
  config.mongo.user +
  ":" +
  config.mongo.password +
  config.mongo.host +
  config.mongo.authDB +
  "?retryWrites=true&w=majority";

mongoose.connect(
  mongoURI,
  { useNewUrlParser: true },
  () => {
    console.log("Connected");
  },
  (err) => {
    // Catch any potential error
    console.log("Unable to connect to MongoDB. Error: " + err);
  }
);
```

**What is the expected behavior?**
Expected behavior is to use *promise* instead of *callback* , this is very weird because promise does not work, but callback works. Why ? 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js - **v12.14.0**
Mongoose - **5.9.19**
MongoDB - None because MongoDB Atlas is a hosted MongoDB service option in the cloud which requires no installation overhead and offers a free tier to get started.

**Comment by vkarpov15** [comment]
I suspect the difference is due to `useUnifiedTopology` and the fact that your mongoURI is malformed. `mongodb+srv//` should be `mongodb+srv://`, and you also need to specify a `port`.
