### ISSUE TITLE
How to cancel populate mongoose ?

### ISSUE THREAD

**Issue by Sagunt0022** [Automattic/mongoose#9254]
this my code

```
    const filteringTheNecessaryFieldsForTheTour = fieldsProjection(info);
    const pathDocumentPlace = "places.place";
    const filteringTheNecessaryFieldsForThePlace = fieldsProjection(info, {
      path: pathDocumentPlace,
    });

    const tour = await tourModel
      .findById(id, filteringTheNecessaryFieldsForTheTour)
      .populate(pathDocumentPlace, filteringTheNecessaryFieldsForThePlace);

```
The fieldsProjection function does the filtering of the necessary fields from the query, it can return those fields that are needed or an empty object. an empty object means that the user does not need the values from " places.place",this means that I don't need to call populate. Is there any way to cancel populate?

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @Sagunt0022

It's not clear what you're trying to achieve. Can you elaborate on what you mean by:
>dependent on value filteringTheNecessaryFieldsForThePlace I want to cancel populate.

**Comment by Sagunt0022** [comment]
@AbdelrahmanHafez I changed my question, you can read it again. thank.

**Comment by vkarpov15** [comment]
If I'm reading your question correctly, I think what you want to do is:

```javascript
const projection = filteringTheNecessaryFieldsForTheTour
const query = tourModel.findById(id, projection)
if (projection['places.place']) {
  query.populate(pathDocumentPlace, filteringTheNecessaryFieldsForThePlace);
}

const tour = await query;
```
