### ISSUE TITLE
TypeScript: Mongoose query types should check if key exists in class 

### ISSUE THREAD

**Issue by kkoomen** [Automattic/mongoose#9256]
**Do you want to request a *feature* or report a *bug*?**

I consider this a **bug**.

**What is the current behavior?**

I have a users service class like so (using NestJS):

```ts
import { UpdateQuery, FilterQuery } from 'mongoose';
import { User } from './schemas/users.schema.ts';

class UsersService {
  constructor(@InjectModel(User.name) private readonly usersModel: Model<User>) {}

  async updateOne(
    conditions: FilterQuery<User>,
    fields: UpdateQuery<User>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions,
        fields,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
}
```

The `User` schema can look like something like this:

```ts
import { Document } from 'mongoose';

class User extends Document {
  username: string;
}
```

When I have my controller with this:

```ts
class MyController {
  constructor(private readonly usersService: UsersService) {}

  @Get()
  async update(@Body() body: UpdateUserDTO): Promise<User> {
    // This expression below should cause an error that 'test' does not exists on `User` which doesn't happen.
    return this.usersService.updateOne({ test: true });
  }
}
```

This can be fixed for some part by modifying the `updateOne()` in the `UsersService` like so:

```ts
 async updateOne(
    conditions: Partial<Record<keyof User, any>>,
    fields: Partial<Record<keyof User, any>>,
    options: Record<string, unknown> = {},
  ): Promise<T> {
    try {
      const result = await this.usersModel.findOneAndUpdate(
        conditions as FilterQuery<User>,
        fields as UpdateQuery<User>,
        { new: true, ...options },
      );
      return result;
    } catch (err) {
      console.log(err);
    }
  }
```

but the custom approach above doesn't work for fields named like `$addToSet`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The `FilterQuery`, `UpdateQuery`, `CreateQuery` and `DeleteQuery` (and other similar types) should all check whether the key is keyof `T`, in my case `T` is `User`.

**IF** there is a solution that can be done by the users themselves I'd love to know how, but the only option I see without having to redefine all the Mongoose query types such as `FilterQuery` is that Mongoose itself should check this which I would expect.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.9.14, the rest is irrelevant.

**Comment by vkarpov15** [comment]
We don't currently have officially supported TypeScript types. Please follow #8108 for updates on the TypeScript front.

**Comment by MitchellCash** [comment]
@vkarpov15 understanding this is an old issue, but now that #8108 has been closed as completed on 30 Nov 2020 and released in v5.11, I am still seeing this issue while running v6.6.

The same reproducible code as the original post still won't be type checked like we were hoping. Would you like me to open a new issue, will you reopen this issue, or is this a "won't fix"?

**Comment by MitchellCash** [comment]
From what I can tell the issue comes from the `RootQuerySelector` type here https://github.com/Automattic/mongoose/blob/master/types/query.d.ts#L88-L90 as it allows any `key:value` and this type is intersected with the `_FilterQuery` type which is the one we're relying on for stricter type checking.

**Comment by vkarpov15** [comment]
@MitchellCash yep that's expected behavior. Mongoose does type casting for you, so it is perfectly valid to pass in any object as a query filter. If you want to be stricter, that's up to you.
