### ISSUE TITLE
validateModifiedOnly should be true by default if the document is NOT new

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#9263]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

As [docs state](https://mongoosejs.com/docs/api.html#document_Document-save), `validateModifiedOnly` option for `save()` is `false` by default.

**What is the expected behavior?**

As [docs state](https://mongoosejs.com/docs/documents.html#updating):

> The `save()` function is generally the right way to update a document with Mongoose. With `save()`, you get full validation and middleware.

I believe `validateModifiedOnly` should be `true` if and only if the document's `isNew` property is `false`, which means the document has already been saved (or better, created). So, it's good for performance to validate only updated fields if the document is not new.

**Comment by vkarpov15** [comment]
I think the issue here is that we need some better documentation around `validateModifiedOnly`. Normally, Mongoose validates modified paths **and** required paths. If `isNew` is false, Mongoose won't validate paths that aren't modified or required, even if `validateModifiedOnly = false`.

**Comment by Tom5om** [comment]
Hi @vkarpov15 how can we get around it?

If the documents isNew=false, but on validateSync() or save() we want ALL fields to be validated normally.

**Comment by Swampi995** [comment]
> I think the issue here is that we need some better documentation around `validateModifiedOnly`. Normally, Mongoose validates modified paths **and** required paths. If `isNew` is false, Mongoose won't validate paths that aren't modified or required, even if `validateModifiedOnly = false`.

I think you might be wrong, validateModifiedOnly has no sense when isNew = true, because all paths are newly populated, so it makes sense just when isNew = false. I also tested this and I can see the performance improvements on saving an existing document with validateModifiedOnly = false.
