### ISSUE TITLE
While trying to fetch data using findById(''), It got stuck.

### ISSUE THREAD

**Issue by sachchidanandy** [Automattic/mongoose#9265]
**Do you want to request a *feature* or report a *bug*?**
I need help if I am doing something wrong.

**What is the current behavior?**
While trying to fetch data using findById() it gets stuck. If I am using correct ObjectID then it's returning data but If I am trying with Invalid ObjectID or empty string It got stuck.

**If the current behavior is a bug, please provide the steps to reproduce.**
Organization.mjs 
---------------------

```
import mongoose from 'mongoose';
const orgSchema = new mongoose.Schema({
    org_name: { type: String, required: true },
    org_logo: { type: String },
    founded_on: { type: Date, required: true },
    founded_by: { type: String, required: true },
    active: { type: Boolean, default:true, required: true }
}, { timestamps: true });
export default mongoose.model('Organization', orgSchema);
```

db_connect.mjs
-----------------

```
// Connection config
const dbConfig = {
    useNewUrlParser: true,
    useFindAndModify: false,
    useCreateIndex: true,
    useUnifiedTopology: true
};
export default () => {
    // Connect to db
    mongoose.connect(MONGODB_URI, dbConfig).then(() => {
        console.log('Connected to db successfully...');
    }).catch( err => {
        console.error(err.message);
    });
    // Listen to any error after connection
    mongoose.connection.on('error', err => {
        console.error(err.message);
    });
};
```

user_controller.mjs
------------------

```
import Organization from '../model/Organization.mjs';
export const createNewUser = async (req, res) => {
    try {
         // Check if org present or not
        const orgObject = await Organization.findById(req.body.org_id).exec();
        if(! orgObject) {
            return res.status(BAD_REQUEST).json(INVALID_ORG);
        }
       // TODO : Create user
    } catch (error) {
        return res.status(INTERNAL_SERVER_ERROR).json(SOMETHING_WENT_WRONG);
    }
}
```

**What is the expected behavior?**
If findById() should be called using invalid ObjectID it should return empty Object. But it's getting stuck there only. I have checked that by adding console.log()

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
Node.js : 12.18.1
Mongoose: 5.9.18
MongoDB: 4.2.8

**Comment by vkarpov15** [comment]
If you call `const orgObject = await Organization.findById(req.body.org_id).exec();` with an invalid id, the `await Organization.findById(...).exec()` call will throw an error. Did you check if the `return res.status(INTERNAL_SERVER_ERROR).json(SOMETHING_WENT_WRONG);` block executes?

**Comment by sachchidanandy** [comment]
Thanks, for the response after restarting my server it starts working. Yes, it's throwing error as it's invalid org_id. But at that time it was stuck.

**Comment by vkarpov15** [comment]
Can you please explain what you mean by "But at that time it was stuck."?
