### ISSUE TITLE
Adding sub docs by index fails on save() 

### ISSUE THREAD

**Issue by pjbrinck** [Automattic/mongoose#9266]
v5.9.25

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In the following gist, note how inserting a sub doc by index in example 3 yields a different sub doc type and yields a validation error on save().

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// example 1
document.keys = [{}];
document.keys[0].name = 'test';
console.log(document.keys.constructor.name); 	// CoreDocumentArray
console.log(document.keys[0].constructor.name); // EmbeddedDocument
document.save();				//

// example 2
document.keys = [];
document.keys.push({});
document.keys[0].name = 'test';
console.log(document.keys.constructor.name); 	// CoreDocumentArray
console.log(document.keys[0].constructor.name); // EmbeddedDocument
document.save();				//

// example 3
document.keys = [];
document.keys[0] = {};
document.keys[0].name = 'test';
console.log(document.keys.constructor.name); 	// CoreDocumentArray
console.log(document.keys[0].constructor.name); // Object
document.save();				// validation failed: keys: Cast to Array failed for value "[ { name: 'test' } ]" at path "keys"
```
	
**What is the expected behavior?**

I expect the same behavior in example 3 as in examples 1 and 2, that proper and transparent type casting takes place.

Documentation (https://mongoosejs.com/docs/subdocs.html#adding-subdocs-to-arrays) suggests using "methods such as push, unshift, addToSet, and others..."

I suspect "and others" includes using keys[0] as an LVALUE, and not only as an RVALUE. This type of assignment (example 3) seems to have worked similar to examples 1 and 2 in a previous version 5.0.3. The fact that I can actually make the object assignment tells me, that such assignment is intended valid. Alternatively, the assignment should have been failed.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

v5.9.25

**Comment by vkarpov15** [comment]
I suspect the issue you're seeing is related to the [first question on our FAQ](https://mongoosejs.com/docs/faq.html#array-changes-not-saved). TLDR; `document.keys[0] = {};` doesn't trigger change tracking and casting, use `document.keys.set(0, {})` instead. We're working on a fix for this with #8884. 

However, the below script works as expected, no errors thrown. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();
  const Model = mongoose.model('Test', Schema({
    keys: [{ name: String }]
  }));

  await Model.create({});
  const document = await Model.findOne();

  document.keys = [{}];
  document.keys[0].name = 'test';
  console.log(document.keys.constructor.name);  // CoreDocumentArray
  console.log(document.keys[0].constructor.name); // EmbeddedDocument
  await document.save();

  document.keys = [];
  document.keys.push({});
  document.keys[0].name = 'test';
  console.log(document.keys.constructor.name);  // CoreDocumentArray
  console.log(document.keys[0].constructor.name);
  await document.save();

  document.keys = [];
  document.keys[0] = {};
  document.keys[0].name = 'test';
  console.log(document.keys.constructor.name);  // CoreDocumentArray
  console.log(document.keys[0].constructor.name); // Object
  await document.save();

  console.log('Done');
}
```

**Comment by pjbrinck** [comment]
I appologize for not having reproduced issue in small scale... 

Allow me to follow up:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();
  const Model = mongoose.model('Test', Schema({
    keys: [{ name: String }]
  }));

  let document;

  document = new Model({});
  document.keys[0] = { name: 'test '};
  await document.save(); // works well

  document = new Model({});
  document.keys[0] = { name: 'test '};
  document.keys = document.keys; // note this unnecessary assignment, which I had because I use highly generalized auto-generated code 
  await document.save(); // fails with: Error: Test validation failed: keys: Cast to Array failed for value "[ { name: 'test ' } ]" at path "keys"

  console.log('Done');
}
```

I removed the unnecessary assignment from my code generator and it works. 

But maybe this still has your interest to investigate.

**Comment by vkarpov15** [comment]
Thanks for the repro script, we will look into this.

Out of curiosity, what code generator are you using? This looks like a similar issue to #9293.

**Comment by pjbrinck** [comment]
Valeri,

we are using a home grown filtering/transformation tool inspired by XSLT (https://www.npmjs.com/package/jsxl) which generates JS code.


Med venlig hilsen / Best regards

Poul-Jørgen Brinck

https://www.linkedin.com/in/pjbrinck/
pjbrinck@hotmail.com<mailto:pjbrinck@hotmail.com>
+45 20581463

________________________________
