### ISSUE TITLE
Bug on supports pre(Array, Function) (gh-7803) when using module.

### ISSUE THREAD

**Issue by mathieulavallee** [Automattic/mongoose#9267]
Hello,

I think I found a weird bug using the function **pre** with **array parameter** on **Schema** in particular circumstance. 

**Current behavior?**
So using the [test related to gh-7803](https://github.com/Automattic/mongoose/blob/3390c5383cc4f11235306b1d9b71acd1eb34d4d5/test/schema.test.js#L2081). The test runs just fine but when I use the code in a module, the output is not as expected.

Here is the reproducible test using a module. 
_Test.js_ import _test_module.js_ and run assert where at least one function should be named "testMiddleware" as define in the _test_module.js_. The output is weird, instead of having both of the key distributed, they are grouped in an array and never get called on either 'save' or 'remove'.

test_module.js

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = Schema({ name: String });
function testMiddleware() {  console.log('foo'); }
schema.pre(['save', 'remove'], testMiddleware);
const testModel = mongoose.model('testModel', schema);
module.exports = testModel;
```

test.js
```javascript
const test = require("./test_module.js");
assert(Array.from(test.schema.s.hooks._pres.get('save')).some((hook)=>hook.fn.name==="testMiddleware"));
assert(Array.from(test.schema.s.hooks._pres.get('remove')).some((hook)=>hook.fn.name==="testMiddleware"));
```

weird faulty output
```javascript
test.schema.s.hooks._pres
Map {
  [ 'save', 'remove' ] => [ { fn: [Function: testMiddleware], isAsync: false } ],
  'save' => [ { fn: [Function], isAsync: false },
    { fn: [Function], isAsync: false },
    { fn: [Function], isAsync: false } ],
  'remove' => [ { fn: [Function], isAsync: false } ] }
```

When the pre function is executed sequencially, the ouput is as expected. The expected ouput the following. 
```javascript
test.schema.s.hooks._pres
Map {
  'save' => [ { fn: [Function], isAsync: false },
    { fn: [Function], isAsync: false },
    { fn: [Function: testMiddleware], isAsync: false },
    { fn: [Function], isAsync: false } ],
  'remove' => [ { fn: [Function], isAsync: false },
    { fn: [Function: testMiddleware], isAsync: false } ] }
```

version:
mongoose :5.9.25
node:v10.15.3

**Comment by vkarpov15** [comment]
That's very strange behavior, I'm unable to repro this. Given the below `testmodel.js`:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = Schema({ name: String });
function testMiddleware() {  console.log('foo'); }
schema.pre(['save', 'remove'], testMiddleware);
const testModel = mongoose.model('testModel', schema);
module.exports = testModel;

```

The below script runs fine, prints 'foo' and a nicely formatted hooks array:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const testModel = require('./testmodel');

  console.log(testModel.schema.s.hooks._pres);

  const doc = new testModel({ name: 'test' });
  await doc.save();
}
```

Are there any other npm modules in your project that might be overwriting built-in methods?

**Comment by mathieulavallee** [comment]
Nevermind after a package update, the issue can't be reproduce...
