### ISSUE TITLE
EmbeddedDocument.prototype.invalidate vs Document.prototype.invalidate return value inconsistency

### ISSUE THREAD

**Issue by bathos** [Automattic/mongoose#9271]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`Document.prototype.invalidate` returns a ValidationError (consistent with [the docs](https://mongoosejs.com/docs/api.html#document_Document-invalidate)). This is shadowed on the `EmbeddedDocument` subclass, but the `EmbeddedDocument` implementation returns a boolean. As far as I can tell this is a bug — the docs don’t document `EmbeddedDocument` separately and its existence seems to be more of an implementation detail.

**If the current behavior is a bug, please provide the steps to reproduce.**

Probably simplest just to link to the implementation code, since it’s clear enough that one returns objects and the other returns booleans:

https://github.com/Automattic/mongoose/blob/415ba3de0486727209f6c2ffc9d6edd360235fc2/lib/document.js#L2573-L2597
https://github.com/Automattic/mongoose/blob/3622233de38316a09f160c07abf8073a9627a5bb/lib/types/embedded.js#L278-L294

**What is the expected behavior?**

That both versions of `invalidate()` exhibit the same behavior (or, if not, that the difference be documented).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Been stuck at 5.6.11 for a while due to breaking changes in a patch version :) — but in any case, this behavior is the same in 5.9.25.

**Comment by vkarpov15** [comment]
@bathos what exactly are the breaking changes in a patch version that you mentioned? I'd like to fix that for you :+1:

**Comment by bathos** [comment]
@vkarpov15 I’m not entirely sure — I last investigated it in around January but didn’t have the bandwidth to go deep; pinning the version was a stopgap solution. I’m hoping to get a chance to investigate it further in the next month or so (esp. since there have been some fixes since then that we’ll benefit from) and if I figure out what’s up I’ll open a new issue for it. Thanks!
