### ISSUE TITLE
Discriminator for array won't update array element

### ISSUE THREAD

**Issue by katherinefhc** [Automattic/mongoose#9272]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using an embedded discriminator in an array and doing an update on that array element, mongoose isn't $set-ing the value as expected
aka arrayField.$.prop updates like the example below are not being applied
```
await Model.findOneAndUpdate(
    { _id,  'arrayField.prop': 'someVal' },
    { $set: { 'arrayField.$.prop': 'someOtherVal' } }
  );
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/katherinefhc/defbbc8c877f56afbc46b79cc236681b#file-gistfile1-txt-L45

**What is the expected behavior?**
The $set updates on fields in embedded arrays that have discriminators should update the document

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node@12.18
mongoose@5.9.25
mongodb@3.5.9

**Comment by vkarpov15** [comment]
That's because Mongoose doesn't know about the `attributes` path - you need to specify the expected discriminator type in your filter for Mongoose to cast it correctly. For example:

```javascript
const updateRes = await ShapeContainer.findOneAndUpdate(
    { _id: insertRes._id, 'shapes': { $elemMatch: { name: 'shape num 4', kind: 'circle' } } },
    { $set: { 'shapes.$.attributes': { radius: 100 } } },
    { new: true }
  );
```
