### ISSUE TITLE
Allow modifying the returned document after findbyId with a middleware(afterware)

### ISSUE THREAD

**Issue by sandorvasas** [Automattic/mongoose#9276]
I tried `document.post('find', doc => doc.xxx = true)` but the resulting doc of .findById is not modified.
It would be practical to allow post-processing of documents, e.g. we have docs in the db that already have some null values in some of their fields, and want to override those values with some default values. 

Adding a flag like `runDefaultOnValues: [null, '', etc]` next to `default` in the schema could also work, so defaults wouldn't just run if the field is strictly undefined.

**Comment by vkarpov15** [comment]
I don't understand the issue - can you please write a script that demonstrates the behavior you're seeing and the behavior you expect?

**Comment by sandorvasas** [comment]
I'm not sure what's hard to understand. I want to modify the returned documents of find/findOne/findbyId/etc using a middleware.

e.g. there's a doc in the db, say: SomeSchema `{ _id: 1, some_field: 6 }`
I want to be able to declare a middleware:
```
SomeSchema.post('find', doc => { if (doc.some_field == 6) doc.some_field = 7; })
```
so when calling SomeModel.findById(1), some_field of the returned document becomes 7
```
const doc = await SomeModel.findById(1);
console.log(doc.toJSON())
// prints: { _id: 1, some_field: 7 }
```

This could be achieved much more easily, if mongoose allowed defaults to run not only for undefined fields.
e.g. 
The Problem
```
const SomeSchema = mongoose.Schema({
   fieldA: { type: String, default: 'ABC' }
})
// (...)

const doc = await SomeModel.create({ fieldA: null })
// (...)
const fd = await SomeModel.findById(doc._id)
console.log(fd.fieldA) // prints null, 
```
Printing null is correct behavior according to mongoose documentation, because defaults only apply when the field value is strictly undefined, and here it is null. But that's not enough for my use cases, I want to be able to do:
```
const SomeSchema = mongoose.Schema({
   fieldA: { type: String, default: 'ABC' , runDefaultOnValues: [null, ''] }
})
// (...)

const doc = await SomeModel.create({ fieldA: null })
// (...)
const fd = await SomeModel.findById(doc._id)
console.log(fd.fieldA) // prints 'ABC'
```

**Comment by vkarpov15** [comment]
Ah ok, so this is a feature request to allow configuring the values Mongoose runs defaults for. We have a related issue already open, please follow #6849 for updates.
