### ISSUE TITLE
`timestamp` does not exist in `saveOptions` object for Model#save() that is used for Model.create

### ISSUE THREAD

**Issue by ekor15** [Automattic/mongoose#9280]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When using Model.create() `timestamp` does not exist in `saveOptions` object for Model#save() 

**If the current behavior is a bug, please provide the steps to reproduce.**
```node
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7960`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = Schema({ name: String }, { timestamps: true });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ name: 'test', createdAt: Date.parse('2011-10-10T14:48:00'), updatedAt: Date.parse('2019-12-12T11:11:11')  }, { timestamps: false });
  
  assert.equal(doc.createdAt.valueOf(), Date.parse('2011-10-10T14:48:00'));
  assert.equal(doc.updatedAt.valueOf(), Date.parse('2019-12-12T11:11:11'));
```

**What is the expected behavior?**
In this request, you approved that we should be able to set the timestamp fields on the doc creation
https://github.com/Automattic/mongoose/issues/7357

But I could not find it for the SaveOptions type
https://mongoosejs.com/docs/api.html#query_Query-setOptions

I tried it in save and it worked ( still needs to be added to type definition) 
I tried it in Model.create and got an error so I guess it was not added there

If I understand correctly create already creates the object
For the argument of best practices:
* I think an ORM should not require multiple calls just to bypass a recommendation it wants us to follow, its enough to explicitly enable this "unrecommended" behavior
* The updatedAt date value is undetermined it can be the createdAt date, but it might also be slightly newer than it
* This makes using mongoose harder for data migrations, 

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.9.20
Node: 12.16.1

**Comment by vkarpov15** [comment]
The issue is that you need to pass documents as an array to `Model.create()` if you want to use `options` as explained in the `Model.create()` docs: https://mongoosejs.com/docs/api/model.html#model_Model.create

```javascript
// This will work:
const doc = await Model.create([{ name: 'test', createdAt: Date.parse('2011-10-10T14:48:00'), updatedAt: Date.parse('2019-12-12T11:11:11')  }], { timestamps: false });
```

Also, https://mongoosejs.com/docs/api.html#query_Query-setOptions is the documentation for query options, **not** save options. You can read more about save options here: https://mongoosejs.com/docs/api/model.html#model_Model-save
