### ISSUE TITLE
How to use Aggregation in Dynamic References via `refPath`  for lookup.

### ISSUE THREAD

**Issue by h4mit** [Automattic/mongoose#9282]
How to use Aggregation in Dynamic References via `refPath`  as lookup?
What should I put instead of `from`  field in lookup ?
for exapmle :
```
const exampSchema = new Schema(
  {
    type: {
      type: String,
      required: true,
      enum: ['A', 'B', 'C']
    },
    items: [{
      type: Schema.Types.ObjectId,
      required: true,
      refPath: 'type'
    }],
  };

const ASchema = new Schema(
  {
    name: {
      type: String
    },
    exam:  {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Exam'
    }
  };
const BSchema = new Schema(
  {
    name: {
      type: String
    },
    exam:  {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Exam'
    }
  };
const CSchema = new Schema(
  {
    name: {
      type: String
    },
    exam:  {
      type: Schema.Types.ObjectId,
      required: true,
      ref: 'Exam'
    }
  };
```

What should I put instead of from ``field`` in lookup :
```
Exam.aggregate([{
  '$lookup': {
    from: '$type', // ??
    localField: 'items',
    foreignField: '_id',
    as: 'items'
  }
}]);
```

**Comment by vkarpov15** [comment]
Unfortunately there's no way to do this with `$lookup`, `$lookup`'s `from` option must be a string collection name. You would either need a separate aggregation for each of `'A', 'B', 'C'`, or a separate `$lookup` for each of `'A', 'B', 'C'`

**Comment by 1Ghasthunter1** [comment]
Anyone know of any work-arounds or other methods to go about this? I'm thinking about possibly merging all three collections into one and then using graphLookup (`from` is now the same collection), but this is intensive.

**Comment by vkarpov15** [comment]
@1Ghasthunter1 what exactly are you trying to do?

**Comment by 1Ghasthunter1** [comment]
@vkarpov15 Here's my SO post: 

https://stackoverflow.com/questions/73819352/how-to-graphlookup-with-dynamic-parent-references-in-mongoose

I ended up using an array of ancestors to do the trick

**Comment by tankotun** [comment]
I shared a easy way to handle this issue. [Check it out](https://dev.to/tankotun/dynamic-lookup-with-mongodb-aggregation-api-3333).

**Comment by ebosetalee** [comment]
@vkarpov15 is there a better way to achieve this using `$documents`?

**Comment by vkarpov15** [comment]
@ebosetalee I don't see how $documents would help here, but I haven't worked with $documents before so I can't be certain. Have you tried?

**Comment by ebosetalee** [comment]
@vkarpov15 I tried but it wasn't working for that use case as the documentation on $documents isn't for that purpose at all. Thanks
