### ISSUE TITLE
New 'text' index not created in mongo cloud (cluster)?

### ISSUE THREAD

**Issue by ajmas** [Automattic/mongoose#9285]
**Do you want to request a *feature* or report a *bug*?**

Bug, but probably user error

**What is the current behavior?**

We defined a text index on our previously existing schema, which allows us to do a search, when testing on non-clustered mongodb server locally. When we pushed to dev and connect to our existing DB in mongo cloud we get an error indicating that we need a text index, yet it is defined as so.

**If the current behavior is a bug, please provide the steps to reproduce.**

A slightly modified version of our code:

```typescript
interface IStoreDB extends IStore, Document {}

const storeSchema = new mongoose.Schema({
    name:{
        type: String,
        required:true,
        index: true
    },
    mobile: {
        type: String,
        required: false,
        unique: true,
        sparse: true,
        index: true
    },

}, {
    timestamps: true
});

storeSchema.index({ name: 'text', mobile: 'text' });

const model = createModel<IStoreDB>('Store', storeSchema);

export default model;
```

and the query:

```
const entries = await Store.find({ $text: {  $search: searchTerm } });
```

**What is the expected behavior?**

The index is added during application restart and we can do the `$text` search

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

 - node 12.16.2
 - mongoose@5.9.5
 - mongodb@3.5.5
 - mongodb server 4.2.8, as part of a replicated cluster in mongodb.com

**Comment by vkarpov15** [comment]
If you're running tests and dropping the collection/database between tests, make sure you do `await Store.init()` before using the text index: https://mongoosejs.com/docs/api/model.html#model_Model.init .

When you do `storeSchema.index({ name: 'text', mobile: 'text' });`, your index build happens in the background, so you need to wait for it to finish.

**Comment by Demi-ob** [comment]
To ensure it runs you can add `await storeSchema.ensureIndex()` to your before e.g 
```
before(async()=>{
    ...
    await storeSchema.ensureIndex()     
   ...
})
```

**Comment by vkarpov15** [comment]
@Demi-ob we recommend running [`syncIndexes()`](https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes) or `init()` as specified in this comment: https://github.com/Automattic/mongoose/issues/9285#issuecomment-665850188
