### ISSUE TITLE
"match" property in model gives inconsistent results

### ISSUE THREAD

**Issue by martinstanicio** [Automattic/mongoose#9287]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
(I am using [Insomnia](https://insomnia.rest))
I use a RegExp to validate a file path given by [`multer`](https://www.npmjs.com/package/multer).
The first time I send a request, it goes trough without errors, but if I send another one it throws a RegExp validation error (The request is the same, the filename is generated using `Date.now()`). The cycle repeats, you can see it more clearly like this:
```
request 1: 200 OK
request 2: 400 Bad Request
request 3: 200 OK
request 4: 400 Bad Request
...
```
(If I restart the server after each request I only get `200 OK`, but of course I cannot just restart the server in production)

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// models/data.model.js

import mongoose from "mongoose";

const DataSchema = new mongoose.Schema({
  myFile: {
    type: String,
    required: true,
    trim: true,
    match: /(([^\\/]*[\\/])*)([^\\/]+)$/g // I get consistent results if I remove this line
  }
});

export default mongoose.model("Data", DataSchema, "Data");
```

```javascript
// routes/data.js

import Data from "../models/data.model.js";
import express from "express";
import fs from "fs";
import multer from "multer";
import path from "path";
import { promisify } from "util";

const router = express.Router(),
  storage = multer.diskStorage({
    destination: (req, file, cb) => {
      cb(null, "./uploads/myFiles");
    },
    filename: (req, file, cb) => {
      cb(null, Date.now() + path.extname(file.originalname).toLowerCase());
    },
  }),
  unlinkAsync = promisify(fs.unlink),
  upload = multer({ storage: storage });

router.post("/", upload.single("myFile"), async (req, res) => {
  try {
    const newData = new Data({
      myFile: req.file.path,
    });
    await newData.save();
    res.status(200).json(newData);
  } catch (error) {
    if (error.errors) {
      unlinkAsync(req.file.path);
      res.status(400).json(error.errors);
    } else {
      unlinkAsync(req.file.path);
      res.status(500).json();
    }
  }
});

export default router;
```

```javascript
// app.js

// Imports
import "dotenv/config.js";
import dataRoute from "./routes/data.js";
import express from "express";
import mongoose from "mongoose";

// Constants and variables
const app = express(),
  db = process.env.DB || "mongodb://localhost/test",
  dist = express.static("dist"),
  port = parseInt(process.env.PORT) || 8080;

// Middlewares
app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Routes middlewares
app.use("/api/data", dataRoute);

// Set mongoose variables to avoid warnings
mongoose.set("useNewUrlParser", true);
mongoose.set("useFindAndModify", false);
mongoose.set("useCreateIndex", true);
mongoose.set("useUnifiedTopology", true);

// Connect to db
mongoose.connect(db, () => {
  console.log(`db connected to ${db}`);
});

// Start server
app.listen(port, () => {
  console.log(`server running on port ${port}`);
});
```

**What is the expected behavior?**
Consistent validation results (`200 OK` or `400 Bad Request` respectively)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Node.js:** 14.5.0
**Mongoose:** 5.9.25 
**MongoDB:** 4.2.8

**Comment by vkarpov15** [comment]
Thanks for pointing this out, turns out there's a bit of a gotcha with the `RegExp#test()` function when the regexp has the `g` option set. See the MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Examples

We implemented a fix, but you can work around this by removing the `/g` at the end of your RegExp. There's no need to ever use the `g` option with `match`.
