### ISSUE TITLE
Typescript issue in discriminator with Array

### ISSUE THREAD

**Issue by samirkatyar** [Automattic/mongoose#9292]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
Typescript error

**If the current behavior is a bug, please provide the steps to reproduce.**

no. i have used example from document https://mongoosejs.com/docs/discriminators.html#embedded-discriminators-in-arrays

**What is the expected behavior?**
should work.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js : 12.18.0
Mongoose : 5.6.6
MongoDB : 3.5.9

I copied this example from mongoose document which I mentioned in above answer (step to reproduce) but it seems not be working with typescript giving error that it does not exist on schema type ( and it should not be working as model method but in document example it has been used with schema type)

```
var eventSchema = new Schema({ message: String },
  { discriminatorKey: 'kind', _id: false });

var batchSchema = new Schema({ events: [eventSchema] });

// `batchSchema.path('events')` gets the mongoose `DocumentArray`
var docArray = batchSchema.path('events');

// The `events` array can contain 2 different types of events, a
// 'clicked' event that requires an element id that was clicked...
var clickedSchema = new Schema({
  element: {
    type: String,
    required: true
  }
}, { _id: false });
// Make sure to attach any hooks to `eventSchema` and `clickedSchema`
// **before** calling `discriminator()`.
var Clicked = docArray.discriminator('Clicked', clickedSchema);

// ... and a 'purchased' event that requires the product that was purchased.
var Purchased = docArray.discriminator('Purchased', new Schema({
  product: {
    type: String,
    required: true
  }
}, { _id: false }));

var Batch = db.model('EventBatch', batchSchema);
```
http://i.imgur.com/hicPVnV.png

**Comment by vkarpov15** [comment]
We do not currently have officially supported typescript types. Please open an issue here: https://github.com/DefinitelyTyped/DefinitelyTyped. Follow #8108 for updates.
