### ISSUE TITLE
Different validation error stringify for mongoose@^5.9.16

### ISSUE THREAD

**Issue by luizshigunov** [Automattic/mongoose#9296]
Prior to mongoose 5.9.16 stringify of a validation error returns:

{"errors":{"accountType":{"message":"Path \`accountType\` is required.","name":"ValidatorError","properties":{"message":"Path \`accountType\` is required.","type":"required","path":"accountType"},"kind":"required","path":"accountType"}},"_message":"Company validation failed","message":"Company validation failed: accountType: Path \`accountType\` is required.","name":"ValidationError"}

From mongoose 5.9.16 and beyond:

{"errors":{"accountType":{"properties":{"message":"Path \`accountType\` is required.","type":"required","path":"accountType"},"kind":"required","path":"accountType"}},"_message":"Company validation failed","message":"Company validation failed: accountType: Path \`accountType\` is required."}

There is no message or name for each error.

I'm using Express .json to serialize error and this is breaking my error handling.

Script to reproduce:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({
    name: { type: String, required: true },
    numAddresses: { type: Number, min: 1 }
  }));

  const doc = new Model({ numAddresses: 0 });

  const err = await doc.validate().catch(err => err);
  console.log(err.message); // Test validation failed: name: Path \`name\` is required., numAdd
  console.log(err.errors['name'].message); // Path \`name\` is required.
  console.log(err.errors['numAddresses'].message); // Path \`numAddresses\` (0) is less than minimum allowed value (1).
  console.log(JSON.stringify(err)); // No message for name or numAddresses
}
```

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in v5.9.27.
