### ISSUE TITLE
Bug in Update $set in a Map property

### ISSUE THREAD

**Issue by vvFiCKvv** [Automattic/mongoose#9298]
Given a schema:
```
  Country = new mongoose.Schema({
    cities: {
        type: Map,
        of: {
             population: {type: Number}
        }
    });
```

When 
`Country.updateOne({_id:""}, {$set: "cities.newyork.population": 10000} ).exec()`
throws Mongoose maps only support string keys, got undefined

Bypassing the mongoose works:
`Country.collection.update({_id:""}, {$set: "cities.newyork.population": 10000} )`
But it is missing schema validation.

By changing the mongoose/lib/schema/map.js function cast = (val, doc, init) => val it's working...
But I am not sure when this should be done in order to create a pull request(maybe when $__schemaType.path ends with ".$*").

P.S I can create a pull request with a failing test in order for anyone to investigate it more.

**Comment by vkarpov15** [comment]
Which version of Mongoose are you using? On Mongoose v5.9.26, the below script succeeds.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const CountrySchema = new mongoose.Schema({
    cities: {
        type: Map,
        of: {
             population: {type: Number}
        }
    }
  });
  const Country = mongoose.model('Country', CountrySchema);

  await Country.updateOne({}, { $set: { "cities.newyork.population": 10000 } }).exec()

  console.log('Done');
}
```

**Comment by vvFiCKvv** [comment]
Sorry for the late delay, I was in vacations,
I did a little more investigation and it has to do with child schemas and maps. 
It was difficult to pinpoint the problem exactly because our schema is complicated.
I should avoid using subschemas, for now, thank you for your involvement.

``it("should work with mongoose", async () => {

        const mongoose = require("mongoose");

        mongoose.set("debug", true);
        mongoose.set("useFindAndModify", false);


        await run();//.catch((err) => console.log(err));

        async function run() {
            await mongoose.connect("mongodb://localhost:27017/test", {
                useNewUrlParser: true,
                useUnifiedTopology: true
            });

            await mongoose.connection.dropDatabase();

            const CountrySchema = new mongoose.Schema({
                cities: {
                    type: Map,
                    of: {
                        population: { type: Number }
                    }
                }
            },
            { strict: "throw", useNestedStrict: true, _id: false, id: false }
            );

            const CountrySuperSchema = new mongoose.Schema({
                country: CountrySchema
            });

            const Country = mongoose.model("Country", CountrySuperSchema);

            let test = await new Country();
            test.save();
            await Country.updateOne({ _id: test._id }, { $set: { "country.cities.newyork.population": 10000 } }).exec();

            console.log("Done");
        }



    });
