### ISSUE TITLE
Mongoose Unable to connect using x509 Certificate.

### ISSUE THREAD

**Issue by RaresAil** [Automattic/mongoose#9300]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I get this error on mongoose.connect(...) but the whitelisted ip is on 0.0.0.0
`MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted.`

**If the current behavior is a bug, please provide the steps to reproduce.**
The url:
```
MONGO_URL=mongodb+srv://...mongodb.net/test?retryWrites=true&w=majority
```
```
const caFileBuf = fs.readFileSync(this.getAbsolutePath('security', 'mongo.pem'));
const mongoURL = process.env.MONGO_URL;
await this.mongoose?.connect(mongoURL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    ssl: true,
    user: 'CN=fastani,OU=fastani,O=Fastani,L=New York City,ST=New York,C=US',
    sslKey: caFileBuf,
    sslCert: caFileBuf,
    authMechanism: 'MONGODB-X509',
    authSource: '$external'
});
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`node: v14.4.0`
`MongoDB: 4.2.8 (MongoDB Atlas)`
`mongoose: ^5.9.27`

**Comment by vkarpov15** [comment]
Another possible cause of this error is that auth failed. Are you able to connect using these credentials using the `mongo` shell?
