### ISSUE TITLE
MongoDB connection error: MongooseServerSelectionError: connection timed out

### ISSUE THREAD

**Issue by elemikelo** [Automattic/mongoose#9308]
Hello,
when I launch the tests (unit and integration) in my project mongodb returns an error (_MongoDB connection error: MongooseServerSelectionError: connection timed out_).

My mongo configuration parameters are:
`mongoose.connect('mongodb://localhost:27017/my_db_name?replicaSet=rs0', {}) // without options`

**IMPORTANT:** The configuration of mongo is in replicat set but with a single cluster.

If I add the option 'use UnifiedTopology: false' the tests work correctly but it returns a warning of type: 'DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option **{ useUnifiedTopology: true }** to the MongoClient constructor.'.

In the latest version of mongoose it indicates that using UnifiedTopology is false by default.

Why do I have to add it manually?

Framework test: mocha v5.2.0
Node version: v10.19.0
MongoDB: v4.2.3
Mongoose:  v5.9.27

**Comment by isinkin** [comment]
I have the same problem, the temporary solution is to install mongoose@5.8.13

**Comment by elemikelo** [comment]
> I have the same problem, the temporary solution is to install mongoose@5.8.13

yes, I didn't have a problem with earlier versions either, it was when I upgraded to the latest version of mongoose

**Comment by vkarpov15** [comment]
Can you please explain what you mean by "the configuration of mongo is in replicat set but with a single cluster"? There isn't much we can do to debug this without more information.

**Comment by elemikelo** [comment]
I'm sorry, I meant a single node @vkarpov15

**Comment by CarlosCondor** [comment]
> Can you please explain what you mean by "the configuration of mongo is in replicat set but with a single cluster"? There isn't much we can do to debug this without more information.

I have the same problem. I think "single cluster" means "a replicaset with only one node", because this is the better way to be able to use transactions on local (because a replicaset is required)

**Comment by vkarpov15** [comment]
@CarlosCondor take a look at this section on replica set hostnames: https://mongoosejs.com/docs/connections.html#replicaset-hostnames . Often, replica set connection issues are due to your machine's `hostname` not matching the host name in the connection string you're passing to `connect()`.

**Comment by CarlosCondor** [comment]
> @CarlosCondor take a look at this section on replica set hostnames: https://mongoosejs.com/docs/connections.html#replicaset-hostnames . Often, replica set connection issues are due to your machine's `hostname` not matching the host name in the connection string you're passing to `connect()`.

I read that section. And tried with different hostnames and it doesnt' seems to be the problem. (Now i am using `127.0.0.1` as host).

Thanks for your reply

**Comment by vkarpov15** [comment]
Are you on OSX or Linux? And, if so, what is the output of running `hostname` from your terminal?

**Comment by CarlosCondor** [comment]
> Are you on OSX or Linux? And, if so, what is the output of running `hostname` from your terminal?

OSX. My hostname is `MacBook-Pro.local`

**Comment by vkarpov15** [comment]
Try using `mongodb://MacBook-Pro.local:27017` in your connection string, that may help.

**Comment by CarlosCondor** [comment]
> Try using `mongodb://MacBook-Pro.local:27017` in your connection string, that may help.

Doesn't work. Same error using  unifiedTopology:true

**Comment by vkarpov15** [comment]
That's strange. Can you print the error's `reason` property? That may explain what's happening:

```javascript
mongoose.connect('mongodb://localhost:27017/my_db_name?replicaSet=rs0', { useUnifiedTopology: true }).catch(err => console.log(err.reason));
```

**Comment by oshoomhaneme** [comment]
hi, im also having problems with connection  with localhost for mongo. it is saying:  
connection error MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri 
please what do i do?

**Comment by vkarpov15** [comment]
@oshoomhaneme please open a new issue and follow the issue template
