### ISSUE TITLE
(node:18519) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

### ISSUE THREAD

**Issue by PagesProgrammer** [Automattic/mongoose#9312]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @PagesProgrammer 

Please see our [deprecation warnings guide](https://mongoosejs.com/docs/deprecations.html), if that doesn't solve the issue you're facing, please open a new issue and follow the issue template.
