### ISSUE TITLE
self reference fields problem  

### ISSUE THREAD

**Issue by elahenikseresht** [Automattic/mongoose#9329]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by elahenikseresht** [comment]
it is impossible to change the fields that are self referenced after you get them from database.I used find method on a collection and after that I wanted to change a self referenced field of it (not in data base .just in the list that I received after I use find.)I couldn't.

**Comment by vkarpov15** [comment]
Please follow the issue template and provide detailed code samples, I don't understand this issue.
