### ISSUE TITLE
Model removeOne deletes multiple documents when a regular expression is used

### ISSUE THREAD

**Issue by michaeldacey** [Automattic/mongoose#9330]
Using the current versions of Mongoose and TypeScript @types/express.

Here is the simple code I used:
let result: { ok?:number, n?:number, deletedCount?:number };
connection = await this.MongodbConnection(dbname);
result = await KittenModel.deleteOne({ name: **new RegExp(req.params.name, 'i')** });
if(result.deletedCount == 1) console.log(`Removed the doc named: ${req.params.name}`);	
else console.log(`Failed to remove the doc named: ${req.params.name}`);

The results ok, n and deletedCount are incorrect e.g. they are all set to 1 when there is no document to delete.
I also discovered multiple documents were being deleted when they matched the regular expression.
All of these problems disappear if you replace the regular expression in the deleteOne() call as follows:
result = await KittenModel.deleteOne({ name: **req.params.name** });

I would have expected just one document to have been deleted in both cases.

**Comment by AbdelrahmanHafez** [comment]
The script below creates two users with the same name, deleting one with a regular expression, and is correctly deleting only one document.

Please modify the script below to demonstrate the issue you're facing.
### 9330.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');


run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: String
  });

  const User = mongoose.model('User', userSchema);

  await User.create({ name: 'Hafez' });
  await User.create({ name: 'Hafez' });

  const result = await User.deleteOne({ name: new RegExp('hafez', 'i') });

  assert.equal(result.deletedCount, 1);

  const remainingUser = await User.findOne({ name: 'Hafez' });
  assert.ok(remainingUser);
  
  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```

### Output
```
5.9.28
All assertions passed.
```
