### ISSUE TITLE
Error opening an already open connection

### ISSUE THREAD

**Issue by michaeldacey** [Automattic/mongoose#9331]
Using the current versions of Mongoose and TypeScript @types/express.

Opening a connection fails to return the Promise if the connection is already open.
Here is the my function:

async MongodbConnection(dbname: string): Promise<Connection>
{
	try
	{
		await mongoose.connect(`mongodb://mongodb:27017/${dbname}?authSource=admin`, {
		'useNewUrlParser': true,
		'useUnifiedTopology': true,
		'useFindAndModify': false,
		'useCreateIndex': true,
		'user': 'docker',
		'pass': 'password'
		});
	}
	catch(error)
	{
		throw error;
	}
	return mongoose.connection;
}

To fix this either close the connection before calling this function again or add a check to this function to ensure the connection is not open.

if(mongoose.connection.readyState !== 1)
{
	await mongoose.connect(`mongodb://webservice:27017/${dbname}?authSource=admin`, {
	'useNewUrlParser': true,
	'useUnifiedTopology': true,
	'useFindAndModify': false,
	'useCreateIndex': true,
	'user': 'docker',
	'pass': 'password'
	});
}

I would expect await mongoose.connect(...) to perform this check. Either it could throw an exception or close the existing connection then reopen it again.

**Comment by vkarpov15** [comment]
Sorry for the trouble, we'll ship a fix for this in v5.10.1 :+1:
