### ISSUE TITLE
[QUESTION] Poorly optimised query

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#9333]
**Do you want to request a *feature* or report a *bug*?**
It's more of a question, but if you want in between feature and bug, then it's a BUG

**What is the current behavior?**
According to mongodb atlas the queries are not optimised resulting in the following alert

>  **[Query Targeting](https://docs.atlas.mongodb.com/reference/alert-resolutions/query-targeting/#query-targeting): Scanned Objects / Returned has gone above 1000**

According to MongoDB Team, which means "Receiving a Query Targeting alert is often an indication that you have a poorly optimized query as a result of not using an index, or using an index that is not specific enough."

**What is the expected behavior?**
It should optimise the queries

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
+ MongoDB: 4.2.8
+ NodeJS: v14.5.0
+ Mongoose: 5.9.24

**Comment by AbdelrahmanHafez** [comment]
The message showing up is saying that the queries running are scanning more than 1000 documents for each document returned, to fix that you want to add indexes on the fields you query the most, and are as unique as possible.

Read more on [MongoDB indexes](http://thecodebarbarian.com/when-should-you-use-mongodb-indexes.html) .

**Comment by tbhaxor** [comment]
@AbdelrahmanHafez I naive question.. SHUD I BE WORRIED FOR THIS WARNING?

**Comment by AbdelrahmanHafez** [comment]
@tbhaxor It's telling you that the performance is slow and can be improved, so your application will be slowed down, it really depends on how fast you need your app to be.
