### ISSUE TITLE
How do I update a document that is also the result of findOneAndUpdate/updateMany

### ISSUE THREAD

**Issue by jnardone** [Automattic/mongoose#9334]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure if this is a feature or bug or a "you can't".  So, I'd say this is probably a documentation bug, because the docs around middleware hooks is really hard to decipher.  There's no real explanation of the specific calls or sequences and how they affect the result handling to the client.  

**What is the current behavior?**
First my goal: I am updating a document.  The code paths are either `.updateMany` or `.findOneAndUpdate`.  These updates should trigger *further* updates based on the data.

These calls can happen from a number of places so I wanted to do this in one place with Mongoose hooks.

For example's sake, let's say the new data includes a parent ID as part of an array.  As part of the update, I want to compute a list of parents for all items in the array and store it.

I can't do this in a `pre` hook, because the updateMany/findOneAndUpdate hasn't happened yet.

I can do these in `post` hooks, because I can requery the data and update it, but the problem is: this does NOT change the results returned to caller from .updateMany/.findOneAndUpdate.

Basically, I want to fire these updates as part of the set of calls to Mongo before data is returned to the caller.  Is there a way for me to replace the payload returned from .updateMany/.findOneAndUpdate in a `post` hook?  The docs talk about using populate in a post hook, but apparently only for doc middleware.  For query middleware how can I change the returned data from the call?

Right now I've got code that looks something like this.  Note that `populateAllParents` requires information that is in the actual update to be calculated; it is not already in the document at the `pre` phase.

```
// fix assignment parents on create, and gets triggered by all post hooks
schema.pre('save', function (next) {
  // this is document middleware; `this` is the document
  populateAllParents(this);  // this fixes the array and sets all the parents
  next();
});

// MY PROBLEM IS FROM HERE ON - I want the data these hooks change to be reflected in the data back to the caller
// without making additional calls from the client.  e.g. if the client calls `findOneAndUpdate` the resulting document
// should INCLUDE the changes made by this call.  

schema.post('findOneAndUpdate', async function (result) {
  const docToUpdate = await this.model.findOne(this.getFilter());
  await docToUpdate.save();
});

schema.post('updateOne', async function (result) {
  const docToUpdate = await this.model.findOne(this.getFilter());
  await docToUpdate.save();
});

schema.post('updateMany', async function (result) {
  const docsToUpdate = await this.model.find(this.getFilter());
  docsToUpdate.forEach(async (doc) => {
    await doc.save();
  });
});
```

Can this be done?  

Node: 12.19
Mongoose: 5.9.27

**Comment by vkarpov15** [comment]
Sorry we missed this issue when it was first reported.

Mongoose doesn't let you replace the entire result of a query, but you can modify the result in place. For example:

```javascript
  const schema = new Schema({ name: String, otherProp: String });
  schema.post('findOneAndUpdate', function(result) {
    result.init({ name: 'other name' });
  });

  const Test = mongoose.model('Test', schema);

  await Test.create({ name: 'test' });
  console.log(await Test.findOneAndUpdate({}, { name: 'test2' }, { new: true }));
```

This is a bit trickier for `updateOne()` and `updateMany()`, since the result of those functions is a command result. But you can always do something like `result.doc = docToUpdate`. See [`Document#init()` docs](https://mongoosejs.com/docs/api/document.html#document_Document-init).
