### ISSUE TITLE
Default value not populated on nested object, even with setDefaultsOnInsert flag set to true

### ISSUE THREAD

**Issue by anatoly314** [Automattic/mongoose#9338]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
default field not populated even with`setDefaultsOnInsert` flag
**If the current behavior is a bug, please provide the steps to reproduce.**

- User model:
```
const UserSchema: Schema = new Schema({
    phone: {
        type: String,
        required: true
    },
    name: {
        type: String,
        required: false
    },
    authCode: {
        value: String,
        createdAt: Date,
        loginAttempts: {
            type: Number,
            default: 0
        }
    }
});
```
- Invocation:
```
const filter = {
            phone: phone
        };
        const update = {
            authCode: {
                value: AuthCodeGenerator(),
            }
        };
        const options = {
            new: true,
            upsert: true,
            setDefaultsOnInsert: true
        };
        const user = await this.UserModel.findOneAndUpdate(filter, update, options).lean().exec();
        return user;
```
**What is the expected behavior?**
`loginAttempts` should be populated with 0
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- mongoose v5.7.32
- node v14.5.0
- mongodb 4.2.2

**Comment by anatoly314** [comment]
It looks that it's related to this issue, still investigating: https://github.com/Automattic/mongoose/issues/5606

**Comment by anatoly314** [comment]
Ok, it isn't a bug but a feature:

> Using lean() bypasses all Mongoose features, including virtuals, getters/setters, and defaults. If you want to use these features with lean(), you need to use the corresponding plugin

More details can be found here: https://mongoosejs.com/docs/tutorials/lean.html

**Comment by vkarpov15** [comment]
Expected behavior, `lean()` skips defaults for perf. Use [mongoose-lean-defaults](https://www.npmjs.com/package/mongoose-lean-defaults) if you need defaults while using lean.
