### ISSUE TITLE
Alias for nested keys

### ISSUE THREAD

**Issue by AdityaGupta150** [Automattic/mongoose#9341]
_Feature Request_

**Current behavior**
We can not use 'alias: 'something', if the key has nested paths. Though we can set a virtual with the same name, to have it behave as if it has the alias.

[Gist link (Standalone)](https://gist.github.com/AdityaGupta150/3d0e1275ad039756f4cde996ff396801) (please use the aliasIssue.js file).

**Expected behavior**
From https://mongoosejs.com/docs/guide.html#aliases
> Aliases are a particular type of *virtual* where the getter and setter seamlessly get and set another property

Here having an alias gives a TypeError, don't know why a TypeError though.
*Use Case* -> As above if both the parent key, and nested paths, have long names, it just makes it easier to have an alias for an existing property, rather than a virtual for same maybe

In the linked [gist](https://gist.github.com/AdityaGupta150/3d0e1275ad039756f4cde996ff396801), 
> instead of 
> alias: 'boss',    //alias for 'b'
> we can use...
> trial.virtual('boss').get(function(){return this.b})  //works good even if nested paths have aliases

> **Versions**
> node - 14.4.0
> MongoDB shell version v4.2.8
> mongoose - 5.10.0

**Comment by vkarpov15** [comment]
Mongoose doesn't currently support setting options on nested paths, because they aren't schema types. Follow #7408 for updates on that.

As a workaround, try the below instead:

```javascript
const trial = new Schema({
     a: {
         alias: 'b',
         type: new Schema({
           b1: { type: String },
           b2: { type: String}
         }, { _id: false })
     }
 });
```
