### ISSUE TITLE
Duplicate entries with same values, for a unique key

### ISSUE THREAD

**Issue by AdityaGupta150** [Automattic/mongoose#9342]
_BUG Report_

**Current Behavior**
Category schema with a name field, with unique: true.
But, multiple documents, with same value of 'name' field can be seen. 

**Steps to Reproduce**
1. Run the [duplicateKeyIssues.js file, from the gist](https://gist.github.com/AdityaGupta150/3d0e1275ad039756f4cde996ff396801)
> By now, the code outside any request handler runs, and sometimes creates duplicates, but mostly not, if so, proceed please
2. Run `curl http://localhost:3000/post`
3. Run `curl http://localhost:3000/delete`, then `curl http://localhost:3000/post`
...Keep repeating step 3, the console will be having multiple 'Created Category' logs each time, showing multiple entries with same name field have be pushed to db

**What is the expected behavior?**
No duplicates should have been pushed.
This is a bug i faced when using express.js server, and multiple categories being created by the pre 'save' hook

> Sir, i think looking through the console logs, after the 3 steps is enough to get the problem, the request method is GET method for all routes, by choice.

> **Routes** -> '/' : Returns categories in database
>                 '/post': Try to creates pre-defined todos
>                 '/delete': ** ⚠️ Drops the database ⚠️ The database name will be 'DUPLICATE15' (on line 14) **

> **Versions**
> node - 14.4.0
> MongoDB shell version v4.2.8
> mongoose - 5.10.0

_SampleOutput_
> received post request
> ℹ Going to create collection with name:  something
> ℹ Going to create collection with name:  something
> ℹ Going to create collection with name:  something
> {name: something }  count = 0
> 🎉  Created category:  something
> 🎉 Created category:  something
> {name: something }  count = 2
> {name: something }  count = 2
> 🎉 Created category:  something 

The multiple created category log shows there is a problem.
Also, do suggest if there's a problem in the way i have done the queries, or please do suggest a fix for it for now.

**Comment by anatoly314** [comment]
Didn't try your code, but maybe some suggestions here will help you? https://stackoverflow.com/questions/5535610/mongoose-unique-index-not-working

**Comment by AdityaGupta150** [comment]
**Update** - It is solved now, the problem likely lies in dropping the database.

From https://masteringjs.io/tutorials/mongoose/unique
>  If you drop the database the User model is connected to, you'll also delete the unique index, **and you will be able to save duplicates.**

So, **instead of using `dropDatabase()` at the /delete route, used `deleteMany({})`, to preserve the index**

_But, Is it by design that mongoose/mongo doesn't create unique index for the database, after the database is dropped, and just before we use `Model.create()`_ ?

**Comment by AdityaGupta150** [comment]
> 
> 
> Didn't try your code, but maybe some suggestions here will help you? https://stackoverflow.com/questions/5535610/mongoose-unique-index-not-working

Tried the suggestions but to no help, since, restarting mongo or mongod didn't help, nor enforcing unique index (which was likely due to the reason dropping the database removed the index). 😄

**Comment by vkarpov15** [comment]
@AdityaGupta150 you're right, the problem is with dropping your database. Dropping the database deletes all indexes, including the [unique index](https://masteringjs.io/tutorials/mongoose/unique). If you want to delete all todos, your delete endpoint should use `todoModel.deleteMany()` and `categoryModel.deleteMany()` instead of dropping the whole database.
