### ISSUE TITLE
Getters for populate virtuals

### ISSUE THREAD

**Issue by NikoFoX** [Automattic/mongoose#9343]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Current populate virtual doesn't allow you to assign foreign object's field value as a virtual's returned value.

Currently doing:

```js
const gameSchema = Schema({
      title: String,
});

const matchSchema = Schema({
      game: ObjectId,
});

matchSchema.virtual('gameTitle', {
      ref: 'Game',
      localField: 'game',
      foreignField: '_id',
      justOne: true,
      options: {select: {'title': 1}}
});
```
and returning populated Match gives:

```js
{
      _id: 'some_match_id',
      gameTitle: {
            _id: 'some_game_id',
            title: 'some_game_title'
      }
}
```

**What is the expected behavior?**
Same virtual should return Match object with gameTitle as String with current Game title.

```js
{
      _id: 'some_match_id',
      gameTitle: 'some_game_title'
}
```

I'm also wondering why the `select` option results in returning both selected field and _id field and not the field alone.

**Comment by vkarpov15** [comment]
The reason why `_id` is there is that `_id` is included by default, and Mongoose needs `_id` to match up the `Game` to its corresponding `Match`. Any other properties in `gameSchema` will be excluded.

The `gameTitle: 'some_game_title'` output is not something we support. Virtual populate always sets `gameTitle` to a Mongoose document, we don't currently support transforming the document into a string.

We'll keep this open for a future feature suggestion. I'm thinking we can add support for something like this:

```javascript
matchSchema.virtual('gameTitle', {
      ref: 'Game',
      localField: 'game',
      foreignField: '_id',
      justOne: true,
      options: {select: {'title': 1}},
      set: doc => doc.title
});
```

Would that work for you @NikoFoX ?

**Comment by NikoFoX** [comment]
Shouldn't it be get instead of set? Analogically to schema path getters. 
That would work for me very much.

**Comment by vkarpov15** [comment]
`get` sounds better, thanks for the suggestion, we'll go with that.
