### ISSUE TITLE
Set debug mode via NODE_ENV or other environment variable

### ISSUE THREAD

**Issue by minicacristi** [Automattic/mongoose#9344]
I am using the latest version of mongoose as of now, 5.10.0, Node 10, MongoDB 4. I am setting the node process in debug mode via environment variable but mongoose must be set programmatically. This is now what I expected.
I must add:

```
if (process.env.NODE_ENV !== 'production') {
  mongoose.set('debug', true)
}
```
I am not the only one that had issues with this (https://github.com/Automattic/mongoose/issues/9206), it appears to be an inconsistency.

Am I missing something? Are there any legitimate reasons for this decision?

I would gladly provide a fix for this.

**Comment by vkarpov15** [comment]
The reason is that we believe frameworks shouldn't be configured by NODE_ENV. Too much potential for unfortunate surprises when deploying to production. If you want to add this behavior, easy to drop in 3 lines of code to set `debug` based on any environment variable you'd like.

**Comment by minicacristi** [comment]
Thank you for your answer! Can you elaborate on how there is "too much potential for unfortunate surprises when deploying to production", who? There is already a debug feature(this can also lead to surprises by this logic) and express is using this pattern without creating mayhem. I find value in patterns and common practices. A lot of users are already using mongoose with express. If this discussion already happened can you please link it here?

**Comment by vkarpov15** [comment]
Needing to set `NODE_ENV` to disable debug mode is a problem for people who don't use environment variables. There's less potential for surprises when you explicitly need to write out `mongoose.set()` in your code.

**Comment by minicacristi** [comment]
True, but I was not advocating to be mandatory, just to be an option. If mongoose finds that specific env var, it will set debug mode internally. Nothing fancy imho.
