### ISSUE TITLE
Interprocess transactions

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9346]
**Do you want to request a *feature* or report a *bug*?**
More like help
**What is the current behavior?**
Hi, I've a function that uses sessions for a transaction that consumes several resources, for now I serialize the operation to avoid overload the process. 

Is there a way to send the session as JSON to use PUB/SUB and send to other processes to accomplish parts of the transaction but preserving the transaction? so If a part of the transaction fails I could abort the transaction?

Maybe hydrating with some plain data?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Be able to convert session to JSON so I could send it to other process to execute part of the transaction.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose: 5.10.0
node 14.8
mongodb 4.2

**Comment by vkarpov15** [comment]
Unfortunately I don't know of a way to share a transaction between multiple processes. It may be possible: sessions and transactions have an id, so if you could share that id you might be able to abort the transaction from different processes. We'll need to investigate more.

Can you please elaborate a bit more about your use case?

**Comment by chumager** [comment]
Hi, I use to work with IPC and PUB/SUB to balance the task between my servers and process, so for example I've a voucher related with some investments, the investments have some documents who must be recreated when I change the voucher, that's a heavy task with some sync operations.

I've a voucher **pre save hook** with transactions to do this. but if I've several investments for the transaction I can't execute the documents update in parallel because I can even get out of memory, but it's a one shot task, so my other processes are doing nothing and my other servers the same.

One option it's to unlink the document creation process from the Investment model to a woker thread, but even the document created is in the database, so I can be creating documents and my transaction fails and I'll get documents not related with investments, and this doesn't allow to work with other servers neither. Besides all that the investment is changed inside a transaction so the document creation can't read the changes until the transaction is finished.

I remember have read sessions are connection related, if that's the case there is nothing to do. The mongodb driver doesn't expose the ClientSession class AFAIK, and it seems the id is assigned with a `Symbol` so it's not possible to change that by hand.

It'll be something interesting to accomplish but I wouldn't put all my coins on it, seems the driver doesn't allow it.

Regards.

**Comment by vkarpov15** [comment]
I don't quite understand your use case, but I took a closer look and I don't think MongoDB supports interprocess transactions. You'd need a way to serialize and then re-hydrate a transaction, which isn't possible since the MongoDB driver doesn't have a publicly-facing `Transaction` class. The only way to create a transaction is via `session.startTransaction()`.

In theory, it may be possible in the future, because it looks like you can use the same session on different connection pools as shown below:

```javascript
run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));
  await Model.createCollection();

  const session = await mongoose.startSession();
  session.startTransaction();

  await Model.create([{ name: 'foo' }], { session });

  const conn = await mongoose.createConnection('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  const Model2 = conn.model('Test', Schema({ name: String }));
  const session2 = await conn.startSession();

  const obj = Object.assign({}, session);
  delete obj.topology;
  delete obj.sessionPool;
  delete obj.clientOptions;
  
  Object.assign(session2, obj);

  // Prints the document
  console.log(await Model2.findOne().session(session2));

  await session.commitTransaction();
  process.exit(0);
}
```

**Comment by chumager** [comment]
That's exactly what I thought, I'll talk with mongodb team to tell them the problem to convince them to change the session behavior, hopefully before I've to implement the project I'm working on.

Thanks...
