### ISSUE TITLE
updated model with array is modified even there is no new data

### ISSUE THREAD

**Issue by gameatrix** [Automattic/mongoose#9347]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

If a run updateOne with $set and upsert:true on a model containing an array i always get { n: 1, **nModified: 1**, ok: 1 } back regardless if the data has been changed each and every time i run it.

If i run the same query but without the array i get { n: 1, **nModified: 0,** ok: 1 } back each and every time i run it.

This indicates to me that the update has modified the existing data but only if there is an array present? Is this by design and why is this so, or is it a bug?

Its hard to explain so i created a reproduction repo for it. 
**https://github.com/gameatrix/mongo_array**

**What is the expected behavior?**
In both cases it should return  { n: 1, nModified: 0, ok: 1 } as no data has been modified.

**Versions**
mongoose : "^5.10.0"
node: v10.13.0
MongoDB shell version v4.2.8

**Comment by vkarpov15** [comment]
This happens because your `stores` array subdocuments implicitly have an `_id` field. Change your product schema to the below and it should work as expected.

```javascript
const ProductSchema = new Schema({
  productName: String,

  stores: [
    new Schema({
      name: String, 
    }, { _id: false }),
  ],
});
```
