### ISSUE TITLE
Schema becomes undefined when applying a plugin which uses imports from the same file

### ISSUE THREAD

**Issue by vinerich** [Automattic/mongoose#9349]
**Do you want to request a *feature* or report a *bug*?**

Possible bug

**What is the current behavior?**

Hey folks,
at first, I know the title is a little .. unspecific, I didn't know how to better break it down so let me explain.

I'm trying to write a custom plugin to synchronize 2 collections. So of course I need to import the schema of the collection to synchronize in my plugin to issue the update-commands.

#### Setup
Now to the interesting part. My project structure was as follow
- helpers
  - mongo-synchronize-plugin.ts
- dbs
    - mongodb
      - index.ts
      - detail.ts
      - master.ts

In `dbs/index.ts` I do the following
```js
export * from "./master";
export * from "./detail";
```

My plugin looks roughly like this (I can give a more detailed view if requested)

mongo-synchronize-plugin.ts
```js
import { MasterSchema } from "@/dbs/mongodb";

const plugin = function (schema: Schema) {

    schema.pre('save', function (next) {
        synchronize(this).then(() => next()).catch(next);
    })

    async function synchronize(document: Document) {
        const updateObject = getDifferences(document);
        return saveToMaster(document, updateObject);
    }

    async function saveToMaster(document: Document, updateObject: Object) {
            return MasterSchema.updateOne(
                { _id: document.ref.ObjectID },
                { $set: updateObject },
                {
                    arrayFilters: [{ "elem.serial": { $eq: document.serial } }],
                    runValidators: true,
                }
            ).exec()
        }
    }
}
```

Plugin is applied as follow
detail.ts
```js
// Define DetailSchema and IDetail

DetailSchema.plugin(plugin);
const detail = mongoose.model<IDetail>("Detail", DetailSchema);
```

#### Issue
Using `detail.findOne()` I now get
```js
TypeError: Cannot read property 'findOne' of undefined
```

If i change the import in `plugin.ts` from
```js
import { MasterSchema } from "@/dbs/mongodb";
```
to
```js
import { MasterSchema } from "@/dbs/mongodb/master";
```
everything works.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I expected mongoose to fail in one of the following lines if something is going wrong while applying the plugin
```js
DetailSchema.plugin(plugin);
const detail = mongoose.model<IDetail>("Detail", DetailSchema);
```

Else I'm just a little lost or maybe my knowledge about js/ts import/export mechanism is too low to understand what's the issue here.

If anything in this issue is too unspecific just leave a command and I'll try to reword it or to include more information.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

-Node: v12.18.0
-Mongoose: 5.10.0
-MongoDB: 4.2.5 Community

**Comment by vkarpov15** [comment]
I suspect this is due to a cyclical import. When you do `import { MasterSchema } from "@/dbs/mongodb";` in `detail.ts`, you're also importing `detail.ts`. In Node.js, when you do a cyclical import, you get an empty object, so `MasterSchema` will be `undefined`.

There's no good way for Mongoose to fail when applying the plugin if there's a bug in a hook the plugin registers.

Also, please change `import { MasterSchema } from "@/dbs/mongodb";` to `import { Master } from "@/dbs/mongodb/master";` or `import { MasterModel } from "@/dbs/mongodb/master";` . The `master.ts` file exports a [model](https://mongoosejs.com/docs/models.html), **not** a [schema](https://mongoosejs.com/docs/guide.html).
