### ISSUE TITLE
Default functions and 'this'

### ISSUE THREAD

**Issue by ScottWager** [Automattic/mongoose#9351]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have a key in my Schema that uses the default function to use `this`. When `type` is an array, `this` only includes default values of some of the keys:

**If the current behavior is a bug, please provide the steps to reproduce.**

```
authors: {
    default: function () {
        console.log(this);
    },
    type: [mongoose.Schema.Types.ObjectId],
},
```

Logs to console an object with only keys that have a default value

vs

```
authors: {
    default: function () {
        console.log(this);
    },
    type: mongoose.Schema.Types.ObjectId,
},
```

Logs to console an object that includes the keys that I'm setting in my 'createCourse' route
```
const course = await Course.create({
    title: req.body.title,
    publisher: req.account._id,
});
```

`**What is the expected behavior?**

Should have access to `this.publisher` when using an array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 14.7.0
Mongoose: 5.10.0
MongoDB: 4.2.3

I love mongoose, thanks for the great work!

**Comment by Eduwardo** [comment]
version 6.0.8 still have this problem, default function is running before the setters

**Comment by vkarpov15** [comment]
@Eduwardo please open a new issue and follow the issue template
