### ISSUE TITLE
Annotations for mongoose

### ISSUE THREAD

**Issue by junaid1460** [Automattic/mongoose#9353]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
None

**If the current behavior is a bug, please provide the steps to reproduce.**
None

**What is the expected behavior?**
It'll be great if mongoose provides decorators like this internally.
I just drafted my version here check this out
https://github.com/junaid1460/mongoose-annotations

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
latest

**Comment by vkarpov15** [comment]
We will consider this as part of our initiative for improved TypeScript support (#8108)

**Comment by vkarpov15** [comment]
Thanks for the suggestion. I agree re: decorators not being standardized yet, so we can close this for now.
