### ISSUE TITLE
No type checking with .new() method

### ISSUE THREAD

**Issue by raph90** [Automattic/mongoose#9354]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
Currently when a new document is instantiated with .new(), there is no type checking with Typescript. 

**What is the expected behavior?**
In the index.d.ts for mongoose the new method is written thus:
`new(doc?: any): T;`
while the create method is like this:
`create<TCreate = T>(doc: CreateQuery<TCreate>, options?: SaveOptions): Promise<T>;`

This means that when I create a new document with .new() there is no type checking, but with .create() there is. 

This may not be a bug per se, but I'm wondering why we don't have `new(doc: T): Promise<T>` or something equivalent for the new method.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.10, types are 5.7.36

**Comment by vkarpov15** [comment]
We don't currently have officially supported TypeScript definitions, you would have to open an issue with @types/mongoose. Follow #8108 for updates.
