### ISSUE TITLE
Upgrade @types/mongodb to 3.5.26

### ISSUE THREAD

**Issue by pbadenski** [Automattic/mongoose#9356]
There's been a number of type fixes and at least one feature (`compression` option) since current 3.5.3 packaged with mongoose.

**Comment by vkarpov15** [comment]
It would be hard for us to upgrade @types/mongodb since we don't have a dependency on @types/mongodb to begin with.

**Comment by pbadenski** [comment]
haha, thanks, I meant to report that for TypeScript definitions which now I realise live in DefinitelyTyped ;)
