### ISSUE TITLE
The updatedAt field is not correctly updated for nested documents.

### ISSUE THREAD

**Issue by gonuit** [Automattic/mongoose#9357]
### Bug
I'm not sure if provided examples are bugs, but these behaviors are unclear for me. 

1. Let's imagine database schemas which looks like that (`timestamps: true` is set for both schemas):
```js
/// NestedSchama
{
  nestedA: { type: String },
  nestedB: { type: String },
}

/// MainSchema
{
  content: {
     a: { type: NestedSchama },
     b: { type: NestedSchama },
     c: { type: String }
  }
}
```
### Case 1
```js
const model = Main.findOne({});
model.content.a.nestedA = "test";
model.save();
```
#### Current behavior.
This will update `updatedAt` value for **MainSchema**, **NestedSchama a** and **NestedSchama b**. 
#### Expected behavior.
`updatedAt` field is being updated for **MainSchema** and **NestedSchama a** (**NestedSchema b** values weren't modified at all - no need for timestamps change).
#### Thoughts.
I believe that this is because `content`, `content.a` and `content.a.nestedA` are marked as modified 🤔?

### Case 2
```js
const updatedModel = Main.findOneAndUpdate({
  c: "value",
  $set: {
    'content.a.nestesA': "value",
  }
}, { new: true });
```
#### Current behavior.
`updatedAt` field is updated **only** for **MainSchema** while **NestedSchama a** was modified too.
#### Expected behavior.
`updatedAt` field is being updated for **MainSchema** and **NestedSchama a**.
#### Thoughts.
Moving all values to `$set` operator resolves problem 🤔.
```js
const updatedModel = Main.findOneAndUpdate({
  $set: {
    c: "value",
    'content.a.nestes_a': "value",
  }
}, { new: true });
```

### Case 3
```js
const updatedModel = Main.findOneAndUpdate({
  c: "value",
  $set: {
    'content.a': { nestedA: "value", nestedB: "value" }, 
  }
}, { new: true });
```
#### Current behavior.
`updatedAt` field is updated **only** for **MainSchema** while **NestedSchama a** was modified too.
#### Expected behavior.
`updatedAt` field is being updated for **MainSchema** and **NestedSchama a**.
#### Thoughts.
Providing all values separately resolves problem:
```js
const updatedModel = Main.findOneAndUpdate({
  c: "value",
  $set: {
    'content.a.nestedA': "value", 
    'content.a.nestedB': "value",
  }
}, { new: true });
```

### Versions:
- **Mongoose**:  `5.10.0`
- **Node.js**: `10.x` / `12.x` / `14.x`

**Comment by vkarpov15** [comment]
Fixed all 3 cases, fix will be in 5.10.2 :+1:

**Comment by gonuit** [comment]
Hi @vkarpov15,
Thanks for the quick action, you rock! 💪 🔥 

I also found another bug/bugs with this database structure. I'll leave it here instead of creating a new problem (maybe you fixed it too).

***

When record exists in the database (with the same schema as in topic) and looks like that:
```json
{
  "_id": "<ObjectId>",
  "content": {
    "a": {
      "_id": "<ObjectId>",
      "nestedA": "data",
      "nestedB": "data",
      "createdAt": "<Timestamp>",
      "updatedAt": "<Timestamp>"
    }
  },
  "createdAt": "<Timestamp>",
  "updatedAt": "<Timestamp>"
}
```
We want to insert "b" by calling `findOneAndUpdate`:
```ts
const updatedModel = Main.findOneAndUpdate({ _id: "some_object_id" }, {
  $set: {
    'content.b.nestesA': "data",
    'content.b.nestesB': "data",
  }
}, { new: true });
```
The update model will look as follows:
```json
{
  "_id": "<ObjectId>",
  "content": {
    "a": {
      "_id": "<ObjectId>",
      "nestedA": "data",
      "nestedB": "data",
      "createdAt": "<Timestamp>",
      "updatedAt": "<Timestamp>"
    },
    "b": {
      "_id": "<ObjectId>",
      "nestedA": "data",
      "nestedB": "data",
      "updatedAt": "<Timestamp>"
    }
  },
  "createdAt": "<Timestamp>",
  "updatedAt": "<Timestamp>"
}
```
#### Current behavior.
As you can see `createdAt` field is not created.
Every `find` call will return record with other value (`_id`) for path `content.b._id`.

#### Expected behavior.
`createdAt` and `updatedAt` fields are created because `NestedSchema` is created.
The value "_id" is fixed.


#### Funny part 🤡 .

573/5000
Then I realize that ... maybe for now ... I will be able to declare the `createdAt` field by declaring the` createdAt` field with the default value set to` () => new Date () `for **NestedSchema**. And you know what? 😄 Works **BUT** partially. The **createdAt** field is returned by the `find` methods, but is not saved to the database (so it always returns the current timestamp). An additional "save" call will do nothing. After marking `content.a.createdAt` as modified, the field will be saved to the database, but I will still get a new` _id` for every `find`.

**Comment by vkarpov15** [comment]
@gonuit unfortunately I don't think there's anything we can do about that issue for now, there isn't a [field update operator](https://docs.mongodb.com/manual/reference/operator/update-field/) we can use to capture the case where we should only set `content.b.createdAt` if `content.b` doesn't already exist.

If you need `createdAt` timestamp to kick in, I'd recommend explicitly creating `content.b`:

```javascript
const updatedModel = Main.findOneAndUpdate({ _id: "some_object_id" }, {
  $set: {
    'content.b': { nestedA: 'data', nestedB: 'data' } 
  }
}, { new: true });
```

Or using `.save()` instead of `findOneAndUpdate()`.
