### ISSUE TITLE
.populate() + .batchSize() + .cursor() works one by one

### ISSUE THREAD

**Issue by yadimon** [Automattic/mongoose#9365]
### Bug:

same as by http://disq.us/p/1zwzgzi
if you query something with populate + batchSize + cursor, the mongoose makes **only one request per item**.

### Example:
e.g. MyItems is any docs collection with some 'subDoc' ids.

```
MyItems.find({}).populate('subDoc').batchSize(1000).cursor();
```

if i remove the `populate()` part, it queries with batch as expected.

**Comment by biomorgoth** [comment]
I have just made a feature that could solve this by reading the batch and populating the batch documents in a single roundtrip.

Please read and comment on the #9366 to see if that suits your needs. I've just got into the same issue and thought of that approach.

**Comment by biomorgoth** [comment]
Researching a little more, i found this has been discussed in the past (see #3683). It would be nice that @vkarpov15 could take a look at the solution to see if he likes the idea behind it.
