### ISSUE TITLE
How to save form-data that contains array in Mongoose?

### ISSUE THREAD

**Issue by AbuUbaida** [Automattic/mongoose#9368]
I have a model containing an array like this:
`const schema = new mongoose.Schema({
path: {
    type: String
},
list: [{
    element1: {
        type: Number
    },
    element2: {
        type: Number
    }
}]})`

In the route file:
`const prescription = new Prescription({
    ...req.body,
    path: req.file.path
})`

What I want to use POST request to get this model data via form-data. And that looks like:

![postman](https://user-images.githubusercontent.com/39676946/91527881-7048bc00-e928-11ea-8398-1a61ee4c9c36.PNG)

Saved that model using: `prescription.save()`
Unfortunately what I get response (It doesn't contain the array elements):

![postman2](https://user-images.githubusercontent.com/39676946/91527997-a128f100-e928-11ea-8020-8a519eb54618.PNG)

If I log in console with: `console.log(req.body)`
It shows:
![vscode](https://user-images.githubusercontent.com/39676946/91528075-c74e9100-e928-11ea-957e-25816a40760c.PNG)

And for: `console.log(req.body.list)`
It returns `undefined`

**Please let me know how to get that response with array elements successfully?**

**Comment by wong2** [comment]
This has nothing to do with mongoose, it's the problem with your HTTP request handling

**Comment by vkarpov15** [comment]
Mongoose doesn't support the square bracket syntax `list[0].element1`, you need to do `list.0.element1`. Or, better yet, `list: [{ element1: 1 }]` as @wong2 suggested.

**Comment by vkarpov15** [comment]
AFAIK this has nothing to do with [JavaScript's FormData class](https://masteringjs.io/tutorials/fundamentals/formdata), that isn't how FormData serializes arrays.

**Comment by AbuUbaida** [comment]
okay thanks for your support @vkarpov15  @wong2
