### ISSUE TITLE
Text indexes get recreated on .syncIndexes()

### ISSUE THREAD

**Issue by aletorrado** [Automattic/mongoose#9373]
Hi! I'm running `.syncIndexes()` after deployment and mongoose is recreating every text index present.

This seems to happen because mongoose is comparing the `key` property of the indexes, but on text indexes this property doesn't reflect the actual indexed fields.

For example, this is an entry for a text index:

```
{
    "v" : 2,
    "key" : {
        "_fts" : "text",
        "_ftsx" : 1
    },
    "name" : "kicker_text_title_text_deck_text_bodyText_text",
    "ns" : "test.articles",
    "weights" : {
        "bodyText" : 1,
        "deck" : 3,
        "kicker" : 2,
        "title" : 5
    },
    "default_language" : "spanish",
    "background" : true,
    "language_override" : "language",
    "textIndexVersion" : 3
}
```

I think that `isIndexEqual` should compare `weight` instead of `key` when comparing text indexes.

Thank you!

**Comment by vkarpov15** [comment]
It looks like you're running an older version of Mongoose, we fixed this in v5.9.25 with #9225 . Please upgrade to at least v5.9.25 and re-open this issue if this issue is still happening.
