### ISSUE TITLE
Cannot access certain fields of schema inside virtual getter

### ISSUE THREAD

**Issue by Tyrubias** [Automattic/mongoose#9377]
**Do you want to request a *feature* or report a *bug*?**
Report a bug/request help.
**What is the current behavior?**
I have the following schema
```js
const PostSchema = new Schema({
  kind: {
    type: String,
    require: true,
    enum: Object.keys(enumPostType),
    description: 'The type of the post (whether event, discussion, or notice)'
  },

  title: {
    type: String,
    required: true
  },

  body: {
    type: String,
    required: true
  },

  text_align: {
    type: String,
    required: false,
    default: 'left'
  },

  date_created: {
    type: Date,
    required: false,
    default: new Date().getTime(),
    index: true
  },

  tags: {
    type: [String],
    required: false,
    default: []
  },

  creator: {
    type: String,
    required: true
  },

  upvotes: [
    {
      type: String
    }
  ],

  downvotes: [
    {
      type: String
    }
  ],

  reports: [
    {
      type: String
    }
  ],

  imageUrl: {
    type: String,
    validate: {
      validator: testUrl =>
        testUrl
          ? /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-/]))?/.test(
              testUrl
            )
          : true,
      message: props => `${props.value} is not a valid URL!`
    },
    required: false
  }
})
```
I'm trying to create a virtual field from the upvotes and downvotes

```js
PostSchema.virtual('relevance').get(function () {
  return this.upvotes.length - this.downvotes.length
})
```

However, `this` does not contain the upvotes and downvotes fields.

**If the current behavior is a bug, please provide the steps to reproduce.**

**N/A**

**What is the expected behavior?**

Based on my understanding I should be able to access the `upvotes` and `downvotes` fields of my schema when creating a virtual field. Am I misunderstanding something?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

I'm using Mongoose v5.10.2, MongoDB v3.6.0, and NodeJS v12.18.3

**Comment by vkarpov15** [comment]
The below script demonstrates that the `relevance` virtual works as expected. Please modify the below script to demonstrate your issue.

```javascript
const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = mongoose.Schema({
    upvotes: [String],
    downvotes: [String]
  });

  schema.virtual('relevance').get(function () {
    return this.upvotes.length - this.downvotes.length
  });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ upvotes: ['test1', 'test2'], downvotes: ['test3'] });
  console.log(doc.relevance);
}
```

**Comment by vemuladevendran** [comment]
const mongoose = require("mongoose");
const getRequiredFieldMessage = require("../errors/error-handling");
const FileSchema = require("./File.schema");
const {
  membershipDateCalculate,
  removeMembership,
} = require("../lib/membership/date");
const StudentSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: getRequiredFieldMessage("Student name"),
      lowercase: true,
    },
    email: {
      type: String,
      required: getRequiredFieldMessage("Student email"),
      unique: true,
    },
    password: {
      type: String,
      required: getRequiredFieldMessage("Password"),
    },
    rollNumber: {
      type: String,
      required: getRequiredFieldMessage("Roll Number"),
      lowercase: true,
      unique: true,
    },
    dob: {
      type: String,
      required: getRequiredFieldMessage("DOB"),
    },
    year: {
      type: String,
      required: getRequiredFieldMessage("Year"),
    },
    mobileNumber: {
      type: String,
      required: getRequiredFieldMessage("Mobile Number"),
    },
    membership: {
      type: Boolean,
      default: true,
      required: getRequiredFieldMessage("Membership status"),
    },
    membershipExpireDate: {
      type: Date,
      default: function () {
        return membershipDateCalculate(this.year);
      },
    },
    isDeleted: {
      type: Boolean,
      default: false,
    },
    image: {
      type: FileSchema,
    },
  },
  { timestamps: true, toJSON: { virtuals: true } }
);

StudentSchema.virtual("isMembershipActive").get(() => {
  console.log("calling-------", this);
  return removeMembership(this.membershipExpireDate, this.membership);
});

const Student = mongoose.model("Student", StudentSchema);

module.exports = Student;

**Comment by vemuladevendran** [comment]
i am trying to access this in virtual but it showing {}. please give me the solution

**Comment by vkarpov15** [comment]
@vemuladevendran you're defining your virtual using an arrow function. Use this instead:

```javascript
StudentSchema.virtual("isMembershipActive").get(function() {
console.log("calling-------", this);
return removeMembership(this.membershipExpireDate, this.membership);
});
```
