### ISSUE TITLE
Unable to "delete" the property of the object in mongoose Document Object

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#9378]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I am unable to delete the field from the mongoose, but `$unset` is working.

**If the current behavior is a bug, please provide the steps to reproduce.**

Without `$unset`
```js
let user = await User.findById(user_id);
delete user.last_name;
await user.save();

user = await User.findById(user_id);
console.log(user.last_name); // Santiago 
```
With `$unset`
```js
await User.findByIdAndUpdate(user_id, { $unset: { last_name: true } });

let user = await User.findById(user_id);
console.log(user.last_name); // undefined 
```

**What is the expected behavior?**
It should delete the property

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v14.8.0

MongoDB: v4.4.0

Mongoose: v5.9.24

**Comment by vkarpov15** [comment]
The way to unset a key in Mongoose is to set it to undefined. `user.last_name = undefined; user.save();` becomes a `$unset` under the hood.
