### ISSUE TITLE
Not able to pass {multi:true} parameter while updating with pull update operator

### ISSUE THREAD

**Issue by surajpra** [Automattic/mongoose#9385]
**Do you want to request a *feature* or report a *bug*?**
Help
**What is the current behavior?**
Not able to pass {multi:true} parameter while updating with pull update operator
**If the current behavior is a bug, please provide the steps to reproduce.**

```Javascript
const pullData = { '$pull': { 'batches.$.committed' : { 'item':lineItemId } } };
await Item.findOneAndUpdate({ 'batches.committed.item': lineItemId }, pullData, { multi: true }, function (err, data) => {
     console.log(err);
     console.log(data);
});
```
**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/41315923/92203813-bad5b580-ee9f-11ea-9abf-ccb90c614c84.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: 12.18.3
Mongoose: 5.10.2
MongoDB : 4.4.0Enterprise

**Comment by vkarpov15** [comment]
`multi` is not a valid option for `findOneAndUpdate()`, that option is only supported for the legacy `update()` method.
