### ISSUE TITLE
How can I set the right collection before insert or update?

### ISSUE THREAD

**Issue by zhengdai** [Automattic/mongoose#9387]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I want to set the collection name before insert and update operation
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Mongoose models don't support changing the underlying collection once the model is compiled. But you can do `mongoose.connection.db.collection('mycollectionname').insertOne()` to bypass Mongoose and use the MongoDB driver directly.
