### ISSUE TITLE
CastError: Cast to ObjectId failed for value "images" at path "_id" for model

### ISSUE THREAD

**Issue by itsvaibhav10** [Automattic/mongoose#9388]
# Current Mongoose Version =**"mongoose": "^5.10.3"**

## My Query 
  **Book.findById(req.params.bookId)**

## Output
**{ bookId: '5f51ec34e6c5b22601dc4064', chapterIndex: '0' } //=>req.params**
**{ bookId: 'images', chapterIndex: 'user4-128x128.jpg' } //=> req.params changes and error thrown***
**Error: CastError: Cast to ObjectId failed for value "images" at path "_id" for model "Book"**

**Comment by vkarpov15** [comment]
This error seems like it is due to your Mongoose model expecting `bookId` to be a valid ObjectId, and the string `'images'` is not a valid ObjectId. Can you please post what your `Book` model's schema looks like?

**Comment by itsvaibhav10** [comment]
mongoose.Types.ObjectId() Solves The Problem Thanks @vkarpov15
