### ISSUE TITLE
Mongoose odd behavior

### ISSUE THREAD

**Issue by rodrigoverasantis** [Automattic/mongoose#9389]
**Do you want to request a *feature* or report a *bug*?**
It's more like a question.

**What is the current behavior?**
using
new Model(req.body).save().then(data =>....)
vs
let newModel = new Model(req.body);
newModel.save()
.then(data => ....)

Having a model with:
creation_date:{
type: Date,
default: Date.now(),
}
data in the first and second lines should be the same, but the creation_date end up different. Like the first line won't generate a new instance of the data and use an old one, so the creation_date it's not the current time.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
creation_time with current time.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
All latest versions.

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @rodrigoverasantis 

```js
creation_date: {
  type: Date,
  default: Date.now()
}
```
The code above sets the default value for `creation_date` to the result of calling `Date.now()` when first compiling the schema, what you want to do is to [pass the function as a default](https://mongoosejs.com/docs/defaults.html#default-functions), and mongoose will execute it on creating new documents. It would look like this:
```js
creation_date: {
  type: Date,
  default: Date.now
}
```

Also, for creation date, you should probably use [schema timestamps option](https://mongoosejs.com/docs/guide.html#timestamps) that automatically adds the createdAt (can be renamed to creation_date if you like) automatically for your schema.

**Comment by rodrigoverasantis** [comment]
That's helpful! Thanks!
