### ISSUE TITLE
isModified of a field is set to `true` even if value hasn't actually changed

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#9396]
**Do you want to request a *feature* or report a *bug*?**
Depends on whether this is expected behaviour or not. Possibly related to https://github.com/Automattic/mongoose/issues/4487

**Repro script**
```js
const mongoose = require('mongoose');
const {Schema} = mongoose;
const uri = `mongodb://localhost:27017/test`;

//Schema
const FooSchema = new Schema({
  bar: {
    type: String,
  },
});

//Pre-save hook 1
FooSchema.pre('save', function(next) {
  console.log('HOOK 1: BAR MODIFIED:', this.isModified('bar'), this.bar);
  this.bar = 'bar';
  next();
});

//Pre-save hook 1
FooSchema.pre('save', function(next) {
  console.log('HOOK 2: BAR MODIFIED:', this.isModified('bar'), this.bar);
  next();
});

//Model
const Foo = mongoose.model('Foo', FooSchema);

//Test function
async function test() {

  //Connect to database
  await mongoose.connect(uri);

  //Create new item
  const foo = new Foo({bar: 'bar'});
  await foo.save();

  foo.bar = 'notbar';
  await foo.save();
}

test();
```

**What is the current behavior?**
At the second save of the document, mongoose says `bar` is modified in the second hook, even though the first hook restored the value to what it was pre-save. So while the value was modified, it has not actually changed.

Output:

```
HOOK 1: BAR MODIFIED: true bar
HOOK 2: BAR MODIFIED: true bar
HOOK 1: BAR MODIFIED: true notbar
HOOK 2: BAR MODIFIED: true bar
```

**What is the expected behavior?**
Expect the following output:

```
HOOK 1: BAR MODIFIED: true bar
HOOK 2: BAR MODIFIED: true bar
HOOK 1: BAR MODIFIED: true notbar
HOOK 2: BAR MODIFIED: false bar <-- expect this to be false because between saved versions, bar has not changed
```

I realise this may not be how Mongoose change tracking was set to work, but for our use case where we try to track fields that have changed for audit purposes it is annoying that some fields always get reported as changed, even though they are not. One example is where we parse and clean up the mobile number format which comes from the client. The client will always send this "formatted" for the local country, e.g. a number like "022 123 123". However, the server will parse this and store it depending on the country code, e.g. "+6422123123". This value does not change, but because we "set" it to "022 123 123" mongoose will always report it as being modified, even though the subsequent hook will restore it to the same value it was before.

It'd be great if the `isModified` value could revert back to false if Mongoose detects that since the last change, the value has been restored to what it was.

Another example that doesn't use hooks:

```js
  const foo = new Foo({bar: 'bar'});
  await foo.save();
  console.log(foo.bar); //bar
  console.log(foo.isModified('bar')); //false

  foo.bar = 'baz';
  console.log(foo.isModified('bar')); //true, expecting true
  foo.bar = 'bar';
  console.log(foo.isModified('bar')); //true, expecting false
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose 5.9.20
mongodb 4.2.5
node 12.16.2

**Comment by samtsai15** [comment]
I think this can help you

```
// Pre-save hook 1
FooSchema.pre('save', function (next) {
  if (this.isNew) {
    console.log('HOOK 1: BAR MODIFIED (isNew): ', this.isModified('bar'), this.bar);
  } else {
    console.log('HOOK 1: BAR MODIFIED:', this.isModified('bar'), this.bar);

    this.bar = 'bar';
  }

  next();
});

// Pre-save hook 2
FooSchema.pre('save', function (next) {
  if (this.isNew) {
    console.log('HOOK 2: BAR MODIFIED (isNew): ', this.isModified('bar'), this.bar);
  } else {
    console.log('HOOK 2: BAR MODIFIED:', this.$locals.preBar !== this.bar, this.bar);
  }
  next();
});


// Model
const Foo = mongoose.model('Foo', FooSchema);

// Test function
async function test() {
  // Connect to database
  await mongoose.connect(uri);

  // Create new item
  const foo = new Foo({ bar: 'bar' });
  await foo.save();
  foo.$locals.preBar = foo.bar;
  foo.bar = 'notbar';
  await foo.save();
}
```

Result
```
HOOK 1: BAR MODIFIED (isNew):  true bar
HOOK 2: BAR MODIFIED (isNew):  true bar
HOOK 1: BAR MODIFIED: true notbar
HOOK 2: BAR MODIFIED: false bar
```

**Comment by adamreisnz** [comment]
Thanks @samtsai15, what is `this.$locals.preBar` ? Is that something that is documented, or am I supposed to set the value of each field in `this.$locals` manually?

**Comment by vkarpov15** [comment]
@adamreisnz See [`Document#$locals` docs](https://mongoosejs.com/docs/api/document.html#document_Document-$locals). `$locals` is an empty object used primarily to store data for document middleware in a way that is guaranteed to not conflict with Mongoose internals.

**Comment by vkarpov15** [comment]
@adamreisnz I added a fix for this in the 5.11 branch. This change is a bit too heavy for a patch release since it affects all `set()` and all `save()` calls. We're planning on shipping 5.11 in November 2020.

**Comment by adamreisnz** [comment]
Thanks, I'll keep an eye out!

**Comment by samtsai15** [comment]
@adamreisnz Sorry for response it. 

You can manually set everything you want variables in `this.$locals`.

check it out : https://mongoosejs.com/docs/api.html#document_Document-$locals

**Comment by vkarpov15** [comment]
One of my concerns with this was perf implications: `deepEqual()` has historically been pretty slow in Mongoose. But with a couple of small changes I've been able to speed up the below script by 30x (30 seconds to sub 1 second on my macbook):

```javascript
'use strict';

const mongoose = require('mongoose');

const { deepEqual } = require('mongoose/lib/utils');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  
  await mongoose.connection.dropDatabase();
  
  const Model = mongoose.model('Test', mongoose.Schema({ _id: false, docArr: [{ _id: false, test: String }] }));
  
  const doc1 = new Model();
  const doc2 = new Model();

    for (let i = 0; i < 10000; ++i) {
    doc1.docArr.push({ test: 'abc' });
    doc2.docArr.push({ test: 'abc' });
  }

  const assert = require('assert');
  console.log('Start compare');

  const start = Date.now();
  for (let i = 0; i < 100; ++i) {
    assert.ok(deepEqual(doc1, doc2));
  }
  console.log('Elapsed', Date.now() - start);
}
```

So this change should be much less heavy.

I opened a related issue that should make `deepEqual()` faster going forward: https://github.com/Automattic/mongoose/issues/9571

**Comment by riggedCoinflip** [comment]
I am currently trying to test an async pre-save hook that should hash a password if it got changed.
```js
UserSchema.pre("save", async function (next) {
    if (this.isModified("password")) {
        this.password = await bcrypt.hash(this.password, SALT_ROUNDS);
    }
    next()
});
```
Testing that hook with this code:
```js
const user = new User({name: "foo", password:"Password1"})
await user.save()
const oldHashedPassword = user.password
//change other field
user.name = "bar"
await user.save()
const newHashedPassword = user.password

expect(newHashedPassword).toBe(oldHashedPassword)
```
 it works as expected most of the time - but on perhaps 30% of the runs, the pre-save hook fires an additional time and tries to hash my already hashed password. 

I can restart the test case over and over and get different results on every run.
For me that sounds like an invisible race condition, but I am no expert.

I am unsure of the current state of the issue:
- Should the error be fixed by now?
- Should I use the locals workaround?
- Is there another workaround with `deepEqual`?

**Comment by vkarpov15** [comment]
@riggedCoinflip we'll try to repro this on our end, but I'd recommend reading up on alternative [patterns for storing user passwords in MongoDB](http://thecodebarbarian.com/thoughts-on-user-passwords-in-rest-apis.html).

**Comment by IslandRhythms** [comment]
```
const mongoose = require('mongoose');
const bcrypt = require('bcrypt')
const SALT_ROUNDS = 10;
var statement = 0;
var equal = 0;


const UserSchema = new mongoose.Schema({
    name: String,
    password: String
});

UserSchema.pre("save", async function (next) {
    if (this.isModified("password")) {
        statement++;
        console.log('this is number of times the if statement was accessed', statement)
        this.password = await bcrypt.hash(this.password, SALT_ROUNDS);
    }
    next()
});


const User = mongoose.model('User', UserSchema);


test();

function test() {
    let i = 0;
    while(i <= 20) {
        run();
        i++;
    }
}
async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });
    
    await mongoose.connection.dropDatabase();
    const user = new User({name: "foo", password:"Password1"})
    await user.save()
    const oldHashedPassword = user.password
    //change other field
    user.name = "bar"
    await user.save()
    const newHashedPassword = user.password
    if(newHashedPassword === oldHashedPassword) {
        equal++;
        console.log('true',equal, statement);
    }
}



```

**Comment by djbar4** [comment]
Was this issue ever fixed and released? I am having the same problem right now where fields where the value hasn't changed are showing up when calling `this.modifiedPaths()`

**Comment by vkarpov15** [comment]
@djbar4 yes this particular issue was fixed and released. If you are experiencing a similar issue, please open a new issue and follow the issue template.
