### ISSUE TITLE
Typescript - Can't extend Mongoose

### ISSUE THREAD

**Issue by subhashdike** [Automattic/mongoose#9399]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am trying to use typescript with Mongoose, and here is what I observe. My requirement is to extend the base Mongoose class so that I can add additional functionality

```
import { Mongoose } from "mongoose";

interface CustomMongooseBase {
  //extending at the interface level so that consumers have the full signature of mine as well as parent interface
  myCustomMethod(): void;
}

class CustomMongoose extends Mongoose implements CustomMongooseBase {
  myCustomMethod(): void {
    console.log("this is my custom method");
  }
}

//this is what I would expect to work, if this compiles fine
const a = new CustomMongoose();
a.myCustomMethod(); // should work
a.model("modelName"); //should also work, since this is from the base. 

//The above logic gives compilation  error
//Non-abstract class 'CustomMongoose' does not implement inherited abstract member 'ConnectionBase' from class 'typeof import("mongoose")'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
There shouldn't be an compilation error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
 "@types/mongoose": "5.7.36"
 "mongoose": "5.10.3"
Node Version = v10.12.0

**Comment by vkarpov15** [comment]
We do not currently have officially supported TypeScript bindings, you'll have to open an issue with @types/mongoose. Please follow #8108 for updates.
