### ISSUE TITLE
Writing same object into 2 databases (Same Schema)

### ISSUE THREAD

**Issue by ameeno** [Automattic/mongoose#9400]
hello, I am trying to have two separate api's with the same data inside each cluster.

I have a local API and db in a cluster, I think i have figured out multiple connections.

but when a model and schema is created and saved to db1, how do i save the same object and same data into the second db?

it seems a little complicated as the id is generated randomly.

**Comment by vkarpov15** [comment]
Suppose `Model1` is connected to `db1` and `Model2` to `db2`. You can then do:

```javascript
const doc1 = await Model1.create(obj);
const doc2 = await Model2.create(doc1);
```

**Comment by ameeno** [comment]
ok so a different model for each db right?

**Comment by vkarpov15** [comment]
Yes, a different model for each db. In Mongoose, a [model](https://mongoosejs.com/docs/models.html) always has exactly 1 [connection](https://mongoosejs.com/docs/connections.html).
