### ISSUE TITLE
Validator should run value through getter

### ISSUE THREAD

**Issue by sgpinkus** [Automattic/mongoose#9402]
**Do you want to request a *feature* or report a *bug*?**
Bug or feature to work around bug.

**What is the current behavior and expected behavior?**
Validators are run after setter but getter is not run. The value without the getter applied may never actually be visible to anyone besides the DB layer. Normally we'd want to validate what the client sees? 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
var mongoose = require('mongoose');
var MessageSchema = new mongoose.Schema({
  text: {
    type: String,
    maxlength: 3,
    get: function(v) { return v.replace(/^XXX: /, ''); },
    set: function(v) { return `XXX: ${v}`; },
  },
}, {
  toObject: { getters: true },
  toJSON: { getters: true },
});

var Message = mongoose.model('Message', MessageSchema);
var m = new Message({ text: '123' });
console.log(m.text); // Give '123'
console.log(m.validateSync()); // Gives validation error: Path `text` (`XXX: 123`) is longer than the maximum allowed length (3).
```

The reason I was wanting to do something like the above is for application layer encryption applied only to one field. set -> encrypt, get -> decrypt. Other use case could be any type of reversable encode / decode transform.

Being able to specify a validator inside the setter somehow would be a possible work around for this, because we have access to the value before and after the setting and can choose what we want to validate.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
> process.version
'v12.18.1'
> require('mongoose').version
'5.10.3'
```

**Comment by vkarpov15** [comment]
I think your best bet here is to write a custom validator that triggers getters by calling `this.get()` as shown below:

```javascript
var MessageSchema = new mongoose.Schema({
  text: {
    type: String,
    validate: {
      validator: function() {
        const decrypted = this.get('text');
        return decrypted.length <= 3; 
      },
      message: 'Text must be less than 3 characters'
    },
    get: function(v) { return v.replace(/^XXX: /, ''); },
    set: function(v) {
      return `XXX: ${v}`;
    },
  },
}, {
  toObject: { getters: true },
  toJSON: { getters: true },
});
```

It is a bit more cumbersome than I would like, but I can't really think of a more elegant solution. We could theoretically add support for a `getters` option for validators, or add a `validateBeforeSetters` option, but both of these seem clunky.

What do you think about this approach @sgpinkus ?

**Comment by sgpinkus** [comment]
@vkarpov15 yeah that makes sense. I can't think of a better solution either. I will go with this for now. Thanks.

Actually I asked the question on SO, but I put it in slightly different terms -- https://stackoverflow.com/questions/63803475/mongoose-how-to-apply-a-transparent-per-field-database-encode-decode-like-trans. I think this transparent transforms, or generally being able to insert some kind of codec middleware into the DB R/W streams is actually a legit use case. As you picked up, my use case is encryption. Another one might be compression. All that would be needed is a post ~ "prepare" hook to go with the existing post init.
