### ISSUE TITLE
`overwrite` option for `mongoose.model()`, and `overwriteModels` for mongoose global

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9406]
A convenient way to make `mongoose.model()` not throw an error if a model with the same name already exists:

```javascript
mongoose.model('Test', schema, null, { overwriteModels: true });
```

Or, to opt in to setting `overwrite` by default:

```javascript
mongoose.set('overwriteModels', true);
```

**Comment by RadotJar** [comment]
Has documentation been updated to reference this? I couldn't find any
