### ISSUE TITLE
date returns less than 1

### ISSUE THREAD

**Issue by indraraj26** [Automattic/mongoose#9416]
**Do you want to request a *feature* or report a *bug*?**  *bug*

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

It is returning minus one i.e if you pass 16 date it returns 15,  if you pass 18 date it returns 17 where as in browser it is working fine if i do new Date();

Also i tried with new Date() but still it returns less than one

```
const newUser = { dob: new Date('10/16/1995') };
const user = new UserModel(newUser);
await user.save();
```
Also i converted date into yyyy-mm-dd but still same
````
let date = '2/10/1977';
    date = new Date(
        `${date.split('/')[2]}-${date.split('/')[0]}-${date.split('/')[1]}`,
    );
    console.log(date);
    const newUser = { dob: new Date(date) };
````
```
const mongoose = require('mongoose');

let UserSchema = new mongoose.Schema({
	dob: Date,
});

run().catch((err) => console.log(err));

async function run() {
	await mongoose.connect('mongodb://localhost:27017/test', {
		useNewUrlParser: true,
		useUnifiedTopology: true,
	});
	await mongoose.connection.dropDatabase();

	const UserModel = mongoose.model('user', UserSchema);

	const newUser = { dob: '10/16/1995' };
	const user = new UserModel(newUser);
	await user.save();
	console.log(user, 'output');

	// output
	/* { _id: 5f5f13e643f6c0cc94ab26a8,
  dob: 1995-10-15T18:30:00.000Z,
  __v: 0 } '' */
}

```
**What is the expected behavior?**
It should save exact date
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

`"mongoose": "^5.9.22",`

**Comment by samtsai15** [comment]
Hi,
Can you print  `console.log(date);` ?
Maybe it's about timezone problem.
MongoDB will save UTC+0 date

**Comment by indraraj26** [comment]
Hi, 

that is just modifying the incoming date string to
date = '2/10/1977'
to
date = '1977-2-10'

yes i agree it is totally related to UTC, but how can i get rid of timezone issue

**Comment by samtsai15** [comment]
You can convert timezone in your client much easier.

Use moment-timezone

```
const moment = require('moment-timezone');
...

console.log(moment(user.dob).tz('Asia/Taipei').format()); // .tz() input your timezone 
// 1995-10-16T00:00:00+08:00 (Your timezone)

```

**Comment by indraraj26** [comment]
But i would like to send this dob to third party service, i cant use hardcoded tz zone since user can be from anywhere in the world

**Comment by samtsai15** [comment]
Maybe you can save String and validate format.

**Comment by indraraj26** [comment]
Yes i think this is the way i will have to use.

Thank you
