### ISSUE TITLE
Pre hooks not firing when there is 2nd level of subdocuments

### ISSUE THREAD

**Issue by RsknCankov** [Automattic/mongoose#9419]
Do you want to request a feature or report a bug?
report a bug

What is the expected behavior?
should fire all pre hooks of child schemas

Let's say there is following mongoose schema structure:

```
import { Schema } from 'mongoose';

export const ChildSchema: Schema = new Schema({price: { type: Number, required: true }});

ChildSchema.pre('validate', function(next: HookNextFunction) {
console.log('Fire validate');
  next();
});

ChildSchema.pre('save', function(next: HookNextFunction) {
console.log('Fire save');
  next();
});

export const ChildChildSchema: Schema = new Schema({prices: [ChildSchema]});

ChildChildSchema('validate', function(next: HookNextFunction) {
console.log('Fire validate');
  next();
});

ChildChildSchema('save', function(next: HookNextFunction) {
console.log('Fire save');
  next();
});

export const ParentSchema: Schema = new Schema({
  childrenLevel2: { type: [ChildSchema], default: [], required: false },
  childrenLevel3: { type: [ChildChildSchema], default: [], required: false },
}, { timestamps: true });
```

Seems neither **Child** or **ChildChild** pre hooks are being fired. As soon as I remove **ChildChildSchema** from **ChildSchema** everything works fine.

What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.
Node.js version: 12.16.2
Mongoose.js version: 5.10.5
MongoDb version : 4.0.0

**Comment by dj2616** [comment]
+1

**Comment by alexdaud** [comment]
+1

**Comment by RsknCankov** [comment]
Okay after performing some tests, it seems that the problem was caused by the external import of child schemas. After defining all schemas in same file everything seems to work fine. I am closing this one.

**Comment by vkarpov15** [comment]
Make sure you define middleware on your schema **before** adding it to a parent schema. See: https://mongoosejs.com/docs/middleware.html#defining
