### ISSUE TITLE
How to read from secondary, slaveOk is work, but the method is instance of "query" and not in aggregate

### ISSUE THREAD

**Issue by lsc949982212** [Automattic/mongoose#9420]
I want to query data from the database, and then I use 'query.slaveOk()', it's work!  but it's does't work when i use 'aggregate.slaveOk()', because the method is only in Query instances, not in Aggregate instances.

 How to use this method?

**Comment by samtsai15** [comment]
slaveOk() already deprecated.

You can use it.
https://mongoosejs.com/docs/api.html#query_Query-read
https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate-read

**Comment by samtsai15** [comment]
slaveOk() already deprecated.

You can use it:
https://mongoosejs.com/docs/api.html#query_Query-read
https://mongoosejs.com/docs/api.html#aggregate_Aggregate

**Comment by lsc949982212** [comment]
thx, resolved
