### ISSUE TITLE
unique option in the schema

### ISSUE THREAD

**Issue by mahmoudAcm** [Automattic/mongoose#9422]
this is my schema
{
    username: {
        type: String,
    },
    email: {
        type: String,
        unique: true
    },
    location: {
        type: String
    },
    password: {
        type: String
    },
    avatar: {
        type: String
    }

the problem is i can insert many records with the same email
how is that possible should i make some additional steps in checking if it is repeated ?

**Comment by AbdelrahmanHafez** [comment]
Welcome @mahmoudAcm 

Check [this question](https://mongoosejs.com/docs/faq.html#unique-doesnt-work) in FAQ, hope it answers your question, please let me know if you still need any further assistance with this issue.
