### ISSUE TITLE
 aggregation isn't resolving/rejecting or firing the callback

### ISSUE THREAD

**Issue by laneme** [Automattic/mongoose#9424]
This could be because of my lack of understanding of the aggregation framework but here it is.

```
const aggregateStage1 = {
    $match: {
        _id: roomId, user_id: userId
    }
}

const aggregateStage2 = {
    $filter: {
        input: '$messages',
        as: 'msg',
        cond: {
            $lt: {"$$msg.timestamp": timestamp},
        }
    }
}
```

These are my two stages. I ran them like this

```
let res = ChatModel.aggregate([
    aggregateStage1, aggregateStage2
], (err, sum) => {
    console.log(err,sum);
})
res.then(resFunc).catch(errLogger
```
The problem is, this isn't returning anything. The promise is never being resolved, the callback is never being called. And program is just exiting(it usually hangs there for moment if there's a promise pending). Not throwing any error either.

I also tried using just one stage, tweaking the aggregation queries and also mongoose provided `aggerate().match(...) ...`
Nothing seem to work. Someone can assist me on this?

I'm using mongoose 5.10.5. idk what mongodb version it's using.

**Comment by laneme** [comment]
I figured out the problem was with node. This was so unexpected

**Comment by vkarpov15** [comment]
@laneme what was the issue? We've seen a few issues pop up in v5.10.5 that may be related to some changes we made to aggregation cursors in that version (#9403). We want to make sure this isn't an issue with Mongoose.

Also, [please don't mix callbacks and promises](https://mongoosejs.com/docs/faq.html#duplicate-query).
