### ISSUE TITLE
Error: TypeError _this.$__.activePaths.init is not a function

### ISSUE THREAD

**Issue by lucafrancescato** [Automattic/mongoose#9439]
I'm using version 5.10.6

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I get the following error when trying to save a document in the database:
```
TypeError _this.$__.activePaths.init is not a function TypeError: _this.$__.activePaths.init is not a function
    at node_modules/mongoose/lib/document.js:2786:29
    ... rest of stack trace
```
This won't let me save the document.
It might be interesting the fact that in version 5.9.4, I had this same error, but the document could be saved nonetheless.

**If the current behavior is a bug, please provide the steps to reproduce.**

This happens due to this schema:
```
const mySchema = new mongoose.Schema(
{
    // other code
    one: {
        two: {
            type: [
                three1: { // The problem is here: defining 'three' field as array of custom objects
                    type: [
                        {
                            // Whatever type, it will throw that error
                        }
                    ]
                },
                three2: Date
            ]
        }
    },
    // other code
});
```
Then in 'pre validate' middleware, I do:
`this.one.two[0].three1 = someVariable; // Where someVariable is of correct type, that is an array of custom objects`

**Workaround found**
```
const mySchema = new mongoose.Schema(
{
    // other code
    one: {
        two: {
            type: [
                three1: Array, // This works
                three2: Date
            ]
        }
    },
    // other code
});
```
In this workaround, the document gets correctly saved (although each custom object in 'three1' array doesn't have its own '_id' field).

**What is the expected behavior?**
The expected behavior is that the documents gets saved without that error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v12.6.1
Mongoose: 5.10.6
MongoDB: 4.2.0

**Comment by vkarpov15** [comment]
I'm unable to repro this, the below script executes without any errors on v5.10.6. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const mySchema = new mongoose.Schema(
{
    // other code
    one: {
        two: {
            type: [{
                three1: { // The problem is here: defining 'three' field as array of custom objects
                    type: [
                        {
                            name: String
                        }
                    ]
                },
                three2: Date
            }]
        }
    },
    // other code
});

  mySchema.pre('validate', function() {
    console.log('Set');
    this.one.two[0].three1 = [{ name: 'baz' }];
  });

  const Test = mongoose.model('Test', mySchema);

  let doc = new Test({ one: { two: [{ three1: [{ name: 'bar' }] }] } });
  await doc.save();

  doc = await Test.findOne();
  doc.markModified('one.two');

  await doc.save();
  console.log('Done');
}
                                        
```

**Comment by lucafrancescato** [comment]
Yes, I will check it and let you know as soon as possible.

**Comment by vkarpov15** [comment]
I don't have any idea of what might cause this error. Can you please paste the rest of the stack trace?
