### ISSUE TITLE
document which returned from database cannot be set a new field.

### ISSUE THREAD

**Issue by wenlittleoil** [Automattic/mongoose#9442]
I use mongoose on the `egg-mongoose` library, here is my code.   
1. Schema definition like below
``` 
  const UserSchema = new Schema({
      age: {
          type: Number,
          required: true,
      },
      username: {
         type: String,
         required: true,
      },
  });
```  

2.How to use
```
      const user = await ctx.model.User.findOne({
          age:  18
      });
      user.roleName ='super-admin';
      console.log(user);
```  

3.The output on the console:
```
{
    _id: 5f59f494d670f986c94d059a,
    age:  18,
    username: 'Jack',
}
```  
As you can see, the `roleName` field didn't show. Actually, what' i expect are like so:
```
{
    _id: 5f59f494d670f986c94d059a,
    age:  18,
    username: 'Jack',
    roleName: 'super-admin'
}
```
Did I do something wrong? Looking forward to your help.

**Comment by samtsai15** [comment]
`user` is Mongoose object, you need convert to plain object. 

1. 
```
findOne().lean()
```

2.  
```
const raw = user.toObject() // or user.toJSON();
raw.roleName ='super-admin';
```

**Comment by wenlittleoil** [comment]
Thanks a lot, both methods work for me, maybe I should read the document completely from beginning to end before starting my development.
