### ISSUE TITLE
Need Help: Mongoose doesn't create indexes exist in sub schemas

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#9446]
**Do you want to request a *feature* or report a *bug*?**
help

**What is the current behavior?**

Mongoose doesn't create indexes (`unique` index for example) exist in sub schemas

**If the current behavior is a bug, please provide the steps to reproduce.**

```node
const subSchema = new Schema(
  {
    /...
    email: {
      type: SchemaTypes.String,
      unique: true,
      trim: true,
      maxlength: 320,
      required: true,
      text: true,
      set: normalizeEmail,
      validate: {
        validator(v) {
          return isEmail(v);
        },
        message: (props) => `${props.value} is not a valid email address.`,
      },
    },
  },

  { _id: false, id: false },
);

module.exports = subSchema;
```

```node
const { EmailModel } = require('./embedded');

const parentSchema = new Schema(
  {
    // ...
    email: { type: EmailModel, required: true }
  },

  { toJSON: { virtuals: true } },
);

module.exports = model('Parent', parentSchema);
```

**What is the expected behavior?**

I check indexes on MongoDB Compass, but don't see a `unique` index associated with the `email` field in the sub schema. I created the `unique` index for the field manually using MongoDB Compass and it works as expected, but Mongoose doesn't create any indexes exist in all sub schema I use!

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.10.6
MongoDB: 4.2.5
Node.js: 14.4.0

**Comment by vkarpov15** [comment]
Where is `EmailModel` defined? Mongoose does gather indexes from subschemas by default, unless you set the `excludeIndexes` option. My best guess based on reading this incomplete code sample is that `EmailModel` is a model class, not a schema, so you aren't defining your schema correctly.

**Comment by meness** [comment]
@vkarpov15 `EmailModel` is the `subSchema` in the above code snippet. `subSchema` is not defined as a model as you see above, unless I'm defining sub schemas in a wrong way.

**Comment by vkarpov15** [comment]
Shouldn't it be `const EmailModel = require('./embedded');` ? It looks like you're exporting a schema as the default export, but then using a destructuring import.

**Comment by meness** [comment]
@vkarpov15 Are you saying this is the problem? 🤔 I used `require-directory` package inside `embedded/index.js`, then I can easily import needed subschemas. That's because I wrote `const { EmailModel } = require('./embedded');`

```node
// embedded/index.js
module.exports = requireDirectory(module, {
  rename(name) {
    return _.flow(_.camelCase, _.upperFirst)(name);
  },
});
```

**Comment by vkarpov15** [comment]
Oh ok, that makes sense. `require-directory` shouldn't be a problem.

I just want to confirm though: what does `console.log(EmailModel instanceof mongoose.Schema)` print?

**Comment by meness** [comment]
> what does console.log(EmailModel instanceof mongoose.Schema) print?
@vkarpov15  It prints `true`

**Comment by vkarpov15** [comment]
The below script demonstrates that Mongoose creates the subschema's index correctly. Please modify the below script to demonstrate your issue.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const subSchema = new Schema(
    {
      email: {
        type: String,
        unique: true,
        trim: true,
        maxlength: 320,
        required: true,
        text: true,
      },
    },
    { _id: false, id: false },
  );
  const parentSchema = new Schema(
    {
      // ...
      email: { type: subSchema, required: true }
    },

    { toJSON: { virtuals: true } },
  );
  const Parent = mongoose.model('Parent', parentSchema);

  await Parent.init();

  console.log(await Parent.listIndexes());
}

```

Output:

```
$ node gh-9446.js 
Mongoose: parents.ensureIndex({ 'email.email': 'text' }, { unique: true, background: true })
(node:32498) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: parents.listIndexes()
[
  { v: 2, key: { _id: 1 }, name: '_id_' },
  {
    v: 2,
    unique: true,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'email.email_text',
    background: true,
    weights: { 'email.email': 1 },
    default_language: 'english',
    language_override: 'language',
    textIndexVersion: 3
  }
]
^C

```

**Comment by meness** [comment]
@vkarpov15 I tested your test case and I get the same output, **but the interesting part is** the email's unique index still doesn't exist. Check the picture below please. The output says it has a unique index, but it actually doesn't exist and I can save the same email address multiple times.

```console
[
    { v: 2, key: { _id: 1 }, name: '_id_', ns: 'test.parents' },
    {
        v: 2,
        unique: true,
        key: { _fts: 'text', _ftsx: 1 },
        name: 'email.email_text',
        ns: 'test.parents',
        background: true,
        weights: { 'email.email': 1 },
        default_language: 'english',
        language_override: 'language',
        textIndexVersion: 3
    }
]
```

![Screenshot 2020-10-10 183815](https://user-images.githubusercontent.com/7955356/95658558-30304800-0b28-11eb-9960-223ad32a8d29.jpg)

**Comment by vkarpov15** [comment]
I don't believe you can actually create a unique text index. I don't know off the top of my head but that isn't what text indexes are used for: https://docs.mongodb.com/manual/core/index-text/.

Why are you trying to create a text index on an email field? AFAIK text indexes aren't useful for one-word string fields, they're useful for fields that contain long-form prose (blog post content, comments, messages, etc.).

**Comment by meness** [comment]
You're right and the issue has fixed with removing the `text` index.
