### ISSUE TITLE
Model.createCollection should catch 'NamespaceExists' errors

### ISSUE THREAD

**Issue by m-weeks** [Automattic/mongoose#9447]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
`MyModel.createCollection` throws an error as of mongoose 5.10

**If the current behavior is a bug, please provide the steps to reproduce.**

In my case I was using it to register a view like so:

```
var MyModelSchema = new Schema({
 /* etc. */
});

var MyModel = mongoose.model('MyModel', MyModelSchema);

MyModel.createCollection({
  viewOn: 'otherCollection',
  pipeLine: [
    /* My pipeline */
  ]
});
```

**What is the expected behavior?**
Since this was the expected behavior in mongoose `5.9` and earlier, I think it should handle the case where the collection already exists by catching a `NamespaceExists` error. This already happens in `syncIndexes` (from #9299), where it catches the error `Model.createCollection` throws from `this.db.createCollection`, but I think `Model.createCollection` should catch the error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Nodejs: 12.16.1
Mongoose: 5.10.6
MongoDb: 4.2

**Comment by vkarpov15** [comment]
You're right, in v5.9 `createCollection()` did not throw an error if the collection already existed. This fix will be in v5.10.8.

**Comment by jarretmoses** [comment]
@vkarpov15 this still seems to be an issue on version `v5.10.11`

**Comment by jarretmoses** [comment]
@vkarpov15 I am still having this as an issue without having changed my code except for upgrading to `mongoose 5.10.11`. Looking at the change made regarding this issue the `createCollection` method never actually gets hit. I tracked it to 
```
  const _createCollection = autoCreate ?
    cb => this.createCollection({}, cb) :
    cb => cb();
```
where `autoCreate` is null. I dont know if thats intentional or not or perhaps I needed to change part of my setup now but I wanted to at least bring this up. As I would think a schema change shouldn't have been necessary for this.

**Comment by vkarpov15** [comment]
@jarretmoses this is definitely unintentional: [`autoCreate` is false by default](https://mongoosejs.com/docs/guide.html#autoCreate). Can you please open a new issue with code samples? You shouldn't have to make any changes to account for this change.
