### ISSUE TITLE
Bug in version 5.10.7 - ValidationError this[documentIsSelected] is not a function

### ISSUE THREAD

**Issue by Adam-Edry** [Automattic/mongoose#9449]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
Failing to create documents in many of my collections. Receiving the following error:
```
ValidationError: projects validation failed: name: this[documentIsSelected] is not a function
```
where projects is the collection name.

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't have steps to reproduce. I suspect this is related to having required in the schema due to the latest changes in history.md:
```
fix(document): pass document to required validator so required can use arrow functions #9435 AbdelrahmanHafez
fix(document): handle required when schema has property named isSelected #9438
```
I'll try to provide a gist or script when I get off of work today if no one comes up with anything until then.

**What is the expected behavior?**
Should be able to create a document in a collection using the create function.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: 5.10.7
MongoDB: 4.2.9
Node.js: 10.16.3

Note: I downgraded to mongoose 5.10.6 and that is working fine.

**Comment by Adam-Edry** [comment]
Reproduced:
https://gist.github.com/Adam-Edry/b6523c461c4017c662948869724fcdd8

gists won't allow me to have directories so I substituted `_` for the directory.
We have 2 dirs `test-mongoose` and `depend-package` each is a node.js package.
After you go into test-mongoose, `npm install` and then run `node index.js` you should see the error

This seems to happen because the mongoose module being used in the dependency package is not the same one as the primary package (test-mongoose). Are there any globals used when we create a schema?

The offending line is `mongoose/lib/schemaType.js:921` and logging there shows that `this[documentIsSelected]` is undefined.

Let me know if I can be of further help

**Comment by eilinora** [comment]
+ 1

Seeing this as well, when my Schema has required on one of its field (even when data is provided) validation fails.

Downgrading to 5.10.6 fixed the problem

**Comment by luisenrike** [comment]
The problem was introduced here:

https://github.com/Automattic/mongoose/commit/b128c9bf21b4d4edce09d39b0f9fbd5741f3e800#diff-020b22edc836e4a997579b91daed76b9R8-R10

>exports.documentIsSelected = Symbol('mongoose#Document#isSelected');
exports.documentIsModified = Symbol('mongoose#Document#isModified');
exports.documentModifiedPaths = Symbol('mongoose#Document#modifiedPaths');

We are requiring `mongoose` from two different packages so they don't share the symbols registry. That's why you get `ValidationError: projects validation failed: name: this[documentIsSelected] is not a function`

a.js
```
module.exports = Symbol('foo')
```

b.js
```
module.exports = Symbol('foo')
```

index.js
```
const fooA = require('./a')
const fooB = require('./b')

fooA === fooB // === false
```

Using `Symbol.for` fixes the problem but I don't know if this is the best way to do it 🤔.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for

**Comment by vkarpov15** [comment]
As a side note, if you have a separate module that stores your schemas, you should consider listing Mongoose in `peerDependencies` rather than `dependencies`, so you minimize the risk of version mismatch.

**Comment by Duchynko** [comment]
Sorry for reopening this issue but could you elaborate a little bit more? I'm using `mongoose 5.11.11` and still experience this.

I have an external npm package where I keep my schemas so I can reuse them in multiple projects. From the same schema package, I export a function which I then call from my application.

```ts
// ...schema package
export function exportModels(mongoose: Mongoose) {
  Group = mongoose.model<IGroupDocument, IGroupModel>("group", GroupSchema);
  User = mongoose.model<IUserDocument, IUserModel>("user", UserSchema);
  Game = mongoose.model<IGameDocument, IGameModel>("game", GameSchema);
  Bet = mongoose.model<IBetDocument>("bet", BetSchema);
}

// ...application project
async connect(): Promise<Mongoose> {
  if (!this.db) {
    this.db = await mongoose.connect(this.connectionString, {
      useNewUrlParser: true,
      useFindAndModify: false,
      useUnifiedTopology: true,
      useCreateIndex: true,
    });
  }
  exportModels(this.db);
  // also tried exportModels(mongoose);
  return this.db;
}
```

**Comment by Duchynko** [comment]
Alright - it seems I'm only experiencing this issue with nested Schemas. My user schema looks like this

```typescript
export const UserSchema = new Schema<IUserDocument>(
  {
    _version: { type: Number, required: true, default: 1 },
    username: { type: String, required: true, unique: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    totalScore: [
      {
        type: TotalScoreSchema,
        required: true,
        default: [],
      },
    ],
    bets: [{ type: BetSchema, default: [] }],
    groupId: { type: Schema.Types.ObjectId, ref: "group" },
  },
  { timestamps: true }
);
```

And the error is
`ValidationError: user validation failed: totalScore.0.season: this[documentIsSelected] is not a function, totalScore.0.competitionId: this[documentIsSelected] is not a function, totalScore.0.score: this[documentIsSelected] is not a function, totalScore.0._version: this[documentIsSelected] is not a function, totalScore.1.season: this[documentIsSelected] is not a function, totalScore.1.competitionId: this[documentIsSelected] is not a function, totalScore.1.score: this[documentIsSelected] is not a function, totalScore.1._version: this[documentIsSelected] is not a function`

I see very similar behavior with the other model that contains a nested schema
