### ISSUE TITLE
Mongoose and TypeScript @types/mongoose

### ISSUE THREAD

**Issue by hishamsabur** [Automattic/mongoose#9451]
Hello, Guys!

With the number of "TypeScript" users increasing day by day, and the popularity and continuation of "Mongoose", I think it is important to treat the update of [`@types/mongoose`](https://www.npmjs.com/package/@types/mongoose) with the same priority as updating the library itself, since at this moment `@types` is behind several issues. "Mongoose."

This's just a suggestion.
Thank you for this wonderful library and wish it continued success.

**Comment by AbdelrahmanHafez** [comment]
Mongoose does not currently support Typescript officially, we're working on official Typescript support, please follow  https://github.com/Automattic/mongoose/issues/8108 for progress.
