### ISSUE TITLE
updateMany().nModified does not work correctly with timestamps

### ISSUE THREAD

**Issue by vovarevenko** [Automattic/mongoose#9452]
## What is the Problem?
If we use `timestamps: true` parameter, then `updateMany.nModified` will always be equal to `updateMany().n`.

## Code Example
```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });
mongoose.set('debug', true);

const Cat = mongoose.model('Cat', new mongoose.Schema({ name: String }, { timestamps: true }));

async function start() {
  const kitty_1 = new Cat({ name: 'Zildjian' });
  const kitty_2 = new Cat({ name: 'Zildjian' });
  const kitty_3 = new Cat({ name: 'John' });

  await kitty_1.save();
  await kitty_2.save();
  await kitty_3.save();

  const result = await Cat.updateMany({}, { name: 'John' });

  console.log(result.n); // 3 (correct value)
  console.log(result.nModified); // 3 (wrong value, should be 2)
}

start();
```

##  Why is this happening?
If we run without a `timestamps` parameter mongoose does this:
```
Mongoose: cats.updateMany({}, { '$set': { name: 'John' } }, {})
```
but if we run with `timestamps: true` parameter mongoose does this:
```
Mongoose: cats.updateMany({}, {
  '$setOnInsert': { createdAt: new Date("Sat, 26 Sep 2020 18:46:11 GMT") },
  '$set': {
    updatedAt: new Date("Sat, 26 Sep 2020 18:46:11 GMT"),
    name: 'John',
  }
}, {})
```
Even if a `name` field is not modified, `updatedAt` field has been modified and mongodb will update all matched documents. So, the number of modified documents will always be equal to the number of matched documents.

As a result: updateMany().nModified does not work correctly if `timestamps: true` for model schema.
This can be solved by filtering by non-compliance with the updated field like this:
```js
const result = await Cat.updateMany({ name: { $ne: 'John' } }, { name: 'John' });
```
but this is not correct in my opinion.

Do you think this needs to be fixed? I think yes. I think this is not intuitive functionality and this does not inherit the `updateMany` logic from mongodb.

Original issue: https://github.com/typegoose/typegoose/issues/388#issuecomment-699531376
MongoDB `updateMany` returns: https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/#returns
Mongoose `updateMany`: https://mongoosejs.com/docs/api.html#model_Model.updateMany

**Comment by AbdelrahmanHafez** [comment]
This is the current expect behavior. `updatedAt` is the date where we attempted to update documents even if nothing really changed, and the value is added in a pre-hook.

The reason for that being we don't have access to the document in the database by the time we do an `updateOne` or `updateMany`, so we can't tell what actually changed without degrading the performance by finding the whole document and comparing the state before/after the update.

I'll close this one in favor of https://github.com/Automattic/mongoose/issues/6861
Let's follow the progress there.
