### ISSUE TITLE
Bug: error inserting or updating on cosmosdb Serverless (with mongodb interface v3.2) on Microsoft Azure

### ISSUE THREAD

**Issue by findemor** [Automattic/mongoose#9456]
Hi!

**What is the current behavior?**
I am getting an error when I try to update or insert a new document into a collection in **Azure CosmosDB with configured MongoDB 3.2 API interface, running on Serverless mode**.

**If the current behavior is a bug, please provide the steps to reproduce.**

When I try to upsert, for instance: 

`Current.model.updateOne(query, data, { upsert: true }, callback);  }`

Then I get this message as error parameter from callback:

`MongoError: Setting offer throughput or autopilot on container is not supported for serverless accounts. ActivityId: dea6ba0f-0000-0000-0000-000000000000, Microsoft.Azure.Documents.Common/2.11.0`

I supposed this is caused while mongoose tries to create the collection and it needs to specify throughput or shardkey, so I pre-generated the necessary collection, specifying shard key in azure portal. Then I specified it in the mongoose schema too:

`new Schema({ .. }, { shardKey: { "passport.pid": 1 }})`

But still receving the same error.

**What is the expected behavior?**

Mongoose being able to insert or update documents in MongoDB API 3.2 for Azure CosmosDB properly in serverless mode.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Using mongoose version 5.10.5
MongoDB 3.2 interface on Microsoft Azure CosmosDB Serverless mode

Thank you!

**Comment by vkarpov15** [comment]
We will look into this. But worth mentioning: we do **not** officially support CosmosDB. We don't test against cosmos, so there may be issues that we are not aware of.

**Comment by vkarpov15** [comment]
I took a quick look and this looks like a [known issue with Azure's quickstarts](https://docs.microsoft.com/en-us/answers/questions/94814/cosmos-quick-start-gt-create-items-contaner-gt-htt.html). From that thread: "our Quickstarts don't work for Serverless accounts". So this isn't an issue with Mongoose, your options are to (1) wait for Microsoft to fix this or (2) don't use the quickstart.
