### ISSUE TITLE
.save callback is getting called before data is in Mongo

### ISSUE THREAD

**Issue by CodeWithOz** [Automattic/mongoose#9460]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
My custom schema method doesn't exist on a document created using `.updateOne` with `upsert: true`. I have a setup like this:
```
// user.js
const userSchema = new Schema({ ... });
userSchema.methods.someMethod = function() { ... };
```

In another file, I create a new user when necessary using `User.updateOne` with `upsert: true` but the created user doesn't have `.someMethod`. Like this:
```
// another.js
const queryThatWontMatchAnyUser = { ... };
const dataOfNewUser = { ... };
User.updateOne(queryThatWontMatchAnyUser, dataOfNewUser, { upsert: true }, function(err, createdUser) {
  if (err || !createdUser) return;
  createdUser.someMethod(); // throws "createdUser.someMethod is not a function"
});
```

Why is `someMethod` missing on the created user?

**What is the expected behavior?**
`createdUser.someMethod` should be the function I defined in `user.js`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node.js 12
- Mongoose 5.10.4

**Comment by vkarpov15** [comment]
You should use [`User.findOneAndUpdate()` instead](https://mongoosejs.com/docs/tutorials/findoneandupdate.html). `updateOne()` updates the document **without** returning the document, you need to use `findOneAndUpdate()` to get the actual updated doc.

Also see [upserting documents with Mongoose](https://masteringjs.io/tutorials/mongoose/upsert).

**Comment by CodeWithOz** [comment]
@vkarpov15 thank you. A related question: what's the value of `this` inside the `findOneAndUpdate` pre-hook? I have something like this:
```
schema.pre('findOneAndUpdate', { document: true, query: false }, function (next) {
  ...
  this.myCustomSchemaMethod();
});
```

`this.myCustomSchemaMethod()` causes an error with this message: `this.myCustomSchemaMethod() is not a function`.

**Comment by CodeWithOz** [comment]
Never mind this question, I've gotten an answer.
