### ISSUE TITLE
Respect virtuals inside subschema while the main field is undefined

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#9462]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I defined a field called `password` and attached to a subschema. The subschema has a virtual called `hasPassword` which returns `true` if `password.password` is not undefined. I get the virtual as expected **while the outer password field is not undefined.**

```node
// User model
{
    password: { type: Password }
}, { toJSON: { virtuals: true } }
```

```node
// Password schema
{
    password: { type: String }
}, { toJSON: { virtuals: true } }

virtual('hasPassword').get(function virtual() {
  return this.password !== undefined;
});
```

```node
// Access
return findById().lean({ virtuals: true }).exec();
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Please use the above code snippets to test it.
- First have a password field. It should work as expected
- Then make the password (the outer password inside User model) undefined. It won't respect the virtual and there would be no `hasPassword` field.

**What is the expected behavior?**
Respect virtuals inside subschema while the outer field is undefined.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose: v5.10.7
Node: 14.4.0

**Comment by vkarpov15** [comment]
This is expected behavior, we don't implicitly create subdocs for virtuals. There are a couple workarounds:

1) Structure your schema to use a nested path rather than a subdocument:

```javascript
  const userSchema = Schema({
    password: { password: String }
  });

  userSchema.virtual('password.hasPassword').get(function virtual() {
    return this.password.password !== undefined;
  });
  userSchema.plugin(leanVirtuals);

  const User = mongoose.model('User', userSchema);
  await User.create({});

  const doc = await User.findOne().lean({ virtuals: true });
  console.log(doc.password.hasPassword); // false
```

2) Make `password` default to an empty object. You may need to add the [mongoose-lean-defaults plugin](https://www.npmjs.com/package/mongoose-lean-defaults) for this to work if old documents in your database have `password = undefined`.

```javascript
  const passwordSchema = Schema({ password: String });
  passwordSchema.virtual('hasPassword').get(function virtual() {
    return this.password !== undefined;
  });

  const userSchema = Schema({
    password: { type: passwordSchema, default: () => ({}) }
  });
  
  userSchema.plugin(leanVirtuals);

  const User = mongoose.model('User', userSchema);
  await User.create({});

  const doc = await User.findOne().lean({ virtuals: true });
  console.log(doc.password.hasPassword); // false
```
