### ISSUE TITLE
Unhandled rejection Error: `autoCreate` is an invalid option.

### ISSUE THREAD

**Issue by denissabramovs** [Automattic/mongoose#9466]
mongoose.set('autoCreate', true);

version v5.10.7

https://mongoosejs.com/docs/guide.html#autoCreate

**Comment by denissabramovs** [comment]
Have anyone tested this option?

**Comment by denissabramovs** [comment]
ok, it seems there is another way through options here:
https://github.com/Automattic/mongoose/blob/80473b362c62fecf709cc4dce934bdd1ebe60705/lib/connection.js#L693

Will try that out now.

**Comment by denissabramovs** [comment]
I see that there is a test for connection option here:
https://github.com/Automattic/mongoose/blob/8b8fea65b1742a52e31a38045f04538ab0376064/test/connection.test.js#L69

**Comment by denissabramovs** [comment]
but no test for `mongoose.set('autoCreate', true);`

**Comment by vkarpov15** [comment]
You're right: the issue is that we support `autoCreate` as a schema option and a connection option, but not a global option. Will add that in v5.10.9 to make it more consistent with `autoIndex`.
