### ISSUE TITLE
findOneAndUpdate is deprecated, so doc must encourage update

### ISSUE THREAD

**Issue by boly38** [Automattic/mongoose#9467]
**Do you want to request a *feature* or report a *bug*?**

[Documentation](https://github.com/Automattic/mongoose/blob/master/docs/tutorials/findoneandupdate.md#how-to-use-findoneandupdate-in-mongoose) improvement

**What is the current behavior?**

The official documentation "upsert" tutorial rely on [findoneandupdate](https://mongoosejs.com/docs/tutorials/findoneandupdate.html#upsert) 

While using findOneAndUpdate, we get some warning. So there is [a doc tips to avoid this deprecation warning](https://mongoosejs.com/docs/deprecations.html#findandmodify)

**What is the expected behavior?**

I would expect one of the following:
- a quick link to redirect and recommand user to use `update` method,
- or an overall tutorial replacement with `update` ?

**Comment by vkarpov15** [comment]
`update()` isn't a replacement for `findOneAndUpdate()`. As the [deprecation warning docs say](https://mongoosejs.com/docs/deprecations.html#findandmodify), you should set the global `useFindAndModify` option to avoid this deprecation warning:

```javascript
// Make Mongoose use `findOneAndUpdate()`. Note that this option is `true`
// by default, you need to set it to false.
mongoose.set('useFindAndModify', false);
```
