### ISSUE TITLE
updateOne/updateMany fails with arrayFilters and timestamps options together

### ISSUE THREAD

**Issue by intenser** [Automattic/mongoose#9468]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Description**
Using updateOne/updateMany to update subdocument array elements with arrayFilters and options.timestamps=true fails.
```
        await Rate.updateOne({ _id: request.params.id },
            { $set: { 'rates.$[filter].margin': margin } },
            { arrayFilters: [{'filter.period': 1}] , timestamps: true }
        );
```

**What is the current behavior?**

Error occurs:
```
MongoError: The array filter for identifier 'filter' was not used in the update { $setOnInsert: { createdAt: new Date(1601979942061) }, $set: { updatedAt: new Date(1601979942061) } }
```
**If the current behavior is a bug, please provide the steps to reproduce.**

You need a model with the schema like:

```
const roomRate = new mongoose.Schema({
    period: Number,
    margin: Number,
});

const schema = new mongoose.Schema({
    rates: [rateSchema],
}, {
    timestamps: true,
});

const Rate = mongoose.model('rate', schema);
```
And then run the above query:

```
await Rate.updateOne(... use parameters as in the description section)
```

**Workaround**
Seems like Mongoose generates the resulting query like:
```
{ $set: { 'rates.$[filter].margin': margin } },
{ $setOnInsert: { createdAt: new Date(1601979942061) },
{ $set: { updatedAt: new Date(1601979942061) } },
{ arrayFilters: [{'filter.period': 1}]
```
... which causes the error (Mongo Shell gives the same error on that query)

Therefore, the workaround is to set options.timestamps=false or to update timestamps manually

```
        await Rate.updateOne({ _id: request.params.id },
            { $set: { 'rates.$[filter].margin': margin } },
            { arrayFilters: [{'filter.period': 1}], timestamps: false }
        );
```

**What is the expected behavior?**

Mongoose must place the { updatedAt: new Date(1601979942061) }  part inside the existing $set, like:
```
{ $set: { 
   'rates.$[filter].margin': margin,
   updatedAt: new Date(1601979942061) } 
} },
{ $setOnInsert: { createdAt: new Date(1601979942061) },
{ arrayFilters: [{'filter.period': 1}]
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js v14.12.0
Mongoose v5.10.8
MongoDB v4.2.8

**Comment by vkarpov15** [comment]
The below script works as expected, no error thrown. Please modify the below script to demonstrate the issue you're seeing.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const roomRate = new mongoose.Schema({
    period: Number,
    margin: Number,
  });

  const schema = new mongoose.Schema({
    rates: [roomRate],
  }, { timestamps: true });

  const Rate = mongoose.model('rate', schema);

  const doc = await Rate.create({ rates: [{ margin: 3, period: 1 }] });

  await Rate.updateOne({ _id: doc._id },
            { $set: { 'rates.$[filter].margin': 5 } },
            { arrayFilters: [{'filter.period': 1}] , timestamps: true }
        );

  const res = await Rate.findById(doc);

  console.log('Done', res.rates);
}

```

**Comment by intenser** [comment]
@vkarpov15 Okay, I found what the problem was. If you modify the code to 
```
  await Rate.updateMany({ _id: doc._id },
            { $set: { 'rates.$[filter].marginERROR': 5 } },
            { arrayFilters: [{'filter.period': 1}], timestamps: true }
        );
```
you'll catch the error too. So the problem was with the wrong array element's field name.

In this case along with timestamps=false, also helps strict=false.

But generally, the error message is unrelated to the issue. Compare with
```
{ $set: { 'rates.someField': 5 } }, { timestamps=true, strict=true}
```
...which executes without errors.

Anyways, thank you for your efforts. You can close the bug report, unless you might want to fix the error message.
