### ISSUE TITLE
Add `bufferTimeout` option: Node process exits without error if model is used before connection

### ISSUE THREAD

**Issue by mhio** [Automattic/mongoose#9469]
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
Node process exits without an error on usage of a model before a connection.

**If the current behavior is a bug, please provide the steps to reproduce.**

File `test-exit.js`
```
const mongoose = require('mongoose')
const dummySchema = new mongoose.Schema({ word: String })
const Dummy = mongoose.model('Dummy', dummySchema);

async function go(){
  //await mongoose.connect('mongodb://localhost:27017/bug-exit-delete', { useNewUrlParser: true, useUnifiedTopology: true })
  await Dummy.create({ word: 'blah' })
  console.log('created')
  await mongoose.disconnect()
}

go().catch(e => console.error('error',e))
```

Running this produces no output or odd exit code:
```
$ node test-exit.js 
$ echo $?
0
```

**What is the expected behavior?**
Some sort of error or rejection, at least a non zero exit code. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 10.22.0, 12.18.3, 14.11.0
mongoose@5.10.8 (mongodb@3.6.2)
db version v4.2.2

**Comment by mhio** [comment]
I haven't been able to find where mongoose or mongodb might do this intentionally so I'm confused ¯\_(ツ)_/¯

**Comment by chumager** [comment]
maybe this will help.

https://mongoosejs.com/docs/faq.html#callback_never_executes

**Comment by mhio** [comment]
Thankyou! I never knew mongoose buffered above the driver.

**Comment by vkarpov15** [comment]
It is a little weird that this exits with no output. It is because `mongoose.disconnect()` clears the buffered requests, but it seems like the buffered requests should throw an error. I'll re-open this and take a closer look.

**Comment by mhio** [comment]
It appears those promises never resolve or reject as the example code never completes. I'm assuming the callback underneath is left in place as the buffered "thing"? But then I don't understand how the process exits as `.disconnect()` is never reached by the example code.

In promise world maybe the pending queries should be rejected on `.disconnect`. That might make a disconnect messier though, and might need some form of aggregate Error.

Can the buffer be filled in any circumstance after a successful connection? Like in a reconnect scenario?

**Comment by vkarpov15** [comment]
@mhio I took a closer look and you're right that `disconnect()` is never reached. The problem is that, since the event loop is empty (no connection so the `Dummy.create()` promise will never resolve), the program exits. We would need to make sure to add something to the event loop so Node doesn't exit, which is a good excuse to introduce the `bufferTimeout` option that we've been considering for a while to address this issue: https://mongoosejs.com/docs/faq.html#callback_never_executes .
