### ISSUE TITLE
updateOne pre hook is not invoked if a document is inserted

### ISSUE THREAD

**Issue by CodeWithOz** [Automattic/mongoose#9472]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `updateOne` inserts a new document the `updateOne` pre hook is not invoked. Perhaps worth mentioning that the `save` pre hook is also not invoked, although that's what I expect.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
// user.js
const userSchema = new Schema({ ... });
userSchema.pre('updateOne', { document: true, query: false }, function (next) {
  console.log('inside updateOne'); // this never shows in the logs
  ...
});

userSchema.pre('save', function (next) {
  console.log('inside save'); // this never shows in the logs, though that's what I expect
  ...
});
```

```
// another.js
const queryThatWontMatchAnyUser = { ... };
const dataOfNewUser = { ... };
User.updateOne(queryThatWontMatchAnyUser, dataOfNewUser, { upsert: true });
```

**What is the expected behavior?**
The `updateOne` hook gets invoked both when an existing doc is being updated and when a new one is being created.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- Node: 10 and 12
- Mongoose: 5.10.4

**Comment by vkarpov15** [comment]
```javascript
userSchema.pre('updateOne', { document: true, query: false }, function (next) {
  console.log('inside updateOne'); // this never shows in the logs
  ...
});
```

The above hook is for the `Document#updateOne()` method, not `Query#updateOne()`. Use `userSchema.pre('updateOne', { document: false, query: true }, function() { ... })` instead. Take a look at the [name conflict section of the middleware docs](https://mongoosejs.com/docs/middleware.html#naming).
