### ISSUE TITLE
.addCursorFlag() is not available

### ISSUE THREAD

**Issue by zuzu-dev** [Automattic/mongoose#9473]
Below is my mongoose model and I read data from db via cursor. My cursor times out after 10 minutes as mentioned in the documentation. 

const cursor = this.importRecordModel.find().cursor()

I am trying to add below to the end of the cursor but either because of typescript or mongoose, It is not on the available functions list. 

.addCursorFlag('noCursorTimeout', true);

<img width="452" alt="Screen Shot 2020-10-08 at 10 29 56 AM" src="https://user-images.githubusercontent.com/61191223/95428145-489a3a00-0951-11eb-9569-7a20e5fff25a.png">

**Comment by vkarpov15** [comment]
It's a TypeScript issue. It looks like `@types/mongoose` doesn't support this function.

We're currently working on officially supported Mongoose type definitions for v5.11.0 in #8108, that will fix this issue. 

I'm not familiar enough with TypeScript yet to know of a workaround off the top of my head, but this SO thread may be helpful: https://stackoverflow.com/questions/31086843/typescript-possible-to-disable-type-checking

**Comment by vkarpov15** [comment]
Fix is in the v5.11 branch :+1:
