### ISSUE TITLE
Update to Mongoose 5.10.9 cause mongoose connection error with a false error message

### ISSUE THREAD

**Issue by sajithneyo** [Automattic/mongoose#9476]
**Do you want to request a *feature* or report a *bug*?**

It's a bug

**What is the current behavior?**

When accessing a collection following error throws from the latest `mongoose 5.10.9`. I previously used` mongoose 5.9.29`

`MongooseError: Cannot call xxx.find() before initial connection is complete if bufferCommands = false. Make sure you await mongoose.connect() if you have bufferCommands = false`

**If the current behavior is a bug, please provide the steps to reproduce.**

Bellow is the connection class that I use to connect my AWS Lambdas to MongoDB

```
import util from 'util';
import mongoose, { ClientSession, Mongoose } from 'mongoose';
import { LambdaLog } from 'lambda-log';

let cachedDB: Mongoose | null = null;

const uriString =
    process.env.NODE_ENV === 'production'
        ? util.format('mongodb+srv://%s:%s@%s', process.env.MONGO_USER, process.env.MONGO_PASS, process.env.MONGO_IP)
        : 'mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false';

const logger = new LambdaLog();

export default class NewMongoConnector {
    public static async connectToDatabase(): Promise<void> {
        if (cachedDB) {
            const hasAConnection = mongoose.connections.find((connection) => {
                return connection.readyState === 1;
            });
            if (hasAConnection) {
                logger.info('reusing connection');
                return;
            }
        }

        const mongooseInstance: Mongoose = await mongoose.connect(
            uriString,
            {
                useUnifiedTopology: true,
                useCreateIndex: true,
                useNewUrlParser: true,
                bufferCommands: false,
                bufferMaxEntries: 0,
                useFindAndModify: false,
                dbName: 'some-name',
                poolSize: 1,
            },
            (error) => {
                if (error) {
                    logger.error(error.toString());
                    cachedDB = null;
                }
            },
        );
        cachedDB = mongooseInstance;
    }

    public static async disconnect(): Promise<void> {
        await mongoose.disconnect();
    }

    public static async startSession(): Promise<ClientSession> {
        const session: ClientSession = await mongoose.startSession();
        return session;
    }
}
```

But the error message says that I have to use await when connecting to the DB, which I do. This happened after the update from 5.9.29 to 5.10.9

**What is the expected behavior?**

This class worked fine for all the micro-services and cached the connections for the lambdas

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node = v12.18.4
MongoDB = 4.2.8
Mongoose = 5.10.9

**Comment by vkarpov15** [comment]
@sajithneyo can you please post an example of how you're using this `NewMongoConnector` class? Hard to figure out what might be going wrong without seeing how this class is used.

**Comment by sajithneyo** [comment]
@vkarpov15 

Import MongoConnector from '../../location';

then inside an async function,

await MongoConnector.connectToDatabase( );

**Comment by vkarpov15** [comment]
Found the issue, fix will be in v5.10.11 next week :+1:

**Comment by sajithneyo** [comment]
Perfect 😊✌

**Comment by sajithneyo** [comment]
@vkarpov15

Hay I updated to `"mongoose": "^5.10.14"`  and the problem still exists ☹️

**Comment by vkarpov15** [comment]
@sajithneyo please open a new issue and follow the issue template
