### ISSUE TITLE
mongoose.set('useCreateIndex', true);

### ISSUE THREAD

**Issue by vinipoo** [Automattic/mongoose#9477]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
I don't understand this issue, but I suspect you'll find the answer on this page: https://mongoosejs.com/docs/deprecations.html
