### ISSUE TITLE
 find() or find one() is returning empty array in mongoose if parameters are passed but when i queried in mongo shell find returns value

### ISSUE THREAD

**Issue by g3hk** [Automattic/mongoose#9480]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

I'm using mongoDB 4.4.1 , mongoose 5.10.9, node.js v12.16.0 and mac OS catalina
Can anyone help me with the error in the below code why find or findOne is returning empty array when a parameter is passed when it has data in database. When i queried via mongo shell find and find one returns value. Only when parameter is passed it is not returning value but it returns value for find and find one with no parameter passed why??? what mistake??? is it a problem with mongoose????

const mongoose = require('mongoose');
const Schema = new mongoose.Schema({
        categoryName: {
            type: String,
            trim: true
        },
        subcategory: [ {
            subcategoryName: {
                type: String,
                trim: true
            }]
});
 module.exports = mongoose.model('categories', Schema);
controller code:
------------------
const categories = require('../models/category');
exports.getCategory = (req, res, next) => {
categories.find({"categoryName":{ $regex: req.params.id, $options: 'i' }},(err, products) => {
   console.log("Products:"+JSON.stringify(products));
  if (err) {
         return res.status(400).json({
           error: "No Products found"+err
         });
       }
       res.status(200).json(products)
     });
};
routes code:
-------------
```
const categoryCtrl = require('../controllers/category'); routes.get('/category/getCategory/:id', categoryCtrl.getCategory);
```
GET call URL via postman:
------------------------
http://localhost:3000/category/getCategory/"Fruits"

**Comment by samtsai15** [comment]
Hi

Did you check `req.params.id` in controller?
And try to remove "*" symbol in url.

**Comment by g3hk** [comment]
pass query param without quotes

**Comment by st1702** [comment]
const Schema = new mongoose.Schema({...
discard the word 'new'
-> const Schema = mongoose.Schema
