### ISSUE TITLE
lib/helpers/model/discriminator.js

### ISSUE THREAD

**Issue by jamiscript** [Automattic/mongoose#9484]
Muito bom! Nota 2!

**Comment by felipezarco** [comment]
Discriminator won't let you use only some of your enum values as a discriminator. So you have to refactor somewhat a lot of code. I agree.

**Comment by AbdelrahmanHafez** [comment]
Welcome @jamiscript 

I'll be closing this issue, please open a new issue and follow the issue template.

**Comment by jamiscript** [comment]
Oh, thanks for the advise, I'll open one with the correct template.
