### ISSUE TITLE
Cannot create text index with default_language: 'none'

### ISSUE THREAD

**Issue by adisaktijrs** [Automattic/mongoose#9490]
Hi, I try to create search feature using $text and $search in mongoose but it stuck when the query meet mongodb english "stop words". I try to change my default_language to none to ignore the "stop words" list but then I realized that I cannot change the default_language.

I was wondering the way my mongoose always create index with default_language: english, even I directly use default_language: 'none'.

Here is my code:

```
kataSchema.index({ kata: "text" }, { default_language: 'none' });
```
and then when I open mongo shell and type db.katas.getIndexes(), it's always showing me this:

```
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_"
	},
	{
		"v" : 2,
		"key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
		"name" : "kata_text",
		"background" : true,
		"weights" : {
			"kata" : 1
		},
		"default_language" : "english",
		"language_override" : "language",
		"textIndexVersion" : 3
	}
]
```

I also try to delete the index in mongo shell and run my code again but it still use english as its default_language.

Do I miss at something or else? I was already searching for it everywhere but still cannot find the issue. Thanks for advice

**Comment by vkarpov15** [comment]
Which version of MongoDB are you using and are you sure you're deleting the index? The below script shows that Mongoose is setting the default index correctly as long as there isn't a conflicting index in place:

```javascript
const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = mongoose.Schema({ name: String });
  schema.index({ name: 'text' }, { default_language: 'none' });

  const Model = mongoose.model('Test', schema);
  await Model.init();

  console.log('Done', await Model.listIndexes());
}
```

Output:

```
$ node gh-9490.js 
Mongoose: tests.ensureIndex({ name: 'text' }, { default_language: 'none', background: true })
(node:92696) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: tests.listIndexes()
Done [
  { v: 2, key: { _id: 1 }, name: '_id_' },
  {
    v: 2,
    key: { _fts: 'text', _ftsx: 1 },
    name: 'name_text',
    default_language: 'none',
    background: true,
    weights: { name: 1 },
    language_override: 'language',
    textIndexVersion: 3
  }
]
^C
```

**Comment by adisaktijrs** [comment]
Hi, thank you for your help. I'm new with mongodb and mongoose so please bear with me.

Yes, I'm sure I have deleted the index and when i check it on mongo shell, it gave me this:
```
[ { "v" : 2, "key" : { "_id" : 1 }, "name" : "_id_" } ]
```
And I use mongoose: 5.10.0 and mongoDB: 4.4.0.

Then, I finally use `ensureIndex` with node-mongodb-native driver operation:
```
Kata.collection.ensureIndex({ kata: "text" }, { default_language: "none" });
```
And it's finally working. Yet I will also try your solution as well. Thanks in advice.
