### ISSUE TITLE
Is there a reason that we shouldn't be able to easily access the collection name from schemas, models, documents, queries?

### ISSUE THREAD

**Issue by nth-chile** [Automattic/mongoose#9491]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Is there a reason that we shouldn't be able to easily access the collection name from schemas, models, documents, queries?

**What is the expected behavior?**

```
import { MyModel } from '../models'

const collection = MyModel.collection

...

const findResult = await MyModel.find(...)

const collection = findResult.collection

```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongodb: ^3.1.4
mongoose: ^5.3.13
node: 13.7.0

**Comment by AbdelrahmanHafez** [comment]
Welcome @nth-chile
Try the script below, I was able to get the collection name from all of the things you mentioned except for schemas, because schemas are reusable and there is no way for mongoose to know which collection the schema is going to be used for. I'll close this issue, please let me know if you need any further assistance.

### 9491.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema, 'my_users_collection');

  console.log(User.collection.name);

  const user = new User({ name: 'Hafez' });
  console.log(user.constructor.collection.name);

  await user.save();

  const query = User.findOne();

  console.log(query.model().collection.name);

  const foundUser = await query;
  console.log(foundUser.collection.name);
  console.log('All assertions passed.');
}
```

### Output
```
my_users_collection
my_users_collection
my_users_collection
my_users_collection
All assertions passed.
```

**Comment by nth-chile** [comment]
@AbdelrahmanHafez amazing! After all the research I did 😂
