### ISSUE TITLE
Virtual Population returning empty array with an array localField

### ISSUE THREAD

**Issue by tareqdayya** [Automattic/mongoose#9498]
**Do you want to request a *feature* or report a *bug*?**
Not sure.

**What is the current behavior?**
Using an array field for localField along with a single field for foreignField inside a virtual and attempting to populate that virtual returns an empty array.

**If the current behavior is a bug, please provide the steps to reproduce.**
`const studentSchema = new Schema({
  name: { type: String },
  languages: [{ type: String }],
});

 const languageSchema = new Schema({
  name: { type: String },
  code: { type: String },
});

 // VIRTUAL
  studentSchema.virtual('userLanguages', {
  ref: 'Language', // ref to languageSchema model
  localField: 'languages',
  foreignField: 'code',
  justOne: false,
});`

**What is the expected behavior?**
This should populate languages, instead, I get an empty array.
`Student.findOne({}).populate('userLanguages')`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.12.0
Mongoose 5.10.9
MongoDB 4.2.3

**Comment by vkarpov15** [comment]
The issue is that you're using the same name for the virtual as the `localField`. So the virtual overwrites the local field. Do `studentSchema.virtual('languages$', { ... })` and it should work.

**Comment by tareqdayya** [comment]
@vkarpov15 sorry, that didn't work.
I updated with the OP with a differently-named virtual.

**Comment by vkarpov15** [comment]
The below script shows that virtual populate finds language docs correctly:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const studentSchema = new mongoose.Schema({
    name: { type: String },
    languages: [{ type: String }],
  });

  const languageSchema = new mongoose.Schema({
    name: { type: String },
    code: { type: String },
  });

  // VIRTUAL
  studentSchema.virtual('userLanguages', {
    ref: 'Language', // ref to languageSchema model
    localField: 'languages',
    foreignField: 'code',
    justOne: false,
  });

  const Language = mongoose.model('Language', languageSchema);
  const Student = mongoose.model('Student', studentSchema);

  await Language.create({ name: 'English', code: 'en' });
  await Language.create({ name: 'French', code: 'fr' });
  await Language.create({ name: 'German', code: 'de' });

  await Student.create({ name: 'test', languages: ['fr', 'de'] });

  const res = await Student.findOne().populate('userLanguages');
  console.log(res.userLanguages);
}
```

Please modify the above script to demonstrate your issue.

**Comment by tareqdayya** [comment]
This is strange. I ran your code, and it worked like it should. Then I went back to running my code (without making any change to it, I checked my git), and it worked! I'm not even using a database by the name of "test".

**Comment by vkarpov15** [comment]
Strange. So can I consider this issue closed?

**Comment by tareqdayya** [comment]
@vkarpov15 I think so 😄since we can't reproduce it, what would be the point of keeping it open.
Anyway, thank you.
