### ISSUE TITLE
Field not persisted if value equals getter return value

### ISSUE THREAD

**Issue by maxaggedon** [Automattic/mongoose#9501]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A required path is not marked as modified when it was not set before if a getter returns the same value.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const schema = new Schema({
  title: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    min: 0
  },
  taxPercent: {
    type: Number,
    required: function() {
      return this.price != null;
    },
    min: 0,
    max: 100,
    get: value => value ?? 10
  }
})

const Model = mongoose.model("Model", schema),

const doc = await Model.create({
  title: "original"
});

original.set({
  title: "updated",
  price: 10,
  taxPercent: 10
})

// won't persist `taxPercent` as the specified value equals the returned value of the getter
await doc.save();
```

**What is the expected behavior?**
`taxPercent` should be in `modifiedPaths` as the persisted doc does not contain it and it was now set (and required!)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: v10.19.0
mongodb: v3.4.14
mongoose: v5.6.5

**Comment by maxaggedon** [comment]
I patched `$__shouldModify` in document.js to achieve the desired behaviour. If this is considered an actual bug by maintainers, I can open a PR.

**Comment by samtsai15** [comment]
Hi ,I test your sample code.

I removed schema property `taxPercent.get` and print after `doc.set`

```
// Mongoose version : 5.9.24

doc.set({
    title: 'updated',
    price: 10,
    taxPercent: 10,
  });

console.log(doc.modifiedPaths()); // =>  [ 'title', 'price', 'taxPercent' ]
```

Hope it will help.

**Comment by maxaggedon** [comment]
@samtsai15 thanks for your reply, unfortunately I need this to provide a consistent default value on the server.
As you can see, the concerned field is not always required, but the getter provides a default value we use on various clients to provide an initial value in form inputs. Therefore removing the getter would require us to right a `getTaxPercent()` function and ensure this one is used instead of the `taxPercent` field...
