### ISSUE TITLE
Can't use Models on multiple Database Connections 

### ISSUE THREAD

**Issue by Beanster199** [Automattic/mongoose#9502]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
I'm following [Mongoose Connection Docs](https://mongoosejs.com/docs/connections.html#multiple_connections) to create multiple database connections on my express app.
When importing Schemas scoped to a connection, and try to use Models methods, i get the next error: 

> UserSchema.find is not a function

**If the current behavior is a bug, please provide the steps to reproduce.**

models/user.js
```
const { Schema } = require('mongoose');

const UserSchema = new Schema({
    name: { type: String},
    lastname: { type: String}
});

module.exports = UserSchema;
```

databases/connection_1.js

```
const mongoose = require('mongoose');
const { Keys } = require('../keys');

const conn = mongoose.createConnection(
    `mongodb://${Keys.DatabaseUser}:${Keys.DatabasePassword}@${Keys.DatabaseHost}/${Keys.DatabaseShema}`
    , { 
        useNewUrlParser: true,
        useCreateIndex: true,
        useFindAndModify: true
    });

    conn.model('User', require('../models/user'), 'Users')

module.exports = conn;
```

routes/index.js

```
const app = require('express').Router();
const UserSchema = require('../models/user');

app.get('/index', async (req,res) => {
    console.log(await UserSchema.find({name: 'Jhon Doe'}))  // <-- Here i have the error: ( UserSchema.find is not a function )
})

module.exports = app;
```

**What is the expected behavior?**

So i understand i need to scope a Schema to a connection and there declare it as Model. Is there something i'm making wrong  or i just forgot? 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: 14.14.0
Mongoose: 5.10.9
MongoDB: 3.6.12 Community?

**Comment by samtsai15** [comment]
You need query with `Model` , not `Schema` 

```
// routers/index.js
const conn = require('../databases/connection_1');

// get User model
const userModel = conn('User');


// access with Model
... await UserModel.find({...})

```

**Comment by Beanster199** [comment]
> You need query with `Model` , not `Schema`
> 
> ```
> // routers/index.js
> const conn = require('../databases/connection_1');
> 
> // get User model
> const userModel = conn('User');
> 
> 
> // access with Model
> ... await userModel.find({...})
> ```

I tried this, but i can't retrieve the Model from the Connection Object 😫

**Comment by vkarpov15** [comment]
@Beanster199 you can access models by name using [`conn.model()`](https://mongoosejs.com/docs/api/connection.html#connection_Connection-model). In your case, `const userModel = conn.model('User')`.
