### ISSUE TITLE
find(), findAndModify() hang when Mongoose connection goes down 

### ISSUE THREAD

**Issue by brenzenb** [Automattic/mongoose#951]
When executing a query using Mongoose, if the connection goes down (maybe the VPN dropped, internet failed), the query hangs without returning a callback.  

This is expected behavior due to Mongoose's 'optimistic' query handling, where it assumes that all queries will be run once the connection returns.  I thought I'd be able to get around this by adding a 'socketTimeout' or 'wtimeout' option to my queries, but it doesn't appear to be working.  

Here are examples, using Coffeescript:

``` javascript
query = 
  _id:  {$in: ['exampleId1', 'exampleId2']}
ModelObject.find query, null, {socketTimeout:100}, (err, result) ->
  console.log err, result
```

OR

``` javascript
Collection.findAndModify query, [], {}, {remove:true, socketTimeout:100}, (err, checkin)->
  console.log err, result
```

Can anyone identify what I'm doing wrong?  Would setting a timeout for reads/writes actually force the callback to be throw when the connection goes down?  

Thanks in advance,
   Brian Renzenbrink

**Comment by tal-ni** [comment]
Does someone plans to solve this issue? is is so critical if the behavior of the driver is to just hangs
