### ISSUE TITLE
Connection fail on any Mongoose version over 10.7.12 [Ubuntu 20.04]

### ISSUE THREAD

**Issue by Snick-m** [Automattic/mongoose#9510]
Hello. I'm working on a Ubuntu 20.04 machine. 

`{
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
    useFindAndModify: false,
  }`

These are my connection options.

`"mongodb+srv://[CENSOR]:[CENSOR]@maineatcluser.rsb2q.gcp.mongodb.net/destinations?retryWrites=true&w=majority"`

and this is my connection URI.

Details of libraries and versions I get Error on :-
```
"mongodb": "^3.6.2",
"mongoose": "^5.10.11",

Node Version : 14.15.0
```

Details of Working setup :-
```
"mongodb": "^3.6.2",
"mongoose": "5.7.12",

Node Version : 14.15.0
```

I am pretty sure the `mongodb` version in my `package.json` probably doesn't matter but including anyways.

**Please Note that I have 0.0.0.0 whitelisted so this is not an IP Whitelist issue.

Also the problem only persists on this Ubuntu 20.04 Machine. I have a Windows 10 Setup in home [Development environment] Where it's all okay.**

```
{ MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/home/brix/Project_EAT/eat_backend/node_modules/mongoose/lib/connection.js:803:32)
    at cb (/home/brix/Project_EAT/eat_backend/node_modules/mongoose/lib/index.js:342:10)
    at Promise (/home/brix/Project_EAT/eat_backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/brix/Project_EAT/eat_backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose.connect (/home/brix/Project_EAT/eat_backend/node_modules/mongoose/lib/index.js:341:10)
    at Object.<anonymous> (/home/brix/Project_EAT/eat_backend/index.js:55:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  message:
   'Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you\'re trying to access the database from an IP that isn\'t whitelisted. Make sure your current IP address is on your Atlas cluster\'s IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/',
  reason:
   TopologyDescription {
     type: 'ReplicaSetNoPrimary',
     setName: null,
     maxSetVersion: null,
     maxElectionId: null,
     servers:
      Map {
        'maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017' => [ServerDescription],
        'maineatcluser-shard-00-01.rsb2q.gcp.mongodb.net:27017' => [ServerDescription],
        'maineatcluser-shard-00-02.rsb2q.gcp.mongodb.net:27017' => [ServerDescription] },
     stale: false,
     compatible: true,
     compatibilityError: null,
     logicalSessionTimeoutMinutes: null,
     heartbeatFrequencyMS: 10000,
     localThresholdMS: 15,
     commonWireVersion: null } }
```

**Comment by vkarpov15** [comment]
Can you please show the code you're using to connect to MongoDB?

**Comment by Snick-m** [comment]
> Can you please show the code you're using to connect to MongoDB?

```javascript
const dbClient = require("mongoose");

const uri = "mongodb+srv://[CENSOR]:[CENSOR]@maineatcluser.rsb2q.gcp.mongodb.net/destinations?retryWrites=true&w=majority";
```

```javascript
dbClient
  .connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
    useFindAndModify: false,
  })
  .then(() => {
    httpsServer.listen(5000, (err) =>
      err ? console.error(err) : console.log("LISTENING on 5000")
    );
  })
  .catch((error) => console.error(error));

function hasLocationData(queries) {
  let keys = Object.keys(queries);
```

**Comment by vkarpov15** [comment]
@p3x-robot @Snick-m can you please paste the output of `error.reason.servers`? Would be handy to see what Mongoose has to say about the individual servers you're connecting to.

**Comment by Snick-m** [comment]
> @p3x-robot @Snick-m can you please paste the output of `error.reason.servers`? Would be handy to see what Mongoose has to say about the individual servers you're connecting to.

@vkarpov15 

Yes I'm posting the output but I strongly doubt the error is caused by server. As I can connect with MongoDB Compass from the problematic machine.

**Comment by Snick-m** [comment]
Here's the output of `error.reason.servers`

```
Map(3) {
  'maineatcluser-shard-00-02.rsb2q.gcp.mongodb.net:27017' => ServerDescription {
    address: 'maineatcluser-shard-00-02.rsb2q.gcp.mongodb.net:27017',
    error: MongoNetworkTimeoutError: connection timed out
        at connectionFailureError (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:342:14)
        at TLSSocket.<anonymous> (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:310:16)
        at Object.onceWrapper (events.js:421:28)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket.Socket._onTimeout (net.js:483:8)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7),
    roundTripTime: -1,
    lastUpdateTime: 206188231,
    lastWriteDate: null,
    opTime: null,
    type: 'Unknown',
    topologyVersion: undefined,
    minWireVersion: 0,
    maxWireVersion: 0,
    hosts: [],
    passives: [],
    arbiters: [],
    tags: []
  },
  'maineatcluser-shard-00-01.rsb2q.gcp.mongodb.net:27017' => ServerDescription {
    address: 'maineatcluser-shard-00-01.rsb2q.gcp.mongodb.net:27017',
    error: MongoNetworkTimeoutError: connection timed out
        at connectionFailureError (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:342:14)
        at TLSSocket.<anonymous> (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:310:16)
        at Object.onceWrapper (events.js:421:28)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket.Socket._onTimeout (net.js:483:8)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7),
    roundTripTime: -1,
    lastUpdateTime: 206188235,
    lastWriteDate: null,
    opTime: null,
    type: 'Unknown',
    topologyVersion: undefined,
    minWireVersion: 0,
    maxWireVersion: 0,
    hosts: [],
    passives: [],
    arbiters: [],
    tags: []
  },
  'maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017' => ServerDescription {
    address: 'maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017',
    error: MongoNetworkTimeoutError: connection timed out
        at connectionFailureError (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:342:14)
        at TLSSocket.<anonymous> (/home/brix/mongoose_test/node_modules/mongodb/lib/core/connection/connect.js:310:16)
        at Object.onceWrapper (events.js:421:28)
        at TLSSocket.emit (events.js:315:20)
        at TLSSocket.Socket._onTimeout (net.js:483:8)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7),
    roundTripTime: -1,
    lastUpdateTime: 206188236,
    lastWriteDate: null,
    opTime: null,
    type: 'Unknown',
    topologyVersion: undefined,
    minWireVersion: 0,
    maxWireVersion: 0,
    hosts: [],
    passives: [],
    arbiters: [],
    tags: []
  }
}
```

**Comment by Snick-m** [comment]
> what fixed it was that i re-indexed every database and collections and the error is gone.

Hi @p3x-robot , Could you please provide me a short brief on how I may do that?

**Comment by vkarpov15** [comment]
My best guess is that `reIndex()` would not do anything to help this issue, but I've been wrong before.

Are you able to connect using the `mongo` shell from your Ubuntu box? Run `mongo "mongodb+srv://[CENSOR]:[CENSOR]@maineatcluser.rsb2q.gcp.mongodb.net/destinations?retryWrites=true&w=majority"` to try.

The "connection timed out" error is unfortunately not very helpful, all it tells me is that Node.js' socket is timing out when trying to connect to your Atlas servers and isn't getting any response. I suspect it is a networking issue, and if you can't connect using the mongo shell then that makes network issue the most likely explanation.

**Comment by Snick-m** [comment]
> My best guess is that `reIndex()` would not do anything to help this issue, but I've been wrong before.
> 
> Are you able to connect using the `mongo` shell from your Ubuntu box? Run `mongo "mongodb+srv://[CENSOR]:[CENSOR]@maineatcluser.rsb2q.gcp.mongodb.net/destinations?retryWrites=true&w=majority"` to try.
> 
> The "connection timed out" error is unfortunately not very helpful, all it tells me is that Node.js' socket is timing out when trying to connect to your Atlas servers and isn't getting any response. I suspect it is a networking issue, and if you can't connect using the mongo shell then that makes network issue the most likely explanation.

Well my instant guess was network issue or a network block or something of the like so I tried, 
 1. Accessing collections through browser.
 2. MongoDB Compass.

I'll try the mongo shell and report back.

**Comment by Snick-m** [comment]
@vkarpov15  Hi I just tried mongo shell and it seems to connect without a problem.

**Comment by Snick-m** [comment]
I think it might be a problem with the MongoDB dependency. Because I remembered that before I used native mongodb drivers to connect and latest version created this error. But version 3.4.0 was working. I hadn't tried anything higher than that.

**Comment by vkarpov15** [comment]
Hmm this is very strange. Couple followup questions:

1. By "I just tried mongo shell and it seems to connect without a problem." do you mean you can connect from your Ubuntu 20.04 box using the mongo shell? Or from your Windows machine?
2. Can you try connecting using the non-`+srv` connection string? For example, `mongodb://[CENSOR]:[CENSOR]@maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017,maineatcluser-shard-00-01.rsb2q.gcp.mongodb.net:27017,maineatcluser-shard-00-02.rsb2q.gcp.mongodb.net:27017/destinations?retryWrites=true&w=majority&ssl=true`
3. Can you try connecting to one of the servers directly as opposed to connecting to the replica set? For example, `mongodb://[CENSOR]:[CENSOR]@maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017/destinations?ssl=true`

**Comment by admosity** [comment]
Stumbled on this issue after it failing on mac with mongodb 4.4.0 with the latest mongoose version (5.10.15). It looks like the parser kicks the bucket (parses mongodb, but not the rest):

```MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb```

After downgrading seems to work fine. Downgraded to 5.7.14 in my case.

**Comment by jaffarc** [comment]
I had the same problem:
version mongodb Server version 4.2.10 

````
connection disconnected MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27015
    at NativeConnection.Connection.openUri (/var/www/testeconn/node_modules/mongoose/lib/connection.js:821:32)
    at Mongoose.createConnection (/var/www/testeconn/node_modules/mongoose/lib/index.js:284:17)
    at Object.<anonymous> (/var/www/testeconn/teste.js:17:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'prod',
    maxSetVersion: 99740,
    maxElectionId: 7fffffff0000000000000012,
    servers: Map { '127.0.0.1:27015 => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 8
  }
}

 var uri = 'mongodb://[user]:[pass]@[ip]:27015/ecommerce_test?authSource=ecommerce_test&authMechanism=SCRAM-SHA-1&w=majority'
mongoose.Promise = Promise;
let options = {
  keepAlive: true,
  connectTimeoutMS: 300000,
  socketTimeoutMS: 300000,
  useNewUrlParser: true,
  useFindAndModify: false,
  bufferMaxEntries: 0,
  poolSize: 4,
  useUnifiedTopology: true
};

let connection = mongoose.createConnection(uri, options);

connection.once("open", function () {
  console.log("MongoDB database connection established successfully");
});
connection.once('error', function (err) {
  console.log('connection disconnected', err);
})
````

I already tried to go  Downgraded to 5.7.14 in my case  but it was not

**Comment by jaffarc** [comment]
> the similar problem was, i had a zombie process, that was stuck in jenkins, after i killed the process, the error was not happening anymore.

But I connect normally through NOSQLBooster.

**Comment by Snick-m** [comment]
> Hmm this is very strange. Couple followup questions:
> 
> 1. By "I just tried mongo shell and it seems to connect without a problem." do you mean you can connect from your Ubuntu 20.04 box using the mongo shell? Or from your Windows machine?
> 2. Can you try connecting using the non-`+srv` connection string? For example, `mongodb://[CENSOR]:[CENSOR]@maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017,maineatcluser-shard-00-01.rsb2q.gcp.mongodb.net:27017,maineatcluser-shard-00-02.rsb2q.gcp.mongodb.net:27017/destinations?retryWrites=true&w=majority&ssl=true`
> 3. Can you try connecting to one of the servers directly as opposed to connecting to the replica set? For example, `mongodb://[CENSOR]:[CENSOR]@maineatcluser-shard-00-00.rsb2q.gcp.mongodb.net:27017/destinations?ssl=true`

@vkarpov15 

1. I meant from my Ubuntu 20.04.
2. I've tried that and it was no use. Same error.
3. No use either. Same error.

**Comment by jaffarc** [comment]
My case it worked i removed
```
 useUnifiedTopology: true


let options = {
  keepAlive: true,
  connectTimeoutMS: 300000,
  socketTimeoutMS: 300000,
  useNewUrlParser: true,
  useFindAndModify: false,
  bufferMaxEntries: 0,
  poolSize: 4
};
(node:56986) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Express server listening on port  3000
Mongodb connection
```

**Comment by Snick-m** [comment]
> My case it worked i removed
> 
> ```
>  useUnifiedTopology: true
> 
> 
> let options = {
>   keepAlive: true,
>   connectTimeoutMS: 300000,
>   socketTimeoutMS: 300000,
>   useNewUrlParser: true,
>   useFindAndModify: false,
>   bufferMaxEntries: 0,
>   poolSize: 4
> };
> (node:56986) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> Express server listening on port  3000
> Mongodb connection
> ```

I think this might ACTUALLY work for me as well... Allowing more time before timeout?

**Comment by Snick-m** [comment]
Okay so it seems just passing `connectTimeoutMS: 300000,` is enough to fix the problem for me.
