### ISSUE TITLE
use Model's api  can't find the data by “_id

### ISSUE THREAD

**Issue by necessityOVO** [Automattic/mongoose#9513]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
use api  Model.findOne  by “_id” , but it return null , but use other field like "name" I can find it
<img src="https://user-images.githubusercontent.com/60960561/97945429-83618780-1dc2-11eb-8694-019cc31f88bc.png" alt="{UF~F5 DKT{QR {~ZMZ J%4" style="zoom: 33%;" />
**If the current behavior is a bug, please provide the steps to reproduce.**

I can find the data by "_id" in mongoDB compass , here is the capture.
<img src="https://user-images.githubusercontent.com/60960561/97945468-9c6a3880-1dc2-11eb-88f4-b61902ed4f9b.png" alt="Y}P~%H@H47F 1L$DIDOEY44" style="zoom: 33%;" />

 use other field like "name" I can find it like here.
<img src="https://user-images.githubusercontent.com/60960561/97945725-4cd83c80-1dc3-11eb-9f70-4b3a2c6c9c14.png" alt="image" style="zoom: 33%;" />

**What is the expected behavior?**
I expected it can return the data like mongoDB compass.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
    "mongoose": "^5.10.11"
    "node":"v14.7.0“”
    "MongoDB" :"5.10.11"

**Comment by makuzaverite** [comment]
`findOne({ _id: id })` returns null if the id passed doesnot exists in the database

Why can't you just use `model.findbyId()`

https://mongoosejs.com/docs/api.html#model_Model.findById

**Comment by necessityOVO** [comment]
> `findOne({ _id: id })` returns null if the id passed doesnot exists in the database
> 
> Why can't you just use `model.findbyId()`
> 
> https://mongoosejs.com/docs/api.html#model_Model.findById

thanks for your response ; 
`model.findById()` still doesn't work , I 'm sure the id exists in the database, I doubt if the type of id is correct now

**Comment by makuzaverite** [comment]
This supposed to work 

screen shots on how you are doing it

**Comment by necessityOVO** [comment]
![image](https://user-images.githubusercontent.com/60960561/97964099-2b8f4480-1df3-11eb-9ee1-6b42a88b154f.png)
 and I can find the data by MongoDB Compass 
![image](https://user-images.githubusercontent.com/60960561/97964279-78731b00-1df3-11eb-8e9f-f13d169da4e2.png)
I just know mongoose a little , is it possible that the type of field of schema is wrong?

**Comment by makuzaverite** [comment]
No the type of schema is not wrong 

So to help i would suggest to give me a repo link so that i can run code and figure out what wrong

**Comment by makuzaverite** [comment]
I think you are using method in wrong way 

see `const result = await model.findById(id).exec();`

then `console.log(result)` I think this is how is should be used not that way you have used it

**Comment by necessityOVO** [comment]
I find the reason! 
when I import the data to the database, the mongoDB Compass report the "id" error, so I change the id's type to String by mistake. It works after reimporting the data.
thanks for your help ^^

**Comment by makuzaverite** [comment]
Thanks

**Comment by xiaoxin-sky** [comment]
> I find the reason!
> when I import the data to the database, the mongoDB Compass report the "id" error, so I change the id's type to String by mistake. It works after reimporting the data.
> thanks for your help ^^

thanks，I meet the same problem。
