### ISSUE TITLE
Recognize discriminator key of array type in query

### ISSUE THREAD

**Issue by KL-Dev1** [Automattic/mongoose#9514]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`model.countDocuments` throws an error when providing an array to the discriminator key, because it can't parse the array.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a model, let's say it's called 'Action'. This is the base model for all other types of actions, which have their own model extending the base. They are listed as discriminators with the field `type` as well, which works fine.
The problem is I'm trying to countDocuments on the base model, while filtering out 2 types using the $in queryOption.

Example:
```
interface Action {
  title: string;
}

interface ActionAddNote extends Action {
 content: string;
}

interface ActionCreatePDF extends Action {
 fileName: string;
}

const numberOfActions = await Action.countDocuments({
  type: { $in: ['AddNote', 'CreatePDF'] }
});
```

The `cast` function fails with the following error: 'TypeError: Cannot read property 'path' of undefined at cast (mongoose\lib\cast.js:106:17)'. I have debugged this function and found that it tries to find the discriminator with the following key `{$in: ['AddNote', 'CreatePDF']}`.

**What is the expected behavior?**
I don't know if the correct behavior would be to parse the array. Perhaps the best option would be to use the base model in the case of an $in array.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS: 14.4.0
Mongoose: 5.9.15
MongoDB: 4.2.8

**Comment by vkarpov15** [comment]
The below script works as intended in Mongoose v5.9.15, no error thrown. Based on your stack trace, I'd guess you're using embedded discriminators somewhere? Please modify the below script to demonstrate the issue you're seeing.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String }, { discriminatorKey: 'type' });
  const Action = mongoose.model('Action', schema);

  const ActionAddNote = Action.discriminator('AddNote', Schema({ content: String }));
  const ActionCreatePDF = Action.discriminator('CreatePDF', Schema({ filename: String }));

  await ActionAddNote.create({ content: 'foo' });

  const numberOfActions = await Action.countDocuments({
    type: { $in: ['AddNote', 'CreatePDF'] }
  });
  console.log(numberOfActions);
}
```
