### ISSUE TITLE
Impossible to catch exception in startSession() when database is down

### ISSUE THREAD

**Issue by vviotto** [Automattic/mongoose#9515]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Let me start by saying that I'm connecting to a local replica set with only one node, for testing purposes, on a windows machine.
When trying to start a session while the mongodb server is down, the startSession function throws an error instead of rejecting the promise with the error, making it impossible to catch, node will then proceed to throw an 'uncaughtException' error.

Here is the stack trace for the error:
```
uncaughtException MongoError: Current topology does not support sessions
    at MongoClient.startSession (C:\repos\mongotest\node_modules\mongodb\lib\mongo_client.js:458:11)
    at NativeConnection.startSession (C:\repos\mongotest\node_modules\mongoose\lib\connection.js:419:31)
    at C:\repos\mongotest\node_modules\mongoose\lib\connection.js:559:14
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a sample app to test the problem:
```javascript
const express = require('express');
const mongoose = require('mongoose');

// Unhandled Exception listeners
process.on('unhandledRejection', (err) => {
  console.log('unhandledRejection', err);
});
process.on('uncaughtException', (err) => {
  console.log('uncaughtException', err);
});

const app = express();

const user = 'admin';
const password = 'admin';
const host = '127.0.0.1';
const port = '27017';
const database = 'mongotest';
const poolSize = 25;

const stringConnection = `mongodb://${user}:${password}@${host}:${port}/${database}`;

mongoose
  .connect(stringConnection, {
    poolSize,
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log('Connection to the database has been established successfully.');
  })
  .catch((err) => {
    console.log(`Unable to connect to the database: ${err}`);
  });

app.get('/', async (req, res, next) => {
  let mongoSession;
  try {
    mongoSession = await mongoose.startSession();
  } catch (err) {
    next(err);
  }

  mongoSession.endSession();
  res.sendStatus(200);
});

// Global error handler
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  res.sendStatus(500);
});

app.listen(4000, () => {
  console.log(`HTTP Server listening on port 4000`);
});
```
1. Start the app and wait for connection with the database
2. Shut down the mongoDB server (in windows, I'm stopping the mongoDB service)
3. Make a request to the '/' endpoint, no response will be returned and the console will show the uncaught exception.

Its also worth noting that when making a request to the same endpoint with the mongoDB server up, the ok response is sent back, that means the server was started correctly as a replica set and sessions are working. 

**What is the expected behavior?**
Based on the docs, the startSession returns a promise, in that case, it should return a rejected promise so we can catch and deal with the error.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node:  v12.18.3
mongoose: 5.10.9
mongoDB: 4.4.1

**Comment by vviotto** [comment]
After some quick investigation, the problem might be the line 420 in the '\lib\connection.js' file.

```javascript
Connection.prototype.startSession = _wrapConnHelper(function startSession(options, cb) {
  if (typeof options === 'function') {
    cb = options;
    options = null;
  }
  const session = this.client.startSession(options);
  cb(null, session); // <--------- this might be the problem
});
```

The code that wraps the function in a promise calls the function with the following callback:
```javascript
  return new Promise((resolve, reject) => {
    fn(function(error, res) { // <----------- This is calling the original startSession function, with a callback
      if (error != null) { // <---------------- This will never be true
        if (ee != null && ee.listeners('error').length > 0 && !error[emittedSymbol]) {
          error[emittedSymbol] = true;
          ee.emit('error', error);
        }
        return reject(error);
      }
      if (arguments.length > 2) {
        return resolve(Array.prototype.slice.call(arguments, 1));
      }
      resolve(res);
    });
  });
```

**Comment by vkarpov15** [comment]
Closed by https://github.com/Automattic/mongoose/commit/9892367113caea3d9dd1bd57180b7f182cf8881f :+1:
