### ISSUE TITLE
special treatment on string[12] passed into findOne() ?

### ISSUE THREAD

**Issue by willyong82** [Automattic/mongoose#9524]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
.findOne() returns null only when we passed in id with string length 12characters or 24characters

**If the current behavior is a bug, please provide the steps to reproduce.**

someModel.findOne({_id:'123456789012'})
somoModel.findById('012345789012345678901234')
someModel.findById('aaaaaaaaaabbbbbbbbbbcccc')

**What is the expected behavior?**
should throw error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: dockerized node:12.13.0-alpine 
mongo: dockerized mongo:4.0.5-xenial
mongoose: 5.10.13
monggose: 5.9. 20 here problem also exist before i do upgrade

**Comment by willyong82** [comment]
I've used both these pattern on creating schema which produced the same result
const someSchema = new mongoose.Schema({
        // this one:
  // _id: mongoose.Schema.Types.ObjectId,
         // and this one:
 //  id: String
})

**Comment by AbdelrahmanHafez** [comment]
Welcome @willyong82 

This is expected behavior, mongoose accepts either a string of 12 bytes or a string of 24 hex characters, and casts it into an object id.
