### ISSUE TITLE
Setting validateBeforeSave = true does not trigger pre/post validation hooks....

### ISSUE THREAD

**Issue by chaeron** [Automattic/mongoose#9525]
On mongoose 5.10.9.....

If you set the option validateBeforeSave: true for a save() Mongoose does not trigger pre/post validation hooks/middleware.

I think it should still call the hooks, just not do any validation in between.  We have some code that uses these hooks, but for some large documents we would like to turn validateBeforeSave off for performance reasons.  Right now we can't do that since we need the hooks to fire.

At the least a new save() option called callValidationMiddleware that can be set to true/false (maybe default of false to preserve existing behaviour) when using validateBeforeSave would be very useful.

Thank you!

**Comment by vkarpov15** [comment]
I'm hesitant to add another option for this, but thankfully there is a pretty simple workaround: call `validate()` with an empty `pathsToValidate` option in `pre('save')` if `validateBeforeSave` is turned off as shown below.

```javascript
  schema.pre('save', async function(next, options) {
    if (options.validateBeforeSave === false) {
      await this.validate([]).catch(() => {});
    }
  });
```

That tells Mongoose to call `validate()`, but not actually validate any paths, so that just executes validate middleware and avoids your expensive validators.

Here's a full script that you can tinker with.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const schema = new Schema({
    answer: {
      type: Number,
      validate: () => console.log('Validator called!')
    }
  });

  schema.pre('validate', function() {
    console.log('Pre validate!');
  });

  schema.pre('save', async function(next, options) {
    if (options.validateBeforeSave === false) {
      // Prints "Pre validate!" but **not** "Validator called!"
      await this.validate([]).catch(() => {});
    }
  });

  const Test = mongoose.model('Test', schema);

  const doc = new Test({ answer: 0.2 });
  await doc.save({ validateBeforeSave: false });

  console.log('done');
}

```

**Comment by vkarpov15** [comment]
Another alternative is for you to just call `await doc.validate([]).catch(() => {});` manually before you call `await doc.save({ validateBeforeSave: false })` if you just have one place where you're disabling `validateBeforeSave`

**Comment by chaeron** [comment]
The workaround you proposed will work perfectly, so many thanks for that!

**Comment by chaeron** [comment]
Hmmm....quick question though....when you call validate([]).catch(() => {}); on a document schema, will it also fire the validate middleware for subdocuments?  Or will we have to do a validate([]).catch(() => {}); on each subdoc as well?

Thanks!

**Comment by vkarpov15** [comment]
You would need to do `validate([])` on every subdoc unfortunately. The whole point of calling `validate([])` is that you don't actually run validation on any paths, and that includes subdocs, so Mongoose won't call `validate()` on the subdocs for you.

We should consider adding Mongoose's internal `getAllSubdocs()` function to the public API for this purpose.

**Comment by chaeron** [comment]
Any progress on exposing the internal getAllSubdocs() function publicly?
