### ISSUE TITLE
DocumentDB Compatibility?

### ISSUE THREAD

**Issue by twigs67** [Automattic/mongoose#9528]
Hello,

Not sure if this is the place for it, but is Mongoose compatible with DocumentDB? Are there any gotchas that make it a nightmare to work with? 

Thanks

**Comment by vkarpov15** [comment]
We don't officially support DocumentDB. There have been a few issues reported: https://github.com/Automattic/mongoose/issues/7800, https://github.com/Automattic/mongoose/issues/4596#issuecomment-302879926, https://github.com/Automattic/mongoose/issues/4455. We fix DocumentDB issues if we can, but we do not currently test against DocumentDB, nor do we have plans to.
