### ISSUE TITLE
Contributing Doc (mmapv1 deprecated in mongodb 4.2)

### ISSUE THREAD

**Issue by FlameFractal** [Automattic/mongoose#9529]
**Do you want to request a *feature* or report a *bug*?**

Documentation fix

**What is the current behavior?**

`CONTRIBUTING.md` states 

```- start a mongodb instance on port 27017 if one isn't running already. `mongod --dbpath <path to store data> --port 27017 --storageEngine mmapv1`. Mongoose tests run much faster on the mmapv1 storage engine as opposed to the WiredTiger storage engine.```

As [mmapv1 has been removed in MongoDB 4.2](https://www.mongodb.com/blog/post/going-in-mongodb-42), starting the server with the command in the doc gives error `Cannot start server with an unknown storage engine: mmapv1`

We should probably update the doc to reflect the same.

**Comment by vkarpov15** [comment]
Will do. We did a lot of work to make Mongoose tests not create too many collections: rapidly creating and dropping collections makes WiredTiger grind to a halt. Right now we typically run tests locally using the `inMemory` storage engine on MongoDB enterprise.
