### ISSUE TITLE
"Model" class is a subclass of "document" class

### ISSUE THREAD

**Issue by kjohnathan** [Automattic/mongoose#9533]
**Do you want to request a *feature* or report a *bug*?**

documentation - 
In the "document" part of the docs, it states that "Model" class is a subclass of "document" class. 
But later it shows that doc instanceof mongoose.model is true. Does it means that "document" class is actually a subclass of "model" class instead?

**Comment by vkarpov15** [comment]
No. In the source code, [Model inherits from Document](https://github.com/Automattic/mongoose/blob/fcc13413acc7bf1454ffa7270587a898aec8b7d0/lib/model.js#L106-L116). When you create a new model using `mongoose.model()`, you get a class that inherits from Model, and so also inherits from Document.
