### ISSUE TITLE
ECONNREFUSED error when trying to connect to replica set with down member

### ISSUE THREAD

**Issue by a0mrpge** [Automattic/mongoose#9536]
**Do you want to request a *feature* or report a *bug*?**
*Bug*
**What is the current behavior?**
When the 3 member mongodb replicaset is in failover state (1 or more nodes are down) mongoose throws the following error when trying to establish a connection:

```events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED XX.XX.X.XXX:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at /data/axe-platform/node_modules/mongodb/lib/core/sdam/server.js:507:14
    at createConnection (/data/axe-platform/node_modules/mongodb/lib/core/connection/pool.js:566:9)
    at connect (/data/axe-platform/node_modules/mongodb/lib/core/connection/pool.js:1008:9)
    at makeConnection (/data/axe-platform/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/data/axe-platform/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/data/axe-platform/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
execution errored with status: 1
```
While it does seem like the connections are established, this error is randomly thrown, and the ECONNREFUSED comes from the server that is down in the replica set. This will happen even if a secondary is shut down in the replica set. 

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce this issue we shutdown a replica set member, wait for a primary to be established, and then try to run a job that uses mongoose to connect to the mongodb replica set. We also tried it with shutting down a secondary. The connection is established in the following way:

```url = ""mongodb://user:password@hostname1:27017,hostname2:27017,hostname3:27017/db_name?authSource=admin"
 var options = {
        keepAlive: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
        socketTimeoutMS: 60000,
       replicaSet: "repl_set_name"
    }

var connection = mongoose.createConnection(url, options);
```

**What is the expected behavior?**
Expected behavior is that when the replica set is in failover state, Mongoose createConnection still works without throwing any errors. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Nodejs version: v10.17.0
Mongoose version: 5.8
Mongodb version: 4.2

**Comment by vkarpov15** [comment]
Try setting the `connectWithNoPrimary` option:

```javascript
 var options = {
        keepAlive: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
        socketTimeoutMS: 60000,
       replicaSet: "repl_set_name",
       connectWithNoPrimary: true
    }
```

This will tell Mongoose to connect even if it can't find a primary in the replica set.

**Comment by arian-press2015** [comment]
I have the same problem, but this option doesn't solve it. I have P-S-A replica set.
when I stop the primary instance, the secondary becomes primary. but when I start my code, it throws 'ECONNREFUSED' (because first instance is down), while I think it should work.
