### ISSUE TITLE
Annoying warnings

### ISSUE THREAD

**Issue by MathisTLD** [Automattic/mongoose#9538]
https://github.com/Automattic/mongoose/blob/86aace14dbd82a01ec996a6a4d1b4f6205484233/lib/schema.js#L654
This warning is annoying (i use the path increment in a sub-document Schema so it shouldn't interfere with versioning)
I think checking for path conflicts should be made when creating a model or at least I would appreciate a way to disable the following warning:
https://github.com/Automattic/mongoose/blob/86aace14dbd82a01ec996a6a4d1b4f6205484233/lib/schema.js#L601-L602

thanks for your help
PS: I'd love to make a PR but I don't know which way you think is the best

**Comment by vkarpov15** [comment]
We'll fix that. But you should be able to work around that if you set `versionKey: false` in your schema.

**Comment by MathisTLD** [comment]
> We'll fix that. But you should be able to work around that if you set `versionKey: false` in your schema.

I tried this but as we can see in the source code this is not how the thing is implemented, setting `versionKey: false` has no effect on the warning.

Anyway, thanks for your job 😊
