### ISSUE TITLE
After update, Mongoose functions (findOne, aggregate ...) on model hang indefinitely

### ISSUE THREAD

**Issue by rstoermer** [Automattic/mongoose#9539]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We were using Mongoose 5.9.1 for a while. After an update to 5.10.13 all our tests suddenly failed, that made use of the database (mongodb-memory-server). True enough, also outside of testing using the real database when running code manually a findOne for example didn't return anything anymore. Just for the sake of it I tried:
- Returning to only slightly newer 5.9.2
- Updating mongodb from 3.5.3 to 3.6.3
- Returning to 5.9.1 (Weirdly the error persists, only deleting the node_modules folder, resetting the package-lock and "npm i" fixes the problem)

**If the current behavior is a bug, please provide the steps to reproduce.**

We are using Express. Our app.js is requiring db.js ```require(global.__basepath + "src/config/db");``` which looks like:

```
const mongoose = require("mongoose");

const options = {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    poolSize: 10, // Maintain up to 10 socket connections
    bufferMaxEntries: 0,
    connectTimeoutMS: 2000,
    socketTimeoutMS: 45000
};

let MongoURI;
if (process.env.NODE_ENV === "local") {
    MongoURI = "mongodb://localhost:27019/db_dev";
    console.log("NODE_ENV: local");
} else {
    console.log("Error no db config found!!!");
    process.exit(1);
}

try {
    if (MongoURI) {
        mongoose.connect(MongoURI, options);

        console.log(`MongoDB trying to connect on ${MongoURI}`);
    }
} catch (err) {
    console.error(`Connection to DB failed with the following message: ${err.message}`);
    // Exit process with Failure
    process.exit(1);
}
```

Models are created in an own npm package, which hasn't changed in this update process. A sample model where I findOne doesn't work anymore looks like:

```
const mongoose = require("mongoose");
const fhirDatatypes = require("../fhirDatatypes");

const Organization = new mongoose.Schema({
    id: {
        type: String,
        required: true,
        unique: true,
        index: true
    },
    meta: {
        type: {
            profile: [String]
        },
        default: {profile: ["http://hl7.org/fhir/r4/organization.html"]}
    },
    resourceType: {
        type: String,
        default: "Organization"
    },
    partOf: {
        type: fhirDatatypes.Reference
    },
    type: {
        type: fhirDatatypes.CodableConcept
    },
    name: {
        type: String,
        required: true
    },
    address: {
        type: fhirDatatypes.Address
    }
});

module.exports = mongoose.model("fhir_organizations", Organization);
```

which is exported in the package in the index.js via:
```
module.exports = {
    Organization: require("./resources/Organization")
};
```

This code for example doesn't return anything anymore and just "hangs":
```
const {Organization} = require("@private/schemas");
return (await Organization.findOne(filter, projection).lean());
```

**What is the expected behavior?**
findOne works even after update

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.9.0
MongoDB on Server: 4.2.9

**Comment by vkarpov15** [comment]
Are you using Sinon or jest fake timers?

**Comment by vkarpov15** [comment]
I took a closer look and I suspect this issue is due to inconsistent versions of Mongoose between `require("@private/schemas")` and your top-level project. If you upgrade Mongoose in `@private/schemas` but not in your top level project, you'll end up with this issue because npm will install a separate version of Mongoose for `@private/schemas`, and that will lead to a different Mongoose instance. Which is a problem because you call `mongoose.connect()` on the top-level project, but define models in the `@private/schemas` package.

@jshkurti can you please provide some code samples?

**Comment by rstoermer** [comment]
> I took a closer look and I suspect this issue is due to inconsistent versions of Mongoose between `require("@private/schemas")` and your top-level project. If you upgrade Mongoose in `@private/schemas` but not in your top level project, you'll end up with this issue because npm will install a separate version of Mongoose for `@private/schemas`, and that will lead to a different Mongoose instance. Which is a problem because you call `mongoose.connect()` on the top-level project, but define models in the `@private/schemas` package.
> 
> @jshkurti can you please provide some code samples?

Might be the reason. What would be your suggestion to handle this? Export the Mongoose instance from the private package and reuse it in the top-level project?

**Comment by vkarpov15** [comment]
@rstoermer make Mongoose a [peer dependency](https://nodejs.org/es/blog/npm/peer-dependencies/) of `@private/schemas` and a dependecy of the top-level project.
