### ISSUE TITLE
Calling `toObject` on an instance of a MongooseArray does not return a native JS array

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#9540]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Calling `toObject` on an instance of a MongooseArray does not return a vanilla JS array

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const assert = require('assert')
const mongoose = require('mongoose')
const Schema = mongoose.Schema

it('Calling `toObject` on an instance of a MongooseArray should return a vanilla JS array', async () => {
   const bookSchema = new Schema({
      name: String,
      tags: [String]
   })

   const Book = mongoose.model('book', bookSchema)
   const book = new Book({
      name: 'Ghostwritten',
      tags: ['time', 'anthology']
   })

   assert.equal([].constructor , Array) // Sanity Test
   assert.equal(book.tags.constructor.name, 'CoreMongooseArray') // As Expected

   // This should pass!
   assert.equal(book.tags.toObject().constructor, Array)
})

```

**What is the expected behavior?**

According to the docs for `MongooseArray#toObject` (https://mongoosejs.com/docs/api.html#mongoosearray_MongooseArray-toObject), calling `toObject` should return a native JS array, but instead returns mongoose's special extended array object instance. (Actually I believe this is true for `toJSON` as well).

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

node.js: 14.5.0
mongoose: 5.10.13
MongoDB: 4.2.10

**Comment by w3hr** [comment]
i think there still issues with the toObject() method.

```
const assert = require('assert')
const mongoose = require('mongoose')
const Schema = mongoose.Schema

it('Calling `toObject` on an instance of a MongooseArray should return a vanilla JS array', async () => {
   const bookSchema = new Schema({
      name: String,
      tags: [String]
   })

   const Book = mongoose.model('book', bookSchema)
   const book = new Book({
      name: 'Ghostwritten',
      tags: ['time', 'anthology']
   })

   assert.equal([].constructor , Array) // Sanity Test
   // assert.equal(book.tags.constructor.name, 'CoreMongooseArray') // <-- fails

   assert.deepEqual(book.tags.toObject(), book.tags); // <-- both the same

   // This should pass!
   assert.equal(book.tags.toObject().constructor, Array)
})
```

i also see an error when i make an reference array to another model

```
  tags: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Tag',
      default: []
    }
  ],
```

 and populate this. the toObject function works there not as expected (give me an plain object array)


node.js: 16.6.1
mongoose: 6.4.4
MongoDB: 4.8.0

**Comment by vkarpov15** [comment]
@w3hr the script you provided passes on my machine with Mongoose 6.4.4. Can you please double check what version of Mongoose you're using using `console.log(mongoose.version)` ?

**Comment by w3hr** [comment]
@vkarpov15 i got v 6.4.4

u uncommented this line here?
`// assert.equal(book.tags.constructor.name, 'CoreMongooseArray') // <-- fails`

for the populate bug (i think its an bug), i will try to write another testcase tomorrow.
but in short: u have to create 2 models, one of them got an ref array (like in my previous answer, tags: [ ..), u populate this and execute .toObject() on it. In this case i would not get the expected result (an plain object array)

**Comment by vkarpov15** [comment]
@w3hr as far as I can tell, `assert.equal(book.tags.constructor.name, 'CoreMongooseArray')` should fail, `book.tags` is a proxied array instead of an instance of an array subclass in Mongoose 6.
