### ISSUE TITLE
_id is not return when it is an object

### ISSUE THREAD

**Issue by hazz1925** [Automattic/mongoose#9548]
**Do you want to request a *feature* or report a *bug*?**

Bug 

**What is the current behavior?**

Then `_id` property is not returned when doing `model.find()`

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a mongodb view by using aggregation pipeline and in the pipeline stage I am doing a group by 2 fields as follows: 

```
        {
          $group: {
            _id: {
              itemId: '$itemId',
              merchantId: '$merchantId',
            },
            currentQuantity: { $sum: '$variance' },
          },
        },
```

This results in mongodb creating a collection with the `_id` field being and object with `itemId` and `merchantId` as follows:

```
    "_id" : {
        "itemId" : "item-4",
        "merchantId" : "5f9f729123010f0011cbea89"
    },
```

**What is the expected behavior?**

Expecting it to return the `_id` field as normal as an object.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node: v12.3.1
Mongoose: 5.10.14

**Comment by AbdelrahmanHafez** [comment]
Welcome @hazz1925

Can you please show me your whole pipeline, and your schemas?

**Comment by hazz1925** [comment]
Hi @AbdelrahmanHafez 

Thanks for you prompt reply.

After checking the schema I just realize that it was wrong. It was `_id: String` instead of an object.
Sorry for that. My bad.

Will close this issue then. Thanks
