### ISSUE TITLE
Transaction error when using Promise.all

### ISSUE THREAD

**Issue by g-popovic** [Automattic/mongoose#9554]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I have to preform 3 update operations & 1 insert operation. I use `Promise.all()` for this, as seen below. Sometimes, very randomly, it throws the following error:
 _(note that the numbers are different based on the request, i.e. the first request says `transaction number 1 does not match... active transaction number is -1`, second request says `transaction number 2 does not match... active transaction number is 1` and so on..._ 
```
MongoError: Given transaction number 2 does not match any in-progress transactions. The active transaction number is 1
    at MessageStream.messageHandler (C:\Users\WIN 10\desktop\ether\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:310:20)
    at processIncomingData (C:\Users\WIN 10\desktop\ether\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\Users\WIN 10\desktop\ether\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at doWrite (_stream_writable.js:442:12)
    at writeOrBuffer (_stream_writable.js:426:5)
    at MessageStream.Writable.write (_stream_writable.js:317:11)
    at TLSSocket.ondata (_stream_readable.js:695:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

This happens randomly, sometimes it doesn't even happen, but usually it happens for 1 or even 2 of the operations in the `Promise.all()` in the below code.

```
const session = await mongoose.startSession();
session.startTransaction();

		try {
                        // Perform 3 update operations & 1 insert operation
			const result = await Promise.all([
				User.findOneAndUpdate(
					{
						_id: recipientId,
						$expr: { $lt: [{ $size: '$matches' }, '$matchSlots'] }
					},
					{
						$push: { matches: { matchId: senderId } }
					},
					{ session }
				),
				User.findOneAndUpdate(
					{
						_id: senderId,
						$expr: { $lt: [{ $size: '$matches' }, '$matchSlots'] }
					},
					{
						$push: { matches: { matchId: recipientId } }
					},
					{ session }
				),
				Like.findOneAndUpdate(
					// Make Like inactive, as it was accepted
					{ to: senderId, from: recipientId },
					{ isActive: false },
					{ session }
				),
				Like.create(
					[
						{
							to: recipientId,
							from: senderId,
							isActive: false
						}
					],
					{ session }
				)
			]);

			await session.commitTransaction();
			session.endSession();
			res.sendStatus(200);
		} catch (err) {
			await session.abortTransaction();
			session.endSession();
			console.log(err);
			res.send(err);
		}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
The error is thrown whenever I use a `Promise.all()` with more then 1 operation in it, however it happens randomly. It never happens (at least I havent encountered it) when the is only one operation, but when there is more then 1 operation it seems to have about a 50% chance of happening for each of the operations.

**What is the expected behavior?**
The expected behavior is to not throw any error (unless it's a MongoDB duplicate value error, in which case `session.abortTransaction()` is called), and simply complete the 4 operations. I need to use transactions for this, as if one of the 4 promises returns `null`, I need to abort the transaction.

P.S.  I can't use `withTransaction()`, as while It does fix the error completely, I need to access the edited documents later on and do some validation.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v12.16.2
Mongoose: v5.10.13
MongoDB: 4.2.10

**Comment by sukritnak** [comment]
@g-popovic 
I've got the same problem.
Can you tell me how to handle this case?

**Comment by g-popovic** [comment]
I think there was some alternative like `mongoose.startTransaction()` or something along the lines that can be used instead of `withTransaction`

**Comment by sukritnak** [comment]
You mean it's not necessary to handle `commitTransaction` and `abortTransaction` and use `withTransaction` instead?

**Comment by g-popovic** [comment]
Ah yes, the other way around, I think you can just use `withTransaction` or something. This was quite a minute ago so I don't remember specifically

**Comment by whatwhywhenandwho** [comment]
I have a similar problem, and I'm using `withTransaction`. Keep in mind I'm only making queries in `Promise.all()`, no mutations, and it randomly fails with that error. If I change to simple sequential `await`s, it always works. This is a huge problem, because instead of taking 20ms, it takes 100ms.

**Comment by vkarpov15** [comment]
@whatwhywhenandwho please open a new issue and follow the issue template?
