### ISSUE TITLE
Mongoose doesn't save empty objects in sub schema with `minimize: false`

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [Automattic/mongoose#9555]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Mongoose doesn't save empty objects for sub documents. 

Example: 

We have two schemas and trying to save empty object `data: {}` described in sub schema with `minimize: false`. 
Current behaviour: It's not store empty object in sub doc.  It's working as expected only if we add `minimize: false` to parent schema. 
```
const subSchema = new mongoose.Schema({
data: {
    type: Object,
    default: {}
  }
}, {
  _id: false,
  strict: false,
  minimize: false
});

const schema = new mongoose.Schema({
  data: {
    type: subSchema
  }
  // other fields
}); // works if we add `minimize:false` here.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Expected behaviour: It should store empty objects in sub schema, because we described separate option only for this schema.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJs: 12.16.1
Mongoose: 5.9.25
MongoDb: 4.0.20

**Comment by vkarpov15** [comment]
The below script works as expected: Mongoose stores `data.data` as an empty object. Can you please modify the below script to demonstrate your issue?

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const subSchema = new mongoose.Schema({
    data: {
      type: Object,
      default: {}
    }
  }, {
    _id: false,
    strict: false,
    minimize: false
  });

    const schema = new mongoose.Schema({
    data: {
      type: subSchema
    }
    // other fields
  });

  const Model = mongoose.model('Test', schema);

  await Model.create({ data: {} });
  const doc = await Model.findOne().lean();
  console.log(doc);
}
```

Output:

```
$ node gh-9555.js 
Mongoose: tests.insertOne({ _id: ObjectId("5fb5cc3ca0b93ae74e7c3f8d"), data: { data: {} }, __v: 0}, { session: null })
Mongoose: tests.findOne({}, { projection: {} })
{ _id: 5fb5cc3ca0b93ae74e7c3f8d, data: { data: {} }, __v: 0 }
^C
$ 
```
