### ISSUE TITLE
updateMany does not log the query when debug mode is activated

### ISSUE THREAD

**Issue by fromi** [Automattic/mongoose#9558]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I don't see the MongoDB query being run when I run an updateMany query.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use `mongoose.set('debug', true)`. See that operations such as "find" gets logged in the console.
Call `const test await SomeModel.updateMany(...)`. See that nothing is log.
Try to log the test variable: `console.log(test) // result is: { ok: 0, n: 0, nModified: 0 }`

**What is the expected behavior?**
I should see the request that is being executed in the logs to understand why it modifies nothing.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v12.18.0
Mongoose v5.10.11
MongoDB v3.6.2

**Comment by AbdelrahmanHafez** [comment]
`mongoose.set('debug', true);` shows the operations that are sent to MongoDB.

Mongoose tries to short-circuit unnecessary operations such as empty updates and doesn't send them to MongoDB, which is what's happening in your case, judging by the `{ ok: 0, n: 0, nModified: 0 }`.

### 9558.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });

  const User = mongoose.model('User', userSchema);

  mongoose.set('debug', true);

  // mongoose does not send the operation to MongoDB because it's an empty updateMany
  // so nothing will show in the logs
  const res = await User.updateMany({ name: '' }, {});
  console.log(res);

  // mongoose will correctly show the updateMany operation being sent to MongoDB
  // Mongoose: users.updateMany({ name: '' }, { '$set': { name: 'Hafez' } }, {})
  await User.updateMany({ name: '' }, { name: 'Hafez' });
}
 ```

### Output
```
{ ok: 0, n: 0, nModified: 0 }
Mongoose: users.updateMany({ name: '' }, { '$set': { name: 'Hafez' } }, {})
```

**Comment by fromi** [comment]
Interesting! Then I need to understand why it short-circuits my operation...

Here is my code:
```
const count = await GameModel.count({'players.userId': visitorId}) // for debug purpose: returns 208.
await GameModel.updateMany({'players.userId': visitorId},
            {$set: {'players.[player].userId': session.user.id}},
            {arrayFilters: [{'player.userId': visitorId}]})
```
As you can see, the updateMany should not be short-circuited as 208 elements should be concerned by the query. I really don't understand what is wrong with the query, and the fact that it is not logged makes it harder to understand.
FYI, both visitorId and session.user.id are non-empty strings.

Thanks if you can help!

**Comment by AbdelrahmanHafez** [comment]
It's not the `filter` part that would make mongoose short-circuit, it's the `update` part that would.

I am not sure if `{'players.[player].userId': session.user.id}` is a valid MongoDB syntax, I don't think I've seen the bracket square syntax in a MongoDB query before. So mongoose removes this update altogether, resulting in an empty write operation. To verify whether or not that's true, try updating a field on the top level of the schema along with this update operation and see the output, if it doesn't have the `players.[player].userId` bit, it means that it's invalid and mongoose has removed it, and that's why you can't see it in the logs.

I assume you want to update a field in an array of objects, you could use the [positional operator](https://docs.mongodb.com/manual/reference/operator/update/positional/#update-documents-in-an-array) for that.

**Comment by fromi** [comment]
It's a completely valid MongoDB syntax which I already used in a migration script (without mongoose).
Have a look at [https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/](https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/)

I finally found my mistake though: the '$' was missing before the brackets: `{'players.$[player].userId': session.user.id}`

Thanks for your time, sometimes it's hard to catch little mistakes like that one!

**Comment by AbdelrahmanHafez** [comment]
Happy to help.

**Comment by vkarpov15** [comment]
Mongoose skips empty updates because the [MongoDB server throws an error on empty updates](https://jira.mongodb.org/browse/SERVER-12266?filter=-4), which was an unfortunate breaking change for us back in the day. If Mongoose didn't skip this update, you would just get an error back.
