### ISSUE TITLE
Virtual populate array and return documents even if no reference is found

### ISSUE THREAD

**Issue by munroe7** [Automattic/mongoose#9559]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Running virtual populate only returns documents where population reference is found

**Example**
I have the following array of emails. I run a populate against the email field in my user collection. This will return the details of the user but some email aren't associated with an account yet, but I would still like them in my final array.

["email1@gmail.com", "email2@gmail.com"]

If one of the user's doesn't exist, I would like it to return this:
[{_id: 109753097121092, name: 'steve', email: 'email1@gmail.com'}, "email2@gmail.com"]
Or even:
[{_id: 109753097121092, name: 'steve', email: 'email1@gmail.com'}, {email: "email2@gmail.com"}]

What i'm getting (notice the entry that failed to populate is missing:
[{_id: 109753097121092, name: 'steve', email: 'email1@gmail.com'}]

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.4.22
node: 8.11.3
mongodb: 3.6.12

**Comment by vkarpov15** [comment]
I don't have a good idea of what your code looks like from your description, can you please provide a code sample that shows what your schemas and your `populate()` call look like?
