### ISSUE TITLE
 Mongoose does not fetch nested subdocuments on arrays

### ISSUE THREAD

**Issue by supermar1010** [Automattic/mongoose#9565]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Have a look here, these issue seem to be related: https://github.com/Automattic/mongoose/issues/9408

I have a similiar problem with retrieving nested properties, so I guess this is not completely fixed.

My document according to mongo express looks like this:

```js
{
    _id: ObjectId('5fb55a6653549930c3430edd'),
    title: 'Test1',
    someArray: [
        {
            someName: 'Mario',
            availableTimes: [
                {
                    someNumber: '1605729569',
                    someOtherNumber: '1605729569'
                },
                {
                    someNumber: '1605729569',
                    someOtherNumber: '1605729569'
                }
            ]
        },
        {
            someName: 'Max',
            availableTimes: [
                {
                    someNumber: '1605749569',
                    someOtherNumber: '1605749569'
                },
                {
                    someNumber: '1605749569',
                    someOtherNumber: '1605749569'
                }
            ]
        }
    ],
    createdAt: ISODate('2020-11-18T17:31:18.825Z'),
    updatedAt: ISODate('2020-11-18T17:31:18.825Z'),
    __v: 0
}
```

when retrieving by mongoose, it is missing the availableTimes:

```json
{
    "_id": "5fb55a6653549930c3430edd",
    "title": "TestSurvey1",
    "someArray": [
        {
            "someName": "Mario"
        },
        {
            "someName": "Max"
        }
    ],
    "createdAt": "2020-11-18T17:31:18.825Z",
    "updatedAt": "2020-11-18T17:31:18.825Z",
    "__v": 0
}
```

This is the code I'm using to retrieve it:
```ts
route.get('/:surveyId', async (req, res) => {
    const survey: ISurvey | null = await Survey.findOne({ longId: req.params?.surveyId }).exec();
    console.log(survey);
    if (survey) {
      res.status(200).send(survey);
    } else {
      res.status(404).send('404 not found');
    }
  });
```

When using lean instead of exec it works flawless, but I cannot use lean, to update docs as far as I know.

Also what is very weird is, that if I change `availableTimes` to something different, it sometimes works, then it stops working again...

**If the current behavior is a bug, please provide the steps to reproduce.**

Not sure, as the behavior changes sometimes :/

**What is the expected behavior?**

It should always return the full document

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose version: "^5.10.15"

mongodb version: 3.6.21 from docker hub

nodejs:15.2.1

**Comment by supermar1010** [comment]
I just found cause for this, notice how the objects in the someArray don't have _id, if you add these/input these objects by code it starts working. I still think this is a bug but a different one

**Comment by vkarpov15** [comment]
Can you please post your schema definition? The issue you referenced, #9408, occurs when you define a default that doesn't fit the schema structure.

Also, try running `await survey.validate()` to see if there are any validation errors. There are cases when Mongoose marks paths as errored when loading from the database because the data in the database is incompatible with the schema, like schema says the path is an array but the document in the db has that path set to a number.
