### ISSUE TITLE
Error passed to callback also thrown outside callback

### ISSUE THREAD

**Issue by TommasoBrandirali** [Automattic/mongoose#9567]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Running asynchronous queries with an erroneous query causes the error to be passed to the callback (as expected) but also to be thrown outside the callback (undesired). Am I missing something here? Is this expected behavior? It seems quite undesired. I also couldn't find any related open issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test', {useNewUrlParser: true});

const kittySchema = new mongoose.Schema({
    name: "String"
});
const Kitten = mongoose.model('Kitten', kittySchema);

let run = async function () {
    try {
        await Kitten.find(
            {
                // Purposefully wrong query to trigger error
                "$matc": {
                    "name": "aKitty"
                }
            }
            , function (err, docs) {
                if (err) {
                    // Expected log
                    console.log("Error caught in callback")
                } else {
                    console.log("No error in callback")
                }
            })
    } catch (err) {
        // Unexpected log
        console.log("Error caught in catch block")
    }
}

run();
```

**What is the expected behavior?**

The error should only be passed to the callback and not thrown outside the callback.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node v13.11.0
Mongoose v5.10.15
MongoDB v4.2.3 Community, same behavior observed with Amazon DocumentDB v4.0.0

**Comment by AbdelrahmanHafez** [comment]
Welcome @TommasoBrandirali

This is expected behavior because [mixing callbacks with async/await executes the query twice](https://mongoosejs.com/docs/queries.html#queries-are-not-promises), and you get the error twice.

The solution is to use one of them, and I would recommend using async/await whenever possible, you don't need callbacks here.
```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test', { useNewUrlParser: true });

const kittySchema = new mongoose.Schema({
  name: 'String'
});
const Kitten = mongoose.model('Kitten', kittySchema);

async function run () {
  try {
    const docs = await Kitten.find({
      // Purposefully wrong query to trigger error
      $matc: { name: 'aKitty' }
    });
  } catch (err) {
    // catch error here
    console.log('Error caught in catch block');
  }
}

run();
```

This is very similar to https://github.com/Automattic/mongoose/issues/9560#issuecomment-729562341
