### ISSUE TITLE
Instance Methods Not Available On Document

### ISSUE THREAD

**Issue by HenryDinh86** [Automattic/mongoose#9570]
Hi There,

Im new and just got into learning nodejs and mongodb. When i instantiate my model, for some strange reason i dont get the instance methods such as .save(). I have used it in the past and never had a problem until im trying to build my current project.

Any help would be much appreciated. I tried to google search for hours and could not figure this one out. 

### mongoose connection file:

![image](https://user-images.githubusercontent.com/20413738/99784756-6245b880-2b70-11eb-93f9-845da2da8b40.png)

### Schema

![image](https://user-images.githubusercontent.com/20413738/99787926-7db2c280-2b74-11eb-8f56-ff7880c9f33a.png)

### Route

![image](https://user-images.githubusercontent.com/20413738/99788096-b8b4f600-2b74-11eb-9753-c25121c9418f.png)

Node v14.15.1, Mongoose v5.10.15

**Comment by AbdelrahmanHafez** [comment]
Welcome @HenryDinh86 

Can you add the lines below and share the output?
```js
console.log(Program);
console.log(newProgram);
```

Also, please avoid sharing screenshots of code, it's easier to share the code itself as text so it's easier for other people trying to help to copy & paste it, it'll be more likely that you'll get the help you need.

**Comment by HenryDinh86** [comment]
> Welcome @HenryDinh86
> 
> Can you add the lines below and share the output?
> 
> ```js
> console.log(Program);
> console.log(newProgram);
> ```
> 
> Also, please avoid sharing screenshots of code, it's easier to share the code itself as text so it's easier for other people trying to help to copy & paste it, it'll be more likely that you'll get the help you need.

Hi Hafez,

Firstly, here are the output from console log:
console.log(Program); ---> Model { Program }
console.log(newProgram); ---> newProgram : {
  exercises: [],
  records: [],
  _id: 5fb7c1d63334f802e4fbf386,
  name: 'Test Name',
  weeks: 8,
  days: 4,
  subTitle: 'testing titles',
  sets: 3,
  reps: '10',
  notes: 'testing note',
  user: 5fb7c01381e72b02c2437767
}

Also sorry about the screenshots. Code as test is below

// mongoose
const mongoose = require('mongoose');

mongoose.connect(
  process.env.MONGODB_URI || 'mongodb://localhost:27017/FitnessApp;',
  {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false
  }
);
module.exports = mongoose;

//Schema
const mongoose = require('mongoose');
const ProgramSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      minlength: 1,
      trim: true,
      required: true
    },
    weeks: Number,
    days: Number,
    // eg Day 1 - Upper Body (POWER)
    subTitle: {
      type: String,
      minlength: 1,
      trim: true
    },
    sets: {
      type: Number,
      required: true
    },
    reps: {
      type: String,
      trim: true
    },
    notes: {
      type: String
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    exercises: [
      {
        default: [],
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Exercise'
      }
    ],
    records: [
      {
        default: [],
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Record'
      }
    ]
  },
  {
    timestamps: true
  }
);
const Program = mongoose.model('Program', ProgramSchema);
module.exports = Program;

//routes
const express = require('express');
const router = express.Router();
const Program = require('../server/models/program');

router.post('/', async (req, res) => {
  try {
    const {
      name,
      weeks,
      days,
      subTitle,
      sets,
      reps,
      notes,
      user = req.user.id
    } = req.body;

    const newProgram = new Program({
      name,
      weeks,
      days,
      subTitle,
      sets,
      reps,
      notes,
      user
    });
    newProgram. <----- here when i hit .(dot) i dont get the save()

**Comment by AbdelrahmanHafez** [comment]
Ok, so seems like Program is a mongoose model, but `newProgram` is not a document instance.
in `routes.js` can you add the following and share the output?

```js
const mongoose = require('mongoose');

const newProgram = new Program({ name, weeks, ... });
console.log('is a document:',newProgram instanceof mongoose.Document);
console.log('newProgram:', newProgram);
console.log('save:', newProgram.save);
```

Do you happen to be using any mongoose plugins?

**Comment by HenryDinh86** [comment]
Hi @AbdelrahmanHafez 

Mongoose plugins you mean using lean() and virtuals? Correct me if im wrong. Im still new to this. If so, i have used them to muck around before and i've removed the code a while ago. 

### Here is the output from the console logs
is a document: true
newProgram: {
  exercises: [],
  records: [],
  _id: 5fba26578eb1d7032f8b1e9e,
  name: 'Another Test',
  weeks: 8,
  days: 4,
  subTitle: 'Test Title 2',
  sets: 3,
  reps: '10',
  notes: 'Another Test Note',
  user: 5fb7c01381e72b02c2437767
}
save: [Function (anonymous)]

**Comment by AbdelrahmanHafez** [comment]
According to the logs `save` is a function, what do you exactly mean when you say that you don't get the methods?

Is there an error that gets thrown? If so, please share it along with the stack trace. 

Also, you can read more about mongoose plugins [here](https://mongoosejs.com/docs/plugins.html).

**Comment by HenryDinh86** [comment]
Im sorry, what i meant is when i hit (dot) im not seeing intellisense in vscode for the various methods the document has. I use to see them.

Thats why i thought its not working. Some tutorial vids i've seen has intellisense for all its methods

**Comment by AbdelrahmanHafez** [comment]
Oh, so it's about intellisense.

Can you create an example repository/script that demonstrates the issue? I tried the minimal script below and it's giving me hints for intellisense.

Try installing `@mongoose/types` and see if it helps `npm i --save-dev @types/mongoose`.

```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;

const userSchema = new Schema({
  name: { type: String }
});

const User = mongoose.model('User', userSchema);

const user = new User();
console.log(user.save);
```

![Screenshot_723](https://user-images.githubusercontent.com/19984935/99903626-232d7980-2cce-11eb-84e8-1ef50e8ee075.jpg)

**Comment by HenryDinh86** [comment]
I've tried to create another project with this example and its showing this when i hit .save As you can see, i dont know why no intellisense for this model.

![image](https://user-images.githubusercontent.com/20413738/99904184-6ebb4400-2d1d-11eb-9609-dab4507ec86a.png)

git repo: git@github.com:HenryDinh86/Test.git

**Comment by AbdelrahmanHafez** [comment]
I tried with the test repo you provided and things seem to be working for me.

Does intellisense work for anything else, or is it just mongoose? It might be an issue with VSCode, try running vscode in safe mode using the following command in your terminal
```
code . --disable-extensions
```

It will open a VSCode window with all extensions disabled, try `npm i moment` and see if you can get intellisense support for moment or not, we'll also try a simple function in the same file, it's possible that some extension/setting is disallowing the intellisense hints.

```js
const moment = require('moment');

moment().add // should show hints here

/**
 * 
 * @param {Number} x 
 * @param {Number} y 
 * @returns {Number} sum
 */
function add(x,y){
  return x + y;
}

console.log(add); // should show hints
```

![Screenshot_724](https://user-images.githubusercontent.com/19984935/99905842-2af41a80-2cdc-11eb-968f-0e94228206d5.jpg)
![Screenshot_725](https://user-images.githubusercontent.com/19984935/99905844-2b8cb100-2cdc-11eb-9014-e96884a155a7.jpg)

**Comment by HenryDinh86** [comment]
It seems like its only for mongoose documents. Whenever i instantiate a new mongoose model it happens.

If i call the model itself and hit dot i get the create ()
![image](https://user-images.githubusercontent.com/20413738/100066848-a7782c00-2e89-11eb-9176-133984f68f2b.png)

I'll try to run it in save mode and give you an update

**Comment by HenryDinh86** [comment]
> ```js
> const moment = require('moment');
> 
> moment().add // should show hints here
> 
> /**
>  * 
>  * @param {Number} x 
>  * @param {Number} y 
>  * @returns {Number} sum
>  */
> function add(x,y){
>   return x + y;
> }
> 
> console.log(add); // should show hints
> ```

I ran vscode in safe mode and installed moment, everything is okay. 

Im also using moment in my project so i created a playground file and mucked around, its giving me intellisense.

I think there's something to do with mongoose...

Here are my Vscode settings:
{
  "workbench.colorTheme": "Material Theme Palenight High Contrast",
  "workbench.iconTheme": "material-icon-theme",
  "liveServer.settings.donotShowInfoMsg": true,
  "workbench.settings.editor": "json",
  "workbench.settings.useSplitJSON": true,
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "debug.node.autoAttach": "off",
  "prettier.arrowParens": "always",
  "workbench.activityBar.visible": true,
  "workbench.startupEditor": "newUntitledFile",
  "workbench.statusBar.visible": true,
  "window.zoomLevel": 0,
  "javascript.updateImportsOnFileMove.enabled": "never",
  "editor.fontSize": 16
}

**Comment by AbdelrahmanHafez** [comment]
Frankly, I am not sure what the issue is here, my last resort would be to manually install `@types/mongoose` in the repository, if that doesn't help, I suppose we could wait and see if someone else could know what the issue is.

**Comment by vkarpov15** [comment]
Realistically, I think the best we can do is to recommend [restarting VS code](https://vscode.readthedocs.io/en/latest/editor/intellisense/#troubleshooting) and reinstalling mongoose and `@types/mongoose` for Mongoose versions before v5.11. Debugging VS Code issues is a deep rabbit hole and we don't have the necessary expertise.
