### ISSUE TITLE
customize some hook functions on the basis of mongoose

### ISSUE THREAD

**Issue by LeonYanghaha** [Automattic/mongoose#9579]
I want to customize some hook functions on the basis of mongoose. For example, on the find function, I can write my own code in this [line of code](https://github.com/Automattic/mongoose/blob/5.10.15/lib/model.js#L2022), right?
Why do I need to customize some hook functions? Because I want to restrict different applications to have different operation permissions in this way. For example, app-1 can be used ```User.find ()```, but not ```User.update ()```。 In order to achieve this function, please let me know if you have any other way. Thank you very much for your help.

I have other questions: My code is asynchronous, but the code in mongoose is in the form of callback. Can I only write callback? Is there any other way for me to use async / await?

**Comment by vkarpov15** [comment]
You can use async/await with Mongoose, you don't need to use callbacks.

And if you want to hook into certain function calls, you should use [middleware](https://mongoosejs.com/docs/middleware.html). For example, you can forbid an app from calling `User.update()` by defining `pre('update')` middleware:

```javascript
userSchema.pre(/^update/, function() {
  throw new Error('App not allowed to use `update()`');
});
```
