### ISSUE TITLE
Getting cast to objectID failed when trying to use ULID for generating objectIds

### ISSUE THREAD

**Issue by akshay-nm** [Automattic/mongoose#9586]
I am trying to get ULID working with mongoose. 

My DocTypeA schema looks like this: 
```js
const mongoose = require('mongoose')
const Schema = mongoose.Schema
const ULID = require('ulid')

const schema = new Schema({
  _id: { type: Schema.Types.String, default: () => ULID.ulid(Date.now()) },
  name: { type: Schema.Types.String },
})

schema.set('toJSON', {
  virtuals: true,
  versionKey: false,
  transform: function (doc, ret) {
    // remove these props when object is serialized
    delete ret._id
  },
})

module.exports = mongoose.model('DocTypeA', schema)
```

My DocTypeB schema looks like this:
```js
const mongoose = require('mongoose')
const Schema = mongoose.Schema
const ULID = require('ulid')

const schema = new Schema({
  _id: { type: Schema.Types.String, default: () => ULID.ulid(Date.now()) },
  name: { type: Schema.Types.String },
  docA: { type: Schema.Types.ObjectId, ref: 'DocTypeA' },
})

schema.set('toJSON', {
  virtuals: true,
  versionKey: false,
  transform: function (doc, ret) {
    // remove these props when object is serialized
    delete ret._id
  },
})

module.exports = mongoose.model('DocTypeB', schema)
```

I am able to create documents for `DocTypeA` and ULID generated stuff is saved as _id in `DocTypeA` documents. 
But when I try to reference a `DocTypeA` document id while creating an `DocTypeB` document, I get the cast error (mentioned in the title). 

Here is the code for creating a `DocTypeA`:
```js
const create = async (payload) => {
  const docA = new DocTypeA(payload)
  await docA.save()
  return docA
}
```
For creating an `DocTypeB`, I am using: 
```js
const create = async (payload) => {
  const docB = new DocTypeB(payload)
  await docB.save()
  return docB
}
```

The collections exist in the database

I also created a SO post: https://stackoverflow.com/questions/65012612/cast-to-objectid-failed-for-value-ulid-id-at-path-doca

**Comment by vkarpov15** [comment]
Looks like you got your answer on SO. The problem is this line: `docA: { type: Schema.Types.ObjectId, ref: 'DocTypeA' },`, `docA` should be of type `Schema.Types.String` to line up with the `_id` type for `DocTypeA`.
