### ISSUE TITLE
Mongoose Isn’t creating database

### ISSUE THREAD

**Issue by itsJavaCoder** [Automattic/mongoose#9589]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I do `mongoose.connect(‘mongodb+srv://username:<my password>@bot.scv9.mongodb.net/test’)` it connects but doesn’t create or store anything in the database
**If the current behavior is a bug, please provide the steps to reproduce.**

```
const mongoose = require('mongoose')
const mongoPath  = 'mongodb+srv://username:<password>@bot.scv9j.mongodb.net/test'

module.exports = async () => {
  mongoose.connect(mongoPath, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  return mongoose
}
```
```
const mongoose = require('mongoose');

let Schema = mongoose.Schema({
    id: mongoose.Schema.Types.ObjectId,
    guildid: String,
    guildname: String,
    logchannelid: String
})

module.exports = mongoose.model('Guild', Schema)
```
```
db.findOne({ guildid: message.guild.id, user: user.user.id}, async(err, data) => {
            if(err) throw err;
            if(!data) {
                data = new db({
                    guildid: message.guild.id,
                    user : user.user.id,
                    content : [
                        {
                            moderator : message.author.id,
                            reason : reason
                        }
                    ]
                })
            } else {
                const obj = {
                    moderator: message.author.id,
                    reason : reason
                }
                data.content.push(obj)
            }
            data.save()
        });
```
This is the code I use to store the data in the database
**What is the expected behavior?**
I want it to create the database and then store the data inside it
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.19.0
Mongoose: 5.10.15
MongoDB: 4.4

**Comment by yashwanthrk** [comment]
There is an issue with mongoose version 5:10:16, please change it back to 5:10:15. We had faced the same issue

**Comment by itsJavaCoder** [comment]
> There is an issue with mongoose version 5:10:16, please change it back to 5:10:15. We had faced the same issue.
> Refer to this thread [#9585 (comment)](https://github.com/Automattic/mongoose/issues/9585#issue-751097126)

I’ve downgraded to 5.10.15 and it still doesn’t work.

**Comment by yashwanthrk** [comment]
Please don't use any  tilde(~) and caret(^),  just do "mongoose": "5.10.15" in package.json.

**Comment by itsJavaCoder** [comment]
> Please don't use any tilde(~) and caret(^), just do "mongoose": "5.10.15" in package.json.

Ah ok. It does it automatically

**Comment by itsJavaCoder** [comment]
> Please don't use any tilde(~) and caret(^), just do "mongoose": "5.10.15" in package.json.

It still does not work

**Comment by vkarpov15** [comment]
You're using a variable `db` as a Mongoose model, but I don't see any `db` schema in your original post. Can you please provide a more complete code sample?

Also, you should probably do `await data.save()` instead of just `data.save()`
