### ISSUE TITLE
add error name again to error objects

### ISSUE THREAD

**Issue by SajjadHadi** [Automattic/mongoose#9590]
Hi, I a little confused, different errors have different keys in objects, in previous versions, every error objects had a name field that made the error type clear, e.g. CastError, ValidationError, they are all gone.
please add the name field again, because checking the Error types with regex in error messages or error reasons does not make any sense.
thank you so much....

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @SajjadHadi

I just tested with v5.10.17, and errors have their correct names. Can you please modify the script below to demonstrate the issue you're facing?
### 9590.js
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');


const userSchema = new Schema({
  age: Number
});

const User = mongoose.model('User', userSchema);

const user = new User({ age: 'invalid' });
const err = user.validateSync();

assert.equal(err.name, 'ValidationError');
assert.equal(err.errors.age.name, 'CastError');


console.log(mongoose.version);
console.log('All assertions passed.');
```

### Output
```
$ node 9590.js
5.10.17
All assertions passed.
```
