### ISSUE TITLE
Expiration date can't update to previous second with new second

### ISSUE THREAD

**Issue by 4cc3ssflick** [Automattic/mongoose#9594]
Here is my previous development testing code

`created_at: {
        type: Date,
        default: Date.now,
        expires: '5s'
    }`

I wanna test for expires feature with 5s. When I change 5s to 3 months like this
 
`created_at: {
        type: Date,
        default: Date.now,
        expires: '7884000s'
    }`
But unfortunately it delete after 5s so i remove single quote and test it again but same issue

`created_at: {
        type: Date,
        default: Date.now,
        expires: 7884000
    }`

Any solution to reset expire date?

**Comment by vkarpov15** [comment]
Use [`syncIndexes()`](https://thecodebarbarian.com/whats-new-in-mongoose-5-2-syncindexes) :+1:
