### ISSUE TITLE
mongoose find doesn't return any doc, while compass does

### ISSUE THREAD

**Issue by gerald-dotcom** [Automattic/mongoose#9596]
We see the data already in MongoDB compass but when it comes to Mongoose it fails to return results but if we try again like say after 5 min then we can see the data on Mongoose (Sometimes this even not works).

I am thinking this has to do with the large amount of documents. We have two collections and each has around 10 million records. We query both of them at same time.

Here is the code that I am using to query just a one collection,

```
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

mongoose.connect('mongodb://WHATEVERIP:27017/DBNAME?authSource=DBNAME', {

    user: "admin",

    pass: "passs",

    useNewUrlParser: true,

    useUnifiedTopology: true

});

var MarketingSchema = new Schema({}, { strict: false });

var MarketingModel = mongoose.model('Marketing', MarketingSchema, 'Marketing');

// r_time is 64 bit timestamp field

var DataRecord = await MarketingModel.find({ ip: "PUT IP OF CLIENT HERE" }).sort({ r_time: -1 }).lean().limit(1).exec();

if (!DataRecord.length) {

    console.log("NOT FOUND");

}
```
Sample data,

```
{
    "_id": {
        "$oid": "5f14cc1e283ea9705f1b31c2"
    },
    "userID": 1433571522,
    "ip": "135.114.236.220",
    "isNew": false,
    "r_time": {
        "$numberLong": "1595198494512"
    },
    "event": "Click",
    "x": 93.39,
    "y": -492.00
}


{
    "_id": {
        "$oid": "5f14cc22283ea9705f1b31c3"
    },
    "userID": 1433571522,
    "ip": "135.114.236.220",
    "isNew": false,
    "r_time": {
        "$numberLong": "1595198498608"
    },
    "event": "Press",
    "x": 91.39,
    "y": -20.00
}



{
    "_id": {
        "$oid": "5f14cc22283ea9705f1b31c4"
    },
    "userID": 1433571522,
    "ip": "135.114.236.220",
    "isNew": false,
    "r_time": {
        "$numberLong": "1595198498652"
    },
    "event": "Type",
    "x": 11.24,
    "y": -29.00
}
```
Just to tell you how hard we are affected with this, We've spent $100k on third party consulting fees and waited almost 1 year without solution until a friend called me up to check on mongoose github.

I'm happy to provide anything you may need even if you need money we can pay it

**Comment by vkarpov15** [comment]
@gerald-dotcom what output do you get? Do you get the "NOT FOUND" message?

Also, are you absolutely sure that 'DBNAME' is the correct database and 'Marketing' is the correct collection?

**Comment by vkarpov15** [comment]
Also, what versions of Mongoose and MongoDB?

**Comment by gerald-dotcom** [comment]
Yes, I get NOT FOUND message but sometimes query return results. It's an unpredictable situation, would say unstable. 

I've put a retry logic to retry like 5 times, it works to some extent but in some cases it doesn't. 

I'm 1000000% correct DBName is the correct database and Marketing is the correct collection. 

MongoDB 4.4 and Mongoose 5.9.25

**Comment by vkarpov15** [comment]
What are the cases where it doesn't work? Slightly different "PUT IP OF CLIENT HERE" or same "PUT IP OF CLIENT HERE" but intermittently returns no results?

**Comment by gerald-dotcom** [comment]
"PUT IP OF CLIENT HERE" this is dummy just to prove what to put there.

The behavior is honestly random for the IP.  Sometimes it works, Sometime it doesn't. 

I mean I am trying to get most recent records..

**Comment by gerald-dotcom** [comment]
The exact same query return results in compass and in node it doesn't but sometimes it does. Please understand me!

**Comment by vkarpov15** [comment]
I unfortunately don't understand you. If you query the same IP multiple times, does it always get you the same result, or does it sometimes give you `null` and sometimes the doc?

**Comment by gerald-dotcom** [comment]
If you query the same IP multiple times, does it always get you the same result, or does it sometimes give you null and sometimes the doc?

Yes.

**Comment by gerald-dotcom** [comment]
Does it sometimes give you null and sometimes the doc?

This one I meant to say

**Comment by vkarpov15** [comment]
Is the data changing? Are there documents whose `ip` changes, or are you deleting documents?

**Comment by gerald-dotcom** [comment]
No data is changing neither I delete documents.

But there is new documents coming in for IPs as usual.

**Comment by vkarpov15** [comment]
How is this code being called? Is this in an Express app or are you just running the script you pasted repeatedly?

**Comment by gerald-dotcom** [comment]
An express app.

**Comment by vkarpov15** [comment]
Can you provide some code samples for how the Express app looks?

**Comment by gerald-dotcom** [comment]
```
const express = require('express');
const mongoose = require('mongoose');
const ipaddr = require('ipaddr.js');
const router = express.Router();

const Schema = mongoose.Schema;

mongoose.connect('mongodb://WHATEVERIP:27017/DBNAME?authSource=DBNAME', {

    user: "admin",

    pass: "passs",

    useNewUrlParser: true,

    useUnifiedTopology: true

});

var MarketingSchema = new Schema({}, { strict: false });

var MarketingModel = mongoose.model('Marketing', MarketingSchema, 'Marketing');

function parseIP(IPAddr) {
    if (ipaddr.isValid(IPAddr)) {
        try {
            var addr = ipaddr.parse(IPAddr);
            if (ipaddr.IPv6.isValid(IPAddr) && addr.isIPv4MappedAddress()) {
                return addr.toIPv4Address().toString();
            }
            return addr.toNormalizedString();
        } catch (e) {
            return false;
        }
    }
    return false;
}

router.post('/', async function (req, res) {
        let ipAddr = parseIP(req.ip);

       var DataRecord = await MarketingModel.find({ ip: ipAddr  }).sort({ r_time: -1 }).lean().limit(1).exec();

       if (!DataRecord.length) {

          console.log("NOT FOUND");

       }
})

module.exports = router;

```

**Comment by vkarpov15** [comment]
Is it possible that, for some reason, `ipaddr` is failing to parse the string and returning `false`?

**Comment by gerald-dotcom** [comment]
In production, we have a check for that like below but I forget to include it on the minimal example ;( 


```
        let ipAddr = parseIP(req.ip);

        if (!ipAddr) {
            throw "Invalid Client";
        }

```

**Comment by vkarpov15** [comment]
Do you have a `readPreference` set?

**Comment by gerald-dotcom** [comment]
> Do you have a `readPreference` set?

What's that? Never heard about it

We are using MongoDB standalone as it's without any modification

**Comment by gerald-dotcom** [comment]
It looks like readPreference applies only to replica type DBs

**Comment by vkarpov15** [comment]
Ok so we can rule out replication lag. Try upgrading to Mongoose 5.10, [MongoDB 4.4 requires v3.6 of the MongoDB Node.js driver](https://docs.mongodb.com/drivers/node/compatibility), and Mongoose 5.10.0 is the earliest version that uses MongoDB Node.js driver 3.6.

**Comment by gerald-dotcom** [comment]
I will try
