### ISSUE TITLE
ObjectId is not a valid ObjectId when used in Mixed

### ISSUE THREAD

**Issue by yoctozepto** [Automattic/mongoose#9602]
**Do you want to request a *feature* or report a *bug*?**

A *bug*.

**What is the current behavior?**

Very similar to (already fixed) https://github.com/Automattic/mongoose/issues/7973
however, I am using `mongoose.Schema.Types.Mixed` and including the ObjectId as a value in the hash.

**If the current behavior is a bug, please provide the steps to reproduce.**

    const exSchema = new mongoose.Schema({
      dummy: { type: mongoose.Schema.Types.Mixed },
    })

    const Ex = mongoose.model('Ex', exSchema)

    const bad = new Ex()
    bad.dummy = { badId: bad._id } // because why not :-)
    await bad.save()

And an example error on save is:

    Error: object [{"_bsontype":"ObjectID","id":{"0":95,"1":197,"2":3,"3":55,"4":17,"5":232,"6":189,"7":110,"8":188,"9":120,"10":76,"11":216}}] is not a valid ObjectId

**What is the expected behavior?**

I expect it works like it did on 4.x

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 8.15.0
Mongoose 5.10.18

**Comment by yoctozepto** [comment]
In my case the workaround was to just stringify (.toString) the ObjectId before saving - all usages I had were compatible with it being a string.

**Comment by vkarpov15** [comment]
I'm unable to repro this, the below script shows that `bad.dummy.badId` is an ObjectId in Mongoose v5.10.18:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const exSchema = new mongoose.Schema({
    dummy: { type: mongoose.Schema.Types.Mixed },
  })

  const Ex = mongoose.model('Ex', exSchema)

  const bad = new Ex()
  bad.dummy = { badId: bad._id } // because why not :-)
  await bad.save()

  const fromDb = await Ex.collection.findOne();
  console.log(fromDb.dummy.badId instanceof mongoose.Types.ObjectId); // Prints "true"
}
```

Can you please modify the above script to demonstrate your issue?

**Comment by yoctozepto** [comment]
Yes, you are right. It seems the custom validator I have is breaking the internal structure. I seemingly forgot to turn it off but obviously not included it in the repro. Sorry!

Any idea why it did not trigger any issue with Mongoose 4?

This issue can be closed otherwise.

**Comment by vkarpov15** [comment]
Hard to tell without seeing the custom validator. Can you share that please?

**Comment by yoctozepto** [comment]
Yeah, the culprit boils down to this part:

    function trimDeep(t) {
      if (_.isString(t)) {
        return t.trim();
      } else if (_.isArray(t)) {
        return _.map(t, trimDeep);
      } else if (_.isObject(t)) {
        return _.mapValues(t, trimDeep);
      } else {
        return t;
      }
    }

Essentially it seems be rewriting the ObjectId object and it fails.

**Comment by vkarpov15** [comment]
Yeah that's because `_.isObject()` returns `true` on ObjectIds, so you're ending up with a [POJO](https://masteringjs.io/tutorials/fundamentals/pojo) that contains ObjectId properties because of `_.mapValues()`. You need to be more careful about cloning non-POJOs. Here's our recommended alternative for checking if an object is a POJO:

```javascript
function isPOJO(arg) {
  if (arg == null || typeof arg !== 'object') {
    return false;
  }
  const proto = Object.getPrototypeOf(arg);
  if (proto == null) {
    return true; // `Object.create(null)`
  }
  return proto === Object.prototype;
}
```

**Comment by yoctozepto** [comment]
Thanks, that's it. I have no other non-POJOs in that legacy schema. I wonder - was ObjectId a POJO in v4 and hence why it worked previously?

**Comment by vkarpov15** [comment]
No it was not. I suspect in v4 there was some logic somewhere that converted POJOs with a `_bsontype` property set to 'ObjectId' back into ObjectIds.
