### ISSUE TITLE
How to get the collection name of popular

### ISSUE THREAD

**Issue by LeonYanghaha** [Automattic/mongoose#9607]
```
const schema = new mongoose.Schema({
    name: 'string', 
    size: {type: 'string', ref: "Employee"}
});
const Tank = mongoose.model('Tank', schema);

// How to get ref information in size field

```
The above code is very simple. I created a model and a schema. But now, I want to get the details of ref through schema or model, such as "employee" in my code. How can I get it? Thank you for your help

**Comment by vkarpov15** [comment]
`Tank.schema.path('size').options.ref` should work

**Comment by LeonYanghaha** [comment]
Thank you for all your help @vkarpov15
