### ISSUE TITLE
Typescript Types.ObjectId definition is incorrect 

### ISSUE THREAD

**Issue by shirhen** [Automattic/mongoose#9608]
version 5.11.0 mongoose

**Reporting a bug**

cannot use `Types.ObjectId().toHexString()` get an error 
`Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new'?`

**What is the expected behavior?**
In the old version 5.10.19 before the new typescript support in 5.11 It worked, so I expect it to keep working if the change was only in typescript support and not the implementation itself. 

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
node v12.13.1 
mongoose 5.11.0

the fault lies in mongoose/index.d.ts
```javascript
class ObjectId extends mongodb.ObjectID {
      _id?: ObjectId;
    }
```
the @types/mongoose/index.d.ts has the correct definition.
```javascript
 /*
      * section types/objectid.js
      * http://mongoosejs.com/docs/api.html#types-objectid-js
      */
    var ObjectId: ObjectIdConstructor;

    // mongodb.ObjectID does not allow mongoose.Types.ObjectId(id). This is
    //   commonly used in mongoose and is found in an example in the docs:
    //   http://mongoosejs.com/docs/api.html#aggregate_Aggregate
    // constructor exposes static methods of mongodb.ObjectID and ObjectId(id)
    type ObjectIdConstructor = typeof mongodb.ObjectID & {
      (s?: string | number): mongodb.ObjectID;
    };

    // var objectId: mongoose.Types.ObjectId should reference mongodb.ObjectID not
    //   the ObjectIdConstructor, so we add the interface below
    interface ObjectId extends mongodb.ObjectID { } 
```

note the  ObjectIdConstructor for ObjectId. 

The question is, is the change on purpose is so then maybe there should be migration documents from @types/mongoose to the mongoose typescript, or is it a bug? 

thanks

**Comment by vkarpov15** [comment]
This is an unintended bug that we missed. You shouldn't need to change your code for valid uses of Mongoose for the new TypeScript bindings, we just missed this case. Thanks for reporting, fix will be in 5.11.1 within the next 24 hours, sorry for the inconvenience!
