### ISSUE TITLE
Support for forked typescript bindings

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9614]
Re: @simllll 's comments here: https://github.com/Automattic/mongoose/issues/9606#issuecomment-736717943 . It is not uncommon for devs to use their own forked versions of @types/mongoose for improved bindings, but trying to use these changes in combination with Mongoose's new types is tricky because when you have both @types/mongoose and Mongoose v5.11 you get a lot of errors about duplicate definitions.

**Comment by vkarpov15** [comment]
@simllll I'll recommend you do the same thing I suggested in https://github.com/Automattic/mongoose/issues/9635#issuecomment-738125901: add the below script to your `package.json`.

```
"scripts": {
  "postinstall": "rm ./node_modules/mongoose/index.d.ts"
}
```

It isn't elegant, but will let you use your alternate typings without any interference from Mongoose's built-in types.

**Comment by simllll** [comment]
Thanks @vkarpov15 for the suggestion, unfortunately this is not possible in our setup (or at least not in any easy way), as we have serveral monorepos (which contain other monorepos sometimes) , the folder strucutre is not always like I just have one node_modules, i would like to go up and down the tree and look for mongoose/index.d.ts and remove that..before doing that, I'll try to prepare a PR that allows defining custom object ids and bring in some other improvements we have in our defintions :) but will take some more time before I can look on that. I guess in the meantime it's the only option to stick to 5.10.x for now...

**Comment by vkarpov15** [comment]
Thanks @simllll and sorry for the inconvenience. Let me know if I can help in any way.

Would you be able to add this postinstall script to each of the monorepos? That seems like it would solve this problem, assuming that your monorepos all have a top-level `node_modules`...
