### ISSUE TITLE
"new" option in `findByIdAndUpdate` function doesn't compile

### ISSUE THREAD

**Issue by jameskentTX** [Automattic/mongoose#9615]
Mongoose 5.11.1
Typescript 4.0.5
Debian 10
MongoDB server version: 4.3.0-1509-ge3e1773

mongoose.connect options: 

`{ useCreateIndex: true, useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false }`

I have fragment of code:
```typescript
await this.model.findByIdAndUpdate(req.body.userId,
      {ejabberdRegistered: true}, {new: true, select: '_id ejabberdRegistered'}, (err, response) => {...});
```

This code is working well in Mongoose ~5.10 but doesn't compile in Mongoose 5.11 and above.

In VsCode Typescript shows info:

Argument of type '{ new: boolean; select: string; }' is not assignable to parameter of type 'QueryOptions'.
  Object literal may only specify known properties, and 'new' does not exist in type 'QueryOptions'

I checked documentation, "new" option in 'QueryOptions' of `findByIdAndUpdate` function exists in Mongoose 5.11

**Comment by vkarpov15** [comment]
Thanks for reporting, we will fix this ASAP and release a fix within the next 24 hours.
