### ISSUE TITLE
More typescript problems -  mongoose.set

### ISSUE THREAD

**Issue by bda2206** [Automattic/mongoose#9616]
Reporting a bug

**What is the current behavior?**

not compiling

code causing problems

```
     mongoose.set('useCreateIndex', true);

```

result

```
- error TS2339: Property 'set' does not exist on type 'typeof import("mongoose")'.

                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

using mongoose 11.1

workaround is seemingly to import mongoose from  mongoose/lib  to avoid the index.d.ts

thanks guys!

**Comment by vkarpov15** [comment]
How are you importing Mongoose?

**Comment by bda2206** [comment]
```import mongoose from 'mongoose';```

the lib workaround involves a bit of messing around. my colleague got it going, I don't know exact details.

**Comment by vkarpov15** [comment]
And what does your tsconfig look like?

**Comment by bda2206** [comment]
also we are having issues with 

```
console.log(`${model.collection.collectionName}`);

```

- error TS2339: Property 'collection' does not exist on type 'Model<Document>'.

and possibly with collectionName not existing in collection. can you check that while your going? thanks

**Comment by bda2206** [comment]
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    "target": "es2020",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "lib": ["es6","es2019"],                           /* Specify library files to be included in the compilation. */

    "outDir": "build",                        /* Redirect output structure to the directory. */
    "rootDir": "srv",                         /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */

     "downlevelIteration": true,              /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    "noImplicitAny": true,                   /* Raise error on expressions and declarations with an implied 'any' type. */
     "strictNullChecks": true,              /* Enable strict null checks. */
     "strictFunctionTypes": true,           /* Enable strict checking of function types. */
     "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
     "strictPropertyInitialization": false,  /* Enable strict checking of property initialization in classes. */
     "noImplicitThis": false,                /* Raise error on 'this' expressions with an implied 'any' type. */
     "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */

    /* Advanced Options */
    "resolveJsonModule": true,                /* Include modules imported with '.json' extension */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true,  /* Disallow inconsistently-cased references to the same file. */
    "pretty": true
  }
}

**Comment by bda2206** [comment]
really appreciate the fast action on this, btw. thanks.
