### ISSUE TITLE
Typescript types issue: No longer supports arrays of strings

### ISSUE THREAD

**Issue by Green-Cat** [Automattic/mongoose#9617]
With the new types shipping with 5.11, arrays of strings in schemas error out.

A very simple example:

```
import { Document, model, Schema } from "mongoose";

export interface IExample extends Document {
    names: string[];
}

export const ExampleSchema: Schema = new Schema({
    names: [String],
});

export const Example = model<IExample>('Example', ExampleSchema);
```

Error:
`
Type 'StringConstructor' has no properties in common with type 'SchemaTypeOptions<any>'.
`

**Comment by vkarpov15** [comment]
Thanks for reporting, we'll fix this and release a fix within the next 24 hours. Sorry for the inconvenience!

**Comment by Green-Cat** [comment]
No problem. Thank you for the effort!
