### ISSUE TITLE
Typings: missing _id from Document class

### ISSUE THREAD

**Issue by ktutnik** [Automattic/mongoose#9618]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**
Missing `_id` from document inherited from [`Document`](https://github.com/Automattic/mongoose/blob/645a45bc6b87b1581149db49532a9366e434db9b/index.d.ts#L282)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.1

**Comment by ktutnik** [comment]
There are more errors https://github.com/plumier/plumier/pull/679/checks?check_run_id=1483131980

**Comment by MajidJafari** [comment]
I also have the same issue. 
Mongoose: 5.11.1, Node.js: 12.18.4

**Comment by NaturesProphet** [comment]
same here

**Comment by vkarpov15** [comment]
@ktutnik I believe the above commit should fix your compiler issues. Please upgrade to v5.11.2 when we release it within the next couple hours, and open a new issue if there are other issues :+1:

**Comment by ktutnik** [comment]
Thanks for the quick update

**Comment by vkarpov15** [comment]
v5.11.2 is out, let me know if you have any more issues, and sorry for the issues :+1:

**Comment by ktutnik** [comment]
Hi @vkarpov15 v5.11.2 still can't fix the issue. I don't see the appropriate code [here](https://github.com/Automattic/mongoose/commit/ef2a4c799ecafe35a55273a10387cd387681e823). Or am I missing something?

**Comment by NaturesProphet** [comment]
same here. updated to 5.11.2 and still have problems with _id

**Comment by ktutnik** [comment]
@vkarpov15 any reason not start from `@types/mongoose` typings?

I think it's good to start from there to make smooth delivery

**Comment by vkarpov15** [comment]
@ktutnik we thought about it, but there were several improvements we wanted to make based on our own experience and feedback from other users.

We added `_id` in https://github.com/Automattic/mongoose/commit/b733c7b20022307b29e1c613646a37b05d4addac, will be in v5.11.3.
