### ISSUE TITLE
typing error on mongoose connection url

### ISSUE THREAD

**Issue by NaturesProphet** [Automattic/mongoose#9623]
Do you want to request a feature or report a bug?
Bug Report

What is the current behavior?
error TS2769: No overload matches this call.

What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.
Mongoose 5.11.1 and nodejs 10.23

this is the code:

import * as mongoose from 'mongoose';
import { injectionList } from '../../common/constants/injection.constants';
import { mongoHost, mongoPassword, mongoPort, mongoSchema, mongoUser } from '../../common/configs/databases.config';

export const mongoProviders = [
  {
    provide: injectionList.MONGO_CONN,
    useFactory: (): Promise<typeof mongoose> =>
      mongoose.connect( `mongodb://${mongoUser}:${mongoPassword}@${mongoHost}:${mongoPort}/${mongoSchema}`, {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        useFindAndModify: false,
        useCreateIndex: true
      } ),
  },
];

and this is the error

error TS2769: No overload matches this call.
  Overload 1 of 3, '(uri: string, callback: (err: NativeError) => void): void', gave the following error.
    Argument of type '{ useNewUrlParser: boolean; useUnifiedTopology: boolean; useFindAndModify: boolean; useCreateIndex: boolean; }' is not assignable to parameter of type '(err: NativeError) => void'.
      Object literal may only specify known properties, and 'useNewUrlParser' does not exist in type '(err: NativeError) => void'.
  Overload 2 of 3, '(uri: string, options?: ConnectOptions): Promise<typeof import("mongoose")>', gave the following error.
    Argument of type '{ useNewUrlParser: true; useUnifiedTopology: true; useFindAndModify: false; useCreateIndex: boolean; }' is not assignable to parameter of type 'ConnectOptions'.
      Object literal may only specify known properties, and 'useCreateIndex' does not exist in type 'ConnectOptions'.

 28   const mongodb = await mongoose.connect( `mongodb://${mongoUser}:${mongoPassword}@${mongoHost}:${mongoPort}/${mongoSchema}`, {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 29     useNewUrlParser: true,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 32     useCreateIndex: true
    ~~~~~~~~~~~~~~~~~~~~~~~~
 33   } );




it always worked using @types/mongoose, but now everything is crashing.

**Comment by vkarpov15** [comment]
Fixed by #9621 , sorry for the inconvenience! We will push this fix in v5.11.2 later today
