### ISSUE TITLE
Method all param require a number instead a string Array

### ISSUE THREAD

**Issue by PadRocha** [Automattic/mongoose#9624]
![image](https://user-images.githubusercontent.com/23110724/100891275-b90b9600-347e-11eb-9ed0-353b368ae563.png)

in the @types/mongoose

```
/**
 * Specifies an $all query condition.
 * When called with one argument, the most recent path passed to where() is used.
 */
all(val: number): this;
all(path: string, val: number): this;
```
I understand that this parameter should ask for an array of objects, in fact the text editor asks for it.

Once corrected it allows me to do the function and the request is executed correctly

```
/**
 * Specifies an $all query condition.
 * When called with one argument, the most recent path passed to where() is used.
 */
all(val: string[]): this;
all(path: string, val: string[]): this;
```

![image](https://user-images.githubusercontent.com/23110724/100891890-5e266e80-347f-11eb-9ffc-a5d236090004.png)

**Comment by vkarpov15** [comment]
This isn't the repo for @types/mongoose. Mongoose has an official `index.d.ts` file now that handles `all()` correctly: https://github.com/Automattic/mongoose/blob/ef2a4c799ecafe35a55273a10387cd387681e823/index.d.ts#L1571-L1572
