### ISSUE TITLE
[TS] Model.findById is missing in index.d.ts

### ISSUE THREAD

**Issue by juergenzimmermann** [Automattic/mongoose#9626]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`MyModel.findById(myId, {}, { lean: true })` cannot be compiled by the TypeScript compiler.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
`interface Model<...>` in the file `index.d.ts` should contain the signature of `findById`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 15.3.0
Mongoose 5.11.1
MongoDB 4.4.2

**Comment by huineng** [comment]
indeed, i just replaced all of them by findOne :)

**Comment by almeidx** [comment]
This has been listed in https://github.com/Automattic/mongoose/issues/9620 already

**Comment by vkarpov15** [comment]
This is fixed by https://github.com/Automattic/mongoose/commit/4b223e4055f5c33dcb361ac793097d9cb1da6234

**Comment by vkarpov15** [comment]
v5.11.2 is now released, please upgrade and this issue should go away. Sorry for the trouble :+1:
