### ISSUE TITLE
[TS] Cannot specify "new: true" for Model.findByIdAndUpdate

### ISSUE THREAD

**Issue by juergenzimmermann** [Automattic/mongoose#9627]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

The TypeScript-Compiler reports an error when I specify `new: true` for the options in `Model.findByIdAndUpdate(...)`.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
No compilation errors. Maybe, an interface e.g. `UpdateOptions` is required, and not only `QueryOptions`.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 15.3.0
Mongoose 5.11.1
MongoDB 4.4.2

**Comment by vkarpov15** [comment]
Fixed by #9615, fix will be out later today
