### ISSUE TITLE
type errors

### ISSUE THREAD

**Issue by NaturesProphet** [Automattic/mongoose#9631]
Bug Report

Mongoose 5.11.2 and nodejs 10.23

i have a schema that include this code:

.
.
.
    location: {
      type: { type: String },
      coordinates: [ Number ]
    },
.
.
.

when i try to build this, i receive this error:

error TS2322: Type '{ type: { type: StringConstructor; }; coordinates: NumberConstructor[]; }' is not assignable to type 'string | Function | Function[] | Schema | SchemaTypeOptions<any> | Schema[] | SchemaTypeOptions<any>[]'.
  Object literal may only specify known properties, and 'coordinates' does not exist in type 'Function | Function[] | Schema | SchemaTypeOptions<any> | Schema[] | SchemaTypeOptions<any>[]'.

16       coordinates: [ Number ]

it always worked using @types/mongoose, but since the last updates it is crashing on build.

**Comment by bda2206** [comment]
5.11.3 is out. 
give it a run?

**Comment by NaturesProphet** [comment]
> 5.11.3 is out.
> give it a run?

i'll check this out now

**Comment by vkarpov15** [comment]
We haven't released 5.11.3 yet, 5.11.2 is the latest version

**Comment by bda2206** [comment]
oops my bad.
