### ISSUE TITLE
enhancement: pass document to default functions

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9633]
Currently when a path has `default` set to a function, we can access the document via `this`, would be nice if the document gets passed as an argument to the function, similar to what we've done to `required` validator in https://github.com/Automattic/mongoose/issues/9433
```js
let documentIsThis;
let documentFromDefault;
const userSchema = new Schema({
  name: { type: String },
  age: {
    type: Number,
    default (doc) {
      // should evaluate to true so people can use arrow functions
      documentIsThis = doc === this;
     documentFromDefault = doc;
    }
  }

});

const User = mongoose.model('User', userSchema);

new User({ name: 'Hafez' });

assert.equal(documentIsThis, true);
assert.equal(documentFromDefault.name, 'Hafez');
```

**Comment by vkarpov15** [comment]
Yeah this would be great! Are you going to be working on this?

**Comment by AbdelrahmanHafez** [comment]
Yes, I'll be working on it.

**Comment by tarasau** [comment]
Hi,
Use mongoose version 6.0.12 migrated from 5.8.13. Could you please explain how to genarate ObjectId and create ObjectId from string provided as param?
On previous version I use mongoose.Types.ObjectId('blah'), but for version 6.0.12 mongoose.Types.ObjectId() mark as 'Method expression is not of Function type'. What should I use instead?

**Comment by AbdelrahmanHafez** [comment]
@tarasau
Can you provide a reproduction script? The following code snippet seems to work correctly.

## 9633-object-id.js
```js
import mongoose from 'mongoose';

console.log(new mongoose.Types.ObjectId());
console.log(mongoose.version);
```
## Output
```
new ObjectId("61833edd635f847d571d971e")
6.0.12
```
