### ISSUE TITLE
possible bug: SchemaTypes.ObjectId.cast does not run when value is `null`

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9634]
So, I came across a case where I want to set all object ids to be `undefined` if the value passed to document is `null`.
The reason being that I want to avoid having `null` keys in my documents, and prefer not having them altogether.

However, trying to do that via custom casting logic did not work because the `cast` function is not invoked when the value is `null`.

```js
'use strict';
disallowNullInObjectId();

// does not work
function disallowNullInObjectId () {
  const originalObjectIdCast = mongoose.SchemaTypes.ObjectId.cast();

  mongoose.SchemaTypes.ObjectId.cast(function (value) {
    if (value === null) {
      return undefined;
    }
    return originalObjectIdCast(value);
  });
}



const userSchema = new Schema({
  name: { type: String },
  cityId: Schema.ObjectId
});

const User = mongoose.model('User', userSchema);

const user = new User({ name: 'Hafez', cityId: null });

// fails, user.cityId is `null` instead of `undefined`
assert.strictEqual(user.cityId, undefined);
```

I was able to work around this by setting a default `set` value to all object ids.
```js
// works
function disallowNullInObjectId () {
  mongoose.SchemaTypes.ObjectId.set('set', (value) => {
    if (value === null) {
      return undefined;
    }

    return value;
  });
}
```

**Comment by vkarpov15** [comment]
We explicitly avoid casting nullish values with this line: https://github.com/Automattic/mongoose/blob/b9dd74b3a9f9b9237d40a16fe6f4b28da9ee60fb/lib/schematype.js#L1105-L1107 . Whether we continue doing this is something worth discussing. I think the general idea is that cast functions shouldn't always have to write `if (v == null) { return v }`, but I can see arguments on both sides. What do you think @AbdelrahmanHafez ?

The current workaround is to use a setter as you described.

**Comment by AbdelrahmanHafez** [comment]
Won't fix, reason here: https://github.com/Automattic/mongoose/pull/9636#issuecomment-738560965

**Comment by hadarsnorlax** [comment]
The `mongoose.SchemaTypes.ObjectId.set` is not working ):

**Comment by hadarsnorlax** [comment]
> We explicitly avoid casting nullish values with this line:
> 
> https://github.com/Automattic/mongoose/blob/b9dd74b3a9f9b9237d40a16fe6f4b28da9ee60fb/lib/schematype.js#L1105-L1107
> 
> . Whether we continue doing this is something worth discussing. I think the general idea is that cast functions shouldn't always have to write `if (v == null) { return v }`, but I can see arguments on both sides. What do you think @AbdelrahmanHafez ?
> The current workaround is to use a setter as you described.

This solution is weak, it gives me no option to disallow null in the schema validation... And I don't want to change it to `required: true` because it will no longer be optional.

**Comment by vkarpov15** [comment]
@hadarsnorlax what do you mean by "I don't want to change it to required: true because it will no longer be optional"?

**Comment by hadarsnorlax** [comment]
That you will have the option to not insert the field at all, and also it will be forbidden to insert it as a null

**Comment by hadarsnorlax** [comment]
@vkarpov15 That you will have the option to not insert the field at all, and also it will be forbidden to insert it as a null

**Comment by vkarpov15** [comment]
So you just want to disallow `null`, but ok to not set the field at all?

**Comment by hadarsnorlax** [comment]
@vkarpov15 Yeah, that's accurate

**Comment by hadarsnorlax** [comment]
> Just add a custom validator, `validate: v => v !== null` should work
Yeah that's working, but is there any way to make this validate global for the entire code or at least for one schema?

**Comment by vkarpov15** [comment]
Yeah, global schematype validation: https://mongoosejs.com/docs/validation.html#global-schematype-validation  `mongoose.Schema.ObjectId.set('validate', v => v !== null)`
