### ISSUE TITLE
types

### ISSUE THREAD

**Issue by NaturesProphet** [Automattic/mongoose#9635]
is there any way to use mongoose without his own type definitions? i want to keep using @types/mongoose.

**Comment by vkarpov15** [comment]
We'll see if we can figure out a workaround.

**Comment by vkarpov15** [comment]
I've done a lot of digging but I haven't been able to find a TypeScript-based workaround that works. Looks like this issue has been the topic of some debate:

https://github.com/microsoft/TypeScript/issues/17042
https://github.com/microsoft/TypeScript/issues/18588
https://github.com/microsoft/TypeScript/issues/37053

TLDR; there doesn't seem to be a good workaround for `tsconfig.json`, but you can get the desired outcome by adding a [postinstall script to `package.json`](https://docs.npmjs.com/cli/v6/using-npm/scripts) that removes the `index.d.ts` file:

```
"scripts": {
  "postinstall": "rm ./node_modules/mongoose/index.d.ts"
}
```

It's far from elegant, but will get the job done.
