### ISSUE TITLE
Bug: Mongoose ver. 5.11.X breaks population

### ISSUE THREAD

**Issue by ironm8** [Automattic/mongoose#9640]
**Do you want to request a *feature* or report a *bug*?**

a bug
**What is the current behavior?**
reproduction: basic model population: 
`        query = mongoose.model('stories').find(conditionsInfo);`
`    let populate = 'desk'`
`                query.populate(populate);`

`{“error”:“Error: Can only use numbers in square bracket path notation, got character \“o\” in path \“desk[object\“\n  at stringToParts (/usr/src/app/node_modules/mpath/lib/stringToParts.js:10:13)\n  at Object.exports.get (/usr/src/app/node_modules/mpath/lib/index.js:51:7)\n  at getModelsMapForPopulate (/usr/src/app/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:242:32)\n  at populate (/usr/src/app/node_modules/mongoose/lib/model.js:4323:21)\n  at _populate (/usr/src/app/node_modules/mongoose/lib/model.js:4293:5)\n  at db.base._promiseOrCallback.cb (/usr/src/app/node_modules/mongoose/lib/model.js:4269:5)\n  at promiseOrCallback (/usr/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)\n  at Mongoose._promiseOrCallback (/usr/src/app/node_modules/mongoose/lib/index.js:1135:10)\n  at Function.Model.populate (/usr/src/app/node_modules/mongoose/lib/model.js:4267:23)\n  at model.Query.Query._completeOne (/usr/src/app/node_modules/mongoose/lib/query.js:2078:9)\n  at Immediate.Query.base.findOne.call (/usr/src/app/node_modules/mongoose/lib/query.js:2117:10)\n  at Immediate._onImmediate (/usr/src/app/node_modules/mquery/lib/utils.js:116:16)\n  at runCallback (timers.js:810:20)\n  at tryOnImmediate (timers.js:768:5)\n  at processImmediate [as _immediateCallback] (timers.js:745:5)“}`

looking at the mongoose.model object we observe this: 
```
 _mongooseOptions: {
    populate: {
      'desk[object': [PopulateOptions],
      'Object],[object': [PopulateOptions],
      'Object]': [PopulateOptions]
    }
```

**Comment by vkarpov15** [comment]
Can you show your schemas please? That will help us repro and fix this.

**Comment by ironm8** [comment]
```
 let schema = {
            headline: {type: String, require: true},
            type: {type: String, require: true},
            createdAt: {type: Date, require: true, default: Date.now},
            lastUpdate: {type: Date, require: true, default: Date.now},
            _owner: {
                userId: {type: ObjectId, required: true, ref: 'users0.1'},
                deskId: {type: ObjectId, require: true, ref: 'desks'},
                organizationId: {type: ObjectId, require: true},
            },
            _parent: {
                storyId: {type: ObjectId, require: true},
                videoId: {type: ObjectId, require: true},
                groupId: {type: ObjectId, require: true},
            },
            _opt: {
                deleted: {type: Boolean},
                status: {type: String, require: true},
            },
            _admin: {
                isDefault: {type: Boolean},
                emailNotify: {type: String},
            },
        };
```

As you can see 'desk' is not actually part of the schema. However it didn't error before

**Comment by vkarpov15** [comment]
I haven't been able to repro this issue, but I put in a patch to mpath in https://github.com/aheckmann/mpath/commit/ffed5197e598df2b6a3312d09fe09b7a66c4de82 that should fix this issue. Now mpath will treat `desk[object Object]` as a property name rather than treating `[object Object]` as an attempt to index into an array. That should fix this issue :+1:
