### ISSUE TITLE
Typeerror when saving/creating doc via transaction

### ISSUE THREAD

**Issue by Tobjoern** [Automattic/mongoose#9642]
**Do you want to request a *feature* or report a *bug*?**
I think I found a missing property of the SaveOptions type in index.d.ts

**What is the current behavior?**
SaveOptions does not have the sessions property, for saving a doc, when using a transaction.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to create/save a document, with the 'session' property, typescript throws an error.

**What is the expected behavior?**
It should be possible to create/save documents using transactions, as this the described behaviour in the [documentation](https://mongoosejs.com/docs/transactions.html). 

> To execute an operation in a transaction, you need to pass the session as an option

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: ^5.11.2

**How to fix?**
add: "session?: mongodb.ClientSession" as a property to SaveOptions, so the type errors disappear.

**Comment by vkarpov15** [comment]
Thanks for reporting, will fix for v5.11.4 :+1:

**Comment by Tobjoern** [comment]
Great!
