### ISSUE TITLE
TypeScript: Missing type definition for native driver off Connection

### ISSUE THREAD

**Issue by higherorderfunctor** [Automattic/mongoose#9643]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`[tsserver/Error/2339] Property 'db' does not exist on type 'Connection'.`

**If the current behavior is a bug, please provide the steps to reproduce.**

`mongoose.connection.db`

**What is the expected behavior?**

[Connection.prototype.db](https://mongoosejs.com/docs/api.html#connection_Connection-db) is missing in the [index.d.ts](https://github.com/Automattic/mongoose/blob/master/index.d.ts).  [DefinitelyTyped reference where this field existed for reference.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L437)

Temporary work around using a Type Guard.

```typescript
const hasDriver = (
  db: mongoose.Connection
): db is mongoose.Connection & { db: mongodb.Db } => 'db' in db;
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

nodejs@v14.11.0
mongoose@5.11.3
mongodb@3.6.3
@types/mongodb@3.6.0

**Comment by vkarpov15** [comment]
Thanks for reporting, fix will be in v5.11.4, we will ship that release within the next 24 hours :+1:
