### ISSUE TITLE
BUG: typescript - Cannot assign `L & Document` as a generic parameter to `Model` 

### ISSUE THREAD

**Issue by picnixz** [Automattic/mongoose#9649]
**Do you want to request a *feature* or report a *bug*?** A bug

**Related issues**

- #9620 
- #9644 

**What is the current behavior?**

The following code-snippet does not compile. 

**Steps to reproduce.**

```ts
'use strict'

import type { Document, Model } from 'mongoose' 

export declare type SqlRecord<L, T extends Document = Document> = L & T
export declare type SqlModel<L, T extends Document = Document> = Model<SqlRecord<L, T>>
```

Compilation error: 

```
error TS2344: Type 'SqlRecord<L, T>' does not satisfy the constraint 'Document'.
  The types of 'delete(...).$where(...).and' are incompatible between these types.
    Type '(array: FilterQuery<T>[]) => Query<T[], T>' is not assignable to type '(array: FilterQuery<Document>[]) => Query<Document[], Document>'.
      Types of parameters 'array' and 'array' are incompatible.
        Type 'FilterQuery<Document>[]' is not assignable to type 'FilterQuery<T>[]'.
          Type 'FilterQuery<Document>' is not assignable to type 'FilterQuery<T>'.
            Type 'FilterQuery<Document>' is not assignable to type '{ [P in keyof T]?: (P extends "_id" ? [Extract<T[P], ObjectId>] extends [never] ? Condition<T[P]> : Condition<string | { _id: ObjectId; } | T[P]> : [...] extends [...] ? Condition<...> : Condition<...>) | undefined; }'.
```

**What is the expected behavior?**

I would expect the code to compile. Indeed, `SqlRecord<L, T>` is a Document, so I would expect Liskov Substitution Principle to hold. The type `L` is actually an arbitrary user-specific layout and I would like to be 

```ts
'use strict'

import { model, Schema } from 'mongoose' 

function random<L>(model: SqlModel<L>, force?: Optional<L>): SqlRecord<L> {
  /* generate a random POJO matching L with some fixed fields coming from `force` */
  const data: L = ...
  /* create the actual document */
  return model.create(data)
}

interface User {
  name: string
  mail: string
}

const UserSchema = new mongoose.Schema({ name: string, mail: string })
const UserModel = mongoose.model<SqlModel<User>>('User', schema)

const user = random<User>(UserModel, { name: 'Alice' })
// "user" is a document with `name = 'Alice'` and `mail` would be a random string
// "user" should also hold attributes derived from the base `Document` class
``` 
The issue arises from the definition of `FilterQuery`. Let us compare [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/64aaf4fe47802030f3d26f2ed8955d6609d85256/types/mongoose/index.d.ts#L170-L182](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/64aaf4fe47802030f3d26f2ed8955d6609d85256/types/mongoose/index.d.ts#L170-L182) with [https://github.com/Automattic/mongoose/blob/68d90c0a7ec1f1d2fd309a8e734f8a4f348d425d/index.d.ts#L2034-L2043](https://github.com/Automattic/mongoose/blob/68d90c0a7ec1f1d2fd309a8e734f8a4f348d425d/index.d.ts#L2034-L2043) By using `FilterQuery` type from `@types/mongoose` actually _does_ work, so I think this bug can be fixed simply by renaming `FilterQuery` with `_FilterQuery` and redefining `FilterQuery<T> = _FilterQuery<DocumentDefinition<T>>`. It appears that `UpdateQuery<T>` does indeed use `DocumentDefinition` on its generic parameter and not its generic parameter directly [https://github.com/Automattic/mongoose/blob/68d90c0a7ec1f1d2fd309a8e734f8a4f348d425d/index.d.ts#L2045](https://github.com/Automattic/mongoose/blob/68d90c0a7ec1f1d2fd309a8e734f8a4f348d425d/index.d.ts#L2045)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: 10.21.0
Mongoose: 5.11.3
MongoDB: 4.4.2

**Comment by vkarpov15** [comment]
You're right, we should use `FilterQuery` with `DocumentDefinition`. Thanks for pointing this out, the fix will be out with v5.11.4 later today.
