### ISSUE TITLE
Changes are lost when doing multiple changes to a mongoose array and using filter

### ISSUE THREAD

**Issue by n-e** [Automattic/mongoose#9651]
**Do you want to request a *feature* or report a *bug*?** 

Either a bug or a behavior that I don't understand

**What is the current behavior?**

When doing the following steps:

```js
  const m1 = new Model({ arr: [{ abc: 'old' }] });
  await m1.save();

  const m2 = await Model.findOne({ _id: m1._id });
  m2.arr = [];
  m2.arr = m2.arr.filter(a => true);
  m2.arr.push({ abc: 'ghi' });
  await m2.save();
``` 

I expect the array in the second saved document to contain only one element, `{abc: 'ghi}` and not `{abc: 'old'}`.

However it contains both elements, and mongoose runs the following mongo query : 

```js
cats.updateOne({ _id: ObjectId("5fca1ccf7c0bf91eb18f1ce8") }, { '$push': { arr: { '$each': [ { _id: ObjectId("5fca1ccf7c0bf91eb18f1cea"), abc: 'ghi' } ] } }, '$inc': { __v: 1 }}, { session: undefined })
```

The m2 object, however, contains only the expected element in the array.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose=require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const Model = mongoose.model('Cat', { arr: [mongoose.Schema({ abc: String }, { _id: true })] });

const run = async () => {
  const m1 = new Model({ arr: [{ abc: 'old' }] });
  await m1.save();
  console.log(m1.toObject());

  const m2 = await Model.findOne({ _id: m1._id });
  m2.arr = [];
  m2.arr = m2.arr.filter(a => true);
  m2.arr.push({ abc: 'ghi' });
  await m2.save();
  console.log(m2.toObject());
};

mongoose.set('debug', true);
run();
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

mongoose 5.11.3, nodejs 14.4.0

**Comment by vkarpov15** [comment]
Taking a closer look, this is expected behavior. `m2.arr = m2.arr.filter(...)` means you're overwriting `arr`: when you do `m2.arr = ...`, Mongoose converts that to a `$set: { arr : ... }`.

You need to modify the array in place using [`pull()`](https://mongoosejs.com/docs/api/array.html#mongoosearray_MongooseArray-pull) in order to remove array elements without overwriting the underlying array.

**Comment by n-e** [comment]
Hi,

I'm not sure I understand your answer : I overwrite the array with `[]`, then I overwrite the array with `m2.arr = m2.arr.filter(...) `, then I push to it. I would expect mongoose to convert to `$set: { arr : ... }` as you say (more specifically `$set: {arr: [{abc:'ghi'}]}`), but it is converted as :

```
cats.updateOne({ _id: ObjectId("5fca1ccf7c0bf91eb18f1ce8") }, { '$push': { arr: { '$each': [ { _id: ObjectId("5fca1ccf7c0bf91eb18f1cea"), abc: 'ghi' } ] } }, '$inc': { __v: 1 }}, { session: undefined })
```
