### ISSUE TITLE
TypeScript: Upserting requires null check

### ISSUE THREAD

**Issue by higherorderfunctor** [Automattic/mongoose#9654]
**Do you want to request a *feature* or report a *bug*?**

Feature request.

**What is the current behavior?**

Update queries that support upserting are marked as possibly returning null values.  See https://github.com/Automattic/mongoose/blob/master/index.d.ts#L784 for the `findOneAndUpdate` type definition as an example.

```
  Argument of type '(doc: ITest) => void' is not assignable to parameter of type '(value: ITest | null) => void | PromiseLike<void>'.                                
    Types of parameters 'doc' and 'value' are incompatible.                                
      Type 'ITest | null' is not assignable to type 'ITest'.                                
        Type 'null' is not assignable to type 'ITest'.      
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```typescript
import mongoose from 'mongoose';                                
                                
interface ITest extends mongoose.Document {                                
  foo: string;                                
  baz: string;                                
}                                
                                
const TestSchema = new mongoose.Schema({                                
  foo: { type: String, required: true },                                
});                                
                                
const Test = mongoose.connection.model<ITest>('Test', TestSchema);                                
                                
Test.findOneAndUpdate(                                
  { foo: 'bar' },                                
  { baz: 'qux' },                                
  {                                
    new: true,                                
    upsert: true,                                
  }                                
)                                
  .then(
    (doc: ITest) => // <<< ERROR HERE
      console.log(doc)
  )                                
  .catch((err) => console.log(err));
```

**What is the expected behavior?**

I should not have to check for the null case when upserting.  This is a "regression" switching from @types/mongoose to mongoose@5.11 typing definitions.  The [DefinitelyTyped implementation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/index.d.ts#L2173) uses function overloading to remove the null case.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

nodejs@v14.11.0
mongoose@5.11.4
mongodb@3.6.3
@types/mongodb@3.6.0

**Comment by macksal** [comment]
I was surprised to see support for this (I noticed when using `findOneAndUpdate` queries).

However, it looks like the upsert type overloads are still missing for `findOne` queries, and maybe a few others (`findById`).

**Comment by vkarpov15** [comment]
@macksal that's a good point re: `new: false`. We will fix that for a future release.

`findOne()` and `findById()` don't support the upsert option, so that isn't a concern.
