### ISSUE TITLE
"this" in 'pre' save hook doesn't allow access to document in mongoose@5.11.4

### ISSUE THREAD

**Issue by jameskentTX** [Automattic/mongoose#9656]
Mongoose 5.11.4
Typescript 4.0.5
Debian 10
MongoDB server version: 4.3.0-1509-ge3e1773

mongoose.connect options:

{ useCreateIndex: true, useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false }

Last version of Mongoose working without errors is ~5.10, from 5.11 and above there are errors.

In Mongoose 5.11.4 I have many many errors, but lets start with 'pre' hook.

**ERROR: "this" in 'pre' save hook doesn't allow access to document:**

```typescript
const userSchema = new Schema({
  username: { type: String, unique: false, trim: true },
  email: { type: String, unique: true, lowercase: true, trim: true }});

userSchema.pre('save', function(next) {
  this.username = 'john';
});
```

Typescript in vscode shows error: 
`Property 'username' does not exist on type 'Document'.`

**Comment by sahasayan** [comment]
try this

```
interface IUser extends Document {
    username: string;
    email: string;
}

const userSchema = new Schema({
    username: { type: String, unique: false, trim: true },
    email: { type: String, unique: true, lowercase: true, trim: true },
});

userSchema.pre<IUser>('save', function (next) {
    this.username = 'john';
});
```

**Comment by ktutnik** [comment]
@jameskentTX alternatively you can specify the `this` data type of inline function like below

```typescript
function(this: User) {
    this. //<-- this is of type User
}
```

So in your case: 

```typescript
userSchema.pre('save', function(this:IUser, next) {
  this.username = 'john';
});
```

**Comment by jameskentTX** [comment]
@sahasayan 
@ktutnik 

Thank you both, IUser interface eliminated errors. Both solutions are working fine.

**Comment by vkarpov15** [comment]
I took a closer look and it looks like DefinitelyTyped doesn't support this either, you need to pass generics to `Schema#pre()`. So I'm not quite sure how this worked without error in v5.10 unless you weren't using any type bindings.
