### ISSUE TITLE
Typings: Return value of Model.insertMany look weird

### ISSUE THREAD

**Issue by ktutnik** [Automattic/mongoose#9662]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Previously when using `@types/mongoose` the result of `Model.insertMany` is array of the document itself, but now the result is `Array<T> | InsertManyResult`. 

This return value in VSCode will not showing any intellisense for list of its member, since no similarities between `Array` and `InsertManyResult`. 

**If the current behavior is a bug, please provide the steps to reproduce.**
```typescript
const inserted = await UserModel.insertMany([ ]);
inserted.   //<--- no available member visible for intellisense
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.4

**Comment by vkarpov15** [comment]
Fixed in https://github.com/Automattic/mongoose/commit/d4c17cef1ddfd952c2e6aa8809a95ede5e37dc13
