### ISSUE TITLE
Store createdAt and updateAt as Unix timestamps? [Repost]

### ISSUE THREAD

**Issue by SwapnilSoni1999** [Automattic/mongoose#9672]
Reposting #3957 due to closed conversation 
and I dont know why conversation is locked even when release is in pending

**Comment by AbdelrahmanHafez** [comment]
This is already released in v5.9.0, we forgot to remove the `pending release` label.
You can overwrite the function that gets the current time.
https://mongoosejs.com/docs/guide.html#timestamps
>By default, Mongoose uses new Date() to get the current time. If you want to overwrite the function Mongoose uses to get the current time, you can set the timestamps.currentTime option. Mongoose will call the timestamps.currentTime function whenever it needs to get the current time.

```js
const schema = Schema({
  createdAt: Number,
  updatedAt: Number,
  name: String
}, {
  // Make Mongoose use Unix time (seconds since Jan 1, 1970)
  timestamps: { currentTime: () => Math.floor(Date.now() / 1000) }
});
```

**Comment by tushar1998** [comment]
Hi I am on version 6.10

When I try to do
```typescript
@Schema({
  versionKey: false,
  timestamps: {
    updatedAt: 'updated_at',
    createdAt: 'created_at',
    currentTime: () => Math.floor(Date.now() / 1000),
  },
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
})
```

Still document get saved as 

```json
{
   name: 'post_one',
   description: 'This is the first Post',
   _id: new ObjectId("63fa935f3df313de2df32744"),
   created_at: 1970-01-20T09:56:06.111Z,
   updated_at: 1970-01-20T09:56:06.111Z,
   id: '63fa935f3df313de2df32744'
 }
```

**Comment by vkarpov15** [comment]
@tushar1998 define created_at and updated_at as number paths in your schema in addition to what you've already done. If you don't define created_at and updated_at in your schema, Mongoose will add those paths as dates

**Comment by tushar1998** [comment]
Hey thanks that actually worked in docs they have created_at and updated_at properties in schema set to Number confused for nestjs mongoose and normal mongoose

**Comment by jericokatong** [comment]
@vkarpov15 Thanks, it works
