### ISSUE TITLE
[Feature] Model.bulkSave(...)

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9673]
One common use case in our applications is finding documents, doing some changes on them, then saving them.
```js
const users = await User.find({ cityId: 1 });
await Promise.all(users.map(async function (user){
  let cart = await  Cart.findOne({ userId: user._id });
  if (!cart) {
    cart = new Cart({ userId:user._id });
  }

  cart.itemsIds.addToSet(item._id);
  await cart.save();
}));
```

Looking at the code snippet above, we have around 600k users, running the code above could have the following for carts:
- 300K carts are unchanged, no sent operations to MongoDB, thanks to mongoose checking if the documents are unchanged.
- 150K carts are inserted (isNew === true).
- 150K carts are updated.

This means we send 300K separate operations, which can be very slow.

Would be great if we have a function that can take an array of documents, and `bulkSave` them in a single operation using `Model.bulkWrite(...)`.

It would work like this:
```js
const users = await User.find({ cityId: 1 });
const carts = await Promise.all(users.map(async function (user){
  let cart = await  Cart.findOne({ userId: user._id });
  if (!cart) {
    cart = new Cart({ userId:user._id });
  }

  cart.itemsIds.addToSet(item._id);
  return cart;
}));

// writeResult is a bulkWrite result
// all carts must be instanceof Document
const writeResult = await Cart.bulkSave(carts); // calls Cart.bulkWrite under the hood
```

What do you think? @vkarpov15 
I'm willing to add this feature if accepted.

**Comment by vkarpov15** [comment]
This is a pretty cool idea, I'd love to see it :+1:

**Comment by applefi87** [comment]
Thank u!
I do have this need but don't understand the doc in mongoose.
Now I found this issues,and I realize this is what I need and success!
