### ISSUE TITLE
How to avoid mongoose re-connection each time I invoke a lambda function ?

### ISSUE THREAD

**Issue by jackmatrix** [Automattic/mongoose#9674]
I am using mongoose as database for my node/express js project. I had no problem until I decided to migrate my app to AWS Lambda. There I need to create a persistent connection to avoid my app to connect to mongodb each time a function is invoked. 

So, I've checked the mongoose [docs][1] but it's unclear to me how to integrate this with my current code : 

    app.get("/", (req, res) => { res.send("Hello World!") });
    app.post("/addMessage", myApp.addMessage);
    app.listen(PORT, () => {});
    
    module.exports.handler = serverless(app);

I've tried this, but it did not work 

    let conn = null;
    module.exports.handler = async (event, context) => {
      context.callbackWaitsForEmptyEventLoop = false;
    
      if (conn == null) {
        conn = mongoose.createConnection(URI, {

          bufferCommands: false,
          bufferMaxEntries: 0
        });

        await conn;
      }
    
        serverless(app)
    };

Any suggestion ?

  [1]: https://mongoosejs.com/docs/lambda.html

**Comment by vkarpov15** [comment]
What does your `myApp.addMessage` function look like?

**Comment by jackmatrix** [comment]
Basic 

```javascript
/* inside my file myApp.js */
 
exports.addMessage = () => {
// put my logic here
}
```

**Comment by vkarpov15** [comment]
Not helpful. Can you please provide a more complete example?
