### ISSUE TITLE
pending release label remains after issues are closed

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [Automattic/mongoose#9675]
Currently, we have to manually remove `pending release` from an issue whenever it's closed, would be nice if we can have GitHub automatically remove `pending release` label from an issue when it's closed. https://github.com/Automattic/mongoose/issues/9672#event-4081686498 is an example of an issue opened due to thinking that a feature wasn't released even though it's released in v5.9.0.

Another option would to not use `pending release` altogether and work with open/closed issues.

**Comment by AbdelrahmanHafez** [comment]
I used the following TamperMonkey script to automatically remove the label from issues:
```js
// ==UserScript==
// @name         GitHub remove pending release label
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/Automattic/mongoose/issues/*
// @grant        none
// ==/UserScript==

(function () {
  'use strict';
  docReady(async () => {
    document.querySelector('#labels-select-menu>summary').click();
    await new Promise((resolve) => setTimeout(resolve, 2000));

    document.querySelector('input[data-label-name=\'pending release\'][checked]') && document.querySelector('input[data-label-name=\'pending release\'][checked]').click();
    await new Promise((resolve) => setTimeout(resolve, 2000));

    document.querySelector('#labels-select-menu>summary').click();
    await new Promise((resolve) => setTimeout(resolve, 2000));

    window.close();
  });



  function docReady (fn) {
    // see if DOM is already available
    if (document.readyState === 'complete' || document.readyState === 'interactive') {
    // call on next available tick
      setTimeout(fn, 1);
    } else {
      document.addEventListener('DOMContentLoaded', fn);
    }
  }
}());
```

And to automatically open issues that are closed and have pending release, I went to [this link](https://github.com/Automattic/mongoose/issues?q=label%3A%22pending+release%22+is%3Aclosed), and ran the following script:
```js
document.querySelectorAll('.js-navigation-container.js-active-navigation-container>div').forEach(function (div, i) {
  // more than 10 tabs at a time make the script not work for some reason
  if (i + 1 > 10) {
    return;
  }

  setTimeout(function () {
    window.open(div.querySelector('a').href, '_blank');
  }, i * 500);
});
```

**Comment by vkarpov15** [comment]
Thanks for your help @AbdelrahmanHafez . I think the approach of not using the "Pending Release" label at all is the way to go. You're right that a dangling "Pending Release" label can cause lasting confusion, whereas an issue being closed but not released yet is only temporary. We'll get rid of this label :+1:

**Comment by AbdelrahmanHafez** [comment]
The only use-case I can see to the `pending release` label is major versions.

It's quite useful so that people can tell whether this is `pending release` or it needs someone to implement it, I'd like it much more if we could still have the pending release but have it automatically removed once an issue is closed.
Do you happen to know of a way we can do that?

**Comment by vkarpov15** [comment]
Not off the top of my head. I'm sure there's some tool out there that can do this, or we can write our own tool. But I think I'd much rather just stop using this label for minor releases; those releases usually have a 1-2 month turnaround, so the potential confusion is limited.

**Comment by AbdelrahmanHafez** [comment]
Okay, I think that would work if we could still use them for major releases.

In which case I think we should just close this issue.
