### ISSUE TITLE
Types: Allow Document polymorphism

### ISSUE THREAD

**Issue by notaphplover** [Automattic/mongoose#9679]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug.

**What is the current behavior?**

Any object of a certain type should be assignable to a variable of a parent type, otherwise polymorphism can not be applied

`Document` instances doesn't seem to respect this:

```Typescript
import mongoose, { Document, Model, Schema, SchemaDefinition, SchemaOptions, Types } from 'mongoose';

enum CardType {
  Artifact = 'artifact',
  Creature = 'creature',
  Enchantment = 'enchantment',
  Land = 'land',
}

interface CardDb extends Document {
  _id: Types.ObjectId;
  type: CardType;
}

interface LandDb extends CardDb {
  type: CardType.Land;
}

const cardDbBaseSchemaDefinition: SchemaDefinition = {
  type: { type: String, required: true },
};

const cardDbSchemaOptions: SchemaOptions = { discriminatorKey: 'type' };

export const cardDbSchema: Schema = new Schema(
  cardDbBaseSchemaDefinition,
  cardDbSchemaOptions,
);

export const cardDbModel: Model<CardDb> = mongoose.model<CardDb>(
  'Card',
  cardDbSchema,
  'card',
);

const landDbAdditionalPropertiesSchemaDefinition: SchemaDefinition = {};

export const landDbSchema: Schema = new Schema(
  landDbAdditionalPropertiesSchemaDefinition,
);

export const landDbModel: Model<LandDb> = cardDbModel.discriminator<LandDb>(
  'Land',
  landDbSchema,
  CardType.Land,
);

const sampleLandDb: LandDb = new landDbModel({
   type: CardType.Land,
});

const sampleCardDb: CardDb = sampleLandDb;
```

Expected behavior: no syntax error is found.
Actual behavior: a syntax error is found:

```
Type 'LandDb' is not assignable to type 'CardDb'.
  The types returned by 'delete(...).$where(...).count(...).distinct(...).toConstructor()' are incompatible between these types.
    Type 'new (filter?: _FilterQuery<Pick<LandDb, "type" | "_id">> | undefined, options?: QueryOptions | undefined) => Query<any[], LandDb>' is not assignable to type 'new (filter?: _FilterQuery<Pick<CardDb, "type" | "_id">> | undefined, options?: QueryOptions | undefined) => Query<any[], CardDb>'.
      Types of parameters 'filter' and 'filter' are incompatible.
        Type '_FilterQuery<Pick<CardDb, "type" | "_id">> | undefined' is not assignable to type '_FilterQuery<Pick<LandDb, "type" | "_id">> | undefined'.
          Type '_FilterQuery<Pick<CardDb, "type" | "_id">>' is not assignable to type '_FilterQuery<Pick<LandDb, "type" | "_id">> | undefined'.
            Type '_FilterQuery<Pick<CardDb, "type" | "_id">>' is not assignable to type '_FilterQuery<Pick<LandDb, "type" | "_id">>'.
              Type '_FilterQuery<Pick<CardDb, "type" | "_id">>' is not assignable to type '{ type?: RegExp | CardType.Land | QuerySelector<RegExp | CardType.Land> | undefined; _id?: string | RegExp | ObjectId | { ...; } | QuerySelector<...> | undefined; }'.
                Types of property 'type' are incompatible.
                  Type 'RegExp | CardType | QuerySelector<RegExp | CardType> | undefined' is not assignable to type 'RegExp | CardType.Land | QuerySelector<RegExp | CardType.Land> | undefined'.
                    Type 'CardType.Artifact' is not assignable to type 'RegExp | CardType.Land | QuerySelector<RegExp | CardType.Land> | undefined'.
```
**What is the expected behavior?**

No syntax error should be found.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

- mongodb: 3.6.3
- mongoose: 5.11.5
- typescript: 4.1.2

**Comment by vkarpov15** [comment]
The script you pasted compiles without error. The syntax error you posted says it is due to a `delete(...).$where(...).count(...).distinct(...).toConstructor()` call, which I don't see in your code. Can you please provide a more complete code sample that includes the code that actually causes the syntax error?

**Comment by vkarpov15** [comment]
Also, it is spelled ["polymorphism"](https://www.w3schools.com/java/java_polymorphism.asp).

**Comment by notaphplover** [comment]
Hi @vkarpov15

> The script you pasted compiles without error. The syntax error you posted says it is due to a `delete(...).$where(...).count(...).distinct(...).toConstructor()` call, which I don't see in your code. Can you please provide a more complete code sample that includes the code that actually causes the syntax error?

Wait a minute, I'm opening a repository with a GH action with the syntax error, this way you should be able to reproduce it

> Also, it is spelled "polymorphism".

Thank you, as you can see there is room for improving my english, I'm editing the issue

**Comment by notaphplover** [comment]
@vkarpov15 I just uploaded a public repo with the code sample. You can check the ci action which fails compiling the typescript code: https://github.com/notaphplover/mongoose-type-bug/actions/runs/408960907
