### ISSUE TITLE
TypeError: Invalid value for schema path | Schema.ObjectID issue

### ISSUE THREAD

**Issue by brett-shwom** [Automattic/mongoose#968]
Running on OSX Snow Leopard. Not sure exactly which version of mongoose I'm using, but I just installed it today with 

``` bash
npm install mongoose
```

The code seems to be choking when I use ObjectID as the datatype for a schema field. When I change ObjectID to say String, the error disappears.

Console Output:

```
bretts-Mac-mini:node_code brett$ sudo node example.js 

/Users/brett/Desktop/node_code/node_modules/mongoose/lib/schema.js:108
      throw new TypeError('Invalid value for schema path `'+ prefix + i +'`');
            ^
TypeError: Invalid value for schema path `definition_id`
    at Schema.add (/Users/brett/Desktop/node_code/node_modules/mongoose/lib/schema.js:108:13)
    at new Schema (/Users/brett/Desktop/node_code/node_modules/mongoose/lib/schema.js:38:10)
    at Object.<anonymous> (/Users/brett/Desktop/node_code/example.js:28:30)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

Source

``` javascript
var mongoose = require('mongoose');


var DefinitionRatingSchema = new mongoose.Schema({
    definition_id     : mongoose.Schema.ObjectID
  , rating            : Number
});
```

**Comment by ktkaushik** [comment]
Wow, i just stumbled on the same error. The error message is so cryptic

**Comment by enVolt** [comment]
just to highlight in ObjectId, `d` is small.
Facing this error from yesterday, stumbled on this post twice, just figured what was wrong.

**Comment by jpatricksweeney** [comment]
agreed...cryptic message.  I had not capitalized the "O" in objectId.  thanks for the info all.

**Comment by baribeaup** [comment]
When you Google the error message, this issue page is the top result. So the error message is officially useful now? (My "d" was also uppercase; changed it and it solved the problem)

**Comment by roodoodey** [comment]
In my case I had a small 'm' in mongoose.Schema.Types.mixed instead of mongoose.Schema.Types.Mixed. Hope that helps someone else in the future.

**Comment by JeffWiebe** [comment]
I had "ID". Much gratitude to those who are responsible for this thread. Thanks.
