### ISSUE TITLE
Typings: unable to define model with generic Model<T & Document> 

### ISSUE THREAD

**Issue by ktutnik** [Automattic/mongoose#9684]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I using a generic repository which I'm not inherit the document from `Document` class but I use `T & Document` instead. The repository is something like this

```typescript
class Repository<T> {
    private readonly Model: Model<T & Document> // error T&Document not allowed

    findById(id:string): Promise<T & Document> {
        return Model.findById(id)
    }
    
    /* other methods */
}
```

Previously it was working on Mongoose 5.11.4 until this #9657 applied. It causing the issue. 

After digging into the source code I found that the cause is the `Document.id` is not optional (`Document._id` is optional), since #9657 `id` property excluded in the `LeanDocument`. 

I tested on my local dev, changing `id` into optional `id?` fixed the issue. Maybe other solution?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.5

**Comment by Romakita** [comment]
Hello team,
We have the same issue since v5.11.5 :)

**Comment by Romakita** [comment]
Our workaround work:

```typescript
import {Document, Model} from "mongoose";

export type MongooseMergedDocument<T> = {[K in keyof T]: T[K]};

export interface MongooseModel<T> extends Model<MongooseMergedDocument<Document & T>> {}
```
See you
