### ISSUE TITLE
Model.insertMany() adds _id fields in subdocuments since mongoose 5.10.16

### ISSUE THREAD

**Issue by notaphplover** [Automattic/mongoose#9690]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug

**What is the current behavior?**

Any version of mongoose after 5.10.16 adds _id fields in subdocuments even if the schema does not include the field

**If the current behavior is a bug, please provide the steps to reproduce.**

You can use this code sample to recreate the bug (just adjust the connection params):

```Typescript
import mongoose, { Document, Model, Schema, SchemaDefinition } from 'mongoose';

interface ExtendedGameSetupDb extends Document {
  format: string;
  playerSetups: PlayerSetupDb[];
  playerSlots: number;
}

interface PlayerSetupDb {
  userId: string;
}

const playerSetupDbSchemaDefinition: SchemaDefinition = {
  userId: { type: String, required: true },
};

const extendedGameSetupDbSchemaDefinition: SchemaDefinition = {
  format: { type: String, required: true },
  playerSetups: {
    type: Array,
    of: playerSetupDbSchemaDefinition,
    required: true,
  },
  playerSlots: { type: Number },
};

const extendedGameSetupDbSchema: Schema = new Schema(
  extendedGameSetupDbSchemaDefinition,
);

const extendedGameSetupDbModel: Model<ExtendedGameSetupDb> = mongoose.model<ExtendedGameSetupDb>(
  'TestSubDocuments',
  extendedGameSetupDbSchema,
  'TestSubDocuments',
);

void (async () => {
  await mongoose.connect(
    'mongodb://<your-url>:<yout-port>/<your-db>',
    {
      authSource: '<your-auth-source-if-any>',
      auth: {
        user: '<your-username>',
        password: '<your-password>',
      },
    },
  );

  const extendedGameSetups: ExtendedGameSetupDb[] = await extendedGameSetupDbModel.insertMany([
    new extendedGameSetupDbModel({
      format: 'sample-format',
      playerSetups: [{
        userId: 'sample-user-id'
      }],
      playerSlots: 2,
    }),
  ]);

  console.log(JSON.stringify(extendedGameSetups, undefined, 2));

  await mongoose.disconnect();
})();

```

If mongoose version is greater than 5.10.15, the console should output the following:

```
[
  {
    "_id": "5fd0c5d532e7ad530f2ef2ee",
    "format": "sample-format",
    "playerSetups": [
      {
        "_id": "5fd0c5d532e7ad530f2ef2ef",
        "userId": "sample-user-id"
      }
    ],
    "playerSlots": 2,
    "__v": 0
  }
]

```

In mongoose 5.10.15, the output is the following one:

```
[
  {
    "playerSetups": [
      {
        "userId": "sample-user-id"
      }
    ],
    "_id": "5fd0cb3d6f2988608b92d64c",
    "format": "sample-format",
    "playerSlots": 2,
    "__v": 0
  }
]
```

As you can see, mongoose versions 5.10.16 to 5.11.5 adds an unexpected `_id` field under `playerSetups`.

**What is the expected behavior?**

No _id filed should be added to the subdocuments as it's a breaking change from mongoose 5.10.15.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS 12.x
mongoose: any version from 5.10.16 to 5.11.5.
MongoDB: 4.4.1

**Comment by vkarpov15** [comment]
Ah this is a funny one. Before v5.10.16, Mongoose didn't support `type: Array, of: playerSetupDbSchemaDefinition`. Your schema was defining `playerSetups` as an array of [mixed](https://mongoosejs.com/docs/schematypes.html#mixed). But when we actually added support for that with #9564, your code started actually working as expected and defining `playerSetups` as an array of subdocuments.

Mongoose [subdocuments get an `_id` by default](https://mongoosejs.com/docs/subdocs.html#finding-a-subdocument). To disable it, do:

```javascript
const playerSetupDbSchema: Schema = new Schema({
  userId: { type: String, required: true }
}, { _id: false });
```
