### ISSUE TITLE
TypeError: mongoose.createConnection is not a function

### ISSUE THREAD

**Issue by raptor1989** [Automattic/mongoose#9693]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error calling function `mongoose.createConnection`

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const options = { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false };
export const localDb = mongoose.createConnection(url, options);
```
This fails compilation:
`TypeError: mongoose.createConnection is not a function`

**What is the expected behavior?**
no error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- Node.js v12.13.0
- Mongoose v5.11.6
- MongoDB v3.6.3
- TypeScript v4.1.2

**Comment by vkarpov15** [comment]
How are you importing mongoose?

**Comment by raptor1989** [comment]
Thanks for suggestion. `"esModuleInterop": true` - was problem.  
Sorry for the confusion.

**Comment by vkarpov15** [comment]
Is there something we can do on Mongoose's end to make this not an issue?

**Comment by raptor1989** [comment]
On Mongoose's it's ok. It's a matter of typescript settings
