### ISSUE TITLE
Add method to get all populated docs on a document

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9702]
Re: #8115 . `doc.getPopulatedDocs()` should return an array of all populated documents associated with this doc.

```javascript
const doc = await Story.findOne({ title: 'Casino Royale' }).populate('fans');
console.log(doc.getPopulatedDocs()); // List of all `fans` documents
```

**Comment by AlexRMU** [comment]
$getPopulatedDocs is in the code and types, but not in the documentation
