### ISSUE TITLE
Operation `postmessages.find()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by abdenour-progdes** [Automattic/mongoose#9703]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Please follow the issue template next time.
