### ISSUE TITLE
[Typescript] `ensureIndexes()` and `createIndexes()` should be callable without parameters

### ISSUE THREAD

**Issue by duizabojul** [Automattic/mongoose#9706]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I think there is a little mistake in typescript declaration file

`createIndexes` and `ensureIndexes` should be callable without parameters.

Actually, calling these functions without parameters results in a typescript error `An argument for 'options' was not provided.`

Typescript declaration file is:

```
    ensureIndexes(options: any): Promise<void>;
    ensureIndexes(options: any, callback?: (err: any) => void): Promise<void>;

    createIndexes(options: any): Promise<void>;
    createIndexes(options: any, callback?: (err: any) => void): Promise<void>;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`mongoose.model("XXX").ensureIndexes()`
`mongoose.model("XXX").createIndexes()`

**What is the expected behavior?**

typescript declaration file should define these functions as following:

```
    ensureIndexes(callback?: (err: any) => void): Promise<void>;
    ensureIndexes(options: any, callback?: (err: any) => void): Promise<void>;

    createIndexes(callback?: (err: any) => void): Promise<void>;
    createIndexes(options: any, callback?: (err: any) => void): Promise<void>;
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node 14.15.0
Mongoose 5.11.7

**Comment by duizabojul** [comment]
The commit 6fe409a is wrong semantically speaking, you have to declare two functions and not only mark options optional: you can either use the first argument as a callback, or as options.

See code : https://github.com/Automattic/mongoose/blob/master/lib/model.js#L1524

**Comment by vkarpov15** [comment]
@duizabojul good point, thanks :+1:
