### ISSUE TITLE
Is model.compile recommended to use?

### ISSUE THREAD

**Issue by jayadrathamondal** [Automattic/mongoose#9708]
There is a function "compile" in the instance of Model. Is it recommended to use? 
I need to add some plugins after the schema is compiled and the model is ready to use.

 I'm doing the following which will basically add plugins if there is already some models are generated.
```
    Object.keys(mongoose.models).forEach(modelName => {
        const model = mongoose.models[modelName];
        model.schema.plugin(setDefaultCastErrorMessagePlugin);
        model.compile(model.modelName, model.schema, model.collection.name, model.db, mongoose);
    });
```

There is no documentation related to the function "model.compile", so I need to know if its recommended to use or not.

**Comment by vkarpov15** [comment]
No. `mongoose.model()` calls `compile()` for you, it's purely internal. What makes you think it is necessary to call `compile()`?
