### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by lobermann** [Automattic/mongoose#9709]
**What is the current behavior?**

When updating from 5.10.5 to the latest version, 5.11.7, we are suddenly facing following issue when trying to assign data to a newly, not yet saved model.

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at model.$set (/node_modules/mongoose/lib/document.js:1046:29)
    at model.$set (/node_modules/mongoose/lib/document.js:1062:14)
    at model.$set (/node_modules/mongoose/lib/document.js:1062:14)
    at model.set [as settings] (/node_modules/mongoose/lib/helpers/document/compile.js:161:13)
    at create (/app/controllers/admin/property.js:51:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

The issue is caused by following change
https://github.com/Automattic/mongoose/commit/63fcb045a54fcf2465d26af3f0b81be934613c24
in line 1028 of document.js. Most likely by line 1026 `this.$__getValue` returning null or undefined.

I did not yet have the time to create an isolated unit test for this outside of our software but wanted to create the bug first.

**What is the expected behavior?**
The data is assigned correctly without an exception. I reverted to 5.10.5 and the error is gone. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.7.0
Mongoose 5.11.7
MongoDB 4.4.1

**Comment by vkarpov15** [comment]
I'm unable to repro this, but I figure this issue should go away if we just avoid nullish values by doing `Object.keys(priorVal || {})` so we don't get this error. Fix will be in v5.11.10 :+1:

**Comment by lobermann** [comment]
@vkarpov15 thank you! I did not yet had the time for this, but I am happy to test it with our codebase.

**Comment by silviubogan** [comment]
I have a similar error:

```log
root/path/to/my/project/node_modules/mongoose/lib/helpers/promiseOrCallback.js:20
            throw error;
            ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /root/path/to/my/project/build/server.js:2:530471
    at /root/path/to/my/project/node_modules/mongoose/lib/helpers/promiseOrCallback.js:17:11
    at /root/path/to/my/project/node_modules/mongoose/lib/model.js:5089:21
    at _done (/root/path/to/my/project/node_modules/mongoose/lib/model.js:3181:16)
    at /root/path/to/my/project/node_modules/mongoose/lib/model.js:3196:18
    at callbackWrapper (/root/path/to/my/project/node_modules/mongoose/lib/model.js:3150:20)
    at /root/path/to/my/project/node_modules/mongoose/lib/model.js:5065:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

* I use mongoose 5.13.1, almost the latest version as of this writing (the latest is 5.12.2 as I see on GH releases page).
* I use mongod v4.0.3.
* I use Node.js v12.18.2.

If it is possibly helpful, what part of my configuration should be upgraded?

The same code running under the following configuration does not crash:

* Mongoose 5.13.1.
* mongod v4.4.6.
* Node.js v12.18.2.

Should I post this as a new issue?

I think I will try to upgrade mongod.

Thank you!

**Comment by silviubogan** [comment]
It tells me `WARNING: shell and server versions do not match` when I try to access with the latest mongo v4.4.6 the server with v4.0.3:

> WARNING: shell and server versions do not match

**Comment by silviubogan** [comment]
I upgraded to mongod v4.0.25 and the error is still there.

**Comment by vkarpov15** [comment]
@silviubogan please open a new issue and follow the issue template. Although I suspect this is an issue with your code, because the stack trace you posted indicates that `/root/path/to/my/project/build/server.js:2:530471` is what is calling `Object.keys()`.
