### ISSUE TITLE
[Lambda]Connection Reconnects Exactly in 10 seconds

### ISSUE THREAD

**Issue by devashish90** [Automattic/mongoose#9711]
Details pending

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by vkarpov15** [comment]
Please make sure you've upgraded to at least Mongoose v5.10.13 so you get the fix for #9179, this issue sounds related.
