### ISSUE TITLE
Aggregate.prototype.append() does not exist in Typescript types

### ISSUE THREAD

**Issue by karrui** [Automattic/mongoose#9714]
**Do you want to request a *feature* or report a *bug*?**
Bug 

**What is the current behavior?**
New types in TypeScript does not contain the `append()` type in `Aggregate` class

**If the current behavior is a bug, please provide the steps to reproduce.**

Attempt to use the `append` method on an aggregate object. Error below will be displayed
```
Property 'append' does not exist on type 'Aggregate<unknown[]>'.ts(2339)
```

**What is the expected behavior?**
Correct typing for `Aggregate.prototype.append()`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.8

**Comment by orlandotorres** [comment]
I should probably open a new issue but I wanted to mention that I receive the same error for `unwind()` missing in the `Aggregate` class as well.
