### ISSUE TITLE
Unable to set a base typescript interface

### ISSUE THREAD

**Issue by judemanutd** [Automattic/mongoose#9723]
**What is the current behavior?**
I had this particular setup working on mongoose version 5.10.15 but cannot get it working with 5.11.8. Here is the basic gist

I have the initial interface that extends Document from mongoose

```typescript
export interface IOrder extends IOrderBase, Document {
  _id: ObjectID;
  id: ObjectID;
}
```
And then the lean interface which contains the properties for the model

```typescript
export interface IOrderBase {
  _id: ObjectID;
  id: ObjectID;
  publicId: string;
  id_customer: ObjectID;

 .... other columns

  createdAt: Date;
  updatedAt: Date;
}
```

This is what my schema looks like 

```typescript
const OrdersSchema = new Schema(
  {
    publicId: { type: String, default: null },
    id: {
      type: SchemaTypes.ObjectId,
      default: null,
    },
    id_customer: {
      type: SchemaTypes.ObjectId,
      required: true,
    },
    ...... other columns
  },
  {
    timestamps: true,
    validateBeforeSave: true,
    minimize: false,
  },
);

const Orders = model<IOrder>("Orders", OrdersSchema);
```

**What is the expected behavior?**

The above config allowed for type casting lean queries in the following manner
1. If I wanted a mongoose document I could simply run the following `Orders.findOne({})` and it would return a document of type `IOrder`
2. If I wanted to run a lean query I would use the following `Orders.findOne({}).lean<IOrderBase>(true)` and it would return a document of type `IOrderBase`

This allowed me to differentiate between a mongoose document and a lean document but is failing with the latest version.

________________________________

For the line `export interface IOrder extends IOrderBase, Document {` I get the following error 
```
Interface IOrder incorrectly extends interface 'Document<any>'
```
For the line `const Orders = model<IOrder>("Orders", OrdersSchema);` I get the following error
```
Type IOrder does not satisfy the constraint 'Document<any>'
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node version : 14.15-alpine3.10
mongoose : 5.11.8
@types/mongoose - removed and deleted node_modules

What is the updated config to reflect the output type of a query when its lean?

I have tried the following as the test indicates 
```typescript
const result: LeanDocument<IOrderBase> = await Orders.findOne({}).lean(fetchLean);
```
but the compiler throws the following error

```typescript
Type 'Pick<Pick<_LeanDocument<IOrder>, "status" | "_id" | "id" | "publicId" | ... 19 more ... | "toPublicJson">, "status" | ... 26 more ... | "updatedAt">[]' is not assignable to type 'IOrderBase[]'.
  Type 'Pick<Pick<_LeanDocument<IOrder>, "status" | "_id" | "id" | "publicId" | ... 19 more ... | "toPublicJson">, "status" | ... 26 more ... | "updatedAt">' is not assignable to type 'IOrderBase'.
```

**Comment by vkarpov15** [comment]
Fix will be in v5.11.9. The issue is that `id` is a string on the `Document` class. We changed it to `any` so you can inherit documents with any `id` property type.
