### ISSUE TITLE
Lean function generic parameter not working - TypeScript

### ISSUE THREAD

**Issue by nestorvanz** [Automattic/mongoose#9728]
I've been working with Mongoose and Typescript with @types/mongoose, but in the latest version, the lean function is not working with generic parameters. It seems like the generic parameter has gone

Previous version:
`model.find({}).lean<T>().exec()` -> working fine

Current version:
`model.find({}).lean<T>().exec()` -> `Expected 0 type arguments, but got 1.`

Mongoose version: `5.11.8`,

**Comment by jasonhis** [comment]
I got the same problem, and I just remove it.

The lean() function is smart enough to create the Pick type.  That has all the properties you define in the Model interface with _id.

You don't need lean<t>()
