### ISSUE TITLE
Keeping _id reference for non populated fields when serializing

### ISSUE THREAD

**Issue by ErnestBrandi** [Automattic/mongoose#9731]
Hopefully I am not missing something obvious !

For consistency, I would like to access the _id of fields being populated (or not) the same manner either way.
From the docs, I know that an _id getter is added to ObjectId instances whether the field is populated or not (which is great).
Sadly when the field is serialized, that reference is lost and therefore I cannot access that _id client side.
I thought that the `{ getters : true }` option would help me here, but it does not.

**What is the current behavior?**
Client side I can access the _id in two different ways : 
- `doc.field (if not populated)`
- `doc.field._id (if populated)`

**What would you expect?**
If "populated fields" could serialize the _id field by default; that would make everything easier client side.
Put differently the path `doc.field._id` should always exist.

**Comment by vkarpov15** [comment]
You can do this by registering a [global getter](https://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html) for all objectids that does what you need:

```javascript
  mongoose.ObjectId.get(function(val, schematype) {
    if (!schematype.options.ref) {
      return val;
    }
    if (val instanceof mongoose.Document) {
      return val;
    }
    return { _id: val };
  });
```

Here's a standalone script:

```
'use strict';

const mongoose = require('mongoose');

mongoose.set('debug', true);

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  mongoose.ObjectId.get(function(val, schematype) {
    if (!schematype.options.ref) {
      return val;
    }
    if (val instanceof mongoose.Document) {
      return val;
    }
    return { _id: val };
  });

  const schema = new mongoose.Schema({
    test: String,
    testId: { type: 'ObjectId', ref: 'Test' }
  }, { toJSON: { getters: true } });
  const Model = mongoose.model('Test', schema);

  const doc = new Model({ testId: '0'.repeat(24) });
  console.log(JSON.stringify(doc, null, '  '));

  const other = new Model({ test: 'test' });
  doc.testId = other;
  console.log(JSON.stringify(doc, null, '  '));
}
```
