### ISSUE TITLE
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated

### ISSUE THREAD

**Issue by Charlene-Bx** [Automattic/mongoose#9733]
I report a *bug*;

I use the lasted version of Mongoose, and when i want connect the database, i have this error message;
"*(node:38455) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-deprecation ...` to show where the warning was created)*"

I pass the option in the MongoClient constructor, but i've always the same message... I don't understand why?

Node.js > 14.13.1
Mongoose > 5.11.8
MongoDB > 4.2.11

**Comment by vkarpov15** [comment]
Can you use the `--trace-deprecation` option as suggested and post the stack trace please?
