### ISSUE TITLE
Defaults option is not working for arrays

### ISSUE THREAD

**Issue by coyotte** [Automattic/mongoose#9736]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Defaults option not working for arrays
tests are broken
https://github.com/Automattic/mongoose/blob/master/test/document.test.js#L9125
it uses **defualt** instead of default option

**If the current behavior is a bug, please provide the steps to reproduce.**
```
  const testSchema = new mongoose.Schema({
      testTopLevel: { type: String, default: 'foo' },
      "testArray": [{ 
        prop: { type: String, default: 'baz' } 
      }],
    });
    const Test = db.model('Test', testSchema);
    const doc = new Test({ testArray: [{  }] } , null, {defaults: false}); 
    assert.ok(!doc.testArray[0].prop);
```

**What is the expected behavior?**
 testArray.prop should be empty

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
 node v14.15.2, mongoose 5.11.8

**Comment by edgesinghkataria** [comment]
@vkarpov15 Hi Val,
Can I work on this issue and submit PR?
