### ISSUE TITLE
When trying to generate bulkWrite update array programatically I get "Update document requires atomic operators"

### ISSUE THREAD

**Issue by webjoyable** [Automattic/mongoose#9737]
I'm trying to update multiple documents in collection by programmatically creating an update array for bulkWrite operation with mongoose.

```javascript
let updateArr = [];

data.map((position) => {
    position.quantities.map((quantity) => {
    updateArr.push({
        updateOne: {
        filter: {
            _id: ObjectId(position.position),
            "quantities._id": ObjectId(quantity._id),
        },
        update: {
            $set: {
            "quantity.$.administratorAimedPrice":
                quantity.administratorAimedPrice,
            },
        },
        },
    });
    });
});

console.log(updateArr);

await Position.bulkWrite(updateArr);
```
This is how the array looks like:

```javascript
[                                                       
  { updateOne: { filter: [Object], update: [Object] } },
  { updateOne: { filter: [Object], update: [Object] } },
  { updateOne: { filter: [Object], update: [Object] } },
  { updateOne: { filter: [Object], update: [Object] } },
  { updateOne: { filter: [Object], update: [Object] } },
  { updateOne: { filter: [Object], update: [Object] } } 
]
```

Error:
`POS TypeError: Update document requires atomic operators at OrderedBulkOperation.raw`

It's really frustrating, I couldn't find any examples of generating an update array dynamically. If there is another way to update multiple documents, with different values by targeting different IDs, please share.

Thank you in advance.

`mongoose version: 5.11.8`

**Comment by vkarpov15** [comment]
Can you check if the $set is empty? Mongoose does cast bulkWrite updates, so my guess is that quantity isn’t a path in your schema. Especially since your filter uses quantities but your update uses quantity

**Comment by webjoyable** [comment]
Thank you for the quick reply, this is what I have in the update array

```javascript
  filter: {
    _id: 5fe5fd062903c74c3062d334,
    'quantities._id': 5fe5fd062903c74c3062d335
  },
  update: { '$set': { 'quantity.$.administratorAimedPrice': 33 } }
}
```

**Comment by webjoyable** [comment]
Long hours :) You are right, it wasn't a path in the schema, I thought it was a bug. Thank you for your time, and happy holidays.
