### ISSUE TITLE
Using async method in mongoose schema

### ISSUE THREAD

**Issue by tbhaxor** [Automattic/mongoose#9739]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

I want to run async script in `default` property of the schema field and  assign the value

```js
const schema = new mongoose.Schema({
    app: {
      type: String,
      default: async function () {
        return new Promise((resolve) => {
          setTimeout(() => {
            resolve('HELLO WORLD');
          }, 3000);
        });
      }
    }
  });
```

**What is the expected behavior?**

It should make the new value with the `HELLO WORLD` as the value of app

I have also testing using the pre init hook

```js
  schema.pre('init', function (next) {
    setTimeout(() => {
      this.app = 'HELLO WORLD2';
      next();
    }, 3000);
  });
```

It is also not working

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Nodejs: v15.0

Mongoose: v5.11.8

**Comment by vkarpov15** [comment]
We've bounced around the idea of async defaults in several issues, including #6781, but the reality is that we cannot without some major caveats. When you do `const app = new App()`, the default wouldn't be set yet, and there's no way to make a constructor async without breaking people's code.

**Comment by tbhaxor** [comment]
I agree @vkarpov15 . But you can expose a builder function for example

```js
const app = await App.build({...someValues})
```

**Comment by vkarpov15** [comment]
Then the problem is that everyone would have to change their code to use `await App.build()`, which isn't really feasible.

Instead of an async default, why not use  `post('find')` middleware?
