### ISSUE TITLE
DeprecationWarning:

### ISSUE THREAD

**Issue by Suraj02303** [Automattic/mongoose#9751]
**Do you want to request a *feature* or report a *bug*?**

(node:16924) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

**Comment by Suraj02303** [comment]
yes i have tried most of the different  method like adding {useUnifiedTopology: true } , downgrading  and upgrading mongoose but the problem yet not get resolved so please help me to fix this issue
here is my code
![image](https://user-images.githubusercontent.com/67150786/103348309-a1e0b800-4abf-11eb-9b6b-4ee5a0ccdf3e.png)

here is the issue screen shot
![image](https://user-images.githubusercontent.com/67150786/103348201-53331e00-4abf-11eb-9736-c9ef477ccd14.png)

**Comment by vkarpov15** [comment]
Run `npm list | grep "mongo"` and post the output. My best guess is that you have another package that uses MongoDB that's causing this warning.

**Comment by Suraj02303** [comment]
+-- mongoose@5.11.9
| +-- @types/mongodb@3.6.3
| +-- mongodb@3.6.3
| +-- mongoose-legacy-pluralize@1.0.2
| +-- mongodb@3.6.3 deduped
| +-- mongodb-uri@0.9.7


here the output after running npm list | grep "mongo".

  @vkarpov15

**Comment by vkarpov15** [comment]
What is the `Grid` function in your example?

**Comment by KensingtonTech** [comment]
@vkarpov15 I also see this behaviour.  Using `{useCreateIndex: true}` in connect options yields the deprecation warning, whilst Mongoose.set('useCreateIndex', true); suppresses it.  There are no other packages in my app that use MongoDB.  package-lock.json confirms I'm using Mongoose 5.11.11 and MongoDB 3.6.3

**Comment by vkarpov15** [comment]
@KensingtonTech can you please open a new issue and follow the issue template?
