### ISSUE TITLE
 Type 'Function' must have a '[Symbol.iterator]()'

### ISSUE THREAD

**Issue by fkamp** [Automattic/mongoose#9755]
Heyya, in mongoose 5.10.11 I used the following Typescript code with no issue.

```javascript

export const UserSchema = new mongoose.Schema({
  someArray:[String]
});

UserSchema.methods.doSomething = function (): void {
  for (let item of this.someArray) {
    console.log(item)
  }
};
```

With 5.11.9, Typescript complains that this.someArray is of Type 'Function' and must have a '[Symbol.iterator]()' method that returns an iterator. I can probably do some casting as a workaround but should possibly be fixed in Typescript definition. Thx!

**Comment by vkarpov15** [comment]
We added a test case for this ☝️ and it passes. Can you please provide a more complete code sample that demonstrates your issue?

**Comment by fkamp** [comment]
Happy New Year :-)
Thanks for looking at it so quickly. Here is a test repo where the error can be reproduced.
https://github.com/fkamp/mongoose-9755
