### ISSUE TITLE
Timestamps not working again in case of bulk updateOne

### ISSUE THREAD

**Issue by vikas-garg** [Automattic/mongoose#9759]
Again facing the same bug #5708. Timestamp not added after updateOne method in bulk operations.

Code snippet of the function I am using for my bulk upserts

```javascript
const bulkUpsert = async (documents) => {
    let bulk = Model.collection.initializeUnorderedBulkOp()
    let counter = 0

    for (const document of documents) {
        const query = {
            cond1: document.cond1,
            cond2: document.cond2
        }

        bulk.find(query).upsert().updateOne(document)
        counter++

        if (counter % 1000 === 0) {
            bulk.execute(function (err, result) {
                bulk = HoldingTransactionModel.collection.initializeOrderedBulkOp()
            })
        }
    }

    if (counter % 1000 !== 0) {
        bulk.execute(function (err, result) {
            // bulk = HoldingTransactionModel.collection.initializeOrderedBulkOp()
            // do something if you want
        })
    }
}
```
Node Version: 14.14.0
Mongoose Version: 5.10.9

@vkarpov15 Please Help with this issue.

**Comment by AbdelrahmanHafez** [comment]
Welcome to GitHub @vikas-garg 

It seems like you're bypassing mongoose altogether by using native methods:
```js
Model.collection.initializeUnorderedBulkOp
```

Try using mongoose [Model.bulkWrite](https://mongoosejs.com/docs/api.html#model_Model.bulkWrite) instead, as mongoose has no control over the behavior of the native driver.

**Comment by vkarpov15** [comment]
@AbdelrahmanHafez is right. Mongoose won't set timestamps if you bypass Mongoose by using `HoldingTransactionModel.collection.X`. Use `bulkWrite()` instead.
