### ISSUE TITLE
Type undefined $inc in model.findOneAndUpdate

### ISSUE THREAD

**Issue by kristiandrex** [Automattic/mongoose#9767]
Hello,

When I try to do an update using model.findOneAndUpdate() and use the $inc attribute I get the following error: Type 'number' is not assignable to type 'undefined'.

`
await Chat.findOneAndUpdate(
    { from: message.to, to: message.from },
     { $inc: { unread: -1 } }
 );
`

![Error screenshot](https://user-images.githubusercontent.com/26419041/103597453-43a44280-4ece-11eb-9f1f-6803c637805f.png)

mongoose: ^5.11.10
typescript: ^3.9.7
nodejs: v14.15.0

**Comment by vkarpov15** [comment]
I'm unable to repro this. We have a [test case](https://github.com/Automattic/mongoose/blob/8066fd268fb23cc43e1ea83584ac389f7506431b/test/typescript/queries.ts#L38) for this and it is passing, and that file works just fine on my VSCode even with TypeScript 3.x:

![image](https://user-images.githubusercontent.com/1620265/103811830-892a5200-502b-11eb-9d4d-1a5b836bcb6e.png)

Can you please provide a more complete example, including schemas, object interface definitions, and `tsconfig.json`?

**Comment by kristiandrex** [comment]
Sorry for the inconvenience, apparently it was just a bug between VSCode and Typescript.
