### ISSUE TITLE
Missing type check for FilterQuery

### ISSUE THREAD

**Issue by BorntraegerMarc** [Automattic/mongoose#9772]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

No transpilation error.

**If the current behavior is a bug, please provide the steps to reproduce.**

There are 2 scenarios that should be fixed. For both scenarios I define the following Schema:
```ts
const RoleSchema: Schema = new Schema({
    assignments: {
        type: Schema.Types.Number,
        required: true,
    }
});
```

# Scenario 1

```ts
class Role {
    assignments: number;
}

const roleModel: Model<Document<Role>> = model<Document<Role>>('roles', RoleSchema);
roleModel.find({ assignments: 'xxx' }); // <-- This line does not throw a transpilation error even though a string is not assignable to a number
```

# Scenario 2

```ts
class Role {
    assignments: number;
}

const roleModel: Model<Document<Role>> = model<Document<Role>>('roles', RoleSchema);
roleModel.find({ assignments2: 2 }); // <-- This line does not throw a transpilation error even though property "assignments2" does not exist on class "Role"
```

**What is the expected behavior?**

Both scenarios should produce a transpilation error.

_Additional info:_ After some debugging I noticed that _Scenario 1_ is behaving correctly when extending `Document`. Example:
```ts
class RoleDocument extends Document {
    assignee: number;
}

const roleModel: Model<RoleDocument> = model('roles', RoleSchema);
roleModel.find({ assignee: 'XXX' }); // <-- Produces TS error "Type 'string' is not assignable to type 'Condition<number>'"
```

I would expect the same behaviour when using `Model<Document<Role>>`

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: v12.13.0
Mongoose: v5.11.9

**Comment by BorntraegerMarc** [comment]
For easier reproduction my `tsconfig.json`:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es6",
        "sourceMap": true,
        "allowJs": true,
        "outDir": "./build",
        "baseUrl": "./"
    },
    "include": ["."],
    "exclude": ["./node_modules"]
}
```

**Comment by vkarpov15** [comment]
Both scenarios are expected behavior. In case (1), Mongoose automatically converts strings to numbers where possible, so `roleModel.find({ assignments: '2' })` is equivalent to `roleModel.find({ assignments: 2 })`.

In case (2), unless  the [`strictQuery` option](https://mongoosejs.com/docs/guide.html#strictQuery) is enabled, Mongoose allows you to query by fields that aren't defined in your schema.

**Comment by BorntraegerMarc** [comment]
Thank you for the explanation @vkarpov15. I see your point for case (1).

However I believe case (2) is still a bug. Even if I initialize the schema with `strictQuery` option the typescript transpilation does not throw any error:

```ts
const RoleSchema: Schema = new Schema({
    assignments: {
        type: Schema.Types.Number,
        required: true,
    }
}, { strict: true, strictQuery: true });
```

**Comment by vkarpov15** [comment]
We may consider making type bindings strict mode aware in the future, but I don't think that's a high priority right now. PRs are welcome though :+1:
