### ISSUE TITLE
Connecting to MongoDB with in docker-compose containers fail with useUnifiedTopology=true

### ISSUE THREAD

**Issue by erezsdev** [Automattic/mongoose#9775]
**What is the current behavior?**
I have a NodeJS Application that connects to a MongoDB server via mongoose.

Both the node application and MongoDB server are served in a docker container (with `docker-compose`)

`docker-compose.yml`:

    version: '3'
    services:
     redis:
      image: "redis:alpine"
      ports:
       - "6379:6379"
      expose:
       - 6379
      restart:
       always
      container_name: redis-server
    
     mongo:
      image: "mongo"
      command: mongod --bind_ip_all --replSet rs8
      volumes:
       - c:\mongo\data:/data/db
      ports:
       - "27017:27017"
      expose:
       - 27017
      restart:
       always
      container_name: mongo-server
       
     accounts-service:
      depends_on:
        - redis
        - mongo
      build:
        context: .
        dockerfile: GenericNodeJSDockerfile
      container_name: accounts-service
      ports:
       - "8001:8001"

In the node app, the connection in mongo looks like this:

    const m = require('mongoose')
    const connectionConfig = {
    	useUnifiedTopology: true,
    	useNewUrlParser: true,
    };

    let connectionString = 'mongodb://mongo:27017/mydb/replicaSet=rs8';

    m.connect(connectionString , connectionConfig).then(_ => {
        console.log("Connected to MongoDB")
    }).catch(err => {
        console.log("Failed connecting to MongoDB: " + err);
    });

(Note: I have already tried connecting without setting replSet)
And the error that is thrown is:

`Failed connecting to MongoDB: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017`

But when I'm commenting the row contains `useUnifiedTopology` option, the connection succeeds.

When I'm debugging the nodejs application without using the docker (i.e mongo is served on docker and nodejs application on the host machine without docker) it works as expected.

Does anyone have an idea how to fix it?

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Dockerize your nodejs application
2. Run mongodb server on docker
3. Try to connect to the mongodb server from nodejs application via mongoose while both running on a docker

`tsconfig.json`
```
{
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "outDir": "./dist",
      "strict": true,
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "noImplicitAny": false,
      "strictNullChecks": false,
      "noImplicitThis": false,
      "skipLibCheck": true
   }
}
```

**What is the expected behavior?**
Should connect without errors

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NPM: 6.14.8
Node: 12.19.1
Mongoose: 5.11.10
MongoDB server version: 4.4.2

**Comment by erezsdev** [comment]
It turns out that I had a bad `hosts` file configuration.

**Comment by sohel902833** [comment]
can you tell me what kind of hosts conf you have changed, I am also facing the same kind of issue

**Comment by taseenb** [comment]
Do not use underscore in hostnames. Notice that Docker Compose `container_name` is also used as hostname, which creates problems and should be deprecated by Docker. Prefer the `hostname` property to define your connections between containers. Underscores may create connection issues because they make invalid hostnames according to DNS standards.
