### ISSUE TITLE
collection.find() cannot fetch the data , shows only empty array 

### ISSUE THREAD

**Issue by AnishGupta** [Automattic/mongoose#9777]
**Do you want to request a *feature* or report a *bug*?**
I think it is a bug

**What is the current behavior?**
I have wrote down the source code file , one for model and other for back-end. I have installed the mongodb community server and even used mongodb atlas . Whenever I am trying to fetch the document from collection (collection.find({})) Instead of getting the documents , I am getting an empty array . 

**If the current behavior is a bug, please provide the steps to reproduce.**

model.js
`let mongoose = require('mongoose');
const article = mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    author:{
        type:String,
        required:true
    },
    desc:{
        type:String,
        required:true
    }
});
module.exports = mongoose.model("Article",article);` 

index.js
 
`var mongoose = require('mongoose');
mongoose.connect("mongodb://localhost/ml",{
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useCreateIndex: true,
  }).then( () => {
    console.log("Database is Connected Successful");
}).catch(err => console.log(err));
var Article = require('./model/model');
Article.find({},(err,data) => {
    if(err){
        console.log(err);
    }else{
        console.log(data);
    }
});`

mongodb collection list : 

`db.article.find()

{ "_id" : ObjectId("5ff6e22a516c5c65c73baef9"), "title" : "Data Science", "author" : "Anish Gupta", "desc" : "Data Science is core branch of Machine learning" }
{ "_id" : ObjectId("5ff6e22a516c5c65c73baefa"), "title" : "Mathematics", "author" : "Anish Gupta", "desc" : "Mathematics is core tools for Machine Learning" }
{ "_id" : ObjectId("5ff6e26b516c5c65c73baefb"), "title" : "Machine Learning", "author" : "Anish Gupta", "desc" : "Machine Learning is a great tools" }`

The Output is : 

`Database is Connected Successful
[]`

**What is the expected behavior?**
I wanted to get the document instead of empty array like this "[]" .

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js => 15.4.1
MongoDB => 4.4.3
Mongoose => 5.11.10

**Comment by vkarpov15** [comment]
Pluralization. Try this instead: `mongoose.model("Article",article, 'article')`

**Comment by AnishGupta** [comment]
@vkarpov15  Thanks for the help ... It works for me
