### ISSUE TITLE
Hook for pre model creation.

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9782]
**Do you want to request a *feature* or report a *bug*?**
Feature.
**What is the current behavior?**
Hi, I've doing a Model to allow pdf creation from a template, assigned to a model.
something like:
```js
//any weird definitions is for my FW
  const PDFTemplate = new db.Schema(
    {
      name: {
        type: String,
        name: "Nombre",
        description: "El nombre del template"
      },
      model: {
        type: "Models",
        name: "Modelos",
        description: "El modelo sobre el cual se hará el template"
      },
      virtual: {
        type: String,
        name: "Nombre Campo",
        description: "El nombre del campo virtual que vinculará el template"
      },
      func: {
        type: String,
        name: "Método",
        description: "El nombre del método que ejecutará el template"
      },
      header: {
        type: "HTML",
        name: "Encabezado de página",
        description: "Encabezado del PDF, se puede omitir, recibe currentPage, pageCount y pageSize"
      },
      body: {
        type: "HTML",
        name: "Cuerpo",
        description: "El cuerpo del PDF"
      },
      footer: {
        type: "HTML",
        name: "Pié de página",
        description: "Pié de página del PDF, se puede omitir, recibe currentPage, pageCount y pageSize"
      }
    },
    {
      name: "Administración de plantillas para PDF",
      description: "Permite definir plantillas que generan PDFs para un documento en particular del modelo definido",
      methods: ["GET", "POST", "PUT", "DELETE"]
    }
  );
```

I've already have a function that allows to add a method to the schema that creates a pdf, but it's made programmatically, now I want to attach a method when it's defined in this model.

The only way I can imagine it's to add a plugin who can add the method(s) before the schema is converted to model, something like:
```js
  db.plugin(schema => {
    schema.pre("model", async function (db) {
      const templates = await db.model("PDFTemplate").find({model: this.modelName});
      [...templates].forEach(template => {
        schema.method({[template.func]: createPDF(template)});
      });
    });
  });
```
As several plugins uses mongoose as argument I think there is no security problem with this kind of definition.
Or course it's just an idea, there is flow problems with this definition, like you must convert this schema to model before apply to others schemas and you have to do it only for other models, but it's easily fixed. 

What do you think? can it be done?

**Comment by vkarpov15** [comment]
`schema.pre('model')` is what [plugins](https://mongoosejs.com/docs/plugins.html) are for. Any reason why you can't just write a plugin?

**Comment by chumager** [comment]
Hi, I mean the moment before converting a schema into model, when you know the name of the model so I can add the method.

Imagine for one side I've a path with archives who exports schemas, but I don't know which schemas are there, justo know in that path I've to load all the schemas and turn them into models.

In the other hand I've a model that allows me to define a document associated with a model (PDF, HTML), and want to declare it as method so later anyone can do document.templateX() (document is a document from a model how has a template defined in the templates model and templateX is the template defined) and return the document defined in the template model.

That way a developer can define any schema he wants and the client can define how to generates a downloadable archive with his format, not depending on a developer to build a function who returns an archive.

I know I can be less abstract and just query in the templates model for the templates assigned to a model and the use it, but my FW uses virtuals to show the capability of download documents (archives) for a document (in the DB), and now it's done programmatically and I want to do it from the database and the only way I can imagine that is by injecting the method knowing the model name that it's defined in the templates model, and as says in the same URL you publish https://mongoosejs.com/docs/plugins.html#apply-plugins-before-compiling-models I can't do it after the model is defined.

Other way could be to query before creating the models with mongo instead of mongoose.

Did I make myself clear or I'm too confusing? 

Regards

**Comment by vkarpov15** [comment]
I think the better way to do this would be to define a separate method:

```javascript
schema.methods.createTemplate = async function createTemplate(templateName) {
  const template = await db.model('PDFTemplate').findOne({ model: this.modelName, func: templateName });
  return createPDF(template);
};
```

Variable methods based on model name isn't something we can easily support right now and I think this approach is straightforward enough.

**Comment by chumager** [comment]
Hi, that's how I do it now, but it's a direct attach, now I can't because the schema ain't know wich templates it has.

What happens if I develop a static who creates a method? It's a problem with that?

```js
schema.static({
  initMethods(){
    schema.method({
      somethind(){...}
    });
  }
});
```

then after create all the models just call ```model.initMethods();```

Is it plausible?

Regards

**Comment by vkarpov15** [comment]
I think the better approach is to just have one method that takes the `template` as a parameter. Why define a bunch of methods that do essentially the same thing when you can just define one method?
