### ISSUE TITLE
Expose mongoose.Query._pre as public

### ISSUE THREAD

**Issue by stalniy** [Automattic/mongoose#9784]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current  behavior**

`mongoose.Query._pre` undocumented and private

**What is the expected behavior?**

`mongoose.Query._pre` documented and public

**Why?**

I’m an author of casl (permission management system) and I wrote a plugin for mongoose which adds `accessibleBy` static method to model. This method returns accessible records from db based on user permissions. 

There are cases when I can predict that there is no such records in db and instead of sending dummy query that returns no results, I’d like to throw an error that user doesn’t have permissions. 

I can use pre exec hook on query to achieve this but currently it’s private and I don’t want to use private method which eventually may disappear without any notice in release

**Comment by stalniy** [comment]
looks like I can just patch `Query.exec` method. As far as I see it's used as a gate for all db queries, right?

**Comment by vkarpov15** [comment]
This is something we've been wanting to do for a while. We will look into this for our next minor release.
