### ISSUE TITLE
cannot update data on capped collection

### ISSUE THREAD

**Issue by riez** [Automattic/mongoose#9786]
I'm trying to update a field on a capped collection but its give me error
the code that i use:
`this.connection.db.collection('message_store').findOneAndUpdate({"position.z": 1234}, {'$set': {'position.z': 1000}})`
the error:
`
UnhandledPromiseRejectionWarning: MongoError: Cannot change the size of a document in a capped collection: 358 != 354
`

I'm was trying the same command on mongo shell and its able to update
`db.message_store.findOneAndUpdate({"position.z": 1234}, {$set: {"position.z": 1000}})`

**Comment by vkarpov15** [comment]
Below script works as expected. Please modify the below script to demonstrate your issue. Also, please provide your versions of Mongoose and MongoDB.

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('debug', true);
mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    bufferCommands: false
  });

  await mongoose.connection.dropDatabase();

  const Capped = mongoose.model('Capped', Schema({ position: { z: Number } }, { capped: 1024, autoIndex: false, autoCreate: false }), 'message_store');
  await Capped.createCollection();

  console.log('Created');

  await Capped.create({ position: { z: 1234 } });
  await mongoose.connection.db.collection('message_store').findOneAndUpdate({"position.z": 1234}, {'$set': {'position.z': 1000}});
  console.log('Done');
}

```
