### ISSUE TITLE
Typescript classes inheritance broken after upgrade from mongoose 5.10.13 to 5.11.11

### ISSUE THREAD

**Issue by ludovic-lambert** [Automattic/mongoose#9790]
**Bug**

Before upgrading to mongoose 5.11.11, the following code was working fine (I simplified it for clarity):

```
abstract class Route {
 constructor (readonly ObjectModel: Model<any>) {
  }

  async getAll(req: Request, res: Response) {
    query = this.ObjectModel.find()
    query.exec((err, docs) => {
      if (err) return res.status(400).json({ message: err })
      res.json(docs)
    })
  }
}

class ImageRoute extends Route {
  constructor () {
    super(Images)
  }
  this.ObjectModel.findOne({ filename: filename })
    .then((doc) => {
      if (doc) {
        doc.isValid = true
        doc.save()
          .then((savedDoc) => {
            if (savedDoc === doc) {
              res.redirect(someWhere)
            } else {
              res.status(500).json(errorMessage)
            }
          })
      }
    })
}
```
Where _Images_ is a Model.

**What is the current behavior?**

After upgrade I get the following Typescript error, which ic occuring for all my existing Models using the same inheritance:

```
ERROR in xxx\src\controlers\ImageRoute.ts
./src/controlers/ImageRoute.ts
[tsl] ERROR in xxx\src\controlers\ImageRoute.ts(27,20)
      TS2345: Argument of type 'Model<ImageDocument>' is not assignable to parameter of type 'Model<Document<any>>'.
  The types returned by 'createCollection(...)' are incompatible between these types.
    Type 'Promise<Collection<ImageDocument>>' is not assignable to type 'Promise<Collection<Document<any>>>'.
      Type 'Collection<ImageDocument>' is not assignable to type 'Collection<Document<any>>'.
        Types of property 'bulkWrite' are incompatible.
          Type '{ (operations: BulkWriteOperation<ImageDocument>[], callback: MongoCallback<BulkWriteOpResultObject>): void; (operations: BulkWriteOperation<...>[], options?: CollectionBulkWriteOptions | undefined): Promise<...>; (operations: BulkWriteOperation<...>[], options: CollectionBulkWriteOptions, callback: MongoCallback<.....' is not assignable to type 
'{ (operations: BulkWriteOperation<Document<any>>[], callback: MongoCallback<BulkWriteOpResultObject>): void; (operations: BulkWriteOperation<...>[], options?: CollectionBulkWriteOptions | undefined): Promise<...>; (operations: BulkWriteOperation<...>[], options: CollectionBulkWriteOptions, callback: MongoCallback<.....'.
            Types of parameters 'operations' and 'operations' are incompatible.
              Type 'BulkWriteOperation<Document<any>>[]' is not assignable to type 'BulkWriteOperation<ImageDocument>[]'.
                Type 'BulkWriteOperation<Document<any>>' is not assignable to type 'BulkWriteOperation<ImageDocument>'.
                  Type 'BulkWriteInsertOneOperation<Document<any>>' is not assignable to type 'BulkWriteOperation<ImageDocument>'.
                    Type 'BulkWriteInsertOneOperation<Document<any>>' is not assignable to type 'BulkWriteInsertOneOperation<ImageDocument>'.
                      The types of 'insertOne.document' are incompatible between these types.
                        Type 'Pick<Document<any>, "__v" | "$ignore" | "$isDefault" | "$isDeleted" | "$isEmpty" | "$isValid" | "$locals" | "$markValid" | "$op" | "$session" | "$set" | "$where" | ... 40 more ... | "validateSync"> & { ...; }' is not assignable to type 'WithId<ImageDocument>'.
                          Type 'Pick<Document<any>, "__v" | "$ignore" | "$isDefault" | "$isDeleted" | "$isEmpty" | "$isValid" | "$locals" | "$markValid" | "$op" | "$session" | "$set" | "$where" | ... 40 more ... | "validateSync"> & { ...; }' is missing the following properties from type 'ImageDocument': title, description, keywords, folder, and 7 more.
 @ ./src/routes/images.ts 15:21-56
 @ ./src/api.ts 48:20-46
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See code above.

I'm using the following Typescript config:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "outDir": "./build",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**What is the expected behavior?**
I don't see any reason why `Model<ImageDocument>` and `Model<Document<any>>` have become incompatible.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
_Before upgrade:_
Node v14.15.0
MongoDB 4.4.1 Community
Mongoose 5.10.13
@types/mongoose 5.10.0

_After upgrade:_
Node v14.15.0
MongoDB 4.4.1 Community
Mongoose 5.11.11

**Comment by ludovic-lambert** [comment]
After uninstalling @types/mongoose as types are directly supported in mongoose 5.11, I manage to get a type error free version. Switching main class constructor parameter between `Model<Document>` and `Modele<any>` led to various types errors about Document variables in the code:
* Using Model<any> leads to less types error in sub-classes and many types error in the abstract class, requiring to hard-type every `doc` variables, eg `this.ObjectModel.findById({ _id: req.params.id }).then((doc: Document) => {[...]}`
* Using Model<Document> leads to a clean main abstract class (all `doc` vars types were automatically recognized), but requires to type all sub-classes `doc` vars to appropriate sub-model, eg ImageDocument.

At the end of the day, either there's something wrong in Document typing, or I misunderstand how to have an abstract class using a Model with a generic `Document`, extended by sub-classes using Models with more specific Documents.

**Comment by stalniy** [comment]
This issue is related to breaking changes introduced by 5.11, when official types where provided. Typescript merges @types/mongoose and mongoose/index.d.ts together what leads to incompatibility issues in types. As a temporary workaround add post install hook in package.json:

```json
{
  “scripts”: {
    “postinstall”: “rm -f ./node_modules/mongoose/index.d.ts”
  }
}
```

or rewrite your app to use official typings

**Comment by vkarpov15** [comment]
Make sure you explicitly remove `@types/mongoose` with `rm -rf ./node_modules/@types/mongoose`. The below script compiles fine as long as you don't have `@types/mongoose`.

If you still have an issue, please modify the below script to demonstrate the compile failure.

```typescript
import { Request, Response } from 'express';
import { Model } from 'mongoose';

abstract class Route {
 constructor (readonly ObjectModel: Model<any>) {
  }

  async getAll(req: Request, res: Response) {
    let query = this.ObjectModel.find()
    query.exec((err, docs) => {
      if (err) return res.status(400).json({ message: err })
      res.json(docs)
    })
  }
}

class ImageRoute extends Route {
  method(res: Response, filename: string) {
  this.ObjectModel.findOne({ filename: filename })
    .then((doc) => {
      if (doc) {
        doc.isValid = true
        doc.save()
          .then((savedDoc) => {
            if (savedDoc === doc) {
              res.redirect('/test')
            } else {
              res.status(500).json({ error: 'test' })
            }
          })
      }
    })
  }
}

```

**Comment by Xenya0815** [comment]
I run into the same issue.

It is not enough to just remove `@types/mongoose` from the dependencies, as other dependencies could add the types again.

For example, the `@types/mongoose-geojson-schema` has the following entry in its package.json:

```
"dependencies": {
  "@types/mongoose": "*"
}
```

Could the `moment` component solution be a solution here too? They published `@types/moment` without any type declarations but with the entry `"deprecated": "This is a stub types definition for Moment (https://github.com/moment/moment). Moment provides its own type definitions, so you don't need @types/moment installed!"` in the packagge.json.

**Comment by vkarpov15** [comment]
I unfortunately don't have access to `@types/mongoose`, but one potential workaround is a postinstall script:

```javascript
"postinstall": "rm ./node_modules/@types/mongoose/index.d.ts"
```

**Comment by tipoc123** [comment]
> I unfortunately don't have access to `@types/mongoose`, but one potential workaround is a postinstall script:
> 
> ```js
> "postinstall": "rm ./node_modules/@types/mongoose/index.d.ts"
> ```

This solution doesn't work.

**Comment by tipoc123** [comment]
> This issue is related to breaking changes introduced by 5.11, when official types where provided. Typescript merges @types/mongoose and mongoose/index.d.ts together what leads to incompatibility issues in types. As a temporary workaround add post install hook in package.json:
> 
> ```json
> {
>   "scripts": {
>     "postinstall": "rm -f ./node_modules/mongoose/index.d.ts"
>   }
> }
> ```
> 
> or rewrite your app to use official typings

It works fine.
