### ISSUE TITLE
db.listCollections() does not return list of collections

### ISSUE THREAD

**Issue by PowellTravis** [Automattic/mongoose#9791]
**Do you want to request a *feature* or report a *bug*?**
Help
**What is the current behavior?**
Just outputs commandCursor error
**If the current behavior is a bug, please provide the steps to reproduce.**

const TFData = mongoose.createConnection('mongodb://__IP__/TFData', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
    useCreateIndex: true
}, err => {
    if(!err) {
        console.info("Connected to TFData Database");
        dataCollection()
    } else {
        console.error("Failed to connect to TFData Database!");
    }
});

function dataCollection() {
    TFData.db.listCollections()
    .next(function(err, tdata) {
        console.log(tdata)
        var tdataLen = Object.keys(tdata).length
        for(var i = 0; i < tdataLen; i++){
            console.log(tdata[i])
            $(".tdata").append(`<li class="tdata-item">
            <a class="tdata-link">${tdata.name}</a>
            </li>`);
        }
    })
    TFData.close()
}

**What is the expected behavior?**
I was expecting the command to output a list of collections inside of the specific database. Any help would be appreciated. Nothing I have found helps at all.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: 12.17.0; Mongoose: 5.11.11; MongoDB: 4.4.1;

**Comment by sahasayan** [comment]
try this 

```javascript
function dataCollection() {
    TFData.db.listCollections().toArray(function(err, tdata) {
        console.log(tdata)
        var tdataLen = Object.keys(tdata).length
        for(var i = 0; i < tdataLen; i++){
            console.log(tdata[i])
            $(".tdata").append('<li class="tdata-item"> <a class="tdata-link">${tdata.name}</a> </li>');
        }
        TFData.close();
    });
}
```

**Comment by PowellTravis** [comment]
Thank you very much for the quick response. That did work! I will close the issue.
