### ISSUE TITLE
mongoose doesn't allow me to create a collection with camelCase name

### ISSUE THREAD

**Issue by Shofiul735** [Automattic/mongoose#9799]
Do you want to request a feature or report a bug?
Report a bug.

What is the current behavior?
mongoose doesn't allow me to create a collection with camelCase name

What is the expected behavior?
I used "classTests" as name of my collection,it should create a collection given name when i saved date and collection doesn't exist, but it creates collection name like this: "classtests"

What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.
Node.js: v14.15.2
Mongoose: latest
Mongodb: latest

Here is my code:

const mongoose = require("mongoose");

mongoose.connect("mongodb://localhost:27017/miniRDS",{
        useNewUrlParser:true,
        useCreateIndex:true,
        useUnifiedTopology: true,
        useFindAndModify: false
},(err)=>{
    if(!err){
        console.log("Connected")
    }else{
        console.log("Couldn't connect!");
    }
});

const tests = new mongoose.Schema({
    subject:{
        type:String,
        required:true,
        default:"ict"
    },
    date:{   
       type:String,
       required:true,
       default:"01-01-2021"
    }
});
const testsModel = mongoose.model("classTests",tests);

const s =  new testsModel({
    subject:"english",
    date:"12-01-2021"
});
s.save();

It creates a collection, name "classtests" instead of "classTests"

**Comment by vkarpov15** [comment]
Expected behavior based on how Mongoose pluralize works. If you want to specify a collection name, do `const testsModel = mongoose.model("classTests",tests, 'classTests');`

**Comment by jamisonj** [comment]
I ran into this issue as well, when I tried to create a model named `customerLogs`. It created two collections: One named `customerLogs` and one named `customerlogs`. Dumb.
