### ISSUE TITLE
Nested schemas in 5.11 give ValidationError this[documentIsSelected] is not a function

### ISSUE THREAD

**Issue by Duchynko** [Automattic/mongoose#9800]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm aware of #9449 but seems that the solution doesn't work for nested schemas.

I have an external npm package where I keep my schemas so I can reuse them in multiple projects. From the same schema package, I export a function which I then call from my application.

```ts
// ...schema package
export function exportModels(mongoose: Mongoose) {
  Group = mongoose.model<IGroupDocument, IGroupModel>("group", GroupSchema);
  User = mongoose.model<IUserDocument, IUserModel>("user", UserSchema);
  Game = mongoose.model<IGameDocument, IGameModel>("game", GameSchema);
  Bet = mongoose.model<IBetDocument>("bet", BetSchema);
}

// ...application project
async connect(): Promise<Mongoose> {
  if (!this.db) {
    this.db = await mongoose.connect(this.connectionString, {
      useNewUrlParser: true,
      useFindAndModify: false,
      useUnifiedTopology: true,
      useCreateIndex: true,
    });
  }
  exportModels(this.db);
  // also tried exportModels(mongoose);
  return this.db;
}
```

I'm also using peerDependencies in my schema package
```json
 "devDependencies": {
    "typescript": "^4.1.3"
  },
  "peerDependencies": {
    "mongoose": "^5.11.11"
  }
```

The error I'm getting only complains about nested schemas (same behavior with other models that contain nested schemas)

`ValidationError: game validation failed: homeTeam.name: this[documentIsSelected] is not a function, homeTeam.logo: this[documentIsSelected] is not a function, homeTeam.teamId: this[documentIsSelected] is not a function, homeTeam._version: this[documentIsSelected] is not a function, awayTeam.name: this[documentIsSelected] is not a function, awayTeam.logo: this[documentIsSelected] is not a function, awayTeam.teamId: this[documentIsSelected] is not a function, awayTeam._version: this[documentIsSelected] is not a function, homeTeam: Validation failed: name: this[documentIsSelected] is not a function, logo: this[documentIsSelected] is not a function, teamId: this[documentIsSelected] is not a function, _version: this[documentIsSelected] is not a function, awayTeam: Validation failed: name: this[documentIsSelected] is not a function, logo: this[documentIsSelected] is not a function, teamId: this[documentIsSelected] is not a function, _version: this[documentIsSelected] is not a function`

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
mongoose should parse the schema correctly

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
`mongoose: 5.11.11`
`node: v12.19.0`

**Comment by vkarpov15** [comment]
@Duchynko can you run `npm list | grep "mongo"` and paste the output please?

**Comment by Duchynko** [comment]
@vkarpov15 Sure, that's the output

```
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-plugin-vue@6.2.2
npm ERR!├─┬ connect-mongo@3.2.0
│ └─┬ mongodb@3.6.3
 peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/eslint-plugin@2.34.0
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by @typescript-eslint/parser@2.34.0
npm ERR! peer dep missing: eslint@2.x - 6.x, required by eslint-plugin-import@2.19.1
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-plugin-vue@6.2.2
npm ERR! peer dep missing: eslint@^6.4.0, required by eslint-template-visitor@1.1.0
npm ERR! peer dep missing: eslint@^5.0.0 || ^6.0.0, required by eslint-plugin-vue@6.2.2
├─┬ mongoose@5.11.11
│ ├─┬ @types/mongodb@3.5.33
│ ├── mongodb@3.6.3 deduped
│ ├── mongoose-legacy-pluralize@1.0.2
```

**Comment by Duchynko** [comment]
I deleted `node_modules`, `package-lock.json` and re-installed everything. The problem still persists, and the output from `npm list | grep "mongo"` is now 

```
├─┬ mongodb-memory-server@6.9.3
│ └─┬ mongodb-memory-server-core@6.9.3
│   ├─┬ mongodb@3.6.2
├─┬ mongoose@5.11.11
│ ├─┬ @types/mongodb@3.6.3
│ ├─┬ mongodb@3.6.3
│ ├── mongoose-legacy-pluralize@1.0.2
│ ├── mongoose@5.11.11 extraneous
```

**Comment by Duchynko** [comment]
@vkarpov15 I did some more digging to see where could be a problem. Hope that helps...

After I create a model,  
```typescript
const Game = mongoose.model<IGameDocument, Model<IGameDocument>>("game", GameSchema);
```
I can see that schema contains all its `childSchemas`. I can also see them under `paths` with a type of `SingleNestedPath`.

However, when saving a document I get the validation error.
```ts
const game = new Game(mockGame());
await game.save(); // throws the error
```

```
errors: {
        'homeTeam.name': ValidatorError: this[documentIsSelected] is not a function
            at validate (/Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:1256:13)
            at /Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:1239:7
            at Array.forEach (<anonymous>)
            at SchemaString.Object.<anonymous>.SchemaType.doValidate (/Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:1184:14)
            at /Users/jakubduchon/Source/tipovacka-serverless/node_modules/mongoose/lib/document.js:2502:18
            at processTicksAndRejections (internal/process/task_queues.js:79:11) {
          properties: [Object],
          kind: 'required',
          path: 'name',
          value: 'AC Port Alex',
          reason: TypeError: this[documentIsSelected] is not a function
              at SingleNested.requiredValidator (/Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:956:60)
              at /Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:1219:24
              at Array.forEach (<anonymous>)
              at SchemaString.Object.<anonymous>.SchemaType.doValidate (/Users/jakubduchon/Source/tipovacka-models/node_modules/mongoose/lib/schematype.js:1184:14)
              at /Users/jakubduchon/Source/tipovacka-serverless/node_modules/mongoose/lib/document.js:2502:18
              at processTicksAndRejections (internal/process/task_queues.js:79:11),
          [Symbol(mongoose:validatorError)]: true
        },
... 
```

I see that `documentIsSelected` is of a type Symbol - but I'm not sure at what point there should be a function assignment.
```ts
// schemaType.js 955:13
console.log(documentIsSelected); // -> Symbol(mongoose#Document#isSelected)
// no validation when this path wasn't selected in the query.
if (cachedRequired != null && !this[documentIsSelected](_this.path) && !this[documentIsModified](_this.path)) {
  return true;
}
```

**Comment by vkarpov15** [comment]
It looks like you have an extraneous installation of mongoose: `mongoose@5.11.11 extraneous`. What is the parent of that extraneous mongoose@5.11.11 installation?

**Comment by Duchynko** [comment]
@vkarpov15 It's my external package where I keep schemas

These are dependencies that the schema package has

```json
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.13.0",
    "@typescript-eslint/parser": "^4.13.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint": "^7.17.0",
    "prettier": "^2.2.1",
    "typescript": "^4.1.3"
  },
  "peerDependencies": {
    "mongoose": "^5.11.11"
  },
  "dependencies": {}
```

**Comment by vkarpov15** [comment]
Try `rm -rf ./node_modules/<external-schema-package/node_modules/mongoose`, that should help. For some reason you have two separate copies of Mongoose 5.11.11 installed.

**Comment by Duchynko** [comment]
Alright. I managed to make it work 🤦🏻‍♂️

The problem was that my schema package is local and by installing it with `npm install ../schema-package`, npm created just a symlink. After installing the package from a tgz (using `npm pack`), everything worked even with `mongoose 5.11.11`. https://stackoverflow.com/a/59766644/8475178
