### ISSUE TITLE
5.11.11 breaks Schema and Models typescript definition from @types/mongoose (TS2322: Type .... is not assignable to type '{ aggregate: { <R = any> ….. })

### ISSUE THREAD

**Issue by lmX2015** [Automattic/mongoose#9801]
Hi there!

I am having a trouble with the latest release (5.11.11) typescript types. It broke Model and Schema definition that used to work on 5.11.10 + @types/moongoose package. 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I made a simplified version of the Model I am using. Our project  also contains more complex one with inheritance, abstraction etc.

https://gist.github.com/lmX2015/b5483ba958d45b3e93178181b6ff8f5b

```
import mongoose, { Document, Model, Schema } from 'mongoose';

const modelName = 'Test';

const TestSchema = new Schema({
  content: String,
  // any type of content
});

export interface TestDocument extends Document {
  content: string
}

export interface TestModel extends Model<TestDocument> {
  // static methods types declaration
  StaticMethod: ()=>void
}

TestSchema.statics = {
  // static methods implementation
  StaticMethod: () => {
    console.log('hello world');
  }
};

export default mongoose.model(modelName, TestSchema);
```

Upgrading from 5.11.10 to 5.11.11 breaks models definition. From what I understand, 5.11.11 includes its own type definition for typescript so the use of @types/mongoose is no longer required. However the types seems to be incompatible and after the upgrade I got the following error:

`TS2322: Type '{ StaticMethod: () => void; }' is not assignable to type '{ aggregate: { <R = any>(pipeline?: any[]): Aggregate<R[]>; <R = any>(pipeline: any[], cb: Function): Promise<R[]>; }; base: typeof import("mongoose"); baseModelName: string; ... 62 more ...; eventNames: () => (string | symbol)[]; } & { ...; }'.   Type '{ StaticMethod: () => void; }' is missing the following properties from type '{ aggregate: { <R = any>(pipeline?: any[]): Aggregate<R[]>; <R = any>(pipeline: any[], cb: Function): Promise<R[]>; }; base: typeof import("mongoose"); baseModelName: string; ... 62 more ...; eventNames: () => (string | symbol)[]; }': aggregate, base, baseModelName, bulkWrite, and 62 more.`

It seems that both the static methods definition and the class inheritance are now causing issues with the Schema Type.

We might be wrong in the way of defining classes for mongoose models and documents (specially on the latest release) but it is quite hard to find typescript documentation or information about the intended way of defining these classes in mongoose.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above, for the tsconfig.json I used:
```
{
  "compilerOptions": {
    "strict": true,
    "module": "commonjs",
    "jsx": "preserve",
    "esModuleInterop": true,
    "sourceMap": true,
    "allowJs": true,
    "lib": [
      "es6",
      "dom"
    ],
    "rootDir": "src",
    "moduleResolution": "node"
  }
}
```

And here is a Sandbox example (you can change the mongoose dependencies from 5.11.11 to 5.11.10 to see the difference):
https://codesandbox.io/s/mongoose-typescript-bug-y6j17?file=/src/index.ts

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- node: tested on 13.7.0 
- Mongoose: working on 5.11.10, problem on 5.11.11
- MongoDB, not necessary here, this is just a compilation problem

**Comment by lmX2015** [comment]
Ok, after digging a bit the implementation of the `Schema` class in both packages, it seems that "statics" property has the type "any" in @types/mongoose and "{ [F in keyof M]: M[F] }" where M extends Model in mongoose 5.11.11. Thus the "statics" object of the Schema should implement all the default static functions in mongoose 5.11.11 while it only need to implement the model specific static functions in @types/mongoose (as in the Vanilla JS). I don't know if it is the intended behavior but here is a working version of the above code:

**Comment by stalniy** [comment]
+1 mongoose@5.11 introduces a breaking change by providing official types. All projects before used `@types/mongoose` which are different. mongoose@5.11 and @types/mongoose fail to compile.

Related issue in casl repo: https://github.com/stalniy/casl/issues/436

**Comment by stalniy** [comment]
This is because TypeScript merges official mongoose types and `@types/mongoose` provided ones. There is no way to override official types, and there is [an open TS issue](https://github.com/microsoft/TypeScript/issues/36146) to add such behavior

**Comment by vsalil** [comment]
I still face same problem. statics method is not working 5.11.12 as well

**Comment by lmX2015** [comment]
Thank for the fix! @vsalil the sandbox example with statics method is working on 5.11.12. Do you have an example of what's not working on your side?

**Comment by vkarpov15** [comment]
@vsalil please open a new issue and follow the issue template. "Me too" posts on closed issues are considered spam.
