### ISSUE TITLE
Definitions again

### ISSUE THREAD

**Issue by UncleVic** [Automattic/mongoose#9815]
Can you replace `<any>` by `<T>` in line 1166?

```
  type SchemaDefinitionProperty<T = undefined> = SchemaTypeOptions<any> | Function | string | Schema | Schema[] | Array<SchemaTypeOptions<any>> | Function[] | SchemaDefinition<T> | SchemaDefinition<T>[];
 ```

Thanks

**Comment by vkarpov15** [comment]
Can't quite do that because it breaks a lot of tests, but we'll use `T` if it isn't `undefined`

**Comment by UncleVic** [comment]
Not important How, but important there is not <any>

Thanx

**Comment by UncleVic** [comment]
But I don't understand why so hard construction.
Why you don't want use `<T = any>`?
