### ISSUE TITLE
[types] Express references in new types

### ISSUE THREAD

**Issue by hasezoey** [Automattic/mongoose#9818]
**Do you want to request a *feature* or report a *bug*?**
question / help

Is there an way to express references in mongoose's new types while being type-complete?  

Something like what typegoose can do with the old types [as can be seen here](https://github.com/typegoose/typegoose/blob/12e24f0a79609c27c58c30060e3110551b844e58/src/types.ts#L316-L323)

i had trouble upgrading these types to the new mongoose types (from 5.10.18 to 5.11.x)

**Comment by vkarpov15** [comment]
It should be possible, I'll look into this

**Comment by vkarpov15** [comment]
I named the type `PopulatedDoc` to avoid potential conflicts with Typegoose, but kept the type pretty much identical :+1:
