### ISSUE TITLE
Model.create() doesn't work with discriminators

### ISSUE THREAD

**Issue by Edmund1645** [Automattic/mongoose#9821]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
specifying the discriminator key as stated on the doc [here] (https://mongoosejs.com/docs/discriminators.html#using-discriminators-with-model-create) does not work

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const mongoose = require('mongoose')
const base = new mongoose.Schema({
 url: String
}, { discriminatorKey: 'post_type' })

mongoose.model('post', base)

const imagePost = new mongoose.Schema({})

base.discriminator('image', imagePost, 'image' )


const post = await base.create({
  url: 'https://example.com',
  post_type: 'image'
})

console.log(post)
```
After running use the code snippet above to create a new document from the base model, the created document does not have the discriminator key on it.

**What is the expected behavior?**
The result of logging the newly created post document should look something like this:

```js
{
  "_id": "ObjectId()",
  "url": "https://example.com",
  "post_type": "image"
}
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
* Node version: 14.15.4
* Mongoose version: 5.11.12

**Extra notes**
From the first code snippet above, If I had used the discriminator `imagePost` to create the new document, the created document would automatically have the `post_type` key.

**Comment by IslandRhythms** [comment]
```
'use strict';
const mongoose = require('mongoose');
mongoose.set('useFindAndModify', false);
const { Schema } = mongoose;
run().catch(err => console.log(err));
async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  await mongoose.connection.dropDatabase();
  // Code here
  const base = new mongoose.Schema({
    url: String
   }, { discriminatorKey: 'post_type' });
   
  const Test = mongoose.model('post', base);
   
   const imagePost = new mongoose.Schema({});
   
   Test.discriminator('image', imagePost, 'image' );
   

  const post = await Test.create({
           url: 'https://example.com',
           post_type: 'image'
         });
   
   
   console.log(post);
}
```

**Comment by Edmund1645** [comment]
Hello @IslandRhythms thanks for picking this up, I'll set up a demo repository to clone and test with.

**Comment by Edmund1645** [comment]
Hello @IslandRhythms in the process of creating a repo to reproduce this issue, I discovered that everything did work as expected, I had to go look at my code well and I noticed that I'd been passing a value that didn't exist all this while as the discriminator key's value.
