### ISSUE TITLE
populate docs don't mention toObject when dealing with virtuals

### ISSUE THREAD

**Issue by jly36963** [Automattic/mongoose#9822]
This is a request for an update in the documentation:

I used virtuals in my models, but populate wasn't working as expected. It started working when I added
`toObject: { virtuals: true }`
to my schemas.

This [page](https://mongoosejs.com/docs/populate.html#populate-virtuals) does not mention the `toObject` property, and I feel like that's a crucial bit of information for those using virtuals.

**Comment by vkarpov15** [comment]
Worth adding that since we already discuss `toJSON`, which is similar.
