### ISSUE TITLE
`await Model.find({}).exec()` hangs after subsequent calls, but `await Model.find({})` always works

### ISSUE THREAD

**Issue by gnarea** [Automattic/mongoose#9825]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have a server-side app where I call `await Model.find({}).exec()` to get all the documents (only 2 records), and it works the first time, but that statement hangs in subsequent calls. If [I remove the `.exec()`](https://github.com/relaycorp/relaynet-internet-gateway/commit/f2ed7e585162158701a7a90d25013c2545be5291), it works every time.

**If the current behavior is a bug, please provide the steps to reproduce.**

For some reason, this doesn't happen locally or in CI (where I run lots of functional tests). It only happens in production (GCP + MongoDB Atlas).

So reproducing this is difficult because you'd probably need to set up MongoDB Atlas, but once that's in place, you'd just need to create a collection with some records and call `await Model.find({}).exec()`. Here's an example:

https://github.com/relaycorp/relaynet-internet-gateway/blob/933b80bb0681b1848ae04888c74f234431e62145/src/services/certs.ts#L14-L18

In case it's relevant, I'm using:

- Node.js 12.14
- Mongoose 5.10.18
- Typegoose 7.4.7
- MongoDB 4.2.11 (on MongoDB Atlas).
- MongoDB connection URL params: `retryWrites=true&w=majority`

Finally, `bufferCommands` true or false doesn't make any difference.

**What is the expected behavior?**

`.exec.()` not to hang. I want to use `.exec()` because, [according to the docs](https://mongoosejs.com/docs/promises.html#should-you-use-exec-with-await?), simply calling `.find()` would give me unhelpful stack traces.

**Comment by vkarpov15** [comment]
The below script works as expected, modulo our omitted Atlas connection string. Please modify the below script to demonstrate your issue:

```javascript
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  const uri = 'mongodb+srv://OMITTED:OMITTED@cluster0.OMITTED.mongodb.net/test?retryWrites=true&w=majority';
  await mongoose.connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  
  const Model = mongoose.model('Test', Schema({ name: String }));
    
  let res = await Model.find({}).exec();
  res = await Model.find({}).exec();
  
  console.log('Done');
} 
```

Another alternative would be to decrease your `serverSelectionTimeoutMS` in `mongoose.connect()`:

```javascript
await mongoose.connect(uri, { useNewUrlParser: true, useUnifiedTopology: true, serverSelectionTimeoutMS: 3000 });
```

The issue you're seeing may just be that you got disconnected from Atlas for some reason, and Mongoose is stuck trying to reconnect for 30 seconds before reporting an error. Reducing `serverSelectionTimeoutMS` would help surface the error faster.
