### ISSUE TITLE
Cannot connect to a replica set using 5.11.12

### ISSUE THREAD

**Issue by MihaiPerju** [Automattic/mongoose#9836]
I am running my own MongoDb Replica Set on Kubernetes.

It has 3 members, I exposed them all via NodePort.

**I can connect to it via shell:**

(feel free to connect, it's an empty, isolated example that will be destroyed)

```
mongo mongodb://stackoverflow:practice@134.122.99.184:31064,134.122.99.184:31086,134.122.99.184:32754/thirty3?authSource=admin
```

**However, I cannot connect to it via mongoose 5.11.12 using the same connection string.**
**It only works until mongoose 4.5.8**

```
mongoose.connect("mongodb://stackoverflow:practice@134.122.99.184:31064,134.122.99.184:31086,134.122.99.184:32754/thirty3?authSource=admin&replicaSet=thirty3&?retryWrites=true&w=majority",
    {
      useNewUrlParser: true,
      poolSize: 5,
      useUnifiedTopology: true,
      serverSelectionTimeoutMS: 5000, // Timeout after 5s instead of 30s
    })
```
I tried tons of configurations, `gssapiServiceName=mongodb`, `replicaSetName=thirty3` (I checked the replica set name by running `rs.conf()` ) and many more other configurations.

**My question is - is there something wrong with mongoose handling these types of communications?**

_I have found similar issues that indicate downgrading as a solution, but downgrading is not ideal unless impossible to fix it normally._

Please try the code samples above, the database is open for connections with the credentials exposed.

**Comment by vkarpov15** [comment]
My best guess is that this is a [host name issue](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). I'll look into this some more, but I think that's the issue since the individual MongoDB servers think their hostname is something like `thirty3-0.thirty3-svc.mongodb.svc.cluster.local:27017` rather than `134.122.99.184:32754`

**Comment by MihaiPerju** [comment]
@vkarpov15  thank you for your response. 

That is a good point. I investigated it a lot since per their [docs](https://docs.mongodb.com/kubernetes-operator/master/tutorial/deploy-replica-set/) they say to provide `replicaSetHorizons`, in a following way:

```
security:
    tls:
      enabled: true
  connectivity:
    replicaSetHorizons:
      - "example-website": "web1.example.com:30907"
      - "example-website": "web2.example.com:32350"
      - "example-website": "web3.example.com:31185"
```

Now, I do have the external ports, I do have the IP, but it is not clear what specifically is the `example-website` and `web[X].example.com` needed to be replaced with. 

I was curious since `mongo` shell command worked fine, so was the `mongoose 4.5.8`.

**Comment by hungtcs** [comment]
I may have encountered the same problem, v5.10.9 is working for me, but v5.11.14 I can not connect to my single node replica set.

**Comment by jooeycheng** [comment]
@MihaiPerju Can you try appending `?directConnection=true` to the Mongo URI?

**Comment by lucashpmelo** [comment]
@jooeycheng `?directConnection=true` This works for me. Thank you!

mongoose v5.11.13

**Comment by vkarpov15** [comment]
I'm going to close this one since it looks like the servers are no longer available. As far as I can tell, this is an issue with [replica set host names](https://mongoosejs.com/docs/connections.html#replicaset-hostnames), you need to make sure that the host names in `rs.conf()` are the same ones as the ones in your connection string.
