### ISSUE TITLE
Different ValidationError JSON.stringify for mongoose@^5.9.16

### ISSUE THREAD

**Issue by hanzki** [Automattic/mongoose#9847]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`ValidationError.toJSON()` does not include the `name` property. This is in contrast with the behaviour of `ValidatorError.toJSON()` which does include the `name` property.

This error was reported previously in https://github.com/Automattic/mongoose/issues/9296 but the fix addressed the issue only partially. `ValidationError.name` is still omitted from JSON and this is causing breaking changes in error handling code which used to rely on the `name` property.

**If the current behavior is a bug, please provide the steps to reproduce.**

The bug can be reproduced with same script as in #9296. I've only changed the log lines at the end.

```js
'use strict';

const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({
    name: { type: String, required: true },
    numAddresses: { type: Number, min: 1 }
  }));

  const doc = new Model({ numAddresses: 0 });

  const err = await doc.validate().catch(err => err);
  console.log(err.name); // ValidationError
  console.log(err.errors['name'].name); // ValidatorError
  console.log(err.errors['numAddresses'].name); // ValidatorError
  console.log(JSON.stringify(err)); // ValidatorErrors have name field but ValidationError does not
}
``` 

**What is the expected behavior?**

Calling `JSON.stringify()` on `ValidationError` object should produce JSON string that includes the `name` field. This is inline with the behaviour of mongoose prior to 5.9.16. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

* Node.js: v14.9.0
* Mongoose: 5.11.13
* MongoDB: 4.2.2

**Comment by vkarpov15** [comment]
Fixed by #9849
