### ISSUE TITLE
Mongoose User.create is not a function

### ISSUE THREAD

**Issue by Architk25** [Automattic/mongoose#9848]
# Mongoose User.create is not a function

## **This is reported because it is a:**
Bug
## **The error and code:**
```
Model.create is not a function
Go to http://localhost:4040/inspect/http or http://localhost:4040/status to view stuff
D:\Code\Web\Node.js\Meow2\server.js:139
const response = await User.create({
                                            ^
TypeError: User.create is not a function
    at D:\Code\Web\Node.js\Meow2\server.js:139:31`

```

While my Schema is: 
```
const mongoose = require('mongoose')

mongoose.set('toObject', { useProjection: true });
mongoose.set('toJSON', { useProjection: true });

const UserSchema = new mongoose.Schema({
		username: { type: String, required: true, unique: true },
		password: { type: String, required: true }
	},
	{ collection: 'users' }
)

const model = mongoose.model('UserSchema', UserSchema)

module.exports = { model }
```

## **Instead, It should work like:**
UserSchema.create is defined already!
## **I'm using:**
Mongoose version 5.10.10 and node version 15.5.0

**Comment by sos10e** [comment]
Did you import the model correctly? and create a User using a new key word.
example:
`const user=new User({username: '..' , password: '...'})
await user.save()`

**Comment by vkarpov15** [comment]
Try `model.exports = model` instead of ` = { model }`, I suspect you're importing the model incorrectly.

**Comment by Architk25** [comment]
Wait, I changed the code, I removed the import of the user.js because it was causing a data leak and it works now! @vkarpov15
