### ISSUE TITLE
updating deeply nested schema

### ISSUE THREAD

**Issue by alexzabo85** [Automattic/mongoose#9852]
Hello, 
I'm trying to update a deeply embedded subdocument. 
The main document named '_product_' with a field named '_filters_' which is an array of subdocuments. 
Each filter in '_filters_' has yet another array of subdocuments called '_stages_'.

I use findOneAndUpdate() which finds the '_product_' document and my update object is: 

`update = {
  $set: {
    'filters.0.stages.1.value': 150
  }
}`

I'm trying to reach filters[0].stages[1].value 

I couldn't find any solution/example for such a situation (and I've read Mastering-Mongoose and other books). Is it even possible? and is it recommended/good-practice to keep such an embedded subdocument schema?

BTW I receive no error from mongoose by doing so.

Thanks in advance,
Alex

**Comment by dbronin** [comment]
I tried to reproduce your problem, but the findOneAndUpdate works perfectly with your syntax when used from a mongo shell. This is using mongoDB 3.6.21

**Comment by alexzabo85** [comment]
Thank you very much. 

I found the issue on my side (not related to Mongoose)
