### ISSUE TITLE
The 'error' event is being emitted before the connection has been established

### ISSUE THREAD

**Issue by samislam** [Automattic/mongoose#9853]
It's mentioned here is the docs:
[Error Handling](https://mongoosejs.com/docs/connections.html#error-handling)
that the 'error' event will be emitted **after** the initial connection has been established.
What's happening instead is that it's being occurred before (and not sure if also after) the initial connection has been established.

This leads to a problem when you want to handle both errors, before and after an error has occurred, in my case, an error message is getting printed twice to the console.

```
try{
  // say for example that mongod server is not started, 
  mongoose.connection.on('error', ()=>console.log("There was an error 1"))
}
catch(error){
   console.log("There was an error 2")
}
```

The output is:
```
There was an error 1
There was an error 2
```

**Comment by vkarpov15** [comment]
The docs don't indicate that 'error' only fires after initial connection, as written they currently say "If initial connection fails, Mongoose will not attempt to reconnect, it will emit an 'error' event, and the promise mongoose.connect() returns will reject.". We will make it more clear that Mongoose may emit 'error' in both cases.
