### ISSUE TITLE
Feature: Add forAll for cursor queries 

### ISSUE THREAD

**Issue by khaledosama999** [Automattic/mongoose#9861]
**Do you want to request a *feature* or report a *bug*?**
Feature

### Feature Description

For cursor queries (that return the data in batches) currently there is a method `forEach` which is used to loop over **each** document returned from the query **not** each batch. it would be nice to loop over **each batch** so you can perform a bulk action on each batch.

### Use Case
You want to send an email to all users currently in your system obviously you will fetch the whole user collection in batches. But it's not very efficient  to send each user an email one at a time that wouldn't be very cost effective plus any mail service has a limit on the max number of bulk emails that could be sent (1000 for example). So the ideal situation would be to fetch the users in batches of 1000 and for  **each batch**  perform a bulk action of sending an email to all those users.

I can make the PR myself but I will wait for the issue approval

**Comment by vkarpov15** [comment]
I have a few issues with this. First, finding a good name: `batchSize` already means something else. Second, it isn't particularly difficult to do this with eachAsync:

```javascript
let batch = [];
const batchSize = 1000;

await Users.find().eachAsync(async function(user) {
  batch.push(user);
  if (batch.length >= batchSize) {
    await sendEmailToUsers(batch);
    batch = [];
  }
});
```

**Comment by khaledosama999** [comment]
That's exactly what I did to solve it :D, but for me here's why I think it would be nice to have it as part of mongoose: 

- From a functional programming point of view the function passed to `eachAsync` is impure since it depends on the `batch` array, so it could introduce all kinds of weird behavior if the user is not careful when it comes to the usage of the batch array outside of the function passed to `eachAsync` .
- Although the solution might seem easy I don't think it will occur to everybody especially  beginners, but if mongoose has a built in function and it's mentioned in the docs that would make it a lot easier.

- And lastly this seems more readable to me : 
```js
await Users
.find()
.batchSize(1000)
.eachBatch(async function (batch) {
await sendEmailToUsers(batch);
});
```

**Comment by khaledosama999** [comment]
@vkarpov15

**Comment by vkarpov15** [comment]
I think a `batchSize` option to `eachAsync()` would work if you're willing to put in a PR :+1:

**Comment by khaledosama999** [comment]
@vkarpov15  Done I don't know exactly how you manage features but the feature branch was based on branch 6.0 and the PR is  on branch 6.0 also I didn't want to come near the master branch as I'm assuming this is the branch used for the latest mongoose version
