### ISSUE TITLE
SchemaDefinitionProperty doesn't work with `number` type

### ISSUE THREAD

**Issue by devagrawal09** [Automattic/mongoose#9863]
**Do you want to request a *feature* or report a *bug*?**
Bug (typescript)
**What is the current behavior?**
Sample code:
```ts
import { Document, Schema, SchemaDefinition } from "mongoose";

interface IProfile { age: number; }

interface ProfileDoc extends Document, IProfile {}

const ProfileSchemaDef: SchemaDefinition<IProfile> = { age: Number };

export const ProfileSchema = new Schema<ProfileDoc>(ProfileSchemaDef);
```
The last line gives me these errors:
```
Argument of type '{ age: SchemaDefinitionProperty<number>; }' is not assignable to parameter of type '{ [path: string]: SchemaDefinitionProperty<undefined>; }'.
  Property 'age' is incompatible with index signature.
    Type 'SchemaDefinitionProperty<number>' is not assignable to type 'SchemaDefinitionProperty<undefined>'.
      Type 'number' is not assignable to type 'SchemaDefinitionProperty<undefined>'.
```
Error goes away if I change the interface definition to
```ts
interface IProfile { age: Number; }
```
But [tslint's recommended rules](https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts) include banning the usage of the `Number` type.

**If the current behavior is a bug, please provide the steps to reproduce.**

Code provided above

```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "lib":["ES2020"],
    "allowJs": true,
    "outDir": "build",
    "rootDir": ".",
    "sourceMap": true,

    "moduleResolution": "node",
    "baseUrl": "./src",
    "esModuleInterop": true,

    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    
    "preserveConstEnums": true,
    "resolveJsonModule": true,
    "pretty": true,
  },
  "include": ["src", "test"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```
**What is the expected behavior?**
The interface can be defined with `number` type and typescript does not throw errors.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v12.15.0, mongoose v5.11.11

**Comment by vkarpov15** [comment]
One potential workaround is to just get rid of the generic param to `SchemaDefinition`: `const ProfileSchemaDef: SchemaDefinition = { age: Number };` . We took a closer look at this and it seems like the best way to get this to work correctly is by adding a 3rd generic param to `Schema` that helps with typechecking your schema definition as suggested in #9789

**Comment by vkarpov15** [comment]
You'll have to do this to help Mongoose infer the type of `age` re: #9789:

```javascript
import { Document, Schema, SchemaDefinition, Model } from "mongoose";

interface IProfile { age: number; }

interface ProfileDoc extends Document, IProfile {}

const ProfileSchemaDef: SchemaDefinition<IProfile> = { age: Number };

export const ProfileSchema = new Schema<ProfileDoc, Model<ProfileDoc>, ProfileDoc>(ProfileSchemaDef);
```
