### ISSUE TITLE
ObjectId.isValid("JGL-24423/TL") returns true even thought its not a objectId

### ISSUE THREAD

**Issue by leoncydsilva** [Automattic/mongoose#9867]
**ObjectId.isValid("JGL-24423/TL") is returning true. It should have returned false**

**Steps to Reporduce
const mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;
console.log(ObjectId.isValid("JGL-24423/TL"));**

**From my understanding any 12 byte string is valid objectId is there a way to avoid this?**

**Comment by vkarpov15** [comment]
Sure, `/0-9a-f/i.test(str)` if you want to make sure a string is a 24 byte hex string. But any 12 byte string is technically a valid objectid.
