### ISSUE TITLE
Connecting with autoEncryption causes repeated connection and disconnection. 

### ISSUE THREAD

**Issue by cor1** [Automattic/mongoose#9883]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When connecting with autoEncryption in options to use FLE, mongoose connects and disconnects repeatedly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Connect to a mongo 4.4.3 instance with the autoEncryption option set, something such as 

`{
                useUnifiedTopology: true,
                useNewUrlParser: true,
                autoIndex: false,
                useCreateIndex: true,
                autoEncryption: {
                    keyVaultNamespace,
                    kmsProviders,
                    schemaMap,
                },
            }`

This exact setup worked with mongo 4.2 just fine. 

**What is the expected behavior?**
Previously when connecting to mongo version 4.2 everything worked as expected, it would connect and not lose the connection. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 13.5, Mongoose 5.11.14, mongodb driver 3.6.3, mongodb 4.4.3

**Comment by vkarpov15** [comment]
Is there some sort of error message you get? Also, is mongocryptd running and are you using mongocryptd v4.4.3? The below script from #8167 as expected for me with MongoDB 4.4.3:

```javascript
'use strict';

const Encrypt = require('mongodb-client-encryption');
const base64 = require('uuid-base64');
const mongoose = require('mongoose');

run().catch(err => console.log(err));

async function run() {
  /* Step 1: Connect to MongoDB using autoEncryption */

  // Create a very basic key. You're responsible for making
  // your key secure, don't use this in prod :)
  const arr = [];
  for (let i = 0; i < 96; ++i) {
    arr.push(i);
  }
  const key = Buffer.from(arr);

  const keyVaultNamespace = 'client.encryption';
  const kmsProviders = { local: { key } };
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    // Configure auto encryption
    autoEncryption: {
      keyVaultNamespace, 
      kmsProviders
    }
  });

  /* Step 2: create a key and configure encryption using JSONschema */

  // Currently, mongodb-client-encryption exports a constructor
  // that takes an instance of the mongodb module as a parameter
  const { ClientEncryption } = Encrypt;
  const encryption = new ClientEncryption(mongoose.connection.client, {
      keyVaultNamespace,
      kmsProviders,
    });

  const _key = await encryption.createDataKey('local');

    // CSFLE is defined through JSON schema. Easiest way to set
  // a JSON schema on your collection is via `createCollection()`
  await mongoose.connection.dropCollection('tests').catch(() => {});
  await mongoose.connection.createCollection('tests', {
    validator: {
      $jsonSchema: {
        bsonType: 'object',
        properties: {
          // Automatically encrypt the 'name' property
          name: {
            encrypt: {
              bsonType: 'string',
              keyId: [_key],
              algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic' }
          }
        }
      }
    }
  });

 /* Step 3: Create a Mongoose model that uses the encrypted collection and see encryption in action */

  // 'super secret' will be stored as 'BinData' in the database,
  // if you query using the `mongo` shell.
  const Model = mongoose.model('Test', mongoose.Schema({ name: String }));
  await Model.create({ name: 'super secret' });

  console.log('Done');
}
                            
```

**Comment by cor1** [comment]
@vkarpov15 , I do not get any error messages other than it disconnecting and reconnecting repeatedly. The only thing I can think of thats different between your script and mine is that I fetch my keys from AWS KMS. I wonder if there is some underlying issue with that. I will keep investigating.

**Comment by cor1** [comment]
@vkarpov15 It appears that my app still functions correctly and when I look at the logs to the mongocryptd the connection is maintained. however in the event handlers 

    mongoose.connection.on('connected', () => console.log(`Connected`));
    mongoose.connection.on('disconnected', () => console.log('Disconnected'));

the logs are thrown repeatedly. Are you able to get consistent results with these event handlers? Im not super worried now that it appears it doesnt actually drop the connection.

**Comment by scriste-sv** [comment]
This behaviour comes from the MongoDB Node driver, and I updated a ticket in MongoDB JIRA system with the details. 
https://jira.mongodb.org/browse/NODE-3133
Hopefully they will put a fix in soon.

**Comment by cor1** [comment]
@scriste-sv Thank you for the update, I was starting to suspect the node driver, glad I wasnt crazy.

**Comment by IslandRhythms** [comment]
@vkarpov15 seems to be an issue with the drivers. I think we can close this issue.

**Comment by thismehmood** [comment]
import { Binary, ClientEncryption, MongoClient, ObjectId } from 'mongodb';
import { encryptData, decryptData } from './gcpKmsClient';
import * as crypto from 'crypto';

const uri = process.env.MONGODB_URI;
const client = new MongoClient(uri);

export class KeyVaultService {
  private keyVaultNamespace = 'encryption.keyVault';

  constructor() {
    client.connect();
  }

  async createDataEncryptionKey(): Promise<ObjectId> {
    const keyVault = client.db('encryption').collection(this.keyVaultNamespace);

    const dek = crypto.randomBytes(32);
    const encryptedDek = await encryptData(process.env.GCP_KEY_NAME, dek);

    const keyDocument = {
      _id: new ObjectId(),
      keyMaterial: encryptedDek,
      creationDate: new Date(),
    };

    await keyVault.insertOne(keyDocument);
    return keyDocument._id;
  }

  async getDataEncryptionKey(keyId: string): Promise<Buffer> {
    const keyVault = client.db('encryption').collection(this.keyVaultNamespace);
    const keyDocument = await keyVault.findOne({ _id: new ObjectId(keyId) });
    if (!keyDocument) {
      throw new Error('Key not found');
    }
    const dek = await decryptData(process.env.GCP_KEY_NAME, keyDocument.keyMaterial);
    return Buffer.from(dek, 'base64');
  }

  async encryptField(dek: Buffer, field: any): Promise<Binary> {
    const encryption = new ClientEncryption(client, {
      keyVaultNamespace: this.keyVaultNamespace,
      kmsProviders: {
        gcp: {
          email: process.env.GCP_SERVICE_ACCOUNT_EMAIL,
          privateKey: process.env.GCP_SERVICE_ACCOUNT_PRIVATE_KEY,
        },
      },
    });

    const encryptedField = await encryption.encrypt(field, {
      keyId: new Binary(dek, Binary.SUBTYPE_BYTE_ARRAY),
      algorithm: 'AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic',
    });

    return encryptedField;
  }
}


here is my code I'm trying to CSFLE using GCP kms, and we have microservices runing on docker environment so     "mongodb-client-encryption": "^6.1.1", is already present in package.json and node_modules as well.
but when i run the docker environment i still got the issue on my terminal.

patient-1       | [11:52:12.204] ERROR (50): Optional module `mongodb-client-encryption` not found. Please install it to use auto encryption or ClientEncryption. {"context":"RpcExceptionsHandler"}
patient-1       |     err: {
patient-1       |       "type": "Error",
patient-1       |       "message": "Optional module `mongodb-client-encryption` not found. Please install it to use auto encryption or ClientEncryption.",
patient-1       |       "stack":
patient-1       |           MongoMissingDependencyError: Optional module `mongodb-client-encryption` not found. Please install it to use auto encryption or ClientEncryption.
patient-1       |               at getMongoDBClientEncryption (/usr/src/app/node_modules/.pnpm/mongodb@6.13.1_mongodb-client-encryption@6.2.0_socks@2.8.4/node_modules/mongodb/src/deps.ts:279:26)
patient-1       |               at Function.getMongoCrypt (/usr/src/app/node_modules/.pnpm/mongodb@6.13.1_mongodb-client-encryption@6.2.0_socks@2.8.4/node_modules/mongodb/src/client-side-encryption/client_encryption.ts:86:50)
patient-1       |               at ClientEncryption (/usr/src/app/node_modules/.pnpm/mongodb@6.13.1_mongodb-client-encryption@6.2.0_socks@2.8.4/node_modules/mongodb/src/client-side-encryption/client_encryption.ts:143:41)
patient-1       |               at KeyVaultService.encryptField (/usr/src/app/dist/apps/patient/main.js:5904:28)
patient-1       |               at PatientService.addMedicalHistory (/usr/src/app/dist/apps/patient/main.js:1532:48)
patient-1       |               at async /usr/src/app/node_modules/.pnpm/@nestjs+microservices@10.4.15_@grpc+grpc-js@1.12.6_@nestjs+common@11.0.10_class-transformer@0_wf7kzsnxi4ek5cejwuautyv53q/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
patient-1       |               at async ServerTCP.handleMessage (/usr/src/app/node_modules/.pnpm/@nestjs+microservices@10.4.15_@grpc+grpc-js@1.12.6_@nestjs+common@11.0.10_class-transformer@0_wf7kzsnxi4ek5cejwuautyv53q/node_modules/@nestjs/microservices/server/server-tcp.js:67:54)
patient-1       |     }
