### ISSUE TITLE
Pre-remove hooks not called for subdocuments

### ISSUE THREAD

**Issue by TimUnderhay** [Automattic/mongoose#9885]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Pre-remove middleware is not called when removing an item from an array of subdocuments.  According to https://github.com/Automattic/mongoose/issues/6224, this seemed to work with Mongoose <5.0.0.  @vkarpov15 asked @georgehess to open a new issue on this in the same https://github.com/Automattic/mongoose/issues/6224, though it appears not to have happened, thus I'm running it up the flagpole.

This behaviour presents a problem for me because I need to know when a document is removed from an array, so that a corresponding cache entry can be deleted.  Unfortunately, modifiedPaths doesn't provide enough context to tell me when something is removed, only that something happened.  I can, of course, clear the cache entry manually from outside of my Mongoose code, but this seems like a less-than-elegant solution.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const mongoose = require('mongoose');

const SubSchema = mongoose.Schema({
  myValue: {
    type: String
  }
}, {});

SubSchema.pre('remove', async function() {
  console.log('Subdoc got removed!')
});



const Schema = mongoose.Schema({
  foo: {
    type: String,
    required: true
  },
  mySubdoc: {
    type: [SubSchema],
    required: true
  }
}, {minimize: false, collection: 'test'});

const Model = mongoose.model('TestModel', Schema);


const initMongoose = async () => {
  const mongooseUrl = `mongodb://user:pass@dbhost:27017/test`;
  try {
    await mongoose.connect(mongooseUrl, {
      useUnifiedTopology: true,
      useNewUrlParser: true,
      promiseLibrary: global.Promise,
      useFindAndModify: false
    });
  }
  catch (err) {
    console.error(err);
    process.exit(1);
  }
  console.log('Connected');
};


const test = async () => {
  await Model.deleteMany({}); // remove all existing documents
  const newModel = {
    foo: 'bar',
    mySubdoc: [{myValue: 'some value'}]
  };
  const document = await Model.create(newModel);
  console.log('Created document');
  console.log('document:', document);
  
  console.log('Removing subDocument');
  document.mySubdoc[0].remove();
  
  
  console.log('Saving document');
  await document.save().catch( (error) => {
    console.error(error);
    process.exit(1);
  });
  console.log('document:', document);

  console.log(`Notice that SubSchema.pre('remove') never ran`);
};



const main = async () => {
  await initMongoose();
  await test();
  process.exit(0);
};

main();
```

Output from the above is:
```
Connected
Created document
document: {
  _id: 601831bcddc22e01c640d6b6,
  foo: 'bar',
  mySubdoc: [ { _id: 601831bcddc22e01c640d6b7, myValue: 'some value' } ],
  __v: 0
}
Removing subDocument
Saving document
document: { _id: 601831bcddc22e01c640d6b6, foo: 'bar', mySubdoc: [], __v: 1 }
Notice that SubSchema.pre('remove') never ran
```

**What is the expected behavior?**
Pre-remove hooks should run when removing sub-documents.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose 5.11.14
Node.js 15.5.1
MongoDB 4.4.1

**Comment by georgehess** [comment]
@TimUnderhay appreciate you opening this ticket. Did it ever work for you? I finally upgraded to v8.2 and still can't get pre/post middleware to fire for subdocuments when they are deleted.

**Comment by TimUnderhay** [comment]
@georgehess IIRC the issue was resolved (though much time has passed so my memory is a bit fuzzy) but I’m no longer using Mongoose so I can’t comment on whether that’s still the case.

**Comment by vkarpov15** [comment]
@georgehess [`remove()` is no longer supported as of Mongoose 7](https://mongoosejs.com/docs/migrating_to_7.html#removed-remove), so there's no more `remove` hooks either

**Comment by georgehess** [comment]
@vkarpov15 looks like the supplied alternative (deleteOne) works with pre middleware. Post middleware doesn’t work but I guess that’s a whole other topic.

**Comment by vkarpov15** [comment]
@georgehess can you please provide code samples that clarify what you mean by "Post middleware doesn’t work but I guess that’s a whole other topic."?

**Comment by georgehess** [comment]
@vkarpov15 here's a [mongoose playground example](https://playground.mongoosejs.io/#YXdhaXQgbW9uZ29vc2UuY29ubmVjdCgnbW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9tb25nb29zZV90ZXN0Jyk7CmNvbnN0IENoaWxkU2NoZW1hID0gbmV3IG1vbmdvb3NlLlNjaGVtYSh7IG5hbWU6IFN0cmluZyB9KTsKQ2hpbGRTY2hlbWEucHJlKCJzYXZlIiwgZnVuY3Rpb24obmV4dCkgewogIGNvbnNvbGUubG9nKCJwcmUgc2F2ZSBtaWRkbGV3YXJlIHdvcmtzIiwgdGhpcy5uYW1lKTsKICBuZXh0KCk7Cn0pOwpDaGlsZFNjaGVtYS5wb3N0KCJzYXZlIiwgZnVuY3Rpb24oc3ViZG9jLCBuZXh0KSB7CiAgY29uc29sZS5sb2coInBvc3Qgc2F2ZSBtaWRkbGV3YXJlIHdvcmtzIiwgc3ViZG9jLm5hbWUpOwogIG5leHQoKTsKfSk7CkNoaWxkU2NoZW1hLnByZSgiZGVsZXRlT25lIiwgeyBkb2N1bWVudDogdHJ1ZSwgcXVlcnk6IGZhbHNlIH0sIGZ1bmN0aW9uKG5leHQpIHsKICBjb25zb2xlLmxvZygicHJlIGRlbGV0ZU9uZSBtaWRkbGV3YXJlIHdvcmtzIiwgdGhpcy5uYW1lKTsKICBuZXh0KCk7Cn0pOwpDaGlsZFNjaGVtYS5wb3N0KCJkZWxldGVPbmUiLCB7IGRvY3VtZW50OiB0cnVlLCBxdWVyeTogZmFsc2UgfSwgZnVuY3Rpb24oc3ViZG9jLCBuZXh0KSB7CiAgLy8gdGhpcyBuZXZlciBydW5zCiAgY29uc29sZS5sb2coInBvc3QgZGVsZXRlT25lIG1pZGRsZXdhcmUgd29ya3MiLCBzdWJkb2MubmFtZSk7CiAgbmV4dCgpOwp9KTsKY29uc3QgUGFyZW50U2NoZW1hID0gbmV3IG1vbmdvb3NlLlNjaGVtYSh7IG5hbWU6IFN0cmluZywgY2hpbGRyZW46IFtDaGlsZFNjaGVtYV0gfSk7CmNvbnN0IFBhcmVudE1vZGVsID0gbW9uZ29vc2UubW9kZWwoJ1BhcmVudCcsIFBhcmVudFNjaGVtYSk7Cgpjb25zdCBkb2MgPSBuZXcgUGFyZW50TW9kZWwoeyBuYW1lOiAnUGFyZW50JyB9KTsKY29uc29sZS5sb2coJ1NhdmluZyBQYXJlbnQnKTsKYXdhaXQgZG9jLnNhdmUoKTsKZG9jLmNoaWxkcmVuLnB1c2goeyBuYW1lOiAnQ2hpbGQgMScgfSk7CmRvYy5jaGlsZHJlbi5wdXNoKHsgbmFtZTogJ0NoaWxkIDInIH0pOwpkb2MuY2hpbGRyZW4ucHVzaCh7IG5hbWU6ICdDaGlsZCAzJyB9KTsKY29uc29sZS5sb2coJ1NhdmluZyBDaGlsZHJlbicpOwphd2FpdCBkb2Muc2F2ZSgpOwpjb25zdCBjaGlsZDIgPSBkb2MuY2hpbGRyZW5bMV07CmNvbnNvbGUubG9nKCdEZWxldGluZyBDaGlsZCAyJyk7CmNoaWxkMi5kZWxldGVPbmUoKTsKYXdhaXQgZG9jLnNhdmUoKTsK) of what I mean. The pre deleteOne middleware for subdocuments runs as expected but post deleteOne never does.
