### ISSUE TITLE
Unhandled Promise Rejection Warning: Mongoose Server Selection Error 

### ISSUE THREAD

**Issue by krishnadevz** [Automattic/mongoose#9894]
**UnhandledPromiseRejectionWarning: MongooseServerSelectionError Bug*?**

**What is the current behavior?**
* hello there I am trying to connect mongoose with URL string included everything is fine but after console.log("mongoDB database connection established successfully") this is not showing this console's text but an error is coming there 
![Screenshot from 2021-02-03 14-54-33](https://user-images.githubusercontent.com/42638797/106726189-1c0cdb00-6630-11eb-8bac-4874aa91031f.png)

```js
const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");
require("dotenv").config();
const app = express();
const port = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const uri = process.env.ATLAS_URI;
mongoose.connect(uri,{useNewUrlParser:true,useCreateIndex:true,useUnifiedTopology:true} 
    );
const connection = mongoose.connection;
connection.once('open',() =>{
console.log("mongoDB database connection established successfully");
})
app.listen(port, () => {
  console.log(`server is running on port ${port}`);
});
```
**server.js file code above and in .env the URI key is given**

**What is the expected behavior?**
* the expected output is MongoDB database connection established successfully.

**What are the versions of Node.js, Mongoose, and MongoDB you are using? Note that "latest" is not a version.**
* "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "mongoose": "^5.11.14",

**Comment by deistermatheus** [comment]
@krishnadevz , a few things that might help people troubleshoot your issue:

1 - Does the shell connect successfully from your system or is the issue specific to the node app?
2 - Can you post the connection string format you are using in your env config? ex: the connection string format that you have
copied and pasted from MongoDB Atlas in the Connect option
3 - Have you double checked if your ip is whitelisted in the Atlas Network Access settings?  Dynamic IPs are a usual source of connection problems in dev setups
4 - Consider adding a  .catch block to mongoose.connect, to log the reason why the connection Promise was rejected and see if it complains about something in your Uri: 

```js
mongoose.connect(uri ,connectionOptions).catch(console.error); 
  ```

It looks like a malformed uri that the mongodriver cannot parse and use to connect,

**Comment by krishnadevz** [comment]
> @krishnadevz , a few things that might help people troubleshoot your issue:
> 
> 1 - Does the shell connect successfully from your system or is the issue specific to the node app?
> 2 - Can you post the connection string format you are using in your env config? ex: the connection string format that you have
> copied and pasted from MongoDB Atlas in the Connect option
> 3 - Have you double checked if your ip is whitelisted in the Atlas Network Access settings? Dynamic IPs are a usual source of connection problems in dev setups
> 4 - Consider adding a .catch block to mongoose.connect, to log the reason why the connection Promise was rejected and see if it complains about something in your Uri:
> 
> ```js
> mongoose.connect(uri ,connectionOptions).catch(console.error); 
> ```
> 
> It looks like a malformed uri that the mongodriver cannot parse and use to connect, but I can't tell exactly why from the info you posted

now the problem is solved but one rejection warning is coming there  connection string is below
`ATLAS_URI=mongodb+srv://krishna:pass*@cluster0.ec6pf.mongodb.net/dbname?retryWrites=true&w=majority`
and also I allowed IP's 
and the warning is like this now 
```js
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
server is running on port 5000
Database Connected bro
(node:81503) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connection <monitor> to 34.234.233.64:27017 closed
    at NativeConnection.Connection.openUri (/home/krishnadevz/excercise/node_modules/mongoose/lib/connection.js:845:32)
    at _mongoose._promiseOrCallback.cb (/home/krishnadevz/excercise/node_modules/mongoose/lib/index.js:345:10)
    at Promise (/home/krishnadevz/excercise/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/krishnadevz/excercise/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/home/krishnadevz/excercise/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/home/krishnadevz/excercise/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/home/krishnadevz/excercise/backend/server.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:81503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vkarpov15** [comment]
@krishnadevz can you please answer question 1? "Does the shell connect successfully from your system or is the issue specific to the node app?"

**Comment by krishnadevz** [comment]
> @krishnadevz can you please answer question 1? "Does the shell connect successfully from your system or is the issue specific to the node app?"

yes shell is connected successfully 
![Screenshot from 2021-02-18 11-13-05](https://user-images.githubusercontent.com/42638797/108311033-68344f80-71da-11eb-9a82-1a6c635cbe4f.png)

**Comment by vkarpov15** [comment]
I'm able to run the below script without error. Realistically, this looks like a connectivity issue that we aren't going to be able to repro.

```javascript
const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");
const app = express();
const port = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const uri = 'mongodb+srv://val:a1b2c3@cluster0.xvnqv.mongodb.net/myFirstDatabase?retryWrites=true&w=majority';
mongoose.connect(uri,{useNewUrlParser:true,useCreateIndex:true,useUnifiedTopology:true}
    );
const connection = mongoose.connection;
connection.once('open',() =>{
console.log("mongoDB database connection established successfully");
})
app.listen(port, () => {
  console.log(`server is running on port ${port}`);
});
```

Also, you didn't answer the question. When I ask "Does the shell connect successfully?", I mean the [mongo shell](https://docs.mongodb.com/manual/mongo/), not your terminal.

**Comment by krishnadevz** [comment]
the issue is resolved now

**Comment by prince3898** [comment]
> the issue is resolved now

How you got it resolved bro? can you tell once
