### ISSUE TITLE
[BUG] When stopping the mongodb daemon and hitting any request the request hangs infinitely.

### ISSUE THREAD

**Issue by satyam-dev** [Automattic/mongoose#9903]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When stopping the mongodb daemon(mimicking db connection drop)  and hitting any request which interacts with db, the request hangs infinitely.

**If the current behavior is a bug, please provide the steps to reproduce.**

Steps:

1. Start mongodb daemon
2. Start node server
3. Hit any request which interacts with db(works as expected)
4. Stop mongodb daemon
5. Hit any request which interacts with db(hangs infinitely and does not timeout after 30secs as default)

Dependencies and its versions:
```
“dependencies”: {
“bcrypt”: “^5.0.0”,
“config”: “^3.3.3”,
“express”: “^4.16.2”,
“fawn”: “^2.1.5”,
“joi”: “^13.1.0”,
“joi-objectid”: “^3.0.1”,
“jsonwebtoken”: “^8.5.1”,
“lodash”: “^4.17.20”,
“mongoose”: “^5.11.7”
}
```

**What is the expected behavior?**
The request should timeout after 30sec(default) when database connection drops. 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJs: `14.15.1`
Mongoose: `^5.11.7`
MongoDB: `4.4.1`

**Comment by satyam-dev** [comment]
**IMPORTANT NOTE: The above issue does not replicates for mongoose `v5.0.2` and same versions of Node and MongoDB**

**Comment by IslandRhythms** [comment]
```

mongoose.connect("mongodb://localhost:27017/test", { useNewUrlParser: true, useUnifiedTopology: true });
const data = mongoose.connection;
data.on("open", function () {
    data.db.dropDatabase(console.log('database drop'));
});
data.on('disconnected', () => {
    console.log('disconnected');
});
data.on('disconnecting', () => {
    console.log('disconnecting');
});
data.on('connecting', () => {
    console.log('connecting');
});
data.on('connected', () => {
  console.log('Hi')
});

const userSchema = new mongoose.Schema({
    email: {
      type: String,
      unique: true // `email` must be unique
    }
  },{timestamps: true});
  const User = mongoose.model('User', userSchema);

  async function test() {
    console.log(await User.create({email: 'test@google.com'}));
    console.log(await User.findOneAndReplace({email:'test@google.com'},{email: 'test2@google.com'}, {new:true, overwrite: true, upsert: true, rawResult:true}));
    // await mongoose.disconnect();
  }
  async function test2() {
    console.log('test2');
    console.log(await User.create({email: 'frank@google.com'}));
  }


  test();
  setTimeout(function() {
    test2();
  }, 35000);

```
Error message is delivered after 30 seconds
