### ISSUE TITLE
FindOne, all Fields greater than 0

### ISSUE THREAD

**Issue by Maeggi** [Automattic/mongoose#9905]
Hi @ll,

How can I find all fields, greater than 0?

Find one Field, greater then 0
> db.inventory.find( { field1: { $gt: 0 } } )

I'm looking for:
> db.inventory.find( { ALLFIELDS: { $gt: 0 } } )

Structur Example:
> {
>      "field1": 1,
>      "field2": 1,
>      "field3": 0,
>      "field4": 1,
>      etc ... 
> }

Thanks

**Comment by IslandRhythms** [comment]
If I'm reading this correctly, I think just calling find() without any parameters will get you what you want.

**Comment by vkarpov15** [comment]
You would need to do a `$or` like `$or: [{ field1: { $gt: 0 } }, { field2: { $gt: 0 } }, ...]`
