### ISSUE TITLE
MongoError: Cannot create field '-1' in element when using deeply nested arrays and defaults

### ISSUE THREAD

**Issue by mcat95** [Automattic/mongoose#9910]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**
When fetching and saving a document with deeply nested arrays and default values, saving the document returns the error:
'MongoError: Cannot create field '-1' in element'

**If the current behavior is a bug, please provide the steps to reproduce.**

I made a gist with the most simplistic repro code I could fund:
https://gist.github.com/mcat95/2a9ed42c3ee06fbecdbfa7e1294e87d9

As you can see, It fails on the Model#save call, just after fetching the document. It seems like the default option in the schema calls markModified on the subdocument, which inserts incorrect paths in the modifiedPaths array.

**What is the expected behavior?**

It should save the document without errors

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
nodejs: 14.12.0
mongoose: 5.11.15
mongodb: 4.4.3

**Comment by mcat95** [comment]
I just noticed #9909 was created while I was writing my issue, which describe a similar problem.

I'm not sure how related they are since it states the bug doesn't happen on 5.8.7, which is not the case of my issue. I tested with 5.8.7 and can also get the error

**Comment by IslandRhythms** [comment]
#9909

**Comment by vkarpov15** [comment]
I'm going to close this in favor of #9909
