### ISSUE TITLE
[BUG] Problem with updating fields that have Mixed type.

### ISSUE THREAD

**Issue by ap0h** [Automattic/mongoose#9915]
Mongoose Version: 5.11.7
Workflow for reproducing bug:
1. You create some schema with some property that has type Mixed and model with that schema (let's say that is UserModel and property sharetribeUser: Type.Mixed )
2. Create a UserModel as new UserModel({id:'123', sharetribeUser: {someAtr: 'someValue'}).save()
3. const user = await findOne({ id: '123'})
4. user.sharetribeUser.newattribute = 'something else'
5. user.save()
In database newattribute is not saved,but it should be.

Only works if I use update with $set.

**Comment by sahasayan** [comment]
try this

``` js
user.sharetribeUser = {
    ...user.sharetribeUse,
    newattribute: 'something else'
}

user.save()
```

**Comment by ap0h** [comment]
I tried everything and nothing works

**Comment by mcat95** [comment]
You need to do `user.markModified(sharetribeUser)` so mongoose knows it has changed, since it can't autodetect changes on Mixed types.

https://mongoosejs.com/docs/schematypes.html#mixed

**Comment by ap0h** [comment]
Thank you so sorry for bothering, I should have read the docs first.
