### ISSUE TITLE
[Bug] retainNullValues param default value not working or subdocuments with match return null

### ISSUE THREAD

**Issue by Kapumas** [Automattic/mongoose#9918]
Mongoose version: 5.11.14
**Do you want to request a *feature* or report a *bug*?**
I think is a bug with retainNullValues
**What is the current behavior?**
I have 2 Schemes with a relation between them, User and Company.

This is the User scheme

```js
const mongoose = require("mongoose");
const User = mongoose.Schema({
  first_name: { type: String },
  last_name: { type: String },
  website: { type: String },
  username: { type: String, required: true, unique: true, index: true },
  email: { type: String, index: true },
  removed: { type: Boolean, default: false },
});
module.exports = mongoose.model("User", User);
```

This is the Company scheme

```js
const Company = mongoose.Schema({
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  uid: { type: String, index: true, unique: true, required: true },
  name: { type: String, index: true, unique: true, required: true },
  bio: { type: String },
  description: { type: String },
  link: { type: String, default: "" },
  removed: { type: Boolean, default: false },
});

module.exports = mongoose.model("Company", Company);

```

I have a logic delete with `removed` field in my schemes, so I can remove an user setting `removed: true`.

**If the current behavior is a bug, please provide the steps to reproduce.**
I need to find Companies with not removed owners, ( `removed: false` ), so this is my query:

```js
Company.find({ removed: false }).populate({
  path: "owner",
  select: "username first_name last_name ",
  match: { removed: false },
});
```

The result is

```json
[
  {
    "owner": null,
    "uid": "companytest1",
    "name": "Company test",
    "bio": "This is a test",
    "description": "This is a test",
    "link": "https://test.com"
  }
]
```

**What is the expected behavior?**
Reading documentation it says that retainNullValues field on populate options params is false by default, so i understand find query shouldn't return `null` values in subdocument populate

i've tried with retainNullValues (true and false) both inside and outside of `options` key and it doesn't work

```js
Company.find({ removed: false }).populate({
  path: "owner",
  select: "username first_name last_name ",
  match: { removed: false },
  options: {
        retainNullValues: false,
  }
});
```

**PSDT**
I've tried too logging `populateOptions` params in [`assignVals.js`](https://github.com/Automattic/mongoose/blob/425f35a45ce02297efd4463b022a25510686aaf7/lib/helpers/populate/assignVals.js#L204) file, line 204 and it never runs this function

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node version: v14.13.1
Mongoose version: v5.11.14
MongoDB version: v4.4.1

**Comment by german970814** [comment]
Same issue! `retainNullValues` is not working properly on `v5.11.14`

**Comment by vkarpov15** [comment]
I took a closer look and it looks like you're misunderstanding the purpose of `retainNullValues`. `retainNullValues` makes Mongoose skip cases where the local field is an array that contains null or undefined. For example:

```javascript
const companySchema = new Schema({ people: [{ type: ObjectId, ref: 'Person' }] });
const CompanyModel = mongoose.model('Company', companySchema);

const doc = new CompanyModel({ people: [new ObjectId('0'.repeat(24)), null, new ObjectId('1'.repeat(24)] });
```

Without `retainNullValues`, Mongoose would strip out the `null` in the above `people` array when populating.

`retainNullValues` doesn't do anything when the local field isn't null or undefined, but [no foreign doc is found](https://mongoosejs.com/docs/populate.html#doc-not-found).

**Comment by Kapumas** [comment]
> I took a closer look and it looks like you're misunderstanding the purpose of `retainNullValues`. `retainNullValues` makes Mongoose skip cases where the local field is an array that contains null or undefined. For example:
> 
> ```js
> const companySchema = new Schema({ people: [{ type: ObjectId, ref: 'Person' }] });
> const CompanyModel = mongoose.model('Company', companySchema);
> 
> const doc = new CompanyModel({ people: [new ObjectId('0'.repeat(24)), null, new ObjectId('1'.repeat(24)] });
> ```
> 
> Without `retainNullValues`, Mongoose would strip out the `null` in the above `people` array when populating.
> 
> `retainNullValues` doesn't do anything when the local field isn't null or undefined, but [no foreign doc is found](https://mongoosejs.com/docs/populate.html#doc-not-found).

So, How I can filter documents by populate match query? i'd like to do that in Mongo Query Level and not implement javascript functions to do that.

**Comment by vkarpov15** [comment]
You can't, which is why we recommend denormalizing fields you want to query by: https://thecodebarbarian.com/mongoose-schema-design-pattern-store-what-you-query-for.html
