### ISSUE TITLE
Connection.prototype.transaction() return value

### ISSUE THREAD

**Issue by kulakovAngel** [Automattic/mongoose#9919]
Mongoose version: 5.10.11.
Node.js version: 12.16.3.
MongoDB vresion: 4.4.3 (cloud.mongodb Atlas)

_Do you want to request a feature or report a bug?_
I think is a bug with **_Connection.prototype.transaction() return value_**

_What is the current behavior?_
This method returns a "CommandResult" instance, but not the value returned by the "fn" callback 

```javascript
const t = await require('mongoose')
  .connection
  .transaction(async session => {

    const newServices = await Service
      .create(services, {
        session
      });

    if (!newServices || !newServices.length) throw new Error('It\'s impossible to create new services');
    return await newVisit.save({
      session
    });
  });

console.log('transaction: ', t); // CommandResult { result: { ok: 1, ...} ... }
```

This example can be simplified to primitive, but the result is the same:
```javascript
const t = await require('mongoose')
  .connection
  .transaction(async session => {

    await SomeModel.save({ session });
    
    return 1;
  });

console.log('transaction: ', t); // CommandResult { result: { ok: 1, ...} ... }
```

_What is the expected behavior?_
As [described in the documentation](https://mongoosejs.com/docs/api.html#connection_Connection-transaction), the method **_Connection.prototype.transaction()_** must return a promise that resolves to the value returned by the **_fn_** callback. In my example, for simplicity, **_"1"_** the number.

> **Returns:**
> - _&#xAB;Promise&#x3C;Any&#x3E;&#xBB;_ promise that resolves to the returned value of fn

I expect something like the following:
```javascript
const t = await require('mongoose')
  .connection
  .transaction(async session => {

    await SomeModel.save({ session });
    
    return 1;
  });

console.log('transaction: ', t); // based on the documentation it should be "1"
```

**Comment by vkarpov15** [comment]
Unfortunately this is a mistake in our docs. The MongoDB driver's `withTransaction()` function doesn't return the [resolved value of the promise](https://masteringjs.io/tutorials/fundamentals/then) that the `transaction()` callback returns. So Mongoose can't support this unless we redo the MongoDB driver's connection handling. Sorry for the confusion :+1:

**Comment by kulakovAngel** [comment]
I got it, thanks.
