### ISSUE TITLE
.sort breaks pagination / infiniscroll

### ISSUE THREAD

**Issue by Glutch** [Automattic/mongoose#9922]
Hey! So i've implemented infiniscroll and my query looks like this
```js
const posts = await Seed.find({status: 'APPROVED', 'color.name': color})
      .skip(parseInt(skip) || 0)
      .limit(8)
      .exec()
```

**That works great, from 0 to the end of posts.** However if i add .sort({upvotes: -1})

```js
const posts = await Seed.find({status: 'APPROVED', 'color.name': color})
    .sort({upvotes: -1})
    .skip(parseInt(skip) || 0)
    .limit(8)
    .exec()
```

Everything goes nuts, i can get the same post 6 times.

I've stared at this for an hour now and i cannot understand why this is happening and it feels like a bug.
If anyone can help me figure this out i would be very thankful

**Comment by Glutch** [comment]
Apparently if "upvotes" are full of 1's, mongodb randomizes the order. wow, i would never have guessed thats how it worked.

Solution
```.sort({upvotes: 'desc', _id: -1 })```

**Comment by vkarpov15** [comment]
MongoDB doesn't strictly guarantee order if two posts have the same value for `upvotes` and you do `.sort({upvotes: -1})`.
