### ISSUE TITLE
Question: Do you use the native $lookup for populate() or just execute multiple queries?

### ISSUE THREAD

**Issue by awesomelike** [Automattic/mongoose#9925]
In the docs, it is written that `populate()` is _**more powerful**_ than `$lookup`. How do you make it more powerful? 
Do you use the native `$lookup` under the hood or just execute multiple queries?

**Comment by vkarpov15** [comment]
Execute multiple queries. That means `populate()` isn't limited by sharding restrictions and you can `populate()` documents that are on an entirely separate cluster.
