### ISSUE TITLE
Document<T = any> in index.d.ts breaks schema.create()

### ISSUE THREAD

**Issue by nnari** [Automattic/mongoose#9928]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently, Object.create() doesn't provide type completion except for the _id field.
Previously Document was set a `class Document`, now it is `class Document<T = any>`
The change happened in this commit https://github.com/Automattic/mongoose/blob/aef25e09d54d272f14c93cbfa01d0986105e41ef/index.d.ts#L369

Last working version I tried this was with 5.11.7

**If the current behavior is a bug, please provide the steps to reproduce.**

Install 5.11.16, try to use `schema.create()`, types will be missing.

```
{
    "compilerOptions": {
        "allowJs": false,
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es5",
        "noImplicitAny": true,
        "skipLibCheck": true,
        "resolveJsonModule": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "@typeDefs/*": [
                "../shared/*"
            ],
        }
    },
    "include": [
        "src/**/*"
    ],
    "references": [
        {
            "path": "../shared"
        }
    ]
}
```
**What is the expected behavior?**
Editor provides types

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v15.8.0, Mongoose 5.11.16, no database registered.

**Comment by LukasGerm** [comment]
The last version which works for me is 5.11.9. The version 5.11.10 or later is not working anymore.

**Comment by nnari** [comment]
``` typescript
import mongoose, { Mongoose } from "mongoose";

interface IUserModel {
  password: string;
  username: string;
}

// TODO Update reference to organization
const UserSchema = new mongoose.Schema({
    username: { type: String, required: true },
    password: { type: String, required: true }
});
const UserModel = mongoose.model<IUserModel & mongoose.Document>(
  "User",
  UserSchema
);

export default UserModel;
```
Using this as the schema
![image](https://user-images.githubusercontent.com/7150217/107859447-25712100-6e42-11eb-9894-8d7662170ffe.png)
Example of autocompletion not working
