### ISSUE TITLE
[Fixed] Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.11.16)

### ISSUE THREAD

**Issue by SurgicalCrow** [Automattic/mongoose#9931]
**I am using the latest version, i even tried to re install the npm package as well, and it says the version is 5.11.16 in package.json as well, still I get this logged in my console when I restart the bot**

``` 2|rg  | Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.11.16)```

alongside, this as well

```(node:13241) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.```

**And any Database related discord bot commands are not working  or replying after 1 minutes I mean a lot laggyy/taking too much time to respond**

My index.js file for my database is here: 

```const mongoose = require("mongoose");

console.log("Connecting to MongoDB...");
mongoose.connect(
  "mongodb+srv://user:pass@cluster0-cy1zr.gcp.mongodb.net/royale",
  { useNewUrlParser: true, useUnifiedTopology: true, useFindAndModify: false, useCreateIndex: true, autoIndex: false },
  err => {
    if (err) {
      console.error(err);
      process.exit(0);
    } else {
      console.log("Connected to MongoDB!!");
    }
  }
);
```

**Comment by ghtali** [comment]
You may downgrade to mongoose 5.11.15, but it is not a big deal, it is just a warning.

npm uninstall mongoose --save
npm i mongoose@5.11.15

**Comment by vkarpov15** [comment]
"Using Unsupported mongoose version, highest supported is 5.10.18" looks like an issue with Typegoose. Just downgrade to v5.10.18.
