### ISSUE TITLE
broken compatibility with latest @types/mongodb

### ISSUE THREAD

**Issue by syffs** [Automattic/mongoose#9939]
**Do you want to request a *feature* or report a *bug*?**
BUG mongoose@5.11.16 with @types/mongodb@3.6.7

**What is the current behavior?**
```
src/loaders/mongoose.ts:25:5 - error TS2322: Type 'import("node_modules/mongoose/node_modules/@types/mongodb/index").Db' is not assignable to type 'import("node_modules/@types/mongodb/index").Db'.
  Types of property 'collection' are incompatible.
    Type '{ <TSchema = any>(name: string, callback?: import("node_modules/mongoose/node_modules/@types/mongodb/index").MongoCallback<import("node_modules/mongoose/node_modules/@types/mongodb/index").Collection<TSchema>>):...' is not assignable to type '{ <TSchema = any>(name: string, callback?: import("node_modules/@types/mongodb/index").MongoCallback<import("node_modules/@types/mongodb/index").Collection<TSchema>>): import("node_modules...'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'result' and 'result' are incompatible.
          Type 'import("node_modules/mongoose/node_modules/@types/mongodb/index").Collection<any>' is not assignable to type 'import("node_modules/@types/mongodb/index").Collection<any>'.
            Types of property 'aggregate' are incompatible.
              Type '{ <T = any>(callback: import("node_modules/mongoose/node_modules/@types/mongodb/index").MongoCallback<import("node_modules/mongoose/node_modules/@types/mongodb/index").AggregationCursor<T>>): import("/mnt/c/dev/...' is not assignable to type '{ <T = any>(callback: import("node_modules/@types/mongodb/index").MongoCallback<import("node_modules/@types/mongodb/index").AggregationCursor<T>>): import("node_modules...'.
                Types of parameters 'callback' and 'callback' are incompatible.
                  Types of parameters 'result' and 'result' are incompatible.
                    Type 'import("node_modules/mongoose/node_modules/@types/mongodb/index").AggregationCursor<any>' is not assignable to type 'import("node_modules/@types/mongodb/index").AggregationCursor<any>'.
                      The types returned by 'group(...).addCursorFlag(...).project(...)[Symbol.asyncIterator]()' are incompatible between these types.
                        Type 'AsyncIterableIterator<U>' is not assignable to type 'AsyncIterableIterator<U>'. Two different types with this name exist, but they are unrelated.
                          Type 'U' is not assignable to type 'U'. Two different types with this name exist, but they are unrelated.
                            'U' could be instantiated with an arbitrary type which could be unrelated to 'U'.
```
reverting to @types/mongodb@3.6.3 does work

**If the current behavior is a bug, please provide the steps to reproduce.**
use mongoose@5.11.16 with @types/mongodb@3.6.7 and use mongodb.Db type in typescript

**What is the expected behavior?**
no typescript error

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose@5.11.16
node@14.15.5
typescript@4.1.5

**Comment by vkarpov15** [comment]
I'm unable to repro this locally, but based on the error message it looks like you have two versions of `@types/mongodb` installed: one at `node_modules/mongoose/node_modules/@types/mongodb` and one at `node_modules/@types/mongodb/index`. Make sure those two are the same version: it's likely that your `package-lock.json` is enforcing `@types/mongodb@3.6.3` for Mongoose.

**Comment by syffs** [comment]
@vkarpov15 that's correct i face this issue when i have 2 versions for `@types/mongodb` (one in my package.json and one which seems to be enforced by mongoose). 

Now, this does imply that mongoose has a broken compatibility with latest `@types/mongodb`:  `@types/mongodb@3.6.8` is the same minor version, so I don't see a reason why `@types/mongodb@3.6.3` is enforced and causing this kind of TS error.

am I missing something ?

**Comment by syffs** [comment]
I guess this is somehow related to #9900 and [mongodb native drive](https://github.com/mongodb/node-mongodb-native) and 3.6.5 not released yet

**Comment by vkarpov15** [comment]
Take a look at your lockfile and make sure all instances of `@types/mongodb` have the exact same version.

**Comment by syffs** [comment]
latest `5.12.x` version no longer has the issue
