### ISSUE TITLE
&gt; on doc page but jsdoc seems ok

### ISSUE THREAD

**Issue by moander** [Automattic/mongoose#9940]
There seems to be a problem with [this line](https://github.com/Automattic/mongoose/blob/0c19536f9bc57a14000dca0d8ef3d6709c57e5f7/lib/schematype.js#L1002
) 
```
 *     postSchema.path('user').ref(() => User); // Or a function that returns the model class
```

On the [doc page](https://mongoosejs.com/docs/api/schematype.html#schematype_SchemaType-ref) (v5.11.16) I see `&gt;`
![image](https://user-images.githubusercontent.com/380191/107985332-2e8cfa00-6fca-11eb-9f92-d617bf675f7b.png)

**Comment by vkarpov15** [comment]
Fix will be released with v5.11.18, thanks for reporting :+1:
