### ISSUE TITLE
Types of props inside schema consutructor not working

### ISSUE THREAD

**Issue by ahmednaser94** [Automattic/mongoose#9942]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/39867467/108117315-6ae15880-70a5-11eb-976f-f4ff9e2b3751.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
After updating to the last version and removed `@types/mongoose` to depend on current version types when i create a schema types not autocomplete like the picture below, when i reviewd generic types of schema i found out that, the third generic type which is `SchemaDefinitionType ` = undefined by default!

![image](https://user-images.githubusercontent.com/39867467/108117837-26a28800-70a6-11eb-83cf-47b21a51c5a1.png)

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/39867467/108117503-a67c2280-70a5-11eb-9072-0a66fc5324ca.png)

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```json
 "typescript": "^4.1.5",
 "mongodb": "^3.6.4",
 "mongoose": "^5.11.16",
```

**Comment by vkarpov15** [comment]
What IDE are you using?

**Comment by ahmednaser94** [comment]
@vkarpov15 VSCode

**Comment by ShadiestGoat** [comment]
@vkarpov15 @ahmednaser94 this is fixed in 5.11.17!

**Comment by ahmednaser94** [comment]
> @vkarpov15 @ahmednaser94 this is fixed in 5.11.17!

I will test it and give you a feedback

**Comment by ahmednaser94** [comment]
@ShadiestGoat

The issue is not fixed in 5.77.17, with VSCode 1.53.2

**Comment by ShadiestGoat** [comment]
@ahmednaser94 
```ts
new Schema<InterfaceYouWant & Document, Model<InterfaceYouWant & Document>, InterfaceYouWant> {}
```
Most certainly is for me

**Comment by ahmednaser94** [comment]
@ShadiestGoat

I tried to pass the interface as a third parameter and it works now, thanks
