### ISSUE TITLE
Occasional error: "MongoNetworkTimeoutError: connection timed out" When Using useUnifiedTopology On AWS Lambda

### ISSUE THREAD

**Issue by michaelgutierrez0** [Automattic/mongoose#9943]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Occasionally my team's code throws an error:
```
error: MongoNetworkTimeoutError: connection timed out    at connectionFailureError (/opt/nodejs/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:342:14)    at TLSSocket.<anonymous> (/opt/nodejs/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connect.js:310:16)    at Object.onceWrapper (events.js:420:28)    at TLSSocket.emit (events.js:314:20)    at TLSSocket.EventEmitter.emit (domain.js:483:12)    at TLSSocket.Socket._onTimeout (net.js:483:8)    at listOnTimeout (internal/timers.js:554:17)    at processTimers (internal/timers.js:497:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

A Lambda function is awaiting the below code:
```
const waitForSecret = require("./waitForSecret");
var mongoose = require("mongoose");

const mongooseConnect = async () => {
    try {
        const secret = await waitForSecret(`mongodb/${process.env.stage}/mongodbconnectionstring`);

        const options = {
            useNewUrlParser: true, // Avoid deprecation warning
            useUnifiedTopology: true, // Avoid deprecation warning
            useCreateIndex: true, // False by default. Set to true to make Mongoose's default index build use createIndex() instead of ensureIndex() to avoid deprecation warnings from the MongoDB driver.
            autoIndex: true, // We want indexes to be build
            poolSize: 10, // Maintain up to 10 socket connections, default is 5
            serverSelectionTimeoutMS: 5000, // Keep trying to send operations for 5 seconds
            socketTimeoutMS: 300000, // Close sockets after 5 minutes of inactivity
        };
        console.log("Connecting to mongoose")
        mongoose.connect(secret.MongoDBConnectionString, options);
        console.log("Connected to mongoose")
        return "Success"
    } catch (error) {
        console.log("failed to connect to mongoDB")
        throw("Mongoose connection failed", error)
    }
};

module.exports = mongooseConnect; 
```
This is not an issue with whitelisting of IPs in atlas as we have whitelisted our entire VPC. This is just asking why useUnifiedTopology is not sending retry requests. 

**What is the expected behavior?**
I am aware that connection issues happen and cannot be avoided. What I would expect to see is some retrys occurring before this timeout message. I have the serverSelectionTimoutMS set to 5 seconds and I would expect it to retry every five seconds but instead it crashes with this error.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS: 12.X
MongoDB:3.6.4
mongoose: 5.11.15

**Comment by vkarpov15** [comment]
I took a closer look and the stack trace indicates that the initial connection `mongoose.connect()` is what's throwing this error. Based on the stack trace and your code, Mongoose isn't getting to your operations. And it looks like the [MongoDB Node driver doesn't retry initial connection if the socket times out](https://github.com/mongodb/node-mongodb-native/blob/d8784d19d6da9b7e2b7929b0a33e7e4db7a95c6c/lib/core/connection/connect.js#L302-L312). Here's a couple ideas to try:

1) Try using [`await`](https://masteringjs.io/tutorials/fundamentals/async-await): `await mongoose.connect()`. 

2) It doesn't look like you're using [Mongoose's recommended Lambda pattern](https://mongoosejs.com/docs/lambda.html), maybe that would help?

3) Could `waitForSecret()` be returning a malformed URL?

**Comment by sajithneyo** [comment]
@vkarpov15 What's the proper way of connecting in a lambda when unifiedTopology is true. Because I saw when unifiedTopology is enabled maxBufferEntries and bufferEntries does not work.

**Comment by vkarpov15** [comment]
With `useUnifiedTopology = true`, `bufferCommands` still works. And `bufferMaxEntries` is unnecessary with `useUnifiedTopology`, so you can just remove it.

**Comment by lucholafrazia** [comment]
Did you guys solve this error? I'm facing the same issue
