### ISSUE TITLE
Version upgrade breaks schema type definitions

### ISSUE THREAD

**Issue by devagrawal09** [Automattic/mongoose#9945]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I upgraded recently from 5.11.11 to 5.11.14 and my code failed at the typescript compilation step. Rolling back to 5.11.11 fixed the issue.
**If the current behavior is a bug, please provide the steps to reproduce.**

The following code compiles fine
```ts
interface Test {
  checked: string;
}
const TestSchemaDef: SchemaDefinition<Test> = {
  checked: String
};
```
But when I change SchemaDef to:
```ts
const TestSchemaDef: SchemaDefinition<Test> = {
  checked: { type: String }
};
```
Typescript fails with the following error
```
Type '{ type: StringConstructor; }' is not assignable to type 'SchemaDefinitionProperty<string>'.
  Types of property 'type' are incompatible.
    Type 'StringConstructor' is not assignable to type 'string'.
```

**Possible cause**
I noticed in 5.11.14, the following type definition
```ts
type SchemaDefinitionProperty<T = undefined> = SchemaTypeOptions<any> | ...
```
was changed to 
```ts
type SchemaDefinitionProperty<T = undefined> = SchemaTypeOptions<T> | ...
```
While this is the expected definition, the issue arises here:
```ts
interface SchemaTypeOptions<T> {
    type?: T;
```
where for a property with type `string`, the schema definition is actually expecting `type` to be a **string value** instead of the `String` class.
**What is the expected behavior?**
Both versions of schema definitions compile without errors.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v14, mongoose v5.11.14

**Comment by ShadiestGoat** [comment]
Im pretty sure 5.11.15 fixes this

**Comment by vkarpov15** [comment]
This was fixed in v5.11.17 with #9911, I can confirm the below script fails with Mongoose v5.11.16 but compiles successfully with Mongoose v5.11.17:

```typescript
import { SchemaDefinition } from 'mongoose';

interface Test {
  checked: string;
}
const TestSchemaDef: SchemaDefinition<Test> = {
  checked: { type: String }
};

```

**Comment by devagrawal09** [comment]
This works fine for string and number, but still breaks for boolean. The following code
```ts
interface Test {
  checked: boolean;
}
const TestSchemaDef: SchemaDefinition<Test> = {
  checked: { type: Boolean }
};
```
does not compile on 5.11.18.
Should I open a new issue for this?

**Comment by vkarpov15** [comment]
@devagrawal09 yes, please open a new issue for this.
