### ISSUE TITLE
Allow discriminatorValue option to discriminate existing collections without updating them

### ISSUE THREAD

**Issue by wnmills3** [Automattic/mongoose#9948]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
A collection has records with a type field that is "A" or "B". There are other common fields in these records, but each type has a set of mutually exclusive fields as well. I can try to define a discriminator on the "type" field with the shared fields in my base schema, and the exclusive fields in the two additional schemas for A and B respectively. The collection already exists with disparate records and I can access them using the base model, but I can't use the derived A or B model to find records even though the type field exists. I do not want to add an artificial __type field to distinguish. I want to specify the value of my discriminator field on the A and B schemas (like an option for discriminatorValue:"A" for the A schema, and discriminatorValue: "B" for the B schema. 

**What is the expected behavior?**

I had hoped that simply specifying the option for discriminator: "type" would be sufficient to cast the existing records in the existing collection correctly. I can see there would be some potential nuanced issues with trying to discern how types might be split against the different schemas. So, it would be easier to specify the value of the type to associate with each schema.

Being able to add these views to subset the content in the existing collection would be nice as I wouldn't necessarily need to change the existing applications that are writing to the underlying mongo database (provided they consistently write the type field's value correctly).

As I port from mongodb APIs to mongoose the discriminatorValue would be ensured to be present when using that view's model. For records that don't match the discriminatorValue they would not be accessed as part of that view.

The discriminator came really close to providing what I needed, but I don't want to change the underlying collection's records -- I merely want to leverage them from mongoose's perspective to automatically apply the selection of / addition of the discriminatorValue when working through mongoose. If the record I supply has the discriminator and a value and the value doesn't match the discriminatorValue then an error should occur for updates.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node 14.15.0
MongoDB 4.4.3
Mongoose 5.11.17

**Comment by vkarpov15** [comment]
I'm not sure I understand your issue, would you be able to provide some code samples?

Perhaps you're looking for the [`discriminatorKey` schema option](https://mongoosejs.com/docs/guide.html#discriminatorKey) or the [`value` parameter to `Model.discriminator()`](https://mongoosejs.com/docs/api/model.html#model_Model.discriminator)? The combination of those two should be flexible enough to create discriminators regardless of what property you're using as the record's type and what values that property has. 

```javascript
const baseSchema = new Schema({}, { discriminatorKey: 'type' }); // Use `type` as the field that stores the discriminator's type
const BaseModel = mongoose.model('Base', baseSchema);

const personSchema = new Schema({ name: String });
const Person = BaseModel.discriminator('Person', personSchema, 'A'); // Use the 'Person' discriminator if `type === 'A'`
```

Does that help?
