### ISSUE TITLE
custom schema type api

### ISSUE THREAD

**Issue by aheckmann** [Automattic/mongoose#995]

**Comment by nottinhill** [comment]
@aheckmann your tests fail against Mongoose versions later than 3.0.0alpha which is listed as a dependency in your project. Any plans to make your plugin compatible to 4.x?

**Comment by aheckmann** [comment]
@nottinhill I'm not planning on touching any of my mongoose plugins anymore (don't use mongoose). I'm happy to give you commit access if you like.

**Comment by vkarpov15** [comment]
@aheckmann I will gladly take you up on that offer of push access to mongoose-long, but only if you give me push access to [muri](https://www.npmjs.com/package/muri) too please :)

**Comment by nottinhill** [comment]
@vkarpov15 Indeed mongoose-long is the more tidier plugin compared to mongoose-currency (albeit doing different things), so if you could mongoose-long to test against Mongoose 4.0.1 I would gladly work from there and re-vamp mongoose-currency.

**Comment by aheckmann** [comment]
@vkarpov15 done

**Comment by whitecolor** [comment]
Are custom types support for props are goingo to land anytime soon?

**Comment by vkarpov15** [comment]
Possibly, I haven't really had a chance to research what it would take to make this work properly.
