### ISSUE TITLE
feat: Access documents for query and model middlewares 

### ISSUE THREAD

**Issue by khaledosama999** [Automattic/mongoose#9954]
### Feature
I noticed for document middleware (events that are concerned with only **one** document) the passed-in function for the hook has access to that document. Why isn't that available for query and model middleware too, I understand that it will require an extra database call to get those documents but it would be nice to have that option for those who need it.

### Use Case
A lot of e-commerce website use services like algolia or elastic search to improve their search experience, which requires migrating data from one source (mongo for example) to their service, and obviously keeping these two data sources in sync is another problem plus a single entity can be updated from different places so it's hard to remember each time that you should also update that entity in your search service. So it would be nice to have it run as a side effect (as middleware) for the appropriate hook and not to worry about it too much.

**Comment by vkarpov15** [comment]
Post hooks do have access to the "updated documents" in certain cases, like `findOneAndUpdate()` or `insertMany()`. We recommend using a post hook to do this sort of syncing, if you choose to use Mongoose for that :+1:
