### ISSUE TITLE
document.remove() removes document when session is aborted

### ISSUE THREAD

**Issue by mmoron** [Automattic/mongoose#9956]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
When using `Connection#transaction(...)` removed documents are deleted from db even if error is thrown. When using `session.withTransaction(...)` documents are not removed.

**If the current behavior is a bug, please provide the steps to reproduce.**

I remove document inside a session started using `connection#transaction` and immediately throw an exception:
```
const session = await connection.startSession();
await connection.transaction(async () => {
    const processes = await ProcessModel.find({ _id }, {}, { session });
    await processes[0].remove({ session });
    throw new Error('boom');
});
```
even though transaction should fail, the document is still deleted from db. I've also tried deleting using `deleteOne` with same result:
```
const session = await connection.startSession();
await connection.transaction(async () => {
    const processes = await ProcessModel.find({ _id }, {}, { session });
    await ProcessModel.deleteOne({ _id }, { session });
    throw new Error('boom');
});
```
If instead of using `connection#transaction` I use `session#withTransaction` everything works:
```
const session = await connection.startSession();
await session.withTransaction(async () => {
    const processes = await ProcessModel.find({ _id }, {}, { session });
    await processes[0].remove({ session });
    throw new Error('boom');
});
```

**What is the expected behavior?**
document should not be removed if there was an error thrown before transaction was finished

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.11.17, node.js 12.18.4, mongo: 4.4.3 Enterprise

**Comment by mmoron** [comment]
So, I'm not sure what exactly is needed for a repro script. It should be as simple as this:

```
const ReproSchema = new Schema(
    {
        field: { type: String },
    },
    { optimisticConcurrency: true },
);
const ReproModel = mongoose.model('Repro', ReproSchema);

const x = new ReproModel({ field: 'abc' });
await x.save();

try {
    const session = await connection.startSession();
    await connection.transaction(async () => {
        const repros = await ReproModel.find({ field: 'abc' }, {}, { session });
        await repros[0].remove({ session });
        throw new Error('boom');
    });
} catch {}

const afterRemove = await ReproModel.find({ field: 'abc' }, {});
console.log(afterRemove.length); // should be 1, but is 0

```

If you substitute `await connection.transaction(async () => {` with `await session.withTransaction(async () => {` it works.

**Comment by IslandRhythms** [comment]
mongoose creates a new session for you when you use the transaction function, so you don't need that variable. Instead, you take it as a parameter. Furthermore, the error you are throwing will never be reached because the line above it will throw an error and execute the catch block. Make sure to log the error in the catch block to ensure there are no other problems.
```
const mongoose = require('mongoose');

mongoose.connect("mongodb://localhost:27017/", { useNewUrlParser: true, useUnifiedTopology: true });
const connection = mongoose.connection;
connection.dropDatabase();

const ReproSchema = new mongoose.Schema(
  {
      field: { type: String },
  },
  { optimisticConcurrency: true },
);
const ReproModel = mongoose.model('Repro', ReproSchema);


async function part2() {
  const x = new ReproModel({ field: 'abc' });
  await x.save();
  try {
    // const session = await connection.startSession();
    await connection.transaction(async (session) => {
      
        const repros = await ReproModel.find({ field: 'abc' }, {}, { session });
        await repros[0].remove({ session });
        throw new Error('boom'); // does nothing because ↑ will cause the error
    });
    console.log('hi');
  } catch(err) {
    console.log(err);
    console.log('hello');
  }
  
  const afterRemove = await ReproModel.find({ field: 'abc' }, {});
  console.log(afterRemove.length); // should be 1, but is 0
}

part2();
```
