### ISSUE TITLE
Mongoose.connect upon failing crashes the server despite being wrapped in a try catch block

### ISSUE THREAD

**Issue by Twiggeh** [Automattic/mongoose#9957]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Crashes upon not being able to connect, despite being in a try catch block

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
// Connect to database
(async (): Promise<void> => {
	try {
		await mongoose.connect(mongooseKey, {
			useNewUrlParser: true,
			useUnifiedTopology: true,
			useFindAndModify: false,
		});
	} catch (e) {
		console.error('Mongoose failed to connect');
		console.error(e);
	}
})();
```
Compiled js version:
```js
(async () => {
    try {
        await mongoose.connect(mongooseKey, {
            useNewUrlParser: true,
            useUnifiedTopology: true,
            useFindAndModify: false,
        });
    }
    catch (e) {
        console.error('Mongoose failed to connect');
        console.error(e);
    }
})();
```

```json
{
	"compileOnSave": false,
	"compilerOptions": {
		"allowJs": true,
		"target": "esnext",
		"lib": ["ESNext"],
		"types": ["node"],
		"moduleResolution": "Node",
		"baseUrl": ".",
		"module": "ESNext",
		"noImplicitAny": true,
		"sourceMap": true,
		"allowSyntheticDefaultImports": true,
		"outDir": "dist"
	},
	"exclude": ["./node_modules/", "./dist", "./scripts"]
}
```

**What is the expected behavior?**
To not crash the server upon "Invalid Connection String"
 
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

NodeJS: 15.8.0
MongoDB : ? Using Atlas
Mongoose : '5.11.17'

**Comment by ShadiestGoat** [comment]
I can confirm that mongoose errors in general crash the process. I had this happen with FindOne when I threw an error. I think there is supposed to be an error catching event (`db.on("error", (err) => {})` I think, don't quote me on that), which may prevent this

**Comment by Twiggeh** [comment]
> I can confirm that mongoose errors in general crash the process. I had this happen with FindOne when I threw an error. I think there is supposed to be an error catching event (`db.on("error", (err) => {})` I think, don't quote me on that), which may prevent this

I don't think I am getting a db instance, when I dont pass connection but I might be wrong ...

[Any who, per documentation this should catch the errors and not crash the process](https://mongoosejs.com/docs/connections.html#error-handling)

![Documentation on error handling .connect ](https://user-images.githubusercontent.com/23149166/108722455-77413780-7523-11eb-8c86-a40ed02581e6.png)

**Comment by Twiggeh** [comment]
=== I was not wrapping MongoDBStore ===
