### ISSUE TITLE
Creating a Mongoose BulkWrite Plugin

### ISSUE THREAD

**Issue by BannerwiseMZL** [Automattic/mongoose#9970]
**Do you want to request a *feature* or report a *bug*?**

Bug (I think)

**What is the current behavior?**

https://stackoverflow.com/questions/66383607/creating-a-mongoose-bulkwrite-plugin

**If the current behavior is a bug, please provide the steps to reproduce.**

https://stackoverflow.com/questions/66383607/creating-a-mongoose-bulkwrite-plugin

**What is the expected behavior?**

Every time a document is created or updated the updatedAt date is set to now

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node 8
mongoose 5.9.6
mongodb 3.3.0-beta2

AND

node 14
mongoose 
mongodb 3.6.4

**Comment by AbdelrahmanHafez** [comment]
I answered your question on SO.
You can pass `{ timestamps: true }` as a second argument to your schema and mongoose will automatically update the `updatedAt` field on updates, whether `bulkWrite`, `updateOne`, or `updateMany`.

**Comment by BannerwiseMZL** [comment]
@AbdelrahmanHafez I've replied in SO. Hope it's makes sense and I hope there's a simple solution for me. Thanks again.

**Comment by AbdelrahmanHafez** [comment]
According to SO discussion, this is the same as https://github.com/Automattic/mongoose/issues/6861, let's follow progress there.

**Comment by BannerwiseMZL** [comment]
I see In the end the expectations are the same, that's true, but this issue is about the plugin not working. My solution to the problem is to write a plugin for the updateOne operation. Do you know if that potentially will works or is it the same as setting timestamps to true? Meaning it will always trigger also when upserted.

**Comment by vkarpov15** [comment]
On SO it looks like you expect `schema.post('updateOne')` hooks to fire when you use `bulkWrite()`. That is not the case. You'll need to use a `post('bulkWrite')` hook.
