### ISSUE TITLE
Question about "justOne" in populated virtuals

### ISSUE THREAD

**Issue by shubham0804** [Automattic/mongoose#9974]
**Do you want to request a *feature* or report a *bug*?**
Just wanted to ask a quick question. When specifying "justOne" for virtual, what is the criteria which mongoose uses to return the populated document. Is it the last created document? If not, can the last created document be retrieved? 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
mongoose: 5.11.15
node: 14.15.0

**Comment by vkarpov15** [comment]
There's no guarantee what document Mongoose will return unless you use `sort`. Without sort, it's up to MongoDB's [natural order](https://docs.mongodb.com/manual/reference/operator/meta/natural/), which is unpredictable.

Use `schema.virtual(myVirtual, { ...options, justOne: true, options: { sort: { createdAt: -1 } } })` to make Mongoose use the most recently created document according to [mongoose timestamps](https://masteringjs.io/tutorials/mongoose/timestamps).
