### ISSUE TITLE
Is there any way to pre save the element of object?

### ISSUE THREAD

**Issue by amankumar6** [Automattic/mongoose#9976]
Is there any way to pre save the element of object which is in an array?
```
const userSchema = new mongoose.Schema({
    name: {
        type: String,
        trim: true,
        required: 'Please Enter your Name',
    },
    items: [
        {
            iteamName: String,
            date: Date,
            price: Number,
            slug: String,
        },
    ],
});
```

Can I do this to pre save?

```
userSchema.pre('save', function (next) {
    this.items.$.slug = slug(this.items.$.itemName);
    next();
});
```

**Comment by vkarpov15** [comment]
Can you please elaborate? I don't understand what it means to "pre save the element" or what `this.items.$.slug` is supposed to do.

**Comment by amankumar6** [comment]
`Pre` is a middleware function. 
We can use it like this
```
schema.pre('save', function(next) {
  // do stuff
  next();
});
```
you can read it here:-  https://mongoosejs.com/docs/middleware.html#pre
I am trying to save `items.slug` to `slug(items.itemName)` but I am not able to do that.

**Comment by vkarpov15** [comment]
Is this what you're looking for?

```javascript
schema.pre('save', function(next) {
  for (const item of this.items) {
    item.slug = slug(item.itemName);
  }
  next();
});
```

**Comment by amankumar6** [comment]
yes, thanks a lot!
