### ISSUE TITLE
High number of connections : Serverless App / MongoDB Atlas

### ISSUE THREAD

**Issue by ErnestBrandi** [Automattic/mongoose#9987]
**Do you want to request a *feature* or report a *bug*?**
This is not a bug, but somehow a bad configuration leading to a bad result I suppose. Also I am aware this is kind of a common issue which is partly due to my app being serverless.
I have read number of threads about it, especially this one : https://github.com/Automattic/mongoose/issues/8805, and the linked Mongoose doc : https://mongoosejs.com/docs/lambda.html

**What is the current behavior?**
I am developing a website with the following stack : React.js, Next.js, Node.js; the website is hosted on Vercel (which rely on AWS lambda itself) and I use MongoDB Atlas as a remote database. 

When I first deployed in production, I noticed a very high number of connections on my cluster. After a while I started suspected mongoose so I deployed 2 simple examples from the next.js repo (https://github.com/vercel/next.js/tree/canary/examples); one is an example with mongodb only (`with-mongodb`) the other with mongoose (`with-mongodb-mongoose`). 

Browsing the two websites in production I could notice ;
- the one using mongodb only would never hit more than **7 connections**,
- the one using mongoose could hit more than **50 connections**...

I have tried the following connect options : 
```
{
        // ...
        bufferCommands: false, // Disable mongoose buffering
        bufferMaxEntries: 0, // and MongoDB driver buffering
}
```
and I have also tried to use `mongoose.createConnection` instead of `mongoose.connect`, but the result is the same.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just deploy the 2 example repos on Vercel and link them to different MongoDB Atlas clusters.

**What is the expected behavior?**
I would like mongoose to behave the same way mongoDB does.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
From Vercel webiste, Node : **14.x** (default since February 4th 2021)
Mongoose : 5.11.18
MongoDB : 3.6.4

**EDIT** : I have just realized the `with-mongodb` example on the Next.js repo is not a perfect replica of the `with-mongodb-mongoose` one, so I have made a repo where I have just replaced mongoose calls with mongodb ones : https://gitlab.com/leotellier/with-mongodb-test

**Comment by vkarpov15** [comment]
I took a closer look and it seems like it's just Vercel's example doesn't correctly persist state between lambda invocations. I put in a PR to improve that, but you can also use the approach from [our Lambda docs](https://mongoosejs.com/docs/lambda.html).

**Comment by ErnestBrandi** [comment]
Hi, thanks for looking into this. 
I looked at the PR you opened, and you seem to blame hot reloading (which is a development option).
The problem I currently face on the other hand, is in production. 
I do not know if the example in the `with-mongoose` example is correct for prod anyway; but as I stated in my previous post, I took notice of the `mongose lambda doc` and tried this method already with no better result. 
I can setup and deploy a repro case and take a screenshot of the number of connections in my cluster if needed.

**Comment by Mihai-github** [comment]
Hi @ErnestBrandi,

     I'm currently dealing with a similar problem building an App using MongoDB Atlas and Next.js.
     My problem is I see even though I'm caching the DB instance when doing the build with Vercel the number of active connections to the DB increases and stays around let's say ~20 ish active connections. Still, from nowhere the build also started being really really slow from ~8M to 45M and crashing afterward because It took too much.
     
     Why did this start to happen and maybe the solution to the problem?
