### ISSUE TITLE
Missing feature that was supposed to be deployed 

### ISSUE THREAD

**Issue by khaledosama999** [Automattic/mongoose#9991]
Sorry for this unnecessary issue but isn't this [PR](https://github.com/Automattic/mongoose/pull/9902) supposed to be part of the latest release (5.11.18) I keep finding myself needing it

**Comment by vkarpov15** [comment]
No, it is in the 5.12 branch, and we'll release it with 5.12.0 within the next couple of weeks. Thanks for your patience :+1:
