### ISSUE TITLE
how to populate virtual fields in the response of create document

### ISSUE THREAD

**Issue by NitinMagdum** [Automattic/mongoose#9992]
https://github.com/Automattic/mongoose/issues/3225 

as per this its working perfect the data from field is getting populated in virtual field in case of getById

```javascript
var countrySchema = new mongoose.Schema({
    capitalId: {type:String}
});

countrySchema.virtual('capital',{
    ref: 'City',
    localField: 'capitalId',
    foreignField: '_id',
    justOne: true
});

countrySchema.set('toObject', { virtuals: true });
countrySchema.set('toJSON', { virtuals: true });

Country.find().populate('capital') 
```

======================

what about create case after create in response if i want the virtual field to get populated.

i added following code for that but its not working

countrySchema.post("save", async function(){
        await this.populate({ path: "capital", model: "City" }).execPopulate(); 
})

**Comment by vkarpov15** [comment]
@NitinMagdum can you please clarify what you mean by "not working" and provide a full code sample?

**Comment by NitinMagdum** [comment]
Take same example 

Get API call --
Country.find().populate('capital')  -- as we have mentioned in schema capital as virtual field /alias which points to  capitalId local field and _id foreign field from City collection so in query result will get city details in virtual field capital


Now in case of Post method whatever result i get in that also i want to populate the same way on newly created country.
 is there any way to achieve this.  newCountry.save({countryName:"ABC", capitalId:"6047185772ecaa9015a369af"})
 want the virtual field should get populated in the result of newly created document.

**Comment by indraraj26** [comment]
Hi @NitinMagdum ,

Can you test this and let us know

```
const mongoose = require('mongoose');

let CountrySchema = new mongoose.Schema({
    capitalId: mongoose.Types.ObjectId
}, {
    toJSON: {virtuals: true},
    toObject: {virtuals: true},
});

CountrySchema.virtual('capital', {
    ref: 'City',
    localField:  'capitalId',
    foreignField: '_id',
    justOne: true
})

let CitySchema = new mongoose.Schema({
    name: String
});


run().catch((err) => console.log(err));

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
    });
    await mongoose.connection.dropDatabase();

    const CountryModel = mongoose.model('Country', CountrySchema);
    const CityModel = mongoose.model('City', CitySchema);
    const cityRes = new CityModel({ name: 'Mumbai' });
    const savedCity = await cityRes.save();
    const countryRes = new CountryModel({capitalId: savedCity._id});
    const savedCountry = await countryRes.save();
    const getPopulateResult = await savedCountry.populate('capital').execPopulate();
    console.log(getPopulateResult)
}

```

**Comment by NitinMagdum** [comment]
ok so here you are first saving the document and again making another request to populate the virtual field. 
i was checking if there is a way in the save response itself we can populate the field instead of making another request
Thanks.

**Comment by indraraj26** [comment]
@NitinMagdum whatever you will do you are going to make another request in order to get the data from another collection.

As per your initial post, This will work
```
const mongoose = require('mongoose');

let CountrySchema = new mongoose.Schema({
    capitalId: mongoose.Types.ObjectId
}, {
    toJSON: {virtuals: true},
    toObject: {virtuals: true},
});

CountrySchema.virtual('capital', {
    ref: 'City',
    localField:  'capitalId',
    foreignField: '_id',
    justOne: true
})

CountrySchema.post('save', async function() {
   await this.populate('capital').execPopulate();
})

let CitySchema = new mongoose.Schema({
    name: String
});


run().catch((err) => console.log(err));

async function run() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useNewUrlParser: true,
        useUnifiedTopology: true,
    });
    await mongoose.connection.dropDatabase();
 
    const CountryModel = mongoose.model('Country', CountrySchema);
    const CityModel = mongoose.model('City', CitySchema);
    const cityRes = new CityModel({ name: 'Mumbai' });
    const savedCity = await cityRes.save();
    const countryRes = new CountryModel({capitalId: savedCity._id});
    const savedCountry = await countryRes.save();
    console.log(savedCountry, 'savedsavedCountry')
}

```

**Comment by NitinMagdum** [comment]
Thanks @indraraj26 @vkarpov15 @IslandRhythms
