### ISSUE TITLE
'Child' flattenMaps is not taken into account when calling toObject on 'Parent'

### ISSUE THREAD

**Issue by andreafdaf** [Automattic/mongoose#9995]
**Do you want to request a *feature* or report a *bug*?**
Bug?

**What is the current behavior?**
If I have a model "Parent" that references a model "Child", and I've set ```ChildSchema.set('toObject', { flattenMaps: true })```, when I call ```parentDocument.toObject()``` the options set on "Child" toObject are not taken into account, so I have to set ```flattenMaps``` on all models that might be related to other models with Map in them

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/andreafdaf/bb533ef53178bdabe102e77f8843db9b

**What is the expected behavior?**
I would expect that, if Child has ```flattenMaps``` set to true, calling ```toObject``` on Parent would use the Child's toObject when converting the Child

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
NodeJS: v14.15.1
Mongoose: mongoose@5.11.18
MongoDB: 4.0.23 Enterprise

**Comment by IslandRhythms** [comment]
```
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;



const MapSchema = new Schema({
  value: { type: Number },
}, { _id: false });

const ChildSchema = new Schema({
  map: { type: Map, of: MapSchema },
});
ChildSchema.set('toObject', { flattenMaps: true });

const ParentSchema = new Schema({
  child: { type: Schema.ObjectId, ref: 'Child' },
});

const run = async () => {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  await mongoose.connection.dropDatabase();

  mongoose.model('Child', ChildSchema);
  mongoose.model('Parent', ParentSchema);

  const ChildModel = mongoose.model('Child');
  const ParentModel = mongoose.model('Parent');

  await ChildModel.deleteMany({});
  await ParentModel.deleteMany({});
  const childDocument = new ChildModel({ map: { first: { value: 1 }, second: { value: 2 } } });
  await childDocument.save();

  const parentDocument = new ParentModel({ child: childDocument });
  await parentDocument.save();

  const resultDocument = await ParentModel.findOne().populate('child').exec();

  const resultObject = resultDocument.toObject();

  console.log(resultObject); // resultObject.child.map is not a POJO
}
run().catch(err => console.log(err));
```
