### ISSUE TITLE
isValidObjectId giving false negative for certain ObjectIds

### ISSUE THREAD

**Issue by loucadufault** [Automattic/mongoose#9996]
Report a bug.

### Current behavior

I am using mongoose's isValidObjectId to check that a string (provided as a part of a request body) is a valid object id because it is set as the reference property of a document. This is meant as a preventative step to sanitize the API input and catch bad id strings before mongoose's "Cast to ObjectId failed for value ... at path ..." error is thrown by mongoose when casting the string to an ObjectId.  I am using mongoose's `isValidObjectId` as specified [in the docs](https://mongoosejs.com/docs/api/mongoose.html#mongoose_Mongoose-isValidObjectId). 

However, there are certain id strings for which `isValidObjectId` returns true, but when an ObjectId type prop on a document is set to this string, saving the document still throws a ValidationError. 

### Steps to reproduce

```
const userSchema = new Schema({
  name: { type: String, required: true },
});
const User = mongoose.model("User", userSchema);

const boardSchema = new Schema({
  name: { type: String, required: true },
  ownerId: { type: Schema.ObjectId, required: true, ref: "User" },
});
const Board = mongoose.model("Board", boardSchema);

const board = await Board.findOne({ _id: "6029f05a87016a1262304d6e" }).exec(); // assume there exists a board with this id

const badIdString = "6029f05a87016a5662304t6e"; // a sample id string that cannot be cast to ObjectId but passes the isValidObjectId check

if (isValidObjectId(badIdString)) { // returns true
  board.ownerId = badIdString; 

  await board.save(); // throws ValidationError
}
```

### Expected behavior

That `isValidObjectId` should return false for a given id string if it can't be cast to an ObjectId, per the documentation: "Returns true if Mongoose can cast the given value to an ObjectId, or false otherwise."

### Versions

Node.js v14.15.0
Mongoose v5.11.15
MongoDB v4.4.1

**Comment by IslandRhythms** [comment]
very strange
```
'use strict';
  
const mongoose = require('mongoose');

mongoose.set('useFindAndModify', false);

const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const boardSchema = new Schema({
    name: { type: String, required: true },
    ownerId: { type: Schema.ObjectId, required: true, ref: "User" },
  });
  const Board = mongoose.model("Board", boardSchema);
  const badIdString = "6029f05a87016a5662304t6e";
  await Board.create({name: 'Test', ownerId: '123456789012'});
  const board = await Board.findOne({name: 'Test'});
  if(mongoose.isValidObjectId(badIdString)) {
    board.ownerId = badIdString;
  }
  await board.save();
};
```
